### ISSUE TITLE
How to include a new map?

### ISSUE THREAD

**Issue by sequencer** [thingsboard/thingsboard#100]
There is some problem in [openstreet](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China)
and the GFW have fucked off the Google Map...
So I wanna to include a new map like [BAIDU Map](https://www.slideshare.net/CatChen/baidu-map-api-introduction-5939794) which works fine in China, and also provides APIs.
Is there a document to introduce how to include new map js?

**Comment by haibaoyf** [comment]
use“opensteet-map”，or change"https://maps.googleapis.com/maps/api/js?key=" to"http://ditu.google.com/maps/api/js?key=" at "/ui/src/app/widget/lib/google-map.js"raw 123

**Comment by ashvayka** [comment]
You can review /ui/src/app/widget/lib/google-map.js and add your own map component/widget based on this script

**Comment by sequencer** [comment]
alright got it need i recompile all project or just hot add it to software file?

**Comment by huily6** [comment]
Have you succeeded in adding Baidu maps? I have this plan now, if you want to make a reference to it, thank you.

**Comment by haibaoyf** [comment]
不好意思，我这里还是使用的谷歌地图，目前谷歌留了国内地图接口www.google.cn/maps，可以正常使用
关键我是做嵌入式设计的，java js这些都不懂





在 2017-05-09 09:56:46，"daisy" <notifications@github.com> 写道：


Have you succeeded in adding Baidu maps? I have this plan now, if you want to make a reference to it, thank you.

**Comment by stormwrym** [comment]
Have you succeeded in adding Baidu maps? I have this plan now, if you want to make a reference to it, thank you.

**Comment by stormwrym** [comment]
Have you succeeded in adding Baidu maps? I have this plan now, if you want to make a reference to it,  
email yyd_cqdxc@163.com     thank you.

**Comment by stormwrym** [comment]
I  have succeeded in adding Baidu maps ,however  ,I can't create Baidu marker.

**Comment by CharlotteEGM** [comment]
Do you have a reference on how you did it ?

**Comment by vparomskiy** [comment]
Close this thread since no active anymore.
