### ISSUE TITLE
[Question] Add customer attributes with rule chains

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#10004]
**Component**

 * Rule Chains

**Description**
Is there a way to add a new attribute when a entity type equals Customer is created ? 

I only find a way to add attributes (cliente, server and shared) in Devices.

Customers seems note have the attributes scopes like Devices.

![image](https://github.com/thingsboard/thingsboard/assets/7483656/9ca9a334-cde5-4377-921b-6f6893c9f602)
![image](https://github.com/thingsboard/thingsboard/assets/7483656/38db3753-c46f-473c-ab64-0b5775ee8d1c)

**Environment**

 * ThingsBoard Cloud Prototype

**Comment by devaskim** [comment]
All entities except device have only server attributes. 
![Скриншот 17-01-2024 121907](https://github.com/thingsboard/thingsboard/assets/86909129/a5d51811-d6cf-4882-9242-9a518193d290)

**Comment by lstarke** [comment]
Thank you @devaskim. I probably was blind to not see the big Server attributes label there.

**Comment by AndriichnekoDm** [comment]
Hi @lstarke!
We appreciate that you are using our product!
Can I assume that your question is resolved?

**Comment by Faheem-Punnasseri** [comment]
Hi @lstarke,

Is the updating of **customer attributes** using the transformation script working fine for you?
