### ISSUE TITLE
Pulling data from one state to another without stateParams.

### ISSUE THREAD

**Issue by VidorGurovich** [thingsboard/thingsboard#10006]
* Generic

**Description**
I have 2 states A,B
State B has 2 widgets

State A has stateParams to pull data into it.
State B's widget 1 is pulling through the stateParams from state A
State B's widget 2 is using a different stateParam to display other data.

Is there a way i can display some of widget 1's data on widget 2 on state B?

**Comment by devaskim** [comment]
1. Is it the same entity on A and on B widget 1?
2. How to you go from A to B ?

**Comment by VidorGurovich** [comment]
- they have different entity aliases
- I move from A to B using a button

**Comment by devaskim** [comment]
> they have different entity aliases
Is there any link between those entities? (relation or maybe something else)

> I move from A to B using a button
Is it some custom code behind it or standard TB action to open new dashboard state?

**Comment by VidorGurovich** [comment]
- No link between the entities.
- Just a standard TB action to open new state

**Comment by devaskim** [comment]
> Just a standard TB action to open new state

If this action uses `Set entity from widget` (checkbox is checked), so you just need to create widget alias called `Entity from dashboard` and use it in B widget 1 to get data keys of the entity from A

**Comment by VidorGurovich** [comment]
The action does indeed use the `set entity from widget`. So that data is being passed to widget 1. 
Widget 2 is using a different entity alias for 95% of its data and i need to just get the last 5% from widget 1 (whos data is passed from state A)<-- this is the issue.

**Comment by VidorGurovich** [comment]
I am using custom actions on state B. Is there maybe something i could use there to pull in the data?

**Comment by devaskim** [comment]
> Widget 2 is using a different entity alias for 95% of its data and i need to just get the last 5% from widget 

I was about that due to `Set entity from widget` feature state B knows about entity from state A, so if widget 2 on state B supports multiple entities, so you can get in this widget data keys both from entity A and from `a different entity alias`.

So is widget 2 custom or some standard widget?

**Comment by devaskim** [comment]
Hm, as entity from A is single, maybe just add widget 3 and display the entities' data?

**Comment by devaskim** [comment]
By the way what data kind of data do you need from that entity (name/label, or timeseries/attributes)

**Comment by VidorGurovich** [comment]
The widget 2 is used to view the data but also to add to and delete the data so just being able to view the entities data wouldnt work unfortunately. 

And the data i need from the entity is the ${Name} that is being passed through from state A.

**Comment by devaskim** [comment]
Again due to `Set entity from widget` you can get name of entity from state A 
```
<widgetContext>.stateController.getStateParams().entityName
```

**Comment by VidorGurovich** [comment]
so when i use the <widgetContextObject> it says issues so then i put widgetContextObject and said that it doesnt exist so then i used 
zone = widgetContext.stateController.getStateParams().entityName;

But when i set a text box to zone then it shows nothing. Any ideas?

**Comment by devaskim** [comment]
>  widgetContextObject and said that it doesnt exist so then i use

I write `<widgetContextObject>` because I didn't know if you have access to the widget context via `self.ctx` or directly `widgetContext`. Copypasting is a bad idea sometimes ;)

> Any ideas?

To debug, print state params to browser console
```
console.log('State 1', widgetContext.stateController.getStateParams())
console.log('State 1.1', widgetContext.stateController.getStateParamsByStateId(widgetContext.stateController.getStateId()))
```

**Comment by VidorGurovich** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/152860387/c0b39cf9-d2d1-4170-b8d3-5981a4e91589)
i need to access the data saying Vidors Building if its possible

**Comment by VidorGurovich** [comment]
when i try:
console.log('State 1', widgetContext.stateController.getStateParams().entityName)
it then gives me an undefined

**Comment by devaskim** [comment]
So your action configuration is a bit different. You set the option called `State entity parameter name` to `SelectedBuildingParameter`, this is why you get `undefined`
 
> i need to access the data saying Vidors Building

It is simple JS:
```
widgetContext.stateController.getStateParams().SelectedBuildingParameter.entityName`
```

**Comment by VidorGurovich** [comment]
You are the GOAT! Thank you so much for being so patient with me. Im still learning a lot but this is going to help me immensely.
Have the best day further.
