### ISSUE TITLE
How do I assign realtionship from an asset to an asset

### ISSUE THREAD

**Issue by VidorGurovich** [thingsboard/thingsboard#10001]
* Generic

**Description**
So I've got a thingsboard dashboard that allows you to create building assets. Now i need to create zones for the buildings so I'm trying to assign relations here so that the zone can be tied to a specific building. How do i go about doing this. I have the building asset created but I'm struggling to understand the code that assigns relations.

So i need to click add zone. Then a pop up will appear saying name the zone and give us an image for your zone. Then when you click create it needs to link to the building that ive clicked into to create the zone.

**Comment by devaskim** [comment]
You need to call `self.ctx.entityRelationService.saveRelation()` Here is the [API ](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/entity-relation.service.ts#L33C10-L33C22)of the service.

**Comment by VidorGurovich** [comment]
Thank you so much I've gotten it to work! So now the next issue pops up. Is there a way to fetch data keys and/or data values from a different widget on the same page?

**Comment by devaskim** [comment]
No, as I know

**Comment by VidorGurovich** [comment]
Last question, if possible how would i go about using getStateParamsByStateId and what data could i retrieve using this.

**Comment by devaskim** [comment]
The original idea, in my understanding, was and is the resolution of widget's alias (e.g. `Entity from dashboard state` and others). But also state params can be used to pass various data between states, i.e. there is no restriction what to store in this object.

**Comment by VidorGurovich** [comment]
okay so ive got the data i need on a different state! Its stored in a Markdown/HTML Card its accesable here using ${Name}. How can i access this data and store it in a variable

**Comment by devaskim** [comment]
Hm, not sure I understand your challenge. I recommend closing this issue as resolved (because you are able to create relations) and then ping me in a new one. There you can describe in details what values and where you want to get them.

**Comment by VidorGurovich** [comment]
100% thanks again for your help
