### ISSUE TITLE
Rule Engine, Device Attribute Enrichment Nodes not working?

### ISSUE THREAD

**Issue by aderbas** [thingsboard/thingsboard#1001]
I try use Enrichment Device Attribute in my custom rule to add latest telemetry in metadata to get it on next node, but it not working. I created a simple device and send 'temperature' telemetry and on node "device attribute" in my rule I filtered device by type and try set 'temperature' on 'latest timesiries' field. When I save the changes on the node, the "temperature" field disappears. How it works?

![captura de tela de 2018-08-08 17 39 46](https://user-images.githubusercontent.com/12519019/43863100-073a6aba-9b32-11e8-819a-c198a9b5568c.png)

![captura de tela de 2018-08-08 17 24 17](https://user-images.githubusercontent.com/12519019/43862589-7817f4de-9b30-11e8-8e83-14092d1df995.png)

**Comment by aderbas** [comment]
Ops, my bad. After typing the variable, I forgot to press "Enter", i'ts a "usability bug"?

**Comment by ashvayka** [comment]
Yes, probably, but this is material design component.

**Comment by clydebarrow** [comment]
I also had this issue. This is a major usability issue, I've spent a couple of hours on it. At the very least the help should mention the fact you have to press enter.
