### ISSUE TITLE
[Question] Display dashboard screenshot in alarm emails?

### ISSUE THREAD

**Issue by PrecisionCannon** [thingsboard/thingsboard#10010]
**Component**

 * Rule Engine

**Description**
The tutorial on sending an image inside an email shows an example of a dashboard screenshot being sent. Is there a way to automatically take a screenshot when an alarm is created and send the screenshot in the email, or is the dashboard screenshot in the tutorial just an example of sending a static image?

**Environment**
Any

**Comment by sam19580** [comment]
@PrecisionCannon Can you please mention the steps to reproduce the issue?
