### ISSUE TITLE
[Bug] the settings in the Widget Settings schema are modified, but the 'Apply' button cannot be automatically enabled

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#10019]
**Describe the bug**
If the Settings schema is used in a widget, modifying its content in the dashboard does not automatically enable the 'Apply' button. It only triggers this behavior when switching to other setting tabs.

**Your Server Environment**

* own setup
  * Debian 10
  * 3.6.2

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Debian 11
* Browser Chrome

**To Reproduce**
1. Import the attached JSON in Widgets library
2. Open any dashboard
3. Step into edit mode and add the imported widget
4. After added, modify the widget
5. Change the "varstring", we can see it

**Screenshots**
![2024-01-19_10-44](https://github.com/thingsboard/thingsboard/assets/33717782/c58a090a-b874-47e9-a296-64c69ad82266)

**Comment by sumin-denys** [comment]
Hi @lsyer,

Thank you for your report! This issue has been confirmed. I've added this request to our backlog PROD-4974. 
I am closing this issue for now. If you need to update the status of the prod ticket, comment on this issue.

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
If you have any further questions, please feel free to create a new issue or reopen this one.
