### ISSUE TITLE
How to delete children assets when deleting parent asset

### ISSUE THREAD

**Issue by VidorGurovich** [thingsboard/thingsboard#10020]
**Component**
 * Generic

**Description**
I have a parent asset called building and this parent relates to child assets called zones. When i delete a building it needs to also delete the zones related to it, how do i go about this?

**Comment by devaskim** [comment]
There is no ready to use solution, in other words, you need to do it on your own.

**Comment by VidorGurovich** [comment]
thanks, i did indeed figure it out 💪 
Have a lovely day
