### ISSUE TITLE
[Bug] Password reset emails will not send in one environment (silent failure, no errors, no logs, only impacts password reset emails)

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#10033]
**Describe the bug**
Any attempt to send a password reset email from our dev VM fails silently. I can create a new user, send the activation email to that user, and receive alarm emails, but after attempting a password reset no email is sent. There is no error in the UI, and tb logs show no events related to email sending. Restarting the service or the VM has no impact. 

Password reset emails CAN be sent successfully from our production VM, which is essentially configured the same. There is something specifically wrong with the dev VM and I have run out of methods to troubleshoot

**Your Server Environment**

* own setup
  * google cloud VM
  * 3.6.2
  * Ubuntu 20.04.6 LTS

**Your Client Environment**

** not relevant, happens on any client

**To Reproduce**
- Go to login screen on our test server
- Press the reset password 

**Expected behavior**
I expect to get an email when I request one

*Context*
We have the same version of thingsboard running in our production VM and that does not exhibit the same problem. I can't tell what is different.

**Comment by ashvayka** [comment]
Is this CE or PE instance?

**Comment by ashvayka** [comment]
@dashevchenko , I suspect the "silent crash" may be here ( in case Exception is not ThingsboardException): 
Please fix this.

```
    @Override
    public void sendResetPasswordEmailAsync(String passwordResetLink, String email) {
        passwordResetExecutorService.execute(() -> {
            try {
                this.sendResetPasswordEmail(passwordResetLink, email);
            } catch (ThingsboardException e) {
                log.error("Error occurred: {} ", e.getMessage());
            }
        });
    }
```

**Comment by dashevchenko** [comment]
Fixed here https://github.com/thingsboard/thingsboard/pull/10055
