### ISSUE TITLE
thingsboard- telemtry full

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#10034]
Hi, when i checked by thingsboard, i could see the telemetry is full, and new values are not updating. i am using thingsboard prototype cloud edition. kindly suggest what to do.
![image](https://github.com/thingsboard/thingsboard/assets/49026279/f78634fd-35e6-4f94-abfd-495987fc6095)

**Comment by mykhailokornieiev** [comment]
Hi. In the case of thingsboard.cloud, if you have used the entire API limit for telemetry, it will be reset only when a new calendar month arrives (counted from the day the subscription started). Or you can upgrade your plan. 
https://thingsboard.io/products/paas/subscription/
![image](https://github.com/thingsboard/thingsboard/assets/115699895/d02d9fce-5772-4815-a60b-d300544ef4f3)
