### ISSUE TITLE
[Question] How to hide top toolbar

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#10031]
**Component**

 * UI

**Description**
Hi, I would like to mask the top toolbar or at least avoid redundancy of profil:
![entete](https://github.com/thingsboard/thingsboard/assets/103430329/fdab3fbb-9043-47fe-a91b-f203ba9e5627)

Where can I find this setting?
Thanks for your answers.

**Environment**

  * ThingsBoard: 3.5.1 PE

**Comment by devdoob** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/1464600/0a56f169-e517-45ce-b1e8-9dfd4e8742d7)


This usually doesn't happen. Looks like a cache issue. Do a CTRL_F5

**Comment by liotys** [comment]
> ![image](https://private-user-images.githubusercontent.com/1464600/298754387-0a56f169-e517-45ce-b1e8-9dfd4e8742d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTg1ODksIm5iZiI6MTcwNTk5ODI4OSwicGF0aCI6Ii8xNDY0NjAwLzI5ODc1NDM4Ny0wYTU2ZjE2OS1lNTE3LTQ1Y2UtYjFlOC05ZGZkNGU4NzQyZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDgyNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjExOWNjZmQ2ZGFmZjQxZjhjMDY1M2RiMmZlYTlkMjBkMjAzNjhhMzk3MmQ4NDAxNWIyYmI5NTVlNjRjZGRlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lfxVY9Ck7pdZsdBkGVoKjx_SznpdOYDeDY3W9imiSGg)
> 
> This usually doesn't happen. Looks like a cache issue. Do a CTRL+F5

Thanks @devdoob for your answer. I guess it's a lit bit more complicated.
When I am at tenant level it works like you. 
It's when the dashboard is chosen as dashboard home for a customer and when I'm connected with a user of the customer. 
If I choose the dashboard in the user profile (default and home) it works fine:
![entete2](https://github.com/thingsboard/thingsboard/assets/103430329/b2500aad-7219-4a44-b055-ede6244da532)
So I would like to choose the dashboard at customer level and not for each user...

**Comment by devdoob** [comment]
ok i get it. Then most probably you;re missing this part. check if you have enabled "Always Fullscreen". It should be checked.

![image](https://github.com/thingsboard/thingsboard/assets/1464600/f974bc61-0f57-4cc8-82b2-034b38280791)

for your second aprt:
Unfortunately customer default dashboard, doesn;t assigned atomatcally to its users. Either you have to manually do or automate it via custom actions in dashboard
