### ISSUE TITLE
Bug with the custom menus selection

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#10038]
How do I keep the custom menu expanded when I open the dashboard?

**Comment by mykhailokornieiev** [comment]
Hi
Please describe your request in as much detail as possible

**Comment by ashvayka** [comment]
Hi @h-takado, we understand your request and treat this as a bug. The behavior of custom menus should match the behavior of the original menu items. We will work to fix this.

**Comment by h-takado** [comment]
thank you!

**Comment by AndriichnekoDm** [comment]
Hi @h-takado.
After we reviewed the custom menu, our team decided to refactor this module into our next version 3.6.4
