### ISSUE TITLE
Importing existing database in Thingsboard

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#1003]
Is there an easy and fast way to import an exesting MySQL-database in Thingsboard?
Now I'm using a python script with MQTT to import all data. Problem is that it is a big database and this is going quite slow.

Any other solutions?

**Comment by eykamp** [comment]
It should be possible to directly insert your data into the TB database.
The structure is not complex.

On Thu, Aug 9, 2018, at 05:33, jensvdh15 wrote:
> Is there an easy and fast way to import an exesting MySQL-database in
> Thingsboard?>  Now I'm using a python script with MQTT to import all data. Problem
>  is that it is a big database and this is going quite slow.> Any other solutions?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/thingsboard/thingsboard/issues/1003
