### ISSUE TITLE
[Question] Navigation Card with no Icons

### ISSUE THREAD

**Issue by datguyhxnnxs** [thingsboard/thingsboard#10046]
**Component**
 * UI

**Description**
When using single navigations Cards the Icon does not scale with the window size. On smaller screens (13inch) the Icons are too big and the text is not visible anymore to the user.
1.) Is there a way to create a Navigation Card Widget with no Icon? 
2.) Is it possible to change the size of the icon, depending on window size?

![Bild_2024-01-24_104023826](https://github.com/thingsboard/thingsboard/assets/135652575/267ae91a-599b-4d89-ae62-912b4d568ff3)

**Comment by ashvayka** [comment]
We are working on a new navigation button widget that will scale. Meanwhile we will add this bug to our backlog

**Comment by datguyhxnnxs** [comment]
Okay, thank you for the quick response.
