### ISSUE TITLE
[Question] MQTT library for Arduino framework

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10054]
What is the recommended and mantained MQTT library to use in ESP32 with Arduino framework to connect to Thingsboard?

**Comment by imbeacon** [comment]
Hi @gcorthey,

Thank you for your interest in ThingsBoard IoT platform. To connect your device, based on ESP32, you can use [ThingsBoard Client SDK](https://github.com/thingsboard/thingsboard-client-sdk) library or you can use Arduino MQTT library with our [MQTT API](https://thingsboard.io/docs/paas/reference/mqtt-api/).
