### ISSUE TITLE
Enable separation of timeseries datastore and entities datastore

### ISSUE THREAD

**Issue by davidgin** [thingsboard/thingsboard#1005]
Currently the deployment of ThingsBoard can use either Cassandra data store or RDBMS.
While Cassandra is optimal for time series data, it lacks many features to support ThingsBoard entity model which is more relational in its nature.
The suggestion is to use 2 data stores simultaneously:
Cassandra API only for time series and RDBMS for all other entities.

**Comment by ashvayka** [comment]
Hi @davidgin 
We've introduced two annotations to control either Cassandra or SQL dao is used:
org.thingsboard.server.dao.util.SqlDao and org.thingsboard.server.dao.util.NoSqlDao.
I suggest to add two other annotations: SqlTsDao and NoSqlTsDao for timeseries data and add the corresponding parameter to thingsboard.yml. We may refactor "database.type" parameter in thingsboard.yml to "database.ts.type" and "database.entities.type".

Good luck with the implementation! Let's use this issue to discuss the implementation details!

**Comment by hagaic** [comment]
Hi @ashvayka 
I started implementing according to your suggestion.
I also added NoSqlAnyDao annotation for Cassandra infra classes like CassandraCluster and CassandraQueryOptions, which are needed both in database.type=cassandra and in hybrid mode.
Currently I'm trying to solve a problem with installation:
ThingsboardInstallService uses a single autowired DatabseSchemaService, so it can only be one of the two. In the hybrid configuration we need both.
Maybe instead of the polymorphic DatabseSchemaService use the two classes:

```
@Autowired(required = false)
private CassandraDatabseSchemaService cassandraDatabseSchemaService;

@Autowired(required = false)
private SqlDatabseSchemaService sqlDatabseSchemaService;
```

and then createDataBaseSchema() only for the non null?
What do you think?

**Comment by ashvayka** [comment]
Hi @hagaic 

I believe we need to create two separate classes/interfaces for each DB type:
CassandraDatabseSchemaService -> CassandraEntityDatabaseSchemaService
CassandraTsDatabaseSchemaService

SqlDatabseSchemaService -> SqlEntityDatabaseSchemaService
SqlTsDatabaseSchemaService

Each one will be responsible for the creation of the corresponding tables/column families and will be annotated with the same annotations as earlier proposed. 
Just to summarize: we separate creation of main entities db structure from creation of timeseries db structure. Do you agree?

**Comment by hagaic** [comment]
Hi @ashvayka 
So to elaborate this in details:
We will have 3 top DatabseSchemaService using 4 sub services:

1. CassandraDatabseSchemaService will delegate to CassandraEntityDatabaseSchemaService, CassandraTsDatabaseSchemaService.
2. SqlDatabseSchemaService will delegate to SqlEntityDatabaseSchemaService, SqlTsDatabaseSchemaService.
3. A new HybridDatabseSchemaService will delegate to SqlEntityDatabaseSchemaService, CassandraTsDatabaseSchemaService. 
HybridDatabseSchemaService will be annotated with a new HybridDao (database.enity.type==sql && database.ts.type==cassandra) 

Exactly one of the three top *DatabseSchemaService will be autowired into ThingsboardInstallService 

Each sub-service will be able to run independently (CREATE KEYSPACE IF NOT EXISTS)

schema.sql/cql and system-data.sql/cql - these 4 files will be broken into 2 files each (entity/ts), each used in one of the 4 sub-services.

**Comment by hagaic** [comment]
Hi @ashvayka 
After further thought, I want to handle the schema installation using a simpler design, without the "3 top DatabseSchemaService" layer:
ThingsboardInstallService will use two autowired services: EntityDatabseSchemaService & TsDatabseSchemaService (both interfaces are marker extensions of DatabseSchemaService), each wired with exactly one of two implementations.

@SqlDao class SqlEntityDatabaseSchemaService implements EntityDatabseSchemaService 
@NoSqlDao class CassandraEntityDatabaseSchemaService implements EntityDatabseSchemaService 

@SqlTsDao class SqlTsDatabaseSchemaService implements TsDatabseSchemaService 
@NoSqlTsDao class CassandraTsDatabaseSchemaService implements TsDatabseSchemaService
