### ISSUE TITLE
[Question] How to override/disable a default widget action?

### ISSUE THREAD

**Issue by DurandA** [thingsboard/thingsboard#10058]
**Component**

 * UI

**Description**
I want to hide the default action of a system widget (in my case a "Scheduler events" widget) in order to replace it with a custom action.

![image](https://github.com/thingsboard/thingsboard/assets/3709037/b134a415-6cdf-470f-8302-9b71455a02c3)

Is it possible to hide the default "Add scheduler event" action (or to replace it)?

I tried to create a custom action that uses the same name as the default action and it resulted in an undefined behavior: the default action with the same name was not displayed for some time, and then after a few renaming/reordering it made the default action reappears.

**Environment**

 * ThingsBoard: ThingsBoard: 3.6.1PE

**Comment by devaskim** [comment]
I guess it is only possible now with hiding via CSS.

**Comment by mykhailokornieiev** [comment]
Hi @DurandA 
Did you manage to test the solution provided above?

**Comment by dan-ind-tech** [comment]
I tried `display: none` to hide two of the "Export widget data" options and it works but only after 5-15 seconds have passed. 
Maybe I'm trying in the wrong spot?
Edit Widget > Appearence > Row style function

`let exportButtons = document.getElementsByClassName('mat-mdc-menu-item');
exportButtons[1].style.display = 'none';`
