### ISSUE TITLE
[Bug] Generate reportt

### ISSUE THREAD

**Issue by ohack38** [thingsboard/thingsboard#10067]
**Describe the bug**
When trying to generate a report as a pdf, the following happens: The page starts the generating process as it should but gets stuck at "Generating dashboard pdf..." and returns following error "Generate report timeout!"

In the console we get the following response
message: "Generate report timeout!"
errorCode: 2
status: 500

**Your Server Environment**
* cloud.thingsboard.io

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows & Mac
* Browser: Firefox & Chrome

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Download button'
3. Click on 'Export as PDF'

**Expected behavior**
Pdf should be generated and displayed on another tab.

**Screenshots**
![Screenshot 2024-01-26 114112](https://github.com/thingsboard/thingsboard/assets/51481416/6c4e3b1a-61f2-4a24-9500-445645cdba83)

**Additional context**

**Comment by mykhailokornieiev** [comment]
Hi
There was an issue with the web-report component on thingsboard.cloud, that is currently fixed. Please check if everything works correctly for now.

**Comment by ohack38** [comment]
Seems to be working as it should. Haven't gotten any errors anymore.

**Comment by ashvayka** [comment]
Hi @ohack38 , I am going to close this ticket. Meanwhile, we have identified several areas of improvement to make sure we do not have such issues in the future.

**Comment by kaichh** [comment]
Hi I'm still having issue generating certain dashboard on thiingsboard cloud. I tested on dashboard with 1 widget and it can export successfully. However, it can't export my dashboard with multiple charts and map widgets. I am assuming the server needs more time to process and it reaches the timeout limit?
