### ISSUE TITLE
Add partition granularity to time series data

### ISSUE THREAD

**Issue by davidgin** [thingsboard/thingsboard#1006]
Currently the partition granularity supports MINUTES, HOURS, DAYS, MONTHS and YEARS.
When dealing with infrequent  time series transmission rate resulting in less than 500000 values in the life span of the device, it is possible to optimize with a partition value 'INDEFINITE' to indicate a default partition value for the partition column and skip saving and querying the partition table.

**Comment by ashvayka** [comment]
Hi @davidgin . I believe this is a quite valid use case and you can suggest a PR based on modifications to CassandraBaseTimeseriesDao. I believe this is the only class you need to change (except adding tests)
