### ISSUE TITLE
[Question] Default TTL

### ISSUE THREAD

**Issue by Aimen-Hammou** [thingsboard/thingsboard#10086]
**Component**

 * Generic

**Description**
Hi.

I was reading the documentation regarding the TTL and data cleanup configuration variable.

For Cassandra what is the default TTL value?
For PostgreSQL what is the default Cleanup time value?

If I put 5 years as TTL, it means that the data it is stored 5 years inside PostgreSQL? 

SQL_TTL_TS_TS_KEY_VALUE_TTL value is 0, what does 0 mean?

SQL_TTL_TS_EXECUTION_INTERVAL: what does this configuration value is about?

**Environment**
 * OS:  Docker + Windows
 * ThingsBoard: 3.6
 * Browser: Mozilla

**Comment by trikimiki** [comment]
Hi!
You can refer to this doc: https://thingsboard.io/docs/user-guide/install/config/

> SQL_TTL_TS_TS_KEY_VALUE_TTL value is 0, what does 0 mean?

This means that records will never expire, basically TTL is switched off.

> For Cassandra what is the default TTL value?

Default is 0 (never expire).

> For PostgreSQL what is the default Cleanup time value?

TTL is 0 (never expire), a procedure to cleanup is set to execute once a day by default (although, as TTL value is 0, it does nothing).

> If I put 5 years as TTL, it means that the data it is stored 5 years inside PostgreSQL?

Yes, if the telemetry timestamp is older than 5 years, it would be removed upon next cleanup procedure "cycle". Note that, for PostgreSQL, this is retroactive (affects all timeseries values, even those that were present before TTL parameter was changed).

This works differently with Cassandra, there records are "assigned" their TTL values once they are written to DB, so changing setting will not affect all records. 

Note that there is other ways to configure TTL, but those only work for Cassandra. Listing them in order of priority:
- message metadata "TTL" field
- "time-to-live" setting in "Save Timeseries" Rule Node
- "Storage TTL days by default" setting in Tenant Profile

For Postgres specifically, there is also an alternative: you can set the attribute "TTL" for the Tenant or Customer entity.

If any of those are not set, a configuration parameter setting is used.

**Comment by Aimen-Hammou** [comment]
Hi @trikimiki 

If I want to set the TTL for PostgreSQL I need to set the field: "SQL_TTL_TS_TS_KEY_VALUE_TTL"? Maximum value of this field is 5 years (in seconds)?

**Comment by trikimiki** [comment]
Yes, correct. `SQL_TTL_TS_TS_KEY_VALUE_TTL` is used for Postgres TTL.

This value has no limit, only the theoretical limitation of Java "long" data type (2^63 - 1).

**Comment by Aimen-Hammou** [comment]
Any value greater than 5 years get ignored? If not, I can't understand where the 5 years limitation is.

**Comment by trikimiki** [comment]
Do you refer to this? 
https://thingsboard.io/docs/user-guide/telemetry/#:~:text=The%20maximum%20allowed%20value%20of%20TTL%20is%205%20years
There is no limit on ThingsBoard side, so I suppose it is about Cassandra application limit. I have no info on this, so I am unsure where this comes from.
In any case, this does not affect Postgres TTL parameters.

**Comment by Aimen-Hammou** [comment]
Wait.

I have a little bit of confusion.

What is the maximum number of years I can put as TTL for PostgreSQL and Cassandra? If it is not 5 years, where does this limit come from?

**Comment by trikimiki** [comment]
According to the documentation, there is only this limit of 5 years for Cassandra. Postgres should not have any limits.

**Comment by Aimen-Hammou** [comment]
Thank you! All clear now.

**Comment by Aimen-Hammou** [comment]
If I use Hybrid Solution: Entities in PostgreSQL and Timeseries in Cassandra. What is the point of having a TTL for Postgres? Entities expire?

**Comment by ViacheslavKlimov** [comment]
Events, alarms, RPCs, audit logs and notifications can expire, if you configured so.

**Comment by ashvayka** [comment]
Hi @Aimen-Hammou, sorry for the confusion. There is no hard limit of five years anywhere in the code. If you are using Cassandra (DATABASE_TS_TYPE = cassandra), then the maximum TTL is configured by 'TS_KV_TTL' parameter. By default no TTL is set ('0').  If you are using PostgreSQL(DATABASE_TS_TYPE = sql) - the value is configured in 'SQL_TTL_TS_TS_KEY_VALUE_TTL' if  'SQL_TTL_TS_ENABLED' = true.

**Comment by Aimen-Hammou** [comment]
@ashvayka 

So Cassandra can store values for more than 5 years?

**Comment by ashvayka** [comment]
yes

**Comment by Aimen-Hammou** [comment]
Ok great.

**Comment by trikimiki** [comment]
Correct. In the case of hybrid installation, Cassandra stores telemetry data, so you need to configure the respective parameter `TS_KV_TTL`.

Note that you can configure Cassandra TTL in other ways, and those overwrite system configuration if set (as per https://github.com/thingsboard/thingsboard/issues/10086#issuecomment-1914716270)

**Comment by Aimen-Hammou** [comment]
Ok, great. Thanks to everybody for helping me.
