### ISSUE TITLE
api/v1/xxxx/rpc post is giving 503 error

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#1008]
```

Curl

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Authorization: Bearer XXX' -d '{ \ 
   "id": "1", \ 
   "method": "setDamperOpening", \ 
   "params": { \ 
     "damperOpening": "23" \ 
   } \ 
 }' 'http://xxxx.amazonaws.com:80/api/v1/xxx/rpc'


Response Body
{
  "timestamp": 1534143458737,
  "status": 503,
  "error": "Service Unavailable",
  "exception": "org.springframework.web.context.request.async.AsyncRequestTimeoutException",
  "message": "No message available",
  "path": "/api/v1/xxxx/rpc"
}
```

**Comment by Saiyidah** [comment]
SuneethaYamani,
May I know what is the solution for 503 error? I just install the TBPE using AWS. Then, after I upgrade the TBPE. The server is problem and got that error. 

Thank you.

**Comment by ban2derlog** [comment]
Hello, is this issue persist on latest ThingsBoard version?

**Comment by IoTThinks** [comment]
> Hello, is this issue persist on latest ThingsBoard version?
I hit 503 error too in HTTP API for RPC.
Any help?

**Comment by ban2derlog** [comment]
@IoTThinks 
Please add command here (without any private data and secret, of course).
But 90% is that you don't have permissions or authorization to GET or POST in 
> /api/v1/xxx/rpc
