### ISSUE TITLE
[Question] Get Correct RuleChain ID - different ID from ruleChain export.

### ISSUE THREAD

**Issue by Aimen-Hammou** [thingsboard/thingsboard#10082]
**Component**
- Rule Chain

**Description**

I have created a rule chain called "creatingDeviceProfile" which basically sends a POST call to a custom server to get a list of device profiles, creates the correct template and sends the information to the /api/deviceProfile API to generate them.
By "correct template" I mean the json schema that is generated when you export a device profile.
Inside the template there is the "defaultRuleChainId" field where I have to pass another rule chain's id, a message parsing rule chain.
How do I retrieve the id of another rule chain? I've tried all the nodes and the "originator" ones give me a different ID than the valid one.

Edit: by "valid one" I mean the one you get when clicking on the button "copy Rule Chain ID"
**Environment**
 * OS:  Docker 
 * ThingsBoard: version 3.6.2

**Comment by devaskim** [comment]
The cheapest way will be to hard code the chain id in a message metadata.

Otherwise, you need either call TB REST API to find chain id by its name, or write custom rule node to do something similar but without REST call.

**Comment by Aimen-Hammou** [comment]
@devaskim 

Hi, thank you for taking time to answer me.

Regarding the TB REST API I don't get the correct rule chain id. 
Found Value: 69e48f36-bea2-11ee-9d45-c76d49e7c212
Expected Value: a9d70cd0-bc2c-11ee-b5c8-538404ffb923 (copy rule chain id button).

Regarding the hard coding could be done but it is way better if automated.

**Comment by devaskim** [comment]
Hm, in my case it is the same (TB 3.6.2 CE) I compare with this id

![Скриншот 29-01-2024 174026](https://github.com/thingsboard/thingsboard/assets/86909129/3f96d12d-a72d-4d31-af0e-852b6a0d70c8)

**Comment by devaskim** [comment]
Hm
Compare chain id in the profile created from UI.

**Comment by Aimen-Hammou** [comment]
@devaskim 

Sorry, I don't understand what you mean.

**Comment by devaskim** [comment]
I meant create a profile via UI, then get its json via REST API

**Comment by Aimen-Hammou** [comment]
This is the exported JSON. 

```
{
  "name": "TestForIssue",
  "description": "",
  "image": null,
  "type": "DEFAULT",
  "transportType": "DEFAULT",
  "provisionType": "DISABLED",
  "defaultRuleChainId": {
    "entityType": "RULE_CHAIN",
    "id": "a9d70cd0-bc2c-11ee-b5c8-538404ffb923"
  },
  "defaultDashboardId": null,
  "defaultQueueName": null,
  "profileData": {
    "configuration": {
      "type": "DEFAULT"
    },
    "transportConfiguration": {
      "type": "DEFAULT"
    },
    "provisionConfiguration": {
      "type": "DISABLED",
      "provisionDeviceSecret": null
    },
    "alarms": null
  },
  "provisionDeviceKey": null,
  "firmwareId": null,
  "softwareId": null,
  "defaultEdgeRuleChainId": null,
  "default": false
}
```

**Comment by devaskim** [comment]
Not sure if it is possible in TB, but maybe you have chains with the same name?

**Comment by Aimen-Hammou** [comment]
No, I don't have similar rule chains ( name ).

I searched for the ID inside the result of the ruleChains/export API endpoint, but can't find it.

**Comment by Aimen-Hammou** [comment]
@devaskim 

One interesting thing is when I access the rule chain via UI, I get the correct ID in the URL.

**Comment by devaskim** [comment]
Are the other chains has the same problem?

**Comment by Aimen-Hammou** [comment]
All of them.

**Comment by devaskim** [comment]
Mystery. What happens when you open in browser `/ruleChains/<non-correct-id>`

**Comment by Aimen-Hammou** [comment]
Infinite loading screen (three blue dots).

**Comment by Aimen-Hammou** [comment]
What is the path to log file?

**Comment by devaskim** [comment]
> What is the path to log file?

The file is in a [docker volume](https://thingsboard.io/docs/user-guide/install/docker-windows/#running). But you can just use `docker container logs -f <tb_container_id>`

======

Another experiment) What id you will get in json while requesting valid id?

![Скриншот 29-01-2024 182510](https://github.com/thingsboard/thingsboard/assets/86909129/188abe53-9098-41c6-8617-b8fcde1d523f)

**Comment by devaskim** [comment]
>  I get from the /api/ruleChains/export API I get result 404 (Rule Chain Not Found)

I have never use this api directly, instead I used this
![Скриншот 29-01-2024 184804](https://github.com/thingsboard/thingsboard/assets/86909129/96ca8e47-e478-4342-82af-16933b14c3f4)

**Comment by Aimen-Hammou** [comment]
Very Interesting.

With that API it works.

```
{
            "id": {
                "entityType": "RULE_CHAIN",
                "id": "a9d70cd0-bc2c-11ee-b5c8-538404ffb923"
            },
            "createdTime": 1706261050909,
            "additionalInfo": {
                "description": ""
            },
            "tenantId": {
                "entityType": "TENANT",
                "id": "e54c8250-b8fc-11ee-8592-ff2af5ad242e"
            },
            "name": "parseMessage",
            "type": "CORE",
            "firstRuleNodeId": {
                "entityType": "RULE_NODE",
                "id": "f17c2e40-bc35-11ee-b5c8-538404ffb923"
            },
            "root": false,
            "debugMode": false,
            "configuration": null,
            "externalId": null
        },
```

What is the difference between the two API endpoints?

**Comment by devaskim** [comment]
I don't know, but you can start from exploring of a [corresponding REST controller](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/controller/RuleChainController.java).

**Comment by Aimen-Hammou** [comment]
It would be good to notify this to the ThingsBoard Team since it leds to confusion, or could possibly be a bug. Is there any way to contact them?

**Comment by Aimen-Hammou** [comment]
Thank you so much!
