### ISSUE TITLE
Is Possible to use Rule Engine to send device latest telemetry to other IoT Platform?

### ISSUE THREAD

**Issue by arimukhlas** [thingsboard/thingsboard#10098]
**Component**

 * Rule Engine

**Description**
Hi, I'm new to thingsboard, i have a device that sends data to thingsboard, my question
Is Possible to use Rule Engine to send device latest telemetry to other IoT Platform?
the flow is like picture below

![Untitled Diagram(9)](https://github.com/thingsboard/thingsboard/assets/95061616/47082786-7a63-4ac1-9f0e-e3aa9dab6330)

**Comment by devaskim** [comment]
In general, yes. But it depends on what protocols that platform supports.
TB provides HTTP REST API node, MQTT node and some others.

**Comment by arimukhlas** [comment]
> In general, yes. But it depends on what protocols that platform supports. TB provides HTTP REST API node, MQTT node and some others.

hi @devaskim thanks for fast reply
I ever try to save telemetry from other platform to thingsboard using rule chain rest api call
in this case, I want the opposite, I want send latest telemetry from thingsboard to other platform

the platform I mean support HTTP REST API, and MQTT
can you give me hint hot to do that?

**Comment by devaskim** [comment]
> can you give me hint hot to do that?

[https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/external-nodes/](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/external-nodes/)

**Comment by arimukhlas** [comment]
> > can you give me hint hot to do that?
> 
> https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/external-nodes/

ok, I have read. I will try using MQTT external rule chain, my question is,
how to prepare data to be sent to the MQTT external is the later telemetry device?

**Comment by devaskim** [comment]
If your external platform supports JSON data through MQTT, no special preparation is needed

**Comment by arimukhlas** [comment]
> If your external platform supports JSON data through MQTT, no special preparation is needed

yes ofcourse, the platform support JSON, can you give me a hint of what combination of rule chain to use?

**Comment by devaskim** [comment]
Here is the simplest ROOT rule chain

![Скриншот 31-01-2024 131903](https://github.com/thingsboard/thingsboard/assets/86909129/1f86656d-397c-4eda-b085-bd358737a91b)

**Comment by arimukhlas** [comment]
> Here is the simplest ROOT rule chain
> 
> ![Скриншот 31-01-2024 131903](https://private-user-images.githubusercontent.com/86909129/301088509-1f86656d-397c-4eda-b085-bd358737a91b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTU0MDIsIm5iZiI6MTcwNjc1NTEwMiwicGF0aCI6Ii84NjkwOTEyOS8zMDEwODg1MDktMWY4NjY1NmQtMzk3Yy00ZWRhLWIwODUtYmQzNTg3MzdhOTFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlM2U1ODQ5NGNjYzk0ZmVhMjg2M2ZhYjYyZGRkNGM2Yzk5ZTk5N2U1NjI4MTkzOTI5MmUxMmYxY2MwOTM1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t9a_rieKSJj_6yX08FVNFcQOPGq1VVRMsacnoUtaidQ)

Thanks for hint, I have tried, but there are some other question
1. If your sample rule chain above succed, then all of device will post telemetry to external IoT Platform, is that true?
how to post latest telemetry to External MQTT broker only from 1 device with certain time period??
2. I have tested rule chain like this bellow using dummy data, 
![11](https://github.com/thingsboard/thingsboard/assets/95061616/c88f6ccf-ea98-45e4-810b-34ab888a425c)

and success posted to external broker, checked from MQTTX Software
![12](https://github.com/thingsboard/thingsboard/assets/95061616/2b6efc24-23eb-4f4f-aec2-ca95a80ac560)

3. The external MQTT Broker only accepts messages with a certain JSON format, for example
```
{
        "Tags":[{
                 "Name":"temperature",
                 "Value":34
        }]
}
```
my question is how to change dummy json value above to latest telemetry from certain device? I'm stuck, need more hints, thanks a lot

**Comment by devaskim** [comment]
> I'm stuck, need more hint

I recommend you following existing guides on how to [get data from a device](https://thingsboard.io/docs/guides/#AnchorIDConnectYourDevice) and [how to pre-process incoming data](https://thingsboard.io/docs/guides/#AnchorIDDataProcessing).

**Comment by arimukhlas** [comment]
> > I'm stuck, need more hint
> 
> I recommend you following existing guides on how to [get data from a device](https://thingsboard.io/docs/guides/#AnchorIDConnectYourDevice) and [how to pre-process incoming data](https://thingsboard.io/docs/guides/#AnchorIDDataProcessing).

I have several devices that successfully send data to Thingsboard CE server
I just want to forward the latest telemetry data from my device to another platform

**Comment by devaskim** [comment]
> If your sample rule chain above succed, then all of device will post telemetry to external IoT Platform, is that true?

yes

> how to post latest telemetry to External MQTT broker only from 1 device with certain time period??

Rule chains provides with various filter rule nodes.
