### ISSUE TITLE
How to Rule Node UI customization

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#10099]
**Component**
 * Rulenode

**Description**
Guidance how to do rule node UI Customization.

**Environment**
 * ThingsBoard: 3.6
 
Hello, 
I was creating custom rule node without edit the UI because it works anyway. But now I wanna create UI Custom for my custom rulenode and stuck when try to follow documentation. 
Here what Im doing, is folowing this to download from the repo 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/1fefdf33-d552-4d4e-8a57-64b53a3dbbc5)

After downloaded, I go to the folder **rule-node-examples-ui-ngx** and then folow instruction to build like this: 
```
yarn install 
yarn run build 
yarn start 
```
then it said listening port 5000 like this 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/3b1a0899-01ca-442e-b208-5304f9e0c19e)
![image](https://github.com/thingsboard/thingsboard/assets/12267053/ae164f80-985f-45d2-9b0f-acaff2c6ee86)
i only can see **Cannot GET /** on browser

what next to do, until I can do UI customization?

**Comment by evanderbird** [comment]
another error i got is after following this step 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/7708e080-5f64-485f-9f6a-f35792075610)


```
Downloading from central: https://repo.maven.apache.org/maven2/org/thingsboard/thingsboard/3.6.0/thingsboard-3.6.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.thingsboard:ui-ngx:3.6.0 (/home/poromon/#myworkspace/rule_nodes_SN/tb-dev-sn-auth-node-code-2/ui-ngx/pom.xml) points at org.custom-nodes.tb:sn-auth-rule-node instead of org.thingsboard:thingsboard, please verify your project structure @ line 21, column 13
[FATAL] Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: Could not find artifact org.thingsboard:thingsboard:pom:3.6.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 21, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.thingsboard:ui-ngx:3.6.0 (/home/poromon/#myworkspace/rule_nodes_SN/tb-dev-sn-auth-node-code-2/ui-ngx/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: Could not find artifact org.thingsboard:thingsboard:pom:3.6.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by devaskim** [comment]
> then I put ui-ngx folder to TB_WORK_DIR, is this correct way?

You need at least one time to build the whole project, so run frot the root project folter 
```
mvn clean install -DskipTests -Ddockerfile.skip=false
```
Then go to `ui-ngx` and run `mvn clean install -P yarn-start`

**Comment by evanderbird** [comment]
thank devaskim for reply. I try what you suggested to run whole project (success) and go to ui-ngx to run `mvn clean install -P yarn-start` 
and still have this eror 
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: org.thingsboard:thingsboard:pom:3.6.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 21, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.thingsboard:ui-ngx:3.6.0 (/home/poromon/#myworkspace/rule_nodes_SN/rule-node-examples-master/ui-ngx/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: org.thingsboard:thingsboard:pom:3.6.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 21, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```
do I need edit some file inside `ui-ngx` to make it works?

**Comment by devaskim** [comment]
Due to `This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced`

Try this for ui-ngx build

![Скриншот 01-02-2024 180134](https://github.com/thingsboard/thingsboard/assets/86909129/0fcef085-5717-4d08-a723-3ec5e0019b50)

**Comment by devaskim** [comment]
By the way, some time ago I gave up implementing custom ui for my rule nodes for the same challenges. Thus I am content with default configuration UI as JSON object
![Скриншот 01-02-2024 182206](https://github.com/thingsboard/thingsboard/assets/86909129/c316a684-b0a8-4819-93d7-a5c1902e86e7)

**Comment by evanderbird** [comment]
> Due to `This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced`
> 
> Try this for ui-ngx build
> 
> ![Скриншот 01-02-2024 180134](https://private-user-images.githubusercontent.com/86909129/301512549-0fcef085-5717-4d08-a723-3ec5e0019b50.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NjYwNjQsIm5iZiI6MTcwNzk2NTc2NCwicGF0aCI6Ii84NjkwOTEyOS8zMDE1MTI1NDktMGZjZWYwODUtNTcxNy00ZDA4LWE3MjMtM2VjNWUwMDE5YjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDAyNTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODgyYzdmZjM0Y2YwNmMxYWFlM2U2MDg4MzBkYjZiZDkzOGFkN2E5NGM3NjgzOTUzNjQwZTYzYjZmMzk4ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79VedG5eklPYZ-A-giHPqNFnNIdKpLHYauAW8qxFRTg)

just try this, and got this eror

```
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/thingsboard/thingsboard/3.6.0/thingsboard-3.6.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.thingsboard:ui-ngx:3.6.0 (/home/poromon/#myworkspace/rule_nodes_SN_2/tb-dev-sn-auth-node-code/ui-ngx/pom.xml) points at org.custom-nodes.tb:sn-auth-rule-node instead of org.thingsboard:thingsboard, please verify your project structure @ line 21, column 13
[FATAL] Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: Could not find artifact org.thingsboard:thingsboard:pom:3.6.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 21, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.thingsboard:ui-ngx:3.6.0 (/home/poromon/#myworkspace/rule_nodes_SN_2/tb-dev-sn-auth-node-code/ui-ngx/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.thingsboard:ui-ngx:3.6.0: Could not find artifact org.thingsboard:thingsboard:pom:3.6.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```
so maybe my pom is not correct?

**Comment by devaskim** [comment]
> Could not find artifact org.thingsboard:thingsboard:pom:3.6.0 in centra

Seems like you need to buld thingsboard project as well
```
mvn clean install -DskipTests
```
