### ISSUE TITLE
Render a thingsboard dashboard in a React app

### ISSUE THREAD

**Issue by elpollo12** [thingsboard/thingsboard#10103]
Hi. I would like to know if it is possible to create dashboards using the thingsboard interface and then view them in a React application?. Is there something that allows me to access the dashboard code or through an iframe? Thanks. @devaskim

**Comment by devaskim** [comment]
If your dashboard is not public, it is accessible only for authorized user, i.e. after a user logged in. So [you need to send](https://stackoverflow.com/a/13432834/17782348) `X-Authorization` http header with access token to load non-public dashboard in `iframe`
![Скриншот 31-01-2024 200952](https://github.com/thingsboard/thingsboard/assets/86909129/a481eb6f-ec24-498e-9306-f4518d846c8e)

**Comment by elpollo12** [comment]
Thanks @devaskim

**Comment by Ultrazombie** [comment]
HI @elpollo12 
Did you manage to test the solution described above?

**Comment by elpollo12** [comment]
Hi @Ultrazombie 
I used the API to log in, I stored the token and then passed it via src to the iframe using the dashboard url and the accessToken parameter.

https://your.thingsboard.host/...?accessToken=token-goes-here

**Comment by JeremiaEnergyLabs** [comment]
Hi elpollo, did you manage to change the ui of thingsboard? by linking it to react?
