### ISSUE TITLE
How to convert time to value in Trendz

### ISSUE THREAD

**Issue by PhilipRai** [thingsboard/thingsboard#10107]
In Thingsboard Trendz:

How can I convert a duration (eg. 2h 35m) to a numeric value so I can use it to calculate CO2 values?

Im currently using to the Duration function to get the value out in days, hours, minutes.

**Component**

 * UI

**Description**
Clear and concise details.

**Comment by vparomskiy** [comment]
For such computations it is better to use batch calculated fields. In this case you have access to to raw telemetry values and can write a function that will calculate CO2 values.
Here is an exampel how to use it - https://thingsboard.io/docs/trendz/batch-calculated-fields/#modify-raw-telemetry

**Comment by Ultrazombie** [comment]
closed due to inactivity
