### ISSUE TITLE
Thingsboard upgrade from 3.6.1 to 3.6.2 (docker thingsboard container)

### ISSUE THREAD

**Issue by fernandobarreto** [thingsboard/thingsboard#10106]
Hi,
I always followed the steps from (https://hub.docker.com/r/thingsboard/tb-cassandra/) in order to upgrade the docker thingsboard container, and it always worked ok until 3.6.1. 

But, does anyone presence the problem below when upgrading docker thingsboard container from 3.6.1 to the latest (3.6.2) ?

docker run -it -v /opt/thingsboard/mytb-data:/data --rm thingsboard/tb-cassandra upgrade-tb.sh

Starting Postgresql...
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....XXXXXXXX UTC [12] FATAL:  database files are incompatible with server
XXXXXXXX UTC [12] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.5 (Debian XXXXXXXX).
 stopped waiting
pg_ctl: could not start server
Examine the log output.
Connecting to Postgres, 300 attempts left...
Connecting to Postgres, 299 attempts left...
Connecting to Postgres, 298 attempts left...
Connecting to Postgres, 297 attempts left...
.............

Thanks,

**Comment by trikimiki** [comment]
Hi!

v3.6.2 uses Postgres 15, but older versions use Postgres 12. They are incompatible, thus requires DB data upgrade.

The easiest way to do that is to make a backup, delete ThingsBoard DB, and restore backup to Postgres. The following worked for me:

1. Restore to v3.6.1. Start your ThingsBoard container.
2. Backup v3.6.1 ThingsBoard data. Afterwards, please ensure that your backup is valid.
```
docker exec -i $(docker ps | grep "mytb" | awk '{print $1}') pg_dump -d thingsboard > thingsboard_upgrade.sql
```
3. Stop ThingsBoard, remove Postgres data. Delete the flag to ensure ThingsBoard v3.6.2 would start successfully in the next step.
```
docker compose stop
sudo rm -rf ~/.mytb-data/db
sudo rm -rf ~/.mytb-data/.firstlaunch
```
4. Change ThingsBoard image version in `docker-compose.yml` file to `3.6.2`. Start it; as there is no Postgres data, that would trigger installation script, please wait 2-3 mins for it would finish.
```
nano docker-compose.yml 
docker compose up -d
```
5. The following commands will disconnect ThingsBoard container from the DB and remove default ThingsBoard database. Run those while container is running:
```
docker exec -i $(docker ps | grep "mytb" | awk '{print $1}') psql -c "SELECT *, pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='thingsboard';"
docker exec -i $(docker ps | grep "mytb" | awk '{print $1}') psql -d postgres -c "DROP DATABASE thingsboard;"
docker exec -i $(docker ps | grep "mytb" | awk '{print $1}') psql -d postgres -c "CREATE DATABASE thingsboard;"
```
6. Restore your backup. Then, stop the ThingsBoard container.
```
docker exec -i $(docker ps | grep "mytb" | awk '{print $1}') psql -d thingsboard -t < thingsboard_upgrade.sql
docker compose stop
```
7. Perform the usual v3.6.1 -> v3.6.2 upgrade procedure.

Note that you need to change `mytb` to specified ThingsBoard service name in your `docker-compose.yml`:
```
version: '3.0'
services:
  mytb:
<...>
```
If `$(docker ps | grep "mytb" | awk '{print $1}')` does not work for you - you can execute `docker ps` and copy container ID from output instead, e.g.:
```
docker ps
CONTAINER ID   IMAGE                                   <...>                                                                                                                                                                                          NAMES
7205746e1a9b   thingsboard/tb-cassandra:3.6.2          <...>

docker exec -i 7205746e1a9b pg_dump -d thingsboard > thingsboard_upgrade.sql
```

**Comment by maghibus** [comment]
So they do not adhere to semantic versioning

**Comment by inakigoicoleaOCB** [comment]
would it be possible and/or advisable to use liquidbase to avoid all future problems with db schemes and new tb versions?
