### ISSUE TITLE
Display a client attribute in the Devices view

### ISSUE THREAD

**Issue by owen63** [thingsboard/thingsboard#10113]
**Is your feature request related to a problem? Please describe.**
I am using device provisioning via X.509 certificates and can successfully create new devices. However the device name comes from the device certificate and this is a unique opaque value. This is done when the iot device is initialised in the factory. Later, when the device is assigned to a customer it will have a friendly name assigned. I want to assign this friendly name to the TB device as a server attribute so that the client can read it. And I want it to be visible in the TB Devices view as a sortable column, similar to the Label column.

**Describe the solution you'd like**
A configurable Devices view that can display a device attribute, or allow the device Label to be overwritten by an attribute..

**Comment by devaskim** [comment]
Why you cannot just set this friendly name to a device label?

**Comment by owen63** [comment]
Yes, the device label would work for display purposes but I want the client
device to also access it. Is that possible?

**Comment by devaskim** [comment]
If you that label should be sent to a connected device, you need to copy it to a shared attribute of a device. It could be simple done with rule chain by filtering ENTITY_CREATED and ENTITY_UPDATED events by a device type and then copy its label to an attribute.

**Comment by owen63** [comment]
Thanks, I will try that. I have another issue - my devices have several firmware components. I can use the Thingsboard firmware API to do OTA updates of the main controller but I also want to download firmware upgrades (a few MB) for other parts - the main controller will orchestrate the subsidiary updates. I need facility in the Device profile to store other binary images and an API to download these in chunks, similar to the firmare API. Is that possible?

**Comment by devaskim** [comment]
Dont know. Create new Github issue for this question, maybe someone will anwer
