### ISSUE TITLE
On the Getaway API, after connecting a device, how long will it be active?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#10116]
This is to send an RPC request to devices. I usually send data once every 30 minutes via the Gateway API. And at this time I send a connection request.

**Component**

 * Generic
 
**Environment**

 * ThingsBoard: 3.6.1

**Comment by epalchenko** [comment]
Hello @psxbox,
Two parameters are responsible for the activity sesion of the device.
DEFAULT_INACTIVITY_TIMEOUT
Default Value(in seconds): 600
Device inactivity timeout is a global configuration parameter that defines when the device will be marked as "inactive" by the server. A user can overwrite this parameter for an individual device by setting the “inactivityTimeout” server-side attribute (NOTE: expects value in milliseconds).
https://thingsboard.io/docs/user-guide/install/pe/config/#device-state-parameters
TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT
Default Value(in milliseconds): 600000
Session inactivity timeout is a global configuration parameter that defines how long the device transport session will be opened after the last message arrives from the device.
https://thingsboard.io/docs/user-guide/install/pe/config/#transport-configuration-parameters

**Comment by psxbox** [comment]
OK, thanks
