### ISSUE TITLE
[Question]: Using TBEL how to identify if a msg.key is json object or json array

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#10127]
**Component**
TBEL

**Description**
We are using TBEL for rule node script. One of the keys of the input message may be a json object or json array (of json objects). I want to know how to handle the ambiguity in TBEL. Is there a way to detect if value of certain key is array and handle accordingly.  

**Environment**
NA

** Work around **
The current workaround is to use toString on the value and identify if first char is "[" but there needs to be a better way to handle this.

**Comment by devaskim** [comment]
`msg.object.length == null`
