### ISSUE TITLE
How to make messages processed sequentially?

### ISSUE THREAD

**Issue by cogic** [thingsboard/thingsboard#10125]
**Component**

 * Rule Engine

**Description**
![image](https://github.com/thingsboard/thingsboard/assets/72649343/446bc084-a698-4aed-861c-b5fe6e95bc63)
I have a rule chain like the one above. Suppose some messages arrive at a device now, I want a message to enter **step 1** only after the previous message leaves **step2**.
 I'm trying to do this using the **SequentialByOriginator** queue, but it doesn't seem to meet my expectations.
Can anyone help me? Thanks in advance.

**Environment**
 * ThingsBoard: 3.4.0

**Comment by ashaforost** [comment]
This type of message synchronization is not available in the thingsboard. Consider changing your rule chain logic to accommodate for the asynchronous message processing.
