### ISSUE TITLE
Cleaning and emptying the Postgres database

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#10126]
**Component**

 * Generic

**Description**
I have a Thingsboard instance with an external database. This database is beginning to have an excessively large size due to the auditing and telemetry part. I can delete records from the database, but until I do a Vacumm full I do not recover the disk size of the deleted data. When doing a full vacuum of the deleted tables, they are blocked by the operation itself and that gives me problems with the system in production.

How do you perform database dumps and disk size recovery in a production environment, where it is essential for the system to continue working?

Thank you very much for the help.

**Environment**

 * OS:  Debian 12
 * ThingsBoard: 3.6.1 CE

**Comment by ashvayka** [comment]
Hi @Borch97 , ThingsBoard uses partitioned tables to store audit logs, events, alarms and telemetry. The cleanup is done by dropping the oldest partition. This is the most efficient approach. And it does not require `vacuum full` to cleanup the space. To find the corresponding parameters, use [configuration](https://thingsboard.io/docs/user-guide/install/config/) page. Look for `sql.ttl.*` params and `sql.*.partition_size` and `sql.postgres.ts_key_value_partitioning`.

For example, to cleanup audit logs, just set the `SQL_TTL_AUDIT_LOGS_SECS` to desired TTL in seconds (1 month = 60×60×24×30=2592000). Note, that the cleanup will not happen immediately after you restart the service. The period of running the cleanup procedure for audit log is configured via SQL_TTL_AUDIT_LOGS_CHECKING_INTERVAL_MS and is 1 day by default. So the cleanup will happen within 1 day after you restart the server. Initial cleanup happens in a random period from 0 to the value of SQL_TTL_AUDIT_LOGS_CHECKING_INTERVAL_MS parameter. Similar for other params.

**Comment by trikimiki** [comment]
Hello @Borch97
Please let us know if the answer above clarifies your question, or if you need any additional pointers.
