### ISSUE TITLE
Key filter of alarm rule condition exception: 'Operation not supported: IN'

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#10120]
**Component**

 * Generic

**Description**
Got exception after applied 'IN' operation in key filter of alarm rule condition, why?
![image](https://github.com/thingsboard/thingsboard/assets/7221781/97706c76-dd29-4d4a-a192-9b1a3bf15ec6)
![image](https://github.com/thingsboard/thingsboard/assets/7221781/a3eebc0a-77f0-497f-a61a-c6884e5a9faa)

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.2 CE

**Comment by devaskim** [comment]
>  why?

because still not [implemented ](https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java#L457)

**Comment by maksonlee** [comment]
> > why?
> 
> because still not [implemented ](https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java#L457) @ashvayka

then why show user the uniplemented options?

**Comment by AndriichnekoDm** [comment]
@maksonlee We create the PR https://github.com/thingsboard/thingsboard/pull/10175.

**Comment by maksonlee** [comment]
thanks for quick fix.
