### ISSUE TITLE
[Question] I gained access after removing the thingsboard tenant administrator group. Does anyone know how to resolve this?

### ISSUE THREAD

**Issue by YS-HARM** [thingsboard/thingsboard#10136]
When you log in, the main screen displays 'There was a problem loading the widget configuration. The associated widget type has been deleted.' It appears like this, and the only categories on the left are home, resources, and norification center. Other items such as dashboards and devices are gone.
When I log in after deactivating the tenant administrator group to a user in the tenant administrator group, it appears as mentioned above.
Please tell me how to go back to the previous time.
please.
![thingsboard오류](https://github.com/thingsboard/thingsboard/assets/83411987/ae7980ab-9f95-43f3-8df6-aae823bebf6e)

**Comment by ashvayka** [comment]
Hi @YS-HARM , This item is related to ThingsBoard Cloud support. To help you we require sharing some sensitive information. Please send an email to support@thingsboard.io with the link to this ticket and your user email address. We will continue communication over email. 

As far as I understand, you have removed your user from the administrator's group and that is why you can't see almost anything accept the image gallery and notification center.
