### ISSUE TITLE
Upgrade Leshan LwM2M components to latest version

### ISSUE THREAD

**Issue by Rhyaldir** [thingsboard/thingsboard#10135]
Thingsboard currently uses version 2.0.0-M5 of the different leshan server and client components (leshan-server-cf, leshan-client-cf, leshan-server-redis, leshan-core) and for monitoring even version 2.0.0-M4. Leshan [2.0.0-M5 was released more than two years ago](https://github.com/eclipse-leshan/leshan/releases/tag/leshan-2.0.0-M5) and has since evolved; adding features and fixing bugs and security issues.
I would recommend upgrading to the latest version (currently 2.0.0-M14) to allow thingsboard to better support LwM2M devices. It is just quite disappointing that clients which work perfectly using the Leshan Demo server, to not work with Thingsboard.

One of the changes desperately needed is Timestamped node support to Send Operations on the client side. Which has been completed in 2.0.0-M9. Also bugs related to properly handling DTLS CID  (see #10061) have been properly addressed in the newer version.

I am fully aware upgrading to a newer lehan version is not straight forward, as these are still milestone versions and quite a few apis have been broken since M5. However, it will do great service to the support of LwM2M devices in thingsboard.

**Comment by AndriichnekoDm** [comment]
Thank you! 
We will discuss this feature request internally. I will get back to you with the additional questions and/or release version soon.

**Comment by mhuybrechts** [comment]
Any update on this?

In a project we are working on we use the LwM2M send with timestamps, but these timestamps are ignored. With the newer Leshan (since March 2022) this is fixed. If this will be disregarded we should find a workaround by implementing something else, probably non-standard which would be a shame.

**Comment by AndriichnekoDm** [comment]
Hi @mhuybrechts !
Currently, we are planning to update to version 2.0.0-M14 in our major release 3.7

**Comment by mhuybrechts** [comment]
@AndriichnekoDm Wow, that is great news! Any idea about the (rough) timeline for the release?

**Comment by AndriichnekoDm** [comment]
We don't have an exact date yet, but we want to do it in the middle to late spring

**Comment by Ultrazombie** [comment]
Hello @Rhyaldir,
We will update these components in the 3.7 version. Please wait for the release.
https://github.com/thingsboard/thingsboard/pull/10095
