### ISSUE TITLE
Custom action in entities hierarchy widget for different nodes

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10140]
**Component**
* UI

**Description**
I need to add an action to an **entities hierarchy** widget so it will **Navigate to new Dashboard state** but the **Target dashboard state** is different for different Asset type. For example, I have asset type building, freezer and refrigerator. I have 3 different dashboard states, one for each type.  Is this possible?

**Environment**
 * OS:  Ubuntu server
 * ThingsBoard: PE 3.6.2
 * Browser: Chrome

**Comment by devaskim** [comment]
Use custom action
```
widgetContext.stateController.openState('your_state_id')
// or 
widgetContext.stateController.openState('your_state_id', stateParamsObj)
```

**Comment by psxbox** [comment]
> Use custom action
> 
> ```
> widgetContext.stateController.openState('your_state_id')
> // or 
> widgetContext.stateController.openState('your_state_id', stateParamsObj)
> ```

This is the change state in the current DASHBOARD, right? How can I change DASHBOARD too?

**Comment by devaskim** [comment]
Right. 
Here is how navigation to another dashboard is implemented inside TB UI 
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1070

**Comment by psxbox** [comment]
> Right. Here is how navigation to another dashboard is implemented inside TB UI https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1070

Fine. Thank you. I'll try this.

**Comment by Ultrazombie** [comment]
closed due to inactivity
