### ISSUE TITLE
Azure AD OAuth

### ISSUE THREAD

**Issue by mohanadsarhan** [thingsboard/thingsboard#10143]
**Component**
 * Installation

**Description**
Has anyone managed to connect Thingsboard to AzureAD? Can you please send me a guide to configure OAuth with Azure AD, as the URL link on the docs guide page is broken? 

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: Professional Edition

**Comment by Mike2912** [comment]
Hi,
here you can find the AzureAD doc:
https://thingsboard.io/docs/user-guide/oauth/azure/
But do not enter the Token and URLs in the thingsboard.yml. Use the Custom Provider via OAuth2 Web-GUI described here:
https://thingsboard.io/docs/pe/user-guide/oauth-2-support/

**Comment by mohanadsarhan** [comment]
Thanks Mike,
I have followed the instructions but ended up with the below error.
Is there a log file where I can get more information on the error to troubleshoot further?

![image](https://github.com/thingsboard/thingsboard/assets/157341584/9f6974a8-3752-4d06-a40e-eec02a5f8697)

**Comment by mykhailokornieiev** [comment]
Hi
Try to use the next steps:

image-20240215-142503.png
image-20240215-145610.png

You need to paste your Redirect URI here:
image-20240215-143303.png

Don’t forget to select “Access tokens (used for implicit flows)“, “ID Tokens (used for implicit and hybrid flows)“ and “Accounts in this organizational directory only“:
image-20240215-143619.png

Client ID:
image-20240215-143117.png

Client secret: 
image-20240215-144224.png

URIs must be v2
image-20240215-142721.png

Also, there is the possibility to get these URIs using .well-known/openid-configuration
image-20240215-142909.png


https://login.microsoftonline.com/411c0f3a-d374-43e2-addd-81aac49bc61a/v2.0/.well-known/openid-configuration

Grant email, openid and profile permissions:
image-20240215-144332.png

Mappers must have “preferred_username” value in both user name attribute key and email attribute key
image-20240215-144705.png
image-20240215-145019.png

 

See list of attributes from Azure here:

they can be used for mapping
image-20240215-145716.png

**Comment by mykhailokornieiev** [comment]
Hi
Try to use the next steps:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/945e586c-39b0-4ad9-844e-7a2dca6e42ed)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/dfdbb99c-c72c-4c20-b0f1-1037f120ee3d)
You need to paste your Redirect URI here:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/3bbc7937-6e55-46fc-ae43-045c3c21222b)
Don’t forget to select “Access tokens (used for implicit flows)“, “ID Tokens (used for implicit and hybrid flows)“ and “Accounts in this organizational directory only“:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/0ef55719-a8bd-4b19-844c-725b9beb7374)
Client ID:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/a9c44858-2881-4eba-9b83-226184db1ccf)
Client secret: 
![image](https://github.com/thingsboard/thingsboard/assets/115699895/96bfe1ad-8ae7-4f8b-b9e5-93cd48c2b0c1)
URIs must be v2
![image](https://github.com/thingsboard/thingsboard/assets/115699895/f1c0613d-61f6-4459-8f18-e88d5f22d32a)
Also, there is the possibility to get these URIs using .well-known/openid-configuration
![image](https://github.com/thingsboard/thingsboard/assets/115699895/c2c31813-c1e8-4895-9a00-7cb45c411a7c)
https://login.microsoftonline.com/411c0f3a-d374-43e2-addd-81aac49bc61a/v2.0/.well-known/openid-configuration

Grant email, openid and profile permissions:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/93897744-13ec-4015-b0ff-56b68ea77f72)
Mappers must have “preferred_username” value in both user name attribute key and email attribute key
![image](https://github.com/thingsboard/thingsboard/assets/115699895/92e0cc19-3361-4f25-9820-7e41d2c2d904)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/89845953-3ee8-4e58-a5f6-a2f2c704fcbc)

See list of attributes from Azure here:

they can be used for mapping
![image](https://github.com/thingsboard/thingsboard/assets/115699895/2ca5d51d-7195-467d-b08f-f6bc8c28ea5b)

**Comment by mohanadsarhan** [comment]
Thanks @mykhailokornieiev this worked for me.
