### ISSUE TITLE
Home dashboard modification

### ISSUE THREAD

**Issue by mohanadsarhan** [thingsboard/thingsboard#10142]
**Component**
 * UI

**Description**
How can the home dashboard (the one that opens in the Home tab) be edited for all users as it contains references to Thingsboard in the Solution Template section? It needs to be edited globally (not as per a user setting) so no tenant admins can change it back.

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: Professional Edition

**Comment by ssakharova** [comment]
Hello @mohanadsarhan,

You can customize the content displayed on the home page by specifying the desired dashboard as your Home dashboard in the Settings > Home settings tab.

By selecting and setting a specific dashboard in this field, that particular dashboard will be presented on the home page upon login.
