### ISSUE TITLE
Propagating back-pressure from server under stress to the clients.

### ISSUE THREAD

**Issue by everslick** [thingsboard/thingsboard#10148]
Is there a standard (or custom for that matter) way to inform the clients, that the server is under high load?

Our clients are connected via MQTT and have the ability to queue messages in case of network failure. If they happen to go online again simultaneously they easily kill the server when sending up to 50 messages per second each. I would like to send a **back-off** or better a **max-send-rate=12** MQTT message from the server to the clients, if it gets under pressure.

Any ideas are appreciated.

**Comment by trikimiki** [comment]
Hi!
Tenant Profile has a feature to enable API Limits: https://thingsboard.io/docs/user-guide/tenant-profiles
