### ISSUE TITLE
Order of tabs name in TimeSeries Table

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#10144]
Hello.
Device names are displayed in the TimeSeries Table tab. 
The order of display is in the order of device registration.

How can I have the tabs sorted and displayed by device name?

![タイムシリーズテーブル](https://github.com/thingsboard/thingsboard/assets/111136063/73111991-a824-466f-8602-2f563fcea707)

**Comment by mykhailokornieiev** [comment]
Hi
Currently there is no such possibility to change tab order in Timeseries Table widget. 
We will discuss this feature request internally. I will get back to you with the additional questions and/or release version soon.

**Comment by h-takado** [comment]
Thank you!

**Comment by AndriichnekoDm** [comment]
Hi @h-takado!
Create another ticket with your description, please.

**Comment by omahurin** [comment]
Hello,

The sort tab entities in alphabetical order functionality is implemented in 4.3. https://github.com/thingsboard/thingsboard/pull/14159
