### ISSUE TITLE
NotificationsCleanUpService does not scale with high notification volume

### ISSUE THREAD

**Issue by timo** [thingsboard/thingsboard#10165]
**Describe the bug**
When there is a lot of notifications, running the cleanup for notifications and notification requests can take a very long time.

**Your Server Environment**

* own setup
  * Deployment: microservices
  * Deployment type: deb
  * ThingsBoard Version 3.5.0PE-1
  * Professional Edition 
  * OS Name and Version Debian 11 (bullseye)

**Expected behavior**
Cleanup of notifications should be handled in the background without me noticing it.

**Observed behavior**
The postgresql server (not used for timeseries data) spent over a day at 100% cpu utilisation until I cancelled the transaction with pg_cancel_backend. All of this work was in a single transaction, too.

**Additional context**
We have a large amount of notifications for some reason™; 5_117_803 rows in the notification table corresponding to 506_439 notification_request rows.

Dropping the partition of the notification table is very fast, of course. However, deleting notification_requests that are older than a given timestamp is much slower. The reason for this is the foreign key from notification to notification_request via the request_id column. It is set to cascade on delete, so any delete on notification_request causes a delete on notification matching the deleted ID.

Here's an `explain analyze` of `delete from notification_request where created_time < 1703721708070` which at the time of running it hit 63 rows in notification_request, it took two minutes to run:

```
 Delete on notification_request  (cost=0.00..52909.11 rows=66 width=6) (actual time=315.421..315.422 rows=0 loops=1)
   ->  Seq Scan on notification_request  (cost=0.00..52909.11 rows=66 width=6) (actual time=178.880..315.383 rows=63 loops=1)
         Filter: (created_time < '1703721708070'::bigint)
         Rows Removed by Filter: 506368
 Planning Time: 0.042 ms
 Trigger for constraint fk_notification_request_id: time=113472.515 calls=63
 Execution Time: 113787.980 ms
(7 rows)
```

As you can see the majority of time is spent in the constraint fk_notification_request_id being triggered once for each of the rows.

An `explain analyze` on a `delete from notification where request_id = 'some-random-uuid'` shows that it's doing a full seq scan on each of the partitions of notification, for a total 1824ms.

Creating a btree index on the request_id column of the notification table allows the deletion of 1097 rows in just 714ms. That's 0.65ms per row compared to 1806ms per row, roughly 2750x faster.

While we will probably change why there are so many notifications in the first place, it would be good for thingsboard to keep its performance high when such an extreme situation occurs.

The size of the request_id index is 1/5th of the size of the id index that already exists on the same table as its primary key.

I tried using a brin index instead, which would be a lot smaller, however it did not improve performance nearly enough to help.

That's why I would suggest adding the index by default in thingsboard.

**Comment by timo** [comment]
The BRIN index actually didn't improve performance at all, it marked every block as needing a re-check, so it was equivalent to a full sequential scan without an index.

It occurs to me that thingsboard could also conditionally create the index as part of the cleanup transaction and drop it again at the end, and only do it if there's more than 100_000 notifications for example.

**Comment by AlexDoanTB** [comment]
@timo starting v3.6.1, the platform opted out from **foreign key** for notifications table (see [this ](https://github.com/thingsboard/thingsboard/pull/9353) ).
There were other fixes as well (like [the OOM issue](https://github.com/thingsboard/thingsboard/pull/9443)).
I'd suggest upgrading to the latest version of the platform. 
The upcoming release (v.3.6.3) will bring more performance improvements.

**Comment by timo** [comment]
Wonderful, thank you!
