### ISSUE TITLE
Bug Rule Node Missing Entity Id 

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#10166]
**Describe the bug**
Originator Id is missing. Can't get entity id.

Happen after upgrade TB 3.6.x

![image](https://github.com/thingsboard/thingsboard/assets/12267053/44cccb2c-f46f-4ed3-96c3-17bc0c42eaa7)
only can see type, can't see id
![image](https://github.com/thingsboard/thingsboard/assets/12267053/00f8ea5e-7beb-40c9-bd58-4576e9eeb520)

**Comment by Backdraft007** [comment]
I think this is the same #10114
