### ISSUE TITLE
[Question] How can I get the last telemetry value before the time window?

### ISSUE THREAD

**Issue by DavidRuizServinet** [thingsboard/thingsboard#10179]
**Component**
 * UI

**Description**
I am developing a widget to show the time in which an attribute has been in a state, the problem I have is that I need the previous state before the time window to know if there has been any change, how could I get this value?

**Environment**
OS: Windows 11 Pro 23H2
ThingsBoard: 3.6
Browser: Microsoft Edge 120.0.2210.133

**Comment by devaskim** [comment]
```
self.ctx.attributeService.getEntityTimeseries(entityId, ['YOUR_ATTRIBUTE_NAME'], startPeriodMs, endPeriodMs).subscribe(
    telemetry => console.log('Telemetry', telemetry),
    error=> console.log('Error', error)
);
```

**Comment by DavidRuizServinet** [comment]
Hello @devaskim I made a mistake indicating that it was an attribute, actually I am the value that I need to obtain comes in a telemetry, how would it be done for that case?

**Comment by devaskim** [comment]
I gave your proper code

**Comment by DavidRuizServinet** [comment]
It finally worked thanks!
