### ISSUE TITLE
Querying devices via /api/devices returns empty array

### ISSUE THREAD

**Issue by regressionsanalyse** [thingsboard/thingsboard#10178]
**Component**
 * Generic

**Description**
Hey there!

I am currently trying to query devices of a certain device type from a single tenant via Thingsboard's HTTP API (`/api/devices`, see [Thingsboard API Documentation](https://thingsboard.cloud/swagger-ui/#/device-controller/findByQueryUsingPOST_1)) .

Unfortunately, I seem to be misinterpreting the documentation, giving me unexpected results.

Consider the following request body to `/api/devices`:

```
{
  "relationType": "Contains",
  "deviceTypes": [
    "myDeviceType"
  ],
  "parameters": {
    "rootId": "id_of_the_tenant_goes_here",
    "rootType": "TENANT"
  }
}
```

I then get an empty list as the result:
`[]`

There is, however, at least one device of type `myDeviceType` present in my tenant. Thus, I would have expected that one to appear in the resulting list.

Can anyone give me a little hint on what I'm doing wrong here? Any pointer would be much appreciated.

Thanks! :)

**Environment**
 * ThingsBoard: 3.6.2

**Comment by devaskim** [comment]
[In TB terms](https://thingsboard.io/docs/user-guide/entities-and-relations/), there is no relations (Contains, Manages or some other) between tenant and devices. To resolve ownership of a device TB uses tenantId, ownerId and/or customerId.

Of course, you can explicitly create relation between tenant and each device, then the result of your query will not be empty.

**Comment by Ultrazombie** [comment]
closed due to inactivity
