### ISSUE TITLE
Widget development time series

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#1017]
Hello there,

I am trying to develop a heatmap widget using OpenLayers. 

I start with the time series widget and get the start up screen where there is the Chart. After clearing everything I still cannot get rid of the display of the legend. Can you guys help me out  ? See picture below.

Any hint is much appreciated! Thanks a lot!

![widget-dev](https://user-images.githubusercontent.com/37292275/44258312-d6b18480-a20e-11e8-97a7-febc7dfc7751.png)

**Comment by sieversb** [comment]
I know, this is an old thread but I though I still give it a shot. Did you solve the problem and if so. Would you share the source code with us? I am currently looking for the exact same solution.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
