### ISSUE TITLE
websocket error event

### ISSUE THREAD

**Issue by vastechpro** [thingsboard/thingsboard#10171]
**Component**

 * UI

**Description**
I am trying to build a widget and I see WebSocket error event -> CloseEvent() in the browser console logs (see screen below).

<img width="795" alt="Screenshot 2024-02-12 at 10 43 50 AM" src="https://github.com/thingsboard/thingsboard/assets/6180900/8f39d601-e7fc-4a37-a080-1cdc18698537">

In the onInit() function of the widget javascript, I am calling service APIs asynchronously using subscription. I suspect this error may have something to do with that, but I am not sure. Any idea how to prevent this error?

**Environment**

 * ThingsBoard: Cloud
 * Browser: Chrome

**Comment by sumin-denys** [comment]
Hi @vastechpro,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.
