### ISSUE TITLE
Battery level enhance status

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#10182]
One of the new widgets is battery level. Very nice widget. We use it to show the capacity of a battery pack.
It would be nice to enhance the widget of status, e.g. charging. Maybe with a seperate attribute of the client and showing a marquee inside the battery or a blinking flash.
Thanks.

**Comment by ssakharova** [comment]
Hello @Backdraft007,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) for updates on new additions to the platform in future releases.
