### ISSUE TITLE
"Action cell button"  icon should be disabled and enabled depending on the attributes of the current user

### ISSUE THREAD

**Issue by gravasz** [thingsboard/thingsboard#10188]
**Component**

 * UI

**Description**
I would like to implement that in a widget the "Action cell button"
 icon should be disabled and enabled depending on the attributes of the current user. So e.g. if the user's isEditor attribute is equal to true, the button should be displayed, otherwise not.
I used the attributeService in "Show/hide action using function", but the function returns before the attribute value is realized.
Is there a solution for this?
My code:

_let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
let newEntityId = {"entityType": "USER", "id": widgetContext.currentUser.userId};
let isEditor;
let isTenant = widgetContext.currentUser.authority =='TENANT_ADMIN';
function getAtt(scope, attrib, callback) {
    attributeService.getEntityAttributes(newEntityId, scope,
        attrib).
    subscribe(
        data => {
            if (data.length > 0) {
                callback(data[0].key === 'editor' && data[0].value === true);
            } else {
                callback(false);
            }
        },
        error => {
            console.log('Error');
            callback(false);
        }
    );
}

function getAttCallback(value) {
    isEditor = value;
}

getAtt('SERVER_SCOPE', ['editor'], function(value) {getAttCallback(value);});
console.log(isEditor);
return (isEditor || isTenant);_

**Environment**

 * OS:  Linux
 * ThingsBoard: 3.6.0
 * Browser: Chrome 121.0.6167.161

**Comment by devaskim** [comment]
It is because each API call (attribute request) is asynchronous, so it will end up independently of Show/Hide function.

**Comment by gravasz** [comment]
Thank you very much
