### ISSUE TITLE
TB 3.6.2 - How do change color of action buttons (entity table widget)?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#10180]
**Component**

 * UI

**Description**
One of our customers recently updated Thingsboard from 3.6.1 to 3.6.2. They noticed that the colors of the action buttons in several table widgets are different than before.

In particular, the customer uses dark backgrounds for the widgets. As the buttons now appear to be grey/black by default, they are no longer recognizable.

In the previous version, the colors were changed to white via custom CSS. Unfortunately, this no longer works and we do not understand why the CSS settings do not work.

Do you have any idea what the error could be? Has the logic been changed with the update and it needs to be configured elsewhere?

**Environment**

 * ThingsBoard: 3.6.2 PE

Screenshots:

Sample Button to change color for:
![image](https://github.com/thingsboard/thingsboard/assets/25298332/51055091-371b-4921-83c5-256f44db1b2b)

CSS Style changes:
![image](https://github.com/thingsboard/thingsboard/assets/25298332/c3ec184a-11fa-47bc-9930-0b3eb14b1a22)

**Comment by devaskim** [comment]
```
.mat-mdc-table .mat-mdc-cell button.mat-mdc-icon-button mat-icon {
    color: red !important;
}
```

**Comment by mde2017** [comment]
@devaskim Thank you for your fast response.
Unfortunately, this does not work, when configured via Widget CSS section (color is still unaffected):

![image](https://github.com/thingsboard/thingsboard/assets/25298332/6e2dfd32-bb10-4d86-9608-4ebbaa10362d)

**Comment by devaskim** [comment]
Hm, it works for me.
Try to inspect icon html container through browser DevTools and manually add this CSS property `color: red !important` into one of its children.
![Скриншот 14-02-2024 155737](https://github.com/thingsboard/thingsboard/assets/86909129/e522bb4a-d9f2-4326-a390-e7fe214e8708)
![Скриншот 14-02-2024 155620](https://github.com/thingsboard/thingsboard/assets/86909129/924c5989-4629-410d-a623-1b443c6fbf9f)

**Comment by mde2017** [comment]
Strange that it doesn't work the same way as on your system.
I assume you are using also TB 3.6.2 PE?

I was able to figure it out, thanks to your help. 
If I add `.` before `mat-icon` everything works fine.

![image](https://github.com/thingsboard/thingsboard/assets/25298332/85854846-3de1-48d2-96aa-bf640ee9c787)

Thanks again @devaskim for helping me out

**Comment by devaskim** [comment]
> I assume you are using also TB 3.6.2 PE?

this version too)

**Comment by BigNavid** [comment]
Is it possible to assign a color for each icon?
Something like red for delete and blue for edit?
