### ISSUE TITLE
Bar chart dont show current day

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#10181]
**Describe the bug**
I created a timeseries bar chart and show an aggregated telemetry data.
Timewindow is setup with:
- Realtime, Last 30 days
- Data aggregation function: Sum
- Grouping interval: 1 day

But in the chart the last bar is from yesterday.

**Your Server Environment**
* own setup
  * Deployment type: deb
  * 3.6.2
  * Professional Edition
  * actual Debian 13

**Your Client Environment**
* OS: Win11
* Firefox
* Version 122.0.1

* Connectivity
  * MQTT

**Screenshots**
![Screenshot 2024-02-14 110901](https://github.com/thingsboard/thingsboard/assets/8741669/bd1d4f64-3715-45be-b124-eba4bd420b6f)

![Screenshot 2024-02-14 at 11-11-07 EASY IOT Dashboard](https://github.com/thingsboard/thingsboard/assets/8741669/aa3d522b-77bc-49d9-857b-72183bfdc14b)

**Comment by AndriichnekoDm** [comment]
Hi @Backdraft007!
According to the description, the behavior of the widget is correct, since the data is aggregated for the day, in your case the day has not yet passed
