### ISSUE TITLE
[Question] Entities count widget showing data from all customers

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#10198]
**Component**

 * UI - Dashboard Widget

**Description**

I'm encountering a weird behaviour of the Thingsboard Entities Count Widget, where the Widget counts **all** entities even when I log in as a customer user with access only to a limited set of assets/devices.

<img width="870" alt="image" src="https://github.com/thingsboard/thingsboard/assets/14202480/19d560d5-4f43-4577-afef-1d25f4f844bc">

In the screenshot above, I would expect the Widget to show 3 Projects. Both the Entities Count and the Entities Table Widget use the same Entity alias to filter.

<img width="710" alt="image" src="https://github.com/thingsboard/thingsboard/assets/14202480/4299a45e-5b58-4264-879d-b11bb5465115">

I'm sure this is related to some kind of permission error, but I'm hitting a wall and don't know what else I can check.

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: PE 3.6.1
 * Browser: Chrome Version 121.0.6167.184 (Official Build) (arm64)

**Comment by dmohns** [comment]
After further testing this looks like a bug to me.

**Steps to reproduce:**

In a freshly set up Thingsboard PE:

- Create some dummy devices
- Create a Customer, then create a Customer user, but _do not assign this account any role_
- Create a Dashboard with Entities Count and Entities List Widget, using an entities alias to match all devices.

**Expected Result:**

Both, the count and the List Widget should be empty/0 respectively.

**Actual Result:**

The List Widget is empty, the Count Widget shows the number of devices in the entire installation.


@AndriichnekoDm do you think we should change the type of this issue?

**Comment by ashaforost** [comment]
Hi @dmohns 

We have verified this bug and are preparing a fix to be released in the upcoming v3.7

**Comment by ashaforost** [comment]
Closing post v3.7 release.
