### ISSUE TITLE
Sum/Average aggreagating functions does not work

### ISSUE THREAD

**Issue by anton-pytel** [thingsboard/thingsboard#102]
Having problem with aggregating data in a Timeseries - Flot  
min, max, count works correctly  
sum, average does not return any value.  

Version installed at our server:  
sudo dpkg -i thingsboard-1.2.2.deb at debian  

What details are needed for you to add?  

Thank you for your help.

**Comment by ashvayka** [comment]
This should definitely work. Please add a screen-shoot of your data and a json for dashboard/widget

**Comment by anton-pytel** [comment]
[max.txt](https://github.com/thingsboard/thingsboard/files/922661/max.txt)
[sum.txt](https://github.com/thingsboard/thingsboard/files/922662/sum.txt)

There is something similar, when I wanted to get timeseries data through REST API see max request and correct response, and sum request and emtpy response.

And here are screenshots with widget json.

![max](https://cloud.githubusercontent.com/assets/15068798/25051670/1fbaa302-214e-11e7-833d-9b47e5424e39.jpg)
![average](https://cloud.githubusercontent.com/assets/15068798/25051671/1fc49e8e-214e-11e7-8e6f-024f0ed83cc6.jpg)

Thank you for your help.

**Comment by ashvayka** [comment]
are you posting this values as strings or as doubles/intagers from devices?
for example: {"CurrentTemperature":42} or {"CurrentTemperature": "42"} ?

**Comment by anton-pytel** [comment]
It is a python script, parsing and forwarding data from Vera Lite device and I did not check datatype getting from Vera, when I have added explicit conversion to float it started to work. Thank you for your help.
