### ISSUE TITLE
Synchronization problems Thingsboard Edge <-> Thingsboard Cloud

### ISSUE THREAD

**Issue by ADV-LUT** [thingsboard/thingsboard#10203]
**Description Bug:**
Setup: Thingsboard Edge devices should synchronize to Thingsboard Cloud. The devices (created on the Edge) fail to synchronize their attributes in many cases to the Cloud. While the device itself appears correctly in the Cloud after synchronization, its attributes do not. The Cloud's logs indicate a failure to recognize the device at the time of attempting to attach the attributes, suggesting a potential issue with the order of operations during synchronization.

**Server Environment:**
Deployment: microservices
Deployment type: docker-compose
ThingsBoard Version: 3.5.1 Community Edition
OS Name and Version: Ubuntu Server 22.04.3 LTS

**Thingsboard Edge Environment:**
Deployment type: docker-compose
ThingsBoard Version: 3.5.1 EDGE
OS: Ubuntu 18.04 LTS

**To Reproduce:**
- Ensure the Thingsboard Edge is offline (no internet connection)
- Create multiple devices with attributes on the Edge.
- Bring the Thingsboard Edge online.

**Expected behavior:**
All devices created on the Edge, along with their attributes, should be correctly synchronized and appear in the Thingsboard Cloud.

**Screenshot:**
![Syncerror_Devices](https://github.com/thingsboard/thingsboard/assets/43776990/7f2d33c6-0e9a-4bd4-9897-42fab5a52506)

**Additional context:**
The Cloud's log shows an error indicating that the entity (device) does not exist on the Cloud at the time of attempting to synchronize the attributes, which suggests that the synchronization process might be attempting to attach attributes before ensuring the device has been created in the Cloud.

**Error log snippet:**

> 2024-02-15 11:53:00,244 [grpc-default-executor-625] WARN  o.t.s.s.e.r.p.t.BaseTelemetryProcessor - Skipping telemetry update msg because entity doesn't exists on edge, entityIdMSB: 5544064048183120366
> entityIdLSB: -8447148077548839668
> entityType: "DEVICE"
> postAttributesMsg {
>   kv {
>     key: "Bezeichnung"
>     type: STRING_V
>     string_v: "B37"
>   }
>   kv {
>     key: "i_max_mA [mA]"
>     type: DOUBLE_V
>     double_v: 5.0
>   }
>   kv {
>     key: "Ausgabe_Maximum"
>     type: DOUBLE_V
>     double_v: 100.0
>   }
>   kv {
>     key: "Modus"
>     type: DOUBLE_V
>     double_v: 5.0
>   }
> }
> postAttributeScope: "SERVER_SCOPE"

**Comment by AndriiLandiak** [comment]
Hello, @ADV-LUT. Thanks for bringing this issue to our attention. We are working on addressing it and will include the fix in the upcoming release, scheduled for a few weeks from now.

**Comment by ADV-LUT** [comment]
Hello @AndriiLandiak .

Thanks for the quick answer, where can I see when the next release is planned?

**Comment by AndriiLandiak** [comment]
Currently, the release dates are not publicly disclosed. To ensure you don't miss the release date, please follow our updates on GitHub and LinkedIn. We are planning to deploy the next release within the upcoming one to two weeks.

**Comment by ADV-LUT** [comment]
Hello @AndriiLandiak ,
I wanted to check in regarding the bug reported in post #10264. Was this issue addressed in the latest release from yesterday (March 18, 2024)? I've gone through the release notes but couldn't find any mention of it. Thanks for any updates you can provide!

Best regards

**Comment by AndriiLandiak** [comment]
Hi @ADV-LUT,

Yes, It was included. We missed adding a label in PR for this bugfix, so It wasn't mentioned in the release notes. Now the Synchronization is working properly. Please don't hesitate to contact us if you encounter any problems. 

Have a great day!
