### ISSUE TITLE
Problem creating alarm

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#1020]
I am trying to create an alarm with the new rule engine.

In my application the alarms are created by the device, based on its internal settings and on the values of its sensors. So, the device is supposed to create an RPC request towards the server with all the necessary information, and the server shall create an alarm based on this RPC.

The RPCs have the following format:
```
{
    "method": "event",
    "params": {
        "severity": "info",
        "message": "test event"
    }
}
```
You can see my rule chain here: https://pastebin.com/EJf7dgcE

I have enabled the debug functionality of the create alarm node. As I see the alarm is properly generated, with no errors.

Later I get to the device, and check the alarms tab, but it always says that no alarms are found. The same goes if I create an alarms widget. It always remains empty.

As it seems the alarm is not created properly. What I am doing wrong?

**Comment by fotis400** [comment]
Oh I forgot to mention that no matter what I select in the alarm propagate checkbox, I discovered that the metadata always contain `propagate: true`. 

It seems like a bug to me, the checkbox is not reflected to the actual alarm.

**Comment by fotis400** [comment]
Hi guys,

any idea how to fix this?

**Comment by vparomskiy** [comment]
@fotis400 does this issue still valid for you?

**Comment by fotis400** [comment]
@vparomskiy no, it seems that it is working now.

I just forgot the issue open.
