### ISSUE TITLE
How to use protobuf with CoAP

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#10211]
**Component**

 * Generic

**Description**
I would like to know how to use protobuf with CoAP converter. I indicated a protobuf structure in a device type. How TB will know that the the device specified in a field of the protobuf plan should be used to extract the information according to the protobuf structure. Which instructions should I put in the data converter decoder to retrieve the device and throw the decoding?
Is there a documentation describing the use of protobuf with CoAP?
Thanks for your answers.

**Environment**

 * ThingsBoard: 3.5.1 PE

**Comment by mykhailokornieiev** [comment]
Hi
There is no possibility of using CoAP integration in combination with the Protobuf payload. 
Even more, data is not sent to transport after integration. 
The only solution is to use devices with CoAP + Protobuf directly, without integration.
