### ISSUE TITLE
[Question] Is it possible to invoke the rule chain execution through REST API?

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#10222]
**Component**
Rule Engine

**Description**
My platform is build around Thingboard rule chains. For better re-use I have common functionalities in rule chains that are then embedded in root rule chain as rule chain nodes. For testing and test automation I would like to unit test the functional rule chains e.g. notification rule chain. Is it possible to invoke the rule chain execution through REST API? 

**Environment**
Self hosted Thingboard v3.6.2

**Comment by ashaforost** [comment]
Hi @sudhirbits 

Yes, it's possible! Check out the rule engine controller API definitions: [Swagger](https://thingsboard.cloud/swagger-ui/#/rule-engine-controller)
