### ISSUE TITLE
Selective OTA Updates

### ISSUE THREAD

**Issue by Ashxmas** [thingsboard/thingsboard#10221]
**Component**
 * UI
 * Generic

**Description**
I want to understand if there is an way to implement selective OTA updates within ThingsBoard, allowing for targeted deployments. Key functionalities could include device filtering, controlled rollouts, and user-specific options for update scheduling or disabling. 
The aim is to enhance user experience, optimize resource usage, and address compatibility concerns. 
Looking forward to discussions on feasibility and potential approaches.

**Environment**
 * OS:  Ubuntu Server 22.04 LTS
 * ThingsBoard: 3.6.1

**Comment by mykhailokornieiev** [comment]
Hi. Please describe your request in as much detail as possible with a full explanation of the desired functionality

**Comment by mykhailokornieiev** [comment]
Closed this ticket due to inactivity.
