### ISSUE TITLE
Thingsboard to TBMQ Integration error (Host must be in public)

### ISSUE THREAD

**Issue by Akramkhan-git** [thingsboard/thingsboard#10231]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by dmytro-landiak** [comment]
Hi @Akramkhan-git,

Please provide more details on what you are trying to do.
 
Do you want to connect the Thingsboard MQTT integration or the Thingsboard MQTT rule node to the TBMQ? 
Where the Thingsboard is deployed (self-hosted/cloud)? Or is it Paas ([https://thingsboard.cloud/](https://thingsboard.cloud/))?
Where the TBMQ is deployed (self-hosted/cloud)?

Please add some errors/screenshots if possible.

Could it be that you are referencing the following?
![image](https://github.com/thingsboard/thingsboard/assets/10978307/6a547113-3194-40d5-9b82-638dc78027bb)

**Comment by Akramkhan-git** [comment]
Hi, Dima Landiak
I want to connect my things board with TBMQ with the help of docker.
my thingsboard is on cloud and TBMQ is running on the localhost.
but my problem is when I am trying to connect my Thingsboard with Tbmq I
get an error that the host must be in public, I also attached an image for
your reference.
so please help me to solve this problem.
thanks for your time

**Comment by Akramkhan-git** [comment]
Hi, Dima Landiak
can we connect so that I can explain to you the exact problem that I am
facing?

**Comment by dmytro-landiak** [comment]
@Akramkhan-git, you can contact me via email to discuss this topic in more detail: dlandiak@thingsboard.io
