### ISSUE TITLE
How to change device name or type

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#10238]
hello
i use this script to save telemetry data to new device.
`metadata.deviceName = "Person12"
return {msg: msg, metadata: metadata, msgType: msgType};`

and new data will not save in Person12 device.
i use this rule node.
![Capture](https://github.com/thingsboard/thingsboard/assets/45573721/7852111a-2c83-4166-b1f8-8b32cd79f031)

**Comment by devaskim** [comment]
You need to change originator, see the corresponding rule node

**Comment by m3relec** [comment]
Thanks for the advice
I used change originator but what I came to the conclusion is that I have to leave this for each device.
Is there a way to run it as a pattern and I don't need to put this for each device?
For example, at the end of each device, an _M is added and the new data is stored in it.

**Comment by ashaforost** [comment]
Hi @m3relec 

If these new devices are already in the system, you can use a change originator with the device name pattern. If, however, you want to create a new device and save the telemetry to this new device, a workaround for that is to use the 'create relation' rule node
![image](https://github.com/thingsboard/thingsboard/assets/47900737/4f685699-49c3-419b-b4ec-4012d4338190)
Yes, a relation between old and new devices will be created, but this rule node allows you to create a new device according to the name pattern and change the originator to this device at once. 

Also, if you are stuck on using the change originator rule node and adding an _M to the device name pattern, you can firstly fetch the current device name via 'originator fields' rule node and then use the following setting in the 'change originator' rule node
![image](https://github.com/thingsboard/thingsboard/assets/47900737/91841f6f-7971-4d3f-9607-9e7488337b11)
