### ISSUE TITLE
[Question] ThingsBoard Installation using Docker (monolithic architecture): Is it possible to use an external MQTT broker?

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/thingsboard#10235]
**Component**

 * Installation

**Description**

- Is there any possibility to install Thingsboard (monolithic architecture) using an external MQTT broker instead of the embedded one?
- If so, What changes should be made in the docker-compose.yml file? Any hint?

@smatvienko-tb could you please help?

Many thanks in advance!

**Comment by AlexDoanTB** [comment]
@alexcorvis84, the platform does not act as an MQTT broker. Under the hood, there is "one" that is a code for MQTT transport, but with limited capabilities. You can use whatever broker (including [TBMQ](https://github.com/thingsboard/tbmq)) as a middleware to feed data into ThingsBoard. To send the data further via MQTT — there is a specific rule node.

**Comment by alexcorvis84** [comment]
> @alexcorvis84, the platform does not act as an MQTT broker. Under the hood, there is "one" that is a code for MQTT transport, but with limited capabilities. You can use whatever broker (including [TBMQ](https://github.com/thingsboard/tbmq)) as a middleware to feed data into ThingsBoard. To send the data further via MQTT — there is a specific rule node.

Now I have some questions:

- How is this configuration done? Do you have a guide available for external integration?
- Do you have a list of brokers (apart from TBMQ) that you support?
- How do you manage authentication and users in the external broker?

If you could share more details that could help me to deploy this architecture I would greatly appreciate it.

Many thanks in advance @AlexDoanTB

**Comment by AlexDoanTB** [comment]
@alexcorvis84, there you have it — https://thingsboard.io/docs/user-guide/integrations/mqtt/

**Comment by alexcorvis84** [comment]
> @alexcorvis84, there you have it — https://thingsboard.io/docs/user-guide/integrations/mqtt/

Thanks for the link @AlexDoanTB, but the thing is that I'm using Thingsboard **Community Edition**

As far as I can check, that guide only refers/available for Professional Edition 😟

So I wonder, isn't possible in CE version?? 😕

Thanks in advance.

**Comment by AlexDoanTB** [comment]
> So I wonder, isn't possible in CE version?? 😕
 @alexcorvis84 nope. That is one of the core differences between CE and PE. Integrations, groups, reporting, white labeling, etc are part of the Pro version.

**Comment by smatvienko-tb** [comment]
> > @alexcorvis84, there you have it — https://thingsboard.io/docs/user-guide/integrations/mqtt/
> So I wonder, isn't possible in CE version?? 😕
> 
You need a 3rd party middleware that will sink your MQTT messages from your broker to the MQTT transport.
You can ask AI to make a simple program, like `I would like to sink MQTT messages from one MQTT broker to another MQTT broker`. However, making the middleware reliable and failure-tolerant from scratch might take a lot of effort. Depends on your load. But it may help you somehow.

**Comment by alexcorvis84** [comment]
> > > @alexcorvis84, there you have it — https://thingsboard.io/docs/user-guide/integrations/mqtt/
> > > So I wonder, isn't possible in CE version?? 😕
> 
> You need a 3rd party middleware that will sink your MQTT messages from your broker to the MQTT transport. You can ask AI to make a simple program, like `I would like to sink MQTT messages from one MQTT broker to another MQTT broker`. However, making the middleware reliable and failure-tolerant from scratch might take a lot of effort. Depends on your load. But it may help you somehow.

Thanks for the reply @smatvienko-tb 

I've found this [opensource MQTT broker](https://github.com/bifromqio/bifromq) which seems it may help accomplish what I'm looking for. Are you aware of it? Do you think it may help?

Thanks in advance!

**Comment by smatvienko-tb** [comment]
I'm not aware of that broker at all. My general experience is based mostly on MQTT integrations by Professional Edition that are compatible with any broker you like. It is much easier to distribute the load across a ThingsBoard cluster having multiple integrations enabled as well.
If you find a working solution to feed the data from a broker to the ThingsBoard CE by MQTT, please feel free to share your experience here.

**Comment by AlexDoanTB** [comment]
@alexcorvis84, you may think of looking towards [ThingsBoard IoT Gateway](https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/). It has the ability to transform the payload into consumable JSON and send it to TB CE.

**Comment by alexcorvis84** [comment]
> @alexcorvis84, you may think of looking towards [ThingsBoard IoT Gateway](https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/). It has the ability to transform the payload into consumable JSON and send it to TB CE.

Wow! I didn't realize that option! That's exactly what we're looking for... I think it really helps me.

Our scenario is to be able to use our external MQTT broker that we've already deployed, and somehow be able to connect the devices that feed data to it to finally be received by our deployed TB CE. So that, I think TB IoT Gateway is our key 🔑 🌟 ! 

Thanks a lot for all your support to the whole team. You rock 🤘 guys!!! Much appreciated! 

I'll let you know...let's try it!

**Comment by alexcorvis84** [comment]
Hi @AlexDoanTB,

I tried to follow the [Getting Started guide](https://thingsboard.io/docs/iot-gateway/getting-started/?connectorsCreation=mqtt) of TB IoT Gateway, but I'm having the following error once I toggle the switch to enable MQTT conector. Any clue to fix what's happening? I've followed the steps as detailed in the guide...

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/3c509e50-4635-4bd9-9a5c-43f90b3c237c)

**Comment by AndriichnekoDm** [comment]
Hi @alexcorvis84 !
Try to change your docker-compose.yml file and add extra hosts. 


    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - host= PUT_YOUR_HOSTNAME_HERE
      - port=1883
      - accessToken=PUT_YOUR_ACCESS_TOKEN_HERE

**Comment by alexcorvis84** [comment]
> Hi @alexcorvis84 ! Try to change your docker-compose.yml file and add extra hosts.
> 
> ```
> # Necessary mapping for Linux
> extra_hosts:
>   - "host.docker.internal:host-gateway"
> 
> # Environment variables
> environment:
>   - host= PUT_YOUR_HOSTNAME_HERE
>   - port=1883
>   - accessToken=PUT_YOUR_ACCESS_TOKEN_HERE
> ```

Thanks @AndriichnekoDm 

Now it's working. I can see in the logs the data being received and converted

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/8d24e2ae-d479-45c5-8625-330e50b290e2)

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/f98d9ac3-a726-4ff6-905d-4780b968f5fe)

The issue now is that the new Device that should be listed does not appear...

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/80888fb9-f75b-443e-97c3-f1754b7e8f30)

Any hint what's happening? Thanks!

**Comment by AndriichnekoDm** [comment]
Can you attach a log file created by this command `docker logs tb-gateway > gateway.log name container`? I tried to figure out what it could be, but the best way to see the logs.

**Comment by alexcorvis84** [comment]
> @alexcorvis84 Can you attach a log file created by this command `docker logs tb-gateway > gateway.log name container`? I tried to figure out what it could be, but the best way to see the logs.

Hi @AndriichnekoDm 

FYI: I tried a new fresh install [following the guide](https://thingsboard.io/docs/iot-gateway/getting-started/?connectorsCreation=mqtt) and now it worked like a charm with latest versions published.

I can see the device created and data being received.

Many thanks.

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/d2bfa008-827f-410d-9324-0c42b2ad211d)
![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/dab4f10c-397f-46de-b761-426abfca6d25)
![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/2382cb2b-ad87-4cde-9cc7-258be81a58fe)
