### ISSUE TITLE
how to assign a device to multiple customers in CE

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#10234]
Hello
How can I assign a device to multiple subscribers?
Currently, I can only assign a device to one group of subscribers.

**Comment by ssakharova** [comment]
Hello @m3relec,

In that case, I can recommend the following:

- you need to add the device you want to assign to the separate entity group;

![image](https://github.com/thingsboard/thingsboard/assets/98035385/a552bcb0-640d-4a23-92a7-d76cb298aed3)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/45d4015c-b824-45ea-a8f7-edecd67f4497)

- you need to share the newly created device group with several customers using the 'Share' button. 

When sharing the device group, you can select the customer with whom you want to share the device group, select the users under this customer (it can be All users or users from Customer Administrator or Customer User groups), and specify the appropriate permissions for the users to access this device group.

![image](https://github.com/thingsboard/thingsboard/assets/98035385/a7cf6f18-1dd8-47be-af52-c80e44b0e8ba)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/6b89b6e7-14f3-4dc3-a196-b79df678f688)

Please let me know if you have any further questions regarding the case.

Best regards,
Sofiia Sakharova
