### ISSUE TITLE
read cassandra data from rule

### ISSUE THREAD

**Issue by scadaway** [thingsboard/thingsboard#10249]
There is a rule called "save to custom table" that allows you to add data to a table in Cassandra. 

Is there any way or any rule to read the data in that table?

that allows reading and/or manipulating the query?

**Comment by scadaway** [comment]
@devaskim

**Comment by diazhh** [comment]
thanks a lot!

**Comment by diazhh** [comment]
> No, as I know. If you familiar with Java, you can create [custom rule node](https://thingsboard.io/docs/user-guide/contribution/rule-node-development/) in the same manner as Save node ([its source code](https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNode.java)).

thanks a lot! @devaskim
