### ISSUE TITLE
Image support with thingsboard

### ISSUE THREAD

**Issue by sgvs-deloitte** [thingsboard/thingsboard#10244]
Hello everyone, Has anyone attempted to upload a picture file to the Thingsboard for a device as one of the telemetry attributes? Since I can't locate any documentation indicating that ThingsBoard offers that kind of feature, is it possible to accomplish that? Please leave a remark if you have any thoughts. I'm grateful in advance.

**Comment by devaskim** [comment]
Try to use Base64 encoding to send image as telemetry and check if [server side configuration limits](https://engix-ltd.github.io/docs/user-guide/install/config/) are big enough for pass your images

**Comment by sgvs-deloitte** [comment]
I have tried base64 string but seems to be not a right way to store the image in postgress DB in encoded version any other alternative way to store them in file structure rather than base64 encoded string
