### ISSUE TITLE
Is it possible for make new device like gateway without TB IoT Gateway

### ISSUE THREAD

**Issue by sirapol** [thingsboard/thingsboard#10256]
**Component**

 * Generic

**Description**
Hello. I doing about gateway for read modbus device.
I using ESP32 for read and write data to modbus each device.

I found the IsGateway toggle button in device.

I would like to know "How it work?".
If I using TB IoT Gateway, I must set it to true for using IoT Gateway function e.g. create new device , bind telemetry and etc. 

But If it make my ESP32 device to be IoT gateway. How I can make it like TB IoT Gateway service ?

**Environment**

 * ThingsBoard: 3.6.2 CM

**Comment by devaskim** [comment]
Just use [MQTT Gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/)
