### ISSUE TITLE
How to change dashboard state to another DASHBOARD in user action (js)?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#10259]
**Component**

 * UI

**Description**
How to change dashboard state to another DASHBOARD in user action (js)?
Thanks.

**Comment by devaskim** [comment]
https://github.com/thingsboard/thingsboard/issues/10140#issuecomment-1931324265

**Comment by devaskim** [comment]
Navigation to another dashboard https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1070

**Comment by psxbox** [comment]
Fine. Thank you. I'll try this.
