### ISSUE TITLE
There is a count property in <tb-owner-autocomplete> component? 

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#10260]
**Component**

 * UI

**Description**
I have a lot of owners. In dialog i use <tb-owner-autocomplete> component for select the owner, and it's give the some list but not all. How I can make this code to show all list?
![image](https://github.com/thingsboard/thingsboard/assets/87794982/5d754a57-2a6d-47df-93b4-e8d2c01cc57f)

**Environment**

 * OS:  Linux
 * ThingsBoard: 3.4.1 PE
 * Browser: Chrome

**Comment by d2eight** [comment]
Hi @psxbox, There is a limit of 50 options for `<tb-owner-autocomplete component>`. Unfortunetely, you cannot configure this in the same way as placeholder and some other configs. If you want to find the single owner quickly, you can use `searchText`.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
