### ISSUE TITLE
Is it possible to install thingsboard/tb-postgres:latest without DEMO data?

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/thingsboard#10263]
**Component**
 * Installation

**Description**
I want to know if it's possible to install thingsboard/tb-postgres:latest **without loading demo** data.

I'm following the guide [Installing ThingsBoard using Docker](https://thingsboard.io/docs/user-guide/install/docker/). 

I can check that it loads DEMO data and I'm wondering if it's possible to install without it.

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/d7247f71-bb5a-4fda-b672-9dd98fd0165f)

**Environment**
 * ThingsBoard: 3.6.2

**Comment by AlexDoanTB** [comment]
@alexcorvis84 hi. 
In dockerized setup, this is not possible. The demo data is a part of the image and on the first launch, you will always see the default tenant + pre-existing entities and configurations. 
As a workaround, after the first start, you can delete a Tenant and execute the docker run command with `-e LOAD_DEMO=false` argument

**Comment by trikimiki** [comment]
Hi
you could also opt for this setup: https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/
it is more customizable (e.g. you can only leave singular "tb-node" running), and there are no additional modifications to dockerfile

> Anyway, as a feature request it would be nice if you could add the LOAD_DEMO (true by default) var into the images as well, in order let users that use dockerized deployment, add that environment variable as 'false' and let us avoiding to deal with this kind of workarounds.

the "LOAD_DEMO" is already part of the env
still, it is a great suggestion overall: I will update install docs accordingly to ensure Compose has this option.
