### ISSUE TITLE
Dashboard search for specific data fields

### ISSUE THREAD

**Issue by quyetvk** [thingsboard/thingsboard#10277]
**Component**

 * UI

**Description**
Current, I am using search feature of entity table and for some data, I use post-processing function to process displayed data on the table. However, it seems search function is applied to raw data (data before doing post-processing).

Am I correct?
And is there any way to configure enabling/disabling fields for searching?

**Environment**

 * OS:  Linux
 * ThingsBoard: v3.6.2
 
 Thanks you for your support!

**Comment by ssakharova** [comment]
Hello @quyetvk,

According to the Thingsboard design, the Post-Processing function changes how data is displayed on the UI but doesn’t modify the underlying data itself. So, if you’re using post-processing for telemetry keys, it affects how the data appears visually but not the actual data.

When you use the search feature in the Entity table, the sorting process occurs on the server-side, not the front end. As a result, the search function operates on the original data (the raw values stored in the database), not the post-processed data displayed on the UI.

Regarding enabling/disabling fields for searching, currently, there isn’t a built-in configuration option for this feature. However, you may be able to achieve this functionality through custom development or by using [dashboard filtering feature](https://thingsboard.io/docs/pe/user-guide/advanced-filters/) of the data displayed in the Entity table based on your requirements.


Best regards,
Sofiia

**Comment by quyetvk** [comment]
Hello @ssakharova 

Thank you for your answer.
I got it.

Best regards

**Comment by rpcai** [comment]
Is there a way to expose the search string from an Entities Hierarchy, or Entities table widget?

I am filtering dashboards based on a USER scoped attribute, which is set on keychange of a custom HTML input widget. However using the native search feature of the stock widgets would be a more elegant solution.
