### ISSUE TITLE
Using Photo Camera Input Widget for Multiple Telemetry Photos

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/thingsboard#10278]
**Widget**

**Description**:
How to use the Photo Camera Input widget to capture and save multiple photos (e.g., 4) as telemetry on ThingsBoard? I’d appreciate any tips or guidance.

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: latest
 * Browser: Chrome

**Comment by devaskim** [comment]
![Скриншот 28-02-2024 153815](https://github.com/thingsboard/thingsboard/assets/86909129/18f8916a-872a-478f-bbcd-025abf928842)

1. Add entity where you want to store the photos.
2. Type existing or new data key.
3. Click if you want to store in an attribute.
4. Click if you want to store in timeseries key.
5. Save dashboard, click `Take Photo` on the widget and click `Allow` if browser asks camera permission.
6. Check you entity's attribute/timeseries data key for a photo(s)

**Comment by Faheem-Punnasseri** [comment]
Great, that was helpful. What if we need to add more than one photo? I think that widget will only allow one photo to be captured and stored, right? Is there any way to capture and store multiple photos (four photos) in a single telemetry payload?

**Comment by Faheem-Punnasseri** [comment]
Yes, I want to include four photos in a single value as evidence of the product. Is it possible? Do you have any suggestions?

**Comment by devaskim** [comment]
> Yes, I want to include four photos in a single value

Due to specificity of your requirements you need to develop widget on your own. As a starting point look at [existing implementation](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/components/phone-input.component.ts)

**Comment by Faheem-Punnasseri** [comment]
Thank you for your response . That was helpful.

> > Yes, I want to include four photos in a single value
> 
> Due to specificity of your requirements you need to develop widget on your own. As a starting point look at [existing implementation](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/components/phone-input.component.ts)
