### ISSUE TITLE
Decode LoRaWAN payload from multiple device vendors

### ISSUE THREAD

**Issue by steve-wright-001** [thingsboard/thingsboard#10270]
I am running an ThingsBoard Professional Cloud instance. I have a Loriot LoRaWAN network server connected on an integration, with a Data Converter decoding most of the JSON from Loriot, all except the LoRaWAN payload.
If I had only one LoRaWAN device type I could include the payload decoding in the Data Converter. However, I plan on using a range of different devices, some from different manufacturers. I cannot find a way in the decoder to know what type of device it is for decoding purposes - I cannot simply rely on fPort I don't think, as I'll have a mix of manufacturers devices, all with different approaches to payload encoding.
I cannot find a way to add this information in Loriot either.
If anyone can suggest how to do this I'd be grateful - it seems to be an obvious requirement, but I cannot find the way to do it.
Many thanks.

Data Converter on the Loriot integration below:

```
var data = decodeToJson(payload);
var deviceName = data.EUI;
var deviceType = "LoRaWAN Device";
var groupName = "LoRaWAN Device";
var gatewayDeviceType = "LoRaWAN Gateway";

// If you want to parse incoming data somehow, you can add your code to this function.
// input: bytes
// expected output:
//  {
//    "attributes": {"attributeKey": "attributeValue"},
//    "telemetry": {"telemetryKey": "telemetryValue"}
//  }

function decodePayload(input) {
    var output = { attributes: {}, telemetry: {} };
    // --- Decoding code --- //

    output.telemetry.hexBytes = bytesToHex(input);

    // --- Decoding code --- //
    return output;
}

var telemetry = {};
var attributes = {};

var timestamp = data.ts;
// If we cannot parse timestamp - we will use the current timestamp
if (timestamp == -1) {
    timestamp = Date.now();
}

var uplinkDataList = [];

if (data.cmd == "rx") {
    attributes.fPort = data.port;
    attributes.fCnt = data.fcnt;

    // You can exclude some keys from the result
    var excludeFromAttributesList = ["data", "gws", "EUI", "ts", "cmd", "port", "seqno", "fcnt", "toa", "ack", "bat", "snr", "rssi"];
    var excludeFromTelemetryList = ["gws", "EUI", "ts", "freq", "port", "data", "cmd", "dr", "offline", "toa", "seqno", "fcnt"];

    var telemetryData = toFlatMap(data, excludeFromTelemetryList, false);
    var attributesData = toFlatMap(data, excludeFromAttributesList, false);

    // Passing incoming bytes to decodePayload function, to get custom decoding
    var customDecoding = decodePayload(hexToBytes(data.data));

    // Collecting data to result
    if (customDecoding.telemetry.size() > 0) {
        telemetry.putAll(customDecoding.telemetry);
    }

    if (customDecoding.attributes.size() > 0) {
        attributes.putAll(customDecoding.attributes);
    }

    telemetry.putAll(telemetryData);
    attributes.putAll(attributesData);

    var deviceInfo = {
        deviceName: deviceName,
        deviceType: deviceType,
        //  assetName: assetName,
        //  assetType: assetType,
        //  customerName: customerName,
        groupName: groupName,
        attributes: attributes,
        telemetry: {
            ts: timestamp,
            values: telemetry
        }
    };

    uplinkDataList.add(deviceInfo);
}

if (data.cmd == "gw") {
    foreach(gatewayInfo : data.gws) {
        var gatewayInfoMsg = {
            deviceName: gatewayInfo.gweui,
            deviceType: gatewayDeviceType,
            attributes: {},
            telemetry: {
                "ts": gatewayInfo.ts,
                "values": toFlatMap(gatewayInfo, ["ts", "time", "gweui", "rssi", "snr"], false)
            }
        };
        uplinkDataList.add(gatewayInfoMsg);
    }
}

return uplinkDataList;
```

**Comment by AlexDoanTB** [comment]
@steve-wright-001, it seems that you can either convert the data into consumable JSON and further extract/process the data from the raw payload in rule chains or create separate integrations based on device manufacturer or payload type. Developing the complex converter fitting to all is somewhat less scalable and hard to debug.

**Comment by steve-wright-001** [comment]
Thanks @AlexDoanTB for your help. I am limited to 5 integrations on my current plan, so I'll look at the rules engine option. I was hoping to avoid this, but I'll get stuck in to understanding it.

**Comment by willjones9** [comment]
@steve-wright-001  The easiest way I've found of doing this is creating device profiles for each device manufacturer, and setting those to use a custom rule chain that includes the implementation specific javascript payload decoder. 

I couldn't figure out how to create separate integrations based upon manufacturer or payload type without using different applications in loriot tied to their own ingress endpoints in thingsboard, which doesn't realistically work at scale.

**Comment by steve-wright-001** [comment]
Thanks @willjones9, I'll give that a go - sounds like a neat solution. So far I've tried detecting the manufacturer from the start of the DevEUI (i.e. the MAC address block), and then do manufacturer-specific decoding within a if block of the data converter. It's working, but it's a bit cumbersome.
