### ISSUE TITLE
Rule Chain connection problem with dashboard

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#10284]
hi everyone. Im intern now. They gave me a issue which is ı couldnt solve the last part. We are sending some telemetry with mqtt which is data type is JSON. I wanna do shift efficiency in thingsboard with these telemetrys. but ı couldnt figure out how ım gonna design the Rule Chain and scripts. ı wanna calculate the shift efficiency and then wanna send to a Dashboard to see. Is there anyone can explane to me?

if ı handle this ım gonna close that issue.

Best regards...

**Comment by cptMULLA** [comment]
I have a sensor collecting data. These sensors collect 2 thing. 1-WorkingTime 2-SpareTime. ı calculate efficiency in the backend. This efficiency calculate the result every 15 seconds and ım seeing on Dashboard widget. But ı wanna calculate one more efficiency on ThingsBoard. This efficiency must takes my efficiency datas which is ı sended evey 15 seconds, and then calculate 8 hours efficiency with my datas. Its gonna take an average 8 hour average. And sended to Dashboard for see on the Widget. I wanna do this on ThingsBoard. I dont wanna write a py code for this. It seems easy but...

**Comment by devaskim** [comment]
Something like this

![Скриншот 01-03-2024 123724](https://github.com/thingsboard/thingsboard/assets/86909129/67bba86c-436f-49c9-a489-c180286a2f04)

**Comment by AndriichnekoDm** [comment]
Hi @cptMULLA ! 
Do you handle this issue?

**Comment by cptMULLA** [comment]
Hi. Yes. But now ım stuck on the code part. Actually ı handle the code part too, but ı wanna see one more thing. Will you help me?
________________________________
Gönderen: AndriichenkoDm ***@***.***>
Gönderildi: 11 Mart 2024 Pazartesi 13:00
Kime: thingsboard/thingsboard ***@***.***>
Bilgi: cptMULLA ***@***.***>; Mention ***@***.***>
Konu: Re: [thingsboard/thingsboard] Rule Chain connection problem with dashboard (Issue #10284)


Hi @cptMULLA<https://github.com/cptMULLA> !
Do you handle this issue?

**Comment by epalchenko** [comment]
Hello.
Feel free to create a new ticket if you have another issue.
