### ISSUE TITLE
Scheduler not publishing shared attribute update

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1028]
I configured a device to be subscribed to one shared attribute, and it is working fine whenever this attribute is update via the GUI. As soon as the "update" button is clicked, the device receives a new message and it contains the new value.

I've set up a Scheduler event (currently running the 5-day trial) to do the very same shared attribute update. The event is triggered at the correct time and the shared attribute is updated, since revisiting the device's page shows the new value.

However, the device does not receive any messages in this case.

Also, if I restart my device, it can see the new value, as it was programmed to query its shared attributes on startup.

Enabling the debug option on the "Save Attributes" block on the default root chain shows that the attribute is received and saved successfully.

Creating a new "Save Attributes" like the one already present on the root chain, but with "Shared" context instead of "Client" does not solve the problem.

Version running is "thingsboard/now 2.1.0PE-1"

Thanks,

**Comment by ashvayka** [comment]
This is fixed and will be available in v2.1.2
