### ISSUE TITLE
Custom icons in icon library

### ISSUE THREAD

**Issue by vastechpro** [thingsboard/thingsboard#10288]
**Component**

 * UI

**Description**
How can I get custom icons uploaded to Image Galary in ThingsBoard to show up in this icon list view:

<img width="560" alt="Screenshot 2024-02-29 at 9 56 49 AM" src="https://github.com/thingsboard/thingsboard/assets/6180900/b0fec68b-b88d-4790-9e27-ab7cb86e783f">

Alternatively, how can I use custom icons in Entities Count widget:

<img width="134" alt="Screenshot 2024-02-29 at 10 00 22 AM" src="https://github.com/thingsboard/thingsboard/assets/6180900/cf6f1348-d38a-4de8-a0ce-c3468de9d9a3">

**Environment**

 * ThingsBoard: Cloud

**Comment by AlexDoanTB** [comment]
@vastechpro ThingsBoard uses material icons set by default. Within the Entities count widget, one cannot use custom pictograms (unless one hacks them using the White labeling — Advanced CSS). It makes sense to have an HTML card instead.

**Comment by vastechpro** [comment]
Ok. Thanks for your reply.
