### ISSUE TITLE
How to get event in rule chain when customer server attributes is updated via widget?

### ISSUE THREAD

**Issue by ronit18** [thingsboard/thingsboard#10283]
In rule chain, I am using Attributes Update to get event when a attribute is updated. But that is working only in device and i want to get the same for customer server attribute update.

**Comment by devaskim** [comment]
On 3.6.2 CE it works as expected (as you need)

![Скриншот 01-03-2024 161114](https://github.com/thingsboard/thingsboard/assets/86909129/6196e88c-3a61-4de2-b61f-477992dedc6d)

**Comment by ronit18** [comment]
> On 3.6.2 CE it works as expected (as you need)
> 
> ![Скриншот 01-03-2024 161114](https://private-user-images.githubusercontent.com/86909129/309240802-6196e88c-3a61-4de2-b61f-477992dedc6d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjAxNjQsIm5iZiI6MTcwOTM1OTg2NCwicGF0aCI6Ii84NjkwOTEyOS8zMDkyNDA4MDItNjE5NmU4OGMtM2E2MS00ZGUyLWI2MWYtNDc3OTkyZGVkYzZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA2MTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzAzMDY5ZTQ4NzBiM2NlMzkyMWIwYmE1ZGE5ZDViY2EzOGQ0YmE1NTA0NjliNjgxYzJjNDBlZWUwMWIzZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.la2_Xn2-SFOQ3u-4y4HNHp6aPujf72kBazFRHtcMbWc)

Yes but i am using Professional edition (3.6.2) and in that i have tested this not working.

**Comment by devaskim** [comment]
Do you try to catch this event in a root chain?

**Comment by ronit18** [comment]
> Do you try to catch this event in a root chain?

Yes. So i tried to catch customer attributes update event in root rule chain and it worked i am able to. But is this the ideal way? or is there a better solution then i did? will this create a problem in my existing rule chains or devices.?

![image](https://github.com/thingsboard/thingsboard/assets/69378341/e2e33fbc-1076-4ae1-8cdc-ddfdc063ff82)

**Comment by devaskim** [comment]
> But is this the ideal way?

The main idea is you get catch customer attributes updates ONLY in a root rule chain. I don't see any problems for your device rule chains.

**Comment by ronit18** [comment]
> > But is this the ideal way?
> 
> The main idea is you get catch customer attributes updates ONLY in a root rule chain. I don't see any problems for your device rule chains.

Yes. This and all the rule chains are working fine. Thank you for your help.
