### ISSUE TITLE
Upgrade from 3.6.1PE to 3.6.2PE fails

### ISSUE THREAD

**Issue by gnosticChemist** [thingsboard/thingsboard#10291]
**Describe the bug**
Upgrading to 3.6.2PE renders the plataform unusable, current session can't load properly and the user are unnable to login.
The log is a spam of the following message:
`[http-nio-0.0.0.0-8080-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column whitelabel0_.customer_id does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column whitelabel0_.customer_id does not exist`

**Server Environment**

* Own setup
  * Deployment: Monolith 
  * Deployment type: deb
  * 3.6.1/3.6.2
  * Professional Edition
  * Ubuntu 20.04.6 LTS

**Comment by gnosticChemist** [comment]
Yes, I have followed the upgrade instructions for PE. I used the "merge option" as recommended, but as stated the system broke. I then downgraded back to 3.6.1 and tried again overwritting the configuration file, still didn't work

**Comment by ViacheslavKlimov** [comment]
Hi @gnosticChemist.
What is "merge option"? 
Please provide the exact list of commands you executes to reproduce the issue.

**Comment by gnosticChemist** [comment]
My apologies, I couldn't try another update until now. 
I updated and it worked fine, looking into my bash history it seens I missed the execution of the upgrade script somehow
I'm sorry for the confusion and thanks for the help
