### ISSUE TITLE
Custom action in widget: URL constructed from widget data

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10299]
I need to create a custom action in a **Value Card Widget** that opens a URL in another browser tab. The URL has to be constructed according to the widget data. I'm using this code:

`window.open('https://www.google.com/xxxxxxxx', '_blank');`

I need to replace `xxxxxxxx `with the widget content, which is a number (e.g., 514983720) coming from a telemetry measurement.

Thanks in advance

**Comment by gcorthey** [comment]
Thanks @devaskim for your reply. Where can I test `console.log(widgetContext.data)` in thingsboard UI?

**Comment by devaskim** [comment]
Put it in the code of your custom action. Then call that action and look at browser's DevTools Console

**Comment by gcorthey** [comment]
Solved
