### ISSUE TITLE
Migrate entire Thingsboard installation from Windows to Ubuntu Server

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#10292]
**Component**

 * Installation
 
**Description**
We currently have a Thingsboard installation on a Windows machine and we wanted to upgrade it to a new one using Ubuntu server. What are the steps needed to have this working? Because I have seen a couple posts related to this but they were from Windows to Windows or Ubuntu to Ubuntu, but not what we wanted, which is Windows to Ubuntu. So I wanted to ask if there is an specific way to do this migration or any special steps to be taken into consideration.

**Environment**

 * OS:  W10 Pro
 * ThingsBoard: 3.6.1

**Comment by devaskim** [comment]
There is no any specific step: just make database dump, restore it on a new server and run TB.
