### ISSUE TITLE
How to resolve attributes received from devices.

### ISSUE THREAD

**Issue by sequencer** [thingsboard/thingsboard#103]
for example, I have a device which can use baseband data, but I can't get the GPS data.
I have got 4 attributes which have been posted to device "TEST_DEVICE"
```
{
  mcc:460,
  mnc:01,
  lac:57605,
  ci:142884903
}
```

I have to use a curl to get response from other website like this`
http://api.cellocation.com/cell/?mcc=460&mnc=01&lac=57605&ci=142884903&output=json`

and I got the response like this:
```
{"errcode":0, "lat":"30.482374", "lon":"114.415634", "radius":"566", "address":"湖北省武汉市洪山区光谷总部国际9栋;光谷大道与凌家山南路路口南355米"}
```

And finally I should save this json to "TEST_DEVICE"
and display it with map.

**Comment by sequencer** [comment]
By the way, I still think there should be a javascript plugin in the handler of request from device or gateway.
some device are to hard to transport strange data.

**Comment by ashvayka** [comment]
Hi!
The best option for now is to write a micro-service using any language that will receive message with 4 attributes/time-series values from device. You can forward data to your micro-service using [**REST plugin**](https://thingsboard.io/docs/reference/plugins/rest/). Once you get the latitude and longitude in your microservice you can send this data as a server-side attributes using POST request to: 
http://host:port/api/plugins/telemetry/$DEVICE_ID/SERVER_SCOPE and payload {latitude: 42.2}

**Comment by ashvayka** [comment]
Please note that I have added todo item to publish end-to-end integration article based on this use case.

**Comment by sequencer** [comment]
Thank you! I got it, trying python to resolve it :)

**Comment by ikulikov** [comment]
Closing due an inactivity.
