### ISSUE TITLE
An error occurred while attempting to decode the Jwt

### ISSUE THREAD

**Issue by samirlenka** [thingsboard/thingsboard#10301]
Hello Team,

I a trying to use Google, OAuth and Azure AD Authentication process to login into Thingsboard UI but I am getting this below Error while trying to login. Unfortunately, I am able to login for 15 to 20 minutes duration and after that I am not able to login subsequently.  Kindly help me with this. I don't know where exactly Thingworx stores its sessions and Auth tokens. 

Kindly help Thank you in advance for your support.

**Comment by samirlenka** [comment]
@ashvayka  Kindly help

**Comment by sumin-denys** [comment]
Hi @samirlenka,

I am closing this issue due to duplication. For any further discussions or updates, please refer to issue #10341
