### ISSUE TITLE
How to increase the maximum data count for the time-series widget?

### ISSUE THREAD

**Issue by openedhardware** [thingsboard/thingsboard#1030]
I noticed that the maximum data count is 500.

![image](https://user-images.githubusercontent.com/16890683/44515174-21754580-a6c2-11e8-86f9-fdcc9e709f06.png)

I want to show past data(for over 2 months) by setting `grouping interval` as an **hour**.

But if I change the range to 60 days, the `Grouping Interval` value rises to `5 hours` and I can't select `1 hour`.

Any idea?

**Comment by nabil-rejeb** [comment]
You have to edit /ui/src/app/api/time.service.js and change 
const MIN_LIMIT = 10;
const AVG_LIMIT = 200;
const MAX_LIMIT = 500;
to suitable values for your use case.
and rebuild the application.

**Comment by openedhardware** [comment]
Thanks for your reply, @nabil-rejeb !

By the way, I had purchased PE running on Ubuntu.

So how can I rebuild on my machine?
