### ISSUE TITLE
How to use API /alarmsQuery/count to get total count of one specific device

### ISSUE THREAD

**Issue by Zhuxf1111** [thingsboard/thingsboard#10305]
**Component**

 * Generic

**Description**
I'm working on my app based on thingsboard api, I want to show a table the total count of alarm created by specific device on my dashboard, and I won't like to using list api and do an extra compute, I think use this api would be better. but I don't find anything related to the payload entityFilter. 

I tried 

```
{
  "entityFilter": {
    "type": "entityType",
    "entityType": "DEVICE",
    "deviceName": "Charging Port 1"
  }
}
```

but it doesn't work.

**Environment**
 * OS:  macOS Sonoma
 * ThingsBoard: Sandbox
 * Browser: Chrome, 121.0.6167.184

**Comment by myroslav-tb** [comment]
Hi @Zhuxf1111 you can use this exapmle to count alarms for the specific device:

```{
  "assigneeId": {
    "id": "18075560-c0ed-11ee-a5eb-ef1e476b648a",
    "entityType": "USER"
  },
  "endTs": 1717071358000,
  "entityFilter": {
    "type": "singleEntity",
    "singleEntity": {
      "id": "84bbbe70-c0ee-11ee-b22b-0b05357c5f1d",
      "entityType": "DEVICE"
    }
  },
  "keyFilters": [],
  "searchPropagatedAlarms": true,
  "severityList": [],
  "startTs": 0,
  "statusList": [],
  "timeWindow": 0,
  "typeList": []
}
```

You can find more information about entity queries here: https://thingsboard.cloud/swagger-ui/#/entity-query-controller/countEntitiesByQueryUsingPOST

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
