### ISSUE TITLE
Difference between Thingsboard MQTT broker implementation and Mosquito broker

### ISSUE THREAD

**Issue by occoder** [thingsboard/thingsboard#1031]
My MQTT client was able to publish messages to Mosquito broker without any exception raised.
But when connecting to Thingsboard built-in MQTT broker, the client incurred "Unable to publish" exception.
The weird thing is Mosquito client really worked fine with Thingsboard built-in MQTT broker.
Is there any subtle implementation difference between Thingsboard MQTT broker implementation and Mosquito broker that may cause such problem?
Thanks any any comment.

**Comment by nabil-rejeb** [comment]
From documentation you can find 
**ThingsBoard server nodes act as an MQTT Broker that supports QoS levels 0 (at most once) and 1 (at least once) and a set of predefined topics.**
You have to change your client topics to suite thingsboard predefined topic or use The ThingsBoard IoT Gateway.
