### ISSUE TITLE
Open public panel from customer panel and maintain the session

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#10317]
**Component**

 * UI

**Description**
Good morning,

I have a panel accessible to a customer, and I want to put a link or an embedded panel to display a public panel of the platform itself. The problem is that when visiting a public panel, I understand that the cookies are changed and when returning to the previous window, it asks to log in again.

Is there any way I can view a public panel and still maintain the session?

Thank you very much for the help,

All the best

**Comment by mykhailokornieiev** [comment]
Hi
If your question is still relevant, please describe it in as much detail as possible with screenshots and full steps to reproduce of current behavior

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
