### ISSUE TITLE
Failure in HTTP Integration for Timeseries Data with Messages over 100k Symbols

### ISSUE THREAD

**Issue by novitum** [thingsboard/thingsboard#10313]
**Describe the bug**

We found a bug related to the "rest api call" node within my rule chain. The rule chain is designed to retrieve Timeseries Data from another system using a REST API GET request. Subsequently, it formats the retrieved data and utilizes the node "Send Timeseries Data to Integration". This node is responsible for initiating a REST API POST request through the HTTP integration. The objective is to store the formatted Timeseries Data as Server Attributes on a newly created device.
![image](https://github.com/thingsboard/thingsboard/assets/122453872/10bf480b-db49-4c49-b8a7-086a56102487)

We observed that messages with a length under 100k symbols are processed successfully, while those exceeding 100k symbols are consistently marked as failures.

Success:
![image](https://github.com/thingsboard/thingsboard/assets/122453872/e6da7206-5137-46c3-bc7e-780cb883d714)

Failure:
![image](https://github.com/thingsboard/thingsboard/assets/122453872/3faf8ea0-0b29-4349-a361-c339f6a6f2e6)

![image](https://github.com/thingsboard/thingsboard/assets/122453872/69df88ec-3f20-4f64-aab9-1bc0b862e6fa)

The initial attempt to address the error involved modifying the configuration file. Specifically, the 'JS_MAX_SCRIPT_BODY_SIZE' was set to 200k. But the error persisted despite making these configuration file adjustments.
![image](https://github.com/thingsboard/thingsboard/assets/122453872/f178d4e4-ac4d-42c7-b7b3-d9b407a1e384)

Additional parameters that could influence the transmitted data volume are located in the upstream reverse proxy (nginx). In our case, the following parameter is configured for requests/payloads: client_max_body_size 8M;
I increased it to 16M for testing purposes; however, the error persists when the payload exceeds 100k.

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: deb
  * ThingsBoard Version: 3.5.1PE
  * Professional Edition
  * OS Ubuntu

* Connectivity
  * HTTP-Integration

**To Reproduce**
1. Create new Rulechain to send / post timeseries data with <100k and >100k symbols using node "rest api call"
2. Create new 'HTTP-Integration' and 'Data Converter' --> use Integration Key in Endpoint URL pattern
3. Enable debugging in node

**Expected behavior**
Successful upload of all data

**Comment by dashevchenko** [comment]
Hi @novitum! Could you please turn on logging (HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE=true) and check Converter/Integration debug events?

**Comment by ViacheslavKlimov** [comment]
Hi @novitum,
Have you managed to discover what the issue is after looking at integration debug events?

**Comment by novitum** [comment]
Hi and thanks for the reply. Unfortunately I do not have direct access and am dependent on the answers of the server admin. As soon as I have the info, I'll get back to you with the corresponding screenshots.

**Comment by novitum** [comment]
I now get a different error message than before. For example, the highlighted message.
![image](https://github.com/thingsboard/thingsboard/assets/122453872/fd1686ca-220e-48d7-84e7-a3b5fc455ed3)

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : "java.util.concurrent.ExecutionException: org.thingsboard.script.api.TbScriptException: java.lang.IllegalArgumentException: **Script input arguments exceed maximum allowed total args size of 150000 symbols**<EOL>?at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)<EOL>?at ... etc.

But we have set JS_MAX_ARG_SIZE to 500.000 (as you see on the screenshot above).
[gc.log](https://github.com/thingsboard/thingsboard/files/14740698/gc.log)

Attached the log data. If you need more or different logs, please let me know.

**Comment by dashevchenko** [comment]
Hi @novitum 
From what I can see, you configured js settings (JS_MAX_TOTAL_ARGS_SIZE), but your integration uses tbel for processing telemetry, so you need to customize  TBEL_MAX_TOTAL_ARGS_SIZE instead of JS_MAX_TOTAL_ARGS_SIZE.

**Comment by novitum** [comment]
Thank you for your help. The issue has been solved with customizing TBEL_MAX_TOTAL_ARGS_SIZE.
