### ISSUE TITLE
Thingsboard notification in flutter app

### ISSUE THREAD

**Issue by mahshadparsa** [thingsboard/thingsboard#10320]
Hi everybody
I have created the Flutter app for getting data from thingsboard. I set temperature rules for creating alarms. I can get alarms by:
AlarmQuery(TimePageLink(10,0,null,SortOrder('createdTime',Direction.DESC)),fetchOriginator:true);
But, I need a local notification on the Flutter app, that shows an alarm when the app is not open. 
Please guide me, on how can I get notifications on the Flutter app according to the Thingsboard alarm.

 * ThingsBoard:  thingsboard_client: ^1.0.8
 * flutter_local_notifications: ^16.3.2
 * Flutter 3.19.2

**Comment by AndriichnekoDm** [comment]
HI @mahshadparsa !
Open this issue here https://github.com/thingsboard/flutter_thingsboard_app/issues
