### ISSUE TITLE
Using customer title as filter inside device profile alarm condition

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#10322]
**Component**

* Device profile
* Alarm

**Description**
Is there a way to get customer title inside device profile alarms condition ?

![image](https://github.com/thingsboard/thingsboard/assets/7483656/a0da80d6-dfa4-4e5c-899a-ae3e121ebd4e)

**Environment**

  * ThingsBoard Cloud Prototype

**Comment by AlexDoanTB** [comment]
@lstarke, if you store the Customer name as an attribute or Time series, you can use the dynamic value. The Entity name itself is an Entity field in ThingsBoard by default. EF cannot be the source of a threshold.
