### ISSUE TITLE
ThingsBoard Cassandra Backup

### ISSUE THREAD

**Issue by Tiricz** [thingsboard/thingsboard#1033]
Hi,

I would like to make backup of Thingsboard server.  Could you please help me with some suggestions? (for cassandra)

Thank you in advance!

**Comment by gopirathnamt** [comment]
hi , i will help you . But i need to know some of the information . Are u currently using cassandra db or other db for thingsboard ?

**Comment by Tiricz** [comment]
hi, thank you for helping,
the Thingsboard uses a cassandra database.
backup must be created with cassandra.

**Comment by gopirathnamt** [comment]
use cqlsh to go to cassandra .
Then type "use thingsboard ; "
then in thingsboard database has the all the tables and u can take back up of what table u need .
If u have further more doubts mail me :gopirathnamt@gmail.com.

**Comment by vijayshukla80** [comment]
Hi 
I am using thingsboard 2.3.1 and i want to take database backup.

Please let me know the steps vijayshukla.tb@gmail.com

**Comment by dip-devlopement** [comment]
> Hi, thank you for helping, the Thingsboard uses a cassandra database. Backup must be created with cassandra. I'm using a version of Thingsboard 2.0.3, cassandra version 3.11.3

I have perfect solution for that. Contact on dharmikprajapati230@gmail.com
