### ISSUE TITLE
ThingsBoard Edge PE - Connection Error with TB PE

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#10335]
**Describe the bug**
We currently try to connect a ThingsBoard Edge PE instance with our ThingsBoard PE Kubernetes Cluster (on Azure):

```
2024-03-08 09:56:52,320 [cloud-manager-reconnect-74-thread-1] INFO  o.t.s.s.cloud.CloudManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: edge.EdgeRpcService/handleMsgs!
2024-03-08 09:56:52,325 [cloud-manager-reconnect-74-thread-1] INFO  o.t.edge.rpc.EdgeGrpcClient - [8a5003fd-f90c-4e8d-9d2f-891654b37836] Sending a connect request to the TB!
2024-03-08 09:56:52,354 [grpc-default-executor-0] WARN  o.t.edge.rpc.EdgeGrpcClient - [8a5003fd-f90c-4e8d-9d2f-891654b37836] Stream was terminated due to error:
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found
```

**Your Server Environment**

* own setup
  * Deployment: microservices
  * Deployment type: k8s
  * ThingsBoard Version 3.6.2 PE
  * Professional Edition
  * TB Edge PE Version 3.6.2 PE
  *  TB Edge PE Host Ubuntu / separate Server

**Expected behavior**
Connection between Edge and ThingsBoard Cloud can established successfully.

**Screenshots**
```
# UNCOMMENT NEXT LINES AND PUT YOUR CLOUD CONNECTION SETTINGS:
export CLOUD_ROUTING_KEY=8a5003fd-f90c-4e8d-9d2f-891654b37836
export CLOUD_ROUTING_SECRET=8uKHNb6svbfJJB3SbSJP
 
# UNCOMMENT NEXT LINES IF EDGE CONNECTS TO PE 'THINGSBOARD.CLOUD' SERVER:
# export CLOUD_RPC_HOST=thingsboard.cloud
#export CLOUD_RPC_SSL_ENABLED=true
 
# UNCOMMENT NEXT LINES IF YOU CHANGED DEFAULT CLOUD RPC HOST/PORT SETTINGS:
export CLOUD_RPC_HOST=XX.XX.XX.XX
export CLOUD_RPC_PORT=9090
```

**Additional context**
Log file is attached
[tb-edge-error-log.txt](https://github.com/thingsboard/thingsboard/files/14537175/tb-edge-error-log.txt)

**Comment by volodymyr-babak** [comment]
@mde2017

Thanks for reporting this issue.

The error seems unusual as per the stack trace, indicating that the Edge was connected not to the ThingsBoard Server, but to some other software.

Could you please provide more details about your Kubernetes setup? Specifically, we are interested in the load balancer configuration for the Edge connection on the Kubernetes side.

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
