### ISSUE TITLE
Cell style function in entities table: call entity server attribute to decide on cell style

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10333]
In an **Entities table** I need to get some **server attributes** from the entity in that row in order to decide on the *Cell style function** (e.g. background color).

Like this but instead of using numbers (0, 35) use an the entity server attribute:
```
if(value < 0) {
   return {"background-color" : "#5F4DEB"};
} else if (value < 35) {
    return {"background-color" : "#62c5e3", "color" : "#19154a"};
```

**How can I do that?**

**Comment by gcorthey** [comment]
I solved this by adding the attributes I needed to the datasource of the table. Then I can access to those attributes directly.

```
const minTemp = entity.minTemp;
const maxTemp = entity.maxTemp;

if ( (value < minTemp) || (value > maxTemp) ) {
    return {
        "color": "red",
        fontWeight: "bold"
    };
} else {
    return {
        "color": "lime",
        fontWeight: "bold"
    };
}
```

![image](https://github.com/thingsboard/thingsboard/assets/11965006/9307edbd-87bc-4c20-896f-9264016e5f43)

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
