### ISSUE TITLE
Hide chart timewindow if entity is not resolved

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#10347]
**Is your feature request related to a problem? Please describe.**

Each our asset may have either one or two sensors. If the second sensor is absent, I would like to see nothing in the lower part of the screen. With the help of CSS I hide `No data to display` message, but there is chart's time window to be displayed disregarding entity is resolved or not.

Considering that TB users don't have feature of conditionally hiding widgets https://github.com/thingsboard/thingsboard/issues/6866, I ask TB ream (maybe @vvlladd28) to implement this request.

![Скриншот 11-03-2024 164941](https://github.com/thingsboard/thingsboard/assets/86909129/d14bf013-f917-4070-b1b9-f226b8d48ddd)

**Comment by AlexDoanTB** [comment]
@devaskim If using the Markdown HTML card widget, would it be easier to update the onRowClick action and add a simple check of the related entities of a parent (one you choose from the state)? If all the related entities have their state configured, and the action returns stateIds that are resolved (and the widget will render them), the ones without data sources will remain intact.

**Comment by devaskim** [comment]
@AlexDoanTB Sounds like Jedi technics considering that Markdown widget hasn't `onRowClick` action )))

As I understand your idea, I should use `Markdown/HTML value function` and `tb-dashboard-state` to show each resolved child entity. Correct me, if I am wrong?

I was hoping to avoid any "enterprise" dashboard/widget solution. And also I need to display the first sensor (relation `Sensor 1`) strongly on the top, and the second sensor (relation `Sensor 2`) if it exists - only at the bottom. So if I would use Markdown widget, I need to walk through resolved datasource(s) and if there would be 2 datasource, I would need to search for first and second sensor to show them on top or on the bottom.

**Comment by AlexDoanTB** [comment]
@devaskim 
> Sounds like Jedi technics considering that Markdown widget hasn't onRowClick action )))

hah, it was about the action for the Entities table where one chooses the target asset, while details are rendered in the MD card based on the data sources. 

For the case that you have (with interrelated devices), perhaps you may have short and full states configured: `state 1 `with `sensor 1` chart and `state 2` with charts for `sensor 1`  and `sensor 2`. If the relation between `sensor 1` and `sensor 2` exists, render `state 2`, else `state 1` comes to the play.

**Comment by devaskim** [comment]
@AlexDoanTB Thanks for your time and suggestions. Seems like I should implement the latter one.
