### ISSUE TITLE
Creating Public Folder for Direct Browser Access

### ISSUE THREAD

**Issue by DanielBustillos** [thingsboard/thingsboard#10340]
**Component**

 * Generic

**Description**
Is it possible to create a public folder in the ThingsBoard application server and access its contents directly from the browser? For instance, I would like to upload some files to a folder within ThingsBoard and share a public link to access these files. Is there a feature or configuration that supports this use case?

Or is there a public file where I can host files?

For my use case (creating a service worker) I need to the files be accesible in the same port of the app, in my case 443.

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard: 3.6.2 (build from source)
 * Browser: Chrome, Safari, etc.

**Comment by Ultrazombie** [comment]
Hello @DanielBustillos 
We don't have this functionality yet, but our customers have made such requests, and we will consider how to implement this in future releases.

**Comment by DanielBustillos** [comment]
Thank you
