### ISSUE TITLE
Add historic data to device

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#10346]
**Component**

 * Generic

**Description**
I have a question about adding historical telemetry data to a device that is already created. Can you add data from the past? I have thought about adding data manually to the database, can it be done in this way? Are there other methods to do this?

**Environment**

 * ThingsBoard: 3.6.2

**Comment by jortega11** [comment]
Thank you!

I was thinking about using this feature to save battery power in my microcontroller making it take some measurements before connecting to the internet because that is a more power demanding task, and then, send the telemetries it has collected in that time. Could something like this be possible with the Telemetry controller?

**Comment by AlexDoanTB** [comment]
@jortega11 yes. You can also collect the data and send an array or nested object with corresponding timestamps instead of using REST API.

**Comment by jortega11** [comment]
I did not know that.

I could manage to get that working as I wanted, thanks!
