### ISSUE TITLE
Render dashboard widgets based on asset-device search query results

### ISSUE THREAD

**Issue by sprijk** [thingsboard/thingsboard#10344]
**Component**

 * UI

**Description**
Problem: many customers may have varying amounts of sensors per asset, so their asset dashboard widget configuration differs per use case. However, there is a selected set of possible sensor types. Onboarding new customers and assigning one default dashboard which is able to generate required widgets is favorable.

**Question**
Is it possible to render widgets dynamically to show/hide based on sensors belonging to an asset (via relations query)?

**Example use case**
1. A temperature indicator widget (e.g. Value card) is configured but only shows when a device of type "Thermometer" belongs to an asset, or a battery indicator widget only shows when a device of type "Battery sensor" belongs to an asset.
2. Two temperature sensors belong to an asset, and therefore two temperature indicator widgets are rendered.

**Possible solution / Feature request**
Create a widget-container that performs a device search from the asset for a specific device type. Depending on the relation query result it renders 0 to n widgets preconfigured for a device type (e.g. temperature), rendering out the the right device names (or device labels).
The the widget-container needs to know the device type it will display and its data (e.g. timeseries parameter or device attribute).

**Workaround / Alternative**
On each new customer device claim event / asset-device relation update:
1. Programmatically loop over all customers and their asset.
3. Generate a unique key for each configuration of widgets from a asset-device relation query.
4. If the configuration of sensors does not exists → Dynamically generate an new asset dashboard for this configuration.
5. Finally, assign the dashboard to the customer.

**Environment**

 * ThingsBoard: 3.6.2

**Comment by sprijk** [comment]
Basically the request is like an Entities table, but it renders Value cards instead of table rows.

**Comment by devaskim** [comment]
Try to use Markdown/HTML widget and its `Use markdown/HTML value` function. There you can re-use `tb-dashboard-state` component to conditionally show/hide dashboard states with type-specific widgets.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
