### ISSUE TITLE
How to change device owner from python api in thingsboard pe

### ISSUE THREAD

**Issue by edanry** [thingsboard/thingsboard#10352]
I want to change the owner of a device via API. When I look at the example files, I find the change_owner_to_customer function, but it gives this error. How can I solve it? 

HTTP response body: b'{"status":500,"message":"Type definition error: [array type, component type: [simple type, class java.lang.String]]; nested exception is com.fasterxml.jackson .databind.exc.InvalidDefinitionException: Cannot construct instance of `java.lang.String[]`: no String-argument constructor/factory method to deserialize from String value (\'ff585200-e039-11ee-86b7-234492c4b328\')\ \n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1]","errorCode":2,"timestamp":1710225020327,"subscriptionErrorCode":null,"subscriptionEntry": null,"subscriptionValue":null}'

**Comment by ashaforost** [comment]
Hi @edanry 

Make sure that the Id parameters in this method call is not a string like `'ff585200-e039-11ee-86b7-234492c4b328'`but an object called EntityId

here's an example:
` device = EntityId(id='c09b2f50-060a-11ef-88ff-e5eba3ba01cf', entity_type="DEVICE")
rest_client.change_owner_to_customer(owner_id=owner, entity_id=device)
`
Also, make sure to use the latest version of the Python rest client.

In case you see any other errors with python rest client, please report them to [thingsboard-python-rest-client Github Issues ](https://github.com/thingsboard/thingsboard-python-rest-client)

I'm closing this issue as it does not relate to the thingsboard project
