### ISSUE TITLE
Is it possible to automatically adjust the scale of the vertical axis of a time series line chart to match the data?

### ISSUE THREAD

**Issue by YS-HARM** [thingsboard/thingsboard#10359]
Among the Axis items in the Timeseries Line Chart advanced settings, is it possible to have the Minimum value on the scale on the vertical axis change automatically according to the data value without setting it?
For example, if the minimum data value is 1000, I would like the Minimum value on the scale to be 800, which is below 1000.
I have a purpose of wanting to see the graph in a larger size.
Please help, I would appreciate it.

I am using thingsboard cloud.

**Comment by YS-HARM** [comment]
I am using thingsboard cloud.

**Comment by mykhailokornieiev** [comment]
Hi
There is no such possibility of setting up dynamic change for min or max value on Axises. The only way is to left them in Auto mode. 
Or, you can create your own custom widget which will meet all desired requirements.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
