### ISSUE TITLE
Thingsboard PE - When duplicating telemetry data form a device to an asset, timeseries data fails to display

### ISSUE THREAD

**Issue by pgirgis2sg** [thingsboard/thingsboard#1035]
When duplicating or changing originator in a rule chain to replicate telemetry data from a device to an asset, the latest telemetry data is visible and can be used in latest data dashboard widgets.  However when using historical timeseries data with the entity of an asset, it fails to display. 

It appears that the historical timeseries data is not stored and made available for use in dashboards.

**Comment by ashvayka** [comment]
Only new messages(after rule was configured) are pushed to parent asset when they arrive. We are not going to make this available in next releases. Instead, we are implementing new cool feature called EntityViews. They will allow you to create different views of the same device without duplicating the telemetry.

**Comment by pgirgis2sg** [comment]
Awesome

Peter Girgis | Chief Technology Officer
2SG Technology Group
 
P: 0427 670 870  | pgirgis@2sg.com.au 
Delivering feature rich software solutions, accompanied by a range of data, communications and M2M products
Other companies within the 2SG Technology Group
www.bigmate.com.au | www.2sgwholesale.com.au  | Contact Centres

> On 22 Sep 2018, at 08:07, Andrew Shvayka <notifications@github.com> wrote:
> 
> Only new messages(after rule was configured) are pushed to parent asset when they arrive. We are not going to make this available in next releases. Instead, we are implementing new cool feature called EntityViews. They will allow you to create different views of the same device without duplicating the telemetry.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.
