### ISSUE TITLE
Thingsboard CE on ubuntu 22.04?

### ISSUE THREAD

**Issue by m-anish** [thingsboard/thingsboard#10354]
**Component**

 * Installation

**Description**
Is thingsboard CE supported on ubuntu 22.04 LTS server. I am creating a digitalocean droplet, but the two pieces of documentation I can find refer to Ubuntu18.04/20.04 but not 22.04. 

So, my question is whether 22.04 is a supported OS, or should I save myself the effort and just go with 20.04

**Comment by devaskim** [comment]
There is no strong restriction on Ubuntu version

**Comment by m-anish** [comment]
@devaskim thanks for your reply. Also, are you aware of any installation scripts/playbooks, or the steps mentioned in the guide are the preferred way to go.

**Comment by devaskim** [comment]
I use official [TB in Docker guide for Ubuntu](https://thingsboard.io/docs/user-guide/install/docker/ and haven't ever faced with some problems

**Comment by m-anish** [comment]
Thanks. I was also able to follow the non-docker install guide and was able to get it up on a 1GB droplet, but it feels that its too little RAM. Need bigger droplet, but the installation process worked.
