### ISSUE TITLE
How to use Previously data

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#10353]
I have a data which is ı collected from sensors. I wanna calculate like this: I'll take this depth data, and then ı'll wait for a 30 seconds (problem starts here) ı write this code:

var previousShiftDepthProgress = 0;

  var currentShiftProcess = totalMassDP; 

  var shiftProgress = currentShiftProcess - previousShiftDepthProgress; 

  previousShiftDepthProgress = currentShiftProcess; 
  
  
  every 30 seconds ı calculate somethings. But this code doesnt work. Because every -ı set for 30 seconds- shift everthings gets restart and does not store data, so thats why ı couldnt use previously data. I stucked here. What am ı missing? I use a rule chain and this code is in blue script. İs there any way to do this on another rule in the rule chain. Suggestions?
  
  Thanks.

**Comment by devaskim** [comment]
To store data you should do 2 step:
1. Use `Script` node to set data key to `msg`, e.g.
```
// some your code

var data = {
    'previousShiftDepthProgress': PUT_THERE_YOUR_VALUE
};

return { msg: data , metadata: metadata, msgType: 'POST_TELEMETRY_REQUEST'};
```

2. Link the node from previous step with `Save timeseries` node to store data to database.

**Comment by cptMULLA** [comment]
My code is exactly same.
