### ISSUE TITLE
Let changing data key type without recreation

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#10364]
**Is your feature request related to a problem? Please describe.**
It may take much time to change the type of data key if it has various basic and advanced custom settings.
![Скриншот 13-03-2024 180839](https://github.com/thingsboard/thingsboard/assets/86909129/7fb18ba3-c3d0-4ee7-90cb-0c9c49ae1a66)

**Describe the solution you'd like**
Let a user to click on data key's type icon and change the type (Attribute, Time Series, Entity Field)

**Describe alternatives you've considered**
Data key recreation.

**Comment by ssakharova** [comment]
Hello @devaskim,

I passed all the provided information to our developers and created an internal prod ticket for them to decide on its necessity and possible implementation in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
