### ISSUE TITLE
[docs] Documentation Inconsistency

### ISSUE THREAD

**Issue by antoninoLorenzo** [thingsboard/thingsboard#10362]
This isn't a bug but the label was the best fit for the issue I am raising.

I successfully installed ThingsBoard, after some trial and error, however, there is something about the documentation that to me is wrong; specifically, I am talking about [Installing ThingsBoard using Docker (Windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/), the following section talks about using VirtualBox to expose the dashboard on the local machine:

`In order to get access to necessary resources from external IP/Host on Windows machine, please execute the following commands`
```
set PATH=%PATH%;"C:\Program Files\Oracle\VirtualBox"
VBoxManage controlvm "default" natpf1 "tcp-port8080,tcp,,8080,,9090"  
VBoxManage controlvm "default" natpf1 "tcp-port1883,tcp,,1883,,1883"
VBoxManage controlvm "default" natpf1 "tcp-port7070,tcp,,7070,,7070"
VBoxManage controlvm "default" natpf1 "udp-port5683,udp,,5683,,5683"
VBoxManage controlvm "default" natpf1 "udp-port5684,udp,,5684,,5684"
VBoxManage controlvm "default" natpf1 "udp-port5685,udp,,5685,,5685"
VBoxManage controlvm "default" natpf1 "udp-port5686,udp,,5686,,5686"
VBoxManage controlvm "default" natpf1 "udp-port5687,udp,,5687,,5687"
VBoxManage controlvm "default" natpf1 "udp-port5688,udp,,5688,,5688"
```

So the problems are the following:
- VirtualBox was never mentioned;
- "default" vm doesn't exist, that's no surprise, we are working with Docker...

The dashboard is still accessible from local machine, so I think this is managed during the docker installation, matter of fact when I run `docker ps` I get the following output:
```
CONTAINER ID   IMAGE                     COMMAND         CREATED          STATUS          PORTS                                                                                                      NAMES
93a5ccdcb215   thingsboard/tb-postgres   "start-tb.sh"   21 minutes ago   Up 20 minutes   0.0.0.0:1883->1883/tcp, 0.0.0.0:7070->7070/tcp, 0.0.0.0:5683-5688->5683-5688/udp, 0.0.0.0:8080->9090/tcp   thingsboard-mytb-1
```

So, I think the documentation should be updated to avoid confusion.

**Comment by Justice-Udehegbunam** [comment]
Hi @antoninoLorenzo, thank you for your diligence in reviewing the documentation and for your feedback. As a fellow contributor, your insight is invaluable to me in ensuring the accuracy and clarity of our documentation.

Upon re-examining the README file in the Docker directory and conducting a comprehensive search throughout the repository, I couldn't locate any references to "VirtualBox." It appears that the documentation is indeed Docker-specific and does not necessitate the use of VirtualBox for installation or setup.

Your feedback underscores the importance of maintaining clear and accurate documentation, and I want to assure you that I take your concerns seriously. If there are specific sections or files where you encountered mention of VirtualBox, or if you have any additional insights or questions, please don't hesitate to share them with me. Your input will help me address any lingering ambiguities and enhance the documentation for all users.

Thank you once again for your contribution to the project, and for your commitment to improving the overall user experience.

Warm regards,
Justice

I am open for more observations

**Comment by antoninoLorenzo** [comment]
Hi, thank you for your appreciation, you can find the issue I am talking about at the following link [Installing ThingsBoard using Docker (Windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/), specifically here:
![Cattura](https://github.com/thingsboard/thingsboard/assets/94693967/0c04b61a-4622-449a-b800-d0ed14546297)

I don't know where specifically it can be fixed, I suppose that there is a CD pipeline for the documentation, however, I hope the screenshot helps.

**Comment by Justice-Udehegbunam** [comment]
Hmm!,

**Comment by trikimiki** [comment]
Hi @antoninoLorenzo 
Thanks for noting that!
I will update/clean-up some install docs soon-ish, and will refactor (or perhaps remove completely) these steps.
