### ISSUE TITLE
how to query entity with attribute not exist ?

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#10367]
**Component**

 * Generic

**Description**
I want to query some Staff which is an asset and  has attribute cardId in SERVER_SCOPE. But if a Staff is create, the attribute is not exist. 
When i query staffs which are not assign to any card, i don't know how to set the KeyFilter.
The StringFilterPredicate only works for nonNull value.
 I tried this:

```java
StringFilterPredicate.StringOperation operation = bingCard
                            ? StringFilterPredicate.StringOperation.CONTAINS
                            : StringFilterPredicate.StringOperation.NOT_CONTAINS;
            KeyFilter keyFilter = new KeyFilter();
            keyFilter.setKey(new EntityKey(EntityKeyType.ATTRIBUTE, "cardId"));
            keyFilter.setValueType(EntityKeyValueType.STRING);

            StringFilterPredicate predicate = new StringFilterPredicate();
            predicate.setOperation(operation);
            predicate.setValue(new FilterPredicateValue<>("-")); //uuid中有-
            keyFilter.setPredicate(predicate);

            keyFilters.add(keyFilter);
```

**Environment**

 * OS:  macos and linux
 * ThingsBoard: 3.4.2
 * Browser: name and version

**Comment by devaskim** [comment]
It is not what you actually asked, but I solved this case with catching ENTITY_CREATED event in rule chains and setting needed (server) attributes with some default values to those newly created entities.

**Comment by lincoln310** [comment]
> It is not what you actually asked, but I solved this case with catching ENTITY_CREATED event in rule chains and setting needed (server) attributes with some default values to those newly created entities.

Me too!

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
