### ISSUE TITLE
Thingsboard Cassandra backup

### ISSUE THREAD

**Issue by Tiricz** [thingsboard/thingsboard#1036]
Hi,
I would like to make backup of Thingsboard server. Could you please help me with some suggestions?

Thank you in advance!

**Comment by gopirathnamt** [comment]
hi , i will help you .
Which database u are using now ?

**Comment by Tiricz** [comment]
Hi, thank you for helping,
I am using cassandra database. Backup must be created with cassandra.
I'm using a version of Thingsboard 2.0.3 cassandra version

**Comment by gopirathnamt** [comment]
i replied on ur other comment

**Comment by Tiricz** [comment]
Thanks, I will try it. If I have any question, I will let you know.
