### ISSUE TITLE
Unable to export dashboard on thingsboard cloud - Getting timed out

### ISSUE THREAD

**Issue by digikloud** [thingsboard/thingsboard#10360]
**Describe the bug**
When user tries to download/export the dashboard as pdf/other file format, thingsboard unable to export and throws Timed out error as shown below

![image](https://github.com/thingsboard/thingsboard/assets/118111106/26b0ff11-b17e-44c8-a13d-306856227c96)

![image](https://github.com/thingsboard/thingsboard/assets/118111106/0a29084c-4ee0-4bd0-a1d1-11f275408443)

Thingsboard Cloud Version  v.3.6.2.3PAAS

**Comment by ViacheslavKlimov** [comment]
Hi @digikloud,

Thanks for reporting this.
We are aware of the issue with reports, and are working to fix it.

**Comment by trikimiki** [comment]
That was a timely issue related to Web Report API problems.
Thank you for your concern!
