### ISSUE TITLE
always be 'out of sync' in using a gateway

### ISSUE THREAD

**Issue by FeiH36** [thingsboard/thingsboard#10378]
**Description**
I tried to use a gateway according to the steps in https://thingsboard.io/docs/iot-gateway/getting-started/. 
The status of the gateway is active. However, the status of a connector always be 'out of sync' no matter if I enable the connector. 
Additionally, the mqtt broker works well as the public messages can be received correctly by a mqtt tool

**Environment**
 * OS:  ubuntu v20.
 * ThingsBoard: v3.6.2
 * thingsboard_gateway: v3.4.5
 * Browser: chrome

**Comment by Ultrazombie** [comment]
Hello @FeiH36,
Please use the gateway issue page for gateway issues.

https://github.com/thingsboard/thingsboard-gateway/issues
