### ISSUE TITLE
Unable to add new widget type 

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1037]
I am using thingsboard 2.0.4 . 
When i try to add new widget type to widget Bundlle . 
It show widget type such as Timeseries , Latest Values ,Control Widget ,Alarm widget and static widget . 
But when i click any Widget type . It wont add it . It is still empty .
I dont know why ?

**Comment by vparomskiy** [comment]
I've verified this scenario on the latest version and it works as expected. I can add any widget type to the new widget bundle.

Please check the browser console for warnings/errors after widget type is selected. And add them to this issue.

**Comment by Tiricz** [comment]
Hi, thank you for helping,
the Thingsboard uses a cassandra database. Backup must be created with cassandra.
I'm using a version of Thingsboard 2.0.3

**Comment by gopirathnamt** [comment]
yeah i check with latest version , it works fine .
But i dont know ,what is the issue in old version . 
Anyways it works fine , ok
