### ISSUE TITLE
How to mqtt device provisioning is gateway?

### ISSUE THREAD

**Issue by sirapol** [thingsboard/thingsboard#10372]
Device Provisioning

 * Generic

**Description**
I working about ESP32 for gateway.
I know how to provisioning device.
But, How to provisioning device is gateway ?

**Comment by myroslav-tb** [comment]
Hi @sirapol, there is no option to provision the device as a gateway. I have created a feature request for our prod team. Once they review it, we’ll post an update on when this feature could be delivered if they decide to add it to the product.

Best regards,
Myrosalv

**Comment by myroslav-tb** [comment]
Hi @sirapol, our team is planning to add this feature in version 3.7.1.
