### ISSUE TITLE
Link to dashboard state

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10373]
I would like to create link to certain dashboard state so the user can scan a qr code on an asset and visit the dashboard state with the entity equals to that asset.

How can I do that and ask for login data?

**Comment by devaskim** [comment]
Open this dashboard yourself when you are logged in, copy url from browser and encode it in QR code.

[Here is how TB widget forms](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1404) dashboard links with specific entity in state.

**Comment by gcorthey** [comment]
Excelent thanks !
