### ISSUE TITLE
relationType  HELP

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/thingsboard#10371]
Can the relationType output of the rule nodes be used to perform analysis within the next node? Type: metadata or msg

**Comment by liotys** [comment]
Hi, how is your relationType defined. With a switch node or just success/failure/true/false?

**Comment by ssakharova** [comment]
Hello @ezeroldan24,

You can try to explore the switch rule node and try to use it in your rule chain logic. The output connection of the rule node corresponds to the result of the script execution. Then, you can use the transformation script rule node to perform analysis and some calculations.

Here you can find more information regarding these nodes:

- Switch rule node - https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/filter-nodes/#switch-node
- Transformation script rule node - https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node
