### ISSUE TITLE
Open another Dashboard in Custom Widget

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10391]
Hello!
Is there a way to open/redirect to a new dashboard using a custom widget or an custom action?
I found this but did not help me much [Link](https://github.com/thingsboard/thingsboard/issues/2693)

The idea is to have a side bar menu (custom widget) in the application and this will be in different dashboards... so I have to redirect to the dashboard which already has these states when the user clicks in them. But is a new dashboard, not the same.

In addition to that, and if possible, redirect to a specific STATE, i do not want to use location.href as it is a pretty slower.

![image](https://github.com/thingsboard/thingsboard/assets/98624393/a13edae6-aa08-49c5-ad69-af51ed1d5f0d)

Thanks!

**Comment by devaskim** [comment]
Take a look how this is done in TB widgets https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1070

**Comment by ezeroldan24** [comment]
<button mat-menu-item id="alarms" (click)="ctx.actionsApi.elementClick($event)">
Use this, and then in the widget action, put the assigned ID and navigate according to the action you need.

**Comment by nicovon24** [comment]
No Eze, Not the way i want to implement it. It is not the idea to use actions, i want it using code for example a method or a function and navigate to other dashboard.
Deva, tried a lot but did not work, not sure if you have tried this solution before.
Thanks and waiting for new responses

**Comment by devaskim** [comment]
> not sure if you have tried this solution before.

@nicovon24  Don't blame someone (especially contributor ;) ) when you failed on your own. Good luck!..

**Comment by nicovon24** [comment]
Sure! The message was not clear i think and then I did not respond the best way reading again the response, thanks anyway and hope you have a fine start of the week!
