### ISSUE TITLE
How to Save Entity Timeseries at Specific Timestamp and Update Value Using Widgets

### ISSUE THREAD

**Issue by samarth20131** [thingsboard/thingsboard#10409]
**Description**
I'm currently working on a project where I need to save entity timeseries data at specific timestamps and update the value whenever needed. 

**Objective**
1. Save entity timeseries data at a specific timestamp.
2. Update the value of this timeseries data using ThingsBoard widgets.

**Questions**

1. How can I save entity timeseries data at a specific timestamp using ThingsBoard widgets?
2. Once the data is saved, how can I update its value using widgets?
3. Are there any specific widgets or configurations that I should be using to achieve this functionality?

saveEntityTimeseries
 
I have used this code snippet in thingsboard widget to save telemetry , but i am unable to save it at specific timestamp
![Screenshot from 2024-03-21 15-39-22](https://github.com/thingsboard/thingsboard/assets/110403688/97175b6c-16e4-486e-b250-80e078e174d9)

This screentshot is of swagger-ui api which is used to save and update telemetry at specific timestamp
![Screenshot from 2024-03-21 15-29-42](https://github.com/thingsboard/thingsboard/assets/110403688/c0b3392c-5c73-4d77-af5c-ccdada681164)

https://github.com/thingsboard/thingsboard/blob/acabcb8462ee7843b10efc51073c7877572bc9b3/ui-ngx/src/app/core/http/attribute.service.ts#L108

**Comment by devaskim** [comment]
Seems like you need to create your own implementation of `saveEntityTimeseries` that will consider custom time stamp, I mean, copy existing implementation of `saveEntityTimeseries` to your widget or action and add time stamp according to example from swagger-ui

**Comment by sumin-denys** [comment]
Hi @samarth20131,

Answering your questions:
1. You need to develop your custom widget in order to save timeseries data for specific **TimeStamp** since ThingsBoard doesn't have such a possibility out of the box. I removed the basic implementation of **SaveEntityTimeseries** function and added the following code:
```
function saveEntityTimeseries(entityType, entityId, telemetries) {
    var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';
    return http.post(url, telemetries);
}
```
Also, you need to change the call of this function inside the **updateAttribute** function to the following:
```
let observable = saveEntityTimeseries(
datasource.entityType,
datasource.entityId,
$scope.attributeUpdateFormGroup.get('currentValue').value
);
```
2. You can use the same widget for this purpose, but to save/update values of timeseries for specific **TimeStamp**, you need to use the following `{"ts":SpecificTS,"ValuesToUpdate":{"key":value, "key":value}}` string example. Below is a screenshot of my test.
![image](https://github.com/user-attachments/assets/ed00bca2-7691-403b-ac79-b7de175167a7)

3. I attached the widget to this comment, which may help you with this.
[update_time_series_with_specific_ts.json](https://github.com/user-attachments/files/17737985/update_time_series_with_specific_ts.json)

**Comment by sumin-denys** [comment]
Hi @samarth20131,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.

**Comment by icoco** [comment]
no way to UPDATE ?  looks only CREATE timeseries data

**Comment by icoco** [comment]
use widget 'Timeseries table', try to implement the Update timeseries data feature with Custom Action, but confuse with the service HTTP, it does not work , it not execute post request, not sure the reason .

```

let http = $injector.get(widgetContext.servicesMap.get('http'));
 
   
...


    function saveEntityTimeseries(entityType, entityId, telemetries) {

        var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';

        return http.post(url, telemetries);

    }
...

then call it : 

saveEntityTimeseries('DEVICE', 'IDxxxx', data)


```

although the post step executed, not not invoke the Request at all, what  reason  make it not call ?

**Comment by icoco** [comment]
> Hi [@samarth20131](https://github.com/samarth20131),
> 
> Answering your questions:
> 
> 1. You need to develop your custom widget in order to save timeseries data for specific **TimeStamp** since ThingsBoard doesn't have such a possibility out of the box. I removed the basic implementation of **SaveEntityTimeseries** function and added the following code:
> 
> ```
> function saveEntityTimeseries(entityType, entityId, telemetries) {
>     var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';
>     return http.post(url, telemetries);
> }
> ```
> 
> Also, you need to change the call of this function inside the **updateAttribute** function to the following:
> 
> ```
> let observable = saveEntityTimeseries(
> datasource.entityType,
> datasource.entityId,
> $scope.attributeUpdateFormGroup.get('currentValue').value
> );
> ```
> 
> 2. You can use the same widget for this purpose, but to save/update values of timeseries for specific **TimeStamp**, you need to use the following `{"ts":SpecificTS,"ValuesToUpdate":{"key":value, "key":value}}` string example. Below is a screenshot of my test.
>    ![image](https://github.com/user-attachments/assets/ed00bca2-7691-403b-ac79-b7de175167a7)
> 3. I attached the widget to this comment, which may help you with this.
>    [update_time_series_with_specific_ts.json](https://github.com/user-attachments/files/17737985/update_time_series_with_specific_ts.json)


try to use the http post way, but seem it does not work in custom action of Timeseries table widget  ( official native ) 

```
  var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';

   http.post(url, telemetriesData);


``
above code executed but not make http request to server , not sure which step wrong .
