### ISSUE TITLE
Dashboard Layout Changes Break Widget Coordinates - Widget get overlapped or out of view

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#10403]
**Describe the bug**
In some Dashboards changing the general layout settings of the Dashboard leads to breaking the widget coordinates. So Widgets receive negative positions or are overlapped by other widgets. The Dashboards only use default widgets (no custom ones). And the behavior is not witnessed for every single dashboard on the TB instance. But we didn't identify any pattern for that, yet.

**Your Server Environment**
* own setup
  * Deployment: microservices
  * k8s (Azure AKS)
  * ThingsBoard Version 3.6.2 PE
  * Professional Edition

**To Reproduce**
1. Open Dashboard in Edit Mode
2. Change Layout Settings of the Dashboard State (e.g. Background Color, Column Counter or Background Image)
3. Apply Changes
4. See error in the positioning of Widgets (some Widgets get lost (negative coordinates) or overlapped by other widgets

![CPT2403201039-900x439](https://github.com/thingsboard/thingsboard/assets/25298332/2bdd3df8-b39d-4de4-8e3d-f4e08f8e9754)

**Expected behavior**
Changes of the Layout shouldn't affect the widgets like that. All widgets have to be still visible after all.

**Screenshots**
Version Control diffs (left original, right after layout changes):

Widget coordinates:
![Layout_Changes](https://github.com/thingsboard/thingsboard/assets/25298332/8b8883d9-eedf-48c7-9934-aa5f3d1a3513)

ExternalID is null:
![ExternalId_Changes](https://github.com/thingsboard/thingsboard/assets/25298332/a685577a-b904-4f98-8c40-4c9c55b9f2a1)

**Comment by AlexDoanTB** [comment]
@mde2017 this is not the 3.6.2 PE definitely. It is v3.61 or below. 
Secondly, it seems like you had issues with the upgrade, as the issue is not reproducible on 3.6.1, 3.6.2, and 3.6.3. 
How do you know if someone is not restoring the version or has the same dashboard in Edit mode during the reconfiguration?

**Comment by mde2017** [comment]
@AlexDoanTB 
It is 3.6.2, here is a video as proof. We were also able to reproduce the error when creating a new widget in the video.
Furthermore we can ensure that no one else was editing the dashboard at the same time.

https://github.com/thingsboard/thingsboard/assets/25298332/4abd06ad-0c20-4915-938c-3d4a4eed02e6

**Comment by AlexDoanTB** [comment]
@mde2017 now I got your point. The above descriptions were loose. Now, it is clear. You are not saving widget changes (resize) once they are done. The Dashboard settings have higher priority, so the unsaved adjustments for widgets get lost. Imagine a workboard that you prepare for work and then create your art on it. The flow should not be upside down. You can add a prod request to retain lower-level configurations before the global setting is done, but I suspect the ticket may not pass validation.
