### ISSUE TITLE
not updating role permission for autogenerated role "customer users" in Sub-Customer User groups

### ISSUE THREAD

**Issue by Mike2912** [thingsboard/thingsboard#10402]
**Describe the bug**
If I change the definition of the autogenerated role "customer users", it's not updating role permissions in Sub-Customer User groups.
It is updating in Customer User groups and it also updates my own role, if it is assigned to a Sub-Customer User group.

**Your Server Environment**
* own setup
  * Deployment type: deb in Azure VM
  * ThingsBoard Version 3.6.1
  * Professional Edition

**To Reproduce**
1. Go to 'Security -> Roles'
2. Click on 'Custom User -> Edit'
3. Change permissions
4. Go to 'Customer -> Hierarchie -> All -> "CustomerA" -> Customer groups -> All -> "Sub-CustomerAA" -> User Groups -> Customer Users -> Edit'
5. Click on 'Roles' and than the '...' (View Role) in row 'Customer User'
6. The Permissions you see are the original ones, the changes you made before are not displayed here

**Expected behavior**
The Permissions should be the updated one from the role

**Screenshots**
New role permissions in role config:
![grafik](https://github.com/thingsboard/thingsboard/assets/55746431/d18c49c0-7d3d-427a-b988-585491126778)

Unchanged role permissions in Sub-customer User groups
![grafik](https://github.com/thingsboard/thingsboard/assets/55746431/975df9c7-3270-411a-ba90-0c8ba5361c6b)

**Comment by mykhailokornieiev** [comment]
Hi. I was able to reproduce such behavior. It looks like a bug in a platform, so I've added this a ticket to our backlog (PROD-3566) for our developers to review and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in subsequent releases.
To avoid it you can assign another role to this "Customer users" user group and then re-assign autogenerated "Customer user" again. After it all changes will be displayed immediately (tested on 3.6.4 PE)

**Comment by mykhailokornieiev** [comment]
Hi. Developers have reviewed this behavior and concluded that it is by design of Thingsboard, and there are no plans to change it. In this case, I close ticket this ticket.
