### ISSUE TITLE
RPC requests for LwM2M device in queue mode should be queued

### ISSUE THREAD

**Issue by Rhyaldir** [thingsboard/thingsboard#10400]
**The problem**
A LwM2M device can (at registration) report that it is using queue mode. In this mode, the device is not always connected and might even disconnect for the network for long periods of time. It is not uncommon to have devices which are online only ten seconds every hour for instance to safe power.
In those cases it is not possible to send RPC request to the device as those requests are not queued, but executed immediately; which will most likely result in a timeout.

**The solution**
RPC requests for LwM2M devices in queue mode should be queued until the next communication attempt of the device (commonly a registration update or sending some data). When a communication attempt occurs the rpc request should be executed on the device.

**Alternatives**
I have been looking at using the rules engine to implement this, but without success.

**Comment by epalchenko** [comment]
Hello @Rhyaldir,
Queue mode is implemented as Persistent RPC. 
Please familiarise yourself with the following: https://thingsboard.io/docs/pe/user-guide/rpc/#persistent-rpc
