### ISSUE TITLE
Why is msg and metadata object parsing different in rule chains?, cant use ${urls.url} in api call

### ISSUE THREAD

**Issue by Philip2809** [thingsboard/thingsboard#10415]
**Component**
 * Rule Engine

**Description**
Why is msg and metadata object parsing different in rule chains?
![image](https://github.com/thingsboard/thingsboard/assets/51290462/5dbce144-c1f9-4562-8277-442c440d0c6d)
Using TBEL

My problem with this:
I cant use ${urls.test} in my rest api call

**Environment**
 * ThingsBoard: 3.6.2

**Comment by devaskim** [comment]
It is a limitation of the platform: all fields in metadata are strings

**Comment by Philip2809** [comment]
Ahh that explains it, thanks!
