### ISSUE TITLE
Allowing White-Labeling Across Customer Hierarchy with Sub-Customers

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#10411]
**Component**

 * UI
 * Generic

**Description**
The white labeling permission function only works at the first customer level. If you enable the option for the first customer below the tenant level, all other customers below this level also have the option to configure their page. Disabling the function then no longer works at the second customer level. Thingsboard always takes the configuration of the first customer level and does not accept any changes elsewhere.
Likewise - it makes more or less sense, or the case is unlikely, but still possible - you cannot give the customer on the second level approval if the customer on the first level does not have this approval.

Is this a bug or is it intentionally implemented this way?

Translated with DeepL.com (free version)
**Environment**
 * ThingsBoard: 3.6.3 PE

**Comment by ssakharova** [comment]
Hello @mde2017,

This behavior is intentionally implemented this way.
