### ISSUE TITLE
Cell content function in entities table: how to get the latest timestamp of a selected key (telemetry/attribute).

### ISSUE THREAD

**Issue by masao-sakai-b5** [thingsboard/thingsboard#10428]
In entities table, I can get the timestamp information of a selected key (telemetry/attribute) with '**time**' and '**timePrev**' in 'data post-processing function'.

![image](https://github.com/thingsboard/thingsboard/assets/114979918/99cdda99-b35a-421f-8cdb-fbf3b03c9d3f)

However, I can not use the '**time**' and '**timePrev**' in "cell style function" and "cell contetn function".

![image](https://github.com/thingsboard/thingsboard/assets/114979918/f06bb074-475c-4217-ae8d-9d9e5d93f6fd)

How can I get  the timestamp information of a selected key?

**Comment by liotys** [comment]
Hi,
you should have a look to ctx.data. Browse the array to find the right line and the right field (i). So the timestamp should be ctx.data[i].data[0].

**Comment by masao-sakai-b5** [comment]
Dear liotys.

Thank you very much for your useful advice.

With the following code, I was able to get all elements with timestamps in the table.

```
let ObjectKeysLength = Object.keys(ctx.data).length;
var ctxDatas = "";
let index = 0;

while(true){
   ctxDatas=ctxDatas + "," + ctx.data[index].data[0];
   if( index >= ObjectKeysLength -1 ){
      break;
   }
   index++;
}
return ctxDatas;

```

By applying this, my problem was solved.

**Comment by masao-sakai-b5** [comment]
Hello @Ultrazombie 
Thanks for your advice.
Close this topic.
