### ISSUE TITLE
ReferenceError: "btoa" is not defined at line number X

### ISSUE THREAD

**Issue by hophead12** [thingsboard/thingsboard#10421]
Hi Thingsboard Team,

I hope you can assist me with my issue. I'm encountering a problem while attempting to use the btoa() function in a script Rule within Thingsboard PE on Ubuntu. Specifically, I'm receiving the following error message:

```
org.thingsboard.script.api.TbScriptException: javax.script.ScriptException: ReferenceError: "btoa" is not defined at line number X
```
This situation is puzzling to me because everything worked fine on the development version installed in Docker. It's possible that I overlooked something, but it appears to me that this could be a service error.

I would greatly appreciate your response.

**Comment by liotys** [comment]
Hi,
you have to use TBEL instead of Javascript to use btoa.
