### ISSUE TITLE
thingsboard service is not recognized by windows 10

### ISSUE THREAD

**Issue by FactorYang** [thingsboard/thingsboard#1042]
I installed it successfully on windows 10, but when execute "net start thingsboard", the service is not recognized by windows.

So i try to uninstall/reinstall, but showed the following failure info. 

![image](https://user-images.githubusercontent.com/15258174/44771090-994cdf80-ab9c-11e8-8a16-9d5e8d8593e6.png)
![image](https://user-images.githubusercontent.com/15258174/44771186-df09a800-ab9c-11e8-9f75-978d61666db8.png)

**Comment by FactorYang** [comment]
BTW, the install log could see here.
[install.log](https://github.com/thingsboard/thingsboard/files/2331119/install.log)

**Comment by mp-loki** [comment]
looks like you have run the installation script twice for whatever reason. try cleaning up the database and re-run the script again

**Comment by FactorYang** [comment]
@mp-loki  hi, thanks for your helping last time.

I deleted the folder and try again from very start, it installed successfully, but when I using "net start thingsboard", the following error occurs.
![image](https://user-images.githubusercontent.com/15258174/44837921-7b9b7b00-ac6d-11e8-9f9e-2393fcc3584e.png)

![image](https://user-images.githubusercontent.com/15258174/44837938-881fd380-ac6d-11e8-896c-26f2969a16a6.png)

**Comment by mp-loki** [comment]
any logs in <THINGSBOARD_INSTALL _DIR>/logs?

Btw, did you run install.bat as Administrator?

**Comment by FactorYang** [comment]
@mp-loki yep, i run with administrator, the log could see below.

[install.log](https://github.com/thingsboard/thingsboard/files/2335688/install.log)

**Comment by mp-loki** [comment]
Is there a thingsboard.log? 

Also, system error 1067 may be a Windows malfunction. I found this topic [here](https://www.drivereasy.com/knowledge/solved-error-1067-process-terminated-unexpectedly-windows-10-7-8/), but I cannot promise that this will work. If it does not, I would suggest you delete a wondows service, clean up database and run installation again.

**Comment by FactorYang** [comment]
@mp-loki all logs could see here.
[thingsboard.err.log](https://github.com/thingsboard/thingsboard/files/2335793/thingsboard.err.log)


[thingsboard.wrapper.log](https://github.com/thingsboard/thingsboard/files/2335794/thingsboard.wrapper.log)

**Comment by FactorYang** [comment]
@mp-loki the other two logs are empty.

**Comment by FactorYang** [comment]
@mp-loki btw, when i open the registry editor to remove the service, i found there is no service named thingsboard, but in the windows management panel, it exits. 
![image](https://user-images.githubusercontent.com/15258174/44846952-84e41200-ac84-11e8-96d3-93eb88a7661a.png)
![image](https://user-images.githubusercontent.com/15258174/44846960-8a415c80-ac84-11e8-857e-fb75e92c0c69.png)

**Comment by mp-loki** [comment]
Please see this issue:
https://github.com/thingsboard/thingsboard/issues/883
but in your case you have to edit thingsboard.xml instead of thingboard.conf

**Comment by FactorYang** [comment]
@mp-loki I add the required line in #883 at the bottom of thingboard.xml, and re-install again (delete original files and copy new downloaded + the new thingboard.xml), and found install process failed. 

![image](https://user-images.githubusercontent.com/15258174/44890067-404f8980-ad0b-11e8-864f-ab7543db4442.png)
![image](https://user-images.githubusercontent.com/15258174/44890074-4a718800-ad0b-11e8-9240-7203217cdcf0.png)
