### ISSUE TITLE
Substitutes for the deprecated widgets

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#10426]
**Component**

 * UI

**Description**
Are there any substitutes for the deprecated widgets? I need some widget to change shared attributes.

![image](https://github.com/thingsboard/thingsboard/assets/7483656/4f034fe5-a06c-4900-881f-597db792fdfe)

**Environment**

 * ThingsBoard: Cloud Prototype

**Comment by mde2017** [comment]
Hi @lstarke,

you can use the **Update Multiple Attributes** Widget instead:

![image](https://github.com/thingsboard/thingsboard/assets/25298332/fd5c5e76-d59c-4b1c-8018-868f759bcb93)

In the **Advanced Data Key Configuration** you can select the desired Datakey Type or Value:

![image](https://github.com/thingsboard/thingsboard/assets/25298332/4f50d38e-e64e-4ee2-92ae-2f7c0ddc4a04)

![image](https://github.com/thingsboard/thingsboard/assets/25298332/2f18d7d5-7edc-45a3-b563-2530257bce76)

**Comment by lstarke** [comment]
Thanks @mde2017

**Comment by Ultrazombie** [comment]
Hello @lstarke 
Do you still have any questions about the topic, or can we close this?

**Comment by lstarke** [comment]
> Hello @lstarke Do you still have any questions about the topic, or can we close this?

You can close it. Thank you.
