### ISSUE TITLE
Draggable marker not working in Maps

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10438]
Hello! the draggable marker button is not working currently after updating thingsboard server to last release.

I used to click to this button and adding assets locations, customer locations into an Openstreet Map or an Image Map... now in both, the marker is not working.

The other buttons are working, but this one not executes nothing, neither opens the popup when there are two or more entities available.

Please help, that my app uses very much this

![image](https://github.com/thingsboard/thingsboard/assets/98624393/5517809d-d94f-427f-85b8-1e2881b1f325)

**Comment by vvlladd28** [comment]
Thank you for bringing this issue to our attention! 
We have addressed it, and the changes can be found in the following Pull Request: https://github.com/thingsboard/thingsboard/pull/10446. Please review it, and if you have any questions or comments, do not hesitate to let us know.
Thank you once again for your contribution!

**Comment by vvlladd28** [comment]
Hi @nicovon24 
This fix is already available on the [thingsboard.cloud](https://thingsboard.cloud/) and will be added to the 3.7 TB release

**Comment by Sylphe88** [comment]
Hey @vvlladd28, thanks for the quick fix. Would you have a timeframe for the 3.7 release? We're quite stuck with manual xPos/yPos attribute definitions for now :)

**Comment by Ultrazombie** [comment]
Hello @Sylphe88,
3.7 should be out this month.
