### ISSUE TITLE
TBEL docs says "inline" but works with multiline?

### ISSUE THREAD

**Issue by Philip2809** [thingsboard/thingsboard#10434]
**Component**
 * UI
 * Rule Engine

**Description**
The thingsboard TBEL docs says:
"TBEL allows you to create Lists. We use our own implementation of the List to control memory usage of the script. That is why TBEL allows only inline creation of lists. For example:" at https://thingsboard.io/docs/user-guide/tbel/#lists

But I can create a list like this as well?
![image](https://github.com/thingsboard/thingsboard/assets/51290462/b896f241-971f-4f10-9287-5166521be7c4)

And it seams to work just fine?

**Environment**
 * ThingsBoard: 3.6.3

**Comment by devaskim** [comment]
It is about inline initialization, not about code formatting.
