### ISSUE TITLE
Browse from gallery - can't select images

### ISSUE THREAD

**Issue by michalpankau** [thingsboard/thingsboard#10445]
**Describe the bug**
Recently I wanted to add new image to marker images list from Browse from gallery, but selection window does not popup.
I have checked this on Chrome/Edge. Chrome mobile, always same result, small balloon... Any clue ?

**Your Server Environment**
https://thingsboard.cloud

** images **
Screen shot from browser
![browse_from_gallery_error](https://github.com/thingsboard/thingsboard/assets/45353572/933ac0fd-2be9-4cfd-ace4-26831bf3155f)

**Comment by michalpankau** [comment]
After clearing cache still not possible to select image, but if I disable 'Use marker image function' then I can browse from gallery.

**Comment by vvlladd28** [comment]
Thank you for bringing this issue to our attention!
We have addressed it, and the changes can be found in the following Pull Request: https://github.com/thingsboard/thingsboard/pull/10449. Please review it, and if you have any questions or comments, do not hesitate to let us know.
Thank you once again for your contribution!

**Comment by michalpankau** [comment]
I assume it is fixed now, when it will be hotfixed on cloud ?

**Comment by ezeroldan24** [comment]
Good morning, in the cloud it keeps failing.
![error](https://github.com/thingsboard/thingsboard/assets/91096768/4f51bf5f-52a0-4eed-af8f-785b206b0386)

**Comment by BiggiePete** [comment]
The issue also exists in Thingboard 3.6.3PE

**Comment by vvlladd28** [comment]
Hi @michalpankau 
This fix is already available on the [thingsboard.cloud](https://thingsboard.cloud/) and will be added to the 3.7 TB release

**Comment by KamranArain** [comment]
Hello, 
I am new to the thingsboard infrastructure, I have deployed PE edition on self-maintained cloud, I have the same issue how can I hotfix this?

**Comment by Ultrazombie** [comment]
Hello @KamranArain 
This issue will be fixed in the 3.7 version,
Please wait for the 3.7 release and update your ThingsBoard service.
