### ISSUE TITLE
How to associate the perpetual license to a new instance

### ISSUE THREAD

**Issue by tanyongnan1992** [thingsboard/thingsboard#10448]
**Component**

 * Generic

**Description**
I had a Thingsboard PE with perpetual license. Today, something wrong happened on the VM instance.
Finally, I had to shut the VM down and launched a new VM instance with the backup data of old VM.
* Meanwhile, I deactivated the old instance ID in Thingsboard license portal and deleted it. The license portal also showed 0/1 for the instance.
<img width="1165" alt="image" src="https://github.com/thingsboard/thingsboard/assets/68315166/3cb7c70f-d877-4cb3-89b9-69195b7f02c4">

However, when I start the Thingsboard in the new VM using the perpetual license, Thingsboard log stated "Instance not found".
If this perpetual license can associate to my new instance? If not, the license will be wasted.

Looking for your support and thank you so much!

**Environment**
 * OS:  Ubuntu 18.04 LTE
 * ThingsBoard: 3.2.2PE
 * Browser: Chrome

**Comment by Backdraft007** [comment]
You have to remove 
`/usr/share/thingsboard/bin/instance-license.data` (Make backup of the file)
and start thingsboard again.

**Comment by tanyongnan1992** [comment]
> You have to remove `/usr/share/thingsboard/bin/instance-license.data` (Make backup of the file) and start thingsboard again.

@Backdraft007 It works~ Thank you so much!
