### ISSUE TITLE
How to using control widget to send mqtt rpc request to device which in most of time is powered off.

### ISSUE THREAD

**Issue by friedrich86** [thingsboard/thingsboard#10444]
**Component**
Control widget slide toggle control

 * Generic

**Description**
question: Our devices are  wireless sensors which in most of time are powered off and offline. When using control widgets to send mqtt rpc request to devices, we expect that when device is power on and connect to mqtt netty broker, sensor will get corresponding rpc request. in thingsboard doc page: https://thingsboard.io/docs/user-guide/rpc/#persistent-rpc  it also writes that rpc has persistent capability, but even I enable persistent in slide toggle control or other control widget, ONLY receive mqtt message when device connects to broker. 

**Environment**

 * OS:  ubuntu 22.04 LTS
 * ThingsBoard: version 3.6.2
 * Browser: Google Chrome version 123.0.6312.58 64 bit

Thanks to any reply.

BR~

**Comment by myroslav-tb** [comment]
Hi @friedrich86, try to increase the timeout of the RPC request.

![image](https://github.com/thingsboard/thingsboard/assets/158559147/2fc6a02e-2096-4bac-983e-1495520c797a)
Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
