### ISSUE TITLE
Add "Disable data hiding" in new ECharts

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#10450]
In old timeseries charts I could disable datahiding for each data key.
![Screenshot 2024-03-26 150929](https://github.com/thingsboard/thingsboard/assets/8741669/120ea8f7-b01c-4b3a-a724-ee55b6dd187a)
In new charts it is not possible.

Would be nice to add this feature to new ECharts, too.

**Comment by ezeroldan24** [comment]
@Backdraft007 How are you? Do you have an idea how to use the Echarts from the official website on thingsboard? Is it simple?

**Comment by Backdraft007** [comment]
Hey @ezeroldan24  I'm fine thanks. :) And you?
No, I'm not so deep in the development of custom widgets.
But the new charts based on the Apache Echarts (since version 3.6.3 of TB).

**Comment by ezeroldan24** [comment]
Very good luckily. Working as usual haha. Yes, I saw the new widgets were very interesting, but I also saw that there are a lot of them on the echarts page. There was a simple way to implement it. Thank you for your reply!

**Comment by devaskim** [comment]
@ezeroldan24 Look at [this official example](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#using-external-javascript-library) how to use external JS library.

You get use [Echarts from jsDelivr CDN](https://www.jsdelivr.com/package/npm/echarts)

**Comment by ezeroldan24** [comment]
As soon as I can I'll review it, thanks for your help @devaskim ! Greetings have a good day
