### ISSUE TITLE
disable receiving device data 

### ISSUE THREAD

**Issue by RG176** [thingsboard/thingsboard#1045]
I want to disable the receiving of data for a defined time.
Therefore I want to send a timestamp to TB, which shall be used as the time until receiving shall be disabled.
I am currently thinking about creating a rule chain, but don´t know how to create it best.
How to access in rule chain any latest telemetry or alarm data of the device?
What is the best way for a disable function with rule chain?

Thank you for your support.

**Comment by vparomskiy** [comment]
You can use this node for fetching the latest telemetry or attribute of the device.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-fields

Flow is simple: when telemetry uploaded, you check current system timestamp with the latest value. If current time-window is disabled - do not send a message to the 'save telemetry' node.
