### ISSUE TITLE
Cannot edit or mapping thingsboard.yml

### ISSUE THREAD

**Issue by Tertoey** [thingsboard/thingsboard#10463]
**Component**

 * Installation

**Description**
I want to add azure ad and google login by oauth 
https://thingsboard.io/docs/user-guide/oauth-2-support/ (i follow this guide but google login button not show)
https://thingsboard.io/docs/user-guide/oauth/azure/

i think it because in  thingsboard.yml no this section. button not show
https://thingsboard.io/docs/user-guide/oauth/azure/#result

first i create thingsboard.yml in my computer and mapping  thingsboard.yml
- ./thingsboard/thingsboard.yml:/usr/share/thingsboard/conf/thingsboard.yml in volume

thingsboard-mytb-1       | ***************************
thingsboard-mytb-1       | APPLICATION FAILED TO START
thingsboard-mytb-1       | ***************************
thingsboard-mytb-1       |
thingsboard-mytb-1       | Description:
thingsboard-mytb-1       |
thingsboard-mytb-1       | The dependencies of some of the beans in the application context form a cycle:
thingsboard-mytb-1       |
thingsboard-mytb-1       |    tomcatServletWebServerFactory defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]  
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    httpTransportContext (field protected org.thingsboard.server.common.transport.TransportService org.thingsboard.server.common.transport.TransportContext.transportService)    
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    defaultTransportService defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/transport-api-3.6.3.jar!/org/thingsboard/server/common/transport/service/DefaultTransportService.class]
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    hashPartitionService defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-3.6.3.jar!/org/thingsboard/server/queue/discovery/HashPartitionService.class]
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    defaultTenantRoutingInfoService defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/queue/DefaultTenantRoutingInfoService.class]
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    defaultTbTenantProfileCache defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/dao-3.6.3.jar!/org/thingsboard/server/dao/tenant/DefaultTbTenantProfileCache.class]
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    TenantDaoService (field private org.thingsboard.server.dao.customer.CustomerService org.thingsboard.server.dao.tenant.TenantServiceImpl.customerService)
thingsboard-mytb-1       |       ↓
thingsboard-mytb-1       |    CustomerDaoService (field private org.thingsboard.server.dao.asset.AssetService org.thingsboard.server.dao.customer.CustomerServiceImpl.assetService)
thingsboard-mytb-1       | ┌─────┐
thingsboard-mytb-1       | |  AssetDaoService (field private org.thingsboard.server.dao.asset.AssetProfileService org.thingsboard.server.dao.asset.BaseAssetService.assetProfileService)
thingsboard-mytb-1       | ↑     ↓
thingsboard-mytb-1       | |  AssetProfileDaoService (field private org.thingsboard.server.dao.asset.AssetService org.thingsboard.server.dao.asset.AssetProfileServiceImpl.assetService)
thingsboard-mytb-1       | └─────┘
thingsboard-mytb-1       |
thingsboard-mytb-1       |
thingsboard-mytb-1       | Action:
thingsboard-mytb-1       |
thingsboard-mytb-1       | Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

but i can mapping file if i change to
- ./thingsboard/thingsboard.yml:/usr/share/thingsboard/conf/thingsboard1.yml

i try to add
spring.main.allow-circular-references: true in environment (https://thingsboard.io/docs/user-guide/install/config/#general-spring-parameters  spring.main.allow-circular-references no Environment)

but found this error
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'transport.http.max_request_timeout' in value "${transport.http.max_request_timeout}"

i add HTTP_MAX_REQUEST_TIMEOUT:  300000 show the same error so i change to transport.http.max_request_timeout: 300000 and found a new error again

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'edges.enabled' in value "${edges.enabled}"

**Environment**

 * OS:  windows 11
 * ThingsBoard: image: "thingsboard/tb-postgres:latest"
 * Browser: google chrome

**Comment by mykhailokornieiev** [comment]
Hi. 

This part of the documentation is outdated. Currently, all of these settings are transferred on the UI side. 
It will be better to get familiar with the “Configuration on Thingsboard“ articles in this documentation https://thingsboard.io/docs/pe/user-guide/oauth-2-support/#configuration-of-thingsboard

For Azure AD, you can get familiar with this comment: https://github.com/thingsboard/thingsboard/issues/10143#issuecomment-1948198924
