### ISSUE TITLE
ub

### ISSUE THREAD

**Issue by kookohd** [thingsboard/thingsboard#10460]
**Need help solving error thingsboard ui**

 * UI
[install.log](https://github.com/thingsboard/thingsboard/files/14787070/install.log)

**Description**
i have successfully downloaded thingsboard, and the server has been started, but i can't access the thingsboard ui. Instructions from https://thingsboard.io/docs/user-guide/install/windows/.

**Environment**

 * OS:  windows 10
 * ThingsBoard: java 11 version
 as i needed java 11, i downloaded one of the previous version which has java 11, windows, jdk, x64, version 11. I download java8 from postgeSQL as it was the latest version, place the 42.7.3 in lib folder under ext folder just like the instructions in thingsboard link, i followed the instructions until i had to access the web ui, as i canot do it but the thingsboard server was up 
when i type net start thingsboard. 
https://jdbc.postgresql.org/download/

 * Browser: the browser i am using is microsoft edge and i need to access localhost:8080 for thingsboard web ui
logs:
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/14787074/thingsboard.log)
[thingsboard.out.log](https://github.com/thingsboard/thingsboard/files/14787076/thingsboard.out.log)
[thingsboard.wrapper.log](https://github.com/thingsboard/thingsboard/files/14787077/thingsboard.wrapper.log)
[thingsboard.err.log](https://github.com/thingsboard/thingsboard/files/14787073/thingsboard.err.log)

**Comment by trikimiki** [comment]
Most likely, it is some kind of MQTT broker app like Mosquitto. You can try checking your Task Manager if it is running.

You can also open the command line (`cmd`) and use `netstat -a -b` to check what exactly runs - you need to check for port 1883.

**Comment by kookohd** [comment]
@trikimiki if i have a mqtt broker running, why does it conflict? i dont get it

**Comment by trikimiki** [comment]
@kookohd 
ThingsBoard uses the MQTT protocol as a possible data transport method. The default port that ThingsBoard binds is 1883, and it is the same for Mosquitto.
If you want to run ThingsBoard and Mosquitto on one machine at the same time, you will need to change default MQTT binding port in either of those.
I am not sure how it is done on Mosquitto, but for ThingsBoard you can find and change the following parameter in `\your-installation-dir\conf\thingsboard.yml`:
```
    # MQTT bind port
    bind_port: "${MQTT_BIND_PORT:1883}"
```
e.g. if you want to change it to 1884:
```
    # MQTT bind port
    bind_port: "${MQTT_BIND_PORT:1884}"
```

**Comment by kookohd** [comment]
@trikimiki if i change the thingsboard mqtt bind port to 1884, how does mqtt broker send the data collected from the devices to thingsboard, as they exist on different port. However there is something i am unsure about. if they are on the same ip address for example thingsboard uses 203.x.x.190:8080 and moquitto i downloaded from eclipse adoptium is using 203.x.x.190:1883. and the mqtt bind port for thingsboard is 203.x.x.190:1884. if they all are under 203.x.x.190 my 1883 broker should be able to send payload to thingsboard right?.

**Comment by kookohd** [comment]
@trikimiki btw if you are free to answer a quick question. 
entered this in cmd prompt: mosquitto_pub -d -q 1 -h 203.x.x.190 -p 1883 -t v1/devices/me/telemetry -u "CAoxkpOJfpmkk9YuS6E" -m "{temperature:25}"
![image](https://github.com/thingsboard/thingsboard/assets/163994445/173cb137-e992-47cd-b9d9-c5e6255bd79d)

![image](https://github.com/thingsboard/thingsboard/assets/163994445/e3286596-c1ce-451e-ba26-1ce385d2c523)
but there is nothing in my latest telemetry why is that so?

**Comment by kookohd** [comment]
so currently i have set the mqtt bind port to be 1884 to listen, my mqtt broker is 1883.

 mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: "${MQTT_ENABLED:true}"
    # MQTT bind-address
    bind_address: "${MQTT_BIND_ADDRESS:203.x.x.x}"
    # MQTT bind port
    bind_port: "${MQTT_BIND_PORT:1884}"
    # Enable proxy protocol support. Disabled by default. If enabled, supports both v1 and v2.
    # Useful to get the real IP address of the client in the logs and for rate limits.
    proxy_enabled: "${MQTT_PROXY_PROTOCOL_ENABLED:true}"
    # MQTT processing timeout in milliseconds
    timeout: "${MQTT_TIMEOUT:10000}"
    msg_queue_size_per_device_limit: "${MQTT_MSG_QUEUE_SIZE_PER_DEVICE_LIMIT:100}" # messages await in the queue before the device connected state. This limit works on the low level before TenantProfileLimits mechanism
    netty:
