### ISSUE TITLE
Configure colour platette in chart widgets

### ISSUE THREAD

**Issue by steve-wright-001** [thingsboard/thingsboard#10466]
**Charts**

* UI

**Description**
I have a timeseries chart that shows all of the temperatures from multiple devices, from a 'Device search query' alias. I can select the colour for the first line on the graph, but cannot find a way to select the rest of the colour palette. Is there a way to do this, or edit the main colour palette used? I'd like to try and make all graphs either fully configurable, or follow a corporate theme.

Thanks.

**Environment**
 * OS:  Windows 10
 * ThingsBoard: cloud
 * Browser: Firefox/Edge

**Comment by ssakharova** [comment]
Hello @steve-wright-001,

There is no way to edit the colors of multiple entity alias data keys (for example, relations query, device groups, etc.) using standard Thingsboard functionality only. However, you can change the color of every data key in separate single-entity aliases (like device, asset, etc.). 

For more clarity, please see the screenshots below:
![image](https://github.com/thingsboard/thingsboard/assets/98035385/d93afa71-59ba-4d27-9a08-721d89ccf09a)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/bef57076-3225-4f59-bf9a-c1a2d74f179d)
