### ISSUE TITLE
Thingsboard - How do I get the customer ID ? 

### ISSUE THREAD

**Issue by Yellowfantt** [thingsboard/thingsboard#10468]
Guys, I'm having trouble getting the ID of the customers I created, could anyone help me?
Is there any API in which I can use the username and password to acquire the customer's ID?
![image](https://github.com/thingsboard/thingsboard/assets/54282309/2dd14181-404c-42c1-9769-e674985286d7)

**Comment by liotys** [comment]
Hi, I guess [https://thingsboard.cloud/swagger-ui/#/customer-controller/getTenantCustomerUsingGET](url) is the function you need connected as tenant administrator.
