### ISSUE TITLE
SMS Provider Settings disappeared on ThingsBoard Professional

### ISSUE THREAD

**Issue by amarotica** [thingsboard/thingsboard#10475]
We can no longer set global SMS provider settings for our ThingsBoard Professional account. Screenshots and guide are available at https://thingsboard.io/docs/user-guide/ui/sms-provider-settings/ but they do not correspond to the actual Settings page.

**Comment by ViacheslavKlimov** [comment]
How does your actual settings page look like? Please attach some screenshots and describe the issue in more detail.

**Comment by amarotica** [comment]
@ViacheslavKlimov this is our settings page:
![image](https://github.com/thingsboard/thingsboard/assets/8608897/40281fa4-55fd-479f-aa54-2cc2c335c6e4)

While the following us what ThingsBoard's docs show:
![image](https://github.com/thingsboard/thingsboard/assets/8608897/1ae39412-deaa-4d27-b6ad-81d0560a9913)

Thanks for looking into it.

**Comment by mykhailokornieiev** [comment]
Hi
SMS settings are available only for sysadmin users.
As far as I see, you are using thingsboard.cloud. There is no access to sysadmin for thingsboard.cloud users. All settings for SMS are already made by Thingsboard, and you just have access to a certain number of SMS per month depending on your plan.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.

**Comment by Vaibhav0216** [comment]
> @ViacheslavKlimov this is our settings page: ![image](https://private-user-images.githubusercontent.com/8608897/320912236-40281fa4-55fd-479f-aa54-2cc2c335c6e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDg1MTQsIm5iZiI6MTcyMTY0ODIxNCwicGF0aCI6Ii84NjA4ODk3LzMyMDkxMjIzNi00MDI4MWZhNC01NWZkLTQ3OWYtYWE1NC0yY2MyYzMzNWM2ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTEzNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE5ZjNhYzZhMGJlNTg2NDc0OTNmZDU5ZmJhZTg3YjI3NWIxZmQ0ZWIyM2YzZTlmMzYzOTQ5YjFlMWJhMGM5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MAQKQH0LLh-1kTS9QK6DPeTW64lYQFaXFoe-pv3uRpI)
> 
> While the following us what ThingsBoard's docs show: ![image](https://private-user-images.githubusercontent.com/8608897/320912600-1ae39412-deaa-4d27-b6ad-81d0560a9913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDg1MTQsIm5iZiI6MTcyMTY0ODIxNCwicGF0aCI6Ii84NjA4ODk3LzMyMDkxMjYwMC0xYWUzOTQxMi1kZWFhLTRkMjctYjZhZC04MWQwNTYwYTk5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTEzNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc4MDQ0NDQ3ZTRkZjA1ZWEzNTc4MTgwZDU5NmZjOWM1MWU0OGM0NTI2N2JhYWY5YTEwNjlmZGMwYTAzZWFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bFqwE4z8eTPi0F3q98bo6nAEH93_eoZ9JB95uRLE2yY)
> 
> Thanks for looking into it.

hi @amarotica  I have same doubt like you. How you have solved this problem.

**Comment by mykhailokornieiev** [comment]
@Vaibhav0216 please get familiar with this comment
https://github.com/thingsboard/thingsboard/issues/10475#issuecomment-2090141532

**Comment by Vaibhav0216** [comment]
Here’s a refined response for your email:

---

Hi ,
Thank you for your information regarding SMS settings for sysadmin users.

As I understand it, since I am using ThingsBoard.cloud, I do not have
access to sysadmin functionalities. It appears that all SMS settings are
pre-configured by ThingsBoard, and my access to SMS is limited to a certain
number of messages per month based on my plan.

Does this mean I need to purchase separate subscriptions for ThingsBoard
Cloud and ThingsBoard PE to fully utilize SMS capabilities?

Looking forward to your guidance.

Kind regards,
Vaibhav

**Comment by mykhailokornieiev** [comment]
@Vaibhav0216 

> As I understand it, since I am using ThingsBoard.cloud, I do not have
> access to sysadmin functionalities. It appears that all SMS settings are
> pre-configured by ThingsBoard, and my access to SMS is limited to a certain
> number of messages per month based on my plan.

This is correct 

> Does this mean I need to purchase separate subscriptions for ThingsBoard
> Cloud and ThingsBoard PE to fully utilize SMS capabilities?

You don't need to use two instances simultaneously. You can consider using a self-hosted on-premise instance and migrating all necessary data. In such case you will need to use Version Control for entities and Rest API calls for telemetry data.

**Comment by Vaibhav0216** [comment]
Thank you for your suggestion regarding using a self-hosted on-premise
instance. However, our organization has decided to use ThingsBoard Cloud to
minimize management and maintenance issues.

Given this scenario, will we need to purchase separate subscriptions for
system administration and infrastructure management, or does a single
subscription cover both aspects?

Looking forward to your clarification.

Best regards,

Vaibhav

**Comment by mykhailokornieiev** [comment]
There is no possibility to use a sysadmin account on thingsboard.cloud at all. It is fully maintained by Thingsboard team as PaaS and SMS setup on it won't be changed. 
For this purpose, the only possible solution is migration to your self-hosted instance, so you will be able to setup your own SMS settings.

**Comment by amarotica** [comment]
On that note, please consider updating your cloud documentation. It is incredibly misleading and is a major factor that caused my client and I go down the wrong path (cloud hosted version vs self hosted). From the sound of it in this GitHub issue, it has been misleading to your other customers as well.On Jul 23, 2024, at 2:38 AM, Mykhailo Kornieiev ***@***.***> wrote:﻿
There is no possibility to use a sysadmin account on thingsboard.cloud at all. It is fully maintained by Thingsboard team as PaaS and SMS setup on it won't be changed.
For this purpose, the only possible solution is migration to your self-hosted instance, so you will be able to setup your own SMS settings.

**Comment by mykhailokornieiev** [comment]
There is no mislead since you've used Community Edition documentation, not the Cloud one. 
![image](https://github.com/user-attachments/assets/7df6c3d2-7ebb-4f2d-bb8c-28f2bfec3b0c)
There are the same articles for Professional Edition
![image](https://github.com/user-attachments/assets/5eeb56cd-c6aa-41bd-bb5f-4bf94884b089)
But there is no such documentation for Cloud.
