### ISSUE TITLE
I want to delete the "function" module on the home page,which code should I delete from "ui-ngx"?

### ISSUE THREAD

**Issue by SuperBabyProgrammer** [thingsboard/thingsboard#10477]
<img width="1045" alt="1711850938360" src="https://github.com/thingsboard/thingsboard/assets/74810645/68ea2c55-cfc8-4f14-b9c3-88e961952179">

**Comment by myroslav-tb** [comment]
Hello @SuperBabyProgrammer, 

You can find files of the widgets for the home dashboard here: https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/app/modules/home/components/widget/lib/home-page

However, the easier solution would be to set up a custom home dashboard for your user.
You can do it by creating a dashboard and setting the widgets that you require. 
![image](https://github.com/thingsboard/thingsboard/assets/158559147/e19893d5-8f05-4d87-b7be-bcf91078f821)

You would need to set it in the user settings.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/de423689-006f-4f66-bacf-816be193721b)

Now, this dashboard will be displayed on the Home page.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/57e8ec06-7a8e-44ec-8b82-04f43ac70786)

**Comment by SuperBabyProgrammer** [comment]
Thank you very much! your answer solved my problem perfectly。
