### ISSUE TITLE
Trendz Analytics: trendz.service: Main process exited, code=exited, 

### ISSUE THREAD

**Issue by PUEVIT** [thingsboard/thingsboard#10474]
**Component**

 * Generic

**Description**
I have the problem that Trendz Analytics does not start anymore and I get the following status message:
trendz.service: Main process exited, code=exited, status=1/FAILURE
trendz.service: Failed with result 'exit-code'.
Installed is last Version 1.10.3

**Environment**

 * OS:  Ubuntu 22.04.1
 * ThingsBoard: version
 * Browser: name and version

**Comment by vparomskiy** [comment]
To find the root cause we need to check errors in the log file (/var/log/trendz/trendz.log)

**Comment by vparomskiy** [comment]
Looks like Trendz service was not updated properly.
Here is a page that describes how to do this - https://thingsboard.io/docs/trendz/install/trndz-upgrade-instructions/#ubuntucentos-1103-hf7

Shert summary:
* Stop Trendz service
* run upgrade script - `sudo /usr/share/trendz/bin/install/upgrade.sh --fromVersion=1.10.3`
* Start Trendz service

**Comment by vparomskiy** [comment]
During upgrade process Trendz write logs. Can you see any errors/problems during upgrade?
