### ISSUE TITLE
How can I bulk delete alarms of an asset?

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10476]
I have thousands of alarms associated with an asset that I need to delete. 
How can I do that? 
I cannot delete the asset and create it again, I need to keep it.

**Comment by ViacheslavKlimov** [comment]
Either create a script that will via REST select all asset's alarms and then delete them one by one, 
or do this through the database:
`DELETE FROM alarm WHERE originator_id = YOUR_ASSET_ID`
