### ISSUE TITLE
get data from a device

### ISSUE THREAD

**Issue by altanop** [thingsboard/thingsboard#10480]
hi , I have made a device in thingboard which reads values from a value generator. I want to create a rule that reads the values I send through curl and not the generator values. Could someone help me?

**Comment by mykhailokornieiev** [comment]
Hi. Please describe your request in as much detail as possible. Do you want to create a rule chain, that will save telemetry sent from curl?

**Comment by maximus12024** [comment]
i found it . but i  would like to help me with another problem. i attach you some rule chain files.  i made an alarm for the WQI_Treatment_Plant_Final but it doesnt work

[water_quality_treatment_alarm.json](https://github.com/thingsboard/thingsboard/files/14823435/water_quality_treatment_alarm.json)

[qwtp_ph_tbd_na_mg.json](https://github.com/thingsboard/thingsboard/files/14823392/qwtp_ph_tbd_na_mg.json)
[qwtp_ca_cl_k_co3_hco3.json](https://github.com/thingsboard/thingsboard/files/14823393/qwtp_ca_cl_k_co3_hco3.json)
[qwtp_so4_f_tds_ec_th.json](https://github.com/thingsboard/thingsboard/files/14823394/qwtp_so4_f_tds_ec_th.json)
[water_treatment_plant_wqi.json](https://github.com/thingsboard/thingsboard/files/14823395/water_treatment_plant_wqi.json)

**Comment by mykhailokornieiev** [comment]
Hi
I recommend you to create the separate tickets for different issues. Please describe you request in as much detail as possible in it, with full explanation of your setup.
As far as I understand, you are trying to generate data **before** root rule chain. In this case, it will not work. I recommend you to add create alarm rule node in it. 
https://thingsboard-portal.atlassian.net/servicedesk/customer/kb/view/1115619341
