### ISSUE TITLE
"Things Board Live" error. Maybe the cloud is not working.

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#10487]
I installed "Things Board Live" from Google Play.
When I run it, I get "No dashboards founds" and the same error with device and assert.
I think the demo system cloud is not working.

and,
I was able to log in with my GitHub account, but if I signed up with my email address, the activation link sent to my email does not seem to be working.

**Comment by epalchenko** [comment]
we were unable to reproduce this issue during testing. Please reopen this ticket if you still have this issue with additional details

**Comment by h-takado** [comment]
I tried it and it seems to work now.
