### ISSUE TITLE
Referencing keys with special characters in TBEL results in "org.thingsboard.script.api.TbScriptException: Error: unresolvable property or identifier:"

### ISSUE THREAD

**Issue by fk-puck** [thingsboard/thingsboard#10488]
Hi all,

I'm trying to set up a rule chain with some calculations but I'm having issues with TBEL as we're using keys with special characters ("-") in their name. Is there a way to escape this character in TBEL?

Keys are like:

EnergyImport-Phase1

Would appreciate any help, I already checked all documentation I found but I can't find a way to get this working.

**Comment by devaskim** [comment]
How do you getting access to this field?
```
msg["EnergyImport-Phase1"]
```

**Comment by fk-puck** [comment]
oh, thank you. That works, indeed... ;-)

**Comment by rancor187** [comment]
> TBEL

### Awesome. Thank you.

How would one know that?
There is not even an example in here regarding that: https://thingsboard.io/docs/user-guide/tbel/

**In the rule-chaine, I need to filter messages like this:
"utilization.throughput.99.endlessCounter"**
**Issue:** 
The digit could be any digit between 0-99. Best solution would be to fetch all messages ending with ".endlessCounter" I guess.

That even possible using TBLE?

Thanks and
best rancor

**Comment by devaskim** [comment]
> Best solution would be to fetch all messages ending with ".endlessCounter" I guess.

@rancor187 There is no such feature. Only manual iterating through subkeys of `utilization.throughput`. Take a look at `foreach` and `entrySet()` examples in official TBEL docs.
