### ISSUE TITLE
Scheduler has no way to schedule events until the end of times

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1049]
Using the PE version of Thingsboard, except for the the issue of attribute updates not being published to the target devices (#1028), everything seems to be working fine. 

However I found that there is no way to schedule repeating events with no end date.

Am I missing something?

(Also, funny things happen when you try using "2100-12-31" as the end date!)

**Comment by ashvayka** [comment]
It is probably a usability issue. Will review and fix
