### ISSUE TITLE
Custom Timewindow

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#10496]
* Custom widget

**Description**
In my custom timeseries widget I'm trying get "max" and "min" values at the same time.
As far as I know the way to do this is to create a custom subscription.

Any help on the structure of "timeWindowConfig" field of the subscription options.

Do I have to subscribe twice for max and min or can I do both at the same time?

**Environment**
 * ThingsBoard: 3.6.2

**Comment by devaskim** [comment]
> Any help on the structure of "timeWindowConfig" field of the subscription options.

Maybe this helps [https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/time/time.models.ts#L122](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/time/time.models.ts#L122)

**Comment by inanlia** [comment]
@devaskim I have checked that link. I wrote my code accordingly. Maybe I made a mistake thats why I was asking others.

Anyway using two custom subscriptions at the same time forced me to restart TB. I'm gonna try a new way to solve my problem.
Still if anyone could give an example of a working code, it would be much appreciated.

**Comment by inanlia** [comment]
Thank you @devaskim. I will look into it.
