### ISSUE TITLE
Telemetry API - Returns a range of time-series values for multiple devices entities.

### ISSUE THREAD

**Issue by maghibus** [thingsboard/thingsboard#10491]
Create a new API in the telemetry-controller that returns a range of time series values for a list of devices.

![image](https://github.com/thingsboard/thingsboard/assets/21333465/e5c3fe4c-d309-4247-8903-4d2848b3fd07)

**Request**

![image](https://github.com/thingsboard/thingsboard/assets/21333465/78b18a32-a405-480a-95b5-ea9a5857ff8e)

**Response**

![image](https://github.com/thingsboard/thingsboard/assets/21333465/385f5296-5fba-49a3-b936-9b5646371a40)

**Comment by myroslav-tb** [comment]
Hello @maghibus, you can use the entity-query controller to retrieve information for multiple entities. It can be accessed by the link in the latest version of the Thingsboard: http://YOUR_HOST/swagger-ui/#/entity-query-controller/findEntityDataByQueryUsingPOST

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.

**Comment by maghibus** [comment]
Hello @myroslav-tb findEntityDataByQueryUsingPOST does not allow you to filter on a value in a specific time range.

**Comment by myroslav-tb** [comment]
Hi @maghibus, I have added a feature request to our prod team backlog. Once they review it, I'll post an update if this feature can be delivered

**Comment by maghibus** [comment]
thanks, if you want I have already implemented the feature in a fork

**Comment by myroslav-tb** [comment]
Hi @maghibus, feel free to contibute using next guide: https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/
