### ISSUE TITLE
Some widgets not rendering accordingly the first time

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10503]
Hello!
Everytime I open a dashboard, this is happening. When I refresh, it clears most of the times (some times does not).
I just uploaded thingsboard to the latest version and this started to happen, also happens in the demo version.
The weird thing is that this does not happen to every widget, it is in some widgets, mainly from Trendz or Tables
![image](https://github.com/thingsboard/thingsboard/assets/98624393/13c4ca0b-bc7f-4639-a2ef-163122c20eef)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/2499d000-811b-4aa3-b0d0-2bde4babb789)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/9e854796-821d-41a5-b9df-b7c2f8249a94)

**Comment by nicovon24** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/98624393/fffe7628-78bd-41d5-8098-aef26400a24e)

**Comment by devdoob** [comment]
It clearly says thta svg tag is not closed. 

If you have ill-formatted html in any widget then TB shows error in most of the widgets. 

Fixed the svg tag in widget next to blue widget of sond sensor table

**Comment by nicovon24** [comment]
Hello dev! Thanks for your help,

Now i have dashboards which sometimes returns bugged errors and sometimes does not, it is a weird thing and don't think is a bug from my application

These widgets were working properly before the update. The applications I developed these months for my company turned out to be a mess, because of the last update. 

Imagine i have an 'imported' svg in an Openstreet map and because of that the widget sometimes returns an error and sometimes does not... I do not think this error is from my part.

Thanks.

![image](https://github.com/thingsboard/thingsboard/assets/98624393/b2745423-51f0-4980-8100-67cb70fe1df8)

**Comment by nicovon24** [comment]
Trendz Widgets which were working are not working, and these do not have svgs, I think there is an issue between the widgets from the previous updates and these one. Thanks

![image](https://github.com/thingsboard/thingsboard/assets/98624393/4107da6b-125c-42c9-a923-9310dbb54282)

**Comment by vparomskiy** [comment]
1. What was the previous version of ThingsBoard?
2. Do you have cutomer widgets?

**Comment by epalchenko** [comment]
Hello @nicovon24,

We've already seen similar behavior if the home dashboard contains widgets with faulty custom HTML code (HTML markdown widget in our case).

**Comment by nicovon24** [comment]
Hello! Yes i forgot to respond, it was lastly an SVG (I had a template string not closed).
@vparomskiy was right.
I had it in two dashboards, as it was in both I thought it was the update.

Thanks for your help @epalchenko @vparomskiy !
