### ISSUE TITLE
Building custom nodes/ library functions

### ISSUE THREAD

**Issue by leoorileo** [thingsboard/thingsboard#1050]
Hi everyone,
I had this question about creating custom nodes in thingsboard environment.
Is there a way to compile and use our own custom node, with custom functionality?
Can someone please help me out with this? Thank you :)
https://github.com/thingsboard/rule-node-examples is one way of doing it, but how do I use this node? make changes to it?

**Comment by ashvayka** [comment]
the nodes need to be placed in the "extensions" folder where thingsboard is installed. They will become available automatically.

**Comment by leoorileo** [comment]
Thank you so much for the reply @ashvayka , can you please specify the location for "extensions" folder? I am unable to locate it, I just found binary-extensions, web-extensions and extensions-form folders which of these should I make use of?

I am trying to create a custom node like one of these nodes(script or check relation or switch nodes)

![thingsboard_node](https://user-images.githubusercontent.com/42926052/45949488-ae8d2080-c019-11e8-8975-7551f9104e40.gif)

**Comment by vparomskiy** [comment]
New Rule Node should be added into classpath. As ashvayka tell - it can be an 'extensions' folder in the directory where Thingsboard service installed.

**Comment by xiehaihong** [comment]
Hi,@leoorileo
how do you modify the file 'custom-nodes-config.js' ?
and define configuration directive like 'tbFilterNodeTestConfig'.
