### ISSUE TITLE
Dynamic Report

### ISSUE THREAD

**Issue by suyutinisai** [thingsboard/thingsboard#10505]
Hi,

I have 10 Devices representing 10 Plants/Sites. These plants have 10 different operators. So I need to send an evening report mail to respective Operators every day. Do I need to create 10 different dashboards or is there any method to pass the device name and generate Report?

 * ThingsBoard: 3.6.3 PE
 
Thanks

**Comment by mykhailokornieiev** [comment]
Hi
As workaround, you can try to create only one dashboard with some entity alias like this:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/bddc1b35-d119-486f-bd19-fc58f2cef302)
In this case it will use some regular name expression. For example, if you have 10 devices with "operator1_device", "operator2_device", etc. pattern, then it will be enought to use just something like this:
`operator%_device`
Then, everything depends on your hierarchy logic. You can share this dashboard with every user group needed, but it will be necessary to create a separate scheduler for each customer.  
![image](https://github.com/thingsboard/thingsboard/assets/115699895/2a3000dd-83fb-4909-80b6-91188ea5b1d4)
Also, you can use specific credentials, so it will report only data available for this user
![image](https://github.com/thingsboard/thingsboard/assets/115699895/408d5026-6d69-4893-a62c-cdf01d1e1d8c)

**Comment by suyutinisai** [comment]
Hi,

Tried this workaround. This is ok for our purpose.

Thanks
