### ISSUE TITLE
Retrieving Time Zone in ThingsBoard Transformation Script Node using TBEL

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/thingsboard#10509]
**Transformation script node (TBEL)**

 
 * Rule Engine

**Description**
How can we retrieve the **local time zone** or browser time zone using the ThingsBoard Expression Language(TBEL)? I tried using 'getTimezoneOffset()' but it is showing an error. Can anyone please provide assistance on this matter?

```
var currentTimeStamp = metadata.ts; 
var msgType = "POST_ATTRIBUTES_REQUEST";

var date = new Date();
var offset = date.getTimezoneOffset();
```

**Comment by epalchenko** [comment]
Hello @Faheem-Punnasseri,

TBEL does not have a getTimezoneOffset() method. Please familiarise yourself with the documentation https://thingsboard.io/docs/user-guide/tbel/#tbdate and choose the method that suits you

**Comment by Faheem-Punnasseri** [comment]
Hello @epalchenko ,

Thank you for your response. I have thoroughly reviewed the documentation provided. Due to the disparity in timezones between our server and our clients, we are encountering issues. Consequently, we are exploring methods to rectify this by obtaining the relevant timezone information. Could you kindly advise if there is a suitable method within TBEL for this purpose, or should I proceed with implementing a solution using JavaScript?

**Comment by epalchenko** [comment]
Hello @Faheem-Punnasseri,

To convert something to a time zone, read this guide:
https://thingsboard.io/docs/user-guide/tbel/#ints-year-month-and-etc-with-optional-time-zone

**Comment by NickDarvey** [comment]
Hey @epalchenko  — your docs say "The Tbel library uses all standard JavaScript methods in the [JavaScript Date](https://www.w3schools.com/jsref/jsref_getdate.asp), such as “toLocaleString”, “toISOString” and other methods;"

`getTimezoneOffset` is a standard JavaScript method that's been there since ES 1. How do we get the timezone offset in a rulechain?

**Comment by rpcai** [comment]
> Hey @epalchenko — your docs say "The Tbel library uses all standard JavaScript methods in the [JavaScript Date](https://www.w3schools.com/jsref/jsref_getdate.asp), such as “toLocaleString”, “toISOString” and other methods;"
> 
> `getTimezoneOffset` is a standard JavaScript method that's been there since ES 1. How do we get the timezone offset in a rulechain?

Agree - This issue should be re-opened, or the documentation updated. I am facing the same issue right now.
