### ISSUE TITLE
Proper Local Web-Development Environment for ThingsBoard Widgets and Dashboards?

### ISSUE THREAD

**Issue by jelacious** [thingsboard/thingsboard#10507]
Hi.

I am wondering if it is possible to have a local web-development environment from which I can run ThingsBoard widgets and dashboards in a reproducible way with possible unit tests? Currently, my development workflow consists of manually copying between the browser-based editor and my own local editor to do changes, linting, version handling etc. This is very cumbersome, error-prone and does not allow me to see if my changes are actually being run in the way I expect, so I am wondering if there is some hidden documentation on how to set-up such a local environment?

What I'd like to have is:
* Unit-tests
* Local copy of an existing instance
* Version control
* Linting
* My own editor for all coding

If this is not possible, I'd love some suggestions on how to make the development process a bit less painful.

**Comment by qwykx** [comment]
Hello @jelacious 
If you'd like to develop quality widgets with reusable components you should have a look at https://github.com/thingsboard/thingsboard-extensions

Testing can be done with `ng test` then, BUT there is still a lack for the tb-services e.g. they have to be mocked.

Cheers

**Comment by ashaforost** [comment]
Closing the issue as stale. Feel free to reopen it if you have any more questions.
