### ISSUE TITLE
Sensor Daten in Dashboard thingsboar filter and sort 

### ISSUE THREAD

**Issue by KhaledSehem** [thingsboard/thingsboard#10514]
Hallo, 
My Objective:

My objective is to retrieve telemetry data from my device and display it on my ThingsBoard dashboard. I have three different sensor IDs that I would like to filter and sort to have separate data fields for each sensor on my dashboard. For example, when I click on Sensor 1, I would like to see the corresponding telemetry data for that sensor, and the same applies to Sensor 2 and Sensor 3.

Furthermore, it is important to mention that the data is continuously updated as it is sent from a receiver connected to a Raspberry Pi. I have already written a script to successfully send the data from the receiver to Thingsboard.

This is the Form of Sensor Ids
'READ: 0 0 4f 9b 19 e5':
Read: 0 0 4f 95 F8 2b
'READ: 0 0 7b 96 1 19':
sensor_3_data.append((timestamp, sensor_id)
Kann you help me? 

Thank you

![IMG_20240404_151200](https://github.com/thingsboard/thingsboard/assets/159773278/9e73e517-a6d6-450a-a8b3-f3ec73a88660)

**Comment by ssakharova** [comment]
Hello @KhaledSehem,

You’ll need to create a main dashboard with at least two dashboard states: a main state (which could list your sensors using an Entities table widget, for example) and a second state (designed to display detailed information about each sensor, perhaps using a Timeseries table widget or other widgets).

These two dashboard states can be linked using a widget action, with a [Custom action](https://thingsboard.io/docs/pe/user-guide/ui/widget-actions/#custom-action) being the ideal choice.
