### ISSUE TITLE
Error subscribing via websocket

### ISSUE THREAD

**Issue by jfparrado** [thingsboard/thingsboard#10516]
**Component**

 * Generic

**Description**
good morning. i am trying to use th websocket for the online version. i am trying with this url "wss://[demo.thingsboard.io/api/ws](http://demo.thingsboard.io/api/ws)" over postman and after it says conencted i am sending this message "{
  "authCmd": {
    "cmdId": 0,
    "token": "Bearer eyJhbGciO...
  }
}" with the token that i got from my profiles page. but every time i try it i am receiving this message "Disconnected from wss://[demo.thingsboard.io/api/ws](http://demo.thingsboard.io/api/ws)
13:29:52
1011 Server Error:
 
Invalid JWT token". an dif i try without the word Bearer it says the te token has expired(it has not because i have just copied it). could you please help me understand what i am doing wrong?

**Comment by CQuarkH** [comment]
That is because you're using the "Bearer " prefix in the token string. Try erasing it.

**Comment by jfparrado** [comment]
i tried without the Bearer but it says "Disconnected from wss://demo.thingsboard.io/api/ws
17:39:16
1007 Invalid Frame:
 
JWT Token expired" . of course i have just generated the new token

**Comment by jfparrado** [comment]
> That is because you're using the "Bearer " prefix in the token string. Try erasing it.

Any idea?

**Comment by jfparrado** [comment]
i am using postman, i got my token from here "https://thingsboard.cloud/api/auth/login", but when i use it on this link "wss://demo.thingsboard.io/api/ws", and then i submmit this message "{
  "authCmd": {
    "cmdId": 0,
    "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyZWNpYmlyY29ycmVvc2lnZ0BnbWFpbC5jb20iLCJ1c2VySWQiOiJiMWY0NDg0MC1mMzZmLTExZWUtYWU4Ny03OWIxOTdkYmZlMTIiLCJzY29wZXMiOlsiVEVOQU5UX0FETUlOIl0sInNlc3Npb25JZCI6ImMyYmY3NDZiLTE3NDgtNGE5Ny1hYmNhLWIxZTIyZDQ1NjZkNyIsImlzcyI6InRoaW5nc2JvYXJkLmNsb3VkIiwiaWF0IjoxNzEyOTMxMTUxLCJleHAiOjE3MTI5NTk5NTEsImZpcnN0TmFtZSI6InJlY2liaXIiLCJsYXN0TmFtZSI6ImNvcnJlb3MiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsImlzQmlsbGluZ1NlcnZpY2UiOmZhbHNlLCJwcml2YWN5UG9saWN5QWNjZXB0ZWQiOnRydWUsInRlcm1zT2ZVc2VBY2NlcHRlZCI6dHJ1ZSwidGVuYW50SWQiOiJiMGM0NTNjMC1mMzZmLTExZWUtYWU4Ny03OWIxOTdkYmZlMTIiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIn0.WNGjjMr5K7_9DqoSokunBi3TnyA_MM9GPJqQtlMhyoKG5bfZGJN1ndx0Mz7JKZYJ0usOtD65z-Av-DW7lttgaw"
  }
}
"
i get the message that it has expired but it still has several hours.

**Comment by jfparrado** [comment]
Thank you for the explaination. 
But if i cant use those tokens, how can i get the right token that is required?

**Comment by jfparrado** [comment]
please some help

**Comment by ViacheslavKlimov** [comment]
/api/auth/login for demo.thingsboard.io

**Comment by jfparrado** [comment]
thanks you so much. i was stocked there for days. i didnt know i had to create an account in demo.thingsboard.io
