### ISSUE TITLE
How do I get the "Display entities selection" in toolbar

### ISSUE THREAD

**Issue by Philip2809** [thingsboard/thingsboard#10523]
**Component**

 * UI

**Description**
How do I get this selector back? We had it before
![default-dashboard](https://github.com/thingsboard/thingsboard/assets/51290462/a24de6c7-f9b4-41f2-9118-fcd6fcebeeb1)

**Environment**
 * ThingsBoard: 3.6.3

**Comment by Philip2809** [comment]
From a bit of digging it seams that it does not show up because the entity alias is not resolved?

**Comment by Philip2809** [comment]
Turns out it only resolves when you have a widget using it and then there is more condtions that have to be meet, like you can't use the device from the dashboardstate, this should all be documented!

**Comment by ssakharova** [comment]
Hello @Philip2809,

In order to do that, you need to go to the dashboard settings and enable the "Display entities selection" option under the Toolbar settings. Please refer to the screenshots below:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/8861dcac-9fa2-4ac5-b724-3b695f3ca2fe)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/86acffd1-4ae6-492f-9f27-474a8f1e4b47)

Best regards,
Sofiia

**Comment by ssakharova** [comment]
Hello @Philip2809,

After digging into the issue, we have determined that this functionality was present in older versions of the Thingsboard. When the “Display entities selection” checkbox was enabled, it allowed users to select entities from aliases on the dashboard toolbar. However, this functionality was rarely used and was subsequently removed by developers. Unfortunately, they overlooked removing the checkbox from the dashboard settings as well.

Thank you for bringing this to our attention. I passed this information to the developers, by creating an internal prod ticket. We ensure that the checkbox will be removed in future versions to avoid any confusion.

Best regards,
Sofiia

**Comment by K-721** [comment]
Hi Sofiia,

While I understand that the feature was rarely used, it is actually very helpful in certain use cases. I currently need this functionality for a power meter dashboard. Having an entity selection would allow a drill-down dashboard of all parameters (e.g voltage, current, harmonics, power factor) to display based on selected device (power meter) only.

Would there be any chance of it being reintroduced in a future release? If not, is there an alternative approach I could use to achieve the same result?

Looking forward to your insights.

Regards,
K
