### ISSUE TITLE
display any dashboard in quick links on home screen

### ISSUE THREAD

**Issue by alenas** [thingsboard/thingsboard#10526]
Customers have some dashboards that they frequently use.

We would like to add a link to "quick links" (in a Home screen) that would take customer straight to a specific dashboard.

In Professional Edition this can be achieved with "custom menu" functionality, but Community Edition does not have that.

**Comment by devaskim** [comment]
Create yet another dashboard and set it as default for each customer's user. Then add quick links to this dashboard

**Comment by mykhailokornieiev** [comment]
Hi @alenas,
You can make the next steps:
1. Create a dashboard with an action button and/or a navigation widget that will redirect to a specific dashboard
For action button:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/49e0910d-f867-4e39-afa6-7bb593a503dd)
For navigation card:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/9ff2fb57-1d80-474b-af21-a9f964a5cf46)
2. Add any necessary widgets from default home page using navigation widgets:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/153fa410-a43e-447c-91e8-5fc9a331f63b)
3. Set this dashboard as the home page for customer:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/8216fbea-a7e1-4478-b4f4-3e2bb8cf8b04)
Now, it will be displayed as home dashboard
![image](https://github.com/thingsboard/thingsboard/assets/115699895/299f1338-a850-4e35-9b33-4bce1a62747b)
