### ISSUE TITLE
Time series data point is an array - how do I split the array

### ISSUE THREAD

**Issue by ezitechthj** [thingsboard/thingsboard#10520]
**Component**

 * Generic

**Description**
I have an Ubuntu Raspberry Pi running Thingsboard IoT Gateway, and connected to a PLC. Some of the timeseries data comes back in array format (see snapshot). How do I separate each array element. In the snapshot each array value defines if a drying bin is open or closed.

![image](https://github.com/thingsboard/thingsboard/assets/147621450/17748c92-e23f-40cd-836d-77c6147b2dda)

**Environment**

 * OS:  Ubuntu Dockker
 * ThingsBoard: 3.6.2PE
 * Browser: Edge

**Comment by qwykx** [comment]
Hello @ezitechthj 

You could do this in the rulechain with the `script` node.

**Post Telemetry**
```json
{
    "bins2StatusSW4": [true,true,false,false]
}
```

**Transform Function in TBEL**
```javascript

var bin_status = msg["bins2StatusSW4"];
var prefix = "prefix"; // Change this to prefix your "index/bin number" represented by i in the following loop

for(int i = 0; i < bin_status.length; i++) { 
    msg[prefix + i] = bin_status[i]
}

return {msg: msg, metadata: metadata, msgType: msgType};
```

**Output**
```json
{
    "msg": {
        "bins2StatusSW4": [true, true, false, false],
        "prefix0": true,
        "prefix1": true,
        "prefix2": false,
        "prefix3": false
    },
    "metadata": {
        "deviceType": "default",
        "deviceName": "Test Device",
        "ts": "1712908568154"
    },
    "msgType": "POST_TELEMETRY_REQUEST"
}
```

**Comment by ezitechthj** [comment]
Excellent. Thank you - this worked.
