### ISSUE TITLE
incorrect function name in template script

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard#10538]
https://github.com/thingsboard/thingsboard/blob/18178b52439cb306d3992d3891947a2ed431ee79/packaging/js/scripts/init/template#L186

shouldn't the function be named `force_reload` as per line 224?

**Comment by ssakharova** [comment]
Hello @skewty,

Thank you for bringing this issue to our attention. We have forwarded the details to our development team so they can correct this flaw.

Best regards,
Sofiia Sakharova

**Comment by anuj-khare** [comment]
Hi @ssakharova ,
since this is quite an easy task,do you mind assigning it to me.
I would love to contribute to thingsboard and would like to start with this one and hopefully become a useful contributor to this project.

**Comment by ssakharova** [comment]
Hello @anuj-khare,

Sure. You are welcome to contribute. Please make a pull request.

**Comment by Andrew1031** [comment]
Hi, I would love to contribute to Thingsboard. Is this issue still open?

**Comment by Andrew1031** [comment]
> Hello @Andrew1031,
> 
> Yes, the issue is still open. You are welcome to contribute. Please make a pull request.

Great, I have submitted a PR

https://github.com/thingsboard/thingsboard/pull/11635
