### ISSUE TITLE
Invalid username or password with rest api call

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#10553]
**Component**

 * Rule Engine

**Description**
Hi,
I'm using a rule node rest api call to modify the label of an asset because I guess we can't modify entity fields with rule nodes.
I have filled the credentials window of the rest api call rule node with "Basic" and the username/password of a tenant administrator.
I have a failure output "org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : "{"status":401,"message":"Invalid username or password","errorCode":10,"timestamp":"2024-04-12T08:06:43.676+00:00""
When I "try it out" the content in swagger with the same account it works.

![image](https://github.com/thingsboard/thingsboard/assets/103430329/2764315b-b503-4285-b1d8-7981ce8d3b3a)

Any Idea of the problem?
Thanks for your answers.

**Environment**

 * ThingsBoard: 3.5.1 PE

**Comment by devaskim** [comment]
Hard to say without configuration of your REST node and how your pass credentials to this node...

Take a look at [this login implementation](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/tb_api_token)

**Comment by liotys** [comment]
Hi @devaskim ,
Here's the rule node config:
![image](https://github.com/thingsboard/thingsboard/assets/103430329/a2bbc595-3a3f-4c59-b18d-f1114f081eb2)

I guessed that with the url specified in the swagger and the credential of the rule node that was enough.

**Comment by devaskim** [comment]
Unfortunately, TB doesn't support such authentication schema. At first, you need to log in (see login endpoint on Swagger page) and then call Asset API with token from log-in stage
![Скриншот 12-04-2024 151949](https://github.com/thingsboard/thingsboard/assets/86909129/2d3e09e6-76b1-496f-8640-4d46cb7961ea)

**Comment by liotys** [comment]
Thanks a lot, I will use your rule node to login before calling the rest node.
