### ISSUE TITLE
[QUESTION] - How to update a widget's state by clicking on a row

### ISSUE THREAD

**Issue by EdikCarlos** [thingsboard/thingsboard#10550]
In thingsboard we have the type Update current dashboard state, but I need to do this manually using the custom action, in addition, I would need to pass the name of the state entity parameter.

![image](https://github.com/thingsboard/thingsboard/assets/70915476/6e985e19-b048-479c-8173-dc5cb57546ed)

**Comment by devaskim** [comment]
Create custom action with something like
```
widgetContext.stateController.updateState(stateId, stateParamsObj);
```

**Comment by EdikCarlos** [comment]
Hello, the problem is that the stateParamsObjs doesn't change when i click in the row this way

**Comment by Ultrazombie** [comment]
Closed due to inactivity
