### ISSUE TITLE
Tenant email required in the REST API, but not in the GUI

### ISSUE THREAD

**Issue by kubakaminski** [thingsboard/thingsboard#10554]
**Component**
 * Generic

**Description**
A tenant's attribute email is set to required here: https://github.com/thingsboard/thingsboard/blob/d62875db98ea3a6e768221d23955ac9ca67c85bc/common/data/src/main/java/org/thingsboard/server/common/data/Tenant.java#L155
However, it is possible to create a tenant without an email using Thingsboard UI. Moreover, the default tenant that is created in a new instance also has an empty email. Due to that, I can't remove/edit the default tenant using REST API client code generated from Swagger docs. I described the problem on the REST API python client level here: https://github.com/thingsboard/thingsboard-python-rest-client/issues/154
Is it possible to somehow remove this default tenant, or maybe you can unset the email as required?

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.6.3
 * Browser: not relevant

**Comment by ViacheslavKlimov** [comment]
Hi @kubakaminski,
As a workaround, you can assign some email to the tenant or delete it **via UI on sysadmin level.**
As for the Swagger, we will fix this discrepancy and make this field not required.
Thanks for reporting this.
