### ISSUE TITLE
How to change Entity aliases with custom action

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#10560]
Hello
I have two categories of active and inactive devices.
I have defined two types of entity aliases active or inactive devices.
I want to choose which  entity aliases to display through custom action.
How can I do this?

**Comment by ssakharova** [comment]
Hello @m3relec,

I recommend that you develop your solution using dashboard states with Markdown/HTML card widgets showing active devices in one state and inactive devices in the other. 

The Smart Retail Solution template partially consists of the Markdown/HTML card widgets. The suggested widget customization and usage in the 'Smart retail' solution template can serve as an example for you to learn and use.
