### ISSUE TITLE
tb-notification-bell in Dashboard

### ISSUE THREAD

**Issue by alanlgirard** [thingsboard/thingsboard#10564]
**Component**

 * UI

**Description**
I am trying to incorporate the user account and notifications that exist in the top bar currently into my dashboard, as I would like a full screen dashboard without the toolbar to allow me to customize the toolbar easily within the dashboard.  I tried adding the following in my html/markdown card but I am not able to get everything to show up.   The account menu icon and picture shows up, but the notification bell does not.  I would like the notification bell to show. Can you let me know if this is possible and what I am missing?

        <tb-notification-bell></tb-notification-bell>
        <tb-user-menu [displayUserInfo]="true"></tb-user-menu>

Would like these in the dashboard
![image](https://github.com/thingsboard/thingsboard/assets/4032278/d7988015-fdc8-4061-a63a-09e0568ebc73)

Currently the user menu icon for account shows and does allow the user to access account page and logout, but the notification bell is not present even though in the dom when inspecting in a browser
![image](https://github.com/thingsboard/thingsboard/assets/4032278/e176d9ea-8dfd-414f-80fc-fcec8dd20cf0)

**Environment**

 * ThingsBoard: 3.6.3 PE
 * Browser: Chrome and Firefox

**Comment by jrkubic** [comment]
@ssakharova Is there a way to retrieve the 'notification' count total?
