### ISSUE TITLE
How do display base64 metric as image in dashboard?

### ISSUE THREAD

**Issue by link89** [thingsboard/thingsboard#10569]
According to this example: https://thingsboard.io/docs/devices-library/esp-eye/#control-device-using-rpc

One can implement a `takePicture` RPC and when it is triggered a photo in base64 format will be saved as an telemetry data.

The whole process is clear to me except the image viewer. Which widget should be used to show the image? HTML value widget or something else?

**Comment by devaskim** [comment]
Use HTML Value Card with the following HTML
```
<img src="data:image/jpeg;base64,${Image}"/>
```
where Image is your date key with base64 string.

**Comment by link89** [comment]
I see. Thank you! Is there any document about the usage of placeholder like `${Image}`?

**Comment by link89** [comment]
For example, I hope that when I send a `takePhoto` command to the device, the device should update an attributed named `latestImage` instead of add a new telemetry data, how can I reference the value in HTTP value card?

**Comment by devaskim** [comment]
>  Is there any document about the usage of placeholder like ${Image}?

No, as I know. But you can look at default configuration of this widget while adding it to your dashboard. I think this example is self-descriptive.

> how can I reference the value in HTTP value card?

`${SOMETHING}` - SOMETHING is the name of your attribute or telemetry data or entity field (name, label)

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
