### ISSUE TITLE
Data keys for related entities in widgets.

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#10578]
**Is your feature request related to a problem? Please describe.**
It's often very usefull to access values of attributes of related entities in addition with attributes of the entity displayed in widgets.

**Describe the solution you'd like**
We could access to attributes or fields or latest datakey of related entities using the name of the relation (rel_name) and it's direction (from, to) like:
rel_name_from.attribute1 or rel_name_to.temperature
It would be great if it could be recursive -> rel_name1_from.rel_name2_to.attribute_name.

![image](https://github.com/thingsboard/thingsboard/assets/103430329/4f5f7789-39fe-4494-9f03-7bb8da5a1d42)

**Describe alternatives you've considered**
When I want to use a related attribute, I copy the attribute of related entity in an attribute of the entity considered. But it needs to be very rigorous with the creation/updates of related values or updates of relations.

**Comment by ssakharova** [comment]
Hello @liotys,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement it in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
