### ISSUE TITLE
Is there client side API to get device name?

### ISSUE THREAD

**Issue by link89** [thingsboard/thingsboard#10571]
As a firmware devloper, I would like to get device name when I connect device to thingsboard server with access token. Is there such API? I have read document in this page but find no relative content: https://thingsboard.io/docs/reference/http-api/#getting-started

**Comment by liotys** [comment]
Hi, the dictionary of the API is here https://demo.thingsboard.io/swagger-ui/.

**Comment by link89** [comment]
> Hi, the dictionary of the API is here https://demo.thingsboard.io/swagger-ui/.

I didn't find the HTTP connectivity API in the swagger doc. For example, there is no

```bash
curl -v -X GET "https://demo.thingsboard.io/api/v1/$ACCESS_TOKEN/attributes?clientKeys=attribute1,attribute2&sharedKeys=shared1,shared2"
```

**Comment by trikimiki** [comment]
Hi!

Depending on the installation type, there might be some entries missing. [demo.thingsboard.io](https://demo.thingsboard.io) is a microservice setup with dedicated HTTP transport, so it's API is out of reach for the "main" API.

If you are using monolith, you can check your local installation for the same path. For example:
http://localhost:8080/swagger-ui/

**Comment by link89** [comment]
Still no. I think the HTTP API for device connection is not part of the swagger doc.

**Comment by KashifAhmd** [comment]
You should try this.

1) for getting device details, name etc.
https://demo.thingsboard.io/swagger-ui/#/device-controller/getDeviceByIdUsingG

2) for device credentials, access_token etc
https://demo.thingsboard.io/swagger-ui/#/device-controller/getDeviceCredentialsByDeviceIdUsingGET

**Comment by trikimiki** [comment]
@link89 it is there for me, under "device-api-controller"

http://localhost:8080/swagger-ui/#/device-api-controller

Are you sure you have a monolith installation, and HTTP (transport) is enabled?

**Comment by link89** [comment]
I find the doc and there is no endpoint to get device data. How about implement an endpoint  `GET /api/v1/{deviceToken}` for the device to get its configuration? 
![image](https://github.com/thingsboard/thingsboard/assets/3314130/8cdb9765-decd-4f2c-baf2-41896d0167f8)

**Comment by link89** [comment]
> What kind of configuration do you need?

device ID, device name, etc. As what I want is to get device info by `deviceToken` instead of user credential, so the device-controller API doesn't work for me.

**Comment by trikimiki** [comment]
You can only get this info by accessing "device controller" API. This requires JWT token to confirm the user auth, that is intended behavior to ensure secure role-based architecture.

The only data you can get via device token are attributes and telemetry. If you really need to access device info, you could create attributes for the device with needed info, but that would raise some security concerns.

**Comment by KashifAhmd** [comment]
![Screenshot from 2024-04-22 17-10-15](https://github.com/thingsboard/thingsboard/assets/109786898/9239b134-a5c3-4dc7-8cab-e99c3f7d57f8)

Try it in postman with Jwttoken without Bearer
