### ISSUE TITLE
Challenge with Displaying Data from Multiple Devices in Custom HTML Widget using Aliases

### ISSUE THREAD

**Issue by Muddassar50** [thingsboard/thingsboard#10577]
I'm currently working on a project where I need to display data from multiple devices within a single widget created using HTML and aliases in ThingsBoard. However, I've run into a challenge where only data from the latest created device is being displayed when multiple devices are added to one alias.
I'm facing an issue where my custom HTML widget, designed to display data from multiple devices using aliases, only shows data from the latest created device when multiple devices are added to one alias.

**What I've Tried**
I've tried various configurations and troubleshooting steps, including reviewing the alias configurations, exploring the documentation, and experimenting with different settings, but I haven't been able to resolve this issue yet.

If anyone has encountered a similar issue or has insights into how to ensure that my custom HTML widget displays data from all devices within the alias, I would greatly appreciate your guidance and expertise.

Your support and insights would be invaluable in helping me overcome this hurdle and successfully implement my project. Thank you in advance for any assistance you can provide!

Looking forward to your responses.

**Environment**
 * ThingsBoard: cloud
 * Browser: google chrome

**Comment by myroslav-tb** [comment]
Hello @Muddassar50, I would recommend for you to use Entities table to display the information from multiple devices in an Entity alias.

![image](https://github.com/thingsboard/thingsboard/assets/158559147/8d014f87-7e89-4e27-bc66-8d465a8c3240)

![image](https://github.com/thingsboard/thingsboard/assets/158559147/41fbfb63-b5a9-4693-afb5-bb2d0d55b95a)


Best regards,
Myroslav

**Comment by Allwhy** [comment]
Hey @Muddassar50
I am a bit late to the party but I have been facing this issue myself and am in the same position of not being able to solve it via the existing HTML value card. The solution I found is to implement my functionality as a custom widget. Although this might not be the most satisfying answer, it works.

**Comment by devdoob** [comment]
Yup its possible if you have a good hand at HTML/CSS.  I used here Markdown widget to iterate over the all the entities in alias and displayed all of data keys. The code is in bottom. 

Tagging @devaskim ... if he likes to add this in [awesome-thingsboard](https://github.com/devaskim/awesome-thingsboard)

![image](https://github.com/user-attachments/assets/29a4336d-9c7a-489d-9db6-85762cc262f6)

![image](https://github.com/user-attachments/assets/3f72363b-86ad-4141-8b64-16f291a1a174)

![image](https://github.com/user-attachments/assets/196e51b6-db54-40ff-a2ed-ae815b77094f)

`
var htmlString = '<div class="flex-container wrap">';

for (var i =0; i < data.length; i++) {
    htmlString += getDeviceCard(data[i].entityName, data[i].entityId);
}

htmlString += '</div>';

function getDeviceCard(deviceName, deviceId) {
    return `
	<div class="flex-item" >
	  <div class="card" >
		<div class="content">
			<h2>${deviceName.slice(-5)}</h2>
			<i class="chip">Vaccant</i>
		</div>
		<div class="card-buttons noselect">
			<div id="lock" device-id="${deviceId}" class="button button-cancel"><svg id="lock" device-id="${deviceId}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg></div>
			<div id="unlock" device-id="${deviceId}" class="button button-reply"><svg id="unlock" device-id="${deviceId}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-unlock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 9.9-1"></path></svg></div>
			<div id="settings" device-id="${deviceId}"  class="button button-reply" style="border-right: none;" ><svg id="settings" device-id="${deviceId}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg></div>
	  	 </div>
	  </div>
	</div>`;
}

return htmlString;`

**Comment by devaskim** [comment]
@devdoob Greate work. Sure, will add. Could you share CSS styles as well?

**Comment by devdoob** [comment]
Yes I did that as a workaround as you know we can not have functions in markdown widget... here is my code to catch click events against each card with its own details

`if ($event.srcElement.attributes['device-id']) {
    widgetContext.attributeService.saveEntityAttributes({
            "entityType": "DEVICE",
            "id": $event.srcElement.attributes[
                'device-id'].value
        }, "SERVER_SCOPE",
        [{
            key: "config_locked",
            value: true
        }]).subscribe();
}`

**Comment by Allwhy** [comment]
Oh!! I see! Thank you a lot @devdoob!

**Comment by Ultrazombie** [comment]
Thanks @devdoob,
Closed due to inactivity.

**Comment by jrkubic** [comment]
@devdoob When implementing this markdown/html card, did you ever encounter a widget refresh problem? I have everything working as expected but when I try to display live telemetry, the entire widget refreshes each time new data is received. There are a few issues already open pertaining to this but was curious if you had encountered the problem in this exact implementation as it's most similar to mine.

Any help is appreciated!

**Comment by devdoob** [comment]
No. Actually I didn't use any telemetry in display so no idea about flickering. But if its really disturbing you then I would to go with custom widget implementation as there we have lots of command over things.

**Comment by aucode** [comment]
I create custom map in HTML Value Card widge. now need get all device latitude and longitude show in map. Can achieve this?
