### ISSUE TITLE
Export data from entity table: aggregation not taken into account

### ISSUE THREAD

**Issue by woodyjon** [thingsboard/thingsboard#10589]
**Describe the bug**
In a dashboard, when I create an entity table and I choose to display an aggregated value (average), it displays well in the table.
But when I export the data in xlsx format, in my exported table, I have the latest values and not the aggregated ones.

<img width="917" alt="image" src="https://github.com/thingsboard/thingsboard/assets/30724004/6fa051e3-4e0b-4a9e-9931-19c11ac64fc4">

<img width="943" alt="image" src="https://github.com/thingsboard/thingsboard/assets/30724004/6c2e676f-8fb8-4535-b14c-4bf80b2cd7b3">

**Your Environment**
* own setup
  * Deployment: monolith on AWS
  * ThingsBoard Version PE 3.6.3

**Your Client Environment**
* OS: Mac
* Browser: Safari
* Version [e.g. 22]

**To Reproduce**
1. Create a dashboard.
2. Add an entity table widget
3. Add a datakey and choose "Aggregation" > "Average"
4. Save your dashboard
5. Click on "export widget data"

**Expected behavior**
An excel file with a table that includes the same values as the ones displayed in the dashboard, so the averages and not the latest values.

**Comment by Ultrazombie** [comment]
Hello @woodyjon,
Aggregation in data key configuration is like a post-processing function that is not taken into account during export.
If you need to export aggregated data, you will have to aggregate it in the rule chain.
