### ISSUE TITLE
Alarm audit

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10587]
How can I know which user cleared an alarm or if it was cleared by the system?

**Comment by SuminDenis** [comment]
Hello @gcorthey 

To see which user cleared an alarm,follow these steps:

1.Click on "Alarms" in the toolbar
![Screenshot from 2024-04-27 13-06-34](https://github.com/thingsboard/thingsboard/assets/63262257/a6ac4220-0f14-4902-bcc4-b629333486cc)
2.Filter Alarms by Status and Severity (in your case, select "Cleared" and "All Severity")
3.In the Assigned field, set it to "All
![Screenshot from 2024-04-27 13-07-17](https://github.com/thingsboard/thingsboard/assets/63262257/5fc531aa-d79f-4314-b715-3d099ad8b777)
4.Click the "Update" button
5.You will see a list of Alarms that have been Cleared
6.Find the "Details" column and click on the "Details" icon to see information about the Alarm
![Screenshot from 2024-04-27 13-09-44](https://github.com/thingsboard/thingsboard/assets/63262257/d8870dde-9014-4f5a-8c63-b1772fbbf9cf)
7.The "Activity" field will show who Cleared this Alarm
![Screenshot from 2024-04-27 13-10-36](https://github.com/thingsboard/thingsboard/assets/63262257/eba3747e-4c02-45b5-b7fc-fde5f6346748)

Hope this helps you!
