### ISSUE TITLE
Cannot edit 'Navigate to other dashboard' action of widget of dashboard imported from another tenant (not VCS)

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#10597]
**Describe the bug**

Steps to reproduce:

1. In Tenant 1 create 2 dashboard. 
2. Create Dashboard 1 with some widget.
3. Create Dashboard 2 with widget which has the `Navigate to other dashboard` action and forwards user to Dashboard 1.
4. Export dashboards.
5. In Tenant 2 import Dashboard 1, then Dashboard 2.
6. Try to edit the the `Navigate to other dashboard` action of widget in Dashboard 2.
7. Got error dialog: 
```
Access Forbidden
You haven't access rights to this location!
Try to sign in with different user if you still wish to gain access to this location.
```
![Скриншот 19-04-2024 125732](https://github.com/thingsboard/thingsboard/assets/86909129/832a694f-5474-44fa-be00-427845a18bb8)

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard 3.6.4
  * Community Edition

**Comment by SuminDenis** [comment]
Hello @devaskim 

If you close the error window and try to change the navigate action again, everything should work.
Its platform design: since after dashboard import the dashboard id is not changed no a new one, you receive a permission error.

**Comment by devaskim** [comment]
@SuminDenis My bad, I haven't ever throught about clicking `Cancel`. Many thanks for you time and help!!!
