### ISSUE TITLE
unable to connect Thingsboard gateway to Thingsboard on AZURE VM

### ISSUE THREAD

**Issue by syuusikou** [thingsboard/thingsboard#1059]
hi everyone, I am a total fresh and was stacked at this problem for 1week+.
I installed TB and TBIoTGateway on one azure VM ( ubuntu16.04 ), and tried to connect gateway to TB following the instruction guide(ThingsBoard doc - IoT gateway get started).
but It just won't work.
my /etc/tb-gateway/conf/tb-gateway.yml file is like this: 
===================================
gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "40.115.147.61" <-----my azure VM globle IP address (I edited the address)
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "SQANC9EKN6nCCYIhJOA9" 
      remoteConfiguration: true
      extensions:
        -
          id: "sigfox"
          type: "SIGFOX"
          extensionConfiguration: sigfox-config.json
===================================

after start TB-gateway service {$ netstat -nap} was like this:
===================================
tcp6       0      0 10.0.0.12:35234         40.115.147.61:1883      ESTABLISHED -
tcp6       0      0 10.0.0.12:1883          40.115.147.61:35234     ESTABLISHED -
===================================

but ping 40.115.147.61 was time out.

any idea why is won't work?
THANKS AHEAD!!

**Comment by armyjam** [comment]
I have this problem too. Did you solve this problem yet?

**Comment by syuusikou** [comment]
@armyjam mine problem is globle address.
it was solved by changing it to private address. but the default private address is not ok（something like 10.0.0.5）.  I set the private address to 192.168.x.x when creating a new VM. then put into the tb-gateway.yml. sovled.....then another problem happened TAT.

**Comment by syuusikou** [comment]
@armyjam mine problem is globle address.
it was solved by changing it to private address. but the default private address is not ok（something like 10.0.0.5）.  I set the private address to 192.168.x.x when creating a new VM. then put into the tb-gateway.yml. sovled.....then another problem happened TAT.

**Comment by armyjam** [comment]
What are your subnet address range and prefix?

**Comment by syuusikou** [comment]
I set it to 192.168.56.102 but i cant remember other information. I can only access it at workplace but I wont be there untill next Tuesday....sry

**Comment by armyjam** [comment]
I set to 192.168.0.0/24 and the private IP is 192.168.0.4 but it's still doesn't work. Please tell me when you can access the web portal. Thanks a lot.

**Comment by syuusikou** [comment]
address range is 192.168.0.0/16.it is default.
did you solve this problem ?

**Comment by armyjam** [comment]
Not yet. I'm finding the solution. Thanks for your help.

**Comment by Ultrazombie** [comment]
Please use instructions for installation from thingsboard.io site
