### ISSUE TITLE
Dinamically update action button icon color using device attribute value

### ISSUE THREAD

**Issue by lucianstefanbarbu** [thingsboard/thingsboard#10598]
**Component**

 * UI

**Description**
Hey, I'm new to Thingsboard and JavaScript in general and I'm trying to create a custom widget that only contains an icon and it dinamically changes the icon's color depending on the boolean value of an attribute of the device I am setting as datasource. I created my widget starting from an Action Button for which i wanted to customize the JavaScript section(this was the logical way of achieving my goal in the way i see widgets right now). 

The reason why I wanted to use an Action Button is because I could easily add a command to switch to another dashboard on-click and it had the icons options already built in. 
```
self.onDataUpdated = function() {
    if (self.ctx.data.length > 0) {
        var fieldKey = self.ctx.data[0].dataKey.name;
        var fieldType = self.ctx.data[0].dataKey.type;
        var latestValue = self.ctx.data[0].data[0][1];

        if (fieldType == 'attribute' && fieldKey == 'power_on') {
            if (latestValue == 'true') {
                self.ctx.$scope.actionWidget.settings.appearance.mainColor = '#0BA112';
                console.log('its green');
            } else {
                self.ctx.$scope.actionWidget.settings.appearance.mainColor = '#B0291F';
                console.log('its red');
            }
        }
    }
};
```
This is what i was able to come up with but the widget's behaviour isn't the intended one because it only changes the color when building the widget and i wanted it to do it in real-time.
**Environment**

 * OS:  Windows 10
 * ThingsBoard: CE 3.6.4
 * Browser: Google Chrome 123.0.6312.123

**Comment by devaskim** [comment]
Try to use JQuery to [change icon's CSS styles](https://api.jquery.com/css/). Something like this to find HTML elements of icons:
```
$('iconCssSelector', self.ctx.$container)
```

**Comment by lucianstefanbarbu** [comment]
Thanks for the response,

I have tried something like this 
```
$('#container > tb-action-button-widget > div > tb-widget-button > button > span.mdc-button__label > div > tb-icon', self.ctx.$container).css("color", "#0BA112");

```

But it does not seem to have any effect on the widget in the dashboard.

**Comment by devaskim** [comment]
![Скриншот 19-04-2024 210153](https://github.com/thingsboard/thingsboard/assets/86909129/6a61a430-2c6b-4514-b61d-894681f7f3a4)

**Comment by lucianstefanbarbu** [comment]
I was able to make it work after all, the problem seemed to be with the CSS selector not being correctly retrieved.
Thanks for all the help!
