### ISSUE TITLE
[VCS] Another default device profile is present in scope of current tenant

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#10593]
**Describe the bug**
For new tenant (i.e. with default device profile) I cannot restore device profiles dump which has its own default device profile even with `Remove other entities` option. While restoring I faced with the following error:
```
Failed: Another default device profile is present in scope of current tenant!
```

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard Version: 3.6.4
  * Community Edition
  * Ubuntu 22

**Comment by ViacheslavKlimov** [comment]
Hi @devaskim,

As a workaround, rename your device profile in the version to "default" and try to import with "Find existing by name" option enabled.

**Comment by devaskim** [comment]
@ViacheslavKlimov Thanks for help
