### ISSUE TITLE
Alarm duration sometimes does not work

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#10590]
**Describe the bug**
Alarm duration sometimes does not work.
For example, The alarm duration in the device profile is set to 2 seconds.
But in alarm table some device shows alarm start time(start_ts) is 2024-04-11 22:18:47,  alarm end time (end_ts) is 2024-04-11 22:18:48, alarm clear time(clear_ts) is 2024-04-11 22:18:48.
The entire time from the start to the recovery of this alarm is less than 2 seconds, which does not meet the condition of a 2-second duration. Why was this alarm created?

**Your Server Environment**
Thingsboard3.3.4.1

* Deployment: microservices
* Deployment type: docker-compose
* ThingsBoard Version: 3.3.4.1
* Community or Professional Edition: Community Edition
* OS Name and Version: Ubuntu20.04

**Comment by ssakharova** [comment]
Hello @xiddjp,

Here is what the Duration term from the [documentation](https://thingsboard.io/docs/pe/user-guide/alarms/#alarm-timing-details) means in the Thingsboard:
_

> **Duration** - an alarm will be created if the duration of exceeding the threshold value exceeds the specified value. For example, you allow a short-term increase in temperature in the room. But if the temperature remains elevated for more than 5 minutes, an alarm is created.

_
