### ISSUE TITLE
SMS provider settings：The drop-down menu cannot be selected and the page will get stuck！！！

### ISSUE THREAD

**Issue by vscodeenv** [thingsboard/thingsboard#10604]
![WXWorkCapture_17137003135414](https://github.com/thingsboard/thingsboard/assets/149743356/e35d9bf8-e109-483d-a1b3-e1cfb47a6aa4)

**Comment by Philip2809** [comment]
Provide browser console? What TB version?

**Comment by Ultrazombie** [comment]
Hello @vscodeenv is this problem still relevant?
if so - please provide additional information.
