### ISSUE TITLE
OAuth2 Cannot save after adding

### ISSUE THREAD

**Issue by vscodeenv** [thingsboard/thingsboard#10605]
![WXWorkCapture_17137003318705](https://github.com/thingsboard/thingsboard/assets/149743356/f0de5333-fbbb-4ee7-908d-feca7dc1a159)

**Comment by ViacheslavKlimov** [comment]
The "Save" button won't be active if you haven't modified anything.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
