### ISSUE TITLE
[FEATURE REQUEST] Generate report into an CSV/XLS

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10619]
Hello,
I am trying to generate a CSV/XLS file similar to the one generated when clicking on a timeseries table in ThingsBoard. However, I need to do this within a rule chain, and the "Generate Report" node does not have this functionality. Additionally, I cannot select the button for CSV/XLS generation when selection of the dashboard state.

I have tried several approaches but have not been successful. Could you please let me know if this feature could be added to a new version of ThingsBoard or if it is already available? Thanks!!

![image](https://github.com/thingsboard/thingsboard/assets/98624393/9ac09c95-69f2-4683-a917-19789480aaee)

**Comment by mykhailokornieiev** [comment]
Hi
Indeed, this is a very popular feature request that has already been asked for multiple times. However, there is no estimated time, or even not known if this feature will be added at all.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.

**Comment by nicovon24** [comment]
Hello @mykhailokornieiev, It would be nice if it can be added. Thanks and hope it can be implemented soon
