### ISSUE TITLE
Decrease the height of the line

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10617]
I have an entity table and I would like to decrease the height of the row. I think there's too much space between the text and the border (padding).

I would like something like this: 
<img width="254" alt="oqueeuquero" src="https://github.com/thingsboard/thingsboard/assets/135682534/d2813ec8-6d91-40d8-a657-2dd2216362be">

**Comment by devaskim** [comment]
Use browser's _Inspect element_ feature to find out which HTML element or CSS class you need to patch, and then add this patched CSS rule to _Advanced widget styles_ of your table.

**Comment by epalchenko** [comment]
Hello @kurch00,

You can look up the element names in the dev tools in your browser. It’s a rule of thumb that works for a majority of custom CSS development on the thingsboard. For example:
![ce3d3942-caaa-442e-9500-dad465732e52](https://github.com/thingsboard/thingsboard/assets/136599093/a5a05134-c693-4fd6-80e0-bb32ffb647da)
![image](https://github.com/thingsboard/thingsboard/assets/136599093/65ebfd46-8a80-40e8-9419-b57dfd76bf5b)
Widget CSS:
`.mat-row{
    height: 15px;
}`
