### ISSUE TITLE
I need to create a filter on my dashboard

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10614]
Hello! I'm new on ThingsBoard and I need some help!

My boss and I have an idea to create a filter on the main state of my dashboard (there's only an entity table).
Unfortunately, we don't know how to do that. I want to filter by the following "organization": client (only the devices from that selected client appear), status (online, offline), and to appear ALL the devices, with no filter. If anyone knows how to create this, I'll be grateful for the help (:

**Comment by liotys** [comment]
Hi, the best way is to use an Update Multiple Attributes widget based on CurrentUser alias. 
After you can use the current user attributes in filters using dynamic values.
What will be not easy is to filter on customer. For my part I've copied customer name in an attribute using a rule chain. If anyone has something better, I'm interested.

**Comment by kurch00** [comment]
ok!! thank you
