### ISSUE TITLE
test

### ISSUE THREAD

**Issue by 123GHLJ** [thingsboard/thingsboard#10628]
Thanks.

**Comment by Backdraft007** [comment]
You can use the alarm rules in the device profile:
https://thingsboard.io/docs/user-guide/device-profiles/#example-2-alarm-condition-with-a-duration

**Comment by 123GHLJ** [comment]
Obrigado pelo retorno Backdraft007.A telemetria recebida tem varias informações(imagem 1),não estou conseguindo realizar o filtro para o alarme considerar apenas IARMS.Realizo este filtro na area da imagem 2 ?
![1](https://github.com/thingsboard/thingsboard/assets/168031149/aa1ca9fe-59a7-4997-9b1e-7031790a4e33)
![2](https://github.com/thingsboard/thingsboard/assets/168031149/0682b641-663c-4c63-946e-380f947206ea)

**Comment by 123GHLJ** [comment]
Thanks for the feedback Backdraft007. The telemetry received has various information (image 1), I was unable to perform the filter for the alarm considered only IARMS. Do I perform this filter in the area of ​​image 2?
![1](https://github.com/thingsboard/thingsboard/assets/168031149/331c54fa-f083-41ab-8e14-5e5eb950140e)
![2](https://github.com/thingsboard/thingsboard/assets/168031149/e5c8f858-79c4-457d-9c5e-0cc5c90ccab2)

**Comment by Backdraft007** [comment]
I only see one image. Please make screenshots in english. It is easier to help.

**Comment by 123GHLJ** [comment]
Sorry.
Image1.
![1](https://github.com/thingsboard/thingsboard/assets/168031149/f276f866-5289-4801-9aa5-ee9497498959)

Image2.
![2](https://github.com/thingsboard/thingsboard/assets/168031149/b9269559-2e60-4e29-95f0-298549da0227)
