### ISSUE TITLE
Push all Device Attributes to Kafka

### ISSUE THREAD

**Issue by bodev1406** [thingsboard/thingsboard#10620]
We are using thingsboard cloud for managing our iot devices. We want to push all device metadata / attributes, no telemetry data for now, to confluent kafka.

I know that i could do it with rule node "originator attributes" but with this node i have to specify all attributes.  I need a more generic way.

Is there a way to do it in thingsboard? Maybe with the rule engine or something else?
How can i get all device information and push it to kafka?

**Comment by devaskim** [comment]
You can do almost the same as described, but get list of attributes via [corresponding API call](https://thingsboard.cloud/swagger-ui/#/telemetry-controller/getAttributeKeysByScopeUsingGET).

**Comment by bodev1406** [comment]
Yes you are right but for the API call i have to do it with an external service and not with thingsboard. Or is there a way to do it in thingsboard?

**Comment by devdoob** [comment]
You have "REST API node" withing rule chain of Thingsboard, just use that to pull data of devices and then push to kafka.

**Comment by bodev1406** [comment]
Ok, your are right. 

To call the API endpoint i have to use the bearer token. How can get such a bearer token in a rule chain?

**Comment by Ultrazombie** [comment]
Hello @bodev1406, 
Is this ticket still relevant? Or we can close this?

**Comment by ashaforost** [comment]
@bodev1406 have you tried the external kafka rule node?
![image](https://github.com/thingsboard/thingsboard/assets/47900737/539d70ff-9aac-4db0-95b5-2594a6a3eada)

**Comment by bodev1406** [comment]
@ashaforost Yes i tried it. So problem was that i need a way to get all attributes of a device or asset and push this information to our kafka instance.
We solved it to use the login rule cain of @devaskim and do a REST API Call to the thingsboard endpoint to get the needed information. After retrieving this information the kafka node is pushing it.

It would be nice to have such a node to query such information
