### ISSUE TITLE
It is recommended to refactor a more friendly and standardized API with reference to Fiware's NGSI v2 API.

### ISSUE THREAD

**Issue by ten2net** [thingsboard/thingsboard#1064]
The Thingsboard REST API is too complex to standardize. It is recommended to refactor a more friendly and standardized API by referring to Fiware's [NGSI v2 API](https://github.com/Fiware/specifications).

**Comment by ashvayka** [comment]
I believe the API you are referencing is quite immature. It is also not clear why we should change the API at all. We have 2000+ servers of ThingsBoard running and I assume we have a lot of applications that already use our API. If we do the change it will break the apps. We are not going to do the breaking changes.
