### ISSUE TITLE
Showing dashboard creation Time in home dahboard widgets

### ISSUE THREAD

**Issue by sushil2817** [thingsboard/thingsboard#10656]
Hey, I tried to create a new widget that would show the dashboard. creation time in the home dashboard
   
    So I did these things and get something interesting 

1) I fetched 2 API's 
a) The authentication API: I fetched this API and get a token and a reference token. (but the user's email and password are hard-coded.)
b) The Dashboard Info API: Again, I fetched this API using the above token, and I would access all the Dashboard Info. I got dashboard creation time, and I created a feature that showed the users total days from dashboard creation day.     
      
So I did those tasks, but the problem is that user credentials are hard-coded, so how can I get a token from local storage? 

Please help me to solve this problem

**Comment by Philip2809** [comment]
you can ask for the dashboard info directly, either via the service in self.ctx.dashboardService.getDashboardInfo() it calls `/api/dashboard/info/${dashboardId}`, check `dashboard.service.ts` for more. This automatically authenticates with logged in user. 

Otherwise you can use localStorage.jwt_token.

**Comment by sushil2817** [comment]
> you can ask for the dashboard info directly, either via the service in self.ctx.dashboardService.getDashboardInfo() it calls `/api/dashboard/info/${dashboardId}`, check `dashboard.service.ts` for more. This automatically authenticates with logged in user.
> 
> Otherwise you can use localStorage.jwt_token.

Could you please elaborate this?

**Comment by Philip2809** [comment]
in your widget code:
`self.ctx.dashboardService.getDashboardInfo(location.pathname.split('/')[2]).subscribe(d => console.log(d.createdTime))`

This gets the current dashboardid based on the url and console logs the createdTime

**Comment by sushil2817** [comment]
> self.ctx.dashboardService.getDashboardInfo()

This snippet of code is giving an error: "Cannot read properties of undefined (reading 'dashboardService')" how can I deal with this kind of code?

**Comment by sushil2817** [comment]
I Solved this problem using localStorage token, then fetched the API and got my results.
