### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by tagliala** [thingsboard/thingsboard#1066]
Hi,

Sorry, I cannot find this information in the documentation

Which browsers are officially supported by the ThingsBoard front-end?

**Comment by vparomskiy** [comment]
The main browser for development - Chrome. 
But in Latest Firefox, IE 11, Edge I think it also should be stable.

**Comment by tagliala** [comment]
@vparomskiy thanks for the answer.

I'm the author of PR #1054. I was interested in adding autoprefixer support and drop vendor prefixes from the SCSS files, but in order to do that I need a list of supported browsers

**Comment by ikulikov** [comment]
ThingsBoard Front-End is based on AngularJS v.1.5.8 and [AngularJS Material v.1.1.1](https://github.com/angular/material). 
TB Front-End is compatible with all browsers supported by AngularJS Material.

From the AngularJS Material [official documentation](https://github.com/angular/material):

> AngularJS Material is targeted for the browser versions defined in the broswerslist field of our package.json. Below is a screenshot from browserl.ist that provides a visual representation of this configuration

**Comment by MarsWarrior** [comment]
Are there any plans to upgrade the AngularJS version used?

The used version has some vulnerabilities according to this site: https://snyk.io/test/npm/angular/1.5.8

We did test an upgrade, but newer Angular versions (1.6/1.7) have breaking changes...

**Comment by tagliala** [comment]
@MarsWarrior 

I'm new to ThingsBoard. As far as I can tell, [some widget](https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/widget/lib/timeseries-table-widget.tpl.html) [use angular](https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/widget/lib/alarm-status-filter-panel.tpl.html) and I can't find tests for the front-end

So, I think that third party plugins could be affected by an Angular upgrade and I would conclude that it is not safe to upgrade.

**Comment by Ultrazombie** [comment]
closed as not active
