### ISSUE TITLE
How to add a new topic subscription using MQTT in thingsboard 

### ISSUE THREAD

**Issue by alersi9** [thingsboard/thingsboard#10667]
**Component**

 * Generic

**Description**
I have a question and I need some support. I am developing a project in which we have connected a certain device to thingsboard through a MQTT basic connection. As far as i know, for data visualization within thingsboard, MQTT devices should publish in topic v1/devices/me/telemetry. However, my device is publishing this data in v1/devices/me/telemetry/Devices and I can not access the data in thingsboard. Is there any way to subscribe to new topics in thingsboard? Actually I am publishing data in several topics and it would be so helpful to know how to subscribe to different topics within thingsboard

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: Community Edition
 * Browser: Firefox

**Comment by alersi9** [comment]
Solved!

**Comment by ca6aqa** [comment]
How did you solve this problem?
