### ISSUE TITLE
IoT Gateway as modbus slave to send TS data to PLC

### ISSUE THREAD

**Issue by ezitechthj** [thingsboard/thingsboard#10666]
**Component**

 * Generic

**Description**
I collect data via LoRAWAN in to Thingsboard. I need to send the same data to a PLC based on the customers network. Was thinking IoT Gateway in modbus slave mode and writing to the slave registers from Thingsboard via RPC for the PLC to read. Is this possible ? (have used IoT gateway as modbus master for collecting PLC data, but not as slave for PLC to collect data from me)

**Environment**

 * OS:  Ubuntu on RPi
 * ThingsBoard: latest
 * Browser: Edge

**Comment by Ultrazombie** [comment]
Hello @ezitechthj 
Please use the gateway issue page for gateway issues.

https://github.com/thingsboard/thingsboard-gateway/issues
