### ISSUE TITLE
Count off/on devices

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10673]
I have an entity table and i want to create a column with the total online devices and the total offline devices. How can i do that?

**Comment by kurch00** [comment]
<img width="1658" alt="2024-04-30 12_38_32-NETZSCH IoT Platform _ Dashboard e mais 10 páginas - Trabalho — Microsoft​ Edge" src="https://github.com/thingsboard/thingsboard/assets/135682534/3cdaf102-5d35-480f-aed1-f880d2ef6038">

I have this information, and I want to add off/on column. i

**Comment by ssakharova** [comment]
Hello @kurch00,

Please try to use the Entity Count widget in your setup.
<img width="319" alt="image" src="https://github.com/thingsboard/thingsboard/assets/98035385/769038f9-3f9b-4900-88a4-0cbe5abef3b0">
