### ISSUE TITLE
Arabic Language UI

### ISSUE THREAD

**Issue by AdeebAldkheel** [thingsboard/thingsboard#10675]
**Component**
 * UI

**Description**
I'm not able to choose Arabic Language, I hope there is an xml file so I can add language and choose it from settings:
![image](https://github.com/thingsboard/thingsboard/assets/36278399/61f842fc-bf49-4f44-a2e8-c644bdd9665a)

**Environment**
 * OS:  Ubuntu 20.04.6 LTS *
 * ThingsBoard: 3.6.2 *
 * Browser: Edge *

**Comment by Ultrazombie** [comment]
Hello @AdeebAldkheel,
We already have merged PR for the Arabic language, and it will soon be available in version 3.7.
https://github.com/thingsboard/thingsboard/pull/10269
