### ISSUE TITLE
Californium block offset mismatch

### ISSUE THREAD

**Issue by madmo** [thingsboard/thingsboard#10690]
**Describe the bug**

When there is a delay (for whatever reason) in the CoAP communication while doing a OTA californium drops out it's special transparent block mode.

When not in transparent mode thingsboard has to supply the correct response block number to not cause a internal server error in californium.

**Your Server Environment**
* own setup
  * Deployment: microservices
  * Deployment type: k8s
  * ThingsBoard Version 3.6.3
  * Community
  * OS Name and Version

**Your Client Environment**
Does not matter, it is a coap transport related issue

**Your Device**

* Connectivity
  * CoAP
* Device vendor and model
  custom coap over thread sensor

**To Reproduce**
Start a OTA over a slow, not perfectly reliable network connection, and observe the device failing with a server error, and also see messages like these in the log:

```
2024-05-02 06:06:09,463 [CoapServer(main)#1] WARN  o.e.c.c.network.stack.BlockwiseLayer - coap resource [coap://localhost/fw/xxx] implementation error, peer requested block offset 153600 but resource returned block offest 0
```

**Additional context**
Discussion in Califronium
https://github.com/eclipse-californium/californium/issues/2234

**Comment by Ultrazombie** [comment]
Thank you for the contribution!
