### ISSUE TITLE
Older Iphones cant load login site since 3.6.3

### ISSUE THREAD

**Issue by X1folta** [thingsboard/thingsboard#10692]
**Describe the bug**
Since we upgraded to 3.6.3 we have several issue reports of users trying to login to our thingsboard instance. All users experiencing issues have Iphone 7 or older, the most-up-to-date firmware version we confirmed so far was iOS 15.7.9. 

**The issue is present also when trying to access https://thingsboard.cloud/login for any of the affected users**

What happens is that it loads the page indefinitely, the three dot animation never stops. Inspecting through the Dev Console we see that a Reference Error gets thrown, saying 'l' (lower case 'L' ) is undefined and the line provided by the Dev Console's stack trace references 'refreshToken' but as the code is obfuscated I dont think any more details can help. 

**Your Client Environment**

**Smartphone (please complete the following information):**
* Device:  iPhone7 and older
* OS: iOS 15.7.9
* Browser Safari

**To Reproduce**
1. Use Iphone 7 or older
2. Go to https://thingsboard.cloud
3. The three dots loading icon starts playing
4. Nothing anymore happens

**Expected behavior**
Login mask / page should be loaded

**Screenshots**
![PXL_20240502_070327503 MP](https://github.com/thingsboard/thingsboard/assets/69015781/70fb479d-81f4-481c-9971-260ce4e1f279)

**Comment by AlexDoanTB** [comment]
There is no bug. The issue is non-reproducible. 
If your users only face pre-loaders, it is more likely that they have network limits (and static resources are loaded super slowly in their region) or were introduced by network providers, taking into account that even not all your users experience the same behaviour.

**Comment by AlexDoanTB** [comment]
As a clue, perhaps the Safari version on iOS 15.x may not support Angular 15+.

**Comment by X1folta** [comment]
@AlexDoanTB 

The devices had the same issue, same behaviour in different networks, we can reproduce it with an Iphone 7 (iOS 15.7.9) in our company network too. Every Iphone 7 or older user so far had the same issue and same behaviour.

We upgraded our Thingsboard instance from 3.6.0 to 3.6.3 where Angular 15+ was present and there it worked. But as mentioned, trying to access Thingsboard cloud leads to the same behaviour. Thanks for your time so far.

**Comment by AlexDoanTB** [comment]
I tested with simulators and real devices with iOS 15.x. 
On that OS, Safari fails to load the login page. If possible, try upgrading to whatever iOS 16.x.

**Comment by X1folta** [comment]
Which simulators are you using? 

We also have an Iphone 6s with same behaviour. Due to Apple's update policy an Iphone 7 cant upgrade above 15.8.2. The upgrade from 15.7.9 to 15.8.2 didnt fix it. If it is to be pinpointed to the deprecated iOS versions in combination with Angular then thats it unfortunately.

**Comment by AlexDoanTB** [comment]
You can test with https://live.browserstack.com/
Support for the Angular features by browser is out of our control, unfortunately.

**Comment by X1folta** [comment]
Thanks for the site. We deployed a Thingsboard instance on version 3.6.0. and version 3.6.3 to test the incompatibility. Were there updates made on Thingsboards Angular Integration specifically in 3.6.3 or its minor releases before 3.6.3? According to the patch notes the migration to Angular 15 was in 3.5.0. 

However discontinued iOS versions as present in the Iphone 7 are able to access 3.6.0. which should have Angular 15.

**Comment by AlexDoanTB** [comment]
@X1folta I mentioned 15+, not 15. You can check that v3.6.3 uses Angular 15.2.10 hotfix while the very recent v3.6.0 is on Angular 15.2.9 at least.
