### ISSUE TITLE
Thingsboard 2.1 on Windows10 missing items in menu

### ISSUE THREAD

**Issue by mennaifer** [thingsboard/thingsboard#1069]
Hi All,
I installed Thingsboard 2.1 on Windows10. When starting the UI i found mising menues like Rules, Devices, Dashboards.
Is this normal?
Thanks

![image](https://user-images.githubusercontent.com/31559621/45369679-bd6ddf00-b5e6-11e8-90d4-a51b58e8f74d.png)

**Comment by mennaifer** [comment]
Attached the install.log and the thingsboard.log
Thanks
[install.log](https://github.com/thingsboard/thingsboard/files/2372212/install.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2372213/thingsboard.log)

**Comment by vparomskiy** [comment]
You have logged in as System Administrator. You need to create Tenant & Tenant User. 
When you will log in as Tenant User, you will see other menus (Rules, Dashboard, etc.)

**Comment by mennaifer** [comment]
Thank you. It's working.
