### ISSUE TITLE
Error when sign up for live demo server by name and email 

### ISSUE THREAD

**Issue by jk4e** [thingsboard/thingsboard#10706]
**Describe the bug**
Error when trying to sign up to the live demo server by name and email on:

> https://demo.thingsboard.io/signup

I have tried several mail addresses and providers. I do not want to use Sign up with ... or test if this works.

**Your Server Environment**

* [https://demo.thingsboard.io](demo.thingsboard.io)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser: Microsoft Edge, Firefox

**To Reproduce**
1. Try to create an account with name, email, password

**Screenshots**
![Screenshot 2024-05-03 143912](https://github.com/thingsboard/thingsboard/assets/116908874/7e9296e6-c159-49da-a58b-9abd05c363be)

**Error message**

`
Unable to send mail: org.springframework.mail.MailSendException: Failed messages: java.lang.ClassCastException: class com.sun.mail.handlers.text_html cannot be cast to class jakarta.activation.DataContentHandler (com.sun.mail.handlers.text_html and jakarta.activation.DataContentHandler are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @2d8f65a4); message exceptions (1) are: Failed message 1: java.lang.ClassCastException: class com.sun.mail.handlers.text_html cannot be cast to class jakarta.activation.DataContentHandler (com.sun.mail.handlers.text_html and jakarta.activation.DataContentHandler are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @2d8f65a4)
`

**Comment by ashaforost** [comment]
Hi @jk4e  

Thank you for reporting the issue. We have fixed it. Please check and let me know.

**Comment by jk4e** [comment]
Hi @ashaforost,

Everything is working fine now! I was able to create an account. 

Thank you and the team for your quick support and fixing the issue!

From my point of view, the issue can now be closed.
