### ISSUE TITLE
Widget inside widget

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10709]
Well, I have a HTML widget and i'd like to put an "Update Multiple Attributes" widget inside the HTML widget. How can I do that?

Here's an example:

<img width="173" alt="widget" src="https://github.com/thingsboard/thingsboard/assets/135682534/4054c105-071a-435d-abc0-df769a1ff11c">

**Comment by Ultrazombie** [comment]
Closed due to inactivity
