### ISSUE TITLE
Devices by oauth2 token

### ISSUE THREAD

**Issue by Nypiaka** [thingsboard/thingsboard#10708]
Is it possible to somehow get a list of user devices through the API with only a jwt oauth2 token? In short, I have a system of 3 services, one of which is ThingsBoard. The first service is authorized through Keycloak, receives a jwt token and goes to the second. The second one wants to use this token to log in to ThingsBoard via Keycloak and get a list of user devices that are authorized by the same Keycloak account in ThingsBoard. How can this be done better? So far, I haven’t come up with anything smarter than writing a separate controller that accepts a token, decodes it, collects an OAuth2AuthenticationToken from it, and only through it receives the user and his devices.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
