### ISSUE TITLE
Unable to send emails for new alarms on Thingsboard Cloud

### ISSUE THREAD

**Issue by JakubVanek** [thingsboard/thingsboard#10718]
**Component**
 * Generic

**Description**
I'm trying to get ThingsBoard to send me an email to GMail when a new alarm is created. I have tried the approaches below, but I was unfortunately not successful. I'm uncertain if I am doing something wrong or if I'm hitting a bug.

 * Methods of creating an alarm: I've tried both the "alarm rules" way (in device profile) and the rule engine way. In both cases, the alarm itself was created. However, the email notification was not sent, see below.
 * Methods of sending an email:
   * I have tried adding an email template to the "New alarm notification" and "Alarm update notification" templates in the Notification center. The result was the following:
     * Email was never sent if an alarm was created or updated by the alarm rules or the rule chain.
     * Email was sent if I manually updated the alarm from the web UI, e.g. when I manually acknowledged the alarm.
     * Web notifications (configured by default) worked in all cases.
   * I have tried sending an email via the "to email" and "send email" rule engine blocks. According to the rule engine debugger, the "send email" block returned an ACK result. However, I've never received the email.
 * Email backends: I tried using the TB Cloud's system SMTP and also my own GMail via an app password. In both cases, the behaviour was the same (I received emails triggered by interaction in UI, but I did not receive emails triggered by device activity).
 * When using the "send email" block in the rule engine, I tried it with both the system SMTP option and with manually-entered GMail credentials.

One interesting observation I have is that when an email was not sent (even though I wanted it to be), it was not counted towards the email quota. This might indicate that the email indeed was not sent from ThingsBoard (as opposed to it being rejected by Google SMTP servers).

**Environment**
 * ThingsBoard: Cloud
 * Browser: Firefox 125.0.3

**Comment by JakubVanek** [comment]
Something seems to be happening now though - during the night, I have received two of the emails that I tried to send from the rule engine via the "to email" block.

**Comment by ashaforost** [comment]
Hi @JakubVanek,

Thank you for reporting this issue! We are currently working on the fix. I will update you when the fix is deployed.

**Comment by ashaforost** [comment]
@JakubVanek 
I apologize for the inconvenience. 
I’m pleased to inform you that the issue was fixed, and the emails are sending now. Please check and let me know if you see any issues.

**Comment by JakubVanek** [comment]
Hi @ashaforost,

thank you for the quick response! I can confirm that emails are now working correctly for me.
