### ISSUE TITLE
Thingsboard - Rule chain for exceuting a expression and store its output under a device as telemetry

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#10722]
I have a widget in my thingsboard dashboard where i input two values. I need to divide these two dashboard inputs and display it in another widget in the same dashboard. How can i achieve this. Is there any specific rule chain for such applications. Or else is it possible to do it directly in the dashboard.

**Comment by ashaforost** [comment]
Hi @mubashirp 

In the rule chain, you can catch the 'Attributes Updated' event and perform the calculation based on the two updated attributes. 
See the screenshots:
![image](https://github.com/thingsboard/thingsboard/assets/47900737/6cad739f-c073-4151-9bba-4aa07c3edcd9)

![image](https://github.com/thingsboard/thingsboard/assets/47900737/4fd083c9-62aa-44ab-b637-ccbebe9583a7)
![image](https://github.com/thingsboard/thingsboard/assets/47900737/10542e54-025f-4539-bacd-e8e3cb412eee)
![image](https://github.com/thingsboard/thingsboard/assets/47900737/73e74425-2d16-4325-af78-badd22ac9d37)


Make sure to change the msgType to "POST_ATTRIBUTES_REQUEST"
