### ISSUE TITLE
Procedure For Fixing Bug

### ISSUE THREAD

**Issue by subrataghosh** [thingsboard/thingsboard#10724]
Hello Team,

I have pulled latest code from the following link 
https://github.com/thingsboard/thingsboard.git

Now, I have found 1 issue in the java source code.
I have fixed that issue and I want to push this code ,so what will be the procedure for forwarding this changes to master?

**Comment by Ultrazombie** [comment]
Hello @subrataghosh 
Please use the following guide:
https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/
