### ISSUE TITLE
how to use d3.js to create custom charts

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#10747]
**Environment**

 * OS:  Ubutu and 22.04
 * ThingsBoard: 3.4

**Comment by devdoob** [comment]
By using custom widgets. Its very easy to implement 3rd party chart libraries if you have understanding how to pull data out of TB

**Comment by epalchenko** [comment]
Hello @KashifAhmd,
To use d3.js in a custom widget, you need to find the library you need on this site: https://cdnjs.com/
![image](https://github.com/thingsboard/thingsboard/assets/136599093/3751c35d-872b-41ea-84b0-ac76eb7de0f9)
Go to the library you need and copy the URL:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/f033b2c2-5976-4e2d-920b-34994560183c)
You should paste this URL into Resources as follows:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/ae52bedb-ed9c-4d60-8d97-e387d2f89ee7)

**Comment by epalchenko** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with a full description of your request.
