### ISSUE TITLE
OTA Firmware update triggers a reconnect loop

### ISSUE THREAD

**Issue by RaiseYourChicken** [thingsboard/thingsboard#10745]
I'm using the Mqtt Python sdk client. When I trigger a firmware update it tries to start it but then the client enters a disconnect/connect loop. From the server side an exception seems to be triggered whenever a new connection is formed with the thingsboard server.

**Your Server Environment**
We have the server deployed through a docker compose on a cloud instance of our internal network
![image](https://github.com/thingsboard/thingsboard/assets/18746685/3efea173-7be7-4cf7-bc38-3292130379e6)

The logs on the client side:
![image](https://github.com/thingsboard/thingsboard/assets/18746685/0344848d-3c71-4c5a-94da-0654e7b17327)
![image](https://github.com/thingsboard/thingsboard/assets/18746685/76270ffd-23f8-44f8-ad27-30cdf73e4c2b)

The Exception shown on the server side:
![image](https://github.com/thingsboard/thingsboard/assets/18746685/e91a6e6e-4975-4a16-8c73-010a7e6e93ad)

**Comment by RaiseYourChicken** [comment]
Problem has been solved, the thingsboard python sdk client was sending the payload wrapped in quotation marks, so instead of emtpy payload "" was arriving, or if sending a chunk_size we would get "1024" instead of 1024

I override the __get_firmware method to fix this

**Comment by Ultrazombie** [comment]
Closed due to inactivity
