### ISSUE TITLE
tb-gateway Failed to decode message

### ISSUE THREAD

**Issue by mamanso** [thingsboard/thingsboard#1075]
Hi
I have configurate the tb-gateway and finnaly it start to work.
The second step is to connect to MQTT broker. I am using a cloud broker iot.eclipse.org with piml/nodemcu topic and trying to map the deviceId to the name of the device and some attributes to the timeserie. The error message is follow. What is the error? thanks

2018-09-12 20:45:29,820 [pool-2-thread-4] INFO  o.t.g.s.gateway.MqttGatewayService - Configuration updates arrived! {"configuration":"[{\"id\":\"mqtt\",\"type\":\"MQTT\",\"configuration
\":{\"brokers\":[{\"host\":\"iot.eclipse.org\",\"port\":1883,\"ssl\":false,\"retryInterval\":3000,\"credentials\":{\"type\":\"anonymous\"},\"mapping\":[{\"topicFilter\":\"piml/nodemcu\"
,\"converter\":{\"attributes\":[],\"timeseries\":[{\"type\":\"double\",\"key\":\"temperature\",\"value\":\"${$.temperature}\"},{\"type\":\"double\",\"key\":\"humidity\",\"value\":\"${$.
humidity}\"}],\"type\":\"json\",\"deviceNameJsonExpression\":\"${$.deviceId}\",\"deviceTypeJsonExpression\":\"${$.deviceId}\",\"filterExpression\":\"500\"}}],\"connectRequests\":[],\"di
sconnectRequests\":[],\"attributeRequests\":[],\"attributeUpdates\":[],\"serverSideRpc\":[]}]}}]"}
2018-09-12 20:45:29,821 [pool-2-thread-4] INFO  o.t.g.service.TenantServiceRegistry - [Tenant] Updating extension configuration
2018-09-12 20:45:30,187 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-12 20:45:35,272 [MQTT Call: d78f8041-87e8-4544-a064-49af9f5a853b] INFO  o.t.g.e.m.c.l.MqttTelemetryMessageListener - [piml/nodemcu] Failed to decode message: [123, 34, 100, 101,
 118, 105, 99, 101, 73, 100, 34, 58, 34, 54, 56, 58, 67, 54, 58, 51, 65, 58, 68, 53, 58, 51, 67, 58, 70, 48, 34, 44, 34, 87, 105, 70, 105, 82, 83, 83, 73, 34, 58, 45, 54, 48, 44, 34, 11
6, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 34, 50, 48, 49, 56, 45, 48, 57, 45, 49, 50, 32, 50, 48, 58, 52, 53, 58, 51, 52, 34, 44, 34, 116, 101, 109, 112, 101, 114, 97, 116, 117,
 114, 101, 34, 58, 34, 50, 50, 46, 50, 48, 34, 44, 34, 104, 117, 109, 105, 100, 105, 116, 121, 34, 58, 34, 54, 54, 46, 48, 48, 34, 44, 34, 112, 114, 101, 115, 115, 117, 114, 101, 34, 58
, 34, 49, 48, 50, 53, 46, 50, 57, 34, 44, 34, 108, 117, 109, 105, 110, 111, 115, 105, 116, 121, 34, 58, 34, 50, 54, 55, 34, 44, 34, 104, 101, 97, 116, 73, 110, 100, 101, 120, 34, 58, 34
, 55, 49, 46, 57, 54, 34, 44, 34, 109, 111, 116, 105, 111, 110, 34, 58, 34, 115, 116, 97, 110, 100, 98, 121, 34, 44, 34, 115, 111, 117, 110, 100, 78, 111, 105, 115, 101, 34, 58, 34, 113
, 117, 105, 101, 116, 34, 125]

**Comment by mp-loki** [comment]
What is the payload that you are trying to send through the gateway? It looks like it tries to decode JSON and fails

**Comment by mamanso** [comment]
JSON
Like this
{"deviceId":"68:C6:3A:D5:3C:F0","WiFiRSSI":-59,"timestamp":"2018-09-13 12:23:48","temperature":"22.20","humidity":"67.20","pressure":"1025.29","luminosity":"523","heatIndex":"72.01","motion":"motion detected","soundNoise":"quiet"}

There are any parameter to estabish the data type that gateway must retrieve?

**Comment by mp-loki** [comment]
I see that your timestamp is a formatted value, not a raw value. Have you configured the tsFormat in your mapping file (or GUI)? The gateway must know how to interpret the string "2018-09-13 12:23:48".

In your case the mapping should be smth like:
```json
"timeseries": [
              {
                "type": "double",
                "key": "humidity",
                "value": "${$.humidity}",
                "ts": "${$.timestamp}",
                "tsFormat": "yyyy-MM-dd HH:mm:ss"
              },
              {
                "type": "double",
                "key": "pressure",
                "value": "${$.pressure}",
                "ts": "${$.timestamp}",
                "tsFormat": "yyyy-MM-dd HH:mm:ss"
              },
             ...
             # more TS mappings here
            ]
```

**Comment by mamanso** [comment]
This is the aupdated configuration inport by GUI interface.

{"configuration":"[{\"id\":\"mqtt\",\"type\":\"MQTT\",\"configuration
\":{\"brokers\":[{\"host\":\"iot.eclipse.org\",\"port\":1883,\"ssl\":false,\"retryInterval\":3000,\"credentials\":{\"type\":\"anonymous\"},\"mapping\":[{\"topicFilter\":\"piml/nodemcu\"
,\"converter\":{\"attributes\":[],\"timeseries\":[{\"type\":\"double\",\"key\":\"temperature\",\"value\":\"${$.temperature}\",\"ts\":\"${$.timestamp}\",\"tsFormat\":\"yyyy-MM-dd HH:mm:s
s\"},{\"type\":\"double\",\"key\":\"humidity\",\"value\":\"${$.humidity}\",\"ts\":\"${$.timestamp}\",\"tsFormat\":\"yyyy-MM-dd HH:mm:ss\"}],\"type\":\"json\",\"deviceNameJsonExpression\
":\"${$.deviceId}\",\"deviceTypeJsonExpression\":\"${$.deviceId}\",\"filterExpression\":\"500\"}}],\"connectRequests\":[],\"disconnectRequests\":[],\"attributeRequests\":[],\"attributeU
pdates\":[],\"serverSideRpc\":[]}]}}]"}

This is the JSON publish on MQTT broker
{"deviceId":"68:C6:3A:D5:3C:F0","WiFiRSSI":-64,"timestamp":"2018-09-14 12:43:43","temperature":"21.20","humidity":"80.00","pressure":"1023.13","luminosity":"144","heatIndex":"70.64","motion":"standby","soundNoise":"quiet"}

And this is the content that appear in the log file telling that Failed to de code message:
[123, 34, 100, 101,
 118, 105, 99, 101, 73, 100, 34, 58, 34, 54, 56, 58, 67, 54, 58, 51, 65, 58, 68, 53, 58, 51, 67, 58, 70, 48, 34, 44, 34, 87, 105, 70, 105, 82, 83, 83, 73, 34, 58, 45, 54, 52, 44, 34, 11
6, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 34, 50, 48, 49, 56, 45, 48, 57, 45, 49, 52, 32, 49, 50, 58, 48, 53, 58, 50, 53, 34, 44, 34, 116, 101, 109, 112, 101, 114, 97, 116, 117,
 114, 101, 34, 58, 34, 50, 49, 46, 50, 48, 34, 44, 34, 104, 117, 109, 105, 100, 105, 116, 121, 34, 58, 34, 56, 48, 46, 48, 48, 34, 44, 34, 112, 114, 101, 115, 115, 117, 114, 101, 34, 58
, 34, 49, 48, 50, 51, 46, 49, 51, 34, 44, 34, 108, 117, 109, 105, 110, 111, 115, 105, 116, 121, 34, 58, 34, 49, 52, 50, 34, 44, 34, 104, 101, 97, 116, 73, 110, 100, 101, 120, 34, 58, 34
, 55, 48, 46, 54, 52, 34, 44, 34, 109, 111, 116, 105, 111, 110, 34, 58, 34, 115, 116, 97, 110, 100, 98, 121, 34, 44, 34, 115, 111, 117, 110, 100, 78, 111, 105, 115, 101, 34, 58, 34, 113
, 117, 105, 101, 116, 34, 125]

**Comment by Karabiy** [comment]
there is now a new ThingsBoard IoT Gateway written in Python. You can refer to this link regarding those: https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/
this should fulfill your needs.
