### ISSUE TITLE
Managing Customers or Tenants rights

### ISSUE THREAD

**Issue by JereInlisol** [thingsboard/thingsboard#10759]
Hi! I am wondering if I can restrict what different tenants can see on their Thingsboard account. As a system admin, can I restrict, for example, rule chains and assets? Because I don't want my customers to be able to see them.

**Comment by ashaforost** [comment]
If you use ThingsBoard Professional Edition, you can do so. Move the tenant users to a different user group (not 'tenant administrators' or 'tenant users') and assign this new group a generic role, allowing them to see the selected resources only. See [RBAC article](https://thingsboard.io/docs/pe/user-guide/rbac/) for more information.

A Community Edition is much simpler and does not have the functionality to limit the resources available to a tenant admin.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
