### ISSUE TITLE
Can the content here be internationalized (can it support Simplified Chinese)?

### ISSUE THREAD

**Issue by ultimate-smile** [thingsboard/thingsboard#10763]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/thingsboard/thingsboard/assets/102498318/406651fb-7e8d-470d-b684-270785c16c1a)
Can the markdown here be internationalized (can it support Simplified Chinese)?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ssakharova** [comment]
Hello @ultimate-smile,

Could you please tell me if this feature request is relevant to you?
If so, please provide **more details** so I can pass this information on to the developers.

**Comment by ssakharova** [comment]
Closed due to inactivity.
