### ISSUE TITLE
Installation issue on Windows10 - Cassandra Timed Out

### ISSUE THREAD

**Issue by mennaifer** [thingsboard/thingsboard#1076]
HI All,
I'm installing Thingsboard 2.1.0 on Windows10 connecting to Cassandra.
Cassandra seems to run ok on port 9042.
The installation of Thingsboard failed at 'Installing Cassandra Database schema ..' with an error 127.0.0.1:9042 Timed Out.

Attached the logs
Thanks for support.

[install.log](https://github.com/thingsboard/thingsboard/files/2376910/install.log)
[thingsboard.wrapper.log](https://github.com/thingsboard/thingsboard/files/2376912/thingsboard.wrapper.log)

**Comment by vparomskiy** [comment]
Did you try to re-run install.bat script?

**Comment by mennaifer** [comment]
Yes, i tried. Same error

**Comment by mennaifer** [comment]
I reinstalled the entier Windows10 and the installation works fine with the second tentative of install.bat.
Thanks for support
