### ISSUE TITLE
Reset user password from sysadmin

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#10771]
**Component**

 * Generic

**Description**
I would like to be able to change or reset a user's password from the SYS_ADMIN role, without needing to know the user's password. I don't want the user to click the "I forgot my password" button, I want to manually reset the password.

Thank you very much in advance

**Comment by epalchenko** [comment]
Hello @Borch97 

In case the password to the System Admin account was lost, you can restore it to the default - sysadmin
To do so, you need to go to your PSQL console:

`psql -U postgres -h localhost -d thingsboard`
And run this query:
`update user_credentials SET password = '$2a$10$YMyxoU0hMOLmd9D7tz/dQeDY3fkXRAv8C023F6hzx2gVB9dTBUpq6' WHERE user_id=(select id from tb_user where authority = 'SYS_ADMIN');`
