### ISSUE TITLE
Show in alarms widget, devices and assets at the same time

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#10775]
I would like to show in the alarms widget, where alarms for both assets and devices are listed. Currently it only allows you to choose one alias and these do not allow you to select a combination of assets and devices.

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
I guess it is some kind of hack but you can create relation between tenant/user/customer and device/asset and then use relation query for your alias.

**Comment by epalchenko** [comment]
Hello @Borch97,
You are right; the platform does not have the functionality you described. For your case, you need to add two separate alarm widgets, one for devices and one for assets, or develop a custom widget that can display devices and assets together. 
You can also use the method suggested in the previous message.
For example, add a relation between the customer and the device/asset:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/5a33dda5-2ecc-4a13-8e53-f76e0f5b0461)
Use Propagate alarm to related entities in Alarm rule:
![Screenshot_104](https://github.com/thingsboard/thingsboard/assets/136599093/000aeaa6-c87b-4803-bce1-b7340494b0a6)
Add alias:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/94573230-b667-4db3-a07d-88552a128e5f)
This is what you get as a result in the Alarms table widget:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/211c324e-e9a9-45d9-b946-fb675033217a)
