### ISSUE TITLE
Devices from Customer

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10789]
Hello!! I need help.

I have an entity table containing all of the customers. Clicking on the customers (the row) I go to a new dashboard state, where there's a new entity table. I want to show all devices from that selected customer. How can I do this?

**Comment by ashaforost** [comment]
@kurch00 

You can create relations between a customer and their devices. After it's done, you can use the device search query alias on a widget to see all devices related to a selected customer.

**Comment by kurch00** [comment]
It works!! Thank youuu...

Just one more question! Do you know if it's possible to create those relations automatically?

**Comment by ashaforost** [comment]
Yes, for newly created devices, you can use the create relation rule node to automatically create a relation from said device to its customer. For devices that are already present, you can do basically the same logic in the rule chain and trigger it for all customers' devices via the scheduler.
![image](https://github.com/thingsboard/thingsboard/assets/47900737/021b0c18-ca7c-47cc-9c19-ce5b458fb1be)

![image](https://github.com/thingsboard/thingsboard/assets/47900737/8f5de7ae-e6fe-4a74-abda-17854d862e9f)

**Comment by kurch00** [comment]
You saved me!! thank uu

**Comment by anautinirea** [comment]
> Yes, for newly created devices, you can use the create relation rule node to automatically create a relation from said device to its customer. For devices that are already present, you can do basically the same logic in the rule chain and trigger it for all customers' devices via the scheduler. ![image](https://private-user-images.githubusercontent.com/47900737/331513640-021b0c18-ca7c-47cc-9c19-ce5b458fb1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzk3MTgsIm5iZiI6MTcyNjA3OTQxOCwicGF0aCI6Ii80NzkwMDczNy8zMzE1MTM2NDAtMDIxYjBjMTgtY2E3Yy00N2NjLTljMTktY2U1YjQ1OGZiMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE4MzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjE1NmFmOTU5NjE4Mjg1ZDNhZTZjMzNlMzU4ODRhNjNiNWFlYWJkZDhiMDkyMjg4NjJkMzE0MzcyMWQwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYaRnNN4pkOO_VmIoVo6GDI4HyrG-8OjrvHSMzE_M6I)
> 
> ![image](https://private-user-images.githubusercontent.com/47900737/331512299-8f5de7ae-e6fe-4a74-abda-17854d862e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzk3MTgsIm5iZiI6MTcyNjA3OTQxOCwicGF0aCI6Ii80NzkwMDczNy8zMzE1MTIyOTktOGY1ZGU3YWUtZTZmZS00YTc0LWFiZGEtMTc4NTRkODYyZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE4MzAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjM1ODIzNjM4OWM2ZTY2NDJjY2IyOWE2MTM5ZDI4YTNkOGMxNjg1NWVlN2RiZTYxOThmNTA5ZTc2ZjU5MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XN5qdJdHe3tsUErXbKLoSxUdu6T3gQaCO0mHqVmIy3k)

Hi @ashaforost, do you mind explaining how the nodes here work? 
I have the exact issue and I am trying to replicate this Rule Chain but my version is Thingsboard PE 3.3.2 and the nodes are slightly different (outdated). Thank you in advance
