### ISSUE TITLE
How to read response from "sendTwoWayRpcCommand(entityId,requestBody)"

### ISSUE THREAD

**Issue by hl1369** [thingsboard/thingsboard#10788]
Hello dears,

i have a problem for reading response in method in "sendTwoWayRpcCommand(entityId,requestBody)" in  "Latest Value" type widgets.
I want to press a button, wait for the device to response and display the data returned from the device in the widget.

Is there a way to solve this specification?

**Comment by devaskim** [comment]
```
sendTwoWayRpcCommand(...).subscribe(
    response => {
        console.log('Response', response);
    },
    error => console.error('Error', error );
);
```

**Comment by hl1369** [comment]
> ```
> sendTwoWayRpcCommand(...).subscribe(
>     response => {
>         console.log('Response', response);
>     },
>     error => console.error('Error', error );
> );
> ```

Thank you @devaskim i change to this model and work well:
deviceService.sendTwoWayRpcCommand(entityId,requestBody)
                            .subscribe(
                        function success(response) {
                            console.log("send Set ok");
                            console.log("Response payload:", response); 
                        },
                        function fail(rejection) {
                            console.log("timeout detect Set");  
                        }
                    );

**Comment by hl1369** [comment]
completed
