### ISSUE TITLE
Is it possible to connect the camera video stream to thingsboard for playback?Your title here

### ISSUE THREAD

**Issue by AldirchEugene** [thingsboard/thingsboard#10784]
Is it possible to connect the camera video stream to thingsboard for playback?

**Comment by xiaobai1017** [comment]
应该可以用html widgets实现

**Comment by ssakharova** [comment]
Hello @AldirchEugene,

You should use the HTML Card widget with the appropriate configuration.
Here is an example of how you can customize the HTML Card widget to display video streaming on the dashboard by inserting these lines of code into the HTML field:

```
<iframe width="100%" height="100%" id='id_stream_stream_***' src='https://www.youtube.com/embed/tgbNymZ7vqY' allowfullscreen></iframe>
``` 
![image](https://github.com/thingsboard/thingsboard/assets/98035385/b431d9de-db6d-42f9-83c2-ab08bdee9cd0)

Best regards,
Sofiia

**Comment by AldirchEugene** [comment]
> 你好@AldirchEugene，
> 
> 您应该使用具有适当配置的 HTML Card 小部件。 以下是示例，说明如何通过在 HTML 字段中插入以下代码行来自定义 HTML Card 小部件以在仪表板上显示视频流：
> 
> ```
> <iframe width="100%" height="100%" id='id_stream_stream_***' src='https://www.youtube.com/embed/tgbNymZ7vqY' allowfullscreen></iframe>
> ```
> 
> ![图像](https://private-user-images.githubusercontent.com/98035385/330416706-b431d9de-db6d-42f9-83c2-ab08bdee9cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NTg1MTIsIm5iZiI6MTcxNjg1ODIxMiwicGF0aCI6Ii85ODAzNTM4NS8zMzA0MTY3MDYtYjQzMWQ5ZGUtZGI2ZC00MmY5LTgzYzItYWIwOGJkZWU5Y2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAxMDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NTlhYjUxMTgxNjE1ZDI2Y2Q5ZGVjZTA5NGVlNjRhOWJhNDU2MWVhNWM5MmU4NTlhYjQ3MzhhMDE5NzkwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._g4d6MKC9OcfLmssBZob4dPP1Dh1_biLwytA8H_XXW4)
> 
> 谨致问候， 索菲亚

ok，thank you very much
