### ISSUE TITLE
Tablet and Laptop Responsiveness

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10782]
Hello,

I have been working with ThingsBoard since September and have developed over 50 dashboards, most of which are in production with clients. However, I am encountering challenges with responsiveness, particularly in complex dashboards that include markdown, maps, entity hierarchies, and tables. Achieving responsiveness in web applications is typically straightforward, but in ThingsBoard, it proves to be quite difficult.

I have worked with VW, VH, etc., but no option seems to satisfy the platform for achieving responsiveness in complex dashboards in ThingsBoard. I have to use enormous widgets in order for the different screens to adapt to them, but the problem is that on big screens, they become excessively large.

Example in a solution I developed:

Desktop: seems good
![image](https://github.com/thingsboard/thingsboard/assets/98624393/4b7afe7e-5107-4687-a874-0d9ec39fa374)

Laptop: starts to fail
![image](https://github.com/thingsboard/thingsboard/assets/98624393/b637b704-9777-43eb-bca5-5213f487d4c2)

Tablet: worse than the previous one
![image](https://github.com/thingsboard/thingsboard/assets/98624393/f00f6061-0e9e-4b3a-b91b-f0e9232fc4cb)

What is the way you guys you recommend to deal with this problem?

Thanks!

**Comment by maaaaaaaaaaaaaan** [comment]
What version are you running? Look similar to a behavior I have seen in public dashboard.
If its the same issue its solved in 3.6.3PE

**Comment by omkarfutureos** [comment]
Hi @nicovon24,
Even i am facing the same issue with handling responsiveness in thingsboard. Let me know if you were able to come up with any solution, would really appreciate it. Thanks!

**Comment by akash009-ux** [comment]
same issue any update ???

**Comment by nicovon24** [comment]
> same issue any update ???

The responsiveness keeps bad. It is a pity with all the potential of the platform and the competition having fixed this with a couple lines of css

**Comment by maaaaaaaaaaaaaan** [comment]
> What version are you running? Look similar to a behavior I have seen in public dashboard. If its the same issue its solved in 3.6.3PE

I wrote this last year. But will take it back. I also still have problems with responsiveness in mobile view. Very annoying!

A workaround that seems to work in most cases is to keep "Layout settings: Default breakpoint" same in all dashboard state that is used. And the sum of all height of the widgets that is visible in mobile view the same.


<img width="930" height="690" alt="Image" src="https://github.com/user-attachments/assets/a266387b-3d39-4df7-b6e4-9c88ed3efed6" />

<img width="729" height="489" alt="Image" src="https://github.com/user-attachments/assets/70497b41-c736-4a2a-b3c3-d09fab94f2ea" />
