### ISSUE TITLE
when delete device API is called in batches，Thingboard can't get connection  from connection pool

### ISSUE THREAD

**Issue by ten2net** [thingsboard/thingsboard#1079]
The API of the delete device is called in batches, but when the device to be deleted does not exist multiple times, the Thingboard cannot work because the connection cannot be obtained from the database connection pool.

**Comment by ashvayka** [comment]
How many devices you are trying to delete at once?

**Comment by ten2net** [comment]
768

**Comment by vparomskiy** [comment]
I'm not able to reproduce it on my local environment. Does this issue still valid?
