### ISSUE TITLE
character limit in decoders and console.log

### ISSUE THREAD

**Issue by MartinCouadeau** [thingsboard/thingsboard#10792]
i noticed that there is a limit of 50.000 characters in a decoder

![limit](https://github.com/thingsboard/thingsboard/assets/51155232/d89a9d61-3b28-4796-aa5d-958c9ed7839b)

is there a way for me to change this in the configuration or its some kind of feature i should ask for?

also, is there a way to enable the function console.log() or is there another function i could use? its really hard to debbug large decoders without that functionality

![console](https://github.com/thingsboard/thingsboard/assets/51155232/b2ba595a-6733-4cfc-a559-224bf582f8cf)

**Comment by devaskim** [comment]
You need to change this server option
https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L838
