### ISSUE TITLE
thingsboard REST API taking too much time to get history data

### ISSUE THREAD

**Issue by swapon-think** [thingsboard/thingsboard#10800]
We're facing issue with data fething using REST API and as well as from dashboard. We are trying to get history data for device  using different interval like 1 day, 7 day and 30 days. It's taking 10 or more seconds, even sometimes it takes 30 seconds or more and also failed to load many times.

I'm using thingsboard professional edition and our current thingsboard version is v.3.3.0

sample url: https://[domain name here]/api/plugins/telemetry/DEVICE/a05e8220-19b4-11ee-8f45-97d7eca13f17/values/timeseries?keys=1_unit,2_Unit,3_Unit&startTs=1714500000000&endTs=1715831823357&interval=86400000&orderBy=DESC&intervalType=MILLISECONDS&agg=MAX

We need all data in request and having issue to get the data using REST API. I would greatly appreciate any updates.

**Comment by mykhailokornieiev** [comment]
Closed this ticket due to inactivity.
