### ISSUE TITLE
What is "profile type" of a device profile ?

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#10805]
**Component**

* Device profile

**Description**
1.
The device profile list has a column named "profile type" :
![image](https://github.com/thingsboard/thingsboard/assets/151620289/8c7cf455-bce6-4694-bf59-bbec49875865)

But I can't find anywhere to define "profile type" ???
No choice exist when creating a new device profile, no dropdown list or similar input in device profile form...
I don't find explanation in documentation or help...

**What is it ?**

2.
Linked to this, I try to use the "device profile switch" rule chain box.
When I want to set a new link to antother box, I get the choice between:  
* default
* Failure

![image](https://github.com/thingsboard/thingsboard/assets/151620289/db66f93c-b34b-4127-8b2f-a2f8376eb9dd)

Where are my profiles device that I have created ?
I can add it manually, and it seems to work...
![image](https://github.com/thingsboard/thingsboard/assets/151620289/fa21d89e-8b4c-4cc1-ad53-4c536199eeca)

**Is there any link with my main question "profile type" ???**

Thank you.

**Environment**
 * OS:  Windows 10
 * ThingsBoard:  Cloud v3.64.1PAAS
 * Browser: Chrome Version 124.0.6367.201 (Build officiel) (64 bits)

**Comment by devaskim** [comment]
2. Device Profile Switch node doesn't support autocomplete, so you need type your profile name, not type, on your own, e.g. `sim_card`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
