### ISSUE TITLE
"additionalInfo" section of the "User" swagger definition seems not consitent 

### ISSUE THREAD

**Issue by gigi130358** [thingsboard/thingsboard#1081]
The API swagger definition downloaded by https://mySite//v2/api-docs?group=thingsboard define the"User" structure as:
"User":{"type":"object","properties":{**"additionalInfo":{"type":"string"}**,"authority":{"type":"string","enum":["SYS_ADMIN","TENANT_ADMIN","CUSTOMER_USER","REFRESH_TOKEN"]},"createdTime":{"type":"integer","format":"int64"}
where the "additionalInfo" is a simple string.
![image](https://user-images.githubusercontent.com/42691425/45625951-6bb5d080-ba8e-11e8-8ff0-3a1849665e01.png)

Swagger#UI  give instead a  "additionalInfo" structure like this:
![image](https://user-images.githubusercontent.com/42691425/45625189-9141da80-ba8c-11e8-8ca5-f99825515f3c.png)
This is also confirmed calling the "AuthControllerApi.getUserUsingGET()"  method generated by swagger-codegen based on the above swagger json definition, that generate a server answer containing an "additionalInfo"  structure like this:
"additionalInfo":{"lang":"en_US","defaultDashboardId":null,"description":"User"}
The different structure between what is defined in swagger json definition and the reply payload, of course generate an error.
Why the swagger json definition is different from the real structure payload reply ?
Should I use some other way to get the correct swagger json definition ?
Thanks

**Comment by ashvayka** [comment]
Hi @gigi130358 . Please submit changes to the source code to fix it if you are interested

**Comment by felixd** [comment]
Still open problem ;)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
