### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10819]
I have 3 dashboard states. The first one contains a table that shows all customers. The second (clicking on a row) contains all devices from the selected customer. And the third contains general information about the selected device. How can I create a back button on the third dashboard state to the second dashboard state, but without losing the information, such as all devices from the previously selected customer?

**Comment by nicovon24** [comment]
That's true, i have a button which executes a history.back() but the update of the last state loses, it's quiet frustating, if anyone know how to keep the state despite the history.back() would be really useful!

**Comment by mariezg** [comment]
Hi @nicovon24 , you follow the tips below :

1. Create a Markdown widget and add the device alias / info in the Data source
2. In the Appearance Tab of the Widget, activate Use Markdown/HTML value function and use this code as a base

`return '<div class="header" fxLayout="row" fxLayoutAlign="center center" fxLayoutGap="0px">' +

        
        '<div class="wf-buttons" fxFlex fxLayout="row" fxLayoutAlign="center " style="padding-right: 0px;">' +

             '<button mat-raised-button color="primary" id="close">' +
              '<mat-icon>highlight_off</mat-icon>' +
              'close' +
            '</button>'
        
        '</div>'
        +
'</div>';
        
` 

Finally in the Action Tab of the Widget add an action "On HTML element Click" with "close" name and enable set entity from widget
![Uploading Screenshot_2024-05-22_14-56-20.png…]()

I hope it helps

**Comment by mariezg** [comment]
Perfect, @kurch00 happy that it works for you.
You can also inclue the code snippet I gave into your menu if you want :)

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by nicovon24** [comment]
Hello @Ultrazombie @mariezg @kurch00 did you find a way to make a back function with a custom action without losing my current stateParams? 

The update dashboard state is good but if i have different ways to access a dashboard how i validate?

I could store a previousDashboardState but should change and validate all my back buttons and also my redirect to another dashboard functions and they are several, thanks!!
