### ISSUE TITLE
Searching dashboards as a customer with entityquerycontroller

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard#10812]
Hello, 

I was tying out some API endpoints and i came across a bug. 
1. I logged in as a customer in the swagger-ui
2. I searched the entity-query-controller, in the endpoint api/entitiesQuery/find
3. I tried to retrieve all the dashboards that I'm allow to view as a client with the following query

{
  "entityFields": [],
  "entityFilter": { "type": "entityType", "entityType": "DASHBOARD"},
  "keyFilters": [],
  "latestValues": [],
  "pageLink": { "page": 0, "pageSize": 10}
}

I get the following error. If i do the same as a tenant this query will work.

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/935407b6-8b05-4687-846b-5c4b72829eab)

I might be wrong but I understand that the problem is related with dashboards not having a customer_id field in the database

**Comment by ashaforost** [comment]
Hi @CalmNite 

I tested your query on v3.6.4, and it works fine:
![image](https://github.com/thingsboard/thingsboard/assets/47900737/66483123-a0f2-482a-891e-5bc211caf661)
The same works with the `/api/entitiesQuery/find` request.

What's your thingsboard version? Is the installation valid? Maybe there were errors during an upgrade?

**Comment by CalmNite** [comment]
thanks for the answer @ashaforost  

I have installed a new version in a different environment following the documentation in your web. 
https://thingsboard.io/docs/user-guide/install/docker/

I have selected the option for kafka. I'm using the image thingsboard/tb-postgres and done all the steps which are indicated in the provided url.
![Captura de pantalla de 2024-05-17 16-02-18](https://github.com/thingsboard/thingsboard/assets/151906929/5b310cb6-c4bd-4738-b719-6521e4061f1a)

In this version i get the same error but with different log. I have also tried in older version and get a similar error.

![Captura de pantalla de 2024-05-17 15-57-35](https://github.com/thingsboard/thingsboard/assets/151906929/b80e994c-c358-432f-8c8b-52b579dcda0b)

Are you logging in as a tenant or a customer?
Am i doing something wrong?

**Comment by CalmNite** [comment]
i have been checking the source code and i came with the answer myself. i added that code to the defaultPermissionQuery in DefaultEntityQueryRepository and now the query works perfectly

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/b990dc36-6979-461c-b858-fb98e51b7119)

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/36c259f1-939b-454b-9d5d-fe6ea5229e25)

**Comment by ashaforost** [comment]
@CalmNite  

This bug was reported and verified, and the fix is planned for v3.7-3.7.1. 
Thank you for reporting the issue and providing a solution!

**Comment by ashaforost** [comment]
I'm closing this issue since the fix was released. Feel free to reopen if you have any questions.
