### ISSUE TITLE
I can not find gen.MsgProtos class.

### ISSUE THREAD

**Issue by LoanHanu** [thingsboard/thingsboard#10825]
I'm gonna build thingsboard from source code v3.6.4 using IntelliJ in Windows 10.
But every code line 'import org.thingsboard.server.common.msg.gen.MsgProtos;' gives error.
I have tried to find the package 'gen' from project tree, but can't find as well.
Please help me in fixing this issue.

![img_20240520](https://github.com/thingsboard/thingsboard/assets/109542346/2db3a5df-df33-4a3e-bea7-ed02755e17f5)

**Comment by ViacheslavKlimov** [comment]
Hello, check this out https://github.com/thingsboard/thingsboard/issues/9464
