### ISSUE TITLE
docker installed version not using postgres ?

### ISSUE THREAD

**Issue by berialcheng** [thingsboard/thingsboard#1082]
I have installed tb following the guide here,  https://thingsboard.io/docs/user-guide/install/docker/

But when i want to check the telemetry data in database, i cant find anything in postgres nor in cassandra.

After digging into the docker exection context, i found following Spring configuation, as we can see the postgres configuration section is commended deliberately , am i missing something, or could anyone please help me upon actually enabling postgres storage here.

`/etc/thingsboard/conf/thingsboard.yml`
![image](https://user-images.githubusercontent.com/2362847/45632553-2ca86f00-bad0-11e8-8bc6-138745b8b80c.png)

**Comment by vparomskiy** [comment]
By default, HSQLDB is used. You will need to configure preferred database using this guide:
https://thingsboard.io/docs/user-guide/install/linux/#optional-configure-thingsboard-to-use-the-external-database

**Comment by berialcheng** [comment]
thanks @vparomskiy, it's helpful. i see what u means, would have a try. 

But it be better if the docker image itself could control the vendor through environment, or could be more specific on the documentation itself, because in the installation by docker guide, it seems missing the important information upon the database selection .
