### ISSUE TITLE
How to remove link underline in thingsboard.

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#10826]
I am unable to hide underline for anchor tag even after I used Css property to remove the underline.
U can see in the image css code

![Screenshot from 2024-05-20 11-32-13](https://github.com/thingsboard/thingsboard/assets/109786898/2982fe8f-f16c-4ab3-a6e1-1e4df0119d21)

**OS
Ubuntu 22.04

**Comment by CalmNite** [comment]
try adding in your css

border-bottom: none;

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/b41feb7e-d528-487f-9cd2-3ab3e8467a32)

**Comment by devaskim** [comment]
@KashifAhmd Sometimes only `!import` helps

**Comment by KashifAhmd** [comment]
> try adding in your css
> 
> border-bottom: none;
> 
> ![imagen](https://private-user-images.githubusercontent.com/151906929/331978422-b41feb7e-d528-487f-9cd2-3ab3e8467a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDE4NjAsIm5iZiI6MTcxNjIwMTU2MCwicGF0aCI6Ii8xNTE5MDY5MjkvMzMxOTc4NDIyLWI0MWZlYjdlLWQ1MjgtNDg3Zi05Y2QyLTNhYjNlODQ2N2EzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMDM5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWY4MzQ0NGU5ODg4YmI3MDhlNWU3YmQ1NjRkMGVkMGY5MDE4MzgwMjBiYzYwYjk5OGY4YTg4NzdjZWJiN2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMkTEBCSljGQ4JNUiowDRelMTTocJCXd_Ah_SzYRu3Y)

Thank u so much, I got this.

**Comment by KashifAhmd** [comment]
> @KashifAhmd Sometimes only `!import` helps, i.e. `text-decoration: none !important;`

Thank you @devaskim for your reference, I tried this also but it didn't work using !important because I was getting a border-bottom there by default.

So the first reference by @CalmNite has been worked.

Thanks again for your support.
