### ISSUE TITLE
docker mkdir: cannot create directory ‘/data/db’: Permission denied

### ISSUE THREAD

**Issue by DriftingShadows** [thingsboard/thingsboard#10827]
**Describe the bug**
On a clean Ubuntu install of 24.04, the following error is shown in the docker logs after following the instructions at [here](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka).

```
mkdir: cannot create directory ‘/data/db’: Permission denied
The files belonging to this database system will be owned by user "thingsboard".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/db ... initdb: error: could not create directory "/data/db": Permission denied
pg_ctl: database system initialization failed
Starting Postgresql...
pg_ctl: directory "/data/db" does not exist
Connecting to Postgres, 300 attempts left...
Connecting to Postgres, 299 attempts left...
Connecting to Postgres, 298 attempts left...
```

**To Reproduce**
1. Install docker
2. Follow instructions to install thingsboard for docker on ubuntu
3. docker compose up -d

**Additional context**
Please feel free to add any other context about the problem here.
This issue only occurs when using the mounted volumes for data and logs. I have done the chown -R 799:799 for both folders. I have also followed [these](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) instructions. When executing ls -lh to view permissions for the /data folder in the container, it shows the following
```
drwxrwxr-x   2 nobody nogroup 4.0K May 20 06:42 data
```

**Comment by jk4e** [comment]
Same error as @DriftingShadows. I have tried several times. Always get this error: 

```
  2024-05-23 21:23:02 mkdir: cannot create directory ‘/data/db’: Permission denied  
  2024-05-23 21:23:02 The files belonging to this database system will be owned by user "thingsboard".  
  2024-05-23 21:23:02 This user must also own the server process.  
  2024-05-23 21:23:02   
  2024-05-23 21:23:02 The database cluster will be initialized with locale "C.UTF-8".  
  2024-05-23 21:23:02 The default database encoding has accordingly been set to "UTF8".  
  2024-05-23 21:23:02 The default text search configuration will be set to "english".
  2024-05-23 21:23:02 
  2024-05-23 21:23:02 Data page checksums are disabled.
  2024-05-23 21:23:02 
  2024-05-23 21:23:02 creating directory /data/db ... initdb: error: could not create directory "/data/db": Permission denied
  2024-05-23 21:23:02 pg_ctl: database system initialization failed
  2024-05-23 21:23:02 Starting Postgresql...
  2024-05-23 21:23:02 pg_ctl: directory "/data/db" does not exist
  2024-05-23 21:23:02 Connecting to Postgres, 300 attempts left...
  2024-05-23 21:23:03 Connecting to Postgres, 299 attempts left...
  2024-05-23 21:23:05 Connecting to Postgres, 298 attempts left...
  2024-05-23 21:23:06 Connecting to Postgres, 297 attempts left...
```
I have checked the permissions of the folders (with `ls -ld`):
```
xxx@xxx:~$ ls -ld .mytb-logs
drwxrwxr-x 2 799 799 4096 May 23 20:51 .mytb-logs
xxx@xxx:~$ ls -ld .mytb-data
drwxrwxr-x 2 799 799 4096 May 23 20:51 .mytb-data
```

My version of OS and docker:
- OS: Linux Mint 21.3 Virginia (Ubuntu)
- Docker version 26.1.3

I have tried:
- build from docker compose file,
- Docker Hub: Pull and Run

Maybe someone can help us solve this problem. That would be great. Thanks for your help!

**Comment by trikimiki** [comment]
hi!
i have just tested the latest tb-postgres, all should be working as per guide
share your docker compose file

**Comment by DriftingShadows** [comment]
> Same error as @DriftingShadows. I have tried several times. Always get this error:
> 
> ```
>   2024-05-23 21:23:02 mkdir: cannot create directory ‘/data/db’: Permission denied  
>   2024-05-23 21:23:02 The files belonging to this database system will be owned by user "thingsboard".  
>   2024-05-23 21:23:02 This user must also own the server process.  
>   2024-05-23 21:23:02   
>   2024-05-23 21:23:02 The database cluster will be initialized with locale "C.UTF-8".  
>   2024-05-23 21:23:02 The default database encoding has accordingly been set to "UTF8".  
>   2024-05-23 21:23:02 The default text search configuration will be set to "english".
>   2024-05-23 21:23:02 
>   2024-05-23 21:23:02 Data page checksums are disabled.
>   2024-05-23 21:23:02 
>   2024-05-23 21:23:02 creating directory /data/db ... initdb: error: could not create directory "/data/db": Permission denied
>   2024-05-23 21:23:02 pg_ctl: database system initialization failed
>   2024-05-23 21:23:02 Starting Postgresql...
>   2024-05-23 21:23:02 pg_ctl: directory "/data/db" does not exist
>   2024-05-23 21:23:02 Connecting to Postgres, 300 attempts left...
>   2024-05-23 21:23:03 Connecting to Postgres, 299 attempts left...
>   2024-05-23 21:23:05 Connecting to Postgres, 298 attempts left...
>   2024-05-23 21:23:06 Connecting to Postgres, 297 attempts left...
> ```
> 
> I have checked the permissions of the folders (with `ls -ld`):
> 
> ```
> xxx@xxx:~$ ls -ld .mytb-logs
> drwxrwxr-x 2 799 799 4096 May 23 20:51 .mytb-logs
> xxx@xxx:~$ ls -ld .mytb-data
> drwxrwxr-x 2 799 799 4096 May 23 20:51 .mytb-data
> ```
> 
> My version of OS and docker:
> 
> * OS: Linux Mint 21.3 Virginia (Ubuntu)
> * Docker version 26.1.3
> 
> I have tried:
> 
> * build from docker compose file,
> * Docker Hub: Pull and Run
> 
> Maybe someone can help us solve this problem. That would be great. Thanks for your help!

I solved the issue. It was related to [user namespaces](https://docs.docker.com/engine/security/userns-remap/). It seems to be enabled by default when installing docker desktop on ubuntu. For eg. I would need to set permission on host to be 100798 to get 799 ownership in the container.

**Comment by trikimiki** [comment]
:+1:
