### ISSUE TITLE
Toast Notifications in Custom Action and Markdown HTML

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10822]
Hello, anyone knows how to show a toast notification using widget content, ctx or any variable in for example a Custom Action HTML?
Thanks and have a good weekend!

**Comment by devaskim** [comment]
Details on toast API is [here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/widget-component.models.ts#L380)
```
    self.ctx.showToast('success', 'Toast message', 3000, 'top', 'center', 'dashboardRoot');
```
As a toast parent you can use either `self.ctx.toastTargetId` or `dashboardRoot` (last argument in the example)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
