### ISSUE TITLE
How to send MQTT message from Thingsboard server to device?

### ISSUE THREAD

**Issue by dungvv** [thingsboard/thingsboard#1083]
I have a Thingsboard server installed and several devices connected (an subscribed) to it. I want to build a REST API which will be called and then Thingsboard server will send MQTT message to all devices.
I was digging into source code but unfortunately I'm not familiar with actor model used in Thingsboard.
Please help me find the piece of code which send MQTT messages to devices? I just want to find the code so I can modify it to work with my use cases.
Thanks,

**Comment by vparomskiy** [comment]
Take a look at DeviceRpcService.processRpcRequestToDevice()
and also TbSendRPCRequestNode.onMsg (ctx.getRpcService().sendRpcRequest(...))

**Comment by dungvv** [comment]
Thank you very much. I found what I needed. 
I'll close this issue now 💃
