### ISSUE TITLE
OPC-UA browse name & display name

### ISSUE THREAD

**Issue by ashdam** [thingsboard/thingsboard#10830]
**Is your feature request related to a problem? Please describe.**
Actually its a fuctionality limitation we found in OPC-UA connector

**Describe the solution you'd like**
OPC-UA has 3 ways of referenting to a node: **nodeid** (unique), **browse** name (cannot be changed) and **display** name (can be changed by the user). 
Our company, uses the **tag path** like "root_node1_node2_node3" to refer to an specific device or variable it's important that this path does not vary. Using browse name you ensure path and naming doesn't vary over time (cannot be changed).

We would like to add the option to use display or browse name of variable/tag. TB currently have only "display name" available.

**Describe alternatives you've considered**
Using display name is OK but does not fulfil our requirements

**Additional context**
In UAExpert, typical OPC-UA client, you can see and use both.

![image](https://github.com/thingsboard/thingsboard/assets/169756398/2fec80f4-fa6a-4d83-92a4-b7e200991da2)

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by imbeacon** [comment]
Hi @ashdam,

This feature request relates to [ThingsBoard IoT Gateway](https://github.com/thingsboard/thingsboard-gateway), could you create it there, please?

**Comment by ashdam** [comment]
I have seen no "feature" label in iotgateway github but created my best ;)
You can close this :D

**Comment by ashdam** [comment]
thank you
