### ISSUE TITLE
Cannot start ThingsboardServerApplication

### ISSUE THREAD

**Issue by carsickcars** [thingsboard/thingsboard#1084]
I builded successful, but when I start Application, I get error:
![1](https://user-images.githubusercontent.com/7300422/45729093-7773d500-bbfd-11e8-824f-fe77cc738c19.png)

**Comment by carsickcars** [comment]
Is anyone can help me ?Thks!!

**Comment by vparomskiy** [comment]
If it is a new build, you need to create a DB schema.
https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#create-database-schema-and-populate-demo-data

**Comment by carsickcars** [comment]
> If it is a new build, you need to create a DB schema.
> https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#create-database-schema-and-populate-demo-data

Hi, I reclean and reinstall then it Started ThingsboardServerApplication in 64.779 seconds (JVM running for 73.495), I do not why. 
But I have a new issues, I put http://localhost:8080 
![3](https://user-images.githubusercontent.com/7300422/45735960-3212d000-bc1c-11e8-8b7d-ee942d1af6a2.png)

**Comment by vparomskiy** [comment]
Your build was not successful because of the dependency problem. Please take a look at this issue
https://github.com/thingsboard/thingsboard/issues/683

After you will change package version, please re-run 'mvn clean install -DskipTests' for rebuilding the project

**Comment by carsickcars** [comment]
Thank you very much,when I changed "ace-builds": "1.3.1", It works.
