### ISSUE TITLE
Count alarme by customer

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10842]
I have a "Markdown/HTML Card" widget with some informations, and I'd like to show the COUNT of alarms of a selected customer. How can I do that?

**Comment by devaskim** [comment]
Maybe this [Alarm Count API](https://thingsboard.cloud/swagger-ui/#/entity-query-controller/countAlarmsByQueryUsingPOST) will help you

**Comment by kurch00** [comment]
Tnkss!! I'll take a look
