### ISSUE TITLE
Disable Drag on Image Map Widget

### ISSUE THREAD

**Issue by mariezg** [thingsboard/thingsboard#10847]
This is not possible to disable the drag/move in Image Map Widget causing the map to go out of the allocated area. Is it possible to lock the view and prevent the user to drag the image with the pointer. 

This is possible to disable zoom/scrolling already in this widget so could you either add or fix this bug ? 

I am happy to do it on my own if I am provided with some guidances or roundabouts.

Thank you for your support on this request.

Kind regards

**Comment by mykhailokornieiev** [comment]
Hi
There is no standard functionality to disable dragging in Image Map, but you can try to use the next CSS snippet in Widget Settings → Widget Card → Card Style → Advanced Widget Style → Widget CSS:
```
.leaflet-grab {
 cursor: default !important;
}
.leaflet-pane.leaflet-map-pane {
 transform: none !important;
}
```

**Comment by mariezg** [comment]
Hi @mykhailokornieiev,

Thank you for the prompt response. Do I have to create a custom widget based on the image Map widget or can I add this CSS properties under the appearance CSS properties? 

Thank you again for your help

**Comment by mykhailokornieiev** [comment]
Hi
You can add it just under the widget card CSS properties.
![image](https://github.com/thingsboard/thingsboard/assets/115699895/533b3f7d-8032-49f2-a02a-50f324edd40d)

**Comment by mariezg** [comment]
Ok @mykhailokornieiev I will give it a try and confirm wether this solve my issue. Thanks for the screenshot and advise. Will keep you posted on this.
Best regards

**Comment by mariezg** [comment]
That works for me, thanks again ! I hope it will help others with same previous requests.
