### ISSUE TITLE
How to remove double quotes from a string in TBEL

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#10853]
I think the question was not clear, so I will add an explanation.

The input is JSON data like this

**Payload content**
{
	"id":"012345",
	"name": "abc"
}

**TBEL function Decoder** 
var data = decodeToJson(payload);  

var result = {
	   ID: data.id.replace('"', ''),
       NAME: data.name.replace('"', '') or  data.name.replaceAll('"', '')
   },
   .....
}

**<Output> -> Expected Output**
{
    "attributes": {
        "ID": 012345,     -> No quotes
        "NAME": abc     -> No quotes
    }
}

**<Output>   -> But it goes like this**
{
    "attributes": {
        "ID": "012345",
        "NAME": "abc"
    }
}

If it's "decodeToString(payload)", it works.

------------------
I want to remove double quotation marks from a double quotation value in TBEL.

The following does not seem to remove them

var text = "abcde";
var result = text.replace('"', '');

How can I do this?

TB PE v3.6.4

**Comment by devaskim** [comment]
`replace` function works as expected

![Скриншот 24-05-2024 141501](https://github.com/thingsboard/thingsboard/assets/86909129/003b8318-11e4-464b-a3a1-1cf031881c3d)

**Comment by h-takado** [comment]
> `replace` function works as expected

Thanks for the comment. But what I want to do is a little different. I've added an explanation.

**Comment by h-takado** [comment]
Self-understanding.
So what I want to do can't be done outside of the numbers.

**Comment by h-takado** [comment]
Thank you all.
