### ISSUE TITLE
trying to find devices from edge entity

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard#10857]
Hello, 

I am trying to create a entity alias in a dashboard. I have a list of edge entities displayed in a map. When i select one i go to a new dashboard state where i am trying to get all the related devices from edge. The edge instance is taken from dashboard state entity but i am failing to retrieve the devices.

I am using this alias 

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/904d8149-3bd2-4229-aeab-53f507e7ada4)

This are my edge devices

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/b3ed3f8b-6299-4c8a-bf07-c43a77c42633)

The edge and the devices are related in relation table as EDGE instead of the COMMON. Is there a way i can retrieve them with the alias without having to relate them again? 

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/5b3bbf00-72ee-45ba-808b-60a570b408b6)

Thanks for the help.

**Comment by ashaforost** [comment]
@CalmNite 

Does the 'state entity parameter name' match the one you set in the widget action that sets the Edge entity to a state?
In any case, please also show your widget action settings.

**Comment by CalmNite** [comment]
I have here this

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/4c76e2bc-5f99-4331-8e77-32a17a304bf1)

the alias

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/2f9ac5dd-6609-48cd-858a-21c7fe7c3414)

Is a custom widget

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/bc47a93a-0266-4085-96ad-5093608bd782)

**Comment by ashaforost** [comment]
@CalmNite 

Make sure the state entity parameter name is the same in the entity alias and widget action. You can test your solution by removing it from the entity alias and your custom code. 

Furthermore, I created a simple test of your code; it works fine on my side:
![image](https://github.com/thingsboard/thingsboard/assets/47900737/fce5d19f-b1e6-4bb6-8110-261fba628772)
![image](https://github.com/thingsboard/thingsboard/assets/47900737/a5ead7df-d156-4966-b580-cca1f0d7a882)
![image](https://github.com/thingsboard/thingsboard/assets/47900737/e543329f-aa3d-4399-a7f1-6cf1debbc91d)

**Comment by CalmNite** [comment]
Thanks for the help @ashaforost 

Yea it does work like you showed, the problem i had was when i created the relation to edge. How did assign the devices to the edge?

I have tried two ways. the first one is in this tab. 
![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/e0ec6b99-e300-4c0a-a766-ebd62d0a1270)

I select manage devices and i add from here the devices.

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/6ccddfd3-ed61-4dab-8b32-76260c0fb708)

If i follow this option i cant see the assigned devices.

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/fb5d5aee-addd-4047-aa3b-aa5f34c547af)

The seconds options is creating a relation from the edge plataform (i think i dont remenber well the process). In this case i can see in the edge relation tab the following, but in the other option it doesnt.

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/596b955b-9019-449a-bc8b-b5a0d482d423)

![imagen](https://github.com/thingsboard/thingsboard/assets/151906929/13619bd1-3bb2-4a8e-b529-24386d576b90)

**Comment by CalmNite** [comment]
I know the second option will work but why does the first one not work?. If there is the option to manage devices in the thingsboard platform why wont the relation create on its own?

**Comment by ashaforost** [comment]
In thingsboard, entity relations are implemented to provide a more robust option for the business use case setup. It allows you to connect entities that are related to each other in some logical way. See [Entities and relations](https://thingsboard.io/docs/user-guide/entities-and-relations/) doc. .
You can always automate the relations setup using the rule chain and the [create relation](https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#create-relation-node) rule node. 

If we're talking about edge-specific questions, I cannot help you with them as a member of thingsboard support. You can address your questions to the edge developers in the [thingsboard-edge](https://github.com/thingsboard/thingsboard-edge/issues) repository.

**Comment by CalmNite** [comment]
Thanks.
