### ISSUE TITLE
Error 404 Not Found during Trendz Installation with ThingsBoard CE

### ISSUE THREAD

**Issue by xang555** [thingsboard/thingsboard#10851]
# Component

- Installation

# Description

I have a problem with installing Trendz with ThingsBoard CE. I got this error message:

```bash
The request to the Thingsboard was failed:
Error during execution request: 
url = /api/whiteLabel/currentWhiteLabelParams cause = 404 Not Found from GET http://xxxxxx:8080/api/whiteLabel/currentWhiteLabelParams{"status":404,"message":"Not Found","errorCode":32,"timestamp":1716433825679}
```
How can I fix this?

# Environment

- OS: Ubuntu
- ThingsBoard: 3.6.4 (installed using Docker)
- Trendz: 1.11.0-RC7 (installed using Docker)

**Comment by ashaforost** [comment]
Hi @xang555 

The latest version of Trendz is 1.11.0-**RC17**; please try installing it instead of 1.11.0-**RC7**. Our Trendz developer commented that they fixed a similar issue before, but if the issue reproduces on the latest version, please let me know.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
