### ISSUE TITLE
Resource Library - How to use JS module type?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#10867]
**Component**

 * Generic

**Description**
In the Resource Library area one can specify resource type JS-module:  
![image](https://github.com/thingsboard/thingsboard/assets/25298332/74c89ba6-374d-42cb-882f-fe840a2446b8)

How should this be used?
Is this only possible in combination of OTA updates or LWM2M? Or can this also be used for custom widgets, e.g. to integrate resources from external JS libraries (instead of using public CDN urls)?

Unfortunately, I couldn't find any information about this in the documentation. You are forwarded directly to the LWM2M page.
https://thingsboard.io/docs/pe/reference/lwm2m-api/

**Environment**

 * ThingsBoard: 3.6.3
___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @mde2017 

The JS module resource is used precisely for the widget development. Here's a [thingsboard-extensions](https://github.com/thingsboard/thingsboard-extensions) repository with instructions on how to build and deploy your custom components.

**Comment by mde2017** [comment]
Hi @ashaforost ,

Thank you very much for your answer, that helps me a lot and answers the question.
