### ISSUE TITLE
Charts - Any way to 'cut' the graph when sensors are disconnected ?

### ISSUE THREAD

**Issue by myfreescalewebpage** [thingsboard/thingsboard#1086]
Hello,

I'm creating some dashboard for IoT sensors. I have installed TB v2.0.3 on my linux server. Is there any way with TB Charts to 'cut' the graph when no data are pushed for a while ?

In the following example, the sensor has been disconnected during several days. I have the following graph:

![graph](https://user-images.githubusercontent.com/16516760/45763753-7197e700-bc31-11e8-923b-e72f746dd23e.PNG)

I would like:

![expected](https://user-images.githubusercontent.com/16516760/45763836-aa37c080-bc31-11e8-9ba0-f453d7665b01.PNG)

Thanks,
Joel

**Comment by ashvayka** [comment]
Hi @myfreescalewebpage there is no such option at the moment. The only thing you can do is to avoid drawing lines at all. You can draw only dots and do not connect them. Feel free to submit PR to change this.

**Comment by raomin** [comment]
Is this still not possible?
_Sorry to dig back this old issue._
