### ISSUE TITLE
Import telemetry data

### ISSUE THREAD

**Issue by beraoudabdelkhalek** [thingsboard/thingsboard#10879]
**Is your feature request related to a problem? Please describe.**
I did not find a way to upload telemetry data to experiment with the rule engine or with the visualization.

**Describe the solution you'd like**
A feature to import telemetry data in different formats like csv, json...

**Describe alternatives you've considered**
I used HTTP to send data from my telemetry data file to simulate that

**Comment by mykhailokornieiev** [comment]
Hi
Import of historical telemetry with a specific timestamp for each datapoint via Bulk/CSV import is not provided by the design of Thingsboard. You can only use REST API calls, so it will save data with a unique timestamp for each record.
