### ISSUE TITLE
Login error in the ThingsBoard Live app on iOS and iPadOS with Demo Account

### ISSUE THREAD

**Issue by jk4e** [thingsboard/thingsboard#10871]
**Describe the bug**
I cannot log in with my Live Demo account. I created a demo account (last week) and can log in and use the web interface. I wanted to try the advertised App but can't log in with my account. Also, I can't find any information if I need a new, separate account just for the app. I think my already created account should work. I get this error message when logging in and when closing the message I get stuck in the loading screen/animation.

Thank you very much in advance for all your help and work in finding and fixing this bug.!

**Your Server Environment**
* [Live Demo](https://demo.thingsboard.io)

**Your Client Environment**
**Smartphone (please complete the following information):**
* Device: iPhone XR, iPad Pro 2021
* OS: iOS 17.5.1.  iPadOS 17.5.1  (I have updated the devices, older version 17.4.X did not work either)
* App-Version: 1.1.1 (newest Version)

**To Reproduce**
1. Sign up via Website ( https://demo.thingsboard.io/signup )
2. Try logging in with the account in the app
3. see Error-Message

**Expected behavior**
Log in and try out the application with my demo account as advertised on the web interface.

**Screenshots**
iPad
![IMG_1332 (Klein)](https://github.com/thingsboard/thingsboard/assets/116908874/66a0a40d-4746-447e-b5a4-66332a6c7386)

iPhone
![IMG_2252 (Klein)](https://github.com/thingsboard/thingsboard/assets/116908874/2c6b5e0c-9f08-4128-a50a-2e1d0a0ad667)

When I restart the app, I get no login window, just errors and an endless loading screen with animation.
![IMG_2254 (Klein)](https://github.com/thingsboard/thingsboard/assets/116908874/47f0cb53-78ea-454d-a3f2-3ca317e3e1c8)

**Comment by ashaforost** [comment]
Hi @jk4e 

Our front-end team is aware of this issue and is currently working on a fix.

**Comment by ybeshkarov** [comment]
Hi @jk4e,


It was fixed and a new version of the ThingsBoard Live is available to upload in the app store.

Best Regards.

**Comment by jk4e** [comment]
Hi ThingsBoard-Team,

thank you very much for the quick fix. Now everything works as desired.
