### ISSUE TITLE
Edge devices functionality

### ISSUE THREAD

**Issue by AneCapde** [thingsboard/thingsboard#10875]
Good afternoon,

I was working with the thingsboard-edge and I encountered some functionalities that seemed unusual to me. I have several thingsboard-edge installed and one central thingsboard platform.

When I create a device on the Edge, it appears on the central platform assigned to the specific instance. However, when I delete this Edge device, it does not disappear from the central platform. It does get removed from the "manage devices" section, but not from the central platform. Moreover, the device continues to be assigned in the relation section under the type "managedByEdge".

I also have a doubt: when I create a device in the central platform and assign it to an instance, this device appears in the Edge platform but nothing appears in the relations tab of the instance.

Am i missing something?

thanks for the help.

**Comment by ashaforost** [comment]
Hi @AneCapde 

Please create an issue in the [thingsboard-edge repository](https://github.com/thingsboard/thingsboard-edge/issues) with all your edge-related issues. I'm closing this issue as unrelated to thingsboard.
