### ISSUE TITLE
How to Configure Sysadmin Password Before Starting ThingsBoard?

### ISSUE THREAD

**Issue by phwolf** [thingsboard/thingsboard#10872]
**Component**

 * Installation

**Description**
I am working with the ThingsBoard IoT platform and I have encountered an issue regarding the sysadmin user password. By default, the sysadmin user has a password set to sysadmin. While I can change this password after the software starts, I have not found a way to configure it beforehand. Is there any configuration settings that allow for setting the password beforehand?

I would appreciate any guidance on how to set the sysadmin password before starting ThingsBoard. If this feature is not currently available, are there any plans to include it in future releases? Alternatively, are there other recommended best practices for ensuring the default password is changed securely during the initial setup?

**Environment**

 * ThingsBoard: 3.6.1

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Mohameddgomaa** [comment]
I'm also facing this issue and would appreciate any guidance or best practices for managing the sysadmin password before initializing. Thanks!

**Comment by trikimiki** [comment]
hi!

users' passwords (including sysadmin) are stored in the DB hashed - the only way to change it without starting TB would be altering DB

for example, the following query changes password of sysadmin to default "sysadmin":
```
update user_credentials SET password = '$2a$10$YMyxoU0hMOLmd9D7tz/dQeDY3fkXRAv8C023F6hzx2gVB9dTBUpq6' WHERE user_id=(select id from tb_user where authority = 'SYS_ADMIN');
```

so one cannot change password without knowing how it looks like hashed
you can create a "test" DB, change sysadmin password via UI on ThingsBoard, copy the hash and insert it into your "prod" DB.
