### ISSUE TITLE
How to change entity alias through action button?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#10873]
Hello.
I have two types of devices in the dashboard that I am showing on the map.
I have defined three types of entity aliases, one of which displays all devices, one of which is device type 1, and another device of type 2.
How can I switch between displaying device type 1, type 2 and all devices through the action key?

**Comment by m3relec** [comment]
thanks @devaskim 
I added the filters I needed.
Is it not possible to change the filter through custom action?

**Comment by devaskim** [comment]
Possible. Look at
```
// 1. To get all filters and find that you need
const filters = widgetContext.aliasController.getFilters();
// 2. Update the filter

// 3. Save the filter
widgetContext.aliasController.updateUserFilter(filter);
```

**Comment by m3relec** [comment]
thanks @devaskim 
I executed these commands and saw the output in the console log.
But I don't know how to use them?
How should I use one of the filters arrays?
I had another question outside of this discussion:
in row style function how to access time series and attribute?

**Comment by devaskim** [comment]
> How should I use one of the filters arrays?

You are on the right way by using `console.log(yourFilterObject)`. The filter has complicated structure, so you need to dive to its  deep and find `keyFilterPredicate` and its `predicates` and then update `value.userValue` of those `predicates`

> in row style function how to access time series and attribute?

If you are about Entity Table widget, row style function has `entity` parameter. There you can find all data keys that are used in the widget.

**Comment by m3relec** [comment]
> You are on the right way by using `console.log(yourFilterObject)`. The filter has complicated structure, so you need to dive to its deep and find `keyFilterPredicate` and its `predicates` and then update `value.userValue` of those `predicates`

thanks a lot. I will try to do it.



> If you are about Entity Table widget, row style function has `entity` parameter. There you can find all data keys that are used in the widget.

Yes, for example, how should I write to check the active?
Or, a variable that is a time series.

**Comment by devaskim** [comment]
> how should I write to check the active?
```
return { "backgroundColor": entity['active'] === 'true' ? 'green' : 'grey' }; // where 'active' is data key LABEL
```

**Comment by Ultrazombie** [comment]
10q @devaskim
