### ISSUE TITLE
Can not send data to TB

### ISSUE THREAD

**Issue by armyjam** [thingsboard/thingsboard#1087]
I have installed TB by following the installation guide to VM windows server on Azure. Everything is ok but when I sent the data from my board(BC95 CoAP) TB can't receive anything. Initially, I used WireShark and TCP packet send for received test TCP packet from other networks. I found that it's can receive the packet successfully.
How can I solve this problem?

Thank you for your kindness.

**Comment by ashvayka** [comment]
Maybe this is a network problem related to closed CoAP port on your network related to VM?

**Comment by vparomskiy** [comment]
Also please check your config file (thingsboard.yml) because CoAP transport is disabled by default (coap.enabled: false)

**Comment by armyjam** [comment]
> Also please check your config file (thingsboard.yml) because CoAP transport is disabled by default (coap.enabled: false)

Thank you very much. Now it's work!!!
