### ISSUE TITLE
Java Rulenode Telemetry Save with TTL

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#10887]
Hi, 
I have question how to save telemetry in java custom rulenode with TTL?

curently I only know this way to save telemetry but no TTL here
```
ctx.getTelemetryService().saveAndNotify(
                    ctx.getTenantId(),
                    device.getId(), // save to device
                   Collections.singletonList(optVehTsKv), 
                   callback);
```

**Comment by devaskim** [comment]
Hm,
Seems like `saveAndNotify` method has ttl parameter
https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java#L110

**Comment by evanderbird** [comment]
wow thanks
