### ISSUE TITLE
Unable to create device using MQTT Gateway API

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#10890]
**Component**

 * UI

**Description**
I am using Thingsboard community edition. I have created one device with "Is gateway" option enabled. 
When I publish message {"device":"Device A"} to v1/gateway/connect topic, device is not getting created. 
Gateway device is displayed as active. 

The issue appears only with the community edition. I was able to create devices and also post telemetry with a professional edition. Is this a limitation with the community edition? I am using CE 3.6.2.

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: CE v3.6.2
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
Check server logs on errors/warnings once your gateway has sent connect message.

**Comment by sjthings** [comment]
Found the issue, name of default profile was changed. Adding "type":"$profilename" in connect message worked. 
[https://github.com/thingsboard/thingsboard/issues/8908](url) This link helped.

**Comment by sjthings** [comment]
Found the issue, name of default profile was changed. Adding "type":"$profilename" in connect message worked.
[https://github.com/thingsboard/thingsboard/issues/8908](https://github.com/thingsboard/thingsboard/issues/url) This link helped.
