### ISSUE TITLE
Accessing Multiple Telemetry Variables in a Telemetry Key for Charts

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10896]
Hello,

Is there a way to use other telemetry or attributes in a telemetry key in Charts? I need access to another variable in the JS of the data key, which is in the device, but I am not able to do it. This is a frequent problem I have, and if there could be a solution in a future platform update, that would be great.
In this case I need access to the multiplier variable in averageRMS_L1 which increseases the Power of the Phase, 

Thank you.

![image](https://github.com/thingsboard/thingsboard/assets/98624393/54a5ec53-141d-484a-b05b-76c7d1a1ae98)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/c2987313-ca1f-4cbe-b321-c10b9ed1ea1a)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/5270f290-0677-4dc3-9d39-df695db08d8f)

**Comment by mykhailokornieiev** [comment]
Hi. There is no possibility to access another datasource data in data post-processing function. 
Such a feature won't be implemented due to the design of Thingsboard. The only possible solution is to use Rule Chains.
In this case, I close this ticket.
