### ISSUE TITLE
Phone Location from web browser

### ISSUE THREAD

**Issue by AARON-HQ** [thingsboard/thingsboard#10891]
**Component**
 * Generic

**Description**
Is it possible to get Phone Location coordinates when using Safari or Chrome on a phone?
 I created a Mobile Action button and it didn't work. I downloaded the Thingsboard app and it does work. 
Please confirm that Mobile Actions will only work if I use a dedicated mobile app?

I was able to use the Open Street Map to manually drop a pin on a location. It's just not as convenient as automatically saving the coordinates. 

**Environment**

 * OS:  Windows
 * ThingsBoard: Cloud 3.6
 * Browser: Safari / Chrome for Iphone
Thanks for your help
Aaron

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by liotys** [comment]
Hi,
you can use an html value card with the following code on an action:

```
function getLocation() {


if (navigator.geolocation) {
        //navigator.geolocation.requestGeolocationPermission();
        navigator.geolocation.getCurrentPosition(showPosition,showError);
    } else {
        alert("La géolocalisation n'est pas prise en charge par ce navigateur.");
    } 
}

function showPosition(position) {
    document.getElementById("SearchLatitude").value = position.coords.latitude;
    document.getElementById("SearchLongitude").value = position.coords.longitude;
    updateUserAttr("SearchLatitude",position.coords.latitude);
    updateUserAttr("SearchLongitude",position.coords.longitude);
    updateUserAttr("SearchGo",1);
    console.log(widgetContext);
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            alert("La demande de géolocalisation a été refusée par l'utilisateur.");
            break;
        case error.POSITION_UNAVAILABLE:
            alert("Les informations de localisation ne sont pas disponibles.");
            break;
        case error.TIMEOUT:
            alert("La demande de localisation a expiré.");
            break;
        case error.UNKNOWN_ERROR:
            alert("Une erreur inconnue s'est produite.");
            break;
    }
}

getLocation();


function updateUserAttr(target, value) {
    /*** update the value of your filter attribute ***/
    // This is an untested example
//    console.log(target,value,entityId, widgetContext.currentUser.userId);
     widgetContext.attributeService.saveEntityAttributes({
            'entityType': 'USER',
            'id': widgetContext.currentUser.userId
        },
        'SERVER_SCOPE',
        [{
            key: target,
            value: value
        }]
    ).subscribe(
        //success and fail scenarios - this is the test code so i just log into the console
        function success() {
            console.log('success');
        },
        function fail() {
            console.log('fail');
        }
    );
} 
```
It works fine with Chrome (which asks for permission) but there is a problem with Safari that returns PERMISSION_DENIED (without any question). 
May be you will find an adaptation for Safari...

**Comment by AARON-HQ** [comment]
Ok! Thanks for the example. I will try it out!

**Comment by Ultrazombie** [comment]
Closed due to ianctivity

**Comment by liotys** [comment]
> It works fine with Chrome (which asks for permission) but there is a problem with Safari that returns PERMISSION_DENIED (without any question). May be you will find an adaptation for Safari...

The reason is that I didn't use an https url in Safari. The Iphone refuses the location to an http url.
