### ISSUE TITLE
Import Dashboard Error

### ISSUE THREAD

**Issue by carsickcars** [thingsboard/thingsboard#1089]
I want to import Dashboard that named "smart_bus_tracking", When I import the "smart_bus_tracking.json"  into the dashbords, I get hints like this picture. 
![1](https://user-images.githubusercontent.com/7300422/45799312-99458880-bcdf-11e8-96c8-ad56c6e28819.png)
Who can help me?

**Comment by ashvayka** [comment]
Each alias corresponds to one device (Buses are moving objects and dispatcher is the one who generates the alarms and messages). You need register devices for this A,B,C,D,Dispatcher and select them in this screen for each alias by clicking on a corresponding "pencil" button. You will also need to write some scripts to push telemetry on behalf of this devices.
