### ISSUE TITLE
Attributes Updated

### ISSUE THREAD

**Issue by HiTyang0312** [thingsboard/thingsboard#10902]
![image](https://github.com/thingsboard/thingsboard/assets/170751488/4720cc23-6f68-49a6-b913-bb1d936fe8ae)

I repeatedly sent the same data, but it changed

![image](https://github.com/thingsboard/thingsboard/assets/170751488/f656397a-3b2f-4c93-8b65-2c1a42dc8543)

![image](https://github.com/thingsboard/thingsboard/assets/170751488/72764629-e77a-481b-8227-fbffc88e95ee)

**Comment by ashaforost** [comment]
Hi @HiTyang0312 

Please describe your issue in more detail. What request and payload did you send to the thingsboard, how did you send it, what results did you expect, what is the actual result, what 'changed'?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
