### ISSUE TITLE
count incoming and outgoing mqtt message ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1090]
is there a way to count the incoming and outgoing mqtt message ? does your implementation of Mqtt support $SYS topic ? and if yes is it possible to use it  to count incomming and sent message ?

**Comment by ashvayka** [comment]
Hi! No, $SYS topic is not supported, but you can count the number of messages in the rule engine. I suggest implementing a custom rule node for this for performance reasons. Feel free to contribute it.
