### ISSUE TITLE
Reset User Password without mail

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#10906]
**Component**

 * Generic

**Description**
Hi,
I need to reset a forgotten password for a customer who can't receive email, so he can't receive the link for resetting. How can I change his password as tenant administrator without knowing his previous password?
Thanks for your answers,

**Environment**

 * ThingsBoard: 3.5.1 PE

___________________________________________________________

**Comment by devdoob** [comment]
Just delete and recreate the user.

**Comment by liotys** [comment]
Thanks for the answer. I feared this was the only way. No matter in my case, but if the users have telemetry (e.g. healt devices) it could be problematic.
