### ISSUE TITLE
how move PopOver (custom dialog) not in the center of the screen ?

### ISSUE THREAD

**Issue by Agailh** [thingsboard/thingsboard#10908]
**Component**

 * UI

**Description**
How to move (edit CSS ) of this cutom dialog , i wanted to move this dialog to the side of the screen not in the center 
![image](https://github.com/thingsboard/thingsboard/assets/86946649/b9cf0015-303e-4d34-927f-500734facaca)

the custom dialog is trigered by on HTML widget on HTML element click (custom action)

This is the code to activate the custom dialog 

let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

openEditEntityDialog();

function openEditEntityDialog() {
    customDialog.customDialog(htmlTemplate, EditEntityDialogController).subscribe();
}

**Environment**

 * OS: windows
 * ThingsBoard: thingsboard community
 * Browser: chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
