### ISSUE TITLE
How to Display Multiple Text Values for a Single Variable in ThingsBoard Widget?

### ISSUE THREAD

**Issue by Islan8** [thingsboard/thingsboard#10900]
**Component**

 * UI

**Description**

I am working on a project where I need to display different text values based on the status of a pump. The status data is received through the variable `P01`, which can have the following numeric values and corresponding statuses:

- 0 - Stopped
- 1 - Starting
- 2 - Running
- 3 - Stopping
- 4 - Fault
- 5 - Maintenance

I would like to display these text values in a widget on my ThingsBoard dashboard. However, I am unable to find a suitable widget or method to accomplish this. 

Can anyone suggest a better way to display these text values based on the variable `BC01` in ThingsBoard? Any help or guidance would be greatly appreciated.

Thank you!

**Environment**

 * OS:
 * ThingsBoard: 3.6.4
 * Browser: Chrome 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
In any thingsboard widget, you can use a post-processing function to change the displayed text based on your timeseries or attribute key value. 
![image](https://github.com/thingsboard/thingsboard/assets/47900737/814296c3-4b42-4ed5-90a2-0cdd427258d6)
![image](https://github.com/thingsboard/thingsboard/assets/47900737/890b7d9a-e987-4367-af29-0893777d6a74)

**Comment by Islan8** [comment]
> In any thingsboard widget, you can use a post-processing function to change the displayed text based on your timeseries or attribute key value. ![image](https://private-user-images.githubusercontent.com/47900737/335484189-814296c3-4b42-4ed5-90a2-0cdd427258d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzc5NzEsIm5iZiI6MTcxNzE3NzY3MSwicGF0aCI6Ii80NzkwMDczNy8zMzU0ODQxODktODE0Mjk2YzMtNGI0Mi00ZWQ1LTkwYTItMGNkZDQyNzI1OGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE3NDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjk0OWEyYTdkNzI4ODQzMjAwMWM1OTZmYjYwZDI1MTZkOWM0YmY0ZjI3YzQzMDMzMjAxZTBjYTFmMTZmYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9d2Ppr3EdDVnUkjVLoDBipdoCFpnnNUM5hskgQDz_PE) ![image](https://private-user-images.githubusercontent.com/47900737/335484930-890b7d9a-e987-4367-af29-0893777d6a74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzc5NzEsIm5iZiI6MTcxNzE3NzY3MSwicGF0aCI6Ii80NzkwMDczNy8zMzU0ODQ5MzAtODkwYjdkOWEtZTk4Ny00MzY3LWFmMjktMDg5Mzc3N2Q2YTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE3NDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTlhNzgyN2I0OWQyODdhYjlmNjEwNjMzNWNhYTViZDE2YzZiY2Q3YmYyYjNjNWRlN2NjMGEwZmQ1YjliNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nAyi4Mw3uxZ096sdEQDeQcsb4z3KxNYQTAGAw75r6vc)

**Comment by Islan8** [comment]
It works, thank you so much.
