### ISSUE TITLE
Cybersecurity security & penetration testing

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#10915]
Hi, I am planning to get Cybersecurity & peneteration testing done for Thingsboard PE (perpetual on premise server). 
Would like to know if someone has already done so and what support would be provided by Thingsboard on same. 

**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Clear and concise details.

**Environment**

 * OS:  RHEL
 * ThingsBoard: 3.6.2
 * Browser: Chrome / Edge

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AlexDoanTB** [comment]
@sjthings You are free to share your pentest results related to ThingsBoard with us. We will comment on the findings, if any.
