### ISSUE TITLE
Can lost message when use InMemoryQueue?

### ISSUE THREAD

**Issue by 04116** [thingsboard/thingsboard#10917]
**Component**

 * Generic

**Description**
Source code use queue for async process. Until [function that persistent timeseries data to database](https://github.com/thingsboard/thingsboard/blob/694967e535a31c1630836dc74db2f08283529b98/dao/src/main/java/org/thingsboard/server/dao/sql/TbSqlBlockingQueue.java#L81) we wait for sometime before save to database if receive empty from queue. In the middle of sleep time, if the server crashes, messages in the queue - not being consumed can lost? (If we use kafka it will not)

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: CE 3.6

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by trikimiki** [comment]
Yes.
InMemory queue implementation stores messages in RAM. Due to the specifics of RAM storage, an application crash will cause present messages in the queue to be lost and unretrievable.

**Comment by 04116** [comment]
Thank @trikimiki so much
