### ISSUE TITLE
Raise Alarm based on state which persists for a longer period (e.g. door open)

### ISSUE THREAD

**Issue by sebsoft** [thingsboard/thingsboard#1092]
I have a use case where a sensor reports the opening and closing of a door.  I want to raise an alarm if the door is open for more than xx minutes.  So in this case the alarm cannot be based on a rule chain  as there is no message to process.   

Or should i use the generator node and check every xx seconds for open doors ?

**Comment by ashvayka** [comment]
I believe the best option for now is to use delay node (TbMsgDelayNode). Be careful that you need to check that the delayed message corresponds to your event. For example: you may start the "timer" for 5 minutes, but there were multiple event during the 5 minutes.
