### ISSUE TITLE
Thingsboard database connection (PostgreSQL) and Connecting real devices/sensors to Thingsboard

### ISSUE THREAD

**Issue by Petronella13** [thingsboard/thingsboard#10924]
Dear members,

May you please help me, I am new to the ThingsBoard platform and have been exploring its features to understand how it works and how to connect real devices ( I'm still researching about it to know how to do it...). 
I am particularly interested in connecting to the ThingsBoard database using HTTP protocols...
My goal is to enable a device to send data to the dashboard and store this data in a PostgreSQL database. However, I am unsure of the specific steps or configurations required to achieve this.

Could you please provide guidance or direct me to the appropriate resources for setting up an HTTP connection to the ThingsBoard database?
I have Thingsboard Community version installed, PostgreSQL database installed and configured and Java 11 installed...

Thank you in advance for your assistance.

**Comment by Backdraft007** [comment]
https://thingsboard.io/docs/reference/http-api/

**Comment by Petronella13** [comment]
> https://thingsboard.io/docs/reference/http-api/

I can't really see what I'm looking for

**Comment by Backdraft007** [comment]
Maybe you specify more details. Which devices do you use and so on.

**Comment by Petronella13** [comment]
> Maybe you specify more details. Which devices do you use and so on.


I'm looking for a way to connect my THINGSBOARD with a DATABASE.
I have the default database of postgreSQL named thingsboard that I've created on installing time...  I have researched a lot but could not find any way to send my telemetry data to any created database (I have installed pgadmin4 ).

**Comment by Backdraft007** [comment]
I can't follow.
You have installed Thingsboard. Which documenation did you follow? When it is installed Thingsboard uses the database.
A device sends telemetry data (with MQTT, HTTP, etc.) to Thingsboard and Thingsboard save the data in the database.
Here is a shematic: https://thingsboard.io/docs/getting-started-guides/what-is-thingsboard/

**Comment by Petronella13** [comment]
> ###
> [Jun 4, 2024](#issuecomment-2146852461)

I followed this: https://thingsboard.io/docs/user-guide/install/windows/

**Comment by Backdraft007** [comment]
Ok,
Server is installed and you can login to the server?
Then you have to read this https://thingsboard.io/docs/user-guide/rule-engine-2-0/re-getting-started/ 
Rule chains manage the data and save them in the database.

Then follow this guide https://thingsboard.io/docs/getting-started-guides/helloworld/#step-1-provision-device
and this
https://thingsboard.io/docs/guides/#AnchorIDConnectYourDevice depending on which protocol you want to use or your device uses.

**Comment by Petronella13** [comment]
@Backdraft007 
Alright! Thank you for your assistance!

**Comment by Ultrazombie** [comment]
Closed due to inactivity
