### ISSUE TITLE
WARN  o.t.s.a.AbstractScriptInvokeService - Script has exception counter 1 on disabledFunctions

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#10925]
**Describe the bug**
Getting warning of WARN  o.t.s.a.AbstractScriptInvokeService - Script has exception counter 1 on disabledFunctions for id b3504dae-fa06-44d2-a72d-fdc352ddecf6 - Seeing some timeouts but not sure how to trouble shoot the same. 

Causes: 
1. exception Timed out: TrustedListenableFutureTask@332fcdd9[status=SUCCESS, result=[java.util.UUID@498564f8]]
2024-06-04 08:20:45,443 [script-timeout-33-thread-1]
2. exception Timed out (timeout delayed by 43 ms after scheduled time): TrustedListenableFutureTask@7a732a3a[status=PENDING, info=[task=[running=[RUNNING ON tbel-executor-50-2], org.thingsboard.script.api.tbel.DefaultTbelInvokeService$$Lambda$2650/0x00000008414d6040@473df637]]]
3. exception Timed out: TrustedListenableFutureTask@12b4c371[status=PENDING, info=[task=[running=[RUNNING ON tbel-executor-57-1], org.thingsboard.script.api.tbel.DefaultTbelInvokeService$$Lambda$2650/0x00000008414d6040@3a90035e]]]

**Need help on trouble shooting this issue, is this a memory issue or some other issue?** 

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: deb
  * ThingsBoard Version: 3.6.4 
  * Community or Professional Edition: CE
  * OS Name and Version: Ubuntu 22

**Comment by trikimiki** [comment]
hi!

`Script has exception counter 1 on disabledFunctions` asserts that some script was blocked by JS/TBEL sandboxing feature (secure execution).

`Timed out: TrustedListenableFutureTask` means that some script took too long to execute or process.

The most common root causes are:
- CPU performance issues - check server monitors
- too "heavy" or too "faulty" scripts - check API Usage-->RuleEngine-->Exceptions
