### ISSUE TITLE
is there any way to get rowIndex or rowNumber in entities table widget?

### ISSUE THREAD

**Issue by Steve7394** [thingsboard/thingsboard#10935]
* Generic

**Description**
is there any way to get rowIndex or rowNumber in entities table widget?
i want to colorize each row on by between for best viewing in ui/ux
for using in row style function in entities table widget

**Comment by devaskim** [comment]
As I know there is no such counters, but you can try to set `rowIndex` in `ctx.$scope.rowIndex` and increment it at the end of each call of row style function.

Or you can use [CSS n-th child pseudo class ](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)to coloring separate rows.

**Comment by Steve7394** [comment]
thanks for your answer. you are right. we can use custom style for a dashboard or each widget and set css like that to colorize each row on by between. just like below
```
mat-row:nth-child(even) {
  background-color: #bde0feDA;
}
```

**Comment by Ultrazombie** [comment]
Closed due to solved
