### ISSUE TITLE
Troubleshooting tb-rule-engine Pod Activation Issues in ThingsBoard Community Edition on Helm Chart

### ISSUE THREAD

**Issue by markcha-ops** [thingsboard/thingsboard#10933]
**Describe the bug**

**Your Server Environment**

* own setup
  * Deployment: microservices
  * Deployment type:  k8s
  * ThingsBoard : 3.6.4
  * Community
  * Ubuntu 22
**Your Client Environment**

**Desktop (please complete the following information):**

* OS: macbook
* Browser:  chrome
* Version 22

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

________________________________________________________________
Hi, I am currently setting up ThingsBoard Community Edition using a Helm chart on a Kubernetes cluster with 3 VMs on Azure, configured on-premise.

Helm chart: [ThingsBoard Cluster Helm Chart](https://artifacthub.io/packages/helm/thingsboard-cluster-betta/thingsboard-cluster)

![image](https://github.com/thingsboard/thingsboard/assets/16717865/92392f10-738a-47d1-b16f-af659919cc82)

When installing using this Helm chart in the MSA version, I encounter a 403 prop failed error and a /login connection refused error on the tb-rule-engine, causing the rule-engine pod to not be activated. 

![image](https://github.com/thingsboard/thingsboard/assets/16717865/375ed4d6-3762-4647-8ef3-0578f7c8715f)

However, when I check the rule-engine logs, it appears to be functioning normally. What is needed to make the rule-engine pod reach the Running state?

**Comment by markcha-ops** [comment]
i solved it removed this values
<img width="754" alt="image" src="https://github.com/thingsboard/thingsboard/assets/16717865/30cab646-c457-4249-8e83-2d140a5a60bf">
i think rule engine don't need this probe.

**Comment by mykolaichukAlexander** [comment]
Hi @markcha-ops we have changed liveness probe for rule engine. After chart update it will have right probe

**Comment by Ultrazombie** [comment]
Closed due to inactivity
