### ISSUE TITLE
Using postman to get telemetry out of root rule  chain 

### ISSUE THREAD

**Issue by JereInlisol** [thingsboard/thingsboard#10930]
I am having problems to telemetry frm our thingsboard server as I am using Postman to connect to thungsboards websocket. I am connected but the messega gives "failed to parse the load" any idea why the JSON is giving this ?

**Comment by KashifAhmd** [comment]
Can you please share the screenshot of how you are doing this using Postman?

**Comment by devaskim** [comment]
@JereInlisol Take a look on this doc
https://thingsboard.io/docs/user-guide/telemetry/#websocket-api

**Comment by trikimiki** [comment]
`failed to parse the load` indicates that your JSON payload is invalid
try validating JSON structure overall (e.g. https://jsonformatter.curiousconcept.com), and checking if you are sending data according to what ThingsBoard expect (you can check Swagger UI for examples)
