### ISSUE TITLE
Default values for server attributes on device creation

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#10938]
**Component**

 * UI

**Description**
I would like to initialize server attributes with default values, when the device is created. There are multiple server attributes, that need to be added per device / entity based on its profile and these need to be initialized as well. 
e.g. InactivityTimeout need to be set to a default value based on device profile when device is created. Also, other parameters like default threshold attributes for device need to be set during device creation. 

Need a way to handle this. 
 

**Environment**

 * OS:  RHEL
 * ThingsBoard: 3.6.2 CE
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
You need to process `Entity Created` event in a ROOT rule chain of your device profile or if you don't have such rule chain do it in global ROOT rule chain. Then in `Script` transformation node put attributes in `msg` and set `msgType` to `POST_ATTRIBUTES_REQUEST`. Finally forward message with attributes to `Save attributes` node

**Comment by sjthings** [comment]
This worked, Thanks.
