### ISSUE TITLE
[Question] Timescaledb removed from thingsboard installation guide

### ISSUE THREAD

**Issue by ronit18** [thingsboard/thingsboard#10941]
I am doing a clean setup in my ubuntu server of thingsboard CE. Last time i did was some earlier version at the time in installation docs (https://thingsboard.io/docs/user-guide/install/ubuntu/), i saw there was option for postgresql+timescaledb. But currently i am not seeing that option. or steps in any documentation page. So why did it got removed from docs? is it deprecated? Because I have a different setup in production in which i have PE 3.6.4 running, so in next release will it work?

**Comment by trikimiki** [comment]
hi!

installation guide was removed, but timescaledb is still supported.
there are no plans to deprecate it in future releases afaik.

"master" still has related code and params:
- https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/install/TimescaleTsDatabaseSchemaService.java
- https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L204
