### ISSUE TITLE
[Question] How can i delete deleted timeseries data from postgres?

### ISSUE THREAD

**Issue by ronit18** [thingsboard/thingsboard#10947]
**Environment**
 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.4 CE
 * Postgresql-15 & timescaledb-15

I am having a postgresql + timescaledb setup. In which i was having 10 devices with roughly 2gb of timeseries data. I have deleted all the devices then i checked size of my postgresql using `sudo -u postgres psql -c "SELECT pg_size_pretty( pg_database_size('thingsboard') );"` and this still shows that 2 gb of data. So it is not deleted from db.
Then after some research i found out this is due to PostgreSQL's MVCC (Multi-Version Concurrency Control) architecture. Then i searched in some issues and found out this (https://www.postgresql.org/docs/11/sql-vacuum.html) by which i can reclaim my deleted storage. But after running `VACUUM FULL;` query, it increased the storage rather then cleaning. So how can i actually delete the deleted timeseries data?

**Comment by pon0marev** [comment]
In version 3.6.4 and earlier, telemetry is not deleted from the database after deleting a device. In version 3.7 will be implemented background deletion of telemetry for deleted devices. However, this does not apply to devices that were deleted before version 3.7 was installed. You can run the following queries to remove telemetry of non-existent devices from the database:

```sql
delete from ts_kv
where entity_id in (
select distinct attribute_kv.entity_id from attribute_kv 
left outer join device on device.id=attribute_kv.entity_id
where attribute_kv.entity_type='DEVICE' and device.id is null);
```
After removing all telemetry, you can remove attributes. Do NOT delete attributes until all unnecessary telemetry has been deleted.
```sql
delete from attribute_kv
where entity_id in (
select distinct attribute_kv.entity_id from attribute_kv 
left outer join device on device.id=attribute_kv.entity_id
where attribute_kv.entity_type='DEVICE' and device.id is null);
```
### Make a backup of the database before running these queries. These queries can cause some performance related issues if you have too much data to delete.
