### ISSUE TITLE
How can I add entityName in the tooltip of the bar chart or line chart whatever?

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#10946]

**Comment by ronit18** [comment]
First go in edit widget then go in appearance tab. In that enable tooltip. 
![image](https://github.com/thingsboard/thingsboard/assets/69378341/4af732d4-6b21-44c0-98d1-d48af97c48a4)

Then go in data tab and click on edit button of your data key. Now ${entityName}`. 
![image](https://github.com/thingsboard/thingsboard/assets/69378341/090f0fd8-a5f1-4e08-a851-71bc032cf9b9)

This will set in tooltip and legend(if enabled)
![image](https://github.com/thingsboard/thingsboard/assets/69378341/5307efaa-1118-4d72-97a2-17033f5b4bfe)

**Comment by KashifAhmd** [comment]
@ronit18 Thanks for the response, I got this.

Can you help me understand how I can customize the tooltip? (like color etc)

I know there is one tooltip format function, can I use that?
If Yes! then help me, How can I use it?

**Comment by ssakharova** [comment]
Hello @KashifAhmd,

When switching to the Advanced mode of the widget configuration, you need to go to the Advanced tab and find the Tooltip section.
Here, you can customize the tooltip (color, etc.)
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/7d0a0ab6-cb79-4bab-bc60-6ecfa345babc">
