### ISSUE TITLE
Slow dashboard/database performance with Google CloudSQL (postgres)

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#10956]
**Describe the bug**

In our Thingsboard instance we notice very poor performance in the dashboards. Our dashboards are very simple, for example we use simple list entities (devices and assets). 

We are still in the pre-production pilot phase and hence the number of devices is low <100.

**Your Server Environment**
* own setup
  * Deployment: `monolith`
  * Deployment type: `k8s`
  * ThingsBoard Version: `3.6.3 PE`
  * OS Name and Version: N/A

We installed Thingsboard in Google Kubernetes Engine (GKE) using the manifest files from: https://github.com/thingsboard/thingsboard-pe-k8s/tree/master/gcp/monolith
We use a dedicated CloudSQL database (postgres) but everything else follows the monolithic approach

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome
* Version `Version 125.0.6422.142 (Official Build) (arm64)`

**To Reproduce**
1. Create a simple dashboard with a list devices widget
2. Open the dashboard and wait for it to load

**Expected behavior**
For such a small dataset I would expect dashboards to load almost instant. 

**Screenshots**
<img width="1250" alt="image" src="https://github.com/thingsboard/thingsboard/assets/14202480/9651ec00-eaea-4386-b86d-ae8d657c1ea4">

**Additional context/Steps already taken**

I went through some older issues and noticed two things

1. It was mentioned that maybe some database indexes are missing. These are the indexes I can see on my tables
   <img width="833" alt="image" src="https://github.com/thingsboard/thingsboard/assets/14202480/e5ca04c3-ade4-4402-aec1-0fcd036429e2">
2. I made sure database and cluster are running in the same GCP zone (in my case `us-central1-b`)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ViacheslavKlimov** [comment]
Please provide a HAR file with network logs (XHR + WS) from the moment of page refresh, up to when devices are displayed. 
You may send it to support@thingsboard.io with the link to this issue.

**Comment by pon0marev** [comment]
In addition to the HAR file, what servers are you using to run your infrastructure? 
Provide the output of next sql query when the dashboards are loading slowly:
```
SELECT pid, age(clock_timestamp(), query_start), usename, query
FROM pg_stat_activity
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%'
ORDER BY query_start ASC;
```
This query will show if you have active database queries that can freeze dashboard loading.

**Comment by dmohns** [comment]
We are using Google CloudSQL with a Postgres database. I was trying to debug queries, but it looks like CloudSQL comes with a very limited set of extensions installed.

Here is the output of your query (run while the dashboard was loading)

```
34778	00:12:48.170398	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34784	00:12:22.196424	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34796	00:12:01.068264	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34797	00:11:58.170363	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34800	00:11:51.92104	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34807	00:11:50.008484	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34808	00:11:43.596396	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34809	00:11:43.463951	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34811	00:11:43.048855	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34813	00:11:37.110256	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
34831	00:11:17.158008	postgres	"SET application_name = 'PostgreSQL JDBC Driver'"
35120	00:00:05.801501	cloudsqladmin	"SELECT CAST(ROUND(EXTRACT(EPOCH FROM (current_timestamp - pg_catalog.pg_postmaster_start_time()))) AS BIGINT),
		pg_catalog.pg_postmaster_start_time(), current_timestamp"
34771	00:00:01.860159	postgres	COMMIT
34754	00:00:01.859652	postgres	COMMIT
34752	00:00:01.859652	postgres	COMMIT
34739	00:00:00.3667	postgres	COMMIT
45	00:00:00.311333	cloudsqladmin	;
34718	00:00:00.301695	postgres	COMMIT
25	NULL	NULL	
28	NULL	cloudsqladmin	
22	NULL	NULL	
27	NULL	NULL	
21	NULL	NULL	
26	NULL	NULL
```

**Comment by pon0marev** [comment]
This is a good sign, this output means that queries are not stuck in the database.
But my second question remains open. What servers are you using for thignsboard and for CloudSQL. Do you use a dedicated or shared core server?
![image](https://github.com/thingsboard/thingsboard/assets/44898346/f676b577-98ec-43bd-88a2-dfa90e1ca787)

In addition, attach thingsboard logs (`/var/log/thingsboard/thingsboard.log`)

**Comment by dmohns** [comment]
> This is a good sign, this output means that queries are not stuck in the database. But my second question remains open. What servers are you using for thignsboard and for CloudSQL. Do you use a dedicated or shared core server? ![image](https://private-user-images.githubusercontent.com/44898346/339460490-f676b577-98ec-43bd-88a2-dfa90e1ca787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTQwMjIsIm5iZiI6MTcxODYxMzcyMiwicGF0aCI6Ii80NDg5ODM0Ni8zMzk0NjA0OTAtZjY3NmI1NzctOThlYy00M2JkLTg4YTItZGZhOTBlMWNhNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljM2RmNDkyNTkwNTM5NTA0M2NiNTdiYjY1N2YyNjMyNjcxNGU4NmM3YjNhZWNlM2QyM2YzZTM0NTU4ZDc0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLB-vzSvXyGMKjppP24VjOwMWbCB9GP4pgenBUlilTU)
> 
> In addition, attach thingsboard logs (`/var/log/thingsboard/thingsboard.log`)

We are using dedicated core. Below is a excerpt from out Terraform

```terraform
  settings {
    tier              = "db-custom-1-3840"
    availability_type = "ZONAL"
  }
```

In the meantime I was able to make some progress on this one myself. Together with the observation that the database probably isn't the bottle neck, the first hint from @ViacheslavKlimov about sending Network logs was a great one.

I went to inspect the network logs in more detailed. I noticed a particular WebSocket query that took ages and seem to be blocking everything else 🙀 

In the dashboard I'm using a Map widget to display my sensors on the map. This map Widget is equipped with a tooltip that fetches a picture of the sensor like so

```html
<img width="150" src="${picture}">
```

However, the picture images are quite "large" (~1mb). So, for project with 50 devices it actually has to send 50mb through the websocket which takes ages.

Removing the tooltip from map widget solved my problem 🎉🎉🎉🎉

Thanks a lot for all the help and pointing me to right direction.
