### ISSUE TITLE
源代码缺少类文件，无法启动服务(The source code is missing class files and cannot start a service)

### ISSUE THREAD

**Issue by wangpony** [thingsboard/thingsboard#1095]
源代码缺少类文件，无法启动服务，例如ClusterAPIProtos这个类文件丢失，无法启动服务。
The source code is missing class files and cannot start a service, such as Cluster API rotos, because the class file is missing and the service cannot be started.

**Comment by vparomskiy** [comment]
All *Protos classes are generated after building a project.
If you are building Thingsboard from sources, please run this command - 'mnv clean install' before starting Thingsboard.
