### ISSUE TITLE
Integration FORBIDDEN

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#10965]
**Component**
TB Integration  

**Description** 
I find some FORBIDDEN status in Integration. I dunno what is wrong here. Anyone have similar issue to this? 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/61b2be4f-64c7-421b-880c-a0936e059301)

this message with status OK
![image](https://github.com/thingsboard/thingsboard/assets/12267053/12a2904b-8e42-4937-99a5-905a7a5e9079)

this is the message content that had status FORBIDDEN, is this error has anything to do with content?
![image](https://github.com/thingsboard/thingsboard/assets/12267053/50e1022e-3d33-4640-bd3f-db00a10514b4)

**Comment by myroslav-tb** [comment]
Hi @evanderbird, the FORBIDDEN status in Integration means that the security is not identified for the connection. It might be misconfigured or missing. Please check if your connection requires security headers.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/c0b36c88-cea9-4dfe-b324-c9e18f76a859)

The error you has for the message that had status FORBIDDEN is indicating that the expected value type for attribute connector is string but it receives list. It has nothing to do with the forbidden status of the message.

Best regards,
Myroslav

**Comment by evanderbird** [comment]
hi @myroslav-tb thanks for your assistance. I will look again the configs

**Comment by myroslav-tb** [comment]
I'm closing this ticket due to inactivity.
