### ISSUE TITLE
I'm having trouble using the library "'package:thingsboard_client/thingsboard_client.dart';" I've tried other versions but I always have this problem

### ISSUE THREAD

**Issue by Yellowfantt** [thingsboard/thingsboard#10963]
I've already tried using other versions of the library but the error continues to persist, can anyone help me?

<img width="736" alt="problema" src="https://github.com/thingsboard/thingsboard/assets/54282309/956bc222-91b2-4227-be8e-8732602ee4f7">

**Comment by ssakharova** [comment]
Please re-create a new ticket in GitHub with respect to the product you are using:

- https://github.com/thingsboard/flutter_thingsboard_app/issues
- https://github.com/thingsboard/flutter_thingsboard_pe_app/issues  

Please describe all the details of your case there, and then you will increase the probability that the GitHub community will be able to help you.

**Comment by Yellowfantt** [comment]
> Recrie um novo ticket no GitHub em relação ao produto que você está usando:
> 
> * https://github.com/thingsboard/flutter_thingsboard_app/issues
> * [https://github.com/thingsboard/flutter_thingsboard_pe_app/issues      ](https://github.com/thingsboard/flutter_thingsboard_pe_app/issues%E2%80%A8%E2%80%A8)
> 
> Descreva todos os detalhes do seu caso e então você aumentará a probabilidade de que a comunidade GitHub possa ajudá-lo.

https://github.com/thingsboard/flutter_thingsboard_app/issues/93
