### ISSUE TITLE
Why Kubernetes config file for ThingsBoard service use TCP for CoAP?

### ISSUE THREAD

**Issue by armyjam** [thingsboard/thingsboard#1096]
I used Kubernetes on Google cloud platform for run the thingsboard service by following this step : https://thingsboard.io/docs/user-guide/install/kubernetes/#tbyaml-file.

The problem is TB cannot receive the data when sent the data from NB-IoT Shield(BC95) by CoAP protocol on 5683 port. I have to see the Kubernetes configuration YAML in tb-service and found that 5683 port is defined by TCP protocol.

```
.
.
.
clusterIP: 10.23.242.112   externalTrafficPolicy: Cluster   ports:
- name: ui
  nodePort: 31146
  port: 8080
  protocol: TCP
  targetPort: 8080
- name: mqtt
  nodePort: 32758
  port: 1883
  protocol: TCP
  targetPort: 1883
- name: coap
  nodePort: 32343
  port: 5683
  protocol: TCP
.
.
.
```
The question is the protocol of `CoAP` should be `UDP` or not?

**Comment by vparomskiy** [comment]
It is a bug, you need to change it to UDP.
We will fix it in the next version.
