### ISSUE TITLE
Clear Alarm if No Reoccurrence of Event within a Specified Time Period

### ISSUE THREAD

**Issue by aricos** [thingsboard/thingsboard#10979]
**Component**

 * Rule Engine
 * Generic

**Description**
Is it possible to clear an alarm in ThingsBoard if the same event that triggered the alarm does not occur again within a specified time period?  I am using ThingsBoard to monitor events from a CCTV system, and I need to implement the following functionality:

1. **Trigger Alarm**: When the CCTV system detects an animal in a specified region.
2. **Clear Alarm**: If no animals are detected in the specified region within the next 10 minutes.

However, I cannot find a way to achieve this using the current rule chain nodes or device profile alarm rules.
It is mandatory to trigger the alarm when the event is happening, so the duration and repeat features in device profile does not serve my goal. 

The only approach I can think of involves creating an external service using the API to periodically check for the event's reoccurrence.

Please provide a solution or guidance on how to achieve this functionality within ThingsBoard. 

Thank you!

**Environment**

 * OS:  docker Ubuntu
 * ThingsBoard: 3.6.4 (CE)

**Comment by sudhirbits** [comment]
Following this.

**Comment by ssakharova** [comment]
Hello @aricos, @sudhirbits,

I passed all the provided information to our developers and created an internal prod ticket for them to decide on its necessity and possible implementation in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
