### ISSUE TITLE
The public dashboard does not work

### ISSUE THREAD

**Issue by hawkwang** [thingsboard/thingsboard#1097]
![public-dashboard](https://user-images.githubusercontent.com/1171865/46071478-addbc200-c1b2-11e8-9eb3-b29781b27518.png)

Any hint?

**Comment by vparomskiy** [comment]
It can be configured in the dashboard settings

**Comment by hawkwang** [comment]
@vparomskiy ,cool! thanks for your reply. I will close this thread.
