### ISSUE TITLE
how to connect lorawan server with thingsboard server ?

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1098]
i want to connect the lorawan server with thingsboard , 
But it shows some General field likes ::

Connector Name *  
Enabled * 
URI *  
Published Topic  
Subscribe  
Consumed Topic 

In authentication field, it shows ::
Client ID  :
Auth :
Name  
Password/Key  
User Certificate 
Private Key 

what should i fill this ?

**Comment by vparomskiy** [comment]
Generally, all lorawan servers support MQTT integration.
Here is a link for general MQTT integration in the Thignsboard:
https://thingsboard.io/docs/user-guide/integrations/mqtt/

And here are 2 guids for connecting via:
TheThinngsNetowrk - https://thingsboard.io/docs/user-guide/integrations/ttn/
ThingPark - https://thingsboard.io/docs/user-guide/integrations/thingpark/

**Comment by gopirathnamt** [comment]
okk
