### ISSUE TITLE
Problem with TBMQ and ThingsBoard ( SN-001 doesn't show telemetry )

### ISSUE THREAD

**Issue by W1zz1S** [thingsboard/thingsboard#10991]
**Component**

 * Generic

**Description**
Hello , so i have been trying to connect TBMQ and ThingsBoard for more then a week now . 
And it was going good on the start but i am doing something wrong probably and i don' know what.
I installed the TBMQ as a docker .. and its running on the tbmq_bridge network of docker-compose .

That one was good smooth etc . 
My configuration its that the tbmq port of docker listen on 1884 on the host machine and inside he maps to 1883 in docker .

I followed this link for integration of the TBMQ and TB-PE [https://thingsboard.io/docs/mqtt-broker/user-guide/integrations/how-to-connect-thingsboard-to-tbmq/](url)

**Mqtt PUB**
`mosquitto_pub -d -q 1 -h 192.168.56.105 -p 1884 -t tb/mqtt-integration-tutorial/sensors/SN-001/temperature -u "tb-pe" -P "secret" -m '{"value":25.3}
`
`Client mosq-4Q0Y9EdBBmqNfvUStw sending CONNECT`
`Client mosq-4Q0Y9EdBBmqNfvUStw received CONNACK (0)`
`Client mosq-4Q0Y9EdBBmqNfvUStw sending PUBLISH (d0, q1, r0, m1, 'tb/mqtt-integration-tutorial/sensors/SN-001/temperature', ... (14 bytes))`
`Client mosq-4Q0Y9EdBBmqNfvUStw received PUBACK (Mid: 1, RC:0)`
`Client mosq-4Q0Y9EdBBmqNfvUStw sending DISCONNECT`
 
**And everything works good except i don't recive last telemetry in the SN-001 device .**
![lasttelemetry](https://github.com/thingsboard/thingsboard/assets/134933952/f2556be9-6aff-4e14-8b2d-ea0d08aaf544) - **No telemerty**
![sensoractive](https://github.com/thingsboard/thingsboard/assets/134933952/cf1905a5-257d-441d-adda-b1d553ab7b05) - **Active device**
![sn001-mqtt](https://github.com/thingsboard/thingsboard/assets/134933952/33f6e82c-4c11-48b9-bef9-d88016a83902) - **MQTT Integration works good .**

**Environment**

 * OS:  Ubuntu Server 22.0.
 * ThingsBoard: 3.6.4PE
 * TBMQ : 1.3.0
 * Browser: Firefox ( version not important )

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AlexDoanTB** [comment]
@W1zz1S I sense the issue is either in your converter script or in your rule chains. 
If the former, test the decoder function (Uplink converter) to check if the output contains telemetry.   
![image](https://github.com/thingsboard/thingsboard/assets/47384595/b34672f5-9ff3-42dd-b25e-abf721a7ad60)

If the latter and the converter work as expected, assuming the SN-001 device profile is *Sensor* (as per documentation) and it points to a Root rule chain, check if you have the *Save Timeseries* rule node or the *Post telemetry* inbound relation to that rule node.   
![image](https://github.com/thingsboard/thingsboard/assets/47384595/01630093-e678-4e55-a25b-e42ced26c468)

**Comment by W1zz1S** [comment]
Hello @AlexDoanTB , unfortunately everything that you mention its good .. But still not working .. I don't really have any other ideas .. 

![Screenshot from 2024-06-14 12-54-15](https://github.com/thingsboard/thingsboard/assets/134933952/81c5153c-e08b-49f9-b962-5681a0b31cb9)
![Screenshot from 2024-06-14 12-48-14](https://github.com/thingsboard/thingsboard/assets/134933952/6a77db7b-2e57-4c18-83cd-ef4578d4ca20)

**Comment by AlexDoanTB** [comment]
@W1zz1S 
Which Device Profile and the target Rule chain is configured for the device? 
Have you debugged your Save TS node to see if the message comes? 
Lastly, go to your device and Check connectivity: send dummy data via mosquitto_pub or cURL

**Comment by W1zz1S** [comment]
@AlexDoanTB 
Which Device Profile and the target Rule chain is configured for the device? - Root Rule Chain 
Lastly, go to your device and Check connectivity: send dummy data via mosquitto_pub or cURL - 
![Screenshot from 2024-06-14 16-12-02](https://github.com/thingsboard/thingsboard/assets/134933952/5986ed2f-d205-46af-a3e9-1fd1e3491448)

Have you debugged your Save TS node to see if the message comes? -
![Screenshot from 2024-06-14 16-14-24](https://github.com/thingsboard/thingsboard/assets/134933952/aaefa8d0-35ad-4d64-b31e-322c71c348bb)

It comes until Data Convertor . From there on nothing , doesn't write to the telemetry .

**Comment by AlexDoanTB** [comment]
@W1zz1S You have your data coming from the converter. 
What is there in your OUT? 
You have not shared the Debug events from your rule nodes, either.

**Comment by W1zz1S** [comment]
@AlexDoanTB 

![Screenshot from 2024-06-18 17-08-24](https://github.com/thingsboard/thingsboard/assets/134933952/56e14157-ec9e-4a9e-9f34-ceed7bc343a1)
![Screenshot from 2024-06-18 17-09-50](https://github.com/thingsboard/thingsboard/assets/134933952/a3ea39a4-d0fe-4602-8f92-b916b149379e)
![Screenshot from 2024-06-18 17-09-56](https://github.com/thingsboard/thingsboard/assets/134933952/21a8922d-7eda-42ec-8b79-0ea5ae158b63)

![Screenshot from 2024-06-18 17-11-03](https://github.com/thingsboard/thingsboard/assets/134933952/9ec266f7-9b03-4252-b32e-997c9f865e14)


Yea right now i also assume its the convertor and i need to change it .

**Comment by AlexDoanTB** [comment]
@W1zz1S, what is there? 
<img width="578" alt="image" src="https://github.com/thingsboard/thingsboard/assets/47384595/51428eb8-9b35-4089-a359-5a04aeeabb99">

**Comment by W1zz1S** [comment]
@AlexDoanTB 

![Screenshot from 2024-06-19 12-23-22](https://github.com/thingsboard/thingsboard/assets/134933952/f51307e2-7eaf-4622-bb1b-187ecb697b1a)

**Comment by AlexDoanTB** [comment]
https://github.com/thingsboard/thingsboard/issues/10991#issuecomment-2167804436

**Comment by W1zz1S** [comment]
@AlexDoanTB 

Hi Alex . I am slowly picking it up how everything works . 
And right now I think that the convertor doesn't apply with the Root Rule Chain and i need to fix in terms of the code .

I am more into Network etc .. So i would appreciate if you could help me with it 

![Screenshot from 2024-06-19 13-48-53](https://github.com/thingsboard/thingsboard/assets/134933952/773ea172-2636-418c-b1b6-ec4d4b8eeff1)
![Screenshot from 2024-06-19 13-49-10](https://github.com/thingsboard/thingsboard/assets/134933952/b9fc0e81-c93f-4b16-8b02-d46eb9c9229b)

I guess that i need a script that this "temperature": 37.2 , needs to be translate it into a raw data 37.2  . Am I wrong or its something different ?

**Comment by AlexDoanTB** [comment]
@W1zz1S Now you have your data received. 
Go to the Latest telemetry tab of the SN-001 device. 
There, you will see the **temperature** key with its value

**Comment by W1zz1S** [comment]
@AlexDoanTB 
![Screenshot from 2024-06-19 14-02-56](https://github.com/thingsboard/thingsboard/assets/134933952/34c29e6b-1069-49e4-846b-ed2c0efe2203)
 
 Still i dont have it .

**Comment by AlexDoanTB** [comment]
@W1zz1S,
 1. The broker's DB by no means is the same as the TB PE database. 
 2. Show me your Data converter and its output. Are you sure you are sending data to the SN-001 device (not to Device A, for instance)?  

I cannot read coffee grounds. It is way easier to help when you share all the steps you do and the configurations you have.

**Comment by W1zz1S** [comment]
@AlexDoanTB 

Yes i can do that . If its not problem for tomorrow . 
If its okay we can go on a Discord , and see it together . 

Show me your Data converter and its output. Are you sure you are sending data to the SN-001 device (not to Device A, for instance)?
Yes : 
![Screenshot from 2024-06-19 17-40-40](https://github.com/thingsboard/thingsboard/assets/134933952/002d0996-b65b-49b4-8bca-70ee49619d5c) 

As you can see at the Meta Data .

**Comment by W1zz1S** [comment]
@AlexDoanTB 
![Screenshot from 2024-06-20 10-56-14](https://github.com/thingsboard/thingsboard/assets/134933952/03bc2953-4dcc-4417-9948-4ad340551c5a)

**Comment by AlexDoanTB** [comment]
@W1zz1S, then check your DB and disk. There are no issues on the TB side. 
I asked to provide clear steps, but you constantly ignore this.

**Comment by W1zz1S** [comment]
@AlexDoanTB 
Please join my discord if you are open for me to give you access and tmp admin on the platform .


https://discord.gg/zqrHPEp

**Comment by W1zz1S** [comment]
![Screenshot from 2024-06-20 20-52-10](https://github.com/thingsboard/thingsboard/assets/134933952/10891212-b97f-43a0-a456-c43b88f7b5aa)

My DB its good and running , but this one its a huge problem so lets see ...

**Comment by AlexDoanTB** [comment]
@W1zz1S, It seems like wss are not allowed on your LB/proxy.

**Comment by W1zz1S** [comment]
@AlexDoanTB 

Thanks for your support i own you a cup of coffee . 

The problem was WS and thats why my telemetry didnt show up . 

LOCK !
