### ISSUE TITLE
Thingsboard v3.7 will be compatible to 3.6.2 thingsboard's database(postgresql) ?

### ISSUE THREAD

**Issue by friedrich86** [thingsboard/thingsboard#10994]
Hi, THINGSBOARDer，
Thingsboard v3.7 will be compatible to 3.6.2 thingsboard's database(postgresql) ?

Now we have thingsboard 3.6.2(community version) running, we want to upgrade thingsbord 3.6.2 to V3.7 while data (postgresql) continue to use, is it feasible?

Thanks for any reply.

**Comment by Backdraft007** [comment]
For sure.
But you have to upgrade step by step. 3.6.2 -> 3.6.3 -> 3.6.4 -> 3.7.x
Look here https://thingsboard.io/docs/user-guide/install/upgrade-instructions/ and read the notes.

3.7.x isnt released yet.

**Comment by friedrich86** [comment]
> For sure. But you have to upgrade step by step. 3.6.2 -> 3.6.3 -> 3.6.4 -> 3.7.x Look here https://thingsboard.io/docs/user-guide/install/upgrade-instructions/ and read the notes.
> 
> 3.7.x isnt released yet.

thank you~
