### ISSUE TITLE
i want to run thingsboard for development how to setup all dependencies that thingsboard need

### ISSUE THREAD

**Issue by anousonefs** [thingsboard/thingsboard#10997]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by pon0marev** [comment]
Closed, as this is a duplicate: https://github.com/thingsboard/thingsboard/issues/10998
