### ISSUE TITLE
Thingsboard Edge PE http proxy support

### ISSUE THREAD

**Issue by ashdam** [thingsboard/thingsboard#11011]
**Component**

 * Generic

**Description**
Summary: We would like to know if http proxy is supported by TB Edge PE.
Full detail

In order to unlock MY_COMPANY restrictions over the network. We are testing again some options on the proxy of MY_COMPANY since we got another software using grpc and it’s working fine and this got us confused and made us consider if we are configuring thingsboard correctly.
 
We got this error
 
![image](https://github.com/thingsboard/thingsboard/assets/169756398/e8252d4d-4f0b-482d-ade2-dba1022b725e)

 
User and password is ok because we have tested it with the other software.
 
We have configured the following:
•	Conf file with java parameters:
 
![image](https://github.com/thingsboard/thingsboard/assets/169756398/48da0893-5b9d-4a1b-ae31-b8b01cd9f808)

 
 
Here we tested different combinations:
o	export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=XXXXXXXXXX -Dhttp.proxyPort=3128 -Dtb.proxy.user=XXXXXX -Dtb.proxy.password=YYYYYY -Dhttps.proxyHost=XXXXXXXXXX -Dhttps.proxyPort=3128”
o	export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=XXXXXXXXXX -Dhttp.proxyPort=3128 -Dhttp.proxyUser=XXXXXX -Dhttp.proxyPassword=YYYYYY -Dhttps.proxyHost=XXXXXXXXXX -Dhttps.proxyPort=3128”
o	export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=XXXXXX:YYYYYYY@XXXXXXXXXX -Dhttp.proxyPort=3128 -Dhttps.proxyHost=XXXXXX:YYYYYYY@XXXXXXXXXX -Dhttps.proxyPort=3128”
 
•	Regular http_proxy environment variables bashrc and config file
 
 
![image](https://github.com/thingsboard/thingsboard/assets/169756398/6cb5575d-7ba4-446d-8c4b-951e1545f70e)

 
 
Regarding the user (and password), after checking the code, we are not sure if using java standard parameter (-Dhttp.proxy.user) or should we use a different one (tb.proxy.user)

![image](https://github.com/thingsboard/thingsboard/assets/169756398/b06faee7-c7de-4b5f-b104-ce15fcbf3718)

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: PE 
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. Please re-create your ticket in TB Edge repository
https://github.com/thingsboard/thingsboard-edge/issues

**Comment by ashdam** [comment]
Done, thank you
