### ISSUE TITLE
MQTT $request_id max value

### ISSUE THREAD

**Issue by JellevanKraaij** [thingsboard/thingsboard#11029]
Hi all,

Im using TB Cloud

I like to know what the length limit is of the MQTT request_id for a parameter request.
For example: v1/devices/me/attributes/request/$request_id
It seems that a 32BIT unsigned number can be too large and it fails.

I have the same question for the firmware and the rpc api (what are the max of ${requestId} ${chunkIndex} and $request_id

v2/fw/request/${requestId}/chunk/${chunkIndex}
v1/devices/me/rpc/request/$request_id
v1/devices/me/rpc/response/$request_id

**Comment by devaskim** [comment]
It is Java integer type, i.e. signed int32

https://github.com/thingsboard/thingsboard/blob/master/common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java#L1359

**Comment by Ultrazombie** [comment]
Closed due to inactivity
