### ISSUE TITLE
Realtime update stop

### ISSUE THREAD

**Issue by ganzuoni** [thingsboard/thingsboard#11034]
We are running 3.3.3 PE and in the last weeks we are observing that from time to time alarm dashboards marked as realtime and even device latest telemetry page are not automatically updated (we have to manually refresh).
We fix the anomaly restarting TB.
The server (monolithic deploy) has been running for about 2 years without such kind of issue and we cannot find any symptom that might suggest a root cause.
Is there any logging settings that can help?

**Comment by pon0marev** [comment]
Attach the thingsboard.log and .har file for the investigation.

**Comment by ganzuoni** [comment]
Do I have to raise log level? For which logger?
How to generate .har file?
Please, note that web ui accesses TB via haproxy->stunnel

**Comment by ganzuoni** [comment]
[tblog.zip](https://github.com/user-attachments/files/15914277/tblog.zip)
I've investigates communication between stunnel and HAProxy and no ws notification is pushed to the client
I've raised log level to TRACE for the whole org.thingsboard.server package and I can see subscription registration when
I display Latest telemetry detail of Device but no further communication take place but pong processing

**Comment by pon0marev** [comment]
What type of deployment do you have? Is it monolith as a service or docker or kubernetes?
If it is a monolith as a service, try to connect at ip address and port 8080 and reproduce your issue. If it doesn't reproduce then the cause is in the load balancer.

**Comment by ganzuoni** [comment]
At the moment, sysadmin restarted the service so it is correctly working now.
Please note that before restartin TB I restarted stunnel but it didn't work
As I said, when the anomaly occurs, I don't see this log lines anymore, 

public class TbWebSocketHandler ..
.....
    public void send(TelemetryWebSocketSessionRef sessionRef, int subscriptionId, String msg) throws IOException {
        String externalId = sessionRef.getSessionId();
        log.debug("[{}] Processing {}", externalId, msg);
...

it appears just when I select a different Device to show unsubscribe from the previous one and subscribe with the new, along with the last telemetry, from that moment, only pong message are sent

In normal situation, the telemetry update is triggered by a Save telemetry rule node
It looks like subscription that triggers update to be sent via WebSocket does not get activated due to 
some problem, but no error message is present in the log.

**Comment by pon0marev** [comment]
If the problem occurs again please try to reproduce it the same way while connecting directly to the service on port 8080. Since it looks like a load balancer issue rather than thingsboard issue.
Make sure load balancers do not modify the header and do not have a websocket limit.

**Comment by ganzuoni** [comment]
Will do, thanks!

**Comment by ganzuoni** [comment]
It happened again (exactly after one week...) and the issue occurs even if
I directly connect to TB app w/o load balancer
I've truncated event table because it was huge due to DEBUG settings in
rule chain nodes.
We are also running ANALYZE on pg once a week. because we have experience
slow alarm data export from dashboard
We are using redis as cache and kafka for queue.

**Comment by pon0marev** [comment]
You may be experiencing performance issues due to data accumulation. So, I would recommend you to upgrade to the latest version as there have been many fixes implemented since version 3.3.3, including performance improvements to WebSocket subscriptions.

**Comment by pon0marev** [comment]
We would like to inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more questions or have encountered similar issues, please reopen this issue.
