### ISSUE TITLE
No data displayed on Thingsboard web after data rotation and compaction in Cassandra

### ISSUE THREAD

**Issue by juanignacionavarro8** [thingsboard/thingsboard#11039]
**Component**

UI

**Description**
I am running Thingsboard in an on-premise environment composed of 4 virtual machines with Ubuntu 18.04.1 LTS operating system. I am using a Cassandra database, which requires a data rotation of old dates which are not part of the requirement of the client using the platform. The data to be rotated (deleted) is related to one of the telemetry tables called ts_kv_cf. After deleting a portion of the records, I performed a user-defined compaction which finished without problems. The compaction freed up 1GB of data only among the four nodes. I then lifted the system as usual, but the web stopped displaying any data, be it devices, clients and any other information. The Thingsboard website was empty, as if it was a newly installed system. I guess initially that I may have a network problem between the different containers because the volume inside each virtual machine corresponding to the Cassandra databases still contained data in all the tables of the system. I obtained the logs from the /var/log folder on the system and found a fragment that caught my attention, which is as follows:

Jun 14 16:32:58 EPEC-TB-CORE-02 kernel: [2701296.264961] veth6b945d8: renamed from eth0
Jun 14 16:32:58 EPEC-TB-CORE-02 kernel: [2701296.300509] br-935c8215d318: port 17(veth3a10366) entered disabled state
Jun 14 16:32:58 EPEC-TB-CORE-02 systemd-networkd[705]: veth3a10366: Lost carrier
Jun 14 16:32:58 EPEC-TB-CORE-02 systemd-udevd[96235]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jun 14 16:32:58 EPEC-TB-CORE-02 kernel: [2701296.395064] br-935c8215d318: port 17(veth3a10366) entered disabled state
Jun 14 16:32:58 EPEC-TB-CORE-02 kernel: [2701296.397953] device veth3a10366 left promiscuous mode
Jun 14 16:32:58 EPEC-TB-CORE-02 kernel: [2701296.397958] br-935c8215d318: port 17(veth3a10366) entered disabled state
Jun 14 16:32:58 EPEC-TB-CORE-02 networkd-dispatcher[789]: WARNING:Unknown index 1311 seen, reloading interface list
Jun 14 16:32:58 EPEC-TB-CORE-02 networkd-dispatcher[789]: ERROR:Unknown interface index 1311 seen even after reload
Jun 14 16:32:58 EPEC-TB-CORE-02 containerd[818]: time="2024-06-14T16:32:58.961159100-03:00" level=info msg="shim reaped" id=8b86ed017655de6d3b4658859024f4b937d6636081ffeb366651926a1a724320
Jun 14 16:32:58 EPEC-TB-CORE-02 dockerd[950]: time="2024-06-14T16:32:58.971012200-03:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 14 16:32:59 EPEC-TB-CORE-02 kernel: [2701296.587228] veth5c5b348: renamed from eth0
Jun 14 16:32:59 EPEC-TB-CORE-02 systemd-networkd[705]: vetha0c1b9b: Lost carrier
Jun 14 16:32:59 EPEC-TB-CORE-02 systemd-udevd[96341]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jun 14 16:32:59 EPEC-TB-CORE-02 kernel: [2701296.653126] br-935c8215d318: port 11(vetha0c1b9b) entered disabled state
Jun 14 16:32:59 EPEC-TB-CORE-02 networkd-dispatcher[789]: WARNING:Unknown index 1299 seen, reloading interface list
Jun 14 16:32:59 EPEC-TB-CORE-02 kernel: [2701296.665118] br-935c8215d318: port 11(vetha0c1b9b) entered disabled state
Jun 14 16:32:59 EPEC-TB-CORE-02 kernel: [2701296.668231] device vetha0c1b9b left promiscuous mode
Jun 14 16:32:59 EPEC-TB-CORE-02 kernel: [2701296.668236] br-935c8215d318: port 11(vetha0c1b9b) entered disabled state
Jun 14 16:32:59 EPEC-TB-CORE-02 networkd-dispatcher[789]: ERROR:Unknown interface index 1299 seen even after reload
Jun 14 16:32:59 EPEC-TB-CORE-02 networkd-dispatcher[789]: WARNING:Unknown index 1299 seen, reloading interface list
Jun 14 16:32:59 EPEC-TB-CORE-02 networkd-dispatcher[789]: ERROR:Unknown interface index 1299 seen even after reload

Can anyone explain the behavior that my system suffered? Is it a known issue and addressed within the Thingsboard project? 
Any help regarding this issue would be appreciated!
**Environment**

 * OS:  Ubuntu 18.04.1 LTS
 * ThingsBoard: 2.4.1
 * Browser: Chrome Versión 114.0.5735.198

**Comment by pon0marev** [comment]
Before deleting data, be sure to make a backup and roll back in case of a similar situation.
How exactly did you delete the data? What commands did you use? 
Could you attach the ThingsBoard (/var/log/thingsboard/thingsboard.log) and Cassandra /var/log/cassandra/debug.log() logs? Or have you already solved your issue?
