### ISSUE TITLE
Your title here

### ISSUE THREAD

**Issue by NAW-KHU** [thingsboard/thingsboard#11032]
**Component**

 
 * Rule Engine

**Description**
Thingsboard PE integration with Chirpstack version 4.8.1
Cannot send downlink data from thingsboard to chirpstack
Device type: milesight smart wall switch
Gateway: milesight UG 63
to send downlink:
downlink converter in TB integratoin:
rule node to send integration downlink: RPC_CALL_FROM_SERVER_TO_DEVICE
{
    "contentType": "TEXT",
    "data": "802911",
    "metadata": {
        "DevEUI": "eui1234567890",
        "fPort": "85"
    }
}

**Environment**

 * OS:  Window 11
 * ThingsBoard: version PE 3.6.2
 * Browser: Microsoft Edge
___________________________________________________________

**Comment by myroslav-tb** [comment]
Hi @NAW-KHU, what do you see in the event logs of the integration and downlink converter, is there any errors? 
How does your rule chain is set up?

**Comment by NAW-KHU** [comment]
Thank you for your reply.
Yes, I can see event log in my TB integration queue. When checking the downlink from incoming rule node is Ok, but for the outgoing side shows error.

{
    "queueName": null,
    "id": "9a19bffd-ff0e-412f-bb66-4c6ebf2f9354",
    "ts": 1718872644096,
    "type": "RPC_CALL_FROM_SERVER_TO_DEVICE",
    "internalType": "RPC_CALL_FROM_SERVER_TO_DEVICE",
    "originator": {
        "entityType": "DEVICE",
        "id": "93ed6d90-2ed4-11ef-96ef-cf2f3c8f0dfe"
    },
    "customerId": null,
    "metaData": {
        "data": {
            "deviceType": "ws501-915m",
            "originServiceId": "ubuntu",
            "requestUUID": "3f4c266a-ad0b-46fb-a0ec-9b721d0f46e7",
            "expirationTime": "1718872649096",
            "persistent": "false",
            "deviceName": "ws501-919m,
            "oneway": "true"
        }
    },
    "dataType": "JSON",
    "data": "{\"method\":\"setValue\",\"params\":\"{\\\"switch_1\\\":1}\",\"additionalInfo\":null}", < please check it>
    "ruleChainId": {
        "entityType": "RULE_CHAIN",
        "id": "f681deb0-2a19-11ef-b9c1-0f59aefcdd4b"
    },
    "ruleNodeId": {
        "entityType": "RULE_NODE",
        "id": "80a06490-2d30-11ef-b9c1-0f59aefcdd4b"
    },
    "valid": true,
    "andIncrementRuleNodeCounter": 3,
    "metaDataTs": 1718872644096
}
The format of chirpstack downlink:
[{
 "contentType": "TEXT",
"data": "CCkR",
"metadata": {
                      "DevEUI": "1234567890",
                      "fPort": "85"
                  }
}]

**Comment by myroslav-tb** [comment]
Hi @NAW-KHU, Please send the error description that you get with the message

**Comment by NAW-KHU** [comment]
Event time
Server
Type
Message
Status
Error
2024-06-21 15:20:26.257	ubuntu	Downlink		Message                ERROR		        
2024-06-21 15:20:26.217	ubuntu	Downlink: RPC_CALL_FROM_SERVER_TO_DEVICE	Message	OK	


Actually , there is no error message in script. the above are shown in integration queue 
Below scripts are shown in Message. Nothing errors in scripts. maybe don't know where error in scripts.
{
    "queueName": null,
    "id": "fd4c08ac-31a1-46b9-a742-b28130f345c4",
    "ts": 1718959826196,
    "type": "RPC_CALL_FROM_SERVER_TO_DEVICE",
    "internalType": "RPC_CALL_FROM_SERVER_TO_DEVICE",
    "originator": {
        "entityType": "DEVICE",
        "id": "93ed6d90-2ed4-11ef-96ef-cf2f3c8f0dfe"
    },
    "customerId": null,
    "metaData": {
        "data": {
            "deviceType": "ws501-915m",
            "originServiceId": "ubuntu",
            "requestUUID": "2566be6b-c1eb-4702-b5e9-40530ff6ab5d",
            "expirationTime": "1718959831195",
            "persistent": "false",
            "deviceName": "ws501-919m-30412",
            "oneway": "true"
        }
    },
    "dataType": "JSON",
    "data": "{\"method\":\"setValue\",\"params\":\"{\\\"switch_1\\\":\\\"on\\\"}\",\"additionalInfo\":null}",
    "ruleChainId": {
        "entityType": "RULE_CHAIN",
        "id": "f681deb0-2a19-11ef-b9c1-0f59aefcdd4b"
    },
    "ruleNodeId": {
        "entityType": "RULE_NODE",
        "id": "80a06490-2d30-11ef-b9c1-0f59aefcdd4b"
    },
    "valid": true,
    "metaDataTs": 1718959826196,
    "andIncrementRuleNodeCounter": 4
}

**Comment by NAW-KHU** [comment]
Downlink converter queue:
-------------------------------
input in downlink converter :
===================
[{
    "msg": {
        "method": "setValue",
        "params": "{\"switch_1\":\"on\"}",
        "additionalInfo": null
    },
    "metadata": {
        "deviceType": "ws501-915m",
        "originServiceId": "ubuntu",
        "requestUUID": "2566be6b-c1eb-4702-b5e9-40530ff6ab5d",
        "expirationTime": "1718959831195",
        "persistent": "false",
        "deviceName": "ws501-919m-30412",
        "oneway": "true"
    },
    "msgType": "RPC_CALL_FROM_SERVER_TO_DEVICE"
}]
output in Downlink converter to send to chirpstack"
==================================
[{
    "contentType": "TEXT",
    "data": "CCkR",
    "confirmed": true,
    "metadata": {
        "DevEUI": "24e124782d130412",
        "fPort": "85"
    }
}]

**Comment by myroslav-tb** [comment]
Hi @NAW-KHU, the errors can be checked in the events logs of the integration or the converters by pressing the three dots in error column.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/31864115-bcbf-4e05-8b49-cb5b1ff227e9)
If your error message says: Pleae contact your system administrator. You need to add `HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE=true` parameter in `/etc/thingsboard/conf/thingsboard.conf` file, so the error description will be shown in the events.

**Comment by NAW-KHU** [comment]
Yes, absolutely right. My error status is "Please contact your administrator"
I'll try it. Thank you.

**Comment by NAW-KHU** [comment]
My current thingsboard PE vesion is 3.6.1 and chirpstack version is 4.8.1.Is it compatible?
I found error in Event, it is said that:
org.thingsboard.server.common.data.exception.ThingsboardException: Possible ChirpStack API version mismatch!

**Comment by myroslav-tb** [comment]
Hi @NAW-KHU, check if the "Use API for Chirpstack 4+" is enabled in the integration settings.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/fb5dd53b-2f97-4a64-a28d-e12bd3a23448)

**Comment by NAW-KHU** [comment]
![Screenshot_29-6-2024_963_smart agb com mm](https://github.com/thingsboard/thingsboard/assets/121937857/be1b40cb-0e53-4cef-89fc-1a0227763ef3)


I already enable: chirpstack API version 4+ in thingsboard integration, however, errors still show API version is mismatch.
Please Help me!

**Comment by myroslav-tb** [comment]
Hi @NAW-KHU, currently, Thingsboard doesn't support Chirpstack version 4.8.1. Please use an older version of the Chirpstack server.

**Comment by myroslav-tb** [comment]
Hi  @NAW-KHU, if you have a docker installation, try to change the port in the application server url field to 8090. Chirpstack make changes to this endpoint and move it as  a separate service.

**Comment by NAW-KHU** [comment]
OK, I'll try it.  We use docker and port 8080 for chirpstack application server.

**Comment by NAW-KHU** [comment]
Hello, I am facing a new issue when downlink payload from thingsboard to chirpstack. Here is screenshot for reference.

![downlink_error_event](https://github.com/user-attachments/assets/f13d38ad-aa21-465f-b9e2-e96af6529e58)
![downlinkconverter_event](https://github.com/user-attachments/assets/71f48d41-273e-4772-a84b-b110edc891ab)
![Chirpstack-server-log](https://github.com/user-attachments/assets/119d99b3-ce6e-4bb2-81f1-1591ab8f1a29)
