### ISSUE TITLE
Cannot edit TTS Integration setting

### ISSUE THREAD

**Issue by dropkicktommy** [thingsboard/thingsboard#11040]
**Describe the bug**
Cannot edit TTS Integration setting

**Your Server Environment**
[ThingsBoard Cloud](https://thingsboard.cloud)
Community Edition

**Your Client Environment**
**Desktop (please complete the following information):**

OS: Windows 10
Browser: Chrome and Firefox

**Smartphone (please complete the following information):**
Device: Samsung S23 Ultra
OS: Android 14
Browser: Chrome and ABP

**Your Device**

Connectivity
  * Integration: The Things Stack Community

**To Reproduce**
1. Go to 'Integrations'
2. Create or Click on a 'The Things Stack Community' integration
3. Click the pencil to enter edit mode
4. Scroll down to 'advanced settings'
5. Try to edit the 'Downlink topic pattern*' field here

**Expected behavior**
Expect to be able to edit and save the text in this field. All other fields in this dialogue are editable. 

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Additional context**
Please feel free to add any other context about the problem here. 

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @dropkicktommy 

Thank you for reporting this issue! I passed this possible bug to our developers for review. We'll post an update when it's available.

**Comment by ashaforost** [comment]
Hi @dropkicktommy 

Returning with feedback: since the downlink topic has a strict structure, we've implemented it as an autogenerated read-only field in the integration settings. 
See more info at  [https://www.thethingsindustries.com/docs/integrations/mqtt/#publishing-downlink-traffic](https://www.thethingsindustries.com/docs/integrations/mqtt/#publishing-downlink-traffic )

So, not a bug but a feature.

**Comment by dropkicktommy** [comment]
Which is fine, but that TTS integration documentation allows two paths -
one to /push and one to /replace. This option, afaik, is not available in
the thingsboard integrations dialog.
There needs to be some option (either direct editing, as suggested - or a
toggle) to allow us to change this path as /push does is not ideal for some
scenarios. Sometimes (as in my case) /replace is the right option.
