### ISSUE TITLE
Add i18n to group descriptions

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#11052]
I would like to have the ability to have a i18n on description of groups, in my case only to use with user groups. The i18n is already working with name of the group. With this ill create user groups automatically when a customer is created, so ill have it with i18n support.

![CleanShot 2024-06-19 at 13 07 32@2x](https://github.com/thingsboard/thingsboard/assets/77509200/ce77a7f9-4ed1-422d-b280-46da55ff1b52)

**Comment by myroslav-tb** [comment]
Hi @ifelse-code, I have created a feature request for our prod team. Once they review it, I’ll post an update on when this feature could be delivered if they decide to add it to the product.

**Comment by myroslav-tb** [comment]
Please follow up on the release notes to check if the feature is added to the Thingsboard.
