### ISSUE TITLE
Upgrading a database from 3.6.1 to 3.6.2 fails on some databases

### ISSUE THREAD

**Issue by ianso-msf** [thingsboard/thingsboard#11050]
**Describe the bug**

On a postgres database where we are running a series of migration scripts from 3.4.3 to 3.7.0, we get stopped at 3.6.2PE.

The error happens when running the upgrade script as follows:

![image](https://github.com/thingsboard/thingsboard/assets/69912317/d7dc0341-38f4-4e7c-b2d4-769000ce111a)

The root error message is "column deviceprof0_.default_edge_rule_chain_id does not exist"

Checking our database schema confirms these columns are absent, while they are present in 

https://github.com/thingsboard/thingsboard/blob/c4e5ab65ee73a604cab2d374c98b232d42390517/dao/src/main/resources/sql/schema-entities.sql#L253

**Your Server Environment**
  * Deployment type: , docker-compose, 
  * ThingsBoard Version see above
  * Professional Edition
  * NixOS

**Your Client Environment**
N/A

**To Reproduce**
1. Create a blank 3.4.3 database
2. upgrade to 3.4.4 using the https://stackoverflow.com/questions/76244461/thingsboard-installation-3-4-4-to-3-5-fails-schema-udpate-postgresql-relation-a 
3. run docker-compose run mytbpe upgrade-tb.sh for 3.4.5, 3.5.0, 3.5.1, 3.6.0, 3.6.1, and then try and upgrade 3.6.2
4. ==> fails here

**Expected behavior**
the database upgrade  should not fail

**Comment by ianso-msf** [comment]
My impression is that it was introduced here:
https://github.com/thingsboard/thingsboard/commit/8174a97926dc54477d95a3d55feb616af8d9ec3c#diff-cea4eed3c583257aec6b2266bad662f448acc0879822b858ef438d9589edeb11

**Comment by pon0marev** [comment]
Use only official documentation for upgrades:
https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/


What do you mean "Create a blank 3.4.3 database"? Did you run the thingsboard installation script? https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-7-run-installation-script

The screenshot doesn't show the whole error. Attach the upgrade log: `/var/log/thingsboard/install.log`

**Comment by pon0marev** [comment]
@ianso-msf  Were you successful in upgrading to the latest version?

**Comment by ianso-msf** [comment]
Hi @pon0marev  yes, we upgraded to the latest version, and the above SQL didn't need to be applied in a system where the upgrade wasn't missed, so i think this can be closed.
