### ISSUE TITLE
Doubts about the creation process and components

### ISSUE THREAD

**Issue by rafaelnogueira1** [thingsboard/thingsboard#11053]
**Component**

 * Generic

Hi guys, good evening

I would like to know if any of you with experience in developing components for ThingsBoard could explain more or less how your creation flow works, how to generate the components and import them into the platform, if you use more direct requests to the API or perform the filters when instantiating the widgets.

I saw in the documentation that there is a plugin, but I haven't had much success using it yet. If someone could also spare a few minutes to chat, it would be very welcome.

I have been researching a lot through the repo and the docs, but I still have some doubts that I believe will only become clear by talking to someone.

I appreciate any help in advance.

**Environment**
 * OS:  name and version
 * ThingsBoard: 3.7
 * Browser: name and version

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @rafaelnogueira1 

Check out our [thingsboard-extensions](https://github.com/thingsboard/thingsboard-extensions) repository as well as the thingsboard's [guide on widget development](https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/). The latter one has some simple examples on how to develop your custom widget. 

If you have any specific questions on custom development, please list them below, so ThingsBoard community may help you.

**Comment by Vaibhav0216** [comment]
Hi @ashaforost,

I hope you're doing well. I've been working on the issue mentioned in GitHub (#11478) and have tried various solutions, but I'm still stuck. When you have a moment, could you please take a look? Your insights would be greatly appreciated.

Thank you so much for your help!
