### ISSUE TITLE
Upgrading from v3.6.4 to v3.7.0 gives login error `The given byte[] value cannot be transformed to Json object`

### ISSUE THREAD

**Issue by sprijk** [thingsboard/thingsboard#11058]
**Describe the bug**
After upgrading from v3.6.4 to ThingsBoard v3.7.0 (MSA + Kafka) I get a:
`IllegalArgumentException: The given byte[] value cannot be transformed to Json object:[-16]`
when I try to login.

It would be great to understand what has changed that could cause this behavior.
I will investigate further, but will have to roll-back shortly.

**Your Server Environment**

* own setup
  * Deployment: microservices
  * Deployment type: k8s
  * ThingsBoard Version: v3.7.0
  * Community

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser: Chrome
* Version: Latest

* Connectivity
  * HTTP

**To Reproduce**
1. Install v3.6.4
2. Upgrade to v3.7.0

**Expected behavior**
Successful login

**Screenshots**
![Screenshot 2024-06-20 110648](https://github.com/thingsboard/thingsboard/assets/2340335/0f15e193-9b62-4268-9291-d8e36716f1f4)

**Comment by sprijk** [comment]
It could have been that I did not fully flush the Redis cache!

However, after the upgrade I now have no more access to the timeseries data...

**Comment by pon0marev** [comment]
Are you using a postgres database or a hybrid database (postgres+cassandra)? Probably the hybrid database, since you would not be able to log in if the issue was with the postgres database. Check the cassandra database endpoint has not changed. Check the status of the cassandra database.
```
nodetool status
```

**Comment by sprijk** [comment]
Well, I use Postgres + TimeScaleDB. Not sure if this is _really_ supported..

**Comment by sprijk** [comment]
So, I've set-up everything new. Kafka saved me on the timeseries data ;)

**Comment by sudhirbits** [comment]
We encountered this issue in docker installation tb. We use an in memory queue but external postgres database and external redis cache. The issue was with the external REDIS cache was not upgraded. May be that's not supported for docker installation. But after reverting the cache to use internal caffeine cache and restarting the server resolved this issue for us.

**Comment by pon0marev** [comment]
@sudhirbits You may have upgraded TB without connecting to an external Redis server or not sequentially (version by version). So you may have had this issue.
If Thingsboard does not find the keys in the Redis cache, it will query the database. So you can safely clear the entire cache to fix such an issue.
```
redis-cli flushall
```
