### ISSUE TITLE
3.4.1 deb install successfully but failed to install by install.sh 

### ISSUE THREAD

**Issue by langlichong** [thingsboard/thingsboard#11059]
**Describe the bug**
-  I download the 3.4.1 tag 
-  use maven to compile at Microsoft Windows  23H2(OS inner 22631.3737) and idea 2024.1.2 after maven install phase , get the thingsboard.deb 
- upload it to ubuntu 20.04.5 LTS (Focal Fossa) server
-  then sudo dpkg -i thingsboard.deb  , there is no errors
- final to exec install.sh : sudo /usr/share/thingsboard/bin/install/install.sh , and get error
```
 sudo: unable to execute /usr/share/thingsboard/bin/install/install.sh: No such file or directory
```
- then to check the file , it exist rightly  , is the deb package must be built at the target os (for me is ubuntu) , i have no idea , please help

**Your Server Environment**

* own setup
  * Deployment: monolith 
  * Deployment type: deb
  * ThingsBoard Version: 3.4.1
  * Community 
  * OS Name and Version：ubuntu 20.04.5 LTS (Focal Fossa) server

**Expected behavior**
  how to fix such problem to exec the install.sh 

**Screenshots**
-  error and file exist check
![image](https://github.com/thingsboard/thingsboard/assets/11713419/155f657b-f615-45b8-8244-04ab6a0b0feb)

- os info
![image](https://github.com/thingsboard/thingsboard/assets/11713419/ebe635f5-cc98-42ed-9735-06e259d69def)

**Comment by Ultrazombie** [comment]
Hello @langlichong 
Could you please provide content of /usr/share/thingsboard/bin/install/install.sh file?

**Comment by langlichong** [comment]
- as the attach files not support the  .sh suffix , so i added a .x to end , please removed before used

**Comment by langlichong** [comment]
- as github not support the .sh attach files , so i changed it to .json 
[install.json](https://github.com/user-attachments/files/15921680/install.json)

**Comment by langlichong** [comment]
i found that after installing the thingsboard.deb that build from windows , the /usr/share/thingsboard/bin/install/install.sh and the config file /usr/share/thingsboard/conf/thingsboard.conf are all dos format , after set the fileformat to unix with ':set ff=unix' , then the install.sh can be successfully , but when access from browser the js has errors :
![image](https://github.com/thingsboard/thingsboard/assets/11713419/7802c79d-5943-4195-850e-24a82e554e0f)

**Comment by pon0marev** [comment]
Are you trying to build a clean version of thingsboard on a windows machine? Or have you already implemented some changes? 
Does the service work after installation according to the instructions in the documentation https://thingsboard.io/docs/user-guide/install/windows/ ?

**Comment by pon0marev** [comment]
We want to inform you that we have closed your ticket as we have not received any updates on this issue. If you still have questions or encounter similar issues after upgrading to the latest version, please reopen this issue.
