### ISSUE TITLE
Deleting notification requests from database

### ISSUE THREAD

**Issue by kojievo** [thingsboard/thingsboard#11065]
**Component**

 * Notifications

**Description**
I am trying to deleted all notifications related data. I already deleted all notifications via API, but then realized that I also have to delete the notification requests that remained. Is it safe to delete all data from the notification_request table in the database with a truncate cascade command?

**Environment**

 * OS:  Debian buster
 * ThingsBoard: 3.5.1

**Comment by trikimiki** [comment]
Hi!

> Is it safe to delete all data from the notification_request table in the database with a truncate cascade command?

If all related notifications are deleted, it is safe to do so.
