### ISSUE TITLE
Notification Templates Modify/Add Parameters

### ISSUE THREAD

**Issue by alanlgirard** [thingsboard/thingsboard#11066]
**Component**

 * Generic

**Description**
Currently using the notification center templates in TB PE to send emails for things like new alarms.  Is it possible to modify the available parameters or add our own parameters?

An example modification would be for an alarm template
Parameter: alarmStatus
Returns as ACTIVE_UNACK for example, but I would like it to return as Active Unacknowledged

Example of a parameter addition to return the device label instead of the name
Parameter: alarmOriginatorLabel

**Environment**
 * ThingsBoard: 3.7 PE

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sprijk** [comment]
should be pretty easy as this information is alread present in `AlarmInfo`
https://github.com/thingsboard/thingsboard/blob/633411f9e13bbdfb9907dd8ac5bb44507d463937/common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmInfo.java#L39
and add `.alarmOriginatorLabel(alarmInfo.getOriginatorLabel()` under this line
https://github.com/thingsboard/thingsboard/blob/633411f9e13bbdfb9907dd8ac5bb44507d463937/application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmAssignmentTriggerProcessor.java#L64

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by Tasosgi** [comment]
Do you mean that adding .alarmOriginatorLabel(alarmInfo.getOriginatorLabel() to AlarmAssignmentTriggerProcessor.java would enable the use of alarmOriginatorLabel as Alarm notification templatization parameter?

**Comment by sprijk** [comment]
well, I hope! I did not try this out yet. I am not too familiar with the code base yet

**Comment by Tasosgi** [comment]
I am not sure. The constructNotificationInfo function already includes various parameters, but they do not seem to work for templating—for example, .alarmCustomerId

**Comment by Tasosgi** [comment]
Maybe if also added here 

https://github.com/thingsboard/thingsboard/blob/f21275b4bd83d46149358fdc964852f1841b05cb/common/data/src/main/java/org/thingsboard/server/common/data/notification/info/AlarmNotificationInfo.java#L60
