### ISSUE TITLE
Triggering a function from a different widget

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard#11078]
Hello, 

I was working with thingsboard widgets. In one of the widgets i have a form and in the second widget i have a map. I wanna update the map base on the parameters that the user has introduced in the form. For example, i have a mat-select like the one in the following image

![image](https://github.com/thingsboard/thingsboard/assets/151906929/e30ec2f2-3d42-480a-bec4-5a28af7001a2)

I added this function in the html so that when there is an update,  trigger that function (ngModelChange)="updateElement()". If the function is in the same widget it works but i wanna now if there is a possibility to trigger a function defined in another widget.

**Comment by devdoob** [comment]
Write this in your first widget to broadcast any change

let broadcastService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('broadcastService'));
broadcastService.broadcast('my-custom-event', {
    value: 'Hello World'
});

Write this in your second to receive whatever broadcasted from first widget.

broadcastService.on('my-custom-event', (event, data) => {
   console.log(data);
});
