### ISSUE TITLE
Trendz Widgets breaking in Thingsboard

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#11073]
Hello,

I am developing some widgets using a "Trendz View" widget. However, I occasionally encounter an error where the widget renders as "TRENDZ VIEW FILTER WITH ALIAS" instead of displaying properly. This issue typically when I select a different device or make changes to attributes. It also sometimes occurs when the widget loads upon entering the dashboard. Most of the time, the widget works correctly, but these errors disrupt its functionality.

The error is:
![image](https://github.com/thingsboard/thingsboard/assets/98624393/28c52d12-e8bd-4adb-8701-dfbea842fe41)

In the dashboard I have something like this
![image](https://github.com/thingsboard/thingsboard/assets/98624393/47ab719a-1a3c-4eee-bee7-a0c3167f8a13)

The normal way would be this
![image](https://github.com/thingsboard/thingsboard/assets/98624393/02df932b-a039-48bf-9e90-dc21501436bc)

Thank you and best regards.

**Comment by yuliaklochai** [comment]
Hi!

To resolve this issue, update your Trendz version to the latest one. Then, update the widget bundle version from the Settings page of your Trendz instance.

**Comment by nicovon24** [comment]
Hello,

I have tested the new widgets bundle and updated it on the dashboard. However, I encountered an issue: I had to recreate each widget individually. This process is not practical, especially if I have multiple widgets to manage.

Is there a way to resolve this issue?

Thanks and regards

**Comment by yuliaklochai** [comment]
HI!

Could you please send a screenshot of the issue you're encountering with the Trendz widget on the dashboard ?
We suspect this problem may be related to recent changes in the widget-saving logic, but we need to verify this.

**Comment by nicovon24** [comment]
Hello, yes of course, here it is the widget with the scrollbar which i could not delete in the Trendz Widget
Thanks @yuliaklochai !

![image](https://github.com/thingsboard/thingsboard/assets/98624393/18d135d6-87b6-4465-bbc1-33949ca254d1)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/370f290a-d203-4aab-9dc2-b2b2e43fa446)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/7459e161-860d-495a-9b4e-36f89936e152)
![image](https://github.com/thingsboard/thingsboard/assets/98624393/eec4ff7d-d3c6-441c-9279-b1a53226cd5f)

**Comment by yuliaklochai** [comment]
What type of Trendz widget do you use: Trendz View Latest, Trendz View Static, or Trendz Builder? 
You can check it while opening the widget edit menu.

**Comment by nicovon24** [comment]
Hello, Trendz View i am using, for allowing me to make filters and select the current asset/device.
Thanks @yuliaklochai !

**Comment by yuliaklochai** [comment]
@nicovon24 it looks like you are using the Trendz Builder Widget. It's deprecated, which could cause problems such as an unwanted scrollbar. I recommend transferring your views from Trendz Builder to Trendz Static or Latest, depending on your use case.
**Trendz View Static** allows adding saved Trendz visualizations into ThingsBoard dashboards.
**Trendz View Latest** is similar to the previous but also supports dashboard aliases for resolving entities.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
