### ISSUE TITLE
how to change filter after getFilters()

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#11075]
Hello.
I want to change the filter through custom action.
I execute `widgetContext.aliasController.getFilters();` and display its value in the console as shown below.
![filter](https://github.com/thingsboard/thingsboard/assets/45573721/bc69ea2f-1ec8-4603-abed-e3e613f9bfe2)
how can I change the value of the filter to what I want?

**Comment by m3relec** [comment]
hello.
I changed the objects related to the filter and then updated it, but there was no change.
`const filters = widgetContext.aliasController.getFilters();
filters["23e1d1d7-9865-114d-f2a1-273ce541ebcf"].keyFilters[0].predicates[0].keyFilterPredicate.value.dynamicValue=false;
filters["23e1d1d7-9865-114d-f2a1-273ce541ebcf"].keyFilters[0].predicates[0].keyFilterPredicate.value.userValue=false;
widgetContext.aliasController.updateFilters(filters);
widgetContext.aliasController.updateUserFilter(filters);`
What else should I do?

**Comment by devaskim** [comment]
The dashboard has configuration option to show its filters, so you can update filter criteria through UI. Thus ff after updating the value in UI, data is being filtered on the dashboard, it means something wrong in your code above.

**Comment by m3relec** [comment]
thanks @devaskim
I change all three parameters `dynamicValue` , `userValue` , `defaultValue`.
And then I execute `widgetContext.aliasController.updateFilters(filters);` and `widgetContext.aliasController.updateUserFilter(filters);`.
And I check the changes in the log console and see that it changes.

**Comment by devaskim** [comment]
`widgetContext.aliasController.updateUserFilter(...)` [expects single filter](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/alias-controller.ts#L450), but you pass all filters

**Comment by m3relec** [comment]
Please give an example if possible.
I don't know exactly how to give a filter to the input of this function.
@devaskim

**Comment by devaskim** [comment]
> I don't know exactly how to give a filter to the input of this function.

```
const filters = widgetContext.aliasController.getFilters();

let yourFilter = null;

// find filter by its name (name is specified in dashboard filters window)
const filterName = "Some Filter Name";
  for (const filterId in filters) {
      if (filters.hasOwnProperty(filterId) && filters[filterId].filter === filterName ) {
           // I don't remember why sometime ago the filter is stringified and then is parsed again
           yourFilter = JSON.parse(JSON.stringify(filters[filterId]));
      }
  }

if (!yourFilter ) {
    // cannot find filter
    return;
}
.... update filter values ....

widgetContext.aliasController.updateUserFilter(yourFilter);

**Comment by m3relec** [comment]
thanks a lot @devaskim.
it will work very well.

**Comment by jrkubic** [comment]
> > I don't know exactly how to give a filter to the input of this function.
> 
> ```
> const filters = widgetContext.aliasController.getFilters();
> 
> let yourFilter = null;
> 
> // find filter by its name (name is specified in dashboard filters window)
> const filterName = "Some Filter Name";
>   for (const filterId in filters) {
>       if (filters.hasOwnProperty(filterId) && filters[filterId].filter === filterName ) {
>            // I don't remember why sometime ago the filter is stringified and then is parsed again
>            yourFilter = JSON.parse(JSON.stringify(filters[filterId]));
>       }
>   }
> 
> if (!yourFilter ) {
>     // cannot find filter
>     return;
> }
> .... update filter values ....
> 
> widgetContext.aliasController.updateUserFilter(yourFilter);
> ```

I'm tying to update my image map widget by doing this in an action. The last line doesn't update the image map to include a filter. Do you have any solution to updating the widget with the retrieved filter?

**Comment by devaskim** [comment]
@jrkubic TB lets editing the input data of filter via UI, try to set the same data via UI as you did programatically and then check if any changes appear on the map.

**Comment by jrkubic** [comment]
I understand I can edit the filter via the UI. The reason I want to do it programmatically is so that I can update the widgets current filter based on an action.

I know how to set the filter in the UI. Now, I want to change and update the filter based on an action.
```
widgetContext.aliasController.updateUserFilter(yourFilter);
```

Does not update anything.

**Comment by devaskim** [comment]
@jrkubic The main idea of my suggestion was not to find alternative, but check how map widget will react on updating filter's data in such way. So now you know that it works) , thus you can look up at websocket session (via browser console) and check what changes are in the filter while editing via UI and compare it to what you have by doing the same programatically.

**Comment by jrkubic** [comment]
Great idea. 
I tried to do something similar but didn't quite know where to check to see these sort of changes. 

Thanks for the direction. I'll get it working and will let you know how the new Image Map behaves/if I find a quick solution.

**Comment by jrkubic** [comment]
@devaskim 
So tried your recomendation but there is zero changes or updates in the websocket session when changing the filter via UI. (To try and see what's happening on the back end)

So I have nothing to help me find how the filter gets set usually. 
Not sure if it's because of the new Image Map and how it handles the markers under the hood?

**Comment by devaskim** [comment]
> To try and see what's happening on the back end

https://github.com/user-attachments/assets/da36dcad-1e66-4cc6-a619-a164cdd557d6

@jrkubic As you can see from the video, after manually updating the input value of the filter, this value was send to the backend. It is possible to do the same programatically in your widget.
