### ISSUE TITLE
Mixing up execution order of two chain rules which run on events coming sequentially with small delay 

### ISSUE THREAD

**Issue by govnoid** [thingsboard/thingsboard#1107]
Configuration: Thingsboard v2.1.0 running on Windows 8.1 using internal database.

Thingsboard has root chain which analyzes output from sensor device and two child chains which turn on and off actuator device based on "on" and "off" signal from sensor. 
Root:
![image](https://user-images.githubusercontent.com/9403780/46372433-cb69c980-c693-11e8-9ee2-a3a89e7ea09b.png)

Alert chain:
https://files.gitter.im/thingsboard/chat/Jx6X/image.png
![image](https://user-images.githubusercontent.com/9403780/46372578-3ca97c80-c694-11e8-8097-b0b74b1e0972.png)
(reset alert chain is the same, but with different rpc call payload)

I found that if sensor sends two or more signals sequentially in very short timeframe (several milliseconds) the rule engine can mix up execution order. For e.g.: if sensor is sending "On" signal and after 10 milliseconds sending "Off" signal it can lead to situation when first will be executed Rpc call to turn off actuator and then rpc call to turn on which is not right.

So what i found of log nodes of rule chains:
`
2018-10-01 13:24:01,176 [pool-31-thread-1] INFO  o.t.rule.engine.action.TbLogNode - Incoming message:
{**"pin2":1,"internalTS":60238**}
Incoming metadata:
{"deviceType":"motion sensor","deviceName":"Motion sensor controller",**"ts":"1538389436504"**}

2018-10-01 13:24:01,176 [pool-31-thread-1] INFO  o.t.rule.engine.action.TbLogNode - Incoming message:
{**"pin2":0,"internalTS":60347**}
Incoming metadata:
{"deviceType":"motion sensor","deviceName":"Motion sensor controller",**"ts":"1538389436551"**}

2018-10-01 13:24:01,520 [pool-31-thread-1] INFO  o.t.rule.engine.action.TbLogNode - Log control Incoming **off** message:
{}
Incoming metadata:
{"deviceType":"motion sensor","deviceName":"Motion sensor controller",**"ts":"1538389436551"**}

2018-10-01 13:24:01,723 [pool-31-thread-1] INFO  o.t.rule.engine.action.TbLogNode - Log control Incoming **on** message:
{}
Incoming metadata:
{"deviceType":"motion sensor","deviceName":"Motion sensor controller",**"ts":"1538389436504"**}
`

InternalTS is internal tick counter in sensor device. When pin2 = 1 actuator should receive "On" message, when pin2 = 0 actuator should receive "Off message".  But in this case thingsboard sends "Off" message initially. Which is wrong.

**Comment by ashvayka** [comment]
Yes, this may indeed happen in case of concurrent execution for some nodes. For example, JS executors use pool of executor thread. Similar for persisting to DB. I am trying to say that messages are delivered to rule engine in correct order, but this is more an issue of particular rule nodes. How to solve it? Maybe execute all JS sequentially and same for DB. But this will be a huge performance issue (degradation). Need to think about this more. I have an idea to introduce "sequential" rule node mode that will execute all messages in a sync mode (affects performance). This is a huge refactoring and I hope we can find a better idea. 

Community is welcome to suggest solution strategy

**Comment by absinthetized** [comment]
Just idiotic idea of 21:00. 

What about a deterministic "lane"? I'm thinking about a special channel where data requiring strict timing can be instradated. All will run async in the pool but a special (not redundant unfortunately) node can be designed to get hi freq deterministic signals/events.

How to implement? NO IDEA. But this bug seems mostly related to the need of special deterministic execution which can be obtained giving a special lane to telemetry rather than recoding the entire stuff from the ground up.

Just my 2 cents.

**Comment by Ultrazombie** [comment]
Hello @absinthetized 
If your idea is still relevant, please create a fresh issue with your proposition :)

Thanks
