### ISSUE TITLE
Bulk Device Delete fails with 20 or 30 selected devices

### ISSUE THREAD

**Issue by YakupOguzhanKaya** [thingsboard/thingsboard#11083]
**Describe the bug**
When user tries to delete 20 or 30 devices at the same time, process fails to delete them all and gives a error notification.

**Your Server Environment**
* own setup
  * Deployment: microservices
  * Deployment type: docker-compose
  * ThingsBoard Version: 3.7.0
  * Community Edition
  * OS Name and Version: Ubuntu 22.04.4 LTS

**Your Client Environment**
Desktop

* OS: Windows 11
* Browser Edge
* Version: 126.0.2592.56

**To Reproduce**
1. Create 30 devices.
2. In devices page, make page size to 30.
3. Click check all button on top and see "30 devices selected"
4. Click Delete button to remove all 30 devices.

**Expected behavior**
All 30 devices should be removed.

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/34554093/4d71d492-9e9a-460d-9f3c-045c4f71ee70)

**Additional context**
It's a bit long gif, please watch until error occurs.
![thingsboard_device_deletion](https://github.com/thingsboard/thingsboard/assets/34554093/1cb9d7eb-29b7-472a-a75d-f2f57240f6e1)

**Comment by ViacheslavKlimov** [comment]
Hi @YakupOguzhanKaya,

There should be something related in the logs, please check.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
