### ISSUE TITLE
Is possible to import device telemetry by csv ?

### ISSUE THREAD

**Issue by kiraten191010** [thingsboard/thingsboard#11080]
**Component**

 * Rule Engine
 * Generic

**Description**
I have a log data is csv file . This log file have 19 type of key and a total of 200,000 pieces of data   I want to import all data into thingsboard device telemetry . 
How should I do ?

**Environment**

 * OS:  Windows10
 * ThingsBoard: 2.0.1
 * Browser: firefox

**Comment by sjthings** [comment]
If this data is available in JSON format, then you can publish this data using any MQTT client application.
The payload format has to be 
[{
    "ts": 170000020,
    "values": {
        "key1": "value1",
        "key2": "value2"
    }
 },
{
    "ts": <timeinms>,
    "values": {
        "key1": "value1",
        "key2": "value2"
    }
},
{
    "ts": <timeinms>,
    "values": {
        "key1": "value1",
        "key2": "value2"
    }
}]

**Comment by kiraten191010** [comment]
Thank you so much
