### ISSUE TITLE
Aggregating Telemetry Data from Various Devices in a Widget

### ISSUE THREAD

**Issue by Vitor-Gabriel-KR** [thingsboard/thingsboard#11088]
Hello ThingsBoard Team and Users,

I'm working on creating a widget that displays the total of a specific telemetry key from multiple devices. I am using ThingsBoard v3.7PE. Below is a detailed description of my setup and the issue I'm facing:

Setup:

I have several devices sending telemetry data, which originate from an IoT Gateway.
(device telemetries image)

![341859333-6327a182-feeb-4c78-9a34-70bdc5643fb9](https://github.com/thingsboard/thingsboard/assets/116317977/c4eb1130-1026-4fbe-a222-5d783608a8c2)

(gateway)
![341859899-15eaabe7-34a3-4d1f-bab7-a3659198e359](https://github.com/thingsboard/thingsboard/assets/116317977/74319a9a-18b6-4e9b-9f40-e326a5808607)

I have created an entity alias that returns an array of these devices.
![341859065-574f6322-83b9-4428-a437-b89c82c71d89](https://github.com/thingsboard/thingsboard/assets/116317977/34cfb46a-eb47-44e4-812e-6ebb06560f96)

I need assistance in creating a widget that shows the real-time sum of "ActivePower" received from all devices. I believe this can be achieved both in the widget and using a Rule Chain. Can someone guide me on how to accomplish this in both methods? I found an example in the documentation on subtraction using Rule Chain, but it was not helpful.

**Comment by wagnerpch** [comment]
Hi, i have the same issue. 

I'm using Thingsboard CE and needs to aggregating telemetry data from thousands of devices in unique value to display on chart or table. 

At the moment i'm thinking on use widget html with API requests, but i know this approach is not the best way for performance. 

So if you could share your solution, it will be very helpfull.

Best reguards.

**Comment by Vitor-Gabriel-KR** [comment]
hi , we already solve this issue look the next post to now how

**Comment by xtaveira** [comment]
@wagnerpch you just have to use a rule chain, follow this documentation bellow

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/

**Comment by Vitor-Gabriel-KR** [comment]
> @wagnerpch you just have to use a rule chain, follow this documentation bellow
> 
> https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/

this was how i solved the issue
