### ISSUE TITLE
Image URL for uploaded image

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#11081]
I have uploaded a image in image gallery of TB. Now I want to access the path of this image in advanced CSS, how can I access the same. 
I can access an external image in CSS as below - 
   background-image: url("https://other.com/wp-content/uploads/2022/04/process.png");

However, what should be the url for images uploaded in "image gallery" in resources section.

**Comment by Backdraft007** [comment]
In the image gallery you can popup the url. There is the path of the image. I think you can use src in your CSS. I don't try it. :)
![Screenshot 2024-06-25 093431](https://github.com/thingsboard/thingsboard/assets/8741669/3b38f025-e744-49b4-9e3a-3b2a4b592139)

**Comment by sjthings** [comment]
Yes, this worked.
