### ISSUE TITLE
[Bug] State label in device table should consider enabled PERSIST_STATE_TO_TELEMETRY server option

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#11085]
When i change PERSIST_STATE_TO_TELEMETRY to true, and execute sql 'CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_ts_view;'. 
But when i open device page, all device state are inactive.
![image](https://github.com/thingsboard/thingsboard/assets/81666438/a7c67fde-93ca-4529-a1b0-0c2a4d6dd8e3)

**Comment by pon0marev** [comment]
What database do you use to store time series data? Is it a Postgres or hybrid (Postgres + Cassandra) database?

**Comment by xiddjp** [comment]
My database is postgresql+cassandra. And DATABASE_TS_LATEST_TYPE is cassandra too.

**Comment by ViacheslavKlimov** [comment]
The recommended approach is to use PostgreSQL to store latest telemetry. 
Unfortunately, in this case, it won't work with Cassandra as the storage for latest.
Same goes for dashboards: some functionality won't work.

**Comment by ViacheslavKlimov** [comment]
To migrate the latest telemetry from Cassandra to PostgreSQL, change the `DATABASE_TS_LATEST_TYPE` to `sql` and run the upgrade script with `cassandra-latest-to-postgres` as fromVersion.

**Comment by pon0marev** [comment]
@xiddjp  Overwrite operations in Postgres are more optimized than in Cassandra. Cassandra databases are good for long-term storage of historical data but not for updating the latest data frequently. Therefore, it is better to store ts_latest in postgres.
