### ISSUE TITLE
  ts_key_value_partitioning: "${SQL_POSTGRES_TS_KV_PARTITIONING:MONTHS}"  

### ISSUE THREAD

**Issue by esthergpe** [thingsboard/thingsboard#11082]
En donde modfico esto:   ts_key_value_partitioning: "${SQL_POSTGRES_TS_KV_PARTITIONING:MONTHS}" 

Estoy instalando Thingsboard y me pide modificar esto y no encuentro donde se hace.

Espero me puedan asesorar

  Gracias por su apoyo

**Comment by Backdraft007** [comment]
Is it a fresh installation or an upgrade?
Which version and which environment? Some more details please.
And write in english please.

**Comment by Ultrazombie** [comment]
Closed due to inatctivity
