### ISSUE TITLE
Add the ability to consume APIs via the Oauth2 provider access token

### ISSUE THREAD

**Issue by maghibus** [thingsboard/thingsboard#11094]
When configuring authentication via the OAuth2 protocol, it would be desirable to allow the possibility of invoking the platform APIs using the access token provided by the IAM

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Ultrazombie** [comment]
Thank you for suggesting this feature! We appreciate your input. This feature is already in our backlog, but due to its complexity, we won't be able to implement it in the near future. It's currently a low priority. Closing this ticket as this feature is already tracked.
