### ISSUE TITLE
Python REST API client, creating a dashboard with assigned customer not working.

### ISSUE THREAD

**Issue by TobyWans** [thingsboard/thingsboard#11099]
**The bug**
When creating a dashboard with an assigned customer, it does not assign the customer to the dashboard, it saves correctly but without a customer.

**Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)

**Client Environment**
* OS: Windows 11
* Browser: Firefox
* Version 127.0.1

**Device**
* Connectivity
  * MQTT

**To Reproduce**
```python
# 1. Create a short customer
short_customer = ShortCustomerInfo(public=False, customer_id="<Customer ID>", title="Test Customer")

# 2. Create the dashboard
with open("data/dashboards/test_dashboard.json", "r") as file:
            dashboard_json = json.load(file)

dashboard = Dashboard(
    title="Test Dashboard",
    configuration=dashboard_json['configuration'],
    assigned_customers=[short_customer]
)
# 3. Save the dashboard
client.save_dashboard(dashboard)
```
**Expected behavior**
To get a dashboard that has the customer as an owner.

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/62607977/b124f8b3-ebcf-4d04-85f2-3354a64858b6)

**Comment by Ultrazombie** [comment]
Hello,

Could you please create a ticket on the REST API client GitHub issue, as the question pertains explicitly to REST API?

Thank you.

https://github.com/thingsboard/thingsboard-python-rest-client/issues
