### ISSUE TITLE
Daily consumption based on meter reading

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#11090]
I need to get daily and monthly consumption of energy and water from utility meter. The meter provides accumulated readings and I need to calculate the consumption before displaying on dashboard. How can this be achieved. I wish to display a bar chart for daily consumption similar to "water metering" use case. Please help. 

Also, I tried delta node in rule chain, however data received from device are not in sequence with respect to time, hence the calculations going wrong.

**Comment by sjthings** [comment]
Further update: this specific use case is mentioned with enrichment node  to calculate delta
[https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/]
However, this does not work if we send multiple packets with different timestamp in single message. All messages gets processed in milliseconds and hence, delta calculation is messed up. I tried with delaying the message, but still if there are multiple packets in single POST_TELEMETRY all get processed in millisecond delay.

**Comment by myroslav-tb** [comment]
Hi @sjthings, If you are using the comunity edition only way to calculate the consumption is write a custom script that will do the job.
If you using the professional edition you can use aggregate latest rule node https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/analytics-nodes/

**Comment by myroslav-tb** [comment]
I'm closing this ticket due to inactivity.
