### ISSUE TITLE
Thingsboard upgrade from 3.6.4 to 3.7.0 (docker thingsboard container)

### ISSUE THREAD

**Issue by fernandobarreto** [thingsboard/thingsboard#11098]
Hi,
I tried to follow the steps from (https://hub.docker.com/r/thingsboard/tb-cassandra/) in order to upgrade the docker thingsboard container from 3.6.4 to 3.7.0. However I'm having problems with the command "docker run -it -v /opt/thingsboard/mytb-data:/data --rm thingsboard/tb-cassandra upgrade-tb.sh" , which presents the message below indefinitly righ after postgre start:

Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
........

Has anyone already checked this?

Thanks,

**Comment by LukaszDuss** [comment]
I have the same issue with fresh install.

**Comment by salvogs** [comment]
same issue, i'm trying to upgrade from 3.6.3 to 3.7.0

**Comment by domotica-undici** [comment]
same issue here

**Comment by yfan41** [comment]
same here.

**Comment by myroslav-tb** [comment]
Hi everyone, we have found an issue with the tb-cassandra image, and our team is working on resolving it

**Comment by LukaszDuss** [comment]
> Hi everyone, we have found an issue with the tb-cassandra image, and our team is working on resolving it

Any ideas when will it be available?

**Comment by myroslav-tb** [comment]
Hi @LukaszDuss, there is no ETA yet.

**Comment by rosiste** [comment]
Same issue, i'm trying to upgrade from 3.6.3 to 3.7.0. Any news after two weeks?

**Comment by myroslav-tb** [comment]
Please follow up on the release notes to check if the bugfix has been added to the Thingsboard.

**Comment by domotica-undici** [comment]
cannot see any solution. still the same problem and unable to upgrade from 3.6.4 to 3.7. 
just for testing purpose, i've tried a brand new installation with 3.7 cassandra and same results: cassandra wont start.
any thoughts?

**Comment by rosiste** [comment]
> cannot see any solution. still the same problem and unable to upgrade from 3.6.4 to 3.7. just for testing purpose, i've tried a brand new installation with 3.7 cassandra and same results: cassandra wont start. any thoughts?

@myroslav-tb Please reopen this issue and label it as Bug not Question as there is the same situation after 2 months with no solution how to upgrade from 3.6.4 to 3.7. Tried new installation with persistent data but with same result "Wait for cassandra db to start..." after update/new install. Thanks.
