### ISSUE TITLE
Telemetry TTL (retention) based on Device

### ISSUE THREAD

**Issue by cos-gl** [thingsboard/thingsboard#11095]
**Thingsboard CE 3.7.0**

 * Rule Engine
 * Generic

**Description**
Is possible to configure retention (TTL) for events based on Device? I need to mantain telemetry events for 5 years for all my devices except for one that I need to mantain only for few days.
I'm aware of event-based TTL (configured in rule chain) but I'm using Postgres only (not Cassandra). 
Any suggestion? Thanks a lot

**Environment**
 * OS:  Ubuntu 24.04 LTS
 * ThingsBoard: 3.7.0
 * Database: Postgresql without timescaledb

**Comment by pon0marev** [comment]
TTL for postgres database is implemented using SQL function, so it is not possible to configure TTL for only one device. You can develop your own TTL logic based on rule chains, using the following nodes: "generator", "rest api" node to receive token, "script" node and "rest api" node to delete timeseries. It might look something like this:
![image](https://github.com/thingsboard/thingsboard/assets/44898346/b3e8d4cd-4d31-42bf-8c17-ef24d38dcfc9)

Use the following query to get the JWT token: https://demo.thingsboard.io/swagger-ui/#/login-endpoint/post_api_auth_login
Use the following query to delete timeseries data: https://demo.thingsboard.io/swagger-ui/#/telemetry-controller/deleteEntityTimeseries
REST API documentation: https://thingsboard.io/docs/reference/rest-api/

**Comment by cos-gl** [comment]
Thanks @pon0marev ,
su basically you are suggesting to delete messages using rest api and that is ok! But I'm not sure how the complete chain would work. I'm trying to guess:
- is the generator block used to "trigger" the retention process? Eg. I want the cleanup happens once a day, the block could generate an event every 24 h?
- the script block will give back - for example - the device ID for which I want to clean data, right?

Do I understand correctly?

Thanks again for your help!

**Comment by pon0marev** [comment]
The generator is allowed to send messages once every 24 hours. However, note that the timer is reset when the generator node is changed or the thingsboard is restarted.
The script node is mainly needed to calculate timestamps, but you can define other variables as well.
![image](https://github.com/thingsboard/thingsboard/assets/44898346/b80bc899-883c-4dc0-9c8a-4141097e63bc)

You can also use the node script to duplicate messages, for example if you need to delete data from multiple devices in the future. (return can use array of objects).
![image](https://github.com/thingsboard/thingsboard/assets/44898346/59b752c8-82ba-4f26-8d42-d886d4a791e5)

**Comment by cos-gl** [comment]
Thanks again @pon0marev,
is there a way, using API, to delete telemetry items for all the keys of the device? 
Thanks

**Comment by pon0marev** [comment]
You need to be sure to specify the keys in the API request. You need specify as comma-separated list of telemetry keys.
You can use the getTimeseriesKeys api request to get all the device keys.

**Comment by cos-gl** [comment]
@pon0marev apologize for the insistence, delving into the construction of the rule chain some more questions arise and I cannot find help in the documentation (could be my fault).
- you say to use Rest Api Call to get the JWT Token. I'm not able to accomplish this. I generate a message with username and password and pass this information to Rest Api Call block (I hope I understand correctly) 

```
// Generator block //
var configuration = {
    username: "administrator@thingsboard.org", 
    password: "xxxxxxxx"
}; 
var currentTimestamp = Date.now();

var metadata = {
    delete: 1,
    ts: currentTimestamp
};
var msgType = "POST_TELEMETRY_REQUEST";

return {
    msg: configuration,
    metadata: metadata,
    msgType: msgType
};
```
but the output of Rest Call is a failure: 
```
java.lang.IllegalArgumentException: Illegal base64 character 40 [...]
```

- another question: how can I get the JWT Token from rest api call block? Will it be written in the output msg?

Thanks again!

**Comment by pon0marev** [comment]
@cos-gl  Are you sending a POST request? 
Does your password have special characters? Try changing your password with only alphabetical characters and numbers.

**Comment by cos-gl** [comment]
Yes! For sure I'm using a POST request! I've tried with cURL and also Powershell, no problems. The password has only letters and number... no luck. Only "special" char is the '@' in the username. Off course all could be base64 encoded but I thought API block managed this (eg like curl). I will give another try

**Comment by pon0marev** [comment]
Try to import the following rule chain and get the token using it:
[get_token.json](https://github.com/user-attachments/files/16313455/get_token.json)

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
