### ISSUE TITLE
[feature] We highly recommend using ClickHouse for storing events.

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#11091]
ClickHouse is an OLAP (Online Analytical Processing) database management system known for its exceptional performance and flexibility in handling massive amounts of data. It has gained popularity among many enterprises, especially for log data storage and analysis. Here are some advantages of ClickHouse in this regard.

We are one of the leading charging pile aggregation platforms in China, connecting over 2 million charging piles. Last year, we extended the open-source version of ThingsBoard by using ClickHouse to store events for over 8 months without encountering any issues. This resulted in significant efficiency improvements for our business team. In our daily operations, our team typically needs to analyze the quality of charging piles and the order data loop based on charging pile message data. This data is usually stored in large quantities in the `rule_node_debug_event` table. Our production environment consistently operates with critical rule nodes in debug mode. PostgreSQL's storage efficiency and analysis efficiency for massive datasets are evidently not as good as ClickHouse, which is why we adopted ClickHouse.

Now, I would like to share this functionality with the ThingsBoard open-source community and hope it will be considered.

**Comment by ashaforost** [comment]
Hi @baigod 

Thank you for your suggestion.
However, we do not plan to change the thingsboard architecture and add new dbms in the near future. As a feature request for the ThingsBoard development team, it's rejected. Nevertheless, feel free to contribute to the open-source version of thingsboard, we will review it, and it may become an addon for thingsboard.
