### ISSUE TITLE
how to save or edit timeseries data in custom action?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#11108]
Hello.
How can I record a new telemetry data or edit the previous telemetry data through custom action?

**Comment by mykhailokornieiev** [comment]
Hi
You can use either `attributeService.saveEntityTimeseries() `controller that will save the latest value:
```
const entityId = 'ENTITY_ID';
const timeseriesScope = 'timeseries';
const timeseries = [{ key: 'timeSeriesKey1', value: 'value1' }]; 
attributeService.saveEntityTimeseries(entityId, timeseriesScope, timeseries).subscribe(
  () => {
    console.log('Timeseries saved successfully');
  }
);
```
Or URL with query parameters for custom timestamps:
```
function saveTimeseries(entityId, data) {
    return http.post('/api/plugins/telemetry/'+entityId.entityType+'/'+entityId.id+'/timeseries/timeseriesScope', data);
}
```

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by icoco** [comment]
> Hi You can use either `attributeService.saveEntityTimeseries() `controller that will save the latest value:
> 
> ```
> const entityId = 'ENTITY_ID';
> const timeseriesScope = 'timeseries';
> const timeseries = [{ key: 'timeSeriesKey1', value: 'value1' }]; 
> attributeService.saveEntityTimeseries(entityId, timeseriesScope, timeseries).subscribe(
>   () => {
>     console.log('Timeseries saved successfully');
>   }
> );
> ```
> 
> Or URL with query parameters for custom timestamps:
> 
> ```
> function saveTimeseries(entityId, data) {
>     return http.post('/api/plugins/telemetry/'+entityId.entityType+'/'+entityId.id+'/timeseries/timeseriesScope', data);
> }
> ```


looks it works, but not sure why my part not work as expectation，

```
 var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';

  http.post(url, telemetriesData); // not execute HTTP call, why  
```

**Comment by icoco** [comment]
> > Hi You can use either `attributeService.saveEntityTimeseries() `controller that will save the latest value:
> > ```
> > const entityId = 'ENTITY_ID';
> > const timeseriesScope = 'timeseries';
> > const timeseries = [{ key: 'timeSeriesKey1', value: 'value1' }]; 
> > attributeService.saveEntityTimeseries(entityId, timeseriesScope, timeseries).subscribe(
> >   () => {
> >     console.log('Timeseries saved successfully');
> >   }
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or URL with query parameters for custom timestamps:
> > ```
> > function saveTimeseries(entityId, data) {
> >     return http.post('/api/plugins/telemetry/'+entityId.entityType+'/'+entityId.id+'/timeseries/timeseriesScope', data);
> > }
> > ```
> 
> looks it works, but not sure why my part not work as expectation，
> 
> ```
>  var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';
> 
>   http.post(url, telemetriesData); // not execute HTTP call, why  
> ```

well, use other way, it is ok :-D

**Comment by icoco** [comment]
> Hi You can use either `attributeService.saveEntityTimeseries() `controller that will save the latest value:
> 
> ```
> const entityId = 'ENTITY_ID';
> const timeseriesScope = 'timeseries';
> const timeseries = [{ key: 'timeSeriesKey1', value: 'value1' }]; 
> attributeService.saveEntityTimeseries(entityId, timeseriesScope, timeseries).subscribe(
>   () => {
>     console.log('Timeseries saved successfully');
>   }
> );
> ```
> 
> Or URL with query parameters for custom timestamps:
> 
> ```
> function saveTimeseries(entityId, data) {
>     return http.post('/api/plugins/telemetry/'+entityId.entityType+'/'+entityId.id+'/timeseries/timeseriesScope', data);
> }
> ```


case 1: 
```
attributeService.saveEntityTimeseries(entityId, timeseriesScope, timeseries).

```
this seem can not UPDATE a Time series record , it only CREATE new one ...


case 2:
```
http.post('/api/plugins/telemetry/'+entityId.entityType+'/'+entityId.id+'/timeseries/timeseriesScope', data);
```

the http not executed post in a widget Custom action , not sure why ,
