### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by 123GHLJ** [thingsboard/thingsboard#11118]
Hello.
I'm using the Script node. Would it be possible for the output values ​​of "temperature" and "humidity" to always be 0 regardless of the input value?
I'm trying some codes but I haven't been successful,
attached image.

Thanks.
![image](https://github.com/thingsboard/thingsboard/assets/168031149/bb60faba-f2fd-4b78-b710-6f67e2ffa0e6)

**Comment by myroslav-tb** [comment]
Hi @123GHLJ, you can just assign a 0 value to temperature and humidity in the script and it will always be returning 0.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/41afab38-458a-4dd4-a655-34f797f243c4)

```
msg.temp=0;
msg.humidity=0;
return {msg: msg};
```
![image](https://github.com/thingsboard/thingsboard/assets/158559147/b85d1d80-0c48-49f4-af73-99180ab057bb)

**Comment by 123GHLJ** [comment]
Hello myroslav-tb .
I tested this alternative, my difficulty is that the message is inside the "data" package. So it does not return a value of 0 inside the "data" package and adds 2 more output messages.

Thanks.

![image](https://github.com/thingsboard/thingsboard/assets/168031149/8645a5f4-d81a-4830-9492-664babf3545b)

**Comment by Backdraft007** [comment]
It is a nested JSON.
If you want to keep data in the structure use this:
`msg.data.temp=0;
msg.data.humidity=0;
return {msg: msg};`

**Comment by 123GHLJ** [comment]
Thank you very much Backdraft007 and everyone for your attention.
