### ISSUE TITLE
Access Dashboard State entity from Widget action

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#11116]
**Component**

 * UI

**Description**

I'm trying to customise the Asset Admin Widget to set a `Contains` relation on asset creation. To do this I need to access the Dashboard State Entity which is part of the `from` relation.

I found that I can access the Dashboard State Entity via

```
console.log('c', widgetContext.dashboard.widgets.dashboardCtx.stateController.stateObject)
```

They filter the array based on my selected Dashboard state.

![image](https://github.com/thingsboard/thingsboard/assets/14202480/4abacda4-e582-4002-9759-e0b019e1f08a)

However, this doesn't feel the right way to do it. My question: Is there a more efficient way to access the dashboard state entity?

**Environment**

 * OS:  MacOS
 * ThingsBoard: 3.6.3
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
`widgetContext.stateController.getStateParams()`

**Comment by dmohns** [comment]
> `widgetContext.stateController.getStateParamsByStateId(yourStateId)`
> 
> [link to source code](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts)

Works like charm 🤩 Thank you.
