### ISSUE TITLE
GPS location on map widget

### ISSUE THREAD

**Issue by Beniox** [thingsboard/thingsboard#11123]
**Describe the solution you'd like**
I would like to have a dot/marker on the map widget with the GPS location of current User, without having to save the location due to privacy concerns. 

**Describe alternatives you've considered**
Getting the location is possible: https://github.com/thingsboard/thingsboard/issues/10891#issuecomment-2138274640 

**Additional context**
It could be added as a checkbox in the settings to enable it. 

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. There is no such a possibility due to design of Thingsboard. It will use stored data in any case. The only possible solutions are either set up some short TTL for telemetry, or create custom widget that will display data from external endpoint

**Comment by LuMagAnd** [comment]
Hi
There are a workaround with window variable. This exported widget has a simple setup for that, but no geolocation error handling is implemented in this example. 
[map_with_geolocation.json](https://github.com/user-attachments/files/16095285/map_with_geolocation.json)

**Comment by Beniox** [comment]
Thanks, the workaround works fine.
I have tried to extend the map widget, but wasn't able to inject data into it. Are there any usable APIs for the map in the custom widget editor?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
