### ISSUE TITLE
Cant create entities version - VC - TB-CE 3.7.0

### ISSUE THREAD

**Issue by LukaszDuss** [thingsboard/thingsboard#11133]
**Describe the bug**
I can't commit changes, all I get is: 
`java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because the return value of "java.util.function.Function.apply(Object)" is null`

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: non-msa docker-compose (postgres + kafka)
  * ThingsBoard Version 3.7.0
  * Community Edition 
  * OS Name and Version: Ubuntu 22.04

**Comment by LukaszDuss** [comment]
Steps to recreate:
1. Install TB according to:
https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka
tb-postgres + kafka queue

2. Configure VC with your existing repository using username and token.
3. Make some changes. i've changed:
- rulechains 
- customer name
- elements of dashboard
- removed old custom widgets from library
4. Try commit changes.
5. no profit

I have changed the repository to brand new one. Still the same issue

**Comment by LukaszDuss** [comment]
i just managed to create commit with only widgets - i will check which part causes this error

**Comment by LukaszDuss** [comment]
> i just managed to create commit with only widgets - i will check which part causes this error
 
OK, it is NOT the VC problem - it is a problem inside customers:

I found this [pic] in public customer attributes - a attribute without name  
(please note that this is fresh - few days old instance of TB)
![image](https://github.com/thingsboard/thingsboard/assets/42135726/40a72f0a-3ce5-4a6e-b8e1-0cfb16ec653f)
I cant delete this attribute via GUI


any ideas how to delete/fix it?

**Comment by ViacheslavKlimov** [comment]
Attributes with empty keys are not permitted. How did you manage to create it?

**Comment by LukaszDuss** [comment]
> Attributes with empty keys are not permitted. How did you manage to create it?

Im not sure why that happened but I know how:
I have few global coeffs that needs to be set on new instances - so  I used "Update Multiple Attributes" widget that is linked to customer attributes to manage them - this time when filling empty spaces (to create&fill the attributes) something went wrong. 

![image](https://github.com/thingsboard/thingsboard/assets/42135726/dee11cfa-ca05-4e70-be7c-349a45da7bc4)
![image](https://github.com/thingsboard/thingsboard/assets/42135726/e6eb4424-b942-4fd2-91e2-027d684ac335)
in this case the name of the customer is COMPANY - I also found that it had "null" attribute but I could delete this customer
I cannot delete "public" customer tho...

**Comment by kkaasan** [comment]
I have similar problem with TB CE 3.7. had to import data from repository version control and after that some devices have server attributes with empty key and values like "0.5746225201100295". cannot make new version now to repository unless i leave out attributes on devices. I cannot delete those keys using TB or rest-api. log tells that it is deleted but empty key remains.
<img width="657" alt="Screenshot 2024-07-09 at 10 42 43" src="https://github.com/thingsboard/thingsboard/assets/12381108/d83cc341-0598-4414-97eb-4387bef44adb">
<img width="327" alt="Screenshot 2024-07-09 at 10 43 31" src="https://github.com/thingsboard/thingsboard/assets/12381108/5d8e33d5-f63b-4b72-910e-18c7ff7075ad">

**Comment by dealnat** [comment]
Hi, this issue is fixed in the version 3.8.0. Please wait until release notes appear on the [site](https://thingsboard.io/docs/reference/releases/)
