### ISSUE TITLE
How to use custom dialog for text input?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#11137]
Hello
I want to use custom dialog to receive a text from the user and store it in telemetry.
I did not find an example of how it works.
How should I do this?

**Comment by mykhailokornieiev** [comment]
Hi
For such purpose you can use custom actions with the same logic described in this comment https://github.com/thingsboard/thingsboard/issues/11108#issuecomment-2200457412 and this template:
https://thingsboard.io/docs/user-guide/ui/widget-actions/#custom-action-with-html-template - There are an examples of add entity, edit entity with add attribute logic. So you can use it as reference
![image](https://github.com/thingsboard/thingsboard/assets/115699895/83adabf5-e3dd-42af-a33b-cc75d4c8bd97)

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
