### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zhangdayeIMAX** [thingsboard/thingsboard#11135]
[Version set to 3.7.1-SNAPSHOT]
编译错误：
sudo yarn run build:prod
yarn run v1.22.22
$ node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration production --vendor-chunk
✔ Browser application bundle generation complete.

Error: src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html:174:7 - error NG5002: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags

174       </div>
          ~~~~~~

  src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts:55:16
    55   templateUrl: './gateway-configuration.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GatewayConfigurationComponent.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

解决：
在ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html目录中第174行，删除一个"< d i v >"即可

**Comment by ViacheslavKlimov** [comment]
I assume it was fixed with this: https://github.com/thingsboard/thingsboard/pull/11124.
Have you fetched the latest changes?
