### ISSUE TITLE
data directory "/data/db" has invalid permissions

### ISSUE THREAD

**Issue by asi-lhn** [thingsboard/thingsboard#11147]
**Component**

 * Installation
 * Generic

**Description**
Hi.
our thingsboard server has stopped running (502 bad gateway).

old container do not work, so i followed the instruction.(https://thingsboard.io/docs/user-guide/install/docker/)

i want to keep our data, so mounted same data and log folder.
i already did commands below.
```
sudo chown -R 799:799 ~/.tb-data
sudo chown -R 799:799 ~/.tb-logs
```

and i got this result.

```
Starting Postgresql...
waiting for server to start....2024-07-04 06:42:39.222 UTC [12] FATAL:  data directory "/data/db" has invalid permissions
2024-07-04 06:42:39.222 UTC [12] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
 stopped waiting
pg_ctl: could not start server
Examine the log output.
Connecting to Postgres, 300 attempts left...
Connecting to Postgres, 299 attempts left...
Connecting to Postgres, 298 attempts left...
Connecting to Postgres, 297 attempts left...
Connecting to Postgres, 296 attempts left...
``` 

+ i tried this command also, got same result.
```
docker run -it -p 8080:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.tb-data:/data -v ~/.tb-logs:/var/logs/thingsboard --restart a
lways thingsboard/tb-postgres
```

**Environment**

 * OS:  linux ubuntu docker
 * ThingsBoard: version
 * Browser: name and version

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
> Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)

To change permissions you need to `chmod` files in `~/.tb-data`

**Comment by asi-lhn** [comment]
> > Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)
> 
> To change permissions you need to `chmod` files in `~/.tb-data`

"~/.tb-data" had permissions 775. 
i changed it to 750 and 700 and tried to start thingsboard, but  same error.

'docker-mytb-1  | waiting for server to start....2024-07-07 22:59:26.146 UTC [12] FATAL:  data directory "/data/db" has invalid permissions
docker-mytb-1  | 2024-07-07 22:59:26.146 UTC [12] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).'

**Comment by pon0marev** [comment]
Please provide the output of the `ll -lah` command in the `~/.tb-data` folder

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
