### ISSUE TITLE
How to change color of Display pagination

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#11143]
hello.
my background of dashboard is dark and the icons of the widgets are also black and cannot be identified..
how to change color of Pagination, Search bar, next and previous button in entities table and other widget?

**Comment by devaskim** [comment]
CSS styles of a widget could be overwritten in Widget configuration -> `Advanced widget style` -> `Widget CSS`
Just find with browser DevTools which CSS class you need and overwrite it.
