### ISSUE TITLE
Widget invisible / diplay: none

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#11155]
![image-20240704-161618](https://github.com/thingsboard/thingsboard/assets/135682534/5121e546-5303-40db-ada6-4275d2ed06b9)

I have those cards with the alarm filter applied. I want to know if it’s possible to make these cards invisible if there’s no active alarm. In my case, only the content is invisible. I want to transform the entire card.

**Comment by kurch00** [comment]
): ok tkss

**Comment by Ultrazombie** [comment]
I'm closing this issue because a feature request is open.
