### ISSUE TITLE
Processing Data via GET Requests

### ISSUE THREAD

**Issue by HannesPiadeno** [thingsboard/thingsboard#11150]
**Component**
 * Rule Engine

**Description**
I am having a device installed which can only send its data with a HTTPs GET Request.
This looks something like this: "GET /api?Message=%22Alarm%22%3Afalse&Token=9gna6li4jy5fm8 HTTP/1.1"
Is there some kind of Workaround in Thingsboard that lets you receive such request on a device and process the requests information.

**Environment**
 * OS:  Ubuntu 22.04
 * Thingsboard: v3.7
 * Browser: Opera

**Comment by AldirchEugene** [comment]
http-transport

**Comment by HannesPiadeno** [comment]
@AldirchEugene  What do you exactly mean? I can only send telemetry with POST requests right!?

**Comment by myroslav-tb** [comment]
Hi @HannesPiadeno, by Thingsboard design, it only possible to send the data by POST requests. You will need to write your own custom endpoint that will receive the data GET request and resend it to Thingsboard by POST.

**Comment by AldirchEugene** [comment]
> @AldirchEugene 你到底是什么意思？我只能使用 POST 请求发送遥测数据，对吗？

please see  https://thingsboard.io/docs/reference/http-api/

**Comment by sudhirbits** [comment]
> Hi @HannesPiadeno, by Thingsboard design, it only possible to send the data by POST requests. You will need to write your own custom endpoint that will receive the data GET request and resend it to Thingsboard by POST.

Do you know if there is any open source project for development of this end point like a protocol translator.

**Comment by myroslav-tb** [comment]
Hi @sudhirbits, you can use a Python rest client to make your custom solution.
https://thingsboard.io/docs/reference/python-rest-client/
