### ISSUE TITLE
iframe question to show its external content

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#11167]
**Component**
 * Generic

**Description**

Hi there,

I am trying to create an HTML widget that includes the iframe tag in order to visualize an external website, but sadly, it shows nothing. If I set the website the own Thingsboard (that is to say, "http://localhost:8080/"), it works, so it might be related to the traffic / ports or something like that.

Do I have to set-up something more? 

Looking forward to your feedback.
Daniel.

**Environment**

 * OS:  Docker on Windows 11
 * ThingsBoard: 3.6.4 (Community Edition)
 * Browser: Chrome

**Comment by dpergarc-c** [comment]
Hi there,

Never mind, the issue was that I am trying to access an HTTPS website, and the Thingsboard instance I have is over HTTP (not secured transport layer), that is why the iframe tag is not working.

Further information can be found below:
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#developer_console

Kind regards.
Daniel.

**Comment by ssakharova** [comment]
Hello @dpergarc-c,

Thank you for letting us know. Have a nice day.
