### ISSUE TITLE
is there any way to get telemetry data of all devices from custom action?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#11160]
hello.
I have a time series table in which I display all the devices
Is there a way to access telemetry values ​​of devices through custom action?
I used `console.log (widgetContext.datasources);` command, but I could not access the values ​​themselves, and I was only getting the names of the values.

**Comment by devaskim** [comment]
you need `widgetContext.data`

**Comment by m3relec** [comment]
thanks @devaskim 
I executed this command and the following values ​​were displayed in the console:
![image](https://github.com/thingsboard/thingsboard/assets/45573721/68454ff8-78c7-4b4a-ada9-1247cd1dc0af)
In these cases, only the name of the key and some other information are displayed, but I could not find the value of the key.
Thank you for guiding me from which part I should access the values ​​of the keys.

**Comment by devaskim** [comment]
Be brave, dive deeper ;)

![Скриншот 09-07-2024 104059](https://github.com/thingsboard/thingsboard/assets/86909129/ba8d9fdf-24aa-4bcb-8c80-46f4b6c282b9)

**Comment by m3relec** [comment]
thanks a lot @devaskim 
Each device has an array with the number of keys defined in the input.
By checking the following arrays, I was able to find the values ​​I needed.
