### ISSUE TITLE
Image Map data key placement

### ISSUE THREAD

**Issue by BombayNitefrog** [thingsboard/thingsboard#11170]
**Component**

 * UI

**Description**
I have an image map, showing an air handling unit, with a single entity as the datasource.
I want to place the different data keys (supplyAirTemperature, valve opening etc.) as labels on the image map, with individual coordinates for each value.

How can I set static x/y values for each data key?

**Comment by devaskim** [comment]
Add your single entity as much data sources as data keys number is, i.e. Image Map widget doesn't detect duplicated entity in data sources configuration

**Comment by ssakharova** [comment]
Hello @BombayNitefrog,

Thank you for letting us know. In that case, may I close the ticket, or do you have any other questions?

**Comment by BombayNitefrog** [comment]
you are welcome to close the issue :)
