### ISSUE TITLE
Assistance Needed with Modbus Connection Configuration (v.3.7.0PE)

### ISSUE THREAD

**Issue by xtaveira** [thingsboard/thingsboard#11177]
Dear Thingsboard Team and Users,

I hope this Issue finds you well. I'm reaching out to request your assistance with an issue I'm encountering while configuring a Modbus connection in the ThingsBoard platform.

I'm currently working on a project that involves the use of a Modbus gateway, and I'm facing difficulties configuring the Modbus connection in ThingsBoard. Specifically, I'm trying to set up a single Modbus slave to receive data from multiple different devices. However, according to the ThingsBoard documentation, when configuring a Modbus connection slave, it seems that only a single device can be created.

To provide further clarification, according to the documentation, the JSON configuration for the slave looks something like this:

```
 slaves: [{    host: ip,    port: port,    deviceName: device_name
}]
```

However, in my scenario, I believe I would need something more like this:

```
slaves: [{    host: ip,    port: port,    devices: [list_of_devices]}]
```

I'm looking to understand how I can properly configure the Modbus connection in ThingsBoard to accommodate this setup, where a single slave receives data from multiple distinct devices.

Additionally, I would like to mention that I will be attaching some images illustrating the construction of the slave to provide further context.

this one doesn't work
![image](https://github.com/thingsboard/thingsboard/assets/96428113/07730d98-df82-49f6-b84f-e4bfd1371c9c)

this one works but just let me to use a single device for each port
![image](https://github.com/thingsboard/thingsboard/assets/96428113/c2691940-180c-4365-856c-081dc75a6ca5)

I would greatly appreciate your guidance on how to configure this connection properly in the ThingsBoard platform. If there are any tutorials or additional documentation that could assist me with this, I would be very grateful if you could share them with me.

Thank you in advance for your attention and support in this matter.

@ikulikov Please help me if you can :D, would be amazing

Best regards

**Comment by xtaveira** [comment]
Add Info: 
![image](https://github.com/thingsboard/thingsboard/assets/96428113/d99b546d-239c-46a5-ae5b-373fde963996)

(Currently Using thingsboard gateway with docker)

**Comment by devaskim** [comment]
> Modbus slave to receive data from multiple different devices.

Does each of those devices have own IP address?

In general, I recommend to to move this question to https://github.com/thingsboard/thingsboard-gateway/issues

**Comment by ssakharova** [comment]
Hello @xtaveira,

Since you are facing an issue with the Thingsboard IoT Gateway, you might consider reaching out to the GitHub community regarding thingsboard gateway issues. They can provide assistance or insights that could prove valuable in addressing your specific needs.

- GitHub thingsboard gateway issues - https://github.com/thingsboard/thingsboard-gateway/issues
