### ISSUE TITLE
About this website, do I need to install the kubectl Cluster or just install the kubectl?

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11178]
Hi All,

About this website, do I need to install the kubectl Cluster or just install the kubectl?  Thanks.
https://thingsboard.io/docs/mqtt-broker/install/cluster/aws-cluster-setup/

**Comment by pon0marev** [comment]
kubectl and eksctl are the only control tools. You must install these tools and then deploy the cluster in the cloud.
Please follow the instructions from start to end, and you will get a running cluster.
In the future, please create TBMQ-related issues in the TBMQ project: https://github.com/thingsboard/tbmq/issues/new/choose
