### ISSUE TITLE
Does a existing Thingsboard server supported joining a cluster?

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11171]
Hi anybody,

I just found below link:
https://thingsboard.io/docs/mqtt-broker/install/cluster/aws-cluster-setup/

However, this document describe "How to create a cluster" instead of I want to put the exsiting "Thingsboard" server to the cluseter.

Thanks.

**Comment by Jameschan07** [comment]
TYPO.
Hi anybody,

I just found below link:
https://thingsboard.io/docs/mqtt-broker/install/cluster/aws-cluster-setup/

However, this document describe "How to create a cluster" instead of put the exsiting "Thingsboard" server to the cluseter.

Thanks.

**Comment by Jameschan07** [comment]
P.S.1 I have an "Thingsboard" instance in EC2 already. And I don't have any cluster. 
P.S.2 I just want to make a new Cluster, then put the existing "Thingsboard" instance which is in EC2 now to the Cluster.

Is it possible?

**Comment by pon0marev** [comment]
To migrate an existing Thingsboard instance to a cluster, you need to deploy an empty Thingsboard cluster and test all features. Stop Thingsboard containers on the NEW instance and drop the Postgres **demo** database. Then make a backup of your current Postgres database (cassandra if you have one) and restore it to the cluster database. After that, change your IP address for the DNS entry.
