### ISSUE TITLE
Multiple Device's to single Rasperry Pi connection

### ISSUE THREAD

**Issue by nithiishkumarb** [thingsboard/thingsboard#11180]
Dear Thingsboard Team,

I have created a device and named it has "first_device",

I have 4 Energy Meter and 1 Rasperry PI , and using a Telegraf has a data collecting agent,

Successfully getting the data in the latest telemetry data but i don't know from which meter's data it is, whether i needed to add a keyname change  node to a Root Rule Chain ? ? ?

Also i needed to list a Devices with its usage,

Please help to sort it out . . . 

Thanks in advance

**Comment by devaskim** [comment]
If each incoming data packet has some unique key, like id or serial number of your energy meters, you can do the following:
1. Create device for each meter, the name will be your unique data key (lets say `id`).
2. Then edit your (root) rule chain by adding `Change originator` node before saving to database. The config will be the following
![Скриншот 10-07-2024 141928](https://github.com/thingsboard/thingsboard/assets/86909129/d93aa315-8401-4c03-81b4-0b816b49f262)
