### ISSUE TITLE
Fetching Timeseries data values from beginning

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1119]
Hi, I am facing some problems in fetching time-series data values using HTTP API.
Simple calls are working, but as soon as I try to fetch more than one value I get 

`{"status":401,"message":"Authentication failed","errorCode":10,"timestamp":ts}`

What I have done so far is:

1.  Getting auth codes

              curl POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d 
              '{"username":"user", "password":"password"}' 'http://IP:8080/api/auth/login'

              `{"token":"$TOKEN","refreshToken":"$REFTOKEN"}`

2. Getting data key

               curl -v -X GET http://IP:8080/api/plugins/telemetry/DEVICE/25f13310-d01e-11e7-b777- 
               7583315fb4ac/keys/timeseries  -H "Content-Type:application/json" -H "X-Authorization: Bearer 
               $TOKEN"

               $KEYS

3. Fetch last telemetry data value

               curl -v -X GET http://IP:8080/api/plugins/telemetry/DEVICE/25f13310-d01e-11e7-b777- 
               7583315fb4ac/values/timeseries?keys=$KEYS  -H "Content-Type:application/json" -H "X- 
               Authorization: Bearer $TOKEN"
              
               $TIMESERIES_DATA_VALUES

Everything works fine till there, but of course with the last command I get only one data value. As soon as I add some parameters to the curl call, like startTS, endTS or limit, i get "Authentication failed".

-             curl -v -X GET http://IP:8080/api/plugins/telemetry/DEVICE/25f13310-d01e-11e7-b777- 
               7583315fb4ac/values/timeseries?keys=$KEYS&$PARAMETERS  -H "Content- 
              Type:application/json" -H "X-Authorization: Bearer $TOKEN"

              {"status":401,"message":"Authentication failed","errorCode":10,"timestamp":ts}

What I am doing wrong? Should I have to specify **all** the parameters as per https://thingsboard.io/docs/user-guide/telemetry/ when I want to fetch more than one timeseries value?

**Comment by vparomskiy** [comment]
Please note that URL parameters are case sensitive, you need to use startTs, endTs - values specified in milliseconds.

Also here is a real-life example:
curl -v -X GET "https://cloud.thingsboard.io/api/plugins/telemetry/DEVICE/7a2441a0-aba6-88e8-b2ed-1b8ee8c54d91/values/timeseries?keys=temperature,himudity&startTs=1536650330000&endTs=1536950330000"  -H "Content-Type:application/json" -H "X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwYXJvbXNraXlAZ21haWwuY29tIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI0Mzc1MWViMC1hYmE2LTExZTgtYjJlZC0xYjhlZThjNTRkOTEiLCJmaXJzdE5hbWUiOiJWaXRhbGl5IiwibGFzdE5hbWUiOiJQYXJvbXNraXkiLCJlbmFibGVkIjp0cnVlLCJwcml2YWN5UG9saWN5QWNjZXB0ZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiI0MzYxNDg5MC1hYmE2LTExZTgtYjJlZC0xYjhlZThjNTRkOTEiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoiY2xvdWQudfewbmdzYm9hcmQuaW8iLCJpYXQiOjE1Mzg3NDU4NDIsImV4cCI6MTUzODc0Njc0Mn0.ISRmqqX_5U9ceAcFgmTv5sKhPbxhcP8TcrpmTl6SN7OPhY8-Ivg4F0CWKE8tGi8GpSWISZehdRY8xa__BqLlhg"
