### ISSUE TITLE
[Urgent] found nothing documents about adding TBMQ nodes to the TBMQ cluster

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11190]
Hi Anybody,

I just follew below link to configure the MQTT Broker Cluster and set up successfully.
https://thingsboard.io/docs/mqtt-broker/install/cluster/docker-compose-setup/

However, I found nothing documents about adding nodes to the cluster. Could anyone share the document.

Thanks.

**Comment by Ultrazombie** [comment]
At this time, we recommend considering a Kubernetes setup if you require more nodes. Unfortunately, we do not have the specific guide you requested at this point, but we do intend to add it in the future.
With the current guide for Docker Compose setup, you would need to change many parameters (such as haproxy.cfg settings, adding new tbmq3 instances, etc.). Therefore, opting for Kubernetes would probably be a better option if you require detailed guidance.
If you have any further questions or need assistance with your deployment, please feel free to reach out.
