### ISSUE TITLE
Application failed to start using IntelliJ IDE

### ISSUE THREAD

**Issue by rock-007** [thingsboard/thingsboard#11201]
**Component**

 * Installation

**Description**
I am looking to build and run the source code on my Mac, I have successfully build and run the application (using command line) by using these commands `$mvn clean install ` & `$java -jar application/target/thingsboard-3.7.1-SNAPSHOT-boot.jar `.
Also rebuild project using the IntelliJ is building all okay too but when I run the application (using Intellij IDE) I am getting error that `required a bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesDao' that could not be found.`, not sure if I am missing sth or haven't set something properly. any help appreciated.

I have tried clear the IntelliJ cache and reloading the project using maven but still no luck.

log file gist link: [[https://gist.github.com/rock-007/d34bda9d3df5cbf9a06f94f628c9c60d](https://gist.github.com/rock-007/d34bda9d3df5cbf9a06f94f628c9c60d)

<img width="2818" alt="image" src="https://github.com/user-attachments/assets/821238cd-d47c-45e4-af50-0204f57ea8a6">

<img width="2535" alt="image" src="https://github.com/user-attachments/assets/b26ee0fd-470c-4523-8653-83a43442f13b">

<img width="2173" alt="image" src="https://github.com/user-attachments/assets/7a749499-11e0-48e4-9567-69016a614ec8">

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/29523879-884e-4bd5-be95-1cc200f4b564">

<img width="977" alt="image" src="https://github.com/user-attachments/assets/18edcf29-8e44-4fb5-a26f-cfa3e6d17dff">
<img width="972" alt="image" src="https://github.com/user-attachments/assets/db6e02e4-a5a7-4c62-94bc-976efba84cca">
<img width="964" alt="image" src="https://github.com/user-attachments/assets/5ecf3588-c927-47ad-9ba1-51928cd9ac68">

**Environment**
 * OS:  Mac
 * ThingsBoard: 3.7.1
 * Browser: n/a

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by rock-007** [comment]
It seems like there might be  some issue with the class path when running the application using the IntelliJ IDE, but can't get my head around what can be causing it.

**Comment by rock-007** [comment]
its working now.

**Comment by Ultrazombie** [comment]
Hello @rock-007 
If it is not difficult for you - please share how exactly you solved the problem. Then, the next people who face this problem will be able to read how you achieved it.

Best regards,
Artem.

**Comment by CloudWise-Lukemiao** [comment]
> 它现在正在工作。



> its working now.

Hello, I have also encountered this issue. How can I configure it to start this project in Idea

**Comment by rock-007** [comment]
> > 它现在正在工作。
> 
> > its working now.
> 
> Hello, I have also encountered this issue. How can I configure it to start this project in Idea

have you tried to build using command line(and make sure no compline time error) and run as well.

you might need to change some code from the following link(https://github.com/thingsboard/thingsboard/issues/9693#issuecomment-1921345571)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
