### ISSUE TITLE
Device is connected ( Active ) but Latest telemetry data not updating....

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11204]
**Latest telemetry data not updating....**
I am sending data from the esp32 to thingsboard cloud. Device is connected ( It show the active status also). But latest telemetry value is not updating. 

Even by using 
`mosquitto_pub -d -q 1 -h mqtt.thingsboard.cloud -p 1883 -t v1/devices/me/telemetry -u "BmHRkgPVHYBmtDrXJXoi" -m "{temperature:25}"`  
this command also not update the latest telemetry value only status become active.

**Comment by myroslav-tb** [comment]
Hi @Vaibhav0216, please check if the rule chain that is used by the device has a save timeseries rule node.

**Comment by Vaibhav0216** [comment]
It due to my connectivity issue. Problem have solved . 
Thank You, 
Vaibhav Kshirsagar.

**Comment by philtrick-twm** [comment]
Hi, I'm having the same problem, and there is a "save timeseries" rule node in the rule chain.
