### ISSUE TITLE
How to connect W5100s-EVB to thingsboard

### ISSUE THREAD

**Issue by Kjellyboy1** [thingsboard/thingsboard#11205]
Hello!
 I want to connect the Wiznet W5100S-EVB-Pico to ThingsBoard. I've already successfully connected the Raspberry Pi Pico with 20 inputs and 6 outputs, and it works perfectly. 
Now I want to do something similar with Ethernet using the W5100S because I can't use WiFi everywhere. 
Have any of you tried this before, and how did you do it? 
I've used the example script from ThingsBoard for the Pico W and modified it, but I'm having trouble getting it right. 
I'm trying different things and searching online. Thanks in advance, guys!

**Comment by Kjellyboy1** [comment]
After searching for a while, I can now connect to ThingsBoard with this script and monitor 7 inputs.

`
#include <ThingsBoard.h>
#include <Ethernet.h>

// Ethernet settings
byte mac[] = { 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX };  // Customize this with your Ethernet shield's MAC address

// Uncomment and configure these settings if using a static IP
IPAddress ip(xx, xx, xx, xxx);  // Static IP address
 IPAddress myDns(8, 8, 8, 8);    // DNS server
 IPAddress gateway(xx, xx, xx, 1); // Gateway
 IPAddress subnet(255, 255, 255, 0); // Subnet mask

constexpr char TOKEN[] = "XXXXXXXXXXXX";
constexpr char THINGSBOARD_SERVER[] = "XXX.XXX.XXX.XX";
constexpr uint16_t THINGSBOARD_PORT = 1883U;
constexpr uint32_t MAX_MESSAGE_SIZE = 512U;
constexpr uint32_t SERIAL_DEBUG_BAUD = 115200U;

EthernetClient ethClient;
ThingsBoard tb(ethClient, MAX_MESSAGE_SIZE);

bool subscribed = false;
volatile bool attributesChanged = true;
volatile int ledMode = 1;
volatile int testrelay = 0;
volatile int Output21;
volatile bool ledState = true;
constexpr uint16_t BLINKING_INTERVAL_MS_MIN = 10U;
constexpr uint16_t BLINKING_INTERVAL_MS_MAX = 60000U;
volatile uint16_t blinkingInterval = 1000U;

uint32_t previousStateChange;
constexpr int16_t telemetrySendInterval = 2000U;
uint32_t previousDataSend;

constexpr std::array<const char *, 2U> SHARED_ATTRIBUTES_LIST = {
  "blinkingInterval", "ledState"
};

constexpr std::array<const char *, 1U> CLIENT_ATTRIBUTES_LIST = {
  "ledMode"
};

const char *getMAC() {
  static char macStr[18];
  sprintf(macStr, "%02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
  return macStr;
}

void InitEthernet() {
  Serial.println("Initializing Ethernet...");
  Ethernet.init(17); // W5100S-EVB-Pico
  // Uncomment the below line to use static IP
   Ethernet.begin(mac, ip, myDns, gateway, subnet);
  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // If DHCP fails, an additional static IP configuration can be added here if needed.
    // Uncomment and configure the below line if you want to use a static IP as fallback.
     Ethernet.begin(mac, ip, myDns, gateway, subnet);
  } else {
    Serial.print("Ethernet initialized. IP address: ");
    Serial.println(Ethernet.localIP());
  }
  delay(1000);
  if (Ethernet.hardwareStatus() == EthernetNoHardware) {
    Serial.println("Ethernet shield was not found. Sorry, can't run without hardware. :(");
    while (true) {
      delay(1); // do nothing, no point running without Ethernet hardware
    }
  }
  if (Ethernet.linkStatus() == LinkOFF) {
    Serial.println("Ethernet cable is not connected.");
  }
}

const bool reconnect() {
  if (Ethernet.linkStatus() == LinkOFF) {
    Serial.println("Ethernet cable is not connected.");
    return false;
  }
  return true;
}

RPC_Response processSetLedMode(const RPC_Data &data) {
  Serial.println("Received the set led state RPC method");
  int new_mode = data;
  Serial.print("Mode to change: ");
  Serial.println(new_mode);
  if (new_mode != 0 && new_mode != 1) {
    return RPC_Response("error", "Unknown mode!");
  }
  ledMode = new_mode;
  attributesChanged = true;
  return RPC_Response("newMode", (int)ledMode);
}

RPC_Response processSetOutput21(const RPC_Data &data) {
  Serial.println("Received the set output state RPC method");
  int new_mode = data;
  Serial.print("Mode to change: ");
  Serial.println(new_mode);
  if (new_mode != 0 && new_mode != 1) {
    return RPC_Response("error", "Unknown mode!");
  }
  Output21 = new_mode;
  attributesChanged = true;
  return RPC_Response("newMode", (int)Output21);
}

RPC_Response processSetRelay(const RPC_Data &data) {
  Serial.println("Received the set relay state RPC method");
  int new_mode1 = data;
  Serial.print("Mode to change: ");
  Serial.println(new_mode1);
  if (new_mode1 != 0 && new_mode1 != 1) {
    return RPC_Response("error", "Unknown mode!");
  }
  testrelay = new_mode1;
  attributesChanged = true;
  return RPC_Response("newMode1", (int)testrelay);
}

const std::array<RPC_Callback, 2U> callbacks = {
  RPC_Callback{ "setLedMode", processSetLedMode },
  RPC_Callback{ "setOutput21", processSetOutput21 }
};

void processSharedAttributes(const Shared_Attribute_Data &data) {
  for (auto it = data.begin(); it != data.end(); ++it) {
    if (strcmp(it->key().c_str(), "blinkingInterval") == 0) {
      const uint16_t new_interval = it->value().as<uint16_t>();
      if (new_interval >= BLINKING_INTERVAL_MS_MIN && new_interval <= BLINKING_INTERVAL_MS_MAX) {
        blinkingInterval = new_interval;
        Serial.print("Updated blinking interval to: ");
        Serial.println(new_interval);
      }
    } else if (strcmp(it->key().c_str(), "ledState") == 0) {
      ledState = it->value().as<bool>();
      Serial.print("Updated state to: ");
      Serial.println(ledState);
    } 
  }
  attributesChanged = true;
}

void processClientAttributes(const Shared_Attribute_Data &data) {
  for (auto it = data.begin(); it != data.end(); ++it) {
    if (strcmp(it->key().c_str(), "ledMode") == 0) {
      const uint16_t new_mode = it->value().as<uint16_t>();
      ledMode = new_mode;
    }
  }
}

const Shared_Attribute_Callback attributes_callback(SHARED_ATTRIBUTES_LIST.cbegin(), SHARED_ATTRIBUTES_LIST.cend(), &processSharedAttributes);
const Attribute_Request_Callback attribute_shared_request_callback(SHARED_ATTRIBUTES_LIST.cbegin(), SHARED_ATTRIBUTES_LIST.cend(), &processSharedAttributes);
const Attribute_Request_Callback attribute_client_request_callback(CLIENT_ATTRIBUTES_LIST.cbegin(), CLIENT_ATTRIBUTES_LIST.cend(), &processClientAttributes);

void setup() {
  Serial.begin(115200);
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  InitEthernet();
}

void loop() {
  delay(10);

  if (!reconnect()) {
    subscribed = false;
    return;
  }

  if (!tb.connected()) {
    subscribed = false;
    Serial.print("Connecting to: ");
    Serial.print(THINGSBOARD_SERVER);
    Serial.print(" with token ");
    Serial.println(TOKEN);
    if (!tb.connect(THINGSBOARD_SERVER, TOKEN, THINGSBOARD_PORT)) {
      Serial.println("Failed to connect");
      return;
    }
    tb.sendAttributeData("macAddress", getMAC());
  }

  if (!subscribed) {
    Serial.println("Subscribing for RPC...");
    if (!tb.RPC_Subscribe(callbacks.cbegin(), callbacks.cend())) {
      Serial.println("Failed to subscribe for RPC");
      return;
    }
    if (!tb.Shared_Attributes_Subscribe(attributes_callback)) {
      Serial.println("Failed to subscribe for shared attribute updates");
      return;
    }
    Serial.println("Subscribe done");
    subscribed = true;

    if (!tb.Shared_Attributes_Request(attribute_shared_request_callback)) {
      Serial.println("Failed to request for shared attributes");
      return;
    }
    if (!tb.Client_Attributes_Request(attribute_client_request_callback)) {
      Serial.println("Failed to request for client attributes");
      return;
    }
  }

  if (attributesChanged) {
    attributesChanged = false;
    tb.sendAttributeData("ledMode", ledMode);
    tb.sendAttributeData("ledState", ledState);
  }

  if (ledMode == 1 && millis() - previousStateChange > blinkingInterval) {
    previousStateChange = millis();
    ledState = !ledState;
    digitalWrite(LED_BUILTIN, ledState);
    tb.sendTelemetryData("ledState", ledState);
    tb.sendAttributeData("ledState", ledState);
  }

  const int buttonPin0 = 0;
  const int buttonPin1 = 1;
  const int buttonPin2 = 2;
  const int buttonPin3 = 3;
  const int buttonPin4 = 4;
  const int buttonPin5 = 5;
  const int buttonPin6 = 6;
  const int buttonPin7 = 7;

  if (millis() - previousDataSend > telemetrySendInterval) {
    previousDataSend = millis();
    tb.sendTelemetryData("input0", digitalRead(buttonPin0));
    tb.sendTelemetryData("input1", digitalRead(buttonPin1));
    tb.sendTelemetryData("input2", digitalRead(buttonPin2));
    tb.sendTelemetryData("input3", digitalRead(buttonPin3));
    tb.sendTelemetryData("input4", digitalRead(buttonPin4));
    tb.sendTelemetryData("input5", digitalRead(buttonPin5));
    tb.sendTelemetryData("input6", digitalRead(buttonPin6));
    tb.sendTelemetryData("input7", digitalRead(buttonPin7));
  }

  tb.loop();
}
`

**Comment by Ultrazombie** [comment]
Hello @Kjellyboy1,
Thanks for the sharing this solution,
I've closed this ticket as it is no longer active
