### ISSUE TITLE
How to extract device-gateway data in rulechain?

### ISSUE THREAD

**Issue by LukaszDuss** [thingsboard/thingsboard#11213]
**Component**
 * Rule Engine

**Question**
How can I get information about GATEWAY originator in rulechain.

**Description**
I have device that serves as Gateway. It uses MQTT, topic v1/gateway/telemetry to send messages about sensors like:

`{
"dev_11":
[{
"Temperature":23.9,
"RSSI":-105,
"Battery":153
}]
}`

Works great - it posts telemetry to rulechain with originator "dev_11" but I'd like to save name of the Gateway device that initiated the message. 

**Environment** 
 * ThingsBoard: version 3.6.4 CE

**Comment by devaskim** [comment]
If only one, i.e. the same, gateway pushes `dev_11` 's data each time, so you can get gateway name through `Related Entity Data` node using `Created` relation. Otherwise, there is no such feature to dynamically resolve gateway originator.

**Comment by LukaszDuss** [comment]
ok, so in case i have 2 gateways that catches same sensor i can only get one that created it. 

thanks :)
