### ISSUE TITLE
ERR_HTTP2_SERVER_REFUSED_STREAM appears when loading Images (Widgets Previews, Image Gallery)

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#11212]
**Describe the bug**
We have recently configured HTTP over SSL with Java Keystore certificates according to the documentation:
https://thingsboard.io/docs/pe/user-guide/ssl/http-over-ssl/

After the change, everything runs smoothly except for loading images. This was particularly noticeable with widget preview images or when inserting images from Image Gallery. Also, the behavior does not occur immediately, but only after the user has repeatedly provoked a loading of the images.

If the error occurs, an error toast appears with the message "Unable to connect". The error ERR_HTTP2_SERVER_REFUSED_STREAM can be found in the log of the web console.

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: deb
  * ThingsBoard Version 3.6.4
  * Professional Edition
  * Ubuntu

**Your Client Environment**
* Browser: Chrome, Edge

**To Reproduce**
1. Open a Dashboard in Edit Mode
2. Add a new Widget
3. Click in and out of the Widget Bundles
4. After some time "Unable to connect" error message appears and Widget Preview Images get lost

**Expected behavior**
Widget Preview Images should always be loading correctly even after a lot of user interaction.

**Screenshots**
![error](https://github.com/user-attachments/assets/a18fb3e3-c80b-4387-9834-40a6b0d348da)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. Please describe this problem with full steps to reproduce: 
- describe your deployment
- do you use any loabalancer?
- how did you generate your key?
- do you use Nginx?

In the case of Thingsboard, using the Java Keystore is already a deprecated method, so it is better to use PEM. An even better option would be to use this guide

https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
