### ISSUE TITLE
Documentation blog not working.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11217]
**Documentation blog not working.**
RPC Reply With data from Related Device. This documentation is not working i follow all steps properly but when I have entered last command. 
`curl -X POST -d '{"method": "getTemperature", "params":{}}' http://localhost:8080/api/v1/IAkHBb9N7kKD9ieLRMFN/rpc --header "Content-Type:application/json"`

Error:- curl: (7) Failed to connect to localhost port 8080 after 0 ms: Connection refused

above error comes. I checked is 8080 port available using command. 
`sudo netstat -tuln | grep 8080
`
I didn't received any response. 
So please update documentation if required.

**Comment by Ultrazombie** [comment]
Hello @Vaibhav0216 

```sudo netstat -tuln | grep 8080 ```

The fact that you see nothing after running this command means that, most likely, the thingsboard service is not running. Please check that the service is up and running

**Comment by Vaibhav0216** [comment]
Thingsboard services is running properly. I have received data from sensors
and dashboard also updating.

**Comment by Vaibhav0216** [comment]
Can you please provide technical support for us if we buy subscription of
thingsboard

**Comment by Ultrazombie** [comment]
Please replace http://localhost:8080 with your thingsboard instance URL.
It looks like you are using an external thingsboard (that's not running on your local)

Alternativity - you can also try to use the 80 port instead of 8080.


In case you want to buy support - you can request it on the Contact Us form using the following link:
https://thingsboard.io/docs/contact-us/

**Comment by Vaibhav0216** [comment]
Update Attribute Widgets Bug
 
1) When I save the updated attribute data, it is not sending the data to the device.
 
2) When I update the attribute value from Device Details -> Attributes -> Shared Attribute, the change is reflected on the dashboard widget's attribute value and the updated attribute value is also sent to the device.
 
3) However, when I update the value from the dashboard widget, the attribute is automatically created and updated in Device Details -> Attributes -> Server Attribute. Despite this, the data is not sent to the device. 
 
4) When I update values from  Device Details -> Attributes -> Server Attribute changes reflected on dashboard but data is not sent to the device.
