### ISSUE TITLE
Rule Engine - Rest Api Call - absoluteURI in POST

### ISSUE THREAD

**Issue by toti1212** [thingsboard/thingsboard#1122]
Hi there.

I try to send telemetry to a server from `rest api call` node but only get `404 Not Found` because the server cant resolve the url, so, I compare the Post of TB 2.X and 1.X, and I see that in version 2.X the post send the absoluteURI in Request URI, but in 1.X send only the `path`.

2.X
```
POST http://<url>/rest/telemetry/ HTTP/1.1
Request Method: POST
Request URI: http://<url>/rest/telemetry/
Host: <url>
```

1.X
```
POST /rest/telemetry/ HTTP/1.1
Request Method: POST
Request URI: /rest/telemetry/
Host: <url>
```

Is this change for something in particular that you consider?

Reading the RFC I got some information but Im not sure how TB do the request.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

**Comment by ashvayka** [comment]
Hi @toti1212 

We believe that it makes sense to send a request to the external server but not to self. So I don't see an issue here. You can always reference localhost if you like. This rule node is designed to work with external systems.
