### ISSUE TITLE
Let users change data keys of a timeseries chart widget

### ISSUE THREAD

**Issue by AndreSensaway** [thingsboard/thingsboard#11239]
**Component**
 * UI

**Description**
I want to give the user the ability to explore their data through a timeseries chart widget.
As an example, I have a device with 100 timeseries tags and I want the user to choose which of those tags are visible (up to a maximum of 5 tags for example) in the timeseries chart without having access to the widget editing and consequently all other widget configurations.

Is this possible without having to make a custom widget?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.6.4 PE

**Comment by mykhailokornieiev** [comment]
Hi
For such cases, you can create an entity view, and assign necessary device telemetry/attribute data for it. Then you can use it in datasource and deny permission for this user to use devices. 
https://thingsboard.io/docs/user-guide/entity-views/
https://thingsboard.io/docs/pe/user-guide/rbac/#permissions

**Comment by AndreSensaway** [comment]
Thanks for the answer, but this doesn't work for my scenario because the end user will always be in fullscreen mode and so I he will not be able to edit the chart widget.

I ended up developing a custom widget that writes to an attribute, of the current user, which tags he wants to see.
I'm know adapting the Line Chart widget to read the user attribute and update the datasources, but I'm running into a problem.

I successfully created the data subscription for a new tag, and the `self.ctx.data` is being populated with data but for some reason the chart does not display the data...
What I did was change the data key name and label to the desired values, then create a new subscription with a copy of the pre-existing options and finally, I update `self.ctx.defaultSubscription`, `self.ctx.data` and `self.ctx.datasources` with the newly created subscription.

I'm printing self.ctx.data in the console and I can see that it is being populated. But when I print `self.ctx.data[0].data` it is empty right before I  call `self.ctx.$scope.timeSeriesChartWidget.onInit()`.

Is there something I'm doing wrong?

widget code:
`self.onInit = function() {
    let datasource = self.ctx.defaultSubscription.datasources[0];
    datasource.dataKeys[0].name = "01.001";
    datasource.dataKeys[0].label = "01.001";

    const subscriptionOptions = {
        type: 'timeseries', //Subscription type
        datasources: self.ctx.defaultSubscription.datasources, //Describes what data you want to subscribe
        useDashboardTimewindow: true,
        callbacks: //Sets callbacks for subscription
        {
            onDataUpdated: () => {
                self.onDataUpdated();
            }
        }
    };
   
    self.ctx.subscriptionApi.createSubscription(subscriptionOptions, true).subscribe(
        (subscription) => {
            self.ctx.defaultSubscription = subscription; //Saving subscription information into widget context
            self.ctx.data = subscription.data; //Saving data into widget context
            self.ctx.datasources = subscription.datasources; //Saving datasource into widget context
            
            console.log('chart data 1:', self.ctx.data[0]);
            console.log('chart data 2:', self.ctx.data[0].data);

            self.ctx.$scope.timeSeriesChartWidget.onInit();
        }
    );
};`

printed logs:

![image](https://github.com/user-attachments/assets/fbf151fa-b319-47c7-8a89-85b0881d2fbe)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
