### ISSUE TITLE
Question: how to move a customer and all customer entities from one tenant to another

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#11249]
**Component**

Platform

**Description**
In my self hosted community version of thingboard
I have a use case where I want to move a customer and all the customers are entities including devices, assets, users, device profiles and rule chains from one tenant to another tenant. 

The source tenant and target tenant are both on the same instance of thingsboard. 

Is there a backend way of achieving the same. Is there a way of achevibg this using a query execution on Postgres database? 

**Environment**

 * OS:  Ubuntu 20.4
 * ThingsBoard: 10.3.6
 * Browser: NA 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
I think, that the best possible solution for this case would be to use Version Control. It can backup/restore entities between tenants or instances.
You can get familiar with its utilization by following the next link:
https://thingsboard.io/docs/user-guide/version-control/

**Comment by sudhirbits** [comment]
Thanks for your comment @mykhailokornieiev 
Using VC would do a backup and retore to another tenant. I was hoping there is a simpler way using a query update or similar.

**Comment by mykhailokornieiev** [comment]
Hi. It is possible to modify this data in the database, **but I highly don't recommend doing it**, so it will be better to use previously suggested methods

**Comment by sudhirbits** [comment]
Understood @mykhailokornieiev 
When I looked into the postgres thingsboard schema I was able to see that the `tenant_id` is denormalised across the schema and not contained. The database update based migration would be extremely complex to impossible. 

Will look into the suggested option.
