### ISSUE TITLE
Your Sharing Separate Dashboards with Admin and User

### ISSUE THREAD

**Issue by Faheem-Punnasseri** [thingsboard/thingsboard#11247]
**Component**

 * Dashboard

**Environment**

 * ThingsBoard: V.3.7.0PE

How can I share the **dashboards** with the **admin** and **user** separately? I have a group of dashboards for a customer, which includes one dashboard for the admin and another for the user. I need to share them in a way that each person receives their respective dashboard.

**Comment by ssakharova** [comment]
Hello @Faheem-Punnasseri,

In that case, you need to put the dashboard for the Customer Administrator and the dashboard for the Customer User into separate dashboard groups.

Next, use the 'Share' button to share each dashboard group with the appropriate users, granting the necessary permissions to the Customer User and Customer Administrator.

Please see the screenshots for more clarity:
![image](https://github.com/user-attachments/assets/b3d48cdf-4414-4188-b83d-38f552923916)
![image](https://github.com/user-attachments/assets/baf4d34e-250b-46e0-aa96-dfe2a5e87191)
