### ISSUE TITLE
API request Authentification header changed?

### ISSUE THREAD

**Issue by VeryBitter** [thingsboard/thingsboard#11257]
Hi everyone

have you by any chance, modified the API authorization header from 'Bearer: TOKEN' to 'Bearer TOKEN' when moving from version 3.6.4 to 3.7.0? It took me a while before finding that the colon should be removed. I use the tb_rest.py library.

Best

**My Server Environment**
  * Deployment: monolith or microservices
  * Deployment type: docker-compose
  * ThingsBoard Version
  * Professional Edition
  * Synology

**Comment by ViacheslavKlimov** [comment]
It was always like that  : )
![image](https://github.com/user-attachments/assets/31eba63d-9c91-4286-ace4-1fb9c7f534d5)

**Comment by ssakharova** [comment]
Hello @VeryBitter,

Please re-create a new ticket in GitHub thingsboard python rest client issues (https://github.com/thingsboard/thingsboard-python-rest-client/issues) if you still have further questions.
