### ISSUE TITLE
Does Thingsboard MQTT Broker (TBMQ) support to listen 2 networks ports at same time?

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11259]
Hi Anybody,

Does Thingsboard MQTT Broker (TBMQ) support to listen 2 networks ports at same time?
Since I want the TBMQ to listen MQTT(Port 1883) and MQTTS(Port8883) at same time.
Is it possible?

Thanks.

**Comment by Backdraft007** [comment]
Please close this one. Double posts, uarg.
https://github.com/thingsboard/thingsboard/issues/11264

**Comment by Jameschan07** [comment]
Double post, #11264
