### ISSUE TITLE
About Cloud server source code deployment issues

### ISSUE THREAD

**Issue by wanghuaming8** [thingsboard/thingsboard#11263]
Version：3.7.0
How to choose the server configuration required for cloud server source code deployment? I hope you can give me some suggestions

**Comment by pon0marev** [comment]
You can find the performance overview of the ThingsBoard service on different servers here:
https://thingsboard.io/docs/pe/reference/performance-aws-instances/

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
