### ISSUE TITLE
Your title here

### ISSUE THREAD

**Issue by kiraten191010** [thingsboard/thingsboard#11262]
**Component**

 * Rule Engine
 * Generic

**Description**

I'm using thingsboard Community Edition
I'm using a Timeseries table to display log data for a device that has over 200,000 pieces of data.
I want to display all the log data of the device on the dashboard, but the maximum value of the Timewindow setting of the Timeseries table is 50000.
![Q-1](https://github.com/user-attachments/assets/dfaf124b-436a-4579-a239-e94bd75034d0)
![Q-2](https://github.com/user-attachments/assets/0a3703ce-124e-4e2a-97b7-2a5851dceb8b)

Is it possible to have all the data displayed on the dashboard?

**Environment**
 * OS:   Windows10
 * ThingsBoard: 2.0.1
 * Browser: google chrome

**Comment by mykhailokornieiev** [comment]
Hi
This limit is set by default but you can increase it using the [configuration parameter](https://thingsboard.io/docs/user-guide/install/config/).
Please try setting a higher value to the DASHBOARD_MAX_DATAPOINTS_LIMIT environment variable

Quote from the [documentation](https://thingsboard.io/docs/user-guide/install/config/#ui-settings-parameters):
<span><span data-testid="comment-base-item-142121">
Parameter | Environment Variable | Default Value | Description
-- | -- | -- | --
ui.dashboard.max_datapoints_limit | DASHBOARD_MAX_DATAPOINTS_LIMIT | 50000 | Maximum allowed datapoints fetched by widgets

</span></span>
For example: export DASHBOARD_MAX_DATAPOINTS_LIMIT=50001
![image](https://github.com/user-attachments/assets/d7f8e43a-459a-4edc-8c48-e44bf109e982)
Don't forget to restart thingsboard service for changes affect
`sudo service thingsboard restart`
Increase this value with caution, as it may affect the stability and performance of the service

**Comment by kiraten191010** [comment]
Thank you for your answer
But when I set the DASHBOARD_MAX_DATAPOINTS_LIMIT value to 300000, the data cannot be displayed on the dashboard
It seems that the DASHBOARD_MAX_DATAPOINTS_LIMIT value is too large and takes too long to display, but 300000 is already the minimum value required.
![Q-3](https://github.com/user-attachments/assets/a2d51ba9-d3b1-4a3b-b540-b86fe6b2a6cf)

**Comment by mykhailokornieiev** [comment]
Hi. In this case, 300000 datapoints will create too complex query for database. That's exactly why this value is set to 50k by default. So, I can only recommend to reduce this value.

**Comment by kiraten191010** [comment]
> Hi. In this case, 300000 datapoints will create too complex query for database. That's exactly why this value is set to 50k by default. So, I can only recommend to reduce this value.

Thank you very much , another question , is it possible to use a fitter or other widget to limit the data show on the dashboard ? For example, only display data with key<wifiPower> value equal to -75

**Comment by mykhailokornieiev** [comment]
@kiraten191010 currently, there is no possibility to filter timeseries values, only entities.
