### ISSUE TITLE
Newly created tenant user cannot login?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1126]
1. I follow the "https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/" contribution guide to build the source success.
2. I visit "http://localhost:3000" and login with "sysadmin@thingsboard/sysadmin".
3. I create a new tenant user "tenantA@thingsboard.org".
4. I copy the activate tenant Url  and visit the Url:"http://localhost:3000/api/noauth/activate?activateToken=rH4PtEnXTpu6Vs51zLUVL2Ni7yKzre",.
5. The Url  Jump to the Login Page.
I cannot activate the newly created tenant user, and of course, I cant login with the newly created tenant user?

**Comment by vparomskiy** [comment]
1. Is it reproducible? If you create another user and go to activation link, what is the behavior?
2. Did you make any changes in the Thingsboard UI?

**Comment by qwyinxiang** [comment]
1. Yes, it is reproducible, I create another tenant user named "tenantB@thingsboard.org", It still jump to the login page.
2. I didnot make any changes in the UI.

**Comment by ashvayka** [comment]
Maybe this is related to 3000 port (debug mode). Try to use 8080 port for activation?

**Comment by qwyinxiang** [comment]
@vparomskiy, @ashvayka, I used the  Branch_V2.1.0, And I tried to use the 8080 port for activation, The tenant user can be activated and can login the Url. Thank you very much.

**Comment by mariojfduarte** [comment]
Still, should work on port 3000 (Custom UI). Should be fixed on Docker image.
