### ISSUE TITLE
LwM2M transport profile object changed when deleting another object

### ISSUE THREAD

**Issue by jbr-ia** [thingsboard/thingsboard#11276]
**Describe the bug**
When deleting an object from the transport-configuration of an lwm2m-device, properties in other multi-instance objects are changed.

**Your Server Environment**

* own setup
  * Deployment type: docker-compose
  * ThingsBoard Version 3.7.0
  * Community Edition
  * Ubuntu 22.04

**Desktop:**
  * OS: Windows 10 / ubuntu 22.04
  * Browser Chrome (windows) / firefox (ubuntu)
  * Version Chrome 126.0.6478.183  / firefox 128.0.2

**Connectivity**
  * LWM2M

**To Reproduce**
1. Go to 'Device profiles'
2. Add a new device profile with LWm2m transport configuration.
3. Add objects to the profile (for example  '6_1.0: Location', and '3340_1.0: Timer')
4. Select some attributes for the location-object (for example, select attribute for #0 latitude for the location-object)
5. Add an extra instance for the timer-object, and select different properties and change key-names (for example, select attribute for resource 5521 in instance 0, and telemetry for instance 1. Select attribute for resource 5538 only in instance 0. Change key name of resource 5521 in instance1 to TEST1. This situation is shown in the image below at screenshots )
6. Click apply changes
7. Check that the configuration is good, and as expected
8. Delete the '6_1.0: Location'-object from the object-list
9. Click apply changes
10. Check the instances for the timer, and the key-names for resource 5521 in instance 1 of the Timer-object have changed, and that suddenly also 'attribute' is selected. See that also the 'attribute' of resource 5538 is selected in instance 1.

**Expected behavior**
When deleting an object, I expect the other objects to be left unchanged.

**Screenshots**
Overview of objects before deleting:
![afbeelding](https://github.com/user-attachments/assets/35d0a1b9-7090-42ed-8c90-90f4c6ad8fbe)

**properties of timer 3340 Before deleting: 6_1.0: Location (after step 6 to reproduce)**
![afbeelding](https://github.com/user-attachments/assets/63df9539-494e-432b-9456-e68f12203a37)

**properties of timer 3340 After deleting 6_1.0: Location (after step 9 to reproduce)**
Instance0 seems to be unaffected, but after deleting 6_1.0: Location, instance1 has attributes selected, and a a changed key name
![afbeelding](https://github.com/user-attachments/assets/e7584c19-3c55-424e-944f-1513fce877a3)

**Additional context**
If in the reproduce-steps, between step 8 and 9, there is a look at the timers, it is seen that instance1 is suddenly doubled in the list. On of them seems a copy of instance0, the other is the original instance1. After applying, it seems these 2 instances are merged.

**Comment by epalchenko** [comment]
Hello,
Thank you for the detailed steps to reproduce. I was able to reproduce this issue.
This looks like a bug in a platform - I had already added to our backlog a ticket for a product team (PROD-4140).
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
