### ISSUE TITLE
Postgres restarts every couple of days as mentioned on 7876

### ISSUE THREAD

**Issue by miguel-paniagua** [thingsboard/thingsboard#11270]
Sorry for duplicating. I have try to reopen the #7876 without success.

**Describe the bug**
postgres shutdowns by Thingsboard as shows on  issue [7876](https://github.com/thingsboard/thingsboard/issues/7876#issuecomment-2244402230)

**Your Server Environment**
* own setup
  * Deployment: monolith 
  * Deployment type: deb
  * ThingsBoard Version: 3.7
  * Professional Edition
  * Ubuntu 

**Your Client Environment**

* OS: Windows 10
* Browser Chrome
* Version: 126.0.6478.183

**Your Device**

* Connectivity
  * Gateway
  * Edge

**To Reproduce**
It is working and each a couple of days, it crashes

**Additional context**
We have the Gateway instance and Edge instance on-premise. Thingsboard is in GCP. 
It looks good, but after 2 days. TB stops the postgres.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashdam** [comment]
Activate linger so postgres is not killed while disconnecting user
`loginctl enable-linger $USER`

this solved our problem un ubuntu 22
