### ISSUE TITLE
Custom Timeseries Widget to Only show the Avg Values

### ISSUE THREAD

**Issue by Chase272** [thingsboard/thingsboard#11289]
**Component**

 * UI

**Description**
I want a make a Custom Timeseries Widget by maybe making changes to the default line chart widget so I can just get the Avg Value and key name on the center and hide the whole line chart. How do i access the HTML properties of the widget as in widget editor i just see <tb-time-series-chart-widget > and not a whole lot of options to customize with

![image](https://github.com/user-attachments/assets/64363650-0aa9-430b-bbc6-b2d9865f8356)

**Environment**

 * ThingsBoard: Community Edition v3.7.1
___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by myroslav-tb** [comment]
Hi @Chase272, you can use an HTML value card widget and configure it to apply the average aggregation function to a data key.

**Comment by Chase272** [comment]
> Hi @Chase272, you can use an HTML value card widget and configure it to apply the average aggregation function to a data key.

@myroslav-tb Thanks for the reply but i also want it to aggregate values within the dashboard time window like it does in the Timeseries chart's legend. Its much better for my implementation that i use the same widget but change the html appearance
