### ISSUE TITLE
How to receive RPC call from server when the other devices are subscribing same topic

### ISSUE THREAD

**Issue by guo-tt** [thingsboard/thingsboard#1128]
Thingy52 sending temperature while subscribe "v1/devices/me/rpc/request/+" topic to wait for RPC call to control LED;

A script in my laptop subscribe "v1/devices/me/rpc/request/+" topic to wait for RPC call also. But The RPC call didn't go through my laptop, instead going to Thingy52.

How?

I have set all the relations between Thingy52 and my laptop..
I am following the windturbine RPC example.

**Comment by bryanyuan** [comment]
it's the same topic, but TB server send RPC request out according to the originator; if you add a rule node to change the originator from Thingy52 to laptop, laptop will receive RPC request.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
