### ISSUE TITLE
Alarm table button

### ISSUE THREAD

**Issue by jvruta** [thingsboard/thingsboard#11284]
**Description**

Where can I find the functions called by pressing the buttons in the default Alarm Table? (Acknowledge, Clear, Details, etc.)
I created a custom alarm table and i want to add the "Acknowledge Alarm" button, but I don't know what function to call.

**Comment by mykhailokornieiev** [comment]
Hi. You can get familiar with the following documentation
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/alarm.service.ts

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
