### ISSUE TITLE
Is it possible to use the same Kafka cluster for Thingsboard and TBMQ?

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#11286]
**Component**

 * Installation

**Description**
I would like to ask if it is possible to use the same Kafka cluster for Thingsboard MSA and TBMQ?
It would be interessting, if Redis could be a shared service also?

**Environment**
 * OS:  SLES 15 + Docker Swarm
 * ThingsBoard: 3.7
* TBMQ: 1.3

**Comment by pon0marev** [comment]
You can use Kafka and Redis for Thingsboard and TBMQ broker since they use different topics and keys. You will not encounter conflicts. However, if you expect a high service load, it is better to split the resources.
