### ISSUE TITLE
Where does the tenant/customer/asset’s telemetry data come from?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1129]
When I created a device named "TestDevice1", the I can send telemetry data by a simple .js file to the device, and I can see the telemetry data on the device detail page.
![image](https://user-images.githubusercontent.com/31084798/46654519-9dc4d900-cbdb-11e8-8fbc-85dac205fbbc.png)
Now, I want to see the asset's telemetry data, how can I do? I tried to related the device and asset like below
![image](https://user-images.githubusercontent.com/31084798/46654621-e5e3fb80-cbdb-11e8-866c-a15f8b0dc512.png)
I still cannot see the asset's telemetry data.
Can any one tell me how can I do ?

**Comment by vparomskiy** [comment]
Please describe how asset's telemetry data is submitted

**Comment by qwyinxiang** [comment]
I don't know how to generate asset's telemetry data. I want to know how to generate asset's telemetry data?

**Comment by qwyinxiang** [comment]
Thank you very much.
But this is not my purpose.
I related the device and asset, and generated device's telemetry data. I want to show the device's telemetry data on the asset's telemetry page. 
I don't is my idea right? if it is right, how can I do, by the Rule engine?

**Comment by vparomskiy** [comment]
It is a valid case. You need to duplicate telemetry form device to the related asset. You can make it inside RuleChains:

1. After the device's Telemetry saved, change message originator to the related asset with 'Change originator' Node
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator

2. Send messages (with changed originator) to saveTelemetry Node

**Comment by qwyinxiang** [comment]
Oh, I understand, thank you very much for your patience.

**Comment by qwyinxiang** [comment]
I created a rule chain link below, and I can see the device's telemetry data on the asset/user/tenant’ telemetry data.
![image](https://user-images.githubusercontent.com/31084798/46722261-b00c4900-cca7-11e8-92ae-374bc3a8a8ad.png)

I have one asset and two devices related to the asset, But the asset's telemetry data only shows the first related device's telemetry data. I expect the collection data of the  two devices on the asset.
How should this be achieved?
According to the following issue,
[https://github.com/thingsboard/thingsboard/issues/823](url)

Do I have to create a time series widget and select aggregation type sum before I can see a collection of device data on the asset's telemetry data?

**Comment by vparomskiy** [comment]
What is inside 'Duplicate*Data' script node?

**Comment by qwyinxiang** [comment]
This is my Duplicate Device Data script:
![image](https://user-images.githubusercontent.com/31084798/46723918-8b19d500-ccab-11e8-8852-41719ff5542b.png)
the following is my device's telemetry data.
![image](https://user-images.githubusercontent.com/31084798/46723965-a258c280-ccab-11e8-971b-11c7a19f7769.png)

**Comment by vparomskiy** [comment]
just to clarify - are you sure that asset has relations to both devices?

Did you try to enable debug mode inside Rule Nodes to see what is going on?

**Comment by qwyinxiang** [comment]
The asset relates to both devices, and I saw the Rule Node, there were the both two device's telemetry data.
Thank you for you patience.

**Comment by vparomskiy** [comment]
Could you please check this case:
deviceA and deviceB submit telemetry to the Thingsboard.
Telemetry form both devices should be copied in related Asset.
If telemetry timestamp of deviceA is the same as a timestamp from deviceB - then only 1 value will be saved in related Asset (Actually - both telemetry will be saved, but timestamp value is a part of primary key, and telemetry of deviceB will override telemetry of deviceA)

If it is your case then you will need to use Aggregation nodes for correct handling telemetries with the same timestamp.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/pe/analytics-nodes/

**Comment by vparomskiy** [comment]
@qwyinxiang - is this ticket still valid or we can close it?

**Comment by qwyinxiang** [comment]
I am sorry , I can't make the timestamps of the telemetry data of the two devices exactly the same, they are always a little worse.
Thank you for your reminder, I plan to study the use the aggregation node.
I will close this issue soon.
