### ISSUE TITLE
How to follow device group sharing in rule chain

### ISSUE THREAD

**Issue by Lucas-Drakon** [thingsboard/thingsboard#11293]
**Component**

 * Rule Engine

**Description**
I have multiple devices set up that are part of multiple device groups (all owned by the tenant), which are then shared with various customers.
I am trying to send telemetry posts, by HTTP POST, from devices to all customers that have access to the device. Each customer will have an external URL for where to send the data to, and some customers might not want data sent to them.
Is this possible? If so, how would this be accomplished?

**Environment**

 * OS: Thingsboard Cloud
 * ThingsBoard: Current Thingsboard Cloud (3.7?)
 * Browser: N/A

**Comment by ssakharova** [comment]
Hello @Lucas-Drakon,

Could you please provide more details about your case? 
Also, what result do you want to achieve, and how do you try to send telemetry data via HTTP POST from devices to all customers?

**Comment by Lucas-Drakon** [comment]
Thanks for the reply.
I have found a method to achieve what I want.

I have the devices owned by the tenant and in device groups that are shared to the customers. Then the devices have a relation to assets (for invoice purposes) which have relations to the customers that I want the data streaming to.
This allows me to retrieve a URL from the customer attributes to use in a REST API call rule chain node to send the data.

I will now close this issue.
