### ISSUE TITLE
How to use the  Rule Chain Node 'rpc call request'

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#11298]
**Rule Chain Node 'rpc call request'**

 
 * Rule Engine
 

**Description**
 How to use Rule Chain Node 'rpc call request'?  
 
 the tip show 'If the RPC call request is originated by REST API call from user, will forward the response to user immediately.' 

I assume that if  someone make the RESTful API call : '/api/rpc/twoway/{deviceId}'

that will 'Sends the two-way remote-procedure call (RPC) request to device' 

so then event the device not response, we still can use the rule node 'rpc call request' return response to the caller of the RESTful api ?  seem it is not, but the tip seem can return response to API invoker ? 

I use the Rule Chain Node 'rpc call reply' , it also not work.

**so summary**:  my question is when invoke the API '/api/rpc/twoway/{deviceId}',  how to use RuleChain node return response to API invoker even the target device not online ?    seem this question is stupid, but one case :  I want use RPC widget from dashboard,  eg: make RPC call from widget to rule chain ,  rule chain node intercept the RPC call and handle it, after that return response directly without pass the RPC call to target device . 

so if possible ?   or how to pass data from widget to rule chain,  ( not through the javascript x-service) 

**Environment**

 * OS:  Mac
 * ThingsBoard: cloud
 * Browser: chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by liotys** [comment]
Hi, I guess it's not possible with rpc request which needs a response from a device. May be you should look with the 'api/rule-engine/' in order to push a request to the root rule-chain and then the 'rest call reply' node send the response to the API caller.
