### ISSUE TITLE
Fullscreen dashboard, top status bar cleanup

### ISSUE THREAD

**Issue by nikil511** [thingsboard/thingsboard#113]
End customers don't need a JSON export of their dashboard, or the device selection.
Less is more ;-)

**Comment by ashvayka** [comment]
I believe this need to be configurable ( for example list of check boxes for each feature in tool bar). Anyway, some users may want to change devices using selector

**Comment by ashvayka** [comment]
This is now implemented. Please check generic email settings.

**Comment by debu99** [comment]
From which user? sysadmin or tenant? I can't find this generic email settings, on sysadmin user, there is no related for this?
