### ISSUE TITLE
How can I set Role Based Access control.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11305]
I am trying to implement role based access control but due to I am newbie on the thingsboard I doesn't understand the Generic Role and Group Role. 

![Screenshot from 2024-07-29 15-12-10](https://github.com/user-attachments/assets/0ccefd70-0fef-40bd-874e-4267c33d895f)

I want this functionality how can i do this.

I don't want to allow user admin group to edit dashboard. so to implement this which permissions i can give.

**Comment by mykhailokornieiev** [comment]
Hi
You can get familiar with the following documentation:
[RBAC](https://thingsboard.io/docs/pe/user-guide/rbac/)
In general, "Generic role" provides the neccessary permissions to all entities under the necessary user group. 
[Generic Roles](https://thingsboard.io/docs/pe/user-guide/rbac/#generic-roles)
 "Group role" makes it only for the specific entity group (device, assets, etc).
 [Group Roles](https://thingsboard.io/docs/pe/user-guide/rbac/#group-roles)
To forbid user group to edit dashboard, you will need to specify all necessary permissions **except** for "Dashboard" -> "Write"
[Permissions](https://thingsboard.io/docs/pe/user-guide/rbac/#permissions)

**Comment by Vaibhav0216** [comment]
Hi
Thank you for helping me.
I want to make 2 different dashboards for some people ( group 1) . I want
to show dashboard 1 and the other hand group of other peoples ( group 2) .
I want to show dashboard 2. How can i do this in thingsboard. I go through
the thingsboard documentation but it doesn't work for this.

Best regards,
Vaibhav

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
