### ISSUE TITLE
Struggling with accessing asset devices when asset is dashboard state

### ISSUE THREAD

**Issue by zelms** [thingsboard/thingsboard#11300]
**Component**
 * Generic

**The Issue**
I can't get the devices of an asset that is the datasource of a widget, specifically when the asset is set as the dashboard state.

**What I'm Trying To Do**
I have multiple different assets, and from the dashboard I'd like the ability to click on one to see all the devices related to that asset. For example, if I have three assets (Room A, Room B, Room C) and each asset has multiple devices (temperature sensor, humidity sensor, etc.) then how can I list all assets on a dashboard where when clicked on, a list of their devices is shown? Eventually I would like to also be able to click on one of those devices and see all of its attributes as well. Ideally this would be in three separate widgets, one listing all assets and their labels, one listing the name of the asset previously selected and its devices with the most recent device data, and the last one with the device name listing time series data. The last widget I can figure out myself, but I'm really struggling with getting a list of devices from an asset.

**What I've Tried**
I'm familiar with dashboard states and that is what I've been using in an attempt to get this to work. Currently I can get a list of all assets, using an asset admin table, then have a selected asset from that table appear in a separate entities tables through updating the dashboard state using widget actions. I'm still unable to get the devices of this asset, only the asset itself. I considered using an entity hierarchy, but I'd like to have a more detailed display of the attributes of each device than what it's able to provide. I also considered modifying the answer from #3577 but I haven't been able to get the solution working yet. In an attempt to get it working I looked for documentation on custom subscriptions (which the answer uses) but couldn't find anything outside of [the basic documentation](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#custom-subscriptions) provided in the widget development article. The only documentation I could find about many of the functions used in that answer was the source code for widget development, so I'm also open to hearing about any other documentation that may help me figure this all out.

**Environment**
 * OS:  Ubuntu 23.10
 * ThingsBoard: 3.7.0
 * Browser: Chromium 126.0.6478.182

**Comment by mykhailokornieiev** [comment]
Hi
For such purpose, you can use the "Relations Query" entity alias.
It will look something like this:
![image](https://github.com/user-attachments/assets/5b267b83-16e7-4b87-a0ad-d1d2c18974a7)
![image](https://github.com/user-attachments/assets/f1b839bc-1e1e-4124-9b69-89d38e10fdda)
![image](https://github.com/user-attachments/assets/32865190-4d19-4630-b545-debdd1497e03)
![image](https://github.com/user-attachments/assets/8a1a8268-ff7d-468e-a7f7-2eecd2e45efe)
![image](https://github.com/user-attachments/assets/23ed1d9b-d115-41fa-83e2-17a9df7abe66)
![image](https://github.com/user-attachments/assets/0666b5cf-29e7-4f1d-8b47-c00b3284ea7a)
![image](https://github.com/user-attachments/assets/0fce8bae-6828-4411-ad49-fdafe0221c3a)
![image](https://github.com/user-attachments/assets/1710ea80-a3ae-40db-9116-07dde4d1cacc)

**Comment by zelms** [comment]
This is exactly what I needed, thank you so much!
