### ISSUE TITLE
ThingsBoard RPC parameters

### ISSUE THREAD

**Issue by ajmachin** [thingsboard/thingsboard#11309]
**Component**
 * Rule Engine

**Description**
Hello,

I am attempting to follow this [tutorial](https://thingsboard.io/docs/user-guide/integrations/custom/) in order to achieve a similar result. My objective is to utilise Knob Control to retrieve the latest telemetry value from a device.

I am encountering an issue when attempting to respond to the RPC method, as I do not have either the session ID or the request ID (I do have the UUID of the request in the metadata, but it is not an integer as the function requires). These arguments are not mentioned in the tutorial, but they are mandatory when sending an RPC response.

How can I obtain them if they are not sent in the request?

**Environment**
OS: Docker on Ubuntu 22.04.4 LTS
ThingsBoard: 3.7.0PE
Browser: Microsoft Edge Versión 127.0.2651.74

**Comment by ssakharova** [comment]
Hello @ajmachin,

For further assistance, please provide the following screenshots and information:

1. The current configuration of your Knob Control widget.
2. The configuration details of your rule chain.
3. The specific RPC request you are sending.

**Comment by ajmachin** [comment]
Hi @ssakharova,

I am attaching the information you required in the latest reply:

* Widget
![Knob widget configuration](https://github.com/user-attachments/assets/facfeb43-90f6-4ce4-9724-db42837f5d81)

* RPC rule
![RPC rule chain](https://github.com/user-attachments/assets/637248ae-73a2-4362-bc1c-d09daaf4c18d)

* Payload script
![Javascript function](https://github.com/user-attachments/assets/7230c2c9-5e9e-4938-a062-87cd86dd2cc3)

As you may see in the last picture, the message does not have none of the parameters needed, the session ID and request ID, a must to perform the desired operation.

```java
public void onMsg(TbContext ctx, TbMsg msg) {
	String serviceIdStr = msg.getMetaData().getValue(config.getServiceIdMetaDataAttribute());
	String sessionIdStr = msg.getMetaData().getValue(config.getSessionIdMetaDataAttribute());
	String requestIdStr = msg.getMetaData().getValue(config.getRequestIdMetaDataAttribute());
	if (msg.getOriginator().getEntityType() != EntityType.DEVICE) {
		ctx.tellFailure(msg, new RuntimeException("Message originator is not a device entity!"));
	} else if (StringUtils.isEmpty(requestIdStr)) {
		ctx.tellFailure(msg, new RuntimeException("Request id is not present in the metadata!"));
	} else if (StringUtils.isEmpty(serviceIdStr)) {
		ctx.tellFailure(msg, new RuntimeException("Service id is not present in the metadata!"));
	} else if (StringUtils.isEmpty(sessionIdStr)) {
		ctx.tellFailure(msg, new RuntimeException("Session id is not present in the metadata!"));
	} else if (StringUtils.isEmpty(msg.getData())) {
		ctx.tellFailure(msg, new RuntimeException("Request body is empty!"));
	} else {
		if (StringUtils.isNotBlank(msg.getMetaData().getValue(DataConstants.EDGE_ID))) {
			saveRpcResponseToEdgeQueue(ctx, msg, serviceIdStr, sessionIdStr, requestIdStr);
		} else {
			ctx.getRpcService().sendRpcReplyToDevice(serviceIdStr, UUID.fromString(sessionIdStr), Integer.parseInt(requestIdStr), msg.getData());
			ctx.tellSuccess(msg);
		}
	}
}
```

Let me know if you need anything else. 

Looking forward to hearing from you.

Kind regards.

**Comment by ssakharova** [comment]
Hello @ajmachin,

Thank you for your response. 
Please try to change the RPC call reply rule node in your rule chain to the RPC call request rule node.

**Comment by ajmachin** [comment]
Hello @ssakharova,

Thank you for your message.

I have followed the method you advised but have not yet achieved the desired result. I may be mistaken, but I understood that the RPC call request sends the request to the devices, rather than responding to the originator of the message (the dashboard).

The devices are unable to respond to downlink commands, therefore the last value must be retrieved via the stored values. This is the reason I have been trying to use the telemetry originator and RPC call reply rule node.

I look forward to your reply.

Kind regards,

**Comment by ssakharova** [comment]
Hello @ajmachin,

The reality is that RPC widgets only function with native RPC. Unfortunately, given your scenario, the implementation you want to achieve will never work.
