### ISSUE TITLE
Dashboard export resets selected device

### ISSUE THREAD

**Issue by Mr-Mime** [thingsboard/thingsboard#11308]
**Component**

 * UI
 * Generic

**Description**
When using the "Export as PDF/PNG/JPEG" function for a dashboard, the selected device is not used for the report.
We do not pass the device as an dashboard state parameter. The device is selected via the alias selection.
When opening an dashboard it opens with the time window that was selected in the edit mode and with the device, that was most recently added to the devices. 

Steps to reproduce:
1. Open dashboard, it opens eg. with device A and time window "last 5 minutes"
2. Change the device to device B and time window to "last 10 minutes"
3. Click "Export to pdf"
4. The generated pdf will show data for the correct time window of "last 10 minutes" but with values from device A

I would expect to see the data of device B, as this one was selected and showed graphs in the dashboard.

My suspicion is, that the device is not passed to the report server which opens the headless browser.
Is this an bug or unintended behavior?
What is an possible solution (using the dashboard sate would mean a lot of work to restructure our way to make data available for customers.

Thanks in advance.

**Environment**

 * OS: Ubuntu 20.4.6
 * ThingsBoard: 3.7 PE
 * Browser: Firefox (also tested with chrome)

**Comment by pon0marev** [comment]
You'll need to use the dashboard state to ensure the web report shows the selected entity or page. Otherwise, you will see the entity preselected during the initial dashboard load.

**Comment by Mr-Mime** [comment]
Yeah I figured that out.
I guess by design there is no other way right now, isn't it?

Because from what I see, the timewindow is somehow passed to the headless server when rendering, but not the device.

But this might be a feature request then :D

**Comment by pon0marev** [comment]
By design, reports now work only using the dashboard state. The web report service must know about the state of the dashboard to render it correctly.
A workaround may be to develop your own extension that will use the [html2canvas](https://html2canvas.hertzen.com/documentation) library and use _**tb-dashboard-layout**_ as the rendering element.

![image](https://github.com/user-attachments/assets/7b5a504a-50d7-40bd-957e-312013768fa9)

**Comment by Mr-Mime** [comment]
okay, thank you very much for the help and the hint with html2canvas.

I see the question as answered
