### ISSUE TITLE
Issue with Device Inactivity Alarms after ThingsBoard Cloud update 3.7.0.3PAAS

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard#11311]
**Component**

 * Generic

**Description**
After the recent major update of ThingsBoard Cloud to 3.7.0, the Cloud has an issue raising the Inactivity/Activity alarms. We have a few Devices in the Cloud, and the TB Cloud platform randomly raises their inactivity alarms. Please find attached the screenshot of a Device where the inactivityTimeout crosses the lastActivityTime value based on the current time, but there is no alarm at ThingsBoard.

![image](https://github.com/user-attachments/assets/01556079-b1bd-482d-b7fc-4f050d299d04)

**Environment**
 * ThingsBoard Cloud: 3.7.0.3PAAS
___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @akseerali  

We are preparing some changes to the device profile alarm handing logic for the upcoming v3.8. Please wait for v3.8 release and update this thread if the issue persists. For more information on the upcoming release, please see https://github.com/thingsboard/thingsboard/milestones and https://thingsboard.io/docs/reference/roadmap/

**Comment by ashaforost** [comment]
Closing the issue due to inactivity. Feel free to reopen.
