### ISSUE TITLE
Access attributes in Timeseries Chart

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#11314]
Hello,
Is there a way to access an attribute from a temperature value in a Timeseries Line Chart? In this case, I need to use an attribute as an offset and either add or subtract it from the timeseries number. Can this be implemented? Also, if I have an attribute that represents the unit from the user, I would like to change the value accordingly. Thank you.
![image](https://github.com/user-attachments/assets/d94a4bce-8ee4-4f38-9355-3182f7fceb95)
![image](https://github.com/user-attachments/assets/a1fe67f9-aa16-41ed-b623-7a8180414524)

**Comment by mykhailokornieiev** [comment]
Please get familiar with this comment
https://github.com/thingsboard/thingsboard/issues/10896#issuecomment-2149933773
Closed as duplicate

**Comment by nicovon24** [comment]
What happens if the user defines other unit such as BAR instead of Millibar and I have to do the calculation?
I have to define three different widgets depending the user preferences, and conditional render it in a Markdown, too much job for a unit, or in this case for a substraction or sum.
If i have four widgets like this, i have to define twelve states.
Ok, thanks, but this is not a good feature
