### ISSUE TITLE
Hourly timeseries limits

### ISSUE THREAD

**Issue by SindreLindahl** [thingsboard/thingsboard#11317]
This question applies to charts, for example timeseries chart.

I'm creating a simple graph for temperature data for a location. Data is hourly, so for example today at 13:00, temp is 25 C. At 14:00, it could be 26 C. But the graph will summarize two data points together, so for example 25C and 26C for two different hours displays as 51C (which is obviously crazy wrong). It's easiest to very when using "Count" aggregation instead of "Sum", which then shows 2 for any time, Of course one way to solve this is to choose "None" as aggregation.

But why do Sum or other aggregations combine more than one data point (a single hour), when grouping interval is set to 1 hour (or less)? Is this a bug?

**Comment by pon0marev** [comment]
Please provide an example of a widget without aggregation and with aggregation.
And provide the exported dashboard.

**Comment by SindreLindahl** [comment]
Thanks for reply. Wasn't able to recreate it today (so typical!). So I'll close this and save an example for next time.
