### ISSUE TITLE
generate dashboard state in rule chain with device id for report

### ISSUE THREAD

**Issue by buchvC** [thingsboard/thingsboard#11316]
**Component**

 * Rule Engine

**Description**

We have a dashboard to select a specific device which will show a temperature chart(each device has a seperate dashboard state selected via the entity). 
I would like to create a report of the dashboard for a specific device in the rulechain. The Problem is that you have to select/know the dashboard id for every specific device, but i want to create the report dynamically for a device to send the report via email on a alarm.

Is it possible to calculate the dashboard id from the device id or get it from somewhere else?
Could this be possible in future versions?

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.7PE 
 * Browser: firefox

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. I'm not fully sure how you want to trigger rule chain, but you can create the same report via rule chain by specifying state in base64 format.
For example Base64:
`W3siaWQiOiJkZWZhdWx0IiwicGFyYW1zIjp7fX0seyJpZCI6ImRldmljZXMiLCJwYXJhbXMiOnsiZGV2aWNlcyI6eyJlbnRpdHlJZCI6eyJpZCI6IjA5YjNmMmYwLTNhOGEtMTFlZS04YzhjLTI3MTExNDA5ZTFlYSIsImVudGl0eVR5cGUiOiJBU1NFVCJ9LCJlbnRpdHlOYW1lIjoiMXN0IGFzc2V0IiwiZW50aXR5TGFiZWwiOiIxc3QgYXNzZXQifSwidGFyZ2V0RW50aXR5UGFyYW1OYW1lIjoiZGV2aWNlcyJ9fV0=`
Decoded JSON:
`[{"id":"default","params":{}},{"id":"devices","params":{"devices":{"entityId":{"id":"09b3f2f0-3a8a-11ee-8c8c-27111409e1ea","entityType":"ASSET"},"entityName":"1st asset","entityLabel":"1st asset"},"targetEntityParamName":"devices"}}]`
So, you can use rule chains with Originator Fields rule node to get the necessary device id and Transformation Script rule node to encode this data in Base64 format.
