### ISSUE TITLE
Dashboard set alarm Schedule 

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11328]
* UI

**Description**
I want my customer be able to set his alarm thresholds. I managed to do the simple temperature demonstration provided by thingsboard.
![image](https://github.com/user-attachments/assets/c0b30eb5-0979-4ca2-a2cc-7ddc6500c6d7)

Now i want it to be more configurable where the customer is able to set between what time the alarm should work ex. 8am to 4pm.

This can be configured by the tenant as the picture shows. I simply want a way for the user to do this inside a dashboard.
![image](https://github.com/user-attachments/assets/e4926063-3a75-40f6-a44c-98ecbbf632fd)

**Environment**
 * OS:  docker
 * ThingsBoard: PE

**Comment by mykhailokornieiev** [comment]
Hi. You can use the next logic:
![image](https://github.com/user-attachments/assets/e6b3d786-e383-4899-bc48-d1ae6bafbae6)
![image](https://github.com/user-attachments/assets/f32e0533-7baa-4e01-b80b-0bab9b79bc0b)
![image](https://github.com/user-attachments/assets/9b3f56bd-1807-4369-81a1-673f261fafa3)
Such an option is available for "active at a specific time" and "custom" alarm schedule.
In this case, customer will need to have "write" permissions to the necessary device, so it will be possible to change alarm schedule for this device by setting it in JSON format as a device server attribute.

**Comment by xTwigx** [comment]
Amazing Thanks. Now id there a way i can have the user use that json without writing json?

Like is there a widget with returns that style of json?

**Comment by mykhailokornieiev** [comment]
Hi. I'm glad to hear that this info is useful for you. In this case, I close this ticket. Feel free to open a new one in case any questions or issues arise.
