### ISSUE TITLE
how to import and export database of an project from multiple project for community edition ?

### ISSUE THREAD

**Issue by chandreshkalariya** [thingsboard/thingsboard#11325]
We have some concerns on project database exporting.
We are doing multiple projects in a system for various site.
But I want to export and import only site 1 project from that system.
How can we do that ?

**Comment by Ultrazombie** [comment]
Hello @chandreshkalariya 

What do you mean by project and multiple projects? Tell us in more detail what you want to achieve as a result.

Perhaps the version control function will help you.

Best regards,
Artem.

**Comment by chandreshkalariya** [comment]
Hi,

 

I mean is that.

I design a dashboard for site 1 in my PC

In same login, in design dashboard for site 2.

So I want to export the data base only for site 1 to use for installation in site 1.

 

 

Best Regards,

Chandresh Kalariya

**Comment by Ultrazombie** [comment]
You can use the version control feature to export and import only the dashboard, not all databases;
Or export to JSONm and import on site 1.

**Comment by Ultrazombie** [comment]
Closed due to inactive.
