### ISSUE TITLE
best way to remove a device /asset via Rule Chain

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#11333]
**Rule Chain**

  
 * Rule Engine
 

**Description**
 seem no way to remove a device / asset via Rule Chain node, or what best way to do the delete operation in rule chain ?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by icoco** [comment]
for data safety , not allow rule chain do delete device directly ?

**Comment by mykhailokornieiev** [comment]
@icoco not sure if I understand your question at all. Please describe it in as much detail as possible

**Comment by mykhailokornieiev** [comment]
@icoco yes, there is no standard node that can delete any entity directly. Only workaround is to use Rest API call node.
