### ISSUE TITLE
[Urgent] Why can't I just create 2 MQTT Brokers and 1 Network Load Balancer to establish high availability?

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11349]
Hi All,

Why can't I just create 2 MQTT Brokers and 1 Network Load Balancer to establish high availability?

My system architecture are: Sensors --> Network Load Balancer --> 2 MQTT broker (TBMQ or Mosquitto) --> Thingsboard.

Is this architecture possible? If not, do you think there is any reason for this?

Thanks.

**Comment by pon0marev** [comment]
Do you mean 2 different mqtt brokers or 2 replicas of the same broker? If there are two replicas of one broker, it is already implemented in our Kubernetes deployment files. https://github.com/thingsboard/tbmq/blob/main/k8s/aws/tb-broker.yml

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
