### ISSUE TITLE
About after the new button is added then calling dialog

### ISSUE THREAD

**Issue by majp1** [thingsboard/thingsboard#1134]
I've created a new dialog ,that I want to call when I click on the new button on the device. Now that the dialog and button have been added, I don't know what to do next to enable me to call the dialog when I click the button.

**Comment by majp1** [comment]
And what's the front frame of Thingsboard? I didn't understand it. 
please explain it.thanks

**Comment by majp1** [comment]
> 如果您将在我们的https://cloud.thingsboard.io/实例中注册，您可以“演示智能计量”仪表板作为您案例的参考：
> “演示智能计量”仪表板 - >建筑物 - >“建筑信息”按钮 - >新对话框已打开
> 
> 这是一个自定义操作代码
> 
> ```
> var $injector = widgetContext.$scope.$injector;
> var
>     types = $injector.get('types'),
>     attributeService = $injector.get('attributeService'),
>     $q = $injector.get('$q'),
>     $mdDialog = $injector.get('$mdDialog'),
>     $filter = $injector.get('$filter'),
>     $document = $injector.get('$document');
> getInfoAttributes().then((attributes) =>{
>     showInfoDialog(attributes);
> }
> ,
> () =>{showFailedDialog('Unable to get info attributes.');})
> ;
> 
> function
> showInfoDialog(attributes) {
>     $mdDialog.show({
>         controller: ['attributes', '$mdDialog', InfoDialogController],
>         controllerAs: 'vm',
>         template: infoDialogTemplate,
>         parent: angular.element($document[0].body),
>         locals: {
>             attributes: attributes
>         }
>         ,
>         targetEvent: $event,
>         clickOutsideToClose: false,
>         fullscreen: true
>     }).then(() => { openBuildingDetails();});
> }
> 
> var
>     infoDialogTemplate = '<md-dialog aria-label="Info">' +
>         '<form name="theForm">' +
>         '<md-toolbar>' +
>         '<div class="md-toolbar-tools">' +
>         '<h2>{{vm.entityTitle}}</h2>' +
>         '<span flex></span>' +
>         '<md-button class="md-icon-button" ng-click="vm.close()">' +
>         '<ng-md-icon icon="close" aria-label="Close"></ng-md-icon>' +
>         '</md-button>' +
>         '</div>' +
>         '</md-toolbar>' +
>         '<md-dialog-content>' +
>         '<md-content class="md-padding">' +
>         '<div layout="column" flex>' +
>         '<div><h3>{{vm.address}}</h3></div>' +
>         '<div style="padding-top: 20px;"><img src="{{vm.image}}"></img></div>' +
>         '<div layout="row">' +
>         '<md-button class="md-raised md-primary" ng-click="vm.openDetails()">' +
>         'Building details' +
>         '</md-button>' +
>         '<span flex></span>' +
>         '</div>' +
>         '</div>' +
>         '<md-content>' +
>         '</<md-dialog-content>' +
>         '<md-dialog-actions layout="row">' +
>         '<span flex></span>' +
>         '<md-button ng-click="vm.close()" style="margin-right:20px;">Close</md-button>' +
>         '</md-dialog-actions>' +
>         '</form>' +
>         '</md-dialog>';
> 
> function
> InfoDialogController(attributes, $mdDialog) {
>     let vm = this;
>     vm.entityTitle = entityName;
>     vm.image = getAttributeValue(attributes, 'image');
>     vm.address = getAttributeValue(attributes, 'address');
>     vm.close = () =>
>     {
>         $mdDialog.cancel();
>     }
>     vm.openDetails = () =>
>     {
>         $mdDialog.hide();
>     }
> }
> 
> function
> getAttributeValue(attributes, key) {
>     var foundAttributes = $filter('filter')(attributes, {key: key}, true);
>     if (foundAttributes.length > 0) {
>         return foundAttributes[0].value;
>     } else {
>         return null;
>     }
> }
> 
> function
> openBuildingDetails() {
>     var params = {
>         entityId: entityId,
>         entityName: entityName
>     }
>     widgetContext.stateController.openState('building_view', params, false);
> }
> 
> function
> getInfoAttributes() {
>     var deferred = $q.defer();
>     attributeService.getEntityAttributesValues(entityId.entityType, entityId.id,
>         types.attributesScope.server.value, 'image,address',
>         {
>             ignoreLoading: true
>         }
>     ).then((attributes) => {
>         if(attributes && attributes.length
> )
>     {
>         deferred.resolve(attributes);
>     }
> else
>     {
>         deferred.reject();
>     }
> }
> ,
>     () =>
>     {
>         deferred.reject();
>     }
> )
>     ;
>     return deferred.promise;
> }
> 
> function
> showFailedDialog(content) {
>     $mdDialog.show(
>         $mdDialog.alert().parent(angular.element($document[0].body)).clickOutsideToClose(true).title(`Unable to display info for ${entityName}`).textContent(content).ariaLabel('Action Demo Dialog').ok('Close').targetEvent($event)
>     )
>     ;
> }
> ```

Thank you very much. I'm trying.

**Comment by alexsmartens** [comment]
Thanks @vparomskiy,
I think your suggestion should solve my challenge of getting attribute data in a time series widget (#1737).

I am wondering whether it is possible to request all available shared scope attributes at once without actually specifying their names?
