### ISSUE TITLE
Permission issue for Waste Management solution template

### ISSUE THREAD

**Issue by SherryTt** [thingsboard/thingsboard#11348]
**Component**
*Permission

**Description**
"I created a count widget following the waste management solution template (see attached picture). This count widget is linked to the map icon for filtering. The issue is when a user clicks on the count widget to filter the map icon, a dialog shows 'Permission Denied. You don't have permission to perform this operation!' I even gave users 'Dashboard (Read and Control)' permission. If I change the permission to 'Customer User' or 'Customer Admin', users can click the widget to filter the map icons, but they can also edit the dashboard, which we don't want.

What permissions would be the solution for this case? I want users to have READ and Control (click the count widget to filter the map and switch the widget on/off) permissions for their dashboard.

Thank you.

**Environment**

TB version : ThingsBoard v.3.5.1PE
OS : Windows 11 v23H2
Browser: Google Chrome Version 127.0.6533.88 (Official Build) [(64-bit)](url)
![2](https://github.com/user-attachments/assets/08d4e09f-375a-4d47-8e04-adf7b73afabb)
![1](https://github.com/user-attachments/assets/3360484e-c52a-4c1e-a464-c1d413a59be3)

**Comment by dealnat** [comment]
Hello,

This solution template has a custom action when the button is clicked. The logic of this action is to write which Thrashbins users should see in user attributes. So, for this action role should have "Attributes Write" permission for "User"
![image](https://github.com/user-attachments/assets/fef96800-529c-4930-a7cd-e6de7ca75dd9)

Best regards, 
Oleksii Kuripko

**Comment by SherryTt** [comment]
Hi Oleksii Kuripko,

Thank you so much for the advice. I have given the user write permission, and it works perfectly. I always practice customizing and designing from the solution template and select the useful functions for my work.

Thanks, Oleksii Kuripko and the Thingsboard team!
