### ISSUE TITLE
rule chain node "  rpc call request ",  only return one result while split the messages to item then make rpc call to device

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#11346]
### rule chain node "  rpc call request ",  only return one result while split the messages to item then make rpc call to device  
 
 
* Connectivity
  * MQTT
  

**To Reproduce**
1)  send two way request with params : [{ id: 1, name :'aa' }, {id:2, name:'bb'"] and method 'save', eg:
```
{
 method :'doSaveOnDevice', 
params : [{ id: 1, name : "aa" },{id:2, name: "bb"}] 
}
```
2) rule chain handle the request and  split params to message items then make new  node " rpc call request " with new method 'doSaveOnDevice',  the message : 

```
{
 method :'doSaveOnDevice', 
params : [{ id: 1, name :'aa' }]
}
``` 

3) client side handle the two requests, and return response result with 'v1/devices/me/rpc/response/${requestid}'

4) question is,  in the rule chain,  why the node  " rpc call request " only got one response ?  but client side has publish data on topic 'v1/devices/me/rpc/response/${requestid}' twice ~

what make this wrong case ..... or how to got the RPC response  in RuleChain totally ?
 
________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hello,

When a request with the array is received to the rule chain, it has UUID in the metadata. The response is generated according to this UUID, so when you give the server 2 requests with the same UUID, the response will be generated only for the one request, and the second will be ignored. Unfortunately, Thingsboard doesn't support flow with split RPC natively as you want. As a workaround, you can add a Script transformation node after the Split node, which will override the UUID for each split RPC to a unique one. 
Here is an example of a Script transformation node:
`
function getRandomInt(min,max) {
  var minCeiled = Math.ceil(min);
  var maxFloored = Math.floor(max);
  return Math.floor(Math.random() * (maxFloored - minCeiled + 1) + minCeiled);
}
metadata.requestUUID = metadata.requestUUID.slice(0,-5) + getRandomInt(10000,99999); //last 5 chars of UUID generated randomly in scope of one request
var newMsg = {};
newMsg.method = "test";
newMsg.params = msg;
return {msg: newMsg, metadata: metadata, msgType: msgType};
`
Also, we think that is a valid issue, so we added "Bulk RPC" functionality into our product backlog, issue PROD-4129.

Best regards, Oleksii Kuripko
