### ISSUE TITLE
Are special custom time frames for dashboards possible?

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#11342]
**Component**

 * UI
 * Generic

**Description**

Would it be possible to define custom time intervals for dashboards?

I need following 8h time frames:
* 6:00 - 14:00
* 14:00 - 22:00
* 22:00 - 6:00

Is this possible by configuration or code changes?

If code changes are needed, could you please point me the right direction?
Would be nice to know the specific class that needs adoption.

Many thanks in advance!

**Environment**

* OS: SLES 15 + Docker Swarm
* ThingsBoard: 3.7

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
You can try to implement it using Date-range-navigator widget. I was able to use 8:00 - 20:00 for each day.
![image](https://github.com/user-attachments/assets/de495c44-7492-4a7c-9770-78e3de2cb73d)
![image](https://github.com/user-attachments/assets/81031edf-7ce4-4b38-8f64-da42ab7ae1d2)
Or, you can either modify this widget or create the custom one for three different time frames. 
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions

**Comment by apachler** [comment]
Hmmm, i have now tried to implement the Date-range-navigator widget but it is not possible to define a custom interval.
@mykhailokornieiev Any idea?

**Comment by mykhailokornieiev** [comment]
Since some time has already passed, I do not remember all the details. It seems that I managed to achieve the result as in the screenshot by setting the required interval on the widget and only then using the edit mod to change the time window and save it. After that, only the day changed, and the time frame was unchanged. If you need two or more such templates, then this widget will not suit you and you need to make a custom one.

**Comment by apachler** [comment]
ok thanks!
