### ISSUE TITLE
Issue with multi_slider (Collibellex). Thingsboard is killing 3 of the 4 multi-slider widgets in same dashboard 

### ISSUE THREAD

**Issue by matiasmelendez** [thingsboard/thingsboard#11358]
Multi_slider issue from [Collibellex-Thingsboard-Widgets](https://github.com/rossmann-engineering/Collibellex-Thingsboard-Widgets)

Iam having a problem when using more than one mult_slider widget in the same TB dasboard. I checked from many angles the device's code and it works well. Even when I use 10 thingsboard's "knob control" in same dashboard (each of them with its own set and get parameters). Communication works well when using the "know control". 
But when I use more than one multi_slider widget (each of them with 2 sliders) in the same widget, thingsboard is killing all of them except one. For example, if I have 4 multi_sliders, thingsboard kills 3 of them.
I am trying to deal with it for the last 2 weeks without success. Any idea of why is this happening?
Thank you very much for your time.
Any help will be welcome.

**Your Server Environment**
* own setup
  * Deployment: AWS - t2.large
  * Deployment type: docker-compose
  * ThingsBoard Version 3.5.1
  * Community Edition

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. This is a third-party custom widget that have no relations to Thingsboard repository. Please create your ticket in [this widget repository](https://github.com/rossmann-engineering/Collibellex-Thingsboard-Widgets)
In this case, I close this ticket.
