### ISSUE TITLE
Thingsboard Customization (Logo, Color...)

### ISSUE THREAD

**Issue by Petronella13** [thingsboard/thingsboard#11353]
**Component**

 * UI

**Description**
Hi, can you please assist me ... I want to Customize the ThingsBoard Community Edition (frontend ), Like changing the Logo, layout, colors and overall look and feel. How can I go about it please ?

**Environment**

 * ThingsBoard:  Community Edition
 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. There is no such possibility for Community Edition. 
There is White Labeling feature that available only for Professional Edition
https://thingsboard.io/docs/pe/user-guide/white-labeling/

**Comment by devaskim** [comment]
@Petronella13 You need to patch the frontend code and then r[ebuild the project](https://thingsboard.io/docs/user-guide/install/building-from-source/).

Here are source links:
[Logo](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/home.component.ts#L55)
[Color constants](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/scss/constants.scss#L34)
[Theming](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/theme.scss)

**Comment by HashstudiozTechnologies** [comment]
Hi, You can reach out to us, can help you with the customization of any nature and type.
![HashStudioz-Vivek-Sanghi-vivek sanghi@hashstudioz com-Contact](https://github.com/user-attachments/assets/4935b968-079a-4681-84d2-6668b4a4e3ad)

**Comment by Petronella13** [comment]
Thank you!

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by iamkaran** [comment]
@Petronella13 https://github.com/iamkaran/tb-override
