### ISSUE TITLE
Widget Filter feature :  Add dynamic use state parameter object value as  condition value

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#11352]
possible add feature on Widget Filter feature eg:
 
 
<img width="1189" alt="filter" src="https://github.com/user-attachments/assets/c4a6979e-d6e2-4300-9ca3-1f8c3a594146">

**Comment by ssakharova** [comment]
Hello @icoco,

Your feature request was rejected because it conflicts with the platform's design. Adding a dynamic use state parameter object value as a condition value is impossible.
