### ISSUE TITLE
generating random value

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1135]
i try to create a new graph widget , but i need to have two key values at a time , but it provide only one random key value , how can i make it to generate two key values ?

**Comment by gopirathnamt** [comment]
thank u bro , i created a new graph widget it shows the live data correctly but when i try to view history data , i  cant view it .

**Comment by gopirathnamt** [comment]
i submitted the data in numeric values only , i checked the datas

**Comment by vparomskiy** [comment]
and its still does not work for you, correct?
Is it possible to get an access to your env to verify it?

**Comment by gopirathnamt** [comment]
i am running thingsboard on my localhost , how can i share it ? do u have any team viewer like software ?

**Comment by vparomskiy** [comment]
1. In your root role chain, open 'Save timeseries' node and enable debug mode. Press save.
2. Wait while data from your devices is submitted to the thingsboard
3. Open 'Save time series' node and navigate to 'Events' tab
4. Find a message from your device (type 'IN') and press 'Data View' button, to show original message payload. This payload must contain telemetry value that does not visualized correctly in your widget.
5. Copy message payload to this thread for investigation

Example:
![debug_events](https://user-images.githubusercontent.com/4686483/47068614-6cf52d00-d1f5-11e8-80d7-6e9ba838e927.png)
![msg_data](https://user-images.githubusercontent.com/4686483/47068619-7088b400-d1f5-11e8-9fa9-95903b5531c0.png)

**Comment by gopirathnamt** [comment]
thanks bro , i found and resolved the problem . I think it works fine now .
