### ISSUE TITLE
Failed send notification to FCM : User doesn't use the mobile app on notification center

### ISSUE THREAD

**Issue by philiaa** [thingsboard/thingsboard#11366]
Description
hello everyone. thanks for thingsboard develeoper
i use thingsboard ce v3.7

i installled thingsboard platfom in my local ubuntu20.04 server and I did portforwording and ddns on the router.
and then all thingsboard platform work well

and i builded thingsboard mobile app(v1.2.0)
flutter build apk......
thingsboard mobile work well on my android phone.....all is good

i reciveed fem subject and message from firebase console....its no problems
but **when i send a notification message for All user(or tenant..etc) from thingsBoard notification center, I got "User doesn't use the mobile app" error**
so i checked source code....

/MobileAppNotificationChannel.java

        var mobileSessions = userService.findMobileSessions(recipient.getTenantId(), recipient.getId());
        if (mobileSessions.isEmpty()) {
            throw new IllegalArgumentException("User doesn't use the mobile app");
        }

**that's problem? need another setting? i guess.....cant make mobilesessions..whats wrong?
is it possible send notification to app via fcm on thingsboard pe version?**

**help me......i already reinstalled five times......thingsboard platform and app is same error**

![thigsboard error1](https://github.com/user-attachments/assets/0f1618ae-8f07-4230-b73f-4738157150e1)
![thigsboard error2](https://github.com/user-attachments/assets/2fe45831-50f0-4a21-ba38-cee43de1fe85)

**Comment by philiaa** [comment]
thanks for answer....@ViacheslavKlimov 

> Hello @philiaa, Are you sure you properly built the mobile app with the correct Firebase mobile-side configuration?
> 
> https://thingsboard.io/docs/mobile/getting-started/#step-4-optional-configure-push-notifications

I followed this procedure and did it. 
Step 4.1 Create Firebase project---> so i got private key...and upload to mobile settings
Step 4.2 Add Firebase to your mobile application
--> firebase login-> dart pub global activate flutterfire_cli-> flutterfire configure
Step 4.3 Check project configuration
---> check android/app/google-services.json....is ok...
---> i just use android...so i didnt set for ios
finally build apk
---> when i send message to thingsboard app on firebase console ... my thingsboard app receviced push message from firebase
---> i think that thingsboard app and firebase is communcation well

i have two question
1. if i generated new private key , need step 4,2 and step 4.3 again?
2.  "User doesn't use the mobile app" error issue caused by mobile app side? or server side?

actually....thingsboard mobile app is work well....without notification....
tell me any solutions please.....^^

**Comment by DeMotione** [comment]
Most likely problem is misconfiguration of `firebase_options.dart`. You can simply try to delete this file and after try to reconfigure your firebase following the steps you did before. Simply run `flutterfire configure` and check if file appended in /lib directory. After build your application and check if everything is working.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
