### ISSUE TITLE
Got error message each time i reload the page "The decoded tex message was too big ... " only on customer account

### ISSUE THREAD

**Issue by Agailh** [thingsboard/thingsboard#11363]
**Component**

 * Generic

**Description**
Everytime i reload the page (for update the entity from filter) i got this error message , but its only appear on some page , not all ,and only appear in customer account , with tenant account (can edit) its fine.
![image](https://github.com/user-attachments/assets/925e33ce-ee9c-40fb-aa39-d68e3f7d1a6f)

**Environment**

 * OS:  linux ubuntu 22.04
 * ThingsBoard: comunity  3.6.4
 * Browser: Chrome latest

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ssakharova** [comment]
Closed due to inactivity.
