### ISSUE TITLE
How to store our data at widgetContext to use it globally as variable?

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#11367]
**Cant we store some of our data at widgetContext to use it globally**

If possible, so please let me know how and where.
Thank you.

**Comment by devdoob** [comment]
No that's not possible. WidgetContext gets changed for each widget. 

To use something globally I would suggest you to use stateController.

PUSH
```
var stateId = self.ctx.stateController.getStateId();
var params = self.ctx.stateController.getStateParams();
params.startDate = self.ctx.$scope.startDate;
self.ctx.stateController.updateState(stateId, params);
```

 PULL
`var startDate = self.ctx.stateController.getStateParams().startDate;`

This code is for custom widget... if you want ot use this in TB provided widgets then replace `self.ctx` with `widgetContext`

**Comment by KashifAhmd** [comment]
Thanks @devdoob .
