### ISSUE TITLE
Failed to login Thingsboard: Unable to acquire JDBC Connection

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#11364]
**Component**

 * Generic

**Description**
I have installed Thingsboard (open source version) in AWS EC2 Linux OS.  So far accessing it without any problem. Suddenly while opening the login page, it is showing the following error message:
"Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection".

What is reason and how to recover? 

**Environment**

 * OS:  Linux 20.04 (installed AWS EC2 instance) 
 * ThingsBoard: version 3.4.2
 * Browser: Chrome and version: 127.0.6533.89 (Official Build) (64-bit)
    

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hello,
  
  This exception seems like Thingsboard is not able to connect to the database. Make sure that postgresql and postgresql@<version>-main services are running, the credentials provided to the thingsboard are correct, and you are able to connect to the DB with those credentials.
  If everything is OK, please provide Thingsboard and Postgresql logs for further investigation.
  
  Best regards,
  Oleksii Kuripko

**Comment by ashaforost** [comment]
I'm closing this issue as stale. Please feel free to reopen if you need any further assistance.
