### ISSUE TITLE
Cannot send RPC from CE Server via Edge server to a device

### ISSUE THREAD

**Issue by tonny1983** [thingsboard/thingsboard#11362]
**Description**
There is a raspberry Pi device connecting to a Edge server in the same LAN, that the Edge server connecting to a CE server via WAN. The device and dashboard are created from Edge server and automatically appears in the CE server.

The device using MQTT client to subscribe to the topic `v1/devices/me/rpc/request/+` which means it can response `the server to client PRC`. It works successfully when call RPC using `/api/plugins/rpc/oneway/{deviceId}` api via Edge server and also via dashboard in the Edge server. But however, neither the api call nor the bashboard works in the CE server, both of which returns TIMEOUT error.

**Screenshots**
(Edge server connected to the CE server normally)
![截屏2024-08-06 12 13 49](https://github.com/user-attachments/assets/f2d1dc7a-7701-4c18-b2e0-62a95faef629)

(CE server shows Edge server info correctly)
![截屏2024-08-06 12 11 03](https://github.com/user-attachments/assets/0eb4b4b5-5932-4576-8936-b61cef2a2200)

(Device status is active on the CE server)
![截屏2024-08-06 12 12 35](https://github.com/user-attachments/assets/7d9be481-3f6c-432e-a3b8-0660c5a0deee)

(Rule the device uses)
![截屏2024-08-06 12 09 17](https://github.com/user-attachments/assets/83548498-e93f-4d71-b5c3-e2473d9cd765)

(Timeout error shows in the bashboard)
![截屏2024-08-06 12 13 05](https://github.com/user-attachments/assets/b1833743-b0c2-4b8a-af9e-a968f00fedac)

**Server Environment**
* own setup
  * Deployment: monolith 
  * Deployment type:  rpm
  * ThingsBoard Version
  * Community v3.6.4
  * CentOS 7

**Client Environment**
**Desktop:**

* OS: MacOS
* Browser Chrome
* Version 127.0.6533.89

**Your Device**

Raspberry Pi 4

* Connectivity
  * MQTT

**Expected behavior**
The server side RPC should work from CE server via Edge server to the device.

**Comment by myroslav-tb** [comment]
Hi @tonny1983, please create the issue for the edge repository https://github.com/thingsboard/thingsboard-edge/issues
