### ISSUE TITLE
Custom Recipient for email

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11376]
**Description**
I currently have a dashboard witch I'm giving access to a customer and his sub-customers. In this dashboard I have a device sending me data via http integration. The dashboard also has an alert system where it uses alarm rules under a device profile. 
![image](https://github.com/user-attachments/assets/5c325854-e43e-4315-b870-9e815584429a).

This alarm gets triggered if a telemetry key from the device is less then a device server attribute set by the user. 
Then in the notification center , if a critical alarm is generated it sends an email to all the customer users (Recipients).

I want it changed where the customer can select who gets an email notification (from the main customer and from the sub-customer) when a critical alarm gets generated.
I also would like the customer to be able to select different users for different alarms.

**Environment**
Ubuntu Docker
ThingsBoard: PE

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by xTwigx** [comment]
I am currently also making alarms using Rule Chains so if there is an online with rule chain i will take it as well :)

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
