### ISSUE TITLE
After stopping Thingsboard, cannot start

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#11374]
**Component**

 * Generic

**Description**
I had some issues to access Thingsboard, which I installed in AWS EC2 instance. After deleting some log files wanted to restart Thingsboard.  For that I did the following:
$sudo service thingsboard stop
$sudo service thingsboard start 
But it did not start. When check the status with 
$sudo service status thingsboard   it shows the following:

sudo service thingsboard status
● thingsboard.service - thingsboard
     Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-08-07 03:57:13 UTC; 36min ago
    Process: 285610 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
   Main PID: 285610 (code=exited, status=1/FAILURE)

Aug 07 03:57:03 ip-172-31-34-110 thingsboard.jar[285626]:  ===================================================
Aug 07 03:57:03 ip-172-31-34-110 thingsboard.jar[285626]:  :: ThingsBoard ::       (v3.4.2)
Aug 07 03:57:03 ip-172-31-34-110 thingsboard.jar[285626]:  ===================================================
Aug 07 03:57:13 ip-172-31-34-110 systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 03:57:13 ip-172-31-34-110 systemd[1]: thingsboard.service: Failed with result 'exit-code'.

* If I start it, is starting, but only momentarily. Then again status is becoming 'failure'. 

(the above commands are executed by connecting EC2 with SSH)

**Environment**

 * OS:  Linux 20.20 LTS (inside EC2)
 * ThingsBoard: v3.4.2
 * Browser: Google chrome 

How to recover? My sensor data and demo system in running in Thingsboard. Need to start as soon as possible.

Any help would be very much appreciated.

Regards,
Debasish
___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by debacs83** [comment]
Had also problem to access PostgreSQL. After restarting postgresql, then restarting Thingsboard, it ran properly. Problem is solved.

**Comment by dealnat** [comment]
Hello,

As you found out on your own, this issue is related to the database's inaccessibility. Please make sure that the server with the DB has enough CPU, RAM, and Disk resources. 
To perform troubleshooting on your own, you can read /var/log/thingsboard/thingsboard.log next time

Best regards,
Oleksii Kuripko
