### ISSUE TITLE
Your connection is not private ( Login white labeling issue ) 

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11385]
**Description** 

**ERROR** 
Your connection is not private
Attackers might be trying to steal your information from iot.amset.in (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
net::ERR_CERT_AUTHORITY_INVALID 

**Extra Information** 
iot.amset.in normally uses encryption to protect your information. When Chrome tried to connect to iot.amset.in this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be iot.amset.in, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit iot.amset.in right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**CNAME**

Name :-  iot.amset.in
Value :-  thingsboard.cloud.

**Comment by ashaforost** [comment]
Hi @Vaibhav0216 

Have you registered the domain on your thingsboard.cloud account? See [Managing domain on ThingsBoard Cloud](https://thingsboard.io/products/paas/domains/#domain-registration)

**Comment by Vaibhav0216** [comment]
Yes, it's done. Thank You.
