### ISSUE TITLE
How does another backend application communicate with Thingsboard without providing the jwt token

### ISSUE THREAD

**Issue by peterabcd1** [thingsboard/thingsboard#11384]
I use Docker to setup thingsboard following https://thingsboard.io/docs/user-guide/install/docker/
I have successfully create a Docker container for it.

I also have another Backend Application(let’s call it backend A) and I want it to communicate with Thingsboard container,
I plan to host both of them in a VM, and only configure traffic rule such that only backend A can communicate with the hosted Thingsboard. Only backend A is accessible to the public

This is how the architecture look like
![thingsboard](https://github.com/user-attachments/assets/05383724-a2f5-4146-adcc-4734e3fdcb3f)

But it seems like there is no configuration in Thingsboard , which can disable/bypass all the authentication logic.
https://thingsboard.io/docs/user-guide/install/config/
Also there is no API key in Thingsboard.

That leaves me only one option, which is to 
1. configurate JWT_TOKEN_EXPIRATION_TIME to a big number
2. Fetch the token by sending request to /api/auth/login with thingsboard login credential to get the access token
3. Use it in every request from my backend to Thingsboard.

Just wondering if there is any workaround to simply disable Thingsboard Authentication, so that backend A can directly send Restful api requests to Thingsboard without providing the access token?

**Comment by SuminDenys** [comment]
Hi @andyabcd1,

Thank you for your report! 

For now, there’s no possibility of disabling Thingsboard Authentication and directly sending REST API requests to Thingsboard without providing the access token.

I have already added this feature request to our backlog, PROD-4162. However, I am unable to provide you with an exact timeframe for implementing the proposed improvement. Our development team is currently reviewing the suggestion about its necessity and feasibility for future versions of ThingsBoard.

We encourage you to stay updated on the latest news and release notes regarding ThingsBoard to remain informed about the possibility of including the proposed improvement in upcoming releases.

I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.

**Comment by mykhailokornieiev** [comment]
Hi. I'm glad to inform you that, starting with v4.3, the API Keys functionality was implemented:
[Hi. I'm glad to inform you that starting with v4.3](https://thingsboard.io/docs/pe/user-guide/security/api-keys/)
