### ISSUE TITLE
Edge disconnects from cloud after running for a period of time

### ISSUE THREAD

**Issue by bcblr1993** [thingsboard/thingsboard#11396]
**Describe the bug**
After running for a certain period, the edge device is displayed as disconnected (status: false) on the cloud. However, the edge device continues to upload telemetry data to the cloud without any issues. This inconsistency causes confusion regarding the actual connection status of the edge device.

**Your Server Environment**
  * Deployment: standalone
  * Deployment type: docker-compose
  * ThingsBoard Version: 3.4.3
  * ThingsBoard Edge Version: 3.4.3
  * Community or Professional Edition: Community Edition
  * OS Name and Version: CentOS (using Docker)

**Your Client Environment**
**Edge Device:**
* Type: Raspberry Pi or similar single-board computer
* OS Name and Version: [Specify the OS version if applicable, e.g., Raspbian, Ubuntu, etc.]
* ThingsBoard Edge Version: 3.4.3

## To Reproduce
The issue frequently occurs in our production environment, where we are using a 4G module for network connectivity. In this environment, after the edge device runs for several hours, the cloud dashboard often shows the edge device as disconnected (status: false), even though telemetry data continues to be transmitted to the cloud.

However, when testing in a local environment using a wired Ethernet connection, the issue is difficult to reproduce. The edge device remains connected to the cloud without showing the disconnected status, even after running for extended periods.

**Production Environment:**
- Network: 4G module
- Frequency of Issue: Frequently occurs after several hours of operation

**Testing Environment:**
- Network: Wired Ethernet connection
- Frequency of Issue: Rarely or never occurs

This suggests that the issue may be related to the specific characteristics of the 4G network, such as higher latency, network instability, or intermittent connectivity, which are not present in the more stable wired Ethernet environment.

## Screenshots

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/ce150f3d-22b2-4e0a-8955-0716e71bff23">

<img width="1837" alt="image" src="https://github.com/user-attachments/assets/12b21808-0d79-414a-9e5e-533c8654af96">
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/c2ee94b6-741e-4fe3-9dcc-16dd859201dc">

**Comment by ashaforost** [comment]
Hi @bcblr1993 

Please address your Edge-related issues to the [Edge repository](https://github.com/thingsboard/thingsboard-edge/issues)

This way, Edge developers will see your issue and may be able to help.

I'm closing the current issue as unrelated to thingsboard.
