### ISSUE TITLE
[FEATURE] Public/private dashboard indicator

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11395]
**Is your feature request related to a problem? Please describe.**

Production ready dashboard could be used both for authorized users and for demonstration (public access), thus some options/actions should be hidden in the latter case. It would be useful to have some indicator telling widget developers if dashboard is opened in public mode.

**Describe the solution you'd like**

```
widgetContext.isDashboardPublic
// or
widgetContext.$scope.isDashboardPublic
```

**Describe alternatives you've considered**

Manually check on `publicId` in URL
```
window.location.href.includes('publicId')
```

**Comment by SuminDenys** [comment]
Hi @devaskim,

Thank you for your report! This is a valid improvement that I’ve already added to our backlog PROD-4155. I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.

**Comment by devaskim** [comment]
@SuminDenys Please, think about adding some trigger to post comment here once the status of backlog ticket is changed, at least, once it will be resolved.

**Comment by SuminDenys** [comment]
Hi @devaskim,

Our team will think about this type of notification.
