### ISSUE TITLE
How can my users log in to my custom white-labeled platform?

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11398]
**Description** 

I have created new white labeled platform using thingsboard cloud. 

How can my users login through below login page.

![image](https://github.com/user-attachments/assets/adcf0160-a30c-4b26-ba88-e790212be233)

**Comment by ssakharova** [comment]
Hello @Vaibhav0216,

Your users can use their credentials. Once they enter their username and password, they will be able to access the platform as usual.
