### ISSUE TITLE
Thingsboard POM update for Kafka

### ISSUE THREAD

**Issue by ssmaurya** [thingsboard/thingsboard#114]
Using 0.9.0.0 version in pom gives build error as
[ERROR] Failed to execute goal on project extension-kafka: Could not resolve dependencies for project org.thingsboard.extensions:extension-kafka:jar:1.2.3-SNAPSHOT: Could not transfer artifact org.apache.kafka:kafka-clients:jar:0.9.0.0 from/to central (http://repo1.maven.org/maven2/): TransferFailedException: ClientProtocolException: The server failed to respond with a valid HTTP response -> [Help 1]

Changing the version to 0.10.2.0 fixed the issue for me.

**Comment by ashvayka** [comment]
@ssmaurya Please feel free to submit PR

**Comment by ssmaurya** [comment]
Closing the issue as it is not reproducible now and I could build using 0.9.0.0
