### ISSUE TITLE
Thingsboard container failed startup - pg_ctl: PID file "/data/db/postmaster.pid" does not exist

### ISSUE THREAD

**Issue by jianyepa** [thingsboard/thingsboard#11409]
Host system has a kernel update and docker daemon was restarted.
Thingsboard container failed to start up due to error `pg_ctl: PID file "/data/db/postmaster.pid" does not exist`

image: "thingsboard/tb-postgres:3.3.4"

**Comment by mykhailokornieiev** [comment]
Hi. Please provide an output of the next command:
`ls -lah ~/.mytb*`
Then, please attach docker-compose.yml file.
Also, you can get familiar with following ticket: https://github.com/thingsboard/thingsboard/issues/3347

**Comment by jianyepa** [comment]
I apologize for my own mistake.
The error was due to insufficient disk space in my host.
I have clean up the host, and postmaster.pid is created
