### ISSUE TITLE
lastActiveTime is getting updated without any input message

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#11407]
I have using thingsboard PE version 3.6.7

The lastActiveTime of few devices is getting updated automatically every 5 mins. 
![image](https://github.com/user-attachments/assets/65008dc4-bf1c-4337-8ef6-c8ee8c1d5d09)

The device is not sending any data either telemetry, attributes or RPC, still the lastactivetime is getting updated. 
I tried to look into debug log messages in rule chain and did not find any relevant message, that must be updating this data. 

Please help with a solution / pointer on how to resolve,t his issue.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
