### ISSUE TITLE
Create own Solution Templates

### ISSUE THREAD

**Issue by rpcai** [thingsboard/thingsboard#11416]
**Component**
 * Generic

**Description**
We would like to develop our own solution templates for customers, and allow them to easily deploy them - i.e in exactly the same manner as the Thingsboard provided solution templates. Is this possible? 

**Environment**
 * ThingsBoard: 3.70 PE

**Comment by mykhailokornieiev** [comment]
Hi
You can use Versioning to make templates (develop a use case and store the configuration in Git). Once required, you can deploy that version. Later on, we plan to add custom template development + Marketplace to sell those software elements.
[Version Control - Exportable Entities and Settings](https://thingsboard.io/docs/user-guide/version-control/#exportable-entities-and-settings)
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by rpcai** [comment]
Thank you for the response.
Using git integration was my fallback position for this fetature - However it's substantially less elegant. 

I assume a script of some description already exists for the provided solution templates - exposing this, rather than keeping it rolled up in PE source would be a compelling feature for professional users.
