### ISSUE TITLE
Empty response when requesting from /api/entitiesQuery/find when using Cassandra

### ISSUE THREAD

**Issue by kitaniman** [thingsboard/thingsboard#11410]
**Describe the bug**
Empty response when requesting from /api/entitiesQuery/find with a specific request body and using Cassandra even though there is new data. 

**Your Server Environment**
* Own setup
* Deployment: monolith 
* Deployment type: deb
* PostgreSQL + Cassandra
* ThingsBoard Version 3.7.0
* Community Edition
* OS: Ubuntu 22.04

**Your Client Environment**
* OS: WIndows 11
* Browser: Chrome 127.0.6533.100 (Official Build) (64-bit)

**Your Device**

* Connectivity
  * MQTT
  * HTTP

**To Reproduce**
Send a POST request to the following path '/api/entitiesQuery/find' with the following request body:
```json
{
    "entityFilter": {
        "type": "singleEntity",
        "singleEntity": {
            "entityType": "DEVICE",
            "id": "<DEVICE_ID>"
        }
    },
    "pageLink": {
        "pageSize": 1
    },
    "latestValues": [
        {
            "type": "TIME_SERIES",
            "key": "temperature"
        }
    ]
}
```
The result will be:
```json
{
    "data": [
        {
            "entityId": {
                "entityType": "DEVICE",
                "id": "<DEVICE_ID>"
            },
            "latest": {
                "TIME_SERIES": {
                    "temperature": {
                        "ts": 0,
                        "value": ""
                    }
                }
            },
            "timeseries": {},
            "aggLatest": {}
        }
    ],
    "totalPages": 1,
    "totalElements": 1,
    "hasNext": false
}
```
More specifically:
```json
"temperature": {
    "ts": 0,
    "value": ""
}
```
**Expected behavior**
```json
"temperature": {
    "ts": 1723528586,
    "value": 23
}
```
**Additional Context**
* I have tried to do the same thing with a duplicate server but that uses PostgreSQL with no Cassandra and the issue did not appear.
* I have Upgraded to 3.7.0 recently.
* This issue results in an unusual behavior with widgets as they do not get the latest data from the WebSocket the first time but they get updated once the sensor sends new data. This happens each time the page is refreshed.

**Screenshots**
![image](https://github.com/user-attachments/assets/66b423d8-d5b8-4b8f-914a-152899f38dc2)

https://github.com/user-attachments/assets/4ca622f8-db1c-46e4-b8ce-59e457bdb330

**Comment by kitaniman** [comment]
I have avoided this issue temporarily by moving the latest telemetry table to PostgreSQL while keeping historical data in Cassandra using the following environment variables:

export DATABASE_TS_TYPE=cassandra
export DATABASE_TS_LATEST_TYPE=sql

**Comment by myroslav-tb** [comment]
Hi @kitaniman, by thingsboard design it is correctly to set the DATABASE_TS_LATEST_TYPE=sql. The cassandra option was left as a backward compatibility with older versions of Thingsboard that can be installed with only cassandra database.
