### ISSUE TITLE
Scheduled Reporting with Entities 

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11411]
* UI

**Description**
I have a dashboard with multiple states. One of witch is reports where it shows graphs with details of a sensor. These graphs use entity and use an entity- alias that is not resolved as multiple entity so I can choose which device data I can have on the graphs.
![image](https://github.com/user-attachments/assets/c977e8d9-1793-417a-b17e-103a0f1a361d)

Selected a device
![image](https://github.com/user-attachments/assets/b1dc03ae-1dfe-4fe4-99b5-080eb68c5a19)

I want to have automatic reports of the reports state but when i select the state and set the entity to the device i want to get reports on it dose not work and only give me the reports state with the default entity device.

Image of the report i got with the wrong device.
![image](https://github.com/user-attachments/assets/217a4a63-2eb1-4f69-ae77-a60597ce0fe9)

 * ThingsBoard: PE

**Comment by SuminDenys** [comment]
Hi @xTwigx,

I am not sure that I understand everything correctly, so could you please add additional information such as:

1. Steps to reproduce
2. ThingsBoard version
3. Expected behavior
4. Current behavior
5. Your dashboard and state settings
6. Report settings
