### ISSUE TITLE
[Feature Request] Dashboards Display timewindow add interval datetime

### ISSUE THREAD

**Issue by HuaPing2017** [thingsboard/thingsboard#11415]
When designing chart data display, we need to query the time interval from last month to now, because we want to compare the status of two months with some data. Currently thingsboard does not have this option, could you please help add an item? Thank you very much

![72E0D2D5-B250-466e-8535-005B039C59CB](https://github.com/user-attachments/assets/292e0411-260b-4959-b540-bcec70d8c278)

**Comment by devaskim** [comment]
`Last` option in Realtime/History section provides `30 days` range

**Comment by mykhailokornieiev** [comment]
Hi @HuaPing2017,
We will re-design timewindow in future releases, so it must be possible to select both "previous" and "current" months simultaneously.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
As for now, as workaround you can use two widgets, with interval - "previous month" for the first one, and interval - "current month so far" for the second one.
