### ISSUE TITLE
How to Use Websocket API To subscription Device CRUD?

### ISSUE THREAD

**Issue by MohnSnow** [thingsboard/thingsboard#11429]
doc : https://thingsboard.io/docs/user-guide/telemetry/
refer: https://github.com/thingsboard/thingsboard/blob/release-3.6/application/src/main/java/org/thingsboard/server/service/ws/WsCommandsWrapper.java

------

this is not supported?

**Comment by mykhailokornieiev** [comment]
Hi. You are correct, this is not supported by design of Thingsboard.
