### ISSUE TITLE
Table widget for Devices where multiple values are in JSON format

### ISSUE THREAD

**Issue by haymanezzeldin** [thingsboard/thingsboard#11438]
**Component**
 * UI

**Description**
I have a device connected that generates multiple Telemetry Keys, some of them have JSON Values, here is an example of the keys/values  generated:

- Batch = 
```json
{
  "WaherID": 1,
  "ItemID": 1724053219131,
  "TimeStamp": 1724053366000,
  "Prog": 15,
  "Category": 16,
  "Weight": 40.2,
  "Customer": 937,
  "employee_shift": 3
}
```
- Dosing = 
```json
{
  "WaherID": 1,
  "ItemID": 1724053219131,
  "TimeStamp": 1724053407000,
  "Article": 650306,
  "TargetValue": 60.3,
  "ActualValue": 60.48,
  "DosingTime": 0.192,
  "DoseFlags": 2,
  "Step_Compartment": 1
}
```
- temperature = `25`

I would like to create a table as follows:
| ItemID        | Prog | Category | Weight | Article | TargetValue | ActualValue | Temperature
|---------------|------|----------|--------|---------|-------------|-------------|-------------|
| 1724053219131 | 15   | 16       | 40.2   | 650306  | 60.3        | 60.48       |25       |

Where:
ItemID is the main ID between the keys, and the rest of the columns are retrieved based on this ID

When I try to add columns to the Table Widget, I only see keys, but I would like to select a specific item from the JSON Value.
Would appreciate it so much if you can show me how to do that please.

**Environment**

 * OS:  MS Windows 11 Enterprise 10.0.22631 Build 22631
 * ThingsBoard: v3.7.0
 * Browser: Firefox 129.0.1

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by haymanezzeldin** [comment]
Thank you so much @mykhailokornieiev, that's great.
However, it's showing only one record, how can I make it show the whole records for the last 30 days?
I tried setting the timewindow, but that didn't change anything!
![image](https://github.com/user-attachments/assets/4f621218-de5c-47cf-85f0-dd8a1e23ccc3)

Best regards

**Comment by mykhailokornieiev** [comment]
Entities table is designed for displaying latest values, not historical. For such purpose, you will need to replace it with Timeseries Table widget. 
![image](https://github.com/user-attachments/assets/4b3ffb83-d010-4285-ba36-358082df436e)

**Comment by haymanezzeldin** [comment]
Perfect, thank you so much @mykhailokornieiev
