### ISSUE TITLE
Showing multiple alarms from the same device

### ISSUE THREAD

**Issue by jvruta** [thingsboard/thingsboard#11434]
* Rule Engine
 
I would like to create a new alarm every time the alarm condition occurs, even if there are multiple alarm triggers from the same device.

When an alarm condition occurs, it generates an alarm. However, if this alarm is accepted and not canceled, a new alarm is not created when the same condition occurs again.

**Comment by mykhailokornieiev** [comment]
Hi. Such kind of functionality is not possible due to design of Thingsboard. A new alarm can be created only after clearing the previous one. That is why, in this case, another logic will not be implemented.
