### ISSUE TITLE
Is it possible to create additional white-labeled instances under an already white-labeled ThingsBoard account?

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11437]
I have successfully white-labeled my ThingsBoard account under the name "crystalvision," with a custom domain, logo, and additional CSS modifications. Now, I want to offer my customers the ability to white-label their own accounts under this already white-labeled "crystalvision" instance.

Is it possible to allow further white labeling within a white-labeled ThingsBoard account? If so, what is the recommended approach to achieve this?

**Comment by mykhailokornieiev** [comment]
Hi. Yes, you can make it by either changing White Labeling settings for the customer manually (Login As -> Customer User -> White Labeling) or making it with rest API call
https://{thingsboard.host}/swagger-ui/#/white-labeling-controller/saveWhiteLabelParams

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
