### ISSUE TITLE
I'm unable to develop a dashboard that provides the best SCADA representation.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11447]
I'm unable to develop a dashboard that provides the best SCADA representation. Could you provide guidance or solutions for creating a dashboard that effectively represents SCADA data?

I want to develop dashboard like :- 

![image](https://github.com/user-attachments/assets/2ec9b917-7c58-42bb-9969-99ec19439914)

How can I develop this type of dashboard.

**Comment by devdoob** [comment]
SCADA not yet supported in Thingsboard. But TB guys are working on it and most probably we will see this feature in next release (as per TB official linkedin page)

**Comment by devdoob** [comment]
https://www.linkedin.com/company/thingsboard/posts/

![image](https://github.com/user-attachments/assets/5962e322-273b-4c87-b360-07d09951b05f)
