### ISSUE TITLE
Exceeded rate limit for WS subscriptions per user

### ISSUE THREAD

**Issue by shayMZ** [thingsboard/thingsboard#11444]
Hi,

I'm encountering an intermittent error on some of our dashboards that states "Exceeded rate limit for WS subscriptions per user." We are using the ThingsBoard Cloud Startup plan.

This error doesn't occur consistently; sometimes, it appears only after refreshing the dashboard, even if it loads without issues initially.

Could you please guide me on how to debug this issue and identify the root cause?

Thank you.
Shay

**Comment by ezeroldan24** [comment]
Good morning @shayMZ ! Apparently it's a TB problem, I'm having the same problem today.

**Comment by mykhailokornieiev** [comment]
Hi
Strict WS rate limits were applied on thingsboard.cloud because the activity of one of the tenants led to some kind of DDoS ​​attack with WS requests. After eliminating the problem, the limits have become less strict, so the problem should not be reproduced at this time.
