### ISSUE TITLE
Route Map Problems in Visualization

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#11442]
Hello, 
i am implementing a Route Map - OpenStreet, with 70 sensors which are in the USA.

The problem i am facing is that there are sensors that are in the same location and I can not see them in the map, how can I do? There is no way to spiderfy them in a Timeseries Widget?

![image](https://github.com/user-attachments/assets/1ba5443e-9685-4afe-821f-5f13951bd412)

**Comment by ssakharova** [comment]
Hello @nicovon24,

Try to use the Google Map widget instead. This widget has Markers Clustering settings that can help you achieve your desired result.
![image](https://github.com/user-attachments/assets/184f2ebd-4aff-44ae-af97-c53714de92c8)

**Comment by ssakharova** [comment]
Closed due to inactivity.
