### ISSUE TITLE
CSS Resource type in Resources library

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#11452]
**Is your feature request related to a problem? Please describe.**

We already have our own css librarie following the company standards e want to use them as library resource.

![image](https://github.com/user-attachments/assets/609ca2a6-795b-4c96-8ed4-6bb518ee32a7)

**Describe the solution you'd like**
Add a new resource type "CSS" for uploading CSS files.

**Comment by dealnat** [comment]
Hi,

We have created a product ticket for your recent feature request. The ticket number is [PROD-4265].
Our team will review and consider implementing your request to improve our product.
This reference number will help us track the progress of your request and provide you with updates as needed.
Please refer to our release notes to find out more about new features and bug fixes: [ThingsBoard CE release notes](https://thingsboard.io/docs/reference/releases/)
If you have any further comments or require clarification, please contact us.

Best regards,
Oleksii Kuripko
