### ISSUE TITLE
 Issue with Telemetry Data Not Being Saved for Assets When Using a Switch in Root Rule Chain

### ISSUE THREAD

**Issue by janhajk** [thingsboard/thingsboard#11454]
**Component**
* Rule Engine

**Description**
I'm experiencing an issue with telemetry data not being saved for assets when using a switch in the root rule chain.

Details:

I am using ThingsBoard Cloud and have modified the root rule chain to include a switch just before the "Post Telemetry" and "Save Telemetry" nodes. The switch checks the device type using the following code:

`return (metadata.deviceType.substr(0,6) === 'FMC230') ? 'short' : 'regular';`

Based on the result, the data is routed to one of two "Save Telemetry" nodes—one with a short TTL and another with a longer TTL. This setup works perfectly for devices, and the telemetry data is saved with the appropriate TTL.

However, when the data is intended to be saved on an asset, it fails to store the telemetry data if it passes through the switch. If I bypass the switch, the telemetry data for assets is saved without any issues. This issue is specific to assets and does not affect devices.

**Environment**
* ThingsBoard: latest
* Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi. Switch rule node not responsible for device -> asset originator changing. 
>Routes incoming message to one or multiple output connections. Node executes configured [TBEL](https://>thingsboard.io/docs/user-guide/tbel/)(recommended) or JavaScript function that returns array of strings (connection names).https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#switch-node

**Comment by mykhailokornieiev** [comment]
For such purpose, you will need to use Change Originator rule node
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator

**Comment by janhajk** [comment]
I don't want to change the originator. I just want to switch between deviceType resp. assetType. I can read metadata.deviceType. But when I try to read metadata.assetType, I get an error stating that metadata ist undefined.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
