### ISSUE TITLE
Widget library version control feature

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#11451]
**Is your feature request related to a problem? Please describe.**
Why there isin't a version control inside Widgets library ?

**Describe the solution you'd like**
Have the same "Versions" button from Dashboards and Rule Chains available inside Widgets library.

![image](https://github.com/user-attachments/assets/4d4dfb3f-8cbe-4687-b749-366af5285008)

**Comment by ssakharova** [comment]
Hello @lstarke,

The Version Control feature is available for the Widget Library. This feature can be used for Widgets and Widgets Bundles.
![image](https://github.com/user-attachments/assets/3cf038f2-7639-40a1-951c-2bd533199536)
![image](https://github.com/user-attachments/assets/933066c1-6bbb-41a2-a12a-b63508109f54)
