### ISSUE TITLE
Concatenate values from different keys

### ISSUE THREAD

**Issue by haymanezzeldin** [thingsboard/thingsboard#11455]
**Component**

 * UI

**Description**
I have a device connected that generates multiple Telemetry Keys, some of them have JSON Values, here is an example of the keys/values generated:
- Batch =
```json
{
  "WaherID": 1,
  "ItemID": 1724053219131,
  "TimeStamp": 1724053366000,
  "Prog": 12,
  "Category": 16,
  "Weight": 40.2,
  "Customer": 937,
  "employee_shift": 3
}
```

- Dosing =
```json
{
  "WaherID": 1,
  "ItemID": 1724053219131,
  "TimeStamp": 1724053407000,
  "Article": 16,
  "TargetValue": 60.3,
  "ActualValue": 60.48,
  "DosingTime": 0.192,
  "DoseFlags": 2,
  "Step_Compartment": 1
}
```
I have created a Timeseries Table, but I would like to have a column that concatenates values from the 2 different keys; for example:
| Column                    |
|---------------------------|
| Prog: 12, Article: 16 |
![image](https://github.com/user-attachments/assets/ac7c72d1-4119-4e3b-bff1-7bf00cef2046)

How can this be done?
Your assistance is so much appreciated.

**Environment**

 * OS:  MS Windows 11 Enterprise 10.0.22631 Build 22631
 * ThingsBoard: v3.7.0
 * Browser: Firefox 129.0.1

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. Please describe your request in as much detail as possible. 
If you want to access Prog data for 8:45:17 from Article datakey by 8:46:30, then there is no such a possibility by design of Thingsboard.

**Comment by haymanezzeldin** [comment]
Hello @mykhailokornieiev,
If you look at the Screenshot I attached, what I would like to achieve is to concatenate the latest value from Batch.Prog with the latest value from Dosing.Article to be "Prog: 12, Article: 16"

Would that make sense?

**Comment by mykhailokornieiev** [comment]
This is impossible to implement with dashboards using standard Thingboard functionality. I'd recommend you to use Rule Chains, so in this case it will be possible to fetch latest Batch.Prog and Dosing.Article values using **Originator Telemetry** rule node and then concatenate it in **Transformation Script** rule node.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-telemetry
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node
Then, you will be able to save it as new timeseries key with **Save Timeseries** rule node and display it on the dashboard as a separate datasource.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-timeseries-node

**Comment by haymanezzeldin** [comment]
Thank you so much @mykhailokornieiev
