### ISSUE TITLE
Issue with Undefined self.ctx.datasources in Custom Control Widgets

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11478]
**Description:**

I'm working on designing a custom control widget for ThingsBoard, and I’m trying to retrieve the latest attribute values similar to how it's done in the attribute card widget. In the onInit function of my custom widget, I use the following code to access self.ctx.datasources:
```
self.onInit = function() {
    
    self.ctx.datasourceTitleCells = [];
    self.ctx.valueCells = [];
    self.ctx.labelCells = [];
    
    const temp  = self.ctx.datasources;
    console.log("temp", temp);
}
   
  ```
This code works correctly in the latest value widget, and I can see the temp value in the console. However, when I use the same code in my custom control widget, temp is undefined.

**Comment by devaskim** [comment]
Perhaps you didn't set any data source in widget/widget-editor configuration.

**Comment by Vaibhav0216** [comment]
How can I Data Source there is no add data source button in the control widget

**Comment by devaskim** [comment]
So why are you using `self.ctx.datasources` if there is no data sources?

**Comment by devaskim** [comment]
> How can I Data Source there is no add data source button in the control widget

Guess, I finally understand what I asked. Add this to JS code:

```
self.typeParameters = function() {
    return {
        dataKeysOptional: false,
        datasourcesOptional: false,
        hideDataSettings: false
    };
}
```

**Comment by Vaibhav0216** [comment]
I am creating custom widget so I clicked on create new widget -> control widget . In this widget I go to edit mode -> data , to check the data source there is know any add datasoure button like in latest value widget. But I want to control and show the the latest value also hence I chose the control widget. I don't know how to done this please suggest me how to do this.

**Comment by Vaibhav0216** [comment]
Hi @devaskim,

I hope you're doing well. I've been trying to work on this issue for a while now, but I'm still facing challenges. If you have the time, I would really appreciate any suggestions or guidance you could offer.

Thank you in advance for your help!

**Comment by devaskim** [comment]
@Vaibhav0216 Export your widget and attach here 

![Скриншот 25-08-2024 132140](https://github.com/user-attachments/assets/3341fb77-e673-4cbd-9a6b-9f452bef2ee5)

**Comment by Vaibhav0216** [comment]
Ok 👍

**Comment by Vaibhav0216** [comment]
Hi @devaskim, due to an error, the widget cannot be saved. I am sharing the code of two different widgets that I want to combine. Please help me with this.

1)  Custom control widget json file  : [tesing_control_widget.json](https://github.com/user-attachments/files/16739544/tesing_control_widget.json)

2) Attribute card ( latest value widget ) : [attributes_card.json](https://github.com/user-attachments/files/16739549/attributes_card.json)

**Comment by devaskim** [comment]
@Vaibhav0216 Try again (comment part of code with error)

**Comment by Vaibhav0216** [comment]
ok I will try

**Comment by devaskim** [comment]
What action should be performed by clicking on ? (send RPC command, attribute update or something else)
1. R, Y, B
2. Dry Run / Overload
3. Manual / Auto
4. Stop / Start

**Comment by Vaibhav0216** [comment]
Hi @devaskim , 

1) widget link : - [pump_demo_2.json](https://github.com/user-attachments/files/16739650/pump_demo_2.json)

**Comment by Vaibhav0216** [comment]
Hi @devaskim , 

1) R,Y,B  
2) Dry Run 
3) Overload 

this attribute value are comes from the sensors we are just showing there latest values this are boolean attributes. 

1) manual 
2) auto 

when we click in check box manual system is on in that case only we  start and stop the pump manually else in auto case this stop and start buttons are inactive. system handle it automatically.

**Comment by devaskim** [comment]
https://github.com/user-attachments/assets/b443d158-185c-4000-a090-5e36eba7e5d9

**Comment by devaskim** [comment]
[a_pump_demo.json](https://github.com/user-attachments/files/16739898/a_pump_demo.json)

**Comment by Vaibhav0216** [comment]
Hi @devaskim,

I would like to send an RPC request when the start button is clicked to initiate the pump, and another RPC request when the stop button is clicked to stop the pump. Could you please guide me on how to send these RPC requests using the widgets you provided?

**Comment by devaskim** [comment]
>  Could you please guide me on how to send these RPC requests using the widgets you provided?

Hi @Vaibhav0216 
Look at [this official example](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#rpc-control-widget)

**Comment by Vaibhav0216** [comment]
Hi @devaskim ,
But in this documentation not mention we can combine latest value and rpc request functionality.

**Comment by devaskim** [comment]
TB relies only on widget type, in other words it doesn't check your widget's code on what API you use. So you can just copy RPC code from example above to the widget I provided.

In general and in my opinion, the `latest` widget type is the most flexible one to customizing its behaviour.

**Comment by Vaibhav0216** [comment]
Ok I will try it.

**Comment by devaskim** [comment]
> RPC code not work in the latest widget.

It is not true. 
Instead mixing widgets doesn't work, but I recommended another way - using RPC API directly, look again at link I have provided. Especially on this
```
self.ctx.controlApi.sendOneWayCommand(rpcMethod, rpcParams, timeout);
```
