### ISSUE TITLE
Disable Email Notification for Specific User

### ISSUE THREAD

**Issue by WillieSpence** [thingsboard/thingsboard#11477]
**Component**
 * UI
 * Rule Engine
 * Generic

**Description**
I'm using the Alarm Rules under Device Profiles to monitor my iOT devices and raise/clear alarms under certain conditions and send notifications via email, web and mobile. This works perfectly well, however, I have some users that would like to disable the email notifications. So I'm looking for a way to disable email notifications for certain users while still using the Alarm Rules in Device Profile, is there a way to achieve this?

**Environment**
ThingsBoard Cloud

**Comment by mykhailokornieiev** [comment]
Hi. You can list necessary users as Recipients in the Notification Center
https://thingsboard.io/docs/user-guide/notifications/#recipients

**Comment by WillieSpence** [comment]
Hi @mykhailokornieiev , Appreciate the response, but could you elaborate? Are you saying that for the user(s) that want emails to be disabled I need to add them as recipients in the notification center, but how do I then disable the email notifications for those users? I have many users that are receiving notifications, but its only a select few users that want email notification to be disabled (they still want the app and web notifications). So I need to only disable the email notification for specific users.

Appreciate if you could just elaborate some more here?

**Comment by Vaibhav0216** [comment]
Hi @mykhailokornieiev,

I hope you're doing well. I've been working on the issue mentioned in GitHub (#11478) and have tried various solutions, but I'm still stuck. When you have a moment, could you please take a look? Your insights would be greatly appreciated.

Thank you so much for your help!

**Comment by mykhailokornieiev** [comment]
@WillieSpence 
You will need to list all users who are **allowed** to receive notifications.
Or, any user can disable it manually in Account -> Notifications by themselves. For this, user must have Profile -> Write permissions.
![image](https://github.com/user-attachments/assets/5e94a999-c40e-4529-8e6e-878cfd11851a)
https://thingsboard.io/docs/pe/user-guide/rbac/

**Comment by mykhailokornieiev** [comment]
@Vaibhav0216 
I have no expertise in custom development. Also, please don't spam in tickets that solve entirely different problems of other community members

**Comment by Vaibhav0216** [comment]
Hi @mykhailokornieiev,

Thanks for your help. However, I'm not receiving any support from ThingsBoard, so I'm reaching out to you. Apologies for any inconvenience.

**Comment by mykhailokornieiev** [comment]
@Vaibhav0216 
GitHub tickets are primarily supported by the community. If one of the Thingsboard employees has the opportunity to help, then they can respond, but this is done only as part of community support, that is, on their own initiative. If you need ongoing custom development support from Thingsboard, you'd better use [Contuct Us form](https://thingsboard.io/docs/contact-us/) to get consulted on the cost and terms of custom development support

**Comment by WillieSpence** [comment]
@mykhailokornieiev , appreciate your assistance on the email notifications. Wasn't aware that users can manage this themselves.
