### ISSUE TITLE
Grouping Telemetry coming from a single device

### ISSUE THREAD

**Issue by karldopplinger** [thingsboard/thingsboard#11487]
**Telemetry Grouping for Widgets**

 UI

**Description**
I have a single Device out in the real world, connected to multiple smaller devices (all of the same type), that one 'main' device sends the telemetry data for all of the other ones. How can I group that within an entity table?

I would like to have a single Entity Table with all of the Devices inside of it. (All of the Devices have a unique key).

**Comment by karldopplinger** [comment]
> Hi. For such purpose you will need to either parse it in rule chain at first, so all data will be recorded for each device separately in Thingsboard, or you can consider usage of MQTT Gateway API, so you will be able to get data for all devices with one active device connection. Only after it you will be able to show this data as separate devices in Entities Table https://thingsboard.io/docs/pe/reference/gateway-mqtt-api/

Is there a tutorial or something for parsing it. So that it is recorded for each device seperately?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
