### ISSUE TITLE
How can I remove the Administator REST API authentication?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1148]
Before I use the REST API, I must post "http://hostIP:8080/api/auth/login" to get access token.

I want to know,  how can I do to skip this step? I want to use the REST API directly.
Looking forward to your answer.

**Comment by vparomskiy** [comment]
Because of security reasons, it is not possible to disable authentication.
What is the problem with getting JWT token?

**Comment by qwyinxiang** [comment]
Thank you for you answer, There is no problem with getting JWT token.
I want to use a third party API manager to manager the thingsboard REST API, but the third party API manager does not support OAuth Authorization, it only supports the Basic/Digest Authorization .
I think about other ways. thank you very much.
