### ISSUE TITLE
Is it possible to pass the wanted time window to dashboards by query parameter?

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#11492]
**Component**

 * UI
 * Generic

**Description**
Since passing the state to the dashboard via base64 encoded json is possible, i would like to know if there is a way to pass the wanted time window to the dashboard somehow?

**Environment**

 * OS:  SLES 15 + Docker Swarm
 * ThingsBoard: 3.7

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. As mentioned in previous ticket https://github.com/thingsboard/thingsboard/issues/11342, you can try to create either custom widget, or custom action. 
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions

**Comment by apachler** [comment]
I have found a way to get it through 
`var stateParams = self.ctx.stateController.getStateParams();`
