### ISSUE TITLE
Filter for `enityType` and `entityProfile` in `aggregate latest` analytics node

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#11493]
**Component**

 * Rule Engine

**Description**

Assume the following setup:

- Asset (Profile: `Project`)
- Asset (Profile: `Household`)
- Device (Profile: `Sensor`)

Each Project can contain (using a relation) multiple Devices and multiple Households.

Assume we want to use a basic `aggregate latest` node to aggregate some telemetry from sensor for all related **devices** for any given **Project**.

Currently, using the `aggregate latest` node will also consider the Households when performing the aggregations, which produces wrong numbers.

**Workarounds considered:**

I can filter inside the `aggregate latest` node for attributes. It is possible to filter for certain attributes which "should" only be present on the desired devices. However, this is unintuitive and error prone. I'm looking for a way to filter in the `aggregate latest` node for `Entity Type = Device` and `Entity Profile = Sensor`.

**Environment**

 * OS:  MacOS 14
 * ThingsBoard: 3.6.3 PE
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. There is no standard functionality that can filter entities for aggregation by entityType or entity profile. Aggregate Latest rule node will aggregate values for **all** entities by specified Relation Type and Direction. 
However, you can assign some **custom** Relation Type between necessary entities.
![image](https://github.com/user-attachments/assets/2828005e-1bba-4691-8e0c-e35c7d59e448)
![image](https://github.com/user-attachments/assets/008731a8-a4ea-4fcb-8063-5f1b86f7ddc3)

**Comment by dmohns** [comment]
> Hi. There is no standard functionality that can filter entities for aggregation by entityType or entity profile. Aggregate Latest rule node will aggregate values for **all** entities by specified Relation Type and Direction. However, you can assign some **custom** Relation Type between necessary entities. 

Thanks a lot for the reply. This is interesting! Unfortunately, I have a couple of other dependencies built on the `Contains` relation (I.e. we are using an entity search query in an external service), so changing this would require quite some refactoring. None-the-less I will look into it.

I'm curious if this feature could be added to the `aggregate latest` node as the `aggregate latest (deprecated)` node seemed to have support for it, see:

<img width="643" alt="image" src="https://github.com/user-attachments/assets/80040323-21f7-4fb0-9624-8c8f7c9c3ebb">

**Comment by mykhailokornieiev** [comment]
There is no necessity to replace current relation, you can just one more between the same entities, as shown on my first screenshot. Asset and devices agg1/2 have two relations between them.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
