### ISSUE TITLE
Web prefix env for frontend UI visualization 

### ISSUE THREAD

**Issue by alexbarta** [thingsboard/thingsboard#115]
Hi,

Is it possible to have an env WEB_PREFIX to prepend dynamically to every web UI request ?

Example:
WEB_PREFIX="/service/thingsboard"
http://myurl:myport/service/thingsboard/ (this corresponds to / request)  http://myurl:myport/service/thingsboard/static/foobarbaz (this corresponds to /static/foobarbaz request )

Regards

**Comment by tolbkni** [comment]
@alexbarta You can setup nginx as a reverse proxy for thingsboard to achieve this purpose.

**Comment by alexbarta** [comment]
Thanks for the tip. I was just wondering if there was an out the box feature in thingsboard to achieve this.

**Comment by type0lang** [comment]
This would be so useful for mesosphere-like deployments!
