### ISSUE TITLE
Relation Additional Info (JSON) - Access via rule chain

### ISSUE THREAD

**Issue by rpcai** [thingsboard/thingsboard#11503]
**Component**
 * Rule Engine

**Description**
I have definined relations between devices:
![image](https://github.com/user-attachments/assets/a1c4fc31-b508-409f-8c0a-2c152846a20e)

The 'Edit Relation' dialog contains an 'additional info' field (JSON). Is it possible to access this relation data via rule chain? What is this fields intended purpose/use?
![image](https://github.com/user-attachments/assets/8ba0d27a-b944-4426-8ca5-e2210e7e34fb)

**Environment**
 * ThingsBoard: PE 3.70

**Comment by mykhailokornieiev** [comment]
Hi. The "additionalInfo" field for relations was created as a reserve for functionality that was not and most likely will not be implemented. That is why the only way to extract this information through the rule chain is only from the [Rest API Call node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node).
![image](https://github.com/user-attachments/assets/75032f04-b0c2-4c0a-bcf6-a0c2a4e06e4a)
![image](https://github.com/user-attachments/assets/00369fb0-899d-484c-87cd-5b258e856cd8)
http://localhost:8080/swagger-ui/#/entity-relation-controller/findByFrom

**Comment by rpcai** [comment]
Thank your for the clarification!
