### ISSUE TITLE
IoT device control using custom MQTT message format & custom MQTT topic name 

### ISSUE THREAD

**Issue by JanCools750** [thingsboard/thingsboard#11502]
I have an IoT device which I want to control using thingsboard. I can read the telemetry data fine. 
My IoT device has relays which I want to control using thingsboard MQTT. I know the exact message format I need to send to my IoT device as controlling the relays via a local mosquitto broker installation works fine. To listen for relay switch messages, my IoT device is subscribed to a topic blabla/+ (for example).
It then expects messages on blabla/relayID topic, with relayID being a number identifying the specific relay. I was trying to use the requestId to get there, so I came up with 2 options which did not work in the end.

1. Server-side RPC. Problem with the RPC Call Request block is that you need to use the method and params format, which is not the format which my IoT device expects. As far as I can see, there is no option to send a custom message format using the RPC call request command.
2. Shared attributes, if I change the shared attributes I use the Rule engine to change the body of the message and it arrives in the correct format however now I do not have any option to change the topic it is posted to. The only option I have for this is changing this is in the device profile transportation configuration, but the 4 relays use different topics e.g. blabla/12 & blabla/13 & blabla/14 & blabla/15.

A last option I was considering is using the protobuf option. Is this something that would work? Do you have any other suggestions to make this work? Thanks in advance!

**Comment by rpcai** [comment]
I have struggled with this as well! 

In my opinion, Thingsboard is soemwhat inflexible regarding its MQTT Telemetry/Attributes API  messaging implementation. It feels as thought it has been developed under the assumption that users will have control over the firmware/MQTT message format on the device end, to suit the Thingsboard API - when this is very seldom the case!

from what I have seen, the majority of devices like to pulbish/listen on a device-specific Topic - Thingsboard however use a generic topic for all devices on the same profile. 

it would be great if dynamic fields were supported for MQTT topics:
e.g v1/devices/me/attributes/[$Device-Name-Or-Atrribute-Value]
![image](https://github.com/user-attachments/assets/510ac9c7-ae64-4910-a93b-23f386417572)



Hopefully someone more learned than me can advise you!

**Comment by JanCools750** [comment]
Thanks for the comment, then I know I'm not alone!

From my understanding of the RPC, I can see from the RPC call reply block in the Rule engine it is possible to use a request ID and custom formatting. But the RPC call reply block is intended to reply on an RPC request from the client. 
I tried this, but always get the error that the serviceID is missing.
If I can somehow trigger a fake RPC request I could use this for triggering the reply which I can custom format (because this needs some serviceID, deviceID and requestID). This maybe could be a workaround but I did not succeed yet to get this working...

**Comment by sumin-denys** [comment]
Hi @JanCools750,

I believe that protobuf can solve the problem by using a specific message format for your device. However, the problem with particular topic ids will remain.

I would like to suggest ThingsBoard Integration as a possible solution to this problem. Integrations were developed to solve problems with specific payload formats. In addition, you can use the message payload to generate topics that meet your requirements.

Here, you can find the necessary information to create the correct integration:
- [Platform Integrations](https://thingsboard.io/docs/user-guide/integrations/)
- [MQTT Integration](https://thingsboard.io/docs/user-guide/integrations/mqtt/)

I hope you find this helpful information. If something is still unclear, please let me know.

**Comment by rpcai** [comment]
@JanCools750  - The MQTT platform integration only functions as a client, if I'm not mistaken? - I had explored this in the past, but gave up, as most end-devices/gateways expect to function as a client also, publihing telemetry to a broker.

**Comment by tonny1983** [comment]
As the document said that:

> he body of server-side RPC request consists of multiple fields:
-  method - mandatory, name of the method to distinct the RPC calls. For example, “getCurrentTime” or “getWeatherForecast”. The value of the parameter is a string.
-  params - mandatory, parameters used for processing of the request. The value is a JSON. Leave empty JSON “{}” if no parameters needed.
- timeout - optional, value of the processing timeout in milliseconds. The default value is 10000 (10 seconds). The minimum value is 5000 (5 seconds).
- expirationTime - optional, value of the epoch time (in milliseconds, UTC timezone). Overrides timeout if present.
- persistent - optional, see [persistent] vs [lightweight] RPC. The default value is “false”.
- retries - optional, defines how many times persistent RPC will be re-sent in case of failures on the network and/or device side.
- additionalInfo - optional, defines metadata for the persistent RPC that will be added to the [persistent RPC events].

In my opinion, it is better if I may add some other fields in the RPC body which is required by the device but thingsboard.
Therefore, the body may look like as follow:
```json
{
  // thingsboard fields
   "method": "method",
   "params": {},
  "timeout": 30000,
  // custom fields
  "a": "a",
  "b":"b",
  // ...
}
```
Most of json-object mappers (jackson and so on) will ignore not mapping fields and without any exceptions, so the additional fields should make bother thingsboard and device work correctly.

**Comment by sumin-denys** [comment]
Hi @tonny1983,

Thank you for your report! For now, there’s no possibility of sending the RPC Request with the custom fields.

I've added this request to our backlog, PROD-4657. Once the product team reviews this ticket, we’ll post an update on when this feature could be delivered if they decide to add it to the product. 

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)

I am closing this issue for now. If you have any further questions or require clarification, please let me know.
