### ISSUE TITLE
Thingsboard Cloud Inaccurately Reporting Device Connection Status

### ISSUE THREAD

**Issue by lfjm2022** [thingsboard/thingsboard#11513]
I have an alarm for device inactivity that sends an sms after 24 hours if a device disconnects from Thingsboard. Twice this month now on the 15th an today the 28th almost all of our devices have sent alarms with their last connection times showing that they have been disconnected for 24 hours. When I go and look at the data the devices show that they are inactive and the last activity timestamp is from 24 hours ago however there is no interruption in data up to the present time with more continuing to come in and all of the Thingsboard plan features are not at their limit. This causes confusion for our team and concern for our customers who believe that their systems are going down.

**Your Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome. Firefox
* Version: 129.0.2

**Smartphone (please complete the following information):**
* Device: Iphone 8
* Browser Safari, Google

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
  *Unclear

**Expected behavior**
I expect not to receive disconnection messages unless our devices are actually disconnected. It is a waste of our limited alarms and SMS and causes concern and doubt for our customers.

**Screenshots**
![Plan Usage](https://github.com/user-attachments/assets/0b2dc7d8-0008-4259-a4ec-59ce0ba5bb9b)
![System Active and Data Coming Through](https://github.com/user-attachments/assets/82808077-d86a-4afa-acb0-f49fe355e958)
![Device Marked as Inactive](https://github.com/user-attachments/assets/6e3280dd-9ce1-4992-b73e-9cf3389b335e)
**Additional context**

Please feel free to add any other context about the problem here.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AlexDoanTB** [comment]
@jin1ming please keep an order: 
- if you face issues with TB CE, you can submit tickets on GH;
- if you have a supported PE version, you can proceed with the Ticketing portal 
- if you face issues with TB Cloud, you have your success manager to contact. 
To be frank, your comment makes less sense.
