### ISSUE TITLE
Change the color for input text fields in a Update Multiple Attributes widget

### ISSUE THREAD

**Issue by JakeDaSnake80** [thingsboard/thingsboard#11519]
I need to change the color of all the input text fields (blue screenshot). I can change the color by entering a value directly into DevTools but unable to overwrite it in _Advanced Widget Style > Widget CSS_. The color for the mat-labels I can overwrite though.

What do I need to enter in the Widget CSS change to color for the "input#mat-input-...."?

![image](https://github.com/user-attachments/assets/66819457-1f65-4df4-9518-c8ff90dbc872)

![image](https://github.com/user-attachments/assets/c8068612-b3c3-4dd5-ab95-f6848e531a9f)

**Comment by Allwhy** [comment]
You can try 
`.mat-mdc-input-element {
    color: blue !important;
}`

The addition of !important often helps when trying to change the Widget CSS :)
