### ISSUE TITLE
Not able to assign device to more than one customer.

### ISSUE THREAD

**Issue by prakharnigam** [thingsboard/thingsboard#1152]
I am not able to assign device to more than one customer.
Previously in 1.x version I was able to assign device to many customer.

Please check. 
![test_1](https://user-images.githubusercontent.com/10355945/46996365-0a8b2680-d13a-11e8-8400-b4ee1481a3f4.JPG)

**Comment by mfalkvidd** [comment]
Could be a duplicate of https://github.com/thingsboard/thingsboard/issues/669 ?
