### ISSUE TITLE
Public Dashboard - Show Public Entities of Sub-Customers?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#11549]
**Component**

 * UI

**Description**
In a current project, the requirement is as follows:
A customer has a public dashboard in which their own devices are displayed (which are also public). Now, in the next step, the devices of a sub-customer of the customer should also be displayed. The entity aliases are set dynamically accordingly and display all devices from a specific profile. The devices of the sub-customer are also public.

![image](https://github.com/user-attachments/assets/77a45656-7176-4e05-9873-f8ac94f71949)

However, if you open the public dashboard, the devices of the sub-customer no longer appear.
What are we doing wrong here? Or is it technically not possible to do it this way?

If the latter is the case, what workarounds are there?

**Environment**

 * ThingsBoard Cloud

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hi,
It should not work the way your client wants.
All public entities must be under the same owner who makes them public.
A Public dashboard of a customer does not mean that a sub-customer has full access to it.
