### ISSUE TITLE
Force Full Screen 

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11553]
Hello I'm using thingsboard to have a single dashboard I can give to multiple customers and sub-customers. 

In this dashboard I have a side menu so to make the dashboard aesthetically and reduce navigation from customers,
Currently I create all the users, and force Full screen on each and everyone.
 
Is there a way I can make it force Full Screen to new created customers by default.
And this could might allow me to let the customer create there own customers.

 * OS:  Ubuntu
 * ThingsBoard: PE 3.7

**Comment by liotys** [comment]
Hello,
see the issue #8599 to achieve this goal.

**Comment by sumin-denys** [comment]
Hi @xTwigx,

The **_Rule Chain_** from issue #8599 will help you set the default Dashboard for any new user and, of course, force **Full-Screen** options. However, it will not allow you to let the customer create their customers.

This is a bug in our system, and our product team is already processing a product ticket PROD-1391. 
Currently, there is no timeframe for fixing this bug. We will inform you as soon as it is fixed. 

I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
