### ISSUE TITLE
ACTIVE_INSTANCES_CAPACITY_EXCEEDED and no instance-license.data to delete

### ISSUE THREAD

**Issue by PabloReyes** [thingsboard/thingsboard#11552]
**Component**
 * Generic

**Description**
I'm running Thingsboard 3.6.4 PE on AWS (EC2, Ubuntu), without Docker, as described [here](https://thingsboard.io/docs/user-guide/install/pe/ubuntu/). After having TB working for a few weeks, I had to apply some changes to the instance and I started getting the `ACTIVE_INSTANCES_CAPACITY_EXCEEDED` error.  I've searched everything in the documentation and github tickets and it seems pretty clear that the license is assigned to a different instance, one with a different ID. I found that the license is assigned to `XXXXX-e3a7`, while my current instance ID, according to `/usr/share/thingsboard/bin/.instance_id` is `XXXXX-aed4`. 

I've read that I should delete the instance from the Thinsboard License Portal, and then remove the `instance-license.data` file in `/usr/share/thingsboard/bin/` or whatever the `TB_LICENSE_INSTANCE_DATA_FILE` env variable says, but the env variable is not set and no matter how much I look I can't find any file like that. 

When I try to delete the instance from the License Portal, it says it may result in losing data. Am I risking anything here really? If I delete the instance from the License Portal and re run the TB service, maybe the license server will just assign the license to this new instance_id, with no data lost?

Thank you

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.6.4 PE

**Comment by ashaforost** [comment]
Hi @PabloReyes 

Please write to the [Contact Us form](https://thingsboard.io/docs/contact-us/) so we may help you with your license issues.
I'm closing this GitHub issue as it's not a community matter.
