### ISSUE TITLE
[Feature Request] Add a Dummy Node to Rule Chain Editor

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#11556]
**Is your feature request related to a problem? Please describe.**

This request is not about a functional feature, but a feature to greatly help rule chain organisation and collaboration between different engineers.

This feature requests is to suggest the addition of a Dummy Node (other common names could be `Nop Node` (no operation), `Empty Node`, `Null Node`). The Dummy Node "does nothing" it simply passes any message forward keeping all data and metadata intact. This node should be visually distinct (different colour) to make clear no processing is happening in this node.

**Describe the solution you'd like**

When designing rule chain it can sometimes be helpful to have access to an operator that just passes the message on. This is useful to logically group components of a rule chain.

Two common scenarios are the following:

- In a **branching scenario** it is common practise to have a "finish branching" node before processing continues. This makes it easy to visually grasp which part of a chain is (for example) message type specific and which parts are common to all messages
  ![image](https://github.com/user-attachments/assets/98e78c9b-4911-4b02-9762-c6f49410866b)
- Simplify organisation of logically connected groups by using a "Start" and "End" node. Consider the example below: Without and Start and End node it is tedious and error prone to refactor this logical group of a rule chain. A lot of connection have to be re-drawn if a node was added.
![image](https://github.com/user-attachments/assets/a74409c8-08f1-48f1-ba71-7beabd6369d9)

**Describe alternatives you've considered**

Currently, we can achieve the same by using a `script` node which an empty body. But it is not visually distinct and can lead to confusion.

**Additional context**

N/A

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @dmohns 

Thank you for your suggestion. We acknowledge the need for better organization and clarity in rule chain design and are working on improvements. While we won’t implement a dummy rule node, alternative elements will be provided to help achieve the same purpose. 
Please see our [Roadmap](https://thingsboard.io/docs/reference/roadmap/) for more upcoming improvements.
