### ISSUE TITLE
custom widget

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#1155]
Hello! 

i'm currently developing custom widget to switch between light states. 

subscription part works correctly and updates widget appropriately , but is there smarter way to send device telemetry value than to use rest call?

another problem is, that can i set widget to "full screen mode" automatically and also to make it prefer 16:9 size. i could make this in normal web page, but i cannot do it to widget.

thanks in advance, Samu.

**Comment by vparomskiy** [comment]
1. if you want to add telemetry value from UI - REST API is an only option.
if you want to load telemetry - you can use web sockets(subscription) or load it directly via REST API. 
Is that what you were looking for? 

2. Do you need to set widget OR dashboard in full-screen mode by default?

**Comment by quirosaur** [comment]
the primary need is to _post_ new changed device data to tb device. i made the widgets 'latest values'- type, so i can get the currently selected number easily through subscription API.
(maybe there's something wrong with my POST syntax, i'll double check.)

And yes, i need to set the _widget_ to full-screen. i know dashboard can be set to that from user's settings.
i would prefer to instantly get the same view as i would when i have clicked the "full-screen" button on widget's top right.

**Comment by quirosaur** [comment]
Hello! 

I checked the syntax of my post, and it should be correct. I get 400 from it, here's one of the syntaxes i tried it:

`$.post("http://<ip_here>:8080/api/v1/<device_accesscode_here>/telemetry",{
                selectedPreset:2
            });`

i also tried the longer version ($.ajax({....})); to no avail.
so that's a major problem for me. 

I can change the values with postman or swagger of thingsboard, but any time i try to use it with REST of html page (be it in widget or external page), nothing works. i always get 400


and on to the other problem: 

does thingsboard have api to control the widget's appearance, or do i have to dig manually the button 

`<button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" id="expand-button" ng-show="!vm.isEdit &amp;&amp; vm.enableWidgetFullscreen(widget)" aria-label="Exit fullscreen" aria-hidden="false" md-ink-ripple="false"><ng-md-icon size="20" icon="fullscreen_exit" options="{&quot;easing&quot;: &quot;circ-in-out&quot;, &quot;duration&quot;: 375, &quot;rotation&quot;: &quot;none&quot;}" class="ng-scope"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"><path d="M5 16h3v3h2v-5H5v2z"></path><path d="M8 8H5v2h5V5H8v3z"></path><path d="M14 19h2v-3h3v-2h-5v5z"></path><path d="M16 8V5h-2v5h5V8h-3z"></path></svg></ng-md-icon><div class="md-ripple-container"></div></button>`

from outside of widget to get it to fullscreen on default?


-Samu



ps. so just to be clear, i need to change telemetry value from inside of widget

**Comment by alexsmartens** [comment]
Hi @quirosaur,
I'm having a somewhat similar issue (#1743). Could you suggest how to load telemetry data in an alternative to REST API way?

**Comment by quirosaur** [comment]
Hi @alexmartens
The solutions that i think would be possible In your case are either using The RESTapi, automatically applying on Page initialization settings to schema or somehow creating appropriate entrys to data ase automatically.

I'm sorry but i fear i cannot help further, since i have moved to different platform with my smart lighting solutions and so I'm not aware of possible New solutions

**Comment by alexsmartens** [comment]
Cool, thank you!
What platform have you moved to?

I think modifying the Settings Schema on page initialization should do the thing. Would you mind posting a couple lines of code or a link to the resource showing how to do it? 
Or maybe you could write a brief explanation of this method and I will figure implementation details out

**Comment by quirosaur** [comment]
I currently don't have access to computer, but you can do it like this: create The fields to The widget's schema and inside onInit function, fetch The values you need. Then, save the values to the schema using the scope self.ctx.settings.yourvalue or something like that. I recommend reading the thingsboard documentation, since all is practically explained there.
