### ISSUE TITLE
[Feature Request] Snap to grid in Rule Chain editor

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#11555]
**Is your feature request related to a problem? Please describe.**

When designing slightly more complex Rule Chain visual consistency can greatly help other developers to understand the flow of a chain and foster collaboration. I.e. visually assigning conceptually connected nodes together etc..

**Describe the solution you'd like**

Currently, it is very tedious to align nodes vertically and horizontally. I found that this is mostly do it on the initial creation of the rule chain. However, later refactoring of the chain, for example adding a node in the middle becomes exponentially more effortsome.

It would be if there was a setting that makes nodes snap to the grid in Rule Chain editor. This would reduce the effort by a lot.

**Describe alternatives you've considered**

Manually aligning all nodes.

**Additional context**

N/A

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by ashaforost** [comment]
Hi @dmohns 

This is a valid improvement to the Rule Chain editor! We are working on this feature, but we do not have a release date set. Please follow [ThingsBoard Release Notes](https://thingsboard.io/docs/reference/releases/) to upgrade the instance when it is implemented.
