### ISSUE TITLE
Resolve state/widget title placeholders from nested state entities

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11562]
**Is your feature request related to a problem? Please describe.**
By specifying, for example, `${enitityLabel}` in the title of dashboard state or in widget title, I get the label of entity in the title (of course, if the entity is set in the dashboard state). There is no way to use such placeholders for entities which is set via `State entity parameter name`.

**Describe the solution you'd like**
E.g. I add entity to state with `State entity parameter name` is set to `machine`. So placeholder would be `${machine.enitityLabel` or `${machine:enitityLabel`

**Describe alternatives you've considered**
No alternatives.

**Comment by ssakharova** [comment]
Hello @devaskim,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement it in future versions of the ThingsBoard.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) for updates on future platform additions.
