### ISSUE TITLE
Make Dashboard timewindow "sticky"

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#1156]
I'd like to be able to change the default dashboard timewindow, and, ideally, make it sticky so that when i returned to the dash, it showed the same timewindow as before.

Is this currently possible?

**Comment by vparomskiy** [comment]
Sure. If you change dashboard time window in dashboard 'Edit' mode, and then press 'Save' - selected time window will be also saved. So you can choose any required time window (latest or historical).
