### ISSUE TITLE
Bar Chart Widget

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11575]
Hello Got a simple question I have a bar chart that gets a datasorce and witch is a delta sums it up per day to see the total difference that day.
![image](https://github.com/user-attachments/assets/a4c3cdd0-52dd-4dd7-bef8-a6b0d0e49e4a)

This is show in a bar graph containing all of the data for the month now i want the legend to display the total as well.

Basically i want it to look like the API Usage charts
![image](https://github.com/user-attachments/assets/6e25f1b8-5ea9-41b4-9c8e-c6fb9ac60283)

**Comment by ssakharova** [comment]
Hello @xTwigx,

It is impossible. However, you can try to achieve the desired outcome by developing a custom widget.
