### ISSUE TITLE
Question for Mail Template

### ISSUE THREAD

**Issue by Rotiot** [thingsboard/thingsboard#11577]
**Component**

 * Generic

**Description**
I want to add the name of the customer when sending automatic mail in the mail template.
We can request the OTP code that comes with the {{code}} variable like OTP code.
Here I want to request the customer name.
For example:
Hello {{customerName}}.
I want to make a change in this way, but I don't know what kind of variable to use. Can you help me with this.

**Environment**

* OS: Ubuntu 20.04.6 LTS
* ThingsBoard: v.3.6.4
* Browser: Chrome Version 128.0.6613.114 (Official Build) (arm64)

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hello, using the User name variable for the mail template is impossible for all templates. 
Variable ${userFullName} can be used from **User activated message**  and **User registered message** templates only.

**Comment by Rotiot** [comment]
so how can I get the username here. is there no solution?

**Comment by Rotiot** [comment]
which variable should I use for activation and registration
