### ISSUE TITLE
How to send data from TB to device using mqtt?

### ISSUE THREAD

**Issue by oroi1991** [thingsboard/thingsboard#1157]
Hi All,

I have completed to setup for running development environment for your supporting.
Now, i have a two questions.

Q1) If when a received temperature data from device is greater than 80 i want to send data for turn on fan from TB to device using mqtt. How can i do for it? Do i need to use RPC function?

Q2) I can add new rule node for any filtering about incoming data. 
(for example, msg.temperature > 80)
If i have a two devices on TB and then both device has a temperature.
How does new added node know which devices's temperature is?

Regards

**Comment by vparomskiy** [comment]
1. Yes, you need to use a filter script node with condition msg.temperature > 80 and 'RPC call request' to send a command to the device. You can use this tutorial as a reference - https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/
https://thingsboard.io/docs/user-guide/rpc/

2. Each message inside Rule Engine has 'originator' field. It defines who is an originator of the message.

**Comment by oroi1991** [comment]
> 1. Yes, you need to use a filter script node with condition msg.temperature > 80 and 'RPC call request' to send a command to the device. You can use this tutorial as a reference - https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/
>    https://thingsboard.io/docs/user-guide/rpc/
> 2. Each message inside Rule Engine has 'originator' field. It defines who is an originator of the message.

Thank you for reply,

You mean about Q2.
I have to check originator field via script?

**Comment by vparomskiy** [comment]
You do not need to do this. It is performed automatically be the Rule Engine.

**Comment by oroi1991** [comment]
Thank you for answer.

I completed to send data to device followed picture.
![image](https://user-images.githubusercontent.com/31301310/47250466-6c120480-d45c-11e8-9c8c-16ef2acd2370.png)

One more question related it.
The data is being sent to device every second when humidity is less than or greater than 40.
I want to send data only once when it is greater than or less than 40 like trigger event.

How do i use the rule chain?

Regard

**Comment by vparomskiy** [comment]
You can create an alarm for this case and send RPC command only when a new alarm is created/cleared. Alarm is new only if there is no uncleared alarm for the same device with the same type.
