### ISSUE TITLE
Creating a delay and checking conditions after the delay using the rule engine

### ISSUE THREAD

**Issue by gurverm** [thingsboard/thingsboard#11584]
**Component**

 * Rule Engine

I have a device that outputs the following telemetry into thingsboard: pressure (number), flow (number), and flushing(bool). Below is the semi-pseudo code that I want to implement through the rule chain using the script node.

// create alarm when below criteria is met
// when flushing occurs 
    // wait 30 seconds
    // check values of pump1 & pump2 statuses & pressure value
        // if all criteria is met
            // return true (send to create alarm node)
        // else return false

var FLUSHING_DURATION = 30 *
1000; // 30 seconds in milliseconds

// Retrieve the flushing start time from the metadata
var flushingStartTime = metadata.flushingStartTime;

if (msg.flushing==1) {
    if (flushingStartTime === undefined ||
        flushingStartTime === null) {
        // If flushing is active and we don't have a start time, set it
        flushingStartTime = Date.now();
        metadata.flushingStartTime = flushingStartTime;
        console.log(flushingStartTime);
    }
} else {
    // If flushing is not active, reset the start time
    flushingStartTime = null;
    metadata.flushingStartTime = null;
}

if (flushingStartTime && Date.now() - flushingStartTime >=
    FLUSHING_DURATION) {
    // Check conditions after 30 seconds of flushing
    return msg.pressure1_psi < 40 && msg.pump1_status ===
        2 && msg.pump2_status === 2;
}

return false;

----

I've attached the rule chain file where I have attempted to implement this logic in various nodes. Please let me know where I am going wrong. 

[filtering_rule_chain.json](https://github.com/user-attachments/files/16901492/filtering_rule_chain.json)

**Comment by pon0marev** [comment]
If you want to configure a delay in a script node, it cannot be implemented because the scripts will be blacklisted.
Use “delay” node to pause message processing in the rule chain.

**Comment by gurverm** [comment]
Since this node is deprecated is there a timeline in which Thingsboard will be removing it from the platform?

**Comment by pon0marev** [comment]
The “Delay” node labeled as deprecated because users misunderstood how it should work. The “Delay” node acknowledges a batch of messages and then continues processing in the rule chain after X seconds. It is not intended to synchronize or sequentially delay between messages in batch.
Therefore it is marked as deprecated, but will not be removed from the platform for now.

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
