### ISSUE TITLE
The link between data source and GPIO widget individaul pin?

### ISSUE THREAD

**Issue by occoder** [thingsboard/thingsboard#1158]
Hi,
I'd like to use the LASTEST VALUE type of GPIO widget bundle to track the boolean states.
I can add the boolean time series as the data source to this widget.
But I'm not able to find out how to link the data source to the actual state of individual LED shown on this widget.
I've looked through all related docs and got the conclusion that ThingsBoard could do this. But HOW is missed. Please advise on this. Thanks.

**Comment by vparomskiy** [comment]
Did you try to follow this tutorial:
https://blog.thingsboard.io/2017/01/esp8266-gpio-control-over-mqtt-using.html

GPIO widget works with 'pins'. In 'advanced' tab you define the mapping between attribute and pin

**Comment by escalanterj** [comment]
That tutorial does not explain anything
