### ISSUE TITLE
Data Communication issue between Flespi and Thingsboard CE Custom installation in ubuntu Server

### ISSUE THREAD

**Issue by adarsh23590** [thingsboard/thingsboard#11582]
**Component**

 * Installation

**Description**
We have installed thingsboard community edition on our linux server. We already have an account in flespi which contains all our teltonika devices. Flespi is working fine. Now we need to integrate thingsboard for our end users. We have set our Linux server address with port 1883 in secondary GPRS settings in Flespi. We have already setup Stream and assign it to all devices so that all data can transmit via stream to thingsboard on our server. Now We are facing some issue as below

- Once i remove all devices from thingsboard platform and if refresh the page. then it is not adding devices from flespi automatically. I have to make test device on platform and then need to add its access token to flespi stream. Then after it is sending devices

- Telemetry data is also sometimes not working as real-time data. Sometimes old data is showing on map or any other widget like speedometer , battery level, etc.

So can anyone help me to resolve this issue.

**Environment**

 * OS:  Linux
 * ThingsBoard: CE

**Comment by adarsh23590** [comment]
even i also want to know about customization from code base. We want to add our custom modules like clusters, Vehicles etc as well as we also want some reports based on data we receive from flespi. So please guide for that also

**Comment by AlexDoanTB** [comment]
@adarsh23590, 
>Once i remove all devices from thingsboard platform and if refresh the page. then it is not adding devices from flespi automatically. I have to make test device on platform and then need to add its access token to flespi stream. Then after it is sending devices

please read the [documentation](https://thingsboard.io/docs/reference/gateway-mqtt-api/) wisely and try not to raise issues that are likely not related to the ThingsBoard platform or Flespi bugs. [Flespi is considered a gateway device](https://flespi.com/kb/flespi-to-thingsboard) on ThingsBoard. If you delete device entities created via MQTT Gateway API, the stream itself (and the session) remains not affected (which is normal). GW API creates devices upon GW connect. If the gateway is connected while you have your devices deleted, the behaviour you described is absolutely standard.  

> Telemetry data is also sometimes not working as real-time data. Sometimes old data is showing on map or any other widget like speedometer, battery level, etc.

There are many use cases when you may get messed up visualization—from sending data with wrong timestamps to low computing power of the machine.

**Comment by adarsh23590** [comment]
Can you guide me for customization at code level. We have install in ubuntu as well as windows using below links

1) **Ubuntu** :-  https://thingsboard.io/docs/user-guide/install/ubuntu/
2) **Windows** :- https://thingsboard.io/docs/user-guide/install/windows/

But we are not able to get code after installation. As per our requirement, we want to add more modules as well as modify existing modules. So Please guide me for this. We are able to get git code from this repo but we are facing isssue in installation.

**Comment by AlexDoanTB** [comment]
@adarsh23590  You are installing the binary image, the service itself. 
To get the code, fork or clone the project and modify whatever you need. 
I'm closing this ticket as irrelevant.
