### ISSUE TITLE
Dashboard query performance on PostgreSQL: Question regarding ts_kv table index and DB sizing

### ISSUE THREAD

**Issue by maximilianpalm** [thingsboard/thingsboard#11591]
**Component**

 * Generic

**Description**
We have some dashboards that take >30s to load the data and would like to improve on that. While analyzing the issue, we found that PostgreSQL takes ~6s to return ~2000 values from one time series (last 7 days). For reference, here are the metrics for our ts_kv table partition for August:

```
SELECT COUNT(DISTINCT entity_id) FROM ts_kv_2024_08;
-- 1,399 devices

SELECT DISTINCT entity_id, key FROM ts_kv_2024_08;
-- 14,453 time series

SELECT COUNT(*) FROM ts_kv_2024_08;
-- 69,964,602 rows -> avg. 26 datapoints per second

-- Partition size: 4,666 MB
-- Index ts_kv_2024_08_pkey size: 5,942 MB
```

We use [deployment scenario B](https://thingsboard.io/docs/reference/iot-platform-deployment-scenarios/#single-server-deployment-with-external-database-scenario-b) which is tested for installations that ingest up to 5k data points per second. Our external DB has 8 GB of RAM, twice the size referenced in that guide, and we only get 0.5% of the traffic. Still, the queries take longer than we would expect and looking at the index size I have a suspicion why that could be.

Side note: I know that ingest and query performance are two different things. However, I would expect a sizing recommended to ingest a certain number of messages to also be able to process and visualize the accumulating data.

So, my questions are:
1. Is there a way to tweak dashboard performance using thingsboard tools? Or do we have to either throw money at the problem for extra RAM and disk IO, or switch to TimescaleDB/Cassandra although we're nowhere near the data rate where this would be recommended?
2. Why does the ts_kv table use a device UUID (`entity_id`) as well as a time series id (`key`) in the primary key? Wouldn't it be more efficient to outsource the large UUID into the mapping table and use a single integer key to uniquely identify each time series? I could imagine that the table as well as the index would be smaller and faster to process for the DB.

**Environment**

 * OS:  RedHat 9.4
 * ThingsBoard: recent PE
 * Browser: Firefox 115.7.0esr

**Comment by pon0marev** [comment]
The performance test is not designed for reads because reads take much longer and the amount of read data is individualized for each case.
Please attach the thingsboard configuration file.
Please describe your infrastructure in detail.
In addition, the m5.large instance type is already outdated and it is preferable to use the m7*.large instance type.

**Comment by maximilianpalm** [comment]
Here is the config file: [thingsboard.conf](https://github.com/user-attachments/files/17016110/thingsboard.conf.txt). Regarding our infrastructure, we're running on Azure using the following components.

Thingsboard Server
- Runs Thingsboard, Zookeeper, Kafka and nginx
- VM size: Standard D2as v5 (2 vCores on an AMD EPYC 7763, 8 GiB RAM)
- Storage: Premium SSD (max. 500 IOPS), 128 GiB

Database
- Azure Managed Service "Azure Database for PostgreSQL"
- VM size: Standard_D2ds_v4 (2 vCores on an Intel Xeon Platinum 8370C/8272CL, 8 GiB RAM)
- Storage: Premium SSD, P20 (max. 2300 IOPS), 512 GiB

Networking
- Thingsboard and the database reside within the same VNet in different subnets.
- We use a WAF that checks web traffic going to the thingsboard nginx.

**Comment by pon0marev** [comment]
What is the load on the server and database?
Attach the database query output (it shows active database queries).
```
SELECT pid, age(clock_timestamp(), query_start), usename, query
FROM pg_stat_activity
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%'
ORDER BY query_start ASC;
```

You can try to increase the maximum number of connections to the database. Add next variable to thingsboard.conf file:
```
export SPRING_DATASOURCE_MAXIMUM_POOL_SIZE=30
```

**Comment by maximilianpalm** [comment]
Thingsboard Server load: RAM 60%, CPU at 8%
Database load: RAM 30%, CPU usually at 12% with short spikes every 40 minutes to 25%

The query regarding the activity returns this:
```
471	"1 mon 30 days 13:50:37.787353"	"azuresu"	"update cron.job_run_details set status = 'failed', return_message = 'server restarted' where status in ('starting','running')"
469	"00:10:34.251033"	"azuresu"	"SELECT query_stats.pgms_stats_insert_data(353947, '60 minutes')"
9406	"00:08:04.935975"	"*****"	"SELECT cls.oid,
    cls.relname as name,
    indnkeyatts as col_count,
    amname,
    CASE WHEN length(spcname::text) > 0 THEN spcname ELSE
        (SELECT sp.spcname FROM pg_catalog.pg_database dtb
        JOIN pg_catalog.pg_tablespace sp ON dtb.dattablespace=sp.oid
        WHERE dtb.oid = 5::oid)
    END as spcname,
    CASE contype
        WHEN 'p' THEN desp.description
        WHEN 'u' THEN desp.description
        WHEN 'x' THEN desp.description
        ELSE des.description
    END AS comment,
    condeferrable,
    condeferred,
    substring(pg_catalog.array_to_string(cls.reloptions, ',') from 'fillfactor=([0-9]*)') AS fillfactor,
    pg_catalog.pg_get_expr(idx.indpred, idx.indrelid, true) AS indconstraint
FROM pg_catalog.pg_index idx
JOIN pg_catalog.pg_class cls ON cls.oid=indexrelid
LEFT OUTER JOIN pg_catalog.pg_tablespace ta on ta.oid=cls.reltablespace
JOIN pg_catalog.pg_am am ON am.oid=cls.relam
LEFT JOIN pg_catalog.pg_depend dep ON (dep.classid = cls.tableoid AND dep.objid = cls.oid AND dep.refobj"
10175	"00:00:20.332405"	"*****"	"COMMIT"
10841	"00:00:20.329725"	"*****"	"COMMIT"
10401	"00:00:11.109767"	"*****"	"COMMIT"
11072	"00:00:05.364034"	"azuresu"	"SELECT pg_catalog.pg_is_in_recovery() as is_in_Recovery"
10072	"00:00:02.573676"	"*****"	"COMMIT"
10847	"00:00:00.968034"	"*****"	"COMMIT"
9601	"00:00:00.967976"	"*****"	"COMMIT"
9812	"00:00:00.950224"	"*****"	"COMMIT"
11076	"00:00:00.323323"	"azuresu"	"commit"
10669	"00:00:00.267627"	"*****"	"COMMIT"
10986	"00:00:00.26761"	"*****"	"COMMIT"
10750	"00:00:00.267566"	"*****"	"COMMIT"
8836	"00:00:00.208569"	"*****"	"COMMIT"
9964	"00:00:00.208419"	"*****"	"COMMIT"
9410	"00:00:00.207304"	"*****"	"COMMIT"
9409	"00:00:00.177241"	"*****"	"COMMIT"
9896	"00:00:00.150398"	"*****"	"COMMIT"
9999	"00:00:00.150304"	"*****"	"COMMIT"
464			
467		"azuresu"	
470		"azuresu"	
473		"azuresu"	
472		"azuresu"	
462			
466			
461			
465			
```
I will test the pool size parameter when I get a chance and get back to you.

**Comment by pon0marev** [comment]
The first 2 queries may negatively affect the database performance because they take too long to run. You may try to terminate them.
Also, try to optimize and clean the database: https://www.postgresql.org/docs/current/sql-vacuum.html

**Comment by maximilianpalm** [comment]
The first two queries belong to the managed PostgreSQL DB of the Azure platform, I don't want to tinker with those. And we have autovaccuum running.

We brought down the loading time for the dashboard somewhat by combining two time series in the same graph, instead of having separate graphs. I read that there is an option to partition the ts_kv table by day instead of month. Could that affect query performance in some way?

Could you comment on my second question from the original post`? I'd still like to understand the design decision regarding the ts_kv primary key.

**Comment by AlexDoanTB** [comment]
@maximilianpalm, 
having a mapping table means the request for O(N) memory and O(N) table reads multiplied by X instances only to initiate it.
100k devices with 10 keys each => 1M records to just up and run. Imagine a cluster of 6 nodes with a lazy load; it will read 6M times from the database.
A straightforward keys approach improves UX with DB operations. However, we use a key dictionary for ts_kv_latest and attributes to address the index and table size in SQL.
Timeseries-oriented DBs (like Cassandra) handle complex keys optimally, operating with hashes, indexes, compression, etc.
Now we are sitting on the wall between performance and complexity for Postgres. Any suggestions are welcome.

**Comment by maximilianpalm** [comment]
Huh, with 100k devices we'd be at 5B rows per month, I don't want to imagine query performance with Postgres for that case. I guess I was just looking at the single node SQL setup. It makes sense that for a more scalable configuraton there is a trade-off.

Any thoughts on the SQL_POSTGRES_TS_KV_PARTITIONING configuration? Could changing it from MONTH to DAY improve our situation? Is it even possible to change the parameter on a running system? A quick google search yielded [this gem](https://github.com/thingsboard/thingsboard/issues/11214#issuecomment-2325843792): "_I started using TB with monthly partitioning and after changed to daily... this was the reason of the mess._"

**Comment by AlexDoanTB** [comment]
I do not think you will get a better performance. 
Changing partitioning on the fly is an absolute red flag — do not do that.

**Comment by maximilianpalm** [comment]
Ok, then we won't touch that setting. In conclusion, we can try to optimize the DB parameters, but my understanding is that we can only get a substantial improvement by either throwing in some extra DB CPU and memory, or by migrating to either TimescaleDB or Cassandra. Does that match your view on the subject?
