### ISSUE TITLE
Question about menu structure

### ISSUE THREAD

**Issue by Rotiot** [thingsboard/thingsboard#11602]
**Component**

 * UI

**Description**
Hello.  I want to change the structure of menus in Thigsboard PE. 
A sample menu structure is in the attached file.
The menus we want to do are not in vertical format but in horizontal format css writing.
Are we doing this from advanced CSS or do we need to intervene directly on the server?
![Uploading dsashboard.jpg…]()

Environment

OS: Ubuntu 20.04.6 LTS
ThingsBoard: v.3.6.4
Browser: Chrome Version 128.0.6613.114 (Official Build) (arm64)

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by trikimiki** [comment]
Could you share the example? It seems you did not upload it properly.

**Comment by Rotiot** [comment]
sorry my mistake I'm uploading again immediately.
![dashboard](https://github.com/user-attachments/assets/6e66e174-b3c4-4452-b219-f7655bc539fd)
