### ISSUE TITLE
 using Docker image "thingsboard/tb-postgres:latest"  pg_ctl: directory "/data/db" is not a database cluster directory

### ISSUE THREAD

**Issue by wyd1520** [thingsboard/thingsboard#11615]
**Describe the bug**
I used Docker to install thingsboard/tb-postgres:latest version on Ubuntu18.04 but it was unsuccessful and the following log was displayed.

Starting Postgresql...
pg_ctl: directory "/data/db" is not a database cluster directory
Connecting to Postgres, 300 attempts left...
Connecting to Postgres, 299 attempts left...
Connecting to Postgres, 298 attempts left...
Connecting to Postgres, 297 attempts left...
Connecting to Postgres, 296 attempts left...
Connecting to Postgres, 295 attempts left...

Data folder permissions are also set using the command。

`
mkdir -p /data/.mytb-data && sudo chown -R 799:799 /data/.mytb-data
mkdir -p /data/.mytb-logs && sudo chown -R 799:799 /data/.mytb-logs
`

![0240910232522](https://github.com/user-attachments/assets/f4c2b250-6dba-46b8-930d-a2c814fdc78a)
![20240910232609](https://github.com/user-attachments/assets/2caf7a41-5b5d-407c-b963-ab8f0c78b141)

**Comment by wyd1520** [comment]
docker-compose.yml

version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - /data/.mytb-data:/data
      - /data/.mytb-logs:/var/log/thingsboard

**Comment by Anders-McLean** [comment]
I'm stuck with the exakt same problem. Any solutions?
