### ISSUE TITLE
Create Users

### ISSUE THREAD

**Issue by xTwigx** [thingsboard/thingsboard#11610]
I am using Thingbaord PE 3.7,

I have a dashboard with many states, I want to have a state dedicated to creating a new users, is there a way a Customer create a user in a dashboard instead of using the thingsbaord menu?

**Comment by xTwigx** [comment]
This is a website i found that has the users "look" i want it to simulate.

So a customer Admin can create a new user and they can also see a list of the users under the Customer they are part of.

I would appreciate any help on this even how to display the Users as Im having some trouble even using the Entities Table

**Comment by devdoob** [comment]
You have to achive this via custom widgets and REST api provided by TB.

here it is implemented as popup dialog

![image](https://github.com/user-attachments/assets/0c8ccfa4-210e-4f09-810a-23a66ce8d987)

`let userService = $injector.get(widgetContext.servicesMap.get("userService"));`

`  
function saveUserObservable(userGroup, user, sendActivationMail)  {
    return userService.saveUser(user, sendActivationMail, userGroup.id.id);
  }
`

**Comment by xTwigx** [comment]
Ok thanks, The table you showed was almost perfect would you be able to send me the json for it and i can try to modify it to fit my needs?

**Comment by devdoob** [comment]
That's a normal Entities table which is loading all the USER type entities from that customer. It's not a custom one. You just need to create a Custom Code Action in that table ad use this service.

**Comment by xTwigx** [comment]
Yes i know but for reason the alias i have is only showing the tenant users.
![image](https://github.com/user-attachments/assets/6ddb110c-ae70-4d2a-a45d-3d9c34455425)

**Comment by devdoob** [comment]
Always create dashboard with context of logged-in customer user. 

1) Create user under your customer
2) Assign your dashboard to user from its user details page
3) Create an alias (entity from dashboard state) in your dashboard to get parent customer of currently logged in user
4) Use stateEntityName from previous alias into new alias to fetch sers from that customer

Alias 1:
![image](https://github.com/user-attachments/assets/af313555-5ea5-4e46-867f-fbb24edab50c)


Alias 2:
![image](https://github.com/user-attachments/assets/f15ffec6-87fb-4708-8c99-8596945c7a81)


Hope this helps!

**Comment by xTwigx** [comment]
Amazing Thanks for the help. I will try to add the custom action to add a user and edit.

**Comment by xTwigx** [comment]
@devdoob Hi im working on the users creation and its almost done im just wondering how you implemented the customer admin.

I have it set up where it created the user and it can select admin or user. then the user is created and given those grouping so that's it functional.

I want to know how you are getting the user group into the table.

**Comment by devdoob** [comment]
You have manintain user role in user's server attributes.... whether he's a normal user or admin user. Also you have to move that user entity in "Customer Users" and "Customer Administrators" upon that admin toggle switch. 

Use entityGroupService for fetching user groups under one customer.

The table headers are the defalt one, I didn't changed anything there

**Comment by DanielBustillos** [comment]
I created a repository that outlines the process I followed to enable user sign-up and account creation. [Here is the repo](https://github.com/DanielBustillos/Users-self-registration-Thingsboard-community-edition). I hope it proves helpful to others.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
