### ISSUE TITLE
out of memory processing log

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#1161]
When starting Thingsboard 2.1.3, I get the following error:
```
2018-10-16 18:04:59,024 [localhost-startStop-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - java.lang.RuntimeException: Logging failed when attempting to log: out
 of memory processing log - /usr/share/thingsboard/data/sql/thingsboardDb line: 75941
Caused by: java.lang.OutOfMemoryError: Java heap space
```
This is about 60% through the log file:
```
thingsboard@thingsboard:~$ wc -l /usr/share/thingsboard/data/sql/thingsboardDb.log
132259 /usr/share/thingsboard/data/sql/thingsboardDb.log
```
I am using the following settings for memory:
`-Xms3512M -Xmx3512M`

Is this large amount of memory usage during startup reasonable?

I was able to start thingsboard by adding another 1GB heap space, but I am not sure how long that will last.

**Comment by vparomskiy** [comment]
Are you using HSQL-DB as a data storage?
In general, HSQL-DB should only be used for development purposes and it is not a good idea to store big datasets in this database because of its nature.
It is better to switch to the Postgres or Cassandra

**Comment by mfalkvidd** [comment]
Yes, I am using HSQL. I tried to migrate to Cassandra or Postgres [7 months ago](https://groups.google.com/forum/#!searchin/thingsboard/cassandra|sort:date/thingsboard/1Rz1aIeVk9s/), but have not managed to figure out how to do it yet.

Do you have any recommendations on how to perform the migration?

**Comment by vparomskiy** [comment]
@mfalkvidd this issue is related to the hsqldb restrictions and I think we can close it. Migration to another database can be discussed in a separate thread.

**Comment by mfalkvidd** [comment]
Yes, we are already tracking the migration instructions in https://github.com/thingsboard/thingsboard/issues/989
Closing.
