### ISSUE TITLE
View entities in descending order in "Update Multiple Attributes" widget

### ISSUE THREAD

**Issue by zelms** [thingsboard/thingsboard#11620]
**Component**

 * UI

**Description**
By default, the "Update Multiple Attributes" widget will display entities in an ascending order. If I have an alias that contains three devices named Employee 1, Employee 2, and Employee 3, then the widget will display Employee 3 at the top and Employee 1 at the bottom. I would like to display entities in a descending order instead, such that Employee 1 is at the top and Employee 3 is at the bottom, is there a way to do this?

**Environment**
 * ThingsBoard: 3.7.0

**Comment by sumin-denys** [comment]
Hi @zelms,

The **_Update Multiple Attributes_** widget sorts entities by creation time. In case you want to display the devices in the following order: Device 1 -> Device 2 -> Device 3, please recreate them in the revert order like that: Device 3 -> Device 2 -> Device 1.

Please let me know if you need further help.

**Comment by zelms** [comment]
That answers my question, thank you!
