### ISSUE TITLE
Required Access token JWT Token in side custom widget for calling Thingsboard API

### ISSUE THREAD

**Issue by abhishekanne** [thingsboard/thingsboard#1162]
Hi 

In one of use case we are calling thingsboard API within init method of custom wdget.

we required token to access the API's

How we can get JWT token of user  who is already logged in ?

I am unable to find it inside slf.ctx object?

Thanks

**Comment by vparomskiy** [comment]
You can use this code:

let $scope = self.ctx.$scope;
let userService = $scope.$injector.get('userService')
let token = userService.getJwtToken();
console.log('Token = ' + token);

Also, you can find other useful authentication methods inside userService

**Comment by Tasosgi** [comment]
At TB 3.0.1PE I can't found .getJwtToken() or .getAuthority() methods in userService. Are these methods exist somewhere else?

**Comment by Windyle** [comment]
> At TB 3.0.1PE I can't found .getJwtToken() or .getAuthority() methods in userService. Are these methods exist somewhere else?

Same problem, does anyone know a possible solution?

**Comment by Windyle** [comment]
I found that they have it stored in the local storage, you can access it using this line of code:

var token = localStorage.jwt_token;
