### ISSUE TITLE
Timewindow shows weird string when translated

### ISSUE THREAD

**Issue by KRderksen** [thingsboard/thingsboard#11624]
When running dashboard in the thingsboard cloud you have the option to set language. when the translation is set to dutch(Nederlands). You see a weird string instead ofthe timestamp.

* [ThingsBoard Cloud](https://thingsboard.cloud)

* Browser chrome
* Version [e.g. 22]

**To Reproduce**
1. Go to a dashboard
2. Click on the three dots (upper right in screen) 
3. click on Account
4.  Set language to dutch(Nederlands)
5. return to dashboard and refresh te page
6. See error
**Expected behavior**

You see a Json string instead of time.

**Screenshots**
![Schermafbeelding 2024-09-11 093122](https://github.com/user-attachments/assets/36a31086-0fa0-467f-ac4f-ee72cd7ac938)
![Schermafbeelding 2024-09-11 090530](https://github.com/user-attachments/assets/db5833ed-5c8f-471c-8984-ffb08bad8d9e)

**Additional context**
Please feel free to add any other context about the problem here.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi

Please clear the browser cache by pressing CTRL+F5 or via browser settings to resolve the issue. This should help you.
![image](https://github.com/user-attachments/assets/a83571fb-96e8-4d3d-85ea-bca1a389b72e)
If it doesn’t help you, then it’s indeed custom translations, so in this case, you need to check the lines related to the timewindow in your custom localization.
In the localization of ThingsBoard PE 3.5+ was changed in code regex for the detection of value for a locale, for example:

```
"timewindow": {
    "years": "{ years, plural, =1 { year } other {# years } }",
    "months": "{ months, plural, =1 { month } other {# months } }",
    "weeks": "{ weeks, plural, =1 { week } other {# weeks } }",
    "days": "{ days, plural, =1 { Tag } other {# Tage } }",
    "hours": "{ hours, plural, =0 { Stunde } =1 {1 Stunde } other {# Stunden } }",
    "hr": "{{ hr }} hr",
    "minutes": "{ minutes, plural, =0 { Minute } =1 {1 Minute } other {# Minuten } }",
    "min": "{{ min }} min",
    "seconds": "{ seconds, plural, =0 { Sekunde } =1 {1 Sekunde } other {# Sekunden } }",
    "sec": "{{ sec }} sec",
    "short": {
      "days": "{ days, plural, =1 {1 day } other {# days } }",
      "hours": "{ hours, plural, =1 {1 hour } other {# hours } }",
      "minutes": "{{minutes}} min ",
      "seconds": "{{seconds}} sec "
    },
```

It can be the difference between your locale and ours – =1 {Sekunde} in our and in your 1 {Sekunde} (for example).
In this case, you will need to change as shown in the example from 1 {day}, 1 {week}, etc. to =1 {day}, =1 {week}, etc.

**Comment by KRderksen** [comment]
It is indeed in the traslations. The keyword is "other" is translated to andere. Which is the dutch word for other. this solved the problem.
