### ISSUE TITLE
Documentation: Review gateway statistics refers to wrong tab

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#1163]
The gateway getting started guide (https://thingsboard.io/docs/iot-gateway/getting-started/#step-6-review-gateway-statistics ) refers to "Latest telemetry" but for my gateway (running version 1.4.0) the data is stored as "Server attributes".

![image](https://user-images.githubusercontent.com/893502/47086937-10a50400-d21b-11e8-8040-3d5f3584fe02.png)

Latest telemetry is empty:
![image](https://user-images.githubusercontent.com/893502/47086917-008d2480-d21b-11e8-9304-7e58eeb97fc5.png)

Perhaps the documentation needs to be updated?

**Comment by vparomskiy** [comment]
No, you should see “devicesOnline”, “attributesUploaded” and “telemetryUploaded” fields in the 'Latest telemetry'.
Right now you do not have them in the latest telemetry and in the attributes section, so your gateway was not yet connected to the Thingsboard.

**Comment by mfalkvidd** [comment]
ok, thanks. Sorry for the confusion.
