### ISSUE TITLE
OPC-UA Integration security

### ISSUE THREAD

**Issue by GabBilo12** [thingsboard/thingsboard#11636]
**Component**

 * Installation

**Description**
Hi everyone, I would like to know how to secure my OPC-UA integration, there is no documentation about that and I would like to know how to do it.

**Environment**

 * OS:  docker
 * ThingsBoard: 3.6.4 EDGEPE

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Ultrazombie** [comment]
Hello @GabBilo12 
please see [OPC-UA integration secure options](https://thingsboard.io/docs/user-guide/integrations/opc-ua/#:~:text=Security%3A%20None%20(can%20be%20Basic128Rsa15%20/%20Basic256%20/%20Basic256Sha256%20/%20None)%3B)

**Comment by GabBilo12** [comment]
Hello @Ultrazombie , this section doesn't say a lot, I would like to know more about this part of the security, which there is no documentation that i've seen.
![image](https://github.com/user-attachments/assets/790de2fd-9df2-4748-bd64-a2a086b432ac)
Thanks!

**Comment by ssakharova** [comment]
Hello @GabBilo12,

In the Security section, you can select the security type supported by your server from the available options: Basic128Rsa15, Basic256, Basic256Sha256, or None.
Afterward, you can choose one of two format types (PKCS12 and JKS) and upload the file containing the key.

**Comment by ssakharova** [comment]
Closed due to inactivity.
