### ISSUE TITLE
Persistent RPC remains in TIMEOUT state after ThingsBoard restart

### ISSUE THREAD

**Issue by stoismeister** [thingsboard/thingsboard#11642]
**Description**: 

When sending a persistent RPC to an inactive device, if ThingsBoard is restarted before the RPC is successfully executed, the RPC remains in the "TIMEOUT" state after the restart. Even when the device comes back online, the RPC is not re-queued or processed, and it remains stuck in the "TIMEOUT" state, preventing it from being executed.
If a ThingsBoard restart is not involved, the RPC call reaches the device when it becomes active (as expected).

I've tried, after the restart, to check the logs with `tail -f /var/log/thingsboard/thingsboard.log | grep <rpcId>`, but I can't see anything happening.

**Steps to Reproduce**:

Send a persistent RPC to an inactive device.
Restart ThingsBoard while the RPC is pending.
Bring the device back online.
Observe that the RPC remains in "TIMEOUT" instead of being reprocessed.
Expected Behavior: The RPC should be reprocessed once the device comes back online after the ThingsBoard service is restarted.

**Environment**:

ThingsBoard version: CE 3.6.3
OS: Ubuntu

**Comment by dealnat** [comment]
Hi, as [documentation](https://thingsboard.io/docs/user-guide/rpc/#:~:text=TIMEOUT%20%2D%20ThingsBoard%20transport,5%20by%20default) says, TIMEOUT messages will not be retried by default and you need to specify their quantity in the request body.

**Comment by stoismeister** [comment]
> Hi, as [documentation](https://thingsboard.io/docs/user-guide/rpc/#:~:text=TIMEOUT%20%2D%20ThingsBoard%20transport,5%20by%20default) says, TIMEOUT messages will not be retried by default and you need to specify their quantity in the request body.

Hi, this is clear, but in the tests I had set 3 retries and it had only done the first one. If I reconnect the device (which is offline) as soon as it comes back active the RPC call is executed successfully. But if I repeat the same test by interposing a restart of thingsboard after the first timeout, this will not retry the remaining 2 retries.

**Comment by dealnat** [comment]
Hi, sorry for the delayed response. I checked the latest 3.8.1 version, and the issue wasn't reproduced. A queued persistent RPC message was sent after the Thingsboard restart. Please verify if this works for you.

**Comment by dealnat** [comment]
Closed due to inactivity
