### ISSUE TITLE
Port Forwarding ?

### ISSUE THREAD

**Issue by JacoFourie** [thingsboard/thingsboard#1164]
Hi all. This is more a question than an issue.
I have installed Thingsboard on a Raspberry Pi and it works 100%. I want to get to a Dashboard from outside my network. So I set-up port forwarding on my router. I can get to the Dashboard but the Widgets do not show any data. So I am guessing the widgets use web-sockets to get the data and it is running on another port. How can I get the widgets to show the data ?

Regards.

**Comment by vparomskiy** [comment]
You are right, widgets are using web-sockets for communication with the thingsboard.
Please find how to enable WebSockets in the documentation of your router.

**Comment by vparomskiy** [comment]
yes, the port is the same (8080 by default)

**Comment by JacoFourie** [comment]
OK but if I can see the HTML and it runs on port 9090 external mapped to port 8080 internal, why can the widgets not see the data as the port is being forwarded ?

**Comment by JacoFourie** [comment]
Reason I am asking is I have another IOT Dashboard EMONCMS and it also uses websockets and it is working fine via my router. So I am wondering if the if TB is generating the HTML / javascript code to point to the server path of my internal IP. So external clients wont get to that IP. Where can I check for that as I had a look at the page source and can not find where the websocket connection is made from the client side.

**Comment by JacoFourie** [comment]
Here is the TB Dashboard that does not work.

http://jdphotography.dyndns.org:9090/dashboard/15eda990-cef0-11e8-b88b-13b80a732a57?publicId=3a68ac80-cb2f-11e8-b88b-13b80a732a57

and here is the EMONCMS one behind the same router just on another port

http://jdphotography.dyndns.org:8000/emoncms/aicc/Power

**Comment by vparomskiy** [comment]
It is really strange because the first link to the thingsboard actually works correctly. I can see the data.
Are you sure that you are not using a 
proxy for accessing thingsboard dashboard?
You can also debug WebSockets in the browser console

![thingsboard dashboard](https://user-images.githubusercontent.com/4686483/47143596-36d7ac00-d2ce-11e8-9213-71b0e5d137bd.png)

**Comment by JacoFourie** [comment]
aaaa OK yes I am behind a proxy at work. So it is the proxy that is blocking the widgets ?

**Comment by JacoFourie** [comment]
If it is the proxy. Why would EMONCMS work and not TB through the same proxy server ?

**Comment by vparomskiy** [comment]
This page does NOT use WebSockets 
http://jdphotography.dyndns.org:8000/emoncms/aicc/Power

Data is loaded by GET http requests.

You can find it by opening browser console and filter network requests by type (in chrome - WS)

**Comment by msalajka** [comment]
check your proxy at work for websocket support. https://websocketstest.com/

**Comment by JacoFourie** [comment]
Aaa thanks. It seems our proxy servers are blocking websockets on non ssl ports.

![image](https://user-images.githubusercontent.com/17771641/47201308-abb3f000-d379-11e8-9d59-c69f604e114f.png)

**Comment by JacoFourie** [comment]
What is the best way to run Thingsboard on SSL. I found this post for nginx

https://gist.github.com/mfalkvidd/3920bd5035806a583b5c1e20eaddabae

I am not sure how to set it up. I have the config file but there are no instructions on how to set-up everything to use this config file. Where should it go etc ?

**Comment by vparomskiy** [comment]
You can generate free SSL certificate via let's encript.
You can use any proxy for configuring https - ngins, haproxy, apache2
Note that you will need a registered domain for creating certificate.

Here is a reference how to generate ssl certificate with let's encript, connect certificate to apache2 and enable https with websockets:

> APACHE
> 
> sudo mcedit /etc/apache2/sites-available/000-default.conf
> 
> ----------------
> 
> ServerName YOUR_DOMAIN_NAME
> 
> RewriteEngine On
> RewriteCond %{HTTP:Upgrade} =websocket [NC]
> RewriteRule /(.*)           ws://localhost:8080/$1 [P,L]
> 
> RewriteCond %{HTTP:Upgrade} !=websocket [NC]
> RewriteRule /(.*)           http://localhost:8080/$1 [P,L]
> 
> RequestHeader set X-Forwarded-Proto "http"
> RequestHeader set X-Forwarded-Port "80"
> 
> ProxyPreserveHost on
> 
> ProxyPass / http://localhost:8080/
> ProxyPassReverse / http://localhost:8080/
> 
> --------------------
> 
> sudo a2enmod proxy proxy_http proxy_wstunnel rewrite headers
> 
> 
> HTTPS
> 
> --------------------
> 
> sudo add-apt-repository ppa:certbot/certbot
> 
> sudo apt-get update
> 
> sudo apt-get install python-certbot-apache
> 
> sudo certbot --apache -d YOUR_DOMAIN_NAME
> 
> sudo mcedit /etc/apache2/sites-available/000-default.conf
> 
> RewriteEngine On
> RewriteCond %{SERVER_NAME} =YOUR_DOMAIN_NAME
> RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
> 
> sudo mcedit /etc/apache2/sites-available/000-default-le-ssl.conf
> 
> RequestHeader set X-Forwarded-Proto "https"
> RequestHeader set X-Forwarded-Port "443"

**Comment by JacoFourie** [comment]
Thanks all for the info. I have NGINX installed so want to use it for now.

I have to use this statement to generate the cert

letsencrypt certonly --webroot -w /var/www/example.com -d example.com -d www.example.com

for Thingsboard what should the /var/www/example.com  be ?

I have the domain jdphotography.dyndns.org so will use that 

letsencrypt certonly --webroot -w /var/www/example.com -d jdphotography.dyndns.org 

but I am not sure what the /var/www/example.com should be for the default install of Thingsboard.

**Comment by msalajka** [comment]
you should have configured nginx port 80 too... (for letsencrypt certificate generation and traffic redirect to https). for example:

```
    server {
        listen 443;
        server_name thingsboard.example.com;
        ssl on;
        ssl_certificate      /etc/letsencrypt/live/thingsboard.example.com/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/thingsboard.example.com/privkey.pem;
        location / {
            proxy_pass  http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection "Upgrade";
            proxy_set_header    Host $host;
        }
   }

    server {
        listen 80;
        server_name thingsboard.example.com;
        location /.well-known/acme-challenge {
            root /var/www/thingsboard.example.com;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }
```
create directory /var/www/thingsboard.example.com

and run... 

letsencrypt certonly --webroot -w /var/www/thingsboard.example.com -d thingsboard.example.com

replace thingsboard.example.com with your domain.
