### ISSUE TITLE
MQTT client was disconnected with reason code 7

### ISSUE THREAD

**Issue by AndreSensaway** [thingsboard/thingsboard#11665]
**MQTT API**
 * Generic

**Description**
I'm using the Python Client SDK (tb-mqtt-client version 1.9.9) to send telemetry data to devices in my thingsboard instance.

When connecting to a gateway device, I keep getting the following message:

`MQTT client was disconnected with reason code 7 (The connection was lost.)`

This happens continuously (around 1 to 2 times per second). I can send telemetry/attributes in the brief periods that the connection holds, but it is not sustainable.

Here is the minimal code that reproduces my error:

```
from time import sleep
from tb_gateway_mqtt import TBGatewayMqttClient
import logging
logging.basicConfig(level=logging.DEBUG)

gateway = TBGatewayMqttClient('myUrl.com', 
                                port=1883, 
                                username='deviceToken')
gateway.connect()

i=0
while True:
    i+=1
    print(f'sent: {"hello_"+str(i)}')
    sleep(10)
```

Is there something wrong with the code or is this a problem on the thingsboard mqtt broker side? From what I could figure out, it seems that the thingsboard broker is disconnecting the client.
I've looked at the thingsboard logs and cannot find anything that would indicate that it is refusing the connection for some reason.

Any help on this would be appreciated!

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.6.4 PE
 * Browser: chrome

**Comment by mykhailokornieiev** [comment]
Hi. Since this problem is related to Python Client SDK and you already created a ticket in the respective repository, I will close this as a duplicate
