### ISSUE TITLE
MQTT rule node: org.thingsboard.mqtt.ChannelClosedException: Channel is closed

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11680]
**Component**
 * Rule Engine - MQTT node

**Description**
I am trying to push telemetry from one tenant to another on the same TB server instance. As a username of MQTT basic credentials I am using token of device, actually it is gateway. In general, I want to push telemetry through MQTT gateway API, but through MQTT node. 

In most cases, I observed failures in debug events of MQTT node (please, see video for more details). Is it possible to use MQTT node for such case?

```
org.thingsboard.mqtt.ChannelClosedException: Channel is closed!
	at org.thingsboard.mqtt.MqttClientImpl.sendAndFlushPacket(MqttClientImpl.java:467)
	at org.thingsboard.mqtt.MqttClientImpl.publish(MqttClientImpl.java:390)
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.onMsg(TbMqttNode.java:88)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:158)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
...
```

https://github.com/user-attachments/assets/88c2a567-9023-47e6-af50-d5a5e8a5da9f

**Environment**
 * OS:  Ubuntu 22
 * ThingsBoard: 3.7.0

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hello,
As you are using the same credentials for this, it's okay that the channel closes when another connection is opened. You can tune this with the configuration parameter ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE, but this doesn't seem to be a production-ready solution.

**Comment by devaskim** [comment]
> As you are using the same credentials for this, it's okay that the channel closes when another connection is opened
 
Is there any option to tell the node to open once a connection and use it all the time? I thought it is possible with `Single mode` option, but no, even with this option is enabled, I observe connection closing.

**Comment by devaskim** [comment]
> As you are using the same credentials for this, it's okay that the channel closes when another connection is opened
 
Hi @dealnat,
Is there any option to tell the node to open once a connection and use it all the time? I thought it is possible with `Single mode` option, but no, even with this option is enabled, I observe connection closing.

**Comment by dealnat** [comment]
Hi,
Yes, you are right, singleton mode is used to keep connection, but ThingsBoard does not allow multiple connections with the same credentials (for the same device, even if this is a gateway device). When the second connection is created, the first one is closed. As a workaround use the option from my previous response.

**Comment by devaskim** [comment]
> When the second connection is created, the first one is closed. As a workaround use the option from my previous response.

I was unclear in my question, so try to rephrase. 
@dealnat  Why TB open yet another connection if, at least in my case, there is single MQTT node in single rule chain on single server instance?

**Comment by devaskim** [comment]
>  When another device connects to this gateway with the same credentials connects to that gateway it blocks the previous connection, and you see the error "Channel is closed"

@dealnat  There is only one device sending in my recent test. To be sure, I re-tested with simple chain - Generator node + MQTT node. From screenshot below it is clear that "Channel is closed" randomly happens even for single device.
![Скриншот 24-09-2024 212054](https://github.com/user-attachments/assets/157fd2cc-1a47-484f-8c2e-f774ba8cd99e)

**Comment by devaskim** [comment]
@dealnat Nevermind my last comment. In general, you are right. Many thanks for your help!

**Comment by devaskim** [comment]
> When another device connects to this gateway with the same credentials connects to that gateway it blocks the previous connection, and you see the error "Channel is closed"

Agree. Not sure why the error happened in my case, because I use only single device to push data via MQTT node, but after I had changed credentials to another gateway device, the error disappeared. 

So, now I don't see any "Channel is closed" on MQTT node side, but there is not any telemetry on tenant-receiver side))) - only single Connect event... @dealnat , I know it is out of scope, but maybe you have some ideas why?
![Скриншот 24-09-2024 222454](https://github.com/user-attachments/assets/946f2567-5e00-4c96-b54d-845aa90cd857)

**Comment by dealnat** [comment]
Hi, I can't tell why exactly this happens, but as I mentioned before - trying to push telemetry via mqtt node to the gateway isn't a good solution and may cause a lot of trouble. I recommend you set up an external mqtt broker and use it

**Comment by devaskim** [comment]
Thanks @dealnat for your help
