### ISSUE TITLE
OTA upgrade

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#11683]
When the thingsboard firmware update device processes the sub-package download, according to the demo file provided by the official website, the __firmware_request_id in the demo file is self-incrementing. If the device is restarted, this id starts from 0 again. Will it conflict with the previous one? I want to know how thingsboard handles this problem.

**Comment by sumin-denys** [comment]
Hi @Remington-Hunter,

Could you please provide a demo file with the following variable? Since I am not able to find anything regarding the **__firmware_request_id**.

**Comment by Remington-Hunter** [comment]
Hi, the demo file I am using is the mqtt example given in the thingsboard document. I saw the use of this variable in it, so I would like to ask this question. I want to know whether this variable will affect the previously disconnected downloads when the download starts from 0 after the mqtt is disconnected.

[https://thingsboard.io/docs/user-guide/ota-updates/?remoteintegrationdockerinstall=mqtt](url)

**Comment by sumin-denys** [comment]
Hi @Remington-Hunter,

If I understand everything correctly, you are interested in how ThingsBoard handles the behavior when the device starts downloading the firmware and, during this process, gets disconnected from the ThingsBoard server. 

In case of such a problem, when the device reconnects to the server and receives the notification about new firmware, the downloading process will start from the beginning. 

The answer to your question is that the **__firmware_request_id** variable won't affect the new download process.

Please let me know if you have additional questions.

**Comment by Remington-Hunter** [comment]
I understand, thank you very much for your prompt reply and assistance!
