### ISSUE TITLE
Please provide the offical ThingsBoard downgrade document.

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11696]
Hi ThingsBoard Support.

I am going to downgrade Thingsboard 3.5 to 3.4.3, please provide a offical document for it.
If the official document has not been prepared yet, please guide me how to downgrade.

Thanks.

**Comment by mykhailokornieiev** [comment]
Hi. 
ThingsBoard doesn’t have a downgrade function.
But you can perform a downgrade to 3.4.3. This can be done only in case you have a backup of your PostgreSQL database from the 3.4.3 version before upgrading to 3.5

To perform a downgrade, please do the next actions:

    Restore the PostgreSQL database it’s version from 3.4.3

    Please download and install ThingsBoard 3.4.3 PE version

Then, run the service.

**Comment by Jameschan07** [comment]
Hi,
Thank you for your quick reply.

But I am using community edition, alsoI don't have the PostgreSQL backup. Can I just download and install ThingsBoard 3.4.3?
(Data losing on Database is allowed)

Thanks.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
