### ISSUE TITLE
Rule Engine - External Node for Google Pub/Sub

### ISSUE THREAD

**Issue by nitinware** [thingsboard/thingsboard#1170]
Currently Thingsboard Rule Engine provides External Nodes for AWS SNS, SQS, Rabbit MQ, Kafka.
Similarly I need a External Node for publishing the telemetry data to Google Cloud Pub/Sub Topics.
Please add this External Node, so that I can integrate my existing system using Thingsboard with minimal change or else I have to add another hop of MQTT/Kafka before publishing it to Pub/Sub.

**Comment by kardashov** [comment]
Hi, added it here:
https://github.com/thingsboard/thingsboard-rule-config-ui/pull/18
https://github.com/thingsboard/thingsboard/pull/1798
