### ISSUE TITLE
Downgrading Thingsboard 3.5 to 3.4.3

### ISSUE THREAD

**Issue by Jameschan07** [thingsboard/thingsboard#11705]
Hi ThingsBoard Support.

I am going to downgrade Thingsboard 3.5 to 3.4.3.

I am currently using the Community Edition, and I do not have a backup of the PostgreSQL database. 

Can I just download and install ThingsBoard 3.4.3 on existing ThingsBoard 3.5 environments? 

(I am okay with losing the data in the database.)

Thank you!

**Comment by mykhailokornieiev** [comment]
Closed as duplicate https://github.com/thingsboard/thingsboard/issues/11691
