### ISSUE TITLE
How to cumulatively add to a value (telemetry or attribute) via rule chain.

### ISSUE THREAD

**Issue by gurverm** [thingsboard/thingsboard#11711]
I have a device that sends a controller status. When the controller status is 2, I want to add 1000 to a separate variable called water_consumed_litres.

The logic I’m trying to achieve with the script nodes in my rule chain is as follows:

Filter Script Node:

// Check if the controller status is 2
return msg.controller == 2;

Transformer Script Node:
// Add 1000 to water_consumed_litres for the last 10 minutes
msg.water_consumed_litres += 1000;

return {
    msg: msg,
    metadata: metadata,
    msgType: msgType
};

---

The issue I’m facing is that when I use the + operator to update water_consumed_litres, the telemetry gets updated as expected. However, when I try to use the += operator, it doesn’t work as intended (though I understand that’s not the behavior I want anyway).

I’ve attached the rule chain file for reference. Could you help clarify why this behavior occurs.

Thanks in advance!

[menzies_valve_output.json](https://github.com/user-attachments/files/17066002/menzies_valve_output.json)

**Comment by devdoob** [comment]
Use Math node for that. I am assuming water_consumed_litres is a telemetry key not attribute

![image](https://github.com/user-attachments/assets/5e36a94b-3b25-4647-a4a0-f5004e41dfe7)

![image](https://github.com/user-attachments/assets/d353f440-2187-45a0-bce8-846df6ade746)

**Comment by gurverm** [comment]
Thank you this worked perfectly! Is there any way that i can get the min and max values over a 24 hour time period through the rule chain? I have found a way to do so through widget data post-processing but its not the greatest. 

For example i have a device that sends temperature values every 15 seconds and id like to retrieve the min and max values from a given day.

**Comment by devdoob** [comment]
For that use Aggregate Stream node. This will calulcate min/max for whole day and save that into telmetry. Make sure you set timezone properly.

![image](https://github.com/user-attachments/assets/b06f5baa-7ae5-4a18-9b6c-1b696f1cbe71)
