### ISSUE TITLE
On-Failure rune node

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11714]
**Is your feature request related to a problem? Please describe.**
As more complex rule chain is, as harder to catch up different errors and failures in reasonable time. For example, here is NPE after upgrading to 3.7.0: https://github.com/thingsboard/thingsboard/issues/11688

**Describe the solution you'd like**
Provide single On-Failure node for each rule chain. This node will be a sink for all others nodes, exactly for theirs Failures. Having this node user would have chance to be notified as soon as possible about various failures.

**Comment by ssakharova** [comment]
Hello @devaskim,

We have to reject this feature request as we believe it could negatively impact performance.

As an alternative, we recommend tracking and collecting metrics through monitoring. You can then create alarms as soon as any failures are detected.
