### ISSUE TITLE
[Feature Request] Seamless Transition Feature from old Chart Widgets to New new Chart widgets (v3.7.0+)

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#11728]
Issue: After upgrading to version 3.7.0, existing chart widgets (time series, state, bar) do not automatically update to the new chart widgets, requiring manual replacement across multiple dashboards, which is **tedious**.

Suggested Solutions:

1.  One-Click Upgrade: Implement a feature to upgrade existing chart widgets to the new version with a single click, ensuring no loss of functionality or data.

2.  Widget Settings Management:
- Export/Import Settings: Allow users to export widget settings and import them into new widget types, facilitating an easier transition.
- Template Library: Introduce a template library where widget settings can be saved and applied to new or existing widgets, enhancing efficiency.

Benefits:

- Simplifies the upgrade process for users with numerous dashboards.
- Enhances user experience by providing tools for quick widget management.
- Can come handy for other dashboard building scenarios, eliminating repetitive tasks.  

@AlexDoanTB

**Comment by AlexDoanTB** [comment]
Hi @t0mZ4,

>  One-Click Upgrade: Implement a feature to upgrade existing chart widgets to the new version with a single click, ensuring no loss of functionality or data.

This does not seem to be a good feature, as dashboards are tailor-made according to the customer's designs, standards, etc. Forceful changes in design may significantly affect users and UX (mobApps especially). This is not the best approach from a backward compatibility standpoint also. 
Perhaps adding a checkbox in the widget's configuration ("change to a new implementation if it exists") makes sense. But this is still in question. 

> Export/Import Settings: Allow users to export widget settings and import them into new widget types, facilitating an easier transition.

I guess, the easiest way is to have a "Copy settings" (datasource) button. But what about CSS? How to resolve the appearance. Again, the feature is complex and requires evaluation and proper design. We'll keep it in mind.   

> Template Library: Introduce a template library where widget settings can be saved and applied to new or existing widgets, enhancing efficiency.

It may appear obsolete with a "Copy settings" button. But all the ideas are welcome. We'll have an improvement ticket raised.
