### ISSUE TITLE
web report configuration with load balancer

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#11721]
**Component**
 * Installation

**Description**
Hi all,
I am planning to start using web reports, but before doing so I would like to know the intended setup.
We are running PE in a docker container. Running the all in one docker, not mcroservices.
I can see the process tb-web-report is running in the container.
When I try to create a PDF it seems my browser want to access the service directly through the https haproxy address.
I was wondering if the intention is to open up this through the load balancer with public access over https and hence that this service is intended / secure in this configuration.

**Environment**

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by pon0marev** [comment]
When you click the create report button, the request is sent to the thingsboard service and redirected to tb-web-report. Then tb-web-report opens the dashboard via a public link (https) and generates a pdf file. This file is sent to thingsboard and then returns to the user. In this case you cannot override the link for the report.
However, if you create the report using the scheduler, you can specify any dashboard endpoint, like `localhost`.
In the second case, you will not use the external network

**Comment by tobbelin** [comment]
Thanks,
It is designed for public access then?

Best
Tobias

**Comment by pon0marev** [comment]
If you mean connecting the web-report via a public HTTPS link to the dashboard, then yes, that's how it works.

**Comment by pon0marev** [comment]
Schema |         Name         | Type  |  Owner   | Persistence | Access method |    Size    | Description 
--------+----------------------+-------+----------+-------------+---------------+------------+-------------
 public | audit_log            | table | postgres | permanent   | heap          | 1924 MB    | 
 public | relation             | table | postgres | permanent   | heap          | 1294 MB    | 
 public | alarm                | table | postgres | permanent   | heap          | 664 MB     |
