### ISSUE TITLE
Change Originator and Related Device Attributes Query by Entity ID or Device Token

### ISSUE THREAD

**Issue by rascove** [thingsboard/thingsboard#11723]
**Is your feature request related to a problem? Please describe.**
The change originator rule chain node only select the first one from multiple relations with same type. The same issue also applicable to related device attributes rule chain node.

**Describe the solution you'd like**
We should be able to specify the related entity in the change originator and related device attributes rule chain nodes, not only by the direction and type, but also by the entity ID or device token to be more specific.

**Describe alternatives you've considered**
The change originator rule chain node also offer the lookup by name, but this may return incorrect entity if multiple entities with the same name, including from different tenancy. No other possible alternative for the related device attributes rule chain node.

**Additional context**
Not applicable.

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. There is already added such a feature request in our backlog.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by thomas-seag** [comment]
Is there any timeline? A "Change Originator" node that can change to the desired entity by ID would be _very_ useful.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #16070 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
