### ISSUE TITLE
Alarm count Widget

### ISSUE THREAD

**Issue by GreazlyA** [thingsboard/thingsboard#11738]
**Component**

 * Generic

**Description**
Alarm count widget for customer of customer 
**Environment**

 Hi using alarm count widget for customer hierarchy dashboard.
I have customer A that has Customer B Customer C  and Customer D under him .
devices owner are customers  B,C,D .
when i login with Customer  B,D  or C users i can see the alarm count on the widget correctly.
when i login with Customer A  user , i would expect to see alarm count for both B,C and D on the widget but i see none (0 alarm).
when looking at the Customer A alarm  i can see the aggregation of B,C,D  in it's alarm tab.
I have attached screen shots  of each customer system alarm page  and alarm widget 

![customer A](https://github.com/user-attachments/assets/453c8949-047a-4d31-9756-9d7b26d2f618)
![customer B](https://github.com/user-attachments/assets/c3639572-a0b2-47f6-92e4-ff094389ecab)
![customer C ](https://github.com/user-attachments/assets/eea03bb3-18fe-4f10-97db-d75af0bc88b4)
![customer D](https://github.com/user-attachments/assets/dae12ad1-1e2d-46b7-8f45-d755976bcb0f)
![lalarm count widget](https://github.com/user-attachments/assets/771f9ba8-11d8-4210-b6d1-eb9295b912b5)

  

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
Alarms count widget is designed in such way that it can only display alarms on current customer level. So there is no possibility to display alarm count of subcustomers devices. Only to create custom widget

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
