### ISSUE TITLE
Device Not Receiving OTA Upgrade Command After Being Offline

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#11732]
After assigning firmware while the device is offline, the device does not receive the OTA upgrade command when it comes back online. How can this issue be resolved?

Thank you!

**Comment by Remington-Hunter** [comment]
Hi，
I am using mqtt_firmware_client.py. When I tried it, I found that every time the simulated OTA upgrade process is started, it will send a request to Thingsboard to obtain firmware notification. The phenomenon I am talking about is that if this request is not sent at startup, and the firmware is allocated in an offline state, the device will not receive the firmware upgrade notification when it goes online again.

`def request_firmware_info(self):
        self.__request_id = self.__request_id + 1
        self.publish(f"v1/devices/me/attributes/request/{self.__request_id}", dumps({"sharedKeys": REQUIRED_SHARED_KEYS}))`
        
 The above code should be that this simulation file will actively send a request every time it runs, and then determine whether to upgrade the firmware.   
 Do you have any other way to ensure that the device can receive firmware upgrade notifications through MQTT? I look forward to your reply. Thank you.

**Comment by dealnat** [comment]
Please provide detailed steps to reproduce because I can download OTA with the mqtt_firmware_client.py too.

**Comment by Remington-Hunter** [comment]
Here’s the translation of your requirements and the function in Markdown format:

---

### Step 1: Comment out the Function in Code
In the file, locate the `__on_connect` function and comment out the last line `self.request_firmware_info()` so the device will not connect automatically. 

```python
def __on_connect(self, client, userdata, flags, result_code, *extra_params):
    print(f"Requesting firmware info from {config['host']}:{config['port']}..")
    self.subscribe("v1/devices/me/attributes/response/+")
    self.subscribe("v1/devices/me/attributes")
    self.subscribe("v2/fw/response/+")
    self.send_telemetry(self.current_firmware_info)
    # self.request_firmware_info()
```

### Step 2: Assign Firmware in the ThingsBoard Dashboard
In the ThingsBoard frontend, navigate to the dashboard and assign the firmware.

### Step 3: Connect to the MQTT Device Using the File
After establishing the connection, the device does not receive an OTA (over-the-air) update notification automatically. When the firmware version is switched while connected, the update executes as expected. However, when offline, the device does not receive upgrade notifications unless a `request_firmware_info` is sent.

**Comment by dealnat** [comment]
Hi, this is the expected behavior of the script. When method __on_connect() is called, we subscribe to the device attributes topic and wait for updates (OTA data stored as the shared attributes). But we can't know if the OTA data was changed when devices were offline, so we call method request_firmware_info(), where we read attributes of the device.
```   
def request_firmware_info(self):
        self.__request_id = self.__request_id + 1
        self.publish(f"v1/devices/me/attributes/request/{self.__request_id}", dumps({"sharedKeys": REQUIRED_SHARED_KEYS}))`
```
So, if you comment out request_firmware_info() method, the device can't know what actual OTA package was assigned to the device

**Comment by Remington-Hunter** [comment]
OK, I understand, thanks for your reply！ Thank you very much!
