### ISSUE TITLE
Fleet tracking system

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#11746]
I am using Thingsboard PE instance and want template for IoT fleet tracking System that is mentioned in use cases sections of Thingsboard. How do I get a template for what is mentioned under this use case 
https://thingsboard.io/fleet-tracking/

![image](https://github.com/user-attachments/assets/c95c577a-9c77-4541-bb30-b7bc02a0d79f)

I am interested in below features mentioned in this link - 
Here are the benefits of using the IoT Fleet Tracking Software:
- Remote condition monitoring.
- Improved visibility.
- Automation of tasks.
- Optimized routes.
- Enhanced safety.
- Cost savings.
- Tracking of individual parcels in vehicle with BLE tags. 

Need a solution template for same. 

The demo is very basic with only tracking information, rest of the features mentioned in website are not available.

**Comment by mykhailokornieiev** [comment]
Hi
You can get familiar with following page:
https://thingsboard.io/docs/pe/solution-templates/fleet-tracking/

**Comment by sjthings** [comment]
The dashboards and features mentioned in template does not include the features mentioned in description and shown in screenshots.

**Comment by mykhailokornieiev** [comment]
Indeed, it's a bit different from the one in our documentation. You can set it up or customize it by yourself.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
