### ISSUE TITLE
Hidden by default do not show when selected, only when a new data is send

### ISSUE THREAD

**Issue by Tamanar** [thingsboard/thingsboard#11754]
**Describe the bug**
I use a time series chart with many series with differents Y-axis.  
To not have all the data at the same time, I want most of the value to be hidden by default.
When I did this my charts were correctly hidden. But when I click on them to show them neither the new y-axis nor the time series appear. If I manually send new data (through mqtt) the y-axis and the time series appear.
It can be reproduced every time I launch the dashboard. 

**Your Server Environment**

  * Community 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: windows 10
* Browser firefox
* Version 130.0.1

**Your Device**

* Connectivity
  * MQTT
  * Send data through python script
* Device vendor and model

**To Reproduce**
1. Launch dashboard
2. Click on the hidden time-series
3. Time-series is not shown. /!\ should be seen
4. Send data
5. Time-series appear 

**Expected behavior**
I expect to see the data when I select the value that is hidden.

**Screenshots**
Tension is selected but do not appear
![tension do not appear](https://github.com/user-attachments/assets/c4f4cf04-233b-4a44-b907-239ad8843f91)
If I send data it appear:
![tension appear after sending data](https://github.com/user-attachments/assets/65c1f2ea-f45c-4e6f-a985-af7b20e7520e)

Here's the timeseries widget:
[time_series_chart_time_series_chart(3).json](https://github.com/user-attachments/files/17149101/time_series_chart_time_series_chart.3.json)

**Comment by mykhailokornieiev** [comment]
Hi
Please confirm that you are using TB version lower than 3.7. If yes, then this is a known bug that was fixed in 3.7.

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce it on P.E. 3.7
https://github.com/user-attachments/assets/ee2c06f2-3dab-48b3-a674-d257817a79c6
You can check your thingsboard version using http(s)://{thingsboard.host}/swagger-ui/ link or by enabling "show version" in White Labeling settings.
![image](https://github.com/user-attachments/assets/57bbace7-110a-44a4-b0b1-93b5f98736d6)
![image](https://github.com/user-attachments/assets/0a4a11e8-2c1a-4ae3-9523-4e0a35396866)

**Comment by Tamanar** [comment]
I am only with with 3.7 not 3.7PE
![image](https://github.com/user-attachments/assets/d453e050-84eb-437c-a136-4831361339b7)

**Comment by Tamanar** [comment]
Do you need the dashboard, the device, the device profil ?

**Comment by mykhailokornieiev** [comment]
Not sure how it will help. 
I've checked with your widget on 3.7 CE (like in your case). As far as I see, your hidden datasource is **tension**
Still, I was unable to reproduce it even that way.
https://github.com/user-attachments/assets/48175a8e-a9db-44b3-b906-b8ff87f9359c
Please describe how exactly you've sent this telemetry, how many datapoint for each datakey is displayed, so I can try to reproduce it with similar conditions.

**Comment by Tamanar** [comment]
I sent telemetry with a python script:
```python
import paho.mqtt.client as mqtt  # import library
import logging
import json
import time
import random
from datetime import datetime as dt
class mqttXXX:
    def __init__(self, MQTT_BROKER: str, MQTT_PORT: int):
        self.logger = logging.getLogger(self.__class__.__name__)
        self.client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
        self.username = ""
        self.MQTT_BROKER = MQTT_BROKER
        self.MQTT_PORT = MQTT_PORT

    def update_username(self, username: str):
        self.username = username
        self.client.username_pw_set(self.username)

    def __enter__(self):
        self.client.connect(self.MQTT_BROKER, self.MQTT_PORT)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.client.disconnect()

    def publish(self, mqtt_topic: str, data: dict):
        message = json.dumps(data)
        # message = "{temperature:98}"
        print(message)
        print(mqtt_topic)
        self.client.publish(MQTT_TOPIC, message, qos=1)
        time.sleep(0.4)
        logging.info(f"Sent message: {message}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    mqtt_XXX = mqttXXX(MQTT_BROKER, MQTT_PORT)
    mqtt_XXX.update_username(MQTT_USERNAME)
    with mqtt_XXX as mqttSensor:
        try:
            data = {
                "irradiance": random.randrange(100),
                "salissure": random.randrange(100),
                "puissance": random.randrange(100),
                "temp_ext": random.randrange(30),
                "temp_cell": random.randrange(45),
                "tension": random.randrange(0, 150),
                "courant": random.randrange(10),
                "puissance_crete": random.randrange(100),
                "battery_etat": random.randrange(100),
                "battery_consomation": random.randrange(0, 50),
                "production_electrique": random.randrange(200),
                "timestamp": dt.now().strftime("%m/%d/%Y, %H:%M:%S"),
            }
            mqttSensor.publish(MQTT_TOPIC, data)
            logging.info(f"Sent temperature data to topic {MQTT_TOPIC}")
        except Exception as e:
            logging.error(f"Error: {e}")
```
I have different dashboard for data for the day, week, month and total
If I take the time series for the week for instance I have 12 point. For each datakey (as it can be seen from the python script)

**Comment by Tamanar** [comment]
So I found something. "Tension" does appear correctly but after 30 minutes... Without any new data send

**Comment by Tamanar** [comment]
I tried with a customer on edge (but same computer), same issue. "tension" appear after 30 minutes

**Comment by mykhailokornieiev** [comment]
Hi
I'm still unable to reproduce such behavior, it loading not more that 30 seconds. 
Please describe your deployment in as much detail as possible.

**Comment by Tamanar** [comment]
We use an unmodified docker image from Thingsboard in 3.7 version
```yaml
tb:
    restart: always
    image: "thingsboard/tb-postgres"
    container_name: tb
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - {{ role_thingsboard_data_path }}:/data
      -       - {{ role_thingsboard_logs_path }}:/var/log/thingsboard
     ports:
      - 1883:1883
```
On a Debian 11 2 heart 8GB RAM

**Comment by mykhailokornieiev** [comment]
Please check in DevTools (F12) -> Networks how fast you get absent data via WebSockets
![image](https://github.com/user-attachments/assets/d3ff57cb-43a2-43e2-bc04-1b444ba47882)
If it provided faster then it displayed on widget, then please check this behavior on another browser / private tab or on more powerful machine

**Comment by Tamanar** [comment]
I don't know how to know if it's provided faster on the widget but here's what I got:
![image](https://github.com/user-attachments/assets/6b907c66-1aa7-4077-8ca0-f28dc9135027)
(I am an embedded engineer so I am not used to using High level interface)
I tried on Edge and Chrome: and the same behavior. On another computer the same behavior. 
I tried to recreate the time series and on the new one, the same issue

**Comment by Tamanar** [comment]
I send data every 15 minutes And I put a 0.4 seconds minimum delay (I saw if I reduced the time I receive nothings)

**Comment by mykhailokornieiev** [comment]
I meant how long it take to receive the hidden data via websockets as soon as you click to display it?

**Comment by Tamanar** [comment]
I'm sorry, but I don't understand what you're asking :/ . If I click on the hidden data, nothing changes in the WebSocket response. As I said before it takes 30 minutes to make the data appear.

**Comment by mykhailokornieiev** [comment]
Hi. Indeed, this was relevant for deprecated timeseries widgets. My bad. 
Today, I was finally able to reproduce this behavior on PE 3.7 and CE 3.7 (postgres-only deployment)
However, as soon as I tried it on Postgres + Cassandra - it's not reproducing at all.
Also, I've upgraded my CE 3.7 (postgres-only) to 3.8 and I also unable to reproduce it anymore. 
Please check it on the latest version (you can install it either as separate container, or upgrade current instance), but make sure you've made a backup of 3.7, so you will be able to make downgrade in case any issues occure

**Comment by Tamanar** [comment]
It's working in 3.8
