### ISSUE TITLE
Large relation Table in PostgreSQL Instance

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/thingsboard#11752]
Hi,

I have a PostgreSQL instance with a relatively small database. However, the relation table is quite large—around 4 GB out of the total 6 GB of the entire database.

Is this normal? Is there a way to clean it up? I believe my queries are slow because of this large size.

Thanks for your help!

**Comment by pon0marev** [comment]
Please attach the size of your tables. (\dt+)
Do you use custom relations for your devices? Do you generate relations in rule chains?
Try to clear the relations table using the command `vacuum full relation;` https://www.postgresql.org/docs/current/sql-vacuum.html
Note that the table will be frozen, and requests will not be received from the ThingsBoard service.

**Comment by Ataraxiall** [comment]
Hi,

My \dt+
`
thingsboard=# \dt+
                                             List of relations
 Schema |         Name         | Type  |  Owner   | Persistence | Access method |    Size    | Description
--------+----------------------+-------+----------+-------------+---------------+------------+-------------
 public | admin_settings       | table | postgres | permanent   | heap          | 176 kB     |
 public | alarm                | table | postgres | permanent   | heap          | 664 MB     |
 public | asset                | table | postgres | permanent   | heap          | 192 kB     |
 public | attribute_kv         | table | postgres | permanent   | heap          | 8560 kB    |
 public | audit_log            | table | postgres | permanent   | heap          | 1924 MB    |
 public | blob_entity          | table | postgres | permanent   | heap          | 8192 bytes |
 public | component_descriptor | table | postgres | permanent   | heap          | 136 kB     |
 public | converter            | table | postgres | permanent   | heap          | 8192 bytes |
 public | customer             | table | postgres | permanent   | heap          | 16 kB      |
 public | dashboard            | table | postgres | permanent   | heap          | 13 MB      |
 public | device               | table | postgres | permanent   | heap          | 80 kB      |
 public | device_credentials   | table | postgres | permanent   | heap          | 72 kB      |
 public | entity_group         | table | postgres | permanent   | heap          | 176 kB     |
 public | entity_view          | table | postgres | permanent   | heap          | 8192 bytes |
 public | event                | table | postgres | permanent   | heap          | 20 MB      |
 public | group_permission     | table | postgres | permanent   | heap          | 40 kB      |
 public | integration          | table | postgres | permanent   | heap          | 8192 bytes |
 public | relation             | table | postgres | permanent   | heap          | 1294 MB    |
 public | role                 | table | postgres | permanent   | heap          | 16 kB      |
 public | rule_chain           | table | postgres | permanent   | heap          | 16 kB      |
 public | rule_node            | table | postgres | permanent   | heap          | 48 kB      |
 public | scheduler_event      | table | postgres | permanent   | heap          | 8192 bytes |
 public | tb_user              | table | postgres | permanent   | heap          | 64 kB      |
 public | tenant               | table | postgres | permanent   | heap          | 16 kB      |
 public | ts_kv                | table | postgres | permanent   | heap          | 290 MB     |
 public | ts_kv_latest         | table | postgres | permanent   | heap          | 1192 kB    |
 public | user_credentials     | table | postgres | permanent   | heap          | 48 kB      |
 public | widget_type          | table | postgres | permanent   | heap          | 1104 kB    |
 public | widgets_bundle       | table | postgres | permanent   | heap          | 16 kB      |
(29 rows)
`
and this is the relation

`      relation_type       | total_rows
--------------------------+------------
 ALARM_ANY                |    2614747
 ALARM_UNACK              |    2614721
 ALARM_CLEARED_UNACK      |    2614379
 ALARM_CLEARED            |    2614369
 Contains                 |       1653
 Has parent               |        394
 ALARM_ACTIVE             |        355
 ALARM_ACTIVE_UNACK       |        353
 ENTITY_GROUP_USER        |        104
 Allowed                  |         95
 IsAdmin                  |         84
 ENTITY_GROUP_CUSTOMER    |         35
 ENTITY_GROUP_DEVICE      |         35
 ENTITY_GROUP_ENTITY_VIEW |         35
 ENTITY_GROUP_DASHBOARD   |         35
 ENTITY_GROUP_ASSET       |         35
 Success                  |         12
 True                     |          8
 Post attributes          |          4
 False                    |          2
 Created                  |          1
 Other                    |          1
 Post telemetry           |          1
 RPC Request from Device  |          1
 RPC Request to Device    |          1
 Cleared                  |          1
 Generate Report          |          1
 Activity Event           |          1
 Inactivity Event         |          1
(29 rows)
`

Thanks!

**Comment by pon0marev** [comment]
Your biggest tables:
``` 
Schema |         Name         | Type  |  Owner   | Persistence | Access method |    Size    | Description 
--------+----------------------+-------+----------+-------------+---------------+------------+-------------
 public | audit_log            | table | postgres | permanent   | heap          | 1924 MB    | 
 public | relation             | table | postgres | permanent   | heap          | 1294 MB    | 
 public | alarm                | table | postgres | permanent   | heap          | 664 MB     | 
```
Since the relations table has the largest number of alarm relations. You will need to review your logic for creating and assigning alarms.
```
relation_type              | total_rows
---------------------------+------------
ALARM_ANY                  |    2,614,747
ALARM_UNACK                |    2,614,721
ALARM_CLEARED_UNACK        |    2,614,379
ALARM_CLEARED              |    2,614,369
Contains                   |        1,653
```

**Comment by pon0marev** [comment]
Let me know if you were managed to improve the performance of your instance.

**Comment by pon0marev** [comment]
We want to inform you that we have closed your ticket as we have not received any updates on this issue. If you still have questions or encounter similar issues after upgrading to the latest version, please reopen this issue.
