### ISSUE TITLE
Change base URL

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1176]
I am not able to change the base URL of tb. 

Currently tb is running at https://MY_IP:8080, but I want to change to https://MY_IP/db:8080. 

I have tried to change it from settings - > general, but It makes no difference, while if I try to change it from the yml file (address: "${HTTP_BIND_ADDRESS:0.0.0.0}"), tomcat fails to start.

So my questing is, how can I change the base url?

**Comment by vparomskiy** [comment]
you can not do this via the thingsboard config file. But it is possible to do this using proxy (apache2, nginx, haproxy)

**Comment by trypzz** [comment]
Hi. Thingsboard doesn't have any parameters for customizing URL. For this case, you can try use HAproxy. Please visit link in KB below:

https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

**Comment by Philip2809** [comment]
> you can not do this via the thingsboard config file. But it is possible to do this using proxy (apache2, nginx, haproxy)

How exactly do you do this with a proxy?
