### ISSUE TITLE
dashboard resizes without notice

### ISSUE THREAD

**Issue by juanpgg-git** [thingsboard/thingsboard#11779]
* UI

**Description**
I completed a dashboard. After 1-2 days, I reopened it, and the widgets had resized themselves, so they don't fit the screen anymore. 
![image](https://github.com/user-attachments/assets/df5b5fd6-cb86-4cc4-82d6-a5b00cc8e0ae)

**Environment**

 * Browser: brave and chrome

**Comment by dealnat** [comment]
Closed as solution provided in #11800
