### ISSUE TITLE
Can not start nor upgrade Tb > 2.1

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1177]
So I am trying to upgrade tb to last release, but after a couple of days of testing, I still have to found a way to upgrade to a tb version higher than 2.1

I am running TB on a ubuntu 16.04 LTS server with java 8. What I have tried till now:

- Start from 2.1 than upgrade following [#1147](https://github.com/thingsboard/thingsboard/issues/1147#issue-369551127). The upgrade process does not even start. I get "ThingsBoard upgrade failed!" right after launching the upgrade script. No /var/log/thingsboard/install.log is created

- Directly install 2.1.1/2/3 same thing. I get "ThingsBoard upgrade failed!" right after launching the install script. No /var/log/thingsboard/install.log is created

- Start from 2.0.0 than upgrade following [#1147](https://github.com/thingsboard/thingsboard/issues/1147#issue-369551127). Again, the upgrade fails. 

I have also experimented every type of database combination cassandra/postgres/hsql. Every time same story.

I have also tried to directly execute 
`sudo su -s /bin/sh -c "java -cp /usr/share/thingsboard/bin/thingsboard.jar $JAVA_OPTS -Dloader.main=org.thingsboard.server.ThingsboardInstallApplication \
-Dinstall.data_dir=/usr/share/thingsboard/data \
-Dspring.jpa.hibernate.ddl-auto=none \
-Dinstall.upgrade=false \
 -Dlogging.config=/usr/share/thingsboard/bin/install/logback.xml \
org.springframework.boot.loader.PropertiesLauncher" "thingsboard"`

In this way, the installation script works, but then when I start tb service, it fails.

This is [thingsboard.out](https://pastebin.com/f84MaqH1) when i try to start tb 2.1.3

Any Idea? From tb 2.1.1 upward, there is some new dependencies or requirements?

**Comment by nrdmtt** [comment]
Here you can find [thingsboard.out](https://pastebin.com/f84MaqH1)

**Comment by cristianhumelnicu** [comment]
Try  to install the package maintainer's version for 2.1.1 , 2.1.2 and 2.1.3 
and after that to run:
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0

**Comment by vparomskiy** [comment]
@nrdmtt - please update the state of this ticket, were you able to resolve it using suggested commands?

**Comment by nrdmtt** [comment]
Starting from 2.1 I have installed 2.1.1 then 2.12 and finally 2.1.3. When I ran the upgrade script, the installation fails right away with "ThingsBoard upgrade failed!"
No log files are created

**Comment by vparomskiy** [comment]
Could you please provide your thingsboard.yml config file.
In most cases, not correctly merged config file is the reason of the problem.

**Comment by nrdmtt** [comment]
During the installation, I usually chose to install the new config file, and then I manually modify the DB configuration, since I am using postgres, as DB.

This is my .yml file for 2.1 (everything working ): https://pastebin.com/jfaPhh4g
This is the upgrading process: https://imgur.com/a/9Bxh9wx

**Comment by vparomskiy** [comment]
Check you new config file for this case:

**line:**
```
# PostgreSQL DAO Configuration
spring:
```
There should be no whitespaces before 'spring:' keyword. If there is a whitespace - remove it try to upgrade

**Comment by nrdmtt** [comment]
Same story. Still getting "ThingsBoard upgrade failed!"

Here the .yml file for TB 2.1.3 https://pastebin.com/qy8rCc94

**Comment by vparomskiy** [comment]
I've just validated upgrade from 2.1.1 to the 2.1.3 using your config file and it works for me.
The most interesting part is that no errors are shown in the console for your case.

Did you modify this file:
/usr/share/thingsboard/bin/install/logback.xml

**Comment by nrdmtt** [comment]
This is my logback.xml file: https://pastebin.com/qEzM0kb1 

I think the problem is some spurious configuration/installation file left some where during the various upgrades. Something related to the databases or the TB user. 

What are the steps to completely  purge TB from the system? I mean every single forlder/configuration/db file. Because, right now, I can not even start with a fresh 2.1.3 install.

**Comment by vparomskiy** [comment]
1. sudo apt-get purge thingsboard
2. Clear content of the '/usr/share/thingsboard/data/'
3. Drop thingsboard database is postgres ( drop database thingsboard; )

**Comment by cristianhumelnicu** [comment]
Try to make upgrade from 2.1 to 2.2 and 2.1.3 without merge/ keeping old
xml file.

**Comment by cristianhumelnicu** [comment]
Si I presume u have 2.1.1 installed
First upgrade to 2.1.2 running upgrade sh . U must to install new yml of
2.1.2

After that do same for upgrading from 2.12 ri 2.1.3 with new yml of 2.1.2

Is the way to make things works.

**Comment by cristianhumelnicu** [comment]
@nrdmtt 
Sorry for late answer ....so how to make 100%  2.1.3 to work
I presume,  u do not have TB installed on your computer ... 
1. First of all download from release thingsboard-2.1.1.deb and thingsboard-2.1.3.deb

2. Install 2.1.1 with:
sudo dpkg -i thingsboard-2.1.1.deb

3. Install demo app for TB with:  
sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

4. If all is ok install over 2.1.1  , 2.1.3 with:
sudo dpkg -i thingsboard-2.1.3.deb

5.  Make upgrade with:
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0
(exacty upper command line .. not with 2.1.1 or other )

6 Start TB with :
sudo systemctl start thingboard

Good luck!

**Comment by vparomskiy** [comment]
@nrdmtt was you able to successfully upgrade your instance?

**Comment by nrdmtt** [comment]
> @nrdmtt was you able to successfully upgrade your instance?

Yes, I finally successfully upgrade to 2.2, starting from 2.0. I couldn't use the upgrade.sh script itself, but I had to execute the command inside it manually. Do no ask me why, but using the script there was no way I could upgrade to anything > 2.0

**Comment by vparomskiy** [comment]
It is on final stage and will be available soon. But i can't give exact date
