### ISSUE TITLE
Dashboard，Click on the issue in the Entities hierarchy

### ISSUE THREAD

**Issue by xiaofeifeii** [thingsboard/thingsboard#11775]
The child node clicks continuously, and when the second click is made, the click event becomes invalid

**Comment by xiaofeifeii** [comment]
I opened the dialog by clicking on a child node in the tree structure, and when I closed the dialog, the dialog would not open when I clicked on the child node

**Comment by mykhailokornieiev** [comment]
Hi
Please describe your issue in as much detail as possible with full steps to reproduce

**Comment by xiaofeifeii** [comment]
1.I am using a Entities hierarch.
2.The issue can be reproduced during the widget operation by using either "Open new dashboard state in a separate dialog or in a popup window" or by calling widgetContext.actionsApi.openDashboardStateInSeparateDialog(stateId, params, title, false, 70, 100) in a custom action.
3.The problem occurs after opening a dialog from a child node of the tree, then closing the dialog and clicking on the same node again. At this point, the dialog cannot be opened, but the issue resolves after refreshing the webpage.

**Comment by mykhailokornieiev** [comment]
Hi
Thank you for the clarifications. I was able to reproduce this behavior and this is a known bug in Entities Hierarchy widget.
I've previously created a ticket and added it to the backlog for developers. Once the product team reviews this ticket, we’ll post an update on when this fix for this bug could be delivered. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by LukaszDuss** [comment]
I got same issue - is it prohibiting me to add support for double click using custom action. 
Is it possible @mykhailokornieiev for devs to add double click support in actions??
