### ISSUE TITLE
Scada behavior - Telemetry data return null

### ISSUE THREAD

**Issue by freeverbier** [thingsboard/thingsboard#11782]
We have telemetry with the key ‘Water pump status (0 OFF, 1 ON)’ which is linked to the attribute ‘Flow animation speed’ of the SCADA symbol ‘Long horizontal pipe’.

The value returned by the console.log is always null, whereas the telemetry oscillates between 0 and 1 and can be displayed graphically on a line chart.

**Your Server Environment**
https://demo.thingsboard.io
3.8.0

**Your Client Environment**
* OS: Windows 11
* Browser : Chrome (Edge)
* Version 129.0.2792.65

**Screenshots**
![image](https://github.com/user-attachments/assets/9fb00ef6-a2ef-45e5-9b0b-f8c9fd7aca45)

**Additional context**
Could the telemetry name with special characters cause this problem?

**Comment by AlexDoanTB** [comment]
@freeverbier it does not relate to SCADA symbol/widget/mode. Try not to use comas or colon signs in your keynames. It should work, then.
