### ISSUE TITLE
Telemetry with entitiesQuery in API REST

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#11789]
**Component**

 * Generic

**Description**
When I use entitiesQuery/find, the response contains latest:{...}, timeseries:{}. 
![image](https://github.com/user-attachments/assets/216fd4e7-c33d-4f3a-96e2-cb04e807a1c9)

I would like to know how to return telemetry in the timeseries part of the response. 
There is non example in the swagger UI. 
Thanks for your response

**Environment**

 * ThingsBoard: PE 3.5.1

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by devaskim** [comment]
@liotys I solve this task with reverse engineering)
1. Add some widget to dashboard with Entity Alias with Entities Query and several telemetry data keys.
2. Open Network tab in browser DevTools, enable WS (websocket) filter.
3. Reload browser page and look at WS traffic.
4. There will be full Entity Query with telemetry keys

**Comment by liotys** [comment]
Hi @devaskim , thanks for your answer. I tried your very interesting method, but I can't achieve my goal. 
When I use a widget with entities, I can only add latest telemetry. So in the api request it's "latestValues" wich is concerned and in the response the "timeseries" field is never populate. 
When I use a widget with timeseries, the api request use GET .../telemetry/ and not entitiesQuery/find.  
My initial need was to have timeseries for a list of assets result of a query. I hoped it was possible with a single entitiesQuery/find request (by populating the "timeseries" field),  but I guess I will have to combine the result of the entitiesQuery/find with some telemetry GET.

**Comment by liotys** [comment]
Thanks @sumin-denys for your ansmwer. I close the issue. 
Maybe you can remove the empty "timeseries" field from the response to this API request which is useless.
