### ISSUE TITLE
TCP Remote integration Not found

### ISSUE THREAD

**Issue by GabBilo12** [thingsboard/thingsboard#11806]
**Component**

 * Installation
 * Generic

**Description**
Hi there, I currently have thingsboard pe edge installed on my system, I added the TCP remote integration via the docs on the website, but when I start the integration I have this error : 
![image](https://github.com/user-attachments/assets/9d878d51-b944-4ebe-aa7a-8b48affd4090)
 Has anyone ever got this error, or how could I make it work

**Environment**

 * OS:  Debian 11
 * ThingsBoard: 3.6.2

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @GabBilo12,

Could you please provide information about your config/setup, such as:
- ThingsBoard/ThingsBoard Edge versions.
- What type of deployment have you used for the Remote Integration / Edge?
- Provide the screenshots of the Integration tab from your Edge instance.

Also, please add the log files for the following list of instances: 
- ThingsBoard.
- ThingsBoard Edge.
- Remote Integration.

**Comment by GabBilo12** [comment]
Hi @sumin-denys 
The integrations works fine when I ask it to send the data to thingsboard.cloud, but I need it to send the data to my edge instance device
- Thingsboard Edge Version : 3.6.5EDGEPE
- For my edge instance i'm using a docker/linux deployment, same thing for the integrations
- Here is the integfration config on the edge instance: 
![image](https://github.com/user-attachments/assets/8a517f8f-ccb6-404b-ad14-656bc5413a36)

Here is the integration config on docker : 
![image](https://github.com/user-attachments/assets/ea82814d-d376-4012-afe9-2ac13205e812)

Here is the log of the integration : 
![image](https://github.com/user-attachments/assets/d0a3d850-b44d-4168-a160-57c0e79c38c8)

Here is some of the edge instance logs : 
![image](https://github.com/user-attachments/assets/280f2857-74e3-4708-8b04-9849d2f981b0)

If you need anything more just tell me as soon as you can!
Thank you!

**Comment by GabBilo12** [comment]
Hi @sumin-denys ,
Also i get those logs when i have this configuration on the integration : 
![image](https://github.com/user-attachments/assets/2b034521-8687-4143-8c4b-d6a16f71e191)
![image](https://github.com/user-attachments/assets/89986ba2-dccc-4a2d-8b2e-125f0d8affd3)

**Comment by sumin-denys** [comment]
Hi @GabBilo12,

Could you try adjusting the **_RPC_PORT_** of your Remote Integration? It seems to be pointing to the default ThingsBoard port, which might be contributing to the issue. I recommend changing the port to **10560** (as per your integration configuration).

Additionally, could you please verify the **_RPC_HOST_** ? It should correctly point to the Edge Instance **IP** address, which should be accessible from the integration container.
