### ISSUE TITLE
dashboard invisible widgets

### ISSUE THREAD

**Issue by juanpgg-git** [thingsboard/thingsboard#11800]
**Describe the bug**
I have a dashboard with around 20 widgets. All of the budgets fit inside the dashboard. After 1-2 days when I enter the dashboard more than half of the widgets become invisible. If I select a widget and try to edit it, I can scroll down and see all of the widgets, but when I return to normal mode they disappear.  

**Your Server Environment*
This is using https://thingsboard.cloud

* OS: [e.g. iOS]
* Browser brave but is also happens on chrome 

**Expected behavior**
I expect all the widgets to be seen in the dashboard

**Screenshots**
![image](https://github.com/user-attachments/assets/7d0e337a-a6a8-43d2-a89d-0f4cb26b7b4f)
![image](https://github.com/user-attachments/assets/dbfe8fcc-f44e-40ab-adc2-042fb1089678)

**Comment by devaskim** [comment]
If those widgets are visible on mobile phone, looks like the appropriate widget configuration option became enabled for some reason.

**Comment by juanpgg-git** [comment]
Does that mean it is a bug?

**Comment by devaskim** [comment]
Seems like that, if you didn't do this on your own

**Comment by dealnat** [comment]
Hi, thingsboard's dashboard has 2 views - desktop and mobile; you can set parameters for displaying the widget on the desktop and the same for mobile. When you open some widget for editing, your dashboard has mobile view, when edit mode is closed dashboard displayed in the desktop mode. That's the reason why you can see some widgets while editing, but they disappear after editing mode is closed. 
![image](https://github.com/user-attachments/assets/5b3e44d1-13b4-4be7-a34a-0c12b2e24db1)
This parameters can be changed by user who has edit access to the dashboard, so it seems like some other user changed your widgets layout settings. You can observe manipulations with the dashboard by dashboard audit log.
![image](https://github.com/user-attachments/assets/0b5eb6c7-3b28-4931-93b3-331a9516d601)
The same conclusions for the #11779

**Comment by juanpgg-git** [comment]
Thanks a lot for the reply. 

I double-checked and all the widgets have that option deactivated, so they should appear. 

I decided to delete that dashboard and create it again. Here's my current layout
![image](https://github.com/user-attachments/assets/d54178f7-e999-491c-aba1-2ded5c1e926e)
If I decide to change the color to in the main edit, the epsilon widget disappears... it happens every time I try to update something in the dashboard layout

**Comment by dealnat** [comment]
Closed as the child issue #11828 is resolved
