### ISSUE TITLE
Adding attributes to profile /group operation

### ISSUE THREAD

**Issue by GreazlyA** [thingsboard/thingsboard#11808]
**Is your feature request related to a problem? Please describe.**
As system administrator running few thousands devices  I find it hard to change some attribute for all device . 

**Describe the solution you'd like**
It would be very helpful if when creating profile it will be able to create default attribute.when the device/asset is created it get the default attributes. those attributes can be changed specifically to device in the single device level. 
if i would like to change some attribute to all devices i can change it in the profile level and use "apply all" button to push the changes to the devices/assets.
basically the same idea of classes 

**Describe alternatives you've considered**
other option can be to put all of the devices/assets and make some "group operation" of CRUD operation to specific attribute 

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @GreazlyA,

Thank you for your report! 
I’ve already added to our backlog PROD-4847. I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
If you have any further questions or require clarification, please let me know.
