### ISSUE TITLE
unconfigured table component_descriptor

### ISSUE THREAD

**Issue by fengzhao33** [thingsboard/thingsboard#1181]
2018-10-23 16:38:37,033 [main] INFO  o.t.s.s.c.AnnotationComponentDiscoveryService - Processing scanned component: ComponentDescriptor(
type=ACTION, scope=TENANT, name=generator, clazz=org.thingsboard.rule.engine.debug.TbMsgGeneratorNode, configurationDescriptor=
{"nodeDefinition":
{"details":"Generates messages with configurable period. Javascript function used for message generation.",
"description":"Periodically generates messages",
"inEnabled":false,
"outEnabled":true,
"relationTypes":["Success","Failure"],
"customRelations":false,
"defaultConfiguration":
{"msgCount":0,"periodInSeconds":1,"originatorId":null,"originatorType":null,
"jsScript":"var msg = { temp: 42, humidity: 77 };\nvar metadata = { data: 40 };\nvar msgType = \"DebugMsg\";\n\nreturn { msg: msg, metadata: metadata, msgType: msgType };"
},
"uiResources":["static/rulenode/rulenode-core-config.js","static/rulenode/rulenode-core-config.css"],
"configDirective":"tbActionNodeGeneratorConfig",
"icon":"repeat",
"iconUrl":"",
"docUrl":""
}
}, actions=null)
2018-10-23 16:38:37,097 [main] ERROR o.t.s.s.c.AnnotationComponentDiscoveryService - Can't initialize component org.thingsboard.rule.engine.debug.TbMsgGeneratorNode, due to unconfigured table component_descriptor
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table component_descriptor

**Comment by Ultrazombie** [comment]
Hello @fengzhao33,
Is your problem still relevant to the latest ThingsBoard version?
