### ISSUE TITLE
As a customer, I need to share a dashboard created on the tenant login to the sub customer that the customer created

### ISSUE THREAD

**Issue by Mark-MV-Wizard** [thingsboard/thingsboard#11821]
* Generic

Tenant -> creates Customer (Distributer)
            Customer (Distributer)-> creates subcustomer (fleetowner)
                            subcustomer (fleetowner)-> creates a Sub-subcustomer(sub fleet owner)
                            
Problem stems from being unable to share dashboards from distributer to fleetowner and fleet owner to sub-fleetowner 

**Description**
As a Tenant, I have customers, and those customers have sub customers, and those sub customers have sub customers. 
I have created dashboards for each of the four levels.
As a tenant I shared the dashboards with the customers, but I'm unsure how to share the shared dashboard to the sub customers as the sub customers have to be created through the customers. I tried changing permissions, but I noticed that I can't share a dashboard that was shared as it gives permission issues.

![image](https://github.com/user-attachments/assets/7e4ffd75-ae78-4ca0-9df6-01a420b07b38)

**Environment**

 * OS:  windows 11
 * ThingsBoard: 3.6.4
 * Browser: edge

__________________________________________________________

**Comment by mykhailokornieiev** [comment]
Hi
It looks like I've already answered your question on the support portal, but I will duplicate it here.

> This can’t be done by design of Thingsboard. Only the customer/tenant who owns the dashboard can share it. However, you can share it with multiple customers. For this, you will need to do “Share“ procedure for each customer one-by-one.
> Customers can’t share dashboard group that was shared to them. Only owner of the group can share it. Sharing is not a providing of ownership, it’s just providing permissions to view this group.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by ezi-ocb** [comment]
Is this still the current state of art? It seems that for the tenant to be involved every time a customer wants to share a dashboard (group) with its sub-customer is not optimal (I am running a professional edition by the way)

**Comment by mykhailokornieiev** [comment]
Hi @ezi-ocb 
I've re-checked our backlog, and such a feature request was previously reopened. Currently, it is planned to be implemented in v4.4, however it can be changed
