### ISSUE TITLE
Upgrade from TB 3.7.0 to TB 3.8.0 failed 

### ISSUE THREAD

**Issue by michaelunterberger** [thingsboard/thingsboard#11827]
**Describe the bug**
if i update from TB PE 3.7.0 on a cent os 8 Server i got this  error (tried it multiple times):

sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.7.0
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.8.0PE)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService': Error creating bean with name 'sqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts': Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService': Error creating bean with name 'RuleChainDaoService': Unsatisfied dependency expressed through field 'ruleChainValidator': Error creating bean with name 'ruleChainDataValidator': Unsatisfied dependency expressed through field 'tenantService': Error creating bean with name 'TenantDaoService': Unsatisfied dependency expressed through field 'whiteLabelingService': Error creating bean with name 'baseWhiteLabelingService' defined in URL [jar:nested:/usr/share/thingsboard/bin/thingsboard.jar/!BOOT-INF/lib/dao-3.8.0PE.jar!/org/thingsboard/server/dao/wl/BaseWhiteLabelingService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'CustomerDaoService': Unsatisfied dependency expressed through field 'schedulerEventService': Error creating bean with name 'SchedulerEventDaoService': Unsatisfied dependency expressed through field 'edgeService': Error creating bean with name 'EdgeDaoService': Unsatisfied dependency expressed through field 'entityGroupService': Error creating bean with name 'EntityGroupDaoService': Unsatisfied dependency expressed through field 'cache': Error creating bean with name 'EntityGroupCache' defined in URL [jar:nested:/usr/share/thingsboard/bin/thingsboard.jar/!BOOT-INF/lib/dao-3.8.0PE.jar!/org/thingsboard/server/dao/group/EntityGroupCaffeineCache.class]: Failed to instantiate [org.thingsboard.server.dao.group.EntityGroupCaffeineCache]: Constructor threw exception
ThingsBoard upgrade failed!

**Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: rpm
  * ThingsBoard Version 3.7.0
  *  Professional Edition
  * OS Name and Version

**To Reproduce**
1.  sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.7.0
2. See error

**Comment by trikimiki** [comment]
hi!
this kind of error is usually caused by configuration error
since you were upgrading, I assume you might not installed newer version of `thingsboard.yml`:

> Package installer may ask you to merge your thingsboard configuration. It is preferred to use merge option to make sure that all your previous parameters will not be overwritten.

check your config directory at `/etc/thingsboard/conf/` - if it has a file with naming such as `thingsboard.yml.rpmnew`, double check and merge with your main `thingsboard.yml`

**Comment by michaelunterberger** [comment]
thank you, that was the problem!
