### ISSUE TITLE
Failed to Upgrade Thingsboard PE from 3.7.0 to 3.8.0: column te1_0.version does not exist

### ISSUE THREAD

**Issue by amarkevich** [thingsboard/thingsboard#11826]
**Describe the bug**
During Thingsboard PE upgrade from 3.7.0 to 3.8.0

**Your Server Environment**
* own setup
  * Deployment: microservices
  * Deployment type: k8s
  * ThingsBoard Version: 3.8.0
  * Professional Edition
  * OS Name and Version: GKE

**To Reproduce**
1. k8s-upgrade-tb.sh --fromVersion=3.7.0
2. See error

**Expected behavior**
migration finished successfuly

**Additional context**
[log-912f8e64-3a91-44fb-91ba-52a8bd76c56c.txt](https://github.com/user-attachments/files/17299399/log-912f8e64-3a91-44fb-91ba-52a8bd76c56c.txt)

**Comment by pon0marev** [comment]
The cause of the failure is most likely the oauth2_mobile and mobile_app tables. See the following query to upgrade the schema:
```
ALTER TABLE IF EXISTS oauth2_mobile RENAME TO mobile_app;
```
Did you try to run the upgrade multiple times or did this error happen the first time you tried?
So try the following:
1. Backup the current database.
2. Check data in the tables oauth2_mobile and mobile_app.
3. If mobile_app table already contains data, then rename oauth2_mobile table to oauth2_mobile_old and try to perform the upgrade once again.
4. If mobile_app table is empty, try to rename it to mobile_app_test and run the upgrade.

**Comment by amarkevich** [comment]
> ALTER TABLE IF EXISTS oauth2_mobile RENAME TO mobile_app;

Details: pq: relation "mobile_app" already exists

In version 3.8.0 tb-redis-configmap renamed to tb-cache-configmap - thats why k8s-install-tb.sh was called prior to migration

I tried `DROP TABLE mobile_app;` but 
`pq: cannot drop table mobile_app because other objects depend on it`

**Comment by pon0marev** [comment]
Try to delete the CONSTRAINT for the mobile_app table first and then delete it.
```
alter table mobile_app drop CONSTRAINT mobile_app_pkey;
alter table mobile_app drop CONSTRAINT mobile_app_unq_key;
DROP TABLE mobile_app;
```

**Comment by amarkevich** [comment]
```
ALTER TABLE IF EXISTS oauth2_mobile RENAME TO mobile_app;
ALTER TABLE IF EXISTS oauth2_domain RENAME TO domain;
ALTER TABLE IF EXISTS oauth2_registration RENAME TO oauth2_client;
```

Just destroy 3 new tables using 'cascade'; migration finished successfully. But need to re-create clients
