### ISSUE TITLE
Custom SMS provider as secondary factor for login

### ISSUE THREAD

**Issue by peterandthejetsons** [thingsboard/thingsboard#11837]
Hello!

I know that there are built-in SMS providers: SNS, Twilio, SMPP, but I would like to use a custom SMS provider that I can trigger with an API call and I can use this through the Rule Chain REST Api Call node. My question would be, could I use the individual SMS provider I want to use for logins?

If you need further information please let me know.

Thanks in advance!

Best regards,
Peter

**Comment by peterandthejetsons** [comment]
Dear @mykhailokornieiev!

Thank you very much for your answer! If I read correctly, SMPP is a p2p protocol that works with solutions that support SMPP, but what I'm looking for is a smooth integration with a computer HTTP API endpoint. If I think correctly, then what I want is not possible?

Thanks in advance!

Best regards,
Peter

**Comment by mykhailokornieiev** [comment]
> If I read correctly, SMPP is a p2p protocol that works with solutions that support SMPP, but what I'm looking for is a smooth integration with a computer HTTP API endpoint. 

I have no idea what do you mean, SMS notifications are working only with SMPP. 
Please clarify your request in as much detail as possible.

**Comment by peterandthejetsons** [comment]
Dear @mykhailokornieiev!

I would like to use an sms sending solution that can be used with REST API calls (GET, POST), just as in the case of Twilio, there is such an option (https://www.twilio.com/en-us/messaging/programmable-messaging-api) and the my question is, could I use the SMS gw solution with API for MFA with Thingsboard?

Thanks in advance!

Best regards,
Peter

**Comment by mykhailokornieiev** [comment]
Hi
This cannot be done by design of Thingsboard. You can use only SMPP for Thingsboard 2FA
