### ISSUE TITLE
Problems when saving timeseries in Rule Chain.

### ISSUE THREAD

**Issue by FrancoBisciglia** [thingsboard/thingsboard#11839]
**Component**

 * Rule Engine

**Description**

Greetings. I'm currently working with the Rule Engine from ThingsBoard. Additionally, I have a network composed by a Milesight LoRaWAN Gateway, model UG65, and a Milesight Valve Controller, model UC61. Also, I'm using the Gateway in Network Server Mode, and it has an embedded Node-Red application running. What I'm trying to do is the following:

1) Valve Controller sends valves states via LoRaWAN to the Gateway.

2) The Node-Red instance running in the Gateway re-formats and redirect the package to the ThingsBoard server via MQTT. In this case, the package is sent to the Gateway device that was previously created in the server.

3) Via a Rule Chain, redirect the package received by the Gateway device to the corresponding Valve Controller device, also previosuly created in the server.

Up to point 2, everything seems to work fine. However, when I try to implement point 3 in a Rule Chain, it doesn't work. The Rule Chain that I made is as follows:

![image](https://github.com/user-attachments/assets/992ef48b-3a04-4133-9d5f-c501e7895dea)

Where the Script Node has the following configuration:

![image](https://github.com/user-attachments/assets/c239dd92-c157-4e46-9033-4084bc38a70c)

As you can see, I just change the "deviceName" from the "Gateway device" to the "Valve Controller device", but this doesn't seem to work. Any ideas or suggestions?

Please let me know if more information is needed. Thank you all.

**Environment**

 * OS:  Windows 11
 * Browser: Chrome

**Comment by devaskim** [comment]
Use `Change Originator` node to change destination entity. Changing `deviceName` in metadata doesn't affect.

**Comment by FrancoBisciglia** [comment]
Greetings @devaskim . Thank you for your answer.

Unfortunately, I have already tried that, and it doesn't work either. For example, let's suppose I have an asset named "Valve Controller", and 2 devices named "Valve Controller A" and "Valve Controller B", which have a relation to that asset. If I put a "Change Originator" node with the following configuration:

![image](https://github.com/user-attachments/assets/16da7ec8-2e9a-4039-a1ed-13871d3e8b53)

What happens is that, when the Gateway gets a message and sends it to the server via MQTT, after passing through that node, the message gets **always** published in the first device, in this case, "Valve Controller A", even if "Valve Controller B" was the one that sent the message in the first place.

This is the reason of why I wanted to change the "deviceName", so I can distinguish between both devices. Any other suggestion?

**Comment by FrancoBisciglia** [comment]
Hi @devaskim .

Maybe I have an older version of ThingsBoard, because I don't have the "Entity by name pattern" option in the "New originator" field. These are the options that I have:

![image](https://github.com/user-attachments/assets/e24c1d5a-d122-4f95-8c16-5ad2cbec1252)

**Comment by devaskim** [comment]
At least in TB CE 3.7 this feature is present

**Comment by FrancoBisciglia** [comment]
Hi @devaskim .

Then it might be that, as I said, I have an older version. Appart from that alternative that you suggested, is there any other with which I can do the same thing?

**Comment by devaskim** [comment]
> is there any other with which I can do the same thing?

Nope.

**Comment by FrancoBisciglia** [comment]
Hi @devaskim 

I understand. Then, I will try to update the ThingsBoard version, so I can use that option. Thank you very much for your help.
