### ISSUE TITLE
Dynamically Change Entity Field Visibility in ThingsBoard Based on Customer Selection

### ISSUE THREAD

**Issue by neeraja87** [thingsboard/thingsboard#11834]
I'm working creating an entity table widget within a state. I want to dynamically change the entity fields based on the customer’s selection. For instance, I have three fields: EF1, EF2, and EF3, and two customers: A and B. When customer A accesses the dashboard state with the entity table, I want to display all three fields (EF1, EF2, EF3). However, for customer B, I want to hide EF2 and only show EF1 and EF3. 

Currently, I can manually hide fields by changing the "Default column visibility" to Hidden, but this affects all users, so all customers see only the visible columns. I considered using the widget context of the dashboard state to get the settings for default column visibility, but the structure for accessing these settings is complex. It results in a large array where the length is the product of the number of customers and entity fields. For two customers and three fields, this array has six entries, which makes it tedious to navigate and find the appropriate default column visibility for each customer. 

Is there a more efficient way to dynamically change the visibility of entity fields based on the customer? 

Any suggestions on leveraging the dashboard service or alternative approaches would be greatly appreciated!

**Comment by ssakharova** [comment]
Hello @neeraja87,

In that case, we can recommend using a separate dashboard for each customer user or consider using [Entity views](https://thingsboard.io/docs/pe/user-guide/entity-views/) in your configuration.

**Comment by s-kalaivanan** [comment]
As per our understanding Entity Views basically limit the visiblity of the information. But our requirement is one of UI. Is there a way to programmatically show/hide columns in an Entities table?

**Comment by ssakharova** [comment]
Closed due to inactivity.
