### ISSUE TITLE
Public Dashboard access-forbidden since Update 3.8.0

### ISSUE THREAD

**Issue by Tomi05-k** [thingsboard/thingsboard#11836]
**The bug**

My dashboards are no longer accessible with the public link after the update from 3.7.x -> 3.8.0. The dashboard group is set to public. 
Unfortunately, deactivating and activating the group did not help. Just like rebooting the ThingsBoard instance.

Another problem is that you can no longer log in to the mobile applications. It comes up after a second without authorization. 
It's probably all connected. 

What can I do?

Best regards Tom! 

Link public dashboard:
https://tjk-solutions.info/dashboard/27957510-5c75-11ef-be7b-1993b94d85af?publicId=a0905fa0-0137-11ef-ab83-73217647ce77

**Your Server Environment**

* own setup
  * Deployment type: deb
  * ThingsBoard Version: 3.8.0
  * Professional Edition

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: iOS, MacOS, Windows
* Browser: chrome, safari

**Smartphone (please complete the following information):**
* Device: iPhone 13
* OS: 18.0.1

**Screenshots**
Public Dashboard Error:
![IMG_0266](https://github.com/user-attachments/assets/2d13abfd-05be-45da-b851-29bbec8e3a6f)

App Problem:
![IMG_0267](https://github.com/user-attachments/assets/d3d8dac5-887c-4467-a1b2-1e84d9190110)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by loicgillioz** [comment]
I am also concerned and I have the same issue.

**Comment by WillieSpence** [comment]
Hi. I have the same issue since this morning. Unable to log into the Mobile Application it just immediately logs me out saying session expired or unauthorised! Please urgently assist.

**Comment by WillieSpence** [comment]
@Tomi05-k , which version of the mobile app are you using?

**Comment by Tomi05-k** [comment]
Should be the 1.2.0.

**Comment by sumin-denys** [comment]
Hi @Tomi05-k,

Thank you for your report!

This looks like a bug in a platform - I had already added to our backlog a ticket for a product team PROD-4711.
Once the product team reviews this ticket, we’ll post an update on when this fix for this bug could be delivered.
If you need to update the status of the prod ticket or have any further questions, please feel free to contact me.

**Comment by Tomi05-k** [comment]
Hello everyone,
a little update from me. I have updated the version to 3.8.1.
Public dashboards are now running again for the time being.

**Comment by sumin-denys** [comment]
Hi @Tomi05-k,

I am pleased to announce that this issue has been resolved in version 3.8.1.
