### ISSUE TITLE
Why does the server send RST to the device?

### ISSUE THREAD

**Issue by CUICUI03** [thingsboard/thingsboard#11831]
Description:

In the first step, the LWM2M device initiates registration to the server, the interaction process is normal, and the server also gives a correct ACK response **(Please note the ip and port number used for device registration here).**

![1](https://github.com/user-attachments/assets/6537b274-ef59-4c02-8fd3-bc45a59307a0)

In the second step, the LWM2M device reports data to the server again after it sleeps for 5 minutes. At this time, the packet log shows that the server does not process this uplink data and sends RST commands to the device**(Note that the device reassigns the ip and port number when it requests the base station to access the network after 5 minutes. When the device reports data to the server, the server does not process it but sends the RST command to the device.).**

![2](https://github.com/user-attachments/assets/b2d764ae-ac16-4167-b6f3-bf14b28c000e)

 Questions:
1. Why does the server send RST to the device?
2. The ip and port registered by the device to the base station will change at any time, how will the server handle it?

**Your Server Environment**

* [ThingsBoard Cloud](https://thingsboard.cloud)
  * ThingsBoard Version  V3.8.0

**Your Device**  869549041222833

**Additional context**
Please feel free to add any other context about the problem here.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by epalchenko** [comment]
I close this ticket due to inactivity.
