### ISSUE TITLE
Thingsboard Latest Release Images Not Available on DockerHub

### ISSUE THREAD

**Issue by nitinware** [thingsboard/thingsboard#1184]
Hi Team,

I am not seeing latest thingsboard releases docker images on DockerHub.

The latest release tag I see on DockerHub is 2.1.0 but all other release after that 2.1.1, 2.1.2, 2.1.3 are missing on DockerHub.

Can you please upload the latest Thingsboard Images on DockerHub, so that we can pull the latest images with all bug fixes and features.

Thanks,
Nitin Ware

**Comment by ashvayka** [comment]
We are significantly updating docker images in ThingsBoard v2.2.0. Stay tuned. I will add a link to blog post here.

**Comment by nitinware** [comment]
@ashvayka - thanks, for the quick response.

**Comment by tensojka** [comment]
@ashvayka Thingsboard v2.2.0 has been released on Thursday. Could you please link the blog post here? Thanks

**Comment by CooL16** [comment]
# The latest version of thingsboard uploaded on docker hub
https://hub.docker.com/_/thingsboard-pe-node
