### ISSUE TITLE
Connect Remote Device to Thingsboard on Premise

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#11840]
Is it possible to send data from a remote device on different network to thingsboard hosted on premise over internet, without any vpn connections.
If possible which protocol i should use, mqtt or http.
Is there any specific format for the url or broker link to use in such cases
@ashaforost @ashvayka

**Comment by sumin-denys** [comment]
Hi @mubashirp,

I believe one of these articles should help you with this question:
- [How to connect your device](https://thingsboard.io/docs/pe/getting-started-guides/connectivity/)
- [Device library](https://thingsboard.io/docs/pe/devices-library/)

If these articles are still not enough, please let me know

**Comment by mubashirp** [comment]
Hi @sumin-denys 

I refered the following articles,
I was able to connect from the raspberry pi to thingsboard when both are in the same network. I used both mqtt and http ( from node-red installed on pi) and was able to send data. But when i tried from a remote device ( from node-red) to send data to thingsboard on-premise its not working.
On the connection http url or mqtt command, i could see the private ip of  the device as a parameter, this ip will be only accessible from a local device (as it is private).
![image](https://github.com/user-attachments/assets/e5441c34-db78-46e7-a8cd-f1c49d5a74cc)

**Comment by mubashirp** [comment]
I am currently testing it on my windows computer connected to a wifi. There is a public ip, but i am not sure that it will be static.

**Comment by mubashirp** [comment]
> I am currently testing it on my windows computer connected to a wifi. There is a public ip, but i am not sure that it will be static.

@sumin-denys

**Comment by sumin-denys** [comment]
Hi @mubashirp,

In case your Windows computer doesn't have the public static IP, you aren't able to connect your device to ThingsBoard without a VPN option.

**Comment by mubashirp** [comment]
Do you have any suggestions for the server which i can use to host thingsboard on-premise, which also has a static public ip.

**Comment by mubashirp** [comment]
> Do you have any suggestions for the server which i can use to host thingsboard on-premise, which also has a static public ip.

@sumin-denys

**Comment by sumin-denys** [comment]
Hi @mubashirp,

If you want to connect IoT devices from anywhere in the world to your computer, it’s essential to set up a static IP address.

A static IP address is a permanent internet address that does not change every time you connect to the network. This ensures that IoT devices worldwide can consistently locate and communicate with your computer. 

Obtaining a static IP varies by country and ISP (Internet Service Provider). Some ISPs offer static IPs as part of their business plans or as an add-on service for an extra fee. It’s important to check with your specific ISP to understand the options for setting up a static IP.

Please contact your ISP so we can proceed with this issue.
