### ISSUE TITLE
custom menu for all customers is not working properly since update to 3.8

### ISSUE THREAD

**Issue by GreazlyA** [thingsboard/thingsboard#11852]
**Describe the bug**
when setting custom menu for all customer users it shows also **home/edge instances/settings/ ** on left side menu.
i had custom menu for all my customers that showed 2 items on the  left side menu before updating to 3.8 .

**Expected behavior**
when setting the new custom menu for all customers (2 last items)  it should show only the 2 items i have configured .

**Screenshots**
![after 3_8](https://github.com/user-attachments/assets/21227e09-17d2-4565-a810-419bda7525c5)

**Additional context**
Please feel free to add any other context about the problem here.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by GreazlyA** [comment]
i have noticed that for new customers it works as accepted but for existing customers it doesn't .

**Comment by sumin-denys** [comment]
Hi @GreazlyA,

Please provide the settings for your custom menu, such as:

- Custom menu config: `White labeling -> Custom menu -> Name of your custom menu`
- Custom menu assignees: `White labeling -> Custom menu -> Manage custom menu assignees`
> [!IMPORTANT]
> The only menu item you cannot hide is “Home”.

Please take a look to this article [Custom menu](https://thingsboard.io/docs/pe/user-guide/custom-menu/), i guess it may help you with this issue.

**Comment by GreazlyA** [comment]
Hi in bold:
White labeling -> Custom menu -> **End user**
White labeling -> Custom menu -> **all customer users**

**Comment by sumin-denys** [comment]
@GreazlyA,

Please add the screenshot of the config as the following:

![image](https://github.com/user-attachments/assets/070a180b-cdf6-4e97-ae4c-0e06dc5ce23c)

**Comment by GreazlyA** [comment]
![for tb git](https://github.com/user-attachments/assets/9845d2ea-3c57-42ce-a144-bcd3fba01ae2)

**Comment by GreazlyA** [comment]
Hi,
i found workaround ,only when deleting for the DB the custom_menu in the customer table  and then used the custom menu features it works as aspect. 
but still it is not compatible with 3.7 when customMenu is defined.

**Comment by omahurin** [comment]
Hello,
Update regarding PROD-4866. This issue is not a bug. After investigation, in the two similar cases, it was discovered that the customer had his own custom menu, which is why tenant one was not applied.
