### ISSUE TITLE
Urgent issue  ---》Why does the server send RST to the device?

### ISSUE THREAD

**Issue by CUICUI03** [thingsboard/thingsboard#11855]
Description:

In the first step, the LWM2M device initiates registration to the server, the interaction process is normal, and the server also gives a correct ACK response (Please note the ip and port number used for device registration here).

![1](https://github.com/user-attachments/assets/bb631081-4905-4992-8e86-515a308c0db7)

In the second step, the LWM2M device reports data to the server again after it sleeps for 5 minutes. At this time, the packet log shows that the server does not process this uplink data and sends RST commands to the device**(Note that the device reassigns the ip and port number when it requests the base station to access the network after 5 minutes. When the device reports data to the server, the server does not process it but sends the RST command to the device.).**

![2](https://github.com/user-attachments/assets/e6c0363d-34ab-4782-bb62-0b8da9fd26a1)

Questions:

1.Why does the server send RST to the device?
2.The ip and port registered by the device to the base station will change at any time, how will the server handle it?
Your Server Environment

[ThingsBoard Cloud](https://thingsboard.cloud/)
ThingsBoard Version V3.8.0
Your Device 869549041222833

**Comment by epalchenko** [comment]
close as a duplicate to https://github.com/thingsboard/thingsboard/issues/11831
