### ISSUE TITLE
Rule chain : How to update alarm, without changing severity level ? (How to get current alarm severity level ?)

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#11864]
**Component**

 * Rule Engine

**Description**
I want to update an alarm detail, without changing the alarm severity level.
How to get previous (current) alarm severity level ?  
How to keep the same alarm severity level ?

I use an alarm severity pattern field using templatization (`${alarmSeverity}`) when I want to update severity level.
But sometimes I just want to update my alarm `details` info, without changing alarm severity level : in that case I don't set the `metadata.alarmSeverity` in my message.

* I was thinking if the alarm severity pattern templatization is not found, and alarm already exist, it will be kept "the same"... it's not the case : I get an error if the alarm severity pattern value is not found.
* Then I try to keep the previous severity level in my alarm "details"... but when I try to retreive it from my `metadata.prevAlarmDetails`, and affect it to my alarm severity templatization pattern in the "details" function generator : it doesn't work.
It seems that the node check for the alarm pattern templatization "before" executing the "details" function.

Thank you for your help.

My rule chain principle :

![image](https://github.com/user-attachments/assets/e4b46b8b-6d6b-4c8e-8ebd-7445b97eac65)

createSeverity node :  
```
var newMeta = metadata;
var alarmLevel = metadata.alarmState;

switch (alarmLevel) {
    case 1:
        newMeta.alarmSeverity = "WARNING";
        break;
    case 2:
        newMeta.alarmSeverity = "MAJOR";
        break;
    case 3:
        newMeta.alarmSeverity = "CRITICAL";
        break;
    default:
        // Keep previous severity level
        break;
}

return {
    msg: msg,
    metadata: newMeta,
    msgType: msgType
};
```

creat alarm node :  
![image](https://github.com/user-attachments/assets/4eceddb7-a1c1-4ce2-9006-68bd5e3fa1b5)

node error if alarm severity is not found :  
```
java.lang.RuntimeException: Used incorrect pattern or Alarm Severity not included in message
	at org.thingsboard.rule.engine.action.TbCreateAlarmNode.processAlarmSeverity(TbCreateAlarmNode.java:225)
	at org.thingsboard.rule.engine.action.TbCreateAlarmNode.lambda$updateAlarm$2(TbCreateAlarmNode.java:188)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:254)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:244)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:125)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Environment**

 * OS:  Windows
 * ThingsBoard: lastest Professional Cloud
 * Browser: Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. I'm unsure what you want to achieve, but I've tried your logic and see no issues.
![image](https://github.com/user-attachments/assets/70def098-a073-46ca-879a-7a3ff1e472f4)
![image](https://github.com/user-attachments/assets/d3b1841d-28d9-40b1-a193-5fbb2e85e674)
Your severity won't be updated if there is no change of severity in your messages

**Comment by GregAscolab** [comment]
Ok I give you more details tomorrow...

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by GregAscolab** [comment]
Did you take my proposal in count ?

> My main proposal : change behavior of the node :  

> If the severity pattern is not found AND there is an existing alarm : keep same severity level as existing alarm.
> Else generate a failure (impossible to create an alarm without severity level)

**Comment by mykhailokornieiev** [comment]
Hi. Currently, a global redesign of the alarm functionality and its management is underway. At this time, we cannot say whether the functionality you specified will be available

**Comment by GregAscolab** [comment]
FYI:
I finaly change my conception... and 90% of the alarm logic is done into my device embedded software.
It send directly the telemetry {"alarmName": "alarmSeverity"}, so I always update the alarm severity all the time : to increase or decrease the severity.

But I still use the "details" method to store the max severity level I reach (and other info), in details object.

br
