### ISSUE TITLE
Impossible to enter the '$' character in "originator attributs" node !

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#11865]
**Describe the bug**
Impossible to enter the '$' character in the attributs form fields :  
* Client
* Shared
* Server
* Latest telemetry

**So it impossible to enter templatization `$[msgKeyName]` or `${metadataKeyName}` !!!**

Tips : In order to be able to enter the templatization value, I need to write it somewhere and copy/paste in the field !!!

**Your Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)
Pro version Cloud Prototype
3.7.0.9PAAS

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome
* Version: 129.0.6668.90

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. Go to rule chain
2. Add "originator attributs" node
3. Try to enter '$' char in form field
4. See error : '$' char is not display/take in count

**Expected behavior**
it has to be possible to enter '$' char to make templatization works.

**Screenshots**
**Note: In this screenshot : the `${alarmDurationName}` has been enterred using copy/paste !!!**
![image](https://github.com/user-attachments/assets/23beebc7-2fb1-4422-9c77-24c2d7e17234)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. $[msgKeyName] format is not relevant for the Originator Attributes rule node, if your key name is alarmDurationName then use just it, without $[]. Usage of special characters in attribute/telemetry names is highly not recommended

**Comment by mykhailokornieiev** [comment]
Even if you want to use templatization from previous rule node, then I'm unable to reproduce this behavior
![image](https://github.com/user-attachments/assets/932f2007-9ddc-4340-b401-09373060c508)

**Comment by GregAscolab** [comment]
Hum... it seems to work with :
Firefox 131.0.3

Not with my Chrome Version 129.0.6668.90 (Build officiel) (64 bits)

**Comment by GregAscolab** [comment]
> Hi. `$[msgKeyName]` format is not relevant for the Originator Attributes rule node, if your key name is alarmDurationName then use just it, without $[]. Usage of special characters in attribute/telemetry names is highly not recommended

I'm not agree with you...
I need to use templatization to get the right attribut name ;-)  
I think you add this ability especially for that !

In my case the name of the telemetry value I need to get, is in `metadata.alarmDurationName` ;-) 

By the way :  
Templatization works if I can entered the '$' char... not my case in my Windows Chrome navigator...

**Comment by mykhailokornieiev** [comment]
> I'm not agree with you...
> I need to use templatization to get the right attribut name ;-)
> I think you add this ability especially for that !

I probably misunderstood your request. In case of templatization, it will use attribute/telemetry **value**, not the key.

> Templatization works if I can entered the '$' char... not my case in my Windows Chrome navigator...

Try to check it in private mode without any extensions enabled.

**Comment by GregAscolab** [comment]
Tested in private mode, no extension : Pb still here...
Tested to change Chrome language : pb still here...
Don't know why...

The $ key have a strange behavior : when pressed, it act like I press "tab". It create en attribut entry.
But the $ char works well in the same form, in `Name` or `Rule Node Description` fields.

**Comment by mykhailokornieiev** [comment]
Still unable to reproduce this behavior for both 3.7 and thingsboard.cloud (3.8):
![image](https://github.com/user-attachments/assets/3656bf80-5491-44ae-8a08-7053e1c69a0b)
![image](https://github.com/user-attachments/assets/1d91dbbb-81f5-4d20-b8aa-0356e0c06d86)

**Comment by mykhailokornieiev** [comment]
Please, try to check it on another machine without any Chrome extensions.

**Comment by GregAscolab** [comment]
Here are my tests results :

Problem with :  
Laptop 1 (Mine) : Windows 10 "French" + Chrome Version 129.0.6668.90 (Build officiel) (64 bits)
Laptop 1 : Windows 10 "French" + Chrome Version 129.0.6668.101 (Build officiel) (64 bits)
Laptop 2 : Windows 10 "French" + Chrome Version 129.0.6668.100 (Build officiel) (64 bits)
Laptop 2 : Windows 10 "French" + Chrome Version 129.0.6668.101 (Build officiel) (64 bits)

No problems with :  
Laptop 1 (Mine) : Windows 10 "French" + Firefox Version 131.0.3 (64 bits)
Laptop 3 : Windows 11 "French" + Chrome Version 129.0.6668.80 (Build officiel) (64 bits)
Laptop 3 : Windows 11 "French" + Chrome Version 129.0.6668.101 (Build officiel) (64 bits)



According to that it's maybe somethig related to software version... environment.
I let you choose to close or not this issue :-)

Thank you for your feedback.
According futur tests on other computer I will complete this issue.

I will continue to use the copy/paste workaround... very strange...
