### ISSUE TITLE
"Repository not found" error when trying to configure Version control

### ISSUE THREAD

**Issue by spiricn** [thingsboard/thingsboard#11869]
**Describe the bug**
Attempted to configure Version control with my Bitbucket repository and keep receiving the following error message when clicking save:

"repository not found: /tmp/repositories/bcd8c720-87d2-11ef-aa21-a154cb8e4b37"

Check access passes ok with the following message "Repository access successfully verified!"

**Your Server Environment**
* own setup:
  * Deployment: microservices
  * Deployment type: docker-compose
  * ThingsBoard Version: 3.8.0
  * Community
  * OS Name and Version: 22.04.1-Ubuntu

**Your Client Environment**
**Desktop (please complete the following information):**

* OS:  Windows
* Browser Chrome

**To Reproduce**
1. Go to 'Version control"
2. Input paramters
3. Click "Save"
5. See error

**Expected behavior**
Error does not get thrown and version control is configured successfully

**Screenshots**
![image](https://github.com/user-attachments/assets/80809edc-cb46-4e2c-a3ec-b057c2b787f1)

** Additional Context**

Checking the logs via `cat /var/log/thingsboard/thingsboard.log | grep ERROR` I'm not seeing an errors(or any other messages) which would indicate a problem

Attaching to the docker container and inspecting its file system I can see that the `/tmp/repositories/bcd8c720-87d2-11ef-aa21-a154cb8e4b37` is created; however it's empty

**Comment by mykhailokornieiev** [comment]
Hi. Change your Bitbucket repository link from SSH format to HTTP

**Comment by spiricn** [comment]
Hello @mykhailokornieiev , thanks for the suggestion; unfortunately that didn't help.

Actually my first attempt was using HTTP along with an access token. When that failed, I then attempted to use SSH with a private key which also didn't work

**Comment by mykhailokornieiev** [comment]
Hi
Thank you for the clarification. It turned out that it was a bug on 3.8 version and 3.8.1 has a hot fix for it.
For a quick fix on 3.8, you need to delete your directory with repositories. Either /tmp/repositories or specific UUID directory. 
After it, try to add you repository in Thingsboard Version Control again.

**Comment by spiricn** [comment]
@mykhailokornieiev Updating to 3.8.1 fixed it, thank you for your support !

**Comment by egomezsafeloc** [comment]
Hi, I am trying to use a github token to log in. Do I need to fill the `Username` field with some dummy value? I am getting an error when leaving it empty:

```
[repo name]: not authorized
```
