### ISSUE TITLE
When using the Java rest client to call the DevicesInfos endpoint the URL of Devices is used

### ISSUE THREAD

**Issue by Wolframfriele** [thingsboard/thingsboard#11875]
**Describe the bug**
While attempting to the make a call to the `/api/customer/{customerId}/deviceInfos` endpoint with the Java Thingsboard Rest Client with the `getCustomerDeviceInfos` method. None of the returned `DeviceInfo` objects had any data for any of the extra 4 fields that the `DeviceInfo` object has over the `Device` object (customerTitle, customerIsPublic, deviceProfileName and active).

After looking at the source code this made sense, the `getCustomerDeviceInfos` method does a call to the `/api/customer/{customerId}/devices` endpoint. See[ the line in the source code](https://github.com/thingsboard/thingsboard/blob/c88a05ef5cec9024a1014e9a026b2da5b488ce59/rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java#L1403), my expectation is that this should be the `/api/customer/{customerId}/deviceInfos` endpoint.

**Your Server Environment**
Thingsboard Community not sure what version

**Your Client Environment**
"org.thingsboard:rest-client", version = "3.7.0" in Java 17

* Connectivity
HTTP
  

**To Reproduce**

1. Add a device under a customer, send telemetry data to the device so the state becomes active.
2. Then use the RestClient.getCustomerDeviceInfos() method with the correct query to get the devices from the selected customer. 
3. Print the results of the current query to standard out.
4. See the customerTitle, customerIsPublic, deviceProfileName and active field, they are all null or false.

**Expected behavior**
The expected behaviour is to get the data from those fields, since a call to the same endpoint in the swagger-ui does yield the correct information.

**Additional context**
This is probably an easy fix, just making sure I'm not missing context for why this url is used.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @Wolframfriele,

Thank you for your report! 
This issue has been confirmed. I've added this request to our backlog PROD-4742. 

I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.

If you have any further questions or require clarification, please let me know.
