### ISSUE TITLE
thingsboard/tb-postgres: using thingsboard.yml to customize `transport.activity.reporting_strategy`

### ISSUE THREAD

**Issue by rretanubun** [thingsboard/thingsboard#11876]
**Component**
 * Installation

**Description**
- I am using [thingsboard/tb-postgres ](https://hub.docker.com/r/thingsboard/tb-postgres) v 3.7.0 (and another installation on v3.6.0)
- I am following this guide for [Device Connectivity](https://thingsboard.io/docs/user-guide/device-connectivity-status/#configuration) and wanted to experiment with changing `transport.activity.reporting_strategy` from the default of `LAST` to `FIRST_AND_LAST`.
- I am not sure how to do so (do I mount it in the docker container like `data` and `logs`, if so to which `internal path?`) 
- reading [this guide](https://thingsboard.io/docs/user-guide/install/config/) seems to indicate that `thingsboard.yml` is no longer relevant and we now just use `docker environment variables` for everything? -- do I get this right?

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.7.0
 * Browser: N/A

**Comment by devaskim** [comment]
Use docker env variable `TB_TRANSPORT_ACTIVITY_REPORTING_STRATEGY` with `FIRST_AND_LAST` value.

Got the name of variable from [here ](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L974)

**Comment by rretanubun** [comment]
@devaskim : Thanks for confirming.
