### ISSUE TITLE
LWM2M devices intergation not easy

### ISSUE THREAD

**Issue by benjaminferrier** [thingsboard/thingsboard#11884]
**Is your feature request related to a problem? Please describe.**

The LWM2M device provisioning experience on Thingsboard is not so user friendly when we are used to others LWM2M platforms.

1. Particularly because it is not so easy to complete manually the "LWM2M Models" in the device profile (instances objects with their correct object version). It is quite long and source of error. This is frustrating especially because this step is not necessary on others LWM2M platforms (Objects and Object Instances are retrieved during the register operation and update during update request if necessary and then autocompleted). Moreover some LWM2M devices could have dynamic resources that are created/deleted, particularly devices with [LwM2M Gateway object 25](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/25.xml) but not only.
2. There is no ready for use LWM2M dashboard to manage LWM2M devices and operations (observe, read, write) like the others platforms (for example, the [leshan demo server](https://leshan.eclipseprojects.io/). It is needed to use RPC widgets and/or custom widget which make LWM2M device integration not so user friendly.
3. The LWM2M queue mode devices can be managed using persistent RPC. But persistent RPC is not activated by default on Thingsboard for LWM2M queue mode devices. 
4. OTA Update seems not working for LWM2M queue mode devices without making some rule chains level modifications for making persistent RPC on OTA Update.
5. It seems that observation parameters are not reloaded after a LWM2M devices restart (and have lost its observation config)

**Describe the solution you'd like**

1. I have no suggestion about how to manage dynamic autocomplete LWM2M models. If the LWM2M models were managed at a device level instead of a device profile level, maybe it could make easier to add the feature of autocomplete objects and instances list of each device. But this seems a big change on Thingboard LWM2M API.
2. A ready to use LWM2M dashboard (inspired of leshan demo sever) could be great
3. Default persistent RPC mode for RPC commands and FUOTA for LWM2M queue mode devices could be great
4. An option (at a device or device profile level) that could enable observation requests resend and notification attributes reload on devices after a new registration request could be great!

Except for LWM2M :-), I find Thingsboard great to use ! Thank you for all your work !

BRs

**Comment by AlexDoanTB** [comment]
@benjaminferrier Thank you for your suggestions. 
1. This way, ThingsBoard (as a multi-tenant platform, let's keep it in mind) can handle custom/desired resource model versions. 
1.1. The Device Profile module supports dynamic configuration.  
2. This is a nice-to-have add-on, probably. Let us finish with the Gateways dashboard. We'll take the request in consideration. After the internal discussion, we will update this thread about the decision on whether to raise a PROD ticket for LwM2M admin dashboard. We need a community demand to prioritise the request. 
3. Persistent RPC for queue mode as a configurable option. @epalchenko  please add a PROD ticket. 
4. This one is unclear. The check is done upon 1st connect/re-connect to the platform.
But if you need it dynamically, you must use Observe. What kind of modifications are you referring to?     
5. Details, please.

**Comment by epalchenko** [comment]
Closed due to inactivity
