### ISSUE TITLE
Retreive LwM2M path via Rule Chain

### ISSUE THREAD

**Issue by LennartMol** [thingsboard/thingsboard#11882]
**Component**

 * Generic

**Description**
I am working with the LwM2M implementation of ThingsBoard.
In our organisation we use another platform called Tartabit as an LwM2M server, but we want to switch.
In Tartabit we use the LwM2M path structure to send information about the devices to our own API.

When a resource is observed in TB, the notify data you get from the device is shown by the attribute key in the following format:
For example, the device object 3 (LwM2M OMA standard) will provide the time every 5 seconds in resource 13.
```
{
    "currentTime": "Oct 16, 2024 13:36 PM",
    "modelNumber": "Model 500"
}
``` 

Is it possible to get the path info via the Rule Chain?
So I can see this message comes from "/3/0/13" so I can forward it to our API?
We use the path structure in our API, so if it is not possible ThingsBoard might not be the right solution for us.

**Environment**

 * OS:  Windows 10  version 10.0.19045 Build 19045
 * ThingsBoard: 3.8.1 via Docker compose
 * Browser: Firefox 131.0.3

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by epalchenko** [comment]
Hello,
When you start observing on the object ‘Device #3_1.2’ - Resource ‘#13 Current time’, you see this message in the rule chain:
![image](https://github.com/user-attachments/assets/b424a0c0-ff2d-4add-aba9-4130068e4bcb)
![image](https://github.com/user-attachments/assets/d718bfce-c4da-4ac9-943d-79a6f073b8f9)
Then, every 5 seconds, the platform will receive the following message:
![Screenshot from 2024-10-29 17-39-34](https://github.com/user-attachments/assets/498dd6fc-0ee2-4e51-93aa-3464a192a1e9)
You can build your custom logic on these notifications to send information about devices to your own API

**Comment by epalchenko** [comment]
Closed due to inactivity
