### ISSUE TITLE
LWM2M 1.1 "send operation" not working without pre-configuring an "observation operation"

### ISSUE THREAD

**Issue by benjaminferrier** [thingsboard/thingsboard#11883]
**Description**

Hello, 
I am trying to connect a [LWM2M 1.1 Adeunis CS](https://www.adeunis.com/en/produit/comfort-serenity-temperature-humidity-co2-voc/) device with its [send operation](http://openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-6-0-646-Send-Operation) mode. After some tests, it seems that the send operation is received by Thingsboard only works for resources that are observed. Is the send operation available on Thingsboard for resources that are not observed?

**To Reproduce**

1. Configure the device profile used by the LWM2M device with all the instances objects of the device. I do not configure observation on the temperature on that profile.
2. Start the device with the sending mode configured to send a temperature every 5 minutes
3. Temperatures are not received by Thingsboard
4. Then configure an observation operation on the temperature resource on the device profile
5. Restart the device so that observation attributes are erased on device side (and the sending mode configured to send a temperature every 5 minutes is still active).
6. Temperatures are well received by Thingsboard every 5 minutes

**Environment**

 * ThingsBoard: v3.7.0 Pro

**Comment by AlexDoanTB** [comment]
@benjaminferrier _observe_ is not necessary to receive attributes or telemetry. 
If you send time series data with a time interval of at least 1 second, _observe_ is not required: you get confirmation and the value. But you have to tell the TB platform how to map values (check Telemetry or Attributes in Profile). 
If smth changes on the device but you do not have Observation, this info will not be accepted and logged. 
Observe = subscription to all changes on a device.

**Comment by epalchenko** [comment]
Closed due to inactivity
