### ISSUE TITLE
chirpstack v4 decoder error

### ISSUE THREAD

**Issue by niho06** [thingsboard/thingsboard#11895]
**Describe the bug**

**Your Server Environment**

* [ThingsBoard Cloud](https://thingsboard.cloud)
* own setup
  * Deployment: monolith or microservices
  * Deployment type: deb, rpm, exe, docker-compose, k8s, ami
  * ThingsBoard Version 3.8
  * Community or Professional Edition cloud

I am using the decoder that comes with Chirptack integration. I have not made any changes and it has been working for 1 month without any problems, but out of nowhere it sends an error when decoding data sent via Chirptack V4.

![image](https://github.com/user-attachments/assets/ce491903-3df9-47c4-8d80-dc8311c5ea19)

![image](https://github.com/user-attachments/assets/c6849750-2900-4047-81f3-0f00ff95047d)

`java.util.concurrent.ExecutionException: org.thingsboard.script.api.TbScriptException: [Error: Invalid statement: input[i]]
[Near : {... var channel_type = input[i]; ....}]
                                ^
[Line: 34, Column: 32]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:594)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:573)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:321)
	at org.thingsboard.integration.http.chirpstack.ChirpStackIntegration.doProcess(ChirpStackIntegration.java:112)
	at org.thingsboard.integration.http.chirpstack.ChirpStackIntegration.doProcess(ChirpStackIntegration.java:66)
	at org.thingsboard.integration.http.AbstractHttpIntegration.process(AbstractHttpIntegration.java:55)
	at org.thingsboard.integration.http.AbstractHttpIntegration.process(AbstractHttpIntegration.java:47)
	at org.thingsboard.integration.api.controller.AbstractIntegrationControllerApi.lambda$process$0(AbstractIntegrationControllerApi.java:51)
	at org.thingsboard.integration.api.controller.AbstractIntegrationControllerApi.lambda$process$1(AbstractIntegrationControllerApi.java:64)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:55)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.thingsboard.script.api.TbScriptException: [Error: Invalid statement: input[i]]
[Near : {... var channel_type = input[i]; ....}]
                                ^
[Line: 34, Column: 32]
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFunction$8(DefaultTbelInvokeService.java:234)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	... 6 more
Caused by: [Error: Invalid statement: input[i]]
[Near : {... var channel_type = input[i]; ....}]
                                ^
[Line: 34, Column: 32]
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:192)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:98)
	at org.mvel2.ast.WhileNode.getReducedValueAccelerated(WhileNode.java:60)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:102)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:98)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:102)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.ast.Function.call(Function.java:181)
	at org.mvel2.ast.PrototypalFunctionInstance.call(PrototypalFunctionInstance.java:19)
	at org.mvel2.optimizers.impl.refl.nodes.FunctionAccessor.getValue(FunctionAccessor.java:50)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:111)...[truncated 667 symbols]`

decorder use:

`var data = decodeToJson(payload);
var deviceName = data.deviceInfo.deviceName;
var deviceType = data.deviceInfo.deviceProfileName;
var groupName = 'IAQ devices';
// var customerName = 'Customer A';
// use assetName and assetType instead of deviceName and deviceType
// to automatically create assets instead of devices.
// var assetName = 'Asset A';
// var assetType = 'building';

// If you want to parse incoming data somehow, you can add your code to this function.
// input: bytes
// expected output:
//  {
//    "attributes": {"attributeKey": "attributeValue"},
//    "telemetry": {"telemetryKey": "telemetryValue"}
//  }
//
// In the example - bytes will be saved as HEX string and also parsed as light level, battery level and PIR sensor value.
//

function decodePayload(input) {
    var output = { attributes:{}, telemetry: {} };
    // --- Decoding code --- //

    output.telemetry.HEX_bytes = bytesToHex(input);

    // If the length of the input byte array is odd - we cannot parse it using the example below
    if (input.length > 2) {
        var i = 0;
        while (i < input.length - 2) {
            var channel_id = input[i];
            i++;
            var channel_type = input[i];
            i++;
            // BATTERY
            if (channel_id === 0x01 && channel_type === 0x75) {
                output.telemetry.battery = input[i];
                i++;
            }
            // PIR
            else if (channel_id === 0x03 && channel_type === 0x00) {
                output.telemetry.pir = input[i] === 0 ? "normal" : "trigger";
                i++;
            }
            // DAYLIGHT
            else if (channel_id === 0x04 && channel_type === 0x00) {
                output.telemetry.daylight = input[i] === 0 ? "dark" : "light";
                i++;
            }
        }
    }

    // --- Decoding code --- //
    return output;
}

// --- attributes and telemetry objects ---
var telemetry = {};
var attributes = {};
// --- attributes and telemetry objects ---

// --- Timestamp parsing
var dateString = data.time;
var timestamp = -1;
if (dateString != null) {
  timestamp = new Date(dateString).getTime();
  if (timestamp == -1) {
      var secondsSeparatorIndex = dateString.lastIndexOf('.') + 1;
      var millisecondsEndIndex = dateString.lastIndexOf('+');
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('Z');
      }
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('-');
      }
      if (millisecondsEndIndex == -1) {
          if (dateString.length >= secondsSeparatorIndex + 3) {
              dateString = dateString.substring(0, secondsSeparatorIndex + 3);
          }
      } else {
          dateString = dateString.substring(0, secondsSeparatorIndex + 3) +
              dateString.substring(millisecondsEndIndex, dateString.length);
      }
      timestamp = new Date(dateString).getTime();
  }
}
// If we cannot parse timestamp - we will use the current timestamp
if (timestamp == -1) {
    timestamp = Date.now();
}
// --- Timestamp parsing

// You can add some keys manually to attributes or telemetry
attributes.deduplicationId = data.deduplicationId;

// You can exclude some keys from the result
var excludeFromAttributesList = ["deviceName", "rxInfo", "confirmed", "data", "deduplicationId","time", "adr", "dr", "fCnt"];
var excludeFromTelemetryList = ["data", "deviceInfo", "txInfo", "devAddr", "adr", "time", "fPort", "region_common_name", "region_config_id", "deduplicationId"];

// Message parsing
// To avoid paths in the decoded objects we passing false value to function as "pathInKey" argument.
// Warning: pathInKey can cause already found fields to be overwritten with the last value found.

var telemetryData = toFlatMap(data, excludeFromTelemetryList, false);
var attributesData = toFlatMap(data, excludeFromAttributesList, false);

var uplinkDataList = [];

// Passing incoming bytes to decodePayload function, to get custom decoding
var customDecoding = decodePayload(base64ToBytes(data.data));

// Collecting data to result
if (customDecoding.?telemetry.size() > 0) {
    telemetry.putAll(customDecoding.telemetry);
}

if (customDecoding.?attributes.size() > 0) {
    attributes.putAll(customDecoding.attributes);
}

telemetry.putAll(telemetryData);
attributes.putAll(attributesData);

var result = {
    deviceName: deviceName,
    deviceType: deviceType,
//  assetName: assetName,
//  assetType: assetType,
//  customerName: customerName,
    groupName: groupName,
    attributes: attributes,
    telemetry: {
        ts: timestamp,
        values: telemetry
    }
};

return result;`

if I use the test tool it does not show any error:
![image](https://github.com/user-attachments/assets/32df22c3-3a53-4d35-9034-3beddbf3e23a)

I hope you can help me solve this problem

**Comment by trikimiki** [comment]
hi!

I think `while` loop could possibly cause array OOB issue
that is if you did not receive neither of `BATTERY`, nor `PIR`, nor `DAYLIGHT` clause worked for `id`/`type`
(junk data input?)

about test converter did not show any error -  I have seen similar issues, where converter did not throw failure when OOB for some reasons, but due to OOB before, failed on another message that was OK

@nickAS21 could you please check default Chirpstack converter?

meanwhile, check out https://github.com/thingsboard/data-converters for the best practices of writing convertors. Using `while` is not recommended - use `for` instead.
E.g. https://github.com/thingsboard/data-converters/blob/main/VENDORS/Milesight/AM319/ChirpStack/uplink/converter.json
```
   decoded.hexString = bytesToHex(input);
    for (var i = 0; i < input.length - 2; ) {
        var channel_id = input[i++] & 0xff;
        var channel_type = input[i++] & 0xff;
        // BATTERY
        if (channel_id === 0x01 && channel_type === 0x75) {
            decoded.battery = input[i];
            i += 1;
        }
        // TEMPERATURE
        if (channel_id === 0x03 && channel_type === 0x67) {
            // ℃
            decoded.temperature = parseBytesToInt(input, i, 2, false) / 10;
            i += 2;
            // ℉
            // decoded.temperature = parseBytesToInt(input, i, 2, false) / 10 * 1.8 + 32;
            // i +=2;
        }
        ....
    }
```

**Comment by niho06** [comment]
Hi and thanks for the suggestions.

I made the changes and the decorder works fine for a couple of hours and then fails again.

`var data = decodeToJson(payload);
var deviceName = data.deviceInfo.deviceName;
var deviceType = data.deviceInfo.deviceProfileName;
var groupName = 'IAQ devices';
// var customerName = 'Customer A';
// use assetName and assetType instead of deviceName and deviceType
// to automatically create assets instead of devices.
// var assetName = 'Asset A';
// var assetType = 'building';

// If you want to parse incoming data somehow, you can add your code to this function.
// input: bytes
// expected output:
//  {
//    "attributes": {"attributeKey": "attributeValue"},
//    "telemetry": {"telemetryKey": "telemetryValue"}
//  }
//
// In the example - bytes will be saved as HEX string and also parsed as light level, battery level and PIR sensor value.
//

function decodePayload(input) {
    var output = { attributes: {}, telemetry: {} };
    output.telemetry.HEX_bytes = bytesToHex(input);

    // Validar que el array de entrada no esté vacío
    if (input.length > 0) {
        var i = 0; // Definir el índice
        while (i < input.length) {
            if (i + 1 >= input.length) break;

            var channel_id = input[i]; // Leer el ID de canal
            i++; // Incrementar índice manualmente
            var channel_type = input[i]; // Leer el tipo de canal
            i++; // Incrementar índice manualmente

            if (i >= input.length) break;

            // BATTERY
            if (channel_id == 0x01 && channel_type == 0x75) {
                output.telemetry.battery = input[i];
                i++; // Incrementar índice manualmente
            }
            // PIR
            else if (channel_id == 0x03 && channel_type == 0x00) {
                output.telemetry.pir = input[i] == 0 ? "normal" : "trigger";
                i++; // Incrementar índice manualmente
            }
            // DAYLIGHT
            else if (channel_id == 0x04 && channel_type == 0x00) {
                output.telemetry.daylight = input[i] == 0 ? "dark" : "light";
                i++; // Incrementar índice manualmente
            } else {
                i++; // Incrementar índice manualmente para saltar el valor actual.
            }
        }
    }

    return output;
}


// --- attributes and telemetry objects ---
var telemetry = {};
var attributes = {};
// --- attributes and telemetry objects ---

// --- Timestamp parsing
var dateString = data.time;
var timestamp = -1;
if (dateString != null) {
  timestamp = new Date(dateString).getTime();
  if (timestamp == -1) {
      var secondsSeparatorIndex = dateString.lastIndexOf('.') + 1;
      var millisecondsEndIndex = dateString.lastIndexOf('+');
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('Z');
      }
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('-');
      }
      if (millisecondsEndIndex == -1) {
          if (dateString.length >= secondsSeparatorIndex + 3) {
              dateString = dateString.substring(0, secondsSeparatorIndex + 3);
          }
      } else {
          dateString = dateString.substring(0, secondsSeparatorIndex + 3) +
              dateString.substring(millisecondsEndIndex, dateString.length);
      }
      timestamp = new Date(dateString).getTime();
  }
}
// If we cannot parse timestamp - we will use the current timestamp
if (timestamp == -1) {
    timestamp = Date.now();
}
// --- Timestamp parsing

// You can add some keys manually to attributes or telemetry
attributes.deduplicationId = data.deduplicationId;

// You can exclude some keys from the result
var excludeFromAttributesList = ["deviceName", "rxInfo", "confirmed", "data", "deduplicationId","time", "adr", "dr", "fCnt"];
var excludeFromTelemetryList = ["data", "deviceInfo", "txInfo", "devAddr", "adr", "time", "fPort", "region_common_name", "region_config_id", "deduplicationId"];

// Message parsing
// To avoid paths in the decoded objects we passing false value to function as "pathInKey" argument.
// Warning: pathInKey can cause already found fields to be overwritten with the last value found.

var telemetryData = toFlatMap(data, excludeFromTelemetryList, false);
var attributesData = toFlatMap(data, excludeFromAttributesList, false);

var uplinkDataList = [];

// Passing incoming bytes to decodePayload function, to get custom decoding
var customDecoding = decodePayload(base64ToBytes(data.data));

// Collecting data to result
if (customDecoding.?telemetry.size() > 0) {
    telemetry.putAll(customDecoding.telemetry);
}

if (customDecoding.?attributes.size() > 0) {
    attributes.putAll(customDecoding.attributes);
}

telemetry.putAll(telemetryData);
attributes.putAll(attributesData);

var result = {
    deviceName: deviceName,
    deviceType: deviceType,
//  assetName: assetName,
//  assetType: assetType,
//  customerName: customerName,
    groupName: groupName,
    attributes: attributes,
    telemetry: {
        ts: timestamp,
        values: telemetry
    }
};

return result;`

![image](https://github.com/user-attachments/assets/f7729276-4067-46ab-b26a-0df2230cdc07)

![image](https://github.com/user-attachments/assets/7f7aa7e3-14f1-46f5-bdb2-2ff80ef8bd30)

Is this a problem with the new version of thingsboard 3.8.1PAAS?

**Comment by mde2017** [comment]
We have the same problem with a self-managed deployment of 3.8.1 PE
After restarting the ThingsBoard service and ChirpStack integration, it works for a few hours and then crashes again.

**Comment by niho06** [comment]
Good morning @mde2017,

I solved the problem by making a new decoder and remove the hexadecimal check. Since I don't see it necessary because chirpstack in via all the decoded data in JSON format.

Regards

**Comment by mde2017** [comment]
Hi @niho06,

thanks for sharing your solution to the issue.
We wil try this approach. 

Our workaround would otherwise be to change the code from TBEL to JavaScript

Best Regards

**Comment by niho06** [comment]
This is my decoder and I haven't had any problems since then, I hope it helps.

`var data = decodeToJson(payload);
var deviceName = data.deviceInfo.deviceName;
var deviceType = data.deviceInfo.deviceProfileName;
var groupName = 'IAQ devices';
// var customerName = 'Customer A';
// use assetName and assetType instead of deviceName and deviceType
// to automatically create assets instead of devices.
// var assetName = 'Asset A';
// var assetType = 'building';

// If you want to parse incoming data somehow, you can add your code to this function.
// input: bytes
// expected output:
//  {
//    "attributes": {"attributeKey": "attributeValue"},
//    "telemetry": {"telemetryKey": "telemetryValue"}
//  }
//
// In the example - bytes will be saved as HEX string and also parsed as light level, battery level and PIR sensor value.
//

function decodePayload(input) {
    var output = { attributes: {}, telemetry: {} };
    output.telemetry.HEX_bytes = bytesToHex(input);

    // Se eliminó el procesamiento de canales específico.

    return output;
}


// --- attributes and telemetry objects ---
var telemetry = {};
var attributes = {};
// --- attributes and telemetry objects ---

// --- Timestamp parsing
var dateString = data.time;
var timestamp = -1;
if (dateString != null) {
  timestamp = new Date(dateString).getTime();
  if (timestamp == -1) {
      var secondsSeparatorIndex = dateString.lastIndexOf('.') + 1;
      var millisecondsEndIndex = dateString.lastIndexOf('+');
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('Z');
      }
      if (millisecondsEndIndex == -1) {
          millisecondsEndIndex = dateString.lastIndexOf('-');
      }
      if (millisecondsEndIndex == -1) {
          if (dateString.length >= secondsSeparatorIndex + 3) {
              dateString = dateString.substring(0, secondsSeparatorIndex + 3);
          }
      } else {
          dateString = dateString.substring(0, secondsSeparatorIndex + 3) +
              dateString.substring(millisecondsEndIndex, dateString.length);
      }
      timestamp = new Date(dateString).getTime();
  }
}
// If we cannot parse timestamp - we will use the current timestamp
if (timestamp == -1) {
    timestamp = Date.now();
}
// --- Timestamp parsing

// You can add some keys manually to attributes or telemetry
attributes.deduplicationId = data.deduplicationId;

// You can exclude some keys from the result
var excludeFromAttributesList = ["deviceName", "rxInfo", "confirmed", "data", "deduplicationId","time", "adr", "dr", "fCnt"];
var excludeFromTelemetryList = ["data", "deviceInfo", "txInfo", "devAddr", "adr", "time", "fPort", "region_common_name", "region_config_id", "deduplicationId"];

// Message parsing
// To avoid paths in the decoded objects we passing false value to function as "pathInKey" argument.
// Warning: pathInKey can cause already found fields to be overwritten with the last value found.

var telemetryData = toFlatMap(data, excludeFromTelemetryList, false);
var attributesData = toFlatMap(data, excludeFromAttributesList, false);

var uplinkDataList = [];

// Passing incoming bytes to decodePayload function, to get custom decoding
var customDecoding = decodePayload(base64ToBytes(data.data));

// Collecting data to result
if (customDecoding.?telemetry.size() > 0) {
    telemetry.putAll(customDecoding.telemetry);
}

if (customDecoding.?attributes.size() > 0) {
    attributes.putAll(customDecoding.attributes);
}

telemetry.putAll(telemetryData);
attributes.putAll(attributesData);

var result = {
    deviceName: deviceName,
    deviceType: deviceType, 
//  assetName: assetName,
//  assetType: assetType,
//  customerName: customerName,
    groupName: groupName,
    attributes: attributes,
    telemetry: {
        ts: timestamp,
        values: telemetry
    }
};

return result;`

Best Regards

**Comment by mde2017** [comment]
Thank you for sharing your decoder, we will try this out

**Comment by nickAS21** [comment]
my recomendation

**Comment by nickAS21** [comment]
> hi!
> 
> I think `while` loop could possibly cause array OOB issue that is if you did not receive neither of `BATTERY`/`PIR`/`DAYLIGHT` for `id`/`type`, and so `if` clauses did not work (junk data input?)
> 
> about test converter did not show any error - I have seen similar issues, where converter did not throw failure when OOB for some reasons, but due to OOB before, failed on another message that was OK
> 
> @nickAS21 could you please check default Chirpstack converter?
> 
> meanwhile, check out https://github.com/thingsboard/data-converters for the best practices of writing convertors. Using `while` is not recommended - use `for` instead. E.g. https://github.com/thingsboard/data-converters/blob/main/VENDORS/Milesight/AM319/ChirpStack/uplink/converter.json
> 
> ```
>    decoded.hexString = bytesToHex(input);
>     for (var i = 0; i < input.length - 2; ) {
>         var channel_id = input[i++] & 0xff;
>         var channel_type = input[i++] & 0xff;
>         // BATTERY
>         if (channel_id === 0x01 && channel_type === 0x75) {
>             decoded.battery = input[i];
>             i += 1;
>         }
>         // TEMPERATURE
>         if (channel_id === 0x03 && channel_type === 0x67) {
>             // ℃
>             decoded.temperature = parseBytesToInt(input, i, 2, false) / 10;
>             i += 2;
>             // ℉
>             // decoded.temperature = parseBytesToInt(input, i, 2, false) / 10 * 1.8 + 32;
>             // i +=2;
>         }
>         ....
>     }
> ```
You can use any loop construct: either -while or -for. The main condition: a check i < input.length - 2 to ensure that there are exactly 2 bytes left to determine the values of the parameters (channel_id, channel_type).
