### ISSUE TITLE
Issue with multiple packet with protobuf

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#11894]
We are using protobuf for communication. We are unable to send multiple packets using protobuf. 
We are planning to use below proto schema - 

            message data {
            
                message msg_values {
                    optional float v1 = 3;
                    optional float v2 = 4;
                    optional float v3 = 5;
                }
            
                message record {
                    uint64 ts = 1;
                    msg_values values = 2;
                }
                repeated record records = 1;
            }

However, this parses data and stores in key as records. The expected output was to use ts as timestamp and values to be stored with keys as v1, v2, v3

Request you to please help, on how to enable multiple packet data transfer with protobuf and also use ts as timestamp for record.

**Comment by liotys** [comment]
Hi @sjthings ,
can you specify in which direction you want to send your protobuf (from or to TB) and where you put your schema?

**Comment by sjthings** [comment]
I wish to send from device to TB. The proto schema is added in telemetry
section under transport configuration of device profile.

**Comment by liotys** [comment]
Ok, here is a sample of protobuf that works fine in TB:
```
syntax ="proto3";
package common;
message Gps {
    float latitude = 1;
    float longitude = 2;
}
message Measure {
    int32 distance = 1;
    int32 charge = 2;
    float temperature = 3;
    int64 timestamp = 4;
}
message Sensor {
    bytes id_sensor = 1;
    repeated Measure measure = 2;
}

message Downlink {
    int32 debut_plage = 1;
    int32 fin_plage = 2;
    string instruction = 3;
}
message Params {
    optional bytes id_gateway = 1;
    optional Gps gps = 2;
    repeated Sensor sensor = 3;
	optional Downlink downlink = 4;
}
message Message {
  optional string method = 1;
  optional int32 requestId = 2;
  optional Params params = 3;
  optional int32 batt_mv_empty = 4;
  optional int32 batt_mv_load = 5;
}
```
During my tests to have samples of hexa strings, I had problems with online converter which didn't give the rights hexa results.  I had to build my own converter in python.
Tell me if you want the python code.

**Comment by liotys** [comment]
For the timestamp, you'll have to fill the field ts in metadata just before the save timeseries node:
```
var newMeta = metadata;
newMeta.ts = msg.ts;
return {msg: msg, metadata: newMeta, msgType: msgType};

```
You'll have to take in account that timestamps in TB are in ms and may be you will receive a timstamp in seconds. Don't forget to multiply by 1000.
