### ISSUE TITLE
Is MQTT Transport in a microservice architecture with multiple replicas compatible with AWS SQS queue ?

### ISSUE THREAD

**Issue by geda** [thingsboard/thingsboard#11899]
![SQS queues](https://github.com/user-attachments/assets/893acac4-0dda-4b9b-86da-0d53069424ff)
[mqtt_k8s_config.yaml.txt](https://github.com/user-attachments/files/17416397/mqtt_k8s_config.yaml.txt)
**Component**

 * Installation in microservice architecture and deployment in a k8s cluster

**Description**
We have installed TB Community edition 3.7 in a k8s cluster in a microservice architecture using AWS SQS Queues.
Everthing works fine with 1 replica of the component MQTT Transport.
As soon as we add more replicas, the MQTT server blocks the request and this error is seen on the mosquitto client:
<= Client (null) received CONNACK (3)
<= Connection error: Connection Refused: broker unavailable.

This error is spotted in the logs of the MQTT Transport:
DEBUG o.t.s.q.c.DefaultTbQueueRequestTemplate - [ef96eeb0-4e82-42c9-8763-85fbadf25af2] Invalid or stale request, response: TbProtoQueueMsg(key=8eb30368-ccb4-43c0-a119-28deab66ee8b, value=entityProfileResponseMsg {   tenantProfile {     tenantProfileIdMSB: 2830421797314957806....

By analyzing the source code, it's looks like that the pod sending the request on the queue is probably not the same that the on reading the response.
[https://github.com/thingsboard/thingsboard/blob/3528715d2bd5249093ab971bded1fb8b3167210a/common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java#L178](https://github.com/thingsboard/thingsboard/blob/3528715d2bd5249093ab971bded1fb8b3167210a/common/queue/src/main/java/org/thingsboard/server/queue/common/DefaultTbQueueRequestTemplate.java#L178)

Are we missing something in the configuration or SQS queues ?

**Environment**

 * ThingsBoard: version 3.7

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by pon0marev** [comment]
Do you use a zookeeper in your deployment? This behavior could be due to missing zookeeper and node mis-synchronization.
In addition, in thingsboard 4.0, all queue types except Kafka and in-memory are planned to be removed . So I recommend using Kafka queue as the most stable and performant queue.

**Comment by geda** [comment]
No we did not use zookeeper and that's probably causing the problem.
Thanks for the advice, we gonna move to Kafka queues.

**Comment by pon0marev** [comment]
@geda Have you successfully configured the connection with 2 mqtt transport replicas?

**Comment by pon0marev** [comment]
We want to inform you that we have closed your ticket as we have not received any updates on this issue. If you still have questions or encounter similar issues after upgrading to the latest version, please reopen this issue.
