### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by andyesys** [thingsboard/thingsboard#1189]
Please add a german translation to the Web Frontend. That's all. 👍

**Comment by vparomskiy** [comment]
Here is a list of all available translations
https://github.com/thingsboard/thingsboard/tree/master/ui/src/app/locale

If you can provide German translation we will add it to the platform.

**Comment by andyesys** [comment]
I don't have the time right now, it will become neccessary in the future though. For now I just wanted to log it here. Thanks.

**Comment by andyesys** [comment]
We have started the german translation and will submit a pull request soon.

**Comment by ThomasBaumgartner** [comment]
![grafik](https://user-images.githubusercontent.com/45274753/81945021-d457a680-95fd-11ea-83f3-ac0a12698378.png)

There is an issue with the representation of the time select window if language is set to german.
