### ISSUE TITLE
Search Device issue

### ISSUE THREAD

**Issue by Postgre** [thingsboard/thingsboard#119]
I've crated a new device called 'MqttCarDevice' then i've tryed to search it via search feature in device page and the result for search is 3 devices with same name !, and i'am sure i've created only one device !

**Comment by ashvayka** [comment]
This is a bug. We will track this.

**Comment by ashvayka** [comment]
This is fixed in master branch now

**Comment by Postgre** [comment]
The same sources of master branch is available in demo site now ?

**Comment by ashvayka** [comment]
no, the source code of master branch is not yet deployed to demo env.

**Comment by ashvayka** [comment]
This is fixed now

**Comment by Postgre** [comment]
Thank you very much!
