### ISSUE TITLE
Display Telemetry Data Between 5-7 AM Daily in ThingsBoard Widget

### ISSUE THREAD

**Issue by Tomi05-k** [thingsboard/thingsboard#11917]
**Component**

 * UI / Dashboard

**Description**
I’m trying to configure a widget in ThingsBoard that displays a telemetry value from a device within the time range of 5:00 to 7:00 AM every day. The telemetry data does not always arrive at exact intervals, so I need the widget to capture and display the first available value within this range.

I attempted to use the filters, but I’m not sure how to configure them correctly. When I try to filter by DateTime, it requires me to specify a full date. However, I only want to filter by time (5:00 - 7:00 AM) so that every day, the first telemetry value received within this time range is displayed in a table.

Is there a way to set this up without specifying an exact date, and only filter by time on a daily basis? Any suggestions or examples would be greatly appreciated.

**Environment**

 * OS:  Ubuntu 24.04
 * ThingsBoard: 3.8.1
 * Browser: Safari and Google Chrome

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
You can try to implement it using Date-range navigator widget.
I've previously provided an example of its configuration
https://github.com/thingsboard/thingsboard/issues/11342#issuecomment-2265409499

**Comment by Tomi05-k** [comment]
Hii, Thank you for your reply. 
I was hoping that I could set a filter or do a very simple SQL query. 
I actually need a table or something where I can always see my value at 06am.
It's stupid to always hover over the line chart with the mouse and read the value. Do you have any other ideas?

**Comment by Tomi05-k** [comment]
That would be cool, except that the date is always the current day.

<img width="681" alt="Bildschirmfoto 2024-10-22 um 17 44 42" src="https://github.com/user-attachments/assets/1db58d39-062d-41cf-bc49-a19bf4745e7b">

**Comment by mykhailokornieiev** [comment]
Hi. There is no such functionality in available widgets and it won't be provided by design of Thingsboard. You can try to create your own widget that will meet all your requirements.
You can get familiar with available documentation:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
