### ISSUE TITLE
Aggregation for each key

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#11921]
Hi there! 

Can you add an option to provide a separate aggregation function for each key when aggregating data in a Timeseries table? For example MAX for "Consumption", AVG for "FlowRate", etc. 

Thanks!

**Comment by mykhailokornieiev** [comment]
Hi
This feature request is rejected since it will be a performance killer and goes against the design for both Thingsboard and Timeseries Table widget.
