### ISSUE TITLE
Client Credentials Grant Flow or API key for REST Api

### ISSUE THREAD

**Issue by tonny1983** [thingsboard/thingsboard#11928]
The REST api, currently requires JWT Token exchanged with USERNAME and PASSOWRD. In some cases, for certain Apis, especially those RPC Apis are usually called by other systems rather than a certain user in thingsboard. It may not be a best practice keeping such a USERNAME and PASSWORD in other system shared by real thingsboard user, because the user could change the PASSWORD but the other systems gets no new password.

It would be very helpful if thingboard could provide API key function to generate some API key for calls from other systems or could register the other systems in thingsboard and then follow the `Client Credentials Grant Flow` to get the token instead of using USERNAME and PASSWORD.

As an alternative, I'd also like to know whether there are possibilities for me to provide a custom authentication filter for REST Api that adds other mechanisms to avoid using username/password.

**Comment by mykhailokornieiev** [comment]
Hi
This feature request was previously added to our backlog for developers.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by AndriiLandiak** [comment]
@tonny1983 hi, it's already implemented and merged, will be available in the next 4.3 release!
