### ISSUE TITLE
The "switch" only outputs "Failure".

### ISSUE THREAD

**Issue by jsxzhub** [thingsboard/thingsboard#11925]
version 3.8.1

![1729589907621](https://github.com/user-attachments/assets/fc334e9a-54ec-41c9-85b1-9eaeeaa688c3)

only outputs ：

![1729589955821](https://github.com/user-attachments/assets/6dfb1f19-9fdf-42de-aaec-9f96f7c65568)

**Comment by mykhailokornieiev** [comment]
Hi. There is no bug in it, since "Switch" rule node is designed for custom relations. In this case, you will need to specify your relations manually.
