### ISSUE TITLE
The sinicization of Chinese is incomplete

### ISSUE THREAD

**Issue by HuaPing2017** [thingsboard/thingsboard#11927]
**Describe the bug**
![image](https://github.com/user-attachments/assets/9f2ae2df-20e8-4897-8dd2-64567fcbaeee)

环境
* OS: Windows
* Browser Microsoft Edge 130.0.2849.46  (64 位)
* Version 3.8.0

**Comment by mykhailokornieiev** [comment]
Hi
These values can be changed via Custom Translation
![image](https://github.com/user-attachments/assets/cab073b3-1026-4222-bdfc-a92f53f3e1ab)
![image](https://github.com/user-attachments/assets/47648645-97dd-43d2-949b-20707c32eb84)
You can contribute by improving this localization and providing an improved localization file:
![image](https://github.com/user-attachments/assets/ac05c34c-0e2d-44dd-91f1-067b7b248921)
https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/

**Comment by mykhailokornieiev** [comment]
https://thingsboard.io/docs/pe/user-guide/custom-translation/
This feature is only available for PE.
But if you want to improve it, we can provide you with a localization file. 
Please specify what exactly language it is.

**Comment by friedrich86** [comment]
Could give hints about the translation code , in which folder? which file.

**Comment by mykhailokornieiev** [comment]
Hi @friedrich86 
You can find it here
https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale

**Comment by HuaPing2017** [comment]
> https://thingsboard.io/docs/pe/user-guide/custom-translation/ 此功能仅适用于 PE。但如果您想改进它，我们可以为您提供本地化文件。请说明它的具体语言是什么。

However, the calendar component I want cannot be modified into Chinese, I am using the CE version, not PE, how to improve

**Comment by mykhailokornieiev** [comment]
@HuaPing2017 as mentioned before, this feature available only for PE. If you want to improve Chinese localization, then you can improve available locale files and then contribute it so it will be used as default localization for both CE and PE
https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale

**Comment by mykhailokornieiev** [comment]
Custom Translation feature provides an ability to make custom translation changes in Thingsboard UI.

**Comment by HuaPing2017** [comment]
> 如前所述，此功能仅适用于 PE。如果要改进中文本地化，则可以改进可用的 locale 文件，然后将其贡献出来，以便将其用作 CE 和 PE [的默认本地化 https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale)

I was tryed ,but it not 

> @HuaPing2017 as mentioned before, this feature available only for PE. If you want to improve Chinese localization, then you can improve available locale files and then contribute it so it will be used as default localization for both CE and PE https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale

I was tryed ,but it don't available

**Comment by mykhailokornieiev** [comment]
You cannot make changes in localizations through UI in CE version. For such cases, you can download locale in JSON format, modify in any available text editor and then make contribution
Please see our [Contribution Guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/).

However, there are some values can't be changed since this is third-party library and it not depends on Thingsboard.
