### ISSUE TITLE
Thingsboard DataBase

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#11920]
Is there any attribute in the thingsboard configuration file that can control not to create new data when starting thingsboard? That is to say, I already have a database connected to a thingsboard. How can I start another thingsboard to connect to this database? Currently, it always reports an error that the system administrator already exists

**Comment by pon0marev** [comment]
I think you are using the thingsboard installation in docker https://thingsboard.io/docs/user-guide/install/docker/. Aren't you?
This problem could happen if the thingsboard container lacks volume for data or the .firstlaunch file cannot be created.

**Comment by Remington-Hunter** [comment]
Yes, thanks for your answer, I have modified the startup script to solve this problem.
