### ISSUE TITLE
Share devices and data between tenants

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard#11931]
Good morning, 

I am working on a project where I have a list of devices in the main tenant. This devices generate data everyday and I wanna know if there is a possibility that a user from a different tenant could access that data for developing but without being able to delete o change information. 

This way the other user could create new dashboards and use the device data without being able to delete any important information.

Thanks for the help!

**Comment by mykhailokornieiev** [comment]
Hi
You can't share data between tenants by the design of Thingsboard.
As a custom workaround, you can make the next:
For entities, you can use Version Control and Git. You can get familiar with this method by following link:
https://thingsboard.io/docs/user-guide/version-control/
For telemetry you can use REST API. Use GET requests for export and POST requests for import. To automate the process, you can make a script based on these requests.
You can get familiar with list of telemetry controllers by following link:
http://{your_thingsboard-url}/swagger-ui/#/telemetry-controller

**Comment by CalmNite** [comment]
Thanks! I will look that option.
