### ISSUE TITLE
eCharts Line chart custom yAxis not hidden when no datakey is visible. 

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#11932]
**Describe the bug**  
We are migrating chart widgets to the new eCharts widget and configured the chart as follows:

<details>
  <summary>1. Chart Screenshot before issue (click to expand)</summary>

![image](https://github.com/user-attachments/assets/782b7b1e-930b-43a9-a99e-cc08464f00df)

</details>

When adding `datakeys` and `yAxis`, we encountered a problem where the `yAxis` remains visible even when no `datakeys` are visible in the legend.

<details>
  <summary>2. Chart Screenshot after issue (click to expand)</summary>

![image](https://github.com/user-attachments/assets/85d36d76-2fb4-4013-b41d-e535e4e63554)

</details>

These are the `yAxis` configurations:

<details>
  <summary>3. Chart widget yAxis config (click to expand)</summary>

![image](https://github.com/user-attachments/assets/254d05e9-abe4-4664-8d21-94d29d03e852)

</details>

However, if I remove the `yAxis` max value (auto), the `yAxis` behaves as intended and becomes hidden when no `datakeys` are visible.

<details>
  <summary>4. Chart widget yAxis config with max value removed (click to expand)</summary>

![image](https://github.com/user-attachments/assets/17cf193f-8caa-4bf9-ae7a-68acad1ee704)

![image](https://github.com/user-attachments/assets/0d9efce6-fc2a-48d6-9c55-98a2c1fd2322)

</details>

---

**Your Server Environment**  
* Own setup  
  * ThingsBoard Version: 3.6.4 PE, 3.7 PE, and 3.8.1 CE

**Your Client Environment**  
* OS: Windows 11  
* Browser: Chrome (latest version)

---

**To Reproduce**  

1. Create an eCharts widget and add an entity alias. The alias should have some telemetry data to display.
2. Add a `datakey` to display.
3. In widget settings -> appearance -> `yAxis` (default), set the max value, and set the min value to 0.
4. In `datakey` settings -> advanced -> set default to hidden.
5. Save the widget settings. You will notice the `yAxis` remains visible even when no `datakeys` are visible, as they are hidden by default.
6. Now, open the widget settings again, remove the `yAxis` max value, and keep the min value at 0, then save the widget.
7. The `yAxis` will now be hidden and will only become visible if a `datakey` is displayed (from legend click).
8. If you set the `yAxis` to auto and specify the max value, the bug does not occur.

---

**Expected behavior**  
The `yAxis` should be hidden when no `datakeys` assigned to that `yAxis` are visible, even if both the max and min `yAxis` values are set.

**Comment by mykhailokornieiev** [comment]
Hi. I was able to reproduce such behavior. It looks like a bug in a platform, so I've added a ticket to our backlog for our developers. There's no set timeframe for this bug fix; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
