### ISSUE TITLE
Horizontally scrollable dashboard

### ISSUE THREAD

**Issue by kavorca92** [thingsboard/thingsboard#11938]
**Is your feature request related to a problem? Please describe.**
Hey!

Im trying to make a dashboard solution where i need to have 10 custom widgets horizontally to fit how the blueprint looks like in real life.
But when im trying to fit them all in a good size horizontally in different breakpoints they keep resizing the widgets that im not resizing to fit them all in.

**Describe the solution you'd like**
A way to create a horizontal scrollable solution to fit projects with horizontally large floorplans to keep the design consistent.

**Describe alternatives you've considered**
I started looking around and find something about gridster having a css class thats called scrollVertical which has:
overflow-x: hidden;
overflow-y: auto;
Could this have something to do with it and can i change it in custom css for the dashboard somehow?

**Comment by Ultrazombie** [comment]
Rejected. We have raised this request in internal meetings. Unfortunately, it is beyond the design and will not be implemented

**Comment by Allwhy** [comment]
Hey, I am currently playing around with custom widgets and gridster options.
I made a custom widget which I can add to my dashboard and then hide by just making its background transparent. 
On Desktop it then enables horizontal scrolling. I didn't test much with it yet, so can't say if there might be any unwanted sideeffects.

The code for the widget is the following:
`
self.onInit = function() {
    const dashboard = self.ctx.dashboard
    dashboard.gridsterOpts.gridType = "scrollHorizontal"
    
    dashboard.gridster.optionsChanged()
}
`

Hope I it helps.
