### ISSUE TITLE
Make user email addresses case insensitive

### ISSUE THREAD

**Issue by dm9de** [thingsboard/thingsboard#11934]
**Is your feature request related to a problem? Please describe.**

We have many users who are not technically savvy, and who will, at different times, capitalise their email addresses or not capitalise them - leading to frequent issues with logging in to Thingsboard, and difficulty in administering user accounts. While RFC 5321 states that the local part of an email address should be considered case sensitive, in practice, this is unworkable.

**Describe the solution you'd like**

Treat user email addresses as case-insensitive when logging in and creating users.

Potentially, could retain case sensitivity for display purposes, but for logging in and determining user uniqueness, should convert email addresses to all lowercase.

**Describe alternatives you've considered**

I am considering writing my own version of the log-in page that converts the email address field to lower case before form submission, and then manually updating all user emails to lowercase. However, this is definitely a sticking plaster workaround. I believe this should be the default behaviour for Thingsboard.

(note: we are Thingsboard PE subscribers)

**Comment by mykhailokornieiev** [comment]
Hi
Please, get familiar with this ticket:
https://github.com/thingsboard/thingsboard/issues/10937

**Comment by dm9de** [comment]
Ah brilliant! Thank you 👍
