### ISSUE TITLE
Rule chains - Relation events

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#11930]
**Component**

 * Generic

**Description**
Hi there!

My work colleagues and I would like to know if there is a possibility to receive only one relations event in rule chain, since it is received two with the same payload but changing the incoming "Entity Id", which causes two executions of our rule chain.

For now, we have implemented the work around attached in the pictures below:

![image](https://github.com/user-attachments/assets/91e3bac2-70db-46bf-8bdc-253442744fee)
![image](https://github.com/user-attachments/assets/b533d202-6fac-40c7-8578-8b919dc07d72)
![image](https://github.com/user-attachments/assets/3cda6982-bed3-4124-a56c-3c8ecbb391ef)

In any case, we would like to know if there is a better approach than that, we should follow another strategy, etc...

Looking forward to your feedback.

Kind regards.
Daniel.

**Environment**

* OS:  Monolitic setup using AWS infrastructure 
* ThingsBoard: 3.7.0PE
* Browser: Chrome

**Comment by dpergarc-c** [comment]
Hi there,

Yeah sure @mykhailokornieiev , find a further explanation below:

The point here is that we would like to discern the relations event in the rule chains.

That is working perfectly since we have this first rule chain:
![image](https://github.com/user-attachments/assets/ca4e565a-084f-4809-bf46-09bdcae83649)

All relations are successfully detected in the first node of the next rule chain:
![image](https://github.com/user-attachments/assets/d6740632-4fb5-4d63-966a-9a27665b09af)

And the debug shows these messages, two "IN" and two "OUT":
![image](https://github.com/user-attachments/assets/bcaaee17-3c98-4872-8ba1-e4fc620dae00)

The data is the same in both cases, which causes a double trigger in the following rule chain nodes.

As I said before, we have a work around that solves it. Maybe it is a Thingsboard strategy for a reason we do not know yet (on the surface, it looks like a problem for the use case we are trying to develop).

Thanks beforehand, sorry for the inconveniences, and looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by mykhailokornieiev** [comment]
Hi
Thank you for this clarification. 
Indeed, creation of the new relation will create two messages in rule chain. This is correct behavior since both entities have new relations added to them (one new relation for each, one in total), and this is a notification in the rule chain that can't be avoided for any of them.  So, it's just by design.
If you want to avoid it, then yes, your workaround is correct.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev,

Yeah, it was a little bit confusing since the data had the same content in both events. In any case, the real problem is that the rule chain is being triggered twice, something we cannot afford because we have a rest api call at the end of the process, and you can imagen how "dirty" is duplicating that request... Anyway, we have a workaround that is working well. 

Thank you very much for your replies.

Kind regards.
Daniel.
