### ISSUE TITLE
thingsboard/tb-cassandra Docker image not working

### ISSUE THREAD

**Issue by llorenzinho** [thingsboard/thingsboard#11936]
**Describe the bug**
thingsboard/tb-cassandra Docker image not working due to cassandra fail to start

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard 3.8.1 / 3.7.0
  * Community Edition

**To Reproduce**
Run docker compose up with a docker-compose file using kafka and tb-cassandra image (>= 3.7.0)

**Expected behavior**
The start-tb.sh file should create postgres data and start cassandra, then thingsboard should be up and running

**Additional context**
Cassandra reports the following error (taken from logs)
`Error: Could not create the Java Virtual Machine`

This should be caused by the JDK upgrade. Release 3.7 changelog says that java has been migrated to version 17. I Think cassandra needs JDK 1.8 to work. (everithing works smoothly with thingsboard/tb-cassandra:3.6.4)

**Comment by mykhailokornieiev** [comment]
Hi
Please, get familiar with this ticket.
https://github.com/thingsboard/thingsboard/issues/11630

**Comment by llorenzinho** [comment]
Thank you @mykhailokornieiev
