### ISSUE TITLE
Scan Qrcode with Thingsboard Live app

### ISSUE THREAD

**Issue by PedroBarbosaDC** [thingsboard/thingsboard#11940]
**Component**
 * Installation

**Description**
I installed Thingsboard CE on my Ubuntu server, configured devices, sent data, created a dashboard, but when I use the QRcode with the Thingsboard Live app it doesn't load. Simply return to the app's home page
![app](https://github.com/user-attachments/assets/54b3b3ac-1cff-4670-9799-fe2c22436e19)

![01](https://github.com/user-attachments/assets/61d3f61e-bcf8-443d-bb3b-e1d543939a6e)

**Environment**
 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.8.1
 * Browser: Microsoft Edge

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Ultrazombie** [comment]
Thingsboard live app working only with https://demo.thingsboard.io/. Please build your own Flutter app application https://github.com/thingsboard/flutter_thingsboard_app
