### ISSUE TITLE
Actions to assets

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#11946]
**Component**
 * Generic

**Description**
Hi there,

Is it possible to launch actions on assets? It is definitely possible on devices, but I would like to know if assets accept that functionality.

Thanks beforehand, looking forward to hearing from you.

Kind regards.
Daniel.

**Environment**
OS: Monolitic setup using AWS infrastructure
ThingsBoard: 3.7.0PE
Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi
Please describe your request in as much detail as possible.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev 

We have some devices that have a relay in order to perform an action (e.g: switch on a light bulb). We trigger that from a dashboard with a button widget like the picture shown below:

![image](https://github.com/user-attachments/assets/a2f724d5-8040-4711-9b88-b1a81474e7f3)

We would like to know if the asset might be able to behave in the same way the device entity does, especially for the functionality mentioned before.

Looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev,

Thank you very much for your reply! It is absolutely clear now!

Kind regards.
Daniel.
