### ISSUE TITLE
500 Internal Error when generating report

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#11947]
**Describe the bug**
I get an 500 Internal server error when trying to generate report using Credential = "Customer user".
It  works if I choose Credential as "Current user".

![image](https://github.com/user-attachments/assets/83b4a13e-e116-4f4e-8bfb-ea621a261218)

**Your Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)
* 3.8.1.4PAAS : Professional Edition

**Your Client Environment**
* OS: Windows 10
* Browser : Chrome

**To Reproduce**
1. Go to "Scheduler"
2. Create a new event : "Generate Report", "pdf" type
3. Choose your dashboard
4. set credential as "Customer user", and choose a user.
5. Click Generate Test Report
6. See error

**Same problem with rule chain node...**
The problem also appear when using the generate report rule chain node, when using the configuration :

```
{
    "reportConfig": {
        "baseUrl": "https://mds.ascolab.fr",
        "useDashboardTimewindow": true,
        "timewindow": {
            "selectedTab": 1,
            "history": {
                "historyType": 0,
                "interval": 1000,
                "timewindowMs": 86400000
            }
        },
        "namePattern": "report-%d{yyyy-MM-dd_HH:mm:ss}",
        "type": "pdf",
        "timezone": "Europe/Paris",
        "useCurrentUserCredentials": false,
        "userId": "<TheUserIdToUseToGenerateReport>",
        "dashboardId": "ef776a20-9087-11ef-bb05-3f7cd9782d8e",
        "state": ""
    },
    "sendEmail": true,
    "emailConfig": {
        "from": "xxxxxxxxxx@ascolab.fr",
        "to": "xxxxxxxxxx@ascolab.fr",
        "subject": "Report generated on %d{yyyy-MM-dd HH:mm:ss}",
        "body": "Report was successfully generated on %d{yyyy-MM-dd HH:mm:ss}.\nSee attached report file.",
        "cc": null,
        "bcc": null
    }
}
```

![image](https://github.com/user-attachments/assets/3c65f11c-79e0-4e9f-b691-e38fb3d48964)
![image](https://github.com/user-attachments/assets/27921dd4-022b-4910-9ef1-35abc3a2b3fd)

`500 Internal Server Error from POST http://tb-web-report:8383/dashboardReport`

**Remark**
Using the good user Id to generate report is important, because it will take care of device assignement and data access.
The dashboard is based on devices of the user !

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. I'm unable to reproduce this issue on thingsboard.cloud with customer user credentials. 
You definitely doing somethings wrong, since it obviously wrong web-report address
![image](https://github.com/user-attachments/assets/b8ee8a0b-2964-429e-aeab-5a47d18ea9d9)
It must be https://localhost:8383
![image](https://github.com/user-attachments/assets/324b3481-4643-4428-ae5b-3d959cdc3089)
I'd recommend you to use system report server

**Comment by GregAscolab** [comment]
I'm sorry, but :

**1/ From Scheduler :**  
Did you try it from scheduler ?
What is your result ?
On scheduler event parameter, there is no "Use system report" option.

![image](https://github.com/user-attachments/assets/acf69bb1-141c-443f-8fc9-3a40d0a232c1)


**2/ From rule chain :**

![image](https://github.com/user-attachments/assets/a301f5a7-a4a9-49cc-92e3-c9a4d635b529)


I use "system report server" :

![image](https://github.com/user-attachments/assets/89077abb-31be-4603-9742-0342e75f8882)

I generate reportConfig and email by script :
```var newMsg = msg;

var dashboardId = "ef776a20-9087-11ef-bb05-3f7cd9782d8e";

newMsg.reportConfig = {
    "baseUrl": "https://mds.ascolab.fr",
    "useDashboardTimewindow": true,
    "timewindow": {
        "selectedTab": 1,
        "history": {
            "historyType": 0,
            "interval": 1000,
            "timewindowMs": 86400000
        }
    },
    "namePattern": "report-%d{yyyy-MM-dd_HH:mm:ss}",
    "type": "pdf",
    "timezone": "Europe/Paris",
    "useCurrentUserCredentials": false,
    "userId": msg.originatorId,
    "dashboardId": dashboardId,
    "state": ""
};
newMsg.sendEmail = true;
newMsg.emailConfig = {
    "from": msg.originatorEmail,
    "to": msg.originatorEmail,
    "subject": "Report generated on %d{yyyy-MM-dd HH:mm:ss}",
    "body": "Report was successfully generated on %d{yyyy-MM-dd HH:mm:ss}.\nSee attached report file.\nOr go to https://mds.ascolab.fr/dashboards/all/"+dashboardId,
    "cc": null,
    "bcc": null
};


return {
    msg: newMsg,
    metadata: metadata,
    msgType: msgType
};
```

I'm sorry, but I can't see where it's wrong ?

**Comment by mykhailokornieiev** [comment]
> Did you try it from scheduler ?
> What is your result ?
> On scheduler event parameter, there is no "Use system report" option.

Yes, everything works correctly. Scheduler Report events will be processed by the Generate Report rule node anyway.
Do you use sub-customer user?

**Comment by GregAscolab** [comment]
Ok... I found it... No relation with configuration of node, or settings...

**It comes from the dashboard accessibility : It was a dashboard owned by myself (as tenant admin), and not accessible by customer's users !**

That's why using the "current user" (myself as tenant admin) was working, and "customer user" was not working !

The "internal 500 error" was not really comprehensive in this case... maybe improve error message.

Thank for your quick support.
