### ISSUE TITLE
Types of relations doubt

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#11945]
**Component**
 * Generic

**Description**
Hi there, 

What is the difference between the relations "_Contains_" and "_Manages_"? I mean, not only theoretically, but also practically. I tried looking for that information in the Thingsboard documentation, but sadly, I found nothing.

Thanks beforehand, looking forward to hearing from you.

Kind regards.
Daniel.

**Environment**
OS: Monolitic setup using AWS infrastructure
ThingsBoard: 3.7.0PE
Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi
From [documentation](https://thingsboard.io/docs/user-guide/entities-and-relations/#relations):

> Entity relation defines connection between two ThingsBoard entities that belong to the same [Tenant](https://thingsboard.io/docs/user-guide/ui/tenants/). The relation has an arbitrary type: Contains, Manages, Supports, etc.

That means that this is just an example of possible relations names. You can use it as you need or even add your own custom relation type. 
![image](https://github.com/user-attachments/assets/5709af32-26bd-4a60-a13d-7bea89474f04)

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev 

Terrific! It is all clear now! It will be useful in several cases we have in mind, thank you very much!

Kind regards.
Daniel.
