### ISSUE TITLE
How to use custom environment variable in Rule Chain rest api node

### ISSUE THREAD

**Issue by andyabcd1** [thingsboard/thingsboard#11951]
**Expected behaviour**
I am setting a Rest Api node in Rule Chain. When there is an alarm created, thingsboard should send a rest api call to my application.

I have local and production environment in my applications, so I expect I can send the api call to the corresponding environment.

**Thingsboard Setup**
I use docker-compose.
```
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      ...
    environment:
      ...
      REST_API_URL: http://host.docker.internal:8005
    volumes:
      ...
 ```

**What I tried**
I configured a rest api rule node that use custom environment variable like below.
<img width="634" alt="Screenshot 2024-10-24 at 10 25 36 AM" src="https://github.com/user-attachments/assets/aff32916-7a07-4dd1-a98a-429fbbdf5122">

But when I check the debugging logs in this rule node, it shows an error.
```
java.lang.RuntimeException: Transport scheme(protocol) must be provided!
	at org.thingsboard.rule.engine.rest.TbHttpClient.buildEncodedUri(TbHttpClient.java:227)
	at org.thingsboard.rule.engine.rest.TbHttpClient.processMessage(TbHttpClient.java:179)
	at org.thingsboard.rule.engine.rest.TbRestApiCallNode.onMsg(TbRestApiCallNode.java:69)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:158)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

It seems like Thingsboard doesn't resolve my custom environment variable `REST_API_URL` properly. 

How to fix that, or is there any better approach in my case?

**Comment by mykhailokornieiev** [comment]
Hi. I don't understand what you are trying to achieve, but this definitely won't work that way
![image](https://github.com/user-attachments/assets/5e70aecc-201a-442d-afda-5f6e1c9d1cd7)
You can use this value only from message/metadata body of Input message (that will come from the previous rule node). You can't set it up in the environmental variables of the docker-compose.yml file.

**Comment by andyabcd1** [comment]
@mykhailokornieiev 

I have two main applications:
1. Thingsboard
2. Backend A (another backend application)

**Environments**
Both applications (Thingsboard and Backend A) have two separate branches or environments.

This means:

Thingsboard has two environments (e.g., local and prod).
Backend A also has two environments matching these branches.

![tb-restapi](https://github.com/user-attachments/assets/3ceeb1cc-3250-4bd9-b1f5-c44f5323203a)

The problem is, I use Thingsboard Version Control to sync both environment.

Let's say I add a External Rest Api rule node in my **local environment**. When I save the rule chain in Thingsboard Source Control Page, the below code(Rule Chain Configuration) will be submitted to Github

```
      "configuration" : {
        "restEndpointUrlPattern" : "http://localhost: 8000/notifications/sms",
        "requestMethod" : "POST",
        ...
```

When I restore the version in my **prod environment,**, it also gives me the same configuration
```
      "configuration" : {
        "restEndpointUrlPattern" : "http://localhost: 8000/notifications/sms",
        "requestMethod" : "POST",
        ...
```
But what I want is
```
      "configuration" : {
        "restEndpointUrlPattern" : "https://my-backend-a.com/notifications/sms",
        "requestMethod" : "POST",
        ...
```

**Comment by mykhailokornieiev** [comment]
> Let's say I add a External Rest Api rule node in my local environment. When I save the rule chain in Thingsboard Source Control Page, the below code(Rule Chain Configuration) will be submitted to Github
> 
>       "configuration" : {
>         "restEndpointUrlPattern" : "http://localhost: 8000/notifications/sms",
>         "requestMethod" : "POST",
>         ...
> 
> When I restore the version in my prod environment,, it also gives me the same configuration
> 
>       "configuration" : {
>         "restEndpointUrlPattern" : "http://localhost: 8000/notifications/sms",
>         "requestMethod" : "POST",
>         ...
> 
> But what I want is
> 
>       "configuration" : {
>         "restEndpointUrlPattern" : "https://my-backend-a.com/notifications/sms",
>         "requestMethod" : "POST",
>         ...
> 

Rest API call node can't use variables from docker-compose.yml
Also, Version Control feature can't manage the necessary URLs for each Rest API call node of necessary Thingsboard instance.
I'd recommend you use the next  workaround:
1. Save the necessary external URL as Tenant's attribute, so it won't be changed on both Thingsboard instances during version restore
2. Add this logic to your Rule Chain:
![image](https://github.com/user-attachments/assets/f01980c0-1008-4115-b702-b8ab53793d9a)
![image](https://github.com/user-attachments/assets/8358511a-2b1f-4942-9f16-75ceda5790b5)
![image](https://github.com/user-attachments/assets/226bc404-c717-4eaf-8fa2-4dbb181d2ad4)
Then, you can use attribute value as message/metadata value in Rest API call node.
You can get familiar with available documentation:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-attributes

**Comment by andyabcd1** [comment]
It's solved. Thanks
