### ISSUE TITLE
eChart legend display issue with display position = right/left and Show values = "any"

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#11959]
### **Describe the bug**
The eChart legend is displaying in a single-line layout with a horizontal scrollbar, despite the widget settings being configured as follows:
- `Display Position` = right/left
- `Show Values` = any option

<details>
  <summary>1. [SCREENSHOT] Chart legend settings (click to expand)</summary>

![image](https://github.com/user-attachments/assets/24db2ea9-7069-45e1-b6ad-37042dc27f83)

</details>
<details>
  <summary>2. [SCREENSHOT] Chart legend display (click to expand)</summary>

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/e43288bd-bd6a-4a0e-8008-40310e1b76d9">

</details>

---

### **Your Server Environment**
* Own setup
  * ThingsBoard Version: 3.6.4 PE, 3.7 PE, and 3.8.1 CE

**Your Client Environment**
* OS: Windows 11
* Browser: Chrome (latest version)

---

### **To Reproduce**
1. Add a new chart widget.
2. Add a datasource with multiple data keys, containing either telemetry values or functions like random/sin/cos.

   <details>
     <summary>Step 2 [SCREENSHOT] Example of chart data key with function (click to expand)</summary>
   
   ![image](https://github.com/user-attachments/assets/a6dd10f9-23ef-479f-b661-ae6fa0dd45e3)
   
   </details>

3. In the `Appearance` tab of the widget settings, set the legend to display on the right/left side and select any `Show Values` option.

   <details>
     <summary>Step 3 [SCREENSHOT] Chart legend settings (click to expand)</summary>
   
   ![image](https://github.com/user-attachments/assets/b507eca0-329d-429d-a9bd-c15a6c4f3bed)
   
   </details>

4. Apply the widget settings. The legend will display on the right/left side but in a single-row layout with a horizontal scrollbar.

   <details>
     <summary>Step 4 [SCREENSHOT] Chart legend display issue (click to expand)</summary>
   
   <img width="548" alt="image" src="https://github.com/user-attachments/assets/0282c4ba-b2ad-43a6-8a32-589f34dcfade">
   
   </details>

### **Expected behavior**
- When the chart legend is set to left or right, it should display in a single column with a vertical scrollbar, similar to the old deprecated timeseries chart widget.

   <details>
     <summary>[SCREENSHOT] Expected result (click to expand)</summary>

   ![image](https://github.com/user-attachments/assets/f467656f-3322-4f74-90ae-ce3ca2f81a7e)
   ---
   <img width="1276" alt="image" src="https://github.com/user-attachments/assets/03d18346-30a9-453d-a92f-ef61bdccb9f1">

   </details>

- The new eCharts widget settings could also include a legend direction option similar to the old deprecated timeseries chart widget.

   <details>
     <summary>[SCREENSHOT] Expected settings (click to expand)</summary>

   ![image](https://github.com/user-attachments/assets/07d0afe3-4ceb-4dee-86e4-5d53ca4f8aab)

   </details>

**Comment by mykhailokornieiev** [comment]
Hi. I was able to reproduce this behavior and already created a ticket for our developers. 
There's no set timeframe for this bug fix; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
