### ISSUE TITLE
How to add other languages ​​to the Thingsboard interface?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#11961]
**Component**

 * UI

**Description**
How to add other languages ​​to the Thingsboard interface? I need to add Uzbek language

**Environment**

 * OS:  Ubuntu/Windows
 * ThingsBoard: 3.8 CE
 * Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi. For such a purpose, you can translate on of available locales on your own and then contribute it so it may added in future releases
https://github.com/thingsboard/thingsboard/issues/11927#issuecomment-2435020628

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
