### ISSUE TITLE
Method in the switch button not updating from setValue to any other...

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11963]
I am trying to update the method of the switch button but it not updating..

![image](https://github.com/user-attachments/assets/b253b784-4ecb-41e1-84a8-bfcf522defcb)

I have updated the method but I receiving a method...
![image](https://github.com/user-attachments/assets/20f27bdf-a60f-4a5f-b522-96439e6682fa)

why this is happing....

**Comment by mykhailokornieiev** [comment]
Hi. Please clarify what Control Widget you use.

**Comment by mykhailokornieiev** [comment]
Are you sure that you saved all changes?
I'm unable to reproduce it with Toggle Button widget (it looks like it on your screenshot)
![image](https://github.com/user-attachments/assets/224cf1a3-12b3-4a33-aff9-d2f3897ffb39)
```
mykhailo@kornieiev:~$ curl  https://tbqa.cloud/api/v1/New_access_token/rpc
{"id":3,"method":"setState3","params":true}
mykhailo@kornieiev:~$ curl  https://tbqa.cloud/api/v1/New_access_token/rpc
{"id":4,"method":"setState3","params":false}
mykhailo@kornieiev:~$ 
```

**Comment by Vaibhav0216** [comment]
but in my case it happing.
1) I have saved the changes.

**Comment by Vaibhav0216** [comment]
mykhailo@kornieiev:~$ curl  https://tbqa.cloud/api/v1/New_access_token/rpc
{"id":3,"method":"setState3","params":true}

how you generate the access_token?

**Comment by Vaibhav0216** [comment]
I have make it a custom widget under control widget category .  Per-existence widget is work properly. but this is not working.

**Comment by mykhailokornieiev** [comment]
> how you generate the access_token?

You can change it manually
https://thingsboard.io/docs/user-guide/ui/devices/#manage-device-credentials

> I have make it a custom widget under control widget category . Per-existence widget is work properly. but this is not working.

In this case, the problem is definitely in your custom widget code, so I won't be able to help. I will add "Help Wanted" label to this ticket so maybe someone in community will be able to help you.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
