### ISSUE TITLE
Button To Change Layer On Map Widgets

### ISSUE THREAD

**Issue by TortueHardie** [thingsboard/thingsboard#11960]
In the map widget, is it possible to add a button that allows the user to switch the map layer type, for example, switching from roadmap to satellite or plan view? And is there a possible workaround using custom actions? I searched, but couldn’t find how to do it.

**Comment by sumin-denys** [comment]
Thank you for your report! 
For now, changing the layer in the map widget is impossible.
We already have a PROD-4879 ticket about this feature request. Once the product team reviews this ticket, we’ll post an update on when this feature could be delivered if they decide to add it to the product.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
If you have any further questions or require clarification, please let me know.
