### ISSUE TITLE
How to use State Behavior in UI throgh Setting Schema in custom widget

### ISSUE THREAD

**Issue by MHamzaBajwa** [thingsboard/thingsboard#11979]
**Component**

 * UI - Custom Widget using Latest Value
 
**Description**
I am working on the custom widget (using type Latest Value) for achieving functionality on ON/OFF toggle button, I have MQTT protocol on the device end, and I want to add options for state behavior like this (this SS form Single Switch widget)
![image](https://github.com/user-attachments/assets/8d23fc6c-3b14-44a0-90c1-44857fe1db88)
![image](https://github.com/user-attachments/assets/215d71bf-e017-40b3-b8bc-de4028df756d)

Here is the current output of my widget in the appearance section in which I want to show state behavior options with options for customizable functions and actions
![image](https://github.com/user-attachments/assets/324a013e-b7f2-4bcf-bc0b-e8d426872a70)

I have also explored schema form of Thingsboard [here](https://networknt.github.io/react-schema-form/) but issue not fixed
Please let me know if something is wrong or missing in the schema, I am new to ThingsBoard 
thank you for your support,

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.8
 * Browser: Chorme

**Comment by MHamzaBajwa** [comment]
@mykhailokornieiev I also trying with control widget 
![image](https://github.com/user-attachments/assets/8d073af1-d641-41c0-8623-ec9711c0a813)

but I want to know how can we show behavior section with states(using setting schema) having feature of returning custom function (as I requested in question images #1 and #2), I just want to replicate behavior section in my custom widget using setting schema, 
I hope you got my point if not please let me know

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it still relevant, feel free to open a new ticket with full description of your request.
