### ISSUE TITLE
Time series chart - Setting ticks step on one Y axis affects the ticks on the other Y axis

### ISSUE THREAD

**Issue by JimmyPedersen** [thingsboard/thingsboard#11973]
**Describe the bug**
When I set tick step to 1 on one Y axis it affects the rest of them negatively, they loose their ticks.
See screenshots

**Your Server Environment**
Thingsboard.cloud

**Your Client Environment**
Windows 11

* OS: [e.g. iOS]
* Chrome 130.0.6723.70

**Expected behavior**
Tick step should only affect the selected axis

**Screenshots**

True/False Y axis set to Tick step auto
![image](https://github.com/user-attachments/assets/118a2279-2540-4d44-83c4-ef515f6eedb1)

True/False Y axis set to Tick step 1
![image](https://github.com/user-attachments/assets/b1c241e1-b736-414e-9230-a9df812283ba)

**Comment by mykhailokornieiev** [comment]
Hi. Please clarify, do you use Ticks interval with some specified value for one Y-axis and auto for another?

**Comment by JimmyPedersen** [comment]
Yes. I set, in this case, the True/false Y-Axis to Tick interval 1 and the rest are on auto

**Comment by mykhailokornieiev** [comment]
Thank you for this clarification. I was able to reproduce this behavior and this is correct one, since there is no default Ticks Interval value pre-defined. As soon as you change Ticks Interval value for any of axises it will become default. You can change value for second axis any time.

**Comment by JimmyPedersen** [comment]
But why would you assume that tick interval is what is wanted on the other axis when they are set to auto?

Auto in this case seems to mean two things.
When no tick interval at all is entered it means what I always thought it meant: Use an appropriate tick interval.
Then when one (or more) tick interval is entered it means use the same as that.

What happens with auto if there are 2 out of n tick intervals set? Which does it use then?

Sorry but that's not logical.
If I want many of the axis to be fixed I set all of their tick intervals manually.
If I want one that scales automatically I would expect to use Auto.

If this breaks backwards compability I think you need to consider a flag that can make the auto configured ticks truly automatic otherwise it's impossible to make a graph with mixed fixed and automatic tick intervals.

**Comment by mykhailokornieiev** [comment]
Hi. I've added a ticket to our backlog for our developers. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15633 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
