### ISSUE TITLE
Entity profile attributes

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#11971]
**Is your feature request related to a problem? Please describe.**
No, I guess it is only a limitation.

**Describe the solution you'd like**
Is it possible to include attributes (or something like that) to the entity profiles in future versions? It will be great to add some extra information there.

**Describe alternatives you've considered**
Right now, we are using the "_description_" tab, but this is going to be unmanageable in the nearby future.

**Additional context**
No additional context.

**Comment by mykhailokornieiev** [comment]
Hi
We already have such feature request in our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
