### ISSUE TITLE
Report are not generated in the user language

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#11970]
**Describe the bug**
Report are not generated in the user language.

When using the generate report rule node, and setting the `userId`  by script, from `msg.originatorId` (for example).
```
"useCurrentUserCredentials": false,
"userId": msg.originatorId
```
The report is generated and I can send it by email.

But in my case I sent an email per customer user.
So each user generate its own report to be sent (according user rights/visibility).
But the user language preference is not apply when generating report.

![image](https://github.com/user-attachments/assets/29a1ab58-74cb-4da3-995b-76cb8a655353)

`Add reportConfig` Node :  

```
var newMsg = msg;

var dashboardId = "ef776a20-9087-11ef-bb05-3f7cd9782d8e";

newMsg.reportConfig = {
    "baseUrl": "https://mds.ascolab.fr",
    "useDashboardTimewindow": true,
    "timewindow": {
        "selectedTab": 1,
        "history": {
            "historyType": 0,
            "interval": 1000,
            "timewindowMs": 86400000
        }
    },
    "namePattern": "report-%d{yyyy-MM-dd_HH:mm:ss}",
    "type": "pdf",
    "timezone": "Europe/Paris",
    "useCurrentUserCredentials": false,
    "userId": msg.originatorId,
    "dashboardId": dashboardId,
    "state": ""
};


newMsg.sendEmail = true;


return {
    msg: newMsg,
    metadata: metadata,
    msgType: "generateReport"
};
```

`msg.originatorId` is the user Id.

**Your Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)
* Prototype Plan
* Version 3.8.1.5PAAS

**Your Client Environment**
* OS: Windows
* Browser : Chrome
* Version : Version 130.0.6723.70 (Build officiel) (64 bits)

**To Reproduce**
1. Create a rule chain include a script node that create "reportConfig" information in a message, using a userId.
2. Connect it to `generateReport` node
3. Send report by email
4. Check report in the email, or in generated files.

(Maybe same problem using "scheduler" ?)

**Expected behavior**
User's language preference must be apply when generating report.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce this behavior via Scheduler (it uses Generate Report rule node anyway)
My tenant user uses English and customer user uses Ukrainian:
![image](https://github.com/user-attachments/assets/3fb8a867-4bfb-492f-bee0-e954da23a8ca)
![image](https://github.com/user-attachments/assets/ea6f6c8a-900d-4c90-9d38-913266056b4a)
Try to restore default Generate Report rule chain logic and check the correct message in debug. 
Also, are you sure that this customer uses translation configured in Account -> Profile and not browser settings?

**Comment by GregAscolab** [comment]
I try with scheduler... something strange...

1/ Click on "Generate Test Report" in scheduler dialog box :
The message is not routed as "generateReport" message type, but updateValue...
So generation of the report is done... magically internally ??? ;-)
There is no rule chain to manage it, but I get a pdf report : Always in english, no user language, whatever my tenant user language is.

2/ When scheduler fire it's event :

- I get a generateReport message in rule chain.
- It is routed to the standard `Generate Report `rule chain (no modification)
- I get no error in generation report node.
- userId is equal to the user I want (g.pub)
- User language setting is selected in Thingsboard user account (it's a client test user I use).
- The email is sent
- **The report included in email is... in wrong language : English, instead of French ?!**

My scheduler config :
![image](https://github.com/user-attachments/assets/fbc46e86-e9ea-4b4b-9e8a-b57032f2bf43)

Generate Report Node debug :  
![image](https://github.com/user-attachments/assets/a7698de5-8632-441d-a6f0-79d0711de834)

![image](https://github.com/user-attachments/assets/29165234-1969-4a3b-9cf5-9d0f03ff4d6e)

![image](https://github.com/user-attachments/assets/1ba8afec-08b0-451b-92a6-a082de5f9412)
=== **a6254680-92a3-11ef-9285-db91bf15ba2b**


Received email :
![image](https://github.com/user-attachments/assets/249ec90c-91ec-463f-b981-10223cefabc8)

Dashboard from g.pub account in French, on web site :
![image](https://github.com/user-attachments/assets/27779be5-f22f-4961-b982-0bf2d6ce7865)


g.pub user settings :
![image](https://github.com/user-attachments/assets/3fe06f46-3138-4226-8f3b-513f6ba9de2f)



I don't understand...

**Comment by mykhailokornieiev** [comment]
Plaese clarify the next:
Do you use customer user or sub-customer user credentials?
Is it some standard widgets with default translations? 
Do you use custom translation, maybe in {i18n} format?

**Comment by GregAscolab** [comment]
Informations :

> Do you use customer user or sub-customer user credentials?

I want report generated by customer user (g.pub)
No sub-customer users for the moment, but can be in futur.
![image](https://github.com/user-attachments/assets/fa561999-2c17-4eeb-a4ae-08487dbc05ee)


> Is it some standard widgets with default translations?
> Do you use custom translation, maybe in {i18n} format?

Yes and no, standard alarm table widget.
But I also use i18n translation from "standard translation" and from added "custom translation".

![image](https://github.com/user-attachments/assets/cb5c4ae3-fff9-4cb5-b828-12b201ed5978)
![image](https://github.com/user-attachments/assets/57e0198b-de80-4b9a-80dd-b80e5f5e0591)

And lot of custom i18n in cell content :  
![image](https://github.com/user-attachments/assets/e445ee36-8c68-4f3e-b551-8dd2b4bab78d)

**Comment by mykhailokornieiev** [comment]
Still can't reproduce under specified conditions
```
var map = {
    "CRITICAL": "{i18n:custom.severity.critical}",
    "MAJOR": "{i18n:custom.severity.major}"
};
return map[value] ? map[value] : value;
```
```
{
  "custom": {
    "severity": {
      "critical": "Custom Critical Severity",
      "major": "Custom Major Severity"
    },
    "title": {
        "alarmTitle": "Custom Alarm Title"
    }
  }
}
```
![image](https://github.com/user-attachments/assets/dc1b3d4d-e58b-47bf-97d5-555f6f235a4f)

**Comment by GregAscolab** [comment]
Hum...

I checked my "g.pub" user...

Something strange :
In user account parameters, the language is set to "French".
But I cannot change it !

I can select a new language, but there is no "SAVE" button.
So I get warning popup message : "You didn't save changes..."

It seems to be my problem !

![image](https://github.com/user-attachments/assets/6778be9a-c8fc-4a3d-bedb-e146807c3033)

![image](https://github.com/user-attachments/assets/a72d9611-ceb3-4226-8dae-8b8a63379d1a)


When I use my tenant user to generate the report : the report language change according my tenant user language settings !

Good... 

1. It seems that my "customers user" don't have the right to change language. Which right it is ?
2. So there is something mixed up : In a way or another, the language has been set to the user (when creating the new user?), because logging as g.pub make the site in French.  
But report engine seems to check if user has the right to change is language.

**Comment by mykhailokornieiev** [comment]
> It seems that my "customers user" don't have the right to change language. Which right it is ?

This is "Profile" permission. 

> So there is something mixed up : In a way or another, the language has been set to the user (when creating the new user?), because logging as g.pub make the site in French.
But report engine seems to check if user has the right to change is language.

I was able to reproduce your behavior and it is not a bug.
1. Create a user without "profile" permissions
2. If you log in as this user from a browser where the browser language is, for example, French, the system will automatically select the browser language.
3. tb-web-report is a headless browser with default language settings, that is, it uses English. That is why, since you have never chosen a language for the user, the language of the browser is chosen
You can avoid this behavior as soon as you change the language manually.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by GregAscolab** [comment]
I was writting a quick reply just before you close it ;-)

I was asking myself : As tenant administrator, "how to set the user language ?"
I can't find it in the user profile, or other...
So in my use case, even if my users are French (using French web browser), they will always receive report in english... because I can't change there language.

So it's seems to me that "Profile" permission has to be set for all users of the tenant...

**Comment by GregAscolab** [comment]
Furthermore, my tests confirm that, even if the user has the "Profile" permission to change its language :
The user has to go at least one time to its own profile, then, change the language from French to another and then back to French, in order to make the "Save" button accessible.
Then click "Save" button.

Only after this procedure, the reports are generated in French !

**Comment by mykhailokornieiev** [comment]
> I was asking myself : As tenant administrator, "how to set the language of a user?"

There are two options:
1) Users can change it by themselve. 
2) You can use "login as" feature, login as the customer user and change it from your end. 
![image](https://github.com/user-attachments/assets/28799b5a-cbff-4012-9a09-5923ec754a81)
![image](https://github.com/user-attachments/assets/b0e19ad2-5682-473f-bbcb-1d28ff52dd80)

> 
> So in my use case, even if my users are French (using French web browser), they will always receive report in english... because I can't change their language.
> So it's seems to me that "Profile" permission has to be set for all users of the tenant...

It is enough to be set only for the user with selected credentials.

> Furthermore, my tests confirm that, even if the user has the "Profile" permission to change its language :
> The user has to go at least one time to its own profile, then, change the language from French to another and then back to French, in order to make the "Save" button accessible.
> Then click "Save" button.
> 
> Only after this procedure, the reports are generated in French !

This is correct and there is no workarounds, since if your browser use French as default language, then Thingsboard will automatically use it for translation. But that will not make French the default language of this customer user. As soon as you login in browser with default language English, your user will have this translation.
The same situation is with tb-web-report. Since this is a headless browser, it will open pages with its default language, which is English. 
So, you anyway need to make French the default Thingsboard user language manually.

Regarding your struggling with providing permissions for the necessary customer user I highly recommend you getting familiar with the following documentation:
https://thingsboard.io/docs/pe/user-guide/rbac/#generic-roles

**Comment by GregAscolab** [comment]
Thank you for this feedback.

Maybe think of a new feature request :  
"Ability to set user language during user creation, or user activation."  
and/or  
"Ability to set user language from user details" (why it's not displayed here as any other information : name, email, etc... ???)

Else I'm quite sure all the new users will never go to their profile to set their language (because it's automatically done by navigator language, which is good), and I don't want to do it myself everyday for every new user ;-)

**Comment by mykhailokornieiev** [comment]
To ensure the best user experience, we’ve decided to follow each user’s browser language preference rather than setting a single default language for all.
Using the browser’s locale setting makes our content more accessible and avoids the frustration of needing to switch languages manually for the end user. This approach meets user expectations and aligns with best practices for a seamless, user-friendly experience.

Because of that, we won’t implement setting the default language for all users, so this feature request is rejected.

**Comment by mykhailokornieiev** [comment]
It's by design and won't be changed

**Comment by GregAscolab** [comment]
> Nope, it's not a bug, since you still can (and need) set up default language for user. Tenant administrator can provide the necessary permissions, so user can set default language.

I will call you to change user language of all my tenant users by yourselve, using the "log as user" feature, when they will call me to say : "my report is not in the right language, even if my website is in the right language, why ?"

Or even give your phone number to answers to them ;-)
:-D

I'm kidding of course, but sometime we have to think of end users... even if it's not "a bug" as you said.
I'm trying to give you my feedback to improve use cases of Thingsboard.

Best regards, and continue your excellent job on Thingsboard.
