### ISSUE TITLE
fail to connect to thingsboard localhost:8080

### ISSUE THREAD

**Issue by yulin-willbeok** [thingsboard/thingsboard#11987]
Hi, I have successfully installed ThingsBoard on my PC following the necessary procedures and installed the required applications.
I was able to start ThingsBoard on my cmd in admin mode and when I check my services on my PC I see that ThingsBoard is already installed, which is okay because I installed it from the cmd before and I can start, stop, and restart it with no errors except when I try to go to my Google Chrome at localhost: 8080, and I said I couldn't access the site.
So I checked the listening ports on my computer, and there are no conflicts, and interestingly, when I start ThingsBoard, which is supposed to be listening on port 8080, I find that the port doesn't even appear anywhere.

 * OS:  windows11
 * ThingsBoard: 3.5.1
[thingsboard.log](https://github.com/user-attachments/files/17606989/thingsboard.log)

**Comment by pon0marev** [comment]
We want to inform you that we have closed your ticket as we have not received any updates on this issue. If you still have questions or encounter similar issues after upgrading to the latest version, please reopen this issue.
