### ISSUE TITLE
I am unable to generate the report of telemetry...

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11995]
I am new to thingsboard. I want to generate the report in the following format. 

![image](https://github.com/user-attachments/assets/75af4889-ad20-463b-b9d2-61f247a63434)

how can i do this?

**Comment by mykhailokornieiev** [comment]
Hi. Please describe your request in as much detail as possible. Report of what exactly do you want to generate? Is it dashboard or widget?

**Comment by Vaibhav0216** [comment]
I want to generate the report of the telemetry values ( eg. temperature and
humidity ). I want to generate this report through the dashboard. Like
shown in the image above.

**Comment by Vaibhav0216** [comment]
![image](https://github.com/user-attachments/assets/fea14d01-7fde-4c94-849e-4743e494e048)

I want functionality like when i click on the "Show Report" then report generate in the tabular format. How can i achieve this. 
how can i implement rule chain and implement result on this.

**Comment by mykhailokornieiev** [comment]
Hi
Excel/CSV export are available as standard functionality only for widgets. There are plans to add it as available formats for Scheduler -> Generate Report (Dashboards). 
If your request is related to custom widget, then I won't be able to help you with it.
In this case, I will add "Help Wanted" label to this ticket, so maybe someone from community will be able to help you.
