### ISSUE TITLE
Things board getting shut . not able to open

### ISSUE THREAD

**Issue by Reshmadirector** [thingsboard/thingsboard#11999]
our ip address - [157.245.97.114:8080](http://157.245.97.114:8080/) ( configured with digital ocean)

mail id  - reshmakprasad2418@gmail.com

we have been using thingsboard from past 8 months and we were very happy with the performance and we were planning to take it up for the next production stage. But, all of a sudden from 15 days, its not working properly and its not updating. Last week same problem occured and it started working after the restart as per our tech team. But, we are really not sure about the problem. Kindly help us to resolve as our production order is pending due to this issue.

**Comment by Ultrazombie** [comment]
Hello @Reshmadirector 
Please provide the thingsboard.log file so we can investigate your problem.

**Comment by Reshmadirector** [comment]
---------- Forwarded message ---------
From: Reshma Prasad ***@***.***>
Date: Wed, 6 Nov 2024 at 16:07
Subject: Re: [thingsboard/thingsboard] Things board getting shut . not able
to open (Issue #11999)
To: thingsboard/thingsboard <
***@***.***>


Hi

Please find attached problem log screenshots.


REgards,

Reshma Prasad

**Comment by dealnat** [comment]
@Reshmadirector I can't see any screenshots

**Comment by Reshmadirector** [comment]
Hi,

Again we have faced the same issue and would want to migrate or upgrade the
version.

Now we are using Digital ocean as our server platform.

We know that once we upgrade to paid and robust version, we can have
thingsboard server and we can get us out of digital ocean and stick on to
things board

Kindly assign someone to help us in having a smooth transition.


Regards,

Reshma Prasad
9380390736

**Comment by dealnat** [comment]
@Reshmadirector please attach logs or screenshot to the github issue, they were not attached via email.

**Comment by dealnat** [comment]
Closed due to inactivity
