### ISSUE TITLE
'Koninkrijk België' is not a language it's a country with 3 official languages.

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#11991]
**Describe the bug**
'Koninkrijk België' is not a language
https://en.wikipedia.org/wiki/Languages_of_Belgium

Present in version 3.8.1 PE and CE (and earlier versions)

Correct would be Dutch or 'Dutch (Belgium)'
There is also Dutch (Netherlands) that is a little different.

I would just change the selection 'Koninkrijk België'  to 'Dutch'

Thanks

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
I'm not sure where it can be found:
![image](https://github.com/user-attachments/assets/74a124c8-32dd-4a49-8bda-006040aad075)
![image](https://github.com/user-attachments/assets/5a451bdd-696a-408c-922e-286a2b46f9d5)
Please describe this ticket in as much detail as possible

**Comment by KenSense** [comment]
hhmm in profile and white labeling i see this (the PE version is 3.6.4 but I see the same in CE version 3.8.1)
![image](https://github.com/user-attachments/assets/bc90926b-800b-4e00-b69b-247f134833f9)
![image](https://github.com/user-attachments/assets/c8d96c2c-c60f-4d6a-930d-399d83323de0)

Maybe something is dragged along from old versions and never got updated in the database?
or does it read something from a file?
Using Ubuntu 22.04 (for both CE and PE)

I also don't see the same screen as yours?

**Comment by mykhailokornieiev** [comment]
We have no mentions of "Koninkrijk België" in Thingsboard code, only in your ticket
![image](https://github.com/user-attachments/assets/21850f45-b6fa-4bd2-9a4e-c76b4f5acdcf)
Please check your browser settings; maybe it translate items by itself.

**Comment by mykhailokornieiev** [comment]
I've found it. Will check it and came back with update later.

**Comment by mykhailokornieiev** [comment]
Hi. This is valid improvement that I've already added to our backlog for developers.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
