### ISSUE TITLE
Can't change Thingsboard Bind Port to 80

### ISSUE THREAD

**Issue by AlanTwigg** [thingsboard/thingsboard#12001]
I Installed Thingsboard 3.8.1 on Ubuntu server 24.04.1 - all installed correctly and I was able to connect to the app on port 8080.

However when I changed the bind port to 80, in /usr/share/thingsboard/conf/thingsboard.yml  I could no longer connect.
Issuing a netstat  -plnt ất the command prompt showed that the server isn't listening on any port.

**Your Server Environment**
* own setup
  * Deployment: monolith 
  * Deployment type: deb
  * Community
  *Version: Ubuntu 24.04.1 , TB: 3.81

**Your Client Environment**
**Desktop  - Mac mini
* OS: MacOS  15.0.1
* Browser : None
* Version  N/A
Mac ssh into Ubuntu server.
Ubuntu cmd line

**To Reproduce**
1. sudo nano /usr/share/thingsboard/conf/thingsboard.yml
2. edit  HTTP_BIND_PORT:80
3. save file, reboot server.
4. issue sudo net stat -plnt , & inspect listening ports
5.  Repeat steps and change http port to 8080
6. netstat shows listening port as 8080

**Expected behavior**
I would expect to see the server listening port as configured, port 80. or any port of my choosing.
Do not wish to install a workaround proxy.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
