### ISSUE TITLE
Custom widget action, navigate to dashbaord with state entity parameter

### ISSUE THREAD

**Issue by SindreLindahl** [thingsboard/thingsboard#12003]
Got a custom widget. In dashboard when editing widget, can add custom action. Configure to navigate to other dashboard and set entity from widget using state entity parameter name. User can then select a device to navigate to another dashboard.

This is what I've done so far:

Create custom action:
`self.actionSources = function() {
    return {
        'customAction': {
            name: 'Card click action',
            multiple: false
        }
    };
}`

Execute action:
`self.ctx.actionsApi.onWidgetAction($event, customAction, entity.id, entity.name);`

And btw to get the action object, can use this to get a list of actions and then find it in there:
`const customActionList = self.ctx.actionsApi.actionDescriptorsBySourceId.customAction;`

But how to apply state entity parameter name to the dashboard being navigated to?

**Comment by SindreLindahl** [comment]
I have tried setting stateParams in the current dashboard.
{
        entityName: "name",
        entityLabel: "label",
        targetEntityParamName: "selected_building,
        entityId: "id"
}

Using 
self.ctx.stateController.updateState(null, stateParams, false);

Or even openState function.

Can use self.ctx.stateController.getStateParams(); to verify the values are set in current dashboard.

But when action triggers, state is not sent to the new dashboard being navigated to.

**Comment by CalmNite** [comment]
hello @SindreLindahl 

I use the following function.

self.ctx.router.navigateByUrl("/dashboards/" + dashboardID + "?state=" + )

at the end you have to use the following format. Is a string in base64 

var state= [{id: "default", params: {entityDashboard: {entityId: e.entidad.id , entityName: e.id}, entityName: e.id}}]

example

![imagen](https://github.com/user-attachments/assets/22f98152-cb30-421d-947e-6dbe38a7a773)
 
default is the state of the dashboard you wanna load and entityDashboard you have to include it on your entity alias :

![imagen](https://github.com/user-attachments/assets/a39b9dd5-7297-40a4-9278-dd72eeb9ae4a)

var base64 = encodeURIComponent(btoa(JSON.stringify(state)));
self.ctx.router.navigateByUrl("/dashboards/b95cdb10-6f4d-11ef-a467-5b5c7d83b52e?state=" + base64);

 be careful with the format or name sometimes i had problems with special characters!

I hope this helps you!

**Comment by SindreLindahl** [comment]
Thanks, that worked! You think the built-in ctx.navigateByUrl is preferable over the universal window.location.href? And finally, what's up with using 'var' in 2024? 😛

**Comment by CalmNite** [comment]
Well from my own experience, I think the router.navigateByUrl() is handled by an angular service and it ensures that the content of the aplication changes without a fully reload of the page which is what window.loacation.href does. If you are navigating inside the same thingsboard instance I would use navigateByUrl.

What is recomended to use? let instead of var? XD

**Comment by SindreLindahl** [comment]
Awesome, that makes perfect sense. Yeah const/let is used instead of var. There are some niche use cases, but not for 'normal' code like here. It can lead to some difficult to find bugs which can be surprising when coming from other languages.

**Comment by CalmNite** [comment]
Thanks for the info. 👍 I will take it into account in the future

**Comment by epalchenko** [comment]
Closed due to inactivity
