### ISSUE TITLE
How can i call api on clicking the button on the widget. 

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12006]
I have created a widget in which a button is available.  Below is image of the dashboard. 
![image](https://github.com/user-attachments/assets/55a714b7-0ff2-403d-a73e-54f116f4a09a)
I would like to call the api when i click on the "show record" button. 
how can i achieve this ?

**Comment by Vaibhav0216** [comment]
[report_log_static_widget.json](https://github.com/user-attachments/files/17643055/report_log.json)
[report_log_latest_value.json](https://github.com/user-attachments/files/17643056/report_log_latest_value.json)
[report_log_control_widget.json](https://github.com/user-attachments/files/17643057/report_log_control_widget.json)

I have made widget in all three types but i didn't find out way. 
Please help me on this.

**Comment by CalmNite** [comment]
Hello @Vaibhav0216 

You can try something like this. This is a custom widget:

![imagen](https://github.com/user-attachments/assets/2069f37d-ad0d-4e6b-b5cf-b9e44cd22f67)

in the button add the event (click)="api_call"

then in you onInit create a fucntion and inside try to add a fetch request or a XMLHttpRequest(). Both are posible with javascript.
 
 self.ctx.$scope.api_call= function(){
//YOUR app call
}

Good luck i hope this helps you!

**Comment by devaskim** [comment]
@Vaibhav0216 @CalmNite 
To call HTTP REST API of some service, including TB, you can do this:
```
    self.ctx.http.post(`/api/rule-engine/`, JSON.stringify(data)).subscribe(
        response => {
            onSuccess();
        },
        error => onError(error, 'send message to rule chain')
    );
    ```
