### ISSUE TITLE
[MQTT Transport] How can you set the RETAIN flag on messages sent to subscribers of the shared attributes topic?

### ISSUE THREAD

**Issue by msanchezc** [thingsboard/thingsboard#1200]
I need to set the RETAIN flag on shared attributes updates so the subscribers can retrieve the last valid message when they first subscribe to the topic `v1/devices/me/attributes`. I've been looking for days in the code but I can't find a proper way to do it. Is this possible?

**Comment by vparomskiy** [comment]
Before subscribing you can request client\shared attributes from the Thingsboard using standard API:
https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server

**Comment by msanchezc** [comment]
Thanks @vparomskiy, I finally convinced my colleagues that requesting attributes was the way to go with ThingsBoard, not setting the RETAIN flag.
