### ISSUE TITLE
Role permissions bug

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#12015]
**Describe the bug**
We have found a bug related to the user roles, where certain information is visible when it should not be that way.

**Your Server Environment**
* Own setup
  * Deployment: monolith
  * Deployment type: k8s
  * ThingsBoard Version: 3.7.0
  * Professional Edition

**Your Client Environment**
* Browser: Chrome
* Version: 130.0.6723.70

**To Reproduce**
1. We have created a role with limited permissions (mostly, read devices, read assets, read alarms, read entities, see dashboards... a simple watcher customer).
2. We have created a user that will be linked to that role.
3. We have assigned the role to the user.
4. When we login with that user, we can see options that are not supposed to appear (resources).

* For further information, see the pictures attached in the _Screenshots_ section.

**Expected behavior**
We are not supposed to see things that are not related to the role permissions such as resources. It is a problem since the user is capable of deleting elements there such as pictures used in several dashboards.

**Screenshots**

1. 
![Permissions](https://github.com/user-attachments/assets/dd3aa6b0-9543-4667-975c-2eb659a6e9d4)

2.
![User](https://github.com/user-attachments/assets/adeca5f5-2554-4743-a7e7-d1965de78b14)

3.
![Results](https://github.com/user-attachments/assets/5d5d6abb-8929-444a-8fff-d693528efd2c)

**Additional context**
It is a production environment, so it is a little bit urgent to find a solution / work around.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev ,

Thank you very much for your reply. Well, we do not think it can be considered as a normal behave, if you have no permissions but you are able to delete resources... it is weird.

This is not personal, do not take it personal, we also think Thingsboard is a extraordinary tool (we are using in several scenarios in fact), but we have different points of view :)

Thank you very much for your feedback.

Kind regards.
Daniel.

**Comment by mykhailokornieiev** [comment]
Hi. We already have a ticket in our backlog to improve this behavior. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
