### ISSUE TITLE
Enhancement Request: Advanced Search in Timeseries Table Component

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#12018]
Hello team,

I’m looking to implement an advanced search functionality within the time series table component of the dashboard. Specifically, I would like to:

Perform searches based on values in a specific column within the table.
Layer additional search conditions on top of the initial column-based search.
Could you provide guidance on how to achieve this, or consider adding support for this feature if it's not currently available?

Thank you for your assistance!

**Comment by mykhailokornieiev** [comment]
Hi. Currently, there is no possibility for such advanced search functions. However, such feature request was previously added to our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
