### ISSUE TITLE
Entity Hierarchy - show thingboard customer groups

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#12016]
Hello, is there a way to show in a entity hierarchy all the structure from thingsboard, starting from the customer groups from the owner? I do not know if anyone has any code and the alias, or something because the widget says "Loading..." like it does not fetch the alias, thanks!

Thingsboard hierarchy:
![image](https://github.com/user-attachments/assets/04054256-4ea2-471b-9591-82436a0e1f2c)

Hierarchy not loading
![image](https://github.com/user-attachments/assets/2c72235b-8668-4e09-a20b-ede73584ff54)

Alias of the hierarchy not loading, the starts with C-, was made to difference the GROUPS and the CUSTOMERS
![image](https://github.com/user-attachments/assets/9450aef5-ddee-4404-8caa-691d36d70d52)

Currently I have this widget working which fetches the current customer selected, but i want to fetch in other hierarchy all the customers 

![image](https://github.com/user-attachments/assets/3c51eaf3-9be9-4207-b7b8-426f98210e6a)

**Comment by mykhailokornieiev** [comment]
Hi
There is no possibility to display in Entities Hierarchy widget all the structure from thingsboard like in Customers Hierarchy tab. This widget is designed to display only selected entities their relations.

**Comment by nicovon24** [comment]
Hello, okay but
why is the reason of the widget if I can not get all my hierarchies in an administration dashboard? It is really greating getting the selected ones, but it is really incomplete, thanks

**Comment by mykhailokornieiev** [comment]
This widget is designed to display hierarchy of **relations** between selected devices. In case you need to use Customer Hierarchy, then you can either the use standard tab, or create your own custom widget

**Comment by nicovon24** [comment]
The typical answer "do it custom", thanks anyway but I thought the purpose of this widget was something else
