### ISSUE TITLE
Get 408 error when send server side RPC call to device

### ISSUE THREAD

**Issue by lomal788** [thingsboard/thingsboard#1202]
Hi team,

I follow this document: https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api to send server side rpc to device, but always get the 408 error code when sending the http post request, is there any issues in this api call? thanks.

and i follow this issue https://github.com/thingsboard/thingsboard/issues/245 thingsboard.yml queue_max_size to 10000 but it won't work. always get 408 error code.

I'm using m4.large AWS,thingsboard 2.0, postgresql 9.5, 10 mqtt device is connected and sending 6 data for 30 second each devices.

process
1.device sending data to thingsboard via mqtt
2.thingaboard call rest api tomcat spring api server
3.spring api server processing data to control device.
4.send RPC to thingsboard

I have 408 error on every 4 step.

even get 408 when getting access token.

**Comment by vparomskiy** [comment]
What **callType** are you using? Is it **oneway** or **twoway**?
If it is a **twoway** - are you sure that the device accepts command from the thingsboard and return response? Default timeout for the response is 10 seconds.

Note that Rule Engine is responsible for sending a command to the device and handling the response.
You can enable debug in your Root Rule Chain for nodes **Message Type Switch** and **RPC call Request** to see how messages are processed.

I have another question - do you see rpc command on the device?

**Comment by lomal788** [comment]
> What **callType** are you using? Is it **oneway** or **twoway**?
> If it is a **twoway** - are you sure that the device accepts command from the thingsboard and return response? Default timeout for the response is 10 seconds.
> 
> Note that Rule Engine is responsible for sending a command to the device and handling the response.
> You can enable debug in your Root Rule Chain for nodes **Message Type Switch** and **RPC call Request** to see how messages are processed.
> 
> I have another question - do you see rpc command on the device?

I'm using onway calltype.
and getting 408 error when 3 party server call oneway call RPC  to thingsboard even thought device is connected via mqtt.
I can't see any command log on device.

**Comment by firheroicths** [comment]
I'm using twoway RPC call from Server to device, and REST api send to NodeA，device connected to NodeB via mqtt。my device side can get the RPC  request that send by api，and NodeB can  also receive device's publish response 。BUT NodeA couldn't get the device response and my api side  always get 408 yet。 
Then i debugger with local IDEA and think that problem maybe  “RuleChainActorMessageProcessor.onTellNext(RuleNodeToRuleChainTellNextMsg)”。

`    void onTellNext(RuleNodeToRuleChainTellNextMsg envelope) {
        checkActive();
        onLocalTellNext(envelope);
        TbMsg msg = envelope.getMsg();
        EntityId originatorEntityId = msg.getOriginator();
        Optional<ServerAddress> address = systemContext.getRoutingService().resolveById(originatorEntityId);
        if (address.isPresent()) {
            onRemoteTellNext(address.get(), envelope);
        } else {
            onLocalTellNext(envelope);
        }
    }`

In my case, The address is NodeB's ,  And next Rule Node is RPC call request。And NodeB get device rpc response，But don't transmit it to NodeA。

**Comment by ashvayka** [comment]
Hi @firheroicths , what version of the TB you are using?

**Comment by firheroicths** [comment]
2.1 and the lasted 2.1.3 is the some problem.

**Comment by firheroicths** [comment]
I change the function  RuleChainActorMessageProcessor.onTellNext(RuleNodeToRuleChainTellNextMsg)  with   `void onTellNext(RuleNodeToRuleChainTellNextMsg envelope) {
        checkActive();
    onLocalTellNext(envelope);` and this problem dosn't  appear.

**Comment by firheroicths** [comment]
![nodea](https://user-images.githubusercontent.com/14211804/47841544-eb0c2300-ddf4-11e8-9489-100b30d7b427.png)
![nodeb](https://user-images.githubusercontent.com/14211804/47841546-eba4b980-ddf4-11e8-93cd-78857a4763d0.png)
@ashvayka This is debugger info. requestId put to localToRuleEngineRpcRequests  in NodeA:9002, and  remove it  in NodeB:9001. My local TB cluster is only the two node.

**Comment by firheroicths** [comment]
@ashvayka i notice the commit with  title 'Fix to RPC logic', i will test with lasted version.Thanks!

**Comment by ashvayka** [comment]
@firheroicths I believe this is already fixed now. Please double-check

**Comment by lc2a** [comment]
@ashvayka   i'm also getting time 408 for v2.1.3 & v.2.2  for oneway

**Comment by vparomskiy** [comment]
@lc2a how your devices are connected to the ThingsBoard and are you sure that devices are online when you are sending RPC call?

**Comment by vparomskiy** [comment]
Close because thead is not active anymore. Original Issue with rpc timeout was resolved few months ago.

**Comment by vcmorini** [comment]
Any chance with **MQTT**?
![mqtt_get_rpc_from_thingsboard_server](https://user-images.githubusercontent.com/44900293/61246975-6b3ea280-a750-11e9-8ab4-1b3f60910dff.png)

Thingsboard on VPS, ports open. RPi access internet behind NAT. The connection is successful, but can't receive MQTT publish from Thingsboard.

I followed the recipe, but nothing.
Any clues where is the mistake?

**Comment by SuneethaYamani** [comment]
How to make device online using rule chain?
