### ISSUE TITLE
Dashboard returning 'No data to display on widget'

### ISSUE THREAD

**Issue by gurverm** [thingsboard/thingsboard#12026]
I have created a dashboard and connected all my devices. When viewing the dashboard as a tenant everything is displayed as ecpected. However, when i assign the dashboard to a customer the widgets are displaying any data. I have another dashboard setup the same way for a different client and it is working fine. Any ideas with what may be happening? 

<img width="1178" alt="Screenshot 2024-11-07 at 10 25 18 AM" src="https://github.com/user-attachments/assets/e250ed6b-72dd-4c13-b50b-e8495c705642">

**Comment by Civilduino** [comment]
Did you assign the right roles to the costumer? They need to have permission for the devices.

**Comment by mykhailokornieiev** [comment]
Hi. Make sure that your customer user have an access to these devices. It must be either shared with customer, or customer must be its owner.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
