### ISSUE TITLE
Deleted sysadmin user by mistake

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#12020]
**Component**

 * Generic

**Description**
It is a super silly question, but, my coworker removed the sysadmin user by mistake from the Thingsboard database. How can I create it again?

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.8

**Comment by dealnat** [comment]
Hi,
You can make another user to be sysadmin. Here is the list of commands:
```
update tb_user set authority = 'SYS_ADMIN' where email = 'customer@thingsboard.org';
update tb_user set customer_id = '13814000-1dd2-11b2-8080-808080808080' where email = 'customer@thingsboard.org';
update tb_user set tenant_id = '13814000-1dd2-11b2-8080-808080808080' where email = 'customer@thingsboard.org';
```
