### ISSUE TITLE
Time Series Widgets: Data of an asset with dynamically configurable time interval/regardless of time interval

### ISSUE THREAD

**Issue by ZYMCao** [thingsboard/thingsboard#12035]
**Component**

 * UI

**Description**
I have several aseets of a certain asset type. Respectively they only have a time span of roughly one hour each during which period of time roughly 200 telemetry data points are generated. 

![image](https://github.com/user-attachments/assets/81215c10-6f1b-4880-bd48-78479066933a)
It's very difficult to find these 200 data points in widget since the starting ts and the end ts vary tremendously from one asset to another; and manually adjusting the time interval is nearly impossible.

I tried several Time Series Widgets, looking for one where ALL timeseries data (roughly 200 of them) can be shown, but none meets my requirement. 

Alternatively I can work with any Time Series Widgets where _Time from_ and _Time to_ below can be dynamically configured so that I can pass the ts of the first datapoint and the last datapoint of the asset (assuming there is a way I can get them) to the following configuration page
![image](https://github.com/user-attachments/assets/87f5de33-d3de-4c1f-aad6-04f31730933b)
but in screenshot above, _Time from_ and _Time to_ are fixed and not asset specific.

Is there any Time Series Widgets out there I miss??

Thanks!

**Comment by mykhailokornieiev** [comment]
Hi
There is no such default functionality. You can implement some custom action, that will check timestamps of the first and last datapoints in current timewindow and then change it on more precise. 
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions
https://thingsboard.io/docs/user-guide/ui/widget-actions/#custom-action-with-html-template
