### ISSUE TITLE
Rule chains - Get customer attributes doubt

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#12036]
**Component**
* Generic

**Description**
Hi there,

We are trying to get the customer attributes in our _"root"_ rule rule chain by using the dedicated node _"Enrichment - customer attributes"_, since we have relevant information that must be attached in other nodes (for instance, we need individual information to build a rest api call using the right node, the _"External - rest api call"_ one).

It is certainly possible when the generated events are not related to entities deletion, but when is that so (device or asset, it does not matter which one), the node tries to get the customer from the entity that has launched the event, but it does not exist already! Should not be independant of that operation? Is there any work around for this?

Thanks beforehand, looking forward to hearing from you.

Kind regards.
Daniel.

**Environment**
OS: Monolitic setup using AWS infrastructure
ThingsBoard: 3.7.0PE
Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi. This is related to design of Thingsboard. You can't get data associated with the deleted entity.

**Comment by dpergarc-c** [comment]
Hi there,

In order to give you further details, when we receive the event message, we have the information already within the metadata section, but we cannot do anything since the _"Enrichment - customer attributes"_ node fails.

Any work around here that might help us?

Kind regards.
Daniel.

**Comment by mykhailokornieiev** [comment]
For such a purpose, I highly recommend getting all the necessary data first and only then deleting the entity.
If your entity is already deleted, then it will be impossible to get the data of its customer, since this device is deleted with all associated data (owner name, owner id, etc.).
As the only possible workaround, you can try to store all the necessary data in some unrelated to both device and customer entity as timeseries/attributes so you can check its values. 
For example, the key is the device name, and the value is the customer name. In this case, it will be some kind of backup.
One rule chain will handle this "backup" on entity created / change owner event
Another one will help to get this info if device is deleted.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev 

Well, that is not possible, and we will try to explain why not a little bit further:

* We have created several server scope attributes variables in the customers such as user, password, etc... which will be used in a third-party API Rest that will be launched at the end of other rule chains. That is helpful indeed since it allow us not to hardcode those values in several places.

* We have right now two scenarios: 
    * Create and delete entities.

![image](https://github.com/user-attachments/assets/8c4733c1-46a5-41e0-a1ab-bfa0592611ba)
The _"Enrichment - customer attributes"_ node is working for the first one since it can catch the customer attributes from the device event, but unfortunately, this is not possible for the second use case.

* We have implemented a work around which trades through the ThingsBoard API the information we need.

![image](https://github.com/user-attachments/assets/6994577f-edda-4d26-8d20-706ca2f4a0be)

Maybe a node that retrieves that information without being related to the rule chain trigger event would be great.

Looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by mykhailokornieiev** [comment]
Please clarify this one:

> Maybe a node that retrieves that information without being related to the rule chain trigger event would be great.

As mentioned before, you can't get customer data after device deletion with Customer Attributes/Fileds rule node. This is by design of Thingsboard and won't be changed.

**Comment by dpergarc-c** [comment]
Hi @mykhailokornieiev ,

It's ok, it is what it is, we will keep using our workaround.

Kind regards.
Daniel.
