### ISSUE TITLE
how to give downlink from thingsboard to device using mqtt/rpc without setmethod

### ISSUE THREAD

**Issue by kesav17** [thingsboard/thingsboard#12039]
Hi Team,

I want to give the downlink command to device from Thingsboard community edition from Power button widget.

I added the below JSON format in power button:
{"rw_prot":
 {"Ver": "1.0.1",
 "dir": "down",
 "id": "12345",
 "w_data": [{"name":"DO1","value":"1"},{"name":"DO2","value":"0"}]
 }
}

but i am receiving the below message on device side:
{"method":"setState","params":{"rw_prot":{"Ver":"1.0.1","dir":"down","id":"12345","w_data":[{"name":"DO1","value":"0"},{"name":"DO2","value":"1"}]}}}

I want to receive only below message on device side without extra content("method":"setState","params":). 
**Expected format on device side:**
{"rw_prot":
 {"Ver": "1.0.1",
 "dir": "down",
 "id": "12345",
 "w_data": [{"name":"DO1","value":"1"},{"name":"DO2","value":"0"}]
 }
}

Could you please me on this. It will be more helpful. Thanks in advance,

**Comment by sumin-denys** [comment]
Hi @kesav17,

Unfortunately, there aren't any possible options to send RPC to the device without **method**, **setState**, **params**. Since these fields are required for the RPC.

You can find additional information about the RPC [here](https://thingsboard.io/docs/user-guide/rpc/)

**Comment by sumin-denys** [comment]
Hi @kesav17,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.
