### ISSUE TITLE
Mobile app - navigation from 'home page' not working

### ISSUE THREAD

**Issue by icehousedoo** [thingsboard/thingsboard#12034]
When using TB mobile app (IOS) our users cannot navigate away from the 'homepage'.
If the user's default page is set to a particular dashboard they can navigate using the drop down list successfully.
However if they go to the homepage using the <- button then they cannot navigate to any other dashboard. This occurs no matter which dashboard we set as the homepage.
I have attempted the following:
Created new dashboard and added the 'dashboards' widget then set this as default in 'settings'. On the mobile app when selecting a dashboard from this widget we see a 'path /be1d........' is currently not supported and the page doesn't change.
Added a button widget to the default dashboard, set with 'open URL' /dashboards/all'. This causes three flashing dots (waiting) for a few seconds then page returns as it was.
I have tried this as both system administrator and end user with no success.

**Your Server Environment**
* [ThingsBoard Cloud](https://thingsboard.cloud)

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: [Windows 11]
* Browser [chrome]
* Version [130.0.6723.70]
Note no issues on desktop environment

**Smartphone (please complete the following information):**
* Device: [iPhone 11]
* OS: [e.g. iOS 17.6.1]
* Browser [e.g. Safari / Chrome]
Using TB live app

Note same issues on iPad
* Device: [iPad 10th gen]
* OS: [e.g. iOS 17.6.1]
* Browser [e.g. Safari / Chrome]
Using TB live app

**To Reproduce**
Using TB Live
1. Logon and navigate to home page if not landed as default
2. Click on any widgets to navigate to a different dashboard
3. See error

**Expected behavior**
Navigation between dashboards from Homepage should work

**Screenshots**
If applicable, please add screenshots to help explain your problem.

First image shows 'back button' and dashboard selection - using this dashboard drop down list works successfully.
![image](https://github.com/user-attachments/assets/2c76f64b-2d49-43f5-a537-68c07d3f1d9d)

Second image shows home page after 'back button' has been pressed. There is no dashboard drop down list and the widgets will not open any other dashboard.
![image](https://github.com/user-attachments/assets/493c4b41-f9b6-4591-9f5d-df9bcae0abc4)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AlexDoanTB** [comment]
If your Home Page is a dashboard (and according to your pictures it is), and you move from one dashboard to another, the RETURN button (back arrow) brings you to a previous page, namely your Home Page dashboard.

**Comment by icehousedoo** [comment]
Hi Alex,
The issue is that once at the homepage I cannot navigate via widgets to any other dashboard. Effectively I am stuck on the homepage unless I close the app and re login to it.

**Comment by icehousedoo** [comment]
Hi Alex,
I'm the tennant admin, have the same issues as the customer users. Have
tried adding / removing roles and groups but the issue still persists.

Cheers

Isaac
