### ISSUE TITLE
About the relations of customer/assets/devices/tenants/dashborads

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1204]
1、Do this entities have a upstream and downstream relationship?
2、I configured a relation from device to dashboard and a relation from dashboard to device, What is the deference between them? and what is the meaning of the relation between the two entities? 

![image](https://user-images.githubusercontent.com/31084798/47770388-2ede2a00-dd1a-11e8-828b-1bb0c53159e5.png)

![image](https://user-images.githubusercontent.com/31084798/47770408-42899080-dd1a-11e8-8fa7-73cdbb584c49.png)

**Comment by vparomskiy** [comment]
The relation has direction '**From**' and '**To**' - it is logic representation how entities are connected.
For example:
You can have a thermostat (device) that is located in the building(asset). 
And you can have many thermostats as well as buildings. So you need to know the building where the thermostat is installed. All you need to know all the thermostats in the building.
Relations used inside Rule Engine and on the Dashboard for alias resolving

Here is a description of how to use relations between entities:
https://thingsboard.io/docs/user-guide/entities-and-relations/

**Comment by qwyinxiang** [comment]
Thanks a lot for your answer.
