### ISSUE TITLE
Unable to send the dashboard report via email?

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#12043]
I am trying to send the dashboard report to the user.

I have scheduled one Generate Report event.
and I am using systems SMTP only which has been done by my system admin.
please have a look at its configurations.

![Screenshot from 2024-11-14 02-07-59](https://github.com/user-attachments/assets/80e0c07e-94b9-44c4-b035-534e39d8bf87)
![Screenshot from 2024-11-14 02-08-35](https://github.com/user-attachments/assets/a1ce55d8-f9e1-4f06-b9fb-75af69532469)
![Screenshot from 2024-11-14 02-09-49](https://github.com/user-attachments/assets/888cd338-d9da-41b1-9b49-2c0281961296)
![Screenshot from 2024-11-14 02-09-56](https://github.com/user-attachments/assets/596c09ac-5141-49b0-8c5d-01349f86f488)
![Screenshot from 2024-11-14 01-50-07](https://github.com/user-attachments/assets/120831ae-a5b1-491c-9e32-860f3afc90a9)

Now please have a look at the rulechain.
![Screenshot from 2024-11-14 02-14-42](https://github.com/user-attachments/assets/32fe77a6-80b6-409a-8bd3-c72b5087c44e)

Here I am getting failure only at the last send email node, please see the error.
Configurations - 
![Screenshot from 2024-11-14 02-18-58](https://github.com/user-attachments/assets/bcf923e8-5274-42dc-9eb3-5401966394c5)
Error of output -
![Screenshot from 2024-11-14 02-16-21](https://github.com/user-attachments/assets/8d042649-272a-4f78-839b-98d07177bc2f)

and its previous to email node configuration is.
![Screenshot from 2024-11-14 02-17-12](https://github.com/user-attachments/assets/7b3c7fbf-7e79-423e-a655-852745ee7035)

**Description**
I am using the latest version of Thingsboard.

**Environment**
 * OS:  ubuntu 22.04
 * ThingsBoard: 3.8.1PE

Please help me to send the report by email successfully.

**Comment by mykhailokornieiev** [comment]
Hi
Make sure that you specified From email exactly as in your SMTP configuration. It must be configured in Settings -> Mail
Make sure that you've made all steps from documentation and "Send test email" was sent successfully.
https://thingsboard.io/docs/user-guide/ui/mail-settings/
If everything is correct with this point, then I'd recommend you to check connectivity to your SMTP server or its setup

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
