### ISSUE TITLE
Device Details - Edit What is available for a user to see

### ISSUE THREAD

**Issue by valixkaldor** [thingsboard/thingsboard#12052]
Hi

When i go to devices and click on one of my devices, I am shown a small table with various subheadings.
for the tenant it is: 

Details
Attributes
Latest telemetry
Alarms
Events
Relations
Audit logs
Version control

I however I have a user type that isn't allowed to Edit relations.

![Screenshot 2024-11-15 113102](https://github.com/user-attachments/assets/99693583-328d-484b-95d7-0c9c8c3d7e7d)

Is there a way to remove the Relations for them.
I know that i can remove audit logs and alarms via the role permission but I haven't been able to change the relations.
I can't remove the read/write permissions, since i need to see and edit the details section.

**Environment**
 * ThingsBoard: 3.8.1

**Comment by mykhailokornieiev** [comment]
Hi. Currently, there is no possibility of denying users access to relations. However, this is valid improvement that I've already added to our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
