### ISSUE TITLE
Line chart widget legend: How to list entities in rows/columns?

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#12064]
**Component**

 * UI
 * Generic
 * Widgets

**Description**
When configuring a line chart widget, in Advanced mode: appearence, I can find no option to choose to list legend in rows / columns , only where (top bot, left, right). when having a few entities the default only shows 1 or 2 . 

How do I set legend to right, entities in rows (direction: column), like in the deprecated widget?

**Environment**
 * OS:  Docker Container in Ubuntu 
 * ThingsBoard: 3.8.1PE
 * Browser: Chrome Version 130.0.6723.119 (Offizieller Build) (64-Bit)
 
 Screenshot from report: 
 
 
![image](https://github.com/user-attachments/assets/40ebc767-d944-472d-afdd-9c26a6c8bf8d)

(left is new line chart widget, right is old line chart widget)
___________________________________________________________

**Comment by mykhailokornieiev** [comment]
Hi
I was able to reproduce this behavior and already created a ticket for our developers.
There's no set timeframe for this bug fix; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
