### ISSUE TITLE
Custom Action Loading Bug

### ISSUE THREAD

**Issue by DBitnerITN** [thingsboard/thingsboard#12066]
**Describe the bug**
Since the update from 3.7.0 to 3.8.1, loading issues have been observed in many custom widgets and custom actions. When opening custom actions or dashboards with custom widgets, a loading bar appears and only disappears after a long waiting period or when clicking within the dashboard/form. Additionally, checkboxes are only updated after another field is clicked. This behavior can also be reproduced in the default "Edit Entity" example using the Action Button widget and a custom action with HTML template.

**Your Server Environment**
* own setup
  * monolith (ubuntu) and microservices (k8s)
  * ThingsBoard Version 3.8.1
  * Professional Edition

**To Reproduce**
1. Add Action Button Widget
2. Add On click Action "Custom Action (with HTML template)"
3. Uncomment Edit Entity Example
4. Save
5. Click on Action Button Widget

**Screenshots**

![chrome-capture-2024-11-18](https://github.com/user-attachments/assets/d470d50b-1231-4d19-a0ce-3c632b801140)

**Additional context**
This Issue was also mentioned here: 
https://github.com/thingsboard/thingsboard/issues/11923

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
