### ISSUE TITLE
TB Migration without Git

### ISSUE THREAD

**Issue by can-git** [thingsboard/thingsboard#12068]
**Component**

 * Installation

**Description**
Hi, 
My company doesn't let me use Git but I need to migrate all type of entities from a server to another. 
At this point I tried Rest Client service but TB wants a little different type of format in the Json to do it. 
I stucked and very open to any suggestion.

**Environment**

***Old***
 * OS:  Windows
 * ThingsBoard: 3.8.1
 
***New***
 * OS:  Ubuntu
 * ThingsBoard: 3.8.1

___________________________________________________________

**Comment by trikimiki** [comment]
hi!
if you need to migrate pretty much everything, perhaps you consider migrating whole DB altogether?
in case there is no data on Ubuntu server - you can just drop Ubuntu DB, dump Windows DB and restore it to Ubuntu DB
