### ISSUE TITLE
Alarm based on the attribute

### ISSUE THREAD

**Issue by AndriiHavrylyak** [thingsboard/thingsboard#1206]
Hi, I want to make an alarm based on the attribute. If the aribut "active" = false,  this is alarm, if  "active" = true,  this is not alarm.I tried to do, but I did not succeed, can you help?

**Comment by vparomskiy** [comment]
You need to implement it inside Rule Engine. Here is a guide that can help:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/

https://thingsboard.io/docs/iot-video-tutorials/#dashboard-development-guide-part-3-of-3-remote-device-control-and-alarm-management

**Comment by AndriiHavrylyak** [comment]
Я знаю, я зробив відповідно до цих інструкцій, але не було тривоги.

![1](https://user-images.githubusercontent.com/38010614/47785866-adcf6480-dd12-11e8-92d1-92e729f319e4.jpg)
![2](https://user-images.githubusercontent.com/38010614/47785867-adcf6480-dd12-11e8-9fa8-648f613ccb6c.jpg)
![3](https://user-images.githubusercontent.com/38010614/47785868-adcf6480-dd12-11e8-828c-ee4f23e761c3.jpg)

**Comment by vparomskiy** [comment]
Please enable **Debug** mode for **Filter2** node and save Rule Chains. 
Then you can open **Events** tab in this node and see incoming/outgoing messages for this node and out relation type (true/false)

**Comment by AndriiHavrylyak** [comment]
I will try now, and can I see the events in the alarm list?

**Comment by AndriiHavrylyak** [comment]
In mode Debug , there is only telemetry, but there is no value attribute

**Comment by AndriiHavrylyak** [comment]
![3](https://user-images.githubusercontent.com/38010614/47797190-871f2700-dd2e-11e8-912e-d17048e0662b.jpg)
I configured the chain through the save node attributes, but nothing was worn out.

**Comment by AndriiHavrylyak** [comment]
If you can help me make a chain

**Comment by vparomskiy** [comment]
Did you investigate the Rule Chain flow using Debug mode? What is the result?

**Comment by AndriiHavrylyak** [comment]
If stream streams are adjusted in debugging mode through "save attributes", then nothing in the Filter2 comes.In  "save attributes" I chose server attributes!!

**Comment by AndriiHavrylyak** [comment]
I want an alarm clock when the device is turned off

**Comment by AndriiHavrylyak** [comment]
I will receive an incoming telemetry from Raspberry Pi,  and if Raspberry Pi  disconnected I want to know when it happened!

**Comment by vparomskiy** [comment]
You can use the Device Connectivity Status feature:
https://thingsboard.io/docs/user-guide/device-connectivity-status/

**Inactivity event** will be created when the device does not submit data during the last 10 seconds (timeout is configurable)
In your Root Rule Chain, you need to create an alarm when this event occurs (or send an email or do anything else)

**Comment by AndriiHavrylyak** [comment]
Thanks, done according to the instructions, and everything works!

**Comment by RyanKikleo** [comment]
Is it possible to see the result of your rule please.
