### ISSUE TITLE
How could I create a widget that sets dashboard timewindow?

### ISSUE THREAD

**Issue by navidrashidian** [thingsboard/thingsboard#12073]
I want to create a custom date picker widget. So I need to set the dashboard time window using my widget. I cannot see how I can do this and appreciate any help.

**Comment by devaskim** [comment]
Why did you duplicate the question?
https://github.com/thingsboard/thingsboard/issues/12045

**Comment by navidrashidian** [comment]
I forgot I had opened another issue re the same point.
