### ISSUE TITLE
Can't build the flutter mobile  application.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12072]
I follow the documentation of the thingsboard mobile development.

I am new to mobile development. 
Below error comes on flutter run...

PS C:\Users\Admin\Desktop\flutter_thingsboard_app> flutter run
"ar": 73 untranslated message(s).
"zh": 92 untranslated message(s).
"zh_CN": 92 untranslated message(s).
"zh_TW": 91 untranslated message(s).
To see a detailed report, use the untranslated-messages-file
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
:

This will generate a JSON format file containing all messages that
need to be translated.
Launching lib\main.dart on SM A707F in debug mode...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
Where:
Build file 'C:\Users\Admin\Desktop\flutter_thingsboard_app\android\build.gradle' line: 14

What went wrong:
A problem occurred evaluating root project 'android'.

A problem occurred configuring project ':app'.
Could not create task ':app:copyFlutterAssetsDebug'.
> Could not create task ':app:mergeDebugAssets'.

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/.
==============================================================================

2: Task failed with an exception.
Where:
Build file 'C:\Users\Admin\Desktop\flutter_thingsboard_app\android\build.gradle' line: 14

What went wrong:
A problem occurred evaluating root project 'android'.

A problem occurred configuring project ':app'.
Could not create task ':app:copyFlutterAssetsDebug'.
> Could not create task ':app:mergeDebugAssets'.
> Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/.
==============================================================================

BUILD FAILED in 1s
Running Gradle task 'assembleDebug'... 2,666ms
Error: Gradle task assembleDebug failed with exit code 1
PS C:\Users\Admin\Desktop\flutter_thingsboard_app>

**Comment by mykhailokornieiev** [comment]
Hi. Please create this ticket in the correct repository
https://github.com/thingsboard/flutter_thingsboard_pe_app
