### ISSUE TITLE
Alarms count node

### ISSUE THREAD

**Issue by GreazlyA** [thingsboard/thingsboard#12076]
**Component**
Alarms count node

 * Rule Engine

**Description**
We are using the Alarms count node in PE edition - it seems that the widget updates the DB a lot for no reason with the same value  ,
how does the alarm count works? what is the Execution period value/time unit or trigger for it to count the alarms?

**Environment**

 * OS:  linux 
 * ThingsBoard: 3.8
 * Browser: chrome 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Backdraft007** [comment]
How looks your rule chain?

**Comment by GreazlyA** [comment]
i meant rule chain not widget - my bad.
this is the screen shout for previous rule chain logic: the marked in red is the rule chain i posted before
![image](https://github.com/user-attachments/assets/078000ad-e893-42fc-aee3-1d1cb4ca3705)

**Comment by Backdraft007** [comment]
And what is your logic of your alarm rules?
You wrote that it write a lot to the DB. I see that you trigger your rule chain even if the alarm is updated. So it can be right that there is an update of the alarm. You can enable the debug feature in the alarm count rule node an can have a look in the logs which data are changed.

**Comment by GreazlyA** [comment]
Hi,
thank you for the info , it seems that  alarm update is triggering all the time - as you mentioned- i don't understand why ,what does alarm update stand for ?

**Comment by Backdraft007** [comment]
AFAIK it is for detailed alarm plans. You get eg. informations like duration of alarm etc. to build complex alarm escalation levels and so on. For this it is necessary that the alarm go through the rule chain with updated data like duration.
You can add a script node to check if the alarm is new or not and go then to your count node or not.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
