### ISSUE TITLE
How to access JSON inside JSON in Widgets and Dashboards

### ISSUE THREAD

**Issue by lggiordano** [thingsboard/thingsboard#12085]
**Component**

 * UI

**Description**
I have an attribute like this:
```json
{
  "config": {
    "printer": {"port":"/dev/ttyS0","enabled":true, ...},
    "reader":{"enabled":false,"debug":true,...},
    "version":"1.0",
    ...
  }
}
```
I want to extract the "enabled" value from "printer".
```javascript
var config = JSON.parse(value);
console.log(config); // prints the config object
console.log(config.version); // prints the version ok
console.log(config.printer); // prints the printer object ok
console.log(config.printer.enabled); // Doesn't work
```

Error popups when I try to save the post-process function:
Error: TypeError: Cannot read properties of undefined (reading 'enabled')

Any tips on how can I access Json objects inside the main Json?

**Environment**
 * OS:  Ubuntu 24.04
 * ThingsBoard: 3.7.0
 * Browser: Google Chrome Versión 130.0.6723.116 (Build oficial) (64 bits)

**Comment by ashaforost** [comment]
Hi @lggiordano 

You can try the following post-processing function:
```
var json_value = JSON.parse(value);
var config = json_value["config"]

if (config){
    return JSON.stringify(config["printer"]["enabled"]);
}
return value;
```

In this case, console.log may not work correctly due to the nature of the post-processing function script compiling, but here's what I get in a widget:
![image](https://github.com/user-attachments/assets/96a966d1-394c-43f2-9a16-bf8853dbad25)

**Comment by lggiordano** [comment]
Thank you so much!
My JSON is more complex than the example I wrote here, but with your tip I was able to extract what I want to show.
