### ISSUE TITLE
Listen to click event from other widget?

### ISSUE THREAD

**Issue by nguyen-hai-nam** [thingsboard/thingsboard#12086]
**Component**

 * UI

**Description**
I'm customizing the entities hierarchy widget. I'm also creating a new widget to display an entity's information in a specific format. The selected entity for my new widget is determined from click events in the entities hierarchy widget. How to listen to click event from other widget?

**Environment**

 * ThingsBoard: 3.8.1 CE

**Comment by CalmNite** [comment]
Hi @nguyen-hai-nam 

You can try using broadcastService. Here I have an example, I hope it fits you.

I have a dashboard with two widgets one is an entities table and the other is a custom widget. This can be done with any type of widget.

In my table I added a custom action on row click that gets some data of the element and sends a broadcast event. Here is the example:

```
let broadcastService = widgetContext.$injector.get(widgetContext.servicesMap.get('broadcastService'));

let result = widgetContext.data.filter(value => value.datasource.name == entityName);

broadcastService.broadcast('show-position', {
    position: JSON.parse(result[1].data[0][1]),
    rotation: JSON.parse(result[2].data[0][1]),
    sphere: JSON.parse(result[3].data[0][1])
});
```


In my other widget I have the following function:


```
let broadcastService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('broadcastService'));
broadcastService.on('show-position', (event, data) => {});
```

This function is created on the self.onInit.
