### ISSUE TITLE
Is it possible to make multiple API calls from a single node?

### ISSUE THREAD

**Issue by jungwone** [thingsboard/thingsboard#12097]
* Rule Engine

**Description**
I am wondering if it is possible to send multiple API requests from a node in the rule chain connected to my device. The example scenario is as follows:

1. Telemetry data is input into the device.
2. Rule Node calls an `ExampleA API` using the telemetry data received as input.
3. `ExampleA API` responds with an array containing 10 values. ex)[1,2,3...10]
4. I want to call the same API for each of the ten elements above: `https://exampleAPI/{elementId}`

I would like to know if this approach is possible in the rule chain, and even if it is possible, whether this method is efficient or if it could negatively impact performance. 

Thank you!

**Environment**

 * OS:  MacOS
 * ThingsBoard: docker image: thingsboard/tb-postgres
 * Browser: Arc browser

**Comment by devaskim** [comment]
Convert you telemetry packet to array of rule engine messages using `Script` node. Then each such new message will be forwarded to `REST API` node. Here details https://github.com/thingsboard/thingsboard/issues/6594#issuecomment-1141037479

**Comment by jungwone** [comment]
> Convert you telemetry packet to array of rule engine messages using `Script` node. Then each such new message will be forwarded to `REST API` node. Here details [#6594 (comment)](https://github.com/thingsboard/thingsboard/issues/6594#issuecomment-1141037479)

Thank you for answering my question!
I just checked #6594 and tried it in my rule engine, but I can't put the name `elementId` in my API URL.

My transformation node makes an array like below.
```javascript
[{
    "msg": {
        "name": "first-item",
        "id": "1"
    }
}, {
    "msg": {
        "name": "second-item",
        "id": "2"
    }
}]
```

After that, I tried to extract the `id` value from the input message and create a URL as shown below: `https://exampleAPI.com/info/$[id]`

However, the `$[id]` value is not being replaced with the actual value, and the URL remains unchanged. 

**Expected:**
- `https://exampleapi.com/info/1`
- `https://exampleAPI.com/info/2`

**Actual values:**
- `https://exampleAPI.com/info/$[id]`

Values inside metadata work correctly when entered as ${key}, but it seems that the input data is an array, and the values are not being converted properly.

**Comment by devaskim** [comment]
If code in script node is correct, REST API node will receive single msg instead of array. You can enable debug mode in REST API node and look if it is so

**Comment by jungwone** [comment]
> If code in script node is correct, REST API node will receive single msg instead of array. You can enable debug mode in REST API node and look if it is so

I enabled debug mode in Transformation node and REST API node and checked:

**Script Node Output**
![image](https://github.com/user-attachments/assets/4d61fb24-592f-4d19-84f3-f32914c34f02)

**REST API Node Input**
![image](https://github.com/user-attachments/assets/ba085fe2-c9a4-4245-a09a-875c43cab85b)

The REST API node still receives an array instead of single msg :(

**Comment by jungwone** [comment]
Ah, the **split array msg** node simply works in this case. This node splits the array and sends N (length of the array) requests to the next node. problem solved!

**Comment by jungwone** [comment]
Ah, the split array msg node simply works in this case. This node splits the array and sends N (length of the array) requests to the next node. problem solved!
