### ISSUE TITLE
How do I change the logo on a deployed platform.(Thingsboard)

### ISSUE THREAD

**Issue by ZhaoLinl** [thingsboard/thingsboard#12098]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Ultrazombie** [comment]
https://github.com/thingsboard/thingsboard/blob/master/LICENSE. Please use the PE version for the white labeling feature.
https://thingsboard.io/docs/pe/user-guide/white-labeling/
