### ISSUE TITLE
getEntityGroupsByOwnerAndType servise is not working in widget custom action?

### ISSUE THREAD

**Issue by KashifAhmd** [thingsboard/thingsboard#12106]
Hi!

I am trying to get all user groups of a particular Customer.

while I am trying it in postman with getEntityGroupsByOwnerAndType API as mentioned in swagger UI documentation, I am able to get the data of all user groups for a Customer.
![Screenshot from 2024-11-22 20-20-53](https://github.com/user-attachments/assets/30486dc7-474a-44b0-b886-493f94932e43)

![Screenshot from 2024-11-22 20-34-20](https://github.com/user-attachments/assets/428db45b-72b1-4191-83bc-5a763a5cc82c)

But when I am trying it in widget custom action I am getting error.
![Screenshot from 2024-11-22 20-30-00](https://github.com/user-attachments/assets/cad57cb5-28c6-48f6-a86e-1476f7e2d4aa)

Help me to resolve this and get the data what I want.

I'll be waiting for the response.

**Comment by KashifAhmd** [comment]
Any response please

**Comment by devdoob** [comment]
not all functions mentioed in swagger are exposed in TB api. But you can still "http" service to directly call any endpoint. 


```
let $injector = widgetContext.$scope.$injector;
let http = $injector.get(widgetContext.servicesMap.get('http'));

http.get("/api/entityGroups/[rest_of_url]").subscribe(res => {

})
```


make sure the url starts from /api/ ....... no need to mention domain name

**Comment by KashifAhmd** [comment]
Nice! This is a great alternative...

Thanks for the response @devdoob.
