### ISSUE TITLE
Git Repository, Restore Full Dashboard after delete?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#12103]
Hi,

I configured version control and I can restore changes I made to the dashboard. 
If I accidentally delete the complete Dashboard/Device is there a way to get it back from the repository?
(I don't see an UI for that)

Thanks

Version 3.8.1 CE and 3.6.4 PE on Ubuntu

**Comment by KenSense** [comment]
No there is not (separate) auto-commit when I delete a whole dashboard that I can use to restore it.
I could do a restore of ALL dashboards though in version control, not what I want.

**Comment by Backdraft007** [comment]
Ah okay, you have only auto commits. I don't use it. I only control my changes manually.
But I think every dashboard has its own file on the git server. Can you check it?

**Comment by epalchenko** [comment]
Hello,
An option to fully restore a dashboard after deletion is to create a new(clean) tenant profile on the platform(the exact version of the platform on which you created version control) through the system administrator. Then, export your dashboard to JSON and import it to your current tenant.

When restoring the version, you need to uncheck this box:
![Screenshot_4](https://github.com/user-attachments/assets/8d022afd-c3c3-48f7-a877-346454a4cbf8)
And check this box:
![Screenshot_6](https://github.com/user-attachments/assets/8c81cfb6-5d77-490d-af2f-59a912f81007)

**Comment by KenSense** [comment]
That would be an way around it if needed, thanks.

Maybe add some extra feature in the auto-commit for deleting entities that they generate their own commit, so you can select them for restore/undelete in version control.

**Comment by epalchenko** [comment]
The ticket (PROD-5041) about your improvement request has already been added to our backlog for the product team.
We will also inform the developer who created the version control about your request.

We will close this ticket as it is already in our backlog.
Please follow our Release Notes (https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
