### ISSUE TITLE
Time selection using the update time series chart

### ISSUE THREAD

**Issue by JakeDaSnake80** [thingsboard/thingsboard#12113]
Hi,

In the older time series chart it was possible to click and drag to change the time window for all widgets in the view. However, with the new time series chart a bottom "zoom field" has been added but it doesn't affect other widgets. Is it possible to use the new time series chart but use the old way of time window zooming?

![image](https://github.com/user-attachments/assets/9ccf58d2-8648-4f6a-8ab0-bd1b8898c636)

**Comment by dealnat** [comment]
Hi,
Since Thingsboard moved to the charts library, the "click and drag" functionality is no longer accessible. Instead, use the slider to select a specific area. 
![image](https://github.com/user-attachments/assets/65f3d5e8-ed97-4245-bc39-84a1662be1e6)

**Comment by JakeDaSnake80** [comment]
Using the slider at the bottom doesn't update/set the time window for other widgets, i.e. just itself. The "click and drag" did update other widgets. Do you have an estimation when the deprecated time series chart will be removed? If it's not going to be removed in the near future I will keep on using that since our customers like it better than the new one.

Med Vänlig Hälsning/Kind Regards
Jakob Svensson

Från: Oleksii Kuripko ***@***.***>
Skickat: den 26 november 2024 15:49
Till: thingsboard/thingsboard ***@***.***>
Kopia: Jakob Svensson ***@***.***>; Author ***@***.***>
Ämne: Re: [thingsboard/thingsboard] Time selection using the update time series chart (Issue #12113)


CAUTION: Please note this email originated from outside the organization.

Hi,
Since Thingsboard moved to the charts library, the "click and drag" functionality is no longer accessible. Instead, use the slider to select a specific area.
image.png (view on web)<https://github.com/user-attachments/assets/65f3d5e8-ed97-4245-bc39-84a1662be1e6>

-

**Comment by dealnat** [comment]
Hi,
Deprecated widgets mean that they will not be updated, but we won't remove deprecated widgets in the near future.
