### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#1212]
F:\gitWorkSpace\thingsboard\common\transport\transport-api\src\main\java\org\thingsboard\server\common\transport\service\AbstractTransportService.java

@Override
    public void process(TransportProtos.SessionInfoProto sessionInfo, TransportProtos.SubscribeToRPCMsg msg, TransportServiceCallback<Void> callback) {
        if (checkLimits(sessionInfo, callback)) {
            SessionMetaData sessionMetaData = reportActivityInternal(sessionInfo);
            sessionMetaData.setSubscribedToRPC(!msg.getUnsubscribe());
            doProcess(sessionInfo, msg, callback);
        }
    }

![image](https://user-images.githubusercontent.com/10750404/47899434-7e585d80-deb4-11e8-92b4-4fe98f3ffd67.png)

![image](https://user-images.githubusercontent.com/10750404/47899467-94661e00-deb4-11e8-97d7-8bdb00755298.png)

**Comment by caoyingde** [comment]
console log file:
[log.txt](https://github.com/thingsboard/thingsboard/files/2541436/log.txt)

**Comment by ashvayka** [comment]
Thank you. This is now fixed.
