### ISSUE TITLE
Detect MQTT connection loss immediately

### ISSUE THREAD

**Issue by TobiasUhmannVoss** [thingsboard/thingsboard#12125]
**Component**

 * Rule Engine

**Description**
When a device connected via MQTT loses connection, I would expect an immediate DISCONNECT_EVENT in the rule chain. However, I only get an immediate DISCONNECT_EVENT if the device disconnects properly. If the device loses connection, e.g. because of a power outage, it takes about 2min for the rule chain to fire the DISCONNECT_EVENT. That feels more like an inactivity event. How can I get an immediate notification in case of a connection loss (like an MQTT LWT message)?

**Environment**

 * OS:  Windows 11
 * ThingsBoard: 3.6.1
 * Browser: Chrome 131

**Comment by TobiasUhmannVoss** [comment]
Just noticed those bug tickets here [1, 2]. Is it right that ThingsBoard's integrated MQTT broker does not support LWT messages and that I have to add another broker to detect connection losses?

[1] https://github.com/thingsboard/thingsboard/issues/416
[2] https://github.com/thingsboard/thingsboard/issues/3165

**Comment by trikimiki** [comment]
you are correct, the LWT messages are not supported
also see https://github.com/thingsboard/thingsboard/issues/11922
feature request in the backlog, as a workaround I can suggest [TBMQ](https://github.com/thingsboard/tbmq) as [it supports this feature already](https://thingsboard.io/docs/mqtt-broker/user-guide/retained-messages/)

**Comment by TobiasUhmannVoss** [comment]
Okay, thanks for the confirmation and the links
