### ISSUE TITLE
Can we do white labelling under white labelled account ?

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12137]
I have thingsboard account which is white labelled. 

Can we provide white labelling to multiple customer under this account?

I read we can handle multi-tenancy but can we handle this tanent from the single account and abstract some important functionality like rule chain in this account?

**Comment by mykhailokornieiev** [comment]
Hi

> Can we provide white labelling to multiple customer under this account?

Yes, you can. For this, you need to use "login as" functionality and change White Labeling for the necessary customer. Also, make sure that white labeling is allowed for this customer:
![image](https://github.com/user-attachments/assets/49965b33-9c72-4630-9a42-52d013055c37)
 

> I read we can handle multi-tenancy but can we handle this tanent from the single account and abstract some important functionality like rule chain in this account?

Not sure how these questions are related. Please clarify

**Comment by Vaibhav0216** [comment]
Hi @mykhailokornieiev,

I have a white-labeled account, and I want to provide my customer with their own white-labeled account, including their own domain and logo.

**Comment by mykhailokornieiev** [comment]
Hi
For this, your customer must have "Allow white labeling" with white labeling permission enabled. 
Then, they can make any necessary changes on their own or you can make it with "login as" feature from your end.
In this case, your tenant will have its own white labeling, and the customer will have its own different one.

**Comment by Vaibhav0216** [comment]
In that white labeling can I restrict the customer from using rule chain and other confidential things.

**Comment by mykhailokornieiev** [comment]
Hi. Rule chains cannot be used by customers, but they are available on the tenant level only by design of Thingsboard.
You can restrict access for your tenant/customer users to the necessary part of Thingsboard either with custom menu or by using RBAC.
https://thingsboard.io/docs/pe/user-guide/rbac/
https://thingsboard.io/docs/pe/user-guide/custom-menu/#hide-existing-menu-items
