### ISSUE TITLE
MQTT over SSL & Invalid message received

### ISSUE THREAD

**Issue by Dfghhj** [thingsboard/thingsboard#1213]
I configured it according to the documentation (https://thingsboard.io/docs/user-guide/mqtt-over-ssl/) and tried to connect using a python script (one-way-ssl-mqtt-client.py).
The console prints "Invalid message received" and msg = [MqttMessage[fixedHeader=, variableHeader=, payload=]]。
![image](https://user-images.githubusercontent.com/20330850/47910319-71943380-decd-11e8-8b58-10511ca5a0d5.png)
![image](https://user-images.githubusercontent.com/20330850/47910812-e9af2900-dece-11e8-998f-eb9d88511d17.png)

**Comment by anujdeshpande** [comment]
@Dfghhj how did you fix this? I am running into the same issue.

**Comment by ashvayka** [comment]
Hi, we have recently fixed main issue introduced in v2.2 but according to your stack, it looks like you have not configured SSL on the server side (in thingsboard.yml). Please retest on the latest master version.
