### ISSUE TITLE
In mobile app order of the widgets is mismatches.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12144]
I have made a dashboard in which order of the widgets is not correct.
![image](https://github.com/user-attachments/assets/97839d3b-2c1f-4736-9970-ba25e86ae494)
see the above image in which buttons are below the widget, but buttons should comes at top. How can I over come this?

**Comment by mykhailokornieiev** [comment]
Please make sure that you've selected the order for the mobile mode for each widget here:
![image](https://github.com/user-attachments/assets/ff4a14b0-8f09-4980-9efa-337707deb2d4)

**Comment by Vaibhav0216** [comment]
Thanks.
