### ISSUE TITLE
Originator telemetry cannot fetch multiple sensors if sensor list is defined in metadataKey

### ISSUE THREAD

**Issue by felisd** [thingsboard/thingsboard#12145]
**Description of bug**
In Rule Chain, when originator telemetry node is created to fetch multiple sensors and sensor list is defined in metadataKey, the node does not output anything. This does not happen when there is only one sensor in the metadataKey.

For example, if I want to get "temperature" only, the output contains temperature data:
![Screenshot 2024-11-29 152536](https://github.com/user-attachments/assets/9cd7445c-0560-4578-8c15-5823bc05f653)

But if I want to get "temperature,pressure", the output contains no sensor data at all:
![Screenshot 2024-11-29 152600](https://github.com/user-attachments/assets/134619f2-1d05-4a4b-98f5-72decbbce616)

Below is the node configuration in the UI:
![Screenshot 2024-11-29 153556](https://github.com/user-attachments/assets/a13617b3-3f08-48f0-9c92-3ffb787243c4)

**Expected behavior**
When there are multiple sensors defined in metadataKey, from my understanding, it should be able to output data from multiple sensors. Not sure if this is an expected behavior and whether there is a workaround to achieve this.

As a comparison, when the sensors are defined in the UI directly and not from metadata, the output contains correct sensors.
![Screenshot 2024-11-29 154144](https://github.com/user-attachments/assets/ca930f92-fc0f-4a7a-9fd2-567bbf619930)
![Screenshot 2024-11-29 154312](https://github.com/user-attachments/assets/bee6812d-00df-4dee-b4b5-95070b57cffb)

**Server Environment**
Own setup (localhost)

  * Deployment type: exe
  * ThingsBoard Version 3.8.1
  * Community Edition
  * Windows 11 Home

**Client Environment**
Desktop
* OS: Windows 11 Home
* Browser: Chrome
* Version: 131.0.6778.86 (Official Build) (64-bit)

**Comment by mykhailokornieiev** [comment]
Hi. Please describe it in as much detail as possible. 
Also, please attach a screenshot of your rule chain with screenshot from debug (IN/OUT messages list) of the Originator Telemetry rule node

**Comment by felisd** [comment]
Hi. What I want to do is to extract the past 1 hour sensor data from different devices. The rule chain will be shared by several devices, and the number of sensors and the list of sensors to extract will be different for different devices. To satisfy this, I want the sensor list to be defined via shared attributes that can be different for different devices.

When I set the attribute to contain one sensor only (e.g., temperature), it correctly extracts the past 1 hour data. But when it contains multiple sensors using a comma-separated string, it doesn't work.

So far the only way I can extract multiple sensors is by defining each sensor as one attribute (e.g., temperature as shared_telemetryKey1, pressure as shared_telemetryKey2), then the rule chain takes in all the attributes. However, this is not preferred as it requires a fixed number of sensors for different devices that use this rule chain, while in my case there will be different numbers of sensors for different devices.

Exported rule chain: [chiller_chain.json](https://github.com/user-attachments/files/17971759/chiller_chain.json)

Screenshot of my rule chain and debug message list (IN/OUT):
![Screenshot 2024-12-02 101645](https://github.com/user-attachments/assets/2de9d9ab-3b1e-4b8d-b53a-2d199705ff05)
![Screenshot 2024-12-02 101613](https://github.com/user-attachments/assets/ad4202ea-478e-4a62-8ad2-0d9cbaf75972)

Screenshot of originator telemetry:
![Screenshot 2024-12-02 101753](https://github.com/user-attachments/assets/1117946d-1427-4adb-96c9-5c3f0ef8373c)

Metadata and message IN:
![Screenshot 2024-12-02 101505](https://github.com/user-attachments/assets/3a188603-96ce-467e-8e03-6d6200fe06b1)
![Screenshot 2024-12-02 101436](https://github.com/user-attachments/assets/6cc14b28-54c1-40c5-808f-d05abb9bf015)

Metadata and message OUT:
![Screenshot 2024-12-02 101600](https://github.com/user-attachments/assets/9957e9ad-5158-46cd-ab2c-bd63eb84de95)
![Screenshot 2024-12-02 101542](https://github.com/user-attachments/assets/f123cced-52a0-47bd-91aa-f9de33d0ab22)

And below is my device attribute:
![Screenshot 2024-12-02 101824](https://github.com/user-attachments/assets/2be94166-2132-4749-8d0a-0dc58fabe5e5)

**Comment by mykhailokornieiev** [comment]
Hi.
Thank you for this clarification.
Each metadata/message key must be specified one by one
The metadata/message template will use the value of the specified input metadata/msg.
![image](https://github.com/user-attachments/assets/dbb09c3c-1873-4f48-b863-3a58743667ae)
![image](https://github.com/user-attachments/assets/f1e9970a-b22a-4f5c-867c-8c94ba48b47e)
![image](https://github.com/user-attachments/assets/3623fb2b-5d55-4126-802d-75289261f871)
This is also specified in documentation:
![image](https://github.com/user-attachments/assets/3228b354-4126-4b2f-9e80-715b143f1481)
![image](https://github.com/user-attachments/assets/fb2dff0c-4bc4-42f2-b5c5-e644ad59bf8e)

**You cannot specify multiple key names in one message/metadata template value by design of Thingsboard**

**Comment by felisd** [comment]
Thank you for the clarification.
