### ISSUE TITLE
Spambots taking over Community chat

### ISSUE THREAD

**Issue by jurkov** [thingsboard/thingsboard#12140]
**Component**

Are you able to somehow manage the [Community chat](https://gitter.im/thingsboard/chat)?
atm. spambots are making this chat not even NSFW

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. We are not managing Community Chat.
It's a really unpleasant situation, but the only thing you can do is send a report about a particular bot/user. Gitter admins make the decision to block or not to block.
