### ISSUE TITLE
Can I assign "ts" and "value" of two different telemetry to the same telemetry? 

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12143]
I want to assign timestamp of one variable and value of another to same variable how can I do it?

![image](https://github.com/user-attachments/assets/1e4c9952-6070-40d9-9533-294cbba0d3d2)

```
let ts = msg.meterReadingDelta.ts; // Extract timestamp with a fallback
let value = msg.DailyConsumption.value; // Extract value with a fallback

msg.waterVol = { "ts": ts, "value": value }; 

return {msg: msg, metadata: metadata, msgType: msgType};
```

**Comment by devaskim** [comment]
To override timestamp:
```
metadata.ts = ts;
```

**Comment by Vaibhav0216** [comment]
Hi @devaskim ,

```
let ts = msg.meterReadingDelta.ts; // Extract timestamp with a fallback
let value = msg.DailyConsumption.value; // Extract value with a fallback

msg.waterVol = { "ts": ts, "value": value };
metadata.ts = ts;

return {msg: msg, metadata: metadata, msgType: msgType};
```
for the above code  below error is comes
`
org.thingsboard.script.api.TbScriptException: java.lang.RuntimeException: TypeError: Cannot read properties of undefined (reading 'ts') in at line number 1
`

**Comment by devaskim** [comment]
@Vaibhav0216 Why not just enable debug mode in this node and test your code in this node by yourself?

**Comment by Vaibhav0216** [comment]
@devaskim, Thanks I don't know about this functionality. 

How can we merge 2 messages data. 

I want to assign timestamp of one telemetry and value of other to same telemetry. 

This two messages comes from two different nodes.

**Comment by devaskim** [comment]
@Vaibhav0216 Take a look at those guides https://thingsboard.io/docs/guides/#AnchorIDDataProcessing

**Comment by Vaibhav0216** [comment]
@devaskim Thank you.
