### ISSUE TITLE
Enrichment - Originator attributes not working.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12158]
Enrichment - Originator attributes not working. 
I have debug and check but "no event found" at debug section. 
![image](https://github.com/user-attachments/assets/3560b9d7-f9e0-4bab-8df2-97606a6b2c16)

**Comment by dealnat** [comment]
Hi, "no events found" means no messages were sent to this rule node. Please check with debug mode if OUT messages with the correct relation type are present on the previous rule node.

**Comment by Vaibhav0216** [comment]
In previous node messages are OUT. previous node working correctly.

**Comment by dealnat** [comment]
Hi, not reproduced in my environment.
![image](https://github.com/user-attachments/assets/725de093-0e70-4975-9ded-400caf182795)
What version do you use?

**Comment by Vaibhav0216** [comment]
Hi @dealnat,
Thank you for your cooperation. The problem is resolved.
