### ISSUE TITLE
It looks like your permissions aren't sufficient to  complete this operations.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12156]
I have created a separate dashboard and customer under him a user which i can login in it and see the dashboard. 

but when I login through the mobile with this user. It say's:-

"It looks like your permissions aren't sufficient to  complete this operations."

how to resolve this issue.

**Comment by mykhailokornieiev** [comment]
Hi
Please describe it in as much detail as possible. 
Did you check the next option?
![image](https://github.com/user-attachments/assets/08d2ebe3-2a9b-4338-a9c2-9be3277ed5c0)

**Comment by Vaibhav0216** [comment]
Hi @mykhailokornieiev ,
I have checked in details also.
Mobile application setting is unchecked. 
![image](https://github.com/user-attachments/assets/4e7cf163-5717-4f25-867b-d5a0c748af1c)

**Comment by mykhailokornieiev** [comment]
Please provide full detailed steps to reproduce. Also, please clarify what mobile application do you use? Is it some from Play Market / App Store, or you've built it on your own?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by Vaibhav0216** [comment]
Hi @mykhailokornieiev ,
Sorry for inactivity due to this issue arise I shifted on other task. I am using own build app.
But I checked in Play store app also same issue arise. For tenant user this issue not comes but for the user this issue comes.

**Comment by mykhailokornieiev** [comment]
This one is exactly the same as your new one:
https://github.com/thingsboard/thingsboard/issues/12523
So, it won't be re-opened and we will continue the investigation in the new one
