### ISSUE TITLE
As user login he can see only dashboard in fullscreen how can I do this?

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12154]
I want to implement functionality like when the user login He can see only the dashboard in fullscreen how can I implement this.

**Comment by basor-dali** [comment]
When user gets created, you will recognize that even in rule chains, and you can change user config from there. 

When user is created, you will get an object like this in rule chains with "ENTITY_CREATED" msgType:

`{
  "id": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "USER"
  },
  "createdTime": 1609459200000,
  "tenantId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "TENANT"
  },
  "customerId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "CUSTOMER"
  },
  "email": "user@example.com",
  "name": "user@example.com",
  "authority": "SYS_ADMIN, TENANT_ADMIN or CUSTOMER_USER",
  "firstName": "John",
  "lastName": "Doe",
  "phone": "38012345123",
  "additionalInfo": {},
  "ownerId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "DEVICE"
  }
}`

You can see that additionalInfo object is empty there. You can place parameters there like this:

`msg.remove("additionalInfo");
var additionalInfo = {};

additionalInfo["defaultDashboardId"] = "52e1cfe0-ffff-11ee-9be6-85794be8ffff";
additionalInfo["homeDashboardId"]  = "52e1cfe0-ffff-11ee-9be6-85794be8ffff";
additionalInfo["defaultDashboardFullscreen"] = true;
additionalInfo["homeDashboardHideToolbar"] = true;

msg.additionalInfo = additionalInfo;

return {msg: msg, metadata: metadata, msgType: msgType};` 


What that will do, it will set a default dashboard to your user, and it will always force it to full screen. 
Hope this is helpful for you. Let me know if you have any more questions

**Comment by mykhailokornieiev** [comment]
Hi
You can set it up the following way:
![image](https://github.com/user-attachments/assets/ccfd2591-aa3d-4dee-9ed1-406d593d1601)
![image](https://github.com/user-attachments/assets/4dd32959-eca3-41cc-868f-e3f8d3033f0c)

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
