### ISSUE TITLE
User with email 'mauli.kshirsagar02@gmail.com' already present in database!

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12153]
I have deleted the user with gmail id "mauli.kshirsagar02@gmail.com" , But still I can't use this gamil id to create the user.

I have checked this on swagger api :- 
```
https://thingsboard.cloud/api/customer/customerId/users?pageSize=1000&page=0
```
response comes like
```
{
    "data": [],
    "totalPages": 0,
    "totalElements": 0,
    "hasNext": false
}
```

**Comment by basor-dali** [comment]
Is it possible that the user is created on another customer, or another tenant?

**Comment by Vaibhav0216** [comment]
I will see. Can you please help me on this issue #12143 ?

**Comment by Vaibhav0216** [comment]
I didn't find api to see all customer under tenant. 
https://thingsboard.cloud/swagger-ui/#/

**Comment by mykhailokornieiev** [comment]
Hi.
Regarding customer users, then you can use the next Rest API call:
https://thingsboard.cloud/swagger-ui/#/user-controller/getAllUserInfos
https://thingsboard.cloud/api/userInfos/all?pageSize=10&page=0&sortProperty=createdTime&sortOrder=DESC&includeCustomers=true 
And as for the customers:
https://thingsboard.cloud/swagger-ui/#/customer-controller/getAllCustomerInfos
https://thingsboard.cloud/api/customerInfos/all?pageSize=10&page=0&sortProperty=createdTime&sortOrder=DESC&includeCustomers=true
Are you sure that you've deleted the user with this email? If this email is used by the different tenant, then you cannot create a user with the same email.

**Comment by Vaibhav0216** [comment]
Means I have created user with different tenant and if I deleted that tenant, In that case can I create. 

What if I want to delete this user of recreation?

**Comment by mykhailokornieiev** [comment]
> Means I have created user with different tenant and if I deleted that tenant, In that case can I create.

I mean, that if you have the user with the provided email under one of the tenants, then you will not be able to create the new user with this email on any tenant account until you delete the previous user.

> What if I want to delete this user of recreation?

Please clarify what do you mean by "user of recreation"?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
