### ISSUE TITLE
Scheduler on CE edition with rule chain

### ISSUE THREAD

**Issue by angelofonte** [thingsboard/thingsboard#12152]
I use the Thingsboard Community version, and I have difficulty creating actions. First of all I would like to be able to activate a relay at a certain time and then turn it off. And the second thing I would like to activate a relay in case the temperature reaches 50°.

I did not find these functions in the Community version, but is it possible to create them somehow?

could you please help me?

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by basor-dali** [comment]
You could use Generator node inside a rule chain, and trigger a message every X settings, and that message can query your device and check the temperature value

**Comment by angelofonte** [comment]
please would you be so kind as to give me some practical examples with the code.

Many thanks

Saluti Angelo Fonte
Il 1 dic 2024, 16:49 +0100, Dali Basor ***@***.***>, ha scritto:

**Comment by basor-dali** [comment]
Please find screenshots of the rule chain that i made quickly here. I have temperature device and relay device on my tenant.

![image](https://github.com/user-attachments/assets/a649f3ad-bc85-4b15-a20d-949d51619419)
![image](https://github.com/user-attachments/assets/3788e458-0124-47e6-83dc-ffa9c26d2e93)
![image](https://github.com/user-attachments/assets/d0356b66-eb33-482d-a4eb-5979d969b44a)
![image](https://github.com/user-attachments/assets/f1af2214-47c8-4936-add1-443c453f9eb7)
![image](https://github.com/user-attachments/assets/66662edc-52cd-4f04-936f-1c4aebcbdbaa)
![image](https://github.com/user-attachments/assets/2767024c-f067-458e-bdff-b45f008ff626)
![image](https://github.com/user-attachments/assets/54c22432-9c56-4ab8-b013-0b473b8ec858)

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
