### ISSUE TITLE
API endpoint to validate device_key

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#1216]
Is there a way to validate whether I have a valid device key without having Thingsboard credentials?  I am writing a script for users to configure their devices, and want to ensure the user entered their device_key properly (the 20 letter code needed to post telemetry).  I could try posting some telemetry to that key, but am looking for a cleaner way, preferably using the API.

Is there such a mechanism?  If not, could I add one?

**Comment by vparomskiy** [comment]
Device token  is a random String so there are no validation rules. But you can fetch a correct token from this REST API:
https://cloud.thingsboard.io/swagger-ui.html#!/device-controller/getDeviceCredentialsByDeviceIdUsingGET

**Comment by eykamp** [comment]
The catch is that the user will not have credentials on the Thingsboard server, and thus won't be able to get an access token.  I basically want to ask the server anonymously if device_key xxxx is valid for device with name yyy.

**Comment by vparomskiy** [comment]
It is not possible by default, because of security restrictions. You will need to modify the source code if it is OK for your case:
org.thingsboard.server.controller.DeviceController.getDeviceCredentialsByDeviceId()
remove **@PreAuthorize** annotation and rebuild sources.
