### ISSUE TITLE
Hidden duplicate telemetry data

### ISSUE THREAD

**Issue by SindreLindahl** [thingsboard/thingsboard#12160]
**Describe the bug**
When overwriting existing data, new data with same ts doesn't overwrite existing data when changing between int and float.

**Your Server Environment**
* Pro Cloud

I don't think any other condition matters, like browser.

**To Reproduce**
1. Make a test device
2. Add telemetry as integer, then add telemetry as decimal / float:

curl -v -X POST http://thingsboard.cloud/api/v1/access-token/telemetry --header Content-Type:application/json --data "{ts: 1733140800000, values: {temperature:1}}"
curl -v -X POST http://thingsboard.cloud/api/v1/access-token/telemetry --header Content-Type:application/json --data "{ts: 1733140800000, values: {temperature:1.5}}"

3. Look at data in widget, aggregate none, sum & count

Aggregation none: Displays the first (integer) value
Aggregation count: Displays 2 (integer value and decimal value)
Aggregation sum: Displays 2.5 (integer value 1 + decimal value 1.5)

**Expected behavior**
I would assume ts is unique key? When overwriting data with same type (int or float), the old value is removed and replaced by new value. Why isn't old value removed and replaced when changing type (int/flot) with same ts?

**Comment by mykhailokornieiev** [comment]
Hi. Thank you for detailed steps to reproduce. I was able to reproduce such behavior.
We have a specific parameter in the thingsboard.yml file that controls if we need to set all data type values except target to null for the same ts on save. 

```
  # Cassandra cluster connection query parameters
  query:
    # set all data type values except target to null for the same ts on save
    set_null_values_enabled: "${CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED:false}"
```

As you can see the default value for this parameter is false, which means that we allow to save multiple data type values for the same timestamp. We didn't change it for thingsboard.cloud
Since the timeseries table can show only one entry per timestamp, it will  show just the first one found. Based on logic on the BE side, the first one is always a long value.

**Comment by SindreLindahl** [comment]
Thanks for detailed info. We have a lot of duplicate data due this behavior. Is it documented anywhere? As you point out I can't see it in table view. Is there any view I can see ALL data? Now that SUM and other aggregations are wrong, is it possible to delete one of the duplicate data (for example long) and only keep the other data (for example int)?

**Comment by mykhailokornieiev** [comment]
Hi.
> Is it documented anywhere? 

Only there: 
> cassandra.query.set_null_values_enabled 	
CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED 	true 	
set all data type values except target to null for the same ts on save
https://thingsboard.io/docs/user-guide/install/config/#cassandra-driver-configuration-parameters

> Is there any view I can see ALL data?

There is no such possibility for thingsboard.cloud. It is only possible to check such values by connecting to Cassandra, that is not possible in case of thingsboard.cloud.

> ow that SUM and other aggregations are wrong, is it possible to delete one of the duplicate data (for example long) and only keep the other data (for example int)?

If you know ts of this data, then you can re-write the data of the necessary data type with TTL 1 second, so it will be automatically retained.

**Comment by SindreLindahl** [comment]
Ok thanks for info! I note the following:
- doc for this important setting is in community documentation, not cloud
- cloud can store 2 different values for a single timeseries per ts
- cloud can only ever view 1 of these values (without aggregation)

This is as close to a bug as it gets. I strongly recommend turning on this setting for all cloud instances. Can't imagine anyone on cloud have usecase for it.

**Comment by mykhailokornieiev** [comment]
Hi. I've discussed this question with developers and we came to the next conclusions:
This is by Cassandra's design, and this parameter won't be changed on Cloud. 
There are no default methods to find and fix such duplicated values. The only workaround is to overwrite all data with a pair of values:
Int with TTL 1, so it will be deleted as soon as the retention period comes. 
Float without TTL, so any int value will look like 1.0. In this case, only float values will be stored. 
There were no recommendations to rewrite int values with float ones, so there is no bug in this case.

**Comment by SindreLindahl** [comment]
Ok thanks for feedback. For those who use node.js (javascript) to generate and send data, the problem is type number used as default for values. All values of x.0 are simplified to just x without decimals (for example 10.0 is simply sent as 10). So the solution for everyone using node.js to send data to TB is to use `.toFixed(1)` everywhere. It's cumbersome, but will fix the issue.
