### ISSUE TITLE
alarm not creating. 

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12183]
This is debug events in alarm not. why not alarms not generating?                                                                       [water_metering_solution_main.json](https://github.com/user-attachments/files/18005121/water_metering_solution_main.4.json)
this this my rule chain please guide me on this.

![image](https://github.com/user-attachments/assets/e795b2ff-990d-4611-80d2-740facb10f4a)

**Comment by Vaibhav0216** [comment]
At a first time alarm created then it goes in updated state.

**Comment by mykhailokornieiev** [comment]
> At a first time alarm created then it goes in updated state.

This is correct behavior by design of Thingsboard. You cannot create alarm for the same originator again if it was previously created until you Clear this alarm. Till then, it will be only updated

**Comment by Vaibhav0216** [comment]
Thank you. I is clear now.
