### ISSUE TITLE
Bug in openstreet maps v.3.8.1

### ISSUE THREAD

**Issue by strangerCatLv** [thingsboard/thingsboard#12195]
**Describe the bug**

hello, I feel this is a bug. in the dashboard that I created, I have defined all asset types, there are 93 assets that have latitude and longitude attribute data.
why on dashboard 1 does not appear all the assets? while on dashboard 2 it appears.
please help, thank you.

**Desktop (please complete the following information):**
* OS: Docker
* Version 3.8.1 PE

**Screenshots**

aliases
![image](https://github.com/user-attachments/assets/1370f551-1333-4f1a-bba7-55c0578ece7e)

dashboard 1
![image](https://github.com/user-attachments/assets/fb6dceab-8fc7-4900-9ddb-7de73a1f0172)

dashboard 2
![image](https://github.com/user-attachments/assets/7a28baf0-acb3-4219-a172-63c5f47c0722)

**Comment by mykhailokornieiev** [comment]
Hi. Please describe this issue in as much detail as possible. Do you use the same widget? Is it Openstreet map widget in both cases? Did you compare their configurations? Please attach your dashboard so I can test it locally

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
