### ISSUE TITLE
Change word on HTML Value Card

### ISSUE THREAD

**Issue by strangerCatLv** [thingsboard/thingsboard#12194]
**Description**

hello, I have a question.
can the words “ENERGY DISABLED” be changed?
I'm using HTML Value Card. 
Thank you.

**Environment**
 * OS:  Docker
 * ThingsBoard: version 3.8.1 PE

![Screenshot 2024-12-05 085336](https://github.com/user-attachments/assets/bb244e13-c387-4413-b89e-d78f081cd797)

**Comment by Backdraft007** [comment]
Hi,
I'm sorry, but I can't follow your question? Normally you can change it yes. But not enough information from you, waht do you want to achieve.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
