### ISSUE TITLE
Multiple level relation from Assets to Device telemetry data not showing (mixed entities)

### ISSUE THREAD

**Issue by peterandthejetsons** [thingsboard/thingsboard#12201]
Hi!

I try to create a simple relation scenario. I have a some assets and the end of relation i have a device, the relation looks like this:
asset1 -> asset2 -> asset3 -> asset4 -> device01

I have entity alias on my dashboard with relation query what has asset entity type of root level. I try to get values from device on map widget, datakeys showing up, but when i try to display values i everytime get nothing, i mean null value.

Is my idea wrong, or is this not possible to implement that easily?

Thanks in advance!

**Comment by mykhailokornieiev** [comment]
Hi
Please provide more details regarding your relations hierarchy and used entity alias in dashboard
What relation types do you have between your entities? How many relations levels did you specify in your entity alias?

**Comment by peterandthejetsons** [comment]
Hi!

I have 4 Assets and 1 Device
Relation looks like this with type of relation:

Asset 1 --- TO --> Asset 2 --- TO --> Asset 3 --- TO --> Asset 4 --- TO --> Device 1

Im using unlimited levels of relation in entity alias. 
Filter type is Relation query 
Root entity type is Asset
Direction is To and last level fetch function and relation filters are not used.

Let me if you need further information.

Thanks in advance!

Regards,
Peter

**Comment by mykhailokornieiev** [comment]
You've specified Relation Directions. 
Please clarify your Relation Types between your entities. By default, it's either Contains or Manages. You've specified 
![image](https://github.com/user-attachments/assets/6b0c23f8-e00e-440b-aea8-234acb9331be)

**Comment by peterandthejetsons** [comment]
Yes, sorry. Im using Contains type of Relations in every case.

**Comment by mykhailokornieiev** [comment]
I was unable to reproduce this behavior.
![image](https://github.com/user-attachments/assets/96eb5ac3-109e-46cb-bb2f-8363d8e3612d)
![image](https://github.com/user-attachments/assets/b9cf7417-47bc-446b-b9ab-b37d453017f8)
![image](https://github.com/user-attachments/assets/63b8ec03-1016-44d3-b6ad-3e1f7300beaf)
Please compare it with your settings

**Comment by peterandthejetsons** [comment]
Hi! 

With Timeseries table it works, but i would like to use with map widgets (latest type) in this way. Can it work somehow with a map widget?

Thanks in advance!

Regards,
Peter

**Comment by mykhailokornieiev** [comment]
Yes, it can be done (at least with Openstreetmap widget)
![image](https://github.com/user-attachments/assets/5e3bb7ac-1cad-455a-8c34-9db5b98b58d1)

**Comment by peterandthejetsons** [comment]
Ok, i'll check and let you know. 

Thanks in advance.

Regards,
Peter

**Comment by peterandthejetsons** [comment]
Hi!

In my case there was a difference, in the chain my device wasn't the last entity, it's related with TO direction to MQTT intergration, because it's created by the intergration. I tried to remove, but not helped. One other difference, in the entity alias for this reason i don't use Fetch last level relation only option. I tried to create another dashboard and its works, it doesn't look quite like yours, but works:

Entity alias:
![image](https://github.com/user-attachments/assets/cf313dca-3795-4f3d-963e-42446e40e51f)

Entity hierarchy:
![image](https://github.com/user-attachments/assets/a60c6810-b456-418e-b4b4-3ae6245d2cee)

Map:
![image](https://github.com/user-attachments/assets/09db6558-f1be-456e-a9d3-c7f77401b69c)

In this case the device has latitude and longitude server type attributes, but in the original case the lat and lon attributes are on the 4rd Asset in the chain. I tried it and its the same:

![image](https://github.com/user-attachments/assets/1dc25c13-7e67-4af3-bc26-5ac88d172a02)

So if i have lat and lon attribute on asset and i'd like to use telemetry data what comes from device the device gives back nothing.

Is there a way to get it work or is this the expected behavior?

Thanks in advance!

Regards,
Peter

**Comment by mykhailokornieiev** [comment]
Hi
Please try the next, I was able to make it work even with additional relation after the device:
![image](https://github.com/user-attachments/assets/38bbb0c4-1bd7-4a1b-93db-357dc1e6160e)

**Comment by peterandthejetsons** [comment]
I tried it in a fresh CE docker based installation, let me show you my results step by step:

Asset1 (there is no FROM just TO relation):
![image](https://github.com/user-attachments/assets/4dad7b7f-463d-4922-be74-0059ecbf0cd4)

Asset2 (there is a FROM relation from Asset1):
![image](https://github.com/user-attachments/assets/2000c019-7284-4215-ad20-8f0b78d73494)

Asset2 (TO relation):
![image](https://github.com/user-attachments/assets/86b2b542-a86f-4260-91ec-2dd14d8f4064)

Asset3 (there is a FROM relation from Asset2):
![image](https://github.com/user-attachments/assets/3ee053a6-bf24-4923-b7fe-c0f35d5a1bbb)

Asset3 (TO relation):
![image](https://github.com/user-attachments/assets/57e86829-7aea-4b87-af26-4c5843375212)

Asset4 (there is a FROM relation from Asset3):
![image](https://github.com/user-attachments/assets/16333a38-8b6a-4d33-a01a-b9b8d02b1159)

Asset4 (TO relation):
![image](https://github.com/user-attachments/assets/77395963-5c66-4e0f-b903-7ac782ffabdf)

Device1 (there is a FROM relation from Asset4):
![image](https://github.com/user-attachments/assets/d21b3d1d-3596-4e58-83ba-29c19b77512f)

In case of Device1 there is no TO relation to additional entites. The next picture show Asset4's attributes (lat, lon):
![image](https://github.com/user-attachments/assets/db32b4eb-09e5-4473-bdf4-295e22a29dfb)

I created Dashboard1 and add 2 widgets (Entities hierarchy):
![image](https://github.com/user-attachments/assets/5a434fa9-0233-421b-b02a-5481a18bb515)

Entities hiearchy widget uses the following code:

```
var entity = nodeCtx.entity;
var query = {
  parameters: {
    rootId: entity.id.id,
    rootType: entity.id.entityType,
    direction: "TO",
    maxLevel: 4
  },
  filters: [{
    relationType: "Contains",
    entityTypes: []
  }]
};
return query;
```

In the code i modified the direction and the level, but it doesn't look like yours. Asset1 doesn't even appear for me, and the relations are displayed multiple times. 

I manually created a string based telemetry key with value for Device1, what looks like this:
![image](https://github.com/user-attachments/assets/bb62e4e9-4df9-4c03-ba9d-66afd38b7f79)

The map widget can use Asset4's latitude and longitude attributes but it cant uses Device1 telemetry data:
![image](https://github.com/user-attachments/assets/d3eb0a16-1b0a-42e9-a0e8-cf5e7a3e9435)

![image](https://github.com/user-attachments/assets/3eecf28b-4def-4819-b8dd-075aa671821e)

![image](https://github.com/user-attachments/assets/8adfbd7e-6df5-4b26-a047-0e6d3cece893)

I'm using an entity alias like yours without additional filters:
![image](https://github.com/user-attachments/assets/51f66fbe-7150-4624-9de3-bae2a1e7af5f)

What am i doing wrong?

Thanks in advance!

Best regards,
Peter

**Comment by mykhailokornieiev** [comment]
Hi

>In this case the device has latitude and longitude server type attributes, but in the original case the lat and lon attributes are on the 4rd Asset in the chain. I tried it and its the same:

Please clarify, do your problem occur only when device has a key **key** and latitude & longitude are on some other entity (some of the Assets)
In this case, it won't work. All of the values must be on the same entity. If all of your entities (Asset 1/2/3/4 and Device) have longitude&latitude&key, then you will have 4 entities on map with key value. It's impossible to represent key of on entity with location of another.

**Comment by peterandthejetsons** [comment]
Hello!

Yes, I only experienced the problem when I wanted to use keys on different levels, e.g. the lat-lon key is specified as an attribute on Asset4, and the key is specified on Device1, which is the 5th level in the relation. I tried several scenarios, but I have to admit that it doesn't work, so I modified my idea and use duplicate to related node. Thank you very much for your help!
