### ISSUE TITLE
alarms count 

### ISSUE THREAD

**Issue by gurverm** [thingsboard/thingsboard#12204]
The alarms count widget is showcasing the proper count in the development dashboard. However, when i login as the customer that the same dashboard is assigned to, the count shows 0. The alarms table displays the proper alarms it is just the count that is not being displayed.

<img width="434" alt="Screenshot 2024-12-05 at 2 23 12 PM" src="https://github.com/user-attachments/assets/898a2769-7694-4696-88cb-f20eaa8da94d">

<img width="385" alt="Screenshot 2024-12-05 at 2 23 02 PM" src="https://github.com/user-attachments/assets/b9c8f442-f61f-4cdf-9dfe-8d86fc26a49e">

**Comment by devdoob** [comment]
What user group are using for you customer user?

**Comment by gurverm** [comment]
Customer User with the role of customer administrator. They can see the alarms table displaying alarms on their end but the alarm count is not changed

**Comment by devdoob** [comment]
Share image of "data" and "appearance" tab of this widget

**Comment by mykhailokornieiev** [comment]
Hi
The Alarm Count widget is able to display only alarms of the level on which this widget is located. So, to display the total number of alarms for a sub-customer, the widget must be at the sub-customer level only.
The tenant is the only user who sees the count of all the alarms with the alarms count widget.

**Comment by gurverm** [comment]
> Share image of "data" and "appearance" tab of this widget

<img width="952" alt="Screenshot 2024-12-06 at 9 48 06 AM" src="https://github.com/user-attachments/assets/f7fd66b7-e306-4e38-a8e7-8c564c900613">
<img width="949" alt="Screenshot 2024-12-06 at 9 48 14 AM" src="https://github.com/user-attachments/assets/b564ad54-052b-4420-b894-7e1d27d34cdc">

**Comment by gurverm** [comment]
@mykhailokornieiev I'm confused. so there is no way to showcase the alarms count for customer users? A user must be a tenant to view this?

**Comment by mykhailokornieiev** [comment]
Hi @gurverm 
Alarm Count rule node is designed to:
Tenant level: display count of alarms on each level from tenant to customer in hierarchy
Customer level: display only alarms of devices on this level, so owner of devices is this customer
If your customer have no devices with active alarms in ownership, then it will display 0.

**Comment by ashvayka** [comment]
Hi @gurverm , apologies for the confusion. Is it possible to share the dashboard JSON so I can check your alarm count widget configuration? You may attach the dashboard with only this widget. Also I need the alarm table screen on the tanant and customer level. 

The best case is to create a dashboard where both alarm count card and alarm table widget are located. This will make sure that the alias and alarm filter is the same but the widget data is different. 

Besides, it is necessary to attach the information about your server according to the 'new issue' template: platform version, installation type, etc.

**Comment by gurverm** [comment]
@mykhailokornieiev is there anyway for me to add an existing device to the customer? 

@ashvayka i emailed you at ashvayka@thingsboard.io with the subject line of "Alarms count #12204" with the JSON of the dashboard that i created. As for the version i am using thingsboard PE

**Comment by mykhailokornieiev** [comment]
Hi @gurverm 
Depending on your Thingsboard edition, there are two options:
PE - "Manage owner and groups" feature
![image](https://github.com/user-attachments/assets/a0a3fbb8-cc3e-48de-9905-06a8e8b02e3d)
CE - "Assign to customer" feature
![image](https://github.com/user-attachments/assets/3fd6429d-7aa5-4a0d-ab5c-3861c6a46489)
Let me know if you still have any questions

**Comment by gurverm** [comment]
@mykhailokornieiev I have added all existing devices to this customer and the alarms count still has not changed.

**Comment by mykhailokornieiev** [comment]
Hi @gurverm 
Please clarify the following: 
Do you have any device on this customer level with alarm that was created after you added this device to this customer? 
Please duplicate for me the data you shared with @ashvayka so I can investigate it more precisely

**Comment by gurverm** [comment]
@mykhailokornieiev I have not had any new alarms since making these changes. Do you have an email that i can send you the json file at?

**Comment by mykhailokornieiev** [comment]
@gurverm please create a new alarm for devices on this level. 
You can share details with me at mkornieiev@thingsboard.io

**Comment by gurverm** [comment]
@mykhailokornieiev I created a new alarm and it appears on the customers end! Thank you so much

**Comment by mykhailokornieiev** [comment]
Hi. I'm glad to hear that it helped. 
The Alarms Count rule node will only display alarms created by devices when the customer owns them. 
Do you have any additional questions regarding this ticket?

**Comment by gurverm** [comment]
@mykhailokornieiev One last question on this topic. Is there any way for me to return the devices label on the alarms table. I havent found a way to change either the originator value to display the label or for the alarm to include the label
<img width="1348" alt="Screenshot 2024-12-17 at 10 46 03 AM" src="https://github.com/user-attachments/assets/0679157c-818b-421f-9c88-0132d4f13f25" />

**Comment by mykhailokornieiev** [comment]
Hi @gurverm 
For such a purpose, you can add entity field "label" as datakey for your datasource:
![image](https://github.com/user-attachments/assets/f1c3b825-0bad-4a31-a40b-a75b6994ea39)
![image](https://github.com/user-attachments/assets/73b20268-1c3a-48e9-94bd-d36dde57f706)

**Comment by gurverm** [comment]
Ahh perfect. Thank you

**Comment by mykhailokornieiev** [comment]
@gurverm I'm glad to hear that we've managed to solve this problem. 
In this case, I close this ticket as solved
