### ISSUE TITLE
How to use entity-view ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1221]
Hi,
We are using TB PE 2.1.3. Do anyone knwo how to configure entity-view ? Where can I find the user guide or document ?

Regards,

Paul Wang

**Comment by brandlyze** [comment]
Same here, also looking for any docs...

**Comment by vparomskiy** [comment]
We are working on documentation and it will be available in the nearest time.

**Comment by oroi1991** [comment]
> We are working on documentation and it will be available in the nearest time.

Could you simply explain about entity-view?

**Comment by vparomskiy** [comment]
You can find a brief explanation here:
https://github.com/thingsboard/thingsboard/issues/1252

**Comment by oroi1991** [comment]
> You can find a brief explanation here:
> #1252

Thanks a lot :)
