### ISSUE TITLE
Entities hierarchy widget - Doubt

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#12234]
**Component**
 * Generic

**Description**
Hi there,

We would like to print within an _Entities hierarchy widget_ all those who have an active and unacknowledged alarm (for example, in red). We believe that it may be by modifying something witin the _Appearance_ tab (perhaps in the _Node text function_ section), what could it be? 

Feel free to modify the code attached below:
``` Javascript
// Function should return text (can be HTML code) for the current node.
// The following example code will generate node text consisting of entity name and temperature if temperature value is present in entity attributes/timeseries.

var data =  nodeCtx.data;
var entity = nodeCtx.entity;
var text = entity.name;

if (data.hasOwnProperty('Type') && data['Type'] !== null) {
    text += '<i> - ' + data['Type'] + '</i>';
}

var ret = text;

/*
if something, then:
    ret = '<b><font color=\"#FF5A5A\">' + text + '</font></b>';
}
*/

return ret;
```

What we have now:
![image](https://github.com/user-attachments/assets/a0a1a64a-d141-448e-9709-fae6f952073e)

What we would like to have (the picture has been manually modified):
![image](https://github.com/user-attachments/assets/90bc3a21-82c5-475c-80d4-ff5b5b35a7ed)

Thank you for your time and looking forward to hearing from you.

Kind regards.
Daniel.

**Environment**
 * OS: Monolitic setup using AWS infrastructure
 * ThingsBoard: 3.7.0PE
 * Browser: Chrome

**Comment by devaskim** [comment]
```
const entityName = 'ES152770';
return `<span style="color: red;">${entityName }</span>`;
```

**Comment by mykhailokornieiev** [comment]
Hi @dpergarc-c 
>We would like to print within an Entities hierarchy widget all those who have an active and unacknowledged alarm

As for this part of a request, you can use the following code snippet as a reference for the alarmService usage with widgetCtx:
```
let alarmService = widgetCtx.$scope.$injector.get(widgetCtx.servicesMap.get('alarmService'));
    let pageLink = widgetCtx.pageLink(10,0,'General Alarm');
    alarmService.getAlarmTypes(pageLink).subscribe(data=>{
console.log(data);
});
```
![image](https://github.com/user-attachments/assets/96dc2c7a-bb85-4c36-899b-2362dc24ad75)

**Comment by dpergarc-c** [comment]
Hi guys,

Thank you very much for your replies.

Yes @mykhailokornieiev!!! We can add the node "_Alarm count_" in one of our rule chains, and in combination with what you say, it might work!!! I will let you know the outcome in any case.

Kind regards.
Daniel.
