### ISSUE TITLE
add originatorLabel or/and details as template parameters at Alarm notification templatization

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard#12242]
The alarmOriginatorName is often not very helpful, especially for users managing a large number of devices. I believe there should be an additional parameter (such as originatorLabel or details) that users can customize to better suit their needs.

**Comment by mykhailokornieiev** [comment]
Hi. Such a feature request was previously added to our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by Tasosgi** [comment]
Hello, Thank you.Do you have an estimate for when this feature will be released?

**Comment by mykhailokornieiev** [comment]
@Tasosgi There is no estimated time or even if it will be implemented at all.

**Comment by mykhailokornieiev** [comment]
Hi
We are glad to inform you that the alarmOriginatorLabel template parameter, as well as details, have been successfully added to the Alarm Notification Template in the v4.3 release.
Feel free to open a new ticket in case any questions or issues arise.
Have a great day.
