### ISSUE TITLE
Does ThingsBoard support OAuth2 Device Authorization Grant (Device Flow)?

### ISSUE THREAD

**Issue by danielef** [thingsboard/thingsboard#12245]
**Component**
 * OAuth2

**Description**
Hello there! I am investigating the OAuth2 capabilities of ThingsBoard for a project involving tenants logging onto devices with limited input capabilities. I would like to know if ThingsBoard implements the OAuth2 Device Authorization Grant, _aka_ Device Flow.

Thanks!

**Comment by sumin-denys** [comment]
Hi @danielef,

Unfortunately, ThingsBoard doesn't support Device Flow, and we don't plan to implement this feature the future. If you have any further questions, please let me know.

> Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).

**Comment by sumin-denys** [comment]
Hi @danielef,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.

> Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
