### ISSUE TITLE
OTA: Assigning firmware create server attribute with key = NULL

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#12241]
**Describe the bug**
When you assign a firmware to a device, TB generates a server attribute with NULL as key name and value of the OTA_PACKAGE.
I cannot remove this server attribute because NULL is normally not allowed.

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: deb
  * 3.7.0 PE
  * Professional Edition
  * Debian 12

**To Reproduce**
1. Go to 'Devices'
2. Click on 'on a device'
3. Assign a firmware
4. Go to server attributes
5. First key is NULL and deletion is not possible

**Expected behavior**
Creation of an attribute with key name = NULL should be prevented

**Screenshots**
![Screenshot 2024-12-12 111214](https://github.com/user-attachments/assets/7b39ad70-dead-46a1-b4d7-b435a8729d9d)

**Additional context**
In my test enviornment 3.8.1 CE, I cannot reproduce this behavior.
How can I delete this attributes from my devices?
Are this attributes a problem to upgrade from 3.7.0 PE -> 3.8.0 -> 3.8.1?

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @Backdraft007,

Thank you for your report! This is a bug that was resolved in the 3.8.0 release. 
For the further correct operation of the platform and the OTA updates feature, you do not need to remove this attribute, as it is used for the OTA updates feature.
There isn't any problem during the upgrade process. This attribute will be moved to the corresponding db table when the platform upgrades.
If you still have questions about this issue, please let me know.

**Comment by Backdraft007** [comment]
Hi @sumin-denys,
when you have a device which has this wrong attribute, you cannot add new widget properly. When you try to add data keys, TB don't show any attributes.
I decided to delete all wrong attributes in the postgres database with:
`DELETE FROM attribute_kv WHERE attribute_key = 0;`
After this command I can add data keys to the widget again.

I close this issue because it is resolved in 3.8.0. This info only for those who are searching for the same problem. :)

**Comment by Backdraft007** [comment]
@sumin-denys,
I have just upgraded to 3.8 -> 3.8.1 and left the wrong server attributes. After the upgrades the wrong attributes are still there and block the usability to add new widgets.
After deletion of attributes with key id = 0 all work fine now.

**Comment by sumin-denys** [comment]
Hi @Backdraft007,

Thank you for your comment!
I will try to reproduce this issue again. Could you please add steps to reproduce it so I can achieve the same behavior as you?

**Comment by Backdraft007** [comment]
Hi @sumin-denys ,
sorry I was on holidays.
On TB-PE-3.7.2 assign a firmware to a device. The device has now a server attribute with an empty key name and a hash in value.
When you upgrade to 3.8. and then to to 3.8.1 the key name is still empty.
