### ISSUE TITLE
TbActor performance

### ISSUE THREAD

**Issue by jay-eb** [thingsboard/thingsboard#12240]
**Component**

 * Rule Engine

**Description**
I use mqtt and kafka to connect my devices and i adjust qps to  check my tb server performance. 
My tb server is monolith and if qps is over some specific value, the server will reports OOM.
So i look into where the data backlog. I found kafka consumer lag is stable, but `TenantActor`'s  queue size only increase, not decrease. See log below, i print log  on [TbActorMailbox.enque()](https://github.com/thingsboard/thingsboard/blob/f21275b4bd83d46149358fdc964852f1841b05cb/common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java#L107) .
![img_v3_02hg_c8832581-f36f-4bd6-b1b6-3391c7872ebg](https://github.com/user-attachments/assets/fcbc43f2-1ab1-4630-8ca8-b295fe433693)
Since the size always increase, and it will lead to OOM.
When i minus qps to a lower level, the queue size back to normal which is 0 or a number less than 10.

So my question is is there way to prevent OOM from qps on high level?  I found some params in `thingsboard.yml` including `${actors.system.throughput}` and `${tenant_dispatch_pool_size}` but they are not work for me when I adjust them value.

**Environment**

 * OS: ubuntu

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. 
Please, describe your request in as much detail as possible with full steps to reproduce. 
Please clarify how exactly you change QPS level?

**Comment by jay-eb** [comment]
@mykhailokornieiev Thanks. Here I will post my test code.
I use `mosquitto` to simulate Mqtt requests and the code of test is here
[Uploading SimuDocap_20241207_154939.tar.gz…]()
Unzip it and in `config/simuDocap.json`, we can change `simuDevNum` to simulate count of devices to connect and change `DefSendConf.delayMin/max` to change qps. My server is 128GB in-memeory and JVM maxheapsize is 64GB. When I set simuDevNum=50` , `delayMin=10` and `delayMax=100`ms, it will reproduce it.

**Comment by jay-eb** [comment]
I find that if I use `queue=in-memory`, actor's msg queue size will be 0 which means no data backlog. Anyone can help me explain it ?

**Comment by mykhailokornieiev** [comment]
Hi
Try to enable **TRACE** logging level for **org.thingsboard.server.actors** in /etc/thingsboard/conf/logback.xml
After that, please restart your Thingsboard service so changes take effect. Then, please provide your thingsboard.log file with the list of tenant and device IDs, so we can check it from our side.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
