### ISSUE TITLE
new pasted widget (strg+v) hides behind other widgets

### ISSUE THREAD

**Issue by ts-itn** [thingsboard/thingsboard#12276]
**Describe the bug**
In Short: When a new widget is pasted into a dashboard, it hides behind other widgets after configuring, but stays put after relocating.

**Environment**

OS: Windows 10 Pro
ThingsBoard: v.3.8.1PE
Browser: Version  Chrome 131.0.6778.140 

**To Reproduce**
When copying a widget in a dashboard and adding it in the same or another dashboard (both times using the right-click-menu) then the widget is added normally.
But then after opening and closing the configuration menu (by using the pencil icon at the top right of the widget) the widget hides behind another widget that existed before.
By shifting widgets one after another the new widget can be found and relocated to a new position. Then after saving the new widget stays at the new location and everything works as expected. 

**Expected behavior**
Once the widget is pasted in a dashboard it shall stay put.

**Comment by ashaforost** [comment]
This bug is confirmed by our team. The fix will be released in upcoming v3.9. The release is expected in the beginning of the next year. Follow our release notes at https://thingsboard.io/docs/pe/reference/releases/
