### ISSUE TITLE
Can the widget send a command at a specified time when the dashboard screen is closed?

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1229]
Hello
I've made a widget that can be done at that time and then turn on the light. There is a problem after the time is set when the webpage of the dashboard is closed, it will not work anymore, but if the webpage is open, the light will be on at the specified time, also from The localstorage function is used in javascript for storage. What do you think is a problem?

**Comment by vparomskiy** [comment]
You should implement required behavior inside Rule Engine or via Scheduled events - they are processed on the backend. The logic that is implemented inside a widget is only executed when widget/dashboard is opened.

**Comment by m0o0** [comment]
thank you for your guidance
The problem was solved @vparomskiy
