### ISSUE TITLE
Simple card does not show numbers after decimal

### ISSUE THREAD

**Issue by tumalow-will** [thingsboard/thingsboard#123]
The widget "Simple Card" does not show and numbers after decimal on release 1.2.2.  

To recreate perform the following steps on the UI:
  - Devices --> latest telemetry --> select any floating point data item
   - show on widget --> Simple card --> add to dashboard 
  - Go to edit mode on the dashboard.  Edit the simple card.  
  - Change "Number of digits after floating point" to something > 0
   - Click the check mark to OK changes.  The number will still not show floating point.

**Comment by ikulikov** [comment]
Fixed in release 1.3.0.
