### ISSUE TITLE
Can't create a custom menu

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#12300]
**Component**

 * UI

**Description**
Hi, I would like to create custom menu for customer but I can't have the plus button to add a menu.
![image](https://github.com/user-attachments/assets/94d4607b-ef14-49eb-b435-8109f25e19b1)
I am logged with tenant administrator account.
What I have to do to be able to create custom menu?
Thanks for your answers.

**Environment**

 * ThingsBoard: 3.5.1PE
 * Browser: EDGE or CHROME

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi @liotys 
I agree with @Backdraft007, and it will be the best option to use the updated Custom Menu on 3.8.1, but it probably won't fix your issue.
> I would like to create custom menu for customer. I am logged with tenant administrator account.


Only customer user/admin can create Custom Menu for its level on 3.5.1 

> but I can't have the plus button to add a menu.

I'm more than sure that your user has no White Labeling -> Write permissions, only Read
I was able to reproduce it this way:
![image](https://github.com/user-attachments/assets/27777988-6ee1-4595-b015-26cf1b0ba1d6)
![image](https://github.com/user-attachments/assets/fbe02196-5fbd-45c7-9506-76f8ed68e7f3)
![image](https://github.com/user-attachments/assets/7aedace4-22d3-49bd-a03f-b8b6101ef31f)
"Save" button became available  as soon as I add Write permissions (All = Write + Read)
![image](https://github.com/user-attachments/assets/3f4af1de-311c-4044-9312-dd85fe1d9da5)
![image](https://github.com/user-attachments/assets/a88a0347-a5cd-4ff2-ac73-164e008063a2)


I highly recommend you to get familiar with the following documentation:
![image](https://github.com/user-attachments/assets/dcc40944-f3f7-4d40-8008-1591ecdec92f)

**Comment by liotys** [comment]
Hi @Backdraft007 , @mykhailokornieiev 
Thanks for your answers.

> I agree with @Backdraft007, and it will be the best option to use the updated Custom Menu on 3.8.1, but it probably won't fix your issue.
I have the "save" button, I just need the "plus" button to create several menus and associate them with clients/profiles.
As I can see, it's not in 3.5.1.
So I will use the indication of #7543 to solve my problem.
