### ISSUE TITLE
I am adding links URL to some events.Can I do that when I click on this event, I went to the page where this photo will be?Perhaps someone was doing something like that?

### ISSUE THREAD

**Issue by AndriiHavrylyak** [thingsboard/thingsboard#1230]
![3](https://user-images.githubusercontent.com/38010614/48053947-98e04e80-e1b4-11e8-968f-2ad2bb0722c9.jpg)

**Comment by vparomskiy** [comment]
You can configure different action types in the Alarm Widget.
In your case, I recommend creating 'On row Click' action with type 'Custom Action'. In the Custom action, you can create a dialog where an image will be shown.

**Comment by AndriiHavrylyak** [comment]
I accepted your advice, now when I click on an event, I have a photo with a message.But I made the URL only a constant, (one photo is revealed for all events) how can I assign a photo to each event?I want to use URL with Alarm details?

**Comment by vparomskiy** [comment]
you can save url in the alarm details. And use this URL when showing a dialog.

**Comment by AndriiHavrylyak** [comment]
I save the url in alarms  details , and open it this way. What is my problem?

![48053947-98e04e80-e1b4-11e8-968f-2ad2bb0722c9](https://user-images.githubusercontent.com/38010614/48708477-559dcb00-ec0b-11e8-80f3-a6c88945ef94.jpg)
![default](https://user-images.githubusercontent.com/38010614/48708480-58002500-ec0b-11e8-82b8-adf113df59df.png)

**Comment by AndriiHavrylyak** [comment]
How to use URL for details?
