### ISSUE TITLE
Thingsboard DashBoard copy

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#12309]
---

### **Description**

In the ThingsBoard dashboard custom widgets, when attempting to use **Ctrl + C** to copy content, the selected content does not get copied to the clipboard. Each time **Ctrl + C** is pressed, the content is not copied. The content can only be copied by right-clicking the selected content in Google Chrome and choosing "Copy".

### **Steps to Reproduce**

1. Open a ThingsBoard dashboard and navigate to a custom widget.
2. Select some content (e.g., text or value) in the widget.
3. Press **Ctrl + C** to copy the selected content.
4. Notice that the content is not copied to the clipboard.
5. Only by right-clicking the selected content and choosing "Copy" can the content be copied successfully.

### **Expected Behavior**

Pressing **Ctrl + C** should copy the selected content to the clipboard directly without needing to right-click and choose "Copy".

### **Actual Behavior**

Pressing **Ctrl + C** does not copy the selected content to the clipboard. You need to right-click on the selected content and choose "Copy" for it to be copied successfully.

### **Environment**

- ThingsBoard Version: thingsboard v3.6.4
- Browser: Google Chrome 
- Operating System: windows

### **Additional Information**

It would be helpful if the issue with **Ctrl + C** could be resolved, allowing users to copy content more conveniently without having to right-click.

---

**Comment by mykhailokornieiev** [comment]
Hi
For now, there’s no possibility to copy the text from the widget using CTRL+C
However, this is a valid improvement was previously  added to our backlog.
There's no set timeframe for this improvement; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. Currently, it is possible to copy from a widget using Ctrl+C starting from the 4.0 release.
