### ISSUE TITLE
Cannot connect tb-gateway with Thingsboard server

### ISSUE THREAD

**Issue by juanWZH** [thingsboard/thingsboard#1231]
I cannot connect tb-gateway with Thingsboard server.. I guess my tb-gateway.yml is wrong, who can show me the right file of tb-gateway.yml,and if there need other file to be modificated in conf folder? my version of tb-gateway is 1.4.0 , please tell me the solution if you know..thanks a lot!!

**Comment by juanWZH** [comment]
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"
gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "demo.thingsboard.io"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "j3CQcoEXcmGJ8BMpK2KK"
        remoteConfiguration: true
opc:
  enabled: true
  configuration: opc-config.json
mqtt:
  enabled: true
  configuration: mqtt-config.json
sigfox:
  enabled: false
  configuration: sigfox-config.json
file:
  enabled: true
  configuration: file-config.json
      extensions:
        -
          id: "http"
          type: "HTTP"
          extensionConfiguration: http-config.json

This is my tb-gateway.yml.

![image](https://user-images.githubusercontent.com/30304898/48106447-6bf47000-e276-11e8-8a91-03a3e7ca706f.png)

**Comment by juanWZH** [comment]
server:
address: "0.0.0.0"
port: "9090"

updates:
enabled: "${UPDATES_ENABLED:true}"
gateways:
tenants:
-
label: "Tenant"
reporting:
interval: 60000
persistence:
type: file
path: storage
bufferSize: 1000
connection:
host: "demo.thingsboard.io"
port: 1883
retryInterval: 3000
maxInFlight: 1000
security:
accessToken: "j3CQcoEXcmGJ8BMpK2KK"
remoteConfiguration: true
opc:
enabled: true
configuration: opc-config.json
mqtt:
enabled: true
configuration: mqtt-config.json
sigfox:
enabled: false
configuration: sigfox-config.json
file:
enabled: true
configuration: file-config.json
extensions:
-
id: "http"
type: "HTTP"
extensionConfiguration: http-config.json
This is my tb-gateway.yml, and it have this bug.
![image](https://user-images.githubusercontent.com/30304898/48106550-c2fa4500-e276-11e8-8187-0f5cd61d718c.png)

**Comment by BIT-masterpy** [comment]
Can you submit a full error log?

**Comment by juanWZH** [comment]
the problem has already be solved.I change the port from 1883 to 1882 in the config file of mosquitto and thingsboard. It works.

**Comment by andrevvell** [comment]
> 1883 to 1882 
Are you sure that you used the same port (1882) on both (mosquitto and thingsboard)?
Or did 1882 to mosquitto 
and 1883 to thingsboard (on MQTT configuration section)?
