### ISSUE TITLE
Could run Thingsboard v3.8 community version on Ubuntu 22.04 64bit version with 4GB RAM?

### ISSUE THREAD

**Issue by friedrich86** [thingsboard/thingsboard#12317]
Could run Thingsboard v3.8 community version on Ubuntu 22.04 64bit version with 4GB RAM?

I use ubutnu 22.04 64bit version 4GB RAM
Run thingsboard v3.8 with postgresql
And When starting thingsboard, it is normal with about 80% percent usage of RAM.
Then ram starts to use more slowly, and thingsboard will be killed by kernel or be shutdown because of no eought ram, I don't know.

I have tried the following method but with no effect.
# Update ThingsBoard memory usage and restrict it to 2G in /etc/thingsboard/conf/thingsboard.conf
export JAVA_OPTS="$JAVA_OPTS -Xms2G -Xmx2G"

--------------
So , could we run thingsboard 3.8 community version on ubuntu 22.04 64bit version with 4GB RAM?

Thanks for any reply.

**Comment by idealissst** [comment]
Hello there,
Could run Thingsboard v3.8 community version on Ubuntu 22.04 64bit version with 4GB RAM?
Yes, it is definitely possible.

I just need a bit more information: Are there any other services running on the machine, or are you using any third-party tools with ThingsBoard, such as Kafka or RabbitMQ, how many messages are being received by your instance?

**Comment by friedrich86** [comment]
> Hello there, **Could run Thingsboard v3.8 community version on Ubuntu 22.04 64bit version with 4GB RAM?** Yes, it is definitely possible.
> 
> I just need a bit more information: Are there any other services running on the machine, or are you using any third-party tools with ThingsBoard, such as Kafka or RabbitMQ, how many messages are being received by your instance?

Yes，I run thingsboard with 3rd tool Kakfa, almost 0 message in my scene. During the tesing, thingsboard receive about ONE mqtt message (about 500bytes) one day.
PS: There is just Thingsboard+postgresql+Kafka in Ubuntu,no other service running.

**Comment by idealissst** [comment]
Hello there,
The screenshot below demonstrates that I was able to run the thingsboard community edition (3.8 version), and it works properly without any errors/exceptions/killings by the kernel.

![image](https://github.com/user-attachments/assets/a049ceb6-130f-4e77-b1b7-859f2d7d78d9)

I am using VMware Workstation, which has 4 gigabytes of RAM and two cores.
Please provide a full thingsboard log so I can analyze the issue and find a proper solution.
You can locate the log file by the following path: 
`/var/log/thingsboard`
I need the file named `thingsboard.log`; please send the log exactly after the thingsboard "gets killed".

**Comment by friedrich86** [comment]
> Hello there, The screenshot below demonstrates that I was able to run the thingsboard community edition (3.8 version), and it works properly without any errors/exceptions/killings by the kernel.
> 
> ![image](https://private-user-images.githubusercontent.com/58531855/398742717-a049ceb6-130f-4e77-b1b7-859f2d7d78d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDExMTIsIm5iZiI6MTczNTM0MDgxMiwicGF0aCI6Ii81ODUzMTg1NS8zOTg3NDI3MTctYTA0OWNlYjYtMTMwZi00ZTc3LWIxYjctODU5ZjJkN2Q3OGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDIzMDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOTQ1ODBiMmZjZWRjMzQzMjM2Y2ZkMzJkNDM2ZmNjMDlmMjJmYTkyMzhhMGUyYjE5OGZmMzRjZTUxM2Y2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uNYgDNrGbB_0k8gIjRfKjasBrn6s9z9bHqQg49fqlqQ)
> 
> I am using VMware Workstation, which has 4 gigabytes of RAM and two cores. Provide a full thingsboard log so I can analyze the issue and find a proper solution. You can locate the log file by the following path: `/var/log/thingsboard` I need the file named `thingsboard.log`; please send the log exactly after the thingsboard "gets killed".

It is a stupid  story.
It seems that  thingsboard runs twice.  First is system run it automatically when ubuntu starts. Second is that I run it manually.
Thanks very much for your reply.
