### ISSUE TITLE
Accessing Device Profile Image by Widget

### ISSUE THREAD

**Issue by Jinboii** [thingsboard/thingsboard#12328]
Hello, was wondering if there is a way to include a device profile image in my dashboard? For example, device profile A has a profile image. I have device 1 which is assigned to device profile A, and when creating a dashboard for device 1, i would like to display device profile A image as well, and was wondering if I am able to do this by custom widget, or if there is any other better alternatives.

Thank you.

**Comment by devaskim** [comment]
Guess there is no ready to use solution, so only custom actions/widges. You need inject `assetProfileService` from [service-ma](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/services.map.ts)p to your widget. Then request profile details by `assetProfileService.getAssetProfile(....)` (details [here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/asset-profile.service.ts#L41C10-L41C25))

**Comment by Jinboii** [comment]
hello thank you for your response, I am still a bit confused can I check if you meant something like this:

    var $injector = self.ctx.$scope.$injector;
    var assetProfile = $injector.get(self.ctx.servicesMap.get('assetProfileService'));
    
    console.log("asset profile service",assetProfile);
    
    var assetTest = assetProfile.getAssetProfile("<device profile id>");
    console.log(assetTest);

and i got this in my console:

![Screenshot 2024-12-26 100257](https://github.com/user-attachments/assets/10d59fbb-e4be-40dc-a0ad-a820ef16bc4b)


> Guess there is no ready to use solution, so only custom actions/widges. You need inject `assetProfileService` from [service-ma](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/services.map.ts)p to your widget. Then request profile details by `assetProfileService.getAssetProfile(....)` (details [here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/asset-profile.service.ts#L41C10-L41C25)). In response you will find image data

**Comment by devaskim** [comment]
@Jinboii Each method of this service or any other returs RxJS's `Observable` object, so to get actual result you need:
```
assetProfile.getAssetProfile("<device profile id>").subscribe(
okResult => {},
errorResult => {}
);
```

**Comment by Jinboii** [comment]
Ah i see thank you. One last question, should the image link be {image: "tb-image;/api/images/tenant/health.jpg"}, how do you reference this in html/javascript of custom widget to display it?


> @Jinboii Each method of this service or any other returs RxJS's `Observable` object, so to get actual result you need:
> 
> ```
> assetProfile.getAssetProfile("<device profile id>").subscribe(
> okResultAkaDeviceProfile => {},
> errorResult => {}
> );
> ```
> 
> or at least
> 
> ```
> assetProfile.getAssetProfile("<device profile id>").subscribe(
> okResultAkaDeviceProfile => {}
> );
> ```

**Comment by devaskim** [comment]
Don't know
Look at html element in asset profile's details page in TB UI (via browser's dev tools)
