### ISSUE TITLE
How to Use a Single Token Across All Widgets in a Dashboard?

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12334]
Hi,

In my ThingsBoard setup, I have created multiple custom widgets. For each widget, I currently fetch a new token separately before retrieving the required values.

I want to optimize this process by fetching the token only once when the dashboard is loaded or refreshed and then reusing the same token across all widgets.

Is there a recommended approach to implement this? Can I store the token in a shared resource like a dashboard state or a global variable that all widgets can access?

Any guidance or examples would be greatly appreciated!

Thank you in advance.

**Comment by devdoob** [comment]
Why do you need a token in widgets? What's your use case of generating a token?

**Comment by Vaibhav0216** [comment]
I want to fetch telemetry data. So i am using the swagger api and my custom widgets.
so to fetch data i need to use auth token. But auth token refresh every day I think. so I need to regenerate it.

**Comment by devaskim** [comment]
@Vaibhav0216 Once you log in, access token is saved in browser's [localStorage](https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage), so to get it. just call `localStorage.getItem('jwt_token')` (see implementation details in [authService](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/auth/auth.service.ts#L96))

But there is no need to directly call TB's REST API. There are various ready to use services which put access token to each request automatically. For your case just call `self.ctx.attributeService.getEntityTimeseries(...)` (list of arguments is [here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts#L137))

**Comment by devdoob** [comment]
If you are using rest endpoints which are exposed in TB `serviceMap` then try using `http `service and make sure the url starts from `/api/whatever`

```
self.ctx.http.get('/api/userGroup/groupPermissions/info")
self.ctx.http.post('/api/userGroup/groupPermissions/info")
self.ctx.http.delete('/api/userGroup/groupPermissions/info")
```

This http service will auomically use currenlty logged-in user token.... no need to send any token via headers

**Comment by Vaibhav0216** [comment]
Thanks @devaskim.

self.ctx.attributeService.getEntityTimeseries(...) this worked.
