### ISSUE TITLE
the status of EXTENSIONS of Tb-gateway is no sync,how can I fix it ?

### ISSUE THREAD

**Issue by juanWZH** [thingsboard/thingsboard#1235]
the status of EXTENSIONS of Tb-gateway is no sync,how can I fix it ?

**Comment by sebsoft** [comment]
For me this worked:

-Export extentions to file
-Delete extentions
-Restart gateway
- Import extentions from file

**Comment by juanWZH** [comment]
> For me this worked:
> 
> -Export extentions to file
> -Delete extentions
> -Restart gateway
> -Import extentions from file

I connect to the external MQTT broker with the mqtt broker file configuration and do not make use of the GUI configuration. Maybe this way cannot do it.

**Comment by syabru** [comment]
In my case Thingsboard is running behind a nginx proxy and I fixed this by adding the following to the nginx configuration:

```
        location / {

                proxy_http_version 1.1;

                [...]

                # WebSocket support (nginx 1.4)
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_pass   http://localhost:9090;
        }
```

See also #900
