### ISSUE TITLE
Simple card label position can only be "Top"

### ISSUE THREAD

**Issue by tumalow-will** [thingsboard/thingsboard#124]
Selecting "Left" for the label position breaks the simple card widget on release 1.2.2.  Red warning text will appear on the font that says "Widget Error: Reference: height is not defined"

To recreate:
   - Go into edit mode on any dashboard that has a Simple Card.
   - Edit the simple card
   - Advanced --> Label Position --> left

**Comment by ashvayka** [comment]
Thank you for reporting this. Any steps to fix this? We would appriciate the PR with the fix.

**Comment by tumalow-will** [comment]
Happy to look into it though javascript isnt my strongest language.

**Comment by ikulikov** [comment]
Fixed in release 1.3.0.
