### ISSUE TITLE
method get and error 406

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1241]
Hello
The widget that I've written works fine, but when I can not get the previous value I entered, I used the following command on the widget side:
self.onInit = function() {
                     document.getElementById("text_time").value = angular.toJson(response);

On the nodemcu side, I use the following command:
else if (methodName == "Settime"){
timefeed = json["params"].as<string>;
}else if  (methodName == "Gettime"){
clinet.publish(responseTopic.c_str(),timefeed.c_str());
}
The problem I found was a 406 error that related to the format of the param. I should send this format in the same way as my stringing is: 22:20
I made some changes and I could only send 22 to the widget and get it there
I changed the value to int and then into the string.

**Comment by m0o0** [comment]
@vparomskiy PLEASE HELP ME

**Comment by vparomskiy** [comment]
Am I right that you send RPC command to the device from the UI (widget), your device receives command and generates a response?
Where did you get 406 error? Is it on widget while waiting for the response from the device? 
Did you try to enable debug mode in Rule Chains to find how the response from the device is handled?
Are there any errors in the thingsboard log file?

**Comment by m0o0** [comment]
Yes, the answer is from the widget, but apparently depends on the message format.
This error is displayed on the widget when the answer from the machine's side is fail (rejection). Code:
function fail(rejection) {
                self.ctx.$scope.rpcCommandResponse = "Failed to send command to the device:<br/>"
                self.ctx.$scope.rpcCommandResponse += "Status: " + rejection.status + "<br/>";
                self.ctx.$scope.rpcCommandResponse += "Status text: '" + rejection.statusText + "'";
What I find out is that the value sent to the device when the set method is sent from the widget's side if it is delivered as follows:  time= json["params"].as<string>;         If this is the same way when sent to the Gat method, use the command:     clinet.publish(responseTopic.c_str(),timefeed.c_str());    We encounter a 406 error on the widget But if this value(time) is converted to int then strings, sending is successful, but the problem is that this value is 22: 23, in which case only 22 will be sent and the second part will be deleted.

**Comment by vparomskiy** [comment]
Sorry, but I still didn't get an idea.
1. Does your device receive RPC command from the widget?
2. Please provide an example of the response (not code but an actual example)
3. Are there any errors in the Thingsboard log file (for time window when the request was submitted)

**Comment by m0o0** [comment]
Thank you, I solved the problem. I sent it as a byte to the widget.

**Comment by WillianMFerreira** [comment]
> Thank you, I solved the problem. I sent it as a byte to the widget.

**Comment by WillianMFerreira** [comment]
> Thank you, I solved the problem. I sent it as a byte to the widget.

m0o0, can you send me this part of your code? I am with your same problem. Thanks!
