### ISSUE TITLE
Configure max http telemetry upload size

### ISSUE THREAD

**Issue by ChristianLutz** [thingsboard/thingsboard#1244]
Hello,

currently we are only able to upload around 4k via the http telemetry endpoint. Is there any setting to change it? We haven't found it so far. Or is this a limit within the thingsboard server?

[This](https://stackoverflow.com/questions/28286905/spring-rest-api-maximum-size-http-post) is what I found for spring boot. Is this setting also available in thingsboard. If so may I change it?

kind regards
Christian

**Comment by vparomskiy** [comment]
Telemetry is uploaded using POST methods so you need to change default max post size for the tomcat. We are using spring boot version 1.4.3, so try to add this property in thingsboard.yml
server.max-http-post-size=0 # Maximum size in bytes of the HTTP post content.

**Comment by vparomskiy** [comment]
The only thing that I can recommend is to enable debug/trace logs in logback.xml for spring and tomcat and try to find what is going on.

**Comment by vparomskiy** [comment]
@ChristianLutz did you find solution/workaround for this issue?

**Comment by ChristianLutz** [comment]
No we haven't, we had to change the client so for each request we upload max 4KB, for 200MB this takes some time. But we run out of ideas for this problem.

**Comment by Ultrazombie** [comment]
closed as not active
