### ISSUE TITLE
want to have widget to display a image from a link

### ISSUE THREAD

**Issue by chenmingzhang** [thingsboard/thingsboard#1245]
i have tried to make thingsboard working in one day, the installation is quite intuitive. thanks.

 my question is as the title, the system i am hooking up with comes with a camera that sends photo to web with a fixed link. how can i have a widget that shows photos in web? thanks.

**Comment by Ultrazombie** [comment]
Hello,
Sorry for the very late responce:

Please use the static widget and iframe.
e.g.

```
<div class='card'>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/2yWhvBkEyaY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
</div>
```
