### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by steadylife** [thingsboard/thingsboard#1248]
I have no changes to the code and run the main method of org.thingsboard.server.ThingsboardServerApplication class from my IDE "idea",I am getting the error :
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Nov 14 15:57:00 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

but if i run  "java -jar application/target/thingsboard-2.2.0-SNAPSHOT-boot.jar"  from command line, it is ok.

**Comment by vparomskiy** [comment]
1. Did you run 'mvn clean install -DskipTests' command?
2. Did you run ThingsboardInstallApplication (it is required for schema generation when it is not exist yet)
3. Provide console output for ThingsboardServerApplication

**Comment by steadylife** [comment]
> 1. Did you run 'mvn clean install -DskipTests' command?
> 2. Did you run ThingsboardInstallApplication (it is required for schema generation when it is not exist yet)
> 3. Provide console output for ThingsboardServerApplication


I run "mvn clean install -DskipTests" successfully,but when I run ThingsboardInstallApplication, i got the error :
2018-11-19 09:17:53,358 [main] INFO  o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Installation...
2018-11-19 09:17:53,358 [main] INFO  o.t.s.i.ThingsboardInstallService - Installing DataBase schema for entities...
2018-11-19 09:17:53,358 [main] INFO  o.t.s.s.i.SqlAbstractDatabaseSchemaService - Installing SQL DataBase schema part: schema-entities.sql
2018-11-19 09:17:53,374 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
java.nio.file.NoSuchFileException: C:\Download\Documents\thingsboard\application\src\main\data\sql\schema-entities.sql
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:59)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:138)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
2018-11-19 09:17:53,374 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@558bdf1f: startup date [Mon Nov 19 09:17:32 CST 2018]; root of context hierarchy
2018-11-19 09:17:53,390 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2018-11-19 09:17:53,405 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2018-11-19 09:17:53,483 [main] ERROR o.t.s.ThingsboardInstallApplication - Unexpected error during ThingsBoard installation!

**Comment by steadylife** [comment]
I tried to run "ThingsboardServerApplication" and acess the link "localhost:8080" .still got :
”Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Nov 19 15:46:31 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available”

the attachment is console output of IDEA
[output.txt](https://github.com/thingsboard/thingsboard/files/2594235/output.txt)

**Comment by steadylife** [comment]
> > 1. Did you run 'mvn clean install -DskipTests' command?
> > 2. Did you run ThingsboardInstallApplication (it is required for schema generation when it is not exist yet)
> > 3. Provide console output for ThingsboardServerApplication
> 
> I run "mvn clean install -DskipTests" successfully,but when I run ThingsboardInstallApplication, i got the error :
> 2018-11-19 09:17:53,358 [main] INFO o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Installation...
> 2018-11-19 09:17:53,358 [main] INFO o.t.s.i.ThingsboardInstallService - Installing DataBase schema for entities...
> 2018-11-19 09:17:53,358 [main] INFO o.t.s.s.i.SqlAbstractDatabaseSchemaService - Installing SQL DataBase schema part: schema-entities.sql
> 2018-11-19 09:17:53,374 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
> java.nio.file.NoSuchFileException: C:\Download\Documents\thingsboard\application\src\main\data\sql\schema-entities.sql
> at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
> at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
> at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
> at java.nio.file.Files.newByteChannel(Files.java:361)
> at java.nio.file.Files.newByteChannel(Files.java:407)
> at java.nio.file.Files.readAllBytes(Files.java:3152)
> at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:59)
> at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:138)
> at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
> 2018-11-19 09:17:53,374 [main] INFO o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@558bdf1f: startup date [Mon Nov 19 09:17:32 CST 2018]; root of context hierarchy
> 2018-11-19 09:17:53,390 [main] INFO o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
> 2018-11-19 09:17:53,405 [main] INFO o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
> 2018-11-19 09:17:53,483 [main] ERROR o.t.s.ThingsboardInstallApplication - Unexpected error during ThingsBoard installation!

I found the cause is there's no "sql" folder in "C:\Download\Documents\thingsboard\application\src\main\data",only "json" and "upgrade" folder.

**Comment by steadylife** [comment]
> @steadylife
> For running ThingsboardInstallApplication you will need also to add additional VM options, because Thingsbaord need to know where to take DB schema files. Here is an example:
> 
> `-Dinstall.data_dir=YOUR_TB_INSTALL_DIR/application/target/data -Dspring.jpa.hibernate.ddl-auto=none -Dinstall.load_demo=true -Dinstall.upgrade=false`
> 
> You can add this options in the top right corner inside IDEA 'Edit Configurations ...' (Run/Debug Configuration -> Application -> ThingsboardServerApplication)

I run "%TB_WORK_DIR%\application\target\windows\install_dev_db.bat" successfully ,Is it the same result as running ThingsboardInstallApplication?

**Comment by steadylife** [comment]
Now I run ThingsboardInstallApplication successfully,  but after run ThingsboardServerApplication ,still can not access "localhost:8080".
[output.Log](https://github.com/thingsboard/thingsboard/files/2594718/output.Log)

**Comment by vparomskiy** [comment]
In most cases, the reason for this error is that UI files were changed and contains errors.
You can run UI in the hot-redeploy mode, and will be able to see UI errors (don;t forget to use port 3000 - http://localhost:3000)

https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#running-ui-container-in-hot-redeploy-mode

**Comment by meittemarc** [comment]
Rebuild node-sass and run UI. 
`npm rebuild node-sass`
`npm run build`
`npm run start`

**Comment by steadylife** [comment]
> Rebuild node-sass and run UI.
> `npm rebuild node-sass`
> `npm run build`
> `npm run start`

when I run "npm run build" ,got the error:
ERROR in ./src/app/widget/lib/flot-widget.js

C:\Download\Documents\thingsboard\ui\src\app\widget\lib\flot-widget.js
  26:8  error  Unable to resolve path to module 'flot.curvedlines/curvedLines'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)


ERROR in ./src/app/widget/lib/flot-widget.js
Module not found: Error: Cannot resolve module 'flot.curvedlines/curvedLines' in C:\Download\Documents\thingsboard\ui\src\app\widget\lib
 @ ./src/app/widget/lib/flot-widget.js 50:0-39

**Comment by gmatheu** [comment]
It seems that **flot.curvedlines** is not properly installed when executing `npm install` due to naming conflict.

https://github.com/thingsboard/thingsboard/pull/1271 solves that issue.

**Comment by steadylife** [comment]
> It seems that **flot.curvedlines** is not properly installed when executing `npm install` due to naming conflict.
> 
> #1271 solves that issue.

thank you!  I changed Package name to "flot.curvedlines " and reinstall it , It is Ok .
