### ISSUE TITLE
Unconfigured table Customer_by_tenant_and_title

### ISSUE THREAD

**Issue by huily6** [thingsboard/thingsboard#125]
thingsboard1.2.2  Add users or public devices after upgrading CORS  prompts: Unconfigured table Customer_by_tenant_and_title

**Comment by ashvayka** [comment]
Hi!

Public devices are 1.2.3 feature and there will be an official script once this version is released. Meanwhile, you can either completely recreate the database, or write your own upgrade script based on the changes cql files.

**Comment by huily6** [comment]
I see,Thanks !

**Comment by ashvayka** [comment]
Please use official [update instructions](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-123)

**Comment by huily6** [comment]
I see ,thanks!
