### ISSUE TITLE
widget, chart show old data ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1250]
hey, 
is there no way to show older data on the widget that are already created because i tried to get older data but i can't, and is there an easy way to fetch all the data from the start of time ?

**Comment by vparomskiy** [comment]
You can select any time window for the dashboard/widget
So what is the problem?

**Comment by souhaiebtar** [comment]
is there any widget,that use it in the prebuilt widget ? or any example of how to use it ?

**Comment by vparomskiy** [comment]
Sure, 'Charts' bundle -> any timeseries widget
in the top right corner you can select required time window

**Comment by souhaiebtar** [comment]
i want to able the client or the end user to view older data but time window is only  available on widget setup,

**Comment by souhaiebtar** [comment]
thanks
