### ISSUE TITLE
What does the "entityViews" module mean?How does it compare to the " asset" "module?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#1252]
![2018-11-15_175534](https://user-images.githubusercontent.com/30205233/48544961-c5584100-e8ff-11e8-86fb-99999a7855dd.png)

**Comment by vparomskiy** [comment]
We are working on documentation and it will be available soon. 
Short description -> Entity View is a View for Device/Asset that has access to original attributes/telemetry BUT only in configured time Interval. 
**For example**, you have Device and want to give access to telemetry of that device for some Customer. But Customer should only have access to telemetry with name 'temperature' and 'humidity', but not have access to the 'pressure'. Also, you can grant access to the date for the last month/year, etc.
