### ISSUE TITLE
get the status of a checkbox in widget

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1254]
i created a custom widget using chartjs,
the data is gotten correctly and it shows properly,

than in the html part i added
`<input id="checkBool" type="checkbox" name="vehicle" value="Bike" checked>`
now the entire html become
```
<input id="checkBool" type="checkbox" name="vehicle" value="Bike" checked>
<canvas id="chartJSContainer" width="600" height="400"></canvas>
```

i tried to get the status of the checkbox  using 
```
self.onInit = function() {
     isChecked1 = $('#checkBool', self.ctx.$container).attr('checked')?true:false;
    console.log('checkbox1 is ');
    console.log(isChecked1);
}
```

but it always get the initial stat, for example for above html, it always return true,

is there a solution to get the status properly ?

**Comment by souhaiebtar** [comment]
@nabil-rejeb do you now any solution for this ?

**Comment by nabil-rejeb** [comment]
Try to use angular checkbox and add a call back on value change

**Comment by souhaiebtar** [comment]
i tested with angular input and it work properly,
i added to html
```
<input required name="inputField" ng-model="inputField"/>
```
and in the javascript side i added:
```
self.onDataUpdated = function() {
    //....
    var inputField = self.ctx.$scope.inputField;
    console.log('inputField test is ' + inputField);
    //....
}
```

**Comment by souhaiebtar** [comment]
i added this to html

```
Realtime <input type="checkbox" name="realtime" ng-model="realtime" />
```

than in the javascript side

```
self.onDataUpdated = function() {
     var realtime = self.ctx.$scope.realtime;

     if ( undefined !== realtime ) {
          if(realtime) { 
          ...
          ...
          }
      }
}
```
