### ISSUE TITLE
Data collection was not completely deleted when the device was deleted.

### ISSUE THREAD

**Issue by felix-ma** [thingsboard/thingsboard#1256]
The device table was deleted only when the device was deleted, and the data in the associated attribute_kv, ts_kv, and ts_kv_latest tables are still available.

**Comment by vparomskiy** [comment]
You are right, attributes and telemetry are not deleted from the DB when the device is removed. The reason is that telemetry removing may be a heavy task. Device can have millions/billions of telemetry values and delete query can lead to significant performance degradation.

**Comment by felix-ma** [comment]
> You are right, attributes and telemetry are not deleted from the DB when the device is removed. The reason is that telemetry removing may be a heavy task. Device can have millions/billions of telemetry values and delete query can lead to significant performance degradation.

But when the device is deleted, the data will be stored in the database, and no new device will be generated.

**Comment by felix-ma** [comment]
And when the equipment is deleted again, the device type can not be set up. It can only be the default. It looks like a bug.

**Comment by felix-ma** [comment]
This phenomenon is that when I use it with the gateway, the value passed through the gateway can still be uploaded without deleting the device, and the device will not be generated.
When I look at the source code, I find that the device in the gateway is still in the connection state after being deleted in TB, and the telemetry data sent again will not be connected again.
The TB generation device is notified only when the connection method is called.
![image](https://user-images.githubusercontent.com/30289895/48606460-9eab1080-e9ba-11e8-97b8-7ca6da0a7e84.png)

This picture is the code in GW.
Device is a Set.
I would like to ask if the message is again passed to the gateway to delete the device after the device is deleted, or is it changed? Every time the information is received, the link will be called.
