### ISSUE TITLE
JavaScript Executor Microservice  BUILD FAILURE

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#1258]
C:\Java\jdk1.8.0_171\bin\java.exe -Dmaven.home=D:\maven\apache-maven-3.2.5-bin -Dclassworlds.conf=D:\maven\apache-maven-3.2.5-bin\bin\m2.conf "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.1\lib\idea_rt.jar=51917:D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.1\bin" -Dfile.encoding=UTF-8 -classpath D:\maven\apache-maven-3.2.5-bin\boot\plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.2.1 -s D:\maven\settings.xml -Dmaven.repo.local=D:\APPLICATION\JavaRepository\repository -DskipTests=true install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 6.1
[INFO] os.detected.version.major: 6
[INFO] os.detected.version.minor: 1
[INFO] os.detected.classifier: windows-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ThingsBoard JavaScript Executor Microservice 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ js-executor ---
[INFO] Configured Artifact: com.google.protobuf:protoc:windows-x86_64:3.0.2:exe
[INFO] Copying protoc-3.0.2-windows-x86_64.exe to F:\gitWorkSpace\thingsboard\msa\js-executor\target\protoc-3.0.2-windows-x86_64.exe
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ js-executor ---
[INFO] Node v8.11.3 is already installed.
[INFO] NPM 5.6.0 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ js-executor ---
[INFO] Running 'npm install' in F:\gitWorkSpace\thingsboard\msa\js-executor
[INFO] 
[INFO] > thingsboard-js-executor@2.2.0 install F:\gitWorkSpace\thingsboard\msa\js-executor
[INFO] > npm run build-proto && pkg -t node8-linux-x64,node8-win-x64 --out-path ./target . && node install.js
[INFO] 
[INFO] 
[INFO] > thingsboard-js-executor@2.2.0 build-proto F:\gitWorkSpace\thingsboard\msa\js-executor
[INFO] > pbjs -t static-module -w commonjs -o ./api/jsinvoke.proto.js ../../application/src/main/proto/jsinvoke.proto
[INFO] 
[ERROR] fs.js:904
[ERROR]   return binding.readdir(pathModule._makeLong(path), options.encoding);
[ERROR]                  ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, scandir 'F:\gitWorkSpace\thingsboard\msa\js-executor\node_modules\protobufjs\cli\targets'
[ERROR]     at Object.fs.readdirSync (fs.js:904:18)
[ERROR]     at Object.requireAll (F:\gitWorkSpace\thingsboard\msa\js-executor\node_modules\protobufjs\cli\util.js:35:20)
[ERROR]     at Object.<anonymous> (F:\gitWorkSpace\thingsboard\msa\js-executor\node_modules\protobufjs\cli\pbjs.js:14:21)
[ERROR]     at Module._compile (module.js:652:30)
[ERROR]     at Object.Module._extensions..js (module.js:663:10)
[ERROR]     at Module.load (module.js:565:32)
[ERROR]     at tryModuleLoad (module.js:505:12)
[ERROR]     at Function.Module._load (module.js:497:3)
[ERROR]     at Module.require (module.js:596:17)
[ERROR]     at require (internal/module.js:11:18)
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! thingsboard-js-executor@2.2.0 build-proto: `pbjs -t static-module -w commonjs -o ./api/jsinvoke.proto.js ../../application/src/main/proto/jsinvoke.proto`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the thingsboard-js-executor@2.2.0 build-proto script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-19T01_52_53_330Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! thingsboard-js-executor@2.2.0 install: `npm run build-proto && pkg -t node8-linux-x64,node8-win-x64 --out-path ./target . && node install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the thingsboard-js-executor@2.2.0 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-19T01_52_53_390Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.230 s
[INFO] Finished at: 2018-11-19T09:52:53+08:00
[INFO] Final Memory: 18M/307M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "development" could not be activated because it does not exist.
[WARNING] The requested profile "public-snapshots" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project js-executor: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by humeibiao** [comment]
I have the same error

**Comment by marcozanghi** [comment]
me to!

**Comment by frogconn** [comment]
I have the same error and build on Ubuntu 18.04.1

**Comment by mysty-mystic** [comment]
did anybody fix the issue,i have the same problem

**Comment by vparomskiy** [comment]
Remove `node-modules` directory from `msa/js-executor` and retry build process.
In some cases npm does not correctly cache modules so they need to be reloaded.

**Comment by alexsmartens** [comment]
I'm having a similar problem:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task
```
Any solution?

**Comment by zacky131** [comment]
Hi..i this is due to versioning issue of node. here is what I've done: ( I'm using thingsboard 3.2)
on your server update to:
node V15.5.0
yarn V1.22.5
npm V7.3.0
at pom.xml  replace the version so it match with your server: 
addition, also change frontend-maven-plugin to version 1.11.0
Lastly,
change package.json inside js-executor and web-ui folder to
"scripts": {
    "install": "pkg -t **node14-linux-x64,node14-win-x64** --out-path ./target . && node install.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "WEB_FOLDER=./target/web nodemon server.js",
    "start-prod": "NODE_ENV=production nodemon server.js"
  },

Thats it, all i had successfully build thingsboard from source on Ubuntu 20.04 server after 3 days in a row try to find out...
hope its help :)

**Comment by huahouye** [comment]
@zacky131 yes, this solution helps me. and I just change `thingsboard/msa/web-ui/package.json` and `thingsboard/msa/js-executor/package.json` from `node12-linux-x64,node12-win-x64` to `node14-linux-x64,node14-win-x64` . Keep the default values for all other fields and options.

```
thingsboard 3.2.1
CentOS Linux release 7.6.1810 (Core)
```
