### ISSUE TITLE
 Will TB use Time Series Database to store IOT data in the future?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#1260]
hi：
Time Series Database has an advantage in the IOT field. Why has TB not adopted it?Or have I found no similar components?

**Comment by vparomskiy** [comment]
Cassandra is an excellent Database for Time-Series data.
And Cassandra is a recommended DB for the Thingsboard.

**Comment by BIT-masterpy** [comment]
Without a doubt, Cassandra is an excellent NOSQL database.But it doesn't seem like a professional Time Series Database.I didn't find Cassandra on the ranks .
https://db-engines.com/en/ranking/time%20series%20dbms

**Comment by mfalkvidd** [comment]
Could you describe the use case you're unable to solve with the currently supported databases?

**Comment by spree1010** [comment]
Hi, I am also interested in this topic.  I read this article and it mentioned from the perspective of query performance and data storage compression,  Cassandra is not as good as professional time series database such as in InfluxDB.  https://www.influxdata.com/blog/influxdb-vs-cassandra-time-series/

@vparomskiy  ,  @mfalkvidd     Would you please give some comments? 

Thank you!
Kun

**Comment by mfalkvidd** [comment]
@spree1010 if a marketing department decided to market Cassandra, they would easily come up with a benchmark that showed Cassandra outperforming InfluxDB, just like the marketing department at Influxdata has done (in reverse) in the blog post you linked.

I'd prefer to look at real-world problems. Could you describe what problem you are experiencing with the currently supported databases? Would that problem be solved by switching to another database backend?

**Comment by nilsonfh** [comment]
Even if the topic is closed, I wanna comment that Thingsboard will be robust and flexible using a professional time series database.  
Thingsboard is excellent managing IoT infrastructure but is not good dealing with big time series as influxdb. By trying to upgrade our TB, we have lost all our data of around one year. Our solution now is replicating all time series to influxdb intercepting and transforming MQTT messages to TB.
