### ISSUE TITLE
cannot build the correct bin file of tb-web-ui for msa/web-ui

### ISSUE THREAD

**Issue by iamaugustin** [thingsboard/thingsboard#1262]
I try to compile the thingsboard and want to deploy them based on msa style. However, I find the deliverables of tb-web-ui.deb doesn't include the correct bin file of tb-web-ui. I see the pom.xml of msa/web-ui, and there is no specific description for this bin generation in msa/web-ui. Is there any suggestion for this? or I just miss anything to get it right.

**Comment by vimalgupta** [comment]
I am also getting the same, i tried 2.3.1 as well 2.4.1 and master branch too. there is not bin directory in the deb file generated. also the same is happening for js-executor.

**Comment by NikhilBijagarni** [comment]
Even i am getting this same error. When i am building on Windows platfrom i can see bin folder. When i install this tb-web-ui.deb on Ubuntu machine i get segmentation error will starting it. 
So when i tried to build on Linux Platfrom i get an error for generating .exe i tried to comment the assembly plugin then the build was successful but i don't see bin folder getting generated under msa/web-ui/target/platform/linux/
Does anyone has the solution for this ?

**Comment by adf0001** [comment]
Try manually execute 
```
pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js
```
or 
```
node_modules/.bin/pkg -t node10-linux-x64,node10-win-x64 --out-path ./target .

node install.js
```
then mvn install.

**Comment by Frozka** [comment]
I was having the same issue, even though it was building fine on local setup, running CI in gitlab private runner was causing this npm "WARNING".

```
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ web-ui ---
 [INFO] Running 'npm install' in /builds/test/thingsboard/msa/web-ui
 [INFO] 
 [INFO] > nodemon@1.18.7 postinstall /builds/test/thingsboard/msa/web-ui/node_modules/nodemon
 [INFO] > node bin/postinstall || exit 0
 [INFO] 
 [WARNING] npm WARN lifecycle thingsboard-web-ui@2.4.3~install: cannot run in wd thingsboard-web-ui@2.4.3 pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js (wd=/builds/test/thingsboard/msa/web-ui)
```

It happens because npm was ran with root privileges: [Answer](https://stackoverflow.com/a/19132229)
If you google `cannot run in wd` there is plenty of solutions how to solve/bandage the issue

What I did is added `--unsafe-perm` to install step.

msa/web-ui/pom.xml (will work with other project that use same plugin)
```
. . .
<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.0</version>
                <configuration>
                    <installDirectory>target</installDirectory>
                    <workingDirectory>${basedir}</workingDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v10.16.0</nodeVersion>
                            <npmVersion>6.4.1</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install --unsafe-perm</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
. . .
```

**Comment by ban2derlog** [comment]
please, use later versions of ThingsBoard.
we always recommend to use latest version.
