### ISSUE TITLE
Discrepancy in latest telemetry value

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#1264]
I got a strange situation with some telemetry data. TB 2.1.3.
For a device the latest telemetry value of "pwr" is shown as "false" at 09:55:10:
![image](https://user-images.githubusercontent.com/11454768/48774137-a70c8f80-ecc9-11e8-9215-cdac8a5f57cf.png)

Unfortunately, this is not the "latest" value in time. When I show the same value by selecting it and use the "SHOW ON WIDGET" button, then I get the following:
![image](https://user-images.githubusercontent.com/11454768/48774311-21d5aa80-ecca-11e8-92a9-84062a595356.png)

Here, the latest value is "true" updated 09:56:17.
I got the same inconsistency in my dashboards. When using the "pwr" telemetry as "latest telemetry" in widgets, I get the value from 09:55:10, but using it e.g. in state diagrams or time series tables, I get the correct latest value (in time) from 09:56:17.
Is that the intended behaviour?

The reason might be linked to the fact, that I send this telemetry data with MQTT, QoS=1, and the timestamp for that message is generated and sent by the device (timestamp not generated by TB when putting the value into the DB).
So it might happen that (e.g. after connection interruption) the MQTT message with the earlier timestamp is sent after the MQTT message with the later timestamp (just my assumption). In fact, in that case, the value with the earlier timestamp is the latest one put into the database.

So what is meant with "latest telemetry"?
Is it the latest value pushed into the database or the one with the most recent timestamp?

If it is the first option, in widgets, is there an easy way to get access the one with the latest timestamp without using the REST API and get the values manually?

**Comment by lswanderleygit** [comment]
I'm with going through the same situation, the widgets with the wrong values since the last telemetry is not considered the timestamp did you get an alternative to this problem?

Thankful !

**Comment by icremer** [comment]
We're on **tb-pe:2.4.1PE** and we have the same discrepancy behavior with our data parsed by a data converter into telemetry values:
![image](https://user-images.githubusercontent.com/42639933/77170103-d9dfb700-6aba-11ea-99e3-40d70d3c3ac8.png)
Only the widgets showing the latest values seem to have the problem.
@ashvayka, @ikulikov any idea ?

**Comment by jnmanchado** [comment]
I have the same discrepancy. I exported data via dashboard and REST API and saw the same behaviour.

**Comment by ChristineChetty** [comment]
I have a similar issue. I suspect it has something to with Standard Queue type being used with AWS SQS

**Comment by Ultrazombie** [comment]
closed due to inactive
