### ISSUE TITLE
cassandra data migration，timeseries chart no history data

### ISSUE THREAD

**Issue by zouhr** [thingsboard/thingsboard#1265]
computer tb1 : thingsboard 2.1.0 , cassandra 3.0.9
computer tb2 : thingsboard 2.1.3  , cassandra 3.11.9
i use cassandra copy comand for data migration,  all tables in keyspace thingsboard 2.1.0 are export, and import to thingsboard 2.1.3  other cassandra.     
now  i can login in thingsboard 2.1.3,  custom,device,asset,widgets, all things are showing normal。but when i open dashboard ，alarm widget is ok，timeseries is show nothing。i can find the telemetry in cassandra database，ts_kv_cf tables is ok.      why dashboard not show history data.

command: from thingsboard 2.1.0
copy thingsboard.ts_kv_latest_cf to '/root/tmp/ts_kv_latest_cf.scv';
copy thingsboard.asset to '/root/tmp/asset.scv';
copy thingsboard.admin_settings to '/root/tmp/admin_settings.scv';
------
import to thingsboard 2.1.3
truncate thingsboard.ts_kv_latest_cf;
copy thingsboard.ts_kv_latest_cf from '/root/tmp/ts_kv_latest_cf.scv';
truncate thingsboard.asset;
copy thingsboard.asset from '/root/tmp/asset.scv';
--------------

**Comment by AbCthings** [comment]
In order to avoid db corruption I suggest using higher level features of ThingsBoard (such as RESTful APIs) instead of directly structuring the db using SQL or CQL.
You can find an example here: https://github.com/AbCthings/thingsboard-data-migration
