### ISSUE TITLE
get device telemetry data

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#1269]
Hi! 
I'm trying to fetch device's telemetry data inside rule chain javascript. However, examples show that i need to use x-auth. That key is not valid for long periods of time, so must i fetch auth key every single time i try to get telemetry data with my code?

**Comment by quirosaur** [comment]
Second question on subject at hand: why i cannot use GET request? i tried it with postman and thingsboard's swagger.io

**Comment by vparomskiy** [comment]
there are **Enrichment** rule nodes that can load telemetry data. Could you explain in more details what telemetry you need and in what cases? 
In most cases, it is not a good idea to load telemetry via REST API inside javascript Rule Node. You should use Enrichment nodes for loading required data and saving them into metadata.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/

**Comment by quirosaur** [comment]
i checked the enrichment nodes, and i didn't find "originator telemetry", which is mentioned in tutorial.
and looking at examples, those mainly add one telemetry data and attribute to message.
I need to fetch all latest telemetry values of separate device, and send them as json to mqtt topic

**Comment by vparomskiy** [comment]
1. Originator Telemetry node was added in the latest Thingsboard version. You need to upgrade to the latest version. What version are you using right now?
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-telemetry

You can also test this node on our ThingsBoard CE (https://demo.thingsboard.io) or ThingsBoard PE (https://cloud.thingsboard.io/) instances

2. You can change originator from the original device to the required device using **Change Originator** Transformation node. Relation query can be used. Note that relation between devices should be created.

**Comment by quirosaur** [comment]
i should have the newest version. i installed this couple months back. i have the new rule engine view and when logged in as a sysadmin, i don't see a prompt about updating

**Comment by vparomskiy** [comment]
it was released in TB 2.1.3
https://github.com/thingsboard/thingsboard/releases

**Comment by vparomskiy** [comment]
You will need first change originator of the message.
For example original messaged is published from Device AAA. And You want to load telemetry of Device BBB. You will need to change message originator (from device AAA) to Device BBB. **Change Originator** node can do this.

**Comment by quirosaur** [comment]
Hi @vparomskiy !

i updated thingsboard and tried the change originator- node.

however, the configuration of said node is bit unclear: 

in docs, it is said that the originator can be device, asset, tenant, customer, etc.
but in that node, there's only possible to select between tenant, customer, or something called related.

my guess is that using related, selecting direction "to" and type "contains" and selecting devices, would be the way, but i see nowhere a possibility to select certain device? (i.e. "Thermostat" or "Lamp")

```
The originator can be changed to:

Originator’s Customer
Originator’s Tenant
Related Entity that is identified by Relations Query
In ‘Relations query’ configuration Administrator can select required Direction and relation depth level. Also set of Relation filters can be configured with required Relation type and Entity Types.

```

**Comment by Navid007** [comment]
This comments is very close to what I am doing, any support is appreciated:
I have a device with dynamic MQTT Attributes, It is a light with multiple color and density, e.g. red:34 or blue:54 or purple:33... I am sending data as MQTT, color as key and value as density.
However list of color may be increased, I am looking for a way to show all list of available colors on the dashboard dynamically.  Basically looking for something like this:

List A:
Light 1 
Light 2
Light 3
,,

If user click on Light 1 then
Show a list with all available colors

Then if select on any color show the history of density change for that color.

From the examples I see we can add dynamically devices and have a list with action to bring another dashboard for details of that device, however can we do that in attribute level and show attributes, keys dynamically ?
