### ISSUE TITLE
public dashboard js resources return http status 404

### ISSUE THREAD

**Issue by liaow** [thingsboard/thingsboard#1273]
tb version : 2.1.2 SNAPSHOT
I tried to access a public dashboard url, but it returned some exceptions. 
so what went wrong?
chrome 404:
![image](https://user-images.githubusercontent.com/3170158/48888102-89c3f680-ee6c-11e8-911f-dc196ffbeaba.png)
static resources in docker :
![image](https://user-images.githubusercontent.com/3170158/48888526-f8558400-ee6d-11e8-855d-05c2a2fe5583.png)

**Comment by vparomskiy** [comment]
If you are using microservice architecture, did you configure haproxy for forwarding requests to a correct microservice?

**Comment by liaow** [comment]
> If you are using microservice architecture, did you configure haproxy for forwarding requests to a correct microservice?

yes, haproxy has taken effect except for public dashboard

![image](https://user-images.githubusercontent.com/3170158/48989709-71065a00-f166-11e8-9cfc-863ff8fa4b20.png)
