### ISSUE TITLE
Entity View cannot display telemetry values

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#1275]
hi：

I use the Change originator node to copy the device data into the associated asset and Entity Views, the value displayed in the resulting asset, but Entity Views nothing
![image](https://user-images.githubusercontent.com/30205233/48894263-41f99b00-ee7d-11e8-9691-b2aacffedf18.png)

![image](https://user-images.githubusercontent.com/30205233/48894291-53db3e00-ee7d-11e8-876e-423aee8b8bb2.png)

![image](https://user-images.githubusercontent.com/30205233/48894338-7f5e2880-ee7d-11e8-92e6-785e850e479c.png)

![image](https://user-images.githubusercontent.com/30205233/48894383-9ac93380-ee7d-11e8-8743-cdf194e36b86.png)

What should I do to make it work?

**Comment by vparomskiy** [comment]
You should not manually copy telemetry from device to the Entity View. When Entity View created, you assign Device for this Entity View and telemetry from the device will be automatically copied to the Entity View (no Rule chain configuration required).

Do you see this behavior (Entity View shows Telemetry of assigned Device)?
If not, what Time Range did you configure for the Entity View?

**Comment by BIT-masterpy** [comment]
![image](https://user-images.githubusercontent.com/30205233/48896454-9c492a80-ee82-11e8-9ee5-17db10683179.png)

![image](https://user-images.githubusercontent.com/30205233/48896483-b1be5480-ee82-11e8-8095-c519de813e6b.png)
Yes, I assigned a device to Entity view when I created it.In addition, Entity view cannot display the telemetry data of the device without modifying Rule chains.

**Comment by volodymyr-babak** [comment]
this issue can be reproduced in the latest 3.3.3 version.
