### ISSUE TITLE
Some confusion about the design of the TB Rule engine

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#1278]
hi:
I feel that the rule chain of TB is very complex. All data enters TB from input node, and then various filters distribute the data to sub-chains. Why not configure a rule chain for each device? Wouldn't that be much simpler? What's the reason why TB uses rule chains centrally?

**Comment by vparomskiy** [comment]
1. Proposed architecture will not work for big installations (500K device is not a rare case for the ThingsBoard).
