### ISSUE TITLE
How to setup language for report server ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1280]
Hi, 
I am using TB  v2.1.3 PE. We can configure Japanese Character Set on our Dashboard. When we generate the report. Those Japanese Character Set beomes "unrecognised" Symbol.

Do anyone know how to solve this issue ?  How can I configure my report server to use the correct character set ?

Our TB v2.1.3 is running on AWS ubuntu Server. I already configure "LANG=ja_JP.UTF-8" on .profile.

**Comment by paulwang55** [comment]
Hi,
The follwoing message is about the process of **"tb-web-report"**.

 I find that it use "en-US" as lang parameter. If we use Chinese or Japanese in the Dashboard, those "Chinese" & "Japanese" information will not be displayed on the Report correctly.
  
**How can I change "--lang" to ja_JP ?**

thingsb+  1301  1274  0 04:23 ?        00:00:00 /usr/share/tb-web-report/chromium/chrome --type=renderer --no-sandbox --disable-background-timer-throttling --disable-breakpad --enable-automation --use-gl=swiftshader-webgl --disable-features=site-per-process --disable-gpu-compositing --service-pipe-token=13981085567223477512 **--lang=en-US** --headless --num-raster-threads=1 --service-request-channel-token=13981085567223477512 --renderer-client-id=2 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
ubuntu    2155  1466  0 04:30 pts/0    00:00:00 grep --color=auto tb



$ ps -ef | grep tb
thingsb+  1085     1  0 04:23 ?        00:00:00 /usr/share/tb-web-report/bin/tb-web-report
thingsb+  1262  1085  0 04:23 ?        00:00:00 /usr/share/tb-web-report/chromium/chrome --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_profile-acxOly --headless --disable-gpu --hide-scrollbars --mute-audio about:blank --no-sandbox
thingsb+  1274  1262  0 04:23 ?        00:00:00 /usr/share/tb-web-report/chromium/chrome --type=zygote --no-sandbox --headless --headless
thingsb+  1299  1262  0 04:23 ?        00:00:00 /usr/share/tb-web-report/chromium/chrome --type=gpu-process --disable-features=site-per-process --no-sandbox --disable-breakpad --headless --headless --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --headless --service-request-channel-token=10734280151343981224
thingsb+  1301  1274  0 04:23 ?        00:00:00 /usr/share/tb-web-report/chromium/chrome --type=renderer --no-sandbox --disable-background-timer-throttling --disable-breakpad --enable-automation --use-gl=swiftshader-webgl --disable-features=site-per-process --disable-gpu-compositing --service-pipe-token=13981085567223477512 **--lang=en-US** --headless --num-raster-threads=1 --service-request-channel-token=13981085567223477512 --renderer-client-id=2 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
ubuntu    2155  1466  0 04:30 pts/0    00:00:00 grep --color=auto tb

**Comment by ashvayka** [comment]
Hi @paulwang55 , we have added this support in v2.2.0 and we will share the documentation here shortly.

**Comment by paulwang55** [comment]
Hi ashvayka,

This issue can be closed. We just upgrade TB PE 2.1.3 to TB PE 2.2.0. at AWS This web report issue is solved.

Thanks
