### ISSUE TITLE
what is the JSON format for  saveRuleChainMetaData

### ISSUE THREAD

**Issue by rahultheagarajan** [thingsboard/thingsboard#1281]
hi, 
I am trying to work with the thingsboard using the swaggerUI. After successful login and configuration, i get to create a device, add telemetry and so on. But for the "rule-chain-controller : Rule Chain Controller " it is not working well. I am able to create a rule chain and getmetadata from a rule chain. But when i try to create a new node inside the rule chain, it is not working. This is the sample rulechain from which i use the json. 

<img width="336" alt="1" src="https://user-images.githubusercontent.com/36836341/49004642-ac714a80-f19f-11e8-8e96-415d4aed5996.PNG">

{
  "ruleChainId": {
    "entityType": "RULE_CHAIN",
    "id": "b95c5e80-dabe-11e8-958c-51edd2b95c16"
  },
  "firstNodeIndex": null,
  "nodes": [
    {
      "id": {
        "entityType": "RULE_NODE",
        "id": "65c11870-f07a-11e8-8267-877c9e71ee33"
      },
      "createdTime": 1543126911863,
      "additionalInfo": {
        "layoutX": 61,
        "layoutY": 280
      },
      "ruleChainId": {
        "entityType": "RULE_CHAIN",
        "id": "b95c5e80-dabe-11e8-958c-51edd2b95c16"
      },
      "type": "org.thingsboard.rule.engine.debug.TbMsgGeneratorNode",
      "name": "Temperature generator",
      "debugMode": false,
      "configuration": {
        "msgCount": 0,
        "periodInSeconds": 10,
        "originatorId": "caeddb20-dabd-11e8-958c-51edd2b95c16",
        "originatorType": "DEVICE",
        "jsScript": "var msg = { temperature: +(Math.random()*5 + 25).toFixed(1) };\nvar metadata = { data: 40 };\nvar msgType = \"POST_TELEMETRY_REQUEST\";\n\nreturn { msg: msg, metadata: metadata, msgType: msgType };"
      }
    }
  ],
  "connections": null,
  "ruleChainConnections": [
    {
      "fromIndex": 0,
      "targetRuleChainId": {
        "entityType": "RULE_CHAIN",
        "id": "926aadf0-d676-11e8-958c-51edd2b95c16"
      },
      "additionalInfo": {
        "layoutX": 401,
        "layoutY": 280,
        "ruleChainNodeId": "rule-chain-node-3"
      },
      "type": "Success"
    }
  ]
}

When i pass the same json for "saveRuleChainMetaData" for another rulechainid (which is an empty rulechain with no nodes), i'm getting response code = 200. but there is no node created.When i pass in the json that was obtained from **getRuleChainMetaData**, i get the below response:

![image](https://user-images.githubusercontent.com/36836341/49004730-e2163380-f19f-11e8-9868-7be210dc6deb.png)

I tried modifying the rulechainid, createdtime and rule node Id as well according to the json format given -
{
  "connections": [
    {
      "fromIndex": 0,
      "toIndex": 0,
      "type": "string"
    }
  ],
  "firstNodeIndex": 0,
  "nodes": [
    {
      "additionalInfo": "string",
      "configuration": "string",
      "createdTime": 0,
      "debugMode": true,
      "id": {
        "id": "string"
      },
      "name": "string",
      "ruleChainId": {
        "id": "string"
      },
      "type": "string"
    }
  ],
  "ruleChainConnections": [
    {
      "additionalInfo": "string",
      "fromIndex": 0,
      "targetRuleChainId": {
        "id": "string"
      },
      "type": "string"
    }
  ],
  "ruleChainId": {
    "id": "string"
  }
}.

It is not creating the rule inside the new rulechain using the metadata. it would be helpful if i could get a sample json format for "saverulechainmetadata" or any other workarounds. Thanks !

**Comment by vparomskiy** [comment]
You can find the correct format in the Browser Console. Here is an example for Chrome DevTools:
https://developers.google.com/web/tools/chrome-devtools/network-performance/

Also - why do you configure RuleChains via REST API?

**Comment by rahultheagarajan** [comment]
Hi @vparomskiy , Thanks for the suggestion. I tried getting the json format from the browser console, it is the same and correct format for the rule node creation, but it is still not getting updated in the rule chain from the swagger UI. 
`{
  "ruleChainId": {
    "entityType": "RULE_CHAIN",
    "id": "8499dfa0-e2a8-11e8-9415-d2806a0d657d"
  },
  "firstNodeIndex": null,
  "nodes": [
    {
      "id": {
        "entityType": "RULE_NODE",
        "id": "6f382300-f2c1-11e8-8267-877c9e71ee33"
      },
      "createdTime": 1543377324336,
      "additionalInfo": {
        "layoutX": 87,
        "layoutY": 277
      },
      "ruleChainId": {
        "entityType": "RULE_CHAIN",
        "id": "8499dfa0-e2a8-11e8-9415-d2806a0d657d"
      },
      "type": "org.thingsboard.rule.engine.debug.TbMsgGeneratorNode",
      "name": "rahul",
      "debugMode": false,
      "configuration": {
        "msgCount": 0,
        "periodInSeconds": 1,
        "originatorId": null,
        "originatorType": null,
        "jsScript": ""
      }
    }
  ],
  "connections": null,
  "ruleChainConnections": null
}`

I think the problem is in this part,  
![image](https://user-images.githubusercontent.com/36836341/49128311-c331b180-f305-11e8-97de-4d00385f677a.png)
So, only if i click the tick mark, the meta-data is getting updated and the rule node is created.
I will now modify my question to "_how to create a rule-node inside a rule-chain from the swagger UI, even if the json format is correct_". Could you help on this part :(

> And also i'm building a website that uses the thingsboard's rules engine as a part. such that the user will give inputs that could configure the rule-chain and get back responses and display it in.

**Comment by fjpa121197** [comment]
Hi, I also having issues doing this. Did you solve this? 

Im trying to create a rule chain that generate random telemetry data for many devices. I have managed to create the devices, however, I want to assign this rule to all the devices created. 

Do I need first to use the saveRuleChain method and saveRuleChainMetaData ? Or is there a way to combine both and only do one POST request? 

Do you have an example on how to do it? (Including saveRuleChain and saveRuleChainMetaData)

Thanks in advance

**Comment by volodymyr-babak** [comment]
Rule chain metadata is not a public API, it's the internal structure of the ThingsBoard platform and the way how its stored can be changed between releases. 
You can use this endpoint to import/export rule chains from one ThingsBoard platform to another, but it's not designed that you are going to add new rule nodes with a help of third-party script.
If you'll really need it, here is the source code, that is responsible for processing incoming rule chain metadata JSON:
https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java#L136
You can review **saveRuleChainMetaData** method and use similar login in your custom third-party tools.
But again, there is no guarantee that this will work between releases. 
If you'll implement the logic for **3.3.3** release, there is only a guarantee, that it will compatible with **3.3.3** ThingsBoard release.
