### ISSUE TITLE
what is the rest call to get telemetry by interval of 1 hour ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1285]
@nabil-rejeb @vparomskiy does any one know how to get telemetry data by interval of 1 hour, i tried to use 
```
curl -v -X GET "http://localhost:8080/api/plugins/telemetry/DEVICE/683ec600-d839-11e8-abfc-69936acdc23a/values/timeseries?keys=temperature&startTs=1542975941000&endTs=1543062341000&interval=3600000&limit=24&agg=AVG" \
--header "Content-Type:application/json" \
--header "X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiIxNGIxM2FkMC1kNzY4LTExZTgtYjZhNi1lOTI3MjU3OTM3YTEiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMTQ4OWRjYjAtZDc2OC0xMWU4LWI2YTYtZTkyNzI1NzkzN2ExIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTQzMjQ0OTUxLCJleHAiOjE1NDMyNDU4NTF9.VQf6TUQ59D3P2iuMHaBefpn49KaTCSwFvYVNrZP8hbQiEziQBpcHZWBX3vF8akMl4MzamDE691YuBiEhZSrVVg"
```

startTs: 1542975941000 ( November 23, 2018 12:25:41 PM)
endTs: 1543062341000 (November 24, 2018 12:25:41 PM)
interval:  `3600000` (number of milliseconds for an hour)
limit: 24
agg: AVG

the rest call return data but the difference between timestamps is not an hour or at least near it, is there something wrong on the REST call? do i need to change ?
what i want is to get value by intervall of an hour ? for the data (temperature), it's sent every around 2s using mqtt

**Comment by ashvayka** [comment]
put agg: NONE and limit to something big. This will give you the raw data. If you are interested in aggregated data that you are using correct query. What is the result you are receiving?

**Comment by souhaiebtar** [comment]
@ashvayka  thanks for responding, i receive data (timestamp with temperature) but the interval is not of an hour, what i want is that the interval between the timestamp is of an hour ?

**Comment by Wdfwilson** [comment]
Same problem interval is not match with result, and this is my param,
![image](https://user-images.githubusercontent.com/45866173/49984317-95ee3000-ffa2-11e8-9116-145b416c1229.png)


Result:
![image](https://user-images.githubusercontent.com/45866173/49984310-8969d780-ffa2-11e8-9ae2-24d42f1bca9a.png)

**Comment by vparomskiy** [comment]
@Wdfwilson when aggregation type **none** is used and **limit** set to 100. API call will return latest 100 telemetries in provided time-window (startTs - endTs). It is exaclty what you see.
If you can describe what you want to load then I'll provide correct api call.

**Comment by souhaiebtar** [comment]
@Wdfwilson thanks for responding, i'm sending data every 2s which mean data is not the problem, the problem is either my call or the api provided don't provide such a feature,  what i want to do is to get a list of value with the interval between them of around one hour ( i don't want aggregation, i want the exact value) ?

**Comment by souhaiebtar** [comment]
@vparomskiy,  i don't want to return random value, i want to return value  with "ts" between every 2 value is of around (1 hour), what i understand is that aggregation return a calculated value (not the exact value), correct me if i'm wrong ?

**Comment by vparomskiy** [comment]
You are right, aggregated value returned. But why it is does not work for you?

**Comment by souhaiebtar** [comment]
i want to create a chart with the exact value, not the aggregated value, the reason for that is that i want to add a comment system, when i click on a point a popup shows up where i can put comment,

**Comment by vparomskiy** [comment]
We have implemented similar case with existing api. The idea is that when point is clicked you need to take a timestamp  of this point and save comment with the same timestamp, but different telemetry name. When you need to fetch comments for the period - you just load all raw telemetries with aggregation = none
