### ISSUE TITLE
Not Found: flatmap-stream@0.1.1 while compiling msa/js-executor

### ISSUE THREAD

**Issue by kidtoy** [thingsboard/thingsboard#1286]
When running "mvn clean install -DskipTests" I get the following error...

[INFO] Running 'npm install' in /root/thingsboard/msa/js-executor
[ERROR] npm ERR! code E404
[ERROR] npm ERR! 404 Not Found: flatmap-stream@0.1.1
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /root/.npm/_logs/2018-11-27T13_38_13_618Z-debug.log

While searching about the error, I found this:
https://github.com/dominictarr/event-stream/issues/116

Apparently the package was removed from the npm repository. Is there any workaround?

**Comment by vparomskiy** [comment]
Fix already applied in the master branch.
