### ISSUE TITLE
The Tenant's ralation has no To Entity field.There is no place to fill this field.

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1288]
![image](https://user-images.githubusercontent.com/31084798/49122200-64147280-f2ee-11e8-87b5-a2e3b349747f.png)
But other entities has the To Entity field. such as the CUSTOMER, ASSET, DEVICE.
![image](https://user-images.githubusercontent.com/31084798/49122032-bb661300-f2ed-11e8-94a7-2a34073ab028.png)

_Originally posted by @qwyinxiang in https://github.com/thingsboard/thingsboard/issues/1284#issuecomment-442281493_

**Comment by volodymyr-babak** [comment]
In the latest **3.3.3** release you can related Tenant to a different Tenant from sysadmin screen:
![image](https://user-images.githubusercontent.com/3466101/152548985-27aa0e87-a9ae-4ce8-8d7c-d00ba53eea4a.png)
