### ISSUE TITLE
Devices created through the gateway, the device type is DEFAULT？

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1289]
I created a gateway device and configured the mqtt extension.
Then I publish device telemetry data, and created an device.
But the newly created device type are all "DEFAULT".
Is this right?

**Comment by felix-ma** [comment]
How many versions of ThingsBoard do you use? The latest version fixes the bug.

**Comment by felix-ma** [comment]
It's not a big update, but a master branch that is being developed.
When did I repair it?
I had encountered this problem before, and I repaired it after updating the code.

**Comment by felix-ma** [comment]
![image](https://user-images.githubusercontent.com/30289895/49209468-86dd7e80-f3f5-11e8-8650-0f2345e73aa8.png)
I found it.

**Comment by qwyinxiang** [comment]
But I have reviewed your commit on 2018/4/18, the modified file content is the same as my version.
Let me check it again. thank you very much.
