### ISSUE TITLE
How to create functions between multiple data-sources?

### ISSUE THREAD

**Issue by toti1212** [thingsboard/thingsboard#129]
Hi guys.
I have two sensors: DeviceA and DeviceB that send to Server tempA and tempB respectively, and i want to calculate the diff between them and graph it all in the same chart.
Thanks

**Comment by ashvayka** [comment]
Hi @toti1212 ,

This is now available only throught the thirdparty processing of the data. To provide analytics or function between different data sources you can push all data to external analytics system and then push the results back to TB. See more details here: https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/

**Comment by toti1212** [comment]
Ok!, Thanks! and congrats for this amazing platfom!
