### ISSUE TITLE
How to control Raspberry Pi GPIO through TB-Gateway?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#1290]
hi:
I am very interested in the following example, but I want to control GPIO through tb-gateway instead of TB directly controlling GPIO. What should I do?
https://thingsboard.io/docs/samples/raspberry/gpio/

Now, I installed TB-gateway and mosquitto (mqtt broker) in Raspberry Pi and TB on PC. What should I do next?

![gpio](https://user-images.githubusercontent.com/30205233/49166713-e6dd1200-f36e-11e8-94b6-52f771f44304.png)

What should **THINGSBOARD_HOST** and **ACCESS_TOKEN** fill in?

**Comment by volodymyr-babak** [comment]
Please follow this starting guide to connect devices over the TB Gateway:
https://thingsboard.io/docs/iot-gateway/getting-started/

Once you'll connect GW to the platform, please configure the MQTT connector to connect Raspberry PI device:
https://thingsboard.io/docs/iot-gateway/config/mqtt/
