### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1293]
Hello,

I have upgreaded the thingsboard 2.0.3 to 2.1.3, and I have modified these line in the thingsboard.yml
database:
  entities:
    type: "${DATABASE_ENTITIES_TYPE:cassandra}" # cassandra OR sql
  ts:
    type: "${DATABASE_TS_TYPE:cassandra}" # cassandra OR sql (for hybrid mode, only this value should be cassandra)

When thingsboard was started, i have not seen my previously data on the charts.
What should I do, if I would like to see the previously data?

**Comment by JozsefGuyas** [comment]
I have tried and it works 
Thank you for help

**Comment by ashvayka** [comment]
In v2.2 we have restored the ts_key_value_partitioning to previous default value to minimize issues during the update.
