### ISSUE TITLE
Unable to post telemetry data using HTTP from command line

### ISSUE THREAD

**Issue by nishant1saxena** [thingsboard/thingsboard#1297]
Hi All,

I installed the community version on Linux. Created a device and now trying to post telemetry data using the following command:
sudo curl -v -X POST -d "{\"temperature\":28}" http://localhost:8080/api/v1/D7ZalE35MyP5wQ5eKSaz/telemetry --header "Content-Type:application/json"

This fails with an error message saying "Timeout during persistence of the message to the queue!" Please help me on this.

The response on the command line is as follows:

Note: Unnecessary use of -X or --request, POST is already inferred.
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,::1'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /api/v1/D7ZalE35MyP5wQ5eKSaz/telemetry HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 18
> 
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 408 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Content-Type-Options: nosniff
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 67
< Date: Fri, 30 Nov 2018 10:00:40 GMT
< Connection: close
< 
* Closing connection 0
{"error":"Timeout during persistence of the message to the queue!"}

Thank You

**Comment by souhaiebtar** [comment]
have you generated a JWT token, it's needed to send data, check this link: https://thingsboard.io/docs/reference/rest-api/

**Comment by ashvayka** [comment]
Hi @nishant1saxena , I assume there is some issue with the DB since you are receiving this reply. Is TB UI working well for your instance?

**Comment by nishant1saxena** [comment]
Hi Andrew,

The TB UI is working fine. Initially, I logged in as sysadmin, then created a tenant and then a user.
After logging in with that user, I was able to see all the tabs like devices etc.
Then created assets, devices, but getting this issue while posting data.

Thanks

**Comment by ashvayka** [comment]
Try to escape quotes like this:

sudo curl -v -X POST -d "{\"temperature\":28}" ...

**Comment by nishant1saxena** [comment]
This time I got a HTTP 500 saying INKApi error. My command is:
sudoku curl -v -X POST -d "{\"temperature\":28}" http://localhost:8080/api/V1/<deviceToken>/telemetry --header "Content-Type: application/json"

Please suggest.

Thank you

**Comment by vparomskiy** [comment]
@nishant1saxena were you able to resolve your task? if this issue is not actual anymore, then I'll close it.
