### ISSUE TITLE
how to use  mdDialog on widget ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1298]
@nabil-rejeb @vparomskiy @ashvayka, i need to use mdDialog to show a confirmation popup on just part of the page, i injected `$mdDialog` and it shows properly but after that the browser tab become unresponsive and i have to close the tab

the code i'm using is 
```JAVASCRIPT
$mdDialog.show(
      $mdDialog.alert()
        .parent(angular.element(angular.element(self.ctx.$container))
        .clickOutsideToClose(true)
        .title('This is an alert title')
        .textContent('You can specify some description text in here.')
        .ariaLabel('Alert Dialog Demo')
        .ok('Got it!')
        .targetEvent(evt)
    );
```

any help please, and thanks

**Comment by nabil-rejeb** [comment]
hello @souhaiebtar 
Take a look to numeric data input in issue #574

**Comment by souhaiebtar** [comment]
thanks

**Comment by souhaiebtar** [comment]
@nabil-rejeb  the problem is that it open on full screen when using parent: angular.element(document.body), i want it to open only on the widget div ?

**Comment by Manusisko** [comment]
Hello. Could you please provide some more details on how to use this? I've tried using your code but nothings happends, and I need to implement a popup window with an iframe on it. I've tried using your code in the Actions Api, but cannot seem to find any documentation on this...

**Comment by Ultrazombie** [comment]
closed due to inactive
