### ISSUE TITLE
Adminstration login

### ISSUE THREAD

**Issue by foliveira15** [thingsboard/thingsboard#13]
Where I can find user/pass for the adm account? 
Only Tenant account in docs. No access to system settings.
tks

**Comment by Shpigor** [comment]
sysadmin@thingsboard.org/sysadmin

**Comment by foliveira15** [comment]
Thank you!

**Comment by ashvayka** [comment]
More information about demo data is here:
http://thingsboard.io/docs/samples/demo-account/
