### ISSUE TITLE
Error when upgrading to version 2.2 from 2.1.3

### ISSUE THREAD

**Issue by pavellzubkov** [thingsboard/thingsboard#1300]
>  ===================================================
 :: ThingsBoard ::       (v2.2.0)
 ===================================================

Error creating bean with name 'baseTimeseriesService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentExcep        tion: Could not resolve placeholder 'database.ts_max_intervals' in string value "${database.ts_max_intervals}"
ThingsBoard upgrade failed!

**Comment by mfalkvidd** [comment]
Looks like you missed one of the new config parameters whem merging your existing config files with the new config files.

**Comment by ashvayka** [comment]
Please review your current thingsboard.yml and compare to new one: https://github.com/thingsboard/thingsboard/blob/release-2.2/application/src/main/resources/thingsboard.yml
