### ISSUE TITLE
How to get data at widget's "self.onInit" function ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1303]
Hi,

We are devloping our widget. Here is our code for "self.onInit" function.

self.onInit = function() {
        
        self.ctx.$scope.data = self.ctx.defaultSubscription.data;
        
        var scope = self.ctx.$scope;
        console.log(scope.data);
        
        **console.log(Object.keys(scope.data));
        
        for (let elem in scope.data[0]) {
            console.log(`${elem} = ${scope.data[0][elem]}`);
            
        }**
    
Here is the HTML code.

<div flex layout="column" style="height: 100%;" layout-align="center stretch">
      <div>My first latest values widget.</div>
      <div flex layout="row" ng-repeat="dataKeyData in data" layout-align="space-around center">
          <div>{{dataKeyData.dataKey.label}}:</div>
          <div>{{dataKeyData.data[0][0] | date : 'yyyy-MM-dd HH:mm:ss'}}</div>
          <div>{{dataKeyData.data[0][1]}}</div>
          <div>{{mydata}}</div>
      </div>
  </div>

This is the simple code from thingsboard document. I found a strange thing. I can see the data through browser's console. When I use console.log to print the information,  the "data" is empty.

Can someone show me how I can get the "data" (datatype is array) ? 

Regards,

Paul Wang

**Comment by colognebroker** [comment]
did you find a solution ?
i am looking for the same

**Comment by progzero** [comment]
I am also interested in this question. How to access data in this function (self.onInit)?

**Comment by mohesk** [comment]
```
dataArray = self.ctx.data
dataArray.forEach(function(data) {
    console.log(data)
    })
```

**Comment by progzero** [comment]
> ```
> dataArray = self.ctx.data
> dataArray.forEach(function(data) {
>     console.log(data)
>     })
> ```

When accessing the property dataArray.data[0][1] will undefined. This method works only in function self.onDataUpdated.

**Comment by mohesk** [comment]
Have you checked `then` function? 

dataArray = self.ctx.data
dataArray.then(data =>{
    console.log(data[0])
    })

**Comment by Ultrazombie** [comment]
closed as not active

**Comment by eluHP** [comment]
console.log(self.ctx);
