### ISSUE TITLE
Searching for help: Thingsboard HTTP Transport Service Failure

### ISSUE THREAD

**Issue by EvanZ0423** [thingsboard/thingsboard#1304]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'http'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
     Required by:
         :http:unspecified
      > Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
         > Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/gradle-ospackage-plugin/3.8.0/gradle-ospackage-plugin-3.8.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/netflix/nebula/gradle-ospackage-plugin/3.8.0/gradle-ospackage-plugin-3.8.0.pom'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.934 secs
[INFO] Initialize build
[INFO] Build
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.2.0:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  1.778 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  4.198 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.196 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  6.769 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  8.308 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  1.493 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.089 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [ 12.080 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  2.300 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.920 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.208 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 14.958 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.086 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.556 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  8.371 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.067 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [  5.411 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 min
[INFO] Finished at: 2018-12-03T22:01:00+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf org.thingsboard.transport:http

I've been stuck in this problem for days.It seems that something is wrong with my Intenet connection but I'm really not sure.
Anyone has faced this problem before?I really need some help.

**Comment by EvanZ0423** [comment]
By the way,I'm using win10 with java1.8.

**Comment by ashvayka** [comment]
There was some issue during fetch of dependency. This is a generic issue not related to TB. Try to cleanup local maven repo and repeat. Build is ok. See: https://travis-ci.org/thingsboard/thingsboard

**Comment by m0o0hammad** [comment]
hello @ashvayka 
please help 
![screenshot from 2019-01-16 13-32-44](https://user-images.githubusercontent.com/30108318/51241527-4630c900-1993-11e9-93b2-5665ac3ba20c.png)

**Comment by ericyansuzhou** [comment]
Did you fix this issue?I'm facing the same issue and looks like the 'https' issue, I can download the gradle-2.13-bin.zip via http, I can't find the place to modified@EvanZ0423

**Comment by AmarLimitless** [comment]
Hi @ashvayka
Please help I am facing the same issue while fetching the dependencies.....
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.082 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [  1.632 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by coder-chriswang** [comment]
@EvanZ0423 how did u fix it?Could u please tell us?

**Comment by Flyerison** [comment]
hi, someone fix it? why going to download gradle resource zip?

**Comment by sww0825521xy** [comment]
Kill the java process and retry, it works for me

**Comment by Flyerison** [comment]
@sww0825521xy hi, thanks your suggest, but what do you mean "kill the java process", JDK process?

**Comment by theanhbp2018** [comment]
I fixed them, you have to install "OpenJDK11U-jdk_x64_windows_hotspot_11.0.14.1_1" everything done.

**Comment by v1nayHyder** [comment]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.006 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [02:14 min]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard LwM2m Transport Service ................ SKIPPED
[INFO] Thingsboard SNMP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Version Control Executor ............... SKIPPED
[INFO] ThingsBoard Version Control Executor Microservice .. SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Monitoring Service ..................... SKIPPED
[INFO] ThingsBoard Monitoring Microservice ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:57 min
[INFO] Finished at: 2024-10-24T12:24:49+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.4:run (default-cli) on project http: Process terminated with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf org.thingsboard.transport:http
PS E:\thingsboard_bitxia\thingsboard> netstat -ano | findstr :9092
PS E:\thingsboard_bitxia\thingsboard> 
 getting issue how to fixed it?
