### ISSUE TITLE
thingsboard compile stucks in HTTP Transport Service 

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1305]
i provide screenshot of it and it keeps on stuck in http transport section 
![screenshot from 2018-12-04 15-05-21](https://user-images.githubusercontent.com/36095688/49432645-2e7ff580-f7d6-11e8-9b63-ef4e0d346c6f.png)

**Comment by vparomskiy** [comment]
try to run this command (debug output enabled) and provide maven logs:
`mvn -X clean install -DskipTests`

**Comment by gopirathnamt** [comment]
hi its work fine now
