### ISSUE TITLE
esp8266 to thingsboard via ddns and port forwarding

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1306]
Hi
I managed to connect to the server management page with the help of ddns, but to connect the esp 8266 machine to the server via api mqtt, which port should I pass on my router?

**Comment by khphillips** [comment]
If I understand correctly, I believe you need to forward port 1883. The demo code for the ESP uses the PubSub client and it is connecting to port 1883 on the Thingboard Server.

**Comment by m0o0** [comment]
@khphillips  Thank you for guiding you but I am 1883 but can not communicate. I use the following code to communicate:
char thingsboardserver[ ] = "xxxx.dlinkddns.com"
..
..
void setup(){
..
..
client.setServer(thingsboardserver,1883);

It's also working properly for managing the job, but I'm having trouble communicating between the server and the device.

On the modem, ports 8080, 1883, and 5683 have been transmitted.

**Comment by m0o0** [comment]
The problem was solved Thank you

**Comment by forGGe** [comment]
@m0o0 , kindly ask you to close the issue, if your problem is resolved, thanks
