### ISSUE TITLE
how to specify the current widget as parent ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1307]
i'm using $mdDialog in a custom widget, the  code is 
```
$mdDialog.show({
            contentElement: $('#myStaticDialog',self.ctx.$container),
            parent: angular.element(document.body)
        });
```
the problem is that i can't get the dialog to only show on the widget only (not on full screen), i know that `parent: angular.element(document.body)` have to change,

i changed my code to 
```
$mdDialog.show({
            contentElement: $('#myStaticDialog',self.ctx.$container),
            parent: angular.element(self.ctx.$container)
        });
```,
the dialog show  properly like i want it but the entire page stop responding (the tab cpu usage is 100 %, and nothing respond)

**Comment by souhaiebtar** [comment]
@nabil-rejeb do you have any idea how to do it ? or how to show $mdPanel on custom widget ? sorry  for the bothering.

**Comment by nabil-rejeb** [comment]
Sorry , No idea now

**Comment by souhaiebtar** [comment]
@nabil-rejeb  thanks anyway

**Comment by PovitruliaV** [comment]
Hi @souhaiebtar, 
Are your issue still relevant?
