### ISSUE TITLE
HTTP POST using QUECTEL EC25

### ISSUE THREAD

**Issue by viswanadh401** [thingsboard/thingsboard#1308]
Hi,

I am trying to create device in thingsboard using HTTP POST method.

POST /api/device/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json
X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiJmZGM4MmRlMC05ZmUyLTExZTgtYjI0OC0yNTlhNzQyN2U2YTAiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiZmQ3NjNkNTAtOWZlMi0xMWU4LWIyNDgtMjU5YTc0MjdlNmEwIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTQzOTMyNTk0LCJleHAiOjE1NzU0Njg1OTR9.E5Bw73-4FAvTpsqoJ3_wg8uD0pePBUaKZPlXzvJcIfjubnc4KpZpTDX-STsCJTmSVvCHUGJDOk110Xrck--EMw

{"name":"DEMO","type":"TEST"}

I tried above code through Postman API and works fine.

But when I am trying through my Quectel EC25. It showing the error as 405(method not supported).

Here I am giving the commands in the console I used for HTTP POST to create device.

AT+QHTTPURL=36,80

CONNECT
http://localhost:8080/
OK
AT+QHTTPPOST=668,80,80

CONNECT
POST /api/device HTTP/1.1
Host: localhost:8080
Content-Type: application/json
X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiJmZGM4MmRlMC05ZmUyLTExZTgtYjI0OC0yNTlhNzQyN2U2YTAiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiZmQ3NjNkNTAtOWZlMi0xMWU4LWIyNDgtMjU5YTc0MjdlNmEwIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTQzOTMyNTk0LCJleHAiOjE1NzU0Njg1OTR9.E5Bw73-4FAvTpsqoJ3_wg8uD0pePBUaKZPlXzvJcIfjubnc4KpZpTDX-STsCJTmSVvCHUGJDOk110Xrck--EMw

{"name" : "DEMO","type": "Create Device"}
OK

+QHTTPPOST: 0,405
AT+QHTTPREAD=80

CONNECT
{"timestamp":1543997802048,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/"}
OK

+QHTTPREAD: 0

Please let me know where the mistake. What the sequence I missed.

**Comment by ashvayka** [comment]
Based on your log you are connecting from the Quectel EC25 to the localhost. This means you are connecting to the same Quectel EC25 and not the server that host ThingsBoard. Please make sure you are using the correct IP address (local or external IP of your ThingsBoard server)
