### ISSUE TITLE
UI Edit Button Overlapping Toobar Menu Items

### ISSUE THREAD

**Issue by idurant** [thingsboard/thingsboard#1310]
The edit mode button changes position with the toolbar header. This causes a slight issue when the UI is not full screen, you can not see all of the paginating toolbar options.

Image attached: 
 
![2018-12-05 08_57_12-thingsboard _ devices](https://user-images.githubusercontent.com/40613410/49521888-f6c38d00-f86b-11e8-8adb-9e66eae0a2c1.png)

**Comment by fotis400** [comment]
Related to #378

**Comment by idurant** [comment]
> Related to #378

ouch, no fix a year later. I guess it doesn't stop workflow but looking at your screenshot it becomes a bigger issue on mobile devices.

**Comment by ashvayka** [comment]
Hi @fotis400 and @idurant . I believe it is not a valid use case to work as a tenant administrator from the mobile phone. The customer user is not affected because he does not have edit button. We welcome you to submit PR, but we believe that this is low priority item.

**Comment by fotis400** [comment]
Hi @ashvayka . It is true that a tenant administrator is most probable to work on a desktop computer. However, sometimes problems happen. And you have to check the device while on the move.

Why not improve usability a little, even in such edge use cases, by something that seems like a trivial fix?
