### ISSUE TITLE
Some keys not working in Javascript editor

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1311]
Sometimes, a very strange problems occurs when editing any javascript code in any of the many places around Thingsboard where it is possible. Some keys simply stop working. Most of the time, the "=" (or "+") and the "_" (or "-"). All other keys work as intended, including other special characters, like "[" or "|".

When this problem surfaces, the current edit will not be saved succesfully, even if the UI says that it was saved.

The problem is not browser specific, having used latest Chrome and latest Firefox on Windows 10, and if I type those keys in some other program (say, Notepad, for example) and then copy/paste the characters, they're pasted normally. No other tabs opened in the browser. Machine checked virus-free (AVG).

I do not have a reliable list of steps for reproducing. I'll say simply that you must open any place in Thingsboard where there is a Javascript code editor, try typing something and sometimes it'll refuse to accept some keys completely.

Reloading the complete page (<control>+R or <F5>) almost always solve the problem.

Beyond that being an annoyance from the usability point of view, I worry that there could be some underlying problem of a more serious relevance behind it, since state is not being saved while the UI says it was.

Thanks,

**Comment by mfalkvidd** [comment]
When this problem is triggered, is anything printed in the browser console log?

**Comment by RondoRonaldo** [comment]
Can you specify whether the problem persists?
