### ISSUE TITLE
w10 build source error

### ISSUE THREAD

**Issue by ycy1991** [thingsboard/thingsboard#1312]
hi 
I always report the following errors in the source code compilation project of win10 system. I checked issues and found no corresponding solution. How to solve this problem?
![image](https://user-images.githubusercontent.com/16506338/49584787-64200c80-f997-11e8-9c7d-705c3b18c592.png)

**Comment by volodymyr-babak** [comment]
@ycy1991 do you have build problems with the latest release version? Is this issue still relevant?
