### ISSUE TITLE
Typo and wrong link in docker description

### ISSUE THREAD

**Issue by tagliala** [thingsboard/thingsboard#1313]
Hi,

I've found a typo and a wrong link at https://hub.docker.com/r/thingsboard/application/

Typo:

> Thi**gn**sboard installation using Docker 

Wrong link:

> official documentation

points to `https://hub.docker.com/r/thingsboard/application/thingsboard.io`

Hope it helps

**Comment by PovitruliaV** [comment]
Hi @tagliala, 
Thank you for letting us know about it. We have passed your comment on to the developers.
