### ISSUE TITLE
Missing data when aggregating

### ISSUE THREAD

**Issue by gringet** [thingsboard/thingsboard#1314]
When I use an aggregation function, some data are missed. I made a quick example to show the problem visually:

This is a real-time graph of the last 7 days, aggregate function is count and interval is 30min :
![cap1](https://user-images.githubusercontent.com/12461133/49640350-aedc6b80-fa0d-11e8-80af-a6da9d9c68c5.PNG)

This is the same real-time graph of the last 7 days, aggregate function is count and interval is 12 hours:

![cap2](https://user-images.githubusercontent.com/12461133/49640562-388c3900-fa0e-11e8-9c7f-f312646956f0.PNG)

As you can see, a lot of data are omitted around the 6 of December and at other days as-well.

The other aggregation function (sum, max, min...) have the same issue.

**Comment by gringet** [comment]
As seen in #1318 , the problem was coming from the fact that some data was in double format and other in long.

**Comment by vparomskiy** [comment]
Fix for this issue will be included in the next release. Average,Min,Max,Sum aggregation functions will process both numeric data types correctly.

**Comment by ashvayka** [comment]
Fixed here: #1440 Will be part of v2.3
