### ISSUE TITLE
Data Aggregation Function (SUM) does not work with some grouping intervals

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#1318]
I'm having an issue with the data aggregation function SUM, which does not appear to work under certain conditions.

In the first table below I have a screenshot of data coming from our weather station with no aggregation or grouping applied. You can see it calls in every ten minutes and there was a rainfall event during the period of 4:00am to 5:50am, with a total rainfall for the period being 12.954mm

![image](https://user-images.githubusercontent.com/16280541/49705148-4a6d1680-fc70-11e8-89c5-c05d0e33559d.png)

Now in the second table I have the SUM aggregation applied with a grouping interval of 1 hour which return a sum value for 4:30am - 5:30am and 5:30am to 6:30, which add up to 12.954mm

![image](https://user-images.githubusercontent.com/16280541/49705163-ae8fda80-fc70-11e8-8eb0-069084dcf20b.png)

**However** when I apply a **TWO hour grouping interval** to the SUM aggregation function for the same period I DO NOT get any values returned:

![image](https://user-images.githubusercontent.com/16280541/49705189-ea2aa480-fc70-11e8-9998-d77a9ee2f3c7.png)

We have checked and the values are being stored correctly (i.e. not strings)
![image](https://user-images.githubusercontent.com/16280541/49705199-03cbec00-fc71-11e8-81ef-d18b2cd24143.png)
(key rf = Rainfall(mm))

This issue is not isolated to this key and happens for example to the rc key which is the actual number of bucket tips from inside the weather station used to calculate rainfall (i.e. 1 bucket tip = 0.254mm of rain)

We are trying to build a chart which give the daily total rainfall for the past ten days, so we need to apply the SUM aggregation to the rf key (rainfall) with a grouping interval of **1 day** however it seems intervals > than 1 hour do not return any values

**Comment by ChristianLutz** [comment]
Maybe #1314 is related

**Comment by vparomskiy** [comment]
@enviroeye It looks like data is not aggregated correctly in cases when time series value if the selected interval is saved as long and double. 
Could you please confirm that inside Cassandra (table ts_kv_cf ) some records (with the key = 'rc' ) have value saved in **long_v** column and others in **dbl_v** column

**Comment by vparomskiy** [comment]
Fix for this issue will be included in the next release. Average,Min,Max,Sum aggregation functions will process both numeric data types correctly.

**Comment by enviroeye** [comment]
Than-you; when is the next release due to be ready? This is a real headache for us as we have a number of customers complaining about incorrect readings from their weather stations and we have had to go an update all their dashboards to 1 hourly groupings, which they don't like as they work from daily rather than hourly data

**Comment by ashvayka** [comment]
Fixed here: https://github.com/thingsboard/thingsboard/pull/1440 Will be part of v2.3
