### ISSUE TITLE
String data not showing up in Timeseries table

### ISSUE THREAD

**Issue by musskopf** [thingsboard/thingsboard#1319]
Hello, I'm trying to setup a simple timeseries table to show all messages received from a device, but it's not showing the "string" data.

Here the latest data from the device:
![image](https://user-images.githubusercontent.com/13247713/49712724-7d73d200-fc91-11e8-9925-97ef37f0a042.png)

And here the same device showing all messages (but the 'gateway' field is blank?!):
![image](https://user-images.githubusercontent.com/13247713/49712936-73060800-fc92-11e8-9b6d-124fd5d02e54.png)

I've check and all data is in the Postgres DB, but it's like the Widget is not reading from the str_v column.

Any ideas?

Thanks!

**Comment by Tauvic** [comment]
I have the same problem

**Comment by Cody-Hayes97** [comment]
Did you ever figure this issue out?

**Comment by RGNagel** [comment]
Up! Any updates?

**Comment by IoTopenTech** [comment]
For a short text, you coul code it as an integer (for examples, using ASCII or a more compact schema), and decode it in Cell Content Function
![imagen](https://user-images.githubusercontent.com/52624907/113409597-e7a86780-93b1-11eb-93d5-905fc90b6a34.png)

**Comment by PovitruliaV** [comment]
Hello, @musskopf is your problem is still relevant?
