### ISSUE TITLE
Error in GUI new rule: Cannot add filter

### ISSUE THREAD

**Issue by dejwoo** [thingsboard/thingsboard#132]
Hey guys, kudos for the platform, I like it a lot.
## Issue
I have got a weird error during creation of new rule, I am trying to filter devices for the rule based on attribute, so I've pasted example code from the docs:

`typeof cs.firmware_version !== 'undefined' && cs.firmware_version === '1.0.0' ` 

and when I click Add button nothing happens, console displays this error:

`
Form submission failed, as the <SELECT> element named 'componentType' was implicitly closed by reaching the end of the file. Please add an explicit end tag ('</SELECT>')
`

I suspect this might be browser problem.
Failed addition of filter happens in Google Chrome(58.0.3029.96) - latest version as of writing this issue.

Adding filter to new rule __works__ in Microsoft Edge 40.15063.0.0.

## Debugging info
Thingsboard server node version: 1.2.2-1

## To resolve this problem
I have tried so far:
1. deleting cookies, cached memory, etc...
2. relogging

Any ideas how to solve this problem?

Thanks

**Comment by ashvayka** [comment]
@dejwoo Thanks for reporting this issue. We will take a look.

**Comment by ikulikov** [comment]
The issue wasn't reproduced.
Tested with thingsboard version 1.3.0-SNAPSHOT. 
Browser: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by nuragic** [comment]
@dejwoo Hi! I've got the same exact error in Chrome, but after googling it I only found this issue. Besides, I'm not using thingsboard so yeah, it's a chrome issue. 😄 

Please, let me know if this helps:

Go to `chrome://flags/#enable-experimental-web-platform-features` and click **Disable**.

Then click the **Relaunch** button and test again.

**Comment by dejwoo** [comment]
@nuragic Hey, thanks for the tip! 😄 
Unfortunately I did not have experimental web platform features enabled.
Did it help you?

**Comment by nuragic** [comment]
Hi! Yup, it worked for me... Ouch, I'm sorry it didn't worked for you... Maybe some chrome extensions?

**Comment by mikewest** [comment]
@dejwoo: It would surprise me if this happened without the experimental flag flipped, would you mind checking again? (And sending me a link to a page where it happens so I can poke at it?)

The error message is output here (https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/HTMLFormElement.cpp?rcl=bf1c79c8f690220ba913dcb7709bb65d49055f82&l=310), and is guarded by a runtime flag check. It would be pretty weird if it was triggering without that flag being set. :)

**Comment by phistuck** [comment]
@mikewest - is that specific feature by any chance enabled by a small percentage field trial?

**Comment by mikewest** [comment]
I don't believe we're flipping the experimental flag on for folks; that would be pretty dangerous, actually. Still, if we were doing so, it would still show up as enabled in `chrome://flags`, which @dejwoo suggested wasn't the case.

**Comment by phistuck** [comment]
@mikewest - no, not the whole experimental flag - only that dangling select feature.

**Comment by dejwoo** [comment]
Hey guys, new report:

I have 2 dev stations(PC and laptop), so on PC I __had__ enabled _experimental-web-platform-features_, and `<select>` problem disappeared when I disabled them.

On laptop I have experienced this error before, and when @nuragic suggested to turn it off, it was disabled. Ergo my previous report that it did not help. I will be on a look out for this, and when it will happen I'll  do a screen-capture.

Could this happened because I am logged in as a user in chrome browser?

**Comment by johansolve** [comment]
Disabling chrome://flags/#enable-experimental-web-platform-features worked for me in a completely different issue with the same symptom

**Comment by ashvayka** [comment]
@dejwoo We will need to investigate it together with @ikulikov . Maybe some time next week we can have a live session.

**Comment by dejwoo** [comment]
@ashvayka sure, PM me with the details.

**Comment by stuartpb** [comment]
Probably worth linking to https://github.com/whatwg/html/issues/2253 which is the issue linked in the comment of the code [linked above](https://github.com/thingsboard/thingsboard/issues/132#issuecomment-319888863)
