### ISSUE TITLE
gps node

### ISSUE THREAD

**Issue by m0o0hammad** [thingsboard/thingsboard#1320]
Hello
In this program, I intend to transfer information to the server with the help of the module a 6mini and ublox, but this does not work. Also, it is necessary to specify the coordinate information on the monitor.

#include <FS.h>
#define TINY_GSM_MODEM_A6  //Defining model of modem
//#define TINY_GSM_DEBUG Serial

#include <ESP8266WiFi.h>
#include <TinyGsmClient.h>
#include <TinyGPS++.h>
#include <ArduinoJson.h>
#include <PubSubClient.h>
#include <SoftwareSerial.h> 
#include "SSD1306.h"
#define GPS_PWR_Pin 16  ///////Define esp8266pin to Active_HIGH Power UP through PNP 2N3906 Transistor Connected to power Pin on A7 PWR
#define BUZZER_Pin 2 //Buzzer pin 
#define switch_Pin 0 //switch pin 
#define PUSH_button 10 //Push Button manual position send

#define TOKEN "123456789" // thingsboard server
char thingsboardServer[] = "xx.xx.xx.xx"; // thingsboard server
String payload;

///////////////////////////////////// Your GPRS credentials
////////////////////////////////////// Leave empty, if missing user or pass
const char apn[]  = "your apn";
const char user[] = "";
const char pass[] = "";

const char* update_path = "/firmware"; //internal server update path
 
String owner_number="";   //authorized owner phone number to accept calls
int config_pointer = 0; ///////flag to allow or not allow send gps info by gprs

unsigned long startgprs;     ///variable that Holds Last GPRS Send Time
String response;  //recived response by Host 

String Switch_State= "0" ;//last state of relay

String Send_interval_str;
uint32_t Send_interval;

////////GPS Variables/////////
String latitude;    
String Longitude;
String HOUR;
String MINUTE;
String SECOND;
String YEAR;
String MONTH;
String DAY;
String SATELITES;
String COURSE;
String HDOP;
String ALTITUDE="0.00";
String SPEED="0";

SSD1306  display(0x3c, 4, 5); //define Instance for  OLED1306 Library
TinyGPSPlus gps;  // The TinyGPS++ object

SoftwareSerial GPS_Serial(13,15);   // The serial connection to the GPS device nodeMCU(RX,TX)
SoftwareSerial GSM_Serial(14,12);   // The serial connection to the GSM device nodeMCU(RX,TX)

TinyGsm modem(GSM_Serial);  // Define Tiny GSM Modem instance
TinyGsmClient GSM_client(modem);  //Define GPRS client with GSM Modem Instance

PubSubClient mqtt(GSM_client);// thingsboard server
int status = WL_IDLE_STATUS;

//////file instance///
File myFile ;
///////////////////////////////////////////////////Begin Of SetUP
void setup() {
  WiFi.mode(WIFI_OFF);
  SPIFFS.begin();
 
   display.init();
   display.flipScreenVertically();
   display.setFont(ArialMT_Plain_10);
   display.setTextAlignment(TEXT_ALIGN_LEFT);
    
     pinMode(GPS_PWR_Pin ,OUTPUT);
     pinMode(BUZZER_Pin,OUTPUT);
     pinMode(switch_Pin,OUTPUT);
     pinMode(PUSH_button,INPUT);
     
     digitalWrite(GPS_PWR_Pin ,LOW);
     digitalWrite(BUZZER_Pin,HIGH);
       
     Serial.begin(115200);
     GSM_Serial.begin(115200);
     GPS_Serial.begin(9600);
     delay(1000);
    
  if(config_pointer==0){ RUN_GSMHW();} 
  mqtt.setServer(thingsboardServer, 1883); //connect to server
}
///////////////////////////////////////////////////End Of Setup

///////////////////////////////////////////////////Begin of Loop
void loop() {
 if(config_pointer==0){
   if(millis()/1000 > 300 && YEAR == "2000" ){ESP.reset();}  // check if GPS is started or not to reset again
   
  checkcall();
  check_GPS(1000); //check and encode NMEA GPS responses
 

  if (millis() > 5000 && gps.charsProcessed() < 10){     ///check if GPS Sent Charachters or not
    
  display.clear();
  display.drawString(0, 33, "Nochars received");
  Serial.println(F("No GPS data received: check wiring"));
  display.display();
    
  }else{
    
display.clear();
                   // PUT Encoded GPS to Variables
 latitude =String (gps.location.lat(),6); 
 Longitude=String (gps.location.lng(),6);
 HOUR=String(gps.time.hour());
 MINUTE=String(gps.time.minute());
 SECOND=String(gps.time.second());
 YEAR=String(gps.date.year());
 MONTH=String(gps.date.month());
 DAY=String(gps.date.day());
 SATELITES =String(gps.satellites.value());
 ALTITUDE =String(gps.altitude.meters());
 SPEED=String(gps.speed.knots());
 COURSE=String(gps.course.deg());
 HDOP=String(gps.hdop.value());
 ///////////////////////////////////////show GPS Variables on OLED
display.setFont(ArialMT_Plain_10);
  display.drawString(0, 0, "Latitude: "+latitude);
  display.drawString(0, 10, "Longitude: "+Longitude);
  display.drawString(0, 21, "Date : "+MONTH+"/"+DAY+"/"+YEAR);
  display.drawString(0, 32, "Time UTC : "+HOUR+":"+MINUTE+":"+SECOND);
  display.drawString(0, 43, "NO. of Satelites : "+SATELITES);
  display.drawString(0, 54, "Altitude Meters : "+ALTITUDE);
  display.display();
  }
  
  ///check if GPS Fixed or Not to send position to Server
  if(ALTITUDE!="0.00"){
    Send_position(Send_interval_str); //check for interval if reached then send position
    } 
  if ( !mqtt.connected() ) {
      reconnect();
    }
    if ( mqtt.connected() ) {
 mqtt.loop();}
 }
}
////////////////////////////////////////////////////////////end of Loop

//////////////////////////////////////////////Function to Startup GSM modem A6 
void RUN_GSMHW(){
  GSM_Serial.flush();
  delay(30);
  POWER_UP_A6();
   
 
///////////////////////initialize setup for GSM Modem
    if(modem.begin()=="true"){  
      Serial.println("Modem is initialized");
       display.drawString(0, 10, "Modem is Initialized");
       display.display();
       BUZZER(100,30,2);      //BUZZ  Delay BUZZ lenght100 ms  and silence length 30 ms ,2 time
    }else{
      Serial.println(modem.begin());
       display.drawString(0, 10, modem.begin());
       display.display();
       BUZZER(300,500,3);      //BUZZ  Delay BUZZ lenght 300 ms  and silence length 500 ms ,3 time
       delay(5000);
       ESP.reset();
    }
//////////////////////////////////////////Check if SIM CARD exists
    if(modem.getSimStatus()==SIM_READY){
      Serial.println("SIM Card is Ready");
      display.drawString(0, 21, "SIM Card is Ready");
      display.display();
      BUZZER(100,30,2);      //BUZZ Delay BUZZ lenght100 ms  and silence length 30 ms ,2 time
    }else{
       Serial.println(F("SIM Card is NOT Ready"));
       display.drawString(0, 21, (F("SIM Card is noT Ready")));
       display.display();
       BUZZER(300,500,3);      //BUZZ  Delay BUZZ lenght 300 ms  and silence length 500 ms ,3 time
       delay(5000);
       ESP.reset();
       return;
    }
///////////////////////////////////////Check mobile Network Status
       Serial.print("Waiting for network...");
       if (!modem.waitForNetwork()) {             
       Serial.println(" Failed");
       display.drawString(0, 32, "Failed Newtwork ");
       display.display();
       BUZZER(300,500,3);      //BUZZ  Delay BUZZ lenght 300 ms  and silence length 500 ms ,3 time
       delay(5000);
       ESP.reset();
       return;
  }
       BUZZER(100,30,2);      //BUZZ  Delay BUZZ lenght100 ms  and silence length 30 ms ,2 time
       display.drawString(0, 32, "Network OK");
       display.display();
       Serial.println(" OK");

  
  Serial.print("Connecting to ");
  Serial.print(apn);
  GSM_Serial.flush();
  delay(1000);
////////////////////////////////////////////////Connecting to GPRS DATA Service

  if (!modem.gprsConnect(apn,user,pass)) {
    Serial.println(" Failed");
    display.drawString(0, 43, "Failed APN Connect ");
    display.display();
       BUZZER(300,500,3);      //BUZZ  Delay BUZZ lenght 300 ms  and silence length 500 ms ,3 time
       delay(5000);
       ESP.reset();
       return;
  }
  
  BUZZER(100,30,2);      //BUZZ  Delay BUZZ lenght100 ms  and silence length 30 ms ,2 time
  Serial.println(" OK");
  
  
//  if(gps_mode=="AGPS"){Serial.print("Start AGPS"); modem.agps_start();}else{Serial.print("Start GPS");modem.gps_start();} //switch between AGPS Or GPS 
   digitalWrite(GPS_PWR_Pin ,HIGH); //turn GPS ON
   Serial.println(" OK");
   display.drawString(0, 43, "GPRS Connected All OK ");
        display.display();
        BUZZER(100,30,4);      //BUZZ  Delay BUZZ lenght100 ms  and silence length 30 ms ,2 time
        delay(2000);

        mqtt.setServer(thingsboardServer, 1883);// mqtt server again
        
}

////////////////////////////////////////////////////////////////////smart Function to Read all NMEA Responses and Encode them...
static void check_GPS(unsigned long ms)
{
  unsigned long startgps = millis();
  do 
  {
    while (GPS_Serial.available())
      gps.encode(GPS_Serial.read());
  } while (millis() - startgps < ms);
}

///////////////////////////////////////////////////////////function to check last Time sent GPS position to server
static void Send_position(String s)
{
  Send_interval=s.toInt();
if (millis() - startgprs >= Send_interval*1000){
  send_GPRS();
  startgprs = millis();
}
}

//////////////////////////////////////////////////////////////Function to Send Positions to Server
   void send_GPRS(){ 
    GSM_Serial.flush();
    delay(30);
    DynamicJsonBuffer jsonBuffer;
  JsonObject& json = jsonBuffer.createObject();
  json["latitude"] = latitude;
  json["Longitude"] = Longitude;
  json["ALTITUDE"] = ALTITUDE;
  json["SPEED"] = SPEED;
  json["COURSE"] = COURSE;
  json["HDOP"] = HDOP;
  json.printTo(payload);
  // Send payload
  mqtt.publish( "v1/devices/me/telemetry", payload.c_str());
  Serial.println( payload );
  payload = "";
} 
///////////////////////////////////////////////////////Function to Powerup A7 module
void POWER_UP_A6(){
   display.clear();
   display.drawString(0, 0, "Reseting Modem");
   Serial.println("");
   Serial.println(F("Reseting Modem"));
   display.display();
   delay(1000);
   modem.restart(); ////////Reboot Modem if  it's ON
  //delay(3000);
   GSM_Serial.flush();
   delay(1000);
   /* this codes are not needed for A6 mini module
  digitalWrite(GPS_PWR_Pin ,0);
  delay(3000);
  digitalWrite(GPS_PWR_Pin ,1);
   Serial.println("");
   */
    display.clear();
    display.drawString(0, 0, "Waiting for A6 Module..");
    Serial.println(F("Waiting for A6 Module to Start.."));
    display.display();
    delay(20000);            ///Wait for Modem  to compeletly  Boot
    GSM_Serial.flush();      //so important to flush Junk Data
    delay(1000);
}
/////////////////////////////////////////////////////////////////////////Buzzer Function 
void BUZZER(uint16_t timout1,uint16_t timout2,uint16_t count){
       for (int i=0;i<count;i++){
       digitalWrite(BUZZER_Pin,LOW);
       delay(timout1);
       digitalWrite(BUZZER_Pin,HIGH); 
       delay(timout2);
  }
}
///////////////////////////////////////////////////////Check incomig Call 
void checkcall(){
  
 
  if(GSM_Serial.available()){
    String number=modem.Check_call();
    
    if(number == "no_call"){
         
   
    return;
    }
    if(number == owner_number){  // this can check whether its owner or some body else
    Serial.println("Called Number accepted");
    delay(1000);
    //no needs for A6 mini module
     //modem.enableSpeaker(1); /// enable OUTPUT Speaker 
     // delay(1000);
     modem.callAnswer(); // answer the CALL 
      delay(500);
      if (digitalRead(switch_Pin)==LOW)
      {
        Switch_State="1";
        save_SW_state(); // save state of Switch_pin to SPIFFS
        digitalWrite(switch_Pin,HIGH); /////////this will turn on a relay then you can connect Between NC and Common pins of relay with NPN Transistor to switch off CAR 
        //BUZZER(150,100,5);/////////////////////////////to Sniffing silently inside the car you can omit this line
        display.clear();
        display.setFont(ArialMT_Plain_16);
        display.drawString(29, 10, "Relay ON");
        display.drawString(20, 26, "Call Answerd");
        display.display();  
      }else
      {
        Switch_State="0";
        save_SW_state(); // save state of Switch_pin to SPIFFS
        digitalWrite(switch_Pin,LOW); ///this will reverse relay
        //BUZZER(75,30,10);
             display.clear();
             display.setFont(ArialMT_Plain_16);
             display.drawString(29, 10, "Relay OFF");
             display.drawString(20, 26, "Call Answerd");
             display.display(); 
        }
       
        Wait_Response(3600000,response); //wait to disconnect
        GSM_Serial.println("ATH"+number);// to hang up phone
        delay(500);
        sendSMS(number,"your Device Location is :\n Latitude: "+latitude+"\n Longitude: "+Longitude); /////// send device location by SMS
              GSM_Serial.flush();
              delay(30);
   }else{
       display.clear();
       display.setFont(ArialMT_Plain_16);
       display.drawString(0,0,"Incoming CALL..");
       display.drawString(0,20,number);
       display.display();
       Serial.println("unauthorized number"+number);
       BUZZER(75,30,15);
        delay(1000);
 GSM_Serial.flush();
 delay(30);
    }
  }
}
 ////////////////////////////////////////////////////////Save Switch pin Status
void save_SW_state(){
    DynamicJsonBuffer jsonBuffer;
    JsonObject& json = jsonBuffer.createObject();
    json["SW"]=Switch_State;
    myFile = SPIFFS.open("/SW.TXT","w");
  if (!myFile) {
  Serial.println("Failed to open SW file ");
  return;
  }
  json.printTo(myFile);
  myFile.close();
}
////////////////////////////////////////////////////////////void to wait for Serial response  with TIMEOUT
void Wait_Response(uint32_t timeout,String& data){
 GSM_Serial.flush();
 delay(30);
  String c;
  unsigned long starttimeout = millis();
  while(GSM_Serial.available()<=0 ){
    if( millis() - starttimeout < timeout){
    yield();               ///////////////////////////////////this function prevent ESP8266 from reset
    }else{
    return;
    }
    }
    // Print available data
    while (GSM_Serial.available()>0) {
       data = GSM_Serial.readStringUntil('\n');
    }
   GSM_Serial.flush();
   delay(30);
}
//////////////////////////////////////////////function to send SMS easy
void sendSMS(String Number,String Text){
  GSM_Serial.println("AT+CMGS="+Number);
 Wait_Response(1000,response);
 GSM_Serial.println(Text);
 GSM_Serial.println((char)26); 
  Wait_Response(10000,response);
}

void reconnect() {
  // Attempt to connect (clientId, username, password)
  if ( mqtt.connect("ESP8266 Device", TOKEN, NULL) ) {
    Serial.println( "[DONE]" );
    mqtt.subscribe("v1/devices/me/rpc/request/+");  /////////////////////Telling server we are ready to receive RPC requests
  } else {
    Serial.print( "[FAILED] [ rc = " );
    Serial.print( mqtt.state() );
    delay(500);
  }
}

**Comment by forGGe** [comment]
@m0o0hammad , please, use proper formatting for the code. It is really hard to read your message.

Also, this:

```
const char apn[] = "your apn";
```

Looks really, really suspicious to me. It seems that you've misconfigured your modem. Also, more logs are required. You can debug your serial communication with a modem, like shown here: https://github.com/vshymanskyy/TinyGSM/blob/74a4bf5d4a6016597447ed5fc629b017dfe2e8f2/examples/HttpClient/HttpClient.ino#L59-L65 
This might give you some clues.

**Comment by m0o0** [comment]
Closes: #1320

**Comment by m0o0** [comment]
ok tnx @forGGe
