### ISSUE TITLE
urgent issue : How to solve "Widget Error : TypeError : self.ctx.valueCell.textWidth is not a function" for System Widget (Card) ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1324]
Hi,

We get the error of widget (Card) on TB PE 2.2.0 (upgrade from TB PE 2.1.3).
![2018-12-12 2 28 20](https://user-images.githubusercontent.com/11456776/49851455-19314980-fe1c-11e8-98ac-ee52f65bf0c9.png)
 
We don't understand why we get the error. We don't have any right to modify "System Widget".

How can we fix this issue ?

Regards,

Paul Wang

**Comment by paulwang55** [comment]
Hi,
I found another information through web browser's developer console.
Here is my screenshot image.
![2018-12-13 4 22 27](https://user-images.githubusercontent.com/11456776/49925466-fe320880-fef3-11e8-9850-1c4fcb5d02fa.png)

I just open the dashboard using "Simple Card" widget.
if I click the error message at "Delveloper console". (I am using Firefox Quantum - 63.0.3 64 bit on Mac OSX 10.13.6) I will see the following message.

**<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Dec 13 08:15:08 UTC 2018</div><div>There was an unexpected error (type=Not Found, status=404).</div><div>No message available</div></body></html>**

Can anyone know how to fix it ? What is it caused by ?

Regards,

Paul Wang

**Comment by gringet** [comment]
> We don't understand why we get the error. We don't have any right to modify "System Widget".

Can't you log as sysadmin ?

The error comes from the javascript code of the widget I think, could you post it ?

**Comment by paulwang55** [comment]
Hi gringet,

Here is javascript code copied from "Simple Card" (System Widget).

**self.onInit = function() {

    self.ctx.labelPosition = self.ctx.settings.labelPosition || 'left';
    
    if (self.ctx.datasources.length > 0) {
        var tbDatasource = self.ctx.datasources[0];
        var datasourceId = 'tbDatasource' + 0;
        self.ctx.$container.append(
            "<div id='" + datasourceId +
            "' class='tbDatasource-container'></div>"
        );
        
        self.ctx.datasourceContainer = $('#' + datasourceId,
            self.ctx.$container);
        
        var tableId = 'table' + 0;
        self.ctx.datasourceContainer.append(
            "<table id='" + tableId +
            "' class='tbDatasource-table'><col width='30%'><col width='70%'></table>"
        );
        var table = $('#' + tableId, self.ctx.$container);
        if (self.ctx.labelPosition === 'top') {
            table.css('text-align', 'left');
        }
        
        if (tbDatasource.dataKeys.length > 0) {
            var dataKey = tbDatasource.dataKeys[0];
            var labelCellId = 'labelCell' + 0;
            var cellId = 'cell' + 0;
            if (self.ctx.labelPosition === 'left') {
                table.append(
                    "<tr><td class='tbDatasource-data-key' id='" + labelCellId +"'>" +
                    dataKey.label +
                    "</td><td class='tbDatasource-value' id='" +
                    cellId +
                    "'></td></tr>");
            } else {
                table.append(
                    "<tr style='vertical-align: bottom;'><td class='tbDatasource-data-key' id='" + labelCellId +"'>" +
                    dataKey.label +
                    "</td></tr><tr><td class='tbDatasource-value' id='" +
                    cellId +
                    "'></td></tr>");
            }
            self.ctx.labelCell = $('#' + labelCellId, table);
            self.ctx.valueCell = $('#' + cellId, table);
            self.ctx.valueCell.html(0 + ' ' + self.ctx.units);
        }
    }
    
    $.fn.textWidth = function(){
        var html_org = $(this).html();
        var html_calc = '<span>' + html_org + '</span>';
        $(this).html(html_calc);
        var width = $(this).find('span:first').width();
        $(this).html(html_org);
        return width;
    };    
    
    self.onResize();
};

self.onDataUpdated = function() {
    
    function isNumber(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }

    if (self.ctx.valueCell && self.ctx.data.length > 0) {
        var cellData = self.ctx.data[0];
        if (cellData.data.length > 0) {
            var tvPair = cellData.data[cellData.data.length -
                1];
            var value = tvPair[1];
            var txtValue;
            if (isNumber(value)) {
                var decimals = self.ctx.decimals;
                var units = self.ctx.units;
                if (self.ctx.datasources.length > 0 && self.ctx.datasources[0].dataKeys.length > 0) {
                    dataKey = self.ctx.datasources[0].dataKeys[0];
                    if (dataKey.decimals || dataKey.decimals === 0) {
                        decimals = dataKey.decimals;
                    }
                    if (dataKey.units) {
                        units = dataKey.units;
                    }
                }
                txtValue = self.ctx.utils.formatValue(value, decimals, units, true);
            } else {
                txtValue = value;
            }
            self.ctx.valueCell.html(txtValue);
            var targetWidth;
            var minDelta;
            if (self.ctx.labelPosition === 'left') {
                targetWidth = self.ctx.datasourceContainer.width() - self.ctx.labelCell.width();
                minDelta = self.ctx.width/16 + self.ctx.padding;
            } else {
                targetWidth = self.ctx.datasourceContainer.width();
                minDelta = self.ctx.padding;
            }
            var delta = targetWidth - self.ctx.valueCell.textWidth();
            var fontSize = self.ctx.valueFontSize;
            if (targetWidth > minDelta) {
                while (delta < minDelta && fontSize > 6) {
                    fontSize--;
                    self.ctx.valueCell.css('font-size', fontSize+'px');
                    delta = targetWidth - self.ctx.valueCell.textWidth();
                }
            }
        }
    }    
    
};

self.onResize = function() {
    var labelFontSize;
    if (self.ctx.labelPosition === 'top') {
        self.ctx.padding = self.ctx.height/20;
        labelFontSize = self.ctx.height/4;
        self.ctx.valueFontSize = self.ctx.height/2;
    } else {
        self.ctx.padding = self.ctx.width/50;
        labelFontSize = self.ctx.height/2.5;
        self.ctx.valueFontSize = self.ctx.height/2;
        if (self.ctx.width/self.ctx.height <= 2.7) {
            labelFontSize = self.ctx.width/7;
            self.ctx.valueFontSize = self.ctx.width/6;
        }
    }
    self.ctx.padding = Math.min(12, self.ctx.padding);
    
    if (self.ctx.labelCell) {
        self.ctx.labelCell.css('font-size', labelFontSize+'px');
        self.ctx.labelCell.css('padding', self.ctx.padding+'px');
    }
    if (self.ctx.valueCell) {
        self.ctx.valueCell.css('font-size', self.ctx.valueFontSize+'px');
        self.ctx.valueCell.css('padding', self.ctx.padding+'px');
    }    
};

self.typeParameters = function() {
    return {
        maxDatasources: 1,
        maxDataKeys: 1
    };
};


self.onDestroy = function() {
};**

**Comment by paulwang55** [comment]
Hi,
Do anyone know how to fix this issue ? We are waiting for the solution.
It is an urgent issue for us. 
Is the issue  caused by upgrading TB PE 2.1.3 to TB PE 2.2.0 ?

Regards,
Paul Wang

**Comment by paulwang55** [comment]
Hi doranagy,

Thanks for your help. It works for me. This case can be closed.
