### ISSUE TITLE
Entity view UI labels not showing in 2.2.0

### ISSUE THREAD

**Issue by glancia** [thingsboard/thingsboard#1325]
Hi all,

I've just upgraded from 2.0.3 to 2.2.0 and everything seems to be working fine, except by the UI labels regarding the new feature Entity Views. Seems like a language file is missing (I'm using English).

Any clues?

Thanks

![image](https://user-images.githubusercontent.com/26585392/49860685-7360e900-fde1-11e8-83c4-93e1610eb78a.png)

**Comment by vparomskiy** [comment]
Try to clear browser cache and reload the page.

**Comment by glancia** [comment]
Great, that worked! Thanks
