### ISSUE TITLE
Kubernetes support for 2.2.0

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#1326]
Hi,
when moving from 2.1.3 to 2.2.0, the support for running thingsboard in kubernetes seems to be missing. Both from the config files that were available in the source as the documentation.

Would it be possible to add them again adjusted for using the microservice architecture?

Thanks.

**Comment by vparomskiy** [comment]
This task is in progress. For the current moment, only docker-compose scripts are available.

**Comment by yukiman76** [comment]
can I help ?, is there a working or in process branch ?

**Comment by absinthetized** [comment]
Just wondering if the "kompose" project can help here...

**Comment by Karabiy** [comment]
Those is available now. You may refer to this link regarding the cluster setup options: https://thingsboard.io/docs/user-guide/install/cluster-setup/
