### ISSUE TITLE
I can't subscribe to v1/gateway/attributes/response 

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard#1327]
When I subscribe to "v1/gateway/attributes" I receive the SUBACK packet
0x92 0x03 0x00 0x02 0x00
These is fine. The last byte means "success, QoS0 granted"

When I subscribe to "v1/gateway/attributes/response" I receive the SUBACK packet
0x92 0x03 0x00 0x02 0x80
The last byte means "Failure, not QoS granted". Although after that I am subscribed to the topic, various issues raised in Paho MQTT C client for embedded platform which I use.

**Comment by ashvayka** [comment]
Hi @Tasosgi . This is indeed a regression since v2.2 and we will fix in v2.2.1
