### ISSUE TITLE
finding data from postgresql

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#1329]
where can i find telemetry data in my postgresql database of thingsboard?

i'm using pgadmin, and i see the thingsboard db with casts, catalogs, event triggers, extensions, etc. but i haven't managed to find table/folder which includes the actual telemetry data.

also, it seems that i cannot use even the basic SQL queries withing pgadmin (but this may also be due my incompetence..)

**Comment by eykamp** [comment]
I don't know a thing about pgadmin, but I do know your telemetry data is in a table called ts_kv.

**Comment by gringet** [comment]
Servers -> local -> thingsboard -> Schemas -> Tables -> ts_kv

Then right click -> View/Edit Data -> All Rows
Or : right click -> Query Tool

A useful query would be : SELECT column_name1, column_name2 FROM public.ts_kv WHERE  column_name1=some_value

you can give a list of column_name or a * to select all.

**Comment by quirosaur** [comment]
thank you, i was able to query from the database. i cannot do "SELECT * FROM *", but it works if i specify the table.

**Comment by bnjmjs** [comment]
hais
