### ISSUE TITLE
can't build from source (version 1.2.2 release)

### ISSUE THREAD

**Issue by zhouylgithub** [thingsboard/thingsboard#133]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project transport: Compilation failure: Compilation failure:
[ERROR] E:\learn\thingsboard\thingsboard-1.2.2\common\transport\src\main\java\org\thingsboard\server\common\transport\adaptor\JsonConverter.java:[59,15] 错误: 无法将类 ToServerRpcRequestMsg中的构造器 ToServerRpcRequestMsg应用到给定类型;
[ERROR] 需要: 没有参数
[ERROR] 找到: int,String,String

**Comment by ashvayka** [comment]
Try latest version from master. It should work fine now
