### ISSUE TITLE
TB Behind NGINX can't activate new account

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#1331]
I have TB running on port http:8080 as usual and a nginx server at https://domain/ redirecting doing a proxy role. Everything works fine except the e-mail notification for a new user redirects the user to http://domain:80.
I have added couple of headers in the nginx setup and now it sends a link to http://domain:443. Notice the wrong protocol (http) which yield a bad request.
Here in my nginx configuration
<pre>
        location / {
                proxy_pass http://192.168.0.66:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header x-forwarded--proto https;
                proxy_set_header x-forwarded-port 443;
        }
</pre>

Any hint?

**Comment by ashvayka** [comment]
Please check haproxy configuration here: https://thingsboard.io/docs/reference/msa/#haproxy-or-other-loadbalancer for some hints on missing headers or rules, etc

**Comment by ikulikov** [comment]
There is typo in 'x-forwarded--proto', should be 'x-forwarded-proto'.
