### ISSUE TITLE
[Feature request] : previous value/ts of window

### ISSUE THREAD

**Issue by gringet** [thingsboard/thingsboard#1332]
For the data post-processing, could we get the previous value/ts of the current window ? It's particularly useful when you want to plot the differential of a time series. For now you have to omit the first value of the window since the previous value/ts of it is 0.

**Comment by ashvayka** [comment]
This was added in v2.2

**Comment by gringet** [comment]
I might be wrong but the v2.2 doesn't have this feature. What I want is the previous value/ts of the window itself. Meaning if I aggregate my data from 2PM to 4PM, I want the first value/ts that comes before 2PM.

For now the value/ts before the timewindow isn't retrieved.

**Comment by vparomskiy** [comment]
If you need previous value/ts the only way is to change time window to the range that will include previous ts.

**Comment by PovitruliaV** [comment]
Hi @gringet,
Are your problem is still relevant?
