### ISSUE TITLE
inactivityTimeout does not trigger inactivity event

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#1334]
I did this tutorial:
[(https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/)]
using a real device connected via LoRaWAN. 
I set the serverAttribute "inactivityTimeout" to 240000 ms so 4minutes. 
But after this 4 minutes the server attribute "active" stays true (forever) and therefore no inactivity Event is triggered. If I change the inactivityTimeout manually the server attribute "active" changes to false or true, depending on the new value I set. Why is this not automatically happening? Am I missing a point?
![printscreen_inactivity_timeout](https://user-images.githubusercontent.com/45274753/49996308-f8d5cc00-ff8e-11e8-8453-ba53c8bd0030.JPG)

**Comment by ashvayka** [comment]
May sound like a stupid question but are you sure you are triggering refresh icon? The page doesn't automatically update itself.

**Comment by ThomasBaumgartner** [comment]
Yes I did. I even checked in the root rule chain if an inactivity event is triggered after the inactivityTimeout. But it isnt't.

**Comment by vparomskiy** [comment]
does your device connect via http or mqtt API?

**Comment by ThomasBaumgartner** [comment]
Integration type is TheThingsNetwork, so I assume it is connected via MQTT.

**Comment by ThomasBaumgartner** [comment]
Problem was in the configuration properties. The state.defaultStateCheckIntervallInSec was set to 3600s. Therefore Thingsboard just made the inactivityCheck once an hour. I changed this parameter to a reasonable value and now everything works like expected. 

![inactivityTimeout png](https://user-images.githubusercontent.com/45274753/62608053-6dcf8a80-b8ff-11e9-9749-3e7333bb3ce8.jpg)

**Comment by JohnEspinosaHans** [comment]
> Problem was in the configuration properties. The state.defaultStateCheckIntervallInSec was set to 3600s. Therefore Thingsboard just made the inactivityCheck once an hour. I changed this parameter to a reasonable value and now everything works like expected.
> 
> ![inactivityTimeout png](https://user-images.githubusercontent.com/45274753/62608053-6dcf8a80-b8ff-11e9-9749-3e7333bb3ce8.jpg)

Are you using Professional Edition and if yes, how did you find the configuration properties?

**Comment by okridgway** [comment]
Where did you find these settings?
