### ISSUE TITLE
Update DeepSleep time with RCP

### ISSUE THREAD

**Issue by marianodo** [thingsboard/thingsboard#1336]
Hi
I'm using the module ESP12 connected to a battery so I have to configure the ESP.deepSleep.
My question is how can I change the time of deepsleep with Thingsboard? (I want to store the time in the eeprom).
I tried using RCP command but if my device is sleep, it doesn't receive the command.

Any suggestion? 
Thanks

**Comment by nmenoni** [comment]
Maybe you can check a shared attribute every time ESP12 wakes up.

**Comment by forGGe** [comment]
> I tried using RCP command but if my device is sleep, it doesn't receive the command.

That's how WiFi works. When in deep sleep your **WiFi radio is OFF**. You wouldn't able to receive any data at all (no matter it is ThingsBoard or not).

So either do as https://github.com/thingsboard/thingsboard/issues/1336#issuecomment-447421414 recommends: wakeup after some period and read shared attributes 

-OR-

Use other power-saving method, where your WiFi radio will be listening for some data from router.
