### ISSUE TITLE
Can’t reach web ui localhost:8080 after new installation

### ISSUE THREAD

**Issue by skjolddesign** [thingsboard/thingsboard#1339]
After successfull install, I cant reach web ui on localhost:8080.
cmd log says thingsboard started successfully, but it's not working.
Tried thingsboard uninstall, and install again. Tried Java uninstall and install again.
I tried install on another computer also, but not working there either. Please help.
My system is: Windows 10(64), Java 8.191(86), Thingsboard 2.2.
Only modification I have done in thingsboard files, is to remove     <startargument>-XX:+UseCondCardMark</startargument> in thingsboard.xml, or else I got error 1067 when starting thingsboard.

Here is complete log files:
[cmd log](https://pastebin.com/Z2cfj1gV)
[thingsboard.xml](https://pastebin.com/RqdnG4PR)
[thingsboard.yml](https://pastebin.com/yZ03TxQS)
[thingsboard.err.log](https://pastebin.com/nB9Gyi66)
[thingsboard.log](https://pastebin.com/q2J5ZRpg)

**Comment by skjolddesign** [comment]
Well, found a solution after third round on this thing. 
Port 1883 and 9001 was already in use by Node.js.
[This post was spot on](https://groups.google.com/forum/#!topic/thingsboard/xGruXQL75sQ):
> Hi, I am able to observe following message: "Caused by: java.net.BindException: Address already in use: bind"
> This is possible if one of the ports that TB uses is already used by other application/service.
> Check following ports: 1883, 8080, 5683 and 9001 in case of cluster mode.
> Also, this is possible if you want to start second instance when first one is already running on the same node.
> Regards,
> Andrew

[This post helped me find process using the ports.](https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/)

It would be nice if `net start thingsboard` command, gave an error about this.

**Comment by Nitheshnithu121** [comment]
I have successfully install mainflux CE server on aws EC2 instance using Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0b44050b2d893d5f7 (64-bit x86) / ami-0dc231c09aef801ea (64-bit Arm)
Now i am not able open the thingsboard login page using http://public ip:8080 port ,can any one help me to solve this problem

**Comment by AWangji** [comment]
> Well, found a solution after third round on this thing.
> Port 1883 and 9001 was already in use by Node.js.
> [This post was spot on](https://groups.google.com/forum/#!topic/thingsboard/xGruXQL75sQ):
> 
> > Hi, I am able to observe following message: "Caused by: java.net.BindException: Address already in use: bind"
> > This is possible if one of the ports that TB uses is already used by other application/service.
> > Check following ports: 1883, 8080, 5683 and 9001 in case of cluster mode.
> > Also, this is possible if you want to start second instance when first one is already running on the same node.
> > Regards,
> > Andrew
> 
> [This post helped me find process using the ports.](https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/)
> 
> It would be nice if `net start thingsboard` command, gave an error about this.

But you didn't say how to solve it. Just stop the process which uses port 1883? I checked that and found that the java.exe was using, so what should i do?

**Comment by skjolddesign** [comment]
The easy answer, I installed a clean ubuntu server virtual machine, and installed Thingsboard there.

The more timeconsuming route, is to know your system in use ports, and know what ports your new application want to use.
If port conflict, you need to edit port number in one of the conflict application config files.

**Comment by AWangji** [comment]
Could you please introduce the details to about answer1? actually i had tried the answer2, but it did not work. Thank you.



---Original---

**Comment by skjolddesign** [comment]
> 
> Could you please introduce the details to about answer1? actually i had tried the answer2, but it did not work. Thank you.
>

Here is Thingsboard installation:
[https://skjoldtech.wordpress.com/2019/03/02/thingsboard-on-ubuntu-server-18-04](https://skjoldtech.wordpress.com/2019/03/02/thingsboard-on-ubuntu-server-18-04)

I recommend reading the other Linux topics here:
[https://skjoldtech.wordpress.com/linux](https://skjoldtech.wordpress.com/linux)

If this not helps, Youtube is your friend.
