### ISSUE TITLE
Compile faild and get error  "Missing artifcat com.sum:tools:jar 1.4.2"  in Eclipse Version 2018-09(4.9.0)

### ISSUE THREAD

**Issue by seamine** [thingsboard/thingsboard#1340]
Compile faild and get error  "Missing artifcat com.sum:tools:jar 1.4.2"  in Eclipse Version 2018-09(4.9.0)

The error string is Missing artifact com.sun:tools:jar:1.4.2

OS: Windows 10 Pro x64 
JDK: jdk1.8.0_151

In stackoverflow.com has a solution
add following lines in application/pom.xml 
`
 <dependency>
   <groupId>com.sun</groupId>
   <artifactId>tools</artifactId>
   <version>1.6</version>
   <scope>system</scope>
   <systemPath>C:\Program Files\Java\jdk1.8.0_151\lib\tools.jar</systemPath>
 </dependency>
`
the second solution is:
eclipse add startup arguments 
`-vm "T:\Program Files\Java\jdk1.6.0_26\bin"`
but has no effect

Do you have other choices that no need to update application/pom.xml

**Comment by vparomskiy** [comment]
It is a problem of the Eclipse IDE.
`-vm "T:\Program Files\Java\jdk1.6.0_26\bin"`
 adjust that to point to the bin directory of your JDK install
