### ISSUE TITLE
ThingsBoard installation failed!

### ISSUE THREAD

**Issue by AndreyArduino** [thingsboard/thingsboard#1343]
Hello!
Debian 9
PostgreSQL 9.6
Java 8 
Selection    Path                                     Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-oracle/jre/bin/java   1081      auto mode
* 1            /usr/lib/jvm/java-8-oracle/jre/bin/java   1081      manual mode

Everything works fine with HSQLDB config. But with PostgreSQL when I try installing ** / usr / share / thingsboard / bin / install / install.sh --loadDemo ** I get the error ** ThingsBoard installation failed! **
I change file ** / etc / thingsboard / conf / thingsboard.yml ** as recomended in ** Installing ThingsBoard on Linux ** and setup username and password for PostgreSQL

`/usr/share/thingsboard/bin/install/install.sh --loadDemo
22:08:00,781 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:08:00,782 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:08:00,783 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
22:08:00,787 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
22:08:00,787 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.2.0.jar!/logback.xml]
22:08:00,787 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
22:08:01,225 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
22:08:01,227 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
22:08:01,256 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
22:08:01,292 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@20929316 - setting totalSizeCap to 3 GB
22:08:01,311 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@20929316 - Archive files will be limited to [100 MB] each.
22:08:01,385 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@20929316 - No compression will be used
22:08:01,387 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@20929316 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
22:08:01,394 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1aeb7ab - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
22:08:01,394 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1aeb7ab - Roll-over at midnight.
22:08:01,409 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@1aeb7ab - Setting initial period to Mon Dec 17 22:08:01 MSK 2018
22:08:01,413 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
22:08:01,464 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
22:08:01,464 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
22:08:01,466 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
22:08:01,466 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
22:08:01,466 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
22:08:01,466 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
22:08:01,467 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:08:01,468 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@123ec81 - Registering current configuration as safe fallback point

ThingsBoard installation failed!`

thingsboard.log is empty. 
database thingsboard exists
What could be my problem?

**Comment by AndreyArduino** [comment]
Reinstalled all with OpenJDK. Now  thingsboard work very well. Question closed.

**Comment by ajsarh** [comment]
I'm having the same issue. Can you please explain how you solved the issue ?
