### ISSUE TITLE
Problem with webpack.config.prod.js

### ISSUE THREAD

**Issue by mariojfduarte** [thingsboard/thingsboard#1345]
Whenever I run the command 

`npm run build`

I get a blank screen. I am trying to deploy a customized version on AWS EC2 using a Dockerfile as follows:

`FROM node:10.8.0
ENV FORWARDHOST='104.196.24.70' FORWARDPORT=80
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . . 
EXPOSE 3000
CMD ["npm","start"]
`

Any tips?

**Comment by ban2derlog** [comment]
hi, white screen issues on web ui are fixed on latest versions.
