### ISSUE TITLE
originator telemetry cuts data if they are too many but no warning is exposted to user

### ISSUE THREAD

**Issue by absinthetized** [thingsboard/thingsboard#1346]
- I've tried to load and inject latest 24 hours of telemetry into a message via an originator->script rule chain

- originator was set to start:24h, end 1:millisec

- I've noticed into the debug window that the latest passed telemetry was a lot BEFORE the current date and time. reducing the timeframe I've slowly reached the lastest millisec.

- basically it was stopping providing telemetry _hours_ before the current date and time. by slowly reducing the window frame I managed to reduce the gap between the lastest provided value and the latest millisec.

- in my case - with my telemetry frequency- I've got a safe hack by requiring no more than 30 mins (start 30 minutes, end: 1millisec)

- while this can be comprehensible, a debug with an error would be nice!

employed version: 2.2.1, I'm using the online demo

**Comment by ashvayka** [comment]
I have added a comment to the rule node details about this limit (1000 records). Sorry for the inconvenience. Will be part of v2.2.1 release.
