### ISSUE TITLE
docker haproxy

### ISSUE THREAD

**Issue by CHNEG8805** [thingsboard/thingsboard#1347]
deploy tb2.2 in microservices model.the haproxy container can not up.it always restarting

**Comment by CHNEG8805** [comment]
when i up haproxy the i login http://{my-host-ip} show 503

**Comment by CHNEG8805** [comment]
![image](https://user-images.githubusercontent.com/9719612/50379567-c8291d00-0687-11e9-8115-675444354649.png)

**Comment by CHNEG8805** [comment]
may be tb-web-ui service can not up?

**Comment by ashvayka** [comment]
Hi! Have you done any local changes or local build?

**Comment by CHNEG8805** [comment]
i have no change the config.when i use centos7.3 run docker have no peoblem. when i use docker for windows have this problem

**Comment by raheem52** [comment]
Where you able to solve this @CHNEG8805 ?

**Comment by CHNEG8805** [comment]
may be my haproxy congig error

**Comment by SerhiiLutchenko** [comment]
You can use the latest version of the ThingsBoard.
Here is the link for the microservices installation guide:
https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/
