### ISSUE TITLE
how to change the font-color of text from white to other color in thingsboard ?

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1348]

**Comment by dvk2018** [comment]
I guess you need to change the value of [the $grey variable]( https://github.com/thingsboard/thingsboard/blob/90643f397c1a83ea9d6b058af80592bc9c6bbc48/ui/src/scss/constants.scss#L20) and rebuild project.
Also PE version of TB can do it for you dynamically.

**Comment by gjweppler** [comment]
I have the PE version- how do you change the font color there?

**Comment by davidsean** [comment]
I also have the PE version, and would like to know how to change the text color.
