### ISSUE TITLE
Is the thingsboard-gateway project alive?

### ISSUE THREAD

**Issue by dvk2018** [thingsboard/thingsboard#1350]
Hi TB team (@ashvayka , @ikulikov , @vparomskiy and other good guys)
First of all, thanks for the great job what you are doing!
I am interesting in is the TB gateway is being supported by you? I am asking because now it is so difficult or even unreal to get some feedback on issues or pull requests for the gateway project.

**Comment by ashvayka** [comment]
Hi @dvk2018 , according to our roadmap, improvement to IoT Gateway is planned in parallel with v2.4 development. We are quite busy with new features in ThingsBoard now, but we plan to either improve Java version of the IoT Gateway or completely rewrite it to python in Q1-Q2 2019. Stay tuned!
