### ISSUE TITLE
Run thingsboard with Nginx proxy

### ISSUE THREAD

**Issue by guru2088** [thingsboard/thingsboard#1351]
Hi,

We want to setup thingsboard and Nginx proxy with a subpath

mydomain/tb/login
mydomain/tb/home

How can we do this ?

**Comment by IvanSemenenko** [comment]
Hi guru2088,

To setup, thingsboard follow the guide below:
https://thingsboard.io/docs/installation/

for using nginx as a proxy server read articles,
that fetching your favorite search engine by request:
**how to configure nginx proxy** :-).

Regards,

**Comment by vishalforcode** [comment]
nginx conf :

location /thingsboard/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_pass http://thingsboard:9090/;
   }
but it redirects to domain/login..i want i to be domain/thingsboard/login
please help me identify what i am doing wrong?

**Comment by wuyuepku** [comment]
the same problem...

**Comment by fidabhittani** [comment]
did anyone found a solution for this?
I am running TB in docker container, I proxied to TB from nginx, and the js bundles it loads shows `unexpected token <`, Dont know why, I fear the paths are not resolved correctly?

**Comment by micafer** [comment]
I have the same problem.

**Comment by harryjubb** [comment]
Also the same here.

ThingsBoard is clearly expecting to be run at the root URL path of the domain that it is hosted on. I am trying to host with nginx on a sub path: but ThingsBoard tries to load static assets from the root of the domain, and so the web interface can't load. 

I have looked through the [configuration variables](https://thingsboard.io/docs/user-guide/install/config/) for TB and haven't seen anything that looks like configuration for hosting TB on a sub path. Is this possible?

**Comment by melvinisken** [comment]
Same problem here. The only workaround was to move to a different subdomain instead of a sub path. Took me quite some time to debug the issue why everything was working except thingsboard.

**Comment by jasine** [comment]
same issue

**Comment by BAslan1988** [comment]
Any Updates on this topic?
Because i encounter same problems as op.

**Comment by BAslan1988** [comment]
> 

Is there any Configuration parameter out there yet for @harryjubb statement by now? Our Company uses traefik for proxying http request (such as thingsboard http) to https and creating subpathes etc. And thingsboard tries to use Root URL path of the Hostsystem.

I configured traefik as follows:

```   
labels:
      - traefik.enable=true
      - traefik.http.routers.tb.rule=PathPrefix(`/thingsboard{regex:$$|/.*}`)
      - traefik.http.services.tb.loadbalancer.server.port=9090
      - traefik.http.routers.tb.tls=true
      - traefik.http.routers.tb.middlewares=tb-redirectscheme
      - traefik.http.routers.tb.middlewares=tb-stripprefix
      - traefik.http.middlewares.tb-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.tb-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.tb-stripprefix.stripprefix.prefixes=/thingsboard/
      - traefik.docker.network=proxy```
