### ISSUE TITLE
thingsboard REST API rulechain

### ISSUE THREAD

**Issue by rmvpaps** [thingsboard/thingsboard#1364]
Hi,
I was trying to create a rule chain using the REST API.I want to be able to dynamically change rule filters.  I could not find any documentation regarding this other than the swagger doc. I first create rulechain using api/ruleChain. Then I try to add nodes using /api/ruleChain/metadata. It gives 200 response but the returned value always sets nodes field to null.
Create rulechain:
POST /api/ruleChain
{
  "id": {
    "entityType": "RULE_CHAIN",
    "id": "2c2f8bd0-0a6c-11e9-81d0-9de33a5e53d7"
  },

  "tenantId": {
    "entityType": "TENANT",
    "id": "6ff13190-0740-11e9-b37a-7f47a922a1b8"
  },
  "name": "api rulez 1",
  "firstRuleNodeId": {
    "entityType": "RULE_NODE",
    "id": "2c2fb2e0-0a6c-11e9-81d0-9de33a5e53d8"
  },
  "root": false,
  "debugMode": false,
  "configuration": null
}
This creates a rulechain. Now I try to add metadata to this rulechain
POST /api/ruleChain/metadata
{
  "connections": [
  ],
  "firstNodeIndex": 0,
  "nodes": [
    {
      "additionalInfo": null,
      "configuration": null,
      "debugMode": true,
      "id": {
        "id": "2c2fb2e0-0a6c-11e9-81d0-9de33a5e53d8",
		"entityType": "RULE_NODE"
      },
      "name": "rtestnode",
      "ruleChainId": {
		  "entityType": "RULE_CHAIN",
        "id": "2c2f8bd0-0a6c-11e9-81d0-9de33a5e53d7"
      },
      "type": "org.thingsboard.rule.engine.filter.TbJsFilterNode"
    }
  ],
  "ruleChainConnections": [

  ],
  "ruleChainId": {
    "id": "2c2f8bd0-0a6c-11e9-81d0-9de33a5e53d7",
	 "entityType": "RULE_CHAIN"
  }
}
This does not give any error but the response has nodes empty
{
  "ruleChainId": {
    "entityType": "RULE_CHAIN",
    "id": "2c2f8bd0-0a6c-11e9-81d0-9de33a5e53d7"
  },
  "firstNodeIndex": null,
  "nodes": [],
  "connections": null,
  "ruleChainConnections": null
}

Is this the right method? Hope you can tell me what I am doing wrong.

**Comment by volodymyr-babak** [comment]
Rule chain metadata is not a public API, it's the internal structure of the ThingsBoard platform, and the way how its stored can be changed between releases.
You can use this endpoint to import/export rule chains from one ThingsBoard platform to another, but it's not designed that you are going to add new rule nodes with a help of third-party script.
If you'll really need it, here is the source code, that is responsible for processing incoming rule chain metadata JSON:
https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java#L136
You can review saveRuleChainMetaData method and use similar login in your custom third-party tools.
But again, there is no guarantee that this will work between releases.
If you'll implement the logic for **3.3.3** release, there is only a guarantee, that it will compatible with **3.3.3** ThingsBoard release.
