### ISSUE TITLE
How to fix a corrupt cassandra table

### ISSUE THREAD

**Issue by azrin1972** [thingsboard/thingsboard#1366]
Hi, 
Yesterday I had an issue with my Cassandra where the system indicated it cannot find the database. Upon restarting the VM's TB is back online but I'm having issue where the customer and the dashboard data is missing. When I try to delete the customers and dashboards, I received a 404 error like the ones below:

<img width="667" alt="screenshot 2018-12-28 at 18 26 39" src="https://user-images.githubusercontent.com/5212844/50512748-b358e900-0ace-11e9-81a3-a53e8e120ae7.png">

<img width="687" alt="screenshot 2018-12-28 at 18 24 40" src="https://user-images.githubusercontent.com/5212844/50512753-b9e76080-0ace-11e9-8f9f-37e6a93835b0.png">

I've tried to create a new customer but when I create a user with the same email, I received and error saying user already exists.

<img width="739" alt="screenshot 2018-12-28 at 18 41 16" src="https://user-images.githubusercontent.com/5212844/50513102-99b8a100-0ad0-11e9-8f54-014933bc0098.png">

It seems like it is a referencing issue and I would like to change/delete the references manually but I do not know where to begin.

Since data has been collected for more than a year now, and I would very much wanting to preserve the data. Please advise on what I should do

Thank you

**Comment by ashvayka** [comment]
Please review the DB structure and TB code and browse the logs to understand what went wrong.

**Comment by azrin1972** [comment]
Hi @ashvayka 

Thanks for responding. I've been going through the DB manually and still figuring out the structure.
Where Can I get the reference to the DB structure? I can access the Cassandra DB but I do not have the table relation.

I went through the database table and saw the Dashboard somehow has different id as compared to the one TB is pointing to. Does TB has another table to keep the references for the Dashboard UIs? I ask is because when I manually delete the row, the dashboard is till in TB.

**Comment by Ultrazombie** [comment]
Please reopen if the question is still relevant
