### ISSUE TITLE
enhancement: use attribute for time series title

### ISSUE THREAD

**Issue by DanwithArduino** [thingsboard/thingsboard#1367]
I would like the name of the widget to be dynamic based off of some attribute or telemetry data from the device. As far as I can tell, there is no provision for that, currently. If i change the data name on the device, at present, it would require setting the widget to the new name, in an ideal scenario the user would be able to change the widget name on the device and see that change reflected on the widget/dashboard.

**Comment by gopirathnamt** [comment]
i Can try to create the new widget asper ur requirement

**Comment by gopirathnamt** [comment]
i created it

**Comment by gopirathnamt** [comment]
![screenshot from 2019-01-03 17-23-54](https://user-images.githubusercontent.com/36095688/50636714-3a014080-0f7d-11e9-9f03-db35698f2964.png)
![screenshot from 2019-01-03 17-24-04](https://user-images.githubusercontent.com/36095688/50636715-3a99d700-0f7d-11e9-8526-cacfa2ab404f.png)
![screenshot from 2019-01-03 17-24-16](https://user-images.githubusercontent.com/36095688/50636716-3a99d700-0f7d-11e9-9fd9-1b157ad5b7a5.png)
![screenshot from 2019-01-03 17-24-20](https://user-images.githubusercontent.com/36095688/50636717-3a99d700-0f7d-11e9-8450-99885a490bdc.png)

**Comment by luPhz** [comment]
This should be sufficient in a widget.

`self.onInit = function() {
    // Get the title from attributes
    let title = /* ... */

    self.ctx.widgetConfig.title = title;
};`

I'm having a hard time to come up with a use-case for this. Are you sure that this is not abuse of the widget title? You can hide the title and display anything you need inside of the widget.

**Comment by alexsmartens** [comment]
Hi @DanwithArduino,
I am having a similar issue #1737. Have you figured out how to use attributes in a timeseries widget?
