### ISSUE TITLE
Captcha error on registration

### ISSUE THREAD

**Issue by LockiStrike** [thingsboard/thingsboard#1374]
I tried to register an account on the live demo server and got an error that email is already used. So I changed the email to another and leave all other fields untouched and on the second submit I got a new error about captcha:

![image](https://user-images.githubusercontent.com/22641574/50586463-350b9680-0e82-11e9-9f01-1e45951bcb87.png)

**Comment by ashvayka** [comment]
I was able to successfully register with a dummy account. Please execute full browser refresh and double-check.

**Comment by ashvayka** [comment]
@LockiStrike please reopen the issue if problem persists
