### ISSUE TITLE
How to use postgresql via ssl

### ISSUE THREAD

**Issue by rggmmiranda** [thingsboard/thingsboard#1375]
Hi,

I am running a TB instance in a GCE virtual machine, and a postgresql DB from GCE as well.

The DB gives me the option to only allow ssl connections, which as I read is the right thing to do, but I am a bit new into this, especially ssl, so my question is: How do I configure thingsboard to work with the DB with ssl?

Without SSL it is working correctly, but if I enable it thingsboard doesn't start.

Thanks

**Comment by ashvayka** [comment]
See some useful comments on the best website: https://stackoverflow.com/questions/11832361/how-to-setup-spring-heroku-postgres-ssl-datasource

**Comment by ashvayka** [comment]
we use spring boot so you can check how to configure spring data to use ssl with postgresql. Please share the results of your findings.

**Comment by rggmmiranda** [comment]
@ashvayka, Thanks for your answer.
Sorry for the late response, I've been away for the last 10 days.
Can you provide a more detailed explanation, I'm not in the knowledge level to implement the solution based on that information.
As you mentioned to share the results of my findings, is this solution something that is supposed to work after configured properly or could it not work?
Why isn't there any Thingsboard official explanation for this matter? Is what I am doing an unncommon/non-practical solution for my thingsboard implementation? Because I do not see it very convinient to use the database connection without SSL.

**Comment by rggmmiranda** [comment]
After a lot of digging I was able to solve it.

GCE provides you with 3 things `client-cert.pem` `client-key.pem` `server-ca.pem` 
the client key must be converted to pk8 with the following command:
`sudo openssl pkcs8 -topk8 -inform PEM -outform DER -in client-key.pem -out client-key.pk8 -nocrypt`

These files must be saved somewhere in the server that is running TB, the folder I used was `/etc/thingsboard/conf/keystore/` since I was already using it for something else (This folder was created)

The key will not be accesible by TB so the correct privileges must be given:
`chmod o+r /etc/thingsboard/conf/keystore/client-key.pk8`

In the POSTGRESQL section in the file `/etc/thingsboard/conf/thingsboard.yml` the following information must be used in the URL line:
`url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://DATABASEIP:5432/thingsboard?sslmode=verify-ca&sslrootcert=/etc/thingsboard/conf/keystore/server-ca.pem&sslcert=/etc/thingsboard/conf/keystore/client-cert.pem&sslkey=/etc/thingsboard/conf/keystore/client-key.pk8}"`

"Allow SSL conections only" should be configured in the GCE DB

**Comment by rjswal** [comment]
@rggmiranda  - thanks for the detailed steps . I came across your question and corresponding solution.
Somehow; when i tried the same with thingsboard.yml, its not working.

My config is below -
# SQL DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ioc?sslmode=true&sslrootcert=/etc/thingsboard/conf/keystore/root.crt&sslcert=/etc/thingsboard/conf/keystore/server.crt&sslkey=/etc/thingsboard/conf/keystore/server.pk8}"
    hikari:
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:50}"
