### ISSUE TITLE
unable to find user by email

### ISSUE THREAD

**Issue by nikitas1974** [thingsboard/thingsboard#1383]
HI,

I am very new with thingsboard services. I try to use thingsboard with raspberry PI 3 B in order to make an IoT project, and after installation procedure, I tried to open Web UI using the link: http://localhost:8080/. When I saw the login window, I tried to do login (with my email address which I have already access in my account in live demo) but I failed (Authentication failed). When I issue the following command in order to check if there are any errors on the backend side: cat /var/log/thingsboard/thingsboard.log | grep ERROR, then I got this message: 2019-01-07 08:00:00,000 [http-nio-0.0.0.0-8080-exec-6] ERROR o.t.server.controller.BaseController - Error [Unable to find user by email [this is my email]]. Also I tried to do login with username: tenant@thingsboard.org and password: tenant, but I have the same result (Authentication failed). What is wrong?

Thanks

**Comment by ekinbukulmez** [comment]
Hello! Have you tried using the sysadmin login? 

username: sysadmin@thingsboard.org
password: sysadmin

**Comment by nikitas1974** [comment]
It works! 

@ekinbukulmez, Thanks a lot!

**Comment by monalimng** [comment]
I tried to do login with username: sysadmin@thingsboard.org and password:sysadmin , but I have the same result (Authentication failed). What is wrong?

**Comment by monalimng** [comment]
I tried to do login with username: tenant@thingsboard.orgpassword: tenant & sysadmin@thingsboard.org pwd- sysadmin and , but I have the same result (Authentication failed). What is wrong?
