### ISSUE TITLE
You must confirm that you are not a robot

### ISSUE THREAD

**Issue by ycy1991** [thingsboard/thingsboard#1386]
![image](https://user-images.githubusercontent.com/16506338/50877199-c68f8100-140b-11e9-81a6-fb771cd9b67b.png)

**Comment by ycy1991** [comment]
how to register account?

**Comment by vparomskiy** [comment]
Please retry. We had problems with sign-up form but now they are resolved.

**Comment by ycy1991** [comment]
thinks a lot ,I have retried  many times,but have the same result,and then ,I am login by sysadmin,the result is
![image](https://user-images.githubusercontent.com/16506338/51162053-c7bf2300-18cf-11e9-9e9d-4a6927b7dcc7.png)

**Comment by wuyunge** [comment]
I have same problem —— can't  sign up before confirm that i am not a robot .
