### ISSUE TITLE
change originator not working

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#1388]
i'm trying to change my message originator according to message. message is from device and target originator is also device. i have tried both "from" and "to", "contains" and "manages". if i then view the metadata, nothing has changed. why is this? 

also, when i try to load telemetry after "changing the originator", it doesn't work.

thanks in advance, Samu

**Comment by mp-loki** [comment]
You need to make sure that you create a relation between two devices first before using "change originator"

**Comment by quirosaur** [comment]
i have made relations, and they are visible. currently i have done/ bypassed this by using "related attributes"- node. relation query works in this, and gives correct data. but "change originator" and "originator telemetry"- nodes won't work. i checked the log file and it showed errors regarding MQTT pipe or something. (mqtt sending from rule chain works)

**Comment by angovil** [comment]
I am facing same issue..@quirosaur were you able to solve the issue?

**Comment by quirosaur** [comment]
@angovil acrually, i moved ftom thingsboard to home assistant and node-RED. i can't recall what was the cause of this problem but i thing it had something to do with the relation query. propably it was just configured wrong. So, i'll suggest to read the documentation again and double check the relations. AND remember to check the direction of relations (to/from). You can also make custom relations, it was useful to my solution at least.

**Comment by Zaris001** [comment]
Has anyone got this working?
Create realtion creates a new device and relation, but it does not change originator. Any working example?
