### ISSUE TITLE
Getting error when inject Google Blockly to thingsboard

### ISSUE THREAD

**Issue by phucluke** [thingsboard/thingsboard#139]
Hi team,

I'm customizing the thingsboard by adding Google Blocky. First, I used npm packages such as node-blockly but not luck because of issue with the webpack.
Then I try to include the Blockly scripts from external site and create a blockly directive so I can inject it to the view. But getting an error in the browser console: **Error: [$injector:unpr] Unknown provider: BlocklyProvider <- Blockly <- tbBlocklyDirective**
![image](https://cloud.githubusercontent.com/assets/11606840/26162007/be5c5594-3b4f-11e7-87ec-ad17b8bc91c1.png)

Could you please advise the issue? Thanks.

**Comment by nvphuc1989** [comment]
I got it working but still looking for a way to **import** local Blockly libraries using webpack. Do you have any suggestion?

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
