### ISSUE TITLE
How to add SVG file to my local server?

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1392]
I need to install the files to change the logo for this solution?
Thankful

**Comment by m0o0hammad** [comment]
When I enter the following command in path[extract clone] , I encounter the following 
mvn clean install -DskipTests
[ERROR] Failed to execute goal on project http: Could not resolve dependencies for project org.thingsboard.transport:http:jar:2.2.1-SNAPSHOT: Failed to collect dependencies at com.sun.winsw:winsw:exe:bin:2.0.1: Failed to read artifact descriptor for com.sun.winsw:winsw:exe:bin:2.0.1: Could not transfer artifact com.sun.winsw:winsw:pom:2.0.1 from/to jenkins (http://repo.jenkins-ci.org/releases): Access denied to: http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/2.0.1/winsw-2.0.1.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :http

**Comment by asnik** [comment]
I just substitute svg files with new logo and rebuild TB. Note: Have to remove any xml tags in text editor at the top of svg file to make the same format as original.

**Comment by m0o0hammad** [comment]
tnx a lot @asnik Change the logo successfully. Just ask a question after every change I have to start the server first?

**Comment by asnik** [comment]
Hi, as I understand after change SVG in sources you have to rebuild whole system and then stop thingsboard service, install new deb package (which overrides jar files), start again service.
