### ISSUE TITLE
Is is possible to compose multivalue in one TS_KV row?

### ISSUE THREAD

**Issue by liaoweiguo** [thingsboard/thingsboard#1399]
I have a device with 20 sensors generate timeseries data, in this scenario, one device message insert 100 ts_kv record, which is not efficent, 
can I add a list column for ts_kv, or something like it

Publishing: {"temperature1":18.381385818606745, "humidity1":21.294707374843295, "temperature2":19.204397696539836, "humidity2":25.537843398421998, "temperature3":18.555055551795064, "humidity3":30.111813174107073, "temperature4":13.823131409186662, "humidity4":23.274061455551195, "temperature5":12.342726968862774, "humidity5":22.045848065104693, "temperature6":14.150095979112619, "humidity6":35.158382853323644, "temperature7":15.15414904336728, "humidity7":20.873284313638585, "temperature8":11.304326616826962, "humidity8":35.97295496331188, "temperature9":12.388070050038678, "humidity9":38.28264475702905, "temperature10":14.73011296392107, "humidity10":23.66280511935455, "temperature11":11.37308069089379, "humidity11":23.392821685360573, "temperature12":10.573069756412403, "humidity12":23.241057605692802, "temperature13":12.029103131385725, "humidity13":22.883623398538404, "temperature14":18.9301480552554, "humidity14":27.726328758489977, "temperature15":15.585780466362078, "humidity15":27.009195719219896, "temperature16":14.928283709060453, "humidity16":39.77374566405186, "temperature17":18.113748907718566, "humidity17":24.80375284582155, "temperature18":18.43828493053978, "humidity18":39.238786769761305, "temperature19":10.935274400495938, "humidity19":24.48936717206518, "temperature20":19.928328582455382, "humidity20":25.975289057387165, "temperature21":16.561268296154157, "humidity21":25.989863131451965, "temperature22":14.03131193006335, "humidity22":21.404426554092904, "temperature23":11.135019200698789, "humidity23":23.166060619399587, "temperature24":16.681969841600434, "humidity24":26.589589334097106, "temperature25":11.792693925307717, "humidity25":23.100501938363724, "temperature26":13.947704701565186, "humidity26":27.287625780103973, "temperature27":14.692237985207361, "humidity27":33.60467179971177, "temperature28":10.456039208647535, "humidity28":20.589837740400355, "temperature29":18.052750792863343, "humidity29":23.67560113516799, "temperature30":17.58012353002277, "humidity30":29.17548676740335, "temperature31":13.507458792712276, "humidity31":35.54023094878304, "temperature32":13.036980771474841, "humidity32":22.44916875226531, "temperature33":16.173960576750375, "humidity33":39.336474254013915, "temperature34":14.175702119341441, "humidity34":30.47518811544876, "temperature35":16.052133505775295, "humidity35":31.17861903296386, "temperature36":10.69322705778874, "humidity36":26.04265388655427, "temperature37":12.149676931882762, "humidity37":25.632787157507607, "temperature38":16.340569326272046, "humidity38":20.104709043292992, "temperature39":19.789475687379806, "humidity39":29.988126033446793, "temperature40":12.09924159424264, "humidity40":39.37730532371452, "active": true}

**Comment by liaoweiguo** [comment]
No no, I means how to reduce the ts_kv_cf rows number? Can I add some columns as temps_v list<double> to table ts_kv_cf, so we can insert ONLY one row for 80 sensor datas?

cqlsh:thingsboard> desc ts_kv_cf;

CREATE TABLE thingsboard.ts_kv_cf (
    entity_type text,
    entity_id timeuuid,
    key text,
    partition bigint,
    ts bigint,
    bool_v boolean,
    dbl_v double,
    long_v bigint,
    str_v text,
    PRIMARY KEY ((entity_type, entity_id, key, partition), ts)
)
cqlsh:thingsboard>

**Comment by liaoweiguo** [comment]
cqlsh:thingsboard> select count(*) from ts_kv_cf;

 count
---------
 1090174

(1 rows)

half an hour produced 1M records in ts_kv_cf

**Comment by mp-loki** [comment]
Well, I think you can try to send it it as a Json String, e.g. escape all quotes and send a message to ThingsBoard like {"data":"{\"temperature1\":\"val1\","temperature2\":\"val2\"...}"}. Then you will have a single unparsed string saved in telemetry, and you would need to parse it directly in widget with a post-processing function to display. However, I can't imagine how would you benefit from this and what issues does the row count causes for you.
