### ISSUE TITLE
Can't login to demo

### ISSUE THREAD

**Issue by doom369** [thingsboard/thingsboard#14]
URL : http://demo.thingsboard.io/login

> The first step is to login to administration Web UI using default account:
> Username: tenant@thingsboard.org
> Password: tenant

Doesn't work

**Comment by ashvayka** [comment]
This login and password is only for local installation. You can get Live Demo account using sign-up procedure http://demo.thingsboard.io/signup

**Comment by doom369** [comment]
@ashvayka every additional step for "trying" reduces your auditory :). Just FYI.
