### ISSUE TITLE
buils thingsboard source code ERROR http transport service

### ISSUE THREAD

**Issue by m0o0hammad** [thingsboard/thingsboard#1400]
hello please help me 
FAILURE
![screenshot from 2019-01-16 13-32-44](https://user-images.githubusercontent.com/30108318/51249261-09bb9800-19a8-11e9-94d3-9e8e3a944e1b.png)

**Comment by ashvayka** [comment]
As you can see from the logs, issue is fetching the dependency from the jenkins repo to your computer.

**Comment by m0o0hammad** [comment]
@ashvayka 
Thank you for your guidance
But how can I solve the problem
I followed all the steps according to the instructions, and I got help from the following source, but the problem did not resolve.
https://travis-ci.org/thingsboard/thingsboard/jobs/479431584

**Comment by qkarthi** [comment]
@ashvayka 

[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke failed: Plugin org.fortasoft:gradle-maven-plugin:1.0.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.fortasoft:gradle-maven-plugin:jar:1.0.8 -> org.gradle:gradle-tooling-api:jar:2.13: Failed to read artifact descriptor for org.gradle:gradle-tooling-api:jar:2.13: Could not transfer artifact org.gradle:gradle-tooling-api:pom:2.13 from/to gradle (http://repo.gradle.org/gradle/libs-releases-local/): Access denied to: http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/2.13/gradle-tooling-api-2.13.pom , ReasonPhrase:Forbidden. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke failed: Plugin org.fortasoft:gradle-maven-plugin:1.0.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.fortasoft:gradle-maven-plugin:jar:1.0.8 -> org.gradle:gradle-tooling-api:jar:2.13


i also got the same error  

i  am using this :

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux",arch: "amd64", family: "unix"
