### ISSUE TITLE
Deploy microservices on multiple machines

### ISSUE THREAD

**Issue by chenchensheng** [thingsboard/thingsboard#1404]
Is there any relevant documentation to deploy microservices on multiple machines?

**Comment by absinthetized** [comment]
Me too was interested. As Docker Compose seems the only available solution at now (being k8s gone) I suppose that [Docker Swarm](https://docs.docker.com/engine/swarm/) is the solution to go...
That's a pity: k8s seems to be the de facto standard for container orchestration and HA nowdays.

**Comment by chenchensheng** [comment]
> Me too was interested. As Docker Compose seems the only available solution at now (being k8s gone) I suppose that [Docker Swarm](https://docs.docker.com/engine/swarm/) is the solution to go...
> That's a pity: k8s seems to be the de facto standard for container orchestration and HA nowdays.
> 
> Btw v.2.4 roadmap reintroduces k8s!

Thx reply.
I have solved this problem with Docker Swarm .

**Comment by ahmed-1a** [comment]
@chenchensheng Can you please describe your solution?
