### ISSUE TITLE
When modifying UI pages, it takes a long time to compile each time.

### ISSUE THREAD

**Issue by christlee2258** [thingsboard/thingsboard#1405]
Every time you modify an HTML page, webpack takes a long time to edit.

For example：

> webpack: Compiling...
> 
>   0% compile
>  10% 0/1 build modules
>  71% seal
>  73% optimize
>  75% hashing
>  78% additional chunk assets
>  90% optimize assets
>  95% emit
> Hash: 8c2978a593299f611997
> Version: webpack 1.15.0
> Time: 5145ms

What are the best ways to optimize？

**Comment by souhaiebtar** [comment]
how do you succeded to modify ui, any step ?

**Comment by ban2derlog** [comment]
hi,
please use new versions to create a custom webpages, and then compile new .jar with it.
