### ISSUE TITLE
Mqtt node issue thingsboard 2.2.0

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1406]
Hi,
I use the mqtt node in order to publish every message to mosquitto broker. The problem is that one message arrives more times, so it duplicates messages sometimes.
Could you tell me what should I do?

**Comment by JozsefGuyas** [comment]
Can I modify the Qos?

**Comment by Ultrazombie** [comment]
Is your problem still relevant?
