### ISSUE TITLE
get shared attribute in widget ?

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1416]
is there a way to get shared attribute from device  in the widget ?

**Comment by souhaiebtar** [comment]
attributeService = self.ctx.$scope.$injector.get('attributeService');

attributeService.getEntityAttributesValues('DEVICE', deviceIdsKeys[0].deviceId, 'SHARED_SCOPE', 'TANK1');

**Comment by alexsmartens** [comment]
Thanks @souhaiebtar,
I think your suggestion could solve my challenge of getting attribute data in a time series widget(#1737).

I am wandering whether you could suggest if it is possible to request all available shared scope attributes at once?
