### ISSUE TITLE
 @Value("${install.data_dir:}") Quotes  Error

### ISSUE THREAD

**Issue by ShaharAriel** [thingsboard/thingsboard#1417]
https://github.com/thingsboard/thingsboard/blob/8cc1e9f72b0c256417b0ec3fc607641c8e806e48/application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java#L66

The quotes after @Value ("$ {install.data_dir:}") are redundant and the error is thrown as follows: The value of 'install.data_dir' is not a valid directory!]

**Comment by ashvayka** [comment]
What is the value of install.data_dir? I assume the error is correct and you have specified invalid directory or directory that does not allow read/write operations for thingsboard OS user.

**Comment by ShaharAriel** [comment]
Note that I have edited the issue-the colon after the PROPERTY 'install.data_dir'  look redundant and may be causing an error (I added printing of dataDir variable to the error message and the value was NULL or empty STRING)

**Comment by ShaharAriel** [comment]
Thanks  you for your quick response.
The problem was in EOL because my OS is WIN and all the files are copied to LINUX,
There were problems reading the files, after I changed the EOL to LF,
(I actually did "CLONE" again after setting the EOL to LF in GIT ) The problems have been solved.

**Comment by ShaharAriel** [comment]
I forgot to mention that I use in DOCKER to run the system (by the PLUGIN of MAVEN)
