### ISSUE TITLE
Unable to install thingsboard on my ubuntu 16.04 

### ISSUE THREAD

**Issue by palutlavamshi** [thingsboard/thingsboard#1418]
Hi IvanSemenenko,

I am facing a problem while installing thingsboard on my ubuntu machine, can you help me to resolve?

tcs@tcs-Latitude-5480:~$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
19:39:54,881 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:39:54,882 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:39:54,882 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
19:39:54,888 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
19:39:54,888 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.2.0.jar!/logback.xml]
19:39:54,888 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
19:39:55,082 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:39:55,085 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
19:39:55,111 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
19:39:55,139 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2065951873 - setting totalSizeCap to 3 GB
19:39:55,145 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2065951873 - Archive files will be limited to [100 MB] each.
19:39:55,181 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2065951873 - No compression will be used
19:39:55,184 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2065951873 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
19:39:55,190 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6acbcfc0 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
19:39:55,190 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6acbcfc0 - Roll-over at midnight.
19:39:55,194 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6acbcfc0 - Setting initial period to Wed Jan 23 18:53:30 IST 2019
19:39:55,198 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:39:55,243 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
19:39:55,244 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
19:39:55,246 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
19:39:55,247 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
19:39:55,247 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
19:39:55,247 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
19:39:55,248 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:39:55,249 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5f184fc6 - Registering current configuration as safe fallback point

ThingsBoard installation failed!
tcs@tcs-Latitude-5480:~$

I have attached the error what i am facing, please have a look

And i have attached the yaml file also.
Thanks,
Vamsi.
[thingsboard.yml.txt](https://github.com/thingsboard/thingsboard/files/2790394/thingsboard.yml.txt)

**Comment by ashvayka** [comment]
Please attach the install.log

**Comment by IvanSemenenko** [comment]
Hi Vamsi,

You have an error in the file.
https://codebeautify.org/yaml-validator
Line 439

Regards,

**Comment by lamiwe** [comment]
Dear all
I have the same problem, pls, help me
Best regards

**Comment by IvanSemenenko** [comment]
Hi lamiwe,

Could you start your investigation from this link
https://github.com/thingsboard/thingsboard/issues/1418#issuecomment-457277318

Regards,

**Comment by palutlavamshi** [comment]
Hi IvanSemenenko,

Thanks for your reply. After taking your suggestions, i could able to install the Thingsboard instance and run as a service. But i am unable to open the Web UI port.

Thanks,
Vamsi.

**Comment by palutlavamshi** [comment]
Hi Team,

There are no logs generated in the

 /var/log/thingsboard/thingsboard.log file

Thanks & Regards,

Vamsi.

**Comment by palutlavamshi** [comment]
Hi,
I am attaching the install.log file. Please have a look
[install.log](https://github.com/thingsboard/thingsboard/files/2811497/install.log)

Thanks.

**Comment by alexsmartens** [comment]
Hi, 
I'm running into a similar problem #1643. Would you have any suggestions?

**Comment by Ultrazombie** [comment]
Please make a new issue with fresh installation or thingsboard problem.
