### ISSUE TITLE
GATEWAY windows

### ISSUE THREAD

**Issue by chaikonen5** [thingsboard/thingsboard#142]
Hi everyone, i'm trying to install IoT gateway for windows and i've some problems. After install Java 8, and tb-gateway, i configure "tb-gateway.yml " =

******
gateway:
  reporting:
    interval: 60000
  persistence:
    type: file
    path: storage
    bufferSize: 1000
  connection:
    host: "127.0.0.1"
    port: 1883
    retryInterval: 3000
    maxInFlight: 1000
    security:
      accessToken: "Ep3X64xwfbhZLlKqvYjm2"
#      keystore: mqttclient.jks
#      keystorePassword: password
#      keystoreKeyAlias: clientalias
#      truststore: mqttclient.jks
#      truststorePassword: password

opc:
  enabled: false
  configuration: opc-config.json

mqtt:
  enabled: true
  configuration: mqtt-config.json

sigfox:
  enabled: false
  configuration: sigfox-config.json

server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

******

but, when i try to start tb-gatway, say that started all correct, but in the logs,  tb-gateway.log, i've this error:
****
2017-05-22 12:29:44,493 [main] WARN  o.t.g.service.MqttGatewayService - Failed to connect to Thingsboard!
org.eclipse.paho.client.mqttv3.MqttException: Se ha perdido la conexión
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
	... 1 common frames omitted

****
P.D: the only diference i think i've is, i'mt not working on port :8080, i work on port 8081.

Can anybody help me??

thankssssssss!!

**Comment by vparomskiy** [comment]
If this issue is still valid for you, please create an issue in the corresponding project
https://github.com/thingsboard/thingsboard-gateway
