### ISSUE TITLE
Javascript FormData function is undefined

### ISSUE THREAD

**Issue by mahmed14** [thingsboard/thingsboard#1420]
I want to add functionality of file upload in asset section. I have implemented directive and controller but unfortunately the application shows FormData is not defined . Although This function is working on my example project. Please share your ideas and solution for file upload in ThingsBoard

**Comment by Ultrazombie** [comment]
Why don't you try a new feature - OTA?
https://thingsboard.io/docs/user-guide/ota-updates/
