### ISSUE TITLE
Rule chain JS functions

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1421]
I am trying to modify the incoming data using rule chain, but I am not able to use normal javascript functions.

**Example**
The incoming telemetry data is base64 encoded. I want to convert it to plain text before storing it. The usual js approach for converting from base64 to string is to use _atob()_, but If i try to use this function, i get "**ReferenceError: "atob" is not defined**"
How can I use JS functions in rule chain?

**Comment by ashvayka** [comment]
I believe you can just add them from this place https://github.com/jsdom/abab/blob/master/lib/atob.js into your JS function code. Although, it is good idea to add them by default and we will consider this.

**Comment by nrdmtt** [comment]
New problem... 
Function .length is undefined as well. 

What I may suggest is to integrate the common JS function in rule engine with the next TB release. Having a JS rule engine without common library/functions is a  bit disappointing....

**Comment by t0mmyz7** [comment]
This is how I managed to convert HEX to BASE64 in Thingsboard PE rule engine and data converter function. I am not sure that it works in CE though:

`msg.base64 = btoa(msg.payload.match(/\w{2}/g).map(function(a){return String.fromCharCode(parseInt(a, 16));} ).join(""))

return {msg: msg, metadata: metadata, msgType: msgType}; `

**Comment by Cryoware** [comment]
> This is how I managed to convert HEX to BASE64 in Thingsboard PE rule engine and data converter function. I am not sure that it works in CE though:
> 
> ```
> msg.base64 = btoa(msg.payload.match(/\w{2}/g).map(function(a){return String.fromCharCode(parseInt(a, 16));} ).join(""))
> 
> return {msg: msg, metadata: metadata, msgType: msgType}; 
> ```

As you know the Converters is a PE feature only, so it has the btoa/atob among other built in functions defined. And they also can be used in the Rule Chains as added convenience.
