### ISSUE TITLE
rule chain lagging and missing input

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#1422]
i observed, that if i update telemetry value of my device, it constantly misses every other input. i directed all successful telemetry messages to mqtt and observed the incoming data with mqtt-spy. What i noticed, was that when sending data to thingsboard, data was constantly missing. sometimes, when data is sent, there is no delay and it works well, but most of the time it lags and doesn't come through the saved telemetry- node.

i'm using postgresql as db and it's located on same raspberry pi as tb itself.

Thanks, Samu

**Comment by vparomskiy** [comment]
Rule Chain can lag when there are a lot of concurrent messages are passed into Rule Chain. 
1. What is your message rate?
2. Does debug enabled for some rule nodes? (it increase pressure on the DB)
3. Provide CPU load and log file for the time window where you see lags.
