### ISSUE TITLE
Update shared boolean attribute widget updates with the value label as String

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#1427]
Hello.
We are using Thingsboard CE-v2.2.0
We have configured the "Update shared **boolean** attribute" widget in a dashboard to update a device boolean shared attribute "calibrazione_ph_on".
The "Advanced" settings are configured as 
True value: Attivata
False value: Disattivata
By doing so, the shared attribute "calibrazione_ph_on" is no longer a boolean, but is changed into **string**, and such string gets the "Attivata" or "Disattivata" text configured in the widget's advanced settings "True value" and "False value" respectively. See screeenshots.

![screenshot_20190128_131310](https://user-images.githubusercontent.com/1144682/51835836-e3c6b980-22fe-11e9-8e60-563955e2c82f.png)
![screenshot_20190128_131409](https://user-images.githubusercontent.com/1144682/51835854-f214d580-22fe-11e9-9328-1a61898c3e09.png)

**Comment by ikulikov** [comment]
Fixed in ThingsBoard v2.3.0
