### ISSUE TITLE
PerformanceTest on tb2.2.0 in clusters model occured database problem(Duplicate entry 'DEVICE-1e9239c2d67abb0a812cb26c82921d0-SERVER_SCOPE-lastDisconne' for key 'PRIMARY')

### ISSUE THREAD

**Issue by ClarenceKennedy** [thingsboard/thingsboard#1429]
(Duplicate entry 'DEVICE-1e9239c2d67abb0a812cb26c82921d0-SERVER_SCOPE-lastDisconne' for key 'PRIMARY')
It seems like that the tb-node is insert the infomation of the centain device into table 'attribute_kv' more than once. we tried many times in miroservices model.But none is success.could any one help us.Thxs!!

**Comment by Ultrazombie** [comment]
Do not reproduce on the 3.3.3 version.
