### ISSUE TITLE
[IDEA] Extensive search criteria in the GUI

### ISSUE THREAD

**Issue by nmenoni** [thingsboard/thingsboard#143]
Currently searching for a device in the list of devices shows results that begin with the letters specified in the search field. But there are situations in which you do not remember exactly how the device name begins but some word that forms part of that name. 

That is why it would be nice (especially when the number of devices in large) if the search field would allow you to perform a more extensive search, such as if the name of my device is "Sensor_over_table" I can for example write it in the search field \*table\* and that the result shows it to me (along with others who also contain that word in their name). Perhaps this search criterion could extend to the content specified in the "description" field of each device.

These same comments apply also to searches on widgets and dashboards as well.

This is just an idea for you to evaluate, thanks.

**Comment by ashvayka** [comment]
The search criteria is scheduled for 3.1
