### ISSUE TITLE
Where can I find the detail document for "Timewindow" functions (ex. onUpdateTimewindow(startTimeMs, endTimeMs)) to use it ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1432]
Hi,

I am trying to develop a custom widget to get data at a period time. I saw the TB document to choose "Timeseries" widget.
At the document (https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions), I only saw the functions - "onUpdateTimewindow(startTimeMs, endTimeMs) 
,onResetTimewindow()". But there is no further detail to describe them.

Can anyone know where I can find the detail document or sample code ?

Regards,

Paul Wang

**Comment by Ultrazombie** [comment]
Description added on the latest version
