### ISSUE TITLE
Can the control widget change its status by the status received from the device?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1433]
I'am trying the RCP function, and I can control the raspberry GPIO status by click the "on/off" button.
When I clicked 'on' button, my device's led is light,
then, I took away the led, my device‘s status is "off", but the control widget on the dashboard looks still "on" status. How can I do to let the control widget receive the device's status and change it's status by the device's status?

My script is like below:
var mqtt = require('mqtt');
var client = mqtt.connect('mqtt://' + thingsboardHost,{ username: accessToken });

// 客户端成功连接后触发
client.on('connect', function () {
    console.log('客户端已连接!');
    client.subscribe('v1/devices/me/rpc/request/+');
    setInterval(publishTelemetry, sendInterval);

});

client.on('disconnect', function () {
    console.log('客户端连接断开');
});

//获取传感器状态
function get_sensor_status() {
    //Encode sensor state to json
    var info = {params:sensor_on_off_state}
    return JSON.stringify(info);
}
//设置传感器状态
function set_sensor_status(status) {
    sensor_on_off_state = status;
    if(status === true) {
        console.log('水量传感器已启动，开始测量水量');
        water_on_fault_stop = 0;
    }else {
        console.log('水量传感器已关闭');
        water_on_fault_stop = 0;
    }
}

client.on('message', function (topic, message) {
    console.log('request.topic: ' + topic);
    console.log('request.body: ' + message.toString());
    client.publish(topic.replace('request','response'), get_sensor_status(), 1);

    
    var data = JSON.parse(message.toString());
    simulate_method = data.method;
    if(data.method === 'getSwitchValue') {
        console.log('获取水量传感器开关状态');
        //回复传感器状态
        client.publish(topic.replace('request','response'), get_sensor_status(), 1);
    } else if (data.method === 'setSwitchValue') {
        console.log('设置水量传感器开关状态');
        //更新传感器状态并回复
        set_sensor_status(data.params);
        client.publish(topic.replace('request','response'), get_sensor_status(), 1);
        client.publish('v1/devices/me/attributes', get_sensor_status(), 1);
    }else {
        console.log("Invalid function!!!");
    }
});

var lastWater=0;
function publishTelemetry() {
    if (sensor_on_off_state === true) {
        var current = datagen();
        client.publish('v1/devices/me/telemetry', JSON.stringify({water: parseFloat(current.toFixed(3))}));
        lastWater = current;
    }else{
        console.log('!!!!!请首先启动传感器模拟器！！！！！！'); 
    }
}
Add the configuration of the control widget is below:

**Comment by vparomskiy** [comment]
Are you using standard RPC widgets or you create a custom widget?
I recommend creating a custom RPC widget for this case. On init, this widget will fetch current device state and put control switch in the desired position.

Here is a widget dev guide: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

You can also take a look on `Demo Custom Widgets` widget bundle on cloud.thingsboard.io
There are few custom widgets that you can use as a reference.

**Comment by qwyinxiang** [comment]
I am using the standard RPC widget, the control widget.
Do you mean that the RCP widget that comes with the system does not support this function?
Change its status by the status received from the device?
If this is the case, I will try a custom control widget. thank you very much.

**Comment by vcmorini** [comment]
> I'am trying the RCP function, and I can control the raspberry GPIO status by click the "on/off" button.
> When I clicked 'on' button, my device's led is light,
> then, I took away the led, my device‘s status is "off", but the control widget on the dashboard looks still "on" status. How can I do to let the control widget receive the device's status and change it's status by the device's status?
> 
> My script is like below:
> var mqtt = require('mqtt');
> var client = mqtt.connect('mqtt://' + thingsboardHost,{ username: accessToken });
> 
> // 客户端成功连接后触发
> client.on('connect', function () {
> console.log('客户端已连接!');
> client.subscribe('v1/devices/me/rpc/request/+');
> setInterval(publishTelemetry, sendInterval);
> 
> });
> 
> client.on('disconnect', function () {
> console.log('客户端连接断开');
> });
> 
> //获取传感器状态
> function get_sensor_status() {
> //Encode sensor state to json
> var info = {params:sensor_on_off_state}
> return JSON.stringify(info);
> }
> //设置传感器状态
> function set_sensor_status(status) {
> sensor_on_off_state = status;
> if(status === true) {
> console.log('水量传感器已启动，开始测量水量');
> water_on_fault_stop = 0;
> }else {
> console.log('水量传感器已关闭');
> water_on_fault_stop = 0;
> }
> }
> 
> client.on('message', function (topic, message) {
> console.log('request.topic: ' + topic);
> console.log('request.body: ' + message.toString());
> client.publish(topic.replace('request','response'), get_sensor_status(), 1);
> 
> ```
> var data = JSON.parse(message.toString());
> simulate_method = data.method;
> if(data.method === 'getSwitchValue') {
>     console.log('获取水量传感器开关状态');
>     //回复传感器状态
>     client.publish(topic.replace('request','response'), get_sensor_status(), 1);
> } else if (data.method === 'setSwitchValue') {
>     console.log('设置水量传感器开关状态');
>     //更新传感器状态并回复
>     set_sensor_status(data.params);
>     client.publish(topic.replace('request','response'), get_sensor_status(), 1);
>     client.publish('v1/devices/me/attributes', get_sensor_status(), 1);
> }else {
>     console.log("Invalid function!!!");
> }
> ```
> 
> });
> 
> var lastWater=0;
> function publishTelemetry() {
> if (sensor_on_off_state === true) {
> var current = datagen();
> client.publish('v1/devices/me/telemetry', JSON.stringify({water: parseFloat(current.toFixed(3))}));
> lastWater = current;
> }else{
> console.log('!!!!!请首先启动传感器模拟器！！！！！！');
> }
> }
> Add the configuration of the control widget is below:

@qwyinxiang , could you manage to do the RPC work with the demo.thingsboard ?
I am facing some issues.

Thanks!

**Comment by aljimgar** [comment]
@qwyinxiang Have you achieved to change switch control status from a device?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
