### ISSUE TITLE
help needed in migration of database from hsql to postgres

### ISSUE THREAD

**Issue by mysty-mystic** [thingsboard/thingsboard#1434]
i have successfully installed thingsboard and is working fine, but if i want to update to postgres where do i make what change,
sudo nano /etc/thingsboard/conf/thingsboard.yml         (or)
sudo nano thingsboard/application/src/main/resources/thingsboard.yml
????
if anybody has already done it , it would really help me if they share the   thingsboard.yml file for reference as many stating they have indentation errors and dont know what is right,

can anyone also help me with further instructions , im new to thingsboard
thanks in advance.

**Comment by Ultrazombie** [comment]
You need to edit the settings in thingsboard.conf
