### ISSUE TITLE
Does the released docker micro service deployment considered session persistence?

### ISSUE THREAD

**Issue by spree1010** [thingsboard/thingsboard#1436]
Hi, can any one help to check whether the released micro service deployment considered session persistence?

Thank you!
Kun

**Comment by vparomskiy** [comment]
for the transport with sessions (mqtt, coap) session is persistent and Thingsboard will communicate with the device via the same microservice. For HTTP behavior will be different because there is no actual session.

**Comment by spree1010** [comment]
thank you very much!
BTW,  in docker compose file,  environment variable CLUSTER_NODE_ID appears in tb_node, mqtt,http section, what does is this variable used for?

Thank you!
Kun

**Comment by vparomskiy** [comment]
@spree1010 
this variable should be empty and value will be autogenerated during service initialization. This ID used for identifying Service instance in the cluster.

@winbillatgithub 
Yes, all required information is stored inside JWT token (stateless session), so HTTP request can be handled on different instances. In case of WebSocket subscription, ThingsBoard knows where to send WebSocket updates and it guarantees that no date is lost in cluster mode

**Comment by spree1010** [comment]
Thank you, vparomskiy. It is clear 👍 

In docker compose file, I find this variable **RPC_HOST** in TB Node,  and have some questions:
- what is the purpose of does this variable?
- does this variable needs to be unique if multiple TB Nodes exist?
- in a kubernetes deployment,  how to set this variable if tb nodes are set in a replication controller?

Thank you!
Kun

**Comment by vparomskiy** [comment]
Combination of RPC_HOST and RPC_PORT used to identify the destination for all messages inside the cluster. 
This combination should be unique.
rpc_host can be defined as IP address of the pod and port can be the same for all pods.
