### ISSUE TITLE
Nashorn (rule chain) increase MaxCpuTime

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1438]
I have a rule chain with a JS script for data decompression, but the execution fails as it requires more than 100ms.

**Error:**
> delight.nashornsandbox.exceptions.ScriptCPUAbuseException: Script used more than the allowed [100 ms] of CPU time.

Is there a way to increase the Max CPU Time?

**Comment by vparomskiy** [comment]
https://thingsboard.io/docs/user-guide/install/config/

You need to change this property in thingsboard.yml - `LOCAL_JS_SANDBOX_MAX_CPU_TIME`

**Comment by nrdmtt** [comment]
Perfect. Thank you.
