### ISSUE TITLE
Time period excludes start time and includes end time

### ISSUE THREAD

**Issue by tagliala** [thingsboard/thingsboard#1443]
Hi,

I've noticed that when I select a time period, the start time is excluded from the range while end time is included. I would expect something like `event_datetime >= start_time && event_datetime < end_time`

I'm using ThingsBoard 2.2.0 , it also happens on ThingsBoard 2.1.0

Please take a look at the following screenshots
![image](https://user-images.githubusercontent.com/556268/52071195-c99d0d80-2582-11e9-8ae6-33b5067b727a.png)
---
![image](https://user-images.githubusercontent.com/556268/52071246-d9b4ed00-2582-11e9-9ab2-cc68509df2a3.png)

**Comment by vparomskiy** [comment]
You are right. When aggregation type is `NONE` then query filter looks like this: 
`time > :startTs AND time < :endTs`

**Comment by tagliala** [comment]
@vparomskiy thanks for your answer.

I've probably found the java code that is related to my question
https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java#L38

I can confirm that aggregation type is none, and it seems to include :endTs.

I would have been expected `time >= :startTs AND time < :endTs` rather than `time > :startTs AND time <= :endTs`

Is this behaviour expected? Maybe it is culture-dependent?

**Comment by vparomskiy** [comment]
different mappings are used for SQL and Cassandra databases. Here is a link for Cassandra
https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java#L709

Actually I can not give a good answer why it was implemented in such way, but it is what we have for the current moment.

**Comment by tagliala** [comment]
Thanks

Looks like it has been implemented this way from the beginning: https://github.com/thingsboard/thingsboard/commit/f6bc0791f10dc20260ea04dec20429c93ed18840#diff-c43bd416fe777106d54a417e156e8dd6R329

At the moment I'm using 00:00:01 as a workaround, it does not affect me too much
