### ISSUE TITLE
Cannot be loaded into the "widgetSettingsSchema" property  

### ISSUE THREAD

**Issue by lddfor** [thingsboard/thingsboard#1449]
HI: Happy New Year!
![image](https://user-images.githubusercontent.com/22298961/52161189-6e8f2600-26fc-11e9-935e-6c83deb0fe99.png)

![image](https://user-images.githubusercontent.com/22298961/52161192-7a7ae800-26fc-11e9-8e1f-168936292117.png)

![image](https://user-images.githubusercontent.com/22298961/52161227-f8d78a00-26fc-11e9-9fcd-07a35f986128.png)

Cannot be loaded into the "widgetSettingsSchema" property;
 
May I ask your advice? Thank you very much!

**Comment by Ultrazombie** [comment]
Is your problem still relevant?
