### ISSUE TITLE
Piggybacked CoAP responses

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#1450]
From my observations it looks like Thingsboard currently never piggybacks CoAP responses, it always goes the "async" route of request, ACK, response, ACK.

I know this is absolutely allowed by the protocol, but the specifications do encourage the usage of piggybacked responses if possible. The response can then be carried directly within the ACK packet. Especially on the client this has multiple advantages, e.g. reduced complexity, network-traffic and ultimately battery-power spent.

> https://tools.ietf.org/html/rfc7252#section-5.2.1
> Implementation Note:  The protocol leaves the decision whether to
      piggyback a response or not (i.e., send a separate response) to
      the server.  The client MUST be prepared to receive either.  On
      the quality-of-implementation level, there is a strong expectation
      that servers will implement code to piggyback whenever possible --
      saving resources in the network and both at the client and at the
      server.

Is it possible for Thingsboard to use piggybacked responses?

**Comment by vparomskiy** [comment]
This feature is planned for the nearest time. Contributions are welcome.

Entry point is `org.thingsboard.server.transport.coap.CoapTransportResource` class that is responsible for handling CoAP requests. 
Thingsboard uses `Eclipse Californium` project for handling CoAP. Each incoming request has 'Type' property (`org.eclipse.californium.core.coap.CoAP.Type`) with possible values `CON, NON, ACK, RST`

**Comment by MrZANE42** [comment]
Any timeframe for this? 
I have an embedded product using a precompiled library that doesn't handle the ACK + Seperate message with new MID very well. All I get on a GET from the server is an empty data packet back (The ACK basically).
Is there any way to configure the Eclipse Caliorfornium differently without changing the soure-code?
As I use/pay for the PRO version I can't do changes to the code and recompile.

**Comment by SergMeleshko** [comment]
Hello @JcBernack 
Is the issue still relevant?

**Comment by JcBernack** [comment]
Hi @SergMeleshko 
yes, still relevant. Behavior in the newest version of Thingsboard is unchanged from what I described here.

**Comment by ashvayka** [comment]
I have added minor comments to the PR. Once you add those few lines I will merge :-)
