### ISSUE TITLE
Cant import your sample aggregate widget. Error occured

### ISSUE THREAD

**Issue by Yinkci** [thingsboard/thingsboard#1451]
I'm trying to follow your step by step for aggregation to count the total sum water consumption. But Theres an error in your widget, I think its outdated. Its says "invalid widget data structure"

Heres the link of your docu: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/
Link of widget export: https://thingsboard.io/docs/user-guide/rule-engine-2-0/pe/tutorials/aggregation_emulators.json

**Comment by vparomskiy** [comment]
The referenced tutorial shows how to aggregate data using Rule Engine and provided JSON is not a widget but Rule Chain. You should import it inside `Rule Chains` section.

**Comment by Yinkci** [comment]
OH sorry, got confused. Thanks!
