### ISSUE TITLE
Missed italian translation for alarm acknowledge dialog box

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#1453]
Using Thingsboard 2.2.0 CE
When an alarm is acknowledged, a dialog box appears asking confirmation for the acknowledge operation.
When the client is Italian, the dialog box misses the translation and displays:
"acknowledge-alarms-title" as title and "acknowledge-alarms-text" as  message.

I have seen that the problem is in wrong mapping string inside the file /thingsboard/ui/src/app/locale/locale.constant-it_IT.json.
There  the mapping is as follows

```
"aknowledge-alarms-title": "Conferma { count, plural, 1 {1 allarme} other {# allarmi} }",
"aknowledge-alarms-text": "Sei sicuro di voler confermare { count, plural, 1 {1 allarme} other {# allarmi} }?",

```
As one can see, the mapping strings are "aknowledge" (and not a**c**knowledge)

**Comment by tagliala** [comment]
Ciao!

there is a typo, but the key but looks correct to me:

https://github.com/thingsboard/thingsboard/blob/401d4b22587eaee7bfe3bbf0fc7113cc038bcef4/ui/src/app/widget/lib/alarms-table-widget.js#L423-L424

Are you sure that the alarm dialog shows a**C**knowledge?

I cannot reproduce this:
![image](https://user-images.githubusercontent.com/556268/52434531-d506b080-2b0f-11e9-9839-c9d3a6cb0d5a.png)

By the way, I had a similar issue with translation keys #1442.

I would suggest you to clear the browser cache and try again

**Comment by albtrentadue** [comment]
Ciao
I will try to reproduce tomorrow at lab, maybe the cache reload solves.
Thank you

**Comment by albtrentadue** [comment]
Ciao
I apologize for my incorrect reference within my report: I indicated the wrong key mappings.
And, yes, the problem we have is about the untranslated strings you added below:
```
"aknowledge-alarm-title": "Acknowledge Alarm",
"aknowledge-alarm-text": "Are you sure you want to acknowledge Alarm?",
```
I can see that these are not present in /thingsboard/ui/src/app/locale/locale.constant-it_IT.json but are used in the Alarm Table widget: /thingsboard/ui/src/app/widget/lib/alarms-table-widget.js
Thanks for pointing out!
