### ISSUE TITLE
[Feature Request] - Visual mapping of relations

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#1455]
Hi there,

Would be great to be able to see the defined relations between entities (tenants customers, assets, devices etc.) visually, i.e. some type of graphical map, perhaps a bit like how the rules engine displays relationships between its nodes.

Mark

**Comment by vparomskiy** [comment]
we have this task in our backlog but it is not planned for the next release. But we will definitely create a widget that shows relation hierarchy.

**Comment by enviroeye** [comment]
Sounds good !

**Comment by Ultrazombie** [comment]
implemented on the latest versions of ThingsBoard
