### ISSUE TITLE
Error saving new widget

### ISSUE THREAD

**Issue by PaoloCortesi** [thingsboard/thingsboard#1457]
I am using thingsboard 2.0
I am trying to customize or duplicate a widget (for example a card one) and I got an error after clicking the button Save or Save As of the Edit Widget Framework.
Exactly the Save button became newly not clickable (as well as it saved correctly) but the upper bar start scrolling until come up one written like "http ... unable to connect .."

The Run button works and I see the modification (for example inserting modification in the javascript).
Any other function of TB platform seems to run correctly (collecting of data and so on) 

The thingsboard log says:
WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: null; nested exception is java.net.SocketTimeoutException

Anyone got any idea or had the same issue?
Thanks a lot
Paolo.

**Comment by vparomskiy** [comment]
I didn't hear about such problem. What I can propose is to upgrade to the latest ThingsBoard version, because 2.0 is pretty old.

**Comment by PaoloCortesi** [comment]
OK,
before upgrading I would investigate because I wonder if it is due to one wrong widget content of my new custom template widget library.
First I am looking for in whole filesystem but I cannot find <mynewwidgtemplib>.json as well I can find the standard for example the one I found  /usr/share/thingsboard/ /data/json/system/widget_bundles/cards.json.
Could you suggest me where I can find the storage of those new templates/widget?
Thanks
Paolo.

  [cid:image001.png@01D1D11D.567EEAB0]

Paolo Cortesi
Cyber Security & ICT Solutions
EIS - Enterprise Information Systems

Leonardo S.p.A.
Via Puccini, 2 - Genova - 16154 - Italia
paolo.cortesi@leonardocompany.com<mailto:paolo.cortesi@leonardocompany.com>

ELICOPTERS / AERONAUTICS / ELECTRONICS, DEFENCE AND SECURITY SYSTEMS / SPACE


Il presente messaggio e-mail e ogni suo allegato devono intendersi indirizzati esclusivamente al destinatario indicato e considerarsi dal contenuto strettamente riservato e confidenziale. Se non siete l'effettivo destinatario o avete ricevuto il messaggio e-mail per errore, siete pregati di avvertire immediatamente il mittente e di cancellare il suddetto messaggio e ogni suo allegato dal vostro sistema informatico. Qualsiasi utilizzo, diffusione, copia o archiviazione del presente messaggio da parte di chi non ne è il destinatario è strettamente proibito e può dar luogo a responsabilità di carattere civile e penale punibili ai sensi di legge.
Questa e-mail ha valore legale solo se firmata digitalmente ai sensi della normativa vigente.
________________________________
The contents of this email message and any attachments are intended solely for the addressee(s) and contain confidential and/or privileged information.
If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately notify the sender and then delete this message and any attachments from your system. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. Unauthorized disclosure and/or use of information contained in this email message may result in civil and criminal liability. “
This e-mail has legal value according to the applicable laws only if it is digitally signed by the sender

**Comment by vparomskiy** [comment]
here is a path `./application/src/main/data/json/system/widget_bundles`
Note - if you make any changes in this directory you need to rebuild and reinstall project

**Comment by PaoloCortesi** [comment]
Thanks a lot, but what do you mean with ./application ?
Under my TB application I haven’t got the ‘scr’ path.. Could you have a look?

[PaoloC@ma41mdidevqa thingsboard]$ ls -la
totale 4
drwxr-xr-x.  6 thingsboard thingsboard   66  1 ott 16.26 .
drwxr-xr-x. 83 root        root        4096 12 ott 14.28 ..
drwxr-xr-x.  3 thingsboard thingsboard   87  1 ott 16.28 bin
drwxr-xr-x.  4 thingsboard thingsboard  144 21 nov 15.50 conf
drwxr-xr-x.  6 thingsboard thingsboard   61  1 ott 16.21 data
drwxr-xr-x.  2 thingsboard thingsboard   40  1 ott 16.26 .oracle_jre_usage

Moreover in whole my TB installation I cannot find the ‘src’ path too.
Do you mean DB (Cassandra) application where I can find something?
/var/lib/cassandra/data/thingsboard/?

Then Under the /usr/share/thingsboard/ /data/json/system/widget_bundles
I cannot find the custom ones, only the standard cards.json, chart.json etc.
Best regards



Il presente messaggio e-mail e ogni suo allegato devono intendersi indirizzati esclusivamente al destinatario indicato e considerarsi dal contenuto strettamente riservato e confidenziale. Se non siete l'effettivo destinatario o avete ricevuto il messaggio e-mail per errore, siete pregati di avvertire immediatamente il mittente e di cancellare il suddetto messaggio e ogni suo allegato dal vostro sistema informatico. Qualsiasi utilizzo, diffusione, copia o archiviazione del presente messaggio da parte di chi non ne è il destinatario è strettamente proibito e può dar luogo a responsabilità di carattere civile e penale punibili ai sensi di legge.
Questa e-mail ha valore legale solo se firmata digitalmente ai sensi della normativa vigente.
________________________________
The contents of this email message and any attachments are intended solely for the addressee(s) and contain confidential and/or privileged information.
If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately notify the sender and then delete this message and any attachments from your system. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. Unauthorized disclosure and/or use of information contained in this email message may result in civil and criminal liability. “
This e-mail has legal value according to the applicable laws only if it is digitally signed by the sender

**Comment by vparomskiy** [comment]
The path that I shared is for ThingsBoard sources. If you install Thingsboard from binaries (not build from sources) then widget bundles are saved inside the database, table `widgets_bundle`
