### ISSUE TITLE
Dashboard: Filter all devices "Created" by gateway

### ISSUE THREAD

**Issue by JacoBezuidenhout** [thingsboard/thingsboard#1459]
Good day all,

Love the software. One problem that I am facing is to create a search in the dashboard for all the devices that was created through a gateway? Is it possible?

**Comment by vparomskiy** [comment]
When a device is created through the gateway, relation is created between gateway and device. You can create 2 aliases:
1 - selected gateway
2 - all related devices for the selected gateway
You can use second alias for example in a entity table widget to show all gateway devices

**Comment by JacoBezuidenhout** [comment]
Thank you @vparomskiy I will try and let you know!
