### ISSUE TITLE
History in timeseries charts not working

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#146]
When I select a timeseries chart, and set the timewindow to history no data are displayed on the chart at all.

Switching back to realtime, and everything works correctly.

**Comment by aletor92** [comment]
Did you resolve the problem?

**Comment by fotis400** [comment]
No, only realtime graphs work for me.

**Comment by fotis400** [comment]
What kind of debug data may I provide to help you track down this?

**Comment by aletor92** [comment]
I have also this problem.

**Comment by ashvayka** [comment]
The best way to help us to solve this is to reproduce on demo environment and send us a public dashboard link. Ideally create two dashboards (one with history and one with latest) over the same data and send us two links + json descriptors of dashboard

**Comment by aletor92** [comment]
http://demo.thingsboard.io/dashboards/50318850-4b80-11e7-9021-c7f326cba909?publicId=0a46dc90-4b81-11e7-9021-c7f326cba909

this is the public link ( whithout sensor ) and in attachment the zip with the json...

There are any option/feature in thingsboard for historical data ?


[test_thingsboard.json.zip](https://github.com/thingsboard/thingsboard/files/1058044/test_thingsboard.json.zip)

**Comment by steves2j** [comment]
I've also noticed this issue. Sort of reproduced it on the Smart Energy Monitoring demo. If you select History, last 12hours and None for data aggregation. No data is displayed.
On my thingsboard server it's the opposite. Select 12hours and Average and no Data is displayed. Change it to NONE and data is displayed.
Maybe the data needs to be in a certain format?

**Comment by victorfu** [comment]
I have the same problem. I just found that History data work fine if the data type is an integer. If you use float, History graph doesn't work.

**Comment by ikulikov** [comment]
Please double check data format that you are using to push data to the thingsboard. The issue that you have reported can be reproduced when you pushing data in string format.
Below is valid data format for float/integer values (values without double quotes):
```json 
{"doubleKey":42.0, "longKey":73}
```
And this is not valid data format for float/integer (double quotes) and interpreted as string values:
```json
{"doubleKey":"42.0", "longKey":"73"}
```

**Comment by douglasprodocimo** [comment]
Hummm keeps not working for me
using umqtt from micropython
I tryed:
c.publish("v1/devices/me/telemetry", '{\'Internal Temperature\':\'%.1f\'}' % temp())
rults json string "{'Internal Temperature':'25.2'}"

c.publish("v1/devices/me/telemetry", ujson.dumps({'Internal Temperature': "%.1f" % temp()})
results json string '{"Internal Temperature":"25.2"}'

c.publish("v1/devices/me/telemetry", ujson.dumps({'Internal Temperature':temp()}))
results json string '{"Internal Temperature": 25.1953}'


The real time works, but history chart does't work

**Comment by bricedenicedu69** [comment]
My following question might somehow not be much related to what you previously asked, but I'd like to know how you initialized the MQTTClient from the umqtt.py librabry from Micropython. I don't really understand to what correspond the password and username required or even the client_id so I don't know how to fill them. I know this post is really old though. Here's the library I am working with : https://github.com/micropython/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py. Can anyone please help? Thanks a lot
