### ISSUE TITLE
I am a New Be! "Device offline"

### ISSUE THREAD

**Issue by colognebroker** [thingsboard/thingsboard#1468]
I have created a new device "HomeMQT" for an "Switch" Representant
I have set a Attribute to tis dervice called "Lamp"

No wenn I create a dashboard with a round button switch
Target is "HomeMQT" and the advaneced Methode is set to "subscribe to Attribute"
The Attribut is set to "Lamp"
So when i change the Attribute "Lamp" with a generator, the switch goes on and off, like it is ok!!
When i manual switch the "round switch" the Attribute did noch change the value and
there is a message "Device offline" ?

I am without any Idea ?

**Comment by vparomskiy** [comment]
Generator node is only responsible for sending data FROM device. From the Thingsboard perspective, your device  'HomeMQT' is offline because there is no active registered session (MQTT/CoAP).
When you press switch - RPC command is sent to the device if no active session found, then 'Device Offline' message will be shown.

**Comment by colognebroker** [comment]
Thank your very much !
How can i register an active session i Thougth that
a connection from my externel red node woult be enougth to simulate a device

**Comment by colognebroker** [comment]
My Idea was so collect alle my devices in an rednode instance withch converts to MQTT Broker (myOwn) and then ,and send it with rednode via pushes and subscripts to TB ....
whats is wrong with my thougths ....
So there is in TB no active Device Connection ?

**Comment by colognebroker** [comment]
> Generator node is only responsible for sending data FROM device. From the Thingsboard perspective, your device 'HomeMQT' is offline because there is no active registered session (MQTT/CoAP).
> When you press switch - RPC command is sent to the device if no active session found, then 'Device Offline' message will be shown.

Thank your very much !
How can i register an active session i Thougth that
a connection from my externel red node woult be enougth to simulate a device
My Idea was so collect alle my devices in an rednode instance withch converts to MQTT Broker (myOwn) and then ,and send it with rednode via pushes and subscripts to TB ....
whats is wrong with my thougths ....
So there is in TB no active Device Connection ?

**Comment by vcmorini** [comment]
@vparomskiy , can this work with demo.thingsboard?

Snippet from my local network RPi:
```
var mqtt = require('mqtt');
var client  = mqtt.connect('demo.thingsboard.io',{
    username: 'XFMdKdp7DRVsJHznnHtb'
});
```
no luck in connecting

**Comment by otgonbayar999** [comment]
Connected with device, have active MQTT session but 'Device Offline' message still shown Switch control widget, when push this switch disappears 'Device Offline' message.  Why 'Device Offline' message not updating when connected and disconnected from Device?
What is the solution?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
