### ISSUE TITLE
Attributes grouping

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#147]
It would be beneficial to have the ability to group attributes.

In complex devices there may be a lot of attributes, and managing them can be difficult. Having the ability to present in the WebUI only a portion of the attributes, or having the device handle a specific part of attributes each time would make things easier.

For example a specific application/thread/code part of the device may subscribe to only one attributes group, thus only getting information that it is really interested to. Instead now a huge handler has to be implemented, knowing details about all parts of the device. This harms data encapsulation and code modularity.

Here is for example a use case:
```
├── Device
│   ├── board
│   ├── firmware
│   └── etc..
├── Network
│   ├── dns
│   ├── ntp
│   ├── ip
│   └── etc...
└── Sensors
    ├── sensor_1
    ├── sensor_2
    ├── sensor_3
    └── etc...
```

Accessing the groups could be done through:

```
v1/devices/me/attributes/$GROUP
```
or by specifying the group in the JSON (although it would be best to simply be able to subscribe only to the group interested to). Ungrouped attributes (as they are now) can still co-exist.

Multiple levels of grouping would also be nice, but I believe at least one level is needed.

Grouping in the same way can also be applied to telemetry, although I am now really sure if it is really needed there.

**Comment by Karabiy** [comment]
The group functionality is available for the ThingsBoard Professional Edition. 
You can refer to this link regarding those: https://thingsboard.io/docs/user-guide/groups/

**Comment by fotis400** [comment]
Hi @Karabiy , why is this closed?

Your proposition is irrelevant to the request.

The request is about grouping the attributes themselves. Making a hierarchical structure.
This is to better organize the attributes, have specific code parts to manipulate specific attributes group (think permissions), and avoid name clashing.

It has nothing to do with entities.

**Comment by LeoMorgan113** [comment]
Hi @fotis400,

I'll ask our developers if this can be implemented in Thingsboard.
For now, we don't think that this feature will be very useful.
But thanks for your participation and for your proposal.
