### ISSUE TITLE
Entity selection drop down not populated

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#1474]
Hi there,

Not sure of of the purpose of the 'Select entities' drop down at the top of the dashboard. On all my dashboard the drop is always empty. I assume it might be to allow you to select different entities from which the dashboard data is populated (which would be handy), but I can't see how it is suppose to work?

PS. I've been through all the documentation / Git issues and Gitter and can't find any info

Mark

**Comment by bemowski** [comment]
I have the same problem, totally blocked from creating a dashboard.  I was using 2.2.0, upgraded to 2.3.0.  this is an initial installation, so i blew away the database.  I'm using the postgres version via docker-compose.

There seems to be no way to select entites for a dashboard in 2.2.0 or 2.3.0 - so i cannot setup anything of use.

**Comment by ashvayka** [comment]
Hi Mark,

did you configure your dashboard aliases? The entity dropdown is populated with options for each entity alias in dashboard.

**Comment by bemowski** [comment]
I did figure it out - it is not obvious to the first time user.  On the
dashboard page, after i create, I click on the "entities" drop down and
there is nothing.

the key point is i have to press the edit button in the bottom right, then
i am offered the option of adding entity mappings.   I spent several hours
on it - and there is a github issue open (so i'm not the only one).  Small
UX suggestion - maybe when the list is empty - put in a prompt, like "No
entity mappings.  Press edit to add mappings."  - i'm not sure - i suck w/
UX/UI but as an end user i was fairly confused.

Thank you for your software - i'm now getting data. I'm only using for my
home - to track temperature and furnace usage in the cold wisconsin winter.

Thanks for responding!
Paul

**Comment by enviroeye** [comment]
Thanks Paul and Andrew,

I still think there might be an issue. I have successfully created aliases on all our dashboards; see the screenshot attached. However the entities selection dropdown remains empty. It seems to only pick up one alias (see second screenshot)

![empty entities selection](https://user-images.githubusercontent.com/16280541/52980683-67238880-342f-11e9-8dce-641822680c9e.jpg)
![screenshot - aliases defined](https://user-images.githubusercontent.com/16280541/52980684-67bc1f00-342f-11e9-854e-7fc2d204d499.jpg)

So I'm clear I assume the entities drop down is to allow you to select between different entities and have the dashboard populated with data from a specific entity based on what you select from the drop down?

**Comment by bemowski** [comment]
Actually i do see the same thing.

**Comment by Gingonic** [comment]
Same here. Am I right to expect to be able to pick devices from there that would switch the context of the dashboard?

**Comment by Nathan-ma** [comment]
I'm also interested on this subject

**Comment by dilancw** [comment]
+1 like to know more information on this.

**Comment by Nathan-ma** [comment]
Ok so After working for a while with Thingsboard I Finally understood how this works:
![image](https://user-images.githubusercontent.com/11060905/84055832-c04c5e00-a98b-11ea-8bf1-dc2c7af49f72.png)

This will depend basically on the Alias you have set up. This alias needs to contain more than one entity in it.

1 ) First of all, it should no "Resolve multiple entities" selected, this will merge all the entities into a single entity. and this is not what we want
![image](https://user-images.githubusercontent.com/11060905/84056043-0d303480-a98c-11ea-9a01-6aa69130708f.png)

2) Create a filter by Type or a filter with something in common with all your entities.
![image](https://user-images.githubusercontent.com/11060905/84056154-36e95b80-a98c-11ea-87f7-9bc07fcc467b.png)

And that's it, its done. 

The ideia here is, Entities are a Input, by creating an Alias filtered by a device type for example you are separating all the inputs into devices and using the dashboard as a Alias reader.
So when you change your device, the whole dashboard changes accordingly.

If you resolve, merge, or do not filter the entities on the input, your output will never be able to work porperly

@dilancw , Give me my like!

**Comment by Delapouite** [comment]
@Nathan-ma thanks a lot for explanation, it makes sense! I've just tested and it works as you described.

Nonethelesss, the blank entities drop-down by default is still confusing and offers no hint on how it is supposed to work, so I still thing that is something that needs to be addressed to guide the user.

**Comment by carolin-skiply** [comment]
Hi there,

So, with my admin user, I got a populated dropdown but with my reader user I do not have it (even so the user have read access to the entities). What permission am I missing ?

Here is the generic role for my reader user :
![image](https://user-images.githubusercontent.com/34483024/100373596-509a6000-300b-11eb-9922-48dce4ac1530.png)

And group permission :
![image](https://user-images.githubusercontent.com/34483024/100373642-5ee87c00-300b-11eb-8db3-d29b30aeec26.png)

Please help,
Caroline.

**Comment by ashaforost** [comment]
I'm closing this issue as stale. If you experience similar issues on the latest thingsboard version, feel free to create a new github issue.
