### ISSUE TITLE
Manage dashboard layout - right hand panel - what's the purpose?

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#1475]
Hi there,

With the manage layout part of the dashboard, I can see that I can basically split the dashboard in two by enabling the right hand layout. But I'm not clear on the purpose of the right hand layout?

I notice on mobile devices the right hand layout is hidden and can be shown by pressing the hamburger icon.

However it would be better if the main layout was shown only on desktop resolutions and the right hand layout hidden, while on mobile devices the main layout is hidden and the right hand layout is shown. This would allow us to create two versions of the dashboard.

I get that Thingsboard is mobile responsive and offers the ability to order the rendering of each widget on mobile devices. However we have some custom widgets some of which we'd like to hide or replace with different versions on mobile devices.

Hope this makes sense

Mark

**Comment by Ultrazombie** [comment]
Please re-open the issue if still relevant.
