### ISSUE TITLE
Is downlink possible with thingsboard-gateway?

### ISSUE THREAD

**Issue by arrowcircle** [thingsboard/thingsboard#1476]
Hi! I am trying to figure how to send commands to devices, that are connected via thingsboard gateway.
Devices are connected in the following way: device -> lorawan gateway -> loraserver -> thingsboard gateway -> thingsboard.

Is it possible to control devices with GUI in thingsboard, that sends downlink to devices over thingsboard gateway?
If possible, where I can learn about it?
If not - what is the best place to start hacking on this?

**Comment by tzeeth** [comment]
Hi @arrowcircle Did you make it work? Regards!

**Comment by arrowcircle** [comment]
@tzeeth No, because there were no reaction from devs here or in chat I abandoned it and switched from thingsboard.
I had an idea how to make it within thingsboard: Use rules engine, to send messages to loraserver mqtt server. You can set up some format of the message in rules engine. Or you can send to some other mqtt channel and use simple script to properly send downlink via API of loraserver.

**Comment by tzeeth** [comment]
@arrowcircle ok will update if I can handle this or I get help, thank for your time.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
