### ISSUE TITLE
Can Thingsboard integrate with WebAuthn ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1481]
Hi,
We want to integrate TB's web page login with "WebAuthn" (ex. fido 2). Currently we are using TB 2.2.0 PE running on AWS.

We want to know that TB support the integration with "WebAuthn" or not.

Regards,

Paul Wang

**Comment by Ultrazombie** [comment]
Please read a fresh OAuth instructions with new versions of ThingsBoard
