### ISSUE TITLE
The generator repeatedly generates data when there are multiple nodes

### ISSUE THREAD

**Issue by 91wangmeng** [thingsboard/thingsboard#1482]
I have a generator like this
![snipaste_2019-02-14_16-18-51](https://user-images.githubusercontent.com/13831315/52772786-57452680-3074-11e9-92f6-d84b84184643.png)
But I found that the generator was generated on the tb1 and tb2 at same time
![snipaste_2019-02-14_16-19-12](https://user-images.githubusercontent.com/13831315/52772789-59a78080-3074-11e9-8973-dd9ade084ca2.png)
Is this the design or is there a problem with my configuration?

**Comment by ashvayka** [comment]
Hi! This is now fixed and deployed to cloud. We will release this in v 2.3.1
