### ISSUE TITLE
Telemeletry duplication in cassandra database

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#1486]
A use case:
A variable that shows the number of people visiting a museum. We keep one data point per day with the same time stamp such as:
```
2019-01-01 00:00:00 X Visitors
```
The number increases over the day so it is used to get the real time value and then remains as a historical data.

If such data is a water consumption for example it can be an integer or float number as 1L, then 1.34L and so on.

Pushing values to a same key in the same time stamp makes the data in Cassanda stored in both fields and of course different values.

This can be easily reproduce using a simple Curl post such

```bash
curl -v -X POST -d @tb.json https://[server]/api/v1/[key]/telemetry --header "Content-Type:application/json"
```
The file content can be:
```
{
	"ts": 1549397060000,
	"values": {
		"SENSOR": 1
	}
}
```

Push this file and then replace the *water* value to a float point value such as 1.5 and execute the post again.
Alternate int/float values and in some point you will  be able to see the problem into the database.

![image](https://user-images.githubusercontent.com/3164100/52843502-9fab2580-3102-11e9-9fda-d49e0e8a1a9d.png)

**Comment by ashvayka** [comment]
Hi @Tangerino ,

this is a known issue with a clear workaround - not to push data as integers and floats simultaneously. Those data is stored in different columns just for performance reasons. I can't suggest any fixes except duplicating the telemetry into both columns on each push. This is not a big performance degradation but may cause some performance decrease. Do you think this is a valid fix or have other ideas?

**Comment by Tangerino** [comment]
Thank you,
I can't control what nature of a real number will be pushed. Beyond that integer is not the same as float. I can send today the value 1 and tomorrow, due changes in the customer parameters send 1.5. I need the last value wins. what value is the good one? So I don't think this is an acceptable fix

**Comment by ChristianLutz** [comment]
@Tangerino Maybe you are able to use the rule engine to convert long value into a double.

**Comment by Tangerino** [comment]
@ChristianLutz Can you give an example on how to do this please?

**Comment by ChristianLutz** [comment]
@Tangerino There is a node [script-transformation-node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node). With this node you have a js available and with this you may add `msg.your_long.toFixed(2)` update the payload and give it back. 
I havn't tested it, it is just an idea. Hope it helps

**Comment by anton-pytel** [comment]
@ashvayka we are having troubles with this behaviour and workaround.
We are using [Lua JIT](luajit.org/luajit.html)  at our gateway and there is only ["number"](https://softwareengineering.stackexchange.com/questions/206354/how-lua-handles-both-integer-and-float-numbers) datatype, what means that it decides internally wether it will be converted as integer or float.

I consider this as bug that should be solved because of this idea:
When I use [getLatestTimeseries](https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/getLatestTimeseriesUsingGET) it returns last long_v, while I use [getTimeseries](https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/getTimeseriesUsingGET) there is clearly shown that it is not last value, because there are newer dbl_v.
![image](https://user-images.githubusercontent.com/15068798/64235332-68626180-cef8-11e9-909d-753003a6724b.png)


**getLatestTimeseries**
```
curl -X GET \
  'https://[tburl]/api/plugins/telemetry/DEVICE/905ac350-60e7-11e9-a359-f71e763e3f48/values/timeseries?keys=emer_voltage_1'
```
Result:
```
{
    "emer_voltage_1": [
        {
            "ts": 1567582501720,
            "value": "233"
        }
    ]
}
```


**getTimeseries**
```
curl -X GET \
  'https://[tburl]/api/plugins/telemetry/DEVICE/905ac350-60e7-11e9-a359-f71e763e3f48/values/timeseries?agg=NONE&keys=emer_voltage_1&startTs=1567513980000&endTs=1567577693000&limit=100&interval=0'
```
Result:

```
{
    "emer_voltage_1": [
        {
            "ts": 1567577669276,
            "value": "227.5"
        },
        {
            "ts": 1567574870271,
            "value": "228.5"
        },
        {
            "ts": 1567574736380,
            "value": "227.2"
        },
        {
            "ts": 1567570700381,
            "value": "227.4"
        },
        {
            "ts": 1567548687504,
            "value": "233" -- <======
        },
        {
            "ts": 1567548309247,
            "value": "232"
        },
        {
            "ts": 1567546617453,
            "value": "231"
        },
        {
            "ts": 1567541483987,
            "value": "232.1"
        }
    ]
}
```
Do you consider it as correct having in mind that application allows to push data of multiple types?

Thank you in advance for help.

**Comment by xalt7x** [comment]
For new telemetry, this problem can be solved by [setting](https://thingsboard.io/docs/user-guide/install/how-to-change-config/) the env variable `CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED` to "true"
Description from the [documentation website](https://thingsboard.io/docs/user-guide/install/config/):
| **Parameter**                           | **Environment Variable**                | **Default Value** | **Description**                                                        |
| --------------------------------------- | --------------------------------------- | :---------------: | ---------------------------------------------------------------------- |
| cassandra.query.set_null_values_enabled | CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED |       false       | set all data type values except target to null for the same ts on save |

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
