### ISSUE TITLE
create rest api call to a body on  the rule chain 

### ISSUE THREAD

**Issue by souhaiebtar** [thingsboard/thingsboard#1487]
i was creating a rule chain like shown in the picture, ![](https://i.imgur.com/hO9n8Nx.png),

the problem is that the `rest api call` component (the drag&drop item) don't contain a body,

it there a way to add a body to rest call 
?

**Comment by souhaiebtar** [comment]
@nabil-rejeb @vparomskiy any help please ? thanks for everything in advance.

**Comment by souhaiebtar** [comment]
ok, i found out, basically it come from the node before, thanks #820

**Comment by lstarke** [comment]
> ok, i found out, basically it come from the node before, thanks #820

Hello @souhaiebtar. I'm trying to add a JSON in a body to make a rest call but no success atm.

Please, can you explain in more detail how you do that ?

**Comment by zunohoang** [comment]
hello @souhaiebtar how to fix it, thanks for everything in advance.
