### ISSUE TITLE
Controll widget not works (thingsboard 2.3.0) "Error undefined undefined"

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1488]
Hi,

I have created a knob control widget, and It can not be used by customer user. I can see this message on the widget "Error undefined undefined". If I sign in as tenant it works.
What do I do wrong? How can I solve it?

**Comment by iDeam0316** [comment]
I am seeing the same failure:
Error: undefined - undefined for control widget on customer dashboard #1472
[https://github.com/thingsboard/thingsboard/issues/1472](url)
