### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by chrowe** [thingsboard/thingsboard#149]
Just wanted to track progress on the PostgreSQL implementation. Is that still happening?

**Comment by ashvayka** [comment]
Yes, it is in progress. See the corresponding [branch](https://github.com/thingsboard/thingsboard/tree/dao-refactoring-vs).

**Comment by aomer7** [comment]
Hi Andrew,

Any expected date of release for PostgreSQL version of thingsboard ?

**Comment by ikulikov** [comment]
Starting from version 1.3.0 there is SQL database support in ThingsBoard (including PostgreSQL).
