### ISSUE TITLE
Feature Request: Telemetry Data Management / Data Retention

### ISSUE THREAD

**Issue by schindlerd** [thingsboard/thingsboard#1491]
This is in reference to: #757 #719 #647 

There should be a mechanism to control data retention globally and per device. A global telemetry data retention policy should ensure that database backends won't become "data graves" and having the flexibility to even set telemetry data retention per device would be the icing on the cake ;)

This is a feature I would really love to see being implemented in some future release.

I believe there might be useful mechanisms in both database backends:
PostgreSQL - https://blog.2ndquadrant.com/postgresql-iot-data-retention-archiving/
Cassandra - https://docs.datastax.com/en/cql/3.3/cql/cql_using/useExpire.html

**Comment by fotis400** [comment]
See also #757
