### ISSUE TITLE
Thingsboard PE - How do we tell what version we are running?

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#1493]
Hi there, 

WE're running Thingsboard PE, wondering how we can tell which version / release we currently have and how we can compare with the current version on Git.

Also under the PE license what upgrades / patches are we entitled to to receive. I've seen some of your new videos which has some features not included in our version, and there are perhaps also some bug fixed we're in need of.

Finally is there a document on the upgrade procedure for PE?

Mark

**Comment by t0mmyz7** [comment]
+1 on this request. We should have a page in the admin login with release history and update links/instructions.

**Comment by cristianhumelnicu** [comment]
@enviroeye 

When u build any dashboard , just looking in to the bottom of page , right side ... and there you will see TB version

**Comment by t0mmyz7** [comment]
@cristianhumelnicu Sorry I don't think this is true any more, at least not for PE edition. No version number is there. 

![image](https://user-images.githubusercontent.com/31729091/53287595-070e4880-3787-11e9-95e6-bdcac874d77d.png)

**Comment by cristianhumelnicu** [comment]
For cloud version of TB  PE , work. I dont know for PE on premises...

**Comment by cristianhumelnicu** [comment]
I thing you can find what TB edition have in pom.xml file...

**Comment by t0mmyz7** [comment]
looking in the pom.xml is not useful for day to day operations. Think WordPress, they have a nice update / news section in the admin panel.

**Comment by gjweppler** [comment]
Is there a way now to display the version number in TB PE (cloud version)?

**Comment by hamburml** [comment]
Could you please add this? A simple info/about feature?

**Comment by woodyjon** [comment]
Indeed, version number is shown at the bottom of the screen in a dashboard for the TB PE cloud (demo cloud), **but not** for on premise PE.

**Comment by woodyjon** [comment]
I found the way to display the version: in White Labeling > White Labeling, at the bottom there is a checkbox to display the platform version. Once checked, the version appears at the bottom right of the left menu.

**Comment by CooL16** [comment]
To check TB version on ubuntu: dpkg -l | grep thingsboard
centos: yum list installed | grep thingsboard

Here is a link for upgrade instructions: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/
