### ISSUE TITLE
feature request: New widget who displaying images according to specific value...

### ISSUE THREAD

**Issue by cristianhumelnicu** [thingsboard/thingsboard#1495]
Feature  Request 

@vparomskiy , @ikulikov,

Hello,

I think a widdget that can display different images according to a certain value is very useful.
It can be used to display , weather conditions , connected car applications ,  and so much more and I think this type of widgets will make the thinksboard platform  to be adopted by many users

I've found a similar request to the link
https://thingsboard.atlassian.net/projects/TB/issues/TB-77?filter=allissues

Do you have any plan for implementation of  this kind of  widgets ?

Thx!
Cristian

**Comment by cristianhumelnicu** [comment]
So ... any direction ? :)

**Comment by ssakharova** [comment]
Hello @cristianhumelnicu,

If you want to display different images in widgets, I recommend exploring the Image Map widget.
![image](https://github.com/user-attachments/assets/366f9338-79b9-465f-a155-dd9ddd78a88b)

**Comment by ssakharova** [comment]
Closed due to inactivity.
