### ISSUE TITLE
feature request: provide visual indication on which nodes have debug enabled in rule chain editor

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#1497]
It will be very useful to have a visual indication in the rule chain editor if debug is enabled for a node without having to go in the node to check.

**Comment by volodymyr-babak** [comment]
@t0mZ4 
Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-843) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our Release Notes to see all new additions to the platform in the subsequent releases.

**Comment by SuminDenys** [comment]
Hi @t0mZ4,

Thank you for your report! 

For now, there’s no possibility to see or change the status of the node without opening. We already have this request in our backlog, PROD-843. I am unable to provide you with an exact timeframe for implementing the proposed improvement.

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/reference/releases/)

If you have any further questions or require clarification, please let me know.
