### ISSUE TITLE
Update shared attribute widgets read client attribute if name collides

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#1501]
Using TB-2.2.0 CE
"Update shared attribute" widget (for all data type) show this behaviour:
One device has a shared attribute named "status". An "Update shared string attribute" is included in a dashboard controlling such shared attribute.
If now an extrernal process posts a value change, via MQTT interface, to an attribute named "status" as well, for the _same_ device,  a **client** attribute named "status" is created for that device.
From this point on, changes made through the widget are applied to the shared attribute, but the widget will update the displayed value for both changes to the shared attribute "status" and changes to the **client** attribute "status". 
Although the presence of two attributes, one shared and one client, having the same name, is not a recommended situation, it may well happen by unintended operation and cause a behaviour in the dashboard creating confusion and need to investigate.
One would expect that the "Update _shared_ attribute" widgets only deals with _shared_ attributes.

**Comment by albtrentadue** [comment]
Hello
Is this issue going to be investigated?
IMHO, this issue reveals two inconsistencies:
1. If I create a **shared** attribute named 'status', how can I control its value from client side, given that any external process requesting changes to such attribute (through topic 'v1/devices/me/attributes') will instead create/change a **client** attribute with same name, in this case, 'status'?
2. Why the "Update **shared** attribute" widget reacts also to changes to a **client** attrivute with the same name?

**Comment by mykhailokornieiev** [comment]
Hi
Not sure if this ticket is still relevant for you, but it's known behavior for Input Widgets (both deprecated "update server/shared attributes" and new "update multiple attributes" widgets) and it uses just the latest value. It won't be fixed due to the design of Thingsboard, and the only correct workaround is using a different attribute names.
