### ISSUE TITLE
cassandra - change of TS_KV_PARTITIONING value leads to data not retrieved 

### ISSUE THREAD

**Issue by vicuzz** [thingsboard/thingsboard#1505]
Hello, i have tried to change the TS_KV_PARTITIONING from MONTHS to INDEFINITE and i have noted that the column partition in the ts_kv_cf table is set to 0.
If i change again to MONTHS, the column partition is set to the correct epoch time, but the records with value of 0 are not retrieved and displayed.
there's a way to mass change the rows where partition=0 with the epoch time? partition is a primary key.
thingsboard 2.3.0 and cassandra 3.0.9

**Comment by vicuzz** [comment]
I found that the default value of TS_KV_PARTITIONING in the 2.1.3 version was changed from MONTHS to INDEFINITE, perhaps leading to the same issue i haved

**Comment by chienfuchen32** [comment]
@ashvayka is it possible change `TS_KV_PARTITIONING` by any program or script? thanks.

**Comment by volodymyr-babak** [comment]
@chienfuchen32 
ThingsBoard team doesn't have any tool at the moment to do migration between different ts kv partitions. 
We'll probably how something in the future, but at the moment you'll need to implement your own script using CQL or Java program to migrate from one partition type to another.
