### ISSUE TITLE
image-map

### ISSUE THREAD

**Issue by lddfor** [thingsboard/thingsboard#1506]
Hello:
    I want to add my own picture in the image-map.js file. How should iconUrl write it?
    Now with a picture of the Google path. If I do this? Thank you.

**Comment by anton-pytel** [comment]
![image](https://user-images.githubusercontent.com/15068798/60087353-27eaa880-973d-11e9-8979-417257c0c345.png)

our "shop" is defined as realation query - 
![image](https://user-images.githubusercontent.com/15068798/60087418-4781d100-973d-11e9-87a2-3f677e080e41.png)


obtaining entity (either asset, device, or ...)
whose server attribute is name "image" with value eg. "http://www.tokyostationcity.com/en/information/images/stationyard_map_b1.png"
