### ISSUE TITLE
Get entity info from rule nodes.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#1509]
The various TB entities (i.e. customers, users, devices, assets) have a set of info fields that can be set by the UI.
For example, for a customer you can set a "description", "address", "phone" etc...

I can't see any way of reading these fields from the rule engine.

Can a new node be added to handle this?

**Comment by ashvayka** [comment]
Yes, of cource, it is possible. Just need to find some time to do this. @ShvaykaD I hope you can find time to do this.

**Comment by fotis400** [comment]
@ashvayka Just updated to v2.3.1 and as I see the requested rule node is included.

Thank you!
