### ISSUE TITLE
Recommended plotting method?

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1511]
Hi there,
is there any method recommended for plotting and custom visualization? If so, is there any example of how to use it? I have not found one in the contribution guide

Also, if anyone uses custom libraries for charting, what kind of libraries are you using? Could you share any examples?

**Comment by alexsmartens** [comment]
In case someone is interested in this question, I implemented what I wanted to with [d3](https://github.com/d3/d3).
You can load directly from [d3js.org](https://d3js.org/), [CDNJS](https://cdnjs.com/libraries/d3), or unpkg.

**Comment by alexsmartens** [comment]
I'm closing this issue because of no interest to this topic from the community. 
Would be glad to open it if anyone wants to keep it going

**Comment by alexsmartens** [comment]
[This post](https://github.com/thingsboard/thingsboard/issues/1257#issuecomment-441048564) suggests using [chartjs](https://www.chartjs.org/)

**Comment by gzlz** [comment]
Hello alexmartens, 
I would like to plot telemetry in frequency domain no in time domain. Do you have any advice to do it?
