### ISSUE TITLE
ruleChain holds a lot of tbMsg causing memory overflow

### ISSUE THREAD

**Issue by JerryZhangCN** [thingsboard/thingsboard#1514]
In the process of using the thingsboard v2.3.0 for data collection, there was a memory overflow problem. We analyzed the heap memory file and found that the ruleChain holds a large number of tbMsg objects, which seems to be a ruleChain that cannot be processed in time. The message entering the queue, maybe where is the configuration of our place wrong? We are using the postgres database, probably connected to 1000 devices, and there will probably be 50 data points per second access, server memory is 16GB, 4 cores, below is our configuration information
[thingsboard.txt](https://github.com/thingsboard/thingsboard/files/2899528/thingsboard.txt)

![image](https://user-images.githubusercontent.com/26397027/53320114-9181b400-390f-11e9-8938-07d9eca7e4ad.png)

This problem has plagued me and my team for a long time. We are eager to get your support. Thank you very much.

**Comment by ashvayka** [comment]
I see that your ThingsBoard instance uses 214 MB and not 16GB as you identified (or at least 2 GB). The memory overflow may happen if the amount of messages you produce is more then your DB can handle. We can protect from this in future, but it will not fix the main problem. The common case when this is happening if you put some of your rule nodes to debug and each message from device is causing multiple messages to DB (NxDebugRuleNodesCount+1) per each original message.

**Comment by JerryZhangCN** [comment]
Thank you  for your reply, I am embarrassed by my description of the error. In fact, there is a memory leak in my system. I understand that ThreadPoolExecutor needs a lot of memory, especially when there are a lot of data messages, but in fact I have a very strange problem. When I use the test tool to test a lot of data, the performance of the program is normal, the memory will be occupied. It has been growing. In my understanding, when the message in the queue is processed, the memory usage should be returned to the test before the GC should be performed, but the program does not perform as it is, it still maintains a high occupancy rate. This has caused me trouble. I don't know if it is a leak in my program, because everything from the heap memory analysis seems normal, maybe I don't understand it clearly, I want to get your help, thank you very much.

**Comment by JerryZhangCN** [comment]
I monitored the gc log while I was testing. I was surprised to find that there was no gc log record for about half an hour during my monitoring. Is this due to the program's restriction on gc?
