### ISSUE TITLE
Thingsboard 2.2.0.PE Deque full error

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1515]
Hi,

I get the following error message when I tried to login.
 I attached the log.

https://drive.google.com/open?id=1B20o8nKB9sBlWJjVl-BlRynh3dS8xAiu

**Comment by IvanSemenenko** [comment]
Hi JozsefGuyas,

You ought to configure or restart cassandra service, please.
The snippet from the attached log points out directly.
2019-02-25 08:39:18,567 [ForkJoinPool-1-worker-0] ERROR o.t.server.actors.ActorSystemContext - Could not save debug Event for Node
com.datastax.driver.core.exceptions.NoHostAvailableException: **All host(s) tried for query failed (no host was tried)**

Additionally, if you are our paid customer it would be great if you will create requests
in our customer portal.

Regards,

**Comment by JozsefGuyas** [comment]
I have restarted it, and It works. 
Could you tell me what could be the problem?

**Comment by IvanSemenenko** [comment]
Hi JozsefGuyas,

You ought to look at cassandra logs
/var/log/cassandra/*
to know the causes. 
But it will be a post-mortem investigation.

Regards,

**Comment by JozsefGuyas** [comment]
What is the best solution, the cassandra or postgresql? I am using tb with cassandra, and I have lot of problem with the cassandra. I have tried to postgresql in another server . it seem it woks fine. What is the best for thingsboard?

**Comment by IvanSemenenko** [comment]
Hi JozsefGuyas,

Thank you for your question.

TB has four DB configurations backed by three types of DB.
Types of DB
HSQLDB - only for testing. We don't recommend it in production environments
PostgreSQL
Cassandra - our mainstream DB
and the fourth type of DB configurations is Hybrid
https://thingsboard.io/docs/reference/#sql-vs-nosql-vs-hybrid-database-approach

Your choice of DB ought to be based on your skills in these database engines.

Regards,

**Comment by ashvayka** [comment]
Deque full happens because you lost connection to Cassandra (and reconnect is not successful) and the queue of messages is full. I suggest to check health of your DB (or DB cluster)

**Comment by fjpa121197** [comment]
@ashvayka  Hi, where can I change the queue size? My database is has not lost connection (I checked the log files) but I still get Deque Full error. https://github.com/thingsboard/thingsboard/issues/3194
