### ISSUE TITLE
How to reversely control devices connected to the thingsboard through the gateway

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1523]
I can use the control widget to control the devices that are directly connected to the thingsboard.
Now I have a device that is connected to the thingsboard through the gateway, I want to control the device through the gateway, how can I do?

My gateways name is "gateway001", and my device connected to the gateway is named "esp8266_001".
Can you help me see which of my steps are wrong?

Firstly, I make a dashboard the bind the target device "esp8266_001", I don't know which device should be bind? the "gateway001" or the "esp8266_001".
![image](https://user-images.githubusercontent.com/31084798/53615155-9e581d80-3c17-11e9-9016-243bba19df3e.png)

Secondly, On the gateways extension configuration tab, I add the server side RPC request, and my mqtt broker's status is Sync.
![image](https://user-images.githubusercontent.com/31084798/53615204-d5c6ca00-3c17-11e9-8d58-5d12c0d581db.png)

Thirdly, In my esp8266's code, I subscribe the topic "sensor/esp8266_001/request/+/+".
Then I clicked the On/Off button on the dashboard, But I can receive any message from the topic I subscribed.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
