### ISSUE TITLE
Debug message persistance

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#1525]
Hi there,

Is there a way to purge old debug messages from the database, or is there a way to set a retention policy?

We have been doing a lot of development/debug and its using up all our hard drive space.

Also, it would be helpful to be able to search/filter debug output in the event logs in the rule chain nodes to aid in debugging.

Mark

**Comment by volodymyr-babak** [comment]
@enviroeye 
this is already available in the TB 3+ version.
You can control time-to-live with the next env variable: **SQL_TTL_EVENTS_DEBUG_EVENTS_TTL**
Here are more parameters to configure:
https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters

Filtering is availabe in 3.3.3 as well:
![image](https://user-images.githubusercontent.com/3466101/155345404-a30fd069-f4da-4547-80e3-3a7ce2e0a140.png)
