### ISSUE TITLE
Adding tooltip to custom widget

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1531]
I'm trying to use `d3-tooltip` for showing a tooltip on a custom chart. The tooltip is to be shown/hided on `mouseover`/`mouseout`. 
This works flawlessly on my web implementation of the widget, but when I add the widget to thingsbord the tooltip never shows up. Apparently this happens because thinsboard has its custom elements over the chart. I did not find anything about tooltip development in thingsboard documentation too.
How can a tooltip be added to a custom chart?

**Comment by alexsmartens** [comment]
[Update]: I've noticed that `d3-tooltip` executes on `mouseover`, however the actual tooltip is not displayed

**Comment by alexsmartens** [comment]
Hi @ashvayka, @ikulikov, @mp-loki, @Terny22,
could you please help here?

**Comment by mp-loki** [comment]
ThingsBoard UI is built on AngularJS Material, so I suggest you use md-tooltip https://material.angularjs.org/latest/api/directive/mdTooltip

**Comment by alexsmartens** [comment]
Hi @mp-loki,
thanks for your response. I just realized that the tooltip in AngularJS Material is a different thing from what I am looking for. I am working on creating a chart tooltip for a custom chart, like the one ThingsBoard has for default charts (as in the figure below). 
Can you please suggest what I can use for that one?


![image](https://user-images.githubusercontent.com/26261714/54127838-1923f400-43e1-11e9-88ca-d775c37d4cfe.png)

**Comment by luPhz** [comment]
Thingsboard is using the [flot library](https://github.com/flot/flot) to draw charts.
There is a wrapper module called [TbFlot](https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/widget/lib/flot-widget.js) that is used by the chart widgets. It handles various widget settings, data updates and ... mouse interaction and **tooltips**.

**Comment by alexsmartens** [comment]
Hi,
I've developed a widget and want to add it to the widget library, let's say to the _Charts_ bundle. So, I did the following:
1) I imported my widget to `widget.service.js`
```
import TbMyWidget from '../widget/lib/my-widget';
...
$window.TbMyWidget = TbMyWidget;
```
2) Added my widget to `charts.json`:
```
{
    "alias": "my_new_widget",
    "name": "My New Widge",
    "descriptor": {
      "type": "timeseries",
      "sizeX": 8,
      "sizeY": 5,
      "resources": [],
      "templateHtml": "",
      "templateCss": ".legend {\n    font-size: 13px;\n    line-height: 10px;\n}\n\n.legend table { \n    border-spacing: 0px;\n    border-collapse: separate;\n}\n\n.mouse-events .flot-overlay {\n    cursor: crosshair; \n}\n\n",
      "controllerScript": "self.onInit = function() {\n    self.ctx.flot = new TbMyWidget(self.ctx);    \n    console.log(\"My TEST NEW\")   \n}\n\nself.onDataUpdated = function() {\n    self.ctx.flot.update();\n}\n\nself.onResize = function() {\n    self.ctx.flot.resize();\n}\n\nself.onEditModeChanged = function() {\n    self.ctx.flot.checkMouseEvents();\n}\n\nself.onMobileModeChanged = function() {\n    self.ctx.flot.checkMouseEvents();\n}\n\nself.getSettingsSchema = function() {\n    return TbMyWidget.settingsSchema('graph');\n}\n\nself.getDataKeySettingsSchema = function() {\n    return TbMyWidget.datakeySettingsSchema(true);\n}\n\nself.onDestroy = function() {\n    self.ctx.flot.destroy();\n}\n",
      "settingsSchema": "{}",
      "dataKeySettingsSchema": "{}",
      "defaultConfig": "{\"datasources\":[{\"type\":\"function\",\"name\":\"function\",\"dataKeys\":[{\"name\":\"f(x)\",\"type\":\"function\",\"label\":\"First\",\"color\":\"#2196f3\",\"settings\":{\"showLines\":true,\"fillLines\":true,\"showPoints\":false},\"_hash\":0.8587686344902596,\"funcBody\":\"var value = prevValue + Math.random() * 100 - 50;\\nvar multiplier = Math.pow(10, 2 || 0);\\nvar value = Math.round(value * multiplier) / multiplier;\\nif (value < -1000) {\\n\\tvalue = -1000;\\n} else if (value > 1000) {\\n\\tvalue = 1000;\\n}\\nreturn value;\"},{\"name\":\"f(x)\",\"type\":\"function\",\"label\":\"Second\",\"color\":\"#ffc107\",\"settings\":{\"showLines\":true,\"fillLines\":false,\"showPoints\":false},\"_hash\":0.12775350966079668,\"funcBody\":\"var value = prevValue + Math.random() * 100 - 50;\\nvar multiplier = Math.pow(10, 2 || 0);\\nvar value = Math.round(value * multiplier) / multiplier;\\nif (value < -1000) {\\n\\tvalue = -1000;\\n} else if (value > 1000) {\\n\\tvalue = 1000;\\n}\\nreturn value;\"}]}],\"timewindow\":{\"realtime\":{\"timewindowMs\":60000}},\"showTitle\":true,\"backgroundColor\":\"#fff\",\"color\":\"rgba(0, 0, 0, 0.87)\",\"padding\":\"8px\",\"settings\":{\"shadowSize\":4,\"fontColor\":\"#545454\",\"fontSize\":10,\"xaxis\":{\"showLabels\":true,\"color\":\"#545454\"},\"yaxis\":{\"showLabels\":true,\"color\":\"#545454\"},\"grid\":{\"color\":\"#545454\",\"tickColor\":\"#DDDDDD\",\"verticalLines\":true,\"horizontalLines\":true,\"outlineWidth\":1},\"legend\":{\"show\":true,\"position\":\"nw\",\"backgroundColor\":\"#f0f0f0\",\"backgroundOpacity\":0.85,\"labelBoxBorderColor\":\"rgba(1, 1, 1, 0.45)\"},\"decimals\":1,\"stack\":false,\"tooltipIndividual\":false},\"title\":\"My New Widget\",\"dropShadow\":true,\"enableFullscreen\":true,\"titleStyle\":{\"fontSize\":\"16px\",\"fontWeight\":400},\"mobileHeight\":null}"
    }
  }
```
However my widget is not showing up on Chart bundle page. 

**Would you please suggest how I can add my widget to an existing widget bundle?**

**Comment by alexsmartens** [comment]
The above question is a separate issue, so I'm continuing it in #1684.
As I've handled adding a tooltip to a custom widget, I'm closing this issue.
