### ISSUE TITLE
i need a help in linking sms gateway with rulechain script.

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1532]
hi ,
   i have a sms gateway , i tried to link that with script in rulechains but it shows XMLHttpRequest not found . i need a help.

**Comment by volodymyr-babak** [comment]
@gopirathnamt 
please provide more details on your issue:
1. configuration of your rule chain
2. configuration of your rule node
3. information on how to send data over SMS gateway and some sample how to use it from the command line or some other debug tool.

Thanks.
