### ISSUE TITLE
Unable to use console.log

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1533]
Unable to use console.log . I dont know why , is there any other option available ?

**Comment by alexsmartens** [comment]
@gopirathnamt,
have you figured how to use console.log() in your case?

**Comment by gopirathnamt** [comment]
Yes use $log.log()
Don't forget to mention the $log in function arguments

**Comment by alexsmartens** [comment]
I am intending to use it for widget development, in this case I have a class instead of a function. When I add `$log` into constructor it is not injected, hence `$log` is undefined inside the class. Here is a code snippet of how I am doing it:
```
export default class TbFlot {
    constructor(ctx, chartType, $log) {
...
```
What do you think?
