### ISSUE TITLE
feature: add Last Activity Time to Group View (in PE)

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#1534]
Add the ability to add lastActivityTime and Active status to device/asset groups in columns edit.

**Comment by Ultrazombie** [comment]
Hello @t0mZ4 
Please explain in more detail. If it is still relevant, then I will pass it on to the developers

**Comment by t0mZ4** [comment]
this is now possible to do, so closing this ticket @Ultrazombie
