### ISSUE TITLE
Digital Gauge not update with animation enabled

### ISSUE THREAD

**Issue by initialChris** [thingsboard/thingsboard#1540]
if I enable the animation in any digital gauges, it refresh his value every two uploads of attributes or time series.
Instead If I disable the animation it refresh on every upload.

**Comment by scientist1642** [comment]
Thanks @initialChris. Same happened with me, unless I disable animation, widget misses some updates and doesn't refresh. V 2.2.0

**Comment by ecmap** [comment]
please fix it, otherwise don't provide the Enable animation option....(the main problem)

**Comment by itnas** [comment]
Still  happens with me TB 2.4.3

**Comment by den1jkee** [comment]
Hello, 
This issue was fixed in the latest versions ThingsBoard.
