### ISSUE TITLE
Thingsboard PE v2.2.1 - Reverse proxy server (Apache) for SSL access of dashboard 

### ISSUE THREAD

**Issue by agm30** [thingsboard/thingsboard#1541]
I'm running Thingsboard PE edition on AWS. 

I'm trying to access the dashboard over HTTPS and I was able to refer to some of the earlier issues which suggest installing a Nginx or Apache reverse proxy server. 

- I installed Apache and tried to start it on port 80 but that does not work since `HAProxy` docker container is listening on both 80 and 443. 
- I want to generate certificates with certbot but it does not work since 80 is occupied. 
- I know that the server is internally running on 8080. Where is this redirect from 80--->8080 happening? 
- Is the load balancer `HAProxy` being used even though I'm not running a cluster? Can I disable it from listening on 80 and 443 by modifying the `docker-compose.yml` (also where can I find this)
- Is it better to use `HAProxy` load balancer to generate certs? If so, how can I do that?
- I've already referred to #1294 and https://thingsboard.io/docs/reference/msa/#deployment but things are still not clear to me.

I can see that from v2.2.2 thingsboard runs a microservices architecture. On my AWS machine I see two docker containers 
- `xalauc/haproxy-certbot:1.7.9` and `qoomon/docker-host`. 
-  So it looks like the first container is the HAProxy is a reverse proxy load balancer with certbot. It can create certs for free and then route requests to backend servers. 
-  The second container is the `docker-host` which is used to route all the traffic to the container. 

----
- Why are we using both these containers at the same time?
- Whats the best way to run the dashboard over SSL/TLS? Should I use the HAProxy certbot image to generate the certs or disable it to run Apache server as a reverse proxy.

**Comment by agm30** [comment]
Update: 
- I decided to abandon the efforts to use Apache or Ngnix as a reverse proxy server. 
- Instead I used the `haproxy-certbot` to generate new certificates and use that as a reverse proxy server. 
- This works except that https was not being enforced. So I had  to change the `haproxy.cfg`. I commented out `redirect scheme https if !letsencrypt_http_acl { env(FORCE_HTTPS_REDIRECT) -m str true }` and added a new line `redirect scheme https code 301 if !{ ssl_fc }`.

Now I get the dashboard on HTTPS. 

Please let me know if this is the right way to go about it.

**Comment by IvanSemenenko** [comment]
Hi agm30,

Thank you for your request.
You ought to transform the string
from 
redirect scheme https if !letsencrypt_http_acl { env(FORCE_HTTPS_REDIRECT) -m str true }
to 
redirect scheme https if !letsencrypt_http_acl 
or 
redirect scheme https if !letsencrypt_http_acl #{ env(FORCE_HTTPS_REDIRECT) -m str true }
:-)

Regards,

**Comment by mujahed1987** [comment]
Hi,
I have similar issue, I am trying to force https redirect, I tried many ways like the solutions up but nothing works, also I have tried to use the new syntax [here](https://www.haproxy.com/documentation/aloha/9-5/traffic-management/lb-layer7/http-redirection/#examples-of-traffic-redirection), but also It does not works, I didn't change any of the other default configurations. 
I am using the docker microservices with version 2.2.0 and I am restarting the haproxy-certbot to apply the new configurations.
any one can help me please?

**Comment by michalfapso** [comment]
I don't know if it helps you, but I've put together a docker-compose.yml for Thingsboard + Nginx reverse proxy with automatic Let's Encrypt certificates: https://github.com/michalfapso/thingsboard_docker_https

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
