### ISSUE TITLE
White labeling on exit with unsaved changes bug

### ISSUE THREAD

**Issue by LockiStrike** [thingsboard/thingsboard#1542]
Hi,
I found an ui issue on PE version.
**Steps to reproduce**: In the `White Labeling` point of menu go to the `White Labeling` and make any changes (e.g. change primary palette) then without saving click on the `System settings` label in breadcrumbs at the top. The dialog about unsaved changes will appear twice.
I would be very grateful if you could take a look on it and fix it. 
I understand that this is not a bug that break some logic but it leads to lack of trust from customers.
Thank you in advance.

**Comment by Ultrazombie** [comment]
Do not reproduce on the latest ThingsBoard versions
