### ISSUE TITLE
Pie chart widget to show total of Timeseries

### ISSUE THREAD

**Issue by astroas** [thingsboard/thingsboard#1545]
Hi,
Is it possible to have a Pie chart widget show the total of Timeseries? I have 3 Timeseries values and would like to see the total of the last 24 hours or see historical data using the timewindow.
Or can I use the Timeseries Bar chart and map the total of the Timeseries to a Pie chart?
Thanks

**Comment by astroas** [comment]
I worked it out if anyone is interested.

Create a new Time Series widget.
Add to resources https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js 
HTML `<canvas id="pieChart"></canvas>`
JavaScript
```
self.onInit = function() {
    
     var pieData = {
        labels: [],
        datasets: []
    };

    var dataset = {
        data: [],
        backgroundColor: [],
        borderColor: [],
        borderWidth: [],
        hoverBackgroundColor: []
    }
    
    pieData.datasets.push(dataset);
    
    for (var i=0; i < self.ctx.data.length; i++) {
        var dataKey = self.ctx.data[i].dataKey;
        pieData.labels.push(dataKey.label);
        dataset.data.push(0);
        var hoverBackgroundColor = tinycolor(dataKey.color).lighten(15);
        var borderColor = tinycolor(dataKey.color).darken();
        dataset.backgroundColor.push(dataKey.color);
        dataset.borderColor.push('#fff');
        dataset.borderWidth.push(5);
        dataset.hoverBackgroundColor.push(hoverBackgroundColor.toRgbString());
    }

    var ctx = $('#pieChart', self.ctx.$container);
    self.ctx.chart = new Chart(ctx, {
        type: 'pie',
        data: pieData,
        options: {
            responsive: true,
            maintainAspectRatio: true,
        }
    });    
    self.onResize();
};

self.onDataUpdated = function() {
    for (var i = 0; i < self.ctx.data.length; i++) {
        var cellData = self.ctx.data[i];
        if (cellData.data.length > 0) {
            var sum = cellData.data.map( v => v[1] ).reduce( (sum, current) => sum + current, 0 );
             self.ctx.chart.data.datasets[0].data[i] = parseFloat(sum);
        }
    }
    self.ctx.chart.update();
};

self.onResize = function() {
    self.ctx.chart.resize();
};

```

**Comment by jauodwenna** [comment]
Hi,
is it possible for pie chart that shows percent values to be a time series? do you have a sample for it?

**Comment by astroas** [comment]
I don’t think you can display the values as a percentage.
You can look at https://www.chartjs.org/docs/latest/charts/doughnut.html  for further information on the chart.

**Comment by DevanshAtray** [comment]
@astroas thanks for posting this code. I am having some problems understanding the onDataupdated function. What is going on in the nested if loop? Also were you able to create a chart that displays last 24 hours total? If so, then does it reset after completion of 24 hours or retains the previous data? Thanks!

**Comment by santobedi** [comment]
> I worked it out if anyone is interested.
> 
> Create a new Time Series widget. Add to resources https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js HTML `<canvas id="pieChart"></canvas>` JavaScript
> 
> ```
> self.onInit = function() {
>     
>      var pieData = {
>         labels: [],
>         datasets: []
>     };
> 
>     var dataset = {
>         data: [],
>         backgroundColor: [],
>         borderColor: [],
>         borderWidth: [],
>         hoverBackgroundColor: []
>     }
>     
>     pieData.datasets.push(dataset);
>     
>     for (var i=0; i < self.ctx.data.length; i++) {
>         var dataKey = self.ctx.data[i].dataKey;
>         pieData.labels.push(dataKey.label);
>         dataset.data.push(0);
>         var hoverBackgroundColor = tinycolor(dataKey.color).lighten(15);
>         var borderColor = tinycolor(dataKey.color).darken();
>         dataset.backgroundColor.push(dataKey.color);
>         dataset.borderColor.push('#fff');
>         dataset.borderWidth.push(5);
>         dataset.hoverBackgroundColor.push(hoverBackgroundColor.toRgbString());
>     }
> 
>     var ctx = $('#pieChart', self.ctx.$container);
>     self.ctx.chart = new Chart(ctx, {
>         type: 'pie',
>         data: pieData,
>         options: {
>             responsive: true,
>             maintainAspectRatio: true,
>         }
>     });    
>     self.onResize();
> };
> 
> self.onDataUpdated = function() {
>     for (var i = 0; i < self.ctx.data.length; i++) {
>         var cellData = self.ctx.data[i];
>         if (cellData.data.length > 0) {
>             var sum = cellData.data.map( v => v[1] ).reduce( (sum, current) => sum + current, 0 );
>              self.ctx.chart.data.datasets[0].data[i] = parseFloat(sum);
>         }
>     }
>     self.ctx.chart.update();
> };
> 
> self.onResize = function() {
>     self.ctx.chart.resize();
> };
> ```

Hello, 
I got `Error: ReferenceError:Chart is not defined Line 31 column 26 of script.` Any solution to it? Thank you.
