### ISSUE TITLE
Since v2.3, webUI loops when customer tries to edit attributes

### ISSUE THREAD

**Issue by tensojka** [thingsboard/thingsboard#1547]
Permissions checking has been expanded in commit 1d1fd7711f9189f3f2aa06e3625f351ec63bd798. This commit is included in release 2.3. It caused customers to (rightly) be unable to write attributes.

When a customer attempts to write a server attribute in the webUI, an infinite loading slider appears and the underlying API operation returns 403.

The option to write attributes should be hidden if a customer is logged in.

P. S. for us, the API change was breaking and wasn't mentioned in the release notes. And, as seen here, was breaking for the webUI too. Could the release notes be amended to include a warning about this?

**Comment by den1jkee** [comment]
Hi, 
This issue was fixed in the latest versions of ThingsBoard since version 3.0. Thank you for your feedback, and sorry for the delay.
Best regards,
Denys.
