### ISSUE TITLE
How to Use Websocket API on Server Code

### ISSUE THREAD

**Issue by madhu781** [thingsboard/thingsboard#155]
Hi All,
I want to use Websocket API in Server code. Please let me know, how to use this and how can i show to UI.

Regards,
Madhu

**Comment by ssmaurya** [comment]
Web socket request packets have changed from 1.2 to1.3. I believe documentation update post 1.3 release might provide information on websocket usage. For now looking at javascript code for UI might give you clues on how to use it.

**Comment by joxxe274** [comment]
Hi all,

Any solution?

I can't connect by websocket connection

**Comment by SERGAMO** [comment]
After taking a look at the error log messages and enabling the DEBUG log from Thingsboard 1.3, I could figure it out. After the initial connection to the websocket with something like:

**_ws://THINGSBOARD_IP:8080/api/ws/plugins/telemetry?token=USER_TOKEN_**

Once the connection is stablished, you can subscribe to 3 properties: "attrSubCmds", "tsSubCmds", "historyCmds"
With tsSubCmds I  finally could have the last values updated at the moment.

Enabling the DEBUG log and taking a look at it, I could find the cmdId for every property on my device.

So, if you want to subscribe to a DEVICE, you can subscribe to ALL the attributes with something like:
**_`{"tsSubCmds":[{"entityType":"DEVICE","entityId":"YOUR_DEVICE_ID","cmdId":1}],"historyCmds":[],"attrSubCmds":[]}`_**

If you want some other attribute, you add the pair keys/attribute for instance
**_`{"tsSubCmds":[{"entityType":"DEVICE","entityId":"YOUR_DEVICE_ID","keys":"temperature","cmdId":3}],"historyCmds":[],"attrSubCmds":[]}`_**

You can play with other values and see the logs to see what happens.

Hope this shed some light!

**Comment by joxxe274** [comment]
@SERGAMO 
I was trying that, but when i use this format url "ws://THINGSBOARD_IP:8080/api/ws/plugins/telemetry?token=USER_TOKEN" i can't connect, on my web log i can see the url is different, is like the system change the url to "http://my_thingsboardIP:8080/socket.io/?token=MY_TOKEN" and i cant connect.

Any idea? do u have an example with javascript? maybe node.js

**Comment by SERGAMO** [comment]
@joxxe274 
For the URL, I just followed the guide from the thingsboard web
https://thingsboard.io/docs/user-guide/telemetry/#websocket-api

I'm working with thingsboard 1.3.  Just for testing purposes and to find the right message for the subscription, I tested a couple of chrome extensions for websockets, like Simple WebSocket Client, and Smart Websocket Client.

For example, with Simple Websocket, I attach a screenshot with the interface, and how after sending the command, thingsboard server answers a the data and pushes the new values every time it changes. 

![image](https://user-images.githubusercontent.com/9613564/31388275-d440f1d0-adcd-11e7-9901-a4f6c0cbe1f0.png)

After testing a little bit more, I found that the cmdId key can be any number you want, is not directly related to the keys. If you don't add any key to the subsription messsge, it'll return all the data for the device.

You can restart thingsboard with DEBUG (change in logback file DEBUG for INFO") and take a look at the log and see what error messages throws to you.

**Comment by zarzaid** [comment]
anyone here know how to get the server attribute with websocket?

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
