### ISSUE TITLE
Originator Attributes node doesn't Save

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1551]
The scenario:

- Thingsboard PE, latest version as of 2019-03-13
- Many devices, having one shared attribute called "enabled", type boolean.
- One rule chain linked to the "inactivity event" with the following nodes:

"Input" -> "Originator Attributes" -(sucess)-> "Create Alarm" (Device Inactive) -(created)-> "To Email" -(sucess)-> "Send Email"

It kind of "works" in the sense that when the device goes inactive, the event is triggered correctly, and the email is sent.

The problem:

I want to customize the email message, so it contains the value of the "enabled" shared attribute (if available) in the email body, at the moment of the triggering of the event. However, when editing the "Originator Attributes" node, _nothing that is put into any of the fields (Except "Name" and "Description") is saved when the changes are applied._

In the end, the metadata is not enriched because no attributes are selected at all.

Enabling debug mode shows:

IN Event (Inactivity Event):
(metadata)
```
{
    "deviceType": "sense_ar",
    "deviceName": "Bluma sense AC_02"
}
```
(data)
```
{
    "active": false,
    "lastConnectTime": 1552486797009,
    "lastActivityTime": 1552486760365,
    "lastDisconnectTime": 1552483151732,
    "lastInactivityAlarmTime": 1552486828078,
    "inactivityTimeout": 60000
}
```

OUT Event (Sucess) has the SAME data.

**Comment by IvanSemenenko** [comment]
Hi mcpicoli,

Thank you for your request.

You ought to press the Enter button
after you have input the attribute name.

Regards,

**Comment by mcpicoli** [comment]
Well, it worked.

Completely non intuitive, but worked. Maybe some clarification of how this interface works is possible?

Thanks, anyway.
