### ISSUE TITLE
Return to dashboard with button

### ISSUE THREAD

**Issue by marianodo** [thingsboard/thingsboard#1555]
Hi,
I have a main dashboard with a table of different devices and then other dashboard showing details from each device. In the entity table I added a row_click action to navigate to the specific dashboard. Then, in the other dashboard, on a custom widget I add a widget header button action to return to the main dashboard (I don't want to use the top header for navigation) but doesn't work properly. I attached some image to show the issue.
The first image shows that I navigate to the second dashboard from the main dashboard
Paysandu : Main dashboard
Solar1 : Detail or second dashboard
![bugthings](https://user-images.githubusercontent.com/7087648/54433278-3b33b400-470a-11e9-9790-dcbad25cc158.png)

After click on action button to return to the main dashboard, the header shows like in the image:
Paysandu -> Paysandu
![bugthings2](https://user-images.githubusercontent.com/7087648/54433285-3ec73b00-470a-11e9-84e7-40da53b0ab94.png)

If I navigate to different devices and return each time, the header looks like the following image:
![image](https://user-images.githubusercontent.com/7087648/54433480-b09f8480-470a-11e9-95de-a4919f74acfa.png)

Besides this, I have an Alarm widget to show alarms and notification from all devices. In the main dashboard I can see notification from all the devices, after navigate to specific device, on that table I see notification only from that device, that is correct. But when I want to return to the main dashboard, the alarm widget still showing the specific device and I expect see all devices as before. This happend if I return clicking the action button. If I return using the top header this work fine.

Thanks

**Comment by marianodo** [comment]
I found the problem.  I configured wrong the action button. I unchecked the "Set entity from widget" option. This is checked by default

**Comment by Elgaatoo** [comment]
Hi Marianodo, 

were you able to do this linkage between dashboards with widgets? I am trying to find a solution where I link my main dashboard to other sub dashboards.

**Comment by marianodo** [comment]
Hi Elgaatoo
Yes I did it with the community edition. You have two option, the first one is adding an action to the widget. The action should be "Navigate to other dashboard".
The second option is add a little code inside the widget using stateController. [link](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#state-controller)
