### ISSUE TITLE
umqtt library and communication with Thingsboard

### ISSUE THREAD

**Issue by bricedenicedu69** [thingsboard/thingsboard#1559]
Hi,
I am currently trying to send sensor values to Thingsboard and try to see them displayed on the dashboard I've configured there. However, I don't understand how to initialize the MQTTClient using the umqtt library. I could easily do this with Adafruit IO because I found a really useful and easy-to-use tutorial, but I don't know to what correspond the different parameters required, which are username, password or any others. Deos anyone know how I should proceed ? I'd really appreciate some advice. Here's the link of the umqtt library from Micropython I am using. **https://github.com/micropython/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py**. I can also provide you with my Python code if needed.

**Comment by affoltep** [comment]
The problem seems to be, that umqtt from micropython only supports no authentication or user AND password authentication.
see the connect function of umqtt
```
 def connect(self, clean_session=True):
        self.sock = socket.socket()
        addr = socket.getaddrinfo(self.server, self.port)[0][-1]
        self.sock.connect(addr)
        if self.ssl:
            import ussl
            self.sock = ussl.wrap_socket(self.sock, **self.ssl_params)
        premsg = bytearray(b"\x10\0\0\0\0\0")
        msg = bytearray(b"\x04MQTT\x04\x02\0\0")

        sz = 10 + 2 + len(self.client_id)
        msg[6] = clean_session << 1
        if self.user is not None:
            sz += 2 + len(self.user) + 2 + len(self.pswd)
            msg[6] |= 0xC0
        if self.keepalive:
            assert self.keepalive < 65536
            msg[7] |= self.keepalive >> 8
            msg[8] |= self.keepalive & 0x00FF
        if self.lw_topic:
            sz += 2 + len(self.lw_topic) + 2 + len(self.lw_msg)
            msg[6] |= 0x4 | (self.lw_qos & 0x1) << 3 | (self.lw_qos & 0x2) << 3
            msg[6] |= self.lw_retain << 5

        i = 1
        while sz > 0x7f:
            premsg[i] = (sz & 0x7f) | 0x80
            sz >>= 7
            i += 1
        premsg[i] = sz

        self.sock.write(premsg, i + 2)
        self.sock.write(msg)
        #print(hex(len(msg)), hexlify(msg, ":"))
        self._send_str(self.client_id)
        if self.lw_topic:
            self._send_str(self.lw_topic)
            self._send_str(self.lw_msg)
        if self.user is not None:
            self._send_str(self.user)
            self._send_str(self.pswd)
        resp = self.sock.read(4)
        assert resp[0] == 0x20 and resp[1] == 0x02
        if resp[3] != 0:
            raise MQTTException(resp[3])
        return resp[2] & 1
```
it just checks whether self.user is defined an it expects as well a password. TB works with user (AccessToken) only, so connecting devices with micropython umqtt to TB seems not to work.

**Comment by mr-engin3er** [comment]
Hello, I have a similar issue regarding the mycropython MQTT library and communication with Thingsboard.
What I successfully did: 
Note: I used the same token for publish and subscribe.
Publish
          1. Connect Thingsboard MQTT broker.
          2. Successfully Publish attributes and telemetry data to Thingsboard.
Subscribe
         1. Connect Thingsboard MQTT broker.
         2. Successfully Subscribe to attributes topic.
 What is not working:
         1. Did not get any message from Thingsboard after successfully subscribe (topic = attributes).
         2. Subscribe loop on esp32 crash when publish data with paho MQTT broker with the same token and on the same topic.

After a lot of research, I found that Thingsboard MQTT broker is working in a different way from other brokers.
So do we have plans to make MQTT client for micropython as we have for python(tb-mqtt-client) and Arduino?

**Comment by SaberPhung** [comment]
Hello, I try to send value from Fipy (micropython) to thingsboard . I use following code. However, It shows error with 
File "/flash/lib/mqtt.py", line 157, in subscribe
MQTTException: 128

from mqtt import MQTTClient_lib
#from mqtt import MQTTClient_lib as MQTTClient
from network import WLAN
import machine
import time
def sub_cb(topic, msg):
   print(msg)
wlan = WLAN(mode=WLAN.STA)
wlan.connect("Sahin 2.4", auth=(WLAN.WPA2, "zme9CL9rAs"), timeout=5000)

while not wlan.isconnected():  
    machine.idle()
print("Connected to WiFi\n")
client = MQTTClient_lib("MQTT device", "demo.thingsboard.io", user="Device_access_token", password="my_password", port=1883)
client.set_callback(sub_cb)
client.connect()
client.subscribe(topic="v1/devices/me/telemetry")
while True:
    print("Sending ON")
    client.publish(topic="v1/devices/me/telemetry", msg="ON")
    time.sleep(1)
    print("Sending OFF")
    client.publish(topic="v1/devices/me/telemetry", msg="OFF")
    client.check_msg()
    time.sleep(1)

**Comment by manuargue** [comment]
Hi, I ported and adapted the official ThingsBoard Python SDK to MicroPython, you can find it here: https://github.com/coredumplabs/thingsboard-micropython. It can be installed with `upip.install('thingsboard-micropython')`.

It's based on the umqtt.robust built-in library of MicroPython, which I know it's not the best, but I didn't want to bloat it with dependencies. It supports token and basic auth, you can find [examples for basic auth here](https://github.com/coredumplabs/thingsboard-micropython/blob/main/examples/auth_basic.py).

Feel free to give it a try and let me know! :)

**Comment by mr-engin3er** [comment]
> Hi, I ported and adapted the official ThingsBoard Python SDK to MicroPython, you can find it here: https://github.com/coredumplabs/thingsboard-micropython. It can be installed with `upip.install('thingsboard-micropython')`.
> 
> It's based on the umqtt.robust built-in library of MicroPython, which I know it's not the best, but I didn't want to bloat it with dependencies. It supports token and basic auth, you can find [examples for basic auth here](https://github.com/coredumplabs/thingsboard-micropython/blob/main/examples/auth_basic.py).
> 
> Feel free to give it a try and let me know! :)

Hi, thanks for your contribution. I would love to try your module.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
