### ISSUE TITLE
CoAP usage architecture and DTLS

### ISSUE THREAD

**Issue by maximcherny** [thingsboard/thingsboard#156]
Hi,

This is more of a question / feature request.

1) Data protection in transit

With MQTT, one is able to configure TLS to protect the data in transit. However, I have not been able to find any mechanisms that would provide same for CoAP. It is possible to add DTLS to the Thingsboard CoAP server? I note that since the underlying implementation appears to be based on Californium it should be a matter of adding support for the built-in DTLS implementation with necessary config parameters?

2) The provided CoAP telemetry / attribute collection service assumes that the sensors will be pushing the data to the server (via POST). When using CoAP, it is also not uncommon for each sensor to run its own CoAP server and provide the telemetry data (such as sensor readings) to connecting clients. In this model, for example, the Thingsboard platform would essentially become a CoAP client and can either OBSERVE sensor readings from their respective servers, or simply GET them periodically. Can this model be easily realised in Thingsboard?

Thanks in advance.

**Comment by ssmaurya** [comment]
I believe if we have to make thingsboard server as a client,then service discovery is needed to discover coap clients behind firewall. I think it is possible to do if we have something like  lwm2m server embedded in thingsboard server. COAP DTLS is easier to support though.

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
