### ISSUE TITLE
Permission Denied in Public Dashboard when theres an Alarm Widget

### ISSUE THREAD

**Issue by Yinkci** [thingsboard/thingsboard#1561]
If there's no alarm widget, the public dashboard is working fine, but when I add an alarm widget  I can no longer access the Public Dashboard, it says permission Denied.

Screenshot: http://prntscr.com/n09pm0

It was not like this before

**Comment by alexmed** [comment]
try opening public link in incognito mode i.e. in any other browser where you are not currently logged in TB

i faced similar issue and it looked to me like system treats public visitors as Guests (i.e. not logged-in guys), instead logged-in visitors are considered Not-guests

im not saying its ok, but i think it explains the behavior

**Comment by Yinkci** [comment]
When testing the public link I always test it on incognito mode, plus our clients encountered it. They encountered it from different PC/Laptop.

**Comment by prassannajohnpaul** [comment]
I have been facing the same issue. @Yinkci

**Comment by den1jkee** [comment]
Hello,
This issue I can`t reproduce in the latest version ThingsBoard. Please write step to step how to reproduce this if this problem persists on the latest versions
Best regards,
Denys.
