### ISSUE TITLE
How to monitor mqtt transport's key performance metrics

### ISSUE THREAD

**Issue by spree1010** [thingsboard/thingsboard#1562]
Hi,

I am doing performance test with thingsboard performance test project on my local PC, and the maximum mqtt connection can be about 3800.  
My question is 
1. for mqtt transport part, is there any metric to monitor, like current mqtt connection 
2. Does thingsboard expose some key performance metric to monitor its performance?

Thank you!
Kun

**Comment by Ultrazombie** [comment]
Do you lack the ApiUsage page in new versions of ThingsBoard?
