### ISSUE TITLE
Dashboard entity alias "Entity name" limits to 100

### ISSUE THREAD

**Issue by biagio-ra** [thingsboard/thingsboard#1563]
**PROBLEM**
In the dashboards, when I add an "Entity alias" and when I use the "Entity Name" with the wildcard "%" it selects only 100 devices whose name starts with the string... but I have over 100 devices! This limit should be removed or increased.

**BACKGROUND**
From a dashboard, I want to be able to view a table of all devices. However the widgets require at least one "entity alias". 

So, here are some options:
- Create an entity alias by "Entity Name" and use the wildcard "%"
- Create an entity alias by "Device Type" (Only works if devices share the same type)
- Don't create any entity aliases **<-- Not allowed in TB**
- Use an alias called "All entities" **<-- Not available in TB**

**POSSIBLE CAUSE**
I noticed that in the Angular "entity.service.js" there is a function named "getEntitiesByNameFilter", which defaults to a page limit of 100. 
https://github.com/thingsboard/thingsboard/blob/ced63c4e70579f9567e05e1632322f226c7cce19/ui/src/app/api/entity.service.js#L317

**POSSIBLE SOLUTIONS**
One of these:
- Remove the limit (if it returns all values)
- Increase the limit to some very high number
- Allow the user to adjust the limit from the entity filter

**Comment by Ultrazombie** [comment]
Closed, as not active

**Comment by Nathan-ma** [comment]
Well yeah, why the limitation?
