### ISSUE TITLE
Change device owner

### ISSUE THREAD

**Issue by astroas** [thingsboard/thingsboard#1564]
Hi,

I am using Thingsboard PE version 2.3.0 and logged in as Tenant Administrator. I would like to change owner of a device but when i select the device there is no change owner icon. I only have add to group. 
What am i doing wrong?

**Comment by JarrodLodge** [comment]
Having the same issue, im on PE trial. Is that the reason?

**Comment by astroas** [comment]
I have now updated to 2.3.1 and I am able to change the owner.

**Comment by RondoRonaldo** [comment]
Glad your issue was solved.
