### ISSUE TITLE
Delete production data

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1569]
Hi,

I'm using thingsboard 2.3.0 with postgreSQL. I would like to delete some production data but I don't want to delete the device. How can I do that?

**Comment by Karabiy** [comment]
you can use the ThingsBoard REST API for those reasons, or go for the database direclty. You also can set the TTL for the upcoming data ( newer version feature ) both for PostgreSQL and Cassandra
ThingsBoard REST API: https://thingsboard.io/docs/reference/rest-api/
