### ISSUE TITLE
Allow nesting of the dashboards

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#157]
I believe that dashboards must be able to be nested. By nested I mean that on one dashboard you shall have a way to navigate directly to other ones.

This will greatly improve the experience provided to the customers, allowing to easily group functionality to separate dashboards (and access them by the default one acting as an overview screen), and that even complex menus will easy to be created.

For this to be achieved I believe the following changes are needed:
* A Special widget, that will lead to another dashboard (that is assigned to the same customer). Customizable icon and title would be great here.
* When inside a nested dashboard, a back button would be nice to appear, allowing back navigation. It would be even better if the top navigation bar was functionally as in other menus of thingsboard.
* Dashboards should have an extra option, to denote whether they are possible to be directly accessed (and thus appear in the dashboards menu of the client), or whether they are purely nested (so access is allowed only through another dashboard).

**Comment by Nippius** [comment]
That seems really confusing from a user perspective.

However you can already change from one dashboard to another. Just open the dashboard you want and on the top right corner click the "..." button (the horizontal one, not the vertical) and click the name of the current dashboard the show the list of the other available dashboards.

**Comment by pticaTor** [comment]
it is not confusing.
User case is: 
The user has dashboard where show short info for all user devices. 
If user want to show long info for single device they select this Special widget (Special field, etc.)

**Comment by fotis400** [comment]
I may not demonstrated it clear enough. I don't find anyhow confusing.

Essentially, I would like to create a "menu". A hierarchy of dashboards.

Lets say that a user has a system that included multiple devices, and various functionality. Lets say that this is a home automation system, for the purposes of the example, that includes a security system, a gardening system, power metering, HVAC etc.

The user is greeted by the default dashboard, that includes only generic information. For example that all devices are up and running, basic info such as the ambient temperature, etc.

The user uses the "special" widget to navigate specifically to the HVAC system. A new dashboard is presented with more details specific on the HVAC of the building.

The user decides to change the temperature setpoint. He/she further navigates to the settings dashboard and changes the setpoint.

Then he/she navigates back, to the HVAC dashboard to check the results, etc...



Now imagine to have 2-4 (or more) dashboards for each system (one with details, one with settings, one with manual controls, etc..), and multiple such systems as stated above. This will lead to a great number of dahsboards, and it will be really confusing for the user to select the correct one each time. Organizing them as a menu as stated above, I believe that will lead in a by far superior (and unique to thingsboard) experience. Instead of simple dashboards, we could provide to the customers even complex "applications".

**Comment by ashvayka** [comment]
Hi @fotis400 . You are absolutely right. This features has high demand and we've been thinking about this a lot recently.  We have already started implementation and will push first version of this feature in v1.3 ( v1.3 will be really interesting release). We can leave this issue open to collect your feedback about our vision of the feature. Before release we plan to make a video how to use it. 

Please note that our implementation is not about switching/navigating the dashboards, but about switching states of the dashboard and ability to stack this states. But in general, it covers the use case you have described.

**Comment by fotis400** [comment]
Nice, your approach sounds interesting... Any release estimations?

**Comment by masaryk** [comment]
hi @ashvayka where we can found more description of this feature in 1.3? thanks.

**Comment by fotis400** [comment]
I have just tried the new features in 1.3, and all I can say is that it is perfect! Far better that what I described.

For me there are no more to be done on this matter, and completely covers my use cases (and the recommendations done above).

Unless anybody else have any other thought on this, we can close the issue.
