### ISSUE TITLE
Text displaying incorrect value when Hovering Mouse over Trend Line on Widget Timeseries - Flot

### ISSUE THREAD

**Issue by DenMurphy** [thingsboard/thingsboard#1570]
I have a problem with "Timeseries - Flot" widgets not displaying the the correct Trend Line Data when hovering over a Trend Line.

**Situation:**

We are using Thingsboard v2.3.0.
Devices are LoRa devices. Data is pushed into TB using MQTT.
Dashboard shows a timeseries (last day), and the current temperature.

**Problem:**
After opening the dashboard, the widget displays 2 trend lines of temperature, Blue & Green in the example below. When hovering the mouse, the trend data displayed on Hover is displaying the data for the other trend line, and vice versa when hovering to the other trend line.

![image 1](https://user-images.githubusercontent.com/6964524/54788992-d1248d00-4c7c-11e9-852f-978dd112b3d9.png)

![image 2](https://user-images.githubusercontent.com/6964524/54788998-d2ee5080-4c7c-11e9-997b-5b4d238150f8.png)

The following are my Node Configurations:

![Temperatures - Datasources](https://user-images.githubusercontent.com/6964524/54789361-f8c82500-4c7d-11e9-9cb6-f6fd3bc47b7b.png)

![Temperatures - Data key configuration - temperature-a](https://user-images.githubusercontent.com/6964524/54789364-fbc31580-4c7d-11e9-8898-9087c7786f88.png)

![Temperatures - Data key configuration - temperature-b](https://user-images.githubusercontent.com/6964524/54789367-fe256f80-4c7d-11e9-98ef-e1994b153055.png)

![Temperatures - Advanced](https://user-images.githubusercontent.com/6964524/54789370-01206000-4c7e-11e9-8d93-a2564d5987db.png)

**Comment by descipher** [comment]
I have duplicated this bug and I can confirm this as an issue. Hovering hi lights one series but returns the values of the other series for display. Could be an indexing issue. I will take a look at the code and see if I can find it.

**Comment by descipher** [comment]
FYI if you disable Hover Individual and Enable Multiple Stacked it will display the correct values.

**Comment by descipher** [comment]
Corrected series sort return value order of tooltipIndividual mode. Commit #1578

**Comment by DenMurphy** [comment]
> FYI if you disable Hover Individual and Enable Multiple Stacked it will display the correct values.

I have temporarily disabled individual hover until the next release. Thanks @descipher

**Comment by Zulfi-ThinkIoT** [comment]
Can you please tell me to display avg, min and max values on the bottom right on a chart. As I only get 'avg' values displayed under the chart.

**Comment by sumin-denys** [comment]
Hi @Zulfi-ThinkIoT,

You can activate these values in the widget's advanced mode in the legend tab. I have added a screenshot below as a hint for you!
![image](https://github.com/user-attachments/assets/19828bc9-d21d-4cec-8a7d-239553a9b079)

**Comment by sumin-denys** [comment]
Hi @DenMurphy,

Thank you for your request. I am glad to inform you that this issue was resolved in the current ThingsBoard version. 

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/reference/releases/).

I am closing this issue. If you have any further questions, please feel free to create a new issue or reopen this one.
