### ISSUE TITLE
HA Postgres Design in Thingsboard DB design

### ISSUE THREAD

**Issue by cjkini** [thingsboard/thingsboard#1572]
Hi guys,

Anyone of u here have tried a PostgreSQL TB design with High Availability setup?

Please let me know how to do it. Your help is much appreciated.

Thanks

**Comment by absinthetized** [comment]
hi,

if you maind about managed services any major could vendor provides failover (expect at *least* 2 mins of blackout). Also AWS Aurora drop-in replacement for Postgres provides very fast failovers (~30-50 secs). Postgres and all the SQL RDBMS are scale up solutions, therefore HA means fast failovers: you cannot have proper rolling updates or the so.

On the DIY side, you could investigate stuff like [repmgr](https://repmgr.org/) by 2nd Quadrant or [Spilo/Patroni](https://github.com/zalando/spilo) by Zalando.

I was investigating these very topics in the past days.
