### ISSUE TITLE
Thingsboard REST API with swagger-ui

### ISSUE THREAD

**Issue by amy108** [thingsboard/thingsboard#1574]
![20190325143036](https://user-images.githubusercontent.com/48902828/54899383-a485a500-4f0a-11e9-86f0-5dfb03868c88.png)

i did authorize in local swagger-ui, but still renturn {
  "status": 401,
  "message": "Invalid username or password",
  "errorCode": 10,
  "timestamp": "2019-03-25T05:53:32.052+0000"
}，dont know why，i'm a newcomer,someone can help me plz?

**Comment by sanshengshui** [comment]
Hi, Please refer to the following documents, 
[JWT Authorization](https://thingsboard.io/docs/reference/rest-api/)
you will get the correct answer!
The most important of all, you should set 'X-ray Authorization to the Bearer $YOUR_JWT_TOKEN

**Comment by amy108** [comment]
> The most important of all, you should set 'X-ray Authorization to

thanks a lot,this page i have read already,and i got the token
![image](https://user-images.githubusercontent.com/48902828/54901826-a18eb280-4f12-11e9-81aa-daf2593540ed.png)
X-Authorization was also added...

**Comment by amy108** [comment]
i solved it with postman

**Comment by dipen-apptrait** [comment]
I am facing the same issue, can you please let me know the solution you used?

**Comment by ferchinas** [comment]
In case someone else needs a more detailed explanation.
You have to add the word "Bearer" plus a space and then the JWT token "Bearer YOUR_JWT_TOKEN"

**Comment by sebastian-lempert** [comment]
> In case someone else needs a more detailed explanation.
> You have to add the word "Bearer" plus a space and then the JWT token "Bearer YOUR_JWT_TOKEN"

Adding the word "Bearer" in front of "YOUR_JWT-TOKEN" really solved it. I missed this note in the official manual (https://thingsboard.io/docs/reference/rest-api/).

**Comment by vulcanux** [comment]
hello how can i connect angular for web development and ionic development using the telemetry from thingsboard profesional version,  through of swagger, i connect i have follow this guide https://thingsboard.io/docs/reference/rest-api/).

**Comment by srinivasankk7** [comment]
> 
> 
> In case someone else needs a more detailed explanation.
> You have to add the word "Bearer" plus a space and then the JWT token "Bearer YOUR_JWT_TOKEN"

this is really helped,, great help
