### ISSUE TITLE
Error requesting timeseries

### ISSUE THREAD

**Issue by lswanderleygit** [thingsboard/thingsboard#1580]
When I make a request for a large amount of data, I have the error "503 Service Unavailable".

For example: https://url../api/plugins/telemetry/DEVICE/d1d000a0-1f08-11e9-b7dc-771ff6b0943c/values/timeseries?keys=a1,a2,a3,a4,a5,a6,a7,a8,b1,b2,b3,b4,b5,b6&startTs=1551409200000&endTs=1554087600000&agg=NONE&limit=40000

With startTs and EndTs of a month, and limit 40000, returns the following error:

{ timestamp: 1553705534735,
  status: 503,
  error: 'Service Unavailable',
  exception:
   'org.springframework.web.context.request.async.AsyncRequestTimeoutException',
  message: 'No message available',
}

With 30000 limit I have the expected return, but with a limit greater than 30,000 of the above error.

Is there any timeout or ttl parameter that causes this problem?

**Comment by Ultrazombie** [comment]
It was closed, as not active.
