### ISSUE TITLE
Some problems After scanning whole project

### ISSUE THREAD

**Issue by dty717** [thingsboard/thingsboard#1585]
1.There is few explanation, especially about bean structure and relation.
2.Too many interface makes the whole project very complicated.
3.Rule engine is not good.
It's a good project and needs some improvement.

**Comment by ashvayka** [comment]
Please go ahead and submit your proposal on what exactly you plan to improve and what exactly is wrong.

**Comment by dty717** [comment]
I think I should rewrite the whole project for better understanding, and redesign the ui and device connect.
<a href="https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=structure.xml#R%3Cmxfile%20modified%3D%222019-04-08T05%3A38%3A29.391Z%22%20host%3D%22127.0.0.1%22%20agent%3D%22Mozilla%2F5.0%20(Windows%20NT%2010.0)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F73.0.3683.86%20Safari%2F537.36%22%20etag%3D%22qDfY-kvw_MNNRgTjtc2z%22%3E%3Cdiagram%20id%3D%22MULKOZ7MlXEjhwR_fcF_%22%20name%3D%22main%22%3E7V1de5s6Ev41uUwfJBAfl03Snt1%2BbLOb3e22d8QmNqcYXMBNfH79ChvZZiRAyAhjp704x8hA8Mw7o3c%2BJK7M28XLH6m%2FnH9OpkF0hY3py5V5d4Wxaxn0v8XAejtgEbwdmKXhdDuE9gMP4V9BOVheN1uF0yCrnJgnSZSHy%2BrgJInjYJJXxvw0TZ6rpz0lUfWvLv1ZwA08TPyIH%2F0aTvN5OeoYxv6LvwXhbM7%2BNGHfLHx2djmQzf1p8nwwZL67Mm%2FTJMm3nxYvt0FUCI8JZnvd%2B5pvd0%2BWBnEuc8E%2FMutj9PHb9ZeH6Pvk4dHAt4una2Rtb%2FPLj1blTy6fNl8zGTzPwzx4WPqT4viZqvnKvJnni4geIfrRz5ZbyT%2BFLwH9WzdPYRTdJlGS0rE4ielVN7PUn4b0OcEw%2FxPKX%2FUrSPPg5WCo%2FEl%2FBMkiyNM1PYV9a5nlNSXCTHb8fKAvz92OzQ9VxQb9EiOz3c33UqQfSkF2Eapx7kLFCArV4ISKGdIPhbobPEqo6Oafxnz9%2Bev7v9%2Ffka8f8uzz7TVqlym9C%2FULhQy6SrcHmdk2rogM27zIkEhkSJvIsEBkdpQXaEro7zyUnf1zlbAvrrONG35LT8Bo%2BbL%2Fkn6aFf9%2FDh7Zjehzbe%2B1%2FYZTCRVeMZ7lafIjAEAVQPpAR8Vty%2FkAW%2By4vHHxfaGZkDrqt1E4i%2BnYIpxOiy9v%2FHJgQnUZpJqU60kq19KlWwm%2FHUzpVFYeJmk%2BT2ZJ7Efv9qM3abKKp4UB3BlV4f8Z5Pm6lL6%2FyhM6tL%2FDpyRZludRiabr%2FxXXvyHs8Ft5u83B3UvlaF0e1aokS1bpJGj43aQkAX46C%2FImd1HKoxBCo4bTIPLz8Fd1vhepq7z0Pgk3tsNwg9gUyhgOVPn2UcvLgNZ3z6EOBDJyv%2BgZZnUqwSZvOkg0P6M%2B5meRyOxav5gt%2FVjdLy7n66xwSfSEyF9T37N3ktsbX7aT9JjNMU3LzoDanKQjYRvx9G0RJxSyiPyM6q8q4eAlzLcOzjXt8njj4d4YHvt%2B7%2BSKg%2FXBwX2QhvSnFBI%2B0u8xTtnqzw6ETQSyZmNHuj3iAa%2FnAh1ufxDn9bgb2Y5TBY1FBnWfbg8QqZkEUcskyKCFKrBySCOqjkAQi59bp85RIc3GVaQRSJdlkUbclhtpRprXJ9IqZGsPuxaklWcyrOkCmiEJNFmKNpBLI8ClOT0BzfSGBZpM%2BuGklJAgryppS5CyQaJQGWnLLojSC31wwlXWwAO3w4%2FppTNDgqFpCRQ%2BKDNkVHW0NoIMu8YdHcjMI7zIPKJLZGaLicAg6JWDXqBBIod6V5sKZbJGew5SCnjqZ%2FNNkgjVsJHdQRfWW%2BUizaGUOheRTheNK7xCBsgqERNgQpqMOOBGkmSEYsBfH5y2LE7I6p%2FYAxlS9sB7uG7v2C%2FT4ZNf%2F7m75yCdzpPF4yprd%2BQ9WL0D5GB5Nmf0rsjmtc10fLZr6uf%2Bo09nNiioE8xzFrMYllk3eSc5rLwkkkbZ3F8WH5%2Bi4KV0ljfC2C2j1pWrhHRKqQNtmQNb1ouOyolaMKAjqgGdAW40cOYAqaYOJOC3m42xU81uup2Tm2pQPgKWkqgko0KlYwOHp5pmcBG4EdYzs9se%2BDuG0fhcHm48Xw8TwDI5j2NNRD55Nnxd9EyNwQFYUS0juBB0ph5jcECNi2u6aqHF4HxNxiDTK3MkXUFdYL03ITDJ2J0nmVdnIaC9bddW1NlCTGAhkn0KnS0EPrDVbCHIAOwKXKDJRPi636arCVqJbApQkJfa5q9Y1yhITyG3n%2FDJBiTAFjUmYQE8EaQd%2FXWd8Wz1oDFikiwWq5ge5DT8ZG0S5yZ1AqYt1%2BClLmyPRLajSeomvkxA75pKTgdok098DwjoaZgGkzxMivQ09fWFDIbRhGNUqYuDBCC3RI1bMBDpTxPd8tdqeZhujF0lnX2E%2BlpZDpvY2ovv3qh4DswDeurJGnCjgZM1pmrTWTeMeriC0jfGBjeNSC2OIJ0%2BAornhjDbrRJTV5VJ2y6Y%2FbE9LMJUe9Y6IcxCDkQY%2Fo2wZoSB1J46wiy7eiNzWIRZ3RIIbXVihWKFzinSwqNCjQWDCUblO6MGwg%2FeSDdq%2BBAknyw54OwXnaDxhiGmCSO8knq2hSHQ5Ptb8COx0KPHumS7lA%2FmCserThWeqcSaJXLq%2FaUDpYnyuIqaMPVgwzSetLcAGXNdjSE2eGC2UqDuuRzLbDpfTzrQEi0J6odSdTGkqhWNq6vbcmTtZVytVCZg60S1xGSBKYFoKjGZoN7KOoj0GgAftT5n%2FNQt20glAD0%2FkeuYtoFTswXr1pElAJu25KHFB2vzPBeworGLFtJUmwVfpxOtvraYTuwHedWM4RvPUmuCHZT%2FWNL8Z1z%2BnBBIgMAyYelEIes03PlzU8qf97ZwW7VlpRtOB223liYJZFxVdtMCoFJdZAgnbwLT2JpIglN6Y60kgfSaFurkYzFwsYbT6mI7ucv2VKM7LsBCogNrbqrlEkcTq7WhhQ3RCMU2Gzs1Q6DBNWAIjnxw55yOIuDz9OYEYM1RXsmLhzEOC%2F4dpzlHAjlQ5%2FOtIWYLvm0iC%2BNZxC87ydPQ33xxZPBzhc2nzT%2BBNR62UTwHWd5kGF1Wr7gAIPzqFdYBOkhMRPgscRakv0Iqz%2FaFl9JtKupq6EHmNmgwFPWlsFLvIGuJyTiSh2qbjwyTPCSy6zCtcdEsDJPkql0pGGRPZDcf6TqTcFMfGoJm8cnD7bYHqv6FW2h4UoeDDLChh22eeE0n0dcBIp9R6FLOVy1xHOFxpDMR4%2BohQRiUGWwX9H7IuhwEfY7tDNtFQvj87I6LALB26gk4rTPYtbzu8o%2B8Mxi2M8AWbczRmpa5RJv3JG2ebcwxFpu34CoOomrzsI12aJtnkm3rAeqn2qXb1mFcLpr4xTu4aLN1me1etaRguxnxsBsUSE%2F2YzN8DA0fmqu04SNwJwfShp4CDJ6fOHbzk8ELiNdyAVdD6XoBeCQ9QY%2FNR%2F2XFfTANItgZeGgQY%2Btb2HFpRAgW3ajFntcaRaEMWh4V%2B1qRNiGrfPDLv%2Bx%2BdD8IoKeagZEtOB12KCHxbaXQTS5Ao3s%2ByW0eVsHX%2Fr0Vm0zdj3ntNObw0dOF%2Bg4PIMX88COo1sE9RppBLP9VhrhjCuc8sACKGTA%2FaKlaYQBtyGAeNRMI5yLjy6q7tdzT%2B1%2BLyW6aO0sOsIvyIYXY%2FMLDvQLqt1yCIP6KrdNQW9pFsQ9s9PyaNBlld1vWrMgzhgqkcP0MDBQn11wjQD8PeVZEbZDcAvcdc%2BKfEUxSaeCaZEthKV69qMoiJJZ6i%2Bo9pcHvZGV7w6aJsdNqE0PV1UgisTNIQk1m5JP2%2F5U3Y9QJzmWLjKOzA3ANQ6Ug6n6AZhw9yAt0%2F3SLn0bXOqD3G62GqQkxnx%2BO1cbWf8LtxGUavM24naCktwguTeUXngKDYP3m3inTqG53RphXmMjLsPkuYVwCMHZC6m24iLkwVsNvEWcywdNP1dBaQCCNyFxOGx%2FKRL3QqPaVx%2BJfE71vdA61umjavrHxnxjjWgtubadJT2eURQbe%2FrxVP6FVZenJout%2BByNmngPHxYa8heFPOLHbLn54fRXzwTLjC5WTQisZGdFl7bqIdvC4Sg9ZdbH6OO36y8P0ffJw6OBbxdP1yJ%2BvjWj4udX1FLzNkVki96mCNYy0Wfb3q%2FGMHdpgDSZBJlEFfjRn%2FyYbfT1ZZVHYRwIaFWJiVnqT0OqMzDcB7HiJihLEONrK5qJ9Mkz2X70WWZv5LR57MZxGjVGQI8bEu07M6jGVHdKPvSOc3%2B6%2BbY4qLSQFgf3fk59YbwZoerlvCmNPozNv6PrGzpeodLgtCrUWHheOQmOhRpD8HGvp5KPmNvu1Fd1A4bmqGUBM3cBy0BJ%2FxRwwfHVEBEyVBeC6jG60QWkIpGJsqkNxjkWmzNBsc1U3eoXWQDZ3NrwvmzOREj4yPXVHiL%2BjVpNiC%2FDp0G%2BSuPdWDurTwNKO%2FzHzQkFOEvJ0LPJzRW568TnI%2F8xiG52rFCUWuOx3%2BgbIKko3iARx8EkL5%2F4qoyeasmG8QZZjLgzP90LqHHlnrvdP9gNkqenLDg6HyISDZ8OSYOfq2KThjNQdh1Z7KxXZAEDbXyjSY0KqxZ7TYZSoWgrvj4ChElUMPYLiBAwSKXslH2yCEHwYuDfOqsaJNy6%2BPQ64xMrt1S4aRJFgsKSkrdc5UlWpqcOnGcUPOUC15knhYIyqq8wnv27OLijkWdPFoPFfOVQ%2Bo5A%2BL0kH4XCF2VBTh5TD0PTGd1t5ekjqyYjC7hd5Z4H5AE4aux5EGqAT33%2FK%2BC3aB4hQ2o2pqN507XxxsTVBDiLFo9EzzUCdwUv79NHpxC%2FSOGLsNHtvF28RaplQJPtldbiHfS5%2BG5bSrctr4fOvot%2Fr5XvSFwrzICoF%2BRNuGxDZz1eWN3o1sH4W%2BsHuuJetK2u9YEnVMxzaU7rrIAYhfGP44jcn0Ger8u6b%2BGAN8WvfJ7MktiPPiUbv9p%2FEaUWTv3lZUdWDMF2ddImLqhxyze5gnQMscCddOPz7MONE5TwRCuUhCeOrL0N7tuIWaNe9xoeaB7AGt8CJ4StKE75ySH3dMS1rkW2FnVd%2BgBYiMAILeFzFroapj7d3C%2B%2Fvw%2B%2FfHc%2BfP%2FwbLzLPl%2F%2FV9C4MZkHkx%2BcOrp2HvcgLM8DPYC8qHR1DwtFpdo83PqmS9zDHN2k3LH4MAOkS7kdl%2BVzLcAb6mOGQrn20DujjaydBRBcsLi7LxxoDAyFclXdKqIVCM5rQQLw8ZwC1aGgbzGPULA9tPbUvs6mrSOnFg6HNPcs4ADa%2FrH6%2Fhxs2RqDA9EWnAkFq7pbhBgOrxQNpjY0OMOiQXUTBDEanFcKB6INDt6wcOi1iFC33BhLrzfeByA7POljHmeGOhf0OHJJaFnQebCjWdOrorg5tOfXYwt1Jqg9a0C02vuuf%2BO5gmdYVVGNvTxY6IHBfG94NsUhgl5AdwvxFQGt%2BpK%2F35AGxKAFitKYBu2xXMW6N0wDKsOCVb2YlshWTFbprx2C2yhpLdBGAgxOnUhx83x4I0%2FP1vkcRbCb97V33G7nu3CNVPPp0MPjfjfNF2OUT6PM%2FJxf1KG%2BJYqgQ7gWx%2FK1CtcD73nkF1izd81WgI7rMX1UrQJ1yz%2B0zV%2BDJqtH1jHAWaXyfkNwz9ihs9WoWxqiBRRj9%2F7c8jQMZ3P5Tg%2BYW9a2BA9W%2BckQvIBPR9wKa8CXWZKHbTzYdHnf3U9Jnh6mSbEUZq8%2BOmHNPyfToDjj%2Fw%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22kAQQoLCSl0D7L1P1RBlT%22%20name%3D%22UI%22%3E5Vtbb6M4FP41eewKcyt57GXaGY1WW6kabbsvIxccoOPgrCG3%2BfV7CCaATRNKSADtS4qPb%2FD5OzfbnRh3880jx4vgT%2BYROtE1bzMx7ie67pga%2FKaCbSYwLT0T%2BDz0MhEqBM%2FhbyKEop%2B%2FDD0SVxomjNEkXFSFLosi4iYVGeacravNZoxWZ11gnyiCZxdTVfp36CWBkF7b06LiKwn9IJ%2Fascys5g27v3zOlpGYMGIRyWrmOB9HfGQcYI%2BtSyLjy8S444wl2dN8c0doCmsO2avzz6t9T7c%2BfY7f16Fj%2Ff7JrrLBHj7TZf91nERJt0OLZV5huhRQTnSbwiS3MwZzwUcnWwGy%2Fe%2BS5RVX8Y4CN9AAOYtNUQlPfvoX76aG5U44o5TwfFR4vWzgrJkAdj%2BHDq8MnIHC7ToIE%2FK8wG5aswbWgixI5hRKCB49HAfEE4WG%2BAgcV4QnZFMijsDrkbA5SfgWmohaS6y80AqUq8m6xLGcHUGJXo6QYUFrfz9ysT7wIJZoV%2FwRE%2F7X23uqHLpG8RuhWdcf38THUUAiAL0gvKorB5fXLH2eoEMJ7B3t9yAeAfxcGO%2FBEiBbqBnG9ucxhmIJ5k9oiaVoSbosmkdWhLKFQuJB4oqshuRtAWwzFG0FRT91RiDihOIkZNFpSF7EJMiw6r3Del1jwmWrGnk3qZeFkktxHIduFTnAiG9foKDlhde08IeVF%2B835cr7bV7ahMlLPgY8l3pBqeiUFvI%2Bn1uYmC25S447sARznxwaT7h74lUCCXWZS8to1axiLssYu6qGH3VLK2Z4YuHOndY7FkN2GNlni05lny6NgzRpIEMaKMNFGWhHtP1Xt%2BeeMy7unWAhOiOiPSgioqlkztBImTgdFxN7Ip81DPLts8yWZJPMp6ldlmu5jpxEthakaUvQjslmNSQbQsNgmyCNaR6xUE3ZZ15LkbXsvc9NvzxoLejncbxOuzGFh3GAF%2BkjrD7k5JCuQMw9B04sCA%2FhRSAzl%2Bqeioq%2BUhcF4N5jbGT8rzU%2BZ9xxlR%2BIgxFEsnVJ5c2WKm%2BbPau8ugMRr3yFgkW6rPWnvba8a9a%2F9qo7DxfSXu8hpKeGl13rcmP3fT0oXXYkWil0aarLU9SzLrdNmmN4seSMLqZg4muZsh%2FQ8py5tD1Oipryts60JUUtOZmW%2FdYHFAVy4G2p2SJtEB%2FQqalV1SmncoQED9mI3fJfTdXf4R01N05%2FvXDVmTZ8wGztCLMHkM%2Bb41QAS06xrtsqgLQtZeiXUYBL8F83a%2Bx%2FdjrKaHEwmklomEuWYekMtRCrDbGbHaUcaAzC8lSSukGcl%2BwUjLNf5I5RluaIu3Nx43YG8YwkKmlcXcSZBo6hi%2BkNDf0IxPPQ89KZbhnUzOhOfQOQkeiMMSlSCFUXlGo1mtHiKLchDdSQvpnh6ymlHMLeuT6szXP9mJtuau7kQ0XFbp45JNXVBIklQXpr48MEc6jnsbWKfdlsUz2Q9XCC33BMDuDZY8LuSLskCNVAWKdGSOZ7Gwy1h%2B8b%2F%2Bvs55O9ZNHD5iWyoscrdYcTmp9ExrN5Fk2KefZG4RIErAVPH5djae9LDlGn7Etq2xmDciUIydd12voSpBvVkeQktDtfcgjXEvvIioiphqe9uqS9dt%2FKqyYHs2Xknn456mwImmhgCI4sru7Y%2FBkNzd%2Bw7kMhQ2KRIR%2FpNzZ%2Fhi35Y%2FmSwZntnxpKj8n%2B9R%2B9qNHzyAxg%2FxB2cStvvBaw5vDgENGGagHN1gGgbAGVY4gzW8AOruJ1TImmOcGwtpeQcjmz7Y0lpMvbn51RAorFf0BlzYv%2FMDO%2B%2FAc%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22aYz1LbSHFJ9NhcSNc2mU%22%20name%3D%22HTML-UI%22%3E7V1bd5s4EP41eUwOkrg%2BpkmabLfttptt0%2BSlh9iqocXgAo7j%2FPqFGGEYYcBUgNzmJQcEyDD65puLRsoROZs%2FXob2wnkXTKl3hJXp4xE5P8LYVJXkb9qw3jSoGt40zEJ3umlC24Zr94lmjdlzs6U7pVHpxjgIvNhdlBsnge%2FTSVxqs8MwWJVv%2BxZ45V9d2DPKNVxPbI9vvXGnsZO1EkPfXrii7sxhP01Uc3NlbrO7s0%2BJHHsarApN5OKInIVBEG%2BO5o9n1EuFxwTzFwrim7cXV4H1kd459Gl9exMebzp7vc8j%2BTeE1I87d%2F3Vurz5ePX96%2FLNl6f7z6ub%2B7M3s2MmnwfbW2YSyz42XjMRhsHSn9K0F%2BWIvFo5bkyvF%2FYkvbpKMJO0OfHcS85QctjyVdnP0jCmj4WRyl79kgZzGofr5JbsqsZGIcOhZmQvutqOKmZgdQoDiq1sPO0MSbO8762wkoNMXtWyu32%2Fjr%2B69nn4Dl1GzvVqNsPzTNxF0VGPztPv3i1BNJ4E9bIAMVE4ASJcIUD2nHD5tYAe9aenKQkkZxPPjiJ3UpYVfXTjL4Xj2xSkJ1p2dv6YYfb5ZM1O%2FOTlvxRPCk%2Blp9vHns%2FYc%2FuNSxQswwltRk9shzPK%2Bjv%2B%2Bf0tVi%2BJ%2FfDZP%2F%2BJPh%2BfT9l9dFriOX6UC8OoVYwiawupZ8fuQ5kdq4Y2%2B4UPgZsCmoGIkDKKkAXQsfnu7KkiG8GOVNCRBjraCIbr6Blp%2BWe3Al%2BdWAvgs%2BM4dO%2BXMU36S6xRLK0i52PJRDekJlcKk9fkZ209DPENSoSV4sOc%2BLKvPgj5kdHlR14MSQtDgqQyJAiiCKKjrSHBCugIDWtIVHHgU7qADw0FvjrqKoKvDqSygM8UBT4EbIk5LPg0DnxB7NAwlbTMoQg0IeroJkR%2FMSEtTIgmlRarBlC%2BrrEIzC3keQTxWlyZhOFjEZn9P80qS0sfUHcrxVcRfSThm%2B36KRECCUaOvUgPE7HYnke9YBba80RYCxq6ydskT4BrH7YXZBE4Gl3ifMDS3efJGfK2cKWJLbcEeVviR9FsWaeuRbasw6UkbGkCFGGjI1taIHOT58cHYks%2B2pPa11FhumF07RUZsRye9rJJqCbtJVJprwGULk%2B67Ku9BqSB%2FiKWSrHyEYvU2msQ2bSXj1SkFiB0XsYXoDEO%2FY1EY7pcNGY2%2BA5tacyE81DQm%2BmZxswXG9oCfJLlC%2BCUIzR9bcGnwoAMGuOewWdx4IucBGdS8j8sO9B0bWT%2BZynbYr7Asf0EogchQF0dXYB8BBYlZHcY4jPw6OLj4y%2BpPThDOvzxMYTn%2Bj%2FklB7En6mMLj6Bcx1yz1jWGc%2Fm7F2mppI4L3DK0mRquK%2FzAifec4M8kPOCWsRfUlScmsgsC8rgNZcoFSPOzUOJU10%2B7Fg95udQisl3xmVRhTRyn%2Bz75xtSyS7SQX5%2BSe3VkXaetNjLOIg2RdzpA7bnzvzk2KPf0q5S4bkT2zvNmuMgHYsoGRrXn%2F2Xnpwfq30OCQZDYmJuSPSqEeltQHhXPBsL5VROe2RhUjbnzJsriNCqECGcEhU3l8S743%2BSOUJt7RGWKyGtq2VVzM%2F3tUe6CToiZFB7xOBWwN%2B3pT%2BJ3cBPWj034t3y349YNZBO00z9hLd25pDUivkoszAukrKrBrw0HakVcqz094nRlyD%2FmArFWhw1EqwlFb%2FCZKXedcIPJiu1gSf8MB%2BtSw2%2FqR05OY2MhUWWo5QEjARgyOhaaQdRbQxcaYf53EfBqLw6EKNiorFNisA5VLnLZWsT4M0%2Bu1yzr1D7TEWQTTH6W7xXLVeB06%2Fd8Dfq9CuDVXMNk1xmRAewMSH7ty5iAkC2Wk7AJoCw14XbsjBt5wvD3zEyhdnCedOjUHCzbymA24njRY1tGjFJqgPblBeHDjG9cUXv9X%2FiT3c3f%2F%2B4O51O3%2F1wHoyKYvrO1PCbRDsHsKwcFsmqXYuTNbAaUG1ZnLwvM6hg4RfLWu20mOB%2BVsMvikkqVUHEBgsdYd1FhcZSBbnq9CFS1K5GUgUzzwQGbaJUgctUNKgCXD8gWBVw%2BOn9mfna1aPZ3fED8f2Lf39WWIVJMF8EvrRVFxqb32WjZwxoWCtF%2BMds11IHoCKZVN6HpSIT3QQo6lryaBDQUX8lj3Vird6uRffSOZT7MDmapUf57i3chc2uJLB5mwKCV%2BTkBkMDg6G15AYEA35h5NBiC47JMnzIJdcrU4yT8f0l2pDLHYcZR61roojA8LCnOB0WGatK7WvBVT0sim27QFzX6%2B%2BHPhxu6J%2Fbw4Q03I%2Fg%2BOz1Ok1vD76WNLy9sWMHll4dOj4DKLlDh3TjpEzbCLXl7d58Or58ybPXwVJSERINyyfCiuUEnnsf2lnX0gkRA%2B22EC9BXFXWyK1yESdCAaFFyYgfxtKqWjg1egwZAUriMSCAKoTgNlyt65PBegOkQNXtOdRAfKzxgsYmNMpVPANr3LujEXpmw6ORj6x8e84XeydduYuINtuVshHqzdtRoBPZ0k7DBIU4I8OXwW3jfhkNtWlonSTYn6cjoJKrTIw7SA4NTHJqS5JDcpVgWyAnh%2BDItza5iNk81lPLeo5943TujRsiS6SA%2FAF4oJ%2FQsmKFUnK%2F9IQLJgyQpY7NuAKqdH7ZkRqNKwypuAIhqwwP3LWeGCkK6Knl1hu%2FShaYqAPo%2Fu4FXcxbqNvWfMRKHIR0QAC4JQH05jAIXdp1YnSJnkadM2xPFnKFTyY0JYbakSuwAvN1PXEFxL42AFe0%2Bd853TYBUg4C3cZhohthOH2qdIU3gaZQAz0JgneiNmPgW0AibMh5XNH4rqgfOxB8g6CpawUZIiD71dP0LSIgWWQ0hIXw%2FmHUgU8gbVYH79h%2BQQqv0NLLq6vzIWxyCnFvpSJCFgR2zBx1oSPBtIIP1ClEcIqHqydt7xWCegTSchXg3ryCsVb5yv3yhMj9lTpFPcfKiaIZZeNJdNKkG%2BlZYbv7XmxqxW4X1UKULH2CwdKlzvsvcz213YB5f%2FBDN1fFA4Cfz53urq5Ms6p7VFyOmVyBnlDugRTwZ1Tgr7%2FcisgdaDs55yeKYgKOkYBhcNuolNlhWRiG%2B4doXZdAIa6aUNg%2FaEhOt%2F%2FueHP79p9Gk4v%2FAQ%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E">my structure in draw io</a>,and I will use draw io as ui development.
