### ISSUE TITLE
How to make configuration changes that can let TB to connect Kafka using SSL?

### ISSUE THREAD

**Issue by magicgw0928** [thingsboard/thingsboard#1586]
My own Kafka cluster had been config using SSL mode connection. So I want thingsboard node can connect Kafka also using SSL. Then I check the source code and find the class 'TbKafkaSettings' contains the external config parameter ${kafka.other} canbe meet my SSL requirement.
///////////////////////////////////////////////////////////
@Value("${kafka.other:#{null}}")
private List<TbKafkaProperty> other;
////////////////////////////////////////////////////////////

So I modify the thingsboard.yml and add the parameters as below:
##############################
kafka:
  other: 
    - 
      key: ssl.truststore.location
      value: /data/tb/truststore.jks
    - 
      key: ssl.truststore.password
      value: testpassword
################################

But when I restart the thingsboard server and check the startup log, log shows
ssl.truststore.location & ssl.truststore.password value is still null. Does somebody know how to make kafka SSL configuration be set in thingsboard.yml?

**Comment by munyiwamicha** [comment]
Hi, were you able to solve this issue?

**Comment by pon0marev** [comment]
Since version 3.5 support for TB_KAFKA_SSL environment parameters has been added:
https://thingsboard.io/docs/user-guide/install/config/#queue-configuration-parameters
