### ISSUE TITLE
Updating a shared preference using the WebUI dosen't propagate the change to the device.

### ISSUE THREAD

**Issue by Nippius** [thingsboard/thingsboard#159]
Hi!

I have a device (in this case I'm using the RPi demo device) that has a shared attribute (just a simple string) and what I'm trying to do is change the attribute using the WebUI and have it push the update to the device using MQTT. 
Per the docs, this should be possible just by subscibing to the topic "v1/devices/me/attributes" however if I do that, the server dosen't send anything to that topic when the shared attribute is updated on the WebUI.

Am I missing something?

Thank you!

**Comment by ashvayka** [comment]
Hi!

This should be fixed in master branch at the moment. Please build from source.

**Comment by Nippius** [comment]
Alright I'll give it a shot :) 

Thank you.
