### ISSUE TITLE
MQTT response to a GetData server request

### ISSUE THREAD

**Issue by DG2RDD** [thingsboard/thingsboard#1590]
The platform : Some Arduino on steriods, with Ethernet card connected to an ADSL box. I use MQTT since it has already been validated with PubSub library on this hardware.

What works already : 
- Sending analog telemetry to Thingsboard client-side : fine
- Receiving setpoints from a Thingsboard panel (analog : rotating button and digital : switch), both reading the setpoint and confirming it by publishing back the received setpoint to Thingsboard : fine

What doesn't : 
- On the opening of a panel, Thingsboard asks for the current value of the setpoints displayed on the panel, to open with an up-to-date value (which is sensible). In my way of programming the widget, it makes Thingsboard send the device an MQTT request like : 
Topic : v1/devices/me/rpc/request/12345
Payload : { "method":"GET [Variable name]"}
to which I should answer : (after I have subscribed to v1/devices/me/rpc/response/+)
Topic : v1/devices/me/rpc/response/12345
Payload : { "method":"GET [Variable name]", "params":"42"}
And I get an "Unable to parse response [object object]" message

I tried : 
Subscribing to v1/devices/me/rpc/request/+ (Server keeps sending the request)
Subscribing to v1/devices/me/rpc/response/1  (Server keeps sending the request)
Changing the format of the payload : 
Payload : { "method":"SET [Variable name]", "params":"42"}
Payload : { "method":"GET [Variable name]", "params":42}
Payload : { "method":"SET [Variable name]", "params":42}
And every variation of all these ... The best I get is an "Unable to parse response [object object]" message.

Any ideas welcome. I'm beginning to chew the carpet a bit ...

**Comment by iscarelli** [comment]
Same problem here.

I tried everything.

[]'s
Ismael

**Comment by asaad1882** [comment]
the payload coming from platform is look like following:
{"id":2,"method":"UPLOAD","params":{"interval":10}}
Hope it solve your issue

**Comment by jernkuan** [comment]
I tried many options, but finally directly returning the value seems to work for me.

 20         // var newMessage = { id: id, method: "getValue", params: 10.0 };
 21         // var newMessage = { method: "getValue", params: 10.01 };
 22         // var newMessage = { params: 10.01 };
 23         // var newMessage = { getValue: 10.01 };
 24         var newMessage = 10.01;
 25         client.publish('v1/devices/me/rpc/response/' + requestId, JSON.stringify(newMessage));

JSON.stringify is eventually optional, you can just publish the string "10.01"

**Comment by Ultrazombie** [comment]
Closed due to inactivity
