### ISSUE TITLE
Issue while developing new plugin

### ISSUE THREAD

**Issue by vipin-nirwal** [thingsboard/thingsboard#1593]
I am trying to try my hand to develop a new plugin. I am following the thingsboard doc for same.
But i am not able to find few files as mentioned in doc. org.thingsboard.server.extensions.rest.plugin.RestApiCallMsgHandler and org.thingsboard.server.extensions.api.component.Action. Could you please let me know where i have to look for same.
Thanks in Advance.
Vipin

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
