### ISSUE TITLE
Map widget not working properly

### ISSUE THREAD

**Issue by dorukhanguloz** [thingsboard/thingsboard#1595]
I created to OpenStreetMap Latest Values and two device named Device1 and Device2.
Then I created two device list alias that name Alias1 and Alias2.
I added Device1 to Alias1 and Device2 to Alias2 alieses. 
And then I created 2 seperate datasources for each alias in edit widget menu. Up to so far everything is ok.
 But there is a problem if i assigned one device to customer group. I assigned Device 1 and Dashboard1 to Customer1. Then I logged in with Customer1. In Dashboard map widget does not work. It can't load a widget initial state. Map is load but it does not show any marker and not slide.
Actually problem is that dataSources json object does not included in ctx object. Is there bug or other something?

**Comment by ibeaconvn** [comment]
same issue with me ? do you have solution to fix it ?

**Comment by ssakharova** [comment]
Hello @dorukhanguloz,
Could you tell me please the problem is still relevant?

Regards

**Comment by dorukhanguloz** [comment]
Hi @ssakharova 
You must be kidding. 😁 3 years passed. Where were you?
