### ISSUE TITLE
How to display all devices by Customer in dashboard?

### ISSUE THREAD

**Issue by aletor92** [thingsboard/thingsboard#160]
Hi,

in dashboard section, in edit mode, you can choose to select "Customer" as entities.
But I can't send any telemetry data to Customer.. ( or I can ? )

Anyway, is there some feature to display all devices by customer into dashboard whitout select/create one-at-one ?

Thanks

**Comment by mfalkvidd** [comment]
A workaround I'm using is to create an entity alias where I manually select all devices for that customer. This makes it possible to re-use the alias in multiple dashboards. But new devices must still be added manually to the alias :(

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
