### ISSUE TITLE
2.3.0 to 2.3.1 update problems

### ISSUE THREAD

**Issue by alexmed** [thingsboard/thingsboard#1600]
please advice if anyone knows estimated date of 2.3.1 release (if any)
or the way to jump to it now (for EC2 instance, probabbly based on standard Docker image)

**Comment by Zer07even** [comment]
looks like its already out, I'm going to try it out this evening: https://github.com/thingsboard/thingsboard/releases/tag/v2.3.1

**Comment by alexmed** [comment]
thanks!

**Comment by alexmed** [comment]
any idea how to update this ? "Monolithic ThingsBoard v2.3 instance with Cassandra running as a docker container" - its running on EC2

i can SSH ubuntu instance itself, but how to update the software running inside the Thingsboard Docker container?

**Comment by alexmed** [comment]
Tried but finished with error:

tried on existing EC2 instance of "ThingsBoard v2.3.0 AMI with PostgreSQL (ami-0098fe7995dc97968)"
finshed with "Unexpected error during ThingsBoard installation! ThingsBoard upgrade failed!"

so i deployed another fresh EC2 instance (ThingsBoard v2.3.0 AMI with PostgreSQL (ami-0098fe7995dc97968) from scratch. 

making the long story short - the install.log is attached
[install.log](https://github.com/thingsboard/thingsboard/files/3042649/install.log)

here are some steps descriptions

basically i've faced 2 issues:

**#1. not related to Thingsboard itself**
when trying to do "sudo dpkg -i thingsboard-2.3.1.deb"
getting this:

```
ubuntu@ip-172-31-30-173:~$ sudo dpkg -i thingsboard-2.3.1.deb
(Reading database ... 56861 files and directories currently installed.)
Preparing to unpack thingsboard-2.3.1.deb ...
Unpacking thingsboard (2.3.1-1) over (2.3.0-1) ...
dpkg: dependency problems prevent configuration of thingsboard:
 thingsboard depends on openjdk-8-jre | java8-runtime | oracle-java8-installer | openjdk-8-jre-headless; however:
  Package openjdk-8-jre is not installed.
  Package java8-runtime is not installed.
  Package oracle-java8-installer is not installed.
  Package openjdk-8-jre-headless is not installed.

dpkg: error processing package thingsboard (--install):
 dependency problems - leaving unconfigured
```


So i do "sudo apt update"  and then "sudo apt upgrade"
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 thingsboard : Depends: openjdk-8-jre but it is not installed or
                        java8-runtime or
                        oracle-java8-installer but it is not installable or
                        openjdk-8-jre-headless but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```
so i do "sudo apt --fix-broken install" which works, and then "sudo apt upgrade" also works
then

**#2. doing seconds step of TB Update manual**
i.e. sudo dpkg -i thingsboard-2.3.1.deb

```
ubuntu@ip-172-31-28-160:~$ sudo dpkg -i thingsboard-2.3.1.deb
(Reading database ... 98872 files and directories currently installed.)
Preparing to unpack thingsboard-2.3.1.deb ...
Unpacking thingsboard (2.3.1-1) over (2.3.0-1) ...
Setting up thingsboard (2.3.1-1) ...
Installing new version of config file /usr/share/thingsboard/conf/thingsboard.yml ...
Processing triggers for systemd (237-3ubuntu10.15) ...
Processing triggers for ureadahead (0.100.0-20) ...
```
looks like its Ok (although it does not ask anything about merging config file as mentioned in Docs)

so next step is Upgrade script itself sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.3.0
which brings to this
[install.log](https://github.com/thingsboard/thingsboard/files/3042649/install.log)


```
===================================================
 :: ThingsBoard ::       (v2.3.1)
 ===================================================

Starting ThingsBoard Upgrade from version 2.3.0 ...
Upgrading ThingsBoard from version 2.3.0 to 2.3.1 ...
Updating schema ...
Unexpected error during ThingsBoard installation!
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: PUBL                                                                                                   IC.EVENT
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.load                                                                                                   Sql(SqlDatabaseUpgradeService.java:175)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgr                                                                                                   adeDatabase(SqlDatabaseUpgradeService.java:164)
        at org.thingsboard.server.install.ThingsboardInstallService.performInsta                                                                                                   ll(ThingsboardInstallService.java:112)
        at org.thingsboard.server.ThingsboardInstallApplication.main(Thingsboard                                                                                                   InstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                                   java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                   sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner                                                                                                   .java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau                                                                                                   ncher.java:593)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: P                                                                                                   UBLIC.EVENT
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.SchemaManager.getUserTable(Unknown Source)
        at org.hsqldb.ParserDDL.compileAlterTable(Unknown Source)
        at org.hsqldb.ParserDDL.compileAlter(Unknown Source)
        at org.hsqldb.ParserCommand.compilePart(Unknown Source)
        at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
        at org.hsqldb.Session.executeDirectStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 14 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```

please advice if anything can be done about

**Comment by bmakhafola** [comment]
Is there a bug on version 2.3.1, i am seeing the same error when running loadDemo script, anyone with the solution to this?  root@server02:/var/log/thingsboard# sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
21:30:36,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
21:30:36,709 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
21:30:36,709 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
21:30:36,713 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
21:30:36,713 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.3.1.jar!/logback.xml]
21:30:36,713 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
21:30:37,245 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
21:30:37,255 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:30:37,351 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
21:30:37,458 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - setting totalSizeCap to 3 GB
21:30:37,493 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - Archive files will be limited to [100 MB] each.
21:30:37,640 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - No compression will be used
21:30:37,654 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
21:30:37,666 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
21:30:37,666 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - Roll-over at midnight.
21:30:37,670 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - Setting initial period to Sat Apr 20 21:07:49 SAST 2019
21:30:37,689 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:30:37,802 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
21:30:37,802 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
21:30:37,811 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
21:30:37,813 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
21:30:37,813 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
21:30:37,813 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
21:30:37,815 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
21:30:37,816 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2cdf8d8a - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.3.1)
 ===================================================

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
**_ThingsBoard installation failed!_**

**Comment by wybornd** [comment]
I have exact same issue

**Comment by alexsmartens** [comment]
I'm having a similar issue here too. Has anyone figured out the solution?

```
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.3.0 
15:54:42,149 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:54:42,150 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:54:42,150 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
15:54:42,152 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:54:42,152 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.3.1.jar!/logback.xml]
15:54:42,152 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
15:54:42,237 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:54:42,237 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:54:42,246 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
15:54:42,256 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1598924227 - setting totalSizeCap to 3 GB
15:54:42,259 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1598924227 - Archive files will be limited to [100 MB] each.
15:54:42,276 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1598924227 - No compression will be used
15:54:42,277 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1598924227 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
15:54:42,279 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@443b7951 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
15:54:42,279 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@443b7951 - Roll-over at midnight.
15:54:42,281 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@443b7951 - Setting initial period to Wed May 08 15:54:08 EDT 2019
15:54:42,283 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:54:42,300 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
15:54:42,300 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
15:54:42,301 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
15:54:42,301 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
15:54:42,301 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:54:42,301 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
15:54:42,304 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:54:42,304 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@14514713 - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.3.1)
 ===================================================
...
```

**Comment by KimLorenzen** [comment]
I got the same issue

**Comment by CooL16** [comment]
This issue has been solved in the latest releases.
