### ISSUE TITLE
how to backup and restore data 

### ISSUE THREAD

**Issue by chenmingzhang** [thingsboard/thingsboard#1601]
This is definitely not a bug but i believe it is worthy to clarify somewhere in the forum. i was wondering how to backup and restore database behind thingsboard. thanks.

**Comment by hafidzdaud** [comment]
hello chen, have you found a solution?

**Comment by chenmingzhang** [comment]
literally i am backing up cassandra data base on the regular basis. i have tested that once cassandra is been restored, thingsboard can work properly. the only trick is to ensure cassandra folder is been backed up under user name cassandra:cassandra. i am using 2.3.1

**Comment by RafaelAllves** [comment]
Is there any place that has documentation on how to restore for postegres?

**Comment by ashaforost** [comment]
Hi @RafaelAllves 

Please see the official postgres documentation on pg_dump usage:
https://www.postgresql.org/docs/12/backup-dump.html

**Comment by dip-devlopement** [comment]
> This is definitely not a bug but i believe it is worthy to clarify somewhere in the forum. i was wondering how to backup and restore database behind thingsboard. thanks.

I have perfact solution for that just contact on dharmikprajapati230@gmail.com

**Comment by dip-devlopement** [comment]
I have perfact solution for that, and I done it successfully

**Comment by dip-devlopement** [comment]
> Is there any place that has documentation on how to restore for postegres?

Yes i have perfact solution, contact on dharmikprajapati230@gmail.com

**Comment by dip-devlopement** [comment]
> Hi @RafaelAllves
> 
> Please see the official postgres documentation on pg_dump usage: https://www.postgresql.org/docs/12/backup-dump.html

There are also some tricky steps which i successfully done, just done back-up and restore in one script ?😀😀 Contact me
