### ISSUE TITLE
Data Converter: Http Integration

### ISSUE THREAD

**Issue by sharmmoh1983** [thingsboard/thingsboard#1605]
While converting input message from device to Thingboard data , I can specify device name and type. Is there a possibility to define asset names also in the message to create right association of device to Asset 

```
// Decode an uplink message from a buffer
// payload - array of bytes
// metadata - key/value object

/** Decoder **/

// decode payload to string
var payloadStr = decodeToString(payload);

// decode payload to JSON
 var data = decodeToJson(payload);

var deviceName = 'CosineController';
var deviceType = 'Controller';

// Result object with device attributes/telemetry data
var result = {
   deviceName: deviceName,
   deviceType: deviceType,
   attributes: {
       model: 'Model A',
       serialNumber: 'SN111',
       integrationName: metadata['integrationName']
     ****asset** : ''**
   },
   telemetry: {
       temperature: 42,
       humidity: 80,
       rawData: payloadStr
   }
};

/** Helper functions **/

function decodeToString(payload) {
   return String.fromCharCode.apply(String, payload);
}

function decodeToJson(payload) {
   // covert payload to string.
   var str = decodeToString(payload);

   // parse string to JSON
   var data = JSON.parse(str);
   return data;
}

return result;
```

Also what is right approach to provision all devices in Thingboard through HTTP Integration?

**Comment by teacherZF** [comment]
Do you want to use the converter function? The converter feature is only available in the PE version, and the open source version does not exist, which is very frustrating.

**Comment by Karabiy** [comment]
you can put the asset to be related with into the attributes, and on the message being processing in the rule engine, use the "create relation" rule node, which will refer to those particular asset.

**Comment by bioshock2k** [comment]
I see that when using the putting the "attributes" it puts the variable in shared Attributes.
Is there a way to put them in the server attributes?

**Comment by Karabiy** [comment]
@bioshock2k server attribute can be set only on the server side. You can set these within the rule engine, after the integration.

**Comment by bioshock2k** [comment]
@Karabiy Do you have in example of a node in the rule engine that does that?
