### ISSUE TITLE
Assign a Device to multiple Customers in CE

### ISSUE THREAD

**Issue by enriquedbelec** [thingsboard/thingsboard#1606]
Hi,
Does exists a way to modify thingsboard CE to allow to assing a Device to multiple Customers?
I've tried on CE, but it only allows to assign a device to a single customer. If you try to assign the same device to other customer, the device became unnasigned from the first Customer.

I've tried the PE and it allow some advaced features, like device and customer groups, but I don't need that advanced features, only to assign a device to more than a single customer.

Also I need to build my own fork and develop a customized project based on Thingsboard, and would be nice to include this feature or help me to implement them. PE doesn't match my requirements, because I need a high customized version and need the source code. And the src is only available for CE.
Any help is appreciated.
Thanks in advance!

**Comment by darkfader** [comment]
Perhaps there is a way to override a class using CLASSPATH? But there is no way if it will be compatible...

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
