### ISSUE TITLE
Inconsistent parameters for RPC in Knob control, ON/OFF control, RPC Call node and Scheduler

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1609]
Scenario is :
- Thingsboard PE, last update 2019-03-13.
- Device for temperature control with a RPC method "set_temperature" accepting and integer for the desired temperature (for example "26"). Call it "device A"
- Device for lighting control of multiple points, method is "actuate" and receive one or more parameters stating which circuits must be changed and to what percentage (dimming). Call it "device B"
- Respective methods to get the current values, in the same format as the request for change.

`
{
    "circuit_1": 50,
    "circuit_2": 0
}
`

Problem is that using the Knob control, I can control device A, but not B, because it accepts a method name for setting the value but does not allow to format the request.

Using the "ON/OFF" button I can control both devices because there is a box for me to specify code for generating/formatting the parameters for the set method:

Device A (26 degrees in the "on" position, 0 meaning off in the "off" position):

`
return value ? 26 : 0;
`

Device B (100 meaning fully on in the "on" position, 0 meaning fully off in the "off" position):

`
return { "circuit_1": value ? 100 : 0 };
`

Using the Scheduler I can control device B but not device A because it does not allow you to specify a scalar value, only an object

Device A, if you try to save:

`
26
`

it is in fact saved as:

`
{}
`

For device B, it is saved as intended:

`
{
    "circuit_1": 100
}
`

Using the RPC Call node I can control both devices, but it is required to add a previous node (Script or other) to properly format the RPC parameters and message type.

The ONLY workaround I found to allow device B to use the knob control was to update its firmware adding new methods "actuate_circuit_1", "actuate_circuit_2" accepting scalar values.

The ONLY workaround I found to allow device A to use the ON/OFF button and the Scheduler was to update its firmware to check the parameters of "set_temperature", testing whether it is an integer scalar value or an object containing a "temperature" value.

Given all that, _the proposed solution is to make ALL of the widgets and the Scheduler interface uniform, following the ON/OFF button model (having a block to specify code for the parameters)_

That would allow coverage of all cases, from the simplest "return value;" to complex data manipulation, if needed.

Thanks.

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
