### ISSUE TITLE
Build failed when installing from source

### ISSUE THREAD

**Issue by KKoovalsky** [thingsboard/thingsboard#161]
Hi. I'm trying to build from source, but I get a test failure:
Results :

> Failed tests:
>   DefaultActorServiceTest.testBasicPostWithSyncSession:242
> Argument(s) are different! Wanted:
> timeseriesService.save(
>     9356f84a-5893-4fcf-b6b5-20c4bc687a27,
>     [BasicTsKvEntry{ts=42, kv=StringDataEntry{value='value1'} BasicKvEntry{key='key1'}}, BasicTsKvEntry{ts=42, kv=StringDataEntry{value='value2'} BasicKvEntry{key='key2'}}]
> );
> -> at org.thingsboard.server.actors.DefaultActorServiceTest.testBasicPostWithSyncSession(DefaultActorServiceTest.java:242)
> Actual invocation has different arguments:
> timeseriesService.save(
>     9356f84a-5893-4fcf-b6b5-20c4bc687a27,
>     [BasicTsKvEntry{ts=42, kv=StringDataEntry{value='value1'} BasicKvEntry{key='key1'}}, BasicTsKvEntry{ts=42, kv=StringDataEntry{value='value2'} BasicKvEntry{key='key2'}}],
>     0
> );
> -> at org.thingsboard.server.actors.plugin.PluginProcessingContext.lambda$saveTsData$18(PluginProcessingContext.java:177)
>

**Comment by ashvayka** [comment]
Hi, This was my mistake. I have fixed it now. Please pull and build again
