### ISSUE TITLE
Dashboard entity group items do not get updated

### ISSUE THREAD

**Issue by Shedaim** [thingsboard/thingsboard#1611]
When using an entity group as an input to a widget, the items on the entity group (e.g. assets), are loaded on first load of the dashboard/widget, but are not updated if an item is added or removed from such entity group. The already loaded items work well with their attributes getting updated normally.
To recreate the issue I used a simple entities widget. Created an entity group with one asset, loaded the dashboard, then removed the asset from that group. The dashboard still shows that asset as part of that group.

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
