### ISSUE TITLE
Request number reset

### ISSUE THREAD

**Issue by DG2RDD** [thingsboard/thingsboard#1613]
I am currently using Thingsboard through MQTT with an Arduino-like device. Everything worked well until the request number went over 65536 and, since my integers are two-byte long, no request from the server has been treated properly since by the Arduino.
Is there a way to reset the request number to 1 (preferably through an MQTT submit) ?

**Comment by DG2RDD** [comment]
I found a way around it.
I just parsed the 4 last gigits of the request# ti differentiate my incoming requests, and treated the whole request# as a string to generate the response char array.
Works fine, now.

**Comment by fotis400** [comment]
Can the Thingsboard authors enlighten us on what is the range of this ID, and when it rolls over?

I am using a signed 32-bit integer for this, is this adequate?
