### ISSUE TITLE
MQTT Gateway Request attribute values from the server

### ISSUE THREAD

**Issue by Fiekers** [thingsboard/thingsboard#1618]
Topic: v1/gateway/attributes/request 
Message: {"id": 1, "device": "sf-gw-sensor-1", "client": true, "key": ["attribute1","attribute2"]}

Subdevice only has attribute1 attribute, request response content error!give the result as follows:
{"id":1,"device":"sf-gw-sensor-1","value":"rtos1.8.10"}
I will not know who this attribute belongs to.

The function that causes the error is 280 lines in [thingsboard/common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/adaptor/JsonConverter.java]. The source code is as follows:

private static void addValues(JsonObject result, List<TransportProtos.TsKvProto> kvList) {
        if (kvList.size() == 1) {
            addValueToJson(result, "value", kvList.get(0).getKv());
        } else {
            JsonObject values;
            if (result.has("values")) {
                values = result.get("values").getAsJsonObject();
            } else {
                values = new JsonObject();
                result.add("values", values);
            }
            kvList.forEach(value -> addValueToJson(values, value.getKv().getKey(), value.getKv()));
        }
    }
Personally, I revised it as follows:
 private static void addValues(JsonObject result, List<TransportProtos.TsKvProto> kvList) {
        JsonObject values;
        if (result.has("values")) {
            values = result.get("values").getAsJsonObject();
        } else {
            values = new JsonObject();
            result.add("values", values);
        }
        kvList.forEach(value -> addValueToJson(values, value.getKv().getKey(), value.getKv()));
    }

Finally, thank you very much for your confirmation.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
