### ISSUE TITLE
timewindow

### ISSUE THREAD

**Issue by SULEIMANYK** [thingsboard/thingsboard#1620]
angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: ngModelWatch","newVal":{"startTimeMs":1556143200000,"endTimeMs":1556143201000},"oldVal":{"startTimeMs":1556143200000,"endTimeMs":1554905138807}},{"msg":"endDate","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.807Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.821Z","oldVal":"2019-04-24T22:00:01.000Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.821Z","oldVal":"2019-04-24T22:00:01.000Z"}],[{"msg":"fn: ngModelWatch","newVal":{"startTimeMs":1556143200000,"endTimeMs":1554905138821},"oldVal":"..."},{"msg":"endDate","newVal":"2019-04-10T14:05:38.821Z","oldVal":"2019-04-24T22:00:01.000Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.821Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.821Z"}],[{"msg":"fn: ngModelWatch","newVal":{"startTimeMs":1556143200000,"endTimeMs":1556143201000},"oldVal":"..."},{"msg":"endDate","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.821Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.834Z","oldVal":"2019-04-24T22:00:01.000Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.834Z","oldVal":"2019-04-24T22:00:01.000Z"}],[{"msg":"fn: ngModelWatch","newVal":{"startTimeMs":1556143200000,"endTimeMs":1554905138834},"oldVal":"..."},{"msg":"endDate","newVal":"2019-04-10T14:05:38.834Z","oldVal":"2019-04-24T22:00:01.000Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.834Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.834Z"}],[{"msg":"fn: ngModelWatch","newVal":{"startTimeMs":1556143200000,"endTimeMs":1556143201000},"oldVal":"..."},{"msg":"endDate","newVal":"2019-04-24T22:00:01.000Z","oldVal":"2019-04-10T14:05:38.834Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.854Z","oldVal":"2019-04-24T22:00:01.000Z"},{"msg":"fn: ngModelWatch","newVal":"2019-04-10T14:05:38.854Z","oldVal":"2019-04-24T22:00:01.000Z"}]]

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
