### ISSUE TITLE
Error: e is undefined when trying to add missing setting for TB gateway extension

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#1622]
Steps to reproduce:
1. Create a new gateway device
2. Upload a minimal extension configuration (http://mjo.se/mqttgateway.json can be used) without one or more keys (omit serverSideRpc for example)
3. Click edit on the extension
4. Click the "Add server-side RPC request" button

Expected: A new section for server-side RPC is added
Seen: Nothing happens except that the following is printed in the browser console:
```
Error: e is undefined
link/n.addAttributeRequest@https://myserver/static/bundle.e079371135118f94b992.js:595:507549
fn@https://myserver/static/bundle.e079371135118f94b992.js line 575 > Function:4:427
i@https://myserver/static/bundle.e079371135118f94b992.js:575:101966
r@https://myserver/static/bundle.e079371135118f94b992.js:575:140453
$eval@https://myserver/static/bundle.e079371135118f94b992.js:575:111240
$apply@https://myserver/static/bundle.e079371135118f94b992.js:575:111472
compile/</<@https://myserver/static/bundle.e079371135118f94b992.js:575:140503
dispatch@https://myserver/static/bundle.e079371135118f94b992.js:39:37882
add/g.handle@https://myserver/static/bundle.e079371135118f94b992.js:39:35947
 undefined
```
The same happens for all other buttons that don't have an existing section.

![image](https://user-images.githubusercontent.com/893502/55896002-9e0b5480-5bbd-11e9-9c1c-62848447aa09.png)

Thingsboard version: 2.3.1
Browser: Firefox 66.0.2

**Comment by ban2derlog** [comment]
Hi, does it persist on latest ThignsBoard version?
