### ISSUE TITLE
How to use attributes as Label in timeseries widget

### ISSUE THREAD

**Issue by affoltep** [thingsboard/thingsboard#1626]
this issue is related to: [https://github.com/thingsboard/thingsboard/issues/987]

I like to use the charts timeseries widget. There I would like to use the content of a server attribute "name" to use as label, because the ${entityName} just shows a unique ID as "70B3D549989304EF" which says nothing to the user. How can I do that?

**Comment by affoltep** [comment]
I just have seen that in V2.3.1 ${entityDescription} was add to UI: Widgets, which is a step further. But as far as I know the entityDescription is just editable over the backend. 

Is there are rule chain function available to edit the entityDescription field? If yes I would have found a workaround by copying the attribute content to the entityDescription.

**Comment by alexsmartens** [comment]
Hi @affoltep,
I have a similar issue #1737. Have you figured out how to use attributes in a timeseries widget?

**Comment by affoltep** [comment]
Hi @alexmartens
Unfortunately my issue haven't done any progress ;( 
In your case I simple think it is not possible to show attributes in Timeseries widget. Wouldn't it simply be possible to declare your attribute as timeserie value? 
I know it is dirty, but you could create a rule chain, which copies a shared or server attribute to a timeseries value. I was as well forced to do that once

**Comment by alexsmartens** [comment]
Thank you @affoltep for your suggestion. I've figured how to do it.
Now I'm looking how to subscribe to the telemetry data with the keys defined in my attribute (#1743). Have you had any experience with something like that?

**Comment by hamburml** [comment]
This is important! I have 10 devices which send their battery voltage. All 10 devices are grouped as entity label and the battery voltage is shown in a time series chart. The label is "batteryVoltage".

But I need the label to be customized. The label must be the name of the device. Or an attribute of the device.

**Comment by affoltep** [comment]
@hamburml - you can do it at least a little better. You can replace the label batteryVoltage either with ${entityName} or ${entityDescription}. So you can at least distinguish your devices.
Unfortunately you are still very limited because:
- ${entityName} is usually a non-speaking primary key (e.g. an EUI), which is hardly to understand
- ${entityDescription} is a field that is only editable from the backend (Devices). Neither it exist a rulechain to edit the description field, nor does a widget exist, wich would allow a changement in dashboards.
It would be great if there would be a solution in thingsboard in future ...

**Comment by hamburml** [comment]
Thanks!

**Comment by rcalderon04** [comment]
I can't find the timeseries "label" in v2.4.3PE. Where is the label field located?

**Comment by rcalderon04** [comment]
> This is important! I have 10 devices which send their battery voltage. All 10 devices are grouped as entity label and the battery voltage is shown in a time series chart. The label is "batteryVoltage".
> 
> But I need the label to be customized. The label must be the name of the device. Or an attribute of the device.
> 
> This is not helpful :(
> 
> ![grafik](https://user-images.githubusercontent.com/7239350/65754418-5350ab00-e111-11e9-9ef0-cfcb7262fb96.png)

@hamburml where you able to change the legend to show the device identifier?

**Comment by hamburml** [comment]
@rcalderon04 
Edit the widget, click the edit icon on a data key and there you have the label, which allows ${entityName} or ${entityDescription}.

![image](https://user-images.githubusercontent.com/7239350/78927623-805a1f00-7a9f-11ea-97f8-60ad982ff9d6.png)

**Comment by rcalderon04** [comment]
@hamburml thanks so much. That's clear and I got it working

**Comment by glancia** [comment]
Hi all,

I've just figured out that Label doesn't work like attributes. When I used to update an attribute called "description", the widget subscription would get the change and refresh the widget data immediately. That seems no to be happening with the device label (entity field).

Can you confirm that this is the expected behavior? If yes, would it be possible to add to the subscription?

**Comment by deeja** [comment]
Using v3.2. I can use both label and ID 
```
Battery ${entityName} ${entityLabel}
```
