### ISSUE TITLE
Can't login to Raspberry Pi 3 local Thingsboard with my live.demo login-password

### ISSUE THREAD

**Issue by Natsumi96** [thingsboard/thingsboard#1628]
Good Evening! 
Today I was installing Thingsboard on Raspberry Pi 3 b using [this instruction](https://thingsboard.io/docs/user-guide/install/rpi/#troubleshooting).
I didn`t changed database, remained HSQL. 

In '**Run installation script**' section instead of executing this command
`sudo /usr/share/thingsboard/bin/install/install.sh —loadDemo`
I executed this one:
`sudo /usr/share/thingsboard/bin/install/install.sh` (without option loadDemo) because thought that this option downloads some extra examples besides main features, which I don't need. _(Maybe this is cause of my problem?)_

I got "_Thingsboard installed successfully!_" message in terminal, then opened local:8080 in web browser, entered email and password, but I got "Authentication failed". I'm sure, password and email are correct, they work correctly in live.demo. 

Chromium Dev Tools shows: "status:401 message: Authentication method not supported errorCode:10" when I'm clicking "login" button. At the same time I can correctly sign in with sysadmin@thingsboard.org account. 

How can I sign in with my live.demo registration data?
![Ошибка авторизации](https://user-images.githubusercontent.com/17880853/56048569-3beb5480-5d61-11e9-91a2-094c874a45db.jpg)
![какая ошибка выбрасывается на логин](https://user-images.githubusercontent.com/17880853/56048599-4ad20700-5d61-11e9-91fa-405d0d225392.jpg)

**Comment by mfalkvidd** [comment]
You can't. Live demo and your local installation are different. They do not share logins.

**Comment by Natsumi96** [comment]
Very sad :(  What login should I use in my local instance in such case? How to register?

**Comment by mfalkvidd** [comment]
Not at all sad. Would you really want all thousands of users who have an account at the live demo to be able to login to your raspberry pi?

The default accounts are listed at https://thingsboard.io/docs/samples/demo-account/

**Comment by Natsumi96** [comment]
System Administrator's, Demo Tenant's and and customers' logins work correctly, success! :)
But I still don't understand, why my live.demo account couldn't protect my hardware (raspberry pi) from other users with another live.demo accounts, how could they get access to my hardware (if it was possible to login to local thingsboard with live.demo accounts)?

And another question. If I login with tenant@thingsboard.org account and create there some devices, dashboard, would my devices/dashboards be safe from another users' (who logged in with the same account) modifications?   (I suspect, that the answer is "yes", sorry for silly question, but I really want to understand things very clearly)

**Comment by mp-loki** [comment]
@Natsumi96 There is in OAuth or anything like that. your user login data is stored in the database. The demo account is stored in the demo server database. When you installed ThingsBoard on your Raspberry PI - it has it's own distinct database (Postgres or HSQLB), which has nothing to do with the demo server.

**Comment by Natsumi96** [comment]
@mfalkvidd @mp-loki 
Thank you both for your help!

**Comment by linthoisana** [comment]
hello @Natsumi96 : As i understand your doubt,
 if its the case that you want to access thte dashboards, devices,assests etc which we see in normal demo account. then you should create a tenant account first after logging in as the system adminstrator into your localhost:8080 thingsbaord and then manage the tenant . the link created will lead you to the your own tenant account. maybe this youtube video will help you. https://www.youtube.com/watch?v=v8etQiv2rls

**Comment by rescuehero** [comment]
If another guy runs into this problem under windows:
use \" in the inner quotation marks and " in the outer quotation marks as follows:
`curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"username\":\"tenant@thingsboard.org\", \"password\":\"tenant\"}" "http://XXX:8080/api/auth/login"`
