### ISSUE TITLE
CPU usage 99.3% by Java running Thingsboard

### ISSUE THREAD

**Issue by ofarshi** [thingsboard/thingsboard#1631]
Sorry in advanced for using wrong terms as I'm new to Thingsboard and Linux.
I amm running Thingsboard on Google VM and after 2 weeks of running fine,  the app crashes. I can see in Google Cloud Console that CPU usage is at 100% since the app crashed and by using "top" command I can see that Java is busy running Thingsboard.
I saw some earlier closed issues about it but I don't know how to fix it, as I said I'm new to this.

**Comment by Karabiy** [comment]
make sure that the hardware configuration of yours is an okay for the current payload of yours 
it is an okay for Java to consume the system resources
you also can refer to the ThingsBoard performance on different hardware configurations on this link: https://thingsboard.io/docs/reference/performance-aws-instances/
