### ISSUE TITLE
reconnection failure

### ISSUE THREAD

**Issue by topskymonk** [thingsboard/thingsboard#1636]
I'm having some problems right now.when there is a lot of offline data,platform consumes less data than it produces data, and the service stops.how do we optimize and what is the recommended server configuration like?

**Comment by ban2derlog** [comment]
Hi, what type of query do you use?
It can be query crash or OOM error if you create a high quantity of messages for query.

**Comment by topskymonk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by topskymonk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
