### ISSUE TITLE
Unable to log when debugging a default widget

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1641]
Hi @mp-loki, @ashvayka, @ikulikov, @Terny22,

here is the log of the problem that I'm having when I add a console.log() into flot-widget.js:

```
ERROR in ./src/app/widget/lib/flot-widget.js
/_myPath_/thingsboard/ui/src/app/widget/lib/flot-widget.js
  42:9  error  You should use the "log" method of the AngularJS Service $log instead of the console object  angular/log
  42:9  error  Unexpected console statement                                                                 no-console
  42:9  error  'console' is not defined                                                                     no-undef

✖ 3 problems (3 errors, 0 warnings)
```

I've tried multiple ways to inject AngularJS `$log` into `TbFlot` constructor, but it did not help. The `$log` was always undefined . 

Would you please share a snippet of code of how you log/debug when you develop a widget?

**Comment by mp-loki** [comment]
You have to run your UI on port 3000 as described [here](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#running-development-environment) and use Google Chrome developer tools to debug

**Comment by alexsmartens** [comment]
@mp-loki, 
this is exactly how I am doing it (following the contribution guide). 
[The contribution guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#running-development-environment) however does not have any explanation on how to debug/log during the process of development.  Could you elaborate more on how you debug/log when you develop widgets?

**Comment by mp-loki** [comment]
Open TB UI with Chrome on port 3000, press F12, go to sources tab, find bundle.js file, find a line of code that you need, put a breakpoint, Chrome will decompose bundle.js to separate js files like in the source code.

**Comment by alexsmartens** [comment]
One more option is to pass `$log` to the widget instance on it's initiation.

In this case you shoud change a couple of things:
-  in the widget itself:
```
export default class TbFlot {
...
}
```
to 

```
var $log;
class TbFlot {
...
}

export default function(_$log){
    $log = _$log
    return TbFlot
}
```
-  in the `widget.service.js`:

`function WidgetService($rootScope, $http, $q, $filter, $ocLazyLoad, $window, $translate, types, utils)` 
to 
`function WidgetService($rootScope, $http, $q, $filter, $ocLazyLoad, $window, $translate, types, utils, $log)`

and

`$window.TbFlot = TbFlot;`
to 
`$window.TbFlot = TbFlot($log)`;
