### ISSUE TITLE
create associations in Rule Chains

### ISSUE THREAD

**Issue by sharmmoh1983** [thingsboard/thingsboard#1645]
I am using MQTT Integration for adding devices in ThingsBorad and trying to establish relationship of devices to required Asset in Rule Chain

I am trying to associate device to Asset called Building with create relation node function with following configuration in Rule Chain but relation is not getting updated so how to use create relation:

<img width="767" alt="Screen Shot 2019-04-16 at 7 21 20 am" src="https://user-images.githubusercontent.com/8494468/56254907-0601f380-6106-11e9-8f0f-21c925858582.png">

**Comment by ShvaykaD** [comment]
Hi @sharmmoh1983,

I double checked 'create relation' rule node work in the cloud.thingsboard.io and looks that it working properly.
Probably, you use an earlier TB release, where rule node has some bug.
Could you please update your TB to the latest version, and provide feedback if you will encounter this bug once again. 

Regards,
Dmytro

**Comment by sharmmoh1983** [comment]
@ShvaykaD 

Thanks for your response.It seems to be working now . I dont know what was the reason
