### ISSUE TITLE
Tooltip function not work

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1649]
It does not work properly under the following documents!
please guide.
![error toolpin](https://user-images.githubusercontent.com/32868670/56291457-8b9f9680-613a-11e9-8c6f-cc0231a1547b.png)

**Comment by ashvayka** [comment]
Try not to use dots in your action names and add some logs to console

**Comment by m0o0** [comment]
The problem was resolved with CUSTOM ACTION thus:
sensor_details
sensor_details1
tnx a lot
