### ISSUE TITLE
UMQTT hangs when connecting to Thingsboard

### ISSUE THREAD

**Issue by leonmyburg** [thingsboard/thingsboard#1650]
uMQTT hangs when connecting to Thingsboard using micropython on ESP32. 
client.connect() hangs or sometimes returns 1. Is it protocol mismatch? What can I do to fix it?

from umqtt.simple import MQTTClient

MQTT_CLIENT_ID = '0fd43110-6116-11e9-a733-1f15456eadd5'
MQTT_HOST = 'demo.thingsboard.io'
MQTT_PORT = 1883

TOKEN = '69FsLXITGOwYaKvRdlmP'
PASSWORD = ''

client = MQTTClient(client_id=MQTT_CLIENT_ID, server=MQTT_HOST, port=MQTT_PORT, user=TOKEN, password=PASSWORD, keepalive=10000)

client.connect()

![image](https://user-images.githubusercontent.com/30655060/56293704-e7155880-6129-11e9-9eda-814e3f2cac49.png)

**Comment by ashvayka** [comment]
Please test with short client I'd like "abc". Maybe it is too long.

**Comment by leonmyburg** [comment]
I have used the same client-id to iot.eclipse.org and seemed to work fine. So I do not think that is the issue. Any other suggestions?

**Comment by affoltep** [comment]
Any progress here? 
It might be as well a problem because no password is needed for the thingsboard mqtt api?

**Comment by ashvayka** [comment]
The client id, according to the [spec](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.1.0/com.ibm.mq.doc/tt60310_.htm) is max 23 symbols. Please use a valid client id.

**Comment by zkbutt** [comment]
怎么的解决了吗？
