### ISSUE TITLE
Feature Request - Chart date time mask

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#1651]
Some charts like monthly production don't need to display the time values so I'd like to apply a mask to format the X-axis like "%Y-%M-%D" for instance. This can avoid the need to create a custom widget

**Comment by ssakharova** [comment]
Hello @Tangerino,

Could you please tell me if this feature request is relevant to you?
If so, please provide more details so I can pass this information on to the developers.

**Comment by Tangerino** [comment]
Yes it is. Thank you


*Merci beaucoup, Muito obrigado, Thanks*

*Carlos TangerinoMobile: +33 6 82 05 55 18*

**Comment by ssakharova** [comment]
Hello @Tangerino,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.

There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
