### ISSUE TITLE
Column/attribute type not checked in views

### ISSUE THREAD

**Issue by darkfader** [thingsboard/thingsboard#1656]
View is disregarding the column type (server/shared/client), only the name is matched.

It's easy to recreate:
Try creating both server/shared attribute with the same name but different value. Add both to the columns in entity view. Then both columns show the same value!

Please check if there are no such other references without checking attribute type since it may be a security issue as well !

**Comment by ban2derlog** [comment]
Hi, does issue still persist on latest version of ThignsBoard?
