### ISSUE TITLE
$YOUR_JWT_TOKEN expires in few minutes

### ISSUE THREAD

**Issue by kp372** [thingsboard/thingsboard#166]
Is there any way to make this token permanent(doesn't expire in short time) for HTTP administration api ?

**Comment by toti1212** [comment]
You can config `thingsboard.yml` file. There are properties like `JWT_TOKEN_EXPIRATION_TIME ` and `JWT_REFRESH_TOKEN_EXPIRATION_TIME ` to change the time.
