### ISSUE TITLE
https://xxx.com/swagger-ui.html is not working 

### ISSUE THREAD

**Issue by cjy37** [thingsboard/thingsboard#1660]
I use k8s deployed Thingsboard, but https://xxxxxxxx.com/swagger-ui.html is not working

```
Cannot GET /swagger-ui.html
```

![image](https://user-images.githubusercontent.com/4444496/56559301-c9d20580-65d3-11e9-8512-deaeeaa60754.png)

**Comment by ban2derlog** [comment]
Hi, on latest version of ThingsBoard there isn't any issues with access to REST API.
For K8S, please, use a valid endpoint from:
`kubectl get svc`
or
`kubectl get ingress`
