### ISSUE TITLE
How to Clone Dashboard for same devices?

### ISSUE THREAD

**Issue by punee995** [thingsboard/thingsboard#1663]
I have 20 same devices and created a dashboard for one device.
can anyone tell me how to clone dashboard?
I've tried Exporting then importing it but it did not work. 

Here is the json file [485246.json](https://pastebin.com/qyDtQ7s8) of one device.

**Comment by absinthetized** [comment]
if you look into the json you will find a section called "entityAliases". Inside you will find a number of devices. If you use 1 dash per 1 device you see just 1 dev listed. In your case this starts at line 1365:
```
"entityAliases": {
      "1c5d7d75-cc51-7186-cdba-5b11bfd39e0f": {
        "id": "1c5d7d75-cc51-7186-cdba-5b11bfd39e0f",
        "alias": "485246",
        "filter": {
          "type": "singleEntity",
          "singleEntity": {
            "entityType": "DEVICE",
            "id": "ebbb55c0-63ee-11e9-a71e-9dc52fc05fdb"
          },
          "resolveMultiple": false
        }
      }
```

you have to look at the devices properties and copy the device ID for the new device you want to use the dash with. then:

1. find and replace the dash "name" with a new name *everywhere* in the json (should be around 2 items)
2. find and replace the device ID (should be 1 item)
3. change the device "alias" filed to match the name of the new device

**Comment by punee995** [comment]
@absinthetized thanks a lot that worked!
