### ISSUE TITLE
unable to retrieve multiple historical telemetry data using rest api

### ISSUE THREAD

**Issue by uni-dev10** [thingsboard/thingsboard#1673]
@nabil-rejeb @vparomskiy It'll be great if you could help me understand this.
I'm unable to retrieve **multiple historical telemetry values** using rest api. The swagger UI returns the error as "bad request" but when tried using postman I only get a **single time series value** for the query.

following is the request i'm making.

`http://localhost:8080/api/plugins/telemetry/DEVICE/463cffe0-61d2-11e9-9b11-ef04d3c2162f/values/timeseries?keys=amps&startTS=1555591536000&endTs=1555691230000&interval=10000&limit=1000&agg=AVG` 

and this is the response,
_{
    "amps": [
        {
            "ts": 1556390676359,
            "value": "26.6"
        }
    ]
}_

**Comment by jnmanchado** [comment]
I have the same behaviour. It seems that the request is not OK because it ignore the interval and agg values. Any ideas?

**Comment by PovitruliaV** [comment]
Hi @uni-dev10 ,
Is this issue still relevant?
