### ISSUE TITLE
RPC Terminal cannot executive long running and tty related command. ie.`top` and `vi`

### ISSUE THREAD

**Issue by alfredayibonte** [thingsboard/thingsboard#1675]
RPC terminal cannot executive long-running commands and TTY related commands. ie.` top` and `vi` throws a 408.

**Comment by ban2derlog** [comment]
Hi, 408 error 99% means that you don't properly set endpoint for RPC or have filter\blocks on transport level.
Does it persist on latest ThingsBoard version?
