### ISSUE TITLE
thingsboard compatibility with Azure Cosmos DB

### ISSUE THREAD

**Issue by absinthetized** [thingsboard/thingsboard#1677]
hello,

azure cosmos db [claims](https://docs.microsoft.com/en-us/azure/cosmos-db/cassandra-introduction) wire protocol compatibility with Cassandra (basically it is presented as a drop-in replacement). Did anyone tested thingsboard in such a layout? having a fully managed cassandra would be great!

**Comment by Delapouite** [comment]
Hello @absinthetized 

As your message is from last May, in the end did you experiment with Cassandra on Azure Cosmos DB? Thanks

**Comment by absinthetized** [comment]
Sorry, Nope. I've got the chance to look at some reliability numbers from
Azure and they defeated the purpouse of an HA system.

BTW aws has now launched a similar service.

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Google Cloud Certified - Professional Cloud Architect
Mobile: 3351613944

Il mer 5 feb 2020, 15:23 Bruno Heridet <notifications@github.com> ha
scritto:

**Comment by RHaefeli** [comment]
Hello,

I've tried to run Thingsboard with Azure Cosmos Cassandra db but unfortunately it lead to the following issue that Thingsboard cannot really connect to the database:

```
2020-02-20 14:48:26,351 [main] INFO  com.datastax.driver.core - DataStax Java driver 3.6.0 for Apache Cassandra
2020-02-20 14:48:26,355 [main] INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
2020-02-20 14:48:26,679 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2020-02-20 14:48:26,831 [main] INFO  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport in the classpath, using it
2020-02-20 14:48:47,206 [main] WARN  o.t.s.d.c.AbstractCassandraCluster - Failed to initialize cassandra cluster due to All host(s) tried for query failed (tried: xxx.cassandra.cosmos.azure.com/xx.xx.xx.xx:10350 (com.datastax.driver.core.exceptions.OperationTimedOutException: [xxx.cassandra.cosmos.azure.com/xx.xx.xx.xx:10350] Operation timed out)). Will retry in 3000 ms
2020-02-20 14:48:50,207 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2020-02-20 14:49:10,331 [main] WARN  o.t.s.d.c.AbstractCassandraCluster - Failed to initialize cassandra cluster due to All host(s) tried for query failed (tried: xxx.cassandra.cosmos.azure.com/xx.xx.xx.xx:10350 (com.datastax.driver.core.exceptions.OperationTimedOutException: [xxx.cassandra.cosmos.azure.com/xx.xx.xx.xx:10350] Operation timed out)). Will retry in 3000 ms
```

I'm using the Thingsboard-2.4.3PE Docker container and set the following environment variables inside the container:
```
DATABASE_ENTITIES_TYPE=sql
DATABASE_TS_TYPE=cassandra
SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=postgres

CASSANDRA_CLUSTER_NAME=CosmosProd
CASSANDRA_KEYSPACE_NAME=thingsboard
CASSANDRA_URL=xxx.cassandra.cosmos.azure.com:10350
CASSNADRA_USE_SSL=true
CASSANDRA_USE_CREDENTIALS=true
CASSANDRA_USERNAME=user_xxx
CASSANDRA_PASSWORD=password_xxx
```
Where the url, username and password of course lead to the Azure Cosmos Cassandra DB I've created before. Also if I connect using the cqlsh tool the connection is working just fine.
`cqlsh.py xxx.cassandra.cosmos.azure.com 10350 -u user_xxx -p password_xxx --ssl
`

Any help would be appreciated if anyone encountered the same issue or has any suggestion what could get it to work.

**Comment by absinthetized** [comment]
There is no specific way to troubleshoot. Still did you managed to attach
to a std cassandra node? Just to be sure the config is ok!

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Google Cloud Certified - Professional Cloud Architect
Mobile: 3351613944

Il gio 20 feb 2020, 16:12 RHaefeli <notifications@github.com> ha scritto:

**Comment by RHaefeli** [comment]
Yes, I am running a Cassandra database in another Docker container on the same host system. Although for that setup the config with the environment variables in it is not exactly the same. I tested this without use_credentials and without use_ssll, also the cluster_name is different.

**Comment by KHH80** [comment]
Hello, 
you can complete the installation process on Microsoft Azure Cosmos DB by adding the following parameter to the installation script at /usr/share/thingsboard/bin/install/install.sh:

`-Dhttps.protocols=TLSv1.2`

Unfortunately after starting Thingsboard you will receive errors like "Having multiple aggregate selectors is not supported" in the spring framework. I found the following statement in the Microsoft documentation maybe addressing this issue:

> Server-side filtering, and server-side aggregation is currently not supported in Azure Cosmos DB Cassandra API.

Does anyone know if it is possible to change the aggregation for Cassandra in Thingsboard?

**Comment by PhiVanTran** [comment]
Hello,
I also installed thingsboard on Azure Cosmos DB. However, as @KHH80 mention, It can't start. 
I think that we need a disable option for "Aggregate telemetry and groups" feature in thingsboard. 
A aggregation function for Cassandra will impact to DB performance. So, In some cases, i think we no need the feature.

I hope Thingsboard team will be interested the idea. With the option, thingsboard can be compatibility with a unmanaged service on Cloud.

**Comment by gregwinn** [comment]
@PhiVanTran @KHH80 I was able to get TB PE running and started on Azure CosmosDB Cassandra using the following setup in my config:
```
# MS Azure Cassandra
export CASSANDRA_CLUSTER_NAME=Test Cluster
export CASSANDRA_KEYSPACE_NAME=thingsboard
export CASSANDRA_URL=YOUR_DB_NAME.cassandra.cosmos.azure.com:10350
export CASSANDRA_USE_CREDENTIALS=true
export CASSANDRA_USERNAME=YOUR_USER
export CASSANDRA_PASSWORD=YOUR_PASSWORD
export CASSANDRA_USE_SSL=true
export CASSANDRA_SSL_HOSTNAME_VALIDATION=false
export CASSANDRA_LOCAL_DATACENTER="Write/Read Location AKA West US | Central"
```

I hope that helps!!!
