### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Anu111997** [thingsboard/thingsboard#1678]
Hi all,
I was trying to install thingsboard from source but got the following error while running the command mvn clean install(i have also tried sudo mvn clean install).
Netty MQTT Client .................................. FAILURE [  1.157 s]
[INFO] Thingsboard Server Commons ......................... SKIPPED
[INFO] Thingsboard Server Common Data ..................... SKIPPED
[INFO] Thingsboard Server Common Messages ................. SKIPPED
[INFO] Thingsboard Server Queue components ................ SKIPPED
[INFO] Thingsboard Server Commons ......................... SKIPPED
[INFO] Thingsboard Server Common Transport components ..... SKIPPED
[INFO] Thingsboard MQTT Transport Common .................. SKIPPED
[INFO] Thingsboard HTTP Transport Common .................. SKIPPED
[INFO] Thingsboard CoAP Transport Common .................. SKIPPED
[INFO] Thingsboard Server DAO Layer ....................... SKIPPED
[INFO] Thingsboard Extensions ............................. SKIPPED
[INFO] Thingsboard Rule Engine API ........................ SKIPPED
[INFO] Thingsboard Rule Engine Components ................. SKIPPED
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport Service ................. SKIPPED
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.625 s
[INFO] Finished at: 2019-05-02T17:28:47+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project netty-mqtt: Failed to clean project: Failed to delete /home/hcbs/thingsboard-master/netty-mqtt/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-mqtt

Please help

**Comment by hgrgic** [comment]
I encountered a similar problem few days ago, can you please check which Java version you are using?
By default I had Java 10, and I had to manually switch to Java 8 before executing 
> mvn clean install -DskipTests

Once I did the switch, I has built the project without any issues.

**Comment by Hanane95** [comment]
Just  try  to clean directoy target with rm -R target in netyy-mqtt and try  mvn clean install  -DskipTests

**Comment by Anu111997** [comment]
Hi i have done this found a new issue.
[ERROR] Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:2.3.1-SNAPSHOT: The following artifacts could not be resolved: org.thingsboard.rule-engine:rule-engine-api:jar:2.3.1-SNAPSHOT, org.thingsboard.rule-engine:rule-engine-components:jar:2.3.1-SNAPSHOT, org.thingsboard.common.transport:transport-api:jar:2.3.1-SNAPSHOT, org.thingsboard.common.transport:mqtt:jar:2.3.1-SNAPSHOT, org.thingsboard.common.transport:http:jar:2.3.1-SNAPSHOT, org.thingsboard.common.transport:coap:jar:2.3.1-SNAPSHOT, org.thingsboard:dao:jar:2.3.1-SNAPSHOT, org.thingsboard.common:queue:jar:2.3.1-SNAPSHOT, org.thingsboard:dao:jar:tests:2.3.1-SNAPSHOT, org.thingsboard:ui:jar:2.3.1-SNAPSHOT, org.thingsboard:tools:jar:2.3.1-SNAPSHOT, com.sun:tools:jar:1.4.2: Failure to find org.thingsboard.rule-engine:rule-engine-api:jar:2.3.1-SNAPSHOT in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ShengtianM** [comment]
Add a new mirror to your maven respository may slove it.

**Comment by Anu111997** [comment]
@ShengtianM can you please explain steps to do that... please

**Comment by ShengtianM** [comment]
> @ShengtianM can you please explain steps to do that... please

1. Delete your current maven repository file, just like "C:\Users\tian\.m2\repository".
2. Find the Maven config file, the config file is  "path/to/yourmaven/config/settings.xml"
3. Add a new mirror, such as "<mirror>  
        <id>nexus-aliyun</id>  
        <mirrorOf>central</mirrorOf>    
        <name>Nexus aliyun</name>  
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>  
    </mirror>" to the config file "<settings><mirrors></mirrors></settings>".
4. Rebuild thingsboard.

**Comment by Anu111997** [comment]
It didnt work for me. Facing the same issue

**Comment by e-infotech** [comment]
Hi, I have the same problem. I tried "mvn clean install -DskipTests" as well. How can I fix it?

**Comment by avlo** [comment]
proper settings.xml file contents as follows:

```
<settings>
  <mirrors>
    <mirror>
      <id>nexus-aliyun</id>
      <mirrorOf>central</mirrorOf>
      <name>Nexus aliyun</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public</url>
    </mirror>
  </mirrors>
</settings>
```
and on *nix systems, file typically available as:

```
${user.home}/.m2/settings.xml

**Comment by avlo** [comment]
although the above settings.xml structure is correct, i do not believe it's mirror contents are sufficient.  i'm still experiencing the following error:

> A problem occurred configuring root project 'http'.
> Could not resolve all dependencies for configuration ':classpath'.
>   Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
>   Required by:
>        :http:unspecified
>      Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
>         Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/gradle-ospackage-plugin/3.8.0/gradle-ospackage-plugin-3.8.0.pom'.
>            org.apache.http.ssl.SSLInitializationException: Keystore was tampered with, or password was incorrect

when attempting to build.  this indicates to me that an (encrypted/unencrypted) login/pass is missing from settings.xml (or companion login/pass xml file).  

can anyone confrm or otherwise solved above 

> Keystore was tampered with, or password was incorrect

exception?

**Comment by jiangyi666** [comment]
> although the above settings.xml structure is correct, i do not believe it's mirror contents are sufficient. i'm still experiencing the following error:
> 
> > A problem occurred configuring root project 'http'.
> > Could not resolve all dependencies for configuration ':classpath'.
> > Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
> > Required by:
> > :http:unspecified
> > Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
> > Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/gradle-ospackage-plugin/3.8.0/gradle-ospackage-plugin-3.8.0.pom'.
> > org.apache.http.ssl.SSLInitializationException: Keystore was tampered with, or password was incorrect
> 
> when attempting to build. this indicates to me that an (encrypted/unencrypted) login/pass is missing from settings.xml (or companion login/pass xml file).
> 
> can anyone confrm or otherwise have solved above
> 
> > Keystore was tampered with, or password was incorrect
> 
> exception?

I have the same problems as you .How did you solve it? I had used two days on it!!! I am crazy......

**Comment by ban2derlog** [comment]
Hi, had you tried to use latest ThignsBoard version?

**Comment by v1nayHyder** [comment]
[INFO] ThingsBoard Server Application ..................... FAILURE [11:28 min]
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Version Control Executor ............... SKIPPED
[INFO] ThingsBoard Version Control Executor Microservice .. SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Monitoring Service ..................... SKIPPED
[INFO] ThingsBoard Monitoring Microservice ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34:00 min
[INFO] Finished at: 2024-10-23T15:43:20+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project application: Some files do not have the expected license header -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :application
PS E:\thingsboard_bitxia\thingsboard> 
I have tried many ways to fix it, but I keep encountering the same error every time.

**Comment by v1nayHyder** [comment]
how to fix it ?
