### ISSUE TITLE
Exception while finding entity views for deviceId error when trying to delete a device that has been created via the Gateway Extension

### ISSUE THREAD

**Issue by samf48** [thingsboard/thingsboard#1682]
Using the IOT gateway setup like this: https://thingsboard.io/docs/iot-gateway/getting-started/ 
I am able to send telemetry and a new device pops up in Thingsboard devices.  My issue now is that I cannot delete them.  I get the error "Exception while finding entity views for deviceId[my-entity-id]".  How do I remedy this?  

Also even though I can post telemetry I always have the status "Not Sync" in the Extensions tab of the gateway device in Thingsboard.  I'm not sure if that is related or not. Additionally in the gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "127.0.0.1"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "DIqQtUep9Cb5wTpotqCk"
      remoteConfiguration: true
      extensions:...
of tb-gateway.yml do I need to match the tenant name with the label "Tenant"?

**Comment by samf48** [comment]
I've narrowed down the issue to use of Postgres.  When I use the deault HSQLDAO internal database, I get a green "sync" and am able to delete devices.  What do I need to do for the gateway to sync with postgres?

**Comment by samf48** [comment]
This turned out to be a corrupted PSQL database issue and not a gateway-specific issue.

**Comment by sidthekid87** [comment]
Hey samf48,

What was the problem on SQL? I have the same issue on my instance of TB. Created device using API but I‘m not able to delete it. Same errortext as yours.

**Comment by samf48** [comment]
> Hey samf48,
> 
> What was the problem on SQL? I have the same issue on my instance of TB. Created device using API but I‘m not able to delete it. Same errortext as yours.

I wasn't able to fix it I had to remake the database from scratch.  It seemed to have trouble after I did an "upgrade"...

**Comment by samf48** [comment]
> Hey samf48,
> 
> What was the problem on SQL? I have the same issue on my instance of TB. Created device using API but I‘m not able to delete it. Same errortext as yours.

Just FYI,  even after I rebuilt and the problem seemed to go away. It is now back and I can't delete devices made via the gateway...

**Comment by dacki** [comment]
Hi,
we also had the issue, but we're using cassandra with the micro service architecture(msa) deployment.
In our case restarting redis did the trick. Maybe there's a cache invalidation problem.

**Comment by samf48** [comment]
I think I narrowed down the heart of the issue.  For those using Postgres SQL the table if the "entity_views" table is missing which can apparently happen during an upgrade, you'll see the error.  Problem is I'm not sure how to re-create that table without losing my data....

**Comment by samf48** [comment]
For those of you using Postgres SQL experiencing this issue, the problem seems to be a missing table. Specifically "entity_views".  Evidently it got wiped out or was never created during the upgrade process...  If I knew how to make this table manually I would, but I'm unsure on how to do this.  

Most certainly if you were to run the install process from scratch using the -loadDemo command switch it would put the table back.  My issue is that I have a fully functioning database with a lot of data in it that I would have to restore hence overwriting the table again.  If there is some sort of merge command for sql that could do the trick.

**Comment by ban2derlog** [comment]
Hi, is it still persist or are you using latest version already?

**Comment by ban2derlog** [comment]
@sidthekid87 
Could you check PSQL database, it has?
`public | entity_view          | table | postgres`
And which version do you use?

**Comment by ban2derlog** [comment]
@sidthekid87 
You could try to upgrade database again to 2.3.1 from 2.3.0 version on another instance TB with the issued database via backup.
This is chance that upgrade will repair DB.
Or simply run backuped DB on clean 2.3.1 with --loadDemo and check if you can delete existing devices.

Another way is more complicated - you could install 2.3.1 on another instance with --loadDemo parameters and compare both DB in PostgreSQL. After you create manually entity_view table there might be need to add columns and all other - indexes\constaints to table.
This could fix error after the table will exist, but if not - then you need to create relations between 'broken' devices as it needs to be done in properly working database.

**Comment by sidthekid87** [comment]
@ban2derlog
I chose the second way and installed Thingsboard on another system with the --loadDemo flag. Then I exported the SQL script to create the "entity_view" table and created the table on our productive system. Now everything looks fine and I can delete the devices.

See the SQL script below:

`CREATE TABLE IF NOT EXISTS public.entity_view
(
    id character varying(31) COLLATE pg_catalog."default" NOT NULL,
    entity_id character varying(31) COLLATE pg_catalog."default",
    entity_type character varying(255) COLLATE pg_catalog."default",
    tenant_id character varying(31) COLLATE pg_catalog."default",
    customer_id character varying(31) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    keys character varying(10000000) COLLATE pg_catalog."default",
    start_ts bigint,
    end_ts bigint,
    search_text character varying(255) COLLATE pg_catalog."default",
    additional_info character varying COLLATE pg_catalog."default",
    CONSTRAINT entity_view_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.entity_view
    OWNER to postgres;`

Thanks for you help!
