### ISSUE TITLE
No response to client-side RPC via CoAP

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#1686]
We are evaluating the RPC feature of Thingsboard and ran into trouble getting it to work at all via CoAP. Using HTTP it is all working fine. Using CoAP, however, the message is received and logged correctly on the rule-nodes but the client never receives a response.

After looking at the raw traffic with Wireshark I can see that the server does send out an ACK message to the original request, but that's it. Posting telemetry and even fetching attributes via CoAP is working perfectly fine, though.

Any advice on how to continue debugging would be greatly appreciated.

**Comment by ikulikov** [comment]
Fixed in release v2.4.0
