### ISSUE TITLE
How to add local JS on the server to the HTML code when calling the HTML widget

### ISSUE THREAD

**Issue by liuli283** [thingsboard/thingsboard#1687]
Hi all！
  I want to call the thingsboard server local JS file in HTML code when running HTML dashboard, without modifying the HTML widget。
HTML code like this：
![image](https://user-images.githubusercontent.com/34901796/57275640-b80f5880-70d1-11e9-90bd-599321834552.png)

local path like this ：
![image](https://user-images.githubusercontent.com/34901796/57275790-163c3b80-70d2-11e9-95df-bd0b37943432.png)

**Comment by Cmonkz** [comment]
Hi, Can I ask how'd you do it? I'm having the same problem.
