### ISSUE TITLE
2.3.1.H-PEPT UI Config

### ISSUE THREAD

**Issue by gglemke** [thingsboard/thingsboard#1691]
Tenant 
--> Customer 
-----> Sub-Customer

Sub-Customer does not inherit the Customer UI configuration. Instead, Sub-Customer user is inheriting Tenant UI.   (Sub-Customer should inherit Customer config and see Customer UI. This is not happening in 2.3.1.H-PEPT)

**Comment by ban2derlog** [comment]
Hi, is it still actual on latest ThingsBoard version?
