### ISSUE TITLE
Can't connect mqtt by websocket in browser

### ISSUE THREAD

**Issue by dUXINBrj** [thingsboard/thingsboard#1693]
I can connect mqtt and publish  by mqtt tutorial script in node but it's no use in browser

```
    var mqtt = require('mqtt')
    var client = mqtt.connect('mqtt://xx.xx.xxx.xxx', {
      username: 'S5kebS6Y0dlPz2tPqLo4',
      password: ''
    })  
    client.on('connect', function () {
      console.log('Client connected!')
    })
```
The browser console is:
`stream.js?182c:64 WebSocket connection to 'ws://xx.xx.xxx.xxx/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Change the connect url to 'mqtt://xx.xx.xxx.xxx:1883'
The browser console is:
`stream.js?182c:64 WebSocket connection to 'ws://xx.xx.xxx.xxx:1883/' failed: Connection closed before receiving a handshake response`

Is there anyone know how to solve this problem？

**Comment by absinthetized** [comment]
Try secure websockets wss:// maybe this is an ssl issue.
