### ISSUE TITLE
Entity view: how to set alias in dashboard

### ISSUE THREAD

**Issue by TheBrunez** [thingsboard/thingsboard#1701]
Hi, I've set an Entity View with type "Asset" and assigned an asset that contains some 
In my dashboard I'm not able to configure the alias in order to display telemetry data from the devices. I've tryed all search and relation query without success, I don't know what to do.

To me the right choice might be the "device research query" searching inside the entity view I've created (like in the image below), but this doesn't work.
![image](https://user-images.githubusercontent.com/18346545/57477889-ed66a280-7299-11e9-8bdf-70ac223e31b4.png)

**Comment by nikitaignatov** [comment]
I'm having a similar issue where relation filter is not being applied for Entity Views, other entity types like Device or Assets are shown.

**Comment by myroslav-tb** [comment]
Hi @TheBrunez, we recommend updating your Thingsboard instance to the latest version. It has a more advanced filter for entities in alias settings.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
