### ISSUE TITLE
Dashboard only works when accessed on localhost:9090?

### ISSUE THREAD

**Issue by 3drs** [thingsboard/thingsboard#1702]
Hello! Now, this one is interesting... Thingsboard running locally on Docker (Windows). Raspis publishing data (MQTT). Root Rule Chain sees data coming in OK. When accessing the dashboard on the machine itself (localhost:9090) the widgets display their data perfectly. All good so far...

Now, when accessing that same dashboard from outside the network environment, these same widgets don't display their data! They are static, without any value. When checking the Root Rule Chain, the data is shown, Message Type Switch does it's thing... but the widgets remain dead?!

Very curious to know if someone recognises this behavior and/or if I'm missing something...

Screenshot 1 (localhost)
<img width="1392" alt="Screen Shot 2019-05-10 at 10 08 53" src="https://user-images.githubusercontent.com/50480369/57512578-4d962c80-730c-11e9-90e6-c3aee38d2c16.png">

Screenshot 2 (accessed from outside)
<img width="1440" alt="Screen Shot 2019-05-10 at 10 09 38" src="https://user-images.githubusercontent.com/50480369/57512583-538c0d80-730c-11e9-9aff-3c67c08aa8c4.png">

**Comment by danibjor** [comment]
Did you log in as administrator, under settings, set the external URL?

Also check in browsers developer console, (under network traffic) what the error messages on the WebSockets?

**Comment by 3drs** [comment]
Thank you for the hint on step 1! That was exactly the type of thing I thought I was missing...

However, still getting websocket errors:
failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}

What port should I use/forward for the external access? I used 9090, but the default in Settings was 8080?

**Comment by danibjor** [comment]
I have Thingsboard running on 9090 internally. The port forward rules in firewall is set to route the external 8080 to port 9090 on the internal network, and the url under settings in Thingsboard is set to http://my-domain:8080

**Comment by 3drs** [comment]
OK, thnx. I'm running on 9090 internally as well, and my port forward rule is mydomain:9090 to thingsboardmachine:9090. So setting http://mydomain:9090 should be fine on my install...

Leaves me with the websocket handshake error... Thanks for your help so far!

**Comment by danibjor** [comment]
WebSocket could be the browser that don't want to do WS over regular HTTP, and needs HTTPS for other than localhost.

**Comment by 3drs** [comment]
*** UPDATE ***
Looks like it's not "https-required-for-anything-non-localhost" related, because when I connect from other computers within the same private LAN as localhost, it works on http (local.ip:9090)...
Only when coming from outside, via the port forward rule, the websockets don't connect...

**Comment by 3drs** [comment]
*** UPDATE ***
To install the TB instance on my Windows machine (Docker), I followed this tutorial: https://thingsboard.io/docs/user-guide/install/docker-windows/
I remember that the following section of the tutorial didn't work during install:
In order to get access to necessary resources from external IP/Host on Windows machine, please execute the following commands:
$ VBoxManage controlvm "default" natpf1 "tcp-port9090,tcp,,9090,,9090"  
$ VBoxManage controlvm "default" natpf1 "tcp-port1883,tcp,,1883,,1883"
$ VBoxManage controlvm "default" natpf1 "tcp-port5683,tcp,,5683,,5683"

I only now connected the dots that this is probably the reason my Websockets don't work.

However, that leaves me with the following question: should I do an entire VirtualBox install, just to run these 3 commands? That doesn't make a lot of sense to me, since Docker appears to be an alternative to VirtualBox?!

Any thoughts/help much appreciated!

**Comment by 3drs** [comment]
*** SOLVED ***
Problem was firewall related (packet analysis).
