### ISSUE TITLE
Using Webhooks in sending data outside Thingsboard

### ISSUE THREAD

**Issue by ian2272** [thingsboard/thingsboard#1713]
Hi, is there a way to send data from thingsboard to webhooks? In my case, I'm trying to setup a way where alarms from the thingsboard can be received in Slack. I already have a webhook URL ready, yet I don't know where I should use the URL.

**Comment by danibjor** [comment]
You can do that with the rules engine.
-

Med vennlig hilsen
Daniel Bjørnbakk

*Mobil 905 81 415 <905%2081%20415>*


tir. 14. mai 2019 kl. 12:13 skrev ian2272 <notifications@github.com>:

**Comment by danibjor** [comment]
You can do that with the rules engine.

**Comment by ThomasBaumgartner** [comment]
Hi, I have exactly the same question. Within the rule chain I did not found a solution. @ian2272 have you already found a solution? 
I even tried in the Integration (using TB PE) but in the HTTP - Integration it is not possible to change the HTTP Endpoint-URL freely.

**Comment by ThomasBaumgartner** [comment]
I managed to push data to the webhook using the _rest api call_ node, in the rule chain.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by MayssaJ** [comment]
Hi, I'm trying to do the same thing i want to send data from thingsboard to slack using a webhook, i tried the rest api call but didn't know where to put the webhook url while configuring the rest api call node, any suggestions ? 
Thabk you!

**Comment by willyguevara** [comment]
can someone please share how can we achieve this?
