### ISSUE TITLE
POST http://{ingress address}/api/auth/login 404 (Not Found) when login TB deployed by k8s at localhost minikube

### ISSUE THREAD

**Issue by danielgreenx** [thingsboard/thingsboard#1715]
I have docker CE, minikube and ThingsBoard docker images prepared on Win 10.
I have deployed ThingsBoard using k8s scripts following the instruction below.
https://github.com/thingsboard/thingsboard/tree/master/k8s

And I can see the ThingsBoard login page.
But I got an error when I click the login button in the browser:
    POST http://{ingress address}/api/auth/login 404 (Not Found)
    bundle.e079371135118f94b992.js:formatted:117533

I did not see any errors in pod logs of tb-web-ui as is shown below.

![image](https://user-images.githubusercontent.com/8423328/57750781-2c6f7a80-7716-11e9-8b99-cb65235759da.png)

**Comment by kldjaff** [comment]
I am thinking the error perhaps located in the tb1 or tb2 services. Please have a look of them.

**Comment by danielgreenx** [comment]
> I am thinking the error perhaps located in the tb1 or tb2 services. Please have a look of them.

I have also checked the logs in the tb1 and tb2 pods. And I could not find anything wrong.
By the way, do I have to set the "zk.enabled" = "true" in the "thingsboard.yml" as I am using a micro-service way to deploy tb?

**Comment by danielgreenx** [comment]
> I am thinking the error perhaps located in the tb1 or tb2 services. Please have a look of them.

Is it because I did not create the "HAProxy"?
https://thingsboard.io/docs/reference/msa/#haproxy-or-other-loadbalancer

**Comment by toti1212** [comment]
Did you use the `docker/docker-compose`'s files to do that?

**Comment by zhangxianwei2015** [comment]
Hi,

I have the same issue, seems the Ingress rule is not working, 
      - path: /.*
        backend:
          serviceName: tb-node
          servicePort: 8080

I add below rule, it will work. but I can't add every paths...
      - path: /api/auth/login
        backend:
          serviceName: tb-node
          servicePort: 8080

any ideas?

**Comment by zhangxianwei2015** [comment]
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/
        backend:
          serviceName: tb-http-transport
          servicePort: 8080
      - path: /static/rulenode/
        backend:
          serviceName: tb-node
          servicePort: 8080
      - path: /static/
        backend:
          serviceName: tb-web-ui
          servicePort: 8080
      - path: /index.html
        backend:
          serviceName: tb-web-ui
          servicePort: 8080
      - path: /
        backend:
          serviceName: tb-web-ui
          servicePort: 8080
      - path: /api
        backend:
          serviceName: tb-node
          servicePort: 8080

works for me

**Comment by shocky** [comment]
> path: /api
> backend:
> serviceName: tb-node
> servicePort: 8080

this woks for me, too.

thank you

**Comment by WillNilges** [comment]
Can someone explain how they got the HAProxy load balancer working on k8s?

**Comment by WillNilges** [comment]
Never mind, I got it. The path you have to add to your ingress controller looks like this:
```
- path: /api
pathType: ImplementationSpecific
backend:
  serviceName: tb-node
  servicePort: 8080
```

I'll probably be opening a PR to fix this. It's absurd this took me a whole week to figure out.

**Comment by mokhos** [comment]
Thanks @WillNilges 
Your solution solved my problem installing this (not so professional!) application on my kubernetes cluster!
I'm afraid I had to follow the instructions for minikube to install it on my kubernetes cluster on another cloud. This `- path: /api` is yet not added to the minikube version.
