### ISSUE TITLE
Can't see other options like Dashboard, Customers,Assets.

### ISSUE THREAD

**Issue by rachitmanchanda** [thingsboard/thingsboard#1716]
I did the set up locally on my Windows Machine
I do not see options such as the Dashboard, Assets and Customers on the left navigation panel.
I did the login using sysadmin.
Whereas the tenants and the customers ain't working either.

**Comment by mfalkvidd** [comment]
The sysadmin account is never able to see Dashboard, Assets or Customers. This is by design.

By "ain't working either" do you mean that these accounts are able to login, but they can't see Dashboard, Assets or Customers. Or do you mean that they are unable to login?

**Comment by rachitmanchanda** [comment]
Yeah Figured.
Created a tenant profile and logged in.
Thanks a lot.
Cheers
