### ISSUE TITLE
Global variables in script node

### ISSUE THREAD

**Issue by volkanalkilic** [thingsboard/thingsboard#1717]
Hello,
Node-Red allows creating global variables in this way: `var current = context.get('current') || 0;`
How can I do this in ThingsBoard?

**Comment by mp-loki** [comment]
You can't create global varaibles, but why do you need it? you just the value that you need along with the metadata. Having global variables is generally considered a bad practice.

**Comment by volkanalkilic** [comment]
> You can't create global varaibles, but why do you need it? you just the value that you need along with the metadata. Having global variables is generally considered a bad practice.

Because I have to simulate the parameters of a welding robot that is repeated every 34 seconds. Very easy to do with Node-red;

`var current =context.get('current') || 0;

var akım=[310,317,301,317,320,0,0,321,318,311,329,312,321,310,311,318,328,0,0,0,318,321,317,328,310,308,0,0,305,306,306,319,319,329];
var gerilim=[28,23,28,25,22,0,0,28,23,23,25,24,22,26,22,27,28,0,0,0,23,25,27,22,26,24,0,0,22,27,23,28,24,26];
var debi=[12,6,5,9,4,0,0,6,8,9,7,7,5,8,4,9,9,0,0,0,4,6,5,4,6,7,0,0,7,9,4,7,6,4];
var gaz_tuketimi=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,27,28,29,31,32,33,34,35,36,37];
var kaynak_tel_hizi = [8,9,10,10,8,10,9,8,10,8,8,8,9,8,8,9,9,10,8,10,10,8,9,8,9,10,8,9,8,10,10,10,8,10];
var toplam_tel_tuketimi_mt = [0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.5,13,13.5,14,14.5,15,15.5,16];
var toplam_tel_tuketimi_gr = [1,2,3,5,6,7,9,11,12,14,16,17,19,21,25,27,30,33,35,,36,37,38,39,45,49,,50,53,54,55,56,57,58,59,60];
var durum = ['Kaynak Noktası 1','Kaynak Noktası 1','Kaynak Noktası 1','Kaynak Noktası 1','Kaynak Noktası 1','Geçiş','Geçiş','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Kaynak Noktası 2','Geçiş','Geçiş','Geçiş','Kaynak Noktası 3','Kaynak Noktası 3','Kaynak Noktası 3','Kaynak Noktası 3','Kaynak Noktası 3','Kaynak Noktası 3','Geçiş','Geçiş','Kaynak Noktası 4','Kaynak Noktası 4','Kaynak Noktası 4','Kaynak Noktası 4','Kaynak Noktası 4','Kaynak Noktası 4'];

var data = {akım:akım[current], gerilim:gerilim[current], debi:debi[current], gaz_teketimi:gaz_tuketimi[current], kaynak_tel_hizi:kaynak_tel_hizi[current], toplam_tel_tuketimi_mt:toplam_tel_tuketimi_mt[current], toplam_tel_tuketimi_gr:toplam_tel_tuketimi_gr[current], durum:current, durum2:durum[current]};


current = current +1;
if (current == 34)
current = 0;
context.set('current',current);

return {payload:data};`

**Comment by mp-loki** [comment]
Use the script node + delay node which loops onto the same script node. this way you will be able to simulate increment

**Comment by IoTopenTech** [comment]
Please @mp-loki , could you further elaborate this? I cannot understand how to implement a loop.
Kind regards

**Comment by RBOSAMIYA9** [comment]
answer to whats the need of global variable.

let say I have a device which sends mqtt message on every hand sanitized now I would like to have a counter on thingsboard dashboard to get total no of hand sanitized. 

There is no way we can increment the counter on every mqtt message.
Thats the practical usecase why we need to have global variable in rule engine.

**Comment by omkarfoodef** [comment]
In my use case, i have multiple custom widgets which have same object configuration, this configuration can be changed. So rather than going in every widget and changing it, I should be able to change it at only one place and should be updated throughout every widgets.
