### ISSUE TITLE
Failed upgrade from 2.2.0 to 2.3.0

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#1718]
Try to upgrade to 2.3.0 version , what the problem? How this fix or backup to 2.2.0 ?
The log file  /var/log/thingsboard/install.log https://pastebin.com/KriPisqx
please help

**Comment by mfalkvidd** [comment]
Did your 2.3.0 installation use hsql as database? If not, you probably missed the "merge your thingsboard configuration" step in the [upgrade guide](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#ubuntucentos-13).

**Comment by destr1ke** [comment]
> Did your 2.3.0 installation use hsql as database? If not, you probably missed the "merge your thingsboard configuration" step in the [upgrade guide](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#ubuntucentos-13).
Hi , i use postgresql
database:
  entities:
    type: "${DATABASE_ENTITIES_TYPE:sql}" # cassandra OR sql
  ts:
    type: "${DATABASE_TS_TYPE:sql}" # cassandra OR sql (for hybrid mode, only this value should be cassandra)

**Comment by mfalkvidd** [comment]
Check that the "spring:" section is configured as described on https://thingsboard.io/docs/user-guide/install/linux/#configure-thingsboard-to-use-the-external-database

**Comment by destr1ke** [comment]
> Check that the "spring:" section is configured as described on https://thingsboard.io/docs/user-guide/install/linux/#configure-thingsboard-to-use-the-external-database

`spring:
  data:
    sql:
      repositories:
        enabled: "true"
  sql:
    hibernate:
      ddl-auto: "validate"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thingsboard}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres2}"
`

**Comment by destr1ke** [comment]
> Check that the "spring:" section is configured as described on https://thingsboard.io/docs/user-guide/install/linux/#configure-thingsboard-to-use-the-external-database

`# PostgreSQL DAO Configuration
spring:
  data:
    sql:
      repositories:
        enabled: "true"
  sql:
    hibernate:
      ddl-auto: "validate"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thingsboard}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres2}"
`
Is this because i use standard login?

**Comment by chaos4284** [comment]
# PostgreSQL DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "validate"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thingsboard}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"

**Comment by Karabiy** [comment]
does the issue persists?
