### ISSUE TITLE
espurna MQTT use with thingsboard

### ISSUE THREAD

**Issue by PirSoft** [thingsboard/thingsboard#1725]
hi dear;
i would like use espurna with thingsboard, but not get telemetry date from espurna.
connection is ok. but cat't send telemetry data to thingsboard.
Espurna MQTT settings:
MQTT Root Topic : v1/devices/me/telemetry

Espurna DEBUG 
[557691] [MQTT] Sending v1/devices/me/telemetry/data => {"temperature":26,"humidity":51,"time":"2019-05-15 23:31:30","mac":"18:FE:34:9D:59:75","host":"ESPURNA-9D5975","ip":"192.168.0.134","id":8758} (PID 1)

can't monitoring date from Last Telemetry tab. 
what is problem.?
thanks.

**Comment by Karabiy** [comment]
do you have any kind of a websocket proxying? Is there any message processing in the rule chain in case the debug mode is applied for the rule node?
