### ISSUE TITLE
Customer Unable to Update Attributes

### ISSUE THREAD

**Issue by JordanNel** [thingsboard/thingsboard#1726]
Hi there,

So I have been trying to get this to work for quite some time now without any success. The problem I'm having has to do with updating attributes from a Customers Dashboard. I have assigned the device who's attributes I would like to change and a Dashboard to make the changes to the Customer. 

If I login to my tenant account I am able to successfully update the attributes either through the "Device Attributes" window, or through the Dashboard I have setup with an "Update Shared String Attribute" widget. This is one of the system widgets. However when I login to the customers account, and follow the exact same process, the update fails. This is the case for any type of attribute I have tried (Integer, Boolean, String, etc.). I am using the latest version of Thingsboard at the time of posting - 2.3.1. 

I have a few images to help explain my problem:

**Customer Dashboard:**
![Capture1](https://user-images.githubusercontent.com/42270123/57966547-b5bfc080-7953-11e9-8a95-e2f33ee15bbf.PNG)

**Tenant Dashboard (Same Dashboard)**
![Capture2](https://user-images.githubusercontent.com/42270123/57966550-bf492880-7953-11e9-9c56-fa912d5f9f97.PNG)

![Capture4](https://user-images.githubusercontent.com/42270123/57966567-1222e000-7954-11e9-8a16-9be58538c82f.PNG)

**Attempt to Delete attribute using Customer Login JWT**
![image4144](https://user-images.githubusercontent.com/42270123/57966569-1a7b1b00-7954-11e9-8183-e9e10f82f51e.png)

**Requesting attributes works using customer JWT**
![image4145](https://user-images.githubusercontent.com/42270123/57966581-41395180-7954-11e9-9508-993a3222fd74.png)

**Successfully able to Delete attribute using Tenant Login JWT**
![rect4153-3-1-0-8-6](https://user-images.githubusercontent.com/42270123/57966595-878eb080-7954-11e9-9560-a3e424d19a88.png)

**The error I receive from Google Chrome console when using Customer Login**
![rect4399-0-2-5](https://user-images.githubusercontent.com/42270123/57966603-a55c1580-7954-11e9-9ecb-54a94101ec49.png)

I'm not sure if there are additional rules I need to add the rule chain to get this to work. I'm currently using the default rule chain with no changes. It seems like the customer does not have permission to change the devices attributes, but I am unsure how to go about giving the customer permission.

I would really appreciate any help with this.

Thanks

**Comment by pgrisu** [comment]
Hello, this is reported also in #1547
Starting from thingsboard 2.3.0 the backend doesn't allow attribute creation/wirite from customer users anymore due to usage of  a new permission/security engine
If you need to unlock it you must change customer user permissions list in the backend source code

**Comment by JordanNel** [comment]
Thank you for pointing me to that Issue. That narrows things down a bit and gives me some sort of direction. Out of interest, would you be able to suggest a way in which one could have device settings that a customer can change from their dashboard, and the device can pull this information and be notified (Subscribe) of any changes made by the customer? Would I need to use the RPC interface?

**Comment by Tasosgi** [comment]
I have the same issue. Is very useful the customer user to have the ability to write the shared attributes

**Comment by Tasosgi** [comment]
In thingsboard PE is possible to assign this level of permission to customer user?

**Comment by JordanNel** [comment]
@Tasosgi I'm not entirely sure if it is possible in the Thingsboard PE, but I agree with you that allowing Customers to update shared attributes is a very useful feature to have. My temporary fix for the time being has been to go back to using Thingsboard v2.2 where this is possible. I have been unsuccessful in getting this to work in v2.3.1 by editing the backend source code. I'm still working on getting the source code to build without any errors on a Linux system.

**Comment by kevz93** [comment]
Did anyone try using the RPC command or RESTful requests ?

**Comment by JordanNel** [comment]
@kevz93 I haven't tried using RPC commands to achieve this, but RESTful requests hit the same barrier if you use customer user authentication.

**Comment by seenivasen** [comment]
Does anyone know exactly where in the backend source code the customer /user permissions are? I also need the ability for a customer to update a shared attribute

**Comment by seenivasen** [comment]
The following change in file CustomerUserPremissions.java resolves this issue : 

put(Resource.DEVICE, TenantAdminPermissions.tenantEntityPermissionChecker);

**Comment by fjpanag** [comment]
Any insight from Thingsboard developers on this issue?
Not allowing customers to change attributes limits the functionality a lot, and renders some of the widgets useless.

**Comment by arjentraas** [comment]
> The following change in file CustomerUserPremissions.java resolves this issue :
> 
> put(Resource.DEVICE, TenantAdminPermissions.tenantEntityPermissionChecker);

where is this file typically located?

**Comment by arjentraas** [comment]
> application/src/main/java/org/thingsboard/server/service/security/permission/

Ye i found the java file on the Github page, but couldn't find it on my debian system. (local installation, postgres edition)

**Comment by Ktysai** [comment]
Any update of this issue?

**Comment by congkeodhbk** [comment]
Add Operation.WRITE_ATTRIBUTES to customerEntityPermissionChecker, customerPermissionChecker, customerDashboardPermissionChecker in file https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/permission/PermissionChecker.java

> Ex: private static final PermissionChecker customerDashboardPermissionChecker =
>             new PermissionChecker.GenericPermissionChecker<DashboardId, DashboardInfo>(Operation.READ, Operation.READ_ATTRIBUTES,**Operation.WRITE_ATTRIBUTES**, Operation.READ_TELEMETRY) {

**Comment by PopoTheSapien** [comment]
This seems to be a deal breaker issue.  Customer users should be at the very least be able to add/edit shared attributes for customizing their devices.  Rebuilding every update is going to be super impractical.

In my case, I would like to add attributes that make it possible for a client to set alarm setpoints on devices. In addition I need to store the endpoints for browser push notifications.

**Comment by amizer12** [comment]
> customerDashboardPermissionChecker

You mean this file in 3.0 ?

https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java

**Comment by tavdog** [comment]
Any update on this ?  This seems to be a glaring problem if TB is to be used with real customer who will need to be able to edit their device settings.

**Comment by vcmorini** [comment]
This is a bottleneck for projects in CE

**Comment by vcmorini** [comment]
> > customerDashboardPermissionChecker
> 
> @congkeodhbk
> 
> You mean this file in 3.0 ?
> 
> https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java

Hi @amizer12 , did you manage to do it? I wonder if you found your answer.

**Comment by vcmorini** [comment]
> > application/src/main/java/org/thingsboard/server/service/security/permission/
> 
> Ye i found the java file on the Github page, but couldn't find it on my debian system. (local installation, postgres edition)

Hi, I also couldn't find it inside the .deb file.
Any updates on how to change the customer permission?

Many thanks

**Comment by vcmorini** [comment]
> The following change in file CustomerUserPremissions.java resolves this issue :
> 
> put(Resource.DEVICE, TenantAdminPermissions.tenantEntityPermissionChecker);

Ok, it worked.

Pay attention that you should modify this file: https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java

And then you should [build it](https://thingsboard.io/docs/user-guide/install/building-from-source/#java).
And then you might have some problems such as [this](https://github.com/thingsboard/thingsboard/issues/1952) or [this](https://github.com/thingsboard/thingsboard/issues/482).

And you might solve doing [this](https://github.com/thingsboard/thingsboard/issues/482#issuecomment-518658151) and/or [this](https://github.com/thingsboard/thingsboard/issues/1923#issuecomment-521155672).

**Comment by EmbeddedDevver** [comment]
Same problem here. 
Hope it can be resolved without editing the java files.

**Comment by EmbeddedDevver** [comment]
Just a workaround in case someone does not want to compile the entire Thingsboard from scratch:

Using POST/GET requests you can alter the CLIENT ATTRIBUTES (not possible for SERVER and SHARED attributes). 

Now adjust the widget to update the CLIENT ATTRIBUTES using POST/GET requests placed in the javascript part.

Use this as POST address : http://YOUR_THINGSBOARD_WEBADDRESS/api/v1/YOUR_DEVICE_KEY/attributes

Then you can just send a JSON format.

Now your customer (and also public dashboards) can change values easily without having to login.

**Comment by jpeg2600** [comment]
This is a very upsetting problem to find out at the end of a many hours project hitting a deadline...

**Comment by EmbeddedDevver** [comment]
Thanks to you all it has been fixed in the next release, see https://github.com/thingsboard/thingsboard/commit/60c141d3ca5b154fa48fd0a9c047c6ca504962a4
