### ISSUE TITLE
cannot send data to thingsboard using python

### ISSUE THREAD

**Issue by alfahadiqbal** [thingsboard/thingsboard#1731]
I want to send data to ThingsBoard and display it in widget On dashboard.

By Following [this ](http://www.bytesofgigabytes.com/thingsboard/sending-data-to-thingsboard-using-python/)tutorial I have:

1. Created Device on ThingsBoard by logging into Tenant Administrator.
**Device Description:**

![create-device-on-things-board](https://user-images.githubusercontent.com/24490639/58072115-236c2680-7bb8-11e9-96a6-971a58721b73.PNG)

**Device created sucessfully:**

![devices-on-dashboard](https://user-images.githubusercontent.com/24490639/58072132-2e26bb80-7bb8-11e9-8a89-e949e4bc5b0e.PNG)

**Device Access Token:**

![device-token](https://user-images.githubusercontent.com/24490639/58072145-37b02380-7bb8-11e9-833e-dc3c11e7a541.PNG)

2. Created MQTT client in python with the access token of my device and publish data there.

But Data was not received on the platform as my devices latest telemetry was not showing any data.

**Image showing DH11 Device latest telemetry:**

![latest-telemetry](https://user-images.githubusercontent.com/24490639/58072159-40a0f500-7bb8-11e9-8255-488b7ced969e.PNG)

**### Python Code:**
`import paho.mqtt.client as paho  		    #mqtt library`
`import os`
`import json`
`import time`
`from datetime import datetime`

`ACCESS_TOKEN='lU7Z4e5I8ldaAX57BFSv'                 #Token of your device`
`broker='demo.thingsboard.io'   			    #host name`
`port=1883 					    #data listening port`

`def on_publish(client,userdata,result):             #create function for callback`
`    print("data published to thingsboard \n")`
`    pass`
`client1= paho.Client("control1")                    #create client object`
`client1.on_publish = on_publish                     #assign function to callback`
`client1.username_pw_set(ACCESS_TOKEN)               #access token from thingsboard device`
`client1.connect(broker,port,keepalive=60)           #establish connection`

`while True:`
  
`   payload="{"`
`   payload+="\"Humidity\":60,"; `
`   payload+="\"Temperature\":25";` 
`   payload+="}"`
`   ret= client1.publish("v1/devices/me/telemetry",payload) #topic-v1/devices/me/telemetry`
`   print("Please check LATEST TELEMETRY field of your device")`
`   print(payload);`
`   time.sleep(5)`

What might be the issue? I am looking ahead for your suggestions in fixing it. Thanks in Advance.

**EDIT:** I have also asked [this ](https://iot.stackexchange.com/questions/4167/how-to-send-data-to-thingsboard-using-mqtt-in-python)question on IoT stack-exchange Community but no response was received yet

**Comment by jd-m3** [comment]
+1 

Having the same thing at the moment.

Apparently, I am suspecting Thingsboard Demo's MQTT endpoint is broken as I tested passing telemetry data through HTTP protocol and it's working fine.

On my experience working with Thingsboard demo, all you have to do is wait until it gets fixed.

**Comment by sowbhagya09** [comment]
how can i dispaly data dynamically from board to thingsboard in python using mqqt 
here you just initialising data in static manner,now i want to dispaly data that getting board to thingsboard

**Comment by 7ommaso** [comment]
I use this method:
`read = client.read_input_registers(0x0244, count=1, unit=2)
temperature = read.registers[0]
.......
payload = "{"
payload += "\"Temperature\":" + str(temp);
payload += "}"
.......
ret = client1.publish("v1/devices/me/telemetry", payload)  # topic-v1/devices/me/telemetry`

**Comment by sowbhagya09** [comment]
i wrote code to display data from board to thingsboard check whether it is
right or wrong

from pymodbus.client.sync import ModbusSerialClient as ModbusClient

from pymodbus.payload import BinaryPayloadDecoder

from pymodbus.payload import BinaryPayloadBuilder

from pymodbus.constants import Endian
import paho.mqtt.client as paho      #mqtt library
import os
import json


import time
from datetime import datetime
ACCESS_TOKEN='oFbEhyYvqHqkSIyfl6OI'                 #Token of your device
broker="demo.thingsboard.io"      #host name
port=1883    #data listening port

client = ModbusClient(method='rtu', port='/dev/ttyS2', stopbits=1,
bytesize=8, baudrate=9600, parity='N')
connection = client.connect()
counter = 1
while True:

    print("==========================================================")

    print("Iteration {}" .format(counter))

    print("----------------------------------------------------------")

    WattHour = client.read_holding_registers(0x009E, 2, unit=1)

    decoder = BinaryPayloadDecoder.fromRegisters(WattHour.registers,
Endian.Big, wordorder=Endian.Little)

    print("Watt Hour Reading:", float(decoder.decode_32bit_float()))

    counter += 1

    print("==========================================================")

    time.sleep(2)
def on_publish(client,userdata,result):             #create function for
callback
    print("data published to thingsboard \n")
    pass
client1= paho.Client("control1")                    #create client object
client1.on_publish = on_publish                     #assign function to
callback
client1.username_pw_set(ACCESS_TOKEN)               #access token from
thingsboard device
client1.connect(broker,port,keepalive=60)           #establish connection

while True:

   payload="{"
   payload+="\"WATT\":float(decoder.decode_32bit_float())";

   payload+="}"
   ret= client1.publish("v1/devices/me/telemetry",payload)
#topic-v1/devices/me/telemetry
   print("Please check LATEST TELEMETRY field of your device")
   print(payload);
   time.sleep(2)

**Comment by 7ommaso** [comment]
payload+="\"WATT\":float(decoder.decode_32bit_float())";
in this part I put a string that change dinamically so you might to write:
payload+="\"WATT\:" + str(float(decoder.decode_32bit_float()));
