### ISSUE TITLE
Not a valid working directory error

### ISSUE THREAD

**Issue by kaustubhn** [thingsboard/thingsboard#1732]
<img width="674" alt="Screenshot 2019-05-21 at 1 29 37 PM" src="https://user-images.githubusercontent.com/1524990/58078703-fc6c1f80-7bcc-11e9-9ef2-cac2236cf36f.png">

What can be the issue? Tried setting install env variable did not work.

Please suggest a solution.

Thanks in Advance

**Comment by kaustubhn** [comment]
Not an issue was running application from wrong path.

**Comment by mkuiwu** [comment]
我发现使用pgsql的版本如果是10的话，在运行thingsboard2.4.3的版本中添加租客会出现这个问题。
解决方法就是将postgreSQL换成9.6版本的，是可以成功使用的。

**Comment by discoverkapil** [comment]
> Not an issue was running application from wrong path.

Could you please provide a solution on what have you done. I am facing this weird issues

Not valid working directory: /usr/share/thingsboard/bin. Please use either root project directory
