### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by astroas** [thingsboard/thingsboard#1735]
Hi,
I am trying to enable HTTPS on Thingsboard PE on AWS following the instructions under FAQS for ThingsBoard Professional Edition on AWS Marketplace

> How to enable HTTPS?
> Step 1. Find out your new instance external IP address or assign Elastic IP address.
> Step 2. Assign valid domain name system (DNS) record to your external IP address for first step.
> Step 3. Connect to your instance using SSH or PuTTY using instructions from the previous questions above.
> Step 4. Execute the following commands:
> 
>     sudo certbot-certonly --domain smth.yourcompany.com --email support@yourcompany.com
>     sudo haproxy-refresh

I have an error when I get to Step 4, command not found. It looks like Certbot is not installed.
Question is installing Certbot the best method of enabling https?
Thanks

**Comment by mfalkvidd** [comment]
Unless you have special requirements, installing certbot is the best method.

**Comment by astroas** [comment]
I have installed certbot but I am a little confused how to set it up. 
The DNS record is assigned to the external IP.
I have errors when i do the following command
`sudo certbot certonly --webroot -w /var/www/html -d www.modrasf.com -d modrasf.com `

> Failed authorization procedure. modrasf.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://modrasf.com/.well-known/acme-challenge/xObCWvCPrlK7IgxnUCVh7ySzw72hCrhLdHv9llhHSU4 [54.206.85.7]: 503, www.modrasf.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.modrasf.com/.well-known/acme-challenge/oBpvqYKkBYk-QkPqSHS9UOcIwX2w7eZekOo13ud1Azc [54.206.85.7]: 503
> 
> IMPORTANT NOTES:
>  - The following errors were reported by the server:
> 
>    Domain: modrasf.com
>    Type:   unauthorized
>    Detail: Invalid response from
>    http://modrasf.com/.well-known/acme-challenge/xObCWvCPrlK7IgxnUCVh7ySzw72hCrhLdHv9llhHSU4
>    [54.206.85.7]: 503
> 
>    Domain: www.modrasf.com
>    Type:   unauthorized
>    Detail: Invalid response from
>    http://www.modrasf.com/.well-known/acme-challenge/oBpvqYKkBYk-QkPqSHS9UOcIwX2w7eZekOo13ud1Azc
>    [54.206.85.7]: 503
> 
>    To fix these errors, please make sure that your domain name was
>    entered correctly and the DNS A/AAAA record(s) for that domain
>    contain(s) the right IP address.

What I am doing wrong, is something to do with webroot in the certbot command?

**Comment by dty717** [comment]
You need to config  A/AAAA record(s) for the domain. e.x. in domains.google.com,add Custom resource records for you ip.
[
![chrome_2019-05-23_15-21-39](https://user-images.githubusercontent.com/27396396/58233495-dbdbcb00-7d6e-11e9-9594-c018b22f59f8.png)
](url)

**Comment by patmaclondon** [comment]
I have a similar problem did everything by the book it's all up and running but certbot is giving me the following error :
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for patmac.cloud
Waiting for verification...
Challenge failed for domain patmac.cloud
http-01 challenge for patmac.cloud
Cleaning up challenges
Some challenges have failed.

When I check port 80 via nmap from an external server it says closed... now I think traffic to port 80 is being redirected... But surely that is certbot doing it so I don't get why I'm getting this error.

Tis is on cent os 7.6
