### ISSUE TITLE
Is the demo mqtt server down right now?

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard#1736]
Is the demo mqtt server down right now? I can't connect from yesterday.

**Comment by jd-m3** [comment]
Yes, as I mentioned in my comment (https://github.com/thingsboard/thingsboard/issues/1731#issuecomment-494623986). You can still send telemetry data through HTTP protocol for the mean time.

**Comment by Tasosgi** [comment]
It works now

**Comment by vcmorini** [comment]
> It works now

still not working here. I am following the examples and nothing.
https://thingsboard.io/docs/reference/mqtt-api/#rpc-api

Any clues?

**Comment by Protolucas** [comment]
Hi everyone, I know it has been a while, but I've tried to connect recently to the demo mqtt server and it didn't work for me. Would you know if by any chance they've stopped maintaining it ? Thanks.
