### ISSUE TITLE
How to get attributes in a timeseries widget?

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1737]
Attributes card widget allows adding **Attributes** input along with Timeseries data as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/26261714/58189891-5a5e3d00-7c89-11e9-8cf8-30b857a64e1c.png)

As I can see, I can only add Timeseries data to a Timeseries widget:

![image](https://user-images.githubusercontent.com/26261714/58190200-fdaf5200-7c89-11e9-8fe4-5d6ac3cfd9d4.png)

How to add **Attributes** as an input to a Timeseries - Flot or a custom widget?

**Comment by alexsmartens** [comment]
Thanks to #1134 and #1416, 
the problem has been solved.

This is how I do it in the widget source code:
```
let tbFlot = this,
    attributeService = $injector.get('attributeService'),
    types = $injector.get('types');

attributeService.getEntityAttributesValues(tbFlot.ctx.datasources[0].entityType, tbFlot.ctx.datasources[0].entityId,
    types.attributesScope.server.value,'myAttributeName1,myAttributeName2,myAttributeName3'
).then((attributes) =>{
    $log.log(attributes)
})
```

**Comment by alexsmartens** [comment]
Please feel free to continue this discussion if you know a better way to do it

**Comment by alexsmartens** [comment]
I did get to the bottom of my ideal solution. In this solution, a user can select **Attributes** and **Timeseries** values at the same time in the widget edit menu (the same as the screenshot in my very first post in this thread).

`datasource-entity` directive is responsible for Timeseries/Attributes/other data selection on Widget Edit. The logic of which data to select can be adjusted in
```
ui/src/app/components/datasource-entity.directive.js
ui/src/app/components/datasource-entity.tpl.html
```
For example, line 78 of `ui/src/app/components/datasource-entity.tpl.html` adds Attribute select field only to the latest value widgets as you can see here:
```
...
<md-chips flex ng-if="widgetType === types.widgetType.latest.value"
...
```
You can update the logic of this line in order to have Attributes selection in a Timeseries widget. For example, the following line will allow the user to select **Attributes** at the same time with **Timeseries** values in Timeseries widgets:
```
...
<md-chips flex ng-if="widgetType === types.widgetType.latest.value && 
                      widgetType === types.widgetType.timeseries.value"
...

**Comment by D-Hipple** [comment]
Sorry to open a closed topic. I am new to Thingsboard widget development. I have not found the documentation very clear. I want to do exactly what you are describing, but I have not idea where you are putting this code. can you point me to something explaining this or tell me the path of the file you are editing.  Thanks.

**Comment by indrajitjagtap** [comment]
Hi,
I have been searching for this. I tried your way but I am getting empty object.
I am creating a new custom widget using timeseries widget. I am able to use the attributeservice, no errors. But, it is returning empty object. Any clue from your side will be great help.

Best regards, Indrajit

> Thanks to #1134 and #1416,
> the problem has been solved.
> 
> This is how I do it in the widget source code:
> 
> ```
> let tbFlot = this,
>     attributeService = $injector.get('attributeService'),
>     types = $injector.get('types');
> 
> attributeService.getEntityAttributesValues(tbFlot.ctx.datasources[0].entityType, tbFlot.ctx.datasources[0].entityId,
>     types.attributesScope.server.value,'myAttributeName1,myAttributeName2,myAttributeName3'
> ).then((attributes) =>{
>     $log.log(attributes)
> })
> ```
,
