### ISSUE TITLE
Access token in url path in Device HTTP Api

### ISSUE THREAD

**Issue by dhananjaysathe** [thingsboard/thingsboard#174]
From here 
https://thingsboard.io/docs/reference/http-api/
https://github.com/thingsboard/thingsboard/blob/master/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java

While the url path is protected by SSL this is not a good practice. One could easily still get it from server or edge logs/ web proxies /or browser history. I am curious to know why this scheme was chosen vs something more standard like an Auth header

**Comment by ashvayka** [comment]
device token is a primitive auth option. If your device is able to do SSL you can use mutual auth based on X.509 certificates. Makes sense?

**Comment by ssmaurya** [comment]
Acesstoken is quite handy for doing quick prototypes. For production deployment I would recommend certs as mentioned by Andrew.

**Comment by ikulikov** [comment]
Closing due an inactivity.
