### ISSUE TITLE
docker-compose error 

### ISSUE THREAD

**Issue by Hanane95** [thingsboard/thingsboard#1740]
Hi guys, i try  to  create image  docker for thingsboard  but when  i  lance docker-compose up -d ,  in my browser i taped localhost:8080 it show the login but when  i click  to  login i had an  issues is microservice not found 503. can you  help  me please

**Comment by fenslett** [comment]
Looks like it was brought about by HAProxy, but not so sure.
Could you more explain it in detail such as logs, error messages and screenshots?

**Comment by kldjaff** [comment]
there should be a file named [docker-start-services.sh](https://github.com/thingsboard/thingsboard/blob/master/docker/docker-start-services.sh). Try this one.

**Comment by CooL16** [comment]
To start thingsboard via docker-compose you can do it only by running this command:
sudo ./docker-start-services.sh

P.S. docker-start-services.sh located in the root folder of your docker thingsboard installation.
