### ISSUE TITLE
Working with Cassandra Database

### ISSUE THREAD

**Issue by anrumawas** [thingsboard/thingsboard#1742]
Hi guys, 

I have docker platform running on linux, with thingsboard/tb-cassandra. with port 9042 open. 
I just want to open cassandra database from other computer using NoSQL Manager to check my data. But i have problem, i cant connect NoSQL Manager? are you guys having solution for this?
anyway is there another way to access and see the cassandra database? 

thanks guys

**Comment by absinthetized** [comment]
Not a solution. Are you sure the port is open to the world and not only to the tb container?!

**Comment by anrumawas** [comment]
> 
> 
> Not a solution. Are you sure the port is open to the world and not only to the tb container?!

i tried to run docker by adding -p 9042:9042 in command below, 

> $ docker run -it -p 9090:9090 -p 9042:9042 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-cassandra 

i can open thingsboard by accessing 192.168.1.122:9090, its working fine, so im assuming the port 9042 is open, but i got rejected from my virtual machine when i tried to connect NoSQL Manager
![image](https://user-images.githubusercontent.com/22255993/58316476-d8634500-7e3d-11e9-9690-fb47df5cfe7e.png)

**Comment by absinthetized** [comment]
Try ssh into the cassandra docker container. It is a different container.
Not the one where tb is running. If you can ssh it or even ping it then
this is a step over.

Nunziati Matteo - PhD, Software & Automation.
AWS certified consultant.
Mobile: 3351613944

Il ven 24 mag 2019, 11:08 anrumawas <notifications@github.com> ha scritto:

**Comment by anrumawas** [comment]
okay thansk, i can ssh the container already, thanks 👍
