### ISSUE TITLE
How to subscribe to telemetry data with keys defined inside a widget?

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1743]
I would want to subscribe to telemetry data with a set of selected keys. In my idea, this procedure is to be performed inside a custom widget and it replaces manual datasource selection.

Example:
Instead of going to data settings and manually selecting "SensorA", "SensorB" and "SensorZ" (as shown in the image below), I want my custom widget to request the timeseries data or the latest data based on the provided list of keys, ["SensorA", "SensorB", "SensorZ" ] in this case.

<img src="https://user-images.githubusercontent.com/26261714/58274320-9d3f1400-7d60-11e9-8acd-37f2fbf83a9f.png" width="400">

_In my particular case the list of keys is stored as an attribute (#1737)._

Any idea on how to do it?

**Comment by alexsmartens** [comment]
I've figured how to do it with REST API:
```
let attributeService = $injector.get('attributeService');
let types = $injector.get('types');
attributeService.getEntityTimeseriesValues(tbFlot.ctx.datasources[0].entityType, 
                                           tbFlot.ctx.datasources[0].entityId, 'myKeys1,myKeys2' , 
                                           myStartTime, 
                                           myEndTime,
                                           myPointNumberLimit).then((timeseries) =>{
    $log.log(timeseries)
})

```

**Comment by alexsmartens** [comment]
However I am still looking for a different solution. In my ideal solution, I would like to inject my attributes instead of manually selected attributes. This approach has two major advantages which I am striving to get:

1. The user can easy see and possibly change all the selected timeseries keys;
2. Thingsboard does all the job of getting data and building the legend for me.

Please share your ideas if you know how to do it

**Comment by alexsmartens** [comment]
I did get to the bottom of it. 
`datasource-entity` directive is responsible for Timeseries/Attributes/other data selection on Widget Edit. The logic of which data to select can be adjusted in
```
ui/src/app/components/datasource-entity.directive.js
ui/src/app/components/datasource-entity.tpl.html
```
For example, line 78 of `ui/src/app/components/datasource-entity.tpl.html` adds Attribute select field only to the latest value widgets as you can see here:
```
...
<md-chips flex ng-if="widgetType === types.widgetType.latest.value"
...
```
You can update the logic of this line in order to have Attributes selection in a Timeseries widget

**Comment by glancia** [comment]
@alexsmartens , would you share an example of the second way (simply update the data keys stored in scope.timeseriesDataKeys in datasource-entity.directive.js )?

Thanks!

**Comment by alexsmartens** [comment]
@glancia,
sorry, I'm neither working on thingsboard project anymore, nor have the access to the code base that I worked on.

**Comment by glancia** [comment]
@ashvayka , could you provide an example on how to add/remove a datakey programatically upon self.onInit() ?

Tks
