### ISSUE TITLE
MQTT over SSL for Microservices

### ISSUE THREAD

**Issue by lc2a** [thingsboard/thingsboard#1744]
Hello, 

Is Microservices deployment for MQTT over SSL support X.509 Certificate based authentication for example of two-way SSL connection?

Do I need to enable SSL for tb-mqtt-transport ?  Will the HAProxy able to pass the X.509 Certificate to tb-mqtt-transport ?

Kindly advise.

Thanks

**Comment by mon-dragon** [comment]
I've been trying to enable MQTT over SSL for days now. I was only able to do it on the microservices though and not through HAProxy. I was hoping it'll work seamlessly since the haproxy.cfg file looks like it's just doing an SSL passthrough. I can be wrong since I'm not too familiar with HAProxy.

Does anybody have a config for HAProxy to make this setup work? Or is there any other methods that can successfully enable MQTT over SSL?

**Comment by mon-dragon** [comment]
The microservices architecture supports MQTT over SSL.

The default configuration for MQTT in [haproxy.cfg](https://github.com/thingsboard/thingsboard/blob/master/docker/haproxy/config/haproxy.cfg) is SSL passthrough so certificates to/from tbMqtt1 and tbMqtt1 shouldn't have any problems.

Just configure [tb-mqtt-transport.env](https://github.com/thingsboard/thingsboard/blob/master/docker/tb-mqtt-transport.env) accordingly. You may refer to this for the [values](https://thingsboard.io/docs/user-guide/install/config/#mqtt-transport-settings) and place your JKS file in the [MQTT config directory](https://github.com/thingsboard/thingsboard/tree/master/docker/tb-transports/mqtt/conf)

**Comment by mon-dragon** [comment]
The microservices architecture supports MQTT over SSL.

The default configuration for MQTT in [haproxy.cfg](https://github.com/thingsboard/thingsboard/blob/master/docker/haproxy/config/haproxy.cfg) is SSL passthrough so certificates to/from tbMqtt1 and tbMqtt1 shouldn't have any problems.

Just configure [tb-mqtt-transport.env](https://github.com/thingsboard/thingsboard/blob/master/docker/tb-mqtt-transport.env) accordingly. You may refer to this for the [values](https://thingsboard.io/docs/user-guide/install/config/#mqtt-transport-settings) and place your JKS file in the [MQTT config directory](https://github.com/thingsboard/thingsboard/tree/master/docker/tb-transports/mqtt/conf).

**Comment by Karabiy** [comment]
the comment above seems to be valid for the solution in a microservices deployment 
you also may refer to the MQTT over SSL guide for the ThingsBoard: https://thingsboard.io/docs/user-guide/mqtt-over-ssl/
