### ISSUE TITLE
Windows 10-Error: Main class Files\Thingsboard\lib\thingsboard.jar could not be found or loaded ThingsBoard installation failed!

### ISSUE THREAD

**Issue by SeppPenner** [thingsboard/thingsboard#1747]
When I run the Thingsboard `install.bat` on a Windows 10 machine (under `C:\Program Files\Thingsboard`), I get the following error:

> Error: Main class Files\Thingsboard\\lib\thingsboard.jar could not be found or loaded
ThingsBoard installation failed!

I assume this is caused by the space in the main folder.

**Comment by SeppPenner** [comment]
Yep. It's definitely caused by the space. I would have provided a pull request, but after trying to fix this for half an hour, I have no idea how to do it. Maybe someone else can check this.

**Comment by Ultrazombie** [comment]
Sorry for the very long reply. If the Pull request is still relevant, you can provide a link to it.
But most likely, your problem should already have been fixed in the last releases.

**Comment by SeppPenner** [comment]
> Sorry for the very long reply. If the Pull request is still relevant, you can provide a link to it. But most likely, your problem should already have been fixed in the last releases.

I honestly have no idea as I'm not using Thingsboard actively anymore...
