### ISSUE TITLE
Enhancement: Update documentation to tell users to re-install the service after udpating the database settings.

### ISSUE THREAD

**Issue by SeppPenner** [thingsboard/thingsboard#1750]
After reading through https://thingsboard.io/docs/user-guide/install/windows/, I fell over the issue that my Thingsboard did tell me that the relations needed do not exist. What did I do? Installed Thingsboard, ran it and afterwards changed the database to Postgres. After checking the issues, I found this one: https://github.com/thingsboard/thingsboard/issues/1021.

The request is to add the information that the service needs to be re-installed (Database needs to be re-initialized) after a switch to another database because this is very confusing if you try to setup Thingsboard with Postgres initially!

**Comment by CooL16** [comment]
It is okay, because the database schema is creating during executing install script with the new DB.

**Comment by SeppPenner** [comment]
@CooL16 Is this working with the latest version then? (I haven't had the use case that I needed to install Thingsboard anymore since when this happened).

**Comment by CooL16** [comment]
@SeppPenner Yes, in the latest version if you upgraded the thingsboard (as a service) you have to stop thingsboard service and run an upgrade script.

But if you switch to the empty database (after installation), please run the install script again to initialize the DB scheme again.

P.S. Please refer to this guide for upgrading process: https://thingsboard.io/docs/user-guide/install/upgrade-instructions/

Please let me know if you have any further questions.

**Comment by SeppPenner** [comment]
@CooL16 Thanks. I will let you know if I have more questions on this topic :)
