### ISSUE TITLE
settings schema in JS file

### ISSUE THREAD

**Issue by dhananjay-ranium** [thingsboard/thingsboard#1753]
Hi All, 
1) I'm builidng a custom widget using google maps, but stuck in how to fetch data from **SETTINGS SCHEMA / DATAKEY SETTINGS SCHEMA** from javascript..? 
i'm getting empty object in self.ctx settings key.
tried fetching by using **Flot.settingsSchema()** and **Flot.datakeySettingsSchema()**, but getting empty object there too.

2) is there any way to remove by default Flot fields populated in **Advanced tab** in widget?? 
when i create new object of Flot in JS, the fields automatically gets added in Advanced tab.

any help would be appreciated.. :slightly_smiling_face: 
Thanks.

**Comment by azagaya** [comment]
I think im facing a similar issue. I created a custom widget from a control widget with gpios, but i cannot get settings i add to the Settings Schema, although they appear in the form to confifugre it. Any help?

**Comment by AlexanderPilhar** [comment]
I'm facing the very same problem (v.3.2.2).

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by GrayCygnus** [comment]
This thread so far answers how to access values on the Settings Schema.

However, it is still unclear/unanswered how to access values that are on the Data Key Settings Schema (or the Latest Data Key Settings Schema).

Following the same pattern of self.ctx.settings.theValue yields undefined, and browsing the documentation quite some time I didn't find anything. I see on the https://thingsboard.io/docs/user-guide/contribution/widgets-development/#settings-schema-section documentation that it is stated (emphasis mine):

> The second tab, Data key settings schema, is used to specify JSON schema of data key settings for automatically generating a UI form using the react-schema-form [builder](http://networknt.github.io/react-schema-form/). This generated UI form is displayed in Advanced tab of the Data key configuration dialog. The Settings Object serialized by this schema is used to store specific settings for each data key of the datasource defined in the widget. **These settings are accessible from widget’s JavaScript code**.

How can we access those?
