### ISSUE TITLE
MQTT Gateway API requesting attributes from other customer

### ISSUE THREAD

**Issue by gtzlbck** [thingsboard/thingsboard#1755]
I got a device Gateway A set as gateway and assigned to customer A. When requesting attributes via `v1/gateway/attributes/request` with token Gateway it seems like there is no check on sufficient permissions - I can access attributes of all devices, even when they are assigned to customer B. 
This seems like a security risk to me, or am I getting something wrong?

Thanks a lot for helping!

**Comment by Ultrazombie** [comment]
Closed, as not active.

**Comment by gnassro** [comment]
i think you are right, can someone explain why if its not a security issue ?

**Comment by marcantoinebouchard** [comment]
I have the same issue, and I haven't be able to find a way to secure this using a rulechain. Any solutions?
