### ISSUE TITLE
oracle-java8-installer can not install

### ISSUE THREAD

**Issue by aniceking** [thingsboard/thingsboard#1757]
Oracle-java8-installer has been removed in the PPA source, I downloaded and installed JAVA8, and has configured the environment variables, why I still want to install JAVA when installing, the specific error message is as follows:

dpkg -i thingsboard-2.3.1.deb
(Reading database ... 150589 files and directories currently installed.)
Preparing to unpack thingsboard-2.3.1.deb ...
Unpacking thingsboard (2.3.1-1) over (2.3.1-1) ...
dpkg: dependency problems prevent configuration of thingsboard:
 thingsboard depends on openjdk-8-jre | java8-runtime | oracle-java8-installer | openjdk-8-jre-headless; however:
  Package openjdk-8-jre is not installed.
  Package java8-runtime is not installed.
  Package oracle-java8-installer is not installed.
  Package openjdk-8-jre-headless is not installed.
dpkg: error processing package thingsboard (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.21) ...
Errors were encountered while processing:
 thingsboard

**Comment by CooL16** [comment]
To solve your issue you have to run the following:
sudo apt update
sudo apt install openjdk-8-jdk
sudo update-alternatives --config java

You can check the installation using the following command:

java -version

Expected command output is:

openjdk version "1.8.0_xxx"
OpenJDK Runtime Environment (...)
OpenJDK 64-Bit Server VM (build ...)
