### ISSUE TITLE
lack gen file

### ISSUE THREAD

**Issue by wjx1018960145** [thingsboard/thingsboard#1758]
lack gen files

**Comment by mp-loki** [comment]
Once you have built project with `mvn clean install` you should be able to locate generated files in your file system

**Comment by wjx1018960145** [comment]
Thanks 

发自我的 iPhone

**Comment by Karabiy** [comment]
you can refer to this guide regarding the contribution: https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/
