### ISSUE TITLE
Can't set device credentials trough Swagger

### ISSUE THREAD

**Issue by djchavex** [thingsboard/thingsboard#1760]
Hello I'm trying to set device credentials trough swagger UI but i always get a 400 error when trying to set the device credentials.

`{
  "timestamp": "2019-05-31T15:28:17.129+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "JSON parse error: Unrecognized token 'abcdefg': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'abcdefg': was expecting ('true', 'false' or 'null')\n at [Source: (PushbackInputStream); line: 1, column: 15]",
  "path": "/api/device/credentials"
}
`
I'm inputing the credentials in the box in swagger ui but not working.

![image](https://user-images.githubusercontent.com/4968497/58717117-643b1b00-83c2-11e9-9880-1e536369c3e4.png)

Can you point me in the right direction??

Best Regards

**Comment by deusxmachina42** [comment]
You need to pass a valid JSON to the Thingsboard API. To set the devices access token to abcdefg try this:

`{"credentialsType": "ACCESS_TOKEN","credentialsId":"abcdefg", "deviceId": {"entityType": "DEVICE","id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}}`

where you set id to the device ID you get from /api/tenant/devices
