### ISSUE TITLE
Filtering assets based on attribute value

### ISSUE THREAD

**Issue by ffrexroy** [thingsboard/thingsboard#1768]
I have Asset A and a group of Assets B. A has a relation to the Assets B.
On my dashboard for A I want to show the related Assets from B in an entity view but I only want to  show the Assets from B if one of their attributes has a specific value.

Is there a way to create such a query on the dashboard level? Or do I have to create a custom widget and then manually filter the data?

**Comment by Ultrazombie** [comment]
Closed, as not active
