### ISSUE TITLE
WebSocket Error on new install on AWS AMI

### ISSUE THREAD

**Issue by ppaquin** [thingsboard/thingsboard#1771]
Hi,

I can't have Thingsboard to work on AWS with AMI. I followed this link : 
https://thingsboard.io/docs/user-guide/install/aws/

All is ok, but when i go to any Device screen, I have this message: 
WebSocket Error: Failed to fetch data! 
Now when I post a telemetry, it's a success from device point of view, but nothing visible on Thingsboard.

It's a brand new install, no change done. Just take any AMI and run Thingsboard to reproduce it.

**Comment by ppaquin** [comment]
Mmmh problem seems volatile... It happen all yesterday day, and this morning. And just now, without any change, the message is gone and i see telemetries... 

I'll let you know if it happen again.

**Comment by Karabiy** [comment]
Issue seems to be fixed, so that I am closing this
