### ISSUE TITLE
Thingsboard 2.3 RPM package can not be installed on Fedora 28..30

### ISSUE THREAD

**Issue by PavelTrushkin** [thingsboard/thingsboard#1773]
```bash
rpm --version
RPM version 4.14.2.1
```

```bash
rpm -i thingsboard.rpm 
error: thingsboard.rpm: tag[42]: BAD, tag 1096 type 5 offset 5768 count 52 len 208
error: thingsboard.rpm cannot be installed
```

so, 
```bash
maven package
```

produces fedora 28/29/30 incompatible rpm

**Comment by IvanSemenenko** [comment]
Hi Pavel,

Thank you for your request.
We support rpm packages for CentOs only.
In the case with Fedora, you ought to do it yourself
using source code.

Regards,

**Comment by aljimgar** [comment]
@IvanSemenenko  I have the same problem #2034

**Comment by rosandic** [comment]
I have the same problem on centOS 8

**Comment by IvanSemenenko** [comment]
Dear customers,

Please pay your attention to the fact, -

**This guide describes how to install ThingsBoard on RHEL/CentOS 7.** 
https://thingsboard.io/docs/user-guide/install/rhel/#prerequisites

Regards,

**Comment by rosandic** [comment]
This means CenOS 8 is not supported?

**Comment by ashvayka** [comment]
Starting ThingsBoard 2.5.1 we support CentOS8 installation and this bug is fixed.
