### ISSUE TITLE
Generate an internal alarm that propagates through the thingsboard instance

### ISSUE THREAD

**Issue by taahirk** [thingsboard/thingsboard#1774]
I have a customized map widget and I allow the user to create customized geofence in the shape of a polygon. I also do some processing to determine if the latest coordinates, lat and lng fall within this polygon and output a boolean result.

I would like to be able to trigger an alarm within thingsboard that propagates into a thingsboard alarm widget.

Currently I have tried to look into server attributes to change the state of a flag, but in the thingsboard rule chain we only have client attributes which come through and according to my reading and understanding alarms are generated within the rule chain.

How can I create an alarm from a server attribute change? Or is there any alternate option I can use

**Comment by PavankumarTalla** [comment]
You can use shared attributes..
