### ISSUE TITLE
TB stop working and unable to start

### ISSUE THREAD

**Issue by skabo** [thingsboard/thingsboard#1778]
Hi, TB has been active for several months but today suddenly stopped working. The website does not load and the service seems stopped.
I tried with:
`sudo service thingsboard stop
`
`sudo service thingsboard start`
But it does not work.

This is the log:
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/3276820/thingsboard.log)
Log from Yesterday (seems to be some errors with sql)
[thingsboard.2019-06-10.0.log](https://github.com/thingsboard/thingsboard/files/3277045/thingsboard.2019-06-10.0.log)

Version: 2.3
Database: sql
Server: Linux Mint 18.2

Please any help is welcome.

Thnaks!

**Comment by Karabiy** [comment]
Hello, 
The ThingsBoard does not officially supports the Linux Mint for now
you may refer to the installation options to check the current Linux distributions the ThingsBoard does officially support: https://thingsboard.io/docs/installation/
also, make sure that the java version of yours and make sure that there were no changes being applied for the database directly and it the schema of the thingsboard database is okay
