### ISSUE TITLE
Device logger

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#178]
One of the much needed features on remote management of a device is of course... remote logging.

Apart from telemetry and attributes, a device shall be able to send to the server human readable messages of its internal operation. Either informative messages, or reporting of error conditions.

I would suggest a new MQTT topic, specifically for logging. I would expect a JSON to be posted there with the following structure (or similar):

```
{
  "timestamp": 1498304216, (optional)
  "severity": "INFO",
  "message": "This is a demo log message!"
}
```
I would expect the following severity levels:

- DEBUG
- INFO
- WARNING
- ERROR

Obviously event, email notifications etc should be able to be generated depending on log messages.

Regarding the UI, it is not much needed to have a widget for a dashboard. Rather this is a diagnostic tool mostly needed in tenant administrator's UI. Basic filtering of severity and date, and search of a specific message is all that is needed I believe.

**Comment by fotis400** [comment]
(I suspect you have this issue on your roadmap. I just post it here for expressing interest and also having others to discuss any ideas on this.)

**Comment by fotis400** [comment]
Are there any news on this for the upcoming 1.4 version?

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
