### ISSUE TITLE
draw fixed horizontal line in thingsboard timeseries flot chart

### ISSUE THREAD

**Issue by ignacioliori** [thingsboard/thingsboard#1780]
Hi all,

I'm trying to draw a custom fixed line on my timeseries- float chart widget in thingsboard app.

Any suggestions? @alexsmartens

**Comment by alexsmartens** [comment]
Hi @ignacioliori,
I use [d3](https://d3js.org/) library for my custom charts, and I can easy do it in my case.
But solving a simple problem like you have with d3 is probably an overkill. There should be a simple method to do it

TB uses [flot](http://www.flotcharts.org/) library for their default charts, checking its documentation might be helpful

**Comment by ignacioliori** [comment]
Thanks @alexsmartens , i will check it and get back if i reach a solution.

**Comment by AbCthings** [comment]
I've been using [chart.js](https://www.chartjs.org/) for creating custom charts, it is not hard to get it work and quite complete library for float charts.
You can find an example on how to integrate into ThingsBoard [here](https://github.com/AbCthings/thingsboard-widgets/blob/master/chart-stacked-with-separate-negative-positive.json). This widget does way more than plotting a simple fixed line, you shall filter it to take only the parts of code you really need.
Hope it helps

**Comment by mehmetalikus** [comment]
any updates ??

**Comment by skoczo** [comment]
Hi. @ignacioliori  did you solve your problem? I have smog chart and want to add lines with standards to know when they are exceeded.

**Comment by skoczo** [comment]
I figure it out. You can do this by creation of new datasource. You are selecting function and in function body you are just putting "return yourVal;"
This will draw line on point 0 
![obraz](https://user-images.githubusercontent.com/531574/103382546-c3599800-4aef-11eb-91e0-8c77c1277ff3.png)

**Comment by bioshock2k** [comment]
> 
> 
> I figure it out. You can do this by creation of new datasource. You are selecting function and in function body you are just putting "return yourVal;"
> This will draw line on point 0
> ![obraz](https://user-images.githubusercontent.com/531574/103382546-c3599800-4aef-11eb-91e0-8c77c1277ff3.png)
> like this
> ![obraz](https://user-images.githubusercontent.com/531574/103382576-df5d3980-4aef-11eb-98c7-9dff23c65b3c.png)

This seems briantly simple, trying to use on the PE version and have no display of the line.... weird right?

**Comment by bioshock2k** [comment]
Great solution! just what i needed @skoczo

**Comment by aliaazri** [comment]
actually we can set it on the advanced setting.. 

![image](https://user-images.githubusercontent.com/29271010/126740676-1c25f38b-fd54-426c-83d5-d71c79f7e5b0.png)

**Comment by PawelZielazek** [comment]
Is it possible to add the label to the red line? For example I mean the small "MAX" label placed above the red line?

**Comment by ssakharova** [comment]
No, it is not possible to add the label to the threshold.
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
