### ISSUE TITLE
com.google.gson.JsonSyntaxException: Can't parse value: 

### ISSUE THREAD

**Issue by lalitjoshi86** [thingsboard/thingsboard#1781]
Hello All,

We are building a Hardware to collect data from various type of sensors and Modbus based devices and send data to Thingsboard. While working on Prototype we faced some issues with connectivity. So far we are able to resolved all the issues and now we have started hitting the TB server. However again its stuck after that due to following format related errors i could see int he logs. I am following the TB document but can anyone help to point where i am making a mistake while constructing a message? 

com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171655","seq":1,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171655","seq":2,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171716","seq":3,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171736","seq":4,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171756","seq":5,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171816","seq":6,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171836","seq":7,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171856","seq":8,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171916","seq":9,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}
com.google.gson.JsonSyntaxException: Can't parse value: {"imei":"865291046138029","pver":"1.0","uid":1,"dtm":"20190612171936","seq":10,"msgid":1,"mdev":1,"modbus":[{"sid":1,"stat":0,"len":3,"reg1":0.00,"reg2":0.00,"reg3":0.00}]}

**Comment by lalitjoshi86** [comment]
Looks like there is a limitation on Thingsboards that it cannot accept multiple nodes in one call.

**Comment by deletexiumu** [comment]
你可以修改JsonConverter.java文件中的第160行代码，说白了就是用Gson解析json数据，源码中只是解析基本类型，所以有嵌套格式的就会报错了。修改完以后然后重新编译，重新编译方法可以参考[官方网站](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)

**Comment by NormanArantec** [comment]
Hi!

Looks like still having the same issue. Not able to send more than one information telemetry element from an HTTP integrator.
After dataconverter takes and treat the information from a Campbell Scientific Datalogger into thingsboard json structure (supposed! I can't find any documentation... just examples):

{
    "deviceName": "campbell_1",
    "deviceType": "campbell_scientific",
    "groupName": "campbell_scientific",
    "telemetry": [{
        "ts": 1582109460,
        "telemetry": {
            "Voltage_Pb": 12,
            "Distancia": 14,
            "Level": 200,
            "Clppm": 41,
            "Caudal": 44,
            "Volumen": 77,
            "Caudal_2": 99,
            "Volumen_2": 6,
            "Caudal_3": 40,
            "Volumen_3": 40,
            "Caudal_4": 4,
            "Volumen_4": 440
        }
    }, {
        "ts": 1582109520,
        "telemetry": {
            "Voltage_Pb": 12,
            "Distancia": 44,
            "Level": 44,
            "Clppm": 25,
            "Caudal": 255,
            "Volumen": 740,
            "Caudal_2": 7420,
            "Volumen_2": 720,
            "Caudal_3": 2720,
            "Volumen_3": 770,
            "Caudal_4": 770,
            "Volumen_4": 550
        }
    }]
}

I get the following error:

com.google.gson.JsonSyntaxException: Can't parse value: {"Voltage_Pb":12,"Distancia":14,"Level":200,"Clppm":41,"Caudal":44,"Volumen":77,"Caudal_2":99,"Volumen_2":6,"Caudal_3":40,"Volumen_3":40,"Caudal_4":4,"Volumen_4":440}

Any suggestion?

**Comment by agtokty** [comment]
Hi @NormanArantec, can you try to change your converter to send data like this : 

```
[{
    "ts": 1582109460,
    "values": {
        "Voltage_Pb": 12,
        "Distancia": 14,
        "Level": 200,
        "Clppm": 41,
        "Caudal": 44,
        "Volumen": 77,
        "Caudal_2": 99,
        "Volumen_2": 6,
        "Caudal_3": 40,
        "Volumen_3": 40,
        "Caudal_4": 4,
        "Volumen_4": 440
    }
}, {
    "ts": 1582109520,
    "values": {
        "Voltage_Pb": 12,
        "Distancia": 44,
        "Level": 44,
        "Clppm": 25,
        "Caudal": 255,
        "Volumen": 740,
        "Caudal_2": 7420,
        "Volumen_2": 720,
        "Caudal_3": 2720,
        "Volumen_3": 770,
        "Caudal_4": 770,
        "Volumen_4": 550
    }
}]
```

**Comment by NormanArantec** [comment]
Thanks @agtokty . it works!
