### ISSUE TITLE
Kafka plugin hangs

### ISSUE THREAD

**Issue by yehudarav** [thingsboard/thingsboard#1792]
Hi everybody, 

We are using TB in monolithic mode (in one server) to calculate real time statistics with Kafka+Spark. The Kafka is also installed on  one server 

Our source are 3 stations that transmit at 1Hz (30msg at a time so effectivly 30Hz). 
Then, we have created a sub rule that publish them in kafka (the topic is the device type). 

Our problem is that the kafka plugin hangs after about 40 minutes. 
We have added a log node after the submission to Kafka and it stops 
logging. TB server and the rule before the publish continue to run without a problem.
We tried increasing the buffer memory of the plugin or the amount size of the submitted 
and increasing the number of threads in the Kafka. 

Inspection of the resources shows that our server is not in load. The CPU utilization is low 
and the memory is approx 20GB (of the 250GB). 

Any ideas?

**Comment by Ultrazombie** [comment]
Please use the latest versions of ThingsBoard,
During this time, we have improved ThingsBoard
