### ISSUE TITLE
Unable to send data from external network to local thingsboard server

### ISSUE THREAD

**Issue by zarzaid** [thingsboard/thingsboard#1793]
Hi everyone,

I've a thingsboard server setup in a local university network. i've already requested a public ip and set it following instruction from this [link](https://www.linode.com/docs/development/iot/install-thingsboard-iot-dashboard/#nginx-reverse-proxy).

The thingsboard UI can be accessed from external network (mobile phone data). 
I'm trying to demonstrate the data transfer from arduino (using mobile data) into thingsboard dashboard. 

Currently i don't have the wifi module for arduino but only have the ethernet shield. My pc wifi connected to the mobile data. So, im sharing my pc wifi adapter internet to the pc ethernet port. then, the pc ethernet port connected to the arduino ethernet shield.

**There is no problem when i used CURL command to send the data from my pc using mobile data. However, the arduino can't connect to the internet/send data to thingsboard when i shared the network through ethernet port.**

I've also tried using the same method (ethernet port sharing) but the pc wifi connected with local university wifi network. No problem occur at all. 

Is it the mobile data network security problem or do i need to configure something on my pc to make it work?

Regards
Zar

**Comment by gabrielsuazo** [comment]
Hi! I'm having a similar problem. Did you ever find a solution? Thank you

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the new ticket if this problem still exists.
