### ISSUE TITLE
Alarm created with null detail

### ISSUE THREAD

**Issue by saesf** [thingsboard/thingsboard#1796]
i create an alarm rule that uses message's alarm data. also, i added some details to alarm's data using following function:
`var details = {};`
`details.errorMSG = metadata.errorMSG;`
`details.type = metadata.type;`
`details.originator = metadata.originator;`
`return details;`
when i generate new alarm, detail field of message is null but when i update the existing alarm, detail message gets updated.below are the debug output for create and update message.

> create in:

`metadata{`
`    "deviceType": "C",`
`    "severity": "CRITICAL",`
`    "originator": "AAA",`
`    "clean": "false",`
`    "deviceName": "SBC",`
`    "errorMSG": "CCC",`
`    "ts": "1561003655692"`
`}`
`data{`
`    "type": "BBB",`
`    "severity": "CRITICAL",`
`    "propagate": true`
`}`

> create out

`metadata{`
`    "deviceType": "C",`
`    "severity": "CRITICAL",`
`    "originator": "AAA",`
`    "type": "BBB",`
`    "clean": "false",`
`    "deviceName": "SBC",`
`    "isNewAlarm": "true",`
`    "errorMSG": "CCC",`
`    "ts": "1561003655692"`
`}`
`data{`
`    "tenantId": {`
`        "entityType": "TENANT",`
`        "id": "c035b720-8cf6-11e9-9cb3-97f8d2e47b6f"`
`    },`
`    "type": "BBB",`
`    "originator": {`
`        "entityType": "DEVICE",`
`        "id": "cd685b90-8cf7-11e9-9cb3-97f8d2e47b6f"`
`    },`
`    "severity": "CRITICAL",`
`    "status": "ACTIVE_UNACK",`
`    "startTs": 1561003656234,`
`    "endTs": 1561003656234,`
`    "ackTs": 0,`
`    "clearTs": 0,`
`    "details": null,`
`    "propagate": true,`
`    "id": {`
`        "entityType": "ALARM",`
`        "id": "efbc84e0-9310-11e9-8f25-99ab340e0d6e"`
`    },`
`    "createdTime": 1561003656238,`
`    "name": "BBB"`
`}`

> update output

`data{`
`    "tenantId": {`
`        "entityType": "TENANT",`
`        "id": "c035b720-8cf6-11e9-9cb3-97f8d2e47b6f"`
`    },`
`    "type": "BBB",`
`    "originator": {`
`        "entityType": "DEVICE",`
`        "id": "cd685b90-8cf7-11e9-9cb3-97f8d2e47b6f"`
`    },`
`    "severity": "CRITICAL",`
`    "status": "ACTIVE_UNACK",`
`    "startTs": 1560955053733,`
`    "endTs": 1561003656234,`
`    "ackTs": 0,`
`    "clearTs": 0,`
`    "details": {`
`        "errorMSG": "AAA",`
`        "type": "BBB",`
`        "originator": "CCC"`
`    },`
`    "propagate": true,`
`    "id": {`
`        "entityType": "ALARM",`
`        "id": "efbc84e0-9310-11e9-8f25-99ab340e0d6e"`
`    },`
`    "createdTime": 1561003656238,`
`    "name": "BBB"`
`}`

does anyone know what is the problem or how can i solve this?

**Comment by Karabiy** [comment]
which version the issue of yours relates to? it seems to be not persisted for the latest version, in case of a proper configuration.
