### ISSUE TITLE
Encryption for mqtt payload in thingsboard

### ISSUE THREAD

**Issue by smsachin** [thingsboard/thingsboard#1797]
Hello,

I would like to know if it is possible to do AES encryption and decryption for payload in thingsboard . Is it possible to import required java libraries to do decryption in data converter or in a rule chain.  What are the security features available in thingsboard for mqtt integration ?

I would like to know what can be written in a data converter, how complex the functions can be?

**Comment by vangalvin** [comment]
Did you manage to find out if this can be done? I am looking at the same thing. 
Would prefer the data sent/received from devices be encrypted

**Comment by indrajitjagtap** [comment]
Thingsboard supports MQTT over SSL...

https://thingsboard.io/docs/user-guide/device-credentials/
https://thingsboard.io/docs/user-guide/mqtt-over-ssl/

**Comment by vangalvin** [comment]
I had thought about mqtt-over-ssl however the devices I am working on are battery powered and rely heavily on the deep sleep function, Using SSL would result in the unit having to create the SSL layer for communication then send the data over that resulting in the wake time being a lot longer than if the unit was to encrypt the data then send that directly.

How I see the handling of the data working is to create a rule for the data that decrypts the information then post the telemetry data.

**Comment by smsachin** [comment]
Hi,

I had contacted thingsboard support regarding this, and they replied that at that time(about six months ago) that they too have not tried this and they only suggested about mqtt over SSL as the security feature. I do not think such things are possible in the data converter. However I am not aware  how to use rule chain to do this.

**Comment by indrajitjagtap** [comment]
How to do plan to encrypt/ decrypt the data?

Suggestion: You can encrypt the data while sending to server using public
key. On thingsboard side, you can use data transformation rule node which
allows you to transform the data using javascript code... there you can
decrypt using private key before saving to database.

Please note: I have not tried this solution. If it is workable within
javascript, then it may be possible... you will need to confirm if private
key stored within rule javascript is safe

**Comment by vangalvin** [comment]
@indrajitjagtap 
> How to do plan to encrypt/ decrypt the data? Suggestion: You can encrypt the data while sending 

The ESP32 has built in cryptographic hardware acceleration for AES, SHA-2 and RSA so its prety fast
the AES-128 encryption process is about 68.75ns. 

I think you are correct, having the receiving code handles by javascript would be the best way to handle things. I was however having issues getting the javascript crypt routines to load. this may have just been a config error but will give it another try later in the week. 

@smsachin 
Well will keep you posted as to how or if i manage to get this working :)

**Comment by fkhalek** [comment]
Guys, 

Sorry, any solution for this request?

**Comment by JaumeGarciaU** [comment]
Anyone found a solution for this?

**Comment by HarvUK** [comment]
I'd be interested in this too!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Comment by lukas-k** [comment]
I would like to re-open this issue as we are facing the exact same problem:

- Devices running on battery, only small data volumes possible, making use of deep sleep features. Using SSL handshakes on each message are adding x20 overhead - this is way too much. Especially, since TLS session resumption is only supported by very few IoT backends.

- Thus, encrypting on application layer using AES and a constant private key is very suitable for this purpose.

- We'd also like to use Cryptographic but also struct libraries in the Rule Chains. Would it somehow be possible to add these libraries to the JS runner soon?

- Alternatively, we need to setup a tiny helper service on that instance locally, communicating via Kafka etc. with the rule chain and handling the decryption part.
