### ISSUE TITLE
Things board docker image is giving "Unable to acquire JDBC Connection"

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#1801]
Hi,
I deployed thingsboard docker image(docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb)

when i call relation api i am getting below error.
Error: Request failed with status code 500 (POST http://xxx.xx.x.xx:9090/api/relation) +3ms
Error: 500: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection

**Comment by CooL16** [comment]
Please use docker-compose up with following docker-compose.yml file: 

version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
