### ISSUE TITLE
How can insert past device data into TB using Rule chain else any method

### ISSUE THREAD

**Issue by harikrishna6050** [thingsboard/thingsboard#1805]
hi....
How can add device past data to TB

**Comment by indrajitjagtap** [comment]
I also want to know if that is supported. Many times, we need to send back
dated data, especially when there is network issue.

**Comment by eykamp** [comment]
You can send telemetry with a specific timestamp that would let you insert past data. Also, the database structure is simple enough that you could bulk load historical data directly into the backend.

**Comment by indrajitjagtap** [comment]
Thanks. I could locate the telemetry API with timestamp. I will try how I
can upload in bulk using telemetry API. Any inputs for bulk loading will
certainly help.

**Comment by guru2088** [comment]
I think you use like this for bulk upload of API

Post Request 

http://host:Port/api/v1/token/telemetry


[
    {
    “ts”:1563519044000, “values”:{“x”:0.01,“y”:123, “z”: 0.0002}
    },
    {
    “ts”:1563519057000, “values”:{“x”:111,“y”:0.02, “z”: 0.09}
    }
]

**Comment by indrajitjagtap** [comment]
Yes, I could figure it out. Anyways, thanks for responding.

**Comment by harikrishna6050** [comment]
Hi

All are using ThingsBoard standard application or else

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
