### ISSUE TITLE
Wrong value displayed on panel/dashboard

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#181]
We have a problem with several widgets NOT displaying the latest value as shown in the timeseries panels, for instance the "Digital thermometer".

**Situation:**
- We are using Thingsboard v1.2.3 on Ubuntu 16.04.2 LTS.
- Devices are LoRa devices. Data is pushed into TB using MQTT.
- Dashboard shows a timeseries (last week), and the current temperature panel.

**Problem:**
After opening the dashboard, the thermometer panel does not display the latest value, but seems to display the MAX value shown in the timeseries graph (32 degrees Celcius). Changing the timewindow to for instance 1 day btw does not change the shown 32 degree value, so it might be pure coincidence that the thermometer panel is showing the max value of the timeseries panel.

![screenshot-2017-06-26-13-28-39](https://user-images.githubusercontent.com/1220775/27537275-6ce2ec44-5a73-11e7-9c2b-522132324e4c.png)

If I check the telemetry from the device, it also shows the - wrong - 32 degree celcius value!

![screenshot-2017-06-26-13-31-06](https://user-images.githubusercontent.com/1220775/27537348-be2e0872-5a73-11e7-8b3b-aa4d6e597d83.png)

After some time, the graph is updated to the latest value as shown in the timeseries graph, ie both panels show the same value (as one would expect it to work!).

The second problem is that in many cases, the shown value is rounded, ie 31.9 shows as 32.0 in the thermometer panel.

**Comment by ashvayka** [comment]
Please update the graph to show latest minute of data. This will force graph to use latest 60 values other then aggregated function. I believe you need to compare latest values with the value you send from device. The latest data point you see in the graph is aggregated data for certain interval. For example, it may be aggregated for 1 hour interval if you show latest 7 days, etc.

**Comment by MarsWarrior** [comment]
The aggregated data interval was set to a minute, and I have added the latest value and list widgets.

I'm still trying to replicate the 32 degree problem (the first problem), but the second problem (rounding values) is very easy to replicate by hitting F5 in the browser.

**1. Latest value (with 2 digit floating point) vs table widget:**
The latest value widget keeps ignoring the .xx value: it rounds to the nearest integer.
![screenshot-2017-06-27-11-29-17](https://user-images.githubusercontent.com/1220775/27580954-8e96d332-5b2c-11e7-984b-94cee9a60d14.png)

**2. Gauge widget shows the right value, but again changes after refresh. No digits after ".".**
Before refresh:
![screenshot-2017-06-27-11-20-39-before-f5](https://user-images.githubusercontent.com/1220775/27581042-c6669be4-5b2c-11e7-82dc-6e6ed41a668b.png)
After refresh:
![screenshot-2017-06-27-11-22-12-after-f5](https://user-images.githubusercontent.com/1220775/27581052-c9686ad4-5b2c-11e7-80c0-c020aa7a08d7.png)

**3. The map widget shows the same problem (1 digit).**
Before refresh (1 digit accuracy, ie 24.55 -> 24.6). Note that the pressure (luchtdruk) is wrong.
![screenshot-2017-06-27-11-30-15-before-f5](https://user-images.githubusercontent.com/1220775/27581117-0174db9c-5b2d-11e7-8e7c-530f16b55ff3.png)
After refresh rounded to nearest integer value. And the pressure (luchtdruk) is now the right value according to the latest telemetry value.
![screenshot-2017-06-27-11-30-58-after-f5](https://user-images.githubusercontent.com/1220775/27581127-07672db6-5b2d-11e7-9e22-baa0b4b594ab.png)

**Comment by ashvayka** [comment]
@MarsWarrior Thank your for detailed report. @ikulikov this requires your attention!

**Comment by MarsWarrior** [comment]
No problem.
If you need more information to analyse this problem, please let me know.

**Comment by ikulikov** [comment]
Can't reproduce using latest thingsboard version 1.3.0-SNAPSHOT. (PS: Simple card widget round issue was fixed.)

**Comment by MarsWarrior** [comment]
Great! Then we should test this.
Is 1.3.0 released shortly, or should I build from source?

**Comment by ikulikov** [comment]
Closing due to an inactivity.

**Comment by mamadouly12** [comment]
@MarsWarrior sorry can you explain how do you connect to lora devices please. I have now 2 sensors wth a usb lora server but i don't nknow how can i connect to lora as mqqt for example; 
Thanks
