### ISSUE TITLE
Knob control widget should send an RPC only when mouse is released.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#1810]
I am trying to use the Knob Control widget. As I see, when the value is changed it sends an RPC towards the device.

This however happens also _while_ the user is manipulating the knob. While the knob is turned numerous RPCs are issued (sometimes tens of them). The device is flooded with such requests, which is a great issue for very constrained devices. (My device has not the memory to cope with so many requests, and drops the connection).

Of course there is no use of sending "intermediate" values to the device.

This widget shall send an RPC with the new value _after_ the mouse button is released, i.e. the final value that the user has selected.

**Comment by vvlladd28** [comment]
Hi @fotis400 
Thanks for your report. We'll fix this in the new release TB

**Comment by vvlladd28** [comment]
Hi @fotis400,
We are added a fix for the master branch
