### ISSUE TITLE
is there any documentation about how to fetch telemetry history data using REST API ?

### ISSUE THREAD

**Issue by mohan-mu** [thingsboard/thingsboard#1811]
please provide  API Link if available

**Comment by pgrisu** [comment]
Hi mohan-mu,
Here https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/getTimeseriesUsingGET is descripted the API you are looking for
Please close this issue if you think it's solved

**Comment by mohan-mu** [comment]
thank you @pgrisu
