### ISSUE TITLE
Handshake message sequence violation, 1?

### ISSUE THREAD

**Issue by wuyuefeng123** [thingsboard/thingsboard#1814]
hi
 
first 
 mqtt one-way ssl  ,and i follow thingboard  isuee, use one-way-ssl-mqtt-client.py config.
(https://thingsboard.io/docs/user-guide/access-token/)

server code 
            sslEngine.setUseClientMode(true);
            sslEngine.setNeedClientAuth(true);

         report log : Handshake message sequence violation, 1?

**Comment by wuyuefeng123** [comment]
@ashvayka

**Comment by Karabiy** [comment]
those has to be okay
please, specify who is the logs originator of the one being provided above
