### ISSUE TITLE
UNABLE : to GET telemetary data 

### ISSUE THREAD

**Issue by shrutiraoniit25** [thingsboard/thingsboard#1815]
This is my CURL command:

curl -v -X GET localhost:8080/api/plugins/telemetry/DEVICE/2f1527e0-964b-11e9-a816-2d1cfd7cbeb7/values/timeseries?keys=weight\
 --header "Content-Type:application/json" \ --header "X-Authorization:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJURU5BTlRfQURNSU4iXSwidXNlcklkIjoiYTcwY2E5NzAtOTI3My0xMWU5LTkxNGMtMDM5NTk3MzFlNzNmIiwiZW5hYmxlZCI6dHJ1ZSwiaXNQdWJsaWMiOmZhbHNlLCJ0ZW5hbnRJZCI6Ijk0ZGYzMDYwLTkyNzMtMTFlOS05MTRjLTAzOTU5NzMxZTczZiIsImN1c3RvbWVySWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTU2MTYyMjY1OSwiZXhwIjoxNTYxNjIzNTU5fQ.k1O-1FpcdraNjm2SIH1OL9sWZWOdjNW3cW00HQFWI43l1aNxaBsYOiGCyFX9CT1yZ8OFynuFtLGUQ2DO2zDaig"

**Comment by asaad1882** [comment]
you are missing Bearer in Authorization, it should be like this:
curl -v -X GET --header "Content-Type:application/json" --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc21hYS5zYWFkQGR1LmFlIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiIzYzdlZDdkMC05NTBkLTExZTktOTgwMy1mMzgzYTNkY2Q5MWIiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMGExNDMyNDAtOTUwZC0xMWU5LTk4MDMtZjM4M2EzZGNkOTFiIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTYxNjI5ODc5LCJleHAiOjE1NjE2MzM0Nzl9.VWMirmba4Ho4BoyxXGH0dqBAlQoPyQvMq5klAuRvpr1ofAeOdQb_DLIRrQiEHsCEbHV2Bn6skYun8oWcqzOXSQ' 'http://94.205.239.99:8080/api/plugins/telemetry/DEVICE/717a31b0-967e-11e9-9803-f383a3dcd91b/values/timeseries?keys=lat

**Comment by shrutiraoniit25** [comment]
I tried with that too...I got this
C:\Windows\system32>curl -v -X GET localhost:8080/api/plugins/telemetry/DEVICE/2f1527e0-964b-11e9-a816-2d1cfd7cbeb7/values/timeseries?keys=weight --header "Content-Type:application/json" --header "X-Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJURU5BTlRfQURNSU4iXSwidXNlcklkIjoiYTcwY2E5NzAtOTI3My0xMWU5LTkxNGMtMDM5NTk3MzFlNzNmIiwiZW5hYmxlZCI6dHJ1ZSwiaXNQdWJsaWMiOmZhbHNlLCJ0ZW5hbnRJZCI6Ijk0ZGYzMDYwLTkyNzMtMTFlOS05MTRjLTAzOTU5NzMxZTczZiIsImN1c3RvbWVySWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTU2MTYyNzc1NiwiZXhwIjoxNTYxNjI4NjU2fQ.8pPhkiFD8tKSxcsecL7dDNo2Q_Z7pJRGxO2hkL3u4aZcLOJUMz4lc3VZ2KHTbmIkh9MV6ndh7oInwPMxQkBrag","refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJSRUZSRVNIX1RPS0VOIl0sInVzZXJJZCI6ImE3MGNhOTcwLTkyNzMtMTFlOS05MTRjLTAzOTU5NzMxZTczZiIsImlzUHVibGljIjpmYWxzZSwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJqdGkiOiJjNDFkYjAyOC02OGVjLTRhMTctYTlmYy0wOTk0ZjE3OWI1OGUiLCJpYXQiOjE1NjE2Mjc3NTYsImV4cCI6MTU2MTYzMTM1Nn0.tthKc90EYM91nteDfNzGd-5Ym_T6atEICdw5Qx1jwCodSSsXwrAKtUwFUYkSKbPV2mM03u1hksYP86mWcDIghg"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /api/plugins/telemetry/DEVICE/2f1527e0-964b-11e9-a816-2d1cfd7cbeb7/values/timeseries?keys=weight HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type:application/json
> X-Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJURU5BTlRfQURNSU4iXSwidXNlcklkIjoiYTcwY2E5NzAtOTI3My0xMWU5LTkxNGMtMDM5NTk3MzFlNzNmIiwiZW5hYmxlZCI6dHJ1ZSwiaXNQdWJsaWMiOmZhbHNlLCJ0ZW5hbnRJZCI6Ijk0ZGYzMDYwLTkyNzMtMTFlOS05MTRjLTAzOTU5NzMxZTczZiIsImN1c3RvbWVySWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTU2MTYyNzc1NiwiZXhwIjoxNTYxNjI4NjU2fQ.8pPhkiFD8tKSxcsecL7dDNo2Q_Z7pJRGxO2hkL3u4aZcLOJUMz4lc3VZ2KHTbmIkh9MV6ndh7oInwPMxQkBrag,refreshToken:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJSRUZSRVNIX1RPS0VOIl0sInVzZXJJZCI6ImE3MGNhOTcwLTkyNzMtMTFlOS05MTRjLTAzOTU5NzMxZTczZiIsImlzUHVibGljIjpmYWxzZSwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJqdGkiOiJjNDFkYjAyOC02OGVjLTRhMTctYTlmYy0wOTk0ZjE3OWI1OGUiLCJpYXQiOjE1NjE2Mjc3NTYsImV4cCI6MTU2MTYzMTM1Nn0.tthKc90EYM91nteDfNzGd-5Ym_T6atEICdw5Qx1jwCodSSsXwrAKtUwFUYkSKbPV2mM03u1hksYP86mWcDIghg
>
< HTTP/1.1 401
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 113
< Date: Thu, 27 Jun 2019 09:29:56 GMT
<
{"status":401,"message":"Invalid username or password","errorCode":10,"timestamp":"2019-06-27T09:29:56.416+0000"}* Connection #0 to host localhost left intact

**Comment by shrutiraoniit25** [comment]
it is solved i have taken the reference token to ...so we need to take only one token
