### ISSUE TITLE
[docs] error?

### ISSUE THREAD

**Issue by imsasa** [thingsboard/thingsboard#1816]
https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server
" Before sending PUBLISH message with the request, client need to subscribe to"
it seems that don't need write `client.subscribe('v1/devices/me/attributes/response/+')`

**Comment by Ultrazombie** [comment]
Can you explain the problem in more detail?
As far as I understand, this problem has already been solved
