### ISSUE TITLE
Rule Engine UI very slow while dragging nodes

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#1819]
While dragging nodes around in the Rule Engine, the UI slows down to an almost standstill. I have tested both Chrome and Safari on MacOS and Chrome on Windows, happens every time. 

I've attached a screenshot of a performance graph in Chrome. You can see that basically all time is spent in the pointermove event handler.

![image](https://user-images.githubusercontent.com/8916953/60298813-9ee59400-992b-11e9-8d2b-3b950312324d.png)

**Comment by Karabiy** [comment]
It is an okay for the ThingsBoard 3.0+ version after the angular migration.
