### ISSUE TITLE
why Aggregate node generate 2 different time series data 

### ISSUE THREAD

**Issue by harikrishna6050** [thingsboard/thingsboard#1820]
hi...
i create one rule chain here choose one Analytics node that is "Aggregate latest time series" 
and set the periodical timestamp 5m  to generate output value .it working good,but its going on generate 2 latest time series data...i not understand how it generate..

#how can solve this problem

**Comment by Ultrazombie** [comment]
We have improved this node a lot in three years. Please check on the latest version.
