### ISSUE TITLE
"Tell Failure" on enrichment nodes missing in the UI

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#1821]
The documentation mentions a "Tell Failure" switch on enrichment nodes, but I can't seem to find it anywhere. Neither in my local installation nor in your live demo.

https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-attributes

**Comment by Ultrazombie** [comment]
Hello @JcBernack,
Is there a problem with this in the latest version of ThingsBoard?
