### ISSUE TITLE
Scientific (exponential) format for last value cards widget

### ISSUE THREAD

**Issue by VeryBitter** [thingsboard/thingsboard#1822]
Hi everyone

I am discovering ThingsBoard (great) and still having (a lot) some difficulties to understand how to modify data visualization. I could not find a previous issue related to this topics: is there a simple way to print data in the scientific notation format (#.##E#) for the last value card widget? If not should I create an simple html widget? How? javascript, html, css?
I am dealing with very small numbers of the order of 1e-8, and I would prefer not to print number with 8 zeros. 
Your help would be much appreciated !

Aristide

**Comment by Ultrazombie** [comment]
Closed, as not active.
