### ISSUE TITLE
Swagger documentation problems

### ISSUE THREAD

**Issue by komis1** [thingsboard/thingsboard#1824]
Much of the http api documentation on swagger is broken. For example, try /api/tenant/devices{?type,textSearch,idOffset,textOffset,limit}

The resulting CURL from Swagger is

curl -X GET --header 'Accept: text/html' --header 'X-Authorization: Bearer <TOKEN>' 'http://<thingsboardurl>/api/tenant/devices{?type,textSearch,idOffset,textOffset,limit}&type=<mydevicetype>&limit=10'

Two problems with the above: first, it generates the wrong accept header (text/html, instead of the correct one `"*/*"`). Second, the searchpart after the api endpoint is completely wrong. As a result the call result can't be seen from Swagger, and if you don't notice the wrong accept header, it can take a while to try and figure out why the Spring framework comes back with an error 406.

It would be good if the API documentation could be fixed/updated, thanks!

**Comment by linyixiao** [comment]
I meet the same problem, could you please tell how to solve it.

**Comment by ashaforost** [comment]
Hi @komis1 
 
This issue is completely fixed in the newer thingsboard releases. 
Please let me know if you have found any issues in the current swagger implementation, if so, I'll create an internal ticket for the dev review of the issues.
