### ISSUE TITLE
Added ability to visualize Polygons on the map？

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1825]
I see the v2.3.1 Main features has this function:UI: Added ability to visualize Polygons on the map widgets;

Can anyone tell me how can I do the visualize polygons on the map widget?
I see the map widget's advanced configuration has a radio button like below, is this the visualize polygon on map function? if it is, where is the place to fill the lantitude and longitude of the device?
![image](https://user-images.githubusercontent.com/31084798/60500297-aa9ad700-9cec-11e9-88ae-af02e8956b9d.png)

**Comment by danibjor** [comment]
the attribute coordinates needs to be a type string, containing an array of lat,lng coordinates.

Like so: `[[lat,lng],[lat,lng],[lat,lng]]`

`[[58.046203,7.271538],[62.128546,4.986382],[63.228927,12.193413]]`
will result in this map:

![image](https://user-images.githubusercontent.com/2149381/60502249-ba4ef700-9cbd-11e9-97ce-0521dfc1c9ee.png)

**Comment by qwyinxiang** [comment]
Thank you very much for your response.
But, whenever I fill my coordinates clockwise or anticlockwise, there is nothing shown on my map.
Anything wrong?
![image](https://user-images.githubusercontent.com/31084798/60559644-a53a9c80-9d7f-11e9-91c9-28d033ea8b36.png)

![image](https://user-images.githubusercontent.com/31084798/60559675-c26f6b00-9d7f-11e9-92d7-fcfc925e5ec4.png)

**Comment by qwyinxiang** [comment]
I use the coordinate points you gave above, and I don't see polygons on the map. Is it wrong with me?
![image](https://user-images.githubusercontent.com/31084798/60560345-ef248200-9d81-11e9-9b27-e6e1d0492dc6.png)
![image](https://user-images.githubusercontent.com/31084798/60560416-49bdde00-9d82-11e9-924f-df8683449aab.png)

**Comment by danibjor** [comment]
Hi,

The coordinates needs to be on a `Device` or `Asset`. 

Here is my test-device:
![image](https://user-images.githubusercontent.com/2149381/60587133-fbb1d600-9d93-11e9-8ac6-c7df432187ff.png)

On the map, I configure it to show the entity( or entities), add the attribute that contains the coordinates (this could also be telemetry data).
![image](https://user-images.githubusercontent.com/2149381/60587204-29971a80-9d94-11e9-8684-20cfec88796f.png)

On tab Advanced, you specify the attribute that contains your polygon coordinates:
![image](https://user-images.githubusercontent.com/2149381/60587258-49c6d980-9d94-11e9-9274-a380a8c98381.png)

**Comment by qwyinxiang** [comment]
I can show the polygons on the map, thank you very much for your help.

**Comment by IoTopenTech** [comment]
Unfortunately there seems to be a bug/problem with the Trip animation Widget.
In this widget you can only select timeseries as data imput, but not attributes, so you cannot select a polygo attribute with the coordinates
![imagen](https://user-images.githubusercontent.com/52624907/80704490-efe28d80-8ae4-11ea-9430-b55b5aa3b9e0.png)
Nevertheless, in the Last value widget attributes selection is indeed allowed
![imagen](https://user-images.githubusercontent.com/52624907/80704668-464fcc00-8ae5-11ea-82f3-ebb295bbd201.png)

**Comment by juanesteban1403** [comment]
@IoTopenTech Hi!, I have the same problem, Did you solve it ? i tried to send coordinates as timeseries but unfortunately did not work, I tried  even to upgrade to version 3.0.1 but it still not working
