### ISSUE TITLE
How to connect ESP8266 to secure MQTT

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1830]
Hi
I am trying to establish a connection between esp 8266 and the server. If possible, please declare the codes for esp 8266.
It should be noted that the server-side configuration was done and checked with the Python script.
Thanks.

**Comment by m0o0** [comment]
@vparomskiy please help

**Comment by m0o0** [comment]
I set up this item, but randomly some messages between the server and the device are lost.
why?

**Comment by Ultrazombie** [comment]
Is your problem still relevant?
