### ISSUE TITLE
Temperature upload over MQTT using Teensy, ESP12E and DHT22 sensor

### ISSUE THREAD

**Issue by Lavanyarajan** [thingsboard/thingsboard#1832]
Im getting the below compilation error when I try to compile and upload the code available in the  link for the Teensy board instead of Arduino:

https://thingsboard.io/docs/samples/arduino/temperature/

C:\Program Files\Arduino\hardware\teensy\avr\cores\teensy3/Stream.h:68:6: error: 'int Stream::timedRead()' is private

  int timedRead();

      ^

C:\Program Files\Arduino\libraries\ArduinoHttpClient\src\HttpClient.cpp:576:17: error: within this context

         int c = timedRead();

                 ^

In file included from C:\Program Files\Arduino\hardware\teensy\avr\cores\teensy3/HardwareSerial.h:252:0,

                 from C:\Program Files\Arduino\hardware\teensy\avr\cores\teensy3/WProgram.h:46,

                 from C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_942455/pch/Arduino.h:6,

                 from C:\Program Files\Arduino\libraries\ArduinoHttpClient\src\HttpClient.h:8,

                 from C:\Program Files\Arduino\libraries\ArduinoHttpClient\src\HttpClient.cpp:5:

C:\Program Files\Arduino\hardware\teensy\avr\cores\teensy3/Stream.h:68:6: error: 'int Stream::timedRead()' is private

  int timedRead();

      ^

C:\Program Files\Arduino\libraries\ArduinoHttpClient\src\HttpClient.cpp:576:27: error: within this context

         int c = timedRead();

                           ^

Error compiling for board Teensy 3.2 / 3.1.

How can I solve this?

**Comment by Ultrazombie** [comment]
Hello @Lavanyarajan 
Is your problem still relevant?
