### ISSUE TITLE
Axis labels wrong

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#1834]
The vertical axis labels are wrong, as shown in the attached image.  I believe the bottom "4" should be "3.5", and that there is a rounding/digits display issue going on.

![image](https://user-images.githubusercontent.com/1133323/60620593-7a0c7900-9d90-11e9-9d82-f0005d04539b.png)

**Comment by eykamp** [comment]
I am running stock Thingsboard 2.3 community version, using Chrome browser on Win10.

**Comment by pgrisu** [comment]
Hello eykamp, you can set Y-axis resolution by 'The number of decimals to display' in widget advanced settings.
If you select '1' the graph will show one decimal point on Y-axis values.
Please close this issue if you think it's solved

**Comment by Ultrazombie** [comment]
@eykamp please confirm if the last message helped you
