### ISSUE TITLE
class missing in the build MsgProtos 

### ISSUE THREAD

**Issue by vijayshukla80** [thingsboard/thingsboard#1836]
the java class missing in the build under common folder org.thingsboard.server.common.msg.gen.MsgProtos

**Comment by vijayshukla80** [comment]
/Users/Silverspring/Projects/Intellij-workspace/thingsboard/common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
Error:(25, 45) java: package org.thingsboard.server.common.msg.gen does not exist

**Comment by xujunxing1991** [comment]
重新编译吧

**Comment by coder-chriswang** [comment]
@vijayshukla80 the same problem
the MsgProtos.java is missing

**Comment by coder-chriswang** [comment]
![image](https://user-images.githubusercontent.com/40193732/61362389-b376d580-a8b4-11e9-9f11-23a6cbe00308.png)

**Comment by coder-chriswang** [comment]
the gen package does not exist

**Comment by coder-chriswang** [comment]
@vijayshukla80 I know that :
![image](https://user-images.githubusercontent.com/40193732/61362907-9a225900-a8b5-11e9-9826-63a4d83abbf6.png)

**Comment by shoshin86** [comment]
Hello any solution to this?

**Comment by xujunxing1991** [comment]
你的依赖包下载失败了，导致没有那个类，需要翻墙下载依赖！希望可以帮到你






在 2019-07-17 17:09:47，"王超" <notifications@github.com> 写道：


@vijayshukla80 I know that :

**Comment by Ultrazombie** [comment]
Hello @skewty 
I contacted the developer, and he said that everything works for us. Could you try increasing the file size in IDEA?

Help -> Edit Custom Properties -> idea.max.intellisense.filesize=**50000**
