### ISSUE TITLE
Input widget not working with multiple devices

### ISSUE THREAD

**Issue by LanceFoudre** [thingsboard/thingsboard#1837]
Recently i started to working on ThingsBoard, having my devices integrated with HTTP, having things working well. I managed to send messages to my devices via an API rest, wich can be triggered by updating attributes with an input widget.
My problem is, when using a list of devices as data for the widget, there's still only one input field to use, plus it only update one device.
So, is it possible to have an input widget that show multiple input field for each device ? As anyone manage to do so ?

**Comment by mircopz** [comment]
Hi, I created a new widget that publishes multiple input fields for different datasources, by doing one or more POST request. Currently only works with server or shared attributes, not timeseries values.
You can check [my pull request](https://github.com/thingsboard/thingsboard/pull/1833) (currently on the waiting list). Let me know if it's what you're looking for!

**Comment by LanceFoudre** [comment]
It seems to be what i'm looking for. But is it possible for you to send me the exported JSON file of the widget ? I'm working with ThingsBoard as a trainee, so i can't access ThingsBoard files, plus as i'm a newbie in coding and stuff, i don't really know how to use your files.
But i greatly appreciate your help !

**Comment by mircopz** [comment]
Sorry but this widget references some source files also, I developed it as a system widget. You can wait for my pull request to be approved, in order to have it in the next release.

**Comment by LanceFoudre** [comment]
Guess i have to wait then, but thanks you anyway, for your help and for your work, i'm sure it gonna be super useful

**Comment by jcgtrace** [comment]
> Recently i started to working on ThingsBoard, having my devices integrated with HTTP, having things working well. I managed to send messages to my devices via an API rest, wich can be triggered by updating attributes with an input widget.
> My problem is, when using a list of devices as data for the widget, there's still only one input field to use, plus it only update one device.
Hi Lance. It sounds like you have done what I need and I am also a newbie to tb. Any change you could give me some instructions how to get inputs from tb to device. I am struggling with how to send the attribute from tb, and then how is can be received. I am using ESP32 and Arduino IDE. A multiple input widget would be perfect but I will also have to wait for that.

**Comment by jcgtrace** [comment]
Hi Lance. It sounds like you have done what I need and I am also a newbie to tb. Any change you could give me some instructions how to get inputs from tb to device. I am struggling with how to send the attribute from tb, and then how is can be received. I am using ESP32 and Arduino IDE. A multiple input widget would be perfect but I will also have to wait for that.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
