### ISSUE TITLE
mvn clean install -Ddockerfile.skip=false  execution failed

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1838]
I use the v2.3.1 and I want to build from source files.
I have installed java and maven on my linux machine, and clone the source code v2.3.1 from git.
Then I execute the following command:

       mvn clean install -Ddockerfile.skip=false

It seems that something went wrong.

Below is the error message:

[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.5:build (build-docker-tb-image) on project tb: Could not build image: The command '/bin/sh -c dpkg -i /tmp/thingsboard.deb' returned a non-zero code: 1 -> [Help 1]

![image](https://user-images.githubusercontent.com/31084798/60700471-9cd29500-9f2a-11e9-81ff-7eede092ce5d.png)

**Comment by kevz93** [comment]
Check if your docker is running and available on the default port given by the environment variable `DOCKER_HOST`
