### ISSUE TITLE
pagination not work

### ISSUE THREAD

**Issue by tng99** [thingsboard/thingsboard#1839]
hi

when I click "next" to see next page nothing happens. Not only at Dashboards but also other places which having pagination (next and previous page)
 
![image](https://user-images.githubusercontent.com/44582289/60655802-8ff56900-9e78-11e9-80b0-03d07848d85e.png)

Thanks for thingsboard.
br

**Comment by mircopz** [comment]
Are you sure to have more than 10 elements? 10 is the default size for pagination, and in your example you have only 6 elements, so there aren't more pages to select

**Comment by tng99** [comment]
yes, i had collect at this time every ten second, so it should be many
page. Could you try this yourself?

/T

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tng99** [comment]
or maybe it only allow to save the last 6 elements?

**Comment by mircopz** [comment]
Change the timewindow settings, you have selected "Last minute", so only last 6 values are shown

**Comment by tng99** [comment]
thanks very much , it is my fault :-). paginate  works fine.

[image: image.png]

br Tuan
