### ISSUE TITLE
Check for update availability

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#184]
At the moment there is no easy way to see what the latest version of Thingsboard is (and subsequently decide whether you need to update or not).

When I use a search engine to look for `Thingsboard version` I cannot find an obvious answer either. I think that in an ideal case there should be a system-related section in the administrator's interface, that should indicate:

- the current version
- the latest version currently available
- some sort of an icon that can be `green` if you have the latest version and `orange` if you're running an old version

The last point is technically not necessary when you have the current and latest versions shown, but it will allow an admin to quickly decide if an update is needed by looking for a particular color (a smaller cognitive load).

The reason I believe this should be on the sysadmin's view (and not in the view of a tenant's dashboard, as discussed in #83), is because it is the sysadmin who can act upon this information because they have the necessary access permissions to do something about those versions.
Showing this to the tenant is not giving them any useful information, as they cannot do anything with it (except maybe, nudge the admin to upgrade).

**Comment by SerhiiLutchenko** [comment]
In Professional Edition in White Labeling you can turn on "Show platform name and version" and it will show you the current version of the ThingsBoard. The latest versions of the ThingsBoard you can find here https://thingsboard.io/docs/reference/releases/
