### ISSUE TITLE
AWS PE version, 503 Service Unavailable

### ISSUE THREAD

**Issue by jcgtrace** [thingsboard/thingsboard#1843]
I have been unable to login to ThingsBoard PE for two days now, using same login. Is there something wrong on the AWS server or has my login chaged? I suspect my devices are also unable to send data.

**Comment by Karabiy** [comment]
Have an ssh access to the server of yours and have the ThingsBoard logs check
You can check those on the /var/log/thingsboard/thingsboard.log

**Comment by SergMeleshko** [comment]
Hello @jcgtrace 
Is the issue still relevant?
