### ISSUE TITLE
How to use "/api/devices" (findByQuery) correctly ? 

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1844]
Hi,
I am trying to use TB's swagger api. Here is my issue. I try to use "/api/devices" (findByQuery) to get devices information. 

According to the document, I have to pass the parameters 

_**{
"deviceTypes": [
"string"
],
"parameters": {
"rootId": "string",
"rootType": "TENANT",
"direction": "FROM",
"relationTypeGroup": "COMMON",
"maxLevel": 0
},
"relationType": "string"
}**_ . 

What is the rootId ? What is relationType ? 

Can anyone know how to pass the parameters correctly ? 

Regards,

Paul Wang

**Comment by tuanvayn** [comment]
Same issuse. But no solution in Google. so sad

**Comment by mircopz** [comment]
rootId and rootType are ID and Type of source entity you're looking relations with, while relationType is the relation type you specify during the creation of a relation (i.e. "Contains", "Manages"...).

**Comment by FazaGhassani** [comment]
I tried to fill the information and there result are always empty array with code 200.

here's my Json looks like:

{
  "deviceTypes": [
    "default"
  ],
  "parameters": {
    "rootId": *MY TENANT ID*,
    "rootType": "TENANT",
    "direction": "FROM",
    "relationTypeGroup": "COMMON",
    "maxLevel": 0
  },
  "relationType":"CONTAIN"
}

**Comment by paulwang55** [comment]
Hi,
Here is my configuration. It works correctly.

Here is the explanation for this JSON format.

For my case, I am looking for the devices controlled by gateway.

The rootId & rootType is my gateway's device id & device type.
    **"rootId": "94bb2e20-542c-11e9-b733-2990e1c2c17a",
    "rootType": "DEVICE"**

The **deviceTypes** is what I am looking for.

For my case, my relationship is "Created". It will be used by the parameter of **relationType**.

{
  "deviceTypes": [
    "CTSB"
  ],
  "parameters": {
    "rootId": "94bb2e20-542c-11e9-b733-2990e1c2c17a",
    "rootType": "DEVICE",
    "direction": "FROM",
    "relationTypeGroup": "COMMON",
    "maxLevel": 0
  },
  "relationType": "Created"
}

**Comment by WillNilges** [comment]
What kind of authorization do you need to do this? I get 401's as a Tenant Admin.

**Comment by WillNilges** [comment]
I also get 401's as a System Admin.

**Comment by sullamago** [comment]
尝试了好多次，可以查询出网关关联的设备，
{
  "parameters": {
    "rootId": "1dd7f430-44fe-11f1-bfe5-71b9c678f5ec",
    "rootType": "DEVICE",
    "direction": "FROM",
    "relationTypeGroup": "COMMON",
    "maxLevel": 0
  },
  "relationType": "Created",
  "deviceTypes": [
    "default"
  ]
}


参数解释
rootId：查询起始点的实体ID，填写网关ID (1dd7f430-44fe-11f1-bfe5-71b9c678f5ec)。

rootType：rootId 类型，指定为 "DEVICE"。 

direction：关系方向。要查询网关的子设备，使用 "FROM" 即可。

relationTypeGroup：可过滤指定组的关系，可设为 "COMMON"。

maxLevel：查询深度，查询网关的直接子设备设为 1。

fetchLastLevelOnly：设为 true 可简化返回结果。

relationType (必选)：关系类型过滤器。网关与设备间常见关系，必须要填写。如果查询网关创建的设备，填写Created

deviceTypes (必选)：设备类型过滤器，填写设备的类型。例如default


> 你好，这是我的配置。它运行正常。
> 
> 以下是该JSON格式的解释。
> 
> 就我而言，我是在寻找由网关控制的设备。
> 
> rootID 和 rootType 是我网关的设备 ID 和设备类型。 **“rootId”： “94bb2e20-542c-11e9-b733-2990e1c2c17a”， “rootType”： “DEVICE”**
> 
> 我就是在找 **deviceTypes**。
> 
> 就我而言，我的关系是“建立”的。它将被 **relationType** 的参数使用。
> 
> {“deviceTypes”： [ “CTSB” ]， “parameters”： { “rootId”： “94bb2e20-542c-11e9-b733-2990e1c2c17a”， “rootType”： “DEVICE”， “direction”： “FROM”， “relationTypeGroup”： “COMMON”， “maxLevel”： 0 }， “relationType”： “Created” }
