### ISSUE TITLE
/api/auth/login

### ISSUE THREAD

**Issue by Gerflet** [thingsboard/thingsboard#1845]
About/API/auth/login 
I'd like to add oauth certification to the thingsboard.Want to know where the  /api/auth/login interface is.

**Comment by qwyinxiang** [comment]
https://thingsboard.io/docs/reference/rest-api/

**Comment by Gerflet** [comment]
I want to know which directory is in the Java project

**Comment by 425804004** [comment]
Hello, Did you find the path  ‘/API/auth/login’

**Comment by Ultrazombie** [comment]
Hello @Gerflet ,
Is your problem still relevant?
