### ISSUE TITLE
Build v2.3.1 from sources on Raspberry3 B+ failed!

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1846]
I gitclone the source files of the thingsboard 2.3.1 on the Raspberry Pi Model3 B+.
Then I run the following command from the thingsboard folder to build the project:

mvn clean install -Dmaven.test.skip=true -Dcheckstyle.skip=true

It seems something went wrong.

Below is the error message:

[INFO] Thingsboard ........................................ SUCCESS [  1.450 s]
[INFO] Netty MQTT Client .................................. SUCCESS [ 10.457 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.026 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 23.789 s]
[INFO] Thingsboard Server Common Messages ................. FAILURE [  0.568 s]
[INFO] Thingsboard Server Queue components ................ SKIPPED
[INFO] Thingsboard Server Commons ......................... SKIPPED
[INFO] Thingsboard Server Common Transport components ..... SKIPPED
[INFO] Thingsboard MQTT Transport Common .................. SKIPPED
[INFO] Thingsboard HTTP Transport Common .................. SKIPPED
[INFO] Thingsboard CoAP Transport Common .................. SKIPPED
[INFO] Thingsboard Server DAO Layer ....................... SKIPPED
[INFO] Thingsboard Extensions ............................. SKIPPED
[INFO] Thingsboard Rule Engine API ........................ SKIPPED
[INFO] Thingsboard Rule Engine Components ................. SKIPPED
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport Service ................. SKIPPED
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.962 s
[INFO] Finished at: 2019-07-08T09:11:27Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project message: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:linux-arm_32:3.6.1
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.6.1 -Dclassifier=linux-arm_32 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.6.1 -Dclassifier=linux-arm_32 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]         1) org.thingsboard.common:message:jar:2.3.1
[ERROR]         2) com.google.protobuf:protoc:exe:linux-arm_32:3.6.1
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   org.thingsboard.common:message:jar:2.3.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   gdsnexus (http://192.168.200.69:8081/nexus/content/groups/public/, releases=true, snapshots=true)
[ERROR] 
[ERROR] -> [Help 1]

![image](https://user-images.githubusercontent.com/31084798/60798502-dc57e600-a1a3-11e9-881b-38e96cc8f600.png)

**Comment by Ultrazombie** [comment]
hello @qwyinxiang 
Is there a problem with this in the latest version of ThingsBoard?
