### ISSUE TITLE
I think thingsboard needs a video live streamming for monitoring.

### ISSUE THREAD

**Issue by dty717** [thingsboard/thingsboard#1849]
I recommend [Icecast](http://www.icecast.org), it's open source.

**Comment by m0o0** [comment]
tnx a lot @dty717 
Can I use this server to connect to iot chips such as esp8266 arduino ...used?

**Comment by dty717** [comment]
@m0o0 I used esp8266 arduino or stm32, but not for this server  for it lacks much library for http or tcp etc.
The repo [Arduino](https://github.com/iot-playground/Arduino) may have some help.
Icecast just need tcp port connect with stream format ogg.

**Comment by m0o0** [comment]
ok tnx a lo @dty717

**Comment by dty717** [comment]
@m0o0 more useful links. 
[Using the ESP8266 WiFi Module with Arduino Uno publishing to ThingSpeak](https://medium.com/@cgrant/using-the-esp8266-wifi-module-with-arduino-uno-publishing-to-thingspeak-99fc77122e82)
[ESP8266 ESP-1 TCP Connections via Arduino UNO](https://forum.arduino.cc/index.php?topic=446501.0)

**Comment by Ultrazombie** [comment]
If you want, you can explain the request in more detail, and I will create a feature request for our dev team. They will consider your request.
Btw, Wouldn't a regular I-frame work for this purpose?
