### ISSUE TITLE
Dashboard search usability

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#185]
This happens on **Thingsboard v1.2.3**

There are several issues with the way this currently works:

- there should be a search bar, and the search icon should be inside that field (in its current form, it takes a click on the search icon to show the search bar)
- once the search icon is clicked, the focus should be automatically switched to the input field (otherwise it takes an extra click) _(this becomes irrelevant if the first request is implemented)_
- the search itself doesn't work. In the demo below you can see an error that is shown: `PRIMARY KEY column "search_text" cannot be restricted as preceding column "customer_id" is not restricted`. In other cases there was no error, I simply saw an empty page of results
- after I go back - the list of dashboards is empty, I have to refresh the page to see them again

My first thought was that it doesn't do a substring search (like discussed in #143), but given that I couldn't really test it - I don't know if that's the case. From a usability perspective, substring searches are much better for people, because they place a lower cognitive load on their shoulders.

![thingsboard-search-issue](https://user-images.githubusercontent.com/295338/27630186-03844486-5bf5-11e7-9675-59a937fed09f.gif)

**Comment by spencerkuhl** [comment]
"No dashboards found". when clicking dashboards.  If I attempt to create a dashboard from the device, and 'open dashboard' it lets me view the dashboard, and I see telemetry coming in,   Upon clicking 'dashboards' again, I receive the error "PRIMARY KEY column "customer_id" cannot be restricted as preceding column "search_text" is not restricted"

**Comment by ikulikov** [comment]
As for release 1.3.0 the following items are implemented:
- Automatic focus on input after search clicked.
- Reset search filter when go back.

**Comment by ralienpp** [comment]
Great, I am looking forward to that. Now I understand why the list was empty - because the filter was still applied.


Why don't you want to have the search bar exposed right away, without requiring an extra-click? Do you need that space for something else?

**Comment by ssmaurya** [comment]
I see search functionality included in v1.3.0.
