### ISSUE TITLE
Setting the perimeter field in incoming telemetry thingsboard metadata

### ISSUE THREAD

**Issue by taahirk** [thingsboard/thingsboard#1850]
0

I have created a thingsboard customer which I have linked to several devices. I am able to receive a customer attribute through enrichment, in the rule chain, which contains a perimeter field, basically a string of latitude and longitude coordinates.

I have then got this to a field for the associated device in the metadata. I attempt to split this data according to thingsboard requirements for the perimeter value seen below, this is all done within the rule chain

[https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#fetch-perimeter-information-from-message-metadata](url)

I then attempt to populate the metadata perimeter field for the device with an array like required [[lat1, lng1], [lat2, lng2],.....[latN, lngN]], this is done within a script.

When I do this I receive the following error: Failed to unbind message data from javascript result

Is there anyway to set this perimeter field within the rule chain

**Comment by avigade** [comment]
Looking for the same functionality. Didn't find a single example on how the gps geofencing rule node works

**Comment by avigade** [comment]
Why is it that none of the devs or support has come for this guy's request.

**Comment by taahirk** [comment]
Hi,

I managed to get this working.

Setup a server attribute for your customer, with perimeter key and value sample being a string of GPS coordinates. E.g. below
-26.14526801412892,27.969832297063608,-26.14311063710062,28.107501762528052,-26.243540417648532,28.11093491628026,-26.24569593521752,27.98493817357343,

In the rule chain add in the customer attribute. 
For source I name it perimeter and for target perimeterValue.

Essentially we need to update the perimeter field similar to what is required
E.g. [[lat1, lng1], [lat2, lng2],.....[latN, lngN]]

To do this I used a script with the  following code.

`if (metadata.perimeterValue) {
     metadata.perimeter = processPerimeter(metadata.perimeterValue);
 }

function processPerimeter(perimeter) {
    var latArray = [];
    var lngArray = [];
    var perimeterArray = "[";
    
    var values = perimeter.split(',');
    
    for (var i = 0; i < values.length; i++) {
        if (values[i] !== '') {
            if (i % 2 === 0) {
                latArray.push(values[i]);
            } else {
                lngArray.push(values[i]);
            }
        }
    }
    
    if (latArray.length === lngArray.length) {
        for (var j = 0; j < latArray.length; j++) {
            var latLng = "[" + latArray[j] + "," + lngArray[j] + "]";
            perimeterArray += latLng;
            
            if (j !== (latArray.length - 1)) {
                perimeterArray += ",";
            }
        }
    }
    
    perimeterArray += "]";
    
    return perimeterArray;
}
`

The metadata now has the required perimeter field saved correctly.

In the geofence alert I have the fields populated as follows
latitude key name = latitude
longitude key name = longitude
Fetch perimeter information from message metadata is ticked

minimal inside duration 1 minute
minimal outside duration 10 minutes

Attache the output to an alarm and trigger when gps geofencing event left/outside occurs 

Hope this helps

**Comment by JasonFarque** [comment]
> 
> 
> Why is it that none of the devs or support has come for this guy's request.

Because ThingsBoard is great software with terrible support.

No forums on their site and the places that they point you to for communication with them are dead ends with people posting questions and very rarely are there answers from the devs.

**Comment by escalanterj** [comment]
Most probably because they do not have competition...

**Comment by escalanterj** [comment]
Does anybody know to configure a geofence alarm ? I get th error: org.thingsboard.rule.engine.api.TbNodeException: Missing perimeter definition!
