### ISSUE TITLE
Enrichment - originator telemetry = "Telemetry is not selected!"

### ISSUE THREAD

**Issue by jh83** [thingsboard/thingsboard#1851]
When using the "Enrichment - originator telemetry" i always get the "Telemetry is not selected!" error. 

In the rule node, it seems as if it wont save what i enter into "Latest timeseries" textbox. As soon as i save the settings and open it again, then its empty. After that the "Telemetry is not selected" error in the debug window.

How should one properly use this node? The documentation does not clarify if im missing something in my configuration.

**Comment by jcgtrace** [comment]
Did you find out how to solve this issue? I am having the same problems.

**Comment by jh83** [comment]
No. I did not solve it. No reaction from the tb team

**Comment by jcgtrace** [comment]
Pity, thanks for the reply. It seems there has been an update that has stopped it from working somehow. I really need to get delta telemetry values. Did you find another way around it?

**Comment by mp-loki** [comment]
When you type your telemetry name in the node configuration, make sure that you hit Enter when done typing. The telemetry should get a grey background and an 'X'  icon. If you don't hit entter, the telemetry is not saved.

**Comment by jcgtrace** [comment]
Thank you very much mp-loki, that makes a huge difference. I will remember that as I am sure it applies elsewhere as well.

**Comment by hemantkamalakar** [comment]
> When you type your telemetry name in the node configuration, make sure that you hit Enter when done typing. The telemetry should get a grey background and an 'X' icon. If you don't hit entter, the telemetry is not saved.

Saved my day.

**Comment by yanggeorge** [comment]
Thanks. Very helpful.

**Comment by yanggeorge** [comment]
> When you type your telemetry name in the node configuration, make sure that you hit Enter when done typing. The telemetry should get a grey background and an 'X' icon. If you don't hit entter, the telemetry is not saved.

Thanks. Very helpful.

**Comment by arianseyedi** [comment]
Question, I'm trying to put toghether a rule chain that decides whether incoming sensor data should trigger an alarm. But I need to access the past hour data to make a comparison. But my originator telemetry enrichment node does not seem to work. I wonder if the "Latest timeseries" entry has anything to do with it? I'm not sure what value to put there. Can someone help please? I tried "default" but it doesn't work.

![image](https://user-images.githubusercontent.com/25851455/89442098-3830cd80-d71c-11ea-8190-b37cbfe5e3e5.png)

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
