### ISSUE TITLE
HTTP Status 400 - Bad Request on Devices list

### ISSUE THREAD

**Issue by pineful** [thingsboard/thingsboard#1852]
Hello,

I found that the 400 error is occurred when we put "|" character on device name and get the list over a page.

It looks that it calls REST GET API for retreiving remaining devices but the designated device name has '|' so the error has occurred. If it was urlencoded to put '%7c' instead of '|', it will gonna be ok.

Please check about it for GET parameter issue of REST API.

![image](https://user-images.githubusercontent.com/17443589/60943564-5497e600-a321-11e9-902d-b2c2e6ddf4b7.png)

**Comment by developersnively** [comment]
Hi, I am facing the same error with referred Policy as no-referrer-when-downgrade. All my devices have [ and ] in their name.

Thank you
Dev

**Comment by ban2derlog** [comment]
Hi, is this issue persist on latest ThingsBoard version?
