### ISSUE TITLE
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

### ISSUE THREAD

**Issue by alperensener** [thingsboard/thingsboard#1854]
Hello,

What is the problem? How can i fix it?

![Screen Shot 2019-07-10 at 16 51 23](https://user-images.githubusercontent.com/50706366/60974708-3a670380-a333-11e9-9fcd-9b5d9631bd39.png)

could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by masterchen** [comment]
1st to make sure that yout database installed correct. 2nd close the anti-virus software to try.

**Comment by eeVoskos** [comment]
Make sure you run the upgrade script after installing 2.4.0:
```
$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.3.1 
```

It's all documented here:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-240

**Comment by Karabiy** [comment]
does the issue persists?

**Comment by Ben-Sassi-Oussema** [comment]
yes please help

**Comment by eykamp** [comment]
I encountered this error as well on a mature install of 2.4.3.  I intend to upgrade, just noting that the issue persists.

Is there any way to see which SQL statement the server is trying to execute?

**Comment by CooL16** [comment]
please provide us with thingsboard.log after getting this error so we can investigate your issue

**Comment by sagarganachari** [comment]
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

How to resolve this issue

**Comment by Milinda96** [comment]
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet] with root cause

I'm getting that same error. How to solve this issue? I'm getting this error when there is Mapping between two tables. (ManytoOne).

**Comment by asinghn** [comment]
Just an observation - I changed my hibernate entity class but missed to make change in db table's structure and got same exception:

```
2021-11-23 20:40:24,523 ERROR [com.pkg] - <Fail when load data in class com.pkg.Emp>
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:281) 
```

**Comment by melkhazen** [comment]
any updates on this issue?

**Comment by melkhazen** [comment]
@Karabiy  Thank you for replaying my issue was having the wrong table name in my code
@JoinTable(name = "**TBL_DRT_USER_ROLES**",  <==== this one
        joinColumns = {@JoinColumn(name = "USER_ID")},
        inverseJoinColumns = {@JoinColumn (name = "ROLE_ID")})
        
everything works fine now ill leave this here for anyone else :)

**Comment by smalik2043** [comment]
We are facing this same issue could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet . We are trying to run the upgrade script /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.1.1 but it always requires a password. Any hint what we need to do? Thank you

**Comment by RavikiranCh22** [comment]
..
