### ISSUE TITLE
Device claiming confirmation failed!

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1857]
hello.
I tried the latest thingsboard v2.4.0, and I have a few questions.
First, what is the use case of device claiming?
Second, how can I do to make device claiming success.
Below is my steps:
1) I use my tenant username and password to generate the X-authorization token. Is this tenant username or the customer username, I tried the two, both are not right.
2) I published a mqtt message to my thingsboard.
C:\Users\renlu>mosquitto_pub -h 192.168.200.129 -p 1884 -u AbfdgrRetGF45 -t v1/d
evices/me/claim -m "{\"secretKey\":\"a1b2c3D$\",\"durationMs\":\"600000\"}"

3) I make a HTTP POST request to confirm device claim.
my post url is:http://192.168.200.129:8080/api/customer/device/Device_1/claim
body is {
	"secretKey":"a1b2c3D$"
}
4) The response is 403.
{
    "status": 403,
    "message": "You don't have permission to perform this operation!",
    "errorCode": 20,
    "timestamp": "2019-07-12T02:10:50.044+0000"
}

I want to know Which step is wrong? And I saw the thingsboard.yml, the "allowClaimingByDefault" is true by default.
![image](https://user-images.githubusercontent.com/31084798/61097637-9e520f00-a48e-11e9-86d4-742fe736c9b3.png)

**Comment by FazaGhassani** [comment]
I also have trouble at confirming the request, my response code is 401

{
    "status": 401,
    "message": "Authentication failed",
    "errorCode": 10,
    "timestamp": "2019-07-15T06:25:24.363+0000"
}

**Comment by pong19021** [comment]
I same as you qwyinxiang .

**Comment by Collin01** [comment]
The process to claim new devices don't describe any username or token to send a message to thingsboard.

The MQTT-API describes that a access token of the device must be specified for authentication.
A new device does not have an access token?!
What should be stated here?
A teanant also has no access token.

I would expect to be able to access topic v1 / devices / me / claim without a token.

**Comment by cmegetpaid23** [comment]
[ Washed ] 
( Snowman's )[ $500 ]Pipeline's( Signature Hz shown above 
< /
Debited 
Cash@squared
@pong19021 
Cash@pong19021 ! - YNQ7YVKDS
- Ferrero 
WHOLESALE 
downloading Internet
_
20200202
_
172350 
_
20200628
_
135204
_1 ( 1200availabl )
$1200.Giftcards $1000availabl.png - - > > > > Èõkþhÿ èõkþhÿ )

**Comment by cmegetpaid23** [comment]
[Features and I will quote receiving a calm me when I was done today 👍 h pay for q in my account I will send you the money to pay for me with the money I would like to see the house to myself I would be interested in  my Sarah is coming to pick me up and I will send it done today Location's to me I will be able ww you have a good night at is the best way cool I will be able pressurizing oh I thought you were fuckn him to pay my account  but it is what I was done today 👍 hn 💵 v I have to check for q in a frçvcvxccvvg3rvvr4vvv for the money I would like to see the house wwwwwwwwwwwwwwwwwwwww wwwwwwwwwwwwwwwwwwwww wwwww 677Art﻿ VM Version: 2.1.0﻿ Java Home: /system﻿ Class  Path: .﻿ Boot Class Path: /system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system  /framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/ext.jar:/system/framework/framework.jar:/  system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/sprengine.jar:/system/framework/android.hidl.  base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/knoxsdk.jar:/system/framework/timakeystore.jar:/system/  framework/fipstimakeystore.jar:/system/framework/sec_edm.jar:/system/framework/knoxanalyticssdk.jar:/system/framework/smartbondingservice.jar:/system/framework/ucmopensslenginehelper.jar:/system/framework/esecomm.jar  :/system/framework/securetoThumbnail.jar:/system/framework/knoxguard.jar:/system/framework/drutils.jar check for q Requested the money for me to Hutchison restauration extracteurs v.]

**Comment by ban2derlog** [comment]
Hi, does the issue persist on latest ThingsBoard version?
