### ISSUE TITLE
I cannot set the option 'Automatic recovery' of rabbitMQ rule node.

### ISSUE THREAD

**Issue by pineful** [thingsboard/thingsboard#1858]
I checked the option 'Automatic recovery' on rabbitMQ rule node,
but everytime it was restored to unchecked.

![image](https://user-images.githubusercontent.com/17443589/61104762-770d3900-a4b2-11e9-8c57-45ef8f5cb8e9.png)

**Comment by pineful** [comment]
When the rabbitmq goes down for a while, it doesn't try reconnect at all!
I upgraded to 2.4.1 but it also has same problem.

**Comment by ban2derlog** [comment]
Hello, is it persisting on latest ThingsBoard version?
