### ISSUE TITLE
Dashboard timeseries duplicate entries (that contain no data points)

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#186]
Seen on **Thingsboard v1.2.3**

- When I edit a dashboard to add some entries to the timeseries, I see _duplicate entries_.
- Although they have identical names, one of them does not contain any values (you can see that in the demo below, when I toggle the elements in the legend).

Note that not all the entries are duplicated, but some are.

![thingsboard-dashboard-timeseries-duplicates](https://user-images.githubusercontent.com/295338/27631291-5014b044-5bf8-11e7-9927-17f608db9768.gif)

**Comment by ashvayka** [comment]
Maybe originally you have uploaded same key with different data formats?

**Comment by ikulikov** [comment]
Closing due to an inactivity.
