### ISSUE TITLE
Cannot click on the Edit data source icon with long label

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#1860]
When the label of a data source is too long, the edit icon icon is not visible
![imagen](https://user-images.githubusercontent.com/52624907/61108236-1239ea80-a482-11e9-82ec-5bb71153f8e9.png)

**Comment by IoTopenTech** [comment]
Unless you reduce the zoom
![imagen](https://user-images.githubusercontent.com/52624907/61108285-3695c700-a482-11e9-93a8-2a5720883c0e.png)

**Comment by Ultrazombie** [comment]
Fixed in the latest version of ThingsBoard
