### ISSUE TITLE
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1)

### ISSUE THREAD

**Issue by RamonCT** [thingsboard/thingsboard#1864]
Dear all,
I have tried to build thingsboard from sources and I have obtained the above error with the release-2.4 and 2.4.1. 

The configuration is:
- On premise: Ubuntu 16.04
- Java: openjdk version "1.8.0_212"
- Maven: Apache Maven 3.3.9

After cloning the repo, I have used the following command to build the sources:
`$ sudo mvn clean install -DskipTests`

The console output is: 
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Server UI 2.4.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ui ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ ui ---
[INFO] Installing node version v6.9.1
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/node/6.9.1/node-6.9.1-linux-x64.tar.gz into /home/ramon/Documents/GIT/thingsboard/ui/target/node/tmp
[INFO] Copying node binary from /home/ramon/Documents/GIT/thingsboard/ui/target/node/tmp/node-v6.9.1-linux-x64/bin/node to /home/ramon/Documents/GIT/thingsboard/ui/target/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 6.4.1
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/npm/6.4.1/npm-6.4.1.tar.gz into /home/ramon/Documents/GIT/thingsboard/ui/target/node/node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
[INFO] Running 'npm install' in /home/ramon/Documents/GIT/thingsboard/ui
[ERROR] npm ERR! Error while executing:
[ERROR] npm ERR! /usr/bin/git ls-remote -h -t git://github.com/fabiobiondi/angular-fullscreen.git
[ERROR] npm ERR! 
[ERROR] npm ERR! undefined
[ERROR] npm ERR! exited with error code: 128
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/ramon/.npm/_logs/2019-07-16T12_22_14_609Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [  2.004 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  4.327 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.164 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.984 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.765 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  1.311 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.079 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.327 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.379 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.630 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.026 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 10.939 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.132 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.091 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  7.271 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.065 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [  9.788 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  6.682 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  6.173 s]
[INFO] Thingsboard Server UI .............................. FAILURE [08:09 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:18 min
[INFO] Finished at: 2019-07-16T14:22:14+02:00
[INFO] Final Memory: 90M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui
`
I have seen closed issue #1335 is similar for release-2.2. For this reason, I tried:
> first, npm install -g
> npm install -g pkg
> then try the (directory thingsboard)sudo -s mvn clean install -DskipTests
> Use the following commands if you fail inside the thingsboard/ui directory:
> npm install -g
> npm install -g pkg
> then try the (directory thingsboard) sudo -s mvn clean install -DskipTests

However, npm install is giving permission denied. Could you help me?

Thank you in advance,
R.

**Comment by m0o0** [comment]
hello @RamonCT 
Please do all the steps at the root.
sudo mvn clean install -DskipTests

**Comment by lazermen** [comment]
check 
git --version

**Comment by pingsutw** [comment]
```
sudo dpkg --configure -a
sudo apt-get -f install
sudo apt-get full-upgrade
sudo apt-get autoremove
sudo apt-get clean
```
hope this command could help you :+1:
