### ISSUE TITLE
[Feature] Real-time warning display for the user interface, configurable within the Rule Engine

### ISSUE THREAD

**Issue by TheBakaRem** [thingsboard/thingsboard#1865]
Hello,
While using ThingsBoard's Rule Engine (I use the Professional Edition v2.3), I realised that when an action takes place, it looks like the user that started the action can't immediately see if an action was successful or not (using a small popup).

Let's take an example. I have an user that can move devices in a special group, which should at any point not contain more than 10 devices (specified in the group's attributes). If an 11th device is added, the rule engine immediately removes the device from the group.

Here is the proposition: I'd like the user to know in real-time what happened, using a configurable Action Node that can send back the warning in a small popup and also send back that same message as an API response, in the case the rule chain was called via ThingsBoard's API. So in this example, having it send the message *"You can't have more than 10 devices in this group"* and display it in a popup on the UI / in the API's response.

Right now, the only actions we can do to warn the user is Log (which logs into the thingsboard.log, inaccessible to users), and Alarm (and as far as I know alarms don't show in a small popup, but can only be seen in dashboards / entity parameters).

This warning action can potentially be useful in a number of scenarios, but mostly as a way to tell the user what happened for specific actions that have been done using the Rule Engine.

I hope you will take this idea into consideration. Thanks in advance!

**Comment by Ultrazombie** [comment]
Closed due to inactivity
