### ISSUE TITLE
ThingsBoard 2.4.0 Cannot choose static widget from Cards

### ISSUE THREAD

**Issue by frogconn** [thingsboard/thingsboard#1866]
ThingsBoard 2.4.0 Cannot choose static widget from Cards. We back to ThingsBoard 2.3.1 for testing this version  can choose this widget.

<img width="1280" alt="ThingsBoard | Dashboard 2562-07-16 23-29-56" src="https://user-images.githubusercontent.com/2070583/61312510-c04ae900-a822-11e9-819e-11954f033057.png">

System run by docker official image on tag thingsboard/tb-cassandra:2.4.0 (https://hub.docker.com/r/thingsboard/tb-cassandra)

**Comment by pgrisu** [comment]
PR #1901 will fix the issue
