### ISSUE TITLE
Feature request: filtering panel data based on selected items (devices/telemetry) in another panel (list, map etc.)

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#187]
With say 2.000 devices and 5 sensors / device, ie. 10.000 different telemetry values I would like to be able to have a single dashboard showing only the selected devices or sensors.

**Example 1:**
- One panel lists all the available devices for that customer
- There are timeseries panels showing temperature, humidity, pressure, angle, etc. 

By selecting (single or multi-select) some devices in the list, the timeseries panels show only the time series for the selected devices.

**Example 2:**
- A map shows all the available devices for that customer
- There are timeseries panels showing temperature, humidity, pressure, angle, etc.
- There are table panels showing the latest values (and date/timestamps)

By selecting (single or multi-select) some devices in map, the timeseries and table panels show only the data for the selected devices.

Currently the timeseries panels have the ability to select (using the legend) what telemetry value is shown or not, so there is some basic filtering available. If that could be extended using selections in other panels, the requested functionality could be implemented I guess.

It would make the dashboards more interactive for users trying to get some detailed data about a device/sensor.

**Comment by ikulikov** [comment]
Starting from the release 1.3.0 this can be achieved by using alias filters, widget actions and dashboard states.

**Comment by nmahale10** [comment]
> With say 2.000 devices and 5 sensors / device, ie. 10.000 different telemetry values I would like to be able to have a single dashboard showing only the selected devices or sensors.
> 
> **Example 1:**
> 
> * One panel lists all the available devices for that customer
> * There are timeseries panels showing temperature, humidity, pressure, angle, etc.
> 
> By selecting (single or multi-select) some devices in the list, the timeseries panels show only the time series for the selected devices.
> 
> **Example 2:**
> 
> * A map shows all the available devices for that customer
> * There are timeseries panels showing temperature, humidity, pressure, angle, etc.
> * There are table panels showing the latest values (and date/timestamps)
> 
> By selecting (single or multi-select) some devices in map, the timeseries and table panels show only the data for the selected devices.
> 
> Currently the timeseries panels have the ability to select (using the legend) what telemetry value is shown or not, so there is some basic filtering available. If that could be extended using selections in other panels, the requested functionality could be implemented I guess.
> 
> It would make the dashboards more interactive for users trying to get some detailed data about a device/sensor.

Any update on this.Have you got any solution.
