### ISSUE TITLE
ERROR: duplicate key value violates unique constraint "ts_kv_unq_key"

### ISSUE THREAD

**Issue by madper** [thingsboard/thingsboard#1870]
![Screenshot from 2019-07-19 15-06-48](https://user-images.githubusercontent.com/451815/61516147-e34de680-aa36-11e9-923f-758ccbbbe104.png)
Not sure how it happens. I'm using thingsboard CE 2.4

**Comment by ban2derlog** [comment]
Hi, is it still persist on latest version of ThingsBoard?
