### ISSUE TITLE
o.t.server.actors.tenant.TenantActor Unknown failure

### ISSUE THREAD

**Issue by madper** [thingsboard/thingsboard#1871]
Hey dear thingsboard team!
I found a lot of following NPE inside of thingsboard log.

![Screenshot from 2019-07-19 17-14-41](https://user-images.githubusercontent.com/451815/61524295-c4585000-aa48-11e9-9263-221656cf8911.png)

**Comment by ban2derlog** [comment]
Hello, does it persist on latest ThingsBoard version?
