### ISSUE TITLE
Docker error start error tb 2.4.0

### ISSUE THREAD

**Issue by yehudarav** [thingsboard/thingsboard#1873]
Hi,

I am using Ubuntu 18.04 , with docker 18.09.7 

When following the instruction on the docker installation page:
`docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data -v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb
`
 I get the errors: 

> Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

After trying to upgrade: 
`docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb upgrade-tb.sh`

I also get 

> Connection to localhost:5432 refused

I get similar errors with thingsboard/tb-postgres 

Should I have to  install the db seperately?
Any ideas?

**Comment by Backdraft007** [comment]
Hi,
I don't use the tb image. The error says, that there is no connection to postgres database. I don't know why this image use postgres. Or did you updrade from 2.3.1?
> thingsboard/tb - single instance of ThingsBoard with embedded HSQLDB database.
> Note: Not recommended for any evaluation or production usage and is used only for development purposes and automatic tests.

Is it your first install? Use tb-postgres instead.

**Comment by Backdraft007** [comment]
Maybe this help: https://github.com/thingsboard/thingsboard/issues/1875

**Comment by yehudarav** [comment]
Hi, 
I get the same error in 

> Hi,
> I don't use the tb image. The error says, that there is no connection to postgres database. I don't know why this image use postgres. Or did you updrade from 2.3.1?
> 
> > thingsboard/tb - single instance of ThingsBoard with embedded HSQLDB database.
> > Note: Not recommended for any evaluation or production usage and is used only for development purposes and automatic tests.
> 
> Is it your first install? Use tb-postgres instead.

Hi, 

I get the same error in the tb-postgres image. Should I install the postgres seperately?

**Comment by Backdraft007** [comment]
Is it a fresh install? Can you create a complete new docker-instance with tb-postgres?
I don't have much experience with docker. :)

**Comment by kevz93** [comment]
Please check if you have actually configured the image port parameter to match your Postgres port

**Comment by ZhangJiaBa** [comment]
I also get java.net.ConnectException: Connection refused, pg_ctl: directory "/data/db" is not a database cluster directory
