### ISSUE TITLE
HSQLDB for thingsboard 2.4?

### ISSUE THREAD

**Issue by AbCthings** [thingsboard/thingsboard#1875]
Is HSQLDB still supported in the new release 2.4?

If so, can I use the same configuration used for thingsboard 2.3.1 to make it work?

Thanks

**Comment by AbCthings** [comment]
I had the opportunity to try it myself, it works with the HSQLDB configuration used in 2.3.1. Just override the PostgreSQL configuration section in thingsboard.yml.

**Comment by hamburml** [comment]
@AbCthings What did you overwrite? I removed the PostgreSQL config and added the HSQLDB config from thingsboard.yml in 2.3.1. Doesn't work :(
