### ISSUE TITLE
Is telemetry data (and other data such as alarms/events) also published to the gateway?

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#188]
I read in the documentation that RPC and attributes are published to the Thingsboard gateway in order for other applications to listen to data (RPC/attributes) updates.

Thingsboard also supports outputting telemetry data to Kafka.

I can't find hower if Thingsboard can output telemetry data and for instance alarms and other events directly to MQTT so other applications can use this data!

**Comment by volodymyr-babak** [comment]
we have created MQTT plugin to able to publish data to MQTT topics
here is PR: 
https://github.com/thingsboard/thingsboard/pull/137

it's still not merged to the master, but will be available in next release that is going to happen this or next week.

meantime, if you'll need it urgently you can build from sources using that branch and use it now

**Comment by MarsWarrior** [comment]
That is great! Didn't notice this PR while browsing the git repository.

We will wait for the new release, as we also want to test the PostgreSQL database (assuming that PR is also part of the update).
