### ISSUE TITLE
Widget Library: Editor goes blank when changing tabs 

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#1881]
TB Professional on AWS EC2
Browser Chrome and Edge
Same issue as above, widget editor window goes gray, all text disappears.  Widget editor is unuseable.  Has anyone solved or addressed this issue?

_Originally posted by @edcline in https://github.com/thingsboard/thingsboard/issues/255#issuecomment-506569558_

**Comment by hassanhawilo** [comment]
How to reproduce the bug:
Click to Widget Libraries then try to change the tab from HTML to CSS or other tabs for Schema. Once change, the editor goes all grey.
I am using chrome Version 75.0.3770.142 (Official Build) (64-bit)
but it works fine on firefox version 68.0.1 (64-bit)

**Comment by ban2derlog** [comment]
Hi, is this issue persist on latest Chrome and ThingsBoard versions?
