### ISSUE TITLE
transformation node - duplicate to group

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#1889]
I need to change a server attribute of all the devices in a specific device group if one of the devices in that group changes its server attribute. 
I tried donig this by the help of the "duplicate to group" node but without success so far. Below a printscreen of my rulechain.
 
![rulechain_duplicate_to_group](https://user-images.githubusercontent.com/45274753/61995514-e4f85980-b089-11e9-8da9-4796f0ae5db8.JPG)

At the moment there are 2 devices in that device group, in the debugging mode I see that 3 messages are generated (see below), but all with the same originatorName. (The originatorname of the device that changed the server attribute)
Am I missing something or is this not the purpose of the choosen node? 
![Debugging_mode_duplicate_to_group](https://user-images.githubusercontent.com/45274753/61995599-ef672300-b08a-11e9-886f-623f2225e097.JPG)

**Comment by ffrexroy** [comment]
I don't know if its a bug with the "duplicate to group" node or not but when I had to solve a similar issue I used the enrichment node "origintator fields" after the duplicate and set id to originatorId. That worked fine in my case.

**Comment by ThomasBaumgartner** [comment]
Thanks a lot. 
Those two nodes ("duplicate to group" and "originator fields")  together do exactly what i was expecting from the "dublicate to group" node. Therfore I guess it was my bug and not the bug of the node.
