### ISSUE TITLE
issue with web-ui and js-executor docker 

### ISSUE THREAD

**Issue by vimalgupta** [thingsboard/thingsboard#1890]
Hi

I have built the docker images but while starting the web-ui and js-executor, they are crashing. on checking further in log it says "sh: 1: /usr/share/tb-web-ui/bin/tb-web-ui: not found" for web-ui and same for js-executor.

I have analysed more and found that while building the deb for these two there is no /usr/share/tb-web-ui/bin directory and similar for js-executor.
Please let me know how can i overcome this issue.

**Comment by affoltep** [comment]
@vimalgupta Same issue - Did you find the reason?

**Comment by miki-tnt** [comment]
same here, looking for a resolution

**Comment by ban2derlog** [comment]
Hi, please check latest ThingsBoard guide for Docker.
All images are built already and [pushed](https://hub.docker.com/u/thingsboard).
