### ISSUE TITLE
Getting error while upgrading from 2.3.1 to 2.4.0 'Error creating bean with name 'claimDevicesServiceImpl'

### ISSUE THREAD

**Issue by aruneshdutta** [thingsboard/thingsboard#1892]
While attempting an update from 2.3.1 to 2.4.0 getting error 'Error creating bean with name 'claimDevicesServiceImpl' , to mention had just selected option to keep the old yml file, and also in the thingsboard.conf file there is no database configuration settings(as is mentioned in fresh installation instructions here for postgresql just for reference) but present in old yml file .Attached is the error screenshot.
img link - https://i.ibb.co/KD60ghM/img.png

**Comment by gazdikm** [comment]
same here...

**Comment by aruneshdutta** [comment]
Resolved the issue issue needs using yml files.You ought to rename the current thingsboard.yml to any name that is suitable for you and next step isrenaming from thingsboard.yml.dpkg-new to thingsboard.yml.Please merge new and old files if it is necessary.  31.07.2019, 17:43, "Martin Gazdik" <notifications@github.com>:same here...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.  Regards,Arunesh Dutta

**Comment by gazdikm** [comment]
sounds cool... Resolved by completely reinstalling thingsboard with dropping old database. My old thingsboard instance was totally empty so it was no problem to do clean install for me.

**Comment by lalitjoshi86** [comment]
> Resolved the issue issue needs using yml files.You ought to rename the current thingsboard.yml to any name that is suitable for you and next step isrenaming from thingsboard.yml.dpkg-new to thingsboard.yml.Please merge new and old files if it is necessary.  31.07.2019, 17:43, "Martin Gazdik" <notifications@github.com>:same here...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.  Regards,Arunesh Dutta

Hi Arunesh, 

I am getting the same error, Can you please advice how you solved this?

**Comment by lalitjoshi86** [comment]
Followed the above workaround and able to upgrade it. Thanks

**Comment by sfvaleriano** [comment]
Hello,
I've same error. I use postgresql database and can not drop it.

This is error message:
Error creating bean with name 'claimDevicesServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'security.claim.allowClaimingByDefault' in value "${security.claim.allowClaimingByDefault}"

Thanks.
