### ISSUE TITLE
Can't add HTML Value Widget

### ISSUE THREAD

**Issue by SamueleCarboni** [thingsboard/thingsboard#1896]
Hello! I just installed thingsboard 2.4.0. When I try to add the HTML Value Widget by clicking on it, nothing happens. I also tried to export and import it in a custom bundle, but the same thing happens.

![image](https://user-images.githubusercontent.com/39309463/62124550-ccc34d00-b2ca-11e9-94b3-29d4919f7758.png)

**Comment by iceytea** [comment]
https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java#L114

![image](https://user-images.githubusercontent.com/40764591/62181216-212b0300-b385-11e9-933f-e39e3602c9fe.png)

**Comment by Backdraft007** [comment]
#1866 

Try to click really near the top of the widget.

**Comment by SamueleCarboni** [comment]
@Backdraft007 Still not working

**Comment by Backdraft007** [comment]
![widget](https://user-images.githubusercontent.com/8741669/62197118-91cf2100-b37f-11e9-9778-2e68302acf8b.jpg)
When I click at the red dot, the widget will be added.

**Comment by SamueleCarboni** [comment]
Ok, now it works. But still this is a workaround and not a solution for me... Thank you anyway @Backdraft007

**Comment by SamueleCarboni** [comment]
And what about the HTML value widget?

**Comment by Backdraft007** [comment]
That seems completly broken.

**Comment by pgrisu** [comment]
PR #1901 will fix the issue

**Comment by SamueleCarboni** [comment]
@pgrisu Ok, it seems it solves the issue, but how to upgrade from previous 2.4.0 without losing data? I'm using Postgres

**Comment by pgrisu** [comment]
DB contents aren't involved by PR #1901 changes. You don't need to run upgrade script. 
Just rebuild and reinstall TB package

**Comment by SamueleCarboni** [comment]
Got issue  #1893 when installing
