### ISSUE TITLE
Couldn't login into Thingsboard Server after few days of normal operation.

### ISSUE THREAD

**Issue by kp372** [thingsboard/thingsboard#190]
I couldn't login into my Thingsboard account, not even an admin account. Whenever I try to do so I get following message:
`All host(s) tried for query failed (no host was tried) `

![thingsboard error](https://user-images.githubusercontent.com/20114714/27713635-750a1c56-5ce1-11e7-8701-00ef53c42acd.JPG)

I have done this as well [Memory update for slow machines](https://thingsboard.io/docs/user-guide/install/linux/) and it worked for few days and I am back again here.

How can I resolve this issue.? Thanks

**Comment by MarsWarrior** [comment]
Have you checked disk or partition space?
You get this error too if the disk is full...

**Comment by ashvayka** [comment]
This is an issue with Cassandra DB. Please see corresponding DB logs.

**Comment by nmenoni** [comment]
We had the same problem running TB in a EC2 t2.micro (the TB AMI). Then we  uprgaded to t2.small (2G of RAM) and the problem went away for about a week but then it happended again. From that moment every morning we have to restart the services in order to use the system for the rest of the day. Someone commented that by upgrading to a t2.medium (4G of RAM) the problem disappears, but we have not tried it yet

**Comment by volodymyr-babak** [comment]
https://wiki.apache.org/cassandra/CassandraHardware

According to cassandra wiki 4GB is minimum for normal work
"In other words, the more memory, the better, with 4GB being the minimum we typically recommended in a virtualized environment (e.g., EC2 Large instances)"

**Comment by MarsWarrior** [comment]
TB and Cassandra take about 8GB on a server with 16GB RAM.

The PostgreSQL version will do much better In that area!

**Comment by ashvayka** [comment]
The PostgreSQL and HSQLDB version is now working fine in master. You can build from source. I will close this once we release v1.3

**Comment by kp372** [comment]
This issue seems to be went away in v1.3. So closing it
