### ISSUE TITLE
New Thingsboard UI using Angular 8

### ISSUE THREAD

**Issue by itea-dev** [thingsboard/thingsboard#1903]
Started a new project to create an alternative front-end app for Thingsboard using the latest Angular 8.

Like the idea? Give it a star to support the project.

Your contributions are welcome.

https://github.com/itea-dev/ng-thingsboard

![NgThingsboard](https://raw.githubusercontent.com/itea-dev/ng-thingsboard/master/login-page.png)

**Comment by cristianhumelnicu** [comment]
Hi could u post  more screen shoot from new front end?

THX!

**Comment by itea-dev** [comment]
@cristianhumelnicu It's still work in progress.

Today I pushed the sign up page.

![image](https://user-images.githubusercontent.com/53100338/62429299-5630b000-b70d-11e9-9dcc-9addb8bca455.png)

**Comment by cristianhumelnicu** [comment]
nice!

**Comment by ashvayka** [comment]
Hi @itea-dev . Thank you for sharing this. I would like to note that once @ikulikov is back from vacation, we plan to continue working on migration to Angular 8. So far, as an exercise, we have done the UI of License Server based on the latest Angular 7/8. There is a lot of "shared" elements we plan to reuse. Once we are ready to share the progress, I will update this issue with the link to a branch where we develop new UI. It will be part of ThingsBoard v3.0 we plan to release this year. 

We welcome you to contribute some items to ThingsBoard v3.0, once we share the "work in progress" branch.

**Comment by itea-dev** [comment]
@ashvayka You welcome. Thanks for sharing with us your plans for this year, that's great news for the Thingsboard community. A lot of users are going to love the upgrade to latest Angular just as we are.

I'll be glad to contribute to the WIP ui branch once it's public, meanwhile I will continue working on the NgThingsboard project.

You are welcome to take code from it if you find it useful, it's licensed under Apache License 2.0, just like Thingsboard.

**Comment by vortexalex** [comment]
Hi community! So @ashvayka is there any news about the new branch you mentioned? Is there  any official and up-to-date roadmap about new features, especially front-end  stuff? I think many people are curious and willing to contribute to this :)

**Comment by ban2derlog** [comment]
Hello.
From version  3.3.3 ThingsBoard migrated to Angular 12.
Please, update to latest version to use all features.

**Comment by itea-dev** [comment]
The NgThingsboard project was discontinued because Thingsboard migrated to Angular 12 and there is no point in duplicating efforts.
