### ISSUE TITLE
thingsboard: unrecognized service

### ISSUE THREAD

**Issue by dl747503664** [thingsboard/thingsboard#1904]
when i executor : sudo service thingsboard start
thingsboard: unrecognized service
I am use CentOS6.8 and Linux version 2.6.32-642.el6.x86_64 and jdk1.8.0.91
when i executor install.sh ,it tele me successly
Could i did not use CentOS6.8 ?
Please help me

**Comment by dl747503664** [comment]
I am use ThingsBoard 3.11.4

**Comment by seahandsome** [comment]
Hey, brother, how do you solve the "thingsboard: unrecognized service"?
