### ISSUE TITLE
Not all material icons get displayed successfully.

### ISSUE THREAD

**Issue by mhdatallah** [thingsboard/thingsboard#1911]
I am trying to display the following on a widget:

`<div ng-switch-when="active" ng-switch
            on="dataKeyData.data[0][1]" class="dataElement"
            fxLayoutAlign="space-around center">
            <md-icon ng-switch-when="true"
                ng-bind="'signal_cellular_4_bar'">
            </md-icon>
            <md-icon ng-switch-when="false"
                ng-bind="'signal_cellular_connected_no_internet_0_bar'">
            </md-icon>
        </div>`

However, only signal_cellular_4_bar is getting displayed. This issue has occurred with other md icons as well.

**Comment by mhdatallah** [comment]
![Screenshot from 2019-08-07 15-26-48](https://user-images.githubusercontent.com/29150302/62619440-da5e7f80-b927-11e9-8a59-018c642ff507.png)
![Screenshot from 2019-08-07 15-26-53](https://user-images.githubusercontent.com/29150302/62619447-dcc0d980-b927-11e9-90e5-e383daf549cb.png)

**Comment by Ultrazombie** [comment]
Are your problem still exist on the latest version of ThingsBoard?
