### ISSUE TITLE
data analytics using Apache Spark, Kafka and ThingsBoard

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1919]
Hi
I'm working on and testing data analytics, and I'm using the latest version of TB I've built with maven before. The question here is, to use Kafka in the RULE engine, I need to add Kafka plugins as mentioned in the instructions(https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/#step-1-kafka-plugin-configuration). And also the version TB version 1.4 should be used?

tnx

**Comment by m0o0** [comment]
@ashvayka please help me 
tnx

**Comment by Ultrazombie** [comment]
Please tell us if this is an actual problem.
And if so, describe it in more detail;
