### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#1920]
Hi
I have successfully run my Kafka and Spark on TB version 1.4 with startup data processing on my server.
But I have the following problem:

ERROR org.apache.velocity - ResourceManager : unable to find resource 'error.vm' in any resource loader.

WEB:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sun Aug 11 14:02:13 UTC 2019
There was an unexpected error (type=Not Found, status=404).
No message available

It should be noted that I tested most of the bug fixes and used several different npm versions but failed to fix the problem and repeatedly deleted and reinstalled the node _module file, but again the problem was not resolved. Please help. .
It should be noted that the same TB version 2.4 TB was successfully built and run and had no problems.

**Comment by m0o0** [comment]
please help @ashvayka @gmatheu 
log:
root@apache:/home/debian/thingsboard-1.4/ui# sudo npm run build

> thingsboard@2.4.0 build /home/debian/thingsboard-1.4/ui
> cross-env NODE_ENV=production webpack

Hash: ab1c956bdba5cdbb7525
Version: webpack 1.15.0
Time: 70414ms
   [0] multi main 40 bytes {1} [built]
    + 1691 hidden modules

**WARNING in ./~/ws/lib/BufferUtil.js**
Module not found: Error: Cannot resolve module 'bufferutil' in /home/debian/thingsboard-1.4/ui/node_modules/ws/lib
 @ ./~/ws/lib/BufferUtil.js 12:15-36

**WARNING in ./~/ws/lib/Validation.js**
Module not found: Error: Cannot resolve module 'utf-8-validate' in /home/debian/thingsboard-1.4/ui/node_modules/ws/lib
 @ ./~/ws/lib/Validation.js 12:16-41

**ERROR in ./src/app/widget/widget-editor.controller.js**

**/home/debian/thingsboard-1.4/ui/src/app/widget/widget-editor.controller.js
  23:8  error  Unable to resolve path to module 'ace-builds/src-min-noconflict/snippets/javascript'  import/no-unresolved
  24:8  error  Unable to resolve path to module 'ace-builds/src-min-noconflict/snippets/text'        import/no-unresolved
  25:8  error  Unable to resolve path to module 'ace-builds/src-min-noconflict/snippets/html'        import/no-unresolved
  26:8  error  Unable to resolve path to module 'ace-builds/src-min-noconflict/snippets/css'         import/no-unresolved
  27:8  error  Unable to resolve path to module 'ace-builds/src-min-noconflict/snippets/json'        import/no-unresolved

✖ 5 problems (5 errors, 0 warnings)


ERROR in ./src/app/widget/widget-editor.controller.js
Module not found: Error: Cannot resolve module 'ace-builds/src-min-noconflict/snippets/javascript' in /home/debian/thingsboard-1.4/ui/src/app/widget
 @ ./src/app/widget/widget-editor.controller.js 27:0-60

ERROR in ./src/app/widget/widget-editor.controller.js
Module not found: Error: Cannot resolve module 'ace-builds/src-min-noconflict/snippets/text' in /home/debian/thingsboard-1.4/ui/src/app/widget
 @ ./src/app/widget/widget-editor.controller.js 29:0-54

ERROR in ./src/app/widget/widget-editor.controller.js
Module not found: Error: Cannot resolve module 'ace-builds/src-min-noconflict/snippets/html' in /home/debian/thingsboard-1.4/ui/src/app/widget
 @ ./src/app/widget/widget-editor.controller.js 31:0-54

ERROR in ./src/app/widget/widget-editor.controller.js
Module not found: Error: Cannot resolve module 'ace-builds/src-min-noconflict/snippets/css' in /home/debian/thingsboard-1.4/ui/src/app/widget
 @ ./src/app/widget/widget-editor.controller.js 33:0-53

ERROR in ./src/app/widget/widget-editor.controller.js
Module not found: Error: Cannot resolve module 'ace-builds/src-min-noconflict/snippets/json' in /home/debian/thingsboard-1.4/ui/src/app/widget
 @ ./src/app/widget/widget-editor.controller.js 35:0-54**
Child html-webpack-plugin for "../index.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 50 hidden modules
Child extract-text-webpack-plugin:
        + 8 hidden modules
Child extract-text-webpack-plugin:
        + 6 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 5 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 6 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Comment by Ultrazombie** [comment]
Does not reproduce on the latest version of thingsboard.
Please try on the latest
