### ISSUE TITLE
Error when building Thingsboard UI from source in Ubuntu

### ISSUE THREAD

**Issue by techfriendly** [thingsboard/thingsboard#1923]
Hi,

I've been trying to build Thingsboard versions 2.2.0, 2.3.1 or 2.4.0 on Ubuntu 18.04 (also tested Debian or CentOS) but I get a failure when building Thingsboard Server UI. 

I saw in several posts that this is a common issue(even in early versions). I tried to test all potential solutions but nothing worked.

Does anybody knows what is failing and what the solution is?

Please take a look at the log below, but it is similar to others posted.

Thanks in advance!

> [INFO] -------------------------< org.thingsboard:ui >-------------------------
> [INFO] Building Thingsboard Server UI 2.2.0                             [20/32]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ui ---
> [INFO]
> [INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ ui ---
> [INFO] Installing node version v6.9.1
> [INFO] Unpacking /home/ubuntu/.m2/repository/com/github/eirslett/node/6.9.1/node-6.9.1-linux-x64.tar.gz into /home/ubuntu/thingsboard-2.2/ui/target/node/tmp
> [INFO] Copying node binary from /home/ubuntu/thingsboard-2.2/ui/target/node/tmp/node-v6.9.1-linux-x64/bin/node to /home/ubuntu/thingsboard-2.2/ui/target/node/node
> [INFO] Installed node locally.
> [INFO] Installing npm version 6.4.1
> [INFO] Unpacking /home/ubuntu/.m2/repository/com/github/eirslett/npm/6.4.1/npm-6.4.1.tar.gz into /home/ubuntu/thingsboard-2.2/ui/target/node/node_modules
> [INFO] Installed npm locally.
> [INFO]
> [INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
> [INFO] Running 'npm install' in /home/ubuntu/thingsboard-2.2/ui
> [INFO]
> [INFO] > node-sass@4.10.0 install /home/ubuntu/thingsboard-2.2/ui/node_modules/node-sass
> [INFO] > node scripts/install.js
> [INFO]
> [INFO] Cached binary found at /home/ubuntu/.npm/node-sass/4.10.0/linux-x64-48_binding.node
> [INFO]
> [INFO] > gifsicle@3.0.4 postinstall /home/ubuntu/thingsboard-2.2/ui/node_modules/gifsicle
> [INFO] > node lib/install.js
> [INFO]
> [ERROR]   ✔ gifsicle pre-build test passed successfully
> [INFO]
> [INFO] > jpegtran-bin@3.2.0 postinstall /home/ubuntu/thingsboard-2.2/ui/node_modules/jpegtran-bin
> [INFO] > node lib/install.js
> [INFO]
> [ERROR]   ✔ jpegtran pre-build test passed successfully
> [INFO]
> [INFO] > optipng-bin@3.1.4 postinstall /home/ubuntu/thingsboard-2.2/ui/node_modules/optipng-bin
> [INFO] > node lib/install.js
> [INFO]
> [ERROR]   ✔ optipng pre-build test passed successfully
> [INFO]
> [INFO] > pngquant-bin@4.0.0 postinstall /home/ubuntu/thingsboard-2.2/ui/node_modules/pngquant-bin
> [INFO] > node lib/install.js
> [INFO]
> [ERROR]   ⚠ The `/home/ubuntu/thingsboard-2.2/ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
> [ERROR]   ⚠ pngquant pre-build test failed
> [ERROR]   ℹ compiling from source
> [ERROR]   ✔ pngquant pre-build test passed successfully
> [ERROR]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
> [ERROR]     at Promise.all.then.arr (/home/ubuntu/thingsboard-2.2/ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
> [ERROR]     at process._tickCallback (internal/process/next_tick.js:103:7)
> [WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> [WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> [ERROR]
> [ERROR] npm ERR! code ELIFECYCLE
> [ERROR] npm ERR! errno 1
> [ERROR] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
> [ERROR] npm ERR! Exit status 1
> [ERROR] npm ERR!
> [ERROR] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
> [ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [ERROR]
> [ERROR] npm ERR! A complete log of this run can be found in:
> [ERROR] npm ERR!     /home/ubuntu/.npm/_logs/2019-08-12T21_33_19_792Z-debug.log
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for Thingsboard 2.2.0:
> [INFO]
> [INFO] Thingsboard ........................................ SUCCESS [  1.843 s]
> [INFO] Netty MQTT Client .................................. SUCCESS [  5.039 s]
> [INFO] Thingsboard Server Commons ......................... SUCCESS [  0.088 s]
> [INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.908 s]
> [INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.948 s]
> [INFO] Thingsboard Server Queue components ................ SUCCESS [  1.363 s]
> [INFO] Thingsboard Server Commons ......................... SUCCESS [  0.041 s]
> [INFO] Thingsboard Server Common Transport components ..... SUCCESS [  8.649 s]
> [INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.570 s]
> [INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.555 s]
> [INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.735 s]
> [INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 11.878 s]
> [INFO] Thingsboard Extensions ............................. SUCCESS [  0.058 s]
> [INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.847 s]
> [INFO] Thingsboard Rule Engine Components ................. SUCCESS [  5.882 s]
> [INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.044 s]
> [INFO] Thingsboard HTTP Transport Service ................. SUCCESS [  8.993 s]
> [INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  7.171 s]
> [INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  6.238 s]
> [INFO] Thingsboard Server UI .............................. FAILURE [01:07 min]
> [INFO] Thingsboard Server Tools ........................... SKIPPED
> [INFO] ThingsBoard Server Application ..................... SKIPPED
> [INFO] ThingsBoard Microservices .......................... SKIPPED
> [INFO] ThingsBoard Docker Images .......................... SKIPPED
> [INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
> [INFO] ThingsBoard Web UI Microservice .................... SKIPPED
> [INFO] ThingsBoard Node Microservice ...................... SKIPPED
> [INFO] ThingsBoard Transport Microservices ................ SKIPPED
> [INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard Black Box Tests ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  02:19 min
> [INFO] Finished at: 2019-08-12T21:33:19Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :ui

**Comment by m0o0** [comment]
please read #1335

**Comment by pgrisu** [comment]
Did you check regarding this error message?
[ERROR] ✖ Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by gpellejero** [comment]
> or: pngquant failed to build, m

Yes, I did, but building proceess still fails. 

I tried to install it but I get a message saying it is already installed.

**Comment by gpellejero** [comment]
> please read #1335

I tested some combinations of NODE and NPM versions even in different TB versions, but building still fails!

I do not know what else to do.

**Comment by gpellejero** [comment]
I want to build from source to test some new LOCALES (spanish regional languages) and a way to do some machine learning with OpenFaaS and R Server, but if I coulnd't even build the standard version...

**Comment by m0o0** [comment]
first, npm install -g
npm install -g pkg
then try the (directory thingsboard)sudo -s mvn clean install -DskipTests
Use the following commands if you fail inside the thingsboard/ui directory:
npm install -g
npm install -g pkg
then try the (directory thingsboard) sudo -s mvn clean install -DskipTests
By doing this, you do not have to change the npm version

**Comment by m0o0** [comment]
@pgrisu you need install package
apt-get install libpng-dev

**Comment by gpellejero** [comment]
HI!

I just discover what happened.

Since "git clone git@github.com:thingsboard/thingsboard.git" y was cloning "https://github.com/thingsboard/thingsboard", but what I really needed to clone is "https://github.com/thingsboard/thingsboard.git"

With this option it worked OK.

I will check this solution in an alternative new server and will be back with further information.

Regards

**Comment by gpellejero** [comment]
Hi all,

I finally checked required commands to build TB properly. I hope this helps other people with the same issue:

1.	sudo apt-get update
2.	sudo apt install openjdk-8-jdk
3.	sudo apt-get install libpng-dev
4.	sudo apt-get install maven
5.	sudo apt install nodejs
6.	sudo apt install npm
7.	git clone https://github.com/thingsboard/thingsboard.git
8.	cd thingsboard
9.	git checkout release-2.4
10.	sudo npm install -g pkg
11.	mvn clean install -DskipTests

On the other side, please be aware that I tested it in an UBUNTU 18,04 LTS AMI image of AWS on a t3a.medium machine (a t3a.small collapses... maybe due to having only 2Gb of RAM).

Thanks for your help

**Comment by zbxzxx** [comment]
os:ubuntu 16

the same as i 
1.i find i haved change the npm source , i use  https://registry.npm.taobao.org/
u can check your registry 
npm config get registry 
then i use commond 
npm config set registry https://registry.npmjs.org/
to change my registry to default registry
then i entey directry 
thingsboard/ui 
rm -rf node_modules/*/.git/
then it works.
wish help u

**Comment by ManhTK1911** [comment]
> Hi all,
> 
> I finally checked required commands to build TB properly. I hope this helps other people with the same issue:
> 
> 1. sudo apt-get update
> 2. sudo apt install openjdk-8-jdk
> 3. sudo apt-get install libpng-dev
> 4. sudo apt-get install maven
> 5. sudo apt install nodejs
> 6. sudo apt install npm
> 7. git clone https://github.com/thingsboard/thingsboard.git
> 8. cd thingsboard
> 9. git checkout release-2.4
> 10. sudo npm install -g pkg
> 11. mvn clean install -DskipTests
> 
> On the other side, please be aware that I tested it in an UBUNTU 18,04 LTS AMI image of AWS on a t3a.medium machine (a t3a.small collapses... maybe due to having only 2Gb of RAM).
> 
> Thanks for your help

hello, I used these commands but it reported an error. 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.4.3:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [01:03 min]
[INFO] Netty MQTT Client .................................. SUCCESS [01:54 min]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.098 s]
[INFO] Thingsboard Server Common Data ..................... FAILURE [01:55 min]
[INFO] Thingsboard Server Common Utils .................... SKIPPED
[INFO] Thingsboard Server Common Messages ................. SKIPPED
[INFO] Thingsboard Server Queue components ................ SKIPPED
....
[ERROR] Failed to execute goal on project data: Could not resolve dependencies for project org.thingsboard.common:data:jar:2.4.3: Failed to collect dependencies at com.datastax.cassandra:cassandra-driver-core:jar:3.6.0 -> com.github.jnr:jnr-ffi:jar:2.1.7 -> org.ow2.asm:asm:jar:5.0.3: Failed to read artifact descriptor for org.ow2.asm:asm:jar:5.0.3: Could not transfer artifact org.ow2.asm:asm:pom:5.0.3 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file: http://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :data

Do you know how to fix it ?

**Comment by MirkoUgoliniDev** [comment]
Hello all,

I got a simialr problem

![image](https://user-images.githubusercontent.com/12691549/79142865-852f1380-7dbc-11ea-92cb-11f3318dd5e9.png)

looking at the log
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-13T17_15_13_577Z-debug.log

I got:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'audit', 'fix' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose npm-session 17881255589b7c2d
5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
5 verbose stack     at Bluebird.all.spread (/usr/lib/node_modules/npm/lib/audit.js:164:19)
5 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:514:35)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
5 verbose stack     at PromiseArray._promiseFulfilled (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
5 verbose stack     at PromiseArray._iterate (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
5 verbose stack     at PromiseArray.init [as _init] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose cwd /home/mirko/thingsboard
7 verbose Linux 5.3.0-28-generic
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"
9 verbose node v10.20.1
10 verbose npm  v6.14.4
11 error code EAUDITNOPJSON
12 error audit No package.json found: Cannot audit a project without a package.json
13 verbose exit [ 1, true ]

**Comment by zacky131** [comment]
I had similar problem one Thingsboard 3.2.. I tried to match all dependencies version such as npm, nodejs, yarn,etc...still not getting good result. I also tried to modify pom.xml so they are match with my VM...
I give up...
Then I tried to build on windows....
it was perfect, no issue at all...
at the end...I take to .deb file generated from windows, to install it on my ubuntu 20.04 server....works like a charm :)
I hope later someone can find solution for ubuntu

**Comment by vcmorini** [comment]
Same problem here

**Comment by ban2derlog** [comment]
Hi, please use official DEB and RPM packages from [site](https://thingsboard.io/docs/user-guide/install/installation-options/).
