### ISSUE TITLE
How can use  "/api/tenant/devices{?type,textSearch,idOffset,textOffset,limit}" correctly?

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1924]
I created many devices on my thingsboard platform. And I don't know the exact number.
and I want to use the API "/api/tenant/devices{?type,textSearch,idOffset,textOffset,limit}" to get all devices's IDs. 
I set limit=100, then use GET http://192.168.200.129:8080/api/tenant/devices?limit=100 command,
the thingsboard returned 100 datas.and the return data's  "hasNext" is true, this means the thingsboard has more than 100 datas.
Next，How can I do to get the rest data?
And I don't understand the meaning of the "type", "textSearch", "idOffset", "textOffset".

**Comment by ashaforost** [comment]
Hi @qwyinxiang 

We've updated our API, now you can iterate through pages with the "page" parameter.
See the /api/tenant/devices{?page,pageSize,sortOrder,sortProperty,textSearch,type} request.
