### ISSUE TITLE
I need writeable attributes from both device and server

### ISSUE THREAD

**Issue by jong0210** [thingsboard/thingsboard#1925]
I have devices with properties that need to be updated by both the devices and the server. Currently, this doesn't seem to be possible with ThingsBoard because the server can't change the client attributes and the client can't change the shared attributes.

It would have been much easier if the client could have changed the shared attributes just like the server. And I see older issues here mentioning this but I think nothing has changed. See https://github.com/thingsboard/thingsboard/issues/148 .

Is anyone having the same issue and how did you solve it? Maybe the web itself can be customized to fix this or perhaps a solution already exists?

**Comment by Backdraft007** [comment]
The Client can change sharedKeys. I do it with mqtt.
https://thingsboard.io/docs/reference/mqtt-api/#publish-attribute-update-to-the-server

**Comment by jong0210** [comment]
Hi, how can you do that? That link only mentions changing the client side attributes.

If this isn't possible, perhaps there's a way to do this via the rule engine or RPC calls?

**Comment by Backdraft007** [comment]
Yes, sorry. I missunderstood your message. I think rule chain is the way, but I'm not so familar with it, right now.

**Comment by jong0210** [comment]
Ok, np.

So does anyone know if this is possible with a rule chain? Perhaps when a change of a device attribute comes in, a shared attribute with the same name can be changed via the rule chain? That way, the server and the device could both read and write "the same" attributes.

??

**Comment by jong0210** [comment]
I may have found the solution myself. It seems to be possible to do this with the "Save Attributes" action in the Rule Chains section.

**Comment by BulanDG** [comment]
Hi, did you solve it? what's the solution?

**Comment by jong0210** [comment]
I solved it with the "Save Attributes" action in the Rule Chains section. If you look at the Root rule chain which comes as default and attach your own rule chain to the end of the save attributes there, you can specify that when a client attribute changes, the corresponding shared attribute changes, too. And on the dashboard you only show the shared attributes, so there's no duplication.

**Comment by Ktysai** [comment]
@jong0210 can you give a little more details, please on how you've solve it!

I'm a newbie and that damn rule chain I've deleted  :((

Thanks in advance!

**Comment by Dewieinns** [comment]
@jong0210, as others have requested can you share a bit more information? 

I can see that I can set all Client Attributes as Shared Attributes but have yet to determine how to differentiate between them and do things accordingly. I don't mind having one Client Attribute duplicated to update one Shared but I do not want to duplicate them all.

**Comment by Kevin-Zh-CS** [comment]
thanks, it helped me a lot
