### ISSUE TITLE
Switch from Community to Professional Edition

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#1932]
Hello!

We have a running Thingsboard 2.4 Community Edition. We want to upgrade to the Thingsboard 2.4 Professional Edition. Can I simply install PE-deb files (https://thingsboard.io/docs/user-guide/install/pe/ubuntu/) and run `sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.0 `

If not, can I reuse the database or do I need to recreate all assets/users/tenants?

Thanks!

**Comment by hamburml** [comment]
I tried it - and it's not working. Inside the thingsboard.log there was always an Error that the License Client couldn't be created and that therefore the instance will shutdown.

I reinstalled the whole device and voila - it works.

Would really love to see a great upgrade mechanism.

**Comment by shanevanj** [comment]
Yes I have a production installation tha my I now want to convert to PE and license - but there is no obvious way to “cross grade”

**Comment by yalamber** [comment]
any update in 2020 for this? is it possible?

**Comment by Karabiy** [comment]
In order to have a migration from ThingsBoard Community Edition to ThingsBoard Professional Edition you may use an upgrade guide for the ThingsBoard Professional Edition. 
Refer to this link regarding an upgrade guide: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/
Make sure to proceed with a backup instruction mentioned in the guide too.

After an upgrade will be finished, you need to configure a license key of yours. Refer to this regarding on how to configure the license key: https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-3-obtain-and-configure-license-key

**Comment by hamburml** [comment]
As said, this didn't work.
Inside the thingsboard.log there was always an Error that the License Client couldn't be created and that therefore the instance will shutdown.

**Comment by Karabiy** [comment]
have you obtained the license key and inserted it properly? can you share the thingsboard.conf of yours ?

**Comment by hamburml** [comment]
As also said, I removed ThingsBoard and installed the PE.deb file. I can't share logs or the conf.

**Comment by csmus** [comment]
I have a code that is uploaded to ThingsBoard using Arduino uno with esp8266 WiFi sheild, I want to upload the same code using esp32, I tried to change on the linking to ThingsBoard setup in the code but its not working, I am new to the IoT..

**Comment by Karabiy** [comment]
> As also said, I removed ThingsBoard CE and installed the PE.deb file.
> _edit_
> There was no firewall or proxy settings the issue. This is not possible because after a full reinstall it worked (with new database, wasn't able to use the old). Yes, the license key was the correct one because it worked after a full reinstall (with the same key)...
> _edit_
> I don't know if the upgrade works with the current version. But in August, 2019, it wasn't.

can you specify the email of yours? Or can you contact Artur via email to proceed with the issue of yours artur@thingsboard.io?

**Comment by hamburml** [comment]
@Karabiy And for what? We have created a new database with a newly fresh installed ThingsBoard PE. I do not have the ThingsBoard CE anymore and don't have the time to set it up. Everything what was important is in this Issue.
