### ISSUE TITLE
Chinese and English mixed together

### ISSUE THREAD

**Issue by ChrisAuYeung** [thingsboard/thingsboard#1935]
![image](https://user-images.githubusercontent.com/25546288/63142374-23938b00-c01c-11e9-9277-9b7accddeec7.png)
 Installing ThingsBoard CE on Ubuntu Server,now I get a problem Chinese and English mixed together.

**Comment by Karabiy** [comment]
those has to be okay. have you done some modifications regarding the translation?

**Comment by ban2derlog** [comment]
Hi, please try to clear cache in your browser.
