### ISSUE TITLE
How to combine multiple widget to send one RPC

### ISSUE THREAD

**Issue by yamato2199** [thingsboard/thingsboard#1936]
I want to build a function that using a switch widget to globally control all the devices on or off and a knob widget to control all device percentage if switch widget is on, i try to use global variable in rule chain to achieve but thingsboard not allow to create global variable, is there any way to do this?

**Comment by SuneethaYamani** [comment]
even I have same requirement.any luck!

**Comment by myroslav-tb** [comment]
Hi @yamato2199, as I understand you need to send the RPC command to several devices simultaneously, you can use and modify the example from our documentation to send the request to many devices:  https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
