### ISSUE TITLE
Page not rendering properly (Clearing cache fixed this)

### ISSUE THREAD

**Issue by jodiemacns-enginuityinc** [thingsboard/thingsboard#1947]
On the Left is Firefox, in the middle is Chrome, and on the right is Chrome incognito mode.

After I cleared my cache, It started working properly.

I still have a browser open that is showing this with the cache not cleared.

<img width="863" alt="Screen Shot 2019-08-22 at 3 28 24 PM" src="https://user-images.githubusercontent.com/54071018/63541586-cd7b8780-c4f4-11e9-8e6c-ae96c5157dd2.png">

**Comment by jodiemacns-enginuityinc** [comment]
This occurred after I upgraded to the Professional edition. Maybe there were some files that were left in my cache from the Community edition that caused the issue.

**Comment by ban2derlog** [comment]
Hi, you need to close all tabs and only then clear all cache for ThingsBoard endpoint.
