### ISSUE TITLE
several polygons on the map

### ISSUE THREAD

**Issue by lazermen** [thingsboard/thingsboard#1948]
Can I create several polygons of different colors on the map at once?

**Comment by lazermen** [comment]
for example
```
[
  [[37, -109.05],[41, -109.03],[41, -102.05],[37, -102.04]], 
  [[27.29, -108.58],[30.71, -108.58],[30.71, -102.50],[27.29, -102.50]], 
  [[47.29, -108.58],[50.71, -108.58],[50.71, -102.50],[47.29, -102.50]] 
]
```

**Comment by emeautomation** [comment]
hi...did you find an answer on this? m trying to find this too

**Comment by viktorkho** [comment]
hi...we need this feature  to show maps like this one: https://almatysu.kz/wp-content/uploads/2019/03/51201-666x1024.jpg

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
