### ISSUE TITLE
how can push notification from things board to mobile application

### ISSUE THREAD

**Issue by harikrishna6050** [thingsboard/thingsboard#1950]
Hi....
how can push notifications from things board to mobile application

**Comment by cristianhumelnicu** [comment]
I think your mobile app should to connect to TB trough API ...

**Comment by harikrishna6050** [comment]
Ok thank you,

one question? how can find things board push notification requesting ID
please tell me

**Comment by laxmiprasannaBorigi** [comment]
@harikrishna6050  Did you get the solution.. I am having the same requirement . when ever device pushed the data it should send push notification  to mobile with data.. can you help me here if you have a solution..

**Comment by Philip2809** [comment]
I know this is a very old issue, but if you use a version before 3.6.3 you can implement your own firebase integration to send push notification but if you update to the latest thingsboard, there is built in mobile notifications

**Comment by Ultrazombie** [comment]
@Philip2809 right,
the latest version of ThingsBoard has this feature.
