### ISSUE TITLE
Change Originator is not working properly

### ISSUE THREAD

**Issue by smartecons** [thingsboard/thingsboard#1951]
I'm building a complex thermostatic control with 16 different thermostats that shall command one refrigeration pump.  I've already built the rulechain and the "OR" condition work properly, but when I change the originator sometimes work and sometimes not. 
In detail when I build the rule chain as new it works but when I reset the server, this part of rulechain stops working and no RPC command is sent to pump.
Thingsboard is loaded on Raspberry Pi3B.
Any help is welcome
![Screenshot(5)](https://user-images.githubusercontent.com/38994142/63639733-52060b80-c697-11e9-9f4b-09e87eb4a7c0.png)

**Comment by smartecons** [comment]
Update: I installed thingsboard on Ubuntu Server with 12 GB Ram but the situation is the same; I was wondering that it could be a memory or processor problem but it seems some other issue

**Comment by mircopz** [comment]
You should enable the Debug mode in each node (in the edit window), then in 'events' tab you can find where is the error (and its reason).

**Comment by smartecons** [comment]
> You should enable the Debug mode in each node (in the edit window), then in 'events' tab you can find where is the error (and its reason).

Debug is already enabled and no error is shown; only "OUT" state change from "SUCCESS" to "FAILURE" .
 The relation between devices is done with a dedicated one.

I repeat, when I make a fresh installation the chain is working, but when I reboot the server it stops working.
If it can help, I attach the complete rulechain
![Screenshot(5)](https://user-images.githubusercontent.com/38994142/64051015-09a88b00-cb7a-11e9-98cf-6dee6254d4ed.png)
![Screenshot(6)](https://user-images.githubusercontent.com/38994142/64051024-0d3c1200-cb7a-11e9-9891-ec59b9e3df0d.png)

**Comment by DiegoMartinezGlez** [comment]
I have the same problem, also in raspberry pi 3 and ubuntu (2gbRAM). I want to start debugging it tomorrow morning.

**Comment by DiegoMartinezGlez** [comment]
I can't find a pattern to force the situation. Sometimes it happens after Ubuntu reboot, sometimes when editing rules ... It seems totally random. I will keep debugging it.

**Comment by DiegoMartinezGlez** [comment]
I have put logs boxes on each rule transition. Yesterday night rule stopped working. In thingsboard.log there is no error, no warning ... nothing. It just stopped writting the logs I added to the rule on each transition. This time it wasn't Change Originator box, it was Check Existing Fields. On Check Existing Fields output, I have logs for each result (True, False, Failure) but nothing appears in thingsboard.log. After reseting thingsboard service, it started to work fine again. 

I don't know how to make it crash, and I cant asure how to fix it (restarting services does not always work).

Next test I want to do is upgrade to v2.4 and behold behaviour.

**Comment by Bliph** [comment]
Don't know it it helps, but i noticed that putting 'var' in front of variable declarations/definitions helps. It seems that TB re-uses the varibales and they _may_ contain garbage values or cross-over values from other messages.

Note: I'm not the biggest javascript-fan...

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
