### ISSUE TITLE
Build failed Ubuntu 18.04

### ISSUE THREAD

**Issue by raghav-kopalle** [thingsboard/thingsboard#1952]
Trying to build from source on ubuntu server 18.04, everytime build fails at "Thingsboard Server UI"
Tried all the suggestions given by different users. Also tried both 2.4 & 2.3, end up getting the same error.
Can someone please help. Thanks in advance. 
--
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.949 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [01:49 min]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.060 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [01:03 min]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 11.564 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 10.026 s]
[INFO] Thingsboard Server UI .............................. FAILURE [01:23 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:50 min
[INFO] Finished at: 2019-08-24T18:36:36Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]                                                   
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui
--

 at ChildProcess.exithandler (child_process.js:206:12)
[ERROR]     at emitTwo (events.js:106:13)
[ERROR]     at ChildProcess.emit (events.js:191:7)
[ERROR]     at maybeClose (internal/child_process.js:877:16)
[ERROR]     at Socket.<anonymous> (internal/child_process.js:334:11)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at Socket.emit (events.js:188:7)
[ERROR]     at Pipe._handle.close [as _onclose] (net.js:498:12)
[ERROR] Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b 0.9-work git://github.com/thingsboard/flot.git /root/.npm/_cacache/tmp/git-clone-1510d5e6
[ERROR] fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1510d5e6': Permission denied
[ERROR] 
[ERROR]     at ChildProcess.exithandler (child_process.js:206:12)
[ERROR]     at emitTwo (events.js:106:13)
[ERROR]     at ChildProcess.emit (events.js:191:7)
[ERROR]     at maybeClose (internal/child_process.js:877:16)
[ERROR]     at Socket.<anonymous> (internal/child_process.js:334:11)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at Socket.emit (events.js:188:7)
[ERROR]     at Pipe._handle.close [as _onclose] (net.js:498:12)
[ERROR] Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/fabiobiondi/angular-fullscreen.git /root/.npm/_cacache/tmp/git-clone-2cde9f6e
[ERROR] fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-2cde9f6e': Permission denied
[ERROR] 
[ERROR]     at ChildProcess.exithandler (child_process.js:206:12)
[ERROR]     at emitTwo (events.js:106:13)
[ERROR]     at ChildProcess.emit (events.js:191:7)
[ERROR]     at maybeClose (internal/child_process.js:877:16)
[ERROR]     at Socket.<anonymous> (internal/child_process.js:334:11)
[ERROR]     at emitOne (events.js:96:13)
[ERROR]     at Socket.emit (events.js:188:7)
[ERROR]     at Pipe._handle.close [as _onclose] (net.js:498:12)
--

When trying to "mvn clean install -P npm-start" in the ui folder

[INFO] Running 'npm install' in /home/ss/thingsboard/ui
[ERROR] npm ERR! path /home/ss/thingsboard/ui/node_modules/mdPickers
[ERROR] npm ERR! code EISGIT
[ERROR] npm ERR! git /home/ss/thingsboard/ui/node_modules/mdPickers: Appears to be a git repo or submodule.
[ERROR] npm ERR! git     /home/ss/thingsboard/ui/node_modules/mdPickers
[ERROR] npm ERR! git Refusing to remove it. Update manually,
[ERROR] npm ERR! git or move it out of the way first.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /root/.npm/_logs/2019-08-24T19_28_53_382Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.808 s
[INFO] Finished at: 2019-08-24T19:28:53Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by bigdolphin** [comment]
You can test these steps. I used it on my server which is also ubuntu 18.04:
cd
sudo rm -r .m2
sudo rm -r .maven
#Install maven 3.6.1
wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
unzip apache-maven-3.6.1-bin.zip
sudo mv apache-maven-3.6.1 /opt/maven
sudo nano /etc/profile.d/mavenenv.sh
#add the 2 lines below into mavenenv.sh
export M2_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}

sudo chmod +x /etc/profile.d/mavenenv.sh
source /etc/profile.d/mavenenv.sh
#Check version to ensure you installed 3.6.1
mvn --version
#Install nodejs and other things
sudo apt install nodejs nodejs-dev node-gyp libssl1.0-dev -y
sudo apt install npm -y
sudo apt install openjdk-8-jdk
#Change java to jdk8
sudo update-alternatives --config java
#Check java version
java -version
**#Very important: ensure JAVA_HOME is pointed to jdk8**
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#Clone 2.4 release
git clone -b release-2.4 --single-branch https://github.com/thingsboard/thingsboard.git
cd thingsboard
git checkout -b release-2.4
sudo git clean -fdx
mvn clean install -DskipTests
sudo dpkg -i application/target/thingsboard.deb

The next steps (database, demo, start) as in thingsboard document.
Hope this help you.

**Comment by shoshin86** [comment]
> You can test these steps. I used it on my server which is also ubuntu 18.04:
> cd
> sudo rm -r .m2
> sudo rm -r .maven
> #Install maven 3.6.1
> wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
> unzip apache-maven-3.6.1-bin.zip
> sudo mv apache-maven-3.6.1 /opt/maven
> sudo nano /etc/profile.d/mavenenv.sh
> #add the 2 lines below into mavenenv.sh
> export M2_HOME=/opt/maven
> export PATH=${M2_HOME}/bin:${PATH}
> 
> sudo chmod +x /etc/profile.d/mavenenv.sh
> source /etc/profile.d/mavenenv.sh
> #Check version to ensure you installed 3.6.1
> mvn --version
> #Install nodejs and other things
> sudo apt install nodejs nodejs-dev node-gyp libssl1.0-dev -y
> sudo apt install npm -y
> sudo apt install openjdk-8-jdk
> #Change java to jdk8
> sudo update-alternatives --config java
> #Check java version
> java -version
> **#Very important: ensure JAVA_HOME is pointed to jdk8**
> export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
> #Clone 2.4 release
> git clone -b release-2.4 --single-branch https://github.com/thingsboard/thingsboard.git
> cd thingsboard
> git checkout -b release-2.4
> sudo git clean -fdx
> mvn clean install -DskipTests
> sudo dpkg -i application/target/thingsboard.deb
> 
> The next steps (database, demo, start) as in thingsboard document.
> Hope this help you.

Thanks for the help @bigdolphin will give it a try and update here!

**Comment by jones53** [comment]
> ## Trying to build from source on ubuntu server 18.04, everytime build fails at "Thingsboard Server UI"
> Tried all the suggestions given by different users. Also tried both 2.4 & 2.3, end up getting the same error.
> Can someone please help. Thanks in advance.
> ## [INFO] Thingsboard Rule Engine API ........................ SUCCESS [ 1.949 s]
> [INFO] Thingsboard Rule Engine Components ................. SUCCESS [01:49 min]
> [INFO] Thingsboard Server Transport Modules ............... SUCCESS [ 0.060 s]
> [INFO] Thingsboard HTTP Transport Service ................. SUCCESS [01:03 min]
> [INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 11.564 s]
> [INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 10.026 s]
> [INFO] Thingsboard Server UI .............................. FAILURE [01:23 min]
> [INFO] Thingsboard Server Tools ........................... SKIPPED
> [INFO] ThingsBoard Server Application ..................... SKIPPED
> [INFO] ThingsBoard Microservices .......................... SKIPPED
> [INFO] ThingsBoard Docker Images .......................... SKIPPED
> [INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
> [INFO] ThingsBoard Web UI Microservice .................... SKIPPED
> [INFO] ThingsBoard Node Microservice ...................... SKIPPED
> [INFO] ThingsBoard Transport Microservices ................ SKIPPED
> [INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
> [INFO] ThingsBoard Black Box Tests ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 11:50 min
> [INFO] Finished at: 2019-08-24T18:36:36Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :ui
> ## at ChildProcess.exithandler (child_process.js:206:12)
> [ERROR] at emitTwo (events.js:106:13)
> [ERROR] at ChildProcess.emit (events.js:191:7)
> [ERROR] at maybeClose (internal/child_process.js:877:16)
> [ERROR] at Socket. (internal/child_process.js:334:11)
> [ERROR] at emitOne (events.js:96:13)
> [ERROR] at Socket.emit (events.js:188:7)
> [ERROR] at Pipe._handle.close [as _onclose] (net.js:498:12)
> [ERROR] Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b 0.9-work git://github.com/thingsboard/flot.git /root/.npm/_cacache/tmp/git-clone-1510d5e6
> [ERROR] fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1510d5e6': Permission denied
> [ERROR]
> [ERROR] at ChildProcess.exithandler (child_process.js:206:12)
> [ERROR] at emitTwo (events.js:106:13)
> [ERROR] at ChildProcess.emit (events.js:191:7)
> [ERROR] at maybeClose (internal/child_process.js:877:16)
> [ERROR] at Socket. (internal/child_process.js:334:11)
> [ERROR] at emitOne (events.js:96:13)
> [ERROR] at Socket.emit (events.js:188:7)
> [ERROR] at Pipe._handle.close [as _onclose] (net.js:498:12)
> [ERROR] Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/fabiobiondi/angular-fullscreen.git /root/.npm/_cacache/tmp/git-clone-2cde9f6e
> [ERROR] fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-2cde9f6e': Permission denied
> [ERROR]
> [ERROR] at ChildProcess.exithandler (child_process.js:206:12)
> [ERROR] at emitTwo (events.js:106:13)
> [ERROR] at ChildProcess.emit (events.js:191:7)
> [ERROR] at maybeClose (internal/child_process.js:877:16)
> [ERROR] at Socket. (internal/child_process.js:334:11)
> [ERROR] at emitOne (events.js:96:13)
> [ERROR] at Socket.emit (events.js:188:7)
> [ERROR] at Pipe._handle.close [as _onclose] (net.js:498:12)
> When trying to "mvn clean install -P npm-start" in the ui folder
> 
> [INFO] Running 'npm install' in /home/ss/thingsboard/ui
> [ERROR] npm ERR! path /home/ss/thingsboard/ui/node_modules/mdPickers
> [ERROR] npm ERR! code EISGIT
> [ERROR] npm ERR! git /home/ss/thingsboard/ui/node_modules/mdPickers: Appears to be a git repo or submodule.
> [ERROR] npm ERR! git /home/ss/thingsboard/ui/node_modules/mdPickers
> [ERROR] npm ERR! git Refusing to remove it. Update manually,
> [ERROR] npm ERR! git or move it out of the way first.
> [ERROR]
> [ERROR] npm ERR! A complete log of this run can be found in:
> [ERROR] npm ERR! /root/.npm/_logs/2019-08-24T19_28_53_382Z-debug.log
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 39.808 s
> [INFO] Finished at: 2019-08-24T19:28:53Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
![image](https://user-images.githubusercontent.com/23331091/71304917-cfece000-2407-11ea-869b-7ad8ee1f4872.png)

you shoud go to /home/ss/thingsboard/ui/node_modules/mdPickers
and find the folder contains .git folder, remove it

**Comment by zacky131** [comment]
had similar issue on TB version 3.2 ..at the end I built with [windows](https://github.com/thingsboard/thingsboard/issues/1923#issuecomment-751685187), later installed the .deb file for my ubuntu 20.04 server

**Comment by vcmorini** [comment]
Same problem here

**Comment by ban2derlog** [comment]
Hi, please use official DEB and RPM packages from [site](https://thingsboard.io/docs/user-guide/install/installation-options/).
