### ISSUE TITLE
Navigate other dashboard state not work

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1953]
Hi!

I use the thingsboard 2.4.0, and I use the follow code to navigate other dashboard state, but it does not work. Could you help me? What do I do wrong?

var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice (entityId.id).then(function(device) {

      if (device.name == 'thermostat1') {                    

          openDashboardState ('Thermostat1');

      } else if (device.name == 'thermostat2') {

          openDashboardState('Thermostat2');

      } else if (device.name == 'thermostat3') {

          openDashboardState('Thermostat3');

      }

});

function openDashboardState(stateId) {

    var params = {
        entityId: entityId,
        entityName: entityName
    };

    Widgetcontext.statecontroller.openState(stateId, params, false);
}

**Comment by mircopz** [comment]
Hi

openDashboardState should be a function like this

```javascript
function openDashboardState(stateId) {
    var descriptor = {
        type: 'openDashboardState',
        setEntityId: true,
        targetDashboardStateId: stateId
    }

    widgetContext.actionsApi.handleWidgetAction($event, descriptor, entityId, entityName);
}
```
