### ISSUE TITLE
'Get back to previous state' widget

### ISSUE THREAD

**Issue by Squarelead** [thingsboard/thingsboard#1955]
Hello there!
I need to add simple 'get back' arrow widget that gets me to previous state. But all of the actions gets forward (to new state or new dashboard) and adding and adding new states. The only way to get back is to click to needed state on top. Maybe I should try any custom action? Thanks in advance.

**Comment by mircopz** [comment]
Hi
I add a new action type to go back to previous state. You can find it in this pull request #1966: you can merge it by your own or you can wait its approval.

**Comment by Squarelead** [comment]
Thanks man, It'll be very useful :)
