### ISSUE TITLE
AJAX resources on local Thingboard server

### ISSUE THREAD

**Issue by maxsenft** [thingsboard/thingsboard#1957]
We're currently using Thingsboard and, for example, the Chart.js widgets on the dashboards. The Chart.js AJAX resources are currently loaded directly from Chart.js' Cloudflare distribution. This is working fine as long as the device accessing the (locally running) dashboard has access to the internet. Unfortunately this is not always possible, so I was wondering if there is an official way where to put resources as part of the Thingsboard installation.

Alternatively, I could setup an extra webserver on the same server which only provides these type of special resources, but I would prefer to avoid that.

I could not find any hint in any configuration file or the documentation of Thingsboard itself, so I hope for any advice!

**Comment by revobd** [comment]
I also have the same question. It would be really appreciated if some one can point to a solution.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
