### ISSUE TITLE
How to use related attribute to get asset attribute contain devices

### ISSUE THREAD

**Issue by yamato2199** [thingsboard/thingsboard#1958]
I have a strature like building(asset)->level(asset)->group(asset)->device, when i am using the related attribute node in rulechain, i cant get any attribute from level and building that the device is belongs to. Is there any way to get the attribute from higher hierarchy

**Comment by yamato2199** [comment]
I can get from 1 level high hierarchy, and i can't get attribute from higher level hierarchy

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
