### ISSUE TITLE
Have Users from User Groups only see Devices that they Manage

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#1961]
Is it possible to have users from a User Group see and interact only with Devices that he has the "Manages" relation to?

For ex. I need Managers of Assets A and B be able to pass devices from A to B and vice-versa. But Managers that only manage A, cannot grab, see or change Devices from B.

**Comment by Ultrazombie** [comment]
Please read the article's about RBAC and user hierarchy https://thingsboard.io
