### ISSUE TITLE
how to put js resource on thingsboard server and load it from web widget?

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#1963]
My tb server should be installed in a lan network, so can not fetch the js resources from cloud.
So i want to place the js code in some folder of tb server, and load it on tb web widget. 
Can i do it this way? If true, where to place it?

**Comment by lincoln310** [comment]
like #1777 。
but tb is a web server, so it should provide file service, so can we just put resources under the fold of the service, then retrieve it using url?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
