### ISSUE TITLE
How to use the gatling cluster to test the performance of the thingsboard？

### ISSUE THREAD

**Issue by blackstar-baba** [thingsboard/thingsboard#1967]
I reviewed the thingsboard performance testing process here：https://thingsboard.io/docs/reference/performance/
The title "Horizontal scaling" has such a paragraph: "launch gatling stress test tool from two separate c4.xlarge instances simultaneous to minimize the possible affect on latency and throughput by thirdparty."
How did you get the two gatling test machines running at the same time and merge the results into one report?
Looking forward to your reply, thanks！

**Comment by Ultrazombie** [comment]
We have a new article about performance testing. You can read it here:
https://thingsboard.io/docs/reference/performance-aws-instances/
