### ISSUE TITLE
JavaScript Executor Microservice

### ISSUE THREAD

**Issue by FeiYanWu** [thingsboard/thingsboard#1973]

**Comment by javahook** [comment]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project js-executor: Failed to run task: 'npm install' failed. (error code 2) -> [Help 1]

**Comment by Karabiy** [comment]
does the issue persists for the current version?

**Comment by ban2derlog** [comment]
Hi, please use latest JS executor versions.
Now it stores in Docker Hub:
`thingsboard/tb-pe-js-executor:3.3.4.1PE`
