### ISSUE TITLE
how to subscribe data from mosquitto with tb gateway?

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#1979]
I use thingsboard gateway connected tb and mosquitto. Now i can send data to mosquitto and after the mapping on tb gateway, it can be show on tb.

But i want to know the attribute change date on tb from mosquitto. How to do it? What is the topic to subscribe?

In demo, tb use v1/devices/... as topic, and tb gateway use senser/+/attribute as topic, i am confused about this.

**Comment by Ultrazombie** [comment]
Please use the issue on the thingsboard gateway page for gateway questions.
https://github.com/thingsboard/thingsboard-gateway/issues
