### ISSUE TITLE
Email on alarm, demo account

### ISSUE THREAD

**Issue by ChristosPalisidis** [thingsboard/thingsboard#1980]
Hello everyone,
I would like to send an email an alarm event. I folowed the relevant tutorial, although it seems that i miss something ,as the email is not being sent. Can anyone help me out?
Thank you!

**Comment by shanevanj** [comment]
what have you code - post your rules so far

**Comment by ChristosPalisidis** [comment]
I created the "create and clear Alarm" rule chain and i also modified the main rule chain as shown in thingsboard tutorials :
`https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email/`
I think the problem is at the SMTP part. Any ideas for a demo account situation?

**Comment by shanevanj** [comment]
My understanding is the demo account limits email - you should setup your own server with your email provider in the SMTP configuration (not accessible in the demo account)

**Comment by dapengqi** [comment]
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email/
thanks

**Comment by Karabiy** [comment]
the thingsboard demo does not provide an option to test the mails. You can have an on-premise installation for those reasons and then configure the emails on its side.
you can refer to this link regarding the ThingsBoard installation options: https://thingsboard.io/docs/installation/
and for this link regarding the mail settings: https://thingsboard.io/docs/user-guide/ui/mail-settings/
