### ISSUE TITLE
I need to set a rule chain to trigger when dashboard is loaded or alterated

### ISSUE THREAD

**Issue by Nathan-ma** [thingsboard/thingsboard#1983]
Hello guys, I'm new using ThingsBoard, hopefully i'm making this request on the right place and please if there is a community forum or tutorial just send me the link and I will be more than helpful.

Ok here we go:
I wanna use the LED indicator feature on the dash board to trigger a RPC call to my device so it can get all the shared attributes properly.
All is done an works well on the Switch controller widget, problem is, I don't wanna use a switch. I do understand LED indicator reads a attribute from the server and that's fine. now I need help making a Rule chain to be triggered when I access dashboard or I don't know refresh it so I can call a RPC, my function will respond with a true or false value and I will put this value under the attribute on the server side so my LED CAN FINALLY work shinny.

My question is, is there a way of doing this for when I enter dashboard for example, a way to initialize a dashboard with a rule chain? thank you

**Comment by Nathan-ma** [comment]
![image](https://user-images.githubusercontent.com/11060905/64205547-a1ee8a80-ce6e-11e9-85e3-78cca384476f.png)
Hello, me again, I dont know if that could also help. but if there is a simple JScript function to call the RPC method, I could just place it inside the OnInit maybe

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
