### ISSUE TITLE
Cannot create uplink converter which parse several inputs into several device outputs

### ISSUE THREAD

**Issue by arthurborgesdev** [thingsboard/thingsboard#1987]
Hi! 

I have an application which several energy meters are connected to a single PLC, and it sends MQTT messages to Thingsboard PE. The problem which I'm facing is that I cannot set a uplink converter capable of decoding all 16 energy meters inputs into 16 devices outputs. It is a limitation from the platform or I'm doing something wrong? What are the workaround for my use case?

**Comment by mp-loki** [comment]
I assume you need to create the converter output in the following format:
```
result = {
       deviceName: deviceName,
       deviceType: deviceType,
       telemetry: {
              "key1":"value1",
              "key2":"value2",
              ...
              "key16":"value16"
       },

**Comment by arthurborgesdev** [comment]
Sorry for not sending any code with my question. I need something like this as an output:

```
result = {
       {
          deviceName: deviceName1,
          deviceType: meter,
          telemetry: {
             "key1": "value1"
          },
       }, 
       {
          deviceName: deviceName2,
          deviceType: meter,
          telemetry: {
             "key2": "value2"
          },
       },
       {
          deviceName: deviceName3,
          deviceType: meter,
          telemetry: {
             "key3": "value3"
          },
       }, ...
}
```

But I read that result can't contain nested values. Is there another workaround or the right way is to have a single MQTT topic for each device?

**Comment by ashvayka** [comment]
Hi @arthurborgesdev ! Are you sure you have reviewed this article: https://thingsboard.io/docs/user-guide/integrations/#converter-output As you can see, you actually can contain two different devices in the container output. See: 

```json
[
    {
        "deviceName":"SN-111",
        "deviceType":"thermostat",
        "attributes":{
            "model":"Model A"
        },
        "telemetry":[
            {
                "ts":1527863043000,
                "values":{
                    "battery":3.99,
                    "temperature":27.05
                }
            },
            {
                "ts":1527863044000,
                "values":{
                    "battery":3.98,
                    "temperature":27.06
                }
            }
        ]
    },
    {
        "deviceName":"SN-333",
        "deviceType":"thermostat",
        "attributes":{
            "model":"Model A"
        },
        "telemetry":{
            "ts":1527863041000,
            "values":{
                "battery":3.99,
                "temperature":27.05
            }
        }
    }
]
```

**Comment by arthurborgesdev** [comment]
My bad. As I am in Maker PE, I'm only allowed to put 10 devices, so as I already had 9, it was only putting AC1, and ignoring all the rest. Sorry for the inconvenience.
