### ISSUE TITLE
Unit tests are ignored during test phase

### ISSUE THREAD

**Issue by michalolsze** [thingsboard/thingsboard#1989]
Hi, in the application module only tests ending with "*TestSuite.java" are taken by surfire plugin during "test" phase". When I included also "*Test.java" many tests fail (e.g. RuleNodeJsScriptEngineTest fails cause of OutOfMemory).
Is there any good explanation why these tests are excluded by default?

**Comment by Ultrazombie** [comment]
Closed, as not active.
