### ISSUE TITLE
Alarm Widget error

### ISSUE THREAD

**Issue by kristoss** [thingsboard/thingsboard#1996]
As a tenant i cannot create any Alarm widget because i can't find it.
As a sysadmin i am trying to create my own alarm wigdet and i get this error
![Screenshot from 2019-09-08 22-02-53](https://user-images.githubusercontent.com/49038152/64556462-1c744a00-d348-11e9-89fd-d0c2ffb509e7.png)

Any thoughts?

**Comment by Ultrazombie** [comment]
Closed, as not active.
