### ISSUE TITLE
Rule chain Js script failure

### ISSUE THREAD

**Issue by nrdmtt** [thingsboard/thingsboard#1998]
Hi, 
I am facing some problem with a simple JS script used for converting a hex string to a JSON object. After a couple of minutes, the script block stops to work, and all the messages goes to “Failure” branch/output.

![image](https://user-images.githubusercontent.com/1341151/64599113-21251680-d3b9-11e9-9dc8-2497b44b2d21.png)

The blue block fails to process the incoming data after a couple of minutes. Here the JS script that convert a hex string to a JSON object. 
```
var tmp = {};

function hexStringToByte(str) {
    if (!str) {
        return new Uint8Array();
    }

    var a = [];

    for (var i = 0, len = str.length; i < len; i += 2) {

        a.push(parseInt(str.substr(i, 2), 16));

    }

    return new Uint8Array(a);
}

function bin2String(array) {

    return String.fromCharCode.apply(String, array);
}

tmp = (bin2String(hexStringToByte(msg.data)));

var obj = JSON.parse(tmp);

for (var k in obj)
    msg[k] = obj[k];

delete msg.data;

return {
    msg: msg,
    metadata: metadata,
    msgType: msgType
};
```

How can I debug the rule chain? Is there any log to understand why the script fails?

**Comment by mircopz** [comment]
You can use 'TEST TRANSFORMER FUNCTION' button, where last received message is used as input and in test output you can see any errors.

**Comment by nrdmtt** [comment]
Finally found the debugging function. 
It appears that the problem is that the script is blacklisted if it fails for 3 times
From the debug:

> javax.script.ScriptException: Script is blacklisted due to maximum error count 3! 

I will modify the code and use a try catch statement for converting the string to JSON.

**Comment by momolok** [comment]
you could also choose to increase the number of fail count or the execution time in thingsboard.yml file. Depending on your OS, the file can be found here:
Windows: YOUR_INSTALL_DIR/conf
Linux:  /usr/share/thingsboard/conf
