### ISSUE TITLE
Deploy thingsboard to an Kubernetes single node , thingsboard Pod is CrashLoopBackOff?

### ISSUE THREAD

**Issue by dy604** [thingsboard/thingsboard#200]
Zookeeper And Cassandra had deployed。
tb'configure as follows：
`apiVersion: v1

kind: Service

metadata:

  name: tb-service

  labels:

    app: tb-service

spec:

  ports:

  - port: 8080

    name: ui

  - port: 1883

    name: mqtt

  - port: 5683

    name: coap

  selector:

    app: tb

  type: NodePort

---

apiVersion: v1

kind: ConfigMap

metadata:

  name: tb-config

data:

  zookeeper.enabled: "true"

  zookeeper.url: "zk-headless"

  cassandra.url: "cassandra-headless:9042"

---

apiVersion: apps/v1beta1

kind: StatefulSet

metadata:

  name: tb

spec:

  serviceName: "tb-service"

  template:

    metadata:

      labels:

        app: tb

    spec:

      containers:

      - name: tb

        imagePullPolicy: IfNotPresent

        image: registry.ng.bluemix.net/thingsboards/application:1.2.4

        ports:

        - containerPort: 8080

          name: ui

        - containerPort: 1883

          name: mqtt

        - containerPort: 5683

          name: coap

        - containerPort: 9001

          name: rpc

        env:

        - name: ZOOKEEPER_ENABLED

          valueFrom:

            configMapKeyRef:

              name: tb-config

              key: zookeeper.enabled

        - name: ZOOKEEPER_URL

          valueFrom:

            configMapKeyRef:

              name: tb-config

              key: zookeeper.url

        - name : CASSANDRA_URL

          valueFrom:

            configMapKeyRef:

              name: tb-config

              key: cassandra.url

        - name : RPC_HOST

          valueFrom:

            fieldRef:

              fieldPath: status.podIP

        command:

        - /bin/bash

        - -c

        - /run-application.sh

        livenessProbe:

          httpGet:

            path: /login

            port: ui-port

          initialDelaySeconds: 120

          timeoutSeconds: 10`

**Comment by volodymyr-babak** [comment]
please provide logs for the tb pods and for the kubernetes events.

**Comment by dy604** [comment]
## Hi dear volodymyr-babak ！ My Operations logs and the Kubernetes Pod events as follows！Thank you very much！ 

root@dy:~/k8s# kubectl get pods
NAME          READY     STATUS             RESTARTS   AGE
cassandra-0   1/1       Running            0          1d
tb-0          0/1       CrashLoopBackOff   4          2m
zk-0          1/1       Running            0          1d
root@dy:~/k8s# kubectl logs tb-0
/bin/bash: /run-application.sh: No such file or directory
root@dy:~/k8s# kubectl describe pod tb-0
Name:		tb-0
Namespace:	default
Node:		173.193.107.212/173.193.107.212
Start Time:	Fri, 07 Jul 2017 13:53:27 +0800
Labels:		app=tb
Status:		Running
IP:		172.30.2.153
Controllers:	StatefulSet/tb
Containers:
  tb:
    Container ID:	docker://be5accb1607e066f9cb98ee2071aec32d3d2fbe713f1e1427e01d2d911a7ef04
    Image:		registry.ng.bluemix.net/thingsboards/application:1.2.4
    Image ID:		docker-pullable://registry.ng.bluemix.net/thingsboards/application@sha256:7fd7d055764fc3c628099affaa2ffb759068a43babd975c5b2b25bff854d791e
    Ports:		8080/TCP, 1883/TCP, 5683/TCP, 9001/TCP
    Command:
      /bin/bash
      -c
      /run-application.sh
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	127
      Started:		Fri, 07 Jul 2017 13:56:30 +0800
      Finished:		Fri, 07 Jul 2017 13:56:30 +0800
    Ready:		False
    Restart Count:	5
    Liveness:		http-get http://:ui-port/login delay=120s timeout=10s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-blljz (ro)
    Environment Variables:
      ZOOKEEPER_ENABLED:	<set to the key 'zookeeper.enabled' of config map 'tb-config'>
      ZOOKEEPER_URL:		<set to the key 'zookeeper.url' of config map 'tb-config'>
      CASSANDRA_URL:		<set to the key 'cassandra.url' of config map 'tb-config'>
      RPC_HOST:			 (v1:status.podIP)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-blljz:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-blljz
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----				-------------		--------	------		-------
  3m		3m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned tb-0 to 173.193.107.212
  3m		3m		1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal		Created		Created container with docker id f5614a6e3d1f; Security:[seccomp=unconfined]
  3m		3m		1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal		Started		Started container with docker id f5614a6e3d1f
  3m		3m		1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal		Created		Created container with docker id 14d5ea9676ce; Security:[seccomp=unconfined]
  3m		3m		1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal		Started		Started container with docker id 14d5ea9676ce
  3m		3m		3	{kubelet 173.193.107.212}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tb" with CrashLoopBackOff: "Back-off 10s restarting failed container=tb pod=tb-0_default(9891a6cd-62d8-11e7-9229-de0c19468281)"

  2m	2m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Created		Created container with docker id 0ec41110026d; Security:[seccomp=unconfined]
  2m	2m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Started		Started container with docker id 0ec41110026d
  2m	2m	2	{kubelet 173.193.107.212}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tb" with CrashLoopBackOff: "Back-off 20s restarting failed container=tb pod=tb-0_default(9891a6cd-62d8-11e7-9229-de0c19468281)"

  2m	2m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Created		Created container with docker id 9c1a9acafa45; Security:[seccomp=unconfined]
  2m	2m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Started		Started container with docker id 9c1a9acafa45
  2m	1m	4	{kubelet 173.193.107.212}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tb" with CrashLoopBackOff: "Back-off 40s restarting failed container=tb pod=tb-0_default(9891a6cd-62d8-11e7-9229-de0c19468281)"

  1m	1m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Created		Created container with docker id fbe88196edfa; Security:[seccomp=unconfined]
  1m	1m	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Started		Started container with docker id fbe88196edfa
  1m	28s	7	{kubelet 173.193.107.212}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tb" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tb pod=tb-0_default(9891a6cd-62d8-11e7-9229-de0c19468281)"

  3m	15s	6	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Pulled		Container image "registry.ng.bluemix.net/thingsboards/application:1.2.4" already present on machine
  15s	15s	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Created		Created container with docker id be5accb1607e; Security:[seccomp=unconfined]
  14s	14s	1	{kubelet 173.193.107.212}	spec.containers{tb}	Normal	Started		Started container with docker id be5accb1607e
  3m	7s	18	{kubelet 173.193.107.212}	spec.containers{tb}	Warning	BackOff		Back-off restarting failed docker container
  13s	7s	2	{kubelet 173.193.107.212}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "tb" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=tb pod=tb-0_default(9891a6cd-62d8-11e7-9229-de0c19468281)"

**Comment by volodymyr-babak** [comment]
how had you built your image "registry.ng.bluemix.net/thingsboards/application:1.2.4" and when ?
Error says that it can't find /run-application.sh file but in tha latest master build this should not happen.

**Comment by dy604** [comment]
My image is thingsboard official published. I just push it in IBM Bluemix Container Registry。

**Comment by volodymyr-babak** [comment]
At the moment officially TB is not supporting kubernetes deployment. 
TB will support officially kubernetes starting from 1.3.0 release that is going to happen soon.

If you wish do it now and not to wait for the official release you can do it but by yourself. This is available in master branch and you have to build docker images from master branch and deploy them to your own docker clouds. And update kubernetes yaml file to use your custom images.

**Comment by dy604** [comment]
Ok！ I know！

I was just waiting for the official release！
 
Thank you very much！

**Comment by volodymyr-babak** [comment]
Deployment steps to Kubernetes cluster is here:
https://thingsboard.io/docs/user-guide/install/kubernetes/
