### ISSUE TITLE
Post using MQTTlens

### ISSUE THREAD

**Issue by indrajitjagtap** [thingsboard/thingsboard#2003]
Hi,

I am looking for how I can connect and post from MQTTlens.

I used device token as client id, access token as user name and password blank. I also tried using user's login user name and password. It does not connect.

Has anybody done this successfully?

**Comment by hemantkamalakar** [comment]
I am using MQTT Box chrome app.
You can use access token as username and leave password empty.
Screenshot
![image](https://user-images.githubusercontent.com/1947238/65263141-8ac7c200-db29-11e9-8305-e49c2e4bb3fd.png)

**Comment by indrajitjagtap** [comment]
Great thanks. It worked...

**Comment by Karabiy** [comment]
you can use the mosquitto and many other clients for those reasons too. also, please, make sure to have the firewall being configured properly
