### ISSUE TITLE
Reference local http resources in custom widgets

### ISSUE THREAD

**Issue by AbCthings** [thingsboard/thingsboard#2004]
Hi all,
I am trying to reference some resources (images, CSS, Javascript) from within a custom widget I am developing. 
Until now, I always used the complete URI such as "http://example.com/res.css".
Unfortunately I am deploying thingsboard in an environment without Internet access.
Is there any way to get a reference to this resources (such as "C:\\\res.css" or "http://localhost:8080/res.css") from within the widget without having to recompile tb?
Is there any "www" accessible folder of the tb web server where i can put my resources?
Thanks

**Comment by Ultrazombie** [comment]
The ThingsBoard functionality does not provide for this
