### ISSUE TITLE
Change dashboard timewindow from ActionsApi with clicked datapoint timestamp

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#2009]
Hello. I'm trying to update the dashboard state's timewindow when I click on a row of a timeseries data table. I've copied the  TimeSeries Card widget and added a "On Row Click" Action option to it.

I haven't found any clues on how to use the Actions section in order to update the timewindow. I've seen I can get the widgetContext on the Action javascript section, and perhaps I could then access the dashboard from the context and edit the timewindow function there. But I want to use the selected timestamp as the source for the time window.

For example: If I select a sample with timestamp dated at 15/05/2019 12:57:30, I want to set the TimeWindow to that date +- 5 minutes. 

How should I approach this? Does anyone have documentation on modifying things from the actions api?

**Comment by corra71** [comment]
Hello. I'm using something like this

const newDashboardtimewindow = {
                aggregation: {
                    limit: 25000,
                    type: "NONE"
                },
                hideAggInterval: false,
                hideAggregation: false,
                hideInterval: false,
                history: {
                    historyType: 1,
                    fixedTimewindow: {
                        startTimeMs: // put here start time in msec
			endTimeMs: // put here end time in msec
                    }
                },
                selectedTab: 1
            };

            widgetContext.dashboard.dashboardTimewindowChangedSubject.next(newDashboardtimewindow);
