### ISSUE TITLE
Cannot add new widget datasource if device has no data

### ISSUE THREAD

**Issue by dbrosy** [thingsboard/thingsboard#2011]
Hi,

I'm trying to follow the video tutorial below:
https://www.youtube.com/watch?v=TwJJbxwQX5k (go to 8:22)
if I have the second thermometer with no data I cannot add datasource due to temperature key not being available, also I cannot create

Steps:
* after creating an alias open "Add New Widget"
* under Digital Gauges select a gauge.
* on data tab click ADD
* In parameters select alias
* type temperature in next box <-- this is issue

Cannot enter temperature (not found) or create temperature key

**Comment by Ultrazombie** [comment]
Closed, as not active.
