### ISSUE TITLE
Cant connect to thingsboard localhost:8080

### ISSUE THREAD

**Issue by hazee007** [thingsboard/thingsboard#2012]
hello guys i have successfully install thingsboard on my PC(windows 10) following necessary procedure and and installing the required applications. 
i was able to start the thingsboard on my cmd in Administrative mode, and also when i checked my Services on my pc i saw thingsboard has been installed which is okay since i installed it from cmd previously, i can start, stop and restart with no error except which i try going to the localhost:8080 on my google chrome, i says site cant be reached.
I look around on the web for some answers and someone suggested port conflict issue.. so i checked my listening port on my pc, there was no conflict and funny enough when i start thingsboard which should be listening on port 8080, i found out that the port was not even showing up anywhere.

below are some file that may be of importance in figuring this out.  Thanks..
[thingsboard.2019-09-14.0.log](https://github.com/thingsboard/thingsboard/files/3613560/thingsboard.2019-09-14.0.log)

[thingsboard_ymlfile.zip](https://github.com/thingsboard/thingsboard/files/3613561/thingsboard_ymlfile.zip)

**Comment by pgrisu** [comment]
Your installation isn't able to start MQTT service

`2019-09-14 22:05:20,830 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Starting MQTT transport...
2019-09-14 22:05:21,158 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MqttTransportService': Invocation of init method failed; nested exception is java.net.BindException: Address already in use: bind
2019-09-14 22:05:21,215 [main] INFO  o.t.s.a.service.DefaultActorService - Actor system terminated: Terminated(Actor[akka://Akka/])
2019-09-14 22:05:21,229 [main] INFO  o.t.s.s.c.rpc.ClusterGrpcService - Going to onStop RPC server
2019-09-14 22:05:21,240 [main] INFO  o.t.s.s.c.rpc.ClusterGrpcService - RPC server stopped!
2019-09-14 22:05:21,248 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2019-09-14 22:05:21,251 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2019-09-14 22:05:21,269 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2019-09-14 22:05:21,273 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
`
It seems that TCP port 1883 is already in use on you system
If so you need to move thingsboard mqtt on different port or disabling mqtt by editing yml file

`  # Local MQTT transport parameters
  mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: "${MQTT_ENABLED:true}"
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    bind_port: "${MQTT_BIND_PORT:1883}"
`

**Comment by hazee007** [comment]
i tried both options now, changing the port to 1885 or disabling mqtt by setting  "${MQTT_ENABLED:true}"  to "${MQTT_ENABLED:false}" both options didnt solve the problem..

**Comment by hazee007** [comment]
Worked...
I stopped the mqtt server i already have running on my pc and then thingsboard worked,
is there a way i can change ports to enable both of them to work together, i tried changing in yml file but nothing happened.

**Comment by pgrisu** [comment]
Did you restarted thingsboard after changing yml file?

**Comment by hazee007** [comment]
ye

> Did you restarted thingsboard after changing yml file?

yes i restarted

**Comment by hazee007** [comment]
Thanks @pgrisu  i was finally  able to change the yml file and everything is working now, i change the port to 1882, for some reason i dont know it doesnt work on port 1885.

**Comment by Nitheshnithu121** [comment]
I have successfully install mainflux CE server on aws EC2 instance using Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0b44050b2d893d5f7 (64-bit x86) / ami-0dc231c09aef801ea (64-bit Arm) 
Now i am not able open the thingsboard login page using http://public ip:8080 port ,can any one help me to solve this problem

**Comment by AWangji** [comment]
> Worked...
> I stopped the mqtt server i already have running on my pc and then thingsboard worked,
> is there a way i can change ports to enable both of them to work together, i tried changing in yml file but nothing happened.

how do you stop mqtt? I met a similar problem but I cannot revolve it as I had change the port to 1882. Could you please help me? thanks.

**Comment by jide07** [comment]
if you are using windows you can check running ports using the command 

> netstat -aon | find /i "listening"  or check [here](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows?page=1&tab=votes#tab-top) for other systems
 
or you can follow this procedure about installing mqtt 

> http://bytesofgigabytes.com/mqtt/installing-mqtt-broker-on-windows/

it's for windows but you will find which operating systems you want.

hopefully this helps

**Comment by rinodc** [comment]
> I have successfully install mainflux CE server on aws EC2 instance using Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0b44050b2d893d5f7 (64-bit x86) / ami-0dc231c09aef801ea (64-bit Arm)
> Now i am not able open the thingsboard login page using http://public ip:8080 port ,can any one help me to solve this problem

Hello, you must open 8080 port first, check security manager of your EC

**Comment by shabir67** [comment]
Hello, i've been trying all the solutions in thes post, but turns out the localhost:8080 still wont open. It would be great if you could help me out. thankyou
[thingsboard.txt](https://github.com/thingsboard/thingsboard/files/7159984/thingsboard.txt)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/7159989/thingsboard.log)

**Comment by yulin-willbeok** [comment]
Hi, I have the same problem. The installation starts everything fine, and when I visit http://localhost:8080/时, I have the problem of connection refused, what can I do to fix it?
os:windows11
[Uploading thingsboard.log…]()
