### ISSUE TITLE
How to utilize the Webcamera Input Widget?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#2014]
Since the last release the Webcamera Input Widget is included. But I can't figure out how to get it working. It would be a cool feature if it's possible to display Camera Streams in the dashboards.

Thanks in advance.

**Comment by bcleuing** [comment]
I successfully got the widget working by doing these:
1) Add a new attribute (e.g. stream_url) to an asset / device which stores the stream URL of my web camera.
2) In the Web Camera Input widget, set that asset / device as the datasource and select the attribute of the stream URL like below:
![image](https://user-images.githubusercontent.com/12772664/65161317-efbbe300-da69-11e9-83dc-c99e1fda4a84.png)

You should then be able to see the live view of the camera.

Hope this helps.

**Comment by mde2017** [comment]
Many thanks, your solution also worked for my use-case.

**Comment by BernhardHaider** [comment]
Hi, i try to make the widget working, but it always shows "no supported web camera"
maybe you can provide an example url for the stream attribute. maybe a public to try it myself
are there any prerequists, e.g. type of the stream?
thank you!

**Comment by bcleuing** [comment]
@BernhardHaider After looking into the code of web camera input widget (https://github.com/thingsboard/thingsboard/blob/a2cc974865ef16748918a98f8240176d401dddf3/ui/src/app/widget/lib/web-camera-input-widget.js), I found out that if your computer does not have a built-in camera, the widget will always show "no supported web camera" (I have tested this with my desktop and notebook computer). So I think I may have misunderstood the usage of the widget.

If you merely want to show your camera stream (HTTP) in the dashboard, you may simply try using the ThingsBoard **static HTML card** widget:

![image](https://user-images.githubusercontent.com/12772664/70848435-6bcc9800-1eac-11ea-9430-1e4fa52ddf16.png)
```
.card {
    font-weight: bold;
    font-size: 32px;
    color: #999;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
}

<div class='card'>
  <img style="height: 100%" src="http://<put your stream url here>">
</div>
```
Hope it works for you.

**Comment by eduardo-leite-oliveira** [comment]
@bcleuing do you know how to send a stream url from python? 
I tried to use static html card with my stream url but it isn't work. If I use a live streaming it works.

**Comment by bcleuing** [comment]
> @bcleuing do you know how to send a stream url from python?
> I tried to use static html card with my stream url but it isn't work. If I use a live streaming it works.

Sorry I do not have much experience with Python streaming, but I can briefly share how I implemented the public camera stream URLs with Raspberry Pi cameras, OpenVPN, Node.js & Express.

- The Raspberry Pis & Node.js server are under the same VPN network

- Node.js server acts as a proxy and exposes the Pi camera streams to the public

```
#!/root/.nvm/versions/node/v14.16.0/bin/node

const express = require('express');
const app = express();
const request = require('request');
const token = 'XXXXXXXX';

app.get('/stream-camera', function(req, res) {
    if (req.query.token == token && !isNaN(req.query.host)) {
      let url = `http://192.168.255.${req.query.host}/html/cam_pic_new.php`;
      request.get({ url }).pipe(res);
    } else {
      res.status(400).end();
    }
});

app.listen(8880, function(){
    console.log('App listening on port 8880!')
});
```

Example streaming camera 192.168.255.3 in ThingsBoard static HTML card 
```
<div class='card'><img style="height: 100%" src="http://<nodejs_server_ip_or_domain>/stream-camera?token=XXXXXXXX&host=3" /></div>
```
