### ISSUE TITLE
How to extend thingsboard user registration to phone number based user registration?

### ISSUE THREAD

**Issue by nirvitarka** [thingsboard/thingsboard#2016]
NOTE: I have asked the same question on [stackoverflow ](https://stackoverflow.com/questions/57967670/how-to-extend-thingsboard-user-registration-to-phone-number-based-user-registrat)
I am trying to implement phone number based user registration for thingsboard users.

Here is what I have tried:

1) Create an email user for the given phone number. For example : PHONE_NUMBER@mydomain.com in thingsboard via REST API call.

2) Create a custom REST api to enable this user & set password (entered by user along with phone number)

Now I am not sure where to call this api in thingsboard rule chain, so that the registered user is activated properly.

I thought it is the "Other" link in Root rule chain but that does not seem a correct place. When I put a "rest api call" node there, nothing happened.

Can someone please guide me to the right direction? Am I following the best possible path to implement phone-based authentication in thingsboard?

**Comment by srinivasankk7** [comment]
> NOTE: I have asked the same question on [stackoverflow ](https://stackoverflow.com/questions/57967670/how-to-extend-thingsboard-user-registration-to-phone-number-based-user-registrat)
> I am trying to implement phone number based user registration for thingsboard users.
> 
> Here is what I have tried:
> 
> 1. Create an email user for the given phone number. For example : [PHONE_NUMBER@mydomain.com](mailto:PHONE_NUMBER@mydomain.com) in thingsboard via REST API call.
> 2. Create a custom REST api to enable this user & set password (entered by user along with phone number)
> 
> Now I am not sure where to call this api in thingsboard rule chain, so that the registered user is activated properly.
> 
> I thought it is the "Other" link in Root rule chain but that does not seem a correct place. When I put a "rest api call" node there, nothing happened.
> 
> Can someone please guide me to the right direction? Am I following the best possible path to implement phone-based authentication in thingsboard?

Hello, Have you got solution for your need? I am also trying to add new customer or user through mobile app and trying to find out the exact rest api to do this

**Comment by nirvitarka** [comment]
I did not get it to work, I then gave up on it.
However, phone number based authetication could be a nice to have feature there.

**Comment by ban2derlog** [comment]
Hi, there are no such features out-of-box.
But you can try to use some 3rd party OAuth 2 authorization by phone to work in ThingsBoard.
