### ISSUE TITLE
Unable to start TB services.

### ISSUE THREAD

**Issue by z4nD4R** [thingsboard/thingsboard#202]
Hello everyone,

I've tried to define outgoing email server. Unfortunately the UI somehow "glitch" (I specify the server - test it via test button - works - but when came back to the settings the UI was empty). I tried to redefine the server several time but the same result - email settings form was alway empty with UI message "Can not load email settings" ( or smth like that). 

I decided to restart TB using `service thingsboard stop` and than `service thingsboard start`. Unfortunately the TB service is not able to start. 

In `/var/log/thingsboard/thingsboard.log` I can see following message:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userController': Unsatisfied dependency expressed through field 'mailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailService': Invocation of init method failed; nested exception is java.lang.NullPointerException `

I believe it says "there is no email settings" and therefore it can't start. Well, I believe the missing UI settings shouldn't stop whole service to start :)

So my question is rather simple: How to fix and make TB alive again?

Thank you all

Y

**Comment by volodymyr-babak** [comment]
hi,

please login into cassandra database using **cqlsh** command:
voba@voba-pc:~$ **cqlsh**
_Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help._

and then execute next query:
**cqlsh> SELECT * from thingsboard.admin_settings where key = 'mail' ALLOW FILTERING;**

and paste output here

**Comment by z4nD4R** [comment]
Hi @volodymyr-babak ,

I'm currently @work :) I'll perform the requested querry as soon as I come back home.

Y

**Comment by z4nD4R** [comment]
@volodymyr-babak 

do you need any more outputs?

Y

**Comment by volodymyr-babak** [comment]
you are missing mail settings. 
Please execute next CQL query in cassandra console:

**INSERT INTO thingsboard.admin_settings ( id, key, json_value )
VALUES ( now ( ), 'mail', '{
	"mailFrom": "Thingsboard <sysadmin@localhost.localdomain>",
	"smtpProtocol": "smtp",
	"smtpHost": "localhost",
	"smtpPort": "25",
	"timeout": "10000",
	"enableTls": "false",
	"username": "",
	"password": ""
}' );**

**Comment by z4nD4R** [comment]
@volodymyr-babak 

thank you. That helped indeed. Please makr the issue as resolved.

Feature request: don't let missing config fail to start whole app. :) 

Y
