### ISSUE TITLE
RBAC - Dashboard Input Widget Error

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#2021]
Hi there,

We have a Customer User defined for our customer and an update device attribute input widget on one of our dashboards. However user gets a "YYou don't have permission to perform this operation!" error when trying to update device attributes via the input widget.

This user is defined in group "Customer User" for an assigned customer:
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/16280541/65199530-1b21ea80-dac9-11e9-9863-86d618977029.png">

"Customer Users" group has roles assigned:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/16280541/65200855-d21f6580-dacb-11e9-8ebc-5b4a178703b3.png">

The Limit Access group role, grants the user write attributes access to the device group "Aquacheck Soil Probes" which contains the devices to which the dashboard input widget is updating attributes. The role has the following permissions
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/16280541/65201136-dbf59880-dacc-11e9-923d-c42ee6f80ac8.png">

We also tried adding a Generic "Limited Access" role as well with the following permissions, but had no luck:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/16280541/65199008-bf576180-dac8-11e9-8339-154164ac286d.png">

What are we missing so the Customer User can update attributes for devices from the customer device group "Aquacheck Soil Probes" using the dashboard input widget?

**Comment by ThinLizzy13** [comment]
Hi could someone help me with something similar please?
