### ISSUE TITLE
Best way to replicate dashboards between tenants

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#2022]
Hi there,

We wish to present a common set of dashboard to all clients. We know this can be done in a single tenant using advanced RBAC (as in video here: https://www.youtube.com/watch?v=xpnYzSiDiJo), but we have hit a limitation with the way custom menu items work with RBAC.

We want to have five custom menu items which link to 'shared' or 'common' dashboards set up as in the RBAC video use case _and one custom menu item which links to a unique homepage dashboard for each customer_. 

So when the customer logs in they see their unique 'homepage dashboard' and then custom menu links to common dashboards showing only their data, as well as a "Home" custom menu item which links to their unique 'homepage dashboard'.

However as the custom menu items are owned by the tenant this cannot be done and the custom menu item which links to a 'homepage dashboard' cannot change based on which customer is logged in. (it would be great to set custom menu items to point to different dashboard states depending on who is logged in)

This means we are having to put customers in their own tenancies to make the custom menu items work as we'd like.

So now we have a headache, since we need to replicate any changes to our common dashboards **across many tenancies**.

So we've taken a look at the admin APIs and considered two approaches:

1. Use the Dashboard Controller to push changes to the common dashboards out to all tenants. This seems plausible, but we're not clear on how the widget IDs and entity alias IDs would be managed when pushing dashboard JSON from one tenant to another.

1. Use the Widget Type Controller and a our own widget bundle. When a widget that is part of a common dashboard is modified, the change could be pushed to each tenant's widget library via API. However we see that even when the widget is modified in the library the changes are not reflected in their instances in existing dashboards, i.e. the dashboards do not use the library as a basis for rendering widgets, and we'd have to re-add the changed widget to each dashboard manually after deploying to the library.

Any advice on this challenge would be greatly appreciated.

Mark

**Comment by danisal** [comment]
I'm also curious about this, is there an easy way to push widget changes to the dashboards where they are being used?

**Comment by mykhailokornieiev** [comment]
Hi. I'm not sure if this request is still relevant for you, but there is Version Control + Auto-Commit feature available since 3.4. You can consider it as a solution for dashboard duplication between tenants
https://thingsboard.io/docs/user-guide/version-control/ 
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
