### ISSUE TITLE
unable to send mail. smtp.sendgrid.net

### ISSUE THREAD

**Issue by Yuva86** [thingsboard/thingsboard#2024]
Hi, Mail server in thingsboard is not working.
I get the following error, when I trigger 'send testmail'
"unable to send mail. smtp.sendgrid.net"
My settings are
protocol: smtp
host: smtp.sendgrid.net
timeout: 10000
Enable TLS-true
port: 587.
API key from sendgrid is valid. I tested that using Postman and i received an email.

Any suggestions, please.

**Comment by mfalkvidd** [comment]
Have you activated the "enable TLS" checkbox?
Are you using "apikey" as username?

**Comment by Yuva86** [comment]
Yes, I activated enable TLS checkbox
Yes, i am using 'apikey' as username

**Comment by vijayshukla80** [comment]
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)

**Comment by Yuva86** [comment]
@mfalkvidd : Any suggestions, pl.

**Comment by amardhore** [comment]
changing the SMTP port to 2525 worked for me

**Comment by ban2derlog** [comment]
Hi, please try a different configuration for SMTP + TLS - port\TLS version.
On latest version port 587 and TLS 1.2 work perfectly.
