### ISSUE TITLE
MQTT 3.1.1 Client IDs (>23 chars) not currently supported

### ISSUE THREAD

**Issue by CliveJL** [thingsboard/thingsboard#2025]
After some time debugging a new MQTT integration in our ThingsBoard 2.4.1 PE deployment with Wireshark, we found that we couldn't connect to our own MQTT broker because the ThingsBoard MQTT client support is for version 3.1 of the MQTT specification, not version 3.1.1. One significant difference is that version 3.1 only allows Client IDs with up to 23 characters, and our Broker requires longer Client IDs to map internally to devices on our platform, something permitted in the 3.1.1 MQTT spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf).

I was wondering if there is anything in the ThingsBoard "roadmap" to provide support for MQTT 3.1.1?

**Comment by msqr** [comment]
I just ran into this same issue. The MQTT integration failed to connect with an error like this:

```
java.lang.RuntimeException: Failed to connect to MQTT broker at X.X.X.X:8885.
```

but no further details. After shortening the client ID to 23 characters, the connect succeeded.
