### ISSUE TITLE
Timeout Error in MQTT-SSL 

### ISSUE THREAD

**Issue by harish2297** [thingsboard/thingsboard#2026]
Hi. I've set up a Thingsboard PE in my system. I followed the procedure given in the link https://thingsboard.io/docs/user-guide/mqtt-over-ssl/ for server configuration and I gave the DOMAIN_SUFFIX as "cloud.thingsboard"
For client configuration I followed the procedure in https://thingsboard.io/docs/user-guide/certificates/ and I gave the DOMAIN_SUFFIX as "cloud.thingsboard" in client side also . I then changed my authentication type in WebUI to X.509 and added the mqttclient.pub.pem key there.
I ran the python sample script give in https://thingsboard.io/docs/user-guide/certificates/ and changed the subscription topic according to my device specifications.
I received 'Connection refused error'. 
I then tried changing hostname in the socket.connect() function to cloud.thingsboard.io. I'm getting a timeout error and I could not see my data getting published.

**Comment by Karabiy** [comment]
please, check the updated guide for the mqtt over ssl using the similar link you have provided. those should not persists afters.

**Comment by jaacsjp** [comment]
Hi,

I am also facing an issue. Thingsboard server refuses SSL handshakes taking more than 8 seconds. Enabling certificate verification in my mbedtls settings takes my CPU clocked at 48MHz take around 12 seconds to verify and complete the handshake. But, after 8 seconds, Thingsboard closes the connection. I find this a regular issue in the embedded world where slow CPUs rule. 

When certificate verification is disabled, I am able to connect without problems, as it takes less than 2 seconds to complete the handshake, but then there is a huge security issue which I dont want in production.

Is it possible to increase this timeout to atleast 12 seconds?? I am using Thingsboard community edition 3.0.1.
