### ISSUE TITLE
[BUG] TB PE Rules Engine - Aggregate Stream Node

### ISSUE THREAD

**Issue by enviroeye** [thingsboard/thingsboard#2027]
Hi there,

We are using the aggregate stream node to calculate various averages on temperature. We are seeing strange entries in the associated devices' telemetry.

The node is configured to write to a value called "averageHourlyTemperature

<img width="817" alt="image" src="https://user-images.githubusercontent.com/16280541/65409630-87834d80-de2b-11e9-82f7-23d42ae01381.png">

However we see this entry for the telemetry instead. It appears to contain the average value in the object and a count. **Is this an expected behaviour.**?

<img width="841" alt="image" src="https://user-images.githubusercontent.com/16280541/65409567-59057280-de2b-11e9-850b-87536ab95000.png">

We would also like to clarify when the calculation for the average is made. The behavior we see for say a daily average is that it is being calculated just once per day. However we have the interval set to 10 minutes and would have thought the average would be calculated every ten minutes with the scope of data being all telemetry the last 24hrs from the moment each time the calculation is done (i.e. the interval period).

**Comment by eeitnn** [comment]
I'm encountering a very similar behavior. In my case however the "RuleNodeState"-Messages (occasionally) appear together with the acutal expected aggregated key-value pair.
Any solutions found?

**Comment by eeitnn** [comment]
This happens if you try to aggregate on a key-value pair that is not provided by one or more of your devices.

**Comment by ashaforost** [comment]
Hi there,

The RuleNodeState telemetry key is added automatically by ThingsBoard. This parameter is directly related to the state persistence setting of the aggregate stream rule node. In case of average aggregation, it stores the sum and count values directly in the database, as opposed to keeping these values in memory, to ensure the fault-proof aggregation (in case your server becomes unresponsive, for example, the latest aggregation could be easily restored) and keep the memory usage to a minimum. 

There's a task on our roadmap to still write this key to the database, but hide it from the UI not to confuse our customers, however, there's no exact timeframe for its implementation.

**Comment by santobedi** [comment]
Hi @ashaforost, 

The RuleNodeState telemetry is still there even in Thingsboard v.3.5.1PE. As I use Analytics nodes multiple times in my rulechain, every device has several occurrences of the RuleNodeState telemetry. Is there any way of hiding it in the UI? It's pretty much annoying to have them in UI.
