### ISSUE TITLE
Slow loading thingsboard iframe...

### ISSUE THREAD

**Issue by Gennaromiccoli** [thingsboard/thingsboard#203]
How does thingsboard take between two and three minutes to load??
The stuffboard's external address loading takes more than 2 minutes.
I noticed that it takes time to download the bundle.js file that is over 6 mb.
Are not there any solutions?

**Comment by ashvayka** [comment]
Once you host your own copy of TB you can configure CDN for this to optimize traffic and page load time. The 6Mb is not small but it will still not be less then 2Mb even if we spend hours on optimization.
