### ISSUE TITLE
TB msa docker installation not working

### ISSUE THREAD

**Issue by prakhar81** [thingsboard/thingsboard#2032]
I have deployed thingsboard2.4 microservices in docker CE on Ubuntu. Its not starting properly

           Name                          Command                 State                                               Ports
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
docker_kafka_1                start-kafka.sh                   Up           0.0.0.0:9092->9092/tcp
docker_redis_1                docker-entrypoint.sh redis ...   Up           0.0.0.0:35788->6379/tcp
docker_tb-coap-transport_1    start-tb-coap-transport.sh       Up           0.0.0.0:5683->5683/udp
docker_tb-http-transport1_1   start-tb-http-transport.sh       Up           0.0.0.0:35793->8081/tcp
docker_tb-http-transport2_1   start-tb-http-transport.sh       Up           0.0.0.0:35794->8081/tcp
docker_tb-js-executor_1       start-js-executor.sh             Restarting
docker_tb-js-executor_2       start-js-executor.sh             Restarting
docker_tb-mqtt-transport1_1   start-tb-mqtt-transport.sh       Up           0.0.0.0:35796->1883/tcp
docker_tb-mqtt-transport2_1   start-tb-mqtt-transport.sh       Up           0.0.0.0:35795->1883/tcp
docker_tb-web-ui1_1           start-web-ui.sh                  Restarting
docker_tb-web-ui2_1           start-web-ui.sh                  Restarting
docker_tb1_1                  start-tb-node.sh                 Up           0.0.0.0:35801->8080/tcp
docker_tb2_1                  start-tb-node.sh                 Up           0.0.0.0:35800->8080/tcp
docker_zookeeper_1            /docker-entrypoint.sh zkSe ...   Up           0.0.0.0:35791->2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp
haproxy-certbot               /start.sh                        Up           0.0.0.0:1883->1883/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:9999->9999/tcp

I am not able to access http://localhost. It says 503 error

**Comment by affoltep** [comment]
It takes a while to start all the services (up to 5 to 10 minutes). Check the log files for errors, especially from tb1 (docker-compose logs -f tb1 | grep ERROR) and cassandra (docker logs -f  <docker_container ID of cassandra>) 
User docker ps to find the docker_container ID of cassandra
