### ISSUE TITLE
Is it possible to relate two devices to one asset?

### ISSUE THREAD

**Issue by kristoss** [thingsboard/thingsboard#2039]
I need to provide a solution when  2 devices push telemetry to one asset.
Is that possible?The change originator node satisfies only the first relation.

**Comment by Karabiy** [comment]
in case if I have understood you correctly, you can use the duplicate to related rule node and afters apply filtering to exclude the related which you don't want to be used for the further processing based on the attribute/etc

**Comment by nmahale10** [comment]
Hello,Can you please elaborate it a little further.

**Comment by Karabiy** [comment]
the change originator does so, though, the duplicate to related node is an okay with those 
it is the ThingsBoard Professional edition functionality 
you can refer to this via this link: https://thingsboard.io/docs/user-guide/rule-engine-2-0/pe/transformation-nodes/#duplicate-to-related-node

**Comment by nmahale10** [comment]
![RULE1](https://user-images.githubusercontent.com/22172258/88308137-4d742800-cd2a-11ea-9e68-6728cdbe4066.png)


I have created this,but no success

**Comment by Karabiy** [comment]
You may apply the next approach for the use case of yours.
 
I have made a rule chain that adds telemetry to the related asset depending on the value of the parameter so you can use it as an example.
The logic of this rule chain is when the message from the device comes to the "duplicate" node the message duplicates to all assets related to this device. Then every message goes through the "add_atr" node where the server attribute is taken in my case.
To store telemetry only in the dedicated asset, there is the "switch" node that checks whether the server attribute is equal to attribute in telemetry. 

![img](https://user-images.githubusercontent.com/31805736/88387692-afc93900-cdbb-11ea-9186-7c61ca07786e.png)
