### ISSUE TITLE
Unable to Clear or Acknowledge User Alarms

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#2040]
I've setup a dashboard with a user as State Entity and put in an Alarms Widget. The widget is configured to enable Alarms clearing and acknowledging.

But Whenever I click on Clear or in Acknowledge: Nothing happens, nothings changes and the alarm remains as is.

Any ideas?

**Comment by IoTopenTech** [comment]
Check that the Originator is not simulated

**Comment by Manusisko** [comment]
Yes, that was the issue. Figured it out a little bit after posting but forgot to update the thread.
