### ISSUE TITLE
How to use REST api 

### ISSUE THREAD

**Issue by wudision0416** [thingsboard/thingsboard#2041]
Hello everyone。
I would like to ask if there is a detailed document about the rest api.
for example:  at `swagger ui` -> `admin-controller` , What‘s’ means about `jsonValue` and `key`.

Where should I get the list of the valid parameters?

**Comment by srinivasankk7** [comment]
Hi, have you got inputs on this? I am also looking for this..

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
