### ISSUE TITLE
Feature Request - rule node to modify ${entityDescription} and ${entityLabel}

### ISSUE THREAD

**Issue by affoltep** [thingsboard/thingsboard#2042]
This request is related to #1626, #987 and #940 
In Timeseries - Flot (graph), there can be used ${entityDescription} as data label.

Unfortunately the description can only be changed from the "Backend" under devices. There is no way to modify the description by the "Frontend" e.g. dashboards.
With a widget, or even better by a rule node which allows to modify the entityDescription variable, these disadvantage may be eliminated. Users, who just have access to the frontend would be able to name their labels for their needs.

**Additional:** Since V2.4.0 there is for devices a new field "Label" available. The ${entityLabel} could be used for Data labels in widget timeseries -flot, too.
So, a rule node, which allows to modify the Label and Description field would be great.

**Comment by den1jkee** [comment]
Thank you for your feedback. We are always improving our project and have already done this feature in the latest versions of ThingsBoard.

Best regards,

ThingsBoard Team.
