### ISSUE TITLE
Generator Rule Node fails after two hours

### ISSUE THREAD

**Issue by Surgbc** [thingsboard/thingsboard#2044]
We have a rule chain with several generator rule nodes which we have used to implement some scheduling that worked seemlessly for three months or so, then they started failing. They work for two hours when thingsboard service is restarted, but fail after that.

Any hint as to what could be causing this?

![image](https://user-images.githubusercontent.com/553313/65936468-628f6b80-e425-11e9-8756-9b2daba20922.png)

**Comment by vparomskiy** [comment]
> they started failing
any logs or please describe how you understood that node failed?

**Comment by Surgbc** [comment]
I have added to the rule chain a rest api call node. From the endpoint, I have a script which monitors the calls made and restarts thingsboard if nothings happens in 10 seconds. Any request to the script shows that the generator node is working, when the requests stops, it shows that the generator has stopped working.

Here is part of the log. 


Oct  1 07:19:57 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 08:18:46 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 09:24:33 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 10:09:31 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 11:19:00 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 11:41:45 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 12:53:37 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 13:49:32 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 15:19:20 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 17:00:38 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 18:35:47 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 18:46:37 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 19:13:43 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 20:05:45 dashboard vipimobot[19261]: restarting thingsboard
Oct  1 22:00:33 dashboard vipimobot[19261]: restarting thingsboard
Oct  2 01:51:25 dashboard vipimobot[19261]: restarting thingsboard
Oct  2 04:00:57 dashboard vipimobot[19261]: restarting thingsboard

The same can also be seen in the debug logs for the nodes in thingsboard.

**Comment by vparomskiy** [comment]
Restarting thingsboard if no messages arrived in 10 seconds - doesn't sound like a good idea.

Generator node is very simple and I don't think that it does not work. More realistic is that rule chain is not configured properly or the system is under heavy load and there is not enough CPU resources to guarantee short execution time.

Debug logs - note that some rule chain debug events may not be saved in the DB if system is under heavy mode. Here is defualt config from thingsboard.yml:
```
debug_mode_rate_limits_per_tenant:
        enabled: "${ACTORS_RULE_CHAIN_DEBUG_MODE_RATE_LIMITS_PER_TENANT_ENABLED:true}"
        configuration: "${ACTORS_RULE_CHAIN_DEBUG_MODE_RATE_LIMITS_PER_TENANT_CONFIGURATION:500:3600}"
```
It means that only the first 500 debug events will be saved in the database per hor, other will be rejected

**Comment by Surgbc** [comment]
I increased the limit and that pretty well solves the issue. I have observed it long enough to conclude that it is now stable.
