### ISSUE TITLE
Update Multiple Attributes widget, can't place the attributes beneath each other

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard#2045]
The attributes you add are placed one next to other. So if you add a lot of them they shrink and you can't see it any more. Is a way to place the attribute beneath each other?
![multiattr](https://user-images.githubusercontent.com/31473443/65947870-ccb60980-e441-11e9-830e-cb0690bd9e13.JPG)

**Comment by Tasosgi** [comment]
Also when I change an attribute the save button continuous to be grey. I must change the most attributes in order the save button to become active.

**Comment by mircopz** [comment]
> The attributes you add are placed one next to other. So if you add a lot of them they shrink and you can't see it any more. Is a way to place the attribute beneath each other?
> ![multiattr](https://user-images.githubusercontent.com/31473443/65947870-ccb60980-e441-11e9-830e-cb0690bd9e13.JPG)

Yes you have a row for each datasource in widget config. If you want N rows, you should add N times the same datasource, adding each time a different set of datakeys

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
