### ISSUE TITLE
Updating thingsboard with sql database

### ISSUE THREAD

**Issue by lazaj** [thingsboard/thingsboard#2046]
Hello,

Just need some clarification about the update.
In the update guide you tell : "Please make sure that you set database.entities.type and database.ts.type parameters values (in the file /etc/thingsboard/conf/thingsboard.yml) to “cassandra” instead of “sql” in order to upgrade your cassandra database".
It's necessary when using only sql database ?

Regards.

**Comment by morpheus000** [comment]
Hello,
worked for me without changing to cassandra.

**Comment by Karabiy** [comment]
it is necessary to have those being set correctly for both, in case if  you have created the new files (thingsboard.conf and thingsboard.yml) for the new version upgrade and haven't merged those with the one you configured for the previous versions.
