### ISSUE TITLE
Removing telemetry data when removing a device

### ISSUE THREAD

**Issue by martindenion** [thingsboard/thingsboard#2047]
Hello,
I have a Cassandra DB installed on Thingsboard. I know how to remove manually telemetry data from Cassandra DB. When I remove manually a device on Thingsboard, I'd like to remove telemetry data related to this device too. 
I don't really know what I have to modify in the source code, maybe this link will have to be modified : https://github.com/thingsboard/thingsboard/blob/3d8aaf69e85ee11aab402eaff24f93b681b1dd37/ui/src/app/device/device.controller.js

Please help !

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
