### ISSUE TITLE
Post numeric attribute value as string

### ISSUE THREAD

**Issue by sfvaleriano** [thingsboard/thingsboard#2051]
Helo,

when I send a numeric attribute as a string it is always saved as a numeric type into field long_v.
eg.:
{"zipCode":"00100"} it's saved as 100 into field long_v of table attrivute_kv

Why? How to solve?

ThingsBoard CE 2.4.1
PostgreSQL 11.5

Regards.

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
