### ISSUE TITLE
REST API Call Google Calendar

### ISSUE THREAD

**Issue by WictorSvensson** [thingsboard/thingsboard#2058]
Hi!

Im setting up a dashboard and want to send out alarms to different people depending on the time of the alarm. My plan is to use Google Calendar API to fetch different emails depending on events in the calendar. 
I'm having some troubles since Google Calendar API seems to use OAuth 2.0 and ThingsBoard REST API Call node needs an API url, method and optional header. In ThingsBoards example for this rule engine node they are using Authorization as a header with the api-key, but this is not possible with OAuth 2.0 as i understand it.

My question is if somebody else have had this problem? Or if there are any other way I can schedule people getting alarm in different times.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
