### ISSUE TITLE
Send MQTT message from thingsboard to device

### ISSUE THREAD

**Issue by z4nD4R** [thingsboard/thingsboard#206]
Hello,

I'm trying to control my RGB Led strip color via thingsboard, but I'm unable to send message from server to device.

The custom widge is pretty simple:
html
```
<button id="sendMessage">Set RGB color.</button> <input type="color" id="color" value="#FFFFFF"></br>
```

js
```
$("#sendMessage").click(function() {
   controlapi.sendOneWayCommand("echo",{'lsc1': $("#color").val()}, 5000);
});
```

When I chose color and hit the send button no messages arrives on device. The `python` message `on_message` is never triggered.

Any help here?

Thank you.

**Comment by ashvayka** [comment]
What was the issue and how did you fixed it?

**Comment by z4nD4R** [comment]
@ashvayka ,

thank you came back to this :)

The issue was caused that I forgot to uncomment following line in my `python` code:
`self.client.loop_forever()` co you can imagine where was the problem.

But to be honest with the `MQTT` messaging from `thingsboard` it is still not working in proper way.

I can set my color, and I see the incomming messages in log:

`17.07.2017 13:17:24  DEBUG  J.py mqtt_msg_rcvd(): MSG from cloud='{"method":"setValue","params":{"value":"#ff00ff","device":"lsc1"}}' from channel='v1/devices/me/rpc/request/192'
`

But after few color changes (2-4) the `MQTT` messages just stop to sent. I've also fired `tcpdump` to see if any packets are incomming but the `thingsboard` is NOT sending any message.

When I restart my `python` app the `MQTT` messages works again (for 2-4 times). I'm using `demo.thingsboard.io` and so I don't have access to `/var/log/thigsboard/thingsboard.log`.

Could you please help me with this issue?

Thx

Y

**Comment by z4nD4R** [comment]
Ok problem solved. 

Note: do not send `hex` value to thingsboard. Send just `numbers`. 

There could be feature request: to add "data type" support as you can see it in i.e. cayenne: https://mydevices.com/cayenne/docs/bring-your-own-thing-api/#cayenne-mqtt-api-supported-data-types

**Comment by ralienpp** [comment]
MQTT allows you to send arbitrary payloads, they're just bytes, after all. If some of the messages are not delivered, it is something in the logic of Thingsboard itself that interferes with that - so it is likely to be a bug that needs to be addressed.


p.s. @z4nD4R, I use `paho` and Python as well, but whenever something doesn't work, before resorting to `tcpdump` I use `mosquitto_sub` to see if this client doesn't see the message either. This tool is available in the standard repository of Debian and Debian-based distros, it is included in the `mosquitto-clients` package.

**Comment by ashvayka** [comment]
@ralienpp We just don't support binary data yet. I mean we don't parse json integers that are in hex. I don't think we should do this. Json does not support hex integers if I understand this correctly: http://www.json.org/

**Comment by ashvayka** [comment]
@z4nD4R please add feature request as a separate issue with the appropriate name. Thanks!

**Comment by z4nD4R** [comment]
Hi @ralienpp ,

Yes I know that MQTT is data/payload agnostic and therefore I knew it was after all issue with TB itself. I bet I'd see a `java extionption` in `/var/log/thingsboard` which would says that `TB can not processed` incomming MQTT messages and so receiving somehow crash for particular MQTT sessions.

Thx for advise me to use `mosquitto_sub` will look for it.

@ashvayka I didn't send `hex` data as `hex` (kinda confusing but wait) I sent them as `string` aka:
`{"value":"#f58743"}`

after receiving this message MQTT stop sending messages. When I conde this `hex` to `integer` and send it as `integer` aka
`{"value":integer_here}`  it starts working.

Y
