### ISSUE TITLE
MarkerWithLabel cdn link removed

### ISSUE THREAD

**Issue by rajesh-avula** [thingsboard/thingsboard#2065]
CDN link for marker with label is not working which is getting used in google map widget.
URL https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js is removed.

**Comment by Lavhe** [comment]
I fixed it on my local repo by referencing this URL

https://cdn.sobekrepository.org/includes/gmaps-markerwithlabel/1.9.1/gmaps-markerwithlabel-1.9.1.min.js

I dont know if i must open a PR for this fix because it is a personal repository

**Comment by kickstart530** [comment]
https://rawgit.com is closing down soon. 

@Lavhe Is the version earlier supported by rawgit.com was it 1.9.1, how did you determine the version as 1.9.1 for the js library?

Suggested alternatives for gitraw.com is unpkg.com below is the URL for the latest version of google's marker with label Try this URL as well.

https://unpkg.com/@google/markerwithlabel@1.2.3/src/markerwithlabel.js is the latest link for content related to the marketwithlable.js 

Hope this helps

**Comment by lucalav2** [comment]
Hi guys, thanks for your help. 
Do you know how to referencing the above URLs within a Thingsboard widget?
regards

**Comment by vvlladd28** [comment]
Hi guys, thanks for your help. This change added a Thingsboard.

**Comment by arno608rw** [comment]
same error

**Comment by rajesh-avula** [comment]
> Hi guys, thanks for your help.
> Do you know how to referencing the above URLs within a Thingsboard widget?
> regards

I have replaced the url in thingsboard application - google-map.js file. Replace the working url inside this google-map.js while lazy loading the markerwithlabel library. Let me know if you need any help.

Thank you.

**Comment by arno608rw** [comment]
> > Hi guys, thanks for your help.
> > Do you know how to referencing the above URLs within a Thingsboard widget?
> > regards
> 
> I have replaced the url in thingsboard application - google-map.js file. Replace the working url inside this google-map.js while lazy loading the markerwithlabel library. Let me know if you need any help.
> 
> Thank you.

Please update docker thingsboard/tb-postgres

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
