### ISSUE TITLE
Bug at Alarms Count Node 

### ISSUE THREAD

**Issue by kristoss** [thingsboard/thingsboard#2076]
I want to count all the temperature alarms based on the Type Filter.
I configure the node properly but my setting is not saved.So the node counts all the alarms.

![image](https://user-images.githubusercontent.com/49038152/66565169-80b64380-eb6a-11e9-84cd-f84d0c110870.png)

the outcome

![image](https://user-images.githubusercontent.com/49038152/66565199-93307d00-eb6a-11e9-8d5b-87296d4eacf8.png)

**Comment by pfh-pixys** [comment]
I have the same problem with version 2.4.1 TPE

Is it fixed in new version?
Do you have a workaround?

**Comment by kristoss** [comment]
Not a bug
you just need to press enter after typing any filter in order to change the configuration of the node
