### ISSUE TITLE
rule chains - rest api call - missing something in the header/metadata

### ISSUE THREAD

**Issue by woodyjon** [thingsboard/thingsboard#2077]
Hello,

In a rule chains, I successfully use the component "rest api call". But for one of the APIs I must call (an SAP system), I need to use the cookie that is sent by a first request (you make a GET call, you receive a cookie in the header, you use it in a subsequent POST call). The problem is that the cookie is received in the header as an array ("set-cookie"). But the metadata provided in the OUT of the "rest api call" component just provides the first element of that array. See below screenshot.

![image](https://user-images.githubusercontent.com/30724004/66584100-c97af600-eb84-11e9-88a1-75c27ad6b2d4.png)

Normally, the "set-cookie" that is returned in the header should be an array, like below:

```json
{
  "status": 200,
  "statusText": "OK",
  "headers": {
    "content-type": "text/plain; charset=utf-8",
    "content-length": "3",
    "x-csrf-token": "gePXdu7T3RBcj2t6wA3NzQ==",
    "cache-control": "no-cache, no-store",
    "dataserviceversion": "2.0",
    "location": "",
    "c4c-odata-response-time": "224  ms",
    "strict-transport-security": "max-age=31536000; includeSubDomains",
    "set-cookie": [
      "sap-usercontext=sap-client=035; path=/;HttpOnly;Secure",
      "MYSAPSSO2=AjQxMDMBABhLADkAxxxxxq90fl3G637rc%3d; path=/; secure; HttpOnly;HttpOnly;Secure",
      "SAP_SESSIONID_LVE_035=78-KcRktFxxxx6Tka0%3d; path=/; secure; HttpOnly;HttpOnly;Secure"
    ]
  },
```

In postman or nodejs, I successfully use that cookie to make the request, but in this Thingsboard context, I cannot.
Is that a bug, a limitation, or something that I don't get?

Thank you!

**Comment by WilerMS** [comment]
Hi,did you solve it?

**Comment by woodyjon** [comment]
At that time, I did not solve it, I created a proxy server instead. I use the thingsboard rest api node to call my server, and from my server, I create the proper connection with SAP.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
