### ISSUE TITLE
JavaScript Executor Build Error

### ISSUE THREAD

**Issue by jalor-zj** [thingsboard/thingsboard#2084]
Build failed in Ubuntu 16.04. Error message like this:

[INFO] > protobufjs@6.8.8 postinstall /home/zhongjian/workplace/code/mythingsboard/thingsboad/msa/js-executor/node_modules/protobufjs
[INFO] > node scripts/postinstall
[INFO] 
[INFO] 
[INFO] > thingsboard-js-executor@2.4.1 install /home/zhongjian/workplace/code/mythingsboard/thingsboad/msa/js-executor
[INFO] > npm run build-proto && pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js
[INFO] 
[INFO] 
[INFO] > thingsboard-js-executor@2.4.1 build-proto /home/zhongjian/workplace/code/mythingsboard/thingsboad/msa/js-executor
[INFO] > pbjs -t static-module -w commonjs -o ./api/jsinvoke.proto.js ../../application/src/main/proto/jsinvoke.proto
[INFO] 
[ERROR] installing jsdoc@^3.5.5
[ERROR] installing tmp@0.0.33
[ERROR] installing uglify-js@^3.3.25
[ERROR] installing espree@^3.5.4
[INFO] > pkg@4.4.0
[INFO] > Fetching base Node.js binaries to PKG_CACHE_PATH
[INFO] 
[INFO] > Error! ESOCKETTIMEDOUT
[INFO] > Asset not found by direct link:
[INFO]   {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-win-x64"}
[INFO] 
[INFO] > Error! ESOCKETTIMEDOUT
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! thingsboard-js-executor@2.4.1 install: `npm run build-proto && pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js`
[ERROR] npm ERR! Exit status 2
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the thingsboard-js-executor@2.4.1 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/zhongjian/.npm/_logs/2019-10-11T15_33_40_148Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:35 min
[INFO] Finished at: 2019-10-11T23:33:40+08:00

Is anybody get this problem?
[2019-10-11T15_33_40_148Z-debug.log](https://github.com/thingsboard/thingsboard/files/3718480/2019-10-11T15_33_40_148Z-debug.log)

**Comment by longgehao** [comment]
老铁解决了没,我也是这个问题

**Comment by ltppp** [comment]
Hello, your question is obvious. I am a Windows system. In my: **C: \ users \ your username \. PKG cache \ V2.6**, there should be two files (fetched-v10.15.3-linux-x64 and fetched-v10.15.3-win-x64). You should be missing one of the files. You can download the complete installation package from the Internet and place it in the corresponding path. For the sake of safety, you'd better delete the original one, because the original one can be deleted. **Can be incomplete. If you don't find these two files, you can also contact me.**

**Comment by jalor-zj** [comment]
Thank you very much. I solved this problem. But i some ubuntu16.04 I found another problem that:
assert.js:339
    throw err;


AssertionError [ERR_ASSERTION]: Placeholder for not found
        at injectPlaceHolder
        at injectPlaceholders
        at _fs.default.open
        at FSReqWrap.args[as oncomplete] (fs.js:140.20)


I replace pkg tool x10.15.3-linux-x64 and v10.15.3-win-x64 wtih v12.2.0-linux-x64 and v12.2.0-win-x64, then this problem is solved. But in another pc, also using ubuntu 16.04, no this problem. why?






At 2019-10-16 10:34:30, "ltppp" <notifications@github.com> wrote:


Hello, your question is obvious. I am a Windows system. In my: C: \ users \ your username . PKG cache \ V2.6, there should be two files (fetched-v10.15.3-linux-x64 and fetched-v10.15.3-win-x64). You should be missing one of the files. You can download the complete installation package from the Internet and place it in the corresponding path. For the sake of safety, you'd better delete the original one, because the original one can be deleted. Can be incomplete. If you don't find these two files, you can also contact me.

**Comment by jalor-zj** [comment]
> 老铁解决了没,我也是这个问题

解决了，看下 . PKG cache目录是不是没有fetched-v10.15.3-linux-x64 and fetched-v10.15.3-win-x64。没有就到这个https://github.com/zeit/pkg-fetch/releases网站手动下载下来。

**Comment by jalor-zj** [comment]
> Thank you very much. I solved this problem. But i some ubuntu16.04 I found another problem that: assert.js:339 throw err; AssertionError [ERR_ASSERTION]: Placeholder for not found at injectPlaceHolder at injectPlaceholders at _fs.default.open at FSReqWrap.args[as oncomplete] (fs.js:140.20) I replace pkg tool x10.15.3-linux-x64 and v10.15.3-win-x64 wtih v12.2.0-linux-x64 and v12.2.0-win-x64, then this problem is solved. But in another pc, also using ubuntu 16.04, no this problem. why? At 2019-10-16 10:34:30, "ltppp" <notifications@github.com> wrote: Hello, your question is obvious. I am a Windows system. In my: C: \ users \ your username . PKG cache \ V2.6, there should be two files (fetched-v10.15.3-linux-x64 and fetched-v10.15.3-win-x64). You should be missing one of the files. You can download the complete installation package from the Internet and place it in the corresponding path. For the sake of safety, you'd better delete the original one, because the original one can be deleted. Can be incomplete. If you don't find these two files, you can also contact me. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

assert.js:339
throw new errors.AssertionError({
^

AssertionError [ERR_ASSERTION]: Placeholder for not found
at injectPlaceholder (/home/zhongjian/thingsboad/msa/js-executor/node_modules/pkg/lib-es5/producer.js:46:37)
at injectPlaceholders (/home/zhongjian/thingsboad/msa/js-executor/node_modules/pkg/lib-es5/producer.js:66:3)
at /home/zhongjian/thingsboad/msa/js-executor/node_modules/pkg/lib-es5/producer.js:224:9
at FSReqWrap.oncomplete (fs.js:140:20)

**Comment by sww0825521xy** [comment]
Solved 💯 
感谢老铁们 🥇

**Comment by creolive** [comment]
> > 老铁解决了没,我也是这个问题
> 
> 解决了，看下 . PKG cache目录是不是没有fetched-v10.15.3-linux-x64 and fetched-v10.15.3-win-x64。没有就到这个[https://github.com/zeit/pkg-fetch/releases网站手动下载下来。](https://github.com/zeit/pkg-fetch/releases%E7%BD%91%E7%AB%99%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E3%80%82)

i download the two files from the url what your provide,but there named "" and "",and what should i do next step?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
