### ISSUE TITLE
Rule Engine JS sandbox

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/thingsboard#2085]
Currently TB provides a sandbox environment to run rule engine node's code. Although this sounds like a good idea, in practice it causes many issues.

- The default settings seem pretty restrictive. Lot's of people have issues with them. I propose increasing them.
- When a script fails for 3 times, it gets blacklisted. I propose a more "adaptive" system, like: when the scripts fails 3 times **in the last 10mins**, then blacklist it. 3 failures over the _total_ many days of a server's uptime, and over thousands of messages arriving does not sound good.
- Currently it seems that this policy enables malicious users to halt a Thingsboard instance. By sending 3 "malformed" messages, the script gets blacklisted, and all devices are affected. It would be better to provide sandbox limits per device or per customer.
- There should be a way of the system getting automatically restored. In my case, where the first node of the root chain was failing the whole server was essentially stopped. What is the purpose to stop on a _suspected_ problem while creating a new big problem? For example, blacklisted scripts may recover automatically after a few minutes, without manual actions.
- Although there is an option to completely disable the sandbox, it does not sound optimal. It sounds to me more like a work-around to a sub-optimal protection policy, than an actual solution.

Apart from improving the sandbox, there are still cases of actually problematic scripts. In this case the user is not notified about the event. There is no way to know about this issue, rather than just suspecting it, after something failing.

- Blacklisting scripts should be clearly logged on TB log file.
- There should be a notification when a tenant administrator logs in. This will draw their attention to the problem.
- An email notification would me a great, for immediate fixing of the issue.
- A button than clearly restores all blacklisted scripts to normal state would be good. Re-saving the rule chains _didn't reliably restore all scripts for me_.
- An indication on a blacklisted node would be greatly helpful. Like a different outline. Now one has to turn on debugging in all nodes, an manually search for the issue. In big chains this is very inconvenient to say the least.
- When a script gets blacklisted, it would be best to log the failure, regardless of the state of the debug option. Now when something fails, you have to suspect it, enable the debug, wait for the problem to appear again, and then correcting it (if the initial assumption was correct). The information on the initial problem is lost.

**Comment by fjpanag** [comment]
On a quick search, it seems that there are lot's of issues on this matter: #793, #889, #938, #1193, #1274, #1998, #2017.

**Comment by ashvayka** [comment]
Hi @fjpanag . Thank you for the great work of collecting those issues. We will work on this as an improvement in ThingsBoard 3.0 that is scheduled for the start of Q1 2020. We plan to make all the improvements you have mentioned.

**Comment by ashvayka** [comment]
Hi @fjpanag . This is a short notice that we plan to implement all the improvements in v2.5

**Comment by fjpanag** [comment]
Hi @ashvayka , thank you for these improvements.
I just updated to v2.5 and indeed the instance can now recover from blacklisted nodes.

Before closing the issue though, I have a couple of questions:

1. For a script to be blacklisted, does it have to fail 3 times in general, or 3 times within 60secs? (assuming the default settings).

2. Is it still possible to attack a Thingsboard instance by sending wrong requests? I mean, the blacklist is still per instance, or it is now per originator?

3. Now what are the means for me as a tenant administrator to diagnose such an issue?

**Comment by hallard** [comment]
@fjpanag 
thanks for the update.

what do you mean by `indeed the instance can now recover from blacklisted nodes` sounds good,
How does this works? Is there a documentation to look for?
Thanks

**Comment by Ultrazombie** [comment]
Closed due to inactivity
