### ISSUE TITLE
Webcamera input

### ISSUE THREAD

**Issue by colognebroker** [thingsboard/thingsboard#2090]
What kind of url string is needed to display cam?
rsp
http
or what else ?

for me it did not work to store the url in an attribute of an asset ?
it did not show anything

**Comment by vvlladd28** [comment]
Hello, this widget uses to add a photo to the TB. The widget uses a camera, at the device from an open TB, to take photo.

**Comment by colognebroker** [comment]
oh thank you, i missunderstood the function.
i love thingsboard…
