### ISSUE TITLE
Closing current session due to invalid msg order

### ISSUE THREAD

**Issue by anlostsheep** [thingsboard/thingsboard#2092]
Hi,recently I have some problems with MQTT: I have a Respberry Pi 3.5 and I run python script on it to collect sounds and upload result telemetry to the Thingsboard ，here is the code for the python script :

```
import paho.mqtt.client as mqtt
import os, time, json,sys,socket,base64
import requests
sys.path.append('/home/pi/paho.mqtt.python/src/')
from mel_code import model_class
from configparser import ConfigParser
import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

ENCODING = 'utf-8'
print(sys.path)
cfg = ConfigParser()
cfg.read('/home/pi/paho.mqtt.python/src/voice/device_config.cfg')
cfg.read('device_config.cfg')
host = cfg.get('address', 'host')
port = cfg.getint('address', 'port')
audio_path = cfg.get('checking', 'audio_path')
audio_upload_url = cfg.get('checking', 'audio_upload_url')

whether_send_audio = cfg.getboolean('common', 'whether_send_audio')

voice_status = {"0": "NORMAL", "3": "BELT_MALFUNCTION", "4": "PILLOW_MALFUNCTION", "2": "WHITE_NOISE", "1": "MALFUNCTION"}

keep_alive = 60

access_token = cfg.get('address', 'access_token')

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))


def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))


def getserial():
    # Extract serial from cpuinfo file
    cpu_serial = "0000000000000000"
    try:
        f = open('/proc/cpuinfo', 'r')
        for line in f:
            if line[0:6] == 'Serial':
                cpu_serial = line[10:26]
        f.close()
    except:
        cpu_serial = "ERROR000000000"

    return cpu_serial


serial_number = getserial()


def publish_message(tile,payload,qos):
    current_time = time.strftime("%Y%m%d%H%M%S", time.localtime())

    print(payload)
    client = mqtt.Client(serial_number+current_time)
    client.enable_logger(logger)
    client.on_connect = on_connect
    client.on_message = on_message
    client.username_pw_set(access_token)
    client.connect(host, port, keep_alive)
    print(payload)
    client.publish(tile, payload=payload, qos=qos)
    time.sleep(0.1)
    client.loop_start()
    client.disconnect()


def send_data_to_server(audio_path, file_name, transfer_file_name):

    print("Start to upload audio file ")
    f = open(audio_path + file_name, "rb")
    audio_data = f.read()
    audio_bytes = bytearray(audio_data)

    multipart_form_data = {
        'file': (str(transfer_file_name), audio_bytes),
        'originalFilename': ('', str(transfer_file_name)),
    }
    response = requests.post(audio_upload_url + '/v1/sensor/audio', files=multipart_form_data)
    print(response.status_code)


def record_sound(input_audio_path, audio_name):
    ##获取当前时间
    audio_file_whole_path = input_audio_path + audio_name
    # 录制声音
    os.system("arecord -d 20 -f cd -c 1 -t wav " + audio_file_whole_path)
    return audio_file_whole_path


def publish_audio_file():
    current_time = time.strftime("%Y%m%d%H%M%S", time.localtime())
    audio_name = current_time + '.wav'
    audio_ab_path = record_sound(audio_path,audio_name)
    f = open(audio_ab_path, "rb")
    #f = open("/home/pi/record/test.txt","rb")
    audio_data = f.read()
    audio_bytes = bytes(audio_data)
    #publish_message("voice/audio", audio_bytes, 0)
    publish_message("v1/devices/me/telemetry", audio_bytes, 0)
    f.close()


def get_host_ip():
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(('8.8.8.8', 80))
            ip = s.getsockname()[0]
        finally:
            s.close()
                                                     
        return ip


def get_voice_status(status):
    if status == 1:
        return voice_status['1']
    elif status == 0:
        return voice_status['0']
    elif status == 2:
        return voice_status['2']
    elif status == 3:
        return voice_status['3']
    elif status == 4:
        return voice_status['4']
    else:
        return voice_status['1']


def public_warning_message():
    ai_engine_module = model_class.AudioModel()

    current_time = time.strftime("%Y%m%d%H%M%S", time.localtime())
    audio_name = current_time + '.wav'
    audio_ab_path = record_sound(audio_path, audio_name)
    status = ai_engine_module.predict(audio_ab_path)
    print("Ai Response" + str(status))

    voice_type = get_voice_status(status)
    transfer_file_name = current_time + '_' + voice_type + '_' + serial_number + '.wav'

    if whether_send_audio:
        send_data_to_server(audio_path, audio_name, transfer_file_name)

    ip = get_host_ip()
    message = json.dumps({"deviceSerialNo": serial_number, "ip": ip, "status": status, 'file_name': str(transfer_file_name)})
    publish_message("v1/devices/me/telemetry", message, 1)


if __name__ == "__main__":
    #publish_message("sensor", "Hello Broker ", 0)
    #publish_audio_file()
    public_warning_message()
```

I'm sure it can successfully upload the data in the 2.3.9 snapshot version, here is the history data:
![image](https://user-images.githubusercontent.com/45201628/66799412-7bc70a80-ef43-11e9-968f-96c60750ed63.png)

now I update to 2.4.1-release version, thingsboard can not recive the telemetry，here is the logs:
![image](https://user-images.githubusercontent.com/45201628/66799288-1410bf80-ef43-11e9-89a3-6368d58e321e.png)

I don't know why he shut down sessions for no reason
If anyone has had the same problem as me, please tell me

**Comment by LaszloMorzsa** [comment]
Hi, do you have solution for this problem? I have same situation after upgrading Thingsboard.

**Comment by yamt** [comment]
i saw this with MQTT-C. (https://github.com/LiamBindle/MQTT-C)
it seems that this happens when a client sends other control messages (in my case, SUBSCRIBE) without waiting for CONNACK.
if i read the mqtt spec correctly, the client behaviour is explicitly allowed.
this should be fixed in thingsboard.

from http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718032
> Clients are allowed to send further Control Packets immediately after sending a CONNECT Packet; Clients need not wait for a CONNACK Packet to arrive from the Server.

**Comment by wanZzz6** [comment]
Just add `time.sleep(1)`  after your `client.connect()`👌

**Comment by piqueza** [comment]
> Just add `time.sleep(1)` after your `client.connect()`

You saved my sanity. Thank you, can confirm this works for me. Will play with shorter intervals, right after I have watched the Spacex launch.

**Comment by piqueza** [comment]
> > Just add `time.sleep(1)` after your `client.connect()`
> 
> You saved my sanity. Thank you, can confirm this works for me. Will play with shorter intervals, right after I have watched the Spacex launch.



> Hi, do you have solution for this problem? I have same situation after upgrading Thingsboard.

Solution is a time.sleep(1) (down to 0.03). It shouldn't be the proper solution IMO, but it works until the platform has a fix. Thanks to @wanZzz6 for suggesting the solution.

**Comment by ashvayka** [comment]
I was reviewing the standard today. And indeed, the client has a right to send publish packages even if the CONACK was not received. Although there is no specification on how much messages platform should store while it is processing the connection request. Please correct me if I am wrong. We will plan the improvement to store a configurable amount of messages while we are processing the CONNECT request. I suspect the number of messages (control packets) will be less than 100. 

Also, I must admit that this behavior sounds weird to me. Why would the client send the data if the connection is not acknowledged yet? But obviously, we should obey the standard. 

While reviewing the code I suggest two improvements:

1) You may send the "publish" in the "on_connect" method. When you are sure that the client is connected. This saves bandwidth.

2) Are you sending the data infrequently? If yes it is ok, but if you send data often, it is much better to keep the connection open.
Otherwise, there is no advantage to use MQTT comparing to HTTP 

3) if your data file is large, you should change the settings to accept larger messages in ThingsBoard. See

transport.mqtt.netty.max_payload_size | NETTY_MAX_PAYLOAD_SIZE | 65536

from config https://thingsboard.io/docs/user-guide/install/config/

**Comment by piqueza** [comment]
> 
> Also, I must admit that this behavior sounds weird to me. Why would the client send the data if the connection is not acknowledged yet? But obviously, we should obey the standard.
> 

This part makes sense with some IOT devices that are configured for send only. A possible use case is a livestock management where all you want is the unit to send a packet periodically with minimal info such as last associated beacon or maybe ambient temperature.

In South African in the Karoo some farmers would use something like this to monitor a water trough that is maybe 100miles away that only sends the water level out three times a day, and the unit does not check if the packet is received, it just sends the info over gprs and checking for responses over an already slow connection where it is not needed for the IOT device to know if its message is received just plonking the message to the IOT gateway makes sense. If no notifications come through the gateway  informs the farmer, not the IOT device. They sometimes run on a tiny solar panel and battery for years with little to no human interaction.

**Comment by ashvayka** [comment]
@piqueza it would be interesting to calculate network traffic consumed by such application with different protocols used. I am quite sure that even HTTP would be more efficient in this case. CoAP - for sure.
