### ISSUE TITLE
why AccessValidator is using singleThreadExecutor

### ISSUE THREAD

**Issue by lilianbiao** [thingsboard/thingsboard#2093]
i found TelemetryController used AccessValidator, and    executor ( props of AccessValidator)  is defined  as SingleThreadExecutor.
the problem is that  when multi-request to save attribute or read, only one thread is working!
does anyone konw where design like this?

**Comment by vparomskiy** [comment]
I don't think that it will lead to significant performance problems in real-life scenarios because this single thread is only used only for handling responses from the Service layer.
AccessValidator performs validation in request's thread (it is not single-threaded validation), then submit request to the Service layer. Once response is ready, that single thread is used for transferring data from the Service to the Response channel.
 It may be an issue if you have hundred thousands concurrent Rest requests, and that is not true most cases

**Comment by lilianbiao** [comment]
thx @vparomskiy!

**Comment by lilianbiao** [comment]
is that means  there were 3 thread for handling this one request?
1) request's thread issued by http
2)service's thread issued by using future
3) validator's thread issued by executor for transfer  result to response

**Comment by jettzhan** [comment]
我有同样的疑惑，比如我调用TelemetryController#getTimeseries 接口，虽然校验过程是由请求线程处理了，但是查询ts_kv中的数据，却是由单线程池AccessValidator  来处理的。一旦这个接口请求是一个大查询任务，会影响其他的请求的正常处理吧。

I have the same concern. For example, when I call the TelemetryController#getTimeseries interface, although the validation process is handled by the request thread, the query for data in ts_kv is processed by the single-threaded pool AccessValidator. If this interface request involves a large query task, it will affect the normal processing of other requests, right?

```sh
curl --location --request GET 'http://localhost:8080/api/plugins/telemetry/DEVICE/3a0c2940-f054-11f0-8199-bfaeb1fd30a3/values/timeseries?keys=temperature&startTs=0&endTs=1770194559000' \
--header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW1vQHRoaW5nc2JvYXJkLm9yZyIsInVzZXJJZCI6IjhhMGUzYzgwLThkZjgtMTFmMC1hYjM0LTRmMDJmMGNmNjg1YyIsInNjb3BlcyI6WyJURU5BTlRfQURNSU4iXSwic2Vzc2lvbklkIjoiM2IxOWNlMWItNWZiNy00NGQ0LTg1YzQtNjBlZTFjY2RhNDM2IiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE3NzE5MjMwNTYsImV4cCI6MTc3MTkzMjA1NiwiZW5hYmxlZCI6dHJ1ZSwiaXNQdWJsaWMiOmZhbHNlLCJ0ZW5hbnRJZCI6IjY3ZTQ4MjQwLThkZjgtMTFmMC1hYjM0LTRmMDJmMGNmNjg1YyIsImN1c3RvbWVySWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAifQ.MjlyNGpnf_UTMzKvWU-IT8qSVyrIixzXymkIPfk9jkcoQOblJKEEho-BuZ8ahlY7yHyLT4vogHmJYt1es1F8Dw'
```

```txt
2026-02-24 18:22:04,260 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-1 [TS Latest] queueSize [0] totalAdded [6] totalSaved [6] totalFailed [0]
2026-02-24 18:22:38,542 [access-validator-31-thread-1] DEBUG org.hibernate.SQL - SELECT * FROM ts_kv WHERE entity_id = ? AND key = ? AND ts >= ? AND ts < ?  order by ts desc limit ?
2026-02-24 18:22:44,187 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-1 [TS] queueSize [0] totalAdded [7] totalSaved [7] totalFailed [0]
```
