### ISSUE TITLE
RPC Button Widget - Method Params with Variables

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#2098]
Hello there,

I'm currently trying to use TB Variables within the "RPC method params" section of the RPC Button Widget e.g.:
`{"entity": ${entityName}}`

The console output is:
`{"entity": ${entityName}}`

Therefore it's not working as I expected and variable values are not inserted.

Is there another way to get use of variables in that use-case?

Thanks in advance

**Comment by TheClockwork9438** [comment]
Hi, I have the same issue here, can you help me in case you figure it out the solution
