### ISSUE TITLE
Where is the "assign devices" button?

### ISSUE THREAD

**Issue by Tasosgi** [thingsboard/thingsboard#2102]
I try to assign devices to a customer as I can see at Thingsboard PE "Entity Groups" video tutorial. I can not found the button "assign devices" in the device groups tabs. In my case there is a button named "change owner" .

![assign](https://user-images.githubusercontent.com/31473443/67008898-2a5d7d80-f0f3-11e9-926c-fa3fd06663c1.png)

I am trying to use the rule chain enrichment "customer attributes" so I must can assign a device to a customer.

**Comment by vvlladd28** [comment]
Hello, functional "assign devices" supported the only Thingboard CE. In the  Thingboard PE, you need to be used "change owner".

**Comment by Tasosgi** [comment]
So how can I use the rule chain enrichment “assign devices” if I can’t assign a device to a customer as I can see here https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/   ? I have already tried it with  the “change owner” but it seems not to work.

**Comment by ashvayka** [comment]
The "Change Owner" in TB PE is the same as "Assign to Customer" in TB CE. The difference is that in TB PE you can assign/change owner to Sub-Customer or back to Tenant.
