### ISSUE TITLE
telemetry upload problem

### ISSUE THREAD

**Issue by micnori** [thingsboard/thingsboard#2103]
Hi!
If I try to publish via MQTT a simple telemetry object like this:
```
var dataObj = {"data":"000012300007"};
var dataJson = JSON.stringify(dataObj);
thingsBoard.publish('v1/devices/me/telemetry', dataJson, ...)
```

When I try to read the telemetry I get this:
```
{
  "data": [
    {
      "ts": 1571322569016,
      "value": "12300007"
    }
  ]
}
```
What happens? Why TB has stripped out the initial 0 from a string?
I'm using TB community edition 2.4.1

Thanks,
Michele

**Comment by magicgw0928** [comment]
I also find this issue. It looks like "000012300007" is recognized as an Integer value by MQTT Transport, so the result is "000012300007" convert to 12300007 and being stored in database.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
