### ISSUE TITLE
Cluster setup recommendation for monolithic architecture

### ISSUE THREAD

**Issue by absolut777** [thingsboard/thingsboard#2104]
Hello guys,

I'm going to deploy TB cluster (3 nodes, DB - cassandra) with monolithic architecture and faced with lack of detail recommendation about this type of installation. My questions:

1. ZK is mandatory or TB cluster can work without ZK?
2. Have I swith cache from Coffein to Redis for cluster setup?
3. If Redis is required can I use Redis Setienel for redis cluster setup? Or I have to use standalone redis/cofein on every cluster node.

Would be greatly appreciated for clarification.

**Comment by xujingzhou** [comment]
I have the same problem. In addition, how can multiple tb-gateway connect to a thingsboard node?

**Comment by Ultrazombie** [comment]
Please read our installation setups and performance test article:
https://thingsboard.io/docs/user-guide/install/cluster-setup/
https://thingsboard.io/docs/reference/performance-aws-instances/
