### ISSUE TITLE
Installation failed on centos with postgresql

### ISSUE THREAD

**Issue by ybwin** [thingsboard/thingsboard#2107]
10:12:09,723 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:12:09,725 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:12:09,725 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
10:12:09,728 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
10:12:09,728 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.3.1.jar!/logback.xml]
10:12:09,728 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
10:12:09,907 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:12:09,909 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:12:09,931 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
10:12:09,958 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - setting totalSizeCap to 3 GB
10:12:09,969 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - Archive files will be limited to [100 MB] each.
10:12:10,021 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - No compression will be used
10:12:10,025 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1401420256 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
10:12:10,029 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
10:12:10,029 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - Roll-over at midnight.
10:12:10,032 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6e5e91e4 - Setting initial period to Fri Oct 18 10:52:30 CST 2019
10:12:10,037 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:12:10,093 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
10:12:10,094 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
10:12:10,102 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
10:12:10,102 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
10:12:10,102 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:12:10,102 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
10:12:10,103 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:12:10,104 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2cdf8d8a - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.3.1)
 ===================================================

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ThingsBoard installation failed!

**Comment by ashvayka** [comment]
Starting ThingsBoard 2.5.1 we support CentOS8 installation and this bug is fixed.
