### ISSUE TITLE
tb-gateway (Over 1000 devices, the message backlog gets worse.)

### ISSUE THREAD

**Issue by xujingzhou** [thingsboard/thingsboard#2109]
Hi, In tb-gateway, the message backlog increases(/usr/share/tb-gateway/bin/storage/Tenant) as more than 1,000 devices are concurrent.  so, how should I scale-out mosquitto and tb-gateway, even to a thingsboard node.

**Comment by Ultrazombie** [comment]
Please use this issue page for question about gateway
https://github.com/thingsboard/thingsboard-gateway/issues
