### ISSUE TITLE
Telemetry upload doesn't work with HTTP API

### ISSUE THREAD

**Issue by techfriendly** [thingsboard/thingsboard#2110]
Hi all,

I successfully updated device attributes through POST, but I can not get any result when updating telemetry data.

I get a 200 status and then I see the update of data in TB:

**POST(url="http://localhost:8080/api/v1/prueba_script/attributes",body="{\"temperatura_2\":4}")**

I get a 200 status but there is no update on telemetry data:

**POST(url="http://localhost:8080/api/v1/prueba_script/telemetry",body="{\"temperatura_2\":4}")**

Any idea?

Thanks in advance

**Comment by gpellejero** [comment]
I forgot to say that everything works on demo.thingsboard.io but fails in my cloud server.

**Comment by Lavhe** [comment]
Is your server running in SSL mode?

Is the certificate self assigned?

I ran into this problem then i make the requests as **http** instead of **https** then it worked

**Comment by Karabiy** [comment]
are you using the nginx for the proxy?
