### ISSUE TITLE
how post video streaming to TB

### ISSUE THREAD

**Issue by m0o0** [thingsboard/thingsboard#2111]
What is the best solution for sending video to TB without using an ip camera and using external rstp rtmp http servers?
So far I've been able to take photos at a specific time and upload them to an external web server and save them to TB using the php script.
I've also used the nabto platform in this case.
But i need help with uploading video to external server with php script.
Thanks for your guidance

**Comment by Ultrazombie** [comment]
Please use iframe option,
e.g. 
```
<div class='card'>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/2yWhvBkEyaY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
</div>
```

**Comment by ezeroldan24** [comment]
Good day, that solution did not work for me, someone found a way to do it? Thanks a lot
