### ISSUE TITLE
Protobuf decoding

### ISSUE THREAD

**Issue by DavidMicallef86** [thingsboard/thingsboard#2119]
Hi,  Our sensors send data encoded using protocol buffers.  In Node.js there are several libraries we can use to decode these.  Are then any suggested ways of decoding protobuf in the 'data converters' section?  currently I am decoding it by reverse engineering the protocol buffer format but its not that ideal.

Thanks

**Comment by ashvayka** [comment]
Try decoding the message in the custom integration. Protobuf has nice ability to convert binary method to JSON. See https://thingsboard.io/docs/user-guide/integrations/custom/. If this does not work for your case, please reply to this thread.

**Comment by hailianglone** [comment]
CE VERSION,  How to operate？ i see intergrations in  PE .

**Comment by ashvayka** [comment]
Since ThingsBoard 3.2, the platform supports custom MQTT topics and Protobuf payload type. This is configurable via [device profiles](https://thingsboard.io/docs/user-guide/device-profiles/#mqtt-device-payload).
