### ISSUE TITLE
mqtt-ssl-java-client-tests

### ISSUE THREAD

**Issue by sad00731** [thingsboard/thingsboard#2121]
hello, I successfully connected to the server that is running MQTT over SSL using the sample two-way-mqtt-ssl-client python client code in thingsboard.io.But I wonder if anybody have tried the java client? I have to connect to thingsboard which is running mqtt over ssl using a java  client (two-way-ssl) because of bussiness needs and I struggled with it for days still got the error "peer not authenticated"

**Comment by sad00731** [comment]
@ashvayka now problem is sloved on premise but once deployed on cloud in microservice architecture ,I got the same error again "peer not authenticated"

**Comment by Karabiy** [comment]
make sure that you have configured everything properly regarding those. it should be okay same as for the python.
