### ISSUE TITLE
Custom Widget Actions

### ISSUE THREAD

**Issue by Lemior** [thingsboard/thingsboard#2122]
Hi
currently im creating my ow widget and it works all fine, but now i want to add an "on row click" action. I have done it like in the entity table. When i click on a row, nothing happens.

I tried to find the error so i created a widget which displays the datasources structure.
With my widget it looks like this:
[{"type":"entity","dataKeys":[],"entityAliasId":"d306aa9b-f96d-6557-f070-2ab424cc8cf3","aliasName":"Current Device","unresolvedStateEntity":true,"name":"Unresolved","entityName":"Unresolved"}]

With the normal entity widget:
[{"type":"entity","dataKeys":[],"entityAliasId":"d306aa9b-f96d-6557-f070-2ab424cc8cf3","aliasName":"Current Device","entity":{"id":{"entityType":"DEVICE","id":"be8538c0-f4c4-11e9-81f1-fff620052eca"},"createdTime":1571746145868,"additionalInfo":null,"tenantId":{"entityType":"TENANT","id":"b26c2160-eb51-11e9-846f-95de06a26055"},"customerId":{"entityType":"CUSTOMER","id":"13814000-1dd2-11b2-8080-808080808080"},"name":"12--0","type":"default","label":null},"entityId":"be8538c0-f4c4-11e9-81f1-fff620052eca","entityType":"DEVICE","entityName":"12--0","entityLabel":"","name":"12--0","entityDescription":""}]

So now is my question: What have i done wrong?

HTML:
```
<md-table-container>
    <table md-table>
        <thead md-head>
            <tr md-row>
                <th md-column><input type="number" ng-model="ProjectId" ng-change="CreateFilter(ProjectId, StationId)"></th>
                <th md-column><input type="number" ng-model="StationId" ng-change="CreateFilter(ProjectId, StationId)"></th>
            </tr>
        </thead>
        <tbody md-body>
            <tr ng-click="onRowClick($event, x)" ng-repeat="x in stations | filter: filter : true | limitTo: query.limit : (query.page -1) * query.limit">
                <td>{{x.project_id}}</td> 
                <td>{{x.station_id}}</td>
            </tr>
        </tbody>
    </table>
</md-table-container>
<md-table-pagination md-limit="query.limit" md-limit-options="query.limitOptions" md-page="query.page" md-total="{{stations.length}}" md-page-select="options.pageSelect" md-boundary-links="options.boundaryLinks">
</md-table-pagination>
```

JS:
`let $scope;

self.onInit = function(){
    $scope = self.ctx.$scope;
    $scope.stations = [];
    $scope.counter = 0;
    $scope.filter = {};
    
    PushStationIntoArray(0,self.ctx.datasources.length);
    
    $scope.CreateFilter = function(projectid, stationid){
        var temp_filter = {};
        if(typeof projectid === 'number'){
            temp_filter.project_id = projectid;
        }
        if(typeof stationid === 'number'){
            temp_filter.station_id = stationid;
        }
        $scope.filter = temp_filter;
    }
    
    $scope.onRowClick = function($event, x){
        var actionSourceId = 'rowClick';
        var descriptors = self.ctx.actionsApi.getActionDescriptors(actionSourceId);
        var entityId = self.ctx.datasources[x.array_position].entityId;
        var entityName = self.ctx.datasources[x.array_position].entityName
        self.ctx.actionsApi.handleWidgetAction($event, descriptors[0], entityId, entityName);
    }
    
    
    $scope.query = {
        page: 1,
        limit: 30,
        limitOptions: [5, 10, 15, 20, 25, 30],
        order: 'station_id'
    }
    $scope.options = {
        boundaryLinks: false,
        pageSelect: true
    };
}

self.typeParameters = function() {
    return {
        maxDatasources: 2,
        dataKeysOptional: true
    };
}

self.actionSources = function() {
    return {
        'rowClick': {
            name: 'widget-action.row-click',
            multiple: false
        }
    };
}

PushStationIntoArray = function(OldStationCount, NewStationCount){
    for(var station_counter = OldStationCount; station_counter < NewStationCount; station_counter++){
        var temp_array = self.ctx.datasources[station_counter].entityName.toString().split("--");
        var temp_object = {
            project_id: parseInt(temp_array[0]),
            station_id: parseInt(temp_array[1]),
            array_position: station_counter
        };
        //if(isNaN(temp_object.station_id) === false){
            $scope.stations.push(temp_object);
        //}
    }
}

**Comment by Bliph** [comment]
Please note that 'entityId' is a object (and not a string). I spent some hours debugging until i discovered this...:

```
entityId = {
  entityType: "ASSET",
  id: "77201a80-f650-11e9-b541-f7e1c0b2cc8f"
}
```

There are 2 ways (at least) to open a new state from a custom widget:

Solution 1:
```
self.onInit = function()
{
....
....
  $scope.onEntityClick = function($event, xxxxx) 
  {
    if ($event)  { $event.stopPropagation(); }

    var descriptors = ctx.actionsApi.getActionDescriptors('rowClick');
    if (descriptors.length) 
    {
      var entityId = <get the ID from somwhere>;
      var entityName = <get the ID from somwhere>;
      self.ctx.actionsApi.handleWidgetAction($event, descriptors[0], entityId, entityName);  
    }
  }
}
```
Solution 2:
```
self.onInit = function()
{
....
....
  $scope.onEntityClick = function($event, xxxxx) 
  {
    if ($event)  { $event.stopPropagation(); }
 
    var descriptors = ctx.actionsApi.getActionDescriptors('rowClick');
    if (descriptors.length) 
    {
      var entityId = <get the ID from somwhere>;
      var entityName = <get the ID from somwhere>;
      var params = {
        entityId: entityId,
        entityName: entityName
      };
  
      ctx.stateController.openState('current_entity', params, false);
    }
  }
}
```

In addition, you have to enable the action to the widget config:
```
self.actionSources = function() 
{
  return {
    'rowClick':  {
      name: 'widget-action.row-click',
      multiple: false
    }
 };
}
```

**Comment by Lemior** [comment]
Thank you. It worked
