### ISSUE TITLE
Hide white-labeling menu option

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2123]
Hello!

We use the PE Version of Thingsboard. For some of our customers we want to adjust the menu. This also means hiding the white-labeling menu. Some customers could white labeling login domain (if they don't know what that means for example).

Unfortunately I can't hide the "white-labeling" menu. How can I achieve that?

Thanks!
Michael

**Comment by enviroeye** [comment]
In the Custom Menu option you need to disable all the sub items of the White Labeling menu option, then it disappears (see json below). You can also do it from the system tenant where you are able to edit the white labeling attributes for each of your tenants. If you disable the custom menu item in your tenant the only way to turn it back on is through the tenant's attribute in the system tenant (or you can do it via the TB API).

{
  "disabledMenuItems": [
    "home",
    "-rule_chains",
    "-integrations",
    "-converters",
    "-roles",
    "entity_view_groups",
    "-customers_hierarchy",
    "-user_groups",
    "-customer_groups",
    "-asset_groups",
    "-device_groups",
    "-dashboard_groups",
    "-scheduler",
    "audit_log",
    "-widget_library",
    **"mail_server",
    "white_labeling",
    "mail_templates",
    "custom_translation",
    "custom_menu",
    "login_white_labeling"**
  ],

**Comment by hamburml** [comment]
Thanks, I'll try that!

**Comment by ts4iot** [comment]
@enviroeye : Could you please add the identifier for **"OTA update"** and **"System settings"** to this very helpfull thread.
Thanks

**Comment by tingznet** [comment]
@ts4iot if you disable the following you can make System Settings invisible.
    "sms_provider",
    "self_registration",
    "resources_library",
I couldn't find the identifier for "**OTA Update**" too.

**Comment by ts4iot** [comment]
For OTA Update it is "otaUpdates"
