### ISSUE TITLE
How "cell content function" work?

### ISSUE THREAD

**Issue by harikrishna6050** [thingsboard/thingsboard#2124]

**Comment by RondoRonaldo** [comment]
By using this feature it is possible to change values that are displayed on a widget depending on logic in this function.
Here is an example:
![image](https://user-images.githubusercontent.com/43723966/88902155-7b8dc680-d25a-11ea-9b5a-4d941d862656.png)

**Comment by harikrishna6050** [comment]
tq@Andrey Tkachenko RondoRonaldo
