### ISSUE TITLE
User relations

### ISSUE THREAD

**Issue by rascove** [thingsboard/thingsboard#2126]
Is it possible for us to have a relations from Device or Asset to User, not only to Customer. In my scenario, I'd like to assign a Device to a particular User, both of these are assigned to the same Customer. I've successfully added this relation using Thingsboard REST API through Swagger-UI, but it'll be nicer if we can do this directly through web UI. It's also not possible to edit this relationship once we've created them.

![part1](https://user-images.githubusercontent.com/11934395/67650165-ce0e1f80-f976-11e9-9d50-860b5e0dc3cd.png)

![part2](https://user-images.githubusercontent.com/11934395/67650164-cd758900-f976-11e9-9d20-2ddebc60448b.png)

**Comment by PovitruliaV** [comment]
Hi @rascove,
Is this issue still relevant?
In the newer version of Thingsboard, we have an opportunity to create relations between Users and the devices directly in the WEB-UI
![image](https://user-images.githubusercontent.com/98046079/182903256-0f0b364a-47ba-4281-b5c9-a2591dcffdfb.png)
Regards,
