### ISSUE TITLE
Q: Control/Last value widget.

### ISSUE THREAD

**Issue by z4nD4R** [thingsboard/thingsboard#213]
Hello All,

I'd like to ask question how to create widget which will show the latest value (aka slidebar for brightness %) but also make it also control widget and so when I move the slidebar I can send MQTT topic back to device.

I created last value widget, but when I move I got exception saying me that `sendOneWayCommand()` function (provided by `self.ctx.controlapi` in control widgets) is `Unknow`.

I believe this is because how the widget is proposed, but I'd like to ask you how to overcome this limitation?

Thank you.

Y

**Comment by ashvayka** [comment]
Use `self.ctx.controlApi` instead of `self.ctx.controlapi`

**Comment by z4nD4R** [comment]
Hi @ashvayka,

such a stupid mistake. Thnak you for correcting me ;).

Although there is no error in `js` or in widget operaetion the message send out is not reaching my `RPi`. This is quiete interresting as message sending out via another widget with the same method is reaching just fine.

Need to dig deeper ;) 

Thank you anyway.

Y
