### ISSUE TITLE
get user info in custom widget

### ISSUE THREAD

**Issue by woodyjon** [thingsboard/thingsboard#2130]
Hello,

I am developing custom widgets and would like to know if it is possible within the widget to get info on the connected user?

My custom widget allows users to manually submit telemetry data. I would like to attach the name of the user to the telemetry data.

Thanks a lot

**Comment by Terny22** [comment]
Hi woodyjon,

You will need to use "userService" in order to get info about the current user. You can inject "userService" using "$injector", that is located in a $scope object.

```
self.onInit = function() {
  let $scope = self.ctx.$scope;
  let userService = $scope.$injector.get('userService');
  let currentUser = userService.getCurrentUser();
  ...
}

```

**Comment by woodyjon** [comment]
Thanks, that works perfectly. Awesome.
Thanks a lot.

**Comment by Karabiy** [comment]
ThingsBoard 3.x version update 
```let localStorage = window.localStorage;
let currentUser = parseJwt(localStorage["jwt_token"]);
self.onInit = function() {
    console.log(self);
    self
        .ctx
        .userService
        .getUser(currentUser.userId)
        .toPromise()
        .then(function(response){
            console.log(response);
        })
}
function parseJwt (token) {
    var base64Url = token.split('.')[1];
    var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    var jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
    return JSON.parse(jsonPayload);
};

**Comment by hjlopezr** [comment]
@Karabiy with userService, can i get the user of customer? how?
