### ISSUE TITLE
Dynamically adjust Entity View period using Rule Chain

### ISSUE THREAD

**Issue by rascove** [thingsboard/thingsboard#2131]
Hi, is it possible to dynamically adjust the start and end date and time for an Entity View using rule chain? For example, after a device sends certain telemetry reading with specific value, the previous telemetry readings shown in the dashboard through Entity Views are no longer visible.

**Comment by PovitruliaV** [comment]
Hi @rascove,
ThingsBoard does not provide such an opportunity. Start and end time - represents the time interval that is used to limit access to target device telemetry. Customer will not be able to see entity telemetry that is outside the specified interval. 
Regards,
