### ISSUE TITLE
Language selection in profile doesn't change units in Dashboard-Timewindow 

### ISSUE THREAD

**Issue by drevil31** [thingsboard/thingsboard#2134]
The issue can be reproduced for example on the demo server by following the steps:
1. Log In onto the demo server
2. Open a dashboard and on the dashboard the timewindow-panel
3. Go to profile
4. Change the language
5. Go to a dashboard and to the timewindow
6. You can see the units in the wrong language

The problem is once the timewindow initializes its units, they stay that way until a page refresh.
If you dont open the timewindow before changing the language everything works as aspected.

**Comment by PovitruliaV** [comment]
Hi @drevil31,
Is this issue still relevant?
