### ISSUE TITLE
Swagger Document Broken

### ISSUE THREAD

**Issue by stephanfr** [thingsboard/thingsboard#2140]
The Swagger API Document is broken for a large number of APIs.  The most serious issue appears to be that the query parameters are included in the path.  Every call with a query parameter in the path fails.

Is there a workaround we are missing ?  I see several other similar references in the github issues.  

Perhaps it would be better to simply remove the Swagger Document until this is fixed as codegen will happily generate incorrect clients which include queries in the path which fail at runtime.

**Comment by Karabiy** [comment]
please specify which exact APIs are broken for those
also, specify which exact parameters are being set incorrect
