### ISSUE TITLE
OPC UA Integration Problem

### ISSUE THREAD

**Issue by czzbzz** [thingsboard/thingsboard#2143]
I am using Thingsboard PE. I tried to receive data from OPC-UA Server using OPC-UA Integration Module. I followed this link (https://thingsboard.io/docs/user-guide/integrations/opc-ua/).

In this guide everything is explained very well. I installed OPC-UA Demo Server , create Uplink - Downlink in Data Converters Tab and create OPC-UA Integration. After what I've done, Thingsboard got to create 10 airconditioner devices automatically but it didn't.

I debugged the OPC-UA Integration module but nothing happened in debug page. Actually there is a connection between Thingsboard and OPC-UA Server. I checked this with WireShark software. Before this integration, I made MQTT Integration and it worked. I think there is a problem in OPC-UA Integration.

Is there anyone who are using OPC-UA Integration? Could you help me please?

Thank you.

**Comment by Alexander-protocal** [comment]
Hello,

I'm having problems too with OPCUA the telemetry data is working, but not the attributes commands.
Anyone can help ?

**Comment by den1jkee** [comment]
Hello, try this integration on the lastest versions of Thingsboard. We did a lot of improvements and bug fixes for that.
Best regards,
Denys.
