### ISSUE TITLE
js-executor build Failure

### ISSUE THREAD

**Issue by javahook** [thingsboard/thingsboard#2149]
[OS: Win10] When I build with 'mvn clean install -DskipTests', raise following errors
.....
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ js-executor ---
[INFO] Running 'npm install' in E:\GitHub\thingsboard\msa\js-executor
[INFO]
[INFO] > snappy@6.2.3 install E:\GitHub\thingsboard\msa\js-executor\node_modules\snappy
[INFO] > prebuild-install || node-gyp rebuild
[INFO]
[INFO]
[INFO] > nodemon@1.19.4 postinstall E:\GitHub\thingsboard\msa\js-executor\node_modules\nodemon
[INFO] > node bin/postinstall || exit 0
[INFO]
[INFO]
[INFO] > protobufjs@6.8.8 postinstall E:\GitHub\thingsboard\msa\js-executor\node_modules\protobufjs
[INFO] > node scripts/postinstall
[INFO]
[INFO]
[INFO] > thingsboard-js-executor@2.4.2 install E:\GitHub\thingsboard\msa\js-executor
[INFO] > npm run build-proto && pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js
[INFO]
[INFO]
[INFO] > thingsboard-js-executor@2.4.2 build-proto E:\GitHub\thingsboard\msa\js-executor
[INFO] > pbjs -t static-module -w commonjs -o ./api/jsinvoke.proto.js ../../application/src/main/proto/jsinvoke.proto
[INFO]
[ERROR] installing jsdoc@^3.5.5
[ERROR] installing tmp@0.0.33
[ERROR] installing uglify-js@^3.3.25
[ERROR] installing espree@^3.5.4
[INFO] > pkg@4.4.0
[INFO] > Fetching base Node.js binaries to PKG_CACHE_PATH
[INFO]
[INFO] > Error! ESOCKETTIMEDOUT
[INFO] > Asset not found by direct link:
[INFO]   {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-win-x64"}
[INFO]
[INFO] > Error! ESOCKETTIMEDOUT
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! thingsboard-js-executor@2.4.2 install: `npm run build-proto && pkg -t node10-linux-x64,node10-win-x64 --out-path ./target . && node install.js`
[ERROR] npm ERR! Exit status 2
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the thingsboard-js-executor@2.4.2 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-11-05T14_49_01_368Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:41 min
[INFO] Finished at: 2019-11-05T22:49:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project js-executor: Failed to run task: 'npm install' failed. (error code 2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by shen974115833** [comment]
Have you solved the problem?

**Comment by anlem12** [comment]
Same problem? Don't know how to solve

**Comment by javahook** [comment]
[INFO] {"tag":"v2.6","name":"uploaded-v2.6-node-v10.15.3-win-x64"}

Download [uploaded-v2.6-node-v10.15.3-win-x64] manually, and copy to the specified directory will be ok.

**Comment by HardwayLinka** [comment]
Hey @javahook, could you tell me where is the specified directory?
