### ISSUE TITLE
Unable to send RPC command from widget action

### ISSUE THREAD

**Issue by geodon203** [thingsboard/thingsboard#2151]
Need to send an RPC command using the custom action facility provided by the Entities widget action cell button. Using the following code but can't get it to work even though I am using the controlApi via the widgetContext?

var rpcMethod = "setNewInterval";
var rpcParams = {
    "interval": 20000
};
var timeout = 10000;
widgetContext.controlApi.sendOneWayCommand(rpcMethod, rpcParams, timeout);

**Comment by IoTThinks** [comment]
I'm using MQTT client to send to Thingsboard MQTT using MQTT API.
You search for ThingsBoard MQTT API.

I think it's easy than the provided ThingsBoard Library.

**Comment by Nehruprasath1** [comment]
How to send RPC command from widget action? Please guide me..

**Comment by serfreeman1337** [comment]
I were able to achieve this with JQuery:

```javascript
console.log(widgetContext);
console.log(entityId);

$.ajax({
    url: 'api/rpc/oneway/' + entityId.id,
    type: 'post',
    contentType: 'application/json',
    data: JSON.stringify({
        method: 'reportStatus',
        params: null,
        timeout: 5000
    }),
    headers: {
        'X-Authorization': 'Bearer ' + localStorage.getItem('jwt_token')
    },
    success: function (data) {
        console.log(data);
    }
});
```

Is there any other clean way to do this ?

**Comment by GeirFrimann** [comment]
@serfreeman1337 do you have any idea how to add params that include device attributes?

**Comment by serfreeman1337** [comment]
@GeirFrimann an easy way would be to query device attributes via api and then send them as JSON string in params:
```javascript
$.ajax({
	url: 'api/plugins/telemetry/DEVICE/' + entityId.id + '/values/attributes?key=my_attribute',
	contentType: 'application/json',
	headers: {
		'X-Authorization': 'Bearer ' + localStorage.getItem('jwt_token')
	},
	success: function (data) {
		console.log(data);
		let attr = data[0].value;
		
		console.log('attr: ' + attr);
		$.ajax({
			url: 'api/plugins/rpc/oneway/' + entityId.id,
			type: 'post',
			contentType: 'application/json',
			data: JSON.stringify({
				method: 'rpcMethod',
				params: JSON.stringify(attr),
				timeout: 5000
			}),
			headers: {
				'X-Authorization': 'Bearer ' + localStorage.getItem('jwt_token')
			},
			success: function (data) {
				console.log(data);
			}
		});
	}
});
```

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
