### ISSUE TITLE
ENTITY_VIEW originator not recognized

### ISSUE THREAD

**Issue by daniauri** [thingsboard/thingsboard#2153]
It is not possible to filter for message originator ENTITY_VIEW.

I have an Entity View filtering visible data from a device for a specific customer based on Rules for his group. This is similar to the [RBAC example](https://thingsboard.io/docs/user-guide/rbac/). 

I want to have the behavior that specific attributes, which are updated on the Entity View via REST API, will be copied to the linked Device of the Entity View. To do this I need to filter incoming messages if they are originated from the Entity View.

![image](https://user-images.githubusercontent.com/51371774/68292671-a280e880-008c-11ea-98ff-a094e0a7c185.png)

EXPECTED: Entity View can be selected in originator type filter.
ACTUAL: Can not select Entity View.

Using the originator fields enrichment node result in an error.

![image](https://user-images.githubusercontent.com/51371774/68292458-30100880-008c-11ea-8e1d-85731f262e44.png)

![image](https://user-images.githubusercontent.com/51371774/68291229-b5de8480-0089-11ea-97d8-e0d9db9e3a31.png)

[Pastebin ERROR](https://pastebin.com/Zfm5w73y)

How to filter for ENTITY_VIEW originated messages?

**Comment by Ultrazombie** [comment]
Please reopen this if still relevant
