### ISSUE TITLE
Assign Asset(s) To Customer modal - use "contains" for customer search not startsWith

### ISSUE THREAD

**Issue by agtokty** [thingsboard/thingsboard#2154]
I think it would be better to search customer using like "contains" method. currently search sql query use this:  **searchTerm%**

my suggestion is:  **%searchTerm%**

related code : https://github.com/thingsboard/thingsboard/blob/ced63c4e70579f9567e05e1632322f226c7cce19/dao/src/main/java/org/thingsboard/server/dao/sql/customer/CustomerRepository.java#L34

What do you think ?

**Comment by Ultrazombie** [comment]
Please reopen this if still relevant
