### ISSUE TITLE
Attribute string length and dashboard display issue

### ISSUE THREAD

**Issue by lambone** [thingsboard/thingsboard#2157]
I defined a Device Server Attribute with the type of String, and when I store the 20 digits number, it is fine in the Device attribute.
But when I define a user input dashboard to enable end user to update it. it just display the last 3 digit in 0.
![image](https://user-images.githubusercontent.com/4221783/68437990-cf610700-0216-11ea-9f53-0a98d6b6dab1.png)

and in dashboard
![image](https://user-images.githubusercontent.com/4221783/68438089-1ea73780-0217-11ea-9d74-7811588c6baa.png)
Thanks

**Comment by denisac77** [comment]
referenced this pull request from commit #2157

**Comment by denisac77** [comment]
#2002

**Comment by denisac77** [comment]
#1008

**Comment by denisac77** [comment]
#101

**Comment by denisac77** [comment]
#1020

**Comment by denisac77** [comment]
#1021

**Comment by denisac77** [comment]
#1027

**Comment by denisac77** [comment]
#2000 #2001 #2002

**Comment by denisac77** [comment]
#2003

**Comment by denisac77** [comment]
#2004

**Comment by denisac77** [comment]
#1600

**Comment by denisac77** [comment]
#405

**Comment by denisac77** [comment]
#1600 fix

**Comment by denisac77** [comment]
#409 fix

**Comment by denisac77** [comment]
#408 fix

**Comment by denisac77** [comment]
#2213 fix

**Comment by denisac77** [comment]
#520 remove

**Comment by denisac77** [comment]
#519 fix

**Comment by denisac77** [comment]
#521 fix

**Comment by denisac77** [comment]
#2210 clear

**Comment by denisac77** [comment]
#2213 remove

**Comment by denisac77** [comment]
#2208 reset

**Comment by denisac77** [comment]
#606 fix

**Comment by denisac77** [comment]
#614 fix

**Comment by denisac77** [comment]
#732 delete

**Comment by denisac77** [comment]
#727 remove

**Comment by denisac77** [comment]
#705 fix

**Comment by denisac77** [comment]
#806 remove

**Comment by denisac77** [comment]
#800 fix

**Comment by PovitruliaV** [comment]
Hi @denisac77 ,
Is this issue still relevant?
