### ISSUE TITLE
Dashboard layout: margin between widgets - horizontal vs vertical

### ISSUE THREAD

**Issue by woodyjon** [thingsboard/thingsboard#2159]
In the layout settings of a dashboard, it seems to me that the horizontal margin between widgets is inverted with the vertical margin.

![image](https://user-images.githubusercontent.com/30724004/68467501-99bc1e00-0216-11ea-99d2-4170c3044ebf.png)

Looking at the code (branch master), the horizontal margin (hMargin) is saved in `margins[0]` and the vertical margin (vMargin) is saved in `margins[1]`.

Then, in the file *dashboard.directive.js*, rowHeight is calculated like so:
(line 479)
```
rowHeight = (viewportHeight - vm.gridsterOpts.margins[1]*(vm.widgets.length+1) + vm.gridsterOpts.margins[0]*vm.widgets.length) / totalRows;
```
I think that `margins[0]` should be replaced by `margins[1]`

and curColWidth is calculated like so:
(line 553)
```
vm.gridster.curColWidth = (vm.gridster.curWidth + (vm.gridster.outerMargin ? -vm.gridster.margins[1] : vm.gridster.margins[1])) / vm.gridster.columns;
```
I think that `margins[1]` should be replaced by `margins[0]`

Could you please check this? I do not submit a pull request because I do not have the environment yet to test this.

Thanks.

**Comment by ashvayka** [comment]
if this is true, it is a serious bug that we need to fix. However, we need to make sure that old dashboard will not be impacted. Need to provide careful upgrade script.
