### ISSUE TITLE
Custom Keyspace name?

### ISSUE THREAD

**Issue by krruzic** [thingsboard/thingsboard#216]
Weird request but I'm wondering if this is even possible and how difficult it would be. For various reasons I'd like to change the keyspace from "thingsboard" to an auto-generated keyspace using an environment variable or similar. I'm assuming I'd have to compile thingsboard with modification but I want to know how extensive this would be

Thanks!

**Comment by ashvayka** [comment]
There is already env variable that you can use: CASSANDRA_KEYSPACE_NAME
from thingsboard.yml: `keyspace_name: "${CASSANDRA_KEYSPACE_NAME:thingsboard}"`
See [configuration guide](https://thingsboard.io/docs/user-guide/install/config/) for more details
