### ISSUE TITLE
ui-vue? anyone?

### ISSUE THREAD

**Issue by Lavhe** [thingsboard/thingsboard#2162]
I see we are currently building **ui-ngx** which is cool

#2150 

Anyone interested in **ui-vue**?

**Comment by Surgbc** [comment]
I installed version 3 of the professional edition and noticed that there are a few changes in the API. I believe this should be the same also for the community edition. Will you stick to using version 2, or are you planning to upgrade to version 3 which will also mean that you upgrade the UI?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
