### ISSUE TITLE
Rule Engine Geofencing refuses to use negative values for latitude

### ISSUE THREAD

**Issue by mbari** [thingsboard/thingsboard#2164]
I am testing out the rule engine My device is sending negative values of Latitude because I am to the south of the equator. 

During the setting up of the geofencing circle, "center latitude" refuses to take negative values. I have attached sample telemetry and screenshots
![Latutude refusing negative values](https://user-images.githubusercontent.com/1671401/68526894-cabd5100-02f1-11ea-95f5-5ac8d9e685c8.png)
![No latitude data](https://user-images.githubusercontent.com/1671401/68526895-cabd5100-02f1-11ea-8e4b-2c2d6fb1b4ad.png)
![Telemetry Sample](https://user-images.githubusercontent.com/1671401/68526932-2be52480-02f2-11ea-8688-efc42b873af2.png)

**Comment by mbari** [comment]
To achieve geofencing, I had to transform the data to eliminate the negative sign. I added to the value

**Comment by yefimov-andrey** [comment]
Thank you for your feedback, this will be fixed in the next release.

**Comment by mbari** [comment]
Welcome
