### ISSUE TITLE
What is the scope in the API?

### ISSUE THREAD

**Issue by mtahle** [thingsboard/thingsboard#2165]
Hi,

can you please explain what is the scope in the API requests and how to use it?

like this one:
/api/plugins/telemetry/{entityType}/{entityId}/attributes/{scope}

EDIT:
Ok, looking into the documentation does not help so I found myself forced for digging the code and I get those lines here 

https://github.com/thingsboard/thingsboard/blob/82b57e1cf8b10009a23a78364267472c0324c95e/application/src/main/java/org/thingsboard/server/controller/TelemetryController.java#L343

and from there the values of the scope could be one of the following: 
- SERVER_SCOPE
- SHARED_SCOPE
- CLIENT_SCOPE

**Comment by vvlladd28** [comment]
https://thingsboard.io/docs/user-guide/attributes/ documentation describes the attribute's type. The asset and byte entity type has only the server attribute

**Comment by mtahle** [comment]
> https://thingsboard.io/docs/user-guide/attributes/

Thanks for your reply, so the SCOPE is the attribute's type itself?

**Comment by mirtaheri** [comment]
> > https://thingsboard.io/docs/user-guide/attributes/
> 
> Thanks for your reply, so the SCOPE is the attribute's type itself?

Did you manage by chance to understand what arguments "scope" can get?
