### ISSUE TITLE
TypeError: Cannot read property 'getTime' of null

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2167]
Hello!

TypeError: Cannot read property 'getTime' of null in bundle.***.js appears if you set on a widget a data from date and the data to date is still empty.

I think this sometimes resets the websocket also.

![image](https://user-images.githubusercontent.com/7239350/68601710-25e37500-04a5-11ea-8258-138bb7ce399d.png)

**Comment by Karabiy** [comment]
does this issue persists? 
also, specify he exact widget being used for those tests
