### ISSUE TITLE
Reset and set new passwort via link

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2174]
Hello!

Sometimes a client forgets it's password. They ask us if we could give them another link so that they can set a new password for their account. The user administration only allows the following tasks (ThingsBoard PE):

- Disable User Account

- Display Activation Link

- Resend Activation

- Login as Tenant Admin

- Delete User

I think it would be wise to have another "Create Reset Password Link" which automatically deletes the old password. Currently we need to delete the user, recreate it and resend the link.

I know there is the "Request Password Reset" option but what is with configurations which doesn't have mail server support.

Thanks!

**Comment by amirDhane** [comment]
Why this issue still open, i tried the demo version and i can get forget password link!
<img width="516" alt="thingsboard forget password" src="https://user-images.githubusercontent.com/11707796/69003368-bdb3e980-0911-11ea-8326-8162b5406eff.png">

**Comment by hamburml** [comment]
This is not what this issue is about.

If you use a self hosted ThingsBoard (CE or PE), you can only use the "Forgot Password?" link on the login page, which tries to send an email.

Sometimes ThingsBoard is configured to not have mail server support.

**Comment by hallard** [comment]
I agree, not able to change user password without email is a missing feature.

**Comment by sferguson-ISI** [comment]
+1 I have to delete accounts and then remake them all the time just for a password reset.

**Comment by ban2derlog** [comment]
Hi, on latest version of ThingsBoard - if you log in as Tenant Administrator you can change passwords.
You need to find User\Tenant and then press Login as $User, then you can change it in this user Profile manually.
@sferguson-ISI

**Comment by hamburml** [comment]
@ban2derlog That would mean the Tenant Administrator knows the password of the User. I want the User to be the only person who enters the password.

**Comment by ban2derlog** [comment]
@hamburml Ok, then what's wrong with "Forgot password?" button?
If your users use valid mail address - then they can change password by themselves.

**Comment by sferguson-ISI** [comment]
@ban2derlog I agree with @hamburml you have to have a mail server setup in order for that to work.  For my case I actually do have the SMTP setup but our emails get sent to spam or blocked altogether.  What we're looking for would be a "reset password link" or something the tenant-admin can click to reset a user's password without prior knowledge of that user's password.

**Comment by hamburml** [comment]
@sferguson-ISI got it right. The setup we used (we don't use it anymore, we left Thingsboard PE for various reasons) was inside a private network without access to public mail servers (even no internal mail servers). I am going to unsubscribe to this issue as I am not concerned anymore.

**Comment by maaaaaaaaaaaaaan** [comment]
I would like to see this feature added. I have the same problem. 

There is a "request password reset" on the login page. And this works fine for me and most users. But some user probably have some corporate spamfilter that blocks the reset password email from our noreply@ourdomain.com 

So it had been nice to manually create that URL and send it manually from our support/personal email account. 

Like
http://ourdomain.com/api/noauth/resetPassword?resetToken=fO77xkeDGrYi111111111111111111pAFjFLjtpT234

**Comment by meberli** [comment]
We need this option as well.

**Comment by sprijk** [comment]
Same here, please reopen

**Comment by cemilf** [comment]
We need this option too. This issue should be reopened

**Comment by martin-hcp** [comment]
Same here, we also need this

**Comment by gales73** [comment]
add feature please

**Comment by GilDev** [comment]
Could this please be reopened?

**Comment by jbergmannAutomation** [comment]
We need this option as well.

**Comment by PhilipRai** [comment]
Yes please!

**Comment by txf-** [comment]
I'm really surprised this still has not been implemented
