### ISSUE TITLE
Possibility to hide certain widgets when exporting or generating pdf report

### ISSUE THREAD

**Issue by woodyjon** [thingsboard/thingsboard#2178]
Hello,

Is it possible to display widgets on a dashboard but have them not appearing when we generate a pdf export of the dashboard?

Would it be easier to to that with custom widgets?

Would it maybe be possible with css @media, considering that the server used for generation might be a special viewport?

Thanks a lot!

**Comment by Wan-Razaq** [comment]
hey man, did you find out how to do this?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
