### ISSUE TITLE
Dashboard state is not kept if using a stored url and login is required

### ISSUE THREAD

**Issue by MrZANE42** [thingsboard/thingsboard#2180]
We would like to store the complete url, including dashboard state so we can directly show a specific dashboard page, in an external application. The problem is that if the user needs to login, if for example the session has expired, they end up at the right dashboard after the login but the dashboard state is not kept. They end up at the start/default page of the dash.
The parameter part ( ?state=W3siaWQiOiJjdXN0b21lcnMiLCJwYXJhbXM... ) of the url gets lost post logging in.

**Comment by MrZANE42** [comment]
Any tips, workarounds, comments?

**Comment by MrZANE42** [comment]
Would very much like a comment to this issue from the TB devs.
TIA

**Comment by Eric-Ruud** [comment]
Did anyone ever find a way to externally link directly to a specific dashboard state?

**Comment by den1jkee** [comment]
hello,
we can`t reproduce this issue on the last version of Thingsboard, please provide steps for reproduce this issue
Best regards,
Denys.
