### ISSUE TITLE
Unable to run sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

### ISSUE THREAD

**Issue by vangalvin** [thingsboard/thingsboard#2182]
I was trying to set the system up to see if it would work with some sensors and if I could set up some monitoring. It seems that as soon as I run the 
sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

Followed the installation procedure, creating the user, setting the password etc.. all seems to be working and postgres is running without a hitch. 

The system just bogs down, no errors seem to appear and 

> postgres=# \password
> Enter new password:
> Enter it again:
> postgres=# \q
> postgres@ip-172-31-14-30:~$ logout
> ubuntu@ip-172-31-14-30:/usr/share/thingsboard/conf$ psql -U postgres -d postgres -h 127.0.0.1 -W
> Password for user postgres:
> psql (10.10 (Ubuntu 10.10-0ubuntu0.18.04.1))
> SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
> Type "help" for help.
> 
> postgres=# CREATE DATABASE thingsboard;
> ERROR:  database "thingsboard" already exists
> postgres=# \q
> ubuntu@ip-172-31-14-30:/usr/share/thingsboard/conf$ sudo nano /etc/thingsboard/conf/thingsboard.conf
> ubuntu@ip-172-31-14-30:/usr/share/thingsboard/conf$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
>  ===================================================
>  :: ThingsBoard ::       (v2.4.1)
>  ===================================================

The OS is  Ubuntu 18.04.3 LTS

Any suggestions as to what to check or how to fix this?
and yes i checked the logs and there seems to be no errors pertaining to this behavior that I can see.

**Comment by hamburml** [comment]
As you can see the error mentions that there already is a ThingsBoard database. The install.sh script is for installing ThingsBoard, not for upgrading/reusing a already existing database.

You can either:

- delete the database and start anew
- use the upgrade-script (https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-241)

I hope this helps.

**Comment by vangalvin** [comment]
I have set up a separate system to try it out on and will give that a go. Thanks :)
The setup instructions on the site did say to create the DB first. 

Thank you for that pointer. crossing fingers that it solves the problem. :)

**Comment by hamburml** [comment]
Sorry, I was scrolling through your message to fast.

Yes, you need to create a new empty database if this is the first time you are installing ThingsBoard. Don't forget to set the **SPRING_DATASOURCE_URL** **SPRING_DATASOURCE_USERNAME** and **SPRING_DATASOURCE_PASSWORD** inside **/etc/thingsboard/conf/thingsboard.conf**.

**Comment by vangalvin** [comment]
Well i have no idea why it was having issues with the other instance, other than the fact there is a MySQL server and Apache2 on it. Created a new instance and everything went perfectly! 
I followed the exact same process as I did on the other instance so my guess is there is something running there that is causing the install script to hang.
