### ISSUE TITLE
Packet/Message Encryption

### ISSUE THREAD

**Issue by vangalvin** [thingsboard/thingsboard#2183]
This may be a silly question however form the looks of things the messages being sent to and from Thingsboard and the device are encrypted. Yes there is a key used for authentication however it seems you can sniff the data and extract the information.

Is there a way to secure this so you are sending essentially an encrypted packet?

Or at the least pack the data on to something like jsonmsgpack as that would not only stop it from being visible but could also be handy for compressing the packets down a little.

**Comment by MrZANE42** [comment]
Use https connection instead of http?

**Comment by ban2derlog** [comment]
Hi, please use transport with SSL:
https://thingsboard.io/docs/pe/user-guide/mqtt-over-ssl/
https://thingsboard.io/docs/pe/user-guide/ssl/http-transport-over-ssl/
