### ISSUE TITLE
Failed to start docker_tb1 and docker_tb2 when Kafka failed once. 

### ISSUE THREAD

**Issue by edmundsong** [thingsboard/thingsboard#2186]
Configuration: 
Version 2.4.2-SNAPSHOT
Microservice deployment through docker. 

When Kafka failed to start due some configuration issue, even after we fixed the configuration issue in Kafka, the docker_tb1 and docker_tb2 will always failed to boot-up with " Timeout occurred while waiting for topic [js.eval.requests] to be available!" message. Seems the only way to fix this problem is to remove all installed docker images and re-install these docker images. 

2019-11-19 13:30:11,458 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'acks' was supplied but isn't a known config.
2019-11-19 13:30:11,458 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'batch.size' was supplied but isn't a known config.
2019-11-19 13:30:11,458 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'buffer.memory' was supplied but isn't a known config.
2019-11-19 13:30:11,458 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'linger.ms' was supplied but isn't a known config.
2019-11-19 13:30:11,459 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka version: 2.3.0
2019-11-19 13:30:11,459 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka commitId: fc1aaa116b661c8a
2019-11-19 13:30:11,459 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka startTimeMs: 1574170211459
2019-11-19 13:30:11,601 [kafka-producer-network-thread | producer-js-invoke-tb2] INFO  org.apache.kafka.clients.Metadata - [Producer clientId=producer-js-invoke-tb2] Cluster ID: 
_Wc1bU1CTSCSjDJAi9T2rQ
2019-11-19 13:30:11,610 [main] INFO o.a.k.c.admin.AdminClientConfig - AdminClientConfig values:
     bootstrap.servers = [kafka:9092]
     client.dns.lookup = default
     client.id =
     connections.max.idle.ms = 300000
     metadata.max.age.ms = 300000
     metric.reporters = []
     metrics.num.samples = 2
     metrics.recording.level = INFO
     metrics.sample.window.ms = 30000
     receive.buffer.bytes = 65536
     reconnect.backoff.max.ms = 1000
     reconnect.backoff.ms = 50
     request.timeout.ms = 120000
     retries = 1
     retry.backoff.ms = 100
     sasl.client.callback.handler.class = null
     sasl.jaas.config = null
     sasl.kerberos.kinit.cmd = /usr/bin/kinit
     sasl.kerberos.min.time.before.relogin = 60000
     sasl.kerberos.service.name = null
     sasl.kerberos.ticket.renew.jitter = 0.05
     sasl.kerberos.ticket.renew.window.factor = 0.8
     sasl.login.callback.handler.class = null
     sasl.login.class = null
     sasl.login.refresh.buffer.seconds = 300
     sasl.login.refresh.min.period.seconds = 60
     sasl.login.refresh.window.factor = 0.8
     sasl.login.refresh.window.jitter = 0.05
     sasl.mechanism = GSSAPI
     security.protocol = PLAINTEXT
     send.buffer.bytes = 131072
     ssl.cipher.suites = null
     ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
     ssl.endpoint.identification.algorithm = https
     ssl.key.password = null
     ssl.keymanager.algorithm = SunX509
     ssl.keystore.location = null
     ssl.keystore.password = null
     ssl.keystore.type = JKS
     ssl.protocol = TLS
     ssl.provider = null
     ssl.secure.random.implementation = null
     ssl.trustmanager.algorithm = PKIX
     ssl.truststore.location = null
     ssl.truststore.password = null
     ssl.truststore.type = JKS

2019-11-19 13:30:11,614 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'acks' was supplied but isn't a known config.
2019-11-19 13:30:11,614 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'batch.size' was supplied but isn't a known config.
2019-11-19 13:30:11,614 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'buffer.memory' was supplied but isn't a known config.
2019-11-19 13:30:11,614 [main] WARN o.a.k.c.admin.AdminClientConfig - The configuration 'linger.ms' was supplied but isn't a known config.
2019-11-19 13:30:11,614 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka version: 2.3.0
2019-11-19 13:30:11,614 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka commitId: fc1aaa116b661c8a
2019-11-19 13:30:11,615 [main] INFO o.a.kafka.common.utils.AppInfoParser
- Kafka startTimeMs: 1574170211614
2019-11-19 13:30:41,763 [main] INFO o.t.s.kafka.TBKafkaProducerTemplate
- [js.eval.requests] Failed to wait for topic: Timeout occurred while waiting for topic [js.eval.requests] to be available!
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.thingsboard.server.kafka.TBKafkaAdmin.waitForTopic(TBKafkaAdmin.java:47)
     at
org.thingsboard.server.kafka.TBKafkaProducerTemplate.init(TBKafkaProducerTemplate.java:85)
     at
org.thingsboard.server.kafka.TbKafkaRequestTemplate.init(TbKafkaRequestTemplate.java:98)
     at
org.thingsboard.server.service.script.RemoteJsInvokeService.init(RemoteJsInvokeService.java:118)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
     at
org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
     at
org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
     at
org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
     at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
     at
org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
     at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
     at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
     at
org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
     at
org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
2019-11-19 13:30:41,766 [main] WARN
o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh
attempt: 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultActorService': Unsatisfied dependency expressed through field 'actorContext'; nested exception is
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actorSystemContext': Unsatisfied dependency expressed through field 'jsSandbox'; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteJsInvokeService': Invocation of init method failed; nested exception is java.lang.RuntimeException: 
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
2019-11-19 13:30:41,784 [Curator-Framework-0] INFO o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2019-11-19 13:30:41,895 [main] INFO org.apache.zookeeper.ZooKeeper -
Session: 0x1000a93ab9a0005 closed
2019-11-19 13:30:41,895 [main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 
0x1000a93ab9a0005
2019-11-19 13:30:41,895 [main] INFO o.t.s.s.c.d.ZkDiscoveryService - ZK client disconnected
2019-11-19 13:30:41,897 [main] INFO o.t.s.s.c.d.ZkDiscoveryService - Stopped discovery service
2019-11-19 13:30:41,931 [main] INFO
o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2019-11-19 13:30:41,935 [main] INFO com.zaxxer.hikari.HikariDataSource -
HikariPool-1 - Shutdown initiated...
2019-11-19 13:30:41,950 [main] INFO com.zaxxer.hikari.HikariDataSource -
HikariPool-1 - Shutdown completed.
2019-11-19 13:30:41,953 [main] INFO o.a.catalina.core.StandardService - Stopping service [Tomcat]
2019-11-19 13:30:42,011 [main] INFO
o.s.b.a.l.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-19 13:30:42,014 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultActorService': Unsatisfied dependency expressed through field 'actorContext'; nested exception is
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actorSystemContext': Unsatisfied dependency expressed through field 'jsSandbox'; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteJsInvokeService': Invocation of init method failed; nested exception is java.lang.RuntimeException: 
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
     at
org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
     at
org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
     at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
     at
org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
     at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
     at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
     at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
     at
org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
     at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
     at
org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actorSystemContext': Unsatisfied dependency expressed through field 'jsSandbox'; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteJsInvokeService': Invocation of init method failed; nested exception is java.lang.RuntimeException: 
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
     at
org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
     ... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'remoteJsInvokeService': Invocation of init method failed; nested exception is java.lang.RuntimeException: 
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
     at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
     at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
     at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     at
org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
     at
org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
     at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
     ... 40 common frames omitted
Caused by: java.lang.RuntimeException: 
java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.thingsboard.server.kafka.TBKafkaProducerTemplate.init(TBKafkaProducerTemplate.java:89)
     at
org.thingsboard.server.kafka.TbKafkaRequestTemplate.init(TbKafkaRequestTemplate.java:98)
     at
org.thingsboard.server.service.script.RemoteJsInvokeService.init(RemoteJsInvokeService.java:118)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
     at
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
     ... 52 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Timeout occurred while waiting for topic [js.eval.requests] to be available!
     at
org.thingsboard.server.kafka.TBKafkaAdmin.waitForTopic(TBKafkaAdmin.java:47)
     at
org.thingsboard.server.kafka.TBKafkaProducerTemplate.init(TBKafkaProducerTemplate.java:85)
     ... 61 common frames omitted

**Comment by rlowit** [comment]
Try to delete all topics in zookeeper. It worked for me. To do that, open a console in zookeeper container with the rest of containers stopped. Run: 
./bin/zkCli.sh -server zookeeper:2181 <<< "deleteall /brokers/topics"
Stop the zookeeper container and finally run docker-start-services.sh

**Comment by sscns** [comment]
yes, i found delete all zookeepr _data folder can also solve this issue, similar as your method to delete all topics in zookeeper. any suggestion for how to fix this issue? seems there are some mess-up in zookeepr topic list?

**Comment by Frozka** [comment]
I dont know why it particulary likes to fail creating this topic. But if it does so you can create it manually by entering kafka container and executing:
```
kafka-topics --create --zookeeper kafka-cluster-zookeeper:2181 --replication-factor 3 --partitions 100 --topic js.eval.requests --config retention.ms=60000 --config segment.bytes=26214400 --config retention.bytes=10485760 --config cleanup.policy=delete
```

**Note** kafka-topics might not be available inside, might need to look for kafka-topics.sh file in your container.
 **Note** set --zookeeper to your address default is zookeeper.
