### ISSUE TITLE
How to hide or disable "Device is offline" message on rpc widgets.

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#2187]
Hello,

I would like to hide or disable the "Device is offline" message on knob button rpc widget. Could you tell me how can I do this?

**Comment by dajtxx** [comment]
We could not get rid that message. We were intercepting the RPC message in the rule chain and rewriting it as a publish to MQTT message. This means some mechanism behind the scenes is not getting the reply it wants.

We gave up and made a custom switch widget that set a server attr. We caught the attr change message in the rule chain and created the publish MQTT message after that.
