### ISSUE TITLE
migrate Data from one thingsboard instance to another

### ISSUE THREAD

**Issue by richardgarcia892** [thingsboard/thingsboard#2191]
hi!
im having a problem while trying to migrate from one ThingsBoard instance to another, i've been running ThingsBoard  an friend's AWS instance, now I need to migrate those to an DigitalOcean instance and KEEP all data from the old instance.

now, i've tried this tool:
https://github.com/AbCthings/thingsboard-data-migration

but it wasn't working, i've started to make some debugging and figured out that everytime i try to fetch the historical telemtry from a device it does return and empty response, like this:

`https://host:port/api/plugins/telemetry/DEVICE/45aca300-d68f-11e9-81b7-b52b3ac7943c/values/timeseries?&limit=100&agg=NONE&keys=vwc&startTs=1564617600&endTs=1569888000`

im sure that authentication is not the problem because when i run the request like this:

`https://host:port/api/plugins/telemetry/DEVICE/45aca300-d68f-11e9-81b7-b52b3ac7943c/values/timeseries
`
it fetch the LAST telemetry without issue

so, i call for your help whit this questions:
- is there any built in method to sync data beetween my old TB installation and the new one?
- is there any "tenant" export feature?
- what am i doing wrong when trying to fetch the data from the API?
- how could I "import" all the telemetry data to the new server? I strongly need to KEEP the original timestamps from the previous telemetries, the API have any option to "override" the built in time stamp with one given in the request?

thanks a lot for any tip you could give me!.

note: all my device use the telemetry http API to report the telemetry, i dont know if this could make any difference

**Comment by Karabiy** [comment]
for those reasons, in case if you need to migrate for the new infrastructure, it is recommended to take the database backup and then, in case if you want to go with the new version on the new instance, to run the upgrade script. 
more about on how to perform the backup you can refer to the upgrade instructions: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#prepare-for-upgrading-thingsboard-centos-ubuntu
