### ISSUE TITLE
Can Thingsboard limit the password length of user account ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#2200]
Hi,

We are using TB PE 2.2.x version now.

We want to limit the password size. ( Maximum / minimum). Can Thingsboard support to limit the password length ?

Here is our request :
1. We want to limit user account's password size. The password size can be limited its maximum or minimum length. 

2. When users setup their password, TB will check the password length. If the size is not correct, TB will provide the notification on the screen.

If TB does not support this function ,yet. When will thingsboard support this function ?

Can someone reply this issue ?

Best Regards,

Paul Wang

**Comment by ashaforost** [comment]
Hi @paulwang55 

See the thingsboard security section in the sysadmin's System Settings tab.
![image](https://user-images.githubusercontent.com/47900737/153204364-71a31e03-38c8-40e0-9566-2bd0792b68d3.png)
