### ISSUE TITLE
Labels of a pie chart with no % info on it

### ISSUE THREAD

**Issue by Nathan-ma** [thingsboard/thingsboard#2201]
Hello Devs, 

I would need a bit of a hand understanding how I can change the label on this pie chart to show the KwH values (raw data) instead of the %.

![image](https://user-images.githubusercontent.com/11060905/69446792-f13cac80-0d33-11ea-9975-843cd6239acb.png)

Here is a picture of the current pie chart!, I'm trying with no success to change the data type something that will fit my needs

**Comment by Nathan-ma** [comment]
![image](https://user-images.githubusercontent.com/11060905/69448006-6f9a4e00-0d36-11ea-9d61-99fab80f7b2c.png)


I do understand it has something to do with the formatter! I just need to know how to change it

**Comment by Ultrazombie** [comment]
Closed due to inactivity
