### ISSUE TITLE
Input Widget Webcamera how to

### ISSUE THREAD

**Issue by BernhardHaider** [thingsboard/thingsboard#2207]
Hi, i try to make the widget working, but it always shows "no supported web camera"
 maybe you can provide an example url for the stream attribute. maybe a public to try it myself
 are there any prerequists, e.g. type of the stream?
Accoring to issue #2014 it could be used to stream, but i could not make it work
 thank you!

**Comment by BernhardHaider** [comment]
#2090 says it is to took photos from the Webcam running on the Computer where the curren t browser is running.
that is a Little confusing.
Maybe someone knows About the function and configuration
thank you!

**Comment by vvlladd28** [comment]
Hello, this widget uses to add a photo to the TB. The widget uses a camera, at the device from an open TB, to take photo.

**Comment by BernhardHaider** [comment]
hi, i still cannot take photos.
in the PE Cloud Demosystem it works, my own PE (Maker subscription) never shows the Button?
But it is running on the same machine.
Even exporting the widget from dem Cloud to my own instance does not make a difference.
maybe someone has an idea?

![TP_PE_Cloud](https://user-images.githubusercontent.com/58142100/73094676-628a0e80-3ee1-11ea-9a22-fdf2d8c1d7be.png)
![TB_PE_own_instance](https://user-images.githubusercontent.com/58142100/73094677-628a0e80-3ee1-11ea-835a-04f834cbb726.png)

**Comment by Karabiy** [comment]
which exact browser you are using?

**Comment by ezeroldan24** [comment]
Good day, that solution did not work for me, someone found a way to do it? Thanks a lot
