### ISSUE TITLE
Export the data to pdf

### ISSUE THREAD

**Issue by gdrako** [thingsboard/thingsboard#221]
Hi All
Does anyone know if it is possible for some of the Widgets to be able to export the data to pdf for printing?

Thank you
George

**Comment by ashvayka** [comment]
Not at the moment.

**Comment by kevz93** [comment]
You can wire one up quickly if you are familiar with the code. If you want it part of the widget, send GET request `url = `/api/audit/logs?limit=${pageLink.limit}`;` Check their RESTful API's
