### ISSUE TITLE
XLS/CSV data export using Thingsboard 2.2-PE

### ISSUE THREAD

**Issue by luca-ferrari-roma** [thingsboard/thingsboard#2211]
Hi all.
Is it possible to change decimal separator (AKA format number) in exported data from the "Export to CSV/XLS" function, enabled in the top-right part of a widget?

Thank you

**Comment by waliul123** [comment]
XLS/CSV data export using Thingsboard 2.2-PE. Is it possible to change decimal separator (AKA format number) in exported data from the "Export to CSV/XLS" .PLESE visit my site https://sarkaryresults.in/
