### ISSUE TITLE
Dashboard state

### ISSUE THREAD

**Issue by ssduracell** [thingsboard/thingsboard#2214]
hey 
i'm a newbie to thingsboard and i wonder if there is an option that you can have one dashboard state 
 with a widget that is linked to an action on multiple widgets. so you can call that dashboard state from a widget action and the widget inside the dashboard state changes on from wich widget it is called.

id like to call an input widget depending on from wich widget its called so i can change server atributes like a double value. Like this: dashboard->dashboard widget -> widget action -> dahboard state -> widget -> change server attribute of device and this for every dashboard widget

friendly regards

**Comment by sdeujfalssy** [comment]
Hello, I am not sure I understand completely, but are you trying to display different widgets based on a selection or action on the first widget? 

If so I believe this is exactly what dashboard states are intended for... you will be navigated to a "new dashboard" with its own set of widgets. You can also include the first widget in all the different dashboard states so that you could navigate to different dashboard states without going back to the default state. 

Or have I misunderstood something?

**Comment by ssduracell** [comment]
let me try to clearify the situation:
i have multiple widgets that display meter readings from my sensors but i want to make one dashboard state that gets called with an action on all the sensor widgets. this dashboard state has only a input widget so i can set the values of the server attribute from the corresponding sensor.

i hope this answer is a little more clear :p

**Comment by sdeujfalssy** [comment]
Thank you, that does clear things up a bit.

As far as I know you can do this: 
1. Create a dashboard state with name: ${entityName}. 
2. Configure action on default dashboard widgets to Navigate to new dashboard state created in 1. 
3. Create an entity alias that is set from the dashboard state 
3. Add a server input widget to the ${entityName} dashboard and set the datasource entity to the entity alias created in 3.

When you click on the action on the widgets on the default dashboard it will redirect you to the ${entityName} dashboard which has a single server input widget that is associated to the device that initiated the redirect. I hope this is what you're after?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
