### ISSUE TITLE
how to disable the aggregation on the display?

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#2217]
Hi, my device location update at 10HZ, how can i change the refresh frequency to show the location?

**Comment by vparomskiy** [comment]
it is done automatically, updates are not fetched by widgets periodically, but recevied from the server via websocket once they are updated

**Comment by lincoln310** [comment]
What i saw is: the location on map updated at 1HZ. Is it because of the mean of location every seconds? If so, where should i change this?

**Comment by lincoln310** [comment]
Any one help?

**Comment by Karabiy** [comment]
you can set those to none, so that no aggregation will occur
