### ISSUE TITLE
TCP Integration not running

### ISSUE THREAD

**Issue by sdeujfalssy** [thingsboard/thingsboard#2220]
Hello Everyone,

I have setup a TCP integration on my Thingsboard PE instance however I cannot access it.

I do not see the port active (10562) when checking what system processes are using network ports (lsof -i -P -n). When I try access the server as a TCP client (nc host 20562), the connection immediately drops as though the TCP server is not listening. I cannot see any events in the TCP Integrations debug log. 

Has anyone else had a similar issue by any chance? 

![Screen Shot 2019-11-30 at 21 35 13](https://user-images.githubusercontent.com/1500208/69905267-c6003000-13b9-11ea-8367-d2c59cae5e24.png)

**Comment by vvlladd28** [comment]
Hi,
Thanks for the info. We will fix it in the new version

**Comment by sdeujfalssy** [comment]
Ok amazing, thanks so much for the feedback, do you know by any chance when the new version might be released?

**Comment by markZAR** [comment]
I also have this issue @sdeujfalssy. Yesterday I was told by the ThingsBoard team that the release date of it is unknown. Business is standing still now.  :(

**Comment by jacksun101** [comment]
I have the issue too. Any update on this?

**Comment by markZAR** [comment]
The updated version 2.4.3 PE still hasn’t solved the issue for me. I’ve been told it’s related to insufficient RAM on my server which has 4GB. I tried running the remote TCP integration on an 8GB Ubuntu instance which still didn’t connect to my ThingsBoard PE server (it did however connect to ThingsBoard cloud, but the TCP connection still didn’t work). Surely this confirms it’s not RAM related?

In the interim I’ve resorted to developing a node-RED flow which parses my TCP payload and feeds it into the ThingsBoard via MQTT in JSON format. 

Still very frustrating that this paid for off the shelf TCP integration doesn’t work.

**Comment by markZAR** [comment]
SOLVED:
The ThingsBoard team finally found the issue for me. Thank you!

Unknown to me was that the thingsboard.yml file has a default value for the Integrations RPC port of 50051. The TCP integration defaults to 9090. Once I changed the thingsboard.yml file integration RPC port to match the TCP integration port on 9090 I managed to connect. 

**On Linux use the following command to edit....**
sudo nano /etc/thingsboard/conf/thingsboard.yml

**Change RPC port from 50051 to 9090...**
integrations:
statistics:
enabled: "${INTEGRATIONS_STATISTICS_ENABLED:true}"
persist_frequency: "${INTEGRATIONS_STATISTICS_PERSIST_FREQUENCY:3600000}"
reinit:
enabled: "${INTEGRATIONS_REINIT_ENABLED:true}"
frequency: "${INTEGRATIONS_REINIT_FREQUENCY:300000}"
allow_Local_network_hosts: "${INTEGRATIONS_ALLOW_LOCAL_NETWORK_HOSTS:true}"
rpc:
enabled: "${INTEGRATIONS_RPC_ENABLED:true}"
port: "${INTEGRATIONS_RPC_PORT:**50051**}"

Please make a note on the TCP integration installation guide of this to prevent others repeat this issue.

**Comment by Karabiy** [comment]
the previous comment is correct
also, for the latest version, the default integration RPC port is now 9090
