### ISSUE TITLE
how to reach CE installation with a domain name not localhost

### ISSUE THREAD

**Issue by RamiKhawaly** [thingsboard/thingsboard#2222]
I just installed the CE edition on aws ec2 instance with ubuntu, and followed the instructions provided on your website, all seems to work. 
however, i need to point a domain to login to the thingsboard dashboard. 
I pointed out the needed domain to the server, but it can't reach the thingsboard dashboard. 

what am i missing?

**Comment by vvlladd28** [comment]
Hi,
You need to install Nginx or Apache to reverse proxy.

**Comment by datenheim** [comment]
You may combine the compose-file from my answer [here ](https://github.com/thingsboard/thingsboard/issues/2238#issuecomment-562641105) with the [nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion).
Is running fine since a year now...

**Comment by datenheim** [comment]
By the way - why didn't you ask the community or forum but filed an issue?
