### ISSUE TITLE
Unexpected error during ThingsBoard installation!

### ISSUE THREAD

**Issue by canerpehlivan** [thingsboard/thingsboard#2223]
Hi,

I am just trying to follow the guide here: https://thingsboard.io/docs/user-guide/install/windows/#step-2-thingsboard-service-installation

In the 5th step, I get this error:

> 
> Detecting Java version installed.
> CurrentVersion 18
> Java 1.8 found!
> Installing thingsboard ...
>  ===================================================
>  :: ThingsBoard ::       (v2.4.1)
>  ===================================================
> 
> Starting ThingsBoard Installation...
> Installing DataBase schema for entities...
> Installing SQL DataBase schema part: schema-entities.sql
> Unexpected error during ThingsBoard installation!
> org.postgresql.util.PSQLException: FATAL: database "thingsboard" does not exist
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
>         at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2589)
>         at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:116)
>         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
>         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:55)
>         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:219)
>         at org.postgresql.Driver.makeConnection(Driver.java:407)
>         at org.postgresql.Driver.connect(Driver.java:275)
>         at java.sql.DriverManager.getConnection(Unknown Source)
>         at java.sql.DriverManager.getConnection(Unknown Source)
>         at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:60)
>         at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:151)
>         at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
> Unexpected error during ThingsBoard installation!
> ThingsBoard installation failed!
> 

I don't understand what is the problem. Can you help?

**Comment by davevert** [comment]
I fell into the same trap. About one-halfway thru STEP 3 there is a "brief" sentence to create a THINGSBOARD data base.  Look carefully. No specifics are given.

**Comment by ankitfidel** [comment]
You need to run the installation script and create the default schema for thingsboard first.

**Comment by abferguson** [comment]
I just ran into the same problem on a Raspberry Pi installation.  I was sloppy and missed the semicolon at the end of the postgresql command that creates the thingsboard database.

postgres=# CREATE DATABASE thingsboard; (Note semicolon at end of command)

The install completed after I added the semicolon.

**Comment by bebosudo** [comment]
I've faced the same issue; my problem was that I tried the `thingsboard/tb` image first, and then the `thingsboard/tb-postgres`, which was failing because it found the hidden file `/data/.firstlaunch`.
When outside the container clean and recreate the data and logs directories:
```bash
$ rm -rf ~/.mytb-{data,logs}/
$ mkdir  ~/.mytb-{data,logs}/
```
Then run the postgres container as per instructions.

**Comment by sourabhkumarjha** [comment]
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: syntax error at or near "PROCEDURE"
  Position: 21
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:68)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:175)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard DB installation failed!


why i get this msg can any one resolve this?

**Comment by taous96** [comment]
Hi canerpehlivan, I have faced the same issue, just go to PostgreSQL and create a database named thingsboard using "CREATE DATABASE thingsboard;" command, then open cmd as administrator, run the script again and the problem will be fixed, hope this helps you

**Comment by SergMeleshko** [comment]
Hello, canerpehlivan.
Is this issue still relevant?

**Comment by wildernessfamily** [comment]
Had the same problem when spinning up a new instance using Docker Compose. I was spinning up a new instance for quick testing of a feature. While I was quickly spinning up the instance, I forgot to change the owners of the two volumes per the following ThingsBoard instructions. Which in turn was causing the said error of this ticket.
```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
```
