### ISSUE TITLE
mailserver not working

### ISSUE THREAD

**Issue by ssduracell** [thingsboard/thingsboard#2224]
hey! 
i'm running thingsboard inside docker and i cant get the mailserver to work with office365 stmp.
i always get the error connection timeout when sending a testmail 
my credentials en host and port information is correct but still i cant send an email.

when i check my chrome console it says: 
errorCode: 2
message: "Unable to send mail: Connection timed out (Connection timed out)"
status: 500
timestamp: "2019-12-02T10:22:11.905+0000"

any ideas?

**Comment by vvlladd28** [comment]
Hi,
You are an open docker port to use the SMT protocol?

**Comment by ssduracell** [comment]
yes but port was blocked by our it department so it's fixed now thnx for support!
