### ISSUE TITLE
Where is Claim Device Widget?

### ISSUE THREAD

**Issue by ikiour** [thingsboard/thingsboard#2228]
Hello 

I have purchased 2.4.1PE.

I need Claim Device Widget and I cannot find it in widget library. Where can I find it?

Regards, 
Ino Kiourtsidou

**Comment by vvlladd28** [comment]
Hi,
This widget will be added to new version 2.4.2PE

**Comment by ikiour** [comment]
Thank you for the prompt reply.

When this new version will be available?

**Comment by ikiour** [comment]
I need it as soon as possible. Can I have it before the official release of 2.4.2PE?
