### ISSUE TITLE
k8s-delete-all.sh deletes all PVs on a kubernetes cluster outside the thingsboard namespace

### ISSUE THREAD

**Issue by martinnaughton** [thingsboard/thingsboard#2230]
In the script k8s-delete-all.sh it deletes all the resources which is fine except if you have more than one application on your kubernetes cluster besides thingsboard.  PVs, like nodes, are not scoped to any namespace. This will delete all PVs 

`kubectl -n thingsboard delete svc,sts,deploy,pv,pvc,cm,po,ing --all --include-uninitialized`

**Comment by volodymyr-babak** [comment]
@martinnaughton thanks for pointing to this issue.

We'll provide the fix in the next release.
