### ISSUE TITLE
connecting TTN devices to TB community edition

### ISSUE THREAD

**Issue by brauliobarahona** [thingsboard/thingsboard#2233]
Is it possible to connect TTN devices to the community edition of ThingsBoards? We currently send data through our gateway to out TB instance, but would like to test functionality through LoRAWAN before moving on with PE edition. 

Any hints?

**Comment by mp-loki** [comment]
http://cloud.thingsboard.io/ allows you to test ThingsBoard PE features for 1 months for free. Also you may consider 1-month pay-as-you-go licenses
