### ISSUE TITLE
Thingsboard security ---X.509Certificate based authentication

### ISSUE THREAD

**Issue by sad00731** [thingsboard/thingsboard#2243]
Hello, I wonder that if I can start one mqtt transport to support both X.509Certificate based authentication(two way ssl on port 8883) and no encrypted accesstoken authentication(on port 1883). If the answer is yes then how?

**Comment by mp-loki** [comment]
you can use one way ssl connection, where your client accepts the server's public ssl key and authenticates itself with the access token as described here:
https://thingsboard.io/docs/user-guide/access-token/

So basically you can tun two-way ssl and one-way ssl at the same time, but not ssl and non-ssl at the same time

**Comment by sad00731** [comment]
@mp-loki thank you so much, it really helps a lot. Now I use the ssl port 8883 to run two-way-ssl and one-way-ssl at the same time. And I wonder if this is some kind of best practice or principle in  all software ? or just in thingsboard application.

**Comment by Karabiy** [comment]
the best practice for the ThingsBoard is being described within the ThingsBoard docs and regarding any kind of third-party software, you can find those on their officials site
ThingsBoard docs: https://thingsboard.io/docs/
