### ISSUE TITLE
Irritations because the UI prints some things in UPPERCASE that are actually lower- or mixed case

### ISSUE THREAD

**Issue by sglux** [thingsboard/thingsboard#2244]
Thingsboard UI (all revisions from 2.3.0 to 2.4.1) shows arbitrarily some definitions in upper case that have been defined in lowercase which can cause hard to resolve confusion.

**Example:**
create a device named "pstesting" with devicetype "xperiment"
create a device named "PStesting" with devicetype "XPERIMENT"

<img width="547" alt="1" src="https://user-images.githubusercontent.com/25433954/70333973-cfb7e680-1844-11ea-905d-98ed6a4b83b0.png">
<img width="540" alt="2" src="https://user-images.githubusercontent.com/25433954/70334727-3f7aa100-1846-11ea-90fb-e753f5f2d709.png">
<img width="385" alt="3" src="https://user-images.githubusercontent.com/25433954/70334768-53260780-1846-11ea-8685-60511a9aabb7.png">

In the device overview you get two devices displayed both with uppercase "XPERIMENT" but they are actually different device types.

If you edit the second device named "PStesting" the edit window title give the name in all uppercase.
also not consistent.

This "forced uppercase" thing is also there in overview of Customers, Assets, Entity Views and so on.

**Isn't this a CSS issue at all? Should be easy to fix because likely no actual code change is required.**

If one prefers uppercase one can name the resources that way. Those who prefer lower case are on many places at least upset. You can not use correct units in headings and titles? For instance "kWh" or "nW/cm²" turns to "KWH" or "NW/CM²" which not is only ugly it is simply wrong.

**Suggestion:**
Since the backend of thingsboard is case-sensitive in all bits (rule chains, scripts, everywhere) it would be of great help in would also increase clarity if the UI would not modify the case of something at all.

**Comment by datenheim** [comment]
Somehow I noticed only a handful of *.scss files are affected but there are plenty of upper/lowercase conversions in java and javascrip files.
IMO Thingsboard should either [do not allow to create "same-name" resources that differ in case only] OR [display the case correctly].

**Comment by sglux** [comment]
Yes, these case-conversions often puzzle me when playing with the API which is case sensitive of course.

**Comment by fotis400** [comment]
Indeed I have hit this issue too. It is very annoying...

But also breaks some locales!  
For example in Greek we have accents on some letters, `α` vs `ά`. These accents must only be used in lower-case letters, and not in upper-case. Upper-casing strings, makes (at least) the Greek locale to break. TB in Greek is just horrible because of this...

Please stop upper-casing strings!

**Comment by den1jkee** [comment]
This issue fixed in last updates.

Best regards,
Denys.
