### ISSUE TITLE
HSQLDB is missing in thingsboard.yml

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2245]
Hello.

The contribution guide mentions HSQLDB database for development purpose. Sadly thingsboard.yml doesn't contain HSQLDB configuration anymore. Therefore the contribution guide is broken and I can't make changes / suggest changes via pull requests.

Therefore I can't run install_dev_db.sh script.

**Comment by Ultrazombie** [comment]
Please reopen this ticket if still relevant.
