### ISSUE TITLE
Need more control: Ability to compare current data with data for last day, week, month, year;

### ISSUE THREAD

**Issue by danibjor** [thingsboard/thingsboard#2259]
When comparing with historical data, comparing with a week ago is fine. But if you want to compare data that's about one month old, it would benifit if weekday match. Say you compare air quality, comparing sunday (a month ago) with thursday (this month) don't make sense - as traffic on weekends tends to have a different pattern than weekdays. This also applies to comparing a year ago.

**Comment by danibjor** [comment]
This applies to chart widget, on the newly released v2.4.2.

**Comment by danibjor** [comment]
Also, if you compare month to month, subtract one whole month from current dataset would stack up better than -30 days. If you compare december to november (previous month), you get off by one day. This so dates line up (nov 1 to dec 1 and so on)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
