### ISSUE TITLE
customer timeseries timewindow "hide fields" bug

### ISSUE THREAD

**Issue by avlo** [thingsboard/thingsboard#2268]
i've discovered what appears to be a timewindow hide fields bug.

the setup requires customer dashboard containing "timeseries bars - flot" widget created by tenant with hidden "last", "aggregation" and "grouping interval".

![000](https://user-images.githubusercontent.com/5356510/70772778-8cafc300-1db0-11ea-8aab-d7ed004bec8a.jpg)

next, to recreate bug.

from customer dashboard, open a timeseries widget & click "realtime-last day" to show fields are indeed hidden:

![001](https://user-images.githubusercontent.com/5356510/70772922-e617f200-1db0-11ea-917b-96d4b85eedb1.jpg)

use mouse to visually select a custom group interval:

![002](https://user-images.githubusercontent.com/5356510/70772937-f0d28700-1db0-11ea-92e5-8d3516ba30e5.jpg)

click "realtime - last minute".  you will now see "last", "aggregation" and "grouping interval" which were previously hidden, are no longer hidden.  this is the bug.

![003](https://user-images.githubusercontent.com/5356510/70772968-034cc080-1db1-11ea-8c74-ec7282937d31.jpg)

**Comment by mircopz** [comment]
Hi

Try this pull request https://github.com/thingsboard/thingsboard/pull/1974.
Indeed, if you want to hide all timewindow fields, even label should be hidden to user.

**Comment by avlo** [comment]
hello. i've pulled your changes, rebuild and redeployed yet am still experiencing same bug.  in other words, both realtime and history dropdown date ranges are modifiable by customer:

![realtime-not-hiding](https://user-images.githubusercontent.com/5356510/70858811-16dc6080-1f44-11ea-80ce-b799c465f5a0.jpg)

![history-still-active](https://user-images.githubusercontent.com/5356510/70858812-19d75100-1f44-11ea-8464-a9b8f7861f76.jpg)

please recall, the issue occurs once customer- using mouse- visually selects a time segment from the graph and then clicks the dropdown menus.

can you provide deployment instance (or screenshots) of bug fix properly working for you?

**Comment by mircopz** [comment]
@avlo I've finally reproduced you issue, try this pull request (https://github.com/thingsboard/thingsboard/pull/2271): the 'hide' parameters were not copied when creating a new timewindow after zooming action.
Let me know, bye

**Comment by avlo** [comment]
your PR works correctly as expected, thanks

**Comment by mircopz** [comment]
Ok please close this issue, thanks

**Comment by avlo** [comment]
PR works correctly as expected, thanks
