### ISSUE TITLE
Telemetry update - troubleshooting / community

### ISSUE THREAD

**Issue by samthesuperhero** [thingsboard/thingsboard#2269]
Hello,

maybe you can help me, is there any troubleshooting guide, I'm trying to get the data through the HTTP API (sensors are posting data to the ThingsBoard).

If inside the device details I look at the server attributes, there are "true" in active, and the last data time is updating real time correctly.

BUT! if I look at lat telemetry tab, there is nothing! And I can't also build the dashboard, 

so I do everything like in videos and in documentation,

but still struggling to make it working.

Help please!!

**Comment by hamzaslama** [comment]
Hello,

* Try to open swagger page `http://localhost:8080/swagger-ui.html`  
* Send this request `http://localhost:8080/swagger-ui.html#!/telemetry-controller/getTimeseriesKeysUsingGET` :
    -   entityType & entityId (you can have this information from the details of the device `http://localhost:8080/devices`
* Try to send this request `http://localhost:8080/swagger-ui.html#!/telemetry-controller/getTimeseriesUsingGET` :
  -   entityType & entityId (you can have the deivce Id From the details of the device `http://localhost:8080/devices`
  - you can get `keys` from the response of  the first request.

Now you can **check** if you have uploded telemetry to this device.

**Comment by samthesuperhero** [comment]
Hello, at details of the [device](https://user-images.githubusercontent.com/13318288/70906473-866f5000-2017-11ea-8ccb-1bfa13127493.png) there are no entityType or entityId

**Comment by samthesuperhero** [comment]
And, I already see my ```keys``` here in the entity
![settings](https://user-images.githubusercontent.com/13318288/70915550-179bf200-202b-11ea-9267-755dbd4a5ccc.png),

so this means that data is coming, and the ThingsBoard sees keys and the data, **BUT** - for some reason no data in dashboards and it doesn't show the last telemetry!

**Comment by samthesuperhero** [comment]
Looks like I understood, this is not entity type and entity ID, but device type and device ID,

so I made the request and got this:
```
{
  "timestamp": "2019-12-17T07:18:31.914+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No enum constant org.thingsboard.server.common.data.EntityType.thingsee_presence",
  "path": "/api/plugins/telemetry/thingsee_presence/f91df3c0-1b1e-11ea-8343-256bab16e4a4/keys/timeseries"
}
```

Any ideas ?

**Comment by samthesuperhero** [comment]
Solved.

The problem was not in ThingsBoard.

Had to configure Nginx for [proxying WebSockets](https://stackoverflow.com/questions/31211919/spring-websocket-handshake-failed-due-to-invalid-upgrade-header-null).
