### ISSUE TITLE
 Terminating application due to critical License Error INVALID_LICENSE_CHECK_SECRET(107), exit code [-1]...

### ISSUE THREAD

**Issue by partylover** [thingsboard/thingsboard#2273]
I bought a PE license from thingsboard and installed PE on AWS Marketplace. I followed the instructions to run the professional edition but I got the error "Terminating application due to critical License Error INVALID_LICENSE_CHECK_SECRET(107), exit code [-1]..." I DON'T know how to handle it. Here are

**Comment by partylover** [comment]
My thingsboard.log
`2019-12-17 10:19:09,423 [Shutdown Thread] INFO  o.t.s.d.s.BasicSubscriptionService - Terminating application due to critical License Error INVALID_LICENSE_CHECK_SECRET(107), exit code [-1]...
`

**Comment by AlexDoanTB** [comment]
Hello @partylover. This error is thrown once you try to use your license key within closed network. As you may see from the documentation on the website an active internet connection is obligatory. 

"The License Server Client (e.g. your ThingsBoard PE instance) requires an internet connection to the host: license.thingsboard.io to issue license check requests. In case internet connection to the host is not available for more than 24 hours, License Server Client may shutdown ThingsBoard instance."

**Comment by partylover** [comment]
@AlexDoanTB  Thanks for the reply

But my instance cannot be contacted license.thingsboard.io may be because our Firewall is blocked. Can you tell the port to connect to? So that I can unlock it

**Comment by partylover** [comment]
thank you i'm open port 8080 it's work

**Comment by kastayou** [comment]
> Hello @partylover. This error is thrown once you try to use your license key within closed network. As you may see from the documentation on the website an active internet connection is obligatory.
> 
> "The License Server Client (e.g. your ThingsBoard PE instance) requires an internet connection to the host: license.thingsboard.io to issue license check requests. In case internet connection to the host is not available for more than 24 hours, License Server Client may shutdown ThingsBoard instance."

Does it mean that Thingsboard PE cannot be used in a closed network? Even with a perpetual licence? 
Our servers are not and will not be connected to the outside world. Does it mean that thingsboard PE is not a possible solution for us?

**Comment by AlexDoanTB** [comment]
@kastayou Once we add offline activation this (utilizing with completely isolated network) will be possible. For now the license check requires internet active connection.

**Comment by lbekaddour** [comment]
> @kastayou Once we add offline activation this (utilizing with completely isolated network) will be possible. For now the license check requires internet active connection.

any updates on this feature ? We also want to use a licence within a closed network with no access to internet

**Comment by AlexDoanTB** [comment]
Hi @mahmutsalman @lbekaddour ,

The offline license and platform deployment are available. But the price is, for sure, higher compared to the online licenses. 
You can request the offline license via the Contact Us form. Refer your request to Alex.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by maksonlee** [comment]
> Hi @mahmutsalman @lbekaddour ,
> 
> The offline license and platform deployment are available. But the price is, for sure, higher compared to the online licenses. You can request the offline license via the Contact Us form. Refer your request to Alex.

it is reasonable that price is higher compared to the online licenses, but about five times the price? i don't quite understand why an offline license feature takes so much.

**Comment by AlexDoanTB** [comment]
> 
> it is reasonable that price is higher compared to the online licenses, but about five times the price? i don't quite understand why an offline license feature takes so much.

Let's be frank: TB PE is a commercial product. The license is protected by online checks. The offline build one can distribute or spoil onto the darknet. How the licensee then should conduct business? Reasonable? 

On a side note: GH issues should refer to the TB CE. It seems to be moveton to discuss here non-CE related topics.
