### ISSUE TITLE
Obtain list of devices with their attributes

### ISSUE THREAD

**Issue by dlazaroi** [thingsboard/thingsboard#2275]
Hello,
I'm starting to use Thingsboard and, after looking at its API, I see there is an endpoint to obtain the list a devices in a customer or in a tenant. Then, for each device, one can retrieve the attributes associated to it.
Is there any way to obtain a list of devices **and** their attributes in a single call (filtering devices by customer, tenant or whatever)? I didn't find any visualization showing this in the dashboard either. This would be great for many of my use cases, where I want to show a table of devices with some properties, and doing a call for each device would perform extremely poorly.
Thanks!

**Comment by Karabiy** [comment]
Hello,
About visualization on a Dashboard
You may use "Device admin table" widget which is contained in "Entity admin widgets" bundle. For your alias, you can select "Filter type"="Group Entities", "Type"="Device" and "Select Entity Group"="All". Then you may specify all the attributes you want to take a look on

**Comment by dlazaroi** [comment]
Thanks for your answer! I see that internally it obtains the data through a websocket. Would this be the recommended way to do it to get the data by another system, or is this more an internal API?

**Comment by vvlladd28** [comment]
Hello,
You cannot get all the data to a single call. You need two calls: (GET /api/tenant/devices) and (GET /api/plugins/telemetry/DEVICE/{entityId}/values/attributes/SERVER_SCOPE) for him
