### ISSUE TITLE
Thingsboard compatibility with Amazon Managed Apache Cassandra Service

### ISSUE THREAD

**Issue by mtahle** [thingsboard/thingsboard#2276]
Hello everybody

Did anyone has tested Thingsboard with Amazon Managed Apache Cassandra? Are t planning to integrate with it in the future?
I think the current version of Thingsboard require something like the following to be fully integrated with AWS managed Cassandra Service
ssl_context.load_verify_locations('$HOME/AmazonRootCA1.pem')

**Comment by ashvayka** [comment]
Hi @mtahle . We welcome you or anyone else to submit PR with necessary changes. AFAIK, Managed Cassandra from Amazon does not support materialized views. However, this is not a problem if we use Hybrid mode (PostgreSQL + Cassandra)

**Comment by mtahle** [comment]
> Hi @mtahle . We welcome you or anyone else to submit PR with necessary changes. AFAIK, Managed Cassandra from Amazon does not support materialized views. However, this is not a problem if we use Hybrid mode (PostgreSQL + Cassandra)

Thanks for the answer, I will check that and try my best
