### ISSUE TITLE
Upgrade 2.4.1->2.4.2.1 failed

### ISSUE THREAD

**Issue by alexism7hz** [thingsboard/thingsboard#2277]
Hi,
I just tried to upgrade from 2.4.1 to 2.4.2.1 and the following error occurred:

```
 $ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.1

 ===================================================
 :: ThingsBoard ::       (v2.4.2.1)
 ===================================================

Error creating bean with name 'jpaAttributeDao': Unsatisfied dependency expressed through field 'attributeKvInsertRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'psqlAttributesInsertRepository': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sql.remove_null_chars' in value "${sql.remove_null_chars}"
ThingsBoard upgrade failed!
```
I followed this guide:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-2421

OS: Ubuntu
DB: PostgreSQL on Amazon RDS

When I did `sudo dpkg -i thingsboard-2.4.2.1.deb`, I chose to keep my existing thingsboard.conf and thingsboard.yml files and to not replace them with the new ones. Thanks for your help!

**Comment by Karabiy** [comment]
it is recommended to merge your .yml with the one for the version you are upgrading on so that you can make sure that all the new variables which appeared for the new version exist and then have an upgrade
