### ISSUE TITLE
how to link tasmota to thingsboard ?

### ISSUE THREAD

**Issue by seangelof** [thingsboard/thingsboard#2279]
The normal way to do this is via the thingsboard gateway, as you will need to convert the MQTT payload to what TB consumes. (@ashvayka correct ? )
See this https://thingsboard.io/docs/iot-gateway/mqtt/

However, as an experiment in my company, we have made a hack on the tasmote firmware, so that the MQTT payload can be consumed by TB directly (without a GW mapping) and everything required (url, access token) is configurable from the tasmota web interface.  I did not have time to review/clean the code for publishing thus has remained in our private repo. 

If more people are interested I can publish it, and/or maybe discuss with the tasmota devs on a more future proof approach (e.g. plugin ? different mode?).  Alternatively, we could maintain our code as a fork of tasmota modified for TB and update to latest version once in a while.

_Originally posted by @nikil511 in https://github.com/thingsboard/thingsboard/issues/520#issuecomment-356452786_

**Comment by nikil511** [comment]
Here is how we did it in 2017
https://github.com/nikil511/Tasmota/tree/thingsboard
one could do a cross-compare and reapply it in latest version of tasmota

**Comment by garudaonekh** [comment]
@nikil511 Have looked your code and compare with tasmota 9.4, it looks like a lot has change. Have you try it withe recent tasmota version?

**Comment by nikil511** [comment]
Nope, I have not played with tasmota for some years now. If you just want a
quick and dirty integration, just throw a node red in the middle.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by enesbcs** [comment]
@garudaonekh Its possible with Tasmota, using ESP32 and Berry
https://github.com/enesbcs/tasmota-custom-scripts/tree/main/thingsboard
