### ISSUE TITLE
Map widgets SSL issues

### ISSUE THREAD

**Issue by ssmaurya** [thingsboard/thingsboard#228]
Google and Openstreet maps under widgets lib folder have references to http:// resources. Due to this browsers complain about mixed content when accessing over SSL. Also security lock generally shown for SSL links disappears from browsers, the moment we open any of the map widgets.
 Solution is to change http:// links to https:// for both these map widgets just file.

**Comment by ashvayka** [comment]
Thank you for reporting this. Do you want to submit a pull request for this? We would be happy to see your contribution.

**Comment by ssmaurya** [comment]
I have submitted pull request for this change.

**Comment by ashvayka** [comment]
Please see the warning from CLA Assistant: 
```
Shiv Shankar Maurya seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
```
Once you fix these we will accept the change.

**Comment by ssmaurya** [comment]
Fix committed.
