### ISSUE TITLE
Customer personalization of Device name

### ISSUE THREAD

**Issue by Ktysai** [thingsboard/thingsboard#2284]
Hi there!

HI, there! Is some way for the customer to edit the device name some something similar? The customer send the devices to his clients and wants to personalize the devices to spot more easily their name

All the best!

**Comment by Ktysai** [comment]
I've tried to use "NEW UPDATE SHARED STRING ATTRIBUTE widget", but in the customer dashboard cannot be updated :((

In the Tenant account, there's no problem.

**Comment by agtokty** [comment]
Hi, by design, editing device is restricted to 'tenant' scope in user interface and API. 
I think there is no way to change device name.

**Comment by Ktysai** [comment]
Thank you @agtokty 
On Thingsboard Professional this fortunately can be done

**Comment by agtokty** [comment]
@tavdog this feature also sounds good, maybe some customer has right to change shared attributes, but not all customer.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
