### ISSUE TITLE
getTimeseries API does not return any values.

### ISSUE THREAD

**Issue by highgits** [thingsboard/thingsboard#2288]
When i test the "getTimeseries" API using the swagger UI,  i get an empty response body.
Note that i checked the the "ts_kv" table within the thingsboard data base i found values stored there and it is not empty.
Can anyone help me ? 

![image](https://user-images.githubusercontent.com/57440792/71349768-0f364080-2570-11ea-967e-ff2e32aa686a.png)

![image](https://user-images.githubusercontent.com/57440792/71349850-40167580-2570-11ea-943c-794bbaeb5bd2.png)

**Comment by highgits** [comment]
This problem still persists for me, can anyone help me ?

**Comment by FacelookHK** [comment]
I am having the same issue. I can get something if I don't include "keys" vlaues. But this becomes getting latest timeseries instead.

**Comment by luixal** [comment]
The problem I'm facing is that not all keys I pass are getting returned. I thought maybe there was a keys limit on the community version so I tried to remove one key and add the one not being returned, but it doesn't show up anyway.

Any ideas?
