### ISSUE TITLE
How to determine the equipment online or offline?

### ISSUE THREAD

**Issue by yuyihan666** [thingsboard/thingsboard#229]
How to get the connection status of the device

**Comment by ashvayka** [comment]
This will be available in v1.4. For now you can implement this as a separate microservice

**Comment by mfalkvidd** [comment]
When implementing this, please also consider devices using Sigfox and similar protocols. Online or offline can be a bit tricky to determine for devices that don't use persistent connections.

**Comment by ashvayka** [comment]
Hi! @yuyihan666  and @mfalkvidd . This was implemented long time ago. Sorry for late update of the ticket. See https://thingsboard.io/docs/user-guide/device-connectivity-status/
