### ISSUE TITLE
How does TB to uniquely identify a device? DeviceToken?

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#2296]
When a device want to connect to TB, all that TB needs is the deviceToken. Dose it mean TB identify a device using the devicetoken but not  the deviceid, and using the devicetoken to map the deviceid in the next steps in TB? 

Then, what happens if the tokens of two devices are the same?

And how does a device get its devicename and deviceid using deviceToken?

**Comment by ahmetgalip** [comment]
Access token (deviceToken) is unique to each device, cannot be shared. As far as I know, DeviceToken acts as device identifier but also authorization. You can also access device using deviceID, but you would need X-Authorization (Bearer + token).

https://thingsboard.io/docs/reference/rest-api/

**Comment by lsyer** [comment]
I know a device can push its data using devicetoken, but as a user, I can use the deviceid only to access its info.

So, if a device connected, how could it can get its own deviceid, even using ruleengine?

**Comment by ahmetgalip** [comment]
There are multiple ways to get device id in the api

**Comment by lsyer** [comment]
> There are multiple ways to get device id in the api

For example? I looked and looked, but had no idea. 
Thanks.

**Comment by lsyer** [comment]
OK, I found it. Using the  "originator fields" node. 
Thanks!
