### ISSUE TITLE
Rule engine + machine learning

### ISSUE THREAD

**Issue by caiwanli** [thingsboard/thingsboard#2299]
As far as I know, the thingsboard's rules engine currently simply sets thresholds to filter out unreasonable data.But I wonder if we can integrate machine learning into thingboard's rules engine?For example, I use a neural network model to predict the life of a machine, and when sensor data is entered into the model, I alert the machine that something is about to go wrong.Can these trained models be deployed to rule nodes?

**Comment by dcmr** [comment]
we wait for you complete the task

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
