### ISSUE TITLE
Sending device data to Thingsboard server via Thingsboard gateway

### ISSUE THREAD

**Issue by bcnrao** [thingsboard/thingsboard#2309]
Hi All,
I have ThingsBoard server running on Ubuntu and just installed the latest python based gateway on another Ubuntu. I got the gateway connected to thingsboard.
I am simulating some device Applications to send MQTT data to the gateway(as per the mqtt.json configuration). However, I dont see the device data getting reported to the server from the gateway. Is there a configuration that needs to be enabled for the data to be sent to the server.
I have attached the configuration and connector.log
I see that the broker sends the data to gateway but the debug logs are not printed in the log file which indicates successful receiving of data.
Thanks in advance.
[connector.log](https://github.com/thingsboard/thingsboard/files/4015471/connector.log)

[mqtt_json.txt](https://github.com/thingsboard/thingsboard/files/4015476/mqtt_json.txt)
[tb_gateway_yaml.txt](https://github.com/thingsboard/thingsboard/files/4015477/tb_gateway_yaml.txt)

**Comment by zbeacon** [comment]
Hi, @bcnrao 

We have added deeper logging for MQTT connector please reinstall library from sources using following commands:
```bash
git clone https://github.com/thingsboard/thingsboard-gateway.git
sudo python3 ./thingsboard-gateway/thingsboard_gateway/setup.py install
```
After this try to run again the gateway, and send new logs to us. It looks like exception raised on connection to the external broker.

**Comment by bcnrao** [comment]
Hi @zbeacon ,

Looks like there was a problem with the payload that I was publishing. Since there is no exception handling at the gateway while decoding the payload, I couldn't get the issue. On adding more debug logs I was able to find out the issue.
Now I am able to get my use case running.

Thanks for the support. I will be closing the issue.
