### ISSUE TITLE
Update to 2.4.2.1 fails

### ISSUE THREAD

**Issue by chruetli** [thingsboard/thingsboard#2310]
I try to update to 2.4.2.1 from my old 2.1.0. Starting the thingsboard service fails with the following error: 
`ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist`
As I had problems with the update scripts I did some steps by hand. So it's possible that I missed some steps...

The tables look like:

`thingsboard-# \dt`
`List of relations`
`Schema |         Name         | Type  |  Owner`
`--------+----------------------+-------+----------`
`public | admin_settings       | table | postgres`
`public | alarm                | table | postgres`
`public | asset                | table | postgres`
`public | attribute_kv         | table | postgres`
`public | audit_log            | table | postgres`
`public | component_descriptor | table | postgres`
`public | customer             | table | postgres`
`public | dashboard            | table | postgres`
`public | device               | table | postgres`
`public | device_credentials   | table | postgres`
`public | entity_view          | table | postgres`
`public | event                | table | postgres`
`public | relation             | table | postgres`
`public | rule_chain           | table | postgres`
`public | rule_node            | table | postgres`
`public | tb_user              | table | postgres`
`public | tenant               | table | postgres`
`public | ts_kv                | table | postgres`
`public | ts_kv_latest         | table | postgres`
`public | user_credentials     | table | postgres`
`public | widget_type          | table | postgres`
`public | widgets_bundle       | table | postgres`
`(22 rows)`

**Comment by SergMeleshko** [comment]
Hello,
Do you install previous versions e.g. 2.2, 2.3, 2.3.1, and up to 2.4.2.1?
