### ISSUE TITLE
ESP32 Pico Kit GPIO control and DHT22 sensor  Arduino SDK not working.

### ISSUE THREAD

**Issue by jnstsean** [thingsboard/thingsboard#2311]
try  https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/  
But in my case,The LED controler Can't control LED's . There are always close.  Only the  first time click will be open the LED'S. 

Server: ThingsBoard 2.4.2-1
lib: ArduinoHttpClient 2.7 ;ThingsBoard 0.2; pubsubclient 2.7 ;ArduinoJson 6.9.1
Code:

#include <WiFi.h>           // WiFi control for ESP32
#include <ThingsBoard.h>    // ThingsBoard SDK
#define COUNT_OF(x) ((sizeof(x)/sizeof(0[x])) / ((size_t)(!(sizeof(x) % sizeof(0[x])))))
#define WIFI_AP_NAME "xxx"
#define WIFI_PASSWORD "1234567890"
#define TOKEN "FOc1BbuxcyYPGmcHisJ5"
#define THINGSBOARD_SERVER "192.168.124.25"

#define SERIAL_DEBUG_BAUD    115200

WiFiClient espClient;
ThingsBoard tb(espClient);
int status = WL_IDLE_STATUS;

uint8_t leds_control[] = { 19, 22, 21 };
int led_pwm = 200;
int send_passed = 0;
bool subscribed = false;
int current_led = 0;

int freq = 2000;    
int channel = 0;    
int resolution = 12; 
const int led = 2;
unsigned long lastSend;

RPC_Response processDelayChange(const RPC_Data &data)
{
  Serial.println("Received the set delay RPC method");
  // Process data
  led_pwm = data;
  Serial.print("Set new delay: ");
  Serial.println(led_pwm);
  return RPC_Response(NULL, led_pwm);
}

RPC_Response processGetDelay(const RPC_Data &data)
{
  Serial.println("Received the get value method");
  return RPC_Response(NULL, led_pwm);
}

RPC_Response processSetGpioState(const RPC_Data &data)
{
  Serial.println("Received the set GPIO RPC method:");
  //Serial.println(&data);
  int pin = data["pin"];
  bool enabled = data["enabled"];
  if (pin < COUNT_OF(leds_control)) {
    Serial.print("Setting LED ");
    Serial.print(pin);
    Serial.print(" to state ");
    Serial.println(enabled);
    digitalWrite(leds_control[pin], enabled);
  }
  return RPC_Response(data["pin"], (bool)data["enabled"]); //Can't working with thingsboard.h v0.4
}

// RPC handlers
RPC_Callback callbacks[] = {
  { "setValue",         processDelayChange },
  { "getValue",         processGetDelay },
  { "setGpioStatus",    processSetGpioState },
};

void setup() {
  // Initialize serial for debugging
  Serial.begin(SERIAL_DEBUG_BAUD);
  WiFi.begin(WIFI_AP_NAME, WIFI_PASSWORD);
  InitWiFi();
  ledcSetup(channel, freq, resolution); 
  ledcAttachPin(led, channel);  

  for (size_t i = 0; i < COUNT_OF(leds_control); ++i) {
    pinMode(leds_control[i], OUTPUT);
  }
}

// Main application loop
void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    reconnect();
    return;
  }
  ledcWrite(channel, map(led_pwm, 0, 100, 0, 4095)); 
  if (!tb.connected()) {
    subscribed = false;
    Serial.print("Connecting to: ");
    Serial.print(THINGSBOARD_SERVER);
    Serial.print(" with token ");
    Serial.println(TOKEN);
    if (!tb.connect(THINGSBOARD_SERVER, TOKEN)) {
      Serial.println("Failed to connect");
      return;
    }
  }

  // Subscribe for RPC, if needed
  if (!subscribed) {
    Serial.println("Subscribing for RPC...");
    if (!tb.RPC_Subscribe(callbacks, COUNT_OF(callbacks))) {
      Serial.println("Failed to subscribe for RPC");
      return;
    }
    Serial.println("Subscribe done");
    subscribed = true;
  }

  if ( millis() - lastSend > 2000 ) {
    Serial.println("Sending data...");
    float s = random(10, 60);
    float t = random(10, 40);
    float v = analogRead(36) / 500;
    if (isnan(s) || isnan(t) || isnan(v)) {
      Serial.println("Failed to read data from sensor!");
    } else {
      tb.sendTelemetryFloat("t", s);
      tb.sendTelemetryFloat("l", t);
      tb.sendTelemetryFloat("v", v);
    }
    lastSend = millis();
  }
  // Process messages
  tb.loop();
}

void InitWiFi()
{
  Serial.println("Connecting to AP ...");
  // attempt to connect to WiFi network

  WiFi.begin(WIFI_AP_NAME, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("Connected to AP");
}

void reconnect() {
  // Loop until we're reconnected
  status = WiFi.status();
  if ( status != WL_CONNECTED) {
    WiFi.begin(WIFI_AP_NAME, WIFI_PASSWORD);
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
    }
    Serial.println("Connected to AP");
  }
}

**Comment by ufanders** [comment]
@jnstsean What ESP32 board are you using? You must make sure the LEDs are mapped correctly for your exact board.
