### ISSUE TITLE
Why have microservices more than 2 offline notifications？

### ISSUE THREAD

**Issue by VIRGIL-YAN** [thingsboard/thingsboard#2314]
![TIM图片20200106164544](https://user-images.githubusercontent.com/6737655/71806692-6aa21b80-30a4-11ea-8361-9a0f5b0fd6c9.png)

**Comment by VIRGIL-YAN** [comment]
The online(Time Telemetry) is my custom attribute。
![TIM图片20200106165344](https://user-images.githubusercontent.com/6737655/71807054-66c2c900-30a5-11ea-8e40-f8a0289fe330.jpg)
![TIM图片20200106165441](https://user-images.githubusercontent.com/6737655/71807060-6b877d00-30a5-11ea-9c8b-b25152c45d8c.png)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
