### ISSUE TITLE
No aliases found issue

### ISSUE THREAD

**Issue by clkc-ca** [thingsboard/thingsboard#2315]
Hello,

I've created dashboard states and entity aliases. However, when I try to create a Switch Control widget and choose an entity alias, it says No aliases found. I have multiple aliases.

Do you have any idea about this issue?

Thank you!

**Comment by JodasSenpai** [comment]
I had the same problem. I work on PE so i made dashboard under ALL group tab. When i made a new group of dashboards and made one there it worked.
