### ISSUE TITLE
Persistant rulechain metadata

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [thingsboard/thingsboard#2322]
how do i get a node in a rule chain to append to the msg and metadata instead of overwriting it?

**Comment by vvlladd28** [comment]
Hi,
Maybe a rule node transformation -> script will help you

**Comment by Engineer-of-Stuff** [comment]
So the problem I am facing is how to pull in variables from an external database? I have a config file that is stored in a database which makes it easy to update a device's config and push those values to TB.

My solution is to create an attribute in a device's client attributes that will store that device's config. I use an originator node which doesn't overwrite anything.
