### ISSUE TITLE
Race condition in MqttClientImpl

### ISSUE THREAD

**Issue by lotuc** [thingsboard/thingsboard#2328]
https://github.com/thingsboard/thingsboard/blob/2adfe0c31c35bcc755de4c0d9adfc87f4d639c99/netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java#L410-L411

Suppose nextMessageId is now 0xfffe, Consider execution flow:

```
1. thread1: this.nextMessageId.compareAndSet(0xffff, 1);  // pass
2. thread2: this.nextMessageId.compareAndSet(0xffff, 1);  // pass
3. thread1: this.nextMessageId.getAndIncrement();         // -> 0xffff
4. thread2: this.nextMessageId.getAndIncrement();         // -> 0xffff + 1, causes error
```

**Comment by zmlgirl** [comment]
same problem

**Comment by zmlgirl** [comment]
> https://github.com/thingsboard/thingsboard/blob/2adfe0c31c35bcc755de4c0d9adfc87f4d639c99/netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java#L410-L411
> 
> Suppose nextMessageId is now 0xfffe, Consider execution flow:
> 
> ```
> 1. thread1: this.nextMessageId.compareAndSet(0xffff, 1);  // pass
> 2. thread2: this.nextMessageId.compareAndSet(0xffff, 1);  // pass
> 3. thread1: this.nextMessageId.getAndIncrement();         // -> 0xffff
> 4. thread2: this.nextMessageId.getAndIncrement();         // -> 0xffff + 1, causes error
> ```

you solve it ?

**Comment by ban2derlog** [comment]
Was fixed on 1 April 2020.
 Here is commit: https://github.com/thingsboard/thingsboard/commit/00b5d36e0bf8d8295463018537dbbd5744902b7b
