### ISSUE TITLE
Does clean/unclean session between ts gateway and MQTT borker matter

### ISSUE THREAD

**Issue by cityant** [thingsboard/thingsboard#233]
I checked code in java\org\thingsboard\gateway\extensions\mqtt\client\MqttBrokerMonitor.java in ts-gateway and found that the MQTT session is clean. Does it mean, if ts-gateway restarts it will not get those messages received by the MQTT broker during the time when ts-gateway shuts down? If so, how those messages reach ts?

**Comment by cityant** [comment]
Anyone knows how this work?

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
This does not matter at the moment. We don't support not clean sessions.  However, the attribute updates are pushed from the server to a client, and if the gateway was offline, he can always fetch the latest values.
