### ISSUE TITLE
When compile thingsboard (v2.4.3) in CentOS7, issue found for http build with gradle-maven-plugin failure

### ISSUE THREAD

**Issue by xianbow** [thingsboard/thingsboard#2333]
[INFO] --- gradle-maven-plugin:1.0.8:invoke (default) @ http ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=84437, ConflictMarker.markTime=59398, ConflictMarker.nodeCount=81, ConflictIdSorter.graphTime=54181, ConflictIdSorter.topsortTime=40201, ConflictIdSorter.conflictIdCount=33, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=683498, ConflictResolver.conflictItemCount=79, DefaultDependencyCollector.collectTime=33547459, DefaultDependencyCollector.transformTime=954145}
[DEBUG] org.fortasoft:gradle-maven-plugin:jar:1.0.8
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.3.9:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.2:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.2:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.9:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.9:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.9:compile
[DEBUG]          com.google.guava:guava:jar:18.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.9:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       com.google.inject:guice:jar:no_aop:4.0:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]       org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG]    org.slf4j:slf4j-api:jar:1.7.5:compile
[DEBUG]    org.gradle:gradle-tooling-api:jar:2.13:compile
[DEBUG]    org.codehaus.groovy:groovy-all:jar:2.0.6:compile
[DEBUG] Created new class realm plugin>org.fortasoft:gradle-maven-plugin:1.0.8
[DEBUG] Importing foreign packages into class realm plugin>org.fortasoft:gradle-maven-plugin:1.0.8
[DEBUG]   Imported:  < project>org.thingsboard:thingsboard:2.4.3
[DEBUG] Populating class realm plugin>org.fortasoft:gradle-maven-plugin:1.0.8
[DEBUG]   Included: org.fortasoft:gradle-maven-plugin:jar:1.0.8
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.2
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.9
[DEBUG]   Included: com.google.guava:guava:jar:18.0
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: com.google.inject:guice:jar:no_aop:4.0
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.22
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.6
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.4
[DEBUG]   Included: org.gradle:gradle-tooling-api:jar:2.13
[DEBUG]   Included: org.codehaus.groovy:groovy-all:jar:2.0.6
[DEBUG] Configuring mojo org.fortasoft:gradle-maven-plugin:1.0.8:invoke from plugin realm ClassRealm[plugin>org.fortasoft:gradle-maven-plugin:1.0.8, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo 'org.fortasoft:gradle-maven-plugin:1.0.8:invoke' with basic configurator -->
[DEBUG]   (f) args = [-PprojectBuildDir=/root/thingsboard-2.4.3/transport/http/target, -PprojectVersion=2.4.3, -PmainJar=/root/thingsboard-2.4.3/transport/http/target/tb-http-transport-2.4.3-boot.jar, -PpkgName=tb-http-transport, -PpkgInstallFolder=/usr/share/tb-http-transport, -PpkgLogFolder=/var/log/tb-http-transport]
[DEBUG]   (f) gradleProjectDirectory = /root/thingsboard-2.4.3/transport/http
[DEBUG]   (f) gradleVersion = 2.13
[DEBUG]   (f) mavenBaseDir = /root/thingsboard-2.4.3/transport/http
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@7a9c84a5
[DEBUG]   (f) tasks = [build, buildDeb, buildRpm]
[DEBUG] -- end configuration --
[INFO] jvmArgs: [Ljava.lang.String;@25f6b3c0
[INFO] gradleProjectDirectory: /root/thingsboard-2.4.3/transport/http
[DEBUG] Connecting from tooling API consumer version 2.13
[INFO] Build
Downloading https://services.gradle.org/distributions/gradle-2.13-bin.zip
[INFO] Download https://services.gradle.org/distributions/gradle-2.13-bin.zip
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....

[INFO] Build
[INFO]
[DEBUG] waiting....
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.4.3:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  0.906 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  6.541 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.104 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  7.493 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  1.074 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.442 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  2.001 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.161 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.795 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.994 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.321 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.514 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  2.250 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.102 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.780 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 14.786 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 12.211 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.240 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [  3.923 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 min
[INFO] Finished at: 2020-01-14T06:33:52-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
    at org.fortasoft.maven.plugin.gradle.GradleMojo.execute (GradleMojo.java:270)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf org.thingsboard.transport:http

**Comment by creolive** [comment]
你的maven不能访问http://repo1.maven.org/maven2/的原因。更新下你的maven镜像地址就可以了。

**Comment by ljanik** [comment]
Hi, I'm facing exactly the same issue and can't figure out why. I'm running the build in Gitlab CI, in gitlab-runner image. When I enter the container and run the build  from the cmdline, it works.

I have following setup:
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

I'm using the alimaven mirror. Any ideas?

**Comment by wingsyz** [comment]
> 嗨，我面临着完全相同的问题，无法弄清原因。我正在gitlab-runner映像中的Gitlab CI中运行构建。当我进入容器并从cmdline运行构建时，它可以工作。
> 
> 我有以下设置：
> openjdk版本“ 1.8.0_242”
> OpenJDK运行时环境（内部版本1.8.0_242-8u242-b08-0ubuntu3〜18.04-b08）
> OpenJDK 64位服务器VM（内部版本25.242-b08，混合模式）
> 
> 我正在使用alimaven镜子。有任何想法吗？
> 
> 更新：似乎我的问题有点不同，xianbow无法“安装gradle”，但是我的问题是无法执行构建：
> 
> [错误]无法在项目http：org.gradle.tooling.GradleConnectionException上执行目标org.thingsboard：gradle-maven-plugin：1.0.9：invoke（默认）：无法使用Gradle发行版' [https：// services](https://services.gradle.org/distributions/gradle-2.13-bin.zip)执行构建[.gradle.org / distributions / gradle-2.13-bin.zip](https://services.gradle.org/distributions/gradle-2.13-bin.zip) '。-> [帮助1]
> org.apache.maven.lifecycle.LifecycleExecutionException：无法在项目http：org.gradle.tooling.GradleConnectionException上执行目标org.thingsboard：gradle-maven-plugin：1.0.9：invoke（默认）：无法使用Gradle发行版' https://services.gradle.org/distributions/gradle-2.13-bin.zip ' 执行构建。
> 在org.apache.maven.lifecycle.internal.MojoExecutor.execute（MojoExecutor.java:215）
> 在org.apache.maven.lifecycle.internal.MojoExecutor.execute（MojoExecutor.java:156）
> 在org.apache.maven.lifecycle.internal.MojoExecutor.execute（MojoExecutor.java:148）
> 在org.apache.maven.lifecycle
> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject（LifecycleModuleBuilder.java:81）
> 上的.internal.LifecycleModuleBuilder.buildProject（LifecycleModuleBuilder.java:117 ）在org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder
> org.apache.maven.lifecycle.internal.LifecycleStarter.execute（LifecycleStarter.java:128）
> 的org.apache.maven.DefaultMaven.doExecute（DefaultMaven.java:305）的.build（SingleThreadedBuilder.java:56）
> 。 apache.maven.DefaultMaven.doExecute（DefaultMaven.java:192）
> 在org.apache.maven.cli.MavenCli.doMain（
> MavenCli.execute（MavenCli.java:956）
> 在org.apache.maven.cli.MavenCli.execute（MavenCli.java:956） .java：288）
> 位于org.apache.maven.cli.MavenCli.main（MavenCli.java:192）
> 位于sun.reflect.NativeMethodAccessorImpl.invoke0 （本地方法）
> 位于sun.reflect.NativeMethodAccessorImpl.invoke（NativeMethodAccessorImpl.java:62 ）
> 于 org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced（Launcher.com ）
> 的java.lang.reflect.Method.invoke（Method.java:498）
> 处的sun.reflect.DelegatingMethodAccessorImpl.invoke（DelegatingMethodAccessorImpl.java:43）java：289）
> 在org.codehaus.plexus.classworlds.launcher.Launcher.launch（Launcher.java:229）
> 在org.codehaus.plexus.classworlds.launcher.Launcher.main（Launcher.java:356）
> 的org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode（Launcher.java:415）上
> 由：org.apache.maven .plugin.MojoFailureException：org.gradle.tooling.GradleConnectionException：无法使用Gradle发行版' https://services.gradle.org/distributions/gradle-2.13-bin.zip ' 执行构建。
> 在
> org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo（DefaultBuildPluginManager.java:137）
> 在org.fortasoft.maven.plugin.gradle.GradleMojo.execute（GradleMojo.java:270 ）在org.apache.maven.lifecycle.internal
> org.apache.maven.lifecycle.internal.MojoExecutor.execute（MojoExecutor.java:156）上的.MojoExecutor.execute （MojoExecutor.java:210）
> 在org.apache.maven.lifecycle.internal.MojoExecutor.execute（MojoExecutor.java:148）
> 在org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject（LifecycleModuleBuilder.java:117）
> 在org.apache.maven.lifecycle
> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build（SingleThreadedBuilder.java:56）
> 上的.internal.LifecycleModuleBuilder.buildProject（LifecycleModuleBuilder.java:81 ）在org.apache.maven.lifecycle.internal.LifecycleStarter
> 在org.apache.maven.DefaultMaven.doExecute（DefaultMaven.java:305）
> 在org.apache.maven.DefaultMaven.doExecute（DefaultMaven.java:192）
> 在org.apache.maven的.execute（LifecycleStarter.java:128）。 DefaultMaven.execute（DefaultMaven.java:105）
> 在org.apache.maven.cli.MavenCli.execute（MavenCli.java:956）
> 在org.apache.maven.cli.MavenCli.doMain（MavenCli.java:288）
> 在org.apache.maven.cli.MavenCli.main （MavenCli.java:192）
> 在sun.reflect.NativeMethodAccessorImpl.invoke0（本机方法）
> 在sun.reflect.NativeMethodAccessorImpl.invoke（NativeMethodAccessorImpl.java:62）
> 在sun.reflect.DelegatingMethodAccessorImpl.invoke（DelegatingMethodAccessorImpl.java:43）
> 在
> 在org.codehaus.plexus.classworlds.launcher.Launcher.launch处的java.lang.reflect.Method.invoke（Method.java:498）在org.codehaus.plexus.classworlds.launcher.Launcher处得到增强（Launcher.java:289）
> 。
> 在org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode（Launcher.java:415）上启动（Launcher.java:229）
> 在org.codehaus.plexus.classworlds.launcher.Launcher.main（Launcher.java:356）上
> [错误]
> [错误]
> [错误]有关错误和可能的解决方案的更多信息，请阅读以下文章：
> [错误] [帮助1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [错误]
> [错误]纠正问题后，可以使用命令
> [错误] mvn -rf org.thingsboard.transport 恢复构建。：http
> mesg：ttyname失败：设备不正确的ioctl
> 错误：作业失败：退出状态1

Hello, I also encountered the same problem, how did you solve this problem?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
