### ISSUE TITLE
How to get token without username and password？

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#2334]
Hi，
I am using the thingsboard platform. The third-party application wants to call my API interface. They must use the username and password to generate a token, then set X-Authorization to this token in the request header, so they can successfully call my API
But I  don’t want others to know my platform's username and password, I think it ’s not secure, Is there a API to get my access token? 
If they can get the access token ,when the token is expired, they can use  POST "/api/auth/token" with body {"refreshToken":"refreshedToken"} to get the new token. I think there is no need for them to know my platform's username and password.
By now, how can the third party get the access token without username and password?

**Comment by vvlladd28** [comment]
Hello,
You need to use API POST "api/auth/login", with body {"username": "email","password":"password"}. You gets token and refreshToken.

**Comment by Karabiy** [comment]
you can create the separate users for each third-party application and restrict their permissions to the level which are acquired for those
