### ISSUE TITLE
Compile from source error: Use https://repo1.maven.org/maven2/

### ISSUE THREAD

**Issue by hjlopezr** [thingsboard/thingsboard#2341]
Hi
As mentioned in this post:
https://support.sonatype.com/hc/en-us/articles/360041287334

need change
"http://repo1.maven.org/maven2/" to secure transfer -> "https://repo.maven.apache.org/maven2/"
How to do this?
i cannot find the reference in the files.

![Compile error](https://user-images.githubusercontent.com/59338934/72470411-68c41080-37a6-11ea-8520-e669b98c8c58.png)

**Comment by hjlopezr** [comment]
Solved 1:
In root directory modify pom.xml:
<repository>
       <id>central</id>
        <url>https://repo1.maven.org/maven2/</url>
</repository>

But now:
Access denied to: http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/2.13/gradle-tooling-api-2.13.pom , ReasonPhrase:Forbidden
same problem.
![Compile error 2](https://user-images.githubusercontent.com/59338934/72478327-543c4400-37b7-11ea-8b83-d04930884e4a.png)

**Comment by hjlopezr** [comment]
For the last error (temporal solution), modify:
.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom
same case add S in http
and run "mvn install" without "clean" parameter

**Comment by raheem52** [comment]
can you provide details about 
modify:
.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom


its' not clear what you are referring too .. help in this is appreciated ..thanks

**Comment by raheem52** [comment]
> For the last error (temporal solution), modify:
> .m2/repository/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom
> same case add S in http
> and run "mvn install" without "clean" parameter


@hjlopezr can you provide details about 
modify:
.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom


its' not clear what you are referring too .. help in this is appreciated ..thanks

**Comment by hjlopezr** [comment]
Hi @raheem52 
Let me clarify, during the compile process TB create a temporal files. In my case compile as root and this files are in /root/.m2/repository/.....
And i found the link to download the package for "http" module in this location. I change  the references in this file:
.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom
"http" to "https" and compile again but don't use "clean" parameter, because this parameter delete all the ".m2/repository" and create a clear estructure.

Hope i was clear!
regards

**Comment by bharathivlsi08** [comment]
Thank you @hjlopezr You saved my day.

**Comment by MirkoUgoliniDev** [comment]
Hello @hjlopezr 
I followed all the  step but I still got the  problem

Any suggestions?

Regards
Mirko

**Comment by hjlopezr** [comment]
Hi @MirkoUgoliniDev:
Which version try to compile?
Memory and processor in your server?

**Comment by MirkoUgoliniDev** [comment]
hi, @hjlopezr hjlopezr 

the version is  2.4.3
I'm  building on  Wmware  virtual machine  Ubunto 18  3 Gb


this is the error:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'audit', 'fix' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose npm-session 17881255589b7c2d
5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
5 verbose stack     at Bluebird.all.spread (/usr/lib/node_modules/npm/lib/audit.js:164:19)
5 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:514:35)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
5 verbose stack     at PromiseArray._promiseFulfilled (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
5 verbose stack     at PromiseArray._iterate (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
5 verbose stack     at PromiseArray.init [as _init] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
5 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
5 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
5 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
5 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
5 verbose stack     at PromiseArray._resolve (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose cwd /home/mirko/thingsboard
7 verbose Linux 5.3.0-28-generic
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"
9 verbose node v10.20.1
10 verbose npm  v6.14.4
11 error code EAUDITNOPJSON
12 error audit No package.json found: Cannot audit a project without a package.json
13 verbose exit [ 1, true ]

**Comment by hjlopezr** [comment]
@MirkoUgoliniDev tried to solve this error: "package.json not found".
I compiled in Ubuntu 18.04 LTS using this method:
https://thingsboard.io/docs/user-guide/install/building-from-source/
whit the last release of TB:
https://github.com/thingsboard/thingsboard/releases/tag/v2.4.3

please feel free to ask me for more questions.
