### ISSUE TITLE
Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8

### ISSUE THREAD

**Issue by bobokingbao** [thingsboard/thingsboard#2343]
while i tried to build project by using mvn clean install -DskipTests,i met following issue

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.4.0:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [  1.037 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  2.613 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.109 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  4.132 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.613 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  0.665 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.029 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  3.952 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  0.977 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.447 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.605 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  8.499 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.045 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.909 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [06:04 min]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.016 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [ 22.625 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:53 min
[INFO] Finished at: 2020-01-16T16:53:33+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke failed: Plugin org.fortasoft:gradle-maven-plugin:1.0.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.fortasoft:gradle-maven-plugin:jar:1.0.8 -> org.gradle:gradle-tooling-api:jar:2.13: Failed to read artifact descriptor for org.gradle:gradle-tooling-api:jar:2.13: Could not transfer artifact org.gradle:gradle-tooling-api:pom:2.13 from/to gradle (http://repo.gradle.org/gradle/libs-releases-local/): Access denied to: http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/2.13/gradle-tooling-api-2.13.pom -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf org.thingsboard.transport:http

**Comment by creolive** [comment]
change your maven repo address use aliyun or huawei yun；

**Comment by bobokingbao** [comment]
thx ,after i switch to aliyun maven ,this issue got resolved

**Comment by manueldevjour** [comment]
@bobokingbao where did you change maven repo address?

**Comment by aalkaram** [comment]
@manueldevjour here is how to change it:
edit /etc/maven/settings.xml and insert the following lines under the <mirrors> tag just after line 158:
    <mirror>  
      <id>alimaven</id>  
      <name>aliyun maven</name>  
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>  
      <mirrorOf>central</mirrorOf>          
    </mirror>

Then replace central repo in the main /opt/thingsboard/pom.xml 
replace these lines
903     <repositories>
904         <repository>
905             <id>central</id>
906             <url>http://repo1.maven.org/maven2/</url>
907         </repository>
WITH these lines
903     <repositories>
904         <repository>
905            <id>alimaven</id>
906            <name>aliyun maven</name>
907            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
908         </repository>

I'm still getting errors compiling thingsboard, but here is a useful link that address node & npm versions that you could change at opt/thingsboard/ui/pom.xml

hope it helps and good luck

**Comment by aalkaram** [comment]
@manueldevjour here is a link that show the required change the file "/etc/maven/settings.xml" ; you also have to change the main pom xml file "thingsboard/pom.xml" here it is:
https://laptrinhx.com/maven-replacement-central-warehouse-aliyun-2549426160/
