### ISSUE TITLE
Timestamp is not present in rule chain input message

### ISSUE THREAD

**Issue by ltancerel** [thingsboard/thingsboard#2345]
Hello,

I am implementing a rule chain algorithm for a customer using Thingsboard PE.

This is triggered by an attribute update for some device group, and this triggers a bunch of thing by analysing previous telemetry, especially analysing timestamps relatively.

My problem is that the attribute update "POST_ATTRIBUTES_REQUEST" does not contain any timestamp, so I cannot make timestamp relative analysis.
I did not find a way to add current timestamp, this sounds weird, but I spent several hours on this.

**Comment by ChantsovaEkaterina** [comment]
Hello,
Have you tried to add a timestamp to metadata by Transformation Script rule node like this:
metadata.ts = new Date().getTime();

**Comment by ltancerel** [comment]
Hello,
yes, that is what I figured out at the end.
Thank you for your help
