### ISSUE TITLE
Hide Dashboard breadcrumbs

### ISSUE THREAD

**Issue by Chris-O2** [thingsboard/thingsboard#2346]
Following on from closed Issue #259, is it possible to add a switch in the Dashboard Setting dialog to hide the Dashboard breadcrumbs at the top of the page.
Reason is that I'd like to setup a Custom Menu with links to specific dasboards so the user must use the menu to access data views.  if the Dashboard breadcrumbs are visible then user can circumvent the menu controls.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
