### ISSUE TITLE
Getting  error (“status”:405,“error”:“Method Not Allowed”) upon sending data to Thingsboard device via command line

### ISSUE THREAD

**Issue by SadafShafi** [thingsboard/thingsboard#2349]
I was just sending some data to my device in thingsboard by writing this command on command line

`curl -v -X POST -d "{\"temperature\": 25}" http://demo.thingsboard.io/devices/api/v1/IG4XXXXXXXXXCQM/telemetry
--header "Content-Type:application/json"`

but I get this error message at the last

`{"timestamp":"2020-01-16T13:09:05.031+0000","status":405,"error":"Method Not Allowed","message":"Request method 'POST' not supported","path":"/devices/api/v1/IG4Dxxxxxxxxxxxxxxxxs6CCQM/telemetry"}* Connection #0 to host demo.thingsboard.io left intact`

what's it I am not doing right?
 All the efforts are appreciated 

Following is the whole error message

`Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 104.196.24.70:80...
* TCP_NODELAY set
* Connected to demo.thingsboard.io (104.196.24.70) port 80 (#0)
> POST /devices/api/v1/IGxxxxxxxs6CCQM/telemetry HTTP/1.1
> Host: demo.thingsboard.io
> User-Agent: curl/7.65.1
> Accept: */*
> Content-Type:application/json
> Content-Length: 19
>
* upload completely sent off: 19 out of 19 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 405
< Allow: GET, HEAD
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Content-Language: en
< Transfer-Encoding: chunked
< Date: Thu, 16 Jan 2020 13:09:04 GMT
<
{"timestamp":"2020-01-16T13:09:05.031+0000","status":405,"error":"Method Not Allowed","message":"Request method 'POST' not supported","path":"/devices/api/v1/IGxxxxxxxxxxxs6CCQM/telemetry"}* Connection #0 to host demo.thingsboard.io left intact`

**Comment by Karabiy** [comment]
you can use the swagger UI for the API investigation reasons 
you can refer to this link regarding the REST API:
https://thingsboard.io/docs/reference/rest-api/
you also need to setup the jwt_token for the authorization  in the curl command of yours 
and using this link you also can refer to the TB HTTP API: https://thingsboard.io/docs/reference/http-api/
