### ISSUE TITLE
 Rest API Call Node is not sending POST parameters

### ISSUE THREAD

**Issue by pcollao** [thingsboard/thingsboard#2350]
Hello,

The curl request works fine from shell in thingsboard server. The curl request is:
```
curl -X POST -s \
  --form-string "app_key=abc" \
  --form-string "app_secret=def" \
  --form-string "target_type=app" \
  --form-string "content=simple message for you." \
  https://api.pushed.co/1/push
```
My problem is with 'rest api call node'. The node configuration is:

 Endpoint URL pattern: https://api.pushed.co/1/push
 Request method: POST
 Use simple client HTTP factory: unchecked
 Headers:

 header | value
--------|-------
 app_key | abc
 app_secret | bcd
 target_type | app
 content | simple message for you

Screenshot:
![rest api call node config](https://user-images.githubusercontent.com/47789799/72697746-c4ccc300-3b1f-11ea-8c1a-68bb1607c87e.PNG)

 The out metadata is:
```
 {
    "deviceType": "TypeA",
    "error_body": "{\"error\":{\"type\":\"empty_credentials\",\"message\":\"You must introduce account credentials to make requests. Please read the documentation available in https:\\/\\/about.pushed.co\\/docs.\"}}",
    "error": "class org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized",
    "deviceName": "DemoDevice",
    "ts": "1579489446332",
    "status": "Unauthorized",
    "statusCode": "401"
}
```
The /thingsboard.log just has:
```
2020-01-20 03:38:43,932 [nioEventLoopGroup-15-2] WARN  o.s.web.client.AsyncRestTemplate - Async POST request for "https://api.pushed.co/1/push" resulted in 401 (Unauthorized); invoking error handler
```

So, I think Thingsboard is not sending POST parameters. My thingsboard version is v2.4.1.

**Comment by pcollao** [comment]
I updated to Thingsboard CE v2.4.3 and the problem remains.

**Comment by pcollao** [comment]
I founded a solution. I was trying to add payload in header and that is bad. So, I added an Script Node before Rest Api Call Node. Finally:
![rulenodes](https://user-images.githubusercontent.com/47789799/72771115-9e219180-3bde-11ea-834c-9c0e60123ea7.PNG)

#### Script Node "gen payload"
```javascript
msg = {};
msg.app_key = "abc";
msg.app_secret = "def";
msg.target_type = "app";
msg.content = "hello user";
return {msg: msg, metadata: metadata, msgType: msgType};
```

#### Rest API Call Node "Pushed.co" with two headers
![rest api call node config working](https://user-images.githubusercontent.com/47789799/72771260-2011ba80-3bdf-11ea-8746-0e6fa9e811e5.PNG)

**Comment by escalanterj** [comment]
Hi Pcollao,
I've exactly the dame problem, but it does not work for me, could you give me a clue how to fix it?

thanks!!

BR
