### ISSUE TITLE
UI: Action source for HTML cards ‘On HTML element click’ in Thingsboard PE

### ISSUE THREAD

**Issue by daniauri** [thingsboard/thingsboard#2351]
Hi,

Related to #1817 I want to use a static HTML card to navigate through dashboard states. The action source "On HTML element click" is not available and the example widget by @pgrisu [new_html_value_card.zip](https://github.com/thingsboard/thingsboard/files/3455398/new_html_value_card.zip)
does not work.  
![image](https://user-images.githubusercontent.com/51371774/72724370-6cc7a800-3b83-11ea-8d90-684d3d46d904.png)

Any suggestions?

**Comment by vvlladd28** [comment]
Hi,
Please specify the version of TB you are using.
You may not have updated the database after updating TB or using an older version TB.

**Comment by GauravChoube** [comment]
I'm also facing same issue.
My requirements also same just want to switch dashboard state by click on button or anything on html.
Please help me out 
Or if possible share widget that can import and used 

Thanks in advance

**Comment by ThomasBaumgartner** [comment]
I'm facing the same Issue with version: 2.4.3PE - is there already a solution for this issue? 

Thank you

**Comment by LucasEtchezuri** [comment]
Same problem !  :-(

**Comment by robert-long** [comment]
I am facing the same issue

When trying to create a custom card where the HTML defines static list items each with their own ID, and the JS has 

self.actionSources = function() {
    return {
        'openSettingsDialog': {
            name: 'openSettingsDialog',
            multiple: true
        }
    };
}

which is a reference to the ID.

when dropping the widget into a dashboard and trying to assign a custom action (with html template) it does not work.

The idea being that when i click on the icon, that a dialog box opens that allows me to update shared attributes of the entity of the widget. Each new line item being s different set of shared attributes for the same entity.


Is there a fix for this yet?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
