### ISSUE TITLE
Thingsboard not store some telemetry

### ISSUE THREAD

**Issue by JaviOtero** [thingsboard/thingsboard#2355]
Hi.

I'm using Thingsboard version 2.1.0 with a PostgreSQL database.

I'm sending telemetry via MQTT and I've noticed that some data is  never been persisted in database. My telemetry is something like this:
{
    "field1": "value 1",
    "field2": "value 2",
    "field3": "value 3",
    "field4": "value 4",
    "field5": "value 5",
    "field6": "{stringyfied json}",
}

The field named field6 is a json (in some cases, a very long json) parsed as string. The problem is that all the fields are stored ok except this field6 that, sometimes, isn't saved in database. I inspected the tables ts_kv and ts_kv_lastest and I could check that this field is not persisted.

Regards

**Comment by ismaeil-shajar** [comment]
For json value you need to add back Slash (\) before quotation (") this it my suggestion 
Please write sample message that not saved for you
