### ISSUE TITLE
Asset cannot contain device group

### ISSUE THREAD

**Issue by ltancerel** [thingsboard/thingsboard#2356]
I am using Thingsboard PE.

It seems that asset cannot contain device group that has been defined.
I have to manually add devices one by one within my asset.
Is there a better way to do this or an improvement that could be done ?

**Comment by ashaforost** [comment]
Hi @ltancerel 

From the rule chain you can create a message with the originator as your device group, then use the duplicate to specific group rule node to duplicate this message to each device from the original group, and then just use the create relation rule node. 
A message with an entity group originator can be generated via Scheduler (all events from scheduler go to the root rue chain)

![image](https://user-images.githubusercontent.com/47900737/153203675-f1a374f5-1ab9-46bc-8958-9556970e43bb.png)
