### ISSUE TITLE
Schedule attributes update to multiple devices leads to wrong rule chain behavior

### ISSUE THREAD

**Issue by ltancerel** [thingsboard/thingsboard#2364]
I am using scheduler to trigger activity on a group of devices by publishing attributes.
I tried both SERVER and SHARED scope.

Upon attribute publish, each device has to execute a rule chain sequence, including previous telemetry retrieving and analysis.
It appears that telemetry that is retrieved is not correct, it seems that it retrieves telemetry from multiple devices.

When I publish the attribute individually, my rule chain script behaves correctly.
Is there a better way to trigger rulechain for a group of devices that will eventually work ?

Can someone analyse the rational for telemetry retrieving error in that case ?

**Comment by NCS-Gil** [comment]
I have exactly the same issue, i have to reset a counter of many devices at specific time. Only works for idividual device.
