### ISSUE TITLE
Create csv device telemetry export widget

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2369]
With ThingsBoard PE it's possible to export all shown widget data as csv. I want to add a widget, which allows to export ALL telemetry to csv, without visible display. I don't want to use data aggregation functions or time ranges. I want to export everything, every telemetry send.

How can I achieve this? I know I could use the "Max Values" setting while Data Aggregation is set to None. But I don't want this and I can't be sure if there are more than for example 50000 values. I could set the limit to a higher number (in thingsboard.yml) but that's not a solution.

I tried it with the telemetry-controller (REST-API) but I can't find an ui service which gives the telemetry-controller features to the ui (but I know there is one. The ui does load the data somehow).

Any ideas? Thanks!

**Comment by vvlladd28** [comment]
Hi,
You can use method **getEntityTimeseriesValues** from service **attributeService**. 
Note that there are required values: smartTs and endTs.

**Comment by hamburml** [comment]
Hi @vvlladd28,
thanks for your answer! Will try this later in the day. I haven't used **attributeService** because of the naming - I expected only access to device attributes and not to device telemetry.

Regards

**Comment by hamburml** [comment]
Hi @vvlladd28,

it's working. But I have another issue. The limit is default 100. This is not an issue if I could move to the next page (pagination). Any ideas how this is done?

Thanks!

**Comment by hamburml** [comment]
I was able to fake pagination. I used **getEntityTimeseriesValues** with a limit of 5000 entries. As startTimestamp I set 0, as endTimestamp I set current Date timestamp.

I parsed the result and set the timestamp of the 4999 entry as new endTimestamp. I recursively call **getEntityTimeseriesValues** and check if the result has 5000 entries.

I also use setTimeout(...) so that I don't want to bombard our ThingsBoard instance. Unfortunately after the 17th or 18th request I don't get a response anymore.

Here is the code

```
....
    self.ctx.$scope.exportData = function()
    {
        function getTimeseriesValues(entityType, entityId, datakey, startTs, endTs, limit, entries)
        {
            attributeService.getEntityTimeseriesValues(
                entityType, entityId, datakey, startTs, endTs, limit
            ).then((timeseries) =>{
                console.log(timeseries);
                entries.push(timeseries);
                if(timeseries[datakey].length === limit)
                {   // there could be more entries!
                    //debugger;
                    var newEndTs = timeseries[datakey][limit - 1].ts;
                    setTimeout(() => {getTimeseriesValues(entityType, entityId, datakey, startTs, newEndTs, limit, entries)}, 1000);
                }
                else
                {
                    debugger;
                    return entries;
                }
            });
        }
        
        var $injector = self.ctx.$scope.$injector;
        var attributeService = $injector.get("attributeService");
        var device = self.ctx.datasources[0];
    
        var datakey = device.dataKeys[0].name;
        var entity = device.entity;
        if (!entity) return;
        var entityType = entity.id.entityType
        var entityId = entity.id.id;
        
        var entries = [];
        
        var timeseriesEntries = getTimeseriesValues(entityType, entityId, datakey, 0, Date.now(), 5000, entries);
        
        debugger;
    }
}
```

The exportData() function is used by a button via ng-click.

Here is a Screenshot of the Chrome Dev-Tools:

![image](https://user-images.githubusercontent.com/7239350/73368099-b82f3400-42b0-11ea-8d1c-566cdbd678d0.png)

That's the 503 message of the last request

`{"timestamp":"2020-01-29T14:55:23.420+0000","status":503,"error":"Service Unavailable","message":"No message available","path":"/api/plugins/telemetry/DEVICE/7cacc4d0-bf5a-11e9-b8b3-537002b28e0c/values/timeseries"}`

If I wait some seconds and try the request manually it works. Looks like ThingsBoard blocks it. Why? Aaaand another question: Why is a new HTTP-Request used instead of the available websocket?

Thanks for helping!

**Comment by vvlladd28** [comment]
Hi @hamburml,

Blocking the installation of the number of requests from the user, these parameters are set in the thingboard.yml file. Default values:

**Comment by hamburml** [comment]
Thanks for your answer!

I haven't set these parameters. The defaults are false, so there is no limit - right?

**Comment by vvlladd28** [comment]
Maybe to cloud.thingsboard.io set limit. 
100:1,2000:60 mean 100 requests to 1 second and 2000  requests to 60 seconds.
I have not used WebSocket yet, it may even be better.

**Comment by hamburml** [comment]
We don't use cloud.thingsboard.io - We have our own server with ThingsBoard PE installed.

**Comment by vvlladd28** [comment]
To use a method from widget context subscriptionApi.createSubscription, from example code in widget image-map.

**Comment by hamburml** [comment]
I am sorry, I don't understand.

What do you want to say? Is in the example code of image-map-widget an example for using the websocket?

**Comment by vvlladd28** [comment]
Hi @hamburml,

You got it right.

**Comment by hamburml** [comment]
Strange... May you share a link?
I created an image map widget, see a `new TbMapWidgetV2(...)` call.

The class is inside https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/widget/lib/map-widget2.js

I don't find a createSubscription call here.

**Comment by silva324** [comment]
Hi @hamburml , did you managed to find a solution to export telemetry from a widget ?

**Comment by hamburml** [comment]
Nope and I don't use Thingsboard anymore, sorry.

**Comment by faywong** [comment]
@silva324 

FYI: https://gist.github.com/Engineer-of-Stuff/129badef3e8de319975d474dedbb9d62

but it's a standalone script.

**Comment by faywong** [comment]
Also you can pay $10 for the csv export implement code: https://www.yuque.com/thingsboard/book/yoe8ys (a chinese engineer's things-board enhancement)

**Comment by cowherdboy** [comment]
> Also you can pay $10 for the csv export implement code: https://www.yuque.com/thingsboard/book/yoe8ys (a chinese engineer's things-board enhancement)

@faywong This was for version 3.2.0. Possible to ask him if he has a version for 3.3.4? In 3.2.0 he showed an option to enable export on the dashboard. I don't see the option to enable it in 3.3.4.

**Comment by faywong** [comment]
> see

I have developed an "export to xls" widget in the v3.3.x codebase. You can contact me.

**Comment by cowherdboy** [comment]
@faywong How do I contact you?

**Comment by faywong** [comment]
> @faywong How do I contact you?
You can email me through philip584521@gmail.com

**Comment by GSIOT** [comment]
> Hello, @faywong 
I'm starting with thingsboar, I would like to know more about exporting data
E-mail: gerson@gsweb.com.br

**Comment by faywong** [comment]
Hi guys, you can join a room in discord to discuss the csv data export widget: https://discord.gg/n2J9WwBg
@GSIOT @cowherdboy
