### ISSUE TITLE
No Device Type in Getting Started Guide

### ISSUE THREAD

**Issue by michaelblxck** [thingsboard/thingsboard#237]
Trying to get started with thingsboard.io but I cannot create a new device without entering the Device Type. This is not featured on the getting started video nor the instructions, and there's no clear example of what a Device Type is supposed to be.

**Comment by ashvayka** [comment]
Hi Michael. Today we have uploaded new version of TB to our demo environment. This is v1.3RC. We have not updated the docs yet. For now you can put anything you want there. But I would suggest to put something meaningful. For example the "fridge" or "termometer" or even a particular model of the device. You will be able to use this device type in dashboard to filter devices and in rule filters.
