### ISSUE TITLE
What does the public device status mean?

### ISSUE THREAD

**Issue by Boldyshev** [thingsboard/thingsboard#2371]
We need to embed a dashboard on a website, one way is to make the dashboard and all its devices public. Does it mean smth. else but to make its telemetry visible to anyone? 

For example, will this not allow unauthorized users to delete the device, or make some other unwanted changes in our database? 

I mean the device is public for users only to receive data, or either to send? Does it give rise to some vulnerabilities?

**Comment by edme10** [comment]
If you make your public dashboard you can publish it on your website and whoever enters the site will be able to visualize the board and can only visualize, in the configuration of each widget you must remove all the configuration buttons so that you cannot alter or modify it. 

regards...

**Comment by Karabiy** [comment]
the previous comment is correct.  it is being used for the public dashboard visualization only
