### ISSUE TITLE
ThingsBoard Multitenancy

### ISSUE THREAD

**Issue by hamzaslama** [thingsboard/thingsboard#2376]
Hi,
I just tried to run Thingsboard from the source code with both relationnal approch and hybride approach and i need to know how can i run thingsboard with **physical** separation of tenant (not just logical sepration) .

**Comment by datenheim** [comment]
What is the use case of that?
Not at all possible AFAIK - apart from separate installation on another machine.

**Comment by hamzaslama** [comment]
Hi @datenheim, 
The idea behind physical separation is : when a tenant :
- need to upgrade the capacities (RAM/storage/CPU ...) and others don't.
- don't need to save their info with others.

**Comment by datenheim** [comment]
Still simpler to have multiple separate installations each only carrying a single tenant!?
By the way: what do you mean with "hybrid approach"?

**Comment by datenheim** [comment]
Please close this issue. Issue-Tracker is not a forum per se ;)
