### ISSUE TITLE
Why using different type in same Dao interface for the TenantId

### ISSUE THREAD

**Issue by Hamza-Slama** [thingsboard/thingsboard#2377]
Hi,
Why using different type in same Dao interface for the TenantId : 

https://github.com/thingsboard/thingsboard/blob/0dd313dd61e1d1dbeb89e3f326cb81b944ecabe4/dao/src/main/java/org/thingsboard/server/dao/device/DeviceDao.java#L41

https://github.com/thingsboard/thingsboard/blob/0dd313dd61e1d1dbeb89e3f326cb81b944ecabe4/dao/src/main/java/org/thingsboard/server/dao/device/DeviceDao.java#L50

**Comment by ashvayka** [comment]
No particular reason. You are welcome to clean up this and submit PR
