### ISSUE TITLE
Multi tenant is gone?

### ISSUE THREAD

**Issue by azrin1972** [thingsboard/thingsboard#238]
Hi,
I saw there was a Tenant Menu fro managing Tenants in the video tutorial but the menu is not where to be found in the actual deployment. Was it intentionally removed?

**Comment by ashvayka** [comment]
no-no, it is not gone. The tenant management is under system administrator level. You are probably logged in as a tenant administrator. Please find default logins [here.](https://thingsboard.io/docs/samples/demo-account/)

**Comment by azrin1972** [comment]
Thanks for the clarification
