### ISSUE TITLE
md-dialog(pop-up) in action for widget doesnt hide 

### ISSUE THREAD

**Issue by Allive** [thingsboard/thingsboard#2388]
md-dialog(pop-up) in action for widget if click "back" button in browser doesn't hide. Clicking for empty area or close button is working properly. This bug appears only if previous page is one of the dashboards pages.

**Comment by den1jkee** [comment]
Greetings,
Thank you for your feedback. We are always improving our project and have already fixed this bug in the latest versions of ThingsBoard.

Best regards,
ThingsBoard Team.
