### ISSUE TITLE
i am getting following error in ""Temperature upload over MQTT using Arduino UNO, ESP8266 and DHT22 sensor ""

### ISSUE THREAD

**Issue by Nitheshnithu121** [thingsboard/thingsboard#2398]
[WiFiEsp] Initializing ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Cannot initialize ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
WiFi shield not present

**Comment by devangpa** [comment]
Can you please describe more...... @Nitheshnithu121

**Comment by ismaeil-shajar** [comment]
I don't think your code is arriving to MQTT connection 
Please upload your esp code

**Comment by devb2020** [comment]
@Nitheshnithu121 
Were you able to resolve this..? I'm receiving the same error.

**Comment by suhasdevmane** [comment]
Does it need to install specific firmware to the esp to send data to thingsboard? i am facing same issue

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
