### ISSUE TITLE
How to Control Device IO based on Data received ?

### ISSUE THREAD

**Issue by kp372** [thingsboard/thingsboard#240]
I am trying to control gpio of the device based on the data received. I got rule and plugin aligned for email notification but I don't know what plugin to use to write back to the same/other devices to control its IOs. Am using MQTT. Is any documentation out there related to this?  
Thanks.

**Comment by ssmaurya** [comment]
You can use RPC  with GPIO control widget to enable/digital IOs. If you are using v1.3.0, you have some more control widgets that can be used with rpc
