### ISSUE TITLE
Feature request: minimize widgets

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#2401]
As an operator I want to minimize (=collapse) certain widgets and adapt other widgets to the new layout so they receive more space on the dashboard.

This is useful for a master-detail type dashboard where I can minimize the master view once an item is selected to leave maximum room for the detail view.

**Comment by ssakharova** [comment]
Hello @janbols,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
