### ISSUE TITLE
executive command ‘mvn clean install -Dmaven.test.skip=true’ build failure

### ISSUE THREAD

**Issue by ai026** [thingsboard/thingsboard#2404]
[INFO] Build
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.4.3:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [ 42.067 s]
[INFO] Netty MQTT Client .................................. SUCCESS [01:34 min]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.006 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 54.845 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.438 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [ 25.386 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 18.930 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.012 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [ 44.884 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [ 37.931 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.687 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  3.034 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [ 11.695 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.012 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  5.398 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [02:05 min]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [03:34 min]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.006 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [ 19.740 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:40 min
[INFO] Finished at: 2020-02-11T21:01:36+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project http: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf org.thingsboard.transport:http

**Comment by vvlladd28** [comment]
Hi,
Maybe this command will help: 
`mvn clean install -DskipTests`

**Comment by ai026** [comment]
> 嗨，
> 也许这个命令会有所帮助：
> `mvn clean install -DskipTests`

I tried this command again with the same error

**Comment by bobokingbao** [comment]
change you remote gradle&maven repo to ali

**Comment by ai026** [comment]
thx, i changed remote gradle repo to ali , this issue has been resolved.

**Comment by Arroon** [comment]
> thx, i changed remote gradle repo to ali , this issue has been resolved.

May i have your configration in detail ?

**Comment by ai026** [comment]
> > 谢谢，我将远程gradle存储库更改为ali，此问题已解决。
> 
> 我可以详细说明一下您的配置吗？

改gradle的配置我不记得了，其实就是网络问题，建议你挂个梯子就行了

**Comment by TTnTTT** [comment]
but I not use gradle
