### ISSUE TITLE
What does actors.queue.enabled configuration mean

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#2408]
On of the settings in https://thingsboard.io/docs/user-guide/install/config/ is actors.queue.enabled. Possible values are true/false. A related one is actors.queue.timeout.

What do they do? I know it means "Enable/disable persistence of un-processed messages to the queue", but how does TB do that. Are those messages stored on disk or db? And if so, is there a performance penalty of enabling it?

**Comment by Ultrazombie** [comment]
Parameter deprecated in the latest version of ThingsBoard.
