### ISSUE TITLE
Upgrade AWS 2.3.1 PE to 2.4.3 PE secret license  

### ISSUE THREAD

**Issue by astroas** [thingsboard/thingsboard#2409]
Hello,
I am trying to upgrade Thingsboard PE 2.3.1 on AWS to 2.4.3. I am able to upgrade without any errors but have noticed I need to obtain a License Secret. I am currently paying for a license through Amazon so how do I get the new license to use with 2.4.3 without buying another?
Thanks

**Comment by Karabiy** [comment]
there is no option, for the latest version, there is no option to proceed with an Amazon Native packet. You will need to migrate to the separate EC2 instance, migrate the Database of yours, and then handle the upgrade after buying the license key on the license portal
