### ISSUE TITLE
add new widget (map) failed

### ISSUE THREAD

**Issue by michaelqxd** [thingsboard/thingsboard#241]
hi, guys
i'm trying to add a new widget for thingsboard.
1.  create a new js file at  thingsboard\ui\src\app\widget\lib
2.  modify  map-widget.js
3. insert a entry to system-data.cql

but it don't work:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 10 16:25:12 CST 2017
There was an unexpected error (type=Not Found, status=404).
No message available
 
[map.tar.gz](https://github.com/thingsboard/thingsboard/files/1214181/map.tar.gz)

**Comment by ashvayka** [comment]
Once you add a map-widget.js you don't need to add it to any cql files. Now you can open the widget library and add your widget based on your directive.

**Comment by ikulikov** [comment]
Closing due to an inactivity.
