### ISSUE TITLE
Update Multiple Attributes widget can not send attribute update event!

### ISSUE THREAD

**Issue by minikiller** [thingsboard/thingsboard#2414]
hi!
I create a Update Multiple Attributes widget and assign multi shared attribute to it, when i change values, i found i can not receive update message from my mqtt client! But when i use Update shared double attribute widget  it works well!

Thanks for your help!

**Comment by iBrick** [comment]
+1 have this problem as well. even with single shared attribute

**Comment by ThianHooi** [comment]
@minikiller  Hi there. Would you mind sharing your widget that updates multiple attributes? I am currently working on something similar. Your help will be greatly appreciated.

**Comment by jonrot1906** [comment]
Did you guys set the parameters right? Default configuration for "Update multiple attributes" widget is that all data keys have the "server"-type. You can change that if you click on the crayon next to the data key to edit it, then change to "advanced" and change the datakey type to whatever you want (in this case "shared").

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
