### ISSUE TITLE
How to Connect MQTT sensor to CE  ?

### ISSUE THREAD

**Issue by dcholdings** [thingsboard/thingsboard#2417]
Hi,

I am new to Thingsboard. I have MQTT Temperature Sensor, and the sensor publishes the temperature & humidity in MQTT a fixed topic every 3minutes. I can change the destination IP address but the topic cannot be changed.  

Please help to suggest how can I connect this sensor to CE?

Thanks !

**Comment by minikiller** [comment]
please  refer to this video https://www.youtube.com/watch?v=7PVMBp5YisY, then you can get what you want to know!

**Comment by devangpa** [comment]
That's Easy Create a (device) <( Get Token ) < (Copy token to script where you publish data). just start a data to CE @dcholdings.

**Comment by Karabiy** [comment]
you can have those being connected using the ThingsBoard MQTT device API. 
you can refer to this link regarding those:  https://thingsboard.io/docs/reference/mqtt-api/
