### ISSUE TITLE
doubt about SessionAwareMsg and SessionCtrlMsg process of SessionManagerActor

### ISSUE THREAD

**Issue by xjz** [thingsboard/thingsboard#242]
hi there,
first of all, very appreciate the fantastic work you have done.  I am reading the source code and got a doubt about SessionManagerActor's onReceive method, 

```
public void onReceive(Object msg) throws Exception {
        if (msg instanceof SessionAwareMsg){
            //......
        } else if (msg instanceof SessionTerminationMsg) {
            //......
        } else if (msg instanceof Terminated) {
            //......
        } else if (msg instanceof SessionTimeoutMsg) {
            //......
        } else if (msg instanceof SessionCtrlMsg){
            //......
        } else if (msg instanceof ClusterEventMsg) {
            //......
        }
    }

```
SessionCtrlMsg extends SessionAwareMsg, so if msg is an object of SessionCtrlMsg, the if (msg instanceof SessionAwareMsg) statement at the very beginning will be hit, the if (msg instanceof SessionCtrlMsg) statement has no chance to run, am i misunderstanding something?

I am very sorry if bother someone!

**Comment by ashvayka** [comment]
This is correct. Please move the SessionCtrlMsg to be first if statement and submit pull request.

**Comment by ashvayka** [comment]
@xjz Thank you!
