### ISSUE TITLE
The changes of Settings schema not work

### ISSUE THREAD

**Issue by Fgwan** [thingsboard/thingsboard#2424]
I am tring to custmize one RPC (Control) widget following the instruction https://thingsboard.io/docs/user-guide/contribution/widgets-development/,
1. add html , css  , javascript successfully
2. clear Settings schema and add new json string and save all changes successfully.   
3.  add console.log in js code to debug the self.ctx.settings,    the settings string not changed, it still is the old value . 

Any help would be appreciated

**Comment by vvlladd28** [comment]
Hi all,

Please change/click on your new settings. Maybe you need to clear the cache.

**Comment by Fgwan** [comment]
Hi vvlladd28, 

Thanks for you response. 

I have cleared browser cache serveral times,  and I also tried firefox,  but still not work.

I installed thingsboard-ce , version 2.6.4

![javascript](https://user-images.githubusercontent.com/23446637/74739947-dfb46380-5294-11ea-966a-48430f47c40f.JPG)
![log](https://user-images.githubusercontent.com/23446637/74739965-e93dcb80-5294-11ea-8f0c-d3a54a0c9d7f.JPG)
![settingsschema](https://user-images.githubusercontent.com/23446637/74739971-ed69e900-5294-11ea-9bc7-9209653cd02e.JPG)

**Comment by vvlladd28** [comment]
The old settings are saved if they were set before changing the widget, the only solution is to create a new widget. 
Also, the field does not appear in the settings if it is blank or if its value has not been changed.

**Comment by Fgwan** [comment]
The new widget works in dashboard, the settings info is shown correctly.
