### ISSUE TITLE
Entity assign/unassigned not triggered when claiming/reclaiming devices

### ISSUE THREAD

**Issue by Shawnshank** [thingsboard/thingsboard#2431]
Hi!

Is there a way to detect claims and reclaims in the rule engine? The most obvious is to use the "Entity Assigned" and "Entity Unassigned" message types from the Message Type Switch node, however, I noticed that this will only trigger when a tenant assigns or unassign a device from a customer.

I would suggest that claiming/reclaiming devices should trigger the same event as when a tenant assigns and unassign a device to be able to notice a claim/reclaim in the rule engine.

**Comment by ashvayka** [comment]
Fixed and will be part of 3.3

**Comment by Shawnshank** [comment]
Thanks for the update :+1:
