### ISSUE TITLE
Widget data loading hangs when dashboard is open from public networks (websockets?)

### ISSUE THREAD

**Issue by rdenisyuk** [thingsboard/thingsboard#2435]
Hello
I am using v2.4.2-PE. When I try to open my dashboards from a PC or smartphone from public WiFi networks most of the widgets fail to load (never-ending spinwheel). Same dashboards work fine when I am on private WiFi or cellular networks.
I suspect this is related to websockets connections being blocked by public network proxies. So the question is if it is possible to force http loading for widgets or (ideally) have a fallback mechanism?

Thank you
Rodion

**Comment by Mike2912** [comment]
I have the same problem, do you have a workaround jet?

**Comment by rdenisyuk** [comment]
Not yet... I think there should be some way to force HTTP, apparently this
is how it worked in previous versions

**Comment by Ultrazombie** [comment]
Some kind of network problem, it doesn't depend on ThingsBoard
