### ISSUE TITLE
Some problems while run thingsboard-pe at kubernetes 

### ISSUE THREAD

**Issue by pustian** [thingsboard/thingsboard#2437]
Problem 1:
I can run thingsboard-pe at kubernetes according to https://github.com/thingsboard/thingsboard/tree/master/k8s, 
after I append the license at the env of tb-node container and with 1 replica.

The problem is that when I delete the tb-node pod, the tb-node pod can't rerun, it crashed with the log--Terminating application due to critical License Error ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104), exit code [-1]...

How I can avoid the porblem?

Problem 2:
If the license allow multiple instance,  when the pod of tb-node crashed with ACTIVE_INSTANCES_CAPACITY_EXCEEDED, all of the instances are used and still crashed with the log ACTIVE_INSTANCES_CAPACITY_EXCEEDED?

**Comment by volodymyr-babak** [comment]
@pustian 

this is a known problem and we are preparing a fix for this to persist instance license data during the pod restarts for a next release. 

At the moment please go to your account on http://license.thingsboard.io/.

Then go to 'Subscriptions' ->  'Manage instances' and remove instances from your subscription(s). 

This is a temporary workaround until next release when new images and k8s configuration will be available, that persists licenses per restarts.

**Comment by chfxr** [comment]
@volodymyr-babak 
We have the same problem, every time the service restarts we need to delete the old license lease and restart the pod.
Is there a progress due this issue ?
