### ISSUE TITLE
About the number of alerts

### ISSUE THREAD

**Issue by buster2004** [thingsboard/thingsboard#2458]
According to the video tutorial, I added a temperature alarm, but when I send multiple data that exceeds the alarm value, only the first alarm is on the console, and the others are not visible.And after I dealt with it, the subsequent alerts can't be displayed.

**Comment by buster2004** [comment]
![image](https://user-images.githubusercontent.com/23544684/75317115-19432b00-58a2-11ea-8a3a-69eb84eab2bb.png)

**Comment by buster2004** [comment]
![image](https://user-images.githubusercontent.com/23544684/75317151-337d0900-58a2-11ea-85ed-26e226a5f86b.png)

**Comment by Karabiy** [comment]
There can be only one alarm of a unique type of an alarm can be set
otherwise those will be updated 
for those reasons you can use the type pattern functionality 
you may refer to this regarding those: https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#create-alarm-node
