### ISSUE TITLE
entities table card widget slow load when 1000 devices

### ISSUE THREAD

**Issue by ismaeil-shajar** [thingsboard/thingsboard#2466]
when I try with 1000 device in entities table widget loading are very slow 

![Screenshot from 2020-03-01 15-54-17](https://user-images.githubusercontent.com/48369508/75627006-064b9600-5bd5-11ea-9fdd-05e8791c53ce.png)

**Comment by ismaeil-shajar** [comment]
when I'm show Network events I found widget call  web-sockets  API for all devices one after another without depending one in which page I'm

**Comment by Ultrazombie** [comment]
Please upgrade to the latest version of ThingsBoard. The latest version has a lot of improvements.
