### ISSUE TITLE
2.4.3版本的汉化

### ISSUE THREAD

**Issue by victorzh** [thingsboard/thingsboard#2477]
哪位老铁汉化过这个版本啊，和之前的1.x.x版本本地化方式不一样了啊？不是很熟悉前端，求教各位大神。

**Comment by Karabiy** [comment]
specify the current version of yours 
in case you are being using the CE version, you can edit those directly
in case if you are using the PE version, you can use the "White labeling" for those reasons, the custom translation option
you can refer to this video regarding those: https://www.youtube.com/watch?v=VSNZWl1NjWU
