### ISSUE TITLE
v2.4.3 ui change to Chinese 

### ISSUE THREAD

**Issue by victorzh** [thingsboard/thingsboard#2478]
How to localize this version, is it different from the previous 1.x.x version of localization? Thank you.

**Comment by Karabiy** [comment]
you can use the white labeling feature in case if you are using the Professional Edition version or edit the source code in case if you are using the Community Edition 
In case if it is the Professional Edition, you can use the "White labeling" for those reasons
you need first to download the translation, make all the changes, and then set those as a text and press save, to overwrite the existing one language 
in case if you have already prepared translated json, you can share those with the ThingsBoard officials or create a pull request 
to contact the ThingsBoard officials regarding the custom translation, you can use the contact us form: https://thingsboard.io/docs/contact-us/
