### ISSUE TITLE
FailedScheduling : 1 node(s) had taints that the pod didn't tolerate.

### ISSUE THREAD

**Issue by JackMeyvesi** [thingsboard/thingsboard#2492]
When i run  ./k8s-install-tb.sh command with cassandra database taking this:

 Name:           cassandra-0
Namespace:      thingsboard
Priority:       0
Node:           <none>
Labels:         app=cassandra
                controller-revision-hash=cassandra-75cc86976d
                statefulset.kubernetes.io/pod-name=cassandra-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/cassandra
Containers:
  cassandra:
    Image:       cassandra:3.11.3
    Ports:       7000/TCP, 7001/TCP, 7199/TCP, 9042/TCP, 9160/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      1
      memory:   2Gi
    Readiness:  exec [/bin/bash -c /probe/ready-probe.sh] delay=60s timeout=5s period=10s #success=1 #failure=3
    Environment:
      CASSANDRA_SEEDS:            cassandra-0.cassandra.thingsboard.svc.cluster.local
      MAX_HEAP_SIZE:              1024M
      HEAP_NEWSIZE:               256M
      CASSANDRA_CLUSTER_NAME:     Thingsboard Cluster
      CASSANDRA_DC:               DC1-Thingsboard-Cluster
      CASSANDRA_RACK:             Rack-Thingsboard-Cluster
      CASSANDRA_AUTO_BOOTSTRAP:   false
      CASSANDRA_ENDPOINT_SNITCH:  GossipingPropertyFileSnitch
      POD_IP:                      (v1:status.podIP)
    Mounts:
      /probe from cassandra-probe-config (rw)
      /var/lib/cassandra from cassandra-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qp65s (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  cassandra-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cassandra-data-cassandra-0
    ReadOnly:   false
  cassandra-probe-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cassandra-probe-config
    Optional:  false
  default-token-qp65s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qp65s
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
 

Any idea to solve this ? Thank You.

**Comment by Ultrazombie** [comment]
Some troubles with node, please provide the output from the command kubectl describe node, if the problem is still relevant.
