### ISSUE TITLE
Build from source 2.4.3 fail at server DAO layer

### ISSUE THREAD

**Issue by CharlotteEGM** [thingsboard/thingsboard#2498]
Hi, I am trying to build from source 2.4.3 on Ubuntu 16.04, java version "1.8.0_201", maven 3.3.9, node v10.16.2, npm 6.9.0. 

Build failed at DAO layer, here is the error : 

[INFO] 20 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  0.458 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  2.480 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.013 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  3.966 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.236 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.282 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  0.669 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.007 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  3.467 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  0.820 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.362 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.433 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  0.603 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.005 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.536 s]
[INFO] Thingsboard Server DAO Layer ....................... FAILURE [  3.445 s]
[INFO] Thingsboard Rule Engine Components ................. SKIPPED
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport Service ................. SKIPPED
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.670 s
[INFO] Finished at: 2020-03-06T15:14:42+01:00
[INFO] Final Memory: 79M/809M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project dao: Compilation failure: Compilation failure:
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[26,43] error: cannot find symbol
[ERROR] symbol:   class TsKvCompositeKey
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[27,43] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[34,55] error: cannot find symbol
[ERROR] symbol: class TsKvEntity
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[34,67] error: cannot find symbol
[ERROR] symbol: class TsKvCompositeKey
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[39,9] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[62,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[76,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[88,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[102,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[115,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[129,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvRepository.java:[143,22] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: interface TsKvRepository
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/JpaTimeseriesDao.java:[43,43] error: cannot find symbol
[ERROR] symbol:   class TsKvEntity
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/JpaTimeseriesDao.java:[44,43] error: cannot find symbol
[ERROR] symbol:   class TsKvLatestCompositeKey
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/JpaTimeseriesDao.java:[45,43] error: cannot find symbol
[ERROR] symbol:   class TsKvLatestEntity
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvLatestRepository.java:[20,43] error: cannot find symbol
[ERROR] symbol:   class TsKvLatestCompositeKey
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvLatestRepository.java:[21,43] error: cannot find symbol
[ERROR] symbol:   class TsKvLatestEntity
[ERROR] location: package org.thingsboard.server.dao.model.sql
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvLatestRepository.java:[27,61] error: cannot find symbol
[ERROR] symbol: class TsKvLatestEntity
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvLatestRepository.java:[27,79] error: cannot find symbol
[ERROR] symbol: class TsKvLatestCompositeKey
[ERROR] /home/ubuntu/thingsboard/dao/src/main/java/org/thingsboard/server/dao/sql/timeseries/TsKvLatestRepository.java:[29,9] error: cannot find symbol
[ERROR] -> [Help 1]

Any idea on the "cannot find symbol" issue ?

**Comment by hjlopezr** [comment]
Hi @CharlotteEGM, which's capacity of your server?
sometimes the compilation crash with a few memory or processor.

**Comment by CharlotteEGM** [comment]
Hi @hjlopezr 
Thanks for the reply. 
Actually I upgraded node version to v12, and somehow it worked.

**Comment by BhushanPDS** [comment]
Thingsboard Server DAO Layer ....................... FAILURE
