### ISSUE TITLE
Delete telemetries

### ISSUE THREAD

**Issue by itl20200309** [thingsboard/thingsboard#2499]
Hi all
I am very new in ThingsBoard and I am doing some experiments.
So I have created lots of wrong telemetries that are no useful and I would like to erase.
I am be able to delete attributes, but I can not do the same for telemetries.
How can I do?
I read in other posts that delete a telemetry is a high consuming task, but I suppose that is consuming also having lots of unusual, wrong telemetries.
Thank you very much indeed!

**Comment by hjlopezr** [comment]
Hi @itl20200309  delete directly in the database. Fast and furious!

**Comment by Mr-Jonas** [comment]
Hi
Could you please provide more details on how to do that ?
Its really not clear when you are using demo.thingsboard.io as there seems to be no database anywhere.

**Comment by baot** [comment]
Hello @itl20200309 @Mr-Jonas  , did you check the **/api/plugins/telemetry/{entityType}/{entityId}/timeseries/delete{?keys,deleteAllDataForKeys,startTs,endTs,rewriteLatestIfDeleted}** endpoint in https://demo.thingsboard.io/swagger-ui.html#/telemetry-controller?

**Comment by itl20200309** [comment]
Hi
Thank you for your answers.
I can not reach the link
I will try to explain better my problem: I have a device which generate 2 telemetries (T1 and T2).
Then I have tried to add a couple on aggregated telemetries by means of rule chain.
Now, my devices has 4 telemetries, but only T1 and T2 are correct. So I would like to erase other telemetries, not only their values, but I want disassociate T3 and T4 from my device.

**Comment by Karabiy** [comment]
you can refer to the ThingsBoard REST API for those. It is achievable using the deleteEntityTimeseries REST API REQUEST 
DELETE /api/plugins/telemetry/{entityType}/{entityId}/timeseries/delete{?keys,deleteAllDataForKeys,startTs,endTs,rewriteLatestIfDeleted}
you can use this link to get more information on how to use the ThingsBoard REST API: https://thingsboard.io/docs/reference/rest-api/
