### ISSUE TITLE
how open a timeseries inside a popup when click a action 

### ISSUE THREAD

**Issue by fac79** [thingsboard/thingsboard#2503]
I have a lastvalue widget and I want open a popup with a timeseries chart when clicking an action button. Is it possible to invoke TbFlot inside a custom action?

**Comment by ashaforost** [comment]
Hi @fac79 

We've added such an option since v3.3.
![image](https://user-images.githubusercontent.com/47900737/153205252-035f7fd4-29cb-4e09-b682-86e5ccea638e.png)
![image](https://user-images.githubusercontent.com/47900737/153205310-ad8f0829-4c2e-40a3-b229-1230d1921374.png)
