### ISSUE TITLE
How do I compare current telemetry to past in Rule? (PE)

### ISSUE THREAD

**Issue by tpharaoh** [thingsboard/thingsboard#2504]
I have a simple parameter
flow: int and when telemetry comes in I want 2 checks...

1) against a set value
2) is current telemetry higher than previous

How can I compare to previous value?

Also, related to this, is there a way to save a parameter in the server. For example: incrementalFlow where the value is added or deleted based on a key?

**Comment by tpharaoh** [comment]
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/transform-telemetry-using-previous-record/#step-2-default-previous-counter-node

this should work for question 2, so, only remaining thing, how to set an attribute, in my rule.

**Comment by Karabiy** [comment]
you can use the enrichment node for your reasons 
the originator attributes node can be used for the reasons of yours: https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-attributes
so that you can use those after for the rule chain processing purposes

**Comment by jyzbamboo** [comment]
> you can use the enrichment node for your reasons
> the originator attributes node can be used for the reasons of yours: https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-attributes
> so that you can use those after for the rule chain processing purposes

Thanks Bro.
