### ISSUE TITLE
Passing parameters over dashboards

### ISSUE THREAD

**Issue by Nathan-ma** [thingsboard/thingsboard#2510]
I need to pass a parameter to the next dashboard!

I'm currently doing like this:
```
self.ctx.actionsApi.handleWidgetAction(
                  $event,
                  descriptors[0],
                  entityId, 
                  entityName, 
                  rowIndex);
```
I wanna pass the row index to the other dashboard, but I cant find this parameter anywhere!
Help!

**Comment by Nathan-ma** [comment]
anyone?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
