### ISSUE TITLE
Update shared string attribute input widget problems

### ISSUE THREAD

**Issue by MrZANE42** [thingsboard/thingsboard#2512]
When editing an string attribute in a shared string input widget it's not possible to set string to something starting with + or 0. All leading 0's and + are removed. It seems the data is treated as integer even if it's a string input.

**Comment by den1jkee** [comment]
Greetings,
Thank you for your feedback. We are always improving our project and have already fixed this bug in the latest versions of ThingsBoard.

Best regards,
ThingsBoard Team.
