### ISSUE TITLE
Device string attribute can't be set as json.

### ISSUE THREAD

**Issue by pustian** [thingsboard/thingsboard#2518]
The device data --`{
    "deviceType": "aaaa",
    "messageType": "dataReport",
    "deviceId": "123123213",
    "timestamp": 1577341677913,
    "protocol": "o2o"
}`  works well.

The data --`{
 "deviceType": "aaaa",
 "messageType": "dataReport",
 "payload": {
  "data1": "1.52",
  "data2": "32.17",
  "time_stamp": "1577341671"
 },
 "deviceId": "123123213",
 "timestamp": 1577341677913,
 "protocol": "o2o"
}`  can't work.

The device data will be support?

**Comment by sebastianmenoni** [comment]
Hi!

can you solve this?

Regards

**Comment by PovitruliaV** [comment]
Hi @pustian,
As you can see in the screenshot, sending the second payload works correctly. Thingsboard distinguishes which value type you have sent with your request, including JSON type 
![image](https://user-images.githubusercontent.com/98046079/172127687-7e1308c3-28a8-49ee-b20c-58345332aab9.png)
Regards,
Valeria
