### ISSUE TITLE
Can't create a filter by customer for a dashboard entity alias

### ISSUE THREAD

**Issue by poldown** [thingsboard/thingsboard#2520]
(Tested on Thingsboard v2.4.3)
It seems that the Entity Alias Filter type "*Device search query*" (or any of the other query filter types) doesn't work with the "*Customer*" or "*Current Customer*" Types.

To reproduce the issue:

 1. Open a Dashboard containing an *Entity Alias* or Create one
 2. Edit the Alias
 3. as *Filter Type*, select "**Device search query**" (or any of the other query filter types, the same issue arises there too)
 4. as *Type*, select either "**Customer**" or "**Current Customer**" (and select a default Customer)
 5. as *Device Types*, select a relevant device type (in the demo installation - "**default**")
 6. Save

No matter what the other fields contain - an error will always appear, disallowing saving, saying "No entities matching specified filter were found." though clearly relevant matches exist.

The problem seem to originate, unsurprisingly, in the fact the the corresponding API calls result in empty responses... (e.g "/api/devices" with a specific customer as parameter returns empty results, though the api call /api/customer/{customerId}/devices does work properly)

**Comment by ChantsovaEkaterina** [comment]
Hello,
Do you have any relations set between devices and a selected customer?  To save this alias, you need to have at list one device that has a relation to the customer.

**Comment by tavdog** [comment]
How can a dashboard be created to list all devices assigned to a customer ?

**Comment by PovitruliaV** [comment]
Hi @poldown,
To create a dashboard with this alias, you need to see if links between the devices and the caster they belong to are configured. This alias type is initially based on the relationships between the entities, so it gathers together those devices which are related to the key entity.
![image](https://user-images.githubusercontent.com/98046079/172140739-e8822552-4731-4427-bd41-95c1d3870094.png)
![image](https://user-images.githubusercontent.com/98046079/172140879-55f6b542-3486-4398-a8e1-468a62f71f59.png)
![image](https://user-images.githubusercontent.com/98046079/172140950-f1dd2695-cd7b-4253-87e7-8d7b78f253f9.png)
Regards
