### ISSUE TITLE
How to manage the increasing telemetries? is there a expire mechanism in TB?

### ISSUE THREAD

**Issue by mlboy2001** [thingsboard/thingsboard#2521]
Is there a expire time can be set for telemetries collected by TB? or how we can treat the culmulative data size which may exceed the disk capacity

**Comment by vvlladd28** [comment]
Hi,
Yes, you can set expire time, more details to https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-timeseries-node

**Comment by Karabiy** [comment]
you can also set the monitoring tool for the server of yours so that you can monitor the disk capacity
