### ISSUE TITLE
Hybrid database performance test

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#2523]
Hi, Im new to ThingsBoard. And I am planning a project which involves experimenting with ThingsBoard databases (SQL and NoSQL) for an IoT system that is already built. The system will receive data from around 10,000 devices. Is there any tool that I can use to evaluate the performance of the database under different frequencies of load? And at the same time, see the effect of increasing the amount of connected devices.

Thanks a lot.

**Comment by Karabiy** [comment]
you can refer to this link regarding the performance on different configurations: https://thingsboard.io/docs/reference/performance/

**Comment by fjpa121197** [comment]
Hi, 
I have seen this, and what I understood from it, was that it is related to the publishing of information. However, I don't see any part related to the actual performance of the database (Cassandra), write latency for example. 

I'm more interested in that part, and that is the reason why I asked if there is any third party tool that can help track this, and if so, is there any changes that I need to do  collect similar Cassandra database metrics?

**Comment by Karabiy** [comment]
Those
