### ISSUE TITLE
White labeling version mark and Admin Security Settings

### ISSUE THREAD

**Issue by JasonFarque** [thingsboard/thingsboard#2528]
Using ThingsBoard PE the White Labeling Version Mark works initially but seemingly at random reverts to displaying the text "white-labeling.version-mask" after an unknown time. Additionally the Admin Securities menu text on the left sidebar reverts to reading "admin.security-settings" for all Tenants.

[Example image here](http://www.pigging.com/tmp/labeling-error.PNG)
[self-registration does the same thing](http://www.pigging.com/tmp/self-reg.PNG)

**Comment by ban2derlog** [comment]
Hi, do you try to clean browser cache or open Dashboard on Private\Incognito tab?
