### ISSUE TITLE
Custom Action Editor - How to show HTML and CSS?

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#2536]
Release notes for version 2.4.1 states:
UI: New ‘Custom Action’ editor with HTML/CSS/JS input capabilities;

I'm on version 2.4.3, when I add a new custom action, only JS editor shows up. How do I enable/access the new editor with HTML & CSS?

**Comment by ChantsovaEkaterina** [comment]
Hello,
There is a separate action type - Custom action (with HTML template) next to Custom action.

**Comment by Manusisko** [comment]
> 
> 
> Hello,
> There is a separate action type - Custom action (with HTML template) next to Custom action.

I cannot see such option on the actions editor (Yes, I'm running PE). Could this be a translation bug? I'm using a spanish instance.

**Comment by ChantsovaEkaterina** [comment]
Thank you for clarification. It is really a problem with translation. By accident, the translation text is blank for your language. But you could select this type of action by switching to another language or clicking on a blank area after Custom action option in the selection list, which could be a little bit confusing.  The option is present, but there is no visible text.

**Comment by vvlladd28** [comment]
Hi @Manusisko, 
This is fixed in version 2.5.0. Thank you for reporting this.
