### ISSUE TITLE
MQTT INTEGRATION 

### ISSUE THREAD

**Issue by blackprincess88** [thingsboard/thingsboard#2537]
Hi there!

I am a newbie with a  Pro version of thingsboard. I have some problems using **MQTT Integration** and **Data Converters** for receiving data via MQTT by an external broker. I have followed the video tutorial  [https://youtu.be/BeN5bsDQbdo](url)  where only temperature data is sent and everything works.

Then I modified both Uplink Data Converter and MQTT Integration module in order to receive a JSON with more than one key-value pair, but I receveid errors or only temperature data is showed in the telemetry of the device. I used debug mode and the funny things is that when I use Uplink test decoder it seems to work (i.e. I found my second key-value pair in the telemetry data). Hence the problem should relies on the MQTT Integration

I tried also removing the last part of the default topic as it seems to affect the name of the telemetry variable ("/temperature"). In addition, for my application, I would like to use a custom different topic (i.e. not including tb/mqtt-integration-tutorial) but when I tried to change this field (both in Data Converter and in MQTT Integration) it did not work. 

**For example, this the simple message that I would like to send by mosquitto_pub**: {"temp":30, "hum":15}. What should I have to modify in the MQTT Integration module?I tried also adding a custom "data-type" in the metadata fields.

Thanks in advance for the help!

**Comment by blackprincess88** [comment]
The MQTT Uplink data converter is as follows:

{
  "name": "MQTT Uplink Converter",
  "type": "UPLINK",
  "debugMode": true,
  "configuration": {
    "decoder": "// Decode an uplink message from a buffer\n// payload - array of bytes\n// metadata - key/value object\n\n// decode payload to string\nvar payloadStr = decodeToString(payload);\n\n// decode payload to JSON\nvar data = JSON.parse(payloadStr);\n\n//HOW IS IT POSSIBLE TO USE A DIFFERENT TOPIC??\nvar topicPattern = 'tb/mqtt-integration-tutorial/sensors/(.+)/temperature';\n\nvar deviceName = metadata.topic.match(topicPattern)[1];\n// decode payload to JSON\nvar deviceType = 'sensor';\n// use assetName and assetType instead of deviceName and deviceType\n// to automatically create assets instead of devices.\n// var assetName = 'Asset A';\n// var assetType = 'building';\n\n// Result object with device attributes/telemetry data\nvar result = {\n\n// Use deviceName and deviceType or assetName and assetType, but not both.\ndeviceName: deviceName,\ndeviceType: deviceType,\nattributes: {\nintegrationName: metadata['integrationName'],\n//Firmversion\nfirmwvers: metadata['firmwvers']\n},\n\n////Telemetry\ntelemetry: {\ntemperature: data.temp,\nhum: data.hum,\nrawData: payloadStr\n}\n};\n\n/** Helper functions **/\n\nfunction decodeToString(payload) {\nreturn String.fromCharCode.apply(String, payload);\n}\n\nfunction decodeToJson(payload) {\n// convert payload to string.\nvar str = decodeToString(payload);\n\n// parse string to JSON\nvar data = JSON.parse(str);\nreturn data;\n}\nreturn result;"
  },
  "additionalInfo": null
}

**Comment by Karabiy** [comment]
Please, make sure that you have properly prepared the data converter for those so that you are also mapping the data which you receive. You can have those checks using the "Test Decoder Function" after the integration on clicking.
