### ISSUE TITLE
ts_kv_latest has duplicate rows

### ISSUE THREAD

**Issue by BarlowHall** [thingsboard/thingsboard#2538]
Greetings! I have run into a little problem...

Some of the latest values on some devices have the same value as one of the other entries... I don't exactly know what might cause this, but I did look in the log file and found that every now and then it has an error:

`Caused by: org.hibernate.HibernateException: More than one row with the given identifier was found: TsKvLatestCompositeKey(entityType=DEVICE, entityId=blahblah, key=Key1), for class: org.thingsboard.server.dao.model.sql.TsKvLatestEntity`

And when I check the database, the table does indeed have duplicate rows...

I am using thingsboard v2.3.1 and a Postgresql database.

Just let me know if you need any more info!

Thanks in advance!

**Comment by jnmanchado** [comment]
I have a similar issue but I can't access to log because when I realized of this data inconsistencies the log was already erased. Any ideas of what can be happening?

**Comment by BarlowHall** [comment]
Hello! Sorry for not replying, only just saw it!

I later found out that the problem with the latest values getting the same data as a different value was merely a mistake in the device's code, so it was arriving correct, but my device code was sending the wrong value.

I still don't know what caused error about the duplicate rows in the `ts_kv_latest` table, but I fixed the errors by removing the entries in the database, and they haven't come back.

I hope you got something working.
Again, sorry for the _very_ late reply.

If you have fixed your problem, then I shall close this issue.
