### ISSUE TITLE
Document does not match Version 1.3

### ISSUE THREAD

**Issue by jianglaiyou** [thingsboard/thingsboard#254]
When will the document be updated to version 1.3?

**Comment by ssmaurya** [comment]
I believe documentation wrt v1.3 mainly entity relations is in github.  Which other document are you referring to?

**Comment by jianglaiyou** [comment]
I think importing PostgreSQL is a big step for TB,but  can't find any words related this.What's your thinking?Will PG and Cassandra co-exist and co-operation? and if selected PG,how to scale it?

**Comment by ashvayka** [comment]
@jianglaiyou We have updated all the docs for v1.3. See this [guide](https://thingsboard.io/docs/user-guide/install/linux/#sql-database-postgresql) for example. Does this helps? I will close this issue in a day or two if no comments.

**Comment by nmenoni** [comment]
Hi! I was looking at the documentation and did not say anything about the
new "alarm precessor" since the "alarm deduplication processor" was
deprecated.
Thanks

2017-08-21 8:03 GMT-03:00 Andrew Shvayka <notifications@github.com>:

**Comment by jianglaiyou** [comment]
OK,you can close it

**Comment by Apoorv903** [comment]
Hi all!, I agree nmenoni same things I face not only the document of alarm processor is missing, document related to MQTT plugin is also not available.
I stuck with raising the alarm can any one give me steps which lead to send MQTT msg from thingsboard to client using MQTT plugin, thingsboard v1.3.
thanks!

**Comment by ashvayka** [comment]
Hi everyone, sorry about this. The docs are somehow behind the released features. Will add them as soon as we can.
