### ISSUE TITLE
Using Aggregate Latest Node on Subcustomers' Groups

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#2545]
I'm having the following configuration of customers implemented in my instance:

> Regions - Main Customers
    > Each region has 3-4 Cities - Sub Customers
          > Each city has several asset/device groups with group names that are identical across all sub-customers. (i.e. Tall Buildings, Small Buildings, etc.).

I want to perform aggregation of telemetries in each asset/device group of each sub-customer, and then perform aggregation of those results to each subcustomer/customer.

However: 
 - Aggregate Latest Node only enables me to select Entity Groups from TENANT level. I cannot access  groups of the customers in order to perform aggregation.
 - There isn't any aparent default relation that links Customers together or Groups to customers.

So:
 a) Is there a way to select All Groups of name GROUP_NAME across all customers and subcustomers to be selected as parents for the Aggregate Latest Node?
b) How can I select sub-customers groups of entities to be parents on this Node?
c) If answer to both of the above is "Cannot be done", is there any pre-existing relation between customers that can be queried with a Relations query? and on that links the Customer with it's Entity Groups?
d) If answer to C) is negative: So far the only solution I've found for this is to link all Assets/Devices to their Group, to their Subcustomer, and link all Subcustomers to their Customer with a custom Relation. Is there any simpler way to achieve this configuration?

**Comment by beau-sys** [comment]
I am also having trouble with analytics/aggregation across customers. 
My setup is less complicated - I just have 10 customers in my hierarchy each with the own device groups. I still can't find any way use aggregation rules chains to access data from their devices in this setup.
Any help would be appreciated

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
