### ISSUE TITLE
Widget Library: Editor goes blank when changing tabs

### ISSUE THREAD

**Issue by azrin1972** [thingsboard/thingsboard#255]
TB version: 1.3
Browser: Safari

How to reproduce the bug:
Click to Widget Libraries then try to change the tab from HTML to CSS or other tabs. Once change, the editor goes grey.

**Comment by Ravindranath2511** [comment]
how did you solve this problem?

**Comment by edcline** [comment]
TB Professional on AWS EC2
Browser Chrome and Edge
Same issue as above, widget editor window goes gray, all text disappears.  Widget editor is unuseable.  Has anyone solved or addressed this issue?
