### ISSUE TITLE
k8s deploying with two ip (mqtt,http)

### ISSUE THREAD

**Issue by mashal1996** [thingsboard/thingsboard#2555]
Hi ,
I am trying to deploy the platform using kubernetes in digitalOcean services and it is working fine for me but the problem is when I want to send the data using mqtt protocol, I have to use different ip than what I use to access web_ui.

How to solve it??

thanks,

**Comment by ban2derlog** [comment]
Hi, do you use HAproxy or Ingress on k8s?
Or maybe any other load balancer?

**Comment by ruipoliveira** [comment]
Hi @ban2derlog. I have the same issue. I use the Ingress on k8s. What the best way for use the same URL for UI + MQTT + MQTTS? 

I use this guide : https://thingsboard.io/docs/user-guide/install/cluster/gcp-monolith-setup/
In this sample, I have an IP for UI and MQTT, but that matters to me.

Thanks
