### ISSUE TITLE
How to share ThingsBoard database?

### ISSUE THREAD

**Issue by ahmedwahdan** [thingsboard/thingsboard#2558]
I have a website for users to add, configure, see the status of their devices.
The devices push the data to the server using TCP sockets.
I want to use the features of Thingsboard like MQTT, Certificates, ruls, etc, but also I need to keep my current website desing.
I thought of sharing the database of the platform, but I don't if this is possible or not and whether there are other better solutions.

Thanks

**Comment by ban2derlog** [comment]
Hi, do you resolve this issue?
