### ISSUE TITLE
How to Enable HTTP over SSL in Thingsboard server

### ISSUE THREAD

**Issue by vcumapathi** [thingsboard/thingsboard#2559]
I need to enable SSL configuration in thingsboard for secure HTTP connection.

thingboard.yml SSL code:

> ssl:
>     # Enable/disable SSL support
>     enabled: "${SSL_ENABLED:false}"
>     # Path to the key store that holds the SSL certificate
>     key-store: "${SSL_KEY_STORE:classpath:keystore/keystore.p12}"
>     # Password used to access the key store
>     key-store-password: "${SSL_KEY_STORE_PASSWORD:thingsboard}"
>     # Type of the key store
>     key-store-type: "${SSL_KEY_STORE_TYPE:PKCS12}"
>     # Alias that identifies the key in the key store
>     key-alias: "${SSL_KEY_ALIAS:tomcat}"   log_controller_error_stack_trace:
> "${HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE:true}"

**Comment by paolofrs** [comment]
Hi! I am looking for the same configuration... I havent't found a solution yet. Did you have a look at this [issue](https://github.com/thingsboard/thingsboard/issues/370)? One user proposed this [configuration](https://gist.github.com/mfalkvidd/3920bd5035806a583b5c1e20eaddabae). It does not work for me since I do not want to use a web proxy (see my [issue](https://github.com/thingsboard/thingsboard/issues/2647)) but I am using it as starting point to correctly set up the ENV in thingsboard.yml file.

**Comment by Karabiy** [comment]
First you need to enable the SSL for the server 
    ....
    # Enable/disable SSL support
    enabled: "${SSL_ENABLED:true}"
 ....
Generate the PKCS12 format key or get those from the provider. Instruction on how those can be generated can be found on the theme-related forums, 
Create a keystore directory in /usr/share/thingsboard/conf (owner and group set to thingsboard for directory keystore)
Move the keystore.p12 file created to directory /usr/share/thingsboard/conf/keystore (owner and group set to thingsboard for file keystore.p12)

**Comment by Arsal973** [comment]
> First you need to enable the SSL for the server
> ....
> # Enable/disable SSL support
> enabled: "${SSL_ENABLED:true}"
> ....
> Generate the PKCS12 format key or get those from the provider. Instruction on how those can be generated can be found on the theme-related forums,
> Create a keystore directory in /usr/share/thingsboard/conf (owner and group set to thingsboard for directory keystore)
> Move the keystore.p12 file created to directory /usr/share/thingsboard/conf/keystore (owner and group set to thingsboard for file keystore.p12)

After following these steps I ended up with "Bad Request" message when opening the server URL over HTTPS

**Comment by Karabiy** [comment]
you can set up proxy for the HTTPS reasons, for example - Nginx, Apache2, Haproxy can be used, for example.
For the debugging purposes, you can put the logs of yours in this thread, so that the issue of yours can be investigated.

**Comment by Arsal973** [comment]
In my case, we already have an AWS Elastic Load Balancer to terminate the SSL connection so don't want to enable another proxy (Nginx, Haproxy, etc.) For this purpose, we have enabled  SSL in the configuration file configured path to the Keystore as you described above.TB server starts without any errors but responds with the message "Bad Request this combination of host and port requires TLS" in the browser over HTTPS.
Is it necessary to configure the proxy when SSL is enabled in TB configuration file?

**Comment by Karabiy** [comment]
@Arsal973 in this case you can forward data with an HTTP to the ThingsBoard server from the ALB, so that it will be an okay. 
Post the logs also in case if you want to have some more detailed answer regarding the issue, those might be useful to get better understanding for the particular case.

**Comment by Arsal973** [comment]
@Karabiy We are forwarding requests to TB over HTTPfrom ALB and it works fine. We face the issue when trying to download the dashboard. The reporting server constructs the base URL target dashboard with port 80 over https
![Dashboard_download_error](https://user-images.githubusercontent.com/7512847/102758787-0fd90100-4395-11eb-9f08-0fc512e9820d.png)
![Untitled](https://user-images.githubusercontent.com/7512847/102759121-837b0e00-4395-11eb-814a-0d6de94d3fe5.png)

**Comment by fuzonmedia** [comment]
anybody solved this problem ? I am facing the same problem "Bad Request
This combination of host and port requires TLS."

**Comment by Karabiy** [comment]
@fuzonmedia make sure you have installed haproxy according to the guide 
example for ubuntu: https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/
for https serving purposes

**Comment by fuzonmedia** [comment]
@Karabiy i am following https://thingsboard.io/docs/user-guide/mqtt-over-ssl/#self-signed-certificate-generation this technique to run TB in SSL & MQTT over SSL. 
Do i still need proxy ?

**Comment by Karabiy** [comment]
@fuzonmedia you have referred to the guide to run the MQTT over SSL, though, not the ThingsBoard (HTTP) over SSL. In case if you want your ThingsBoard to run with an HTTPS (browser access general) you should consider to proceed up with the installation of the proxy and the haproxy will be the best choose to my mind. 
In case if you are running ThingsBoard with an HTTPS mode, please, share the configuration .yml within this thread

**Comment by fuzonmedia** [comment]
@Karabiy if you check my shared link it says mqtt over ssl at the same time it also allow to use same SSL certification to use for HTTPS. I am trying to use that same technique. I have generated self signed certificate using the same why they explained then i used that keystore to YML file e.g : https://prnt.sc/134bjyn. Then i used thingsboard conf file to expose 8883 for MQTTS. 

My idea is to enable SSL over HTTP along with MQTT over SSL using self signed certificate as they are depends on each other. 
Any idea whats wrong ? 

Note : thingsboard log dont have any error.

**Comment by Ultrazombie** [comment]
Please use haproxy for redirect with self-sign certificate
