### ISSUE TITLE
[Bug] Mqtt Integration "io.netty.handler.codec.mqtt.MqttMessage cannot be cast to io.netty.handler.codec.mqtt.MqttPublishMessage"

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#2565]
When the payload of my mqtt message exceeds +/- 8KB, Thingsboard throws this error and disconnects from the broker.
![image](https://user-images.githubusercontent.com/32327026/78008460-fa700280-733f-11ea-82e1-9767ef7c21c6.png)

I did some searching for a limit in the payload size, and there is a configuration that limits this, but it defaults to 65536 bytes / 64kB (transport.mqtt.netty.max_payload_size). So the problem shouldn't be there.
But I've noticed an issue on an other github repository (https://github.com/moquette-io/moquette/issues/375). There the MqttDecoder had a max decoding size of 8092 bytes, which could be the same problem here.

**Comment by DejonckheereWard** [comment]
I found where the limitation is comming from,
does anyone here know how to update "maxBytesInMessage" in thingsboard.
The default value is 8092 and is used as the max message size in the MqttDecoder() class.
(definition maxBytesInMessage: https://github.com/thingsboard/thingsboard/blob/master/netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientConfig.java)
(usage: https://github.com/thingsboard/thingsboard/blob/2a2a0f9caf3b94a1052d833c412e1f06b4f4af06/netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java#L521)

**Comment by Tikarei** [comment]
I'm getting this error as well but not sure what causes this, other than using multiple IoT Gateways with OPC UA connectors.

**Comment by DejonckheereWard** [comment]
> I'm getting this error as well but not sure what causes this, other than using multiple IoT Gateways with OPC UA connectors.

Can I ask what ThingsBoard version you are using? I'm not running the latest version, and still have the same issue.
I get the error whenever i send an MQTT message larger than 8kB (8192 bytes) to ThingsBoard. I am using my own broker and having ThingsBoard subscribe to one topic of my broker.

**Comment by Tikarei** [comment]
I'm on 3.0.1., I get this error when subscribing to roughly over 50 device telemetries with an OPC-UA server. I'm using Kafka, so the the event queue shouldn't have a problem. However, I'm using memory storage with the IoT Gateway, which could be the issue. I have not been able to get the file storage option working.

**Comment by amber-aw** [comment]
Yes, I noticed that it does not restart too. Unfortunately, I have solar-powered devices that connect only a few times a day. Breaking the messages up would not be good for me, because I would use more power for more transmissions.

**Comment by DejonckheereWard** [comment]
I understand, i'm able to split up my messages because they get preprocessed by a script in between the IoT devices & thingsboard. That way i'm easily able to split up the messages into multiple chunks.

**Comment by jllanosf** [comment]
> 
> 
> When the payload of my mqtt message exceeds +/- 8KB, Thingsboard throws this error and disconnects from the broker.
> ![image](https://user-images.githubusercontent.com/32327026/78008460-fa700280-733f-11ea-82e1-9767ef7c21c6.png)
> 
> I did some searching for a limit in the payload size, and there is a configuration that limits this, but it defaults to 65536 bytes / 64kB (transport.mqtt.netty.max_payload_size). So the problem shouldn't be there.
> But I've noticed an issue on an other github repository ([moquette-io/moquette#375](https://github.com/moquette-io/moquette/issues/375)). There the MqttDecoder had a max decoding size of 8092 bytes, which could be the same problem here.

I've found the same issue when trying to send bigger mqtt messages into thingsboard, the solution is to change the NETTY_MAX_PAYLOAD_SIZE parameter in the thingsboard.yml configuration file. It comes as 65536 bytes by default.

**Comment by DejonckheereWard** [comment]
Yeah, that's what I found as well, the problem is that the setting has no effect.
![image](https://user-images.githubusercontent.com/32327026/92440034-24a9d400-f1ac-11ea-9b56-85965d9e2707.png)
This is the current setting (default) and still crashes on messages that are bigger than 8kB.

**Comment by jllanosf** [comment]
That's strange, I had exactly the same log and problem and making that parameter bigger solved it.
I'm working with 18 tri-axis accelerometers, sending everything in one single packet, when I was sending only the X-axis the message was 7,5kB, but when I started sending every axis (22.6 kB message) it started having this problem. I set the NETTY_MAX_PAYLOAD_SIZE to 300000 and it worked again.

**Comment by DejonckheereWard** [comment]
Would you mind letting me know what ThingsBoard version you are running?
Also, the only way this would make sense is if it's not bytes but bits. so 65536bits would be 8kiB if converted.
I'll try changing this parameter with that in mind and see the results.

**Comment by amber-aw** [comment]
I agree with DejonckheereWard's comments about the bits and bytes, and also thought that the 65536 value could not be restricting the incoming messages since they could not be bigger than 64K. Nevertheless, if jllanosf has tested that the change solves the issue, I am more than happy to make this change too.
BTW, I am using v3.1.1PE.

**Comment by jllanosf** [comment]
I'm using Thingsboard v3.1.1CE.
I agree with both of you, it would only make sense if the config is in bits, I just roughly made it triple the default value and it worked.

**Comment by yefimov-andrey** [comment]
NETTY_MAX_PAYLOAD_SIZE applies to all the incoming messages to the MQTT API, in the next release there will be a configurable value on MQTT integrations which will regulate the maximum length of incoming message to those.

**Comment by 425804004** [comment]
> 我使用的是3.0.1。，使用OPC-UA服务器订阅大约50种以上的设备遥测时，会出现此错误。我正在使用Kafka，因此事件队列应该没有问题。但是，我在IoT网关中使用内存存储，这可能是个问题。我无法使文件存储选项正常工作。

Hello, how many keys does your gateway have per connector. I'm testing the gateway bottleneck. When I use five connectors, 1500 keys per connector. He will make the same mistake. When I have a connector with more than 1500 keys, it will have a data update error
