### ISSUE TITLE
Widget manipulation controls not visible on a black background

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#257]
This picture illustrates what I mean:

![image](https://user-images.githubusercontent.com/295338/29607814-b649bf96-87f2-11e7-9069-6c6566d669cc.png)

I don't know what the best solution would be. Perhaps have a white outline of the icons, or invert the color scheme.

**Comment by ikulikov** [comment]
Just change "Text color" to some lighter color inside "Settings" tab of widget.
![image](https://user-images.githubusercontent.com/8308069/31602829-cc3022ac-b266-11e7-998e-21a592e56f63.png)
