### ISSUE TITLE
Postgresql - SchemaManagementException: Schema-validation: missing table [ts_kv]

### ISSUE THREAD

**Issue by agtokty** [thingsboard/thingsboard#2570]
Hi all,

I am trying to build and run tests with updated master branch but , this error throwing by hibernate; 

`Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [ts_kv]`

StackTrace : https://gist.github.com/agtokty/e7ce9102328a18fd089b8c287e910e05

may the problem be caused by the tv_kv table has [partition on ts column](https://github.com/thingsboard/thingsboard/blob/194d628bfd42bed8b50bdb0d3b2c017ac6a371fc/dao/src/main/resources/sql/schema-ts-psql.sql#L26)?

Btw, I was uncomment [this line]( https://github.com/thingsboard/thingsboard/blob/194d628bfd42bed8b50bdb0d3b2c017ac6a371fc/dao/src/test/java/org/thingsboard/server/dao/SqlDaoServiceTestSuite.java#L39) for postgresql tests.

**Comment by DManstrator** [comment]
I have a similar issue. Also using Postgres with partitioning, using sql files to execute initial SQL statements (liquibase) and after each statement as successful, I get the missing table exception before the program is starting.

I searched through a lot of resources but couldn't find an answer.

@agtokty When I set `hibernate.hbm2ddl.auto=update` instead of validate, I didn't get the exception anymore but instead I got the exception that the table already exists (lol). Maybe it helps you somehow.

**Comment by DManstrator** [comment]
@agtokty I debugged the hibernate code over the last hours and found this:
https://github.com/hibernate/hibernate-orm/blob/9c6805fdd36ba96b2ca6dc3dd9d4b82f08d29e04/hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java#L66-L91

`tableTypes` is used to filter tables when they are calculated in the `getTables` method and is set to `[TABLE, VIEW, MATERIALIZED VIEW]` by default (check line 337 of that class). But partitioned tables have the `PARTITIONED TABLE` type. So I checked how that array is defined and saw that you can configure it via. some settings (check code). I found out that it is managed by `org.hibernate.cfg.AvailableSettings.EXTRA_PHYSICAL_TABLE_TYPES` which is defined as `hibernate.hbm2ddl.extra_physical_table_types`.

So I've added `hibernate.hbm2ddl.extra_physical_table_types=PARTITIONED TABLE` to my `hibernate.properties` and now all tables are found.

Hope that helps you.

**Comment by agtokty** [comment]
@DManstrator thanks!

**Comment by jamesdh** [comment]
This is a problem in general w/ hibernate and the use of partition tables. I don't even know what thingsboard is but this issue helped me solve this problem in our current project. Thank you @DManstrator for digging into this!
