### ISSUE TITLE
Long string of numbers parsed as number

### ISSUE THREAD

**Issue by bskrt** [thingsboard/thingsboard#2572]
*for reference: TB 2.4.3 PE*

I'm getting device ids over mqtt that are strings of the following type:  `31534147313130300083212353937`.

In the received json they are still strings, in the database too (stored in str_v column), but once I try to show them in an entities table widget, the string becomes a number.

I checked this by doing a post-processing `return typeof(equipment_id)` which showed up as number.

Pretty sure this is a bug.

**Comment by ssakharova** [comment]
Hello @bskrt,

If you still have this issue, you can change the configuration parameter by updating and setting the _JSON_TYPE_CAST_ENABLED_ env variable in the **thingsboard.conf** file to false:

`export JSON_TYPE_CAST_ENABLED=false`

After that, you need to restart your Thingsboard service to apply the settings.
