### ISSUE TITLE
[BUG] rpc-reply-tutorial,,"status":503,"error":"Service Unavailable","message"

### ISSUE THREAD

**Issue by lesliechung88** [thingsboard/thingsboard#2573]
I refer to this teaching document and an error occurs

[https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-reply-tutorial/](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-reply-tutorial/)

`root@ubuntu:~# curl -X POST -d '{"method": "getTemperature", "params":{}}' http://localhost:8080/api/v1/0E2GoD82WeXkYYkwrRikent-Type:application/json"`
**{"timestamp":"2020-04-03T07:09:00.729+0000","status":503,"error":"Service Unavailable","message":"No message available","path":"/api/v1/0E2GoD82WeXkYYkwrRik/rpc"}**

The documentation mentions:  "Add Filter Script node and connect it to the Message Type Switch node with relation type **RPC Request**."
But I didn't find "RPC Request", found "**RPC Request from Device**" and "**RPC Request to Device**"

2.4.3 CE ubuntu deb install

**Comment by waoywssy** [comment]
I just pick the “RPC Request from Device”, got the same issue, failed to follow the device side RPC demo.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
