### ISSUE TITLE
Timeseries - Flot Chart: Comparison Trace Bug

### ISSUE THREAD

**Issue by falkkyburz** [thingsboard/thingsboard#2574]
-> Same issue with Timeseries Bar
Thingsboard Version 2.4.3
To reproduce, tick the "Enable Comparison" check mark in "Comparison Settings" under the "Advanced" tab. 

Issue:
In real time mode, the "Comparison" trace data timewindow is not updated when new telemetry arrives for the real time trace. This results in the "Comparison" trace being shiftet out of the plot on the left.  Reloading the page results in loading in the full comparison trace, which is then shifted out again. I didn't find a setting that altered the behavior.

Unfortunately I can't debug the code (not a developer). I looked at subscription.js and flot-widget.js but couldn't find an issue. All the code updating the timewindow seems sensible.

Maybe I'm missing something?

Best Regards
![image](https://user-images.githubusercontent.com/30900572/78397851-4518a580-75f2-11ea-98a7-b530ccb95b92.png)

**Comment by yeduy** [comment]
Hi,

I am struggling with the sam issue. Did you find any solution?

**Comment by FalkMusick** [comment]
No sorry, no solution yet. I stopped using this feature for the moment.

**Comment by vvlladd28** [comment]
Thank you! We will fix it soon.
