### ISSUE TITLE
ClusterRpcServiceGrpc.java:[193,92] 错误: 找不到符号

### ISSUE THREAD

**Issue by ioprotocol** [thingsboard/thingsboard#258]
when i compile the thingsboard,  failed with this message:
thingsboard/application/target/generated-sources/protobuf/grpc-java/org/thingsboard/server/gen/cluster/ClusterRpcServiceGrpc.java:[193,92] 错误: 找不到符号
I compile both v1.3 and v1.2.3, they have this problem both, can you give me some help?
thanks very much!

**Comment by ioprotocol** [comment]
I hava find the reason, it is because of google protoc buffer.

**Comment by chp008** [comment]
How do you solve this problem, because I also encounted it.

**Comment by lxhtkj** [comment]
i also encounted the same problem,i protoc is 3.0.2

**Comment by lxhtkj** [comment]
> I hava find the reason, it is because of google protoc buffer.
hey,what is reason?

**Comment by sarveshr** [comment]
Anybody found solution to this problem? I am getting same error.

**Comment by codeayit** [comment]
Anybody found solution to this problem? I am getting same error.

**Comment by paoyingshidai** [comment]
Anyone solve this problom?
