### ISSUE TITLE
org.thingsboard.server.common.msg.gen

### ISSUE THREAD

**Issue by waytai** [thingsboard/thingsboard#2588]
How to resolve this problem?
Thingsboard --> compile

**Comment by agtokty** [comment]
first of all, what is your problem ? can you be more specific ?, I guess you need to build org.thingsboard.common.message module to get generated proto classes.

open terminal in **common/message** then run  the `mvn install`

**Comment by waytai** [comment]
thank you

**Comment by anjoean** [comment]
> first of all, what is your problem ? can you be more specific ?, I guess you need to build org.thingsboard.common.message module to get generated proto classes.
> 
> open terminal in **common/message** then run the `mvn install`

Hi, I run the `mvn install`，but I got this error in my IDEA IDE：
“ Could not resolve dependencies for project org.thingsboard.common:message:jar:3.3.0-SNAPSHOT: **Failure to find org.thingsboard.common:data:jar:3.3.0-SNAPSHOT** in https://repo1.maven
.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of maven.org has elapsed or updates are forced”.
![error](https://user-images.githubusercontent.com/20274072/128985353-45c991e6-187d-45cd-b1da-4cf78124e6fa.jpg)

Can you help me or share this file "org.thingsboard.common:data:jar:3.3.0-SNAPSHOT" ?
thx

**Comment by Ahrovan** [comment]
thingsboard\common\message\src\main\java\org\thingsboard\server\common\msg\TbMsg.java:31:45
java: package org.thingsboard.server.common.msg.gen does not exist

I see this message. please check #problem #bug
