### ISSUE TITLE
Clutter in the dashboard view

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#259]
I'd like to report a minor aesthetics issue with the dashboard view. The name is shown in several places, so it is redundant:

![image](https://user-images.githubusercontent.com/295338/29627996-5bac2596-8834-11e7-8e87-b8e992b6ce4c.png)

Can't A, B and C be collapsed into a single element - A? It is in the most prominent position on the screen, so all the other onces are not just cluttering the screen, but they're also competing for attention.

Another issue is that the `dashboard` part in the breadcrumbs on top - the navigation panel is always visible on the left side, therefore they both take space and compete between themselves.

**Comment by ashvayka** [comment]
The B and C are now identifiers of a state. Dashboard may have multiple states. We will have a video how to use this. But I understand what you are talking about. I will provide more comments later.

**Comment by ashvayka** [comment]
Just disable "Keep toolbar opened" In your main dashboard settings.
