### ISSUE TITLE
XLSX export in UTC, not local time

### ISSUE THREAD

**Issue by glancia** [thingsboard/thingsboard#2591]
I'm running version 2.4.3 PE and found out that files exported in XLS format are OK with the timestamps, but files exported in XLSX are showing UTC time.

How to fix that?

Thanks

**Comment by yeduy** [comment]
Hi,

I am struggling with the same problem. Could you find any solution?

**Comment by vvlladd28** [comment]
Hi all,
Thank you for the reported problem! We will fix it with a new version.

**Comment by glancia** [comment]
Hi, can you confirm if it was fixed in any of the recent releases?

**Comment by RondoRonaldo** [comment]
From ThingsBoard 2.5.2 version this bug was fixed so the time has timezone in both of the XLS and XLSX formats.
