### ISSUE TITLE
widget error: typeerror:null is not an object (evaluating 'this.contextValueClone.translate')

### ISSUE THREAD

**Issue by yingzhangOK** [thingsboard/thingsboard#2593]
Switch between horizontal and vertical screens(portrait to landscape)

With iOS devices, I get below errors on "digital gauges" widgets, but working fine on Win 7, 10, macos:

widget error: typeerror:null is not an object (evaluating 'this.contextValueClone.translate')
widget error: typeerror:undefined is not an object (evaluating 'self.ctx.gauge.update')

![17288453-AD69-4CBE-8AE3-C378B00A9955](https://user-images.githubusercontent.com/15194833/78852974-53cae680-7a50-11ea-866f-097a17ec7dc7.jpeg)

Any solution to these issues?

**Comment by Cody-Hayes97** [comment]
Have you found out how to fix the problem?
