### ISSUE TITLE
Changing min and max values in gauges - unable to enter minus '-' sign 

### ISSUE THREAD

**Issue by Corei52500k** [thingsboard/thingsboard#26]
Hello Developers,

i started using thingsboard this week, and i noticed something while playing with it. I tried changing the max and min values for one of the gauges, but was not able to enter the minus sign "-" in the Minimum value Field. I had to use the Scrollwheel or the up and down arrows to achive neagtive values.

![image](https://cloud.githubusercontent.com/assets/24847458/21573765/b68b795e-cee8-11e6-8ff2-6aa66d46fb61.png)

Systeminfo:
Ubuntu 16.04.1 x64 Serverversion
thingsboard-1.0.2.deb

If you need more Information please let me know, i will provide it then.
Greetings from Germany.

Note: I updated my post, because i found the option to reduce the ticks, which solved one descriped problem.

**Comment by ashvayka** [comment]
Hi @Corei52500k,

Thank you for reporting this. We will fix in next minor release.

**Comment by ashvayka** [comment]
I will update the issue when it is done.

**Comment by ashvayka** [comment]
This is fixed in v1.0.3 http://blog.thingsboard.io/2017/01/thingsboard-103-minor-release.html
