### ISSUE TITLE
Alarm Widget - Custom Action for "On row click "

### ISSUE THREAD

**Issue by solutionsisa7** [thingsboard/thingsboard#2600]
Hi All,

I have an alarm widget in a higher level dashboard state concentrating alarms coming from many different devices. I need to implement the following: when clicking in the alarm row it is necessary to open a new dashboard state with the details of the alarm originator device. For that I am using the widget "On row click" action of the type "Custom Action". Below the code I am using:

var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice (entityId.id).then(function(device) 
{
var params = {
        entityId: entityId,
        entityName: entityName
    };

    Widgetcontext.statecontroller.openState('operacao', params, false);

});

However, when a row is clicked in the widget, nothing happens.

Could someone please help understand what I am doing wrong here?

Thanks.

**Comment by vvlladd28** [comment]
Hi, 
Maybe you need the action of the type "Navigate to new dashboard state".

**Comment by solutionsisa7** [comment]
> Hi,
> Maybe you need the action of the type "Navigate to new dashboard state".

Thanks for your comment. That is not working.  It opens the new dashboard but do not transfer the context of the device that generated the alarm. That's why I trying to use a custom action with some code to inform the new dashboard state the correct device. But with the code I shared the new dashboard state is not even open.

**Comment by t0mmyz7** [comment]
@solutionsisa7 hi, this is a bit dated, but perhaps still relevant for you.

see this for a solution: https://github.com/thingsboard/thingsboard/issues/3147
