### ISSUE TITLE
Injecting Dependencies !

### ISSUE THREAD

**Issue by Nathan-ma** [thingsboard/thingsboard#2603]
I want to inject this simple dependency so I can use it on my tables : 
```
(function(angular) {
  var ngContextMenu = angular.module('directive.contextMenu', [])
    .run(function() {
        console.log("Running");
    });

  ngContextMenu.directive('cellHighlight', function() {
    return {
      restrict: 'C',
      link: function postLink(scope, iElement, iAttrs) {
        iElement.find('td')
          .mouseover(function() {
            $(this).parent('tr').css('opacity', '0.7');
            console.log("familia")
          }).mouseout(function() {
            $(this).parent('tr').css('opacity', '1.0');
          });
      }
    };
  });
})(window.angular);
```

I'm new to Angular and thingboard as well. I thought I could just push it into the dependency lists of module "thingsboard" using : 
`angular.module('thingsboard').requires.push('directive.contextMenu')`

and it kind of work, I can see the "Running" msg being printed on the console, but I cant make the directive work.

```
<table md-table class="cell-highlight">
```

Any help is appreciated, thank you!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
