### ISSUE TITLE
How to access the thingsboard device telemetry data or the device data using python code

### ISSUE THREAD

**Issue by Nitheshnithu121** [thingsboard/thingsboard#2610]
Hello
       Can any one suggest me a python code which is used to access the thingsboard device telemetry data or the device data

**Comment by eykamp** [comment]
You can take a look at my very much under-development project that allows you to do just this:

https://github.com/eykamp/thingsboard_api_tools

I'm in the process of rewriting to make it more object-oriented, but it works great as-is for retrieving telemetry and attributes (as well as other things).

**Comment by HendAdell** [comment]
I want to do the exact same thing, if anyone can help please ?

**Comment by eykamp** [comment]
Use my code (either the library, or steal the bits you need).  It's marked as "not ready for prime time" because its incomplete -- what's there works well.

This code is utterly untested, but will get you pointed in the right direction.

    mothership_url = "www.wherever.org"
    thingsboard_username = "who_are_you"
    thingsboard_password = "xyzzy"

    tbapi = TbApi(mothership_url, thingsboard_username, thingsboard_password)

    device = tbapi.get_device_by_name("device_name")
    
    latest_temp = tbapi.get_latest_telemetry(device, "temperature")
    all_humidity = tbapi.get_telemetry(device, "humidity")     # Lots more options on this method
