### ISSUE TITLE
OpenWeatherMap

### ISSUE THREAD

**Issue by cristianfagiani** [thingsboard/thingsboard#2620]
Playing with latest telemetry map widget and would like to add map layers (i.e. precipitation_new) using OWM server.

I got convinced that to do this i need to implement my own widget (possibly starting from original map widget code...).

Am i right or there are other possible solutions ?

Using v. 2.4.3PE

Thanks

**Comment by vvlladd28** [comment]
Hi, 
Yes, you can implement your widget, but there is another way to use setting "custom provider" and added a link to the titles map.

**Comment by cristianfagiani** [comment]
Did try with urls found on openweathermap web site but no success.
Could you send me some example url ?
Thx

**Comment by vvlladd28** [comment]
Hi,
Example to the official site:  https://openweathermap.org/api/weathermaps
