### ISSUE TITLE
Hiding a widget's title panel makes it uneditable

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#2625]
In an attempt to implement some of the widgets discussed in https://github.com/thingsboard/thingsboard/issues/60, I hid the title panel of my custom widget, by writing `self.ctx.hideTitlePanel = true` in `onInit()`.

While this hides the panel, as expected, it also makes it impossible to edit this widget in the future. The place where the "edit" icon is normally shown isn't there (presumably because it is a part of that panel). Here's what I mean:
![image](https://user-images.githubusercontent.com/295338/79346850-250ead80-7f33-11ea-9f29-1310c66f9d1e.png)

Is there a way to reclaim this editing ability?

**Comment by Nonta-w** [comment]
A bit late but incase someone still looking, just right click on the widget to open edit menu.

But "self.ctx.hideTitlePanel = true" only work when widget is added for me. After refresh, it seem like config in widget's setting override it and the panel comeback.
