### ISSUE TITLE
IoT device （ESP32 dual core utilized) crashes as ThingsBoard service Restarts

### ISSUE THREAD

**Issue by algovera** [thingsboard/thingsboard#2626]
I am using ESP32 and leveraging dual core in order to ensure the main logic does not get blocked, I used SDK ThingsBoard provided.  

One cores handling device IO and main logic, the other is handing ThingsBoard communication,  network / wifi and MQTT.

Everything works fine with dual core, on the network core, Wifi reconnect works too.

The **issue** happens, when I **restart ThingsBoard service** (through docker), simulating unexpected server shutdown, ESP32 crashes at the point **where ThingsBoard reconnect takes place**.

This issue does not happen, if I disconnect WIFI and restart ThingsBoard service, the ESP32 will keep trying to reconnect.

Will supply the error code from console shortly.

Did anyone encounter this issue?  
Any idea how to handle this?

21:13:15.549 -> 
21:13:15.549 -> Waiting for WiFi... WiFi connected
21:13:15.549 -> IP address: 
21:13:15.549 -> 192.168.1.82
**21:13:15.549 -> Connecting to ThingsBoard node @ 122.116.56.69**
21:13:20.571 -> E (38685) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
21:13:20.571 -> E (38685) task_wdt:  - IDLE0 (CPU 0)
21:13:20.571 -> E (38685) task_wdt: Tasks currently running:
21:13:20.571 -> E (38685) task_wdt: CPU 0: Core0Function
21:13:20.571 -> E (38685) task_wdt: CPU 1: loopTask
21:13:20.571 -> E (38685) task_wdt: Aborting.
21:13:20.571 -> abort() was called at PC 0x400da6af on core 0
21:13:20.571 -> 
21:13:20.571 -> Backtrace: 0x4008f1c0:0x3ffbe170 0x4008f3f1:0x3ffbe190 0x400da6af:0x3ffbe1b0 0x400877a9:0x3ffbe1d0 0x4000bfed:0x3ffb4530 0x4008ca51:0x3ffb4540 0x4008b687:0x3ffb4560 0x4012de46:0x3ffb45a0 0x4011c968:0x3ffb45c0 0x400d39b9:0x3ffb45e0 0x400d39e1:0x3ffb4610 0x400d34cd:0x3ffb4630 0x400d3546:0x3ffb4670 0x400d1555:0x3ffb46a0 0x400d2741:0x3ffb46d0 0x4008b8d5:0x3ffb46f0
21:13:20.606 -> 
21:13:20.606 -> Rebooting...

Source code
'
void IoT::reconnect() 
{
  while (!tb->connected()) 
  {
    wifiAP.addAP("xxxx","xxxxx");
    Serial.println();
    Serial.print("Waiting for WiFi... ");

    while(wifiAP.run() != WL_CONNECTED) {
        Serial.print(".");
        delay(500);
    }

    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());

    Serial.print("Connecting to ThingsBoard node @ ");
    Serial.println(thingsboardServer);
    // Attempt to connect (clientId, username, password)
    if ( tb->connect(thingsboardServer, TOKEN) ) {
      Serial.println( "[DONE]" );
    } else {
      Serial.println( "[FAILED] :  retrying in 2 seconds" );
      // Wait 2 seconds before retrying
      delay( 2000 );
    }
  }
}
'

**Comment by ban2derlog** [comment]
Hello, does this issue persist on latest ThingsBoard version?
