### ISSUE TITLE
Control widget to connect to sensor device

### ISSUE THREAD

**Issue by oanhrung** [thingsboard/thingsboard#2638]
I config a gateway device with 2 thermometer device on Thingsboard. When I want to send rpc command to gateway, I use rpc button widget and it will send message to topic: v1/devices/me/rpc/request/$request_id. When I want to send "connect request" to a thermometer, I don't know which widget to use, it should send message to topic: v1/gateway/connect with content: {"Device": "thermometer-001" }

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
