### ISSUE TITLE
cassandra Docker image build issues when run mvn clean install -DskipTests -Ddockerfile.skip=false 

### ISSUE THREAD

**Issue by ismaeil-shajar** [thingsboard/thingsboard#2639]
when run mvn clean install -DskipTests -Ddockerfile.skip=false to build project and docker images the following error fire 
`Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.5:build (build-docker-tb-cassandra-image) on project tb: Could not build image: The command '/bin/sh -c curl https://www.apache.org/dist/cassandra/KEYS `

**Comment by ismaeil-shajar** [comment]
solution work for me is replace [https://www.apache.org/dist/cassandra/KEYS](url) in Dockerfile in 
msa/tb/docker-cassandra/
by
[https://downloads.apache.org/cassandra/KEYS](url)
the solution let build finish without error . 
but I'm not working with cassandra image so I don't know if image work fine or not

**Comment by CooL16** [comment]
Please confirm the issue has been resolved

**Comment by ismaeil-shajar** [comment]
Solved
