### ISSUE TITLE
How to achieve interaction between widgets

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2640]
Suppose my dashboard contains two widgets (Google Maps and Card)
[Similar to this sample](https://demo.thingsboard.io/dashboard/3a1026e0-83f6-11e7-b56d-c7f326cba909?state=W3siaWQiOiJkZWZhdWx0IiwicGFyYW1zIjp7fX0seyJpZCI6ImRpc3RyaWN0X2J1aWxkaW5nX3ZpZXciLCJwYXJhbXMiOnsiZW50aXR5SWQiOnsiaWQiOiJkMTRkOTcxMC03YzE1LTExZTctODM1ZC1jN2YzMjZjYmE5MDkiLCJlbnRpdHlUeXBlIjoiQVNTRVQifSwiZW50aXR5TmFtZSI6IkRpc3RyaWN0IEIiLCJlbnRpdHlMYWJlbCI6IkRpc3RyaWN0IEIiLCJzZWxlY3RlZF9idWlsZGluZyI6eyJlbnRpdHlJZCI6eyJpZCI6ImFjYTg4NzIwLTdjMTYtMTFlNy04MzVkLWM3ZjMyNmNiYTkwOSIsImVudGl0eVR5cGUiOiJBU1NFVCJ9LCJlbnRpdHlOYW1lIjoiQnVpbGRpbmcgQjEiLCJlbnRpdHlMYWJlbCI6IkJ1aWxkaW5nIEIxIn0sInRhcmdldEVudGl0eVBhcmFtTmFtZSI6InNlbGVjdGVkX2J1aWxkaW5nIn19XQ%3D%3D&publicId=322a2330-7c36-11e7-835d-c7f326cba909)

Q: After clicking the device in the card, I want Google Maps to move to the device and open the infowindow. But I don't know how to achieve it (or which action api), is there a corresponding tutorial (programming)?

**Comment by ecmap** [comment]
solved

**Comment by mgonzSVQ** [comment]
How do you dolved?

I have same problem and I'm stuck with this.
