### ISSUE TITLE
Devices widged handles IDs and labels column values as numbers

### ISSUE THREAD

**Issue by MrZANE42** [thingsboard/thingsboard#2644]
As you can see in this picture IDs are handled like non-string values, in this case integers.
the device labeled 77 should in fact be named 000000077 and all of the other labels and IDs should be pure hexadecimal values. 

![image](https://user-images.githubusercontent.com/7534100/79740157-7fc35300-82ff-11ea-81e6-fb4d4cb0decd.png)

**Comment by den1jkee** [comment]
Greetings,
Thank you for your feedback. We are always improving our project and have already fixed this bug in the latest versions of ThingsBoard.

Best regards,
ThingsBoard Team.
