### ISSUE TITLE
SSL configuration strategy without ngix/apache proxy

### ISSUE THREAD

**Issue by paolofrs** [thingsboard/thingsboard#2647]
Hello,

I have Debian Buster server running **ThingsBoard CE in a docker container**. I really like the portability of this implementation and I really love tb. The server is a VPS with few resources and is dedicated to TB evaluation purposes only. I do not want to install other webservices but I need TLS/SSL encryption. **I would like to use certbot/let's encrypt but I need to configure TB** (I assume so, I am quite new to certbot). 

**What is the best strategy to configure TB to work with TLS/SSL in a container?** I'd better to add specific ENV (some are listed [here)](https://thingsboard.io/docs/user-guide/install/config/) in the compose/docker file or directly modify the *.yml and *.conf files and mount them as volumes? Is this last option possible? 

Can you help on this specific configuration (tb over https with certbot)? What ENV shoudl I set?

**Comment by jigar-j-patel** [comment]
https://github.com/michalfapso/thingsboard_docker_https

you can follow this link.
