### ISSUE TITLE
Confused about using Rest Api Call or integration

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2650]
Background: Let's say I want to send the thingsboard device's data (telemetry data) to local (downlink)

Q:
1. I am not sure how to use Thingsboard PE Integration (HTTP) to send data (downlink), I don’t know how to trigger / setup integration (HTTP) (downlink) and data converter (to json downlink)

For example, to obtain telemetry data from an Thingsboard (rule chains)-> data converter (not sure how to trigger / setup from the rule chains)-> integration (not sure how to trigger / setup from the rule chains)-> downlink-> local

2. I don't know where to put my downlink_url if I use Thingsboard PE Integration.

3. What is the difference between REST API call (HTTP) and integration (HTTP)? [downlink only]

thank

**Comment by Karabiy** [comment]
1. you can put the downlink integration rule node. refer to this: https://thingsboard.io/docs/user-guide/integrations/#downlink-data-converter
2. there is no option for the downlink to have the separate URL, it uses the one from which the data were sent 
3. for the rest API call you can have all the separate URLs and confs for he metadata 
so, for your use case, it is better to use the "REST API" external rule node
