### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2651]
Q:
1. How to hide entity group button (red one)?
![take](https://user-images.githubusercontent.com/63713926/79945162-cea7ee80-849f-11ea-88ea-4133056a7d45.png)

2. Assuming that the staff should not have the right to view the information of the administrator in the user group. How to hide all and the administrator (blue one)? (I can’t find a place to set permissions for those boxes)
<img width="1227" alt="take2" src="https://user-images.githubusercontent.com/63713926/79945944-87226200-84a1-11ea-9d47-8281fad67527.png">

thank

**Comment by ban2derlog** [comment]
Hi, do you try this functions on latest ThignsBoard version?
