### ISSUE TITLE
Change Datasource Entity's Parameters in Timeseries Chart with another Widget

### ISSUE THREAD

**Issue by harshchauhan11** [thingsboard/thingsboard#2656]
Hello All,
Good Day..

I want to change the entity's selected parameters in the Datasource, automatically from another Widget.
Example:
**Widget A** (Timeseries Flot Chart)
**Widget B** (Some static HTML with some Dropdown Box, which can update Dashboard State on selecting any item)

Here we can select datasource from Entity alias in the UI and then selecting Timeseries param from that.
![image](https://user-images.githubusercontent.com/6233006/79990418-a84d7780-84ce-11ea-9041-2cfd67a28ed4.png)

**I want to update the Timeseries parameter (here "test") by selecting dropbox item from another Widget.**

How can this be possible? Any help would be great for me.
Thank you.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
