### ISSUE TITLE
MAP POLYGONS

### ISSUE THREAD

**Issue by cristianfagiani** [thingsboard/thingsboard#2659]
Very interesting feaure...but is there a way to have labels over polygons ?
My goal is to put the area name.
Otherwise another solution could be to activate related area on map when clicking a row on entity list...but have completely no idea if this can be achieved.

Thanks

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
