### ISSUE TITLE
dashboard carousel

### ISSUE THREAD

**Issue by luigiGlorioso** [thingsboard/thingsboard#2666]
Hello Authors,
it will be good to have a sort of tool that enable to view multiple dashbards based on time . let me explain: I have two dashboards and I want to see the first one for 10 seconds and the second one for 5 seconds, indefinitely.
Morover It will be nice to have messages that scroll in the bottom line from left to right.
suppose I have three messages I want to see them as:
first message  -   second message - third message 
These carousels have to be linked also as default dashboard for tb users.

**Comment by Karabiy** [comment]
for those reasons, you can use an iframe using the html widget, or you can create your custom one.
regarding the second question, you can have those being done with the custom widget and regarding the default dashboard you can have those being configured for the users of yours 
you can refer to this link regarding the on how to proceed with the widget development: https://thingsboard.io/docs/user-guide/contribution/widgets-development/
