### ISSUE TITLE
Digital Gauges Not Refreshing with Telemetry Data

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2669]
refer to this [post](https://github.com/thingsboard/thingsboard/issues/856)
The problem seems to be resolved.
But when I use "PostMan" to send and test http integration and widget library,
Sometimes, when the animation function is enabled, the widget does not update the data.
How to solve?

**Comment by itnas** [comment]
sorry for my english
The problem same happens with me, TB 2.4.3
![image](https://user-images.githubusercontent.com/2129863/80466904-5346b100-8967-11ea-89f8-ee57221c55a3.png)

**Comment by goboras** [comment]
tb-postgress docker ver. 2.4.3 problems with digital gauges when animation is enabled

**Comment by itnas** [comment]
ThingsBoard 2.5 problem has been resolved.

**Comment by ecmap** [comment]
> ThingsBoard 2.5 my problem has been resolved.

Yes it looks great

**Comment by Rworld-Ravi** [comment]
> > ThingsBoard 2.5 my problem has been resolved.
> 
> Yes it looks great

Not in my case- 
OS - Ubuntu bionic
TB version: 2.5
The value still freezes, the only workaround available is to disable the animation.
