### ISSUE TITLE
Scripting export / import of dashboards, devices, rules chains

### ISSUE THREAD

**Issue by dajtxx** [thingsboard/thingsboard#2672]
Is there a way to script the export or import of a set of dashboards, rules chains, etc to make it simpler to move a system from one server to another?

Eg we're developing a system on a staging server and want to move the whole lot to a production server, or we want to save the definitions in a source code control system with exporting everything one piece at a time and moving around all the different screens,

**Comment by ashvayka** [comment]
Hi @dajtxx !

Sure, please see how to use our rest client: https://thingsboard.io/docs/reference/rest-client/#professional-edition-rest-client
It can help you to automate all export/import.

Regards!

**Comment by dajtxx** [comment]
OK, thanks.
