### ISSUE TITLE
How do I debug thingsboard through vscode？

### ISSUE THREAD

**Issue by maddff** [thingsboard/thingsboard#2674]
I used to use IDEA to debug thingsboard. When I tried to debug it through Visual Studio Code, got the following error:
```
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.
Build file '/Users/totoro/Documents/workspace/thingsboard/application/build.gradle' line: 30
A problem occurred evaluating root project 'application'.
Failed to apply plugin [class 'com.netflix.gradle.plugins.packaging.SystemPackagingBasePlugin']
Could not create an instance of type com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.
Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.BaseDirFileResolver, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator)
```

![image](https://user-images.githubusercontent.com/19566405/80405418-2b1e6a00-88f5-11ea-990f-2dcb65302828.png)
![image](https://user-images.githubusercontent.com/19566405/80405676-805a7b80-88f5-11ea-9f1f-c8dda332a6fc.png)

I have installed these plugins and related env: Java Extension Pack & Spring Boot Extension Pack & Gradle Extension Pack.

Thanks for help😊

**Comment by maddff** [comment]
solved

**Comment by faywong** [comment]
@maddff 

Would you tell me how to debug thingsboard through IDEA with mvn spring-boot:run?
I have not figured out which configuration files is used this way? Is there a readme/doc coverred this topic?
