### ISSUE TITLE
Need help, does the Entities table widget support displaying icons on the value column?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2676]
In addition to displaying values, I also want to display icons on the entities table. . .

I tried to use 'img / span / or i tag' on the 'data post-processing function' to display the icon, but it shows an error.

I don't know how to display icons (material design icons) or image, can someone teach me how to do it ... (or modify the original one to support this feature)

**Comment by ecmap** [comment]
solved

**Comment by engr-faizan** [comment]
@ecmap How did you do that?
