### ISSUE TITLE
New customer with a specific hierarchy (template)

### ISSUE THREAD

**Issue by blackprincess88** [thingsboard/thingsboard#2679]
Hi there!

I would like to know if  there is a way to replicate a customer structure in terms of groups, roles and dashboards automatically for each new customer for the same tenant? Is there some example of API or rule chain to perform this operation?

This is the use case: I am the tenant and I created a template structure for my customers by using customer hierarchy (as suggested in the documentation) with particular user groups, template groups for the entities and so on...I would like to have this structure for each new customer in order to be free from charge for each new customer..

Thank you for help!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
