### ISSUE TITLE
Rule chain RPC call fails when metadata.oneway is true and timeout is 0

### ISSUE THREAD

**Issue by dajtxx** [thingsboard/thingsboard#2682]
If an RPC call is one way then no reply is expected, so I think a timeout value of 0 should be ok and not cause a failure.

Even better would be a checkbox to signify a one way call which disables the timeout field when checked.

The help text should at least mention how to do this.

I had to read the source to figure out how to make a one way call in a rules chain :(

**Comment by djfil** [comment]
And how is it? I am very lost on this, and can't find any documentation on the subject... some examples, but I keep getting "NO_ACTIVE_CONNECTION"
There are a bunch of people already asking about this in a form or another...

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
