### ISSUE TITLE
Server side rpc call first request is ok,but the second not work

### ISSUE THREAD

**Issue by ioprotocol** [thingsboard/thingsboard#269]
I user a mqtt client connect to thingsboard node and subscribe the topic of "v1/devices/me/rpc/request/+",
then I send a rpc request to "http://serverAddress:8080/api/plugins/rpc/twoway/device1Id", the client will 
receive the request and response also successfully,  but when I resend a rpc call to "http://serverAddress:8080/api/plugins/rpc/twoway/device1Id", the Mqtt Client can't receive request any more,  is this a issue? please give me a help!  Thank you very much.

**Comment by ashvayka** [comment]
We will review this but I don't suspect the bug here since we are using the same API all the time.

**Comment by dmytro-landiak** [comment]
I've just checked your question. Everything is working fine.
