### ISSUE TITLE
Dash board state changed

### ISSUE THREAD

**Issue by cristianfagiani** [thingsboard/thingsboard#2690]
I would like to do 2 simples things on my dashboard:
I have an entity list and when i click on a row of the list i show historic data to another widget on the same dashboard.
Problem is that every row can have different value types (level in meters or pressure in bar..) and wold like to:
1 - Set correct um (mt or bar) next to value on historic list widget (note that um is a server attribute of the selected entity)

2- Just put ${entityName} of selected entity on historic widget title

I cannot find any manual wich explains basic things like keywords or variable names (like dashboard state parameters names...)

Could someone please help ?

Thanks

![image](https://user-images.githubusercontent.com/3875034/80515359-20f67d00-8982-11ea-9efc-2c3ba6cc88a5.png)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
