### ISSUE TITLE
Help!, how to navigate to other dashboard on custom action?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2693]
Background: Know how to write scripts / functions to navigate to new dashboard state on custom action

Q: I want to navigate to other dashboard on custom action, but I don’t know how to get $state or other variable work in scripts / functions, this is my [reference](https://github.com/thingsboard/thingsboard/blob/2a1c55f02217e72eecd955c16c8dbcab7ac74ede/ui/src/app/components/widget/widget.controller.js) ...
<img width="866" alt="test" src="https://user-images.githubusercontent.com/63713926/80590062-dcd0ae80-8a4d-11ea-9a46-7c59847a81bd.png">

Can someone help me?

thank

**Comment by JuliusHarald** [comment]
have a look at the issue #1480 . Maybe that will help you

**Comment by ecmap** [comment]
@JuliusHarald 

I still don’t know how to navigate to other dashboards in custom actions,
Can you give an example to demonstrate how to do this? Thank you~

**Comment by JuliusHarald** [comment]
Basiclly you have to write a url, that looks something like this:

let url = `/dashboards/` + [the UUID of the Dashboard you want to navigate to]

you can also add a state like:
let state = 'default';
let url = `/dashboards/` + [the UUID of the Dashboard you want to navigate to] + '?state=${state}`

after this you can open the URL with:

window.location.href = url;

Getting the UUID of the Dashboard you want to navigate to or the state can also be difficult, you need also help with that?

**Comment by FrancescoMenga** [comment]
@sabreestorm Your method work really good, but i suggest to use the angular integrated navigator, that can be accessed by using:
widgetContext.router.navigateByUrl(url), instead of window.open().
This method seems to load pages faster.

**Comment by leitinhakk** [comment]
> Basiclly you have to write a url, that looks something like this:
> 
> let url = `/dashboards/` + [the UUID of the Dashboard you want to navigate to]
> 
> you can also add a state like: let state = 'default'; let url = `/dashboards/` + [the UUID of the Dashboard you want to navigate to] + '?state=${state}`
> 
> after this you can open the URL with:
> 
> window.location.href = url;
> 
> Getting the UUID of the Dashboard you want to navigate to or the state can also be difficult, you need also help with that?

hi, I know that has been a while since this comment has been posted, but maybe you can help me getting the uuid?
