### ISSUE TITLE
How to copy widgets?

### ISSUE THREAD

**Issue by Corei52500k** [thingsboard/thingsboard#27]
Hello Developers,

in the changelog i read that you added the ability to copy and paste widgets. How can i do that? In which menu is the option available?

Thanks.

**Comment by ashvayka** [comment]
@Corei52500k, I have recorded short video about how to do this (~1.7Mb). Basically this is available in the dashboard editing mode.
[copy-paste.mp4.zip](https://github.com/thingsboard/thingsboard/files/680893/copy-paste.mp4.zip)

**Comment by Corei52500k** [comment]
@ashvayka Thx! I have never tried to use right mouse click, i was always searching for an Icon.
