### ISSUE TITLE
Documentation unclear on horizontal scaling/clustering configuration on Docker Swarm with PostgreSQL 

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#270]
I have read the documentation on clustering but can't find any example / description of using another database then Cassandra.

**What do I want / need ?**
A 3-6 node cluster with Thingsboard running on a Docker Swarm. 

**The preferred solution:**

- A container stack with TB Gateway, TB & PostgreSQL
- Scaling is done using the docker swarm scale command. Ie, same configuration for each TB node!
- The data is stored on a persisted volume (shared storage), where TB assigns a unique folder to each database, so that no conflict is created when multiple databases are created on the same shared storage.

**However, I'm not sure if this is possible, hence some questions...**

- Can I use the scaling option in Docker Swarm to scale TB, or should I do that manually, ie declaring 3-6 separate TB instances with each a separate volume to store the database?
- Can I do this with PostgreSQL?, just as with Cassandra? 
- I need the MQTT Gateway. Do I have to deploy a gateway per TB/PostgreSQL stack?
- What happens if in a 3-cluster setup 1 node fails? I assume the two other nodes will keep on serving data and the dashboards. What if the 3rd node comes back up?
- Is Cassandra used for clustering, or does TB this itself, hence the database clustering possibilities are not used, hence about any database can be used (big plus!)

Thanx

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by MarsWarrior** [comment]
I forgot to comment on this, but here it is...
I can see my question was not very clear ;-)

According to : https://thingsboard.io/docs/user-guide/install/cluster-setup/ you can cluster TB.

![image](https://user-images.githubusercontent.com/1220775/32702448-c1ec1260-c7e7-11e7-8a79-b7efcf314702.png)


The default backend is Cassandra. I want to use PostgreSQL.
Can I simply replace Cassandra by PostgreSQL in this setup, or does it work differently?

**Comment by vparomskiy** [comment]
Since ThingsBoard 2.2 microservice architecture was released. Please find more details here: https://thingsboard.io/docs/reference/msa/
