### ISSUE TITLE
Silo monitoring events data source and dashboard widget?

### ISSUE THREAD

**Issue by dajtxx** [thingsboard/thingsboard#2710]
I would like to include something similar on my dashboard. It's not using alarms because they don't have the INFO status.

How was this widget done and where does it's data come from?

I can't find a widget like that in the community edition.

**Comment by PovitruliaV** [comment]
Hi @dajtxx ,
![image](https://user-images.githubusercontent.com/98046079/173865279-771cdd44-47f2-4608-bdd5-e779b9ef5df0.png)
If I understood you correctly you are talking about this widget. In this case, we are using Markdown/HTML Card widget.
In this widget, you can write your own HTML code and thus create a kind of custom widget. 
Correct me if I'm wrong.
