### ISSUE TITLE
Don't close the test function 'dialogs' with the escape key, or don't lose the code changes without asking

### ISSUE THREAD

**Issue by dajtxx** [thingsboard/thingsboard#2711]
The 'test function' area is the most convenient place to work on code that transforms input messages to something else.

But that window closes without asking when you press escape, and doesn't keep the changes to the code. So you lose all your changes. This has just happened to me twice while trying to dismiss a code completion popup.

**Comment by ban2derlog** [comment]
Hi, this is already fixed on latest ThingsBoard version.
