### ISSUE TITLE
MQTT topic subscribtion

### ISSUE THREAD

**Issue by e-infotech** [thingsboard/thingsboard#2713]
Hi,
I'm using thingsboard for my project and I encountered a problem related to the topic subscription! 
I want each stream of data to go to different devices based on the device names but it seems the devices cannot subscribe to their interesting topic and because thingsboard is using an old version of node-red, this task can not be done using rule chain! Do you have any solution?

**Comment by PovitruliaV** [comment]
Hi @e-infotech ,
MQTT API uses the thingsboard built-in MQTT broker that can only work with topics like `v1/devices/me/attributes` `v1/devices/me/telemetry`, etc. You can read more on the MQTT API capabilities in the [MQTT API](https://thingsboard.io/docs/pe/reference/mqtt-api/) article.
Regards
