### ISSUE TITLE
Location of mqttserver.jks when built from sources

### ISSUE THREAD

**Issue by bcnrao** [thingsboard/thingsboard#2715]
Hello,

I have built thingsboard from sources in ubuntu 16.04 and running it using the resulting jar file.
I am trying to test the MQTT with SSL interface and I am not sure where exactly to place the mqttserver.jks file. I tried to create a folder in /usr/share/thingsboard/conf and placed the keystore file. 
I get the mqttserver.jks file not found exception.
Then I tried to place it under thingsboard/application/src/main/resources/ and rebuilt thingsboard.
Now I get java.lang.IllegalArgumentException: URI is not hierarchical.

Please help in fixing this issue.

Thanks in advance

**Comment by chhein** [comment]
Maybe the same error as in #4216 ?
Ive got also problems with that.
@bcnrao

**Comment by Ultrazombie** [comment]
solved by chfxr in other issue
