### ISSUE TITLE
Problem with sending data via MQTT

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#2727]
Hello everyone ! I have a problem with sending data via MQTT. If I send data to **demo.thingsboard.io** then they come and I see them, but if I send to my aws ec2 server then the data does not come.
**What could be the problem?because everything comes to demo.thingsbord.io**
thingsboard config:
![Снимок](https://user-images.githubusercontent.com/32870557/81045226-779e1280-8ebe-11ea-81af-8d26263d73bc.JPG)
ports:
![Снимок2](https://user-images.githubusercontent.com/32870557/81045296-98666800-8ebe-11ea-9103-90ad400aedd5.JPG)

**Comment by vvlladd28** [comment]
Hi,
You may have a misconfigured firewall, and it is blocking the MQTT. The default port for MQTT 1883

**Comment by destr1ke** [comment]
> Hi,
> You may have a misconfigured firewall, and it is blocking the MQTT. The default port for MQTT 1883

Thanks for your answer , yes i have used the default port but the problem was the same

**Comment by dajtxx** [comment]
Could the firewall may be blocking the default port?

**Comment by destr1ke** [comment]
> You may have a misconfigured firewall

Tell me please where can I find it?
