### ISSUE TITLE
Create attribute templates based on Device Type

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#273]
I will be deploying dozens of identical sensors into the field.  It would be great if there were a way, perhaps using Device Type, to set up a common set of attributes for all devices of that type.  That would save a ton of manual configuration.  

For example, I want all of my PM1 sensors to have a latitude and longitude attribute that will be assigned manually during configuration.  I don't want to have to manually add the container for those attributes to every sensor.  Rather, I'd like to define them once and have every PM1 sensor pick them up automatically.

It seems that the existing Device Type could be leveraged for this purpose.  Common attributes could be configured at the Device Type level, with their definitions (and possibly values) flowing down to the Device level.

Is something like this currently possible?  If the idea is good, and adding it is straightforward, I could do the work myself and submit a pull request.

Thoughts?

One alternative workflow that I am considering is trying to do all the configuration work via the API using a custom script.  This has some advantages, but it would seem to better enforce integrity to have the Device Type provide the common set of attributes.

**Comment by t0mmyz7** [comment]
Yes very important feature, define a "thing" definition/template and when adding new one, if using existing template, it will create all the fields. Then user manually can fill them or device can report them automatically.

**Comment by ashvayka** [comment]
I agree that this is valid feature. It may be a candidate for 1.4 release. Will update this issue if we will have a design ready.

**Comment by affoltep** [comment]
Any news about this feature? It would be really helpful.

**Comment by vparomskiy** [comment]
1. You can implement it using Rule Engine. There is a **ENTITY_CREATED** event that is passed to the Rule Engine when device created:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/

You can define RuleChain that will detect those events and set the required attribute/value pairs for each device type.

2. API - sure, you can make it via REST API:
https://cloud.thingsboard.io/swagger-ui.html#!/telemetry-controller/saveDeviceAttributesUsingPOST

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.

**Comment by alexsmartens** [comment]
Hi @eykamp,
Have you figured out how to fill in default attributes with templates?

I am trying to figure out how to use attributes for configuring what kind of telemetry data I want to receive from various device types (#1737). It would be great if you could help with an advice

**Comment by eykamp** [comment]
Yes, sort of. I now do all my configuration work using Python scripts, so replication and modification is easy.

This is not an ideal solution, but it works for me.

I am developing a set of tools to make this easier: https://github.com/eykamp/thingsboard_api_tools It is still very much a work in progress, and is very incomplete, but it covers the ground I need it to, and I find using this lib makes things a lot simpler. Feel free to take code, ideas, or whatever if you find them useful. I have developed another API on top of this that provides more project-level abstraction; this really just helps with the mechanics of interacting with the TB API. Eventually I will provide a set of objects (Customer, Device, Dashboard, etc.) to abstract away some the details.

**Comment by alexsmartens** [comment]
Thank you @eykamp for your comprehensive response. I've figured how to do it.
Now I'm looking how to subscribe to the telemetry data with the keys defined in my attribute (#1743). Have you had a chance to do something like that?

**Comment by eykamp** [comment]
I haven't, but depending on your situation, you could do this via the REST API. That would work less well if you needed things to be dynamic. I've done some dashboard manipulation with scripts (specifically using a dash as a template for new devices, or to update a number of dashboards automatically), so I know it's possible and not well supported.

**Comment by amardhore** [comment]
> I've figured how to do it.
@alexsmartens i am also struggling with similar issue on how to configure attribute automatically to all the similar devices. I tried to follow some references but i am not still clear on how to do. How did you do it? 
Thanks

**Comment by alexsmartens** [comment]
@amardhore, sorry I have not been working with thingsboard for a while now so cannot point you to the direct solution of your problem. Back in the day, I ended up figuring out how thingsboard works on Angular level and modifying component source code (you can do pretty much anything there). 

Look up #1737, you might find this helpful
