### ISSUE TITLE
CONSTRAINT name is wrong or not?

### ISSUE THREAD

**Issue by amy108** [thingsboard/thingsboard#2734]
/dao/src/main/resources/sql/schema-timescale.sql
the CONSTRAINT name **ts_kv_pkey** in the sql file above is wrong or not?

**Comment by ShvaykaD** [comment]
Hi, @amy108 the constraint name for the ts_kv table is correct.

**Comment by ShvaykaD** [comment]
Initially, the constraint was mistakenly named ts_kv_pkey when the table called tenant_ts_kv. However, during the upgrade to the future release 2.5 the table will be renamed to ts_kv and the primary key constraint will be called ts_kv_pkey.
