### ISSUE TITLE
Unable to start thingsboard service

### ISSUE THREAD

**Issue by z4nD4R** [thingsboard/thingsboard#274]
Hello everyone,

I found out that tb service stopped to work. I have issues `service thingsboard restart` but unfortunatelly I can not bring the `tb` service back alive.

I'm attaching `/var/log/thingsboard/thingsboard.log` https://pastebin.com/qXna1uAT .

Any advice will be helpfull.

Thank you.

Y

**Comment by volodymyr-babak** [comment]
hi, 

just to confirm:
1. TB was running fine without any issues
2. At some point TB stopped
3. After restart without any modifications to the configuration it starts throwing this errors on mapping

are these statements correct?

**Comment by z4nD4R** [comment]
@volodymyr-babak,

more or less like you specified. The exact way:

- TB was running fine without any issues
- Make some dashboard modification (export and import dashoard)
- Works for some time
- At some point TB stopped
- After restart without any modifications to the configuration it starts throwing this errors on mapping

This is exact path :) 

Y

**Comment by z4nD4R** [comment]
@volodymyr-babak,

if you need some more logs or debug informations, please don't hesitate to ask.

Y

**Comment by volodymyr-babak** [comment]
hi, from the log file it doesn't clear where is the issue.
Please change log level to DEBUG and restart application.
And then attach log file + config file.

**Comment by z4nD4R** [comment]
@volodymyr-babak, do you have a hint for me how to enable the DEBUG level?

**Comment by volodymyr-babak** [comment]
/usr/share/thingsboard/conf/logback.xml is configuration file for log level and other options

**Comment by z4nD4R** [comment]
@volodymyr-babak,

thank you for pointing me to `/usr/share/thingsboard/conf/logback.xml` :)
I'm attaching the log file (quite huge) directly here.

Y
[thingsboard.txt](https://github.com/thingsboard/thingsboard/files/1285795/thingsboard.txt)

**Comment by volodymyr-babak** [comment]
you have issues with memory on your device
2017-09-07 16:53:52,854 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Initialization of bean failed; nested exception is java.lang.OutOfMemoryError: Java heap space

**Comment by MarsWarrior** [comment]
We see a lower limit of 4-6GB ram using Ubuntu for TB to run.
So our VM's have 8-16 GB and run without problems.

**Comment by volodymyr-babak** [comment]
If you are using 1.3 version and it's not painfully to re-create data and devices you can consider SQL database instead of cassandra. This will work fine on 1GB RAM devices

**Comment by z4nD4R** [comment]
@volodymyr-babak 
Yes I'm using 1.3 version of TB, but I'm not using cassandra DB. I'm using SQL :) 
Moreover this setup worked like a charm before ;) 
I believe the glitch will be somewhere else :/ 

Y

**Comment by volodymyr-babak** [comment]
I'm not saying that cassandra is definitely the issue.
ThingsBoard is stopping because luck of RAM memory. 
But root cause is not  clear and must be investigated separately - could be database, java configuration, memory usage by some other process, etc.

**Comment by z4nD4R** [comment]
@volodymyr-babak , It is interesting as it was working without any issues a quiete long time and than suddenly it stops. I have tried to reboot RPI3 and start TB, but no luck here as well.

Is there any chance to bring it alive (I wouldn't like to lost all my configuration like dashboard, devices etc).

Y

**Comment by volodymyr-babak** [comment]
have you tried to increases RAM memory for the thingsboard java process ?

**Comment by z4nD4R** [comment]
@volodymyr-babak do you mean to increas values scpecified in `/etc/thingsboard/conf/thingsboard.conf` ? :

```
# Update ThingsBoard memory usage and restrict it to 150MB in /etc/thingsboard/conf/thingsboard.conf
export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpi -Xms256M -Xmx256M"
```

Y

**Comment by volodymyr-babak** [comment]
yes

**Comment by z4nD4R** [comment]
@volodymyr-babak I'll try it as soon as return home. Will share result here.
Thank you so far.

Y

**Comment by z4nD4R** [comment]
@volodymyr-babak:

I have edited the given line as you suggested and my TB instance is alive again. Thank you many times.

PS: is there anyway to donate this project or support in other way?

Y

**Comment by ashvayka** [comment]
@z4nD4R We should make some T-Shirts :rofl: . You can support us by contributing the issues/fixes/features. There are some ideas in the neighbor github issues.

**Comment by z4nD4R** [comment]
@ashvayka the T-Shirts would be great, let me know I'd like to participate on design of those T-Shirts :D 
Speaking about suport by issues omw to upload another one.

Y

**Comment by saurabhjhamb** [comment]
I have recently updated from 1.3.0 to 1.3.1 following instructions from https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-131 but unable to get Thingsboard up and running.

Have followed most of the above but my issue doesn't seem to be with memory (running on a 15GB RAM server), but see the log has 1st ERROR as
"**ERROR o.s.boot.SpringApplication - Error handling failed**"

attaching detailed logs...[thingsboard.log](https://github.com/thingsboard/thingsboard/files/1534737/thingsboard.log)

look forward to your help in getting it back up. Have loads of data in cassandra can't afford to lose...

**Comment by mp-loki** [comment]
Hi @saurabhjhamb ! Looks like you are using thingsboard.yml file from 1.3.0 with the 1.3.1 version. In 1.3.1 some properties have been added to the config file which are missing in yours. Please, use the thingsboard.yml file from 1.3.1 version and update it with your values.

**Comment by saurabhjhamb** [comment]
Thanks, rpm saved new file as .yml.rpmnew, found diff on "create_components_on_init"

now working!

**Comment by khaiz91** [comment]
May I know how do you guys solve this issue?
I just posted a new issue at #861 https://github.com/thingsboard/thingsboard/issues/861
My error is java.lang.OutOfMemoryError: GC overhead limit exceeded
Please assist, thank you.
