### ISSUE TITLE
Gateway is out of sync

### ISSUE THREAD

**Issue by xjdg150135** [thingsboard/thingsboard#2742]
I have run TB and gateway on the same computer.Now,I want connect real device  by modBus。The 502 port of the device and the computer are connected.But gateway is out of sync.MQTT is OK.[[![Yek8PO.png](https://s1.ax1x.com/2020/05/07/Yek8PO.png)](https://imgchr.com/i/Yek8PO)](url)

**Comment by ashvayka** [comment]
@zbeacon  please help to investigate this

**Comment by zbeacon** [comment]
Hi @zbeacon 

Thank you for your interest in ThingsBoard IoT gateway.
The feature "Sync" was implemented for the old Java-based gateway. The Python gateway doesn't support this feature. You can check the attribute "Active" in "Server attributes" of the gateway device. To get this information - open the gateway device, got to the tab ATTRIBUTES and select the Server attributes from the drop-down list.
