### ISSUE TITLE
Document API call for setting attributes

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#275]
Setting attributes via the API is not documented.  If these are intended to be part of the public API, they should be.

Example: POST http://<<server_address>>/api/plugins/telemetry/DEVICE/<<device_id>>/SERVER_SCOPE

I can add the documentation if it should be public.

**Comment by ashvayka** [comment]
@eykamp Please contribute the documentation to https://github.com/thingsboard/thingsboard.github.io
Feel free to ping us if you will have issues with docs editing/viewing.
