### ISSUE TITLE
Date.toLocaleString() not working in Script node under Transformation node

### ISSUE THREAD

**Issue by adksujan** [thingsboard/thingsboard#2750]
I want to convert the timestamp of my message to local time with different timezone than UTC, e.g. in Central European Timezone  inside the Script node in rule chain. How can we achieve that. Unfortunately, all of the javascript Date function, for e.g. `toLocaleString('de-DE')` gives the same UTC time zone not the local time zone.

```
date = new Date(parseInt(metadata.ts));
metadata.date = date.toLocaleString('de-De');
return {msg: msg, metadata: metadata, msgType: msgType};
```
Expected  output `metadata.date` to be `5/7/2020, 9:57:00 PM` but got  `5/7/2020, 7:57:00 PM` instead.

**Comment by ashvayka** [comment]
this is not related to thingsboard and just a javascript question. @ChantsovaEkaterina  please provide comments

**Comment by ChantsovaEkaterina** [comment]
Hello, you can use ES6 features in the rule nodes only if your TB instance is running in microservice mode. If no, in the better case your code will be working as if some code fragment doesn't exist, in the worse case you receive an error.
The only way I see to do the needed transformation in your case is to manually compose the date in a required format.
For sample,
`var date = new Date(parseInt(metadata.ts));
var year = date.getUTCFullYear();
var month = date.getUTCMonth() + 1;
var dayOfMonth = date.getUTCDate();

month = (month < 10) ? ('0' + month) : month;
dayOfMonth = (dayOfMonth < 10) ? ('0' + dayOfMonth) : dayOfMonth;

metadata.date = year+"-"+month+"-"+dayOfMonth+"T00:00:00+02:00";`
