### ISSUE TITLE
Send Twilio SMS using "rest api call" node

### ISSUE THREAD

**Issue by sw-dev-code** [thingsboard/thingsboard#2755]
I need to send SMS in my Rule Chain. I'm trying to set `rest API call` to call Twilio API for SMS sending but without success.

I know there is a Twilio plugin in PE, but I would like to use `rest API call`.

**Comment by JasonFarque** [comment]
> I need to send SMS in my Rule Chain. I'm trying to set `rest API call` to call Twilio API for SMS sending but without success.
> 
> I know there is a Twilio plugin in PE, but I would like to use `rest API call`.

I also spent several hours trying to get this working in 2.4.3PE and could not. I never could figure out a way not to have quotation marks around my messages through Twilio.

**Comment by bcnrao** [comment]
@JasonFarque Can you please explain how were you passing the Body,To and From information in the message payload. I tried sending the information as a json payload 
example
{"Body"='Hi there!',
 "From"='+15017122661',
 "To" ='+15558675310'
} and I get a bad request with error "Message body is required".
Any help would be appreciated.
Thanks

**Comment by JasonFarque** [comment]
@bcnrao I was never able to get TB2.4.3PE to send an SMS message through Twilio using the REST output node - and I agree that we should be able to. I don't know why it doesn't work but it sounds like we had the same problem. The *only* way I can send an SMS via Twilio is to use the Twilio node and I was never able to find a way to prevent it from sending the quotation marks around a message. It's very annoying and if you find a solution please let me know here.

**Comment by Rworld-Ravi** [comment]
hh

**Comment by Rworld-Ravi** [comment]
> @bcnrao I was never able to get TB2.4.3PE to send an SMS message through Twilio using the REST output node - and I agree that we should be able to. I don't know why it doesn't work but it sounds like we had the same problem. The _only_ way I can send an SMS via Twilio is to use the Twilio node and I was never able to find a way to prevent it from sending the quotation marks around a message. It's very annoying and if you find a solution please let me know here.

I have run a minimal flask server as a service side-by-side a TB2.5 CE, and using that rest API Node to call the flask server APIs to get the work done easily (of course, python Twilio module to send messages to Whatsapp, even more fun with a Twilio chatbot setup).
Its really use full for some complex tasks that are tedious within Thingsboard's limited or complex scripting options.
References : [https://www.twilio.com/docs/whatsapp/quickstart/python](url)
[https://www.twilio.com/blog/build-a-whatsapp-chatbot-with-python-flask-and-twilio](url)

**Comment by Milan991** [comment]
@JasonFarque Can you tell me what node do you have before Twilio node for creating the SMS text?

**Comment by JasonFarque** [comment]
> @JasonFarque Can you tell me what node do you have before Twilio node for creating the SMS text?

I'm using a Script node to assemble the msg text prior to passing it off the the Twilio node.

**Comment by Milan991** [comment]
@JasonFarque Can you send me an example of Script node json you are using?

**Comment by mrs-aleksandra** [comment]
@JasonFarque or anyone, how does this assembling the message in Script node looks like? Any example?

**Comment by ahmed-1a** [comment]
I also spent some time, and finally, I got to the following:

Script code: 

```
var sms = "MessagingServiceSid=" + encodeURIComponent('xxxxx') + "&From=" + encodeURIComponent("xxxx") + "&To=" + encodeURIComponent("+xxxx") + "&Body=" + encodeURIComponent('hello')  ;
return  {msg:sms} ;
```

![image](https://user-images.githubusercontent.com/41074884/104831533-e3c07b00-5881-11eb-8004-91f449e94109.png)

API node call headers: 
Content-type application/x-www-form-urlencoded
Authorization Basic [Account SID]:[AuthToken]

[Account SID]:[AuthToken] should be encoded to Base64 first, Use [https://www.base64encode.org/](https://www.base64encode.org/) and then paste it into the header

![image](https://user-images.githubusercontent.com/41074884/104831520-b70c6380-5881-11eb-9089-4c89bac6c584.png)


This should work, one problem I couldn't solve so far is that there is a quotation mark at the end of the SMS message, this is because the message payload from the script is passed with those quotation marks.

I used this method with Alpha Sender ID which is not possible with the SMS node.

**Comment by ahmed-1a** [comment]
@sw-dev-code @mrs-aleksandra 

I managed to solve the quotation mark issue by passing additional params at the beginning and the end.

![image](https://user-images.githubusercontent.com/41074884/104831680-0acb7c80-5883-11eb-8436-1b43af196cdb.png)

**Comment by ahmed-1a** [comment]
Maybe Alpha Sender ID can be enabled in addition to mobile numbers in send SMS node @ashvayka @ikulikov 

![image](https://user-images.githubusercontent.com/41074884/104845491-b13c6f80-58cd-11eb-8dde-42d66230a380.png)

**Comment by konradSC** [comment]
I was able to get voice calling working with the REST API node using this format in my script node. 

`metadata.AuthString = btoa("ACxxxxxxx");

var strMsg = "";
strMsg += "start=start&";
strMsg += "Twiml=<Response><Say>Hey. If you hear this please call your father. </Say></Response>&"
strMsg += "To=+18645551234&";
strMsg += "From=+18645550000&";
strMsg += "end=end";

return {msg: strMsg, metadata: metadata, msgType: msgType};`

**Comment by Civilduino** [comment]
If using the Twilio Node in the Professional Edition, the return ´msg´ from the Script Node can be just a String variable with the information you want to send.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
