### ISSUE TITLE
 How to use the data returned by REST API

### ISSUE THREAD

**Issue by leehosg** [thingsboard/thingsboard#2756]
hi
The situation is to take a token value and try to send that token value to the header every time another rest api is called.

Is there a way to send the data received by rest api to the header of another rest api?

![image](https://user-images.githubusercontent.com/41560134/81540724-03c3a480-93ad-11ea-8c27-15e9f8819118.png)

I wonder if there's a way to use it as soon as you get it, or where to store it and load it whenever you need it.

I'm not sure if the meaning will be conveyed when I'm using the translator, but thank you.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
