### ISSUE TITLE
When updating attributes, return a list of attributes in the body

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#276]
When POSTing to http://<<server_address>>/api/plugins/telemetry/DEVICE/<<device_id>>/SERVER_SCOPE, the returned body is empty.  It might be better to return a list of attributes, which would make it more consistent with other API calls.  Since this 1) is undocumented (see #275); and 2) currently returns nothing, adding a return value should not break any existing applications.

**Comment by ashvayka** [comment]
@eykamp Do you have Java experience? We welcome you to contribute this even if you don't have one. We will review the codes and apply changes if needed. But we would like to offer changing the URL a little bit to remain backward compatibility. There might be 1000 of server attributes in some cases and for performance reasons there is no need to return all of them in some cases.

**Comment by eykamp** [comment]
I have lots of Java experience.  My current problem is I can't get Thingsboard to build on my Windows machine.  But when I do...

I'm happy to work with you on the design.  It's your project, and you are no doubt aware of use cases I am not.

Chris

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
