### ISSUE TITLE
Thresholds in flot windows update when attribute is server but not when it is shared

### ISSUE THREAD

**Issue by JasonFarque** [thingsboard/thingsboard#2769]
The new flot thresholds in the 2.5PE time series windows do not update visually or save their values if they are coming from shared attributes, only if they are server attributes (the default).

In my system my devices connect to report data and download new user thresholds via REST so these attributes need to be shared.

**Comment by Ultrazombie** [comment]
Please reopen the issue if still relevant for the latest version of ThingsBoard.
