### ISSUE TITLE
Alarm table widget won't update the details element

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2771]
[With reference to this tutorial](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/) 
I set up an alarm rule chain and dashboard.
But I have the following questions about Details (update)
![pic0](https://user-images.githubusercontent.com/63713926/81909642-79be4a80-95fd-11ea-8348-5fb7762e2d8d.png)

Suppose I set details element contains 3 data
<img width="547" alt="pic2" src="https://user-images.githubusercontent.com/63713926/81909663-7f1b9500-95fd-11ea-9705-dfe140c2216b.png">
![pic1](https://user-images.githubusercontent.com/63713926/81909678-85117600-95fd-11ea-9175-83308d795995.png)

When an alarm occurs, it will directly display the data on the "Alarm Details" dialog box, but when the data changes (still under conditions), such as data2 (false-> true), the dialog box will not update the corresponding New data (Only update End time)

How to solve it?

**Comment by ashvayka** [comment]
Hi @ecmap , please use the following template:

```javascript
var details = {};
if (metadata.prevAlarmDetails) {
    // MAKES SURE THAT THE PREVIOUS DETAILS ARE USED.
    details = JSON.parse(metadata.prevAlarmDetails);
}
//INSERT YOUR LOGIC BELOW


return details;
```
