### ISSUE TITLE
Update script --fromVersion

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/thingsboard#2774]
Hi,

currently when Thingsboard is updated, the update script has to be manually called. This script requires the `--fromVersion` argument to be set.

This is quite troublesome in my opinion. 

1. It requires the user to know what what the previous version of the database. This may not be always possible, e.g. when restoring an old database backup, or if erroneously updated Thingsboard without previously noting the old version.
2. It is not always obvious what argument shall be passed to `--fromVersion`. For example when updating from 2.1.0 to 2.2.0 the argument is still 2.0.0.
3. It is a manual process so it is error-prone. If wrong `--fromVersion` argument is passed, I guess it may be difficult to recover later (Can you test all possible combinations or old, new versions and erroneous value?)

My proposition is to store the version directly to the database. So it is clear that this specific DB is meant to be used for a specific TB version. The update script shall look for this field in DB and determine on its own the correct value to use for the `--fromVersion` argument.

This way all of the above issues are solved, in a nice automated way.

**Comment by ashvayka** [comment]
We have already started using this approach and plan to completely automate it in the future.

**Comment by ashvayka** [comment]
The version is now stored in tb_schema_settings after 2.5 release

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by fjpanag** [comment]
This issue is still valid. Why it is closed?

This functionality is **very** important for automated updates / deployment, and it is [still discussed on other products of the family](https://github.com/thingsboard/tbmq/issues/115).
