### ISSUE TITLE
Error viewing private dashboard with public device

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#278]
I created a Customer "CUST" and a device "DEV", which I made public.  I also created a dashboard for CUST called "DASH".  

When I am logged in as the tenant administrator, I can see DEV on DASH just fine.  But when I create a user for CUST, and login as that user, I cannot get DASH to display info about DEV.  Some of the widgets are displayed with the message "Widget Error: TypeError: Cannot read property '0' of undefined".

I am guessing there is a permissions issue when users view devices assigned to the public user.

The goal I am trying to achieve is to create a series of users, each with one or more devices, each of whom can see a detailed dash with their devices.  I also want to create a publicly available map of all devices, to let all users browse through each other's data.

**Comment by eykamp** [comment]
The problem appears to be when the UI does a GET on http://<SERVER URL>/api/device/<DEVICE ID>

The log shows this:
 ERROR o.t.server.controller.BaseController - Error [You don't have permission to perform this operation!]

If the device is public, shouldn't I anyone have the right to run that query?

**Comment by eykamp** [comment]
I don't have my build setup working yet, but reading the code suggests the problem may be in BaseController.java, checkCustomerId(), specifically the if statement:

```
if (authUser.getAuthority() == Authority.SYS_ADMIN ||
                    (authUser.getAuthority() != Authority.TENANT_ADMIN &&
                            (authUser.getCustomerId() == null || !authUser.getCustomerId().equals(customerId))))
```

I'm not sysadmin, nor am I tenant admin, so my constomerId has to match the device customerId.  Since the device is assigned to the public user, and I am not that user, that test will fail.  I think there needs to be an explicit check to allow the device to be owned by the public user to get past that statement.

If I'm right, the fix will be trivial.  Assuming I understand how the permission model is intended to work, that is.

**Comment by ashvayka** [comment]
@ikulikov let's discuss this. Maybe this is a valid change request. Although this need to be fixed not only in a rest layer but also in a telemetry plugin.

**Comment by eykamp** [comment]
Well... it seems clear that I should be able to add a public device to a private dashboard, so I think the underlying issue is legitimate.

As to the nature of the fix, I don't yet know the codebase enough to know if the fix I proposed is proper, and I am still struggling to get a working dev environment set up, so I don't even know if it will work.  

I'm open to other ways to address the problem.

**Comment by eykamp** [comment]
I have a patch to resolve this; one cluster of tests is not passing, but when I resolve that, I'll submit a PR.

**Comment by eykamp** [comment]
One difficulty with implementing this is that the only way we know if a device is public is whether it is owned by the public user.  And, unfortunately, the only way to know if a userid belongs to the public user is to load the customer record and look either at the customer name (magic value "public") or at its attributes.  This causes some problems in objects that are essentially simple models (like Device).  These objects have a customerId, but there is no way for them to get the customer attributes needed to determine if a customer is public or not.  Therefore a Device doesn't know if it's public or not unless someone tells it, and there are few code paths that make telling it problematic.

One resolution would be to create a magic GUID for the public customer, though this would require an upgrade script to change the customer GUID and everything that connects to it.

I'm still looking for other solutions, but this may be the best way to go.

**Comment by vparomskiy** [comment]
Please use EntityView and RBAC features to implement your case
https://thingsboard.io/docs/user-guide/entity-views/
https://thingsboard.io/docs/user-guide/rbac/
