### ISSUE TITLE
Alarm widgets at 2 different Dashboard states

### ISSUE THREAD

**Issue by Regimbal** [thingsboard/thingsboard#2780]
I observed a strange behavior with my ThingsBoard CE 2.4.3 instance.

I have a dashboard with more than 2 states.
First is an overall state called "General", with one alarm table widget set to show all asset devices alarms.
A second state shows the details (called "Details") of a device belonging to the asset.

The aim is to have :
- on the "General" state : one Alarm Table showing the alarms of all devices belonging to the asset & given customer.
- on the "Details" state : another Alarm Table showing only the alarms of the concerned device

The issue is when I set the alarm table on one state, I get the exact same parameters on the other one.
Meaning same entity filter, same columns, titles etc...
To circumvent the issue, I had to create a custom alarm widget, without any modifications to it, and insert it either at one state or the other.

Sounds like a bug isn't it?

**Comment by ChantsovaEkaterina** [comment]
Hello. Such a situation may happen if you copied the widget with a reference. In this case, all the settings will be duplicated when changing.
