### ISSUE TITLE
opening multiple state dashboards 

### ISSUE THREAD

**Issue by MariamMagdy** [thingsboard/thingsboard#2782]
i watched the video of : Dashboard development guide, Part 2: Dashboard states, Aliases and Widget actions. and i wrote the code found in it at 9:5 mins but it doesn't open any state dashboard. here is my code :
var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice (entityId.id).then(function(device){
    
    if(device.type == 'energy sensor') {
      openDashboardState ('energy_state');
      
    } else if(device.type == 'water sensor') {
      openDashboardState('water_state'); 
      
    } else
    
    {
        
      openDashboardState('temperature_state');
    }  
    
});  

function openDashboardState(stateId) {
    var params = {
    entityId: entityId,
    entityName: entityName
};
widgetContext.stateController.openState(stateId, params, false);
}
so can anyone please tell my where is the problem ?

**Comment by ChantsovaEkaterina** [comment]
Hello. Could you specify the TB version you are using? Are you have any errors in the console?

**Comment by MariamMagdy** [comment]
@ChantsovaEkaterina 

i am using the live demo version on the website

**Comment by ChantsovaEkaterina** [comment]
Since the demo environment was updated to version 3.0 you should change your code a little bit to make it work.
```
var $injector = widgetContext.$scope.$injector;
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(
    function(device) {
        if (device.type == 'energy sensor') {
            openDashboardState('energy_state');
        } else if (device.type == 'water sensor') {
            openDashboardState('water_state');
        } else {
            openDashboardState('temperature_state');
        }
    });

function openDashboardState(stateId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.stateController.openState(stateId, params, false);
}
```

**Comment by MariamMagdy** [comment]
@ChantsovaEkaterina  Thank you so much . it works well

**Comment by ezeroldan24** [comment]
Good afternoon, can you do this with the id of a button developed with us? Instead of the device identifier?
