### ISSUE TITLE
The microservice of the rule engine cannot run after being packaged

### ISSUE THREAD

**Issue by christlee2258** [thingsboard/thingsboard#2783]
![image](https://user-images.githubusercontent.com/103922/82166863-73291f00-98ec-11ea-81f7-22083246d579.png)

**Comment by ashvayka** [comment]
What version are you using? There is no QueueBenchmark  in  v2.5.1

**Comment by ashvayka** [comment]
I suspect this is some custom build. We have automated tests that the docker/deb images are working.
