### ISSUE TITLE
How to get functions between multiple data-sources for each Tenant?

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#279]
I would like to use this procedure.
https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/

However my question is, how to get  "analytic gateway" data from spark for each Tenant (Entreprise A and Entreprise B), if all the data of several devices are together?

In conclusion if i have Enterprise A and Enterprise B how to specify data by Each Enterprise?

Thanks!

**Comment by kimoudev** [comment]
@ashvayka

**Comment by ashvayka** [comment]
If I understand you correctly, you want to have a spark job that processes multiple tenants? Than we need to add a $tenantId support to a template engine. You will be able to create a system rule to send all data to spark and then use it in your job. Your job will need to have login/password information for all tenants.

**Comment by kimoudev** [comment]
Exactly thanks for understanding, Company A, Company B = Tenant A, TenanB.
- Can you please give me some indications to set up "$tenantId support to a template engine".
- And also how to create "a sytem rule to send all data to spark" please. 
@ashvayka

**Comment by kimoudev** [comment]
@ashvayka  @ouertani

**Comment by vparomskiy** [comment]
Not valid anymore. Since ThingsBoard v2.x. specific Rule Nodes should be used.
