### ISSUE TITLE
[docs] Swapped labels in Telemetry User Guide

### ISSUE THREAD

**Issue by BrainCrumbz** [thingsboard/thingsboard#28]
Hi there!
Was going through your documentation to better understand your IoT platform, and maybe there's a typo on [Telemetry user guide page](http://thingsboard.io/docs/user-guide/telemetry/):

![thingsboard - working with telemetry data - mozilla firefox](https://cloud.githubusercontent.com/assets/3185573/21639952/38f0725e-d273-11e6-9f02-561d2cb71031.png)

Shouldn't *Request* and *Response* arrows (or labels) be the other way around? Isn't the cluster who requests data to the device, which in turn responds?

HTH

**Comment by ashvayka** [comment]
Hi!

Actually, device pushes data to the server using MQTT publish, CoAP post or HTTP post request.
The server then replies when the data was successfully stored in DB and processed. 
Device can upload data periodically or on certain trigger condition. You can control period of data upload by [subscribing to shared device attribute](http://thingsboard.io/docs/reference/mqtt-api/#subscribe-to-attribute-updates-from-the-server), for example "uploadFrequency".

If you want to request data from the device in real time and on demand, you can send an RPC call. This is also covered in [the docs](http://thingsboard.io/docs/user-guide/rpc/)

**Comment by BrainCrumbz** [comment]
A-ha! That makes sense. Thank you!
