### ISSUE TITLE
Devices created by MQTT gateway do not trigger ENTITY_CREATED event

### ISSUE THREAD

**Issue by helguson** [thingsboard/thingsboard#2805]
# Context
We use an [official docker image consisting of Thingsboard CE 2.4.3 and cassandra](https://hub.docker.com/r/thingsboard/tb-cassandra).

# Steps to reproduce
- setup a mqtt gateway in Thingsboard [(Step 1 in ->)](https://thingsboard.io/docs/iot-gateway/getting-started/)
- post telemetry data for a non existing device to the gateway [(->)](https://thingsboard.io/docs/reference/gateway-mqtt-api/)

# Expected behaviour
- The system creates a new device.
- The system triggers a message for an [ENTITY_CREATED event](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types) which can be processed by the [rule engine](https://thingsboard.io/docs/user-guide/rule-engine-2-0/re-getting-started/) (since creating devices manually triggers such messages).

# Actual behavior
- The system really creates a new device.
- The rule engine receives no message for an ENTITY_CREATED event regarding that device.

**Comment by YevhenBondarenko** [comment]
Hello @helguson 
Thank you. We have fixed this, changes will be available in the next release.
