### ISSUE TITLE
2.5.0 Widgets display minimum value.

### ISSUE THREAD

**Issue by Antyneutrinoo** [thingsboard/thingsboard#2807]
Hello,

After upgrading to 2.5.0 all digital gauges display always minimum value in mobile browser. The bars display correct magnitude, but the digits show always minimum. In a desktop browser everything works fine.

Anybody noticed the same behaviour?

**Comment by kopjakj** [comment]
Hello,

I recognized the same behavior.

**Comment by Antyneutrinoo** [comment]
Is this a bug or someone knows how to fix this?

**Comment by ggreeve** [comment]
+1 on this issue.
What is the release date for v2.5.1, I assume this will be fix in it. Or will v3 come our first? What about running the dev branch? Wanting to know my option on what the fasted way would be for me to get the digital gauge fix implemented. Maybe roll back to previous version?

**Comment by Alentus** [comment]
> +1 on this issue.
> What is the release date for v2.5.1, I assume this will be fix in it. Or will v3 come our first? What about running the dev branch? Wanting to know my option on what the fasted way would be for me to get the digital gauge fix implemented. Maybe roll back to previous version?

Try disable animation on widget settings. This work for me.

**Comment by ggreeve** [comment]
Thanks for the tip. That works

**Comment by ggreeve** [comment]
@Alentus Thanks for the tip. That works

**Comment by ashvayka** [comment]
This is already fixed and will be available in 2.5.1
