### ISSUE TITLE
Error:(19, 42) java: package org.thingsboard.server.gen.cluster does not exist

### ISSUE THREAD

**Issue by mybaby1** [thingsboard/thingsboard#281]
Hi:
  I  import thingsBoard(release-3) into IDEA,but there are many errors like 
"Error:(19, 42) java: package org.thingsboard.server.gen.cluster does not exist" ;
 "Error:(23, 65) java: package  org.thingsboard.server.gen.discovery.ServerInstanceProtos  does not exist";
 "Error:(31, 69) java: package   ClusterAPIProtos  does not exist"
 It seems like the package of  "org.thingsboard.server.gen" is missing.
Can anybody help me?
Thanks.

**Comment by volodymyr-babak** [comment]
This is a known issue. Please see details here:
https://groups.google.com/forum/#!topic/thingsboard/rHTlXCal4aA

**Comment by mybaby1** [comment]
I can not open https://groups.google.com/forum/#!topic/thingsboard/rHTlXCal4aA

**Comment by volodymyr-babak** [comment]
I have just verified link and it works fine.
If google is blocked in your country please use some proxy to get access to google groups.

**Comment by sunchenyang** [comment]
Has the problem been solved?

**Comment by JTechG** [comment]
With Eclipse, I am not able to compile the code since "org.thingsboard.server.gen" is not found. 
Error
"The import org.thingsboard.server.gen cannot be resolved"

Tried the steps mentioned in 
https://groups.google.com/forum/#!topic/thingsboard/rHTlXCal4aA

but it didnt help

**Comment by mp-loki** [comment]
@JTechG has the maven build succeeded? if yes, you should be able to locate the generated-sources directory under target/ and add it to the Eclipse Build Path

**Comment by Yousef962** [comment]
open meven window, open thingsboard Coap Trasport Service then open lifecycle 
then clean then install to solve this problem in intellji 
![Screenshot from 2021-08-22 22-37-05](https://user-images.githubusercontent.com/84511801/130368089-8bbd5658-0f3e-4a95-8c3b-4147e66ba644.png)
