### ISSUE TITLE
Provision for sending one data out of many to another system using REST API.

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#2810]
Hello All,
   I have multiple data say DT1, DT2, DT3, DT4, and DT5. 
I am sending all this data to Device1 of Thingsboard.
I want to segregate the data in such a way that only one data can be sent for one REST API Query.

So how can I filter the data in such a way that if I query for data DT1 only DT1 information  should get passed as a response

Thanking you all.

**Comment by ashvayka** [comment]
Please provide an example of REST API call you already make and we will comment on the alternatives.

**Comment by nmahale10** [comment]
The solution I have tried is given below:-
 I have sent DT1 to Device1,DT2 to Device2 ,DT3 to Device3,DT4 to Device4 and DT5 to Device5.
Used similar kind of query given below

http(s)://MyCloud.in/api/plugins/telemetry/DEVICE/852d8200-9788-11ea-b94b-4b8eb8a38a67/keys/timeseries

But here I need to create 5 different devices on thingsboard.


As mentioned in the earlier query I wanted to minimize devices , for that, I have sent all data to Device1. But how to handle it further. Please suggest.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
