### ISSUE TITLE
Control widget getValue method response with MQTT Gateway API

### ISSUE THREAD

**Issue by brianKarma3** [thingsboard/thingsboard#2813]
Firstly, I would like to thank all the Thingsboard developers for the amazing tool. 

I am trying to control a fan speed set point with the knob control widget and MQTT Gateway API. I have got the setValue method working but stuck at the getValue method response. 

I am trying to follow the MQTT Gateway API reference: https://thingsboard.io/docs/reference/gateway-mqtt-api/

However I cannot find a way to response the getValue method and update the knob value. 

`def on_message(client, userdata, msg):
    print ('Topic: ' + msg.topic + '\nMessage: ' + str(msg.payload))
    # Decode JSON request
    data = json.loads(msg.payload)['data']
    device = json.loads(msg.payload)['device']
    if device == 'Hab2':
        if data['method'] == 'setFanSpeedAtTemp' : 
            # Parse the message. 
            fanSpeedAtTemp = float(data['params'])
            client_local.publish('Habs/Hab2/ExtractionFan/FanSpeedAtTemperature', fanSpeedAtTemp, retain= True)
        elif data['method'] == "getFanSpeedAtTemp":
            reply_msg = {'device': device, 'id': data['id'], 'data': {'value':float(hab2.fanSpeedAtTemp) }}
            temp = json.dumps(reply_msg) 
            print("reply message: " + temp)
            client.publish('v1/gateway/rpc', json.dumps(reply_msg))`

I am not sure what to assign to the 'data' variable of the reply_msg.
I have also tried
 reply_msg = {'device': device, 'id': data['id'], 'data': {'params':float(hab2.fanSpeedAtTemp) }}
But no luck. 
Any help would be appreciated.

**Comment by ashvayka** [comment]
@zbeacon please help.

**Comment by ashvayka** [comment]
First we need to make sure that your gateway is working fine. What gateway type do you use? Is this Python gateway?

**Comment by zbeacon** [comment]
Hi @brianKarma3,

To use RPC, you should have a service, which will process all requests from TB and keep connections active. To create a device using Python, you can use the following [module](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/tb_client/tb_device_mqtt.py) or use the tb-mqtt-client module from pip3 (`pip3 install tb-mqtt-client`).
To get the RPC request from ThingsBoard - you have to create an object of the TBDeviceMqttClient class and run the method `set_server_side_rpc_request_handler`, pass the callback_function as an argument to this method.

**Comment by brianKarma3** [comment]
HI @zbeacon ,

Thank you very much for suggesting the tb-mqtt-client module.  I worked great. 

I am using the Python IoT gateway to upload sensor data from local MQTT to Thingsboard. With the tb-mqtt-client module's tb_gateway_mqtt.py, I can now write my own script to send command from TB dashboard to the local devices via the same gateway device. 

I would suggest that you can mention this module in the IoT gateway guides and/or the Raspberry Pi GPIO example, so users can refer to it.  I have done some though readings on the guide and docs on TB website and did not find a link to this module. 

KInd regards,
Brian
