### ISSUE TITLE
Active alarms are not shown in Alarm Table if created before the time interval

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#2821]
I have verified that the Alarm Table widget does not show an alarm created before the specified displayed time interval - if I am not missing anything.
If this is so, my opinion is that this is not correct because an alarm situation that is still outstanding risks to shift out of sight.
The easy workaround is to extend the time interval to the max (30 days), and that may be ok at Customer.
However, at development time, one may easily forget that an alarm was created some days before, and when the same test is run after some days, the alarm _is not shown in the Alarm Table_ (because it is only UPDATED, not CREATED) and it's hard to understand why.
In my opinion, the Alarm Table widget time interval should filter the last UPDATE timestamp of an alarm type, not the CREATION timestamp: if an alarm type is updated _now_, is relevant _now_.

**Comment by Karabiy** [comment]
regarding the max time interval to be set, you can press the advanced option to configure the time interval for the data to be observed. those is located at the left from the time setting. you also can have the alarm widget to be with an individual timewindow to be configured and in the  advanced tab you can have the alarm to be set on which exact those has to sort on.
