### ISSUE TITLE
Cant access client attributes from device in rest api call

### ISSUE THREAD

**Issue by MxTrinh** [thingsboard/thingsboard#2822]
Hello everyone,

we are trying to build a little weather station, where the dashboards gets following values from a raspberry pi:
- temperature
- humidity
- latitude
- longitude

The problem: The node "rest api call" doesnt accept for somehow our clientside attributes, but accept serverside attributes from for example customer / asset.

Rule engine:

> ![grafik](https://user-images.githubusercontent.com/37332692/82735100-922a1580-9d1f-11ea-962e-503b5b2492d4.png)

Node: device_Attributes:
> ![grafik](https://user-images.githubusercontent.com/37332692/82735105-9b1ae700-9d1f-11ea-99cd-1375545f8821.png)

Node: rest_api_call
> ![grafik](https://user-images.githubusercontent.com/37332692/82735127-b8e84c00-9d1f-11ea-82de-27f0efced8e5.png)

Device attributes:
> ![grafik](https://user-images.githubusercontent.com/37332692/82735203-357b2a80-9d20-11ea-8e62-5b909393e9dc.png)

I am thankful for every help

LG 
M

**Comment by ashvayka** [comment]
Hi @MxTrinh  Please use "Originator attributes" instead of (Related) "Device Attributes". You are probably trying to fetch the attribute of the current device and not the related one. is this correct?
