### ISSUE TITLE
o.a.coyote.http11.Http11Processor - Error parsing HTTP request header

### ISSUE THREAD

**Issue by suryasundarraj** [thingsboard/thingsboard#2823]
I see the following error, on setting up Thingsboard P.E. Version 2.5 using docker/ ubuntu setup 

mytbpe_1     | 2020-05-24 03:59:24,505 [http-nio-0.0.0.0-9090-exec-1] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
mytbpe_1     |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
mytbpe_1     | java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
mytbpe_1     | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:418)
mytbpe_1     | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
mytbpe_1     | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
mytbpe_1     | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
mytbpe_1     | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
mytbpe_1     | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
mytbpe_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
mytbpe_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
mytbpe_1     | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
mytbpe_1     | 	at java.lang.Thread.run(Thread.java:748)

Please let me know the fix. Thanks in advance

**Comment by ashvayka** [comment]
This is not critical error and may be caused by device trying to push MQTT message to HTTP port.

**Comment by Rishi-NF** [comment]
@suryasundarraj What did u do to fix this?
