### ISSUE TITLE
Layout problem (bug)? after version 3.0.0

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2829]
1. Margin cannot be 0 after v3.0(If I set it to 0, it returns to 10) 
<img width="774" alt="螢幕快照 2020-05-25 上午11 28 47" src="https://user-images.githubusercontent.com/63713926/82776697-5eb1cd00-9e7e-11ea-99b4-0ff6d95e7678.png">

2. If I set the background color to transparent, the table header is also set to transparent (it does not happen before v3.0.0)
<img width="265" alt="螢幕快照 2020-05-25 上午11 51 11" src="https://user-images.githubusercontent.com/63713926/82776871-edbee500-9e7e-11ea-8169-f04c2db5a7e1.png">

![table](https://user-images.githubusercontent.com/63713926/82777465-c9fc9e80-9e80-11ea-9f56-73d10c71b342.gif)

3. Same as question 2  (it does not happen before v3.0.0), and the position of 3 icons is fixed (how to change to non-fixed position)

(**Will this special CSS change become a template for thingsboard in the future（v3.x.x）?**)
![alarm](https://user-images.githubusercontent.com/63713926/82777428-b2251a80-9e80-11ea-82be-bee87471e61b.gif)

5. Google map widget shows watermark (Leaflet)? But it doesn't matter, I can use CSS method to hide those watermarks. 
However, the problem is that it shows a watermark (for development purposes only), I confirmed that my api key is a **paid version**, and tested with **two keys**, but it still shows this watermark.  (it does not happen before v3.0.0)
<img width="687" alt="螢幕快照 2020-05-25 上午11 29 07" src="https://user-images.githubusercontent.com/63713926/82777947-61162600-9e82-11ea-8073-eef0bf4ee5f5.png">

**Hope someone can tell me how to solve these problems (especially problems 3, 5)
V3.0.0 completely broke my previous settings (layout) :(**

**Comment by vvlladd28** [comment]
Hi,
You can provide instructions on how to reproduce the problem 4?

**Comment by ecmap** [comment]
> Hi,
> You can provide instructions on how to reproduce the problem 4?

After checking again (4), it seems that my server (image) permission problem

**Comment by ashvayka** [comment]
This is fixed and will be included into 3.0 release.
