### ISSUE TITLE
Cancel current dashboard request

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2831]
Hello :)

In Dashboards, sometimes data from a time period longer than 30 days is needed. If you are too energetic you simply say "100 days" or longer. Of course this can take some time to load - If you change your mind and switch back to 7 days or 2 hours - it takes really long to load. It looks like the current request isn't cancelled.

How can this be added?

**Comment by ashaforost** [comment]
Hi @hamburml 

In the latest releases, we've added a feature that cancels queries if they couldn't be finished in 30 seconds. Please see  [v3.3.2 release notes ](https://github.com/thingsboard/thingsboard/releases/tag/v3.3.2) and take a look at the JAVAX_PERSISTENCE_QUERY_TIMEOUT' parameter.
