### ISSUE TITLE
Incrementally update the dashboard widgets

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2832]
Hello :)

In Dashboards, sometimes data from a time period longer than 30 days is needed. If you are too energetic you simply say "100 days" or longer. Of course this can take some time to load.

The only feedback we get is a loading icon. I would like to see an incrementally update of the widget. The data which is already loaded could be displayed.

What do you think about that? Can something like that be added?

**Comment by ashvayka** [comment]
Hi @hamburml ,

what type of aggregation do you use in this case? If None - theoretically this is possible, if anything else - we aggregate data on the DB side and send the results of aggregation as one reply. This is unlikely to change in 2020.

**Comment by hamburml** [comment]
Thanks for your answer!

Yes, normally we don't use any type of aggregation because this manipulates the telemetry which was sent - and it's critical that NOTHING is changed. Wouldn't it be better to split up the requests to the db? Heavy load is bad load :)

Additionally an export of all non-aggregated telemetry which were received in a certain month (for example, could be also two month) isn't achieveable in a dashboard.
