### ISSUE TITLE
flot widget - display count in legend

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2833]
Hello.

In a flot widget we can adjust the legend to display the min value, max value, average and total value of a parameter. How can we display the count of values of that parameter?

Thanks!

**Comment by ashaforost** [comment]
Hi @hamburml,

Thingsboard doesn't provide a possibility to add custom keys to the chart legend. You can develop your own widget to fulfill your needs. Please see the [Widget Development Guide](https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/).
