### ISSUE TITLE
Make use of internal MQTT Broker

### ISSUE THREAD

**Issue by creyD** [thingsboard/thingsboard#2834]
The [official docs](https://thingsboard.io/docs/reference/mqtt-api/) state:

> ThingsBoard server nodes act as an MQTT Broker that supports QoS levels 0 (at most once) and 1 (at least once) and a set of predefined topics.

I have an MQTT gateway which is capable of sending data to an MQTT broker. However my Thingsboard Instance doesn't seem to get any data from the gateway - which implies that it can in fact not act as a broker. I checked manually using the command line and `mosquitto_pub` and there is no error message, but also no data showing up in the Thingsboard.

Does the Thingsboard instance provide an MQTT broker or not? And if yes, how do I activate it?

**Comment by ashvayka** [comment]
Hi @creyD . What environment do you use? Is this a demo.thingsboard.io or your local setup?

**Comment by creyD** [comment]
It is our local installation on a server with a static IP. @ashvayka

**Comment by scybZhangliang** [comment]
Is "ThingBoard Server Node" really a broker?,if it is,how do it work in the cluster mode? and how do i configure my mqtt-transport service（specific the broker address）?

**Comment by creyD** [comment]
We wrote our own broker for now, but I would be highly interested why the docs state it as "broker" when it doesn't contain one.

**Comment by creyD** [comment]
@ashvayka I would like to close these tickets, but I still am a bit confused. Could you please clear things up?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
