### ISSUE TITLE
why not IdleStateHandler in server？

### ISSUE THREAD

**Issue by yzzh9** [thingsboard/thingsboard#2837]
why not IdleStateHandler in server？

**Comment by ashvayka** [comment]
please provide more details.

**Comment by yzzh9** [comment]
Abnormal disconnection of device . In the server side，How do I know if the device is disconnected？I know can be implemented by  'IdleStateHandler' ,but I do not see 'IdleStateHandler' in the server side.

**Comment by yzzh9** [comment]
> please provide more details.

Abnormal disconnection of device . In the server side，How do I know if the device is disconnected？I know can be implemented by 'IdleStateHandler' ,but I do not see 'IdleStateHandler' in the server side.

**Comment by ashvayka** [comment]
This depends on the protocol you use. For MQTT this is based on ping logic that is embedded to the mqtt protocol. What protocol you are using?

**Comment by yzzh9** [comment]
> This depends on the protocol you use. For MQTT this is based on ping logic that is embedded to the mqtt protocol. What protocol you are using?

I'm using MQTT. For MQTT ping logic that is:
`            case PINGREQ:
                if (checkConnected(ctx, msg)) {
                    ctx.writeAndFlush(new MqttMessage(new MqttFixedHeader(PINGRESP, false, AT_MOST_ONCE, false, 0)));
                    transportService.reportActivity(sessionInfo);
                }
                break;`
For PINGREQ, only reply PINGRESP. 
Abnormal disconnection of device, For example, the network cable is broken. ping logic didn't deal with it.

**Comment by ashvayka** [comment]
the transportService.reportActivity updates the local state of the session. If there is no connectivity, the service will send inactivity event automatically. The session inactivity timeout is configured using TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT env variable and is periodically reported to TB Core using TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT parameter.
