### ISSUE TITLE
Dont know how to do a square root account in thingsboard

### ISSUE THREAD

**Issue by Game0nPT** [thingsboard/thingsboard#2840]
I guys
I have a project using a nodemcu+mpu6050 and i send data via telemetry to thingsboras. The objective is to in thingsbora duse the parameters of the acelaration and do something like this in a script:
square root((AcX * AcX)+(AcY * AcY)+(AcZ * AcZ))
The problem is that i dont know how to do the square, i have tryed something like this : Math.Square... but it doesnt work
If anyone knows how to do that please let me know

**Comment by ChantsovaEkaterina** [comment]
Hello, a function that you need: Math.sqrt().
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt

**Comment by Game0nPT** [comment]
Thanks, when i put Math.s   the word square dindnt apear so i thought it would not work
