### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chriswang-** [thingsboard/thingsboard#2841]
** Tb Gateway device could not remotly config in the Thingsboard UI(device details menu)**

I am trying to config a gateway device in thingsbaord Device details menu. In the tab Extentions, which I want to add a MQTT broker to the gateway, But it doesnt work. 

BWT, It is valid config the gateway in the local config file.

Is it bug?  Or something I am mis-understanding?

**Comment by ashvayka** [comment]
We are deprecating the Extensions tab in favor of new widget that is available in widget library. This tab is removed in v3.0
