### ISSUE TITLE
AWS-SQS: Forced usage of credentials

### ISSUE THREAD

**Issue by janschumann** [thingsboard/thingsboard#2843]
The AWS SQS implementation forces the use of access keys provided by specific config properties and makes it impossible to fallback to the standard behavior off the AWS sdks, which includes fallback to ENV variables, the default credential profile and most importantly: the instance profile.

https://github.com/thingsboard/thingsboard/blob/b124f86a0f49c6b39b7bcce1760edb0922b26841/common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java#L40

Would you accept a PR which enables the default credentials provider chain? https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-roles.html

**Comment by ashvayka** [comment]
Yes, we will accept, if you explicitly add a parameter. 

queue.aws_sqs.use_credentials_from_env (or similar) to thingsboard.yml

**Comment by ashvayka** [comment]
Thank you for highlighting this!

**Comment by ashvayka** [comment]
@YevhenBondarenko please fix this in 2.5.2
