### ISSUE TITLE
Thingsboard 2.5 Install Issue  

### ISSUE THREAD

**Issue by bharathivlsi08** [thingsboard/thingsboard#2852]
When i am trying to install the .deb file or compile from source i am facing issue when i run installation script

I dont face the issue with the version 2.4.3

Can anyone help here please.

![Screenshot from 2020-05-27 14-52-21](https://user-images.githubusercontent.com/7710920/83001979-1b945d00-a02a-11ea-998e-1ab684fa38e6.png)

**Comment by hamburml** [comment]
Do you use postgresql 11 or greater? I think v2.5 needs postgresql 11 or greater.

**Comment by bharathivlsi08** [comment]
@hamburml  Thank you for the information, you saved my day. I have installed postgresql 11, but postgresql 10 was in use. Removed postgresql 10 helped to solve the issue.
