### ISSUE TITLE
[feature] export CSV from dashboard / portal

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#286]
Often users ask for the ability to export data to CSV from the UI. They either want to see the data for specific parameter for a specific device,  but often they ask for full export of the data.

do you plan on adding such feature?

Let me know if I can provide any other details-specifics.

**Comment by Poquaruse** [comment]
We have been thinking about this, too. Our users would be very much interested in such a feature. 

One way of doing it could be an external service which receives an RPC (incl. device, start and end timestamp), then triggers the database for the data and finally creates the requested dataset... Not the cleanest way of doing it but I guess it could work?! 

What do you think?

**Comment by t0mmyz7** [comment]
Hi!

So depends who your users are, I am thinking about end-users who consume the data and use it daily. They need it to be as easy as a click of a button.

Select time range, select devices, export data.

something like that, also a data explorer is usually a great tool to have.

**Comment by Poquaruse** [comment]
From that point of view you're absolutely right. Now that you explained it, I have several use cases in my mind. 👍

**Comment by logivity** [comment]
This is a very important feature to implement in current setup as most companies have several non linked software that require data to be fed manually. 

Best place to put this would be on dashboard in relation to time-window so that user can choose the time-frame from which data should be recorded.  Simplest solution from user perspective I can see is extracting data that is fed to widgets based on time-window. There should be multi select box from which columns of relevant database should be exported.

**Comment by toti1212** [comment]
This is a great feature to be incorporated. @ashvayka are planning to incorporate it in the next versions?

**Comment by nmenoni** [comment]
Yes, I also agree that it is a very necessary feature! Thanks!

2017-11-09 9:51 GMT-03:00 Rodrigo Suarez <notifications@github.com>:

**Comment by aderbas** [comment]
+1

**Comment by fabianoms** [comment]
Looks like this feature was only added in the Professional Edition. 
Pull requests related to this feature could be accepted?

**Comment by minexew** [comment]
I guess not.

**Comment by vparomskiy** [comment]
This feature was implemented as part of PE and we do not plan to move it to open source. But if it is important for you, you can implement it for your case with the custom widget.

**Comment by daisy-dai** [comment]
Is this feature implemented? I also need it very much.

**Comment by maxwmsilva** [comment]
> Often users ask for the ability to export data to CSV from the UI. They either want to see the data for specific parameter for a specific device, but often they ask for full export of the data.
> 
> do you plan on adding such feature?
> 
> Let me know if I can provide any other details-specifics.

Hello man How can I export data from thingsboard widget ? version CE ...

**Comment by fuu0** [comment]
Does anyone have any solutions for the CE version? I'm trying to set up a weekly csv upload and wonder why it's so difficult.
