### ISSUE TITLE
[Question] Does ThingsBoard reload the mqttserver.jks file?

### ISSUE THREAD

**Issue by hamburml** [thingsboard/thingsboard#2861]
**Component**

 * Generic

**Description**
We use MQTT over SSL (https://thingsboard.io/docs/user-guide/mqtt-over-ssl/). Our certificates are created via Let's Encrypt. The Let's Encrypt certificates are valid for 90 days and are refreshed after 30 days.

I want to automatically renew the Let's Encrypt certificates (which already works) and automatically create a new mqttserver.jks - This already works. Do I need to restart ThingsBoard or does it automatically reload the file when it's replaced? I would love to have no downtime :)

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: 2.5 PE

**Comment by Ultrazombie** [comment]
Yes, I think you should reload the ThingsBoard so that it sees the new key file
