### ISSUE TITLE
Save only latest value of telemetry

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#2862]
I am sending data to Device1 
Values as
First :- {"key1":10}  
Second:-{"key1":11}
Third:-  {"key1":12}
So if First value comes it should be sent to telemetry.
If "Second" value come  "ONLY " it should be sent to telemetry Discarding "First" Value.
If "Third" value comes  "ONLY " it should be sent to telemetry Discarding "First" and "Second" Value
(From DB if possible).

I have just checked ,it is possible by passing some  queries.
Deleting can be done manually.

But how to do it same in Thingsboard UI.

So if we put this data in Table of dashboard .Only latest value must be visible.

Thanking yo all.

**Comment by Karabiy** [comment]
for the reason of yours, you need to create the custom widget, which will handle all the operations at once. you may refer to the TB sources and also guide on [this link](https://thingsboard.io/docs/user-guide/contribution/widgets-development/
) can be useful for you
