### ISSUE TITLE
[Bug] "digital gauges" widgets display error with safari on iPhone:widget error: typeerror:null is not an object (evaluating 'this.contextValueClone.translate')  

### ISSUE THREAD

**Issue by yingzhangOK** [thingsboard/thingsboard#2869]
**Describe the bug**
Switch between horizontal and vertical screens(portrait to landscape)

With iOS devices, I get below errors on "digital gauges" widgets, but working fine on Win 7, 10, macos:

widget error: typeerror:null is not an object (evaluating 'this.contextValueClone.translate')
widget error: typeerror:undefined is not an object (evaluating 'self.ctx.gauge.update')

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * ThingsBoard 2.4.3 and above
  * Win10 and Ubuntu16

**Your Client Environment**

**Smartphone (please complete the following information):**
* Device: iPhone8, iPhoneXR and iPhoneXS max
* OS: iOS12.0 and iOS13.3.1
* Browser: chrome and safari
* Version: chrome 76.0.3809.123, safari system-provided

**Screenshots**
![image](https://user-images.githubusercontent.com/15194833/83138922-1fa1a700-a11e-11ea-8806-d9888c79ac3f.png)
![image](https://user-images.githubusercontent.com/15194833/83139062-5d063480-a11e-11ea-8e23-b6dd209c602f.png)
![image](https://user-images.githubusercontent.com/15194833/83139140-7b6c3000-a11e-11ea-8e0c-839c3562b11e.png)

**Comment by ashvayka** [comment]
It looks like you have a local environment? If not - please share your account on demo.thingsboard.io privately (we need only login name) to info@thingsboard.io and we will check with our device on your account. We can't reproduce this on our account.

**Comment by yingzhangOK** [comment]
demo/cloud all have this problem，i have send you a email. thanks
