### ISSUE TITLE
[Question] What is the Best way to upgrade PostgreSQL Schema while keeping Data?

### ISSUE THREAD

**Issue by harshchauhan11** [thingsboard/thingsboard#2870]
**Component**
PostgreSQL Database Upgrade

 * Installation

**Description**
What is the best way to upgrade existing PostgreSQL Database Schema regularly (when alteration happens in the new Commits), while keeping all old Devices, Assets, Telemetry data as it is?

As of now, I am altering Database directly by altering queries added in the commit as per the new version of ThingsBoard. I have also tried to run "ThingsboardInstallApplication.java" with jar command, but it didn't upgrade the schema as per new changes.

**Environment**
 * OS: Windows 10
 * ThingsBoard: 2.4.3
 * Browser: Chrome

**Comment by hamburml** [comment]
Why don't you use the UpdateScript? https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-25

In Linux for example:
`sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.3`

**Comment by ashvayka** [comment]
Following the upgrade procedure (mentioned by @hamburml in the previous comment) is the correct way to do this.
