### ISSUE TITLE
Unable to send telemetry data to Thingsboard using Curl (HTTP)[Bug] 

### ISSUE THREAD

**Issue by naddush** [thingsboard/thingsboard#2872]
**Describe the bug**
I'm using Thingsboard CE in my local server, I've created an asset and a device and I tried to send some telemetry data using Curl command as bellow, normally it tells that the connection has been established and the message also sent, but the data wasn't displayed on thingsboard .
here is the command that I used, I also used the token of my device .

curl -v -X POST -d "{\"temperature\": 30}" localhost:8080/api/v1/5c47f4c0-a0f6-11ea-8e73-73276fac7ed2/telemetry --header "Content-Type:application/json"

**Your Server Environment**

* demo.thingsboard.io
* HTTP
  * ThingsBoard 
  * ThingsBoard Version CE
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows[e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * HTTP

**Comment by ashvayka** [comment]
I suspect  you are trying to use [telemetry upload API](https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api). The issue is that you are using device id instead of device access token.
