### ISSUE TITLE
[Bug] Can`t choose datasource.

### ISSUE THREAD

**Issue by mervyned** [thingsboard/thingsboard#2873]
**Description**
Why I can`t choose datasource for widget sometimes? but it will be ok after reboot tb system.

[Screenshot](https://m-private-storage.oss-cn-beijing.aliyuncs.com/HAOHT/bug.jpg)

**Environment**

ThingsBoard: 2.4.2
Browser: Chrome

**Comment by ashvayka** [comment]
Have you tried to click on "+" icon (create new data source)?

**Comment by mervyned** [comment]
After click on "+" icon,nothing happened!

**Comment by Karabiy** [comment]
have you tried to reload the page itself? 
Also, it is recommended to have an upgrade for the latest version of the ThingsBoard to make sure that the issue does persist on the actual version
