### ISSUE TITLE
[Question] What's the best way to let customer set up alarm thresholds

### ISSUE THREAD

**Issue by xhr0428** [thingsboard/thingsboard#2875]
**Component**

 * Generic

**Description**
What's the best way to let customer to set up alarm thresholds for individual devices and even enable/disable alarm email notification? Thanks

**Comment by RondoRonaldo** [comment]
You can use the next approach:

Thresholds are stored as server attributes in a required device. By using input widgets on a dashboard a customer user will be able to change these thresholds. In a rule chain by using the "originator attributes" rule node incoming messages will fetch threshold attributes from the device and going through the "script" filter rule node only valid messages will create an alarm and will be sent as an email. 
![image](https://user-images.githubusercontent.com/43723966/88823101-5e5ee680-d1cd-11ea-8a54-5654840f12ee.png)
