### ISSUE TITLE
[Bug] Custom Widget working flawless in Dev-Environment but wont work on Dashboard

### ISSUE THREAD

**Issue by Xerf1** [thingsboard/thingsboard#2877]
Since a few days ago our thingsboard-instance suddenly got problems with not finding functions from importet libraries anymore. But this problem only persists outside of the Thingsboard Dev-Environment. 

Heres an example:
I have programmed a custom list-widget which uses the jquery.scrollTo library (https://github.com/flesler/jquery.scrollTo) to scroll the list to the selected entry. 
This worked flawless for over a month now. Yesterday I decided to slighty change the layout of some labels in a list-entry. So I didn't even touch any javascript-code or change something in the requirements tab. 
However after saving, everything was fine inside the Widget-Dev-Environment but outside of it, on an actual dashboard, console told me that the ".scrollTo()" function that ive importet and that worked before, suddenly is no function anymore. 

Another example:
In a custom Calendar-Widget Ive programmed, Ive been using the daterangepicker library (https://www.daterangepicker.com/) to select a custom date-range. Today i wanted to add a function to grey out the calendar if there is no data available yet. So after adding this functionality, again in the Dev-Environment everything was working fine, but outside of it, none of the daterangepicker's functions were working anymore. It seemed like while the HTML- and CSS portions of the Library were imported fine, the JS-Part wasn't importet at all. 

I got that last example working again, after exporting and importing the widget a few times, even creating a new widget once and copying all the code by hand and changing the import address in the resources tab from "//cdn.jsdelivr.net/..." to "https://cdn.jsdelivr.net/..". However this did not work on the first example which still isn't working. 

Regarding my server Environment: 
We have our own Thingsboard Instance set up on a pretty powerful Server, with Docker.
Weve got 2 Thingsboard-Nodes running for load-balancing purposes. However I'm not the Server guy, so if you need more infos about the Setup, just hmu.
 
Client Environment:
Same problems on Desktop with Chrome, Desktop with Firefox and Chrome on a Smartphone.

I dont really know how to reproduce it yet. But since the bug only appears on a real dashboard and wont inside the Dev-Environment, it must have something to do with environmental differences between these two states. I hope you guys know what differences there are, especially regarding the loading of outside libraries. 

Hope you get that fixed soon, Its pretty hard to continue developing widgets if I cant trust the preview panel in the widget development environment. 

Kind Regards

Paul

**Comment by Ultrazombie** [comment]
Please reopen if still relevant
