### ISSUE TITLE
How to read JSON keys

### ISSUE THREAD

**Issue by mircopz** [thingsboard/thingsboard#2882]
**Component**

 * UI

**Description**
Since from TB 2.5 the value of a key can be a JSON also. This allows to send a JSON object from a device without stringify it, but from an UI point of view, is there any advantage? I created a timeseries table with a JSON datakey, but it is represented as a string. So the only way to read an inner key is to user JSON.parse function on the string.
Is there any way to access the inner JSON keys?

**Environment**

 * ThingsBoard: 2.5

**Comment by ashvayka** [comment]
You may use post-processing function or cell content value function in the data source (key) configuration of your widget. Example of Cell Content Function may be found here:
https://github.com/thingsboard/thingsboard/blob/release-2.5/application/src/main/data/json/demo/dashboards/rule_engine_statistics.json

```javascript
return JSON.parse(value).ruleChainName;
```
