### ISSUE TITLE
[Question] Is there a way to use Aggregate latest node with less than a minute interval ?

### ISSUE THREAD

**Issue by Itgvs** [thingsboard/thingsboard#2883]
I am using the following layout
Customer having several assets and several devices per each asset.
I need to aggregate (sum) the latest energy telemetry key from all devices per 10 seconds interval, the lowest interval available in the node is 1 minute, is there a way to make it 10 seconds ?

**Comment by ashvayka** [comment]
This is UI limitation. You can download the rule chain JSON and manually change the value to 10 seconds.
