### ISSUE TITLE
[Question] Is it possible to disable the built in web ui in TB single docker images?

### ISSUE THREAD

**Issue by jPXUGAAt54** [thingsboard/thingsboard#2885]
**Component**

 * UI

**Description**
Is it possible to disable the web ui in single docker images? I tried to change the server.js file in /ui/ bit it did not work. As i have to say that i do not fully understand the file structure yet it would be freat if one experienced user could guide me into the right direction here.

I want to achieve the following:

- Spin up a single docker image of tb-postgres
- Be able to access the /api/ endpoints
- Disable user login over web ui

Thanks in advance

**Environment**

 * OS:  Ubuntu 16.04.6 LTS
 * ThingsBoard: 2.4.3
 * Browser: Chrome, Firefox

**Comment by Ultrazombie** [comment]
ThingsBoard functionality does not provide this in a monolithic installation.
