### ISSUE TITLE
RPC setup issue

### ISSUE THREAD

**Issue by sarmelo** [thingsboard/thingsboard#2887]
Hello,

   I 've been using Thingsboard demo for an academic project and I 've been stuck for some time with this issue. My project consists of 2 sensors connected on rasp's, one slave and one master. I want to make a setup, where the master sensor will send (via Thingsboard) message to the slave to start sending data, upon hitting a specific threshold.
   While i am able to send data with no problem from both sensors individually, there seems to be an issue with either my rule setup or the code of the slave. The code is: 
```
import os
import time
import sys
import board
import busio
import adafruit_adxl34x
import paho.mqtt.client as mqtt
import json

THINGSBOARD_HOST = 'demo.thingsboard.io'
ACCESS_TOKEN = 'access_token'

INTERVAL=2

sensor_data = {'ASx': 0, 'ASy': 0, 'ASz': 0}

i2c = busio.I2C(board.SCL, board.SDA)
accelerometer = adafruit_adxl34x.ADXL345(i2c)

def on_connect(client, userdata, rc,*extra_params):
    print('Connected with result code ',rc)
    client.subscribe('v1/devices/me/rpc/request/+')

def on_message(client, userdata, msg):
    print('Topic: ' + msg.topic + '\nMessage: ' + str(msg.payload))
    data = json.loads(msg.payload)
    if data['method'] == 'start':
        # Sending acceleration data to ThingsBoard
        client.publish('v1/devices/me/telemetry', json.dumps(sensor_data), 1)

next_reading = time.time()

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
client.username_pw_set(ACCESS_TOKEN)
client.connect(THINGSBOARD_HOST, 1883, 60)

client.loop_start()

try:
    while True:
        Ax, Ay, Az= accelerometer.acceleration
        print(u"Ax: {:g}m/s, Ay {:g}m/s, Ay {:g}m/s".format(Ax, Ay, Az))

        sensor_data['ASx'] = Ax
        sensor_data['ASy'] = Ay
        sensor_data['ASz'] = Az

        next_reading += INTERVAL
        sleep_time = next_reading-time.time()
        if sleep_time > 0:
            time.sleep(sleep_time)

except KeyboardInterrupt:
    pass

client.loop_stop()
client.disconnect()
```

  I am getting the rc code (1) but nothing after that.
  My custom rule chain is shown below. It is connected to the root rule chain on the "Save Telemetry" node upon "Success".
![rule chain](https://user-images.githubusercontent.com/66205679/83351791-b0ab9480-a34f-11ea-93d3-236459cebebf.png)

It is my first time using Thingsboard and i 'm not very proficient in python also... I have sweeped the guides but i cannot make progress from here...

**Comment by ashvayka** [comment]
Similar scenario is described here: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/

Long story short - you need to change originator of the message to related device.

**Comment by sarmelo** [comment]
Thanks for the reply. I have put the "change originator" node already, before the script node based on this guide: [](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/check-relation-tutorial/)

But still, I dont get any telemetry from my 2nd device nor any message on my device monitor (except the rc). I also have swapped the relation types in every possible combination (I think...).

**Comment by ashvayka** [comment]
please attach your rule chain JSON for review.

**Comment by sarmelo** [comment]
well, it seems there was an OS issue as it is operational now. Thanks anyway :)
