### ISSUE TITLE
Problem with scheduler crashing ThingsboardPE 2.5 

### ISSUE THREAD

**Issue by pharmboyz** [thingsboard/thingsboard#2889]
**Component**

 * Installation

**Description**
When I try to run a scheduled report the Thingsboard server crashes and the whole server needs to be rebooted.

**Environment**

 * OS:  Ubuntu 18+ running on AWS
 * ThingsBoard: version 2.5 PE
 * Browser: Chrome
[Scheduler error.txt](https://github.com/thingsboard/thingsboard/files/4709374/Scheduler.error.txt)

**Comment by ashvayka** [comment]
What is your server resources? I assume this is using PostgreSQL? Is it loaded during handling the report request? One of the options is that server starts consuming some memory and on constrained environments Linux is killing the process due to low memory.

**Comment by Karabiy** [comment]
have you installed the web reporter component of the ThingsBoard?
