### ISSUE TITLE
dashboard AngularJs Err:10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by sdfantasy** [thingsboard/thingsboard#289]
when I use a dashboard with 10 charts. when i add the 11th chart ,the console window show the msg below:

![i gczg f8cc4 l n162 h](https://user-images.githubusercontent.com/13897059/30356639-a1091bd8-986c-11e7-8572-7acc58d4cabd.png)

.and my explorer crashed. the 10 charts all use random function,do 10 functions is the max?

**Comment by ashvayka** [comment]
@ikulikov please review this.

**Comment by Terny22** [comment]
This is fixed now in master branch and deployed to demo environment.
