### ISSUE TITLE
Create devices, relation, and assets

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#2894]
Hi, I am new to thingsboard. I want to create multiple devices, assets and define their relation. However, I do not want to these using the thingsboard interface. I see that their is  a ThingsBoard REST API Client that lets you do this. Is there a way where I can do this using python? THe REST API client is using JAVA, however, I do not know how to incorporate that file code.

**Comment by ashvayka** [comment]
You may use [REST API documentation](https://thingsboard.io/docs/reference/rest-api/) available via swagger UI. We will consider adding the Python REST API client as well.

**Comment by fjpa121197** [comment]
If I need to create around 10,000 devices. I'll need to do it manually?

**Comment by fjpa121197** [comment]
Thanks, the documentation available helped me to see that I can create post requests to create devices! Thanks!
