### ISSUE TITLE
[Bug]Error msg "Incorrect ReadTsKvQuery. Key can't be empty" appears many times.

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#2896]
**Describe the bug**
Runing two days after it was upgraded to v2.5.1, the server cannot show any new telemetry data. And I found thingsboard gave many error information using "journalctl -u". 
One type of msg appeared many many times:
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]: Exception in thread "ForkJoinPool-2-worker-40" org.thingsboard.server.dao.exception.IncorrectParameterException: Incorrect ReadTsKvQuery. Key can't be empty
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.validate(BaseTimeseriesService.java:202)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.ArrayList.forEach(ArrayList.java:1257)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.findAll(BaseTimeseriesService.java:68)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.subscription.DefaultSubscriptionManagerService.handleNewTelemetrySubscription(DefaultSubscriptionManagerService.java:336)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.subscription.DefaultSubscriptionManagerService.addSubscription(DefaultSubscriptionManagerService.java:144)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at com.sun.proxy.$Proxy223.addSubscription(Unknown Source)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.subscription.DefaultTbLocalSubscriptionService.pushSubscriptionToManagerService(DefaultTbLocalSubscriptionService.java:134)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.subscription.DefaultTbLocalSubscriptionService.addSubscription(DefaultTbLocalSubscriptionService.java:125)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService$4.onSuccess(DefaultTelemetryWebSocketService.java:537)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService$4.onSuccess(DefaultTelemetryWebSocketService.java:522)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1078)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Jun 01 12:02:34 youxuautomatic thingsboard.jar[7744]:         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard 2.5.1
  * debain 9.6

**Your Device**

* Connectivity
  * MQTT

**Comment by ashvayka** [comment]
ThingsBoard 2.5.1 was released yesterday evening. In your bug report you identify that you are running it for two days. How is this possible? Maybe you use 2.5.0?

**Comment by lsyer** [comment]
It was 2.5.1, I compiled it by myself.
