### ISSUE TITLE
Sending a "POST" rest api call

### ISSUE THREAD

**Issue by MxTrinh** [thingsboard/thingsboard#2897]
Hello everyone,

I have the following configuration in the rule engine:
![grafik](https://user-images.githubusercontent.com/37332692/83497739-2f711080-a4bb-11ea-9ac4-ee816e4c25e1.png)

The generator node has the standard code:
![grafik](https://user-images.githubusercontent.com/37332692/83497810-516a9300-a4bb-11ea-959c-6bab88ffc8e5.png)

Which results into following result:
![grafik](https://user-images.githubusercontent.com/37332692/83497835-5b8c9180-a4bb-11ea-87f5-c7f26a196957.png)

I want to do this "POST" request:
![grafik](https://user-images.githubusercontent.com/37332692/83497924-7d861400-a4bb-11ea-9c3d-f24bdb5ea2d8.png)

But it doesnt work. I tested it on Insomnia and the request works there:
![grafik](https://user-images.githubusercontent.com/37332692/83498011-9ee70000-a4bb-11ea-8727-b008f9a2b9c2.png)

Did I miss something in the Rule Engine? 

With best regards,
M

**Comment by ashvayka** [comment]
Try adding Content Type header (application/json). Many servers filter out request by content type

**Comment by ashvayka** [comment]
Have you tried enabling debug log and checking the debug messages in the "Events" tab.

**Comment by MxTrinh** [comment]
I could fix it with the addition of "Content-Type". Thanks for the help @ashvayka
