### ISSUE TITLE
[Bug] Loss of RPC communication after device reconnects to Thingsboard server

### ISSUE THREAD

**Issue by CharlRossouw** [thingsboard/thingsboard#2898]
**Describe the bug**
The ESP32-based device is measuring telemetry data. The Thingsboad server is running on the Microsoft Azure cloud. The device is sending telemetry data to the Thingsboard server using MQTT. The Thingsboard server is also sending RPC's, when applicable, to the device. All functionality continues to work until the device reconnects to the Thingsboard server (the WiFi connection remain uninterrupted). After the device has successfully reconnected to the Thingsboard server, the telemetry data is sent and received fine. However, from this point on, no RPC's can be sent to the device. A "408" error is displayed on the server and no commands are received on the device. (the RPC timeout has been increased but did not work)

**Your Server Environment**

Own setup on Microsoft Azure
  * cloud deployment
  * ThingsBoard Version 2.4.3 PE
  * Linux virtual machine using recommended settings

**Your Client Environment**

**Desktop (please complete the following information):**
* OS: Windows 10
* Browser: Chrome 

**Your Device**
ESP32 WROOM

* Connectivity
  * MQTT
*ESP32 DEVKIT by Espressif*

**To Reproduce**
Cannot forcibly reproduce behavior. When the device looses MQTT connection to the Thingsboard server it automatically reconnects before trying to send more data. The connection is successful and the device is able to send telemetry data. Once reconnected, the Thingsboard server reports a "408" error whenever a RPC is sent (the device does not receive anything on the RPC topic). This error does not exist until the device reconnects to Thingboard.
**If the device is rebooted or and the WiFi connection is reestablished then the error disappears**

**Expected behavior**
It is expected that the device receive RPC's after reconnection with the Thingsboard server.

**Screenshots**
The expected response from the Thingsboard server (custom dashboard widget):
![image](https://user-images.githubusercontent.com/60431336/83507775-4f0f3580-a4c9-11ea-885b-9edf94145932.png)
The expected response on the device (from the serial monitor):
![image](https://user-images.githubusercontent.com/60431336/83507870-6f3ef480-a4c9-11ea-91ff-208a1ba2d519.png)

The error message received when error occurs:
![image](https://user-images.githubusercontent.com/60431336/83507948-8a116900-a4c9-11ea-9eea-76a7b4160e4c.png)

**Additional context**
The RPC's are being sent to the device through a custom widget on a dashboard. The RPC's can also be sent using the "RPC Debug Terminal" widget on a dashboard. Both work fine until the device reconnects.

**Comment by ashvayka** [comment]
Are you sure that your device is subscribing to "v1/devices/me/rpc/request/+" after reconnect? The subscriptions are not persisted.
