### ISSUE TITLE
Where does the telemetry message come from?

### ISSUE THREAD

**Issue by yuyihan666** [thingsboard/thingsboard#290]
![qq 20170913183059](https://user-images.githubusercontent.com/22385476/30372856-e0630b5a-98b1-11e7-8d86-5458a53888dd.png)

**Comment by volodymyr-babak** [comment]
from database

**Comment by yuyihan666** [comment]
I know that the telemetry data comes from database, But I want to know what the difference between the latest telemetry showed in the "latest telemetry" tab in device, rule and asset. what your intent?

**Comment by ashvayka** [comment]
The intent is that you can put custom telemetry in the asset or tenant or customer entity. We have added ability to assign telemetry and attributes to all sorts of entities just for a flexibility.

**Comment by yuyihan666** [comment]
what I understand is that if I assign several devices to a asset, then I can get those devices' telemetry data showed in the asset's "latest telemetry" tab, meantime I can setup some rules to aggregate those telemetry data from devices as one showed in asset, yes?   I don't find anywhere to customize the aggregate rules!!!

**Comment by yuyihan666** [comment]
@ashvayka
