### ISSUE TITLE
Rule Engine Base

### ISSUE THREAD

**Issue by ahmedwahdan** [thingsboard/thingsboard#2901]
Hello,

I see that Things-board rule engine is almost the same as Node Red, so if I want to build my own rule engine what is the technologies, principles, ...etc that I should know to be able to achieve that.

Thank you!

**Comment by Karabiy** [comment]
it is highly recommended to take computer science courses. you can refer to the TB sources as the knowledge base, in case if you want to proceed on programming is a Java.
