### ISSUE TITLE
DEBUG Mqtt transport in thingsboard

### ISSUE THREAD

**Issue by faithware** [thingsboard/thingsboard#2902]
Thingsboard 2.5

I have a strange issue with my devices disconnecting from thingsboard ones a three days and never be able to reconnect. I am using MQTT SSL over 2G network.
Disconnections happens ones a while but my devices are   able to reconnect. But when it disconnects after 3 days, my devices can't reconnect and only hardware reset makes them able to reconnect again.
I am suspicious of the MQTT client that my devices are using. I want to see all the MQTT activity in thingsboard.log 
I should recompile thingsboard and modify the logging information but there is no documentation about it. How can I enable MQTT logging in thingsboard.log

Thanks very much for the help

**Comment by faithware** [comment]
No chance for an answer here?

**Comment by faithware** [comment]
@ashvayka Would anyone answer my question?

**Comment by Karabiy** [comment]
> I am suspicious of the MQTT client that my devices are using. I want to see all the MQTT activity in thingsboard.log

you can setup those in the logback.xml file. Also, make sure t hat the devices of yours does not drop connection on their side.
