### ISSUE TITLE
kafka connection not actual address

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#2904]
**Describe the bug**
 Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available

**Your Server Environment**
* own setup
  * local infrastructure:standlone 
  * ThingsBoard Version : 3.0
  * OS Name and Version:  windows and jetbrans
 
when I run the application ,it can not run normally.I writte the kafka address is remote but the actual connect address is the local address. and in the 2.5 version it is noramally

**Comment by Karabiy** [comment]
Make sure that the kafka application of yours is running okay and is accessible using the port you have mentioned. For those reasons you can use the nmap utility or just go with the netstat. 
Also, specify on how exact you are trying to connect to those.

**Comment by trypzz** [comment]
Hi, @zth390872451 

Do you have additional questions or I can close this issue?

**Comment by trypzz** [comment]
Closed due to inactivity.
