### ISSUE TITLE
[Question] Custom Action not working after upgrade to V3.0

### ISSUE THREAD

**Issue by Itgvs** [thingsboard/thingsboard#2906]
Currently i'm using "Entities hierarchy" widget and the below custom action code to browse between dashboard states based on Device/Asset selection.
The below code was working fine but recently it stopped working, I've matched the code with the recent tutorial published 28 May and nothing seems to be changed.
Please advise if there is something i need to modify for the below code to work

`var $injector = widgetContext.$scope.$injector;

if (entityId.entityType === 'DEVICE') {
    $injector.get('deviceService').getDevice(entityId.id)
        .then(
            function(device) {
                openDashboardState('devices');
            });
} else if (entityId.entityType === 'ASSET') {
    $injector.get('assetService').getAsset(entityId.id)
        .then(
            function(asset) {
                openDashboardState('asset');
            });
}

function openDashboardState(stateId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.stateController.openState(stateId, params,
        false);
}`

**Comment by vvlladd28** [comment]
Hi @Itgvs, 
In the new version of TB 3.0, we update the Angular version, and some features need to be updated to work correctly on the new version. Examples are available in **Custom action (with HTML template)**.
To make your code work, you need to change:
`$injector.get('deviceService').getDevice(entityId.id).then(` => `$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(`
`$injector.get('assetService').getAsset(entityId.id).then(` => `$injector.get(widgetContext.servicesMap.get('assetService')).getAsset(entityId.id).subscribe(`
