### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#2907]
**Describe the bug**
User unable to open dashboards unless also given read permissions on Widgets Bundle. Providing this permission also means that now the user has access to the Widgets Library Group. I tested if dashboard permission was denied if no read permissions present, it wasn't. User can still access dashboards, there's just no action cell button to Open Dashboard.

**Your Server Environment**

Thingsboard PE 2.4.3 on AWS

**To Reproduce**
1. Go to roles, create a new role and give it following permissions;
Devices( read)
Dashboard(read)
Dashboard Group(read)
Widget Type(read)
2. Create a user and give it this role 
2.5. Note that on the side bar you do not have Widgets Library menu item
3. Go to Dashboard Groups, any group
4. See that you cannot open any dashboards due to lack of action cell button
5. Edit the role and give it Widgets Bundle(read) permission
5.5. Note that this enables Widgets Library menu item
6. Go to dashboards, and now you can open them

**Expected behavior**
The Widgets Library menu item should not be in the side bar. It is strange that opening dashboards is locked behind this menu item.

**Comment by Karabiy** [comment]
It is an okay behavior. It is so because the dashboards requires the widgets to be used, same as the device groups, etc.
