### ISSUE TITLE
Dasbhoard is not loading by customer account

### ISSUE THREAD

**Issue by z4nD4R** [thingsboard/thingsboard#291]
Hello Everyone, 

I hope you missed me :P 
I've noticed another interresting issues. The dashboard is working just fine when `Tenant Admin` is logged. The problem starts when `Customer` is logged in. Then the dasbhoard will never load.

I'm attaching the picture of dashboard which can not be loaded.
![snimka](https://user-images.githubusercontent.com/13903889/30453737-23780a1a-999a-11e7-96c5-80200aa7ed86.png)

Y

**Comment by cethalon** [comment]
Hey!
Just to cover all bases, have you assigned the `device(s)` associated with this dashboard to the `customer`? As far as I can tell with my recent use of Thingsboard, a dashboard can only show information within the scope of the current user (or customer in this case).
Hope this helps!

**Comment by z4nD4R** [comment]
@cethalon,

I can't believe it. So simple? Thank you a lot, it helped now it works like charm :)

Y
