### ISSUE TITLE
[Bug] Unable to send JSON file with JAVA POST 

### ISSUE THREAD

**Issue by naddush** [thingsboard/thingsboard#2912]
**Describe the bug**
So I've been trying to write a code which takes a CSV file from my project and convert it to JSON format, so I can send a POST request to my local thingsboard platfom.
Although, I'm getting this exception error while trying to parse a JSON object : Exception in thread "main" java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to org.json.simple.JSONObject

Here's my code.
 import java.io.File;
import java.util.List;
import java.util.Map;
 
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import java.io.DataInputStream;
import java.io.File;
//import org.json.JSONObject;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.json.simple.JSONArray;

public class CSVtoJSON {
	 public static void main(String[] args) throws Exception {
	        File input = new File("ArgosData_2020_05_24_22_21_59.csv");
	        File output = new File("output.json");
	        String access_token = "rxmqDZF0J1BCUIDm1Faw";
	 
	        CsvSchema csvSchema = CsvSchema.builder().setUseHeader(true).build();
	        CsvMapper csvMapper = new CsvMapper();
	 
	        // Read data from CSV file
	        List<Object> readAll = csvMapper.readerFor(Map.class).with(csvSchema).readValues(input).readAll();
	 
	        ObjectMapper mapper = new ObjectMapper();
	 
	        // Write JSON formated data to output.json file
	        mapper.writerWithDefaultPrettyPrinter().writeValue(output, readAll);
	 
	        // Write JSON formated data to stdout
	        System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(readAll));
	        
	        try {
	            JSONParser parser = new JSONParser();
	            //Use JSONObject for simple JSON and JSONArray for array of JSON.
	            JSONObject data = (JSONObject) parser.parse(
	                    new FileReader(output.getAbsolutePath()));//path to the JSON file.
	            System.out.println(data.toJSONString());

	            String paramValue = "param\\with\\backslash";
	            String yourURLStr = "http://host.com?param=" + java.net.URLEncoder.encode(paramValue, "UTF-8");

	            URL url2 = new URL("http://localhost:8080");
	            HttpsURLConnection conn = (HttpsURLConnection) url2.openConnection();
	            conn.setRequestMethod("POST");
	            conn.setRequestProperty("Content-Type", "application/json");
	            conn.setRequestProperty("Accept", "application/json");
	            conn.setRequestProperty("Authorization", "Bearer" + access_token);

	            conn.setDoOutput(true);
	            OutputStream outStream = conn.getOutputStream();
	            OutputStreamWriter outStreamWriter = new OutputStreamWriter(outStream, "UTF-8");
	            outStreamWriter.write(data.toJSONString());
	            outStreamWriter.flush();
	            outStreamWriter.close();
	            outStream.close();
	            String response = null;

	            System.out.println(conn.getResponseCode());
	            System.out.println(conn.getResponseMessage());

	            DataInputStream input1 = null;
	            input1 = new DataInputStream (conn.getInputStream());
	            while (null != ((response = input1.readLine()))) {
	                System.out.println(response);
	                input1.close ();
	            }
	        } catch (IOException | ParseException e) {
	            e.printStackTrace();
	        }
	    }

**Comment by Bdlikenp** [comment]
Don't think your bug has anything to do with thingsboard but anyway it's because your Json is an array and not an object.
The issue is with your json file.

**Comment by Karabiy** [comment]
> Don't think your bug has anything to do with thingsboard but anyway it's because your Json is an array and not an object.
> The issue is with your json file.

It is so. The array object was sent, not the JSON one, so that the issue occurs. Make sure to send the JSON object.
