### ISSUE TITLE
How to export device configurations?

### ISSUE THREAD

**Issue by ahmedwahdan** [thingsboard/thingsboard#2914]
How to export device configurations?

**Comment by whhhh1500** [comment]
no way ，Export results is "[ ]"

**Comment by zouhr** [comment]
rest api ？

**Comment by whhhh1500** [comment]
You have to upload your own JSON configuration and make it conform to the rules
like





this version  is thingsboard-gateway-2.2.1rc ，I don't know much about python.
It's just a thought. I hope it can help you















在 2020-06-19 21:11:50，"zouhr" <notifications@github.com> 写道：

rest api ？

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
