### ISSUE TITLE
Installation Postgresql Password

### ISSUE THREAD

**Issue by nicholasjconn** [thingsboard/thingsboard#292]
I followed the installation instructions for the Raspberry Pi. When trying to start the ThingsBoard service I receive an error that authentication failed for user "postgres".

I changed the postgres user password during installation (as per the link), but cannot figure out how to let the ThingsBoard code know about the new password. Any suggestions?

**Comment by mp-loki** [comment]
You set the postgres password in thingsboard.yml. At the very bottom of the file you will see the username and password fields. It is postgres/postgres by default.

Just verify that you can login to your postgres instance with psql using your new password, to ensure that it was set correctly.

**Comment by nicholasjconn** [comment]
Thank you! That solved the problem.

**Comment by eykamp** [comment]
I created a pull request to clarify the documentation on this point, as I've missed it as well.
