### ISSUE TITLE
How to make a dashboard accessible from any pc ?

### ISSUE THREAD

**Issue by HendAdell** [thingsboard/thingsboard#2921]
I am working from OS Ubuntu 16.04 and I am trying to make my dashboard public and try to access the link from another pc but it says access forbidden, even though the dashboard and the device is public.
Also I tried the customer feature and assigning the device and dashboard to that customer. After trying to log in from the other pc that has thingsboard installed on it it says authentication failed.
 
Any help ??

**Comment by yefimov-andrey** [comment]
If you press F12 while opening a dashboard, you will be able to determine which resource you are denied access to.

**Comment by HendAdell** [comment]
I pressed F12 and it gave me this error in the console: Failed to load resource: the server responded with a status of 401()

> If you press F12 while opening a dashboard, you will be able to determine which resource you are denied access to.

**Comment by HendAdell** [comment]
How can I make it accessible from another laptop connected to another network?

**Comment by Karabiy** [comment]
For those reasons you need to have a public IP for the host server of yours. So that you can access those using the public IP.

**Comment by HendAdell** [comment]
Okay, sorry for that question bas how can I get the public IP ?

**Comment by Karabiy** [comment]
It depends. You can have an infrastructure being bought from the cloud provider who also provides the public IP, or you can request such an option your local network provider. There are various options on those.
