### ISSUE TITLE
Sending data from ThingsBoard to android application

### ISSUE THREAD

**Issue by MariamMagdy** [thingsboard/thingsboard#2922]
I make 3 devices in dashboard , and i make for each device a function to generate specific values for it.
my question here is how to send the values of the devices from ThingsBoard to an android application on a smartphone ?

**Comment by Bdlikenp** [comment]
you can use the API : https://thingsboard.io/docs/reference/rest-api/

**Comment by aniketmanjare** [comment]
@Bdlikenp  do you have any example or a step to step documentation regarding data from Thingsboard to Android application

**Comment by aniketmanjare** [comment]
@MariamMagdy hey  have you get your data into the android app, would you like to help me with the same

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
