### ISSUE TITLE
saveRuleChain and saveRuleChainMetaData

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#2924]
Hi, 

I am working with the Swagger rule-chain-controller methods, in specific saveRuleChain and saveRuleChainMetaData. Im able to create a rule chain without problem. 

For saveRuleChain, I used the following body request: 
{
    "additionalInfo": null,
    "name": "Test 1",
    "firstRuleNodeId": null,
    "root": false,
    "debugMode": false,
    "configuration": null
 }

And I get the following:

{
  "id": {
    "entityType": "RULE_CHAIN",
    "id": "b6da6080-a989-11ea-b41c-b736d1701c39"
  },
  "createdTime": 1591621953160,
  "additionalInfo": null,
  "tenantId": {
    "entityType": "TENANT",
    "id": "dc92c470-9e80-11ea-80dd-234a1b2b10da"
  },
  "name": "Test 1",
  "firstRuleNodeId": null,
  "root": false,
  "debugMode": false,
  "configuration": null
}

And I am able to see it in the TB UI:

![Screenshot from 2020-06-08 14-13-29](https://user-images.githubusercontent.com/43655840/84034584-6f8c3380-a992-11ea-912d-e8098b06b6b3.png)

Then, I want to create a simple generator of data, which the body of the request (saveRuleChainMetaData) is:

{
    "firstNodeIndex": null,
    "nodes": [
      {
        "additionalInfo": {
          "layoutX": 51,
          "layoutY": 266
        },
        "type": "org.thingsboard.rule.engine.debug.TbMsgGeneratorNode",
        "name": "Test 1 generator",
        "debugMode": false,
        "configuration": {
          "msgCount": 0,
          "periodInSeconds": 300,
          "originatorId": "38952e30-a975-11ea-b41c-b736d1701c39",
          "originatorType": "DEVICE",
          "jsScript": "var msg = { temp: 42, humidity: 77 };\nvar metadata = { data: 40 };\nvar msgType = \"POST_TELEMETRY_REQUEST\";\n\nreturn { msg: msg, metadata: metadata, msgType: msgType };"
        }
      }
    ],
    "connections": null,
    "ruleChainConnections": [
      {
        "fromIndex": 0,
        "targetRuleChainId": {
          "entityType": "RULE_CHAIN",
          "id": "b6da6080-a989-11ea-b41c-b736d1701c39"
        },
        "additionalInfo": {
          "layoutX": 385,
          "layoutY": 153,
          "ruleChainNodeId": "rule-chain-node-3"
        },
        "type": "Success"
      }
    ]
  }

However, I get the following error: 

{
  "status": 400,
  "message": "Incorrect ruleChainId null",
  "errorCode": 31,
  "timestamp": "2020-06-08T13:16:12.578+0000"
}

Any idea why? the ruleChainId is the same as the one created before.

**Comment by fjpa121197** [comment]
Edit: I used this for the saveRuleChainMetaData method 
{
  "connections": null,
  "firstNodeIndex": null,
  "nodes": [
      {
        "additionalInfo": {
          "layoutX": 49,
          "layoutY": 293
        },
        "type": "org.thingsboard.rule.engine.debug.TbMsgGeneratorNode",
        "name": "Test 1 Emulator",
        "debugMode": false,
        "configuration": {
          "msgCount": 0,
          "periodInSeconds": 13,
          "originatorId": "38952e30-a975-11ea-b41c-b736d1701c39",
          "originatorType": "DEVICE",
          "jsScript": "var msg = { temperature: +(Math.random()*5 + 25).toFixed(1)};\nvar metadata = {};\nvar msgType = \"POST_TELEMETRY_REQUEST\";\n\nreturn { msg: msg, metadata: metadata, msgType: msgType };"
        }
      }
    ],
  "ruleChainConnections": [
      {
        "fromIndex": 0,
        "targetRuleChainId": {
          "entityType": "RULE_CHAIN",
          "id": "dcb73c60-9e80-11ea-80dd-234a1b2b10da"
        },
        "additionalInfo": {
          "layoutX": 424,
          "layoutY": 219,
          "ruleChainNodeId": "rule-chain-node-3"
        },
        "type": "Success"
      }
    ],
  "ruleChainId": {
    "id": "4b8f9560-a98f-11ea-b41c-b736d1701c39"
  }
}

And I got the following error:

{
  "timestamp": "2020-06-08T13:59:25.012+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "I/O error while reading input message; nested exception is java.io.IOException: Missing entityType or id!",
  "path": "/api/ruleChain/metadata"
}

But I dont know to what part and where should I put it.

**Comment by Karabiy** [comment]
for the rule chain using the rest api reasons, it is recommended first to have the on UI review on which exact REST API calls being invoked based on different scenarios. For those reasons, you can press the F12 in most user agents and refer to the networking tab.
