### ISSUE TITLE
Active Alarm Filter not working

### ISSUE THREAD

**Issue by robin-log5data** [thingsboard/thingsboard#2925]
Either in a widget or in the alarm info within the device data, when filtering for active alarms, only cleared alarms are shown. Active alarms are only visible when the filter 'any' is used.

![image](https://user-images.githubusercontent.com/53912926/84054133-ee787080-a980-11ea-85dc-4f4af55a17ca.png)

![image](https://user-images.githubusercontent.com/53912926/84054194-051ec780-a981-11ea-96cb-3cc733caf9e3.png)

**Comment by Karabiy** [comment]
please, specify the current TB version of yours

**Comment by PovitruliaV** [comment]
Hi @robin-log5data,
Is this issue still relevant?
