### ISSUE TITLE
[Bug] English translations are incomplete in 3.0.0

### ISSUE THREAD

**Issue by jskillen** [thingsboard/thingsboard#2926]
**Describe the bug**
English translations are incomplete in 3.0.0

**Your Server Environment**
My own setup
Version 3.0.0
Ubuntu Linux

**To Reproduce**
1. Open system settings: https://thingsboard.url/settings/outgoing-mail
2. See sub-menu items are placeholders, not text. E.g. "admin.mail-template-settings" and "white-labeling.white-labeling"

**Expected behavior**
Submenus and titles will be translated into english instead of placeholders.

**Screenshots**
![image](https://user-images.githubusercontent.com/50240540/84074579-a27cfa00-a987-11ea-82f5-0437bbde0d4d.png)

**Comment by Karabiy** [comment]
please, make sure to clear the cache after upgrading

**Comment by jskillen** [comment]
@Karabiy thanks, that does the trick.
