### ISSUE TITLE
[Bug] Links in activation (and other?) emails no longer work in 3.0.0

### ISSUE THREAD

**Issue by jskillen** [thingsboard/thingsboard#2927]
**Describe the bug**
My activation email has an activation link. When the user receives the link it resembles this: x-webdoc://567B6844-C3F9-4149-ABC3-4B6DDC1C8B39/$activationLink.

**Your Server Environment**
My own setup
Version 3.0.0
Ubuntu Linux

**Your Client Environment**
Mac Mail, Outlook

**To Reproduce**
Steps to reproduce the behaviour:
1. Observe in mail template that the activation email contains a link that will be processed - $activationLink
2. Create a new user under a tenant and send the activation to them via email
3. In the user's email client open the activation email
4. Observe that the activation email link is unusable

**Expected behavior**
The $activationLink parameter will be replaced with a functional URL.

**Additional context**
Other parameters have been observed to not be replaced in the mail processor: e.g. $targetEmail

**Comment by vvlladd28** [comment]
Hi @jskillen,
We changed the email template engine in TB 3.0. You need to update your email templates to work, changed $activationLink to $ {activationLink}.

**Comment by allupaku** [comment]
This doenst fix the issue. Even in the display activation link is broken, for tenant admin
