### ISSUE TITLE
Error in New Widget Creation

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#2931]
Hello All,
  I am facing issues while creating new "TimeSeries Widget" in my TB Cloud deployment.
I am using v2.4
Screenshot has been attached.
Kindly support
![Error1](https://user-images.githubusercontent.com/22172258/84229286-d894b800-ab06-11ea-89cf-0c9124a48502.png)

**Comment by yefimov-andrey** [comment]
There is some error in your JS file, all of it needs to be seen in order to determine where the error is.
