### ISSUE TITLE
If the relation table is particularly large, how can I optimize it?

### ISSUE THREAD

**Issue by fyzzy1943** [thingsboard/thingsboard#2940]
My relation is represented by millions of rows of data, the query is very slow, what should I do？

**Comment by Karabiy** [comment]
which exact relations you are referring to? the entities one?

**Comment by fyzzy1943** [comment]
@Karabiy thank you. I config a rule chain to create alarm when the device does not upload data, it will generate an offline alarm, which is created more frequently. It may create several pieces of data in relation at a time. Now, 99% of the relation table should be data from the ALARM group. 
And I use postgresql.

**Comment by Karabiy** [comment]
which exact issue you are facing on those? 
you can have an API call to delete those relations in case if it is required. you can refer to this link regarding TB Rest API: https://thingsboard.io/docs/reference/rest-api/

**Comment by fyzzy1943** [comment]
Thank you very much. When I got the asset relation, it felt a bit slow. I deleted a lot of relations. Now it is much better. Thank you.
