### ISSUE TITLE
Why is the Queue deprecated? IO is time consuming , Akka will have low performance

### ISSUE THREAD

**Issue by zhangxianwei2015** [thingsboard/thingsboard#2946]
https://github.com/thingsboard/thingsboard/blob/accd98676f2e836c3193637ca0d8f038ad466492/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java#L55

**Comment by zhangxianwei2015** [comment]
Put the msg into Queue and create several threads to consume it, will increase throughput.

**Comment by heqiqi** [comment]
@zhangxianwei2015 
Hi,
Do you know why TB removed akka instead of own actor system ? will akka have low performance?

**Comment by zhangxianwei2015** [comment]
@heqiqi 
Hi,
No, I don't thing akka have low performance.
From my case, an actor(single thread) have alots of time consumer tasks(like io), it will have issue. 
I created several threads in the actor then it is ok.

Create several actors to process is another way I think will work.
