### ISSUE TITLE
[Bug] Selecting Español in Profile settings keeps english translations.

### ISSUE THREAD

**Issue by doquen** [thingsboard/thingsboard#2949]
**Description**
As administrator, i go to profile, and select "Español" from drop down menu, but language keeps on english after saving. Other languages seems to work.

**Environment**
* Built from source, branch release-3.0
  * Digtal Ocean Droplet
  * ThingsBoard 3.0 (branch release-3.0)
  * Ubuntu 18.04

**Client Environment**
* OS: Ubuntu 20.04
* Browser Firefox
* Version 77.0.1
**To Reproduce**
1. Go to Profile in administrator account
2. Click on Español from language selector
3. Click Save

**Expected behavior**
Text change to spanish translation

Maybe i broke something when playing with the code? I don't remember touching anything related to translations.

**Comment by vvlladd28** [comment]
Thank you for the report, coming soon we added fix to the master.
