### ISSUE TITLE
Custom parseValueFunction for Led indicator widget

### ISSUE THREAD

**Issue by HassanMojab** [thingsboard/thingsboard#2950]
https://github.com/thingsboard/thingsboard/blob/72c7002f619263d1ef1170eaac8105182248cca8/ui-ngx/src/app/modules/home/components/widget/lib/rpc/led-indicator.component.ts#L323

If the value is 0 for true and 1 for false and we write a parseValueFunction:
`return (data === 0) ? true : false;`
the parseValueFunction can't be reached in case of 0 because of the "if" statement in [this](https://github.com/thingsboard/thingsboard/blob/72c7002f619263d1ef1170eaac8105182248cca8/ui-ngx/src/app/modules/home/components/widget/lib/rpc/led-indicator.component.ts#L323) line and the fact that 0 is assumed false in JS.
Finally, the returned value for both 0 and 1 would be "false".

**Comment by vvlladd28** [comment]
Thank you for the report, coming soon we added fix to the master.
