### ISSUE TITLE
[Bug] Device's renamed but telemetry's deviceName metadata does not update 

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#2952]
**Describe the bug**
If you change the name of a device, the deviceName metadata received in the Root Rule Chain, through http telemetry send, keeps the old name

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard Version 2.5.0
  * OS Name and Version Ubuntu 16

**Your Device**

* Connectivity
 
  * HTTP
 

**To Reproduce**
1. Rename a device.
2. In the Root Rule Chain, the deviceName metadata will keep the old name when a new telemetry arrives.
This is what you get in the incoming telemetry
![imagen](https://user-images.githubusercontent.com/52624907/84642023-3147c480-aefc-11ea-8120-22507b747a3d.png)
But this is the real name of the device
![imagen](https://user-images.githubusercontent.com/52624907/84642134-52101a00-aefc-11ea-9df8-54b2e6c10aaf.png)

**Comment by yefimov-andrey** [comment]
This bug was fixed in 2.5.2.
