### ISSUE TITLE
rule chain import error

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#2953]
**Describe the bug**
error after tb-2.5 rule chain file import to the tb-3.0 project .

**Your Server Environment**

 ThingsBoard Version :2.5
I find some properties has removed in tb-3.0.
tb-2.5 code :
![image](https://user-images.githubusercontent.com/13637039/84630236-3d447e00-af1e-11ea-9c6e-3096702f59d4.png)
tb-3.0 code:
![image](https://user-images.githubusercontent.com/13637039/84630265-4897a980-af1e-11ea-9bee-81a17d30140f.png)

How to be downward compatible？

**Comment by ashvayka** [comment]
Hi @zth390872451 , please check the latest [3.0](https://github.com/thingsboard/thingsboard/blob/v3.0/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rpc/TbSendRpcReplyNodeConfiguration.java) code. Everything is in place. I believe you are using the wrong version. If not - please send a link to file on GitHub.
