### ISSUE TITLE
thinsgboard-dev-3.0 can not opne rule chain

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#2955]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13637039/84646871-4a209c00-af35-11ea-8084-476e7ad34cf3.png)

**Your Server Environment**
  ThingsBoard Version: tb-develop-3.0 
I created a new rule chain but I can not open it .

**Comment by vvlladd28** [comment]
Hi @zth390872451,
Please use release version TB, https://github.com/thingsboard/thingsboard/releases/tag/v3.0.1 or update your version to the last master.
