### ISSUE TITLE
Error while building from source [ui-ngx]

### ISSUE THREAD

**Issue by ahmedwahdan** [thingsboard/thingsboard#2956]
OS: Windows
Release: 3.01

`[INFO] Compiling ngx-translate-messageformat-compiler : es2015 as esm2015
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[INFO] added 1647 packages from 1454 contributors and audited 1656 packages in 586.339s
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR]
[INFO]
[INFO] 58 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO]
[INFO] found 6 vulnerabilities (3 low, 3 high)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[DEBUG] Exit value 0
[INFO]
[INFO] --- frontend-maven-plugin:1.7.5:npm (npm build) @ ui-ngx ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:1.7.5:npm from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:1.7.5, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:1.7.5:npm' with basic configurator -->
[DEBUG]   (f) arguments = run build:prod
[DEBUG]   (f) installDirectory = C:\thingsboard\ui-ngx\target
[DEBUG]   (f) npmInheritsProxyConfigFromMaven = true
[DEBUG]   (f) project = MavenProject: org.thingsboard:ui-ngx:3.0.1 @ C:\thingsboard\ui-ngx\pom.xml
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@e7137c1
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6ad5923a
[DEBUG]   (f) skipTests = true
[DEBUG]   (f) testFailureIgnore = false
[DEBUG]   (f) workingDirectory = C:\thingsboard\ui-ngx
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:1.7.5:npm {execution: npm build}
[DEBUG] -- end configuration --
[INFO] Running 'npm run build:prod' in C:\thingsboard\ui-ngx
[DEBUG] Executing command line [C:\thingsboard\ui-ngx\target\node\node.exe, C:\thingsboard\ui-ngx\target\node\node_modules\npm\bin\npm-cli.js, run, build:prod]
[INFO]
[INFO] > thingsboard@3.0.1 build:prod C:\thingsboard\ui-ngx
[INFO] > ng build --prod --vendor-chunk
[INFO]
[ERROR] Compiling @angular/animations : module as esm5
[ERROR] Compiling @angular/core : module as esm5
[ERROR] Compiling @angular/animations/browser : module as esm5
[ERROR] Compiling @angular/animations/browser/testing : module as esm5
[ERROR] Compiling @angular/common : module as esm5
[ERROR] Compiling @angular/cdk/clipboard : module as esm5
[ERROR] Compiling @angular/cdk/platform : module as esm5
[ERROR] Compiling @angular/cdk/bidi : module as esm5
[ERROR] Compiling @angular/cdk/collections : module as esm5
[ERROR] Compiling @angular/cdk/scrolling : module as esm5
[ERROR] Compiling @angular/cdk/drag-drop : module as esm5
[ERROR] Compiling @angular/common/http : module as esm5
[ERROR] Compiling @angular/common/http/testing : module as esm5
[ERROR] Compiling @angular/flex-layout/core : module as esm5
[ERROR] Compiling @angular/platform-browser : module as esm5
[ERROR] Compiling @angular/flex-layout/extended : module as esm5
[ERROR] Compiling @angular/flex-layout/flex : module as esm5
[ERROR] Compiling @angular/flex-layout/grid : module as esm5
[ERROR] Compiling @angular/flex-layout : module as esm5
[ERROR] Compiling @angular/cdk/keycodes : module as esm5
[ERROR] Compiling @angular/cdk/observers : module as esm5
[ERROR] Compiling @angular/cdk/a11y : module as esm5
[ERROR] Compiling @angular/platform-browser/animations : module as esm5
[ERROR] Compiling @angular/forms : module as esm5
[ERROR] Compiling @angular/material/core : module as esm5
[ERROR] Compiling @angular/cdk/portal : module as esm5
[ERROR] Compiling @angular/cdk/overlay : module as esm5
[ERROR] Compiling @angular/material/form-field : module as esm5
[ERROR] Compiling @angular/material/autocomplete : module as esm5
[ERROR] Compiling @angular/material/badge : module as esm5
[ERROR] Compiling @angular/cdk/layout : module as esm5
[ERROR] Compiling @angular/material/bottom-sheet : module as esm5
[ERROR] Compiling @angular/material/button-toggle : module as esm5
[ERROR] Compiling @angular/material/card : module as esm5
[ERROR] Compiling @angular/material/checkbox : module as esm5
[ERROR] Compiling @angular/material/chips : module as esm5
[ERROR] Compiling @angular/cdk/accordion : module as esm5
[ERROR] Compiling @angular/material/expansion : module as esm5
[ERROR] Compiling @angular/material/grid-list : module as esm5
[ERROR] Compiling @angular/material/icon : module as esm5
[ERROR] Compiling @angular/material/icon/testing : module as esm5
[ERROR] Compiling @angular/material/divider : module as esm5
[ERROR] Compiling @angular/material/list : module as esm5
[ERROR] Compiling @angular/material/menu : module as esm5
[ERROR] Compiling @angular/material/progress-bar : module as esm5
[ERROR] Compiling @angular/material/progress-spinner : module as esm5
[ERROR] Compiling @angular/material/radio : module as esm5
[ERROR] Compiling @angular/material/sidenav : module as esm5
[ERROR] Compiling @angular/material/slide-toggle : module as esm5
[ERROR] Compiling @angular/material/slider : module as esm5
[ERROR] Compiling @angular/material/button : module as esm5
[ERROR] Compiling @angular/material/snack-bar : module as esm5
[ERROR] Compiling @angular/cdk/stepper : module as esm5
[ERROR] Compiling @angular/material/stepper : module as esm5
[ERROR] Compiling @angular/cdk/table : module as esm5
[ERROR] Compiling @angular/material/select : module as esm5
[ERROR] Compiling @angular/material/tooltip : module as esm5
[ERROR] Compiling @angular/material/paginator : module as esm5
[ERROR] Compiling @angular/material/sort : module as esm5
[ERROR] Compiling @angular/material/table : module as esm5
[ERROR] Compiling @angular/material/tabs : module as esm5
[ERROR] Compiling @angular/material/toolbar : module as esm5
[ERROR] Compiling @angular/cdk/tree : module as esm5
[ERROR] Compiling @angular/material/tree : module as esm5
[ERROR] Compiling @angular/core/testing : module as esm5
[ERROR] Compiling @angular/platform-browser-dynamic : module as esm5
[ERROR] Compiling @angular/platform-browser/testing : module as esm5
[ERROR] Compiling @angular/compiler/testing : module as esm5
[ERROR] Compiling @angular/platform-browser-dynamic/testing : module as esm5
[ERROR] Compiling @angular/common/testing : module as esm5
[ERROR] Compiling @angular/router : module as esm5
[ERROR] Compiling @angular/router/testing : module as esm5
[ERROR] Compiling @auth0/angular-jwt : module as esm5
[ERROR] Compiling @flowjs/ngx-flow : module as esm5
[ERROR] Compiling @angular/material/dialog : module as esm5
[ERROR] Compiling @angular/cdk/text-field : module as esm5
[ERROR] Compiling @angular/material/input : module as esm5
[ERROR] Compiling @angular/material/datepicker : module as esm5
[ERROR] Compiling @mat-datetimepicker/core : module as esm5
[ERROR] Compiling @ngrx/store : module as esm5
[ERROR] Compiling @ngrx/effects : module as esm5
[ERROR] Compiling @ngrx/effects/testing : module as esm5
[ERROR] Compiling @ngrx/store/testing : module as esm5
[ERROR] Compiling @ngrx/store-devtools : module as esm5
[ERROR] Compiling @ngx-share/core : module as esm5
[ERROR] Compiling @ngx-translate/core : module as esm5
[ERROR] Compiling @ngx-translate/http-loader : module as esm5
[ERROR] Compiling angular-gridster2 : module as esm5
[ERROR] Compiling angular2-hotkeys : module as esm5
[ERROR] Compiling ngx-window-token : module as esm5
[ERROR] Compiling ngx-clipboard : module as esm5
[ERROR] Compiling ngx-color-picker : module as esm5
[ERROR] Compiling ngx-daterangepicker-material : module as esm5
[ERROR] Compiling ngx-hm-carousel : module as esm5
[ERROR] Compiling ngx-translate-messageformat-compiler : module as esm5
[ERROR]
[ERROR] Compiling ngx-flowchart : module as esm5`

**Comment by ahmedwahdan** [comment]
![image](https://user-images.githubusercontent.com/5406736/84654930-55150580-af10-11ea-94c5-7e18d3dc96ad.png)

**Comment by ahmedwahdan** [comment]
![image](https://user-images.githubusercontent.com/5406736/84656813-922ec700-af13-11ea-86f3-af7d4662cc2b.png)

**Comment by jaichaturvedi88** [comment]
@ahmedwahdan Were you able to fix this issue? We are also getting this error.

**Comment by ravipras8** [comment]
i am also facing the same issue. getting error like below after these compilation errors. i do tried by adding prettier to packages and build which worked but i am looking is there any other way?

![image](https://user-images.githubusercontent.com/13759816/89150368-07199700-d57c-11ea-84e5-808ffbf32f09.png)

**Comment by waseemullah157** [comment]
This is issue because of version of typescript. I was able to resolve this issue by updating to the latest version.
Run this command to update the version to latest stable version.
`npm install -g typescript`
