### ISSUE TITLE
No description of TextPageLink and TextPageData 

### ISSUE THREAD

**Issue by Ankeshkumarsingh** [thingsboard/thingsboard#2959]
I am searching in repo for TextPageLink and TextPageData , its not there instead PageLink and PageData is found.

I am trying to access through restClient in springboot but it throwing error since no proper description is there.

Please help me or update repo with latest code.
Thanks in advance

**Comment by Ankeshkumarsingh** [comment]
Can you please update the rest artifactory with latest codes?

**Comment by Sascha1993** [comment]
Hei,
same issue here. Using REST-calls with this data structures always results in "400 Bad Request"-Exception. Hoping someone may help soon.
Best regards

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
