### ISSUE TITLE
[Bug] Attribute update subscription not work

### ISSUE THREAD

**Issue by train860** [thingsboard/thingsboard#2960]
mosquitto_pub -d -h "demo.thingsboard.io" -t "v1/devices/me/attributes" -u "DOQCcVodU7wQkSmNhv7A" -m "{\"temperature\":24}"

mosquitto_sub -h "demo.thingsboard.io" -t "v1/devices/me/attributes" -u "DOQCcVodU7wQkSmNhv7A" -v

test the attribute subscription functionality, but it doesn't appear to be working.

**Comment by vvlladd28** [comment]
Hi @train860,
Which version of ThingsBoard are you using?

**Comment by train860** [comment]
> Hi @train860,
> Which version of ThingsBoard are you using?

the version on demo.thingsboard.io.

I have also tried self host a docker vesion on ubuntu,used image thingsboard/tb-postgres:lastest ,
subscription also not work，but publish is ok。

**Comment by train860** [comment]
I finally found that only shared attributes can be subscribe，use rule chain can fix it。
