### ISSUE TITLE
Drop Down Widget with multiple selection

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#2965]
Hello All, 
  I am working on Drop Down Widget in Thingsboard.

It is required for selection of devices or can say entities.Data of selected entity will get displayed.
I have created simple Drop Down Widget.

Now I am looking for multiple selection in Drop Down widget so that I can select multiple devices.

It can be used for smooth navigation and data display between devices.

**Comment by Karabiy** [comment]
the widget data depends on the current alias being selected as the data source. does the widget of yours refers to those?

**Comment by nmahale10** [comment]
Yes it refer to that only.But I want to display the data after selecting one of the device (say Alias has two devices "Device1" and "Device2").So in this case if I select Device1 it show Device1 data only

**Comment by Karabiy** [comment]
You need to create the custom widget which will reveal the data based on the actions taken and have the already defined alias with those device data. 
you can refer to this link regarding those: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

**Comment by RajeshSavanth** [comment]
> Hello All, I am working on Drop Down Widget in Thingsboard.
> 
> It is required for selection of devices or can say entities.Data of selected entity will get displayed. I have created simple Drop Down Widget.
> 
> Now I am looking for multiple selection in Drop Down widget so that I can select multiple devices.
> 
> It can be used for smooth navigation and data display between devices.

Hi Can u share the code u have written for dropDown widget. Thanks
