### ISSUE TITLE
[Question] How to configure to avoid these errors (429, 500)?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2967]
**Component**

 * Rule Engine
 * Generic

**Description**
Now, I am using a live demo (cloud.thingsboard.io) for testing.
And have the following questions:

1. When I use "get attribute" and "save attribute" at the same time on the widget to update (by clicking one button) the attribute for more than 60 devices, the update will often fail due to error 429 (too many request). How can I avoid it?
![螢幕快照 2020-06-17 上午9 12 13](https://user-images.githubusercontent.com/63713926/84843678-22d3e700-b07b-11ea-8247-f9e7e0ed7e6d.png)

How can I change [thingsboard.yml](https://thingsboard.io/docs/user-guide/api-limits/) so that 60 or more devices can update/upload new data in seconds without error 429?

2. Sometimes when server (nodejs) uploads data (to thingsboard), it will be blocked to update in a short time due to error code 500 (Script is blacklisted due to maximum error count 3!), how to avoid or increase "maximum error count"?
![螢幕快照 2020-06-17 上午9 14 51](https://user-images.githubusercontent.com/63713926/84843711-397a3e00-b07b-11ea-8a91-d7444cef6d40.png)

In addition, can the contents of thingsboard.yml be modified on aws (can the live demo also be changed, do not know how to change it)?

**Environment**

 * OS:  (Live Demo / AWS);
 * ThingsBoard: v3.0.1
 * Browser: not related

**Comment by ecmap** [comment]
Please help, especially error code 500 (blacklist)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
