### ISSUE TITLE
[Question] Inactivity timing issues

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2968]
**Component**

 * Rule Engine
 * Generic

**Description**
Now, I am using a live demo (cloud.thingsboard.io) for testing - [Create Alarm when the Device is offline](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/).
And have the following questions:

1. As shown in the figure below, when the device is uploaded to the thingsboard for the first time, even if the data contains "inactivityTimeout", the inactivity event will not be calculated based on the inactivityTimeout.
![螢幕快照 2020-06-17 上午10 04 58](https://user-images.githubusercontent.com/63713926/84846966-92010980-b082-11ea-8d93-5c4682a50038.png)
<img width="579" alt="螢幕快照 2020-06-17 上午10 08 03" src="https://user-images.githubusercontent.com/63713926/84846973-97f6ea80-b082-11ea-84c6-3e25b6f0ce6c.png">
<img width="584" alt="螢幕快照 2020-06-17 上午10 08 25" src="https://user-images.githubusercontent.com/63713926/84846990-a2b17f80-b082-11ea-84fe-65d1186086ef.png">

2. Even if the device contains "inactivityTimeout", inactivity events will appear errors of tens of seconds or minutes (faster or slower)

How can I solve the above problem?

Where can I change the [defaultStateCheckInterval](https://github.com/thingsboard/thingsboard/issues/1334) in the live demo (cloud.thinsgboard.io)?

Using AWS, can I change the defaultStateCheckInterval (where/in which file)?

**Environment**

 * OS:  (Live Demo / AWS)
 * ThingsBoard: v3.0.1
 * Browser: not related

**Comment by ecmap** [comment]
Please help to fix it

**Comment by Karabiy** [comment]
you can refer to the thingsboard.yml of the current setup of yours. those is located in the /etc/thingsboard/conf/ folder, so that you can configure those

**Comment by eRJx** [comment]
Inactive event is not working on TB Cloud version. After turning off the device, no inactive event is generated even after 60 minutes.
However, as soon as the device is turned on, an activity event and an inactivity event are generated together.  If I change the  device server attribute inactivityTimeout manually the Inactive event is generated, depending on the new value I set. The device is connected via MQTT.

Environment

- ThingsBoard: Cloud v. 3.3.3

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
