### ISSUE TITLE
installation error on centos 6

### ISSUE THREAD

**Issue by mekesim** [thingsboard/thingsboard#297]
I have installed PostgreSQL on Centos 6, and try to insall thingsboard, get below error, could you help to guide how to deal with it? Thanks.

[root@nnnn ~]# sudo /usr/share/thingsboard/bin/install/install.sh

>  ===================================================
>  :: ThingsBoard ::       (v1.3.0)
>  ===================================================
> 
> Starting ThingsBoard Installation...
> Installing DataBase schema...
> Installing SQL DataBase schema...
> Unexpected error during ThingsBoard installation!
> org.postgresql.util.PSQLException: ERROR: syntax error at or near "NOT"
>   Position: 632
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
>         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
>         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
>         at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
>         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
>         at org.thingsboard.server.service.install.SqlDatabaseSchemaService.createDatabaseSchema(SqlDatabaseSchemaService.java:61)
>         at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:109)
>         at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:41)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
> Exception in thread "main" java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
> Caused by: org.thingsboard.server.install.ThingsboardInstallException: Unexpected error during ThingsBoard installation!
>         at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:131)
>         at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:41)
>         ... 8 more
> Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "NOT"
>   Position: 632
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
>         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
>         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
>         at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
>         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
>         at org.thingsboard.server.service.install.SqlDatabaseSchemaService.createDatabaseSchema(SqlDatabaseSchemaService.java:61)
>         at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:109)
>         ... 9 more
> ThingsBoard installation failed!

**Comment by mp-loki** [comment]
Hi @mekesim 

Which ThingsBoard version are you using?

Can you please look for **schema.sql** in your /usr/share/thingsboard/data/sql/ (or smth like this) and attach it here? 
It seems to me that the schema.sql file has an error which we no longer have in the latest version.

**Comment by ashvayka** [comment]
@mekesim If there will be no updates to this thread I will close it today.

**Comment by ChSM56** [comment]
Hi @mekesim, @ ikulikov

Sorry to be posting here as I have never been here.

I have run into the same issue today.

My System is Cento 7 and worked fine with HSQLDB. I tried to populate a Postgres DB and switch but failed. So, I started all over again and ran into the same problem of failure to populate Demo data.
![pgsql config](https://user-images.githubusercontent.com/29800826/32778874-9cbcf524-c961-11e7-91b0-dd3757d2e365.PNG)

The step I am at:
                            /usr/share/thingsboard/bin/install/install.sh    --loadDemo

My Installation Guide is : 
https://thingsboard.io/docs/user-guide/install/linux/


My SQL Files are attached with extension .txt (renamed for Upload to accept)

[schema.sql.txt](https://github.com/thingsboard/thingsboard/files/1470642/schema.sql.txt)

[system-data.sql.txt](https://github.com/thingsboard/thingsboard/files/1470643/system-data.sql.txt)

![capture](https://user-images.githubusercontent.com/29800826/32778728-03d72f96-c961-11e7-94e1-bbb67998a404.PNG)

I am looking to use Postgresql as the data store.

I have configured on a Windows 10 desktop the access to Postgresql thats running on the same system used for Thingsboard installation. the system has 4GB RAM and 225GB disk storage with Dual core processor configuration.
![pgsql config](https://user-images.githubusercontent.com/29800826/32779056-56575da8-c962-11e7-8ddf-86cde3c63eed.PNG)

Thank you for your help

**Comment by ChSM56** [comment]
Hello ashvayka, ikulikov

Sorry to extend the post with the Successful Instal status with HSQLDb.

This issue I see is with Postgresql Database demo data population.

Thanks & Regards

![image](https://user-images.githubusercontent.com/29800826/32779356-6e1938e8-c963-11e7-845f-3d8177d86741.png)

**Comment by Radhe92** [comment]
Dear all , 
please guide what is the issue . 
though the following setting done by me.
export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Xms256M -Xmx256M"

root@debian:/home/radhe# /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5FF4C683C3.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:262)
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:212)
	at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:38)
	at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:91)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:254)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:123)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:131)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

**Comment by mp-loki** [comment]
This error means that the database schema was created and demo data has already been populated in one of the previous runs. 
Try running `service thingsboard start`

**Comment by Radhe92** [comment]
Now , i am facing new issue , as i have flash the code and trying to burn it again , the below error is coming for any code i am trying to burn.

Radhes-MacBook-Air:blinky radheshyamyadav$ make BOARD=nrf52_pca10040 CONF_FILE=prj_cs7ns2.conf
  CHK     include/generated/generated_dts_board.conf
  Using /Users/radheshyamyadav/zephyr as source for kernel
  GEN     ./Makefile
  CHK     include/generated/version.h
  CHK     include/generated/generated_dts_board.h
  CHK     include/generated/syscall_list.h
  CHK     include/generated/syscall_dispatch.c
  CHK     misc/generated/configs.c
  CHK     include/generated/offsets.h
make[3]: `isr_tables.o' is up to date.
