### ISSUE TITLE
Issue with custom action button after 3.0.1 update

### ISSUE THREAD

**Issue by RobertasP** [thingsboard/thingsboard#2970]
Hello, i am using custom action button in widget. Script:
var $injector = widgetContext.$scope.$injector;
$injector.get('assetService').getAsset (entityID.id).then(function(asset){
if(asset.Name == 'apartment') { 
openDashboardState ('apartment');
} else {
openDashboardState('building_view');
}
});
function openDashboardState(stateId) {
var params = {
entityId: entityId,
entityName: entityName
};
Widgetcontext.statecontroller.openState(stateId, params, false);
Before update it's worked fine, opened dashboard states depending on clicked asset, now this button do nothing.

**Comment by vvlladd28** [comment]
Hi @RobertasP, 
In the new version of TB 3.0, we update the Angular version, and some features need to be updated to work correctly on the new version. Examples are available in Custom action (with HTML template).
To make your code work, you need to change:
`$injector.get('assetService').getAsset (entityID.id).then(` => `$injector.get(widgetContext.servicesMap.get('assetService')).getAsset(entityId.id).subscribe(`
`if(asset.Name == 'apartment') {` => `if(asset.name == 'apartment') {`

**Comment by RobertasP** [comment]
Thank you, that helped.
