### ISSUE TITLE
[Question] Custom Menu - dashboard needs public?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#2971]
**Component**

 * UI

**Description**
Custom menu: As shown in the [video/tutorial](https://www.youtube.com/watch?time_continue=242&v=VSNZWl1NjWU&feature=emb_title), we can design a side navigation bar (menu) or even link directly to the dashboard, but I don’t know if the dashboard needs to be made public?
<img width="787" alt="螢幕快照 2020-06-17 下午3 17 25" src="https://user-images.githubusercontent.com/63713926/84869462-a5c36480-b0b0-11ea-9091-b9ca6ccdfde8.png">
![螢幕快照 2020-06-17 下午3 24 34](https://user-images.githubusercontent.com/63713926/84869469-a825be80-b0b0-11ea-84dc-5ccfd35755c6.png)
Can I do this if the dashboard is not public?

**Environment**

 * OS:  (Live Demo / AWS)
 * ThingsBoard: v3.0.1
 * Browser: not related

**Comment by ecmap** [comment]
Can someone share the experience?

**Comment by PovitruliaV** [comment]
Hi @ecmap,
You can add a dashboard to the custom menu using the id of that dashboard, not a link to it as in the example
![image](https://user-images.githubusercontent.com/98046079/184154969-c8c8e928-a23c-4e0d-a6b3-e0921bdabaeb.png)
In that case, you will not need to make the dashboard public, but if you want your customizers to access it, you will have to share the dashboard with them.
If this does not work for you and the only option is to link to the dashboard, then you need to make it public.
Regards,
