### ISSUE TITLE
[Question] How to maintains control value 

### ISSUE THREAD

**Issue by engfei** [thingsboard/thingsboard#2976]
Hi, I'm currently doing MQTT RPC testing with eWon Gateway. I facing below issue and appreciate if anyone could give me some hints

I created 2 control widget in Thingsboard Dashboard (Analog Knob control and Digital Switch control). The issue now is the control value will falls back to default value when I refresh the dashboard.

For topic "**v1/devices/me/telemetry**", i publish data in below format and is working good
json$ = '{'
json$ = json$ + '"Temperature001":' + '"' + STR$  (GETIO "Analog1") + '"'
json$ = json$ + '}'
MQTT "PUBLISH",  TopicToPublishOn$ ,  json$ , 0,0

For topic "**v1/devices/me/rpc/response/"**", i publish data in same format but it doesnt work 
TopicToResponse$ = "v1/devices/me/rpc/response/"
$IDinputJson$ = MsgTopic$
$StartBracketPos% = 27
$EndBracketPos% = LEN $IDinputJson$
RequestID$ = $IDinputJson$($StartBracketPos% TO $EndBracketPos%)

Response$ = '{'
Response$ = Response$ + '"getValue":' + '"' + AI1$ + '"'
Response$ = Response$ + '}' 
PRINT Response$
TopicToResponsewID$ = TopicToResponse$ + RequestID$
MQTT "PUBLISH",  TopicToResponsewID$ ,  Response$ , 0,0

appreciate if someone could give some hints

Thank you

**Comment by IoTThinks** [comment]
Just response to v1/devices/me/rpc/response/<request-id>
The payload is just a number. Such as 12.34
