### ISSUE TITLE
Mapping of Device data from cassandra and postgres

### ISSUE THREAD

**Issue by SORC3r3r** [thingsboard/thingsboard#2981]
**Component**

 * Generic

**Description**
We are using Thingsboard with postgres and cassandra.
Currently we try to do some data analysis by using the data from the databases.
We would like to map devices telemetry data that is saved in cassandra to the attributes of the same device which is saved in postgres. The `entity_id` of the cassandra entries of that device is the id which I can get from the Thingsboard UI by copying it via the button in the devices details. The id of the device in postgres seems to be some other id.

How can I map the values from cassandra and postgres?

**Environment**

 * OS:  TB Docker Container running in k8s
 * ThingsBoard: 2.4.3
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
Apologize for not answering
Please reopen the issue if still relevant
