### ISSUE TITLE
[Bug]v3.0.1  rest api cannot get the devices info，responce is [ ]

### ISSUE THREAD

**Issue by zouhr** [thingsboard/thingsboard#2983]

**Comment by Karabiy** [comment]
which exact request you are using for those reasons?

**Comment by bcleuing** [comment]
I also encountered similar problems (response is an empty array) when getting tenant assets and devices with REST APIs, and I managed to solve it by setting the request parameter `page` to 0 (initially I thought it starts from 1).

```
{pageSize: 100, page: 0}
```

Hope this helps.

**Comment by Karabiy** [comment]
It is so because the count starts from the 0 for those.
