### ISSUE TITLE
Same alarm created two times

### ISSUE THREAD

**Issue by selvamaniraj** [thingsboard/thingsboard#2986]
Duplicate alarms are created with the same startTs and endTs. 
When cleared, only one of the two gets cleared and other 
one does not get cleared
![alarm_duplication](https://user-images.githubusercontent.com/20810762/85193595-c4f80700-b2e7-11ea-94b2-cb424891d570.png)
# Duplicate alert created
![alarm_duplication_1](https://user-images.githubusercontent.com/20810762/85193597-c6c1ca80-b2e7-11ea-9d05-4e22f0fe9ff2.png)
# One of the two duplicate alarms did not get cleared
![alarm_duplication_2](https://user-images.githubusercontent.com/20810762/85193598-c75a6100-b2e7-11ea-8258-72efa8f2248a.png)

**Comment by yefimov-andrey** [comment]
How does your alarm rule chain look like?

**Comment by jianchunzhu** [comment]
I have the same issue.
thingsboard version: 3.2.2 release.
The device profile is configured with root rule chain, and in the root rule chain it will go to an alarm chain after save the timeseries. Then in the alarm chain first check the device type, next to check the value to create or clear the alarm.

**Comment by Ibrahim-elkholy** [comment]
I have the same issue, it happens when there is two messages for the same originator the time between them less than 1 second

**Comment by mykhailokornieiev** [comment]
It is important to understand that the function of creating alarms is atomic, so if there are two possible sources of creating an alarm , both will be created and it will not be possible to cancel the creation of at least one. Please check if you are not receiving two messages in rule chain that should create alarms at the same time
Also, please clarify how exactly you create alarms: both through the “device profile” and “create alarm” rule node, or only with “create alarm“ rule node?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
