### ISSUE TITLE
openDashboardState Not Working In Thingsboard 3.0.1

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#2987]
Hello !
I successfully used the following code on Thingsboard 2.4.3 widget's custom action.
When I migrated to Thingsboard 3.0.1 the code is not working anymore !
Please help me and give me the working code for Thingsboard 3.0.1 !
Or give me some samples for the new version of Thingsboard because now
my platform is not working !
Could somebody translate this code for Thingsboard 3.0.1 ?
Thank You !

Here is the code :
var $injector = widgetContext.$scope.$injector;
$injector.get('deviceService').getDevice(entityId.id).then(function(device) {
 if(device.type == 'TEMP SENSOR'.trim()) {
  openDashboardState('TEMP SENSOR Details'.trim());
 }
 else if(device.type == 'HUM SENSOR'.trim()) {
  openDashboardState('HUM SENSOR Details'.trim());
 }
 else if(device.type == 'CO2 SENSOR'.trim()) {
  openDashboardState( 'CO2 SENSOR Details'.trim());
 }
 else if(device.type == 'WATER METER SENSOR'.trim()) {
  openDashboardState( 'WATER METER SENSOR Details'.trim()); 
 } 
 else if(device.type == 'ENERGY METER SENSOR'.trim()) {
  openDashboardState( 'ENERGY METER SENSOR Details'.trim()); 
 }
else if(device.type == 'COOLER FREEZER SENSOR'.trim()) {
  openDashboardState( 'COOLER FREEZER SENSOR Details'.trim()); 
 } 
});

function openDashboardState(stateId) {
 var params = {
 entityId: entityId,
 entityName: entityName
 };

 widgetContext.stateController.openState(stateId, params, false);
}

**Environment**
 * OS:  Win7 x64
 * ThingsBoard: 3.0.1
 * Browser: Google Chrome

**Comment by vvlladd28** [comment]
Hi @RobertasP,
In the new version of TB 3.0, we update the Angular version, and some features need to be updated to work correctly on the new version. Examples are available in Custom action (with HTML template).
To make your code work, you need to change:
`$injector.get('deviceService').getDevice(entityId.id).then(`=> `$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(`
