### ISSUE TITLE
Device list doesn't update automatically

### ISSUE THREAD

**Issue by hmirzaee2** [thingsboard/thingsboard#2988]
Hello
When I load a dashboard with a dynamic entity alias (using Device Type, relation query, ...) device list doesn't update.
For example if I add some new devices with specified device type, list of devices in running dashboard will not change.
How can I overcome to this problem?

**Comment by yefimov-andrey** [comment]
What do you mean by "list will not change"? The fact that it won't change at all or only that it won't change without refreshing the page?

**Comment by Karabiy** [comment]
You can apply the filtering and add those to the separate entity group, in case of the ThingsBoard PE, which will also allow you to have more dynamic processing.

**Comment by hmirzaee2** [comment]
> What do you mean by "list will not change"? The fact that it won't change at all or only that it won't change without refreshing the page?

I mean device list updates every time I refresh the dashboard but I need device list be updated without that,
I used self.ctx.aliasController.updateAliases() but it refreshed dashboard.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
