### ISSUE TITLE
how support protobuf about mqtt in ce version [Feature Request]

### ISSUE THREAD

**Issue by hailianglone** [thingsboard/thingsboard#2991]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Karabiy** [comment]
please, specify whether you have already proceeded with the next guide regarding on how to contribute: https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/

**Comment by ashvayka** [comment]
Since ThingsBoard 3.2, the platform supports custom topics and Protobuf payload type. This is configurable via [device profiles](https://thingsboard.io/docs/user-guide/device-profiles/#mqtt-device-payload).
