### ISSUE TITLE
Send the same data repeatedly

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#2997]
tb version 2.5 problem

My action: add a device disconnect event and send data to Kafka.

Test results: it was found that Kafka received two disconnected messages at the same time.

Check the code and find: it will be sent twice here。I think error occur here:
```
DefaultTransportService.java : 
    process(sessionInfo, getSessionEventMsg(TransportProtos.SessionEvent.CLOSED), null);
    sessions.remove(uuid);          
   sessionMD.getListener().onRemoteSessionCloseCommand(TransportProtos.SessionCloseNotificationProto.getDefaultInstance());
```
1、My problem: I wonder why I need to call the sendtodeviceactor() function twice?
2、My solution ：I annotated the call in the doDisconnect () function of the MqttTransportHandler class. transportService.process () method, it was found that it was only sent once after testing. Will this cause other problems?

**Comment by zth390872451** [comment]
no one answer?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
