### ISSUE TITLE
Multiple EntityID in handleWidgetAction

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3001]
Can I send multiple "EnityID" in following function.(May be in Array or String Format)
   self.ctx.actionsApi.handleWidgetAction(event, descriptor, entityId, entityName, null, entityLabel);
Can I access same from other widget.

Thanks

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
