### ISSUE TITLE
Thingsboard Read Only Attributes

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3002]
Hello !
Please tell me how to make the device's server attributes to be read only for the client.
Can I choose which one attribute to be read-only ?
Tenant must be able to read and to write the server's attributes.
Thank You !

**Environment**
 * OS:  Win 7 x64
 * ThingsBoard: 2.5.2
 * Browser: Chrome

**Comment by Karabiy** [comment]
hello
you can use the Role Based Access Control functionality of the ThingsBoard Professinal Edition for those. 
you can refer to this link regarding the RBAC: https://thingsboard.io/docs/user-guide/rbac/

**Comment by lmax25** [comment]
Thank You !
