### ISSUE TITLE
[Question] building image web-ui from source issue  

### ISSUE THREAD

**Issue by Hamza-Slama** [thingsboard/thingsboard#3005]
**UI**

**Description**
i'm trying to run thingsboard with microservices apprcoh and i have problem when building docker image from source of web-ui 
when using ```gcr.io/cloud-builders/mvn:3.5.0-jdk-8``` this is the output : 
```

root@webui-fdc676f44-kz6sz:/tmp# dpkg -c tb-web-ui.deb |grep 'tb-web-ui$'
-r-x------ thingsboard/thingsboard 6626 2020-06-22 09:17 ./usr/share/tb-web-ui/init/tb-web-ui
lrw-r--r-- root/root                     0 2020-06-22 09:17 ./etc/init.d/tb-web-ui -> /usr/share/tb-web-ui/init/tb-web-ui
```

 
and when using  `cloud9 ( amazon linux 2)` this is the output : 

```
root@tb-web-ui-759d76bff6-9bqjz:/tmp# dpkg -c tb-web-ui.deb |grep 'tb-web-ui$'
-r-x------ thingsboard/thingsboard 47078623 2020-06-25 09:11 ./usr/share/tb-web-ui/bin/tb-web-ui
-r-x------ thingsboard/thingsboard     6626 2020-06-25 09:11 ./usr/share/tb-web-ui/init/tb-web-ui
lrw-r--r-- root/root                      0 2020-06-25 09:11 ./etc/init.d/tb-web-ui -> /usr/share/tb-web-ui/init/tb-web-ui
```

it seems like this package doesn't be generated : 

`-r-x------ thingsboard/thingsboard 47078623 2020-06-25 09:11 ./usr/share/tb-web-ui/bin/tb-web-ui`

how can i fix this error ? any suggestion ? 
**Environment**
 * ThingsBoard: V2.4.3

**Comment by Ultrazombie** [comment]
Hello,
I think this issue is not relevant,
Please re-open the ticket if this is relevant for the new ThingsBoard version.
