### ISSUE TITLE
[Bug] License client does not intialize - Thingsboard 2.4.3 GCP Marketplace VM instance will not start Thingsboard - 

### ISSUE THREAD

**Issue by dsilva-vd** [thingsboard/thingsboard#3008]
**Describe the bug**
The Thingsboard service will not start on my VM instance. The last part of the console shows the following:
Jun 25 19:02:11 thingsboard-pe-1-vm systemd[1]: thingsboard.service: Main process exited, code=exited, status=255/n/a
Jun 25 19:02:11 thingsboard-pe-1-vm systemd[1]: thingsboard.service: Failed with result 'exit-code'.
Jun 25 19:04:52 thingsboard-pe-1-vm systemd[1]: Starting Certbot...
Jun 25 19:04:53 thingsboard-pe-1-vm systemd[1]: Started Certbot.
Jun 25 19:29:52 thingsboard-pe-1-vm systemd[1]: Starting Daily apt download activities...
Jun 25 19:29:53 thingsboard-pe-1-vm systemd[1]: Started Daily apt download activities.
Jun 25 19:37:34 thingsboard-pe-1-vm google-accounts: INFO Adding user devops_admin to the Google sudoers group.
[3800709.009851] google_accounts_daemon[18361]: Adding user devops_admin to group google-sudoers
Jun 25 19:37:34 thingsboard-pe-1-vm google_accounts_daemon[18361]: Adding user devops_admin to group google-sudoers
Jun 25 19:37:44 thingsboard-pe-1-vm google-accounts: INFO Adding user devops_admin to the Google sudoers group.
[3800719.034600] google_accounts_daemon[18361]: Adding user devops_admin to group google-sudoers
Jun 25 19:37:44 thingsboard-pe-1-vm google_accounts_daemon[18361]: Adding user devops_admin to group google-sudoers
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[1]: Created slice User Slice of devops_admin.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[1]: Starting User Manager for UID 1002...
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[1]: Started Session 7631 of user devops_admin.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on REST API socket for snapd user session agent.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on GnuPG network certificate management daemon.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on GnuPG cryptographic agent and passphrase cache.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Reached target Timers.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Reached target Paths.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Reached target Sockets.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Reached target Basic System.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[1]: Started User Manager for UID 1002.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Reached target Default.
Jun 25 19:37:45 thingsboard-pe-1-vm systemd[394]: Startup finished in 51ms.
Jun 25 19:39:04 thingsboard-pe-1-vm systemd[1]: Started thingsboard.
Jun 25 19:39:08 thingsboard-pe-1-vm thingsboard.jar[581]:  ===================================================
Jun 25 19:39:08 thingsboard-pe-1-vm thingsboard.jar[581]:  :: ThingsBoard Professional Edition ::       (v2.4.3PE)
Jun 25 19:39:08 thingsboard-pe-1-vm thingsboard.jar[581]:  ===================================================
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]: Initializing ThingsBoard License Client, Release Date [2020-01-08]
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]: Obtained instance data from file.
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]: instanceId: [XXXXXXXXXXXXXXXXXX]
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]: planData: {
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   "maxassets" : {
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "value" : 10,
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "description" : "Assets amount limitation "
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   },
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   "maxdevices" : {
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "value" : 10,
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "description" : "Devices amount limitation"
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   },
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   "whitelabeling" : {
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "value" : false,
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:     "description" : "White-labeling feature"
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]:   }
Jun 25 19:39:29 thingsboard-pe-1-vm thingsboard.jar[581]: }
Jun 25 19:39:30 thingsboard-pe-1-vm thingsboard.jar[581]: #033[1;31m[ERROR] License Error: INVALID_LICENSE_CHECK_SECRET(107) - Invalid secret request sequence number!
Jun 25 19:39:30 thingsboard-pe-1-vm thingsboard.jar[581]: #033[0;39m #033[1;31m[ERROR] Failed to initialize ThingsBoard License Client!
Jun 25 19:39:30 thingsboard-pe-1-vm thingsboard.jar[581]: #033[0;39m #033[1;31m[ERROR] Failed to init license client
Jun 25 19:39:30 thingsboard-pe-1-vm thingsboard.jar[581]: #033[0;39m Terminating application due to critical License Error INVALID_LICENSE_CHECK_SECRET(107), exit code [-1]...
Jun 25 19:39:30 thingsboard-pe-1-vm systemd[1]: thingsboard.service: Main process exited, code=exited, status=255/n/a
Jun 25 19:39:30 thingsboard-pe-1-vm systemd[1]: thingsboard.service: Failed with result 'exit-code'.

**Your Server Environment**

* own setup
  * Single VM on GCP
  * ThingsBoard Version - 2.4.3
  * OS Name and Version - Ubuntu 18.04.3 LTS

**To Reproduce**
1. I tried sudo service Thingsboard stop (restart and start)
2. The service starts running but then fails due to the license client erorr

**Expected behavior**
I didn't expect the license client to stop working. I had made no changes to the system and expected it to be up and running.

**Additional context**
I copied the server console log and can attach it here. Is it okay to have the instance name in the file or should I delete that from the log first before posting?

**Comment by yefimov-andrey** [comment]
You need to deactivate your instance on license portal, delete the license file which is located at  /usr/share/thingsboard/bin/instance-license.data and restart ThingsBoard.

**Comment by dsilva-vd** [comment]
Thank you @yefimov-andrey that fixed my problem.

**Comment by mensch92** [comment]
Hi, I have the same problems. But I am using thingsboard in microservice docker-compose cluster setup. I'm using Version 2.4.3PE. Attached, you can see a part of my thingsboard.log:

```
...
2020-12-16 06:03:38,619 [main] INFO  o.t.license.client.TbLicenseClient - Initializing ThingsBoard License Client, Release Date [2020-01-08]
2020-12-16 06:05:48,357 [main] ERROR o.t.license.client.TbLicenseClient - License Error: CONNECTION_ERROR(400) - Failed to connect to ThingsBoard License Server!
2020-12-16 06:05:48,358 [main] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
2020-12-16 06:05:48,362 [main] ERROR o.t.s.d.s.BasicSubscriptionService - Failed to init license client
org.thingsboard.license.shared.exception.LicenseException: Failed to connect to ThingsBoard License Server!
        at org.thingsboard.license.client.TbLicenseClient.toLicenseException(TbLicenseClient.java:390)
        at org.thingsboard.license.client.TbLicenseClient.activateInstance(TbLicenseClient.java:316)
        at org.thingsboard.license.client.TbLicenseClient.readInstanceDataOrActivate(TbLicenseClient.java:301)
        at org.thingsboard.license.client.TbLicenseClient.init(TbLicenseClient.java:156)
        at org.thingsboard.server.dao.subscription.BasicSubscriptionService.init(BasicSubscriptionService.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
...
```
At the Thingsboard License Portal the two Instances from the "Problem Server" do not come up. 
I am purchasing two Thingsboard PE Startup Subscriptions with each two instances.
How can I solve this issue?

**Comment by e1ke** [comment]
If you are struggling to find /usr/share/thingsboard/bin/instance-license.data, please check, if you are also as stu*id as me an overread your env-variable 
TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
in your docker-compose.yaml. This line of course changes the place of your instance data. So delete it with 
rm -f /data/license.data
and then...voila :)

P.S.
I came across multiple Errors like 
Terminating application due to critical License Error ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104)
License Error: INVALID_LICENSE_CHECK_SECRET(107) - Invalid secret request sequence number!
and
License Error: INSTANCE_NOT_FOUND(105) - Instance not found!

hope this helps
