### ISSUE TITLE
INFO on Add a new widget action to go back to previous dashboard state #1966

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3014]
Hello again !
I really need a new widget action to go back to previous dashboard state.

I have read the post from :
https://github.com/thingsboard/thingsboard/pull/2849

But I didn't understand what to do to get the new widget action to work...

Can you be more specific, please ?
Thank You !

Environment
OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

**Comment by Ultrazombie** [comment]
Closed, as not active.
