### ISSUE TITLE
What Map services are used in Map Widget ?

### ISSUE THREAD

**Issue by BaerSy** [thingsboard/thingsboard#3015]
**Component**

 * Generic - map widget

**Description**
What Map services are used in Map Widget? Google Map? Can we use other in other countries?

**Comment by Delapouite** [comment]
Here is the list of available map providers:
```
export * from './tencent-map';
export * from './google-map';
export * from './here-map';
export * from './image-map';
export * from './openstreet-map';
```

https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/index.ts
