### ISSUE TITLE
[Bug] Custom Action Not working anymore

### ISSUE THREAD

**Issue by Killtutor** [thingsboard/thingsboard#3016]
**Describe the bug**
previous of the migration to thingsboard 3.0.1 my widget custom actions was working just fine, but now does nothing

**Your Server Environment**

* own setup
  * cloud infraestructure, no docker
  * ThingsBoard Version 3.0.1
  * Ubuntu 16.04 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 16.04
* Browser Firefox
* Version 77.0.1

**To Reproduce**
1. Go to imagemap with a custom action to redirect for one or another dashboard status by device type
2. Click on the polygon
3. Nothing happen, no redirection, no new dashboard state.

**Expected behavior**
the polygon should route to a new dash board state by device type.

**Screenshots**
![githubTBBug](https://user-images.githubusercontent.com/20267814/85961121-2f5b1800-b976-11ea-9863-377611004e12.png)

**Additional context**
prior the update version 2.5 was used.

**Comment by vvlladd28** [comment]
Hi @Killtutor ,
In the new version of TB 3.0, we update the Angular version, and some features need to be updated to work correctly on the new version. Examples are available in Custom action (with HTML template).
To make your code work, you need to change:
`$injector.get('deviceService').getDevice(entityId.id).then(`
to
`$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(`
