### ISSUE TITLE
Get Telemetry for Specific Alarm

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3018]
Hello !

Please tell me how to define a custom action in Alarm Widget On Row Click.

This new action must get all the telemetry data starting with Alarm Created Time
for the device in the clicked row and to display all the data into another dasboard state
in a new widget.

Thank You !

Environment

OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
