### ISSUE TITLE
Dont change the UI to Spanish[Bug] 

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/thingsboard#3019]
**Describe the bug**
When select spanish in profile, dont work

* own setup
  * local
  * ThingsBoard Version: 3.0.2
  * OS Name and Version: Debian 10

**Comment by vvlladd28** [comment]
Thank you for the report, coming soon we added fix #2957 to the master.

**Comment by vvlladd28** [comment]
Fix added to master
