### ISSUE TITLE
Monitoring cassandra metrics

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3020]
Hi, 

I'm trying to monitor cassandra database when multiple devices are sending telemetry data to TB. Im using Applications Manager to monitor the cassandra database. Im able to connect to it correctly, however, when I start sending data, the performance metrics (writes per second) do not show/reflect in the monitor. 

I already filed an issue for the application manager support team to look at, and they told me that " latest Cassandra is not exposing these Attributes via MBeans ". Is there any configuration part that I should change for this?

On the other hand, is there any open source software that is able to monitor the cassandra database in real time that you suggest?

Thanks in advance

**Comment by Karabiy** [comment]
there are various versions on those. 
it might be better, in this case, to contact the Cassandra support, in case if they can propose any kind of an embedded solution or the most clear.
