### ISSUE TITLE
Custom widgets to change dashboard state

### ISSUE THREAD

**Issue by GauravChoube** [thingsboard/thingsboard#3023]
Hi everyone,
I'm using thingsBoard demo version 3.0.1.
I want to switch dashboard state by using custom widgets.
So I used custom widgets method and formed the one click button widget that was refered from some others post where those also doing same things.but still whenever click the widget not happening anything.
Please help me anyone and possible share widget or code that atleast work.
Thanks

**Comment by Karabiy** [comment]
you can refer to the TB source code on how those can be developed properly

**Comment by GauravChoube** [comment]
Hi Karabiy,
i already follow process as show in getting started guide for custom widget but still help me out.
can you suggest some code that help me for my problem

**Comment by Karabiy** [comment]
I recommend you to refer to the TB source code for the best practices investigation reasons.
