### ISSUE TITLE
[Question] How do I get attributes when creating an inactivity alarm?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#3025]
**Component**

 * Rule Engine

**Description**
Suppose I want to display the temperature value in the alarm when the inactivity alarm is created.

However, as shown in the figure below, Inactivity data and Metadata do not include the temperature attribute.
<img width="384" alt="螢幕快照 2020-06-29 下午5 02 47" src="https://user-images.githubusercontent.com/63713926/86092777-91d02780-bae0-11ea-8f9e-814ded844f5a.png">
<img width="445" alt="螢幕快照 2020-06-29 下午5 02 55" src="https://user-images.githubusercontent.com/63713926/86092833-a6acbb00-bae0-11ea-83af-1e8a920325e2.png">
<img width="438" alt="螢幕快照 2020-06-29 下午5 02 34" src="https://user-images.githubusercontent.com/63713926/86092851-ad3b3280-bae0-11ea-957f-12afaae8e3b1.png">

How can I get the value of this attribute (details.temperature)?
![t png](https://user-images.githubusercontent.com/63713926/86092934-cb089780-bae0-11ea-988f-fae53434e54d.jpg)

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use the _Originator Attributes_ _(Enrichment)_ rule node to add the latest temperature value to the metadata.

**Comment by Karabiy** [comment]
The details can be found in the body of the message in the details object.

**Comment by ecmap** [comment]
> Hello,
> You can use the _Originator Attributes_ _(Enrichment)_ rule node to add the latest temperature value to the metadata.

thanks
