### ISSUE TITLE
[Question] $injector in custom widgets

### ISSUE THREAD

**Issue by ChristofferHolmesland** [thingsboard/thingsboard#3026]
Latest values custom widget

**Description**
Is there any documentation about the widgetContext.$scope.$injector object? I couldn't find anything here https://thingsboard.io/docs/user-guide/contribution/widgets-development/.

**Environment**
ThingsBoard: v2.4

**Comment by ashaforost** [comment]
Closing this issue as inactive. If you have a similar question, please create new GH issue.
