### ISSUE TITLE
[Bug] when claiming device without SecretKey, thingsboard return 500

### ISSUE THREAD

**Issue by cychiu8** [thingsboard/thingsboard#3031]
**Describe the bug**
* As a customer, when claiming device without body, the response will be 500

**Your Server Environment**

* demo.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS:  win10
* Browser: chrome(83.0.4103.116), Postman v7.27.1

**Your Device**

* Connectivity
  * HTTP

**To Reproduce**
1. login as a customer and get the token of the customer
2. post `https://demo.thingsboard.io/api/customer/device/$DeviceName/claim` without SecretKey
3. See error 500

* if I use the body with `{"secretKey": null}`, the result would be "Failure".

**Expected behavior**
* As the description of the user guide, the secretkey should be an optional. 
* 👉 https://thingsboard.io/docs/user-guide/claiming-devices/#device-claiming-api-request 
* expected response
```
{
    "device": {
        "id": {
            "entityType": "DEVICE",
            "id": XXX
        },
        "createdTime": 1589445609810,
        "additionalInfo": {
            "description": "Demo device that is used in sample applications for ESP8266"
        },
        "tenantId": {
            "entityType": "TENANT",
            "id": XXX
        },
        "customerId": {
            "entityType": "CUSTOMER",
            "id": "XXX
        },
        "name": "ESP8266_Demo_Device",
        "type": "default",
        "label": null
    },
    "response": "SUCCESS"
}
```

**Screenshots**
* the result of without request body
![image](https://user-images.githubusercontent.com/43577255/86200958-b388e780-bb90-11ea-9bb2-469ef14c9463.png)
* the result of request body with null value
![image](https://user-images.githubusercontent.com/43577255/86201812-18ddd800-bb93-11ea-8624-37dce65f4bf1.png)

**Additional context**

* The request body in the DeviceController [[ref1]](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/controller/DeviceController.java#L463) is not required
* but using it directly [[ref2]](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/controller/DeviceController.java#L475)

**Comment by Ultrazombie** [comment]
Closed due to inactive
