### ISSUE TITLE
[Question]/[Bug] Access token must have letters or can be numerical?

### ISSUE THREAD

**Issue by dsvagelj** [thingsboard/thingsboard#3033]
**Component**

 * UI

**Description**
I cant set device access token to be only numbers(see image below). Is this intended behavior or a bug?
![image](https://user-images.githubusercontent.com/8733880/86241085-9bba5f00-bba2-11ea-8153-01e9090457ba.png)

If I add a letter at the start I can save new access token.
![image](https://user-images.githubusercontent.com/8733880/86241527-577b8e80-bba3-11ea-9883-82ed429c9671.png)

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.0.1PE
 * Browser: Microsoft Edge, 83.0.478.56

**Comment by vvlladd28** [comment]
HI @dsvagelj, 
Thank you for the report, coming soon we added fix #2972  to the master.
