### ISSUE TITLE
[Bug] RemoteIntegrationManagerService fails on failFast field

### ISSUE THREAD

**Issue by takeurpills** [thingsboard/thingsboard#3035]
When setting up a remote integration of TCP type and with the TEXT handler a "failFast":false parameter is added to the handlerConfiguration object. When starting the TCP/UDP remote integration service the service fails (please see the error below). I found a workaround by deleting this "failFast" part in the public.integrations table for this exact integration entry.
The main issue is though, that every time the Integration has to be modified/updated/saved from the UI, the "failFast" part is automatically added (updated in the DB) so it needs to be manually deleted again.

`2020-06-29 17:34:41,589 [grpc-default-executor-1] ERROR o.t.i.s.RemoteIntegrationManagerService - Failed to initialize platform integration! java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "failFast" (class org.thingsboard.integration.tcpip.configs.TextHandlerConfiguration), not marked as ignorable (4 known properties: "messageSeparator", "maxFrameLength", "stripDelimiter", "charsetName"]) at [Source: (String)"{"port":10560,"soBacklogOption":128,"soRcvBuf":64,"soSndBuf":64,"soKeepaliveOption":false,"tcpNoDelay":true,"handlerConfiguration":{"handlerType":"TEXT","maxFrameLength":128,"failFast":false,"stripDelimiter":true,"messageSeparator":"SYSTEM_LINE_SEPARATOR"}}"; line: 1, column: 191] (through reference chain: org.thingsboard.integration.tcpip.tcp.TcpConfigurationParameters["handlerConfiguration"]->org.thingsboard.integration.tcpip.configs.TextHandlerConfiguration["failFast"])`

**Your Server Environment**
* On-premise
  * Ubuntu server 20.04
  * ThingsBoard PE 3.0.1
  * ThingsBoard TCP/UDP Integration 3.0.1

**Comment by Karabiy** [comment]
Does those refer to the integration which was created before the upgrade for the 2.5+ version on the new created one?

**Comment by jskillen** [comment]
I have the same configuration and have experienced the same issue.

**Comment by takeurpills** [comment]
@Karabiy, this is a fresh 3.0.1 installation.

**Comment by Karabiy** [comment]
have you tried to restart the tb-tcp-udp-integration?

**Comment by takeurpills** [comment]
Yes, I have. Tried restarting TBPE and the Integration service as well. I have also tried deleting the whole integration and setting it up from scratch - same result. I believe, that the failFast parameter belongs to the BINARY handler and shouldn't be added when I create a TEXT handler TCP Integration.

**Comment by vvlladd28** [comment]
Hi @takeurpills, 
Thank you for your report. The fix will be added to the new release of TB PE.

**Comment by anhdv1979** [comment]
@takeurpills : Could you pls help me check why TB-TCP integration always get error (in TB PE show success in lifecycle but I could not get telemetry from device. Note: i do as TB sample). Many thanks
[tb-tcp-udp-integration.2.log](https://github.com/thingsboard/thingsboard/files/5044498/tb-tcp-udp-integration.2.log)

**Comment by Karabiy** [comment]
@anhdv1979 please, delete those file and create it once more. also, provide us with the information regarding those file size, so that we can have more details on issue
