### ISSUE TITLE
[Question] Does the REST API allow client-side ID generation?

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#3037]
**Component**
 * Generic

**Description**
We are occasionally generating IDs on the client-side (because of offline-functionality).
This used to work perfectly well, until we updated from 2.4.1 to 2.5.2. Now we always get a 404 when trying a request like this:
```
POST /api/asset
{
   "id":{
      "entityType":"ASSET",
      "id":"81ce2668-bbd3-11ea-b3de-0242ac130004"
   },
   "name":"test",
   "type":"test",
   "label":"test"
}
```

Is this intended behavior? If yes, is there a reason for the change?

**Environment**
 * ThingsBoard: 2.4.1 and 2.5.2

**Comment by Sascha1993** [comment]
Hei everyone,
I have the similiar issue with the dashboard-Uuid, assets and devices. It's not possible to get the Uuid for dashboards via Websocket-UI(apart from making it public and extract from URL). On the other side there is the opportunity to fetch all dashboards and access the id with this undocumented TextPageLink Data structure. But using TextPageLink always results in "400 Bad Request". Sample code snippet below:

TextPageLink link = new TextPageLink(3);
client.getTenantDevices("thermometer", link).getData().forEach(x -> System.out.println(x.getName()));
2.5.0

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
