### ISSUE TITLE
[Question] COAP response missing 

### ISSUE THREAD

**Issue by goc333** [thingsboard/thingsboard#3039]
COAP
 * Generic

**Description**
I've install thingsboard following instructions https://thingsboard.io/docs/user-guide/install/ubuntu/ on digital ocean.
When i send coap post from powershell data is received and i can see telemetry but there is no response from server, also when i try coap get there is no response. I tried same command on free trial thingsboard online and it worked ok.
Are there some additional settings that has to be configured?

**Environment**
 * ThingsBoard: v3.0.1

**Comment by Karabiy** [comment]
make sure that you have enabled the coap in the thingsboard.yml and there are no firewall restrictions between you and the server host

**Comment by goc333** [comment]
coap is enabled in thingsboard.yml, firewall is disabled on digital ocean server and on pc, I aslo tried to send data using sara N200 module and there is no response from server.  

![image](https://user-images.githubusercontent.com/17862006/86598168-069dd880-bf9d-11ea-8535-de045a6204fb.png)

when I listen port with tcpdump I can see that response is sent but never received on any of my devices

**Comment by Karabiy** [comment]
please make sure that the coap server is not running. you can have those using the 
netstat -tulpn
to check whether the port is listening or using the 
nmap -p $PORT $HOST
so that you can also scan those, whether the port is opened/filtered or closed.

**Comment by goc333** [comment]
this is response for netstat
![Capture](https://user-images.githubusercontent.com/17862006/86815518-0a0b8f80-c083-11ea-847d-b3629631272c.PNG)

and this is for nmap
![Capture2](https://user-images.githubusercontent.com/17862006/86815616-24de0400-c083-11ea-8612-a18c5ab55bfb.PNG)

**Comment by Karabiy** [comment]
can you provide with the thinsgboard.yml

**Comment by goc333** [comment]
here it is 

[thingsboard.zip](https://github.com/thingsboard/thingsboard/files/4890333/thingsboard.zip)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
