### ISSUE TITLE
[Question] Thingsboard architecture: Durable message queues with RabbitMQ

### ISSUE THREAD

**Issue by vandeveldemaarten** [thingsboard/thingsboard#3042]
**Component**

 * Installation
 * Generic

**Description**
For acquiring a well performing setup we used messaged queues (with RabbitMQ) as part of our Thingsboard architecture.

(From [documentation](https://thingsboard.io/docs/reference/#:~:text=by%20ThingsBoard%20Core.-,Message%20Queues%20are%20awesome!,Bus%20and%20Google%20Pub%2FSub.&text=Thus%2C%20all%20messages%20for%20the,pushed%20to%20the%20same%20partition.), see chapter: "Message Queues are awesome!)
_"ThingsBoard supports multiple message queue implementations: Kafka, RabbitMQ, AWS SQS, Azure Service Bus and Google Pub/Sub. ... . Using durable and scalable queues allow ThingsBoard to implement back-pressure and load balancing. Back-pressure is extremely important in case of peak loads.
We provide “abstraction layer” over specific queue implementations and maintain two main concepts: topic and topic partition. One topic may have configurable number of partitions. Since most of the queue implementations does not support partitions, we use topic + “.” + partition pattern."_

Following this our current setup uses Thingsboard and RabbitMQ. Upon restart or unexpected shutdown of our RabbitMQ (msg queues) it looses all queues and messages within. This is due to the queues not being persisted. RabbitMQ does have a standard feature which makes the queues durable, unfortunately this is not enabled by Thingsboard.

**Question**
Is there a way to enable the RabbitMQ durable queue feature through Thingsboard configuration (thingsboard.yml)?
This way messages with QoS of "1" or "2" are persisted in the queue.

**Environment**
 * OS: Linux/amd64
 * ThingsBoard: Thingsboard v3.0.1 (docker: thingsboard\tb-postgres:latest)
 * Browser: Chrome version 83.0.4103.116
 * Docker: [docker-compose.txt](https://github.com/thingsboard/thingsboard/files/4863811/docker-compose.txt)

**Additional Content**
* Feature in RabbitMQ management
![image](https://user-images.githubusercontent.com/60184800/86353607-cde1c480-bc67-11ea-9a29-8869f55dea07.png)

* RabbitMQ documentation, see chapter "Durability"
[RabbitMQ queues](https://www.rabbitmq.com/queues.html)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
