### ISSUE TITLE
I'm having problems connecting to Thingsboards' demo broker.

### ISSUE THREAD

**Issue by Protolucas** [thingsboard/thingsboard#3043]
`#!/usr/bin/env python
#Library import
import paho.mqtt.client as paho			#MQTT library
import time						#time library
import random as rnd					#random library

#Get_value function definitions
def on_publish(client, userdata, result):		#Callback function
	print("data published to thingsboard \n")
	pass

def get_temperature():					#Generate a random temp
	return '%.2f'%rnd.uniform(-50,50) + "Celsius"
	
def get_humidity():                               	#Generate a random humidity
	return '%.2f'%rnd.uniform(0,100) + "%"
	
def get_payload():					#Generate payload
	payload = '{"Temperature":"'
	payload += get_temperature()
	payload +='", "Humidity":"'
	payload += get_humidity()
	payload += '"}'
	return payload
	
#MQTT client definition
ACCESS_TOKEN1='ylvI8SmDWE0MJfA2Mtn1'			#AccessToken of Virtual Environment Station 1 in TB
ACCESS_TOKEN2='eYpOZi2wn8epSgpVHJ8N'			#AccessToken of Virtual Environment Station 2 in TB
print("1")

broker='demo.thingsboard.io'				#Host name
port=1883						#Data listening port
print("2")

client1= paho.Client("control1")			#Create client 1 object
client1.on_publish = on_publish			#assign function to callback of client1
client1.username_pw_set(ACCESS_TOKEN1)		#assign to client1 the acess token of Virtual ENvironment Station 1 in ThingsBoard
try:
	print("connecting")
	client1.connect(broker,port,keepalive=10)		#Establish connection using the func connect from the class client
	print("CONNECTED")
except:
	print("connection failed")
	exit(1)

client2= paho.Client("control1")			#Create client 1 object
client2.on_publish = on_publish			#assign function to callback of client1
client2.username_pw_set(ACCESS_TOKEN2)		#assign to client1 the acess token of Virtual ENvironment Station 1 in ThingsBoard
client2.connect(broker,port,keepalive=10)		#Establish connection using the func connect from the class client
print("4")

#Sending data
print("5")

while True:
	print("6")
	payload1 = get_payload()
	payload2 = get_payload()
	ret = client1.publish("v1/devices/me/telemetry",payload1)
	ret = client2.publish("v1/devices/me/telemetry",payload2)
	print("Please check LATEST TELEMETRY field of your devices")
	print(payload1);
	print(payload2);
	time.sleep(4)`

And my terminal window : 
![image](https://user-images.githubusercontent.com/67751671/86380947-034cd900-bc8d-11ea-9878-b09b8444e00a.png)

**Comment by Karabiy** [comment]
please, specify whether you are using the demo.thingsboard.io 
you also may refer to this link regarding the sample of a client code which is an okay: https://thingsboard.io/docs/user-guide/access-token/
