### ISSUE TITLE
[Feature Request] Add Cluster deployment instructions for Kubernetes

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3049]
Hi guys

At the moment the scripts/instructions only cover Kubernetes on Minikube

it would be great if you can add support for full Kubernetes deployment using kubectl 

This will allow admins to choose their favorite host of Kubernetes cluster. 

I like to use DigitalOcean for example.

Thanks!

**Comment by t0mmyz7** [comment]
Is this a solid approach here? To convert the docker-compose to K8s file?
https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

My concern would be upgrading the nodes..mmm

**Comment by t0mmyz7** [comment]
Well I guess the minicube instructions can be easily adapted to full k8s cluster by just login with kubectl to your cluster previous.

**Comment by t0mmyz7** [comment]
this was done, thanks!

https://github.com/thingsboard/thingsboard-pe-k8s

**Comment by xiddjp** [comment]
This service type is monolith. I mean we may encounter performance issues, and how can we handle session issues with multiple pods, just like websocket connection?

> this was done, thanks!
> 
> https://github.com/thingsboard/thingsboard-pe-k8s
