### ISSUE TITLE
Can't assign id to device when registering via API

### ISSUE THREAD

**Issue by danielfree** [thingsboard/thingsboard#305]
Thingsboard 1.3.0

When using /api/device POST api to save a new device, we found that if we assign the id via 
`id: {id: xxxx} ` then the response would be like 

" Could not read document: Missing entityType or id!; nested exception is java.io.IOException: Missing entityType or id! " 

If we drop this field then everything is ok, however we'd like to assign device ids at manufacturing stage instead of getting randomly generated uuids.

**Comment by volodymyr-babak** [comment]
hi, according to code you have to provide enityType. In your case I suppose it's DEVICE:

**Comment by danielfree** [comment]
@volodymyr-babak Hi, I've tried with id: {entityType:'DEVICE', id:xxxx}  still giving me the same error.

**Comment by danielfree** [comment]
It turns out to be the issue of generated uuid. I've used version 4 uuid from https://www.uuidgenerator.net/version4  however the api seems only to accept version 1 uuid.

Is this a bug?  @volodymyr-babak  I've seen several usages of UUID.randomUUID() (which is version 4) in the project but in JpaAbstractDao: 
https://github.com/thingsboard/thingsboard/blob/c5d47bbe02a9dbba993e22c7affb0cc9e396b6e6/dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java#L60 
it's time-based uuid which is version 1.

**Comment by volodymyr-babak** [comment]
I suppose you are correct, version 1 must be used. If in some places 4 version is used, then it could be a bug, or in that places version 1 is not mandatory

**Comment by ashvayka** [comment]
@danielfree all our entities require time based UUIDs compatible with Cassandra time uuid

**Comment by priyankakrvino** [comment]
"exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "message": "Could not read document: Missing entityType or id!; nested exception is java.io.IOException: Missing entityType or id!"


the above error is occur in swagger ui??
is there any id mismatching error??

**Comment by priyankakrvino** [comment]
i used version 1 itself but the same issue raised...

**Comment by sujataapatil** [comment]
I am facing same issue while trying through REST client, anyone got it fixed?
