### ISSUE TITLE
sending http request through widget

### ISSUE THREAD

**Issue by DavidR-fr** [thingsboard/thingsboard#3054]
Hi Guys

I am using the device admin table to create device on thingsboard. 
I would like to take the device name and forward this to a 3rd party application using an http POST embedded in the java section of the widget code.
To do that i have created an XMLHttpRequest in my code.

When i run the code, nothing happen. I don't think this request is executed.

Has someone ever succeed to make similar action ? or any better way to make this ?

Thanks a lot
David

**Comment by ChristofferHolmesland** [comment]
`
const xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (xhttp.readyState != 4) return;
    console.log(xhttp.status);
    console.log(xhttp.responseText);
}

xhttp.open(method, url);
xhttp.send();
`

**Comment by DavidR-fr** [comment]
Hi

Thanks this is exactly what I am doing, but it as no effect. I don’t think the code is executed or the request not forwarded either. Here the code I have in the java section:

    var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
if (this.readyState == 4 && this.status == 200) {
alert(this.responseText);
}
};
xhttp.open("POST", url, false);
xhttp.setRequestHeader("Content-type", "application/json");
xhttp.setRequestHeader("accept", "application/json");
xhttp.setRequestHeader("authorization", "Basic am9uLnNtaXRoOkNDS3FqMkk3QkdmSw==");
xhttp.timeout=10000;
xhttp.send("{ \"devEUI\": \"11aa11bb22cc33dd\", \"appEUI\": \"aa00bb12ce22dd33\", \"appKey\": \"aa00bb11cc22dd33aa00bb11cc22dd33\", \"deviceType\": \"G3_PULSE_V1\", \"utilityId\": 2}");
}

And the one the html section

    <button mat-button mat-raised-button color=« primary
    type="submit" onclick="UserAction()">Swagger</button> »

I don’t really understand what I am doing wrong

Best Regards
David

**Comment by itrich** [comment]
I have exactly the same problem. 

```
var xhr = new XMLHttpRequest();
var weatherData;
xhr.open("GET", url);
xhr.onreadystatechange = function() {
        console.log("onreadystatechange: " + xhr.readyState);
        if (xhr.readyState !== XMLHttpRequest.DONE) {
            return;
        }
        console.log("status: " + xhr.status)
        if (xhr.status === 0 || (xhr.status >= 200 && xhr.status < 400)) {
            console.log("response: " + xhr.responseType);
            //return;
        }
        console.log("Response:" + xhr.response);
        // Turning the JSON data into an object 
        weatherData = JSON.parse(xhr.response);
        console.log("Weather: " + weatherData);
        // No error so parse and display in HTML
        displayWeather(weatherData);
};
xhr.send();
```

gives me an empty response and status code 0.

**Comment by Maxwh21** [comment]
Did you guys ever figure this out?
