### ISSUE TITLE
How to use assetService in map widget?

### ISSUE THREAD

**Issue by hmirzaee2** [thingsboard/thingsboard#3059]
Hello
I want to create a dynamic marker tooltip in map widget (image map) , For example map shows some building assets and when user click a marker, tooltip shows related assets on tooltip,
So I used this code in tooltip function in  image map advanced settings, but it only works on dashboard edit mode and show empty tooltip in dashboard view mode, Do you have any idea?

let id = data.$datasource.entityId.toString();
let $injector = window.ctx.$scope.$injector;  //window.ctx is widget self.ctx I assigned in widget init method,
let assetService = $injector.get(window.ctx.servicesMap.get(
    'assetService'));

assetService.findByQuery(query).toPromise( (result)=> {
    result.forEach(function(item) {
        mytooltip+= '<br>' + item.name;
    });
    data.mytooltip= mytooltip;
});
return '${mytooltip}';

**Comment by mgogh** [comment]
Hi,

I would like to do something quite similar but I encounter some issues.
Did you succeed in doing this stuff ?

Regards,

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
