### ISSUE TITLE
the values are not shown in dashboard

### ISSUE THREAD

**Issue by anhnv194** [thingsboard/thingsboard#3064]
Dear,
We are currently using thingsboard CE platform, database: postgreSQL and cassandra. Let me take an example:
Solar inverter devices are being managed for our customer on thingboards CE . By clicking on the hierarchy widget in the dashboard, it will display the required device information. But we have an issue on new timeseries table on dashboard with solar2 device that some values are not shown in table. 
Please see attached file as below and help me this issue.
Many thanks

 
![lastest telemetry_solar 1](https://user-images.githubusercontent.com/67814445/86892178-1ac31080-c12a-11ea-9fd6-3e09ca64f321.jpg)
![lastest telemetry_solar 2](https://user-images.githubusercontent.com/67814445/86892181-1bf43d80-c12a-11ea-937d-3be39f0d16d3.jpg)
![solar 1_hierarchy](https://user-images.githubusercontent.com/67814445/86892184-1c8cd400-c12a-11ea-8b21-e9ff91b940c6.jpg)
![solar 2_hierarchy](https://user-images.githubusercontent.com/67814445/86892187-1d256a80-c12a-11ea-8902-1b095ffd5223.jpg)
![solar inverter_rule chains](https://user-images.githubusercontent.com/67814445/86892188-1dbe0100-c12a-11ea-8405-1a9dec88bc81.jpg)

**Comment by Karabiy** [comment]
do you have the telemetry split? so that, you have the the "ratio" being sent separately?
