### ISSUE TITLE
Keys group formation of device.

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3066]
Hello All,

  I have one device say "TestDevice".
  and keys :- test1,test2,test3,test4.

Can I group this - Group 1 :-test1,test2
                             Group 2 :- test3,test4

and use this Group names in REST API call to get latest telemetry.So I will just send "Group 1" instead of test1,test22 in REST API call to get data of "test1" and" test2".

Thanks

**Comment by Ultrazombie** [comment]
Closed due to inactive
