### ISSUE TITLE
DynamoDB as NoSQL database

### ISSUE THREAD

**Issue by frhack** [thingsboard/thingsboard#307]
Could be possible to implement the ability to use  DynamoDB as NoSql database backend ?

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
Hi @frhack . Please see our contribution guide https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/ and review the dao package in the code. At the moment we support sql and cassandra, dynamodb support is welcome to open-source version.
