### ISSUE TITLE
Custom Widget

### ISSUE THREAD

**Issue by vijayshukla80** [thingsboard/thingsboard#3070]
I am facing issue with custom widget of read HTML tag in the **self.onInit** function, getting value “undefined” in window alert. 

**HTML CODE**:

<!DOCTYPE html>
<html>
<body ng-app="">
 <div flex layout="column" style="height: 100%;">
    <form #downlinkForm="ngForm" (submit)="calConfig()">
     <md-content class="md-padding" layout="column">
     <label for="country"><h4>Device Configuration </h4></label>
            <label for="singleSelect">Device Mode</label>
            <select name="device_mode" ng-model="deviceMode">
                  <option value="000">Time Based</option>
                  <option value="001">Motion Based</option>
                  <option value="010">Indoor Location</option>
                  <option value="110">BLE Live</option>
            </select>
           <label for="dl_hex_val">Computed Configuration Value</label>
           <textarea id="dwonlink_value" ng-model="dwonlinkValue" style="height:50px"></textarea>
           <input type="submit" value="Create New Configuration"/>
   </md-content>
  </form>
</div>
</body>
</html>

**JS Code** : 

self.onInit = function() {
    self.ctx.$scope.calConfig = function() {       
       var deviceMode = self.ctx.$scope.deviceMode;           // select parameter
      window.alert(deviceMode);
   };
}

**Comment by Ultrazombie** [comment]
Closed due to inactive.
