### ISSUE TITLE
Changing conf file- Limit to connected mqtt clients?

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3078]
Hi,

Is a change to the configuration file needed for a high number of mqtt clients that want to connect to TB? Im having issues connecting 1,000 clients to TB using paho-mqtt. I am using threads to send data for the devices every 10s, however, I cant even connect to TB. 

Thanks in advance

**Comment by Karabiy** [comment]
you can refer to this link regarding the API limits 

https://thingsboard.io/docs/user-guide/api-limits/
