### ISSUE TITLE
How to handle count/impulse data?

### ISSUE THREAD

**Issue by Poquaruse** [thingsboard/thingsboard#308]
Hi,

first of all let me say that I am very impressed with this awesome project! I really like the approach and the documenation which makes it a pleasure to try your software! :-) Thank you!

I did run into a small problem though. Right now, I'm using Grafana and InfluxDB to solve a specific task. A Raspberry Pi observes my (not so smart) electric meter and as soon as an impulse is detected (meaning, that 1/75 kWh of electric energy have been consumed) an entry in InfluxDB is created. This means, that each event is registered and the value is just a simple "1". Then in Grafana, I do the following:

SELECT derivative(cumulative_sum("value"))/75*1000*3600/(5*60) FROM "electric_meter" WHERE $timeFilter GROUP BY time(5m) fill(null)

This gives me an approximation of the current power (nota bene: not the _energy_ consumed!). Currently, the device at the electric meter only tells me that an event happened (e.g. a certain amount of energy has been consumed). It does not calculate the time difference between to events to derive the power from this. 

I'd like to replicate this in thingsboard. I'm quite sure, that the above way is not possible. Do you know another approach? Is there a way to preprocess the data or to use the time difference between to logged events in order to calculate the power? I'm grateful for any hints. :-)

Thanks and best regards

**Comment by volodymyr-babak** [comment]
hi, you can implement your own analytics REST endpoint. 
Using https://thingsboard.io/docs/reference/plugins/rest/ you can send events to this endpoint every time device sends you somethings. 
In the body of this REST request you are sending $deviceName as well.
You implement your own custom calculate logic inside your analytics REST endpoint, and once you calculate your power you send back it to ThingsBoard.
To send back updated telemetry you can use Gateway API https://thingsboard.io/docs/reference/gateway-mqtt-api/ where device token is not required, only device name.

**Comment by ashvayka** [comment]
I suggest to keep this issue open until we will publish a reference guide how to do this.

**Comment by Poquaruse** [comment]
Thank you both for your replies. I'll look into it and I'll try to wrap my head around it.

If it doesn't bother you, I'd keep this issue open because I also think that some guidance would be nice.

Best regards!

**Comment by vparomskiy** [comment]
Please use following tutorials to implement data aggregation:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/
