### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AndyWebJava** [thingsboard/thingsboard#3082]
**Describe the bug**
Where is the Msgprotos class???org.thingsboard.server.common.msg.gen.MsgProtos not found.

**Your Server Environment**
Ubuntu18.04
![1594531122(1)](https://user-images.githubusercontent.com/22862566/87239483-456edb00-c442-11ea-86dd-d07ad6635771.jpg)

**Comment by Karabiy** [comment]
are you using the master branch?

**Comment by trypzz** [comment]
Hello, @AndyWebJava 

We are don't get any feedback from you.
Do you have additional questions or I can close this issue?

**Comment by trypzz** [comment]
Closed due to inactivity.
