### ISSUE TITLE
[Bug] unable to complete SSL setup as dicumented

### ISSUE THREAD

**Issue by saikumaru** [thingsboard/thingsboard#3083]
**Describe the bug**
I am trying to install SSL for CE on AWS EC2 as per steps outlined here https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

> sudo service haproxy restart

Fails with

>Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

>journalctl -xe
parsing [/etc/haproxy/haproxy.cfg:53] : 'bind *:443' : unable to load SSL private key from PEM file '/usr/share/tb-haproxy/default.pem'

>sudo certbot-certonly --domain your_domain --email your_email
An unexpected error occurred:
Error creating new order :: Cannot issue for "12345.compute-1.amazonaws.com": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy

**Your Server Environment**
* own setup
  * cloud on EC2

* deployment
  * OS Name and Version- Ubuntu 18.04
]

**To Reproduce**
Follow steps to deploy TG CE on Amazon EC2.

https://thingsboard.io/docs/user-guide/install/cluster/aws-self-hosted-setup/

Then go to the section to setup the Haproxy
https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

**Expected behavior**
The script should execute successfully.

**Screenshots**

**Additional context**
Lol

**Comment by CooL16** [comment]
You cannot add letsencrypt certificate to amazon domain name.

Please buy another domain name, and attach ip address of your ec2 instance to it.

**Comment by saikumaru** [comment]
@CooL16 , but that was for the step 9

Can you advise a solution for the error on step-8 please?

**Comment by Congregator** [comment]
Has there been any resolution to this for step 8?

**Comment by davidjovanny** [comment]
Hi, I was trying with the document file, however, it didn´t work according to that. when I was at 9 step same failure, 
 `sudo service haproxy restart`

> Job for haproxy.service failed because the control process exited with error cod                                                                                                             e.
> See "systemctl status haproxy.service" and "journalctl -xe" for details.

checked finally /usr/share/tb-haproxy/default.pem and it was just 1 key, must be public and private together, so deleted all files and remade again and it worked.

`sudo rm /usr/share/tb-haproxy/default.pem /tmp/haproxy_key.pem /tmp/haproxy_cert.pem /tmp/haproxy.csr`
`sudo haproxy-default-cert`
`sudo service haproxy restart`
