### ISSUE TITLE
Custom action to add "Filter" on widget header in Thingsboard "Open Street Map Widget"

### ISSUE THREAD

**Issue by VegitoGogeta** [thingsboard/thingsboard#3085]
**Component**

 * UI

**Description**
Hi there, i am new to  thingsboard IOT platform and i am struggling in custom actions. plz guide me to resolve and  how to move forward after getting datasources ,to achieve my requirement.

A clear and concise details.
![hncs8](https://user-images.githubusercontent.com/68214547/87271505-0cda0a80-c4f1-11ea-8257-75b77c24500e.png)

![lqZXV](https://user-images.githubusercontent.com/68214547/87271587-4579e400-c4f1-11ea-9068-08430f8932d7.png)

**Environment**

 * OS:  ubuntu and 18.04
 * ThingsBoard: 3.0.1
 * Browser: chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
