### ISSUE TITLE
[Question] Polygon for Image Map

### ISSUE THREAD

**Issue by micklwl** [thingsboard/thingsboard#3088]
**Component**

 * Image Map Widget

**Description**
The polygon for image maps seems to have the coordinates based on pixel size. This cause the polygon form to be of the same size regardless of the widget size, and to be placed incorrectly if the widget resizes. Perhaps change it to be based on x, y coordinates between 0 and 1 instead or is that any alternative way to solve this issue?

**Environment**
 * ThingsBoard PE
 * Chrome

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
