### ISSUE TITLE
how to use "java -jar" to start thingsboard instead of "servcie thingsboard start"

### ISSUE THREAD

**Issue by cc19931002** [thingsboard/thingsboard#309]
Our lab need to debug thingsboard remotely,so I need to add some extra JVM parameter when thingsboard start。
  I try to use java -jar  but failed,I am really depressed.Is there any suggestions?

**Comment by ashvayka** [comment]
you can add this parameters in thingsboard.conf located in /etc/thingsboard/conf/. There is an ability to setup JVM options.
