### ISSUE TITLE
[Feature Request] Delete telemetry data from UI.

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/thingsboard#3090]
Can we please have a way of deleting telemetry data from the UI?

Garbage data may be easily generated from a device, during debugging/testing, or due to any malfunction. There should be a way to delete that data.

Yes, I am aware that this can be achieved through the REST API. However it is not optimal.

Firstly, many of the Tenant Admins, cannot use the REST API. They are managing devices, they are not developers. Do not assume that all have the same background, or the same technical skills.

Secondly, using the REST API is really cumbersome. It involves a lot of steps, that mistakes can happen, and that consumes a lot of time.

It would be much much more easy and simple if there was just one button next to every telemetry. You just click it, and its gone. Just like the shared attributes.

**Comment by luixal** [comment]
This is **totally** needed.

**Comment by iwas108** [comment]
Any update on this? Today my 25GB server is dead due to thingsboard log file consumed 5GB and the postgresql database consumed 19GB. I'm looking a way how to remove some old debugging telemetry data from database to save space and turn my server back on.

**Comment by cemsina** [comment]
I am working on it

**Comment by dk9uv** [comment]
Great, I really appreciate that,

would be very helpful

 

With best regards

 

Chris

 

 

Von: Cemsina Güzel ***@***.*** 
Gesendet: Dienstag, 13. Juli 2021 10:30
An: thingsboard/thingsboard
Cc: dk9uv; Manual
Betreff: Re: [thingsboard/thingsboard] [Feature Request] Delete telemetry data from UI. (#3090)

 

I am working on it

**Comment by b16rdp** [comment]
Hi there,

I have the same issue with a massive amount of debug data I need to delete.  One of our engineers left debug mode turned on for a script monitoring all incoming data.  So now we have over 300,000 debug entries, for one component of one rule.  If I delete the script in the rule will the debug data still remain?  If I delete the entire rule will the debug data still remain?

I think this is the same question as being asked by others and is really needed to keep systems clean, after commissioning has taken place.

Thank in advance for any advise or assistance on this.

**Comment by PovitruliaV** [comment]
Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1360) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our Release Notes to see all new additions to the platform in the subsequent releases.

**Comment by piechade** [comment]
@PovitruliaV news on this topic?

**Comment by smart92** [comment]
@fjpanag, are any news about the possibility to delete telemetry data from UI?
