### ISSUE TITLE
[Bug] Live Demo: some data not displayed on live demo

### ISSUE THREAD

**Issue by Elaine0** [thingsboard/thingsboard#3092]
**Describe the bug**
Data is not displayed on dashboard, which is on live demo server.
The error code is: WebSocket Error: error code - 1011.

**Your Server Environment**
* demo.thingsboard.io

**Your Client Environment**
* Browser: Google Chrome 
* Version: 83.0.4103.116 (Official Build)

**To Reproduce**
1. Go to 'Dashboards'
2. See error and error code is WebSocket Error: error code - 1011.

**Expected behavior**
The asset data should display on each widget.

**Screenshots**
![1](https://user-images.githubusercontent.com/36446347/87394403-548c8f00-c5e2-11ea-8c6b-1dae0d7e8a22.PNG)

**Comment by Karabiy** [comment]
have you used any kind of a custom widgets for those, or it all of those are default?

**Comment by ashvayka** [comment]
please provide your login name and we will review this specific use case.

**Comment by adamfadil** [comment]
same issue when i used a custom widgets development

**Comment by Karabiy** [comment]
@adamfadil please provide us with the video record on those if it is possible 
@Elaine0 please specify your login name for the demo.thingsboard.io

**Comment by adamfadil** [comment]
Hi Thingsboard/Thingsboard

**Comment by adamfadil** [comment]
Hi Thingsboard/Thingsboard

this is my login name for the  demo.thingsboard.io    :
adamsah2010@gmail.com

the widget gantt run fine with angularjs version but note with angular2
and Data is not displayed on dashboard

Best regards

**Comment by adamfadil** [comment]
Hi @Karabiy 
in order to reproduce the bug, please find attached widget, it runs without problems with angularjs
[gantt.zip](https://github.com/thingsboard/thingsboard/files/4937476/gantt.zip)

**Comment by Karabiy** [comment]
> Hi @Karabiy
> in order to reproduce the bug, please find attached widget, it runs without problems with angularjs
> [gantt.zip](https://github.com/thingsboard/thingsboard/files/4937476/gantt.zip)

which exact version of the angular js you are using?

**Comment by adamfadil** [comment]
Thingsboard 2.5.0 CE

**Comment by Elaine0** [comment]
> please provide your login name and we will review this specific use case.

Sorry for the late reply.
My login name is: yifei.chen@evalueserve.com

**Comment by Elaine0** [comment]
> @adamfadil please provide us with the video record on those if it is possible
> @Elaine0 please specify your login name for the demo.thingsboard.io

Sorry for the late reply.
My login name is: yifei.chen@evalueserve.com

**Comment by Elaine0** [comment]
> have you used any kind of a custom widgets for those, or it all of those are default?

Yes, I've used a custom widget as attached:
[value_card.zip](https://github.com/thingsboard/thingsboard/files/4940886/value_card.zip)
Value is not displayed on this custom widget.

Besides, for default widget: **entity card** and **tool-tips on map widget** is not working.

**Comment by Elaine0** [comment]
@ashvayka @Karabiy

**Comment by cytaylorw** [comment]
Same problem when using **Entity group list** alias filter type. Select the entity group from the drop-down list but still no data displayed.

**Comment by ChristineChetty** [comment]
I have this issue intermittently as well. All standard widgets

**Comment by Cody-Hayes97** [comment]
I have been having the same issue, when going back 7 or 30 days in the time window, the websocket error appears and the console gives a message that reads "cannot convert null or undefined to object"

**Comment by Cody-Hayes97** [comment]
even when using all standard widgets

**Comment by michaldengusiak** [comment]
I come across same issue when use historic data I suspect due to nulls
![image](https://user-images.githubusercontent.com/26113670/119557855-a1133000-bd98-11eb-90be-ec48485ecdec.png)

**Comment by glancia** [comment]
Hello. Any feedback on this?

I also have the same problem using custom widget and historical data timewindow, managed inside the widget using the method 

```
self.ctx.timewindowFunctions.onUpdateTimewindow(startTs,endTs)
```

TB version 3.2.2PE

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
