### ISSUE TITLE
Multiple Headers For REST API CALL Node

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3096]
Hello !
Please tell me how to use multiple headers in REST API CALL Node
I have this command which is working fine with CURL on Ubuntu server 18.04 : 
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJz I CUTTED OFF THE JWT TOKEN' 'http://127.0.0.1:8080/api/alarm/67f775d0-c5fd-11ea-a047-ef6fb003d528/ack'

So, as you can see above the command is heaving 3 headers :
header1_value='Content-Type: application/json'
header2_value='Accept: application/json'
header3_value='X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJz I CUTTED OFF THE JWT TOKEN'
and the command
command='http://127.0.0.1:8080/api/alarm/67f775d0-c5fd-11ea-a047-ef6fb003d528/ack'

In metadata from previous node I have all needed parameters like above.
In the attached picture will see how I designed the node.
Every time I get a error from the REST API CALL Node even if the command is running fine with CURL on Ubuntu server 18.04 : 
Please tell me how to pass the complete command in REST API CALL Node.

Thank You !

Environment
OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

![Untitled-2](https://user-images.githubusercontent.com/59779817/87486040-f3e16e80-c642-11ea-8c78-45da7c23cc3a.jpg)

**Comment by Karabiy** [comment]
you can set more headers than three of them by clicking on  + ADD button below the headers.

**Comment by lmax25** [comment]
Dear sir !
In the picture above you can see that I already added multiple headers by clicking on + ADD button below the headers....
But somehow it is not working...

Please be kind and tell me how to execute the following CURL command with REST API Call node from Thingsboard :

curl -X POST --header 'Content-Type:   application/json' --header 'Accept: application/json' -d   '{"username":"tenant@thingsboard.org",   "password":"mypassword"}' 'http://127.0.0.1:8080/api/auth/login'

How can I send the -d  '{"username":"tenant@thingsboard.org",   "password":"mypassword"}'  to the REST API CALL node ?

Thank You !

**Comment by escalanterj** [comment]
Did you get any response in 2 years?
