### ISSUE TITLE
[Bug] Inconsistent UI wrt alarm update via rest api

### ISSUE THREAD

**Issue by ganzuoni** [thingsboard/thingsboard#3098]
I've created and alarm via rule chain and added some details.
While the alarm is ACTIVE, I've updated the alarm via Swagger UI adding jut another field in the details.
Using getAlarmById in Swagger I can see the correct details with the added field, while TB Web UI always shows
"old" version of alarm details (new filed is missing)
This happens even after a complete restart
TB v 3.0.1 community edition

**Comment by Karabiy** [comment]
make sure you configured the details properly 
refer to the below regarding the screenshot including the details function  which won't came back the previous details 
![pasted image 0](https://user-images.githubusercontent.com/31805736/87569432-c7276880-c6cf-11ea-92ba-3af3eb247067.png)
