### ISSUE TITLE
[Bug] Can't update existing integrations in PE3.01

### ISSUE THREAD

**Issue by jskillen** [thingsboard/thingsboard#3099]
**Describe the bug**
Changing values in existing integration details does not trigger the accept button (checkmark) to become enabled. This makes updating the integration impossible unless you change the type of integration, which clears out any preexisting values.

**Your Server Environment**
* own setup
  * Local deployment
  * ThingsBoard 3.01PE
  * Ubuntu 18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Mac OS Catalina 10.15.5
* Browser: Chrome
* Version 83.0.4103.116

**To Reproduce**
1. Go to integrations screen
2. Click on an existing integration and toggle edit mode
3. Update any value except for the integration type
4. Observe that accept button remains disabled and changes cannot be accepted

**Expected behavior**
The accept button should be enabled and changed values should be applied

**Comment by Karabiy** [comment]
can you provide us with the video record?

**Comment by jskillen** [comment]
@Karabiy 
> can you provide us with the video record?

Attached.
[Screen Recording 2020-07-20 at 8.56.14 AM.mov.zip](https://github.com/thingsboard/thingsboard/files/4948769/Screen.Recording.2020-07-20.at.8.56.14.AM.mov.zip)

**Comment by vvlladd28** [comment]
Hi @jacklicn,
Thank you for your report. We will add a fix coming soon

**Comment by vvlladd28** [comment]
Hi @jskillen 
You may have problems with the header filters, check for empty fields. There, all fields are required.

**Comment by jskillen** [comment]
@vvlladd28 
I just checked and all the header filter fields have values.
As you saw, I had just re-opened the integration. All field validation had been performed on the initial save.

**Comment by jojo-** [comment]
I am encountering the same issue, and can only update the integration if I remove the Client ID.

**Comment by trypzz** [comment]
Fixed in 3.1 release. Close
