### ISSUE TITLE
Typo in RPI3 Install Guide ?

### ISSUE THREAD

**Issue by Corei52500k** [thingsboard/thingsboard#31]
Hi,

i am currently installing Thingsboard on a RaspberryPi, i noticed that a variable name does not match

From your Install Guide (http://thingsboard.io/docs/user-guide/install/rpi/) [**NEW_HEAP_SIZE**]:

![image](https://cloud.githubusercontent.com/assets/24847458/21723383/76f8f472-d430-11e6-9d0d-bc55512cd752.png)

From /etc/cassandra/cassandra-env.sh [**HEAP_NEWSIZE**]

![image](https://cloud.githubusercontent.com/assets/24847458/21723478/dcc7e178-d430-11e6-859c-d98466c7c50b.png)

Maybe the changed the variable names?
Greetings.

**Comment by ashvayka** [comment]
Thanks! Fixed in this [Pull request](https://github.com/thingsboard/thingsboard.github.io/pull/13/files)
