### ISSUE TITLE
Switch node configuration doesn't allow to set custom relations

### ISSUE THREAD

**Issue by vortexalex** [thingsboard/thingsboard#3109]
Hello,

I'm using TB 2.4.1.

The Switch rule node doesn't allowe me to configure custom labels on the outgoing links. It always shows me only the Failure relation:
![image](https://user-images.githubusercontent.com/5671229/87782833-8d6f7280-c833-11ea-9c8c-3d7af84e976c.png)

I expected to see the popup like it is described in the TB user guide (see below):

![image](https://user-images.githubusercontent.com/5671229/87782772-6d3fb380-c833-11ea-9b0f-83bdd15e2311.png)

What's wrong with this? My function is the same shown in the TB user guide.

Thank you for helping!

**Comment by Backdraft007** [comment]
You can enter a name like you want. Just write in the field.

**Comment by vortexalex** [comment]
OMG! Thank you!!! :)
