### ISSUE TITLE
[Bug] Can't establish connection to Cassandra DB because of Thingsboard configuration

### ISSUE THREAD

**Issue by SORC3r3r** [thingsboard/thingsboard#3111]
**Describe the bug**
Since you changed the default cassandra datacenter config calue to `datacenter1`, we can't establish a connection to our cassandra cluster anymore unless we change the name of the datacenter of some cassandra nodes to this exact value.

**Your Server Environment**
Thingsboard Enterprise v3 running in Kubernetes cluster.

**To Reproduce**
1. Have a cassandra cluster which does not have any node running in `datacenter1`
2. Try to establish a connection between Thingsboard and Cassandra
3. See it failing until you change the configuration of Cassandra

**Expected behavior**
Remove that value for the cassandra datacenter or make it configurable in Thingsboard.

**Additional context**
Here is the change in the Github commit I guess:
https://github.com/thingsboard/thingsboard/commit/fa79331702273bda7d6169bdec505f4a4fbf6c53

/cc @mihaics

**Comment by vvlladd28** [comment]
Hi @SORC3r3r,
Yes, this fix will be added to the new release of TB PE 3.1. It will be possible to change the Cassandra datacenter.
