### ISSUE TITLE
Arduino + ESP8266-01. RPC commands works very strange

### ISSUE THREAD

**Issue by NazarDiadiun** [thingsboard/thingsboard#3114]
Thingsboard is a great resource that has helped me more than once!
Without any problems, I can send telemetry to the service.
This time I needed to control the Arduino GPIO from the dashbord. I used the example from the SDK for RPC, and it even somehow worked, but it works once for 30 clicks of a button. I have no problem interpreting the data, everything is fine - when the arduino “sees” the rpc command, it receives the data perfectly. There is only one problem - Arduino almost never sees that I changed the state of the switch. I repeat - I can press the switch 10 times, and the arduino will only react once, or not at all.
I use a bunch of Arduino + ESP8266-01 (software serial)
First, I connected the hardware (ESP8266 to arduino) and downloaded an example from the library for working with RPC. After that, I created a widget on the dashboard in the form of a switch. If I constantly turn it on and off, then sometimes I can see in the serial port the data that I turned on or off the switch. But it works as unstable as possible.
And so, I cannot understand the reason for such unstable work (Although, in principle, both hardware and software seem to work, if I can accept at least one RPC command)
I really hope for the help of experts, or those who have gone through this. I have already killed a lot of time for this.
Thanks in advance!

**Comment by hafidzdaud** [comment]
Hello, I have yet to master this in full. Documentation has a lot of gap.

I assumed you are using one-way RPC? I found two way RPC cannot be done with private IP address facing public internet MQTT broker.

**Comment by NazarDiadiun** [comment]
Thanks for the answer!

I've tried using both one-way RPC and two-way. In both cases, the result is the same, except that in the first case, the thingsboard does not expect a response from the controller. Maybe the problem is that I am using the Software serial and arduino instead of downloading the firmware directly to the ESP8266, but the project conditions do not allow me to do this.

**Comment by Karabiy** [comment]
for those reason you can use the "RPC Reply" Rule node. 
Refer to this link on the tutorial related: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-reply-tutorial/

**Comment by NazarDiadiun** [comment]
That is, I can’t just add a widget to the dashboard and immediately use it with the thingsboard SDK library?

**Comment by NazarDiadiun** [comment]
I tried to do everything as in the tutorial to control the outputs of the GPIO. However, nothing came of it, as I already wrote
https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/

**Comment by NazarDiadiun** [comment]
I will also add that sometimes in the serial port I see the following line: [TB] unable to de-serialize RPC

**Comment by NazarDiadiun** [comment]
I have already tried to connect the ESP8266 to the Arduino MEGA 2560 Hardware Serial, but to no avail. I changed the Baud rate for ESP to 115200. Similarly, it did not help

**Comment by NazarDiadiun** [comment]
Okay. As it turned out, for some reason I cannot use the thingsboard library with arduino and esp8266. I just tried to upload the sketch directly to esp8266 and the RPC data immediately went to the serial port. It's very strange, and you will have to figure out how to transfer data to arduino, but it works. Thanks to everyone who helped or suggested!
