### ISSUE TITLE
Unable to add devices for a customer in Dashboard entities filter of type "Device Search Query"

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3115]
**Component**

 * UI

**Description**
When creating a filter of type "Device Search Query", I pick "Type" field to be CUSTOMER and then pick a customer name from the list, Relation Type "Any type", then I select a Device type from available list - but when clicking on "Add", it says in red color "No entities matching specified filter were found.". But that customer has few devices of that device type assigned to it.

**Environment**

 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: 3.0.1
 * Browser: Chrome

**Comment by ashvayka** [comment]
The bug is fixed and will be deployed to demo.thingsboard.io today. Commit https://github.com/thingsboard/thingsboard/commit/2dd2cae91b912dc1eab59d002bafe9d5fe7b437d
