### ISSUE TITLE
[Bug] Change owner of device is not registered as an event in the system

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3121]
Hi

We are trying to act upon this event but it is not registered in the rule chain. We assume it would be under message type:  "ENTITY_UPDATED" event.

TB PE 3.0.1

Regards

**Comment by SuminDenis** [comment]
Hi [@t0mZ4](https://t.me/t0mZ4),

I'm glad to inform you that the "Change Owner of Device" event is registered starting from ThingsBoard PE 3.2.1.

Please take a look at this release note: https://thingsboard.io/docs/pe/reference/releases/#v321-january-26-2021

Can we close this ticket?

Best regards,
Denys

**Comment by epalchenko** [comment]
close due to inactive
