### ISSUE TITLE
[Bug] Thingsboard PE 3.0.1 with docker

### ISSUE THREAD

**Issue by CorentinBarman** [thingsboard/thingsboard#3122]
**Describe the bug**

I can't run Thingsboard PE with docker (in memory queue) starting from version 2.5.1 and higher. Every time I deploy it, I get the following error at the very end.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 9090 was already in use.
```

The docker engine is clean and no other containers are running, port 9090 is definitely not in use anywhere else than from Thingsboard.

Trying to use the kafka queue service result in other errors also, in every docker container (zookeeper, kafka & tpbe).

I can provide the log files if you can't reproduce.

**Your Server Environment**

Tested in three docker environments by following the default configuration from https://thingsboard.io/docs/user-guide/install/pe/docker/.

* Jelastic cloud running Docker Engine, deployed with Portainer stack (linux x86_64 CentOS Linux 7)
* Windows 10 with Docker Desktop
* MacOS Catalina 10.15.5 with Docker Desktop

Thingsboard PE version:
* 2.5.0 works everywhere
* 2.5.1, 2.5.2, 3.0.0, 3.0.1 don't work with docker deployment

Tests were made with Thingsboard PE maker license.

**To Reproduce**

1. Follow the deployment steps with docker from https://thingsboard.io/docs/user-guide/install/pe/docker/
2. Use "in memory" or "kafka" queue service
3. Perform docker-compose up
4. Error near the end of deployment

**Expected behavior**
If the docker image version is 2.5.0, everything goes smoothly and the deployment is a success.

**Comment by CooL16** [comment]
You have to export INTEGRATIONS_RPC_PORT with any port except 9090, I recommend you
to use port 50051.
Please use this docker-compose.yml file:
version: '2.2'
services:
mytbpe:
restart: always
image: "store/thingsboard/tb-pe:3.0.1PE"
ports:
- "8080:9090"
- "1883:1883"
- "5683:5683/udp"
environment:
TB_QUEUE_TYPE: in-memory
TB_LICENSE_SECRET: YOUR_SECRET_KEY
TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
**INTEGRATIONS_RPC_PORT**: 50051
volumes:
- ~/.mytbpe-data:/data
- ~/.mytbpe-logs:/var/log/thingsboard
Please let me know if something is unclear for you.

**Comment by CorentinBarman** [comment]
Thanks, adding the line did fix it!
