### ISSUE TITLE
[Bug] Excessive Use of AWS SQS Queues

### ISSUE THREAD

**Issue by egulacti** [thingsboard/thingsboard#3128]
**Description**
After setting up Thingsboard as a self hosted setup on AWS using AWS SQS I have observed huge amount of SQS usage. In 12 hours approximately 35 Million messages where exchanged with SQS causing unnecessary costs (17 USD/day)

**Server Environment**
  * Self-hosted setup using AWS EC2 instance
  * ThingsBoard Version 3.0.1
  * Ubuntu 18.04

**Client Environment**
I have not uploaded any data yet. I used only demo data and browser to access the Thingsboard server.

**Expected behavior**
The number of SQS messages should not be this high. There are 44 SQS queues created by Thingsboard server and most of them report ~5000 empty receives/min. Manually modifying the queus to use long polling didn't help.

The default behavior of using AWS SQS should be reviewed. The following from AWS documentation [(Reducing Costs)](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/reducing-costs.html) could be helpful: 

> To reduce the cost of using Amazon SQS and to decrease the number of empty receives to an empty queue (responses to the ReceiveMessage action which return no messages), enable long polling. For more information, see Amazon SQS Long Polling.

**Screenshots**
tb_core_5.fifo monitor screenshot is as follows

![aws-sqs-monitor](https://user-images.githubusercontent.com/11722394/88031691-9a4ad980-cb45-11ea-97c9-0b882866dd0c.jpg)

**Comment by YevhenBondarenko** [comment]
Hi @egulacti 

These params affect the number of requests per second from each partitions per each queue.
Number of requests to particular Message Queue is calculated based on the formula:
((Number of Rule Engine and Core Queues) * (Number of partitions per Queue) + (Number of transport queue partitions)
+ (Number of microservices) + (Number of JS executors)) * 1000 / POLL_INTERVAL_MS
For example, number of requests to AWS SQS based on default parameters is:

Rule Engine queues:
Main 10 partitions + HighPriority 10 partitions + SequentialByOriginator 10 partitions = 30
Core queue 10 partitions
Transport request Queue + response Queue = 2
Rule Engine Transport notifications Queue + Core Transport notifications Queue = 2
Total = 44
Number of requests per second = 44 * 1000 / 25 = 1760 requests

Based on the use case, you can compromise latency and decrease number of partitions/requests to the queue, if the message load is low.
Sample parameters to fit into 10 requests per second on a "monolith" deployment: 

TB_QUEUE_CORE_POLL_INTERVAL_MS=1000
TB_QUEUE_CORE_PARTITIONS=2

TB_QUEUE_RULE_ENGINE_POLL_INTERVAL_MS=1000
TB_QUEUE_RE_MAIN_POLL_INTERVAL_MS=1000
TB_QUEUE_RE_MAIN_PARTITIONS=2
TB_QUEUE_RE_HP_POLL_INTERVAL_MS=1000
TB_QUEUE_RE_HP_PARTITIONS=1
TB_QUEUE_RE_SQ_POLL_INTERVAL_MS=1000
TB_QUEUE_RE_SQ_PARTITIONS=1

TB_QUEUE_CORE_POLL_INTERVAL_MS=1000

TB_QUEUE_TRANSPORT_REQUEST_POLL_INTERVAL_MS=1000
TB_QUEUE_TRANSPORT_RESPONSE_POLL_INTERVAL_MS=1000

**Comment by egulacti** [comment]
Hi Yevhen,

Thanks for the detailed explanation and sample parameters. I will try these in production. It is seems more feasible to use a managed Kafka service on AWS. 

This behavior is by design and not a bug.
