### ISSUE TITLE
Choose device in sendOneWayCommand [control widget]

### ISSUE THREAD

**Issue by hjlopezr** [thingsboard/thingsboard#3134]
**Component**
 * Control widget

**Description**
How to send RPC command to specific device when i have multiples devices in my dashboard.
For example with "RPC button" control widget:
        if (oneWayElseTwoWay) {
            commandPromise = self.ctx.controlApi.sendOneWayCommand(rpcMethod, rpcParams, timeout);
        } else {
            commandPromise = self.ctx.controlApi.sendTwoWayCommand(rpcMethod, rpcParams, timeout);
        }
        commandPromise.subscribe(
            function success() {
                self.ctx.$scope.error = "";
                self.ctx.detectChanges();
            },
            function fail(rejection) {
                if (self.ctx.settings.showError) {
                    self.ctx.$scope.error =rejection.status + ": " +rejection.statusText;
                    self.ctx.detectChanges();
                }
            }
        );
In 2.5 version i used "sendTwoWayRpcCommand" but in 3.0.1 version i'cannot find the how to access to this command.

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: v3.0.1
 * Browser: Chrome

**Comment by Tasosgi** [comment]
I am wondering the same..
