### ISSUE TITLE
[Bug] Device API accessible using old Access Token via CoAP

### ISSUE THREAD

**Issue by JcBernack** [thingsboard/thingsboard#3137]
**Describe the bug**
There seems to be a weird caching problem with device access tokens or sessions when using the Device API via CoAP.
After changing the device token from `foo` to `bar` the device API is accessible using either `foo` or `bar`.

**Your Server Environment**
* own setup
* observed in version v.2.5.2
* v2.4.1 does not have this problem

**To Reproduce**
1. create device with token `foo`
2. POST `{"foo":"bar"}` to`coap://tb-url/api/v1/foo/telemetry`
3. change device token to `bar`
4. POST `{"foo":"bar"}` to`coap://tb-url/api/v1/foo/telemetry`
5. POST `{"foo":"bar"}` to`coap://tb-url/api/v1/bar/telemetry`

**Expected behavior**
All the steps will succeed, but step 4 is expected to fail as the token is no longer valid.

**Comment by JcBernack** [comment]
I just tested the same thing on `demo.thingsboard.io` and can not reproduce the problem.
A diff between v2.5.2 and develop/3.1 shows no changes to anything CoAP related. Wtf?

**Comment by YevhenBondarenko** [comment]
Hi @JcBernack 

I have just tested 2.5.2 and can't reproduce this bug.

When you tested v.2.5.2 you changed device token from UI or swagger?

**Comment by JcBernack** [comment]
Hi @YevhenBondarenko 
I changed the token from the UI.

**Comment by JcBernack** [comment]
Sorry, this was a deployment bug on our end.
