### ISSUE TITLE
Is there anyway to connect db by using db tool?

### ISSUE THREAD

**Issue by Jadenhub** [thingsboard/thingsboard#3139]
**Component**
 * Generic

**Description**
I want to connect the PostgresSQL by using DBeaver tool.
But I got this message.
![image](https://user-images.githubusercontent.com/36879858/88149477-b8dace80-cc32-11ea-9874-1e49421a5b25.png)

I follow the step.
https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/

And I can run successfully.
![image](https://user-images.githubusercontent.com/36879858/88149878-40c0d880-cc33-11ea-913d-40aa2ad8afea.png)

Is there anyway to access db by  using db tool?

thanks

**Environment**
 * OS:  ubuntu 16.04
 * ThingsBoard: version 3
 * Browser: name and version

**Comment by Karabiy** [comment]
Check the host name and password to be set for the postgres

**Comment by waytai** [comment]
HeidiSQL

**Comment by Jadenhub** [comment]
I run the  sudo java -jar application/target/thingsboard-3.0.1-boot.jar .

Then, the service look like is running normally.
How do I know the db setting(dbname, hostname, username, password)?! thanks

**Comment by MarkVortman** [comment]
@Jadenhub 
By default, you can't connect to PostgreSQL from remote. To enable remote access to PostgreSQL server:

1. Connect to the PostgreSQL server via SSH
2. Get location of postgresql.conf file by executing the command (it should be something like /var/lib/pgsql/data/postgresql.conf
`psql -U postgres -c 'SHOW config_file'`
3. Open postgresql.conf file and add the following line to the end:
`listen_addresses = '*'`
4. Get the location of pg_hba.conf file: 
`grep pg_hba.conf /var/lib/pgsql/data/postgresql.conf`
where /var/lib/pgsql/data/postgresql.conf is the file from output of step 2
5. Add the following line to the end of pg_hba.conf file:
`host samerole all 203.0.113.2/32 md5`

> 203.0.113.2/32 is the remote IP from which connection is allowed. If you want to allow connection from any IP specify 0.0.0.0/0 

> md5 is the authentication method, which requires the client to supply a double-MD5-hashed password for authentication.

6. Restart PostgreSQL server to apply the changes

**Comment by Karabiy** [comment]
you can also set up the ssh tunnel for those reasons, and have a use of those  based on the particular tool you want to use for those reasons.
