### ISSUE TITLE
Fetch past telemetry data via REST API

### ISSUE THREAD

**Issue by Sascha1993** [thingsboard/thingsboard#3145]
REST API / RestClient Java 3.0.1PE | IllegalArgumentException: Map has no value for 'limit'

Hello everyone,

thanks for spending your time and reading about my issue. Currently, I'm working on a software tool for sensor analysis and I want to fetch Telemetry Data from the past with the REST Service of thingsboard. 

I have already implemented other components, which can successfully fetch latest telemetry data without any problem. Since, the SNAPSHOT Version 2.5. of the Java RestClient includes the TextPageLink apart from the official RestClient 2.5 on Github, I decided to use the 3.0.1PE Version. 
        &lt;dependency>
            &lt;groupId>org.thingsboard&lt;/groupId>
            &lt;artifactId>rest-client&lt;/artifactId>
            &lt;version>3.0.1PE&lt;/version>
        &lt;/dependency>

//In order to fetch the telemtry data of one specific device I use the PageLink data structure as follows:
**RestClient client = new RestClient(url);**
**client.login(username, password);**
**PageLink telemetryLink = new PageLink(100, 0); // fetch Page of index 0 with 100 entities**
//Furthermore, I use two longs for the unix-encoding of the time frame as following:
**fetchPastTelemetry(client, telemetryLink , 1595348075085L, 1595378375285L);**
//Afterwards I use the getTimeseries()-Method for fetching the telemetry data with the following parameters:
**private static void fetchPastTelemetry(RestClient client, PageLink link, long begin, long end) {
		TimePageLink timeLink = new TimePageLink(link, begin, end);
		UUID uuid = UUID.fromString("d3f033c0-b55a-11ea-b4ad-47e5929eed78");
		Device device = client.getDeviceById(new DeviceId(uuid)).get();
		List<String> keysPerDevice = client.getTimeseriesKeys(device.getId());
		Aggregation agg = Aggregation.AVG; 
		long interval = 6000; // in milli
		client.getTimeseries(device.getId(), keysPerDevice, interval, agg, timeLink).forEach(tsKvEntry -> System.out.println("Key: "+ tsKvEntry.getKey()+ " time: " + tsKvEntry.getTs()+ " value: "+ tsKvEntry.getValueAsString()));
}**

// All this results in an IllegalArgumenException:

**Exception in thread "main" java.lang.IllegalArgumentException: Map has no value for 'limit'**
(UriComponents.java:345)/(HierarchicalUriComponents.java:1058)/(UriComponents.java:262)/(HierarchicalUriComponents.java:450)/(Map.java:661)/(HierarchicalUriComponents.java:446)/(HierarchicalUriComponents.java:435)/(HierarchicalUriComponents.java:52)/(UriComponents.java:161)/(DefaultUriBuilderFactory.java:380)/(DefaultUriBuilderFactory.java:200)/(RestTemplate.java:694)/(RestTemplate.java:622)/(RestClient.java:1439)

I'm running this on the demo Tenant in order to explore the feasibility of a software tool on top of thingsboard. 
Please help me with this issue, I would really appreciate. :)

Best regards,
Sascha

**Comment by ismaeil-shajar** [comment]
If you use community edition PE rest version will not work for you 
Rest API v 2.5 was old and just work for thingsboard 2.4.3 
Now you need work with new version of REST API which is included in thingsboard source code.
So to install REST API please do the following :
1- git clone thingsboard from github release version 
If you use tb 2.5 download branch (release 2.5) 
Else download ( release 3.0) 
2- after clone source code you have two options either install all thingsboard include rest clients (REST API) or just install common model and rest client model 
Go to /common folder and run 
mvn clean install -DskipTests
Then got to /rest-client and run 
mvn clean install -DskipTests

3- now you have rest api dependancy in your local machine you just need to replace dependency version in you used app 
For example if you install release 2.5 new rest client version is  2.5.2
You can check it in your local repo I think floder is in ~/m2/org/thingsboard/rest-client

**Comment by Sascha1993** [comment]
Hello Ismaeil,
thank you for your help. I'm going to have a try on this

**Comment by Sascha1993** [comment]
Hello,

I would like to test your approach.  Regrettably, the Maven Build doesn't work.

Using Win 10, Maven 3.6.3, and JDK 14.0.1 results into a Build FAILURE when running mvn clean install -DskipTests in \common, \restclient or root. This holds for release-2.4, release-2.5, and release-3.0. 

Specifically, it says
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project netty-mqtt: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

The link gives a hint to the POM-file but I'm not sure how to solve this issue. In addition, I have tried to use different JDK versions 11 and 8, and Maven version 3.1. 

Under another constellation Win7, JDK 12, Maven 3.6.3, release 3.0, \restclient I receive a **similiar** error to this one:

[ERROR] Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:3.1.0-SNAPSHOT: Could not find artifact org.thingsboard:rest-client:jar:3.1.0-SNAPSHOT in central (http://repo1.maven.org/maven2/) 

such as here https://github.com/thingsboard/thingsboard/issues/1678

Thank you for your previous suggestions. I would really appreciate further help regarding this issue. 

Best regards

**Comment by ismaeil-shajar** [comment]
First you need use jdk 8 and maven v 3.6 and work with version release 2.5

**Comment by Sascha1993** [comment]
With this setup the build for release-2.5\rest-client ends up in this Build Error:

[ERROR] Failed to execute goal on project rest-client: Could not resolve dependencies for project org.thingsboard:rest-client:jar:3.1.0-SNAPSHOT: Could not find artifact org.thingsboard.common:data:jar:3.1.0-SNAPSHOT in central (https://repo1.maven.org/maven2/) -> [Help 1]

I have even tried to use Maven 3.6.0 besides 3.6.3 and always updated the environment variables for jdk and maven.

In addition, both approaches with new mirror and without mirror were used:
<mirror>
		<id>nexus-aliyun</id>
		<mirrorOf>central</mirrorOf>
		<name>Nexus aliyun</name>
		<url>http://maven.aliyun.com/nexus/content/groups/public</url>
</mirror>

**Comment by Sascha1993** [comment]
No, that's not the problem. What else could be problem? I went through all the related issues and tried a lot.

**Comment by Sascha1993** [comment]
That's not the problem. After building Common the building phase of Rest-client ends up with the following:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project rest-client: Could not resolve dependencies for project org.thingsboard:rest-client:jar:3.1.0-SNAPSHOT: Failed to collect dependencies at org.thingsboard.common:data:jar:3.1.0-SNAPSHOT
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by Sascha1993** [comment]
<img width="736" alt="report" src="https://user-images.githubusercontent.com/60472761/88823958-fbb61c80-d1c5-11ea-83c8-53aae61674cf.PNG">
<img width="614" alt="common org" src="https://user-images.githubusercontent.com/60472761/88823968-ffe23a00-d1c5-11ea-887b-798c7998938e.PNG">

Hope this pics illustrates the state adequately

**Comment by ismaeil-shajar** [comment]
First check .m2/repository/org/thingsboard folder and search for common jar and it's version 
If you not find it.
I THINK IS short to build all release-2.5 root file 
Go to / and run maven clean install

**Comment by Sascha1993** [comment]
Thank you for your continuous response, Ismaeil. I really appreciate your effort. As you see in the 2nd picture the .m2\repository\org\thingsboard folder contains this jar. 
Meanwhile, I have also tested many builds with different constellations from the root directory with npm 6.13.4 and npm 3.10.8. May you tell me which npm version is required for ui-ngx in release-2.5?

**Comment by ismaeil-shajar** [comment]
Ok force rest-client pom to get dependencies by use this 

<dependency>
    <artifactId>..</artifactId>
    <groupId>..</groupId>
    <scope>system</scope>
    <systemPath>${thingsboard common data .jar path}</systemPath>
</dependency>

**Comment by Sascha1993** [comment]
Finally, I was able to complete the build, thanks. Anyway I have the same issue from the beginning with "3.1.0-SNAPSHOT" throwing ava.lang.IllegalArgumentException: Map has no value for 'limit'
in
at org.thingsboard.rest.client.RestClient.getTimeseries(RestClient.java:1646)
at org.thingsboard.rest.client.RestClient.getTimeseries(RestClient.java:1633)
