### ISSUE TITLE
How to pass entityName when using openDashBoardState() in custom Action

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3147]
Hi Guys, in the map widget we are using this following code to switch to dashboard state based on device type. But we cannot figure out how to pass entityName to the state so we can use the alias option 'Entity taken from dashboard state parameters'

any help would be greatly appreciated 

version: thingsboard 3.0.1PE

```

var $injector = widgetContext.$scope.$injector;
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(function(device) {
        if (device.type == 'SCC-2D') {
            openDashboardState('SCC_2D')
        }
        else if(device.type == 'SCC-2T') {
            openDashboardState('SCC_2T')
        }
        else if(device.type == 'SCC-DT')  {
            openDashboardState('SCC_DT')
        }
});

function openDashboardState(stateId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    }

    widgetContext.stateController.openState(stateId, params, false);
}

```

**Comment by t0mmyz7** [comment]
Hi @vvlladd28  perhaps you can share your expertise with us o this issue as well?

**Comment by vvlladd28** [comment]
Hi @t0mmyz7,

You need to use the name from the service response:
 
```
var $injector = widgetContext.$scope.$injector;
var deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));

deviceService.getDevice(entityId.id).subscribe(function(device) {
        if (device.type == 'SCC-2D') {
            openDashboardState(‘SCC_2D’, device)
        }
        else if(device.type == 'SCC-2T') {
            openDashboardState('SCC_2T', device)
        }
        else if(device.type == 'SCC-DT')  {
            openDashboardState('SCC_DT', device)
        }
});

function openDashboardState(stateId, device) {
    var params = {
        entityId: entityId,
        entityName: device.name
    }

    widgetContext.stateController.openState(stateId, params, false);
}
```

**Comment by t0mmyz7** [comment]
@vvlladd28 thanks alot Vlad, again you help us solve this and achieve our objective!! I wonder if there is a reference where we could have studied openDashboardState() to know what variables it expects?

One small typo to fix in your code example, 

instead of            

 `openDashboardState(‘SCC_2D’, device)`

`openDashboardState(**'**SCC_2D**'**, device)`

**Comment by Arteria2** [comment]
Hello, I try to put this code in custom Action but it does not work. Can you help me ?
Thanks

var $injector = widgetContext.$scope.$injector;
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));

deviceService.getDevice(entityId.id).subscribe(function(device) {
        if (device.type == 'ers-elsys') {
            openDashboardState('co2_etat',device)
        }
        else if(device.type == 'ers-elsys-sound') {
            openDashboardState('sound_etat',device)
        }
        
});

function openDashboardState(stateId,device) {
    var params = {
        entityId: entityId,
        entityName: device.name
    };

    widgetContext.stateController.openState(stateId, params, false);
}
