### ISSUE TITLE
when execute npm install，why the file IUtils.d.ts: in node_modules/@date-io/core/IUtils.d.ts would produce "import .......  prettier" and leads to a fault

### ISSUE THREAD

**Issue by chuck199202104** [thingsboard/thingsboard#3148]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by Karabiy** [comment]
which OS and environment you are using for those to be executed?

**Comment by chuck199202104** [comment]
I use windows 10 to execute it, and I found this import seems no&nbsp; positive effect to build,so I delete it and build successfully.But I want to know why,thx!


 
---Original---

**Comment by Karabiy** [comment]
issue seems not to persists.
