### ISSUE TITLE
Analytics script

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#315]
It would be nice to have the ability to add a custom analytics script in thingsboard. Something like Google Analytics, to track the usage of our thingsboard instance.

I would expect to have the ability in the administrator menu, to specify a script that it would be injected at all generated HTML content, regardless of tenant/client.

Seems useful to me, and trivial to implement.

**Comment by ashvayka** [comment]
Hi @fotis400. This can be done by injecting a custom widget to a dashboard that has Google Analytics. In any way, I would recommend to avoid doing this without license agreement with the customer users.

**Comment by fotis400** [comment]
This is a good idea. I may do it this way.

But I see some issues with this, this is why I am proposing this to be part of the whole platform.

- You cannot monitor traffic in the whole site. Only in dashboards.
- You depend on your tenants, and generally on properly configuring the specific widget. This widget has to be configured it every time you create a new dashboard.
- You either need a dedicated widget, which will have a visual artifact, or combine it with an existing one, that will however mess things up a bit.

What are your thoughts on this?

(A license agreement isn't necessary either way? I mean with the devices we are already collecting data from the users. Not only their browsing, but maybe even what happens inside their home!)

**Comment by barobba** [comment]
Hi @ashvayka, I think it's better to let the "TB subscription holder" be responsible for making the agreements, and having the ability to add "usage analytics" is hugely important to a business. Is this feature in place now? I see this post was from 2017.
