### ISSUE TITLE
Cant access rest api even with Bearer in X-authorization

### ISSUE THREAD

**Issue by liamza1** [thingsboard/thingsboard#3150]
Hi 
I always get a 
{
  "status": 401,
  "message": "Invalid username or password",
  "errorCode": 10,
  "timestamp": "2020-07-24T07:56:08.125+0000",
  "subscriptionErrorCode": null,
  "subscriptionEntry": null,
  "subscriptionValue": null
}
curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzeXNhZG1pbkB0aGluZ3Nib2FyZC5vcmciLCJzY29wZXMiOlsiU1lTX0FETUlOIl0sInVzZXJJZCI6ImRmOGZmMWEwLWMxZGMtMTFlYS1hNzQzLTc5MjVlY2U3NmYyMSIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE1OTU1NzY0NTksImV4cCI6MTU5NTU4NTQ1OX0.5lgTPxvMBtkkwVLIPOXdCyg6daVyz_vJNxrdZuYDkZBqR3dH2gUtig8gmvbGOBSoyXhFjynk20SlE8vz53yq0g","refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzeXNhZG1pbkB0aGluZ3Nib2FyZC5vcmciLCJzY29wZXMiOlsiUkVGUkVTSF9UT0tFTiJdLCJ1c2VySWQiOiJkZjhmZjFhMC1jMWRjLTExZWEtYTc0My03OTI1ZWNlNzZmMjEiLCJpc1B1YmxpYyI6ZmFsc2UsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwianRpIjoiNmVlNjk0MjctY2NlOS00NjIyLTgzYjAtNjVlMTQ4ODRlMGNiIiwiaWF0IjoxNTk1NTc2NDU5LCJleHAiOjE1OTYxODEyNTl9.EZSVHSvBTQ3p4U-9IdEcKM9ug41CQDRVV3BuZAyUkJOvUqoLOv2bTEW_a5vwg6RtV__PKLfT3Qhv9Km71zD9og' 'http://102.37.43.51:8080/api/device/types'
when trying to use the rest API even on swagger

request is

**Comment by fsokolovsky** [comment]
I think, you can't use a sys_admin user for this.

**Comment by liamza1** [comment]
even in a tenant 

curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2xkY2hhaW50ZW5hbnRhZG1pbkBmb3VyaWVyLmNvLnphIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI1ZTYzZTg3MC1jMjhiLTExZWEtOGIzOC1jZDAxMjA3YzQyZDgiLCJmaXJzdE5hbWUiOiJBZG1pbiIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiJhZGE0NWZjMC1jMWRmLTExZWEtOGIzOC1jZDAxMjA3YzQyZDgiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE1OTU1ODAzMTIsImV4cCI6MTU5NTU4OTMxMn0.9qC5kslxOTYI7-X7QmK-fxHOKL5K1jdOohZYguYWadPyh0eJruvo6QFW1npJRWLtGofWYBWpWTSsajnjWvo_7Q","refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2xkY2hhaW50ZW5hbnRhZG1pbkBmb3VyaWVyLmNvLnphIiwic2NvcGVzIjpbIlJFRlJFU0hfVE9LRU4iXSwidXNlcklkIjoiNWU2M2U4NzAtYzI4Yi0xMWVhLThiMzgtY2QwMTIwN2M0MmQ4IiwiaXNQdWJsaWMiOmZhbHNlLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImp0aSI6IjJhZWEwMDQwLWQ0MDEtNDgzOC05YWE5LTE1MjA4MzFjMjM3NiIsImlhdCI6MTU5NTU4MDMxMiwiZXhwIjoxNTk2MTg1MTEyfQ.wZDe_GHGSjyF1zDe8Gq-lQ-tvukrVpj0VrRo7s_F-ryIiu8M4xEgRNzsy8x80mamvdxbAHRXFfCcNkJ9_n3G6Q' 'http://102.37.43.51:8080/api/device/types'

Response Body
{
  "status": 401,
  "message": "Invalid username or password",
  "errorCode": 10,
  "timestamp": "2020-07-24T08:48:06.010+0000",
  "subscriptionErrorCode": null,
  "subscriptionEntry": null,
  "subscriptionValue": null
}

**Comment by Karabiy** [comment]
which version you are referring to? Have you tried to use the swagger for those reasons? 
you may refer to this on how to use rest api properly: https://thingsboard.io/docs/reference/rest-api/

**Comment by fsokolovsky** [comment]
You have also a refresh token in header. You have to use just "Bearer token" value

**Comment by liamza1** [comment]
Im Using Thingsboard PE and the curl request sent is the one from the swagger for my instance

**Comment by fsokolovsky** [comment]
That means, you are not authorized. Don't use **system user** and for authorization use only _'Bearer token_string'_ (without refreshToken and quotes). Sweager let you put any string for authorization and will look like logged in.

**Comment by Karabiy** [comment]
> You have also a refresh token in header. You have to use just "Bearer token" value

It is correct. For the reasons of yours, you should have proceeded with the next request
curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2xkY2hhaW50ZW5hbnRhZG1pbkBmb3VyaWVyLmNvLnphIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI1ZTYzZTg3MC1jMjhiLTExZWEtOGIzOC1jZDAxMjA3YzQyZDgiLCJmaXJzdE5hbWUiOiJBZG1pbiIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiJhZGE0NWZjMC1jMWRmLTExZWEtOGIzOC1jZDAxMjA3YzQyZDgiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE1OTU1ODAzMTIsImV4cCI6MTU5NTU4OTMxMn0.9qC5kslxOTYI7-X7QmK-fxHOKL5K1jdOohZYguYWadPyh0eJruvo6QFW1npJRWLtGofWYBWpWTSsajnjWvo_7Q' 'http://102.37.43.51:8080/api/device/types'
Though, the token being used here is an expired, so that, please, request the new one and try to proceed on with those
