### ISSUE TITLE
[Bug] deviceType is not being passed to tooltip function in Google Map widget

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3151]
In thingsboard 3.0.1, deviceType is not passed to tooltip function in Google Map widget

When entering the following code to the tool-tip function, only deviceName is shown, deviceType is not shown.

``
var deviceType = dsData[dsIndex]['$datasource'].entity.type;
var deviceName = dsData[dsIndex]['$datasource'].entity.name;
return <span style="font-size:16px;">${deviceName}&nbsp;${deviceType}</span>;
``
expected: 
both deviceName and deviceType are shown

Purpose:
We want to show specific variables in this tooltip based on deviceType

**Comment by vvlladd28** [comment]
Hi @t0mmyz7,

You need update list dataKeys for datasources widget: add new entityField key - `type`. And updated your tooltip code for `var deviceType = dsData[dsIndex]['$datasource'].entity.type;` to `var deviceType = data.type; `

**Comment by t0mmyz7** [comment]
@vvlladd28 beautiful thanks for helping, i had no idea about the E variable in the data source.

For anyone who might be facing this issue, here is how I got it working based on @vvlladd28 explanation:
1. You must include Type in data sources:
![image](https://user-images.githubusercontent.com/31729091/88420057-ca101080-cdd5-11ea-9a83-62432e178620.png)

(by default the label is Type, case-sensitive)

2. In the tooltip functiom, you declare it and use it like this:

`var deviceType = data.Type
var deviceName = dsData[dsIndex]['$datasource'].entity.name;
return '<br>' + deviceType + '<br>' + `deviceName;``

that's it, thanks !
