### ISSUE TITLE
[Question] Get and update device attrbutes via Service

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3156]
Hi All,
I`ve been struggling for a while with getting the attributes for my device via built-in services in Thingsboard - here is the code i`m using:
![image](https://user-images.githubusercontent.com/55321188/88407895-13ab2c00-cdd3-11ea-9e34-de2b3411d0f5.png)
And error:
![image](https://user-images.githubusercontent.com/55321188/88407920-2160b180-cdd3-11ea-86a8-3551a2a1e3d3.png)
I`ve been diggin around this for a while but this service is just not responding for some reason.

i`m using 3.0.1 TB AWS hosted

**Comment by Tasosgi** [comment]
I think you must use .getEntityAttributes instead of .getEntityAttributesValues. I am also trying to figure out how it works at 3.0.1

**Comment by amizer12** [comment]
> I think you must use .getEntityAttributes instead of .getEntityAttributesValues. I am also trying to figure out how it works at 3.0.1

I got it working via this code in init entry:

    $scope = self.ctx.$scope;
    attributeService = $scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
    
    $scope.updateAttribute = function() {
            var datasource = self.ctx.datasources[0];
              if (datasource.entity === undefined) {
            datasource.entity = {entityType:"NODEVICE", id:"NO_ID"}
            }
else
            attributeService.saveEntityAttributes(datasource.entity.id,
                'SHARED_SCOPE',
                [
                    {
                        key: "KEY1",
                        value: "VALUE1"
                    }
                ]
            ).subscribe(
                function success() {
                    console.log('success')
                },
                function fail() {
                console.log('fail')
                }
            );
    };
    $scope.updateAttribute()



Looks liek using self.ctx.servicesMap.get prior invoking the service works, and then in the widget development guide in order to avoid the "entity.id undefined" add the IF that detects this case and logs error, withotu that IF widget editor won`t let you save the widget as it uses a function for test and function is not an entity ( i know, dumb... )

**Comment by Tasosgi** [comment]
I am glad you could make it work. Unfortunately in my case I can't use self.ctx.datasources. I am trying to read device attributes from inside a control widget which don't give access to datasource. So I am stuck with .getEntityAttributes

**Comment by amizer12** [comment]
That is the thing - use the code above and try it, it should work with the
attribute service just fine

wt., 28 lip 2020, 08:35 użytkownik Tasosgi <notifications@github.com>
napisał:

**Comment by skewty** [comment]
I simplified the code above to help others who might come to this issue looking for help.

The below code is working for me.

```javascript
    var entityId = {entityType: "ASSET", id: "11ad33f0-0ba0-11ed-b226-71603f754336"};
    var attributeScope = "SERVER_SCOPE"
    var attributes = [
        {key: "dirtyState", value: 69}
    ];

    self.ctx.$scope.$injector.get(
        self.ctx.servicesMap.get('attributeService')
    ).saveEntityAttributes(
        entityId, attributeScope, attributes
    ).subscribe(
        function success() {
            alert('success')
        },
        function fail(error) {
            alert(error.message)
        }
    );
```
or even better (just use the existing `ctx.attributeService` value):
```javascript
    var entityId = {entityType: "ASSET", id: "11ad33f0-0ba0-11ed-b226-71603f754336"};
    var attributeScope = "SERVER_SCOPE"
    var attributes = [
        {key: "dirtyState", value: 69}
    ];

    self.ctx.attributeService.saveEntityAttributes(
        entityId, attributeScope, attributes
    ).subscribe(
        function success() {
            alert('success')
        },
        function fail(error) {
            alert(error.message)
        }
    );
```

**Comment by skewty** [comment]
@amizer12 if my code above helps explain / solve your issue please close this issue.

I think your issue is `saveEntityAttributes(entityId` parameter is incorrectly formed.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
