### ISSUE TITLE
Mass emailing

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#316]
It is useful to have the ability to send mass emails towards all/some of the users of our instance. For example to mass notify about a new feature or change, about upcoming scheduled server outage, advertisements, or anything that concerns everyone.

When sending such an email there would be an option to which roles would you like to address the email. A tenant may be able to email its clients. An administrator may email other administrators, the tenants, the users, everybody etc...

Also there may be an option to send the email to everybody matching the selected roles, or to specific accounts. For example a list where you can tick which users you want to notify, in case you need to email some specific users, and not everybody.

Templates for the emails will be nice to have too, so you can write the actual content and then thingsboard will format the email according to the template, adding headers or trailers, logos, setting fonts or colors etc... Multiple editable templates for various occasions would be cool too.

Finally I believe that a history of the sent emails must be kept. So you can monitor what you have already sent to your users, or for an administrator to check what has been sent from a tenant etc.

**Comment by fotis400** [comment]
I would love to contribute in this, but my skills are not adequate for such kind of development I think... I do mostly MCU related stuff.

I understand that this will have to wait a long time, and that there are more serious priorities now. Let's keep it open however if you don't mind. Maybe someone else implements this, or maybe you may find some time...

**Comment by idimon4uk** [comment]
I would like to contribute in this. I will need a minor support, maybe, in gitter.

**Comment by idimon4uk** [comment]
@ashvayka I would like to contribute in this. I will need a minor support, maybe, in gitter.

**Comment by ashaforost** [comment]
Hello from the future:) This feature was implemented as a part of a [notification center](https://thingsboard.io/docs/user-guide/notifications/). Thank you for your patience!
