### ISSUE TITLE
how to show imgae on thingsboard map like below image

### ISSUE THREAD

**Issue by sourabhkumarjha** [thingsboard/thingsboard#3160]
![WhatsApp Image 2020-07-25 at 16 59 25](https://user-images.githubusercontent.com/29812327/88456058-4703be80-ce98-11ea-9562-5808f410befa.jpeg)

**Comment by sourabhkumarjha** [comment]
i got the idea how can i show the img

**Comment by ssakharova** [comment]
Hello @sourabhkumarjha,
Could you tell me please your question is still relevant?

Regards
