### ISSUE TITLE
How to calculate delta betwen Daily MAX and Daily MIN for a telemetry value? 

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3166]
As the title describes, i having being try to figure this one out for a week now. 

We have a devices under various customers with a the same device type. They have sensor connected to analog1. We convert the analog to Sensor data, type dendrometer_raw

we want to calculate daily for all devices of this type the following values at midnight:

dendro_daily_growth = dendrometer_raw (MAX today) - dendrometer_raw (MAX Yesterday)
dendro_daily_shrinkage = dendrometer_raw (MAX today) - dendrometer_raw (MIN today)

I am completely stuck on this.

any idea or suggests most welcome!!

**Comment by t0mmyz7** [comment]
@vvlladd28 I am appealing to your might TB powers again Vlad :1st_place_medal:

**Comment by ChantsovaEkaterina** [comment]
Hello,
Please, correct me if I  understand wrong what you need. 
The _deendrometer_raw_ is not always increasing, it can increase and decrease.
In this case, the first step is to calculate the daily min and max. You can do this by _Analytics - aggregate stream_ rule node.
Just set the aggregation function (min/max), aggregate interval type - day, and your timezone. At midnight you will receive the daily min/max values.
To calculate _dendro_daily_growth_ add the _Enrichment - originator attributes_ rule node after the _Analytics - aggregate stream_ (configured to calculate daily max). This will allow you to fetch previously saved daily max for _dendrometer_raw_.
After that calculate the _dendro_daily_growth_ (with _Transformation - script_) and save both: _dendro_daily_growth_ and recent _dendrometer_raw_daily_max_.
The _dendro_daily_shrinkage_ calculation is more complex. The daily max and min will be computed by different rule nodes and as a consequence will be transferred as two independent messages. Right now I can't come up with a more elegant way to do this than listed below:
After _Analytics - aggregate stream_ (configured to calculate daily min) add _Action - save timeseries_. I.e. the _dendrometer_raw_ should be saved instantly after calculation.
Add a small delay (_Action - delay_) after calculating the daily max and before fetching the previous daily max.  Along with previous daily max (in the _Enrichment - originator attributes_) fetch recent daily min. Calculate the _dendro_daily_growth_ and _dendro_daily_shrinkage_ in the following _Transformation - script_.

**Comment by t0mmyz7** [comment]
@ChantsovaEkaterina  awesome thanks for suggestion and method I will try and report back here. Aggregate stream node should be listening to telemetric messages of the relevant device Type, correct?

**Comment by ChantsovaEkaterina** [comment]
@t0mmyz7 If you perform the data conversion and generate the _dendrometer_raw_ telemetry key in the rule chain, you should create an additional link between node, where you perform this conversion and the Aggregate stream node.
If all operations related to data transformation made in Data Converter, you should filter messages from the required device type in the rule chain and direct them to the Aggregate stream node.

**Comment by t0mmyz7** [comment]
@ChantsovaEkaterina can I clarify with you something,

when you instruct to fetch latest min/max using   Enrichment - originator attributes rule node after the Analytics - aggregate stream (configured to calculate daily max). I must save the output of aggregate stream node as attribute first? the output of this node is telemetry message, so I need to convert it to attribute message type, then save it with save attributes?

Can the same be accomplished with save telemetry and originator telemetry node instead?

**Comment by ChantsovaEkaterina** [comment]
@t0mmyz7 _Enrichment - originator attributes_ rule node allows you to fetch not only attributes but also the latest timeseries values.

**Comment by t0mmyz7** [comment]
good news guys, I manage to get this working. doing some final tests and I will share my Flow here!

![image](https://user-images.githubusercontent.com/31729091/89188887-ea935400-d5a7-11ea-8568-19b0decb2ffe.png)

**Comment by B-DAGBERT** [comment]
Hi @t0mmyz7,

I'm trying to do something almost similar to your case.

I want to calculate each day the evolution of my telemetry. (Max of the day - min of the day)

But I can't get working the aggregate stream. Can you show me your node configuration please ? 

Thx in advance

**Comment by t0mmyz7** [comment]
Sure mate, I deleted all the other stuff, and kept the example for daily delta between max and min

our sensor is called Dendro_1
[sensor_formulas__dendro_daily_max_min.txt](https://github.com/thingsboard/thingsboard/files/5241316/sensor_formulas__dendro_daily_max_min.txt)

change the file to .json and import as rule chain

![image](https://user-images.githubusercontent.com/31729091/93515357-205e8300-f931-11ea-99e4-e00beeb84652.png)


let me know if you have any questions.

the idea here is to wait few seconds until Daily Max is saved, then grab it on the same chain as daily Min, calculate the delta and save results

works well!

**Comment by B-DAGBERT** [comment]
Seems it's working with the calculation on the max aggregation. My data being always increasing, I have to calculate the consumption on the max aggregation.

Thanks again for your help

**Comment by t0mmyz7** [comment]
What I recommend you to do is:

calculate your raw value (script node) and save it as timeseries
calculate max (agg stream node) -> save as timeseries
calculate min (agg stream node) -> save as timeseries
calculate delta (script node) -> save as time series

create a dashboard with values widget and inspect your values. you will see if something is missed calculated, you will also visually see your max/min values in the raw values column and you can tell if it is working or not.

**Comment by cptMULLA** [comment]
Hi. what did you write in this scripts? ım intern and ım new in thingsboard, so... thank you from now.
