### ISSUE TITLE
Data Buckets (Access to database data directly)

### ISSUE THREAD

**Issue by logivity** [thingsboard/thingsboard#317]
I am trying to export data from the database directly so that I can make slowl updating dashboards. But not sure how plugin would work. Can you direction me on right path on where to start. 

I am looking to put filter based data in dashboard widgets and list based data view where data can be filtered.

**Comment by ashvayka** [comment]
I don't understand this question. Please add more details

**Comment by ikulikov** [comment]
Closing due to an inactivity.

**Comment by logivity** [comment]
Sorry, forgot to update. After looking through open issue this is more related to feature request for CSV export. So that the data from dashboard can be exported to CSV file.
