### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by viktorkho** [thingsboard/thingsboard#3171]
**Describe the bug**
In dashboard Timeseries Flot widget doubles timeseries names in legend (plot is OK).

**Your Server Environment**
* own setup
  * Thingsboard v.3.0.1 in docker (thingsboard/tb-postgres)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Debian/Kali 2020.1 , Windows 10
* Browsers Chromium 80.0.3997.132 & Firefox 68.6.0

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT with custom converter
  * Gateway

**To Reproduce**
1. Add Timeseries Flot widget to your dashboard, add single datasource
2. Click on 'Save'
3. See doubled datasource names in legend

**Expected behavior**
Single datasource name per datasource.

**Screenshots**
1) 5 datasources added: https://pasteboard.co/Jjzmuz2.png
2) 10 items in the legend, 5 lines in the chart: https://pasteboard.co/Jjzndyg.png

**Comment by ChantsovaEkaterina** [comment]
Hello, 
it looks like you have two devices in your datasource. One of them has the needed telemetry, and other one doesn't.
Could you check your alias, please? Also, you could use the ${entityName} pattern in data keys labels to define if the duplicated names in the legend refer to one device.

**Comment by viktorkho** [comment]
Hello,

you are absolutely correct - the entity alias corresponds to 2 devices. My problem was resolved when I corrected the alias used. And this is not a bug, ofcourse.

Thank you for your help!
