### ISSUE TITLE
Suggestion of how to run TB

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3173]
Hi,

I am running TB, using a hybrid approach (Cassandra and PostgreSQL). All of them running in the same machine, with the following specs:
Proceessor: Intel Core i5-3570 CPU @3.40GHz x 4
RAM: 8GB
Disk Size 500GB

My goal is to connect up to 10K devices that send data every 10 seconds. Right now, using only 2.5K devices, the machine doesnt get over-loaded and I can access TB Web UI and a dashboard that I have to check if the devices are active. However, as I increase the number of devices connected and sending data, the Web UI starts overloading and laggy. I have check the CPU utilization and between TB and Cassandra, it reaches 90-100%.  

I think I will separate the Cassandra database and put it in another machine. However, I wanted to know if changing TB queue service (currently using in-memory) will benefit or make the Web UI less laggy? 

Also, I know you can separate Cassandra database and have running in a separate machine. But can you do the same with the postgreSQL database? And is it possible to do it with TB? So a part of TB that handles MQTT requests is in a machine and the rest of TB is in another?

Thanks in advance

**Comment by ashvayka** [comment]
Hi @fjpa121197 , please await a bit for 3.1 release. It will be available in max 2 weeks. This is a major improvement for UI performance and responsiveness based on improvements of SQL queries behind the UI requests.

**Comment by fjpa121197** [comment]
What are the differences between using in-memory and kafka as queue service?

**Comment by Karabiy** [comment]
Kafka provides more reliability. 
for example, in case if you have Kafka and for some reason you have your ThingsBoard host being down, the Kafka will keep store those messages and also the in-memory does not fit the cluster deployments, because of the synchronization is being required between the services.
