### ISSUE TITLE
[Bug] Alarm table cannot show details info(v3.1)

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#3176]
**Describe the bug**
Alarm table cannot show details info.

**Your Server Environment**

* cloud.thingsboard.io (v3.1)

**To Reproduce**
1. Embed details into alert messages and create alarm table
2. See error

**Expected behavior**
Show details.

**Screenshots**
**Rule Chain**
![螢幕快照 2020-07-28 上午10 17 35](https://user-images.githubusercontent.com/63713926/88611924-ac37f980-d0bc-11ea-998c-a12a6e0d7e3b.png)

**Alarm table setting**
![螢幕快照 2020-07-28 上午10 18 40](https://user-images.githubusercontent.com/63713926/88611963-c1ad2380-d0bc-11ea-8703-3df5daba4b41.png)
![螢幕快照 2020-07-28 上午10 18 47](https://user-images.githubusercontent.com/63713926/88611975-c671d780-d0bc-11ea-9ef5-7d3fd5384cb1.png)
![螢幕快照 2020-07-28 上午10 18 56](https://user-images.githubusercontent.com/63713926/88611985-cb368b80-d0bc-11ea-8376-af132884ada1.png)

**Browser console log**
<img width="1260" alt="螢幕快照 2020-07-28 上午10 21 21" src="https://user-images.githubusercontent.com/63713926/88612045-e3a6a600-d0bc-11ea-856d-58bb03ca1733.png">

**Comment by ChantsovaEkaterina** [comment]
Hello,
Could you check, please, if Location is recognized as an alarm field?
In this case, you will have a small bell icon near the key label:
![image](https://user-images.githubusercontent.com/17936317/88660010-a3581f80-d0de-11ea-86e3-86d1ebfaf2c3.png)
If no, please delete the key and try to add it again, but pointing the correct field type.

**Comment by ecmap** [comment]
> Hello,
> Could you check, please, if Location is recognized as an alarm field?
> In this case, you will have a small bell icon near the key label:
> ![image](https://user-images.githubusercontent.com/17936317/88660010-a3581f80-d0de-11ea-86e3-86d1ebfaf2c3.png)
> If no, please delete the key and try to add it again, but pointing the correct field type.

Thank you very much, now it works

**Comment by ecmap** [comment]
> Hello,
> Could you check, please, if Location is recognized as an alarm field?
> In this case, you will have a small bell icon near the key label:
> ![image](https://user-images.githubusercontent.com/17936317/88660010-a3581f80-d0de-11ea-86e3-86d1ebfaf2c3.png)
> If no, please delete the key and try to add it again, but pointing the correct field type.

**malfunction**

The data (details.xxxx) is based on Label*, but not on Key*, so when I try to change the Key* **(details.xxxx->xxxx)**, it can still display the data on the table.
![螢幕快照 2020-07-29 上午9 26 17](https://user-images.githubusercontent.com/63713926/88745973-ea492200-d17d-11ea-80ed-da34464244d9.png)
![螢幕快照 2020-07-29 上午9 26 27](https://user-images.githubusercontent.com/63713926/88745976-eddca900-d17d-11ea-8c9f-bcfd9c89d08f.png)
![螢幕快照 2020-07-29 上午9 26 57](https://user-images.githubusercontent.com/63713926/88745987-f208c680-d17d-11ea-9ad5-dc849e2521ae.png)


However, when I try to change the Label ***(details.xxxx->xxxx)/(details.xxxx->Details.xxxx)**, it cannot display the data on the table.
![螢幕快照 2020-07-29 上午9 32 16](https://user-images.githubusercontent.com/63713926/88746352-ee297400-d17e-11ea-819c-7b8bf2e18c60.png)
![螢幕快照 2020-07-29 上午9 32 26](https://user-images.githubusercontent.com/63713926/88746358-f1bcfb00-d17e-11ea-957d-98d29be01d97.png)
![螢幕快照 2020-07-29 上午9 32 36](https://user-images.githubusercontent.com/63713926/88746362-f41f5500-d17e-11ea-8da3-66ad4d59933c.png)
![螢幕快照 2020-07-29 上午9 33 00](https://user-images.githubusercontent.com/63713926/88746364-f681af00-d17e-11ea-9367-d5e9371f96b8.png)
![螢幕快照 2020-07-29 上午9 33 09](https://user-images.githubusercontent.com/63713926/88746367-f84b7280-d17e-11ea-839f-34284b0b2a45.png)
![螢幕快照 2020-07-29 上午9 33 21](https://user-images.githubusercontent.com/63713926/88746372-fb466300-d17e-11ea-81ea-4ae820ef8291.png)

**Please fix it.**

**Your Server Environment**

cloud.thingsboard.io (v3.1)

**Comment by vvlladd28** [comment]
Hi @ecmap
Thank you for your report. We will add a fix soon.

**Comment by ChantsovaEkaterina** [comment]
Thank you for reporting about the problem. We will fix this soon.

**Comment by ecmap** [comment]
> Thank you for reporting about the problem. We will fix this soon.

Has it been fixed?
The table still cannot display details.xxxx information
(Still have the same problem)

**Your Server Environment**

**cloud.thingsboard.io (v3.1)**

**Comment by ChantsovaEkaterina** [comment]
Hello,
Could you check one more time? Perhaps, two days ago, recent changes were not transferred to Cloud Environment.

**Comment by ecmap** [comment]
> Hello,
> Could you check one more time? Perhaps, two days ago, recent changes were not transferred to Cloud Environment.

it's OK now,
Thanks for the fix 👍 :)
