### ISSUE TITLE
[Question] DomSanitzer in Widget for base64 encoded data

### ISSUE THREAD

**Issue by imoon** [thingsboard/thingsboard#3184]
**Component**

 * UI
 * Widget
 
**Description**
My IoT application acquires audio signals from deployed devices. The short audio clips (<500KB) are base64 encoded and sent to TB as a JSON key/value. My goal is to provide access to the latest recordings on the dashboard so the user can quickly evaluate and take necessary action.

So I created a new widget to display the html5 audio element and set its src to the base64 encoded data string like this:`src="data:audio/wav;base64,UklGRgh3AQBXQVZFZm10IBAAAAAB … /6//q/+T/3P/g/9v/4//a/+j/3f/o/+X/6P/t//D/9v/3/w=="`. However, Angular does not permit this because it is considered an unsafe url and disables it by prepending `unsafe` to the string like this: `src="unsafe:data:audio/wav;base64,UklGRgh3AQBXQVZFZm10IBAAAAAB … /6//q/+T/3P/g/9v/4//a/+j/3f/o/+X/6P/t//D/9v/3/w=="`.

The obvious solution is to use Angular's DomSanitizer (`domSanitizer.bypassSecurityTrustUrl()`) but it is not accessible within the widget's scope and it cannot be imported at runtime. A search of this repo shows numerous usages of the DomSanitizer, including in various widget components (ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts, ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts, etc.). 

Is it possible to access the DomSanitizer in a Widget? If so, how? If not, what other options can I try?

**Environment**

 * OS:  AWS EC2 
 * ThingsBoard: PE 3.0.1
 * Browser: Chrome 84

**Comment by imoon** [comment]
Is there anyone who can help me with this?

**Comment by vvlladd28** [comment]
Hi @imoon,
In the new version TB 3.1, we are added DomSanitizer to widgetContext.

**Comment by imoon** [comment]
@vvlladd28 good news. Thanks
