### ISSUE TITLE
[Question] There is error when build

### ISSUE THREAD

**Issue by Jadenhub** [thingsboard/thingsboard#3185]
**Component**
 * UI

**Description**
I pull the latest version.
![image](https://user-images.githubusercontent.com/36879858/88767363-1f6c6900-d1ac-11ea-9a58-253f33e68caf.png)

sudo mvn clean install -DskipTests   .... failed
![image](https://user-images.githubusercontent.com/36879858/88767518-52aef800-d1ac-11ea-9891-42baaa14944b.png)

**Environment**
OS: ubuntu16.04
Thingsboard: latest

**Comment by Ultrazombie** [comment]
closed due to inactivity
