### ISSUE TITLE
[Question] Unable to filter my data through ThingsBoard widgets

### ISSUE THREAD

**Issue by Nadou14** [thingsboard/thingsboard#3186]
**Component**

 * UI
 * Rule Engine
 * Widgets
 

**Description**
I've recently been using thingsBoard communing edition to send data and create some visualization, everything went well till now, but I think if I'm not wrong that there is some limitations in this platform in terms of data analytics, because I've been trying to figure out how to add filters on my dashboards to get easily some data by its name or value, or by the device name for example. is there anyway to do so if that is possible with ThingsBoard ?

**Environment**

 * ThingsBoard: version 3.0.1

**Comment by ssakharova** [comment]
Hello @Nadou14,

Could you tell me please your question is still relevant?
If yes, please refer to this article [https://thingsboard.io/docs/user-guide/dashboards/#entity-filters](url)

Regards,
