### ISSUE TITLE
[Feature Request] Add option to filter alarms in alarms table widget by alarm Type

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3187]
Hi
currently it is only possible to filter which alarms are visible in the alarms table by alarm Status. 

**Our request** is to have the ability to also filter by alarm type, and have the option to select single or multiple alarm types.

Use-case: we have Agriculture devices where we want to show alarms related to the sensors on one dashboard, and alarms related to operations on another dashboard. So if we could filter by alarm type, we could set which alarms are showing on which table in the relevant dashboard.

note: perhaps this is possible in the data source, Use cell content function, if so let me know and I'll try.

**Comment by vvlladd28** [comment]
Hello, 
This functional added for the new version TB 3.1.

**Comment by t0mmyz7** [comment]
Looking forward to using it, thanks for the update
