### ISSUE TITLE
[Bug] ThingsBoard device search query can't be added

### ISSUE THREAD

**Issue by Nadou14** [thingsboard/thingsboard#3189]
**Describe the bug**
I'm unable to add an alias using the filter device search query using thingsboard CE V3.0.1 on my local server!

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * docker deployment
  * ThingsBoard Version 3
 
![image](https://user-images.githubusercontent.com/68945713/88793264-d234cb00-d19c-11ea-823d-3829ccf24e8e.png)

**Your Device**

* Connectivity
  
  * HTTP

**Comment by vvlladd28** [comment]
Hi @Nadou14,
Thank you for your report, we will add a fix to the master branch. Coming soon we add fix to demo.thingsboard.io

**Comment by Nadou14** [comment]
@vvlladd28 Thank you for your reply, I'd also like to know if it  is possible to create data filters through rule engine to be able to filter data in the widgets ?
