### ISSUE TITLE
Alarm if device in inactive / doesn't send new data

### ISSUE THREAD

**Issue by Poquaruse** [thingsboard/thingsboard#319]
Hi,

is there a way to create an alarm which is active if a certain device hasn't sent new data for a defined amount of time (e.g. the device is inactive for too long). Sometimes, sensors disconnect without us realizing immediately and that would be a way to prevent this...

Best regards

**Comment by ashvayka** [comment]
This is planned to v1.4 release. There is also an issue for this somewhere in the history

**Comment by Poquaruse** [comment]
Great, thanks for letting me know!
