### ISSUE TITLE
[Question] Programatically set Widget size

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3191]
Hi,
Is there a way to programatically set the widget height and size ?

I know TB uses gridster for layout and when i `console.log(self.ctx.dashboard.gridsterOpts)` i can see multiple options.
i`ve digged through the gridster documentation for each and no matter what i inject directly into the DOM it is completely ignored by widgets.

I would also love to set mobile widget height to something bigger then 10 and it is not happening even if i directly inject it in the widget code ( i need it as my widget as in actuall application that is being cut in mobile view  as it needs more then 10 point for height)

I can get current widget height and width from API as documented but how can i set it to a desired value ?

Any idea ?

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.0.1 CE
 * Browser: Chrome

**Comment by amizer12** [comment]
I`ve found a REALLY HACKY way to do it - i get the height of two divs of my custom widgets, sum them up and then set the height attribute of the widget div in DOM, i also do the same in 

`on.Resize`

```
vueh=clientHeight+clientHeight2+32
xx=document.getElementsByClassName("tb-widget")[0]
xx.style.height = vueh+'px';
```

**Comment by yogamuliawan** [comment]
I've found a tricky way to do it by changing the height via xpath address

Use below function to get the Element and set the height using `style.property = value`

```
getElementByXpath = function(xpathfullpath) {
  return document.evaluate(xpathfullpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}
```

Goodluck Guys! 😊
