### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by zhoushuntong** [thingsboard/thingsboard#3192]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
compile the source failed

**Environment**

 * OS:  win10
 * ThingsBoard: latest
* Browser: name and version

[INFO] Thingsboard ........................................ SUCCESS [  1.979 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  3.790 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.336 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  7.101 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.827 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  4.179 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  1.526 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  1.303 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 16.532 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.105 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  2.212 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  2.299 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.072 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.349 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  2.350 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.088 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.862 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 13.815 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  8.800 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.150 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [ 28.267 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:42 min
[INFO] Finished at: 2020-07-29T21:36:15+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.thingsboard:gradle-maven-plugin:1.0.10:invoke (default) on project http: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://serv
ices.gradle.org/distributions/gradle-6.3-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf org.thingsboard.transport:http

**Comment by sadran** [comment]
I have got the same failure in thingsboard compilation. have you found any solution ?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
