### ISSUE TITLE
ESP8266. the graph in the dashboard is not drawn in real time

### ISSUE THREAD

**Issue by NazarDiadiun** [thingsboard/thingsboard#3193]
I don't understand what happened. My sketch worked fine, but something strange has started happening recently. Data is sent from ESP8266 and comes to the dashboard. But the realtime function seems to be not available. I need to reload the page to see the data just arrived. Also, the RPC commands stopped reaching the ESP8266. I tried to load the sketch from the guides, however, even there, in the serial port, it is not visible that I switched the switch. Is this a problem on the thingsboard ?

**Comment by Karabiy** [comment]
please, specify whether you are using the live demo environment of the ThingsBoard or you are using the on premises installation
in case if you are using the on premises installation, please, specify the exact version of the ThingsBoard you are using 
To have the check of the version you may refer to the (PE only) white labeling → white labeling → show platform name and version or, in case if you have ssh access, you can use the (is okay with both CE and PE) “ dpkg -l thingsboard “ command to check the version.
also check the device connectivity and whether there are no issues related to the network

**Comment by NazarDiadiun** [comment]
Thanks for answering!

I am using a live demo, there are no problems with connecting the device. As I already wrote - Data is sent and I can see it, but only when I reload the page. When I rebooted it earlier, the setGpioStatus command came to me on ESP8266, now it does not come. I tried a few sketches and they all worked a few days ago.

**Comment by Karabiy** [comment]
can you specify the email you are using to login to the live demo, so that we can check the issue of yours

**Comment by NazarDiadiun** [comment]
Nazardiadiun@gmail.com

Thanks in advance!

**Comment by chendrix4** [comment]
I'm having the same issue with ESP32/DHT22 tutorial on the live demo. I must manually refresh to see new data, and setGpioStatus widgets timeout every time.

My account is cdhendrix0207 [at] gmail [dot] com.

**Comment by csimena** [comment]
I'm also having the same issue on Mac OS with Safari!

**Comment by NazarDiadiun** [comment]
> can you specify the email you are using to login to the live demo, so that we can check the issue of yours

Hello! Still no solution to this problem? It still doesn't work as it should.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
