### ISSUE TITLE
[Bug]  "Requested item wasn't found!" response while creating a device with API

### ISSUE THREAD

**Issue by JuliusHarald** [thingsboard/thingsboard#3200]
**Describe the bug**
I want to create a device in Thingsboard using the API. I am pretty sure it already worked, but now I am getting the response: 
{"status":404,"message":"Requested item wasn't found!","errorCode":32,"timestamp":"2020-07-30T09:31:23.798+0000"}

**Your Server Environment**
I am using Thingsboard 2.5.2 ( also tried 2.5.1 and 3.0.1 same result) CE

**To Reproduce**

curl -v -X POST -d @create-device.json http://DOMAIN:PORT/api/device --header "Content-Type:application/json" --header "X-Authorization:Bearer eyHaFij..."

The Json:
{ 
	"id": {
		"entityType": "DEVICE",
		"id": "137bf660-d24c-11ea-a20d-bb6c95c6b641"
	}, 
	"name": "API Device II",
	"type": "Impl ServerSeitig"
}

UUID is Version 1

**Expected behavior**
Creating a device with given name, type and id

**Comment by yosry95** [comment]
I am encountering the same problem.

**Comment by marinovdh** [comment]
Same issue here when creating an alarm via the API. It looks like **creating** an object with an id is not allowed. Defining an id results in a lookup for the object with that id and results in a 404 not found error. 

Removing the id works in my case, but I actually want to specify the UUID myself. Is there any way to distinguish _create_ and _lookup_ calls? Or should _PUT_ calls also be supported for this?

**Comment by SuminDenis** [comment]
Hi, it's normal behavior referring to swagger documentation 
![image](https://github.com/thingsboard/thingsboard/assets/63262257/0d41a31c-6f78-4536-8817-d285428dfe81)

**Comment by epalchenko** [comment]
close due to inactive
