### ISSUE TITLE
how to assign a device to multiple customers

### ISSUE THREAD

**Issue by fredriclim** [thingsboard/thingsboard#3202]
In thingsboard CE, I have add a device A, and need to assign device A to specific customer A and customer B. So, when logging to customer A or customer B, i can see the device A.

But, it look like only allow to assign a device A to a customer.

Any idea? thanks.

**Comment by Nadou14** [comment]
@fredriclim if you want to do it dynamically you can easily create a rule chain, there's a node in Action named assign to customer, to learn more how to configure your rule chain you can refer to thingsboard documentation : https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#assign-to-customer-node

**Comment by Karabiy** [comment]
for the Community Edition there is no inbox option for those, though, you can make the dashboard public, or create the third customer, who will have this device and have those being inserted as an iframe. Or you can develop those on your side. 
as for the Professional Edition, those can be done using the roles functionality, so that you can provide the permissions for the access to the entities you want to share

**Comment by Buhaw85** [comment]
Has anyone create a rule cain to assign customers to multiple devices?

**Comment by invis2912** [comment]
There's a unique way to assign sensor to multiple customers without creating Rule chain in Professional Edition. I have no idea on Community Edition.

Let's say you have device assigned to customer A, you want customer B and C to have access to same device data on their own dashboard.

Step 1: Go to Customer Hierarchy -> Customer A -> Device Groups -> All 
Step 2: Click on Entity Group Details in edit option at All: Devices.
Step 3: Go to Permissions. Click on add permissions.
Step 4: In the pop-up, Role : Entity Group Read-only User, User group: Customer B, Select user group: All (Note: You can select customer users as well)
Step 5: Save. Now you can have access to data of devices in Customer A to Customer B.

Repeat same for Customer C. Now, you can see the data of Customer A devices in the dashboard of Customer B and C.
