### ISSUE TITLE
[Question] "HTTP Transport Service" building failed

### ISSUE THREAD

**Issue by dorafrodo** [thingsboard/thingsboard#3204]
**Component**

 * Bulid Error

**Description**
Hi, I used the command "mvn clean install -DskipTests" to build the source code of TB, but it always failed when it executed to "HTTP Transport Service". Below is the ERROR message. Is there anything I can do to solve this problem? Thanks!

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.1.0-SNAPSHOT:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.462 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  2.187 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.176 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  3.482 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.461 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.168 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  0.908 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.516 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  8.860 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.053 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.574 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.770 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.805 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.007 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  1.884 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.066 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.660 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  9.132 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  6.368 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.041 s]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [  2.778 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.997 s
[INFO] Finished at: 2020-07-31T16:02:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.thingsboard:gradle-maven-plugin:1.0.10:invoke (default) on project http: org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf org.thingsboard.transport:http

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.1.0-SNAPSHOT

**Comment by Hardikrathod01** [comment]
I have the same problem. OS: Windows 10 Thingsboard: release-3.1

**Comment by XW-Zhaochen** [comment]
I got the same problem on Windows 10 release 3.0

**Comment by periatrubikx** [comment]
I'm encountering the same! Any leads please? I m on a mac os with open-jdk-15.

**Comment by okancvlc** [comment]
you should use java 11

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
