### ISSUE TITLE
Need help to start the Trendz Analytics CE

### ISSUE THREAD

**Issue by Shahul1983** [thingsboard/thingsboard#3205]
Getting the following error while executing net start trendz from CMD prompt in window 10

trendz>net start trendz
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

**Comment by Shahul1983** [comment]
Its resolved.

**Comment by Karabiy** [comment]
good to hear!

**Comment by durai83a** [comment]
Is community edition working properly

**Comment by yuliaklochai** [comment]
Hello,
In Trendz, there is no Community Edition like in ThingsBoard. However, we can offer you a coupon to test Trendz Analytics for 30 days.
You can find more information here:
https://thingsboard.io/pricing/?section=trendz-optionsTrendz
For more detailed information, please feel free to reach out to the Trendz Analytics account manager ([dmatvienko@thingsboard.io](mailto:dmatvienko@thingsboard.io)), who can provide you with a comprehensive explanation of the licenses and subscriptions that Trendz can offer.
Thank you for considering Trendz Analytics, and please don't hesitate to contact us for further assistance.

**Comment by yuliaklochai** [comment]
Also, we`d like to add that you can always connect Trendz to the ThingsBoard Community Edition. You can find the installation guide here, just choose your installation options:
https://thingsboard.io/docs/trendz/install/installation-options/
And if you`ve already tried to install Trendz, let us know at what step you have faced difficulties.

**Comment by durai83a** [comment]
I've already installed thingsboard community edition using docker and if I
install trendz either using docker or choosing cent os will it integrate I
want to do trial and want to see what are the things that you offer.
