### ISSUE TITLE
[Question] How to navigate to a new dashboard state by clicking on row and add new widget for each device on ThingsBoard

### ISSUE THREAD

**Issue by Nadou14** [thingsboard/thingsboard#3206]
**Component**

 * UI
 * Rule Engine
 * dashboard state
 * Generic

**Description**
I've created a widget card which contains multiple devices, and I've added an action to navigate to a new dashboard by clicking on a row, I want for each dashboard to create diffrent widget, the problem is when I create a widget it's the same for all the device dashboard state, even though I try to modify it, then the other widgets got modified too, I don't know if it's a bug from the platfom or not. please can anybody help me with this.

**Environment**

 * ThingsBoard:  CE version 3

**Comment by Delapouite** [comment]
Hello. Do you use a unique title for each widget?

**Comment by Karabiy** [comment]
please, specify whether you have used the dashboard import option for those
