### ISSUE TITLE
RestClient 3.1.0 |  getTimeseries() | Map has no value for 'limit'.

### ISSUE THREAD

**Issue by Sascha1993** [thingsboard/thingsboard#3207]
**Describe the bug**
Fetching Telemetry Data from the past with the RestClient of "3.1.0-SNAPSHOT" causes an IllegalArgumentException: Map has no value for 'limit'.

//In order to fetch the telemtry data of one specific device I use the PageLink data structure as follows:
RestClient client = new RestClient(url);
client.login(username, password);
PageLink telemetryLink = new PageLink(100, 0); // fetch Page of index 0 with 100 entities
//Furthermore, I use two longs for the unix-encoding of the time frame as following:
fetchPastTelemetry(client, telemetryLink , 1595348075085L, 1595378375285L);
//Afterwards I use the getTimeseries()-Method for fetching the telemetry data with the following parameters:
private static void fetchPastTelemetry(RestClient client, PageLink link, long begin, long end) {
TimePageLink timeLink = new TimePageLink(link, begin, end);
UUID uuid = UUID.fromString("d3f033c0-b55a-11ea-b4ad-47e5929eed78");
Device device = client.getDeviceById(new DeviceId(uuid)).get();
List keysPerDevice = client.getTimeseriesKeys(device.getId());
Aggregation agg = Aggregation.AVG;
long interval = 6000; // in milli
client.getTimeseries(device.getId(), keysPerDevice, interval, agg, timeLink).forEach(tsKvEntry -> System.out.println("Key: "+ tsKvEntry.getKey()+ " time: " + tsKvEntry.getTs()+ " value: "+ tsKvEntry.getValueAsString()));
}

**Your Server Environment**
demo.thingsboard.io
<img width="121" alt="thing_version" src="https://user-images.githubusercontent.com/60472761/89033209-99305e00-d336-11ea-9452-503e3fa5134b.PNG">

**Your Client Environment**
Win10
JDK 8
Maven 3.6.3

* Connectivity
   HTTP/ Rest

**To Reproduce**
1. Download branch: https://github.com/thingsboard/thingsboard/tree/release-2.5
2. Maven build in root: mvn clean install -DskipTests
3. Create Account on demo Tenant
4. Add dependencies in pom: 
&lt;dependency>
&lt;groupId>org.thingsboard&lt;/groupId>
&lt;artifactId>rest-client&lt;/artifactId>
&lt;version>3.1.0-SNAPSHOT&lt;/version>
&lt;/dependency>
&lt;dependency>
            &lt;groupId>org.thingsboard.common&lt;/groupId>
            &lt;artifactId>data&lt;/artifactId>
            &lt;version>3.1.0-SNAPSHOT&lt;/version>
&lt;/dependency>

5. run in Eclipse 

**Expected behavior**
Receive a List of tsKvEntry-data structure.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/60472761/89034021-6a1aec00-d338-11ea-95da-12badd9ea032.png)

**Comment by DavidBoman** [comment]
Hi all, 

I'm getting hit by this as well. Would love to get a fix for this before the next release if possible. I would like to chip in and create a pull request but unfortunately I'm having trouble building the Thingsboard project right now for multiple reasons...

**Comment by Sascha1993** [comment]
Hei David, 
feel free to use my Bearer-Auth code:

StringBuilder endpoint = new StringBuilder(url);
endpoint.append("/api/plugins/telemetry");
endpoint.append("/DEVICE");
endpoint.append("/" + deviceId);
endpoint.append("/values/timeseries?limit=" + String.valueOf(requestAgg.getLimit()));
endpoint.append("&agg=" + requestAgg.getAgg());
endpoint.append("&keys=" + keys.stream().collect(Collectors.joining(",")));
endpoint.append("&startTs=" + String.valueOf(requestAgg.getBegin()));
endpoint.append("&endTs=" + String.valueOf(requestAgg.getEnd()));

URL ressource = new URL(endpoint.toString());
HttpURLConnection conn = (HttpURLConnection) ressource.openConnection();
conn.setRequestProperty("X-Authorization", "Bearer " + token);
conn.setRequestProperty("Content-Type", "application/json");
conn.setRequestMethod("GET");
try (BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
String output;
StringBuffer response = new StringBuffer();
while ((output = in.readLine()) != null) {
response.append(output);
}

**Comment by YevhenBondarenko** [comment]
Hi,
we have already fixed this and these changes will in the next release.
