### ISSUE TITLE
[Question] there is a way to create sounds alerts and popups in dashboards?

### ISSUE THREAD

**Issue by juanesteban1403** [thingsboard/thingsboard#3209]
Hi!, I am working in a project where it needs to have sound alerts and popups. I do not know if it is possible to do it by development widget. Has anyone made it possible?

**Comment by dhaval2017** [comment]
when you like to have sound and popups?

**Comment by juanesteban1403** [comment]
Hi, thanks por answer me.

The situation is very simple, if you are in a monitoring Center, and you
have to pay attention to a different process it is easier when the
platform shows a popup for example if a thermometer exceeds 30 degrees, It
can be bounded by alarm or just a simple event coming from the rule chain
but showed in dashboard.

**Comment by davidjovanny** [comment]
Hi Juanesteban, do you find a way to do this? I am looking for a similar solution. Thanks a lot

**Comment by dhaval2017** [comment]
@juanesteban1403 @davidjovanny 
With custom widget you both can achieve your solution
here is map library used by thingsboard 
https://leafletjs.com/

**Comment by davidjovanny** [comment]
Hi dhaval2017 thanks for your answer, I have tried to do with the alarm widget, but I can´t find a way to link the alert signal with the sound popup, I am sorry I am not an expert with Thingsboard or Java, could you be a little bit specific please? or maybe do you have an example to learn? thanks a lot for your time. Regards

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
