### ISSUE TITLE
[Question] Back button in dashboard

### ISSUE THREAD

**Issue by jwholme2** [thingsboard/thingsboard#3210]
**Component**
 * UI

**Description**
I have a dashboard that allows a drill-down by clicking on a device in a table. I tried implementing an HTML widget that has an action to update the dashboard to the default, but it does not work. Any suggestions are appreciated!

![image](https://user-images.githubusercontent.com/5523336/89055247-12748480-d328-11ea-85eb-1a41111025eb.png)

**Environment**
 * ThingsBoard: 2.4.3PE

**Comment by t0mmyz7** [comment]
please paste your html code
