### ISSUE TITLE
[Question] Thingsboard demo does not update temeletry data

### ISSUE THREAD

**Issue by engfei** [thingsboard/thingsboard#3214]
Hi, I have trouble getting both device telemetry data and dashboards updating real time. But when I refresh the page, the data is updated on both device telemetry data and dashboards. How to resolve this?

it also prompted me 
"504 Gateway Time-out"

**Comment by vvlladd28** [comment]
Hi @engfei,
Please recheck this problem, because this not reproduce at me.

**Comment by engfei** [comment]
Hi @vvlladd28 

Things are getting back normal this morning without doing anything. Thanks

**Comment by TanCans** [comment]
Hey, i am having the same problem since a couple of days, do you know how to solve it or what can be the problem?

**Comment by ahsan2882** [comment]
Does this happen with the paid version as well?
