### ISSUE TITLE
Thingsboard Custom Image Folder

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3216]
Hello !
I want to use in Thingsboard my custom images for devices and for assets.
Please tell me in which folder should I place these custom images in order to be loaded from there by Thingsboard.
Does Thingsboard have such folder ?
Thank You !

Environment

OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

**Comment by amizer12** [comment]
I`m in the same boat - i`m loading now images from external sources but it messes up my performance - i think those files are packed inside compiled jar file.
I`ll try to compile from source and add images to it and see if that works.
If that`s the case then maybe there is a way to imprt local files into the webpage via JS somehow ?

**Comment by lmax25** [comment]
Sorry !
Still not found any solution yet except the external link image...

**Comment by Ultrazombie** [comment]
Closed, as not active.
