### ISSUE TITLE
[feature] flow-based alarm editor

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#322]
Hi

I'd like to suggest creating a code-free or flow-based (node-red style) editor for creating alarms.

I cannot ask my end-users or even integrators to follow such complex instruction set for alarms.

https://thingsboard.io/docs/samples/alarms/basic-rules/

IMO it should be a much simpler process visually.

If you are considering this I'd be happy to provide more insights.

**Comment by fotis400** [comment]
This would be awesome! Definitely a good idea (although I bet this is not trivial to implement).

I would like to add that such a feature would also be very useful for combining the telemetry and RPC communications. We could make a firmware for the devices like firmata, and implement all the logic on the server side, on a simple editor.

**Comment by t0mmyz7** [comment]
Maybe there is some open source package that can be implemented here, or even Node-Red itself perhaps?

In other platforms that I use, the workflow engine is used to achieve almost everything, from applying calibration equation on incoming raw data, to triggering alerts, sending notifications, storing the data in new variable and more and more.

sO I think that ThingBoard is due to have something of this sorts. Because much of the functionality of this platform is actually pretty straightforward.

Looking forward to getting others to lay in on this :)

**Comment by ashvayka** [comment]
Hi Guys, 

This is quite valuable feature but is also challenging to implement. We have this in mind for a long time. The TB v1.4 will be an initial phase of rule engine refactoring to support more complex use cases. We may include some basic building blocks for this, but it will take two or three minor releases to evolve. 

Few features I have in mind for refactoring:
1) Filters should be chained for performance reasons. The event should be passed between the filters and other components. Output of one filter may be yes/no and should follow different processing chains.
2) Multiple actions may be applied to one result of filtering
3) Action may produce multiple other events that will be pushed in front of processing queue and will be processed independently. 

At the moment we don't have much resources to allocate a dedicated engineer for this, but this is obviously important topic for TB evolution.

**Comment by t0mmyz7** [comment]
Hi

This feature still very relevant :) Integrating node-red inside thingsboard or alongside, for rules engine would be awesome. I saw another SaaS portal in the vertical of RTLS, proximi.io has done just that. 

https://proximi.io/features/#actionflows

maybe it will serve as some inspiration

**Comment by vparomskiy** [comment]
Not valid anymore. Since ThingsBoard v2.x. specific Rule Nodes should be used for creating alerts.
Here are few guides that show how to do this:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/
