### ISSUE TITLE
[Bug] /api/customer/{customerID}/devices?   doesn't work anymore

### ISSUE THREAD

**Issue by faithware** [thingsboard/thingsboard#3226]
Apparently with the tb3.0.1  the calling  /api/customer/{customerID}/devices? doesn't work anymore.
Whould you please check it out guys

**Comment by vvlladd28** [comment]
Hi @faithware,
This call work at me! http://cloud.thingsboard.io/api/customer/{customerID}/devices?pageSize=10&page=0, 
You need adde two query parameters  pageSize and page.

**Comment by faithware** [comment]
Thanks @vvlladd28  
Can you point out where i can find this in the source code?
Bests

**Comment by Karabiy** [comment]
https://github.com/thingsboard/thingsboard/blob/master/rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
1026 row, getCustomerDevices method

**Comment by vvlladd28** [comment]
Hi @faithware,
ThingsBoard REST API may be explored using Swagger UI: http://demo.thingsboard.io/swagger-ui.html#/
