### ISSUE TITLE
[Bug] getEntityTimeseriesValues missing from attributes service

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3229]
Hi,
`getEntityTimeseriesValues `is missing form attribute service, there is no way to get telemetry data for device via attribute service anymore.
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts

![image](https://user-images.githubusercontent.com/55321188/89200064-c8053900-d5af-11ea-880d-2d56983c8fe1.png)

**Your Server Environment**

TB 3.0 AWS hosted

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Win10
* Browser :Chrome

**Comment by ban2derlog** [comment]
Hi, is this persist on latest ThingsBoard version?
