### ISSUE TITLE
[Question] How can i request rest api in customer widgets?

### ISSUE THREAD

**Issue by Bruce1221** [thingsboard/thingsboard#3239]
**Component**

 * Widgets

**Description**
Is there any way to request rest api in customer widgets?
I want to get some data from my fastAPI server,But some wrong comes,looks like
![image](https://user-images.githubusercontent.com/52122620/89390431-493c0780-d739-11ea-8d3f-d370112bfcb5.png)

**Environment**

 * OS:  Centos7
 * ThingsBoard: 3.0.1

**Comment by Delapouite** [comment]
It looks like you're getting a CORS issue, which is not directly connected to Thingsboard itself, but more a general issue about letting your client served on one domain accessing another one through XHR: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Bruce1221** [comment]
Thank you.
It's my config of api server problem.
I already fix it.
