### ISSUE TITLE
[Feature Request] Add a new Azure Event Hub external rule-chain node

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3241]
Hello

Thingsboard currently offers the following external nodes:

![image](https://user-images.githubusercontent.com/39315/89397166-c8b4e100-d70f-11ea-85df-d827c8286b6a.png)

They are great because they allow to easily push events to two famous cloud providers which are:

- AWS with the SQS and SNS nodes
- GCP with the pub-sub node

To complete the trio, we need a similar rule-chain node to push events to an [Azure Event Hub](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about). This new node configuration would let the user enter SAS Tokens or Connection Strings.

**Note**: I'm aware that there's already an official integration called "Azure Event Hub": https://thingsboard.io/docs/user-guide/integrations/azure-event-hub/ and we could potentially use an `integration downlink node` in the rule-chain to push events.

Unfortunately this integration is convoluted as it put an Azure Iot Hub into the mix, which is totally unrelated to the simple task I described.

**Comment by YevhenBondarenko** [comment]
Hi @Delapouite, unfortunately, we do not planed to add this rule node to 3.1 release, but we will do our best to add this feature in future releases.

**Comment by ban2derlog** [comment]
Hi, this nodes already added on latest version of ThingsBoard.
![image](https://user-images.githubusercontent.com/33271053/175103811-6a06720d-c478-47b1-ac5a-51596faf064f.png)
