### ISSUE TITLE
[Question] How to deploy TB using microservice and multiple host machines

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3249]
Hi, is there any documentation on how to run TB using microservices in multiple machines?
I only see "Docker configuration for ThingsBoard Microservices" example, but is with only one host machine. Where can I specify the IP address of each machine?

Thanks

**Comment by CooL16** [comment]
@fjpa121197 to perform that you need an external kafka, zookeeper and redis services.
Then you have to set the Ip of a common zookeeper and kafka services (so to them can connect ThingsBoard and they will be able to communicate with each other)
you can set the propper properties within tb-node.env, queue-kafka.env fileы.
As well you have to comment out all settings that relates to tb-core2 on one machine, and all settings that relates to tb-core1 on the second machine. (this settings located within docker-compose.yml files)

**Comment by trypzz** [comment]
closed due to inactivity.
