### ISSUE TITLE
Aggregated stream data not resetting in dashboard after the specified time interval[Bug] 

### ISSUE THREAD

**Issue by MercuryToNeptune** [thingsboard/thingsboard#3252]
**Describe the bug**
I am using a stream aggregation node to sum my incoming data for a specified time interval. After completion of this time interval, widgets are retaining the same data as in previous interval if no new data is sent. Only when new data is sent from the device does the widgets update.

**Server Environment**

* own setup
  * Local infrastructure
  * ThingsBoard Version: 3.0.1

**To Reproduce**
1. Add a stream aggregation node and specify a small interval.
2. Send data from the device to thingsboard once in first interval.
3. Wait for the interval to finish.
4. Previous data is still displayed if no new data is sent. 

**Expected behavior**
Widgets must reset to zero if there is no new data for the new time interval.

**Comment by Ultrazombie** [comment]
Closed, as not active.
