### ISSUE TITLE
[Bug] data converter code frequently lost

### ISSUE THREAD

**Issue by jskillen** [thingsboard/thingsboard#3257]
**Describe the bug**
When I *initally* save my data converter it appears to work fine. If I subsequently edit the data converter, the updated code is frequently reverted to the initial code after a save. When I re-open the data converter it shows the old code.

**Your Server Environment**

* own setup
  * Azure Cloud
  * ThingsBoard 3.0.1 PE
  * Ubuntu Linux 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Mac OSX Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.105

**To Reproduce**
1. Create a data converter. Save and close it.
2. Re-open the same data converter. Update the code and save it.
3. Open the same data converter again. See that the code is the same as it was in step 1.
4. Tear out hair in frustration.

**Expected behavior**
The data converter should have the updated code, not the code that was entered initially.

**Comment by jskillen** [comment]
Two follow-ups to this:

1. This seems to happen when I navigate away from the data converters and then return.
2. **IMPORTANT** I have discovered that *even though it is displaying my data converter code* when I open the panel, the system is *actually running the SAMPLE converter*, as seen in the debugging results!

This has rendered my ability to deliver any sort of solution impossible.

**Comment by yefimov-andrey** [comment]
This issue was fixed in v.3.1.0.
 Anyone encountering it as a workaround needs to create a downlink converter for every integration on their instance (even if you don't push any data downlink). The default one will work fine.

**Comment by Karabiy** [comment]
> This issue was fixed in v.3.1.0.
> Anyone encountering it as a workaround needs to create a downlink converter for every integration on their instance (even if you don't push any data downlink). The default one will work fine.

or you can just fully recreate the converter

**Comment by jskillen** [comment]
@yefimov-andrey @Karabiy 
Thanks for the reply.

I'm not sure that I was clear in my initial statement about this bug. It is not that there *has* to be a converter. 

I will try to be more precise with these 2 points:

- The data converter code shown in the editing screen does not always reflect the data converter code that was saved.
- The data converter code that run by the integration is not always current to the code that was saved.

My workaround is that I have to create a new converter *every time* I make a change. Furthermore, I have to update the integrations that use said converter.

Given the bug I noted [here](https://github.com/thingsboard/thingsboard/issues/3099), I also have to re-set every HTTP integration because changing the integration does *not* trigger the event to enable saving the integration.

In view of all the above, @yefimov-andrey, are you saying these issues will be fixed in 3.1.0? When can we anticipate a release?

**Comment by Karabiy** [comment]
the 3.1 is released, those may not persist
