### ISSUE TITLE
Telegram with negative chat id not working

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3258]
I successfully send telegram with positive chat_id but impossible with negative chat_id. Pls help me check!
![Error](https://user-images.githubusercontent.com/7521909/89613893-7dd0d000-d8ad-11ea-915b-0b7713ca9b05.png)

**Comment by Karabiy** [comment]
have you checked your bot? is everything okay on its side?

**Comment by anhdv1979** [comment]
Yes. I use curl and it sends OK but could not send from rule chain (with negative)

**Comment by fatimazahrasifer** [comment]
@anhdv1979 i have the same problem , did you fixed the issue ?
