### ISSUE TITLE
[Question] Using shared image attribute as image map background

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#3260]
**Component**

 * UI

**Description**
I want to use the widget "Update shared image attribute" to import a floor plan. This part works well, the image is stored base64 encoded as shared attribute. I can copy the content of the attribute and paste it to a browser and the picture is displayed again. 

Then I want to use this picture as a background in the input widget: "Markers Placement Image Map". Where I have two possibilities for an entry: 

1. Image URL source entity alias
2. Image URL source entity attribute

I assumed to put ${corresponding_attribute} in the second field and thats it. But it did not work. 

Am I missing a point, how can I import the "image attribute" as a background in the Markers Placement - Image Map input widget. 
![Markers Placement Image Map](https://user-images.githubusercontent.com/45274753/89664250-28a9b400-d8d7-11ea-8cb0-bf92dd7f8023.png)

**Comment by ChantsovaEkaterina** [comment]
Hello,
To make this work you should fill out both fields: source entity alias and source entity attribute. Entity alias should contain a corresponding entity that has the image attribute.

**Comment by ThomasBaumgartner** [comment]
Thank you very much @ChantsovaEkaterina if I enter both entity alias and the corresponding image attribute it works. 👍 

Anyway I do not understand the reason why one needs to enter the entity alias, since the relation to the entity alias is already defined in the datasource.

**Comment by ChantsovaEkaterina** [comment]
@ThomasBaumgartner  This made for the case if someone wants to use another entity's attribute, that isn't specified as a widget datasource.
