### ISSUE TITLE
[Question] How do you use the AngularJS getCustomerAssets method?

### ISSUE THREAD

**Issue by samf48** [thingsboard/thingsboard#3262]
**Component**
 * UI
 
**Description**
I'm attempting to get a customer's associated assets in a UI widget using:

    
```
assetService = $injector.get('assetService');

currentUser.customerId = "4613ccc0-5906-11ea-880d-a3f39e11edea";
assetService.getCustomerAssets(currentUser.customerId,1,1,1,1).then(
    function(assets) {
        console.log("assets: ",assets);
    });
```

but I'm getting the error:

`Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "undefined"`

I can see the HTTP GET API call in my browser console output as:
` https://website.domain:8080/api/customer/4613ccc0-5906-11ea-880d-a3f39e11edea/assets?limit=undefined `

Evidently I'm passing the "limit" parameter incorrectly or otherwise using that method wrongly.  How do you use the getCustomerAssets method?

**Environment**

 * OS:  Windows Server 2016
 * ThingsBoard: 2.4.3
 * Browser: Chrome 84.0.4147.105

**Comment by Delapouite** [comment]
Hi. Have a look at the definition of the `getCustomerAssets` function: https://github.com/thingsboard/thingsboard/blob/develop/2.5.3/ui/src/app/api/asset.service.js#L192-L226

The signature is : `getCustomerAssets(customerId, pageLink, applyCustomersInfo, config, type)`

Where `pageLink` is an object with fields like `limit`, `textSearch`, `idOffset`, `textOffset`…

**Comment by samf48** [comment]
That was it @Delapouite , thanks a lot.
