### ISSUE TITLE
Request Timeout every time. What happened ?

### ISSUE THREAD

**Issue by NazarDiadiun** [thingsboard/thingsboard#3263]
Hello!
Every time I enter the dashboard, I get a request timeout on the widget. The request for ESP8266 does not come, so I cannot answer. When I try to manually send data for the widget, it does not respond to them. The problem arose just under two weeks ago. Before that, everything was fine.

Mac OS X, ESP8266-01

**Comment by Karabiy** [comment]
what's in the rule engine processing to be set, does the "send rpc call" rule node being set there? Is the device being already connected?

**Comment by Karabiy** [comment]
does the issue persists?
