### ISSUE TITLE
[Question] How to choose descending sort order in dashboard Device Admin Table widget's advanced form's Default sort order field

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3265]
**Component**

 * UI

**Description**
I specified lastAcitivityTime in Dashboard->Widget->Device admin table->Advanced->Default sort order. That seems to be working. How can one specify descending order along with name? Default seems to be ascending and I have to click to choose descending every time I open the dashboard.

**Environment**

 * OS:  Ubuntu LTS 18.04
 * ThingsBoard: 3.0.1
 * Browser: Chrome

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can do this by adding the " - " sign before the attribute name specified as default sort order.

**Comment by ashvarma-git** [comment]
Thank you for the answer. Please add ii to documentation. It was also not obvious that one could simply specify a device attribute there, since no drop list is offered to make a selection like in many other form fields. I just found out by chance.
