### ISSUE TITLE
[Bug] Bulk provisioning from CSV doesn't work unless CSV has exactly 3 columns name, type, access_token AND exactly in that order

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3266]
**Describe the bug**
I tried to do bulk provisioning (add new devices) using CSV. I initially had columns name, label, type in that order. It is mentioned in all your documentation and videos that the minimum required is name and type. But actually what is happening is that unless you have just 3 fields - name, type, access_token - AND exactly in that order - the CONTINUE button remains greyed out.
I found this out by trial and error several times - that all 3 columns are needed and specifically in that order.

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard Version 3.0.1
  * OS Name and Version Ubuntu LTS 18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Mac OS X
* Browser Chrome
* Version 84.0.4147.105

**To Reproduce**
1. Go to Devices screen
2. Click on '+'
3. Choose Upload
4. Select CSV file
5. Click CONTINUE
6. On Import configuration, deselect "First name contains column name", click CONTINUE
7. Assign Columns to corresponding attributes - I had columns name, type, label - but CONTINUE remains greyed out

**Expected behavior**
Minimum name and type is needed as per documentation. However, see the bug description for the issue.

**Screenshots**

**Additional context**

**Comment by vvlladd28** [comment]
Hi @ashvarma-git,
Thank you for the report. Coming soon we will fix this
