### ISSUE TITLE
[Question] Material Angular datepicker

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3274]
**Component**

* UI
**Description**

Could anyone help me advice how to add datepicker range inside a static widget ? I add but it shows blank.
Material Angular Datepicker Range https://material.angular.io/components/datepicker/overview

**Environment**

 * OS:  Ubuntu 20.04 lts
 * ThingsBoard: 3.01 PE
 * Browser: chrome and firefox

**Comment by belotesagar** [comment]
getting the same issue when I am adding angular material date picker in the latest value widget/time series widget.

OS: windows 10 pro
ThingsBoard: 3.01 PE
Browser: chrome and firefox

**Comment by ban2derlog** [comment]
Hi, is this still exist on latest ThingsBoard version?
