### ISSUE TITLE
Thingsboard tb-gateway stops to receive messages

### ISSUE THREAD

**Issue by DanielRichart** [thingsboard/thingsboard#3275]
**Component**

 * Generic

**Description**

I have Thingsboard and tb-gateway installed in an Ubuntu machine. It receives data from about 100 sensors and display them in a dashboard.
The tb-gateway receives the sensors' information via MQTT.
The problem is that, sometimes it **suddenly stops receiving messages**. When it does, i check the logs and see lots of lines with:

**[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress**

**If i remove the MQTT extension config file from the gateway device, restart the tb-gateway service and then put the MQTT config file back in the gateway device**, it starts to work again. Sometimes it also receive all the messages from the time it was down.

**Please, what can i do to prevent the tb-gateway to suddenly stop working like this?**

Thanks a lot,
Daniel Richart

**Environment**

 * OS:  Ubuntu 16
 * ThingsBoard: 2.4.2.1-1

**Comment by Karabiy** [comment]
please, try to create several connectors for the MQTT type and also make sure that the server host machine is an okay with the current payload of yours. also, specify the payload of yours

**Comment by DanielRichart** [comment]
Thanks for the answer.

I did some further research and apparently one solution for this problem is to make some modifications on the MqttMessageSender.java file, as seen in https://github.com/thingsboard/thingsboard-gateway/issues/106

**I can't find this file on my pc to try the modifications. any ideia where it is?**

Thank you,
Daniel Richart
