### ISSUE TITLE
What is the right way to enable MQTT ssl and connect device?

### ISSUE THREAD

**Issue by ahmedwahdan** [thingsboard/thingsboard#3278]
I'm working with thingsboard on Windows, editing some features and trying to enable MQTT SL.
I followed the steps related to enable SSL and generate the certificates, and I got the following error: 
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record
104c00044d5154540482000a003136386464366666612d343165322d346339362d383965302d62663233353034646665643131353937303930373638333735000d54325f544553545f544f4b454e

I removed all devices and still I get this exception.

**Comment by Karabiy** [comment]
you can refer to this link regarding the essentials of those. those should be an okay with the example of the configurations: https://thingsboard.io/docs/user-guide/mqtt-over-ssl/

**Comment by ahmedwahdan** [comment]
I already used these configuration, but still have this exception.

**Comment by Karabiy** [comment]
which os you are running on?

**Comment by ahmedwahdan** [comment]
Windows 10

**Comment by Karabiy** [comment]
i recommend you to test those with the clean ubuntu installation on the virtual machine, for example, because there lots of OS circumstances which may affect those

**Comment by Ktysai** [comment]
HI there!

I have a similar problem regarding TB Community edition 3.1.1

with NO SSL, I can acces the machine (UBUNTU 18 & TB CE ) from Win10 and from the Ubuntu itself.

With SL enable and the self signed certificate I still cannot connect. my error:

` File "one-way-ssl-mqtt-client.py", line 50, in <module>
    client.connect("localhost", 8883, 1)
  File "/home/linuxuser/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/linuxuser/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer`

Thanks!

**Comment by greg-mcnamara** [comment]
I'm having the same problem. I'm trying to do 2-way MQTT with SSL and the connection fails. I think it's a problem with the haproxy configuration, I think it needs to do an SSL passthrough on MQTT. Is there an example haproxy.cfg for this scenario? The documentation only shows SSL termination and then unencrypted to MQTT transport on 1883 (which will not provide device cert provisioning and 2-way as far as I understand).

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
