### ISSUE TITLE
Thingsboard PE blank

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3279]
Sometimes I have blank page when going with the URL. Pls help me check & give me some advices 
![image](https://user-images.githubusercontent.com/7521909/89861678-8c322b00-dbd0-11ea-99e0-77fe3b8c8577.png)

**Comment by Delapouite** [comment]
Hello. When saying "sometimes", do you mean it finally appears when you refresh the page ?

**Comment by anhdv1979** [comment]
Yes. I have to refresh

**Comment by anhdv1979** [comment]
Could anyone help me ? I think this is a bug from 3.0.1 PE version. In the pass I use 2.4.3 CE without this issue

**Comment by Karabiy** [comment]
make sure to clear the cache, so that those should not persists

**Comment by anhdv1979** [comment]
Clear cache in browser ? If so, sorry but I could not ask all of my customers to do like this. Any suggestion ? Pls help!

**Comment by zwells** [comment]
Any update on this? We're experiencing the same problem across all 3+ versions

**Comment by ban2derlog** [comment]
Please, clear cache for ThingsBoard page in browser.
This can happen after update if browser cache all page and try to load it partially from TB instance and from local cache.

In 3.2.1 version this was fixed finally.
