### ISSUE TITLE
[Question] RPC node "NO_ACTIVE_CONNECTION" error

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#3297]
**Component**

 * Rule Engine

**Description**
My RPC Call Request Node returned an error "NO_ACTIVE_CONNECTION". I am sure my device is connected to thingsboard, because I can receive telemetry data periodically. But when I send RPC call request to related device, the node occured an error.
![image](https://user-images.githubusercontent.com/31084798/90092826-8f5a2200-dd5c-11ea-84a9-418fd37b8df2.png)

`java.lang.RuntimeException: NO_ACTIVE_CONNECTION
	at org.thingsboard.rule.engine.rpc.TbSendRPCRequestNode.lambda$onMsg$0(TbSendRPCRequestNode.java:119)
	at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.lambda$sendRpcRequestToDevice$0(DefaultTbRuleEngineRpcService.java:109)
	at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.lambda$processRpcResponseFromDevice$1(DefaultTbRuleEngineRpcService.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Environment**

 * OS: Ubuntu18.04
 * ThingsBoard: 3.0.1
 * Browser: google chrome

**Comment by qwyinxiang** [comment]
Can you tell me, under what circumstances will report this error?

**Comment by Karabiy** [comment]
specify whether the related device is being connected to the ThingsBoard at that moment

**Comment by qwyinxiang** [comment]
I am sure the related device is connected to thingsboard. But the related device is not send telemetry data to thingsboard.
When I let my related device to periodically send data to thingsboard, the rpc sent by thingsboard to the device was also successful.
Thank you very much.

**Comment by nickymeng** [comment]
Any clue about this? I have the similiar issue

**Comment by Karabiy** [comment]
which exact device api you are using for those devices?

**Comment by djfil** [comment]
#2682
That's how far I got too!
I've been around this issue for over a week.
Unfortunately, the message never gets to the device, when sent from the rpc call request node on the rule-engine... BUT it is working from the dashboard widget.

To give a bit of more context :
I have setup a light sensor and a relay with a pair of esp32 wroom devkitc 4.
Objective is to have the relay light up whenever it gets to dark in the room. 
TB receives the telemetry from both devices which is presented in a dashboard, and I got to set a control widget that can trigger the Relay channels on and off.
But when setting a rule engine flow to send the RPC request I get the same behavior as @qwyinxiang  
I am using TB Postgres installed with docker. version 3.2.2

The flow:
{
  "ruleChain": {
    "additionalInfo": {
      "description": ""
    },
    "name": "Light Induced Switch",
    "firstRuleNodeId": null,
    "root": false,
    "debugMode": true,
    "configuration": null
  },
  "metadata": {
    "firstNodeIndex": 3,
    "nodes": [
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 1102,
          "layoutY": 615
        },
        "type": "org.thingsboard.rule.engine.filter.TbJsFilterNode",
        "name": "Check MSG Type",
        "debugMode": true,
        "configuration": {
          "jsScript": "return msgType == \"RPC message\""
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 1529,
          "layoutY": 644
        },
        "type": "org.thingsboard.rule.engine.rpc.TbSendRPCRequestNode",
        "name": "RelayControlAsset",
        "debugMode": true,
        "configuration": {
          "timeoutInSeconds": 30
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 545,
          "layoutY": 412
        },
        "type": "org.thingsboard.rule.engine.transform.TbTransformMsgNode",
        "name": "Create Command",
        "debugMode": true,
        "configuration": {
          "jsScript": "var newMsg = {}\nvar newType = 'RPC message'; \nvar newMeta = {deviceName: \"ESP32 SwitchControl\",deviceType:\"ESP32 blank\",ts:metadata.ts}\nnewMsg.method = \"setRelayStatus\"\nnewMsg.params = {channel:0,enabled:true}\nnewMeta.oneway = false;\n//newMeta.expirationTime = \"30\";\nreturn {msg: newMsg, metadata: newMeta, msgType: newType};"
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 254,
          "layoutY": 661
        },
        "type": "org.thingsboard.rule.engine.filter.TbCheckRelationNode",
        "name": "check relation",
        "debugMode": true,
        "configuration": {
          "checkForSingleEntity": true,
          "direction": "FROM",
          "entityType": "DEVICE",
          "entityId": "89674020-8a64-11eb-9d88-b9a83ec123f3",
          "relationType": "Uses"
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 277,
          "layoutY": 197
        },
        "type": "org.thingsboard.rule.engine.filter.TbJsFilterNode",
        "name": "resistance < 2000;",
        "debugMode": true,
        "configuration": {
          "jsScript": "return msg.resistance < 2000;"
        }
      }
    ],
    "connections": [
      {
        "fromIndex": 0,
        "toIndex": 1,
        "type": "True"
      },
      {
        "fromIndex": 2,
        "toIndex": 0,
        "type": "Success"
      },
      {
        "fromIndex": 3,
        "toIndex": 4,
        "type": "True"
      },
      {
        "fromIndex": 4,
        "toIndex": 2,
        "type": "True"
      }
    ],
    "ruleChainConnections": null
  }
}

metadata:
{
    "deviceName": "ESP32 SwitchControl",
    "deviceType": "ESP32 blank",
    "oneway": true,
    "ts": "1617363807316"
}
Data:
{
    "method": "setRelayStatus",
    "params": {
        "channel": 0,
        "enabled": true
    }
}
On the Relay device it subscribes like: client.subscribe("v1/devices/me/rpc/request/+");
I even have set the device to reply, but it actually never receives no message, so this was pointless.
This is true for both oneway true and false

**Comment by ban2derlog** [comment]
Hi, does this still persist on latest ThingsBoard version?

**Comment by djfil** [comment]
I have no idea. I went another way. It was over a year ago.
Thanks anyway

**Comment by noodzhan** [comment]
hello , i met this problem in v3.2.2 .
