### ISSUE TITLE
Unable to get active event on rpc request

### ISSUE THREAD

**Issue by GauravChoube** [thingsboard/thingsboard#3298]
Hi,
As per documents , whenever device request to thingsBoard it's generate the active event message on telemetry, attributes and rpc messages.

But I'm not getting any active event message on rpc messages request but it's generating on telemetry and attributes message.

I also tried to generate using rule chain but don't know to where to send after generate message.

I'm using demo version of thingsBoard and I generally want to active and inactive event of all devices that indicates that help me to process my application.

Please help me and suggest me if anything can do using rule chain.

**Comment by GauravChoube** [comment]
please some one respond me!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
