### ISSUE TITLE
Two records with the same ENTITY_ID, TS and KEY

### ISSUE THREAD

**Issue by alestmej** [thingsboard/thingsboard#330]
Hi,

I sent two measurements using postTelemetry API. Measurements was from the same device, with the same timestamp but with different values. In database I found 2 rows - one with old value and one with a new value!

Content of TS_KV_LATEST and TS_KV tables:

`ENTITY_TYPE		ENTITY_ID						KEY				TS				BOOL_V	STR_V	LONG_V	DBL_V`
`DEVICE			1e7a1f215a434d0b789ffecc4738788	StateOfCharge	1507298704304	<null>	<null>	<null>	0.12496066`
`DEVICE			1e7a1f2344abbc0b789ffecc4738788	StateOfCharge	1507298704304	<null>	<null>	777	<null>`

The reason is obvious - first value was interpreted as double and was written to DBL_V column, the second value was interpreted as long and was written to LONG_V column.

Expected behavior: When one device sends two different values with the same timestamp, the last wins - the old value is deleted and new value inserted.

Tested on TB revison: ec2bbbc25b2833420c9c26f2386bcad6bf79f7c8 using default configuration (HSQLDB).

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by alestmej** [comment]
Nice to see any reaction, but what to comment?
One device in one time has two different values for one telemetry attribute. See database tables TS_KV_LATEST and TS_KV above.

**Comment by ashvayka** [comment]
Hi @alestmej . I understand that this is definitely not a feature, but fixing this will introduce significant performance degradation for insert operations (especially in cassandra). For now I would like to suggest not to insert values of different types to same key for same device.

**Comment by vparomskiy** [comment]
This issue is already resolved in latest ThingsBaord version
