### ISSUE TITLE
[Bug] Unable to create a new device using the HTTP API

### ISSUE THREAD

**Issue by ChristofferHolmesland** [thingsboard/thingsboard#3301]
**Describe the bug**
POST /api/device returns 404 when using the same request message as we used for v2.1, but there are no changes in the swagger documentation that indicate any change in the expected input.

**Your Server Environment**
AWS t2.small
Ubuntu 18.04 LTS
Thingsboard 2.5.3

**Your Client Environment**
Windows 10
Python 3 with requests library

**Your Device**
HTTP API

**To Reproduce**
Send a HTTP POST request to /api/device to create a new device.

**Expected behavior**
Expected a new device to be created.

**Additional context**
JSON payload that works on v2.1
```{'createdTime': 0, 'name': 'Configuration2', 'type': 'Configuration', 'tenantId': {'id': 'b7596480-7323-11ea-9cf9-03786fc38564', 'entityType': 'TENANT'}, 'id': {'id': '35ce9227-dd66-11ea-a1ad-0c7a15b14fd0', 'entityType': 'DEVICE'}}```

JSON payload that doesn't work on v2.5.3
```{'createdTime': 0, 'name': 'Configuration2', 'type': 'Configuration', 'tenantId': {'id': '0969c620-dd5f-11ea-b842-6fcf8b56bb71', 'entityType': 'TENANT'}, 'id': {'id': '5a5b6902-dd66-11ea-935d-0c7a15b14fd0', 'entityType': 'DEVICE'}}```

**Comment by ChristofferHolmesland** [comment]
We get the same response when we add the ```?accessToken=``` parameter.

**Comment by ChristofferHolmesland** [comment]
The request works when the device id isn't sent from the client.

**Comment by Karabiy** [comment]
the device id is being set on service side, so that those would be properly generated.
