### ISSUE TITLE
[Question] How can I create a widget using existing Javascript bundle

### ISSUE THREAD

**Issue by imoon** [thingsboard/thingsboard#3305]
**Component**

 * UI
 * Widget development

**Description**
I want to create completely custom widgets but am stuck understanding how to implement an existing javascript bundle as mentioned here: https://thingsboard.io/docs/user-guide/contribution/widgets-development/#using-existing-javascript-code.

It is not clear how to do this. Where do I put the bundle? Does it need to be compiled? Does it have to be served via CDN? Is there a complete example or step-by-step guide?

**Environment**

 * OS:  AWS Marketplace AMI - Ubuntu
 * ThingsBoard: 3.1.0PE

**Comment by Ultrazombie** [comment]
Closed, as not active.
