### ISSUE TITLE
[Question] how to get jwt token for rest api when user is registered with oauth2

### ISSUE THREAD

**Issue by amir-hg** [thingsboard/thingsboard#3307]
**Generic**
Hi
i have a running keycloak server and i can register and login tenants through oauth2.
i want to use rest api. i need a valid jwt token.
i could get new jwt token with following command 

`curl -L -X POST 'https://<keycloak-server>/auth/realms/<realm-name>/protocol/openid-connect/token' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=client-id' --data-urlencode 'grant_type=password' --data-urlencode 'client_secret=xxxx-xxxxx-xxx-xxxx-xxxxxxx' --data-urlencode 'scope=openid' --data-urlencode 'username=username' --data-urlencode 'password=password'`

i use above jwt token with Bearer but i got following response

> {
  "status": 401,
  "message": "Invalid username or password",
  "errorCode": 10,
  "timestamp": "2020-08-14T06:22:08.392+0000"
}

i should mention that i can not get jwt token directly from thingsboard and i got the same error
how should i get a valid jwt token when users registered with oauth2?
thanks in advance

**Comment by ten2net** [comment]
I have the same problem. I don't know how to solve it? But what is puzzling is: Why did this problem close without any solution after it was reopened? I am eager to get official help.

**Comment by amir-hg** [comment]
Sorry it was my mistake that i closed without solution.
I reopen it and hopeful to get solution

**Comment by loelkes** [comment]
If I got it right ThingsBoard only accepts tokens from the `/api/auth/login` endpoint.  

Here's a workaround:

* Log in with your OAuth2 account.
* Set a password in the profile section. Your local account (linked to your Oauth2 Account) now has a password.
* Get a token from `/api/auth/login`.

**Comment by amir-hg** [comment]
@loelkes 
You are right
If i set a password to the profile (via thingsboard web ui), i could easily generate token
But i prefer get token without setting thingsboard profile password.
I want to get a token from api (documented on swagger ui).

**Comment by loelkes** [comment]
That also depends on our OAuth2 Provider and how Thingsboard implements it. If TB and your OAuth2 provider both support _Resource Owner Password Credentials Grant_ (Keycloak does) then TB can use your password to log in and retrieve an OAuth2 token. I suppose this must be implemented and a solution must be found if you have multiple OAuth2 endpoints registered.

Your question is answered, I would suggest closing this and opening a feature ticket explaining the required feature in detail and/or making a pull request.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by sirnino** [comment]
Is there any feature ticket related to this problem? I'm still facing the same issue in Oct 2023

**Comment by laurylloyd** [comment]
bonjour à vous, j'ose espérer que vous vous portez bien. J'ai un problème, j'arrive pas à intégrer les données de mon code python vers ma gmao thingsboard. Et voici mon code python : import paho.mqtt.client as mqtt
import json
import time

# Configuration de la connexion MQTT
THINGSBOARD_HOST = 'adresse_ip_serveur_ubuntu'  # Remplace par l'adresse IP de ton serveur ThingsBoard
ACCESS_TOKEN = 'TON_ACCESS_TOKEN'  # Token d'accès pour le dispositif (lampadaire) dans ThingsBoard

# Connexion MQTT à ThingsBoard
client = mqtt.Client()
client.username_pw_set(ACCESS_TOKEN)
client.connect(THINGSBOARD_HOST, 1883, 60)

# Fonction pour envoyer les données des lampadaires à ThingsBoard
def envoyer_donnees_lampadaires():
    # Exemples de données de lampadaires (température, état, luminosité, consommation d'énergie)
    donnees = {
        'temperature': 22.5,    # Température autour du lampadaire (exemple)
        'etat': 'allumé',       # Statut du lampadaire (allumé ou éteint)
        'luminosite': 75,       # Niveau de luminosité (en pourcentage)
        'consommation': 12.3    # Consommation d'énergie en kWh
    }
    
    # Convertir les données en format JSON
    payload = json.dumps(donnees)
    
    # Envoi des données à ThingsBoard sur le topic MQTT dédié aux télémétries
    client.publish('v1/devices/me/telemetry', payload)
    print(f"Données envoyées à ThingsBoard : {payload}")

# Envoyer les données toutes les 5 minutes
try:
    while True:
        envoyer_donnees_lampadaires()  # Envoie des données des lampadaires
        time.sleep(300)  # Pause de 5 minutes
except KeyboardInterrupt:
    print("Script interrompu.")
finally:
    client.loop_stop()  # Arrête la boucle MQTT
    client.disconnect()  # Déconnexion de MQTT
