### ISSUE TITLE
[Question] How to select specific target platforms to build from source?

### ISSUE THREAD

**Issue by voanhcuoc** [thingsboard/thingsboard#3308]
**Component**

* Installation
* Documentation

**Description**

Right now when invoking a build from source by `mvn install`, packages for every platforms will be built, which will consume a lot of build time and computing power. I only need a package for ubuntu, but have to wait it to build everything, and have to handle build errors of other platforms.

I don't find docs on how to pick or exclude platforms from the build.

**Comment by yefimov-andrey** [comment]
You can comment out unnecessary packages by commenting the corresponding part in the packaging/java/build.gradle, for example, if you don't need .rpm files, you can comment it out from the https://github.com/thingsboard/thingsboard/blob/a39087883ae97ffa0e822e221bf9e7f17d627c48/packaging/java/build.gradle#L98 to https://github.com/thingsboard/thingsboard/blob/a39087883ae97ffa0e822e221bf9e7f17d627c48/packaging/java/build.gradle#L135

And from the pom.xml file: https://github.com/thingsboard/thingsboard/blob/a39087883ae97ffa0e822e221bf9e7f17d627c48/pom.xml#L455

Same way (but different parts) for all other platforms, which includes .deb, .exe and .zip(for Windows).

Also, building can be sped up by adding -DskipTests if you don't want tests to be run.
