### ISSUE TITLE
 Permission denied with ThingsBoard PE and Docker

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3311]
**Component**

 * Installation

**Description**

I want to run my ThingsBoard Professional Edition with 

```
docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v /home/user/.ThingsBoard-data:/data -v /home/user/.ThingsBoard-logs:/var/log/thingsboard -e "SomeKey" --name mytb-pe --restart always store/thingsboard/tb-pe:3.1.0PE
```

but I got the following output:

```
mkdir: cannot create directory ‘/data/db’: Permission denied
chown: cannot access '/data/db': No such file or directory
unix_chkpwd[11]: check pass; user unknown
Password:
```

The user `user` has been added to the group `docker` and I change the group for the directory `/var/lib/docker` to `docker`.

```
$ ls -l /var/lib/
drwx--x--x 14 root      docker   4096 Aug 14 12:27 docker
```

How can I fix this issue?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.1.0PE

**Comment by Karabiy** [comment]
try to run those with sudo

**Comment by Kampi** [comment]
> 
> 
> try to run those with sudo

Same issue. I tried it with `root` too to avoid permission violations.

**Comment by CooL16** [comment]
You may run the following commands:
sudo chown -R 799:799 /home/user/.ThingsBoard-data
sudo chown -R 799:799  /home/user/.ThingsBoard-logs

**Comment by Kampi** [comment]
> 
> 
> You may run the following commands:
> sudo chown -R 799:799 /home/user/.ThingsBoard-data
> sudo chown -R 799:799 /home/user/.ThingsBoard-logs

Thank you. This was the missing part.

**Comment by lung2008123** [comment]
Thanks for raising the topic!

I'm now trying ThingsBoard installation and ran into the error above. My device has with the following environments:

**Environment**
- OS: MacOS 11.1
- ThingsBoard 3.2.0PE
- Docker 20.10.2

Following the official [Installing ThingsBoard PE using Docker (Linux or Mac OS)](https://thingsboard.io/docs/user-guide/install/pe/docker/), the commands `sudo chown -R 799:799 YOUR_PATH/.mytbpe-data` & `sudo chown -R 799:799 YOUR_PATH/.mytbpe-logs` will raise access issue for regular user.

They will fail `docker-compose up -d` as regular user has read access only and fails to `mkdir` the sub-folder in `./mytbpe-data` & `./mytbpe-data`.

I've stuck for a few hours and finally found out this issue, probably MacOS-specific. Could dear contributors indicate those commands as optional for MacOS users?

Appreciate it!

**Comment by lung2008123** [comment]
My solution is just `mkdir YOUR_PATH/.mytbpe-data` & `mkdir YOUR_PATH/.mytbpe-data` in regular user zsh; without the following `sudo chown -R 799:799` command.
