### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PopoTheSapien** [thingsboard/thingsboard#3313]
**Describe the bug**
Failure to upgrade to 3.1 from 3.0.1.

The first upgrade failed because the primary key for one of the tables was not present when it was to be removed.

Output 
```

  ===================================================
  :: ThingsBoard ::       (v3.1.0)
  ===================================================
 
 Starting ThingsBoard Upgrade from version 3.0.1 ...
 Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
 Updating schema ...
 Optimizing alarm relations...
 Failed updating schema!!!
 org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
   Position: 136
```

**Your Server Environment**

* own setup
  * ThingsBoard Version: 3.0.1
  * Ubuntu

**Expected behavior**
Successful upgrade

**Comment by Karabiy** [comment]
have you run the install before the upgrade? can you please have the next request being done manually
please, run the next commands -
sudo su - postgres
psql 
\c thingsboard

select * from tb_schema_settings; 

and provide us with the output of those, so that we can comments on those

**Comment by PopoTheSapien** [comment]
Thanks for getting back to me.  All I did was run through the Procedure scripts manually and made sure each one executed.  It seems to have done the trick.  I suspect that most upgrade attempts will fail the second time around because most scripts dont have safety checks.  This was especially the case where primary keys were deleted or changed.  I would suggest making more use of the 'IF EXISTS' phrase before operating on a key/variable that doesn't exist.

All sorted now thanks.
