### ISSUE TITLE
[Bug] Sending telemetry over rest doesn't trigger the rule engine

### ISSUE THREAD

**Issue by ymucahit** [thingsboard/thingsboard#3316]
**Describe the bug**
Sending telemetry data to devices over Rest call with the request to the telemetry controller `api/plugins/telemetry/{entityType}/{entityId}/timeseries/{scope}` doesn't trigger the rule engine. Therefore, TB can't recognize the device state and does not produce inactivity/activity events. Furthermore, the user can't create alarm according to the rule engine with given telemetry data.

The problem doesn't occur with the device-api-controller `/api/v1/{deviceToken}/telemetry`.

**Your Server Environment**

* own setup
  * local infrastructure, Docker, k8s
  * ThingsBoard v3.0, v2.4
  * Windows 10, Ubuntu 18.04

**Your Client Environment**

**Desktop:**

* OS: Windows 10, Ubuntu 18.04
* Browser chrome
* Version 84

**Your Device**
Mock device 
* Connectivity
  * HTTP

**To Reproduce**
1. Create a rule from rule engine page for inactivity time out alarms as described in https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/
2. Get token with the request below via command line
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"username":"tenant@thingsboard.org", "password":"tenant"}' 'http://localhost:8080/api/auth/login'`
3. Go to http://localhost:8080/swagger-ui.html
4. Click on 'Authorize' at the top of the page and enter the token as `Bearer <token>`
5. Scroll down to 'telemetry-controller' saveEntityTelemetry
6. Enter the information below for the request:
`entityType: DEVICE`
`entityId: <any device uuid saved in TB>`
`scope: SERVER_SCOPE`
`requestBody: {"temperature": 32}`  
7. Click 'Try it out!' button.
8. Wait for 'defaultInactivityTimeoutInSec' or device specific 'inactivityTimeout' seconds.
9. It will not generate inactivityEvent

**Expected behavior**
The expected behavior of the method should be same with the device-api-controller `/api/v1/{deviceToken}/telemetry`.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Karabiy** [comment]
in this case you can send the telemetry using the HTTP integration, in case if those is being required, so that you can specify the device name and type to map those
for the case of the CE, you can use the HTTP API also for those reasons 
it is an okay behavior

**Comment by ymucahit** [comment]
Yes, there are always workarounds. However, in my opinion, api/plugins/telemetry/{entityType}/{entityId}/timeseries/{scope} controller should not do only a CRUD operation to the DB. It should also trigger the mechanisms similar to any other ways like mqtt, rpc, or device-api-controller. Am I wrong? There might be a logic behind this where I missed.

**Comment by ChristofferHolmesland** [comment]
What if we want to use the rule engine with asset telemetry? There is no workaround like `/api/v1/assetToken/telemetry` for that.

**Comment by jskillen** [comment]
I second @ymucahit on this. If there is a reason behind not running the rules engine at least make it explicit that it won't run and why. I spent far too long trying to debug this before I found this post.
