### ISSUE TITLE
Thingsboard with haproxy

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3318]
1. After I install haproxy, I am very strange that if I create device & asset under URL:8080 & could not see them under URL ? And rule chain behave wrong (for aggregration, ussually null value) after haproxy installed. 
2. I completely remove haproxy but I don't know why I could still use URL without port 8080 ?
Pls help!

**Comment by agtokty** [comment]
1 . Don't understand
2. Thingsboard is using 8080 as a default port, so tb will always run on this port(if you dont change it from configuration). haproxy  also use this port to acces tb itself.

**Comment by anhdv1979** [comment]
Let me describe:
1. I install TB 3.1 PE on premise. After that I run thingsboard with URL and port 8080 (default). Creating devices and asset under group e.g D group for devices and A group for assets. After that I install Ha as guide. I come with URL without 8080 port. But assets and devices not show although D & A groups show. ?????
2. Uninstall haproxy completely but still come with URL without 8080 port. How do I do to make it back before haproxy installaion. It means that I would like to come with url and 8080 port, not url alone

**Comment by agtokty** [comment]
OK, it is very interesting that after haproxy uninstallation, tb still reachable with 80(without 8080 port) port. 
Are you sure haproxy is not running or any other program like apache redirecting your 80 port to 8080 ?

**Comment by anhdv1979** [comment]
Yes. I check all httpd apache nginx but none of them run
