### ISSUE TITLE
MQTT PUBACK missing 

### ISSUE THREAD

**Issue by saurabhjhamb** [thingsboard/thingsboard#332]
Hello everyone,

I am using Paho mqtt client to send to an invalid json string as message to thingsboard, but not gettting PUBACK in reply. The state machine of mqtt client goes bad and needs a connection reset to send any further messages.

This error happens when I use QOS as 1, and goes away on QOS 0.
Can anyone help share thoughts on circumventing this?

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
Hi @saurabhjhamb . The normal behavior of MQTT server according to RFC is to close the connection to a client that sends invalid messages. As you have already identified, the issue is in invalid json string.

**Comment by saurabhjhamb** [comment]
Hi @ashvayka isn't that about invalid MQTT messages. I am sure the message payload and everything is fine. The problem is in realtime, system can corrupt json string, and gateway doesn't get to know that TB has closed the MQTT coonnection.

A simple nack and then (maybe) closing the MQTT connection would help!
I look forward to your thoughts on this...

Regards,
Saurabh
