### ISSUE TITLE
[Question] Rule Chain unavailable?

### ISSUE THREAD

**Issue by Johnacom** [thingsboard/thingsboard#3321]
my rule chain is not loading, i cant acces to rule chain on my demo version

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by Karabiy** [comment]
those should be okay now. there were a small changes being applied for the environment related
