### ISSUE TITLE
[Question] Entity admin widget server-side attributes show

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3324]
**Component**

 * UI - Entity admin widget
**Description**
Could you pls tell me how to show server-side attributes e.g active -> icon instead of true/false; lastActivitytime -> timestamp to Datetime ?
**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.1.0 PE
 * Browser: Chrome & Firefox

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use data post-processing or cell content function to change attribute values formatting.
A simple example for active attribute:
_Cell content function:_
```
value = '&#11044;';
return value;
```
_Cell style function:_
```
var color;
if (value == 'false') {
    color = '#EB5757';
} else {
    color = '#27AE60';
}
return {
    color: color,
    fontSize: '18px'
};
```
