### ISSUE TITLE
[Bug] Aggregation stream error

### ISSUE THREAD

**Issue by chutoanthang22** [thingsboard/thingsboard#3325]
**Describe the bug**
Error for Aggregation stream of two generator
**Your Server Environment**

* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**
1. Create two genereators
![image](https://user-images.githubusercontent.com/46512749/90370613-dc5d3180-e097-11ea-9c09-e904319a5822.png)
2. Create rule chain
![image](https://user-images.githubusercontent.com/46512749/90370673-fc8cf080-e097-11ea-8206-25b0ed177f04.png)
![image](https://user-images.githubusercontent.com/46512749/90370758-1af2ec00-e098-11ea-8889-a81a15352d3b.png)
3. See error
- No totalA value for Asset
![image](https://user-images.githubusercontent.com/46512749/90371099-a7051380-e098-11ea-8ca4-2a44a9fb13fe.png)
and error in rule chain
![image](https://user-images.githubusercontent.com/46512749/90371173-be440100-e098-11ea-8f32-e4dc739cb844.png)
![image](https://user-images.githubusercontent.com/46512749/90371191-c56b0f00-e098-11ea-9f23-5b5ba9bf3a3d.png)
![image](https://user-images.githubusercontent.com/46512749/90371218-d025a400-e098-11ea-9e33-16661c228ec6.png)

Pls help me check!

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Karabiy** [comment]
can you specify the email you are using for the authorization?

**Comment by chutoanthang22** [comment]
lo23.f2@gmail.com

**Comment by YevhenBondarenko** [comment]
Hello @chutoanthang22,

The current issue was fixed in the version 3.1.1.
