### ISSUE TITLE
Unstable connection between sim800 and broker thingsboard v2.4.3

### ISSUE THREAD

**Issue by maiquiISA7** [thingsboard/thingsboard#3328]
Hello, how are you?
Congratulations on the work!

I'm having trouble maintaining the connection to the broker via GPRS with SIM800, I use MQTT, the connection between the device and the broker then falls without a pattern, the connection to the cellular network does not fall, only with the broker. No wifi works perfectly. Has anyone ever experienced this?

**Comment by Karabiy** [comment]
are you connecting to the ThingsBoard MQTT API? Can you provide us with the logs of the device/thingsboard
for the thingsboard logs you can refer to the /var/log/thingsboard/

**Comment by maiquiISA7** [comment]
Yes. can I get this information from inside the thingsboard? Because it is installed on a remote server and I only have access to its graphics.
Using the example 0004-arduino-sim900_send_telemetry behaves the same way.
The wifi works.
I think it has something to do with latency or another parameter, can I get this information from inside the thingsboard? Otherwise I ask the server staff to send me

**Comment by Karabiy** [comment]
being not sure though, in case if you receive any kind of a data on the ThingsBoard side you are able to see those in case if the debug mode is being set in the rule engine. For those reasons, please, use the debug mode for the rule nodes to be set, so that you can check the debug logs in the events tab of the rule node, so that you can get additional information regarding the processing.

You also may refer to this link regarding the debugging: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#debugging

so that in case if no data is being set here, and the issue relates to the connectivity, those first has to be checked on the device side whether everything is okay on this side.

**Comment by maiquiISA7** [comment]
This we did when we were testing. When the data is sent, we can visualize it.

Do you have any MQTT parameters to be adjusted, such as timeout?

**Comment by Karabiy** [comment]
> Do you have any MQTT parameters to be adjusted, such as timeout?

Yeah, you can refer for the thingsboard.yml for those. Those can be found under the "mqtt" topic. 
Please, set those in the thingsboard.conf file and refer to the thingsboard.yml file only to get the environmental variables. It is the same logic as for the license key, so, for example, in case if you would have want to change the MQTT enabled ( the MQTT API to stop ) to the disabled, for the thingsboard.conf file you would have added the next row: 
export MQTT_ENABLED=false

After all the changes will be applied, it is required to have the thingsboard restart, to have the changes to be applied. 

The thingsboard.yml file is located in the same directory as the thingsboard.conf. The path for the directory is /etc/thingsboard/conf/

On the below, also, you can refer for specific MQTT parameters that are present in the thingsboard.yml:
```  # Local MQTT transport parameters
  mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: "${MQTT_ENABLED:true}"
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    bind_port: "${MQTT_BIND_PORT:1883}"
    timeout: "${MQTT_TIMEOUT:10000}"
    netty:
      leak_detector_level: "${NETTY_LEAK_DETECTOR_LVL:DISABLED}"
      boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
      worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
      max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"
      so_keep_alive: "${NETTY_SO_KEEPALIVE:false}"
    # MQTT SSL configuration
    ssl:
      # Enable/disable SSL support
      enabled: "${MQTT_SSL_ENABLED:false}"
      # SSL protocol: See http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
      protocol: "${MQTT_SSL_PROTOCOL:TLSv1.2}"
      # Path to the key store that holds the SSL certificate
      key_store: "${MQTT_SSL_KEY_STORE:mqttserver.jks}"
      # Password used to access the key store
      key_store_password: "${MQTT_SSL_KEY_STORE_PASSWORD:server_ks_password}"
      # Password used to access the key
      key_password: "${MQTT_SSL_KEY_PASSWORD:server_key_password}"
      # Type of the key store
      key_store_type: "${MQTT_SSL_KEY_STORE_TYPE:JKS}"
```
