### ISSUE TITLE
Assign device data to customer dashboards

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3333]
**Component**

 * Generic

**Description**

I have a ThingsBoard setup with two different customer groups and each customer group contains one device.

![Image(1)](https://user-images.githubusercontent.com/3458587/90558866-0cdac380-e19d-11ea-8bd9-c53d3f617de5.png)

Each of these two devices receives random MQTT data from a Python script.

I also have two different dashboard groups which are assigned to each customer

![Image(2)](https://user-images.githubusercontent.com/3458587/90558993-3e538f00-e19d-11ea-8b9f-1cd7fd43ee44.png)

In the next step, I create a simple time series in one of the dashboards but when I add the `temperature` data field from the device, the data fields of both devices are added to the time series

![Image(3)](https://user-images.githubusercontent.com/3458587/90559149-7d81e000-e19d-11ea-8aa0-6c5f5ae74415.png)

How can I modify the permissions in that way that only the data fields of devices from the customer who owns the device can be added to the dashboard?

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.01

**Comment by yefimov-andrey** [comment]
What do you mean? On the tenant level? Tenant always has access to all entities of their customers.
