### ISSUE TITLE
[Question] How to configure Trendz to talk to a SSL-enabled Thingsboard PE instance on the same host?

### ISSUE THREAD

**Issue by coliguru** [thingsboard/thingsboard#3334]
**Component**

 * Installation

**Description**
We have been using Thingsboard PE successfully for the past 6 months. Thanks for a great product, TB Team! 
Our TB PE instance is configured with SSL and runs on an Ubuntu 18.04.2  host in Amazon EC2.  As we gear up to analyze the humongous amount of telemetry data we have collected in the past 6 months  we decided to try Trendz. To install it I started following the instructions here: https://thingsboard.io/docs/trendz/install/ubuntu/ but was a surprised to find no mention to SSL. How can I make Trendz talk to a TB_API_URL configured with SSL?  The documentation assumes localhost and unfortunately we have TB_API_URL on https://tb.domainname.com:8080. 

I hope someone can give us some advice on how to proceed. We are eager to try Trendz.

**Environment**

 * OS: Ubuntu 18.04.2
 * ThingsBoard: PE 3.0.1 
 * Browser: N/A

**Comment by vparomskiy** [comment]
Just set to TB_API_URL without port number - https://tb.domainname.com

**Comment by coliguru** [comment]
Thank you! That worked.
