### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by doudoubean** [thingsboard/thingsboard#3335]
**Component**

 msa

**Description**
I'm trying to build Thingsbooard from source according to these instructions: https://thingsboard.io/docs/user-guide/install/building-from-source/. I want to run thingsboard as docker on loongson mips64el arch, Does the thingsboard support loongson mips64el arch?
**Environment**

 * OS:  Linux kylin 3.10.0-862.9.1.ns7_4.37.mips64el
 * ThingsBoard: 3.1
 * docker：17.12.1.ce
 * jdk : 1.8.0_242
 * maven : 3.6.3

**Comment by ban2derlog** [comment]
Hi, for now ThingsBoard support only x86_x64 and ARM architecture.
You can try to build it for loongson mips64el, but it isn't tested and even tried to install on that.
