### ISSUE TITLE
Switching dashboards on row click

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3336]
**Component**

 * UI

**Description**

I try to understand ThingsBoard a little more and so I watch the [Dashboard development](https://www.youtube.com/watch?v=mqWEGs1Z2BQ) series on YouTube, but I got stuck at minute 9:46 when the speaker adds his custom code to the card widget, because the code doesn´t work for me.

I use the following code:

```js
var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice(entityId.id).then(function(device) {
    if(device.type == 'Energy Simulator') {
        openDashboardState('energy_state');
    } else if(device.type == 'Water Simulator') {
        openDashboardState('water_state');
    } else {
        openDashboardState('temperature_state');
    }
});

function openDashboardState(stateId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    
    widgetContext.stateController.openState(stateId, params, false);
}
```

And my dashboards are called `energy_state`, `water_state` and `temperature_state`. My devices are the following 

![Image](https://user-images.githubusercontent.com/3458587/90615078-e30cb580-e20b-11ea-9e2d-b0a867b886f0.png)

So what is wrong here?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.1.0PE
 * Browser: Firefox 79.0

**Comment by Backdraft007** [comment]
Hi,

maybe this issue helps you:
https://github.com/thingsboard/thingsboard/issues/3147

**Comment by Kampi** [comment]
> 
> 
> Hi,
> 
> maybe this issue helps you:
> #3147

Thank you. This answer solve the issue.
