### ISSUE TITLE
[Question] Datetime picker

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3337]
Could anyone help me how to add Datetime picker component like below
![734211B6-07DB-4A3C-A24E-D9F756A7EF63](https://user-images.githubusercontent.com/7521909/90629193-233e5900-e249-11ea-9a64-e6a3b64ad515.png)

into new widget ?

**Comment by Karabiy** [comment]
you can refer to this link for the TimeWindow function which you may apply on the custom widget: https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions

**Comment by ChantsovaEkaterina** [comment]
Hello,
As an example, you can refer to our datetime-period.component
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/components/time/datetime-period.component.ts
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/components/time/datetime-period.component.html
