### ISSUE TITLE
Which generic permissions are needed for dashboard?

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3339]
**Component**

 * UI

**Description**

I try to make a user which has only read access to his dashboard. So I make a Read-only ´Group´ with all read permissions and a ´Generic´ role with the permissions `Profile`: `All` and `Dashboard`: `All` but the user can only export the dashboard. He is unable to open it.

![Image](https://user-images.githubusercontent.com/3458587/90723091-638aef00-e2bc-11ea-9a82-154e2a2ad4c4.png)

 When I replace the `Dashboard` permission with `All` in the `Generic` role the user can access the dashboard, but this isn´t optimal. So what permissions are missing?

**Environment**

 * ThingsBoard: 3.1.0PE

**Comment by vvlladd28** [comment]
Hi,
You need to add Generic permission to 'Widgets Bundle.'

**Comment by Kampi** [comment]
> 
> 
> Hi,
> You need to add Generic permission to 'Widgets Bundle.'

Hello,

this doesn´t work. I add the permission `Widget Bundle`: `All` to the generic role of the user and he can not access the dashboard.

**Comment by Kampi** [comment]
Hello,

I think I found the solution. It seems that I need the `Widget Type` permission too.

**Comment by ashvayka** [comment]
Yes, this is correct, you need to add `Read` permissions for `Widget Bundl`e and `Widget Type`
