### ISSUE TITLE
Cannot create a device using /api/device API

### ISSUE THREAD

**Issue by lucascarnato** [thingsboard/thingsboard#334]
Hello Everybody,

I have a java application creating many devices by calling /api/device API.
The device get visualized in the dashboard (so I guess it is created), but as soon as I click on it I get this error message:  "GET: /api/device/fbff20b0-ac4d-11e7-a25d-a53156edab23/credentials
404:". 
This is the Json used during the API call
{
  "id": {
    "entityType": "DEVICE",
    "id": "fbff20b0-ac4d-11e7-a25d-a53156edab23"
  },
  "createdTime": 1507483659835,
  "tenantId": {
    "entityType": "TENANT",
    "id": "20c7aae0-9fdb-11e7-b4f2-a53156edab23"
  },
  "customerId": {
    "entityType": "CUSTOMER",
    "id": "13814000-1dd2-11b2-8080-808080808080"
  },
  "name": "test",
  "type": "test"
}

Moreover, if I try to retrieve the credential using 
 http://192.168.43.216:8080/api/device/fbff20b0-ac4d-11e7-a25d-a53156edab23/credentials
I get this response
{
  "status": 404,
  "message": "Requested item wasn't found!",
  "errorCode": 32,
  "timestamp": 1507484900823
}

It looks like the credential are missing!

How can I solve this problem?
Thank you

luca

**Comment by danielfree** [comment]
@lucascarnato I used to meet a similar issue. If you look at the code, you will find the reason is that if you create device via /api/device with device's id, the server won't create a new token-based credential for you, thus you won't get any credential from /api/device/{id}/credentials.

Basically you have two choices: either creating device without assigning id, or set a new credential for each device via API.

**Comment by lucascarnato** [comment]
@danielfree  Thank you very much, you are totally right.
Thank you so much

Luca

**Comment by aridhiramy** [comment]
Hi lucascarnato, how can i create device in thingsboard using Device API ? im not using a user interface

**Comment by lucascarnato** [comment]
It should be this API, but to be sure I should check my code... that I cannot do

https://demo.thingsboard.io/swagger-ui.html#!/device-controller/saveDeviceCredentialsUsingPOST

**Comment by wallygrass** [comment]
In Swagger UI you can find example value which should be passed as a device param in BODY (saveDevice) as below:
{
  "additionalInfo": "string",
  "createdTime": 0,
  "customerId": {
    "id": "string"
  },
  **"id": {
    "id": "string"
  }**,
  "name": "string",
  "tenantId": {
    "id": "string"
  },
  "type": "string"
}
when you pass id as **id: null** then during save process credentials will be created automatically.
.....
  },
  **"id": null**,
  "name": "string",
....

**Comment by micnori** [comment]
Hi!
I have a problem creating devices by calling /api/device API
In particular, I receive a 400 bad request response.
For me is not crear the minimum set of attribute that I must set into the POST body. 
Which attributes can I omit?

Thanks,
Michele

**Comment by M3Henry** [comment]
@micnori The minimum required fields in the POST body are the same as in the Add Device GUI form
```json
{
  "type": "my_device_type",
  "name": "device_0001"
}
```

**Comment by micnori** [comment]
Ok perfect, now it works fine :)
Thanks,
Michele

**Comment by thilanka02** [comment]
Hi!
Is there any specific reason, why thingsboard is not allowed to create devices with given id?

**Comment by rezaUniqe** [comment]
Can't assign the device to customer from different tenant!

I got this error but the weird thing is I m able to create a device without entering customer but when I log in to things board it was not there so I decide to set tenant id and customer id but I got this Can't assign device to customer from different tenant! so what is the problem please help
