### ISSUE TITLE
[Question] Set Entity Id & Name from Entity Admin Table to new dashboard state

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3340]
**Component**

 * UI
 **Description**
Pls help me how to update entity id & name from entity admin table to new dashboard state (with my custom widget)
1. Entity table 
<img width="960" alt="1" src="https://user-images.githubusercontent.com/7521909/90730754-d8791b80-e2f2-11ea-9db1-d434d10adb63.png">
2. My custom widget
<img width="960" alt="2" src="https://user-images.githubusercontent.com/7521909/90730788-ea5abe80-e2f2-11ea-84c8-3ce87188dabd.png">
-> add custom widget to new dashboarh state but I don't know how to set/get entity Id & name into Mat-input field.
**Environment**

 * OS:  Ubuntu 20.04 lts
 * ThingsBoard: 3.1.1 thingsboard cloud
 * Browser: chrome

**Comment by BarberEngineering** [comment]
I've been on the struggle bus with this one piecing together a bunch of older posts but here's what I've scoured so far. Would be great if someone can finish the puzzle!

in the widget JS use:
```javascript
self.onInit = function() {
    $scope = self.ctx.$scope;
    $scope.ctx = self.ctx;
    $scope.onButtonClick = function($event, entity,
        actionDescriptor) {
       
       console.log("CLICK DETECTED")
       
       var entityParams = self.ctx.dashboard.dashboardWidgets.dashboard.stateController.stateObject[0].params
       }
}
```

this gets you the entity item selected by another control as { entityId: entityLabel: entityName: }

in the HTML section use something like:
```html
<a class="active" id="home" (click)="onButtonClick($event, entity, actionDescriptor)">Home</a>
```

which if you open devtools you should see a print when you click on the link. The only thing that comes through is $event though thats why I use the entityParams line.

I'm missing a method to open a new dashboard.. openState only changes the state for that dashboard you are on. I'm going to try regular angular routing calls and see if that works, just hope it doesn't break anything.
