### ISSUE TITLE
Why are there multiple sessions in deviceactor Processor

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#3341]
private final Map<UUID, SessionInfoMetaData> sessions;
    private final Map<UUID, SessionInfo> attributeSubscriptions;
    private final Map<UUID, SessionInfo> rpcSubscriptions;

Test findings:
when I alter the device attributes,
the code:
```
attributeSubscriptions.entrySet().forEach(sub -> {
                    sendToTransport(finalNotification, sub.getKey(), sub.getValue().getNodeId());
                });
```
It will be sent many times to transport.

**Comment by ashvayka** [comment]
There is a configuration parameter actors.session.max_concurrent_sessions_per_device or ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE which is set to 1 by default. So, when the newer session is created, old one is closed. This is useful for "buggy" devices/firmware that forgets to close sessions. 
However, for some extreme cases you might need two physical devices to connect with one credentials and they both need to receive notification.
