### ISSUE TITLE
two mqtt project:ssl=true & ssl=false

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#3342]
In the test, I started two mqtt projects in the microservice. One mqtt uses SSL = true and the other mqtt project SSL = false. However, I found that when I update the device sharing properties, it will not be pushed to the device side successfully. Why do I need to modify it.
project module:
tb-transport-mqtt：Quantity: 2 sets
tb-core：Quantity: 2 sets
tb-rule-engine.：Quantity: 2 sets
And I added suffixes to the topics in each project ssl.true perhaps ssl.false.
![image](https://user-images.githubusercontent.com/13637039/90735840-26485080-e300-11ea-957f-19a14e407d56.png)

**Comment by ashvayka** [comment]
Does the same work if you use only one MQTT server (SSL true or false)?  Because I a quite sure this is a cluster setup problem and not related to the MQTT over SSL at all.
