### ISSUE TITLE
[Bug] Tooltip doesn't display in Timeseries float widget when viewing from Mobile Device

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3343]
TB PE 3.0.1 and TB PE 3.1.0

When viewing dashboard with Timeseries float widget in mobile device, clicking on the line does not produce tooltip as expected.

In desktop, clicking on the line produces the tooltip.

Tested with Android Firefox and iOS Safari

**Comment by t0mmyz7** [comment]
@ashvayka can you guys look into this issue? big one for our customers... still exists in 3.1.1

**Comment by t0mmyz7** [comment]
clicking on the graph in mobile view in browser or in mobile phone, does not produce tooltip with value/date

![image](https://user-images.githubusercontent.com/31729091/91838451-33493600-ec56-11ea-85c1-0a7f86ccbe26.png)

**Comment by t0mmyz7** [comment]
@ashvayka Any updates or plans to add this functionality to mobile? Clients are asking for it

**Comment by SuminDenys** [comment]
Hi @t0mZ4,

I am glad to inform you that this issue was resolved in the current ThingsBoard version.

**Comment by t0mZ4** [comment]
nice :)
