### ISSUE TITLE
[Bug] Alarm widget cannot  atuo update status, event...

### ISSUE THREAD

**Issue by chutoanthang22** [thingsboard/thingsboard#3344]
**Describe the bug**
Alarm widget cannot auto update when create/clear alarm!!
1. Create alarm
![image](https://user-images.githubusercontent.com/46512749/90752281-63f9a900-e301-11ea-8fa7-5a5a51afbb65.png)
2. Clear alarm but not auto update in widget
![image](https://user-images.githubusercontent.com/46512749/90752369-7d9af080-e301-11ea-93f8-334819144d20.png)
3. Press f5 to refresh => widget updated
![image](https://user-images.githubusercontent.com/46512749/90752512-ae7b2580-e301-11ea-99ba-2fa0aef73f7a.png)

I need auto refresh in widget. Pls help me check!!!

**Comment by ashvayka** [comment]
Please provide a bit more info. Is "Clear Temperature" a telemetry field or a field from alarm details?

**Comment by chutoanthang22** [comment]
"Clear Temperature" is the field from rule node " Clear Alarm".
Like the example: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/

**Comment by ashvayka** [comment]
Hi @chutoanthang22 . The temporary workaround should be to check the "Propagate Alarm" flag in the rule node.  @YevhenBondarenko has fixed the issue. Fix will be part of 3.1.1 release.

**Comment by ahmed-1a** [comment]
This issue is still there CE v3.2

**Comment by YevhenBondarenko** [comment]
Hi @ahmed-1a
Thank you. 
We have already fixed this issue.  #3987
