### ISSUE TITLE
[Question] How to creat multiple level alarm with Alarm Widget

### ISSUE THREAD

**Issue by chutoanthang22** [thingsboard/thingsboard#3349]
Could you pls tell me  how to create multiple levels alarm?
E.g: 
Temperature: 40 ~ 45 => Warning
Temperature: 45 ~ 50 => Major
Temperature: >50  => Critical

**Comment by t0mmyz7** [comment]
check out this guides:

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email/

**Comment by PovitruliaV** [comment]
Hi @chutoanthang22,
Is this issue still relevant?
