### ISSUE TITLE
cannot distinguish legends when use entity list as datasource

### ISSUE THREAD

**Issue by liaow** [thingsboard/thingsboard#335]
Cannot distinguish legends when use entity list as datasource.

1. The legends of multiple entities display the same name when use entity list. 
If too many entities in a entity list, the legends shoot into the chart.

    <img width="1171" alt="wx20171009-205400 2x" src="https://user-images.githubusercontent.com/3170158/31339364-47d754ec-acc8-11e7-91c7-bae996ee3650.png">

2. when the cursor is hovering on a point of a dashboard, with a long list of entities, the value list will be displayed out of the screen. It may be better to display in multiple columns.

    <img width="1437" alt="wx20171009-214211 2x" src="https://user-images.githubusercontent.com/3170158/31341051-cd86c0c8-accd-11e7-99dc-06a59f793ac0.png">

**Comment by ikulikov** [comment]
In the "Timeseries" field click "pen" icon to start editing of attribute.
In the opened dialog find "Label" field and type something like:
"${entityName} Temp". As a result an ${entityName} variable will be
substituted with corresponding entity name of current data set.

**Comment by liaow** [comment]
So thanks. 
and what about Q2?

**Comment by ikulikov** [comment]
> and what about Q2?
I agree, tooltip should be improved for such case. I think it will be possible to include this improvement into the nearest release.

**Comment by liaow** [comment]
sound fantastic! awaiting
