### ISSUE TITLE
[Question] Count Latest Values with aggregate stream node/ Get all related Attributes

### ISSUE THREAD

**Issue by JonasRueck** [thingsboard/thingsboard#3350]
**Component**

 * Rule Engine

**Description**

1)

Is it possible to count the values received in the last hour with aggregate stream node? I can only select aggregration count with interval 1 hour. But this will lead to fixed timewindows, for example I will get the count of the values from 14:00-15:00 but at 15:00 the count will be reset and starts from 0 for 15:00-16:00. I'm looking for a dynamic count which gives me the count of the values received in the last hour/day from current timestamp.

2)
Is it possible to get every attribute of related assets/devices based on orginator and add them to metadata? Related Attributes Node will produce always a new message for every relation. I want all attributes at once in metadata.

**Environment**

 * ThingsBoard: Thingsboard v.3.0.1 PE

**Comment by JonasRueck** [comment]
Still looking for an answer :smile: 

I want to count messages sent in the last hour and do that like eveery 5 minutes.
Example:
It's 15:00. So I count from 14:00-15:00 and get 100. Next interval will be 5 minutes later so its 15:05 and I count from 14:05-15:05 and get 90.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
