### ISSUE TITLE
[Feature Request] Move a widget to a different bundle

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3351]
Hi

At the beginning of my project, I've created a new widgets bundle to host my dozen of custom-made widgets.
Now, as this list of widgets is getting quite big, I'd like to separate them in new logical bundles.

So I've create these new bundles, and try to move my widgets to them using the Administration REST API by changing the value `bundleAlias` in the POST `/api/widgetType` endpoint.

Here's the error `400` returned by the API: `'Update of widget type bundle alias is prohibited!'`

So is it a technical or a philosophical limitation?
Could this API constraint be removed to let developers move their widgets around?

**Considered alternative:**
I would like to avoid to do the `import / export` dance manually by using the GUI as this a long and error-prone process.

Thanks!

**Comment by ban2derlog** [comment]
Hi, this limitation is hard coded.
You can import\export widgets with REST API without UI usage.
BUT you still can't change already created widgets type alias.
