### ISSUE TITLE
How to set User group permissions to only display the devices from a single asset

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3352]
**Component**

 * UI

**Description**

I have a customer (`Customer A`) with two different asset groups (`District 1` and `District 2`) and each asset group contains one asset (`House A-1-1` and House `A-2-1`). And I have to device groups (`A-1` and `A-2`) with two temperature sensors. Each temperature sensor is added (with the `Relations` tab of the asset) to one asset.
Then I have two different user groups (`District 1` and `District 2`). Each user group contains one user with read only rights for the dashboard. This user should only see a dashboard with the devices in his district. The dashboard should be created with the tenant administrator account, so the tenant administrator see all four devices.

How can I achieve this? My current solution displays all devices as tenant administrator and the devices from both districts.

![Image](https://user-images.githubusercontent.com/3458587/90882319-138b5580-e3ac-11ea-87d6-970377ca2d8a.png)

**Environment**
 * ThingsBoard: 3.1.0PE

**Comment by Blackbadger313** [comment]
Hi @Kampi i facing a same chase as you post. Perhaps could you help to explain method that you use to cover this chase? 

Thank you
