### ISSUE TITLE
How can I configure the outgoing mail with Docker?

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3356]
**Component**

 * Generic

**Description**

I have ThingsBoard running in a Docker container and I want to use the e-mail client from the ThingsBoard installation. My Ubuntu Host has `postfix` installed and the program is configured successfully. How can I use this program as an SMTP server for my ThingsBoard? Do I have to modify my `docker-compose.yml` to map the port (actual `25`) to the host?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: ThingsBoard 3.1.0PE

**Comment by DejonckheereWard** [comment]
I use the docker version of ThingsBoard aswell (version 2.4.3PE right now).
I didn't have to open the port in the docker container for it to be able to work with our mail server. Only difference is that this is located on a different server than the one thingsboard is running on.

Now, things i would try:
in thingsboard use 0.0.0.0 or the host's IP as IP for the mail server with port 25.

These 2 links may be useful for you:
https://nickjanetakis.com/blog/docker-tip-35-connect-to-a-database-running-on-your-docker-host#:~:text=Fortunately%20you%20can%20easily%20have,your%20local%20network%20IP%20address.

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by Kampi** [comment]
Hello,

I´ve tried it again today, but I don´t have any success with it.
My settings are the following:

![Mail](https://user-images.githubusercontent.com/3458587/93770081-02886b00-fc1c-11ea-8db8-daacc5f364f4.png)

Where `User` stands for the user which runs the ThingsBoard container on my host. I have tested my `postfix` installation over the terminal and I can send mails to given e-mail contacts. But the integration to ThingsBoard doesn´t work. I get a `Connection refused` all the time.

My `docker-compose.yml`, which I use to run the ThingsBoard instance` looks like this:

`
version: '2.2'
services:
  User_TB:
    restart: always
    image: "store/thingsboard/tb-pe:3.1.1PE"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
      - "50051:50051"
    environment:
      TB_QUEUE_TYPE: "in-memory"
      TB_LICENSE_SECRET: <SomeLicense>
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      INTEGRATIONS_RPC_PORT: 50051
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/thingsboard"
    volumes:
      - ~/.User_ThingsBoard-data:/data
      - ~/.User_ThingsBoard-logs:/var/log/thingsboard
  postgres:
    restart: always
    image: "postgres:11.6"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: "thingsboard"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ~/.User_ThingsBoard-data/db:/var/lib/postgresql/data
`

**Comment by trypzz** [comment]
Hello, @Kampi 

Tell me, please, your problem is actual or not?

I thinks root cause of your problem this is "localhost" in "Host" input field  in your configuration. "localhost" for docker container this mean the same container where running thingsboard app. You need put in host with your SMTP server (for example 192.168.0.25)
