### ISSUE TITLE
[Question] help! sned external data

### ISSUE THREAD

**Issue by chars1205** [thingsboard/thingsboard#3359]
**Component**

 * Generic

**Description**
1. save the data collected by thingsboard in the database, If so, is there a way to send the data stored in the database to the outside?

**Environment**
 * OS: debian 10.4 
 * ThingsBoard: v.3.0.1

**Comment by amizer12** [comment]
Check the documentaiton - there is entire API you cna use for this - https://thingsboard.io/docs/api/

**Comment by Karabiy** [comment]
you can also use the external rule nodes, so that you will send the processed data. Please, refer to this link for those: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/

**Comment by chars1205** [comment]
@amizer12 , @Karabiy  thanks for your help!
