### ISSUE TITLE
[Feature Request] Change URL to represent selected item in customer hierarchy

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3360]
Hello

A customer hierarchy can get quite deep pretty quickly when multiples levels of customers or sub-customers are involved.

Right now, when colleagues of mine ask questions like "could you tell me where this specific dashboard is hidden in the customer hiearchy maze?", it's quite hard to communicate back the answer other than sending them a screenshot of the ThingsBoard UI with a red arrow pointing to the desired location.

The problem is that in the URL bar of the browser, the path invariably remains the same `/customersHierarchy` so there's no easy way to just send them a link.

Therefore, this URL should change as users drill down the hierarchy tree, expanding tree-nodes in the sidebar. End result would be to have URLs reflecting the UI state like: `/customerHierarchy/customers/customerFoo/dahsboards/thermostats`…

Thanks

**Comment by ban2derlog** [comment]
Hi, you can get DashBoard full URL in DashBoard groups.
In DashBoard Groups you can search dashboard by name and send direct URL to specific dashboard.
