### ISSUE TITLE
[Question] Iframe doesn't show

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3361]
**Component**

 * UI
 
**Description**
I embed iframe into thingsboard widget but it shows nothing. It shows that "content has been blocked. Content must served over https. Pls help how to use with http
![image](https://user-images.githubusercontent.com/7521909/91050498-f1faca00-e648-11ea-8267-91bf9b70758f.png)

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.1.0 PE
 * Browser: chrome

**Comment by amizer12** [comment]
See here:
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
