### ISSUE TITLE
Thingsboard on low speed, high latency internet

### ISSUE THREAD

**Issue by Vermss** [thingsboard/thingsboard#3365]
**Component**

 UI

**Description**
When using slower internets, (<5Mbps and >500ms ping, devices, dashboards, assets all won't load) is there a setting somewhere this can be changed to allow these types of connections to work?

**Environment**

 * OS:  AWS EC2 - Small
 * ThingsBoard: 3.1
 * Browser: Chrome UpTo-Date

**Comment by ban2derlog** [comment]
Hi, you need to tune timeout for all transport.
Here you can see all parameters for ThingsBoard:
https://thingsboard.io/docs/user-guide/install/config/
Please, try to set different Timeout values according to your average Ping.
