### ISSUE TITLE
[Feature Request] Add Alarm notification management for end-users

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3368]
Thingsboard has an awesome alarm system. But it is missing notification management, and the current solution is to create rule chains for receiving alarms by email, sms, telegram etc.

One of the challenges here is on how to allow end-user to control notification settings and preferences.

my suggestion here is to add an alarm notification centre where any user can select which alarms types and severity he wishes to receive and by which method.

When programming alarms, the admin will select which user groups, or notification groups should receive the alarms, and the member users of those groups will determine/control the notification preferences.

what do you guys think ?

**Comment by kkalbaugh** [comment]
This would be a huge asset to Thingsboard.  we just purchased Thingsboard PE and alarm thresholds and notification management is the missing piece we need to be made easier for end-users.

**Comment by jlevell** [comment]
I cannot overstate the need for this feature.  It would be a tremendous boon to our users.  It's going to be nearly impossible to support 1000's of devices AND their users with regards to alarms.  Making Alarm notification management available to users would be our top priority need right now.

**Comment by ashvayka** [comment]
Hi @t0mmyz7 , @kkalbaugh , @jlevell . Thank you for your valuable input. We will start development of this feature after v3.2. Please expect it to arrive in v3.3.

**Comment by fishskinlau** [comment]
@ashvayka Will this feature be available for v2.x ?

**Comment by t0mmyz7** [comment]
If you can, also include ability to receive Repeat Notifications as long as alarm is active.

For example, if temperature alert is active receive SMS notification, enable repeat alert every X minutes.

thanks :+1:

**Comment by t0mmyz7** [comment]
Hi @ashvayka  any chance we'll see this in 3.3 :) ?

**Comment by cemsina** [comment]
IBen event yönetimi için node ekliyordum 2 tane. Bir tanesi event publish, diğeri de generator node gibi fakat publishlenen event için çalışıyor. Bu mevcut sorunu çözmüyor mu?

**Comment by t0mZ4** [comment]
Hi @Ultrazombie 
how come this was closed? I don't think this feature was added in v3.3.3 ?

**Comment by Ultrazombie** [comment]
@t0mZ4, reopened, sorry, 
misunderstood the original question. will remain open until implementation

**Comment by thhart** [comment]
Is there anything in serious planing, still nothing seen in 3.4.1?

**Comment by dreibelt** [comment]
Massive requirement, other systems are doing this quite well.

**Comment by thhart** [comment]
@dreibelt What systems do you recommend as replacement?
@ashvayka Seriously nothing here? Is there anybody out there?

**Comment by dreibelt** [comment]
Im simplifying here, but a round-about way of acheiving this is to add server-attributes to a user group for each notification-type, add a notification-type property to the alarm details, and create a rule chain for new alarms that loops over matching users ( it works, but a gui method would win)

**Comment by Ultrazombie** [comment]
closed due to inactivity
