### ISSUE TITLE
CoAP DTLS PSK

### ISSUE THREAD

**Issue by strautins** [thingsboard/thingsboard#3374]
Does Thingsboard CoAP transport layer supports DTLS, specific Pre-shared key authentication?

**Comment by Karabiy** [comment]
seems to be the feature request

**Comment by strautins** [comment]
Thank you!
In future, it could be nice addition to Thingsboard for "on battery"  devices. 
There are already projects going on, on CoAP DTLS. I preferred Java@github `californium/scandium` may be it is wise to check.
I got my answer, again, thanks. Feel free to close this question, if no future action will take place.
