### ISSUE TITLE
[Question] latest telemetry

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3385]
* Generic

**Description**
As I check, it seems that latest telemetry table moved from cassandra to postgresql and it seems that 
1. No need  UUIDConverter for entityid from entity tables (asset, device...)  to kv latest table (postgres) and kv history table (cassandra) ? Is that right ? 
2. History telemetry data table (cassandra) also includes the latest telemetry ? Why latest moved from cassandra to postgres ? for performance ?
3. And what happen if we would like to upgrade from 2.4.3 to 3.1 ? any tool to migrate data because you change the database schema ?

**Environment*
 * OS:  ubuntu 20.04
 * ThingsBoard: 3.1.0 PE
 * Browser: chrome

**Comment by ashvayka** [comment]
Hi @anhdv1979 

1. This is correct. No need to use UUIDConverter any more.
2. We have moved latest values to PostgreSQL to be able to perform filtering of entities based on latest telemetry readings. This move is optional and controlled by the DATABASE_TS_LATEST_TYPE env variable. See thingsboard.yml comments for more details. If you don't have more then 10 000 updates of the latest telemetry per second you should be totally fine with PostgreSQL. We have reached 50 000 inserts to the latest telemetry with PostgreSQL with NVMe disks with no issues.
3. Yes, sure, just carefully follow the upgrade instructions and don't forget to backup the database(s) first: [CE](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/) or  [PE](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/)
