### ISSUE TITLE
How can update server attribute values using Latest card widget (using card see the attachment pic)

### ISSUE THREAD

**Issue by harikrishna6050** [thingsboard/thingsboard#3386]
**Component**

 * UI
 

**Description**
A clear and concise details.
why i choose this card, this card only supports HTML code. i am designed one project dashboard in this project control the motor through BUTTON switch, when button press Motor will be ON other wise OFF. i am trying to update the value of BUTTON (using server attribute) is not update because this CARD only present only visible data not control widget..... please give me the solution ...

Thank you

**Environment**
@RondoRonaldo
![Lateat card value with html code support](https://user-images.githubusercontent.com/52191862/91631639-c422d600-e9f8-11ea-9c18-7f42aacb9bfa.png)

**Comment by amizer12** [comment]
Play around with update attribute widget ( in Input widget bundle) - not this html one.
![image](https://user-images.githubusercontent.com/55321188/91634194-ced86d80-e9ee-11ea-9c5b-89395114ee98.png)
I`m assuming you are using integer to store the value of motor state, if not then choose apropriate widget from input bundel that will correspond with your type of attribute and data.
Once you have that working - then you can try to edit this widget and code some good UI to make it a button, you need a fronted skills to do this plus some JS as well.
This should get you started in terms of development good front-end code aorund it:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#using-external-javascript-library

**Comment by harikrishna6050** [comment]
thank you @amizer12  please find the attachment
[ISSUSE.docx](https://github.com/thingsboard/thingsboard/files/5145146/ISSUSE.docx)

**Comment by harikrishna6050** [comment]
> Play around with update attribute widget ( in Input widget bundle) - not this html one.
> ![image](https://user-images.githubusercontent.com/55321188/91634194-ced86d80-e9ee-11ea-9c5b-89395114ee98.png)
> I`m assuming you are using integer to store the value of motor state, if not then choose apropriate widget from input bundel that will correspond with your type of attribute and data.
> Once you have that working - then you can try to edit this widget and code some good UI to make it a button, you need a fronted skills to do this plus some JS as well.
> This should get you started in terms of development good front-end code aorund it:
> https://thingsboard.io/docs/user-guide/contribution/widgets-development/#using-external-javascript-library

Thank you.. please find the attachment
[ISSUSE.docx](https://github.com/thingsboard/thingsboard/files/5145150/ISSUSE.docx)

**Comment by ChantsovaEkaterina** [comment]
Hi,
As an alternative, if you want to use an HTML card widget, you can use _On HTML element click_ custom action to update the server attribute. In this case HTML element should have an _id_ attribute same with the custom action name.

**Comment by harikrishna6050** [comment]
> Hi,
> As an alternative, if you want to use an HTML card widget, you can use _On HTML element click_ custom action to update the server attribute. In this case HTML element should have an _id_ attribute same with the custom action name.

hi @ChantsovaEkaterina  thank you 
can you please give one example how can handle it.

**Comment by ChantsovaEkaterina** [comment]
Hi, @harikrishna6050 
If I understand correctly what you want to achieve, you have to add an id attribute with an _actionName_ value to a button element in your HTML. Then create a custom action with an appropriate name (id attribute value), select _On HTML element click_ as an action source, and _Custom action_ as an action type. Example of how to handle the attributes with custom actions you can find by selecting the _Custom action with HTML template_. When you choose these, you will see three examples of handling the attributes and entity itself. There are three examples: add, edit, and delete the entity. You need the second. Your case is more simple than written in this example, you need no HTML template, but the way of getting the current attribute value and saving it is the same.
