### ISSUE TITLE
Adding widgets twice leads to Page Unresponsive

### ISSUE THREAD

**Issue by Panometric** [thingsboard/thingsboard#3387]
The browser (Chrome 85) will lock up if the dashboard is in edit mode, and you try to add twice. 

**Server Environment** 

* demo.thingsboard.io

**Client Environment** 
* OS: Windows 
* Browser Chrome 85
* Version 85

**To Reproduce**

1. Open a dashboard
2. Edit it
3. Add a Control Widget
4. Press Add again
5. Notice the Control Widgets are selected, but no widgets are displayed, and the browser is unresponsive. 

**Expected behavior**
The control widgets should display

**Comment by Karabiy** [comment]
can you please specify the email you are using for the demo.thingsboard.io?

**Comment by 154386670** [comment]
I also encountered the same problem

**Comment by 154386670** [comment]
The version is 3.1, the operating environment is docker, CPU 4 cores, 8G memory, when running widgets, google chrome does not respond. However, this problem has not been found with the safari browser.

**Comment by Karabiy** [comment]
it seems to be okay on my side. 
can you, please, provide us with the video record also having the DevTools to be present on the screen ( F12  in Chrome )?

**Comment by Panometric** [comment]
It's still doing, it, using Chrome. I'm not sure what you want form the console, but I found this: 
![image](https://user-images.githubusercontent.com/716218/93266466-f5bcd080-f75e-11ea-818e-0837cde05654.png)

**Comment by 154386670** [comment]
There will be the following information:
{"status":401,"message":"Authentication failed","errorCode":10,"timestamp":"2020-10-13T14:24:53.823+0000"}

**Comment by sumin-denys** [comment]
Hi @Panometric,

Thank you for your report!
I am glad to inform you that this issue is resolved in the latest version of ThingsBoard, 3.8.1. I am closing this issue.
If you have any further questions, please feel free to create a new issue or reopen this one.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
