### ISSUE TITLE
[Bug] build error Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<Date>'.

### ISSUE THREAD

**Issue by hasikp1** [thingsboard/thingsboard#3390]
Build error in version": "3.1.1",
I received the following error when I am building  the UI-NGX

```
ERROR in node_modules/@date-io/date-fns/build/date-fns-utils.d.ts:4:22 - error TS2420: Class 'DateFnsUtils' incorrectly implements interface 'IUtils<Date>'.
  Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<Date>'.

4 export default class DateFnsUtils implements IUtils<Date> {
                       ~~~~~~~~~~~~

  node_modules/@date-io/core/IUtils.d.ts:126:3
    126   getDaysInMonth(value: TDate): number;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'getDaysInMonth' is declared here.
```

**Comment by ashvayka** [comment]
Please make sure you have completely removed node_modules before the clean build:

`rm -rf ui-ngx/node_modules/*`

**Comment by nick-cooney** [comment]
Is this an ongoing issue. I'm experiencing the exact error during a yarn build. have removed node_modules and reinstalled, dependencies ( "@date-io/date-fns": "^2.8.1", "@material-ui/pickers": "^3.2.10") are up to date.

**Comment by hasikp1** [comment]
still fails tried in both windows and ubuntu machine. receiving the same error. node version 12.18.3, angular cli 10.1.0. used npm i and then ng build. Any solution

**Comment by csm1sh** [comment]
I got same error

**Comment by john1337** [comment]
> Please make sure you have completely removed node_modules before the clean build:
> 
> `rm -rf ui-ngx/node_modules/*`
> 
> The build bot report that the build was ok. You can log in as a guest here and check: https://builds.thingsboard.io/

hey,you'd better check this：https://material-ui-pickers.dev/getting-started/installation
which means date-io/2.x doesn't work with material-ui/pickers/3.x

**Comment by wy6688** [comment]
I have the same problem,  and I found out the top reason is that  "material-ui-pickers" V3 only compatible with @date-io/date-fns@1.x date-fns, while tb currently using @date-io/date-fns@2.6.1.  change @date-io/date-fns@1.3.13. the error gone.
 see the original document: 
      https://material-ui-pickers.dev/getting-started/installation#peer-library
