### ISSUE TITLE
[Question] Finding active alarms from the API

### ISSUE THREAD

**Issue by DaveHartburn** [thingsboard/thingsboard#3391]
**Component**

 * Generic

**Description**
Does anybody know how to get a list of active alarms for a device from the API, or the meaning of pageSize and page, which are required parameters? I am successfully pulling telemetry data, so I know the authorisations are correct, however when I try:
`curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer <my token>' 'http://<my server>/api/alarm/DEVICE/daf7a3a0-df0e-11ea-853e-5b39d3212c69?pageSize=20&page=1'`

I am getting a 500 response:
`{
  "status": 500,
  "message": null,
  "errorCode": 2,
  "timestamp": "2020-08-31T07:26:34.554+0000"
}`
From the GUI, I can see there is an active alarm (3 days old if that makes a difference)

Nothing is being written to thingsboard.log. If I change the entity type or the device ID to something that does not exist, then I get an error to say so, so something is working behind the scene. Going to '/api/device/info/<device id>' also works. I do get the same 500 issue if I use `api/alarm/highestSeverity`. It almost looks like this part of the API is failing.

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: v3.1.0
 * Browser: Firefox 79.0

**Comment by Delapouite** [comment]
Hello. Did you try to have a look to the network traffic in your Firefox Devtools when you are looking at the widget displaying the 3 alarms on the GUI? It should give you a hint on the API endpoint used.

**Comment by ashvayka** [comment]
1. Try 'page=0' (first page)
2. Try to use any other API. Maybe the issue is with the headers or your URL.  (for example, try to get a list of devices).

**Comment by YevhenBondarenko** [comment]
Hi @DaveHartburn, try to add param searchStatus=ACTIVE

**Comment by YevhenBondarenko** [comment]
#3397

**Comment by DaveHartburn** [comment]
Many thanks @YevhenBondarenko, that is what I needed. @ashvayka I likely needed the page 0 too, thanks both.
