### ISSUE TITLE
docker run images report config/logback.xml not found

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#3392]
When I execute cmd:  docker run images: thingsboard/tb-core ,
the log is that:
java.lang.IllegalStateException: java.io.FileNotFoundException: /config/logback.xml (No such file or directory).......
the image thingsboard/tb-core  is build by use the module msa/docker-tb/target/Dockerfile to created and use the tag name:thingsboard/tb-core.
and other module is also produced the problem : file config/logback.xml not foud.
what problem is that?
and I found the logback.xml is packaged in the dir:data.tar\.\usr\share\tb-mqtt-transport\conf.
why the shell script need to turnned to the dir:config ?

**Comment by ashvayka** [comment]
Please follow official documentation for the setup based on the docker-compose project: https://github.com/thingsboard/thingsboard/tree/master/docker

The tb-core is a microservice that should not be launched as a separate docker image without docker-compose.
