### ISSUE TITLE
[Question] Number of Decimals on variable in 'To Email' rule chain node.

### ISSUE THREAD

**Issue by BigAdam86** [thingsboard/thingsboard#3393]
**To email-node**

 * Rule Engine

**Description**
When using a variable in the email body with the ${temperature}-format I get a lot of decimals.
Is there a way to round it to a single decimal? In widgets, et.c. I'm using ${temperature:1} and it works, but that doesn't work in the rulechain.

**Comment by ChantsovaEkaterina** [comment]
Hello,
Currently, the only way is to round value to a needed number of decimals before creating an email template. You can do this in the Transformation-  script rule node and after that go to creating an email body.
