### ISSUE TITLE
[Question] Define widget subscription programatically

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3399]
Hi,
Is there a way to programatically defined widget subscription and not via widget UI ?
I want to create widget that pull telemetry AND latest values for some of the attributes.

Problem is that if i define this widget as latest values type - i cannot get the telemetry via attribute service ( only remove or update is available in 3.1 ) and if i defined the widget as timeseries - i can pull attributes from attributes sevice BUT becasue attributes are not in scope of the widget ( this type of widget only allows you to add telemetry, nothing else) they are not being automatically updated on datat update ( i now have a workaround for it and i run an update function in wodget every 10 seconds but i want this to be 100% reactive if possible )

It would be great if either attribute sevice have the option to pull latest telemetry OR have the ability to increase timeseries widget scope even porgramatically with attributes.

Any advice ?

**Comment by ChantsovaEkaterina** [comment]
Hi,
There are two methods in Widget Context -> subscription API: _createSubscription_, _createSubscriptionFromInfo_.
But if you need only attributes and latest timeseries values standard latest values widget allows you to get these.

**Comment by amizer12** [comment]
Hi, 
Apologies for not being clear - i need timeseries data for the graph as well, so not only latest timeseries.
The thing is that getTimeseries doesn`t exist in 3.0 upwards in Attribute Service, see here:
https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/core/http/attribute.service.ts#L28
There is _deleteEntityTimeseries_ and _saveEntityTimeseries_ but no getEntityTimeseries :(

**Comment by amizer12** [comment]
@ChantsovaEkaterina 
Can you point me to the code in github or documentation that shows the mentioned API options ?

in self.ctx scope i have only "defaultSubscription" option and that only returns the widget subscription.

**Comment by ChantsovaEkaterina** [comment]
Hi, @amizer12 
The API itself for getting telemetry data still present, not sure why it wasn't added to the attributes service.
https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/getTimeseriesUsingGET

As for subscription methods, they are not in the _scope_, but in _self.ctx.subscriptionApi_.
https://github.com/thingsboard/thingsboard/blob/f510b142a786cd755344924f003913efb05db4c2/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L260
