### ISSUE TITLE
[Question] POST /api/integration returns 400 Bad Request

### ISSUE THREAD

**Issue by linekermtl** [thingsboard/thingsboard#3400]
**Component**

 * Generic

**Description**
POST /api/integration/ returns 400

**Environment**
 * OS: macOS
 * ThingsBoard: 2.5.2PE-1
 * Browser: Safari 

I'm trying to save an integration using POST /api/integration, the message body has the mandatory fields filled in. But I keep getting the following error:
`{
    "timestamp": "2020-09-01T00:15:27.838+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "I/O error while reading input message; nested exception is java.io.IOException: Missing entityType or id!",
    "path": "/api/integration/"
}`

Here's the request body:
`
{  
  "additionalInfo": "created by postman",
  "configuration": {
      "metadata": {},
      "clientConfiguration": {
      "connectTimeoutSec": 10,           
      "credentials": {
        "type": "basic",
        "username": "intentionally blanked out",
        "password": "intentionally blanked out"
      },
      "cleanSession": false,
      "host": "intentionally blanked out",
      "port": 8883,
      "ssl": true
    },
    "topicFilters": [
      {
        "filter": "v3/bizard-lab/devices/sentrius-1/up",
        "qos": 0
      }
    ],
    "downlinkTopicPattern": "${topic}"
  },
  "createdTime": 0,
  "debugMode": true,
  "defaultConverterId": {
    "id": "6ade24a0-ca27-11ea-b8b6-f3024ac1a0a4"
  },
  "downlinkConverterId": {
    "id": "eb2cd2a0-ca27-11ea-b8b6-f3024ac1a0a4"
  },
  "enabled": true,
  "id": { 
    "id": "6fb7fb0e-eb2e-11ea-adc1-0242ac120002"
  },
  "name": "water meter integration",
  "remote": false,
  "routingKey": "abc",
  "secret": "123",
  "tenantId": {
    "id": "53e06260-aa5f-11e9-acab-83d6cfdffb63"
  },
  "type": "MQTT"
}`

It seems all the parameters are filled according to the swagger UI, what am I missing? 
Can you please share a working example of message body? 

Thanks!

**Comment by Karabiy** [comment]
which ThingsBoard and the integration version you are running? As for the result body, as the data converter result, the message should be in the format as it is via the link: https://thingsboard.io/docs/user-guide/integrations/#uplink-data-converter

**Comment by linekermtl** [comment]
Thanks, maybe it's an issue with the swagger documentation issue then. I'm using version 2.5.2PE-1, private installation. Here's the example message body as provided by https://{{url}}/swagger-ui.html, note "entityType" is not included in the example: 

`{
  "additionalInfo": "string",
  "configuration": "string",
  "createdTime": 0,
  "debugMode": true,
  "defaultConverterId": {
    "id": "string"
  },
  "downlinkConverterId": {
    "id": "string"
  },
  "enabled": true,
  "id": {
    "id": "string"
  },
  "name": "string",
  "remote": true,
  "routingKey": "string",
  "secret": "string",
  "tenantId": {
    "id": "string"
  },
  "type": "OCEANCONNECT"
}`

Also I noticed this API is not present in https://demo.thingsboard.io/swagger-ui.html, why?

**Comment by Karabiy** [comment]
because there is no integration functionality for the ThingsBoard Community Edition

**Comment by trypzz** [comment]
closed due to inactivity.

**Comment by souvikrnd** [comment]
hello . i want to connect exotel and thingsboard . when i try to sent post request then show me mpty body message . but i also sent correct details in msg:data
