### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by murongfeng66** [thingsboard/thingsboard#3401]
**Describe the bug**
org.thingsboard.server.service.ttl.AbstractCleanUpService#executeQuery The connection used by
The java.sql.DriverManager#getConnection method was created, and it was not closed after use. And every time a scheduled task is executed, a connection will be created, which will cause the database connection to run out for a long time。

**Comment by ashvayka** [comment]
@ShvaykaD please fix this asap.

**Comment by ShvaykaD** [comment]
Hi @murongfeng66 and @ashvayka, 

I have double-checked the AbstractCleanUpService and its children's classes and I didn't see any issue with connection creation, because it declared in the try-with-resources statement and the Connection interface extends from the AutoCloseable interface which means that we don't need to explicitly close the connection.

**Comment by murongfeng66** [comment]
your code:
try {
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            getWarnings(statement);
            resultSet.next();
            removed = resultSet.getLong(1);
            log.debug("Successfully executed query: {}", query);
        } catch (SQLException e) {
            log.debug("Failed to execute query: {} due to: {}", query, e.getMessage());
        }

it should be:
try (
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(query)
        ){
            getWarnings(statement);
            resultSet.next();
            removed = resultSet.getLong(1);
            log.debug("Successfully executed query: {}", query);
        } catch (SQLException e) {
            log.debug("Failed to execute query: {} due to: {}", query, e.getMessage());
        }

**Comment by ShvaykaD** [comment]
Hi @murongfeng66, thanks for the comments, this was fixed and merged to the master branch.
