### ISSUE TITLE
[Bug] TCP Integration Shutdown without process uplink

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3402]
Pls help me chech why TCP Integration shutdown without process uplink
[tb-tcp-udp-integration.log](https://github.com/thingsboard/thingsboard/files/5153986/tb-tcp-udp-integration.log)
#863921031797940,CMD-T,V,DATE:20083,TIME:152920,LAT:21.0830730N, LOT:105.9846500E,Speed:0.0,0-1-0-0-46-27,000,45202-05DE-024ADE0D,00,0.00,28.0-29.5,4,80
Maybe your tcp server does not receive terminator ? our gps device send data as above. Seem that your service need stop signal & fire timeout to shutdown 
Eventhought you use Hercules as tcp client and send to your tcp integration, yours seem to shutdown after read
with ' ' -> echo -e '#863921031797940,CMD-T,V,DATE:20083,TIME:152920,LAT:21.0830730N, LOT:105.9846500E,Speed:0.0,0-1-0-0-46-27,000,45202-05DE-024ADE0D,00,0.00,28.0-29.5,4,80'  -> OK
without ' ' -> echo -e #863921031797940,CMD-T,V,DATE:20083,TIME:152920,LAT:21.0830730N, LOT:105.9846500E,Speed:0.0,0-1-0-0-46-27,000,45202-05DE-024ADE0D,00,0.00,28.0-29.5,4,80 -> Shut down 

Pls help quick because I have to integrate for customer device

**Comment by YevhenBondarenko** [comment]
@anhdv1979 pls provide us the version of ThingsBoard which you use.

**Comment by YevhenBondarenko** [comment]
Hi @anhdv1979, could you provide us with the integration configuration?

**Comment by anhdv1979** [comment]
![image](https://user-images.githubusercontent.com/7521909/91872947-ae383e00-eca2-11ea-9755-9ba593ac53db.png)

![image](https://user-images.githubusercontent.com/7521909/91872904-9f518b80-eca2-11ea-923b-0a76bee548d9.png)

![image](https://user-images.githubusercontent.com/7521909/91873029-c5772b80-eca2-11ea-8a71-b9955e8053dd.png)

or

![image](https://user-images.githubusercontent.com/7521909/91873161-e8094480-eca2-11ea-9628-774bf00e4e63.png)

![image](https://user-images.githubusercontent.com/7521909/91873244-fce5d800-eca2-11ea-8852-031f7c99d784.png)

netcat OK without ''

**Comment by anhdv1979** [comment]
1. integration.yml
server:
  # Server bind address
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  # Server bind port
  port: "${HTTP_BIND_PORT:8082}"

integration:
  routingKey: "${INTEGRATION_ROUTING_KEY:PUT_YOUR_ROUTING_KEY_HERE}"
  secret: "${INTEGRATION_SECRET:PUT_YOUR_SECRET_HERE}"
  allow_local_network_hosts: "${INTEGRATION_ALLOW_LOCAL_NETWORK_HOSTS:true}"
  statistics:
    # Enable/disable integration statistics
    enabled: "${INTEGRATION_STATISTICS_ENABLED:true}"
    persist_frequency: "${INTEGRATION_STATISTICS_PERSIST_FREQUENCY:3600000}"

storage:
  data_folder_path: "${INTEGRATION_STORAGE_DATA_FOLDER_PATH:./}"
  max_file_count: "${INTEGRATION_STORAGE_MAX_FILE_COUNT:100}"
  max_records_per_file: "${INTEGRATION_STORAGE_MAX_RECORDS_PER_FILE:30}"
  max_records_between_fsync: "${INTEGRATION_STORAGE_MAX_RECORDS_BETWEEN_FSYNC:10}"
  max_read_records_count: "${INTEGRATION_STORAGE_MAX_READ_RECORDS_COUNT:50}"
  no_read_records_sleep: "${INTEGRATION_STORAGE_NO_READ_RECORDS_SLEEP:1000}"

executors:
  thread_pool_size: "${EXECUTORS_SIZE:1}"
  reconnect_timeout: "${EXECUTORS_RECONNECT_TIMEOUT:3000}" # in milliseconds

rpc:
  host: "${PRC_HOST:cloud.thingsboard.io}"
  port: "${RPC_PORT:9090}"
  timeout: "${RPC_TIMEOUT:5}" # Timeout in seconds for channel termination
  ssl:
    enabled: "${RPC_SSL_ENABLED:false}"
    cert: "${RPC_SSL_CERT:roots.pem}"
  client_id: "${RPC_CLIENT_ID:remote}"

js:
  evaluator: "${JS_EVALUATOR:local}"
  # Built-in JVM JavaScript environment properties
  local:
    # Use Sandboxed (secured) JVM JavaScript environment
    use_js_sandbox: "${USE_LOCAL_JS_SANDBOX:true}"
    # Specify thread pool size for JavaScript sandbox resource monitor
    monitor_thread_pool_size: "${LOCAL_JS_SANDBOX_MONITOR_THREAD_POOL_SIZE:4}"
    # Maximum CPU time in milliseconds allowed for script execution
    max_cpu_time: "${LOCAL_JS_SANDBOX_MAX_CPU_TIME:5000}"
    # Maximum allowed JavaScript execution errors before JavaScript will be blacklisted
    max_errors: "${LOCAL_JS_SANDBOX_MAX_ERRORS:3}"

2. integration.conf
export JAVA_OPTS="$JAVA_OPTS -Xloggc:/var/log/tb-tcp-udp-integration/gc.log -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps"
export JAVA_OPTS="$JAVA_OPTS -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10"
export JAVA_OPTS="$JAVA_OPTS -XX:GCLogFileSize=10M -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=10000 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSParallelInitialMarkEnabled"
export JAVA_OPTS="$JAVA_OPTS -XX:+CMSEdenChunksRecordAlways -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly"
export LOG_FILENAME=tb-tcp-udp-integration.out
export LOADER_PATH=/usr/share/tb-tcp-udp-integration/conf

# UNCOMMENT NEXT LINES AND PUT YOUR CONNECTION PARAMETERS:
export PRC_HOST=smartconnect.pde.vn
export RPC_PORT=9090
export INTEGRATION_ROUTING_KEY=39d76749-9643-a08d-31ed-15fb0ee0876a
export INTEGRATION_SECRET=laekhzkr61k60d5jsrkp

**Comment by Karabiy** [comment]
please, let us proceed further communicating related to the issue of yours via email. you can contact me using the next email vponoiko@thingsboard.io 
also, specify current version of the ThingsBoard and the integration of yours

**Comment by Karabiy** [comment]
the issue referred for the particular port to be used, as the integration used the 7887 port (referring to the screenshot)  to receive on the data for those.  After those was applied, the corresponding messages started to be available to be observed in the events tab and to be processed.
