### ISSUE TITLE
How to read configuration properties from a plugin?

### ISSUE THREAD

**Issue by cityant** [thingsboard/thingsboard#341]
Anybody knows how a plugin read some properties (mqtt transport host and port) in the configuration file. Seems there is no such methods or handles in the plugin context. I am not sure if spring boot @value can be used or not. Perhaps it can't?

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
Hi @stormwrym . This items and much more are documented in a rule/plugin development guide:
https://thingsboard.io/docs/user-guide/contribution/extensions-development/#action-development-guide

Please note that we plan to do a major refactoring of this items in 1.5 to be more decoupled and easy to contribute. See https://github.com/thingsboard/thingsboard/issues/322
