### ISSUE TITLE
How to display device label in Timeseries tooltip?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3410]
Hi Guys

I have a time-series graph showing group of devices, I need to show the device label or name in the Legend and in the Tooltip, otherwise user cannot tell which variable belongs to which device.

Any way to do it?

for example, this RSSI graph of 3 different devices

![image](https://user-images.githubusercontent.com/31729091/91965123-baf77900-ed18-11ea-9eee-dfbabdbf904f.png)

![image](https://user-images.githubusercontent.com/31729091/91965142-c0ed5a00-ed18-11ea-8112-004af4c4cce0.png)

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use ${entityName} and ${entityLabel} patterns in labels.

**Comment by t0mmyz7** [comment]
perfecto! easily done

![image](https://user-images.githubusercontent.com/31729091/91980622-387ab380-ed30-11ea-8fbb-ca5833f81d60.png)
