### ISSUE TITLE
[Bug] Unable to indicate "To entity" in relations from/to tenant

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#3411]
**Describe the bug**
Unable to indicate to entity in relations from/to tenant
There is no option to select the to entity type nor the to entity itself.
![imagen](https://user-images.githubusercontent.com/52624907/91967396-74535000-ed13-11ea-8ffa-418029b8f984.png)

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard Version 2.5.1
  * OS Name and Version: Ubuntu

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Firefox
* Version 

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vvlladd28** [comment]
Hi @IoTopenTech ,
Can you write a version of TB and a web browser?

**Comment by IoTopenTech** [comment]
Dear @vvlladd28 
I am using ThingsBoard CE 2.5.0 and have tested it with Firefox and Chrome.

More information.
When logged as tenant admin, any try to create a relation from a device to the same tenant ends with an Access Forbidden message.
![imagen](https://user-images.githubusercontent.com/52624907/92026740-bc00c880-ed61-11ea-917a-5047b2ba205c.png)
When logged as sysadmint, the Add relation dialog box of the tenant does not allow to specify the to entity (as showed in my previous message).
Kind regards

**Comment by Ezhilvendan-iot** [comment]
Hi I am using trail cloud account of things-board. I was created a customer and dashboards , and assigned to the user , Its worked well as per desired results , but after some time i am getting the error while trying to access the user account like this **Access Forbidden You do not have sufficient rights to access this location! Try to log in with another user if you still want to access this location.** Any one can help me out from issues.

<img width="848" alt="image" src="https://github.com/thingsboard/thingsboard/assets/77045604/ad6585bc-e83b-4461-95b6-f41ba2787428">

**Comment by SuminDenis** [comment]
Hello @[IoTopenTech](https://github.com/IoTopenTech),

I’m glad to inform you that this issue has been solved in the current version of ThingsBoard!
