### ISSUE TITLE
How to use the advanced css feature? How to set background image for login page?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3422]
Hi 

there is no documentation on the Advanced CSS feature in White-label

For example, we would like to set a background image for the login page. How can it be done?

And can we get some doc for Advanced CSS ?

**Comment by t0mmyz7** [comment]
I understood from Alex that it is not possible to change css on the login screen, this should be added as a feature request :+1:

**Comment by DenysVisser** [comment]
This is confusing as there is clearly an [Advanced CSS] function in the Login white labelling. 
Can we get some clarification as to its function if not for updating the CSS for customisation?

**Comment by Ultrazombie** [comment]
@t0mZ4 Hello,
If you mean the ThingsBoard CE version, we do not have this feature in CE.

**Comment by t0mZ4** [comment]
this was implemented

```
.mat-app-background, .tb-dark.mat-app-background {
    background-image: url("https://cdn.hipwallpaper.com/i/46/69/zKF0oA.jpg");
}
.tb-default.mat-app-background, .tb-default .mat-app-background {
    background-color: #eee;
    color: rgba(0,0,0,.87);
    background-color: pink !important;
}
```
