### ISSUE TITLE
[Question] Create websocket connection form widget - how to get  JWT_TOKEN from widget scope ?

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3424]
Hi,
I'm trying to build a widget which would use websocket connection.
I`ve followed documentation but place where i'm lost is the JWT_TOKEN.
I can generate it manually as per documentation , but this is not scallable as i need to get the token once the widget is loaded and user is logged in so i can use to to initiate connection and pull data.

I see in the netowkr tab of the browser that for the subscription created via standard widget UI it gts the token and creates websocket connection:
![image](https://user-images.githubusercontent.com/55321188/92410278-e8428d80-f143-11ea-9877-6509d814e0fd.png)

Any idea how i can pull the token form the widget level ?

Any guidance would be much appreciated !

I'm running Thingsboard CE 3.1

**Comment by dhaval2017** [comment]
Why you need to create web socket?

**Comment by amizer12** [comment]
@dhaval2017  I want to have a widget that pulls the data from the API via websocket on front end and i don`t want to use attributeservice as it is not giving me the timeseries, only attributes

**Comment by amizer12** [comment]
Got it - i pull it form the browser cookie - it's all there:
```
localStorage.getItem('jwt_token')
localStorage.getItem('refresh_token')
```

**Comment by ashvayka** [comment]
You should not use this directly. One should use [Subscription Object](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#subscription-object) with dataKeys type = 'timeseries'
