### ISSUE TITLE
[Question] how to call external rest api with https url inside widget 

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3429]
Could anyone help me how to call rest api inside widget ?
Thingsboard: 3.1.1 PE

**Comment by amizer12** [comment]
It is better to do it via websocket - this is how all the out of he  box widgets are created.
It is pretty easy, but the thing i'm struggling with is how to get the token from the widget scope of the current user.
The rest is pretty easy: https://thingsboard.io/docs/user-guide/telemetry/#example

**Comment by anhdv1979** [comment]
I would like to call external rest api from widget !!!

**Comment by Karabiy** [comment]
you can invoke the rule chain from the widget (as it is done for the input widget, as an example) and have the external rule node "REST API Call" to be set for those reasons
you can refer to this link regarding the REST API Call rule node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/

**Comment by anhdv1979** [comment]
I have to deal with rest api response inside the widget for further process. pls kindly check if your web-ui supports something like 
1. var $http = self.ctx.$scope.$injector.get('$http');
and then call
2. $http({ method: 'GET', url: 'https://jsonip.com/' }).
  success(function (data, status, headers, config) {
      console.log('worked');
    // ...
  }).
  error(function (data, status, headers, config) {
      console.log('notworked');
    // ...
  });
but it seems that I get eror just as (1) declare.

**Comment by amizer12** [comment]
@anhdv1979 do you need to update the dat aor only read them ? if read go with websockets, they work like a charm with minimum overhead and connect nicely with any reactive framework you build your widget on.
Get the token from cookie, and get entityID  from either widget context or via ewbsocket as well and initiate the connection.

**Comment by amizer12** [comment]
> you can invoke the rule chain from the widget (as it is done for the input widget, as an example) and have the external rule node "REST API Call" to be set for those reasons
> you can refer to this link regarding the REST API Call rule node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/

@Karabiy 
I can invoke rule node in rule chain form the widget ?? **Holy crap i wasn`t aware of this.**
How do i do that - i`ve checked input widgets and they all use attributeService to update the values, i haven`t seen any code related to launching or connecting to the rule engine.
Can you add some insights on how to launch the rule chain or external node from widget ?

**Comment by anhdv1979** [comment]
Maybe you misunderstand my question. I have another system with its own rest api. I need to get response data after call rest api within the widget and do further work. Any method ? Http client or XMLHttpRequest ?

**Comment by amizer12** [comment]
Got it - then http client is the way to go if you want to do it within the
code of the widget. Think about also involving the rest api call in rule
node and push the response data to the device in thingsboard as their own
attributes, then it`s way easier to create any widget since you will be
working on this data as a native TB Device attributes - just a thought.

czw., 10 wrz 2020 o 10:40 anhdv1979 <notifications@github.com> napisał(a):

**Comment by anhdv1979** [comment]
To be frank in my case I have to call http client or something like that within the widget ? Is it possible ? how ?
Many thanks

**Comment by DavidR-fr** [comment]
Hi

It seems it is possible to do that by embedding such code in the widget:
const xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (xhttp.readyState != 4) return;
    console.log(xhttp.status);
    console.log(xhttp.responseText);
}

xhttp.open(method, url);
xhttp.send();

but for me it doesn't work. Can you try on your side ?

**Comment by escalanterj** [comment]
Any solution on this topic? I have the same problem
