### ISSUE TITLE
How to do translation for raw gps latlng in map widget

### ISSUE THREAD

**Issue by xjz** [thingsboard/thingsboard#343]
Google map is blocked for some known reasons, so we recently added a new map from a chinese map provider to TB, the problem is that we must translate  the raw gps latlng by using rest api before feed it to the map, it is an async operation and seems impossible to do this translation in map's createLatLng,any suggestions? great thanks !

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
You can add this functionality in the Thingsboard gateway https://github.com/thingsboard/thingsboard-gateway. This is not available yet in TB and will be part of https://github.com/thingsboard/thingsboard/issues/322
