### ISSUE TITLE
[Bug] Rule Chain REST API Call

### ISSUE THREAD

**Issue by felixmondelo** [thingsboard/thingsboard#3434]
**Describe the bug**
I included an external node in my Rule Chain to invoke a GET method on a REST API, but I get always io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information.

The REST API is in local machine and is working perfect.

**Your Server Environment**

* own setup
  * local infrastructure 
  * ThingsBoard Version 3.1.1
  * OS Name and Version Windows 10

**To Reproduce**
1. Go to Rule Chain
2. Click on Root Rule Chain
3. Add an external node REST API CALL.
4. Invoke a GET method on a local REST API.

**Expected behavior**
The REST API is invoked without errors.

**Screenshots**
![RuleChain](https://user-images.githubusercontent.com/14011841/92624153-785d1000-f2c7-11ea-9f26-a637612d8cdc.png)

**Comment by Karabiy** [comment]
please, set the simple client HTTP factory, so that those should be okay

**Comment by felixmondelo** [comment]
Ok, with that check works.
