### ISSUE TITLE
[Question] Rule Chain JS Nodes

### ISSUE THREAD

**Issue by felixmondelo** [thingsboard/thingsboard#3437]
**Component**

 * Rule Engine
 * Installation

**Description**
Is any configuration related to Rule Chain JavaScript nodes (Log, Filter Script, Transform Script, ...)? This components are not working, but no error is logged.

If I try to Test the scripts in the Rule Chain editor, I get a Nullpointer exception (I explained this point on Bug  #3425).

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.1.1
 * Browser: Chrome

**Comment by Karabiy** [comment]
it seems tobe okay on my side. Please, make sure to install the Java package properly. Also, in case if the issue persists, I recommend you to proceed on using the Linux or try to have the docker installation for the Windows to be set. The issue should not persists in case if the docker deployment being done
you can refer to this link regarding the windows docker installation: https://thingsboard.io/docs/user-guide/install/docker-windows/

**Comment by felixmondelo** [comment]
Finally, I install the product on Ubunto and is working fine.
