### ISSUE TITLE
[Bug] Entities hierarchy widget nodeCtx always level 1

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#3438]
**Describe the bug**
When setting up an entities hierarchy widget, the callbacks for each node is called with a nodeCtx. That nodeCtx always has a level 1 without any parent. As a result the callbacks cannot make a distinction based on the level in the hierarchy.

**Your Server Environment**
* own setup
  * local docker deploy
  * ThingsBoard Version 3.1.1

**Your Client Environment**
* OS: Ubuntu
* Browser: Firefox

**To Reproduce**
1. load the demo tenant
2. login as tenant@thingsboard.org and create a new dashboard with `Thermostat Alarms` as a single entity alias.
3. create a hierarchy widget using the `Thermostat Alarms` entity alias. In the advenced tab fill in the following code in the `node relations query function`:
```
console.log("nodeCtx", nodeCtx)
var entity = nodeCtx.entity;
var query = {
    parameters: {
        rootId: entity.id.id,
        rootType: entity.id.entityType,
        direction: "FROM",
        maxLevel: 3
    },
    filters: [{
        relationType: "ToAlarmPropagationAsset",
        entityTypes: []
    }]
};
return query;
```
4. Click save and inspect the console logging: there's a weird `TEST DEV1` node although not shown and all the other nodes have level 1 
```
11:57:22.875 nodeCtx 
{…}
data: Object {  }
entity: Object { id: {…}, name: "TEST DEV1" }
level: 2
parentNodeCtx: Object { entity: {…}, data: {}, level: 1 }
<prototype>: Object { … }
11:57:22.904 nodeCtx 
{…}
childrenNodesLoaded: true
data: Object {  }
entity: Object { id: {…}, name: "Thermostat Alarms", label: "Thermostat Alarms" }
level: 1
parentNodeCtx: undefined
<prototype>: Object { … }
11:57:23.075 nodeCtx 
{…}
childrenNodesLoaded: true
data: Object {  }
entity: Object { id: {…}, name: "Thermostat T2", label: "Thermostat T2" }
level: 1
parentNodeCtx: undefined
<prototype>: Object { … }
11:57:23.076 nodeCtx 
{…}
childrenNodesLoaded: true
data: Object {  }
entity: Object { id: {…}, name: "Thermostat T1", label: "Thermostat T1" }
level: 1
parentNodeCtx: undefined
<prototype>: Object { … }
```
![Screenshot from 2020-09-10 12-13-52](https://user-images.githubusercontent.com/1818153/92716504-31baf480-f35f-11ea-8058-2f7fe100534d.png)

**Comment by vvlladd28** [comment]
Hi @janbols,
This will be fixed in version 3.3.0
