### ISSUE TITLE
How to show the last data from multiple devices on one output?

### ISSUE THREAD

**Issue by joxxe274** [thingsboard/thingsboard#344]
Hi, i want to show a sum data from multiple devices, i create an asset with related devices, and i want to show a value like [https://demo.thingsboard.io/dashboards/3a1026e0-83f6-11e7-b56d-c7f326cba909?publicId=322a2330-7c36-11e7-835d-c7f326cba909](url) on widget named "Energy Consumed"

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
Hi @joxxe274 . At the moment we manually inject this data from a custom script. The built-in functionality to sumarize groups will be based on https://github.com/thingsboard/thingsboard/issues/322 but not available yet.

**Comment by vparomskiy** [comment]
Please find details how to aggregate incoming telemetry in these tutorials
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/

**Comment by Cody-Hayes97** [comment]
after following these tutorials, the aggregation I get back is often inaccurate. I have two devices that send telemetry every 9-11 seconds yet when I try to aggregate every 10 seconds the data is not synced up. is there no way to make the aggregation immediate and not have to set intervals?
