### ISSUE TITLE
Sigfox connectivity does not work

### ISSUE THREAD

**Issue by ksemmler519** [thingsboard/thingsboard#3446]
* Generic

**Description**
I am using the Thingsboard demo version and trying Sigfox integration of several Sigfox devices we have. I followed all the steps in the tutorial, but something is wrong since I get "no events found" in the section of EVENTS in the menu Integration - please see attachement. I also configured the callback in Sigfox, but actually I am not sure about the section "headers filter" since the tutorial suggests "AccessToken 123"...I wrote as header "https" and as value the rest of the endpoint url - see attachment. Is there anyone who successfully connected Sigfox devices with Thingsboard? What could be the problem? PS: Actually I am not sure if with the demo version one can test Sigfox integration. 

**Environment**

![Screenshot (30)](https://user-images.githubusercontent.com/71043025/92893882-5fb13f00-f41a-11ea-89d4-29567bdb1f47.png)
![Screenshot (31)](https://user-images.githubusercontent.com/71043025/92893884-6049d580-f41a-11ea-85b8-0410bf7d0874.png)
![Screenshot (32)](https://user-images.githubusercontent.com/71043025/92893891-617b0280-f41a-11ea-943b-1b3b4089ccb1.png)

OS:  MIcrosoft Windows 10 Pro
ThingsBoard v.2.4.3PE
 Browser: Firefox 79.0

**Comment by mfalkvidd** [comment]
@ksemmler519 could you add a link or similar to the tutorial you are using, to make sure we are looking at the same stuff.

**Comment by ksemmler519** [comment]
Hi mfalkvidd,
Yes. This is the link to the turorial on "how to setup SigFox Integration" 0:47/4:38 https://thingsboard.io/docs/user-guide/integrations/sigfox/. Thanks in advance!

**Comment by ksemmler519** [comment]
Hi mfalkvidd,
Yes. This is the link to the turorial on "how to setup SigFox Integration" 0:47/4:38 https://thingsboard.io/docs/user-guide/integrations/sigfox/. Thanks in advance!
