### ISSUE TITLE
[Bug] Impossible connexion with Firefox ESR

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3447]
Hello

Many of our customers are experiencing very difficult connections to ThingsBoard instances that we manage.

Just by trying to load the homepage, the network tools show that the CSS stylesheets are downloaded, a handful of JS scripts as well, but then the browser almost freezes and displays this warning ribbon at the top:

![image](https://user-images.githubusercontent.com/39315/92894746-23caa980-f41b-11ea-8c0f-2a923aea6f43.png)

We have eliminated network related issues, by trying to connect from different places (so different IP addresses).
So it looks like that there's something fishy going on at the browser level. Looks like Firefox 68 (July 2019) is not compatible with TB 3.0.1. Do you have any clues on what could go wrong? Are there any missing polyfills for this version?

Thanks for your help

* Thingsboard  3.0.1PE
* OS: Windows
* Browser: Firefox
* Version: 68 ESR

**Comment by vvlladd28** [comment]
Hi @Delapouite,

Thank you for your report. We have already fixed this problem in TB PE 3.1.0.
