### ISSUE TITLE
[Question] Transform Payload in Rule Engine

### ISSUE THREAD

**Issue by felixmondelo** [thingsboard/thingsboard#3448]
**Component**
 * Rule Engine

**Description**
I need to generate a new JSON in the Root Rule Chain, this new JSON is different from the input. I am using the script node to add new nodes.

I need to add JSON node names with @, for example:

input message > { "temperature" : 24}
output message > { "@temp": 24}

How can achieve this?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.1.1
 * Browser: Chrome

**Comment by Chabrol** [comment]
Something like this should work in an transformation script:
```
msg["@temp"] = msg.temperature;
delete msg.temperature;
```

**Comment by felixmondelo** [comment]
It works!!!
