### ISSUE TITLE
Why should I refresh every time I load tencent map

### ISSUE THREAD

**Issue by stormwrym** [thingsboard/thingsboard#345]
it was always blank  When I opened tencent map,however Normal display after refresh.

**Comment by ashvayka** [comment]
We don't have tencent maps in ThingsBoard AFAIK. What map are you talking about?

**Comment by stormwrym** [comment]
Hi @ashvayka Thank you for reporting this problem!  it is a map of China and i added it to this project.However ,There are two problems . number one As you can see above.  number two i have no idea which method to write  latitude and longitude of the standard translate into the longitude latitude of tencent map

**Comment by ashvayka** [comment]
Hi @stormwrym . You have probably have not contributed this back to our project. I don't see any tencent maps in open-source code base. We do not provide support for code that is not contributed back to open-source in github pages.
