### ISSUE TITLE
[Question] how to get telemetry value from duration within widget

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3450]
I have an use case similar to thingsboard smart meter with increasing total power key.
how to get subtraction total power from duration (from date, to date) within widget ? Pls do not give me thingsboard example link because I read them so many times.
I need to call rest api for max (from - to date), min & them substract ?
Very appreciated with any suggestion.
P.s: its seem that I could not find telemetryService to fetch data & userService doesn't have getJwtToken() ?????
* ThingsBoard: 3.1.1 PE

**Comment by Ultrazombie** [comment]
Hello @anhdv1979
Is your problem still relevant?
