### ISSUE TITLE
Is it possible to set device / asset limit on Tenants? (TB PE)

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3451]
For Multi-Tenants set-up, the first settings I need is device and asset limits. This way I set  what license package the Sub-Tenant has.

Is this possible to do already? Otherwise it is an important one to have.

A part for setting the limits, it can be awesome to have a report in the System Admin dashboard for current/monthly/history usage.

Thanks!

**Comment by PovitruliaV** [comment]
Hi @t0mZ4,
Yes, you can do this on tenant profile configuration in your sysadmin account 
![image](https://user-images.githubusercontent.com/98046079/174821344-4bd2cd78-e061-4458-b3a4-e432eb006b79.png)

Regards
