### ISSUE TITLE
Performance issues with dashboard

### ISSUE THREAD

**Issue by LeonardoFurini** [thingsboard/thingsboard#3454]
Hello, I would like to know if there are any limitations for the widgets available on the dashboard. I'm using using the Cards widget to solve for multiple devices, and when importing the data the dashboard is extremely slow to make the transitions.

Is there a safe amount of data to guarantee performance? Is the limitation in the browser I am using?
Tanks!!

![image](https://user-images.githubusercontent.com/20671517/93039118-111fc280-f61d-11ea-840e-21d623f5078a.png)

**Comment by yefimov-andrey** [comment]
The browser shouldn't matter for this, but the amount of data for sure will.
Does it lag on client or server side? (If it lags on client side, the whole browser will become unresponsive)
