### ISSUE TITLE
[Question] X-Authorization vs Authorization HTTP header

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3458]
Hello

While interacting with the API I often get `401` errors because I use the `Authorization` HTTP header by "mistake" instead of the one prefixed with a `X-` which is `X-Authorization`.

Any reason why this choice was made? From my understanding and looking at the RFC : https://tools.ietf.org/html/rfc7235#section-4.2, `Authorization` should be perfectly valid, the `X-` prefix should only be used for non-standard headers.

Thanks

**Comment by Ultrazombie** [comment]
We don't see the point in changing it. We do not plan to change it.

**Comment by lackovic** [comment]
I think the OP is asking the reason for the choice, he is not asking to change it.

I am also interested in knowing the reason.
