### ISSUE TITLE
[Bug] When using widgets, chrome does not respond

### ISSUE THREAD

**Issue by 154386670** [thingsboard/thingsboard#3464]
**Describe the bug**

When using the control widget, there is no problem adding the first control widget. When you continue to add the second control widget, chrome has no response and the page is stuck.
The operation process is as follows:
Login----Click "Dashboard"-Click the "+" sign in the lower right corner, select "Control widgets", select any control widgets to add to the "Dashboard", there will be no corresponding situation in Chrome，This happened on both the demo platform and my own server。

**Your Server Environment**

* demo.thingsboard.io
* http://47.108.198.14/
username:tenant@thingsboard.org
password:tenant

* own setup
  * ThingsBoard Version is 3.1
  * OS Name is CentOS 7.8 docker 

**Your Client Environment**
**Desktop (please complete the following information):**
* OS: MacOS Catalina 10.15.6 
* Browser chrome
* Version 85.0.4183.102

**Your Device**
Unused device access, only used in the platform

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'add'
3. Scroll down to 'Control widget'
4.Add more than 2 control widgets

**Screenshots**

![image](https://user-images.githubusercontent.com/20450625/93189249-7f2acd80-f774-11ea-91a6-43efb9b84be2.png)

![image](https://user-images.githubusercontent.com/20450625/93189311-9073da00-f774-11ea-84bc-401bebb16b4b.png)

**Comment by 154386670** [comment]
This bug will appear every time when you use it

**Comment by jacksun101** [comment]
Yes, I have this problem too on my licensed instance and the version number is v3.1.1PE. Please help and fix it.

**Comment by 53tang** [comment]
safari browser seems ok

**Comment by fbenpao** [comment]
Yes, I have this problem too

**Comment by Ultrazombie** [comment]
does not reproduce on the latest version
