### ISSUE TITLE
MQTT with SSL connection

### ISSUE THREAD

**Issue by Ktysai** [thingsboard/thingsboard#3465]
**Description**
With NO SSL, I can acces the machine (UBUNTU 18 & TB CE ) from Win10 and from the Ubuntu itself.

With SSL enabled and the self signed certificate I still cannot connect. my error:

`File "one-way-ssl-mqtt-client.py", line 50, in <module> client.connect("localhost", 8883, 1) File "/home/linuxuser/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 937, in connect return self.reconnect() File "/home/linuxuser/.local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1100, in reconnect sock.do_handshake() File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake self._sslobj.do_handshake() File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake self._sslobj.do_handshake() ConnectionResetError: [Errno 104] Connection reset by peer`

Any suggestions?

**Environment**
 * OS:  Ubuntul 18
 * ThingsBoard: 3.1.1 CE

**Comment by Karabiy** [comment]
please, try to proceed first with the example configuration to be set ( you can refer for this link to those: https://thingsboard.io/docs/user-guide/mqtt-over-ssl/#example-of-configuration ) 
after those being applied, you can use emulator as for the access token based authentication: https://thingsboard.io/docs/user-guide/access-token/
in order to validate whether there are any kind of an issues related to the particular system settings you are using.

**Comment by Ktysai** [comment]
@Karabiy thank you!

Please can you amend that tutorial and specify the changes needed also in the **thingsboard.yml** file?

It will be veeery useful for n00b like myself :) TB, is a great platform, but sometimes the tutorials lack some 'n00b' attention :)

I have bolded all the changes made there.

  # Local MQTT transport parameters
  mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: "${MQTT_ENABLED:true}"
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    bind_port: "${MQTT_BIND_PORT:**8883**}"
    timeout: "${MQTT_TIMEOUT:10000}"
    netty:
      leak_detector_level: "${NETTY_LEAK_DETECTOR_LVL:DISABLED}"
      boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
      worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
      max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"
      so_keep_alive: "${NETTY_SO_KEEPALIVE:false}"
    # MQTT SSL configuration
    ssl:
      # Enable/disable SSL support
      enabled: "${MQTT_SSL_ENABLED:**true**}"
      # SSL protocol: See http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
      protocol: "${MQTT_SSL_PROTOCOL:TLSv1.2}"
      # Path to the key store that holds the SSL certificate
      key_store: "${MQTT_SSL_KEY_STORE:mqttserver.jks}"
      # Password used to access the key store
      key_store_password: "${MQTT_SSL_KEY_STORE_PASSWORD:**your_password**}"
      # Password used to access the key
     key_store_password: "${MQTT_SSL_KEY_STORE_PASSWORD:**your_password**}"
      # Password used to access the key
      key_password: "${MQTT_SSL_KEY_PASSWORD:**your_password**}"
      # Type of the key store
      key_store_type: "${MQTT_SSL_KEY_STORE_TYPE:JKS}"

**Comment by PankajHack** [comment]
hey did you got the solution please help me through this
