### ISSUE TITLE
https://thingsboard.io/docs/user-guide/install/kubernetes/ 404 page

### ISSUE THREAD

**Issue by zhangchunsheng** [thingsboard/thingsboard#3468]
https://thingsboard.io/docs/user-guide/install/kubernetes/

The document is not exist.

```
404 Error!
Sorry, this page was not found. :(
```

**Comment by Karabiy** [comment]
please, specify from which exact page you have found a link for those.

**Comment by zhangchunsheng** [comment]
> please, specify from which exact page you have found a link for those.

https://thingsboard.io/docs/user-guide/install/kubernetes/

It's your website.
