### ISSUE TITLE
http://xxx:32776/api/noauth/oauth2Clients 404 (Not Found)

### ISSUE THREAD

**Issue by zhangchunsheng** [thingsboard/thingsboard#3469]
Are you sure this can work fine?

```
Execute the following command to start services:

$ ./docker-start-services.sh

After a while when all services will be successfully started you can open http://{your-host-ip} in you browser (for ex. http://localhost). You should see ThingsBoard login page.

Use the following default credentials:

System Administrator: sysadmin@thingsboard.org / sysadmin
```

**Comment by Karabiy** [comment]
which exact instruction you are referring to? 
pleas,e specify which exact issue you are facing. provide us with the thingsboard logs which you receive.

**Comment by zhangchunsheng** [comment]
> which exact instruction you are referring to?
> please, specify which exact issue you are facing. provide us with the ThingsBoard logs which you receive.

I don't understand the url http://{your-host-ip}, there is no port.

**Comment by brucedong2016** [comment]
I use k8s deploye tb-web-ui project,it show the same problem.
Is there any issue in the front source code?
Please check that,thanks. @ashvayka 
![image](https://user-images.githubusercontent.com/2783137/93880941-cedb3d00-fd10-11ea-879e-b02d485c0d94.png)

**Comment by Doyle-net** [comment]
After the microservices are deployed, the services are running normally. But the oauth2Clients interface 503 error occurs when I access thingsboard. Which service log should I check?
![image](https://user-images.githubusercontent.com/7744216/96333968-cf60bc80-109f-11eb-8bb4-34cd26caf6c8.png)
