### ISSUE TITLE
[Question] Update device "type" after device is created

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3478]
**Component**

  * Generic

**Description**
If I use the REST API /api/device for creating a device with a particular "type", once device is created with a particular type how can I update the "type" using REST API?

**Environment**

 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: 3.0.1 CE
 * Browser: Chrome

**Comment by ashvarma-git** [comment]
If it is possible in Web UI, it should be possible through REST API. But I don't see a way to do it given the description of Swagger UI.

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use this API for your purpose:
https://demo.thingsboard.io/swagger-ui.html#!/device-controller/saveDeviceUsingPOST

**Comment by ashvarma-git** [comment]
What are the minimum attributes needed for this saveDevice call. Once a device is created, later I have already tried to update "type", by providing following as application/json input:

```
{
  "name": "existing_unique_name",
  "type": "new_type_string"
}
```

But this doesn't result in update of the type.

**Comment by ChantsovaEkaterina** [comment]
@ashvarma-git, you need to pass the whole device object, not only separate fields.

**Comment by ashvarma-git** [comment]
Whole object as in every field as below -

```
{
  "additionalInfo": "string",
  "createdTime": 0,
  "customerId": {
    "id": "string"
  },
  "id": {
    "id": "string"
  },
  "label": "string",
  "name": "string",
  "tenantId": {
    "id": "string"
  },
  "type": "string"
}

```

Why are all fields needed when the only thing you need to identify is the unique device for which "type" is being updated? Id I can understand but what is the relevance of setting tenantid, label, createdTime etc again when the device is already created and assigned to a customer under a tenant?

**Comment by ashvarma-git** [comment]
Hi,

Can you please reply about which fields are minimum in order to update a device "type"?
Thx.

**Comment by ChantsovaEkaterina** [comment]
Hi, @ashvarma-git 
As I wrote, you need to pass all parameters, this way the API works. 
If you pass only _id_, _name_, and _type_, your request will be successful and deviceType will be changed, but all other device properties such as _label_, _additional info_, and others become empty or reverted to default.

**Comment by ashvarma-git** [comment]
I can understand if some fields like additionalInfo, label etc become defaults. But what I am seeing when passing only id, name and type is that the device information is not updated at all.
So my real question is what fields are minimum required to actually trigger an update of the device information.
I don't really use additionalInfo or label. createdTime should set at backend automatically.
So I can set customerId, id, name, type and tenantid. Is that sufficient?

**Comment by YevhenBondarenko** [comment]
Hi, @ashvarma-git 
Try to use this:
```
{
  "id": {
    "entityType": "DEVICE",
    "id": "YOUR DEVICE ID"
  },
  "name": "T1",
  "type": "thermostat"
}
```

**Comment by ashvarma-git** [comment]
Yes, this worked finally!
Thanks a lot.
