### ISSUE TITLE
[Question] Display device image on dashboard

### ISSUE THREAD

**Issue by lehnert** [thingsboard/thingsboard#3484]
**Component**

 * UI

**Description**

Hi, I tried following suggestions in #777  to display images on a dashboard. I'm encoding an image as base64 and sending it from a device to my thingsboard. I'm currently creating an image map widget and setting the image URL source entity alias to "Pi Camera" and the Image URL source entity attribute to "picture". Pi Camera is the name of the entity alias for that dashboard of the device "Pi Camera 1" which has a client-side attribute "picture". I have confirmed that the base64 encoding works as I can use the REST api to ask for the picture attribute from that device and I can visualise it in a base64 decoder script. Currently the New Image Map widget just shows up as a blank white image and nothing else. Any help to display image from a camera device would be appreciated.

**Environment**
 * OS:  Ubuntu

**Comment by lehnert** [comment]
I managed to display images using a html value card with the following html:

`<div class='card'>
    <div class='content'>
        <div class='column'>
            <h1>Latest Image</h1>
            <img src='data:image/jpeg+xml;base64,${#0}' style="transform:rotate(90deg);" height="75%"/>
        </div>
    </div>
</div>`

My problem now is that I can't get it working for images greater than 640x480 resolution. I thought it might be due to mqtt max json string length but I believe that is 0. What else might cause the mqtt transport system to not work with large image sizes? It is being sent as an attribute.

**Comment by t0mmyz7** [comment]
interested in this as well.

**Comment by lehnert** [comment]
So the following html code works to display an image and the issue I was having with streaming larger images was caused by the thingsboard conf parameter NETTY_MAX_PAYLOAD_SIZE having a default of 65536. I'm setting it to NETTY_MAX_PAYLOAD_SIZE=1048576 and that's currently working for a 1920x1080 rgb image encoded in base64.
```
<div class='card'>
    <div class='content'>
            <img src='data:image/jpeg+xml;base64,${#0}' style="transform:rotate(90deg);" height="50%"/>
    </div>
</div>
```

**Comment by t0mmyz7** [comment]
Hi chri
Can you share your full widget configuration with screenshot or perhaps
export of the json?

**Comment by lehnert** [comment]
Sure, export of widget below as couldn't attach as json file (should work if you save raw text below to .json file):
{
  "widget": {
    "isSystemType": true,
    "bundleAlias": "cards",
    "typeAlias": "html_value_card",
    "type": "latest",
    "title": "New widget",
    "sizeX": 7.5,
    "sizeY": 3,
    "config": {
      "datasources": [
        {
          "type": "entity",
          "name": null,
          "entityAliasId": "5d006426-ddd2-bde4-1040-4666f419bed2",
          "filterId": null,
          "dataKeys": [
            {
              "name": "image",
              "type": "attribute",
              "label": "image",
              "color": "#2196f3",
              "settings": {},
              "_hash": 0.1308451951953915
            }
          ]
        }
      ],
      "timewindow": {
        "realtime": {
          "timewindowMs": 60000
        }
      },
      "showTitle": false,
      "backgroundColor": "#fff",
      "color": "rgba(0, 0, 0, 0.87)",
      "padding": "0px",
      "settings": {
        "cardCss": ".card {\n   width: 100%;\n   height: 100%;\n   border: 2px solid #ccc;\n   box-sizing: border-box;\n}\n\n.card .content {\n   padding: 20px;\n   display: flex;\n   flex-direction: row;\n   align-items: center;\n   justify-content: space-around;\n   height: 100%;\n   box-sizing: border-box;\n}\n\n.card .content .column {\n   display: flex;\n   flex-direction: column;    \n   justify-content: space-around;\n   height: 100%;\n}\n\n.card h1 {\n    text-transform: uppercase;\n    color: #999;\n    font-size: 20px;\n    font-weight: bold;\n    margin: 0;\n    padding-bottom: 10px;\n    line-height: 32px;\n}\n\n.card .value {\n    font-size: 38px;\n    font-weight: 200;\n}\n\n.card .description {\n    font-size: 20px;\n    color: #999;\n}\n",
        "cardHtml": "<div class='card'>\n    <div class='content'>\n            <img src='data:image/jpeg+xml;base64,${#0}' style=\"transform:rotate(90deg);\" height=\"50%\"/>\n    </div>\n</div>"
      },
      "title": "New HTML Value Card",
      "dropShadow": false,
      "enableFullscreen": true,
      "widgetStyle": {},
      "titleStyle": {
        "fontSize": "16px",
        "fontWeight": 400
      },
      "useDashboardTimewindow": true,
      "showLegend": false,
      "actions": {}
    },
    "row": 0,
    "col": 0,
    "id": "d53f5f17-95a0-145f-6da0-6ed46d415449"
  },
  "aliasesInfo": {
    "datasourceAliases": {
      "0": {
        "alias": "Pi Camera 2",
        "filter": {
          "type": "singleEntity",
          "resolveMultiple": false,
          "singleEntity": {
            "entityType": "DEVICE",
            "id": "8ce6fcd0-fc21-11ea-939a-4f1b2edc8dfc"
          }
        }
      }
    },
    "targetDeviceAliases": {}
  },
  "filtersInfo": {
    "datasourceFilters": {}
  },
  "originalSize": {
    "sizeX": 5,
    "sizeY": 8
  },
  "originalColumns": 24
}

**Comment by kleinsimon** [comment]
Hi all, 

I try to accomplish the same but with client-side attributes instead of telemetry. This way I want to have the latest image from the device but dont store it as telemetry in the DB. Is there some way to address client side-attributes in the widget?

**Comment by kleinsimon** [comment]
Ok I think I had something wrong in the entity alias definition. I created a widget from the device attribute directly and then I had a working definition which I could use in the image widget. Now its working, but still flickering strongly. I will look deeper in that issue.

**Comment by lehnert** [comment]
Hi Mohamed,

as a snippet of python, it would look like this:

```python3
import base64
import io
import requests
from picamera import PiCamera

# Capture the image
camera = PiCamera(resolution=(640, 480))
stream = io.BytesIO()
camera.capture(stream, 'jpeg')
encoded_img = base64.b64encode(stream.getvalue())

# Post the image to thingsboard
access_token = "YOUR_DEVICE_TOKEN"
requests.post(f"http://localhost:80/api/v1/{access_token}/attributes<http://localhost:80/api/v1/%7baccess_token%7d/attributes>", json={'image': encoded_img})
```

Then at the thingsboard end, you need a custom widget that reads an attribute value and sends it to the src attribute of an img tag.
Note that we're using attributes rather than telemetry so that it doesn't form a time series.


For IP reasons we cant share the code directly.

Kind regards,

Dr Chris Lehnert
Chief Investigator | Senior Lecturer

***@***.***

School of Electrical Engineering and Robotics | Science and Engineering Faculty |
Address: S-Block 1161 Gardens Point Campus, 2 George St Brisbane, QLD 4000 |
T: +61 7 3138 2483  | ***@***.******@***.***> |  https://research.qut.edu.au/qcr/
Web: https://staff.qut.edu.au/staff/c.lehnert | Linkedin<http://www.linkedin.com/in/clehnert> | Twitter: @ChrisLehnert<https://twitter.com/ChrisLehnert>

I acknowledge the Turrbal and Yugara, as the First Nations owners of the lands where QUT now stands. I pay respect to their Elders, lores, customs and creation spirits. I recognise that these lands have always been places of teaching, research and learning.

This email and its attachments (if any) contain confidential information intended for use by the addressee and may be privileged. We do not waive any confidentiality, privilege or copyright associated with the email or the attachments. If you are not the intended addressee, you must not use, transmit, disclose or copy the email or any attachments. If you receive this email by mistake, please notify the sender immediately and delete the original email.

CRICOS 00213J
