### ISSUE TITLE
[Question] MQTT Device attribute response took a long time to reply.

### ISSUE THREAD

**Issue by ktannady** [thingsboard/thingsboard#3489]
**Component**

 * Generic

**Description**
Hello, i have successfully requested shared attribute via MQTT API, but the response took too long (20sec to 1 min range), I'm going to use the feature on a battery powered application to notify the device that there is an new firmware version. 20sec to 1 min is quite bad for a battery powered application. is there anyway to make the response faster? or someone has this problem too?

**Environment**
 * ThingsBoard: latest

**Comment by Ultrazombie** [comment]
Hello @ktannady 
Please try version 3.3.4.1. It is much faster. If you reencounter this problem, please describe the workflow
