### ISSUE TITLE
[Question] Data Transformation using Server Attribute

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#3493]
**Component**

  * Rule Engine
 
**Description**
Hi Folks, I would like to know if it is possible to use Server Attributes to be used on data transformation? I mean, my device send key X: value x through http integration, on my device I created a Server Attribute key A: value a. So, for every telemetry received from device I want to be recorded on the database just the result of a - x, for example. I imagine I need to do this at rule engine, but I did not discovered how to call server attributes for this calculation. If anyone could send me some tips or share any code for that I really appreciate. Thanks in advance.

**Environment**
* OS:  Ubuntu 18
 * ThingsBoard: v3.1.1 PE

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use the _Originator Attributes_ rule node to get the attributes in the rule chain.
