### ISSUE TITLE
RPI GPIO Sample Application Link not working

### ISSUE THREAD

**Issue by Corei52500k** [thingsboard/thingsboard#35]
Hello again,

i have just seen your updated documentation, and i was interested in the GPIO Sample and found an URL in the documentaion that is not working.

Both URLs (same target URL) are not working:
Found on page: http://thingsboard.io/docs/samples/demo-account/
URLs are leading to: http://thingsboard.io/docs/samples/demo-account/docs/samples/raspberry/gpio/

![image](https://cloud.githubusercontent.com/assets/24847458/21868782/bd018df8-d854-11e6-8876-8a2f6246cf1e.png)

From the Navigation Tree i think this would be the correct one:
http://thingsboard.io/docs/samples/raspberry/gpio/

Greetings Core

**Comment by ashvayka** [comment]
Fixed! Thank you!
