### ISSUE TITLE
Is it reasonable if customer users have permission to see access token？

### ISSUE THREAD

**Issue by liaow** [thingsboard/thingsboard#350]
Is it reasonable if customer users have permission to see access token？Why？
i think it is unreasonable

**Comment by ikulikov** [comment]
@ashvayka please comment on this.

**Comment by ashvayka** [comment]
I believe this is reasonable. Customer can't change them. Just use in their apps/devices. You may want to contribute a PR that allows to have a "checkbox" with this option for each customer/user.

**Comment by liaow** [comment]
@ikulikov @ashvayka Thx, that is a great idea

**Comment by liaow** [comment]
but in practical use, customer users are not allowed upload any data, so i think it is not reasonable if customer users have permission to see access token by default.
And on this basis, a "checkbox" with special permission option for each customer/user.

**Comment by xjz** [comment]
if customer users are hardware producer,they need save the access token into flash of device,so   they should at least have permission to see

**Comment by ssmaurya** [comment]
I think customer users should have access even to add devices, assets and dashboards, which could be controlled by license based on devices /dashboard/assets limit. This would give tenant and customer flexibility of adding devices on their own based on licensing model
