### ISSUE TITLE
ESP32 Pico Kit GPIO control and DHT22 sensor monitor using ThingsBoard Arduino SDK

### ISSUE THREAD

**Issue by Larbi75** [thingsboard/thingsboard#3502]
**Description**
Hi
I follow all the instruction on https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/.
I'm using thingsboard's librairy from github.
The temperature/humididty widget is ok, 

The issue is that GPIO widget is not working. I can turn ON leds once (first time), but nothing happen if i want to turn the leds OFF.
Any help ?

**Environment**
 * OS:  Debian 10 (buster)
 * ThingsBoard: 3.1
 * Browser: firefox

**Comment by Larbi75** [comment]
Any news ?

**Comment by ufanders** [comment]
@Larbi75 What ESP32 board are you using? You must make sure the LEDs are mapped correctly for your exact board, and that you are using the correct GPIO pin init (open drain, push-pull, pull-up, pull-down, etc.).

**Comment by SimonCS10** [comment]
I have the same. It is only getting state "1", but never "0" from Thingsboard. Also the visualization does not change...

**Comment by jerakis** [comment]
I have the same issue with GPIO state

**Comment by pablolode** [comment]
hello, someone could find the problem of the change in the visualization of the leds?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
