### ISSUE TITLE
[Question] Checkbox on chart to print several timeseries

### ISSUE THREAD

**Issue by B-DAGBERT** [thingsboard/thingsboard#3503]
Hi everyone,

I would like to select wich timeseries is printed on my chart using, for example, some checkbox.

In my case, I want to print a daily, weekly or monthly consumption of my water sensor. I already calculated the consumption but I can't find a way to choose directly on the dashboard wich timeseries is printed on the chart.

Is there a solution to select a timeseries directly on the user interface ? 

Thanks in advance for who could help me.

**Comment by yefimov-andrey** [comment]
If you put several telemetry keys in the chart widget, you can click on the labels under the chart itself to hide them: 
![Screenshot from 2020-09-22 17-01-51](https://user-images.githubusercontent.com/16429767/93892601-5e72f280-fcf5-11ea-9349-832aedb275bf.png)

![Screenshot from 2020-09-22 17-02-00](https://user-images.githubusercontent.com/16429767/93892598-5d41c580-fcf5-11ea-8022-6cc776260d6b.png)

**Comment by B-DAGBERT** [comment]
Thanks for your reply, but that's not what I'm looking for. I've to print data from serveral sensor on the same charts and this way of doing is not very conveniant. 

![image](https://user-images.githubusercontent.com/44493549/93979741-ffa58b80-fd7d-11ea-9c16-dd3914a49c08.png)

Is there a way to change directly the telemetry key from the widget ?

**Comment by B-DAGBERT** [comment]
@yefimov-andrey No idea of how I can do that ?

**Comment by yefimov-andrey** [comment]
If you mean adding new keys without editing the widget, this is not currently possible.
