### ISSUE TITLE
Built from source without Plugins.

### ISSUE THREAD

**Issue by toti1212** [thingsboard/thingsboard#351]
Hi guys.
I have a problem building from sources.

The command to generate the _.jar_ was `mvn clean install -DskipTests` and the command to execute it is `java -jar thingsboard ....`

In the section of Plugins I do not see the plugins of **mqtt**, **rest api**,**kafkka**, etc. When I want to create a new one, in "_device type_" they do not appear as an option either to create them.

I inspect the postgres database and in 'component_descriptor' table I can see this info.

Any idea?

**Comment by volodymyr-babak** [comment]
hi @toti1212 
by default extenstions are not included into application module.
If you would like to see extensions using **_java -jar_** please add **PROJECT_DIR/target/extensions** folder to your classpath of **_java -jar_** command.
