### ISSUE TITLE
[Question] WebSocket Error: error code - 1002 

### ISSUE THREAD

**Issue by B-DAGBERT** [thingsboard/thingsboard#3511]
Hello everyone,

I've got this error message on top of my page when i'm using the platform.

It doesn't impact the functionment of the platform but I would like to remove it ..

How can I solve that please ?

**Comment by Karabiy** [comment]
you can go for the thingsboard.yml and increase the next values:
 max_updates_per_session: "${TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION:300:1,3000:60}"
for example, in ten times, so that 
and also the timeout in 10 seconds 
 max_updates_per_session: "${TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION:3000:1,30000:70}"
so that the issue should not persists

**Comment by B-DAGBERT** [comment]
Thx, I'll confirm you that tomorrow when I'll be back at the office.



Benjamin Dagbert
07 89 46 74 96

**Comment by B-DAGBERT** [comment]
Still have the error even if I increase the max_update_per_session per 10 like you said.

Have I to increase it again ? Or is there another solution ?

**Comment by Karabiy** [comment]
have you restarted the ThingsBoard service after applying new configurations?

**Comment by B-DAGBERT** [comment]
Of corse

**Comment by JavierNR** [comment]
Do you have Haproxy in front of thingsboard server? If so I believe that this code should avoid that error:
`timeout connect 5000ms
 timeout client 50000ms
 timeout server 50000ms
 timeout tunnel  1h`

**Comment by B-DAGBERT** [comment]
No haven't a Haproxy, I just have a PfSense firewall in front the thingsboard server.

This error occur when I pass through the proxy using the external IP adresse of my VM. But when I use an IpSec tunnel and the local adress of my VM. This message nerver appear.

**Comment by vvlladd28** [comment]
HI @B-DAGBERT,
We will fix this problem in the new version, TB 3.2.2. Wait for the release of the new version or do build from source code.

**Comment by SergMeleshko** [comment]
@B-DAGBERT Hello,
Is the issue still relevant?
