### ISSUE TITLE
Get deviceLabel and deviceDescription in Rule Chain

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3524]
Hello !
I am using Thingsboard 3.01.

Please tell me how can I enrich a node with the following variables :

deviceLabel
deviceDescription

I don't know the name of the system variables.

I will attach a picture for better understanding.

Thank You !

![Untitled-1](https://user-images.githubusercontent.com/59779817/94623178-49313180-02bc-11eb-9178-242a8f0356eb.jpg)

**Environment**
OS: Win7 x64
ThingsBoard: 3.0.1
Browser: Google Chrome

**Comment by ChantsovaEkaterina** [comment]
Hello,
You need to use the _Originator fields_ rule node.
![image](https://user-images.githubusercontent.com/17936317/94660619-8faf7c00-030e-11eb-8d84-d4d21101e6bc.png)

Then the needed fields will be added to the metadata.
Additional info will contain the description if it is provided.
![image](https://user-images.githubusercontent.com/17936317/94661155-5f1c1200-030f-11eb-9e21-412e391c318c.png)


If no additional info and label are present _null_ value will be added.
![image](https://user-images.githubusercontent.com/17936317/94660893-fa60b780-030e-11eb-8cbc-910921127e55.png)

**Comment by lmax25** [comment]
Label and additionalInfo are working fine !

Thank You Very Much !

Best Regards !
