### ISSUE TITLE
Support hyphen in email format

### ISSUE THREAD

**Issue by CharlotteEGM** [thingsboard/thingsboard#353]
Hello, 

I'm trying to add a user with an hyphen in the email address, but I'm getting an "invalid format" error. 

It is very classic email format in my company and it is too bad that it is not supported. 

Is it possible to add this format, so the requested user can use the platform ? 

See attached picture, thanks

![image](https://user-images.githubusercontent.com/17477703/31653568-4b72ed8a-b323-11e7-8ecc-6a73eff1c11a.png)

**Comment by ashvayka** [comment]
Hi @CharlotteEGM Just recently we have release v1.3.1 with a fix to this issue. Please see upgrade instruction and it should do the magic :-)

**Comment by CharlotteEGM** [comment]
Great, thanks !

**Comment by CharlotteEGM** [comment]
HI again, i try to build the v1.3.1 from source and i get this error : 

[INFO] Thingsboard Server Tools .......................... FAILURE [0.356s]
[INFO] ThingsBoard Server Application .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.817s
[INFO] Finished at: Tue Oct 17 09:34:01 UTC 2017
[INFO] Final Memory: 15M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tools: Could not resolve dependencies for project org.thingsboard:tools:jar:1.3.1: Failure to find org.thingsboard.common:data:jar:1.3.1 in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by ashvayka** [comment]
What build command are you using?

**Comment by CharlotteEGM** [comment]
Hi, I managed to pass the server tools build with 
$ sudo mvn clean install
Maybe it was a permission problem. 

But i'm still getting stuck with the last "server Application" part. 
Here is the error :

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:24 min
[INFO] Finished at: 2017-10-17T13:18:02Z
[INFO] Final Memory: 60M/449M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/centos/thingsboard/application && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java -jar /home/centos/thingsboard/application/target/surefire/surefirebooter7199580485788457988.jar /home/centos/thingsboard/application/target/surefire/surefire5458450099426937051tmp /home/centos/thingsboard/application/target/surefire/surefire_03212860901774319399tmp
[ERROR] -> [Help 1]


FYI i use maven version 3.5.0, java 1.8.0_144, and centos 7.4 (1708)

**Comment by ashvayka** [comment]
try "mvn clean install -DskipTests"
If you already have TB running you may have conflicts with running version
against http and mqtt port during tests.

Regards,
Andrew

**Comment by CharlotteEGM** [comment]
It worked perfectly, thanks ! I have now upgraded to 1.3.1 and was able to create user with hyphen :)
Thanks again for your help
