### ISSUE TITLE
[Feature Request] SAML support

### ISSUE THREAD

**Issue by winstonhong** [thingsboard/thingsboard#3531]
Currently ThingsBoard has developed OAuth 2.0 relying party.
https://github.com/thingsboard/thingsboard/tree/master/application/src/main/java/org/thingsboard/server/service/security/auth

SAML is another most popular identity federation protocol supported by Spring.
https://spring.io/projects/spring-security-saml

It would be great if ThingsBoard can use Spring Security SAML library to develop SAML service provider.

Docker-running Shibboleth SAML identity provider is available for testing SAML service provider. 
https://github.com/winstonhong/Shibboleth-SAML-IdP-and-SP

**Comment by winstonhong** [comment]
Hello @ssakharova,

Thank you very much for considering SAML service provider support for ThingsBoard. 

This Feature Request is developing SAML service provider for ThingsBoard. 

More details are provided below for your reference.

The SAML service provider (or SAML relying party) support allows ThingsBoard administrator to configure ThingsBoard with a third-party identity provider (such as Okta or OneLogin or inBay’s Zero-Password Authentication) via SAML protocol, then ThingsBoard can leverage third-party identity provider to perform identity authentication. ThingsBoard users do NOT need to remember username/password for ThingsBoard login.

1. Click **SAML login** button on the login page of ThingsBoard,
2. The user is redirected to the authentication page of a third-party identity provider (such as Okta),
3. The user performs the login authentication for the third-party identity provider,
4. The user is redirected back to ThingsBoard with a SAML token,
5. ThingsBoard SAML service provider validates the SAML signature, extract the username from SAML token, and then logs the user in to the home page of ThingsBoard.

I have built a demo for Shibboleth SAML identity provider and SAML service provider at GitHub repository. ThingsBoard SAML SP is parallel with Shibboleth SAML SP in the SAML authentication demo below.

Shibboleth SAML IdP and SAML SP Demo
------------
+ Access the link "https://sp.example.org:2443" to launch the Shibboleth SAML SP demo
+ Click **Login**
+ You are redirected to Shibboleth SAML IdP 
+ Input Username/Password credential (e.g., winstonhong/winston-passwd) and then Click **Login**
+ You are redirected back to reach Shibboleth SAML SP-protected web page

https://github.com/winstonhong/Shibboleth-SAML-IdP-and-SP

**Remarks**
(1) Shibboleth SAML SP was developed using [OpenSAML library](https://shibboleth.atlassian.net/wiki/spaces/OSAML/overview).
(2) ThingsBoard SAMLSP can be developed using [Spring Security SAML library](https://spring.io/projects/spring-security-saml)
Quote "Spring SAML Extension allows seamless inclusion of SAML 2.0 Service Provider capabilities in Spring applications." 
(3) The following GitHub repository implements SAML SP using  [OpenSAML library](https://shibboleth.atlassian.net/wiki/spaces/OSAML/overview).
https://github.com/zeigeist/opensaml

Best regards,

**Comment by ssakharova** [comment]
Hello @winstonhong,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by bharathwebdev** [comment]
Hi team, can i know the status of this, i also need this to support true sso
