### ISSUE TITLE
Alarm Polling Interval Not Found in TB 3.1.1

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3535]
Hello !
I have found a very big problem in TB 3.1.1 :
In Alarm widget I couldn't find Alarm Polling Interval Option in TB 3.1.1 !

As you will see in the attached picture, when I clear or acknowledge one alarm from my browser, because Alarm Polling Interval can't be set in TB 3.1.1, any changes made to any of the alarms (clear or acknowledge) will not be updated in any open sessions
from any other browser or any other computer, except on the browser that is making the change to the alarm.

So, the result will be : ONE ALARM with at least two different statuses !

In the previous version (2.5.2) of TB, by specifying the Alarm Polling Interval, any change made to any alarm, will be matched on any other open session.

In TB 3.1.1 you must do a manual refresh of the page to see the new status of the alarm...

I think this is very wrong !

What can I do to replace the lost Alarm Polling Interval Option ?

All my alarms rule chains are based on the Alarm Polling Interval Option !

Here you have a picture to see for yourself this error and maybe you will understand better what I am trying to say.

Thank you !

![Untitled-1](https://user-images.githubusercontent.com/59779817/94978863-1be8bb80-0528-11eb-9207-ad6779fedc74.jpg)

Environment
OS: Win 7 x64
ThingsBoard: 3.1.1
Browser: Chrome

**Comment by ssakharova** [comment]
Hello @lmax25,

Could you tell me please the problem is still relevant?

Regards
