### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Amrutharajan** [thingsboard/thingsboard#3538]
Any changes set for login page BG colour and FG colour are not reflecting after re login.

In thingsboard portal there are provisions to change the login page background colour and foreground colour. But whenever I use the option and change any of it  and logout. When I logged in again I couldn't find the changes. So can I get the clarity on that ? and how these things are working.

**Your Server Environment**
 cloud.thingsboard.io

**Comment by Ultrazombie** [comment]
Closed, as not active.
