### ISSUE TITLE
How to use Attribute data in Map tooltip widget?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3541]
Hi guys

I am trying to do some logic and to display attribute values in the map tooltip / map color function

it works for timeseries data, but I cannot make it work for attributes:

for attribute key 'active' that is selected in the data source for the widget.

	var active = dsData[dsIndex]['active'];
doesn't work
while the same works for temperature time series in the data sources.

	var temperature = dsData[dsIndex]['temperature'];

What is the correct method here?

@YevhenBondarenko

**Comment by LucasEtchezuri** [comment]
I have the same problem !!  :-(

**Comment by t0mmyz7** [comment]
Any idea about this? @YevhenBondarenko  @ashvayka

**Comment by ChantsovaEkaterina** [comment]
Hello, @t0mmyz7 
The approach you are using to get the attributes/timeseries values is correct.
Could you check, please, if you are addressing attributes by the label, not by key name?

**Comment by t0mmyz7** [comment]
HI @ChantsovaEkaterina 

you are correct, i try again and it does work, what made the difference was to use the value as a string and not boolean.

before I was trying to use the value as boolean

if (active == true) {}

but what works is actually if (active == "true")


thanks for your reply

**Comment by bioshock2k** [comment]
I have the opossite problem ahahah
Works for attributes and timeseries values are ignored...

**Comment by dhaval2017** [comment]
@bioshock2k please share the code

**Comment by bioshock2k** [comment]
var state = dsData[dsIndex]['active'];
var usb = dsData[dsIndex]['vusb'];

if(state=='false')
{
    res='red';
}
else{
if(usb==0.0){
    res='blue';
}
else{
    res='green'
}
}
return res;

The only way i got this to work is to translate the timeseries to an attribute..
