### ISSUE TITLE
[Question] Dashboard error toast - Too many updates!

### ISSUE THREAD

**Issue by Tikarei** [thingsboard/thingsboard#3542]
**Component**
 * UI - Dashboard

**Description**
I have an MQTT nodeJS process that is pushing telemetry to a device in regular intervals, usually 2 seconds. I ran into a bug in my code and somehow the interval got messed up and looks like it's pushing the data way too fast for ThingsBoard because I am getting an error toast on the dashboard that says **Too many updates!**. I can see the telemetry still getting updated multiple times per second even though my nodeJS process is terminated.

How do I get rid of the error? Do I need to clear the Kafka message queue? How do I clear the Kafka message queue?

**Environment**
 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: 3.1.1
 * Browser: Chrome latest

**Comment by yefimov-andrey** [comment]
This error is being shown if you go over the websocket limits. They are configured in the thingsboard.yml file in the following section:
https://github.com/thingsboard/thingsboard/blob/7a34e2a3f53f3e6bba87427e379ed66132bc7360/application/src/main/resources/thingsboard.yml#L37

**Comment by Tikarei** [comment]
@yefimov-andrey Thank you. I understand that I can update the thingsboard.yml file to increase the limits and the error would go away, but the problem is that those limits should be there, I just need to find a way to stop TB from pushing the updates. As I mentioned, I already disconnected the device that was pushing the updates but TB keep receiving them. I assume this was from the message queue. So, would the correct solution be to go clear the queue? Is it possible to delete only messages from that particular device from the queue?

**Comment by ashvayka** [comment]
Hi @Tikarei , if you use Kafka it is not possible (at least easily) to delete only part of the messages from the queue. Please review and configure transport rate limits:

https://github.com/thingsboard/thingsboard/blob/release-3.1/application/src/main/resources/thingsboard.yml#L542

Also, starting 3.2 this rate limits will be configurable in Tenant Profile.

**Comment by Tikarei** [comment]
@ashvayka Thanks, I have already updated the limit. I will be looking forward to update 3.2.

**Comment by fargiolas** [comment]
> This error is being shown if you go over the websocket limits. They are configured in the thingsboard.yml file in the following section:

I have a question about this toast. I'm publishing telemetry with MQTT, qos=1 at about 1000 messages per second (I'm uploading some past telemetry all at once). On the client I get no error, sometimes messages get queued for a bit but it empties quickly and as far as I can tell all messages are being delivered. In the tenant web interface I get this toast though...
Am I losing data? at the moment I don't have access to the TB installation to check the logs and limits but I'd like to understand this purely from a user point of view. My understanding would be that if the transport gives no error, with qos=1 and empty queues all messages should be delivered and stored in the database... so why this error toast?
