### ISSUE TITLE
[Request] Show logo in dashboard when in full screen mode

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3544]
Hi

In many of our commerical use-cases. The end users are not exposed to the menu, and are Full Dashboard mode users only. Problem is, in this view, the white label logo is not shown which hurts the branding and the white-label experience.

I think there is easily room in the top-bar for a slim dashboard.

for example, current view, no white-label/logo experience

![image](https://user-images.githubusercontent.com/31729091/95128092-9e0ff480-0761-11eb-926c-113f96e26c99.png)

can easily have a logo in the top bar or dashboard title bar

companies like their branding showing as much as possible :)

**Comment by Karabiy** [comment]
for now, for those reasons, you can have a use of the html widget, so that you can have those to be set on the bottom with the logo being set their.

**Comment by t0mmyz7** [comment]
Hi guys

we keep running into this request, any chance of adding the White Label logo to the topbar when in full screen!??

@ashvayka @Karabiy 

this html widget solution takes lot of screen space and also Logo is boxed in.

**Comment by mdheer** [comment]
Hi guys, 

Is there already someone working on this feature? If not, I would be happy to try and implement it! Please let me know

Mathieu

**Comment by Karabiy** [comment]
> Hi guys,
> 
> Is there already someone working on this feature? If not, I would be happy to try and implement it! Please let me know
> 
> Mathieu

For those reasons you can contact @vvlladd28 or just proceed with the guide on how to contribute which you can find via this link: https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/

**Comment by ashvayka** [comment]
Hi @t0mmyz7 ,

We will consider adding this to 3.3.0 or 3.3.1. I believe this is relatively easy to add. @vvlladd28 let's discuss this.

**Comment by mdheer** [comment]
Okay thanks! I will contact him. 

> > Hi guys,
> > Is there already someone working on this feature? If not, I would be happy to try and implement it! Please let me know
> > Mathieu
> 
> For those reasons you can contact @vvlladd28 or just proceed with the guide on how to contribute which you can find via this link: https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/

**Comment by mdheer** [comment]
> Hi @t0mmyz7 ,
> 
> We will consider adding this to 3.3.0 or 3.3.1. I believe this is relatively easy to add. @vvlladd28 let's discuss this.

Hi @ashvayka,

Is it possible you meant me? :)

**Comment by mdheer** [comment]
To provide you with some background information: we are a group of 5 students from Delft University of Technology (the Netherlands). For the course Software Architecture, we are required to contribute to an open-source project. We have chosen ThingsBoard as our project and would like to implement this feature to get started and familiarize ourselves with the project.

**Comment by mdheer** [comment]
@ashvayka @vvlladd28 we are working on implementing this feature. We would like to use the logo from the white-labeling configuration, however the source code for white-labeling is not in this repository. Would it be possible to provide us this source code? Or is there another way to implement this feature?

**Comment by ashvayka** [comment]
Hi, @mdheer,
The white-labeling feature is part of ThingsBoard PE and is not part of the community edition. We contribute a lot to open-source and white-labeling, as part of the PE, helps our company to get revenue to continue our contribution. For obvious reasons, we can't share the code of ThingsBoard PE. I understand that you are a group of students that are required to contribute to the open-source project. So, I would like to propose two options:
1) You may add the "Display logo" checkbox setting to the dashboard settings. See the second screen here: https://thingsboard.io/docs/user-guide/dashboards/#settings (https://thingsboard.io/images/user-guide/dashboards/settings/dashboard-settings.png). You may place it before "Display dashboards selection". If checked, you can use a standard API call to fetch and display the default logo (ThingsBoard) there. In this way, ThingsBoard PE users will be able to see the logo that they configured in the white-labeling settings. On the other hand, companies that don't want to use ThingsBoard PE simply replace the logo file in the project, and this feature will work for them as well. Such implementation does not conflict with PE and we will merge it.
2) There are plenty of other features for contribution and if you don't like (1), I can search and provide you with more options. For example, there is an interesting and challenging task to visualize a number of incoming/outcoming messages and errors in the rule chain UI.

**Comment by mdheer** [comment]
Hi @ashvayka, 

Thank you for your reply. We understand that it would not be possible to share the ThingsBoard PE code. We have implemented the feature as you described in 1 and created a merge request. Is this how you had it in mind? @t0mmyz7 
![setting_screenshot](https://user-images.githubusercontent.com/37894626/112066036-f4cd8700-8b65-11eb-804f-dfcf445b7d07.png)
![normalview](https://user-images.githubusercontent.com/37894626/112066048-f8f9a480-8b65-11eb-99f9-407a40136ea7.png)
![without_screenshot](https://user-images.githubusercontent.com/37894626/112066083-0878ed80-8b66-11eb-8dd2-805fe74060fb.png)
![fullscreen](https://user-images.githubusercontent.com/37894626/112066086-0adb4780-8b66-11eb-88fb-3b7b8e33f37f.png)

**Comment by t0mmyz7** [comment]
Nice, few comments:

1. Where do we select the URL for the logo Image?
2. What is the recommended dimension (height/width) for it?
3. Potentially have the option to show the logo only show in full-screen mode of the dashboard, because when dashboard is not in full-view / dashboard-only view, then the main logo is shown.  

thanks for your contribution

**Comment by mdheer** [comment]
Thanks you for your reaction @t0mmyz7. To answer your questions: 
1. You can upload the logo in the thingsboard/ui-ngx/src/assets and add the name in the file dashboard-page.components.ts at line 193. This file can be found in "thingsboard/ui-ngx/src/app/modules/home/components/dashboard-page/". Or replace the current "example.png" by your own logo, then you won't need to change the name in the code. 
2. There is no recommended dimension as the size is adjusted automatically. 
3. This should be relatively straightforward to add. @ashvayka What is your view on this? Only showing the logo when in fullscreen mode or adding another checkbox with the possiblity to enable this?

**Comment by t0mmyz7** [comment]
@mdheer normally if we are not in Dashboard full mode, then the Logo is visible in the main framework

if we are in full screen mode, or if we limit user to dashboard view only, the logo isn't visible.

also having the ability to set a different logo per dashboard opens up some more possiblities as well.

so my suggestion would be

1. checkbox to show logo just in fullscreen mode
2. field to  change logo filename and a tooltip"?" instruction on where to place the logo (will this only work if you build from source or for the .deb as well)? Otherwise can provide URL for logo

**Comment by mdheer** [comment]
@t0mmyz7 , we have implemented your request. The logo is now only visible in fullscreen mode. Also, we have added a textbox in the settings menu where you can specify  the filename you want to use. So to show the logo: 

1. Add the logo file in the assets folder
2. Go to the dashboard settings 
3. Specify the name of your file in the logo field (example_logo.png is used by default)
4. Check the box saying "show logo"
5. Save and close the settings and your logo will be shown in fullscreen mode

**Comment by t0mmyz7** [comment]
@mdheer great work mate
