### ISSUE TITLE
[Question] Error on installation script: Unexpected error during ThingsBoard installation!

### ISSUE THREAD

**Issue by AnderBenito** [thingsboard/thingsboard#3549]
**Component**

 * Installation

**Description**
Hi! Im trying to install the dockerized 2.4.1 version of ThingsBoard on my Ubuntu 20.04. I have followed the guide as it says, but when I run the "docker-install-tb.sh" script I get the following error:

Creating network "docker_default" with the default driver
Creating docker_postgres_1 ... done
Creating docker_redis_1    ... done
Creating docker_tb1_run ... done
Starting ThingsBoard installation ...
08:42:53,640 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:42:53,641 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:42:53,641 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/config/logback.xml]
08:42:53,644 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:42:53,644 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
08:42:53,644 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/config/logback.xml]
08:42:53,784 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:42:53,796 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/config/logback.xml] 
08:42:53,796 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 10 seconds
08:42:53,799 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:42:53,807 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
08:42:53,826 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - setting totalSizeCap to 3 GB
08:42:53,832 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - Archive files will be limited to [100 MB] each.
08:42:53,862 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - No compression will be used
08:42:53,864 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - Will use the pattern /var/log/thingsboard/tb1/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
08:42:53,867 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/tb1/thingsboard.%d{yyyy-MM-dd}.%i.log'.
08:42:53,867 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - Roll-over at midnight.
08:42:53,869 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - Setting initial period to Wed Oct 07 08:32:35 UTC 2020
08:42:53,871 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:42:53,899 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/tb1/thingsboard.log
08:42:53,899 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/tb1/thingsboard.log]
08:42:53,900 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:42:53,901 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:42:53,901 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:42:53,903 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
08:42:53,903 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.google.common.util.concurrent.AggregateFuture] to OFF
08:42:53,903 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:42:53,903 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
08:42:53,903 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:42:53,904 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:42:53,904 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@45ff54e6 - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.4.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:55)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:219)
	at org.postgresql.Driver.makeConnection(Driver.java:407)
	at org.postgresql.Driver.connect(Driver.java:275)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:60)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:151)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: java.net.UnknownHostException: postgres
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:64)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:147)
	... 17 common frames omitted
Unexpected error during ThingsBoard installation!

Also while starting the services and connecting to localhost I get error "503 Service Unavailable" when trying to log in.

Thanks!

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 2.4.1
 * Docker: 19.03.13

**Comment by Strauteka** [comment]
I think, you have to provide more info. 
1.` I have followed the guide as it says,...` !Please link to that guide/script.
2. There is [Thingsboard](https://hub.docker.com/r/thingsboard/tb-postgres/tags) images and examples what you can try. 

From error you can see that TB cant connect to DB `org.postgresql.util.PSQLException: The connection attempt failed.`
Check if container `Creating docker_postgres_1 ... done` is Up and you actually can connect with thingsboard User to It!

**Comment by AnderBenito** [comment]
I followed this guide: https://github.com/thingsboard/thingsboard/blob/v2.4.1/docker/README.md

The error occurs when I run the docker-install-tb.sh script. However, the docker-start-tb script runs with no problem and all containers appear as "Up":

`CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                                      NAMES
ce8011b9d41c        xalauc/haproxy-certbot:1.7.9          "/start.sh"              8 minutes ago       Up 8 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:9999->9999/tcp   haproxy-certbot
0b8b926f6152        thingsboard/tb-node:2.4.1             "start-tb-node.sh"       8 minutes ago       Up 19 seconds       0.0.0.0:32822->8080/tcp                                                                    docker_tb2_1
b78892b91449        thingsboard/tb-node:2.4.1             "start-tb-node.sh"       8 minutes ago       Up 22 seconds       0.0.0.0:32821->8080/tcp                                                                    docker_tb1_1
18c0f25d1b54        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_11
35d632d3ebd9        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_4
c56395f49ee3        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_13
719691999e15        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_5
3feb011e838a        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_10
8cea52e38ad5        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_20
d1da16d6c232        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_3
b45b7b64ce70        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_8
e8f92a05fe62        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_2
d8fd8ab837cd        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_1
da6d038b6d57        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_14
e4cda31ad7dd        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_9
579f32eb0a45        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_19
8019b785e37d        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_18
ae1593b32753        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_16
caed7db5a92c        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_6
4b014e45d56a        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_15
85c7d5c78f5d        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_17
233265596c31        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_12
87d910b3493f        thingsboard/tb-js-executor:2.4.1      "start-js-executor.sh"   8 minutes ago       Up 8 minutes                                                                                                   docker_tb-js-executor_7
3ba014a40619        thingsboard/tb-coap-transport:2.4.1   "start-tb-coap-trans…"   8 minutes ago       Up 8 minutes        0.0.0.0:5683->5683/udp                                                                     docker_tb-coap-transport_1
a7fac39c42e5        thingsboard/tb-mqtt-transport:2.4.1   "start-tb-mqtt-trans…"   8 minutes ago       Up 8 minutes        0.0.0.0:32776->1883/tcp                                                                    docker_tb-mqtt-transport1_1
fcb4f6984cc1        thingsboard/tb-mqtt-transport:2.4.1   "start-tb-mqtt-trans…"   8 minutes ago       Up 8 minutes        0.0.0.0:32773->1883/tcp                                                                    docker_tb-mqtt-transport2_1
53796a67bff1        thingsboard/tb-http-transport:2.4.1   "start-tb-http-trans…"   8 minutes ago       Up 8 minutes        0.0.0.0:32774->8081/tcp                                                                    docker_tb-http-transport2_1
f72fff1b60c7        thingsboard/tb-http-transport:2.4.1   "start-tb-http-trans…"   8 minutes ago       Up 8 minutes        0.0.0.0:32775->8081/tcp                                                                    docker_tb-http-transport1_1
17be9a3ef2d5        wurstmeister/kafka:2.12-2.2.1         "start-kafka.sh"         8 minutes ago       Up 8 minutes        0.0.0.0:9092->9092/tcp                                                                     docker_kafka_1
c4c937cb75f1        thingsboard/tb-web-ui:2.4.1           "start-web-ui.sh"        8 minutes ago       Up 8 minutes        0.0.0.0:32770->8080/tcp                                                                    docker_tb-web-ui1_1
df2058b23294        zookeeper:3.5                         "/docker-entrypoint.…"   8 minutes ago       Up 8 minutes        2888/tcp, 3888/tcp, 8080/tcp, 0.0.0.0:32772->2181/tcp                                      docker_zookeeper_1
7e5c15817302        thingsboard/tb-web-ui:2.4.1           "start-web-ui.sh"        8 minutes ago       Up 8 minutes        0.0.0.0:32771->8080/tcp                                                                    docker_tb-web-ui2_1
a674c6bd14d9        redis:4.0                             "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes       0.0.0.0:32769->6379/tcp                                                                    docker_redis_1
e3f5582681c2        postgres:9.6                          "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes       0.0.0.0:32768->5432/tcp                                                                    docker_postgres_1`

I can connect to the postgres database through pgAdmin and all tables seem to be ok.

Thanks!

**Comment by anmobor** [comment]
Hello @AnderBenito ,
Did you find the solution to this issue? I have the same

**Comment by anmobor** [comment]
Hello @trypzz 

I found the solution, I was installing thingsboard docker and I had a problem with Postgres following the manual, then I forgot the manual and I change the user of the db folder to postres, then It worked fine, that was my solution.
Thank you any way,
Antonio

**Comment by trypzz** [comment]
@anmobor okay, thanks for your feedback.

**Comment by trypzz** [comment]
Hello, @AnderBenito 

Do you have any questions at this time about this issue? Or problem not actual right now?

**Comment by adamwawrzynski** [comment]
@anmobor could You please provide more details (ideally steps to reproduce) to mitigate this error? I am also facing it right now.

Environment:

- Docker version: 20.10.2, build 20.10.2-0ubuntu1~20.04.2
- OS: Ubuntu 20.04 LTS
- Thingsboard: 3.2.2

**Comment by anmobor** [comment]
Hello @adamwawrzynski,
For your type of installation I don't know where to apply the solution I made, try to find the data base volumen and change the user to postgres, only for the catabase volume, not for other volumens. In my case, when I assigned the postgres database in the file system to the postgres user, it worked, but in my deploy I have one docker for thingsboard and another for the database, I don't see for you the database docker and subsequently the volumen, if you find that volumen, is there where you should change the user to postgres.

Best reggards,
Antonio

**Comment by Ultrazombie** [comment]
Closed due to inactivity
