### ISSUE TITLE
[Question] How to configure Thingsboard to make use of more server resources for a higher throughput?

### ISSUE THREAD

**Issue by ysit-thingsboard** [thingsboard/thingsboard#3555]
**Component**
 * Generic

**Environment**
 * OS:  CentOS 8
 * ThingsBoard: 3.1.1 CE in docker cluster
 * docker cluster deployment on one server of 6 vCPUs and 8G RAM
 * Browser: Chrome 85.0.4183.102
 * No additional rule chain configured

**Description**
How to configure Thingsboard to make use of more server resources for a higher throughput?

We are using TB Gateway to convert payload for 100 devices. Each device is sending data at 1 message per second. Each message is converted to 11 datapoints (2 attributes and 9 telemetry). So the TB Gateway is receiving 100 messages per second and should be sending **1100 datapoints per second** to Thingsboard. According to the deployment guide: "The most simple deployment scenario is suitable for up to 300 000 devices with 10,000 messages and **10,000 data points per second** based on real production use cases."

The Gateway has no error in logs and the statistics is 500 events every 5 seconds. 
![image](https://user-images.githubusercontent.com/71913697/95411060-14764780-0958-11eb-8eb4-e609a07c1b39.png)

But Thingsboard has about 30 min of delay after running for 1 hour. The delay increases as time passed. The time is the data time generated at the same server.
![image](https://user-images.githubusercontent.com/71913697/95411469-21476b00-0959-11eb-8821-f7da450d2ccf.png)

All services stays at low resources usage.
![image](https://user-images.githubusercontent.com/71913697/95412265-2c02ff80-095b-11eb-81f2-efc18bf674b2.png)

The server resource usage stays low too.
![image](https://user-images.githubusercontent.com/71913697/95412227-17266c00-095b-11eb-8853-e74f0b522b05.png)

From my observation, Thingsboard can not make use of the server resource even at a higher data rate. I have tried to increase Kafka main queue partition to 25 but it doesn't help at all.

**Comment by baigod** [comment]
I have the same question, please advise me

**Comment by pon0marev** [comment]
Thingsboard uses as many resources as it needs to process messages. If you have message delays, you should set up a kafka queue and a redpanda tool to understand how much delay there is and how many messages are in the queue.
Upgrade to the latest version of Thingsboard as there are many new features for debugging rule chains.
Follow this documentation to get started: https://thingsboard.io/docs/user-guide/troubleshooting/#troubleshooting-instruments-and-tips

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
