### ISSUE TITLE
Does Websocket API change, after v1.3.0 ?

### ISSUE THREAD

**Issue by zhw618** [thingsboard/thingsboard#356]
I developed a webpage using the Websocket API of ThingsBoard.
It worked well with thingsboard v1.2.3.

Yestoday I update thingsboard to the new version( v1.3.1),
the webpage is broken~~~

Does the Websocket API change? Please help!

I sniff the network traffic with  Wireshark tool,
when websocket connected (with v1.2.3), the sent messages and received messages are all plain text,
like this:
 {"tsSubCmds":[{"deviceId":"a7f4a0c0-2e5e-11e7-8375-673c572a5db7","scope":"LATEST_TELEMETRY","cmdId":2}] }

but with thingsboard v1.3.1, the messages transfe in websocket connection, 
are all messy code!!  What happened in new release?

Where is the new websocker api  document?
I'm so sad, now.   Who can help me   : - (  
Thanks very much!

**Comment by ssmaurya** [comment]
API has changed from 1.2.3 to 1.30. Please refer to this 
https://thingsboard.io/docs/user-guide/telemetry/#websocket-api

Most notable change is use of entity id instead of device id.

**Comment by ashvayka** [comment]
Hi! This API is not public now so we have changed it.

instead of deviceId use entityId and add entityType

{"tsSubCmds":[{"entityType":"DEVICE", 
"entityId":"a7f4a0c0-2e5e-11e7-8375-673c572a5db7","scope":"LATEST_TELEMETRY","cmdId":2}] }

Please close the issue if this resolves the error

**Comment by zhw618** [comment]
@ashvayka   Thanks very much! 
 Now it works again.
