### ISSUE TITLE
[Feature Request] API to Change User / Customer password without Email

### ISSUE THREAD

**Issue by sensorthai** [thingsboard/thingsboard#3560]
I am developing Mobile Application with Thingsboard, but I have a problem when customer need to change password, it must send email to a user account, I want customer can change password on the Mobile App.

**Comment by vvlladd28** [comment]
Hi @sensorthai,

This API is already available in ThingsBoard. You may need a method `/api/auth/changePassword`  and body `{"currentPassword":"","newPassword":""} `

**Comment by sensorthai** [comment]
Hi @vvlladd28 
How to use this api. what is the json body?

/api/noauth/resetPassword
/api/noauth/resetPasswordByEmail

**Comment by vvlladd28** [comment]
Hi @sensorthai,

API: `/api/noauth/resetPassword` body: `{"resetToken": "", "password": ""}`
API: `/api/noauth/resetPasswordByEmail` body: `{"email": ""}`

**Comment by shaphiro** [comment]
I suppose, resetToken can only be acquired with an email, correct?

**Comment by kalaohgee** [comment]
Is it possible to get the reset token in any alternative method to email?
