### ISSUE TITLE
Confusion about ToDeviceActorSessionMsg and ToDeviceSessionActorMsg

### ISSUE THREAD

**Issue by xjz** [thingsboard/thingsboard#357]
Name of the two different kinds of Msg is somewhat subtle, how come you give the names to the Msg and what is the right way to read the two names?

**Comment by ashvayka** [comment]
First one is from a device session actor to device actor and second one is vise versa. See architecture guide for more details.

**Comment by xjz** [comment]
@ashvayka thank you
