### ISSUE TITLE
How to get the alarms for one specified device by deviceID

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3571]
Hello !
I am trying to get the alarms for one specified device by deviceID.
And I have:
the device is having 2 alarms
entityType = DEVICE
entityId = b3345c80-049a-11eb-aa16-ab4e7f566144
pageSize = 1
page = 1
Please tell me what I am doing wrong on the following CURL command :
curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer eyJhbGciOiJIUzUxMi0wNDhhLTExZWItYjUzZi1kYmRmZWRlZWViYzAiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMjJlMGZjMjAtMDQ4YS0xMWViLWI1M2YtZGJkZmVkZWVlYmMwIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNjAyNDQxMzgzLCJleHAiOjE2MDI0NTAzODN9.Y30fghkHxWptW8YdBZbhzutG5sGTzpAzBCRqIwDAWPxGIjUJw_MqJRTkDFL7gGyNIlYZFEZ_bwETuviD1AbNBQ' 'http://127.0.0.1:8080/api/alarm/DEVICE/b3345c80-049a-11eb-aa16-ab4e7f566144?pageSize=1&page=1&fetchOriginator=true'

I always get the following response :
{
  "status": 500,
  "message": null,
  "errorCode": 2,
  "timestamp": "2020-10-11T20:43:31.933+0000"
}

Thank You !

**Environment**
Environment
OS: Win 7 x64
ThingsBoard: 3.1
Browser: Chrome

**Comment by ashvayka** [comment]
Page should probably start with 0. @YevhenBondarenko  please check the API link

**Comment by YevhenBondarenko** [comment]
Hi @lmax25,

we have fixed this bug in the 3.2.0 release.

This bug is related to both empty params "search status" and "status".
If you need to search all alarms you can add search status "ANY" and it will work.

**Comment by lmax25** [comment]
The error was because of the missing ANY parameter from search status.
Now it is working fine !
Thank You Very Much !
