### ISSUE TITLE
How to display the number of devices for every related asset

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3577]
Hello !
I have a number of three assets, each asset containing a different number of devices.
I am using an Entities widget to display all the assets.
Please tell me how to display in a custom column of that widget the number of related devices for every asset.
Please look at the attached picture for better understanding.

Thank You !

![image](https://user-images.githubusercontent.com/59779817/95797635-a5eb0e00-0cf8-11eb-8ad6-3f811d2b9cf2.png)

Environment
Environment
OS: Win 7 x64
ThingsBoard: 3.1.1
Browser: Chrome

**Comment by jln-ho** [comment]
+1, I'm currently struggling with this as well! It seems like the default table widget doesn't support this out of the box (I might be wrong, though).

Generally speaking, I guess it would be really useful to have something like "custom columns" for which the displayed value can be computed using some arbitrary javascript function. Conditional formatting would be another great addition.

**Comment by JuliusHarald** [comment]
I did a workaround. I copied the entities-table to my custom widget bundle and added the following code in the `onDataUpdated` function:

`self.onDataUpdated = function() {
    self.ctx.$scope.entitiesTableWidget.onDataUpdated();
    
    var entityRelationService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('entityRelationService'));
    var attributeService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
    
    var attributeScope="SERVER_SCOPE";
    let key = "amountDevices"
    self.ctx.datasources.forEach(entity => {
        if (entity.entityType === "ASSET") { // Without this there is an endless loop in the editor!
            entityRelationService.findByFrom(entity.entity.id)
                .subscribe(relations => {
                    var amountDevices = 0;
                    relations.forEach(relation => {
                        amountDevices++;
                    });
                    let attributes = [{key: key, value: amountDevices}]; 
                    let oldAttributeValue;
                    attributeService.getEntityAttributes(entity.entity.id, attributeScope, [key])
                        .subscribe(oldAttributes => {
                            if(oldAttributes[0].value != amountDevices){
                                attributeService.saveEntityAttributes(entity.entity.id, attributeScope, attributes).subscribe();
                            }
                        });
                }, e => console.log("No Relation"));
        }
    });
}`

But beware that an sysadmin has not the rights to do something with attributes, but thatś what I do. That can lead to an endless loop in the editor and widget-bundle. (Maybe something that could be changed in future releases?)

**Comment by lmax25** [comment]
It is working great !
Thank You Very Much and Best Regards !

**Comment by jln-ho** [comment]
While @JuliusHarald's workaround probably works OK in some or even most cases, I still think this is an interesting feature that could be useful in the "official" table widget. What do you think, @ashvayka?

**Comment by lmax25** [comment]
Hello again !

It will be very nice to have this function included in the next
releases of Thingsboard !

**Comment by santobedi** [comment]
> I did a workaround. I copied the entities-table to my custom widget bundle and added the following code in the `onDataUpdated` function:
> 
> `self.onDataUpdated = function() { self.ctx.$scope.entitiesTableWidget.onDataUpdated();
> 
> ```
> var entityRelationService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('entityRelationService'));
> var attributeService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
> 
> var attributeScope="SERVER_SCOPE";
> let key = "amountDevices"
> self.ctx.datasources.forEach(entity => {
>     if (entity.entityType === "ASSET") { // Without this there is an endless loop in the editor!
>         entityRelationService.findByFrom(entity.entity.id)
>             .subscribe(relations => {
>                 var amountDevices = 0;
>                 relations.forEach(relation => {
>                     amountDevices++;
>                 });
>                 let attributes = [{key: key, value: amountDevices}]; 
>                 let oldAttributeValue;
>                 attributeService.getEntityAttributes(entity.entity.id, attributeScope, [key])
>                     .subscribe(oldAttributes => {
>                         if(oldAttributes[0].value != amountDevices){
>                             attributeService.saveEntityAttributes(entity.entity.id, attributeScope, attributes).subscribe();
>                         }
>                     });
>             }, e => console.log("No Relation"));
>     }
> });
> ```
> 
> }`
> 
> But beware that an sysadmin has not the rights to do something with attributes, but thatś what I do. That can lead to an endless loop in the editor and widget-bundle. (Maybe something that could be changed in future releases?)

Hi, I updated the `onDataUpdated ` of `entities-table` widget. But I'm confused about `Datasource `in the widget. Which `Datasource `should I use to display the number of devices per asset? Is there any extra workaround to get the number of devices? 

Thank you.

**Comment by JuliusHarald** [comment]
Hi,

> But I'm confused about `Datasource `in the widget. Which `Datasource `should I use to display the number of devices per asset?

What `Datasource` do you mean? Inside the code or if you are in a dashboard and want to add a asset as a datasource?
If its the second one, than first have to create `Entity Alias` for the asset(s) you want to have in the table. Than you can add this entity alias as the datasource and choose the attribute "amountDevices" as a key in columns.

**Comment by santobedi** [comment]
@JuliusHarald 
I edited the `Entities table` widget at the widgets library using your code and later used the widget in a dashboard. 

I created the `Entity aliases` as follows: 
<img width="420" alt="2024-01-26 17_00_43-Pixii cloud _ Dashboard" src="https://github.com/thingsboard/thingsboard/assets/10918248/7d6aa7f2-e6a2-453c-a286-8403567c2f74">

Later I used this Entity alias in the modified `Entities table` widget as follows: 

<img width="562" alt="2024-01-26 17_02_02-Pixii cloud _ Dashboard" src="https://github.com/thingsboard/thingsboard/assets/10918248/21c11317-2c25-4314-81a8-e88820505226">

However, I don't see the expected result (number of related devices per asset) in the dashboard. 

<img width="789" alt="2024-01-26 17_04_08-Pixii cloud _ Dashboard" src="https://github.com/thingsboard/thingsboard/assets/10918248/15d72ec9-0805-484a-92fb-323616c6a7f1">

To make sure everything is tested well, I tried to use `"amountDevices"`  and `amountDevices`.

Please correct me if I've missed something. 

Thank you.

**Comment by santobedi** [comment]
@JuliusHarald 
I added a console log in your code: 
<img width="325" alt="console" src="https://github.com/thingsboard/thingsboard/assets/10918248/91effccf-617a-46c7-9cc6-ec62f8ccf6a5">

And checked the Console by using the widget in the dashboard wherein I saw the Assets and their respective number of devices followed by an error. I used four assets to test and I could see their related device number in the console before the error occurred. 

<img width="673" alt="Bug" src="https://github.com/thingsboard/thingsboard/assets/10918248/4ceed14a-0fda-4d3a-bfe1-5784cb78f827">

**Comment by santobedi** [comment]
@JuliusHarald 
I used the console log to print the assets and their respective number of devices: 

<img width="325" alt="console" src="https://github.com/thingsboard/thingsboard/assets/10918248/9bc5ab31-3643-4880-9e0f-4acfc65dd82a">

The console log shows all the assets and their device numbers followed by an error: 

`Uncaught TypeError: Cannot read properties of undefined (reading 'value')`

I'm using Thingsboard PE v.3.6.2.

**Comment by santobedi** [comment]
Finally found the solution. The problem was in the `if` condition where you compare `oldAttributes[0].value! = amountDevices`.

**Comment by zelms** [comment]
I was having issues with getting this to work for me. It took modifying `if(oldAttributes[0].value != amountDevices)` to `if(oldAttributes.length == 0 || oldAttributes[0].value != amountDevices)`. Full code (with some comments) below
```javascript
    //Gets object to be able to read and modify relations of the data source(s) for the widget
    var entityRelationService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('entityRelationService'));
    //Gets object to be able to read and modify attributes of the data source for the widget
    var attributeService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
    
    //Both used later to define a new attribute 
    var attributeScope="SERVER_SCOPE";
    let key = "amountDevices";
    
    //Loop through each datasource for this widget 
    self.ctx.datasources.forEach(entity => {
        //Check if a data source is an asset, because we aren't trying to count devices 
        if (entity.entityType === "ASSET") { // Without this there is an endless loop in the editor!
            entityRelationService.findByFrom(entity.entity.id)
                .subscribe(relations => {   //Use an Angular approach to get list of relations 
                    var amountDevices = 0;
                    //Loop through all relations and count them
                    relations.forEach(relation => {
                        amountDevices++;
                        //relation is an object with properties .from and .to
                        //Both these properties have sub properties .entityType and .id
                    });
                    
                    //To define the key (what you use to name the attribute) and value (what shows up on the widget)
                    let attributes = [{key: key, value: amountDevices}]; 
                    //Get attributes named [key] from an entity. [key] is an array of strings, which in this case has only one value, key 
                    attributeService.getEntityAttributes(entity.entity.id, attributeScope, [key])
                        .subscribe(oldAttributes => {
                            //oldAttributes is a list of attributes (type object) that matched with [key] array 
                            if(oldAttributes.length == 0 || oldAttributes[0].value != amountDevices){  //Added in checking if there are no attributes for this particular asset 
                                //Add attribute 'amountDevices' with value stored in amountDevices 
                                attributeService.saveEntityAttributes(entity.entity.id, attributeScope, attributes).subscribe();
                            }
                        });
                }, e => console.log("No Relation"));
        }
    });
```
