### ISSUE TITLE
[Question] why I cannot access localhost:8080?

### ISSUE THREAD

**Issue by e-infotech** [thingsboard/thingsboard#3582]
Hi,
I have TB on my windows 10 and it didn't have any problem, but today I end java.exe task and after that localhost:8080 does not open and returns the below error! 
what should I do?
![image](https://user-images.githubusercontent.com/45136020/95894262-d2357780-0d56-11eb-9be8-31b976a14243.png)

**Comment by e-infotech** [comment]
Can anyone help me with this?!

**Comment by Karabiy** [comment]
Please, provide us with a thingsboard.log file so that we can proceed with an investigation further. The thingsboard.log is located in the /var/log/thingsboard/

**Comment by ashvayka** [comment]
@e-infotech , DO I understand you correctly that when you write "I end java.exe" task it means that you have stopped or killed this task?

**Comment by yulin-willbeok** [comment]
Hi, I have the same problem. The installation starts everything fine, and when I visit http://localhost:8080/时, I have the problem of connection refused, what can I do to fix it?
os：windows11
[Uploading thingsboard.log…]()
