### ISSUE TITLE
Response to device when use telemetry http api

### ISSUE THREAD

**Issue by Jalili-73** [thingsboard/thingsboard#3584]
**Component**

 * Generic

**Description**
I want send body response to device when device send telemetry data(json) with http to thingsboard.
for example thingsbord send back a response to device that data received in json format.
i check response in device and if response doesnt back to device i send again
what should i do

**Environment**

 * ThingsBoard: 3.1.1

**Comment by yefimov-andrey** [comment]
If you want ThingsBoard to send data to your devices which are connected via HTTP you will need to use Professional Edition which provides downlink connection (from platform to devices) via the integration feature.

**Comment by Jalili-73** [comment]
> If you want ThingsBoard to send data to your devices which are connected via HTTP you will need to use Professional Edition which provides downlink connection (from platform to devices) via the integration feature.

thanks for your reply
but i have CE version of thingsboard is there any solution like tools or any trick to handle this problem?

**Comment by Karabiy** [comment]
in case if you have a small payload, you can refer to the ThingsBoard IoT Gateway REST connector. You can refer for this link on those: https://thingsboard.io/docs/iot-gateway/config/rest/

**Comment by debacs83** [comment]
@Jalili-73 
Could you solve the problem? I am looking for exactly the same thing. If you did, could you please help?
