### ISSUE TITLE
maps' control is not work 

### ISSUE THREAD

**Issue by stormwrym** [thingsboard/thingsboard#359]
hi ,
I want to add  search box in maps .I have reading this map API  and demo .demo is normal operation out of thingsboard .However, It is not work when i add to thingsboard,
 following code:
var middleControl = document.createElement("div");
middleControl.innerHTML = "html code";
map.controls[qq.maps.ControlPosition.TOP_CENTER].push(middleControl);

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
