### ISSUE TITLE
[Question] Interaction between different widgets in dashboard

### ISSUE THREAD

**Issue by Ander-Benito-Owasys** [thingsboard/thingsboard#3590]
Hi! Is there any way I can send or share data between two widgets within the same dashboard? I cannot find any info about this in the documentation.

Im using thingsboard v3.1.1

Thanks!

**Comment by ChrisEvisi** [comment]
Hi @Ander-Benito-Owasys ,   Were you able to find a result for you query ?  Im looking for answer to the same problem. 
I saw https://github.com/thingsboard/thingsboard/issues/976    but wondering if there is another option to using userService ?
 Thanks

**Comment by AnderBenito** [comment]
Hi @ChrisEvisi. Currently, the userService trick is the only way I got it working. It is very hacky but it does the job. I hope TB implements an official way to achieve this.
Also, you can try to share data through the dashboard context object.

**Comment by ChrisEvisi** [comment]
Thanks very much for your reply @AnderBenito .   Will try that out.
