### ISSUE TITLE
Alarms Questions

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3591]
Hello !

Please tell me how can I Acknowledge or Clear all of the existing alarms for one device from rule chains or a custom widget.

Please tell me how can I get a list for all existing alarms for one device from rule chains or a custom widget.

Thank You !

**Environment**
OS: Win 7 x64
ThingsBoard: 3.1.1
Browser: Chrome

**Comment by Ultrazombie** [comment]
Closed, as not active.
