### ISSUE TITLE
Enabling rule chain alarms with MQTT doesn't work in thingsboard [Bug] 

### ISSUE THREAD

**Issue by lorithai** [thingsboard/thingsboard#3594]
Hi

Uncertain of this should be classified as a bug or not, but here goes. 

**Short description**
When I am sending telemetry to devices in thingsboard using MQTT the alarms I have set up (using this guide https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/) doesn't work. It does work to begin with when using POST requests, but it stops working as soon as I use MQTT for a device. The device seems to always be active as indicated by the server attribute "active".

**Your Server Environment**
* own setup
  * server
  * ThingsBoard Version 3.1.1pe
  * Ubuntu 20.04

**Your Client Environment**
**Desktop (please complete the following information):**
* OS: windows
* Browser: chrome
* Version: 85.0.4183.121 (Official Build) (64-bit)

**Your Device**
Laptop

* Connectivity
  * MQTT

**To Reproduce**
1. Configure rule chain (https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/)
    1a. send inactivity to alarm trigger (rule chain)
    1b. send activity to alarm clear (rule chain)
    1c. save server attributes (rule chain)
2. Configure device
    2a. create device
    2b. set inactivityTimeout server attribute to a value (60000ms in my case) for a device
3. send telemetry using mqtt
    3.a used python to send mqtt data to the device.
    3.b Don't send more data and wait until the timeout time runs out
    3c. check if the alarm has triggered
4. Error
    Telemetry of the device updated. The alarms never triggers after no sent data. The devices also never get the inactive status (server attribute "active" is true always)

**Expected behavior**
Alarm should trigger.

**Screenshots**
root rule chain
![image](https://user-images.githubusercontent.com/25453483/96277382-7bd56c80-0fd4-11eb-9333-6d608ebacb83.png)

**Additional context**
If i create a new device, set inactivityTimeout to a value and instead of sending telemetry using MQTT use POST the alarms do trigger. If I then switch over to MQTT the alarms stop triggering again.

**Comment by ashvayka** [comment]
Hi @lorithai , when you send data via python, do you close the client session or the python app remains running and MQTT session is active?

**Comment by escalanterj** [comment]
Hello, 
I have the same problem, did you find the solution?
Thanks!!
Best and happy new year!

**Comment by techtona** [comment]
Similar problem,
still didn't find the solution.

the default DEFAULT_STATE_CHECK_INTERVAL is 60 I think that is not the problem.. I used MQTT

**Comment by potato-stack** [comment]
Nobody have a solution ? Mind having the same problem too, it work just fine yesterday, suddenly the alarm stop working. I use MQTT too

**Comment by Yomilot** [comment]
As I understand there is still no fix to this problem? I am trying to trigger an alarm from a raspberry PI with MQTT and nothing seems to work...
