### ISSUE TITLE
MSA PostgreSQL + TimescaleDB 

### ISSUE THREAD

**Issue by Doyle-net** [thingsboard/thingsboard#3595]
Microservice mode, how to configure PostgreSQL + TimescaleDB, PostgreSQL + Cassandra configuration has been understood. But there is very little about TimescaleDB configuration

**Comment by MarkVortman** [comment]
@Doyle-net 
You feel free to set up and customize your database as you want. Then you can connect from ThingsBoard to your database using the **tb-node.postgres.env** file. Few examples, which you can use:
1. Use remote TimescaleDB ( for example install on separated instance Timescale DB and allow access to your ThingsBoard )
2. Change docker-compose.postgres.yml or docker-compose.yml - add official TimescaleDB docker [image](https://hub.docker.com/r/timescale/timescaledb) and configure access in **tb-node.postgres.env**
3. Install TimescaleDB on your host and configure access from docker network in **tb-node.postgres.env**

**Comment by ysit-thingsboard** [comment]
TimescaleDB is PostgreSQL DB installed with TimescaleDB extension so there is only one DB in PostgreSQL + TimescaleDB mode. You have to replace PostgreSQL docker image with TimescaleDB image. For the configuration on the env file, you can refer to one of the linux installation guide.

**Comment by WillNilges** [comment]
So then, what does the structure of such a solution look like? Should there be a Postgres container and a Timescale container? Timescale has "Hypertables." Is there a Hypertable for Timescale data and a normal table for everything else?

When I took @MarkVortman's advice, I saw that only one Timescale container was created. During a test, this one container used a lot of CPU and IO. I'm guessing because it had to handle two tables. Is this assumption correct?

**Comment by ysit-thingsboard** [comment]
> So then, what does the structure of such a solution look like? Should there be a Postgres container and a Timescale container? Timescale has "Hypertables." Is there a Hypertable for Timescale data and a normal table for everything else?
> 
> When I took @MarkVortman's advice, I saw that only one Timescale container was created. During a test, this one container used a lot of CPU and IO. I'm guessing because it had to handle two tables. Is this assumption correct?

@WillNilges Could you share your TB configuration with us? We have tuned our timescaledb and some db configuration on TB side but we never see our DB used lots of CPU (max around 60%) when we send lots of data to TB. Then we find TB starts losing data when there are still plenty of CPU resources left.

**Comment by WillNilges** [comment]
Sure, I'll post it when I get into work tomorrow. It's pretty bizarre behavior. It seems pretty nominal until you push it really hard, but under the same load, Cassandra was fine.

**Comment by ysit-thingsboard** [comment]
Thanks a lot.

I would suggest that you check if all your data are saved into database since we found TB will lose some data without producing any error for both timescale and cassandra.

**Comment by WillNilges** [comment]
My thingsboard config is pretty much vanilla. I now realize that there's quite a few config files. Is there any file in particular you're looking for?

Here's my `tb-node.postgres.env`
```
# ThingsBoard server configuration for PostgreSQL database

DATABASE_TS_TYPE=timescale
SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/thingsboard
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=postgres
```

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
