### ISSUE TITLE
[Feature Request] Replace Cassandra in Docker Compose Microservices with ScyllaDB

### ISSUE THREAD

**Issue by janknieling** [thingsboard/thingsboard#3597]
I recommend to replace Apache Cassandra in the docker compose files for the Microservices (and generally on all other setups) against its fork ScyllaDB (https://www.scylladb.com).

ScyllaDB is a rewrite of Cassandra in C++. It is much better than Cassandra (performance etc) and its 100% compatible to Apache Cassandra

**Comment by dorlaor** [comment]
Cheers! Keep me informed in case you need more info or in case there is a problem. Dor

**Comment by govorox** [comment]
Interesting! From the specs it should be like for like replacement. Has anyone actually tried it yet?

**Comment by dorlaor** [comment]
I grepped the repository, there is much more Cassandra than a docker file, I see K8S usage and even direct sstable manipulation. It can all work with Scylla but it requires more changes, especially around K8S, the scylla operator should be used. 
So there is some investment to be made with a good upside of performance, functionality and manageability.

**Comment by ashvayka** [comment]
I have tested Scylla DB few years ago and at that time it even was not able to load our schema. Don't want to start the "holy war" here. We use Cassandra in many setups and so far so good. What exactly (please provide reference to the documentation) do you mean when you talk about upside of functionality and manageability in this case?

**Comment by dorlaor** [comment]
It could be that a few years ago we didn't have the feature set. Now we are
supposed
to have it all. Here is a 'marketing' diff list, it is accurate:
https://www.scylladb.com/scylla-vs-cassandra/
You're most welcome to use Scylla if you like, I'm not here to sell or to
fight. LMK if there is an issue

**Comment by ashvayka** [comment]
We welcome PRs from community to add support of Scylla option for the install scripts. Especially if it is compatible with the java driver that we use. However, we are not yet ready to say that we officially support Scylla. What we can do is to try use it on demo.thingsboard.io for a while and check how it goes. But we have a lot of work so I can't provide any timeline now.

**Comment by janknieling** [comment]
> Interesting! From the specs it should be like for like replacement. Has anyone actually tried it yet?

I have tested it a few weeks ago.
Everything has worked fine and it has a much better performance because it is written in C++ and not in Java

**Comment by ArthurGing** [comment]
@janknieling Could you please share how you make Scylla work with Thingsboard?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
