### ISSUE TITLE
[Feature Request] Add Traefik as LoadBalancer/Proxy to Docker Compose

### ISSUE THREAD

**Issue by janknieling** [thingsboard/thingsboard#3598]
I recommend to delete HAProxy of the docker compose files (Microservices etc.) as default loadbalancer and replace it with Traefik (https://traefik.io) because it is much better (for a Microservices deployment).
Traefik has more features than HAProxy (like native LetsEncrypt/ACME support) and a better performance.

**Comment by OctavioCriollo** [comment]
> Do not actual.
> We don't plan to leave haproxy in our documentation and setups. You can use traefik, nobody forbids it.

I have modified thingsboard microservices to use traefik
