### ISSUE TITLE
[Question] How define Request Headers with self.ctx.http in TB 3.0+?

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#3600]
**Component**
* UI

**Description**
How can we use the exporte service `HttpClient` on `self.ctx.http` to make REST API calls with custom headers? I need to define custom Authorization headers (IE for executing FCM Requests / other requests). There's isn't any apparent way to define headers.

Note: I've tested both:

`self.ctx.http.get(url, {headers});`

and

`self.ctx.http.get(url, headers);`

**Environment**
 * OS:  Ubuntu 18
 * ThingsBoard: V3.1.1PE
 * Browser: Any

**Comment by ajithkumar222** [comment]
@Manusisko how to send data between two custom widgets on thingsboard v3.1

**Comment by Boolhwi** [comment]
Is there any update in this topic??

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Maybe you can find some tricks by this link:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
