### ISSUE TITLE
[Question] Is there a way to delete alarms directly from alarms table widget?

### ISSUE THREAD

**Issue by tengann** [thingsboard/thingsboard#3601]
I have a ThingsBoard v3.1.1 PE setup using AWS EC2 instance.

Here is a screenshot of my alarms table widget. As shown, all the alarms have been cleared and acknowledged but still showing on the alarms table. Is there a way to delete these alarms with the "Cleared Acknowledged" status? I want it to be deleted directly from the widget instead of from the database.
![Alarm](https://user-images.githubusercontent.com/48940092/96420434-15e12300-1228-11eb-83ad-61eef3dbffa2.png)

**Comment by Karabiy** [comment]
you can acknowledge and clear those. In case if you want the deletion for those to be handled, those refers to the custom widget option. The next guide will be useful for you: https://thingsboard.io/docs/user-guide/contribution/widgets-development/
you can refer for this link as for the alarms details: https://thingsboard.io/docs/user-guide/alarms/
