### ISSUE TITLE
Allow RPC Calls and Alarms in ENTITY_VIEW

### ISSUE THREAD

**Issue by robertoenr** [thingsboard/thingsboard#3605]
Hi, thank you and all community for this great project! Hope it will grow well, that's excellent!

My suggest is that the ENTITY_VIEWS, should be able to allow/dis-allow RPC calls, and allow/dis-allow alarms, events..

I consider this important in order to make the full functionallity of share a Device/Asset to several customers. Actually it only allows to share attributes and telemetry.

Thank you!

**Comment by Ultrazombie** [comment]
Entity view doesn't to connect to the device; entity_view masks an actual device. In which case do you need this feature? Or maybe it is irrelevant, and we can close this one.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
