### ISSUE TITLE
Timeseries - Flot Widget Legend [Bug] 

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#3616]
**Describe the bug**
The Timeseries - Flot Widget is currently bugged when trying to use the legend feature. 
This is the starting state I'm using. All the crossed out datakeys have "Hidden by default" checked in their DataKey settings.
![image](https://user-images.githubusercontent.com/26427343/96801700-8d42cc80-144b-11eb-8d0c-5a6efc919782.png)

If I try to add another datakey (100) it sorts the list using the first character value. 
![image](https://user-images.githubusercontent.com/26427343/96801887-04786080-144c-11eb-98fa-59513b2597f2.png)

The sorting issue is not the main topic of this post, but also worth mentioning. It basically a feature of Thingsboard that sorting is non-functional as everything is sorted as strings. It doesn't really even make sense to have sorting in the legend. I should be able to sort it however I want by rearranging the datakey order. I believe this was the case pre 3.0.

The real issue is that now datakeys 20 and 40 are not hidden by default. I've changed nothing other than adding another datakey. This was also not occuring pre 3.0

Does anyone know how to get around this?

**Comment by vvlladd28** [comment]
Hi @JacksonBowe 
We already fixed the problem "Hidden by default" in DataKey settings. This fixed will have added to version 3.2.0. Problem with sort legend keys we will discuss with our team. 

Thank you for your report.
