### ISSUE TITLE
[Feature Request] Add Dynamic Duration variable and Thresholds to Alert rules in Device Profiles

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3618]
Hi Guys

I am very excited for the Device Profile feature coming up in 3.2.0 
I tested it in cloud.thingsboard.io and would like to suggest couple feature requests:

1. If you can, make Duration condition also dynamic, so it can be set by Device Attribute. In most of our use cases, the threshold value and the time-in-condition (duration) are both dynamic between devices, while the rest of the stuff is the same.
![image](https://user-images.githubusercontent.com/31729091/96856024-2979cd00-1466-11eb-864c-5196dfd58836.png)

2. Can you add to device profiles something to handle Thresholds on Graphs ? So in timeseries graph for example, device profile will determine the Threshold level for the graph. So I can have a default threshold value for any device of this profile type.

Kindly

**Comment by ashvayka** [comment]
Hi @t0mmyz7 . We may add (1) but not in the first release. About (2). Please check the advanced settings of the data key in the timeseries widget. There is an ability to draw threshold based on the value of the attribute of the entity. Does this work for you? If not - please explain in more details how you see the use of (2)

**Comment by t0mmyz7** [comment]
@ashvayka about (1), great looking forward.

about (2), can you briefly tell me how it works?  I try to use it before without success.

Can I create an ASSET entity, and pull the values from there? Or must it be from the entity that is selected in the widget?

Any help would be appreciated

**Comment by t0mmyz7** [comment]
@ashvayka another request for profiles, to add actions to alarm rules

For example, after setting alarm rule, user can add some actions

1. Send RPC to device (or update device Attribute)


I would also add notification actions but I think this can be covered in Alarm management system which was posted as a seperate request.

what do you think?

**Comment by t0mmyz7** [comment]
@ashvayka hey mate, just reminding you about this request,

`If you can, make Duration condition also dynamic, so it can be set by Device Attribute. In most of our use cases, the threshold value and the time-in-condition (duration) are both dynamic between devices, while the rest of the stuff is the same.`

**Comment by t0mZ4** [comment]
this was added to device profile so i am closing.
