### ISSUE TITLE
[Bug] An alarm entry should be created for each API call to /api/alarm

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#3623]
**Bug description**
When generating 2 alarms of the same type for a device, only one is displayed and created (I checked in the DB). Once I acknowledge and clear the first one, only then I can inject a new one of the same type for that device.

I use the rest API to do so (POST on /api/alarm), I don't see any option there to modify that behavior. Also the API call returns the status code 200 (whenever the alarm is inserted or not) when the API specifies it should return 201 for created.

**Server Environment**
  * ThingsBoard lastest Version using docker thingsboard/tb-postgres
  * Linux

**Client Environment**
Not relevant

**Expected behavior**
A new alarm entry for each call to the API + correct http status.

**Comment by marshallr3** [comment]
Encountering the same problem. Is there a solution for this yet?

**Comment by marshallr3** [comment]
@bbrenne I found a workaround that has a few contraints. Firstly, Thingsboard API has built-in the idea that only a single "active" alarm is present at any given time ([reference here](https://thingsboard.io/docs/user-guide/alarms/#:~:text=ThingsBoard%20identifies)).
To get around this constraint, set your alarms to have the `status` property  as `{"status": "CLEARED_UNACK"}` or alternatively you can use `"CLEARED_ACK"` for a cleared and acknowledged alarm. The main thing is that no new alarm of the same type can show up unless the previous 'active' alarm has been cleared. Hope this helps.
