### ISSUE TITLE
How to restore TB installed on a broken VM

### ISSUE THREAD

**Issue by blackprincess88** [thingsboard/thingsboard#3628]
Hi there!

I lost my TB stuff as the Virtualbox VM where it was running is broken. I have a recent copy of the VM, is it possible for me to recovery all just importing the VM image ? Do I have to deactivate the current active instance (which is associated to the broken machine) before importing? I have a PE  Maker license.

Thank you!

**Comment by CooL16** [comment]
You have to deactivate and remove instance-license.data if exists it when you will try to run ThingsBoard on another machine.
