### ISSUE TITLE
[Question] start thingsboard service only listen on ipv6

### ISSUE THREAD

**Issue by JackYangzg** [thingsboard/thingsboard#3630]
**Component**

 * Generic
version: thingsboard-3.1.1
system: centos7

**Description**
when I start thingsboard server, only ipv6 port is binding to listen for http and mqtt.

**Comment by CooL16** [comment]
It is an issue with your system settings, please make sure you have set it up to ipv4

**Comment by ban2derlog** [comment]
You can easy bind your service to any IP address and version by setting `HTTP_BIND_ADDRESS` parameter in `thingsboard.conf` file
https://thingsboard.io/docs/user-guide/install/config/#monolithic-deployment-on-linux

**Comment by rajatksud** [comment]
same issue with PE 3.4.6 on ubuntu. I have nginx running which is listening on port 443 and binding on tcp but thingsboard only binds on tcp6. I tried setting export HTTP_BIND_ADDRESS=0.0.0.0 it binds on tcp6. Tried to give it HTTP_BIND_ADDRESS=127.0.0.1 but that also listens on tcp6 with address strangely as 127.0.0.1
http is working fine (though /api/ws needed to proxy_pass=http://[::1]:8080). 

Issue is mqtt is not working at all and not able to use gateways on PE. Same gateway is working with CE and cloud. 
I have added this to nginx.conf 

`stream {
    upstream mqtt {
		server localhost:1884;
		server 127.0.0.1:1884;
                 server [::1]:1884;
    }

    server {
        listen 1883;
        proxy_pass mqtt;
    }
}
` 
No success

**Comment by rajatksud** [comment]
I was able to solve the ipv4 issue. The embedded tomcat server is missing the setting to prefer ipv4 stack for the jvm. 
This line in the .conf file  fixes the issue
export JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"

previous posts do not address the issue.
