### ISSUE TITLE
Issue with Label and Tooltip Functions at PE 3.1.1

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#3636]
**Component**
 * UI

**Environment**
 * OS:  Ubuntu 20
 * ThingsBoard: PE 3.1.1
 * Browser: Chrome

**Description**
Hi Guys, I am trying to use Label Functions to customize my assets labels and colors at a Latest Value OpenStreetMap widget. At Dashboard Advanced Parameters tab, we have as default function the following. 

var deviceType = dsData[dsIndex]['deviceType'];
if (typeof deviceType !== undefined) {
    if (deviceType == "energy meter") {
        return '<span style="color:orange;">${entityName}, ${energy:2} kWt</span>';
    } else if (deviceType == "thermometer") {
        return '<span style="color:blue;">${entityName}, ${temperature:2} °C</span>';
    }
}

So, my doubts are:

1) Which options are possible to read as dsData[dsIndex]? I mean, hoa can I get a list of possible keys?
2) I tried to alter this function for assetType instead of deviceType, once my aliasses were created filtering my assets types, but it did not work. What I am trying to run is the following, but instead of create colors differenciation it is not returning any label for any asset. Without using label function the labels work fine (without any differenciation).

var assetType = dsData[dsIndex]['assetType'];
if (typeof assetType !== undefined) {
    if (assetType == "ABC") {
        return '<span style="color:orange;">${entityName}</span>';
    } else if (assetType == "DEF") {
        return '<span style="color:blue;">${entityName}</span>';
    }
}

Thanks for your help sharing your tips and comments.

**Comment by ChantsovaEkaterina** [comment]
Hello,
When using _dsData[dsIndex]_ you are able to get the value of any key, that you specified in the Datasources tab, in this way:
_dsData[dsIndex]['targetKeyLabel']_.
To get the asset/device type you need to add the _"type"_ key (if your entity has attributes with the same name, it is important to select the correct key type - _entity field_). Then you will be able to use it in the label function by specifying _dsData[dsIndex]['Type']_ if you have not changed the default key label.

**Comment by FreddyHunter** [comment]
Thanks Ekaterina, your explanation was perfect and now it is working properly!!
