### ISSUE TITLE
[Question] Issue about switch widget

### ISSUE THREAD

**Issue by TanCans** [thingsboard/thingsboard#3642]
I have an issue about subscribing MQTT client, to enable to control the LED ring of my circuit with control widget.

I have connected with the server and gave the access tokens as well as ids, defined my client. But when i try to switch the control widget, it does not do anything. I am sharing a the piece of code which im trying.

server = 'demo.thingsboard.io'
port = 1883
pw= ...
pw_red= ...
id = ...
topic_subscribe='v1/devices/me/rpc/request/+'
topic_publish='v1/devices/me/telemetry'

client = MQTTClient(id, server, port,pw,pw)

client_red = MQTTClient(id, server, port,pw_red,pw_red)
time.sleep(2)
client_red.connect()
gc.collect()

def sub_cb_red(topic_red, msg_red):
    print((topic_red, msg_red))
    global r
    if msg_red == b'{"method":"setValue","params":true}':
        chain.show(allred)
        r=True
    if msg_red == b'{"method":"setValue","params":false}':
        chain.show(black)
        r=False

def subscribe_thread(self,n):
  self.subscribe(topic_subscribe,n)

client_green.set_callback(sub_cb_red)

_thread.start_new_thread(subscribe_thread,(client_red,0))

**Comment by Ultrazombie** [comment]
Closed, as not active.
