### ISSUE TITLE
[Question] Link public dashboard with "Entity taken from dashboard state" alias to a specific device

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#3644]
I have a generic dashboard that uses a "Entity taken from dashboard state" alias to show information from different devices.

I have made the dashboard and the devices public, but cannot link the dahsboard public URL to a specific device.

How could I get a generic public dashboard able to show information from different devices? perhaps adding some parameter to the dashboard public url?

Kind regards

**Comment by IoTopenTech** [comment]
I have found a solution.
Just copy the public dashboard url and add a state paremeter with the state encoded in base64

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
