### ISSUE TITLE
[Feature Request] Hide version number in browser console logs

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3649]
Hello

Is it possible to hide the version number appearing in the devtools console?

![image](https://user-images.githubusercontent.com/39315/97442257-f170ff00-1929-11eb-9729-9dc3563472d3.png)

Having this value displayed is problematic from a security point of view because it exposes valuable information that can be used by an attacker. (and therefore it negatively affects audit reports performed by penetration testers)

Thanks

**Comment by ashvayka** [comment]
Will do. @vvlladd28 please add this to the next release..

**Comment by trypzz** [comment]
This is already fixed and is not reproduced in 3.2.2
