### ISSUE TITLE
Timezone support for Dashboards/Timewindow

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#365]
Hi all,
First many thanks for this amazing platform! It is a real pleasure to work with it and see the tremendous support provided by the TB team!

Scenario:
- We have customers(customer users) controlling complex devices (all of the same type) by use of fullscreen dashboards
- Each customer dashboard (or better a dashboard state, which is opened after the customer has selected a specific device) is representing a single device of the customer
- The devices are spreaded all over the world and acting in different timezones.
- For the use case it is important that customers can see and handle timeseries data according to the local timezone of the devices

All the timeseries data ist logged into database with UTC. TB then uses the locally set timezone of the frontend (e.g. PC) to select and display timeseries data. That is perfectly fine as long as the device and the frontend are located in the same timezone. It gets complicated for the customer/user, when time needs to be selected according to the local timezone the device is located in.
One way around this is to select the frontend timezone according to the device location. Then everything is working as expected within the dashboard. But for obvious reasons that solution is not acceptable in real world.

So the question is:
How can I achieve to let the customer select and display timeseries data (and others) according to the local timezone of the current device, not according to the timezone the frontend is configured for?
 I was not successful to use onUpdateTimewindow() because the timewindow mixes it up with the frontend timezone again.
The timezone selection can probably be solved by having own widgets for timeframe selection and handling the subscription timeframe range via the REST API. But this sounds complicated and would re-implement a lot of stuff TB is already providing natively.

Is there may be another way? Did I miss or misunderstood something here?

If not, how about this:
- The dashboard timewindow gets a timezone setting option which is independent from the frontend timezone. Default remains frontend timezone. The user can select the timezone for the current dashboard with it.
- All time information within the dashboard is then displayed according to the selected timezone (as now for the frontend timezone).
- The timezone setting of the dasboard can somehow be set/modified programmatically. Best way is not fully clear for me. A dedicated stateParameter for the dashboard state which is automatically read by the dashboard timewindow when dashboards opens? This would allow to set the timezone automatically according to the location of the device.

Thanks!

**Comment by makefitter** [comment]
Hello,

@ashvayka & @BatListener is there any update on this issue. We have the same problem. Thanks.

**Comment by BatListener** [comment]
Sorry, no solution I can offer.
I am still hoping that timezone support will be introduced in future versions of TB.

**Comment by glancia** [comment]
Hi, I have the same need.

**Comment by wenzul** [comment]
Hi, I have the same need.

**Comment by BernhardHaider** [comment]
Hi, I have the same need.
additonally i cannot see data on the dashboard from timezone higher then mine
e.g. data from australia (+8) cannot be seen for about 7hours (my timezone +1)

**Comment by nmahale10** [comment]
Hi any update on this.Facing same issue

**Comment by amber-aw** [comment]
Well, this still seems to be an issue. To keep things simple, I imagine most people have their field devices reporting using UTC. Putting the telemetry aspect aside, the issue of viewing timeseries data still remains. If there were an additional customisable parameter associated with a dashboard that allows options such as: 'use viewer's local time from browser', 'use this timezone, e.g. GMT+05'. Thingsboard would handle everything in UTC, but when sending or receiving timestamp information it would 'translate' it using the dashboard's setting. That way anyone can view (and also export) timeseries data using their own local time, or any other timezone.

**Comment by amber-aw** [comment]
One more thing I forgot to mention. At the moment, as an ugly work-around, it is possible to view the data in the correct timezone by adjusting the system's time on the computer or device that is being used to view the timeseries data (e.g. temporarily set a new timezone or set an environment variable). This at least allows data to be exported with the correct timestamps. There may be browser plugins or add-ons that allow for a selectable timezone, which would be more convenient, although I have not tested this.

**Comment by fargiolas** [comment]
any news about this? if I send UTC timestamps and open the dashboard in my timezone (CET, GMT+1) I  get all the data in timeseries widgets one hour behind without apparently any option to localize the timestamps. Am I missing anything? looks a pretty major issue to me, it seems odd that it didn't get any feedback from the devs. Maybe is there a workaround I'm not seeing?

**Comment by ashaforost** [comment]
Since ThingsBoard v3.2.2 there's an option to change the dashboard timezone, which can be accessed through the dashboard time window. This way, knowing the timezone of your device, you can display the widgets data with the local time of the device.
