### ISSUE TITLE
[Question] REST registered users - how to Activate without email

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#3651]
Hi All,
I`m able to register users via REST API but they are not active unless they click a link in the email that contains the activation token.
Is there a way to completely remove the activation step so users are active right after registration ?
And if not - is there  away to get the email token  via API and activate them ?

**Comment by amizer12** [comment]
I`ve solved this by writing an AWS Lambda function that makes 5 api calls:
- one is loging in via dedicated tenant account and obtaining token
( this is a potentiall security risk as you need to hardcode the credentials into the function - make sure you secure your API
 as much as possible and code as well.)
- creating a new user
- getting a activation link for newly created user ( get the new user id from previous API call response )
- parsing the url to only have the toke instead the entire URL and using this token via api call to activate the user
- loggin out from tenant account

If you then connect this lambda function to API Gateway you can actually create an api that is doing a user registration and integrate it anywhere you like in any front end application of your choice.

**Comment by m-owais** [comment]
I tried using the "/api/user/{userId}/activationLink" to get a link to the the URL and parse the token from it as in the java client

https://github.com/thingsboard/thingsboard/blob/2bd28cb021bc794db5c297cae5063362bee61427/rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java#L669

But i get an error message 
status": 405,
"error": "Method Not Allowed",

Is there any extra setup required. I am using demo server

**Comment by amizer12** [comment]
@m-owais did you first authenticate yourself in swagger using a tenant or tenant admin account JWT token ?

**Comment by m-owais** [comment]
I was able to figure it out. It seems a customer object cannot be activated. User objects need to be created and activated instead.

Also there was some wrong code generated by swagger code gen for additionalInfo properties for all objects which i had to fix manually.

**Comment by etairossamarth** [comment]
Hi @amizer12 
Can you please share the REST API call to create a user. (I am having some difficulty to create a user via API)

**Comment by amizer12** [comment]
Hi,
You would need to write your own as TB does not currently support directly a single API call to create and activate user. 
I did it as mentioned above through a lambda function that is doing couple API calls to TB in specific order and that is also holding a dedicated tenant user and password that is used by lambda function to process all those calls.
This lambda also accepts the email and other details in JSON that are used to create user.
Then i externalize it via API Gateway so i can call it from mobile app or website.

**Comment by etairossamarth** [comment]
Hi @amizer12 , Thanks for the comment

But as you mention in your query "I`m able to register users via REST API but they are not active unless they click a link in the email that contains the activation token."

I am unable to create users via REST API, it's always failing with 400 without any error message. If possible, can you please share the REST call to create a user?

**Comment by amizer12** [comment]
HI, So i`m launching in order:
Login with hard coded tenant credentials within the lambda function code( TODO - find better way to do it )
And getting the token i`m oging to use in next calls, and then i create customer:


Then adding user:
```
function createcustomer() {
    return new Promise((resolve) => {
            axios(
              {
                method: 'post',
                url: tburl+'/api/customer',
                headers: { 
                  'Content-Type': 'application/json', 
                  'Accept': 'application/json',
                  'X-Authorization': 'Bearer '+ [token]
                },
                data: 
                
                JSON.stringify({
                  "title": email,
                  "additionalInfo":
                    {"description":"desc"},
                  "country":"Poland",
                  "city":"Poznan",
                  "state":"State",
                  "zip":"420",
                  "address":"",
                  "address2":"",
                  "phone":"phone",
                  "email":email})
              }
              )
            .then(function (response) {
              resolve(response.status);
              customerid=response.data.id.id
            })
            .catch(function (error) {
              resolve(error.response.data.message);
            })
        });
}
```
Then adding user for for the same customer with the same details ( for my setup every customer have a single user it night be didfferent for you )
```
function createuser() {
    return new Promise((resolve) => {

            axios(
              {
                method: 'post',
                url: tburl+'/api/user?sendActivationMail=false',
                headers: { 
                  'Content-Type': 'application/json', 
                  'Accept': 'application/json',
                  'X-Authorization': 'Bearer '+ [token]
                },
                data: JSON.stringify({"email":email,"firstName":firstName,"lastName":lastName,"additionalInfo":{"description":"","defaultDashboardId":null,"defaultDashboardFullscreen":false},"authority":"CUSTOMER_USER","tenantId":{"entityType":"TENANT","id":tenantid},"customerId":{"entityType":"CUSTOMER","id":customerid}})
              }
              )
            .then(function (response) {
              userid=response.data.id.id;
              resolve(response.status);
            })
            .catch(function (error) {
              resolve(error.response.data.message);
            })
        });
}
```

Then i`m getting and activztion token for this user:

```
function getactivationtoken() {
    return new Promise((resolve) => {
            axios(
              {
                method: 'get',
                url: tburl+'/api/user/'+userid+'/activationLink',
                headers: { 
                  'X-Authorization': 'Bearer '+ [token]
                },
                data: null
              }
              )
            .then(function (response) {
              //parse url to ge only token
              token_string = response.data;
              var url = new URL(token_string);
              var acttoken = url.searchParams.get("activateToken");
              activatetoken=acttoken
              resolve(response.status);
            })
            .catch(function (error) {
              resolve(error.response.data.message);
            })
        });
}
```

And then im activating the user with the password he is providing as parameter to my lambda function ( i launch this function via api gateway that accepts the json with 2 parameters - email and password )

```
function getactivationtoken() {
    return new Promise((resolve) => {
            axios(
              {
                method: 'get',
                url: tburl+'/api/user/'+userid+'/activationLink',
                headers: { 
                  'X-Authorization': 'Bearer '+ [token]
                },
                data: null
              }
              )
            .then(function (response) {
              //parse url to ge only token
              token_string = response.data;
              var url = new URL(token_string);
              var acttoken = url.searchParams.get("activateToken");
              activatetoken=acttoken
              resolve(response.status);
            })
            .catch(function (error) {
              resolve(error.response.data.message);
            })
        });
}
function activatesetpassword() {
    return new Promise((resolve) => {
            axios(
              {
                method: 'post',
                url: tburl+'/api/noauth/activate?sendActivationMail=false',
                headers: { 
                  'Content-Type': 'application/json', 
                  'X-Authorization': 'Bearer '+ [token]
                },
                data: JSON.stringify({"activateToken":activatetoken,"password":userpassword})
              }
              )
            .then(function (response) {
              resolve(response.status);
            })
            .catch(function (error) {
              resolve(error.response.data.message);
            })
        });
}
```

Hope that helps !

**Comment by etairossamarth** [comment]
Hi @amizer12 

I appreciate your help so much. I am able to understand the whole procedure now.
Again Thanks a lot for your help.
