### ISSUE TITLE
Support of Template-Dashboards

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#366]
Hi all,

Scenario:
- There are thenth or hundreds of customers with many users controlling quite complex devices (all of the same type) by use of fullscreen dashboards.
- As the functionalities to be provided by the dashboards are always the same for all devices, the dashboards for all customers look exactly identical. The devices are shown according to the access rights/device assignments of the respective customer.

Problem:
- Currently, there is a possibility to assign several dashboards to one customer.
- But:  There is no possibility to let several customers reference the same dashboard, i.e. each customer needs its own, dedicated dashboard(s)
- If changes / extensions are necessary to the dashboard(s), the dedicated dashboards of all customers need to be modified individually. This is hard to maintain, if there is a large number of customers to be handled.

There is, of course, a work-around to it. I generated an external script, which is using the REST API in order to fiddle around with the dashboard configurations. So in fact, I define a kind of new dashboard template, read its configuration via the REST API and run through the dashboards of all customers to modify their configuration using the new template configuration. This is working, but it is far from elegant, fast or memory efficient .

So my question:
Would it be possible and would it make sense to allow a dashboard to be assingned to several customers?
Changes to such a "template-dashboard" would directly be reflected for all customers / users referencing to it which would easify the maintenance of the dashboards a lot.

I know, that might have quite an influence on the internal relation handling and even the administrative UI. Nevertheless, I think, such an extension could increase the flexibility and usability of the architecture.
And sorry, if this were brought up somewhere else, already!

Thanks!

**Comment by ashvayka** [comment]
This is now in master branch and will be part of TB v1.4 release!
