### ISSUE TITLE
[Question] Is there a plan to upgrade the supported JDK to something recent?

### ISSUE THREAD

**Issue by dmd17** [thingsboard/thingsboard#3661]
**Component**
 * Generic

**Description**
JDK 8 is no longer supported. Recent JDK versions have better GC as well. Is there a plan to upgrade the supported JDK to something recent?

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.0
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
Closed, as not active.
