### ISSUE TITLE
[Question] Is there a way to enable FIFO to limit database table storage capacity?

### ISSUE THREAD

**Issue by tengann** [thingsboard/thingsboard#3663]
**Component**

 * Generic

**Description**
I have a Professional Edition setup using AWS EC2 instance, with postgreSQL-12 as the database.

Is there any way to enable First-In, First-Out (FIFO) on the database tables to limit storage capacity? (For example, limit the storage capacity for each table to 1GB.)

**Environment**

 * ThingsBoard: v3.1.1 PE

**Comment by Ultrazombie** [comment]
Closed, as not active.
