### ISSUE TITLE
Create several telemetry (timestamp) in data converter from 1 telemetry

### ISSUE THREAD

**Issue by Arteria2** [thingsboard/thingsboard#3665]
I receive 1 telemetry in my data converter which contains several data (see below)
Data 1 : Timestamp
Data 2 : Volume
Data 3 : Log Timestamp 
Data 4 : Log Volume
Data 5 : Volume at log Timestamp + 1 hour
Data 6 : Volume at log Timestamp + 2 hour
...

I would like to divide this message in several messages (a telemetry for each hour). How can I do this in my data converter ?
Thanks for your help.

**Comment by Karabiy** [comment]
You can refer for an example for those on below. So that, the next structure should be used for the telemetry:

        "telemetry":[
            {
                "ts":1527863043000,
                "values":{
                    "battery":3.99,
                    "temperature":27.05
                }
            },
            {
                "ts":1527863044000,
                "values":{
                    "battery":3.98,
                    "temperature":27.06
                }
            }
        ]

So that the data converter for this structure setup will be approximately the next:  
```

// Decode an uplink message from a buffer
// payload - array of bytes
// metadata - key/value object

/** Decoder **/

// decode payload to string
var payloadStr = decodeToString(payload);

// decode payload to JSON
// var data = decodeToJson(payload);

var deviceName = 'Device A';
var deviceType = 'thermostat';
var customerName = 'customer';
var groupName = 'thermostat devices';
// use assetName and assetType instead of deviceName and deviceType
// to automatically create assets instead of devices.
// var assetName = 'Asset A';
// var assetType = 'building';

// Result object with device/asset attributes/telemetry data
var result = {
// Use deviceName and deviceType or assetName and assetType, but not both.
   deviceName: deviceName,
   deviceType: deviceType,
// assetName: assetName,
// assetType: assetType,
   customerName: customerName,
   groupName: groupName,
   attributes: {
       model: 'Model A',
       serialNumber: 'SN111',
       integrationName: metadata['integrationName']
   },
   telemetry: [{
       ts: "ts1",
       value: {
       temperature: 15,
       humidity: 10,
       rawData: payloadStr
   }},{
          ts: "ts2",
       value: {
       temperature: 42,
       humidity: 80,
       rawData: payloadStr
}}
   ]
};

/** Helper functions **/

function decodeToString(payload) {
   return String.fromCharCode.apply(String, payload);
}

function decodeToJson(payload) {
   // covert payload to string.
   var str = decodeToString(payload);

   // parse string to JSON
   var data = JSON.parse(str);
   return data;
}

return result;

**Comment by Arteria2** [comment]
Thanks for your message. 
In my case, the telemetry is like this : 
  "telemetry":
        {
            "ts":1527863043000,
            "values":{
                "battery1":3.99,
                "temperature1":27.05,
                 "battery2":3.99,
                "temperature2":27.05,
            }
        }

My device read one telemetry per hour and send one telemetry every six hours. But I only have 1 message with one timestamp and 6 values. With this timestamp, I deduct the others.

I I would like to create a table at the end of my data converter with one timestamp and one measure. But, at the beginning I have only ont timestamp and 6 measure (one message).
