### ISSUE TITLE
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.

### ISSUE THREAD

**Issue by rmwwiii** [thingsboard/thingsboard#3667]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

xx@xx:~$ sudo /usr/share/things*/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v3.1.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:634)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:66)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:194)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

---

<h2>i installed  thingsboard windows version but the result was same as the ubuntu . </h2><br/>
<h4>The fact is that i am fresh man .Please help me  elaborate description and operation guide . Thanks! ! ! I am sorry and shamed for my action! T^T</h4>

---

**Environment**

 * OS: win10  WSL Ubuntu 20.04.1 LTS<br/>
 * ThingsBoard: thingsboard.v.3.1.1<br/>
 * Browser: Google Chorme 86.0.4240.111 x64

**Comment by Delapouite** [comment]
Hello. What is your Postgresql version? Looks like you're using `10` and need `11`.

**Comment by rmwwiii** [comment]
> Hello. What is your Postgresql version? Looks like you're using `10` and need `11`.

windows platform postgresql 13；
ubuntu platform PostgreSQL 12.

**Comment by diptiprakashpalai** [comment]
Hi @rmwwiii  I am sorry to disturbing  you, I am facing also the same above mentioned problem while installing Thingsboard. Could you please tell how did you fix it? Thanks in advance.

**Comment by rmwwiii** [comment]
@diptiprakashpalai 
 https://jdbc.postgresql.org/
 <h4>find jdbc adapted,the problem maybe resovled.</h4>

**Comment by Centurio-Macro** [comment]
> 
> 
> @diptiprakashpalai
> https://jdbc.postgresql.org/
> #### find jdbc adapted,the problem maybe resovled.

I have the same problem and so far found no solution. How did you solve it?
Can you explain what you mean with "find jdbc adapted,the problem maybe resovled"?

**Comment by Centurio-Macro** [comment]
> 
> 
> Hello. What is your Postgresql version? Looks like you're using `10` and need `11`.

How do you know that he needs version 11? Also, how do authentification type and version relate to each other?

**Comment by Centurio-Macro** [comment]
> 
> 
> Hello. What is your Postgresql version? Looks like you're using `10` and need `11`.

How do you know he needs version 11? Also, how do authentification type and version relate to each other?

**Comment by rmwwiii** [comment]
> > @diptiprakashpalai
> > https://jdbc.postgresql.org/
> > #### find jdbc adapted,the problem maybe resovled.
> 
> I have the same problem and so far found no solution. How did you solve it?
> Can you explain what you mean with "find jdbc adapted,the problem maybe resovled"?

org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and **that it is using an authentication scheme supported by the driver**.

- https://jdbc.postgresql.org/download.html ->**Other Versions** 
- find jdbc driver adapt for your jdk version

**Comment by Centurio-Macro** [comment]
> org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and **that it is using an authentication scheme supported by the driver**.
> 
>     * https://jdbc.postgresql.org/download.html ->**Other Versions**
> 
>     * find jdbc driver adapt for your jdk version

I´m trying to install:
Thingsboard 3.1.1

I´ve succesfully installed:
Java JDK 8
PostgreSQL 13.1 for Windows 10.
According to your link I should use JDBC 4.2. I installed the newest version, `42.2.18 JDBC 42`.
I have also successfully started pgAdmin and created the Database thingsboard.

Thats what pg_hba.conf and postgresql.conf look like:
[pg_hab.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3RsIklx7kyzzCk9?e=j8cPgY)
[postgresql.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3aUMehgBLPg-kaZ?e=CWWbpU)
[thingsboard.yml](https://1drv.ms/u/s!Au1bXNOlBiy8y3ftSnHG7x3zu12t?e=PISwiw)

From what I´ve learned from other online discussions these look correct.

I took a look into the thingsboard log file. There this error is logged, right before the usual `org.postgresql.util.PSQLException` notification. Any idea what this could mean?

```
2020-11-30 12:19:34,535 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2020-11-30 12:19:35,621 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.postgresql.util.PSQLException: Der Authentifizierungstyp 10 wird nicht unterstützt. Stellen Sie sicher, dass die Datei 'pg_hba.conf' die IP-Adresse oder das Subnetz des Clients enthält und dass der Client ein Authentifizierungsschema nutzt, das vom Treiber unterstützt wird.
```

After installing, where should I save the `postgresql-42.2.18.jar` driver file?

**Comment by rmwwiii** [comment]
> > org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and **that it is using an authentication scheme supported by the driver**.
> > ```
> > * https://jdbc.postgresql.org/download.html ->**Other Versions**
> > 
> > * find jdbc driver adapt for your jdk version
> > ```
> 
> I´m trying to install:
> Thingsboard 3.1.1
> 
> I´ve succesfully installed:
> Java JDK 8
> PostgreSQL 13.1 for Windows 10.
> According to your link I should use JDBC 4.2. I installed the newest version, `42.2.18 JDBC 42`.
> I have also successfully started pgAdmin and created the Database thingsboard.
> 
> Thats what pg_hba.conf and postgresql.conf look like:
> [pg_hab.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3RsIklx7kyzzCk9?e=j8cPgY)
> [postgresql.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3aUMehgBLPg-kaZ?e=CWWbpU)
> [thingsboard.yml](https://1drv.ms/u/s!Au1bXNOlBiy8y3ftSnHG7x3zu12t?e=PISwiw)
> 
> From what I´ve learned from other online discussions these look correct.
> 
> I took a look into the thingsboard log file. There this error is logged, right before the usual `org.postgresql.util.PSQLException` notification. Any idea what this could mean?
> 
> ```
> 2020-11-30 12:19:34,535 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
> 2020-11-30 12:19:35,621 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
> org.postgresql.util.PSQLException: Der Authentifizierungstyp 10 wird nicht unterstützt. Stellen Sie sicher, dass die Datei 'pg_hba.conf' die IP-Adresse oder das Subnetz des Clients enthält und dass der Client ein Authentifizierungsschema nutzt, das vom Treiber unterstützt wird.
> ```
> 
> After installing, where should I save the `postgresql-42.2.18.jar` driver file?

---
- That is a big key. 
- Put **‘postgresql-42.2.18.jar’**to jdk directory,
                        **e.g.     postgresql-42.2.18.jar ---> ......./jre/lib/ext/postgresql-42.2.18.jar**
- END, good luck!

**Comment by Centurio-Macro** [comment]
> > After installing, where should I save the `postgresql-42.2.18.jar` driver file?
> 
>     * That is a big key.
> 
>     * Put **‘postgresql-42.2.18.jar’**to jdk directory,
>       **e.g.     postgresql-42.2.18.jar ---> ......./jre/lib/ext/postgresql-42.2.18.jar**
> 
>     * END, good luck!

Kudos to you sir, it worked.
I put the file into thingsboard folder and PostgreSQL folder, but I never thought about the JDK one, thx a lot.

```
C:\Program Files (x86)\thingsboard>install.bat --loadDemo
Detecting Java version installed.
CurrentVersion 18
Java 1.8 found!
Installing thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v3.1.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Loading demo data...
Installation finished successfully!
2020-12-01 08:49:47,801 INFO  - Starting ServiceWrapper in the CLI mode
2020-12-01 08:49:48,202 INFO  - Completed. Exit code is 0
ThingsBoard installed successfully!

C:\Program Files (x86)\thingsboard>
```

**Comment by rmwwiii** [comment]
@Centurio-Macro  It is my pleasure ,guy. Wish you a happy life.ヽ(ﾟ∀ﾟ)ﾒ(ﾟ∀ﾟ)ﾉ
