### ISSUE TITLE
"ResourceManager : unable to find resource 'error.vm' in any resource loader."

### ISSUE THREAD

**Issue by skedin** [thingsboard/thingsboard#367]
I run my Thingsboard 1.3.1 instance in 2 ways:
1. Run ThingsboardServerApplication in IDE
2. java -jar thingsboard-1.3.1-boot.jar

Launching the application is fine, but when I visit http://localhost:8080, I get "ResourceManager : unable to find resource 'error.vm' in any resource loader.".
I don't see this issue in Thingsboard 1.2.3 & 1.3.0. Anything I missed?

I also try to add a Velocity error page as error.vm, but don't know what exception or error instances to display!

**Comment by ssmaurya** [comment]
Did you update database post 1.3.1 installation? You can run upgrade script to upgrade from 1.3.0

**Comment by ssmaurya** [comment]
Also you can run hotdeploy to get exact source of error.

**Comment by skedin** [comment]
I use new 1.3.1 database schema.

How to run hot deploy? Thanks.

**Comment by skedin** [comment]
I have solved the problem, the webpack build part did not complete successfully, now it is ok.

**Comment by rof20004** [comment]
Ok, you can close the issue now @skedin

**Comment by pushkar31** [comment]
Hi,
I am facing the same problem. what you did to solved the problem.
 the webpack build part did not complete successfully, now it is ok.

How to check this webpack build part?
