### ISSUE TITLE
[Bug] ThingsBoard PE instance deployed in aws is not working

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#3670]
Thingsboard AMI deployed in aws is down from today 9AM.Please share steps to resolve.

![image](https://user-images.githubusercontent.com/37862040/97978375-7e68fc00-1df3-11eb-83b3-a25426efdc07.png)

**Comment by Karabiy** [comment]
Please, provide us with a thingsboard.log file so that we can proceed with an investigation further. The thingsboard.log is located in the /var/log/thingsboard/ 
Additionally, provide us with the thingsboard.conf and the thingsboard.yml files. Those are located at /etc/thingsboard/conf/

**Comment by SuneethaYamani** [comment]
PFA logs while server was working fine ..after server is down both logs are attached
[thingsboard.2020-10-30.0.log](https://github.com/thingsboard/thingsboard/files/5493923/thingsboard.2020-10-30.0.log)
[thingsboard.2020-11-02.0.log](https://github.com/thingsboard/thingsboard/files/5493924/thingsboard.2020-11-02.0.log)

**Comment by SuneethaYamani** [comment]
PFA of logs,thingsboard.yml,config
[thingsboard logs.zip](https://github.com/thingsboard/thingsboard/files/5493977/thingsboard.logs.zip)

**Comment by SuneethaYamani** [comment]
In case if we are not able to recover.. how to download custom widget,rule engine,dashboard json from inside ubuntu machine.

**Comment by ashutoshbehura** [comment]
I am facing also the same after updating using sudo apt-get update in ec2. I am using ThinhsBoard PE on aws ec2. Can someone help how to get my dashboard(JSON files)?
I have tried to recover all the files from #/usr/share/thingsboard/data/json but could not get my dashboard data. 

![issue](https://user-images.githubusercontent.com/24368774/98239821-8f9a4000-1f8e-11eb-90bb-d9730e3df261.JPG)

**Comment by Ultrazombie** [comment]
Dashboard, etc., do not save in /usr/share/thingsboard/data/json folder. Thingsboard use PostgreSQL for these. Please re-open the new ticket if you have any questions about this topic.
