### ISSUE TITLE
[Bug] Dashboard state broken after setting faulty cell style function.

### ISSUE THREAD

**Issue by ChristofferHolmesland** [thingsboard/thingsboard#3671]
**Describe the bug**
Setting the cell style processing function on a datasource timeseries to an invalid value, e.g. `return value + "123";` breaks the dashboard.

**Your Server Environment**
Ubuntu, Thingsboard PE v3.1.1

**Your Client Environment**
Desktop, Windows 10, Chrome version 86

**To Reproduce**
1. Create new dashboard
2. Add entity table widget
3. Add data source to widget, select one of the fields and edit it.
4. Select "Use cell style function"
5. Content of function "return value +"123";".
6. Save changes.
7. Try to edit the datasource field, page freezes.
8. Try to edit the dashboard states, page freezes.

In addition, other widgets on the same dashboard state cannot be edited anymore. This means that if you only have one dashboard state the whole dashboard needs to be recreated. If you have multiple states the faulty one can be deleted and then recreated.

**Expected behavior**
Expected behavior is that only the widget is broken, but it would be nice to still be able to edit it to fix the problem as recreating a dashboard state or the widget might be time consuming.

**Comment by SuminDenis** [comment]
Hello @[ChristofferHolmesland](https://github.com/ChristofferHolmesland),

I’m glad to inform you that this issue has been solved in the current version of ThingsBoard!
