### ISSUE TITLE
[Bug] Improve explanation of what's accepted in entity alias "Entity Name"

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#3682]
Hello

At first, I was about to open a new ticket asking that the current dashboard entity alias type called "Entity Name" is too limiting, because it only accepts a string describing what the prefix of a device name should be, and sometimes you may want to have more flexibility, for example "Name contains" or "Name ends with". This confusion is because the input field is label "Name starts with" which is misleading.

But it turns out that this field is capable to accept wildcards, using the `%` char, as briefly found in this issue after some digging : https://github.com/thingsboard/thingsboard/issues/1563
Therefore, to grab all devices with name containing `TE`, one could use `%TE%`:

![image](https://user-images.githubusercontent.com/39315/98342608-f2342000-2010-11eb-9c83-a2264964d1fd.png)

The problem is that the possibility to use `%` is not self explanatory. So an easy fix would be to improve the label of the field and detailing its "regex-like" possibilities.

Thanks

**Comment by ashvayka** [comment]
PR 4803 Merged and will be part of 3.3 release
