### ISSUE TITLE
Can a dashboard be shared between two customers?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#3683]
If I have two customers, Customer A and Customer B, can I share a dashboard I made on my tenant administrator account with both of them?

**Comment by itrich** [comment]
With Thingsboard PE 3.2, you can share Dashboard Groups to all subsequent customers. You can control whether the receiving customer can read or even write to the Dashboard Group.

![2020-12-11 07_26_26-mhascaro Portal _ Dashboardgruppen](https://user-images.githubusercontent.com/29982899/101870604-42f3e700-3b82-11eb-9477-7ab3902593b6.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
