### ISSUE TITLE
[Question] User access (read/write) to an asset server attribute

### ISSUE THREAD

**Issue by syvic** [thingsboard/thingsboard#3686]
**Component**
 * Generic

**Description**
 I'm trying to get a User to be able to act on an "Update server double attribute" widget but I get an this error: "You haven't access rights to this location!". If I use the widget with the tenant it works correctly. Is it possible for a user to have write permissions to the server attribute of an asset without making it public? Thanks

**Environment**
 * ThingsBoard: 3.1.1 CE

**Comment by Ultrazombie** [comment]
You can achieve this in the PE version with the RBAC feature.
