### ISSUE TITLE
[Question] How to configure different email server settings for different white lable profiles?  

### ISSUE THREAD

**Issue by henkbredell** [thingsboard/thingsboard#3687]
Hi 
We are running TB PE 2.4.3
We have a white labeled profile that inherits email server settings at the moment

Can we set different email server settings for different white labeled profiles?
When logged in as administrator on the white labeled profile, I cannot see the "Use System Mail Server Settings" tick box to untick.

Regards
Henk

**Comment by PovitruliaV** [comment]
Hi @henkbredell,
Is this issue still relevant?
