### ISSUE TITLE
a dependency error when install on ubuntu16

### ISSUE THREAD

**Issue by cc19931002** [thingsboard/thingsboard#369]
as showed below,could anyone help me,tks

![4](https://user-images.githubusercontent.com/26158117/31881512-516e19ce-b816-11e7-97cf-64c760d43431.png)

**Comment by ssmaurya** [comment]
Looks like some issue with java installation. You can try openjdk installation using apt-get repo and see if it works. 
You can refer https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
