### ISSUE TITLE
[ERROR] Failed to execute goal org.thingsboard:gradle-maven-plugin:1.0.10:invoke (default) on project application: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.

### ISSUE THREAD

**Issue by shahjee005** [thingsboard/thingsboard#3696]
Hi everyone,
I am trying to  build thingsboard release-3.1 from source on Ubuntu Server 18.04 LTS (HVM) ,AWS Ec2 (t3a.2xlarge-32GiB) and got the above mentioned error.
I have tried many suggested solution in several posts on this forum related to build issue but nothing worked for me so far.
Anyone else have faced the similar problem ? any suggested solution? 
Would really appreciate the help. Thanks !

I am getting the following error;

`Task :renameRpm FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':renameRpm'.
> Could not copy file '/root/thingsboard/application/target/thingsboard-3.1.1-1.noarch.rpm' to '/root/thingsboard/application/target/thingsboard.rpm'.
   > java.io.IOException: No space left on device

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
4 actionable tasks: 4 executed
[INFO] Deleting unused version-specific caches in /root/thingsboard/packaging/java/.gradle
[INFO] Build
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.1.1:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  4.226 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  6.583 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.081 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  7.130 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.231 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.182 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  0.664 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  2.028 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 15.155 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.022 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  2.759 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.847 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.397 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.694 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  1.056 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.033 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.959 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 10.439 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  6.005 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.011 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 35.035 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 16.481 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 16.690 s]
[INFO] ThingsBoard Server UI .............................. SUCCESS [06:07 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  1.385 s]
[INFO] Thingsboard Rest Client ............................ SUCCESS [  0.458 s]
[INFO] ThingsBoard Server Application ..................... FAILURE [ 48.237 s]
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:11 min
[INFO] Finished at: 2020-11-11T00:50:47Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.thingsboard:gradle-maven-plugin:1.0.10:invoke (default) on project application: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :application`

**Comment by smatvienko-tb** [comment]
Hi @shahjee005, @ashvayka!
It seem you are running build under the **root**.  Try to avoid building and running under the root. It is good idea to use a regular user instead.

I had a similar issue today on the WSL (Linux on Windows 10) Ubuntu 18 under the regular user.
It was general issue with the environment when Gradle failed to start
The fix was to remove `~/.gradle` folder. 
To remove the folder I have to uninstall gradle before with the command
`sudo apt remove gradle`
May be it's not a perfect solution, but it works fine for me.
`[INFO] Reactor Summary for Thingsboard 3.3.0-SNAPSHOT:`
![image](https://user-images.githubusercontent.com/79898499/123525170-7f7ad080-d6d7-11eb-8daf-a23312d64bf1.png)
Have a nice day!

**Comment by TTnTTT** [comment]
真的服了，编译一天了还没解决，尝试了网上的十几种方法

**Comment by ChenMouRen** [comment]
> 

老哥解决没，我他妈也是编译一天了还没解决

**Comment by yjt1216** [comment]
好了吗？还在debug

> > 
> 
> 老哥解决没，我他妈也是编译一天了还没解决

**Comment by yjt1216** [comment]
可以试试 改动 mirror

**Comment by ChenMouRen** [comment]
不经常看邮箱，不好意思哈，我们项目里面不需要用到gradle打包，我把maven-gradle插件在pom文件里面全部注释了就成功了

尹江涛 ***@***.***> 于2023年8月31日周四 10:16写道：

**Comment by dlanorok** [comment]
Please add this known bug to the documentation.

**Comment by weifan01** [comment]
Because this file was not downloaded completely, you can manually download it and unzip yourself and place it in the `~/.gradle` directory.

**Comment by DISAI** [comment]
> 真的服了，编译了还没解决，尝试了网上的十几种方法
![image](https://github.com/thingsboard/thingsboard/assets/27934713/9e93747b-8d33-4acf-abd6-c1dd63f67c8c)

**Comment by DISAI** [comment]
Manual download

**Comment by sduqlsc** [comment]
https://github.com/thingsboard/thingsboard/issues/5335#issuecomment-1564269747

following above comment, added in the `pom.xml`:

```xml
 <plugin>
                            <groupId>org.thingsboard</groupId>
                            <artifactId>gradle-maven-plugin</artifactId>
                            <configuration>
                                <gradleProjectDirectory>${main.dir}/packaging/${pkg.type}</gradleProjectDirectory>
                                <gradleDistribution>https://mirrors.cloud.tencent.com/gradle/gradle-6.6-bin.zip</gradleDistribution>
                                <gradleInstallationDir>E:\\.gradle</gradleInstallationDir>
                                

```

changed to `tencent gradle mirror`, finally shows a build success message.


enviroment:

maven: 3.9.8
jdk: 1.8
os: win11
thingsboard:  3.1.1

**Comment by 1486756632** [comment]
> ```
> mirrors
> ```

thanks bro,it works
