### ISSUE TITLE
HTTPS for Thingsboard

### ISSUE THREAD

**Issue by ram1505** [thingsboard/thingsboard#370]
I'm a newbie to Thingsboard. Wondering how to make my AWS instance of Thingsboard secured with HTTPS?

**Comment by ssmaurya** [comment]
Easiest way in my opinion would be to run separate https server and redirect all traffic to localhost port of thingsboard. This way you don't need any additional configuration on thingsboard. Ensure that insecure port of thingsboard is not accessible from outside aws instance.

**Comment by ram1505** [comment]
As mentioned, I'm a newbie to thingsboard. Is there any settings within Thingsboard sysadmin where I can change all these to redirect?

**Comment by ssmaurya** [comment]
You need to install apache httpd and follow the following to configure redirection.
https://www.linode.com/docs/web-servers/apache-tips-and-tricks/redirect-urls-with-the-apache-web-server

**Comment by chunyeow** [comment]
Installed the self-signed certificate as followed for TB: 
https://thingsboard.io/docs/user-guide/mqtt-over-ssl/

Change configuration at /etc/thingsboard

**Comment by ram1505** [comment]
Still no luck for me. I'm looking at making the entire thingsboard over SSL.

**Comment by alexvargasbenamburg** [comment]
I use apache(ver 2.4.25) whit this VirtualHost configuration.
Enable this modules: ssl, proxy_wstunnel, proxy_http, proxy

``

  <VirtualHost *:443>
        ServerAdmin "EMAIL ADMIN"
        DocumentRoot /var/www/html
        ServerName "SERVERNAME"

        ProxyRequests off
        ProxyPreserveHost On
        #Redireccion de wss a ws
        ProxyPass /api/ws ws://localhost:8080/api/ws
        ProxyPassReverse /api/ws ws://localhost:8080/api/ws/
        #Redireccion de https(443) a 8080 mostrar maintenace.html en caso de error
        ProxyPass /maintenance.html !
        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile    "CERTFILE"
        SSLCertificateKeyFile "KEYFILE"
  </VirtualHost>

``

**Comment by mfalkvidd** [comment]
Thanks @alexvargasbenamburg 
Your example helped me create a nginx config that I've verified works with Thingsboard, including websocket support.
[nginx-thingsboard](https://gist.github.com/mfalkvidd/3920bd5035806a583b5c1e20eaddabae)

**Comment by adambforbes** [comment]
Does any one have any more simplified/complete instructions for changing a ThingsBoard instance to HTTPS ? I am having trouble following how to do this. It seems like it should be a base feature as everyone that accesses the site sees "Not Secure" at the top of their web browser every time they access the site.

**Comment by sfletc** [comment]
I second the above comment.  The setup isn't obvious (even with googling) if you're not familiar with AWS/web stuff

**Comment by toukke** [comment]
Have you tried installing HAProxy with Let's encrypt? (assuming you are using Linux)
https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

**Comment by GrayCygnus** [comment]
@toukke using HAProxy by following that link worked for me

**Comment by skuppens** [comment]
Will only installing HAProxy result in enabling https for thingsboard? I'm not having a full DNS-name. only IP.
I wanted to access TB on port 443 in stead of 8080 but changing this in the yml causes an error upon installing.

**Comment by michalfapso** [comment]
I've created a docker-compose.yml for Thingsboard + Nginx reverse proxy with automatic Let's Encrypt certificates: https://github.com/michalfapso/thingsboard_docker_https/
