### ISSUE TITLE
Fetch devices based on device type using rest api

### ISSUE THREAD

**Issue by sonychoudhary** [thingsboard/thingsboard#3706]
**Component**
 * Generic

**Description**
I want to fetch devices based on device type using rest api but its not working
![98800633-af21e480-2436-11eb-9841-2694b4b27ac9](https://user-images.githubusercontent.com/42209904/98845895-5a04c380-2474-11eb-8150-f96888964ae5.png)
![98800642-b0531180-2436-11eb-8212-44a22783b463](https://user-images.githubusercontent.com/42209904/98845899-5b35f080-2474-11eb-8b00-9f6a106ae259.png)

**Environment**
 * ThingsBoard: 3.0

**Comment by sonychoudhary** [comment]
correct packet format for query:
```
{
  "deviceTypes": [
    "device type you want to search"
  ],
  "parameters": {
    "rootId": "device id of the gateway",
    "rootType": "DEVICE",//device type of the gateway
    "direction": "FROM",
    "relationTypeGroup": "COMMON",
    "maxLevel": 0
  },
  "relationType": "Created"
}
```

**Comment by WillNilges** [comment]
Do you think you could post your full `curl` command?
