### ISSUE TITLE
How to setup https with letsencrypt when using Docker-compose Cluster deployment?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3709]
Hi Guys
I am trying to setup domain https when using the Docker-compose cluster deployment.

I setup certbot and get certificates on the server, how do I map those to the Docker Haproxy? 

https://github.com/thingsboard/thingsboard/blob/master/docker/haproxy/config/haproxy.cfg

any help greatly appreciated

**Comment by t0mmyz7** [comment]
any help on this guys ?

**Comment by jigar-j-patel** [comment]
I am searching similar configuration but not found anywhere.
I have installed thingsboard docker and want to setup certbot for letsencrypt and https using haproxy or anyother method.

**Comment by jigar-j-patel** [comment]
@t0mZ4 
I have found this link which might be useful.

https://stackoverflow.com/questions/63827227/enable-https-on-thingsboard
https://github.com/michalfapso/thingsboard_docker_https

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
