### ISSUE TITLE
[Bug] The 'Filter' on the dashboard is not showing the correct text (image below)

### ISSUE THREAD

**Issue by QMand** [thingsboard/thingsboard#3710]
**Describe the bug**
The new 'filter' features is not displaying the correct text because I watched the video explaining the new Filter feature and on Thingsboard CE the text is incorrect.

**Your Server Environment**
* own setup
  * cloud
  * ThingsBoard Version 3.1.1
  * Ubuntu 18

**To Reproduce**
1. Go to a dashboard and go into edit mode.
2. Click on the new Filter feature on the top of the page.
OR
1. Go to a dashboard and go into edit mode.
2. click on 'edit widget' and where the filter feature is now available the text shows filter.filter instead of the correct text.

**Expected behavior**
Correct text must be used. For example at the moment when clicking on filters the text on the popup should show Filter, not filter.filters and the 'ADD' button should only show 'ADD' not FILTER.ADD etc

**Screenshots**

![image](https://user-images.githubusercontent.com/13391739/98955780-faf08e80-2507-11eb-9f7b-9b90dde08bd0.png)

![image](https://user-images.githubusercontent.com/13391739/98955826-0ba10480-2508-11eb-8e92-f1daf077317a.png)

**Comment by dharapatel1596** [comment]
Hii,

Is anyone working on this issue? If not, I would like to work on this.

**Comment by xalt7x** [comment]
It might be a local issue (e.g. browser cache).

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
