### ISSUE TITLE
[Question] Why do I keep receiving ghost server-side RPCs?

### ISSUE THREAD

**Issue by GuilhermePiorno** [thingsboard/thingsboard#3714]
I'm  using Server-side RPC command to receive a command widget (switch)'s status. It works fine. But something is bothering me, everytime I subscribe to v1/devices/me/rpc/request/+ I receive 400+ publishes from the server immediately after.

I'll attach an image of what I get when I subscribe with MQTT Exploer for example.
![publishes](https://user-images.githubusercontent.com/50006421/98964683-e00e2200-24e7-11eb-99cc-2ab52eec0d1b.png)

Most of the publishes I get are `{"method":"checkStatus"}` messages. But some I recognize from switches that I already deleted from the dashboard they were. I created a switch with {method:AAAA} and deleted it for example. But I still get a `682 = {"method":"AAAAA"}` message as soon as I subscribe to request/+

Is there something I'm not understanding correctly? Can anyone let me know how to work around this? I don't want to receive nearly 500 useless publishes before I get a useful one.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
