### ISSUE TITLE
[Bug] Certificate creator issue : server.keygen.sh

### ISSUE THREAD

**Issue by molivost** [thingsboard/thingsboard#3715]
**Certificate creator issue : server.keygen.sh **

Hello Thingsboard dev team :-)

I'm working with SSL clients to TB mqtt broker.
And I'm integrating with tb_gateway another clients.
The problem is when TB gateway tb_client.py made the handshake by ssl.py produce this error:

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for 'x.x.x.x'

The issue is when generate the certificate with "keytool" on server.keygen.sh, because the server's IP is not incorporated

so I added "-ext" option in the script to add a "Subject Alternative Name" in the Certificate

```
THIS IS AN EXTRACT OF: server.keygen.sh 

.
.
.
keytool -genkeypair -v \
  -alias $SERVER_KEY_ALIAS \
  -dname "CN=$DOMAIN_SUFFIX, OU=$ORGANIZATIONAL_UNIT, O=$ORGANIZATION, L=$CITY, ST=$STATE_OR_PROVINCE, C=$TWO_LETTER_COUNTRY_CODE" \
  -keystore $SERVER_FILE_PREFIX.jks \
  -keypass $SERVER_KEY_PASSWORD \
  -storepass $SERVER_KEYSTORE_PASSWORD \
  -keyalg RSA \
  -keysize 2048 \
  -validity 9999 \
  ---> -ext san=ip:192.168.0.1,ip:100.10.10.100 <---
.
.
.
```
with this modification of the Certificate, is possible connect tb_gateway to MQTT on Thingsboard through SSL

Server:
Debian stretch
thingsboard 3.1.1 with MQTT SSL enabled (TLSv1)

Client:
python3-thingsboard-gateway  2.5.2
Python 3.7.3
TLS 1.0 (modified in /usr/lib/python3/dist-packages/thingsboard_gateway/gateway/tb_client.py)

greetings
and very thanks for your work
Marcos

**Comment by zbeacon** [comment]
Hi @molivost,

Please make sure that DOMAIN_SUFFIX is correct, it looks like you try connect devices with this certificate, but not from the same network(If you generate certificate for local IP but try to connect from external network, it will fail). Or you have a different IP (Usually 192.168.0.1 is IP of network router or switch). Please make sure that you use correct IP.

**Comment by Kralg** [comment]
I am also facing the problem in accessing the server by its IP address. I am unable to reach the server over the LAN or from outside the network even by using the server.keygen.sh with molivost modification ext san=ip:localServerIP,externalIP. Can you write what is the right way to configure the server.keygen.sh and keygen.properties to be able to use with IP addresses? For client I am using one-way-ssl-mqtt-client.py from https://thingsboard.io/docs/user-guide/access-token/

`Traceback (most recent call last):
  File ".\one-way-ssl-mqtt-client.py", line 49, in <module>
    client.connect("192.168.1.70", 8883, 1)
  File "C:\Python36_64\lib\site-packages\paho\mqtt\client.py", line 941, in connect
    return self.reconnect()
  File "C:\Python36_64\lib\site-packages\paho\mqtt\client.py", line 1104, in reconnect
    sock.do_handshake()
  File "C:\Python36_64\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python36_64\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)`

**Comment by ashvayka** [comment]
Hi @Kralg . We had similar issue during tests over ThingsBoard 3.2. We have fixed it by modifying few parameters in the one-way-ssl-mqtt-client.py. We will upload new version to the website soon. Meanwhile, you can review changes here: 
https://github.com/thingsboard/thingsboard.github.io/blob/bc483b73fb42d3edaf488ade2978d0b689683142/docs/user-guide/resources/mqtt-over-ssl/one-way-ssl-mqtt-client.py
