### ISSUE TITLE
Fetch old telemetry data in data post processing funtion

### ISSUE THREAD

**Issue by ANANTHAKRISHNAN1996** [thingsboard/thingsboard#3724]
**Component**

 * Generic

**Description**
To fetch old telemetry data from the database in widgets data post-processing function. I need to create a bill according to the water consumed in last month and display it in a widget. Inorder to do that i need to fetch old telemetry data for a particular timestamp. How can i do this. Thanks

**Environment**

 * OS: Windows 10
 * ThingsBoard:Thingsboard PE
 * Browser: Chrome

**Comment by PovitruliaV** [comment]
Hi @ANANTHAKRISHNAN1996,
For this, you will need to use rule chain logic. Please refer to this [Article as an example](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/transform-telemetry-using-previous-record/). Also, you can use for this rest API call node **getTimeseriesUsingGET** request and get the data for a particular timestamp.
Regards,
