### ISSUE TITLE
[Question] How to create a filter for all device assigned to a customer?

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3726]
**Component**

 * UI

**Description**
I want to create a dashboard data source filter that shows all devices assigned to a customer. It doesn't seem to be working as it shows error that no devices could be found for that customer (which is not correct), so I want to make sure I am following the right steps.

Please list the steps in creating such a filter.

**Environment**

 * OS:  MacOS Catalina 10.15.2
 * ThingsBoard: CE 3.0.1
 * Browser: Chrome, 86.0.4240.198

**Comment by ashvarma-git** [comment]
Please provide some guidance here.

**Comment by ashvarma-git** [comment]
Hello, I am still unable to get data source consisting of devices assigned to a customer.

![image](https://user-images.githubusercontent.com/55399007/102675968-4ffb7200-4150-11eb-8289-d600eab4af90.png)

It shows "No entities matching specified filter were found" which seems incorrect.
Can you please comment if I am using this form correctly if I want to add certain Device types for a customer (customer name hidden in screenshot)?

Thanks.

**Comment by ssakharova** [comment]
Hello @ashvarma-git,

First, you need to create relations between the customer and his devices. 
After that, in order to display the list of customer devices, you need to configure the device search query alias type, as shown in the screenshot below:
![image](https://github.com/thingsboard/thingsboard/assets/98035385/ead7bc80-b485-4839-947a-d5ec3625d430)

**Comment by icoco** [comment]
if many customer , need the same feature dashboard , how to create one that works for different customer ?

**Comment by icoco** [comment]
well got it, should use 'Type Current User Owner' ,  👍
