### ISSUE TITLE
[Customer Portal] Please provide a reasonable answer to your customer

### ISSUE THREAD

**Issue by ysit-thingsboard** [thingsboard/thingsboard#3728]
**Describe the bug**
TB support team will only ask their customers increase hardware capabilities when a customer encounters a performance problem.  We have encountered performance problem at data rate of 1100, and even 10 datapoints per second in a cluster deployment. That's the only we received the same answer from TB after complaining to their manager. And yet, TB website claims that they can handle 10000 datapoints per second with standalone deployment.

All we want is a **reasonable answer**, but TB said they can't do that because we only on the basic support plan.

**Your Server Environment**
Just setup a standalone deployment will do.

**To Reproduce**
1. Buy a TB license
2. Encounter an performance problem
3. Ask for help on customer portal
4. Wait for TB team to ask you to increase your hardware capabilities

**Expected behavior**
A reasonable answer provided from TB team on the customer portal

**Screenshots**
From me:
![image](https://user-images.githubusercontent.com/71913697/99475791-3f59af80-298a-11eb-8770-cf3f6ccf8a26.png)

From TB Manager:
![image](https://user-images.githubusercontent.com/71913697/99475643-ef7ae880-2989-11eb-97a7-66a8fe063eef.png)

**Comment by ysit-thingsboard** [comment]
We never asked TB to provide solution with exact time. Here is an e-mail that I sent to TB manager on 9/18:

![image](https://user-images.githubusercontent.com/71913697/99629818-a606c800-2a73-11eb-9c8f-c029ce90254d.png)

**Comment by ashvayka** [comment]
Hi @ysit-thingsboard , just for the record, we have issued the refund.

**Comment by ysit-thingsboard** [comment]
The surprise is that your team would prefer to refund rather than just provide reasonable replies to your customers.
