### ISSUE TITLE
[Feature Request]Suggest to support Timeseries DB, i.e InfluxDB

### ISSUE THREAD

**Issue by zhxiaodong** [thingsboard/thingsboard#3729]
Currently only support Postgresql and Cassandra. For iot data, I suggest put them into InfluxDB; for relational data, still put them into PG.

I can help you deliver this feature.

**Comment by xiddjp** [comment]
Are you finished this feature?@zhxiaodong

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
