### ISSUE TITLE
[Question] How can I implement Multi-Factor Authentication (MFA) for user login to dashboard?

### ISSUE THREAD

**Issue by tengann** [thingsboard/thingsboard#3730]
**Component**

 * Generic

**Description**
I have a Professional Edition setup hosted in cloud using AWS EC2 instance. 

Are there any possible methods to implement Multi-Factor Authentication (MFA) for user login to the dashboard?

I am attempting to implement it using the GoogleAuth library from https://github.com/wstrange/GoogleAuth.

However, it seems like either Maven or Gradle is needed to add the dependencies to my build environment in order to use the library. Is there a Maven or Gradle plugin that can be included into my instance for this purpose?

**Environment**

 * ThingsBoard: v3.1.1 PE

**Comment by Ultrazombie** [comment]
2fa already implemented in 3.4+ versions.
