### ISSUE TITLE
[Feature Request] Multi-Factor Authentication (MFA) for User Login

### ISSUE THREAD

**Issue by tengann** [thingsboard/thingsboard#3732]
**Is your feature request related to a problem? Please describe.**
I have a Professional Edition setup hosted in cloud, using AWS EC2 instance. I need a way to implement more secure login to the dashboard for users preferably through the user of Multi-Factor Authentication (MFA) but currently, there seems to be no way I can implement it.

**Describe the solution you'd like**
Are there any MFA plugins currently supported for use on ThingsBoard? 

**Describe alternatives you've considered**
The only security feature I know of for user login is the Single Sign On functionality through OAuth 2.0 protocol but it is not what I am looking for.

**Comment by Ultrazombie** [comment]
https://thingsboard.io/docs/user-guide/two-factor-authentication/
Already implemented.
