### ISSUE TITLE
[Question] Entity admin widget with checkbox

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3734]
**Component**

 * UI
 * Generic

**Description**
Could anyone tell me how to add checkbox for entity admin widget for each row ?
Many thanks
**Environment**

 * OS:  ubuntu 20.04
 * ThingsBoard: 3.1.1 PE
 * Browser: chrome

**Comment by ashvayka** [comment]
What would you like to do with the checkbox? What action should be taken when the checkbox is pressed?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
