### ISSUE TITLE
[Bug] the description of rule engine's create relation node not take into account

### ISSUE THREAD

**Issue by songkemail** [thingsboard/thingsboard#3738]
**Describe the bug**
* It does no effect whatever the description set when use create relation node.

**Your Server Environment**

* demo.thingsboard.io
* own setup
  * docker deployment
  * 3.1.1
  * centos 7.8

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: windows 10
* Browser [chrome]
* Version [22]

**To Reproduce**
1. Go to 'rule chain'
2. Click on 'create relation node'
3. Scroll down to 'description', and edit json-type info,then save the configuration.
4. the relation created but without any description provided.

**Expected behavior**
A created relation with the provided "description" as additional info. It'll be better if the description can be use ${metaKeyName} to substitute variables from metadata

**Screenshots**
![image](https://user-images.githubusercontent.com/4156359/99331704-f4bd3200-28ba-11eb-8a22-f30a5360d75a.png)

**Comment by vvlladd28** [comment]
Hi @songkemail,

This behavior is not a bug because the input field 'Description' possible to add notes for the rule nodes. 
Rule node 'Created Relation'  not yet supported fields 'additional info'.
