### ISSUE TITLE
[Bug] rule-engine-controller all api always returns 408

### ISSUE THREAD

**Issue by songkemail** [thingsboard/thingsboard#3739]
**Describe the bug**
It always returns 408 when the api in the rule-engine-controller catalog, envn though the rest reply node's debug output the success info.

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [win10]
* Browser [chrome]
* Version [22]

**To Reproduce**
1. Go to 'rule chain', add rest reply node, then connect to the swith type node with "rest api request" connection type.
2. Use swagger to send POST /api/rule-engine/* request, returns 408

**Expected behavior**
Returns the custom result other than 408.

**Screenshots**
![image](https://user-images.githubusercontent.com/4156359/99337408-2931ed80-28bd-11eb-995c-f9f460a556f6.png)

![image](https://user-images.githubusercontent.com/4156359/99337231-d6f0cc80-28bc-11eb-8a43-92989f6a85ff.png)

**Comment by nmahale10** [comment]
Hello Have you got any solution  for this. I am stuck in same issue

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
