### ISSUE TITLE
[Feature Request] Create a helm chart for deploying on kubernetes

### ISSUE THREAD

**Issue by gmenuel** [thingsboard/thingsboard#3741]
Currently for deploying on kubernetes is running shell scripts which create the kubernetes resources. Having a helm chart for doing that would allow for easier configuration, upgrade and deletion of thingsboards resources.

Is the creation of an helm chart something that could be useful for other people ?

**Comment by ozanturker** [comment]
@ikulikov hi, would you mind if I want to pick up this issue?

**Comment by MWallenberg** [comment]
I think this would be really useful. Shell-scripts and yaml-files make it harder to manage, upgrade and maintain the application over the long run. Helm charts would be a lot better.

**Comment by chris3081** [comment]
I started the process I haven't finished converting everything over yet, so its not ready for PR. Your Welcome to assist if you like.

**Comment by contrun** [comment]
Here is a link to @chris3081 's effort. https://github.com/chris3081/thingsboard

**Comment by chris3081** [comment]
that version of the chart still needs a few things, below is the laundry list:-

- Finish the different install modes simple, hybrid, provide your own DBs 
- Need to build helm tests so installs are tested thus can be marked failed and rollback when things went wrong
- some testing to ensure the professional edition works as it should, I don't own a license so testing is a challenge.
- test rolling rolling upgrades/downgrades(assuming the software is happy there)
- documentation (in the form of a readme.md)
- documentation in the values.yaml

Things that I think would be cool
- add HorizontalPodAutoscaler in assuming it doesn't break the professional licensing agreement. Also need to ID the correct conditions for that scale out/in.

Happy to turn over ownership of my fork to the original poster if they choose, I started building out this sometime back for a friend who uses thingsboard as part of their job so my knowledge on the product is limited but happy to build the chart out.

**Comment by movergan** [comment]
Helm is a must in 2021. +1

**Comment by midokura-agustin** [comment]
Hi, I just submitted a PR to add helm support: https://github.com/thingsboard/thingsboard-ce-k8s/pull/59

Let me know what you thing about it

**Comment by midokura-agustin** [comment]
PR merged!
https://github.com/thingsboard/thingsboard-ce-k8s/pull/59

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
