### ISSUE TITLE
I do not understand data storage procedure

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#375]
I do not understand how thingsboard works...
After several sendings of Data, I see only the value changes.
Please how to get multiple values based on the send time?

![image](https://user-images.githubusercontent.com/6891046/32007696-942bdbbc-b9aa-11e7-95bd-bb7a7a570c27.png)

Thank you.

**Comment by ssmaurya** [comment]
You can try creating dashboard with this value and on dashboard you can see historical data. On this screen, you will only last value. For historical dats, use dashboards

**Comment by kimoudev** [comment]
I do not know if i made a bad configuration somewhere.
after nearly 10 different sendings of data to my divice SN002.
I still get the latest record.
I have selected history with a time period.

![image](https://user-images.githubusercontent.com/6891046/32031644-cc8a0d46-ba02-11e7-9c9a-8857487dca97.png)

Thank you @ssmaurya

**Comment by ssmaurya** [comment]
Try with timeseries chart instead of bar chart and see if you are getting the historical data. or use timeseries  table from cards widget

**Comment by kimoudev** [comment]
Thank you very much @ssmaurya

**Comment by guo-tt** [comment]
How to store the data into external cassandra database?

**Comment by vparomskiy** [comment]
What do you mean by 
> external Cassandra database
?

If this Database is not part of the Thingsboard storage layer, then you need to implement service that will implement communication with External storage and then integrate it in the Thingsboard.

If you just want to use Cassandra as the main database in Thingsboard, then please find details here:
https://thingsboard.io/docs/user-guide/install/linux/#optional-configure-thingsboard-to-use-the-external-database
