### ISSUE TITLE
[Bug] MQTT borker SSL key_store path not work as doc describe 

### ISSUE THREAD

**Issue by seua** [thingsboard/thingsboard#3750]
**Describe the bug**
As user guide describea, https://thingsboard.io/docs/user-guide/mqtt-over-ssl/#self-signed-certificate-generation, the ssl keystore file is a normal path like /etc/thingsboard/conf/mqttserver.jks.
But the code is 

public class MqttSslHandlerProvider {
....

            URL ksUrl = Resources.getResource(keyStoreFile);
            File ksFile = new File(ksUrl.toURI());

Resources.getResource only works with resources in the classpath.  So the keystore file can not be configured.

**Comment by zth390872451** [comment]
/*URL ksUrl = Resources.getResource(keyStoreFile);
            File ksFile = new File(ksUrl.toURI());
            URL tsUrl = Resources.getResource(keyStoreFile);
            File tsFile = new File(tsUrl.toURI());*/
            File ksFile = new File(keyStoreFile);
            File tsFile = new File(keyStoreFile);

key_store: "${MQTT_SSL_KEY_STORE:E:\\GitSelfWorkspace\\thingsboard\\mqttserver.jks}"

I alter some code,you can try it!

**Comment by chhein** [comment]
Is it possible that this realtes to #4216 ?
@zth390872451 
@seua

**Comment by Ultrazombie** [comment]
Closed due inactivity
