### ISSUE TITLE
Save data to custom table in postgreSQL 

### ISSUE THREAD

**Issue by omar-mha** [thingsboard/thingsboard#3751]
Hello All,

I have succesfully installed Thingsboard CE on an AWS environment. It is running correctly without issues. I have installed this version with PostgreSQL only.
 @@
My project will consist of a network with multiple devices. Each device has its own sensors. I need to have the data from each device separated in different tables. In first instance my plan was to create different tables and route the data to those tables using the rule engine. But now I have seen in the rule engine guide that this is only possible for Cassandra DB. 

Is this still the case and are there any other possibilities available?

Thanks in advance!

**Comment by ashvayka** [comment]
Hi @CrazyRs6 I strongly believe that creating a table per device is not a scalable solution. You may push incoming data to Kafka or other message queue and write your own micro service to store the data in any format and any db. However, you will not be able to use those "alternative" PostgreSQL tables to graph data in the dashboards

**Comment by trypzz** [comment]
closed due to inactivity
