### ISSUE TITLE
Remote TCP Integration - Integration is not working properly and debug mode is not returning messages

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#3752]
**Describe the bug**
The debug mode of tcp integration seems to be not working properly. Just in some conditions it is generating error messages. The same behavior is happening with the data converter related, it is just generating error message in the some conditions: the same when the integration events are generated. Up to know I wasn't able to get any success message. So, it is being difficulty to put it to run once we are not having conditions to check if the The service seems to be working ok based on the verbose of log file. I am using a Binary Handler with length at 5th byte with 1 byte length and at this moment I am not adjusting neither striping any first bytes. So, I don't know if the problem is at my side with some mistakes at configuration or if it is really a bug on that. So, could you help me with that? Because at the same server I am running a http integration which is running for months without any problem.

**Your Server Environment**
* Google cloud Instance
   * ThingsBoard 3.1.1PE
  * OS Ubuntu 18

**Your Client Environment**
* OS: Windows 10
* Browser Chrome, Firefox and Edge
* Connectivity
* Integration: TCP

**To Reproduce**
1. I am using a real NB-IoT sensor to send payload to my server and port. Beside that, I am also using Hercules software to emulate a TCP client to send sensor payload (Hex). I am also pointed my remote integration to cloud.thingsboard.io to check if there was something with my installation, but the behavior was the same. The payload looks like something like in Hex: 383030303031303231453032423130303136303030303030303030313638303038303634433430303139313836353035373034343338363831353831, the length is 30 bytes, the length byte is at 5th byte and the length of it is 1 byte and I could strip the first 5 bytes.

**Expected behavior**
What I was expecting is to receive for every message (from sensor or Hercules software) an event at integration debug tab to check if it is working fine or not and help me to put it live.

**Screenshots**
Attached I am sending the tcp integration verbose of tb-tcp-udp-integration service, and I am also copying some printscreens

**Additional context**
[TCP-Integration-Binary-Handler.txt](https://github.com/thingsboard/thingsboard/files/5561794/TCP-Integration-Binary-Handler.txt)
[screenshots.docx](https://github.com/thingsboard/thingsboard/files/5561827/screenshots.docx)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
