### ISSUE TITLE
Is there a way to hide a widget based on device type?

### ISSUE THREAD

**Issue by sferguson-ISI** [thingsboard/thingsboard#3758]
**Component**
Dashboard states

 * UI
Multiple dashboard for devices

**Description**
Is there a way to hide a widget based on the device type that's clicked?  For Example I have an entity list widget with all my devices on my first landing page dashboard.  The user clicks on the device and it goes to a dashboard state with detailed info.  I have devices that are very similar but may or may not have an extra feature such as humidity.  So basically if I have a device with temperature and humidity I want to show the graphs of temperature and humidity when I click on that type of device.  If I have a device with only temperature the info dashboard should have no humidity graph.  

Is the only way to do this with multiple dashboards?  The issue I have with that is there are several other widgets on the info page and if I make a change to one of those other widgets I now have to duplicate the change on the other dashboards....

**Environment**
 * OS:  Windows Server 2016
 * ThingsBoard: 2.3.4
 * Browser: Chrome (latest version)

**Comment by ChantsovaEkaterina** [comment]
Hello,
There is no option to hide a widget from a particular state but in your case, you could create a second state (not a new dashboard), and when clicking on a device in the list check its type and depending on this navigate to the needed state. As for widgets that should be the same for both states (only if they are completely the same including a datasource set, state entity for example), there is an ability to copy widget by link. If the widget copied by link, changes made to it in one state should be automatically propagated to another.

**Comment by jonrot1906** [comment]
Depending on your widgets, you could also apply a filter, which will check for attribute or timeseries "humidity". E.g. applaying an attribute filter "Humidity" with key name "humidity" you can set operation to "ignore case" if this attribute "not contains" a value (you leave the value line blank). Now if you have a widget where you want to display your humidity and temperature timeseries, simply create a datasources which will apply the filter for each device depending on your dashboard state.

**Comment by sferguson-ISI** [comment]
> Hello,
> There is no option to hide a widget from a particular state but in your case, you could create a second state (not a new dashboard), and when clicking on a device in the list check its type and depending on this navigate to the needed state. As for widgets that should be the same for both states (only if they are completely the same including a datasource set, state entity for example), there is an ability to copy widget by link. If the widget copied by link, changes made to it in one state should be automatically propagated to another.

This was a good workaround and prevents me from having to duplicate widget code changes.  For anyone else looking at this, when you click on a widget there is an option to "Copy" or "Copy Reference" do the later. thanks!
