### ISSUE TITLE
Login expiration

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#376]
As I observed, a single login at a specific computer is enough to keep the user logged-in forever. Regardless of page refresh, browser restart, computer restart etc...

Problematic scenario: I get to a friend, and use its computer. When finished, I forgot to log out. Now he has indefinite access to my account.

The user session, should expire somehow, restricting such cases of possible misuse. The user shall be prompted again for password after expiration.

**Comment by mfalkvidd** [comment]
@fotis400 see https://github.com/thingsboard/thingsboard/issues/85

**Comment by fotis400** [comment]
My problem is not about dashboards, but about the tenant administrator login.

Was is said in #85, if it is working as described seems perfect.

However my observation on my tenant administrator account is that it is not expiring at all, even if closing the window, and trying many days later.

Unless of course there was any fix recently on this. I am using 1.3.1

**Comment by Javierete** [comment]
@fotis400 I'm running from git master (1.4.0) and this problem seems fixed to me

**Comment by fotis400** [comment]
I tested 1.4.0 too and it seems fixed.
