### ISSUE TITLE
[Bug/Question] Missing .yml file from AWS thingsboard instance

### ISSUE THREAD

**Issue by Lautaro-a** [thingsboard/thingsboard#3761]
Hello, i have a TB instance installed on an AWS server, i was recently working with the UDP integration but the file "tb-tcp-udp-integration.yml" is missing.
when i do `` ls /etc/tb-tcp-udp-integration/conf `` the only files that show are "logback.xml" and "tb-tcp-udp-integration.conf".
I've searched on nearby folders but it isn't there.
is there any way to download or reinstall the file?
thanks.
![0a2b10a43983675a34110df95592e985](https://user-images.githubusercontent.com/69549697/99897612-b2f50880-2c79-11eb-8646-8c13a530bf00.png)

-Thingsboard server-
* AWS EC2 t3.micro setup
* Ubuntu 18.04.5
* Thingsboard version 3.1.1PE

**Comment by Ultrazombie** [comment]
Closed due to ianctivity
