### ISSUE TITLE
scheduler initialization with string coversioned to number

### ISSUE THREAD

**Issue by Boolhwi** [thingsboard/thingsboard#3766]
Is there any way to prevent type cast string value to number?
When I insert string value like "00000" to shared attributes in a device,
it is automatically conversioned to integer 0.

Thanks in advance.

**Comment by Boolhwi** [comment]
@ashvayka

**Comment by vvlladd28** [comment]
Hi @Boolhwi,
This issue has been fixed in version TB 3.1.1

**Comment by Boolhwi** [comment]
hi there @vvlladd28 
You said this issue has been fixed in TB 3.1.1, but I'm already using TB 3.1.1 (PE version).
Is that solution worked obviously??
