### ISSUE TITLE
[Question] Propagating telemetry data received via REST API call in the rule engine

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#3777]
**Component**
 * Rule Engine

**Description**
I have device that contain devices. In the rule engine I created a rule that generate an REST API request to a server that I created, the generator node is specified to the main device. The information that I get back is regarding all the devices that are contained by the main device. What I want to do is to propagate the data I received to each child device, what is happening for me is that the main device get the telemetry data. To get the data I want for each child device I generated a new call in a new rule and get what I need from the data I received, this seems to me not the right way. How can I achieve that?
The flow of the rule for the main device is:
generator node -> rest api call node -> transformation script -> rule chain(root rule)

**Environment**
 * OS:  Ubuntu 20.04.1
 * ThingsBoard: v3.1.1
 * Browser: Chrome

**Comment by ashvayka** [comment]
ThingsBoard PE has a "Duplicate to related" transformation rule node. If you are CE user, you can develop a similar node using [rule node development guide](https://thingsboard.io/docs/user-guide/contribution/rule-node-development/)
