### ISSUE TITLE
Rule Engine Filter per Device Group

### ISSUE THREAD

**Issue by manuel-iot** [thingsboard/thingsboard#3779]
**Component**

 * Rule Engine

**Description**
How do I get the DeviceGroup in the RuleChain for a Device that sends Telemetry Data?
UseCase: Devices in GroupA should save telemetry Data for 6 Month, Devices in GroupB should save telemetry Data only for 6 Hours. Or different Aggregations for Devices in different Groups.

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.1.1 PE

br
Manuel

**Comment by ashvayka** [comment]
Hi @manuel-iot . Since 3.2 we have introduced device profiles which allow you to set a specific rule chain per [device profile](https://thingsboard.io/docs/user-guide/device-profiles/). We will add a task to our roadmap to allow fetching attributes of the group in the rule chain.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
