### ISSUE TITLE
Bad view in mobile

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#378]
Look at the following screenshot from my mobile:

![screenshot_2017-10-25-21-08-21](https://user-images.githubusercontent.com/3100169/32015103-c19559fc-b9c8-11e7-8372-5bdb33c70aef.jpg)

Here you can observe two issues:
* The edit button gets awfully in the way of selecting another tab, like in this case latest telemetry. I think it is better to move it a bit.
* Look at the values bellow. Nothing constrains the size of the texts. Everything gets on top of each other, creating an unreadable mess. Including the colums titles ("Last update time" and "Key"). Maybe somehow restrict the size of the various texts? Change "Last update time" to "Last update", and maybe shorten the telemetry keys appending a "..." at the end?

**Comment by yefimov-andrey** [comment]
Considering the first point about the edit button - this is still the case, I will add your suggestion to the backlog.
Considering the second point - there is a horizontal scrollbar at the bottom to see all the correct telemetry keys and values.

**Comment by fotis400** [comment]
Hi @yefimov-andrey,

regarding the second point, the problem is not scrolling. It is that the texts overlap, making an unreadable mess. The texts must be constrained within the boundaries of their column only, and not be able to overflow to the next column.

**Comment by yefimov-andrey** [comment]
@fotis400 , 
Can you provide fresh screenshots? I couldn't see the issue on Android Chrome.

**Comment by fotis400** [comment]
@yefimov-andrey here you are. This is on Firefox for Android.

As you see, the content of the key column overflows over the value column.

![Screenshot_20200630-175359](https://user-images.githubusercontent.com/3100169/87343901-3e38f180-c556-11ea-9d0c-b214536ef59f.jpg)

**Comment by yefimov-andrey** [comment]
We recommend using Chrome on all platforms as it is one of the most stable in our practice.

**Comment by ashvayka** [comment]
Hi @fotis400 ,

First of all, I would like to apologize for @yefimov-andrey responses. 
Second, This is now fixed in 3.x. I am attaching screenshots from both Chrome and Firefox on Android. 
Firefox:
![Issue378ScrollWorksInFirefox](https://user-images.githubusercontent.com/5016373/95307599-82a40700-0891-11eb-8a8f-dde4346322f1.jpg)

Chrome:
![Issue378ScrollWorksInChrome](https://user-images.githubusercontent.com/5016373/95307604-833c9d80-0891-11eb-81dc-0dadc2d8820f.jpg)

**Comment by fotis400** [comment]
Hi @ashvayka,

indeed this is correct on Thingsboard 3. It works as expected.

Thank you!
