### ISSUE TITLE
[Question] How to make widget that takes input from user and sends that input to integration downlink?

### ISSUE THREAD

**Issue by marinbudimir** [thingsboard/thingsboard#3782]
**Custom widget**

I want to make simple custom widget that takes some input from user, e.g. some input text, and sends that text to integration downlink. But I can't figure how to do that.

For example if this is our widget:
![Screenshot from 2020-11-27 13-22-28](https://user-images.githubusercontent.com/26256491/100449186-c65a0680-30b3-11eb-9a12-97c7cb94ef7c.png)

Our downlink converter should get { "key": "value"}

Is that possible to do?

**Comment by santobedi** [comment]
Hello @marinbudimir @ashvayka,

Any updates on it?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
