### ISSUE TITLE
[Question] hard to build ui-ngx , when run "yarn install" 

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#3784]
**Component**

 * UI-ngx
  

**Description**
hard to build ui-ngx module ,   when run "yarn install",  it report bellow message that seem show network connection issue, but that should not a problem indeed, what make this problem ? 

yarn install
yarn install v1.22.4
[1/4] Resolving packages...
warning @angular/cli > debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/common/-/common-10.0.9.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/tb/ui-ngx/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

**Environment**

 * OS:  mac, centos
 * ThingsBoard: 3.1.1

**Comment by ashvayka** [comment]
Try to clear node_modules: 
```bash
rm -rf ui-ngx/node_modules
```

**Comment by dharmesh95** [comment]
Tried mvn clean install on release 3.2 and it showed
`There appears to be trouble with your network connection. Retrying...`
Do I have to install yarn manually?

**Comment by ashvayka** [comment]
No, it is probably an issue with your network or yarn servers.. Please clean node modules and try again. We never experience similar issues.

**Comment by dharmesh95** [comment]
Fix was to add timeout
`<arguments>install --network-timeout 1000000</arguments>`
