### ISSUE TITLE
How is it possible  the device telemetry Called from the in the Rule chains section?[Question] your title here

### ISSUE THREAD

**Issue by sinafast117** [thingsboard/thingsboard#3785]
Hello.
I'm working with thingsboard 
I have defined an external device And the information that is in the Latest telemetry section and my connection is established online.
I can define a Widgets to display and store my telemetry .Everything is ok.

My problem is in this part: I want to create an alarm for my telemetry .
I'm going to the Rule chains section for this . I want to  through this page using script block and create alarm block do this.
But my problem is that my telemetry is not known on this page And I can't write any code to create alarm I can attribute to my telemetry.
Please help me. How can I set an alarm for my device telemetry?
(https://user-images.githubusercontent.com/75209911/100545098-68721e00-326f-11eb-8722-476dcfac410e.png)

**Comment by ashvayka** [comment]
Hi @sinafast117 . Please specify what version of the platform you are using. If 3.2, you may receive data from this device into a different rule chain. And that may be the cause of the issue.
