### ISSUE TITLE
How to send RPC command from widget action?

### ISSUE THREAD

**Issue by Nehruprasath1** [thingsboard/thingsboard#3786]
How to send RPC command from widget action(thingsboard)?

**Comment by winbillatgithub** [comment]
Different protocols have different ways to send RPC command, as for modbus:
write [{\"tag\":\"payload\",\"functionCode\":16,\"address\":0,\"registerCount\":2,\"byteOrder\":\"0B0A0D0C\",\"bit\":14,\"value\":100.1}]

**Comment by Nehruprasath1** [comment]
Am used MQTT protocol. So, how to send RPC command via widget action?
![thingsboard](https://user-images.githubusercontent.com/75245302/100719836-2964d980-33e3-11eb-9cfa-1315216448fc.jpg)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
