### ISSUE TITLE
[Question] Notification "No message available" when generating pdf / jpeg / png for Dashboard

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#3787]
**Component**

 * UI

**Description**
I want to generate reports from a dashboard. First of all I tried exporting a dashboard as pdf by clicking on "Export Dashboard" directly in the Dashboard. T tried different browsers firefox and chrome and different thingsboard versions but without success. What am I missing? 
Is there someting I need to activate in the setup of thingsboard? 

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 2.4.3 and 3.1.1
 * Browser: All

![grafik](https://user-images.githubusercontent.com/45274753/100603535-8a1de480-3305-11eb-8897-ecb5c2f04b41.png)

**Comment by ThomasBaumgartner** [comment]
After updating to Thingsboard PE 3.2 to error still occurs, but the error message slightly changed. Which is the suggested troubleshooting?
![grafik](https://user-images.githubusercontent.com/45274753/102773230-32651d00-4389-11eb-8758-93679709e404.png)

**Comment by Arsal973** [comment]
@ThomasBaumgartner can you share logs to see the path headless browser in the reporting server uses to fetch the dashboard?
In case you are using TB with Https behind a proxy then you face this issue as it adds port 80 to the URL with https protocol (**https**://<your-domain>:**80** ........)
