### ISSUE TITLE
[Question] Steps after changing thingsboard-master/application/src/main/resources/thingsboard.yml

### ISSUE THREAD

**Issue by ashvarma-git** [thingsboard/thingsboard#3789]
**Component**

 * Installation

**Description**
I have CE 3.0.1 installation on my own cloud server. After making a change to thingsboard-master/application/src/main/resources/thingsboard.yml, can I just restart thingsboard service or does it require recompile of the application also?

**Environment**

 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: CE 3.0.1
 * Browser: Chrome

**Comment by vvlladd28** [comment]
Hi @ashvarma-git,

After changing the YAML file, your need to recompile the application.  
It is also possible to overwrite the YAML value, editing ThingsBoard configuration file `/etc/thingsboard/conf/thingsboard.conf`, then you only need to restart thingsboard service

**Comment by ashvarma-git** [comment]
Did you mean /etc/thingsboard/conf/thingsboard.yml?
What will be the format in /etc/thingsboard/conf/thingsboard.conf vs a yml file if I want to change:

      max_updates_per_session: "${TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION:300:1,3000:60}"

**Comment by vvlladd28** [comment]
Hi @ashvarma-git,

For example, your case:
`export TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION=300:1,3000:60`

**Comment by ashvarma-git** [comment]
Hi,

I did as recommended above by creating
/etc/thingsboard/conf/thingsboard.conf with this single line:

export
TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_UPDATES_PER_SESSION=10000:1,30000:60

I restarted thingsboard service.

But I still continue to get the WebSocket Error: Too many updates!


-Ash
