### ISSUE TITLE
Signup page not appear in login site ?

### ISSUE THREAD

**Issue by stephenvxx** [thingsboard/thingsboard#379]
Hi i run my local thingsboard but my login site doesnt have signup page ? How to solve the prolem ? Thank you.

**Comment by mfalkvidd** [comment]
@stephenvxx see https://github.com/thingsboard/thingsboard/issues/265

**Comment by vparomskiy** [comment]
Sign up page is the part of demo environment and is not planned to be a part of main code base. But If you wish you can contribute this feature.

**Comment by steele-cjf** [comment]
> Sign up page is the part of demo environment and is not planned to be a part of main code base. But If you wish you can contribute this feature.

where?
