### ISSUE TITLE
[Bug] Root Rule Chain convert string without letter automatically to number

### ISSUE THREAD

**Issue by cc-rabali94** [thingsboard/thingsboard#3790]
Hello, I have notice, that TB Root Rule Chain converts string which doesn't contains any letter automatically to an integer. In my case I want to use this string as an identifier for my sub rule chain to create a relation with an asset.  

**Describe the bug**
Root rule chain converts string without letter/character automatically to integer/number

Incoming message from Integration:
`{
    "charge": "A234567880",
    "mandant": 125,
    "materialNr": "A2C456789012345678",
    "trADatum": 1230760740000,
    "trEDatum": 1230767940000,
    "trackStatus": 1,
    "trackingId": "010003010009"
}`

Message Inbound in Root Rule Chain:

`{
    "charge": "A234567880",
    "mandant": 125,
    "materialNr": "A2C456789012345678",
    "trADatum": 1230760740000,
    "trEDatum": 1230767940000,
    "trackStatus": 1,
    "trackingId": 10003010009
}`

**Your Server Environment**
* own setup
  * local infrastructure deployment
  * ThingsBoard Version 2.5.4PE
  * OS Version CentOS 7
  * Java Version OpenJDK 8 (1.8.0_252)

**Your Client Environment**

* OS: Windows 10 Version 20H2 
* Browser Google Chrome 
* Version  86

**Your Device**

* Connectivity
  * Integration: HTTP
* Content-Type: application/json (JSON Object)

**To Reproduce**
1. Create an uplink data converter which parse and return the incoming string from HTTP to JSON object 
2. Create a HTTP Integration which uses the uplink converter created earlier
3. Go to Root Rule Chain and turn on debug mode on "Message Type Switch". **You will see the bug described above on EVENTS Tab as Type IN and OUT**
3. Send a message (see bug description) as HTTP POST to integration URL with content-type application/json
4. See error on EVENTS Tab in "Message Type Switch",

**Expected behavior**
JSON string should not be converted to number automatically.

**Comment by ashvayka** [comment]
The behavior of automatic conversion is controlled using the JSON_TYPE_CAST_ENABLED env variable (true by default).

**Comment by cc-rabali94** [comment]
Thanks. I'll try it out

**Comment by Backdraft007** [comment]
I have the same issue with an MQTT-Client. The device send an ID with 20 digits. When I look at the attributes at the device, it shows the right data.
When I use a widget (e.g. Cards), it shows a wrong value. I set JSON_TYPE_CAST_ENABLED to false and restarted service.
But no change. Our workaround is, that we send "ID" infront. But it is only a workaround.

**Comment by ashvayka** [comment]
Hi @Backdraft007 , If the attributes of the device shows correct, then this is a different issue. Because @cc-rabali94 telemetry is affected by JSON conversion on the transport layer and your telemetry is stored ok, but displayed differently.
