### ISSUE TITLE
Double Menu when using custom white-label menu [Bug] 

### ISSUE THREAD

**Issue by f4ndor** [thingsboard/thingsboard#3793]
**Describe the bug**
After updating to thingsboard 3, we are experiencing weird custom menu behaviour:
We used the iframeUrl to create sidebar links to dashboards ( see code below )
This used to work fine, but now it creates double menu and header around the dashboard.
Any insight on how to fix this? Is there a proper way to link to  dashboard besides "iframeUrl" ?

**Your Server Environment**

* own setup
 ThingsBoard PE 3.1.1

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: windows / any
* Browser chrome 

**To Reproduce**
```
{
  "disabledMenuItems": [
    "home",
    "integrations",
    "converters"
  ],
  "menuItems": [
    {
      "name": "TEST",
      "iconUrl": null,
      "materialIcon": "view_list",
      "iframeUrl": "/dashboardGroups/ceda14d0-21b4-11ea-9de0-11b867bb66d6/205cc980-f710-11e9-9c20-01ad4df032ab",
      "setAccessToken": false,
      "childMenuItems": []
    },
```

**Expected behavior**
Not to have double site menu

**Screenshots**
![image](https://user-images.githubusercontent.com/3774057/100760398-042b9780-33f2-11eb-9601-6830f32da917.png)

**Comment by vvlladd28** [comment]
Hi @f4ndor,

 This is didn't bug, key setting iframeUrl injecting all page view. You need to change line to work correctly: 
`"iframeUrl": "/dashboardGroups/ceda14d0-21b4-11ea-9de0-11b867bb66d6/205cc980-f710-11e9-9c20-01ad4df032ab",`
to:
`"iframeUrl": "/dashboard/205cc980-f710-11e9-9c20-01ad4df032ab",`

**Comment by f4ndor** [comment]
thank you, I knew it was something trivial.

**Comment by Kullpoint** [comment]
> Hi @f4ndor,
> 
> This is didn't bug, key setting iframeUrl injecting all page view. You need to change line to work correctly: `"iframeUrl": "/dashboardGroups/ceda14d0-21b4-11ea-9de0-11b867bb66d6/205cc980-f710-11e9-9c20-01ad4df032ab",` to: `"iframeUrl": "/dashboard/205cc980-f710-11e9-9c20-01ad4df032ab",`

I try to do this, but it doesnt work. Conlose say that:

ERROR Error: Uncaught (in promise): n: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":404,"statusText":"OK","url":"http://MYLOCAL/api/dashboard/1234567-2677-11ec-b235-11f89ce87ccd","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://MYLOCAL/api/dashboard/1234567-2677-11ec-b235-11f89ce87ccd: 404 OK","error":{"status":404,"message":"Requested item wasn't found!","errorCode":32,"timestamp":"2021-11-29T15:23:41.050+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}}
    at _ (polyfills.caae856b41bca3d96962.js:1)
    at _ (polyfills.caae856b41bca3d96962.js:1)
    at polyfills.caae856b41bca3d96962.js:1
    at e.invokeTask (polyfills.caae856b41bca3d96962.js:1)
    at Object.onInvokeTask (vendor.260e1d5c0be955c0320c.js:1)
    at e.invokeTask (polyfills.caae856b41bca3d96962.js:1)
    at t.runTask (polyfills.caae856b41bca3d96962.js:1)
    at b (polyfills.caae856b41bca3d96962.js:1)
    at t.invokeTask [as invoke] (polyfills.caae856b41bca3d96962.js:1)
    at p (polyfills.caae856b41bca3d96962.js:1)
