### ISSUE TITLE
[Question] Timewindow selection and Back button

### ISSUE THREAD

**Issue by rdenisyuk** [thingsboard/thingsboard#3795]
**Component**

 * UI
 
**Description**
Timeseries widgets (charts. etc.) allow "zooming" into a certain period by selecting the required time range by a mouse. This feature is extremely helpful for drill-down interaction, however there is no way to get back to the prevoius time window. Hitting the "Back" browser button is a common UI technique expected by users but with Thingsboard it quits the current page.

Is there any way to support the "Go back" functionality for time periods (and for dashboard states as well by the way) using Back browser button or implement this functionality with a dashboard button 

Thank you

**Environment**

  * ThingsBoard: version 3.1.1. PE
 * Browser: Chrome, Edge

**Comment by ChantsovaEkaterina** [comment]
Hello,
As for chart widgets, when "zooming" into a certain period, you can go back to a previous time period by double-click on a widget.
