### ISSUE TITLE
Https Redirect

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#380]
I do not know if there is a particular configuration.
I redirected localhost:8080 to a  DNS https.
The problem is that in https i do not get data.
Thank you 

//Redirect https
![image](https://user-images.githubusercontent.com/6891046/32073215-977056f4-ba95-11e7-823b-9f24edc4b750.png)

//No Redirect https
![image](https://user-images.githubusercontent.com/6891046/32072779-261d589a-ba94-11e7-9b99-ccc27a4ba38a.png)

**Comment by ashvayka** [comment]
This is the issue with websockets. Your redirect probably does not support them

**Comment by gopirathnamt** [comment]
Can u tell me how you enabled the https ?
