### ISSUE TITLE
scheduler initialization with string conversined to number issue

### ISSUE THREAD

**Issue by Boolhwi** [thingsboard/thingsboard#3801]
hi there @vvlladd28 
You said this issue has been fixed in TB 3.1.1, but I'm already using TB 3.1.1 (PE version).
Is that solution worked obviously??

_Originally posted by @Boolhwi in https://github.com/thingsboard/thingsboard/issues/3766#issuecomment-735582640_

**Comment by Ultrazombie** [comment]
Closed due to inactivity
