### ISSUE TITLE
Post Telemetry via MQTT met with [code:5] Connection refused: Not authorised when using  tb-mqtt-transport image 3.2.0

### ISSUE THREAD

**Issue by rlewsley99** [thingsboard/thingsboard#3802]
**Describe the bug**
MQTT telemetry Post requests are being met with code 5 error [not authorised]. This has been caused by something within the new image update for tb-mqtt-transport. Tested with Asyncio_mqtt python package and mosquitto_publish client, both returning the same error. Full error below: 

```
asyncio_mqtt.error.MqttConnectError: [code:5] Connection refused: Not authorised
Future exception was never retrieved
future: <Future finished exception=MqttCodeError('Unexpected disconnect')>
asyncio_mqtt.error.MqttCodeError: [code:5] Unexpected disconnect
```

**Your Server Environment**
  * Cloud deployment of Kubernetes infrastructure comprising of redis, cassandra, postgresql, kafka and zookeeper
  * ThingsBoard Version: V3.0.0
  * Linux Debian 10 Buster

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Debian 10 Buster
* Browser: Chrome
* Version

**Your Device**
Lenovo Thinkpad x260

* Connectivity
  * MQTT
     - Asyncio_MQTT python package used to send telemetry over MQTT
 

**To Reproduce**
-Update tb-mqtt-transport to latest image (3.2.0)

**Expected behavior**
Both mosquitto_pub and asyncio client had been sending with no issues until image was updated. Rollback of image to 3.1.1 fixed issue, unsure of what was causing error code 5, any ideas? Part of commercial project so information is limited but if anything further is needed please let me know.

**Comment by ashvayka** [comment]
Are you updating only transport? All other services are not updated?

**Comment by rlewsley99** [comment]
> Are you updating only transport? All other services are not updated? You need to update the whole cluster for the internal communication between the microservices to work properly. The DB also needs to be updated. Is this CE or PE?

CE, it was only the transport image that updated as others were pinned to a previous stable version, just as we thought this was too. Thank you for your reply though its helpful to know it was a case of needing to update the cluster as a whole, primary purpose from this post was just to point out to others in case they experienced the same issue.

**Comment by ashvayka** [comment]
Ok, I see. We do not recommend to update images partially if you apply a change from 3.x.* to 3.y.*. For the minor updates like 3.x.1 to 3.x.2 it will most likely work (but we also don't recommend doing it).

**Comment by ashvayka** [comment]
We have changed the protobuf structures and added new entities like DeviceProfiles, so the mqtt transport simply can't work without this info.
