### ISSUE TITLE
[Question] Custom timeseries.

### ISSUE THREAD

**Issue by shhishir** [thingsboard/thingsboard#3807]
**Component**

 * UI

**Description**
I am trying to implement a custom Timeseries, where I want to have the min-time constant. Like the starting point of the time series constant and the max-time to be continuous. I have tried :

```
startTime = 1607068800000;
endTime = new Date().getTime(); //currentTime
self.ctx.timewindowFunctions.onUpdateTimewindow(startTime, endTime); 
```
this gives me the time series with the interval data of startTime and endTime. As the endTime is constantly updating with given current time but my timeseries never updates. Unless I double-click on the timeseries manually.

![timeseries](https://user-images.githubusercontent.com/36517158/101149452-3ec64780-361f-11eb-894a-d49776cca671.png)

As seen in the image the 9:00 should be constant, that is fine but 10:30, that should keep updating automatically. 
Any help will be highly appriciated. 
Thanks.

**Environment**

 * ThingsBoard: 3.1.OPE
 * Browser: Google Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
