### ISSUE TITLE
[Question] LwM2M support in Release 3.2

### ISSUE THREAD

**Issue by sanadamin** [thingsboard/thingsboard#3812]
can you please advise if the LwM2M will be supported in the 3.2 version and if there is a timeline for it?

**Comment by ashvayka** [comment]
Hi @sanadamin , we have done a lot of work to make LwM2M support available. However, forced to postpone it till 3.3. I believe it will be available by the end of January 2021.

**Comment by sanadZamin** [comment]
Hello @ashvayka is there any update on the lwm2m release date?
