### ISSUE TITLE
[Question] How to plot an array of data-points (time independent) using a Thingsboard widget

### ISSUE THREAD

**Issue by 21659419** [thingsboard/thingsboard#3813]
**Component**

 * UI

**Description**
When a specific event occurs in the field, an IoT device takes a series of data samples (eg. transient current readings at the moment of a fault). These readings are then published to a Thingsboard instance via the MQTT API.

Is there a way to plot these data-points as a waveform using a Thingsboard widget? The data-points can be published in any format. eg. [221.13, 220.94, 220.75, ...]

I have tried publishing the data as an array of telemetry objects with the 1 second intervals:

eg.
[{
      "values": {"currentSample": 221.13},
      "ts": 1607354360512
   },
   {
      "values": {"currentSample": 220.94},
      "ts": 1607354361512
   },
   {
      "values": {"currentSample": 220.75},
      "ts": 1607354362512
   }, ...
]
The idea is then to plot the waveform as telemetry using the flot widget. The issue is that this waveform will only exist for a short period of time. Is there then a way to visualize this limited telemetry irrespective of the current window time?   

**Environment**

 * OS:  Ubuntu 20.04.1 LTS
 * ThingsBoard: v.3.1.1
 * Browser:  Chrome

**Comment by ahmed-1a** [comment]
Same issue here

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
