### ISSUE TITLE
Devices Aren't Appearing When Added By Integration

### ISSUE THREAD

**Issue by webstermath** [thingsboard/thingsboard#3814]
We are currently using an AWS IOT Integration.  When the integration automatically provisions a device, the device is not added to the device panel but instead only appears in the relations tab of the integration.  If I try to add the device manually in the device section, I get the error "Device with such name already exists!".  Is this a bug or am I missing something?

**Comment by seanofahey** [comment]
I am experiencing the same with devices that have been created using the HTTP Integration on thingsboard.cloud.  The devices are listed as expected in the Integrations/Relations tab with the relation "ManagedByIntegration" but none of the devices are shown in the Device Groups/All entity group.  Is there an additional step required to make the devices appear?

**Comment by rivardjm** [comment]
Any update on this? It has been quite a while and it would be nice if there was a workaround or if we are missing something.

**Comment by v2sumac** [comment]
> Hi @seanofahey , @webstermath , just checking if this is related to the output of the converter. Most probable cause is that it is assigned to some customer (Customer A, by default) and you can find the device in the Customer Hierarchy. Please confirm that this is not the case here.

Seriously Awesome, I found under Customer A and changed the owner. Thank You Dude!
