### ISSUE TITLE
[Question] When will Lwm2m release?

### ISSUE THREAD

**Issue by zhangxianwei2015** [thingsboard/thingsboard#3816]
**Component**

 * Generic

**Description**
Hi, 
In roadmap 3.2 will support lwm2m protocol, may I knwo when will 3.2 release with lwm2m?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by zhangxianwei2015** [comment]
@nickAS21

**Comment by ashvayka** [comment]
Hi @zhangxianwei2015 , we have done a lot of work to make LwM2M support available. However, forced to postpone it till 3.3. I believe it will be available by the end of January 2021.

**Comment by zhangxianwei2015** [comment]
Hi,
Seems there is no progress in git branch lwm2m.
Will it still be available in the end of January 2021? or a reschedule?

brs

**Comment by JavierNR** [comment]
I'm too interested on lwm2m support.
@zhangxianwei2015 I've believe thingsboard team are working on lwm2m support, see: #3840

Thanks to thingsboard team for all efforts ;)

**Comment by zhangxianwei2015** [comment]
@JavierNR 
After the code revert, there has been 2 months without any update in branch lwm2m.
I am really appreciate to the thingsboard team :), and I am also looking forward to the lwm2m support:)
