### ISSUE TITLE
[Question] local UI doesn't reflect API updates

### ISSUE THREAD

**Issue by stevenmettler** [thingsboard/thingsboard#3819]
**Component**
 * UI

**Description**
I am new with thingsboard and have installed it on Docker. I am hitting the API to post telemetry and attributes, and getting 200 OK when I POST. When I look at the device I am providing the token for, I do not see telemetry or attribute data updated in the UI. However, when I GET the attributes, I can see the values updated being sent from the API.

**Environment**

 * OS:  OS X but running on Docker
 * ThingsBoard: latest CE
 * Browser: Chrome 87

Postman requesting attributes:
<img width="1122" alt="Screen Shot 2020-12-08 at 12 51 40 PM" src="https://user-images.githubusercontent.com/10799094/101521654-1fe3f000-3954-11eb-92f4-8766d6dba5ef.png">

Thingsboard UI of same device:
![Screen Shot 2020-12-08 at 12 52 40 PM](https://user-images.githubusercontent.com/10799094/101521780-443fcc80-3954-11eb-8cd7-75bcd3445944.png)

**Comment by ashvayka** [comment]
Hi @stevenmettler . You are using GET instead of POST request. Also, please make sure that when you hit "Send" the response code is 200 or 204.
