### ISSUE TITLE
Entities and relations (question)

### ISSUE THREAD

**Issue by ghjklgv9** [thingsboard/thingsboard#382]
hi0 hi ! I set Assets by Documentation,but can't be use for my part

this my setted photo

![1509352479881](https://user-images.githubusercontent.com/22571265/32161428-845845fa-bd23-11e7-971b-f2173fa81162.jpg
![1509352533661](https://user-images.githubusercontent.com/22571265/32161467-9dcc6570-bd23-11e7-9431-dec2019d8ad1.jpg)
![1509352549993](https://user-images.githubusercontent.com/22571265/32161471-a0e95f7e-bd23-11e7-9eaa-3d4bea966b93.jpg)
![1509352509155](https://user-images.githubusercontent.com/22571265/32161454-988c3144-bd23-11e7-8079-9b07d4c21e8e.jpg)
)
![1509352777390](https://user-images.githubusercontent.com/22571265/32161554-025838ac-bd24-11e7-81bf-4ac193b424ed.jpg)

thanks!!

**Comment by vparomskiy** [comment]
Close this thread since it is not active anymore.
