### ISSUE TITLE
[Bug] Missing New Columns in CassandraTsDatabaseUpgradeService

### ISSUE THREAD

**Issue by lc2a** [thingsboard/thingsboard#3830]
Upgrade Failed from 2.4.3 -> 3.0 due to migration from Cassandra to PostgreSQL

Missing below Add new Columns in thingsboard/application/src/main/java/org/thingsboard/server/service/install/CassandraTsDatabaseUpgradeService.java

```
alter table thingsboard.attributes_kv_cf add json_v text;
alter table thingsboard.tenant add isolated_tb_core boolean;
alter table thingsboard.tenant add isolated_tb_rule_engine boolean;
```

**Comment by den1jkee** [comment]
Greetings,
Thank you for your feedback. We are always improving our project and have already fixed this bug since the 2.5.3 version of ThingsBoard.

Best regards,
ThingsBoard Team.
