### ISSUE TITLE
[Question] toLocaleString() does not work in the script function

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#3837]
**Component**

 * Rule Engine

**Description**
According to the instruction of this [link](https://thingsboard.io/docs/user-guide/install/pe/aws-marketplace/), I have successfully deployed TB.

However, when I tried to use the same code (.toLocaleString() with timeZone) in the script function, I found that the code did not work on the aws side (but it worked on cloud.thingsboard.io).
How to configure so that I can use this JavaScript?

**cloud.thingsboard.io**
![螢幕快照 2020-12-11 上午11 14 44](https://user-images.githubusercontent.com/63713926/101857496-95450000-3ba2-11eb-9541-264612afb88b.png)

**aws**
![螢幕快照 2020-12-11 上午11 14 54](https://user-images.githubusercontent.com/63713926/101857550-b6a5ec00-3ba2-11eb-8aa0-6b33f00815fe.png)

**Environment**

 * ThingsBoard: 3.2

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use some ES6 features in the rule nodes only if your TB instance is running in microservice mode. If no, in the better case your code will be working as if some code fragment doesn't exist, in the worse case you receive an error.
One possible alternative for you to cope with the described case is to manually compose the date in a required format, i.e. separately get hours, minutes, and seconds, convert the hours according to the needed timezone and then combine all this into a string.
