### ISSUE TITLE
Subscription object

### ISSUE THREAD

**Issue by sdfantasy** [thingsboard/thingsboard#384]
we don't want to enable the dashboard's edit mode for the end user.
But our device have 100+ keys,we want the user to select the keys to show in a chart by checkbox.
like this :
![image](https://user-images.githubusercontent.com/13897059/32214910-4d7fd6e0-be5b-11e7-89c9-be11c52b4140.png)

Is there have any other method to change the dataKeys in a Subscription object?

**Comment by ashvayka** [comment]
Yes, you can do this programmatically and store the configuration in customer attributes

**Comment by sdfantasy** [comment]
Can you help to give a simple demo? Thanks!

**Comment by vparomskiy** [comment]
For the current moment, it is not possible with standard widgets. You will need to implement custom widget to support this or group telemetry keys and create different dashboard states for different groups

**Comment by alexsmartens** [comment]
@ashvayka, @vparomskiy,
I'm willing to develop a custom widget to be able to change dataKeys based on the datasource attributes. Can you please elaborate on how to get attributes input inside a timeserious widget(#1737)?

**Comment by Karabiy** [comment]
you may refer to the widget development guide of ours for those reasons: https://thingsboard.io/docs/user-guide/contribution/widgets-development/
