### ISSUE TITLE
[Bug] Thingsboard CE Upgrade v3.0.1 to v3.0.0 fails

### ISSUE THREAD

**Issue by ahmed-1a** [thingsboard/thingsboard#3843]
I thought of writing this if anyone else facing the same issue. 

I had Thingsboard CE v3.0.1 running on Google VM instance 1 vCPU 2.75 GB memory. 
The upgrade script failed on updating table event. 

The way I solved this is by upgrading the spec. of the instance to 4 vCPUs, 16 GB memory. The upgrade took some time at the same point but worked without a problem. Make sure to backup the disk before attempting the upgrade.

At the end, I downgraded the spec to that of the original one. Thingsboard works now. 
Another way is to create a new instance with high spec for upgrading. Then, you can always replace the disk to run the upgraded thingsboard.  

I have a question, how to keep the data sent by the devices during the time taken to upgrade?
Does this have to depend on the devices by saving the data, or can this be solved in the server backend?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
