### ISSUE TITLE
ThingsBoard Create Device with custom Access token

### ISSUE THREAD

**Issue by mm-1994** [thingsboard/thingsboard#3848]
**_### hi all

i would like to create new device from admin device widget and change its access token while creation.
code i am using_**

let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

openAddDeviceDialog();

function openAddDeviceDialog() {
    customDialog.customDialog(htmlTemplate, AddDeviceDialogController).subscribe();
}

function AddDeviceDialogController(instance) {
    let vm = instance;
    
    vm.addDeviceFormGroup = vm.fb.group({
      deviceName: ['', [vm.validators.required]],
      deviceType: ['', [vm.validators.required]],
      deviceLabel: [''],
      attributes: vm.fb.group({
          latitude: [null],
          longitude: [null]
      })      
    });
    
    vm.cancel = function() {
        vm.dialogRef.close(null);
    };
    
    vm.save = function() {
        vm.addDeviceFormGroup.markAsPristine();
        let device = {
            name: vm.addDeviceFormGroup.get('deviceName').value,
            type: vm.addDeviceFormGroup.get('deviceType').value,
            label: vm.addDeviceFormGroup.get('deviceLabel').value
        };
        let device2 = {
            createdTime: 0,
            credentialsId: "string",
            credentialsType: "ACCESS_TOKEN",
            credentialsValue: "123",
            id:"string"
            
            
        };
        deviceService.saveDevice(device).subscribe(
            function (device) {
                saveAttributes(device.id).subscribe(
                    function () {
                        widgetContext.updateAliases();
                        vm.dialogRef.close(null);
                    }
                );
            }
        );
       deviceService.saveDeviceCredentials(device2).subscribe();
        
           
    }
    function saveAttributes(entityId) {
        let attributes = vm.addDeviceFormGroup.get('attributes').value;
        let attributesArray = [];
        for (let key in attributes) {
            attributesArray.push({key: key, value: attributes[key]});
        }
        if (attributesArray.length > 0) {
            return attributeService.saveEntityAttributes(entityId, "SERVER_SCOPE", attributesArray);
        } else {
            return widgetContext.rxjs.of([]);
        }
    }
}

**Comment by vvlladd28** [comment]
Hi @mm-1994,

You need to change the device save function:
```
vm.save = function() {
    vm.addDeviceFormGroup.markAsPristine();
    let device = {
        name: vm.addDeviceFormGroup.get('deviceName').value,
        type: vm.addDeviceFormGroup.get('deviceType').value,
        label: vm.addDeviceFormGroup.get('deviceLabel').value
    };
    widgetContext.http.post('/api/device/credentials?accessToken=123', device).subscribe(
        function (device) {
            saveAttributes(device.id).subscribe(
                function () {
                    widgetContext.updateAliases();
                    vm.dialogRef.close(null);
                }
            );
        }
    );
}
```

**Comment by mm-1994** [comment]
Hi @vvlladd28 
thanks so much for your help and quick response.
i tried your code but when i create the device an error "incorrect deviceId null"
here is my code

`let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

openAddDeviceDialog();

function openAddDeviceDialog() {
    customDialog.customDialog(htmlTemplate, AddDeviceDialogController).subscribe();
}

function AddDeviceDialogController(instance) {
    let vm = instance;
    
    vm.addDeviceFormGroup = vm.fb.group({
      deviceName: ['', [vm.validators.required]],
      deviceType: ['', [vm.validators.required]],
      deviceLabel: [''],
      attributes: vm.fb.group({
          latitude: [null],
          longitude: [null]
      })      
    });
    
    vm.cancel = function() {
        vm.dialogRef.close(null);
    };
    
    vm.save = function() {
        vm.addDeviceFormGroup.markAsPristine();
        let device = {
            name: vm.addDeviceFormGroup.get('deviceName').value,
            type: vm.addDeviceFormGroup.get('deviceType').value,
            label: vm.addDeviceFormGroup.get('deviceLabel').value
        };
        widgetContext.http.post('/api/device/credentials?accessToken=123', device).subscribe(
            function (device) {
                saveAttributes(device.id).subscribe(
                    function () {
                        widgetContext.updateAliases();
                        vm.dialogRef.close(null);
                    }
                );
            }
        );
    };
    
    function saveAttributes(entityId) {
        let attributes = vm.addDeviceFormGroup.get('attributes').value;
        let attributesArray = [];
        for (let key in attributes) {
            attributesArray.push({key: key, value: attributes[key]});
        }
        if (attributesArray.length > 0) {
            return attributeService.saveEntityAttributes(entityId, "SERVER_SCOPE", attributesArray);
        } else {
            return widgetContext.rxjs.of([]);
        }
    }
}`

**Comment by vvlladd28** [comment]
Hi @mm-1994,
I had mistaken in URL API, this correct code:
```
 widgetContext.http.post('/api/device?accessToken=123', device).subscribe(
        function (device) {
            saveAttributes(device.id).subscribe(
                function () {
                    widgetContext.updateAliases();
                    vm.dialogRef.close(null);
                }
            );
        }
    );
```

**Comment by mm-1994** [comment]
@vvlladd28 
thank you so much really helped alot

**Comment by mm-1994** [comment]
Done
