### ISSUE TITLE
[Bug] deviceType null in dsData structure

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#3850]
I have defined a new Device with a "testdevice" profile
I have defined a new dashboard with a map widget
The problem I found is the following: the deviceType property in the dsData structure (label function) is always null (see screenshot attached)

**Server**
* Server OS: linux debian 9
* Docker version 20.10.0, build 7287ab3
* ThingsBoard v.3.2.0 CE (docker container)
 
**Desktop**
* Client OS: ubuntu 20.04
* Browser chrome (brave)
* Version 1.17.75 Chromium: 87.0.4280.88 (64 bit)

**Steps to reproduce the behavior:**
1. Define a new Device with a specific profile "testdevice"
2. Goto dashboard and define a new alias
3. Define a new dashboard adding a map widget
4. Configure the new map widget
5. add console.log line in the label function in order to print the dsData structure

**Expected behavior**
The deviceType should be equal to "testdevice"

**Screenshots**
![Schermata da 2020-12-15 20-25-24](https://user-images.githubusercontent.com/9846064/102263431-95336000-3f14-11eb-87a4-dbe6874ccab8.png)

**Comment by ChantsovaEkaterina** [comment]
Hello, @shaphiro 
Please, make sure that the _type_ entity field is added as datasource key. If so, try to get it in the following way:
_dsData[dsIndex][typeKeyLabel]_.

**Comment by shaphiro** [comment]
I added the "type" entity field (it was not added).

Now I can take the value with:
`var deviceType = dsData[dsIndex]['Type'];`

Thanks!!
