### ISSUE TITLE
Problems with Installing TB using Docker (Ubuntu 20.04)

### ISSUE THREAD

**Issue by BaerSy** [thingsboard/thingsboard#3851]
I did install early TB version using Docker under Ubuntu, and I had no problem.  I tried to install latest TB under Ubuntu recently and never succeeded. I checked issue #3347  and followed the recommendations from @CooL16 and got some progress, but still have issues as below. Appreciated any advice.

postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2020-12-15 20:23:39.505 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-12-15 20:23:39.505 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-12-15 20:23:39.511 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-15 20:23:39.526 UTC [26] LOG:  database system was shut down at 2020-12-15 20:04:01 UTC
postgres_1  | 2020-12-15 20:23:39.532 UTC [1] LOG:  database system is ready to accept connections
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
 

Docker-compose.yml:

_version: '2.2'
services:
  mytbpe:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
           - "8080:8080"
           - "1883:1883"
           - "5683:5683/udp"
    environment:
           TB_QUEUE_TYPE: in-memory
           SPRING_DATASOURCE_USERNAME: postgres
           SPRING_DATASOURCE_PASSWORD: postgres
           SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
    volumes:
           - ~/.mytb-data:/data
           - ~/.mytb-logs:/var/log/thingsboard
  postgres:
          restart: always
          image: "postgres:11.6"
          ports:
           - "5432"
          environment:
              POSTGRES_DB: thingsboard
              POSTGRES_PASSWORD: postgres
    volumes:
           - ~/.mytb-data/db:/var/lib/postgresql/data_

**Comment by trikimiki** [comment]
Hello,

Can you provide some more information? What guide you were using and on which step that error occurred? And what you actually did differently from that guide?

Also, try checking your running containers - maybe Postgres isn't running?:
`$ docker ps | grep postgres`

**Comment by BaerSy** [comment]
@trikimiki after run "docker ps | grep postgres", i got nothing....
Even run "sudo docker ps ", i can't see any container too :)
I will give more details for my case.
(0) I followed the guide "https://thingsboard.io/docs/user-guide/install/docker/"
(1) When I apply docker-compose.yml as below, I got a permission denied to create data/db, then I read #3347, and changed  docker-compose.yml to below:

version: '2.2'
services:
  mytbpe:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
  postgres:
    restart: always
    image: "postgres:11.6"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/.mytb-data/db:/var/lib/postgresql/data


Then i got the problem:

edge@edge-VirtualBox:~$ sudo docker-compose up
Creating edge_postgres_1 ... done
Creating edge_mytbpe_1   ... done
Attaching to edge_mytbpe_1, edge_postgres_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
postgres_1  | 2020-12-17 01:28:20.655 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-12-17 01:28:20.655 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-12-17 01:28:20.662 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-17 01:28:20.812 UTC [23] LOG:  database system was shut down at 2020-12-16 21:52:29 UTC
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
postgres_1  | 2020-12-17 01:28:21.070 UTC [1] LOG:  database system is ready to accept connections
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
mytbpe_1    | psql: could not connect to server: No such file or directory
mytbpe_1    | 	Is the server running locally and accepting
mytbpe_1    | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by trikimiki** [comment]
So, as I see in your compose file, you are pulling both:
```
mytbpe:
  image: "thingsboard/tb-postgres"
```
and
```
postgres:
  image: "postgres:11.6"
```

That image of TB comes with preinstalled and preconfigured PostgreSQL. And additionally, you are pulling another PostgreSQL image. It might have worked that time, but the newer version of TB may have conflicts with this setup right now:
```
postgres_1 | PostgreSQL Database directory appears to contain a database; Skipping initialization
```

Also, your TB service is called "mytbpe", but your data and log directories called "mytb-data" and "mytb-logs" - that could be an issue too. 

I suggest renaming the service name and trying to `docker-compose up` again first.

If it won't work - can you please tell me where installation failed for you before you were trying to use a custom compose file?

**Comment by BaerSy** [comment]
Thanks @trikimiki, follow your advice, I reinstall TB using the guide ""https://thingsboard.io/docs/user-guide/install/docker/".  I removed all containers and images and install it from scratch.  
(1) docker-compose.yml 

version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard

(2) After run "docker-compose pull", the docker image created:
edge@edge-VirtualBox:~$ sudo docker images
REPOSITORY                 TAG     IMAGE ID            CREATED             SIZE
thingsboard/tb-postgres   latest              8e5197354159        2 weeks ago         1.35GB
(3) After run "docker-compose up", i got the following errors:
edge@edge-VirtualBox:~$ sudo docker-compose up
Starting edge_mytb_1 ... done
Attaching to edge_mytb_1
mytb_1  | psql: could not connect to server: No such file or directory
mytb_1  | 	Is the server running locally and accepting
mytb_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
mytb_1  | psql: could not connect to server: No such file or directory
mytb_1  | 	Is the server running locally and accepting
mytb_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Can't understood why it connected to another postgresal instance?

**Comment by trikimiki** [comment]
Your TB should be running at [127.0.0.1:8080](url) if you used default settings.

**Comment by BaerSy** [comment]
I used default setting for sure, I tried http://127.0.0.1:8080  and the results:

The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by BaerSy** [comment]
Very strange thing here:

I have 2 virtual machine - ubuntu 18.04  (6 months ago) and ubuntu 20.04(now).  

(1) First one is old version of TB works very well.

ae485368656c   thingsboard/tb-postgres   "start-tb.sh"       5 months ago        Up 5 minutes        0.0.0.0:1883->1883/tcp, 0.0.0.0:5683->5683/udp, 0.0.0.0:9090->9090/tcp   mytb

I can  start TB from inside VM and ouside VM without any problem.

(2) Second one is latest one. I could make it work.  Few issues:
(a) I can't apply "docker-compose up" after "Docker-compose pull".  I can only apply "Docker-compose start". 
(b) I can't access to 127.0.0.1:8080 inside VM and 192.168.1.222:8080 outside VM.

Any advice?
Thanks

**Comment by BaerSy** [comment]
@trikimiki I created a brand new VM with 20.04 and followed "https://thingsboard.io/docs/user-guide/install/docker/" again.  The interesting thing is that I got other errors after run "docker-compose up"...

edge@edge-VirtualBox:~$ sudo docker-compose pull
Pulling mytb ... done
edge@edge-VirtualBox:~$ sudo docker-compose up
Creating network "edge_default" with the default driver
Creating edge_mytb_1 ... done
Attaching to edge_mytb_1
mytb_1  | mkdir: cannot create directory ‘/data/db’: Permission denied
mytb_1  | The files belonging to this database system will be owned by user "thingsboard".
mytb_1  | This user must also own the server process.
mytb_1  | 
mytb_1  | The database cluster will be initialized with locale "C.UTF-8".
mytb_1  | The default database encoding has accordingly been set to "UTF8".
mytb_1  | The default text search configuration will be set to "english".
mytb_1  | 
mytb_1  | Data page checksums are disabled.
mytb_1  | 
mytb_1  | creating directory /data/db ... initdb: could not create directory "/data/db": Permission denied
mytb_1  | pg_ctl: database system initialization failed
mytb_1  | psql: could not connect to server: No such file or directory
mytb_1  | 	Is the server running locally and accepting
mytb_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
mytb_1  | psql: could not connect to server: No such file or directory
mytb_1  | 	Is the server running locally and accepting
mytb_1  | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by CooL16** [comment]
@BaerSy have you executed these commands?
```
mkdir -p ~/.mytbpe-data && sudo chown -R 799:799 ~/.mytbpe-data
mkdir -p ~/.mytbpe-logs && sudo chown -R 799:799 ~/.mytbpe-logs
```

**Comment by BaerSy** [comment]
Yes, @CooL16, see below. I exactly follow the installation guide

drwxrwxr-x  2  799  799 4096 Dec 18 13:34 .mytb-data
drwxrwxr-x  2  799  799 4096 Dec 18 13:34 .mytb-logs

**Comment by CooL16** [comment]
Please execute this command it might resolve your issue: sudo chmod -R 777 ~/.mytb-data

**Comment by BaerSy** [comment]
I just did as you siad. The results are same

edge@edge-VirtualBox:~$ sudo chmod -R 777 ~/.mytb-data
edge@edge-VirtualBox:~$ sudo docker-compose up
Starting edge_mytb_1 ... done
Attaching to edge_mytb_1
mytb_1  | mkdir: cannot create directory ‘/data/db’: Permission denied
mytb_1  | The files belonging to this database system will be owned by user "thingsboard".
mytb_1  | This user must also own the server process.
mytb_1  | 
mytb_1  | The database cluster will be initialized with locale "C.UTF-8".
mytb_1  | The default database encoding has accordingly been set to "UTF8".
mytb_1  | The default text search configuration will be set to "english".
mytb_1  | 
mytb_1  | Data page checksums are disabled.
mytb_1  |

**Comment by zopha** [comment]
I was following the same guide @BaerSy was and getting the same errors. Following some advise here I've removed the postgres image and created directories using
`mkdir -p ~/.mytb-data && sudo chmod -R 777 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chmod -R 777 ~/.mytb-logs`

so now I have this as my compose file

`  mytb:
    restart: always
    container_name: thingsboard
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
`

It's getting further but I'm getting a load of errors like

`2020-12-22 15:44:18,635 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 08001
2020-12-22 15:44:18,635 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - The connection attempt failed.
2020-12-22 15:44:18,724 [main] ERROR o.s.b.w.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'oauth2AuthenticationSuccessHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'oauth2AuthenticationSuccessHandler' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultSystemSecurityService': Unsatisfied dependency expressed through field 'mailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
2020-12-22 15:44:18,778 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2020-12-22 15:44:18,784 [main] WARN  o.a.c.loader.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [sql-queue-0-ts-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
 org.thingsboard.server.dao.sql.TbSqlBlockingQueue.lambda$init$2(TbSqlBlockingQueue.java:61)
 org.thingsboard.server.dao.sql.TbSqlBlockingQueue$$Lambda$897/245386411.run(Unknown Source)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
`
And a good bit more, which just leads to.

`waiting for server to shut down.... done
server stopped
Starting ThingsBoard ...
`

This is just using the container on it's own and following the guides on thingsboard.io (https://thingsboard.io/docs/user-guide/install/docker/) and some suggestions here. I've tried this on a fresh Ubuntu and Debian installs, no idea if I'm missing anything.

**Comment by BaerSy** [comment]
@zopha   I also repeated few times with same results. 
Old version works well.

**Comment by zopha** [comment]
> @zopha I also repeated few times with same results.
> Old version works well.

What version is the old one using? I'd like to give it a try and see if that works for me.

**Comment by BaerSy** [comment]
1.x or 2.x

**Comment by CooL16** [comment]
@BaerSy please provide us with output of: ls -la on the mytb directory

**Comment by Dewald928** [comment]
Same issue here. Any progress?

**Comment by scutcz** [comment]
> Same issue here. Any progress?

sudo chmod -R 777 ~/.mytb-data
sudo chmod -R 777 ~/.mytb-logs

Executed these commands got it fixed to me.

**Comment by Dewald928** [comment]
For some reason running:

```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
docker run -it -p 8080:9090 -p 1883:1883 -p 5683:5683/udp -v ~/.mytb-data:/data \
-v ~/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-postgres
```

works fine.

**Comment by BaerSy** [comment]
@woland7 I tried your docker-compose.yml.  

With your yml file, I can run "docker-compose start" without any problem.  Buy when I run "docker-compose up" I got :

 
![compose-up](https://user-images.githubusercontent.com/27965673/109435189-42cbf080-79e7-11eb-92ae-e840b6b41c57.PNG)

**Comment by badril1978** [comment]
Hi anmobor,

Could you elaborate on this:

"Inside the ~/.mytb-data/db:/var/lib/postgresql/data you have to do the next:
chown -R postgres ~/.mytbpe-data/db"

Did you mean inside the "~/.mytb-data/db" directory?
I tried chown but I get "invalid user: postgres".

**Comment by anmobor** [comment]
Hi badril1978,
db is a folder with all the database stuff.

firts:
mkdir -p ~/.mytbpe-data 
sudo chown -R 799:799 ~/.mytbpe-data mkdir -p ~/.mytbpe-logs 
sudo chown -R 799:799 ~/.mytbpe-logs

--> for you: chown -R thingsboard /volumes/thingsboard_CE/mytbpe-data/db"

if you have the user for the database thingsboard do the same but instead of changing the owner to postgres to thingsboard

My version:
I used docker compose and I defined there the user postgres for the data base. I paste here my docker compose and follow the guide in the thingsboard docker in linux, at the end do chown -R postgres ~/.mytbpe-data/db" or in the directory you have /db. Also maybe you'll have to change the ports because I changed them because of my needs: 

chown -R postgres /volumes/thingsboard_CE/mytbpe-data/db"

My docker compose:
version: '2'
services:

  nginx:
    image: nginx
    ports:
      - "8166:80"
      - "8088:8088"
    links:
      - mytbpe  # will use this one here
    volumes:
      - /volumes/thingsboard_CE/nginx/conf.d:/etc/nginx/conf.d

#    networks:
#      - docker_network
  mytbpe:
    restart: unless-stopped
    image: "store/thingsboard/tb-pe:3.2.2PE"
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
#      TB_LICENSE_SECRET: yourlincense if you use PE
#     TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
    volumes:
      - /volumes/thingsboard_CE/mytbpe-data:/data
      - /volumes/thingsboard_CE/mytbpe-logs:/var/log/thingsboard
    links: 
      - postgres
     
    depends_on:
      - postgres
#    networks:
#      - docker_network
  postgres:
    restart: unless-stopped
    image: "postgres:12"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - /volumes/thingsboard_CE/mytbpe-data/db:/var/lib/postgresql/data

**Comment by badril1978** [comment]
Hi anmobor,

Thanks for pointing me in the right direction. Finally got it to work. In my situation, there were several issued that needed to be addressed.

1. The Thingsboard CE installation using Docker guide is incomplete as mentioned [here](https://githubmemory.com/repo/thingsboard/thingsboard.github.io/issues). It is included in the Thingsboard PE version thought. Having followed the instructions from the thingsboard website. I came across the second issue.

2. The mytb_1 container and postgres_1 container couldn't communicate. 
I had the same problem as @BaerSy: 
mytb_1 | Is the server running locally and accepting
mytb_1 | connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
postgres_1 | 2020-12-17 01:28:21.070 UTC [1] LOG: database system is ready to accept connections
mytb_1 | psql: could not connect to server: No such file or directory

So, I followed @woland7  suggestions adding an extra volume (mine was defined '.my') to share between mytb_1 and postgres_1 container. That brought me further, but came across the third issue. 

3. Thinsgboard user doesn't exist. I had the same problem as @BaerSy:
![image](https://user-images.githubusercontent.com/45901907/120886673-aa668d00-c621-11eb-9208-d90c537ad917.png)

After reading in the the postgres docker documentation, I added a "POSTGRES_USER: thingsboard" in my docker-compose.yml file. This seemed to solve this issue, but gave rise to another issue. 

4. Thingsboard database was created twice, first by the mytb_1 container, and second by the postgres_1 container. This results in the following error message while installing:

mytb_1       | ERROR:  database "thingsboard" already exists
mytb_1       | ERROR:  database "thingsboard" already exists
postgres_1   | 2021-06-05 09:50:28.919 UTC [85] ERROR:  database "thingsboard" already exists
postgres_1   | 2021-06-05 09:50:28.919 UTC [85] STATEMENT:  CREATE DATABASE thingsboard

Since I defined a user in the postgres container "POSTGRES_USER: thingsboard", this automatically creates a database of the same name as the user namely "thingboard. The mytb_1 container on the other hand implicitly creates a "thingsboard" database when it does its installation. Since postgres is installed first, the mytb_1 container sees that a database has been created and produces the above error. The workaround was to define a "dummy" database and assign it to "POSTGRES_USER: thingsboard" in the postgres_1 container in my docker-compose.yml file.  This solved this problem, but gave a rise to yet another issue. 

5.  When mytb_1 wanted to communicate with the postgres_1 container, the following error occured:

postgres_1   | 2021-06-05 10:13:17.174 UTC [86] FATAL:  password authentication failed for user "postgres"
postgres_1   | 2021-06-05 10:13:17.174 UTC [86] DETAIL:  Role "postgres" does not exist.

This stems from defining "postgres" as the user in the mytb_1 container through the docker-compose.yml script. So I changed the user to "thingsboard". Finally it works. Below are my system details and docker-compose.yml file.

My system details are:
Ubuntu 20.04 running on VMWare
Thingsboard CE installation in Ubuntu 20.04 with Kafka as queue service.

docker-compose.yml

version: '2.2'
services:
  zookeeper:
     restart: always
     image: "zookeeper:3.5"
     ports:
       - "2181:2181"
     environment:
       ZOO_MY_ID: 1
       ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
  kafka:
    restart: always
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mytb:
    restart: unless-stopped
    image: "thingsboard/tb-postgres"
    expose:
      - "8080"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: thingsboard


     volumes:
       - /home/bard/thingsboard/.my-data:/data
       - /home/bard/thingsboard/.my-logs:/var/log/thingsboard
       - /home/bard/thingsboard/.my:/var/run/postgresql
     
     depends_on:
       - postgres
       - kafka

  postgres:
    restart: unless-stopped
    image: "postgres"
    ports:
        - "5432"
    environment:
      POSTGRES_USER: thingsboard
      POSTGRES_DB: dummmy
      POSTGRES_PASSWORD: postgres

    volumes:
      - /home/bard/thingsboard/.my-data/db:/var/lib/postgresql/data
      - /home/bard/thingsboard/.my:/var/run/postgresql

**Comment by BaerSy** [comment]
We have not resolved it since end of last year. We thought it was CE problem.  Then We just purchase PE and we got the same problems,  Wondering why the paid edition also has the problem and the issue last almost half year, no any update in installation procedure.  I am reading the above answers and tried to find out a solution.  In the meat time, can someone tell me whether PE has the same community support as CE.  I will update you once I successes  in installation.

**Comment by badril1978** [comment]
> We have not resolved it since end of last year. We thought it was CE problem. Then We just purchase PE and we got the same problems, Wondering why the paid edition also has the problem and the issue last almost half year, no any update in installation procedure. I am reading the above answers and tried to find out a solution. In the meat time, can someone tell me whether PE has the same community support as CE. I will update you once I successes in installation.

No, it's not a CE problem.. I think it's just a "no one bothered to update the thingsboard installation procedure" problem. I installed the CE version, but I had to look piece together advice from this thread and look around in the internet to sort it out. Hope it works out well for you @BaerSy .

**Comment by BaerSy** [comment]
@badril1978 thanks. i did some progress, but had a problem with initializing license client.
@anmobor i saw you are using PE, believe you are using license too. have you met this problem? 
mytbpe_1    | 2021-06-08 13:24:41,977 [main] INFO  o.t.license.client.TbLicenseClient - Initializing ThingsBoard License Client, Release Date [2021-03-24]
mytbpe_1    | 2021-06-08 13:24:43,304 [main] ERROR o.t.license.client.TbLicenseClient - License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!
mytbpe_1    | 2021-06-08 13:24:43,307 [main] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
mytbpe_1    | 2021-06-08 13:24:43,310 [main] ERROR o.t.s.d.s.BasicSubscriptionService - Failed to init license client
mytbpe_1    | org.thingsboard.license.shared.exception.LicenseException: Active instances capacity exceeded!
mytbpe_1    | 	at org.thingsboard.license.shared.exception.LicenseErrorResponse.toLicenseException(LicenseErrorResponse.java:69)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.toLicenseException(TbLicenseClient.java:393)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.activateInstance(TbLicenseClient.java:331)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.readInstanceDataOrActivate(TbLicenseClient.java:316)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.init(TbLicenseClient.java:171)
mytbpe_1    | 	at org.thingsboard.server.dao.subscription.BasicSubscriptionService.init(BasicSubscriptionService.java:100)
mytbpe_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mytbpe_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mytbpe_1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytbpe_1    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by anmobor** [comment]
@BaerSy 

In the docker-compose you have to have this two lines:
TB_LICENSE_SECRET: PUT_YOUR_LICENSE_SECRET_HERE
TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data

And then
You have to:
stop and remove the container, not start again 
go to the Thingsboard license portal 
deactivate the INSTACE, not the license and leave it so, 
and then start again the docker creating a new container,
it will activate automatically another instance to the new container

**Comment by BaerSy** [comment]
@anmobor thanks very much. it works.
