### ISSUE TITLE
Thingsboard Dashboard Card with color change from red to green

### ISSUE THREAD

**Issue by RAULXXX** [thingsboard/thingsboard#3853]
Hi everyone,

I would like to have a card widget with the possiblity of change the backgound color in order to view if the device is in the right state or not (from green to red e.g.). 

I can send a variable from the device and i recieve this variable correctly in the telemetry.

In this picture we see the card i would to change the color, it doesnt matter the value of the temperature i only want to show the letter "L20 ABB" and the background color 

Thank you for any clue

**Comment by RAULXXX** [comment]
I have an idea to solve that problem, on a digital gauge with a linear bar (min 0 and max 100)  i use red color from 0 to 99 and green from 100 to 200 then i send 99 if i want red or 110 if a i want green. 

Anybody knows a better way to do it? and if for example i dont want to use the linear bar and only change the color of the letters?

![ee](https://user-images.githubusercontent.com/70969190/102458810-112cc580-4045-11eb-9722-bca033b180cf.PNG)

**Comment by kalutkaz** [comment]
Hi, 
You can create telemetry "color" with the color you need and pass it to the "Value Card" widget and then change the background from HTML for example  " style =' background: $ {color} ' ".

Here is an example widget
[value_card_example.zip](https://github.com/thingsboard/thingsboard/files/5765695/value_card_example.zip)

**Comment by adwait009** [comment]
I tried to import this card in widget library but it is giving me this error. Unable to import widgets bundle: Invalid widgets bundle data structure. What do i need to change in this to make it work for me.
