### ISSUE TITLE
More than one file was found with OS independent path 'google/protobuf/duration.proto'. in REST client 3.2.0[Bug] 

### ISSUE THREAD

**Issue by androidEl** [thingsboard/thingsboard#3854]
**Describe the bug**
i found an error with new version of java REST Client. when i build my apps display an error 'More than one file was found with OS independent path 'google/protobuf/duration.proto'.'

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
