### ISSUE TITLE
how to best run Thingsboard DockerCompsoe Cluster on AWS?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3857]
Hi Guys

for a small size deployment, 500-1000 devices sending messages every 5 minutes.

I would like to use DockerCompose on EC2 in AWS and RDS for DB.

Testing with ThingsBoard CE:

From my experiment I needed a t3.xlarge machine to run the Cluster with Docker Compose. I disabled all the db related images.

Still the deployment required the xlarge. 

How do you recommend to tweak the resources so that it can run on a large instance?

Kindly

**Comment by pon0marev** [comment]
If you are deploying a [microservice docker](https://github.com/thingsboard/thingsboard/tree/master/docker) you need a powerful server to deploy all the containers. This is excessive for such a small workload.
Use monolith deployment in docker: https://thingsboard.io/docs/user-guide/install/docker/
