### ISSUE TITLE
[Question] auto logout-custom menu-iframe

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#3858]
**Component**

 * White-labeling: custom menu

**Description**
In the custom menu, I set up two custom menus, one uses the TB example, and the other uses my own public dashboard.
<img width="826" alt="螢幕快照 2020-12-17 上午11 54 10" src="https://user-images.githubusercontent.com/63713926/102442920-7fcb4c80-4060-11eb-8e8a-2b823e423896.png">

The two menus can work normally (display the content), but when the reload function is used in the browser, (TB example) can keep the login status, but the one using its own public dashboard link will auto logout...
![螢幕快照 2020-12-17 上午11 54 51](https://user-images.githubusercontent.com/63713926/102442968-9bceee00-4060-11eb-9512-37d242a38d78.png)

How can I fix this problem? thanks~

**Environment**

 * ThingsBoard: 3.2 ([aws](https://thingsboard.io/docs/user-guide/install/pe/aws-marketplace/))
 * Browser: chrome

**Comment by Surgbc** [comment]
You should probably share your dashboard with the current user. Public dashboards belong to public user and will set access token for public user in the browser, thus effectively logging out the currently logged in user.
