### ISSUE TITLE
[Question] Custom menu - how to include it in "/home"?

### ISSUE THREAD

**Issue by ecmap** [thingsboard/thingsboard#3859]
**Component**

 * Custom menu

**Description**
Is there any way to include it in "/home"?

<img width="1613" alt="螢幕快照 2020-12-17 下午2 31 07" src="https://user-images.githubusercontent.com/63713926/102452119-c1fe8900-4074-11eb-9577-4fe502b5eb5b.png">

Thanks~

**Environment**

 * ThingsBoard: 3.2

**Comment by ashvayka** [comment]
This is not possible yet. Probably a valid feature request.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
