### ISSUE TITLE
"new" button for additional marker on maps is missing

### ISSUE THREAD

**Issue by affoltep** [thingsboard/thingsboard#386]
The new button to include a further marker is missing on the "new" maps to display latest values in thingsboard 1.3.1. The button is usually located at the very end of the advanced settings.

Problem: There is no way to add a second or more markers on the same map with the new maps widgets. The function was available on the deprecated maps.

**Comment by Karabiy** [comment]
you can refer to the current "input widgets" maps for those reasons. First, you need to add the amount of entities (or functions) which you want to visualize using the markers and then drag, drop and select which exact entity will be available for the pop-up.
