### ISSUE TITLE
[Question] ThingsBoard PE 3.1.1 Integration of Custom Fonts

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#3860]
Hi,

In one of our projects, a customer wants to map their corporate identity in Thingsboard. This includes the integration of custom fonts (e.g. Google Noto Fonts). Is this possible system-wide for ThingsBoard (including menus, dashboards, email templates etc.) ? If yes, how can this be realized?

Thanks in advance

**Comment by mde2017** [comment]
I was able to set a Custom Font for the Menu using the video below:
https://www.youtube.com/watch?v=V9jl-gb9g2I

`@import url('https://fonts.googleapis.com/css2?family=Noto Sans');
 
.tb-root,
*:not(.material-icons):not(.tb-toogle-icon):not(.pull-right):not(.fa) {
    font-family: 'Noto Sans', sans-serif !important;
}
`

**Comment by inakigoicolea** [comment]
Hi

I want to set a custom font, but ideally only for the pop-up window with the credentials for the devices.

How could I change the font only to that credentials dialog?
