### ISSUE TITLE
[Question] Widget development: problem with ng-repeat

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#3861]
**Component**
 * UI

**Description**
I'd like to create a new widget as explained here:

https://thingsboard.io/docs/user-guide/contribution/widgets-development-before-3.0/#creating-simple-widgets

I have followed the instructions for the very simple "latest values widget" example.
When I click Run I obtain this error in the angular ng-repeat structure:

```
TypeError: Cannot read property 'dataKey' of undefined
    at e_Template (template.html:20)
    at Eo (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at jo (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at na (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at VM10363 polyfills.cbc38d3fba3c960b664b.js:1
    at jo (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at VM10363 polyfills.cbc38d3fba3c960b664b.js:1
    at jo (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at ua (VM10363 polyfills.cbc38d3fba3c960b664b.js:1)
    at e.value (VM10363 polyfills.cbc38d3fba3c960b66
```
dataKeyData seems not correctly instantiated.
It's strange because the "data" variable seems correctly instantiated as an array of objects. If I try to remove the ng-structure using this simple line of code it works:

`<div>{{data && data[0].dataKey.label}}</div>`

without "data &&" it gives the same error. This "trick" does not works inside the ng-repeat structure.

**Environment**

 * OS:  Linux debian
 * ThingsBoard: 3.2.0
 * Browser: Brave version 1.17.75 Chromium: 87.0.4280.88 (64 bit)

Thanks

**Comment by ChantsovaEkaterina** [comment]
Hello, @shaphiro 
It seems that you are following the guide written for the older TB version than you have.
Please, try to change your code according to this one:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#latest-values-widget

**Comment by shaphiro** [comment]
Ho, I'm sorry for the mistake!

Thank you
