### ISSUE TITLE
[Question] Multiple alarms in the same message

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#3866]
**Component**
 * Rule Engine

**Description**
Hi, I'd like to define a workflow to be able to manage multiple alarms within the same input message.
For example, if we have the following message:
{
temperature: 10,
humidity: 85
}
I'd like to create a workflow in which I can manage two alarms without duplicating nodes in different chains. For example if it was possible to "split" the original message in two message in the same chain (or, in general, N messages, 1 for each parameter) I could manage more easily this process. But this solution it seems not possibile.

Are there any "simple" way to do this?

Thanks in advance

**Comment by LuPe97** [comment]
You can try to use a "Filter - switch" Node. 

You can send multiple outputs for each attribute. 

Split Code for the Node: 
```javascript
return Object.keys(msg)
```

Now you have a Message for every single Telemetry in your Object.

I hope this helps you a bit.
