### ISSUE TITLE
[Question] How can to visualize array or object that is received as telemetry data

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#3867]
**Component**
 * Generic

**Description**
Hi,
Several of my devices get some telemetry data in an array or object form.
Let's take array for example, it has some important information inside it and I want to visualize it.
I know that I can break the data through the rule engine before it is delivered to the device but each element in the array has the same format so if I do that I can only send one element.
How can I visualize the array or rather what inside of it?
Thanks!

**Environment**
 * ThingsBoard: 3.2.0

**Comment by Torounia** [comment]
Hi, I have the same question. My sensor is measuring on event-basis for 10 seconds at 1000 samples per second (Accelerometer). I am planning on sending the data as an array as per the example below:
```
data_raw = {
        "trigger_time": 123,
        "data": {
            "first_timestamp": timestamps[0],
            "data": sensor_data.tolist() # array of 10000 data samples
        }
```

Is the above assumption correct? Would that work?

I am planning on using the PE version

Thanks!

**Comment by snir99** [comment]
Asked a similar question see [here](https://github.com/thingsboard/thingsboard/issues/3852).
