### ISSUE TITLE
deploy xalauc/haproxy-certbot:1.7.9 in docker swarm failed

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#3869]
OS：Ubuntu 20.04
Thingsboard: 3.1.0
when i deploy thingsboard microservice using docker swarm,xalauc/haproxy-certbot:1.7.9 container failed by printing the following error message:
getsockopt failed strangely: Operation not permitted

don't know where cause this problem,by the way all other container succeed

**Comment by t0mmyz7** [comment]
hi
anyway you will want to swap xalauc image for this one
https://github.com/lonequantum/docker-haproxy-certbot

because you will get an error when trying to get letsencrypt cert

i am using docker-compose by the way not swam

**Comment by john1337** [comment]
> hi
> anyway you will want to swap xalauc image for this one
> https://github.com/lonequantum/docker-haproxy-certbot
> 
> because you will get an error when trying to get letsencrypt cert
> 
> i am using docker-compose by the way not swam
that's ok using docker-compose,but didn't work using swarm,i don't know why

**Comment by t0mmyz7** [comment]
weird, not too familiar with swarm, maybe try that other image?

**Comment by john1337** [comment]
finally solve this problem by replacing xalauc/haproxy-certbot:1.7.9 with haproxy:1.7.12，
here is the article from https://jonhuster.blog.csdn.net/article/details/112239101

**Comment by trypzz** [comment]
Closed, because now we using self-developed docker image for haproxy-certbort and problem do not reproduce in 3.2.2 version.

PR: https://github.com/thingsboard/thingsboard/pull/4354/commits
