### ISSUE TITLE
[Question] Can custom menu be configured to open a dashboard without opening it in an iframe?

### ISSUE THREAD

**Issue by Surgbc** [thingsboard/thingsboard#3873]
**Component**
 * UI

**Description**
The settings for custom menu has the `iframeUrl` for opening a page in an iframe. But this is very slow on my server. Is there a way that the custom menu can be set open the page now opened in the iframe in the normal window?

 `{
  "disabledMenuItems": [
  
  ],
  "menuItems": [
    {
      "name": "",
      "iconUrl": null,
      "materialIcon": "",
      "iframeUrl": "",
      "setAccessToken": true,
      "childMenuItems": [ ]
    },
  ]
}`

**Comment by mm-1994** [comment]
hi @Surgbc
did you solve this issue
i have the issue when i set a dashboard to open from custom menu it takes long time to open.
can you help me  
@ashvayka also if you can help

**Comment by Surgbc** [comment]
Yes, I did. But it will require that you rebuild thingsboard. If you have a private development server I could show you how.

**Comment by mm-1994** [comment]
yes i have a private server
what can i do

**Comment by Surgbc** [comment]
It's a long set of commands. And since I did it on the PE version, I would suggest that we continue the conversation privately as the process may violate the terms of the license. You can reach out at brian@cseco.co.ke.

**Comment by Surgbc** [comment]
@mm-1994 are you still working on this?

**Comment by mm-1994** [comment]
@Surgbc yes , but still no clue 
can you share with me your idea

**Comment by Surgbc** [comment]
I've added you to the organization [thingsboardMod](https://github.com/thingsboardMod). I'll create a repo there shortly with the instructions.

**Comment by angelikileonida** [comment]
I have the same issue,

but my instance is in professional edition hosted in  AWS, version  3.2.0 PE

**Comment by Surgbc** [comment]
@angelikileonida I have added you to [thingsboardMod](https://github.com/orgs/thingsboardMod). You can check [DashboardFromCustomMenu](https://github.com/thingsboardMod/DashboardFromCustomMenu) and see if you can follow the instructions and let me know if you have any problems.

**Comment by angelikileonida** [comment]
Hi @Surgbc, 

thank you for the info. I will try, is this recommended by TB team?

**Comment by angelikileonida** [comment]
Hi @Surgbc,
 
I will try following the instructions and let you know. thank you

**Comment by MasterChips1** [comment]
Hi,

With Thingsboard 3.2.2 PE version you can now link a dashboard ID to the custom menu instead of only the IframeUrl.

**Comment by mm-1994** [comment]
hi @MasterChips1 
how is that done ?

**Comment by MasterChips1** [comment]
Hi @mm-1994 
First you need to update to 3.2.2 PE version with (on ubuntu/centos) : https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#prepare-for-upgrading-thingsboard-centos-ubuntu
Then on custom menu you have a new setting that you can add: dashboardId. Here you need to enter the dashboard Id from the dashboard you want to show. 

This can be found in the url of the dashboard: your_site/dashboardGroups/{dashboardId}/xxx

**Comment by diffuzi** [comment]
@Surgbc  - could you please add me to thingsboardMod? It would be great, thanks!

**Comment by Surgbc** [comment]
@diffuzi I have. But why not upgrade to the version 3.2.2?

**Comment by diffuzi** [comment]
@Surgbc  thanx. We have 3.2.2, but at the first time the dashboard-id did not function. Now it works ;)

**Comment by Kevinowitsch** [comment]
> Hi @mm-1994 First you need to update to 3.2.2 PE version with (on ubuntu/centos) : https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#prepare-for-upgrading-thingsboard-centos-ubuntu Then on custom menu you have a new setting that you can add: dashboardId. Here you need to enter the dashboard Id from the dashboard you want to show.
> 
> This can be found in the url of the dashboard: your_site/dashboardGroups/{dashboardId}/xxx

Not working for me. 
Only way atm to get it somehow to work is using the whole URL in the iframe field.

**Comment by markZAR** [comment]
Got it working. Yay. No more double menu!

For me the dashboardId was not found in this position.... your_site/dashboardGroups/{dashboardId}/xxx
but rather This can be found in the URL of the dashboard: your_site/dashboardGroups/{dashboardGroupId}/**{dashboardId}**
