### ISSUE TITLE
How To Display Several devices having same serial number ?

### ISSUE THREAD

**Issue by mm-1994** [thingsboard/thingsboard#3875]
Hi ,

i have main dashboard having all devices, some if these devices having same serial number as timeseries value ( ex . 123123)
these devices is displayed with device admin widget.
i want to click of any of the devices with this serial number and navigate to new dashboard state and display only devices having this serial number.
N.B i don't know the serial number it is dynamic 
thanks. 
please if you can  @ashvayka @vvlladd28

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
