### ISSUE TITLE
Swagger Code Gen

### ISSUE THREAD

**Issue by pellesg** [thingsboard/thingsboard#388]
I’ve tried to use Swagger Code Gen, but I seem to be missing some definition file or something. I’m new to Swagger code gen, so I’m not totally sure what’s needed on the server side to support code gen. Should this work in TB?
I tried the following cmd:
java -jar swagger-codegen-cli-2.2.1.jar generate -i http://localhost:8080/XXX -l csharp
Where XXX has been various destinations, but a either get parse error or file not found.. 
Can anybody help me?
Planning to make a DataGenerator and test some heavy duty load😊

**Comment by ChristianLutz** [comment]
I used maven to get it working, as you see i copied to swagger.json locally because i don't have access during the build. So this may solve your problem, too.

    <plugin>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-codegen-maven-plugin</artifactId>
      <version>${swagger-codegen-maven-plugin.version}</version>
      <executions>
        <execution>
          <id>cs-build</id>
          <phase>generate-sources</phase>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>
            <inputSpec>${basedir}/src/main/resources/swagger.json</inputSpec>
            <language>csharp</language>
            <generateApis>true</generateApis>
            <generateApiTests>false</generateApiTests>
            <generateSupportingFiles>false</generateSupportingFiles>
            <output>${basedir}</output>
          </configuration>
        </execution>
      </executions>
    </plugin>
