### ISSUE TITLE
deploy xalauc/haproxy-certbot:1.7.9 in docker swarm failed 

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#3884]
OS：Ubuntu 20.04
Thingsboard: 3.1.0
when i deploy thingsboard microservice using docker swarm,xalauc/haproxy-certbot:1.7.9 container failed by printing the following error message:
getsockopt failed strangely: Operation not permitted

don't know where cause this problem,by the way all other container succeed

**Comment by john1337** [comment]
finally solve this problem by replacing xalauc/haproxy-certbot:1.7.9 with haproxy:1.7.12，
here is the article from https://jonhuster.blog.csdn.net/article/details/112239101

**Comment by trypzz** [comment]
duplicate  #3869
