### ISSUE TITLE
[Bug] MigratorTool Does not work!

### ISSUE THREAD

**Issue by dujunchen** [thingsboard/thingsboard#3895]
**Describe the bug**
My thingsboard environment has been upgraded to 3.2.0,old  thingsboard environment use PostgreSQL only,now,i want to change db to hybrid (PostgreSQL + Cassandra). I want to use MigratorTool in module tools,but it dont work.After I view some source codes of MigratorTool,i discover the problem.The construction of table ts_kv_latest and ts_kv in PostgreSQL is not same as the ones in MigratorTool source code.
**Your Server Environment**

* own setup
  * k8s deployment
  * ThingsBoard Version 3.2.0
**Your Client Environment**
* OS: MacOS
* Version 3.2.0
**Screenshots**
The construction of table ts_kv_latest and ts_kv in PostgreSQL
![image](https://user-images.githubusercontent.com/37523573/103151740-d1d84480-47bb-11eb-9d4b-a33cf9d80824.png)
The construction of table ts_kv_latest in MigratorTool source code
![image](https://user-images.githubusercontent.com/37523573/103151753-ecaab900-47bb-11eb-8552-38145b5d9f0b.png)

**Comment by Ultrazombie** [comment]
Hello,
sorry for the delay,
The migrator tool is improved and works well so far.
