### ISSUE TITLE
load page slow 

### ISSUE THREAD

**Issue by stormwrym** [thingsboard/thingsboard#390]
Hi ,
   It took me a few minutes to open the login page,I found that loading "bundle.11b7a3a9ce84e6e82164.js"  
  was very slow and large(5.9M) . It is not work that try to use <mate /> maker and HttpServletResponse  setting cache-control  
  ^v^-------------oso-----------------v^v

**Comment by ashvayka** [comment]
there was recent update to the cache control to avoid caching the script. @ikulikov let's investigate this.

**Comment by danielelic** [comment]
Any update? @ashvayka

**Comment by vparomskiy** [comment]
bundle size was optimized in ThingsBoard v2.2 
Please update to the latest version.
