### ISSUE TITLE
[Bug] Dashboard assigned customers can't be empty once a customer is assigned

### ISSUE THREAD

**Issue by HassanMojab** [thingsboard/thingsboard#3903]
To unassign a customer from the dashboard by removing the customer from the Entity list inside the "Manage assigned customers" modal, if the list is empty, the API call responds 400 Bad Request.

**Your Server Environment**
* demo.thingsboard.io

**Your Client Environment**

* OS: MacOS
* Browser: chrome
* Version 87.0.4280.88 (Official Build) (x86_64)

**To Reproduce**
1. Go to the Dashboards
2. Click on 'Manage assigned customers'
3. Assign a customer to the dashboard
4. Again Click on 'Manage assigned customers'
5. Remove the customer from the list
6. Click the 'Update' button

**Expected behavior**
The customer should be unassigned from the dashboard.

**Additional context**
A workaround is to assign the dashboard to the Public customer and then use the 'Make dashboard private' to unassign it from all the customers.

**Comment by YevhenBondarenko** [comment]
We could not reproduce the issue, so please provide us with the full error message from the response.

**Comment by HassanMojab** [comment]
Yes it is now fixed in the `demo.thingsboard.io`, but the response was:

```
{
  "timestamp": "2021-01-05T11:23:40.784+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "Required request body is missing: public org.thingsboard.server.common.data.Dashboard org.thingsboard.server.controller.DashboardController.updateDashboardCustomers(java.lang.String,java.lang.String[]) throws org.thingsboard.server.common.data.exception.ThingsboardException",
  "path": "/api/dashboard/68bb1900-0bcf-11eb-b3b7-1b19a2c03e54/customers"
}
```
ThingsBoard Version: 3.1.1

**Comment by YevhenBondarenko** [comment]
Thanks, the issue has fixed.
This fix will be available in the next release.
