### ISSUE TITLE
[Bug] Missing "Add Role" - Button under Roles, logged in with Tenant in 3.2.0 PE 

### ISSUE THREAD

**Issue by NN01010101** [thingsboard/thingsboard#3912]
When logged in as tenant under "Roles" there is no plus button as shown in the RBAC Guide https://thingsboard.io/docs/user-guide/rbac/#examples-and-how-tos

**Server Environment**
* own setup
  * docker deployment
  * ThingsBoard 3.2.0 PEvVersion
  * Mac OS Catalina 10.15.4 

**Screenshots**
![missing_plus](https://user-images.githubusercontent.com/10622794/103378209-78cd2100-4ad9-11eb-8061-c6af5f6a2bac.jpg)

**Comment by ashvayka** [comment]
Please make sure you are the Tenant Administrator and not the Tenant User. These buttons are hidden if your user does not have permission to edit the roles. I have double-checked that everything works ok on thingsboard.cloud which is based on 3.2.1-SNAPSHOT
