### ISSUE TITLE
K8s image deployment failed

### ISSUE THREAD

**Issue by 425804004** [thingsboard/thingsboard#3914]
* Generic

**Description**
The deployment of TB Web UI and TB JS executor is running with error

Starting‘Thingsboard Web UI Microservice’... 
Segmentation fault(core dumped)

I generated the image based on MSA of 2.4.3 source code。I have no problem with the official image deployment。
I think the size of the 2.4.3 image provided by the government is 40KB less than the image generated by my own packaging。
The only thing I don't think is that dockerfile in 2.4.3 is debian:stretch But it has become th in the latest 3.2 ingsboard:base 。 I don't have any clue. I hope I can get some ideas to solve this problem.thank you very much indeed
**Installation**

 * ThingsBoard: 2.4.3
 * Browser:chrome
 * docker version：18.06.1-ce
 *K8S version  ：v1.14.0

**Comment by ashvayka** [comment]
The 2.4.3 is a very old version. Please try to use the latest 3.x or at least 2.5.x.

**Comment by 425804004** [comment]
Because I have some code for secondary development and want to migrate it to k8s code, I want to determine whether images Debian has affected it. If so, I will upgrade the version

**Comment by 425804004** [comment]
> The 2.4.3 is a very old version. Please try to use the latest 3.x or at least 2.5.x.

Because I have some code for secondary development and want to migrate it to k8s code, I want to determine whether images Debian has affected it. If so, I will upgrade the version

**Comment by ban2derlog** [comment]
Hi, are you try to use latest version for K8s deployment?
