### ISSUE TITLE
[Bug] Issues with styling and title of entities card widget

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#3917]
**Describe the bug**
When I create a Entities Cards(Latest values) widget and try to change the widget title nothing happens and it stays the default one.
![title_issue](https://user-images.githubusercontent.com/31441724/103650977-8404ce80-4f69-11eb-9511-c3c4015daf13.png)

Furthermore when applying forSize style under the widget style nothing happens. Is there a way to change the size of the table headers and the table body differently?

**Environment**
* ThingsBoard: 3.2.0
* Ubuntu 20.04
* Firefox

**Comment by Backdraft007** [comment]
You can set the title in the advanced section.
