### ISSUE TITLE
Websocket Error on TB 3.2 PE

### ISSUE THREAD

**Issue by Arsal973** [thingsboard/thingsboard#3918]
**Component**

 * Generic

**Description**
I have started receiving Websocket error when I sign is a Tenant Admin. 
Have faced teh same issue previously but restarting the DB (Postgres) and TB service had resolved the issue for some time and now it has appeared again.

**Environment**

 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: 3.2 PE
 * Browser: Chrome Version 87.0.4280.88 (64-bit)
 
![TB WS Error](https://user-images.githubusercontent.com/7512847/103782264-0cae6800-5059-11eb-8f51-4dee7bf03cf4.png)

**Comment by Arsal973** [comment]
Here is the log file
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/5776532/thingsboard.log)

**Comment by ahmed-1a** [comment]
I have seen the same error in CE 3.2 today for the first time.

**Comment by Arsal973** [comment]
@ashvayka any update on this?

**Comment by Boolhwi** [comment]
I also have same issue. And I think this issue makes too many DB connections.

**Comment by ashvayka** [comment]
Hi @Arsal973 I don't see any websocket related errors in the logs. Please enable debug log level and launch this again. Although there is an error that identifies a potential upgrade issue.

**Comment by Arsal973** [comment]
@ashvayka please refer to the screenshot of browser console attached above. There you can see list of websocket errors we receive at the frontend

**Comment by ashvayka** [comment]
There is no meaningful error there. This is for security reasons. The UI user should not receive the stack trace of the server.

**Comment by vvlladd28** [comment]
Hi @Arsal973, 
We will fix this problem in the new version, TB 3.2.2. Wait for the release of the new version or do build from source code.

**Comment by Arsal973** [comment]
Thanks, @vvlladd28 for the update. Can you please share the upcoming release date?

**Comment by vvlladd28** [comment]
We plan to release by end of the current month.

**Comment by trypzz** [comment]
3.2.2 released. March 24 2021
