### ISSUE TITLE
[Question] Action on static element not working properly

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#3920]
**Component**
 * UI

**Description**
I created a button that when clicked suppose to go to a new dashboard state. The button was created in a static widget under the cards bundle. When I set the action to be 'on HTML element click' and then click on the button nothing happens.
This is the html code for the button:
`<div class='card'><button>Rules</button></div>`

![button_action_issue](https://user-images.githubusercontent.com/31441724/103800679-5dbc5d00-5055-11eb-85c1-03f3dcdc9439.png)

**Environment**

 * Ubuntu 20.04
 * ThingsBoard 3.2
 * Firefox

**Comment by ChantsovaEkaterina** [comment]
Hello,
To make this work you need to add an _id_ attribute with the action name to your markup.
`<div class='card'><button id="to_device_rules">Rules</button></div>` 
If you want the whole card to be clickable, you need to add an _id_ to the parent element and duplicate it for every nested element.

**Comment by snir99** [comment]
@ChantsovaEkaterina thanks, it solve my problem.
