### ISSUE TITLE
[Question] Self compiled package fails to install / postgresql driver

### ISSUE THREAD

**Issue by Regimbal** [thingsboard/thingsboard#3922]
**Component**
thingsboard 3.2.0-1

 * Installation

**Description**
The issue I meet does not happen with pre compiled deb package.
I try to install thingsboa following the steps of the official website, with following configuration:
Postgresql (tried 11, 12, 13).

The only thing I changed from the doc is the postgresql username and database owner.
Do anyone of you have any idea?
Searching in previous issues and around the web I also tried update rc-select version to latest, same with jdbc postgresql driver... Same result

Installation fails with the following message  :
`2021-01-05 20:45:41,297 [main] ERROR o.t.s.ThingsboardInstallApplication - Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver`

You can find the complete install.log file [Here on Pastebin](https://pastebin.com/4s7hwePj) 

**Environment**

 * OS:  Debian 10
 * ThingsBoard: 3.2.0
 * Browser: not related

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
