### ISSUE TITLE
REST API Properties

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3923]
Hello All,

    What is sort Property in Swagger URL REST API Link.

 /api/user/devices{?type,textSearch,sortProperty,sortOrder,pageSize,page}

What property to be set for 
textSearch and sortProperty

**Comment by vvlladd28** [comment]
Hi @nmahale10,

textSearch [String] - name to find device
sortProperty [String] - device name property, for sorting devices in array response

**Comment by nmahale10** [comment]
Can you please explain what is device Name Property.

Is their any other way to get All devices of Particular tenant.

**Comment by vvlladd28** [comment]
For example device Name Property: name, label, type, createdTime, etc.
Get all devices, current tenant, used API: /api/user/devices?pageSize=1000&page=0

**Comment by nmahale10** [comment]
Thanks a lot for quick update.

Is it possible to modify response as per requirement.

For example I just want 2 fields only “name” and “createdtime” in response

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
