### ISSUE TITLE
Linking MQTT Gateway API gateway to Uplink and Downlink converters

### ISSUE THREAD

**Issue by NN01010101** [thingsboard/thingsboard#3927]
Hi Thingsboard Team, you guys are doing an amazing job. Thank you for that.
I use Thingsboard PE and my solution heavily relies on MQTT Gateway API (NOT Gateway IoT). 

Question:

Is there a way to pass data to a custom Uplink converter before it reaches the gateway node? Basically to link gateway to a particular converter. I'm aware of the integration solution, but it requires a separate broker. 

Let me explain my use case:
As a hardware gateway, I use an ESP8266 which gathers information from multiple non-IP devices. The data is binary of a proprietary protocol. I would like to represent all the devices from non-IP network in thingsboard. For that, a parsing logic is needed. Parsing must happen in the cloud.  Ideally, esp publishes data as JSON with base64 raw data payload. Uplink converter receives it and parses it in the JSON format accordingly to MQTT Gateway API, Gateway object receives the packet (v1/gateway/telemetry) and creates devices accordingly.  Almost same logic for Downlink converter where RPC calls from devices that are being passed through the gateway to custom Downlink converter.

Is there any solution I'm not seeing here?

Thanks in advance.

PS: I could also parse the data in the rule engine, but I couldn't find any node that would be able to create a new device "on the fly". Is there any solution for that?

**Comment by NN01010101** [comment]
I could solve my problem by creating a custom rule. The example with creating new messages in this guide helped a lot: https://thingsboard.io/docs/user-guide/contribution/rule-node-development/#creating-new-messages-from-the-rule-node

**Comment by AndreSensaway** [comment]
Did you find a solution for this issue?
I have a similar use-case
