### ISSUE TITLE
[Bug] cannot increase Widget text size

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3932]
I am unable to increase text size in the widget, only in the title.

Using the same style as Title, what is expected that the text in the widget will also increase in side.

![image](https://user-images.githubusercontent.com/31729091/104168523-d8df9380-5406-11eb-9390-16362d5d9d16.png)

**Comment by LeoMorgan113** [comment]
Hi,
You can change the text size with the post-processing function in advanced settings.
![2021-08-09_09-42](https://user-images.githubusercontent.com/56256429/128669362-debd7853-d800-47f6-981e-eb6083255726.png)

However, you cannot enlarge column headers text.
