### ISSUE TITLE
[Bug] Cursor Offset after setting Custom Font in White-Labeling (Advanced CSS)

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#3934]
**Describe the bug**
After setting a Custom Font in White-Labeling there is a cursor offset in several input fields e.g. CSS configurations.
I followed the guide in mentioned in this video with adaptions for the Google Noto Fonts:
https://www.youtube.com/watch?v=V9jl-gb9g2I

**Your Server Environment**
* own setup
  * Azure Cloud and Local infrastructure
  *  3.2.0PE
  * OS Centos

**Expected behavior**
There should be no offset after changing the Font.

**Screenshots**
Cursor Position:
![offset1](https://user-images.githubusercontent.com/25298332/104191858-5d89dc00-541e-11eb-9267-0ec8231b1250.png)

After Pressing DEL:
![offset2](https://user-images.githubusercontent.com/25298332/104192067-9e81f080-541e-11eb-8583-10a89a3738b3.png)

**CSS used**

```
@import url('https://fonts.googleapis.com/css2?family=Noto Sans');

.tb-root,
*:not(.material-icons):not(.tb-toogle-icon):not(.pull-right):not(.fa) {
    font-family: 'Noto Sans', sans-serif !important;
}
```

**Comment by LeoMorgan113** [comment]
Hi @mde2017,

I've checked this and added task to ThingsBoard backlog, our developers will review this bug, but there’s no exact timeframe for this. If you would like to know the progress on this ticket, you can create another ticket on Jira with the production ticket number mentioned ( PROD-1138 ), and we’ll gladly update you on the ticket’s stage.

**Comment by jbepro** [comment]
Hi @mde2017 and @LeoMorgan113, 
I have exactly the same issue with Thingsboard PE 4.2.1. 
Is it possible to access the Jira ticket, or to have an update ? I'm interessed in a workaround or something like that, to customize the font without this side effect. 
Thanks in advance for your help ! :)
