### ISSUE TITLE
How to sort dashboard order desc or asc?

### ISSUE THREAD

**Issue by Boolhwi** [thingsboard/thingsboard#3936]
Hi, I'm using PE 3.1.1.

I wonder is there any way to change dashboard order.
![Screenshot_2021-01-12](https://user-images.githubusercontent.com/56704659/104288668-74eac700-54fb-11eb-9fb3-3e487c11f37f.png)
![Screenshot_2021-01-12(1)](https://user-images.githubusercontent.com/56704659/104288808-a6639280-54fb-11eb-90ba-14557923d3e0.png)
For example, I want to change order of dashboards  'Dashboard' > 'In line Oil Tank' > 'Chart & Monitor' to  'Chart & Monitor' > 'In line Oil Tank' > 'Dashboard' 
Thx advance.

**Comment by amillot** [comment]
Hi,
Bumping this issue, is there any way this can be done on Thingsboard PE ? Would like to list of dashboards in order asc/desc since in the current state the order seems to be completely random.
Thanks
