### ISSUE TITLE
Custom Action on entity view

### ISSUE THREAD

**Issue by engqandeel1993** [thingsboard/thingsboard#3938]
var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice (entityID.id).then(function(device) {

      if (device.name == 'thermostat1') {                    

          openDashboardState ('Thermostat1');

      } else if (device.name == 'thermostat2') {

          openDashboardState('Thermostat2');

      } else if (device.name == 'thermostat3') {

          openDashboardState('Thermostat3');

      }

});

function openDashboardState(stateId) {

    var params = {
        entityId: entityId,
        entityName: entityName
    };

    Widgetcontext.statecontroller.openState(stateId, params, false);
}

please I want to use this code on "Entity View" not in the device

**Comment by ChantsovaEkaterina** [comment]
Hello,
To achieve what you want to, you need just to replace _deviceService_ with _entityViewService_.
So your code will be transformed in the next way:
```
var $injector = widgetContext.$scope.$injector;

$injector.get('entityViewService').getEntityView(entityID.id).then(function(entityView) {

    if (entityView.name == 'thermostat1') {

        openDashboardState ('Thermostat1');

    } else if (entityView.name == 'thermostat2') {

        openDashboardState('Thermostat2');

    } else if (entityView.name == 'thermostat3') {

        openDashboardState('Thermostat3');

    }
});
```

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
