### ISSUE TITLE
DeviceActorMessageProcessor resending RPC calls on subsequent Device Connects

### ISSUE THREAD

**Issue by steves2j** [thingsboard/thingsboard#394]
When sending an RPC call to an offline device, the Call is cached in the rpcPendingMap which has a key of integer.

When the Device comes online, the pending RPC call is successfully send, however the rpcPendingMap does not have the entry removed due to an incorrect search of the key to remove.

A interim set is used to store the successfully send id's however this is a SUID set not an integer set.

To fix, change this set to Integer and push the entry.getKey() instead of the value.getMsg().getMsg().getId() object in the processPendingRpc method.

**Comment by ashvayka** [comment]
Do you want to submit PR?

**Comment by ashvayka** [comment]
Thank you for the report

**Comment by vparomskiy** [comment]
Issue already resolved.
