### ISSUE TITLE
Request to multiple devices

### ISSUE THREAD

**Issue by podmla** [thingsboard/thingsboard#3953]
Hi guys,
I'm new to this and I've encountered a proplem while returning RPC request from ThingsBoard to multiple devices. 
As what I read from ThingsBoard's publications, I just can send the request from ThingsBoard to exactly one device via DeviceID, so now, what should I do if I want to send one request to more than one device.

Thanks guys to take a look to this!

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request.
