### ISSUE TITLE
Load balancing  setup

### ISSUE THREAD

**Issue by xjz** [thingsboard/thingsboard#396]
Document on load balancing is left blank, is there a plan to fill with some examples,eg load balancing with nginx.TB cluster has built-in consistent hash ring based on id,while nginx do load balancing based on traffic, if nginx forwards device to a server which does't match the one resolved by TB based on device id, more RPC calls in TB cluster will happen,is that right?

**Comment by ashvayka** [comment]
Yes, you can't sync them easily, but this is ok. You just need to use some basic LB, that supports TCP. We recommend to use AWS LB or other LB built in for provider. It is not our priority to explain how to configure Nginx

**Comment by xjz** [comment]
@ashvayka thank you
