### ISSUE TITLE
[Bug] RESTAPI /api/alarm/highestSeverity/{entityType}/{entityId} maybe trigger dead cycle

### ISSUE THREAD

**Issue by real7** [thingsboard/thingsboard#3966]
**Describe the bug**
getHighestAlarmSeverity, if device's alarmseverity is not "CRITICAL", the program will enter a dead cycle。

the problem code at org.thingsboard.server.dao.alarm.BaseAlarmService.findHighestAlarmSeverity()。

**Your Server Environment**
* own setup
  * Centos   ThingsBoard Version 3.2.0

**Comment by YevhenBondarenko** [comment]
Hi @real7, @AndrewVolosytnykhThingsboard  has fixed the issue. Fix will be part of 3.3 release.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
