### ISSUE TITLE
[Feature Request] TCP Integration Downlink

### ISSUE THREAD

**Issue by pde-system-integration** [thingsboard/thingsboard#3969]
I know that at the moment TCP integration does not support Downlink functionality but pls have plan to upgrade this functionality because many devices need to remote control.
Many thanks!

**Comment by YevhenBondarenko** [comment]
This feature was added and will be available in the 3.2.1 version.

**Comment by pde-system-integration** [comment]
It seems that Thingsboard PE 3.2.1 hasn't add this feature. Pls help me check!
https://thingsboard.io/docs/reference/releases/#v321-january-26-2021

**Comment by YevhenBondarenko** [comment]
Info about this feature and guide we add on the next week.

**Comment by YevhenBondarenko** [comment]
Hi @pde-system-integration 

The docs about TCP Downlink is available [here](https://thingsboard.io/docs/user-guide/integrations/tcp/#downlink-converter).
