### ISSUE TITLE
[Question] Custom Action  not working after upgrade to V3.2

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#3971]
Hi All,

I have a custom action button and using device service to get user devices.  We matched the code after the upgrade but doesn't work. 

Seems that the function requires a PageLink object which is not defined. 
![image](https://user-images.githubusercontent.com/45817004/105168798-4a17f880-5b23-11eb-9339-38a084c44d6f.png)

Please advise on how to solve this issue.
 
let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let assetService = $injector.get(widgetContext.servicesMap.get('assetService'));
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

var $injector = widgetContext.$scope.$injector;
var params= {};
params.limit = 50;
   let getDevs = deviceService.getUserDevices(params)
            .then(
                function(devices) {
                    vm.devices = devices;
                });

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.2
 * Browser: Chrome

**Comment by ahmed-1a** [comment]
I couldn't find getUserDevices in [here ](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/device.service.ts)

**Comment by angelikileonida** [comment]
Hi, 

well, I was looking in the swagger documentation to see the supported commands and the REST API supports it.
On top in release 2.4  getUserDevices was supported. 

what is the alternative to get a list of devices per user or customer or by device type?

Do you have any documentation on what is supported for each service? 

 Thank you in advance, 

Angeliki

**Comment by ahmed-1a** [comment]
Check [this folder](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/app/core/http) and you can browse through all the functions. 

These should also be reflected in the [Swagger UI](https://demo.thingsboard.io/swagger-ui.html)

You're looking for:
![image](https://user-images.githubusercontent.com/41074884/105689912-41dd0600-5ef3-11eb-8d7f-69a5692a7a4c.png)

![image](https://user-images.githubusercontent.com/41074884/105689977-59b48a00-5ef3-11eb-9d61-398220270ce4.png)
