### ISSUE TITLE
[Question] Change color of a building marker based on inactive devices in owns

### ISSUE THREAD

**Issue by Cody-Hayes97** [thingsboard/thingsboard#3973]
**Component**

 * UI
[map screenshot](https://ibb.co/GPvDLJ9)

**Description**
Hello! I currently have a map widget that is displaying every asset in my portfolio. Each asset contains several devices, all with their own active/inactive attributes. What I want to do is change the markers on the map to red if there are one or more inactive devices contained in that building, or green if all devices in the building are active. I know how to change color of markers on a map when directly referencing a device or attribute, but since this map is displaying the assets, I will somehow need to drill down to reference the devices in the asset, and then change the marker on the map. Is there any functionality for this? I cant seem to find any examples of someone trying this out. If there are any methods I could use to accomplish this whether it be the rule chain or marker function I could use the help. Thanks in advance!

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 
 * Browser: chrome

**Comment by vvlladd28** [comment]
Hi @Cody-Hayes97,
Rule Chain may solve your problem. You need to catch the event created/ cleared alarm and update attributes in the asset.

**Comment by misbahelamin** [comment]
Hi @vvlladd28 
Thanks for yous input above , I will appreciate if you give an example for the solution you suggest above , since I am new with Thingsboard and IoT ..
I mean like the rule chain flow and the inside scripts ..
Thank you in advance
