### ISSUE TITLE
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

### ISSUE THREAD

**Issue by sagarganachari** [thingsboard/thingsboard#3975]
whenever i add new dashboard in TB ,i am getting the following error.

could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by ashaforost** [comment]
Hi @sagarganachari 

Is the issue still present?
