### ISSUE TITLE
Create Custom REST API Queries

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3978]
Hello All,
   In my case I want to send the historical data of all keys of one device using "getTimeseries".
In current REST API Call key names are compulsory.

I need to create REST API in such a way that I can keep key names optional.
By default it should send all the data of keys.

Can we achieve this in TB PE 3.1 Version.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
