### ISSUE TITLE
requestBody in rule-engine-controller

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3981]
Hello All,
  Can any one please tell what is the "requestBody" in rule-engine-controller in REST API.
What parameters to be given

**Comment by ahmed-1a** [comment]
It's the msg from the previous node, and the body to be sent in the rest API method.

[Check this link.](https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node)

Also, use the Debug feature to check the incoming msg in any node.

**Comment by nmahale10** [comment]
Thanks for the reply.
Is it possible to fix JWT Token without expiration.

**Comment by ashvayka** [comment]
@ahmed-1a answer is correct. Thank you!
