### ISSUE TITLE
Is there any way to upload telemetry in bulk ?

### ISSUE THREAD

**Issue by manishpatelgt** [thingsboard/thingsboard#3983]
I am using below API for uploading telemetry where I can send Object with key-value like below

URL: https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api

**Request Body:**

```
{
  "latitude": 23.1072006,
  "longitude": 72.5426742,
  "speed": 0.0025938347
}

```
Question: I am looking for bulk upload where I can send Array of Object with key-value like below

**Request Body:**

```
[
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  },
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  },
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  }
]
```

**Comment by ahmed-1a** [comment]
Have you tried to include the timestamp?

`{"ts":1451649600512, "values":{"key1":"value1", "key2":"value2"}}
`

**Comment by manishpatelgt** [comment]
No. let me check

**Comment by manishpatelgt** [comment]
If I send above JSON then it works well

URL: http(s)://host:port/api/v1/$ACCESS_TOKEN/telemetry

[
```
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  },
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  },
  {
    "latitude": 23.1072006,
    "longitude": 72.5426742,
    "speed": 0.0025938347
  }
]
```

**Comment by manishpatelgt** [comment]
Let me close this.

**Comment by FacelookHK** [comment]
Would the 3 elements end up having same timestamp? This causes ThingsBoard to save only 1 element successfully.
