### ISSUE TITLE
[Question] Thingboard MQTT QoS

### ISSUE THREAD

**Issue by oalles** [thingsboard/thingsboard#3988]
**Thingsboard**

 * Installation

**Description**
I see here https://thingsboard.io/docs/reference/mqtt-api/ that 

"ThingsBoard server nodes act as an MQTT Broker that supports QoS levels 0 (at most once) and 1 (at least once) ", I wonder how Qos level can be changed. 

Tnx

**Environment**
 * ThingsBoard: 3.2

**Comment by ashvayka** [comment]
Hi @oalles .

The QoS level is specified by the mqtt client in the PUBLISH or SUBSCRIBE messages. It is not configured on the back end. See publish [header](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718038) and subscribe [packet](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718066) documentation.

**Comment by oalles** [comment]
Tnx ashvayka.

Given an a device, in order to subscribe to RPC commands from the server, send SUBSCRIBE message to the following topic:

v1/devices/me/rpc/request/+

The client/device  can subscribe with QoS 1, but how it can be controled the message published to that topic comes with QoS =1? It seems to be zero. 

Same for IoW Gateway and RPC configuration. Can it be set that a given RPC is sent to a given topic?
serverSideRpc configuration field allows requestTopicExpression, but no qos. Can Qos be leverage there?
