### ISSUE TITLE
Dashboard not working when "Always Full-screen" selected

### ISSUE THREAD

**Issue by Elnuvr** [thingsboard/thingsboard#3993]
Dashboards

 Generic

I created a dashboard using the HTML Card as a navigator. The issue is that when I set that dashboard to "Always Full-screen" for the user it does not function that same as when the "Always Full-screen" is unchecked. In other words, when the "Always Full-screen" is unchecked the dashboard work as intended.

We are on the latest version of TB (upgraded last night 2021/01/25)

**Comment by vvlladd28** [comment]
Hi @Elnuvr,

This correct work TB because this function is designed to work with one dashboard and provides the inability to go to other pages that are different from the specified dashboard

**Comment by PawelOstropolski** [comment]
Looks like I have similar issue here.... for chrome on Android devices...  the functionality I would like to achieve is:
a user ( a customer of a customer) login will point him directly to a single dashboard in full screen mode.... no toolbars, no home etc just the dash content full screen. 
I tried many combinations of user settings and dashboard settings but can not get it to work on Chrome on Android... which does not have a full screen menu button. 

@TB Can you provide an intended configuration for the above i.e.: user settings and dashboard settings

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
