### ISSUE TITLE
[Bug] switch control widget RPC update status not working most of times

### ISSUE THREAD

**Issue by amir-hg** [thingsboard/thingsboard#3994]
**Describe the bug**
switch control widget not update its status from RPC call when i open dashboard.
most of time it does not update its status and remain as default ( some time rarely it does work. i did not change anything i only open dashboard again and again)
i create a round switch control with the same config and device it works like charm!

**Your Server Environment**
i tested in my local localhost(v3.2.0) , thingsboard.cloud, my own cloud(v3.2.0) . all of them is same result
i tested on desktop chrome(Version 87.0.4280.66 (Official Build) (64-bit)) 
i tested on mobile chrome (88.0.4324.93)
and mozila firefox (84.0.2 (64-bit))

the dashboard exist on my thingsboad.cloud account named "esp"

`{
  "widget": {
    "isSystemType": true,
    "bundleAlias": "control_widgets",
    "typeAlias": "switch_control",
    "type": "rpc",
    "title": "New widget",
    "sizeX": 4,
    "sizeY": 2.5,
    "config": {
      "targetDeviceAliases": [],
      "showTitle": false,
      "backgroundColor": "#e6e7e8",
      "color": "rgba(0, 0, 0, 0.87)",
      "padding": "0px",
      "settings": {
        "requestTimeout": 500,
        "initialValue": false,
        "setValueMethod": "setGpioStatus",
        "showOnOffLabels": true,
        "title": "Switch control",
        "retrieveValueMethod": "rpc",
        "valueKey": "value",
        "parseValueFunction": "return data ? true : false;",
        "getValueMethod": "checkStatus",
        "convertValueFunction": "return value ? {\"pin\":2,\"enabled\":true} : {\"pin\":2,\"enabled\":false};"
      },
      "title": "New Switch Control",
      "dropShadow": true,
      "enableFullscreen": false,
      "widgetStyle": {},
      "titleStyle": {
        "fontSize": "16px",
        "fontWeight": 400
      },
      "useDashboardTimewindow": true,
      "showLegend": false,
      "actions": {},
      "decimals": 2,
      "datasources": [],
      "targetDeviceAliasIds": [
        "50ab37b6-cdc4-b210-02f7-b227152a74c0"
      ]
    },
    "row": 0,
    "col": 0,
    "id": "78738252-3b8d-f15d-f284-4adeb40c75d6"
  },
  "aliasesInfo": {
    "datasourceAliases": {},
    "targetDeviceAliases": {
      "0": {
        "alias": "esp",
        "filter": {
          "type": "singleEntity",
          "resolveMultiple": false,
          "singleEntity": {
            "entityType": "DEVICE",
            "id": "dfb2fa20-5fb5-11eb-a4ac-114d4c9f373e"
          }
        }
      }
    }
  },
  "filtersInfo": {
    "datasourceFilters": {}
  },
  "originalSize": {
    "sizeX": 4,
    "sizeY": 2
  },
  "originalColumns": 24
}`

**Comment by RondoRonaldo** [comment]
Hi,

Thank you for this information. This bug will be fixed in ThingsBoard 3.3v.
