### ISSUE TITLE
QoS Control in server-side RPC requests 

### ISSUE THREAD

**Issue by jalvarez2000** [thingsboard/thingsboard#3998]
Given an device, in order to subscribe to RPC commands from the server, send SUBSCRIBE message to the following topic:

v1/devices/me/rpc/request/+

The client/device can subscribe with QoS 1, but how it can be controlled the message published to that topic comes with QoS =1? It seems to be zero.

Same for IoW Gateway and RPC configuration. Can it be set that a given RPC is sent to a given topic?
serverSideRpc configuration field allows requestTopicExpression, but no qos. Can Qos be leverage there?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
