### ISSUE TITLE
[Question] Dashboard  Custom action - how to call assertservice / deviceservice functions with a pagelink object?

### ISSUE THREAD

**Issue by kastayou** [thingsboard/thingsboard#4003]
**Component**

 * UI

**Description**
I am trying to add an action button based on the "custom action (with HTML template)" to an entities table widget.
I would like to retrieve the list of asset of a specific type ("buildings").

My starting point is the add entity example.
The assetService is injected and I would like to use the following function provided by the asset service to retrieve the list of asset of a specific type:

```
 public getTenantAssetInfos(pageLink: PageLink, type: string = '', config?: RequestConfig): Observable<PageData<AssetInfo>> {
    return this.http.get<PageData<AssetInfo>>(`/api/tenant/assetInfos${pageLink.toQuery()}&type=${type}`,
      defaultHttpOptionsFromConfig(config));
  }
```

I need to pass an object of type PageLink.
How to import this object type?

I have tried to call the function like this:

```
function test(){
            widgetContext.rxjs.forkJoin([
                assetService.getTenantAssetInfos({'page':0,'pageSize': 50}, "BUILDING")
        ]).subscribe(
            function (data) {
                console.log(data);
            }
        ); 
}
```
When I call my test function, I get the following error:

```
polyfills.cbc38d3….js:1 ERROR TypeError: **e.toQuery is not a function**
    at **e.getTenantAssetInfos** (main.b61999d….js:1)
    at test (eval at <anonymous> (1.c834409….js:1), <anonymous>:138:30)
    at Object.EditEntityDialogController [as controller] (eval at <anonymous> (1.c834409….js:1), <anonymous>:51:5)
    at e [as constructor] (1.c834409….js:1)
    at new e (1.c834409….js:1)
    at e_Factory [as factory] (VM18315 ɵfac.js:5)
    at kr (polyfills.cbc38d3….js:1)
    at polyfills.cbc38d3….js:1
    at Fu (polyfills.cbc38d3….js:1)
    at n.value (polyfills.cbc38d3….js:1)
```

The toQuery function is called by the asset service function to transform the PageLink object to a string

https://github.com/thingsboard/thingsboard/blob/61723da3910222caae4acc87fc414fc794fdf66c/ui-ngx/src/app/shared/models/page/page-link.ts#L108

```
  public toQuery(): string {
    let query = `?pageSize=${this.pageSize}&page=${this.page}`;
    if (this.textSearch && this.textSearch.length) {
      query += `&textSearch=${this.textSearch}`;
    }
    if (this.sortOrder) {
      query += `&sortProperty=${this.sortOrder.property}&sortOrder=${this.sortOrder.direction}`;
    }
    return query;
  }
```

How to make a call from a custom action with HTML to a function of asset service or device service that needs a PageLink object as an input parameter?
Does somebody has a working sample code?

Note, if I replace the assetservice call by another function that does not take a pagelink object (_assetService.getTenantAssetInfos('c0286e40-5fd5-11eb-9a8a-7980bfd46495')_) as an input paramter, the code is working fine

A clear and concise details.

**Environment**
Thingsboard CE 3.2.0
 * OS:  docker image (tb-postgres:3.2.0) on centOS
 * Browser: Chrome

**Comment by kastayou** [comment]
Thank you !! It is working

**Comment by Mark-MV-Wizard** [comment]
Its still unclear how to use this page link object as when I use the assetService.getCustomerAssetInfos i still get the f.toQuery errror. can you please show an example query of how to use this function with the pagelink object to query a particular type of asset that belongs to a customer using the JavaScript widget editor menu

The code hints in the editor menu does not do a good job of explaining it properly
