### ISSUE TITLE
Copy data from one device to other using Rule Engine

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#4006]
If We set relation from Device A to Device B and using Rule Chain and using Change Originator.
, the whole data gets copied to Device B
My question is , is it the data duplication at Postgres DB levvel also .
So Postgres will have 2 differnt entries for one key under two different device.( Device A and Device B)
Can anyone please help me to clarify this.

**Comment by vvlladd28** [comment]
Hi @nmahale10,
If Rules Chain looks like this:
`Data -> save attributes/save timeseries -> Change Originator -> save attributes/save timeseries `
Postgres will have 2 different entries for one key under two different devices. ( Device A and Device B)

**Comment by nmahale10** [comment]
OK. If I use ASSET then also the behavior will be same?
If We set relation from Device A to ASSET A and using Rule Chain and using Change Originator.
, the whole data gets copied to ASSET A
My question is , is it the data duplication at Postgres DB level also .
So Postgres will have 2 different entries for one key under two different entities.( Device A and ASSET  A)
Can you please help me to clarify this.

**Comment by vvlladd28** [comment]
Yes, everything is correct

**Comment by nmahale10** [comment]
OK Thanks for the reply. Can I use ENTITY_VIEW so that I can avoid data duplication at Potsgres level.
If We set relation from Device A to ENTITY_VIEW and using Rule Chain and using Change Originator.
, the whole data gets copied to ENTITY_VIEW
My question is , is it the data duplication at Postgres DB level also .
So Postgres will have 2 different entries for one key under two different entities.( Device A and ENTITY_VIEW)
Can you please help me to clarify this.

**Comment by vvlladd28** [comment]
Yes, but you don't have to. ENTITY_VIEW automatically copies data added in the setting and belongs to the time window ENTITY_VIEW.

**Comment by nmahale10** [comment]
OK. But does it make a same entry to ENTITY_VIEW . Let us Say I have telemetry {"temp1":11} in DEVICE A. I make relation from DEVICE A to ENTITY_VIEW .It will make copy of {"temp1":11} to ENTITY_VIEW. My question is will it make the same entry at Database level also. So I will have two entries one under DEVICE A and other under ENTITY_VIEW in POSTGRES.
Is there any other way using which I can see the data of different DEVICES under one ENTITY without DUPLICATION OF DATA AT POSTGRES LEVEL.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
