### ISSUE TITLE
[Question] activity logging

### ISSUE THREAD

**Issue by simatei** [thingsboard/thingsboard#4007]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Is there currently a feature that would enable the system administrator to see a log activities such as sign in for customers or tenant admins?

**Environment**

 * OS:  name and version
 ThingsBoard: CE
 * Browser: name and version

**Comment by PovitruliaV** [comment]
Hi @simatei,
Unfortunately, at this point in time, ThingsBoard does not provide such an opportunity. But we have already added this request to our backlog for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
