### ISSUE TITLE
RPC from server - timeout issue PE

### ISSUE THREAD

**Issue by nalberto** [thingsboard/thingsboard#4013]
I have a device that gets telemetry from http integration.
I need to send a command to the device and I am using the rules engine to do that by sending an api call to the device and it works.
The issue is that the control widget is reporting a timeout when I send the rpc command.
Documentation shows how to send an RPC command from the rules engine but it refers to a message_id in the metadata but it is not present from the RPC call from server.
I just need the widget not to report an error all the rest works.

I would appreciate a simple example

**Comment by GrayCygnus** [comment]
I'm also on TB PE and am experiencing the same thing. My end device receives the Downlink command and updates whatever it should update, but the widget reports "Timeout" about 15 seconds after sending the command. I also wish to disable such timeout notification.

Did you manage to solve this?

**Comment by GrayCygnus** [comment]
@nalberto perhaps a bit hacky but I managed to remove the Timeout Popup notification. What I did what edit the CSS of the widget (custom widget) and include the following:

    .tb-toast {
        display: none;
    }
    .error-toast {
        display: none;
    }
    .tb-toast-panel {
        display: none;
        max-width: 0;
    }
    .toast-panel {
        display: none;
        max-width: 0;
    }

This prevents the popup from being displayed, although it does not avoid the 408 error that causes it.

**Comment by nicolas-simplycity** [comment]
Thanks for the tip. That will help a lot until TB fixes it.
I did not think of that.
Thanks again
