### ISSUE TITLE
[Question] Latest value Openstreet map offline display

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4015]
**Component**
 * UI

**Description**
I have two question regarding the map widget (type: latest value):

1. How can I make an Openstreet map work offline (while there is no internet)? I created a dashboard that will work on an local network.
2. Is there a way to make a marker image on the map to blink. For example I have two marker image one is green and the other is yellow I want it change color between them every second. Is there a way to do that?

I have some other question that didn't got any answer and will appreciate if someone will help me with them:
[https://github.com/thingsboard/thingsboard/issues/3959](url)

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2
 * Browser: Firefox

**Comment by kastayou** [comment]
Regarding your question 1, I am in the same situation, my thingsboard instance is on a local network not connected to Internet.

You need to setup a map server on your local network and configure your widget to use your own map server (advanced settings tab)

![image](https://user-images.githubusercontent.com/30028174/106326634-13598500-627d-11eb-953f-d5c0903ca48d.png)

You can find lot of example online about how to setup your offline map server (docker images exist)

**Comment by snir99** [comment]
@kastayou thanks, can you refer any good source that I can use?

**Comment by kastayou** [comment]
You can look at the following links:
[https://hub.docker.com/r/overv/openstreetmap-tile-server/](https://hub.docker.com/r/overv/openstreetmap-tile-server/)
[https://github.com/maptiler/tileserver-gl](https://github.com/maptiler/tileserver-gl)

Verify the different licences
