### ISSUE TITLE
[PE 3.2.1] Error displayed on the phone

### ISSUE THREAD

**Issue by pde-system-integration** [thingsboard/thingsboard#4018]
Error displaying device profile when I watch it on phone. Please help me check!
![image](https://user-images.githubusercontent.com/72959779/106110805-c6db5000-617d-11eb-8fbe-8c66d06d9094.png)

**Smartphone (please complete the following information):**
* Device: iPhone8 Plus
* OS: iOS 14.3
* Browser: Safari

**Comment by vvlladd28** [comment]
Hi @pde-system-integration,

To solve this problem, you need to clear cache in the Safari browser(https://support.apple.com/en-us/HT201265)

**Comment by pde-system-integration** [comment]
Thanks for your help!
