### ISSUE TITLE
Initiate multiple  REST API calls in the rule engine from one generator

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#4019]
**Component**

 * Rule Engine

**Description**
I would like to use an external rest API   to receive extra information for customer devices from an external REST Server. 
based on example  https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/get-weather-using-rest-api-call/

Generator Node has an option only for a specific “Asset/Device”. So I need a generator node for each device in order to initiate the REST API Call to receive information for each of my devices.
I would like to have one generator node( to trigger every n mins) and dynamically get the devices list (either by type or relation) in the rule chain and send  N requests through “Rest API call” node for each device.   
Is that possible through the rule chain? Do you propose another solution to achieve this functionality?

Angeliki

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.2 PE
 * Browser: chrome

**Comment by corlinski** [comment]
Hi
I have similar problem. Haven't tried that yet but I think to create a Generator node with Originator set as Device. Assign the Rule Chain to the customer / asset in question.
Then for each device belonging to the customer /asset it should trigger a REST API Call.

**Comment by FacelookHK** [comment]
Writing a custom node would be easier?

**Comment by rwanrooy** [comment]
I am looking for the same functionality but it seems that thingsboard is missing this. Did someone manage to figure this out?

**Comment by pon0marev** [comment]
It would be better to configure this functionality via the scheduler. However, you can also do this via the “generator”  and “duplicate to group” nodes. 
In the generator node, select “Entity group” and then add the “duplicate to group” node.
![image](https://github.com/user-attachments/assets/04c41983-1fef-49cd-a8ee-8c37cca158c7)
![image](https://github.com/user-attachments/assets/d0c1a083-f17d-4376-a9bd-11c33ab1c8a2)
This way your message will be duplicated to all devices in the group:
![image](https://github.com/user-attachments/assets/70f2f5aa-5089-4986-a113-be2eaeba8062)
