### ISSUE TITLE
[Question] Purpose of "Events" tab in Assets, Devices, EntityView on the Community Edition

### ISSUE THREAD

**Issue by robertoenr** [thingsboard/thingsboard#4027]
We've seen that on TB CE, when we open an ASSET, DEVICE or an ENTITY_VIEW, all of them have a tab called "Events". What is the purpose of this tab? How can we add events to an item? What are the possible events?
Any documentation about this events?
Thanks for your great work!

![events_tab](https://user-images.githubusercontent.com/38040966/106323181-4862d900-6277-11eb-80e0-9126b5670768.png)

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.2.1 CE
 * Browser: Chrome 84

**Comment by ehsanmqn** [comment]
Hi @robertoenr 
Did you find out the purpose of Event tabs in the mentioned entities? It will be appreciated if you guide me.

**Comment by ehsanmqn** [comment]
@ashvayka 
I have this question also

**Comment by ban2derlog** [comment]
Hi, this tab persists in different Entities in ThingsBoard.
This tracks different changes for different Entity types.
