### ISSUE TITLE
Does ThingsBoard use a multi-tenant database design?

### ISSUE THREAD

**Issue by anthonyorona** [thingsboard/thingsboard#4028]
I like how assets are modeled as a general tree with an arbitrary set of relations, but I am not sure about how that performs at scale in a relational DBMS. Does anyone know if ThingsBoard uses a multi-tenant database design?

**Comment by agtokty** [comment]
Hi @anthonyorona , sure, thingsboard uses the **tenant_id** column for each entity table in database.

You can see the scheme from [here](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/sql/schema-entities.sql).
