### ISSUE TITLE
[Bug] Whitelabel Error Page

### ISSUE THREAD

**Issue by sipt91** [thingsboard/thingsboard#4032]
**Describe the bug**
Use tenant@thingsboard.org to login.
Press F5 http://localhost:8080/assets
Error: Whitelabel Error Page

**Your Server Environment**
* My setup
  * local infrastructure
  * thingsboard-3.2.1
  * CentOS Linux release 7.9.2009 (Core)

**My Client Environment**
* OS: Windows 10
* Browser chrome

------------------------------
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Mon Feb 01 14:46:31 ICT 2021
There was an unexpected error (type=Not Found, status=404).
------------------------------

**Comment by blackstar-baba** [comment]
It fixed , look here: #4334

**Comment by blackstar-baba** [comment]
It fixed , look here: #4334
