### ISSUE TITLE
Misleading extra dots on state chart widget

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#4034]
Hello

![image](https://user-images.githubusercontent.com/39315/106430229-cbe51b80-646b-11eb-8322-e15255d4cd9d.png)

The screenshot above presents the same telemetries data displayed in a flot chart at the top and a state chart at the bottom.

With the flot chart, it is clearly visible that only a handful of values where sent during a short timeframe. Meanwhile, the state chart automatically adds 2 "ghost" dots values, at the beginning and at the end (the red arrows).

I understand that a state chart is suited for booleans, and the non interrupted lines make sense. But the 2 extra dots falsely imply that a value was sent at the current time which is not true.

Also, these "ghost" dots are not always present, they flicker which is even more misleading.

So to conclude, my take would be to remove these 2 extra dots.

Thanks

**Comment by pon0marev** [comment]
In version 3.7.0 “State chart” widget has been redesigned. This behavior is no longer reproduced. Please upgrade ThingsBoard to version 3.7.0 or higher.
If you can reproduce this behavior on version 3.7+, please create a new issue with a link to the current one.
![image](https://github.com/user-attachments/assets/b435765c-e764-49e3-afd8-675d177ea414)
