### ISSUE TITLE
[Question] Custom menu:  change the order of menu items

### ISSUE THREAD

**Issue by vincent12dev** [thingsboard/thingsboard#4035]
**Component**
     White-labeling: custom menu

**Description**
I wonder if we can change the order of items in a menu.
Thanks~

**Environment**

 * OS:  name and version
 * ThingsBoard:  Professional Edition(PE)
 * Browser: name and version

**Comment by Kullpoint** [comment]
just replace it in json file)

**Comment by Kevinowitsch** [comment]
He probably wants to move a custom item above the predefined items. Have the same issue. Probably not possible right now.

**Comment by PovitruliaV** [comment]
Hi @vincent12dev ,
Unfortunately, at this point in time, TB does not provide such an opportunity.
Regards
