### ISSUE TITLE
Device connectivity status not updated

### ISSUE THREAD

**Issue by sebsoft** [thingsboard/thingsboard#4039]
Device connectivity status

**Description**

I'am using a HTTP integration on TB PE to get the data of my sensors in TB.   The integration sucessfully creates new devices and everything functions a expected.  It seems however that the device state is not always correctly updated.  Active = false although data just arrived and timeout is set to 5 days. 

The server side attributes lastConnectTime  and lastDisconnectTime are also missing for all devices.

**Environment**

* Linux
 * 3.2.1. PE
 * Chrome

**Comment by gohm-tech** [comment]
Hi @ashvayka,

We have the same issue too.

Best Regards,
**Gohm Team**

**Comment by mykhailokornieiev** [comment]
Hi. As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
