### ISSUE TITLE
[Question] is it possible to control the values of the generator node from rule chain with a control widget?

### ISSUE THREAD

**Issue by Lautaro-a** [thingsboard/thingsboard#4040]
**Component**
 * Rule Engine

**Description**
I want to generate a telemetry that can be controlled with the knob control widget. I was wondering if it was possible by changing the generator node script so it can interact with the widget.

**Environment**
 * ThingsBoard: version 3.1.1PE

**Comment by aadriii88** [comment]
yo tambien necesito ayuda

**Comment by mykhailokornieiev** [comment]
Hi. Nope, there is no such possibility since it has different functionalities. 
The only solution, as I see, will be to create some custom widget, that will update rule chain's JSON. 
But I'd rather recommend you to use Scheduler, since Generator designed for test purposes, not production.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
