### ISSUE TITLE
[Question] Use telemetry data from different devices to visualize a calculation of the two or more variables.

### ISSUE THREAD

**Issue by doscon-git** [thingsboard/thingsboard#4044]
**Component**

 * UI

**Description**
In a graph widget it possible to add new data points. Is it possible to access multiple attributes from different devices and use those to calculate a new plot line using the Post Processing function? 

For example, i have flow data, concentration data plotted in one plot. I would like to calculate the total amount (flow*concentration) using the flow and concentration and have that plotted alongside the two other variables.

**Environment**

 * ThingsBoard: 3.1.1

**Comment by abhilash2134** [comment]
Facing the same problem!!

**Comment by ChantsovaEkaterina** [comment]
Hello,
There is no ability to get access to other keys data from the Post Processing function.
To achieve what you would like to get, it would be better to create a rule chain, that would perform all the calculations needed and create a new telemetry key, that could be plotted alongside other keys.

**Comment by doscon-git** [comment]
> Hello,
> There is no ability to get access to other keys data from the Post Processing function.
> To achieve what you would like to get, it would be better to create a rule chain, that would perform all the calculations needed and create a new telemetry key, that could be plotted alongside other keys.

Thank you. I was aware of using rule chains to do calculations, but so far i have only been able to apply these rule chains to present and future data, not past data. Is it possible to apply a rule chain to past data?

**Comment by ChantsovaEkaterina** [comment]
@doscon-git It is not possible to apply a rule chain to past data. One way to handle the past data is to write a script, that will fetch all needed data for a period, perform calculations and save newly created values with an appropriate timestamp in the past.
