### ISSUE TITLE
Export telemetry / timeseries data in a weekly CSV

### ISSUE THREAD

**Issue by marshandrewg** [thingsboard/thingsboard#4046]
**Component**

 * Rule Engine

**Description**
On a weekly basis, I want to be able to export chosen device telemetry values that have been gathered, as a csv file through email.

Similar to #3065, I have tried using the current Generate Report tool; but with the amount of data collected the pdf exported is a snapshot of all the widgets and tables loading. And I would prefer to export in csv format, with the widget data rather than a screenshot.

**Comment by brucedune** [comment]
Did you ever figure this out?
thanks

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
