### ISSUE TITLE
Concern for query performance with the asset model presented in TB Community

### ISSUE THREAD

**Issue by anthonyorona** [thingsboard/thingsboard#4047]
I have viewed the data model for ThingsBoard and see that you use a model like so:

![asset_model](https://user-images.githubusercontent.com/70772352/106661420-09be6e80-6556-11eb-97fa-ad276f8c6738.png)

So if I want to model a large building..there seems to be some downside here with query performance. I have to build a general tree and query it to get the information that I am looking for.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
