### ISSUE TITLE
Graph tooltip support for mobile devices

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#4048]
Hi team,

first of all congrats on the latest release, i see great performance improvements and so far no White Screen of Death :)

About this request:

I have raised this request before with support, but I am putting it in writing here as well.

please add tool-tip support for Graphs in mobile devices. Our users are constantly asking for this feature,

to be able to click on the graph in mobile-view and to get a tooltip with the value and timestamp where they clicked.

This feature/ability is very common across the board, and customers are used to it/looking for it in our thingsboard based solution as well.

![image](https://user-images.githubusercontent.com/31729091/106701905-1d1e1800-65f0-11eb-819d-c84aadfd72b7.png)

Community, if you see a need for this as well please +thumbsup this post

**Comment by lucilenikkels** [comment]
@t0mmyz7 I have started to work on this, but I can't seem to reproduce the issue (see the tooltip on my mobile iOS device in the screenshot).
Could you specify where this issue occurs?

![screenshot](https://user-images.githubusercontent.com/23525731/112132187-9d153700-8bca-11eb-9b73-b5977538af1e.jpeg)

**Comment by t0mmyz7** [comment]
Hi there!

Thanks for your contribution,so for us it doesn't work on Android firefox
and iOS safari.

Maybe it's something in the widget configuration?

Can you export your widget and I will try it?

Which browser are you using?

**Comment by lucilenikkels** [comment]
Hi again - sorry for the slow reply, I was working on another issue:)

I am using iOS safari and just checked again more thoroughly, but I can't find any cases where the desktop version is showing a tooltip and the mobile version is not. Perhaps you can point me to an instance of this on the demo server?

I'm not so sure is convenient send with regard to my widget configuration (which I by the way didn't change as far as I know) but [this](https://github.com/thingsboard/thingsboard/files/6198875/dashboard.zip) is the export of the dashboard on which I was testing, hope that helps!

> Hi there! Thanks for your contribution,so for us it doesn't work on Android firefox and iOS safari. Maybe it's something in the widget configuration? Can you export your widget and I will try it? Which browser are you using?
> […](#)

**Comment by t0mmyz7** [comment]
Maybe it was addressed in 3.2.2 , I am testing on 3.2.1
Let me try on demo server

**Comment by t0mmyz7** [comment]
@lucilenikkels ok I can confirm,issue is fixed in 3.2.2
. Closing the comment, what about that Dark Mode view instead 😆
