### ISSUE TITLE
The OAuth button is not showing up in the login page [Bug] 

### ISSUE THREAD

**Issue by Freir96** [thingsboard/thingsboard#4049]
**Describe the bug**

**Your Server Environment**

* own setup
  * Vagrant 2.2.10
  * ThingsBoard 3.2
  * CentOS Linux release 7.9.2009 (Core)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser opera
* Version 73

**To Reproduce**
1. Open thingsboard.yml
2. Add an authenticator (google, oauth0, or custom)
3. Save
4. Restart thingsboard service

Alternatively add the authenticators in thingsboard.yml

**Expected behavior**
An oauth button is visible on the login page

**Additional context**
The authentication used to work based on the configuration from thingsboard.yml on version 3.1.1, but after an update to 3.2 the button stopped to show up. Previously the authenticator used in our project was keycloak, but attempts to use google or oauth0 also did not work.

Edit: Manual setup with GUI does actually work, but the configuration from thingsboard.yml still doesn't work with oauth2.

**Comment by egavriluta** [comment]
Hello! I am wondering if the issue is still open? If so together with a group of fellow students in Software Architecture we are interested in doing our best to solve it. :)

**Comment by egavriluta** [comment]
Hi @ashvayka, @vvlladd28,
I was investigating this issue, it seems that a lot of changes were introduced in the security parameters of the thingsboard.yml when comparing v3.1 with v3.2. Most of these changes are related to the oauth2 configurations. I am still looking to identify the root cause, in order to attempt a fix. Any extra context for the issue would be very helpful. Furthermore, could you let me know if this issue is still opened and needed to be developed.

**Comment by loelkes** [comment]
I have a similar Issue with v3.2.2 (running with Docker) where I configured a custom OAuth2 provider (Keycloak) but the button never shows up on the login page. No error message is shown in the UI, haven't checked the logs yet.

**Comment by loelkes** [comment]
@Freir96 @egavriluta The issue was that ThingsBoard only does not allow redirects to HTTPS if it only runs with HTTP, even if you have a proxy handling HTTPS in front. Unless you want to use a HTTP after redirect the solution is to run TB with HTTPS behind the reverse proxy to allow HTTPS redirects for OAuth2.

Isn't there some magic header you can set in the first reverse proxy?

**Comment by p30arena** [comment]
@loelkes 
I have the same problem and don't know how to resolve it.

I have enabled SSL through Nginx but the button is not showing up, also tried every possible combination.
the button was showing up before enabling SSL.

**Comment by p30arena** [comment]
I used the following config in Nginx and my problem is solved:

```
       proxy_pass http://127.0.0.1:8020;
       proxy_set_header  Host               $host;
       proxy_set_header  X-Real-IP          $remote_addr;
       proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto  $scheme;
```

**Comment by p30arena** [comment]
but now the problem is that it redirects me with the wrong scheme... (HTTPS to HTTP)

![image](https://user-images.githubusercontent.com/1261332/125170790-efa05080-e1c5-11eb-936c-800178a8af57.png)

**Comment by p30arena** [comment]
Ok, I changed the source code to log the error and upgraded to MASTER.

` [invalid_id_token] An error occurred while attempting to decode the Jwt: Couldn't retrieve  remote JWK set: org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden`

Is this error related to being behind a reverse proxy? or the server's IP is banned?

**Comment by hide74** [comment]
@p30arena Thanks a lot for your good information.
Now I could authenticate with Google account as below nginx settting;

                proxy_pass http://localhost:8081;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header  X-Real-IP          $remote_addr;
                proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto  $scheme;

**Comment by Beetix** [comment]
Thanks! Had also the issue with HAProxy. Added `http-request add-header X-Forwarded-Proto https if { ssl_fc }` in my Thingsboard backend config.
