### ISSUE TITLE
State chart not working

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#405]
I am trying to use the state chart, to visualize the ON/OFF state of some telemetry data.

No matter what I do, it does not show anything. What kind of data does this widget expect me to send it?
0/1? true/false? Anything else?

**Comment by ashvayka** [comment]
0/1

**Comment by ashvayka** [comment]
You can apply converter to values in data source configuration

**Comment by fotis400** [comment]
Yes I am aware of the converters, and I have already tried to convert my bool value to 0/1. Generally I have experimented with this a lot. But the chart is always blank. Nothing is displayed.

**Comment by fotis400** [comment]
Ohhh.... My bad.... Instead of using a function for post-processing my value, I was inserting the code in the tooltip value formatting....

Just fixed it, and it works perfectly.

**Comment by mfalkvidd** [comment]
@fotis400 what function did you use? I have a boolean and used the functions below but it always shows "on".
![image](https://user-images.githubusercontent.com/893502/57786883-9a2a9f00-7734-11e9-8a27-d42076759496.png)
![image](https://user-images.githubusercontent.com/893502/57786912-aadb1500-7734-11e9-9eef-bd349e2dd0d6.png)

**Comment by fotis400** [comment]
I simply used this:

```
if (value == 'true')
    return 1;
else
    return 0;
```

**Comment by mfalkvidd** [comment]
Thank you @fotis400 
I expected the value to be a boolean, but it is a string so comparing to 'true' instead of true is what's needed.

**Comment by Goran-59** [comment]
Hello there, is it possible to have multiple defined states on vertical axis? 
I mean i tried to change "Ticks formatter function" on a various ways and still noting on the chart. 
The thing is i have String as a input value, and i want to be presented on the State chart. Values are predefined and there are 9 of them. 
Any help? I would be pleased.

**Comment by mpbr13** [comment]
Thanks a lot!

**Comment by Buhaw85** [comment]
Is there a why to write it so that if it is TRUE it retures value as DEVICE ONLINE?
![image](https://user-images.githubusercontent.com/130080104/235283570-8adf7d71-3193-4407-bdae-30a6be00c21e.png)

**Comment by dhaval2017** [comment]
@Buhaw85 
if (value == 'true')
    return 'ONLINE';
else
    return 'OFFLINE';

**Comment by martin9115** [comment]
Hi, I save some data, but can't display it in chart. I try with history data, but still don't see any chart. Any help?
![TB-Chart](https://github.com/thingsboard/thingsboard/assets/50946705/97cdf921-dedb-49b0-b893-3ea2cca6eb92)
