### ISSUE TITLE
[Question] Focusing on map when clicking on table row

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4053]
**Component**
 * UI

**Description**
I have a few devices (for now) that I show on a map and on a table. What I want to do is when I click on the a device in the table the map will focus/jump to that device on the map. If I have a lot of devices on the map locate a specific one so this can help to find the one that is needed by clicking on the table. How can I do that?

Here is an image for reference:
![table_click_map_focus](https://user-images.githubusercontent.com/31441724/106781384-ac0f4c80-6651-11eb-890c-bd12727c880a.png)

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2
 * Browser: Firefox

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
If this question is still relevant to you, feel free to open a new ticket with full description of your request.
