### ISSUE TITLE
[Bug] TenantAdmin additionalInfo  lost

### ISSUE THREAD

**Issue by oakfire** [thingsboard/thingsboard#4054]
**Describe the bug**
When  SysAdmin edit and save the TenantAdmin profile,  TenantAdmin additionalInfo will be lost ,  only left with "description","defaultDashboardId""defaultDashboardFullscreen"

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version: 3.2.0
  * OS Name and Version: Ubuntu18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows10
* Browser: chrome
* Version 88.0.4324.104

**To Reproduce**
1. Login as SysAdmin
2. Choose a Tenant and edit a TenantAdmin and save.
3. Use pgAdmin to see the Database, some TenantAdmin's additionalInfo ('lang', 'lastLoginTs',etc) was lost.

**Comment by vvlladd28** [comment]
Hi @oakfire 
Thank you for your report. Coming soon we add a fix.
