### ISSUE TITLE
Unable to send data from Arduino uno+ ESP01 to local thingsboard server

### ISSUE THREAD

**Issue by momomola1** [thingsboard/thingsboard#4055]
Hi, I've set up the local thingsboard server on my laptop. I'm able to send data from my arduino uno+esp01 to the demo server. However, when I tried sending it to the local server, it failed to send the data over. I'm following the tutorial given on DHT sensor https://thingsboard.io/docs/samples/arduino/temperature/

This is what was shown on the serial monitor.

`[WiFiEsp] Initializing ESP module
[WiFiEsp] Initilization successful - 1.1.2
Connecting to AP ...
Attempting to connect to WPA SSID: 512kbps@streamyx
[WiFiEsp] Connected to 512kbps@streamyx
Connected to AP
Attempting to connect to WPA SSID: 512kbps@streamyx
[WiFiEsp] Connected to 512kbps@streamyx
Connected to AP
Connecting to ThingsBoard node ...[WiFiEsp] Connecting to 192.168.229.186
[FAILED] : retrying in 5 seconds
Connecting to ThingsBoard node ...[WiFiEsp] Connecting to 192.168.229.186
[FAILED] : retrying in 5 seconds
`

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
