### ISSUE TITLE
See data of diiffrent devices under One Entity without duplication at Postgres DB Level

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#4057]
Let us Say I have telemetry {"temp1":11} in DEVICE A. I make relation from DEVICE A to ENTITY_VIEW .It will make copy of {"temp1":11} to ENTITY_VIEW. My question is will it make the same entry at Database level also. So I will have two entries one under DEVICE A and other under ENTITY_VIEW in POSTGRES.
Is there any other way using which I can see the data of different DEVICES under one ENTITY without DUPLICATION OF DATA AT POSTGRES LEVEL.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
