### ISSUE TITLE
 clickable Latest values card  widget 

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#4058]
**Component**
 * UI

**Description**
Hi, 
I want to make the latest values card clickable. 
can you help with this? 
![image](https://user-images.githubusercontent.com/45817004/106875121-fc80bb80-66de-11eb-85b3-2ce2fe093da5.png)

We have tried adding element click function in  tbDatasource-container but  the click function doesnt trigger. 
`$scope = self.ctx.$scope;
 $scope.ctx = self.ctx;
 $scope.onButtonClick = function($event, entity,actionDescriptor) {
        console.log("clicked");
        if ($event) {
            $event.stopPropagation();
        }
        self.ctx.actionsApi.handleWidgetAction(
            $event, actionDescriptor, "entityId",
            "entityName");
    }

 self.ctx.$container.append(
            "<div id='" + datasourceId +
            "' class='tbDatasource-container' "
            + "(click)='onButtonClick($event, entity, ctx.actionsApi.getActionDescriptors('actionCellButton'))'"
            +"></div>"
        );
   self.actionSources = function() {
    return {
        'elementClick': {
            name: 'widget-action.element-click',
            multiple: true
        }
    };

**Environment**
OS: Ubuntu
ThingsBoard: 3.2 PE
Browser: Chrome

**Comment by kristoss** [comment]
Hi,

I also faced the same issue. Any update?

Thanks

**Comment by kalutkaz** [comment]
Hi,

If you need adding element click function in tbDatasource-container you must pass the function to window:

        self.ctx.$container.append(
            "<div onclick='onButtonClick(event)' id='" + datasourceId +
            "' class='tbDatasource-container'></div>"
        );
        
        window['onButtonClick'] = function (event) {
            console.log('click');
        }

then the function will be triggered on click:

![image](https://user-images.githubusercontent.com/43555187/108692152-ef4c3500-7504-11eb-82de-c5a03335054c.png)

**Comment by kristoss** [comment]
Hi kalutkaz,

Thanks for the info,i made it but the html onclick custom action didn't work
This is the relevant action method call, I get the click console log but now further action
 window['_onButtonClick'] = function (event) {
        self.ctx.actionsApi.elementClick(event);
        console.log('click');
    }
Have you ever faced this?

Thanks,

**Comment by kalutkaz** [comment]
Hi @kristoss,
Could you please explain in more detail what functionality you are trying to implement?

**Comment by kristoss** [comment]
Hi @kalutkaz 

I would like to achieve navigation to another dashboard state on click
![2021-04-14 10_57_53-Dashboard](https://user-images.githubusercontent.com/49038152/114674954-6be2df00-9d10-11eb-913f-f5b38468c902.png)

with this implementation

```
window['_onButtonClick'] = function (event) {
self.ctx.actionsApi.elementClick(event);
console.log('click');
}
self.actionSources = function() {
    return {
        'elementClick': {
            name: 'widget-action.element-click',
            multiple: true
        }
    };
}
```

**Comment by kalutkaz** [comment]
Hi @kristoss 

For your task you can use two widgets, "HTML Value Card" if you want display some dynamic value or "HTML Card" this widget show static information.

In  "HTML Value Card" you must create action like this (in target dashboard state you must choose your state):
![image](https://user-images.githubusercontent.com/43555187/115032506-0dfdf500-9ed2-11eb-9239-d00fdadddd3f.png)

then you must add an 'id' with the name of your action to all html elements that need to be clickable (in the future we will fix this problem and you can only add 'id' to the parent element and all child elements will also be clickable).

for example I made the whole widget clickable:
![image](https://user-images.githubusercontent.com/43555187/115034107-cf693a00-9ed3-11eb-9ae9-558f0aa0b687.png)
 As a result when I click on widget new state is open:
![image](https://user-images.githubusercontent.com/43555187/115034356-1820f300-9ed4-11eb-9285-12df31b09ebd.png)

The 'HTML Card' work the same.

You also can read about action in tb pe documentation: https://thingsboard.io/docs/pe/user-guide/ui/widget-actions/

**Comment by kgabor1** [comment]
I know it is a very old thread, but is there any way to add On click event to a latest value cards (e.g. Horizontal Valu card)? Even when you create a new action for it, or use a built cardClick action, nothing happens, no action you set (e.g. navigate to a new dashboard) fires. So you can click on it, you can select any action (like navigate to new dashboard, new dashboard state), but finally nothing happens. 
The HTML solution is OK, however the built in value cards are just more better looking for many cases, and it is weird why it is not clickable by default. 

The last code I tried on cloning a Horizontal value card and modify it:
HTML:
<div style="width:100%; height:100%;" ng-click="onWidgetClick($event)">
    <tb-value-card-widget
        [ctx]="ctx"
        [widgetTitlePanel]="widgetTitlePanel">
    </tb-value-card-widget>
</div>


JS part:
self.actionSources = function() {
    return {
        'cardClick': {
            name: 'widget-action.card-click',
            multiple: false
        }
    };
};
