### ISSUE TITLE
[Feature]Widget - Single line Gantt Charts

### ISSUE THREAD

**Issue by logivity** [thingsboard/thingsboard#406]
Looking to implement single line Gantt charts similar to one shown in following link. 

https://jsfiddle.net/dx0Lw52b/

I think I might be able to develop widget with charts. My only problem is I need to add reason for every time the charts is in off position whenever mouse is hovered in corresponding off area. Also the reason code has to be manually entered i.e. a sub user (user with very limited privileges) is asked to add/select the reason. Once reason is selected it should show up on gantt chart for corresponding area.

**Comment by logivity** [comment]
I was thinking of using state charts, but how to add additional data which is not collected directly from device.

**Comment by ashvayka** [comment]
You can use rest API to store telemetry or server side attributes and the query it.

**Comment by ashvayka** [comment]
If you have troubles to find the API - let me know

**Comment by logivity** [comment]
@ashvayka I think I got where the API is but I using Cassandra for TB (p.s. I am new to Cassandra) and I am not sure if it can handle relation in data very well. Such as if there is a state case such as ON and OFF and I want to add reason for why it is off via a widget then where am I supposed to store this "reason" data in relation to state of input of a device.

**Comment by logivity** [comment]
Also what Cassandra table is used to receive telemetry data and store data.

**Comment by vparomskiy** [comment]
You can save a reason using different telemetry name but same timestamp. This 'mapping' should be used in your custom widget for showing reasons.
