### ISSUE TITLE
[Bug] No support for i18n (language) in cell content function

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#4066]
**Describe the bug**
It is not possible to use i18n (white labeling/language) when using the cell content function. Example: I want to have a type of alarm that is translated and display in a column of my alarm widget.

**Your Server Environment**
ThingsBoard Version 3.2.0 PE

**To Reproduce**
1. Add a key to white labeling
2. Create an alarm widget
3. Generate an alarm
4. Modify type of alarm data source to return "{i18n:your_key}" in cell content function.
5. See that the cells in column type display {i18n:your_key} instead of the translated value

**Expected behavior**
i18n strings are translated

**Possible solutions**
1. Make the translation service available
or
2. Automatically parse and translate {i18n:keys} in the output

**Comment by ChantsovaEkaterina** [comment]
Hello, @bbrenne 
Custom translation support for cell content functions was added in v.3.2.2.

**Comment by bbrenne** [comment]
After test, it seems also fixed in HTML Card content :).
