### ISSUE TITLE
[Feature Request] Improve <title></title> content by adding the entity name

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#4067]
Hello

Whille working with ThingsBoard, you often have many tabs open in your browser. Unfortunately their title is not precise enough to be meaningful. Let me illustrate with a more concrete example. Here I have 2 rule chains:

![image](https://user-images.githubusercontent.com/39315/107009038-c9006880-6794-11eb-9b12-17be6fc88911.png)

If I keep this list in a browser tab and open a new browser tab for each of these rule chains, I got: 

![image](https://user-images.githubusercontent.com/39315/107009131-e9302780-6794-11eb-841f-63fda6e9436e.png)

So it will be easier if `Thermostat` and `Root Rule Chain` names would also appear in the `<title></title>` of the page, because right now it's painful to find the right browser tab when you have a lot of them opened.

This is also true for almost any other entities like widgets in bundle, dashboards…

Thanks

**Comment by ssakharova** [comment]
Hello @Delapouite,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
