### ISSUE TITLE
Display Custom Alarm Messages Based on TB Selected Language

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4071]
Hello !
Please tell me how can I display alarm custom messages depending on Thingsboard selected language.
I need something like this :

if global_language='EN-us'
{alarm_message='THIS IS AN ALARM'}

if global_language='IT-it'
{alarm_message='ITALIAN TRANSLATION'}
and so on...

Thank You !

**Environment**
 ThingsBoard CE 3.2.1 
Windows 7 x64
Browser: Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
