### ISSUE TITLE
Get Dashboard Data using REST API

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#4072]
Can we get Dashboard Real time and Historical data using REST API.
How to get dashboard ID to be used in REST API

**Comment by ashvayka** [comment]
I suggest to open the Chrome debug console and navigate to the networks tab. Most of the requests to get the data are based on the WebSockets (not REST API), but they do have REST API analog. See this guide: https://stackoverflow.com/questions/43081107/how-do-you-inspect-websocket-traffic-with-chrome-developer-tools
