### ISSUE TITLE
[Bug] Can't delete imported widget from dashboard

### ISSUE THREAD

**Issue by garageeks** [thingsboard/thingsboard#4073]
**Describe the bug**
I have exported a customized card widget, and imported it back to create a new one. 
When I change the new widget, also the previous one is affected.
When I try to remove widgets from the dashboard, at least one card widget remains and it won't be deleted.

**Your Server Environment**

cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome
* Version 87

**To Reproduce**
1. Create new current value card widget
2. Modify it and assign a data source, then save
3. Export it
4. Import it from JSON file
5. Modify the newly added widget and replace the data source, then save

**Expected behavior**
the two distinct widgets operate independently

**Actual behavior**
After step 5, a third widget is created, same as the second one. If dashboard is saved, they are stacked on top of each other.
If you try to delete them, you can't. 

**Additional context**
I believe the exported widget contains a unique ID that it is not replaced with a new one after importing it.
Two widgets with same ID = boom!
It looks like it is not possible to change widget ID from the UI.

**Comment by corlinski** [comment]
I have the same issue

**Comment by Emil-S-Christiansen** [comment]
Has anybody found workaround for this? As I have the same issue.

**Comment by hallard** [comment]
Yes same widget ID on same dashboard has this issue, I remove ID line from JSON and import back, TB autocreate a new ID in this case and it works

**Comment by X1folta** [comment]
Does this still not have a more programmatic solution? I experience this since half a year and hope there is something to call to avoid the IDs being the same.

**Comment by pon0marev** [comment]
This behavior has been fixed in version 3.6.0.
If you simply need to copy a widget in one dashboard, use the copy function:
![image](https://github.com/user-attachments/assets/6f73b660-26e9-4b29-ac63-1784f0efc437)
