### ISSUE TITLE
http integration downlink converter

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#4074]
**Component**
 * Generic

**Description**
Hi, 

how can we invoke HTTP downlink converter though rule chain with node "Action - integration downlink"?
for now, in the rule chain, we get the device telemetry from the uplink and then invoke node "Action - integration downlink". 
but we get failure ton the integration downlink. 

Based on this guide https://thingsboard.io/docs/user-guide/integrations/#downlink-data-converter
is stated that 
"However, some integrations, like SigFox or generic HTTP integration are not able to push message asynchronously. These integrations, due to the nature of the underlying HTTP protocol, are only able to push downlink information synchronously in reply to the uplink message request. In this case, the last downlink message originated by rule engine will be stored in the queue until the new uplink message arrives for a particular device."

Can you help?

**Environment**
OS: Ubuntu
ThingsBoard: 3.2 PE
Browser: Chrome

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.

**Comment by filipcoja** [comment]
Has this changed? I still cant get the integration downlink to work when trying to make an external API call when something in the rule chain happens
