### ISSUE TITLE
How to call a server attribute value at cell style function or cell content function?

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#4077]
**Component**
 * UI

**Description**
I would like to know how can I call a server attribute value at cell style function or cell content function. For example, I want to check if value <= server attribute value to define a specific style or content format.

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.1 PE
 * Browser: Chrome and Edge

**Comment by ashvayka** [comment]
At the moment it is possible to add an attribute into the data source and then reference it using 'entity.attributeName' in the "cell content function". Unfortunately, this is inconvenient, since the attribute will be listed as a separate column that you can't easily hide. I am going to add a feature request to improve and document this for v3.3

**Comment by FreddyHunter** [comment]
Great Andrew, thanks.

Em qua., 10 de fev. de 2021 às 14:11, Andrew Shvayka <
notifications@github.com> escreveu:

**Comment by vvlladd28** [comment]
Hi @FreddyHunter
We are added this functional(#4235) in the master branch. Coming soon, we a release version with new functionality.

**Comment by KenSense** [comment]
Is something like this now possible In the timeseries table with pressureMinL2 as shared attribute?  
entity isn't present as parameter?
Look like the changes mentioned are added in v3.2.2 but that doesn't solve the request?

Cell style function: f(value, rowData, ctx)
if (value > entity.pressureMinL2) {
    return {
        "background-color": "#62c5e3",
        "color": "#19154a"
    };
}

**Comment by gcorthey** [comment]
> Hi @FreddyHunter We are added this functional(#4235) in the master branch. We will release a new version including this functionality by the end of the month.

Could you please refer me to the documentation where the call of entity attribute is used in the cell content function?

**Comment by gcorthey** [comment]
> 

Have you found the answer to your question?
