### ISSUE TITLE
can tenant user to see different devices

### ISSUE THREAD

**Issue by sdfantasy** [thingsboard/thingsboard#408]
current TB version，same tenant user can see  all the devices in this tenant.
Is there any plan to enable the tenant admin to config tenant user to see different devices(many to many relations)?

For example：Tenant A has two users(Not customs)：A1 and A2.  I want A1 to manage DeviceB1/B2/B3,and A2 to manage B4,B5,B6.
Current TB have SYS_ADMIN/'TENANT_ADMIN'/'CUSTOMER_USER' roles,but i think add a  'TENANT_USER' role is more appropriate.

**Comment by ssmaurya** [comment]
It would be easier if customer users had access similar to tenants so that main tenant can creat customer entities and assugn users. I have similar requirement

**Comment by vparomskiy** [comment]
Starting from ThingsBoard PE 2.3 you can assign different roles to different user groups. Here is a feature description:
https://thingsboard.io/docs/user-guide/rbac/
