### ISSUE TITLE
[Question] Why does Thingsboard use a comparatively old version of californium?

### ISSUE THREAD

**Issue by joe-pulse** [thingsboard/thingsboard#4080]
**COAP transport**

 * Generic

**Description**
Thingsboard is using Californium version 1.0.2. The current latest version is 2.6.1. Is there a particular reason for using such an old version, or is this simply a to-do?

**Environment**
All

**Comment by ashvayka** [comment]
We are going to update to new version of californium in ThingsBoard 3.3 (together with LwM2M support)
