### ISSUE TITLE
[Bug] Impossible to select text to copy it on dashboards (user-select: none)

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#4083]
Hello

Dashboards display valuable information that we often need to copy and paste to deal with it elsewhere.

Unfortunately, it seems impossible to select text from widgets with the mouse. This is due to several `user-select: none` CSS statements sprinkled in the DOM.
I believe this restriction is indeed useful when the edit mode is on, to be able to move widgets on the grid. But in visualization mode, it creates a lot of frustration to users that just want to extract bit of data by copy pasting.

Thanks

**Comment by LeoMorgan113** [comment]
Hi @Delapouite,

I will add your suggestion to our backlog(PROD-998), so it will be reviewed by our developers, but I can not provide you with an exact time frame on this.
