### ISSUE TITLE
[Question] RPC command: choose device in sendOneWayCommand / sendTwoWayCommand

### ISSUE THREAD

**Issue by hjlopezr** [thingsboard/thingsboard#4085]
**Component**
Widgets Development

 * UI
 
**Description**
How to send RPC command to especific device?
In this example ("RPC (Control) widget" section) not use IdDevice:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
In the past "angular" version used
sendTwoWayRpcCommand from deviceService.

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.2.1
 * Browser: N/A

Thanks!!

**Comment by hjlopezr** [comment]
Solved with:
https://github.com/thingsboard/thingsboard/issues/1623

**Comment by paolofrs** [comment]
Hi @hjlopezr 

Good to heard that! Anyway, can you provide more details? 

I've tried solution in #1623. I've created a **latest value** widget and added [this piece of code](https://github.com/thingsboard/thingsboard/issues/1623#issuecomment-743993310) in the `self.ctx.$scope.sendCommand = function(){ [HERE] }` following the [RPC widget development official guide](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#rpc-control-widget) but if does not work. The widget does not even render in the bottom right corner... If I switch to **Control Widget** widget type it renders but it does not receives any telemetry. 

What am I doing wrong? 

What I need is to send an **RPC OneWay Command**. Upon reception of this command the device upload a specific telemetry datasource that inform the user if the command was either properly executed of not. Thus, I need the RPC widget to be able to subscribe to datasources.  

My test setup:

  + server: tb-postgres 3.2.1 (docker image) on Ubuntu 18.04-LTS
  + client: Mozilla Firefox 87.0

**Comment by hjlopezr** [comment]
> Hi @hjlopezr
> 
> Good to heard that! Anyway, can you provide more details?
> 
> I've tried solution in #1623. I've created a **latest value** widget and added [this piece of code](https://github.com/thingsboard/thingsboard/issues/1623#issuecomment-743993310) in the `self.ctx.$scope.sendCommand = function(){ [HERE] }` following the [RPC widget development official guide](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#rpc-control-widget) but if does not work. The widget does not even render in the bottom right corner... If I switch to **Control Widget** widget type it renders but it does not receives any telemetry.
> 
> What am I doing wrong?
> 
> What I need is to send an **RPC OneWay Command**. Upon reception of this command the device upload a specific telemetry datasource that inform the user if the command was either properly executed of not. Thus, I need the RPC widget to be able to subscribe to datasources.
> 
> My test setup:
> 
> * server: tb-postgres 3.2.1 (docker image) on Ubuntu 18.04-LTS
> * client: Mozilla Firefox 87.0

Hi @paolofrs 
Can you share me the HTML & JS code? to review

**Comment by paolofrs** [comment]
Hi @hjlopezr 

tks for your help!  Here is the HTML:

~~~
<form #rpcForm="ngForm" (submit)="sendCommand()">
     <div class="mat-content mat-padding" fxLayout="raw" fxLayoutGap="5px">
         <button mat-raised-button color="primary" type="submit" >
             GO!
         </button>
     </div>
</form>
~~~

and the JS:

~~~
self.onInit = function() {
    
    self.ctx.$scope.sendCommand = function() {
        var rpcMethod = self.ctx.settings.rpcMethod;
        var rpcParams = self.ctx.settings.rpcParams;
        var timeOutSet = self.ctx.$scope.timeOutSet;
        var oneWayElseTwoWay =  true; // always TRUE with LoRa
        var timeout = 500; // set to 500 ms fixed

        // Get deviceid from first datasource
        var deviceid = self.ctx.datasources[0].entityId;
    
        // Get deviceService 
        var $injector = self.ctx.$scope.$injector;
        var $deviceservice = $injector.get(self.ctx.servicesMap.get('deviceService'));

        // Send oneWay RPC-Command, with requestBody like {"method": "methodname", "params": 1} 
        commandPromise  = $deviceservice.sendOneWayRpcCommand(deviceid, requestBody, { ignoreErrors: true  });
        
        commandPromise.subscribe(
            function success(response) {
                console.log("Command was successfully received by device. No response body because of one way command mode.");       
            },
            function fail(rejection) {
                console.log("Failed to send command to the device:");
                console.log(rejection);
            }
        );
    }    
}
~~~

If I use a **last value** widget type, the widget does not even render in the bottom right corner... If I switch to **Control Widget** type it renders but it returns this error when pressing the md-button associated with sendCommand() function (from browser debug console):

~~~
ERROR TypeError: self.ctx.datasources is undefined
~~~

**Comment by hjlopezr** [comment]
> Hi @hjlopezr
> 
> tks for your help! Here is the HTML:
> 
> ```
> <form #rpcForm="ngForm" (submit)="sendCommand()">
>      <div class="mat-content mat-padding" fxLayout="raw" fxLayoutGap="5px">
>          <button mat-raised-button color="primary" type="submit" >
>              GO!
>          </button>
>      </div>
> </form>
> ```
> 
> and the JS:
> 
> ```
> self.onInit = function() {
>     
>     self.ctx.$scope.sendCommand = function() {
>         var rpcMethod = self.ctx.settings.rpcMethod;
>         var rpcParams = self.ctx.settings.rpcParams;
>         var timeOutSet = self.ctx.$scope.timeOutSet;
>         var oneWayElseTwoWay =  true; // always TRUE with LoRa
>         var timeout = 500; // set to 500 ms fixed
> 
>         // Get deviceid from first datasource
>         var deviceid = self.ctx.datasources[0].entityId;
>     
>         // Get deviceService 
>         var $injector = self.ctx.$scope.$injector;
>         var $deviceservice = $injector.get(self.ctx.servicesMap.get('deviceService'));
> 
>         // Send oneWay RPC-Command, with requestBody like {"method": "methodname", "params": 1} 
>         commandPromise  = $deviceservice.sendOneWayRpcCommand(deviceid, requestBody, { ignoreErrors: true  });
>         
>         commandPromise.subscribe(
>             function success(response) {
>                 console.log("Command was successfully received by device. No response body because of one way command mode.");       
>             },
>             function fail(rejection) {
>                 console.log("Failed to send command to the device:");
>                 console.log(rejection);
>             }
>         );
>     }    
> }
> ```
> 
> If I use a **last value** widget type, the widget does not even render in the bottom right corner... If I switch to **Control Widget** type it renders but it returns this error when pressing the md-button associated with sendCommand() function (from browser debug console):
> 
> ```
> ERROR TypeError: self.ctx.datasources is undefined
> ```

In my TB render the button, but request Body is not defined (obviously, isn't defined in JS) with "last value".
Use try-catch in .onInit and console.log to debug the errors.

"Control Widget" don't have "datasources" to get the information.
Use console.log(self-ctx) in every widget type to know the data sources available

Waiting for your news.

**Comment by paolofrs** [comment]
Hi @hjlopezr 

yeah, thank you so so so much!!! The `try {} cath {}` helped a lot tracing down my faults.

First, as you correctly noticed, I've forgot to define the `requestBody` function. Here is the correct JS: 

~~~
self.onInit = function() {

    console.log(self.ctx);

    try {  self.ctx.$scope.sendCommand = function() {
        // string that identifies the method to call in the device 
        var rpcMethod = self.ctx.settings.rpcMethod;
        // string version of the JSON object to send to the device
        var rpcParams = self.ctx.settings.rpcParams;
        // put them toghter
        var requestBody = {"method": rpcMethod, "params": rpcParams};
        //var timeOutSet = self.ctx.$scope.timeOutSet;
        var oneWayElseTwoWay =  true; // always TRUE with LoRa
        var timeout = 500; // set to 500 ms fixed

        // Get deviceid from first datasource
        var deviceid = self.ctx.datasources[0].entityId;
        
        console.log("deviceid: ")
        console.log(deviceid);
    
        // Get deviceService 
        var $injector = self.ctx.$scope.$injector;
        var $deviceservice = $injector.get(self.ctx.servicesMap.get('deviceService'));
        
        console.log("deviceService: ")
        console.log($deviceservice);

        // Send oneWay RPC-Command, with requestBody like {"method": "methodname", "params": 1} 
        commandPromise  = $deviceservice.sendOneWayRpcCommand(deviceid, requestBody, { ignoreErrors: true  });
        
            commandPromise.subscribe(
                function success(response) {
                    console.log("Command was successfully received by device. No response body because of one way command mode.");       
                },
                function fail(rejection) {
                    console.log("Failed to send command to the device:");
                    console.log(rejection);
                }
            );
        }
    } catch { console.error(error); }
}
~~~

Secondly, my button wasn't rendering because since it is a **lastvalue** widget object, it is supposed to be bound to a data source (press edit button -> in the bottom right corner, edit widget -> fill the form in the "data" tab). I selected the only available "function" source. 

But at this point I was still receiving errors at `sendOneWayRpcCommand()` execution because the HTTP request generates to a missing deviceid: 

~~~
Object { headers: {…}, status: 404, statusText: "OK", url: "http://localhost:8080/api/plugins/rpc/oneway/13814000-1dd2-11b2-8080-808080808080", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://localhost:8080/api/plugins/rpc/oneway/13814000-1dd2-11b2-8080-808080808080: 404 OK", error: "Device with requested id wasn't found!" }
5.95ab3e549a861f2f8075.js line 1 > Function:44:29
~~~

But this last is a "fake" error: using the widget with a **connected device** as data source (i.e. placing the widget in a real dashboard) does not return any 404 ERROR. 

The strange thing is, if you instance the widget in a dashboard while the device is not seen as "connected", the TB instantiates the widget as and `rpc` type instead of a `lastvalue` type (returning the `ERROR TypeError: self.ctx.datasources is undefined` when pressing the button). But maybe it's just me doing another mistake... 

I've been stuck with this issue for a long time, thank you very much!

**Comment by hjlopezr** [comment]
> Hi @hjlopezr
> 
> yeah, thank you so so so much!!! The `try {} cath {}` helped a lot tracing down my faults.
> 
> First, as you correctly noticed, I've forgot to define the `requestBody` function. Here is the correct JS:
> 
> ```
> self.onInit = function() {
> 
>     console.log(self.ctx);
> 
>     try {  self.ctx.$scope.sendCommand = function() {
>         // string that identifies the method to call in the device 
>         var rpcMethod = self.ctx.settings.rpcMethod;
>         // string version of the JSON object to send to the device
>         var rpcParams = self.ctx.settings.rpcParams;
>         // put them toghter
>         var requestBody = {"method": rpcMethod, "params": rpcParams};
>         //var timeOutSet = self.ctx.$scope.timeOutSet;
>         var oneWayElseTwoWay =  true; // always TRUE with LoRa
>         var timeout = 500; // set to 500 ms fixed
> 
>         // Get deviceid from first datasource
>         var deviceid = self.ctx.datasources[0].entityId;
>         
>         console.log("deviceid: ")
>         console.log(deviceid);
>     
>         // Get deviceService 
>         var $injector = self.ctx.$scope.$injector;
>         var $deviceservice = $injector.get(self.ctx.servicesMap.get('deviceService'));
>         
>         console.log("deviceService: ")
>         console.log($deviceservice);
> 
>         // Send oneWay RPC-Command, with requestBody like {"method": "methodname", "params": 1} 
>         commandPromise  = $deviceservice.sendOneWayRpcCommand(deviceid, requestBody, { ignoreErrors: true  });
>         
>             commandPromise.subscribe(
>                 function success(response) {
>                     console.log("Command was successfully received by device. No response body because of one way command mode.");       
>                 },
>                 function fail(rejection) {
>                     console.log("Failed to send command to the device:");
>                     console.log(rejection);
>                 }
>             );
>         }
>     } catch { console.error(error); }
> }
> ```
> 
> Secondly, my button wasn't rendering because since it is a **lastvalue** widget object, it is supposed to be bound to a data source (press edit button -> in the bottom right corner, edit widget -> fill the form in the "data" tab). I selected the only available "function" source.
> 
> But at this point I was still receiving errors at `sendOneWayRpcCommand()` execution because the HTTP request generates to a missing deviceid:
> 
> ```
> Object { headers: {…}, status: 404, statusText: "OK", url: "http://localhost:8080/api/plugins/rpc/oneway/13814000-1dd2-11b2-8080-808080808080", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://localhost:8080/api/plugins/rpc/oneway/13814000-1dd2-11b2-8080-808080808080: 404 OK", error: "Device with requested id wasn't found!" }
> 5.95ab3e549a861f2f8075.js line 1 > Function:44:29
> ```
> 
> But this last is a "fake" error: using the widget with a **connected device** as data source (i.e. placing the widget in a real dashboard) does not return any 404 ERROR.
> 
> The strange thing is, if you instance the widget in a dashboard while the device is not seen as "connected", the TB instantiates the widget as and `rpc` type instead of a `lastvalue` type (returning the `ERROR TypeError: self.ctx.datasources is undefined` when pressing the button). But maybe it's just me doing another mistake...
> 
> I've been stuck with this issue for a long time, thank you very much!

@paolofrs share the output of the console navigator, to help you. I test in my TB with your new code and run without problems.

**Comment by Skyflowed** [comment]
I finally found a solution :

Create a new custom widget with type : TIME SERIES (it won't work with others types...)

Put the following code into each section :

JS :
self.onInit = function() {
    console.log("NON RPC TYPE");
    console.log(self.ctx);
    self.ctx.$scope.sendCommand = function() {
        var rpcMethod = self.ctx.settings.rpcMethod;
        var selected_command = document.getElementById("command").value;
        console.log(document.getElementById("command").value);
        var rpcParams = selected_command == "on" ? "true" : "false";
        var timeout = self.ctx.settings.requestTimeout;
        var oneWayElseTwoWay = self.ctx.settings.oneWayElseTwoWay ? true : false;
        var requestBody = {"method": rpcMethod, "params": rpcParams};
        var deviceIds = [];
        // Get deviceService 
        var $injector = self.ctx.$scope.$injector;
        var $deviceservice = $injector.get(self.ctx.servicesMap.get('deviceService'));
        for(i=0;i<self.ctx.datasources.length;i++){
            deviceIds.push(self.ctx.datasources[i].entityId);
        }
        deviceIds.forEach(element => {
             var commandObservable;
            if (oneWayElseTwoWay) {
                // Send oneWay RPC-Command, with requestBody like {"method": "methodname", "params": 1} 
                commandObservable  = $deviceservice.sendOneWayRpcCommand(element, requestBody, { ignoreErrors: true  });
            } else {
                commandObservable = self.ctx.controlApi.sendTwoWayCommand(element, requestBody, timeout);
            }
            commandObservable.subscribe(
                function (response) {
                    console.log("response");
                    if (oneWayElseTwoWay) {
                        self.ctx.$scope.rpcCommandResponse = "Command was successfully received by device.<br> No response body because of one way command mode.";
                    } else {
                        self.ctx.$scope.rpcCommandResponse = "Response from device:<br>";                    
                        self.ctx.$scope.rpcCommandResponse += JSON.stringify(response, undefined, 2);
                    }
                    self.ctx.detectChanges();
                },
                function (rejection) {
                    self.ctx.$scope.rpcCommandResponse = "Failed to send command to the device:<br>"
                    self.ctx.$scope.rpcCommandResponse += "Status: " + rejection.status + "<br>";
                    self.ctx.$scope.rpcCommandResponse += "Status text: '" + rejection.statusText + "'";
                    self.ctx.detectChanges();
                }
                
            );
        })
        
       
    }
}

HTML : 

<form #rpcForm="ngForm" (submit)="sendCommand()">
     <center>
        <label for="command">Command type :</label><br>
        <select name="command" id="command">
            <option value="on">ON</option>
            <option value="off">OFF</option>
        </select><br><br>
        <button type = submit>SEND RPC COMMAND TO DEVICE GROUP</button><br><br>
     </center>
        <div>
            <center>
                <label>Command response :</label>
                <div style="width: 100%; height: 100px; border: solid 2px gray" [innerHTML]="rpcCommandResponse">
          </div>
          </center>
        </div>
</form>

SETTINGS SCHEMA : 

{
    "schema": {
        "type": "object",
        "title": "Settings",
        "properties": {
            "oneWayElseTwoWay": {
                "title": "Is One Way Command",
                "type": "boolean",
                "default": true
            },
            "requestTimeout": {
                "title": "RPC request timeout",
                "type": "number",
                "default": 500
            },
            "rpcMethod": {
                "title": "rpcMethod",
![Thingsboard_RPC_to_multiple_devices](https://user-images.githubusercontent.com/62890017/119821564-ff542600-bef2-11eb-8260-0ee7d499916f.JPG)


                "type" : "string",
                "default" : "setValue"
            }
        },
        "required": []
    },
    "form": [
        "oneWayElseTwoWay",
        "requestTimeout",
        "rpcMethod"
    ]
}
