### ISSUE TITLE
MQTT Sparkplug payload decoder to JSON? 

### ISSUE THREAD

**Issue by me1121** [thingsboard/thingsboard#4086]
**Component**
Generic

**Description**
I'm connecting MQTT gateway to a cloud MQTT broker (Hive MQ) and from the broker to ThingsBoard MQTT integration. The issue I have is that the MQTT gateway is publishing the message payload in MQTT Sparkplug format (binary) but Thingsboard Uplink data converter accepts only payloads in JSON, Text, or Binary(Base64) format, so the incoming message payload is not readable.
How to decode the incoming payload (Sparkplug binary format) to JSON to be accepted by ThingsBoard uplink converter? (The same issue expected to be with the Downlink Converter) 

**Environment**
 * ThingsBoard: PE deployed on AWS EC2 instance
 * OS:  Wundows 10
 * Browser: Chrome

**Comment by bodiroga** [comment]
It would be really awesome if Sparkplug B support could be added as an integration 😉

**Comment by ashvayka** [comment]
Hi @bodiroga and @me1121 . Please clarify few points to help prioritize this.

1. The Sparkplug format (binary) is basically the Protobuf payload according to this [schema](https://github.com/eclipse/kura/blob/develop/kura/org.eclipse.kura.core.cloud/src/main/protobuf/kurapayload.proto), right?
2. Please vote for this issue with thumb up to prioritize.

**Comment by bodiroga** [comment]
Hi @ashvayka!

As far as I know, there are two versions of the protocol:

- Sparkplug A: the old version of the protocol, which uses the Protobuf payload schema you have linked (Kura).
- Sparkplug B: latest version of the protocol, fully described [here](https://cirrus-link.com/mqtt-sparkplug-tahu/). The reference implementation of the protocol is developed by the [Eclipse Tahu project](https://github.com/eclipse/tahu). The complete specificacion is defined [here](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf) and the payload schema for this version can be found in the following link: https://github.com/eclipse/tahu/blob/master/sparkplug_b/sparkplug_b.proto

Knowing that the protocol defines the whole lifecycle of each device (birth, death, telemetry data, commands...), I would love if a Sparkplug integration could be developed that automatically discovers and adds the devices, without much user intervention (define the broker connection and not much else).

Thanks for your work and support and best regards,

Aitor

**Comment by HaydenGriffin** [comment]
Sparkplug B looks really interesting to me, would have huge merit being included in TB. Also in RPC for both host to device, and device to host.

**Comment by ammaree** [comment]
+1 for SparkPlug B.
Support of GPB in telemetry and RPC (both device <> host directions) payload is a must.
Support for a GPB serialised payload containing an array of telemetry values, say 60 values for a specific (single) sensor taken at 1 minute intervals, buffered at the EoN device and uploaded to TB every hour.
Payload would include a timestamp and interval period between telemetry values allowing host to accurately timestamp each value into the TSDB.

**Comment by Civilduino** [comment]
https://github.com/hashmapinc/Tempus/issues/64
Is this already implemented?
