### ISSUE TITLE
[Bug] Assets are invisible 

### ISSUE THREAD

**Issue by LukasPeer** [thingsboard/thingsboard#4087]
**Describe the bug**
Multiple Assets are invisble in the Asset Overview. They exist (Asset Limit is amount of Asset seen + Missing Assets) and are in realtion to other assets.

**Your Server Environment**
* own setup
  * 4 Core Server with 8GB of Ram
  * ThingsBoard Version: v3.2.1
  * Ubuntu Server 18.04 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10 / Raspberry Pi OS 64bit
* Browser Firefox, Edge, Chrome with cleared Cache
* Version newest for each

**Your Device**

* Connectivity
  * Integration: HTTP
* Device vendor and model
Does not matter here. Asset is created by "create relation" Node in RuleChain.

**To Reproduce**
No real Idea. It happend after i deleted them once and they were created again.

**Expected behavior**
All Assets should be seen in the Overview.

**Screenshots**
First you can see the overview. I censored unrelated entities to protect the privacy. 
![overview](https://user-images.githubusercontent.com/7852555/107613484-b5e41180-6c48-11eb-9c8e-af09bdcc7f1c.PNG)

Here you can see the relation from a asset which can be seen from the overview.
![connection to wesel](https://user-images.githubusercontent.com/7852555/107613483-b5e41180-6c48-11eb-8aa6-ae1d8b251a80.PNG)

**Comment by LuPe97** [comment]
Adding Information.
![create asset](https://user-images.githubusercontent.com/7852555/107622852-c308fc80-6c58-11eb-8b81-b6cecd58c61d.PNG)

**Comment by RondoRonaldo** [comment]
Hi,

Most likely, if you used a default data converter, all entities(devices, assets) were created under predefined customer and an entity group: 
![image](https://user-images.githubusercontent.com/43723966/121585539-61587380-ca3b-11eb-8557-b1f4af8b80a9.png)

So you may check your customers whether one of them has these entities. 

You can also find in what exact customer an entity is located by using, for instance, several requests from Swagger-UI like this: 
https://thingsboard.cloud/swagger-ui.html#!/asset-controller/getAssetByIdUsingGET

A response will give you information on where a requested asset is located.
