### ISSUE TITLE
With CoAP, the server-side RPC always "time out"!

### ISSUE THREAD

**Issue by zhw618** [thingsboard/thingsboard#409]
I deployed thingsboard  platform (v1.3.1) on CentOS 7 using the linux rpm file.  

My device ,as a CoAP client, has connected to my thingsboard platform.
The telemetry data can be sent, and thingsboard can received it correctly.
Everythings is OK, for now. 

Then I try to test the feature of  "server-side RPC". 
Firstly, send a GET request of CoAP with observe flag to subscript.
Secondly, I send a RPC request with my http client from server-side, 
and the device received the request immediately, as: 
     {"id":61,"method":"0200","params":"0011"}
At this time, all looks like still rather fine 👍 

Then the device needs to reply a message in 20s, and I indeed finished it.
but the trouble comes: the server-side RPC request always return "time out"!

I sent POST to the URL :  coap://122.155.218.51:5683/api/v1/6502/rpc/61 
(My $Access_Token is 6502 ) with the payload of:  {"id":61,"method":"0200","params":"0011"} 
in 20s, server-side shows: time out.  :-(
I changed the payload of respone message and tried many times, such as: 
 {"id":"62","method":"0200","params":"0011"}  and {"method":"0200","params":"0011"}
and {"result":"ok"} and ...... server-side RPC always "time out".

Please help me. Is there something  wrong with my action?  Or it's perhaps a bug?
Thank you very much!

ps: I found another issue:  in the received RPC request json: {"id":61,...},
     the "id" is a number, but not a string as described in document.
----------------------------------------------------------------------------------
Further, I have tried the MQTT protocol for comparison:
I subscript the topic of : v1/devices/me/rpc/request/+
and the device received the RPC request json: {"method":"0200","params":"0011"}
via the topic of : v1/devices/me/rpc/request/65.
Then the reply message of:  {"method":"0200","params":"0011"} 
was sent to the topic of: v1/devices/me/rpc/response/65, 
and the server-side RPC immediately end up and returned the json.

But what's  wrong with CoAP?  Need help, thanks very much.

**Comment by mp-loki** [comment]
Did you try setting coap.timeout in thingsboard.yml? The default value is 10 seconds

**Comment by zhw618** [comment]
Generally，the reply was sent by my device in 3 sec. after reply, server-side http rpc request still wait...wait...then get a response of "time out".

so I donot think it's coap.timeout 's problem.
Thank you all the same. @mp-loki
And did you have the same issue with you Thingsboard plantform?

**Comment by zhw618** [comment]
Is there other sugguestion? 
This problem has been bothering me for a long time. Thanks

**Comment by ashvayka** [comment]
is the same payload/or similar works with mqtt client?

**Comment by zhw618** [comment]
with same payload/ same works, the mqtt client works very well.

I have  done the same works with platform of  http://demo.thingsboard.io
the same results: mqtt client works well, but not CoAP .

ps: I use the Cu plugin of firefox as CoAP client, and the client can send telegram payload successfully, can received the rpc json strings successfully, but server-side have no responses.
 
Please help to research it.  Thanks.

**Comment by vparomskiy** [comment]
@zhw618 please upgrade to the latest version, I've verified that RPC over CoAP transport works as expected.
