### ISSUE TITLE
[Question] Is it possible to get TB server attribute from ESP8266?

### ISSUE THREAD

**Issue by caiofrota** [thingsboard/thingsboard#4090]
**Description**
I have server attributes and I'd like to read these values from my ESP8266.
I tried with RPC but I have to change the RPC code every time I have a new value.

**Comment by vvlladd28** [comment]
Hi @caiofrota,
You need to used shared attributes.

**Comment by caiofrota** [comment]
> Hi @caiofrota,
> You need to used shared attributes.

Thank you for answering! Do you have an example?

**Comment by vvlladd28** [comment]
Sorry, but I not have example
