### ISSUE TITLE
[Question] Is it possible to add multiple devices with the same X.509 certificate?

### ISSUE THREAD

**Issue by bilirubina** [thingsboard/thingsboard#4093]
**Component**

 * Generic

**Description**
This has been issued here #662. I couldn't find a clear answer, and the issue was old.

1. Do I have to manually run `client.keygen.sh` everytime I add a new device, and manually add its certificate on the Manage Credentials section of the platform, or can I have a single certificate valid for hundreds of devices? If I am a producer and mass produce devices, is it still feasible to use a solution like ThingsBoard?

2. Can I specify to use X.509 certificate by default as I add a new device, instead of a token? Can I add a new device which uses x.509 authentication from command line, instead of the GUI?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
