### ISSUE TITLE
[Question] Adding custom data keys from GUI or CLI

### ISSUE THREAD

**Issue by bilirubina** [thingsboard/thingsboard#4094]
**Component**

**Description**
I noticed that data keys are only available if I publish them from the device. Only a small set are available by default (_picture_).

- Is this the only way to have data keys available? Can I create data keys (i.e. water_level) from the server, both from GUI and from CLI, or is it mandatory that the device sends them first, like this:
`mosquitto_pub -d -h "localhost" -t "v1/devices/me/attributes" -u "TOKEN" -m "{"water_level": "3.5"}"`
![datakeys](https://user-images.githubusercontent.com/78793369/107761420-9eca2000-6d2b-11eb-94c4-4ca7d4e4c1a9.png)

**Comment by PovitruliaV** [comment]
Hi @bilirubina,
The data key defines the time series, attribute, or entity field you want to use in the widget. Data critical definition consists of type (time series, attribute of entity field) and the actual key.

A list of available attribute keys is a list of all client, server, and shared [attributes](https://thingsboard.io/docs/user-guide/attributes/) of your device or other entity.

The list of available time series keys depends on what time series data you devices [report](https://thingsboard.io/docs/user-guide/telemetry/#device-telemetry-upload-api) to ThingsBoard or what time series data you have saved via rule engine or [REST API](https://thingsboard.io/docs/reference/rest-api/).
The date keys must exist on your device for later use in widgets. Telemetry always carries the current values collected by your devices. But as an option, you can create server attributes in your device in GUI.
Regards,
