### ISSUE TITLE
[Question] Getting customer id from the rule chain

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#4099]
Hi, 
I'd like to get to Customer Id from the rule chain flow. I'm able to get, for example, the customer name by "customer details" node but I didn't find any node nor any example code about the customer id. 

Thanks in advance!

**Comment by vvlladd28** [comment]
Hi @shaphiro,
You cannot explicitly obtain a customer ID. Use the rule node ['Change Originator'](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator) in parameters 'Originators source' -  'Customer' to solve this problem.

**Comment by shaphiro** [comment]
Hi @vvlladd28, I have tried your solution but it seems that this node has no effects. In the output message the entity type is correctly set to "Customer" Entity type but the are no customer Id in the metadata. See
![Schermata da 2021-02-23 08-53-30](https://user-images.githubusercontent.com/9846064/108815586-fe8abb80-75b4-11eb-9831-8e74c9d0a6b4.png)
![Schermata da 2021-02-23 08-53-10](https://user-images.githubusercontent.com/9846064/108815597-0185ac00-75b5-11eb-99d6-166de698de45.png)

 attachments.

Thanks in advance.

**Comment by shaphiro** [comment]
Hi @vvlladd28 problem solved! Thanks!
