### ISSUE TITLE
Built issue - thingsboard 1.3

### ISSUE THREAD

**Issue by logivity** [thingsboard/thingsboard#410]
I tried to build Thingsboard v1.3.1 via github and the built was successful but when I run http://localhost:8080/login following error shows up in browser.

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Fri Nov 10 00:30:44 EST 2017
> There was an unexpected error (type=Not Found, status=404).
> No message available

Thins only happens with maven built after changing svg logo in ui/src/svg (names were kept same).
When I build without making these changes everything works fine with checkout version 1.3
When I install with **https://github.com/thingsboard/thingsboard/releases/download/v1.3.1/thingsboard-1.3.1.deb** it runs completely fine too.

Also I am using Cassandra as database.
Attached are complete install and thingsboard log.
[install.log](https://github.com/thingsboard/thingsboard/files/1462990/install.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/1462991/thingsboard.log)

Please advise

**Comment by logivity** [comment]
Alsi I am using Cassandra as database.

**Comment by logivity** [comment]
[maven built log](https://github.com/thingsboard/thingsboard/files/1462387/maven.built.log)

Attached is complete log i got in Ubuntu 16.04 terminal after running "mvn clean install".

**Comment by logivity** [comment]
Update: I found the issue, it is because of XML code in svg file and if you convert text to path in svg file. The server runs completely fine but now svg logo does not show up after running http://localhost:8080/login .

**Comment by logivity** [comment]
Update: Issue reolved. SVG file if has XML callouts such as text etc will not work well with thingsboard build.

**Comment by souhaiebtar** [comment]
@logivity  what program(or what settings) have you used to generate svg without xml callouts ?

**Comment by souhaiebtar** [comment]
for me changing the logo was no problem, i just used online-convert.com to convert png to svg than to make sure, i opened it and removed the first line ( the xml tag `<xml..>`), now about logo plus text, to make simple don't use illustrator, i tried everything and still nothing, the solution for me was to use Inkscape to create the text, but the only way that worked for me is to create every character seperately than transform every one into path ( using Path -> Object to path menu),  for example  let say the text is `ABC`, to make it work i created a text object  `A` than transform it to path, the same to `B` than `C`, after that i resized them as i wish and stuck them, after that i saved to svg format than opened the file using a text editor to remove the `<xml...>` tag;  i tried to create a single text object `ABC` than tranformed it to path, but thingsboard always show the same error, the only way it worked for me is as i described befor
