### ISSUE TITLE
[Question] Using "attributes substitution" in Alarm details section

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#4102]
There are several days that I am playing with alarm settings in the Device Profile section (**Community edition**). I have defined a lot of dynamic alarms based on "source attributes". Alarms work but I can't use the source attributes in the "details section" in order to create a more complex dynamic message.

For example if I define a a server attribute "maxValue" for a particular device, I can use successfully this attribute in the alarm conditions, but, if I type ${maxValue} or ${ss_maxValue} in the alarm details section it doesn't work. In the details section I can use for example the timeseries key ${temperature} but no other attributes.

How can I accomplish this?

Thanks!

**Comment by bymzy** [comment]
i am quite confused about this problem too

**Comment by angovil** [comment]
i am also facing similar issue. Is this a bug or currently not supported feature to access attributes in details section

**Comment by mykhailokornieiev** [comment]
Hi. Indeed, there is no such a possibility. There is a ticket in backlog for our developers to add such feature. Please follow [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
