### ISSUE TITLE
[Question] What is recommended Kubernetes nodes number to deploying TB for production?

### ISSUE THREAD

**Issue by ehsanmqn** [thingsboard/thingsboard#4103]
**Component**

 * Installation

**Description**
I want to deploy TB with Kubernetes cluster. Before starting, I want to know what is recommended architecture, resources and kubernetes cluster nodes number for this purpose?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 2.3
 * Browser: Chrome

**Comment by trypzz** [comment]
Hello, @ehsanmqn 

You can visit this link https://thingsboard.io/docs/reference/iot-platform-deployment-scenarios/ to get information about your question.

On this KB page, you can find some examples for requests per second to thingboard platform and requirements for systems.
