### ISSUE TITLE
[Question] Navigate to other dashboard state showing device details (from alias filter type 'Entity list').

### ISSUE THREAD

**Issue by maaikez** [thingsboard/thingsboard#4105]
**Component**
 * UI

**Description**
I followed the dashboard development guide tutorial:
https://www.youtube.com/watch?v=mqWEGs1Z2BQ.
Everything is working fine when I do everything the same as in the tutorial. I did not add a map and only 1 sensor type (temperature), but it works as expected. 

I have some devices with a temperature sensor and I added all devices to the same Asset. 

I now want to go to a dashboard state from an 'Entities' table with multiple devices (Alias filter type is either an Entity list, or 'Device search query' from Asset with the correct device types, see below). 
![alias2](https://user-images.githubusercontent.com/4672351/107958576-81eb5200-6fa2-11eb-889a-6cbbd68e150a.png)
![alias](https://user-images.githubusercontent.com/4672351/107958578-84e64280-6fa2-11eb-8664-515da94df4de.png)

The table looks like this:
![table](https://user-images.githubusercontent.com/4672351/107958696-ae06d300-6fa2-11eb-95ef-0c79aed93719.png)

And the action:
![action](https://user-images.githubusercontent.com/4672351/107958758-c7a81a80-6fa2-11eb-8b2e-6ed71114beff.png)

The dashboard I want to go to looks like this:
![dashboardstate](https://user-images.githubusercontent.com/4672351/107958881-f1f9d800-6fa2-11eb-9dba-fdec16c0d001.png)

When clicking on the device in the list, I indeed go to the 'tempstate_from_device' dashboard state. However, the chart says 'no data to display on widget'. There is also no device name on top of the screen (where the dashboard name is). 
![dashboard_notworking](https://user-images.githubusercontent.com/4672351/107959681-012d5580-6fa4-11eb-94fc-246d89ee1cd0.png)

The chart data:
![chart_data](https://user-images.githubusercontent.com/4672351/107959425-b0b5f800-6fa3-11eb-9c1e-bd1c613789b2.png)
 
Where alias 'selected sensor' is:
![selectedsensor](https://user-images.githubusercontent.com/4672351/107959499-cd523000-6fa3-11eb-94cd-2a895320f654.png)

So, why am I not seeing any data? What is the difference with the other method and what should I change to do it this way? 

**Environment**

 * OS:  The ThingsBoard cassandra docker container
 * ThingsBoard: 3.2.1
 * Browser: Firefox on Linux.

(By the way, when following the youtube video, so with an asset, then click on the asset to go the the next state with the devices, then click on a device to show a temperature chart, my chart looks like this:
![dashboard_tmp](https://user-images.githubusercontent.com/4672351/107959954-54070d00-6fa4-11eb-9f30-5e2f24083e79.png))

**Comment by ashvayka** [comment]
I can see that the new widget displays data for the last minute. Maybe you need to increase the time interval to something like last day? If not - please try to reproduce this on demo.thingsboard.io or thingsboard.cloud and provide your login (without password). We will check and let you know what is wrong into this ticket..

**Comment by maaikez** [comment]
Ah yes, I changed that, but that did not make a difference. I must have something forgotten somewhere. I'll try on the demo or cloud later.

**Comment by maaikez** [comment]
Of course it works on the demo thingsboard. 
So I did everything the same, I really don't know what is wrong on my own dashboard. Maybe I have things with the same name or something I am not aware of. Sorry for bothering (but unfortunately I still don't understand :().
