### ISSUE TITLE
[Bug] Problem to sent Telemetry data to Thingsboard 3.2.1 installed on our cloud server.

### ISSUE THREAD

**Issue by Easyproto** [thingsboard/thingsboard#4108]
**Describe the bug**
I can't send telemetry data to Thingsboard CE installed on a cloud server with Linux.

**Your Server Environment**

* demo.thingsboard.io
* own setup
  * Cloud server using 2VCPU , 4GB Ram
  * ThingsBoard Version 3.2.1 (but tested also with previous version 3.2.0)
  * Linux Debian 10 64 bit (Busters), proxy NGINX , CERTBOT 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: MacOS Big Sur
* Browser ChromeVersion 
* Version 88.0.4324.150 (Official Build) (x86_64

**Your Device**
* Connectivity
  * HTTP
* Postman or Curl 

**To Reproduce**
Simply I followed your instruction inside Get Started->Connect Device. So:
1. Create a new device using default parameter.
2. Take device token from inside button "take access token".
3. Copy this token inside url POST as for your instruction : https://our_dns_name/api/v1/DAXG78EAL1xFEM52oGCh/telemetry
4. Execute POST
5. Check "latest telemetry" inside device.

**Expected behavior**
My expectation is to view the telemetry data sent inside Latest Telemetry.
Instead "latest telemetry" remain empty.

**Screenshots**
* Created a new device by selecting default device profile.
 
![image](https://user-images.githubusercontent.com/22988436/107980343-6000c800-6fc0-11eb-8060-bf56a1a37c0d.png)
*Created a default profile using Root Rule Chan 

![image](https://user-images.githubusercontent.com/22988436/107980500-ace49e80-6fc0-11eb-9047-c88b0d5efcb5.png)

*Created a Root Rule Chain
![image](https://user-images.githubusercontent.com/22988436/107980744-1369bc80-6fc1-11eb-854d-26aa7430ad03.png)

* Enable the debug in "save timeseries" and send telemetry data using Postman. Data is correctly received a processed due to message Success.
![image](https://user-images.githubusercontent.com/22988436/107981190-ed90e780-6fc1-11eb-9c6d-3cfb79940e28.png)

* Checked "latest telemetry" inside device but unfortunatly the table is empty alse if I try to reload page.
![image](https://user-images.githubusercontent.com/22988436/107981367-3a74be00-6fc2-11eb-9183-9bfd407029a3.png)

*To be sure I used pgAdmin4 to read database and this is the result:
![image](https://user-images.githubusercontent.com/22988436/107981745-f6ce8400-6fc2-11eb-8968-72ddd4700174.png)
By checking the dictionary i discovered that 25 are message ok (and are 2 because I sent 2 POST) and 26/27/28 are falt (all 0 so no  errors).

*I have also checked the API usage windows but seems to be freezed....
![image](https://user-images.githubusercontent.com/22988436/107981905-575dc100-6fc3-11eb-9bde-ab8cd67720a8.png)

* To be sure about POST message I have tried to send message to demo.thingsboard.io where I created an account and created a new device like before explained. All is OK so HTTP POST message is OK
![image](https://user-images.githubusercontent.com/22988436/107982124-c804dd80-6fc3-11eb-88cc-b51363a5b152.png)

**Additional context**
I've tried this procedure for Thingsboard 3.2.0 and 3.2.1 but without succes.
I don't know how Thingsbord is structured inside but seem sto bue a sort of disconnection between data in the database e Thingsboard UI. I don't know if you use a scheduler to refresh dynamically data but seem that this scheduler doesn't function in my installation. Data remain in the database but no one takes this data to be displayed.
The strannge is that all Rule Chains seems to be OK but all stops after datas are stored.
It's clear that the Rule Chain is activated; or best triggered, by the post command so doesn't need a scheduler, but probably Dashboard or latest telemetry needs a sort of sync scheduled by a tiimer...

Where I made some mistake in my consideration ?
I forgot something that must be enabled at config level ?
Any suggestions ? 
You use some particular localhost port that need to be enabled? (at the moment I don't use any type of firewall so all is opened).

For me is a big problem that I can't understand also because, in my develop, I left this part as last assuming that is the base of thingsboard and must function easily!! Instead I have had less problem using API (to create tenat, user, customer or device) than using telemetry data command....

Please let me know I'm in trouble...
Thanks
Giacomo

**Comment by ashvayka** [comment]
What is the result of your POST? Is it 200OK? I suspect you have not set up HTTPS correctly, because you use custom setup (Linux Debian 10 64 bit (Busters), proxy NGINX , CERTBOT). Try to set up HTTPS using our proxy instructions (available in the post-install steps). or try to post using HTTP and not HTTPS to make sure this is not the case. Anyway, it is important to know the result of your POST request.

**Comment by Easyproto** [comment]
Hi, thanks for your fast reply.

The answer is 200Ok without any body.
I’ve also tried with a curl in localhost, avoiding the use of proxy, but nothing.

My question is : why all processo of telemetry data is correct and is stored in database but not the visualization?
Why NGINX could be a problem if data is received ?
How explained in my post, the system seems to be frezed . Seems to be a problem in the scheduler that refresh screen...
My question is : UI interface is refreshed using a scheduler that for some reason could be frozen?
There is a way to debug what happen after the correct reception of a telemetry data, for example at the end of rule chain after telemetry save ?

I’m pretty sure that NGINX isn’t the problem .

Thanks


Giacomo Cesari
Email: info@easyproto.it
Skype: giacomo.cesari68

**Comment by Easyproto** [comment]
Hi All

I found the problem by searching in internet the typical NGINX configuration.
In this link https://gist.github.com/mfalkvidd/3920bd5035806a583b5c1e20eaddabae is reported a typical reverse proxy configuration.

My old configuration was :
location / {
 proxy_pass http://localhost:8080/;
 proxy_set_header Host $host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-Host $host;
 proxy_set_header X-Forwarded-Server $host;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 }

The new is :
    location / {
            proxy_pass http://localhost:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
    }

Now all is ok and also the API usage window...
I think that you should add this help in installation documentation to avoid future equal problem..

Now I will continue to implemetation
Thanks a lots for support.

Giacomo
