### ISSUE TITLE
Running Unit Tests - Throwing "Schema-validation: missing table [admin_settings]"

### ISSUE THREAD

**Issue by periatrubikx** [thingsboard/thingsboard#4109]
Unit Test

Running the 3.3.0 version locally. Trying to running tests and getting the following error
"Schema-validation: missing table [admin_settings]". 

The test I was trying to run is JpaDeviceDaoTest; It seems to be using sql-test.properties. 

Am I missing someting?

Thanks,

**Comment by ashvayka** [comment]
You should run the SqlDaoServiceTestSuite instead of JpaDeviceDaoTest. The Test Suite is responsible for installing the DB structure and some test entities. See

```java 
    @ClassRule
    public static CustomSqlUnit sqlUnit = new CustomSqlUnit(
            Arrays.asList("sql/schema-types-hsql.sql", "sql/schema-ts-hsql.sql", "sql/schema-entities-hsql.sql", "sql/schema-entities-idx.sql"
                    , "sql/system-data.sql"
                    , "sql/system-test.sql"
            ),
            "sql/hsql/drop-all-tables.sql",
            "sql-test.properties"
    );
```

**Comment by zth390872451** [comment]
> ```java
> @ClassRule
> ```



> You should run the SqlDaoServiceTestSuite instead of JpaDeviceDaoTest. The Test Suite is responsible for installing the DB structure and some test entities. See
> 
> ```java
>     @ClassRule
>     public static CustomSqlUnit sqlUnit = new CustomSqlUnit(
>             Arrays.asList("sql/schema-types-hsql.sql", "sql/schema-ts-hsql.sql", "sql/schema-entities-hsql.sql", "sql/schema-entities-idx.sql"
>                     , "sql/system-data.sql"
>                     , "sql/system-test.sql"
>             ),
>             "sql/hsql/drop-all-tables.sql",
>             "sql-test.properties"
>     );
> ```

I run  the class ControllerSqlTestSuite：
it still no use，and thre result:
![image](https://user-images.githubusercontent.com/13637039/109786366-0ba84a00-7c48-11eb-8ef8-26f39e4f301a.png)
and I also can not know how to run the test

**Comment by vortexalex** [comment]
Ok @ashvayka  , there is the `SqlDaoServiceTestSuite `, but what if one wants to run the `JpaDaoTestSuite` instead in order to test the Dao layer? It's actually impossible to run this suite because it breaks due to dependencies on beans like `StatsFactory` and others.

I'de really interested into running this test suite class, how do you actually run it without having errors on dependencies? thank you.
