### ISSUE TITLE
thingsboard alaram with telegram boot

### ISSUE THREAD

**Issue by nrajashekarreddy** [thingsboard/thingsboard#411]
As per the guidelines given in documentation we have done the setup of telegram but couldn't recieve messages. So,provide some more information about telegram notifications (setting up of rules and plugins).

**Comment by dmytro-landiak** [comment]
I have followed all steps in provided guide and successfully received all messages.
https://thingsboard.io/docs/iot-gateway/integration-with-telegram-bot/
Please make sure you are using appropriate chat_id and Telegram Bot API token.

**Comment by nrajashekarreddy** [comment]
we are using appropriate chat id and telegram bot token, we are getting messages contionously for every 5 minutes, how can we control it? and set the time.

**Comment by dmytro-landiak** [comment]
actually, you can configure alarms on the example of the following link 
https://thingsboard.io/docs/samples/alarms/basic-rules/
and send messages when new alarm is created.

**Comment by nrajashekarreddy** [comment]
actually,we have done this process earlier but we can't get any responces.

**Comment by MaheshbabuThupakula** [comment]
we are getting problem while creating new device, that is client attributes are not added and latest telemetry not updating.

**Comment by vparomskiy** [comment]
Here is tutorial how to send messages to the Telegram using Rule Engine
https://thingsboard.io/docs/iot-gateway/integration-with-telegram-bot/
