### ISSUE TITLE
/tools/src/main/shell/keygen.properties

### ISSUE THREAD

**Issue by Strauteka** [thingsboard/thingsboard#4114]
It would be nice to have "Subject alternative names" parameter in "keygen.properties" config file for servers without domain name. Otherwise in client I got 
`Caused by: java.security.cert.CertificateException: No subject alternative names present
        at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:142)`

Alternative:  keytool -keystore mqttserver.jks -alias serveralias -genkey -keyalg RSA -validity 365 -ext san=ip:x.x.x.x

**Comment by zbeacon** [comment]
Hi @Strauteka ,

Thank you for your participating in the project life. Subject alternative names parameter was added into the keygen.properties and it is available in the master branch of the ThingsBoard repository.

**Comment by Strauteka** [comment]
Thank you! Tested, in my case works!
