### ISSUE TITLE
[Question] Add keys to RPC call

### ISSUE THREAD

**Issue by jonrot1906** [thingsboard/thingsboard#4115]
**Component**

 * Generic

**Description**
I'm currently trying to get a few Mongoose OS driven devices to work hand in hand with my Thingsboard installation. Unfortunately, the RPC engine of Mongoose OS needs some extra keys like msg.id and msg.src to work properly. I couldn't get it to work with my Thingsboard instance as every message which contains more than msg.method and msg.params is blocked by the "RPC call request" node of my rule engine. Also I need send the request id in the message to get a response. Currently I have not implemented anything else on the device side, which would be possible.

I have now switched to using shared attributes which work, but I think it's not ideal.
My question is therefore: Is there any possibility to get Thingsboard to send more than msg.method and msg.params in the RPC call to the device?

**Environment**
 * OS:  Mongoose OS (device side), Ubuntu 20.04 (server side)
 * ThingsBoard: 3.2.0

**Comment by Ultrazombie** [comment]
closed due to inactive
