### ISSUE TITLE
[Question] Failed to connect localhost:8080 with token $TOKEN

### ISSUE THREAD

**Issue by ruanfelipe7** [thingsboard/thingsboard#4117]
I can't connect from the ide arduino software on my local server. When I tested it with the demo server it worked normally. I can access the server through the browser, but the arduino ide connection fails.

 * OS:  Ubuntu 20.04

**Comment by trikimiki** [comment]
Hi!

Can you please specify how are you trying to connect via Arduino and where it fails?

**Comment by ruanfelipe7** [comment]
It was my mistake.
