### ISSUE TITLE
[Question] read user rights in widget action

### ISSUE THREAD

**Issue by maaikez** [thingsboard/thingsboard#4118]
**Component**
 * UI

**Description**
On my dashboard, I have some input widgets to update server attributes. But I want that only users with a specific role can do that. Is there a way to achieve that? I can also put the input widgets on a new dashboard state and add an action on another widget to only navigate to that state when the user has a specific role. Is it possible to know the current user's role within the action of a widget? Or where can I find documentation about that? 

**Environment**
 * ThingsBoard: v3.2.1

**Comment by guillermo26** [comment]
Hi! I am interested in the same thing. I would like to check user permissions (or role) to show/hide a button of a widget action. I know that if the user has no permissions is unable to edit an asset (for example), but I think not to show the buttons that he can interact with it's better (if it's possible). Can you provide me an example to do this from the widgetContext?, I have seen that I can get the current user object, but I don't know where the permissions are (I want check if has write permissions over assets for example)

Thanks in advance!

**Comment by marcolg88** [comment]
Hello,
i'm also interested in this thing. Unfortunately I cannot find the documentation anywhere, especially for professional-only features.

**Comment by Nick-Aus** [comment]
To _read_ user rights (as per the title of this question) I've figured out the below which works ok for my requirements -
```
$injector = self.ctx.$scope.$injector; 
userPermissionsService = $injector.get(self.ctx.servicesMap.get('userPermissionsService'));
console.log(userPermissionsService.userPermissions); // expand this to decide what you need to test for your use case
```
