### ISSUE TITLE
[Bug]  psql: FATAL: role "thingsboard" does not exist

### ISSUE THREAD

**Issue by woland7** [thingsboard/thingsboard#4121]
Trying to install tb-postgres, following the official documentation. I get this:

`postgres_1  | 2021-02-17 18:04:55.558 UTC [34] FATAL:  role "thingsboard" does not exist
mytb_1      | psql: FATAL:  role "thingsboard" does not exist`

**Comment by trikimiki** [comment]
HI!

Can you please specify what guide did you follow and rather what step this bug is observed?

**Comment by trypzz** [comment]
Hi, @woland7 

We are waiting for your answer. If your problem does not actual - please, let us know.
