### ISSUE TITLE
[Question] Updating telemetry data from dashboard widget

### ISSUE THREAD

**Issue by lorithai** [thingsboard/thingsboard#4122]
**Component**
 * UI

**Description**
Is it possible to insert or update telemetry values from a dashboard using a widget? I know it is possible to change server attributes, but in the guides for developing widgets i can't find any mention of inserting/updating telemetry data. 

**Environment**
 * ThingsBoard: 3.1.1

**Comment by ChantsovaEkaterina** [comment]
Hello,
To update telemetry data you could use _Update timeseries_ widgets from _Input widgets_ bundle, also _Multiple attributes_ widget could be used, but for the last one don't forget to select _Timeseries_ data key type in the _Advanced_ data key settings.
