### ISSUE TITLE
[Question] How can I change the value of my attribute, with a widget control

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4127]
**Component**

- Generic

**Description**

I am trying to change the value of an attribute of my device "APITests" with a control widget "switch control", but when I press it it does not change the value of my attribute.

**device** 
![device](https://user-images.githubusercontent.com/78015483/108484657-57e4a900-729c-11eb-819b-c31bad4381bf.PNG)

**Alias divece in dashboard**
![alias](https://user-images.githubusercontent.com/78015483/108484856-94180980-729c-11eb-945f-9e82188b2f8d.PNG)

**advanced switch control configuration**
![advacontrol](https://user-images.githubusercontent.com/78015483/108484964-b27e0500-729c-11eb-88f0-6a35238cfd89.PNG)
![advcontrol1](https://user-images.githubusercontent.com/78015483/108484971-b447c880-729c-11eb-881f-d7225bff1386.PNG)

**rule chain for get the method**
![rulechain](https://user-images.githubusercontent.com/78015483/108485062-cd507980-729c-11eb-9ad7-0e44a4740479.PNG)

**file chain rule**

[rpc_call.zip](https://github.com/thingsboard/thingsboard/files/6008899/rpc_call.zip)

**audit logs in device**

![details](https://user-images.githubusercontent.com/78015483/108485826-9fb80000-729d-11eb-94ad-9449155127a5.PNG)

**Environment**

- OS: Windows 10

- ThingsBoard v.3.2.1PE

- Browser: Google Chrome

**Comment by Mirjka** [comment]
Hi, 
I share more than 1 attribute over device attributes. I added a switch control to the dashboard and tried to switch this particular attribute, called, "(2501)_run_stop". But I get no connection. Further I made shure, that the Device Name and the method is consistant. 
It would be great, if you could take a look.

![1](https://user-images.githubusercontent.com/46453902/113706278-c9f33f00-96de-11eb-9870-d84745632469.PNG)
![2](https://user-images.githubusercontent.com/46453902/113706277-c95aa880-96de-11eb-89e8-71bd23912955.PNG)
![3](https://user-images.githubusercontent.com/46453902/113706280-ca8bd580-96de-11eb-9758-ecc4a72a83da.PNG)

Thank you

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
