### ISSUE TITLE
[Question] How can I use REST API to make device?

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#4128]
**Component**

 * Generic

**Description**
I want to use REST API to make devices that I will assign to customers. What do you think I should use for it?
I previously tried to use 'saveDevice' but I have no idea how to use it. And I also tried 'assignDeviceToTenant', I put tenantID(UUID) from postgres thingsboard database. but for some reason ( I guess I used it wrong way ) I got 404 error "Requested item wasn't found!" error code 32 .  And I checked 'getDevicesByIds' working.

I want to make a program that makes devices automatically and assign it to customer. So, I'm wondering what API I should use and how I should use it. Thank you for your input.

**Environment**

 * OS: Ubuntu 18.04
 * ThingsBoard: latest
 * Browser: Chrome

**Comment by Strauteka** [comment]
While waiting for better answer!

https://github.com/thingsboard/tb-ce-rest-client-example

```java
import org.thingsboard.rest.client.RestClient;

RestClient restClient = new RestClient(url);
restClient.login(username, password);

private Device createDevice(String name) {
        Device device = new Device();
        device.setName(name);
        device.setType("sd");
        device = restClient.saveDevice(device);
        return device;
}
```


### pom.xml

```
<properties>
    <thingsboard.rest.version>3.1.1</thingsboard.rest.version>
</properties>
....
<repositories>
    <repository>
      <id>tb-repo</id>
      <name>Thingsboard repository</name>
      <url>https://repo.thingsboard.io/artifactory/libs-release-public</url>
    </repository>
  </repositories>
...
<dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>rest-client</artifactId>
      <version>${thingsboard.rest.version}</version>
</dependency>
```

**Comment by saviodivelo** [comment]
Thank you for your help and it might be helped for me! But now I'm struggling how to use it cause I'm like a novice.. Could you tell me what knowledge I need to study for it? (I really want to study how to use it.) Thank you.

**Comment by Strauteka** [comment]
Thingsboard privides rich documentation [(link here)](https://thingsboard.io/docs/)  and has API documentation under `<host>/swagger-ui.html` link in each thingsboard server. [Here is for demo server api](https://demo.thingsboard.io/swagger-ui.html).  [Restapi docs](https://thingsboard.io/docs/reference/rest-api/). In github you can find Pyton client and Java(thats for sure), if you want to use that. But it is not necessary, you can use simple http requests with any language you want following api docs.  As you see here about 12k unsolved cases, you can understand that you are on your own. With small steps each day you can learn to use thingsboard. 
if you didnt started with [helloworld](https://thingsboard.io/docs/getting-started-guides/helloworld/), you should try.
Good luck.

**Comment by ashvayka** [comment]
More examples are available here: https://thingsboard.io/docs/reference/rest-client/. Small correction, it is 1.2k unsolved cases, not 12K. We reply as soon as our support team or contributors have free time.

**Comment by saviodivelo** [comment]
I really appreciate that.. Thank you so much !
