### ISSUE TITLE
Does device have to poll to implement server-side RPC when using http device api 

### ISSUE THREAD

**Issue by xjz** [thingsboard/thingsboard#413]
As document said, device needs to subscribe  to RPC commands from the server by  GET method, if this http request is not a persistent connection,device will have to do subscription/polling  at intervals. Am i understanding correctly?

**Comment by ashvayka** [comment]
Yes, this is correct. We do not recommend to use http if you want to do server side RPC calls. This is redundant from both resources and traffic. That is why we recommend MQTT.

**Comment by xjz** [comment]
Got it,thanks!
