### ISSUE TITLE
 Two-Way SSL X.509 Certificate Based Authentication

### ISSUE THREAD

**Issue by Strauteka** [thingsboard/thingsboard#4132]
Can someone confirm, that in Two-Way SSL connection, device Certificate CN parameter should match servers domain name "CN=domainName"
* Manage to connect only when device certificate CN parameter equals servers domain name.

**Comment by andrew355** [comment]
It depends how you write your device client. With Eclipse Paho MQTT, the following uses TLS but does not require the certificate CN parameter to match the domain name:
 
mqttc.tls_set(cert_reqs=ssl.CERT_NONE, tls_version=ssl.PROTOCOL_TLSv1_2, ciphers=None)

**Comment by Strauteka** [comment]
I use Eclipse Paho MQTT, but could not find where I can set such a thing. for ssl using `javax.net.ssl.*` and `MqttConnectOptions.setSocketFactory(..)`
Can you give `mqttc` class name or example link, so I can look at libraries and fix my client code?
Yes, CN does not have to be servers domain name, checked with rOS mqtt and could connect to Thingsboard with CN different from servers Domain!

**Comment by andrew355** [comment]
I should have included the line before, which (in Python) is:
mqttc = mqtt.Client()

Search this page for the tls_set() method:
https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php

and you'll see the options there.

**Comment by Strauteka** [comment]
oh, I am using java version.. will try to sweep code.
Thank you very much!
