### ISSUE TITLE
[Question] How to call self.ctx.controlapi.sendtwowaycommand

### ISSUE THREAD

**Issue by pde-system-integration** [thingsboard/thingsboard#4134]
**Description**
Could anyone pls help me how to pass deviceid into function self.ctx.controlapi.sendtwowaycommand to send rpc command to specific device with device id
**Environment
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.2.1 PE
 * Browser: Chrome

**Comment by ChantsovaEkaterina** [comment]
Hello,
self.ctx.controlapi.sendtwowaycommand function uses as target id _targetDeviceId_ parameter, that could be found in _ctx.defaultSubscription_  for control widgets.
As an alternative to this function, you could use _sendTwoWayRpcCommand_ from _deviceService_, this function expects two parameters:  _deviceId_ and _requestBody_.

**Comment by pde-system-integration** [comment]
self.ctx.controlapi.sendtwowaycommand function uses as target id targetDeviceId parameter, that could be found in ctx.defaultSubscription for control widgets.
**-> could I set targetDeviceId e.g ctx.defaultSubscription.targetDeviceId = entityId ?**
As an alternative to this function, you could use sendTwoWayRpcCommand from deviceService, this function expects two parameters: deviceId and requestBody.
**-> Could you give me more information about sendTwoWayRpcCommand ? if possible, pls give me some script code ?**
Many thanks!

**Comment by ChantsovaEkaterina** [comment]
@pde-system-integration,
I think it is possible to change _ctx.defaultSubscription.targetDeviceId_ parameter, but to be sure that widget behavior would be predictable it would be better to use _sendTwoWayRpcCommand_ from _deviceService_.
Example of using _deviceService_:
```
const $injector = self.ctx.$scope.$injector;
const deviceService = $injector.get(self.ctx.servicesMap.get('deviceService'));
const requestBody = {
    method: 'string',
    params: 'any',
    timeout: 'number'
};
deviceService.sendTwoWayRpcCommand('targetDeviceId', requestBody).subscribe(() => {
    // processing request result
})
```
