### ISSUE TITLE
[Question] PE edition white labeling

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4137]
**Component**
 * UI

**Description**
I am thinking about buying PE, one of the features that interest me there are the white-labeling. Before I buy I wanted to know if I will have full control on what is presented in the label?
For example I created a dashboard and made it public. When I go to the public link I can see the dashboard and I noticed that I have an upper bar that contains entities, the option to switch between dashboards and more. I do not want those options to be presented. Does the white labeling allow me to do that?

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard 3.2 CE
 * Browser: Firefox

**Comment by ChantsovaEkaterina** [comment]
Hello,
If the only thing you need to do is to manage the dashboard toolbar, you don't need PE for this.
Options of hiding entities and dashboards selection are available in the dashboard settings.

![image](https://user-images.githubusercontent.com/17936317/108983361-76311700-7697-11eb-8cb9-dc4ccee9617b.png)

Details about the White-labeling feature you can find in the documentation:
https://thingsboard.io/docs/user-guide/white-labeling/

**Comment by snir99** [comment]
@ChantsovaEkaterina thanks, Is there a way to add a logo to the toolbar?

**Comment by ashvayka** [comment]
Adding a logo is available only in PE.
