### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by armp30** [thingsboard/thingsboard#4138]
**Describe the bug**
in the rest-client module, some of the URLs that use getUrlParams doesn't have the '?' or some character to separate URL from URL params so it causes a 404 response

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard Version 3.2
  * OS Name and Version manjaro 

**Your Device**

* Connectivity
  * HTTP

**To Reproduce**
use the rest-client module as a separate project

public PageData<TenantProfile> getTenantProfiles(PageLink pageLink) {
        Map<String, String> params = new HashMap<>();
        addPageLinkToParam(params, pageLink);
        return restTemplate.exchange(
                baseURL + "/api/tenantProfiles" + getUrlParams(pageLink),
                HttpMethod.GET,
                HttpEntity.EMPTY,
                new ParameterizedTypeReference<PageData<TenantProfile>>() {
                }, params).getBody();
    }

the line containing the geturlparams(pageLink) function should be like this
baseURL + "/api/tenantProfiles?" + getUrlParams(pageLink),
there is multiple functions that has this problem and the solution is just adding '?' before geturlparams function.

**Comment by ashvayka** [comment]
Fixed and will be part of 3.2.2
