### ISSUE TITLE
How to update a specified server attribute for all registered devices at the same time ?

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4141]
Hello !

Please tell me how can I update a server attribute for all registered devices.
I need to update a specified server attribute for all registered devices at the same time.

Thank You !

Environment
OS: Windows 10
ThingsBoard v.3.2.1CE
Browser: Google Chrome

**Comment by vvlladd28** [comment]
Hi @lmax25,
Your need to used functional Scheduler from version TB PE
