### ISSUE TITLE
Thingsboard TELEMETRY not updating on widgets[Bug] 

### ISSUE THREAD

**Issue by GuilhermeMoura97** [thingsboard/thingsboard#4145]
Hello,

I have been trying to use thingsboard in the last two weeks and develop an application that both receives and sends information through MQTT. I had no issues until yesterday when thingsboard seems to stop working at all. I can still send telemetry through MQTT however, none of my widgets update the information. 

So, I tried to run the thingsboard tutorial (https://thingsboard.io/docs/getting-started-guides/helloworld/#tutorial-resources) with the rule chain generator and all, and again, it doesn't update. 

**Your Server Environment:**
   -  demo.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Mozilla Firefox

**Your Device**

* Connectivity
  * MQTT

**Expected behavior**
Update widgets with new information

**Screenshots**
Image of thingsboard dashboard 1 min apart using the tutorial temperature generator (1 sec messages, widget never changes for 1 min): ![Thingsboard_tutorial](https://user-images.githubusercontent.com/71149960/108832621-b2934300-75c3-11eb-8328-95accd297350.png)

**Additional context**
I was trying to collect data from the database through the windows terminal, and I think it was after that thingsboard stopped working. Could that be related to my issue?

**Comment by Smita1231** [comment]
Yes. For me also..suddenly the dashboard stop working. Under latest telemetry data is reflected but the dashboard is not showing any data. Please look into this matter. It is really very urgent

**Comment by damianidisapo** [comment]
Yes. The same for me..

**Comment by vvlladd28** [comment]
Hi, 
Thank you for the report; we resolve a problem in demo.thindsboard.io. Please check again

**Comment by ashvayka** [comment]
Hi @GuilhermeMoura97 , please note that demo.thingsboard.io is just a demo environment hosted on a single server. If you really like the high-availability - please consider [thingsboard.cloud](https://thingsboard.cloud) or your own setup.

**Comment by thucar** [comment]
> Hi,
> Thank you for the report; we resolve a problem in demo.thindsboard.io. Please check again

Hi, could you please explain what was causing this issue? I'm seeing the same thing on my TB installation. The incoming data is not being refreshed on the Dashboard real time. If I reload the dashboard page, then the latest values show up correctly.

**Comment by thucar** [comment]
More details about the issue: 
The problem is not limited to only dashboard. Even when I go into Devices and look at their Telemetry, the values there do not update while I have the device Latest Telemetry tab open. 

This is happening on a CE version

I also have a PE installation for production environment and that is working correctly.

**Comment by thhart** [comment]
Had this phenomenon as well, a user could not see any telemetry data any more, tenant could still see. So I deleted the user and added again and it worked.

**Comment by thucar** [comment]
@thhart thanks for thinking along but unfortunately that's not what's happening to me. Thingsboard is behaving similarily for users and tenant admins alike. No matter the user level, if you open up a Dashboard, you get a nice, fully populated dash. All data is there, no matter if its time series or attributes. Now the problem is that the data never changes while you have the dash open.

If you refresh the dash, or change dashboard state, then all values get updated but only once. So every time you refresh the dash for whatever reason, you get fresh data. If you just keep the dashboard open, you're only getting stale data that was fetched at the time of loading the dashboard.

**Comment by thhart** [comment]
@thucar Indeed it sounds rather like a WS problem, maybe you have some Proxying going on strange in your connection/company, perhaps try a different network/client/browser but this a wild guess and I can not help further.

**Comment by Guapz** [comment]
I am using TB PE Cloud and I have the same issue. When I am using Demo.thingsboard.io it all works and the widget data and telemetry is being updated. However on TB PE Cloud, it does not. It also cannot show any charts or widgets with any history of the data. Only manual refresh of the webpage updates the realtime data widgets, but still no history widgets. 

Has anyone found a solution?

**Comment by fxsilva** [comment]
I have some similar issue, I have a DO sensor working with the CE version installed in a server, the system was working good, some days ago it begins to show a delay between the data sent to the server using HTTP.
The node send 4 data at the same time, Oxygen concentration, oxygen saturation, temperature and voltage, but only votage arrives timely, the other data arrives with a big delay
![image](https://user-images.githubusercontent.com/41272130/128088289-d5e4dce2-c85a-433a-bf27-e4f1ab5ad8b7.png)

**Comment by t0mmyz7** [comment]
@fxsilva did you find a solution for this?

**Comment by amarkevich** [comment]
reproduced on `store/thingsboard/tb-pe:3.3.1PE`

**Comment by jollytrivedi2019** [comment]
Update MQTT transport configuration in device profile. This resolved for me. When I published the data from MQTTBox, telemetry was updated in ThingsBoard.


![image](https://github.com/thingsboard/thingsboard/assets/58602491/da4a51d7-e71f-49e9-8408-3d2785ad0cbf)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
