### ISSUE TITLE
v3.2.1 UI: Add ability to open dashboard state in separate dialog,  How?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#4148]
Hi

in the changelog for 3.2.1 CE, it lists this feature:
UI: Add ability to open dashboard state in separate dialog

can you share instructions on doing this?

Thanks

**Comment by ashvayka** [comment]
Please check this guide: https://thingsboard.io/docs/user-guide/ui/widget-actions/#open-in-a-separate-dialog

**Comment by t0mmyz7** [comment]
Thanks!!
