### ISSUE TITLE
How to the device receive data from thingsboard in real-time? 

### ISSUE THREAD

**Issue by lichmac** [thingsboard/thingsboard#4150]
Hi
I'm a newbie. I have a mobile app to send my telemetry data via the api:
curl --location --request POST 'https://thingsboard.cloud/api/v1/$ACCESS_TOKEN/telemetry?timeout=20000' \
--header 'Content-Type: application/json' \
--data-raw '
{
"temp": 37
}'
The API works fine. $ACCESS_TOKEN is device token in thingsboard
Mobile app save the telemetry data, then the device needs to show the telemetry data in realtime. The device used MQTT to subscribe topics:
'v1/devices/me/rpc/request/+',
'v1/devices/me/rpc/response/+',
'v1/devices/me/attributes',
'v1/devices/me/telemetry'
(auth with username = $ACCESS_TOKEN of the device to connect to MQTT ==> successfully).

I tried to use the RPC API, but the API needs $JWT_TOKEN to auth

curl --location --request POST 'https://thingsboard.cloud/api/plugins/rpc/oneway/${deviceId}' \
--header 'Content-Type: application/json' \
--header 'X-Authorization: Bearer $JWT_TOKEN' \
--data-raw '{
"method": "setTemp",
"params": {
"value": temp
},
"timeout": 60000
}'

The RPC API works. My device receives the telemetry data from MQTT.

My Question: How to my device receive real-time telemetry data from my mobile app saved to thingsboard server and don't need to use RPC API or $JWT_TOKEN ? Because I don't want to use the $JWT_TOKEN

Sorry, my English is not good.

Can you help me?

Thank you very much

**Comment by Ultrazombie** [comment]
closed due to inactive
