### ISSUE TITLE
[Bug] Entities widget didn't show data

### ISSUE THREAD

**Issue by jaballogian** [thingsboard/thingsboard#4152]
**Describe the bug**
The entities table (card) widget in a dashboard didn't show data but other widgets did.

**Server Environment:**

Own setup
  * Local infrastructure
  * ThingsBoard Version: 3.2.1 profesional edition
  * OS Name and Version: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-135-generic x86_64)

**Client Environment**

Desktop
  * OS: Windows 10 build 18363
  * Browser: Chrome version 88.0.4324.182

**Device**

* Connectivity
  * Integration: flespi.io with protocol_id thingsboard
* Device vendor and model: Teltonika MTB100 (teltonika)

**To Reproduce**
1. Created a dashboard group with the name "Test - *****"
2. Created a dashboard with the name also "Test - *****"
3. Created an entity alias with the name also "Test - *****"
![image](https://user-images.githubusercontent.com/24468466/108975266-e603c980-76b8-11eb-9211-3258e0bcdd66.png)
4. Added an entities card widget, assigned "Test - *****" alias to the widget, and assigned some temperature values
![image](https://user-images.githubusercontent.com/24468466/108975477-1f3c3980-76b9-11eb-8b7d-b0ab4f22b1e5.png)
5. Added a new attributes card widget, assign "Test - *****" alias to the widget, and assigned some temperature values (the same as values in step 4)
![image](https://user-images.githubusercontent.com/24468466/108976095-c325e500-76b9-11eb-9cd7-ccb2fc84809f.png)

**Expected behavior**
The entities table widget shows data as same as the data shown in the new attributes card widget.

**Screenshots**
![image](https://user-images.githubusercontent.com/24468466/108975748-662a2f00-76b9-11eb-9659-cb34c108bc32.png)

**Comment by vvlladd28** [comment]
Hi @jaballogia,
Thank your for your report. We are sorry for this inconvenience. There will be a release with this improvement in 2-3 weeks.

**Comment by jaballogian** [comment]
I updated the bug report.

Screenshot 1
![Capture](https://user-images.githubusercontent.com/24468466/110059096-25f03e00-7d96-11eb-9729-c95a66e327f5.PNG)

Screenshot 2
![Capture 2](https://user-images.githubusercontent.com/24468466/110059100-27ba0180-7d96-11eb-9c9b-69f1fd6c8b56.PNG)

As you can see from the first screenshot, in the "Entities" card widget, there are "Temperature 1" and "ble.sensor.temperature.1" columns.
In the second screenshot, both columns access the same data from "ble.sensor.temperature.1".
The column without any dot (Temperature 1) shows the data and the column with dots (ble.sensor.temperature.1) doesn't show the data.

**Comment by vvlladd28** [comment]
Hi @jaballogian,
Yes, this is a problem that we have already fixed. The new version of TB will be released soon include fix this problem.
