### ISSUE TITLE
[Feature Request] Support CrateDB as alternative time series DB

### ISSUE THREAD

**Issue by proddata** [thingsboard/thingsboard#4156]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see, that Thingboard doesn't officially support CrateDB as time-series DB solution, as we (Crate.io) get requests for CrateDB to support Thingsboard. We looked into that, but unfortunately it seems more realistic the other way around.

**Describe the solution you'd like**
Support CrateDB as alternative solution for time-series data to the Cassandra solution already in place. As CrateDB is a shared-nothing distributed database solution it should be a great alternative for distributed application scenarios.

**Describe alternatives you've considered**
I tried to use CrateDB as drop-in replacement for the postgres solution, but unfortunately CrateDB doesn't fully support all PostgreSQL features used by Thingsboard.

**Additional context**
We would gladly help/assist or even create some PRs :)

**Comment by ashvayka** [comment]
You are free to add a PR to implement support of CrateDB instead of PostgreSQL. This may be a challenging task. I would recommend to start with PR that replaces time-series storage (Cassandra) with CrateDB. At the moment we don't have time to do this on our own.
