### ISSUE TITLE
[Question] Focusing on device in map when clicking on table row

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4157]
**Component**
 * UI

**Description**
I have a few devices (for now) that I show on a map and on a table. What I want to do is when I click on the a device in the table the map will focus/jump to that device on the map. If I have a lot of devices on the map locate a specific one so this can help to find the one that is needed by clicking on the table. How can I do that?

Here is an image for reference:
![table_click_map_focus](https://user-images.githubusercontent.com/31441724/106781384-ac0f4c80-6651-11eb-890c-bd12727c880a.png)

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2

**Comment by aortega1** [comment]
hi @snir99 , have you come across a solution to this by chance?  I began writing a custom leaflet implementation which builds a dynamic table which is then selectable/searchable.  I was hoping for this to be integrated into ThingsBoard however as their map configuration lends itself towards my end users.

**Comment by snir99** [comment]
@aortega1 unfortunately not yet, if ill come across a solution I will post it here. I will appreciate it if you will come up with a solution post it here too.

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
