### ISSUE TITLE
Implement MQTT Last Will and Testament

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#416]
MQTT Last Will and Testament is an important feature for monitoring the overall health of a sensor network.  I believe implementation will be relatively straightforward.

**Comment by fotis400** [comment]
Yes this is a much needed feature, I would also vote for this.

This will not only benefit device monitoring, but also a great variety of use cases.

**Comment by Karabiy** [comment]
you can use any kind of the third-party MQTT broker with those being already implemented and the MQTT integration, which is available for the ThingsBoard Professional Edition. 
You may refer to this link regarding those: https://thingsboard.io/docs/user-guide/integrations/mqtt/

**Comment by fotis400** [comment]
Thingsboard is supposed to have an embedded broker. As it is using MQTT is should also support last will and testament.

Why should we use an external broker/gateway for such a simple need? It just overcomplicates things for no reason...

**Comment by Alex-Stanfield** [comment]
I strongly back the request. We pay for an IOT platform which has MQTT. It must support LWT, it's just a fundamental component of the MQTT paradigm.
We don't want to depend on a third party to complete a half-baked implementation of MQTT. 
Neither we want to add points of failure to our solutions.
Thanks a lot for considering completing the implementation.

Best regards
Alex

**Comment by JimmyPedersen** [comment]
Any updates on this request?
Would very much like support for this
Best regards
Jimmy
