### ISSUE TITLE
[Question] How i can take the downlink in remote integration

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4166]
**Component**

 * Generic

**Description**
A clear and concise details.
This is the response that it sends me when I use the hhtp endpoint url of the integration, in this one it returns the downlink
url end poin integrationt: http://192.168.1.229:8080/api/v1/integrations/http/42ab8931-0957-e96b-2641-79cf55dd7e43
![image](https://user-images.githubusercontent.com/78015483/109179143-e1f3ac80-7789-11eb-8984-5820afc87fa5.png)
![image](https://user-images.githubusercontent.com/78015483/109179480-38f98180-778a-11eb-8651-f9ba34b0b7fa.png)
OUT downlink
![image](https://user-images.githubusercontent.com/78015483/109179219-f6d04000-7789-11eb-8e63-16df0e295f83.png)

This is the response it sends me when I use the remote integration (docker) address and it does not contain the downlink.
url remote integration : http://0.0.0.0:8082/api/v1/integrations/http/aca2c6dc-601a-8a68-ee16-460be570da60
![image](https://user-images.githubusercontent.com/78015483/109179418-2a12cf00-778a-11eb-84d3-4002744226fe.png)
![image](https://user-images.githubusercontent.com/78015483/109179554-50d10580-778a-11eb-98c7-a8080d5a92b6.png)

PD: With the url of the remote integration the uplink is made perfectly
**Environment**

 * OS:  windows 10
 * ThingsBoard: ThingsBoard v.3.2.1PE
 * Browser: google chrome

**Comment by Ultrazombie** [comment]
Is your problem still relevant on the latest version of ThingsBoard?
