### ISSUE TITLE
[Feature Request] List all upstream rule-chains in the interface (green input node)

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#4168]
Hello

Some ThingsBoard usages require to setup many (like dozens) rule-chains.
At some point it's getting hard for users to understand the "big picture". So a strategy is often to start the visit from the root rule-chain and then explore each paths.

In recent versions, the purple nodes pointing to external rule-chains received a very handy button to jump to the designated rule-chain: 

![image](https://user-images.githubusercontent.com/39315/109278719-25e1c280-7819-11eb-9170-82bf8376597d.png)

Thank you for adding this, it's very useful.

But what if want to go the other way around? Let's say you open one rule-chain. There's currently no easy way to know which are the rule-chains pointing to it.

So my suggestion would be to add some kind of improvement on the green input node :

![image](https://user-images.githubusercontent.com/39315/109279086-9c7ec000-7819-11eb-8054-ab97617f4ebd.png)

For example by clicking on the green input node, it could open a panel where all the pointing rule-chains would be listed (with links to navigate to them rapidly)

Thanks!

**Comment by pon0marev** [comment]
We are working on UX improvements for Rule Chains. Lots of new features that give more observability of processes inside the RC and between them. Stay tuned. The functionality you are suggesting may become obsolete with the next generation of Rule chains
