### ISSUE TITLE
[Question] How can I bring Device Group Name to an Entity or Asset Card Widget?

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#4174]
**Component**

 * UI

**Description**
I would like to know if it is possible, and how to do it in a positive case, to include (or to call) the device group name as a key at entity or asset card widget in a dashboard.  Today it allows us to include as an environment key the name, label, type and creation time, is there any way to get the device group name?

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.2.1PE
 * Browser: any

**Comment by Ultrazombie** [comment]
One device can be in many device groups; add the name of the device group to the device attribute and show it on widgets.
