### ISSUE TITLE
[Question] Thingsboard 3.2.1 installation failed in Windows 10 System.

### ISSUE THREAD

**Issue by egeong** [thingsboard/thingsboard#4176]
**Component**

 * Installation
"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\thingsboard-3.2.1\msa\js-executor "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\lib\idea_rt.jar=62093:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2018.2.5 -DskipTests=true install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ThingsBoard JavaScript Executor Microservice 3.2.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ js-executor ---
[INFO] Configured Artifact: com.google.protobuf:protoc:windows-x86_64:3.11.4:exe
[INFO] Copying protoc-3.11.4-windows-x86_64.exe to C:\thingsboard-3.2.1\msa\js-executor\target\protoc-3.11.4-windows-x86_64.exe
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.5:install-node-and-yarn (install node and yarn) @ js-executor ---
[INFO] Installing node version v12.16.1
[INFO] Copying node binary from C:\Users\Jinghe\.m2\repository\com\github\eirslett\node\12.16.1\node-12.16.1-win-x64.exe to C:\thingsboard-3.2.1\msa\js-executor\target\node\node.exe
[INFO] Installed node locally.
[INFO] Installing Yarn version v1.22.4
[INFO] Unpacking C:\Users\Jinghe\.m2\repository\com\github\eirslett\yarn\1.22.4\yarn-1.22.4.tar.gz into C:\thingsboard-3.2.1\msa\js-executor\target\node\yarn
[INFO] Installed Yarn locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.5:yarn (yarn install) @ js-executor ---
[INFO] Running 'yarn install' in C:\thingsboard-3.2.1\msa\js-executor
[INFO] yarn install v1.22.4
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ pkg -t node12-linux-x64,node12-win-x64 --out-path ./target . && node install.js
[INFO] > pkg@4.4.9
[ERROR] internal/child_process.js:407
[ERROR]     throw errnoException(err, 'spawn');
[ERROR]     ^
[ERROR] 
[ERROR] Error: spawn UNKNOWN
[ERROR]     at ChildProcess.spawn (internal/child_process.js:407:11)
[ERROR]     at spawn (child_process.js:548:9)
[ERROR]     at fabricate (C:\thingsboard-3.2.1\msa\js-executor\node_modules\pkg\lib-es5\fabricator.js:65:54)
[ERROR]     at fabricateTwice (C:\thingsboard-3.2.1\msa\js-executor\node_modules\pkg\lib-es5\fabricator.js:139:3)
[ERROR]     at MultiStream._queue (C:\thingsboard-3.2.1\msa\js-executor\node_modules\pkg\lib-es5\producer.js:182:53)
[ERROR]     at MultiStream._next (C:\thingsboard-3.2.1\msa\js-executor\node_modules\multistream\index.js:73:10)
[ERROR]     at Meter.onEnd (C:\thingsboard-3.2.1\msa\js-executor\node_modules\multistream\index.js:120:10)
[ERROR]     at Object.onceWrapper (events.js:417:28)
[ERROR]     at Meter.emit (events.js:311:20)
[ERROR]     at endReadableNT (_stream_readable.js:1204:12) {
[ERROR]   errno: 'UNKNOWN',
[ERROR]   code: 'UNKNOWN',
[ERROR]   syscall: 'spawn'
[ERROR] }
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.551 s
[INFO] Finished at: 2021-02-28T15:06:02+08:00
[INFO] Final Memory: 16M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (yarn install) on project js-executor: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Description**
js-executor always failed to install, I don't have any clue.Do you have any idea where to solve the issue?

thanks!

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.2.1
 * Browser: Chrome

**Comment by egeong** [comment]
It seems that some commands are unique to Linux, but how solve this problem with Windows system?

**Comment by a49557711** [comment]
I also encountered the same problem

**Comment by scutcz** [comment]
Same error here.

**Comment by scutcz** [comment]
> Same error here.

I've resolved the problem by downloading the required packages manually from [https://github.com/vercel/pkg-fetch/releases](url) then copy those packages to the PKG cache folder. Just for your reference.

**Comment by egeong** [comment]
> > 同样的错误在这里。
> 
> 我已通过从[https://github.com/vercel/pkg-fetch/releases](url)手动下载所需的软件包，然后将这些软件包复制到PKG缓存文件夹中，解决了该问题。仅供您参考。

@scutcz 
Thanks for answering my message, I'd like to give it a try and see if that works for me. :-)

**Comment by SergMeleshko** [comment]
Hello @egeong.
Did the message above help you?
