### ISSUE TITLE
[Question] Mobile App Support

### ISSUE THREAD

**Issue by cylyl** [thingsboard/thingsboard#4178]
**Mobile App**

 * UI

**Description**
Any plan for mobile app support? such as develop mobile app with Flutter?

**Comment by DenysDi** [comment]
Hi @cylyl ,
We are planning to present [Mobile client SDK](https://thingsboard.io/docs/reference/roadmap/) later this year.
So just follow our [release notes](https://thingsboard.io/docs/reference/releases/)

Best regards,
Denys
