### ISSUE TITLE
loading a device dashboard locks up the entire chrome tab

### ISSUE THREAD

**Issue by Cody-Hayes97** [thingsboard/thingsboard#4183]
Describe the bug
Hello there, I have a bit of a problem that I have yet to run into on TB and was hoping for help. I have a asset dashboard with 3 devices in a list, one device gateway and 2 solar inverters. when I click on one of my inverters the dashboard works fine, however, when I click on the other it takes me to that device's dashboard, but then my whole tab freezes. this does not happen with any other device in my entire ThingsBoard tenant. this device is the same device type as my other inverter so it makes no sense why one would stall my whole page.

it says that this might be due to a font not loading or waiting forever to get a response? I'm not sure if this is the reason or a coincidence.

If anyone has run into this problem or knows how to fix it I would appreciate the help.

Your Server Environment

own setup
cloud or local infrastructure or docker deployment
ThingsBoard Version 3.1
ubuntu/linux
Your Client Environment

Desktop (please complete the following information):

OS: Windows 10

Browser: chrome

Connectivity

HTTP

**Comment by trikimiki** [comment]
Hello Cody,

Can you reproduce this behaviour and then check your log file for any recent ERROR or WARN event? On Windows, your logs are located in `<install path>\thingsboard\logs\thingsboard.log`.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
