### ISSUE TITLE
[Question] how to navigate to DeviceDetails from Dashboard?

### ISSUE THREAD

**Issue by olsky** [thingsboard/thingsboard#4186]
Dashboard

 * UI

**Description**
howto navigate from EntitiesTable to Devices --> selected Device details?

**Comment by LeoMorgan113** [comment]
Hi @olsky,

If I understand you clearly, you would like to use custom action for the dashboard.
You can refer to this article: https://thingsboard.io/docs/user-guide/ui/widget-actions/#navigate-to-new-dashboard-state
