### ISSUE TITLE
Get latest telemetry alarm information from rule chain

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#4188]
I'd like to create a delta alarm among the latest telemetry values.
The delta must be calculated among the current value and the previous 2 hour value or, if there is a previous alarm, between the current value and the value relative to the cleared alarm timestamp.

My idea would be:
1) get the latest telemetry 2 hour values 
2) get the latest cleared alarm timestamp (within the two hours)
3) if there are no cleared alarms in the previous 2 hours compute the delta between le current value and the previous 2 hour value
4) if there are cleared alarms in the previous 2 hours get the latest cleared alarm timestamp, pick up the related telemetry value and finally compute the delta between this value and the current value.

The problem? I don't know how the get related alarms information inside a rule chain. I hope my explanation is clear!

Any suggestion?

Thanks in advance

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
