### ISSUE TITLE
Thingsboard - Is it possible to access configured "Roles" based on the "userId" in Rule Chain?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#4194]
Here is the situation.

A user group is configured as follows,

1. - Group Role #1 : Device #1 & Device #2 are given only read access
2. - Group Role #2 : Device #3 has given read & write access
3. - There a relation From User #1 to Device #4

Required Flow:

1. User #1 sends data to Device #4 using it's device id in Thingsboard server. HTTP POST method is used and in URL mentioned the device id of Device #4. This data contains the target device name/id (In our case here Target devices are Device #1, #2, #3)
2. Device #4 receives the data.
3. A Rule chain should identify the target device based on the payload message received.
4. Also should check the User Group role whether it is only read or includes write access configured.
5. In our case here, if data contains "Device #3" id, then this User #1 can do read & write attributes, if data contains "Device #1" or "Device #2", then user can only read attributes/telemetry. With "POST" command to "Device #1" or "Device #2", the response should be like "Don't have permission to perform Write operation"

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
