### ISSUE TITLE
Thingsboard - How safe is to include $ACCESS TOKEN & User Auth in HTTPS URL while posting the telemetry data to Thingsboard?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#4195]
When we post / get a telemetry data from Thingsboard server using HTTP API commands, we mention device's $ACCESS_TOKEN or $DEVICE_ID in the URL and for Authorization $JWT_TOKEN or $USERNAME:PASSWORD.

If we are using http:// or https://, does it make difference? Is these device & user credentials are secure with https:// ?

**Comment by NarinLab** [comment]
If HTTP(Secure) is still intact, then nobody can see what is being sent between TB and Devices. But, if only using HTTP then surely it is very easy to eavesdrop the credential.

**Comment by ashvayka** [comment]
Hi @bhimashankarP ,

If you use HTTP - any "[man in the middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)" can see all the data. 
If you use HTTPS - the "[man in the middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)" can't see your data, including the access token and other parameters of the URL.
