### ISSUE TITLE
[Question] Use filter "check relation" (rule) for nested assets

### ISSUE THREAD

**Issue by karaby** [thingsboard/thingsboard#4197]
**Component**
 * Rule Engine

**Description**
I need to get data from devices filtered by an asset of a level higher than the first.
That is, asset A (floor) contains asset B and C (rooms). Asset B contains sensor D. Asset C contains sensor E.
I need to send messages about the inactivity alarm of any sensor located on floor A, i.e. sensor D or E.
If I create 2 filters "check relation" for assets B and C, then everything is fine. But if I create a filter "check relation" for asset A, then no alarm message is generated.
How to create rules correctly?

**Comment by Ultrazombie** [comment]
Closed, as not active.
