### ISSUE TITLE
Thingsboard : Is it possible to access the JWT Token in Rule Chain as Metadata?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#4204]
While using "REST Call API" node in Rule chain, we need supply "X-Authorization" header to execute the given request (POST/GET...).
How to get the value (Bearer $JWT_TOKEN) for this "X-Authorization" based in the Rule Chain?

My current testing flow is as shown in the attached image.
![TB JWT Token](https://user-images.githubusercontent.com/38416893/109995047-ebee5000-7d33-11eb-9963-9d7892af0566.png)

**Comment by LeoMorgan113** [comment]
Hi @bhimashankarP,

While login in the network displayed a request for this, and in the Preview, you can find a token.
So you may try to use this request for getting token in rule node "Rest Call API".

![2021-06-07_16-40](https://user-images.githubusercontent.com/56256429/121027448-a23c5800-c7af-11eb-86d3-7f2e803c1004.png)
![2021-06-07_16-42](https://user-images.githubusercontent.com/56256429/121027452-a4061b80-c7af-11eb-8ff9-d64790902c5c.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
