### ISSUE TITLE
[Question] How to show image attribute in dashboard

### ISSUE THREAD

**Issue by nalberto** [thingsboard/thingsboard#4206]
**Component**
 * UI

**Description**
How do you display an image attribute in a dashboard?
I just want to show the image stored as a server image attribute.
The input widget is of no use because the image shows up very small and I don't want the upload button next to it.

I thought of using the HTML card but it does not allow to insert data (image attribute) and therefore I don't know how to link the base64 string to the html.

I saw a post about using the image map widget but there is no detail explanation and it would not work for me. I don't want to display a telemetry value but just the image as a reference for the user to have a picture of the device.

Cheers
Nic

**Comment by ChantsovaEkaterina** [comment]
Hello, @nalberto 
It is possible to display an image attribute on the dashboard by using the HTML Value Card widget.
Please, take a look at the example in the file attached. Change the file extension from _txt_ to _json_ to import this example widget to the dashboard.
[image_attribute_example.txt](https://github.com/thingsboard/thingsboard/files/6116543/image_attribute_example.txt)

**Comment by nalberto** [comment]
Excellent. This should work. It allows me to link the html widget to a datasource (entity).

Where did you find this widget? I could not find it as part of the standard widgets.
Is there a separate repository of available extra widgets somewhere?
Thank you.

**Comment by ChantsovaEkaterina** [comment]
@nalberto 
This widget is a standard one. You can find it in the Cards bundle -> Latest values -> HTML Value Card.
![image](https://user-images.githubusercontent.com/17936317/110762423-7285be80-8259-11eb-9b71-7d95abd353f7.png)

**Comment by nalberto** [comment]
Thanks again. Yes I can see that now.

Other question. Let me know if I need to create a new entry:
I know I can use this method {$variableName} to include an entity alias into the html section of this widget.
I need to do that same thing but in the css section of the widget but it is not accepted.
How can I refer to an entity alias variable into the css section.
This would be very powerfull as it will allow me to interact directly by css on an SVG image to show and hide different sections of the image based on telemetry data.

Thank you

**Comment by ChantsovaEkaterina** [comment]
There is no way to refer to the datasource keys in the CSS section.
Not sure if it would be helpful for you, but you could try to use the _style_ tag in the HTML section.
```
<style>
    // Your styles here
</style>
```
In this case, variables ${keyLabel} will be substituted by their values.
