### ISSUE TITLE
[Question] How to handle delayed data to Rule Chain?

### ISSUE THREAD

**Issue by shalahuddinn** [thingsboard/thingsboard#4207]
**Component**
 * Rule Engine

**Description**
My rule chain analytics is state-based, which means the calculation depends on the value of the previous data.

Let say the device generate data every second, so for 5 second there are 5 data from t=0 to t=4 (t=0, t=1, t=2, t=3, and t=4). In an ideal situation, first, the device will send the t=0 data and then Thingsboard will receive it. Next, the device will send the t=1 data and then Thingsboard will receive it. Next, the device will send the t=2 data and then Thingsboard will receive it. Therefore, Thingsboard will receive the data in chronological order based on the t value.

But due to the network issue, I faced a problem. Let say Thingsboard gets the t=3 data for now, but due to the network issue, the t=1 data just arrive exactly after the t=3 data. The t=1 should be sent and be received earlier than the t=3 data but it can happen because of a lost network connection. So the order of the data coming to the Thingsboard rule chain is broken.

So I need the Thingsboard rule chain to process the data in order based on the t value, not based on which data come first. Every message that comes to Thingsboard contains the device timestamp value on its metadata. So I think I can use that value to sort those messages.

How do I solve this?

Thank you

**Environment**
 * ThingsBoard: 3.2.1

**Comment by mgogh** [comment]
Hi,

It's a good question ! Any answer or update about this ?

Regards,

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
