### ISSUE TITLE
[Question] Is it possible to rotate between dashboard states every x seconds?

### ISSUE THREAD

**Issue by JonasRueck** [thingsboard/thingsboard#4208]
**Component**

 * Generic

**Description**
I have a dashboard with three different dashboard states. Is it possible to switch between those three dashboard states like every x seconds? And if so, how can I achieve this? I already tried with Custom Action, but this will require an interaction of the user, like clicking on a row or a button.

**Environment**

* OS: Windows 10
* ThingsBoard: 3.2.1 CE
* Browser: Google Chrome

**Comment by JonasRueck** [comment]
Any update on this?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request.
