### ISSUE TITLE
Device profiles alarm creation not works [Bug] 

### ISSUE THREAD

**Issue by Stefke-hw** [thingsboard/thingsboard#4214]
In device profiles you have the option to create an alarm without rule chain. I created a very simple alarm to test, but the alarm is not displayed in the active alarm list of the device, when it should appear. The device profile is used by a device. There I made sure that the device value which is used for the alarm really changed, but no alarm occurred. 

In the following picture dispalys my device profile alarm settings:
![problem](https://user-images.githubusercontent.com/70195937/110301817-d52c4f80-7ff8-11eb-93df-e5d2fa2a3ef6.png)

ThingsBoard Version: 3.2.1 Professional Version
The telemetry is transmitted by a Sensor with a mytt connection.
The value tuerOffen is either "1" or "0"

**Expected behavior**
Create an alarm by the device profiles stettings. Later I want to build more complex alarms, but first I need a solution for this problem.

**Comment by vvlladd28** [comment]
Hi @Stefke-hw,
Please describe in more detail the step-by-step process of repeating this bug. (Send data, example device, and configuration device profile)

**Comment by Stefke-hw** [comment]
Hi @vvlladd28 
1. I'm create the device profile with the following Parameters:

![device_profile_details](https://user-images.githubusercontent.com/70195937/110622698-1741c680-819c-11eb-9345-90fb13cb5431.PNG)

Alarm rules should create an alarm with the name "Test" of the value tuerOffen is equals "1":
![Alarm_rules](https://user-images.githubusercontent.com/70195937/110622730-1f016b00-819c-11eb-9d1e-a552f6ed5fb2.PNG)

2. The device data is from a LoRaWAN Sensor and is send from NodeRed, in the gateway format, to one in Thingsboard as gateway declared device. The data then assigned by the Gateway Engine of Thingsboard to the device with the right name.

Example data: 
- { "LoRa-3330A316": [ { "tuerOffen": 1, "manipulation": 0, "batterylow": 0, "reportCounter": 10, "temperatur": 24.718576431274414, "feuchtigkeit": 40.95892333984375, "devtype": "CM868LRTH", "devaddr": "3330A316" } ] }
- { "LoRa-3330A316": [ { "tuerOffen": 0, "manipulation": 0, "batterylow": 0, "reportCounter": 10, "temperatur": 24.761476516723633, "feuchtigkeit": 41.36328125, "devtype": "CM868LRTH", "devaddr": "3330A316" } ] }

Device configuration:

![Details_device](https://user-images.githubusercontent.com/70195937/110622784-32acd180-819c-11eb-9f6a-6fbcf49ee2a2.PNG)

The telemetry is displayed correctly on the device an value of tuerOffen is "1":
![Telemetrie_Sensor](https://user-images.githubusercontent.com/70195937/110622802-39d3df80-819c-11eb-940a-1b5e6390d50b.PNG)

Alarms list: There are some alarms but they are all created by a rule chain and no one has the type "Test" which is configured in the device profile alarm rules 
![Alarm device](https://user-images.githubusercontent.com/70195937/110622823-43f5de00-819c-11eb-8ad7-815885abb886.PNG)

**Comment by ashvayka** [comment]
Hi @Stefke-hw , what are the key type (Attribute or Timeseries) and value type in your alarm filter? The only reason why your configuration will not work (the only possible reason I know) is that your filter is comparing an attribute called "tuerOffen" to 1 and you are sending timeseries data and not attribute. Please attach the screen with the filter configuration. 

![missing_screen](https://user-images.githubusercontent.com/5016373/110635140-7232e800-81b3-11eb-9bdc-37f1436f6b55.png)

**Comment by Stefke-hw** [comment]
Hi @ashvayka,
The key type is Timeseries and the value type numeric

![filter configuration](https://user-images.githubusercontent.com/70195937/110745630-d7cab700-823b-11eb-88f8-718c9f70f898.png)

![filter configuration_2](https://user-images.githubusercontent.com/70195937/110746538-3b091900-823d-11eb-8a03-13d38563af9b.png)

**Comment by YevhenBondarenko** [comment]
Hi @Stefke-hw,

**Comment by YevhenBondarenko** [comment]
Hi @Stefke-hw 
Could you provide "LoRa" rule chain?
Rule node "[device profile](https://thingsboard.io/images/user-guide/device-profile/device-profile-rule-node.png)" should be first in this rule chain;

**Comment by lilalukas** [comment]
Hi,
I work together with stefke-hw and you are totaly right. We missed the device-profile-node in the _LoRa_-RuleChain. After adding the node, the alarm is created propperly.
Thanks for your support!
