### ISSUE TITLE
Cannot resolve symbol 'TransportProtos'

### ISSUE THREAD

**Issue by yseryg** [thingsboard/thingsboard#4215]
Cannot resolve symbol 'TransportProtos'

 
import org.thingsboard.server.gen.transport.TransportProtos;
in
/common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttSslHandlerProvider.java

**Comment by yseryg** [comment]
nofind TransportProtos

**Comment by ashvayka** [comment]
execute 'mvn generate-sources'
