### ISSUE TITLE
Thingsboard Error When Building from Source

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4217]
Hello !
I am trying to build from source the original version of TB 3.2.2 using : mvn clean install.
Every time I get the following errors :

>  Thingsboard ........................................ SUCCESS [  4.529 s]
[INFO] Netty MQTT Client .................................. SUCCESS [ 10.880 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.943 s]
[INFO] Thingsboard Server Common Data ..................... FAILURE [ 21.124 s]
[INFO] Thingsboard Server Common Utils .................... SKIPPED
[INFO] Thingsboard Server Common Messages ................. SKIPPED
[INFO] Thingsboard Actor system ........................... SKIPPED
[INFO] Thingsboard Server Stats ........................... SKIPPED
[INFO] Thingsboard Server Queue components ................ SKIPPED
[INFO] Thingsboard Server Commons ......................... SKIPPED
[INFO] Thingsboard Server Common Transport components ..... SKIPPED
[INFO] Thingsboard MQTT Transport Common .................. SKIPPED
[INFO] Thingsboard HTTP Transport Common .................. SKIPPED
[INFO] Thingsboard CoAP Transport Common .................. SKIPPED
[INFO] Thingsboard Server Common DAO API .................. SKIPPED
[INFO] Thingsboard Extensions ............................. SKIPPED
[INFO] Thingsboard Rule Engine API ........................ SKIPPED
[INFO] Thingsboard Server DAO Layer ....................... SKIPPED
[INFO] Thingsboard Rule Engine Components ................. SKIPPED
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport Service ................. SKIPPED
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.026 s
[INFO] Finished at: 2021-03-09T08:13:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project data: There are test failures.
[ERROR]
[ERROR] Please refer to /home/lmax25/thingsboard/common/data/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/lmax25/thingsboard/common/data && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java --illegal-access=permit -jar /home/lmax25/thingsboard/common/data/target/surefire/surefirebooter5849009768687459234.jar /home/lmax25/thingsboard/common/data/target/surefire 2021-03-09T08-13-09_365-jvmRun1 surefire6959766436431536432tmp surefire_04415011564806758246tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/lmax25/thingsboard/common/data && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java --illegal-access=permit -jar /home/lmax25/thingsboard/common/data/target/surefire/surefirebooter5849009768687459234.jar /home/lmax25/thingsboard/common/data/target/surefire 2021-03-09T08-13-09_365-jvmRun1 surefire6959766436431536432tmp surefire_04415011564806758246tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:991)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:837)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]

Can somebody tell me how to compile the project without errors ?

Thank You !

Environment :
Ubuntu 18.04
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_282, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-136-generic", arch: "amd64", family: "unix"

**Comment by vvlladd28** [comment]
Hi @lmax25,
The problem is that we are updating the master branch to the version of OpenJDK 11. Please configure your operating system to use OpenJDK 11 by default. You can configure which version is the default using the following command:
`sudo update-alternatives --config java`

**Comment by lmax25** [comment]
I did updated and configured as default OpenJDK 11.
After running  mvn clean install -Ddockerfile.skip=false
I get the following error :

 ThingsBoard Docker Images .......................... FAILURE [  6.592 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.962 s
[INFO] Finished at: 2021-03-09T15:57:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tb: Could not resolve dependencies for project org.thingsboard.msa:tb:pom:3.2.2-SNAPSHOT: Could not find artifact org.thingsboard:application:deb:deb:3.2.2-SNAPSHOT in central (https://repo1.maven.org/maven2/) -> [Help 1]
[ERROR]

I found on the internet this command mvn dependency::tree and I get the following error :
[ERROR] Failed to execute goal on project tb: Could not resolve dependencies for project org.thingsboard.msa:tb:pom:3.2.2-SNAPSHOT: Could not find artifact org.thingsboard:application:deb:deb:3.2.2-SNAPSHOT in central (https://repo1.maven.org/maven2/) -> [Help 1]

What is wrong now ?!

Thank You !

**Comment by vvlladd28** [comment]
Please check version JDK in maven, using a command: `mvn --version`

**Comment by lmax25** [comment]
mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-136-generic", arch: "amd64", family: "unix"

and
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by Ultrazombie** [comment]
Closed, as not active.
