### ISSUE TITLE
[Question] I can create search bar to enter address ?

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4222]
**Component**

 * Generic

**Description**
I need to create a search bar, for my map widget, can I do that?
![image](https://user-images.githubusercontent.com/78015483/110752657-db633b80-8245-11eb-8517-8d5c7e8135c2.png)

**Environment**

 * OS:  windows 10
 * ThingsBoard: ThingsBoard v.3.2.1PE
 * Browser: google chrome

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
