### ISSUE TITLE
[Question] How to change dashboard title?

### ISSUE THREAD

**Issue by jarisevon** [thingsboard/thingsboard#4226]
**Component**

 * UI

**Description**
It seems that dashboard title is not updated on dashboard layout if it has been changed 
from initial title value. 
Here initial value was "More Test" and was later changed to "A2 Daily".
Pics attached.
![3](https://user-images.githubusercontent.com/22496384/110778747-6d316f80-826b-11eb-88e0-176238b5dc71.jpg)
![2](https://user-images.githubusercontent.com/22496384/110778752-6dca0600-826b-11eb-87f1-92f8a5996cac.jpg)
![1](https://user-images.githubusercontent.com/22496384/110778754-6dca0600-826b-11eb-98c0-c534f9bab581.jpg)

**Environment**

 * OS:  Windows Server 2012
 * ThingsBoard: 3.2.1
 * Browser: Chrome 89.0.4389.82

**Comment by ChantsovaEkaterina** [comment]
Hello, @jarisevon 
What you are seeing in the toolbar is the name of the default dashboard state.
After renaming the dashboard you need to change the default state name too if you would like it to be the same as the dashboard name.
