### ISSUE TITLE
[Bug] Button list device in map widget no exist

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4228]
**Describe the bug**
In this video https://www.youtube.com/watch?v=WH5miq2zSPw in the min 1:26 when him touch the icon list the diveces (Thermometer-A, Thermometer-B, Thermometer-C), but when i created the same input map widget the icon the list device does not exist.

![image](https://user-images.githubusercontent.com/78015483/110782472-77ea0580-8267-11eb-8ba1-8b4b12676093.png)

can you pass me the code of the custom action to list the devices

**Your Server Environment**

  * ThingsBoard v.3.2.1PE

**Desktop (please complete the following information):**

* OS: windows 10
* Browser chrome
* ThingsBoard v.3.2.1PE

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
In video tutorials were written for TB v2.x. 
In TB 3.0, we changed the logic of adding markers to the map. Presently to add a marker to the map, drag the marker symbol (located in the upper right corner of the map) to the place where you want to set the location. After placing the marker on the map, will be show tooltip with a list of entities to set the location. You will need to click on the name of the entity to store the storage location.

**Comment by AbrahamSalvi** [comment]
Hi @vvlladd28,
thanks for answering my message, do you know if you can create a search bar on the widget map? i am using openstreetmap.
Thanks a lot

**Comment by vvlladd28** [comment]
Hi,
You need to create a [filter](https://thingsboard.io/docs/user-guide/advanced-filters/).

**Comment by AbrahamSalvi** [comment]
Hi, 
Thanks, it is a solution, but what I want to do is search an address and have it redirect in the map widget.

In this type
![image](https://user-images.githubusercontent.com/78015483/110942643-6291db80-833a-11eb-829f-e1be4416e9da.png)

Thanks a lot

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
At the moment it is impossible to implement.

**Comment by ashvayka** [comment]
I believe it is possible to implement, but it is just not scheduled to any release yet.

**Comment by AbrahamSalvi** [comment]
Thanks!

**Comment by jonpodtu** [comment]
@vvlladd28 I'm having problem adding markers as there is no marker symbol to drag from the corner. I can add the markers by the xPos and yPos variable in the shared attributes, however this is only suboptimal as I can't change the values through dragging around in the map.

I'm using the image map widget.

**Comment by ssakharova** [comment]
Hello @AbrahamSalvi,
Could you tell me please your problem is still relevant?

Regards
