### ISSUE TITLE
How to send Rest API Reply to console from Thingsboard Rule Chain?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#4229]
Background :
There are two devices configured in Thingsboard, Device #1 & Device #2.
Message Format:
```
Device #2 Name : ...
Device #2 Status : ...
```
We POST a telemetry data to Device #1 using cURL command from Cmd Prompt in Windows OS  & this data also includes the identity details of Device #2.
Once Device #1 receives telemetry data, it forwards it to Device #2 based on whether telemetry data contains identity parameters of Device #2. Current approach here, configured a Rule Chain that checks the input message and sends a "Rest API Call" to "Device #2" with device id.

But how to get the status from the external "Rest API Call" node and send it back to the console?

**Comment by Ultrazombie** [comment]
The description of your task sounds like a gateway device and its child, in which case we recommend using an mqtt gateway api. Your current app is not flexible for production.
https://thingsboard.io/docs/reference/gateway-mqtt-api/
