### ISSUE TITLE
[Question] how to search by substring of name?

### ISSUE THREAD

**Issue by luixal** [thingsboard/thingsboard#4231]
**Component**

 * UI

**Description**
In the _Devices_ page, when trying to search for a device using part of the name it doesn't show any results, I have to match the name from the beggining.

Example:

I have a device called _"D1 - First Device"_. If I click on the search icon and type _"first"_, it should show this device but it doesn't. If I type _"D1"_ then it is shown.

This makes finding devices really hard.

**Environment**
 * OS:  Ubuntu Server
 * ThingsBoard: 3.1.1
 * Browser: Chrome, latest

**Comment by vvlladd28** [comment]
Hi @luixal,
To search for a device using part of the name, write search text starts with the special character "%". For example, there is a device with the name "_D1 - First Device_" to search for it can enter search phrases: "_%first_" or "_D1_".

**Comment by luixal** [comment]
Hi @vvlladd28 , I show examples of that, but that doesn't work when I try it.

I have many devices, like in this list:

![image](https://user-images.githubusercontent.com/615268/112716649-e37ad680-8ee7-11eb-9b8e-83f305b932a1.png)

When I try to search by part of the name, using the % char, weird things happens. Sometimes, it shows nothing:

![image](https://user-images.githubusercontent.com/615268/112716661-f8f00080-8ee7-11eb-9ec0-9e9fa16d8e25.png)

others, it shows all devices, not filtering at all:

![image](https://user-images.githubusercontent.com/615268/112716670-00afa500-8ee8-11eb-995c-9da44cfc9652.png)

Am I doing something wrong?

Thanks!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
