### ISSUE TITLE
Required permission to create entity relation[Bug] 

### ISSUE THREAD

**Issue by lilalukas** [thingsboard/thingsboard#4234]
**Describe the bug**
The creation of a entity relation is only possible with generic and not with group permission.
I created a user with limited permissions to read and write only the entities of a customer. When the user tries to add a relation between asset and device he is not able to select the entity type. Even with permissionlevel _all_ for the device and asset-group it does not work. Only if the generic permission read/write is granted the selection is possible but every device (not only devices in the specific group) is listed.

**Your Server Environment**
TBPE 3.2.1

**Your Client Environment**
Desktop, Win10, Chrome 89

**To Reproduce**
1. Create Customer
2. Create Asset and Device Group inside Customer
3. Create usergroup and create Tenent-user to this group
4. Add _group_-roles read/write
5. Set permissions of usergroup to read/write the asset and device group inside of customer
6. add Asset and Device to group
7. Try to add realtion between device and asset
8. Selection of Entity-Type will fail
9. --
10. Create generic role for read/write
11. Add role to user group
12. Adding relation will work but in selection every other tenant-device is listed

**Comment by ashvayka** [comment]
@YevhenBondarenko , please investigate this.

**Comment by YevhenBondarenko** [comment]
Hi @lilalukas,

**Comment by YevhenBondarenko** [comment]
Hi @lilalukas,
we have checked this issue and think this behavior is correct because group roles read/write not permits to add relations. 
To exclude this confusion, we are planning to remove the add relations button.

**Comment by lilalukas** [comment]
Hi @YevhenBondarenko,
thanks for looking into it.
Am I right, that it will not be possible for a user with limited access to device and asset groups to create relations between them?

Thanks
Lukas

**Comment by YevhenBondarenko** [comment]
Yes, you are right.

**Comment by lilalukas** [comment]
I would like to request this as a future feature since we may have multiple _projectUsers_ who should have the limited group based access but also should be alowed to create relations between these entities. 

Thank you very much for the quick respond!
