### ISSUE TITLE
Cannot Update Shared Attribute with the assigned user credential

### ISSUE THREAD

**Issue by openedhardware** [thingsboard/thingsboard#4237]
**Description**
I have made a custom widget to update the devices' shared attributes by using the following code and added it to a dashboard:

```javascript
attributeService = $scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
attributeService.saveEntityAttributes(
            self.ctx.datasources[index].entity.id,
            'SHARED_SCOPE',
            [
                {
                    key: name,
                    value: val
                }
            ]
        ).subscribe(
            function success() {
                alert('Successfully Updated!');
            },
            function fail() {
                
            }
        );
```
If I login to the dashboard with a tenant admin, I can update the shared attribute.

But if I assign the dashboard to a customer and login to the dashboard with a customer user, I cannot update the shared attribute of the device:

![image](https://user-images.githubusercontent.com/16890683/110933626-f6c66780-8367-11eb-893a-71183207402d.png)

![image](https://user-images.githubusercontent.com/16890683/110934131-97b52280-8368-11eb-808c-4585da6507f0.png)

Do I need a permit to allow customer users to modify the shared attributes of the device that is assigned to them?

Thanks! 

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: version 3.2.0
 * Browser: Latest Chrome

**Comment by ahmed-1a** [comment]
CE v3.2.0

I used the widget for updating a server side attribute, I also received the same error, a customer user couldn't update it.
A tenant user can without a problem. 

The use of the server-side attribute is a threshold value for an alarm related to a device.

**Comment by jpeg2600** [comment]
I'm trying to figure out the solution proposed in #1726 if it can help you

Is there any plan to fix it in CE ?

**Comment by ahmed-1a** [comment]
It seems the [solution](https://github.com/thingsboard/thingsboard/issues/1726#issuecomment-774536729) is the easiest but it requires rebuilding thingsboard. 

But I haven't tested it myself.

**Comment by openedhardware** [comment]
Yes, built from source again and it works! :)
Here is a result deb file if you want - http://0x0.st/-ZRZ.deb

**Comment by EmbeddedDevver** [comment]
> Yes, built from source again and it works! :)
> Here is a result deb file if you want - http://0x0.st/-ZRZ.deb

Can you show me the exact file changes that you have done? Or maybe send me the new file so I can compare it with the original?

I think it was in the file below, right? Please let me know so I can make a pull requests to the dev to integrated it in newer versions... 

https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/permission/CustomerUserPermissions.java

**Comment by openedhardware** [comment]
Yes, added `put(Resource.DEVICE, TenantAdminPermissions.tenantEntityPermissionChecker);` to that file.

**Comment by EmbeddedDevver** [comment]
> Yes, added `put(Resource.DEVICE, TenantAdminPermissions.tenantEntityPermissionChecker);` to that file.

Thanks to you all it has been fixed in the next release, see https://github.com/thingsboard/thingsboard/commit/60c141d3ca5b154fa48fd0a9c047c6ca504962a4
