### ISSUE TITLE
Error installing Thingsboard on Rpi 3

### ISSUE THREAD

**Issue by baraynavab** [thingsboard/thingsboard#424]
Hi, I tried installing TB on Rpi 3 but when I put in the install script here's the error I am getting. I think it has to do with either not having a DB or not having the DB installed. Can you please point me to the right direction? 

pi@rpi1:~ $ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'databaseSchemaService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlDatabaseSchemaService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.datasource.url' in string value "${spring.datasource.url}"
ThingsBoard installation failed!

**Comment by mp-loki** [comment]
Hi @baraynavab. Can you please attach your thingsboard.yml ?

**Comment by baraynavab** [comment]
here it is attached as a txt file. Since Git didnt allow me to attached it directly. 

[thingsboard.yml.txt](https://github.com/thingsboard/thingsboard/files/1480052/thingsboard.yml.txt)

**Comment by mp-loki** [comment]
I assume you are using the default HSQLDB configuration.
The only issue I see now with your configuration file is that the line `HSQLDB DAO Configuration` Should be commented out, because it is a comment, but not the part of configuration. 
Can you just add a # in front of it and try to re-run the install script? 
`#HSQLDB DAO Configuration`

**Comment by baraynavab** [comment]
I commented all of the HSQLDB this out and save the yml file. 

#HSQLDB DAO Configuration
#spring:
#  data:
#    jpa:
#      repositories:
#        enabled: "true"
#  jpa:
#    hibernate:
#      ddl-auto: "validate"
#    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H$
#  datasource:
#    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.hsqldb.jdbc.JDBCDriver}"
#    url: "${SPRING_DATASOURCE_URL:jdbc:hsqldb:file:${SQL_DATA_FOLDER:/tmp}/thi$
#    username: "${SPRING_DATASOURCE_USERNAME:sa}"
#    password: "${SPRING_DATASOURCE_PASSWORD:}"

and executed the following again but I get the same error

pi@rpi1:/ $ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'databaseSchemaService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlDatabaseSchemaService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.datasource.url' in string value "${spring.datasource.url}"
ThingsBoard installation failed!

**Comment by baraynavab** [comment]
Additionally I did the following to see if it makes a different to the yml file. 

`#HSQLDB DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "validate"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.HS$
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.hsqldb.jdbc.JDBCDriver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:hsqldb:file:${SQL_DATA_FOLDER:/tmp}/thin$
    username: "${SPRING_DATASOURCE_USERNAME:sa}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"

`

but still no luck.. i got the following other error

`pi@rpi1:/ $ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5FA2A25F0F.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:262)
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:212)
	at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:38)
	at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:91)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:254)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:123)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:131)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
`

**Comment by mp-loki** [comment]
@baraynavab, sorry, I meant to comment out only the `#HSQLDB DAO Configuration` line, not the whole HSQLDB  section. So far your configuration looks correct.

The error `org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!` means that the database was created and demo data is already loaded during one of your previous runs of install.sh script.

What I would suggest you to do now is:

1) run `sudo service thingsboard start` and see if ThingsBoard goes up
2) if it does not help - delete manually the HSQLDB database files: `rm -rf /tmp/thingsboardDb*`
and then run `install.sh` again

Let me know how it goes.

**Comment by ashvayka** [comment]
to wipe the data folders use 

> rm -rf /usr/share/thingsboard/data/sql/thingsboardDb*

**Comment by baraynavab** [comment]
Ok sorry for the late reply. I managed to get it installed after I deleted the HSQLDB db files via the **rm -rf /tmp/thingsboardDb*** command and the data folder wipe via the **rm -rf /usr/share/thingsboard/data/sql/thingsboardDb*** command.

Here's the install script output. 

`pi@rpi1:/etc/thingsboard/conf $ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================


log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB600634D3EA.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Loading demo data...
Installation finished successfully!
ThingsBoard installed successfully!`

But when I go to start Thingboard. I dont think its started. When I look at the log file I get the following. 

`2017-11-28 06:03:56,472 [main] ERROR o.s.boot.SpringApplication - Application startup failed
2017-11-28 10:09:35,681 [main] ERROR o.s.boot.SpringApplication - Application startup failed
2017-11-28 13:04:32,156 [main] ERROR o.s.boot.SpringApplication - Application startup failed
`

**Comment by mp-loki** [comment]
Any logs in /var/log/thingsboard?

**Comment by baraynavab** [comment]
Here's the attached log file of the last 500 messages. 

[thingboard_error_log.txt](https://github.com/thingsboard/thingsboard/files/1514790/thingboard_error_log.txt)

**Comment by mp-loki** [comment]
@baraynavab 
`Error creating bean with name 'MqttTransportService': Invocation of init method failed; nested exception is java.net.BindException: Address already in use`
It means that another application is already running on port 1883 on your system, most likely an mqtt broker, like mosquitto or smth like that.
What you can is do either:
 - shut down the process which has occupied port 1883
 - or go to thingsboard.yml and change the port in mqtt section of configuration in order to resolve conflict.

Hope it helps

**Comment by mbihari** [comment]
Go to pgadmin delete your thingboard bata base and 
again cretae the database thingsboard..
