### ISSUE TITLE
[Question] UI - Adding Croatian language

### ISSUE THREAD

**Issue by alenhrga** [thingsboard/thingsboard#4241]
**Component**

* UI

**Description**

Is it okay if I add *Croatian* language locale in UI (ui-ngx) and make a pull request?

**Comment by vvlladd28** [comment]
Hi @alenhrga,
Yes, it will be great if you do pull request

**Comment by ashvayka** [comment]
Hi @alenhrga , we welcome you to create a PR. Closing the issue due to it is obviously fine to submit PRs with translations.
