### ISSUE TITLE
[Feature Request] Add bulk device creation API method

### ISSUE THREAD

**Issue by viktorkho** [thingsboard/thingsboard#4242]
**Is your feature request related to a problem? Please describe.**
We are going to integrate TB with our provisioning subsystem, we want to create multiple (hundreds of) devices with single request. Now we have to wait a long time while TB creates devices, including CSV import.

**Describe the solution you'd like**
We expect TB to provide API method for bulk devices creation.

**Comment by Hardikrathod01** [comment]
Hi,
I would like to start working on this feature,has anybody started working on this feature?

**Comment by dharapatel1596** [comment]
Hi,
I would like to start working on this feature,has anybody started working on this feature?
Also, if nobody has picked this up yet, then how do you suggest to approach this? I believe at the moment, each device's payload is picked up and device is created. Then another payload for another device and repeat the procedure.

Instead I can think of a common approach where, CSV import sends all the payloads at one go to the API and we modify API as well as front end to support this.
