### ISSUE TITLE
[Question] Can I set dataSort or sortingDataAccessor from an Entity Table?

### ISSUE THREAD

**Issue by adamwolf** [thingsboard/thingsboard#4243]
**Component**

 * Generic

**Description**

Hi folks!

I have opened up the Entity Table Widget and saved a copy, and am trying to override the sorting.  I think I can do it if I can set dataSort or sortingDataAccessor for the entityDataSource for the sort table, but I'm not having much luck.  Is this even something I can do from the widget, or would this require Angular component changes?

**Environment**
 * ThingsBoard: PE Cloue

**Comment by vvlladd28** [comment]
Hi @adamwolf,
This sort order set in entity table widget. Your need to navigated tabs  'Advance settings' in edit widget mode and configure setting `Default sort order`. Described in more detail in the documentation on [Entity Table](https://thingsboard.io/docs/user-guide/ui/entity-table-widget/#4-sorting-the-data-in-the-table-widget)

**Comment by adamwolf** [comment]
I'm sorry by the way if I actually assigned someone?! I did not mean to be rude!

**Comment by ashvayka** [comment]
Hi @adamwolf , have you set the order using tips from @vvlladd28 ?

**Comment by adamwolf** [comment]
I would like to sort on something that isn't directly a key.  I was able to
do it by creating a content function that added a hidden div that has
appropriate sorting.  I don't think that's the best idea but it's the best
I could come up with.
