### ISSUE TITLE
[Feature Request]Full e2e API support for user registration and password reset

### ISSUE THREAD

**Issue by amizer12** [thingsboard/thingsboard#4245]
Hi,
I'm running Thingsboard in headless mode as well as many of us users of this great system.
The main thing i'm currently missing is a full user registration and password reset in API. I have now a workaround in place that calls multiple calls to API to create a user, activate it and etc via existing API, the same for pass reset but it would be awesome to have this out of the box in thingsboard.
This is the biggest blocker right now for expanding this tool into full headless mode with user registration and self password reset outside of Thingsboard UI and via dedicated app.
If you can consider this as a feature request for next upcoming releases i think it would be a step in a very right direction, considering how big the headless is now in every possible tech domain.

**Comment by Ultrazombie** [comment]
No one has shown further interest in this, so it has been rejected. Please create a new feature request if you still consider this valid.
