### ISSUE TITLE
Technical architecture

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#425]
I would like to invest more in the source code for modifications.
I would like to confirm if I understand the architecture of TB so well.
First Mvn multiple modules(Backend and UI)
1.BACKEND
  1a-Sring boot
  1b-JPA-hibernate
  1c- Akka, netty
  1d- MQTT / Coap / Http

2.UI
2a- Angular / Api restful / websocket etc ...
2b- webpack.

My concern is that I do not understand so well the process.
From receiving data from sensors, persistence in the database cassandra and websocket to the view and API RESTfull

Someone can explain to me if  understands the process better please?

Thank you

**Comment by avlo** [comment]
hello, i see you've closed the question but without posting an answer.  did you ever discover/create an architecture document/diagram for TB as you've asked?

**Comment by avlo** [comment]
hello, i see you've closed the question but without posting an answer.  did you ever discover/create an architecture document/diagram for TB as you've asked?
