### ISSUE TITLE
[Question]/[Bug]  Docker building error

### ISSUE THREAD

**Issue by arkadiusz-czerwinski** [thingsboard/thingsboard#4250]
**Component**
Installation
**Description**
During an attempt on building docker container of docker build https://github.com/thingsboard/thingsboard/blob/master/msa/tb/docker-tb/Dockerfile
the following error is generated:
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to process "${pkg.name}.conf": missing ':' in substitution
```
I am not sure if it is bug or misuse so I kept both categories
**Environment**
 * OS:  Windows 10/ ubuntu

**Comment by alihajqani** [comment]
Were you able to solve your problem? I have a like problem.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
