### ISSUE TITLE
How to delete old timeseries data 

### ISSUE THREAD

**Issue by varun-mahajan** [thingsboard/thingsboard#4258]
**Component**
 * Generic

**Description**
Our use-case is to retain only X days of timeseries data. Looking for information on how to configure this and if it is supported out of box from thingsboard? 3.2.1 version has Tenant profiles, that has a setting "Default Storage TTL days". Just setting that alone is not helping. For each device in given tenant, we want to only retain 7 days data and auto-delete the older data.

We are using postgres and not cassandra. As per thingsboard config, under sql section there are some TTL related options, but they don't seem to be impacting and help in purging either.

ttl:
      ts:
        enabled: "${SQL_TTL_TS_ENABLED:true}"
        execution_interval_ms: "${SQL_TTL_TS_EXECUTION_INTERVAL:86400000}" # Number of milliseconds. The current value corresponds to one day
        ts_key_value_ttl: "${SQL_TTL_TS_TS_KEY_VALUE_TTL:0}" # Number of seconds

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.2.1 with Postgres
 * Browser: NA

**Comment by trikimiki** [comment]
Hello!

Please refer to this doc for a more detailed description of particular config properties: https://thingsboard.io/docs/user-guide/install/config/

You are looking at the correct properties - you need to change _sql.ttl.ts.ts_key_value_ttl_ value to 7x24x60x60=604800 in order for your TTL to work. Note that this will affect ALL devices.

Also, note that the new TTL value will not affect already written timeseries data. You will need to remove it manually. 

First of all, you need a day timestamp you want to delete old data before in milliseconds (epoch time).
You can get it on this site: https://www.epochconverter.com/
For example, you want to delete data before July 1, 2019, epoch time in ms is 1561939200*1000=1561939200000
Now run this in your PSQL console:
DELETE from ts_kv where ts < 1561939200000;

**Comment by varun-mahajan** [comment]
@trikimiki , thanks for your response. It is very helpful. Wasn't aware that existing data will not be deleted. 

Also, can you please share any information about Tenant profile setting value "TTL Storage Days". We wanted to control this per tenant and this seems to be right type of setting, but is not helping.

**Comment by ashvayka** [comment]
Hi @varun-mahajan , the "TTL Storage Days" setting works on the tenant level only for Cassandra DB. The PostgreSQL does not allow us easily configure the TTL on a row level basis.
