### ISSUE TITLE
Unable to build Thingsboard 1.4 from source

### ISSUE THREAD

**Issue by ethicstechOSS** [thingsboard/thingsboard#426]
Hi,
I am building TB 1.4 from source. My environment is Ubuntu 16.04, 64bit and Java  8. I am getting the error in Thingsboard Server DAO Layer Tes. Complete attached with this message. PFA. 
BTW, I did not installed Cassandra/PostgreSQL since it is optional. 

TIA,
Prakash.

**Comment by ethicstechOSS** [comment]
Unable to attach a file. The log info is here, https://pastebin.com/BJKaMSHP

**Comment by ssmaurya** [comment]
Looks like your schema might not be set. You can try building using mvn clean install -DskipTests

**Comment by ethicstechOSS** [comment]
Thanks. That did the tricks. The compilation started. However, still facing another compilation issue:

[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [  3.093 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.135 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 10.798 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.020 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.056 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 19.682 s]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  2.478 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [  9.332 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.062 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  5.703 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  1.945 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  5.638 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  1.302 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.062 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  1.153 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  2.196 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  1.532 s]
[INFO] Thingsboard Server UI .............................. FAILURE [01:22 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:32 min
[INFO] Finished at: 2017-11-18T13:44:08+00:00
[INFO] Final Memory: 75M/203M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 137) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui

**Comment by ssmaurya** [comment]
You need to retry building it after removing node_modules folder from ui

**Comment by ethicstechOSS** [comment]
I removed the node_modules in thingsboard/ui/ folder. Then recompiled. Still getting the same error. This time I noted the node_modules folder available in thingsboard/ui/node/ folder. If I removed this folder and rebuild, again getting the same error and the node_modules folder created in /thingsboard/ui/. 

I also noticed this log during compilation:

Building Thingsboard Server UI 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ui ---
[INFO] Deleting /root/thingsboard/ui/target
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ ui ---
[INFO] Installing node version v6.9.1
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/node/6.9.1/node-6.9.1-linux-x64.tar.gz into /root/thingsboard/ui/target/node/tmp
[INFO] Copying node binary from /root/thingsboard/ui/target/node/tmp/node-v6.9.1-linux-x64/bin/node to /root/thingsboard/ui/target/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 3.10.8
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/npm/3.10.8/npm-3.10.8.tar.gz into /root/thingsboard/ui/target/node/node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
[INFO] Running 'npm install' in /root/thingsboard/ui
[WARNING] npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by logivity** [comment]
Please try to stop thingsboard server and build again.

**Comment by ethicstechOSS** [comment]
Kindly note that I am building TB on a fresh cloud Ubuntu and I dont have any other running TB service to stop it.

**Comment by ethicstechOSS** [comment]
I added --allow-root option in UI pom.xml file and enabled -X for full debugging. Here is the detailed error message,

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install --allow-root' failed. (error code 137) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install --allow-root' failed. (error code 137)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui

**Comment by ethicstechOSS** [comment]
Looks like it is a known issues which is not yet resolved, #298, https://github.com/thingsboard/thingsboard/issues/298

**Comment by ethicstechOSS** [comment]
I fixed the issue by using the least version of npm & node as per the advise from @datthanhvu98
But I am not sure why the main source still uses older version of node & npm in pom.xml file. 

Solution : 
Modify the file https://github.com/thingsboard/thingsboard/blob/master/ui/pom.xml and edit the node & npm version as like the below. 

 <nodeVersion>v8.9.1</nodeVersion>
                            <npmVersion>5.5.1</npmVersion>

**Comment by mp-loki** [comment]
Hi @ethicstechOSS! Feel free to submit a PR with this change

**Comment by gaurav20-07** [comment]
Hi @ethicstechOSS, I tried updating the ui/pom.xml with the latest versions of node and npm after that build is giving the following error "some files do not have the expected license header". Can you please help me out.

**Comment by mp-loki** [comment]
@gaurav20-07 run `mvn license:format` from project root folder

**Comment by stephenvxx** [comment]
@gaurav20-07  nope, actually i think u should install a lastest version of npm. I fixed my bug on this way. Good luck !

**Comment by piotrlinski** [comment]
CentoOS  -> sudo yum install libpng-devel
Ububtu --> sudo apt-get install libpng-dev

worked for me...
