### ISSUE TITLE
[Bug] Switch control widget not working on dashboard load

### ISSUE THREAD

**Issue by wenzul** [thingsboard/thingsboard#4263]
Immediately after displaying a dashboard (for all), the Switch control widget does not display a true value (MQTT RPC). The corresponding RPC request is sent and logged on the client side. Also in the browser I see the POST request with the response true. As soon as I click on the dashboard modify or even just drag the window smaller the switch control state adjusts itself to ON. No further request is triggered for this. The Round Switch widget on the other hand works.

I dont't know it exactly since when it breaks. In 2.x it worked.

After Dashboard load...
![grafik](https://user-images.githubusercontent.com/8477202/111618622-e3425300-87e4-11eb-9a15-036d8d754475.png)

Log on client side...
MQTT: Connected with result code 0
Topic: v1/devices/me/rpc/request/46 Message: b'{"method":"getValue"}'
This is a RPC call. RequestID: 46. Payload: b'{"method":"getValue"}'. Going to reply now!
Topic: v1/devices/me/rpc/request/45 Message: b'{"method":"getValue"}'
This is a RPC call. RequestID: 45. Payload: b'{"method":"getValue"}'. Going to reply now!

E.g. after enter edit mode... same for resizing.
![grafik](https://user-images.githubusercontent.com/8477202/111620323-da528100-87e6-11eb-9a4a-9ce51c7f9302.png)

Own 3.2.1PE setup on local infrastructure.

Firefox 64-Bit 86.0 and Chromium Version 86.0.4188.0 (64-Bit)

**Expected behavior**
Show the actual value of Switch control on page load.

Maybe related https://github.com/thingsboard/thingsboard/issues/3994 https://github.com/thingsboard/thingsboard/pull/4331

**Comment by wenzul** [comment]
I guess related to https://github.com/thingsboard/thingsboard/pull/4331.

**Comment by Ultrazombie** [comment]
Inactive. ThingsBoard fixed this a lot of versions ago.
