### ISSUE TITLE
[Question] Change color of rows in widget

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4264]
**Component**

 * Generic

**Description**
Hello everyone, I need to change the color of my row according to the state of the device. for example: if it is on then the yellow row. is this possible to do? 
I'm using Entitty admin widgets - Device admin table widget
![Captura](https://user-images.githubusercontent.com/78015483/111628863-f78c4d00-87f0-11eb-9b89-6bb320dfc957.PNG)

**Environment**

 * OS:  Windows 10 pro
 * ThingsBoard: ThingsBoard v.3.2.1PE
 * Browser: chrome

**Comment by ashvayka** [comment]
Hi @AbrahamSalvi . Stay tuned for v3.2.2 release. We have added this feature just recently. @Dshcherbyna will document it next week. You can explore it on demo.thingsboard.io

**Comment by AbrahamSalvi** [comment]
Thanks @ashvayka! i will see
