### ISSUE TITLE
[Bug] Customer Users being created randomly in 'Tenant Administrators' Group

### ISSUE THREAD

**Issue by Manusisko** [thingsboard/thingsboard#4265]
**Describe the bug**
On seemingly random events, as we have tried to identify, a 'Tenant Administrators' group is created in the Customer's Users Groups and one or more users are added to it. Mostly newly created users suffer this event upon creation, although only some of them. Users in this group belong to the Customer, but DO NOT belong to the user group 'ALL'. Detection of these events has been impossible to reproduce.

NOTE:
This appears to occur only in one of our servers.
All users created from a Tenant Account but whilst properly setting the customerId and ownerId fields in the REST api request.
Attempting to add these users to User Group ALL is imposible in the UI as this group doesn't show up in there.
Issue might be related with the EntityGroupId query parameter of the saveUser service.
 
**Your Server Environment**

* own setup
  * Cloud Deployment in AWS EC2
  * ThingsBoard Version 3.2.1 (has been ocurring since 2.4+)
  * OS Name and Version: Ubuntu 18.04
  * PostgreSQL DB setup in AWS RDS Server.

**Client Setup**
  * Issue occurs on any Device, when creating users from the REST API in the backend. The execution is handled by a Middleware REST API Service.

* Connectivity
  * HTTP
 

**Expected behavior**
Users should be created in the desired GROUP and in ALL Group, in order to have proper permissions.

**Screenshots**
![image](https://user-images.githubusercontent.com/39056975/111630671-5c37af80-87d1-11eb-8c4f-8f0b1f1809d1.png)

**Comment by ashvayka** [comment]
Hi @Manusisko , please contact us via support@thingsboard.io and specify this ticket. We will transform it to the Help Desk. Github issues is not the best place to discuss TB PE tickets.
