### ISSUE TITLE
Invalid flag --release

### ISSUE THREAD

**Issue by Hardikrathod01** [thingsboard/thingsboard#4268]
**Component**

 * Installation

**Description**
When I run the command
cd ${TB_WORK_DIR}
mvn clean install -DskipTests I get the error that invalid flag --release. Whereas, if i run the same command for release-3.2 branch, I do not get this error. Any help would be appreciated. 

**Environment**

 * OS:  Windows
 * ThingsBoard: master branch

**Comment by SamueleCarboni** [comment]
Same here

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
