### ISSUE TITLE
Tenant level access privileges to customer users

### ISSUE THREAD

**Issue by ssmaurya** [thingsboard/thingsboard#427]
Currently customer users do not have access to creation of devices, dashboards and assets for their own use. There are scenarios where customer users should be given this access. Is this feature planned to be included in TB. Enabling of  this feature can be configurable through customer card when customer entity is created by Tenant. Only difference would that customer user created devices, dashboards and assets would be automatically assigned to the customer.

**Comment by vparomskiy** [comment]
Starting from ThingsBoard PE 2.3  you can assign different roles to different user groups. Here is a feature description:
https://thingsboard.io/docs/user-guide/rbac/
