### ISSUE TITLE
[Question] Error Installing Thingsboard

### ISSUE THREAD

**Issue by med-belouaer** [thingsboard/thingsboard#4274]
**Component**

 * Installation

**Description**
I'm getting this error during the installation, i tried using docker this time and i'm getting the same error over and over, i trying on a ubuntu 18 instance (openstack) and i can't find a solution. I followed the documentation ( i tried on a AWS EC2 instance and it work just fine) 

Starting ThingsBoard installation ...
mytb_1  |  ===================================================
mytb_1  |  :: ThingsBoard ::       (v3.2.1)
mytb_1  |  ===================================================
mytb_1  | 
mytb_1  | Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'psqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRuleChainService': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'entityService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseEntityService': Unsatisfied dependency expressed through field 'assetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseAssetService': Unsatisfied dependency expressed through field 'assetDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaAssetDao': Unsatisfied dependency expressed through field 'assetRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetRepository' defined in org.thingsboard.server.dao.sql.asset.AssetRepository defined in @EnableJpaRepositories declared on JpaDaoConfig: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Using named parameters for method public abstract org.springframework.data.domain.Page org.thingsboard.server.dao.sql.asset.AssetRepository.findAssetInfosByTenantId(java.util.UUID,java.lang.String,org.springframework.data.domain.Pageable) but parameter 'Optional[tenantId]' not found in annotated query 'SELECT new org.thingsboard.server.dao.model.sql.AssetInfoEntity(a, c.title, c.additionalInfo) FROM AssetEntity a LEFT JOIN CustomerEntity c on c.id = a.customerId WHERE a.tenantId = :tenantId AND LOWER(a.searchText) LIKE LOWER(CONCAT(:textSearch, '%'))'!

**Environment**

 * OS:  Ubuntu 18.04.5 LTS on Openstack
 * ThingsBoard: 3.2.1

**Comment by med-belouaer** [comment]
@ashvayka Any help please !

**Comment by lsyer** [comment]
I wonder which java version you used? It requires OpenJDK11.

**Comment by med-belouaer** [comment]
@lsyer the documentation on the official website says that it requires OpenJDK8. On the other hand I tried to run it using docker containers, there is no java needed it's already built-in with the docker image but I had the same error for both ways.

**Comment by vvlladd28** [comment]
HI @med-belouaer,
The docker image also requires building source code on the local machine, which is then placed into the docker image. We have already updated the instructions for use OpenJDK 11.

**Comment by med-belouaer** [comment]
@vvlladd28 Now I get this error !

> Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/helpers/Util
> 	at org.slf4j.LoggerFactory.failedBinding(LoggerFactory.java:162)
> 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
> 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
> 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
> 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
> 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
> 	at org.thingsboard.server.ThingsboardInstallApplication.<clinit>(ThingsboardInstallApplication.java:27)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.Util
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 15 more
> ThingsBoard installation failed!
>

**Comment by loongwind** [comment]
> @vvlladd28 I had reset my VM and followed the new instructions with OpenJDK11. Now I get this error !
> 
> > Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/helpers/Util
> > at org.slf4j.LoggerFactory.failedBinding(LoggerFactory.java:162)
> > at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
> > at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
> > at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
> > at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
> > at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
> > at org.thingsboard.server.ThingsboardInstallApplication.(ThingsboardInstallApplication.java:27)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> > at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> > at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
> > at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> > at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
> > Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.Util
> > at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> > at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> > at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
> > at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> > ... 15 more
> > ThingsBoard installation failed!

@med-belouaer So am I. Have you solved it？

**Comment by soyoeml** [comment]
+1. I got same error too. I use docker method.

Starting ThingsBoard ...
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/helpers/Util
	at org.slf4j.LoggerFactory.failedBinding(LoggerFactory.java:162)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:142)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:46)
	at org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:41)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.Util
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more
waiting for server to shut down.... done
server stopped

**Comment by pavel-zdenek** [comment]
Ok so in my case, it was caused by running the Docker on Apple Silicon. I don't know how a JVM classloader failure could be caused by any of the quite low-level known issues https://docs.docker.com/desktop/mac/apple-silicon/#known-issues (mind that the image does not crash by itself and i run other JVMs in Docker just fine) but i know the blast radius of the problem and can avoid it. CC @ashvayka

**Comment by Ultrazombie** [comment]
Closed due to inactivity
