### ISSUE TITLE
[Question] How to use getValue for the switch to show the current state

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4276]
**Component**

 * Generic

**Description**
When I enter the view of my device, how can I make the value of the control widgets have the current value of my device?  and not always "off"

![Captura1](https://user-images.githubusercontent.com/78015483/111811462-5926e700-88d7-11eb-98b5-7a02157ffe5c.PNG)
![Captura2](https://user-images.githubusercontent.com/78015483/111811468-5a581400-88d7-11eb-9a5e-737981620910.PNG)

**Environment**

 * OS:  Windows 10 pro
 * ThingsBoard: ThingsBoard v.3.2.1PE
 * Browser: chrome

**Comment by ashvayka** [comment]
The RPC widget is sending the RPC call to your device. The device should reply with the value (true/false). If your device can't handle the RPC call, you should retrieve on/off value using attributes or telemetry. See Combobox on the screen you have shared. .

**Comment by AbrahamSalvi** [comment]
Hi @ashvayka,
This is what the switch returns (why params "null"?)

![Captura](https://user-images.githubusercontent.com/78015483/112291779-ba143d80-8c90-11eb-8701-2278af6de13d.PNG)

I control the rpc of setValue with this code, to send it the new value of the attribute and it works! but with "getValue" I don't know if I'm using the correct method

![Captura2](https://user-images.githubusercontent.com/78015483/112292249-2ee77780-8c91-11eb-9e15-ed78680d646a.PNG)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
