### ISSUE TITLE
one problem when reading source code

### ISSUE THREAD

**Issue by cc19931002** [thingsboard/thingsboard#428]
In class RuleActorMessageProcessor.java as showed below
  I find if "action.isOneWayAction()" returns false which means it is a "twoWayAction",the current thread will “pushToNextRule" util the corresponding "Plugin Actor" give a feedback or timeout. 
  Does these lead to blocking problem and why do you design this?
  I am think about here over and over again,could you pls help me?
![jt](https://user-images.githubusercontent.com/26158117/32988842-80ab274a-cd47-11e7-9a67-84d929ddc57f.png)

**Comment by ashvayka** [comment]
We are going to refactor this in new rule engine so I don't recommend to invest to much time here. It is complicated and new implementation will be simplified.

**Comment by vparomskiy** [comment]
This part of code was refactored. Closing
