### ISSUE TITLE
[Question] Alarm cleared with "wrong" message details

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#4280]
**Component**

 * Rule Engine

**Description**
The Alarm Cleared message has a wrong message details. I don't know if this is normal but the alarm cleared message is associated to the Alarm created message details (see screenshots). How can I get (or found) the alarm cleared message details?

1) I have defined the alarm rules (create and clear)
![screen1](https://user-images.githubusercontent.com/9846064/111976524-02512580-8b02-11eb-8863-44a89c5c82ba.png)

2) I have defined the flow in the rule engine and activated the debug option ...
![screen2](https://user-images.githubusercontent.com/9846064/111983364-57913500-8b0a-11eb-8660-e72bf225fc18.png)

3) The message details in the Alarm cleared message is the message details defined in the Alarm create rule ("Soglia max superata, valore attuale 60°C --> Max threshold exceeded, current value 60*).

![screen3](https://user-images.githubusercontent.com/9846064/111984547-cb800d00-8b0b-11eb-93fa-9e0e9644ff55.png)

I'd like to send the cleared message and not the created message.

What am I doing wrong?

**Environment**
 * OS:  Ubuntu linux
 * ThingsBoard: CE 3.2.1

**Comment by ashvayka** [comment]
Hi @shaphiro , this is already fixed in https://github.com/thingsboard/thingsboard/pull/4247
