### ISSUE TITLE
Custom Menu iFrame logout 

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#4281]
**Component**

 * UI
 

**Description**
Hi, 

we have created a custom menu for some of our dashboards. The problem we have is that when the session expires the login page is visible in the  iFrame and not in the broswer session.  We need to reload the page to redicted to the login page 

![iframeLogout](https://user-images.githubusercontent.com/45817004/111998113-5ff66980-8b24-11eb-8700-a229191e59a0.png)
![broswerLogout](https://user-images.githubusercontent.com/45817004/111999081-4e619180-8b25-11eb-8d16-6f6d7c515ebf.png)

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.2.2PE
 * Browser: chrome, Microsoft Edge

**Comment by ashvayka** [comment]
Custom menu supports links to the dashboards without iframe. Use "dashboardId" instead of "iframeUrl".

**Comment by angelikileonida** [comment]
Hi, 

we tried using the "dashboardId" instead of "iframeUrl" but after save the json resets to iframeUrl null. 
is there smth else that needs to be changed in the JSON configuration?

![dashboardId_3](https://user-images.githubusercontent.com/45817004/112115319-b8c80f80-8bc1-11eb-82a5-560e8f7cb748.png)
![dashboardId_2](https://user-images.githubusercontent.com/45817004/112115310-b82f7900-8bc1-11eb-802b-b03bfd8346b0.png)
![dashboardId_1](https://user-images.githubusercontent.com/45817004/112115316-b8c80f80-8bc1-11eb-8df1-5f9ea4c7481d.png)

**Comment by niovi** [comment]
Any update on this?

**Comment by angelikileonida** [comment]
Hi,
 any updates?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
