### ISSUE TITLE
Dashboard state : Open in separate dialog using custom action

### ISSUE THREAD

**Issue by innoagg** [thingsboard/thingsboard#4283]
*UI

How does one "Navigate to new dashboard state" using a widget custom action AND "Open in separate dialog"?

The docs don't seem to address the added feature to open state in separate dialog. 

**Environment**
 * ThingsBoard: 3.2.1

**Comment by ashvayka** [comment]
Please review this article: https://thingsboard.io/docs/user-guide/ui/widget-actions/#open-in-a-separate-dialog

**Comment by innoagg** [comment]
Sorry if the ticket was not clear, I am trying to do this with the
IStateController in a custom action script. How is that done?

**Comment by Adw1284** [comment]
```
widgetContext.actionsApi.openDashboardStateInSeparateDialog("update_devices", {}, "Update Devices", true);
```
`update_devices` is state id of dashboard state

Open state
```
function openDashBoardState(stateId, entityName, entityId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.stateController.updateState(stateId, params, false);
}
```

**Comment by G-Sivamanikandan** [comment]
Is there any default option to close the dashboard state dialog like closeDashboardState ?
