### ISSUE TITLE
Thingsboard doesn't work with Postgres

### ISSUE THREAD

**Issue by mripv6** [thingsboard/thingsboard#430]
After following the instructions to change from HSQLDB to Postgress, Thingsboard refuses to start. Here is the error log. The instructions don't mention changing the postgres user password, but I did so in thingsboard.yml. I'm running 1.3.1. I tried using 1.4-SNAPSHOT on another VM, but after a successful build, Thingsboard wasn't able to start. 

2017-11-19 18:01:47,336 [localhost-startStop-1] INFO  o.h.tool.hbm2ddl.SchemaVal
idator - HHH000229: Running schema validator
2017-11-19 18:01:47,353 [localhost-startStop-1] INFO  o.h.t.s.e.i.InformationExt
ractorJdbcDatabaseMetaDataImpl - HHH000262: Table not found: admin_settings
2017-11-19 18:01:47,354 [localhost-startStop-1] INFO  o.h.t.s.e.i.InformationExt
ractorJdbcDatabaseMetaDataImpl - HHH000262: Table not found: admin_settings
2017-11-19 18:01:47,362 [localhost-startStop-1] ERROR o.s.b.c.e.tomcat.TomcatSta
rter - Error starting Tomcat context. Exception: org.springframework.beans.facto
ry.UnsatisfiedDependencyException. Message: Error creating bean with name 'thing
sboardSecurityConfiguration': Unsatisfied dependency expressed through field 're
stAuthenticationProvider'; nested exception is org.springframework.beans.factory
.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticati
onProvider' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!
/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthent
icationProvider.class]: Unsatisfied dependency expressed through constructor par
ameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDepen
dencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dep
endency expressed through field 'relationService'; nested exception is org.sprin
gframework.beans.factory.UnsatisfiedDependencyException: Error creating bean wit
h name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#42c67d29' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#42c67d29': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory

Postgres databases:

                                   List of databases
    Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-------------+----------+----------+-------------+-------------+-----------------------
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
             |          |          |             |             | postgres=CTc/postgres
 thingsboard | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |

**Comment by xjz** [comment]
you need to create database and tables for thingsboard,there are sql scriptes in application/target/data after successfully building

**Comment by mripv6** [comment]
Thank you. That wasn't in the instructions, but it makes sense.

I couldn't find the sql files, so I went ahead and compiled version 1.3.1. The instructions are wrong. I had to use:

git clone https://github.com/thingsboard/thingsboard.git
cd thingsboard
git checkout release-1.3
mvn clean install

Then the files were located in thingsboard/application/target/data. I copied the files to the server then ran the scripts (order matters) using:

psql -U postgres -d thingsboard -h 127.0.0.1 -f schema.sql
psql -U postgres -d thingsboard -h 127.0.0.1 -f system-data.sql

sudo service thingsboard start

Watching the log file shows all is well. Now I can create my gateway and devices again. Hopefully, this will make Thingsboard stable. I'm running on a t2.micro instance in AWS. I moved the MQTT broker and TB-Gateway to another AWS instance. I also modified the configs to reduce the RAM consumed by java as per the instructions.

Thanks for your help.

**Comment by pushkar31** [comment]
Hi,
I did the database import and things board started on port 8080.
but on browser it says-: http://13.127.98.67:8080/

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jan 17 08:30:06 UTC 2018
There was an unexpected error (type=Not Found, status=404).
No message available
