### ISSUE TITLE
[Question] How to swap Map widget provider on the fly

### ISSUE THREAD

**Issue by JaMurphSmi** [thingsboard/thingsboard#4302]
I am trying to dynamically swap the map provider from Google Maps Satellite to OpenStreetMap.Mapnik and back on a user click to a widget header custom action.

I can access and change the values successfully, as I can see they are reflected in the form on click, however my action doesn't succeed in refreshing or applying the new values to the widget. They do apply when I modify something via the sidebar settings menu, and apply via the orange tick button there, however I don't want a user to have to do this every time.

Is there a way I can do the same as the orange tick from my custom action? 

Any input will be greatly appreciated.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
