### ISSUE TITLE
Update timewindow widget from antoher widget by Custom action

### ISSUE THREAD

**Issue by romaudulus** [thingsboard/thingsboard#4303]
Hello. I'm need to update  one widget  timewindow when I click on a row of a another widget timeseries data table.
First widget is map and next widget timeseries with rows populated begin and end trips.
 I want to use the selected timestamp as the source for the time window another widget.

Thank You for advice me.

romaudulus

**Comment by vvlladd28** [comment]
Hi @romaudulus,
In TB PE, you can't do make a public dashboard because TB PE supports only the public dashboard group/device group. In your case, your need to create a new dashboard group and added a dashboard that you want to make public, and then make this group public.

**Comment by romaudulus** [comment]
Hi Vladyslav,

 

My problem is elsewhere. I have created two widgets. One contains in each row an data of the start and end of the ride. Then I have  map widget that displays the driving route from the coordinates of the tracker that sent the position coordinates. So I need to click on one row of the first widget and update  time window in the map widget to show the driving route. Can I do that via user action script?

 

Thank You for help me.

 

Romudulus

**Comment by vvlladd28** [comment]
Hi @rascreid 
You can write a custom action that updates the dashboard time window according to your parameters. You cannot update the time window of a widget from another widget. For example, using a custom action widget for update dashboard time-window:
```
const newDashboardtimewindow = {
    aggregation: {
        limit: 25000,
        type: "NONE"
    },
    hideAggInterval: false,
    hideAggregation: false,
    hideInterval: false,
    history: {
        historyType: 1,
        fixedTimewindow: {
            startTimeMs:  ${Your start time in millisecond},
            endTimeMs: ${Your end time in millisecond},
        }
    },
    selectedTab: 1
}
widgetContext.dashboard.dashboardTimewindowChangedSubject.next(newDashboardtimewindow)
```

**Comment by romaudulus** [comment]
Great, we are very close to a solution.

 

When I put as start and stop static value then script work.

My column for start time is name ‚begin‘ and column for end time named „end“

 

When I modify script : ${begin}  and ${end}  then syntax error I see and script not work.

 

What I do wrong? 

 

Sorry for my ignorance I am programwriter for embedded systém in C and JAVA is mystery for me ))

 

Thanx very much.

 

romaudulus

**Comment by romaudulus** [comment]
Please, how I can set variable "${Your start time in millisecond}" and "${Your end time in millisecond}" from clicked row  in timeseries widget? I have column with start time named as 'begin' and stop time column named 'end'



const newDashboardtimewindow = {
    aggregation: {
        limit: 25000,
        type: "NONE"
    },
    hideAggInterval: false,
    hideAggregation: false,
    hideInterval: false,
    history: {
        historyType: 1,
        fixedTimewindow: {
            startTimeMs:  ${Your start time in millisecond},
            endTimeMs: ${Your end time in millisecond},
        }
    },
    selectedTab: 1
}
widgetContext.dashboard.dashboardTimewindowChangedSubject.next(newDashboardtimewindow)

**Comment by vvlladd28** [comment]
Hi @romaudulus 
You can get the row table value that was clicked from the function parameter: `additionalParams`

**Comment by romaudulus** [comment]
Hi Vladyslav, thank You.
Can You please give me some example how to do it? How from additionalParams get row data from widget?

**Comment by vvlladd28** [comment]
```
const newDashboardtimewindow = {
    aggregation: {
        limit: 25000,
        type: "NONE"
    },
    hideAggInterval: false,
    hideAggregation: false,
    hideInterval: false,
    history: {
        historyType: 1,
        fixedTimewindow: {
            startTimeMs:  additionalParams.2,
            endTimeMs: additionalParams.3,
        }
    },
    selectedTab: 1
}
widgetContext.dashboard.dashboardTimewindowChangedSubject.next(newDashboardtimewindow)
```
where in additionalParams.2/additionalParams.3 - 2(3) number of data column in your table

**Comment by romaudulus** [comment]
I try but in editor appear error message : "A leading decimal point can be confused with a dot: '.0'"
Expected '}' ...........
