### ISSUE TITLE
3.2.1PE : API getUserCustomers [Bug] 

### ISSUE THREAD

**Issue by WeNext-Dev** [thingsboard/thingsboard#4306]
**Describe the bug**
I have updated from V.3.0.1PE to V3.2.1PE
The REST API does not respond anymore to the API ```/api/user/customers{?textSearch,sortProperty,sortOrder,pageSize,page}
getUserCustomers```
e.g. /api/user/customers?pageSize=1&page=0 .

I have tried also on the swagger UI, and by command line like ```'curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer XXXXX' 'https://XXXX.net/api/user/customers?pageSize=1&page=0'```
We get the response:
```json
{
  "data": [],
  "totalPages": 0,
  "totalElements": 0,
  "hasNext": false
}
```

Befor the update we get the customer address and information from this request.
Currently, our customers cannot get data anymore from this request.

**Your Server Environment**
* own setup
  * cloud 
  * V3.2.1PE
  * Ubuntu 18.04 LTS

**Your Client Environment**
**Desktop**
* OS: [Windows 10]
* Browser [chrome]

**Expected behavior**
```json
{
  "data": [
    {
      "id": {
        "entityType": "CUSTOMER",
        "id": "XXXX"
      },
      "createdTime": 1572010656347,
      "additionalInfo": null,
      "country": "Germany",
      "state": "XXXX",
      "city": null,
      "address": null,
      "address2": null,
      "zip": null,
      "phone": null,
      "email": null,
      "title": "XXXX",
      "tenantId": {
        "entityType": "TENANT",
        "id": "XXXXX"
      },
      "parentCustomerId": null,
      "customerId": null,
      "ownerId": {
        "entityType": "TENANT",
        "id": "XXXX"
      },
      "name": "XXXX"
    }
  ],
  "totalPages": 58678,
  "totalElements": 58678,
  "hasNext": true
}
```

**Comment by vvlladd28** [comment]
Hi @WeNext-Dev,
We have tested API call returned response in 3.2.2 PE. Maybe your authorization token user didn't have a customer and returned an empty response. Please update your version of TB and test against it. If this problem reproduces, please send logs TB in this API call.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
