### ISSUE TITLE
Time series Export and Value Formatting

### ISSUE THREAD

**Issue by innoagg** [thingsboard/thingsboard#431]
It is often necessary to add some formatting to telemetry values in Timeseries Tables so that they display in the dashboard in a "friendly" way. This functionality works fine, however when the data is exported to excel/csv the values do not reflect any of this formatting. 

It would be beneficial if perhaps each Data Key value can be configured to "Preserve Formatting (Yes/No)" for export purposes.

**Comment by Manusisko** [comment]
Yes, this is a key issue and it should be included

**Comment by LeoMorgan113** [comment]
Hi,

We have this feature in our backlog(ticket number PROD-651), so it will be implemented in our future version, most likely v.3.3. 
So keep updated: https://thingsboard.io/docs/reference/releases/
