### ISSUE TITLE
Device Group deletet, devices still there, but not visible

### ISSUE THREAD

**Issue by Mirjka** [thingsboard/thingsboard#4315]
**Component**

 * Generic

**Description**
I deleted a device group and thought the devices included are beeing deleted as well automatically. But when I add a new device with the same ID, TB is telling me, the device is already existing. How can I clean / delete these devices?

**Environment**

 * OS:  Ubuntu 18
 * ThingsBoard: Professional (Version...have to ask our admin...)
 * Browser: FireFox 78.9.0esr

**Comment by vvlladd28** [comment]
Hi @Mirjka,
You need to check entities in group "All".

**Comment by ashvayka** [comment]
Deleting a group does not delete devices. Device may be a member of multiple groups. Devices are always members of group "All".

**Comment by Mirjka** [comment]
I checked "All", but there wheren´t the devices. After I logged out and logged in I had the licence back and the devices were gone...
