### ISSUE TITLE
Can't set alarm activation flag on Rule chain

### ISSUE THREAD

**Issue by antoniocgg** [thingsboard/thingsboard#4319]
**Rule Engine**

**Description**
I want to enable or disable  alarms  based on a server attribute called temperatureAlarmFlag wich is a boolean variable.
My **script** node has the code below

_return (msg.temperature > metadata.ss_temperatureAlarmThreshold) && metadata.ss_temperatureAlarmFlag ;_
    

And is preceded by the  **originator attributes** node with the two server attributes (temperatureAlarmThreshold and temperatureAlarmFlag)

It works and fires the alarms without the temperatureAlarmFlag variable, but I want to enable and disable the alarms based on this attribute.

I appreciate any help to accomplish this. 

**Environment**

 * OS:  Windows 10
 * ThingsBoard: live demo
 * Browser: Chrome 89.0.4389.90

**Comment by ChantsovaEkaterina** [comment]
Hello, @antoniocgg 

Please, note that values stored in metadata always have the type 'string'.
So by writing `return (msg.temperature > metadata.ss_temperatureAlarmThreshold) && metadata.ss_temperatureAlarmFlag;` you are comparing to a non-empty string what is always 'true'.
To make your condition work properly you need to rewrite it in such way:
`return (msg.temperature > metadata.ss_temperatureAlarmThreshold) && (metadata.ss_temperatureAlarmFlag === 'true');`

**Comment by antoniocgg** [comment]
Thank you @ChantsovaEkaterina !
Worked perfectly.

**Comment by ashvayka** [comment]
Hi @antoniocgg , have you considered using the [Alarm Rules](https://thingsboard.io/docs/user-guide/device-profiles/#alarm-rules) in the Device Profile?

**Comment by antoniocgg** [comment]
Hi @ashvayka !
I tried both ways, but couldn't make it either. 
I followed the script on TB page. I'll try again considering the metadata is 'string'

Thank you

**Comment by Ultrazombie** [comment]
Closed due to ianctivity
