### ISSUE TITLE
[Bug] Upgrade ThingsBoard from 3.2.1 to 3.2.2

### ISSUE THREAD

**Issue by mire22** [thingsboard/thingsboard#4321]
**Describe the bug**
Can't upgrade ThingsBoard, using Docker thingsboard/tb-cassandra, from version 3.2.1 to 3.2.2.
The cassandra database never start.
In /var/log/cassandra/cassandra.log, there is the following error message:
```
Cannot change the number of tokens from 256 to 16
Fatal configuration error; unable to start server.  See log for stacktrace.
ERROR [main] 2021-03-27 16:29:29,986 CassandraDaemon.java:822 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot change the number of tokens from 256 to 16
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1045)
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:994)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:793)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:723)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:400)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:676)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:800)
```

**Your Server Environment**
* own setup
  * ThingsBoard Version 3.2.1 (trying to upgrade to 3.2.2)
  * OS Name and Version (Debian 9)

**To Reproduce**
```
mkdir -p ~/mytb-data && sudo chown -R 799:799 ~/mytb-data
mkdir -p ~/mytb-logs && sudo chown -R 799:799 ~/mytb-logs
docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp -v ~/mytb-data:/data -v ~/mytb-logs:/var/log/thingsboard --name mytb thingsboard/tb-cassandra:3.2.1
# Wait until it started

echo 3.2.1 | sudo tee mytb-data/.upgradeversion # This file is not updated during installation... (maybe other issue...)
docker pull thingsboard/tb-cassandra:3.2.2
docker stop mytb
docker run -it -v ~/mytb-data:/data --rm thingsboard/tb-cassandra:3.2.2 upgrade-tb.sh

# See that it never start the database
```

**Expected behavior**
ThingsBoard should update to version 3.2.2.

Thank you!

**Comment by kien-truong** [comment]
`thingsboard/tb-cassandra` Cassandra was upgrade from version `3.11` to version `4` with the changes to `3.2.2`. This is a bad idea due to multiple reasons:
* Cassandra `4` is still in beta
* Cassandra `4` have different default configuration from `3.11`, for example the default `num_tokens` is now 16 instead of 256. 
* You also should run `nodetool upgradesstables` in order to upgrade existing data, whenever you upgrade a major Cassandra version

**Comment by mire22** [comment]
I'm not able to argue about this choice of Cassandra version, i'm just a user trying to keep my system updated.
So do the `upgrade-tb.sh` script will be updated to upgrade the existing Cassandra database?
Or could you explain me how to do this upgrade "by hand"?
I think, next ThingsBoard versions will rely on an Cassandra version. I don't want to lose my data during upgrade.

Thank you for your help.

**Comment by kien-truong** [comment]
It's a bad idea to couple multiple stateless and stateful services like in `thingboard/tb-cassandra`. That image should be used for testing only and not for production.

I would advice you to do the following step:

* Take snapshot of your Cassandra tables with Thingsboard 3.2.1
* Setup a new 1-node Cassandra cluster from the Official Cassandra docker image, or a package manager of your choice.
* Move the snapshot to the new Cassandra cluster and restore the snapshot into tables.
* Setup a `thingsboard/tb-node` container to connect to your new Cassandra cluster.
* Add more server to the new Cassandra cluster if required

**Comment by mire22** [comment]
Ok thank you for the advice, I will try.
Maybe the [ThingsBoard installation webpage](https://thingsboard.io/docs/user-guide/install/docker/) should be updated with a `docker-compose.yml` doing that...

**Comment by mire22** [comment]
Maybe, if I use the cluster configuration from [here](https://github.com/thingsboard/thingsboard/tree/master/docker), I don't need to update the Cassandra database?
I saw in [docker-compose.hybrid.yml](https://github.com/thingsboard/thingsboard/blob/master/docker/docker-compose.hybrid.yml) the Cassandra version is 3.11. So I just need to link my existing volume to this service. In other words, rewrite the service as:
```yml
  cassandra:
    restart: always
    image: "cassandra:3.11.3"
    ports:
      - "9042"
    volumes:
      - ~/mytb-data:/var/lib/cassandra
```
Is it good?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
