### ISSUE TITLE
[Question] Thingsboard3.2.2 compile failed on project netty-mqtt

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#4323]
**Describe the bug**
I download the newest thingsboard version3.2.2. And my maven version is 3.6.3. my java version is 11.0.10.
Then I executed the command "mvn clean install -Dmaven.test.skip=true". And the following error occured:
![image](https://user-images.githubusercontent.com/31084798/112786258-6cc90f00-9088-11eb-8567-65bd6fe1dfe2.png)

**Comment by huzhixiang** [comment]
I got this error too, how to fix it?
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project netty-mqtt: Fatal error compiling

**Comment by cjy37** [comment]
+1

**Comment by jiekechoo** [comment]
上面写了，Java 版本不对。WRONG JDK Version，换JDK1.8试试看呢

**Comment by seenivasen** [comment]
I have the same issue, anyone has a solution for this?

**Comment by seenivasen** [comment]
Issue resolved, I previously had an older version of JAVA installed. I then installed java version 11 but the JAVA_HOME path still pointed to the older version of java. Update the path to resolve your issue.

**Comment by jiekechoo** [comment]
I resolved this issue, in CentOS,  `yum install java-11-openjdk-devel` , fixed.
