### ISSUE TITLE
[Bug] Transport services fail on kubernetes due to JDK 11 migration

### ISSUE THREAD

**Issue by hairyheron** [thingsboard/thingsboard#4328]
**Describe the bug**
When using the Kubernetes configuration from https://github.com/thingsboard/thingsboard/tree/v3.2.2/k8s, the transport services are unable to start. Example output from `tb-http-transport` service:

```
Starting 'ThingsBoard HTTP Transport Microservice' ...
[0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/log/tb-http-transport/tb-http-transport-c999dbf5d-59mk2/gc.log instead.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
[0.001s][error  ][logging] Error opening log file '/var/log/tb-http-transport/tb-http-transport-c999dbf5d-59mk2/gc.log': No such file or directory
[0.001s][error  ][logging] Initialization of output 'file=/var/log/tb-http-transport/tb-http-transport-c999dbf5d-59mk2/gc.log' using options '(null)' failed.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Affected services:
* tb-http-transport
* tb-mqtt-transport
* tb-coap-transport
* tb-node

I assume this is related to the [JVM options in configmap](https://github.com/thingsboard/thingsboard/blob/release-3.2/k8s/common/tb-node-configmap.yml#L27) that are incompatible with JDK 11.

**Your Server Environment**
* own setup
  * Kubernetes (AKS)
  * Configuration from https://github.com/thingsboard/thingsboard/tree/v3.2.2/k8s with `DATABASE=postgres` and `DEPLOYMENT_TYPE=basic`

**To Reproduce**
1. Follow the steps in https://github.com/thingsboard/thingsboard/tree/v3.2.2/k8s#installation to install TB 3.2.2 to a k8s cluster.
2. Check status of pods with `kubectl get -n thingsboard pods`

**Expected behavior**
All pods, including the transport service ones, should be in `Running` state without any errors.

**Additional context**
This can also break other versions of thingsboard that are already deployed to some cluster, because the k8s manifests use `:latest` tag for all images. In fact, I was only upgrading my k8s cluster, which caused the creation of new pods with new (broken) images.
Downgrading transport services and tb-node service to 3.2.1 helped, but this caused an incompatibility with `tb-web-ui` frontend. So I also needed to downgrade `tb-web-ui` to 3.2.1.

From my perspective there could be multiple takeaways:
* The 3.2.1 to 3.2.2 update changed which environment variables are required/supported (due to JDK 11). I believe this is problematic, given there is only a patch-level increase in the version number.
* Using tag `:latest` in k8s manifests is dangerous because it might cause upgrades that are not desired
* It would be great to extend CI so that the kubernetes deployment would also be tested

**Comment by ashvayka** [comment]
Hi @hairyheron ,

sorry for the errors and inconvenience. I will fix this tomorrow morning. Meanwhile, you can change the configmaps according to the example [here](https://github.com/thingsboard/thingsboard/blob/v3.2.2/docker/tb-node/conf/thingsboard.conf) and [here](https://github.com/thingsboard/thingsboard/blob/v3.2.2/docker/tb-transports/mqtt/conf/tb-mqtt-transport.conf)

**Comment by ashvayka** [comment]
Fixed in this [PR](https://github.com/thingsboard/thingsboard/pull/4338) Merged to master as well.

**Comment by hairyheron** [comment]
@ashvayka Awesome, thanks a lot for your fast help (and please forgive my late response)!
