### ISSUE TITLE
Reset Timewindow after zooming

### ISSUE THREAD

**Issue by lilalukas** [thingsboard/thingsboard#4329]
Hi,

I would like to see a __reset zoom__ button in one of the next versions. Especially if you set your timewindow to a historical date you have much work to reset the view after you zoomed in. Realoading the page takes quite a time if you have many values to display.

Thanks for the constant development! Great work!

**Comment by ashvayka** [comment]
Zoom is reset easily with a double-click.

**Comment by lilalukas** [comment]
Thanks
works great!
Maybe you could document this function. I work since 6 months with thingsboard and was not aware of this.
