### ISSUE TITLE
Calculating deltas according to Documentation does not work

### ISSUE THREAD

**Issue by Cody-Hayes97** [thingsboard/thingsboard#4333]
**Component**
 * Rule Engine

**Description**
Hello, I'm trying to calculate the delta for a telemetry value using the previous record and subtracting them. Im following the logic described here in the docs: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/transform-telemetry-using-previous-record/#use-case 
However, this method does not work for me, as no matter how much the original value changes, the delta is always zero. It seems the originator attributes rule node is only fetching the most recent record and not the previous one, which causes the difference to be zero. 

here's an example of my rule chain flow, as you can see its exactly how its done in the documentation.
![CQ Carbon Management System _ Rule chain and 3 more pages - Personal - Microsoft​ Edge 3_29_2021 11_06_37 AM](https://user-images.githubusercontent.com/52092524/112881285-55862380-9080-11eb-9625-94a567f092fd.png)

but the delta is always zero no matter what:

![CQ Carbon Management System _ Rule chain and 3 more pages - Personal - Microsoft​ Edge 3_29_2021 11_05_38 AM](https://user-images.githubusercontent.com/52092524/112881336-633ba900-9080-11eb-9c88-6f842da617cb.png)

Is there any way I can make this work by grabbing the previous telemetry? I dont want to use the originator telemetry node as I just want to grab the second to most recent record.

Any help would be greatly appreciated, Thank You!

**Environment**
 * OS:  Windows 10
 * ThingsBoard: v3.1.0

**Comment by ashvayka** [comment]
Hi @Cody-Hayes97 , this is very strange. Please share the json export of your rule chain. Also, please consider using new rule node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#calculate-delta

**Comment by Cody-Hayes97** [comment]
Hello @ashvayka Here is the JSON for the rule node im currently using: https://file.io/HQvlCsB6oFC0
My team is trying to do this without the new node. as we have not updated to 3.2

RAW JSON:
{
  "ruleChain": {
    "additionalInfo": {
      "description": ""
    },
    "name": "new",
    "firstRuleNodeId": null,
    "root": false,
    "debugMode": true,
    "configuration": null
  },
  "metadata": {
    "firstNodeIndex": 0,
    "nodes": [
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 304,
          "layoutY": 150
        },
        "type": "org.thingsboard.rule.engine.filter.TbMsgTypeSwitchNode",
        "name": "switch",
        "debugMode": true,
        "configuration": {
          "version": 0
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 599,
          "layoutY": 148
        },
        "type": "org.thingsboard.rule.engine.metadata.TbGetAttributesNode",
        "name": "previous",
        "debugMode": true,
        "configuration": {
          "tellFailureIfAbsent": true,
          "clientAttributeNames": [],
          "sharedAttributeNames": [],
          "serverAttributeNames": [],
          "latestTsKeyNames": [
            "TotWhImp"
          ],
          "getLatestValueWithTs": false
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 771,
          "layoutY": 267
        },
        "type": "org.thingsboard.rule.engine.transform.TbTransformMsgNode",
        "name": "default",
        "debugMode": true,
        "configuration": {
          "jsScript": "metadata.TotWhImp = msg.TotWhImp\n\nreturn {msg: msg, metadata: metadata, msgType: msgType};"
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 861,
          "layoutY": 148
        },
        "type": "org.thingsboard.rule.engine.transform.TbTransformMsgNode",
        "name": "calculation",
        "debugMode": true,
        "configuration": {
          "jsScript": "msg.deltaTotWhImp = msg.TotWhImp - metadata.TotWhImp\n\nreturn {msg: msg, metadata: metadata, msgType: msgType};"
        }
      },
      {
        "additionalInfo": {
          "description": "",
          "layoutX": 1148,
          "layoutY": 147
        },
        "type": "org.thingsboard.rule.engine.telemetry.TbMsgTimeseriesNode",
        "name": "save",
        "debugMode": true,
        "configuration": {
          "defaultTTL": 0
        }
      }
    ],
    "connections": [
      {
        "fromIndex": 0,
        "toIndex": 1,
        "type": "Post telemetry"
      },
      {
        "fromIndex": 1,
        "toIndex": 3,
        "type": "Success"
      },
      {
        "fromIndex": 1,
        "toIndex": 2,
        "type": "Failure"
      },
      {
        "fromIndex": 2,
        "toIndex": 3,
        "type": "Success"
      },
      {
        "fromIndex": 3,
        "toIndex": 4,
        "type": "Success"
      }
    ],
    "ruleChainConnections": null
  }
}

**Comment by Ultrazombie** [comment]
Closed due to inactivity
