### ISSUE TITLE
ERR :unassignAssetFromCustomer when customer is deleted

### ISSUE THREAD

**Issue by sdfantasy** [thingsboard/thingsboard#434]
when open the ASSET menu,show flowing ERROR:
![image](https://user-images.githubusercontent.com/13897059/33064874-21b43f0a-cee2-11e7-9377-5b458bb68d3d.png)

when unassignAssetFromCustomer:
![image](https://user-images.githubusercontent.com/13897059/33064726-9f4f1648-cee1-11e7-99ff-4460cf873a6c.png)
![image](https://user-images.githubusercontent.com/13897059/33064753-c1ecf8b4-cee1-11e7-9961-09b20d858cef.png)

**Comment by LeoMorgan113** [comment]
Hi @sdfantasy,

This issue fixed in the newest versions.
Please refer to https://thingsboard.io/docs/reference/releases/
