### ISSUE TITLE
[Question] How to make a dashboard require a user name and password

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4344]
**Component**
 * UI

**Description**
I created a dashboard, currently it is public and I can access it with the public link given. When accessing the public link I want a user name and password to be required to view the dashboard. How can I do that and where can I manage those credentials?

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2

**Comment by Mirjka** [comment]
Maby there is a better way or I did it this way:

Download the puplic dashboard and upload it again in a non puplic dashboard group.

add a generic role with all the rights you need. For users, wich are able to control devices I use this rule:
- Alarm: All
- Dashboard: I have Attributes and Timeseries, so I added Read, Write, Read ATtributes, Write, Attributes, Read Telemetry, Write Telemetry
- Dashboard Group: Read
- Device: All regarding read and write
- Widgets bundle: Read
- Widget Type: Read

Then add a user and add this rule to the user. Add a standard-dashboad and if you like klick "always fullscreen".

When this user is logged in, he will be directed directly to the dashboard.

I hope this was helpful! Cheers

**Comment by snir99** [comment]
How do I set a dashboard group? I have CE, is this a PE feature?

**Comment by Delapouite** [comment]
Entity-groups are indeed a PE feature.

**Comment by snir99** [comment]
Found a solution, in this solution we will not use the public link but create users and register them to the dashboard we want to require username and password. 
[This post](https://thingsboard.io/docs/user-guide/ui/dashboards/) is very helpful to understand this method.
