### ISSUE TITLE
[Bug] Using Enrichment Node "related device attribute" gives "Unknown" error

### ISSUE THREAD

**Issue by mgrey** [thingsboard/thingsboard#4349]
**Describe the bug**
Using Enrichment Node "related device attribute" gives "Unknown" error

**Your Server Environment**
* own setup
  * cloud: VPS
  * ThingsBoard 3.2.2
  * OS Ubuntu 18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 7
* Browser Chrome
* Version 89.0.4389.90

**Smartphone (please complete the following information):**

**Your Device**

**To Reproduce**
1. Add a "related device attribute" node after 'message type switch/post telemetry" and "save timeseries"
2. Configure to fetch attributes from related device above, in my case attributes from a gateway device (Direction: To, Relation type: Contains, Device type: gateway).
3. Any combination tried gives 'Failure' with unknown error (even if 'Tell Failure' not checked) 

**Expected behavior**
Fetching attributes from related device correct, if error try to be more specific than 'Unknown'

**Screenshots**
-

**Additional context**
Corresponding help text does not correspond to version 3.2.2 of Thingsboard.
I think you should explain 'Relation type' and 'Direction', isn't it the same thing?

**Comment by mgrey** [comment]
'Unknown' comes from the Rule Engine Statistics dashboard (that comes with demo).
If you enable debug on node, you just get failure with empty error

**Comment by SuminDenis** [comment]
Hello @[t0mZ4](https://github.com/t0mZ4),

I’m glad to inform you that this issue has been solved in the current version of ThingsBoard!
