### ISSUE TITLE
Autocomplete goes nuts

### ISSUE THREAD

**Issue by filiphosko** [thingsboard/thingsboard#435]
Sometimes when somebody is too eager and has an above average typing speed, autocomplete can go nuts and wreak havoc. Maybe it would be good to implement some throttling. It's not a critical bug, but it's an inconvenience for sure.

![screenshot-2017-11-21 thingsboard asset group](https://user-images.githubusercontent.com/23213144/33074874-fc48f306-cec7-11e7-8ef3-8ff779478c75.png)

**Comment by ashvayka** [comment]
this is a bug in the third-party lib and we don't know how to fix it now.

**Comment by vparomskiy** [comment]
Issue resolved in the latest ThingsBoard version (2.3)
