### ISSUE TITLE
Rule Chain: where to find / install 

### ISSUE THREAD

**Issue by Mirjka** [thingsboard/thingsboard#4351]
**Component**

 * Rule Engine
 * Installation

**Description**
I´m using Thignsboard 3.2.1 PE (Maker) but there is no Rule Chain available.
I can´t find the requirements or reasons. Is there a update / do I have to upgrade to prototype?

**Environment**

 * OS:  Ubuntu 18.4
 * ThingsBoard: 3.2.1 PE
 * Browser: FireFox 87.0

**Comment by Delapouite** [comment]
Do you mean that the "rule-chains" entry does not appear int he main menu (left sidebar)?

Ensure that you are connected as a tenant admin, not as sysadmin.
If you're connected as a tenant admin, verify that the menu entry has not been hidden in white labeling options.

**Comment by Mirjka** [comment]
We updated our TB, now we got it, thanks!
