### ISSUE TITLE
package org.thingsboard.server.common.msg.gen does not exist. Where to find this package

### ISSUE THREAD

**Issue by Justsmilec** [thingsboard/thingsboard#4352]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by ligengithub** [comment]
me too   have you resolve this problem?

**Comment by zhouzhu3991** [comment]
when we run the command :mvn install -DskipTests or mvn clean install successfully, this package is generated in the cache, as long as don't run mvn clean, this package will keep remain.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
