### ISSUE TITLE
[Bug] Map view, multiple entities/markers broken. 

### ISSUE THREAD

**Issue by janvl1234** [thingsboard/thingsboard#4359]
The Map view in v2.x.x was working fine when a device had multiple locations (latitude/lonitude)
However it's not possible to show multiple locations from the same device in v3.x.x. I just updated all the way to 3.2.2. 

Here is a screenshot from v2.4.3

![maps_view_tb_v2](https://user-images.githubusercontent.com/5804996/113391899-8d4cde00-9394-11eb-8c18-cf4a8b340540.png)

And in v3.2.2 I see this:

![maps_view_tb_v3](https://user-images.githubusercontent.com/5804996/113392242-149a5180-9395-11eb-92b2-03c4e17f21bb.png)

The location shown on the map is always the last one in the list.

**Comment by ChantsovaEkaterina** [comment]
Hello, @janvl1234 
Could you check the map widget datasources on v3.2.2 one more time, please? It seems like you specified one alias three times.

**Comment by janvl1234** [comment]
Hi @ChantsovaEkaterina , 
Three times the same alias is exacly what I want. I have a single alias which has three different locations.
You can see I do the same thing with TB CE 2.x.x where I then get all three location of this single alias. 
How can I put multiple locations of a single alias on a map in TB CE 3.x.x 
Looks like it's a bug since it works fine on the old thingsboard.

**Comment by vvlladd28** [comment]
Hi  @janvl1234,
Coming soon, we will add the fix to master branch.

**Comment by janvl1234** [comment]
Hi @vvlladd28, 
Thanks for the fix. Looking forward to the new release with the fix :)

**Comment by ngsuityan** [comment]
@vvlladd28 Is that for ThingsBoard CE v 3.3.4 still not available for multiple placement marker in a single map still not available???

**Comment by mlutsoUC** [comment]
> Hi @janvl1234, Coming soon, we will add the fix to master branch.

2 years coming still not realized
