### ISSUE TITLE
Suboptimal algorithm for validating uniqueness of strings

### ISSUE THREAD

**Issue by filiphosko** [thingsboard/thingsboard#436]
When I have a type that describes a group (pluralized words, let's say for this example it will be "groups"), I create that type and then I want to create an entity type that will be a descendant by "singularizing" the type ("group"), I can't do it because the validator assumes I'm typing the same word. It's unfortunate, because since I used the pluralized word I'm kinda screwed and the only option is to create this entity type through API call.

![snimka obrazovky 2017-11-21 o 14 37 00](https://user-images.githubusercontent.com/23213144/33075366-7f7e004e-cec9-11e7-8825-65059e9213a6.png)

**Comment by ashvayka** [comment]
@ikulikov please review.

**Comment by vparomskiy** [comment]
Issue fixed in the latest ThingsBoard version (2.3)
