### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MaxDeveloper** [thingsboard/thingsboard#4363]
**Describe the bug**
**Enrichment - originator attributes** nodes do not respect attributes types. All values are converted to strings.

**Server Environment**

* Raspberry Pi
  * local infrastructure
  * ThingsBoard Version 3.2.1
  * OS Name and Version: Raspbian GNU/Linux 10 (buster)

**Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser: Chrome
* Version:  89.0.4389.114 

**To Reproduce**

Create shared attributes with correct types (double, int, boolean) in the Device -> Shared Attributes tab. 

![image](https://user-images.githubusercontent.com/1550120/113516358-0706e680-95a4-11eb-88ed-6f1289681c2c.png)

In the rulle chain create **Enrichment - originator attributes** node with settings like this:

![image](https://user-images.githubusercontent.com/1550120/113516403-51886300-95a4-11eb-86da-ab4cc81e3135.png)

In the DEBUG mode in metadata output you'll see all of them are strings.

![image](https://user-images.githubusercontent.com/1550120/113516479-b0e67300-95a4-11eb-96f3-daf4a757da78.png)

Found it while comparing values in code: (shared_enableClimateControl == false)
Problem "false" != false. And I have to remember all of them are strings now.

**Expected behavior**
Keep attribute values types as defined in shared attributes:
```
{
    "shared_enableClimateControl": false,
    "shared_maxAirHumidity": 95,
    "shared_maxAirTemperature": 22,
    "shared_minAirHumidity": 80,
    "shared_minAirTemperature": 18,
    "ts": 1617557105851
}

```

**Comment by LeoMorgan113** [comment]
Hi @MaxDeveloper,

Metadata stored as pair of String values, so if you want to work with metadata, don't forget to use parseInt() or Boolean().

**Comment by ashvayka** [comment]
Unfortunately, we can't change the structure of the metadata (from KV map where K and V are Strings) to a JSON object without loosing backward compatibility with existing scripts. Although the enhancement is valid, it will be delayed at lest till version 4.x
