### ISSUE TITLE
Trip widget label function problem

### ISSUE THREAD

**Issue by romaudulus** [thingsboard/thingsboard#4364]
Hi, I use TB 3.2.1 and and have problem with trip widget label function:

When I use simple Show label : **<b>Bus: ${entityName}</b><br/><b>Bus speed:</b>${velocity}<br/>**

then label works as expected BUT when I try do same with Label function 

**var speed = dsData[dsIndex]['velocity'];
console.log(speed);
if (typeof speed !== undefined) {
     return  '<b>Bus: ${entityName}</b><br/><b>Bus speed:</b>'+ speed +'<br/>';
}**

Then label is correct shown only for first point on the map and for next points disappear.
![image](https://user-images.githubusercontent.com/17903837/113590586-c30af480-962a-11eb-8857-e17fc0d6e6c6.png)

I attach log screen.
Thank You for reply.
Romaudulus

**Comment by LeoMorgan113** [comment]
Hi @romaudulus,

You problem may be caused by this code:
**_var speed = dsData[dsIndex]['velocity'];_**

Try to use
**_var speed = ${velocity}_**
