### ISSUE TITLE
Installing TB-GATEWAY on Windows 10 and Connect it with Thingsboard Server (minus TB-Gateway on the Server)

### ISSUE THREAD

**Issue by ChSM56** [thingsboard/thingsboard#437]
I was attempting to set up a desktop with TB-Gateway on a Windows 10 Desktop and connect to the Thingsboard Server (It has TB-Gateway installed and the service stopped).

I set up the Thingsboard Server with IP 192.168.0.4 and the Windows 10 is set up with TB-Gateway.

The Gateway is not connecting to the server for some reason I failed to fix.

Please help.

The Windows 10 is running musquitto MQTT (port: 1882) as well as TB-Gateway (port:1883).

[mosquitto.conf.txt](https://github.com/thingsboard/thingsboard/files/1491938/mosquitto.conf.txt)

The Linux Centos Server is running with TB-Gateway that works on the ports: 

![image](https://user-images.githubusercontent.com/29800826/33081361-3013f93c-cf00-11e7-8bb0-0d807ad0ae4b.png)

Please assist as to what should be the configurations on the TB-Gateway on a different system and the Server settings.

Thanks

**Comment by ashvayka** [comment]
Please attach the logs of the gateway. Also you need to validate that your mosquitto installation is working fine and you can publish/subscribe via command line tools. 

Also, if the TB server is on the other host, there is no need to reconfigure mosquitto. TB gateway will connect to a local mosquitto on port 1883 and push data to remote mqtt server on the same port 1883

**Comment by ChSM56** [comment]
Hello @ashvayka 

Please allow me to write a few lines on my set up:

IT Landscape & Systems architecture:

a. Centos 7 (192.168.0.4)installed with Thingsboard, mosquittio mqtt and TB-Gateway all in One System - Monolithic System architecture. Everything works fine and attached the screenshots. Reason for these screens is to show the changes I make to the configurations . 

b. Windows 10 desktop (192.168.0.5) installed with mosquitto mqtt and TB-Gateway connecting to Thingsboard running on Centos7 (192.168.0.4) - Sample horizontal scale Systems architecture

Use Chrome browser running on Windows 10 (192.168.0.5) for preliminary confirmation of the Installation.

The below is a series of screen grabs : 
![thingsboard deployment 20171128_a](https://user-images.githubusercontent.com/29800826/33301348-5728b56a-d41b-11e7-8164-948fdb629242.png)

The changes I make to the properly working configurations on Monolithic  structure is to point to mosquitto mqtt running on 192.168.0.5 and tb-gateway running on 192.168.0.5.  The Windows 10 desktop is running both mosquitto mqtt and tb-gateaway.

Am also attaching the log files from Windows 10 desktop tb-gateway .

![image](https://user-images.githubusercontent.com/29800826/33301466-e2527522-d41b-11e7-93a3-b3dd48461a00.png)

The tb-gateway.error.log filesize is zero !

[tb-gateway.wrapper.log](https://github.com/thingsboard/thingsboard/files/1508429/tb-gateway.wrapper.log)

Please review and help me to correctly configure the Platform.

Thank you.
 
PS: If ONLY I had another computer available to me, I would have liked mosquitto mqtt run on it and try to configure the systems.

**Comment by mp-loki** [comment]
Hi @ChSM56 ! It seems like the doc is outdated, so is your config file. The following `tb-gateway.yml` configuration worked for me:
`
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        port: $TB_MQTT_BROKER_PORT
        host: localhost
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "${GATEWAY_ACCESS_TOKEN:$YOUR_ACCESS_TOKEN}"
      extensions:
        -
          type: "http"
          configuration: http-config.json
        -
          type: "mqtt"
          configuration: "mqtt-config.json"
          enabled: "true"
`
The difference here is that you try to put the **mqtt** section under gateways/tenants[0]/extensions as described in the example above, not inline directly. (you probably don't need that http part).

Let me know if it helps

**Comment by ChSM56** [comment]
Hi @mp-loki,

Thank you for your help. I shall try this on Friday,  1st Dec.

Much appreciated

**Comment by ChSM56** [comment]
@mp-loki:
I am a little curious on the file format difference. The file format is exactly the same for me on both CentOS 7 & Windows 10. The files were part of the downloads and I was merely editing not altering their structure.

So, where could the difference origin?

**Comment by mp-loki** [comment]
@ChSM56 I think the structure has changed at some point, so that you have extentions (incl. mqtt) settings per tenant, not a global setting on the top level. We have to update docs on this

**Comment by ChSM56** [comment]
Hi @mp-loki 

It is of no avail. Attached is now my config file contents. The old file is also attached for review. Now, the tb-gateway service stops by itself after starting and I can not find anything wrong.

The system with IP 192.168.0.4 is Centos 7 with Thingsboard platform and also mosquitto .

The system with IP 192.168.0.5 is tb-gateway and I made the configuration changes.

[tb-gateway.yml.old.txt](https://github.com/thingsboard/thingsboard/files/1521799/tb-gateway.yml.old.txt)
[tb-gateway.yml.txt](https://github.com/thingsboard/thingsboard/files/1521800/tb-gateway.yml.txt)

The System is - 

 ===================================================
 :: Thingsboard Gateway ::       (v1.2.1)
 ===================================================

[tb-gateway.log](https://github.com/thingsboard/thingsboard/files/1521933/tb-gateway.log)
[tb-gateway.out.log](https://github.com/thingsboard/thingsboard/files/1521934/tb-gateway.out.log)
[tb-gateway.wrapper.log](https://github.com/thingsboard/thingsboard/files/1521935/tb-gateway.wrapper.log)

I just feel that there is a disconnect in the configurations (a broken link) as when I started tb-gateway on the Centos 7 system, it works.

**Comment by mp-loki** [comment]
@ChSM56 your configuration looks fine for me, however 
it seems like the [.zip file](https://github.com/thingsboard/thingsboard-gateway/releases/) you are using is out of date. I would recommend you to build ThingsBoard Gateway [from sources](http://localhost:4000/docs/iot-gateway/install/building-from-source/) now and try again. 
Just keep in mind that you have to build **thingsboard** application on your machine before you build gateway, so you have necessary artifacts in your local maven repo.

**Comment by ChSM56** [comment]
Hi @mp-loki 
Thank you for your support and help. However,  I prefer using just binaries and I would close this thread with a hope that there would be resolution built into the development plan at some stage. Further I am opening a new issue with regard to ports used and the software stack as layers and architecture is quite confusing to me.
