### ISSUE TITLE
[Question] How can I do actions on multiple devices

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4371]
**Component**

 * Generic

**Description**
I need to do the same action for several devices without having to enter each one, to change the state, for example using a check box to select. How could I do it?
![image](https://user-images.githubusercontent.com/78015483/113679034-994fdd00-96bf-11eb-8755-efef8a854089.png)

**Environment**

 * OS:  windows 10 pro
 * ThingsBoard: ThingsBoard v.3.2.2PE
 * Browser: chrome

**Comment by kalutkaz** [comment]
Hi, 

You can use mat-selector multiple for your task.

For example, I have list with three devices:
![image](https://user-images.githubusercontent.com/43555187/114000532-c63cf500-9863-11eb-893b-7ff05ac1ac52.png)

For your task I use 'Widget header button':
![image](https://user-images.githubusercontent.com/43555187/114000848-0ac89080-9864-11eb-8d60-9c8cffd754ef.png)

At first you need to get Devices id and names. This information you can find in widget context:
![image](https://user-images.githubusercontent.com/43555187/114001181-5ed37500-9864-11eb-8f8a-1dfb60e23586.png)

you can use this code: 
```
    let devices  = [];
    for(let key in widgetContext.datasources){
        devices.push(widgetContext.datasources[key].entity);
    }
```
after that you need to add this information to your form group:
```
    vm.FormGroup = vm.fb.group({
      selectDevicesId: [[]],
      devices:[devices],
    });
```

In first field will saving select devices and in second field all devices in your widget

After that add this html:
```
 <mat-form-field>
              <mat-label>Select devices</mat-label>
              <mat-select formControlName="selectDevicesId" multiple>
                <mat-option *ngFor="let device of FormGroup.get('devices').value" [value] = "device.id">{{device.name}}</mat-option>
              </mat-select>
  </mat-form-field>
```

As a result you can choose some devices:
![image](https://user-images.githubusercontent.com/43555187/114002734-cd650280-9865-11eb-81fa-618fb33b7e18.png)

And selector will saving ids this devices:
![image](https://user-images.githubusercontent.com/43555187/114004164-0ea9e200-9867-11eb-909f-4eb15c9f8a10.png)

Use this ids you can do some action with your devices.

Here is a test widget with this action:
[test_widget.zip](https://github.com/thingsboard/thingsboard/files/6277769/test_widget.zip)

**Comment by AbrahamSalvi** [comment]
Hi @kalutkaz,
When I try to add the json file I get this error. The lines that you have passed me, where do I add them?
![image](https://user-images.githubusercontent.com/78015483/114174907-9e1fc580-9939-11eb-8738-1c496afc943e.png)

**Comment by kalutkaz** [comment]
Hi @AbrahamSalvi,
You need import this widget to some dashboard in Dasboard groups:
![image](https://user-images.githubusercontent.com/43555187/114365496-2e9d1680-9b83-11eb-94a8-93ba090bcc3f.png)
![image](https://user-images.githubusercontent.com/43555187/114365569-44124080-9b83-11eb-9fda-ec86941238c1.png)
![image](https://user-images.githubusercontent.com/43555187/114365837-863b8200-9b83-11eb-8545-ef39dc729b63.png)

**Comment by AbrahamSalvi** [comment]
Hi @kalutkaz ,
Could the checkbox be put in the same row as the device?
Thank you very much for the reply!

**Comment by kalutkaz** [comment]
Do you mean something like this?
![image](https://user-images.githubusercontent.com/43555187/114400270-77b49100-9baa-11eb-8605-29ce6bd62831.png)

**Comment by AbrahamSalvi** [comment]
Yes

**Comment by kalutkaz** [comment]
Unfortunately this is impossible. You can add here only button for your custom action.

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
A custom widget can solve your problem. 
We will add your feature to a backlog list, and when the opportunity arises, we will add this functionality to the platform. We will be very grateful if you have the opportunity to help us realize this.

**Comment by AbrahamSalvi** [comment]
Thank you @vvlladd28 !
