### ISSUE TITLE
[Question] true or false with State Chart - How?

### ISSUE THREAD

**Issue by Mirjka** [thingsboard/thingsboard#4373]
**Component**

 * UI

**Description**
Hi, I need to show the status of 10 pumps, which are send via timeseries. 
They are shown in the device / timeseries, but Iam not able to show them on a State Chart. 
I tried to change the Tooltip value format function, f(value) and on the Ticks formatter function f(value) like that:

if (value == true) {
    return 'On';
} else if (value == false) {
    return 'Off';
} else {
    return '';
}

also:
==                   ===
value               msg or message
true or false    TRUE or FALSE
true or false    'true' or 'false'

**Environment**

 * OS:  Ubuntu 18.4
 * ThingsBoard: 3.2.2 PE
 * Browser: FireFox 7890

**Comment by kalutkaz** [comment]
Hi,
If you want to show status On or Off you need use 'data post-processing function' and add some changes to 'Tooltip value format function' and 'Ticks formatter function'.

1) Click here in 'edit widget':

![image](https://user-images.githubusercontent.com/43555187/113888729-47947900-97cb-11eb-8eeb-841ca1063034.png)
than click to 'Use data post-processing function' and add in new field this code: 
`return value === 'true';`

![image](https://user-images.githubusercontent.com/43555187/113889154-a0641180-97cb-11eb-8470-56d61ba64e61.png)
and click "Save"

2) In 'Tooltip value format function' and 'Ticks formatter function'  copy this code:
 ```
if (value == 1) {
    return 'On';
} else if (value == 0) {
    return 'Off';
 } else {
    return '';
 }
```
![image](https://user-images.githubusercontent.com/43555187/113889514-fa64d700-97cb-11eb-8652-f54d1f38299d.png)

![image](https://user-images.githubusercontent.com/43555187/113890339-bcb47e00-97cc-11eb-92f5-0ebb3fbb78f1.png)

Than save changes.

As a result, chart show On or Off status:
![image](https://user-images.githubusercontent.com/43555187/113890937-495f3c00-97cd-11eb-9359-160ad46c9aa6.png)

**Comment by Mirjka** [comment]
Perfect, thanks alot!
