### ISSUE TITLE
Custom action to download report file

### ISSUE THREAD

**Issue by angelikileonida** [thingsboard/thingsboard#4374]
**Component**

 * UI

**Description**
I want to create a custom action the user clicks and  downloads a generated report. 

in the swager api i can see that there is a **downloadBlobEntity** resource 
GET /api/blobEntity/{blobEntityId}/download

but I cannot find the service in the code.
https://github.com/thingsboard/thingsboard/tree/release-3.2/ui-ngx/src/app/core/http

How can I  import this blob entity and download the file? 

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.2.2PE
 * Browser: chrome, Microsoft Edge

**Comment by ChantsovaEkaterina** [comment]
Hello, @angelikileonida 
I suppose you are looking for _downloadBlobEntity_ method from the _BlobEntityService_. But unfortunately, this service is not available in the _servicesMap_.
Have you tried to use the _Reports_ widget from the _Files_ widget bundle?
