### ISSUE TITLE
Access Token for device

### ISSUE THREAD

**Issue by puwarbv** [thingsboard/thingsboard#4375]
**Component**

 * Generic

**Description**
A clear and concise details.

Thanks for this wonderful application. I have been using this platform for small projects and has been using it for home automation system at my personal room. However, I am facing a challenge when I went to provide a solution to a customer.

It might be noob question but has been constantly bugging me.
The issue is:
* To authorize a device, TB uses device access token. up till now I was providing a custom parameter for device token in the web portal for entering ssid and password while making the connection and later on user can enter this token when adding a device. However it doesn't feels right that a customer should be doing this much work.
* My doubt is about the role of different accounts, sys admin, tenant and customer. If tenant is the one who would be manufacturing its own iot devices and selling it to a customer, then what is the need of sys admin to manage tenant?

*The other doubt is, instead of giving customer token definition, I can hard code the token in my device program and later on can provide this to user, but this won't be optimum solution as token should be something dynamic and must be ease for user. Just like password associated.

**Comment by ashvayka** [comment]
Hi @puwarbv ,

thank you for the kind words. Please review the [device provisioning](https://thingsboard.io/docs/user-guide/device-provisioning/) feature. It should help you to embed the provisioning credentials to the firmware (once for the firmware version) and each device running this firmware will be able to register on it's own. Then, you can use [claiming](https://thingsboard.io/docs/user-guide/claiming-devices/) for the end-user to assign the device to him. 

The sysadmin is a manager of tenant accounts.  You may have multiple tenants in one server.
