### ISSUE TITLE
Live-demo telemetry data does not update in real-time

### ISSUE THREAD

**Issue by niikand** [thingsboard/thingsboard#4376]
An issue has occured on a demo project. The project consists of an arduino uno with a ESP8266 Wi-Fi chip that sends pressure data to Thingsboard. Up until yesterday we were able to see updates in real-time on Thingsboard both telemetry and dashboard graphs. 

We've tried to rollback the code to an earlier working version without success. As well as setting up a clean Thingsboard demo-live account. This was tried due to finding similar issues on this page, but no detailed description on how the issue was solved.
This issue is replicated on both Microsoft edge and Firefox.

ISSUE: Values on the Telemetry update page for each device is no longer updating in realtime. The data (and timestamp) is however updating when reloading page. Relating to this the graphs are no longer working. 

Attach mail in case it's relevant: 
sensortest2021@gmail.com

**Comment by Ka-non** [comment]
it happens the same to me. I had a panel that worked correctly, with charts that gave data and suddenly they do not work (and the ESP32 are sending data without problem, the devices receive). Has there been any change in the platform? Maybe a version change?

**Comment by Ka-non** [comment]
demo.thingsboard.io is down at this moment

**Comment by ashvayka** [comment]
Yes, I am investigating and restarting this now

**Comment by Ka-non** [comment]
Service up!
and now, i can see graph... but 3 days of data has lost
![Captura11](https://user-images.githubusercontent.com/65251218/114008155-3f3b4d00-9862-11eb-9058-b28b42b03878.PNG)

**Comment by niikand** [comment]
It seems that it was a problem with demo Thingsboard service.
The issue has been resolved following the restart. 

Thanks

**Comment by ashvayka** [comment]
The issue was related to the DB. I have restarted the DB and ThingsBoard to make it work. This env has a high load and we don't replicate it because it is just for the demo.
