### ISSUE TITLE
Unable to read custom menu from JSON!

### ISSUE THREAD

**Issue by cesar-ayuuk** [thingsboard/thingsboard#4378]
Hello, 

I'm getting a weird issue while trying to login in thingsboard dashboard.
This is the error message i'm getting while trying to login:
 "Unable to read custom menu from JSON!"

And the same error on thingsboard log and nothing else:
"ERROR o.t.s.dao.menu.BaseCustomMenuService - Unable to read custom menu from JSON!"

The only thing is that the users to log in have roles. So, they have permission to see only some dasbhoards etc. We don't have custom menu for the users but it's trying to read it . What could be the cause of this issue?

Thingsboard version: v.3.2.1
OS: Ubuntu 18.04

**Comment by ashvayka** [comment]
please attache the network part of the console from your browser. This will help to identify which exact URL is requested, etc.
