### ISSUE TITLE
[Question] Error when adding remote MQTT integration - "Host must be in public network"

### ISSUE THREAD

**Issue by MarcelMann** [thingsboard/thingsboard#4383]
**Component**

 * Generic

**Description**
Hi, i want to add a mqtt-remote-integration to my thingsboard.cloud. 
The remote integration is supposed to run on the same machine in Docker as my MQTT broker.
Following [this guide](https://thingsboard.io/docs/user-guide/integrations/remote-integrations/) I am running into a problem in "Step 2. Create Remote Integration". The gif shows how the broker gets specified as "localhost" (what makes sense as the Remote integrationand broker are running on the same machine). In my case the Thingsboard UI tells me that "Host must be in public network".

Am i missing something, am i doing something wrong or is this some kind of a bug?

![Unbenannt](https://user-images.githubusercontent.com/3834407/114020625-16ba4f80-9870-11eb-9543-a5267efe51f9.png)

**Environment**

 * OS: Windows 10 
 * ThingsBoard: thingsboard.cloud Free Trial Month (dont know how to find out the version running there)
 * Browser: Edge 89.0.774.68

**Comment by vvlladd28** [comment]
Hi @MarcelMann,
The reason for not being able to create remote integration was a problem with TB.  
Thank you for reporting this problem. Coming soon, we are fixed in thingsboard.cloud.

**Comment by MarcelMann** [comment]
Thanks, bug is fixed. closing this

**Comment by Akramkhan-git** [comment]
@vvlladd28 
I am facing the same issue

**Comment by Akramkhan-git** [comment]
Error:- localhost must be in the public
