### ISSUE TITLE
[Bug] References to another rule chain lost after import

### ISSUE THREAD

**Issue by MaxLepplaKsb** [thingsboard/thingsboard#4384]
**Describe the bug**
When I am exporting a rule chain with references to another rule chain and import the rule chain again in another instance, the reference to the other rule chain is lost.

**Your Server Environment**

* own setup
  * docker deployment
  * v3,2,1
  * AWS Linux

**Your Client Environment**
**Desktop:**

* OS: Windows 10
* Browser: Chrome
* Version: 89.0.4389.114

**Your Device**
* Connectivity
  * MQTT
  * HTTP

**To Reproduce**
1. Go to "Rule chains"
2. Click on 'Add rule chain'
3. Create a rule chain and save it ( named: "Rule chain A")
4. Create another "Rule chain" and create a reference to the rule chain before
5. Save it (named: "Rule chain B")
6. Click in the overview on "Export rule-chain" and save it to the local machine
7. Clean up all rule chains or choose a clean instance of thingsboard
8. Import the "Rule chain A"
9. Import the "Rule chain B" (reference to "Rule chain A" not found)
10. Error: Reference to "Rule chain A" not found

**Expected behavior**
The root/ main rule chain (Rule chain A) should reference the sub-rule chain (Rule chain B)

**Screenshots**
![root_rule_chain_err](https://user-images.githubusercontent.com/63094079/114023667-72d2a300-9873-11eb-8814-4c32e0e07bda.PNG)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
