### ISSUE TITLE
Extend REST endpoint to delete specific telemetry values

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#439]
It can sometimes be helpful to be able to delete screwball telemetry values that might, for example, blow out dashboard widget axes.  Extend the existing REST endpoint that is used for deleting attributes and allow it to delete specific telemetry values as well.

**Comment by eykamp** [comment]
I have code for this ready to go, but want to implement some tests to prove it works.  I was looking for the right place to create a test, and I am not sure where the best place to create them would be.  Could someone please suggest the appropriate place for these tests?

**Comment by ashvayka** [comment]
please add as-is. There is no good example of test for plugin. I know this is not perfect, but if you can manually test it and it works - i will review the code. We will improve in new rule engine.

**Comment by eykamp** [comment]
Ok... I am pretty confident it works on an SQL database, but haven't tested it with a Cassandra setup because that's hard for me to do.  There is one more test case I need to verify, and this code has been done for a while, so the codebase has likely changed beneath it, so I'll need to make sure it merges smoothly.

**Comment by LeoMorgan113** [comment]
Hi @eykamp,

Is this issue still actual?

**Comment by eykamp** [comment]
If I never submitted a PR for this... maybe not.  I'll reopen if needed.
