### ISSUE TITLE
Import and export Dashboard states function

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#4390]
How to import and export dashboard states? I have 30 pages in one dashboard, same layout but for different IP device.  I built one page state, and I hope can export and import this state to add into the same dashboard, does TB has this function? If not, I suggest to develop one.

**Comment by t0mmyz7** [comment]
I want to 2nd this request.
some times we build a dashboard and need to use it as state instead, or vice versa, and we really can use the ability to import/export states, or states as dashboards, dashboards as states.

**Comment by KenSense** [comment]
Yes I also want that, looks like I have to create existing pages again to put them as state in the overview dashboard.

**Comment by pon0marev** [comment]
Duplicating states is bad practice and something like this will not be implemented in the platform.
Instead, use “Actions” and send the entity to the dashboard state. Then use “Entity from dashboard state” as an alias
![image](https://github.com/user-attachments/assets/4dcb9a63-9cec-4d78-bdc3-7889c4b15dcf)
Then use “entity from dashboard state” as an alias
![image](https://github.com/user-attachments/assets/b858fc25-ddfe-438e-8663-3d1b6c920ed7)
