### ISSUE TITLE
[Question] How can I subscribe to the attribute?

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4398]
**Component**

 * Generic

**Description**
How can I subscribe to the attribute that I use with this widget? 
![image](https://user-images.githubusercontent.com/78015483/114383958-6bbad600-9b8e-11eb-8537-806feebe1c05.png)

For example in the switch control we can subscribe to the attribute!
![image](https://user-images.githubusercontent.com/78015483/114384158-a886cd00-9b8e-11eb-8175-c7250950344d.png)

I have tried to send the value of the attribute when sending the "getDimming" method but I don't know how to return it.

![image](https://user-images.githubusercontent.com/78015483/114384306-d704a800-9b8e-11eb-8796-f4a43351bc61.png)

**Environment**

 * OS:  Windows 10 pro
 * ThingsBoard: ThingsBoard v.3.2.2PE
 * Browser: chrome

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
This widget used the RPC command to show/written attributes. To show the device's attribute values, widgets from 'Digital gauges' or 'Analogue gauges' bundles may be better for you.

**Comment by AbrahamSalvi** [comment]
What I need is something that RPC can send, since the send method does it correctly, but I need that when entering the view it has the current value of the "bright" attribute in this case.
Thank you very much for answering!

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity.
