### ISSUE TITLE
[Question] HTML Code for changing Dashboard state

### ISSUE THREAD

**Issue by Mirjka** [thingsboard/thingsboard#4407]
**Component**

 * UI

**Description**
Hi, I would like to implement some more obvious navigation buttons. The Widget header Actions are to small for a lot of users, so I added a html Button with a specific action "click on html element", but I can´t get it working. 

Here the dashboard and the "Menu"
![3](https://user-images.githubusercontent.com/46453902/114695759-42c84b80-9d1c-11eb-92c4-5f78a92469c6.PNG)

Here the html settings:
![1](https://user-images.githubusercontent.com/46453902/114695388-dbaa9700-9d1b-11eb-97a3-6eda3c7c3f47.PNG)

Here the action setting:
![2](https://user-images.githubusercontent.com/46453902/114695449-ee24d080-9d1b-11eb-9e5d-3b5cc339cb5b.PNG)

Maby a text is not recognized as a element?
**Environment**

 * OS:  WIN 10p
 * ThingsBoard: newest
 * Browser: FireFox newest

**Comment by Alentus** [comment]
Tag attibute "id" and action name must be same. And use link or button 

```HTML
<div class="navbar">
    <a id='home' >
        <i id='home' class="material-icons">home</i>
        <div id='home' class="menutext">Главная</div>
    </a>
    <a id='setup'  >
        <i id='setup' class="material-icons">settings</i>
        <div id='setup' class="menutext">Настройки</div>
    </a>
    <a id='status'>
        <i id='status' class="material-icons">wb_iridescent</i>
        <div id='status' class="menutext">Статус устройств</div>
    </a>
    <a id='alarms'>
        <i id='alarms' class="material-icons">format_align_justify</i>
        <div id='alarms' class="menutext">Журнал ошибок</div>
    </a>    
</div>
```
![image](https://user-images.githubusercontent.com/53187020/114709434-3d2b2f80-9d35-11eb-9e80-ed820945ce74.png)

**Comment by Mirjka** [comment]
Thanks, I see. Is it possible to encrease the size, colour and position of the symbol in order to make it matching the white labeling?

Here the button itselfe:
![1](https://user-images.githubusercontent.com/46453902/114882929-bc3b6900-9e04-11eb-9bf4-b2c6db9c467b.PNG)

And the code:
![2](https://user-images.githubusercontent.com/46453902/114882948-c2314a00-9e04-11eb-9817-1c08f9837ece.PNG)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
