### ISSUE TITLE
How to set up Kafka consumer on TB CE

### ISSUE THREAD

**Issue by badkoubeh** [thingsboard/thingsboard#4411]
I am trying to set up a Kafka consumer on TB CE to fetch some messages from a Kafka broker. The Kafka broker seems like it is an IoT Hub instance so I have a bootstrap server address and credentials to connect to this broker. I would like to know if the CE support Kafka clients and how to set it up on the Rule Engine.

 * OS:  macOS
 * ThingsBoard version: latest

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
