### ISSUE TITLE
ThingsBoard installation failed!

### ISSUE THREAD

**Issue by mechanicairev** [thingsboard/thingsboard#4412]
**Component**

 * Installation

**Description**
Although I have done all the steps correctly, I cannot complete the setup.

[install.log](https://github.com/thingsboard/thingsboard/files/6311505/install.log)
[tb-license.log](https://github.com/thingsboard/thingsboard/files/6311506/tb-license.log)
[thingsboard.err.log](https://github.com/thingsboard/thingsboard/files/6311507/thingsboard.err.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/6311508/thingsboard.log)
<img width="1080" alt="Unexpected error" src="https://user-images.githubusercontent.com/76724537/114727986-5a68f980-9d47-11eb-8cd0-bda2461057c0.png">
[thingsboard.out.log](https://github.com/thingsboard/thingsboard/files/6311509/thingsboard.out.log)
[thingsboard.wrapper.log](https://github.com/thingsboard/thingsboard/files/6311510/thingsboard.wrapper.log)

**Comment by Backdraft007** [comment]
Is it a fresh installation?
Do you have a license?
Why do you install an old version?

**Comment by trikimiki** [comment]
Hello,
I think you already have a database called "thingsboard" in your Postgres and it is populated with some data.
You can try the following:
1. Make a database backup.
2. Run "psql" console. It should be in your "Start" menu, under "Postgres".
3. Connect to your database with your Postgres credentials (default are postgres/postgres as user/password).
4. Drop database (this will delete all the data inside it): `drop database thingsboard;` (note the semicolon at the end of the command).
5. Create an empty database: `create database thingsboard;`
6. Re-run "install.bat".

**Comment by SergMeleshko** [comment]
Hello @mechanicairev 
Did the above answer help you?
