### ISSUE TITLE
[Question] HTTP integration not work

### ISSUE THREAD

**Issue by karaby** [thingsboard/thingsboard#4417]
**Component**

 * Installation
 * Generic

**Description**
Professional edition. 
Does not work HTTP integration. 
Response: 
{"timestamp":"2021-04-15T12:29:41.269+00:00","status":404,"error":"Not Found","message":"","path":"/api/v1/integrations/http/b64bf329-c4d2-afab-6525-66a5952877d3"}
Exactly the same integration on https://thingsboard.cloud/integrations works fine.

**Environment**

 * OS:  Kubernetes
 * ThingsBoard: 3.2.2 PE
 * Browser: - [curl]

**Comment by ban2derlog** [comment]
Hi, error 404 means that resource is blocked or missing for HTTP.
Do you add `/api/v1/integrations` to load balancer in K8s?
