### ISSUE TITLE
[Question] Thingsboard Version Control Scope

### ISSUE THREAD

**Issue by Cody-Hayes97** [thingsboard/thingsboard#4419]
**Description**
Hello! My team and I are trying to copy our ThingsBoard dev environment into a production environment. I know that there is functionality to be able to export the dashboards and rule chains to JSON and save those, but how would I go about doing this for all aspects of our ThingsBoard environment? things like the hierarchy, white labeling configurations, entity relationships, etc. We need to be able to completely copy the environment. Any help with this would be greatly appreciated!

**Environment**
 * OS:  windows 10
 * ThingsBoard: v3.1
 * Browser: google chrome

**Comment by trypzz** [comment]
Hi. Tell me, please, server OS where you installed thingsboard. And all 3-r party applications using with thingsboard.

**Comment by Cody-Hayes97** [comment]
> Hi. Tell me, please, server OS where you installed thingsboard. And all 3-r party applications using with thingsboard.

Hello, we are using Google Cloud Platform and running our ThingsBoard instance on a VM there

**Comment by trypzz** [comment]
I mean 3-r party applications. For example: Thingsboard using with **PostgresDB and Kafka**

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
