### ISSUE TITLE
[Question] How change the color widget?

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4423]
**Component**

 * Generic

**Description**
How can I change the color of the widget when it changes state?
![image](https://user-images.githubusercontent.com/78015483/114993375-0c193f00-9e9c-11eb-9acc-80118392df4a.png)

**Environment**

 * OS:  windows 10 
 * ThingsBoard: ThingsBoard v.3.2.2PE
 * Browser: chrome

**Comment by LeoMorgan113** [comment]
Hi @AbrahamSalvi,

Could you please specify color of what exactly do you want to change?

**Comment by adwait009** [comment]
I found the solution through one of the discussion threads on github.
https://github.com/thingsboard/thingsboard/issues/738

Regards,
Adwait
