### ISSUE TITLE
[Question] Line break in alarm details using API REST

### ISSUE THREAD

**Issue by mire22** [thingsboard/thingsboard#4435]
**Component**

 * UI

**Description**
I want to send alarm details with a line break in it, using the API REST of ThingsBoard.
It appears that the object "details" from the json is printed:
`details="1\n2"`
![image](https://user-images.githubusercontent.com/35899128/115062781-03038e80-9eeb-11eb-8007-4e3e92f22c04.png)
`details=["1", "2"]`
![image](https://user-images.githubusercontent.com/35899128/115062847-16165e80-9eeb-11eb-9422-9d84ba9acc2c.png)

I just want to have in the details block several lines to provide informations to the user.

Thank you!

**Environment**
 * OS:  Debian 10
 * ThingsBoard: 3.2.1
 * Browser: Mozilla Firefox 87.0

**Comment by ashaforost** [comment]
Thingsboard doesn’t provide a possibility to post-process alarm details. To override the default settings, you can create your custom action for the alarm widget settings to display alarm details in any format, suitable for you. Please refer to the [Custom Actions](https://thingsboard.io/docs/pe/user-guide/ui/widget-actions/#custom-action-with-html-template) article for more details on this topic.
