### ISSUE TITLE
[Question] Is it possible to use the same asset name for different customers?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#4439]
**Description**
Given two Customers A & B, we would like to create an Asset for each Customer with the same name e.g. "Building".
The name should be the same, but the asset has to be different for each of the two Customers (other location attributes etc.)

After I created the Asset in Customer A, I result with an Error Message when attempting to do the same for the second Customer:

![error](https://user-images.githubusercontent.com/25298332/115211065-7f6ebb00-a0ff-11eb-906f-fc508e2f1f9b.PNG)

Is there a way to create different Assets with the same name?
Otherwise the names has to be made unique, which would mean a lot of effort with like 50 customers.

**Environment**

 * ThingsBoard PE 3.2.0
 * Hybrid (Postgres + Cassandra)

Thanks in advance.

**Comment by vvlladd28** [comment]
Hi @mde2017,
To solve this problem, I can propose to create assets with different names but to set the same label for them.

**Comment by mde2017** [comment]
Thanks @vvlladd28 for your answer.
We will create unique names for assets and use the same entityLabels.
