### ISSUE TITLE
Feature Request : Multiple mail addresses in mail plugin/rules 

### ISSUE THREAD

**Issue by affoltep** [thingsboard/thingsboard#444]
It would be nice to have the possibility to send warnings/alarms to multiple email addresses. The actual mail plugin allows just one email recipient per TO/CC/BCC field.
As far I could do a small research, the used java mailer would allow comma separated inputs as [mail1@xy.com , mail2@xy.com]. So, if you know where to change, it may be a small adaption.

**Comment by ashvayka** [comment]
You can probably put something like:
a@a.com,b@b.com

Please check.

**Comment by affoltep** [comment]
Still generates the following error:
javax.mail.internet.AddressException: Illegal address in string

**Comment by affoltep** [comment]
Pull request #572 covers this feature request
