### ISSUE TITLE
 Send notifications using Telegram Bot

### ISSUE THREAD

**Issue by fatimazahrasifer** [thingsboard/thingsboard#4443]
**Description**
i would like to send alarms notifications using telegram API , i followed the documentation for sending temperature alarm using API rest , the alarms were configured but i didn't receive the notification from the telegram Bot

**Environment**

 * OS:  Mac OS
 * ThingsBoard: v.1.0.1
 * Browser: Firefox

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
