### ISSUE TITLE
[Feature Request] Control widget visiblity using Filters

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#4445]
The idea is to select which Widgets will be visible or not based on Filters. Similar to how data sources are seen or not based on the filters.

This is useful to create a cleaner user experience while not having to create duplicate dashboards or dashboard states for every configuration.

For example, a device config dashboard state, certain widgets are hidden based on filter.

or main dashboard, with certain graphs hidden or visible depending on the device configuration.

We work with IoT Transmitters that can have many different combos of sensors/controllers connected.

I would say the biggest challenge here will be to make the dashboard re-align / dynamically arrange itself when a widget is hidden. At the moment I am not sure the thingsboard UI engine can support this.

Does anyone else think this is a good idea?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
