### ISSUE TITLE
[Question] Persistent data send only lastest file in IOT gateway

### ISSUE THREAD

**Issue by Thammaruthai** [thingsboard/thingsboard#4447]
**Component**

 * UI

**Description**
I test the persistent data with unplug the LAN wire on first raspberry pi for 3 hours with setting in thingsboard-gateway like this

```
  type: file
  data_folder_path: /var/lib/ThingsboardGateway/
  max_file_count: 200
  max_read_records_count: 10
  max_records_per_file: 2000
```
in folder of 2nd raspberry pi  `/var/lib/ThingsboardGateway/`
has many file on the folder. Then I plug the LAN wire.  The chart of time series is show only the value in the last file ( I see from date create of file. the chart show from time of data create to time of data modify. )

How to config the chart to show all of persistent data in IOT gateway when is comeback to online.

**Environment**

 * OS:  1st raspberry pi 4 ubuntu 18.04(Thingsboard) , 2nd raspberry pi 4 ubuntu 18.04 (only thingsboard gateway)
 * ThingsBoard: v.3.2.2 CE

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
