### ISSUE TITLE
[Bug] empty body in response of rest-api call will occur error message: "Caused by: java.lang.IllegalArgumentException: argument "content" is null"

### ISSUE THREAD

**Issue by ksbneo** [thingsboard/thingsboard#4457]
**Describe the bug**
in Rule Chain, create a rest-api call, the call will return an empty body but with statusCode = 200.
In the right first subsequence widget (no matter what's the type of widget), it always returns failure status with the error message: "Caused by: java.lang.IllegalArgumentException: argument "content" is null"

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment: Ubuntu instance on AWS EC2
  * ThingsBoard Version: PE 3.2.2
  * OS Name and Version: Ubuntu 16.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windows
* Browser [e.g. chrome, safari]: chrome
* Version [e.g. 22]

**To Reproduce**
1. Go to 'Rule Chain', create a new rule chain
2. In the new rule-chain, create a REST-API Call to call a web service that returns an empty body in response.
3. At runtime, the REST-API Call works fine, but in the right after Widget (no matter what's sort of widget), would always return failure status, and report error message: Caused by java.lang.IllegalArgumentException: argument "content" is null

**Expected behavior**
Invoke empty body in REST-API Call without a problem.

**Screenshots**

**Additional context**

**Comment by steja-boku** [comment]
Any update on this ?

**Comment by pon0marev** [comment]
Following the RFC documentation, you should send response code 204 to the [GET](https://www.rfc-editor.org/rfc/rfc9110.html#name-get) request if the response has empty content: https://www.rfc-editor.org/rfc/rfc9110.html#status.200

**Comment by pon0marev** [comment]
We would like to inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more questions, please reopen this issue.
