### ISSUE TITLE
Accesstoken Based Authentication not working on Enabling MQTT TLS

### ISSUE THREAD

**Issue by ravipras8** [thingsboard/thingsboard#4458]
**Component**
 * MQTT

**Description**
I have enabled MQTT TLS, i am able to connect and send telemetry through X509 authentication mode. my problem is when MQTT TLS enabled, other authentications modes i.e Access token and Basic Auth is not working in backend i am getting java exception saying invalid device certificate. so please let me know is this valid scenario or not. or i should not us other authentication modes on MQTT TLS enabled?

**Environment**
Tried in multiple environment but results remain same.
 * OS:  Windows, Ubuntu
 * ThingsBoard: 3.2.1

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
