### ISSUE TITLE
[Question] Two-Way RPC with remote MQTT Integration

### ISSUE THREAD

**Issue by MarcelMann** [thingsboard/thingsboard#4461]
**Component**

 * Rule Engine
 * Generic

**Description**
I am trying to implement 2 way RPC with the remote MQTT integration. 

Example use-case:
In my Dashboard i have a knob-control. Using the Knob-Control for One-Way rpc (i.e. setting a value on my devices) works without any problems). When the dashboard- window reloads, the knob-control-widget tries to send a two-way RPC to get it's inital value. This RPC gets dropped in the downlink node in the rule engine, with "java.lang.RuntimeException: Only oneway RPC calls are supported in the integration!". That seems like wanted behaviour?

Is there any way to make such two-way RPCs with the remote integration?

**Environment**
 * OS:  Win10
 * ThingsBoard: thingsboard.cloud
 * Browser: Edge

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
