### ISSUE TITLE
[Bug]  504 Gateway Time-out, The server didn't respond in time.

### ISSUE THREAD

**Issue by Zdeno5** [thingsboard/thingsboard#4462]
**Describe the bug**
Dashboard not working, all time:
504 Gateway Time-out
The server didn't respond in time.

**Your Server Environment**
demo.thingsboard.io

**Your Client Environment**
Desktop:
* OS: WIN 10
* chrome
* Version 89.0.4389.128

* Connectivity
  * MQTT

**To Reproduce**
1. Just open Dashboards

**Expected behavior**
Not giving a big red error

**Screenshots**
![image](https://user-images.githubusercontent.com/40716132/115579422-72e88f00-a2c6-11eb-811a-f5032576e09a.png)

**Comment by vvlladd28** [comment]
Hi @Zdeno5,
 Can you repeat this problem?
 It was not detected during our chek.

**Comment by Zdeno5** [comment]
it seems to work now

> Hi @Zdeno5,
> Can you repeat this problem?
> It was not detected during our chek.

It seems to work now

**Comment by hyphenate93** [comment]
We had this same issue. It seems the Demo servers were down / very slow the last two days. It appears to be working now. However, telemetry data is no longer updating in real-time. These same issues were present last week and were fixed after the servers went offline for maintenance.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
