### ISSUE TITLE
[Bug] Clicking the download icon an choosing PDF, PNG, or JPG results in error

### ISSUE THREAD

**Issue by Cody-Hayes97** [thingsboard/thingsboard#4464]
**Describe the bug**
Hello, When logging on to ThingsBoard and navigating to the Main dashboard:
[menu](https://ibb.co/vmbv3KR)
 then clicking the download icon on the right side of the header to open the dropdown menu and clicking either PDF, PNG, or JPG, The dashboard gives this error:
[error](https://ibb.co/WDySWv0)

The expected result is to make a selection in the dropdown and download the selected file type (PDF, PNG, JPG)
Actual result: making a selection in the dropdown returns an error (see screenshot)
Downloading JSON data DOES WORK. 

Could Anyone please tell me how to fix this? Thanks!

* own setup
  * Google Cloud Platform
  * v3.1

* OS: Windows 10
* Browser Chrome

**To Reproduce**
1. Go to Dashboard
2. Click on download icon to the right side of the header
3. choose either PDF, PNG, or JPG

**Comment by trypzz** [comment]
Hi, clarify, please, do you use HAproxy or something else?

**Comment by PovitruliaV** [comment]
Hi @Cody-Hayes97,
Is this issue still relevant?
