### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mrroot998** [thingsboard/thingsboard#4469]
With thingsboard on docker-compose, on the web page, when we click on the assets part, we can access to the page without error but if we refresh the page (always on the assets page) an error occurs:

![assets_page_error](https://user-images.githubusercontent.com/82999391/115710756-fb246e00-a372-11eb-9354-574460a58bed.png)

I have the same error when I directly tape the root on my internet explorer.
(http://127.0.0.1:8080/assets)  

**Your Server Environment**
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version [3.2]
  * OS Name and Version: Ubuntu 20.04

**Client Environment**
**Desktop:**
* OS: [Ubuntu]
* Browser [chrome]
* Version [20.04]

* Connectivity
  * HTTP

**Comment by vvlladd28** [comment]
Hi @mrroot998,
Thank you for your report. We fixed the issue at maste branch #4353. The fix will add at the new release.

**Comment by mrroot998** [comment]
Thank you very much for your quick help.
