### ISSUE TITLE
I am not able to change the base URL of tb. you can not do this via the thingsboard config file. But it is possible to do this using proxy (apache2, nginx, haproxy)

### ISSUE THREAD

**Issue by anmobor** [thingsboard/thingsboard#4472]
you can not do this via the thingsboard config file. But it is possible to do this using proxy (apache2, nginx, haproxy)

_Originally posted by @vparomskiy in https://github.com/thingsboard/thingsboard/issues/1176#issuecomment-431870515_

May you provide a manual how to do that please.

**Comment by DenysDi** [comment]
duplicated to https://github.com/thingsboard/thingsboard/issues/1176
