### ISSUE TITLE
[Question] In a Widget, how to use a Schema to generate the html UI?

### ISSUE THREAD

**Issue by guifran** [thingsboard/thingsboard#4474]
I have a Json schema describing my UI, built using the standard format react-schema-form.
In a widget, I would like to use that schema to create the html UI.

Could you please guide me showing what code should be set as HTML and Javascript?

**Comment by guifran** [comment]
Edit:
Basically, I want to do what the Settings schema is doing.
The Settings schema is defining the Settings UI.
I want to define the widget UI using a schema.

That should be pretty simple, as all the libraries must already be included to do that, but I've not been able to find any example.
Any help would be very appreciated.

**Comment by dhaval2017** [comment]
here is the sample examples
thingsboard is using this builder

http://networknt.github.io/react-schema-form/
