### ISSUE TITLE
Thingsboard millions of concurrent tests

### ISSUE THREAD

**Issue by ahawzp** [thingsboard/thingsboard#4477]
We are now doing simulations of millions of data concurrency. In the process of using the official tool gatling to test, as long as the number of concurrency increases, the database will lose data. The currently tested architect thingsboard is a single machine, a Cassandra cluster, and a test architecture such as postgresql. At present, when the data concurrency reaches 10,000, data will be lost. Can your company help provide some ideas and architecture for concurrent testing of the thingsboard platform? Looking forward to your reply.

**Comment by den1jkee** [comment]
Hi,
do you still need help with that setup ?
