### ISSUE TITLE
[Question] get device telemetry value

### ISSUE THREAD

**Issue by GregoryW21** [thingsboard/thingsboard#4482]
I am using V3.2.2
I am using image map.
I can show all asset on the image map. 
I would like to show the device telemetry value under asset tooltips. 

Under the tooltip function, I can only get the corresponded asset entity information. How can I the the device telemetry value. 

I already build the relationship in between asset and device, and also add device to Datasources. However, when it call asset tooltips, I don't know how to get the device telemetry value.

Thanks

**Comment by LeoMorgan113** [comment]
Hi @GregoryW21,

You can customize your tooltip in advanced settings with tooltip functions:
![2021-06-01_16-04](https://user-images.githubusercontent.com/56256429/120328017-1039d880-c2f3-11eb-854f-347bca798c55.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
