### ISSUE TITLE
[Question] Can a devie be assinged to multi customers?

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#4483]
If one tenant has many customers and many devices, can he assign a device to multi customers?
In the current version, only one customer it can be assiged?

**Comment by ssakharova** [comment]
Hello @lsyer,

Following the documentation: ThingsBoard allows you to configure multiple custom Entity Groups. Each entity (device/asset/entity view/customer/user/dashboard) may belong to multiple groups simultaneously.

You can refer to 
https://thingsboard.io/docs/pe/user-guide/groups/
