### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by adriortega** [thingsboard/thingsboard#4488]
**Component**

 * Rule Engine

**Description**

Hi everyone, I have some problems with the performance of the thingsboard Rule Engine. I have displayed several serial scripts nodes, in order to transform the payload data. I have notice that some of the output data do not correspond to the theorical input data. I have made several trials and I think that the possible problem could be an asynchronous performance of the Rule Engine. Viewing the logs in Debug Mode, some of the input payload enter to the node at the same time, so they may be doing interferences between them.

I am gonna show you an example of this situation. In the input msg there is always the same payload, and when I test my function, the output msg is different each execution.

Test 1.

![image](https://user-images.githubusercontent.com/71086524/116069227-7051b500-a68b-11eb-8cc5-1877dcad3158.png)

Test 2. 

![image](https://user-images.githubusercontent.com/71086524/116069268-7ba4e080-a68b-11eb-80ce-80e2b63c9ac1.png)

Test 3.

![image](https://user-images.githubusercontent.com/71086524/116069324-8a8b9300-a68b-11eb-8522-fc19ee25ed03.png)

As you can see, in every photograh the output result is different. 

So I would like to know if it is possible my interfereces hypotesis. Because it is not usual that codes porduce fails.

Regards and Thanks.

Adrian

**Environment**
 * OS:  Windows 10 64 bits
 * ThingsBoard: version 3.2.2
 * Browser: Chrome Version 89.0.4389.128 (Build oficial) (64 bits)

**Comment by vvlladd28** [comment]
Hi @adriortega,
Please check the script in the Rull node (before declaration used var). Maybe while writing the transform script was forgotten declaration variable, and it caused using a global variable.

**Comment by adriortega** [comment]
Hi @vvlladd28 and thanks for your answer, but I don´t understand exactly what do you refer to. Do I have to change my code writing var declaration? If you can explain it a bit longer or with an example I would be perfect.

Thank you very much and best wishes.

**Comment by vvlladd28** [comment]
Hi @adriortega,
Bad code (use global values):
```
deviceName = metadata.deviceLabel;
alarmName = metadata.alarmName;
alarmValue = metadata.alarmValue;
msg = alarmName + "alarm on device " + deviceName + "\n" + "Value: " + alarmValue;
return {msg: msg, metadata: metadata, msgType: msgType}; 
```

Good code (use local values)::
```
var deviceName = metadata.deviceLabel;
var alarmName = metadata.alarmName;
var alarmValue = metadata.alarmValue;
var msg = alarmName + "alarm on device " + deviceName + "\n" + "Value: " + alarmValue;
return {msg: msg, metadata: metadata, msgType: msgType};
```
