### ISSUE TITLE
attibutes / keys usage in post processing function not implemented?

### ISSUE THREAD

**Issue by rsajben** [thingsboard/thingsboard#449]
Hi,

I can't acces any variables (keys, attributes) inside post-processing functions except ones defined in the function header 

function(time, value, prevValue) {
   return value;
}

is there a way to tailor how measured data are interpreted when multiple devices are shown in the same graph? I cant' use the same constant for all of them) Something similar to

function(time, value, prevValue) {
   return ${attr_koef}*value;
}

or

function(time, value, prevValue, attributes) {
   return attributes.koef*value;
}

BTW: Map widgets can work with attributes similar way - in advanced configuration - for displaying tooltip data ...

Thanks

Radovan

**Comment by rsajben** [comment]
Hi Mark,

I have no answer regarding the post-processing functions options. I just
use it with constant values ... actual value multiplied by a number. Never
tried the prevValue.
One workaround probably could be some script getting, calculating and
writting back results regularly via the provided API ... a kind of API
based batch re-calculation ...

Radovan

Dňa 23. 2. 2018 9:21 dopoludnia používateľ "enviroEYE" <
notifications@github.com> napísal:

**Comment by enviroeye** [comment]
Thanks Radovan, much appreciated, we’ve quietly been trying to avoid writing the capability into our middleware, but it looks like its the only way forward!

**Comment by vparomskiy** [comment]
additional parameters were added into PostPorcessing function since ThingsBoard v2.2
