### ISSUE TITLE
[Question] SNMP telemetry

### ISSUE THREAD

**Issue by mgelfand2009** [thingsboard/thingsboard#4491]
**Component**

  * Generic

**Description**

Good day!
I am new to TB, now the task is to organize monitoring through SNMP.
It was possible to configure the gateway, but taking into account the fact that for some reason the "get" method does not work, only the "walk" method, the data from sensors comes like this:
 
{"1.3.6.1.4.1.3854.2.3.2.1.4.16": "19", "1.3.6.1.4.1.3854.2.3.2.1.4.17": "21", "1.3.6.1.4.1.3854.2. 3.2.1.4.18 ":" 20 "," 1.3.6.1.4.1.3854.2.3.2.1.4.19 ":" 18 "," 1.3.6.1.4.1.3854.2.3.2.1.4.20 ":" 20 " , "1.3.6.1.4.1.3854.2.3.2.1.4.21": "26", "1.3.6.1.4.1.3854.2.3.2.1.4.22": "23", "1.3.6.1.4.1.3854.2. 3.2.1.4.23 ":" 18 "," 1.3.6.1.4.1.3854.2.3.2.1.4.43 ":" 21 "," 1.3.6.1.4.1.3854.2.3.2.1.4.48 ":" 18 " , "1.3.6.1.4.1.3854.2.3.2.1.4.49": "28", "1.3.6.1.4.1.3854.2.3.2.1.4.50": "22", "1.3.6.1.4.1.3854.2. 3.2.1.4.51 ":" 19 "," 1.3.6.1.4.1.3854.2.3.2.1.4.52 ":" 19 "," 1.3.6.1.4.1.3854.2.3.2.1.4.53 ":" 22 " , "1.3.6.1.4.1.3854.2.3.2.1.4.54": "22", "1.3.6.1.4.1.3854.2.3.2.1.4.55": "22"}

now the problem is to split this line into 17 sensors by TB resourses. For further binding to dashboard widgets.

Tell me how to do this?

And, accordingly, another question - why does the "get" method not work in SNMP requests in the telemetry section? Or am I doing something wrong?

**Environment**

  * ThingsBoard: version PE 3.2.2

Screen of telemetry section:

![Снимок экрана 2021-04-26 в 16 56 07](https://user-images.githubusercontent.com/83076321/116071963-54143f00-a6b0-11eb-82ed-4199d5edb60c.png)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
