### ISSUE TITLE
[Bug] Reports-server does not wait for the dashboard to be fully loaded before capturing

### ISSUE THREAD

**Issue by Delapouite** [thingsboard/thingsboard#4507]
Hello.

We have a scheduler that regularly triggers the generation of reports in PDF.
Most of the time, everything works as expected.

Unfortunately, we also observe that in some case the generated PDFs are useless, because they only captured loading dashboards, where the data is not yet present and only the loading spinners are shown.

Example: 

![image](https://user-images.githubusercontent.com/39315/116435502-b6ee0d80-a84b-11eb-8651-0c987e75d035.png)

In more technical terms, the headless browser in charge of taking the screenshot and convert it info a PDF, is way too eager and does not wait for ThingsBoard to be ready before doing its job.

How would you tackle this issue? Is there any way to tell the reports server to wait a bit more longer before taking the screenshot to let ThingsBoard a few more seconds to fully display the dashboards?

Thanks

**Comment by uiplEa** [comment]
Same problem here. We are using thingsboard 3.2.2 on thingsboard.cloud
We have set up the scheduler to send daily reports as PDF with 24 h graphs. Sometimes we get mails with incomplete dashboard view. We also got mails with a PDF which shows the login screen. 

It seems the system recognizes the fault and tries it again. But it sends several incomplete PDFs in mails. This is not so nice for real used customer applications.

**Comment by BCTFuchs** [comment]
We have the same issue here. This function is completely useless. Sometimes it works, sometimes it does not work. We are using TB-Cloud. 
I thought, that maybe the big amount of data-points causes a delay during page-load. But reducing time-window to a more moderate size does definitely not improve the situation.

**Comment by jch889** [comment]
Hello, 
We have a similar error, but in our case the generated PDF contains the login screen.

We are using TB PE 3.4.1

![Screenshot 2022-11-30 150637](https://user-images.githubusercontent.com/43139163/204875905-0f51e7ec-7b7a-42ec-bb24-a768e7d5452d.jpg)
![Screenshot 2022-11-30 150747](https://user-images.githubusercontent.com/43139163/204875908-c3f32969-fcd8-4ae6-bbce-761249511a32.jpg)

**Comment by Ieva111** [comment]
Was there any solution for the issue?

**Comment by AndreSensaway** [comment]
We are having the same issue. Reports generated, both by the scheduler or by using the download button of the dashboard, have missing data in multiple widgets.

Any fix for this?

**Comment by Ultrazombie** [comment]
Closed due to inactive.

**Comment by IoTThinks** [comment]
> We had the same issue. Reports generated, both by the scheduler or by using the download button of the dashboard, had missing data in multiple widgets.
> 
> Our fix was by configuring the tb-web-report service. changed the /usr/share/tb-web-report/conf/default.yml file and increased the dashboardIdleWaitTime parameter:
> 
> ```
> browser:
>   # Browser launch timeout (ms)
>   launchTimeout: "60000"
>   # Default page navigation timeout (ms)
>   defaultPageNavigationTimeout: "120000"
>   # Generate report request timeout (ms)
>   generateReportTimeout: "30000"
>   # Load dashboard resources timeout (ms)
>   loadDashboardResourcesTimeout: "60000"
>   # Dashboard idle wait time (ms)
>   dashboardIdleWaitTime: "2000"
>   # Max browser pages
>   maxPages: "5"
> ```

The fix is working.
Thanks a lot.
