### ISSUE TITLE
[Question] Global Access of Thingsboard (on-premise) Server

### ISSUE THREAD

**Issue by arsalanqasimahmed** [thingsboard/thingsboard#4518]
I have setup thingsboard (community edition) on-premise on my laptop using the installation guide for windows. I am able to send device telemetry data from a NodeMCU to this server. The problem is, this works only when the NodeMCU is on the local area network (same as the server) and it uses the private IP of my laptop as the thingsboard server IP to send data. 

When the NodeMCU is on a different network, it can not connect to the server using the public IP address of the laptop (which I found from an IP telling website). I know this would require some specific network configuration but I am not too sure how to sequentially go about this.

I want to know the process of making this work. Any guide in this regard would be appreciated.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
