### ISSUE TITLE
Application based authentication

### ISSUE THREAD

**Issue by kpranga** [thingsboard/thingsboard#452]
Dear creators, 
Do you plan to implement authentication based on application or asset?
I'm trying to create system for more than 100 End Nodes and it's not effective to make a different connector for every signgle device. Maybe you have some solution for it?
Best Regards

**Comment by vparomskiy** [comment]
@kpranga if it is still valid request for you, could you provide more details on how you see it in real life.

**Comment by kpranga** [comment]
Hi @vparomskiy, I managed it by using TB-Gateway to make the connection from LoRaWAN server.
