### ISSUE TITLE
Creating a Map widget

### ISSUE THREAD

**Issue by Ccorreia08** [thingsboard/thingsboard#4526]
Hi all, I am totally new to thingsboard so forgive me if my question is too basic. I've been following some tutorials online yet I have not been able to display a marker for a device on a map. 

This is what I did as a test:

1) Create a device called "node" and assign to it a latitude and a longitude as attributes (in the decimal system).
2) Create Dashboard and Alias for that single device.
3) Create widget using the widget bundles and selecting "latest values" and google maps widget.
4) As data source for the widget I used the two attributes (Latitude and Longitude) for the device.

This however, has not worked for me and the map does not display any marker. 
 Is there anything wrong in what I did above? Do I need a rule chain or an asset to accomplish this?

I have attached the widget as it shows no markers of the node Im trying to add.

Thank you all in advance.

![thingsboard](https://user-images.githubusercontent.com/83451656/116683806-65ab5e80-a9b0-11eb-85ff-9ec53508b154.jpg)

**Comment by Ccorreia08** [comment]
Hi, to whoever might have the same issue.  I was able to fix this by clustering the markers in advanced settings.

**Comment by Backdraft007** [comment]
I have no problems. Can you give more screenshots with details of your device?
