### ISSUE TITLE
[Bug] refresh token gives 401 error

### ISSUE THREAD

**Issue by rezaUniqe** [thingsboard/thingsboard#4532]
**Describe the bug**
hi i m new to thingsboard I'm trying to get new token from refresh token and I tried this:

headers:

'Content -Type': 'application/json'
'X-Authorization': bearer token
data:

"refreshToken": refreshToken

with   api/auth/token

but it gives me this error:
{"status":401,"message":"Token has expired","errorCode":11,"timestamp":"2021-05-03T09:04:06.214+00:00"}

**Comment by LeandroCuello** [comment]
Same problem in 3.5.1 PE
```
{
    "status": 401,
    "message": "Authentication method not supported",
    "errorCode": 10,
    "timestamp": "2023-06-14T20:15:58.373+00:00",
    "subscriptionErrorCode": null,
    "subscriptionEntry": null,
    "subscriptionValue": null
}
```
