### ISSUE TITLE
customer user home dashboard

### ISSUE THREAD

**Issue by abdelhadi9** [thingsboard/thingsboard#4535]
* UI
 

**Description**
I created a customer group wich in it there is several customers with a user group wich has a custom role with limited ressources of visualizing dashbords and widgets only. and later i create for each customer a group of dashboards and devices and i share them with him.
My problem is when i assign a home dashbord for a user it doesn't appear in the home page only default dashboard is assigned and works as default.
My second problem is i don't want that the customer user to see the group of devices that i shared with him, (i didn't give him device ressource in the role ressources). Can i do that?

**Environment**

 * OS:  cloud
 * ThingsBoard: 3.2.2 paas
 * Browser: chrome latest

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
