### ISSUE TITLE
REST API call 'getCustomerDevices' has changed

### ISSUE THREAD

**Issue by achenje** [thingsboard/thingsboard#4544]
**Component**

 * Installation
 * REST API

**Description**
REST API call 'getCustomerDevices' has changed after updating TB from **v2.4.3** to **v.3.2.2**
In v2.4.3. it was:
_get /api/customer/{customerId}/devices{?type,textSearch,idOffset,textOffset,limit}_

In v3.2.2 it is
_get /api/customer/{customerId}/devices{?type,textSearch,sortProperty,sortOrder,pageSize,page}_ 

The problem is that with v2.4.3 API I was able to get a list of all devices that are assigned to the customer. With v.3.2.2 I have to iterate through the pages to get a complete list of assigned devices. 

We use our own developped MES to show devices that are assigned to specific customers which is not possible anymore. 
Is there a way to use the old REST API version from v2.4.3 with the new v3.2.2?

**Environment**

 * OS:  Kybernetes installation
 * ThingsBoard: 3.2.2
 * Browser: Firefox

**Comment by Backdraft007** [comment]
Try to set pageSize=1000 and page=0

**Comment by achenje** [comment]
Thanks. It works perfectly fine!
