### ISSUE TITLE
[Question] Widget development example

### ISSUE THREAD

**Issue by achenje** [thingsboard/thingsboard#4547]
**Component**

 * Widget Development

**Description**
Is there an open widget library available that shows the JS code, the settings schemes, the HTML, CSS schemes etc.?

I have carefully read TB's user guide for widget development (https://thingsboard.io/docs/user-guide/contribution/widgets-development/) and created my own "silo" widget, but I am missing some details especially for timeseries data with my a graphical widget. 
For instance the default settings in the "settings scheme" of the TB IDE will not all be shown in the "Advance" tab when I actually create the widget in my dashboard.

Maybe somebody has some examples for me!?    

**Environment**

 * OS:  Kybernetes
 * ThingsBoard: v3.2.2
 * Browser: Firefox

Here is my settings scheme:
{
    "schema": {
        "type": "object",
        "title": "Settings",
        "properties": {
            "minValue": {
                "title": "Minimum weight",
                "type": "number",
                "default": 0
            },
            "maxValue": {
                "title": "Maximum weight",
                "type": "number",
                "default": 500
            },
            "lowerLimit": {
                "title": "Lower limit",
                "type": "number",
                "default": 100
            },
            "upperLimit": {
                "title": "Upper limit",
                "type": "number",
                "default": 200
            },
            "neonGlowBrightness": {
                "title": "Neon glow effect brightness, (0-100), 0 - disable effect",
                "type": "number",
                "default": 0
            },
            "dashThickness": {
                "title": "Thickness of the stripes, 0 - no stripes",
                "type": "number",
                "default": 0
            },
            "roundedLineCap": {
                "title": "Display rounded line cap",
                "type": "boolean",
                "default": false
            },
            "title": {
                "title": "Gauge label",
                "type": "string",
                "default": "Silo"
            },
            "showTitle": {
                "title": "Show gauge label on top",
                "type": "boolean",
                "default": false
            },
            "unitTitle": {
                "title": "Unit label",
                "type": "string",
                "default": "kg"
            },
            "showUnitTitle": {
                "title": "Show unit label",
                "type": "boolean",
                "default": true
            },
            "showLimits": {
                "title": "Show limit values",
                "type": "boolean",
                "default": true
            },
            "showTimestamp": {
                "title": "Show value timestamp",
                "type": "boolean",
                "default": true
            },
            "timestampFormat": {
                "title": "Timestamp format",
                "type": "string",
                "default": "dd.MM.yyyy                                 HH:mm:ss"
            },
            "showValue": {
                "title": "Show weight value",
                "type": "boolean",
                "default": true
            },
            "showMinMax": {
                "title": "Show min / max weight values",
                "type": "boolean",
                "default": true
            },
            "gaugeWidthScale": {
                "title": "Width of the gauge element",
                "type": "number",
                "default": 1.00
            },
            "baseColor": {
                "title": "Between lower and upper limit color",
                "type": "string",
                "default": "##FFC000"
            },
            "highColor": {
                "title": "Above upper limit color",
                "type": "string",
                "default": "00B050"
            },
            "lowColor": {
                "title": "Below lower limit color",
                "type": "string",
                "default": "#C00000"
            },
            "limitStrokeColor": {
                "title": "Limit stroke color",
                "type": "string",
                "default": "#5c5c5c"
            },
            "gaugeColor": {
                "title": "Background color of the gauge element",
                "type": "string",
                "default": "#d8d8d8"
            },
            "titleFont": {
                "title": "Gauge title font",
                "type": "object",
                "properties": {
                    "family": {
                        "title": "Font family",
                        "type": "string",
                        "default": "Roboto"
                    },
                    "size": {
                        "title": "Size",
                        "type": "number",
                        "default": 10
                    },
                    "style": {
                        "title": "Style",
                        "type": "string",
                        "default": "normal"
                    },
                    "weight": {
                        "title": "Weight",
                        "type": "string",
                        "default": "400"
                    },
                    "color": {
                        "title": "color",
                        "type": "string",
                        "default": null
                    }
                }
            },
            "labelFont": {
                "title": "Font of label showing under value",
                "type": "object",
                "properties": {
                    "family": {
                        "title": "Font family",
                        "type": "string",
                        "default": "Roboto"
                    },
                    "size": {
                        "title": "Size",
                        "type": "number",
                        "default": 6
                    },
                    "style": {
                        "title": "Style",
                        "type": "string",
                        "default": "normal"
                    },
                    "weight": {
                        "title": "Weight",
                        "type": "string",
                        "default": "400"
                    },
                    "color": {
                        "title": "color",
                        "type": "string",
                        "default": "#595959"
                    }
                }
            },
            "valueFont": {
                "title": "Font of label showing current value",
                "type": "object",
                "properties": {
                    "family": {
                        "title": "Font family",
                        "type": "string",
                        "default": "Roboto"
                    },
                    "size": {
                        "title": "Size",
                        "type": "number",
                        "default": 10
                    },
                    "style": {
                        "title": "Style",
                        "type": "string",
                        "default": "normal"
                    },
                    "weight": {
                        "title": "Weight",
                        "type": "string",
                        "default": "400"
                    },
                    "color": {
                        "title": "color",
                        "type": "string",
                        "default": "#595959"
                    }
                }
            },
            "minMaxFont": {
                "title": "Font of minimum and maximum / upper and lower limit labels",
                "type": "object",
                "properties": {
                    "family": {
                        "title": "Font family",
                        "type": "string",
                        "default": "Roboto"
                    },
                    "size": {
                        "title": "Size",
                        "type": "number",
                        "default": 5
                    },
                    "style": {
                        "title": "Style",
                        "type": "string",
                        "default": "normal"
                    },
                    "weight": {
                        "title": "Weight",
                        "type": "string",
                        "default": "300"
                    },
                    "color": {
                        "title": "color",
                        "type": "string",
                        "default": "#595959"
                    }
                }
            }
        }
    },
    "form": [
        "showTitle",
        "title",
        "showUnitTitle",
        "unitTitle",
        "showMinMax",
        "minValue",
        "maxValue",
        "showLimits",
        "lowerLimit",
        "upperLimit",
        "neonGlowBrightness",
        "dashThickness",
        "roundedLineCap",
        "showTimestamp",
        "timestampFormat",
        "showValue",
        "gaugeWidthScale",
        {
            "key": "highColor",
            "type": "color"
        },
        {
            "key": "baseColor",
            "type": "color"
        },
        {
            "key": "lowColor",
            "type": "color"
        },
        {
            "key": "limitStrokeColor",
            "type": "color"
        },
        {
            "key": "gaugeColor",
            "type": "color"
        },
        {
            "key": "titleFont",
            "items": [
                "titleFont.family",
                "titleFont.size",
                {
                    "key": "titleFont.style",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "italic",
                            "label": "Italic"
                        },
                        {
                            "value": "oblique",
                            "label": "Oblique"
                        }
                    ]
                },
                {
                    "key": "titleFont.weight",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "bold",
                            "label": "Bold"
                        },
                        {
                            "value": "bolder",
                            "label": "Bolder"
                        },
                        {
                            "value": "lighter",
                            "label": "Lighter"
                        },
                        {
                            "value": "100",
                            "label": "100"
                        },
                        {
                            "value": "200",
                            "label": "200"
                        },
                        {
                            "value": "300",
                            "label": "300"
                        },
                        {
                            "value": "400",
                            "label": "400"
                        },
                        {
                            "value": "500",
                            "label": "500"
                        },
                        {
                            "value": "600",
                            "label": "600"
                        },
                        {
                            "value": "700",
                            "label": "800"
                        },
                        {
                            "value": "800",
                            "label": "800"
                        },
                        {
                            "value": "900",
                            "label": "900"
                        }
                    ]
                },
                {
                    "key": "titleFont.color",
                    "type": "color"
                }
            ]
        },
        {
            "key": "labelFont",
            "items": [
                "labelFont.family",
                "labelFont.size",
                {
                    "key": "labelFont.style",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "italic",
                            "label": "Italic"
                        },
                        {
                            "value": "oblique",
                            "label": "Oblique"
                        }
                    ]
                },
                {
                    "key": "labelFont.weight",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "bold",
                            "label": "Bold"
                        },
                        {
                            "value": "bolder",
                            "label": "Bolder"
                        },
                        {
                            "value": "lighter",
                            "label": "Lighter"
                        },
                        {
                            "value": "100",
                            "label": "100"
                        },
                        {
                            "value": "200",
                            "label": "200"
                        },
                        {
                            "value": "300",
                            "label": "300"
                        },
                        {
                            "value": "400",
                            "label": "400"
                        },
                        {
                            "value": "500",
                            "label": "500"
                        },
                        {
                            "value": "600",
                            "label": "600"
                        },
                        {
                            "value": "700",
                            "label": "800"
                        },
                        {
                            "value": "800",
                            "label": "800"
                        },
                        {
                            "value": "900",
                            "label": "900"
                        }
                    ]
                },
                {
                    "key": "labelFont.color",
                    "type": "color"
                }
            ]
        },
        {
            "key": "valueFont",
            "items": [
                "valueFont.family",
                "valueFont.size",
                {
                    "key": "valueFont.style",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "italic",
                            "label": "Italic"
                        },
                        {
                            "value": "oblique",
                            "label": "Oblique"
                        }
                    ]
                },
                {
                    "key": "valueFont.weight",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "bold",
                            "label": "Bold"
                        },
                        {
                            "value": "bolder",
                            "label": "Bolder"
                        },
                        {
                            "value": "lighter",
                            "label": "Lighter"
                        },
                        {
                            "value": "100",
                            "label": "100"
                        },
                        {
                            "value": "200",
                            "label": "200"
                        },
                        {
                            "value": "300",
                            "label": "300"
                        },
                        {
                            "value": "400",
                            "label": "400"
                        },
                        {
                            "value": "500",
                            "label": "500"
                        },
                        {
                            "value": "600",
                            "label": "600"
                        },
                        {
                            "value": "700",
                            "label": "800"
                        },
                        {
                            "value": "800",
                            "label": "800"
                        },
                        {
                            "value": "900",
                            "label": "900"
                        }
                    ]
                },
                {
                    "key": "valueFont.color",
                    "type": "color"
                }
            ]
        },
        {
            "key": "minMaxFont",
            "items": [
                "minMaxFont.family",
                "minMaxFont.size",
                {
                    "key": "minMaxFont.style",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "italic",
                            "label": "Italic"
                        },
                        {
                            "value": "oblique",
                            "label": "Oblique"
                        }
                    ]
                },
                {
                    "key": "minMaxFont.weight",
                    "type": "rc-select",
                    "multiple": false,
                    "items": [{
                            "value": "normal",
                            "label": "Normal"
                        },
                        {
                            "value": "bold",
                            "label": "Bold"
                        },
                        {
                            "value": "bolder",
                            "label": "Bolder"
                        },
                        {
                            "value": "lighter",
                            "label": "Lighter"
                        },
                        {
                            "value": "100",
                            "label": "100"
                        },
                        {
                            "value": "200",
                            "label": "200"
                        },
                        {
                            "value": "300",
                            "label": "300"
                        },
                        {
                            "value": "400",
                            "label": "400"
                        },
                        {
                            "value": "500",
                            "label": "500"
                        },
                        {
                            "value": "600",
                            "label": "600"
                        },
                        {
                            "value": "700",
                            "label": "800"
                        },
                        {
                            "value": "800",
                            "label": "800"
                        },
                        {
                            "value": "900",
                            "label": "900"
                        }
                    ]
                },
                {
                    "key": "minMaxFont.color",
                    "type": "color"
                }
            ]
        }
    ]
}

**Comment by ChantsovaEkaterina** [comment]
Hello, @achenje 
Do you mean that you would like to display some advanced settings conditionally?

**Comment by achenje** [comment]
Hello Ekaterina,

thanks for the reply. I could resolv theissue in the meantime.
However, would it be possible to get some samples for graphical timerseries widgets.
I designed a few graphical timeseries widgets e.g. Silo, Truck, Container etc. myself but I dam missing agood manual or tutorial. Examples would be also very beneficial.

Thanks in advance
![silo_scale](https://user-images.githubusercontent.com/83758598/120313907-ee345c00-c2da-11eb-889e-0223662740f4.JPG)

**Comment by ChantsovaEkaterina** [comment]
Hello, @achenje 
Unfortunately, there is no other guide for widgets development besides the one you have already read (https://thingsboard.io/docs/user-guide/contribution/widgets-development/).
As examples you can consider all widgets available in the widgets library.
Good examples of sophisticated JSON schemes for advanced settings are maps and charts widgets, also you could take a look at gauges.

**Comment by skewty** [comment]
If I understand correctly you are looking for some example Widgets that are not bundled into ThingsBoard.
Being bundled into ThingsBoard gives them all sorts of coding advantages that I believe we will not get (like TypeScript).

I'd really like to code my widgets in TypeScript like this (for example):

```typescript
import { Widget, WidgetContext } from 'somewhere/thingsboard/widget/models';

class FooWidget implements Widget {
    constructor(protected ctx: WidgetContext) {
         ...
    }

    public onInit(): void {
    }

}
```

But I don't think they offer this type of developer experience for Widgets at this time.

Also note that their client side code uses Angular, React, jQuery and LoDash to name just a few.

You can see many of the core interfaces at:
https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/core/api/widget-api.models.ts

Anyone figured out a way to use TypeScript in Widgets with all the nice parts like type hints and VCS?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
