### ISSUE TITLE
PSOC6 AMQP

### ISSUE THREAD

**Issue by arkastratuscent** [thingsboard/thingsboard#4551]
Hi All,

Does thingsboard support device connection using AMQP?
We have a psoc6 based device where the development of the firmware was done using AMQP.
I dont see any documentation how to connect PSOC6 to Thingsboard when using AMQP.

Many Regards,
Arka

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
