### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by LinnSense-CodeRepo** [thingsboard/thingsboard#4556]
Hello Community, 

Backround:
Probuct: Thingsboard PE Cloud (TRIAL LICENCE) 
OS: Windows 10
Device: Esp8266
Protocol: MQTT

I have hit a road block, can someone help? :
I am following the following guide:

https://thingsboard.io/docs/samples/esp8266/temperature/

The only difference is I would like to communicate via the PE Cloud server as I am interested in using the benifts of the Scheduler widget. 
The code I have embedded works with the Demo Server. 
The main difference is on this line of code:

char thingsboardServer[] = "YOUR_THINGSBOARD_HOST_OR_IP";

Question: what is the PE Cloud Host Or IP. 

I have tried the code below and it gives no errors when sent, however, where it goes I don't know. I am logged into the PE Cloud UI. 

char thingsboardServer[] = "thingsboard.cloud";

I appreciate any help with this, 

Kind Regards
Caoilte

**Comment by kastayou** [comment]
Did you try with "cloud.thingsboard.io"?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
