### ISSUE TITLE
How to build docker image for `tb-postgres` only?

### ISSUE THREAD

**Issue by adksujan** [thingsboard/thingsboard#4559]
Hi, On building docker images from source the documentation tells `mvn clean install -Ddockerfile.skip=false`, which basically builds everything. How can we build docker image for standalone `tb-postgres` only ?

**Comment by trypzz** [comment]
Hi. Clarify please, you want to build thingsboard from sources and connect him to dockerize postgres?

**Comment by zhangjun03402** [comment]
My approach is：
1. first do package of msa/tb in the parent root directory，the -pl parameter tells maven to work for the specified module only:
   mvn clean package -Dmaven.test.skip=true -Ddockerfile.skip=false -pl msa/tb -am
2. and then go to the directory you want, here is msa/tb，
    mvn dockerfile:build@build-docker-tb-postgres-image -Dmaven.test.skip=true -Ddockerfile.skip=false
   build-docker-tb-postgres-image is the execution id in the pom

**Comment by trypzz** [comment]
Hi,
We using the default postgres image. Please, follow https://hub.docker.com/_/postgres

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
