### ISSUE TITLE
thingsboard gateway modbus

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard#4560]
i am configring thingsboard-gateway ,about modbus Connection over TCP/UDP protocol. 
The data type of device is boolean type,Example:
 "timeseries": [
          {
            "tag": "test",
            "type": "bits",
            "functionCode": 2,
            "objectsCount": 1,
            "address": 1
          }
        ],
But all the data of device is false. use 'modbus poll' of tools test ，result  has 1(one) or  0(zero).
Please tell me how to solve this problem
 Tanks a lot!
**Versions (please complete the following information):**
 - OS: [CentO S7  ]
 - Thingsboard IoT Gateway version [e.g. 2.6]
 - Python version[e.g. 3.6]
 - Thingsboard 3.2.2

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
