### ISSUE TITLE
[QUESTION] Better documentation on how to build from source

### ISSUE THREAD

**Issue by glennvdv** [thingsboard/thingsboard#4561]
Documentation says:
- install java 11
- install maven
- execute mvn clean install

But i'm getting failed test in the DAOLayer. It tries to connect to localhost:5432. I assume this is a postgress instance? Do i need to start a docker container manually? Or should this be started automatically (testcontainers,...).
Or am i missing something?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
