### ISSUE TITLE
[Question] docker-compose install can not download tb-snmp-transport and tb-lwm2m-transport

### ISSUE THREAD

**Issue by xvjialing** [thingsboard/thingsboard#4562]
**Component**

 * Installation

**Description**
after run ` ./docker-start-services.sh` , docker-compose install can not download docker image `thingsboard/tb-snmp-transport:latest` and `thingsboard/tb-lwm2m-transport:latest` .
```shell
 ./docker-start-services.sh
Creating network "docker_default" with the default driver
Pulling tb-web-ui1 (thingsboard/tb-web-ui:latest)...
latest: Pulling from thingsboard/tb-web-ui
Digest: sha256:259f686dfe943eac0086936bbd74cb1dbaf04ef13dc73621a19ac95d22af43cc
Status: Downloaded newer image for thingsboard/tb-web-ui:latest
Pulling postgres (postgres:12)...
12: Pulling from library/postgres
Digest: sha256:06277995d7028f4455e56f21864146ee2425c83308dc96283c7a96e6881cc826
Status: Downloaded newer image for postgres:12
Pulling zookeeper (zookeeper:3.5)...
3.5: Pulling from library/zookeeper
Digest: sha256:cb85895866f826ff53a2488fba04e5741258873548f45736a35501673e3a2cc8
Status: Downloaded newer image for zookeeper:3.5
Pulling redis (redis:4.0)...
4.0: Pulling from library/redis
Digest: sha256:2e03fdd159f4a08d2165ca1c92adde438ae4e3e6b0f74322ce013a78ee81c88d
Status: Downloaded newer image for redis:4.0
Pulling kafka (wurstmeister/kafka:2.13-2.6.0)...
2.13-2.6.0: Pulling from wurstmeister/kafka
Digest: sha256:b40a84a356310acf701edef76dcced2afd3570702689c7a03d08273c4e45062a
Status: Downloaded newer image for wurstmeister/kafka:2.13-2.6.0
Pulling tb-http-transport1 (thingsboard/tb-http-transport:latest)...
latest: Pulling from thingsboard/tb-http-transport
Digest: sha256:022509b0898d9796d26a0617449750ea878b8d890f68a4efbbe16655808f4b29
Status: Downloaded newer image for thingsboard/tb-http-transport:latest
Pulling tb-js-executor (thingsboard/tb-js-executor:latest)...
latest: Pulling from thingsboard/tb-js-executor
Digest: sha256:27d3d1ebe7b1f513d83d39cc6f894ea16c8b44972dd85b4506f6e5bc4dd8fb31
Status: Downloaded newer image for thingsboard/tb-js-executor:latest
Pulling tb-rule-engine1 (thingsboard/tb-node:latest)...
latest: Pulling from thingsboard/tb-node
Digest: sha256:b4d94a2a1999d770c32cd9f4336bd39bfd1df2fbe33d6f51f4aef1aa7d81e671
Status: Downloaded newer image for thingsboard/tb-node:latest
Pulling tb-snmp-transport (thingsboard/tb-snmp-transport:latest)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling tb-snmp-transport (thingsboard/tb-snmp-transport:latest)...
pull access denied for thingsboard/tb-snmp-transport, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Environment**

 * OS:  ubuntu 16.0.4
 * ThingsBoard: 3.2.2

**Comment by xvjialing** [comment]
in the folder `docker`

**Comment by whdwanghaidong** [comment]
i have the same question too!

**Comment by xvjialing** [comment]
> i have the same question too!
there are no image for thingsboard/tb-snmp-transport:latest and thingsboard/tb-lwm2m-transport:latest in docker hub, so i remove this two image from docker-compose config files

**Comment by whdwanghaidong** [comment]
> > i have the same question too!
> > there are no image for thingsboard/tb-snmp-transport:latest and thingsboard/tb-lwm2m-transport:latest in docker hub, so i remove this two image from docker-compose config files

when i remove two images from docker-conpose.yml ,it make a new error:
ERROR: The Compose file is invalid because:
Service tb-lwm2m-transport has neither an image nor a build context specified. At least one must be provided.

can you help me?

**Comment by whdwanghaidong** [comment]
> > i have the same question too!
> > there are no image for thingsboard/tb-snmp-transport:latest and thingsboard/tb-lwm2m-transport:latest in docker hub, so i remove this two image from docker-compose config files

when i remove two images from docker-compose.yml ,it make a new error:
ERROR: The Compose file is invalid because:
Service tb-lwm2m-transport has neither an image nor a build context specified. At least one must be provided.

can you help me?

**Comment by pszymkowiak** [comment]
you should remove in docker-compose.kafka.yml tb-snmp-transport and tb-lwm2m-transport also in order to work.

**Comment by trypzz** [comment]
Hi, try to remove (or comment) lines with tb-lwm2m-transport and tb-snmp-transport in all used docker-compose files. And run docker-compose again.

**Comment by whdwanghaidong** [comment]
got it

**Comment by trypzz** [comment]
Hi, @whdwanghaidong 
Tell me, please, it working now?

**Comment by whdwanghaidong** [comment]
> Hi, @whdwanghaidong
> Tell me, please, it working now?

Yes,it works fine.
