### ISSUE TITLE
[Question] how to display the difference between two telemetries at one day time interval?

### ISSUE THREAD

**Issue by mkdthanga** [thingsboard/thingsboard#4570]
**Component**

 * UI

**Description**
I want to display the rate of increase in honey weight for every day (sensor: honey weighing scale), I tried using post processing function in table widget, but it was not giving many possibilities other than accessing the previous value and current value!
I want to have a post-processing function like 
**return current value - Value at 0:00 Hrs (midnight);**
or 
**return current value - Value before 24 hrs;**
**See screenshot:**
![image](https://user-images.githubusercontent.com/36918728/118003361-cdff2600-b348-11eb-8a85-9052a2d45819.png)

**Environment**

 * OS:  Ubuntu and 18.04
 * ThingsBoard: 3.2.1
 * Browser: Chrome and  90.0.4430.72

Could anyone please help me out or suggest me anything for my requirement?

Regards,
Thangz

**Comment by ChantsovaEkaterina** [comment]
Hello, @mkdthanga 
As an alternative, you could perform data processing in the rule chain.
To fetch historical data you can use the _originator telemetry_ rule node _(Enrichment)_.

**Comment by jonrot1906** [comment]
You could also set your data history to "Last: 30 Days", "Data aggregation: max" and "Grouping interval: 1 day". That will show the max value in 24 hour steps. Then just add a datasource with something like:

`x=value-prevOrigValue;
return x;`

And you should be fine ;-)

**Comment by mkdthanga** [comment]
Hello @ChantsovaEkaterina, 
thank you so much, it really helped and I succeeded in implementing it too! Thank you once again!

**Comment by mkdthanga** [comment]
Hello @jonrot1906,
I haven't tried it yet, but sounds to be working and practical! Thanks anyways!

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
