### ISSUE TITLE
[Question] Update Another Widget on Custom Action Row Click

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4579]
* UI
Hello !
Please tell me how to update another widget content when one row from the first widget is clicked ?
Thank You !
Here is a picture for better understanding.

![TB_REQUEST](https://user-images.githubusercontent.com/59779817/118197868-7b149400-b458-11eb-9520-9c87826f208e.jpg)

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.2.2

**Comment by LeoMorgan113** [comment]
Hi @lmax25,

If you want to update another widget content you may try the next solutions:
1. Use "Update current dashboard state" for action type, if all widgets are the same.
https://thingsboard.io/docs/user-guide/ui/widget-actions/#update-current-dashboard-state
2. In case of difference, you may try "Navigate to other dashboard" action type.
https://thingsboard.io/docs/user-guide/ui/widget-actions/#navigate-to-other-dashboard

**Comment by dhaval2017** [comment]
add custom action on row click or action cell button
update entity alias of targeted widget with selected entity

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
