### ISSUE TITLE
Calling Rest API of Thingsboard through Ajax, working fine on IE, but giving error on chrome.

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [thingsboard/thingsboard#458]
**Error:**
Failed to load http://localhost:8080/api/plugins/telemetry/DEVICE/8ca63470-d370-11e7-b261-89d910061ae4/values/timeseries?keys=longitude,latitude: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**GET Request:**

$.ajax({
 type: 'GET',
 crossDomain: true,
 url: "http://localhost:8080/api/plugins/telemetry/DEVICE/"+device_id_rest[device_id_index]+"/values/timeseries?keys=longitude,latitude",
 contentType: "application/json",

 dataType: "JSON",
xhrFields: {
    withCredentials: true
  },

   beforeSend:function(xhr){
    console.log("beforesend");

    xhr.setRequestHeader ("X-Authorization", "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnQxQHRoaW5nc2JvYWQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiIzNjkyM2E4MC1kMzY1LTExZTctYjI2MS04OWQ5MTAwNjFhZTQiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiYmVhYjc0NjAtZDM2My0xMWU3LWIyNjEtODlkOTEwMDYxYWU0IiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTExODgwNTQ5LCJleHAiOjE1MjA4ODA1NDl9.sSexUNn1iQKiAc2gaBV0E8uOhHnrzDsZcU8u238xNpETqmr6IDhQh7DAZ_QpWI13qstyhOGBtkKuqIdx-_naQg");
  },

success:function(data){

latitude=data['latitude'][0]['value'];
longitude=data['longitude'][0]['value'];

update_marker(device_id_index,latitude,longitude);

},
  error:function(error){
    console.log(error);
  }

});

**Comment by JacquelineGoh** [comment]
Hi kamran000,

Can you enlighten me the way to get retrieve back the data from thingsboard?
I do not really understand how it works.

Do I need to prepare a database to save the query data?
What type of tools should I use to enter the link address?
[http://localhost:8080/api/plugins/telemetry/DEVICE/47a76ba0-ad9b-11e7-a5ac-2f8f3fdf329b/values/timeseries?keys=a1,a](http://localhost:8080/api/plugins/telemetry/DEVICE/47a76ba0-ad9b-11e7-a5ac-2f8f3fdf329b/values/timeseries?keys=a1,a2)

I hope I can hear from you. :)
Thank you and have a nice day.

**Comment by kamran000** [comment]
Hi @JacquelineGoh,
you will find following links useful for your query. 

https://thingsboard.io/docs/user-guide/telemetry/

https://support.ladesk.com/061754-How-to-make-REST-calls-in-PHP

https://stackoverflow.com/questions/27700513/how-to-get-data-from-jquery-ajax-requests

**Comment by kamran000** [comment]
Hi @JacquelineGoh 

You can change expiration time in thingsboard.yaml file  
  tokenExpirationTime: "${JWT_TOKEN_EXPIRATION_TIME:9000000}" # Number of seconds (15 mins)

https://thingsboard.io/docs/user-guide/install/config/
