### ISSUE TITLE
[Question] Thingsboard How To Opendashboardstate in Separate Dialog

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4580]
Hello !

Please tell me : how to open dashboard state in separate dialog using a custom option 

Thank You !

I  have this code to open a dashboard state in normal mode:

var $injector = widgetContext.$scope.$injector;
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe(function(device) {
     
  if(device.type == 'TEMP&HUM SENSOR'.trim()) {
  openDashboardState('TEMP&HUM-SENSOR'.trim());
 }
});

function openDashboardState(stateId) {
 var params = {
 entityId: entityId,
 entityName: entityName
 };

 widgetContext.stateController.openState(stateId, params, false);
}

**Environment**
 * OS:  UBUNTU 18.04
 * ThingsBoard: 3.2.2

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Comment by Adw1284** [comment]
https://github.com/thingsboard/thingsboard/issues/4292#issuecomment-2155009216
