### ISSUE TITLE
[Bug] Custom Widget Angular binding not updating when calling http.get(...)

### ISSUE THREAD

**Issue by Bliph** [thingsboard/thingsboard#4582]
**Describe the bug**
We are creating a custom widget for ThingsBoard 3.2.2PE using Angular bindings. The widget is getting data from a REST-service (running on the same server as Thingsboard). We are callin `self.ctx.http.get('...')` to retrieve data from the REST-service. The problem is that the widget data/view is not updated when the data subscription "returns". 

The code contains a object created by self.ctx.http.get() and adds a subscription to this object. Whe the subscription 
returns a data object, we are not able to update the view using standard Angular bindings. We are however able to update
the DOM directly by calling `document.getElementById(<id>).innerHTML = <text>`

We also tried to wrap the code inside a self.ctx.ngZone.run(), but that did not help.

**Your Server Environment**
* OS: Ubuntu 20.04
* ThingsBoard 3.2.2PE

**Your Client Environment**
* OS: Windows 10
* Browser: Chrome
* Version: Version 90.0.4430.212 (Official Build) (64-bit)

**To Reproduce**

HTML:
```
<!DOCTYPE HTML>
<div>
    <div>
        <button mat-raised-button color="primary" (click)="load()"> 
            Async Load
        </button>
        <button mat-raised-button color="primary" (click)="nothing()"> 
            Do nothing
        </button>
    </div>
    <div>
        <div>Link: {{some_link}}</div>
        <div>DOM: <span id='html_id'>...</span></div>
        <div>Curly: {{response_text}}</div>
    </div>
</div>
```

Javascript:
```
let $scope;

self.onInit = function() 
{
    console.log(self);
    $scope = self.ctx.$scope;
    $scope.some_link = '/api/v1/U3NYx2YqVeaEYKQBXxcC/attributes';
    $scope.response_text = '...';
    $scope.nothing = function()  {};

    $scope.load = function() 
    {
        $scope.response_text = '...';
        document.getElementById("html_id").innerHTML = '...';
        self.ctx.ngZone.run(() =>
        {
            const obs = self.ctx.http.get($scope.some_link, { responseType: 'text' });
            obs.subscribe(data => { 
                $scope.response_text = data;
                document.getElementById("html_id").innerHTML = data;
            });
        });
    };
};
```

Please se Widget code. Note that the link is a direct reference using a access token. To reproduce, **please replace this access token with your own access token!**

1. Click on 'Async Load'
2. -> DOM: Text string is updated (but not curly)
3. Click on 'Do nothong'
4. -> Curly: Text string is updated

Prior to step 1: Initial look
![1](https://user-images.githubusercontent.com/49234210/118274370-59052b00-b4c5-11eb-87d4-b93657e9cb95.png)

Step 2:
![2](https://user-images.githubusercontent.com/49234210/118274382-5d314880-b4c5-11eb-8a61-4a6bfe6facf3.png)

Step 4:
![3](https://user-images.githubusercontent.com/49234210/118274400-602c3900-b4c5-11eb-8baf-9221cc65a260.png)

**Expected behavior**
Both DOM and Curly texts should be uptdated at the same time when clicking 'Async Load'. Angular bindings should be updated on async callbacks the same way that DOM is updated. This has be tested to work in a "pure" Angular app running outside ThingsBoard with (almost) identical code.

**Comment by ChantsovaEkaterina** [comment]
Hello, @Bliph 
The code below should help you to solve the issue with data updating:
```
obs.subscribe(data => { 
    $scope.response_text = data;
    self.ctx.detectChanges();
}); 
```

**Comment by Bliph** [comment]
Thanks! It really did solve my issue!
Is this a bug, or a (undcomumented) feature of how the change detection is implemented in ThingsBoard?

**Comment by ChantsovaEkaterina** [comment]
@Bliph 
It is not a bug. For widgets and from now on for dashboards, the OnPush change detection strategy is used.
https://angular.io/api/core/ChangeDetectionStrategy

**Comment by Bliph** [comment]
Ok. Thanks for clafication. I guess it would be a good idea to include a note about this in the Thingsboard Widget development section. I'm closing this issue as the original problem is solved.
