### ISSUE TITLE
[Question]Any possible to trigger relation event when a device add relation to a asset？

### ISSUE THREAD

**Issue by eydonmlau** [thingsboard/thingsboard#4586]
Hi,
    When a device add relation to a asset, I did not see any relation event, but the message can only seen in audit logs. Can it possbile to add some events such like relation event?
    When deleting a device from th TB CE, I want to know the device are no longer belongs to the asset, so triggering an event may be a good idea? or how can I konw  this special message in the rule chains? 

thanks~

**Comment by mLaurFunkwerk** [comment]
I have the exact same Issue. It would be perfect, if an event would be released whenever a Relation is created, updated or deleted. Right now a change of a Relation does not release any event. My company is using Thingsboard PE self hosted solution. Connecting Entities with your relation feature is a huge part of our use case.

Great product beside that.

Any advice is appreciated.

Thank you

**Comment by gohm-tech** [comment]
Hi @ashvayka,

We have the exact same issue. Please inform us.

Best Regards,
**Gohm Team**
