### ISSUE TITLE
Ubuntu Install: thingsboard: unrecognised service[Bug] 

### ISSUE THREAD

**Issue by Jayelzibub** [thingsboard/thingsboard#4587]
I followed the installation guide to the letter at https://thingsboard.io/docs/user-guide/install/ubuntu/

No issues at all installing on Ubuntu using in-memory queue service and postgres.  I get to the very last command- "sudo service thingsboard start" and get this error:
thingsboard: unrecognised service

I performed a service --status-all command and thingsboard is not in the list.

**Your Server Environment**

* own setup
  * Local Infrastructure
  * thingsboard 3.2.2
  * Ubuntu 20.04.2.LTS

I would have expected that I would start the service and it would start successfully and I could open my browser to localhost:8080 but with no service running I cannot.

Can you please advise at what part the service is added to the service list and any idea of what I may have done wrong?

**Comment by trypzz** [comment]
Hi, @Jayelzibub 

Can you provide this log `/var/log/thingsboard/install.log`?

**Comment by Jayelzibub** [comment]
Sure, here you go
[install.log](https://github.com/thingsboard/thingsboard/files/6568528/install.log)

**Comment by trypzz** [comment]
@Jayelzibub , paste here, please, output of this commands `systemctl | grep thingsboard` and `ls /sys/fs/cgroup/memory/system.slice/thingsboard.service/`

**Comment by Jayelzibub** [comment]
grep: and: No such file or directory
grep: ls: No such file or directory
grep: /sys/fs/cgroup/memory/system.slice/thingsboard.service/: No such file or directory
System has not been booted with systemd as init system (PID 1). Can't operate.

**Comment by trypzz** [comment]
@Jayelzibub these are two different commands.
Use:
 `systemctl | grep thingsboard`
and after first command use this:
`ls /sys/fs/cgroup/memory/system.slice/thingsboard.service/`

**Comment by Jayelzibub** [comment]
"System has not been booted with systemd as init system (PID 1). Can't operate."

I assume this is the problem, my Ubuntu is booted within Windows.

**Comment by trypzz** [comment]
You are using WSL?

**Comment by Jayelzibub** [comment]
Yes, sorry I should have mentioned that in my intial opening.

**Comment by trypzz** [comment]
Oh. We are sorry, but we do not support WSL at this time. You can try to install thingsboard for Windows or Windows with Docker. 
Visit please these links for additional information. 

Windows: https://thingsboard.io/docs/user-guide/install/windows/

Windows with Docker: https://thingsboard.io/docs/user-guide/install/docker-windows/

I'm closing this issue.

**Comment by Jayelzibub** [comment]
Ah ok, I understand, it does work I just need to run - sudo /usr/share/thingsboard/bin/thingsboard.jar
