### ISSUE TITLE
[Question] UDP using mulitple udp integrations

### ISSUE THREAD

**Issue by sebsoft** [thingsboard/thingsboard#4588]
**Integrations**

I have an (remote) UDP itegration running which works fine.  Now i would like to add another UDP integration running on a different port.  My goal is to have devices of type A sending to port xx  and devices of type B sending data to port yy, is  this possible ?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
