### ISSUE TITLE
Is Rule Chain being bypassed? 

### ISSUE THREAD

**Issue by antoniocgg** [thingsboard/thingsboard#4589]
**Component**

 * Rule Engine

**Description**
I cut the link between **Message Type Switch** and **Save Timeseries** and I can still see the telemetry on the  _"Last Telemetry"_ tab.
Is my Rule Chain being bypassed?

I selected the specific Rule chain in "Device Profile" and the device is under the rigth device profile. 

**Environment**

 * OS:  Windows 10
 * ThingsBoard: PE Cloud
 * Browser: Chrome  90.0.4430.212

**Comment by LeoMorgan113** [comment]
Hi @antoniocgg,

I have tested it on my TB, but everything works clear.
Maybe you need to clean the cache, restart TB, check all, and try again.

![2021-06-01_15-19_1](https://user-images.githubusercontent.com/56256429/120322151-c51cc700-c2ec-11eb-92b2-8443bdb5607e.png)

![2021-06-01_15-18](https://user-images.githubusercontent.com/56256429/120322145-c3eb9a00-c2ec-11eb-8823-571584a837a4.png)
![2021-06-01_15-19](https://user-images.githubusercontent.com/56256429/120322149-c4843080-c2ec-11eb-998f-1f120bb74f22.png)

**Comment by antoniocgg** [comment]
Thank you @LeoMorgan113 !
