### ISSUE TITLE
Add ability to delete historic telemetry data for a specific device

### ISSUE THREAD

**Issue by JWood48** [thingsboard/thingsboard#459]
During testing i have set up several test devices and logged some telemetry data to them, now i would like to delete all past telemetry data to start fresh, but this is only possible by deleting the device and creating a new device?

**Comment by mp-loki** [comment]
@JWood48 you can connect to your database and cleanup ts_kv and ts_kv_latest tables manually

**Comment by LeoMorgan113** [comment]
Hi @JWood48,

You may use API Delete request to delete telemetry from a certain period:
https://thingsboard.cloud/swagger-ui.html#!/telemetry-controller/deleteEntityTimeseriesUsingDELETE

You can read more about swagger up to this link: https://thingsboard.io/docs/reference/rest-api/

Also, you can make your Rest API request using REST API CALL node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node
