### ISSUE TITLE
[Bug] Unexpected Permission Error to delete Device Entity using custom delete CRUD on dashboard

### ISSUE THREAD

**Issue by shiyapiku-dev** [thingsboard/thingsboard#4591]
I followed the tutorial on [How to perform CRUD operations from the dashboard (custom action with HTML template)](https://www.youtube.com/watch?v=4qSSbqXntEQ)

No issues at with "edit entity" action with other user group but for "delete entity" custom action from dashboard, a permission error pops-up resulting the user group unable to delete the entity.

I added **all permission and roles** on the user group to manage the dashboard, devices and entities but the permission
problem still persists.

Your Server Environment

    own setup
        Local Infrastructure
        thingsboard 3.2.2
        Ubuntu 20.04.2.LTS

Screenshots
![delete-job-screenshot-1](https://user-images.githubusercontent.com/68854705/118594885-b3abc900-b7dc-11eb-8855-56ce4c856762.png)
![delete-job-screenshot-2](https://user-images.githubusercontent.com/68854705/118594889-b5758c80-b7dc-11eb-92de-88367318f975.png)
![delete-job-screenshot-3](https://user-images.githubusercontent.com/68854705/118594893-b6a6b980-b7dc-11eb-80b2-d21bcefe377f.png)
![user-group-roles](https://user-images.githubusercontent.com/68854705/118594895-b7d7e680-b7dc-11eb-9685-9e15ec7898a8.png)

I would have expected the user group to easily delete the device entity from dashboard as the "edit entity" custom dashboard action is working well.

Can you please advise at what permission should I add to fix this bug and any idea of what I may have done wrong?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
