### ISSUE TITLE
[Question] Dashboard creation automation

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#4596]
**Component**
 * Rule Engine

**Description**
Hi there , tell me is it possible to automate the process of creating dashboards?

**Comment by Backdraft007** [comment]
Hi,
https://thingsboard.io/docs/pe/solution-templates/overview/

**Comment by ashaforost** [comment]
Hi,
You can also find useful the [Python](https://thingsboard.io/docs/reference/python-rest-client/) or [Java REST Client](https://thingsboard.io/docs/reference/rest-client/) to interact with ThingsBoard REST API via your application.
