### ISSUE TITLE
[Question] Filters

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4598]
**Component**

 * Generic

**Description**
Good morning, when I create filters they are always chained with "and" and depend on each other. How could I create filters with "or" or that do not depend on each other?

![image](https://user-images.githubusercontent.com/78015483/118777590-8537f780-b889-11eb-9e57-d468b882b3bd.png)

**Environment**

 * OS:  windows 10 
 * ThingsBoard: 3.2.2PE
 * Browser: google chrome

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
Currently, this function is not available for TB. In future versions, we plan to add create filters with "or".

**Comment by AbrahamSalvi** [comment]
Hi @vvlladd28, i can use twos filters for the map widget?
thanks!

![Captura](https://user-images.githubusercontent.com/78015483/118951856-ba147f00-b95b-11eb-890d-b4a4e3f1f0ed.PNG)

![Captura1](https://user-images.githubusercontent.com/78015483/118951863-bc76d900-b95b-11eb-8ffc-6c9babb68173.PNG)

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi, 
The map widget can use two or more filters

**Comment by AbrahamSalvi** [comment]
Hi @vvlladd28 , I add 2 filters but the widget only use the first.

![image](https://user-images.githubusercontent.com/78015483/118971438-b854b680-b96f-11eb-8983-a0f96267a9c7.png)

**Comment by AbrahamSalvi** [comment]
Both filters use the filter massive for current user.

![image](https://user-images.githubusercontent.com/78015483/118972560-f900ff80-b970-11eb-870c-4ed2d6012b13.png)

**Comment by vvlladd28** [comment]
Hi @AbrahamSalvi,
The two-filter approach will only work if the key labels match at two data sources. (You need to delete the number 2 in the key labels)

**Comment by AbrahamSalvi** [comment]
Hi, sorry but I have not understood the answer very well, You tell me that having these two filters, they could affect the map widget independently without depending on the other? 

![image](https://user-images.githubusercontent.com/78015483/119800065-f3f60000-bedc-11eb-9edf-a1a4c1234238.png)

**Comment by vvlladd28** [comment]
Hi, @AbrahamSalvi 
I meant that you need to configure the map widget.
![Screenshot from 2021-05-31 10-38-11](https://user-images.githubusercontent.com/18036670/120158703-18175100-c1fd-11eb-9769-2c6e6d422354.png)
When creating multiple data source, you need to give the same label for the data keys, because widget working a single label.

**Comment by AbrahamSalvi** [comment]
@vvlladd28  thank you so much :)
