### ISSUE TITLE
install_dev_db.sh file installation failled!! on Thingsboard

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#460]
Hi ,
    After builded Things-board source. I have trying to install following directory binary 

**Thingsboard{DIR-}/application/target/bin/install/ install_dev_db.sh,**

 but I have some problem on Ubuntu. please help me to fix it. have attached my logs. Thanks

Getting the following error:

===================================================
 :: ThingsBoard ::       (v1.4.0-SNAPSHOT)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'databaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cassandraDatabaseSchemaService': Unsatisfied dependency expressed through field 'cluster'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraInstallCluster': Invocation of init method failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1] Cannot connect))
ThingsBoard DB installation failed!

**Comment by vparomskiy** [comment]
It looks like appliczation try to connect to Cassandra on localhost (127.0.0.1:9042), but is doesn't started.
Did you start Cassandra before starting Thingsboard?
You also can use PostgreSQL or HSQLDB as alternative storage.
