### ISSUE TITLE
Need help with error with thingsboard/tb-postgres on docker windows

### ISSUE THREAD

**Issue by Obiwan-Cannabis** [thingsboard/thingsboard#4600]
**Component**

 * Installation

**Description**
Trying to install thingsboard/tb-postgres on docker windows by following the thingsboard installation (https://thingsboard.io/docs/user-guide/install/docker-windows/) but got error:
"connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Environment**

 * OS:  docker desktop v3.3.3(64133)
 * ThingsBoard: 3.2.2

**Comment by trypzz** [comment]
Hi @Obiwan-Cannabis,
Can you provide commands what are you using? I've tested instructions on fresh and clear new Windows 10 installation and it's working fine.

Where you find this log?

Which did you choose **WSL 2 backend** or **Hyper-V backend and Windows containers** while installing Docker Desktop?

**Comment by Obiwan-Cannabis** [comment]
I retried yesterday. It worked. Don't know what i did wrong the first time. Probably a folder misspelled. 

Thx anyway for the answer
