### ISSUE TITLE
Need to be able to group Users within a Customer

### ISSUE THREAD

**Issue by codyclay88** [thingsboard/thingsboard#461]
Is there a way within ThingsBoard to group together Users within the same customer? For example, there are several cases where we need to be able to send alerts for a subset of the Users for a customer. 

Also, within the User entities can we add custom attributes/properties? I believe the only pieces of data we can store for a user are Name, Description, and Email Address, but some of our customers require Twilio text or voice messages so we'd like to store phone numbers if possible. 

Other than these issues we are loving ThingsBoard so far! Keep up the good work!

**Comment by vparomskiy** [comment]
@codyclay88 You can use Role-Based access control that is available in thingsBoard PE v 2.3
It allows to group users and assign different permissions to groups. Here is the description:
https://thingsboard.io/docs/user-guide/rbac/
