### ISSUE TITLE
[Question] Using the Request Connector, in the ThingsBoard IOT Gateway, the Device cannot be seen in the ThingsBoard Dashboard

### ISSUE THREAD

**Issue by karpal-Gmail** [thingsboard/thingsboard#4611]
**Component**

 * UI

**Description**
Using the Request Connector, in the ThingsBoard IOT Gateway, the Device cannot be seen in the ThingsBoard Dashboard under the Relations using the From filter

**Environment**
ThingsBoard Server running in Ubuntu
ThingsBoard IOT Gateway running in Ubuntu using Request Connector

When I check for the device in the ThingsBoard Server, it is not displayed under Relations using the From filter.

Please advise.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
