### ISSUE TITLE
[Bug] Latest value Custom widget and self.ctx.defaultSubscription.data[0].data[0][1] not working and cannot save the widget

### ISSUE THREAD

**Issue by zimbot97** [thingsboard/thingsboard#4612]
**Describe the bug**
I have follow this example in hoping to build a custom widget, https://thingsboard.io/docs/user-guide/contribution/widgets-development/#time-series-example, however Thingsboard can obtain the data but would not allow me to save the widget.

**Your Server Environment**

* own setup
  * local infrastructure (running on localhost)
  * ThingsBoard 3.2.2

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 16.04
* Browser Firefox
* Version :3.2.2

* Connectivity
  * MQTT
  

**Expected behavior**
It should have save and allow user to run

**Screenshots**
![image](https://user-images.githubusercontent.com/41312147/119208331-4d70c000-bad4-11eb-88bb-eef997ab1673.png)

**Additional context**
console.log and the gauge behind the error warning was able to react according to value but could not be saved

**Comment by ChantsovaEkaterina** [comment]
Hello, @zimbot97 
To prevent the error try to add an additional check if the data variable exists and not empty, what could happen on the first update function call.

**Comment by Civilduino** [comment]
This solved the problem as @ChantsovaEkaterina recommended
https://stackoverflow.com/questions/5113374/javascript-check-if-variable-exists-is-defined-initialized
Thanks!
