### ISSUE TITLE
I get the error as follows  : Cannot initialize ESP module ; No tag found ; WiFi shield not present

### ISSUE THREAD

**Issue by RaduZaha** [thingsboard/thingsboard#4613]
13:45:28.378 -> [WiFiEsp] Initializing ESP module
13:45:29.387 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:31.361 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:33.392 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:35.369 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:37.393 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:38.404 -> [WiFiEsp] Cannot initialize ESP module
13:45:44.429 -> [WiFiEsp] >>> TIMEOUT >>>
13:45:44.429 -> [WiFiEsp] No tag found
13:45:44.476 -> WiFi shield not present

I am trying to do the temperature and humidity project using esp9288 and dht 22.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
