### ISSUE TITLE
how to use ctx attribute service to call getEntityTimeseries 

### ISSUE THREAD

**Issue by HNKSara** [thingsboard/thingsboard#4614]
**Component**

 * Generic

**Description**
 Hi,
I want to call ctx.attributeservice.getEntityTimeseries  to get sum of timseries as a column in EntityTable-widget. so I called that in 
advanced javascript section of widget column.

**_e = entity.id; //entityId
t = ["lat"]; //keys keys=gas,temperature
n = 1479735870785; //startTs
i = 1479735871858; //endTs
a = 100; //limit
o = "SUM" //agg
u = 60000; //interval
p = "AVG"; //orderBy
d = false; //useStrictDataTypes
m = 1; //config

sum= ctxmain.attributeService.getEntityTimeseries(
    entityId = e, keys = t, startTs = n, endTs = i,
    agg = o, interval = u , limit=a);        
return sum;_**

 but i am witnessed this result:

**_e {_isScalar: false, source: e, operator: e}
operator: e {project: ƒ, thisArg: undefined}
source: e {_isScalar: false, source: e, operator: e}
_isScalar: false
__proto__: Object_**

i expect to get a number or list of number as output, please give me a solution
thanks in advance

**Environment**

 * ThingsBoard: CE

**Comment by ChantsovaEkaterina** [comment]
Hello, @HNKSara 
Hope, code below will help you. Also, please note, that the _getEntityTimeseries_ method is asynchronous.
```
const attributeService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('attributeService'));
attributeService.getEntityTimeseries(entityId, keys, startTs, endTs, limit, agg, interval).subscribe((data) => {
    console.log(data);
})
```

**Comment by HNKSara** [comment]
Hi, 
thanks, it works fine.
but there is some edit:
self removed:
const attributeService = ctx.$scope.$injector.get(ctx.servicesMap.get('attributeService'));
attributeService.getEntityTimeseries(entityId, keys, startTs, endTs, limit, agg, interval).subscribe((data) => {
    console.log(data);
})


**the result is here:**
{ workload: Array(1) }
workload: Array(1)
0: {ts: 1620033938000, value: "768"}
length: 1
__proto__: Array(0)
__proto__: Object
