### ISSUE TITLE
BUTTONS on navigation 

### ISSUE THREAD

**Issue by eschummer01** [thingsboard/thingsboard#4615]
os of last version update,  all buttons for navigation stopped working . is this a known problem ? 

version is professional  v.3.2.1

**Comment by vvlladd28** [comment]
Hi @eschummer01,
Can you provide a more detailed description of the problem?

**Comment by eschummer01** [comment]
hi porblem was solved by our devleoper,   changes in new version  impel,ented a different method for the navigation  we had to update all dashboards :-(

**Comment by eschummer01** [comment]
Hello

Please look into this, we are integrating watteco devices and are encountering compilation errors.

Maybe you can help understand whats wrong ?

https://github.com/thingsboard/thingsboard/issues/4689

Regards

Eric schummer
