### ISSUE TITLE
How to get historical telemetry data in custom time series widget?

### ISSUE THREAD

**Issue by RakeshG1** [thingsboard/thingsboard#4616]
**Custom Widget Creation - for historical telemetry data**

 * Generic

**Description**
Hello All, I am a newbie to ThingsBoard platform and trying to go through ThingsBoard documentation and articles. But I am unable to find a way to get specific historical telemetry data in my custom timeseries widget. If I am trying with self.ctx.defaultSubscription.data, getting only latest data value. But my goal is 'to store selected historical telemetry data into some javascript array to do some analysis'. any lead to this, will be very helpful!

**Environment**
 * OS:  Windows
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
