### ISSUE TITLE
[Bug] Thingsboard PE Cloud not updating Telemetry

### ISSUE THREAD

**Issue by Guapz** [thingsboard/thingsboard#4623]
I am using Thingsboard PE Cloud and it's working great. However when going to the dashboard, the widgets are not updating. Only on refresh, the widget is being updated. Widgets that show history data do not show any data at all.

When going to the device and looking at "Latest Telemetry", the same thing occurs. Instead of the data updating continuously, it only updates when refreshing. 

I have tried this on several browsers and operating systems, but it really is an issue of TB PE Cloud. In the Demo environment (demo.thingsboard.io), it does work and data is being updated continuously. 

Hope that this will be fixed since the dashboard is unusable at the moment with TB PE Cloud

I am using TB PE Cloud v3.3.0CLOUD

**Comment by vvlladd28** [comment]
Hi @Guapz,
Yes, there are some issues on https://cloud.thingsboard.io; this is a demo environment. 
We only guarantee stable work for https://thingsboard.cloud.

**Comment by Guapz** [comment]
Thank you for the quick response! I now see that you are right and that I had the wrong link.
