### ISSUE TITLE
[Question] Widget RPC

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#4626]
**Component**

 * Generic

**Description**
How to lock the dashboard while doing the rpc buttons action?
![image](https://user-images.githubusercontent.com/78015483/119645567-74096080-be1e-11eb-9ef6-80a4b99ab099.png)

**Environment**

 * OS:  Windows 10
 * ThingsBoard:  v.3.2.2PE
 * Browser: google chrome

**Comment by Delapouite** [comment]
Hi. Could you be more precise about your definition of "locking a dashboard" please? Thanks

**Comment by AbrahamSalvi** [comment]
Hi, i want something similar to the one in the photo, when I do an action, the back is blocked until the action is finished, so the user has the feeling that the rpc is doing something.

This is possible?

![image](https://user-images.githubusercontent.com/78015483/119793680-17b64780-bed7-11eb-99f2-c06d0e124e0b.png)

**Comment by skewty** [comment]
This seems like a basic client side web dev ask if I am understanding you correctly.
Before you call out the RPC set self.rpcInProcess = true; And when if finishes (success or error) set it to false.
Then bind enabled to !self.rpcInProcess value.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
