### ISSUE TITLE
The output msg before in of rule chain

### ISSUE THREAD

**Issue by songkemail** [thingsboard/thingsboard#4634]
**Describe the bug**
The out event produced before the in event when msg coming in the rule chain, which due to the wrong result of the rulechain.

**Your Server Environment**

* own setup
  * docker deployment 
  * ThingsBoard Version 3.1.1
  * OS Name and Version centos 7.5

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. mqtt device produce many connect event to rule chain
2. the rule chain event print the wrong order of in out msg

**Expected behavior**
the right order of in out event msg

**Screenshots**
![image](https://user-images.githubusercontent.com/4156359/119744142-f85ef080-bebd-11eb-8766-22cb5a34a72b.png)

**Comment by songkemail** [comment]
@ashvayka

**Comment by sumin-denys** [comment]
Hi @songkemail,

Based on the attached screenshot, I can conclude that ThingsBoard processes all messages in the correct order (according to the message ID). First, we see IN and then OUT with two identical message IDs, so everything works as it should.

Why are IN/OUT messages printing in the wrong order?
- When IN/OUT messages are processed, it may take a pretty small amount of time. Depending on processed time, each message has the createdTime field (in milliseconds), which is used for sorting purposes. 

Based on the information above, I assume that each of these messages has the same createdTime(e.g., 19:13:36.723 | IN and 19:13:36.723 | OUT), and when ThingsBoard sorted these messages using the createdTime field, we can observe this bug.
