### ISSUE TITLE
How can i distribute telemetry data from one device to other devices i have created

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard#4640]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
i have a real device（Name ：DeviceA）, its rule Engine name "deviceARule"。The DeviceA have  four telemetry。
For example：{
    "msg": {
        "telemetryOne": 0.23943963646888733,
        "telemetryTwo": 0.2332449108362198,
        "telemetryThree": 0.2552765905857086,
        "telemetryFour": 1042.1875
    },
    "metadata": {
        "deviceType": "deviceARule",
        "deviceName": "DeviceA",
        "ts": "1622087996680"
    },
    "msgType": "POST_TELEMETRY_REQUEST"
}
i reated to devices , deviceB and deviceC.
I want DeviceB to get TelemetryOne and TelemetryTwo.
DeviceC to get TelemetryThree and TelemetryFour.
The expected results are as follows;
DeviceB:
{
    "msg": {
        "telemetryOne": 0.23943963646888733,
        "telemetryTwo": 0.2332449108362198
    },
    "metadata": {
        "deviceType": "deviceBRule",
        "deviceName": "DeviceB",
        "ts": "1622087996680"
    },
    "msgType": "POST_TELEMETRY_REQUEST"
}
DeviceC:
{
    "msg": {        
        "telemetryThree": 0.2552765905857086,
        "telemetryFour": 1042.1875
    },
    "metadata": {
        "deviceType": "deviceCRule",
        "deviceName": "DeviceC",
        "ts": "1622087996680"
    },
    "msgType": "POST_TELEMETRY_REQUEST"
}

 But the telemetry data in the device list is nothing. For Example：

![image](https://user-images.githubusercontent.com/21196303/119798807-0d637000-bf0e-11eb-9269-4851fa54a65c.png)

**Environment**

 * OS:  centos 7.0
 * ThingsBoard: 3.2
 * Browser: chrome last

**Comment by ashaforost** [comment]
Depending on the specifics of your use case, you can find useful several transformation rule nodes: duplicate to related( /group), change originator rule node.
Please refer to the[ Transformation Nodes](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/transformation-nodes/) article for more information on the topic.

**Comment by RenCisco** [comment]
OS: centos 7.0
ThingsBoard:commumity Edition 3.2

I don't understand  your solution. I tried the 'change originator node', but it didn't work!


i collect data of Device A throught the thingsboard-gateway, The Device A has  five last telemetry (pressure,temperature,humidity,voltage,electricity).
I created two virtual devices:  B and C.
### before change：
一、device list img：
![image](https://user-images.githubusercontent.com/21196303/120420190-74fa3f00-c396-11eb-8e3b-887859772366.png)
二、device profile list img：
![image](https://user-images.githubusercontent.com/21196303/120420260-a115c000-c396-11eb-85a6-6f3844fd1d2b.png)
![image](https://user-images.githubusercontent.com/21196303/120420324-be4a8e80-c396-11eb-8f6d-6528be4f9b8b.png)
三、rule chain list img：
![image](https://user-images.githubusercontent.com/21196303/120420391-df12e400-c396-11eb-8e37-f89356dc6e21.png)
![image](https://user-images.githubusercontent.com/21196303/120420454-f356e100-c396-11eb-9d45-1607e011cf17.png)

Script Transformation Node configuration：
![image](https://user-images.githubusercontent.com/21196303/120420704-724c1980-c397-11eb-85a1-496bddd219d3.png)
B.Rulechain and C.Rulechain:
![image](https://user-images.githubusercontent.com/21196303/120420780-9d366d80-c397-11eb-841f-aaf3dfca2de0.png)

result:  deviceB or DeviceC dosen't any data in the last telemetry,But there is data in the rule chain and the OUT status is SUCCESS
![image](https://user-images.githubusercontent.com/21196303/120421432-da4f2f80-c398-11eb-8969-326e59bce44d.png)


### Issue:
How to do it ? -- device b has data in the last telemetry list

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
