### ISSUE TITLE
[Question] Why do you commit when Kafka doesn't consume any data？

### ISSUE THREAD

**Issue by formerly11** [thingsboard/thingsboard#4641]
**Component**
common->queue

 * Generic

**Description**
    When no device is active, I find that Kafka's CPU utilization is very high. 
    By looking at Kafka's log, I find that Kafka is always deleting topics：`__ comsumer-offsets_xx`, by analyzing the contents of those topics, I found that some consumers always submit offset 0. 
    Through analysis, I think submission occurs in the `org.thingsboard.server.queue.common.defaulttbqueuerequesttemplate # init` method. Is this the reason for Kafka's phenomenon.

**Environment**

 * OS:  Ubuntu 18.04.4 LTS
 * ThingsBoard: 3.2.2
 * Browser: Google Chrome 86.0.4240.75

**Comment by kien-truong** [comment]
Yes, this is quite a big issue. Even on lightly loaded cluster, Thingsboard still commits to Kafka on the average of thousands of time per seconds.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
