### ISSUE TITLE
need multiple copy and paste for widget [Feature Request]

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#4645]
Currently, only can copy one widget and paste one widget for one time, we do need multiple select, copy and paste widgets to make work efficiently. thanks

**Comment by ashaforost** [comment]
ThingsBoard doesn't provide the feature of copying several widgets, I've created a corresponding feature request in our backlog(PROD-996). In a meantime, you can use some third-party application to be able to access the history of your clipboard ( e.g. glipper for Gnome, Klipper for KDE and etc ) to be able to paste multiple objects, that you've previously copied.
