### ISSUE TITLE
[Bug] HTTP request to OAuth2 custom mapper is text/plain instead of application/json

### ISSUE THREAD

**Issue by driesva** [thingsboard/thingsboard#4647]
**Describe the bug**
When ThingsBoard calls a custom OAuth2 mapper it sends the JSON serialization of the _principal_ as text/plain. I would expect it to have Content-Type application/json

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version: 3.2.2PE
  * OS: CentOS 7.4

**To Reproduce**
Configure a custom OAuth2 mapper and inspect the request. In my case I got:
```
POST /oauth2/map HTTP/1.1
Accept: application/json, application/cbor, application/*+json
Content-Type: text/plain;charset=ISO-8859-1
Content-Length: 1066
Host: localhost:8090
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.6 (Java/11.0.9.1)
Accept-Encoding: gzip,deflate
```

**Expected behavior**
Content-Type application/json

**Additional context**
Relevant class (in CE) that makes the request is org.thingsboard.server.service.security.auth.oauth2.CustomOAuth2ClientMapper

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
