### ISSUE TITLE
[Bug] UI not showing labels (Device Profiles and API Usage tabs)

### ISSUE THREAD

**Issue by GregorR1** [thingsboard/thingsboard#4653]
**Describe the bug**
On certain Navigation Tabs the UI is not correctly displaying Labels.  For example, the device profiles tab is showing "device-profile.device-profiles" and every label on this tab is doing the same (see attached screenshots below).

**Your Server Environment**
AWS EC2
Thingsboard v3.2.2PE
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1048-aws x86_64)

**Your Client Environment**

* OS: Windows 10
* Browser: Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Thingsboard Web page
2. Sign in
3. Click on the device profiles/API usage tab
4. See issue on every label

**Expected behaviour**
The labels should appear properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/35920977/120007986-6bf22200-bfd2-11eb-839b-13f69d619782.png)
![image](https://user-images.githubusercontent.com/35920977/120008050-7ad8d480-bfd2-11eb-957d-23e9982192da.png)

**Comment by mde2017** [comment]
I got the same issue after updating ThingsBoard. Was able to resolve this by deleting the browser cache. After that the labels in the navigation were displayed properly.

**Comment by trypzz** [comment]
Hi, @GregorR1 and @mde2017 

Try to clear browser cache and reload the page.

**Comment by GregorR1** [comment]
That sorted it.  Thanks :)
