### ISSUE TITLE
[Question] Two way ssl MQTT communication

### ISSUE THREAD

**Issue by dwjbosman** [thingsboard/thingsboard#4654]
I am trying to use the "two-way-ssl-mqtt-client" example in conjunction with the 'cloud' version of Thingsboard.

    python two-way-ssl-mqtt-client.py
    Please write your ThingsBoard host or leave it blank to use default (localhost): thingsboard.cloud
    Please write path to your server public certificate or leave it blank to use default (mqttserver.pub.pem): tb-cloud-chain.pem
    Please write path to your client public certificate or leave it blank to use default (mqttclient.nopass.pem): keyStore.pem
    Connected with result code  {'session present': 0} 5 ()

the on_connect function receives parameters:
  flags = {'session present': 0}
  rc = 5 which means 5: Connection refused – not authorised

I used this to obtaine the various keys:

    wget https://thingsboard.io/docs/user-guide/resources/mqtt-over-ssl/tb-cloud-chain.pem
    
    openssl req -x509 -sha256 -nodes -days 999 -newkey rsa:2048 -keyout client.key -out client.pem -subj "/C=FR/O=TA/OU=TA/CN=thingsboard.cloud" 
    openssl pkcs12 -export -out public_private_client_key.pfx -inkey client.key -in client.pem 
    openssl pkcs12 -in public_private_client_key.pfx -out keyStore.pem -nodes

I copied the contents of client.pem (which is also contained in keyStore.pem) to the Thingsboard device credentials.  

The one-way example using tb-cloud-chain.pem using a device access token is working.

Why is is the connection refused?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket with detailed steps to reproduce if this problem still exists.
