### ISSUE TITLE
Json structured telemetry keys result in BadRequest error

### ISSUE THREAD

**Issue by holgerbrandl** [thingsboard/thingsboard#4657]
**Describe the bug**
When using json structured keys for time-series, it fails to pull them via curl, 

Timeseries key example
```
{"foo":"bar","some":"thing"}
```

**Your Server Environment**
  * ThingsBoard Version: v3.2.2
  * OS Name and Version docker with official image running on ubuntu 20.04

**Your Client Environment**
curl & swagger 

**Connectivity**
* MQTT

**To Reproduce**
1. Create a device
2. Send some telemetry with a json key (see example above)
3. Try to fetch telemetry data via swagger or curl
4. Error: `HTTP Status 400 – Bad Request`

**Expected behavior**
Since the documentation does not seem to enforce any format restrictions on telemetry keys, json keys should be supported.

**Additional context**
* I've also checked the postgres database which is used as backend. The events are correctly stored. Keys are correctly present in `ts_kv_dictionary` and `ts_kv_latest` contains the latest data. So it seems to be a problem with the query API.
* I've made sure that indent and whitespace of the json key are matched 
*  The attributes can be shown via "Show on widget" in the  UI

**Comment by LeoMorgan113** [comment]
Hi @holgerbrandl,

I investigate your problem and want to suggest you the next: use in swagger not entityId, but deviceId.
I tested it and got the latest timeseries.
![2021-06-01_15-02](https://user-images.githubusercontent.com/56256429/120320542-f85e5680-c2ea-11eb-9ac1-1a178cc771b8.png)

**Comment by holgerbrandl** [comment]
Thanks @LeoMorgan113 for the analysis. I've repeated the process, but the problem persists. It works when *not* providing any `keys`. However, it fails to work when providing my json key as `keys` argument after `entityId` (for which I have provided the deviceId).

For `getLatestTimeseries` simply omitting the `keys` argument,  and extracting the telemetry of interest could serve as simple workaround. However, for `getTimeseries` the `keys` argument is mandatory, and I can't find a way how to use this method with JSON key.

Other methods such as `getTimeseriesKeys` list the json key correctly. 

Feel welcome, if I could support the process by doing more tests/analysis on my end. I'd still hope that it could be solved by escaping the json key in some way that is not clear to me yet.

**Comment by LeoMorgan113** [comment]
The correct keys structure for `getTimeseries` is your keys separated by commas without spaces.
**`key1,key2`**


![2021-06-07_16-30](https://user-images.githubusercontent.com/56256429/121025277-a9fafd00-c7ad-11eb-9b00-a648dab88e4d.png)
![2021-06-07_16-29_1](https://user-images.githubusercontent.com/56256429/121025291-acf5ed80-c7ad-11eb-8e3d-a573b8beb122.png)

**Comment by holgerbrandl** [comment]
This is working fine, as long as the key is not a json structured description as documented above. The issue is all about having **keys that are json** itself. Key example for a time series: `{"foo":"bar","some":"thing"}`

**Comment by LeoMorgan113** [comment]
So if you get **JSON structure**, you need to convert it in **_string_** of keys, for example, with "Transformation-Script", because `getTimeseries` support only the format described before.
Then put this string in the "Rest API Call" node.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node

![2021-06-11_15-54_1](https://user-images.githubusercontent.com/56256429/121689514-5bab6e00-cacd-11eb-97b0-605fef8c554d.png)
![2021-06-11_15-54](https://user-images.githubusercontent.com/56256429/121689527-5f3ef500-cacd-11eb-8c50-a55845edf21d.png)
![2021-06-11_15-51](https://user-images.githubusercontent.com/56256429/121689529-60702200-cacd-11eb-9c32-22a102e94062.png)

**Comment by holgerbrandl** [comment]
Thanks for the worked-out example. So from what I understand, it is currently not possible to consume the swagger API with keys that contain a comma (such as my mentioned json keys). Did I read your answer correctly?

**Comment by LeoMorgan113** [comment]
Yes, for now, it can be only in format **_test1, test2_**, not key-value, like JSON format.

**Comment by escalanterj** [comment]
does anybody have a complete example of REST API call to send command? thanks!
