### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gdipaolo11111** [thingsboard/thingsboard#4658]
**Describe the bug**
Failed to connect error while I try the ESP32 sample/tutorial
*https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/

**Your Server Environment**

demo.thingsboard.io

**Your Device**
MakerHawk ESP32 LoRa SX1276 (JUST WIFI SIDE)

* Connectivity
   MQTT
  

**To Reproduce**
1. Go to 'https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/'
2. Change SSID, PASWORD and TOKEN
3. UPLOAD
4. See error:  Connecting to: demo.thingsboard.io with token '%%%%%%%%'
Failed to connect

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
