### ISSUE TITLE
Support for getting topic name at rule chain nodes to process data posted from same device on different topic differently.

### ISSUE THREAD

**Issue by ayanakshi** [thingsboard/thingsboard#4660]
**Component**
 * Rule Engine

**Description**
I have a requirement in which a device can post different structure of JSON Payloads. Since, the payload will go through Rule Node, Is there any way to get the topic name on rule chain node using which I can determine that this payload structure will come and process accordingly.

**Comment by ayanakshi** [comment]
Hi.. Please help me in this. Is there any other way by which this can be achieved.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
