### ISSUE TITLE
How to remove debug data?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#4662]
Hello everyone

Can we delete Debug data? Can we set TTL on debug data?

Everytime I open a debug event view on my server it takes for ever and I do not need old data there.

Regards

**Comment by trikimiki** [comment]
Hello!

Please check out this documentation: https://thingsboard.io/docs/user-guide/install/config/
You will find there related TTL configuration properties for Postgres and Cassandra (depending on where you store entity data). Please note that TTL will be applied for new events only, so you will still need to remove older data manually.

To delete debug event data, you will need to truncate the corresponding tables:
- Postgres: "event"
- Cassandra: "thingsboard.event" (you might want to run `nodetool clearsnapshot thingsboard` command afterward to remove this data from your disk)
To prevent unexpected issues, please always stop ThingsBoard and create the database(s) backup before making any manual changes.
