### ISSUE TITLE
Manage multiple alarms in the same node

### ISSUE THREAD

**Issue by astijon95** [thingsboard/thingsboard#4663]
**Component**
 * Rule Engine

**Description**
Hi, I'm trying to manage multiple alarms for a single device using Rule Engine. I don't want to had as many nodes as number of alarms (watch images below).
![Captura de pantalla (286)](https://user-images.githubusercontent.com/85154397/120280425-f29b4d80-c2b7-11eb-9631-c3e81bc6b5fd.png)

 Is there any way to use a single Script and Create/Cleare Alarm node to manage all the alarms?

Thanks in advance

**Comment by ashvayka** [comment]
Please provide an example of the script node. For example Zipper. Also, take a look at the device profile alarm rule examples: https://thingsboard.io/docs/user-guide/device-profiles/#alarm-rules

**Comment by astijon95** [comment]
Hi, the code of each script node is simple, just the following,

return msg.zipper== false;

All the alarms in the picture are same type of conditions. 

Thanks in advance

**Comment by angovil** [comment]
Hi,

In the device profile, under Alarm Rule section, as per the documentation it is mentioned that "Details - the alarm details template supports substitution of the telemetry and/or attribute values using ${attributeName} syntax;". However it seems this is limited to only those attribute which are part of filter condition? Is there any way to add other attributes into the alarm details section.

Thanks

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
