### ISSUE TITLE
documentation for query entity REST api

### ISSUE THREAD

**Issue by eddubeddu** [thingsboard/thingsboard#4664]
Hi,

I am working on a project to integrate with ThingsBoard using its REST APIs.
I know there's Swagger documentation available, however I can't easily work out what every endpoint does, and how to populate request payloads, because the documentation is pretty basic.

Most specifically I am trying to work out how to form valid request payloads when using the endpoints
countEntitiesByQuery (POST /api/entitiesQuery/count)
findEntityDataByQuery (POST /api/entitiesQuery/find)

Is there some documentation resource or any examples available anywhere?

**Comment by ashvayka** [comment]
This is a valid question/enhancement. We have not documented this yet. You can find the data structures examples if you browse websocket messages in Chrome network debug while browsing the complex dashboards.
