### ISSUE TITLE
[Bug] Rule Chain rest api call node - curly brackets { } in URL params error

### ISSUE THREAD

**Issue by mihaelking** [thingsboard/thingsboard#4666]
Hello,
I am having problems with Rest api call node in Rule chains. I am trying to create a POST request to server that requires data in JSON format to be in URL params. The problem is with { } curly brackets as Thingsboard thinks it's a variable. 
If I understand correctly variable in URL should only be recognised if there is a dolar sign in front of curly brackets - ${metaKeyName}. 
When I perform POST request to this example URL:
`"https://hidden_url.com/test?data=[{\"test\":\"test\"}]"`
I get the following error:
![image](https://user-images.githubusercontent.com/80819736/120334020-8ee14680-c2f0-11eb-8266-6ab46404dd18.png)

I am using script node to insert the data in URL and then I save it in metadata and forward it to rest api call node. 
Rest api call node looks as the picture below:
![image](https://user-images.githubusercontent.com/80819736/120330889-8a675e80-c2ed-11eb-8328-3be442bf5017.png)

I tried to insert data directly in URL in  with a form like example below, but got the same result:
![image](https://user-images.githubusercontent.com/80819736/120334295-d071f180-c2f0-11eb-99d4-96196f1aeeec.png)

We are using Thingsboard PE version 3.2.1

Any advice how to solve this problem?

Best regards,
Miha

**Comment by ashvayka** [comment]
See https://www.w3schools.com/tags/ref_urlencode.ASP. URLs can only be sent over the Internet using the ASCII character-set.

The 
[{\"test\":\"test\"}]
Is converted to 
%5B%7B%5C%22test%5C%22%3A%5C%22test%5C%22%7D%5D

**Comment by mihaelking** [comment]
> See https://www.w3schools.com/tags/ref_urlencode.ASP. URLs can only be sent over the Internet using the ASCII character-set.
> 
> The
> [{"test":"test"}]
> Is converted to
> %5B%7B%5C%22test%5C%22%3A%5C%22test%5C%22%7D%5D

Thank you for fast response. I am fully aware of url encoding and i am sorry I didn't mention I already tried that. With the help of Postman Mock serverb I found out that Thingsboard already coverts ASCII to HEX. 
If I enter an URL like this: 
`https://postman_url.com/test?data=%5B%7B%5C%22test%5C%22%3A%5C%22test%5C%22%7D%5D`
Thingsboard will convert % sign to %25, you can see on the bottom picture. This is causing parsing error on the REST server.
![image](https://user-images.githubusercontent.com/80819736/120359609-27cf8c00-c308-11eb-9342-7dce49bfbb24.png)

If I enter the following link (you can see I left out curly brackets {} ):
`https://postman_url.com/test?data=["test":"test"]`
I get the correct form on Postman:
![image](https://user-images.githubusercontent.com/80819736/120360319-e9869c80-c308-11eb-8b3f-ec7412fd43c3.png)

But as soon as I add the curly brackets I get an error I mentioned in the first comment.
