### ISSUE TITLE
[Bug] sorting by customerIsPublic on getTenantDeviceInfos service causes server error

### ISSUE THREAD

**Issue by eddubeddu** [thingsboard/thingsboard#4673]
**Describe the bug**
Using the [getTenantDeviceInfos](https://demo.thingsboard.io/swagger-ui.html#!/device-controller/getTenantDeviceInfosUsingGET) service, when passing parameter sortProperty = customerIsPublic an internal server error occurs.

**Your Server Environment**
* demo.thingsboard.io

**Your Client Environment**
**Desktop :**
* OS: iOS
* Browser: chrome
* Version 90.0.4430.93 (Official Build) (arm64)

**To Reproduce**
1. Go to Swagger documentation on demo org https://demo.thingsboard.io/swagger-ui.html#!/device-controller/getTenantDeviceInfosUsingGET
2. authorise the service with your bearer token
3. set sortProperty for getTenantDeviceInfos to value "customerIsPublic"
4. set any values for pageSize and Page
5. click Try it out

**Expected behavior**
A successful response with records ordered by field customerIsPublic

**Additional context**
This is the error message returned
```
{
  "status": 500,
  "message": "org.hibernate.QueryException: could not resolve property: customerIsPublic of: org.thingsboard.server.dao.model.sql.DeviceEntity [SELECT new org.thingsboard.server.dao.model.sql.DeviceInfoEntity(d, c.title, c.additionalInfo, p.name) FROM org.thingsboard.server.dao.model.sql.DeviceEntity d LEFT JOIN org.thingsboard.server.dao.model.sql.CustomerEntity c on c.id = d.customerId LEFT JOIN org.thingsboard.server.dao.model.sql.DeviceProfileEntity p on p.id = d.deviceProfileId WHERE d.tenantId = :tenantId AND LOWER(d.searchText) LIKE LOWER(CONCAT(:textSearch, '%')) order by d.customerIsPublic asc]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: customerIsPublic of: org.thingsboard.server.dao.model.sql.DeviceEntity [SELECT new org.thingsboard.server.dao.model.sql.DeviceInfoEntity(d, c.title, c.additionalInfo, p.name) FROM org.thingsboard.server.dao.model.sql.DeviceEntity d LEFT JOIN org.thingsboard.server.dao.model.sql.CustomerEntity c on c.id = d.customerId LEFT JOIN org.thingsboard.server.dao.model.sql.DeviceProfileEntity p on p.id = d.deviceProfileId WHERE d.tenantId = :tenantId AND LOWER(d.searchText) LIKE LOWER(CONCAT(:textSearch, '%')) order by d.customerIsPublic asc]",
  "errorCode": 2,
  "timestamp": "2021-06-02T10:55:52.810+00:00"
}
```

**Comment by LeoMorgan113** [comment]
Hi @eddubeddu,

You got an error because there is no such sortProperty.
To find right sortProperty name you can click on title name in table, then go to dev tools -> network -> last request
![2021-07-01_17-12](https://user-images.githubusercontent.com/56256429/124138987-d8f44e00-da8f-11eb-989e-19420fe70ab2.png)
That will be your sortProperty - 'customerTitle'
![2021-07-01_17-12_1](https://user-images.githubusercontent.com/56256429/124138993-d98ce480-da8f-11eb-8703-481eece57a4f.png)

**Comment by eddubeddu** [comment]
Thanks for the response.
Is it intended behaviour however that if I were to try and sort by that field, then the response of the API exposes the error message from the DB, which prints the SQL statement?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
