### ISSUE TITLE
[Question] Unable to create User via Rest API

### ISSUE THREAD

**Issue by samteck-etairos** [thingsboard/thingsboard#4675]
**Component**

 * Generic

**Description**
Unable to create a customer user via REST API (though able to create via UI)

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.2 (https://demo.thingsboard.io/)
 * Browser: Chrome (version-90)

API - POST /api/user{?sendActivationMail}

Body - 
{
  "additionalInfo": "string",
  "authority": "SYS_ADMIN",
  "createdTime": 0,
  "customerId": {
    "id": "string"
  },
  "email": "string",
  "firstName": "string",
  "id": {
    "id": "string"
  },
  "lastName": "string",
  "name": "string",
  "tenantId": {
    "id": "string"
  }
}

Response - 
{
  "timestamp": "2021-06-02T10:59:32.215+00:00",
  "status": 400,
  "error": "Bad Request",
  "message": "",
  "path": "/api/user"
}

Few Points:
1. Authentication is fine as I am able to run other APIs (create customer)
2. Via Web UI I am able to create the User for a customer
3. In customerId and tenantId fields in the body I am copying values from UI. But in "id" I am using a random ID
4. In swagger file (https://demo.thingsboard.io/swagger-ui.html#/) it says optional all the fields in the body. Is it so ?

**Comment by etairossamarth** [comment]
I am using the below curl command, with 4 keys in the body. But it is still giving 400 without any error message.
Do I need to give anything else in the body?

curl --location --request POST 'https://thingsboard.cloud:443/api/user?sendActivationMail=true' --header 'X-Authorization: Bearer $YOUR_JWT_TOKEN' --header 'Content-Type: application/json' --data-raw '{
  "additionalInfo": null,
  "authority": "CUSTOMER_USER",
  "customerId": {
    "id": "193e4590-c502-11eb-aa75-3166bd5a93bc"
  },
  "email": "user3@test.com"
}'

Response : 
{"timestamp":"2021-06-04T09:23:24.435+00:00","status":400,"error":"Bad Request","message":"","path":"/api/user"}

**Comment by samteck-etairos** [comment]
Closing the issue as able to create a customer user.
Sharing the API with necessary body keys.

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Authorization: Bearer [TOKEN]' -d '{
"email": "youremail@example.com" }' 'https://demo.thingsboard.io/api/user?sendActivationMail=true'​
