### ISSUE TITLE
Terrible performance with PostgreSQL

### ISSUE THREAD

**Issue by nikil511** [thingsboard/thingsboard#468]
I am running TB on a VM with 4 vCPUs and 8GB RAM using PostgreSQL as a service (Azure 50 compute units).
TB  is very slow when storing telemetry data ~100 messages per second (from single thread client)
VM and DB CPUs are both idle. Tried both ver 1.3.1 and today's snapshot (5/12/2017) - same slow performance.  Same test but with Cassandra db gives x100 better speed.

Also, after a few thousand telemetry messages TB enters a weird state where everything is working but the devices related to the telemetry can not share data (dashboards always loading) and situation requires a few minutes to recover, after the telemetry upload has been terminated.

Has anyone else tested the performance of TB with PostgreSQL ?
Could this be a JPA configuration problem ? 
Is JPA & PostgreSQL a second class citizen for TB ? - better stick to Cassandra for now ?

**Comment by MarsWarrior** [comment]
We haven't seen this problem sofar with PostgreSQL. But we are only getting about 10 messages per second, only 1/10th of your data ingress.

- Are  you using 9.6 or 10.0?
- Any idea if it is CPU or I/O bound?
- Using default PostgreSQL settings? Upping shared buffers (default settings can be very low) and cache size can make a great impact on PostgreSQL performance.

You could try timescaledb as an alternative to PostgreSQL. Does perform a lot better in the long run compared to PostgreSQL.

**Comment by hemantkamalakar** [comment]
Do we need to make any configuration changes in TB to work with TimescaleDB?

**Comment by mp-loki** [comment]
It should work out of box, since TimescaleDb requires the same postgres driver. We did not certify for for TimescaleDB specifically, but I did installation once as an exercise an it worked.

**Comment by hemantkamalakar** [comment]
Ok.
I will check and let you know.

**Comment by MarsWarrior** [comment]
For best performance (timeseries functionality TimescaleDB) you should create a hyper table.
See TimescaleDB info on github!

**Comment by m-menon** [comment]
@nikil511 was the problem solved? Because I am thinking of switching TB to PostgreSQL. If the problem is severe I can rethink my plan. Thanks.

**Comment by nikil511** [comment]
@m-menon well the "terrible" part was solved I guess using latest snapshot build from source, and improving our "gateway" software which could be causing some additional problems with bursts of data.

PSQL in our current use-cases is about x4 slower than Cassandra which is ok.
I tried to tune the pool size but there was not much improvement. I also tried timescale supertable on kv and made latests_kv a memory table (as a test) but did not see major improvement either. At least in the incoming telemetry which is our current concern and I was measuring. 

However, I still prefer the PSQL version as I can do more directly on the DB so I'm just waiting for it to mature a bit more, and plan to spend more time tuning it at some point. 

Please give it a go and share your findings! :-)

**Comment by m-menon** [comment]
@nikil511 thanks a lot for taking time to reply. Seems like you did experiment a fair bit on getting that PSQL stuff :) I've had a word with someone who is involved in the development and it seems like (at least for now), the best option would be to choose Cassandra. I was pretty reluctant as I heard that Cassandra does have some learning curve and time isn't exactly in my favor. But then again I wouldn't want a slow performance because going forward it could become worse as data increases. So with a heavy heart I just switched to Cassandra but I am thinking of setting up a test machine just to try the PSQL part - not immediately though but very soon. I sure will share my findings when I do :) I can't let go of SQL that easily yet.

**Comment by nikil511** [comment]
@m-menon 
Is there a case where your customers ask for a report  that you can not fulfill with TB dashboards?

Try to do a select - join query with tenant id or all devices related with a particular asset, on kv table in Cassandra to understand what learning curve we are talking about! 

...and then let me know, cause I failed to find an easy way. Its seems another layer is required for even simple queries (i.e. Apache spark)

**Comment by m-menon** [comment]
With NoSQL databases redundant data isn't always scorned upon. Perhaps you may want to think along those lines? For now my requirements aren't exactly complex. My worry is that say one day Cassandra snaps and I need to write stuff to pull some data out, do joins etc, then I could be in trouble if I didn't understand the database well. That would be a terrible situation. And also till I fully understand TB, I would not want to make any changes on the database side directly as that could pose problems during future upgrades. I am in a dilemma too. A not so elegant way I can think of is that another mqtt client is subscribed to some of those topics and dumps data into some sql database like MySQL, MariaDB or even a NoSQL db like MongoDB. MongoDB is quite dev friendly and plenty of ways to query that stuff. That way I could query an alternate database and run complex queries without affecting anything else. But then again the set up could get more complex and maintaining it a headache eventually.

**Comment by LeoMorgan113** [comment]
Hi @nikil511,

Is this issue still actual?

**Comment by nikil511** [comment]
4 years later? No! :-)
