### ISSUE TITLE
How do I change server attributes using rule chain ?

### ISSUE THREAD

**Issue by miniib** [thingsboard/thingsboard#4683]
So I want to change a server attribute om my device that contains coordinates for a polygon, that I want to update as my gps-sensor changes location.

How is that done ?

Cheers Alexander

**Comment by rishavpreet** [comment]
If your device is sending telemetry data then you can use script node to change change the msgType to POST_ATTRIBUTE_REQUEST and then use save attributes node to save the data.

This will update your coordinates in server attributes.

Return value of script:
```

{   
    msg: new payload,
    metadata: new metadata,
    msgType: new msgType 
}

```
For reference- https://thingsboard.io/docs/user-guide/attributes/

**Comment by miniib** [comment]
> If your device is sending telemetry data then you can use script node to change change the msgType to POST_ATTRIBUTE_REQUEST and then use save attributes node to save the data.
> 
> This will update your coordinates in server attributes.
> 
> Return value of script:
> 
> ```
> 
> {   
>     msg: new payload,
>     metadata: new metadata,
>     msgType: new msgType 
> }
> ```
> 
> For reference- https://thingsboard.io/docs/user-guide/attributes/

Thanks! But I can't seem to get it to work. Can you show me how a coding example on this might look? I dont really understand how I access the server attributes in the script?

**Comment by rishavpreet** [comment]
> > If your device is sending telemetry data then you can use script node to change change the msgType to POST_ATTRIBUTE_REQUEST and then use save attributes node to save the data.
> > This will update your coordinates in server attributes.
> > Return value of script:
> > ```
> > 
> > {   
> >     msg: new payload,
> >     metadata: new metadata,
> >     msgType: new msgType 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For reference- https://thingsboard.io/docs/user-guide/attributes/
> 
> Thanks! But I can't seem to get it to work. Can you show me how a coding example on this might look? I dont really understand how I access the server attributes in the script?

You don't need to access the server attributes if you only want to update the coordinates to their latest value.

In the msg json use the same name as the server attribute that you want to update and then use save attributes nodes to save the in database.

It will automatically save/update the coordinates in the server attributes for that device.

**Comment by rishavpreet** [comment]
> ![image](https://user-images.githubusercontent.com/3350211/137258621-e2dffa29-cca4-44c5-97ba-89c9918c65c1.png) @rishavpreet you should change 'POST_ATTRIBUTE_REQUEST' to 'POST_ATTRIBUTES_REQUEST'

Updated.

**Comment by ashaforost** [comment]
Hi @miniib 

Is your issue resolved, or do you have any further questions?
