### ISSUE TITLE
[Question] Does Thingsboard support Redis over TLS?

### ISSUE THREAD

**Issue by andreagilardoni** [thingsboard/thingsboard#4685]
**Component**
 * Generic

**Description**
I am currently deploying thingsboard on a k8s cluster using an external redis DB provided by Digitalocean. 
Redis managed by DO only supports tls connections and here comes my question: does Thingsboard support Redis over TLS? If so how do I enable it? 

I am thinking the issue is related to TLS because I don't see any documentation about setting this option and I am currently getting the following error: 
``org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool``

**Comment by arminfelder** [comment]
from reading the source code, I would say, it is not supported right now, but I would need this feature as well

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
