### ISSUE TITLE
REST API getAlarms Incorrect Model Syntax

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#4690]
Hello !
I am trying to get the device alarms through API function getAlarms

/api/alarm/{entityType}/{entityId}{?searchStatus,status,pageSize,page,textSearch,sortProperty,sortOrder,startTime,endTime,offset,fetchOriginator}

This request is working using only one status parameter like : ACTIVE_UNACK .
http://127.0.0.1:8080/api/alarm/DEVICE/f9f260e0-8519-11eb-bf83-031e63630406?status=ACTIVE_UNACK&pageSize=100&page=0&fetchOriginator=false

The error appears when I try to request multiple parameters from status like : "ACTIVE_UNACK", "ACTIVE_ACK"

Can you give me the correct syntax of the  API REQUEST command, because the example provided in the Swagger UI command getAlarms model is not working...

How can I send multiple status parameters at once like : "ACTIVE_UNACK",  "CLEARED_UNACK", "CLEARED_ACK"

Thank You !

**Environment**
* OS:  Ubuntu 20
* ThingsBoard: 3.22
* Browser: Chrome
![Untitled-1](https://user-images.githubusercontent.com/59779817/120921512-b52a2c00-c6cc-11eb-9f2e-47b3e6012c1d.jpg)

**Comment by AndrewVolosytnykhThingsboard** [comment]
Hi @lmax25, thank you for the question. You can't input several types in the field "status", but if you'd like to find alarms like ACTIVE_UNACK and CLEARED_UNACK, you can use "searchStatus" field and input UNACK there. We don't have the ability to specify 3 different statuses. Search status can be: ANY, ACTIVE, CLEARED, ACK, UNACK

**Comment by lmax25** [comment]
Hello again !
Maybe I didn't understood but on swagger page, as a model for getAlarms command 
it is written :
status (string, optional) = ['ACTIVE_UNACK', 'ACTIVE_ACK', 'CLEARED_UNACK', 'CLEARED_ACK']stringEnum:"ACTIVE_UNACK", "ACTIVE_ACK", "CLEARED_UNACK", "CLEARED_ACK"

Please tell me where is the mistake !

Thank you very much !

**Comment by AndrewVolosytnykhThingsboard** [comment]
@lmax25 it is an example of request:
![image](https://user-images.githubusercontent.com/77969531/121318480-f52f2000-c913-11eb-8d60-966df4257c41.png)

**Comment by lmax25** [comment]
Thank you very much for the answers !
It is almost clear now...
Maybe in the future versions you will add the options to search alarms for multiple statuses...

Best Regards !
