### ISSUE TITLE
[Feature Request] How can I show combination of incoming metrics on the dashboard

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#4692]
**Component**

 * Generic

**Description**
Hi, I'm planning to apply this wonderful system on my new platform.

For that I need to show the combination of incoming metrics on the dashboard such as heart rate per steps every 1 minute.
(Only on server side. Not like take new key and value from device)

However, I don't know how dashboard works like whether the data is loaded from database or thingsboard core's buffer inside(I don't know if there is) to be shown on the dashboard graph.

So I'm wondering how I can show the combination of input data on dashboard and I would be grateful if you could let me know how I could do it.

Thank you for your input.

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: latest (Community Edition)
 * Browser: chrome

**Comment by LeoMorgan113** [comment]
Hi @saviodivelo,

Thingsboard platform working by this way: device sends telemetry on platform then it can be processed in rule chain, if nessacery, save data in a database(Postgre or Casandra) and only then data can be visualized on a dashboard.

If you have any further questions please ask.
