### ISSUE TITLE
Why is the Demo Smart Metering app in cloud.thingsboard.io not working?

### ISSUE THREAD

**Issue by csann** [thingsboard/thingsboard#4700]
**Component**

 * UI

**Description**
When I look at this app (on cloud.thingsboard.io), the Measure History chart shows no data. I'm pretty sure it did at first but it doesn't any longer show anything. 

Also, what is the difference between cloud.thingsboard.io and thingsboard.cloud?

**Environment**

 * OS:  MacOS 1.4
 * ThingsBoard: version
 * Browser: Safari 14.1.1

**Comment by csann** [comment]
<img width="1210" alt="Screen Shot 2021-06-07 at 7 49 55 PM" src="https://user-images.githubusercontent.com/1936653/121105407-ad9c7d00-c7c9-11eb-9b9f-d9d41da4b9e1.png">

This is what I see. There is a red circle on the Measure History chart, no data is changing.

**Comment by devangsolutioner** [comment]
Kindly use https://thingsboard.cloud/home might be they changed url for cloud platform and once you started send data to this URL it will sure work.!!! i did also faced this issue but make sure you download all your  existing configuration from cloud.thingsboard.io
