### ISSUE TITLE
On thingsboard.cloud, how can I delete old telemetry data?

### ISSUE THREAD

**Issue by csann** [thingsboard/thingsboard#4701]
**Component**

 * Generic

**Description**
I am a new user of thingsboard.cloud. How can I delete telemetry data? I know I can delete the device. Is there any other way?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by LeoMorgan113** [comment]
Hi @csann,

You may use API Delete request to delete telemetry from a certain period:
https://thingsboard.cloud/swagger-ui.html#!/telemetry-controller/deleteEntityTimeseriesUsingDELETE

**Comment by csann** [comment]
Would you please show me an example of how to use this in the getting started example on ThingsBoard.cloud?

https://thingsboard.io/docs/paas/getting-started-guides/helloworld/?connectdevice=mqtt-linux

**Comment by LeoMorgan113** [comment]
You can read more about swagger up to this link: https://thingsboard.io/docs/reference/rest-api/

Also, you can make your Rest API request using Rule Chain https://thingsboard.io/docs/user-guide/rule-engine-2-0/re-getting-started/
and REST API CALL node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node
