### ISSUE TITLE
How can I create emulated data on thingsboard.cloud

### ISSUE THREAD

**Issue by csann** [thingsboard/thingsboard#4702]
**Component**

 * Generic

**Description**
I am in the process of creating a dashboard. I would like to create the dashboard while looking at real time emulated data. 

Is there any way to create it directly from a CSV file?

I am currently using MQTT to send data from my computer using a python script which reads data from a CSV file. This is able to send a batch of data. I could modify it to send the data in real time, but before I do that, Is there a better way?

**Environment**

 * OS:  MacOS 11.4
 * ThingsBoard: version
 * Browser: Safari 14.1.1

**Comment by trypzz** [comment]
Hi @csann,
Please, clarify, you wanted export data from CSV file to thingsboard in real-time?
Or export all data from CSV and after this sending data by python script in real-time?

**Comment by LeoMorgan113** [comment]
@csann,

For emulating data you can use 'Generator Node'(follow the article: https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#generator-node).
For example, you can add a randomizer(Math.random()) for temperature and set period for 15sec, save telemetry data and display it on the widget.
Also, you can have a Script for randomizing data, put data in the file in JSON format and then send it using MQTT(https://thingsboard.io/docs/reference/mqtt-api/#publish-attribute-update-to-the-server).

Old data can be deleted directly from a database or with the REST API Request(https://thingsboard.io/docs/reference/rest-api/) in the Rule Chain or using Swagger
![2021-09-30_17-08](https://user-images.githubusercontent.com/56256429/135471061-106d1c1b-8303-438e-8de2-9ae93e63bac2.png)
.
