### ISSUE TITLE
Docker Containers Bug [Bug] 

### ISSUE THREAD

**Issue by irdet2** [thingsboard/thingsboard#4703]
**Describe the bug**
Creating new ThingsBoard installation using Docker containers and add a device. I can send telemetry data via API without a problem. Deleting the containers *WITHOUT* deleting their respective volumes (so to keep the data) and re-creating them brakes API since no more telemetry data can be send via API. Even if I create a new device is no longer working

**Your Server Environment**

* own setup
  * Docker Deployment Version 20.10.7, build f0df350
  * ThingsBoard Version 3.2.2
  * CentOS 8 release 8.4.2105

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: ALL
* Version: Latest for all 

**Your Device**

* Connectivity
  * HTTP

**To Reproduce**
1. Create a new set of containers using docker-compose
2. Create a device and make it public
3. Send telemetry data using API and "curl" command from any computer
4. Data are shown
5. Drop containers (but *KEEP* their data) which is analogue to "docker-compose down"
6. Bring another set of containers up using the previous data, analogue to "docker-compose up"
7. You are no longer able to send telemetry data via API

**Expected behavior**
Since the data of the containers are kept it was expected to be able to send new telemetry data to the device. Additionally even new devices cannot accept telemetry data via API calls

**Comment by toni-hameenniemi** [comment]
It might be related to kafka broker id. Try setting a hardcoded id for your kafka(s)? KAFKA_BROKER_ID environment variable, set it to some number that persists even if you re-create the containers.

**Comment by irdet2** [comment]
Hi!

@tonihW : Thanks for pointing me to the correct direction!

From my tests I have found the following: 

1) In the initial container build $KAFKA_BROKER_ID is set to [1001] since it's the first available after the $KAFKA_RESERVED_BROKER_MAX_ID which is by default [1000], if not set otherwise.

2) Terminating and re-launching containers probably sees [1001] as used and gets another one (haven't verified if it's the next one or a random one but that doesn't matter here).
This has as a result the problem described previously.

My solution to this problem was the addition of the following two lines in my docker-compose YML file under the "environment" of "kafka" service:

```
      KAFKA_BROKER_ID: 1001
      KAFKA_RESERVED_BROKER_MAX_ID: 1002
```

The question now is : Shouldn't this be transferred to [Installation Documentation](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka) and change it to include at least something like:

`      KAFKA_BROKER_ID: 1`

or to any number below [1000] in order for the first spawn and subsequent ones to use that one? If the first spawn for $KAFKA_BROKER_ID is explicitly set and is below [1000] then there is no reason to alter the $KAFKA_RESERVED_BROKER_MAX_ID since the $KAFKA_BROKER_ID will always be explicitly set in the future.

Inserting the above in the  [Installation Documentation](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka) I believe resolves this bug.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
