### ISSUE TITLE
modifying existing fields for test on Thingsboard

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#471]
I have question here, I’m trying to modifying the user level data’s like adding one more fields in user profile.  but I'm getting **Error Undefined Cloumn name (variable name).**
So where I need to handle the adding, fetching data and set/get data in database ?. how the Java side reading the data and returning the data to user. what are the file I need to use?. Where the file is appear in thingsboard folder?. Thanks.

**Comment by mp-loki** [comment]
@srimathselva you need to add columns to the tables in schema.cql or schema.sql (regarding which database do you use), and then re-create DB in dev environment (or do alter table). After that you can change the dao layer.

**Comment by srimathselva** [comment]
Thanks @mp-loki . I have added field in following directory database : **Thingsboard/dao/src/main/resources/cassandra/schema.cql**  file  . Can you tell me how to recreate DB in dev environment. is there any steps to do that.  I’m using Ubuntu 16.0.4 machine. and **how to check Java logs when UI(web application) is running ?.**

**Comment by mp-loki** [comment]
@srimathselva it depends on how and where you are running ThingsBoard. there are install_dev_db.sh and .bat scripts that re-create DB schema from scratch. You need to drop existing schema and create an empty one before running that script. If you are using HSQLDB you need to delete /tmp/thingsboardDB* files. 
Normally =, the log file is in /varlog/thingsboard.log. On Windows the paths provided will vary correspondingly. Please check logback.xml for logging config

**Comment by amit-flpl** [comment]
@mp-loki do you know where is the thingsboard DB is created by default? i need to access it, want to check if i can take backup and restore it.

**Comment by mp-loki** [comment]
If you are using HSQLDB, the default config is:
`${SQL_DATA_FOLDER:/tmp}/thingsboardDb`
If $SQL_DATA_FOLDER is not defined, the database files by default will be placed in /tmp dir or C:\tmp\ on Windows

**Comment by amit-flpl** [comment]
![ss](https://user-images.githubusercontent.com/40464496/41975660-fe52b58e-7a38-11e8-88ef-bf144e0b5e09.PNG)

@mp-loki 
Here is the screenshot. On which file i can fire queries??? I am using ubuntu.
 $SQL_DATA_FOLDER is not defined, whenever is echo it nothing is displayed.

**Comment by mp-loki** [comment]
Your data is in thingsboardDb.script file. You can google for the corresponding HSQLDB query tool.
>$SQL_DATA_FOLDER is not defined

That's the point, if you want to redefine the default location (/tmp) you can change it in the yaml config file or set $SQL_DATA_FOLDER env variable yourself.

**Comment by amit-flpl** [comment]
Thanks a lot @mp-loki ! You have helped me a lot.
Can you please help me with these issues? Please! Have been searching solution from a month now!
[](https://stackoverflow.com/questions/51039646/thingsboard-failed-to-start-application-startup-failed-on-ubuntu)
[](https://stackoverflow.com/questions/50771876/thingsboard-service-fails-to-start-up)

If thingsboard fails again, can i replace the DB.script file and will everything be restored? Or I will have do proper process of backup and restore of DB?

**Comment by Karabiy** [comment]
please, specify whether the issue persists
