### ISSUE TITLE
ruleEngine slow.

### ISSUE THREAD

**Issue by ccwxl** [thingsboard/thingsboard#4713]
**Component**

 * Rule Engine
 
**Description**
hi I use thingsboard to deploy a single instance (monolith). rabbitmq. The number of messages per second to the rule engine is about 400/s. The root rule engine will have a message type switch forwarded to 5 rule chains (each message of the root engine will be 5 messages are generated and forwarded to the queue). I found that tb_rule_engine.main queue consumption is particularly slow. But when it stops for a while, consumption will increase. I locate DefaultTbRuleEngineConsumerService.

  if (!ctx.await(configuration.getPackProcessingTimeout(), TimeUnit.MILLISECONDS)) {
// timeout = true;
//}
Will wait to increase the delay. How can I optimize?

**Environment**

 * OS:  mac_os
 * ThingsBoard: 3.2.2

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
