### ISSUE TITLE
[Question] How to move to a dynamic dashboard state

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4714]
**Component**
 * UI

**Description**
I have a dashboard with three devices each device has it own devices that it contains. I have the three main devices in a table, what I want to do is when clicking on the table row to go to this device dashboard state that show more details about this device. The pictures below show how I want it to be displayed.

![devices_table](https://user-images.githubusercontent.com/31441724/121463847-74c3fa00-c9bb-11eb-9163-1423b27af8aa.png)

I know that I can create a dashboard state like this `${entityName}`. All the three devices have the same device profile but each device have different number of devices that it contains.

The two following pictures display different devices:
![device2_dashboard_view](https://user-images.githubusercontent.com/31441724/121465726-d76ac500-c9be-11eb-9d67-95797f8af0f0.png)
![device1_dashboard_overview](https://user-images.githubusercontent.com/31441724/121465755-dfc30000-c9be-11eb-9055-ae7143e01aea.png)

The big main gauges displays the grade of the device I clicked on and the smaller gauges are all the devices that the main one contains. With the big gauges I used `entity alias` with filter type of `entity from dashboard state` but for the rest of the gauges I did not know what entity alias to use so it will be generic. The two different dashboard in the images created manually so there was a lot of tedious work to create somewhat the same dashboard state.

I know that if I display the contained devices in a table instead of gauges it will be possible but I want the display to have gauges. The number of gauges will vary from device to device.
I think that I need to create an entity alias that will fit this but I do not know which and how to.

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2 CE

**Comment by LeoMorgan113** [comment]
Hi @snir99,

Unfortunately, there is no possibility to make a dynamic dashboard state for a different number of widgets, you need to create states manually.
