### ISSUE TITLE
[Question] Forward specific telemetry fields to specific assets?

### ISSUE THREAD

**Issue by Marco-Ct** [thingsboard/thingsboard#4716]
**Component**

 * UI
 * Rule Engine
 * Generic

**Description**
Let's say i have a device which collects temperatures from differents rooms: E.g:
central_device has telemetry: temp_kitchen, temp_bathroom , temp_diningroom

I have three Assets: kitchen. bathroom, diningroom.  

I want the device (central_device) to forward the specific telemetry fields to the corresponding asset. Meaning temp_kitchen should go to the asset kitchen, temp_bathroom to the asset bathroom and so on... 

Is that possible? If it is, any hint,direction how this can be done would be appreciated. 
Thank you.

**Comment by JacksonBowe** [comment]
Use relations and a rule chain.

Select your asset **Kitchen**. Navigate to the relations tab and add something like this
![image](https://user-images.githubusercontent.com/26427343/122839437-5f47bc00-d33b-11eb-8b95-a3f41de309fa.png)

Set it as To/From whichever makes more sense to you. **Be consistent.**

Now your **Kitchen** asset will _contain_ your device **temp_kitchen**

Now create a rule chain, something like this
![image](https://user-images.githubusercontent.com/26427343/122839851-34aa3300-d33c-11eb-87f3-a3c45c6b1128.png)

Transformation node 
![image](https://user-images.githubusercontent.com/26427343/122839908-54415b80-d33c-11eb-955a-01e6b9d42c54.png)

When your devices posts temperature it will be duplicated to your asset.
This is a rough guide on one method to achieve what you want. You will have to play around with some of these settings like direction etc but once they are correct it will work. I've done it in the past but ended up removing it. It doesn't allow for very much expandability.

**Comment by Marco-Ct** [comment]
> Use relations and a rule chain.
> 
> Select your asset **Kitchen**. Navigate to the relations tab and add something like this
> ![image](https://user-images.githubusercontent.com/26427343/122839437-5f47bc00-d33b-11eb-8b95-a3f41de309fa.png)
> 
> Set it as To/From whichever makes more sense to you. **Be consistent.**
> 
> Now your **Kitchen** asset will _contain_ your device **temp_kitchen**
> 
> Now create a rule chain, something like this
> ![image](https://user-images.githubusercontent.com/26427343/122839851-34aa3300-d33c-11eb-87f3-a3c45c6b1128.png)
> 
> Transformation node
> ![image](https://user-images.githubusercontent.com/26427343/122839908-54415b80-d33c-11eb-955a-01e6b9d42c54.png)
> 
> When your devices posts temperature it will be duplicated to your asset.
> This is a rough guide on one method to achieve what you want. You will have to play around with some of these settings like direction etc but once they are correct it will work. I've done it in the past but ended up removing it. It doesn't allow for very much expandability.


Hi thanks for your answer. You descriped the proccess when having multiple devices (device_kitchen, device_bathroom,device_diningroom) and multiple asset ( kitchen, bathroom, diningroom). But i only have **one** device with  multiple telemetry ( telemetry_bathroom, telemetry_diningroom, telemetriy_kitchen) and i want to split the telemtry of this single device to different assets: telemtry_bathroom to the asset bathroom, telemetry_diningroom to the asset diningroom and telemetry_kitchen to the asset kitchen. 

Hope it is understandable what i am trying to achieve. 
Best regards 
Marco

**Comment by vortexalex** [comment]
Follow these steps:

1) for each asset, create one relation between the asset and the device e.g.:
      - Kitchen asset related to the device, with relation type name 'Kitchen' (or whatever name you want )
      - Bathroom asset related to the device with relation type name 'Bathroom'
 2) create a rule chain where:
      a) identify your particular multi-telemetry device with a Filter Switch (this is optional depending on your overall scenario)
      b) split the message coming from device creating a new msg body for every asset, with only the telemetry of interest (Transformation scripts),
      c) Change the Originator specifying the above qualifying relation (of course you cannot have more than one asset with that relation type to make it working)

![image](https://user-images.githubusercontent.com/5671229/123446131-dbaafb00-d5d8-11eb-8130-42ee8bdd1aed.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
