### ISSUE TITLE
Can't find "Copy Access Token" under Thingsboard PE 3.2.2

### ISSUE THREAD

**Issue by BaerSy** [thingsboard/thingsboard#4720]
**Component**

 * UI
 * Generic

**Description**
After create a device, we can't find button of "Copy Access Token" in the Device Profiles, see attached.

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: PE 3.2.2
 * Browser: [Chrome]
![accessToken](https://user-images.githubusercontent.com/27965673/121615547-25b7ac80-ca2f-11eb-8c5c-055a6bb7feb6.PNG)

**Comment by mde2017** [comment]
Hi @BaerSy,

copy Access token is only available for Devices not Device Profiles:

![image](https://user-images.githubusercontent.com/25298332/121677481-365f3580-cab6-11eb-9758-d8155e039b1a.png)
