### ISSUE TITLE
Protocol Buffers + base64 encoding

### ISSUE THREAD

**Issue by marcolg88** [thingsboard/thingsboard#4723]
Hello,
i have two questions.

I have devices that transmit over MQTT using Protocol Buffers encoding. I'd like them to connect to ThingsBoard cloud. However, these devices encode the protocol buffer binary payload in a base64 string before sending it out as MQTT payload. Is there a way to tell ThingsBoard that the incoming Protocol Buffer payload is base64 encoded?

Thank you!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
