### ISSUE TITLE
[Feature Request] Add support for Redis Sentinel

### ISSUE THREAD

**Issue by kien-truong** [thingsboard/thingsboard#4728]
Redis Sentinel is the one of the official way of deploying Redis, providing H/A capability while requiring less servers (1 primary + 2 replicas) than Redis Cluster (3 primaries + 3 replicas). In addition, Redis Sentinel is basically a regular primary + replicas setup with automatic failover, so it does not have any restrictions of Redis cluster. As a result, many people prefer Redis Sentinel over Redis Cluster.

Thingsboard currently supports Redis Standalone or Cluster, but not Redis Sentinel, it would be great if Redis Sentinel is also supported.

**Comment by LeoMorgan113** [comment]
Hi @kien-truong,

I've added your appeal to our backlog, it will be review by our developers and they decide if this is reasonable to support it.
