### ISSUE TITLE
build ui-ngx fail

### ISSUE THREAD

**Issue by Miki-byte-1024** [thingsboard/thingsboard#4729]
**Component**

 * UI
 * Installation

**Description**
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:install-node-and-yarn (install node and npm) on project ui-ngx: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz: Connect to github.com:443 [github.com/192.30.253.112] failed: Connection timed out: connect -> [Help 1]

**Environment**

 * OS:windows10
 * ThingsBoard: 3.2.2version
 * Browser:  Google Chrome  90.0.4430.212

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
