### ISSUE TITLE
[Question] Dynamic Attribute Display

### ISSUE THREAD

**Issue by Jayelzibub** [thingsboard/thingsboard#4730]
**Component**
 * Generic

**Description**
I have many devices that have attributes with the key prefix "part" and an integer value.  For example "part-542157:10" or "part-454784:20" etc.  These attribute keys are dynamic and will be added/deleted over time.  

I want to display in a dashboard only the device attributes with the prefix "part".  How can I do this?

**Comment by LeoMorgan113** [comment]
Hi @Jayelzibub,

You can add a filter for dashboard based on the 'Attribute' key type.
Key name - the name of your attribute.
An example,
![2021-06-17_13-56](https://user-images.githubusercontent.com/56256429/122384022-fc89a580-cf73-11eb-81d4-361c72ac697d.png)
![2021-06-17_13-57](https://user-images.githubusercontent.com/56256429/122384031-feebff80-cf73-11eb-808b-81cf6cf9ab0e.png)

**Comment by ChantsovaEkaterina** [comment]
Hello, @Jayelzibub 
If I understand correctly, what you would like to achieve, you can't subscribe dynamically to attributes containing particular patterns in the key name by using default widgets functionality. This could be performed only by a custom widget, which will fetch all keys available, filter them by a condition specified, and only then create a subscription on a list of filtered attributes.
