### ISSUE TITLE
Getting NO_ACTIVE_CONNECTION Error while using RPC call request and TB Gateway

### ISSUE THREAD

**Issue by itsoli91** [thingsboard/thingsboard#4734]
**Component**

 * Rule Engine

**Description**
I'm using RPC call request node to send RPC calls to my device which is thermostat. Sometime it works fine and sometimes I get error below. What's Wrong ? I also added `inactivityTimeout` server-side attr to device for 15 days but still get this error.

```
java.lang.RuntimeException: NO_ACTIVE_CONNECTION
	at org.thingsboard.rule.engine.rpc.TbSendRPCRequestNode.lambda$onMsg$0(TbSendRPCRequestNode.java:134)
	at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.lambda$sendRpcRequestToDevice$0(DefaultTbRuleEngineRpcService.java:125)
	at org.thingsboard.server.service.rpc.DefaultTbRuleEngineRpcService.lambda$processRpcResponseFromDevice$1(DefaultTbRuleEngineRpcService.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Transformation Script :

```
var msg = {
    method: metadata.cs_location + "/" + metadata.originatorName + "/ThermostatMode/set",
    params: 3
};
metadata.oneway = true;
return {
    msg: msg,
    metadata: metadata,
    msgType: msgType
};
```

Gateway mqtt.json

```
{
  "broker": {
    "name": "Default Local Broker",
    "host": "mosquitto",
    "port": 1883,
    "clientId": "ThingsBoard_gateway",
    "security": {
      "type": "basic",
      "username": "xx",
      "password": "xx"
    }
  },
  "mapping": [// my mappings ],
  "connectRequests": [
    {
      "topicFilter": "xx/Building/+/+/nodeinfo",
      "deviceNameJsonExpression": "${name}"
    }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": ".*",
      "requestTopicExpression": "xx/${methodName}",
      "valueExpression": "${params}"
    }
  ],
  "disconnectRequests": [],
  "attributeUpdates": []
}
```

**Environment**

 * OS:  Linux Ubuntu
 * ThingsBoard: latest

**Comment by IoTThinks** [comment]
I seem to hit the same thing via Gateway MQTT API in ThingsBoard 3.2.2 every 10 minutes.
ThingsBoard v2.5.6 works fine for me.

**Comment by IoTThinks** [comment]
I found this one was new in TB v3.2.2
![image](https://user-images.githubusercontent.com/29994971/124390733-1ddde600-dd17-11eb-9aa5-298dda060a9d.png)

Device State service uses a global configuration parameter for inactivity timeout. This parameter is defined in thingsboard.yml (state.defaultInactivityTimeoutInSec) and by default it is set to 10 seconds. **A user can overwrite this parameter for an individual device by setting the “inactivityTimeout” server-side attribute (value is set in milliseconds).**

Device State service uses a global configuration parameter to detect inactivity events. This parameter is defined in thingsboard.yml (state.defaultStateCheckIntervalInSec) and by default it is set to 10 seconds.

There is no “inactivityTimeout” server-side attribute
=> This mean no timeout?
![image](https://user-images.githubusercontent.com/29994971/124390778-44038600-dd17-11eb-90f1-ca40b409d5fa.png)

**Comment by IoTThinks** [comment]
In thingsboard.yml of ThingsBoard 3.2.2, the default should be 600s and 60s instead of 10s and 10s in the documentation?

![image](https://user-images.githubusercontent.com/29994971/124390970-5f22c580-dd18-11eb-9cbf-d7793ae9469c.png)
