### ISSUE TITLE
Unable to start embedded Tomcat

### ISSUE THREAD

**Issue by jkxqj** [thingsboard/thingsboard#474]
I wanna run thingsboard on my ubuntu 16.04. I use Intellij Idea,java8,maven. I had succeed in run maven clean and install .But when I  run ThingsboardServerApplication.main()  ,the errors happened: Unable to start embedded Tomcat... detail logs on  https://pastebin.com/L00NQD0D

could you help me?

**Comment by jkxqj** [comment]
@ouertani @bhtak @dyosick @Shpigor @eykamp could you help me?

**Comment by mp-loki** [comment]
@jkxqj in development environment you need to un install_dev_db.sh script. it is described in [Contribution Guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)
