### ISSUE TITLE
 integration from TheThingsNetwork

### ISSUE THREAD

**Issue by Inrebusillis** [thingsboard/thingsboard#4741]
Good Morning,

We are using Thingsboard Professional edition and we notice that when we add a fourth integration the oldest one stop to work and only the newest three are keep working.

![image](https://user-images.githubusercontent.com/85984234/122170378-cae2e280-ce7e-11eb-9dc0-a7f3a2a4f968.png)

Is there any limit in the number of integration you can pull from TheThingStack/and ThethingsIndustries?
Thankyou for the attention

**Comment by LeoMorgan113** [comment]
Hi @Inrebusillis,

We don't have any limit on the number of integration, so it cannot cause the problem.
Maybe you could provide more information?

**Comment by Inrebusillis** [comment]
Solved.
There is a limit of 3 applications during the test phase from TheThingsNetwork.
And the system (TTN) discard the older.
Thanks

**Comment by Inrebusillis** [comment]
Solved.
There is a limit of 3 applications during the test phase from TheThingsNetwork.
And the system (TTN) discard the older.
Thanks
