### ISSUE TITLE
[Feature Request] Add RTL layout for the RTL languages 

### ISSUE THREAD

**Issue by vanenshi** [thingsboard/thingsboard#4742]
It would be greate if you add a rtl layout for the rtl languages like `arabic` and `farsi`. we can add a `direction` attribute to the localization json files to determined the `direction` of that language.

can you provide some information about how to detecting the language change in your UI? I am interesting in doing this myself

**Comment by Ultrazombie** [comment]
This is already in our backlog, thank you. We're closing this ticket to avoid duplication. Please feel free to reach out if you have any further questions.
