### ISSUE TITLE
ThingsBoard 1.3.1 unusable on iPad and iPhone (responsiveness problem)

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#475]
We have serious problems with using TB on anything but a computer.

As you can see from the screenshots below, widgets are almost unusable or fully unusable on smaller devices. 

**Example 1: widget list on iPad Landscape. Small but doable.**
![ipad landscape 2017-12-10 at 20 12 53](https://user-images.githubusercontent.com/1220775/33826775-60086b12-de66-11e7-9726-871890e5bf16.jpg)

**Example 2: Same widget list on iPad Portrait. Unreadable graphs.**
![ipad portrait 2017-12-10 at 20 13 24](https://user-images.githubusercontent.com/1220775/33826777-62b03aa2-de66-11e7-9f0b-1cb618c7f6e7.jpg)

**Example 3: Newly created dashboard on iPhone Plus Portrait. Completely unreadable!**
![iphone portrait 2017-12-11 at 10 58 35](https://user-images.githubusercontent.com/1220775/33826781-64493dd2-de66-11e7-9e68-9c96ca6c60ab.jpg)

Is there any CSS or something to correct this?
Or is this already fixed in the 1.4.0 snapshot?

**Comment by MarsWarrior** [comment]
Ok. Checked the latest 1.4.0 snapshot.

The problems with the iPhone are solved. Graphs are displayed nicely.

However: on the iPad the problem persists. It is much better, but it seems the iPad tries to fit all widget rows on the screen. So displaying 2 rows / 2 columns is ok, but adding a third row creates the same problem as with 1.3.1: unusable graphs!

**Comment by yefimov-andrey** [comment]
Did this issue occur in Safari or some other browser?
