### ISSUE TITLE
Thingsboard Device Provisioning : How to create new devices in a specified device group via API?[Question] your title here

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#4750]
As I am going through the documentation regarding "Device Provision" & "Bulk Provision" in Thingsboard, I came to know that the devices can be provisioned via following API,

`curl -v -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{"deviceName":"*<name>*","provisionDeviceKey":"*<key>*","provisionDeviceSecret":"*<secret_key>*"}" "https://thingsboard.cloud/api/v1/provision"`
The above command will create a new device under default device group ("All" device group). How can we make this API to create a new device under specified Device Group with the help of "Device Group" entity id?

Please provide suggestions.

Thank you.

**Comment by JacksonBowe** [comment]
Unless you are dead-set on using the API to do this, I can show you a simple solution using a rule chain which I have implemented off my **Root** rule chain.

Looks like this:
![image](https://user-images.githubusercontent.com/26427343/122697601-fef84200-d288-11eb-9c30-739be2aa9a95.png)

Script Node:
![image](https://user-images.githubusercontent.com/26427343/122697730-51396300-d289-11eb-9ebb-1c7f5ea7f0ac.png)

Add to Group Node:
![image](https://user-images.githubusercontent.com/26427343/122697783-60b8ac00-d289-11eb-9dc1-5b88c4b53b48.png)

It's really simple. Any event that gets processed by the rule chain gets routed into here. If the metadata contains a field **deviceType,** then it uses that to create a group for it. This means that if I create a new deviceType, it auto-creates a group for that type once the device posts.

Alternatively, if you have very strict groups, you can have a similar rule chain and immediately after provisioning a device post an attribute. Something like "group":"thermostats" and have the above rule chain check for that message field specifically then process accordingly.

Sorry if this is not helpful to your API issue, but maybe someone else will find it useful!

**Comment by bhimashankarP** [comment]
Thank you very much. I know it's going to work for now.
