### ISSUE TITLE
Timeseries data values Grouping Multiple devices on one output?

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#476]
Please, there are solutions for that,
Thank you

**Comment by ashvayka** [comment]
Please provide more details to your request.

**Comment by kimoudev** [comment]
Timeseries data values API below
`http (s): // host: port / api / plugins / telemetry / entityType {} / {} entityId / values / timeseries keys = key1, key2, key3?`

My case is that I use Counting and tracking people sensors.
If I have 2 or more sensors in the same shop
and I would like to have the following value SUM:
- groupId: 1
- CompanyId: 003
- sensor 1 enters value: 2
- sensor 2 Enters value: 3

if i would like for example
Filter by Param [groupId or CompanyId]

and finally get
Outpout {enters: 5}

Please, can you give me some orientation

**Comment by kimoudev** [comment]
After a good reading,
I think we can group the values of the same Zone's divices with this Example
https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/
A little complex for me is that for each zone it is necessary to send attribut and telemetry data  respect to the device Token ...
which means to me several sending  for each device created.
The scheme that I will find more advantageous is a combination of the gateway and kafka, spark. Thus the devices and attributes are generated automatically.
And spark aggregation for group values of the same Zone's divices in asset
Thank you 
@ashvayka

**Comment by kimoudev** [comment]
@ashvayka @vparomskiy
