### ISSUE TITLE
[Bug] Access Forbidden (sysadmin)

### ISSUE THREAD

**Issue by limchiasyan** [thingsboard/thingsboard#4765]
I recently updated to ThingsBoard CE v3.2.2.

- I accessed the server from Windows 10 via Chrome and Edge browsers within **local network**.
- When I signed in as **sysadmin** and go to the **Profile** page, both gave me the **Access Forbidden** alert.
- I am able to cancel them (2 times) and continue to edit the profile.
- Normal for **tenant** and **customer** accounts.

I have tested the installation:
1. Using Ubuntu Server 20.04.2 LTS
2. Using Docker (thingsboard/tb)

**Screenshots**
![image](https://user-images.githubusercontent.com/64771965/122643587-2b09ab00-d143-11eb-8244-b71081b6551c.png)

**Comment by vvlladd28** [comment]
Hi @limchiasyan,
Thank you for your report. This issue has fixed in the master branch (#4318).  
You can get fix used build from source code or wait for the release.
