### ISSUE TITLE
[Question] 5 servers (16 cores, 32G), how many rule chains are supported? Is 1000 pieces okay?

### ISSUE THREAD

**Issue by qzzhujixue** [thingsboard/thingsboard#4768]
5 servers (16 cores, 32G), how many rule chains are supported? Is 1000 pieces okay?

**Comment by qzzhujixue** [comment]
I only know that it can support many, many devices, but I am not sure about the number of supported regular chains. Is there not too many regular chains? Too many will affect performance

**Comment by qzzhujixue** [comment]
I only know that it can support many, many devices, but I am not sure about the number of supported rule chains. Is there not too many rule chains? Too many will affect performance?

**Comment by ashvayka** [comment]
It is important to understand which rule nodes are used in those rule chains. Filter, Transformation, and Action nodes are very cheap (10000s are ok). Enrichment nodes are cheap but may consume some memory to cache the values. External nodes may consume some threads. Also, we try to reuse thread pools whenever possible, some external node libraries do not allow to use shared thread pools. Azure IoT Hub and RabbitMQ nodes are probably the most expensive from the resource point of view.

**Comment by qzzhujixue** [comment]
> It is important to understand which rule nodes are used in those rule chains. Filter, Transformation, and Action nodes are very cheap (10000s are ok). Enrichment nodes are cheap but may consume some memory to cache the values. External nodes may consume some threads. Also, we try to reuse thread pools whenever possible, some external node libraries do not allow to use shared thread pools. Azure IoT Hub and RabbitMQ nodes are probably the most expensive from the resource point of view.

okay, thank you

**Comment by qzzhujixue** [comment]
> It is important to understand which rule nodes are used in those rule chains. Filter, Transformation, and Action nodes are very cheap (10000s are ok). Enrichment nodes are cheap but may consume some memory to cache the values. External nodes may consume some threads. Also, we try to reuse thread pools whenever possible, some external node libraries do not allow to use shared thread pools. Azure IoT Hub and RabbitMQ nodes are probably the most expensive from the resource point of view.

Hello, similar to Kafka and rabbitmq, do they use long connections and then keep occupying threads? In other words, if I have 1000 rule chains and the final output is all kafka, what will happen?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
