### ISSUE TITLE
[Bug] Cannot start thingsboard after upgrading from 3.0.1 to 3.2.2. Unsatisfied dependency expressed through field 'timeseriesLatestDao'

### ISSUE THREAD

**Issue by btabuenca** [thingsboard/thingsboard#4774]
**Describe the bug**
Cannot start thingsboard after upgrading from 3.0.1 to 3.2.2. Error creating bean with name 'baseTimeseriesService': Unsatisfied dependency expressed through field 'timeseriesLatestDao'

**Your Server Environment**
  * local infrastructure or docker deployment
  * ThingsBoard Version :V3.2.2
  * OS Name and Version :Centos7

**To Reproduce**
1.  systemctl start thingsboard
2. See error

**Expected behavior**
Thingsboard should start and run

**Additional context**
`2021-06-22 19:30:24,251 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory]: Factory method 'tomcatServletWebServerFactory' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'httpTransportContext': Unsatisfied dependency expressed through field 'transportService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultTransportService' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/transport-api-3.2.2.jar!/org/thingsboard/server/common/transport/service/DefaultTransportService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tbCoreQueueProducerProvider' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-3.2.2.jar!/org/thingsboard/server/queue/provider/TbCoreQueueProducerProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'inMemoryMonolithQueueFactory' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-3.2.2.jar!/org/thingsboard/server/queue/provider/InMemoryMonolithQueueFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hashPartitionService' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-3.2.2.jar!/org/thingsboard/server/queue/discovery/HashPartitionService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultTenantRoutingInfoService' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/queue/DefaultTenantRoutingInfoService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantServiceImpl': Unsatisfied dependency expressed through field 'apiUsageStateService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiUsageStateServiceImpl' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/dao-3.2.2.jar!/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseTimeseriesService': Unsatisfied dependency expressed through field 'timeseriesLatestDao'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesLatestDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2021-06-22 19:30:24,255 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2021-06-22 19:30:24,259 [sql-queue-0-ts-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2021-06-22 19:30:24,259 [sql-queue-1-ts-4-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2021-06-22 19:30:24,259 [sql-queue-2-ts-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2021-06-22 19:30:24,271 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2021-06-22 19:30:24,290 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2021-06-22 19:30:24,337 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-22 19:30:25,689 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter -

***************************
APPLICATION FAILED TO START
***************************

Description:

**Field timeseriesLatestDao in org.thingsboard.server.dao.timeseries.BaseTimeseriesService required a bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesLatestDao' that could not be found.**

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesLatestDao' in your configuration.`

**Comment by btabuenca** [comment]
In case it helps, I get a similar error when installing demo as suggested in Step 6  here [https://thingsboard.io/docs/user-guide/install/rhel/?rhelThingsboardDatabase=postgresql](https://thingsboard.io/docs/user-guide/install/rhel/?rhelThingsboardDatabase=postgresql)

`[sbc@iaas92-46 ~]$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
[sudo] password for sbc: 
[0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/log/thingsboard/gc.log instead.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
 ===================================================
 :: ThingsBoard ::       (v3.2.2)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'psqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRuleChainService': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'entityService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseEntityService': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantServiceImpl': Unsatisfied dependency expressed through field 'apiUsageStateService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiUsageStateServiceImpl' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/dao-3.2.2.jar!/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseTimeseriesService': Unsatisfied dependency expressed through field 'timeseriesLatestDao'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesLatestDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
ThingsBoard installation failed!`

**Comment by AndrewVolosytnykhThingsboard** [comment]
@btabuenca hi! Thanks for your comment! Can you please specify steps you've done to upgrade Thingsboard from 3.0.1 to 3.2.2 ?

**Comment by btabuenca** [comment]
> @btabuenca hi! Thanks for your comment! Can you please specify steps you've done to upgrade Thingsboard from 3.0.1 to 3.2.2 ?

Dear @AndrewVolosytnykhThingsboard , thanks for your support!
I have strictly followed the steps described here [https://thingsboard.io/docs/user-guide/install/rhel/](https://thingsboard.io/docs/user-guide/install/rhel/)

**Comment by AndrewVolosytnykhThingsboard** [comment]
@btabuenca if you're trying to upgrade from 3.0.1 to 3.2.2 without intermediate versions, it will cause issues. You should update Thingsboard step-by-step. From 3.0.1 to 3.1, from 3.1 to 3.1.1 etc to 3.2.2.
Could you tell me if you've done these steps?

**Comment by btabuenca** [comment]
> @btabuenca if you're trying to upgrade from 3.0.1 to 3.2.2 without intermediate versions, it will cause issues. You should update Thingsboard step-by-step. From 3.0.1 to 3.1, from 3.1 to 3.1.1 etc to 3.2.2.
> Could you tell me if you've done these steps?
No, I did not these intermediate updates. Then ... what do you suggest me to proceed?

**Comment by AndrewVolosytnykhThingsboard** [comment]
try to restore using backup and update correctly
