### ISSUE TITLE
[Bug] Thingsboard PE 3.2.2 Scheduler UI

### ISSUE THREAD

**Issue by hazarmutgan** [thingsboard/thingsboard#4782]
**Describe the bug**
In the calendar widget settings I am using Forced Default Event type and Custom Event type.
If I use the '+' sign on the top right of the widget to add schedule everything works fine.

![image](https://user-images.githubusercontent.com/52603603/123003070-f4d26280-d3b2-11eb-93ef-665b63c30247.png)
![image](https://user-images.githubusercontent.com/52603603/123003087-fd2a9d80-d3b2-11eb-9794-1d7c06ff4c4f.png)

However if  I click on the day on the calendar to add an event the template based custom field is not visible and schedule tab is broken.

![image](https://user-images.githubusercontent.com/52603603/123002664-737ad000-d3b2-11eb-9de1-3bd68e435713.png)
![image](https://user-images.githubusercontent.com/52603603/123002753-8beaea80-d3b2-11eb-86bc-5757a71c0d25.png)

**Your Server Environment**

* own setup
  * local deployment
  * PE 3.2.2
  * Ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Chrome
* Version 91.0.4472.114

**Comment by LeoMorgan113** [comment]
Hi @hazarmutgan,

I can not reproduce this bug. Is this still exist?

**Comment by vvlladd28** [comment]
Hi @hazarmutgan, 
Thank you for your report.  This issue will be fixed in the new release TB.
