### ISSUE TITLE
[Question] Why use LSB and MSB in some entity fields, for example, DeviceId is deviceIdMSB and deviceIdLSB in the object?

### ISSUE THREAD

**Issue by qzzhujixue** [thingsboard/thingsboard#4784]
Why use LSB and MSB in some entity fields, for example, DeviceId is deviceIdMSB and deviceIdLSB in the object?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
