### ISSUE TITLE
[Question] How should one format  device RPC request when  transport is MQTT/protobuf?

### ISSUE THREAD

**Issue by ubIQio** [thingsboard/thingsboard#4792]
**Component**

 * Generic

**Description**

I have a working system using MQTT/JSON, with telemetry, attributes and RPC which needs to use MQTT/protobuf to save bandwidth on the wire.

I can specify the telemetry and attributes protobuf schema in the transport dialog of version 3.2.2., and communicate from the client devices to my TB server using MQTT/protobuf just fine

However, RPC requests , which work using MQTT/JSON, fail to work using  MQTT/protobuf transport, and I cannot see where I would set the schema for this in order to send the RPC requests as protobuf messages

Any clues much appreciated!

**Comment by ubIQio** [comment]
I see this was added 8 days ago by @ashvayka and the request format is

`          "package rpc;" 
            "message RpcRequestMsg {" 
            "  string method = 1;" 
            "  int32 requestId = 2;" 
            "  string params = 3;" 
            "}";
`

Any idea when this will be part of a release?

**Comment by ashvayka** [comment]
pretty soon, by July 10.
