### ISSUE TITLE
[Question] Should TB accept bridged connections from mosquitto?

### ISSUE THREAD

**Issue by rduivenvoorde** [thingsboard/thingsboard#4795]
**Component**

 * Installation / general

**Description**

Having an excisting MQTT broker, we thought to use a bridge to a running TB
But whatever protocol version I use in the mosquitto.conf, I keep seeing 
`
ERROR o.t.s.t.mqtt.MqttTransportHandler - [5ebb297b-6c27-49fc-a853-51620e7c0365] Message processing failed: MQTTis unknown protocol name
`
in the logs (or MQIsdpis unknown protocol name in case of configuring mosquitto to use bridge_protocol_version mqttv31

tried to use both username/id/password and access-token for the bridge->TB connection

**Environment**

 * OS:  Debian testing Docker containers (latest image)

The idea was to feed TB from our central broker and maybe break up topics in TB later...
Or is this a bad idea, and is TB best used as central broker?

**Comment by rduivenvoorde** [comment]
Just found this:
https://stackoverflow.com/questions/45878364/how-to-let-thingsboard-connect-to-an-independent-mqtt-broker/45879873#45879873
is that answer still valid: "use the TB IoT Gateway" in between it?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
