### ISSUE TITLE
[Bug] Big database query

### ISSUE THREAD

**Issue by Hopperpop** [thingsboard/thingsboard#4807]
**Describe the bug**
We have been seeing slow response time when loading data in the dasboards. On one moment a user was switching dashboards quickly and the data didn't load anymore. Other users saw the same and couldn't load any data anymore.

In the performance logger of azure we found following query:
```
select tskventity0_.entity_id as entity_i1_31_, tskventity0_.key as key2_31_, tskventity0_.ts as ts3_31_, tskventity0_.bool_v as bool_v4_31_, tskventity0_.dbl_v as dbl_v5_31_, tskventity0_.json_v as json_v6_31_, tskventity0_.long_v as long_v7_31_, tskventity0_.str_v as str_v8_31_ from ts_kv tskventity0_ where tskventity0_.entity_id=$1 and tskventity0_.key=12 and tskventity0_.ts>=1623847754000 and tskventity0_.ts<1624452555000 order by tskventity0_.ts desc nulls last limit 35270
```

It ran for a accumulated time of almost 37min and an execution count of 1343.
![afbeelding](https://user-images.githubusercontent.com/11853634/123608956-8ac91b80-d7ff-11eb-9219-fd4865ba1e39.png)

Using the keyId and the arbitrary limit we can say for 95% sure that it came from a custom widget with following time settings:
![afbeelding](https://user-images.githubusercontent.com/11853634/123607655-60c32980-d7fe-11eb-811e-4749f4d1972a.png)

The bug/question is: 

- Why did it run so many times?
- Why is the time range in the query from Wednesday to Wednesday, while the time settings are from Monday to Sunday?
- The timerange is also from a week earlier than the time the dashboard was loaded, while the settings was set to the current week.

Afterwards the data loaded normally.

**Your Server Environment**

* Own setup
  * Azure VM running Thingsboard v.3.2.2PE
  * Azure Database for PostgreSQL server

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Win10
* Browser: Firefox v89.0.2 

**To Reproduce**
Not known yet.

**Additional context**
Running the querry manually (the entity_id filter is ommited) gives:
```
select tskventity0_.entity_id as entity_i1_31_, tskventity0_.key as key2_31_, tskventity0_.ts as ts3_31_, tskventity0_.bool_v as bool_v4_31_, tskventity0_.dbl_v as dbl_v5_31_, tskventity0_.json_v as json_v6_31_, tskventity0_.long_v as long_v7_31_, tskventity0_.str_v as str_v8_31_ from ts_kv tskventity0_ where tskventity0_.key=12 and tskventity0_.ts>=1623847754000 and tskventity0_.ts<1624452555000 order by tskventity0_.ts desc nulls last limit 35270;
/* Affected rows: 0  Found rows: 2,026  Warnings: 0  Duration for 1 query: 0.000 sec. (+ 3.110 sec. network) */
```

The custom widget uses the standard subscription mechanism. From our side we can't see anything that could case this behavior.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
