### ISSUE TITLE
[Feature Request] Upgrade Javax engine / Nashorn to support ES 6/ + allow to import modules

### ISSUE THREAD

**Issue by nvandamme** [thingsboard/thingsboard#4808]
Hi,

Is upgrading Nashorn planned ?
Or better yet, is migrating to GraalJS (https://github.com/oracle/graaljs) planned with nodejs coexecution ?

It could really enhance TB Rule Engine by using modern javascript and modules.

**Comment by Ultrazombie** [comment]
Hello
Feel free to test TBEL and remote JS executors(NodeJS) instead of Nashorn.

**Comment by ZYMCao** [comment]
This is actually something I am also looking for. Maybe you guys will reconsider GraalJS??
