### ISSUE TITLE
[Question] RPC call reply via MQTT

### ISSUE THREAD

**Issue by nvandamme** [thingsboard/thingsboard#4809]
Hi,

When i generate a RPC call reply in the Rule Engine, all my replies are failing with the error : 
```java.lang.RuntimeException: Service id is not present in the metadata!```

My rule is setup with a device listening on these topics : 
- telemetry: t/# with topics patterns : t/{device_uid}/{message_type}
- attributes: a/# with topic patterns : a/{device_uid}/{message_type}

The topic filters is catching all my topic patterns including rpc calls (good) : 
- RPC call from device topic pattern : a/{device_uid}/{message_type}/rpc/request/{requestId}
- Attributes update request : a/{device_uid}/{message_type}/request/{requestId}

How can i populate serviceId, seesionId... required for sendind RPC call replies ?

**Comment by faithware** [comment]
Post your docker-compose

**Comment by nvandamme** [comment]
Docker is not involved in this setup. We are using the straight Linux install setup.



---

Nicolas Vandamme | CEO/CTO

+352 621 41 86 07
+33 642 736 677
***@***.***

PGP Public Key ID : 492C5E8C

FIRIS SA | LU27948222 | RCS Luxembourg B 200097
9 rue du Laboratoire| L-1911 Luxembourg | LUXEMBOURG

________________________________

**Comment by Ultrazombie** [comment]
Closed due to inactivity
