### ISSUE TITLE
Alarm Table List by Updated time?

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#4811]
**Component**

 * UI - Alarms Table

**Description**
Currently Alarm table is showing the alarm list by when it created right? When the time window set, let say set to 12hour, it only show alarm which is created in 12hour ago.

But if the alarm created 14hours ago, but it updated 1minute ago by a rule node, this alarm only got updated  `end timestamp`, but the `start timestamp` or created time is still the same. So this alarm will not appear in alarm list.

Is there any a way to config this in alarm widget? I want to show the alarm got updated lately, even the time created is more than 12hrs, if the `end timestamp` is still in 12hrs range it can appear on the list?

**Comment by LeoMorgan113** [comment]
Hi @evanderbird,

The Alarm Table doesn't show alarms that are Updated, only active(created) or cleared. 
So maybe you may recreate the alarm, not update it.
The other way, you may try is to create some logic with Script Transformation Node to overwrite the time or add new attribute/telemetry parameter to display the actual time of alarm.

![2021-06-24_15-56_1](https://user-images.githubusercontent.com/56256429/125780865-9667a161-7e80-48e5-8a0d-be384d54f300.png)
![2021-06-24_15-57](https://user-images.githubusercontent.com/56256429/125780872-ee03821e-a200-4fd9-b935-772fa619ebc7.png)
