### ISSUE TITLE
[Feature Request] Add import export settings to ease deployment of new server

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#4813]
**Is your feature request related to a problem? Please describe.**
We need to be able to move/deploy new server fast. However a lot of data/configuration are not importable/exportable easily.

**Describe the solution you'd like**
Make the following configurations importable and exportable on files:
* Roles
* White labeling
  * Mail server
  * Mail template (this one is extremely painful for now)
  * Custom translation (should not be that hard)
  * Custom menu
  * White labeling (also very painful)
  * Login with white labeling

**Describe alternatives you've considered**
A single interface to export all of these in an archive and that let you check what you want to export in an archive

**Additional context**
Could be also used for backup.

**Comment by Ultrazombie** [comment]
Hello,
Since the 3.4 version of ThingsBoard, we have that feature: https://thingsboard.io/docs/user-guide/version-control/
