### ISSUE TITLE
[Feature Request] Map clustering with active alarms sumed up

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#4814]
**Is your feature request related to a problem? Please describe.**
Map clustering is a nice feature, what would make it an incredible one would be the possibility to directly see each cluster with the number of active alarms of the devices in the cluster.

**Describe the solution you'd like**
Possibility to directly display each cluster with the number of active alarms of the devices in the cluster.

**Describe alternatives you've considered**
At least if there is active alarm in the cluster or not.

**Comment by Ultrazombie** [comment]
No one has shown further interest in this, so it has been rejected. Please create a new feature request if you still consider this valid.
