### ISSUE TITLE
[Question] Control: 'Update device attribute' widget?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#4816]
**Component**
Thingsboard Webpage
 * UI
Widget: 'New Update device attribute'

**Description**
Is there any documentation about how to use this widget?
There is a { } edit box what are you supposed to enter, list, code?

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.2.2

**Comment by ashaforost** [comment]
Hi there,

For now, the documentation for the input widgets is in development.
As for those curly brackets in the widget settings, they are used to set the key-value pairs of server or shared attributes of your device/s, which will be updated on a button click.

For example, I had a device with the server attribute "active" set to false. With the following configuration, I can manually change this value to true.
![image](https://user-images.githubusercontent.com/47900737/123842712-c1935480-d919-11eb-8316-dcb05c65869a.png)

Please let me know if you have any further questions.

**Comment by KenSense** [comment]
Thanks that clears it up
