### ISSUE TITLE
[Question] Button Action Code to Post latest telemetry value to another key?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#4817]
**Component**
Thingsboard Webpage
 * UI
Widget Actions

**Description**
I want to copy the value of the telemetry key distributionImage to distributionRefImage when they press the action button.

I don't have much more than starting with 

_let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));_

Then I assume this but I don't know how I should translate that to javascript??
(Get latest value and post it again on other key)

_var sourcekey = 'distributionImage'
value = get /api/plugins/telemetry/{entityType}/{entityId}/values/timeseries{?keys,useStrictDataTypes}_ 

_var targetkey = 'distributionRefImage'
post /api/plugins/telemetry/{entityType}/{entityId}/timeseries/{scope}_ 

Thanks

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.2.2

**Comment by KenSense** [comment]
I see I may need to use getEntityTimeseries and saveEntityTimeseries from class AttributeService
An example would be nice!

**Comment by KenSense** [comment]
I tried to simplify it by writing the code in the rule chain and then trigger that code with a server Attribute.
So on Action I only need to set an predefined server Attribute (no pop-up)

But it doesn't work, do you see why? (is there some way to debug to see what fails?)
`let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext
    .servicesMap.get('attributeService'));

saveAttributes(entityId);

function saveAttributes(entityId) {
    let attributesArray = [];
    attributesArray.push({
        key: "setRefTrigger",
        value: true
    });
    if (attributesArray.length > 0) {
        return attributeService.saveEntityAttributes(
            entityId, "SERVER_SCOPE",
            attributesArray);
    } else {
            return false;
    }
}`

Thanks

**Comment by ChantsovaEkaterina** [comment]
Hello, @KenSense 
The code below should help you. It is important to call _subscribe_, without this nothing will work.
```
saveAttributes(entityId).subscribe(() => {
//    your code
});

function saveAttributes(entityId) {
    let attributesArray = [{
        key: "setRefTrigger",
        value: true
    }];
    return attributeService.saveEntityAttributes(
        entityId, "SERVER_SCOPE",
        attributesArray);
}
```

**Comment by KenSense** [comment]
Thanks!

That works
