### ISSUE TITLE
Thingsboard PE V3.2.2 Timeinterval window acting strangely

### ISSUE THREAD

**Issue by ChristineChetty11** [thingsboard/thingsboard#4828]
The UI is not making sense, timewindow.interval selection does not have a translation

Console Error Log: 
![image](https://user-images.githubusercontent.com/60428015/123948399-a704be00-d9a1-11eb-93be-553a5396f098.png)

Screenshot:
![image](https://user-images.githubusercontent.com/60428015/123948361-9c4a2900-d9a1-11eb-95b2-960d9d1621e7.png)

**Comment by LeoMorgan113** [comment]
Hi @ChristineChetty11,

Please clean browser cache and reload page.
It must help.
