### ISSUE TITLE
[Bug] Device Active State not updated using Kafka Integration

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#4829]
**Describe the bug**
The Inactivity and Activity Events are not properly updated while using the Kafka Integration. The attribute **active** remains in false state, even if there are new messages and lastActivityTime is updated. Therefore alarming for device connectivity can't be used in a productive environment. 

The same behaviour was also reported for the HTTP Integration in the following issue:
https://github.com/thingsboard/thingsboard/issues/4039

**Your Server Environment**
  * Azure Cloud Kubernetes
  * ThingsBoard 3.2.2 PE

* Connectivity
  * Integration: Kafka

**Expected behavior**
Update both attributes **active** and **lastActivityTime**.

**Screenshots**

![image](https://user-images.githubusercontent.com/25298332/123960629-cefb1e00-d9af-11eb-9733-dad5179799f4.png)

**Comment by mde2017** [comment]
upgraded to Version 3.3.2. but the problem is still present. Active state is false.

![image](https://user-images.githubusercontent.com/25298332/144385586-4774e5fc-cb3b-4590-94f3-c11eb325afc4.png)

**Comment by gohm-tech** [comment]
Hi @ashvayka and @vvlladd28,

We have the same issue too.

Best Regards,
**Gohm Team**

**Comment by xiddjp** [comment]
what a terrible issue
