### ISSUE TITLE
[Bug] Cannot change device owner with role that should allow it.

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#4833]
**Describe the bug**
I want to change the owner of a device with a custom made role but it does not allow it..
(The role does not have device delete rights)

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard 3.2.2
  * OS Windows 10

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Edge

**To Reproduce**
1. Make new role with provided rights (including change owner for devices)
2. Login with user of that role
3. Go to devices group page
4. Select device
5. Icon to change owner is not available!?

**Screenshots**
![image](https://user-images.githubusercontent.com/49442805/123974430-e260b600-d9bc-11eb-9886-ff1bcac5e133.png)

**Comment by LeoMorgan113** [comment]
Hi @KenSense,

If you want to change owner you can claim device. Refer to https://thingsboard.io/docs/user-guide/claiming-devices/
From Tenant, you can claim it to Customer. 

If then appear necessity to claim it to another one, you need to do the next:
- Reclaim device to Tenant back
- Then claim it to another Customer

**Comment by KenSense** [comment]
I'm the tenant and the device is currently owned by the tenant.
I like to move it from the general device pool to a customer.

**Comment by LeoMorgan113** [comment]
So you should try device claiming.
It can be done with Swagger.

**Comment by vvlladd28** [comment]
Hi @KenSense,
Thank you for your report, this issue will be fixed in the new version TB

**Comment by KenSense** [comment]
Is there a workaround for now? (without giving 'All' rights)

**Comment by vvlladd28** [comment]
There is no workaround.
Wait for a new release which is expected within 2-3 weeks
