### ISSUE TITLE
[Question] What is this "apiUsageStateService" for? I have used it in many places.

### ISSUE THREAD

**Issue by qzzhujixue** [thingsboard/thingsboard#4838]
What is this "apiUsageStateService" for? I have used it in many places.

**Comment by LeoMorgan113** [comment]
Hi @qzzhujixue,

We have ApiUsage, which gathers all statistics from Thingsboard, you can view it in the 'ApiUsage' menu item.
So "apiUsageStateService" is needed for working with these services.
