### ISSUE TITLE
Unable to find resource 'error.vm' in any resource loader.

### ISSUE THREAD

**Issue by ethicstechOSS** [thingsboard/thingsboard#484]
Hi. 
I am getting "ERROR org.apache.velocity - ResourceManager : unable to find resource 'error.vm' in any resource loader" in the log file and the whitelabel error on the login web page. 

The existing issue #367 is what I am facing right now. However, I could not able to understand what will be the solution @skedin fixed. There were other similar issues raised by others due to code modification,  #410, #331, #268, #241, #73 But, I just build the existing source without modified anything.

**Comment by mp-loki** [comment]
Hi @ethicstechOSS . You see this issue when ui module is not built properly. This has something to do with node and npm not working stable - same versions work on some machines and fail on others. There is no a stable fix for this right now. we will try to address it soon.

**Comment by ethicstechOSS** [comment]
Hi mp-loki. Thanks for your input. So may I know which version of npm & node can build the properly working ui module successfully?. Information about the OS also useful for me. Because, I have being tried the same Ubuntu 16.04 64bit on 4 machines. None of them working properly with the latest node & npm versions.

**Comment by ram1505** [comment]
I'm having the same issue. I'm on Ubuntu 16.04 with node version 8.9.4 and npm version 5.6.0.

**Comment by LeoMorgan113** [comment]
Hi,
This issue was fixed in the newest versions.
Please refer to https://thingsboard.io/docs/reference/releases/
