### ISSUE TITLE
[Question]  Hello, I want to know what is the function of "service.tenant_id" in thingsboard.yml configuration file? What is the connection with the tenants in the business?

### ISSUE THREAD

**Issue by qzzhujixue** [thingsboard/thingsboard#4845]
**Component**
 * Rule Engine

**Description**
Hello, I want to know what is the function of "service.tenant_id" in thingsboard.yml configuration file? What is the connection with the tenants in the business?

**Environment**
 * OS:  Linux centos 7
 * ThingsBoard: 3.2.2
 * Browser: chrome

**Comment by LeoMorgan113** [comment]
Hi @qzzhujixue,

'service.tenant_id' is not used by default for now. But the main idea for this is when we want to run a core or rule engine for specific tenant, we define ID and only messages for his queue will be processed.
