### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by creinarz** [thingsboard/thingsboard#4846]
Hi, 

For the last few hours I am getting this error while trying to login to the demo.thingsboard.io server:

"Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection". Also, mosquitto_pub returns with unknow error.

Is the server down?

Thanks for your help.
Christof

<img width="1392" alt="Screen Shot 2021-07-01 at 21 42 00" src="https://user-images.githubusercontent.com/64421910/124213710-0c9a9c80-dabf-11eb-9e33-35f44a420d1d.png">

**Comment by vvlladd28** [comment]
Hi @creinarz ,
Thank you for your report, the issue have been fixed.
