### ISSUE TITLE
How to generate $JWT_TOKEN for data query API

### ISSUE THREAD

**Issue by JacquelineGoh** [thingsboard/thingsboard#485]
Good day to all reader,

Thingsboard has prepared the data query API instruction [Timeseries data keys API](https://thingsboard.io/docs/user-guide/telemetry/)

To get the [$JWT_TOKEN](https://thingsboard.io/docs/reference/rest-api/#rest-api-auth) is to run the code below:
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"username":"tenant@thingsboard.org", "password":"tenant"}' 'http://[mylocalhostname]/api/auth/login'`

I have tried using the curl.exe software in windows 10 run the code above and the result shown as below:

`curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{"username":"tenant@thingsboard.org", "password":"tenant"}" "https://[mylocalhostname]/api/auth/login" -k                                                                                             {"status":401,"message":"Authentication failed","errorCode":10,"timestamp":1513354947224} `

Therefore, I cannot get the correct TOKEN to proceed the query. 
Do any success cases to generate the TOKEN and the suitable tools to query the data?

Thank you and have a nice day. :)

**Comment by mp-loki** [comment]
Your request is correct, I have copied it  to the command line and it worked correctly:

```
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: appli                                                                                                                                  cation/json' -d '{"username":"tenant@thingsboard.org", "password":"tenant"}' 'ht                                                                                                                                  tp://localhost:8080/api/auth/login'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1002  100   944  100    58   2160    132 --:--:-- --:--:-- --:--:--  2160{"                                                                                                                                  token":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGV                                                                                                                                  zIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI0ZWYyYzdlMC1hYjk1LTExZTctYTQ1Zi0xZGNlZmZ                                                                                                                                  jOGYyOGYiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiNGVmMTY4NTA                                                                                                                                  tYWI5NS0xMWU3LWE0NWYtMWRjZWZmYzhmMjhmIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTF                                                                                                                                  iMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTEzNTQ5NzM                                                                                                                                  5LCJleHAiOjE1MTM1NTA2Mzl9.QtSkAg_pEyMhHvo6zx8M9uaCfDmtXn-4a4fVcPH3-huiQX1QPzJ_1o                                                                                                                                  vLVb-5Wng8bWNjAMmOnbqcQbJJmhlsjQ","refreshToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiO                                                                                                                                  iJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlJFRlJFU0hfVE9LRU4iXSwidXNlcklkI                                                                                                                                  joiNGVmMmM3ZTAtYWI5NS0xMWU3LWE0NWYtMWRjZWZmYzhmMjhmIiwiaXNQdWJsaWMiOmZhbHNlLCJpc                                                                                                                                  3MiOiJ0aGluZ3Nib2FyZC5pbyIsImp0aSI6ImIyNGFiYjA3LWE5NmMtNDJmMi04ODIxLTRmY2QxMWNiN                                                                                                                                  jI3ZSIsImlhdCI6MTUxMzU0OTczOSwiZXhwIjoxNTEzNTUzMzM5fQ.ozC2aFc8bOJ7PGUiPjjK9_tyQo                                                                                                                                  K90RXgEe2oV0HrSfxf5W3Vha3jCjgerTG04g1oAnH-tUhN-aHpEGl2g2KNPw"}

```
In your case 401 unauthorized could mean that username/password do not exist in your application database. Are you able to login to GUI using the same credentials?

**Comment by JacquelineGoh** [comment]
Hi @mp-loki,

What type of the environment are you using to run this code?
Linux or macOS?
Because I am using the windows and install the curl.exe software. 
Then, the result will be shown in above. 

Do you success query the data or retrieve the data from Thingsboard?

Thank you :)

**Comment by mp-loki** [comment]
I was running that line of code in Git Bash on Windows 10. You may try Postman as well

**Comment by JacquelineGoh** [comment]
Hi @mp-loki ,

I found that the windows 10 command prompt cannot treat single quote.
Therefore, I need to put a backslash (\) to the double quote.

eg: curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"username\":\"tenant@thingsboard.org\", \"password\":\"tenant\"}" "http://[localhost_name]/api/auth/login"

**Comment by JacquelineGoh** [comment]
Hi @mp-loki ,

Thank you for your reply. :) 

Now I can get some response with the token but I tried several ways still cannot get the correct answer.
1. When the token expired I will replace new token
2. I have tried the link with http or http(s) both also give me the similar output 
3. "301 Moved Permanently" error from curl I have tried to put the slash end of the link the output also same.

The output from postman:
`{
    "timestamp": 1514210272390,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.IllegalArgumentException",
    "message": "Invalid UUID string: DEVICE",
    "path": "/api/plugins/telemetry/DEVICE/47a76ba0-ad9b-11e7-a5ac-2f8f3fdf329b/values/timeseries"
}`

The output from curl:
`Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to [localhost_name] (xxx.xxx.xxx.xxx) port 80 (#0)
> GET /api/plugins/telemetry/DEVICES/47a76ba0-ad9b-11e7-a5ac-2f8f3fdf329b/values/timeseries?keys=UTC,a1 HTTP/1.1
> Host: [localhost_name]
> User-Agent: curl/7.57.0
> Accept: */*
> Content-Type:application/json
> X-Authorization:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI3MjkzMmI4MC1kZWY5LTExZTctYTVhYy0yZjhmM2ZkZjMyOWIiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiZmVlM2ZmMjAtZGVmOC0xMWU3LWE1YWMtMmY4ZjNmZGYzMjliIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTE0MjA5OTEzLCJleHAiOjE1MTQyMTA4MTN9.QYug82xdxV1vBvp9dC-FW6bgVS_mMtgW4NXC2DW3JSI2UmDf8JnzID3zwXGHxiqjBPM8Lk0_XbM2HaJdXpiV_g
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.12.2
< Date: Mon, 25 Dec 2017 13:53:52 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Location: https://[localhost_name]/api/plugins/telemetry/DEVICES/47a76ba0-ad9b-11e7-a5ac-2f8f3fdf329b/values/timeseries?keys=UTC,a1
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>
* Connection #0 to host [localhost_name] left intact`

Thank you and have a nice day.

**Comment by mp-loki** [comment]
**X-Authorization** must be '**Bearer {{token}}**', you have only **{{token}}**. Note the space between 'Bearer' and the token

**Comment by hanyuwenn** [comment]
If you have installed node.js, you can use the code below to get **JWT_TOKEN**.

`var request = require('request');

var host = 'localhost:8080';	
var username = 'tenant@simit.com';	 
var password = '123qweasd';			

var user = {
	'username': username,
	'password': password
};

var options = {
	method: 'post',
	url: 'http://' + host + '/api/auth/login',		
	headers: {
		'Content-Type': 'application/json',
		'Accept': 'application/json',
	},
	body: JSON.stringify(user),
};

request(options, function(error, response, body) {
	console.log('error:', error);
	console.log('statusCode:', response && response.statusCode);
	console.log('body:', body);
});

`

**Comment by hanyuwenn** [comment]
If you have installed node.js, you can use the code below to get JWT_TOKEN.

```
var request = require('request');

var host = 'localhost:8080';	
var username = 'tenant@simit.com';	 
var password = '123qweasd';			

var user = {
	'username': username,
	'password': password
};

var options = {
	method: 'post',
	url: 'http://' + host + '/api/auth/login',		
	headers: {
		'Content-Type': 'application/json',
		'Accept': 'application/json',
	},
	body: JSON.stringify(user),
};

request(options, function(error, response, body) {
	console.log('error:', error);
	console.log('statusCode:', response && response.statusCode);
	console.log('body:', body);
});
```

**Comment by HeroBarry** [comment]
> 



> I was running that line in Git Bash on Windows 10. You may try Postman as well

Is right!  win10 dos is fail,if you fail in win10 curl ，can try git bash.

**Comment by murt30** [comment]
Windows 10 Command line is the problem. Replace ' with " and put a \ before the double quotes in the JSON object. "{\"username\":\"tenant@thingsboard.org\", \"password\":\"tenant\"}"

**Comment by aniketmanjare** [comment]
> I was running that line in Git Bash on Windows 10. You may try Postman as well

Im trying to GET the data on Postman from Thingsboard, but  I am getting Authorization denied code and I have used proper Bearer Token with a space can you suggest me a solution
