### ISSUE TITLE
[Question] No enum constant org.thingsboard.server.common.data.EntityType.TB_RESOURCE

### ISSUE THREAD

**Issue by pkrulz** [thingsboard/thingsboard#4853]
I recently upgraded from v3.1 to v3.2 and then v3.2.2 on Ubuntu 20.04
There was no error message on upgrade.

While the upgradation instruction said merge the config files, it did not give such option and I went ahead with my old yml and config files.

First that was a problem and thingsboard refused to start. After releasing that it was having issues due to configurations found in new yml files but not present in my old files I downloaded the latest yml from here into the config folder
https://raw.githubusercontent.com/thingsboard/thingsboard/master/application/src/main/resources/thingsboard.yml

After that when I tried to start it gave me the following error. I am not sure how to go ahead from here. Any pointers please

` ERROR o.s.b.w.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditLogServiceImpl': Unsatisfied dependency expressed through field 'auditLogLevelFilter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'auditLogLevelFilter' defined in class path resource [org/thingsboard/server/config/ThingsboardSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thingsboard.server.dao.audit.AuditLogLevelFilter]: Circular reference involving containing bean 'thingsboardSecurityConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'auditLogLevelFilter' threw exception; nested exception is java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.common.data.EntityType.TB_RESOURCE`

**Comment by pkrulz** [comment]
Update:

Around 12 hours later, the web interface is up and I don't understand how.

Nevertheless an error message like this is still present in the log file
`[http-nio-0.0.0.0-8080-exec-4] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception`

Also I am not able to post messages to the server. All of them end with Error 501. 

I have been using curl to send data from Windows 10 and the command looks like this
`curl -v --data "{"heartbeat":42}" https://myserver.com/api/v1/<APICODE>/telemetry --header "Content-Type:application/json"`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
