### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vinodkmani** [thingsboard/thingsboard#4854]
**Describe the bug**
On the video option in trip animation widget, the arrows to control speed and to set initial and end points is not working as expected.
 => Video right/left double arrow goes to the end/beginning of the video.
 => The other to end arrows don't do anything

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version 3.1.1
  * OS Name and Version Windows 10 Enterprise

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windowa
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] 

**To Reproduce**
1. Go to '...' Trip animation video
2. Click on '....' Control Arrows

**Expected behavior**
Play faster  and go the  ends on clicling respective arrows

**Screenshots**
![image](https://user-images.githubusercontent.com/56358395/124299854-cc3a2d80-db55-11eb-9f1d-96e7c613b3f6.png)

**Additional context**

**Comment by LeoMorgan113** [comment]
Hi @vinodkmani,

I checked it on my side(v.3.2.2) and found that these arrows may not work as expected when in the time window selected very small period. 
Please, choose longer timeperiod and check if this problem still appear.
![2021-07-15_13-08](https://user-images.githubusercontent.com/56256429/125770862-e572d821-4273-4812-b513-c8acb99d44b4.png)

By the way, soon will be new version and known bugs with this widget have to be fixed. So keep up to update.
