### ISSUE TITLE
[Bug] We are getting error while connectig to device through Gateway

### ISSUE THREAD

**Issue by abhishekprofessional** [thingsboard/thingsboard#4856]
**Describe the bug**
So We downloaded thingsboard code from GitHub and tried to connect the device through the gateway and getting following errors.

```
""2021-07-04 23:24:05" - ERROR - [mqtt_connector.py] - mqtt_connector - 198 - [WinError 10061] No connection could be made because the target machine actively refused it"
""2021-07-04 23:24:17" - ERROR - [mqtt_connector.py] - mqtt_connector - 198 - [WinError 10061] No connection could be made because the target machine actively refused it"
```

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Linux and windows 
* Browser: Chrome
* Version : 91.0.4472.114

**Your Device**

* Connectivity
  * MQTT
  * Gateway

**To Reproduce**
1. Downloaded thingsboard from the Github
2. Installed all the requirements from the setup.py file
3. Changed the host and access token in the tb_gateway.yaml
4. We triggered the tb_gateway.py file

**Expected behavior**
Connection should be established and subscription should be done with the required topic

![image](https://user-images.githubusercontent.com/58512818/124395090-d0b24200-dd1f-11eb-9f54-3d2d67bbb863.png)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
