### ISSUE TITLE
ruleEngine Cluster deploy.  ServiceId is Unique?

### ISSUE THREAD

**Issue by siaron** [thingsboard/thingsboard#4858]
If the rule engine is deployed in a cluster. Should the serviceId of each service be unique? See the following in TbGpsGeofencingActionNode
`.find(ctx.getTenantId(), msg.getOriginator(), DataConstants.SERVER_SCOPE, ctx.getServiceId())` query. If it is not unique, will it cause data statistics errors.

**Comment by volodymyr-babak** [comment]
@siaron 
this is correct, the service ID for tb-core/rule-engine components must be unique to avoid any mess in the data processing.
