### ISSUE TITLE
[Question] Is it possible to pass Dashboard State/Entity to Scheduler Widget Custom Event ?

### ISSUE THREAD

**Issue by hazarmutgan** [thingsboard/thingsboard#4859]
**Component**

 * UI
 * Scheduler Widget

**Description**
Scheduler Widget is not related to any dashboard entity or state so user needs to select the originator every time although in our application scheduler widget is available to the user only at specific dashboard state ( for example and asset or a device) . Is it possible to pass this information to custom event configuration HTML?

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: PE 3.2.2
 * Browser: Chrome

**Comment by t0mmyz7** [comment]
Hello any updates on this? We would like to achieve the same thing exactly. 

@ashvayka @YevhenBondarenko

**Comment by vvlladd28** [comment]
Hi @hazarmutgan,
At the moment, it is impossible to implement. In future releases, we will add it.
