### ISSUE TITLE
can not find the type of Kafka Plugin

### ISSUE THREAD

**Issue by williamye** [thingsboard/thingsboard#486]
![image](https://user-images.githubusercontent.com/4486648/34111787-b1b0454a-e445-11e7-9295-6383b9570ed5.png)
Try to add one new Plugin which type should be Kafka Plugin. But there seems no this kind of Plugin type in my web UI. The source code is from the official github repo. How can I fix this problem? Thank you.

**Comment by mp-loki** [comment]
If you are running from your development environment, you need to add kafka plugin to your application/pom.xml as a dependency, otherwise it is not included in classpath. There is a different behavior when you install ThingsBoard as a service
