### ISSUE TITLE
[Bug] MQTT Protobuf mangles multiple message types

### ISSUE THREAD

**Issue by ubIQio** [thingsboard/thingsboard#4860]
Thingsboard MQTT Protobuf mangles telemetry key/value pairs when using multiple message types [see Google Protobuf docs example](https://developers.google.com/protocol-buffers/docs/proto3#adding_more_message_types) shown below
```

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}

message SearchResponse {
 string response = 4;
}
```

The use of multiple message types is desirable for a complex device that issues many different types of telemetry (eg many different types of sensors, LOGS etc) and these message types are sent with different frequencies. (If there is only one message type then all telemetry data must be sent on each publish which is very bandwidth inefficient).

** Server Environment**
* demo.thingsboard.io

**Your Client Environment**

* OS: MacOS 11.4
* Browser: chrome
* Version [91.0.4472.114 (Official Build) (x86_64)]

**Your Device**
Thingsboard demo test device A2

* Connectivity
  * MQTT with protobufjs

**To Reproduce**

Use this protofile as proto.file
```
syntax ="proto3";
package telemetry;

message Stats {
  string uptime= 1;
  string rssi = 2;
}

message Temperatures {
  string ta= 3;
  string tp = 4;
}
```

Use this script as pbtest.js
```
var mqtt = require('mqtt');
var protobuf = require("protobufjs");

const thingsboardHost = "demo.thingsboard.io";

// Reads the access token from arguments
const accessToken = process.argv[3];


run().catch(err => console.log(err));

async function run() {
    // Reads the protfile from arguments
    const root = await protobuf.load(process.argv[2]);

    const Temperatures = root.lookupType('telemetry.Temperatures');
    const Stats = root.lookupType('telemetry.Stats');

    const temps = Temperatures.encode({ ta: "Ta", tp: "Tp" }).finish();
    
    const stats = Stats.encode({ uptime: "uptime", rssi: "rssi" }).finish();

    // console.log(temps.toString('hex')); // 
    // console.log(stats.toString('hex')); // 

    // Initialization of mqtt client using Thingsboard host and device access token
    console.log('Connecting to: %s using access token: %s', thingsboardHost, accessToken);
    var client  = mqtt.connect('mqtt://'+ thingsboardHost, { username: accessToken });

    // Triggers when client is successfully connected to the Thingsboard server
    client.on('connect', function () {
        console.log('Client connected!');
        client.publish('v1/devices/me/telemetry', temps);
        client.publish('v1/devices/me/telemetry', stats);
        
    });
  
}

```

Setup a device profile to use the above proto.file

Set a device to use the device profile created above and copy its `<device token>`

Publish the protobuf data over MQTT to Thingsboard demo using

`node pbtest.js proto.file <device_token>
`

**Expected behavior**
Expect that the latest telemetry shows all 4 keys with corresponding values

Result is that only first two key are shown with no values.

Changing the proto.file to
```

syntax ="proto3";
package telemetry;

message Stats {
  string uptime= 3;
  string rssi = 4;
}

message Temperatures {
  string ta= 1;
  string tp = 2;
}
```

results in Stats message values being displayed as Temperatures message, ie

![image](https://user-images.githubusercontent.com/12933213/124462080-9aada600-dd91-11eb-8b10-60159c9d9f50.png)

**Comment by nguyenlam185** [comment]
Hi @ubIQio,
Have you made any progress?
I am now facing the same problem with the CE version, so if you have any idea to help me out, I would appreciate so much.

**Comment by ShvaykaD** [comment]
Hi @ubIQio and @nguyenlam185, the Thingsboard MQTT Protobuf doesn't support multiple messages cause we are using dynamic proto schemas that build in the runtime on each schema update in the device profiles, so when we are receiving data from the device in the MQTT we don't have a way to determinate which Dynamic message descriptor we should use to convert MQTT message payload(bytes) to JSON.

As a workaround for your issue, I can suggest using one message with an optional keyword for each proto field inside:

see the example below:

schema:

`syntax ="proto3";
package telemetry;

message Telemetry {
   optional string uptime= 1;
   optional string rssi = 2;
   optional string ta= 3;
   optional string tp = 4;
}`

mqtt client:

`var mqtt = require('mqtt');
var protobuf = require("protobufjs");

const thingsboardHost = "demo.thingsboard.io";

// Reads the access token from arguments
const accessToken = process.argv[3];


run().catch(err => console.log(err));

async function run() {
    // Reads the protfile from arguments
    const root = await protobuf.load(process.argv[2]);

    const Telemetry = root.lookupType('telemetry.Telemetry');
    
    const telemetryWithTemperatures = Telemetry.encode({ ta: "Ta", tp: "Tp" }).finish();
    const telemetryWithStats = Telemetry.encode({ uptime: "uptime", rssi: "rssi" }).finish();

    // Initialization of mqtt client using Thingsboard host and device access token
    console.log('Connecting to: %s using access token: %s', thingsboardHost, accessToken);
    var client  = mqtt.connect('mqtt://'+ thingsboardHost, { username: accessToken });

    // Triggers when client is successfully connected to the Thingsboard server
    client.on('connect', function () {
        console.log('Client connected!');
        client.publish('v1/devices/me/telemetry', telemetryWithTemperatures);
        client.publish('v1/devices/me/telemetry', telemetryWithStats);
        
    });
}`

and video example:

https://user-images.githubusercontent.com/16356590/128370223-95520704-b45d-4f31-92f9-aaec735c82a7.mp4

**Comment by ShvaykaD** [comment]
Hi @ubIQio and @nguyenlam185  please note that we can add to the schema multiple messages but only the last one will be used in the MQTT transport as DynamicMessage for parsing the payload.

It means that you can use the other messages as proto fields inside the last message

**Comment by nguyenlam185** [comment]
Hi @ShvaykaD ,
I will try your solution and may get back to you soon.
Thank you for your support.

**Comment by ShvaykaD** [comment]
Hi @nguyenlam185, please let me know if I can close this issue?

**Comment by ubIQio** [comment]
@ShvaykaD , 

 using the other messages as proto fields inside the last (only) message was my workaround which works just fine.

In case anyone happens to be using minipb in python or micropython, here's my profile (different format to proto.file)


``` 
# Telemetry Inner schemas
Temps = (('ta', 'f'), ('tp', 'f'),)
Stats = (('uptime', 'z'),('freeheap', 'z'),('conn', 'z'),('cputemp', 'f'),('rssi', 'f'))
Nfft  = (('nb', '#f'), )


# Telemetry Outer schema
telem_schema = (('temps', '[', Temps, ']'),
          ('stats', '[', Stats, ']'),
          ('nfft', '[', Nfft, ']'),
         )

```

This permits sending 512 float arrays in about 6ms from an esp32, which took more like 3s using JSON so works well


thanks for looking into this, closing as my problem is solved
