### ISSUE TITLE
[Bug] profile alarm with complex logic not working with dynamic value if set but attribute is missing

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#4862]
We have noticed that if we set a complex alarm rule in device profile using 2 dynamic values. If one of the attributes is missing, the alarm doesn't work. Perhaps this is as intended, but it does cause us some issues with the following common use-case:

for temperature sensor, we allow user to set High Threshold and Low Threshold

the alarm logic is  (if value is greater than High Threshold **or** lower than Low Threshold)

Using dynamic values

the bug is, if user did not set Low or High threshold attributes, the alarm does not work.

expected: Since it is an OR statement, if High Threshold is set, but Low Threshold is not set, we still expect alarm to trigger.

Does this make sense?

**Comment by t0mmyz7** [comment]
I did notice now the option to "Inherit from owner" if attribute is missing. Which should solve this issue, but I think the bug still stands.

**Comment by yeduy** [comment]
Hello @t0mmyz7 ,

What I know is if the customer don't set the Threshold from dashboard, Alarm rule is using default value what u set on device profiles.

![image](https://user-images.githubusercontent.com/59412389/128343824-e9d5dba1-d0ad-4f71-a989-ad5c9502db29.png)

Did you try this?

If it doesn't help maybe you can force your customers to set the Threshold using data key settings on widget.

![image](https://user-images.githubusercontent.com/59412389/128344200-1e0608a1-5f69-45b4-ac5e-bd7d05f69a3d.png)

**Comment by SuminDenis** [comment]
Hello @[t0mZ4](https://github.com/t0mZ4),

I’m glad to inform you that this issue has been solved in the current version of ThingsBoard!
