### ISSUE TITLE
[Question] Close opened MQTT connection

### ISSUE THREAD

**Issue by fraucamidokura** [thingsboard/thingsboard#4863]
**Component**

 * Generic

**Description**

Suppose we have a broken device that is sending a huge amount of data. I want to close the current connection on a specific device.

I'm not finding a way to close an open connection, and I would like to know if is possible.

Thank you in advance

**Comment by KenSense** [comment]
If you make a new connection with the same Client ID the current one will be closed
(it doesn't prevent the device to dome the same reconnect and kick you off)

I guess in that situation I would change the device credential settings I think so It can't keep sending data, only try to connect..
It will depend on your device firmware how long it tries before giving up.

**Comment by fraucamidokura** [comment]
> If you make a new connection with the same Client ID the current one will be closed
> (it doesn't prevent the device to do the same reconnect and kick you off)
> 
> I guess in that situation I would change the device credential settings I think so It can't keep sending data, only try to connect..
> It will depend on your device firmware how long it tries before giving up.

Thank you very much for the answer. The problem is that changing credentials prevent the device to make new connections. But if the device is already connected changing the credentials does not disconnect that device so it could keep sending information.

I will take a look on the client id thing to see if we have a work around with that one.
