### ISSUE TITLE
[Question] How to check the type/device profile of an Entity and change dashboard state based on the type/device profile

### ISSUE THREAD

**Issue by sambartle** [thingsboard/thingsboard#4867]
UI

If I have an entity list which contains multiple entities, of different types, which all show a single measurement (so all can be shown no matter the type) is there a way to switch dashboard states based on the type (possibly from Device Profile which is set to 'therm' or 'light' in my example below) of the clicked entity so that I can display the diagnostic data for each entity (which differ significantly) using a type based state for each differing type?

There's an answer to a similar question here which implies its possible, but unfortunately didn't elaborate on how to do it: https://github.com/thingsboard/thingsboard/issues/3758#issuecomment-731016259

An example:

EntityList
-----------
Thermometer    25C
Thermometer2    45C
Light Sensor    100lux

When I click any of the thermometers I want to navigate to a dashboard state (thermometer), which has specific data and graphs for a thermometer (and specifically the one selected).. but if I select a Light Sensor.. then I want to go to a (Light Sensor state), with different data and attributes. I was hoping that the "Device Profile" could be used as a type to allow switching states based on that and then set the entity based on the item clicked.

Environment

OS: Windows Server
ThingsBoard: 3
Browser: Chrome (latest version)

**Comment by ChantsovaEkaterina** [comment]
Hello, @sambartle 
To switch states depending on the device profile you need to create a custom action. The following code will allow you to get the type (profile) of a device and then open an appropriate dashboard state:
```
let $injector = widgetContext.$scope.$injector;
$injector.get(widgetContext.servicesMap.get('entityService')).getEntity(entityId.entityType,
    entityId.id).subscribe(function(entity) {
    let entitySubType = entity.type;
    if (entitySubType === 'therm') {
        openDashboardState('thermometer_state');
    } else if (entitySubType === 'light') {
        openDashboardState('light_sensor_state');
    }
});

function openDashboardState(statedId) {
    let params = {
        entityId: entityId,
        entityName: entityName,
        entityLabel: entityLabel
    };

    widgetContext.stateController.openState(statedId,
        params, false);
}
```

**Comment by sambartle** [comment]
Hi, @ChantsovaEkaterina 

That's a perfect answer, thank you very much for that, I had been struggling for a long time and had come up with a method that partially worked, using a complete reload and some JSON crafting to make the state parameters.. but your way is much much nicer and doesn't require the reload (or hardcoded dashboard addressing)

Thanks,
Sam
