### ISSUE TITLE
Widget preview is cropped in 'Latest telemetry' tab of a device (demo thingsboard)

### ISSUE THREAD

**Issue by forGGe** [thingsboard/thingsboard#487]
SToR:

- Go to https://demo.thingsboard.io/devices
- Create device, push some data.
- Go to 'Latest Telemetry' tab.
- Select any telemetry unit.
- Click 'Show on widget button'.
- Select any bundle from drop-down list.

Expected:

- Widget preview will be maximized

Actual:

- Widget preview is cropped as shown below

![img](https://user-images.githubusercontent.com/5261821/34200719-c5ca279a-e57a-11e7-85d5-4586bf68a449.png)

System details:

```
$ uname -a
Linux Local 4.14.4-1-ARCH #1 SMP PREEMPT Tue Dec 5 19:10:06 UTC 2017 x86_64 GNU/Linux
$ chromium --version
Chromium 63.0.3239.84 
```

**Comment by Terny22** [comment]
This is fixed now in master branch and deployed to demo environment.

**Comment by forGGe** [comment]
> This is fixed now in master branch and deployed to demo environment.

Confirm, thanks!
