### ISSUE TITLE
[Bug] Widget does not show current database content after updated from 3.2.1. to 3.2.2.

### ISSUE THREAD

**Issue by gaizkasi** [thingsboard/thingsboard#4876]
**Describe the bug**
After updated from 3.2.1. to 3.2.2 an 'Entity Widget' in dashboard have stopped showing correct data value from database. It seems to me a bug in the widget because it can't get the current content from database. I try to add again the widget as well as restarting Thingsboard service.

**Your Server Environment**
* own setup
  * Local Infrastructure
  * 3.2.2
  * Ubuntu Server

**Your Client Environment**

**Desktop (please complete the following information):**
* OS: Win10
* Browser: Firefox 
* Version: 89.0.2

**Expected behavior**
It should show database content.

**Screenshots**
![irudia](https://user-images.githubusercontent.com/56073775/124905272-2d468300-dfe6-11eb-8bb5-a02077bb00c7.png)
![irudia](https://user-images.githubusercontent.com/56073775/124905317-36375480-dfe6-11eb-8175-bb6860f1ed43.png)

**Comment by ingegaizka** [comment]
The key in the database screenshot corresponds to the third column in the widget table.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
