### ISSUE TITLE
[Bug] Error using system SMTP settings. SMTP works when configuring manually.

### ISSUE THREAD

**Issue by artturimW** [thingsboard/thingsboard#4877]
**Describe the bug**
When sending email with "send Email" node in rule engine using system SMTP settings, I get failure in "send email" node debug log. 

error:
MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;

Exactly same settings do work when disabling the "Use system SMTP settings" in rule engine "Send Email" node and writing parameters manually. When configuring System SMTP settings and pressing the test email button it does work and sends me a email.

I am using SMTP port 465 and TLS encryption.

For some reason it is trying to connect localhost 25.

My ThingsBoard is running in AWS on swarm mode.

**To Reproduce**
1. Use same system SMTP settings.
2. Send some test email with rule engine "Send email" node and put debug on.
4. See error in debug log

**Screenshots**
![image](https://user-images.githubusercontent.com/86042541/124915475-422d1180-dffa-11eb-9ec2-57bc17d92bd2.png)
(host, user and password sensured)

**Comment by trypzz** [comment]
Hi @artturimW,
Be sure you type 465 port in send email node. Because I trying to reproduce this issue and this works fine for me.

Regards,
Bogdan

**Comment by artturimW** [comment]
Hello,

Can't type in send email node settings when using system SMTP settings. Problem was when using system SMTP Settings. 

Regards,
Artturi

**Comment by artturimW** [comment]
System wide email settings works now after update.

**Comment by artturimW** [comment]
System wide email settings works now after update.
