### ISSUE TITLE
How to include a new map?

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#489]
How to include a new map? :)
When I reconstructed the Baidu map in accordance with the development way of Google map, but there has BMap undefined errors,Google will not.  Outside the google-map.js file,  where else do need to load  Maps API?
Thanks

**Comment by xjz** [comment]
the api of tencent map is similar to google map,it is not difficult to add it based on google map widget in tb

**Comment by ashvayka** [comment]
@xjz 
Do you want to share the code or I should close this?

**Comment by xjz** [comment]
@ashvayka we are thinking about sending a PR after refactoring,for now the code has some hardcode.
