### ISSUE TITLE
[Question] Could login with Windows AD

### ISSUE THREAD

**Issue by jalin168** [thingsboard/thingsboard#4890]
**Component**

 * UI

**Description**
Could  `Windows AD (Active Directory)`  be used to log in to ThingsBoard?

**Environment**

 * OS:  Windows 10 64-bit Pro, version 1803 (Build 17134.1246)
 * ThingsBoard: 3.2.2
 * Browser: Chrome , version 90.0.4430.72 (64 bit)

**Comment by ban2derlog** [comment]
Hi, you can use only Azure Active Directory (Cloud) for this.
Or a custom service that will have requested Endpoints and will have workflow similar to ``auth0`` ©
![image](https://user-images.githubusercontent.com/33271053/184668339-290761eb-4c5f-4d96-a6c2-d31474cc408d.png)
