### ISSUE TITLE
[Question] Failure to find org.thingsboard:dao:ja r:tests:3.3.0-SNAPSHOT 

### ISSUE THREAD

**Issue by loongxing** [thingsboard/thingsboard#4893]
[ERROR] Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:3.3.0-SNAPSHOT: Failure to find org.thingsboard:dao:ja
r:tests:3.3.0-SNAPSHOT in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus
-aliyun has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :application

**Comment by volodymyr-babak** [comment]
@loongxing 
if this is still valid, please provide the command that you are using to build the project, and additionally, please specify your environment - java version, OS etc.
