### ISSUE TITLE
mqttserver.jks

### ISSUE THREAD

**Issue by youhammad** [thingsboard/thingsboard#4902]
**Component**

 * Generic

**Description**
where I should add mqttclient.jks to let thingsboard see him? 

**Environment**

 * OS:  ubuntu and 20.04 LTS
 * ThingsBoard: 3.3.0
 * Browser: chrome

**Comment by faithware** [comment]
It should be copied to /etc/{SERVICE}/conf/ make sure that the thingsboard user has read access to that.

**Comment by trypzz** [comment]
Hi,

Answer provided by @faithware is correct. Clarify, please, do you have additional question relation to this topic?
