### ISSUE TITLE
Two assets with the same name but different customers results in conflict.

### ISSUE THREAD

**Issue by Davidorul** [thingsboard/thingsboard#4907]
Using TB PE 3.2.2 we noticed that the asset name is unique across a whole installation.

e.g.:
Customer 1 creates an asset named "building" or "maschine"
Customer 2 creates an asset with the same name and get's the error: 

<img width="470" alt="image" src="https://user-images.githubusercontent.com/51907992/125632896-ce69079c-95c9-4d89-8ee0-55cf106650b7.png">

What makes this very intransparent for the user is that he himself will probably not have access to the other user's asset thus he will never be able to figure out why there is a naming conflict.

With more and more customers on one server, the conflicts will become more common as asset names usually are quite generic like "building, street, company, machine, etc."

Is there any plan to change this behaviour in the future ?

(Imho the asset name is just that - a name. - It should not be used to *uniquely* identify an asset. For this an ID should rather be used.)

**Comment by LeoMorgan113** [comment]
Hi @Davidorul,

Let me illustrate the next situation:
You have assets with the same name 'Asset1' and 'Asset1' under the different customers.
You, as a tenant, go to the dashboard and choose your asset in alias or you want to use the asset in the Rest API Call.
Which one is correct "Asset1" or "Asset1"? Ambiguous.

That's why you have to set all names unique.

**Comment by Davidorul** [comment]
If I choose an asset in a dashboard (or anywhere else) - I expect only *my* assets to show up. Thus I only get one asset. - Mine.

Why would TB show me assets of a different customer ? I don't even have access to those...

**Comment by LeoMorgan113** [comment]
In the integrations and in the Rest Api Call, dasboards used names, so again if you are under a **tenant**, you can see all assets and all devices of all customers.
So to avoid ambiguity for tenants all names for assets and devices must be unique.

**Comment by Davidorul** [comment]
Hmmm. I see.
It is a bit unfortunate (especially from a user viewpoint) but I understand your reasoning.
Thank you for you explanation !
