### ISSUE TITLE
[Bug] After deleting a gateway created device you need to restart gateway to re-create it.

### ISSUE THREAD

**Issue by fraucamidokura** [thingsboard/thingsboard#4909]
**Describe the bug**
The gateway creates devices automatically. Once create the device could send information to thingsboard. 

If the device is deleted in the console or through API request then that device could not send more information. If I restart again the gateway then that device will be created again.

We would like not to restart the gateway to re-generate the device again.

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard 3.3.0
  * Ubuntu 20.04

**To Reproduce**
1. Send sensor data on a new device to the gateway
2. On Thingsboard the new device appears
3. Delete that device
4. Send sensor data on a device named equal to step 1 to the gateway
5. On Thingsboard the new device does not appear

**Expected behavior**
We expect that on step 5 the device appears again

**Comment by volodymyr-babak** [comment]
@fraucamidokura 
thanks for bringing this problem up, this is fixed in the latest 3.3.3 version:
https://github.com/thingsboard/thingsboard/releases/tag/v3.3.3

* Notify IoT gateway about delete or rename of the device;
