### ISSUE TITLE
Thingsboard as Leshan adopter

### ISSUE THREAD

**Issue by sbernard31** [thingsboard/thingsboard#4913]
Hi,

I see your are using Leshan in thingsboard.

As main maintainer of Leshan project, I would like to know if you would accept to be added [Leshan adopters](https://iot.eclipse.org/adopters/#iot.leshan).

You can also post a comment at : https://github.com/eclipse/leshan/issues/830

Any feedback about Leshan is welcome too. (you can use this issue or open a new one on Leshan repository)

(By the way, I see you are using californium too so maybe you could be added as Californium adopters too ?)

**Comment by ashvayka** [comment]
Hi @sbernard31, yes, we accept to be added to Leshan and Californium adopters. We hope you are ok if we mention Leshan or Califorinum in our documentation or architecture page.

**Comment by sbernard31** [comment]
> We hope you are ok if we mention Leshan or Califorinum in our documentation or architecture page.

It's totally OK to me.  I guess @boaks (main Californium maintainer) too :-)

> we accept to be added to Leshan and Californium adopters.

I created the corresponding PR : https://github.com/EclipseFdn/eclipsefdn-project-adopters/pull/108

Thx :pray:

**Comment by boaks** [comment]
> We hope you are ok if we mention Leshan or Califorinum in our documentation or architecture page.

Sure, go for it.

Just to mention: 
[Californium 2.6.4](https://github.com/eclipse/californium/issues/1667) was released today.

**Comment by sbernard31** [comment]
Done for Californium : https://iot.eclipse.org/adopters/#iot.californium
And Leshan : https://iot.eclipse.org/adopters/#iot.leshan
