### ISSUE TITLE
cannot uncheck hide home toolbar[Bug] 

### ISSUE THREAD

**Issue by glenosborne** [thingsboard/thingsboard#4926]
**Describe the bug**

**Your Server Environment**
docker PE 3.2 localhost:8080
windows 10

**Your Client Environment**
windows 10 
chrome latest

**To Reproduce**
create a customer and try to change home show toolbar to yes by unchecking the box 
![image](https://user-images.githubusercontent.com/58960596/126083863-162ee81e-487b-4d7d-9638-d1053a30b45b.png)

**Expected behavior**
toolbar to visable to user when home nav is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/58960596/126083883-faa3dffc-75d0-4de4-96fa-09777847f978.png)

**Additional context**
loged in at client as admin, is customer of tenant admin

**Comment by ban2derlog** [comment]
Hi, do you try to set Home Dashboard field before setting checkbox?
![image](https://user-images.githubusercontent.com/33271053/184674431-36ffc16e-cb70-4b78-b526-d6627eeb6069.png)
