### ISSUE TITLE
[Question] How to use json value in postFunc with aggregation value in timeseries line chart

### ISSUE THREAD

**Issue by lwd369** [thingsboard/thingsboard#4927]
**Component**
 * UI

**Description**
I have a telemetry data like this:
``` json
{
  "battery": {
    "temperature": 25.0,
    "percent": 0.5
  },
  "state": "working",
  "others": "..."
}
```

And I can extract the `temperature` value  in latest value widget using post function like  #3017 posted:

```
let temp = JSON(value).temperature;
if (temp) return temp;
return value;
```

But if I am using timeseries line chart widget, which have a AVG aggregation.  Then the `value` in post processing function will always be `NAN`.

I found in [data-aggregator.ts](https://github.com/thingsboard/thingsboard/blob/d991376f44ff16005e8ba6111891c6e7a3efaa5d/ui-ngx/src/app/core/api/data-aggregator.ts#L411) the convert function will convert json string to `NAN`.

Is there any solutions, or the only way is flat my data format?

By the way, can I set the aggregation to 'NONE' in system widget setting?

**Environment**
 * OS:  CentOS 8.3
 * ThingsBoard: 3.2.3-Release
 * Browser: Chrome mac 91.0.4472.114

**Comment by dhaval2017** [comment]
By the way, can I set the aggregation to 'NONE' in system widget setting?

are you looking for something like this use widget time window instead of dashboard time window?

![image](https://user-images.githubusercontent.com/33371842/126147183-0d9982aa-6c04-4318-a1da-a75a3a4e8851.png)

**Comment by lwd369** [comment]
@dhaval2017 

I am not found this option.

I set the aggregation function to None, and the post processing function works!  And the widget still shown the avg value 😂.

Thank you for your help!!

**Comment by dhaval2017** [comment]
send me hello on dhaval@nistantritech.com
If needed I will help you with custom widget to solve your query else setup widget on your dashboard

**Comment by ubIQio** [comment]
@dhaval2017 thanks so much this fixed my problem too!
