### ISSUE TITLE
Install thingsboard from build source on mac 

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#493]
**I have builded  thingsboard successfully. After that how to install thingsboard  to mac os. please guide me to install. What are the steps need to do. Thanks**

**Comment by mp-loki** [comment]
Installation on Mac OS should similar to installation on Linux, just make sure to replace apt-get or youm calls with homebrew command or whatever the Mac OS package manager you use.

https://thingsboard.io/docs/user-guide/install/linux/

**Comment by leeching6070** [comment]
how to replace ( sudo dpkg -i thingsboard-1.4.deb) command on mac?
