### ISSUE TITLE
[Feature Request] Shared seperate axis for multiple data sources

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#4930]
To have better control over the graphs, user should be able to create multiple Y-axis's, and then to assign data sources to them. 

This will allow for a graph to have for example 2 humidity sensors, 2 temperature sensors and to have only 2 Y-axis.

currently, only the main y axis can be shared, and once you separate a data source to its own axis, it cannot be used by a 2nd data source.

To implement this, in the widget main settings, just like you can add multiple thresholds, you can create mutiple axis, define them and then assign them to the data source.

hope this makes sense

Regards

@

**Comment by pon0marev** [comment]
In the latest versions, you can configure multiple Y axes:
https://github.com/thingsboard/thingsboard/issues/5810#issuecomment-2402609443
