### ISSUE TITLE
[Question] How to get new Data from ODBC-views 

### ISSUE THREAD

**Issue by m4ld3** [thingsboard/thingsboard#4942]
**ODBC-Connector**

 * odbc.json

**Description**
Hi,
I have a test-share from a building management system via ODBC (postgresql on the BMS). The connection to the database runs fine. The share consits of 11 rows (measurement site) with 10 coloums: 

plaintext (name of measurement site), 
adress (BACnet-Address)
site (uninteresting)
node (uninteresting)
unit (uninteresting)
device-adress
adress-type (uninteresting)
protocol_type (uninteresting)
timestamp
value. 

The table is a collection of 11 views, so it has no primary key and there will be no further rows. The problem is, that no data gets fetched. There are no errors in tb_connection (IoT-Gateway runs fine). 

connector.log:
> ""2021-07-21 10:00:24" - INFO - [odbc_connector.py] - odbc_connector - 227 - [ODBC Connector] Polling iteration finished. Processed rows: current 0, total 0"

odbc.json:                                                                                               

 {
   "connection": {
     "str": "Driver={postgresql};Server=xxx.yyy.de;Port=5432;Database=gltdb;Uid=xxx;Pwd=xxx;",
     "attributes": {
       "autocommit": true,
       "timeout": 0
     },
     "encoding": "utf-8",
     "decoding": {
       "char": "utf-8",
       "wchar": "utf-8",
       "metadata": "utf-16le"
     },
     "reconnect": true,
     "reconnectPeriod": 60
   },
   "pyodbc": {
     "pooling": false,
     "native_uuid": true
   },
 
   "polling": {
     "query": "SELECT plaintext, address, device_address, timestamp, value FROM gltexp001.current_values WHERE value > ?",
     "period": 30,
     "iterator": {
       "column": "value",
       "query": "SELECT * FROM gltexp001.current_values",
       "save": false
     }
   },
   "mapping": {
     "device": {
       "type": "odbc",
       "name": "'GLT_ ' + plaintext"
     },
     "sendDataOnlyOnChange": false,
     "timeseries": "*"
   },
   "serverSideRpc": {
     "enableUnknownRpc": false,
     "methods": [
     ]
   }
}

 

My Suggestion is, that it may be the iterator-section which causes problems. As it is described in the documentation ([https://thingsboard.io/docs/iot-gateway/config/odbc/](url)) the subsection is mandatory (means neccessary). Should the iterator-section be disabled? The aim is to get plaintext, adress, device_adress and timestamp from all 11 rows (measurement sites) at one time.  From the documentation:

> **IMPORTANT**

> The main challenge of the iterator feature is to unambiguously figure out whether to restore iterator data from a previous 

> gateway work session or to use values from the connector configuration file.

I don't think that the iterator should be restored when I want to get the new values from all views. Should it be disabled? So the Iteator-section is described but disabled? How can it be disabled (if neccessary). 

I hope the description helps. Thank you very much!

**Environment**

 * OS:  Ubuntu 20.04.2 LTS
 * ThingsBoard: version 3.2.2PE-1
 * Python3 Thingsboard-gateway  2.6-1
 * Browser: Firefox 89.0.2 (64-Bit)

**Comment by volodymyr-babak** [comment]
@m4ld3 
If this is still a valid ticket, please create a ticket on the gateway repository https://github.com/thingsboard/thingsboard-gateway, because this issue is not related to the ThingsBoard IoT platform. Thanks!
