### ISSUE TITLE
Thingsboard Installlation failed on 14.0.4 ubuntu

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#495]
### but I getting following error : Thanks
 _===================================================_
 :: ThingsBoard ::       ### ### (v1.4.0-SNAPSHOT)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema...
Installing Cassandra DataBase schema...
Unexpected error during ThingsBoard installation!
com.datastax.driver.core.exceptions.SyntaxError: line 1:7 no viable
alternative at input 'MATERIALIZED' ([CREATE] MATERIALIZED...)
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
        at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
        at
com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at
com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
        at
org.thingsboard.server.service.install.CassandraDatabaseSchemaService.lambda$loadCql$0(CassandraDatabaseSchemaService.java:58)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at
org.thingsboard.server.service.install.CassandraDatabaseSchemaService.loadCql(CassandraDatabaseSchemaService.java:58)
        at
org.thingsboard.server.service.install.CassandraDatabaseSchemaService.createDatabaseSchema(CassandraDatabaseSchemaService.java:52)
        at
org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:118)
        at
org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at
org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:7 no
viable alternative at input 'MATERIALIZED' ([CREATE] MATERIALIZED...)
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
        at
com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
        at
com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
        at
com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
        at
com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
        at
com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
        at
com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
        at
com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
        at
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at
io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
        at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
        at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
        at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at
io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:961)
        at
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
        at
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at java.lang.Thread.run(Thread.java:748)
Unexpected error during ThingsBoard installation!
ThingsBoard DB installation failed!

**Comment by ashvayka** [comment]
I assume you are using old Cassandra version
