### ISSUE TITLE
[Question] RPC getValue proper response

### ISSUE THREAD

**Issue by pedroply** [thingsboard/thingsboard#4954]
RPC

Generic

When using a widget that offers RPC from server to device with the ability to retrieve "on/off value" "using call RPC getValue method" I cannot send a proper response to the server from the device where the widget updates to the desired state. 
The widget stops requesting the getValue method when I send a response but it does not update its state accordingly.
I have tried the following response bodies:
 - {"method":"getValue","params":true}
 - {"method":"getValue","params":{"value":true}}
 - {"value":true}
 - true
But without any luck. 

When testing the RPC functionality with the RPC debug terminal I can see the device response as expected.

 OS:  Ubuntu 20.04
 ThingsBoard: v3.2.2
 Browser: Google Chrome 92.0.4515.107

**Comment by vvlladd28** [comment]
Hi @pedroply,
Maybe you have such an issue #4311?
If so, this will be fixed in TB3.3.0. You can also build from source to get fix faster.
