### ISSUE TITLE
GPIO control over MQTT using ThingsBoard

### ISSUE THREAD

**Issue by kathornton01** [thingsboard/thingsboard#4961]
Hello,
I've been trying to use this tutorial (https://thingsboard.io/docs/samples/raspberry/gpio/) to control a simple LED (on/off). I have tested the LED to make sure it works (and works on the RPi), but when I try to control it via the Thingsboard Dashboard widget, nothing happens. I know my RPi is receiving the message, as I get the following messages:

_After running "python gpio.py":_
   Connected with result code {'session present': 1}

_After turning on Pin 12 on Thingsboard widget:_
   Topic: v1/devices/me/rpc/request/183
   Message: {"method":"setGpioStaatus","params":{"pin":12,"enabled":true}}

_After turning off Pin 12 on Thingsboard widget:_
   Topic: v1/devices/me/rpc/request/184
   Message: {"method":"setGpioStaatus","params":{"pin":12,"enabled":false}}

Does anyone know what the problem might be, or could anyone suggest something I could try?

Thank you!!

**Comment by kathornton01** [comment]
Edit: Got it to work. Didn't change anything except the hardware -- got a new resistor and new LED and it worked immediately. I tested the LED and resistor before to make sure they were working, and they were, so not sure why this made a difference, but thought I'd update this anyway.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
