### ISSUE TITLE
[Bug] OAuth2 Button not showing up

### ISSUE THREAD

**Issue by andrea-kyurchiev** [thingsboard/thingsboard#4968]
The oAuth2 config button isn't appearing when logged in as sysadmin. Version is 3.0.1 and oAuth2 is enabled in the config. I was trying to set up Auth0 as shown in the documentation
![Untitled](https://user-images.githubusercontent.com/77273562/126789163-d7fe62df-fbe4-456e-8779-e16dbbb13e83.png)

**Comment by vvlladd28** [comment]
Hi @andrea-kyurchiev,
This function is added in [TB 3.2.0](https://github.com/thingsboard/thingsboard/releases/tag/v3.2)
