### ISSUE TITLE
Thingsboard_Public dashboard data loading error

### ISSUE THREAD

**Issue by abhishekavl** [thingsboard/thingsboard#4974]
Thingsboard UI - Community edition

**Environment**
 * OS:  Window10 x64
 * ThingsBoard: version 3.2.2
 * Browser: Google crome
 * Database : Postgresql 13.3.2
 Problem : I have made a dashboard & made it public. It is working on local host. but when I am using Public url of that dashboard then dashbaords opens but data does not display on the trends. 
Please refer the snap
![Thingsboard_Public dashboard data loading error](https://user-images.githubusercontent.com/87922855/126906303-95e67922-d2d2-4dea-a461-e6cf4e71c30b.jpg)
![Thingsboard_Public dashboard data loading error](https://user-images.githubusercontent.com/87922855/126906323-7d1e73d7-e4c6-4237-b359-74d3a9d974f5.jpg)
 attached for more clearly. 

Please support ton resolve the same. 
Thanks in advance for the same.

**Comment by Backdraft007** [comment]
Hey,
is the device also public?

**Comment by abhishekavl** [comment]
Hi, 
Device was not public. Earlier, I have tried to make it public but option was not enable as this was assigned to customer - A. 
I have removed the same from customer-A and made it public. Now it is working fine & can view public url of dashboard on same PC and other PC also connected on same network. 
Thanks a lot for the input & support

Regards
Abhishek
