### ISSUE TITLE
[Feature Request] Change credentials type in device provisioning

### ISSUE THREAD

**Issue by jlikeme** [thingsboard/thingsboard#4975]
**Is your feature request related to a problem? Please describe.**
We set provision strategy of device profile to `Check for pre-provisioned devices`, because we want to use bulk provisioning to create pre-provisioned devices. In this situation, we can only get credentials of pre-provisioned devices that has setted in thingsboard. However, we want devices to supply X.509 Certificate. 

**Describe the solution you'd like**
When the device hasn’t been provisioned yet, allowing devices to change credentials type and supply tokens or certificates in device provisioning, just like `Allow to create new devices` provision strategy.

**Describe alternatives you've considered**

**Additional context**

**Comment by vvlladd28** [comment]
Hi @gao270615179,
This functional in active development and TB 3.3.1 we are added this request
