### ISSUE TITLE
<IDEAS> These are some typical implementation aspects 

### ISSUE THREAD

**Issue by ChSM56** [thingsboard/thingsboard#498]
Here is my typical debate point in many platforms/products and specifically here with **# thingsboard:**

The Ownership, Tenancy and User permission - How are they related to each other?
I was exploring to understand and hit the usual black hole I am used to in many instances. I am working on an instance in my local installation and with default installed data.

So goes the sequence of events :-

1.  Created a Device with a tenant - a Sensor dht22 model that sends Temperature and Humidity data with device name - SN-001 (reused from examples)

2.  Created a Dashboard and named it as Weather in my balcony - screenshot attached

![image](https://user-images.githubusercontent.com/29800826/34402784-00fad788-ebca-11e7-8092-d832f4ad25ba.png)

3. I assigned the Dashboard to "Customer A"
4. A user is created to the above Customer.
5. I logged in as the user of "Customer A" and opened the Dashboard. **My expectation was to be able to see the dashboard with the data.**  It was not the case.

**So, the questions is - if the data does not go with dashboard, it is just the artifact but not data that is assigned. How useful it is to assign ? Do we need a separate flow for assigning the artifacts and actual data? How does one expect a end user to be familiar with such artifacts and their use? May be while displaying the Dashboards to a end user role, the system should apply a filter if a Dashboard has a data source associated or NOT and display only those that have a data source?**

6. Then I logged in another browser and assigned the Device - SN-001" to "Customer-A"
7. The Dashboard does not immediately start showing the data. 
8. I have to go back and start the dashboard again to see the data.
So far so good.

9. Now, I unassigned the dashboard from the Customer-A.

![image](https://user-images.githubusercontent.com/29800826/34403358-b8dff9fc-ebcd-11e7-8519-b7695ec0f260.png)

10. My expectation is the User would No More see the Dashboard. No the user continues to see the data. 
11. The user loses the data only but continues to see the Dashboard on the page Refresh in the same session of Logged In.
12. Then I unassigned the Device from Customer.
13. The Dashboard still continues to see the data 

![image](https://user-images.githubusercontent.com/29800826/34403421-26069c84-ebce-11e7-8999-d19556761bab.png)

So, the Consequential question - On Assignment of a device to a Customer, is the Historic data of the Device Also accessible to the user?

**_Further, the Assignment screen shows Check Boxes, which means I should be able to assign to multiple Customers but it is Not the case. Especially, if it is Artifact assignment it is more important.** 

IMHO:
The product in implementing the tenancy, needs to address the aspect of Time dimension of an Entity Association with the Role on the Platform has to be factored in.

Thnaks & Regards

PS: I am very greatly impressed with the product and the journey of making it as open source on Apache T&C.

**Comment by ashvayka** [comment]
Hi @ChSM56 . When you assign the dashboard to the customer you also need to assign some devices to the customer as well. Generally speaking, you need to assign both. The fact that when you un-assign the dashboard a user need to re-login is probably a bug, but I believe it is a low priority.

Assignment to multiple customers is not ready yet.
The time dimension aspect is certainly valid use case, we will enable it in the new rule engine.

**Comment by ChSM56** [comment]
Hi @ashvayka 
Sorry for any confusion on re-login, it was navigation back and re-entry to Dashboard.

Do I close this Issue or do I post it elsewhere?

Thanks & Regards

**Comment by ChSM56** [comment]
Hi @ashvayka

Here is another anomaly that I noticed and does not a solution.

After a successful login, the Session is ****_NEVER EXPIRED_**.** 

I noticed that logged in session continued even after -
1. Browser Closed and Reopend
2. Platform Server Restarted
3. Server Restarted

Is that a feature by design? 

IMHO -
It is preferred to have a session expiry duration setting at Tenant level, if not at application level as a WebServer (Tomcat) setting.

Thanks & Regards

**Comment by ChSM56** [comment]
Another area of Observation is on the UI aspect.
I noticed an earlier discussion of implementation of Themes as well. It is definitely Good to have support of themes. However, an earlier part to themes (at least similar stages were like Yahoos ) is 
Personalisation.

What it can cover is :

1. List views as well as Card view to the managent screens of Devices, Customers, Assets that have a high potential to have hundreds to be listed (I practically had done the other way of First List and then implemented Card view in the case of EMM - Enterprise Mobility Management platform or MDM - Mobile Device Management).

2. The Navigational aspect of the Left side menu positioning on the Top as well as in Small size for both left side and at top

3. The choice of placing a few smaller aspects of Customer Logo and Company Address so that the users are continued to attach their work with the platform ti their employer In an Enterprise implementation, this plays a very key role for selection criteria.

4. Assets may be labelled for Region and a separate Entity for Asset covering the aspects of ID, Mfd Year,  Location, Owner, Assignee, (with Customer organizational Hierarchy) 

5. We also need an Import from a local file for Entities to save time and get going faster with the platform where the number of items in an Entity is high, (A learning from EMM/MDM for that matter any Enterprise App)
