### ISSUE TITLE
[Question] ThingsBoard PE 3.2.2 global styling overridden in widget editor

### ISSUE THREAD

**Issue by JaMurphSmi** [thingsboard/thingsboard#4982]
I am currently on PE 3.2.2 and my team have tried to apply stylings to our site to align it more with our company's look and feel. When adding this CSS however, it appears that the styling for the widget code editor has been overridden, and it is now very difficult to use eg below where editing will occur 7-8 spaces behind where the cursor is, per the red arrow
![image](https://user-images.githubusercontent.com/22885637/127126213-5e6ecd91-6397-4dd3-98c1-d1bf78905aea.png)

Is there any stylesheet available that we can add to the global styling to get the proper styling back in the editor?

**Comment by mde2017** [comment]
I'm experiencing the same issue, with no solution yet:
#3934

**Comment by LeoMorgan113** [comment]
Hi @mde2017,

As far as you have the same issue as #3934, I'll repeat the answer:
_I've checked this and added task to ThingsBoard backlog, our developers will review this bug, but there’s no exact timeframe for this. If you would like to know the progress on this ticket, you can create another ticket on Jira with the production ticket number mentioned ( PROD-1138 ), and we’ll gladly update you on the ticket’s stage._
