### ISSUE TITLE
[Bug] Infinite loading bar

### ISSUE THREAD

**Issue by JaMurphSmi** [thingsboard/thingsboard#4988]
I am on ThingsBoard PE 3.2.2 and there are many times where I perform some actions in the UI, and in response the loading bar will begin to cycle, but it will not disappear.

When this happens all edit, save and delete options are unavailable, and can very quickly make ThingsBoard unusable. This would be a very important thing to fix, as it quickly impacts the user's experience.

![image](https://user-images.githubusercontent.com/22885637/127314659-723661f0-878b-4e7a-8a0f-98f5031e0f81.png)

**Comment by LeoMorgan113** [comment]
Hi @JaMurphSmi,

I recommend you upgrade to the newest release, this issue must be fixed.
