### ISSUE TITLE
thingsboard.service failed.

### ISSUE THREAD

**Issue by EchoXBR** [thingsboard/thingsboard#499]
I Follow the installation instructions，finally remind me failed
Here is the log

/bin/systemctl status  -l thingsboard.service
● thingsboard.service - thingsboard
   Loaded: loaded (/usr/lib/systemd/system/thingsboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 四 2017-12-28 14:40:22 CST; 46min ago
  Process: 19718 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
 Main PID: 19718 (code=exited, status=1/FAILURE)

12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337)
12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
12月 28 14:40:22 Echo thingsboard.jar[19718]: at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36)
12月 28 14:40:22 Echo thingsboard.jar[19718]: ... 8 more
12月 28 14:40:22 Echo systemd[1]: thingsboard.service: main process exited, code=exited, status=1/FAILURE
12月 28 14:40:22 Echo systemd[1]: Unit thingsboard.service entered failed state.
12月 28 14:40:22 Echo systemd[1]: thingsboard.service failed.

**Comment by EchoXBR** [comment]
https://thingsboard.io/docs/user-guide/install/linux/#hardware-requirements
My system is CentOS7

**Comment by EchoXBR** [comment]
Actually I don't konw where can I find detial error log.

**Comment by ChSM56** [comment]
I set up Thingsboard on Centos 7 recently.
My experience where it can be useful to your context :
1. Just check if you ran - 
    Run installation script - sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo after making the choice of your persistence storage
2. Could you do this successfully after the above ?
    service thingsboard start 
3. Please check if port - 8080 is in use by any other process?
   ss -ntlp | grep 8080 whould show you this.

May be a reinstall would solve the problem.

I could Install it and run it on Centos 7.

**Comment by EchoXBR** [comment]
thanks very much
this is my first ask questions online and first received recovery so happy. :)

When I follow the instructions, running the installation script is successful
I just ran the installation script again, and this failed without error log ,just print ThingsBoard installation failed!

8080 no user;

Myserver is aliyun's  CentOS 7 
In this "/etc/thingsboard/conf/thingsboard.yml" file I saw same keyword about mqtt/Zookeeper/ etc. Is MyServer need those environment? I just configure it step by step
1.JDK8
2.Postgresql install and config and run it. Now MyServer's postgersql can be remote access
3.thingsboard server install.
4.Memory update for slow machines (1GB of RAM)
5.run installation script .first is success, reinstall failed. PS (reinstall error without error log)
6.start thingsboard server failed.

**Comment by ChSM56** [comment]
Please check your postgresql password to contain No Special characters. I had problems with it as my password had @ . Also I assume you ran --loadDemo script to load the data.

**Comment by vparomskiy** [comment]
You can find more information on log file. It is located in
/var/log/thingsboard/

**Comment by Fiberstore** [comment]
I also aliyun， My host is ubantu sys，Error log display ：2018-02-09 10:09:32,464 [main] ERROR o.a.coyote.http11.Http11NioProtocol - Failed to start end point associated with ProtocolHandler [http-nio-120.77.45.163-8001]
2018-02-09 10:09:32,465 [main] ERROR o.a.catalina.core.StandardService - Failed to start connector [Connector[HTTP/1.1-8001]]
2018-02-09 10:09:32,567 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter -
Whether it is changed to 8080 or 8001 It's all this mistake

**Comment by vparomskiy** [comment]
Install instructions were changed since Thingsboard v2.x so this issue is actual anymore. Closing it.
