### ISSUE TITLE
[Question] Upgrading from Community to Professional Edition

### ISSUE THREAD

**Issue by DanieleCampanaro2000** [thingsboard/thingsboard#4990]
**Component**

 * Installation

**Description**
Hi! I'm a developer and I'm going to upgrade by Thingsboard instance from Community Edition to Professional Edition. I need some information about this process. I've found this guide (https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/)... can I follow it in order to do the upgrading? And next, Will my datas (devices, assets, dashboards...) be preserved during the upgrading?

Thanks a lot

**Environment**

 * OS:  Linux 20.04 LTS
 * ThingsBoard: Thingsboard CE 3.2.2 self-hosted on my server

**Comment by vvlladd28** [comment]
Hi, @DanieleCampanaro2000,
Yes, this is correct instruction. Your will save TB data.

**Comment by t0mmyz7** [comment]
@vvlladd28 it is possible to upgrade from CE to PE ?

**Comment by DanieleCampanaro2000** [comment]
ok, thanks a lot for the answers.
I've done the upgrade today and everything worked flawlessy.
