### ISSUE TITLE
build error: org.thingsboard.server.extensions.core.plugin.telemetry.gen.TelemetryPluginProtos does not exist

### ISSUE THREAD

**Issue by hguomin** [thingsboard/thingsboard#50]
Hi, 

I clone the thingsboard code, import it into intellij IDEA maven project and build it, everything is ok but when building the extensions-core module there is error occurs, as following:

Error:(28, 1) java: package org.thingsboard.server.extensions.core.plugin.telemetry.gen.TelemetryPluginProtos does not exist
Error:(155, 20) java: cannot find symbol
  symbol:   class SubscriptionUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(180, 40) java: cannot find symbol
  symbol:   class SubscriptionUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(202, 13) java: cannot find symbol
  symbol:   class AttributeUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(232, 42) java: cannot find symbol
  symbol:   class AttributeUpdateValueListProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler

Any idea to fixed this build issue? thanks.

**Comment by hguomin** [comment]
Hi, 

I clone the thingsboard code, import it into intellij IDEA maven project and build it, everything is ok but when building the extensions-core module there is error occurs, as following
===================================================================
Error:(28, 1) java: package org.thingsboard.server.extensions.core.plugin.telemetry.gen.TelemetryPluginProtos does not exist
Error:(155, 20) java: cannot find symbol
  symbol:   class SubscriptionUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(180, 40) java: cannot find symbol
  symbol:   class SubscriptionUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(202, 13) java: cannot find symbol
  symbol:   class AttributeUpdateProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
Error:(232, 42) java: cannot find symbol
  symbol:   class AttributeUpdateValueListProto
  location: class org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRpcMsgHandler
===================================================================

Any idea to fixed this build issue? thanks.

**Comment by ashvayka** [comment]
This is related to auto-generated code based on protobuf structures. Please add the generated source code manually in IDEA. Folder location: extensions-core/target/generated-sources/protobuf/java

**Comment by hguomin** [comment]
@ashvayka thank you, I have fixed the build.

**Comment by hguomin** [comment]
@ashvayka Hi, Andrew, I still experience the similar build error in application module:

Error:(28, 42) java: cannot find symbol symbol:   class ClusterRpcServiceGrpc location: package org.thingsboard.server.gen.cluster

I checked the folder application\src\main\proto, it seems that there is no proto file for class ClusterRpcServiceGrpc, is this file missing? thanks.
