### ISSUE TITLE
Cannot start thingsboard

### ISSUE THREAD

**Issue by hpham04** [thingsboard/thingsboard#500]
I followed this guideline https://thingsboard.io/docs/user-guide/install/docker/ to start but it failed
The following is the log file:
docker-compose up tb
Starting thingsboard_tb_1 ... 
Starting thingsboard_tb_1 ... done
Attaching to thingsboard_tb_1
tb_1         | (Reading database ... 25247 files and directories currently installed.)
tb_1         | Preparing to unpack /thingsboard.deb ...
tb_1         | Not running (process 90). Removing stale pid file.
tb_1         | Unpacking thingsboard (1.3.1-1) over (1.3.1-1) ...
tb_1         | Setting up thingsboard (1.3.1-1) ...
tb_1         | Creating 'Thingsboard' schema and system data...
tb_1         |  ===================================================
tb_1         |  :: ThingsBoard ::       (v1.3.1)
tb_1         |  ===================================================
tb_1         | 
tb_1         | Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
tb_1         | ThingsBoard installation failed!
tb_1         | #
tb_1         | # Copyright © 2016-2017 The Thingsboard Authors
tb_1         | #
tb_1         | # Licensed under the Apache License, Version 2.0 (the "License");
tb_1         | # you may not use this file except in compliance with the License.
tb_1         | # You may obtain a copy of the License at
tb_1         | #
tb_1         | #     http://www.apache.org/licenses/LICENSE-2.0
tb_1         | #
tb_1         | # Unless required by applicable law or agreed to in writing, software
tb_1         | # distributed under the License is distributed on an "AS IS" BASIS,
tb_1         | # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
tb_1         | # See the License for the specific language governing permissions and
tb_1         | # limitations under the License.
tb_1         | #
tb_1         | 
tb_1         | export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb"
tb_1         | export LOG_FILENAME=thingsboard.out
tb_1         | export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
tb_1         | export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql
tb_1         | export LANG='C.UTF-8'
tb_1         | export HOSTNAME='135eec7df0b7'
tb_1         | export JAVA_HOME='/docker-java-home/jre'
tb_1         | export CASSANDRA_URL='cassandra:9042'
tb_1         | export CASSANDRA_HOST='cassandra'
tb_1         | export COAP_BIND_PORT='5683'
tb_1         | export JAVA_VERSION='8u141'
tb_1         | export COAP_BIND_ADDRESS='0.0.0.0'
tb_1         | export PWD='/'
tb_1         | export ZOOKEEPER_URL='zk:2181'
tb_1         | export HOME='/root'
tb_1         | export POSTGRES_PORT='5432'
tb_1         | export DATABASE_TYPE=' cassandra'
tb_1         | export ADD_SCHEMA_AND_SYSTEM_DATA='true'
tb_1         | export CA_CERTIFICATES_JAVA_VERSION='20170531+nmu1'
tb_1         | export JAVA_DEBIAN_VERSION='8u141-b15-1~deb9u1'
tb_1         | export no_proxy='*.local, 169.254/16'
tb_1         | export MQTT_BIND_PORT='1883'
tb_1         | export ADD_DEMO_DATA='false'
tb_1         | export SHLVL='1'
tb_1         | export MQTT_BIND_ADDRESS='0.0.0.0'
tb_1         | export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
tb_1         | export POSTGRES_HOST='postgres'
tb_1         | export CASSANDRA_PORT='9042'
tb_1         | export _='/usr/bin/printenv'
tb_1         | export LANG='C.UTF-8'
tb_1         | export HOSTNAME='135eec7df0b7'
tb_1         | export JAVA_HOME='/docker-java-home/jre'
tb_1         | export CASSANDRA_URL='cassandra:9042'
tb_1         | export CASSANDRA_HOST='cassandra'
tb_1         | export COAP_BIND_PORT='5683'
tb_1         | export JAVA_VERSION='8u141'
tb_1         | export COAP_BIND_ADDRESS='0.0.0.0'
tb_1         | export PWD='/'
tb_1         | export ZOOKEEPER_URL='zk:2181'
tb_1         | export HOME='/root'
tb_1         | export POSTGRES_PORT='5432'
tb_1         | export DATABASE_TYPE=' cassandra'
tb_1         | export ADD_SCHEMA_AND_SYSTEM_DATA='true'
tb_1         | export CA_CERTIFICATES_JAVA_VERSION='20170531+nmu1'
tb_1         | export JAVA_DEBIAN_VERSION='8u141-b15-1~deb9u1'
tb_1         | export no_proxy='*.local, 169.254/16'
tb_1         | export MQTT_BIND_PORT='1883'
tb_1         | export ADD_DEMO_DATA='false'
tb_1         | export SHLVL='1'
tb_1         | export MQTT_BIND_ADDRESS='0.0.0.0'
tb_1         | export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
tb_1         | export POSTGRES_HOST='postgres'
tb_1         | export CASSANDRA_PORT='9042'
tb_1         | export _='/usr/bin/printenv'
tb_1         | Starting 'Thingsboard' service...
tb_1         | Started [99]
tb_1         | 	at java.lang.reflect.Method.invoke(Method.java:498)
tb_1         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
tb_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
tb_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
tb_1         | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
tb_1         | Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
tb_1         | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
tb_1         | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
tb_1         | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
tb_1         | 	... 16 common frames omitted
^CGracefully stopping... (press Ctrl+C again to force)
Stopping thingsboard_tb_1 ... done

Could you please advise how to overcome this issue
Thank you so much

**Comment by ashvayka** [comment]
You have something launched and occupied the 8080 port. This prevents service to start.
