### ISSUE TITLE
Problem: Multiple Users Trying to Control Same Motor on Dashboard Simultaneously

### ISSUE THREAD

**Issue by kathornton01** [thingsboard/thingsboard#5010]
**Component**
 * Generic

**Description**
(I am trying to find the best way to solve this problem on Thingsboard, if possible. But, if it cannot be done with Thingsboard, I'm open to using something else and integrating the Thingsboard dashboard). 

I am currently working on a project where I will have a public dashboard that will display sensor data as well as control a motor, all connected to a Raspberry Pi. This setup will be used in a remote lab for college students, where they will be able control the motor (a fan) and record data. However, since we have multiple students, we foresee a problem with controlling the motor -- what happens if multiple students are on the dashboard at the same time, and each tries to control the fan? Presumably this will cause errors, especially if one student is trying to increase the RPM of the fan, while another is trying to decrease it. 

The solution we thought of to solve this error was to have a time slot sign up form for the students, and based on the time slot they choose, they will get a one time password for the Thingsboard dashboard that will only work for their slot. So, if student A chooses 12:05-1pm, and student B chooses 1:05-2pm, student A will get a password that will only work between 12:05 and 1pm, and at 1pm would lock the student out of the dashboard. This way, we can ensure that only one student is ever on the dashboard at a time, so that we'll never run into the issue of having multiple people trying to control the same motor and sending it mixed signals. 

Does anyone know of a way we might be able to achieve this? The idea we had was that we could make a google form or something and manually create and give out passwords for each time slot, but we aren't sure how we would go about locking the dashboard with a password, let alone having it only respond to certain passwords at certain times -- and on top of that, kicking a student off the dashboard after said time. 

Is this even possible? And if it isn't, is there a different solution for this problem? I can't imagine that no one has ever run into this problem before -- where multiple people are trying to control the same device on a dashboard -- but my Google searches haven't returned anything so I'm not sure.

Thank you so much for your help!

**Environment**
 * OS:  RPi using Raspbian and personal computer using macOS Big Sur 
 * ThingsBoard: Free community version (not secure, http)
 * Browser: Firefox

**Comment by vvlladd28** [comment]
Hi @kathornton01, 
This can be implemented in TB PE. You will need to schedule events that will be referenced in a chain of rules (the originator will be the group/user who must access the schedule). You will need to create at least two groups of users with different rights, one group will have access to control, and all the others will not have access or read access.

After that, you can catch it and change the group of users according to the chain of rules (you will need two groups, one that gives the right to change attributes, and the other will not). You will need to move users from the groups that have the rights to control to another group, and the group / user who let the originator move to this group

**Comment by kathornton01** [comment]
> Hi @kathornton01,
> This can be implemented in TB PE. You will need to schedule events that will be referenced in a chain of rules (the originator will be the group/user who must access the schedule). You will need to create at least two groups of users with different rights, one group will have access to control, and all the others will not have access or read access.
> 
> After that, you can catch it and change the group of users according to the chain of rules (you will need two groups, one that gives the right to change attributes, and the other will not). You will need to move users from the groups that have the rights to control to another group, and the group / user who let the originator move to this group

Thank you so much for your response! I am very new to Thingsboard and have never used the chain of rules, originators, events, etc., so I have some questions regarding your response. Here is what I understand so far (please correct me if I am wrong) :

- First create an originator (group or user) which has access to the time slot schedule of the students
- Then create two groups of users -- Group One will have view and control access, Group Two will neither have view nor control access
- Then “catch it” -- **what does this mean?** 
- We’ll need two groups -- Group A gives right to change attributes, Group B doesn’t
- We’ll then create a chain of rules and change who is in each group based on that chain of rules (I believe something like “_if during this time slot, move Person X from Group Two and Group B to Group One and Group A_”)
- "You will need to **move users from the groups that have the rights to control to another group**, and **the group / user who let the originator move to this group**" -- does this first part (bolded) mean the same thing as my example (italicized) in the previous bullet point? Also, I'm confused on the second (bolded) part of this sentence -- what is the group/user that's "letting" the originator move? why is the originator moving? isn't the originator the one controlling the time slot schedule?

Thank you SO much for your help!!

**Comment by JacksonBowe** [comment]
It's a pretty complicated solution you're looking for if you require it to be automated. There is also another problem with the initial way you were trying to approach this that I think it important to mention.

> A will get a password that will only work between 12:05 and 1pm, and at 1pm would lock the student out of the dashboard

If a student has a password that works at 12:30 and logs in... they're in. There's not really a way to lock them out, if you get what I mean. What vvlladd28 was getting at is that the better way to restrict them would be to change the permissions on individual students, via their User Groups.

Non-automated solution:

- Create two user groups as below
![image](https://user-images.githubusercontent.com/26427343/129514149-588522d3-249d-45e0-b3d5-5373a1b382dc.png)

- Create a role
![image](https://user-images.githubusercontent.com/26427343/129514271-ed158788-6de5-423f-b9ad-b8b3f791cf89.png)

- Add the permission to the desired User Group 
![image](https://user-images.githubusercontent.com/26427343/129514347-d6c3b0a4-983a-44a0-9796-fc5bb6f969ce.png)

- Create a User account for each of your students, make them go to the dashboard by default and open in fullscreen. (Unless they need to access other stuff I guess)
- Every hour, manually move the correct student into the group that gives them permissions, and remove the student who was previously in there.
- This is tedious but incredibly simple

Automated Solution: This is horrific

- Navigate to the scheduler and create something like below, make it repeat daily at desired time
![image](https://user-images.githubusercontent.com/26427343/129514617-7ba40adf-bbcd-4be3-9ffe-20f58eb308a2.png)

- Above setup enables write permissions at midday. Create another one that disables write permissions 1 hour later. Do this for every student (yuck right?)

- In the rule chain make this bad boy
![image](https://user-images.githubusercontent.com/26427343/129514890-2b14ed06-d0dd-42c7-93e5-11ed2f048d14.png)

To understand it you may have to just test it and turn debug on. Play around until it works, as I can't do an actual test myself right now, but you see the process.

That should wrap it up.
