### ISSUE TITLE
About time-series database

### ISSUE THREAD

**Issue by liguilini** [thingsboard/thingsboard#5029]
**Is your feature request related to a problem? Please describe.**
I'm using ThingsBoard with timescale db,The data over 300 million.The ThingsBoard become very slow loading.

**Describe the solution you'd like**
May add [TDengine](https://github.com/taosdata/TDengine)  ? I also test over 400 million data in TDengine, it still very fast and powerful.

thanks.

**Comment by linsmalldragon** [comment]
has any one did some job for tdengine?

**Comment by CGmatt1369** [comment]
We have the same problem.
