### ISSUE TITLE
[Question] Showing asset on a map and display in the tooltip the max value of a device telemetry contains by the asset

### ISSUE THREAD

**Issue by BanbanBZH** [thingsboard/thingsboard#5037]
**Component**
map widget 

**Description**
I have some assets on my map. Each asset is a building and contains different devices. 
I want to display the maximum temperature value of a device in the tooltip of the asset but I don't know if it's possible and how to do it ? 
I don't know how I can get the value of the device in the tooltip code ? 

Thanks in advance.

**Comment by dhaval2017** [comment]
As I know you have to make custom widget for it
you can use leaflet library which is also used by thingsboard for map widget


Thanks

**Comment by JacksonBowe** [comment]
Create relations between the asset and all contained devices. When a device temperature reading arrives at TB it will be sent into the rule chain. Somewhere in the rule chain you need to notice that this device has posted, save its telemetry, and then use the **change originator** rule node. 
Originator Source: Related
Direction: Whatever works, try both, hurts my brain to think about
Relation Type: however you set your relations up, Entity types: Asset

This will change the originator of the message to the Asset containing the original device. Awesome, now we're going to pull an attribute of this asset.

Make following rule chain:
![image](https://user-images.githubusercontent.com/26427343/129516946-9648a8da-e5cf-4660-aab2-114e7767cc7a.png)

What's this do? Device posts temperature, we change originator to asset then pull an attribute that looks like this:
deviceTemps = { "devName1": temperature, "devName2": temperature}

If that attribute doesn't exist, create it. If it does exist, update it.

Now in your map widget you can pull that in and iterate through it for the highest value.

**Comment by KenSense** [comment]
I want to do the same thing only latest value of temp sensor,
I have multiple temp sensors and want to show one in the tooltip of the room marker on the building.

Not sure why we would need a rule chain to store the data again, the relation is there.
The latest data is already stored for the sensor I only want to read it starting from knowing the room it's in instead of the device itself.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
