### ISSUE TITLE
Device creation via Python API/Curl

### ISSUE THREAD

**Issue by tsirlapu** [thingsboard/thingsboard#5041]
**Device Creation**

 * Generic

**Description**
I want to create a device automatically(Programatically) without using UI.
First I used to create the token/refresh token with the curl command, later I wanted to try and the curl command "saveDevic" under device controller. And I'm not sure what to fill the body of the request with, because I always get 400 

So does anyone know the sequence of API's to use in python for thingsboard device creation/provisioning via the access token

**Environment**

 * OS:  Thingsboard installed on Ubuntu
 * ThingsBoard: both 2.5 and 3.2
 * Browser: Google chrome

**Comment by Backdraft007** [comment]
Hey,
I use requests in Python.

`headers = { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Authorization' : 'Bearer ' + token }
 newDevice = { "name": 'name', "type": 'deviceType' }
r = requests.post('https://TBSERVERURL/api/device?accessToken='+accessToken, json=newDevice, headers=headers)`

**Comment by ashvayka** [comment]
Please consider using the official Python Rest API SDK. See the CE version docs here: https://thingsboard.io/docs/reference/python-rest-client/ and PE version docs here: https://thingsboard.io/docs/pe/reference/python-rest-client/
