### ISSUE TITLE
[Question] Bar chart with "dynamic keys"

### ISSUE THREAD

**Issue by pridi** [thingsboard/thingsboard#5062]
As reported in the picture below, I would like to create a bar chart (of latest values) where the number of “Uxx” can vary between different dashboards. At the same time I would like to avoid to prepare, let’s say 100 Uxx, having all of them on the chart even if they will not all be used. 
How can I accomplish this?

![image](https://user-images.githubusercontent.com/36031754/128836401-81f27fb7-5bcc-4a4b-83c2-4bafed1bb180.png)

**Comment by dhaval2017** [comment]
Hi @pridi 
Is this something like you have device with keys from U00-U100 and you want to display bar chart?

**Comment by pridi** [comment]
Hi @dhaval2017, thank you for your quick response. In reality I don't know at the beginning how many Uxx I will have. On one dashboard I could have 20 Uxx, on another 32 for example. I don't want all the time to configure the widgets key:
I would like that the widget will add automatically the Uxx based on the keys value I'll send to thingsboard.

**Comment by dhaval2017** [comment]
Oh got it
As I know for now thingsboard widget dont have that option in chart
You have to develop custom widget for that where you provide min max range in widget settings for Uxx and use that number to make chart

Thanks

**Comment by pridi** [comment]
Thank you @dhaval2017. You're right, I'm trying to create a custom widget, even if I'm struggling on how to accomplish this.

**Comment by dhaval2017** [comment]
If you are still struggling with accomplish this using custom widget.
We can help you in developing custom widget 
feel free to contact me on dhaval@nistantritech.com

**Comment by dhaval2017** [comment]
1)create latest value widget
2)add settings for key prefix and min max value
3)make datasource to allow 0 datakeys
4)read min, max and prefix settings in widget in oninit function and call service to get latest telemetry data with settings value
5)make chart based on that value

**Comment by dhaval2017** [comment]
If still struggling mail us on dhaval@nistantritech.com 
We will develop custom widget for you
