### ISSUE TITLE
[Bug] kafa max.request.size configuration

### ISSUE THREAD

**Issue by Doyle-net** [thingsboard/thingsboard#5067]
**Describe the bug**
When there are many alarm rules configured in deviceProfiles, the following error occurs after restarting the gateway :

` WARN  o.b.s.q.k.TbKafkaProducerTemplate - Producer template failure: The message is 2761864 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
org.apache.kafka.common.errors.RecordTooLargeException: The message is 2761864 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
`
I did not find the max.request.size configuration on version 3.2.2

**Your Server Environment**

  * docker deployment
  * ThingsBoard 3.2.2 
  
* Connectivity
  * Gateway

**Comment by ashvayka** [comment]
Support of this parameter was introduced in 3.3
    max.request.size: "${TB_KAFKA_MAX_REQUEST_SIZE:1048576}"
    max.in.flight.requests.per.connection: "${TB_KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION:5}"
