### ISSUE TITLE
what's opening of thingsboard a definitio?

### ISSUE THREAD

**Issue by gogogotest** [thingsboard/thingsboard#5073]
**Component**

 * Generic

**Description**
release3.2

A tenant administrator creates a public asset that other tenant administrators cannot see. Why?

What does the disclosure of equipment mean? After disclosure, the equipment list of customers under the same tenant cannot be queried. Will this function be made public?

**Environment**

 * OS:  win10
 * ThingsBoard: release3.2
 * Browser: google

**Comment by LeoMorgan113** [comment]
Hi @gogogotest,

'Make entity public' means that you open access to entity out of ThingsBoard(out of account).
Mostly like, it is used when you want to give a person a link to the dashboard, but without creating an account.
You make the dashboard and related entities public and users outside of TB can view the dashboard following the link. 

If you want the tenant administrator to see an asset from another tenant, you need to create a Group role and give permission to this asset.
