### ISSUE TITLE
[Bug] widget error All the widgets are unable to display

### ISSUE THREAD

**Issue by guanyu-chen-jpg** [thingsboard/thingsboard#5087]
When I use idea to start the server, all the widgets are unable to display, 

![image](https://user-images.githubusercontent.com/82787307/129481469-ce59c75d-06ff-492f-ae48-cb2dc5d191e2.png)

But when I use net start thingsboard command in cmd to start it, It is normal.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
