### ISSUE TITLE
[Question]widget error All the widgets are unable to display

### ISSUE THREAD

**Issue by guanyu-chen-jpg** [thingsboard/thingsboard#5088]
When i use idea to start the server all the widgets are nuable to display.
![image](https://user-images.githubusercontent.com/82787307/129483155-2458a894-88d8-4377-be93-c214e7fff212.png)
But when i use cmd, it is normal.

**Comment by vvlladd28** [comment]
Hi @guanyu-chen-jpg,
You can describe in more detail: 
- What IDEA are you using?
- What parameters are used to run?
