### ISSUE TITLE
[Question] Unable to enable reports (pdf/png)

### ISSUE THREAD

**Issue by lorithai** [thingsboard/thingsboard#5089]
**Component**

 * UI

**Description**
When trying to download a png/pdf report of a dashboard errors appear. 

![image](https://user-images.githubusercontent.com/25453483/129551773-6589e4ec-37bf-4bc6-ac1e-8cb05ac759d5.png)

**Actions taken**
I tried adding bind for port 8383 to haproxy for the http-in.

![image](https://user-images.githubusercontent.com/25453483/129552151-3ee87ad2-a1ec-4536-9505-0b4cbee99adb.png)

 I Get a new error message when trying to download, but it isn't very helpful. 
![image](https://user-images.githubusercontent.com/25453483/129552028-8e4b27ad-fd6e-4ffd-a237-ccbcee2a8923.png)

My thingsboard.yml config for reports server

![image](https://user-images.githubusercontent.com/25453483/129552362-7154f8c6-a753-4683-8191-8b7ce3a53e63.png)

**Environment**

 * OS:  Ubuntu 20.04.1 LTS
 * ThingsBoard: PE 3.1.1
 * Browser: firefox, Chrome
 * Using Haproxy

**Comment by Backdraft007** [comment]
Hey,

do you have installed the WebReport component?
https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-9-install-thingsboard-webreport-component

Is the service tb-web-report runing? Have a look into /var/log/tb-web-report

It is not neccessary to change anython in haproxy for WebReports.

Greets
Chris

**Comment by lorithai** [comment]
> Hey,
> 
> do you have installed the WebReport component?
> https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-9-install-thingsboard-webreport-component
> 
> Is the service tb-web-report runing? Have a look into /var/log/tb-web-report
> 
> It is not neccessary to change anython in haproxy for WebReports.
> 
> Greets
> Chris

Hi

Thank your, that was the issue. 

I had been following the community guide and not the PE guide. The community guide made no mention of the WebReport component. The reporting guide (https://thingsboard.io/docs/paas/user-guide/reporting/) also makes no mention of installation of the WebReport component. I just assumed it was part of TB.

**Comment by Backdraft007** [comment]
Hey,
Reporting is only available in cloud and professionel edition.
