### ISSUE TITLE
[Question] Solution templates supported in 3.3.0

### ISSUE THREAD

**Issue by BaerSy** [thingsboard/thingsboard#5092]
**PE 3.3.0**

 * Generic

**Description**
When I read doc, it mentions that solution templates will be supported in PE3.3.0.  I installed it but can't find it in the menu. Can you confirm whether it is supported in 3.3.0?

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: or 3.3.0
 * Browser: Chrome

**Comment by JacksonBowe** [comment]
@BaerSy They're only available in Cloud version I think. Unless the change you're mentioning is them being offered standard now.

**Comment by BaerSy** [comment]
Per description in the page of https://thingsboard.io/docs/pe/
PE 3.3 should offer this feature.

**Comment by BaerSy** [comment]
![image](https://user-images.githubusercontent.com/27965673/129786373-81aeac34-1744-4c24-a043-d1a21bf39603.png)

**Comment by ashvayka** [comment]
Hi @BaerSy and all PE customers! Sorry for the delay in releasing the solution templates for PE. We plan to do this in 3.3.1 or 3.3.2 at the latest.

**Comment by BaerSy** [comment]
Whats time frame for 3.3.1 and 3 3.2?

**Comment by ashvayka** [comment]
3.3.1 will be released before the end of September. Ideally, middle of September.

**Comment by ashvayka** [comment]
3.3.2 is the next bug fix release that we plan to release in 1-1.5 months after 3.3.1
