### ISSUE TITLE
[0.000s][error][logging] Invalid option: filesize must be in range [0, 18446744073709551615]

### ISSUE THREAD

**Issue by HeartsK** [thingsboard/thingsboard#5095]
Loaded: loaded (/usr/lib/systemd/system/thingsboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-08-17 17:29:06 CST; 4min 55s ago
  Process: 3740133 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILU>
 Main PID: 3740133 (code=exited, status=1/FAILURE)

8月 17 17:29:05 thringsboard systemd[1]: Started thingsboard.
8月 17 17:29:06 thringsboard thingsboard.jar[3740133]: [0.000s][error][logging] Invalid option: file>
8月 17 17:29:06 thringsboard thingsboard.jar[3740133]: [135B blob data]
8月 17 17:29:06 thringsboard thingsboard.jar[3740133]: [170B blob data]
8月 17 17:29:06 thringsboard thingsboard.jar[3740133]: Error: Could not create the Java Virtual Mach>
8月 17 17:29:06 thringsboard thingsboard.jar[3740133]: Error: A fatal exception has occurred. Progra>
8月 17 17:29:06 thringsboard systemd[1]: thingsboard.service: Main process exited, code=exited, stat>
8月 17 17:29:06 thringsboard systemd[1]: thingsboard.service: Failed with result 'exit-code'.

**Comment by ashvayka** [comment]
Please add more details what version are you using and what kind of build option? This log is insufficient to help you.

**Comment by HeartsK** [comment]
i use thingsboard-3.3 release,and build by source code, use local mvn clean install -DskipTests order get the thingsboard-3.3.1~SNAPSHOT-1.noarch.rpm, and rpm -Uvh thingsboard-3.1.1.rpm,then start thingsboard.service report that error

**Comment by ashvayka** [comment]
Why have you closed the issue? Is this your local modification problem? Please share with community

**Comment by HeartsK** [comment]
yes is my local environment character conversion cause the error
