### ISSUE TITLE
Thingsboard community edition, cannt see telemetry using mqtt box, but same setup works for free cloud version

### ISSUE THREAD

**Issue by nikkal2110** [thingsboard/thingsboard#5099]
we have things board community edition installed on server, i was able to publish mqtt messages to it a month ago.
I was working on AWS for some time and when i tried to start working again with thingsboard since yesterday, i am not able to see any telemetry data.

i am using mqtt box for sending data. with the same setup on mqtt box i can post on cloud version free account but not on community edition. Any help would be appreciated.

Thanks

**Comment by jiekechoo** [comment]
The message you sent must be 'json' format, and your access_token must be equal to Thingsboard device's setup.

**Comment by nikkal2110** [comment]
> The message you sent must be 'json' format, and your access_token must be equal to Thingsboard device's setup.

Hi there,

Thanks for your input. I am using MQTT box for sending data. I am able to send data to thingsboard free cloud version, but using same settings i cannot send data to community edition. 
access_token is equal to thingsboard device setup and format is also same (json)

**Comment by trikimiki** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the new ticket if this problem still exists. In new ticket, specify detailed steps to reproduce the issue.
