### ISSUE TITLE
where is the “devices” menu ?

### ISSUE THREAD

**Issue by konglinghai123** [thingsboard/thingsboard#510]
![image](https://user-images.githubusercontent.com/12596758/34526996-ffe49d56-f0de-11e7-95b4-d02f8b340588.png)

build version 1.3.1

login default user :  sysadmin@thingsboard.org/sysadmin 

but i access this url : http://127.0.0.1:8082/devices

![image](https://user-images.githubusercontent.com/12596758/34527191-ba2f2fd2-f0df-11e7-86b0-00498a539086.png)

**Comment by mp-loki** [comment]
try to log in as tenant@thingsboard.org/tenant

**Comment by konglinghai123** [comment]
![image](https://user-images.githubusercontent.com/12596758/34529737-eed96592-f0e7-11e7-89db-168de2cecc29.png)
![image](https://user-images.githubusercontent.com/12596758/34529753-f923c286-f0e7-11e7-8101-779493224f2f.png)

can you give me your SQL script?

**Comment by konglinghai123** [comment]
yes,i running from idea , and use the DAO mould that have a SQL script to create my database. i can run the project and login as sysadmin. by i don't have permition to access the 'devices' menu.
so i want to get a right SQL script.

**Comment by mp-loki** [comment]
did you try running **install_dev_db.sh** (or bat) script from your target folder? it should have populated the demo data including tenant user

**Comment by konglinghai123** [comment]
thanks you , I know why  and found the solution.
1.create a tenant by system admin.
2.use this tenant account login system.
