### ISSUE TITLE
[Question] PostgreSQL issue with thingsboard/tb-postgres on docker (windows)

### ISSUE THREAD

**Issue by hangusto** [thingsboard/thingsboard#5101]
**Component**

 * Installation

**Description**
Follow the instruction of the installation: [Installing ThingsBoard using Docker (Windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/)
Here is my **docker-compose.yml**:
<pre>
version: '2.2'
services:
  tb:
    container_name: mytb
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683-5688:5683-5688/udp"
      - "5432:5432:
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard
volumes:
  mytb-data:
    external: true
  mytb-logs:
    external: true
</pre>

docker desktop backend:  **WSL 2 backend**

docker image:  **thingsboard/tb-postgres:3.3.0**

After the installation, it seems that the thingsboard working is ok, but there are 2 questions about PostgreSQL:

### **1. How do I change the user from "thingsboard" to "root" or "postgres"?**
<pre>
PS D:\DockerFile\ThingsBoard> docker exec -it mytb bash
thingsboard@50e22fb5560c:/$
</pre>
to be
<pre>
root@50e22fb5560c:/$
postgres@50e22fb5560c:/$
</pre>
I try this:
<pre>
thingsboard@50e22fb5560c:/$ su - postgres
Password: postgres
su: Authentication failure
</pre>
Does anyone know the default password for "root" or "postgres"? 
Is there any restrictions for changing the user?
I can't use the "sudo" command and cannot into PostgreSQL in the docker @@
<pre>
thingsboard@50e22fb5560c:/$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
</pre>
<pre>
thingsboard@50e22fb5560c:/$ sudo
bash: sudo: command not found
thingsboard@50e22fb5560c:/$ apt-get install sudo
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
thingsboard@50e22fb5560c:/$
</pre>

### **2. Is there any methods or recommendations for operating PostgreSQL from docker in the host's browser?**

Thanks

**Environment**

 * OS:  Windows 10
 * ThingsBoard: CE 3.3.0
 * Browser: Chrome

**Comment by ashvayka** [comment]
Please take a look at [installation steps](https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/) via docker-compose. This will allow you to isolate PostgreSQL from thingsboard and take full control of your DB image. This is a recommended way.
