### ISSUE TITLE
[Bug] Thingsboard PE Upgrade to 3.3 Failed?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#5103]
**Describe the bug**
Upgrading from PE 3.2.2 to PE 3.3.0
C:\Program Files (x86)\thingsboard>upgrade.bat --fromVersion=3.2.2
Upgrading thingsboard ...
  ______    __      _                              ____                               __
/_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
/ /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

===================================================
:: ThingsBoard Professional Edition ::       (v3.3.0PE)
===================================================

Warning: Nashorn engine is planned to be removed from a future JDK release
Error creating bean with name 'integrationArgumentResolverMessageConverter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.integration.support.converter.ConfigurableCompositeMessageConverter]: Constructor threw exception; nested exception is java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/fasterxml/jackson/databind/cfg/MapperBuilder.streamFactory()Lcom/fasterxml/jackson/core/TokenStreamFactory; @7: areturn
  Reason:
    Type 'com/fasterxml/jackson/core/JsonFactory' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/TokenStreamFactory' (from method signature)
  Current Frame:
    bci: @7
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/cfg/MapperBuilder' }
    stack: { 'com/fasterxml/jackson/core/JsonFactory' }
  Bytecode:
    0000000: 2ab4 0002 b600 08b0

ThingsBoard upgrade failed!

C:\Program Files (x86)\thingsboard>

* Server Environment**
  * Windows Server 2019
  * openjdk version "11.0.10" 2021-01-19 
  * Postgresql 12

**Comment by ashvayka** [comment]
This looks like dependency issue. Please try to update to openjdk 11.0.11. We will check from our side to fix this in TB 3.3.1

**Comment by KenSense** [comment]
I updated java to the latest version, the problem stays the same.

C:\Program Files (x86)\thingsboard>java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

C:\Program Files (x86)\thingsboard>upgrade.bat --fromVersion=3.2.2
Upgrading thingsboard ...
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.3.0PE)
 ===================================================

Warning: Nashorn engine is planned to be removed from a future JDK release
Error creating bean with name 'integrationArgumentResolverMessageConverter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.integration.support.converter.ConfigurableCompositeMessageConverter]: Constructor threw exception; nested exception is java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    com/fasterxml/jackson/databind/cfg/MapperBuilder.streamFactory()Lcom/fasterxml/jackson/core/TokenStreamFactory; @7: areturn
  Reason:
    Type 'com/fasterxml/jackson/core/JsonFactory' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/TokenStreamFactory' (from method signature)
  Current Frame:
    bci: @7
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/cfg/MapperBuilder' }
    stack: { 'com/fasterxml/jackson/core/JsonFactory' }
  Bytecode:
    0000000: 2ab4 0002 b600 08b0

ThingsBoard upgrade failed!

C:\Program Files (x86)\thingsboard>

**Comment by ashvayka** [comment]
What kind of queue are you using? Cassandra DB is used?  We can't reproduce this locally. Probably the issue depends on the list of enabled features (db type, queu type, etc).

**Comment by KenSense** [comment]
I will email you my .yml file, no Cassandra is used.

**Comment by ashvayka** [comment]
ashvayka@thingsboard.io

**Comment by KenSense** [comment]
> [ashvayka@thingsboard.io](mailto:ashvayka@thingsboard.io)

You should already have the email, I did email it when I posted the message.

**Comment by ashvayka** [comment]
Please specify your email and I will check again.

**Comment by KenSense** [comment]
It has the same subject as this "Thingsboard PE Upgrade to 3.3 Failed" and I did send it again. (Name Ken)

**Comment by SergMeleshko** [comment]
Hello.
Is this issue still relevant?

**Comment by KenSense** [comment]
Maybe, but not longer relevant for me since we switched to an Ubuntu environment instead of Windows to fix (workaround) the problem.

**Comment by Roeli1969** [comment]
Hi.
I have the same error upgrading from 3.2.2PE to 3.3.0PE
Any solution?

Postgresql-42.3.3
Openjdk11U 11.0.14.1_1

**Comment by Ultrazombie** [comment]
Hello @Roeli1969,
Is your problem still relevant?
