### ISSUE TITLE
[Bug] typo of the name 'leadflet.ts' at ui-ngx/src/typings

### ISSUE THREAD

**Issue by chengdi1988** [thingsboard/thingsboard#5105]
**Describe the bug**
Name of `https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/typings/leadflet-editable.d.ts` is wrong. It should be 'leaflet' rather than 'leadflet'
**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vvlladd28** [comment]
Hi @chengdi1988 
Thank you for your report. Thank you for your report. Coming soon, we will add a fix.
