### ISSUE TITLE
[Question] Maintenance page when Thingsboard is down? (Windows)

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#5116]
Hi,

What would be the easiest solution to set up a maintenance page when Thingsboard is down for an upgrade?
Preferable somethings that doesn't take resources when Thingsboard is running.
Maybe there is another service that can be started? (after stopping the Thingsboard service.)

 * OS:  Windows Server
 * ThingsBoard PE

**Comment by ashvayka** [comment]
this may be done if you hide ThingsBoard behind popular load balancers. They support maintenance pages.
