### ISSUE TITLE
[Question] How do I toggle a switch based on a sensor value under same asset?

### ISSUE THREAD

**Issue by gicohdawer** [thingsboard/thingsboard#5119]
Hi everyone,

I have a scenario where I have a motor and a sensor installed within the same building. I want to actuate the motor if the sensor value gets lower or higher than a certain value. Please note that both are under the same asset.

After achieving this, the next scenario is that I have multiple assets containing sensor & motor pairs under one larger Asset. Now, I want to trigger a physical alarm in control room if any of the motor gets actuated on any of sub-assets.

Please someone help how to achieve this. Please mention steps or any tutorial to achieve this functionality.

Regards,
Dawer.

**Comment by jiekechoo** [comment]
I think you have a lot of works to do.
first question:
1. create a rule chain, get sensor's value, then trigger a attribute( big_val );
2. from motor device, sub the attribute, then do something;

second question:
1. just use v3.3 to create alarms;
2. maybe you need an another rule chain.

**Comment by gicohdawer** [comment]
Awesome suggestion.
Really thankful to you.
Will now implement triggering the sub asset's attribute based on motor. and then based on that attribute will trigger the alarm on the parent asset. Thanks.

**Comment by ashvayka** [comment]
@gicohdawer  and everyone who may find this issue using search, we have two guides that show some basics of rule engine and related to this topic:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/function-based-on-telemetry-from-two-devices/
and
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/
