### ISSUE TITLE
[Question] Import data history from other platform

### ISSUE THREAD

**Issue by Xab01** [thingsboard/thingsboard#5123]
Hello all,

We are using Thingboard cloud, We would like to create a new device and import all its data from the 2 last years into thingboard.

1.  Is it possible?
2. we tried ==> http(s)://host:port/api/v1/$ACCESS_TOKEN/telemetry with the ts value like ({"ts":1451649600512, "values":{"key1":"value1", "key2":"value2"}})
but the record is not inserted.

Do you have any ideas how to proceed?

Thanks in advance

Xavier

**Comment by dhaval2017** [comment]
Yes it's possible

**Comment by Xab01** [comment]
Thanks for the feedback :-)
Do you have any procedure or examples ?

**Comment by dhaval2017** [comment]
Same as you did
https://thingsboard.io/docs/reference/http-api/

You must be missing something if you haven't customised anything in rulechain
