### ISSUE TITLE
[Question] Is there a way to have source control on Rule Chains and Rule Nodes?

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#5127]
**Component**

 * Rule Engine

**Description**
Is there a way to keep Rule Chains and Rule Nodes under source control?

There are mainly two use cases:

- Prevent accidental deletion of nodes or entire chain.
- Keep code for the `Script` nodes with history. 

Additionally, it will be very useful if the code for the `Transform` function can be supplied from a repository, for eg. github.

**Environment**

 * OS:  Any
 * ThingsBoard: Any
 * Browser: Any

**Comment by marulitua** [comment]
We can create a simple provision tool using [python client library](https://github.com/thingsboard/thingsboard-python-rest-client).
Every exported JSON file is just a schema.
To provision dashboard, we can create a simple function like the following
```python
        def provision_dashboard():
            for dashboard_file in glob('thingsboard/dashboards/*.json'):
                with open(dashboard_file) as json_file:
                    dashboard_data = json.load(json_file)

                    dashboard = Dashboard(
                        configuration=dashboard_data['configuration'],
                        name=dashboard_data['name'],
                        title=dashboard_data['title']
                    )

                    res = client.get_tenant_dashboards(page_size=100, page=0, text_search=dashboard.name)
                    for c in res.data:
                        client.delete_dashboard(c.id)

                    client.save_dashboard(dashboard=dashboard)
```

**Comment by basor-dali** [comment]
Thank you @marulitua ! this is very helpful, i will implement something like this on my application.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
