### ISSUE TITLE
MQTT stop working (test using performance-tests)

### ISSUE THREAD

**Issue by chunyeow** [thingsboard/thingsboard#513]
We have TB installed (cassandra and TB in one single instance) in 2 core CPU with 4G RAM and done a quick test using performance-tests tool. We use the default test properties inside the tool. 20,000 devices has been successfully created. Later on, when starting injecting the traffic (ramp us 20,000 MQTT connection in 1 seconds), it can only execute the test up until around 3,980 devices. 

CPU reach up to 160% but then back to normal. TB is not died and other transports still working, such as HTTP and CoAP. But MQTT no longer work. Checking with "netstat -an", the MQTT socket is able to open but no response. 12 worker threads nioEventLoopGroup all in runnable. Any idea on what to look for?

**Comment by ashvayka** [comment]
I think you have limit on max connections set to 4096. This cause issues when client number is close to this number. You need to apply specific OS parameters tunning to allow more open file descriptors to handle 20000 parallel connections

**Comment by chunyeow** [comment]
@ashvayka Thanks. You are right. Apparently, I have missed out to check the setting of max open FD thought that it works. Check with 'cat /proc/<pid>/limits' indicates only 4096 as you mentioned. Thanks
