### ISSUE TITLE
[Question] RPC and HTTP integration to control devices using the Knob control

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5131]
**Component**

 * Rule Engine

**Description**
We have started to build a demu using the TB platform, and now trying to use the Knob control to control our devices.
Our devices are connected via a third party platform that we integrate with using http platform integration. Streaming telemetry works flawlessly. However using RPC from the knob control is a bit of a problem.
We can transmit messages created by setUpdate rpc to our devices using the rest api call in the rule engine. Problem is that we get a message in the knob control saying that the message timed out.
Preferably we would like to reply to the getValue rpc call in the rule engine adding a value from the devices attribute instead of going all the way out to the device. We stream the value anyway as part of our telemetry data.

Is there any guide how to do this, or any best practices? Do we have to make a custom integration, can we make this in the rule engine, or any other option?

Thanks

**Environment**
ThingsBoard version 3.3.0 PE
Minikube

**Comment by dhaval2017** [comment]
@tobbelin 
Your device supports thingsboard RPC command??
If not then using custom widget will be the best way

Thanks

**Comment by tobbelin** [comment]
It does not support anything Thingsboard specific.
I hoped we could customize rest api calls and doing so opening up to use all the features of the TB platform.
If I could only loop back the RPC requests as a response I would be able to append attribute values. Also if I could just translate the outgoing message in the rule engine to a http rest request and ack the rpc call I would be all done. :-)


> @tobbelin
> Your device supports thingsboard RPC command??
> If not then using custom widget will be the best way
> 
> Thanks

**Comment by tobbelin** [comment]
> @tobbelin
> Your device supports thingsboard RPC command??
> If not then using custom widget will be the best way
> 
> Thanks

Created a simple widget. Thanks.
