### ISSUE TITLE
[Question] Timeseries Line Chart first sample in window

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5134]
**Component**

 * UI

**Description**
We have a timerseries line chart set up to show our pressure over a fan inlet.
Since we are streaming telemetry over a cellular connection we only send data once per hour and on changes. In the timeseries window I see a gap to the first sample visible in the window. I would expect it to draw a line from the point before the window visible. I have the line chart set up to plot a smoothed curve.
Is this me doing something wrong or by design?

**Environment**
 * ThingsBoard: 3.3.0PE
 * Browser: Edge Version 94.0.982.2

**Comment by tobbelin** [comment]
![Skärmbild 2021-08-24 153038](https://user-images.githubusercontent.com/15633540/130627851-f2a3ee01-d6e1-462f-ae1c-b5e42573907d.png)

**Comment by tobbelin** [comment]
And I do have data before that point if I zoom out.

**Comment by tobbelin** [comment]
The solution with my way of fixing this is not great since if I try to show a window of 30 minutes and no datapoints are in that window I can not create my "virtual" datapoints. 
This must be a common problem, am I missing something?

**Comment by myroslav-tb** [comment]
Hi @tobbelin, try to increase the maximum number of values in a timewindow.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/916bdacd-6ac0-4e04-81c4-a0dee5d7196e)

Best regards,
Myropslav
