### ISSUE TITLE
[Question] Where can I translate Thingsboard PE

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#5135]
**Component**

 * UI

**Description**
Some sentences and words are not translated to german in PE. How can I contribute to help?

**Comment by vvlladd28** [comment]
Hi @Backdraft007,
You can make a pull request for this repository or write us using the form [Thingsboard Contact Us](https://thingsboard.io/docs/contact-us/).

**Comment by ashvayka** [comment]
Hi @Backdraft007 , please take a look at https://thingsboard.io/docs/pe/user-guide/custom-translation/ white-labeling tutorial. The video,  timing is ~5 minutes, covers custom translation. You may notice the "Download Local File" button. You may compare German and English locales and add missing translations. We will be happy to receive the updated German translation file and add it as default to TB PE.

**Comment by Backdraft007** [comment]
OK, thanks, in the next weeks I will add missing translations.
