### ISSUE TITLE
How to access timeseries values of type String or json in the widget subscription?

### ISSUE THREAD

**Issue by ferchinas** [thingsboard/thingsboard#5143]
**Component**
 * UI
 
**Description**
The subscription to a timeseries of type `String`or `json` does not show the values correctly in the widgets, it always shows the value "0".

_TimeSeries Table card widget_
![Screenshot_63](https://user-images.githubusercontent.com/30049639/130804804-bc63f255-049f-4a82-85c5-baee4cb34b61.png) 
The same happens if I try it with a custom timneseries widget, accessing the data in the following way
`self.ctx.defaultSubscription.data [timeSerieIndex].data [valueIndex][1]`

_The same timeseries widget with numeric data works as expected_
![Screenshot_64](https://user-images.githubusercontent.com/30049639/130806044-c6936b63-3269-47ce-a49a-ea557e7f189d.png)

_This is my data_
![Screenshot_66](https://user-images.githubusercontent.com/30049639/130805763-2a60f00c-eec4-4155-90e4-a6c4c0c9be45.png)

_The subscription to the last values of the same time series, shows the correct values in "Simple card" widget_
![Screenshot_65](https://user-images.githubusercontent.com/30049639/130804833-f38d0158-f07d-4977-a9c4-fa16ff8e914c.png)

Am I doing something wrong, is it a bug or is it a limitation?
Thank you

**Environment**
 * OS:  Ubuntu 18.04.4
 * ThingsBoard: 3.3.0
 * Browser: Firefox 91.0.2 (64-bit)

**Comment by ashvayka** [comment]
Hi @ferchinas , are you using any data aggregation functions in your time window or NONE as aggregation?

**Comment by ferchinas** [comment]
You are the best!
I apologize for the silly question.
I hope that at least your answer will also help someone else.
