### ISSUE TITLE
while adding  custom marker in mapwidget , along with cluster marker and labels are displaying . can anyone please help me ??

### ISSUE THREAD

**Issue by tulasitubati** [thingsboard/thingsboard#5144]

**Comment by LeoMorgan113** [comment]
Hi @tulasitubati,

Could you please provide the screenshot?

**Comment by tulasitubati** [comment]
![Screenshot from 2021-08-25 23-03-56](https://user-images.githubusercontent.com/34621759/131792541-907d1bb0-c3be-4223-b75e-0a95b71d71d5.png)
   

this issue is replicating on when i used custom marker in map-widget

**Comment by LeoMorgan113** [comment]
There is marker and label function, so you can customize it on your needs, disable if you want:
![0](https://user-images.githubusercontent.com/56256429/131852629-9a7c119e-c400-4492-a2b5-43bcfbe14e48.PNG)
![image-20210901-075514](https://user-images.githubusercontent.com/56256429/131852111-ef81b11f-5e25-4712-b9de-22a6e2449880.png)

**Comment by tulasitubati** [comment]
I'm using clustering with custom marker not every time marker is displaying 
If I'm not using custom marker or I'm using through marker image function clustering was working fine .. I'm getting an issue only through custom marker

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
