### ISSUE TITLE
[Question] How can I Provision/Claim device with Protobuf ?

### ISSUE THREAD

**Issue by nguyenlam185** [thingsboard/thingsboard#5146]
Hi guys,
I am now able to publish/subscribe to Telemetry, Attributes and RPC topics using Protobuf as the proto schemas can be declared explicitly. But I have not known how to declare schema for Device Provisioning/Claiming ?

May I have some suggestion on this ?

Thanks in advance

**Comment by mykhailokornieiev** [comment]
Hi. There is no possibility of device provision/claiming with Protobuf.
