### ISSUE TITLE
[Feature Request] add option to set entity Label in Creation Relation Node

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#5147]
Hi

We use the create relation - create entity if not exist option often when we provision new devices and assets.

we find that not having the option to set Asset label when 'creating entity if not exist'  is problematic for us and requires extra manual steps.

if you add the field to set entity Label in the node it would be very helpful.

![image](https://user-images.githubusercontent.com/31729091/130927436-9138950d-cdb5-4534-bdd1-a290eed208a1.png)

**Comment by LeoMorgan113** [comment]
Hi @t0mmyz7,

I can recommend you the next solution: you can set label with REST API Call node with the next request:
![image](https://user-images.githubusercontent.com/56256429/131215785-89f29a34-fd8b-4ffd-b44a-a6a1431ee610.png)

![image](https://user-images.githubusercontent.com/56256429/131215774-2ae7c83a-76c7-4448-8519-d0189b415340.png)

**Comment by LeoMorgan113** [comment]
Also, I have added your appeal to our backlog, so developers will review and implement it as soon as possible.

**Comment by t0mmyz7** [comment]
That's great thanks alot!

**Comment by t0mmyz7** [comment]
Also thanks for the work around.
