### ISSUE TITLE
[Bug] Set Entity Label and Entity Name does not work in Update Multiple Attributes Widget in Version 3.3.0 PE

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#5148]
Hello

This was working before, but is not working now.

Changing the entity Label or Name in Update Multiple Attributes Widget  for assets (and most likey devices too) does not work in v3.3.0

After changing the field and getting Success message, entity name or label remain the same.

![image](https://user-images.githubusercontent.com/31729091/130936461-0e4a4edf-f245-44d5-9808-b7f3d3929326.png)

**Comment by t0mmyz7** [comment]
Hi Andrew

this was working before and it quite convenient way to have customer make changes to different settings in one place (attribute, name. label).

any chance to make it work again in newest version?
