### ISSUE TITLE
Custom Widgets - How to list all telemetry dataKeys from a device inside a widget (without providing all the keys) and getting de data from these keys.

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#5150]
**Component**

 * UI

**Description**
I am trying to create a widget that shows all the telemetry from a device, without having to subscribe to the individual keys manually (by adding them one by one in the widget setup).

**Environment**

 * ThingsBoard: 3.1.1PE

I have not yet found any way to possibly find all the datakeys, I did however found a post about subscribing to a predifined list of keys, but the code provided doesn't seem to work anymore.
https://github.com/thingsboard/thingsboard/issues/1743#issuecomment-495660839

**Comment by dhaval2017** [comment]
Hi @DejonckheereWard 
I checked and see that thingsboard have rest api to get list of telemetry key but they don't have added in services so you cant get list of telemetry key in widget development

there is another way you might like until thingsboard add option to get all telemetery key in widget 
you can setup the rulechain to store the all latest telemetry keys in server attribute 
whenever any data comes just check if its available in server attribute if not just add and update it

will that help you?

**Comment by DejonckheereWard** [comment]
Hi @dhaval2017 
Would it be possible then to call that rest api from inside the widget in some way?

**Comment by dhaval2017** [comment]
@DejonckheereWard yes you can call rest api If you have access to accesstoken

I think this will help you to get accesstoken
https://github.com/thingsboard/thingsboard/issues/1162

**Comment by DejonckheereWard** [comment]
@dhaval2017 
I will look into this tomorrow and see how far I get.
Thank you very much for your help.

**Comment by nowherex** [comment]
Hi, I recently had a similar problem, I solved it by creating my own widget with websocket subscription, you can find out more about how websocket works on thinsboad dashboard here: https://thingsboard.io/docs/user-guide/telemetry/#websocket-api

My Widget:
![Console WebSocket](https://i.ibb.co/Q87QYs0/Console-Web-Socket.png)

**Comment by DejonckheereWard** [comment]
I managed to get the data using the rest API, i only wanted them once when the page loads so websockets not really required for me.
Did have some issues with the token, mainly because my custom widgets are saved as system widgets, and the token you get while making the widget has no permission to access the data.
Thanks for the help
