### ISSUE TITLE
Communication between Widgets 

### ISSUE THREAD

**Issue by CalvinG21** [thingsboard/thingsboard#5159]
I'm currently using ThingsBoard 3.2.2 , I have 2 custom widgets in a dashboard , I need widget A to send events/messages to widget B.

Below is the detracted JS code for sending events between widgets.

var rxEvent = root.$on(
        'widgetComms',
        function(event, recievedData) {
            if (recievedData) {
                //do stuff
            }
        });

function sendMessage() {
    var scope = self.ctx.$scope;
    var root = scope.$root;
  
    
    root.$emit('widgetComms', {
        message: text
    });
}

Is there a new way of communicating between widgets in TB versions 3 and above?

**Comment by JacksonBowe** [comment]
Personally I would just do it via attributes of the dashboard state entity. Not the ideal solution, but one that is simple to implement.

Example: 
Widget A takes attribute flag, represented by a html toggle.
Widget B takes same attribute, and performs logic based on value.

**Comment by vvlladd28** [comment]
Hi @CalvinG21,
In ThingsBoard 3.2.2, we are using Angular 10, which does not support root.$emit, root.$on.We have written our own implementation of these methods:
```
let broadcast = $scope.$injector.get(self.ctx.servicesMap.get('broadcastService'));

broadcast.broadcast("rootEvent", {
  message: "rootEvent Message"
})

broadcast.on("rootEvent", function (event, data) {
   //Event handling code
}))
```
