### ISSUE TITLE
Thingsboard Logo

### ISSUE THREAD

**Issue by ram1505** [thingsboard/thingsboard#516]
Ho,
I'm a newbie to Thingsboard. I got the Thingsboard EC2 instance from the getting started page. Is there a way to change the logo and the footer text powered by thingsboard without needing to rebuild.

**Comment by myfreescalewebpage** [comment]
Hi,
I'm also interested by this subject, why issue has been closed without any comment?
Joel

**Comment by hecko** [comment]
Because this is not a feature supported by community edition of ThingsBoard

See https://thingsboard.io/products/thingsboard-pe/ for whitelabelling.

**Comment by yalamber** [comment]
@hecko is there any licensing issue if we change it from UI source code?

**Comment by hecko** [comment]
@yalamber I personally don't think so - you can freely fork the codebase and changing parts of the code; but Im not part of the development team, nor affiliated
with TB at all, so better ask through official website so you have an official backing here :)
