### ISSUE TITLE
[Question] Thingsboard Widget style : Not able to add url path of local PC for background image instead of https link

### ISSUE THREAD

**Issue by abhishekavl** [thingsboard/thingsboard#5160]
**Component**

 * UI

**Thingsboard Widget style: Not able to add url path of local PC for background image instead of https link**
![Image of issue](https://user-images.githubusercontent.com/87922855/131242514-b4a99e9d-605d-4c42-a449-f596c8df21d0.png)

**Environment**
 * OS:  WIndow 10, 
 * ThingsBoard: 3.3
 * Browser: Google Chrome

**Comment by dhaval2017** [comment]
@abhishekavl 
convert image into data url 

example widget style
{
  "backgroundImage": "url('data:image/gif;base64,R0lGODlhUAAPAKIAAAsLav///88PD9WqsYmApmZmZtZfYmdakyH5BAQUAP8ALAAAAABQAA8AAAPbWLrc/jDKSVe4OOvNu/9gqARDSRBHegyGMahqO4R0bQcjIQ8E4BMCQc930JluyGRmdAAcdiigMLVrApTYWy5FKM1IQe+Mp+L4rphz+qIOBAUYeCY4p2tGrJZeH9y79mZsawFoaIRxF3JyiYxuHiMGb5KTkpFvZj4ZbYeCiXaOiKBwnxh4fnt9e3ktgZyHhrChinONs3cFAShFF2JhvCZlG5uchYNun5eedRxMAF15XEFRXgZWWdciuM8GCmdSQ84lLQfY5R14wDB5Lyon4ubwS7jx9NcV9/j5+g4JADs=')"
}

**Comment by volodymyr-babak** [comment]
@abhishekavl 
widget is not able to fetch images from your local PC.
Please use tip, that was provided by @dhaval2017 to fix your problem.
