### ISSUE TITLE
[Bug] Disable then display activation link provide activateToken=null URL

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#5162]
**Describe the bug**

**Your Server Environment**
Thingsboard 3.2 PE on docker with external Postgres DB

**Your Client Environment**

* OS:  Windows 10
* Browser Firefox 91.0

**To Reproduce on my side**
1. Go to customer hierarchy
2. Click on Disable user account
3. Click on Display activation link
4. See error the link that ends with "/api/noauth/activate?activateToken=null"

**Expected behavior**
Valid activation token.

**Comment by bbrenne** [comment]
Creation of a new user displays a correct link.

**Comment by trikimiki** [comment]
This is a feature, not a bug. The activation token is being created once, and once the user was "activated" this way, you cannot re-activate it again via the activation link.

**Comment by volodymyr-babak** [comment]
@bbrenne 
Disable/Enable user account, and the Activation user account is different things.
In the latest version clicking on the 'Display activation link' will throw an error, that 'User is already activated!':
![image](https://user-images.githubusercontent.com/3466101/152166420-537164f4-85f4-407d-a3e4-584c5dc48af0.png)

And this error will be thrown in both variants - whether the user is disabled or enabled.
