### ISSUE TITLE
[Bug] SECURITY_USER_LOGIN_CASE_SENSITIVE has no effect on password recovery

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#5163]
**Describe the bug**
When SECURITY_USER_LOGIN_CASE_SENSITIVE is set to false, the user created is saved in lower case (testTEST@test.com becomes testtest@test.com). User can login with or without upper case which is fine. However if the user losts his password, he MUST enter the email address with lowercase or the account is not found.

**Your Server Environment**
Thingsboard 3.2 PE on docker with external postgres DB.

**Your Client Environment**

* OS: Windows 10
* Browser Firefox 91.0

**To Reproduce**
1. Sets SECURITY_USER_LOGIN_CASE_SENSITIVE to false
2. Create user testTEST@test.com
3. Log out
4. Try recover password for testTEST@test.com
4. See error account not found

**Expected behavior**
Password recovery must take SECURITY_USER_LOGIN_CASE_SENSITIVE into consideration.

**Comment by vvlladd28** [comment]
Hi @bbrenne,
Thank you for your report.  We plan to fix this in 3.3.1.
