### ISSUE TITLE
[Bug] All name and fileds with XXX.XXX

### ISSUE THREAD

**Issue by B-DAGBERT** [thingsboard/thingsboard#5165]
Hi, 

I've got an "issue" with all my name of menus and fields.
Everything printed is called by the name the group dot the name of the field. 

I can fix it by using the custom translation but it's a bit annoying ...

Here's the bug in 3.3PE:
![image](https://user-images.githubusercontent.com/44493549/131310319-37ead1b3-2eac-43c5-894d-7b8f6dd2082f.png)

Same menu on one of my other instance in 3.0.1PE without issues :
![image](https://user-images.githubusercontent.com/44493549/131310412-09425858-63e9-4296-8e23-8bb890420b14.png)

Both deployed on a local ubuntu server Ubuntu 18.04.1 LTS.

Does someone have a solution or an explanation of this issue ?

Thx !

**Comment by Backdraft007** [comment]
clear your browser cache and reload the page.
Does it help?

**Comment by B-DAGBERT** [comment]
No it dont :/ Still have the issue on 3.3 and not on 3.0.1

**Comment by B-DAGBERT** [comment]
But only have the issue on Google Chrome, not on Firefox

**Comment by B-DAGBERT** [comment]
Sorry, you was right, clear the cache solved it, thx
