### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by Mirjka** [thingsboard/thingsboard#5168]
**Component**

 * UI

**Description**
Hi, is it possibe to use "update schared Boolean attribute" Widget to write two different integer values? 
I tried to use the 'data post-processing function' but didn´t get it working. Like:
return value === 'true';

Since there is no 'Tooltip value format function' I simply added:
if (value == 'true') {
    return '1';
} else if (value == 'false' {
    return '0';
} else {
    return '';
}

Is it possible / what Iam doing wrong? 

Best regards
Mirjka

**Environment**

 * OS:  WIN 10 pro 
 * ThingsBoard: latest version PE
 * Browser: FireFox 91.0.2

**Comment by JacksonBowe** [comment]
You would need to create a custom widget. It wouldn't be hard. The widget has this function
`$scope.updateAttribute = function() {
        if ($scope.entityDetected) {
            var datasource = self.ctx.datasources[0];
            attributeService.saveEntityAttributes(
                datasource.entity.id,
                'SHARED_SCOPE',
                [
                    {
                        key: $scope.currentKey,
                        value: $scope.checkboxValue || false
                    }
                ]
            )`

If you change this line `value: $scope.checkboxValue || false`
to 
`value: (($scope.checkboxValue) ? //True Condition : //False Condition)`
you should be fine

With your example:
`value: (($scope.checkboxValue) ? 1 : 2)`

Haven't tested it but it's definitely possible. Good luck!
