### ISSUE TITLE
[Question] Knob Control (Control Widget - Dashboard) unable to getValue 

### ISSUE THREAD

**Issue by samteck-etairos** [thingsboard/thingsboard#5176]
**Component**

 * UI

**Description**
For Knob Control Widget, I can set the value using setValue RPC and the data is sent to my device.
But, if we have a similar knob at the end-node and the value is changed from there, that value is not reflected from getValue RPC

Observation: when we open the dashboard for the first time the getValue RPC is executed and it changes the KnobValue which it fetches from the device. But the thing is that getValue RPC is only working when dashboard is opened for the first time.

**Environment**
demo.thingsboard.io

**Comment by ferchinas** [comment]
Hello this is something that I have been looking to solve for a long time.
It would be nice if the `knob widget` has that option like `New Switch Control` does.
`Retrieve on / off value using method`
And you can subscribe to changes of an Attribute or Timeseries

**Comment by Ultrazombie** [comment]
Closed due to inactivity
