### ISSUE TITLE
In thingsboard dashboard Customized control widget on and off switch view is not updated

### ISSUE THREAD

**Issue by Viswanath95** [thingsboard/thingsboard#518]
Hi,
    I'm using Thingsboard V1.3.1 and i created customized control on and off switch widget in thingsboard dashboard.My problem is after receiving the telemetry value in thingsboard device the view status on and off is not updated on control widget switch in thingsboard dashboard.How to dynamically change on and off switch by fetching the telemetry value from thingsboard device.

Any suggestion will be more useful for me.

**Comment by ashvayka** [comment]
Please post the code of yourwidget somewhere and link to the code here

**Comment by Viswanath95** [comment]
The link for my customized created on and off switch control widget is given below:
https://github.com/Viswanath95/Button-widget/blob/readme-edits/README.md

**Comment by Viswanath95** [comment]
Hi,
In below link i'm sending my customized button widget code:
https://codepen.io/Viswanath95/pen/WdaZyJ

My problem is I want to dynamically on and off this switch by fetching device telemetry value in thingsboard.How can I achieve this use case?

**Comment by Viswanath95** [comment]
From my python file i'm sending true or false to thingsboard device value by passing 1 or 0.
By creating a customized on/off switch widget on settings schema part i'm using default on/off switch settings schema code given on control widget on/off switch in thingsboard.

**Comment by colognebroker** [comment]
> From my python file i'm sending true or false to thingsboard device value by passing 1 or 0.
> By creating a customized on/off switch widget on settings schema part i'm using default on/off switch settings schema code given on control widget on/off switch in thingsboard.

I am Thingsboard Newbee , did you achive a switch button to control a telemetry ?
I would be very pleased for an example code ....
Greets from Germany

**Comment by Karabiy** [comment]
you can refer to the RPC guides regarding those: https://thingsboard.io/docs/user-guide/rpc/
also, you need your device to support the RPC requests and have the proper method to be used for the case of your device. I think that those are being described within the device docs or can be done via custom firmware. 

> > From my python file i'm sending true or false to thingsboard device value by passing 1 or 0.
> > By creating a customized on/off switch widget on settings schema part i'm using default on/off switch settings schema code given on control widget on/off switch in thingsboard.
> 
> I am Thingsboard Newbee , did you achive a switch button to control a telemetry ?
> I would be very pleased for an example code ....
> Greets from Germany
