### ISSUE TITLE
 How to set default entity in dashboard state

### ISSUE THREAD

**Issue by ferchinas** [thingsboard/thingsboard#5183]
* UI
 
**Description**
Hello: I would like to be able to select the first device by default in the panel status when the user enters the dashboard. 
So that the widgets show the device information instead of the message "Target device is not set".
Is it possible to achieve this by making a custom widget based on the Entities table widget, adding some code in the self.onInit () function?

Even better would be to be able to remember the last device selected by the user.
Is there a way to persist data in the client's browser to do this?

**Now it looks like this**
![Screenshot_70](https://user-images.githubusercontent.com/30049639/131759032-f1f494da-d42a-462e-9ea9-d3fbe797433b.png)

**I want it to look like this**
![Screenshot_71](https://user-images.githubusercontent.com/30049639/131759037-5bafeaa3-e7e2-43c0-b2fa-4749e0e2237d.png)

**Environment**
 * OS:  name and version
 * ThingsBoard: 3.3.0
 * Browser: Firefox

**Comment by ferchinas** [comment]
Thanks for the reply @JacksonBowe 
I have another dashboard built as you say.
But I want to do it this way to be one click away when you want to check multiple devices.

**Comment by JacksonBowe** [comment]
@ferchinas yeah that's understandable. The only other way I can think of doing this would be with a customer widget as you say.

It would be a gross solution, and I'm talking extremely gross.

In the onInit() function of the entities list, if you pull the datasource, get the first entity, and then programatically update the dashboard state with the new entity with.
```
function updateDashboardState() {
    var params = {
        entityId: entityId,
        entityName: entityName,
        entityLabel: label,
    };
    widgetContext.stateController.openState(widgetContext.stateController.getStateId(),
        params, false);
}
```

Although you would first need to check if there is a currently allocated state entity, otherwise you will get stuck in a loading loop.

To be honest, this probably wouldn't even work due to loading delays. That's the best I've got unfortunately, good luck with it!

**Comment by ferchinas** [comment]
I was willing to receive a gross proposal :)
I replaced the `widgetContext `with `self.ctx` in your suggested code because in the javascrit part of the custom widget I have not access via `widgetContext`.
Do you know how I can access the list of devices of a certain `entity alias` to be able to pass them as a parameter to `openState`?
Thank you very much for your help

**Comment by JacksonBowe** [comment]
@ferchinas 
As in, an `entity alias` which isn't attached to your current widget? I'm not sure how to do that. You can see a list of all resolved entity aliases under `self.ctx.dashboard.resolvedAliases` but I don't know if you can see all the entities they contain.

**Comment by ferchinas** [comment]
@JacksonBowe I was finally able to solve it in the way you mentioned above, thank you very much for the information.
I attach the code and the widget to [download ](https://github.com/thingsboard/thingsboard/files/7130309/auto_select_entity.zip) in case someone else needs it

```
var initialized = false;

self.onDataUpdated = function() {
    updateDashboardState();
};

function updateDashboardState() { 
    if (initialized) 
        return;
        
    var datasource = self.ctx.datasources[0]; 
    if (datasource != null && self.ctx.stateController != null) {
        if (self.ctx.stateController.getStateParams().entityName == null) {
            var params = { 
                entityId: { id: datasource.entityId, entityType: datasource.entityType}, 
                entityName: datasource.entityName, 
                entityLabel: datasource.entityName
            };
            self.ctx.stateController.updateState(self.ctx.stateController.getStateId(), params, false);
            initialized = true;
        }
    }
}
```

**Comment by inidaname** [comment]
Hello @ferchinas and @JacksonBowe 
Thanks for the code you shared and guide.
I will like to do this without showing the initial state of the dashboard just loading then show the default entity.
Is this possible?
