### ISSUE TITLE
[Bug] Could not transfer artifact com.sun.winsw:winsw:pom:2.0.1 from/to jenkins

### ISSUE THREAD

**Issue by tulasitubati** [thingsboard/thingsboard#5184]
**Describe the bug**
Could not transfer artifact com.sun.winsw:winsw:pom:2.0.1 from/to jenkins (http://repo.jenkins-ci.org/releases): Transfer failed for http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/2.0.1/winsw-2.0.1.pom 308 Permanent Redirect

i tried by using mvn clean install -DskipTests  can any one please help me

**Comment by trikimiki** [comment]
Try switching Jenkins repo URl from http to https:
find the module that is failing to build
go to the respective module _pom.xml_ file
change Jenkins repo from `http://repo.jenkins-ci.org/releases` to `https://repo.jenkins-ci.org/releases`
