### ISSUE TITLE
[Bug] Entity Alias Telemetry Keys not previewed in Widget Configuration

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#5188]
**Describe the bug**
In Widget Datasources Configuration no Telemetry keys are previewed, although telemetries are existing for the selected device.
This makes creating dashboards more complex, because of possible typos of keynames. Also one does not know, which telemetries are present, without taking a look into device menue.

Strangely, the preview works for both, attributes and entity metadata like e.g. name or label.

**Your Server Environment**
  * 2 Node Kubernetes Cluster on Azure
  * ThingsBoard Version 3.3 (also in previous version) 

**Expected behavior**
Telemetries are displayed in Datasources Configuration of each widget.

**Screenshots**
Device:
![image](https://user-images.githubusercontent.com/25298332/131827849-f143372e-152b-4a08-bdcb-36b6ec4d982b.png)

Entity Alias:
![image](https://user-images.githubusercontent.com/25298332/131828141-73dc8898-c283-4f5e-b6f8-594904e85338.png)

Widget Configuration:
![image](https://user-images.githubusercontent.com/25298332/131828235-f6b44714-85b4-47fa-83b6-22184b82f749.png)

**Comment by ferchinas** [comment]
@mde2017  I'm not sure about this, but you could try entering the **device name** instead of the **device id** when defining the alias

**Comment by mde2017** [comment]
@ferchinas thanks for the hint. 
But in that case the name equals the device id, to guarantee that each name is unique. The friendly device name is stored within the entity label.

**Comment by JacksonBowe** [comment]
@mde2017 I have had this issue a few times. I found it was mostly happening when I was in edit mode, and then changed to a new state, then tried adding widgets as you are. I think the entityAliases may not fully load for unless they are required by the current state.

If this sounds like what is happening to you, then I would suggest navigating to the desired state before entering edit mode.

**Comment by mde2017** [comment]
@JacksonBowe Thank for your help. Unfortunately it still doesn't work if I use the default state, without any state change. So there must be another reason for this behaviour.

**Comment by mde2017** [comment]
I could figure out, why it's not working. Initially we configured TB to use Postgres to store latest telemetry data. Later we changed this config to use Cassandra instead. After that change also Telemetry keys aren't previewed any longer.

I was able to reproduce this on a local installation.
Any idea how to fix this?
