### ISSUE TITLE
Date format typo

### ISSUE THREAD

**Issue by hertell** [thingsboard/thingsboard#5191]
Hi,

During a merge of my old config file with a new, i stumbled into this. I think that the date format should be YYYY.MM.DD instead of YYYY.MM.dd

https://github.com/thingsboard/thingsboard/blob/6abbea1f91a470839631201d99c815eb58f058e7/application/src/main/resources/thingsboard.yml#L527

**Comment by ashaforost** [comment]
Hi there, this is actually a bug fix, as DD refers to the number of days since the start of the year and dd is a particular day of month. This fix doesn't affect anything, except for the Elasticsearch logs.
