### ISSUE TITLE
[Bug] :

### ISSUE THREAD

**Issue by pegah-mir** [thingsboard/thingsboard#5195]
**Describe the bug**

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pegah-mir** [comment]
Bug
Hello
when I update tenant , device or... , I can edit createtime in api .
Thanks
@vvlladd28 @ashvayka

**Comment by ashaforost** [comment]
Hi there,

Please clarify your issue and describe the expected behavior and the behavior you're seeing.

**Comment by pegah-mir** [comment]
Hello
I used to api of creating tenant in postman.
sample:
http://thingsboard/api/tenant

body:
{"id":{"entityType":"TENANT","id":"tenantId"},"createdTime":1631446438611,"title":"pegah"}

if you enter this body without createdTime then save createtime with zero
It`s a bug ,I don`t have to update createtime 
{"id":{"entityType":"TENANT","id":"tenantId"},"title":"pegah"}

Thank a lot

@vvlladd28 @ashvayka

**Comment by pegah-mir** [comment]
Bug
Hello
when I use thingsboard platform in desktop and I create a deviceProfiles .I select a queue name but don`t save .In edit of deviceProfiles ,I can change and save queue name.
thingsboard community , version 3.2.0
Thanks
@vvlladd28 @ashvayka

**Comment by pegah-mir** [comment]
Hello
Can you help me,please?
Thanks

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
