### ISSUE TITLE
[Bug] Attributes Updated Event not triggered in Root Rulechain

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#5197]
**Describe the bug**
As part of a customer's project we have to export metadata, attributes and telemtries into an external message Queue (e.g. RabbitMQ). This export has to be triggered on each data change. So I tried using the "Message Type Switch" and the "Attributes Updated" Event. After changing the attribute value via Input Widget (from Dashboard) and also via Device Attributes Menue no event is triggered. (Tested with Debug Mode in Rulechains).

**Your Server Environment**

* own setup
  * Azure cloud & local infrastructure
  * tested with ThingsBoard Version 3.2.2 & 3.3.0
  * Ubuntu & CentOS

**To Reproduce**
1. Create Device and Attribute
2. Extend Root Rulechain by Adding Attributes Updated Event and Transformation Script Node
3. Activate Debug Mode for Transformation Script Node
4. Change Attribute value via Dashboard or Device Menue

**Expected behavior**
The Attributes Updated Event is triggered properly, allowing to realize usecases as mentioned above.

**Screenshots**

Changes of Root Rulechain:
![image](https://user-images.githubusercontent.com/25298332/132197948-978a8a1a-26bd-4dde-8e40-459f5df9fe70.png)

Sample Device with Attribute:
![image](https://user-images.githubusercontent.com/25298332/132198143-0619f01d-cb87-4374-acb9-2d1a7960f3ca.png)

**Comment by ashaforost** [comment]
Hi there,

By design, the update attributes input widget doesn't use the root rule chain to ksave an attribute, but it directly sends a save attributes request to the server. Thus, you can't use a message type switch rule node with the input widgets.

**Comment by mde2017** [comment]
Hi @ashaforost,

thanks for your help. I can now unterstand why it's not working as expected.
Do you know of any workarounds to still realize the mentioned usecase?

**Comment by eeitnn** [comment]
> Hi there,
> 
> By design, the update attributes input widget doesn't use the root rule chain to ksave an attribute, but it directly sends a save attributes request to the server. Thus, you can't use a message type switch rule node with the input widgets.

Well, then why does it work for me (PE 3.3.0)?

**Comment by JacksonBowe** [comment]
Yeah this issue should not be closed. I'm currently using Boolean Value Input Widgets and they are posting ATTRIBUTES_UPDATED msgType into my root rule chain. 

PE 3.1.1

**Comment by eeitnn** [comment]
I think the actual issue is that the event-log, displayed in debug-mode is strongly delayed
