### ISSUE TITLE
need bars for dashboard

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5201]
widgets on dashboard are very easy to chaos when sceen sized changed, so we need a horizontal bars and verical bars to keep those widgets on their position. a horizontal bars and a verical bars widgets.

**Comment by JacksonBowe** [comment]
It's not clear what you are trying to achieve. Widgets do not move around on their own.

**Comment by trikimiki** [comment]
Can you please provide screenshots with steps to reproduce?

**Comment by jasonlee9900** [comment]
if you make vertical menus by HTML card on the left side of the dahsboard, and put gauges, cards, charts on the righ side of the dashboard, when in mobile phone view, the life side menu will insert into right side widgets by chaos, I hope can show menu first then other widgets in next, not like that: menu button1, menu button2, gauge 1, gauge2, menu button3, card1, menu button 4, etc. chaos on small screen. if there is a vertical bar to hold life side menu, then it will show all menu buttons first and other widgets all show below the menu buttons on mobile phone screen.

**Comment by jasonlee9900** [comment]
or sometimes we designed all control button on the life side in a vertical line, and timeseries cards on righ hand of dashboard. And when screen size changed, that vertical line control widgets will insert into life side timeseries widgets in chaos. normally , we want it show all control widget first, then show timeseries widget later when screen size changed to a small screen.

**Comment by jasonlee9900** [comment]
sorry, I found solution, there are mobile setting for widget order, that solve the problem. thanks.
