### ISSUE TITLE
label widget conflict wieh HTML card

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5204]
if one page have a lot of label widgets, and each label widget has many data, when you open it from dashboard list, and then switch immediately to another page full of HTML cards before all label widgets shows up data, then the second page (full of HTML cards) will chaos, and refresh the page still chaos.  But if we waiting all data finished shows up on the first page (full of label widgets), then switch to the the second page (full of HTML cards) will show nice without chaos. 
This bug happens on tb3.3, and tb3.2.0 do not have such problem, maybe related to cache etc.

**Comment by LeoMorgan113** [comment]
Hi @jasonlee9900,

Maybe you could provide screenshots for illustrating the situation or exported dashboard?

**Comment by jasonlee9900** [comment]
this problem maybe because I try to make HTML card height to it's limit 7000px by change the gride.
If I use TB3.3 to make this HTML card will not have this problem, but height is limited, so I copy that long HTML card from my TB3.2.0 project, so caused this prblem. 
nomally, when switch from "overview" menu to "help" menu should looks like below:
![22](https://user-images.githubusercontent.com/50089284/134911968-52b5b3e3-635a-42df-b9bc-54166959b2d7.PNG)

but if click too quick befor all label widgets' data show up in "overview" page, then "help"page will show like below:
![11](https://user-images.githubusercontent.com/50089284/134912320-b543ca9a-26ab-482d-940b-42001cba9ca4.PNG)

**Comment by jasonlee9900** [comment]
As you have designed the new help widget for 3.3.1, I will discard this HTML card for help documentation, and try the new help widget. thanks.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
