### ISSUE TITLE
fix button for all innner pages

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5206]
so far I use HTML card for menu buttons, but headache is I need to make/modify each inner states/page's HTML card button menu. 
each time I add a new state/inner page, all HTML button need to be modified again. 
Is that possible to fix it, one time put a HTML button there, is works for all inner states/pages?

**Comment by vvlladd28** [comment]
Hi, @jasonlee9900
This functionality is available within the dashboard. To make one widget that will be displayed on different the dashboard states you need:
1. Right-click on the selected widget
2. Choose - **Copy  reference**
3. Go to the right state
4. Choose - **Past reference**
