### ISSUE TITLE
[Question] Is it possible to do API calls in custom widgets, that aren't sent client wise but fetched using the thingsboard server?

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#5207]
**Component**

 * UI
 * Custom widgets

**Description**

I am trying to use an API inside a custom widget, but the problem is that I don't want to put this API publicly accessible.
I can access the API when i'm on the same network, meaning the widget works perfectly then, untill i'm on a different network / mobile network.
I think this would be a bit similar to the "RPC" calls, but not to the device, but asking the thingsboard instance to fetch something and send that data back to the client.

**Environment**

 * ThingsBoard: version 3.2.2

EDIT:

I did find this: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/get-weather-using-rest-api-call/
but I want to do POST too and not continiously request data and save it in a database.

**Comment by dhaval2017** [comment]
@DejonckheereWard do you know about services in custom widget?

**Comment by DejonckheereWard** [comment]
> @DejonckheereWard do you know about services in custom widget?

Services in custom widgets?

**Comment by jonrot1906** [comment]
Just make a RPC request from the client to the ThingsBoard server and process it through a rule chain. You can follow this tutorial [here](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-reply-tutorial/)
Part of the rule chain could be the "rest api call" node where you can also post data (changing the request method).
