### ISSUE TITLE
[Question] How to send fw_state with protobuf?

### ISSUE THREAD

**Issue by nguyenlam185** [thingsboard/thingsboard#5210]
**Description**
Hi guys,
My task are dealing with Protobuf and I am able to send telemetry messages with the following proto schema:

```
message Telemetry
{
    optional string current_fw_title = 1;
    optional string current_fw_version = 2;    
    optional string fw_state = 3 [json_name = "fw_state"];
    optional string fw_error = 4 [json_name = "fw_error"];

    optional uint32 temperature = 5;
    optional double humidity = 6;
    optional float illumination = 7;
}
```

Now come to the OTA part. I cannot send the Firmware state to ThingsBoard for one reason: The key names are interpreted as CamelCases. For example when I try to publish **fw_state** by the following snippet, the **Lastest Telemetry** will show: 
**fwState** - **UPDATED**, and the information in Firmware Dashboard are not changed accordingly.

```
Telemetry tele;
tele.set_fw_state("UPDATED");
std::string proto;
tele.SerializeToString(&proto);
mqtt.publish("v1/devices/me/telemetry", proto);
```

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: v3.3.0 CE
 * Browser: Chrome

Please anybody give me some advice.
Thank you so much for spending time on my issue

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
