### ISSUE TITLE
[Question] Devices not show latest telemetry

### ISSUE THREAD

**Issue by hodinhtan** [thingsboard/thingsboard#5211]
**Component**

 * UI

**Description**
Devices not show latest telemetry even that rulechain show data coming.

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard:  CE 3.2.2
 * Browser: Chrome Version 93.0.4577.63 (Official Build) (64-bit)

Data incoming in rule chain.
![Screenshot from 2021-09-08 12-24-38](https://user-images.githubusercontent.com/32461398/132451324-74b386fb-7823-4630-86e2-2ebc10b7cecb.png)

But in device no latest telemetry data show.
![Screenshot from 2021-09-08 12-27-34](https://user-images.githubusercontent.com/32461398/132451565-ffc306f1-e544-452d-84bc-233608e70430.png)

Anyone have this issue. I used to worked at 3.1 version.
Thank you

**Comment by JacksonBowe** [comment]
@hodinhtan Is that first screenshot you have of a "Save Timeseries" rule node?

If not, you need to route the output of that node into a "Save Timeseries" node

**Comment by hodinhtan** [comment]
> @hodinhtan Is that first screenshot you have of a "Save Timeseries" rule node?
> 
> If not, you need to route the output of that node into a "Save Timeseries" node

Yes it is "Save Timeseries" node. 
For more information, I also have this issue in Device profiles tab
![Screenshot from 2021-09-08 12-39-03](https://user-images.githubusercontent.com/32461398/132452645-daeb8d96-5246-42cf-b4a0-571ffbc54be0.png)

**Comment by JacksonBowe** [comment]
If you don't mind, would you be okay with posting the whole rule chain for that device profile?

**Comment by hodinhtan** [comment]
@JacksonBowe  I use default rulechain from thingsboard CE 3.2.2. 
I tested with docker version seems work normally.
The issue above occur by build from source code version.
I guess i would use docker version.

Regards.

**Comment by JacksonBowe** [comment]
Ok, it's strange that you're getting this issue then. Best of luck for a solution!

**Comment by hodinhtan** [comment]
I fixed this problem.
It worked normally by localhost deployment.
so that I find out that problem come from my deployment, websocket can't use in my server configuration. I used wrong nginx config.

so that I follow this setup : https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

I would like to close this. 
Thank you.
