### ISSUE TITLE
Hierarchy widget with relation of ownership

### ISSUE THREAD

**Issue by serifis84** [thingsboard/thingsboard#5213]
**Component**
 * UI

**Description**
Is there a way to use Hierarchy widget based on ownership and not on relations? To reproduce the customer hierarchy builtin dashboard but with less components (only customers, subcustomers, usrers). Could it be possible to import this builtin dashboard in a custom widget?

**Environment**
 OS:  Ubuntu Server 20.04 LTS
ThingsBoard: 3.3.1PE
Browser: Google Chrome

**Comment by LeoMorgan113** [comment]
Hi @serifis84,

I suppose this guide will help you: https://blog.thingsboard.io/2019/04/how-to-build-your-own-entity-empire.html?m=0
If default 'Hierarchy widget' is not cover your needs, you could create a custom one.

**Comment by serifis84** [comment]
Thank you for your reply @LeoMorgan113 ,

I ve already watched this video, but also many other that helped me allot understanding thingsboard. I would like to make a custom dashboard for managing my customers, subcustomers, their sub-subcustomers etc. The hierarchy widget is quering by ther relation and not by the ownership (customer owns another customer who owns another one etc..). Maybe i will have to create a custom widget as you suggest
