### ISSUE TITLE
need help widget

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5216]
As HTML card only allow 7000 pix height, where we should write online help document? Every system need a help document. especially for complex thingsboard.  Athought we can let customer to go to thingsboard.io to read help document, but every system are specially designed for special purpose, we do need some good place to write help documents.

**Comment by jonrot1906** [comment]
What about using iframe and a separate bookstack instance? Alternatively use different dashboard views (i.e. a main view poinint to different subtopics).  Didn't test, but using `<div class="col" style="overflow:auto;">` might also be possible.

**Comment by LeoMorgan113** [comment]
Hi @jasonlee9900,

In the v3.3.1 was added Markdown/HTML widget, which can be used for writing documentation: https://thingsboard.io/docs/reference/releases/
I suppose that it's what you need.

**Comment by jasonlee9900** [comment]
yes, that's good!
