### ISSUE TITLE
Customize dashboard URLs

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#522]
At the moment the dashboard URL is a GUID, which is not user-friendly. I would like to be able to optionally add an alias. Thus, when demoing my boards to others, I can do so by typing the address from memory.

For example `https://example.com/dashboards/4a3b2590-f199-11e7-b94f-bf5fb2576e51` -> `https://example.com/dashboards/kitchen`.

In the context of multitenancy, perhaps the URL should be `dashboards/<tennant alias>/<dashboard alias>`, for example `https://example.com/dashboards/king/first-castle`.

Another point related to URLs is the title of the page, at the moment it is globally the same for every dashboard. So if you open several dashboards in several tabs, they look the same, so you cannot figure out which is which without actually opening it.

This is also clear when you type something in the browser's address bar:
![image](https://user-images.githubusercontent.com/295338/34729115-16c5abb0-f55c-11e7-816a-10c77c6400bd.png)

All the black areas contain the same text, the only thing that is unique is the GUID, which is a bit difficult to memorize, unless you're an elephant :-)

So, this boils down to two things:

- [ ] allow dashboards to be accessed by alias, not just by the GUID
- [ ] change the `title` of each dashboard, so they are easier to discriminate

**Comment by NarinLab** [comment]
Any update on this?

**Comment by LeoMorgan113** [comment]
Hi @ralienpp @NarinLab 

I may suppose that this is not possible due to name conflict.
For example, you will have 2 dashboards with the same name 'Kitchen', but 1 for 'Office 1' and the second for 'Home' group.
So there will be a misunderstanding.
That's why your dashboard must have a unique URL address.
In the other case, you have to set your dashboard name unique.
