### ISSUE TITLE
[Question] Why return value of putIfAbsent ignored

### ISSUE THREAD

**Issue by formerly11** [thingsboard/thingsboard#5223]
**Component**

 * Generic
 
**Description**
In method org.thingsboard.server.common.transport.service.DefaultTransportService#registerSyncSession，why return value of putIfAbsent ignored

**Environment**

 * ThingsBoard: 3.2.2

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
