### ISSUE TITLE
[Question] Simple neon gauge option The colors for the indicator using boundary values

### ISSUE THREAD

**Issue by Xab01** [thingsboard/thingsboard#5226]
Dear all, 

I'm trying to configure a simple neon gauge. The info from time serie is displayed correctly.

I try to use in advances options the use precise value for the color indecator. 
If I use the Predefined value ==> everything is working like expected
If I try to use the Value taken from entity attribute ==> the value aren't taken into account. I try to use server attribute ==> is it possible ?

![image](https://user-images.githubusercontent.com/6254435/132826438-e5a94b1b-af3b-483b-b884-b91e8f984169.png)

Is it the correct way to proceed?

Xavier

**Comment by ChantsovaEkaterina** [comment]
Hello, @Xab01 
When selecting the _Value taken from entity attribute_, you need to specify the _**Source entity alias**_ also, in another case widget doesn't know from which entity to take the _Source entity attribute_.

**Comment by Xab01** [comment]
Thnaks a lot
It's works like expected !

Best Regards
Xavier
