### ISSUE TITLE
[Bug] Compile problems with release-3.3

### ISSUE THREAD

**Issue by tfft** [thingsboard/thingsboard#5234]
I'm unable to compile release-3.3 on Ubuntu-20.04 -- I get the error noted below and the error is within an infinite loop from the looks of it.  I followed the instructions noted on the [Thingsboard website](https://thingsboard.io/docs/user-guide/install/building-from-source/); downloaded 'release-3.3' source from git and then ran 'mvn install'.

In passing, the instructions noted in the URL should also possibly include the various 'skip' options.

**Server Environment**
  * Own setup (Linux - Ubuntu-20.04)
  * ThingsBoard Version 'release-3.3'
  * `Linux mylinux_box 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**To Reproduce**
Steps to reproduce the behavior, in a terminal/xterm:
```
1. git clone https://github.com/thingsboard/thingsboard.git
2. cd thingsboard
3. git checkout release-3.3
4. mvn clean install
```

**Expected behavior**
A proper compilation of the source in order to generate the requisite files to run thingsboard.

**Additional context**
The error report was noted [here](https://stackoverflow.com/questions/69153777/thingsboard-release-3-3-compile-problem) and it was suggested that I enter a bug report (which is what I'm doing here).  A number of other miscellaneous comments,

1. A work-around is noted in the link above ('mvn -DskipTests install') - it would be nice to know what other -D options exists for those of us who are 'mvn' novices
2. During the build/compile process is there a way to specify a different port in lieu of the default 7070 (conflicting with anydesk) ?  Again, what are the various options available for this and other "features" - is this listed somewhere ?  Can it be included or documented please (config file or command-line or ...) ?
3. The README file (in the source root) should incorporate all this info or a link should be created to discuss all these items what is there now is rather minimalistic

Here are the errors, that I end-up with,

> Warning: Nashorn engine is planned to be removed from a future JDK release
> 2021-09-12 20:54:53,796 [main] ERROR o.t.s.s.edge.rpc.EdgeGrpcService - Failed to start Edge RPC server!
> java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:7070
>         at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328)
>         at io.grpc.internal.ServerImpl.start(ServerImpl.java:179)
>         at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
> **..[skip over many statements similar to above]..**
> Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
> 2021-09-12 20:54:53,796 [main] WARN  o.s.w.c.s.GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adminController': Unsatisfied dependency expressed through field 'edgeGrpcService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'edgeGrpcService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to start Edge RPC server!
> 2021-09-12 20:54:53,813 [main] ERROR o.s.boot.SpringApplication - Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adminController': Unsatisfied dependency expressed through field 'edgeGrpcService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'edgeGrpcService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to start Edge RPC server!
>         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
>

**Comment by trypzz** [comment]
Hi,

The root cause if your issue is : bind(..) failed: Address already in use.

Check which process binded to this port by execution this command:

sudo lsof -n -i :7070

Or change RPC port in thingsboard configuration.
