### ISSUE TITLE
[Question] How to load with labeling settings with scripts?

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#5235]
**Component**

Thingsboard PE

**Description**

Is it possible to change white labeling settings via any automated system? Ideally I would just put my custom translations, white labeling, etc... as files but I don't think it's possible.

I also looked into the REST API but I don't see any section related to white labeling. Did I miss it? (that way I could at least make some curl calls to feed my instance after installation).

**Comment by ashaforost** [comment]
Hi there,

Please refer to the [REST API](https://thingsboard.io/docs/reference/rest-api/) article, where you'll find the steps to log in with swagger and see all the requests available:
![image](https://user-images.githubusercontent.com/47900737/133256563-5eef9964-255a-4638-bdfb-80351803ce98.png)
