### ISSUE TITLE
[Bug] Fails to connect to upgraded version of Thingsboard

### ISSUE THREAD

**Issue by rosas-github** [thingsboard/thingsboard#5239]
**Describe the bug**
I want to upgrade thingsboard version 3.2.2 to version 3.3.0. I follow the steps of the [guide](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/) successfully, but, when I try to connect to the localhost:8080 it fails, never connects to the server. I try to downgrade thingsboard to version 3.2.2 and I runs correctly again.

**Your Server Environment**
* demo.thingsboard.io

* own setup
  * local infrastructure deployment
  * ThingsBoard Version 3.2.2 to 3.3.0
  * Ubuntu 20.04 LTS

**Your Client Environment**
**Desktop:**

* OS: Windows 10
* Browser Chrome
* Version 

**Smartphone (please complete the following information):**
* Device: PC
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version 93.0.4577.63 (Official build) (64 bits)

* Connectivity
  * MQTT
  * HTTP

**Expected behavior**
Run the thingsboard demo and continue working on it.
But I get the following warning when I start thingsboard service: The unit file, source configuration file or drop-ins of thingsboard.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by jonrot1906** [comment]
That might be because of added Edge functionality in version 3.3.0 which i.e. exposes port 7070, causing your ThingsBoard systemctl file to change. Why not just run `systemctl daemon-reload` (with root priviledges) and try again? Might solve your issue. If not, please provide the output of `systemctl status thingsboard`.

**Comment by rosas-github** [comment]
I tried it several times. I tried again a few minutes ago. You can see the results of `sudo systemctl daemon-reload` and `systemctl status thingsboard`.
![daemon-reload](https://user-images.githubusercontent.com/61634031/133132177-8195b18d-d09a-4ae4-9cdc-97aca639391b.png)
![status](https://user-images.githubusercontent.com/61634031/133132197-0d7075ff-3d54-4f24-980c-6bfdf3005962.png)

**Comment by rosas-github** [comment]
Also, I checked for the ports used in my server and it seems like 7070 isn't being used.
![ports](https://user-images.githubusercontent.com/61634031/133133003-1648290d-7e32-42ff-8a07-80f2093844da.png)

**Comment by Backdraft007** [comment]
Why is there a nginx?
What says /var/log/thingsboard/thingsboard.log?

**Comment by rosas-github** [comment]
I don't know why there is a nginx at port 1883.
I looked in /var/log/thingsboard/thingsboard.log and it doesn't really show anything suspicious nor reports anything wrong.
What I wonder is why there is no communication with ports 8080 and 7070. Given the fact that I try to communicate with port 8080 to communicate with the thingsboard instance from my browser. (I tried loggin to ports 8082 and 8083, without success)

**Comment by rosas-github** [comment]
This is are the results of `sudo netstat -tulpn` applied to thingsboard 3.2.2. and 3.3.0 that I installed. Clearly, version 3.3.0 isn't connecting to ports 8080 and 5683.

Thingsboard v3.2.2
![netstat_v3 2 2](https://user-images.githubusercontent.com/61634031/133264145-970df92e-345a-4b1b-8b6c-f383a701e909.png)

Thingsboard v3.3.0
![netstat_v3 3 0](https://user-images.githubusercontent.com/61634031/133264160-7089a219-567f-42f6-8e03-f7e04ddd2fb1.png)

**Comment by jonrot1906** [comment]
I think you don't see any port 8080 bindings because Thingsboard never comes to the point to start its http server because of the failure. Did you read out the whole line where it says "Illegal reflective access [...] to field"? Might be interesting which field is faulty. Also, are you using Thingsboard + Postgresql or Thingsboard + Hybrid Cassandra/Postgresql?

**Comment by rosas-github** [comment]
Yeah, I checked the illegal reflective access, but it appears in the version 3.2.2 as well. So I didn't really mind that warning.
I'm using Tb + Postgresql. And it is correctly configured.

**Comment by Backdraft007** [comment]
I have running a CE 3.3.1.
I have only java process with port 8080 and 1883. Can you have a look in your thingsboard.yml which services uses the 8082 and 8883?

**Comment by rosas-github** [comment]
If I install (from zero) thingsboard CE 3.3.1, the service using 8883 dissapears, meaning that it only happens to CE 3.3.0.
In both cases, port 8082 is used by 11jdk. It doesn't happen when I'm running CE 3.2.2.
Although I found out something interesting running `sudo lsof -i`: it seems like thingsboard tries to connect to aws unsuccessfully and that's why it doesn't bind to 8080. This only happens with CE 3.3.0. and 3.3.1.
![lsof](https://user-images.githubusercontent.com/61634031/133434996-855e3200-cf81-4801-809e-d2d1f7cd6349.png)
![lsof2](https://user-images.githubusercontent.com/61634031/133435175-b1bbe8d3-7986-4071-9281-2849e8f740bd.png)

**Comment by trikimiki** [comment]
You might want to check `/var/log/thingsboard/thingsboard.log` file after you try to start the ThignsBoard. It seems like it is stuck on some error or tries to unsuccessfully reconnect to some endpoint.

Also, do you have any special configurations? ThingsBoard should not connect to any AWS endpoint by default.

**Comment by rduivenvoorde** [comment]
I also ran into this problem... 3.2.2 to 3.3.1 fails with stacktrace:

```
Starting ThingsBoard upgrade ...
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.3.1)
 ===================================================

Starting ThingsBoard Upgrade from version 2.4.2 ...
Upgrading ThingsBoard from version 2.4.2 to 2.4.3 ...
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:233)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:154)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        ... 17 common frames omitted
Unexpected error during ThingsBoard installation!

```

https://github.com/thingsboard/thingsboard/issues/5126 notes that there was a Postgres version upgrade from 11 to 12... and:
"Additionally you can create dump of postgres 11 database (thingsboard 3.2.2), save to some dir on your host, download thingsboard 3.3.0 image with postgres 12, restore data from your dump to the new database and run upgrade script."

Which is not so nice as an upgrade path :-(
But I will try that.

**Comment by rduivenvoorde** [comment]
@jonrot1906 I started the official thingsboard/tb-postgres CE edition Image some months ago with separate volumes.

In the data volume mounted (the one with a 'db' dir in it, and a .firstlaunch and .upgradeversion in it), the .upgradeversions (created by the image/container I presume):
```
3.3.1   
``` 
And within the container asking for the postgres version:
```
thingsboard@c1b7c82deab5:/$ psql
psql (11.11 (Debian 11.11-1.pgdg+1))
Type "help" for help.

thingsboard=# select version();
                                                          version                                                           
----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.11 (Debian 11.11-1.pgdg+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
(1 row)

```

**Comment by jonrot1906** [comment]
Yeah, unfortunately the newest version of the ThingsBoard Docker upgrade script sets .upgradeversion to 3.3.1, even if the upgrade was not successful. So you're running 3.2.2 now, right? You can easily migrate your data doing:
```docker run --rm -v ~/.mytb-src/db:/var/lib/postgresql/11/data -v ~/.mytb-dst/db:/var/lib/postgresql/12/data -e PGUSER="thingsboard" -e POSTGRES_INITDB_ARGS="-U thingsboard --local=C.UTF-8" -e POSTGRES_PASSWORD="postgres" tianon/postgres-upgrade:11-to-12``` as suggested in #5214.
Your data structure is then upgraded to Postgresql 12 standard and it should work.
To sum it up, the steps to do are:

1. Set right version of `.upgradeversion` (to 3.2.2)
2. Migrate your data using the above command
3. Try the docker upgrade again as suggested in ThingsBoard docs.
4. Enjoy.

**Comment by rduivenvoorde** [comment]
@jonrot1906 thanks for the thorough answer! Will try this.
