### ISSUE TITLE
Attribute edit JSON array validation fails [TB v3.3.0]

### ISSUE THREAD

**Issue by AdrienAdB** [thingsboard/thingsboard#5240]
**Describe the bug**

Edit attribute JSON array impossible 

**Your Server Environment**

* own setup
  * cloud
  * ThingsBoard Version 3.3.0
  * OS Name and Version Ubuntu 20.04

**Your Client Environment**

* OS: [e.g. iOS]
* Browser Brave, Firefox, Chrome
* Version latest

**To Reproduce**

- Edit Device
- Shared attribute
- JSON type
- Extend window (edit JSON)
- Edit JSON attribute as an array
```json
[
   {"name": "A"},
   {"name": "B"}
]
```
- Validation fails, unable to save.

**Screenshots**

<img width="454" alt="Screenshot 2021-09-14 at 18 17 21" src="https://user-images.githubusercontent.com/22590767/133249172-d7ac8742-3477-4955-b0f1-973733f2541f.png">

**Comment by jonrot1906** [comment]
I reckon you need to define it like:
```
{"key1":
    [
        {"name":"A"}, 
        {"name":"B"}
    ]
}
```

**Comment by gao270615179** [comment]
Why not support json array?
