### ISSUE TITLE
[Question] Using edge instances

### ISSUE THREAD

**Issue by cemsina** [thingsboard/thingsboard#5241]
**Component**

 * Installation
 * Generic

**Description**
Hello there,
How do I start thingsboard ce to use edge instances? When I open it, I can enter the /edgeInstances page manually, but it does not appear in the menu. Also, I couldn't find the module for edge instances. Is edge instance module part open-source?

**Environment**
 * OS:  Windows and CentOS
 * ThingsBoard: 3.3
 * Browser: Chrome

**Comment by Backdraft007** [comment]
I think it is also available in CE. Clear your Browser-Cache and reload your site.

**Comment by cemsina** [comment]
I found the EDGES_ENABLED variable and set its value to true. It appears in the interface. But I couldn't find how to start edge server. Isn't the edge server connecting to the thingsboard CE?

**Comment by jonrot1906** [comment]
Did you already obtain a license? Follow [this](https://thingsboard.io/docs/edge/provision-edge-on-server-ce/) and [this](https://thingsboard.io/docs/edge/getting-started/getting-started-ce/) tutorials.
You then need to install Thingsboard edge onto your desired device.

**Comment by cemsina** [comment]
I want to examine the edge instance code. Why do I need a license?

**Comment by volodymyr-babak** [comment]
@cemsina You must have to obtain a license to examine ThingsBoard Edge despite the platform you are connecting to - CE, PE or Cloud. We offered 30 days trial for ThingsBoard Edge so you can examine and evaluate it.
