### ISSUE TITLE
[Question] Hierarchy widget custom action get node selected

### ISSUE THREAD

**Issue by serifis84** [thingsboard/thingsboard#5247]
**Component**

 * UI

**Description**
How could i get the selected node  through custom action of hierarchy widget? I would like to delete the selected entity

**Environment**
OS: Ubuntu Server 20.04 LTS
ThingsBoard: 3.3.1PE
Browser: Google Chrome

**Comment by Katekisiv** [comment]
Hi,

In the action configuration, there is the "Action source" field. You have to choose "on node selected" in this field so you will be able to perform the custom action when clicking on the desired entity in the hierarchy.

Best regards,
Kate

**Comment by serifis84** [comment]
@Katekisiv thank you for your reply!
"On node selected" will trigger a custom action when the node is clicked. I would like to have more widget header buttons, like add or delete or edit an entity and when click them trigger a custom action. In the custom action's code get the selected nodes name or whatever

**Comment by Katekisiv** [comment]
Hi,

There is no predefined functionality to add more than one action for each node. For your purpose, the only way is to write the custom widget with the desired functionality.

Regards,
Kate
