### ISSUE TITLE
Can't subscribe to any attibrute or series from switch controls

### ISSUE THREAD

**Issue by mobulaco** [thingsboard/thingsboard#5250]
Switch Controls

 * UI
 * Generic

**Description**
Hello,

My first tests with thingsboard.

I've tried a simple switch demo with on/off messages from a node-red instance.
It seems that the card widget which subscribes to device attribute works, however switch controls which subcribes to an attribute/series not gets the current value.

Thw widget files:
[exports.zip](https://github.com/thingsboard/thingsboard/files/7173803/exports.zip)

The value is a string "on" / "off"
the getValue/attribute function is:
    `return data=="on" ? true : false;`

Everything else with RPC functions (getValue, setValue) works but I want to read the real status from fresh device attribute.

I have checked that when I change the state from switch button (or from device), the attribute has changed to correct value.

Any suggestions?

Thanks :)

**Environment**
 * OS:  ubuntu 20.04
 * ThingsBoard: 3.3.1
 * Browser: Chrome ~93

**Comment by ericarena** [comment]
same problem happen!

**Comment by mykhailokornieiev** [comment]
Hi. By design of Thingsboard, you can use either integer or boolean values for getValue in Switch Control widget, not integer.
