### ISSUE TITLE
[Bug] incorrect datapoint count report in DefaultTransportService

### ISSUE THREAD

**Issue by ByteGen** [thingsboard/thingsboard#5253]
**Describe the bug**
The datapoint counter will be submitted multiple in `DefaultTransportService

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version:  latest version
  * OS Name and Version: Linux

**curl test**

* Connectivity
  * HTTP

**To Reproduce**
1. create test device (with access token `test_token`)
2. report device timeseries in json array: `curl -v -X POST -d "[{\"temperature\": 24}, {\"other1\": 25, \"other2\": \"some\"}]" http://127.0.0.1:8080/api/v1/test_token/telemetry --header "Content-Type:application/json"`
3. open the api usage dashboard and check the Transport datapoint counter, It has increased by six, but there are actually only three data points.

**Additional context**
The problem may be caused by the following methods. The `dataPoints` calculates all of the `KvCount` in list, but it will be submitted multiple times in `packCallback`.
```
    @Override
    public void process(TransportProtos.SessionInfoProto sessionInfo, TransportProtos.PostTelemetryMsg msg, TransportServiceCallback<Void> callback) {
        int dataPoints = 0;
        for (TransportProtos.TsKvListProto tsKv : msg.getTsKvListList()) {
            dataPoints += tsKv.getKvCount();
        }
        if (checkLimits(sessionInfo, msg, callback, dataPoints)) {
            reportActivityInternal(sessionInfo);
            TenantId tenantId = getTenantId(sessionInfo);
            DeviceId deviceId = new DeviceId(new UUID(sessionInfo.getDeviceIdMSB(), sessionInfo.getDeviceIdLSB()));
            CustomerId customerId = getCustomerId(sessionInfo);
            MsgPackCallback packCallback = new MsgPackCallback(msg.getTsKvListCount(), new ApiStatsProxyCallback<>(tenantId, customerId, dataPoints, callback));
            for (TransportProtos.TsKvListProto tsKv : msg.getTsKvListList()) {
                TbMsgMetaData metaData = new TbMsgMetaData();
                metaData.putValue("deviceName", sessionInfo.getDeviceName());
                metaData.putValue("deviceType", sessionInfo.getDeviceType());
                metaData.putValue("ts", tsKv.getTs() + "");
                JsonObject json = JsonUtils.getJsonObject(tsKv.getKvList());
                sendToRuleEngine(tenantId, deviceId, customerId, sessionInfo, json, metaData, SessionMsgType.POST_TELEMETRY_REQUEST, packCallback);
            }
        }
    }
```

**Comment by ashvayka** [comment]
Hi @ByteGen , thank you for reporting this. We will fix. @YevhenBondarenko please prepare the fix.

**Comment by ViacheslavKlimov** [comment]
Hi @ByteGen.
`packCallback` is indeed submitted multiple times, but `ApiStatsProxyCallback` within it is executed only once when the last message of the pack is processed. 
We've tried to reproduce the issue with the latest TB version in master branch but everything is counted correctly...

**Comment by ByteGen** [comment]
Hi @ViacheslavKlimov, 
Do you use JSON ARRAY data (e.g. `[{\"temperature\": 24}, {\"other1\": 25, \"other2\": \"some\"}]`) when reproducing this issue? As I tested, it is counted correctly for other data formats.

**Comment by ViacheslavKlimov** [comment]
@ByteGen Yes, I've used the same payload, and data points counter was increased by 3. Please tell us what TB version you are using?

**Comment by ByteGen** [comment]
I'm using version 3.2.2. 
I've checked the `API_USAGE_STATE` historical data again:
```
 entity_type     | entity_id                            | key                    | partition     | ts            | bool_v | dbl_v | json_v | long_v | str_v
-----------------+--------------------------------------+------------------------+---------------+---------------+--------+-------+--------+--------+-------
 API_USAGE_STATE | a8a6c6f0-9e95-11eb-b73e-596bf20abbd2 | storageDataPointsCount | 1630454400000 | 1630454400000 |   null |  null |   null |      3 |  null

 entity_type     | entity_id                            | key                            | partition     | ts            | bool_v | dbl_v | json_v | long_v | str_v
-----------------+--------------------------------------+--------------------------------+---------------+---------------+--------+-------+--------+--------+-------
 API_USAGE_STATE | a8a6c6f0-9e95-11eb-b73e-596bf20abbd2 | transportDataPointsCountHourly | 1630454400000 | 1631520000000 |   null |  null |   null |      6 |  null
```

you can see that the `storageDataPointsCount` is 3, but the `transportDataPointsCountHourly` is 6.

**Comment by ByteGen** [comment]
@ViacheslavKlimov Sorry for late reply. I've checked the code, and it's indeed executed only once.
```
public void onSuccess(TbQueueMsgMetadata metadata) {
    if (msgCount.decrementAndGet() <= 0) {
        DefaultTransportService.this.transportCallbackExecutor.submit(() -> callback.onSuccess(null));
    }
}
```
I'll check the test again, and close this issue for this moment.
Thanks for your time : )
