### ISSUE TITLE
[Question] I I have not been able to receive telemetry from my devices on Thingsboard from Flespi

### ISSUE THREAD

**Issue by minhoca83** [thingsboard/thingsboard#5256]
**Component**

 * UI

**Description**

I have been having problems with receiving data from the flespi platform on Thingsboard, specifically on the demo server since this week. Before it worked perfect. Now I do not receive telemetry from my devices but I do see them on device in Thigsboard.

![Picture 2](https://user-images.githubusercontent.com/37186335/133806950-4da38c74-33c2-4772-ae50-65ba56d6d232.PNG)

But I see that something comes to Thingsboard because in the server attributes there are updates of the moment and on the side of flespi in the toolbox I see the following with each message sent.

404: stream has sent messages 09/17/2021 10:41:10 { accepted: 0 event_code: 404 origin_id: 25313 origin_type: 12 read: 1 rejected: 1 skipped: 0 timestamp: 1631889670.220231 }

![Picture 1](https://user-images.githubusercontent.com/37186335/133807005-222aa37c-8e26-406f-b594-7f90096a0b66.PNG)

![Picture 3](https://user-images.githubusercontent.com/37186335/133807038-ea293af6-eafc-4b61-915f-f61381402644.PNG)

The Rejected atribute catches my attention.

Could someone give me any suggestions that I could do?

I have already deleted everything in thingsboard and have recreated it from scratch and in the same way with the Stream of Flespi.

**Environment**

 * OS:  Win 10 Pro
 * ThingsBoard: demo.thingsboard.io
 * Browser: Firefox 92.0 (64-bit)

**Comment by ashaforost** [comment]
Hi there,

Please share the example of a request you use to send data to this device and a screenshot of a rule chain associated with it.

**Comment by minhoca83** [comment]
Hi @ashaforost, thank you for you reply. 

Somehow the problem was solved by itself yesterday. First I checked my account in flespi and I see that again my Stream to Thingboards was down, somehow thingsboard sundely rejects the connection indefinitely. So, this is not the first time that this happen, the lost of connection, I delete the Stream in Flespi and all relate with the Gateway Device's create in ThingsBoard, then I create all again to create a new connection between both platform and all begin to work fine again! 

This situation creates a concern about the integration between both platforms. I lost the trust with the platform, Thingsboard, to do a presentation with a dashboard because it's probably that I could lose the connection and I will not see my devices on the dashboard... 

About you request,  to be honest I don't know how to share the example  of a request I use to send data to this device. 

And use the rule of chain by default. I atacched a picture
 
![rule of chain](https://user-images.githubusercontent.com/37186335/134179218-2388ce27-039e-4b23-b742-f3c1de0d10fa.PNG)

**Comment by jonrot1906** [comment]
Why exactly are you using a gateway device?
Generally a self-hosted ThingsBoard installation would work more stable as there could be hundreds of thousands devices connected to the thingsboard demo server which could (!) cause spontaneous connection loss. As well, I can't evaluate your flespi setup, so maybe there is something wrong on this end.

**Comment by minhoca83** [comment]
Hi @jonrot1906, thaks for your reply!

The gateway device was because a recomendation for the integration procedure in the Flespi web page: 
https://flespi.com/kb/how-to-set-up-stream-from-flespi-to-thingsboard

Yea, I think that using the demo server could be a reason for the connection failure. 

I talked with Flespi support and they told me that for they side everything was fine.

Any way, thank very much for the answer. For the moment everythings is running fine.

**Comment by ezeroldan24** [comment]
I'm having the same problem, were you able to find a solution to the disconnection of the flespi stream?

**Comment by minhoca83** [comment]
Hi,
The cause of my problem at that time was that I had exceeded the limit of
datapoints for my type of subscription in ThingsBoard.

Appears to be that the connection between Flespi platform and things board
consume a lot of datapoints in very short time.

Hope this helps.

Best wishes
