### ISSUE TITLE
[Question] Why do we need Edge when we have CE?

### ISSUE THREAD

**Issue by WeiTangLau** [thingsboard/thingsboard#5259]
**Component**
Edge, CE

**Description**
Based on my understanding, CE includes Edge features. As such, what is the reason for running Edge? (Of course other than it is much more light weight.

Furthermore, are we allowed to use CE in production environment and provide as a service to our customers?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by jonrot1906** [comment]
ThingsBoard CE is licensed under Apache 2.0 license, read [here](https://thingsboard.io/docs/faq/).

Edge has got other functionalities than ThingsBoard CE, you can use it i.e. on devices with unstable internet connection to queue and store important data which is later published to your server running ThingsBoard CE, read [here](https://thingsboard.io/products/thingsboard-edge/).
