### ISSUE TITLE
Thingsboard cloud PE user activation does not work 

### ISSUE THREAD

**Issue by mehtajaimin** [thingsboard/thingsboard#5261]
After creating a new user the activation link gets generated but on using the link it does not redirect to the set password page. 

here is the link to activate a dummy user:
cloud.proboard.live/login/api/noauth/activate?activateToken=m9i9o2cisACxCgB0zpDaTSM6UC6Erg

**Comment by Ultrazombie** [comment]
Please provide more details on your deployment, looks like a redirect issue
