### ISSUE TITLE
[Question] moving asset from a tenant group to anothor 

### ISSUE THREAD

**Issue by muhannadA** [thingsboard/thingsboard#5265]
hi there , i was just wondering is there a way to move an asset from a tenant group to another with its historical data

**Comment by ashaforost** [comment]
Hi there,

You can change the owner of an asset in the UI or by sending a corresponding request, which you can refer to in the [Swagger UI.](https://thingsboard.io/docs/pe/reference/rest-api/)
As for the UI option, please refer to the following image:
![image](https://user-images.githubusercontent.com/47900737/135070064-f16a4129-483c-4252-81a2-5a3971b43824.png)
 As you can see, there are several options available to you, depending on your use case. Using any of these options ensures that all the asset's information will be safely transferred to the other group along with the asset itself.
