### ISSUE TITLE
MQTT Device Api doesn´t work

### ISSUE THREAD

**Issue by gzlz** [thingsboard/thingsboard#5267]
**Component**
 * Generic

**Description**
When I send telemetry via HTTP Device Api works fine but when I do with MQTT Device Api doesn´t work.

**Environment**
 * OS:  ubuntu-1804-bionic
 * ThingsBoard:  3.2.2 PE Docker installation with the port 1883 exposed in docker-compose.yml

 
![mqtt_problem](https://user-images.githubusercontent.com/19785703/134352148-6759e6e6-00f8-4259-a26c-897a5582d016.PNG)

**Comment by jonrot1906** [comment]
Do you use UFW or any other firewall? Run `sudo netstat -tulpn | grep LISTEN` on your Ubuntu system and post the output please.

**Comment by gzlz** [comment]
Hello jonrot1906,

the instance is running in a Google Cloud VM with opened TCP 1883 port in inbound rules.


![Sin nombre](https://user-images.githubusercontent.com/19785703/134392629-7629607d-9b9d-4f75-9e5d-b827a6baea34.png)
.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
