### ISSUE TITLE
[Question] Device reclaiming through MQTT API

### ISSUE THREAD

**Issue by payablez** [thingsboard/thingsboard#5269]
**Component**
 * Generic

**Description**
Nowadays, the only documented way to perform device reclaiming it's via HTTP API (https://thingsboard.io/docs/user-guide/claiming-devices/#device-reclaiming-api-request)
Is there any topic for MQTT API to perform the device reclaiming?

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.2.2 PE
 * Browser: Chrome

**Comment by Katekisiv** [comment]
Hi,

You can find it here: https://thingsboard.io/docs/reference/mqtt-api/#claiming-devices.

Best regards,
Kate

**Comment by myroslav-tb** [comment]
Hi @payablez, please check the documentation for device claiming via MQTT: https://thingsboard.io/docs/reference/mqtt-api/#claiming-devices

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
