### ISSUE TITLE
[Bug] Rule chain : IN messages without OUT messages

### ISSUE THREAD

**Issue by tdsimpro** [thingsboard/thingsboard#5271]
**Describe the bug**
As you can see on the screenshot, I've got incoming messages and not outgoing messages.

![Screenshot from 2021-09-23 11-25-50](https://user-images.githubusercontent.com/43056920/134442393-7e910b8f-8f5f-4033-8a94-2b47073ca14d.png)
* own setup
  * local infrastructure
  * ThingsBoard Version : 2.4

I know I'm running an old version but I doubt the issue is with the software itself, but more with my configuration and thingsboard.yml file ? 
I've attached my current configuration file.
Thanks in advance
[thingsboard.yml.txt](https://github.com/thingsboard/thingsboard/files/7214637/thingsboard.yml.txt)
.

**Comment by Backdraft007** [comment]
Pleas show your rule chain.

**Comment by tdsimpro** [comment]
@Backdraft007 it's the basic root rule chai
![Screenshot from 2021-09-23 17-18-14](https://user-images.githubusercontent.com/43056920/134468285-92fece8e-c5f1-4669-8f93-b681429391c8.png)
n

**Comment by Backdraft007** [comment]
Ok, thats strange. Can you find someting in thingsboard.log?

**Comment by tdsimpro** [comment]
@Backdraft007 no error and nothing special in the logs

**Comment by ashvayka** [comment]
The 2.4 is quite old and we don't have the logging that helps to investigate such issues in the old version. The only thing I can suggest is to update to the latest 2.x and better to 3.x. If you don't have custom widgets/actions it should be easy.

**Comment by tdsimpro** [comment]
@ashvayka Fair enough, we actually have a lot of customisation so can't update that easily unfortunately. Any way you could point me toward a direction so I can do some debugging myself ? So far I've been adding debug message sto ActorSystemContext and various nodes but can't find any disparities.

**Comment by tdsimpro** [comment]
FYI it was actually the debug limit per tenant + a bug preventing the log to appear anywhere. Thanks for your help

**Comment by sferguson-ISI** [comment]
> FYI it was actually the debug limit per tenant + a bug preventing the log to appear anywhere. Thanks for your help

How did you adjust that debug limit, I have the same issue.

**Comment by tdsimpro** [comment]
hey @sferguson-ISI it's in thingsboard.yml debug_mode_rate_limits_per_tenant.
You can just use ACTORS_RULE_CHAIN_DEBUG_MODE_RATE_LIMITS_PER_TENANT_CONFIGURATION as an environment variable
