### ISSUE TITLE
[Question] How to show ThingsBoard widget or private dashboard in a flutter app

### ISSUE THREAD

**Issue by aljkor** [thingsboard/thingsboard#5273]
**Component**

 * Generic

**Description**

I have managed to show ThingsBoard dashboard in my flutter app by making it public and then using its public dashboard link inside a WebView widget. 

Firstly, I am wondering whether it is possible to access ThingsBoard dashboard that is private (by using JWT token maybe?). 

Secondly, is it possible to show only one widget inside a dashboard (in a similar way, URL of the widget?).

**Comment by ashvayka** [comment]
Hi @aljkor , See Flutter/Dart related projects:
https://github.com/thingsboard?q=&type=&language=dart&sort=
They are currently not yet released, but you can find a lot of useful code there, including authentication.
