### ISSUE TITLE
Rest API request to /api/device/credentials results in "400 Bad Request" [Bug] 

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5274]
I'm trying to change the ACCESS_TOKEN of a "virtual" device using the REST API.
I've copied the message body from the documentation shown in the swagger-ui.
The example message body is given as:
```
{
  "createdTime": 0,
  "credentialsId": "string",
  "credentialsType": "ACCESS_TOKEN",
  "credentialsValue": "string",
  "deviceId": {
    "id": "string"
  },
  "id": {
    "id": "string"
  }
}
```
My message-body looks as follows:
```
{
  "deviceId": {
    "id": "31d79790-1c65-11ec-bd62-390c2baef8bf"
  },	
  "createdTime": 0,
  "credentialsType": "ACCESS_TOKEN",
  "credentialsValue": "pQea9l7XMvZbINdqLulm"
}
```
So, as you can see I've omitted some of the optional key-value pairs such as "createdTime". 

**My Server Environment**
* own setup
  * local
  * PE 3.3.0
  * MS Windows 10

**My Client Environment**

* MS Win 10
* Chrome Version 93.0.4577.82 (doesn't really matter)
* Insomnia v2021.5.3

**To Reproduce**
1. Create a new device
2. Get the tenant-level Bearer Access token from ${host:port}/api/auth/login
3. Create the POST request above with Conent-Type application/json, Accept: application/json and  X-Authorization: Bearer ${BearerTokenHere}
4. submit the request
5. => 400 Bad Request

**Expected behavior**
Device Access Token is replaced by the given one.

**Screenshots**
not helpful in this case

**Additional context**

**Comment by JacksonBowe** [comment]
Hi @eeitnn try changing 
```
"deviceId": {
    "id": "string"
  }
```

to 
```
"deviceId": {
    "id": "31d79790-1c65-11ec-bd62-390c2baef8bf",
    "entityType": "DEVICE"
  }
```

Possibly don't use the "deviceId" field and just use this instead
```
"id": {
    "id": "31d79790-1c65-11ec-bd62-390c2baef8bf",
    "entityType": "DEVICE"
  }
```
^ Untested, just some thoughts based on my experience with using swagger-ui. It's often not 100% correct.

**Comment by eeitnn** [comment]
Hi @JacksonBowe ,

thanks a lot for your suggestions. 
Indeed I had to add the key-value pair "entityType":"DEVICE" to the "deviceId"- object.
However, now it seems like the API is not designed to change the credentials of an already existing device.
I'm receiving the following response:

```
{
  "status": 400,
  "message": "Credentials for this device are already specified!",
  "errorCode": 31,
  "timestamp": "2021-09-24T06:27:23.995+00:00",
  "subscriptionErrorCode": null,
  "subscriptionEntry": null,
  "subscriptionValue": null
}
```

Do you know of any workaround or is this a dead end here?

**Comment by JacksonBowe** [comment]
@eeitnn Hmmm, I could have sworn that I have changed the access token on a device before. Although that would have been with TB3.1.1PE. Maybe it's no longer possible.

Sorry I can't help more. Good luck though.

**Comment by eeitnn** [comment]
@JacksonBowe 
Thank you anyway. I've already helped a lot.

**Comment by LeoMorgan113** [comment]
Hi @eeitnn 

The correct request body is:

`{
"id":{
 "id":"ed54f880-1d2f-11ec-8a2a-9ff4ff0175e3"
},
"createdTime":1632485222408,
"deviceId":{
"entityType":"DEVICE",
"id":"ed53e710-1d2f-11ec-8a2a-9ff4ff0175e3"},
"credentialsType":"ACCESS_TOKEN",
"credentialsId":"Lb9UPyREtNwQmZsGFr2",
"credentialsValue":null
}`

You need to put your token in credentialsId, not credentialsValue

**Comment by ashvayka** [comment]
This API is actually designed **only** for updates. First, you need to execute getDeviceCredentialsByDeviceId to get the "id" and then use this API call to update the credentials with new credentialsType, credentialsId and credentialsValue. We are working on updating the Swagger API documentation [here](https://github.com/thingsboard/thingsboard/tree/feature/swagger)

**Comment by eeitnn** [comment]
@LeoMorgan113 : Thank you for the correct body 
@ashvayka : Updating the ACCESS_TOKEN is exactly what I want to do. Thank you for the hint towards getDeviceCredentialsByDeviceId. This was the id I was missing.
