### ISSUE TITLE
[Bug] 3.3.1PE is unusable, list of bugs inside

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5276]
This week I've tried to play around with 3.3.1PE but had zero success getting **any** functionality working consistently.

I'm currently going through the process of addressing these issues with my paid support, but I really want to get an idea if anyone else is encountering these issues.

For reference, everything mentioned below is happening right now in a fresh tenancy. I've reproduced all the issues while writing this.

**Rule Chains**:
- Sometimes when I press "Save Changes" the whole rule chain deletes itself
- This isn't strictly reproduceable, it just happens sometimes, so that's cool
![rule-chains-deleting](https://user-images.githubusercontent.com/26427343/134602067-e7d5be6c-87da-4077-be1a-8dae5205676d.gif)
- Similar issue when you try to load a rule chain (although this may just be visual)
![rule chains not loading](https://user-images.githubusercontent.com/26427343/134602089-19ee508d-93a1-4f70-90dd-148759b6cffd.gif)

**Device Profiles**:
- These straight up don't work. Every aspect fails
- Device profiles can be created by an Integration + Data Converter maybe 5% of the time.
Here's me trying desperately for it to function as documented. Notice **weather station** profile doesn't get created
![deviceProfiles not creating](https://user-images.githubusercontent.com/26427343/134604400-40c1609c-af06-49be-98e0-fc58fd2c750e.gif)
- When trying to create a Device Profile with an integration, the output from the Data Converter needs to contain 
"deviceType": _type_
- For a device coming through an integration to **use** a Device Profile, the output from the Data Converter needs to contain
"deviceProfile": _profile_
- Integrations cannot create a profile and then use it in the same output. You get the below error message:
```
"message":"ERROR: insert or update on table \"device\" violates foreign key constraint \"fk_device_profile\"\n  Detail: Key (device_profile_id)=(ecff1ea0-1b32-11ec-ba4a-4f628d77f391) is not present in table \"device_profile\".","suppressed":[],"localizedMessage":"ERROR: insert or update on table \"device\" violates foreign key constraint \"fk_device_profile\"\n  Detail: Key (device_profile_id)=(ecff1ea0-1b32-11ec-ba4a-4f628d77f391) is not present in table \"device_profile\"."},"suppressed":[],"localizedMessage":"could not execute statement; SQL [n/a]; constraint [fk_device_profile]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
```

**Data Converters**
- They're not saving changes sometimes, see below (using default converter but deleted a few fields to showcase)
![broken converters](https://user-images.githubusercontent.com/26427343/134601328-8a85ecf4-6d25-4b57-969c-71cf78a2278d.gif)
- If I go and set the result to be static it works though:
![converters-broken-2](https://user-images.githubusercontent.com/26427343/134601604-35a377d7-44d3-4846-a7d3-61ab51fb1234.gif)

So yeah, just some really cool stuff that isn't usable, at least for me. 

Some thoughts I've had about why/how this is happening. 
- The way that I've set up my database is causing read and writes to be extremely slow. So the UI is loading before response.
- I know there is a bug concerning Data Converter outputs. It is **required** that the output contains the desired deviceProfile otherwise the message won't be routed to the correct rule chain.

I'll keep updating this thread as I find more broken stuff, in addition to using my paid support. But yeah, anyone else getting these issues?

Cheers

**Comment by JacksonBowe** [comment]
New Bug: Integrations cannot create a device that previously existed but was deleted.

Process:
Integration creates device with name > dev01
User goes and deletes device dev01
Device posts to integration again
Integration **will not** recreate the device.

**Comment by JacksonBowe** [comment]
New Bug: Rule Chains not passing messages through to referenced chains

In this gif I'm getting debug logs from one node, but it doesn't get passed into the referenced rule chain. Debug is enabled on both nodes.
![rule chains broken](https://user-images.githubusercontent.com/26427343/134613385-bc70d897-a797-4823-89f7-38fbfc9ff2d5.gif)

**Comment by ashvayka** [comment]
Hi @JacksonBowe , we are analyzing and fixing the bugs you have reported as soon as we reproduce them. 
However, quick question, Is there any chance you are using PGPool or similar tools for the PostgreSQL cluster? 
Some reported bugs look very suspicious. Looks like you are writing to PostgreSQL writer and read from PostgreSQL replica that is out of sync with the writer.

**Comment by ashvayka** [comment]
Similar question. Are you using Cluster mode of ThingsBoard? If yes, what type of cache?

**Comment by JacksonBowe** [comment]
Hi @ashvayka , my deployment is based on Scenario C from the Thingsboard docs.

![image](https://user-images.githubusercontent.com/26427343/134825035-740460c1-6959-43d0-8785-45b9aa9e3ed9.png)

In my setup, I'm using 2x t3.medium instances with a Multi-AZ Postgres DB. Both instances are pointing back to the same DB. We're not using Redis.

Have you been able to reproduce the Integrations unable to create devices/deviceProfiles consistently?

Thanks for the response also!

Update:
Using your questions as a starting point we found that we had not enabled the "stickyness" option in our deployment group. So I think what was happening is that I was being randomly routed between instances with different caches. That would explain the rule chains "deleting" themselves. I've tried to reproduce the issue now and thankfully have been unsuccessful.

Is this a viable alternative to using Redis? I ask because we have only ~200 devices at the moment so we're trying to find a middle ground with out deployment complexity.

**Comment by JacksonBowe** [comment]
Rule Chain Odd Behaviour:

It seems that my Rule Chain is using a previous configuration. In the below gif, I've **disabled** debug mode, and completely disconnected the input link to the selected node. However, when I refresh, I'm still getting debug logs.
![rule-chain-not-updating](https://user-images.githubusercontent.com/26427343/134828711-1afe9a5d-e843-4b83-9d23-c075aee0215b.gif)

 The Database has updated to the correct value
![image](https://user-images.githubusercontent.com/26427343/134828733-d3c26deb-4ad4-4e79-ba89-c38e38c69d77.png)

Possible that this may be related to the issue of Integrations not using the updated version of a Converter?

Cheers

**Comment by smatvienko-tb** [comment]
@JacksonBowe, You are right, the issue is related to the cache. In cluster setup (many tb-nodes) you have to use distributed cache (Redis) or disable cache at all. 
The previous 3.2 version has zero value for some caches and you might be fine using the local cache for the rule chains.
Here is an example of what can you change in thingsboard.yml to disable local cache
![image](https://user-images.githubusercontent.com/79898499/134870518-9340ea3f-7324-4512-8218-01a3eb93fb7e.png)
The better solution is to spin up the Redis cache with the helm chart.
Also, it is mandatory to use a Zoopeeker (for discovery) and Kafka (for messaging) in cluster mode (many tb-nodes).

**Comment by ashvayka** [comment]
Hi @JacksonBowe ,

my personal recommendation in case of 200 devices - Use only 1 ThingsBoard instance and managed PostgreSQL (AWS RDS). If you like to have a failover of ThingsBoard, you may deploy it in k8s and allocate two nodes, so, K8S will re-start the instance on the second node in case of hardware issues on the first node. This will allow you to avoid using Cache. 

Using Kafka is highly recommended to survive peak loads as your number of devices will grow. Using Kafka also helps to avoid losing data that already arrived to ThingsBoard from devices, but was not processed yet. 

About PostgreSQL: Avoid writing and reading from multiple nodes. Always write and read from master. Make sure your failover works with custom PostgreSQL cluster solutions, or consider using AWS RDS.

About Redis and Zookeeper - it is a **must** in case you have multiple thingsboard instances in a cluster.

**Comment by ashvayka** [comment]
I have personally tested all the reported bugs related to "device profiles and integrations/converters" and also browsed the related code. I have not reproduced them and am quite sure that the only possible issue might be the inconsistent DB/Cache state due to your specific setup.
