### ISSUE TITLE
[Feature Request] Make it also possible to run the thingsboard/postgres image with Podman instead of Docker

### ISSUE THREAD

**Issue by rduivenvoorde** [thingsboard/thingsboard#5284]
I'm in a RedHat environment in which running containers using Podman is preferred over Docker

So I started to run the image successfully(!) using *Docker* using the instructions of:
https://hub.docker.com/r/thingsboard/tb-postgres

That is: creating a logs and data dir and making 799 owner of it...

But doing the same thing using Podman fails with the following message:

```
mkdir: cannot create directory ‘/data/db’: Permission denied
The files belonging to this database system will be owned by user "thingsboard".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/db ... initdb: error: could not create directory "/data/db": Permission denied
pg_ctl: database system initialization failed
```

Within the container the thingsboard user does have id 799:

```
$ cat /etc/passwd
...
thingsboard:x:799:799:Thingsboard application,,,:/home/thingsboard:/usr/sbin/nologin
Debian-exim:x:101:103::/var/spool/exim4:/usr/sbin/nologin
postgres:x:102:104:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
```

BUT: the data dir is (within the container) NOT owned by that user id:

```
$ ls -lna /data
total 8
drwxr-xr-x  2 65534 65534 4096 Sep 27 08:19 .
dr-xr-xr-x 22     0     0 4096 Sep 27 08:21 ..

```

Anybody a clue how to fix this, and with that make Podman an option to run the image

**Comment by trypzz** [comment]
Hi,

Provide the commands, which you execute with the podman.
NOTE: thingsboard are not support thirt-party services and podman - that are only your choice.

**Comment by rduivenvoorde** [comment]
Podman is (should be) a 'drop-in'-replacement of Docker, so you (should) are able to use all the docker commands:

```
LOCAL_TB_DATA_DIR=/tmp/.tb-data
LOCAL_TB_LOG_DIR=/tmp/.tb-logs
mkdir -p $LOCAL_TB_DATA_DIR && sudo chown -R 799:799 $LOCAL_TB_DATA_DIR
mkdir -p $LOCAL_TB_LOG_DIR && sudo chown -R 799:799 $LOCAL_TB_LOG_DIR

podman run -it -p 9090:9090 -p 1883:1883 -p 7070:7070 -p 5683-5688:5683-5688/udp -v $LOCAL_TB_DATA_DIR:/data -v $LOCAL_TB_LOG_DIR:/var/log/thingsboard --name tb docker.io/thingsboard/tb-postgres:3.3.1
```

(if I understand correctly, Podman should be a little safer then docker, because not running as root, and maybe(?) a stricter distinction between host and container)

**Comment by shenyan77** [comment]
Just a tmp workaround to run image by podmain. 

1.  Create a user thingsboard by providing uid/gid = 799/799
sudo groupadd -g 799 thingsboard
sudo useradd thingsboard -u 799 -g 799 -m -s /bin/bash

2. sudo su - thingsboard
    mkdir -p ~/.mytb-data
    mkdir -p ~/.mytb-logs

3.   podman run -it -p 9090:9090 -p 7070:7070 -p 1883:1883 -p 5683-5688:5683-5688/udp -v /home/thingsboard/.mytb-data:/data -v /home/thingsboard/.mytb-logs:/var/log/thingsboard --name mytb --restart always thingsboard/tb-postgres

this is working for me
