### ISSUE TITLE
Critical and High vulnerabilities in components used by Thingsboard 3.3.1 found by OWASP dependency-check

### ISSUE THREAD

**Issue by joe-pulse** [thingsboard/thingsboard#5286]
OWASP dependency-check plugin finds the following components used by Thingsboard tags/v3.3.1 have Critical or High CVEs filed against them:

Dependency | Vulnerability IDs | Package | Highest Severity↓ | CVE Count | Confidence | Evidence Count
-- | -- | -- | -- | -- | -- | --
cassandra-driver-core-3.11.0.jar | cpe:2.3:a:apache:cassandra:3.11.0:*:*:*:*:*:*:* | pkg:maven/com.datastax.cassandra/cassandra-driver-core@3.11.0 | CRITICAL | 3 | High | 27
nimbus-jose-jwt-9.5.jar (shaded: net.minidev:json-smart:1.3.1) | cpe:2.3:a:json-smart_project:json-smart-v1:1.3.1:*:*:*:*:*:*:*cpe:2.3:a:json_smart_project:json_smart:1.3.1:*:*:*:*:*:*:* | pkg:maven/net.minidev/json-smart@1.3.1 | CRITICAL | 1 | High | 9
json-smart-2.3.jar | cpe:2.3:a:json-smart_project:json-smart-v2:2.3:*:*:*:*:*:*:*cpe:2.3:a:json_smart_project:json_smart:2.3:*:*:*:*:*:*:* | pkg:maven/net.minidev/json-smart@2.3 | CRITICAL | 1 | Highest | 34
accessors-smart-1.2.jar | cpe:2.3:a:json-smart_project:json-smart-v1:1.2:*:*:*:*:*:*:*cpe:2.3:a:json_smart_project:json_smart:1.2:*:*:*:*:*:*:* | pkg:maven/net.minidev/accessors-smart@1.2 | CRITICAL | 1 | Low | 30
protobuf-dynamic-1.0.3TB.jar | cpe:2.3:a:thingsboard:thingsboard:1.0.3tb:*:*:*:*:*:*:* | pkg:maven/org.thingsboard/protobuf-dynamic@1.0.3TB | HIGH | 1 | Highest | 16
libthrift-0.9.2.jar | cpe:2.3:a:apache:thrift:0.9.2:*:*:*:*:*:*:* | pkg:maven/org.apache.thrift/libthrift@0.9.2 | HIGH | 5 | Highest | 24
rest-5.0.2.jar | cpe:2.3:a:elastic:elasticsearch:5.0.2:*:*:*:*:*:*:*cpe:2.3:a:elasticsearch:elasticsearch:5.0.2:*:*:*:*:*:*:* | pkg:maven/org.elasticsearch.client/rest@5.0.2 | HIGH | 9 | Highest | 36
spring-orm-5.2.14.RELEASE.jar | cpe:2.3:a:pivotal_software:spring_framework:5.2.14:release:*:*:*:*:*:*cpe:2.3:a:springsource:spring_framework:5.2.14:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.2.14:release:*:*:*:*:*:*cpe:2.3:a:vmware:springsource_spring_framework:5.2.14:release:*:*:*:*:*:* | pkg:maven/org.springframework/spring-orm@5.2.14.RELEASE | HIGH | 1 | Highest | 28
spring-messaging-5.2.12.RELEASE.jar | cpe:2.3:a:pivotal_software:spring_framework:5.2.12:release:*:*:*:*:*:*cpe:2.3:a:springsource:spring_framework:5.2.12:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.2.12:release:*:*:*:*:*:*cpe:2.3:a:vmware:springsource_spring_framework:5.2.12:release:*:*:*:*:*:* | pkg:maven/org.springframework/spring-messaging@5.2.12.RELEASE | HIGH | 1 | Highest | 28
spring-integration-core-5.2.11.RELEASE.jar | cpe:2.3:a:vmware:spring_framework:5.2.11:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_integration:5.2.11:release:*:*:*:*:*:* | pkg:maven/org.springframework.integration/spring-integration-core@5.2.11.RELEASE | HIGH | 1 | Highest | 33
spring-aop-5.3.3.jar | cpe:2.3:a:pivotal_software:spring_framework:5.3.3:*:*:*:*:*:*:*cpe:2.3:a:springsource:spring_framework:5.3.3:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.3.3:*:*:*:*:*:*:*cpe:2.3:a:vmware:springsource_spring_framework:5.3.3:*:*:*:*:*:*:* | pkg:maven/org.springframework/spring-aop@5.3.3 | HIGH | 1 | Highest | 29
spring-security-web-5.4.4.jar | cpe:2.3:a:pivotal_software:spring_security:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_security:5.4.4:*:*:*:*:*:*:* | pkg:maven/org.springframework.security/spring-security-web@5.4.4 | HIGH | 1 | Highest | 30
spring-security-web-5.3.9.RELEASE.jar | cpe:2.3:a:pivotal_software:spring_security:5.3.9:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_security:5.3.9:release:*:*:*:*:*:* | pkg:maven/org.springframework.security/spring-security-web@5.3.9.RELEASE | HIGH | 1 | Highest | 29
spring-security-oauth2-core-5.4.4.jar | cpe:2.3:a:pivotal:spring_security_oauth:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:pivotal_software:spring_security:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:pivotal_software:spring_security_oauth:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_security:5.4.4:*:*:*:*:*:*:* | pkg:maven/org.springframework.security/spring-security-oauth2-core@5.4.4 | HIGH | 1 | Highest | 32
spring-security-core-5.4.4.jar | cpe:2.3:a:pivotal_software:spring_security:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.4.4:*:*:*:*:*:*:*cpe:2.3:a:vmware:spring_security:5.4.4:*:*:*:*:*:*:* | pkg:maven/org.springframework.security/spring-security-core@5.4.4 | HIGH | 1 | Highest | 30
spring-security-config-5.3.9.RELEASE.jar | cpe:2.3:a:pivotal_software:spring_security:5.3.9:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_framework:5.3.9:release:*:*:*:*:*:*cpe:2.3:a:vmware:spring_security:5.3.9:release:*:*:*:*:*:* | pkg:maven/org.springframework.security/spring-security-config@5.3.9.RELEASE | HIGH | 1 | Highest | 29
scandium-2.6.1.jar | cpe:2.3:a:eclipse:californium:2.6.1:*:*:*:*:*:*:* | pkg:maven/org.eclipse.californium/scandium@2.6.1 | HIGH | 1 | Highest | 31
leshan-server-cf-2.0.0-M3.jar | cpe:2.3:a:eclipse:californium:2.0.0:m3:*:*:*:*:*:* | pkg:maven/org.eclipse.leshan/leshan-server-cf@2.0.0-M3 | HIGH | 1 | Low | 29
element-connector-2.6.1.jar | cpe:2.3:a:eclipse:californium:2.6.1:*:*:*:*:*:*:* | pkg:maven/org.eclipse.californium/element-connector@2.6.1 | HIGH | 1 | Highest | 29
californium-core-2.6.1.jar | cpe:2.3:a:eclipse:californium:2.6.1:*:*:*:*:*:*:* | pkg:maven/org.eclipse.californium/californium-core@2.6.1 | HIGH | 1 | Highest | 31
hibernate-validator-4.3.0.Final.jar | cpe:2.3:a:hibernate:hibernate_orm:4.3.0:*:*:*:*:*:*:*cpe:2.3:a:redhat:hibernate_validator:4.3.0:*:*:*:*:*:*:* | pkg:maven/org.hibernate/hibernate-validator@4.3.0.Final | HIGH | 4 | Highest | 34

**Comment by joe-pulse** [comment]
[v3.3.1-thingsboard-dependency-check-report.zip](https://github.com/thingsboard/thingsboard/files/7235832/v3.3.1-thingsboard-dependency-check-report.zip)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
