### ISSUE TITLE
[Question] Are there different functions in CE between different installation? (Ubuntu server/windows+docker)

### ISSUE THREAD

**Issue by hangusto** [thingsboard/thingsboard#5287]
**Component**

 * Installation

**Description**

I try to use different ways to install thingsboard from [Ubuntu server (20.04)](https://thingsboard.io/docs/user-guide/install/ubuntu/) and [Docker(windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/).

After installation, I found that the function menus are different:

**Ubuntu server** installation
![image](https://user-images.githubusercontent.com/45854355/134898211-65eb84d9-3255-490b-8876-87073d16baaa.png)

**Docker(Windows)** installation
![image](https://user-images.githubusercontent.com/45854355/134898229-bec856c7-c5d3-4401-9880-5a5225a8b51b.png)

It obvious that more functions in [Docker(windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/) installation:

- Device profiles
- OTA updates
- Edge instances
- Edge management
- Api Usage
- System Settings

Moreover, when I checked the postgresql service in [Docker(windows)](https://thingsboard.io/docs/user-guide/install/docker-windows/) is not working.

But in [Ubuntu server](https://thingsboard.io/docs/user-guide/install/ubuntu/) installation, thingsboard service is not working without postgresql service.

It makes me confused.

**Ubuntu server** installation
![image](https://user-images.githubusercontent.com/45854355/134898197-fbdd3c62-d3c4-4086-b96f-b0c9d29ecbf0.png)

**Docker(Windows)** installation
![image](https://user-images.githubusercontent.com/45854355/134898205-ba6ebc88-ce23-49fc-9f88-1ba7e0b9ac8b.png)

### I want to understand what causes differences.

Thx.

**Environment**

 * OS:  Windows Docker (WSL2 backend)
 * Docker image: [Ubuntu:20.04](https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated)/ [tb-postgres:3.3.1](https://hub.docker.com/r/thingsboard/tb-postgres/tags?page=1&ordering=last_updated)
 * Java version
   Ubuntu server installation: **openjdk 11.0.11 2021-04-20**
   Docker(Windows) installation: **openjdk 11.0.9.1 2020-11-04**
 * ThingsBoard: 3.3.1
 * Browser: Chrome/Edge

**Comment by Backdraft007** [comment]
In the screenshot I see that version 3.1.1 ist installed on docker. Can you try an upgrade?

**Comment by ashvayka** [comment]
> In the screenshot I see that version 3.1.1 ist installed on docker. Can you try an upgrade?

Probably the @hangusto used image 3.1.1 instead of 3.3.1 due to typo and this causes the difference. The Docker image is launching PostgreSQL inside as a separate process. The image definitely contains PostgreSQL and it is mandatory for ThingsBoard 3.x

**Comment by hangusto** [comment]
@ashvayka I got it, thank you for the clear explanation. 
But I still have question about the user's permission issue in **Docker image: tb-postgres**. Could I elevate the permission to root for installing other tools, i.e. iputils-ping, wget or vim? Or this is not allowed? I want to implement Two-Way SSL connection with X.509 certificate and to build some program in the container.

**Comment by ashvayka** [comment]
@hangusto , non-root docker images is a feature, not a bug. Many Enterprises do not allow to launch of docker images with root permission in their K8S clusters. If you need some tools, you may [extend the docker image](https://stackoverflow.com/questions/22905803/how-to-extend-an-existing-docker-image) and use new image instead of base one. If you have any specific questions how to do this - please update this issue.
