### ISSUE TITLE
[Question] Converters creating asset - devices- and relations between them

### ISSUE THREAD

**Issue by yayaLy** [thingsboard/thingsboard#5288]
**Component**

 * Rule Engine or Data converters

**Description**
I have an MQTT broker sending data with a specic format
{
     "equ_name":"equ name",
      "latitude":"lat value",
       "longitude":"long value",
         "device":{ 
                        "deviceName":"test",
                        "time":1632745871,
                         "telemetry":{
                                 "Vibration x":0.09,
                                       "Vibration y":0.15,
                         }
           }
}

  The equ_name is my equipment and an equipment can have multiple devices (sensors)
I want when my converter receive the data to create an asset (if it does not exist) and the devices. 
But most importantly to create the relation between the asset and its devices.

Can it be done, directly witth the converter or should I do it with something else

Thank you for your answer

**Environment**
 * ThingsBoard: PE v3.3.1

**Comment by JacksonBowe** [comment]
Hi @yayaLy 

The way I would approach this would be to have the converter set an attribute on the device 
```patentEntity: {"type":"ASSET", "name"}```

Then inside your rule chains I would just have something that looked for messages containing key **parentEntity** and then use the **create relation** node. There's some other small steps, but this is how I've done it.

**Comment by yayaLy** [comment]
Hi @JacksonBowe 
Thank you very mutch. this does help a lot. And it resolved my problem
