### ISSUE TITLE
Is that prosible to add a simple shopping cart for Thingsboard?

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5289]
sometimes people may want to sell some hardware products on their IoT platform e.g. Raspberry Pi or gateway hardware etc. 
Is that prosible to add a simple shopping cart for Thingsboard?

**Comment by ashaforost** [comment]
Dear ThingsBoard Customer,

Thank you for taking the time to request a product enhancement. Your input is welcome, and we appreciate your feedback to improve the ThingsBoard experience. Please answer the following questions

Sincerely,
The ThingsBoard Team

Your Company Name:
Your Name and Title:
Description (please include as much detail as possible, such as the ThingsBoard URL to the page you are referring to, the name of the reporting view, name of column header, etc.):
Reason for Enhancement/Business Case (please provide a specific reason):
Current Workarounds (if any):

**Comment by jasonlee9900** [comment]
hello, ashaforost:
Are you contributor or employee of TB company? I just give a proposal, anythings related to a certain company? some of info you need are private not suitable publish in this forum, if you contact me privately then I can provide.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
