### ISSUE TITLE
[Bug] Can't provision device profile name from thingsboard-gateway 

### ISSUE THREAD

**Issue by pnavazzotti** [thingsboard/thingsboard#5290]
**Describe the bug**
I cannot configure "DeviceTypeExpression" field in mqtt.json. I tried to hardcore these value as string instead of evaluating the field with JsonPath, and this is where the problem shows up.
Of course, I have created beforehand a device profile called Rondas, with the Transport configuration set to MQTT and listening in the topic dig_ronda. I've also tried to set the Device Provisioning tab to "Allow to create new devices" and it doesn't work.
   ```
"mapping": [
     {
         "topicFilter": "dig_ronda",
         "converter": {
             "type": "json",
             "deviceNameJsonExpression": "rondas",
             "deviceTypeJsonExpression": "Rondas",
             "timeout": 1200,
             "attributes":[
             ],
             "timeseries":[
               {
                  "type":"float",
                  "key":"cal_flotado",
                  "value":"${$.values.cal_flotado}"
               },
              
```
I am using tb-gateway 2.2

**Comment by ashvayka** [comment]
@zbeacon , please provide comments.

**Comment by zbeacon** [comment]
Hi @pnavazzotti ,

Thank you for your interest in ThingsBoard IoT gateway. The issue, you described is a known one from old versions, please try to use the latest version of the gateway and let us know about the results.  
Also we have to say that the gateway cannot change device profile for device after it was created, so the very first message, converted from device should contain correct deviceType(Device profile type).  

Device provisioning feature is not related to the gateway, you can read more about the provisioning feature [here](https://thingsboard.io/docs/user-guide/device-provisioning/).

**Comment by pnavazzotti** [comment]
Hi @zbeacon!

Thanks for your answer. 
I performed the Thingsboard-gateway upgrade to the latest existing version (**latest = 2.6**), as the 2.7 version mentioned here [](https://github.com/thingsboard/thingsboard-gateway/releases) is not found in Docker hub. This did not generate any change in the issue I am going through. 

The loading of the device `"rondas"` is done correctly, but the profile Thingsboard sets for it is "default" and not `"Rondas"`. The tests were performed by removing any kind of profile, previously, related to `"Rondas"`.
 
I am currently using Thingsboard version 3.2 and Thingsboard-gateway 2.6.

**Comment by Ultrazombie** [comment]
Hello @pnavazzotti 
Since you are facing an issue with the IoT Gateway, you might consider reaching out to the GitHub community regarding thingsboard gateway issues. They can provide assistance or insights that could prove valuable in addressing your specific needs.
GitHub thingsboard gateway issues - https://github.com/thingsboard/thingsboard-gateway/issues

Feel free to re-open the ticket on the gateway repository if you still have this problem.
