### ISSUE TITLE
[Question] Multi-state dashboard setting is not complete

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5297]
For ThingsBoard PE 3.3.1, if dashboard has multile states, the setting dialog is not complete, and the columns, background, etc cannot be set. What is the reason for this?
![2021-09-29 13_32_10-Window](https://user-images.githubusercontent.com/17080208/135208940-dcbb92bb-4019-42ce-9b4c-23a69c611f9b.png)

**Comment by ChantsovaEkaterina** [comment]
Hello, @sunyong-mwi 
If the dashboard has multiple states, layout settings are individual for each state. You can find them in a separate dialog by clicking the "Manage layouts" button next to "Manage dashboard states" on the left toolbar corner.
![image](https://user-images.githubusercontent.com/17936317/135229558-e45c19c5-e887-4faa-bd96-0b3c59bff2e4.png)

**Comment by sunyong-mwi** [comment]
Thank you for the explanation.
