### ISSUE TITLE
[Question] Dashboard navigation with list of entities

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5298]
Let's say there are two states in dashboard. 
- In default state, there are two cards. The first card displays the count of devices with attribute X value as A, and the second card displays the count of devices with attribute X value as B. 
- In second state, there is an entity list. 

I want to add action icons in both cards to navigate to the second state of entity list. 
- When action icon is clicked on first card, the dashboard navigates to second state to show all the devices with attribute X value as A
- When action icon is clicked on second card, the dashboard navigates to second state to show all the devices with attribute X value as B 

How should I do the above?

**Comment by JacksonBowe** [comment]
Hi @sunyong-mwi , what you may want to use here are filters.
To navigate to the dashboard state use a customer action so that you can set an attribute on the user.
```
let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext
    .servicesMap.get('attributeService'));

function updateDashboardState(stateId, label) {
    // example code, you will need to change
    var params = {
        entityId: entityId,
        entityName: entityName,
        entityLabel: label,
        prevState: widgetContext.stateController.getStateId()
    };
    widgetContext.stateController.openState(stateId,
        params, false);
}

function updateUserAttr(target, value) {
    /*** update the value of your filter attribute ***/
    // This is an untested example
    attributeService.saveEntityAttributes({
        entityId: {"entityType": "USER", "id": widgetContext.currentUser.userId},
        attributeScope: "SERVER_SCOPE",
        attributes: [{key: 'keyYouWantToUse', value: "value"}]
    })
    
} 

// updateUserAttr
// updateDashboardState
```

Then make a dynamic filter something like this
![image](https://user-images.githubusercontent.com/26427343/135357163-16cce58b-5454-4223-87b4-6002f92f3d81.png)

What you want is possible with the above method, I've got it set up in my solution. Good luck

**Comment by sunyong-mwi** [comment]
The saveEntityAttributes() call does not work. I tried the following syntax based on some other examples, also not working.

    attributeService.saveEntityAttributes(
        widgetContext.currentUser.userId, // entityId
        'SERVER_SCOPE',                   // attributeScope
        [{key: key, value: value}]        // attributes
    )

**Comment by sunyong-mwi** [comment]
I found the issue. The saveEntityAttributes() call syntax should be as follows:

    attributeService.saveEntityAttributes(
        {'entityType': 'USER', 'id': widgetContext.currentUser.userId},
        'SERVER_SCOPE',
        [{key: key, value: value}])

I managed to implement the feature I want. Thanks for the help.

**Comment by irdet2** [comment]
Hi! I am trying to achieve a similar thing but I am not able to use the "saveEntityAttributes()" either. @sunyong-mwi which version this worked for you? I am on Community Edition v.3.3.2. Do you think that something has changed in the releases between yours and mine? Could you please post your working example or give any other guidance? 
Thanks in advance!

**Comment by sunyong-mwi** [comment]
@irdet2 hi, my version is also 3.3.2

**Comment by irdet2** [comment]
@sunyong-mwi Great! Glad that we are on the same version. 
Based on your comments I think I was able to create the custom action but I am not sure how to test it. Any hints on this?

Trying to follow @JacksonBowe 's filter solution but most probably I am doing something wrong and is not working. 

So far I have set the following as a "Custom Action" on "Marker Click":

`
let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext
    .servicesMap.get('attributeService'));

function updateDashboardState(stateId, label) {
    var params = {
        entityId: entityId,
        entityName: entityName,
        entityLabel: label,
        prevState: widgetContext.stateController
            .getStateId()
    };
    widgetContext.stateController.openState(stateId,
        params, false);
}

function updateUserAttr(target, value) {
    attributeService.saveEntityAttributes({
            'entityType': 'USER',
            'id': widgetContext.currentUser.userId
        },
        'SERVER_SCOPE',
        [{
            key: "whateverkey",
            value: "whatevervalue"
        }]
    ).subscribe(
        //success and fail scenarios - this is the test code so i just log into the console
        function success() {
            console.log('success');
        },
        function fail() {
            console.log('fail');
        }
    );
}

updateUserAttr();
updateDashboardState();
`

And I get to see the "success" message on console log. 
But after that I am little puzzled on what to do and how to set the filter.

Any ideas?

Thank you!

**Comment by JacksonBowe** [comment]
@irdet2 you are basically there. Change the key to `deviceTypeFilter` and set the value to one of your device types. Then on your dashboard you set a filter and say 'show all entities whose entityType is equal to users server attribute `deviceTypeFilter`'

Make sure to apply the filter to the widget.

Also, I dont know if community edition has access to filters as I've only used PE.

**Comment by irdet2** [comment]
@JacksonBowe following your suggestions I have changed the "Custom Action" to the following :


```
let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext
    .servicesMap.get('attributeService'));

function updateDashboardState(stateId, label) {
    var params = {
        entityId: entityId,
        entityName: entityName,
        entityLabel: label,
        prevState: widgetContext.stateController
            .getStateId()
    };
    widgetContext.stateController.openState(stateId,
        params, false);
}

function updateUserAttr(target, value) {
    attributeService.saveEntityAttributes({
            'entityType': 'USER',
            'id': widgetContext.currentUser.userId
        },
        'SERVER_SCOPE',
        [{
            key: "deviceTypeFilter",
            value: "default"
        }]
    ).subscribe(
        //success and fail scenarios - this is the test code so i just log into the console
        function success() {
            console.log('success');
        },
        function fail() {
            console.log('fail');
        }
    );
}

updateUserAttr();
updateDashboardState();
```

where the ```value: "default"``` is the device's profile name. Is that OK? I am doing this on an asset though related to a device with that profile. Do you think that this is an issue?

As for the filter the Community Edition also provides such a functionality so taken the screen shot you have provided before and putting my details I have set the following :

![TB_Filter](https://user-images.githubusercontent.com/6882765/149160359-31cf3705-e5b8-4479-ad62-a576a9f29731.JPG)

By the way what should I put at the "xxx" part?? What I really have is part of the users email....Is that correct?

Then I am using this filter on an entities table and expecting when I click on the mark to see the table entries changing.

**Comment by JacksonBowe** [comment]
Try these values
* Key type = Entity Field
* key name type

Filter 
* starts with
* ignore case=true
* Current user
* Source attribute = deviceTypeFilter

In long form this is what the filter is doing.

Find me all entities containing an **entity_field** named **key_name** where the value **starts with** **CurrentUser['sourceattribute']**

So in this instance:
Filter for all entities where entityType == 'default'
