### ISSUE TITLE
some problem with thingsboard extensions

### ISSUE THREAD

**Issue by cc19931002** [thingsboard/thingsboard#530]
what will happen if I create a kafka plugin without adding corresponding dependency to application/pom.xml

**Comment by cc19931002** [comment]
and I found the rows did't increse in table component_descriptor  in cassandra ,So I think only add dependency to application/pom.xml is not enough，am i right?

**Comment by cc19931002** [comment]
rows in table plugin in cassandra did't increase too

**Comment by cc19931002** [comment]
throws a ClassNotFoundException?

**Comment by mp-loki** [comment]
You'll get an error in gui and the plugin obviously will not work. You don't need to change pom.xml if you are running ThingsBoard as a service.
