### ISSUE TITLE
[Question] How to create device offline monitoring in thingsboard (with IoT gateway)?

### ISSUE THREAD

**Issue by hangusto** [thingsboard/thingsboard#5300]
**Component**

 * Generic

**Description**

Purpose:  to create device offline monitoring in thingsboard (with IoT gateway).

I try to monitor the **device's active status** and use [IoT gateway](https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/) + Kepware simulator to push telemetry. 

In my thingsboard.yml:
`  defaultInactivityTimeoutInSec: "${DEFAULT_INACTIVITY_TIMEOUT:10}"`
`  defaultStateCheckIntervalInSec: "${DEFAULT_STATE_CHECK_INTERVAL:10}"`

`  inactivity_timeout: "${TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT:300000}"`
`  report_timeout: "${TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT:3000}"`

There are some questions here:

Q1: What is the relationship/different functions between **transport.sessions.inactivity_timeout** and **state.defaultInactivityTimeoutInSec**?

Q2: When I stopped the Kepware server, the simulator also stopped pushing telemetry. But, the attribute **active** keeps "true" and **lastActivityTime** keeps updating till I stopped IoT gateway and the active status did become "false".

I have read [Device Connectivity Status](https://thingsboard.io/docs/user-guide/device-connectivity-status/) and known the "activity event" and "inactivity event" meaning and double-checked the latest telemetry which not updated after stopping Kepware server. 

I think that the connectivity is still exist between thingsboard and IoT gateway which causes the active status won't be updated.
It makes me confused.

In other words, is it possible to monitor the active status for the individual device with IoT gateway? How to do?

![image](https://user-images.githubusercontent.com/45854355/135250013-560fa0ef-0796-457b-943e-099fb63d5578.png)

Q3: I also try the tutorial [Create Alarm when the Device is offline](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/).

Following all the steps of them, I found that it won't clear alarm automatically and it **need to clear manually** to restart alarm monitoring.

I'm not sure if it is caused by the same reason as the above problem

Here is my rule chain and node setting:
![image](https://user-images.githubusercontent.com/45854355/135316707-e65d2f4a-f302-4181-900e-e6b4902bff16.png)
![image](https://user-images.githubusercontent.com/45854355/135316396-c17554e1-5ea2-4ad7-9508-80bbf0906ee0.png)
![image](https://user-images.githubusercontent.com/45854355/135316477-da4a409f-406f-41a0-bff8-b1a824485f1d.png)

**Environment**

 * OS: Windows Docker(WSL2 backend)
 * ThingsBoard: tb-postgres:3.3.1 & tb-gateway:latest
 * Browser: Chrome/Edge

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
