### ISSUE TITLE
[Bug] Entities Table Row Style Function

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5302]
The Row style function for the Entities Table widget has some issues when using cell actions.

If setting to a solid colour it puts a thin line under the each row
![image](https://user-images.githubusercontent.com/26427343/135359594-5455e4ea-ce62-49d7-bd9a-a1095a83c526.png)

If using a gradient (which I want to do) it does this
![image](https://user-images.githubusercontent.com/26427343/135359668-aea5be7a-2b91-45bd-8277-058cf8f4bfec.png)

I'm guessing because the widget splits into two columns, Data & Actions, then this style just applies to both.

**Comment by JacksonBowe** [comment]
Very clunky, and expensive, workaround for my particular use-case.
```
var result = {}
result["border-radius"] = "10px";
result.background = "linear-gradient(to right, rgba(255, 51, 0, 0.5) 0%, rgba(255, 51, 0, 0) 80%)";

// Find all action cells and make them transparent
cells = $("mat-cell.mat-cell.cdk-cell.cdk-column-actions")
for (var i=0; i < cells.length; i++) {
    cells[i].style.background = "rgba(0,0,0,0)";
}

return result
```
![image](https://user-images.githubusercontent.com/26427343/135361713-907d7fe1-e893-46ae-a785-6752a0362f24.png)

**Comment by JacksonBowe** [comment]
If using PE edition you can change the global css styling in White Labelling section with the following code
```
.ts-table-1733368106 .mat-table .mat-row .mat-cell.mat-table-sticky, .ts-table-1733368106 .mat-table .mat-header-cell.mat-table-sticky{
    background: transparent;
}
.ts-table-1733368106 .mat-table .mat-row:hover:not(.tb-current-entity) .mat-cell.mat-table-sticky {
    background-color: transparent;
}
```

**Comment by ashvayka** [comment]
The workaround is ok, but we need to fix this.

**Comment by SuminDenis** [comment]
Hi @JacksonBowe,

A thin line under the each row - fixed 
Gradient not applying to the action column - its a design choice with won’t be reconsidered, as our developers explained.
