### ISSUE TITLE
[Question] Regarding deviceProfile alarms scalability

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5303]
I'm trying to set up some default deviceProfile alarms using processes as described in [the docs](https://thingsboard.io/docs/pe/user-guide/device-profiles/#alarm-rules). 

I just have a question regarding how to sperate different device profiles that share the same key names.

For example if I have a water temperature sensor (profile: waterSensor) and an ambient air temperature sensor (profile: airSensor). Both devices record temperature as telemetry, however the range of values is unique to both.

Now, following suggestions in the docs I could set up tenant level server-attributes like waterSensorHighTempThreshold and airSensorHightempThreshold, but I think it's easy to see how this approach isn't scalable. 

Something that I think might be worth exploring would be storing all alarmThresholds in an JSON formatted attribute (or maybe some new system?).
Example with the two afore mentioned device profiles, waterSensor, airSensor:
```
alarmThresholds: {
    "waterSensor": {
          "highTemperatureThreshold": "value1",
          "key2": "value2"
    },
    "airSensor": {
          "highTemperatureThreshold": "value3",
          "etc...":""
    },
    "deviceProfile3": {},
}
```

With this sort of approach, each deviceProfile could use the same key (eg highTemperatureThreshold) but have default values unique to the value range that is practical for their application.

Is there some way that I can achieve this result using the current deviceProfile alarms?

Cheers,

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
