### ISSUE TITLE
[Question] Is it not allowed upload device telemetry via Thingsboard's MQTT in rule engine?

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#5308]
Rule Engine

Is it not allowed upload device telemetry via Thingsboard's MQTT in rule engine? I got "Channel is closed" exception when sending data to MQTT (localhost) as device telemetry in Rule Engine. 

Instead of uploading device telemetry via MQTT in rule engine, is it possible to change the entity id and then save the timeseries as another device? 

OS:  Ubuntu 20.04
ThingsBoard: 3.3.1
Browser: Firefox, Chrome and Edge

**Comment by FacelookHK** [comment]
Further testing it, looks like the "Channel is closed!" exception came from the rule engine sending telemetry to a "Is Gateway" device.

**Comment by epalchenko** [comment]
Hello,
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket with detailed steps to reproduce if this problem still exists.
