### ISSUE TITLE
[Question] getCustomerDevices return empty array

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5309]
I'm trying to enhance an entity-table widget (the table lists all customers) by adding a custom action (with html template), where I need the list of devices for the currently selected customer.

The relevant part of my attempts looks as follows:
```
        let pl = new widgetContext.pageLink(10,0,null,null);
        
        deviceService.getCustomerDevices(entityId.id,pl,'MyDeviceProfile').subscribe(function(data){
           console.log(entityId.id);
           console.log(data);
        });
```

However, all this returns to the console is:

> 03a54e20-fe61-11eb-8c0e-ede4043c3db2
> 
> {data: Array(0), totalPages: 0, totalElements: 0, hasNext: false}
> data: []
> hasNext: false
> totalElements: 0
> totalPages: 0
> [[Prototype]]: Object

I've double checked the ID of the customer and made sure he owns a couple of device with the profile "MyDeviceProfile".
I expected to receive an array of these devices.

Where is my mistake?

**Environment**
 * OS:  Win 10
 * ThingsBoard: PE 3.3.0
 * Browser: Chrom

**Comment by Mayanks2101** [comment]
Can you Please Share the solution as I am trying this but it is showing an error Like, 
Error : widgetContext.pageLink is not a constructor
