### ISSUE TITLE
[Question] input widget field lable color

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5312]
Where can I change the input widget field lable color and the action button color?

![2021-10-01 20_39_25-Window](https://user-images.githubusercontent.com/17080208/135621065-2d2e08c2-79b0-4d16-ace6-4295971851c5.png)

**Comment by zhgchen** [comment]
I run into this issue too. I try to solve it by searching, but failed. By debugging with chrome I found that we might change Widget CSS: 
input {
    /*width: 200px;*/
    /*padding-bottom: 44px;*/
    /*font-size: 14px;*/
    /*line-height: 1.42857143;*/
    color: #fff;
    /*color: #555;*/
    /*background-color: #fff;*/
    background-image: none;
    /*border-bottom: 1px dotted #ccc;*/
    border-spacing: 12px;
    /*width: 90%;*/
    height: 2rem;
    font-size: 1.0625rem;
    padding-left: 0.875rem;
    line-height: 147.6%;
    /*padding-top: 0.825rem;*/
    /*padding-bottom: 0.5rem;*/
    /*border-radius: 4px;*/
    /*outline: none;*/
    /*outline: 1px solid #ccc;*/
    overflow: hidden;
    white-space: nowrap;
    display: block;
    -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .5s, box-shadow ease-in-out .15s;
}

/*input:empty::before {*/
    /*input:before {*/
/*    color: yellow;*/
/*    content: attr(placeholder);*/
/*}*/

/*input:focus {*/
    /*outline: none;*/
    /*outline: 4px solid #51c9ff;*/
    /*background-color: #fff;*/
/*    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);*/
    /*box-shadow: inset 0 1px 1px rgba(23, 56, 145, .075);*/
    /*   	position: absolute;*/
    /*top: 0.9975rem;*/
    /*left: 0.875rem;*/
    /*line-height: 147.6%;*/
    /*border-color: red;*/
    /*color: red;*/
    /*transition: top .2s;*/
/*}*/

.ng-star-inserted {
    color: white;
    /*   	top: 0.9975rem;*/
    /*left: 0.875rem;*/
    /*line-height: 147.6%;*/
    /*border-color: red;*/
    /*color: red;*/
    /*transition: top .2s;*/
}

.mat-form-field-label {
    /*border: 1px solid yellow;*/
    color: #fff;
}

/*input-label {*/
/*	position: absolute;*/
/*	top: 0.9975rem;*/
/*	left: 0.875rem;*/
/*	line-height: 147.6%;*/
/*	color: red;*/
/*	transition: top .2s;*/
/*}*/

/*input-underlined {*/
/*	position: absolute;*/
/*	top: 3.9375rem;*/
/*	left: 0.875rem;*/
/*	line-height: 147.6%;*/
/*	color: red;*/
/*	transition: top .2s;*/
/*}*/

/*.mat-form-field-subscript-wrapper {*/
/*    bottom: 8px;*/
/*    border: 1px solid yellow;*/
/*    color: blue;*/
/*}*/

.mat-form-field-flex {
    border-bottom: 1px solid white;
    /*color: red;*/
}

.mat-button-base {
    /*outline: 1px solid #51c9ff;*/
    margin: 6px 8px;
    font-size: 0.9rem;
    /*background-color: #fff;*/
    color: #fff !important;
}

.mat-raised-button {
    background-color: #e6f1ea;
}
### This is my output:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3364738/187072918-a18d8e2a-25f6-4f25-a565-37ddbabf3700.png">
