### ISSUE TITLE
[Bug]  telemetry originator enrichment node output doubled string encoded values only

### ISSUE THREAD

**Issue by nvandamme** [thingsboard/thingsboard#5316]
When using telemetry originator enrichment node in rule chains, added metdata are dumped as string encoded within string for all requested fields.

For example if I request the last temperature (float) of any device, my metadata output will look like : 

metada : 
```
temperature: "\"42.42\""
```

In this state, a string parsing is sinvolved to extract the relevant data from metadata requested by the enrichment node.

Is the enrichment node not responsible to provide metadata's fields extracted and encoded with the right value types ?

for example : 

metada : 
```
temperature: 42.42
```

**Server Environment**
  * local infrastructure on VPS
  * ThingsBoard Version : 3.3.1 (with postgres)
  * OS Name and Version : ubuntu server

**Your Device**

* Connectivity
  * MQTT (with protobuff)

**Comment by JacksonBowe** [comment]
What is the question here though?

What would you like to happen instead of this?

**Comment by tobbelin** [comment]
I have the same "problem".
I would assume a long in my case is stored in the telemetry as a long or at least a string. Not a escaped string in a string.

**Comment by nvandamme** [comment]
> What is the question here though?
> 
> What would you like to happen instead of this?

See a better explanation on my first post

**Comment by PovitruliaV** [comment]
Hi @nvandamme,
Is this issue still relevant?

For example, you can use this template: `JSON.parse(metadata.temperature)` to access fetched telemetry in other nodes.

Regards,
