### ISSUE TITLE
[Question] Export white label and other tenant settings.

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5319]
**Component**

 * UI

**Description**
I want to set up a dev site separate from the main site. 
But to have any value from this I would like to be able to copy settings we try in the dev site to the main site. Most this is white label settings and mail templates.
Is there any smart way of doing this?

**Environment**

 * OS:  Debian, microservices
 * ThingsBoard: 3.3.1
 * Browser: Edge

**Comment by nowherex** [comment]
You can use the Rest API to pull the dev host attributes and upload it to the production host, you can view tenant attributes by accessing your TB PE instance as user with sysadmin permission, clicking tenants > youtenant > attributes, mailTemplates for example

To learn how to use the Rest API visit: https://thingsboard.io/docs/reference/rest-api/

**Remembering that to use tenant attributes, API access must also have sysadmin permissions.
