### ISSUE TITLE
Confirmation about the mobile GPS feature

### ISSUE THREAD

**Issue by muhammadfahad93** [thingsboard/thingsboard#532]
Hi .
   Hope you all are doing fine. Its not a bug or error  issue. I want to just confirmation that thingsboard can work with mobile GPS data. Or you have some things plan for mobile gps tracking use case. Or it possible that mobile GPS support some soon with thingsboards.

Thanks

**Comment by vparomskiy** [comment]
Hi. Is is possible to story any data in Thingsboard because of flexible data schema.
There are also widget that are based on GPS.
Could you please describe in more details, what exactly GPS features you need?

**Comment by fahadabid** [comment]
ok. I want to to store user coordinate data from Mobile GPS to thingsboard and show like tracking. Is in your process do you clean data as according to internet Mobile GPS is not accurate.

**Comment by muhammadfahad93** [comment]
oK I am explaining in detail. I am working on app that sends server it coordinate data from mobile device using GPS plugin. Now i have to show at dashboard about the position and tracking of that user. Second things i about the data . Did thingsboard do some kind of data cleaning as according to internet Mobile GPS data is not accurate.

**Comment by vparomskiy** [comment]
1. Yes, Thingsboard can show position and track of the device
2. There are no 'clining GPS data' algorithms in Thingsboard. But you can easily add such algorithms into the system via Rule Engine. Once you have an algorithm implementation, you can create Rule that will 'clear' GPS data every time when data arrived into Thingsboard
