### ISSUE TITLE
[Question] Localhost page is not working after successful installation and starting of thingsboard. 

### ISSUE THREAD

**Issue by vishnupriyak18** [thingsboard/thingsboard#5329]
**Component**

 * Installation

**Description**
 I've successfully installed and started the thingsboard but when I go to the link 'http://localhost:8080/', I get a page saying " This page isn't working". How can I solve it?

I'm using
 * OS:  Windows 10
 * ThingsBoard: version 3.3.1
 
![Screenshot (128)](https://user-images.githubusercontent.com/75568791/136337676-d6b75ecb-79b2-4b4e-83d1-0b8dda0159d2.png)
![Screenshot (130)](https://user-images.githubusercontent.com/75568791/136337781-43220bc4-353c-4b6a-85cd-d34a110c04ed.png)

**Comment by vishnupriyak18** [comment]
> Hi,
> 
> Provide you thingsboard config. Maybe you changed the default port. And check the /etc/hosts file.

hi, thanks for responding..
i will share the file here, please help me figure out.

**Comment by yulin-willbeok** [comment]
Hi, I have the same problem. The installation starts everything fine, and when I visit http://localhost:8080/时, I have the problem of connection refused, what can I do to fix it?
[Uploading thingsboard.log…]()
