### ISSUE TITLE
[Feature Request] Implement Rule Chain Versioning

### ISSUE THREAD

**Issue by tingznet** [thingsboard/thingsboard#5337]
**Feature Description**
Working on complicated rule chains has the risk of destroying the existing workflow. You have to manually export the rule chain before making modifications as a way of taking backups.

**Proposed solution**
Keeping each saved version of rule chain in the database with an auto-incremented version number could be useful. Whenever you want to revert to a previous version of the rule chain you can select the desired version from the UI and workflow contents will be reloaded. 

If rule chain has new nodes you can increment major version number and if only contents are changed you can increment minor version number. Another approach is to ask to the user the type of version change: users selects major or minor version increment.

**UI Mockup**
![image](https://user-images.githubusercontent.com/85642992/136574851-80ae8c66-9728-4375-913d-5775a81ee755.png)

**Comment by Ultrazombie** [comment]
this will be introduced in version 3.4, see if that helps you.
https://github.com/thingsboard/thingsboard/issues/6033
