### ISSUE TITLE
custom action: Get the current logged user info

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5339]
Unfortunately the issue [3013](https://github.com/thingsboard/thingsboard/issues/3013) was closed.
The proposed solutoins were:

- userService.getCurrentUser()
- self.ctx.currentUser

unfortunately none of these solutions work for PE 3.3.0
I'm really confused because the class [WidgetContext](https://github.com/thingsboard/thingsboard/blob/ff293ae1f452acda2d1d1487d838d278a4a85b4a/ui-ngx/src/app/modules/home/models/widget-component.models.ts#L108) 
contains the getter **currentUser**

How can I access it?

**Comment by JacksonBowe** [comment]
Hi @eeitnn , if this is in a customer widget action then you can just use

```console.log(widgetContext.currentUser)```

Returns this;
```
authority: "TENANT_ADMIN"
customerId: "13814000-1dd2-11b2-8080-808080808080"
enabled: true
exp: 1633911871
iat: 1633902871
isPublic: false
iss: "thingsboard.io"
scopes: ['TENANT_ADMIN']
sub: "devTest@myinsight.io"
tenantId: "d2304e50-1ccc-11ec-b706-d55b5732010b"
userId: "db48a500-1ccc-11ec-b706-d55b5732010b"
[[Prototype]]: Object
```

In my customer widgets I use

`self.ctx.currentUser.userId`

to get the current users id.

**Comment by eeitnn** [comment]
Hi @JacksonBowe,

thanks for the hint. This works for me.
