### ISSUE TITLE
Not able to run the thingsboard web application using thingsboard.deb file

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#534]
Hi,
       After build-ed Things-board source i have customized successfully. but when I trying to deploy the thingsboard.deb file to start the thingsborad service,  **Getting the following Error :**

 **ERROR 5546 --- [0.0-8080-exec-1] org.apache.velocity : ResourceManager : unable to find resource 'error.vm' in any resource loader.**

Thanks,

**Comment by rof20004** [comment]
Maybe compile issues, try to run mvn clean install again and check your changes, licenses changes. In my case I got this error when I created a wrong code somewhere.

**Comment by mp-loki** [comment]
this is because UI module was not built successfully. We faced this issue before on some machines, but we don't have a stable fix for it so far

**Comment by CooL16** [comment]
The Velocity is looking for this template if it has an errors so you may have a problem with a template and it trying to get the error content but cannot.
Per http://s2velocity.sandbox.seasar.org/en/error_template.html "when an error caught in a view template and rendering is forwarded to error.vm."

You can change the name of this in the property files according to the documentation.
