### ISSUE TITLE
No Keys found in the "ts_kv_dictionary" table yet, on the "latest telemetry tab" of Device, data shows

### ISSUE THREAD

**Issue by periatrubikx** [thingsboard/thingsboard#5340]
**Component**

UI

**Description**
I am sending some basic JSON data (temp, humidity etc.) and the "latest telemetry tab" is showing the data. However, when i try to build the dashboard; add entity alias for the device, it says "no Keys found". Upon look at the ts_kv_dictionary, sure enough there arent any keys. 

**Environment**

version 3.2.0
running locally
postgrest db.

I was trying to look for where the keys were coming from in the ts_kv table but unable to trace.

**Comment by JacksonBowe** [comment]
@periatrubikx what if you just write out the full key yourself. As in, if you know your key is "temperature", write out the word temperature and hit the "create new timeseries key" option.
![image](https://user-images.githubusercontent.com/26427343/136716165-91372ed5-e54a-4e41-a343-5d90d7c8a86a.png)


Does that update the ts_kv_dictionary table?

**Comment by Ultrazombie** [comment]
Hello @periatrubikx,
Are your problem still exist?
Please provide a piece of new information if so.
