### ISSUE TITLE
[Question] How to add a custom action Source to the action Settings of custom widgets  ?

### ISSUE THREAD

**Issue by yaodadaa** [thingsboard/thingsboard#5341]
![image](https://user-images.githubusercontent.com/55545124/136741724-304243a2-a833-41d0-9e96-0d9755b4019f.png)

I want to add a custom action Source here

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
