### ISSUE TITLE
[Question] What is the data size limit for JSON telemetry via http Integration ?

### ISSUE THREAD

**Issue by ChrisEvisi** [thingsboard/thingsboard#5342]
**Component**
 * Integrations (HTTP)

**Description**
Im trying to process and save JSON telemetry value via http Integration and data converter which is about 280 kB.  The Integration processes the JSON payload and sends to Data Converter Input which can be seen in Events log, but there is no associated Data Converter record.  
This was working prior to upgrading to v3.3.1 PE so it may be that the upgrade changed this or all prev JSON msgs were smaller kB size.  Anyway, does anyone know what the kB limit is for JSON telemetry via http Integration and Data Converter ?  
Thanks for any help with this

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.3.1 PE
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
There is no limit, you can raise the payload size in the ThingsBoard settings if you get more than 1MB, but we advise you not to use such a large payload.

**Comment by Raven888888** [comment]
@Ultrazombie May I know which setting to set? I am hitting server internal error 500 when sending 1MB message through http telemetry API.

**Comment by lstarke** [comment]
Any updates about this question ?
