### ISSUE TITLE
Custom Maps Widget.

### ISSUE THREAD

**Issue by JacoFourie** [thingsboard/thingsboard#535]
Hi all. I love Thingsboard. It really is very cool software.

Can I make my own custom maps widget? I need to draw a line and only one line. I am tracking the location of a Water Pivot. Here is a sample of what I am doing.

http://demo.thingsboard.io/dashboards/76f7adb0-fafe-11e7-abe9-1d8d2edf4f93?publicId=62079880-f6e8-11e7-abe9-1d8d2edf4f93

What I am doing now is to send 2 lat longs every time I send the data. So that the widget will draw the line from the center point every time. But obviously that is not the correct way. As it draws 2 lines and will vanish if left for too long

So what I need is to have one static point that I configure and the the GPS module will send its location. Then the widget should draw the line from the center point to the position.

I hope somebody can help or point me in the correct direction.

**Comment by Javierete** [comment]
Hello @JacoFourie I will do the same as you on a few days, as I have a pivot with GPS module connected to my supervisory system (SCADA).
On the next days I will connect and try visualization with thingsboard and maybe can help.

**Comment by JacoFourie** [comment]
Hi. I assume that you have to use a Polyline like in this sample.

https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

But how to you modify the widget in Thingsboard to add the custom code ?

**Comment by JacoFourie** [comment]
Is there no documentation on how to do this with the Widgets ?

**Comment by JacoFourie** [comment]
@Javierete did you get this working yet ?

**Comment by ant4res** [comment]
Hello! I'd like to add a shape file or a polygon to my map on Thingsboard. Did you succeed in your attempt to add custom code to the widget?

**Comment by ant4res** [comment]
Hi! I developed with success a custom widget for a time series chart, but I'm not able to access the Google map object to modify the existing Google Map widget.
Starting from the fact that *self.ctx.map* is a TbMapWidgetV2 object, *self.ctx.map.map* should be a TbGoogleMap object and *self.ctx.map.map.map* should be a Google map object.
But, when I try to execute a Google method on this, I obtain the followin error:
***undefined is not an object (evaluating 'gmap.getBounds')***

What is wrong in the following code?

self.onInit = function() {
    self.ctx.map = new TbMapWidgetV2('google-map',
        false, self.ctx);
    gmap = self.ctx.map.map.map;
    gmap.getBounds();
}

Thanks in advance to anyone who can help me.

**Comment by JacoFourie** [comment]
@vparomskiy I can not follow the tutorial as I do not see "Create Widget Type". I only have "Create new Widget Bundle" and there I can only change the name.

**Comment by EitharYassin** [comment]
Is it possible to modify one of thingsboard widget?

**Comment by mfalkvidd** [comment]
@EitharYassin yes. Create a new (empty) widget bundle. Open the widget you wanr to modify. Click Save As. Save it in your new bundle.

**Comment by EitharYassin** [comment]
I want to ask @JacoFourie about the line in the map?

**Comment by mkdthanga** [comment]
Hello everyone,
I would like to know, if there is any possibility to generate data visualization using ‘Open Street Map’ automatically just by giving the device name alone (without feeding the individual device parameters/attributes ex. latitude, longitude, level, etc.).

Requirements:
In the below screenshot, the highlighted parameters should be extracted by the map widget and plot the tooltips and markers for each parameter automatically instead of feeding each individual parameter separately.

![Tb_map_widget_problem](https://user-images.githubusercontent.com/36918728/95303831-01924300-0884-11eb-9d00-d2717be47f67.png)

Regards,
Thangaraj

**Comment by Aviijit** [comment]
is there any documentation available to create a custom map widget?
Because I'm not able to add a custom google map in thingsboard widget

**Comment by ezeroldan24** [comment]
Anyone knows how to add custom tools to the google map, such as directions, stops, layers?

**Comment by AtaGunZ** [comment]
it's 2025 and there is still no documentation about how map widgets really work.
