### ISSUE TITLE
How to pass data from custom map widget to marker image function?

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5355]
I've created a custom map widget based on the OpenStreetmap-Widget.
Inside the onInit()-function I'm computing some data.
Is there some way to make this data available to the marker image function of the widget?

Since the marker image function is passed the parameters data, images, dsData and dsIndex I was wondering if can modify the contents from within the onInit-function maybe.

However, I'm not sure where to start. There is an object **self.ctx.data** which holds an array which looks very similar to what is inside **dsData**. 
But modifying this object has no effect on the resulting dsData object.

There has to be a better way to share objects between these different scopes.
Any ideas?

**Comment by vvlladd28** [comment]
Hi @eeitnn,
You can't change the data inside the onInit()-function.
To modify the data you can use a Use data post-processing function in data-key settings or write your own function and called inside onDataUpdated-function before `self.ctx.map.update();`
