### ISSUE TITLE
Thingsboard installed server has error

### ISSUE THREAD

**Issue by anbha** [thingsboard/thingsboard#536]
Hi

When i tried to create a new plugin in own installed server, it shows error message.
But in thingsboard demo server working fine. Then why Own installed thingsboard server has this type of problem.
The error is 
GET: /api/plugins/telemetry/PLUGIN/4021ed90-fb45-11e7-9e10-cf623b3d6578/values/attributes/SERVER_SCOPE
404: 

Anybody can explain what is the problem this and how can i solve this problem. Your answer is so helpful for me.

Thanks&Regards

**Comment by rof20004** [comment]
You followed the installation and configuration steps exactly like tutorial?

**Comment by anbha** [comment]
Hi @rof20004 ,
Thanks for your reply.

Yes, I followed the installation and configuration steps exactly like tutorial.
I can't understand what is the problem and i how to solve this. 

Thingsboard installed server working fine before 2 weeks, and i use the plugin but now its not working.  
I use the 1883 port for MQTT when installation.  Am trying to sending Email through Gmail. Am using port 587 for SMTP. If i want to add any other port when I install thingsboard server for sending Email?

So explain me what is the issue is this? and, how to i solve this?

Thanks&Regards

**Comment by rof20004** [comment]
Did you restarted the application?
Try to reboot your machine too.

Yesterday I was receiving many errors about mqttextension, I stopped the service but the errors still showing. I did this:

# netstat -tulpn | grep :8080

And I saw that the proccess was not stopped, O killed the proccess and start works again.

Regards.

**Comment by anbha** [comment]
Hi @rof20004  

Yes, i restarted my application and reboot the machine. 
But it's not working. The same issues are repeating. 
I check the log file, on there the MQTT are working. But the Data are not Receiving by Thingsboard device.
The same issue (mentioned above) occurred.  
What can i do now? 

Thanks&Regards

**Comment by Karabiy** [comment]
the plugins are now deprecated.
It is all okay for the ThingsBoard current versions. In case if you see no data in the telemetry and the data is being pushed, go for the first node in the root rule engine and press debug mode there, to make sure that the data is being received. 
Also, make sure that there is no websocket proxying on the side of yours.
