### ISSUE TITLE
[Question] Is there a way for the device to easily get firmware from the TB server via http(s)

### ISSUE THREAD

**Issue by MrZANE42** [thingsboard/thingsboard#5366]
**Component**

 * Generic

**Description**
We use a Quectel 4G modems at commands to connect to a thingsboard server.
Normally all communication goes over mqtt but the firmware update needs to be over http(s) as the firmware is stored in the modems internal file-system prior to update. While it is possible to write code that fetches in chunks over mqtt there is already a system in place for getting the firmware via a http GET request. This works with OTA packages that link to external URL but is it possible to also fetch a firmware/software, stored in thingsboard cloud, for the specific device with just a REST get call (including device token of course)? I've looked though the documentation but not been able to find anything.
If not I would be very grateful if this could be added

**Environment**
 * OS:  Windows 10
 * ThingsBoard: PaaS v.3.3.2PAAS-RC1 (Subscription: Prototype)
 * Browser: Chrome

**Comment by ashvayka** [comment]
Hi @MrZANE42 , while @vvlladd28 provided a good end-to-end example written in Python, I would like to also share the actual API to download the firmware over HTTP: https://thingsboard.io/docs/reference/http-api/#firmware-api

**Comment by MrZANE42** [comment]
Sounds good, and maybe also write in the documentation that the parameter are there if you want to make sure you are getting what you think.
The idé of having them as an extra check makes sense now that you've explained it.
Thanks for your help and your excellent product.

Skaffa Outlook för Android<https://aka.ms/ghei36>
________________________________
