### ISSUE TITLE
Widget UI elements misaligned

### ISSUE THREAD

**Issue by SanderElsen** [thingsboard/thingsboard#537]
while using the thingsboard demo I often come across a problem with the UI.
the card widgets for example have their data sunk like this:
![alt](https://image.prntscr.com/image/m6eG0iiOSEm15lYVu5BfFw.png)
when I refresh the page it's fixed:
![alt](https://image.prntscr.com/image/RhP71iz0R_KOXYm4FjvxHg.png)

**Comment by LeoMorgan113** [comment]
Hi @SanderElsen,

This problem fixed in v3.2.2.
https://thingsboard.io/docs/reference/releases/
