### ISSUE TITLE
Use link / url to set dashboard entity?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#5377]
Hi
we would like to link from Alarm email to the dashboard showing the entity that produced the alarm.

i can include entity id, name, label, in the email in the link, but how to use this to load entity in the dashboard? 

that need is to show user with 1 click a nice graph of the alarm.

any way to achieve this?

thanks

**Comment by t0mZ4** [comment]
works well, closing.

**Comment by Produmize** [comment]
Is it also possible to a dashboard with f.e. timeseries widget and give it a start and end time and show that?

**Comment by rusko-hypros** [comment]
@Produmize did you find a proper solution?
