### ISSUE TITLE
[Bug] Map view, multiple entities/markers broken. 

### ISSUE THREAD

**Issue by janvl1234** [thingsboard/thingsboard#5391]
Bug report was closed, bug was never fixed.
See: https://github.com/thingsboard/thingsboard/issues/4359

**Comment by vvlladd28** [comment]
Hi @janvl1234,
Thank you for your report, we have checked on our side - it works correctly in the last version TB.
![Screenshot from 2021-10-18 16-18-05](https://user-images.githubusercontent.com/18036670/137738998-83b3dbc3-ce5a-4b00-8443-02bbcef5785c.png)
Could you please check your key names and what is your version of TB?

**Comment by janvl1234** [comment]
Hi @vvlladd28, 
Thanks for testing the issue on your side again. 
I am using ThingsBoard v3.3.1
The differences in on your side an my side is that you use Attribute values and I use Telemetry values. 
Can you try on your side telemetry values? 
I have the same result with only the latest lat/lon shown when using telemetry values. On both the map and route map. 
I will update my script to send the values into the Attributes and see if that works.

**Comment by janvl1234** [comment]
Hi @vvlladd28 ,
Do you have any idea how I can solve the issue?
