### ISSUE TITLE
[Question] How to use a widget to upload a CSV file with telemetry?

### ISSUE THREAD

**Issue by richardgarcia892** [thingsboard/thingsboard#5399]
**Component**
 * Generic

**Description**
Hello, I need to add a custom widget that allows user to upload a CSV File that contains several telemetry manually taken from a device that doesnt have any kind of real time connectivity, then bulk load the telemetry data from the CSV to the device and reload the dashboard state (in order to make the new telemetry visible in all other widgets)

In the best escenario the widget would allow user to select the device from a dropdown / search bar form and then upload the CSV file, however, just to make everything as simple as posible Just uploading the CSV and using the file name or even a column from the CSV itself (in case the CSV carries data from more than one device) would be enought.

another option would be a input text form, where the user just paste the CSV content.

How can I archieve this?

Thanks!

**Environment**
 * ThingsBoard: 3.1.1

**Comment by volodymyr-babak** [comment]
@richardgarcia892 
Here is the source code of the default import widget of the ThingsBoard platform: 
https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/app/modules/home/components/import-export

You can use it as a base for the implementation of your custom widget.
And here is the link to the custom widget development guide:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/

And here is the link to how to build ThingsBoard from sources:
https://thingsboard.io/docs/user-guide/install/building-from-source/
