### ISSUE TITLE
How to show asset' data which contain some thermostats on card?

### ISSUE THREAD

**Issue by FocusYangQ** [thingsboard/thingsboard#540]
I see it's something about asset' attribute.
![qq 20180119104402](https://user-images.githubusercontent.com/35205142/35132344-bc95193a-fd05-11e7-9271-e31c4d8559f3.png)
![qq 20180119104412](https://user-images.githubusercontent.com/35205142/35132345-bcc96762-fd05-11e7-87b1-dc992be00f87.png)
But attribute is a static state.How to show a dynamic data？

**Comment by RondoRonaldo** [comment]
Can you specify whether the issue persists?
