### ISSUE TITLE
[Bug] Rule node IN type event order is out of order

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#5402]
**Describe the bug**
When the QoS of mqtt is 1, send 1,2,3,4,5 telemetry data in sequence through mqtt. View the events of type in in the switch rule node, and the order is 1,2,4,3,5. The wrong order causes data processing exceptions.

**Your Server Environment**
Thingsboard 3.3.0 docker environment with:
haproxy-certbot:1.3.0
4 tb-node:3.3.0
20 tb-js-executor:3.3.0 
2 tb-mqtt-transport:3.3.0
2 tb-http-transport:3.3.0
1 tb-coap-transport:3.3.0  
1 kafka:2.13-2.6.0
1 redis:4.0 
1 postgres:12
1 cassandra:3.11.3

Ubuntu 20.04 x64
Mozilla Firefox 92.0

* Connectivity
 MQTT

**To Reproduce**
1.  The device sends the telemetry value to TB every 500 milliseconds
2.  Telemtry value is like "seq":6239994  "seq":6239995  "seq":6239996  "seq":6239997  "seq":6239998  "seq":6239999  
3.  In the rule node open debug mode
4.  Check the IN type event data, the msg order is not same as mqtt input, maybe like: "seq":6239994  "seq":6239995  "seq":6239996  "seq":**6239998**  "seq":6239997  "seq":6239999   
 

**Expected behavior**
Rule node IN type data is same as mqtt send order

**Comment by xiddjp** [comment]
Ok, with this queue, the order can be guaranteed. 
But there is another problem, sometimes i got four or five input when i send only one telemtry...

**Comment by sferguson-ISI** [comment]
I have this same issue where there are multiple inputs and only one output @xiddjp , were you able to solve that?
