### ISSUE TITLE
[Bug] Can't change active ttl(Time To Live) parameter under server attributes to device 

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5404]
Hi,

I receive measurement data of the device at certain intervals. If the relevant data from the device does not come within the time to live (ttl) time, I want to display it under the server attributes, which are under the device, passively, if the data is received, it is active.

When I send ttl(Time To Live) data as a string with Python, I get an error. Instead, I couldn't see any improvement in the time I sent it in milliseconds.
I request your support on the matter. 

Best Regards,
Gohm Team

** Server Environment**

    own setup

        docker deployment

        OS: Linux(Ubuntu 20.04)

** Client Environment**

    OS: Linux(Ubuntu)
    Browser : Chrome, Firefox
    Version Ubuntu Version 20.04

**Comment by gohm-tech** [comment]
`        body = {}
        body["rssi"] = rssi
        ttl_ms = DEFAULT_GATEWAY_ALIVENESS_TIMEOUT_MS
        self.rest_client.save_entity_telemetry_with_ttl(body, entity_type=gateway.id.entity_type, entity_id=DeviceId(gateway.id.entity_type, gateway.id.id), scope="IGNORED", ttl=str(ttl_ms))`

**Comment by gohm-tech** [comment]
Hi @ashvayka 

Can you please reply?
Is there anything you wonder about our system?

Best Regards,
Gohm Team

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
