### ISSUE TITLE
"Autoplay" function for timewindow

### ISSUE THREAD

**Issue by jln-ho** [thingsboard/thingsboard#542]
Hi everyone,

I'm looking for a way to automatically change the timewindow on a dashboard. 

For example, the user should be able to specify a time window from time ``t1`` to time ``t2``, along with a ``step_size`` and a ``speed``. They could then press "play" or "pause" or something like that to automatically change the time period to the interval ``[t1 + i * step_size ; t2]`` every ``speed`` seconds, where ``i`` is just a counter that is incremeneted every ``speed`` seconds. A movable slider at the bottom of the dashboard to adjust the time window manually or simply watch it advance would be great, too.

I started looking for some way to manipulate the global timewindow from within a single widget in the [widget API documentation](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#basic-widget-api), but as far as I can tell this is not supported (probably for good reasons, lots of potential for weird side effects).

So my questions are:

- Is there some workaround or hack to modify the global timewindow from within a widget?
- If not, where would I have to start to extend thingsboard in order to support the desired functionality? (I'd be willing to submit a PR if it seems doable)
- Are others interested enough in this functionality to maybe turn this into an "offical" feature request?

Thanks!

**Comment by PovitruliaV** [comment]
Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1367) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our Release Notes to see all new additions to the platform in the subsequent releases.
