### ISSUE TITLE
[Question] Deploy to AWS EKS with the build from source

### ISSUE THREAD

**Issue by EddieChinZJ** [thingsboard/thingsboard#5435]
* Installation

**Description**
I would like to host my own build on AWS EKS.
May I know how k8s works with the build from source?

Thank you.

**Comment by trikimiki** [comment]
You can build Docker images as specified in the guide: https://thingsboard.io/docs/user-guide/install/building-from-source/#build-local-docker-images.
Then, you can upload these images to some image registry (e.g. [Docker Hub](https://hub.docker.com)).
