### ISSUE TITLE
[Bug]  Could not resolve dependencies for project org.thingsboard:application:jar:3.3.1: org.thingsboard:dao:jar:tests:3.3.1 was not found

### ISSUE THREAD

**Issue by brewswang** [thingsboard/thingsboard#5448]
**Describe the bug**
] Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:3.3.1: org.thingsboard:dao:jar:tests:3.3.1 was not found in https://repo.jen
kins-ci.org/releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jenkins has elapsed or updates are forced -> [H
elp 1]

**Your Server Environment**

* own setup
  * ThingsBoard Version release 3.3
  * OS Name and Version win10

**Comment by lwd369** [comment]
You could run command ```mvn clean install ```, don't skip tests. Then the dao-3.3.1-tests.jar should installed locally in maven.
Or you could try manually download the jar file from [here](https://repo.thingsboard.io/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-public/org/thingsboard/dao/3.3.1/dao-3.3.1-tests.jar), then put it into your local maven repository.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
