### ISSUE TITLE
[Question] OTA

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5460]
**Component**

 * Rule Engine

**Description**
I connect my devices using an integration. When I create OTA packages I would like to upload these to my devices.
Can this be done using a rule engine script or something easy like that? The integration uses REST API.
I guess this can be done if I only could access the package from the rule engine. Is there a way to do that?
  
**Environment**
 * ThingsBoard: 3.3.1

**Comment by tobbelin** [comment]
Thanks.
The integration is to another platform that is a bit more limited than thingsboard, so it would be easier for me to push the files from thingsboard.
Is there any way to access the actual files from rule engine?
Or is it recommended to run scripts in the rule engine that actually uses the REST API of both thingsboard and the other platform?

**Comment by Nathan-ma** [comment]
@tobbelin Well, I don't think I truly understood this platform's limitations. I thought you would be able to do an HTTP request and download the files. and for that, I must say I'm sorry.

Now Answering your second post. I don't really know if there is a way to use only the rule engine, but this might help you somehow, keep in mind I don't think you can actually use it inside a rule, but maybe there is.

<img width="1350" alt="CleanShot 2021-11-01 at 00 06 22@2x" src="https://user-images.githubusercontent.com/11060905/139616401-9b358d74-c309-4adc-83ba-bad93e28fe06.png">

This is the code for the action button inside the dashboard that allows you to download said files.

This tells me there must be an otaPackageService Running. and inside said service, a method to download files using Device Profile ID.

How to link this into the rule engine I honestly don't know, I believe using the External REST API Rule is the way to go (without using what was mentioned).

**Comment by tobbelin** [comment]
Hi,
Thanks alot, an no need to say sorry for helping. And that information was not even there. :-)
I think I will try to make this as an external synk script instead then.

Many thanks again.
