### ISSUE TITLE
[Bug] ThingsBoard Gateway Modbus Connector

### ISSUE THREAD

**Issue by serifis84** [thingsboard/thingsboard#5467]
**Describe the bug**
Cannot set a coil with function 5

**Your Server Environment**
* own setup
  * ThingsBoard Gateway 2.8

**To Reproduce**
modbus.json

{
	"server": {
		"name": "XXXXXX",
		"type": "tcp",
		"host": "XXXXXXXXXX",
		"port": 510,
		"timeout": 35,
		"method": "socket",
        "byteOrder": "BIG",
		"retries": true,
		"retryOnEmpty": true,
		"retryOnInvalid": true,
		"devices": [
			{
				"unitId": 1,
				"deviceName": "XXXXXX",
				"deviceType": "XXXXXXXXX",
				"attributesPollPeriod": 5000,
				"timeseriesPollPeriod": 3000,
				"sendDataOnlyOnChange": true,
				"connectAttemptTimeMs": 5000,
				"connectAttemptCount": 5,
				"waitAfterFailedAttemptsMs": 300000,
				"timeseries": [
				  {
					"tag": "MeterA_flow",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 0
				  },
				  {
					"tag": "MeterA_cubic",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 2
				  },
				  {
					"tag": "MeterA_total",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 6
				  },
				  {
					"tag": "MeterB_flow",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 10
				  },
				  {
					"tag": "MeterB_cubic",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 12
				  },
				  {
					"tag": "MeterB_total",
					"type": "int",
					"functionCode": 3,
					"registerCount": 1,
					"address": 16
				  }
				],
				"rpc": [
					{
						"tag": "Q1",
						"type": "coil",
						"functionCode": 5,
						"objectsCount": 1,
						"address": 8192
						},
					{
						"tag": "Q2",
						"type": "coil",
						"functionCode": 5,
						"objectsCount": 1,
						"address": 8193
					}
				]
			}
		]	
	}
}

** Gateway debug**

*From RPC debug TErminal Tried:
Q1 false
Q1 False

''2021-10-29 14:04:55' - DEBUG - modbus_connector - 408 - Modbus connector received rpc request for Logo8 with server_rpc_request: {'device': 'Logo8', 'data': {'id': 99, 'method': 'Q1', 'params': False}}'
''2021-10-29 14:04:55' - ERROR - modbus_connector - 437 - 'bool' object is not iterable'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 424, in server_side_rpc_handler
    self.__process_rpc_request(server_rpc_request, rpc_command_config)
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 449, in __process_rpc_request
    rpc_command_config, content)
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/bytes_modbus_downlink_converter.py", line 70, in convert
    builder_functions["bits"](value)
  File "/usr/lib/python3.7/site-packages/pymodbus/payload.py", line 161, in add_bits
    value = pack_bitstring(values)
  File "/usr/lib/python3.7/site-packages/pymodbus/utilities.py", line 94, in pack_bitstring
    for bit in bits:
TypeError: 'bool' object is not iterable

*From RPC debug TErminal Tried: 
Q1 0

''2021-10-29 14:06:54' - DEBUG - modbus_connector - 408 - Modbus connector received rpc request for Logo8 with server_rpc_request: {'device': 'Logo8', 'data': {'id': 100, 'method': 'Q1', 'params': 0}}'
''2021-10-29 14:06:54' - ERROR - modbus_connector - 437 - 'int' object is not iterable'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 424, in server_side_rpc_handler
    self.__process_rpc_request(server_rpc_request, rpc_command_config)
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 449, in __process_rpc_request
    rpc_command_config, content)
  File "/usr/lib/python3.7/site-packages/thingsboard_gateway/connectors/modbus/bytes_modbus_downlink_converter.py", line 70, in convert
    builder_functions["bits"](value)
  File "/usr/lib/python3.7/site-packages/pymodbus/payload.py", line 161, in add_bits
    value = pack_bitstring(values)
  File "/usr/lib/python3.7/site-packages/pymodbus/utilities.py", line 94, in pack_bitstring
    for bit in bits:
TypeError: 'int' object is not iterable

*From RPC debug TErminal Tried: 
Q1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

''2021-10-29 14:11:59' - DEBUG - modbus_connector - 408 - Modbus connector received rpc request for Logo8 with server_rpc_request: {'device': 'Logo8', 'data': {'id': 103, 'method': 'Q1', 'params': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}}'
''2021-10-29 14:11:59' - DEBUG - modbus_connector - 290 - Modbus connected to device Logo8.'
''2021-10-29 14:11:59' - DEBUG - bytes_modbus_downlink_converter - 94 - [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]'
''2021-10-29 14:11:59' - DEBUG - modbus_connector - 397 - With result WriteCoilResponse(8192) => 1'
''2021-10-29 14:11:59' - DEBUG - modbus_connector - 478 - Write 'WriteCoilResponse(8192) => 1''
''2021-10-29 14:11:59' - DEBUG - modbus_connector - 490 - {'success': True}'

**Comment by samson0v** [comment]
Hi @serifis84, your issue was fixed, please, update your Gateway via the master branch.
Thanks for your interest in ThingsBoard IoT Gateway.

**Comment by serifis84** [comment]
@samson0v Could you please post how to call the RPC for the above modbus.json? Do i have to send for example: Q1 False or Q1 0? I have defined Q1 and Q2 as "coil" type so it is expected to Set or Unset them. It is not a 16bit byte-array but single-bit component.
Thank you for your help!

**Comment by serifis84** [comment]
@samson0v ok found something, maybe is a bug or just it works like this? 
If defined like this

                                                "tag": "Q1",
                                                "type": "coil",
                                                "functionCode": 5,
                                                "objectsCount": 0,
                                                "address": 8192
with objectsCount -> 0  Then it works like a charm

**Comment by TTnTTT** [comment]
I try to write register with follow config：
{
            "tag": "aa",
            "type": "register",
            "functionCode": 6,
            "objectsCount": 0,
            "address": 40038,
            "value": 22
          }
but receive an error.

**Comment by serifis84** [comment]
@TTnTTT this syntax was from an older version. If you installed the latest version and download the latest config examples https://github.com/thingsboard/thingsboard-gateway/releases/download/3.1/configs.tar.gz you will find a modbus json example
