### ISSUE TITLE
Widgets Development

### ISSUE THREAD

**Issue by PankajHack** [thingsboard/thingsboard#5471]
I am trying to create a new custom widget in that i made a dropdown menu and i want the table beow that dropdown cahnges as i change the selected value in the dropdown i am not able to do it can anyone help me in this .
How i am trying to do this is i am making multiple datasources and want to get the data by switching beteen the datat from those datasources. Please help

**Comment by PankajHack** [comment]
Please dont tell me to refer to the documentation as it might be useful for expirienced people but i am a newbiew and not understanding how to do it

**Comment by serfreeman1337** [comment]
Are you using "Entities table" widget and trying to switch devices for datasource with dropdown ?

Take look at [dashboard states](https://thingsboard.io/docs/user-guide/ui/widget-actions/#update-current-dashboard-state). There is clear screenshots how to achieve this.

Then take a look at https://github.com/thingsboard/thingsboard/issues/5183#issuecomment-915378143 for state switching code to use with dropdown.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
