### ISSUE TITLE
Bug for card widgets for decimal setting

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5475]
label card and value card can not set decimals, whatever your setting is, it always show 2 decimals. 
bug code as below:
            var valDec = 2;
            var splitVals = label.split(':');
            if (splitVals.length > 1) {
                label = splitVals[0];
                valDec = parseFloat(splitVals[1]);
            }
            
For TB3.2.0 and all elder version has this bug. 
How to make decimal setting work as timeseries table?

**Comment by jasonlee9900** [comment]
I fixed the problem by change code "valDec = parseFloat(splitVals[1]);" to "valDec = parseInt(splitVals[1]);"
I believe TB3.3.1 also has this bug, althrought i didn't test it. 
anyway, the way setting decimals by {##:**} are not very convenience as how timeseries table.

**Comment by trikimiki** [comment]
I cannot reproduce it for 3.3.3. Could you please check if this is reproducing in your environment with the latest version?
