### ISSUE TITLE
[Question] Problem for install  TB with Microservices architecture

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#5480]
**Component**

 * Installation

**Description**
This error appears and does not let me enter, I have followed the manual adding kafka.

![image](https://user-images.githubusercontent.com/78015483/139906079-823e69ac-eb3e-4adc-b349-4533ad7ccdef.png)

**Environment**

 * OS:  w10
 * ThingsBoard: 3.3.1PE
 * Browser: google

**Comment by AbrahamSalvi** [comment]
![image](https://user-images.githubusercontent.com/78015483/140059192-db4edb4d-f31f-41bf-969a-2a4d8732e562.png)

**Comment by trikimiki** [comment]
Closed as duplicate to #5491
