### ISSUE TITLE
'RestClientCE' object has no attribute 'rpc_v_2_controller' [Bug] 

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5481]
Hi, 
We want to use "handle_two_way_device_rpc_request_v1" function under the RestClientCE class. But when we try to use this function, we got this error. 
![Screenshot from 2021-11-03 10-24-35](https://user-images.githubusercontent.com/91528436/140024335-ce5a82a5-b273-42d6-9116-2f08638faa9b.png)
When we examined the RestClientCE and RestClientBase class, we saw that the error came from here.
![Screenshot from 2021-11-03 08-45-34](https://user-images.githubusercontent.com/91528436/140025319-ccde4d7d-bc3b-4c6c-a4e0-28c05a975465.png)

![Screenshot from 2021-11-03 08-44-54](https://user-images.githubusercontent.com/91528436/140025328-540f60bb-e0d2-497e-b9cb-1afba18ccb67.png)

Best Regards,
Gohm Team

** Server Environment**

own setup

    docker deployment

    OS: Linux(Ubuntu 20.04)
** Client Environment**

OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

**Comment by ashvayka** [comment]
The error is in the autogenerated code you are using? The v1 is deprecated. Please consider using handle_two_way_device_rpc_request_v2. It is the same interface but different result codes in the case of offline devices.

**Comment by gohm-tech** [comment]
Hi,
We did not find this "handle_two_way_device_rpc_request_v2" function. Can you direct us?

https://github.com/thingsboard/thingsboard-python-rest-client/blob/master/tb_rest_client/rest_client_ce.py

Best Regards,
Gohm Team

**Comment by samson0v** [comment]
Hi @gohm-tech, your issue was fixed. Please, update your rest client to the newest version via the master branch.

Sorry for the inconvenience 💙

**Comment by gohm-tech** [comment]
Hi, 
I think there is no update on the pip package. 
https://pypi.org/project/tb-rest-client/#description

**Comment by samson0v** [comment]
@gohm-tech yep, because we didn't do the release version yet, so for now you have to update the rest client via the master branch from [github](https://github.com/thingsboard/thingsboard-python-rest-client)

**Comment by gohm-tech** [comment]
Hi @samson0v 
Thanks for the information.
Best Regards,
Gohm Team
