### ISSUE TITLE
[Question] Asset Table Refresh

### ISSUE THREAD

**Issue by Mmhlschmidt** [thingsboard/thingsboard#5487]
**Component**

 * UI

**Description**
I have an asset table that displays various assets of a certain type.  REST calls are sent to thingsboard that may add or delete those assets but it takes a while for the widget to update. Is there a way to kick the widget so it refreshes what it displays?

**Environment**

 * OS:  name and version
 * ThingsBoard: 
 * Browser: Edge

**Comment by JacksonBowe** [comment]
I don't think you refresh the widget, but rather the entity alias.

Widgets have an onDataUpdated() method that refreshes them, so changing the data (by updating the alias) will update the widget.

Through widget actions you can add this line `widgetContext.updateAliases();` after adding/deleting your assets.

**Comment by Mmhlschmidt** [comment]
Thanks. I am creating new assets through REST calls. Is there a rest call
to update the aliases?

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
