### ISSUE TITLE
Saving new custom widget- unable to connect error

### ISSUE THREAD

**Issue by hadawie** [thingsboard/thingsboard#5489]
**Component**

 * UI/Widgets

**Description**
I am developing a custom widget to that will visualize latest data from a sensor; problem is that I can't save it! whenever I try to save it I get the message "Unable to connect"!

Not sure if this is relevant, but my environment uses postage DB and when I checked the widgets_bundle table is was empty although I can access and use the preinstalled widget bundles. 

Any advise is much appreciated, thank you.

**Environment**

 * OS:  Ubuntu 20.x, local personal server
 * ThingsBoard: 3.3.1
 * Browser: Safari

**Comment by sferguson-ISI** [comment]
Same issue, makes it impossible to make changes to widgets.  Only started having this issue after I upgraded from 2.4.2.1.
OS: Windows Server 2016
Thingsboard: 3.3.2
Browser: Chrome and Firefox
PostgresDB hosted on AWS RDS.

**Comment by sferguson-ISI** [comment]
Update on this, I think I know what might be causing this error @hadawie I believe it's a timeout issue with the database when you try to save widget changes.  For me I have Thingsboard database hosted on AWS RDP and my Thingsboard instance is on a EC2 instance.  If I remote into EC2 and then open up a browser and make my changes there, I don't get the dreaded "unable to connect" message.  @ashvayka is there a database timeout for widgets setting somewhere that can be adjusted?

**Comment by pon0marev** [comment]
You may see this message if thignsboard could not execute the query within 30 seconds (this is a predefined timeout value).
To improve the performance of database queries, you can set the following parameters:
```
export SPRING_DATASOURCE_MAXIMUM_POOL_SIZE=20
export SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_BY_DEFAULT_NULL_ORDERING=none
```

**Comment by jrkubic** [comment]
[#15536](https://github.com/thingsboard/thingsboard/issues/15536)
