### ISSUE TITLE
How can I get the JWT_TOKEN of current tenant in the widget?

### ISSUE THREAD

**Issue by hanyuwenn** [thingsboard/thingsboard#549]
I wrote a widget that needs to get all the devices of the current tenant through the REST API. But the REST API for getting all devices requires JWT_TOKEN. How to get the JWT_TOKEN of the current tenant in the widget.

**Comment by souhaiebtar** [comment]
@hanyuwenn  maybe it is late but you can do it using:

```
     userService = self.ctx.$scope.$injector.get('userService');
    const jwt_token = userService.getJwtToken();
```

**Comment by Karabiy** [comment]
the JWT_TOKEN of the current user is being stored in the local storage 
you can try to use the next for the reasons of yours also
`localStorage.get(key)`
