### ISSUE TITLE
[Bug] Problem for install TB with Microservices architecture

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#5491]
**Describe the bug**

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [linux]
* Browser [chrome,]
* Version [3.3.1PE]

**Expected behavior**
I have followed this manual but I run into errors when installing TB in microservices.

https://github.com/thingsboard/thingsboard-pe-docker-compose
https://thingsboard.io/docs/user-guide/install/pe/cluster/docker-compose-setup/?ubuntuThingsboardQueue=kafka

**Screenshots**

![image](https://user-images.githubusercontent.com/78015483/140307580-0e57b3ef-8828-4f89-b6c5-e9778e293c3f.png)

![image](https://user-images.githubusercontent.com/78015483/140307621-c669bbfe-757a-4f66-b6f7-92eaa2134bc0.png)

**Additional context**

**Comment by ashvayka** [comment]
You have a license error 'Active Instance Capacity exceeded'. This means you have purchased a license for one (x) instance and trying to create 2(x+1) or more replicas.

**Comment by AbrahamSalvi** [comment]
I am only using it for this docker, how could I solve it?

**Comment by AbrahamSalvi** [comment]
I remove the instance from thingsboard 
![image](https://user-images.githubusercontent.com/78015483/140533867-4693cd22-5814-4895-931e-4b8efe7dde7f.png)

And you don't see the licensing error anymore, but the errors with kafka are still being seen.

![image](https://user-images.githubusercontent.com/78015483/140534497-39048cee-fb16-4adc-b85c-ce161a860ce9.png)

@ashvayka

**Comment by AlexDoanTB** [comment]
Hi @AbrahamSalvi ,

Please stop tbpe service / your container /
Remove instance-license.data file 
Clear instanceIDs on License portal 
Start tbpe container 
 
https://www.youtube.com/watch?v=2khu3RP0TGE

**Comment by AbrahamSalvi** [comment]
Hi @AlexDoanTB,
I have tried this but now I only get the kafka error.

Thanks for the reply!

**Comment by AlexDoanTB** [comment]
> Hi @AlexDoanTB, I have tried this but now I only get the kafka error.
> 
> Thanks for the reply!

Do you have AutoCreateTopics enabled?

**Comment by AbrahamSalvi** [comment]
Where i can check this?

**Comment by AbrahamSalvi** [comment]
Now I load TB and I can access !!

But errors keep appearing in the logs, and I don't know if that will affect

![image](https://user-images.githubusercontent.com/78015483/140739289-5de012fe-0f41-43a6-9ee1-eaa8fa25b45a.png)


ERRORS!

![image](https://user-images.githubusercontent.com/78015483/140739570-db4412cf-4b17-41b7-9e4d-792c028e7b59.png)
