### ISSUE TITLE
[Bug] Not valid working directory: /usr/share/thingsboard/bin.

### ISSUE THREAD

**Issue by WillNilges** [thingsboard/thingsboard#5497]
**Describe the bug**
On ThingsBoard 3.3.1 deployed on baremetal K8s, I get this popup error when trying to create a tenant:

```Not valid working directory: /usr/share/thingsboard/bin. Please use either root project directory, application module directory or specify valid "install.data_dir" ENV variable to avoid automatic data directory lookup!```

I checked the `tb-node-0` pod, and everything seems to be in place. This worked fine in the past, but now, suddenly, I get these issues. The only thing I can think of is file permissions for PV directories, and somehow MetalLB munging things (I just installed it). The former seems possible, but the latter doesn't. I'm going to spin up an older version of my cluster and see if I can reproduce it prior to that change.

**Your Server Environment**

ThingsBoard v3.3.1
Fedora Server 34
RKE (Kube v1.21)

**Your Client Environment**

Ubuntu Desktop 20.04 LTS
Firefox 93

**Your Device**
```
mosquitto_pub -d -q 1 -h 10.10.2.37 -p 1883 -t v1/devices/me/telemetry -u **************** -m {"ts": 1634762086277, "values": {"BMSBatteryTemp": "25.5"}}
```

**To Reproduce**
1. Log in as SysAdmin
2. Create Tenant
3. `Not valid working directory: /usr/share/thingsboard/bin. Please use either root project directory, application module directory or specify valid "install.data_dir" ENV variable to avoid automatic data directory lookup!`

**Expected behavior**
Tenant is created. No error reported.

**Comment by WillNilges** [comment]
I'm thinking this has something to do with networking (MetalLB?) solely due to the fact that if I try to burn down ThingsBoard and re-build it on the same node, I get these errors from `tb-db-setup`

```
2021-11-04 20:22:25,192 [Thingsboard Cluster-admin-1] WARN  c.d.o.d.i.c.c.ControlConnection - [Thingsboard
 Cluster] Error connecting to Node(endPoint=/127.0.0.1:9042, hostId=null, hashCode=76fa5726), trying next 
node (ConnectionInitException: [Thingsboard Cluster|control|connecting...] Protocol initialization request
, step 1 (OPTIONS): failed to send request (io.netty.channel.StacklessClosedChannelException))
```

**Comment by WillNilges** [comment]
I don't think it's MetalLB anymore. It could be something wacky with Calico networking on RKE. I tried creating a cluster that didn't use MetalLB, and got the same results.

**Comment by WillNilges** [comment]
Turned off dual-stack and it's still happening. Color me supremely confused. I'm gonna revert to my last known good configuration, from _scratch_, and see if it stops happening.

**Comment by WillNilges** [comment]
I've got ghosts. My previous config no longer works.

Well, good news! It's probably not networking. It's something else. Not a SCOOBY what, though.

**Comment by WillNilges** [comment]
For a sanity check, I tried a _completely stock_ version of thingsboard-ce-k8s. That aforementioned cassandra issue is still happening.

https://github.com/thingsboard/thingsboard-ce-k8s/issues/43

**Comment by WillNilges** [comment]
I've tracked this down to an issue in my customization of the configs, so it's safe to say that this issue was user error. The Cassandra issue seems to happen when I use Calico plugin on RKE. I switched to Canal and it disappeared (for now).

**Comment by jainy-james** [comment]
Hi,
I was also facing this same issue, and tried your way of solving it but in vain.
Is there any other way, I can fix this ?

**Comment by ahmedshehtaa** [comment]
> Hi, I was also facing this same issue, and tried your way of solving it but in vain. Is there any other way, I can fix this ?

https://blog.csdn.net/qq12547345/article/details/122688556 may help
