### ISSUE TITLE
Confusion on linking to AWS MQTT

### ISSUE THREAD

**Issue by mattb1969** [thingsboard/thingsboard#5507]
Hi, I am really struggling to link my own instance of ThingsBoard CE edition to my AWS IoT MQTT feed. No matter what documents I read, it still doesn’t make sense.

I _assumed_ that I could get ThingsBoard to subscribe to the topics in AWS IoT, but I must be missing something. When I refer to the documentation there is no explanation of what is required, at most just a list of commands to follow.

All I want to do is take the MQTT feed from AWS IoT and display the data on ThingsBoard that I have installed in a separate cloud platform.

Really struggling at present, feeling very deflated as no matter what I try and do, it is difficult.

**Comment by JacksonBowe** [comment]
For my mqtt subscriptions I use an Integration. Unfortunately these are only available in Professional Edition.

**Comment by mattb1969** [comment]
That’s what I fear.
Is there any other way?

**Comment by ashvayka** [comment]
You may develop your own (micro)service that will subscribe to the mqtt broker and publish data to ThingsBoard via [MQTT Gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/)
