### ISSUE TITLE
Installation Failed.

### ISSUE THREAD

**Issue by AtifJaved1** [thingsboard/thingsboard#551]
<img width="1279" alt="screen shot 2018-01-26 at 5 52 51 pm" src="https://user-images.githubusercontent.com/26598012/35440573-cb0a4dca-02c1-11e8-83b0-fe57fb7c52c3.png">
This is the error I have facing while installing a Thingsboard.io on Ubuntu Server. I have setuped JDK 9 for this.
<img width="528" alt="screen shot 2018-01-26 at 5 54 48 pm" src="https://user-images.githubusercontent.com/26598012/35440642-0cfe4f06-02c2-11e8-8d45-64a0d919917b.png">

**Comment by hanyuwenn** [comment]
use JDK1.8 and try it again

**Comment by mbari** [comment]
this is the error I am getting while trying to install 

peter@vps512215:~$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
ThingsBoard installation failed!
peter@vps512215:~$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by Firdauzfan** [comment]
Try to build from source with mvn clean install.

**Comment by mbari** [comment]
I found the problem. I had messed up the .yml file while configuring the database to use. Now it works

**Comment by destr1ke** [comment]
How not to spoil the file when editing?
