### ISSUE TITLE
[Question] White Labeling Css from Api

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#5517]
**Component**

 * UI

Hello... I want to ask about white labeling api. How can we set a css theme through the api and which one the api is?
so no need to set manually from url white-labeling/whiteLabel  
just fire the api like `/api/mycssString` and then css being updated 
![image](https://user-images.githubusercontent.com/12267053/140760698-1dcfd50c-ac1e-4736-bd86-fedf34314b39.png)

**Comment by ashvayka** [comment]
We have documented the API in 3.3.2. Please stay tuned. We plan to publish the updated packages tomorrow. For now, you can use our dev server swagger docs. 

To get the white-labeling CSS for login, use:
https://cloud.thingsboard.io/swagger-ui/#/white-labeling-controller/getLoginWhiteLabelParamsUsingGET See model of the output. "customCss" property.

To update the settings, use:
https://cloud.thingsboard.io/swagger-ui/#/white-labeling-controller/saveLoginWhiteLabelParamsUsingPOST
