### ISSUE TITLE
[Question] how to configure Kafka integration backed by Confluent Cloud

### ISSUE THREAD

**Issue by davetroiano** [thingsboard/thingsboard#5519]
**Component**

 * Generic

**Description**
I'm able to write data from ThingsBoard to Kafka (Confluent Cloud) by adding an "External - kafka" node to my rule chain and specifying the four required authentication params [here](https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#kafka-node), but the same config isn't working when I try to set up a Kafka integration to read data from Confluent Cloud. Is it supported? Is there [documentation](https://thingsboard.io/docs/user-guide/integrations/)?

**Environment**

 * OS:  macOS Catalina
 * ThingsBoard: ThingsBoard Cloud
 * Browser: Chrome 95.0.4638.69

**Comment by davetroiano** [comment]
I see this `FAILED` value for key `tb-core-0_state` but I don't see more detailed info on the failure:

![image](https://user-images.githubusercontent.com/4550245/140796921-b8425012-bbf4-4261-9e98-58038b845a61.png)

**Comment by AlexDoanTB** [comment]
Hi Dave,

Apparently, you are facing the issue with Kafka integration — HTTPS / PLAIN login method for Confluent Cloud. The fixed version is on the way.

**Comment by davetroiano** [comment]
Thank you, appreciate it!

**Comment by davetroiano** [comment]
Confirming that this is now fixed!
