### ISSUE TITLE
How to get the temprature automatic after reboot the Raspberry Pi with  DHT22 sensor

### ISSUE THREAD

**Issue by jackyZhangHZ** [thingsboard/thingsboard#552]
thingsboard is a such great IoT platform
we have used it for device , and now one question:

How to get the temprature automatic after reboot the Raspberry Pi with  DHT22 sensor.
Now i have to run the Python ｓcript manually first.

i know it may not a thingsboard question  ;-)
IF ANYONE CAN HELP, MANY MANY THANKS!

**Comment by ralienpp** [comment]
This is indeed not a Thingsboard question. I assume you are running the latest version of Raspbian, so you need to write a systemd service file. This guide will help you with this process, read it carefully, as it covers all you need to get it done: https://wiki.archlinux.org/index.php/systemd#Writing_unit_files.
