### ISSUE TITLE
[Question] Custom Menu parent without click redirect

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#5521]
**Component**

 * UI
 * Generic

Hello... I want to create menu with parent child, but what i want is the parent no need redirect to any url, so I just wanna click expand arrow icon then show child menu. Any way to do that? I click the icon only but still redirect  
![image](https://user-images.githubusercontent.com/12267053/140848304-083f809f-7fa0-4e51-b9d3-5d76faf77824.png)

**Comment by Kullpoint** [comment]
We need an answer!)

**Comment by vmlourenco** [comment]
We need an answer! (Im still here)

**Comment by ifelse-code** [comment]
also looking for this @ashvayka 

is there any way to do this?

**Comment by h-takado** [comment]
I have the same problem.
Can anyone give me a solution!

**Comment by myroslav-tb** [comment]
Hi @evanderbird, I have created a feature request for our prod team. Once they review it, we’ll post an update on when this feature could be delivered if they decide to add it to the product.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
Please follow up on the release notes to check if the feature is added to the Thingsboard.
