### ISSUE TITLE
Report of time series table for multiple devices

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5528]
I want to generate report of time series table for multiple devices. In ThingsBoard dashboard time series table, each device is in separate tab, and the exported report will only show the first tab. How to generate the report for all the devices in one action instead of switching to each tab and exporting one by one?

![2021-11-10 17_03_59-Window](https://user-images.githubusercontent.com/17080208/141083104-5c0e5940-5187-407d-a612-c94386bbd855.png)

**Comment by DavidHartnell** [comment]
Has there been any progress on this issue? Or any work-arounds?

**Comment by sunyong-mwi** [comment]
I checked ThingsBoard v3.6.4. This issue is fixed. Thank you.
