### ISSUE TITLE
The widget "Attributes Card" does not change the number of digits after floating points

### ISSUE THREAD

**Issue by podliponochka** [thingsboard/thingsboard#553]
The widget "Attributes Card" does not change the number of digits after floating points on release 1.3.1.

To recreate perform the following steps on the UI:

Devices --> latest telemetry --> select any floating point data item
show on widget --> Attributes card --> add to dashboard
Go to edit mode on the dashboard. Edit the Attributes card.
Change "Number of digits after floating point" to something >= 0
Click the check mark to OK changes. 
The result - Always 2 digits shows after the floating point.

**Comment by LeoMorgan113** [comment]
Hi @podliponochka,

I've added this issue to our backlog, so it will be reviewed by our developers as soon as possible.
Thanks for your participation.
Keep updating! 
https://thingsboard.io/docs/reference/releases/

**Comment by mubashirp** [comment]
still i am facing the same problem. ios there any method to resolve
