### ISSUE TITLE
Build from source issue | Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by Lollitoe** [thingsboard/thingsboard#5530]
OS Information
--
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

Maven version
--
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-90-generic", arch: "amd64", family: "unix"

Error
--
```
[INFO] Reactor Summary for Thingsboard HTTP Transport Service 3.3.2-SNAPSHOT:
[INFO]
[INFO] Thingsboard HTTP Transport Service ................. FAILURE [04:51 min]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard LwM2m Transport Service ................ SKIPPED
[INFO] Thingsboard SNMP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:26 min
[INFO] Finished at: 2021-11-10T10:36:56Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project http: Could not resolve dependencies for project org.thingsboard.transport:http:jar:3.3.2-SNAPSHOT: The following artifacts could not be resolved: org.thingsboard.common.transport:http:jar:3.3.2-SNAPSHOT, org.thingsboard.common:queue:jar:3.3.2-SNAPSHOT: Could not find artifact org.thingsboard.common.transport:http:jar:3.3.2-SNAPSHOT in central (https://repo1.maven.org/maven2/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by ashvayka** [comment]
Please specify the command that you execute to get this output?

**Comment by Lollitoe** [comment]
sudo mvn clean install -rf org.thingsboard.transport:http -DskipTests

**Comment by ashvayka** [comment]
Why do you use "-rf org.thingsboard.transport:http"? When you do this, the previous packages are not getting built.

**Comment by Lollitoe** [comment]
i innitially just used sudo mvn clean install -DskipTests, but it failed at [INFO] Thingsboard HTTP Transport Service, it said at the bottom to run mvn <arg> -rf org.thingsboard.transport:http

**Comment by Lollitoe** [comment]
any suggestions to succesfully compile this release from source?

**Comment by Lollitoe** [comment]
Re-Ran it from scratch after reinstalling everything. please see below

`[INFO] Reactor Summary for Thingsboard 3.3.2:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.135 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  5.677 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.250 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 13.558 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  1.609 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.305 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  1.950 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.665 s]
[INFO] Thingsboard Server Common Cluster API .............. SUCCESS [ 19.623 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  6.499 s]
[INFO] Thingsboard Server Common Cache .................... SUCCESS [  1.592 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.115 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.222 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  3.014 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.120 s]
[INFO] Thingsboard CoAP server ............................ SUCCESS [  1.205 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  2.556 s]
[INFO] Thingsboard LwM2M Transport Common ................. SUCCESS [  5.121 s]
[INFO] Thingsboard SNMP Transport Common .................. SUCCESS [  2.164 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  2.318 s]
[INFO] Thingsboard Server Remote Edge wrapper ............. SUCCESS [  8.576 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.080 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.989 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 24.028 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [01:02 min]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.056 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [03:33 min]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 23.545 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 22.222 s]
[INFO] Thingsboard LwM2m Transport Service ................ SUCCESS [ 22.821 s]
[INFO] Thingsboard SNMP Transport Service ................. SUCCESS [ 21.908 s]
[INFO] ThingsBoard Server UI .............................. FAILURE [06:10 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:13 min
[INFO] Finished at: 2021-11-12T09:23:34Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn build) on project ui-ngx: Failed to run task: 'yarn run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 134 (Exit value: 134) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ui-ngx`

**Comment by ArunjitSanasam** [comment]
I am having the same issue, failure at ThingsBoard Server UI. Have you already solved the issue? I am building on Ubuntu 20.04.3 LT having the same maven version as you while running mvn clean install -DskipTests command

**Comment by Lollitoe** [comment]
> I am having the same issue, failure at ThingsBoard Server UI. Have you already solved the issue? I am building on Ubuntu 20.04.3 LT having the same maven version as you while running mvn clean install -DskipTests command

Nothing as of yet

**Comment by maxwmsilva** [comment]
For ThingsBoard Server UI .............................. FAILURE
Try.....
add the command on file  .pom.xml
folder: 
thingsboard-3.3.2\ui-ngx\pom.xml

in line 98 after  <arguments>run build:prod</arguments>

you can add the command 
 <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>

and save.

repeat the build with the command  "mvn clean install -DskipTests"

**Comment by Lollitoe** [comment]
Worked for me cause now I got build success
