### ISSUE TITLE
[Question] How can I connect AWS s3?

### ISSUE THREAD

**Issue by jsjang-rtdata** [thingsboard/thingsboard#5535]
**Component**

 * Generic

**Description**
I want to display files(image, text, etc.) in AWS S3 on the dashboard. 

But I don't know how.

Please advise on how to connect.

**Environment**

 * ThingsBoard: PE v3.2.1

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket.
