### ISSUE TITLE
[Bug] In time series chart widget, ${entityLabel} does not work for the chart title

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5538]
In time series chart widget, the ${entityLabel} works in the legend, but does not work for the chart title.

![2021-11-11 16_59_11-Window](https://user-images.githubusercontent.com/17080208/141268855-440b8fdb-d65b-4695-8b62-826148d1b108.png)

**Comment by JacksonBowe** [comment]
Could you test by using `${entityName}`?

If that works then the problem is that you're not passing `entityLabel` into this dashboard state.

**Comment by sunyong-mwi** [comment]
The result is the same for entity name

![image](https://user-images.githubusercontent.com/17080208/141392832-70dc001b-3076-4d80-836c-36140e0227ce.png)

**Comment by JacksonBowe** [comment]
Looks like this widget may not support using state entities in the title. Not sure how to get that working.

**Comment by ssakharova** [comment]
Hello @sunyong-mwi,

In the latest versions of the ThingsBoard, this ability to display `${entityLabel}` and `${entityName}` as a chart title is supported. Therefore, we recommend that you upgrade to the latest version.
