### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by Kernelalive** [thingsboard/thingsboard#5539]
**Component**
Thingsboard-gateway , TB-PE

 * Generic

**Description**
Hello!,
I have a TB-PE connected with a TB-Gw and through mqtt i receive messages like the following: 
`mosquitto_pub` -d -q 1 -h localhost -p "1883" -t "/sensor/data" -u "*********" -m '{"unit": "%", "description": "state of charge", "status": 0, "value": null, "device_name": "victron", "timestamp": "2021-09-14T06:32:07.507569+00:00", "sensor_type": "state_of_charge", "scalefactor": 1.0, "smart_device": `"RPi001"}'`

My question is how can i get this timestamp field correctly in order for tb to be able to understand it and sort it  ?
Just to say i use  the default converter of TB-GW (see mqtt.json below) 

**Mqtt Json**
{
  "broker": {
    "name":"Default Local Broker",
    "host":"127.0.0.1",
    "port":1883,
    "clientId": "ThingsBoard_gateway",
    "security": {
      "type": "basic",
      "username": "username",
      "password": "password"
    }
  },
  "mapping": [
    {
      "topicFilter": "/sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${serialNumber}",
        "deviceTypeJsonExpression": "${sensorType}",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          },
          {
            "type": "string",
            "key": "${sensorModel}",
            "value": "on"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temperature}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "/sensor/+/data",
      "converter": {
        "type": "json",
        "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/data)",
        "deviceTypeTopicExpression": "Thermometer",
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "/custom/sensors/+",
      "converter": {
        "type": "custom",
        "extension": "CustomMqttUplinkConverter",
        "extension-config": {
            "temperatureBytes" : 2,
            "humidityBytes" :  2,
            "batteryLevelBytes" : 1
        }
      }
    }
  ],
  "connectRequests": [
    {
      "topicFilter": "sensor/connect",
      "deviceNameJsonExpression": "${SerialNumber}"
    },
    {
      "topicFilter": "sensor/+/connect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/connect)"
    }
  ],
  "disconnectRequests": [
    {
      "topicFilter": "sensor/disconnect",
      "deviceNameJsonExpression": "${SerialNumber}"
    },
    {
      "topicFilter": "sensor/+/disconnect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/disconnect)"
    }
  ],
  "attributeUpdates": [
    {
      "deviceNameFilter": "SmartMeter.*",
      "attributeFilter": "uploadFrequency",
      "topicExpression": "sensor/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "echo",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
      "responseTimeout": 10000,
      "valueExpression": "${params}"
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "valueExpression": "${params}"
    }
  ]
}
**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: latest TB-PE 
 * ThingsBoard Gateway : 2.9
 * Browser: firefox

**Comment by JacksonBowe** [comment]
If I understand your question, you want to convert `2021-09-14T06:32:07.507569+00:00` into the equivalent unix timestamp, eg `1631601127507`

If so can't you just use JavaScript? 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse 

If you message gets fed into your rule chain do it in a script node and override the value of `metadata.ts`

**Comment by Kernelalive** [comment]
Hi @JacksonBowe ,
thank you for the reply.
How can i do  that ? creating a converter and  an integration for a specific device or is there any other way?
Also I have a TB-GW connected to TB. Is it possible to do that timestamp conversion  in the mqtt.json of TB-GW?  
Thank you in advance

**Comment by JacksonBowe** [comment]
@Kernelalive 
I've not used TB Gateways before so I'm not sure on how they work. How is this set up?
What I've done for my MQTT connections is use an Integration + Data Converter. This lets me use the same input route for all my MQTT devices from different venders. Based on my experience I'd recommend that approach.

**Comment by Kernelalive** [comment]
@JacksonBowe 
thanks for the reply . I will try the way you propose.
Thanks
