### ISSUE TITLE
<IDEA> dashboards, devices and its permissions

### ISSUE THREAD

**Issue by piotrlinski** [thingsboard/thingsboard#554]
Hi

At this moment permission mechanism for dashboards and devices works as follows:
- assign/create devices and dashboards to a customer
- assign/create users to a customer

having such a configuration in place, all users for a given customer are allowed to see all dashboards assigned to a customer. What if within the same customer there are users which should no have access to the same dashboard?

What do you think about the idea of extending permission in the way so it would be possible to control devices/dashboards/(maybe even telemetry parameters) on user level??

**Comment by jondoig** [comment]
I'd like to make some devices and dashboards on [our Thingsboard](https://citysensors.be.unsw.edu.au) public so anyone can discover them, access telemetry data from the devices and view the dashboards. The public home page should show these publicly available devices and dashboards, like you see on our [Geonode site](https://citydata.be.unsw.edu.au).

Also a device or dashboard owner should be able to choose which users can access it.

Role-based security like the [Django access control](https://docs.djangoproject.com/en/2.0/topics/auth/) model (used by Geonode) would be perfect:  
* Users create and own resources (e.g. devices, dashboards)
* Users may be members of groups (like Thingsboard's "Customers")
* Resource owners may assign permissions (e.g. read, write) on resources
* To make a resource public, the owner grants permissions on it to the AnonymousUser, a special user with no login

**Comment by PopoTheSapien** [comment]
In this vein, it would also be cool if the email (user) can belong to two different customers.  Upon logging in, they get to select which customer they are logging on behalf of.   I have two different vertical apps that i would like the same user (email) to register for.

Is there a workaround for this that I have not thought of?

**Comment by ban2derlog** [comment]
advanced RBAC is part of basic functional of ThingsBoard PE and this won't be added in CE.
