### ISSUE TITLE
There is a vulnerability in  Eclipse Californium 2.6.1,upgrade recommended 

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [thingsboard/thingsboard#5547]
https://github.com/thingsboard/thingsboard/blob/f2974532c607ea239aff63bf0885628496f13bd4/pom.xml#L57

Recommended upgrade version：

**Comment by mykhailokornieiev** [comment]
Hi QiAnXinCodeSafe
For now we have no information about issues with caffeine.version>2.6.1. Can you please clarify what vulnerabilities do you mean? After it we will add it to our backlog and our dev team will consider it. 
Best regards,
Mykhailo Kornieiev,
TechOps Engineer at Thingsboard

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
