### ISSUE TITLE
How to explore data from OPC-UA devices?

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#555]
Hello everyone,

      I met a problem in my exploration, The opc-ua server can connection successful, But cannot read tag value in devices.

This is OPC-UA mapping config:
![opc-ua config](https://user-images.githubusercontent.com/28647391/35667227-cec15ecc-0767-11e8-83b3-5e00db2a7342.png)

This is KEPServerEX 6.4  node config:
![kepserverex](https://user-images.githubusercontent.com/28647391/35667074-3d9508fe-0767-11e8-813f-953a84df4cb3.png)

Please help me check where is a problem.
Thank!

**Comment by BIT-masterpy** [comment]
Have you solved the problem?

**Comment by mp-loki** [comment]
Can you please tell us which version of TB Gateway are you using?

**Comment by Karabiy** [comment]
Have you tried the ThingsBoard Professional Edition OPC-UA integration feature?
You may refer to this link regarding those: https://thingsboard.io/docs/user-guide/integrations/opc-ua/
Also, the new ThingsBoard Gateway does support the OPC-UA integration, it is available both for Professional and for the Community Edition: https://thingsboard.io/docs/iot-gateway/config/opc-ua/
