### ISSUE TITLE
[Question] I cannot assign multiples customers to the same device

### ISSUE THREAD

**Issue by pnavazzotti** [thingsboard/thingsboard#5551]
Hi,

I have a centralized device that contains multiple telemetry keys. I want to associate this device to multiple customers so I can create dashboards for each one of them.

I tried to assign the "public" client to the device as I understand that this would allow all clients to have access to the device, but it didn't work.

Any suggestions?

Thanks

-------------------------------------------------------------------------------------------------

I am using Thingsboard 3.2.2

**Comment by ssakharova** [comment]
Hello @pnavazzotti,

If you are using Thingsboard CE, consider using Entity Views. 
If you are using Thingsboard PE, you can share the device with multiple customers.
