### ISSUE TITLE
[Question] How do I enable Two-Factor Authentication (2FA)?

### ISSUE THREAD

**Issue by technorabilia** [thingsboard/thingsboard#5559]
**Component**

 * Installation
 * Generic

**Description**

How do I enable Two-Factor Authentication (2FA)?

What are the possibilities for MFA or 2FA?

Two-factor authentication (2FA), sometimes referred to as two-step verification or dual-factor authentication, is a security process in which users provide two different authentication factors to verify themselves. 2FA is implemented to better protect both a user's credentials and the resources the user can access.

**Environment**

 * ThingsBoard PE

**Comment by technorabilia** [comment]
Duplicate of #3732

I really could use some input on how to implement this.

**Comment by Ultrazombie** [comment]
Please following these instructions:
https://thingsboard.io/docs/user-guide/two-factor-authentication/
