### ISSUE TITLE
My plugin needs relations information of device to process.

### ISSUE THREAD

**Issue by cityant** [thingsboard/thingsboard#556]
Hi @ashvayka, is it reasonable to have relations information in plugin API (DeviceMetaData.java) which plugins can access to process? The implementing path can be:
1. Fetch relations from dao to DeviceMetaData in DeviceActorMessageProcessor.
2. EntityRelationController posts relation updates message to device actor / DeviceActorMessageProcessor to refresh relations metadata.

Could you please enlighten that if the approach is reasonable. If positive, we will implement this and make a pull request. Thanks!

**Comment by vparomskiy** [comment]
Not actual anymore because plugins were removed in ThingsBoard v2.0
Closing
