### ISSUE TITLE
Multiple alarms of same type for same device

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5561]
Whenever a device triggers an alarm of some type, say "high temperature", the alarm needs to be cleared, before a new "high temperature" alarm can be created. If the previous alarm is not cleared, it us simply updated.
It does not matter whether the alarm was created by the "createAlarm" rule-chain node or the rest api.

As an example, take the following message-payload:

```
{
  "status": "ACTIVE_UNACK",
  "ackTs": 0,
  "clearTs": 0,
  "details": {
    "Temp": 100.0
  },
  "type": "high temp",
	 "originator": {
   "entityType": "DEVICE",
   "id": "b427e9c0-25ac-11ec-bde5-63c1a7e5914f"
  },
	"severity": "CRITICAL"
}
```

Send this payload as a POST-request to the endpoint "/api/alarm".

The response will look something like:

```
{
  "tenantId": {
    "entityType": "TENANT",
    "id": "207d8760-fa74-11eb-af75-038d007dac7c"
  },
  "customerId": {
    "entityType": "CUSTOMER",
    "id": "9dac2530-25ac-11ec-bde5-63c1a7e5914f"
  },
  "type": "high temp",
  "originator": {
    "entityType": "DEVICE",
    "id": "b427e9c0-25ac-11ec-bde5-63c1a7e5914f"
  },
  "severity": "CRITICAL",
  "status": "ACTIVE_UNACK",
  "startTs": 1636995244097,
  "endTs": 1636995244097,
  "ackTs": 1636994788308,
  "clearTs": 1636994788308,
  "details": {
    "Temp": 100.0
  },
  "propagate": false,
  "propagateRelationTypes": [],
  "id": {
    "entityType": "ALARM",
    "id": "a3bd5220-4634-11ec-b660-810f721d3f60"
  },
  "createdTime": 1636995244098,
  "name": "high temp"
}
```

Then I try to save a new alarm with the following payload:

```
{
  "status": "ACTIVE_UNACK",
  "ackTs": 0,
  "clearTs": 0,
  "details": {
    "Temp": 105.0
  },
  "type": "high temp",
	 "originator": {
   "entityType": "DEVICE",
   "id": "b427e9c0-25ac-11ec-bde5-63c1a7e5914f"
  },
	"severity": "CRITICAL"
}
```

As a result, the previous alarm-entity is updated. The details-object, as well aus endTs is updated. 
This is not what we want.
We need thingsboard to be able to record multiple "high temp" alarms with the status "ACTIVE_UNACK".
The only workaround I have found is clearing a newly created alarm immediately after it was created.
Apparently it is possible to have multiple alarms of the status "CLEARED_UNACK"

Is there some workaround to have multiple unacknowledged alarms of the same type for the same device?

**Comment by Goran-59** [comment]
I ran into the same problem. Although, i found that on some thread from 2019 someone had the same problem. Unfortunately, developers were working on it then.  So @ashvayka , have you solved fetching alarms from multiple devices simultaneously?

**Comment by mykhailokornieiev** [comment]
Hi. Such kind of functionality is not possible due to design of Thingsboard. A new alarm can be created only after clearing the previous one. That is why, in this case, another logic will not be implemented.
