### ISSUE TITLE
[Feature Request] Protobuf Support for Kafka Integrations/Data Converter

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#5565]
**Is your feature request related to a problem? Please describe.**
In a current project we use the Sparkplug specification for structuring device & gateway payloads.
We send the data to a Confluent Kafka Cluster and connect ThingsBoard via Kafka Integration/ Data Converters.
Currently the Data Converters don't support protobuf, so we have to convert to JSON beforehand.

**Describe the solution you'd like**
Direct Support of protobuf in Data Converters without relying on any other external service. 

**Describe alternatives you've considered**
In the current solution we have to provide a Protobuf to JSON Converter via Kafka Streams Microservices.

**Additional context**
https://developers.google.com/protocol-buffers/
https://sparkplug.eclipse.org/
https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf

**Comment by ashvayka** [comment]
Sparkplug is now officially supported starting version 3.5: https://thingsboard.io/docs/reference/mqtt-sparkplug-api/

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
