### ISSUE TITLE
OPC UA integration does not automatically reconnect to OPC UA server

### ISSUE THREAD

**Issue by ts4iot** [thingsboard/thingsboard#5568]
The OPC UA integration is configured as described in the following link: 
[https://thingsboard.io/docs/user-guide/integrations/opc-ua/](url)

The integration works in general with the following limitations described in issue: [https://github.com/thingsboard/thingsboard/issues/5532](url).

After a restart of the OPC UA server, the OPC UA integration does not automatically reconnect to the OPC UA server. The only way to reconnect is to disable and enable the OPC integration.

Description of the Server Environment
own setup
local infrastructure with docker deployment (single node with docker compose)
ThingsBoard Version (3.3.1PE)

Description of the Client Environment
OS: Windows 10
Browser Firefox Portable
Version 86.0

Connectivity
OPC UA integration
No Gateway

**To Reproduce**
1. Configure OPC UA integration
2. Enable OPC UA integration
3. Show data capturing in dashboard
4. Restart OPC UA server

**Expected behavior**
The OPC UA integration should automatically reconnect after some seconds to the OPC UA server

**Additional context**
After disabling/enabling of the OPC integration the data capturing runs again.

**Comment by ban2derlog** [comment]
hi, please update your service to newer version.
in 3.4.1 - there where added a bunch on updates for OPC UA Integration:
https://thingsboard.io/docs/pe/reference/releases/#v341-august-18-2022
