### ISSUE TITLE
[Bug] TB 3.3.2: Error reading private key from PEM certs on boot

### ISSUE THREAD

**Issue by robertoenr** [thingsboard/thingsboard#5570]
I'm trying to configure the MQTT with SSL in my tests and I've followed this guide https://thingsboard.io/docs/paas/user-guide/mqtt-over-ssl/ using the "SSL configuration using PEM certificates file" and "PEM certificate file" sections. 

After this I've copied the generated files "server.pem" and "server_key.pem" to the mytb-config directory which is mapped to a volume inside the docker container to /config directory, defined in the docker-compose.yml. Also, on the docker-compose I've added the variables described:

```
MQTT_SSL_ENABLED: "true"
MQTT_SSL_CREDENTIALS_TYPE: PEM
MQTT_SSL_PEM_CERT: server.pem
MQTT_SSL_PEM_KEY: server_key.pem
MQTT_SSL_PEM_KEY_PASSWORD: password
```

Also on the mytb-config directory I've ensure the permissions with "sudo chown -R 799:799 .".

When I compose and run the container with docker up -d, I've checked that it throws this exception:

**"Unable to load private key neither from certFile: server.pem nor from keyFile: server_key.pem"**

...and the whole container reboots again and again. Thingsboard never boots up.

I've tried to execute the openssl command with the flag -nodes in order to avoid the password protect of private key. This way the system print outs some errors about SSL on boot, but it boots up. 

Also I've tried enter the container with console, and check that the /config dir has the expected files, and the files are there ok...

Could be this a bug? Maybe I'm doing something wrong?

Thanks!

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version 3.3.2
  * Ubuntu 20.04 LTS

**Comment by jiangb** [comment]
try:

MQTT_SSL_PEM_CERT: /config/server.pem
MQTT_SSL_PEM_KEY: /config/server_key.pem
