### ISSUE TITLE
Problems ESP32S2 with Arduino to send MQTT telemetry over to ThingsBoard

### ISSUE THREAD

**Issue by snappercayt** [thingsboard/thingsboard#5571]
**Component**

 * Generic

**Description**
I tried to test the [DHT22 Example for Pico](https://thingsboard.io/docs/samples/esp32/gpio-control-pico-kit-dht22-sensor/) on my ESP32S2 but it was easier said than done, I followed the Getting Started as given [here](https://thingsboard.io/docs/getting-started-guides/helloworld/?connectdevice=mqtt-windows) on a trial account, provisioned a device, obtained token with MQTT, tested MQTT feature on [MQTTBox](https://chrome.google.com/webstore/detail/mqttbox/kaajoficamnjijhkeomgfljpicifbkaf) so I was sure my device can be connected. Added a simple dashboard with table to check the JSON data can be viewed.

My problem start after testing my ESP32S2 for blink LED example, I copy the DHT22 sample and install required libraries but I get don't get anything after `Connected to AP` it keeps looping and I don't get any response on the dashboard or data like I did from my browser

So I am stuck. How do I use the Arduino sample on ESP32S2? Is there a better example? do I have to add something extra or remove some code to work on ESP32S2? I hope you guys can help as I am new with RPC so it will take time for me to write on my own, still going through documentation so other way I found is flashing the OTA firmware given [here](https://github.com/thingsboard/esp32-ota) but I am not capable yet for that option...

**Environment**

 * OS:  Windows 7
 * ThingsBoard: 3 
 * Browser: Chrome 95

**Comment by merculy** [comment]
what the fake

**Comment by snappercayt** [comment]
I have been reading about ESP32-S2 board and it does timers differently, will update

**Comment by Ultrazombie** [comment]
Closed due to inactivity
