### ISSUE TITLE
[Question] problem with reset password

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5581]
**Component**

 * Generic

**Description**
I have a problem when I want to send a reset password. I get this error.

` [http-nio-0.0.0.0-8080-exec-7] WARN  o.t.server.controller.AuthController - Error occurred: You don't have permission to perform 'WRITE' operation with 'PROFILE' resource!`

Can anybody point me towards what right is missing? When creating a new user the mail works fine.

**Environment**

 * OS:  docker 
 * ThingsBoard: 3.3.2PE
 * Browser: Edge

**Comment by JacksonBowe** [comment]
Check your roles. What role is assigned to the account you are trying to use here. Does it have permission ``` Profile: All ```.

**Comment by tobbelin** [comment]
This is a standard tenant user account, autogenerated roles. It has Profile:All, All: Read.
Is the reset of password depending on the user roles?

Best
Tobias

**Comment by tobbelin** [comment]
Is there nobody else with this problem? Any tips on how to debug this further from our side?

**Comment by JacksonBowe** [comment]
Clarify something for me quickly. Are you on an account A (with role tenant user), and trying to send a password reset to an account B?

**Comment by tobbelin** [comment]
I created a new user to test this. Set it up as a normal user.
Then in incognito mode trying to log in as that user, pressing reset password.
Then I get this logmessage on the server and no mail goes out to the user.

**Comment by JacksonBowe** [comment]
Have you logged in at least once successfully before trying to reset password?

**Comment by tobbelin** [comment]
All users I have tried has the same problem though.  Same for a tenant admin user.

**Comment by tobbelin** [comment]
Not on the test user I created. But the user noticing the problem had.
And I did not find a quick solution for that other than recreating that user so that they could reactivate, those mails actually works.

**Comment by JacksonBowe** [comment]
I just created a tenant user, logged in, logged out, clicked forgot password, entered the email address for the account, and then received the password reset in my inbox.

This was on TB3.1.1 PE

**Comment by tobbelin** [comment]
On my test user I had accidentally not added it to a group. (sorry!) Not sure how I missed that.
Now my test user actually gets mail.
Tomorrow will test with a user that had the problems before. That user is in the tenant admin group and has always been.
So the group problem was only with my test account.
I have updated TB since I hade to recreate the user, so maybe it just works now. 🤞

**Comment by tobbelin** [comment]
I think the problem is that the emails are case sensitive. And the user was created with big first letter.
Is this by design or a bug? I would not want that behavior.

**Comment by tobbelin** [comment]
My bad, that was a setting missing.
