### ISSUE TITLE
[Question] Color of map widget cluster

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5582]
**Component**

 * Generic

**Description**
I want the cluster to have red color if any of the pins in the cluster is red. To easily find problematic machines on the map overview. Is this possible?

**Comment by jfrancoVicomtech** [comment]
I also would to know if it is possible.

**Comment by ssakharova** [comment]
Hello @tobbelin and @jfrancoVicomtech,

Yes, it is possible.
In the latest versions, you need to go to the Appearance tab of the widget and find Markers clustering settings. 
Here is a Clustering markers setting where you can programmatically configure the Marker color function. 

Please see the screenshot:
![image](https://github.com/thingsboard/thingsboard/assets/98035385/674752d8-58ce-49fe-a7c4-b923003529cf)
You can use the question mark button to find more information and examples.
