### ISSUE TITLE
How can i publish telemetry to other device without acess token

### ISSUE THREAD

**Issue by Pankaj9410557422** [thingsboard/thingsboard#5586]
my scenario is like i am having say 3 devices which in which the telemetry is being published an i have multiple devices which are related to these devices (i can have multiple relation with the above three devices with these devices). The issue is if i am using change originator node to publish the telemetry to these devices it is actually publishing the telemetry to only the first related device. 
How can i acheive publishing telemetry to these related devices.
Please provide me a solution to this scenario or other approach i can apply to  pulish telemetry.

**Comment by ashvayka** [comment]
If your 3 devices use MQTT, then you may use MQTT [Gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/). But make sure that the devices are marked with "Is Gateway" checkbox in device details.
