### ISSUE TITLE
[Question] Adding  dom element to Thingsboard Time series chart

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5587]
**Component**
I want to edit the time series graphic and show the device selected via the combo box that I want to add and the telemetry co2 o2 data that I want to show connected to it dynamically in the graphic. But I add a combo box with chart js to the time-series chart, but I'm having a problem with the display. Can you help me, please?

I want to add the combo box filtering part I sent in the attachment on the time series chart container.
![Selection_002](https://user-images.githubusercontent.com/91528436/142585077-67df470f-922e-4997-9d47-8642dd219b71.png)
![Selection_001](https://user-images.githubusercontent.com/91528436/142585085-343c2be0-ed54-4f2c-9ff3-ad443d3b1ba4.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
