### ISSUE TITLE
TLS: two way ssl without private key? is something wrong?

### ISSUE THREAD

**Issue by liaoweiguo** [thingsboard/thingsboard#559]
For MQTT TLS config, the python tools code tls_set only ca and certificate, NO private key, why?

in tools/src/main/python/two-way-ssl-mqtt-client.py

client.tls_set(ca_certs="mqttserver.pub.pem", certfile="mqttclient.nopass.pem", keyfile=None, cert_reqs=ssl.CERT_REQUIRED,
                       tls_version=ssl.PROTOCOL_TLSv1, ciphers=None);

client.tls_insecure_set(False)

As I understand, one way SSL you provide a CA certificate, for two way ssl, you should provide ca, client certificate AND private key. For RSA certificate/publickey without private key means NOTHING

**Comment by ashvayka** [comment]
@mp-loki please help when you will have time.

**Comment by sad00731** [comment]
the mqttclient.nopass.pem already contains the client private key

**Comment by Ultrazombie** [comment]
Hello @liaoweiguo
Did your problem still relevant?
