### ISSUE TITLE
[Feature Request] Post-processor module or post processing function that supports multiple data sources

### ISSUE THREAD

**Issue by garageeks** [thingsboard/thingsboard#5591]
**Is your feature request related to a problem? Please describe.**
I'm using TB to store values from solar power generators and remotely monitor them. I have been storing voltage and current values.
Now I would like to show in the dashboard the power over time. It is a simple math operation: power = voltage * current (Good old Ohm's law). I expected to do this in the data post-processing function of the time-series widget, but according to TB help desk this is not supported. I have 3.2PE version.

![post-processing](https://user-images.githubusercontent.com/15252836/142662774-16aaed40-00ca-4cd2-92cc-e07800ef6249.JPG)

**Describe the solution you'd like**
The best feature would be a post-processor module that can generate new values according to a formula applied to existing data.
An example of this feature is in Emoncms https://guide.openenergymonitor.org/emoncms/postprocess/

Alternatively, an easier approach would be a data post-processing function that is able to access to multiple data sources and is able to do simple math operations with the values. In this case the result of the post-processing function is calculated on-the-fly and displayed in the time-series widget but not stored anywhere.

**Describe alternatives you've considered**
I could set up a rule chain to pre-compute "power", but this has two issues:
- it adds yet another data point on an already ballooning database due to lots of pre-computed values
- it doesn't work with existing data

**Additional context**
The requirement of TB to pre-calculate everything with the rule engine and store the results makes it inflexible and leads to enormous databases.
I understand the reasoning of pre-calculating to obtain faster populating dashboards, however my database is already over 100GB in less than a year and there are only 30 devices connected to this instance. 
Additionally, project requirements are varying over time, so it would be very useful to have a post-processing tool or at least a more powerful time-series widget.

**Comment by mykhailokornieiev** [comment]
Hi. 
Such a feature won't be implemented due to the design of Thingsboard. The only possible solution is to use Rule Chains.
In this case, I close this ticket.
