### ISSUE TITLE
[Bug] Unable to save asset with type TbServiceQueue

### ISSUE THREAD

**Issue by samleegit** [thingsboard/thingsboard#5592]
**Describe the bug**

**Your Server Environment**

* own setup
  * MySelf developer environment, idea，jdk11.0.13
  * ThingsBoard Version: CE 3.3.1 and 3.3.2
  * OS Name and Version: Windows10

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows10
* Browser :chrome
* Version: 96.0.4664.45（64 Bit）

**To Reproduce**
1. Go to 'assets'
2. Click on '+'，create assets
3. choose 'TbServiceQueue' type
4. See error: Unable to save asset with type TbServiceQueue

**Expected behavior**
Assets created success.

**Screenshots**
![image](https://user-images.githubusercontent.com/4971842/142713332-69a94cef-94f8-4ab3-861f-9f8ab07c8933.png)
![image](https://user-images.githubusercontent.com/4971842/142713345-c35f9ce1-6b60-4a50-8062-8036de4e9a08.png)
![image](https://user-images.githubusercontent.com/4971842/142713365-df9a5603-c369-41d9-a6f3-1e520e64542a.png)
![image](https://user-images.githubusercontent.com/4971842/142713374-a3768d55-d917-4755-b3a2-d6d66a75d847.png)

**Additional context**

**Comment by sanshengshui** [comment]
When creating an asset, the type "TbServiceQueue" is not supported
![image](https://user-images.githubusercontent.com/23117382/143600905-b939886d-51ea-457d-a873-b9f9ff707363.png)

**Comment by ashvayka** [comment]
This is not a bug. "TbServiceQueue" is a reserved asset type that stores Rule Engine stats. It will be removed in future releases since we plan to move rule engine queues to separate thingsboard entities with their own entity type (QUEUE).

**Comment by greg-mcnamara** [comment]
Thanks @ashvayka that makes sense. So, how do you add an asset type? I can't see it on my Tenant Admin menus (Thingsboard PE self-hosted).

**Comment by hallard** [comment]
BTW any chance to hide these system assets, it confuse customers and also don't wan't to take the risk of deletion by customer?

**Comment by zxz666** [comment]
@robinwesterik hi,can you tell me details how to manually typing in an asset type in the text box?
