### ISSUE TITLE
[Bug] Incorrect Symbol Shown on Legend

### ISSUE THREAD

**Issue by seikosantana** [thingsboard/thingsboard#5594]
**Describe the bug**
As the title says, the symbol set in datasource in Timeseries - flot is not showing the assigned symbol. In a chart with 3 datasources, with each one has its own symbol (unit) for the telemetry, it shows symbol of another datasource instead of what's assigned to it.

**Your Server Environment**

* own setup
  * Local infrastructure with Raspberry Pi 4
  * ThingsBoard Version: 3.1.1
  * Ubuntu Server 18.04 ARM64

**Your Client Environment**

**Desktop**

* OS: Windows 10 21H1
* Browser: Microsoft Edge 
* Version  95.0.1020.53

**Your Device**

* Connectivity
  * MQTT
* Device vendor and model: Custom device

**To Reproduce**
1. Create a new timeseries flot
2. Add 3 datasources
3. Assign different symbols to each datasource
4. See error (the legends aren't showing the correct symbol)

**Expected behavior**
Legends should be showing the symbol assigned

**Screenshots**
![image](https://user-images.githubusercontent.com/35630407/142714257-3b5d7384-0513-4100-b972-b09923872d6a.png)
![image](https://user-images.githubusercontent.com/35630407/142714263-5c8314f1-0e88-4e2e-8a1a-45d9fde64018.png)
![image](https://user-images.githubusercontent.com/35630407/142714270-79f47534-5d31-46b6-ae6b-2b9508fe4042.png)
![image](https://user-images.githubusercontent.com/35630407/142714276-a8918918-bba8-47f3-9c5f-d8d3c0159a45.png)

Those screenshots above show what symbols are assigned to each datasource.

![image](https://user-images.githubusercontent.com/35630407/142714298-97a08440-046d-4749-9021-ce8de11257c1.png)

As shown on the last image, EMC has the °C symbol, while temp has %EMC shown next to the average.

**Additional context**
Tests was performed on Timeseries - Flot widget

**Comment by ChantsovaEkaterina** [comment]
Hello, @seikosantana 
The issue described was fixed in TB v.3.2. 
I would recommend you update your Thingsboard instance to get the improvements and bug fixes added in recent versions.
The latest version released is 3.3.2.

**Comment by seikosantana** [comment]
Thanks, I did the upgrade, and now i have encountered problems after upgrading.
