### ISSUE TITLE
[Question][Bug?] Map Clustering changed from 3.1.1 -> 3.3.x

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5597]
I've noticed that after upgrading from v3.1.1 to v3.3.1 (and then 3.3.2) that map marker clustering is behaving differently. When two markers are at a near identical position i v3.1.1 clicking the cluster would "balloon" out the markers however in v3.3.x it becomes impossible to see the location of a marker if it's at very similar coords to another. See gifs below

3.1.1 behaviour

https://user-images.githubusercontent.com/26427343/142784764-c14d8fec-90ad-4380-b632-9071fabd377f.mp4

3.3.x behaviour

https://user-images.githubusercontent.com/26427343/142784880-05a2b8e7-48c5-4bd7-8aa7-40a7ba111f1a.mp4

**Comment by ChantsovaEkaterina** [comment]
Hello, @JacksonBowe 
We have disabled the "balloon" (spidery) effect for clustering.
To see the exact marker's position when markers are very close try to experiment with the maximum radius that a cluster will cover in the clustering settings.
![image](https://user-images.githubusercontent.com/17936317/142838728-d113f328-db49-444b-b2b6-f6baa7ed99f8.png)

**Comment by JacksonBowe** [comment]
@ChantsovaEkaterina , is there any chance of this effect coming back as an option? I have instances where markers are always going to be at the exact same lat-long so reducing the marker cluster radius won't help unfortunately. The markers are 100% stacked on top of each other.

**Comment by ChantsovaEkaterina** [comment]
@JacksonBowe, we will take into account your request and return back the "spidery" effect for clustering as an additional option in the next version.

**Comment by nechry** [comment]
Great new, I also set devices at same location and is no more possible to check them. happy to see the spidery effect back as before.
