### ISSUE TITLE
[Question][Bug] 3.3.2 Swagger changes

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5598]
The new swagger UI looks really amazing, and it's great that it automatically logs in using your saved session however I'm having trouble using it because of the url it tries to use.

Swagger is trying to use the following:
```
curl -X 'GET' \
  'http://{MY_DOMAIN}:80/api/device/types' \
  -H 'accept: application/json' \
  -H 'X-Authorization: Bearer {MY_TOKEN}'
```
Which gives the following result:
![image](https://user-images.githubusercontent.com/26427343/142789775-92d7bc93-abde-4ad6-a40d-57e7683d7419.png)

If I go through my cmd prompt and test I do indeed get no response, but it's because the url is incorrect. 
If I use the correct url it works fine:
```
curl -X 'GET' \
  'https://{MY_DOMAIN}/api/device/types' \
  -H 'accept: application/json' \
  -H 'X-Authorization: Bearer {MY_TOKEN}'
```
Notice I just removed the `:80` port identifier, and changed from `http://...` to `https://...`
This successfully returns my device types.

```
curl -X GET --header "accept:application/json" --header "X-Authorization: Bearer {MY_TOKEN}" https://{MY_DOMAIN}/api/device/types?pageSize=1000
[{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"controller"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"creek monitor"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"default"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"micro weather station"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"no-type"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"pivot"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"pump controller"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"rain gauge"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"soil probe"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"solar controller"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"tank sensor"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"thermostat"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"tracker"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"water quality sensor"},{"tenantId":{"entityType":"TENANT","id":"268619d0-d20a-11ea-a6fc-01fcf02ede18"},"entityType":"DEVICE","type":"weather station"}]
```

**Comment by ashvayka** [comment]
Hi @JacksonBowe , please let us know more about your Load Balancer setup and possibly the configuration of the load balancer. The Swagger UI should take the base URL that you open in the browser unless some headers from original request are specified/missing. We don’t see same issues in our environments.

**Comment by JacksonBowe** [comment]
Hi @ashvayka ,
Load balancer setup:
* In the same vpc and security group as my ec2 instance
* Security Group with the following
![image](https://user-images.githubusercontent.com/26427343/142805895-2b0e1010-0df1-4696-9cc8-8e79acd2e211.png)
* Listeners set up as
![image](https://user-images.githubusercontent.com/26427343/142806023-6bef6705-4ded-4fee-9b0f-88055f9eb3d3.png)
* ThingsboardTargetGroup settings
![image](https://user-images.githubusercontent.com/26427343/142806132-e8ae0324-af55-4f49-b16f-787f2f020df1.png)

This is what my swagger looks like for reference
![image](https://user-images.githubusercontent.com/26427343/142806387-030b1bdd-b8d5-47ac-a550-7fe1e967f5a0.png)

**Comment by Ultrazombie** [comment]
Hello JacksonBowe, 
Is your problem still relevant?

**Comment by quentinmit** [comment]
I just ran into the same problem. With the default configuration, sending `X-Forwarded-*` headers does not affect the Swagger-generated server URL:

```
curl -s -H "X-Forwarded-Proto: https" -H "X-Forwarded-Port: 10" -H "X-Forwarded-Host: nowhere.com" -H "X-Forwarded-SSL: on" 'http://localhost:8080/v3/api-docs/thingsboard' | jq '.servers'
[
  {
    "url": "http://localhost:8080",
    "description": "Generated server url"
  }
]
```

It looks like only the `Host` header is being honored (which means that it doesn't generate an HTTPS URL).

**Comment by corinmoss** [comment]
If anyone else is having this issue behind an nginx reverse proxy, the x-forwarded-proto header does seem to fix it:

        proxy_set_header X-Forwarded-Proto https;

**Comment by jpaddix** [comment]
@corinmoss Thanks! You saved my day!
