### ISSUE TITLE
[Question]How can I change thingsboard logo

### ISSUE THREAD

**Issue by kaizen8501** [thingsboard/thingsboard#560]
Hi every one, I am success compile and run my thingsboard 1.4.0. 
And then I want to change logo so I changed import logoSvg from '../../svg/logo_title_white.svg to '../../svg/my logo file.svg' and then compile and run. 
But I get "This application has no explicit mapping for /error, so you are seeing this as a fallback" in my browser. 
Could I get help? 
Additionally, I made svg file using Inkscape Vector Graphics Editor on Ubuntu.

**Comment by Firdauzfan** [comment]
Try to make id of the SVG file same as to logo_title_white.svg
And I suggest rename my logo file.svg to logo_title_white.svg, and then change the SVG id.

**Comment by piotrlinski** [comment]
in addition to above comment 

SVG can not have any XML objects/markers inside (i.e. text section ), if so all need to be converted to path

I have done it 2 weeks ago and all worked fine. SVG file I have created using Inkscape on Windows

**Comment by saurabhjhamb** [comment]
I was able to do it using inkscape, but pls remove the xml tag manually otherwise this wont work!

**Comment by kaizen8501** [comment]
@saurabhjhamb Thank you. I solved this problem after removed xml tag in svg file.

**Comment by Junaid09** [comment]
hi everyone, i'm very new in this. i wanna ask after making changes how can i compile and run thingsboard??

**Comment by Gastondamian** [comment]
any step by step guide to chage the logo?
