### ISSUE TITLE
[Feature Request] Repeat Alerts in Device Profiles.

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#5600]
Hi

It is actually a lot of work to create a Repeat alert mechanism in the rule chain. Also, this mechanism, based on existingAlarm, only works if the device has incoming Data, which is fine for Temperature Sensor alerts but doesn't work for NoComm type alerts.

So this can be a great addition to Device Profiles

currently existingAlarm is sent every time a new timeseries is saved on the device, but this can be every 5min, and I only wish to send a repeat alert every 60 minutes (or X minutes). And the issue i described above, that existingAlarm is only produced when new data arrives.

So this feature is very needed,

Device Profile -> Alarm Rules can have a setting for repeatAlert, in Minutes, using dynamic attributes, and on set Time, the Profile Node can produce this new type of Alarm message, repeatAlert, and we will use that to send notifications to users.

let me know if you need any use-case or other clarifications. 

@ashvayka

**Comment by mykhailokornieiev** [comment]
Hi. This is a valid improvement that was previously added to our backlog. Once the product team reviews this ticket, we’ll post an update on when this feature could be delivered if they decide to add this improvement to the product. There’s no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
