### ISSUE TITLE
[Question] How can I dynamically change the data on the Timeseries Widget?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5602]
I want to interfere with the time-series graph with the help of the widget bundle editor on the attached screen. Instead of the data query part in the normal time series widget, I want to real-time show the device selected by the user from the combo box and the measurement data he wants to show on the screen. I request your support on this issue.

When I want to go into detail in the widget editor, it seems like I have to write my own code in the chart js or I think I need to intervene and put my own yield on the "self.ctx.defaultSubscription.datasources" and "self.ctx.defaultSubscription.data" below. But whatever intervention I tried failed. can you please support me?

self.ctx.$scope.datasources = self.ctx.defaultSubscription.datasources;
self.ctx.$scope.data = self.ctx.defaultSubscription.data;
![Selection_003](https://user-images.githubusercontent.com/91528436/142870388-53920586-388d-421f-a87c-742bfd81974a.png)
![Selection_004](https://user-images.githubusercontent.com/91528436/142870398-490afb7c-4643-43ec-a4ca-faa449a3a703.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by hasankarainfo** [comment]
I'm researching this too

**Comment by hasankarainfo** [comment]
i think i found it. 

    let datasources = ctx.widgetConfig.datasources;
    let datakeys = datasources[0].dataKeys ; 
    
    for (var i = 0; i < 10; i++) {
        
        let objClone = Object.assign({}, datakeys[0]);
        
        objClone.label = objClone.name = objClone.pattern =  "sensor"+i;
        objClone.type = 'timeseries';
        objClone.funcBody = 'return;';
        
        objClone._hash = self.hashCode(objClone.name);
        datakeys.push(objClone);
    }

**Comment by hasankarainfo** [comment]
I also found a better way. 

    self.hashCode = function (str) {
        var hash = 0;
        var i, char;
        if (str.length === 0) return hash;
        for (i = 0; i < str.length; i++) {
            char = str.charCodeAt(i);
            hash = ((hash << 5) - hash) + char;
            hash = hash & hash;
        }
        return hash;
    }
    self.onInit = function() 
    {
        let datasources = ctx.defaultSubscription.configuredDatasources;
        let datakeys = datasources[0].dataKeys = [];
        let protokey = ctx.widgetConfig.datasources[0].dataKeys[0];
        datakeys.push(protokey);    
        for (var i = 0; i < 10; i++) {
            let objClone = Object.assign({}, protokey)
            objClone.name = objClone.pattern =  "sensor"+i;
            objClone.label = "label"+i;
            objClone.units = "units"+i;
            objClone.decimals = 1;
            objClone.type = 'timeseries';
            objClone.settings = [];
            objClone.minValue = 0;
            objClone.maxValue = 100;
            objClone.color = "#8080f0";
            objClone._hash = self.hashCode(objClone.name);
            datakeys.push(objClone);
        }
        ctx.defaultSubscription.initDataSubscription();
    }

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
