### ISSUE TITLE
[Bug] CASSANDRA_KEYSPACE_NAME ignored during install

### ISSUE THREAD

**Issue by resmo** [thingsboard/thingsboard#5603]
**Describe the bug**
We'd like to run 2 thingsboard setups (dev, test) using the same cassandra cluster (and postgresql db) and that is why we wanted to set cassandra keyspaces and database names. 

But we were not able to set a different cassandra keyspace for each environment (postgres db works fine). We can not even "rename" the keyspaces 

`CASSANDRA_KEYSPACE_NAME` as described in https://thingsboard.io/docs/pe/user-guide/install/config/#thingsboard-core-settings is ignored during install process.

It seems the keyspace `thingsboard` is hardcoded in https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/cassandra/schema-ts.cql#L17 

**Your Server Environment**
own setup:
  * docker (nomad cluster) + cassandra 3.11 cluster in VMs
  * ThingsBoard Version  3.3.2

**To Reproduce**
1. setup cassandra in a container:
2. run install with env vars:
```
CASSANDRA_CLUSTER_NAME="example-cluster"
CASSANDRA_KEYSPACE_NAME="thingsboard_dev"
CASSANDRA_USE_CREDENTIALS=false
CASSANDRA_LOCAL_DATACENTER="datacenter1"
CASSANDRA_URL="cassandra:9042"
```

**Expected behavior**
cassandra namespace used as configured in CASSANDRA_KEYSPACE_NAME in setup instead of  `thingsboard`

**additional**
```
 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.3.2PE)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing Cassandra DataBase schema part: schema-ts.cql
Loading system data...
Installation finished successfully!
```

**Comment by smatvienko-tb** [comment]
Hi, @resmo.
Thank you for your feedback.
The thingsboard keyspace name is included in schema-ts.cql and not overridden during install. 

The simplest solution is to replace keyspace in the installed folder (useful in the service model)
`nano /usr/share/thingsboard/data/cassandra/schema-ts.cql`

Other (my favourite) approach is to create the schema using Cassandra **cqlsh** (useful in Docker and Kubernetes):

Docker:
`smatvienko@linux:~$ docker exec -it cassandra /bin/bash`
Kubernetes:
`smatvienko@linux:~$ kubectl exec -it cassandra-helm-0 -- /bin/bash`

Docker:
`I have no name!@linux:/$ cqlsh -u cassandra -p cassandra 127.0.0.1`
Kubernetes:
`I have no name!@cassandra-helm-0:/$ cqlsh -u ${CASSANDRA_USER} -p ${CASSANDRA_PASSWORD} ${POD_IP}`
```
Connected to Thingsboard_Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.11 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> 
```
`cassandra@cqlsh> DESC KEYSPACE thingsboard; `

![image](https://user-images.githubusercontent.com/79898499/142981681-e71591ab-38a8-42cb-bbbb-ff6e68f8882a.png)

Then run the same create commands but with another keyspace name like:

`CREATE KEYSPACE dev WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} ...`
`CREATE TABLE dev.ts_kv_latest_cf ( ...`
`CREATE TABLE dev.ts_kv_partitions_cf ( ...`
`CREATE TABLE dev.ts_kv_cf ( ...`

Enjoy!

Important: choose and apply the [replication factor](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useUpdateKeyspaceRF.html) properly when you have many Cassandra nodes in the cluster.
Advanced: make sure that system_auth keyspace has a replication factor of more than 1 if you have many Cassandra nodes in the cluster.

**Comment by resmo** [comment]
Thanks for the hints, @smatvienko-tb 

Would probably be good to make some docs about this nearby the config `CASSANDRA_KEYSPACE_NAME`  description

Closing
