### ISSUE TITLE
[Question] How can I actively change the device on the Dashboard?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5604]
Hi,
Do we have the option to actively use the menu marked with part 1 on the attached Dashboard screen for the device selection menu in 2 parts? Our goal is to dynamically change the values shown in the chart and the device. Is there a simple solution to this? I request your support on the matter.
![Selection_006](https://user-images.githubusercontent.com/91528436/142980017-3afcfa6f-f643-42c8-b3dc-11f7ae73f50e.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
