### ISSUE TITLE
[Question] How can I edit the name of the legends shown in the time graph?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5605]
Hi,
My purpose in this question is to edit the name of the legends connected to the devices that I have added as an entity list and to understand that it is connected to it by adding the device id per legend.
![Selection_007](https://user-images.githubusercontent.com/91528436/142980122-04edfb5f-7698-4d6b-b3a9-473bfa27e7af.png)
![Selection_008](https://user-images.githubusercontent.com/91528436/142980124-4d9fdbf6-49f9-4294-a61e-34d013d1ab00.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by Backdraft007** [comment]
Help this?
https://github.com/thingsboard/thingsboard/issues/1626

**Comment by JacksonBowe** [comment]
Use `${entityLabel}` in the Data Key Label field
![image](https://user-images.githubusercontent.com/26427343/143133841-fe14a320-7d4d-4da5-a1f4-d17193f09878.png)
Result:
![image](https://user-images.githubusercontent.com/26427343/143133944-5acbc954-385d-4a5f-8758-393bf3fcaf27.png)

Can use `${entityName}` alternatively

**Comment by gohm-tech** [comment]
Hi, @JacksonBowe @Backdraft007 
Thank you, it works for our issue.
Best Regards,
**Gohm Team**
