### ISSUE TITLE
The Gateway cannot push data to the ThingsBoard

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard#5606]
**Describe the bug**
**information description**
1. Tb-gateway obtains data from device 1 over Modbus protocol.  Device 1 has more than 3000 fields.
     The configuration file is as follows
                {
                          "server": {
                            "type": "tcp",
                            "host": "device ip address",
                            "port": 502,
                            "timeout": 35,
                            "method": "socket",
                            "byteOrder": "BIG",
                            "devices": [
                              {
                                "unitId": 1,
                                "deviceName": "deviceName1",
                                "attributesPollPeriod": 5000,
                                "timeseriesPollPeriod": 5000,
                                "sendDataOnlyOnChange": true,
                                "timeseries": [
                        {"tag":"A","type": "bits","functionCode": 2,"objectsCount": 1,"byteOrder": "LITTLE","address":0},
                        {"tag":"B","type": "bits","functionCode": 2,"objectsCount": 1,"byteOrder": "LITTLE","address":1},
                                             **### More than 3,500 lines are omitted**
                        {"tag":"C","type": "32float","functionCode": 4,"objectsCount": 2,"wordOrder": "LITTLE","address":1482},
                        {"tag":"D","type": "32float","functionCode": 4,"objectsCount": 2,"wordOrder": "LITTLE","address":1498},
                        {"tag":"E","type": "32float","functionCode": 4,"objectsCount": 2,"wordOrder": "LITTLE","address":4594}
                                ]  }   ]  }   }

2. tb_gataway.yaml file configuration is as follows.
              thingsboard:
              host: thingsboard ip address
              port: 1883
              remoteShell: false
              remoteConfiguration: false
              security:
                accessToken: PUT_YOUR_ACCESS_TOKEN_HERE
              qos: 1
            storage:
              type: memory
              read_records_count: 1000
              max_records_count: 100000
            #  type: file
            #  data_folder_path: ./data/
            #  max_file_count: 10
            #  max_read_records_count: 10
            #  max_records_per_file: 10000
            connectors:
            #  -
            #    name: MQTT Broker Connector
            #    type: mqtt
            #    configuration: mqtt.json
              -
                name: ModbusDaxinginput
                type: modbus
                configuration: modbusDxiput.json
            #  -
            ....Is omitted
            #  -
            #    name: Custom Serial Connector
            #    type: serial
            #    configuration: custom_serial.json
            #    class: CustomSerialConnector

3. By capturing packets using tcpdump, the gateway can obtain all field values of the device using Modbus.

**issue description**
1. When the Modbus profile is only 20 lines long, there is no problem getting the data and displaying it in real time .
2. When a Modbus configuration file is several thousand lines long, ThingsBoard can't display all the fields and keep the data up to date.  
         
![1](https://user-images.githubusercontent.com/21196303/142978893-4cad2526-d355-4b39-be00-a94058044acd.png)

3.  How can i solve this issue? Thingsboard doesn't display data and doesn't update data in a timely manner when modbus configuration files are thousands of lines long.
4. Is thingsBoard having trouble communicating with the Gateway?  
5. How many lines can a Modbus profile support?  
**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Community Edit latest Version
  * OS centos7
  * DB postgresql

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [win10]
* Browser [chrome,]
* Version [e.g. 22]

**Your Device**
* Connectivity
  * Gateway -modbus
  * Integration: (Specify name) 
* Device vendor and model

**Comment by ashvayka** [comment]
Please create a corresponding issue for the gateway [project](https://github.com/thingsboard/thingsboard-gateway/issues). I am sure it is not an issue of ThingsBoard,

**Comment by RenCisco** [comment]
@ashvayka 
information description
 1.I've found that ThingSBoard can't write to PostgresQL if the Modbus configuration file has too many lines .
2.Thingsboard logs reported an error :ERROR o.t.s.t.mqtt.MqttTransportHandler - [d6d47acf-8d36-4c08-820a-c99b308a2cab] Message processing failed: too large message: 80215 bytes.
3. db is postgresql 12
4. so how can i solve the problem:(ERROR o.t.s.t.mqtt.MqttTransportHandler - [d6d47acf-8d36-4c08-820a-c99b308a2cab] Message processing failed: too large message: 80215 bytes.)

**Comment by ashvayka** [comment]
Try to update the NETTY_MAX_PAYLOAD_SIZE parameter. See [configuration](https://thingsboard.io/docs/user-guide/install/config/) for more details:



transport.mqtt.netty.max_payload_size | NETTY_MAX_PAYLOAD_SIZE | 65536 | Max payload size in bytes
-- | -- | -- | --

**Comment by RenCisco** [comment]
@ashvayka  Thanks for your help!
The tb page can display all data of 3500 lines in  modbus configuration file  ，but it don't update ontime. 
if i   configure five fileds in the modbus configuration file, modbus's data can update one time 5 seconds in the tb page  
so my question is how can i do for updated all data on time.

now:NETTY_MAX_PAYLOAD_SIZE is 5M

**Comment by RenCisco** [comment]
@ashvayka  Thanks for your help!
The tb page can display all data of 3500 lines in  modbus configuration file  ，but it don't update ontime. 
if i   configure five fileds in the modbus configuration file, modbus's data can update one time 5 seconds in the tb page  
so my question is how can i do for updated all data on time.

now:NETTY_MAX_PAYLOAD_SIZE is 5M

**Comment by ashvayka** [comment]
Please review the [troubleshooting guide](https://thingsboard.io/docs/user-guide/troubleshooting/?scenario=growing-latency) to investigate latency in message delivery. There is a chance that the latency is also caused by the IoT Gateway itself, but first, please follow the troubleshooting guide for the ThingsBoard.
