### ISSUE TITLE
[Question] Updating End Time after creating Alarm at the rule chain

### ISSUE THREAD

**Issue by Goran-59** [thingsboard/thingsboard#5608]
Hi there,

Is it possible to create multiple alarms across a single Create Alarm block for multiple devices simultaneously and get right END TIME?

![image](https://user-images.githubusercontent.com/84317817/143001308-1b33c04b-585b-4c9b-a98d-9dbe4f551ade.png)

Specifically, this Rule Chain is working in the way of creating alarms. I am getting the limit alarms for different priority, because each device has certain amount values while all of them have been checked in the scripts.
However, in this case i do not get the END TIME of alarm (it is always the same as CREATING TIME). That is happening because i overwriting previous when i get the new telemetry from different device. 

**So, is there a way to manually update END TIME?**

This is a code where i am separating devices: 
````
var newMesg = {};
var newMetadata = {};
switch (metadata.deviceName) {
    case "SFR": {
        if (msg.AlarmHighSFR) {
            newMesg.AlarmStatus = true;
            dateObject = Date(metadata.ts);
            newMetadata.Datetimestamp = dateObject
                .toLocaleString();
            newMetadata.FaultySensorsHigh = metadata
                .FaultySensorsHigh;
            newMetadata.deviceName = metadata.deviceName;
        } else {
            newMesg.AlarmStatus = false;
        }
    }
    break;
case "NRA": {
    if (msg.AlarmHighNRA) {
        newMesg.AlarmStatus = true;
        newMetadata.FaultySensorsHigh = metadata
            .FaultySensorsHigh;
        newMetadata.deviceName = metadata.deviceName;
    } else {
        newMesg.AlarmStatus = false;
    }
}
break;
case "DROBAK": {
    if (msg.AlarmHighDRO) {
        newMesg.AlarmStatus = true;
        newMetadata.FaultySensorsHigh = metadata
            .FaultySensorsHigh;
        newMetadata.deviceName = metadata.deviceName;
    } else {
        newMesg.AlarmStatus = false;
    }
}
break;
case "FREVAR": {
    if (msg.AlarmHighFRE) {
        newMesg.AlarmStatus = true;
        newMetadata.FaultySensorsHigh = metadata
            .FaultySensorsHigh;
        newMetadata.deviceName = metadata.deviceName;
    } else {
        newMesg.AlarmStatus = false;
    }
}
break;
}

return {
    msg: newMesg,
    metadata: newMetadata,
    msgType: msgType
};
````

**Comment by Alentus** [comment]
Hi, you can set alarm type and other parameters in incoming message to alarm node.
Set checkbox in nodde setting's 
![screenshot-192 168 0 115_9000-2021 11 24-10_07_37](https://user-images.githubusercontent.com/53187020/143199883-d0945691-15a6-472b-811f-1f017d95e74e.png)

And in script node use some like this
```
var newMsg = {
    "severity": "INDETERMINATE",
    "type": "fls_line_stop",
    "startTs": 1632120936111,
    "propagate": true,
    "details":{},
    "propagateRelationTypes": ["Contains"]

}

```

> However, in this case i do not get the END TIME of alarm (it is always the same as CREATING TIME). That is happening because i overwriting previous when i get the new telemetry from different device.

It is strange, perhaps you have set the same alarm type for one device for several conditions

**Comment by Alentus** [comment]
@Goran-59 The details are not important, just an example from my system. The stop time is set by passing the alarm reset node with the same alarm type. Can you export your rule chain for better understanding?

**Comment by Goran-59** [comment]
Sure it is not a problem: 

[new_data_validation_alarms.zip](https://github.com/thingsboard/thingsboard/files/7604535/new_data_validation_alarms.zip)

In the red box i need to somehow update the update End Time: 

![143001308-1b33c04b-585b-4c9b-a98d-9dbe4f551ade](https://user-images.githubusercontent.com/84317817/143480972-ce490507-bfff-4c9b-89e7-3768fd8b136c.png)

**Comment by Alentus** [comment]
@Goran-59  The end time is set when the alarm is updated, that is, if you have an alarm triggered by one message in the alarm generating node, then the end and start time will be the same; if several messages arrive, the end time will be the arrival time of the last one. You need to send messages to the node all the time while the alarm is active for the time to be updated. And for correct operation for one type of alarm, there must be one level, because the alarm is cleared by type. Here is my chain following your exampl
[alarms.zip](https://github.com/thingsboard/thingsboard/files/7605121/alarms.zip)
e.

**Comment by Goran-59** [comment]
I tried to explain you that. Although, i tried to find a way to go around and hard code it.
However, your example was helpful and i know what i need to change now . 

Спасибo.
