### ISSUE TITLE
[Question] Set Is Gateway Checkbox with Rest API

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5613]
Hi, 
I want to create a Gateway automatically. I can create Gateway with Rest API. However, I can't set the "is gateway" checkbox. How can I set this checkbox in Rest API? Also, I am using Device Profile and can I set this checkbox with Device Profile.

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by Alentus** [comment]
Hi, i am don't  check this but maybe you need add additionalInfo in request body like

```
{
  "id": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "DEVICE"
  },
  "tenantId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "TENANT"
  },
  "customerId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "CUSTOMER"
  },
  "name": "A4B72CCDFF33",
  "type": "Temperature Sensor",
  "label": "Room 234 Sensor",
  "deviceProfileId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "DEVICE_PROFILE"
  },
  "deviceData": {
    "configuration": {},
    "transportConfiguration": {}
  },
  "firmwareId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "OTA_PACKAGE"
  },
  "softwareId": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "OTA_PACKAGE"
  },
  "additionalInfo": {
    "gateway": true
   }
}
```

**Comment by ashvayka** [comment]
@Alentus is correct. Add "gateway":true to the "additionalInfo"
