### ISSUE TITLE
[Bug] ThingsBoard doesn't show data in the chart. Telemetry shows only on latest value widgets and latest telemetry on the device information

### ISSUE THREAD

**Issue by seikosantana** [thingsboard/thingsboard#5615]
**Describe the bug**
I was upgrading Thingsboard instance. And the as the title says, new telemetry pushed to the server doesn't show up in chart widgets, only on latest value widgets (and it needs to be refreshed to update).

**Your Server Environment**

* own setup
  * cloud infrastructure
  * ThingsBoard 3.2.0 and 3.3.2 (will explain further)
  * Ubuntu Server 18.04 amd64

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Tested on Ubuntu 20.04 Desktop and Windows 10 20H2
* Browser Chrome
* Version 95.0.4638.69

**Your Device**

* Connectivity
  * MQTT
  * HTTP

* Device vendor and model: Custom device

**To Reproduce**
1. I was at version 3.2.0 before the upgrade, following the upgrade instructions for thingsboard CE.
2. I performed backup of database with `pg_dump -Fc -f thingsboard.dump thingsboard`
3. I performed version-by-version upgrade to 3.3.2
4. I tried pushing new telemetry to new device, and telemetry does not show up on the chart widgets, not updating automatically.
5. I thought something went wrong during the upgrade, so i uninstalled thingsboard with `sudo apt purge thingsboard`
6. I reinstalled thingsboard with the debian package on https://github.com/thingsboard/thingsboard/releases/download/v3.2/thingsboard-3.2.deb
7. I dropped the thingsboard database with `DROP DATABASE thingsboard;`
8. I created a new database called thingsboard. `CREATE DATABASE thingsboard;`
9. I restored the previous backup with `pg_restore -Fc -C -c ./thingsboard.dump`
10. I forgot the database password to put in the conf, so i changed the password with `\c thingsboard; \password`
11. I put in the following content to /etc/thingsboard/conf/thingsboard.conf
# DB Configuration 
```
export DATABASE_ENTITIES_TYPE=sql
export DATABASE_TS_TYPE=sql
export SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
export SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
export SPRING_DATASOURCE_USERNAME=postgres
export SPRING_DATASOURCE_PASSWORD=mynewpassword
export SPRING_DATASOURCE_MAXIMUM_POOL_SIZE=5
# Specify partitioning size for timestamp key-value storage. Allowed values: DAYS, MONTHS, YEARS, INDEFINITE.
export SQL_POSTGRES_TS_KV_PARTITIONING=MONTHS
```
12. I started the thingsboard service, and did the same test to see if it works.
13. See that telemetry is not showing in the timeseries datasource but shows up in latest telemetry of device information, needs refreshing to get the value updated.

**Expected behavior**
Telemetry should show up in the timeseries and in latest value chart, without the need of refreshing to get the value updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/35630407/143226566-7c26455f-bde4-4822-aa63-ba1e9a81989b.png)
![image](https://user-images.githubusercontent.com/35630407/143226620-949bb893-5071-45a7-a434-c796ffcce5ac.png)

**Additional context**
On 3.3.2 before i reinstalled thingsboard, The telemetry keys still appears in the selections, but not after reinstalling.
A log file is attached.

Thanks a lot in advance!
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/7595116/thingsboard.log)

**Comment by volodymyr-babak** [comment]
@seikosantana 

You have issue with timeseries history table:
**Caused by: org.postgresql.util.PSQLException: ERROR: "ts_kv" is not partitioned**

This error message is constantly appears in your log. 
Latest data works fine, because for the latest values another table is used.

Please provide your version of PostgreSQL database. Is it 11 version or later?

And please attach your current **ts_kv** table schema of **thingsboard** database.
