### ISSUE TITLE
[Question] How can I restore to the previous version if the Upgrade Fails (Again)

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#5618]
Thingsboard PE upgrade stuck after
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.3.1
ThingsBoard upgrade failed!

I only use a postgresql database.

Do I need to restore the whole VM or can I just replace the config files and start the service again?

**Environment**
 * Ubuntu 20.04 LTS
 * ThingsBoard PE 3.3.1

**Comment by Ultrazombie** [comment]
Hello @KenSense,
Is your problem up to date? 
If so, please provide the full output of the upgrade command
and the steps of your upgrade.
Also, we strongly recommend backing up your database before any upgrade.

**Comment by KenSense** [comment]
I eventually got it completing by disabling the TLS setting and then fixed that problem later.
The question was in case I'm stuck is there a way to go back to the previous version assuming you have a backup of the database before you started the upgrade or is full VM restore advised/required?

**Comment by Ultrazombie** [comment]
If you have a database backup, of course, you can revert to a previous version. For example, you had a version 3.3.1, and you failed to upgrade to 3.3.2:
1. install TB 3.3.1 to which the backup database belongs.
2. Restore database from backup (TB 3.3.1 version)
3. Start ThingsBoard.

**Comment by KenSense** [comment]
Any removal steps?

**Comment by Ultrazombie** [comment]
@KenSense, Yes, before restoring need to connect to PSQL and run

```
drop database thingsboard;
create database thingsboard;
```

and after that 

`psql -U postgres -d thingsboard -W < /path_to_backup/backup.sql.bak`

We also advise you to make a backup with 
`pg_dump thingsboard > /path_to_backup/backup.sql.bak`

**Comment by KenSense** [comment]
That is for the database but what about the install files?
Just run the old install and script again?

**Comment by Ultrazombie** [comment]
In your case: when you only restore the backup, you need just run your thingsboard service and didn't install any (Or delete files).


I advise you to try these actions on some virtual machine so that there is no misunderstanding of backup algorithms on your main server.
