### ISSUE TITLE
Build ThingsBoard sources failure

### ISSUE THREAD

**Issue by carlos2997** [thingsboard/thingsboard#562]
When i'm compiling the source, i have this problem...
![screenshot from 2018-02-06 11 36 32](https://user-images.githubusercontent.com/22376498/35871296-ddf84ffe-0b31-11e8-8ded-2437b457abb3.png)
 
I have these versions
![screenshot from 2018-02-06 11 39 41](https://user-images.githubusercontent.com/22376498/35871399-280b6a36-0b32-11e8-8b7a-411d828fff06.png)
:

**Comment by 9410ger** [comment]
You have to modify /thingsboard/ui/package.json and replace this:
![image](https://user-images.githubusercontent.com/17624350/35883463-4d42044a-0b55-11e8-9bc1-a8c5ef79cf2e.png)
with this:
![image](https://user-images.githubusercontent.com/17624350/35883492-618af060-0b55-11e8-878f-77b17b71550a.png)
and do it for all git repositories in the file

**Comment by ashvayka** [comment]
this should work fine without modifications. See the build badge on the main project page. It is working fine.

**Comment by ashvayka** [comment]
https://travis-ci.org/thingsboard/thingsboard
