### ISSUE TITLE
[Question] How to Create alarm in case a script fails in the Rule Engine?

### ISSUE THREAD

**Issue by Nathan-ma** [thingsboard/thingsboard#5622]
**Component**

 * Rule Engine

**Description**
Hello, I know this might be an easy question. But I have many rules running on my Rule engine, and I wanna be able to trigger an alarm if any script fails to run for example, and also be able to see what caused the issue. I was previously enabling Debug on said rules, but as we all know, debug will quickly consume all the space you have and it will require a DB clean.

I have zero experience with alarms on Thingsboard. How can I easily create an alarm for each rule and manage all the alarms in a single dashboard? 

What about the Log rule? can I catch and save the failure information on it? if yes, I will have to access the nasty Thingsboard log file in order to retrieve it?

Thanks a bunch for the good samaritan with the golden hart that will provide me guidance and pictures!

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.3.2
 * Browser: Chrome (95.0)

**Comment by ashvayka** [comment]
Hi @Nathan-ma, we have a rule engine statistics dashboard. See the [docs](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics). This does not trigger notifications automatically but is very useful. We will add notifications later as a separate subsystem.

**Comment by Nathan-ma** [comment]
Yes, thank you ashvayka. I'm running on an older version. I saw this dashboard and now more than ever I need to start parsing my old widget to angular9 and update to this amazing new version. This rule dashboard is everything I've ever wanted !
