### ISSUE TITLE
Getting previous data in custom widget?

### ISSUE THREAD

**Issue by Pankaj9410557422** [thingsboard/thingsboard#5626]
I was making custom widget in which i need to get previous three months data and make some calculations on that data. I am using the timewindow function to update the timewindow but the issue is the the data in default subscription i dont know fills after sometime and till than my loop gets over as it dets the data arrray length =0; can anyone help me with another way of doing this. Please suggest some approch to deal with this situation or any way  can make a database call to get all data as jumping over the timewindow is increasing the complexity of the code.

**Comment by ashvayka** [comment]
Have you checked the https://thingsboard.io/docs/user-guide/contribution/widgets-development/ ?
