### ISSUE TITLE
 The update of REST API plugin not apply changes. Keep running with old values

### ISSUE THREAD

**Issue by toti1212** [thingsboard/thingsboard#563]
Hi.
I have 2 REST API Call Plugins, that send data to diferents urls. One of them send data to one url, and the other one, used to test with a dinamic url, so, many times I update de plugin changing the url.

Many times, the plugin have errors( 404 ) that cant send data to the url, but   seeing in the log when I update de plugin, its keep running with the old url.

The only way to fix it is restart the service.

Any ideas?

Thanks

**Comment by ashvayka** [comment]
should be fixed in the latest version

**Comment by toti1212** [comment]
Okay thanks! I will try to update to the latest version this weekend. If its works I notify here and close the issue!

**Comment by vparomskiy** [comment]
@toti1212 : did you check the latest version and does it work or not? Thank you for updates.
