### ISSUE TITLE
[Bug] Time-series aggregation fails: Number of intervals is too high

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5635]
I've encountered a problem using the 'getTimeseries'-function of the telemetry controller.
My api call looks something like

`HOST/api/plugins/telemetry/DEVICE/efed8f70-b19c-11eb-97b1-a7c28d931877/values/timeseries?interval=10900000&agg=AVG&&useStrictDataTypes=false&keys=Temperature,DragForce&startTs=1609459260000&endTs=1618179260000`

This equals 800 aggregation-intervals inside my time-window.
The repsonse is:

`Incorrect TsKvQuery. Number of intervals is to high - 800. Please increase 'interval' parameter for your query or reduce the time range of the query.`

Unfortunately, there is no documentation on what is the actual max. nr of intervals allowed.
The weird thing is that I do get the 'raw' (non-aggregated) data for the same total time-window if I drop the interval and aggregation parameters. 
So, in principle I could do the aggregation myself.

Maybe this is somehow related to the **cassandra-db**?

Any suggestions?

Server Environment:

own setup
docker deployment
ThingsBoard Version: 3.3.1 PE
Win 10

**Comment by ashvayka** [comment]
No, actually there is such documentation. See https://thingsboard.io/docs/user-guide/install/config/, "Common database parameters": 


database.ts_max_intervals | DATABASE_TS_MAX_INTERVALS | 700 | Max number of DB queries generated by single API call to fetch telemetry records
-- | -- | -- | --

**Comment by eeitnn** [comment]
> No, actually there is such documentation. See https://thingsboard.io/docs/user-guide/install/config/, "Common database parameters":
> 
> database.ts_max_intervals	DATABASE_TS_MAX_INTERVALS	700	Max number of DB queries generated by single API call to fetch telemetry records

Thank you. I didn't expect that this request is subdivided into so many sub-requests.

**Comment by ashvayka** [comment]
Cassandra does not support "GROUP BY" for specific intervals. Only for partition/clustering key. And the grouping intervals from the request do not necessarily match the grouping intervals of the partition/clustering key. So, that is the only option we found to do this.
