### ISSUE TITLE
Submenu in the submenu item does'n want to display. What shall I do?

### ISSUE THREAD

**Issue by Kullpoint** [thingsboard/thingsboard#5636]
Submenu in the submenu item does'n want to display. What shall I do?

[image 1][1] | [image 2 ][2]

  [1]: https://i.stack.imgur.com/MAGn2.png
  [2]: https://i.stack.imgur.com/DL4X1.png

**Comment by vvlladd28** [comment]
Hi @Kullpoint,
Currently, the TB supports only two menu levels.
