### ISSUE TITLE
How to fix doublemenu?

### ISSUE THREAD

**Issue by Kullpoint** [thingsboard/thingsboard#5638]
I just need to view a dashborads list (without double menu like in screen)
Its a custom menu link:
{
      "name": "HVAC",
      "iconUrl": null,
      "materialIcon": "assessment",
      "iframeUrl": "/dashboardGroups/2a987140-2677-11ec-b235-11f89ce87ccd",
      "dashboardId": null,
      "hideDashboardToolbar": null,
      "setAccessToken": false,
      "childMenuItems": []
}
![image](https://user-images.githubusercontent.com/60100065/143905881-a866ad52-be73-45e0-92a6-6e4da474fe47.png)

**Comment by Kevinowitsch** [comment]
Hi, have you found a solution yet?
