### ISSUE TITLE
Disconnect on publish() (ESP8266)

### ISSUE THREAD

**Issue by wyojustin** [thingsboard/thingsboard#564]
*** Newbie first publish try. *** 

I'm trying to publish hello world to a device named "ESP8266Client" on the live demo (Acct: wyojustin) (made public)
Device ID: ff382890-09f8-11e8-9141-1d8d2edf4f93
Access Token: 5vOhJJYU2rGTDiJJ5FME

I am able to successfully connect to the device
`if (client.connect("ESP8266Client", TOKEN, NULL)) {
      connected = true;
      Serial.println("connected");
      // Once connected, publish an announcement...
      Serial.print("publish? ");
      Serial.println(client.publish("v1/devices/me/telemetry", "hello world")); // disconnects client
      // ... and resubscribe
      client.subscribe("inTopic");
  while(1){
    Serial.println(client.connected());
    delay(1000);
  }`

I can confirm that the client remains connected if I do not publish anything, but disconnects whenever I try to publish.

Thanks for any help you can provide!

**Comment by ashvayka** [comment]
this means you publish an invalid message that is rejected. Once the message is rejected the server closes the connection (according to MQTT Protocol definition.) You are obviously posting invalid JSON (Hello World)
