### ISSUE TITLE
Can Thingsboard 3.3.0 PE be downgraded?

### ISSUE THREAD

**Issue by aortega1** [thingsboard/thingsboard#5641]
I have a production system which is no longer operable and need to downgrade to a earlier release, are there downgrade instructions from 3.3.0?

**Comment by Backdraft007** [comment]
Hi,
from which version do you have done the upgrade?
What is the problem with your system?

**Comment by ashvayka** [comment]
ThingsBoard stores dashboards, rule chains, and other entities in the database. So, to downgrade, you should install old package and restore the backup of the database. Make sure you also use old (pre-upgrade) versions of thingsboard.yml and thingsboard.conf

**Comment by aortega1** [comment]
Closing as no longer relevant.  I was able to wipe the server and get 3.3.2 functional...to a point, more on that in another issue.

**Comment by synetalsolutions** [comment]
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.7.0

run this command it will fix your issue.
