### ISSUE TITLE
[Question] REST upload ota package

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5646]
**Component**

 * Generic

**Description**

Trying to upload OTA file using the REST api with python requests.
First I post a package using /api/otaPackage and giving it the json
`json = {
        "tenantId": {
        "id": tenantId,
        "entityType": "TENANT"
    },
        "deviceProfileId": {
        "id": deviceProfileId,
        "entityType": "DEVICE_PROFILE"
    },
    "type": "FIRMWARE",
    "title": "FS",
    "version": tag,
    "tag": "FS " + tag,
    "fileName": tag,
    "hasData": True,
    "contentType": "application/octet-stream",
    "checksumAlgorithm": "SHA256",
    "checksum": hash,
    "dataSize": len(data),
    "additionalInfo": {}
    }`

I have tried with various amount of data in the json, with without the checksums, with hasData set to true, false and so.

Then I try to post the data using /api/otaPackage/{packageId} 
where packageId is the id created above.
data is the binary of the file I want to upload
adding the "checksumAlgorithm": "SHA256" parameter.

When I execute I get response status 500 and errorCode: 2

Any tips on how to find what I am doing wrong?

Best
Tobias

**Environment**

 * OS:  docker
 * ThingsBoard: 3.3.2PE
 * Browser: Python

**Comment by tobbelin** [comment]
Found the problem, I just needed to send with files instead of data in the requests module.

**Comment by RudraNathPalit** [comment]
Hi, Can you share the code that finally worked.
