### ISSUE TITLE
Export and import function for OPC UA integration

### ISSUE THREAD

**Issue by ts4iot** [thingsboard/thingsboard#5647]
With TB 3.3.1 it is not possible to export / import an OPC UA integration to a file (e.g. JSON).

Please provide a feature to export and import an OPC UA integration. It should work comparable to the export/import feature of data converters.

An alternative is to do it manually. For simple OPC UA mappings this is ok, but for complex OPC UA mappings it is not practical.

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
