### ISSUE TITLE
Send Downlink to Chirpstack (LoRa End node) from Thingboard using integration downlink.

### ISSUE THREAD

**Issue by santobedi** [thingsboard/thingsboard#5658]
I'm able to send the following `JSON object` as a downlink using external `rest API call` from the Thingsboard. The `data` is the Base64 string that commands a Modbus relay (and it works perfectly fine). 

 ```
 {
         "deviceQueueItem": 
            {
             "confirmed": true,
            "data": "AgABAAgBBQAB/wDd+g==",
             "devEUI": "ac1f09fffe0137bb",
             "fCnt": 0,
            "fPort": 129,
             "jsonObject": ""
            }
        }
```
I want to send the same JSON object using the `integration downlink`. I've made Uplink / Downlink converters and the Integrator in the Thingsboard. In the integration details, I've chosen ChirpStack. I've used Control Widgets (Switch control) in the dashboard and the `integration downlink` node in the Rule chains. However, I'm unable to send the `JSON object` to the end node. Is there any documentation about using Chirpstack integration in the Thingsboard? Any hints or code snippets will be highly appreciated. Thank you. 

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.2.2PE
 * Browser: Chrome

**Comment by santobedi** [comment]
The integration downlink worked after upgrading the Thingsboard to 3.3.2PE.

**Comment by BaerSy** [comment]
@santobedi Sorry to bother you.  We are working on Thingsboard PE integrating with ChirpStack, never got worked. Do you mind i ask you some help on how you make it work?  for example, in ChirpStack application server/application, what i need integrate, Thingsboard or HTTP? in Thingboard PE side, do i need configure something too, for example, in integration, do i need configure "ChirpStack" too?  anything I need pay attention too?  Many thanks in advance.

**Comment by BaerSy** [comment]
Hi, @santobedi 
Thanks for your advice. Follow your advices, I saw the device tab of TB says "2022-01-22 21:39:36	active	true", does this mean TB can link to Chirpstack?  I can  see some data (fcnt, fport....) from telemetry.  but I can't see any application data, like temperature etc.  I believe i need more works on decode and encode function.  Do you have example of decode and encode functions?  I noticed that both Chirpstack and TB need these functions( TB data converter need take care uplink and downlink).  Chirpstack -- application -- Codec need these functions too.  Do you have any example? thank you in advance.

**Comment by santobedi** [comment]
Hello @BaerSy,

You need to design your decoder in the CODEC part of your device profile in Chirpstack. It's very simple. To check what you are receiving from your LoRa End node at the network server, you can do as follows: 

```
function Decode(fPort, bytes) {
var testObjects={};
testObjects["firstObject"] = byets[0];
testObjects["secondObject"] = bytes[1];
// and so on....
return testobjects;
}
```

In the TB, these Objects will appear as follows (Key/Value pairs in the Timeseries telemetry):

`data_firstObject`, `data_secondObject` and so on.

 Note that you can see these Objects in the device data section of the Chirpstack too (under `Objects`). 

Now, you must figure out which bytes give you Temperature or Humidity values.

**Comment by ujals** [comment]
{
    "deduplicationId": "31b79c17-fe91-4596-b7d2-27273ada6c14",
    "time": "2023-12-20T06:26:19+00:00",
    "deviceInfo": {
        "tenantId": "52f14cd4-c6f1-4fbd-8f87-4025e1d49242",
        "tenantName": "ChirpStack",
        "applicationId": "d1d0687e-d0a0-4c19-9798-c4e811413c7f",
        "applicationName": "Frac Tracker",
        "deviceProfileId": "8d43a3cc-c681-45ea-bb93-9e1915a9d642",
        "deviceProfileName": "FRAC",
        "deviceName": "FRAC_tracker",
        "devEui": "a84041c3d185ee46",
        "deviceClassEnabled": "CLASS_A",
        "tags": {}
    },
    "devAddr": "780000ba",
    "adr": true,
    "dr": 5,
    "fCnt": 57,
    "fPort": 2,
    "confirmed": false,
    "data": "AAAAAAAAAAAPoiACmAFC",
    "object": {
        "Longitude": 0.0,
        "Hum": 66.4,
        "Tem": 32.2,
        "BatV": 4.002,
        "MD": 0.0,
        "Location": 0.0,
        "Latitude": 0.0,
        "LON": "ON",
        "ALARM_status": "FALSE"
    },
    "rxInfo": [{
        "gatewayId": "9d2726095c1c22c9",
        "uplinkId": 9312,
        "gwTime": "2023-12-20T06:26:19+00:00",
        "nsTime": "2023-12-20T06:26:19.577289947+00:00",
        "rssi": -33,
        "snr": 13.5,
        "context": "YEE7Vw==",
        "metadata": {
            "gateway_h3index": "8c6520cb381c1ff",
            "region_common_name": "AS923",
            "regi": "AS923_1",
            "gateway_lat": "1.397581957823936",
            "gateway_id": "115aBSxqRKFG4n7tJYUJA65rxmuNLPMQgxDGFiLfb9RDN9rkCUw",
            "gateway_name": "gentle-fiery-pigeon",
            "gateway_long": "103.750001247407795",
            "region_config_id": "as923"
        },
        "crcStatus": "CRC_OK"
    }],
    "txInfo": {
        "frequency": 923200000,
        "modulation": {
            "lora": {
                "bandwidth": 125000,
                "spreadingFactor": 7,
                "codeRate": "CR_4_5"
            }
        }
    }
}

this is my decoder
var data = decodeToJson(payload);
var deviceName= data.name;
var deviceType='default';
var decodedpayload=data.decoded.payload;
var device_id=data.id;
decodedpayload.device_id=device_id;
decodedpayload.hotspot_name=data.hotspots[0].name;
decodedpayload.hotspot_lat=data.hotspots[0].lat;
decodedpayload.hotspot_long=data.hotspots[0].long;
decodedpayload.hotspot_freq=data.hotspots[0].frequency;
var Lati=1.397581957823936;
var Longi=103.7500012474078;

var circle = {
    "latitude": Lati,
    "longitude":Longi,
    "radius":700};
var hotspot_circle = {
    "latitude": data.hotspots[0].lat,
    "longitude":data.hotspots[0].long,
    "radius":5000};
decodedpayload.circle=circle;
decodedpayload.hotspot_circle=hotspot_circle;

var result = {
deviceName: deviceName,
deviceType: deviceType,
telemetry:decodedpayload
};

function decodeToString(payload) {
return String.fromCharCode.apply(String, payload);
}

function decodeToJson(payload) {
var str = decodeToString(payload);
var data = JSON.parse(str);
return data;
}
return result;
  its not working
