### ISSUE TITLE
[Bug] Telmetry data not shown in dahsboard although present in cassandra

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5660]
I've been struggling for hours now to identify what I'm doing wrong.
But it appears to be some kind of a bug now. 

I'm integarting telemetry data via kafka-integration for a specific device.
The uplink-converter (in debug mode) tells me, that the data is received and processed.
Taking a look into the cassandra-db for that specific device also confirms, that the new data was received and accepted as telemtry data.
However, it is not displayed in the time-series widget.

Take a look at the line chart:
![image](https://user-images.githubusercontent.com/86358217/144257889-fa61362e-3a59-4a54-9aaf-11d107f5b26e.png)

Now, I'm sending data from the 1st of Nov 2021 to the 1st of Dec 2021 to my kafka-topic.
Let's take a look at the cassandra db:
![image](https://user-images.githubusercontent.com/86358217/144258256-407a507c-5966-4682-8899-6f64fc682d8e.png)
The highlighted timestamp corresponds to Nov 15th. 2021
So the telemetry data is present.

However, the above dashboard still lacks the new data.

BTW: Before I sent the new data, I deleted the previous data for my telemetry key "Fres" for this time-range using

`SOMEHOST/api/plugins/telemetry/DEVICE/08040790-c20c-11eb-ab6d-8bbdd278744b/timeseries/delete?keys=Fres&deleteAllDataForKeys=false&startTs=1635724800000&endTs=1638454232000&rewriteLatestIfDeleted=false
`
Is this somehow related to the problem?
Is this some kind of caching problem?

Best regards

Environment:
PE 3.3.1

**Comment by eeitnn** [comment]
Does anybody have an idea?
I've now tried to send the data via an mqtt-gateway-device and the problem remains. 
So it is not related to the kafka-integration.

Interestingly, I can see that the data was received by thingsboard.
It appears in the "Save Timeseries"-Node in the root-rulechain.
Also I can find it in cassandra and the latest telemetry tab of the corresponding device.
Only the dashboard completely lacks the telemetry data.



![703c6d9e-b2da-4a1b-9234-4fd8ff549451](https://user-images.githubusercontent.com/86358217/145778225-ef0f0e04-8f1f-4b4d-8f9c-6b8560ac576e.jpg)
![a90ff6f7-d14e-4462-a401-af6320122b7c](https://user-images.githubusercontent.com/86358217/145778232-c5f29b6b-709e-419a-be3d-60c5878564ff.jpg)
![image](https://user-images.githubusercontent.com/86358217/145778743-5fd0b7b5-18d1-466e-abd2-6997186800c9.png)
![image](https://user-images.githubusercontent.com/86358217/145779053-f8d97b9f-0cd9-461f-b1f0-837d911af705.png)

**Comment by eeitnn** [comment]
The issue was the following:

When deleting data for a specified time-window via the REST-API, the corresponding record in the partitions-table might be removed. So even if the data is present in ts_kv_cf-table, thingsboard first queries the partition-table. If the entry for the time-window is missing it doesn't look further into the ts_kv_cf-table. Instead it is assumed that there's no telemetry data available

**Comment by ThomasBaumgartner** [comment]
Hello @eeitnn I'm facing the exact same behaviour. Can you explain a little more in detail how this behaviour can be avoided? Since I want to delete certain values and rewrite them using the API.

Best regards,

I'm currently using TB Version 3.3.2.

**Comment by eeitnn** [comment]
> Hello @eeitnn and @ThomasBaumgartner, I think I might have the same issue as you, as described [here](https://github.com/thingsboard/thingsboard/issues/6844). Do you have found a solution for this ? Thank in advance,
> 
> Lucas

Sure. I assume you're using cassandra for timeseries-data. Thingsboard creates a table called "ts_kv_partitions_ts". It acts like some kind of flag which stores a timestamp once every month for every device and every telemetry-key in case there is timeseries data for available for the given month. Before thingsboard takes a look on the actual telemetry data (stored in ts_kv_cf), it checks whether the table "ts_kv_partitions_cf" contains records for the queried timewindow. 

If you delete telemetry data for a timewindow greater than one month, not only the actual timeseries data is deleted (from ts_kv_cf) but also the corresponding records from ts_kv_partitions_cf. 

This means, you will have to add these missing records manually into the latter one.

**Comment by lucasKapf** [comment]
Hi @eeitnn thank you for your answer. The thing is I use thingsboard.cloud, so I believe I have no access to those tables ?
I don't know what to do, do I have to use the "save to custom table" rule node and provide the table names that you are talking about ?
I have created an issue [here](https://github.com/thingsboard/thingsboard/issues/6844) to explain my problem in details, but I think it is the same issue as yours.
Best regards,

Lucas
