### ISSUE TITLE
[Question] additionalParams not working on Custom Actions Markdown/HTML Card

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#5663]
**Component**

 * Generic

**Description**
additionalParams is not returning selected data on Custom Action of Markdown/HTML Card.

Custom action JS is just with the console.log:
`console.log(additionalParams);`

This returns an object as below
![image](https://user-images.githubusercontent.com/77509200/144282424-5608e805-0b69-47b6-bac6-4b3f3c56ccd9.png)

When I perform the same with Entities table widget I got the correct object, with the data I need as below:
![image](https://user-images.githubusercontent.com/77509200/144282978-2b87f70d-03f0-4b93-bf1b-cd106f25634a.png)

Is this a problem with the widget code? How can I solve this?

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: PE 3.3.2
 * Browser: Firefox 94.0.2

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Comment by AlexRak2** [comment]
why would this be closed? This is a question others might need, im going through this now to
