### ISSUE TITLE
"rpc call reply" rule node missmatch with deviceService.sendXxxWayRpcCommand

### ISSUE THREAD

**Issue by Nick-Aus** [thingsboard/thingsboard#5665]
The "rpc call reply" rule node requires an integer (default is requestId) but sendXxxWayRpcCommand provides a UUID (as requestUUID).

The reply rule node also expects a serviceId and sessionId which are not provided by the deviceService function.

The RPC command is being sent off via an external REST call. Is this "rpc call reply" not the approach I should take to update a pending RPC promise in the client widget? *lost*

**Comment by Ultrazombie** [comment]
Please read the following documentation:
https://thingsboard.io/docs/user-guide/rpc/#processing-the-client-side-rpc-by-the-platform
Could you provide more details about your problem in the new ticket if you still have any questions? Because I'll close this one as inactivity
