### ISSUE TITLE
[Bug] 无法访问com.github.os72.protobuf.dynamic.DynamicSchema

### ISSUE THREAD

**Issue by ligengithub** [thingsboard/thingsboard#5668]
**Describe the bug**
java: 无法访问com.github.os72.protobuf.dynamic.DynamicSchema
  错误的类文件: /D:/maven/apache-maven-3.6.3-bin/apache-maven-3.6.3/repository/org/thingsboard/protobuf-dynamic/1.0.3TB/protobuf-dynamic-1.0.3TB.jar!/com/github/os72/protobuf/dynamic/DynamicSchema.class
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * Windows

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mykhailokornieiev** [comment]
Hi ligengithub
Please let me know if your issue is still relevant. Perhaps you have already found a solution? If it's still relevant, please clarify your issue details and steps to reproduce it.
Best regards,
Mykhailo Kornieiev,
TechOps Engineer at Thingsboard
