### ISSUE TITLE
[Question] How can I assign firmware to device and device profile?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5669]
Hi,
I want to assign firmware for my device and device profiles in the attached pictures. But I want to use rest api and similar systems, not manually. When I examined the endpoints in the rest api, I did not encounter any such endpoints. Can you explain this issue with an example?
What is the difference between Firmware and Software assignment?
Can you provide a document or detailed explanation for me to understand the differences between firmware and software assignment in the device information section in the attached picture?

![Selection_006](https://user-images.githubusercontent.com/91528436/144412070-d05150e8-b37f-4203-9aea-26c6a37ea21c.png)![Selection_004](https://user-images.githubusercontent.com/91528436/144412109-ed86fc8c-aa38-4521-a0e2-142a8c84d6ee.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by ashvayka** [comment]
Please follow the official [documentation](https://thingsboard.io/docs/user-guide/ota-updates/). First, you need to create a firmware package that requires you to choose an applicable device profile. Afterward, you will be able to assign the package to the device profile.

**Comment by gohm-tech** [comment]
Hi @ashvayka,
Actually, we already followed this documentation and we ran it in our own application. But We wanted to assign firmware using REST-API. We found a way of how can we get firmware information to devices using REST-API.
[https://demo.thingsboard.io/swagger-ui/#/device-controller/saveDeviceUsingPOST](url)

We can assign **firmwareId** to device-profile using REST-API with help of this link.
[https://demo.thingsboard.io/swagger-ui/#/ota-package-controller/saveOtaPackageInfoUsingPOST](url)

We want to change **firmwareId** to a specific device using REST-API.

Best Regards,
**Gohm Team**

**Comment by gohm-tech** [comment]
Hi @ashvayka,

Thank you, We used this function and it is working.

Best Regards,
**Gohm Team**
