### ISSUE TITLE
Creation of Custom HTML Value Card Widget with multiple datasources

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5670]
Hello,
I am trying to create a widget similar to the HTML Value Card Widget but with multiple datasources.
For the moment I started with the original HTML Value Card Widget Code :
I just changed the maxDataSources value to 2 and the singleEntity to false inside the self.typeParameters function.
But when I use my custom widget, only the first datasource is taken into account.
I think that I have to modify/add more code inside my custom widget but I don't know where to start.

The goal of this widget is to be able to have two datasources : 
One for an entity which represents a Customer, and one for an entitycount which counts the number of assets contained in this customer.
Then I would display the customer info and this count on the widget.

Best regards,

Lucas

**Comment by ashvayka** [comment]
Have you found out how to do this?

**Comment by lucasKapf** [comment]
@ashvayka Yes it works, I just didn't "refresh" my custom widget when I was testing it.
I only changed the code as said in my first post.
