### ISSUE TITLE
[Question] OTA timeout

### ISSUE THREAD

**Issue by tobbelin** [thingsboard/thingsboard#5674]
**Component**

 * Generic

**Description**
I would like to set a timeout for OTA update. If an OTA update has not completed after x minutes set the job to failed.
Is there any best practice for this? Preferably not relying on action from the device, more like the state transfer from Queued -> Initiated.

**Comment by myroslav-tb** [comment]
Hi @tobbelin, when an OTA update is initiated, and Thingsboard cannot proceed with the update for some reason (device offline, bad connection, the device doesn't respond, etc.), Thingsboard makes several retry attempts before returning the status failed.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
