### ISSUE TITLE
Show device connection status on dashboard

### ISSUE THREAD

**Issue by kclauah** [thingsboard/thingsboard#5675]
**Component**
* UI
* MQTT API

**Description**
There are server attributes showing that whether device is last Connect ,last Disconnect and last activity. How can I show an indicator of whether device is online or offline on the dashboard?

**Environment**
 * OS: Raspberry PI 4
 * ThingsBoard: version 3.3.1
 * Browser: Firefox latest version

**Comment by Backdraft007** [comment]
Hi,
there is also the server attribute "active". You can use it. But be careful, depending on your configuration it can be possible, that the device is 10 minutes online later. This is when your device not disconnect correctly. That is the default timeout. Look here:
https://thingsboard.io/docs/user-guide/device-connectivity-status/

**Comment by kclauah** [comment]
Thank you for swift response. The "active" server attribute works fine on my device.
