### ISSUE TITLE
[Feature Request] memory requirements Kafka queue 

### ISSUE THREAD

**Issue by tomtobback** [thingsboard/thingsboard#5676]
The installation guide does not mention the large memory requirements for Kafka, 2GB seems insufficient.

I had been running Thingsboard CE v3.2.0 for over a year on an Ubuntu 18.04 server, with local PostgreSQL and in-memory queue. Resources: 1 vCPU and 2GB memory (Alibaba ECS). Average usage: CPU 1%, mem 55%, system load average 5. This load average is very high, but the system was stable for over a year, working well with only 5 active sensors and occasional web interface use.
I upgraded to v3.3.2 a few days ago, and the load average doubled to around 10, which got me worried. CPU was still < 5% and mem 55%, so it was not immediately clear to me why the system was so busy. I decided to replace the in-memory queue with Kafka, as recommended in the [installation docs](https://thingsboard.io/docs/user-guide/install/ubuntu/#step-4-choose-thingsboard-queue-service). This made the situation worse, with CPU up to 25% and mem 75%. Kafka crashed overnight. I upgraded from 1 vCPU to 2 vCPU, and this had a curious effect: CPU went up to 12% and load average down to 0.5; all seemed good. However, Kafka again crashed overnight due to the mem slowly increasing from 75% to 100% over 5 hours.
When i looked into the Kafka process, i noticed it is started with `java -Xmx1G -Xms1G` which seems to mean it requires 1G of memory? Also the Zookeeper process has `java -Xmx512M -Xms512M`. This of course creates problems on a 2GB system. I don't find any parameters in the thingsboard.yml to change these memory requirements, that could be a solution if it makes sense to run Kafka and Zookeeper with less memory. The `JAVA_OPTS` seem only to apply to the main thingsboard process?

I suggest to add a note in the [documentation](https://thingsboard.io/docs/user-guide/install/ubuntu/#step-4-choose-thingsboard-queue-service) that Kafka requires at least 4GB of memory. You may also add that running Thingsboard on a single core results in very high load averages.

I disabled Kafka/Zookeeper and went back to an in-memory queue, and that is running fine - below image shows the last 5 days:
* initial stable situation with v3.2.0, 1 vCPU, 2GB, load average 5
* upgrade to v3.3.2 increases load average to 10
* 'upgrade' to Kafka, crashing twice when mem increases from 75% to 100%
* upgrade to 2 vCPU, load average down to < 1
* current stable situation without Kafka, CPU 5%, mem 50%, load average 0.5

![monitor5days](https://user-images.githubusercontent.com/6690460/144564248-14474d42-e19a-4772-ba6b-e030dd0bb017.png)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
