### ISSUE TITLE
[logging] Error opening log file '/var/log/thingsboard/tb-core1/gc.log': No such file or directory

### ISSUE THREAD

**Issue by gdgzlxf** [thingsboard/thingsboard#5683]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version
[logging] Error opening log file '/var/log/thingsboard/tb-core1/gc.log': No such file or directory

**Comment by ashvayka** [comment]
The description is extremely insufficient. So I am closing this.

**Comment by gdgzlxf** [comment]
您好，我已经收到你的邮件，我会尽快回复您的邮件。

**Comment by a-sapuppo** [comment]
Starting ThingsBoard installation ...
[0.001s][error][logging] Error opening log file '/var/log/thingsboard/tb-core1-gc.log': Permission denied
[0.001s][error][logging] Initialization of output 'file=/var/log/thingsboard/tb-core1-gc.log' using options 'filecount=10,filesize=10M' failed.
Invalid -Xlog option '-Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/tb-core1-gc.log:time,uptime,level,tags:filecount=10,filesize=10M', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.``

**Comment by gdgzlxf** [comment]
您好，我已经收到你的邮件，我会尽快回复您的邮件。

**Comment by a-sapuppo** [comment]
```
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
```

same
