### ISSUE TITLE
[Question] securityHost/Port not stored in database when creating lwm2m device profile with PSK

### ISSUE THREAD

**Issue by liandimx** [thingsboard/thingsboard#5684]
**Component**

 * UI?
 * Generic?

**Description**

 I created a device profile with security mode as PSK on both Bootstrap and LwM2M server:

![tbq1](https://user-images.githubusercontent.com/39143992/144782553-1a8039b5-8bdb-47dc-a838-00504d3e10f3.PNG)

Then I created a device using above profile and set its credentials as following:

![tbq2](https://user-images.githubusercontent.com/39143992/144782842-224fea3f-5fff-43a1-9fb2-28b57a134ce8.PNG)

![tbq3](https://user-images.githubusercontent.com/39143992/144782877-e364d043-2e32-4ed3-984c-8dd8bf65a42c.PNG)

Then I used a leshan-client-demo to test the connection:

`java -jar ./leshan-client-demo.jar -n d1 -b -u localhost:5688 -i d1 -p 0123456789abcdef0123456789abcdef`

but the bootstrap process failed. I noticed these logs on the output of client:

```
...
   CaliforniumEndpointsManager 2021-12-06 10:59:14,345 [INFO] New endpoint created for server coaps://localhost:0 at coaps://0.0.0.0:65281
     DefaultRegistrationEngine 2021-12-06 10:59:14,345 [INFO] Trying to register to coaps://localhost:0 ...
...
```

Wondering why the client is using 'coaps://localhost:0' as server url, I looked into the database table 'device_profile',
and found there was no securityHost/Port attributes in the 'profile_data' column (only host/port):

```
...
    "bootstrap": {
      "servers": {
        "binding": "UQ",
        "shortId": 123,
        "lifetime": 300,
        "notifIfDisabled": true,
        "defaultMinPeriod": 1
      },
      "lwm2mServer": {
        "host": "0.0.0.0",
        "port": 5686,
        "serverId": 123,
        "securityMode": "PSK",
        "serverPublicKey": "",
        "clientHoldOffTime": 1,
        "bootstrapServerAccountTimeout": 0
      },
      "bootstrapServer": {
        "host": "0.0.0.0",
        "port": 5688,
        "serverId": 111,
        "securityMode": "PSK",
        "serverPublicKey": "",
        "clientHoldOffTime": 1,
        "bootstrapServerAccountTimeout": 0
      }
    },
...
```

If I manually add 'securityHost' and 'securityPort' attributes to above json data, the client bootstrap process will success.

So my question is : Have I done something wrong when creating the device profile?

Please give me some advice, thank you~

**Environment**

 * OS:  Microsoft Windows [Version 10.0.19042.1348]
 * ThingsBoard: branch release-3.3
 * Browser: Google Chrome Version 95.0.4638.69

**Comment by epalchenko** [comment]
Hello @liandimx,
You did not specify the correct host in the device profile in the LwM2M Server and Bootstrap Server settings. In yours, you need to specify 127.0.0.1 or localhost:
![Screenshot 2024-05-16 223953](https://github.com/thingsboard/thingsboard/assets/136599093/0ac1dd9c-72d3-4cee-9477-1fbc4598c4c0)
Please let me know if this has worked for you.

**Comment by epalchenko** [comment]
Hello,
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request.
