### ISSUE TITLE
[Bug] Does it works? (dashboards image)

### ISSUE THREAD

**Issue by Kullpoint** [thingsboard/thingsboard#5686]
![Знімок екрана 2021-12-06 о 10 08 37](https://user-images.githubusercontent.com/60100065/144810217-ea1ccd90-2549-4238-9638-21a4959b947b.png)
Does it works? I mean that i add an image to image field, but nothing happens and no instructions.
Position changing doesn't work to.

**Comment by vvlladd28** [comment]
Hi @Kullpoint,
This function is for Mobile App. Look here: [ThingBoard Mobile App Doc](https://thingsboard.io/docs/mobile/customize-dashboards/#dashboard-image)
