### ISSUE TITLE
[Bug] Im try to open html viewer in full screen, but nope)

### ISSUE THREAD

**Issue by Kullpoint** [thingsboard/thingsboard#5688]
![Знімок екрана 2021-12-06 о 16 00 39](https://user-images.githubusercontent.com/60100065/144860737-01b9b07f-fec5-4efc-8a96-d029f2ef5a4a.png)

Im trying to open html viewer in full screen, but instead i have  this.
Cache clearing doesn't help.
Web version PE

**Comment by ashvayka** [comment]
Please provide more details about where is this HTML viewer is located. This will improve resolution time.

**Comment by ashvayka** [comment]
Also provide your browser info (version, platform, etc)

**Comment by Kullpoint** [comment]
In all HTML cards;
Google Chrome 96.0.4664.93 (dev) (x86_64);

**Comment by vvlladd28** [comment]
Hi @Kullpoint,
What version of TB are you using?

**Comment by Kullpoint** [comment]
Web version PE

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
