### ISSUE TITLE
[Question] how to setup a staging environment in clustered mode - licence key conflict

### ISSUE THREAD

**Issue by ThomasPrioul** [thingsboard/thingsboard#5689]
**Component**
 * Installation

**Description**
I'm trying to setup a staging environment in my company to test changes for my tenants before applying them on the production environment.
Both environments are running TB PE 3.3.1 with hybrid storage (postgres+cassandra).
I want the staging environment to be a copy of the production environment data-wise, so I purchased another TB licence to run the staging environment, then tried to dump & restore the postgres database from the production instance on the staging instance.
However the production database somehow contains the licence information embedded in it.
Now my staging environment does not start and I have no idea how to reapply my 2nd license key while keeping the rest of the data.

How should I proceed ?

**Environment**
 * OS:  ubuntu
 * ThingsBoard: 3.3.1PE running on docker-compose

**Comment by ashvayka** [comment]
There is no license information in the database. All the license info is stored in the license.data file. Maybe you have copied the volumes (and not only the database). Then this is the root cause. Just
1) shut down dev TB instance
2) remove the license.data file
3) make sure the correct license key is used.
4) start it again.

**Comment by ThomasPrioul** [comment]
Thanks for your answer.
I had probably corrupted something else, my TB instance was not starting and I had no license.data file at all.
What I did was **remove the old instance from the license server**, reset everything and the staging instance came back to life.
I had not copied the volume, I did a SQL dump from the running postgres container in production.
