### ISSUE TITLE
tenant@thingsboard.org won't log 

### ISSUE THREAD

**Issue by mekaneeky** [thingsboard/thingsboard#569]
tenant@thingsboard.org won't log in to local install of thingsboard 1.3.1 on Win7 Ultimate x64 running Java 1.8.0_161 and Node.js version 8.9.4  from the website it gives me an Authentication failed error.
Note that install.bat resulted in these WARNS
log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB61726BCB2F.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by Firdauzfan** [comment]
if you install in windows, i think that try to login as sysadmin@thingsboard.ord and the password should be sysadmin
