### ISSUE TITLE
API Usage - Telemetry persistence hourly activity

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5691]
May I know how to interpret Telemetry persistence hourly activity chart in the API Usage page? In the screenshot below, the daily data points is around 10-15K, but the telemetry persistence is around 1.5-2.5M. 

![image](https://user-images.githubusercontent.com/17080208/144967221-6c3cd267-1f89-4484-888a-f25cfe568d7e.png)

**Comment by ashvayka** [comment]
The Telemetry persistence informs you how many "data point storage days" were used. Assuming you have 3 data points and you configure the "save timeseries" to store them for 100 days, you will have 3x100=300 data point storage days. 
See more info [here](https://thingsboard.io/products/paas/subscription/) (look for "Default storage TTL" and "Data point storage days").
