### ISSUE TITLE
[Bug] After Upgrade to TB 3.3.2 PE, Debug of Data Converter "In" show base64 coded message

### ISSUE THREAD

**Issue by holgerkoch** [thingsboard/thingsboard#5697]
We enable the debug mode of the converter an lock at the data incoming. So far we could see the payload here in json format. After the update to ThingsBoard 3.3.2 PE we only see the base64 encoded string.

**Your Server Environment**
* own setup
  * Installation on AWS with autoscaler and RDS PostgreSQL
  * ThingsBoard 3.3.2 PE (thingsboard-3.3.2PE-1.noarch)
  * Amazon Linux release 2 (Karoo)

**Your Client Environment**
* Windows 10
* Chrome 96.0.4664.45

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: AWS Core IoT

**To Reproduce**
1. Go to converter
2. aktivate Debug mode
3. wait for the next message
4. call the event tab and select debug, "IN"

**Expected behavior**
I wanna see the cleartext json like in previous versions

**Screenshots**

**Additional context**
After Update to TB 3.3.2 PE
![MicrosoftTeams-image_base64_encoded](https://user-images.githubusercontent.com/3931187/145072114-f427e42b-9adb-4876-9ec7-762483e40f2c.png)

Previous versions:
![MicrosoftTeams-image_json](https://user-images.githubusercontent.com/3931187/145072118-dcae734f-f304-4699-9538-4f2f3997762b.png)

**Comment by ashvayka** [comment]
Please share the information about the integration that created this input. In 3.3.2, we have improved the support of binary and text payloads for some integrations. Previously, the modal window was assuming that the payload is always JSON, but now we analyze the content type (from the HTTP or CoAP headers). The MQTT integration does not know is it JSON, text or binary data, so we always display it as binary. But, if you use "Test decoder function" in the converter, you may switch the content type manually and the input will be automatically converted.

**Comment by holgerkoch** [comment]
Hi,
i use the AWS IoT integration.
best regards

**Comment by nowherex** [comment]
Hi, I'm having the same problem after updating the thingsboard PE to v3.3.2, before update we could check MQTT and  Http integration data input in JSON format (example below), now all are displayed in base64 (data output is ok, no changes) but now we are not able to query the data entry as clearly as before.

As a temporary solution, I put the raw Payload in payload output with key "rawPayload", but I don't know how heavy it is for the database or if it affects something on the platform.

####  Example of output data (temporary solution) :
[{
     "deviceName": "DEVICE NAME",
     "deviceType": "DEVICE TYPE",
     "attributes": {
         "model": "TB01",
     },
     "telemetry": {
         "ts": 1638994679227,
         "values": {
             "temperature": 24,
             "battery": 3.2,
         }
     },
     "rawPayload": [{
         "channel": 91660000,
         "sf": 10,
         "time": "2021-12-06T10:41:45-03:00",
         "gwip": "MYSTRONGIP",
         "gwid": "000000000000",
         "repeater": "00000000ffffffff",
         "systype": 0,
         "lol": -39,
         "snr": 28.3,
         "snr_max": 35,
         "snr_min": 22.5,
         "macAddr": "aaaa05",
         "date": "00A738790f4a0100",
         "frameCnt": 315,
         "fport": 100,
         "devEUI": "0000000000000000"
     }]
}]


## In data Before Update:
![Before update](https://uploaddeimagens.com.br/images/003/577/163/original/before.jpg?1638994114)

## In data After Update:
![Before update](https://uploaddeimagens.com.br/images/003/577/160/original/after.jpg?1638994102)

**Comment by ashvayka** [comment]
Greetings, ThingsBoard Community! 

The issue you are facing is actually an improvement. I know it is hard to believe so, but it is :-). We have added "Support binary data consumption for HTTP/CoAP/MQTT integrations;" in v3.3.2. Before this release, the only supported format for many integrations as JSON. However, AWS and other integrations should support binary and simple text payloads as well. The AWS integrations that @holgerkoch is using are based on MQTT. We consume MQTT messages (v3.x) that do not have a content type. Technically, nothing is changed except the way the payload is displayed in the UI. 

To improve user experience, we will try to convert the binary payload to JSON in the UI part of the Data Converter/Integration Debug events table.
