### ISSUE TITLE
[Question] How can I Add Remote PostgreSQL Database?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5700]
Hi, I want to change the Thingsboard PostgreSQL database from local to remote. Therefore, I created a docker-compose.yml file in the following. Here, the remote PostgreSQL database has PostgreSQL and user permissions such as in the following.
version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      HTTP_BIND_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://xx.xxx.xxx:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: thingsboard
      SPRING_DATASOURCE_PASSWORD: thingsboard
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
However, I give an error in the following. How can I add a remote PostgreSQL database in Thingsboard?
mytb_1  | 2021-12-09 06:13:32,023 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "admin_settings" does not exist

**Comment by gohm-tech** [comment]
It should be run
docker run -it -p 8080:9090 -p 1883:1883 -p 5683:5683/udp --name tb --restart always -e SPRING_DATASOURCE_URL='jdbc:postgresql://*******:5432/things' -e SPRING_DATASOURCE_USERNAME='postgres' -e SPRING_DATASOURCE_PASSWORD='postgres' thingsboard/tb-postgres

**Comment by DEV-ONI** [comment]
I can't seem to get `thingsboard/tb-postgres` image to acknowledge these variables. 
```
SPRING_DATASOURCE_URL: jdbc:postgresql://xx.xxx.xxx:5432/thingsboard
SPRING_DATASOURCE_USERNAME: thingsboard
SPRING_DATASOURCE_PASSWORD: thingsboard
```
Did you do something else to get this to work?

**Comment by gohm-tech** [comment]
What kind of error you are getting?
