### ISSUE TITLE
[Bug] Rulechain Customer/Tenant Details Node - City Field not available in Dropdown

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#5701]
**Describe the bug**
In the Enrichment Node for Customer Details the information related to the customer's city is missing. All other fields are selectable except the city. The same behaviour is present for Tenant Details Node.

**Your Server Environment**
* ThingsBoard Version 3.3.2

**Expected behavior**
Add functionality to select city field for customer and tenant details nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/25298332/145377869-d8d26712-ecfa-488f-b542-61f2915c59a9.png)

![image](https://user-images.githubusercontent.com/25298332/145377909-a54328fa-9e03-4df1-86eb-ccbd61e73811.png)

**Comment by vvlladd28** [comment]
Hi @mde2017,
Thank you for your report. Coming soon added a fix in the master branch [thingsboard-rule-config-ui-ngx](https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/54)

**Comment by mde2017** [comment]
Hi @vvlladd28, 
thank you for replying & fixing the issue.
