### ISSUE TITLE
[Feature Request] Less confusion in case of last reading from offline device

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#5703]
In a last reading widget it will always show a value, it should be easily possible to see on the widget that it is a reading of an inactive device.

**Describe the solution you'd like**
- Make it possible to use more than one datasource in the widget to dynamically change it looks.
or
- Be able to set a time per widget before it should be grayed out
or 
- Make it grayed out when the device is not longer active. 

**Describe alternatives you've considered**
You can currently add the timestamp on the widget but it's not obvious, people don't read that.
Putting another widget next to it without value just background color with datasource = 'active' (obviously takes extra space and doesn't look nice)

**Additional context**
Easily understanding the current situation by looking at the dashboard, without having to check the 'fine print'

**Comment by JacksonBowe** [comment]
I've taken this approach

Maybe it can work for you as well
![image](https://user-images.githubusercontent.com/26427343/145482075-2824285e-0001-4e51-b4a8-e525fa0334ad.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
