### ISSUE TITLE
[Question] Issue with MQTT integration TB cloud 

### ISSUE THREAD

**Issue by Ccreevey** [thingsboard/thingsboard#5706]
Hello,

I am currently trying to add a new logger that has a different format for the MQTT to my Thingsboard Cloud but can not get my data to appear in the telemetry, eg(id/sensor/temperature/28) and the data is { "value": "28"}.  I made a data converter which outputs:

{
    "deviceName": "id",
    "deviceType": "thermostat",
    "telemetry": {
        "temperature": 28
    }
}

I was following the example since I was having trouble ThingsBoard PE: MQTT Integration Configuration Guide on youTube (https://www.youtube.com/watch?v=OPkE5FXGPrs) which is on a local sever from the video. I followed the video exactly, except the part were they use the command prompt and added in my access code as the video didn't need one. When I send the command C:\Program Files\mosquitto>mosquitto_pub -d -q 1 -h "mqtt.thingsboard.cloud" -p 1883 -t "sensors/Therm-A3/temperature" -u"****"  -m "{\"value\":28}" , no data is received by the device, no data in the data converter, or the integration. When testing the data converter with the same as the video the output I get is:

{
    "deviceName": "Therm-A3",
    "deviceType": "thermostat",
    "telemetry": {
        "temperature": 25
    },
    "attributes": {
        "integrationName": "Test integration"
    }
}

Any ideas on how to resolve this work be great,

Thank you,
Cameron

**Comment by myroslav-tb** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
