### ISSUE TITLE
Thingsboard Spring configuration - Spring facet

### ISSUE THREAD

**Issue by Ahrovan** [thingsboard/thingsboard#5711]
**After Import Thingsboard to IDEA - need to choose Spring facet**
How to choose? and need details about this step. 

**Environment**
 * ThingsBoard: 3.3.3
 
 
![Spring configuration check](https://user-images.githubusercontent.com/5772832/145669243-5e9ea800-472f-4313-aeec-e48c6b67a0ee.JPG)
![Spring facet](https://user-images.githubusercontent.com/5772832/145669255-703ea276-6062-4a1e-a0ec-b29914b811ef.JPG)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
