### ISSUE TITLE
[Question] How to resolve the thingsboard event log missing when having the same timestamp ?

### ISSUE THREAD

**Issue by lim-chris** [thingsboard/thingsboard#5714]
**Component**

 * UI

**Description**
Thingsboard event log missing when having two same timestamp event. For example, when two telemetry event is published to the thingsboard at the same ts: 1639106013029, then Thingsboard server might have just replaced the status of the latest one. Is there a way to keep all the data although it having the same ts ?

Telemetry:
Publishing to v1/devices/me/telemetry: { "ts": "1639106013029", "values": {"event": "2. Command dpkg-query -f '${binary:Package}\\n' -W completed, but will log instead to file: /var/lib/dispatcher/upload/dpkg-query_-f_'${binary:Package}\\n'_-W_10-12-2021-03:13:33"}}
Publishing to v1/devices/me/telemetry: { "ts": "1639106013029", "values": {"event": "3. SOTA Internally Running command: apt-get -yq upgrade"}}

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: v3.3.1-1
 * Browser: Chrome

**Comment by Nathan-ma** [comment]
Someone, please correct me ln this if I'm wrong but I think the TimeStamp is the unique key in the telemetry's table on the database.

If that's the case, the answer would be a no.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
