### ISSUE TITLE
Dashboard: switch controls send oneway REST request which finished with 504 code

### ISSUE THREAD

**Issue by amarkevich** [thingsboard/thingsboard#5717]
**Component**
 * UI / Rule Engine

**Description**
Round switch / Switch Control UI controls send oneway REST request. Root Rule Chain handle message type "RPC Request to Device" and try to handle following way
![image](https://user-images.githubusercontent.com/62415/145789135-8a5a46f1-a427-4d56-b006-603e03757ef7.png)
but there is 504 response in browser:

```
POST /api/rpc/oneway/bd601bf0-58da-11ec-8d54-3ffc24413577 HTTP/1.1
Host: thingsboard.company.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
X-Authorization: Bearer [real_token]
Content-Length: 68
Origin: http://thingsboard.company.com
DNT: 1
Connection: keep-alive
Referer: http://thingsboard.company.com/dashboardGroups/44ed1c10-30b0-11ec-b985-bf08606f72d5/11235e20-5730-11ec-8d54-3ffc24413577

{"method":"getValue","params":null,"persistent":false,"timeout":500}
```

```
HTTP/1.1 504 
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Content-Length: 0
Date: Mon, 13 Dec 2021 09:51:16 GMT
Via: 1.1 google

```

In result this error displayed on UI: 
![image](https://user-images.githubusercontent.com/62415/145790970-2777b925-7b80-49c4-a61c-00f998779f86.png)

How to avoid this behavior?

**Environment**
 * OS:  client: Windows 10 Enterprise 21H1 64-bit; server: docker@gke
 * ThingsBoard: 3.3.2PE
 * Browser: Firefox 95.0 (64-bit)

**Comment by tobbelin** [comment]
I also have a similar problem. Want to deal with the RPC calls in the rule engine using an REST call node.
My workaround now was to create my own widget and using deviceService sendOneWayRpcCommand. Then I just ignore the response. The response is then 505 after timeout.
Would love some more info about how the should work doing it right.

**Comment by NickDarvey** [comment]
I'm seeing this too. Is there a way we're supposed to acknowledge these messages so we don't get a 504 response?

**Comment by mykhailokornieiev** [comment]
Hi. For server-side RPC you need to use RPC Call Request rule node, not RPC Call Reply. Call Request will handle both request and reply for calls made from server. 
https://thingsboard.io/docs/user-guide/rpc/#using-the-rule-engine

**Comment by NickDarvey** [comment]
How does that work when we're using integrations to send downlink messages?

![image](https://github.com/user-attachments/assets/f8bde38c-e587-4b42-a0d2-521807415319)
