### ISSUE TITLE
Dashboard: switch controls send oneway REST request in case "Subscribe for attribute" configured

### ISSUE THREAD

**Issue by amarkevich** [thingsboard/thingsboard#5718]
**Component**
 * UI

**Description**
In case "Subscribe for attribute" no request expected.

**Environment**
 * OS: client: Windows 10 Enterprise 21H1 64-bit; server: docker@gke
 * ThingsBoard: 3.3.2PE
 * Browser: Firefox 95.0 (64-bit)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
