### ISSUE TITLE
[Bug] Upgrade from 3.1.1PE1 to 3.2PE failed 

### ISSUE THREAD

**Issue by doscon-git** [thingsboard/thingsboard#5720]
Trying to upgrade from version 3.1.1PE1 to 3.2PE fails. 

**Your Server Environment**
* own setup
  * thingsboard 3.1.1PE1
  * Ubuntu 20.04.1 LTS (Focal Fossa)

**Your Device**

**To Reproduce**
Followed these instructions
https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#ubuntucentos-32

**Screenshots**
During the upgrade i got the following error
![image](https://user-images.githubusercontent.com/54800452/145884762-2b1d7cf0-5010-4ae7-830b-bb5763ced512.png)

Got this warning when starting the service
![image](https://user-images.githubusercontent.com/54800452/145885058-29487245-2a55-4438-bb51-8bf2beb32a61.png)

And this is the status message of thingsboard (failure)
![image](https://user-images.githubusercontent.com/54800452/145885104-5125038b-153b-4001-815d-f2ffbf284a91.png)

**Additional context**

**Comment by SergMeleshko** [comment]
Hello @doscon-git 
Do you execute `systemctl demon-reload` after upgrade?

**Comment by doscon-git** [comment]
> Hello @doscon-git Do you execute `systemctl demon-reload` after upgrade?

Hi

Yes, i did do that. I also tried restarting the machine. Still got the same error.
