### ISSUE TITLE
[Feature Request] Add sw/fw_filename shared attribute in OTA

### ISSUE THREAD

**Issue by jlikeme** [thingsboard/thingsboard#5721]
**Is your feature request related to a problem? Please describe.**
We need install software depend on file type. Getting file type by filename is a fast way.

**Describe the solution you'd like**
Add `sw_filename`/`fw_filename` shared attribute for `Upload binary file` OTA mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by ashaforost** [comment]
Closing this issue as deprecated in favor of https://thingsboard.io/docs/pe/user-guide/ota-updates/
