### ISSUE TITLE
[Question]  The problem of not creating an alarm on thingsboard interface

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5724]
I tried logging in with both the tenant user and the user to create an alarm in the device profile. The telemetry filter alarms I created do not come even when the device reaches that threshold value. I can see the alarms when I create them with Rest Api. However, created alarm on the Thingsboard interface was not generated or not shown
![screencapture-dm-gohm-tr-19019-deviceProfiles-2021-12-14-10_32_40](https://user-images.githubusercontent.com/91528436/145954064-89c56d4a-a10b-423e-85b1-bcca8cd6bfd4.png)
![screencapture-dm-gohm-tr-19019-devices-2021-12-14-10_33_10](https://user-images.githubusercontent.com/91528436/145954078-97a44099-ad23-44f6-8c6d-657d85ee2eba.png).

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by JacksonBowe** [comment]
That device profile has a rule chain attached to it. In the rule chain, is there a "device profile" rule node? It should be RED. This is needs to be in the rule chain attached to a device profile.

**Comment by gohm-tech** [comment]
Hi @JacksonBowe,

The device profile rule node already exists in the rule chain. Also, the device profile is linked to the rule chain. Where else could this problem come from?

![screencapture-moli-gohm-tr-21013-ruleChains-c3191080-1148-11ec-8f56-4f4261e14c6c-2021-12-15-10_51_36](https://user-images.githubusercontent.com/91528436/147213062-166a862c-6460-4a5f-8487-8a67d1a7e8df.png)

Best Regards,
**Gohm Team**

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
