### ISSUE TITLE
Maps cluster expand feature is not working properly [Bug] 

### ISSUE THREAD

**Issue by irdet2** [thingsboard/thingsboard#5725]
**Describe the bug**
I am using OpenStreet maps to display assets on the map. In the past I was able when I was zooming or when I was clicking on a cluster to expand it and see all the assets. 
I have recently upgraded to TB 3.3.2 and this is not happening. Please see the attached pictures. 
Image 1.JPG is showing 3 clusters. 
Selecting one of them (doesn't really matter which one since it's the same behavior in all) and zooming in I cannot have it expand the last 4 assets that are on the same location. In the past this was possible and you could see all assets with connected lines in the same location.

**Your Server Environment**

* own setup
  * Docker deployment
  * ThingsBoard Version: 3.3.2
  * OS Name and Version: CentOS Linux release 8.5.2111 (fully updated)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows10/MacOS BigSur/MacOS Monterey
* Browser: All browsers are affected (Safari, Chrome, Firefox and Opera)
* Version: All of them are fully updated

**Smartphone (please complete the following information):**
* Device: iPhone12Pro/iPhone11/Pocophone F1
* OS: iOS 14. iOS 15, Android
* Browser:  Chrome, Safari
* Version: latest

**To Reproduce**
1. Create a few assets with same latitude and longitude and a few others in different coordinates
2. Put them on an OpenStreet maps widget
3. Watch the cluster on the map and try to zoom in
4. You will not be able to visually independently the assets that are on the same coordinates but you will always see a cluster for them

**Expected behavior**
It is expected to be able to expand the latest cluster and see individual assets

**Screenshots**
Have a look at the attached images
![1](https://user-images.githubusercontent.com/6882765/146013352-cd4a50e2-9a40-494a-b2bf-ede6ce65955b.JPG)
![2](https://user-images.githubusercontent.com/6882765/146013358-f8986832-8fba-4b66-849a-6e090c503188.JPG)

**Comment by JacksonBowe** [comment]
It's an intentional change. See issue #5597

**Comment by irdet2** [comment]
OK! I see! Thank you very much @JacksonBowe for pointing it out.

 Any ideas on which version this will be re-enabled ?

**Comment by JacksonBowe** [comment]
No clue. Hopefully in the next release. As in the issue I linked it's made the map widget unusable for many of my devices too :(

**Comment by irdet2** [comment]
Yeap! Mine as well! I have a lot of devices in the same location and not using the “spidery” (as it called) effect makes them unreadable on the map.

If they consider as next release the 3.3.3 then I guess we are close because 7hours ago the *-SNAPSHOT image was uploaded to Docker Hub. If not then I really don’t know how we can mitigate this ….

**Comment by irdet2** [comment]
Hi @JacksonBowe, I just wanted to let you know that if I am not mistaken the change we were talking has already been merged to the master branch with PR #5616 and is in the following line:
https://github.com/thingsboard/thingsboard/blob/cf2d8c6888324a2b6fdfbec4371a24aa587b2d55/ui-ngx/src/app/modules/home/components/widget/lib/maps/map-models.ts#L60

**Comment by thhart** [comment]
Any chance to receive the snapshot release as package somewhere?

**Comment by vvlladd28** [comment]
A new version is scheduled for release this month.

**Comment by thhart** [comment]
I tested with 3.3.3 and it is working. Thanks.
