### ISSUE TITLE
Timeseries Bar and Line Chart show wrong data[Bug] 

### ISSUE THREAD

**Issue by DerGue69** [thingsboard/thingsboard#5727]
**Describe the bug**
After Update from 3.2.2 through to 3.3.2 some of my Timeseries Bar and Line Charts show wrong data, but only for new data.
I was able to isolate the problem: The Data Aggregation Function "Max" is showing wrong Values. When switching for example to "Average" data seems to be correct.

When looking at the Device and it's latest telemetry, the values appear correct here.
Even when I create a gauge an display the value there, everything is correct.

Only when I use timeseries Charts with aggregation "Max" data is much too low. Data before the update from 3.2.2-3.3.2 is shown correctly.

**Your Server Environment**
Ubuntu 18.04.4 LTS
Thingsboard 3.3.2
psql (12.9 (Ubuntu 12.9-1.pgdg18.04+1))

**Your Client Environment**
Chrome Version 96.0.4664.93  on Windows 10.

**Smartphone (please complete the following information):**
Samsung Galaxy A52 - Chrome

**Your Device**
I feed data with a http Post through Node-Red.
Data is coming from my Solar Inverter. for example how many kWh of energy I used in this day: 4.80619999999999

**To Reproduce**
Steps to reproduce the behaviour:
1. Update from 3.2.2 to 3.3.2
2. Go to a timeseries Bar or Line Chart
3. Click on Edit Time window, Choose Data Aggregation MAX and for example grouping interval 1 Day
4. See that data after update to 3.3.2 is being displayed wrong.

**Expected behaviour**
The MAX Data Aggregation grouped by 1 day shall deliver the biggest value for this dataset of this day. 

**Screenshots**
As you see, something is wrong....Average is higher as MAX. But only after my update on 11.Dec,

Data Aggregation MAX - Grouped by 1 day, last 20 days:
![image](https://user-images.githubusercontent.com/96002277/146155110-2d5ce9db-5922-42b5-9e7e-f3742f52e89a.png)

![image](https://user-images.githubusercontent.com/96002277/146154713-1d717f38-2519-4fe3-80a8-d67900b284c4.png)

Data Aggregation Average - Grouped by 1 day, last 20 days.
![image](https://user-images.githubusercontent.com/96002277/146155054-89e18e72-d379-4692-9e07-3a84505684a9.png)

![image](https://user-images.githubusercontent.com/96002277/146154810-a1844ca1-37e3-4f09-82e3-d48982996c90.png)

**Additional context**
I love Thingsboard - please fix the BUG in an upcoming Version.
Greetings from Austria - Vienna!

**Comment by Kullpoint** [comment]
Hi DerGue69! Do your widget just bigger.

**Comment by DerGue69** [comment]
This is bigger...Fullscreen.
10. Dec I charged by car, therefore there is this big number. But afterwards something is wrong.
![image](https://user-images.githubusercontent.com/96002277/147543215-7d4f6c68-3690-48ef-a8f3-bb99e398fa2a.png)

**Comment by Kullpoint** [comment]
Same...
[](url
![Знімок екрана 2021-12-28 о 10 23 22](https://user-images.githubusercontent.com/60100065/147545279-91ad83f8-a1aa-47dd-a604-73855be6e831.png)
)

**Comment by DerGue69** [comment]
Grouping Interval MAX shows way smaller values than Average.
This is not a normal behaviour.

![image](https://user-images.githubusercontent.com/96002277/147549081-77d72af8-b256-4f78-962a-dd15fcde40a6.png)

![image](https://user-images.githubusercontent.com/96002277/147549127-e9683254-084d-42b6-ae92-c642cca48d87.png)

**Comment by DerGue69** [comment]
I think I found what is causing the problem:

Like I mentioned I am feeding Thingsboard through NodeRed which calculates some values.
And the values have lots of decimal places. Example 4.80619999999999

Now I changed my rawdata to only 2 decimal places (example 4.81) . And I the bar and line charts are showing the correct values again.

I still think that there is a bug somewhere in your routines.

**Comment by ianog-eng** [comment]
I am also having this problem, with all aggregation functions except Count. Below is a summary, I also have the actual data in #5819  It definitely seems to be related to the precision of the data

![Screenshot 2022-01-06 134533 Summary](https://user-images.githubusercontent.com/84106368/148378966-dd489e0a-a10b-439e-95c6-b707f89872c6.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
