### ISSUE TITLE
Samples Build Failure Demo Loader

### ISSUE THREAD

**Issue by CristianMendivelso** [thingsboard/thingsboard#573]
![image](https://user-images.githubusercontent.com/22376509/35988996-0427f09c-0cce-11e8-845a-783d68528bca.png)
I have problems with the maven dependencies in https://github.com/thingsboard/samples project

**Comment by vparomskiy** [comment]
Not actual anymore. Closing

**Comment by nvellal** [comment]
Any idea as to how this was solved? I am trying to build the samples projects. I already successfully built Thingsboard from source.

NV
