### ISSUE TITLE
[Bug] Dont cahnge value in shared attributes

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#5731]
**Describe the bug**
Hello,
Using the "update multiple attributes" widget to modify shared attributes, when I want to modify the attributes it does not change the value but rather creates a new variable in "server attributes".
This appears to be a bug

**Your Server Environment**

* own setup
  * local
  * 3.3.1 PE
  * WS 10 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [Windows 10]
* Browser [chrome]
* Version [3.3.1 PE]

**Your Device**

* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78015483/146186490-bab0015a-d722-4934-8820-1447c7aa7c51.png)

I put the shared attributes
![image](https://user-images.githubusercontent.com/78015483/146186663-54c6f5f4-6bc0-40fe-9767-c4fd054443be.png)
![image](https://user-images.githubusercontent.com/78015483/146186516-ea90e111-71a0-4d31-9149-628ccf3e3b8e.png)

Variable in server attributes
![image](https://user-images.githubusercontent.com/78015483/146186564-45ad741c-5ec4-4504-94de-19a7a3b78057.png)

**Additional context**

**Comment by ChantsovaEkaterina** [comment]
Hello, @AbrahamSalvi 
Have you changed the data key type to 'Shared attribute' in the advanced data key settings for attributes that should be saved as shared?
![image](https://user-images.githubusercontent.com/17936317/146222817-fde35ea3-6944-4655-bc2b-37e9871b7e54.png)

**Comment by AbrahamSalvi** [comment]
Nice !! Now it works!
Thanks a lot @ChantsovaEkaterina 

Good job
