### ISSUE TITLE
[Bug]  We are having trouble fetching dashboard information with Python tb rest client. How can we fix it?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5732]
We can view the dashboard information without any errors by querying it via the swager rest api. We can even display the response directly on the "api/dashboard/{dashboardId}" address without any problem with http request. Our problem is that we want to use python tb_rest_client for this operation. we are receiving. While debugging this situation, we realized that it is related to the tb_rest_client source code. Can you please help us with this?
[swagger_dashboard_Response.txt](https://github.com/thingsboard/thingsboard/files/7719620/swagger_dashboard_Response.txt)
![Selection_003](https://user-images.githubusercontent.com/91528436/146194004-dd11918a-5d53-440d-b6fc-38a7c00c4c79.png)
![Selection_002](https://user-images.githubusercontent.com/91528436/146194010-36fbf6ca-2876-4455-9aa3-bc0a6efb7a08.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by samson0v** [comment]
Hi @gohm-tech, it seems that you are using old version of rest client, please, install it from master branch and use the next code example:
```python
with RestClientPE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password)
        user = rest_client.get_user()
        dashboard = rest_client.get_dashboard_by_id(
            DashboardId('DASHBOARD', 'f99de770-282c-11ec-a9e6-556e8dbef35c'))
        print(dashboard)
    except ApiException as e:
        logging.exception(e)
```

Result:
<img width="427" alt="зображення" src="https://user-images.githubusercontent.com/43861229/146377261-707d7e82-1b33-4f97-ac28-9f918ecea0f7.png">

Thanks for your interest in Python ThingsBoard Rest Client!

**Comment by gohm-tech** [comment]
Hi @samson0v,

Our commıtId is **d303096a**. I think it is already new version. We are using a Comunity Edition. This functionalty (get_dashboard_by_id) is supporting by community edition.

Best Regards,
**Gohm Team**

**Comment by samson0v** [comment]
Hi @gohm-tech, we haven't had any issue with using this method via the Community Edition version. Anyway, I think on Monday we will release the [new version](https://github.com/thingsboard/thingsboard-python-rest-client/pull/42) of Python Rest Client, so you can try one more time to use it.
Thanks!
