### ISSUE TITLE
[Feature Request] Mac M1 (ARM core) build earlier version, such as 3.1.1 , should change protobuf version to higher.

### ISSUE THREAD

**Issue by jiekechoo** [thingsboard/thingsboard#5734]
In pom.xml file, change 

- protobuf.version from **3.11.4** to **3.17.3**, it works fine.
- io.grpc:protoc-gen-grpc-java:**1.0.0** to **1.43.0** 

because there is no older version osx-aarch64 file in maven repository.

**Comment by jiekechoo** [comment]
and nodeVersion should be new version of V16.*.* in ui-ngx/pom.xml

**Comment by Ultrazombie** [comment]
Closed due to inactivity
