### ISSUE TITLE
[Feature Request] Thingsboard Helm Chart

### ISSUE THREAD

**Issue by JonasRueck** [thingsboard/thingsboard#5735]
Hey there,

currently there is no helm chart for thingsboard. I've found the following issue which is still open, but sadly no progress.

https://github.com/thingsboard/thingsboard/issues/3741

Configuration, upgrade and deletion of thingsboard resources would be way easier on kubernets with a helm chart.

Thank you!

**Comment by midokura-agustin** [comment]
Hi, I just submitted a PR to add helm support: https://github.com/thingsboard/thingsboard-ce-k8s/pull/59

Let me know what you thing about it

**Comment by midokura-agustin** [comment]
PR merged!
https://github.com/thingsboard/thingsboard-ce-k8s/pull/59
Thanks @ikulikov
