### ISSUE TITLE
[Question] Want widget to generate action in Rulechain

### ISSUE THREAD

**Issue by purplehorace** [thingsboard/thingsboard#5736]
**Component**

 * UI
 * Rule Engine

**Description**
I have created a widget, very simple push button that I want to start some events to perform a rest api call using the Rulechain node.
Trying to understand how I can create the event/signal/message that will be sent from the widget button to the Rulechain input where I can then action the rest-api-call.

Currently the button is generating a custom action to log to the console to validate the click.
How can I get the button click event into the Rulechain.

Any help appreciated.

Thank you.

**Environment**
 * ThingsBoard: 3.3.1 CE
 * Browser: Chrome and Edge

**Comment by Raven888888** [comment]
Looking for the same too. Bump

**Comment by dhaval2017** [comment]
@Raven888888 
When You update server attribute inside custom widget
You will get event on rule chain 
If you like you can store that value else ignore it

**Comment by Raven888888** [comment]
@dhaval2017 thanks for your quick response
 got it now

**Comment by purplehorace** [comment]
yes also managed to get that to work. thank you.
