### ISSUE TITLE
[Question] MQTT-Subscription failed

### ISSUE THREAD

**Issue by m4ld3** [thingsboard/thingsboard#5742]
**MQTT Subscribtion**

 * Subscription the the TB-broker with mqtt/Java (Paho)

**Description**
Hi,
I have some trouble in subscribing at the topic v1/devices/me/telemetry. I have no problems in subscribing on v1/devices/me/**attributes** There I can get new attributes when I post them in the UI. So my Java-Program seems to runs fine (see bottom).

I get the following at the console:

_Subscriber running
checking
Mqtt Connecting to broker: tcp://192.168.1.25:1883
Mqtt Connected
MqttException (128)
MqttException (128)
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:438)
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:406)
	at Test.MqttSubscriber.subscribe(MqttSubscriber.java:57)
	at Test.MqttSubscriber.main(MqttSubscriber.java:30)_

I guess that Error Code 128 means that the subscription was pulled back.

What am I doing wrong? Publishing content to thingsboard at that topic is no problem. Do I have to activate the broker somehow? Or do I have to realise it with the IoT gateway? 

I hope someone can help :)

**Environment**

 * OS:  win10 and ubuntu
 * ThingsBoard: CE and PE
 * Browser: name and version

`       package Test;

        import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
        import org.eclipse.paho.client.mqttv3.MqttCallback;
        import org.eclipse.paho.client.mqttv3.MqttClient;
        import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
        import org.eclipse.paho.client.mqttv3.MqttException;
        import org.eclipse.paho.client.mqttv3.MqttMessage;
        import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;
        
        public class MqttSubscriber implements MqttCallback  {

	
	private static final String brokerUrl ="tcp://192.168.1.25:1883"; //Broker

	
	private static final String clientId = "test"; //Client-ID

	
	private static final String topic = "v1/devices/me/telemetry"; //Topic
	
	private static final String user = "AT2"; // Accesstoken von Device in TB!
	
	private static final String pw = "test";
	
	private static final char[] password = pw.toCharArray();

	public static void main(String[] args) {

		System.out.println("Subscriber running");
		new MqttSubscriber().subscribe(topic);
	}

	public void subscribe(String topic) {
	
		MemoryPersistence persistence = new MemoryPersistence();

		try
		{

			MqttClient sampleClient = new MqttClient(brokerUrl, clientId, persistence);
			MqttConnectOptions connOpts = new MqttConnectOptions();
			
			
			
			connOpts.setCleanSession(true);
			connOpts.setUserName(user);
			connOpts.setPassword(password);

			System.out.println("checking");
			System.out.println("Mqtt Connecting to broker: " + brokerUrl);

			sampleClient.connect(connOpts);
			if (sampleClient.isConnected()==true) System.out.println("Mqtt Connected");
			else System.out.println("could not connect");

			sampleClient.setCallback(this);
			sampleClient.subscribe(topic);
			
			
			

			System.out.println("Subscribed");
			System.out.println("Listening");

		} catch (MqttException me) {
			System.out.println(me);
			me.printStackTrace();
		}
	}

	 //Called when the client lost the connection to the broker
	public void connectionLost(Throwable arg0) {
		
	}

	//Called when a outgoing publish is complete
	public void deliveryComplete(IMqttDeliveryToken arg0) {

	}

	public void messageArrived(String topic, MqttMessage message) throws Exception {

		
		System.out.println("| Topic:" + topic);
		System.out.println("| Message: " +message.toString());
		System.out.println("-------------------------------------------------");
	
	}

}`

**Comment by GeirFrimann** [comment]
Try changing sampleClient.setCallback(this) to sampleClient.setCallback(messageArrived)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
