### ISSUE TITLE
[Bug] We get an error after a certain time after the widget is created on the dashboard

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5746]
We are getting an error in the graphics in the dashboard that we have created in the attached picture. It is an error that we get from time to time without using the rest api and similar changes other than the thingsboard. The only part that is intervened by us as a change is to define the data source for the widget. Is there a solution for this bug?
![Selection_005](https://user-images.githubusercontent.com/91528436/146757593-ce41e79e-865a-441c-a577-ad0b4c648d81.png)
![Selection_004](https://user-images.githubusercontent.com/91528436/146757596-ace2f999-0add-4163-9ce9-8e62e88a18b7.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by ashaforost** [comment]
I'm closing this issue as inactive. If you experience similar issues on the latest thingsboard version, feel free to create a new github issue.
