### ISSUE TITLE
Thingsboard server not getting connected in http://[server-ip]:8080

### ISSUE THREAD

**Issue by desuryan** [thingsboard/thingsboard#575]
After successful installation of thingsboard application, it's not possible to access the server in http://127.0.0.1:8080. It shows a dialogue as "Server refused to Connect".
As precondition the thingsboard is already started and running.
Here the database connectivity is through PostGre SQL.
The OS is Windows 10 -P.
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/1710060/thingsboard.log)

**Comment by vparomskiy** [comment]
From your log file:
```
Application startup failed
Error creating bean with name 'MqttTransportService': Invocation of init method failed; nested exception is java.net.BindException: Address already in use: bind
```
MQTT transport could not start because port is already used by another process

**Comment by dinukasal** [comment]
I got the same error, Please help me to fix the issue. Log file is attached below.
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2143593/thingsboard.log)

Thanks.
