### ISSUE TITLE
[Question] if possible assign a device profile to customer then customer can got all device  permission  ?

### ISSUE THREAD

**Issue by icoco** [thingsboard/thingsboard#5756]
about  "Manage device" in  "Customers' module, 

    
if possible assign a device profile to customer then customer can got all device  permission  ?

currently, administrator have to add device one by one, that  waste much time

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request.
