### ISSUE TITLE
Timeseries Graphs - Max number of values capped to 500

### ISSUE THREAD

**Issue by saurabhjhamb** [thingsboard/thingsboard#576]
Folks - I am unable to set a value > 500 of max values in Timeseries graphs when NO aggregation is selected. Current version I am using is 1.3.1, I was able to manually insert a higher value in 1.3.0.

Could you please check if this is an issue or there's a workaround?

**Comment by ALovedOne** [comment]
I'm also not able to get more than 500 points to display on 1.4 - kind of hard to make useful graphs for data collect ~1 per minute.

**Comment by Ultrazombie** [comment]
Close ticket. can't reproduce on the latest version
