### ISSUE TITLE
Edit device label in Dashboard

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5763]
In Update Multiple Attributes dashboard widget, I can add device label to display it. However, when I try to edit the label from dashboard, a server attribute "label" is added. The device's label is not changed. How to change the device label in the dashboard?

**Comment by vvlladd28** [comment]
Hi @sunyong-mwi,
Update Multiple Attributes dashboard widget, not support update entity fields "label." 
You can create a custom widget action to update the entity field "label."

**Comment by sunyong-mwi** [comment]
May I know how to create custom widget to update "label"? Is there any sample to follow?

**Comment by sunyong-mwi** [comment]
Any update?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
