### ISSUE TITLE
[Feature Request] Add description/purpose field to subscriptions in license portal

### ISSUE THREAD

**Issue by poelstra-sioux** [thingsboard/thingsboard#5767]
**Is your feature request related to a problem? Please describe.**
In the ThingsBoard license portal, we have quite a few subscriptions, and we'd like to know whether some of them are really necessary still.

**Describe the solution you'd like**
Add an additional column to the overview that I can fill in with a short description of that subscription's purpose/location.

**Describe alternatives you've considered**
Keeping a separate list in Excel, using the create timestamp as the key...

**Comment by ashvayka** [comment]
@YevhenBondarenko , please add this feature. It is a valid feature request.

**Comment by ssakharova** [comment]
Hello @poelstra-sioux, 
Thank you for taking the time to contact us. Right now, we do not have this feature available, but the good news is that we have already started working on that feature, and it will be available in one of our upcoming releases.
