### ISSUE TITLE
Gateway Device Relations

### ISSUE THREAD

**Issue by innoagg** [thingsboard/thingsboard#577]
It would be beneficial if the gateway -> device relation that is automatically added when a device is created through a gateway could be maintain for any gateway that makes contact with a device. 

In our case our devices "Roam" and come in contact with multiple gateways and we would like to see this represented in the data.

**Comment by LeoMorgan113** [comment]
Hi @innoagg,

This feature is presented in the latest releases.
Please, keep up to update: https://thingsboard.io/docs/reference/releases/
