### ISSUE TITLE
How do i remove the debug data from my database?

### ISSUE THREAD

**Issue by Zangetu121345** [thingsboard/thingsboard#5779]
I accidentally kept my debug data ON in one of my rule node and now the database is full. Can anyone tell me how do i remove the debug data from database?
If i remove that node again will it remove the debug data from the database?

**Comment by mde2017** [comment]
Hi @Pankaj9410557422,

the debug data is stored in the "event" PostgreSQL table. 
You could consider truncating the table to remove the debug data.

If you only remove the node, the data would be still present in the database afterwards.

**Comment by kxiopl** [comment]
Is there an easy way to do from the Thingsboard UI itself ? Or should there be one in the future ?

**Comment by mde2017** [comment]
Hi @kxiopl,

as far as I know, there is no way to do this via ThingsBoard UI. 
I don't know if this in the backlog for future versions.

Another approach could be setting TTL (Time to Live) configs for debug events:
![image](https://user-images.githubusercontent.com/25298332/148024171-96d19a02-6338-4510-8a4a-f8d94f876584.png)
https://thingsboard.io/docs/pe/user-guide/install/config/

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
