### ISSUE TITLE
Same sensor data pushed from different (gateway) device

### ISSUE THREAD

**Issue by m-menon** [thingsboard/thingsboard#578]
hi,, firstly thanks for the wonderful ThingsBoard. It is cool! Recently started on Thingsboard and I need some advice on this scenario that I am facing. I have a bunch of Bluetooth beacons from which I am collecting data using a few Raspberry Pi gateways. These gateways are authenticated by the access token ( as explained in getting started tutorials ). Now these beacons as they are moved around, will come in proximity of another gateway which collects and posts the data to ThingsBoard. So on the ThingsBoard side how do I set this up where the sensor data ( json dumps ) can come from different devices ( gateways )? I have 4 gateways set up and I can add widgets but I need to choose the entity/gateway. So in short the same beacon data can be posted by either Device A, Device B or Device C .. or even Device D. All these devices A, B, C and D use access tokens. Thanks.. Cheers

**Comment by m-menon** [comment]
Is this going nowhere? I think this is a common scenario that people will encounter.

**Comment by mp-loki** [comment]
Hi @m-menon! 
The ThingsBoard Gateway provisions devices to ThingsBoard, so the telemetry is collected by a Device entity, not a Gateway entity. [This example](https://thingsboard.io/docs/iot-gateway/mqtt/) describes how to set up a gateway and send the telemetry to a device named 'SN-001'. The trick is that in that scenario the device publishes data to 'sensor/SN-001/temperature' topic on the mqtt broker, Gateway subscribes to this topic and sends data to ThingsBoard. on ThingsBoard data is displayed under SN-001 device. You can easily modify this scenario by, say, you have two MQTT brokers A and B and two gateways  - Gateway A and Gateway B, each subscribed to a corresponding topic. The device SN-001 can publish telemetry to either A or B, but use the same topic, say 'sensor/SN-001/temperature' (as in the example). In this case, both  Gateway A and Gateway B will collect the data and publish it to the same SN-001 device in TB.

**Comment by m-menon** [comment]
hi, cool thanks. I am getting a hang of it but I think I may not have explained it clearly.  Let me break it into clearer steps.

I have 2 gateways ( raspberry Pi ), and 3 bluetooth beacons. The gateways themselves send some attribute/telemetry data about themselves. The gateways authenticate by access tokens. The data that is sent by the gateway follows this format
Gateway A
`{"gwA.mac": xx:xx:xx:xx:xx:xx, "gwA.battery": xx, "gwA.cpu": xx}`
Gateway B
`{"gwB.mac": xx:xx:xx:xx:xx:xx, "gwB.battery": xx, "gwB.cpu": xx}`
The mac is used as an attribute and battery and cpu as time series. I am able to easily visualize this on a card widget on Thingboard.

Now comes the part of the bluetooth beacons. The beacons may be within the vicinity of either Gateway A or Gateway B. So either Gateway A may read the data from the beacon, or Gateway B may read the data from the beacon. Once read, the respective gateway will post the data to the Thingsboard server ( using mqtt). The (beacon) data posted on to the thingsboard server follows this format
```
{"bcn01.mac": xx:xx:xx:xx:xx:xx, "bcn01.battery": xx, "bcn01.temperature": xx}
{"bcn02.mac": xx:xx:xx:xx:xx:xx, "bcn02.battery": xx, "bcn02.temperature": xx}
{"bcn03.mac": xx:xx:xx:xx:xx:xx, "bcn03.battery": xx, "bcn03.temperature": xx}
```

Here too the data is getting posted ( through any one of the gateways ) but I confused on the visualization part of the above beacon data. For gateways I have checked the option "Is Gateway" to true.
![add_new_device](https://user-images.githubusercontent.com/10776430/36343289-5069699e-1445-11e8-9b4d-492e393c0f50.jpg)



I am using Thingsboard 1.3.1

**Comment by m-menon** [comment]
This is where I am a little stuck - resolve as multiple entities, entity list etc. This part I think tends to get a little confusing.

![add_new_device_1](https://user-images.githubusercontent.com/10776430/36343728-bde0dba6-144a-11e8-8db0-9f2f24ebcb43.jpg)

**Comment by m-menon** [comment]
It's this part that I am getting stuck at. I am separating the beacon data with numbers like bcn000001.temperature, bcn000001.time etc but it locks it down to a single entity ( gateway ). If it's a single beacon and single gateway, It's all fine. But here the same beacon data can be captured by any one of the gateways and posted on the server. I have set up 4 different gateways devices ( each with it's own access token ).

![same_sensor_data_from_different_gateway](https://user-images.githubusercontent.com/10776430/36349455-693a6216-14c2-11e8-8721-785236acbc69.jpg)

**Comment by m-menon** [comment]
I am not sending anything back to the gateway ( Raspberry Pi ), or the beacons from the Thingsboard Server. It should't be so complicated. When I create a new entity ( by choosing entity list ), it shows up as gateway + sensor, gateway + sensor, gateway + sensor, gateway + sensor ( 4 times, because there are 4 gateways ). If I add the individual beacon as a device, then I would need to authenticate ( using access token ). This is not possible because the beacons can't post the data themselves - it has to come through one of the gateways.

**Comment by m-menon** [comment]
haha, I have seen others ask very similar question on Stackoverflow. Something fundamental like this shouldn't be so difficult. No point in have a hundred pages of documentation without a clear explanation of most basic steps towards setting up an IoT backend/dashboard. All I wanted to do is to display the same sensor data ( say Sensor A ) coming from any one of the client devices, to show on the same widget. If I choose single entity, the widget won't update if the data comes from other device. If I choose entity list, and turn on "Resolve as multiple entities", then I end up with the widget showing all the devices.

![same_sensor_data_from_different_gateway_2](https://user-images.githubusercontent.com/10776430/36352353-ae4347bc-14f2-11e8-8def-e623fa348580.jpg)

**Comment by m-menon** [comment]
I get it, "Gateway" doesn't mean a device that collects data and posts it to the thingsboard server, even though technically and logically it is still a gateway. I need to install thingsboard gateway on my gateway device, and then have it collect/send the sensor data. Thanks anyways.

**Comment by blinkomaniak** [comment]
@m-menon can you please leave your email, I would like to get in contact with you to buy some of your knowledge regarding this issue. I want to implement geolocation algorithms using TDoA with LoRaWAN and show the position using ThingsBoards Map widgets. My LoRaWAN gateways send the LoRaWAN packets that receive from multiple nodes to an MQTT Broker (CloudMQTT), all gateways use the same topic (gateway/geoloc) to send the data. Then, I have setup 01 integration at ThingsBoard PE that subscribes to the MQTT Broker to that particular topic, so it gets the messages that the gateways publish at the MQTT Broker, but it only creates 01 virtual device per node. Maybe, I need to add little bit more complex logic to the data converter so it can create devices with the name [Gateway ID + Device Address] in such way that at ThingsBoard, it creates various virtual devices instead of only 01, but I would like to have a more experienced point of view as yours. I hope you can help me. Thanks in advance,

**Comment by m-menon** [comment]
@blinkomaniak it's been a long time since I did that project. I haven't explored Thingsboard lately but feature-wise they seem to have added many more features. Unfortunately I don't have any experience of working on Thingsboard lately and so I might not be able to help much. Also I am in the midst of some urgent things and I am kinda tight on time.

Btw have you had a look at [this](https://thingsboard.io/docs/reference/gateway-mqtt-api/)? This gateway can act like a bridge; it allows for exchange of data between multiple devices and the platform using a single MQTT connection. Cheers
