### ISSUE TITLE
[Question] Thingsboard with PostgreSQL + TimescaleDB

### ISSUE THREAD

**Issue by cvhoangpt** [thingsboard/thingsboard#5781]
**Component**

 * Installation

**Description**
One month ago, my thingsboard configuration is set to PostgreSQL and Cassandra, all fine. But when I set DB to PostgreSQL with TimescaleDB, thingsboard said that ts_kv is missing (relation ts_kv is missing). I query this .sql (https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/sql/schema-timescale.sql), it works fine.
Why does this error occur? Why Thingsboard do not update database to match with TimescaleDB?

**Environment**

 * OS:  CentOS 7
 * ThingsBoard: version 3.2.2

**Comment by trikimiki** [comment]
In case you switch database type, you need to install database schema first. There is no check in the ThingsBoard whether the DB type was "switched" in the configuration.
Database schema is installed with install script, e.g. https://thingsboard.io/docs/user-guide/install/ubuntu/#step-6-run-installation-script . But this script also installs entity schema alongside with timeseries schema, so the best way to install timeseries schema after new DB type switch is as you did - run some-file.sql query from here https://github.com/thingsboard/thingsboard/tree/master/dao/src/main/resources .
