### ISSUE TITLE
Accessing Postgres DB on Docker in CE 

### ISSUE THREAD

**Issue by Mark19888** [thingsboard/thingsboard#5782]
Hi There,

As per title, I'm running CE in Docker using Kafka / Postgres and I'm struggling to access the latter even after exposing the 5432 port in the yaml file. I'm using the login reported in Portainer under the relevant env variables but without any luck... Any ideas why that is and what I'm doing wrong? 

Thanks,
Mark

![image](https://user-images.githubusercontent.com/96733753/147490322-0af7510c-92ef-491d-880d-b38fbb725b81.png)

**Comment by ashvayka** [comment]
Do you use Docker or Docker compose? Please provide a command you use to launch all components?

**Comment by Mark19888** [comment]
I'm using docker desktop and I'm simply following your documentation - maybe I'm doing something wrong but I'm pretty good with docker - link to documentation and yaml below.

Thanks,
M

**https://thingsboard.io/docs/user-guide/install/docker-windows/?ubuntuThingsboardQueue=kafka**

_version: '2.2'
services:
  zookeeper:
    restart: always
    image: "zookeeper:3.5"
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
  kafka:
    restart: always
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    depends_on:
      - kafka
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard
volumes:
  mytb-data:
    external: true
  mytb-logs:
    external: true_

**Comment by pon0marev** [comment]
Hi Mark,
Use the command to access the database:
`docker exec -it <container_name> psql -U thingsboard`
