### ISSUE TITLE
Bar chart widget - no labels? 

### ISSUE THREAD

**Issue by Mark19888** [thingsboard/thingsboard#5783]
Hi,

I'm using the CE edition on Docker and I can't seem to be able to get the **multiple** bar chart widget to show the labels for the input data I'm using the way I could do it with a **single** bar chart widget - screenshots below for reference. Is there a way to get it to work that I'm just not seeing here?

Moreover, the aggregations (min / max / average) also don't seem to work in this particular widget...?

Thanks,
Mark

Single Bar - works as expected:
![image](https://user-images.githubusercontent.com/96733753/147491584-a7cb0321-103b-453c-8e2f-49c07a76d226.png)

Multiple Bars - does not work as expected:
![image](https://user-images.githubusercontent.com/96733753/147491756-fb008073-650d-4fda-aea7-5698a05c32ae.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
