### ISSUE TITLE
[Bug] Rulechain number precision error

### ISSUE THREAD

**Issue by ChristofferHolmesland** [thingsboard/thingsboard#5786]
**Describe the bug**
When telemetry contains a string that looks like a number it is converted to a number type automatically by the rule chain. The conversion occurs when the number is outside of the `Number.MAX_SAFE_INTEGER` range. This produces precision errors when a value like `"840380235174088834"` is converted to `840380235174088800`.

**Your Server Environment**
  * Cloud infrastructure: AWS
  * ThingsBoard Version: 3.2.1PE
  * OS Name and Version: Ubuntu 18.04.2 LTS

**Your Client Environment**
None

**To Reproduce**
1. Create an HTTP integration that receives input like
```
{
    "code": "840380235174088834",
}
```
And produces the following output
```
{
    "deviceName": "CodeLog",
    "deviceType": "Code",
    "telemetry": {
        "code": "840380235174088834"
    }
}
```
2. Add a transformation node to the rule engine that doesn't modify the data. Turn on debug mode.
3. Trigger the HTTP integration with a value above `Number.MAX_SAFE_INTEGER`.
4. Check the debug event log of the transformation node to see that the string has been converted to a number with lost precision.

**Expected behavior**
I expect the rule chain to not automatically convert the data types. If I knew that it would convert a string to a number type I would expect it to respect the precision range so that the same number I want to store is what is actually being stored.

**Screenshots**
Screenshot showing the precision error.
![image](https://user-images.githubusercontent.com/1873309/147544477-ff64eef0-adf1-4941-9afa-dde4f36671e7.png)

**Comment by ouertani** [comment]
@ChristofferHolmesland Seems BigInt not support by nashorn: https://bugs.openjdk.java.net/browse/JDK-8010732 
This is the default behavior :

`ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");

System.out.println(engine.eval("var msg = {\n"
        + "    \"code\": 840380235174088834,\n"
        + "}; msg.code.toString()"));`

Of course using String will fix the issue.

**Comment by ChristofferHolmesland** [comment]
@ouertani It is not possible to use a string since the string input `"840380235174088834"` is automatically converted to an integer type by the rule engine resulting in this value `840380235174088800`.

That's the problem I'm trying to highlight here. Since BigInt is not supported by nashorn string data should not be automatically cast to a number type if they are outside of the safe range.

**Comment by ouertani** [comment]
@ChristofferHolmesland 
The screenshot https://user-images.githubusercontent.com/1873309/147544477-ff64eef0-adf1-4941-9afa-dde4f36671e7.png shows a number as input and not a string.

**Comment by ChristofferHolmesland** [comment]
@ouertani Correct, but that is just to show an example of what I mean by precision error. If you follow the steps I described and send the data as a string the value is automatically cast from being a string to a number type.

This is the payload that is sent to thingsboard.
```
{
    "code": "840380235174088834"
}
```

**Comment by ouertani** [comment]
@ChristofferHolmesland attached my screenshot with 3.3.2 CE 

![image](https://user-images.githubusercontent.com/68893/150841994-b4a11a08-a80a-4036-99b4-5ccf439f2f8f.png)

**Comment by SuminDenis** [comment]
Hi @ChristofferHolmesland,

We know about this issue and have **PROD-1691** already in our backlog!

As a workaround, you can change the configuration parameters by setting the variables in the thingsboard.conf file. For these, please add the following `export JSON_TYPE_CAST_ENABLED=false` to your thingsboard.conf and restart the service. This should help with a problem when a string automatically converts to a number!

Also, since 3.4.2, ThingsBoard released TBEL. You can read about TBEL by following the link: https://thingsboard.io/docs/pe/user-guide/tbel/
TBEL supports numbers like yours, and there isn't any problem with precision.

Please let us know if you have any questions!
