### ISSUE TITLE
api saveDevice not working - Missing entityType or id

### ISSUE THREAD

**Issue by nirvitarka** [thingsboard/thingsboard#579]
I am trying to use api saveDevice via a REST client (POSTMAN) with below request body

{
  "additionalInfo": "this is description",
  "createdTime": 0,
  "customerId": {
    "id": "---mycustomerid---"
  },
  "id": {
    "entityType": "DEVICE",
    "id":"abcd"
  },
  "name": "test_device",
  "tenantId": {
    "id": "---mytenantid---"
  },
  "type": "---mydevicetype---"
}

But getting response as "Bad Request" with below response 

"exception": "org.springframework.http.converter.HttpMessageNotReadableException",
    "message": "Could not read document: Missing entityType or id!; nested exception is java.io.IOException: Missing entityType or id!",
    "path": "/api/device"

I checked other closed issues here which say providing entityType should solve this, but I am already providing it, still no luck.

Can anyone help?

**Comment by vparomskiy** [comment]
1. Do you try to create new device or update  existing?
2. Could you please provide json that you use? It should contains tenantId and device Id, in case if it is update operation. 
3. You can always open browser development console and find real json that is used for different API

**Comment by sujataapatil** [comment]
Apologies the json added earlier got messed up. Corrected it in original post above, please check.

I am trying to create a new device, added my tenant id ,customer id & device id (as abcd) too.

**Comment by vparomskiy** [comment]
Here is the correct JSON
```
{
  "id": {
    "entityType": "DEVICE",
    "id": "-- device UUID --"
  },
  "createdTime": 1517575870841,
  "tenantId": {
    "entityType": "TENANT",
    "id": "-- tenant UUID --"
  },
  "customerId": {
    "entityType": "CUSTOMER",
    "id": "-- customer UUID --"
  },
  "name": "Device_Name",
  "type": "Device",
  "additionalInfo": null
}
```
You have missed 'entityType' field for tenantId & customerId properties

**Comment by sujataapatil** [comment]
Thank you vparomskiy,
With this json format, I am getting below response. Is there any error code reference available?

{
    "status": 400,
    "message": "Can't create entity for domain object --my json input comes here--",
    "errorCode": 31,
    "timestamp": 1519146694627
}

**Comment by ben-hudson** [comment]
Hi @nirvitarka ,

I had the same problem as you. You're getting that error because you're posting the wrong data.
To create a new device you want to post the following:
`{"name":"name","type":"default","additionalInfo":null}`
(with your auth token in the X-Authorization header)

You will _get back_ the JSON that @vparomskiy commented. Then you can use that info to set up device credentials etc.

**Comment by luixal** [comment]
Hmm.. just got here having the same error on the ```/api/device``` endpoint. Got it working by tweaking the json i was sending according to the example posted by @vparomskiy .

Anyway, the example in swagger docs is this:

```json
{
  "additionalInfo": "string",
  "createdTime": 0,
  "customerId": {
    "id": "string"
  },
  "id": {
    "id": "string"
  },
  "label": "string",
  "name": "string",
  "tenantId": {
    "id": "string"
  },
  "type": "string"
}
```

and the one I got working is this:

```json
{
  "additionalInfo": "aaaa",
  "createdTime": 0,
  "customerId": {
    "entityType": "CUSTOMER",
    "id": "myCustomerId"
  },
  "label": "aaaa",
  "name": "aaaa",
  "tenantId": {
    "entityType": "TENANT",
    "id": "myTenantId"
  },
  "type": "aaaa"
}
```

Where can I find updated docs about using the API?

Thanks!
