### ISSUE TITLE
 I still experience the similar build error in application module

### ISSUE THREAD

**Issue by Stone1985** [thingsboard/thingsboard#58]
Hi, Andrew, I still experience the similar build error in application module:

Error:(28, 42) java: cannot find symbol symbol: class ClusterRpcServiceGrpc location: package org.thingsboard.server.gen.cluster

I checked the folder application\src\main\proto, it seems that there is no proto file for class ClusterRpcServiceGrpc, is this file missing? thanks.

**Comment by ashvayka** [comment]
Hi!

The service is auto-generated. Definition is located [**here**](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/proto/cluster.proto#L94).

I suggest you to build the project using maven from CLI: "**mvn clean install**" with optional "**-DskipTests**" to speed up the build. Once project is built, you will have auto-generated sources here: 
**application/target/generated-sources/protobuf/grpc-java**.

You can add this folder as a source folder, but we have plugin in the build for this purposes and it should happen automatically if you are using idea or eclipse.

**Comment by lxhtkj** [comment]
Hey!
I am using “mvn clean install” to build, but the end result is：
![question](https://user-images.githubusercontent.com/24477480/50535422-c62df500-0b84-11e9-8db5-c5165011e72e.gif)
version is 2.2.0 ；
I am tried 3 times to built,but result is same.
help me!Thanks~!!
