### ISSUE TITLE
Alarm details cleared by Device Profile alarm rules

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5800]
I have a device profile to create alarm when the reading is above a threshold and clear alarm when the reading is below the threshold. In the device profile alarm rule, I set the details as data reading "${temperature}".
I followed the https://github.com/thingsboard/thingsboard/issues/3919 to allow user to input comment for the alarm. The comment is set in "alarm.details.comment".
After the alarm is created, I can input the comment with no issue. However, when the alarm is cleared, the comment of the alarm is also cleared. How should I keep the alarm comment in this case?

**Comment by sunyong-mwi** [comment]
Some further findings: if I don't configure the details in the device profile alarm rules, the custom alarm details of "comment" will not be cleared when the alarm is cleared. However, before the alarm is cleared, if there is alarm update, the alarm comment will be cleared. It seems to be a bug.

**Comment by sunyong-mwi** [comment]
Any response? We need to solve the problem urgently.

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce this behavior on the latest Thingsboard version. 
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
