### ISSUE TITLE
[Question] Hide telemetry data from users

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5804]
Hi,

We need to save the variable in a historical way. At the same time, we do not want the user to see this variable. Actually, we want to see the date the device relation changed. We know that this is recorded as a log, but we do not want to learn this change date by looking at the logs.

Is there any way to hide telemetry data from users?

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by mde2017** [comment]
Hi @gohm-tech,

as far as I know there is know option to hide single telemetry keys for a user. You could only allow all or none.

Possible workarounds:

-  Store the telemetry data / variable on a different entity where the user has no direct access to, e.g. the Customer or Tenant entity itselft. This could be accomplished by Rulechains with Change Originator Node

-  Make use of external Nodes (like MQTT, Kafka, REST) or save to custom Table (only when using Cassandra) to store the data outside of ThingsBoard

**Comment by gohm-tech** [comment]
Hi @mde2017,

How can we allow to show none? What steps can we take to achieve this?

Best Regards,
**Gohm Team**

**Comment by mde2017** [comment]
Hi @gohm-tech,

This is only available for ThingsBoard PE via Role-Based Access Control (RBAC) feature.

There you could define a generic role where you can choose which permissions are set. Afterwards the role is assigned to a specific User group.

![image](https://user-images.githubusercontent.com/25298332/147908364-c483fe95-9546-47e9-8316-946815d2f985.png)

If you remove the operation "Read Telemetry" the users aren't allowed to read telemetries for the Device Group ressource.

**Comment by gohm-tech** [comment]
Hi @mde2017,

Thanks for your help.

Best Regards,
**Gohm Team**
