### ISSUE TITLE
[Question] OTA Firmware, get URL storage?

### ISSUE THREAD

**Issue by Ken26M** [thingsboard/thingsboard#5808]
Hi,

Is it possible to get an URL of the stored firmware that you uploaded in Thingsboard or do you have to fully commit and change the client software to the way the firmware update works in Thingsboard?

**Environment**

 * OS:  Ubuntu 20.04 LTS
 * ThingsBoard: 3.3.2

**Comment by Ultrazombie** [comment]
Closed due to inactivity
