### ISSUE TITLE
[Feature Request] Aggregation setting in time window

### ISSUE THREAD

**Issue by efpage** [thingsboard/thingsboard#5809]
Hy all,

If I change the time window in a dashboard, the aggregation time is often larger than useful. Usually I have to reajust the aggregation manually. Would it be possible to change the frontend to always choose the shortest possible aggregation after change of the time window? Even selecting the same list position in the select dialog would be suitable, as aggregation usually is changed with the time range.

**Comment by Ultrazombie** [comment]
Rejected.
If you select a time window, the default grouping is the optimal one. You can then manually select the one you want.
