### ISSUE TITLE
How to store telemetry data based on device's time in thingsboard? 

### ISSUE THREAD

**Issue by piousdeepakxavier** [thingsboard/thingsboard#581]
Hi,

We have offline data capturing options in our device end. Once the device goes online the stored telemetries will be published to the thingsboard server along with real-time telemetries. However the stored telemetry should not be ported in cassandra with the real-time timestamp. How can I store my offline captured telemetries with it's actual recorded time?

**Comment by piotrlinski** [comment]
from Thingsboard doc

_In case your device is able to get the client-side timestamp, you can use following format:

{**"ts":1451649600512**, "values":{"key1":"value1", "key2":"value2"}}

In the example above, we assume that “1451649600512” is a unix timestamp with milliseconds precision. For example, the value ‘1451649600512’ corresponds to ‘Fri, 01 Jan 2016 12:00:00.512 GMT’_

**Comment by adambforbes** [comment]
I have followed this documentation and am sending through HTTP uplike data in the format {"ts":1451649600512, "values":{"key1":"value1", "key2":"value2"}}

The data is however getting saved at the time it gets sent, not the specified timestamp. Does anyone have any further clarification on what "In case your device is able to get the client-side timestamp" means?

**Comment by pamafe1976** [comment]
Could you solve this?
