### ISSUE TITLE
[Feature Request] multiple y-axis combination

### ISSUE THREAD

**Issue by efpage** [thingsboard/thingsboard#5810]
Hy there,

Let assume you have multiple sensors for temperature and humidity. Temperatures all share the left axis. If I set the humidity as a second axis, each sensor creates it´s own new axis scale. I assume, this was not intended to have multiple right axis with the same title and settings. It was really useful to use the same axis scale for sensors with the same settings. This does not seem to be possible now.

BR, Eckehard

**Comment by pon0marev** [comment]
In the latest versions (3.7.0+), you can configure multiple Y axes:
![image](https://github.com/user-attachments/assets/9d22fa59-fbba-4b59-aac7-a168ae6a8b94)
