### ISSUE TITLE
[Question] Assign same asset to multiple customers

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#5811]
**Component**

 * Generic

**Description**
I have about 10,000 assets, which are houses, and I need to assign each one to a different customer so that each one can access their house data and no other data. On the other hand, I need to group the assets by municipalities, and that each of those municipalities have access to all the assets in their area. For that I need that each asset can be assigned to at least 2 different customers, but it only allows me to assign it to one at the same time.

In the same way, I need everything to be in the same tenant so as not to duplicate data, since there has to be synchronization of the data in case of updating them.

Is there some way to do this, either by somehow assigning an asset to two different clients, or by changing the logic.

Thanks a lot.

**Environment**

 * ThingsBoard: C.E. 3.3.2

**Comment by mde2017** [comment]
Hi @Borch97,

in CE you can only assign each asset to exactly one customer.

The logic you want to implement is part of the RBAC functionality in TB PE versions:
https://thingsboard.io/docs/pe/user-guide/rbac/
