### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pegah-mir** [thingsboard/thingsboard#5812]
**Describe the bug**
Any body can delete account of sysadmin in thingsboard

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard Version = 3.2.0
  * OS Name and Version = Ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [ Ubuntu]
* Browser [chrome ]
* Version [20.04]

*MY Device Using**
  Postman for Linux
  Version 7.36.5
   
* Connectivity
 
  * HTTP
  
* Device vendor and model

**To Reproduce**
1. open postman 
2. past this api http://could.tb/api/user/useridsysadmin
   and Request Method: DELETE
3. submit send button
4. See successful

**Expected behavior**
TB must not allow to delete sysadmin

**Comment by volodymyr-babak** [comment]
hi @pegah-mir 

I can not reproduce this issue.
I had tried to delete sysadmin user using tenant admin credentials with the URL that you provided, but I'm getting 403 error message:
{"status":403,"message":"You don't have permission to perform this operation!","errorCode":20,"timestamp":"2022-01-21T14:02:33.224+00:00"}

And here is the sample of my request:
curl --location --request DELETE 'http://localhost:8080/api/user/22f50260-67d5-11ec-8196-75accf27ac07' --header 'Content-Type: application/json' --header 'X-Authorization: Bearer XXX'
