### ISSUE TITLE
 Is there any way for thingsboard alarm type components to obtain data

### ISSUE THREAD

**Issue by fanbingbing16** [thingsboard/thingsboard#5817]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
其他类型的部件例如最新值可以获取到data，而告警类型的data为undefined
Other types of widgets, such as the latest value, can obtain data, while the data of alarm type is undefined

现在的需求是在告警类型的部件中得到后端传上来的值
**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by Ultrazombie** [comment]
Hello @fanbingbing16 
Tell us your problem in more detail, preferably in English, it will speed up the solution of your problem
