### ISSUE TITLE
[Bug] Dashboard Widget Data Aggregation Function returning incorrect values

### ISSUE THREAD

**Issue by ianog-eng** [thingsboard/thingsboard#5819]
**Describe the bug**
When aggregating timeseries data in a widget, the aggregated values are incorrected calculated.

**Your Server Environment**
* cloud.thingsboard.io

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Microsoft Windows 11 Home 10.0.22000 Build 22000
* Browser: Chrome
* Version: Version 96.0.4664.93 (Official Build) (64-bit)

**Your Device**

* Connectivity
  * Integration: AWS IoT Core 
* Device vendor and model
  * In-house device, using Particle Electron running RTOS

**To Reproduce**
1. Create Dashboard
2. Create time-series table widget
3. Display data with changing values
4. set aggregation function to 'none'
5. Note raw values
6. Set aggregation function to SUM with a period of 1 hour
7. note incorrect values

**Expected behavior**
I expect the data to be aggregated correctly using the specified function 

**Screenshots**
Raw data:
![Screenshot 2022-01-05 125136 - raw](https://user-images.githubusercontent.com/84106368/148209800-509cd51e-6076-46e9-8d51-93d1d263465c.png)

Incorrectly aggregated data:
![Screenshot 2022-01-05 125040 - sum](https://user-images.githubusercontent.com/84106368/148209850-9735df23-f610-4879-af94-1e701803c274.png)

**Additional context**
May be related to #5727

**Comment by ianog-eng** [comment]
I have the issue with other aggregates, not only SUM

**Comment by ianog-eng** [comment]
Following the comment about precision in #5727 I did a test, this bug only affects data that has a higher precision, see below the summary of my test for each aggregation and the test data. The count function is not affected, so it seems like there is some bug affecting handling of precision on the aggregation functions.

Result summary:
![Screenshot 2022-01-06 134533 Summary](https://user-images.githubusercontent.com/84106368/148378556-5c31809a-d2b2-4de5-b80c-2a9ccc90af72.png)

Raw values:
![Screenshot 2022-01-06 132914 raw](https://user-images.githubusercontent.com/84106368/148378576-dfcf538c-8477-4bb0-a709-5212df742df0.png)

Count function:
![Screenshot 2022-01-06 133035 count](https://user-images.githubusercontent.com/84106368/148378600-b67516d9-c64f-4426-a891-a7aa22b128b1.png)

Min Function:
![Screenshot 2022-01-06 133327 min](https://user-images.githubusercontent.com/84106368/148378622-f92fb0af-d70e-481f-99cb-3ba379f63c49.png)

Max Function:
![Screenshot 2022-01-06 133418 Max](https://user-images.githubusercontent.com/84106368/148378641-85ecdcce-4ebe-4f1b-90a3-faebcc45e686.png)

Average Function:
![Screenshot 2022-01-06 133447 avg](https://user-images.githubusercontent.com/84106368/148378669-de15e79e-5ab4-417e-9e56-6d688a337808.png)

Sum function:
![Screenshot 2022-01-06 133721 SUM](https://user-images.githubusercontent.com/84106368/148378698-f439c967-488d-4cb0-8c13-7ad412063ba6.png)

**Comment by tdsimpro** [comment]
Hey FYI it's because telemetries with more than 16 numbers after the decimals are saved as string in the db instead of numbers, and are then ignored when using aggregations or calculation (sum, avg etc)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
