### ISSUE TITLE
different devices a total value

### ISSUE THREAD

**Issue by jorisgengler** [thingsboard/thingsboard#582]
Is it possible to add different devices values together?
for a total value

**Comment by vparomskiy** [comment]
You will need to create new widget for this. Please find details in documentation.

**Comment by jorisgengler** [comment]
I understand that I need to create a new widget.
In the widget with 1 device I can calculate a total (with javascript).
but how should that be if you have multiple decives?

Can you tell me where I can find this in the documentation?

**Comment by vparomskiy** [comment]
In widgets development guide, in section 'Basic widget API' you can find more details. But in general, you should create an alias that will resolve a list of devices that you require. After that, 'onDataUpdated()' method will be called when list will be initialized, inside this method you can get access to the list of devices from ctx.defaultSubscription object.

**Comment by jorisgengler** [comment]
Thank you for your help
I read development guide, but i come not further than make a list of the alias.

I do not see the ctx.defaultSubscription object.

Do you have maybe an example of this?

**Comment by vparomskiy** [comment]
Here is a tutorial how to aggregate data from different devices using RuleEngine
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/

**Comment by edlux998** [comment]
Any update in this peace of shit??? Support can't answer simple question about own software
