### ISSUE TITLE
[Bug] ThingsBoard's entities table does not correctly use the title parameter

### ISSUE THREAD

**Issue by Eric-Willoughby** [thingsboard/thingsboard#5825]
**Describe the bug**
Tables that use entities that are widgets in ThingsBoard do not properly display the title set under the edit pop out window, but instead uses the default name of the widget type. The title property is used and seen in the edit area, but it does not update on the widget title itself. 

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version 3.3
  * Ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**
* OS: Windows 10 Enterprise 
* Browser Chrome
* Version 1809

* Connectivity
  * HTTP

**To Reproduce**
1. Go to Dashboards and select the plus icon (+) then create new widget. 
2. Give it whatever values you want and save it. 
3. Go to the widget that was just created and select the pencil edit icon and try to change the title name and save.
4. See attached screenshot for an example output.

**Expected behavior**
When updating the title for a widget, the title should update on the widget itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/97132982/148247386-5fafe0c5-a2c6-4f67-84e3-ac617f1ecaac.png)

**Comment by Raven888888** [comment]
Please use Advanced tab setting @Eric-Willoughby 

![image](https://user-images.githubusercontent.com/58241952/148325394-103b083d-aa8c-41a2-b99f-dfc8f1022ae9.png)

**Comment by Eric-Willoughby** [comment]
@Raven888888 Thank you!
