### ISSUE TITLE
how can we add image in dashboard , in which widgets ? 

### ISSUE THREAD

**Issue by jitendraspatil** [thingsboard/thingsboard#5826]
**Component**

 * UI

**Environment**

 * OS:windows 10 pro
 * ThingsBoard: 3.2.2
 * Browser: chrome

**Comment by jitendraspatil** [comment]
i am not able to add image in dashboard can you  help me

**Comment by mde2017** [comment]
Hi @jitendraspatil,

there are several ways to accomplish this. You could even use images as Dashboard backgrounds. 

Some widgets where this is possible:

- Static HTML Card --> img HTML Tag for embedding images via URL
- Image Map
- Markers Placement Image Map

**Comment by jitendraspatil** [comment]
Thank you
