### ISSUE TITLE
[Question] Custom Map Widget: Nested subscribe causes refresh

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5827]
**Component**
UI

**Description**
I'm working on a custom widget, derived from the map-widget where I include the alarm-data of the aliased devices.
For this purpose, I'm using the deviceService (to get all the user devices' ids) and the http-service (to call the alarm api-endpoint).
I've added my code into the onInit-function as well as the onDataUpdated-function.
The relevant parts of the code look as follows (I've simplified the relevant code to a minimum which still causes the strange behavior):

```
self.onDataUpdated = function() {           
    ...
    let defaulthttpconfig={
        ignoreLoading:false,
        ignoreErrors:false,
        resendRequest:false
    };
    
    customerId={entityType:'CUSTOMER',id:self.ctx.currentUser.customerId};
    let pl = new self.ctx.pageLink(100,0,null,null);

    const uu='/api/alarm/DEVICE/';
    const bb='?pageSize=100&page=0';

   // nested subscriptions
   const outer$=deviceService.getUserDevices(pl,'MYProfile',defaulthttpconfig);
   outer$.pipe(
        self.ctx.rxjs.switchMap( data => {
            //return self.ctx.rxjs.of(data); // <-- no refresh triggered 
            return http.get(uu+data.data[0].id.id+bb,defaulthttpconfig);  // <--refresh triggered
        })            
    ).subscribe(console.log,console.error); 
   ...
```

Surprisingly, this nested subscription triggers a refresh of the widget as seen in the following gif:
![mymap_refresh_gif](https://user-images.githubusercontent.com/86358217/148357917-f2671877-2f70-4bbf-acd3-c583c3cae887.gif)
This refresh propagates into the widget-types view which makes it hard to add new widgets because the edit-menu is refreshed every couple of seconds. See the next gif.
![overview_refresh](https://user-images.githubusercontent.com/86358217/148358950-d7dfffcf-ede6-422e-8239-1fb3b8de058d.gif)

Is there any way to prevent this behavior?

**Environment**
 * OS:  Win 10
 * ThingsBoard: PE 3.3.1
 * Browser: Chrome

**Comment by elpollo12** [comment]
Hi @eeitnn , did you find a solution to this problem?

**Comment by eeitnn** [comment]
> Hi @eeitnn , did you find a solution to this problem?

Hi. Not really

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
