### ISSUE TITLE
Moving simple Python App from Demo to Cloud

### ISSUE THREAD

**Issue by fulburncams** [thingsboard/thingsboard#5828]
**Component**

 * Generic

**Description**
**Background**
I have simple Python app which I have used to capture remote data on Raspi Zero and send via MQTT to thingsboard.demo.  It all works and i have setup dashboards on the Demo version fine.  I have setup the params in Python for Thingsboard host ('demo.thingsboard.io'),  port 1883 , access-token as per instructions and when i call the mqtt commands all works fine.  When i want to send data the program uses the line ...

_client.publish('v1/devices/me/telemetry', json.dumps(sensor_data),1)_

This all works fine, although i am intrigued what the _'v1/devices/me/telemetry_' parameter refers to , is this the topic ?  Anyway... as I have now reached the demo data limit I have tried to move to the basic cloud version

**Query**
I am not sure what settings to setup, having moved to the paid-for 'thingsboard cloud' environment.  As far as i can tell
Thingsboard host should now be set to 'thingsboard.cloud', port again 1883,  access_token is changed (I grabbed this from a new device I setup) .  What no longer seems to work is the client.publish,  and I am  not sure what to put in the first parameter ?  Is this the topic,  I which case how/where do I setup topic ?

I have looked at Raspberry Pi (Deb) Installation,  which seems to require gateway setup,  but I did not previously need gateway setup,  so not sure this is the answer and it looks like a fair bit of work.  Is theer a really basic setup without tb-gateway

Any help gratefully received
Thanks
Steve

**Environment**

 * OS:  Debian/Raspbian V10 Buster
 * ThingsBoard: version 2.0
 * Browser: N/A

**Comment by Ultrazombie** [comment]
Closed due to intactivity
