### ISSUE TITLE
$(entityName) under dashboard state names not working as shown in Tutorial #2 of guide

### ISSUE THREAD

**Issue by Ideasrefined** [thingsboard/thingsboard#583]
The guiding tutorial 2 "Dashboard development guide part 2" shows dashboard state name given as $(entityName) which will later be resolved to actual state name when the user traverses to a new state. But on following that tutorial the $entityName doesn't resolve to anything. It stays as "$(entityName)"

**State creation**
![sate_creation](https://user-images.githubusercontent.com/5001509/36252054-3f46b1e4-1265-11e8-8954-80bc0de536a6.png)

**Sub state names should be derived from here**
![states](https://user-images.githubusercontent.com/5001509/36252078-49b16476-1265-11e8-9a6d-c1cd1809ea97.png)

**On clicking and heading to new state. the state name doesn't resolve**
![no_state_name](https://user-images.githubusercontent.com/5001509/36252122-5aaf54b8-1265-11e8-9bb0-7169cc76c3f0.png)

Is this a bug or am I missing something obvious ?

**Comment by Terny22** [comment]
Hi, Ideasrefined!

The correct pattern syntax is ${entityName}, instead of $(entityName)
