### ISSUE TITLE
[Question] Programmatically change widget timewindow

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#5830]
**Component**
 * Generic

**Description**
I've created a custom widget derived from the alarms-table-widget.
Now I need to modify the timewindow within the onInit-function.

I know how to change the timewindow for the whole dashboard
This can be achieved by passing a Dashboardtimewindow-object to self.ctx.dashboard.dashboardTimewindowChangedSubject.next(...).

Is there a similar approach for the widget ?

**Environment**
 * OS:  Win10
 * ThingsBoard: 3.3.1 PE
 * Browser: Latest Chrome

**Comment by eeitnn** [comment]
Nevermind. Found a solution.

**Comment by richqqrd** [comment]
> Nevermind. Found a solution.

I got a similiar problem, can you maybe share your solution? I would really appreciate that

**Comment by Nathan-ma** [comment]
I'm also having a similar problem, Mind Sharing @eeitnn ?
