### ISSUE TITLE
Notification of disconnection periodicaly

### ISSUE THREAD

**Issue by hjlopezr** [thingsboard/thingsboard#5831]
**Component**

 * Rule Engine
 * Generic

**Description**
Hello all
I have to several devices with a several customers.
I looking for send an email periodically when a device has been a disconnect for a certain time (for example week, month, etc).

With the rule engine (Disconnect Event or Inactivity Event) runs once when i create the rule, but i need that check periodically, for example every day.

Some ideas?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: v3.3.2
 * Browser: N/A

**Comment by dhaval2017** [comment]
Hi @hjlopezr 
What if you store telemetry data disconnected=1 whenever disconnection is fired?

Later you can fetch for number of time disconnected for different interval
You can make many different types of reports

**Comment by mde2017** [comment]
Hi @hjlopezr,

please try following this guide:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-inactivity-alarm/

You can define the desired inativity interval with the server attribute "inactivityTimeout" (needs to be in milliseconds)

**Comment by mde2017** [comment]
Hi @hjlopezr,

each time a device gets new data in thingsboard, the lastActivityTime server attribute is updated with a new timestamp. By defining the inactivityTimeout, following the mentioned guide, you can define a timeout value which triggers an Inactivity event in the Root Rule Chain. You can handle this via rulechains and create alarms afterwards. So this should be exactly the way you want to realize this usecase.

Example:
If you set inactivityTimeout to 10 min, it will be checked periodically if the difference between the timestamp of the last activity and the timestamp of right now exeeds 10 min. If that's the case, the Inactivity Event will be triggered.

**Comment by hjlopezr** [comment]
Thank you @mde2017. I don't explained me. The process is clear but the functionality not.
For example: How often is "checked periodically"?

This rule must log all devices without activity >  60 seconds

<img width="305" alt="ruleChain" src="https://user-images.githubusercontent.com/59338934/149337488-f40dc93d-3feb-41df-a682-4ed6df43cb50.png">

as config in the thingsboard.yml:

```
state:
  # Should be greater then transport.sessions.report_timeout
  defaultInactivityTimeoutInSec: "${DEFAULT_INACTIVITY_TIMEOUT:60}"
  defaultStateCheckIntervalInSec: "${DEFAULT_STATE_CHECK_INTERVAL:60}"
  persistToTelemetry: "${PERSIST_STATE_TO_TELEMETRY:false}"

```
I have disconnected devices for days or weeks  but none is logged, only appear devices that was disconnected in the last 60 seconds  and not the oldest.
Further the "life cycle event" is UPDATED once, this is my question about how often.

<img width="760" alt="lifecycle" src="https://user-images.githubusercontent.com/59338934/149339763-c41bf1e9-4493-401a-bdea-73babd019ec4.png">

Regards!!!

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
