### ISSUE TITLE
[Feature Request] Button to enable or disable a scheduler

### ISSUE THREAD

**Issue by kxiopl** [thingsboard/thingsboard#5834]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have a simple button to enable or disable a particular configured scheduler instead of reconfiguring a scheduler every time.

**Comment by volodymyr-babak** [comment]
hi @kxiopl 
Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1350) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
