### ISSUE TITLE
[Question] Is there a proper tutorial showing how to implement OTA with ESP32

### ISSUE THREAD

**Issue by 232485** [thingsboard/thingsboard#5835]
**Component**

 * Generic

**Description**
A comprehensive tutorial and example of latest OTA implementation with ESP32. The old tutorial on the website is complicate and outdated I think: https://thingsboard.io/docs/samples/esp32/ota/

**Environment**

 * ThingsBoard: 3.3.2

**Comment by epalchenko** [comment]
Hello @232485,
For now, previous guide was made for 2.4 ThingsBoard version and it includes an example for realization of this feature.
For the latest versions, there is dedicated feature for OTA.
Please, use this https://thingsboard.io/docs/pe/user-guide/ota-updates/?remoteintegrationdockerinstall=mqtt for references.
