### ISSUE TITLE
[Bug] Security check in alarm route

### ISSUE THREAD

**Issue by nowherex** [thingsboard/thingsboard#5836]
**Describe the bug**
Hi Thingsboard team, I'm creating an API to consume some alarm information and I found what i believe to be a serious bug in the new version of thingsboard PE (3.2.2), in the alarm route the security check taht should check the user permission for the entity It is not being performed, when looking for alarm information by ID with a costumer that does not have read or write permission for the entity, we are receiving the information as if he had it.

Even when we tried to get device information with this client we received correctly that it does not have permissions, we tested it with different devices, assets and costumers and the bug (security flaw) persists.

Please, Could you check?

**Your Server Environment**
Thingsboard PE
* own setup
  * ThingsBoard v3.2.2
  * OS Linux

**To Reproduce**
Steps to reproduce the behavior:.
1. Generate an alarm with any customer or tenant access (Costumer A ) can be asset or device.
2. Enter another costumer of the same level or bellow (Costumer B).
3. Log in to the documentation with Customer B access data.
(https://youthingsboardinstance.com/swagger-ui/)
4. Try to handle the alarm generated for Costumer A, you will see that you will get ack, clean, fetch information and so on.

**Expected behavior**
We should receive the information that the user does not have write or read permissions for the alarm (as happened before the update).

**Comment by volodymyr-babak** [comment]
hi @nowherex 
I can't reproduce this at the moment.
Let's say we have the next hierarchy of entities:
- Tenant
  -  Customer A
    - Asset A
  - Customer B

If I'm generating an alarm on Asset A and then trying to find an alarm for this **Asset A** using **Customer B** credentials, I'm getting error regarding permission denied:
**{"message":"You don't have permission to perform 'READ' operation with ASSET 'Asset A'!","errorCode":20,"status":403,"subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null,"timestamp":"2022-01-20T14:01:59.444+00:00"}**

Here is the curl command I'm using to fetch alarms:
`curl -v -X GET --header "Content-Type:application/json" --header "X-Authorization: Bearer XXX" "https://thingsboard.cloud/api/alarm/ASSET/0189ef70-79f8-11ec-9cdc-97964cc3249d?page=0&pageSize=10" -d '{}'`

Please specify the exact hierarchy and query that you are using so we can reproduce it.

**Comment by nowherex** [comment]
Hello @volodymyr-babak, i performed the test again and the bug persists (using the same hierarchy of entities).

- Tenant
  - Customer A
    - Asset A
 - Customer B

just a note, the routes where the bug occurs are these:
https://MYINSTANCEURL/api/alarm/{alarmId}
https://MYINSTANCEURL/api/alarm/{alarmId}/ack
https://MYINSTANCEURL/api/alarm/{alarmId}/clear

that is, in the routes that deal directly with the alarm and not with the entities (devices, assets).

here is my curl command:
```
curl -X 'POST' \
  'https://MYINSTANCEURL/api/alarm/1a89d2f0-7a5d-11ec-b852-01e9ac3798d7/ack' \
  -H 'accept: */*' \
  -H 'X-Authorization: Bearer XXX' \
  -d ''
```

If possible, I await your comments. thanks

**Comment by volodymyr-babak** [comment]
hi @nowherex 

Thank you for rising up this bug - indeed I was able to clear the alarm with a different customer by alarm id; I had already added to our backlog a ticket for a product team (PROD-1361). There's no set timeframe for our dev reviews; however, please follow our Release Notes to see all new additions to the platform in the subsequent releases.
