### ISSUE TITLE
[Feature Request] Allow customer to log in.

### ISSUE THREAD

**Issue by purplehorace** [thingsboard/thingsboard#5840]
**Is your feature request related to a problem? Please describe.**
CE system allows for a tenant to create a customer who has a number of users associated.
For a situation where there is an OEM that has a dealer network, who in turn has its customers it would make sense that the Dealer/Customer should be able to log in as the 'Customer'.  Customer would then be able to see and manage all the devices associated and see and manage the users associated.  Tennant would still have overall control of all Customers and their users.

**Describe the solution you'd like**
Introduce password access control for 'Customer' and have that account as admin level for its users and devices.

**Describe alternatives you've considered**
Have tried to look at using multiple tenant accounts to facilitate but unable to share devices or entity views between tenants and their users.

**Comment by vvlladd28** [comment]
Hi @purplehorace,
This feature is available in ThingsBoard PE. You can create customers with different roles (different rights), which can manage devices and their users.

**Comment by purplehorace** [comment]
Hi @vvlladd28 
Yes we are aware of the PE version but the platform is overpowered for a simple 3 layer user system.
We see PE useful where there can be multiple levels of Tenant, Customer and Users where Customers can have Customers and Users.

Customer login would allow for more flexibility on the awesome CE codebase.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
