### ISSUE TITLE
POST http://192.168.1.224/api/noauth/oauth2Clients?platform=WEB 503 (Service Unavailable)

### ISSUE THREAD

**Issue by suyutinisai** [thingsboard/thingsboard#5841]
**Describe the bug**
Can't able to login 
hosted as microservices 

* own setup
  *  docker deployment
  * ThingsBoard Version 3.3
  * Ubuntu

![image](https://user-images.githubusercontent.com/90888637/148728459-08939f87-1939-4c83-b453-b02a58d5da03.png)
@ashvayka

**Comment by Ultrazombie** [comment]
@suyutinisai  Hello,
do you still have a problem?
If so, please provide the thingsboard.log file to investigate your issue.
