### ISSUE TITLE
can we edit line chart widget

### ISSUE THREAD

**Issue by BhushanPDS** [thingsboard/thingsboard#5842]
**Component**

 * UI

**Description**
I need to add my own code in .line chart widget

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.2.1
 * Browser: chrome

**Comment by ashaforost** [comment]
Hi @BhushanPDS 

Please see the [Widget Development Guide](https://thingsboard.io/docs/user-guide/contribution/widgets-development/) for some instructions on how to modify the thingsboard widgets.
Basically, you can modify any of the available functions within the widget (OnInit, OnResize, OnDestroy, etc., see the Basic widget API section of the documentation)
