### ISSUE TITLE
[Question] One single row JSON telemetry

### ISSUE THREAD

**Issue by gzlz** [thingsboard/thingsboard#5844]
**Component**
 * Rule Engine

**Description**
I have a device that sends a large amount of different JSON telemetry every 15 minutes. As the amount of data is large it sends it in three parts, by sending it in three parts it is stored in the database in three rows with three different timestamps. How could I store it in a single row with a single timestamp?

Now, I have this:
![Captura_1](https://user-images.githubusercontent.com/19785703/148780408-f22a68ec-d958-44f3-90e9-e1c14a057cbb.PNG)

I would like to have this:
![Captura_2](https://user-images.githubusercontent.com/19785703/148780700-1dc7b6f5-5513-48e1-a5e2-529f065bd84f.PNG)

**Environment**
 * OS:  Ubuntu Server 18.04
 * ThingsBoard: 3.2.2
 * Browser: Chrome

**Comment by digital-codes** [comment]
If you have timing available at your sensor you could generate the timestamp yourself and submit it like so {ts:<timestamp>,values:{your values}}
If not you should be able to push the timestamp to a shared attribute on part 1 and retrieve it on the subsequent two.
See documentation for both options

**Comment by gzlz** [comment]
Hello Andreas, thank you for your help.
I have created a shared attribute and the telemetry is transformed properly in a transformation script, but I'm doing something wrong because  I haven't access to the shared attribute. I leave hare the code with the first and second block.

new_msg = {}
new_metadata = {}

if (msg.Vibration.RMS.X != null) {
        new_metadata.sharedTimeStamp = Date.now();
        new_metadata.ts = new_metadata.sharedTimeStamp;
        new_msg.Temperature = msg.Temperature;
        new_msg.X_RMS = msg.Vibration.RMS.X;
        new_msg.X_Kurtosis = msg.Vibration.Kurtosis.X;
        new_msg.X_P2P = msg.Vibration.P2P.X;
        new_msg.X_Z2P = msg.Vibration.Z2P.X;
    }

    if (msg.Vibration.RMS.Y != null) {
        new_metadata.ts = metadata.sharedTimeStamp;
        new_msg.Y_RMS = msg.Vibration.RMS.Y;
        new_msg.Y_Kurtosis = msg.Vibration.Kurtosis.Y;
        new_msg.Y_P2P = msg.Vibration.P2P.Y;
        new_msg.Y_Z2P = msg.Vibration.Z2P.Y;
    }

**Comment by digital-codes** [comment]
You can access the shared attributes in the rule chain via the originator attributes enrichment block. I do this to get access to a value I've written into a shared attribute (see screenshots - sorry, partially German)

![Bildschirmfoto zu 2022-01-11 14-25-25](https://user-images.githubusercontent.com/34965919/148950926-2ca0cefa-d711-4695-b1cd-161cae869c17.png)
![Bildschirmfoto zu 2022-01-11 14-25-05](https://user-images.githubusercontent.com/34965919/148950942-230fe002-d38c-477d-8ca3-0917a944b8d3.png)

**Comment by gzlz** [comment]
Hi andreas, thanks for your help.
I have tried, but the value of the shared attribute does not change. When part 1 arrives I change the value of the shared attribute with the current timestamp. Then when parts 2 and 3 arrive the shared attribute has the default value that I set manually when I created the shared attribute for the device via the UI. I will continue testing.
