### ISSUE TITLE
How to change Owner of a Customer programmatically ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5845]
Hello,

I am trying to create a customer from a custom action. I managed to create it. The thing is, when the customer is created, it is located at the root of the customer hierarchy. I would like to be able to place the created customer inside a customer group of another customer directly when it is created. 
Is it possible ?

Best regards,

Lucas Arsicaud

**Comment by lucasKapf** [comment]
Do I have to set the "owner" attribute ?

**Comment by lucasKapf** [comment]
I have discovered that the widgetContext.entityGroupService provides a changeEntityOwner function. 
I understand that the parameter e represents the owner and the parameter t represents the customer whose owner needs to be changed. I just don't know what to put as parameter n ?
Here is a screenshot of the function changeEntityOwner :

![CaptureChangeOwnerMethod](https://user-images.githubusercontent.com/95343678/149125077-ae53d4e0-43d3-44ee-905f-f72ef117824d.PNG)

**Comment by lucasKapf** [comment]
I finally achieved it by doing this : 


```
var owner = widgetContext.stateController.stateObject[1].params.entityId;
entityGroupService.changeEntityOwner(owner,asset.id).subscribe(
							function () {
								widgetContext.updateAliases();
								vm.dialogRef.close(null);
							} );
```
The parameter n seems to be optional.

**Comment by TrumeterCloud** [comment]
Does this still work?
`                let targetOwnerId = {
                    entityType: 'CUSTOMER',
                    id: '90de4720-5eb2-11ee-aaf7-0f7cfc867049'
                }
                let moving = {
                    entityType: 'USER',
                    id: '852fd2e0-5ecb-11ee-aaf7-0f7cfc867049'
                }
                self.ctx.entityGroupService.changeEntityOwner(targetOwnerId,moving)`
                
This code gave me the following error:

> polyfills.0507304945bea4e4.js:1     POST https://dev-cloud.trumeter.com/api/owner/TENANT/6074e550-31fb-11ee-9527-e5144d913765/CUSTOMER/90de4720-5eb2-11ee-aaf7-0f7cfc867049 500 (Internal Server Error)
