### ISSUE TITLE
[Question] No telemetry data

### ISSUE THREAD

**Issue by soyoeml** [thingsboard/thingsboard#5847]
**Component**

 * UI
 * Data Converters and Integrations
 * Generic

**Description**
When I send sensor binary data, there is no telemetry data showed. 
I send data with this command:
echo -e -n '\x06\x01\x16\x31\x32\x33\xFF' | nc -q1 -w1 127.0.0.1 10560

I can see debug events from data converters:
{
    "deviceName": "Temp Sensor 01",
    "deviceType": "default",
    "attributes": {
        "model": "01",
        "serialNumber": "SB001",
        "integrationName": "Temp_Integration"
    },
    "telemetry": {
        "temperature": "22",
        "rawData": [1, 22, 49, 50, 51, 255]
    }
}

I also can see rule save timeseries events. 
2022-01-10 13:15:43ip-172-31-18-220INDEVICEc2d472e3-fda0-4244-a7b8-f1ee3b789538POST_TELEMETRY_REQUESTPost telemetry

{
    "temperature": 22,
    "rawData": [1, 22, 49, 50, 51, 255]
}

It's successfully saved. I also can query it from psql in tables: ts_kv_latest and ts_kv_2022_01. 
But there is no telemetry data anywhere. Please help me to take a look.

**Environment**

 * OS:  Ubuntu 20.04 focal
 * ThingsBoard: thingsboard-3.3.2pe
 * Browser: Firefox 95.0 64bit

**Comment by kalutkaz** [comment]
Hi, @soyoeml could you add some more information,  for example, some screenshots from rule chains in debug mode and widget configuration where you visualization the information. It`s hard to find reason without that.

**Comment by soyoeml** [comment]
I deleted hidden device "Temp Sensor 01" and created a new device "Temp Sensor 01" manually, then it shows now.
