### ISSUE TITLE
Cant connect to thingsboard localhost:8080

### ISSUE THREAD

**Issue by indrawanfian** [thingsboard/thingsboard#5849]
I have finished installing thingsboard on windows, all went well. no problem for net start and net stop thingsboard, but unable to connect or open webserver localhost:8080.
here I attach the thingsboard.log file

this is information about my environment and ThingsBoard version:
OS:  Windows 10 home edition
ThingsBoard: 3.32 community edition

[thingsboard.log](https://github.com/thingsboard/thingsboard/files/7842875/thingsboard.log)

**Comment by kalutkaz** [comment]
Hi @indrawanfian as I can see in the log file port that thingsboard try to use is already in use:
![image](https://user-images.githubusercontent.com/43555187/149163157-e2532233-bbce-4c4d-9076-808a088f48cf.png)
![image](https://user-images.githubusercontent.com/43555187/149163208-c2d5ee21-415d-4795-bccf-c709eb61fa5d.png)
Maybe some other program using this port.

You need clean this port (for example using comand "sudo kill -9 $(sudo lsof -t -i:7070)"). 
After that all must work ok.

**Comment by SergMeleshko** [comment]
Hello.
Is the problem still relevant?
