### ISSUE TITLE
[Question] Use Node.js package in Widget Development

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#5850]
**Component**

 * Generic

**Description**
I would like to develop a custom widget, but I need to make use of a node.js package. Is there any possibility to install the package with npm and that it can be used inside a widget?

**Environment**

 * ThingsBoard: CE 3.3.2

**Comment by mde2017** [comment]
Hi @Borch97,

I faced a similar problem with the chart library apexcharts. It is not possible to import node.js packages directly. But importing worked via CDN urls:

https://apexcharts.com/docs/installation/

Importing with the following url worked:
https://cdn.jsdelivr.net/npm/apexcharts@3.32.1/dist/apexcharts.min.js

You can look up CDN urls for your preferred library here:
https://www.jsdelivr.com/

**Comment by Borch97** [comment]
Thanks for the advice.
 I am trying to connect to a minio server, but when importing the .js (https://cdn.jsdelivr.net/npm/minio@7.0.25/dist/main/minio.js) , it constantly tells me that Client is not a function, when inside the javascript file it is and is a function.

**Comment by digital-codes** [comment]
You can also host packages on-premise and include them in the "resources"  tab of the custom widget. I do this for a couple of features.
Make sure to get CORS right (host on same server, for example)

**Comment by Borch97** [comment]
Yes, that's the way I'm trying, but I get an error constantly when I try the following code.

```
var s3Client = Client({
  endPoint: 's3.amazonaws.com',
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY'
})

s3Client.listBuckets(function(e, buckets) {
  if (e) return console.log(e)
  console.log('buckets :', buckets)
})
```

The "original", making use of node.js would be the following.

```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 's3.amazonaws.com',
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY'
})

s3Client.listBuckets(function(e, buckets) {
  if (e) return console.log(e)
  console.log('buckets :', buckets)
})
```

I don't know if maybe it's something with my syntax.

**Comment by DiogoMesquitaInd** [comment]
> Oi@Borch97,

Can you provide more details on how you integrated the ApexCharts library into thingsboard? I'm trying but the following error appears:
-ApexCharts is not defined.

Even declaring the object in the resources tab.

Could you share some widget using Apexcharts?

Thank you very much

**Comment by DiogoMesquitaInd** [comment]
>Oi mde2017

Can you provide more details on how you integrated the ApexCharts library into thingsboard? I'm trying but the following error appears:
-ApexCharts is not defined.

Even declaring the object in the resources tab.

Could you share some widget using Apexcharts?

Thank you very much

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
