### ISSUE TITLE
[Feature Request] Add optional Authorization when opening public dashboard

### ISSUE THREAD

**Issue by aljkor** [thingsboard/thingsboard#5853]
I tried using thingsboard public dashboard in my flutter application as a webview/iframe. However, I want to show private device's telemetry on the public dashboard to users who have access to the device. This is why I would like to add a feature, where when you open a public dashboard inside your app, you could send authorization token with it. This would set the `jwt_token` inside localstorage from public JWT to user's JWT and those who have access to the device's telemetry would be able to see data, those who only have a link and public JWT would only see public data inside the dashboard.

Enable sending optional X-Authorization header with Bearer JWT, that changes public  jwt_token inside localstorage to the user's JWT, when you want to load public dashboard. This would enable some users to access private devices telemetry. Users who would have a link and not optional X-Authorization header would receive public JWT as it is implemented right now and would see public data.

Perhaps it could be implemented as a query parameter. So inside a link you would add `&jwt=USER_JWT`. 

Usage:
`webViewController.loadContent(public_TB_dashboard_link, SourceType.url, headers: {"X-Authorization": "USERS_JWT"});`
or
`webViewController.loadContent(public_TB_dashboard_link+"&jwt=USERS_JWT", SourceType.url);`

When the change of the jwt_token would happen in the localstorage, the calls for telemetry would enable user to access private devices' data (if user has permission to access them). Right now, when you open public dashboard it automatically gives you a public JWT that cannot access private device's telemetry.

**Comment by vvlladd28** [comment]
Hi @aljkor,
This feature is available in ThingsBoard. You need to use the query parameter - accessToken, and optional - refreshToken. 
We also have a mobile application written on [flutter app](https://github.com/thingsboard/flutter_thingsboard_app).

**Comment by aljkor** [comment]
Thank you, @vvlladd28 !
Looks like I overlooked this information.

**Comment by codeHui** [comment]
> 
Could you give a example how to add query parameter - accessToken? I tiried the way below but not working, I guess it's the wrong way. Thanks. 
http://xxxx/dashboard/6c54bb50-8663-11ed-877a-a1ceb73f90dc?publicId=7f925e90-04d8-11ee-b455-039d27cbd19e**&accessToken=xxxx**
