### ISSUE TITLE
[Bug] v3.3.2 build fail 

### ISSUE THREAD

**Issue by paullyang** [thingsboard/thingsboard#5854]
when build the v3.3.2 source code, Getting the following error now:

[INFO] Running 'yarn install' in C:\Users\Administrator\eclipse-workspace\thingsboard-3.3.2\thingsboard-3.3.2\ui-ngx
[INFO] yarn install v1.22.4
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[INFO] error Command failed.info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] error Command failed.
[INFO] Exit code: 128
[INFO] Command: git
[INFO] Arguments: ls-remote --tags --heads git://github.com/thingsboard/ngx-flowchart.git
[INFO] Directory: C:\Users\Administrator\eclipse-workspace\thingsboard-3.3.2\thingsboard-3.3.2\ui-ngx
[INFO] Output:
[INFO] fatal: remote error:
[INFO]   The unauthenticated git protocol on port 9418 is no longer supported.
[INFO] Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.087 s
[INFO] Finished at: 2022-01-11T18:58:22+08:00
[INFO] ------------------------------------------------------------------------

Seems git:// URI is no longer supported and it should be changed to https:// for unauthenticated cloning

Thanks

**Comment by VictorHSalvador** [comment]
I am on the same problem. How to resolve?

**Comment by SuperChrisliu** [comment]
@paullyang I am on the same problem. How to resolve?

**Comment by SuperChrisliu** [comment]
see https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported

i replace git://github.com/thingsboard/ngx-flowchart.git with "ngx-flowchart": "https://github.com/thingsboard/ngx-flowchart/archive/refs/heads/release/1.0.0.tar.gz" in package.json file

then `yarn install` can success run 
but get another error:

 /usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run start
yarn run v1.22.17
$ node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve --configuration development --host 0.0.0.0 --open
An unhandled exception occurred: Unexpected end of input

**Comment by SuperChrisliu** [comment]
@paullyang
