### ISSUE TITLE
[Question] Timeout to process [X] messages

### ISSUE THREAD

**Issue by amarkevich** [thingsboard/thingsboard#5855]
**Component**
 * UI /  Rule Engine

**Description**
After some period UI is long responding / 502 HTTP response. CPU and memory usage as usual.
Container logs contain
```
2022-01-11 05:04:58,005 [tb-rule-engine-consumer-43-thread-4 | Main-7] INFO o.t.s.s.q.DefaultTbRuleEngineConsumerService - Timeout to process [1] messages
2022-01-11 05:04:58,005 [tb-rule-engine-consumer-43-thread-4 | Main-7] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [44a6c440-30b0-11ec-b985-bf08606f72d5] Timeout to process message: TbMsg(queueName=Main, id=923a19c6-483d-4540-8cf8-06ad60c492d1, ts=1641877495996, type=POST_TELEMETRY_REQUEST, originator=ec4d0400-59ac-11ec-b86d-e1f1167afba5, customerId=null, metaData=TbMsgMetaData(data={}), dataType=JSON, data={"co2":1387.1}, ruleChainId=ecadac80-59aa-11ec-b86d-e1f1167afba5, ruleNodeId=3ac0b430-59ab-11ec-b86d-e1f1167afba5, ruleNodeExecCounter=0, callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@7316f26a), Last Rule Node: [RuleChain: HVAC alarms|RuleNode: critical co2(82829230-5900-11ec-8d54-3ffc24413577)]
```

Currently only pod restart helps.

**Environment**
 * OS: store/thingsboard/tb-pe:3.3.2PE @ GKE, monolith
 * ThingsBoard: 3.3.2
 * Browser: Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by nastya-kouzma** [comment]
screenshot for a bug is attached
![TB_error](https://user-images.githubusercontent.com/97589990/149086343-41acf54d-d9ef-4fc3-998a-77484f4c818e.png)

**Comment by ashvayka** [comment]
The log message indicates the name of the rule node where the message processing is "stuck". In your case, it is Last Rule Node: [RuleChain: HVAC alarms|RuleNode: critical co2(82829230-5900-11ec-8d54-3ffc24413577)]. Please share the https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics dashboard screens. Most probably, you are using JS functions to process the messages and your JS executors can't keep up with the load. But this is just guessing.

**Comment by nastya-kouzma** [comment]
[image: Screenshot 2022-01-14 at 17.22.12.png]
[image: Screenshot 2022-01-14 at 17.25.55.png]
looks like that. Unfortunately I can't load details for RE. last hour
period is empty, previous periods can't be loaded.
despite the whose app seems to work in a proper way, i can't delete the
mentioned rule chain, it ends up in the same error.

**Comment by nastya-kouzma** [comment]
[image: Screenshot 2022-01-14 at 17.58.39.png]

**Comment by nastya-kouzma** [comment]
@ashvayka , I've succeeded to delete a rule chain you've mentioned, however, I still get the same error:
![image](https://user-images.githubusercontent.com/97589990/149720342-7ec79217-d610-4afb-9fcc-0375661734de.png)

**Comment by nastya-kouzma** [comment]
@ashvayka , Thingsboard keeps on showing 502 error. Now it's also showed during authentication attempts:
![image](https://user-images.githubusercontent.com/97589990/150494502-44cf6492-0714-4032-8fdd-a7fb526f3f42.png)

Such patterns make an app useless for us, since we can't invite customers.. Please, let us know, how we could deal with this error.

**Comment by trikimiki** [comment]
Can you please share your log file, preferably after you get the error?

**Comment by amarkevich** [comment]
some generators running which cause this timeouts

**Comment by nastya-kouzma** [comment]
> Can you please share your log file, preferably after you get the error?

we used rule chains for telemetry generation with sending period 1s. now it's updated to 30s and everything looks ok.
are there any thresholds for performance? what are minimum values for sending telemetry from generator to provide stable work of app?
