### ISSUE TITLE
[Question] Customer account unable to see data in dashboards

### ISSUE THREAD

**Issue by fabioafreitas** [thingsboard/thingsboard#5858]
**Component**
 * Generic

**Description**
I've just installed a thingsboard server on a VM in Google Cloud, following the steps shown in the [official tutorial](https://thingsboard.io/docs/user-guide/install/ubuntu/). The installation went smoothly, and i can access all the features with the tenant account without problems. However, when i try to access any default dashboard, created during the installation, or custom ones with a customer account the data simply doesn't show up.

Dashboard image logged in as customer
![image](https://user-images.githubusercontent.com/20552037/149031406-a6f55f29-0ab3-4cec-8f37-0038d3510b2b.png)

Same dashboard logged in as tenant
![image](https://user-images.githubusercontent.com/20552037/149031525-de3dce64-2ebf-4781-b7b3-7e03348ae5fc.png)

Is there any configuration i need to do to the data so that the data appears for costumers?

**Environment**
 * OS:  Debian GNU/Linux 10 (buster)
 * ThingsBoard: v3.3.2
 * Browser: Google Chrome v96.0.4664.110 64bits

**Comment by mde2017** [comment]
Hi @fabioafreitas,

the dashboard displays only data from assigned devices and assets. 
Did you also assign the Thermostats devices to the customer?

**Comment by fabioafreitas** [comment]
Hi @mde2017 ,

Thanks for the response, it seems that this is exactly what was missing. I just assigned the devices to the customer and the dashboard started working. Thank you!!
