### ISSUE TITLE
[Bug] Grouping hourly gives half-hour timeframes when filtering in Chart

### ISSUE THREAD

**Issue by erwinberkouwer** [thingsboard/thingsboard#5863]
**Describe the bug**

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**
* Browser [e.g. chrome, safari]

* Connectivity
  * MQTT

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'A chart'
3. Scroll down to 'Timeframe'

**Expected behavior**
When I group a chart (or another widget) on hour basis and for example the history of 1 day I get a timeframe of every half hour instead of every rounded hour. 
![Capture](https://user-images.githubusercontent.com/56593791/149134254-56f7a9a7-6578-47af-a6cc-581b1a3e196c.PNG)

**Screenshots**

**Additional context**

**Comment by kalutkaz** [comment]
Hi @erwinberkouwer. As I understand it, you just misunderstood the meaning of this setting. 

The timewindow in the timeseries table sets the hour interval for displaying telemetry. For example, on the screen you set 'Realtime - last 12 hours', it means that table should display all telemetries that we get for the last 12 hours. This setting doesn't control the time when we get telemetry.

**Comment by erwinberkouwer** [comment]
@kalutkaz Thanks for the reply, I get the same result when I choose the history tab. Grouping on '2 hours' is working, but the 1 hour is giving the 11:30 and 12:30 instead of the 11:00 and 12:00 timeframe for example. I hope you can help me out! Cause the telemetry data is coming in every second.

**Comment by kalutkaz** [comment]
@erwinberkouwer I checked your issue. When we set some value in the grouping interval we visualization the average value for the timestamp.   

For example, we have some telemetries with timestamp 15.1x.xx:
![image](https://user-images.githubusercontent.com/43555187/149153698-87b21aad-59de-4b8b-ba33-47829ee92028.png)

We set the grouping interval one hour, which means that we have 24 intervals (0-1, 1-2, ..., 15-16, ...). For all of this intervals we generate table`s row with average timestamp (0-1 -> 0.30, 1-2 -> 1.30, ..., 15-16 -> 15.30, ...) and visualize the information for this time interval:
![image](https://user-images.githubusercontent.com/43555187/149155364-3df5c576-dd99-41d2-a7b2-adf5a1d155c2.png)
As you can see now we have one telemetry with an average timestamp 15.30 for time interval 15.00 - 16.00.

The same logic for other grouping interval values. If we selected 30 minutes we have time interval 00.00-00.30, 00.30-01.00, ..., 15.00-15.30,... With average timestamp 00.15, 00.45, ..., 15.15, ... :
![image](https://user-images.githubusercontent.com/43555187/149156015-5def54f1-fe0e-476d-a8ae-463a3b585ef0.png)

Hope that helps you.

**Comment by erwinberkouwer** [comment]
Thanks a lot! This is really helpfull!
