### ISSUE TITLE
[Question] Display second to last and not the latest values

### ISSUE THREAD

**Issue by irdet2** [thingsboard/thingsboard#5867]
**Component**

 * UI

**Description**
My devices are sending a group of timeseries values in ThingsBoard (e.g. Timestamp, Latitude, Longitude etc.). 
In a dashboard I would like to show not the latest but the second to last (penultimate) values.
For example let's say that I have the following values 
Timestamp=t 
Latitude=y(t)
Longitude=x(t)
and those are the latest ones.

I would like to be able to get the values at T=(t-1) for all of them so in the above example I would like to be able to get
Timestamp=t-1
Latitude=y(t-1)
Longitude=x(t-1) 
where "t-1" means one value before the latest (second to last or penultimate).

I understand that I may be able to get a part of this by adjusting the timeframe at the dashboard but this doesn't help because not all devices transmit at the same time.

So, could this be achieved somehow either by manipulating the widgets or the rule chains or with any other way?

I am looking forward to hear your thoughts and ideas!

**Environment**

 * OS: CentOS v.8 (latest)
 * ThingsBoard: 3.3.2
 * Browser: Firefox 96 and/or Chrome 97 and/or Safari 15 (for both desktop and mobile devices)

**Comment by dhaval2017** [comment]
@irdet2 
What do you think of storing t-1 telemetry value as different key and update in rulechain whenever there is update in telemetry value

lets say current telemetry value is
Timestamp=t
Latitude=y
Longitude=x

now when get new data 
Timestamp=t2
Latitude=y2
Longitude=x2

in rulechain first get the latest telemetry which is 
Timestamp=t
Latitude=y
Longitude=x 

update it with 
_Timestamp=t
_Latitude=y
_Longitude=x 
Timestamp=t2
Latitude=y2
Longitude=x2


on dashboard you can show below values for t-1 value
_Timestamp=t
_Latitude=y
_Longitude=x

**Comment by irdet2** [comment]
Hi! Thanks for pointing this out. Besides that I think that I would also need to do a comparison between the already existing data and the newly arrived because is doesn't mean that the new one would be different. 

So, thinking of it again I don't actually need the exact previous value but the previous value that is different from the new one. 
What do you think about it? Would your suggestion work including a comparison?

But what if I want to keep/show the last five that are different from one another? How would I achieve that? Is there a more efficient way?

Thanks!

**Comment by dhaval2017** [comment]
@irdet2 
No need to do compression
When you fetch already existing data latest data it will be stored in different variable name compare to newly arrived data

**Comment by irdet2** [comment]
Hello @dhaval2017,

I am sorry but I don't get it how this can be done.

Let's say a device transmits location coordinates in two variables (longitude, latitude) and those are stored in ThingsBoard db.

In a few minutes it transmits them again but are the same so I don't need a new variable since I already have them stored. This can be done many times until at some point the location changes. So, this is the point that I want a new variable with the new coordinates to be stored. 
That's why I am saying I would need comparison, in order to see if it has changed with the previous or not and if so then it should be stored to a new variable. Maybe there is an automatic way that I am not aware so please elaborate if you can!

Additionally, is there a way for this to auto scale for the different locations every time or should I have let's say hard-coded the number of previous locations that can be stored?

Thank you!

**Comment by dhaval2017** [comment]
@irdet2 can you use server attribute?

whenever you get new coordinates do following

Compare with previous coordinates which is stored as server attribute of device/asset
if both are same and no need to update ignore it
else update coordinates in server attribute

visualize that server attribute at place where you want to show location coordinates for t-1 time


**Additionally, is there a way for this to auto scale for the different locations every time or should I have let's say hard-coded the number of previous locations that can be stored?**
I didnt got your this question

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
