### ISSUE TITLE
[Request] Update to Eclipse/Californium 2.7.0 or 3.2.0?

### ISSUE THREAD

**Issue by boaks** [thingsboard/thingsboard#5868]
The currently used Eclipse/Californium version 2.6.1 is about 1 year old.

In the meantime a couple of bugs have been fixed. It's recommended to update at least to 2.7.0.

Let me add, that the [Upcoming RFC 9146](https://www.rfc-editor.org/rfc/authors/rfc9146.html) requires to migrate to Californium version 3. Today the 3.2.0 gets releases. Together with my work in [Eclipse/tinyDtls](https://github.com/eclipse/tinydtls) this enables to use CoAP/DTLS CID very efficient, very reliable, and very scalable.

I build an example demo for the [Thingy 91](https://www.nordicsemi.com/Products/nRF9160) to demonstrate, how energy saving (PSM) and DTLS CID plays together, true e2e encryption over a week with changing assigned ip-addresses. I currently plan to publish that client in Q2/2022.

**Comment by boaks** [comment]
I forgot to mention, that there is a [MIGRATION_HINTS](https://github.com/eclipse/californium/blob/master/MIGRATION_HINTS.md) to help to migrate to 3.0. And for sure, if some questions are left, don't hesitate to [open an issue](https://github.com/eclipse/californium/issues/new/choose).

**Comment by ashvayka** [comment]
Thank you for noting this. We will update.
