### ISSUE TITLE
String item being interpreted as numeric

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#587]
I get this json when I retrieve my client_attributes:

[{'lastUpdateTs': 1518819505082, 'key': 'sampleDuration', 'value': 30}, {'lastUpdateTs': 1518819505082, 'key': 'firmwareVersion', 'value': '0.110'}]

Notice that firmwareVersion is a string.

When I display that value on a widget, it appears to have become a number:

![image](https://user-images.githubusercontent.com/1133323/36332909-03c557f0-1329-11e8-8aec-a42f234eedb9.png), 
![image](https://user-images.githubusercontent.com/1133323/36332964-38b53aca-1329-11e8-95b5-a2200a169cd0.png)

The UI seems to be incorrectly handling string data that appears numeric.

**Comment by vparomskiy** [comment]
fixed in the Thingsboard 2.2

**Comment by bskrt** [comment]
Just ran into the same issue running TB 2.4.3 PE.

I'm getting device ids over mqtt that are strings of the following type:  `31534147313130300083212353937`.

In the received json they are still strings, in the database too (stored in str_v column), but once I try to show them in an entities table widget, the string becomes a number.

I checked this by doing a post-processing `return typeof(equipment_id)` which showed up as number.

Is this maybe a bug on the entities table widget specifically?

**Comment by Regimbal** [comment]
Same problem here with CE v2.4.3
This leads strings values beginning with some specific characters (0, + etc...) to be truncated.
I observed it on Attribute Card widget, and Input widgets two.
