### ISSUE TITLE
[Question] Create new Asset from Public Dashboard

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#5877]
**Component**

 * Generic

**Description**
I have created a dashboard with a form, where any user with the dashboard link can access. I would like that as soon as the form data is submitted, an asset is created with the data from that form.

The logic is developed in the widget, and if I access the dashboard with an authenticated user, the asset is generated correctly and assigned to the active user.
The problem comes when the panel is public and the user who accesses it is not authenticated. It gives me an error that I do not have sufficient permissions since it cannot assign the asset to any Tenant since there are none authenticated.

I would like to know if through the assetService.saveAsset function or some similar one, it would be possible to indicate the TenantId to which to save it and thus not give the permission error.

**Environment**

 * ThingsBoard: 3.3.2 CE

**Comment by ashvayka** [comment]
The check for the permission is on the server-side. So if you pass the tenantId/UserId parameters, you will still receive an error. Actually, this is not doable in CE without code changes. And it is a security issue since public users are disallowed to create assets intentionally.
