### ISSUE TITLE
Add device, get its token and modify it in programmatically way

### ISSUE THREAD

**Issue by PP90** [thingsboard/thingsboard#588]
It looks like that the only way to add a device and then get the generated access token is via the GUI as explained in the guide. 
Is there any way to create a device and then get the token (and optionally change it)  in a programmatically way ? Is there any available API to do that ?

Thank you.

**Comment by eykamp** [comment]
There is.  I wrote a script to add a new device, configure it, and do some other things.  You can see it there:

https://github.com/eykamp/birdhouse/blob/master/management/provision.py

You'll also need my tbapi library (very incomplete and subject to change) which can be installed using the pip command listed in the code.

You'll likely want to do less/something else, but this will get you started.  If you find there are things you need missing from the api lib (there's far more missing than present), and feel motivated to add them, be sure to send me a PR.

**Comment by vparomskiy** [comment]
Here is API for getting device token by deviceID
https://demo.thingsboard.io/swagger-ui.html#!/device-controller/getDeviceCredentialsByDeviceIdUsingGET

**Comment by PP90** [comment]
It is a very good starting point for my purposes. Since I am developing in Java language, I am more interested to the interaction mechanisms with thingsboard rather than the implementation itself.

Thanks again.

**Comment by vparomskiy** [comment]
Then you can take a look at DeviceController class. Method - getDeviceCredentialsByDeviceId()
It returns DeviceCredentials object. It should be easy for you to implement RestClient based on spring restTemplate that will do authorization.

**Comment by boopathi033** [comment]
How to pass credentials for a DeviceID

**Comment by vparomskiy** [comment]
Did you read device API documentation? There you can find how to pass device credentials.

**Comment by Karabiy** [comment]
you can use the Rest API of the ThingsBoard for those reasons.
you can refer to this link regarding the on how to use the REST API: https://thingsboard.io/docs/reference/rest-api/
also, you can get a better understanding of which exact API endpoint and params can be used for the request of yours in case if you will go with an F12 and inspect the networking. So that you can have different examples to test

**Comment by mm-1994** [comment]
Hi All 
i have a question 
in device admin widget i would like to create device and change its access token to an input

how can i do so 

code i am using : 

let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

openAddDeviceDialog();

function openAddDeviceDialog() {
    customDialog.customDialog(htmlTemplate, AddDeviceDialogController).subscribe();
}

function AddDeviceDialogController(instance) {
    let vm = instance;
    
    vm.addDeviceFormGroup = vm.fb.group({
      deviceName: ['', [vm.validators.required]],
      deviceType: ['', [vm.validators.required]],
      deviceLabel: [''],
      attributes: vm.fb.group({
          latitude: [null],
          longitude: [null]
      })      
    });
    
    vm.cancel = function() {
        vm.dialogRef.close(null);
    };
    
    vm.save = function() {
        vm.addDeviceFormGroup.markAsPristine();
        let device = {
            name: vm.addDeviceFormGroup.get('deviceName').value,
            type: vm.addDeviceFormGroup.get('deviceType').value,
            label: vm.addDeviceFormGroup.get('deviceLabel').value
        };
        let device2 = {
            createdTime: 0,
            credentialsId: "string",
            credentialsType: "ACCESS_TOKEN",
            credentialsValue: "123",
            id:"string"
            
            
        };
        deviceService.saveDevice(device).subscribe(
            function (device) {
                saveAttributes(device.id).subscribe(
                    function () {
                        widgetContext.updateAliases();
                        vm.dialogRef.close(null);
                    }
                );
            }
        );
       deviceService.saveDeviceCredentials(device2).subscribe();
        
           
    }
    function saveAttributes(entityId) {
        let attributes = vm.addDeviceFormGroup.get('attributes').value;
        let attributesArray = [];
        for (let key in attributes) {
            attributesArray.push({key: key, value: attributes[key]});
        }
        if (attributesArray.length > 0) {
            return attributeService.saveEntityAttributes(entityId, "SERVER_SCOPE", attributesArray);
        } else {
            return widgetContext.rxjs.of([]);
        }
    }
}

**Comment by Karabiy** [comment]
@mm-1994 the issue is closed already. You can create a new issue for those, so that those may be reviewed and answered.
