### ISSUE TITLE
Where to find the documentation?

### ISSUE THREAD

**Issue by Kevinowitsch** [thingsboard/thingsboard#5885]
**Component**

 * Generic

**Description**
In another post @ashvayka wrote that there is a documentation since v3.2.
I'm looking for things like:
- widgetContext in custom action
- nodeCtx (hierarchy, something has changed in v3)
- data (tooltip etc)
- etc

**Environment**
 * OS:  Windows 7
 * ThingsBoard: PE 3.3.2
 * Browser: Firefox 96.0 (64Bit)

**Comment by ashvayka** [comment]
See https://github.com/thingsboard/thingsboard-ui-help or click the "?" icon that corresponds to any place where you input the custom code. For example: 

![image](https://user-images.githubusercontent.com/5016373/149524591-90a747b6-5220-4c29-817e-be85415592cf.png)

**Comment by Kevinowitsch** [comment]
I didn't have the help mode activated. Thats why I didn't see the "?" icon.
