### ISSUE TITLE
[Question] Inconsistent Settings for Widget UI

### ISSUE THREAD

**Issue by Eric-Willoughby** [thingsboard/thingsboard#5886]
**Component**
 * Widgets and Tables
 * UI

**Description**
Widget UI in ThingsBoard do not have a consistent way to update the title. Some widgets use the settings tab while others need to use the advanced tab. It seems like admin widgets (Alarms, Assets admin table, Device admin table, etc) are set with the advanced tab versus others all just using the settings tab. What is the reason for this? If there is one.

 - Go to Dashboards and select the plus icon (+) then create new Device admin table.
 - Give it whatever values you want and save it.
 - Go to the widget that was just created and select the pencil edit icon and try to change the title name and save under the advanced tab.
 - Do this again, but create a time series chart of your choosing instead.
 - Notice that you have to use the settings tab for the time series chart and advanced tab for the device admin to update the title.

**Environment**
 * Server side: Docker/Ubuntu 20.04
 * Client side: Windows 10 Enterprise version 1809
 * ThingsBoard Version 3.3
 * Browser Chrome

**Comment by ashaforost** [comment]
Hi @Eric-Willoughby 

The simple explanation to different methods of title setting is that the title field in the 'settings' tab is just a string field, but the same field in the 'advanced' tab can parse dynamic values such {i18n} structure or entity fields (i.e., ${entityName}) 
Moreover, the setting tab is the default tab for all our widgets, they are all basically made from one template. 

Please see the following examples:
![image](https://user-images.githubusercontent.com/47900737/151342160-fb6a1f24-2b6a-465b-9698-16791f9546e2.png)
![image](https://user-images.githubusercontent.com/47900737/151342253-ea019c52-1084-470d-8b55-7c1e4abb4e76.png)

**Comment by Civilduino** [comment]
That is a nice trick to use {i18n}, you should create a "trick" section in the documentation :)

However, not all widgets have a title option in the advance section, for example, the time series charts. How would you fix the title with ${entityName} in that case?
