### ISSUE TITLE
[Bug] Navigating to Other dashboard using Action button links to an editable page

### ISSUE THREAD

**Issue by robert-long** [thingsboard/thingsboard#5887]
**Bug**
When using Action Cell Button to Navigate to other dashboard, other dashboard presents with an edit Icon in lower right corner.

**Server Environment**
* Own Setup
  * Docker Deployment
  * ThingsBoard Version 3.3.2-PE
  * Ubuntu 20

**Your Client Environment**
**Desktop 1**
* OS: Win 10
* Browser: Chrome & Firefox

**Desktop 2**
* OS: Ubuntu
* Browser: Firefox

**To Reproduce**
1. Create New Dashboard
2. Add Entity table to dashboard 
3. Add Action cell button to table that navigates to other dashboard
4. Got to first new dashboard
5. use newly created button to navigate to new dashboard

**Expected behavior**
When navigating using the action button you should be greeted with a dashboard, without the ability to use the edit button

**Screenshots**

![home](https://user-images.githubusercontent.com/87493438/149423608-17080212-e317-4461-8941-54e388447ffb.jpg)
This is a new dashboard home page

![home_setup3](https://user-images.githubusercontent.com/87493438/149423672-017c8113-4724-4205-915a-65ba901a7c62.jpg)
this is the configuration of the action button

![details page](https://user-images.githubusercontent.com/87493438/149423695-55a0face-225a-49cc-954f-97d388bc2a2d.jpg)
this is the temp page that was navigated to using the action button referenced above

![details](https://user-images.githubusercontent.com/87493438/149423792-bf9ff5ba-4563-4b38-ab0f-7401bafb6f46.jpg)
this is the exact same instance after upgrading to thingsboard 3.3.2 PE (note the edit button in the lower right hand corner)

**Comment by vvlladd28** [comment]
Hi @robert-long,
Thank you for your report. We will fix this issue in the next release of TB.

**Comment by robert-long** [comment]
So this issue is still occurring.

When navigating to a new dashboard using a widget header action, the new dashboard that it navigates to shows the "edit" button in the lower right hand corner. This is showing up for all of the users .

see attached photo
![Capture](https://user-images.githubusercontent.com/87493438/185658686-568718c0-b9bf-4930-86c3-8e05c8ab96a2.JPG)
