### ISSUE TITLE
[Question] How to send repeated RPC commands until a condition is met using Integration Downlink?

### ISSUE THREAD

**Issue by santobedi** [thingsboard/thingsboard#5888]
I'm using Integration Downlink (Chirpstack) to receive telemetry (Modbus RTU responses) from a RAK7431 end node and send RPC commands switching (On/Off) the Modbus relay connected to it. In the TB, the RPC command is initiated from the Switch Control (Control Widget) in the dashboard. Here, the Switch Control Subscribes for Timeseries (On/Off status of the relay). 

Depending on the network condition and radio environment (LoRaWAN), every RPC command does not necessarily reach the end node (RAK7431). Moreover, Integration Downlink supports only one-way RPC (although I've not figured out yet about using the getValue method if it would have supported two-way too). 

In this condition, I want to (a) send RPC from by clicking a button in Switch Control, (b) add delay for a few milliseconds (give some time to operate), and (c) Check the Timeseries (On/Off status of the relay), if the status is unchanged, send the RPC again. 

How can I achieve it? 

Thank you. 

**Environment**

 * ThingsBoard: 3.3.2PE

**Comment by santobedi** [comment]
@samson0v

**Comment by santobedi** [comment]
Solved it by designing our own Control Widget.

**Comment by xiaoyu4122** [comment]
Hi，I met the same peoblem. Would you mind sharing the way?
