### ISSUE TITLE
Thingsboard help! 

### ISSUE THREAD

**Issue by CristianMendivelso** [thingsboard/thingsboard#589]
Hi, I'm trying to find this uri ( /api/plugins/telemetry/ASSET/18cddbc0-1588-11e8-b191-019c092573b4/timeseries/values ) in the source of thingsboard, because that uri is used in the spark and kafka IoT data analyitics example, I want to know how thingsboard receive the telemetry values. Thanks

**Comment by mp-loki** [comment]
org.thingsboard.server.controller.plugin.PluginApiController

**Comment by CristianMendivelso** [comment]
Thanks a lot!
