### ISSUE TITLE
Facilitate localization

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#59]
I would like to contribute to the project by translating the user interface to Romanian. It would be great if the entry  barrier for translators were lowered, here is what could help me get started:

* a "How to contribute" guide that explains (1) how to create a new locale, (2) which files to edit, (3) what tools to use and (4) how to test the translation. Having looked around the source I think that this is where all the strings are, but I am not sure: https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/locale/locale.constant.js. 
* Thingsboard could register at Transifex, or a similar site, where people could contribute translations via a nice web-interface (the previously described method requires one to know git in order to make a fork, then send a pull request with a translation)
* Or maybe use some other tool like Stringlate (though this one is Android-only), which would allow anyone who speaks a foreign language do the translation, while having no programming skills.

**Comment by ashvayka** [comment]
This is a valid points, we will add "How to contribute" guide to our backlog.

**Comment by nikil511** [comment]
+1 on Transifex

**Comment by ralienpp** [comment]
I started working on a Romanian translation and am willing to write the corresponding section of the `how to contribute` guide, based on my workflow.

What should it be written in? RST? Markdown? LaTeX? Is the manual itself a project somewhere on Github?

**Comment by mcicolella** [comment]
Any update about this issue? I'd like to work on Italian translation but it had better to use any platform as Transifex to manage contributions.

**Comment by fotis400** [comment]
Same here. I would like to contribute a Greek translation, and a solution like Transifex would be nice.

Also. How you guys _test_ the translation? It is almost impossible to follow all strings through all the code to see their use. It is also very difficult to check all UI screens.
Any suggestions? Or a workflow to follow?

**Comment by dyosick** [comment]
Hi, guys
Hope [this PR](https://github.com/thingsboard/thingsboard/pull/941) helps to implement the idea discussed here.

**Comment by ashvayka** [comment]
Since both Greek and Italian translations are now available, I am closing this issue. Now it is sufficient to contribute only one JSON file with [locale](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale), and our team will do the rest.
