### ISSUE TITLE
[Feature Request] dynamic setting Highlights for Analogue gauges Widget!

### ISSUE THREAD

**Issue by Tpro4391** [thingsboard/thingsboard#5902]
**Is your feature request related to a problem? Please describe.**
I find "Analog gauges" very suitable for simulating mechanical watches.
However the Highlights thresholds of "Analogue gauges" are fixed (From, to use numbers) I want it to be setable like "Value taken from entity attribute"

**Describe the solution you'd like**
It would be great to be able to set [From] Value source and [To] Value source with "Value taken from entity attribute" same as "Digital gauges" for Highlights

**Comment by ashaforost** [comment]
Hi @Tpro4391 

Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1346) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
