### ISSUE TITLE
[Feature Request] Request all shared attributes from MQTT Gateway API

### ISSUE THREAD

**Issue by adw128** [thingsboard/thingsboard#5906]
I have done some investigation through the code and I want to request all the shared attributes from thingsboard.  I've been trying to use the documentation as https://thingsboard.io/docs/reference/gateway-mqtt-api/#request-attribute-values-from-the-server, but it doesn't show you how to request all attributes. I've tried using: "*", "", ".*" to no effect.

I've searched through the existing issues but can't find any relevant ones. What's the best way to request all attributes? 

Cc: @pbrkr

**Comment by volodymyr-babak** [comment]
hi @adw128 you can request all SHARED attributes from MQTT Gateway API with the next command:
**{"id": $request_id, "device": "Device A", "client": false, "keys": []}**

Please re-open the ticket if this will not work for you.

**Comment by mcavalcante** [comment]
> hi @adw128 you can request all SHARED attributes from MQTT Gateway API with the next command: **{"id": $request_id, "device": "Device A", "client": false, "keys": []}**
> 
> Please re-open the ticket if this will not work for you.

Hello @volodymyr-babak ,

I tried to request all shared attributes from Arduino using MQTT, as explained by you, but it didn´t work. Does it still work for the newer ThingsBoard version (3.4.x)? 

Thanks.

**Comment by ospmoon** [comment]
> > hi @adw128 you can request all SHARED attributes from MQTT Gateway API with the next command: **{"id": $request_id, "device": "Device A", "client": false, "keys": []}**
> > Please re-open the ticket if this will not work for you.
> 
> Hello @volodymyr-babak ,
> 
> I tried to request all shared attributes from Arduino using MQTT, as explained by you, but it didn´t work. Does it still work for the newer ThingsBoard version (3.4.x)?
> 
> Thanks.

I checked and it works!

if it doesn't work for you,
I can advise you a few steps:
1) subscribe to topics
subscribe("v1/gateway/attributes/response");
subscribe("v1/gateway/attributes");

2) and take a close look at the last key in the payload
there should be "keys" but not "key".
payload ="{\"id\":1, \"device\":\"device_0\", \"client\": false, \"keys\": []}";

Good luck.

**Comment by eleicsjaivik** [comment]
It would be have great addition to the main document
I found it in github issues, the position of it should be in main docs.
