### ISSUE TITLE
[Question] How to Avoid Auto language change  ?

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5909]
Hi,

The Thingsboard system changes automatically according to my computer's language setting. How can we change this automatic language change we want from the configuration? What steps should be followed to perform this operation?

![Seçim_002](https://user-images.githubusercontent.com/91528436/149779106-e0324455-f7a3-4f8d-a2c3-435264f865f3.png)
![Seçim_001](https://user-images.githubusercontent.com/91528436/149779109-6eb7ebc9-a201-4740-99c4-98b74deba101.png)

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by ashaforost** [comment]
Hi @gohm-tech 

Thingsboard UI, by default, uses the locale that’s set in your browser. The only way to change the profile language is manually set the language in the Thingsboard profile setting. However, the default language for all newly created users will be set to their browser locale.

**Comment by claezon** [comment]
I recently noticed this as well. We are getting customers all over the world and this mishmash of different languages/missing translations is not a good UX. It should definitely be possible to whitelist languages!
