### ISSUE TITLE
PostgreSQL vs Cassandra for Thingsboard

### ISSUE THREAD

**Issue by m-menon** [thingsboard/thingsboard#591]
hi, just wanted to know which database is best suited for Thingsboard? PostgreSQL OR Cassandra? I am planning to test it thoroughly before planning any real deployments. Wouldn't want to use the embedded HSQLDB because the testing set up has to be as close as possible to real deployment. Thanks

**Comment by vparomskiy** [comment]
Cassandra is a main option for thingsboard because it is much faster for timeseries data and big dataset aggregation

**Comment by m-menon** [comment]
Thanks a lot for the clarification :+1:
