### ISSUE TITLE
[Question] What are the functional differences between Community Edition and professional edition?

### ISSUE THREAD

**Issue by bggmjxh** [thingsboard/thingsboard#5911]
What are the functional differences between Community Edition and professional edition?

**Comment by bggmjxh** [comment]
I need to evaluate whether the additional functions of the professional version relative to the community version will be used in the next few years. If so, I can consider purchasing the professional version directly.

**Comment by serfreeman1337** [comment]
You can check [Feature Comparison Matrix](https://thingsboard.io/products/thingsboard-pe/).

**Comment by bggmjxh** [comment]
·Rule Engine: Components

·NB-IoT, SigFox, LoRaWAN support

What is the difference between "basic" and "advanced" in these two items?

**Comment by serfreeman1337** [comment]
PE has additional rule engine nodes. 
Search for "ThingsBoard PE Feature" on these pages: [action nodes](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/action-nodes/), [transformation nodes](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/transformation-nodes/), [analytics nodes](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/analytics-nodes/).

I think basic support for NB-IoT, SigFox, LoRaWAN devices in CE means that you can actually connect them by writing your own connector (Like: device --UDP--> your UDP Converter --HTTP--> Thingsboard), whereas PE has numerous [platform integration](https://thingsboard.io/docs/user-guide/integrations/).

**Comment by KenSense** [comment]
There were a few things important for us:
The integrations/data conversion and the white labeling so you can put your company logo on the website. (white labeling only starts from $99)
You also get extra levels of user security settings and setups (although there some bugs in there), if you plans to have customers on it then you can't really stay with CE. (check  Customers hierarchy in PE)

We started with CE to check it out then later we replaced it with a PE version to add lora and now it is running public.

**Comment by Ultrazombie** [comment]
@bggmjxh Hello, 
You can read the difference at this link:
https://thingsboard.io/products/thingsboard-pe/   (Feature Comparison Matrix  Block)

**Comment by debacs83** [comment]
Hello,

Is it possible to send data from AWS Lambda to ThingsBoard, installed in AWS EC2 instance for ThingsBoard Community Edition? I have read that it is possible with ThingBoard PE with the IoT Integration feature, but want to know if it can be done with CE also. And if so, how to achieve that. 

Any help would be very much appreciated. 

ps. I have used ThingsBoard installing in Ubuntu 20.04 (on-premise) previously and loved its features and ease of use. Wanted to try with AWS.
