### ISSUE TITLE
What is the optimal value of ui.dashboard.max_datapoints_limit, DASHBOARD_MAX_DATAPOINTS_LIMIT?

### ISSUE THREAD

**Issue by Pankaj9410557422** [thingsboard/thingsboard#5916]
I want to know what is the optimal value of the DASHBOARD_MAX_DATAPOINTS_LIMIT in the yml file as i changed it to 2 million to get monthly data on my custom dashboard from that day onwards my server gets error whenever i open the dashboard. 
Can anyone help me out with this scenario. I only changed the value of this parameter do i need to change some other parameters also in order to work in an optimized way

**Comment by Ultrazombie** [comment]
@Pankaj9410557422 Hello,
The optimal value is precisely 50,000, but everyone can change it to suit their needs. Please provide the error that appears after changing this parameter to help you.
