### ISSUE TITLE
Can tb-navigation-card-widget will navigate outside the thingsboard like www.google.com

### ISSUE THREAD

**Issue by BhushanPDS** [thingsboard/thingsboard#5920]
**Component**

 * UI
 

**Description**
I am using navigation card ,which is currently only rendering inside thingsboard ,So  need card which can render outside the thingsboard

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.2
 * Browser: chrome

**Comment by ashaforost** [comment]
Hi @BhushanPDS 

The navigation card was developed to add links only to the internal thingsboard components.
If you want to create a button that will redirect you to another service, you can use an HTML card widget, which is most commonly used for the static image display and link insertion.
