### ISSUE TITLE
ThingsBoard : How to access list of users via JavaScript in the Dashboard?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#5934]
**Component**
 * UI

**Description**
We have one dashboard where a list of customers are displayed. 
There is an action button provided on each row called "Manage Users" which will take to another dashboard state where a list of users are displayed.
With "Add" action provided on header, a popup dialog opens to create new user under that customer.
When we logged in as a Tenant Admin & use this "Add New User" option, it's not creating user under that particular customer instead it's creating user at Tenant level.
After reading the JavaScript written for the "Add New User" action, there is missing "Customer" details.
So, how to access customer details from the parent dashboard state into JavaScript?

Please, your help would be very much appreciated.

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.3.x ( PaaS Instance )
 * Browser: Chrome 97.0

**Comment by JacksonBowe** [comment]
Assuming you have your dashboard set up such that the selected customer is the active "state entity". In this case you pass the state entity (the selected customer) into the widget you mentioned above, from here you can access the customerId in the code for the "Add" header button.

Just my best guess from the details you've provided, gl

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
