### ISSUE TITLE
ThingsBoard : What would be the "Navigation Path" in Navigation Card Widget?

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#5935]
**Component**
 * UI

**Description**
We have used a "Navigation Card" which is used to navigate to another dashboard state.
For this, we have to provide a "Navigation Path" parameter. 

What is the proper way/syntax for this "Navigation Path" in order to navigate to another dashboard state?
![Untitled](https://user-images.githubusercontent.com/38416893/150334515-e74bdcfb-6a98-454e-988f-70232eac2fc3.png)

Please provide your suggestion.

**Environment**

 * OS:  Windows10
 * ThingsBoard: 3.3.x ( PaaS Instance )
 * Browser: Chrome 97.0

**Comment by ashaforost** [comment]
Hi @bhimashankarP

To navigate to other dashboard state you just need to paste the link to this state to the path of the Navigation widget:
http://</host/>**/dashboardGroups/9d216bc0-45f5-11ec-9127-0b0fd6aa30ae/1d4e27e0-751f-11ec-9e37-5da303062035?state=W3siaWQiOiJuZXciLCJwYXJhbXMiOnt9fV0%253D**

Here's a code snippet from this widget, as you can see, it only accepts the path to the page, no dynamic values or domains allowed:
https://github.com/thingsboard/thingsboard/blob/da4c74287216fc6962c74f084c2eedebf06e1a64/ui-ngx/src/app/modules/home/components/widget/lib/navigation-card-widget.component.ts#L59
