### ISSUE TITLE
[Question] MQTT Profile /telemetry and /telemetry1 also to Telemetry Topic filter

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#5939]
**Component**
 * Generic

**Description**
Transport Configuration: MQTT Device Profile Topic Filter
Can I define some variations of names, the wild cards do not seem to allow that?
I want like:
/telemetry and /telemetry1 and /telemetry2 to Telemetry topic
/attributes and /attributes1 and /attributes2 to Attributes topic

Thanks

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.2

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
