### ISSUE TITLE
SureFire plugin Error

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#594]
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ethics/Downloads/thingsboard-master/application/target/surefire-reports for the individual test results.

**Comment by gopirathnamt** [comment]
why you closed the issue ?
it isn't solved yet

**Comment by mp-loki** [comment]
> There are test failures
Means that you were building from source and some tests failed, probably because of your code changes. Please, check why the tests were failing and try to fix them, then rebuild.

**Comment by gopirathnamt** [comment]
i used -DskipTests and it resolved
