### ISSUE TITLE
Is it possible to use Google Maps API to get longitude and latitude from an address ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5941]
Hello,

I would like to know if it is possible to get the latitude and longitude from an address using the Google Maps API ? 
The address is provided by the attributes of an asset.
I tried to do it but I got a Cross Origin Read Blocking (CORS) error. 

Best regards,

Lucas

**Comment by mde2017** [comment]
Hi @lucasKapf,

this should be possible via rulechains and the REST API Call nodes.
The process you would like to perform is called Geocoding. There are several API's available to do this (commercial & free).
Some examples:

https://developers.google.com/maps/documentation/geocoding/overview (restricted free version, Google Maps)
https://nominatim.org/release-docs/develop/api/Overview/ (free, based on OSM)

**Comment by lucasKapf** [comment]
Hi @mde2017, thank you for your quick answer. I didn't know I could achieve this via Rule Chains.
The thing is I only have message sent from my devices in my rule chains, how can I have message when an asset is created from my dashboard ?
