### ISSUE TITLE
[Question] Manage multipart response rule chain node

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#5943]
**Component**

 * Rule Engine

**Description**
I am creating a Node for the rule chain that sends a GET request to an endpoint, and this establishes a connection by sending a multipart/x-mixed-replace packet every time there is an event on the server.

This way, I need to always be connected to that endpoint and every time I receive a new part from the server, pick it up and send it as output from the node.

I'm still trying to solve the Java part, how to collect the part each time one arrives without waiting for the request to finish (suggestions are accepted), but when I solve it, it is possible to have an input to the node, from a generator for example , but several exits?

**Environment**

 * ThingsBoard: 3.3.2.CE

**Comment by Ultrazombie** [comment]
Closed due to inactivity
