### ISSUE TITLE
[Question] Expand Collapse widget feature in Dashboard

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#5944]
Hi, how to make a  expand and collapse feature in a dashboard like we have in Customers hierarchy
![image](https://user-images.githubusercontent.com/12267053/150460271-799b02f1-d0e5-4ea7-b31f-999984df8b84.png)
 
here we can close/collapse the hierarchy tree and widget on the right will adjust full screen size,
what I wanna do is create that functionality in a new custom dashboard, i wanna put a hierarchy widget on the left and other widget on the right, and left side can be expand/collapse, how to do that?

**Comment by myroslav-tb** [comment]
Hi @evanderbird, I have created a feature request for our prod team. Once they review it, we’ll post an update on when this feature could be delivered if they decide to add it to the product.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
Please follow up on the release notes to check if the feature is added to the Thingsboard.
