### ISSUE TITLE
thingsboard is not starting,instead showing like this in local host.

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#595]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Feb 21 16:10:26 IST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by vparomskiy** [comment]
Without logs and system configuration it is hard to guess the reason of the error

**Comment by gopirathnamt** [comment]
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/1746701/thingsboard.log)
this is full log file
![screenshot from 2018-02-22 10-58-51](https://user-images.githubusercontent.com/36095688/36521896-6b8cb1b8-17bf-11e8-845b-37c6ca7e116a.png)
this is my system configuration.

**Comment by vparomskiy** [comment]
1. Did you make any changes in Thingsboard before starting it?
2. How do you start Thingsboard application?
3. How did you install Thingsboard application? From deb package or from sources?

**Comment by gopirathnamt** [comment]
i make changes,but when freshly download code,it works.
thanks for ur support .
and i have one more doubt,i have thingsboard.1.3.1 on my server.
Can i update the thingsboard with 1.4.0,instead of fresh install?

**Comment by gopirathnamt** [comment]
ok d
