### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by ChrSchultz** [thingsboard/thingsboard#5951]
**Thingsboard PE ESP32 OTA**

 * Generic ThingsboardPE

**Description**
II tried to follow the Guide to build an OTA for ESP32, but I can't create a device ESP32 with type ESP32_OTA because the Option device_type is not given in Thingsboard3x. So I'm stuck. 

**Environment**

 * OS: Thingsboad PE Cloud (Maker) Testing
 * ThingsBoard: 3.3.3
 * Browser: Firefox, Chromium

**Comment by ashaforost** [comment]
Hi @ChrSchultz 

You need to create a device profile called ESP32_OTA and select it during the device creation process. The device profile and device type is basically the same thing, we've just changed the naming convention in the subsequent versions.
Additionally, you can check out our new feature of OTA firmware/software updates: 
[Over-the-air firmware and software updates](https://thingsboard.io/docs/user-guide/ota-updates/)
