### ISSUE TITLE
[Bug]  Changing Home Dashbord from user with limited permission does not work 

### ISSUE THREAD

**Issue by andrevocat** [thingsboard/thingsboard#5952]
**Describe the bug**
calling /api/user ... with POST  for an User with Resource USER:Write permission does not change home dashbord id other additional Infos are updated
doing the same call with Resource All:All can change the Home dashboard id

Body:
{
"id": {
"entityType": "USER",
"id": "..."
},
..
"additionalInfo": {
...
"homeDashboardId": "<id of home dashboard>",
"...
},
...
}

**Your Server Environment**
TB 3.3.2 / self managed

**Your Client Environment**
windows 10, Edge, Firefox....

**To Reproduce**
Add Role with restricted Permissions on User Create, Delete, Read, Write
Add UserGroup with this Role
Add User to this UserGroup
Call API
Check if HomeDashoard Id has changed

**Expected behavior**
A User with write Permission on USER resource can change HomeDasboard

**Comment by mde2017** [comment]
Hi @andrevocat,
have you tried adding the Write permission for 'Profile' ressource?

**Comment by andrevocat** [comment]
Jepp, Resource Profile:All is set.

**Comment by andrevocat** [comment]
more precise, restricted customer user, with the role add,deleting other user of this cutomer, should be able to change the homeDashboardId for any of the customer_user. not only his own

**Comment by SuminDenis** [comment]
Hello @andrevocat,

First of all, for this type of action, you need to use **Generic Role Type** for the admin user with permissions to the following **Resources**:

1. White Labeling (please don't forget to allow White Labeling for Customer)
2. Dashboard
3. User
4. Profile

Also, it looks like you tried to set the Home Dashboard to the user who doesn't have access to this dashboard! Please verify that the user has read permissions for the dashboard you tried to set as Home Dashboard.

After following all these steps, you should be able to set the **Home Dashboard** for your Customer's user from the admin user.
