### ISSUE TITLE
why AbstractCassandraBaseTimeseriesDao.convertResultToTsKvEntry return fake TsKvEntry  when there's no data

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#5958]
**Component**

 * Generic

**Description**
why AbstractCassandraBaseTimeseriesDao.convertResultToTsKvEntry return fake TsKvEntry  when there's no data

here's the code in thingsboard3.3.x

    protected TsKvEntry convertResultToTsKvEntry(String key, Row row) {
        if (row != null) {
            Optional<String> foundKeyOpt = getKey(row);
            long ts = row.getLong(ModelConstants.TS_COLUMN);
            return new BasicTsKvEntry(ts, toKvEntry(row, foundKeyOpt.orElse(key)));
        } else {
            return new BasicTsKvEntry(System.currentTimeMillis(), new StringDataEntry(key, null));
        }
    }

why would it return one fake BasicTsKvEntry rather then null??

**Environment**

 * OS:  ubuntu20l04
 * ThingsBoard: 3.3
 * Browser: chrome

**Comment by john1337** [comment]
TimeseriesService.findAllLatest and TimeseriesService.findLatest is different,apprently findAllLatest  didn't fake any data like findLatest,i think faking data is kind of innappopriate

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
