### ISSUE TITLE
[Question] rest api rule node call with non-JSON return

### ISSUE THREAD

**Issue by rdenisyuk** [thingsboard/thingsboard#5963]
**Component**
 * Rule Engine

**Description**
I need to call an HTTP endpoint from my rule chain that returns a text/plain or text/csv content.
The existing "rest api" node seems to pass the result of the call directly as a message to the next node. However any succeeding "script" node (even empty one) will fail with a message saying this is not a valid JSON.
java.util.concurrent.ExecutionException: javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:6 Expected eof but found ,

Is there a way to ask "rest api" to package the result as JSON? Or make the "script" component accept a message that is not JSON? I also tried to do an HTTP call using XMLHTTP directly from a "script" node but this object seems to not be available in ScriptEngine.

**Environment**
 * OS:  Ubuntu 20
 * ThingsBoard: 3.3.2
 * Browser: Chrome

**Comment by pon0marev** [comment]
Provide an example of your rest API request and response.

**Comment by rdenisyuk** [comment]
REST API Node
![image](https://user-images.githubusercontent.com/25106844/151153960-742a6ca0-cfb6-4c37-91ff-1529f63f4303.png)

Response message data
<img width="765" alt="image" src="https://user-images.githubusercontent.com/25106844/151153759-5f56a98b-5b3e-4008-803c-ec2d096ce1bf.png">
Response message meta
![image](https://user-images.githubusercontent.com/25106844/151154090-2bbe13f4-09bf-4783-8564-79e2eca654ba.png)

SCRIPT node following the REST API
<img width="533" alt="image" src="https://user-images.githubusercontent.com/25106844/151154347-1e57dfee-d1eb-4288-a169-5e06fe8928ba.png">

Failure
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25106844/151154402-195fb729-7e23-4d02-aa1b-5e87e5ffcd26.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/25106844/151154464-83880556-4d87-4fcd-bf6c-975de95d621b.png">

**Comment by pon0marev** [comment]
The rule node handles messages as a JSON file. You can [create your own rule node](https://thingsboard.io/docs/user-guide/contribution/rule-node-development/#overview) to convert the string into JSON.

**Comment by rdenisyuk** [comment]
Thank you. But this solution will not work for a Cloud TB, right? Or is it possible to upload JARs to Cloud?

As I mentioned, I also tried to instantiate an HTTP client from the script node. But "fetch" and XmlHttp seem to not be present in the script engine. Is there any documentation for objects available in the engine? Also your syntax checker seems to follow ecmascript6 rules, but the script engine appears to be based on a different JavaScript standard

**Comment by pon0marev** [comment]
The ThingsBoard cloud does not allow uploading custom extensions. In this case, you should create your own application that will convert XML to JSON.
The rule engine supports json data only.
The script engine is based on nodejs and is called js-executor.
