### ISSUE TITLE
[Question] Separate mobile dashboard for each device

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5967]
Does thingsboard allow customer users to select entity aliases on the dashboard? When I log in to thingsboard with Flutter webview with user, I cannot select entity aliases and assign new device. Our main goal is for the user to enter the entity aliases in the dashboard and assign a new device. Do you have an idea for a way to do this?

**Server Environment**
own setup
docker deployment
OS: Linux(Ubuntu 20.04)

**Client Environment**
OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

Best Regards,
**Gohm Team**

**Comment by ashaforost** [comment]
Hi @gohm-tech,

You can either grant all of your users the permissions to edit the dashboard (in PE edition generic role with the dashboard, dashboard group, widget bundle, widget type resources) or you if your design logic allows, you can add one entity alias (for all devices, for example) and each logged in user will only see the devices he has access to.

Please let me know if you have any further questions.
