### ISSUE TITLE
[Question] Is it possible to know the number of users currently logged in?

### ISSUE THREAD

**Issue by kastayou** [thingsboard/thingsboard#5971]
**Metrics ?**

 * Generic

**Description**
Is there a way to know the number of users logged in in the platform? 
I did not find an api endpoint for that and I did not find this information in the metrics.

**Environment**

 * OS:  Ubuntu Docker
 * ThingsBoard: 3.3.1
 * Browser: N/A

**Comment by Ultrazombie** [comment]
Unfrotnuetly, no
