### ISSUE TITLE
[Question] detectChanges for other widget

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#5972]
Description:
When we want trigger change detection of current widget, we use code like this `self.ctx.detectChanges` 

My question is how to do this change detection running for other widget,
if in a dashboard I have 2 custom widget, widget A and Widget B

from widget A, what code I can use to trigger change detection of widget B? so widget B will be updated?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
