### ISSUE TITLE
Cannot see Debug events (Debug mode is ON)

### ISSUE THREAD

**Issue by kelvinsutandars** [thingsboard/thingsboard#5973]
**MQTT Integration Debug**

 * Generic

**Description**
MQTT is being installed locally on the same Ubuntu server. MQTT Integration presumably works fine because it can add device when there are incoming messages, telemetry from all the devices are also fine. However, even when I turn the Debug Mode of MQTT Integration on, there is no event recorded. Any idea on why this is?

**Environment**
 * OS:  Ubuntu 20.04 (LTS) x64
 * ThingsBoard: 3.2.2
 * Browser: Chrome 97.0.4692.99

**Comment by ashvayka** [comment]
The default rate limits for debug events is 50K events per hour. Are you sure you are not affected by the limits?

**Comment by kelvinsutandars** [comment]
Hi @ashvayka ,

Yes, right now the only telemetries being sent is from 2 devices generated by the Generator on the rule chain, each sending MQTT telemetry per 30 seconds. So I think it should be fine?

Why this concerns me is that I am trying to implement TCP Integration now and although I can send message just fine to the remote server from Hercules (simulating TCP client), ThingsBoard doesn't receive this telemetry and that's why I am trying to figure out what's wrong using the Debug Mode.

**Comment by epalchenko** [comment]
Hello,
Please explain your workflow more precisely. 
Do I understand correctly that you generate telemetry through the generator node and want to see these messages in the Debug event in integration?
In this case, you will not see anything in the integration debug events, and this is the normal behavior of the platform. 
If you still have not resolved this issue or have similar problems, please re-create a new ticket with detailed steps to reproduce.
