### ISSUE TITLE
[Feature Request] switch to PostgreSQL10Dialect

### ISSUE THREAD

**Issue by amarkevich** [thingsboard/thingsboard#5974]
PostgreSQL 12 is recommended but [org.hibernate.dialect.PostgreSQLDialect](https://docs.jboss.org/hibernate/orm/5.6/javadocs/org/hibernate/dialect/PostgreSQLDialect.html) used, actually extends PostgreSQL82Dialect.

**Comment by ashvayka** [comment]
Are you affected by this issue? Please feel free to submit PR. We will consider merge to v3.4

**Comment by amarkevich** [comment]
Its not an issue but feature
