### ISSUE TITLE
Windows 10: ThingsBoard Installation Failed

### ISSUE THREAD

**Issue by WedaPashi10** [thingsboard/thingsboard#598]
Hi, 
I am referring to this guide for installation of thingsboard on my computer (OS is Windows 10, 64-bit).
https://thingsboard.io/docs/user-guide/install/windows/

I downloaded the zip from Installation Archive link provided in the same guide.
The Java version is "1.8.0_161".

I am skipping all the steps that are specified as Optional.

Following is the log that I am getting on my cmd prompt.

    install.bat
    Detecting Java version installed.
    Detecting if it is 64 bit machine
    CurrentVersion 1.8
    Java 1.8 found!
    Installing thingsboard ...
    ===================================================
    :: ThingsBoard ::       (v1.3.1)
    ===================================================
    log4j:WARN` No appenders could be found for logger (hsqldb.db.HSQLDB61BCE181BC.ENGINE).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    Connector configured to listen on port 8080 failed to start
    ThingsBoard installation failed!

Can anyone help?

**Comment by JimishF** [comment]
I'm getting the same issue on ubuntu 18.04, what is the solution?

**Comment by caman99** [comment]
![cmf](https://user-images.githubusercontent.com/54280610/63963581-90e4f880-cabf-11e9-9761-75dc4848a2be.jpg)


kill 8080

**Comment by YurriR19900821** [comment]
change port in config.yml file
