### ISSUE TITLE
[Question] Trendz Native Widget error after upgrade to TB 3.3.3PE

### ISSUE THREAD

**Issue by andreas-jankowski** [thingsboard/thingsboard#5982]
Hi,
after upgrading TP PE to v3.3.3 all my widgets in dashboard showing the message under Description. Is there a newer trendz widget bundle or how can I fix it?

**Component**
 * Trendz

**Description**
![grafik](https://user-images.githubusercontent.com/49144943/151581834-cd478919-3c81-44b3-9063-b357909ec947.png)

**Environment**
 * OS:  Ubuntu Server 20.04.3
 * ThingsBoard: 3.3.3PE
 * Trendz 1.8.2 with trendz-tb-lib-1.8.0-SNAPSHOT.jar

**Comment by andreas-jankowski** [comment]
Resolved by installing of newest Trendz version. Thanks to the support!

**Comment by holgerkoch** [comment]
Hi,
i have exactly the same problem with exactly the same software versions:
OS: Amazon Linux 2
ThingsBoard: 3.3.3PE
Trendz 1.8.2 with trendz-tb-lib-1.8.0-SNAPSHOT.jar

But what new version of trendz? In the documentation is 1.8.2 already the latest version.

best regards

**Comment by andreas-jankowski** [comment]
Hey,

TB Support installed the newest Version that is not listed in docs yet.

wget https://dist.thingsboard.io/trendz-1.9.0.deb
sudo service trendz stop
sudo dpkg -i trendz-1.9.0.deb
sudo /usr/share/trendz/bin/install/upgrade.sh --fromVersion=1.8.0
sudo service trendz start

best regards

**Comment by holgerkoch** [comment]
Hi Andreas,
thank you verymuch for your answer. I found the package:
    wget https://dist.thingsboard.io/trendz-1.9.0.rpm
and make a update:
    sudo service trendz stop
    sudo rpm -Uvh trendz-1.9.0.rpm
    sudo /usr/share/trendz/bin/install/upgrade.sh --fromVersion=1.8.0
    sudo systemctl daemon-reload
    sudo service trendz start

The Update was successful and Trendz is working. Unfortunatelly the exactly same error still occurs.
I open a support ticket at thingsboard.io, hopefully they can help me.

Best regards, Holger Koch

**Comment by holgerkoch** [comment]
Hi,
maybe there is a difference between trendz widget and trendz native widgets. The former works, the native plugin produces the error message. Is there a new version of the Native Plugin or the Native Trendz Library? (https://thingsboard.io/docs/trendz/embed-visuals/)

Best regards, Holger Koch

**Comment by vparomskiy** [comment]
After upgrading to Trendz 1.9 you will need to change the resource URL for Trendz widgets t something like this:
> http://{**TRENDZ_HOST_NAME**}/trendz/assets/trendz-tb-lib-ang12.js

The reason is that Trendz library is no longer hosted on ThingsBoard service. It is a part of Trendz service starting from version 1.9
![image](https://user-images.githubusercontent.com/4686483/162719898-43815d56-85d1-4f88-88e4-1c8be9cfc96a.png)
