### ISSUE TITLE
How to configure SSO with Azure Active Directory

### ISSUE THREAD

**Issue by angel-colao** [thingsboard/thingsboard#5985]
**Component**

 * Generic

**Description**
We are trying to configure Single Sign On to our Thingsboard instance using Azure Active Directory but we are getting the following error:

![image](https://user-images.githubusercontent.com/94895265/151658532-9784093f-9944-4a09-b2ec-170d61d4a301.png)

**Environment**
 * OS:  Ubuntu (AWS Instance BYOL)
 * ThingsBoard: 3.3.3
 * Browser: Chrome, Edge

I attach configuration in the platform:

![image](https://user-images.githubusercontent.com/94895265/151658724-d39ecee2-180e-4220-8c39-92b3540fcea3.png)

Are we missing something? 

Thanks in advance, Angel

**Comment by pon0marev** [comment]
You have the wrong Client secret. Do you use the correct value in secrets?
![image](https://user-images.githubusercontent.com/44898346/151755195-bcc9e468-0df3-4eed-8a00-197491b15f23.png)

**Comment by angel-colao** [comment]
Hello and sorry for my late response...I recreated the configuration again and now everything works fine.

Thanks,
Ángel

PD: I updated the version to 3.3.4.
