### ISSUE TITLE
Creation of a generic dashboard

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5987]
Hello,

I would like to know if it is possible to create a generic dashboard for several customers ? 
In fact I just want to parametrize one entity alias depending on the Customer Name containing the dashboard.
If it is possible, I will be able to create one unique dashboard for all my customers, and this dashboard will show only the informations of the customer.

Best regards,

Lucas

**Comment by ashaforost** [comment]
Hi @lucasKapf 

You can create one dashboard on a tenant's level, for example, grant viewing/edition permissions for this dashboard to any user group you need with the Roles feature, available in PE edition and thingsboard.cloud.
Then, on a dashboard, your customers will always see only the entities they have access to, so by adding, for example, devices of customers A, B, C, the tenant will see all the devices, and each customer will access only their corresponding devices.

In your generic role, make sure to grant the reading permissions for a dashboard, dashboard group, widget type, and widget bundle resources.

**Comment by lucasKapf** [comment]
Hi @ashaforost, thank you for your quick answer, this helps a lot.
I will look at it

**Comment by lucasKapf** [comment]
Maybe I'm doing something wrong but I have a problem : 

I have created my dashboard on tenant's level. But when I try to assign this dashboard to my customer user, the dashboard is not found. My customer is a customer of a customer in the customer hierarchy and is in the "Customer User" group.
This group should have the viewing permissions for this dashboard.
