### ISSUE TITLE
[Bug] Averaging issue in dashboard starting from 3.3.2 PE

### ISSUE THREAD

**Issue by rdenisyuk** [thingsboard/thingsboard#5988]
**Describe the bug**
Since migration from 3.2.2 to 3.3.2 (and also reproduced after upgrade to 3.3.3) the averaging of certain timeseries values is wrong - it sometimes returns 0 for values that are all positive. 

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard 3.3.3 and 3.3.2 PE
  * Ubuntu 20

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Chrome, Edge

**To Reproduce**
I have a field consumption-dg-mtpd that I visualize in the dashboard. All the values of this field are positive over the last 5 hours as can be seen in the screenshot without aggregation. But when I select the "average" data aggregation in the timeline, the resulting values become zeroes for certain periods (see screenshot).

This doesn't affect all the fields, just several. I restored my TB 3.2.2 version and run it in parallel and the issue is not reproduced there

**Expected behavior**
Average values must be calculated properly

**Screenshots**
Without averaging
<img width="209" alt="image" src="https://user-images.githubusercontent.com/25106844/151764821-434b3e9f-7802-454a-bd88-38c0a876b07c.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/25106844/151764671-0aae33d3-5c3c-4330-9748-6605d557120f.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/25106844/151765216-b07e312d-b829-4227-9d6b-bc5e31a0d872.png">

With averaging
<img width="207" alt="image" src="https://user-images.githubusercontent.com/25106844/151764882-cc680f3b-20f2-44e1-9eb6-a280d648faf2.png">
![image](https://user-images.githubusercontent.com/25106844/151765050-226ead2d-e45b-41a7-9122-2121f6b17836.png)
<img width="574" alt="image" src="https://user-images.githubusercontent.com/25106844/151765277-884d3bd2-6901-40ab-b334-d46d2bcb1fb0.png">

**Additional context**

**Comment by rdenisyuk** [comment]
I think the problem in somewhere in database writing in 3.3.2/3.3.3. When I look at the tv_ks table for this field I see some entries incorrectly stored as str_v.
Please note that this field is calculated in a rule chain (division of numbers). No way it can be a string

```
select * from ts_kv where key=179;
              entity_id               | key |      ts       | bool_v |         str_v          | long_v |         dbl_v          | json_v
--------------------------------------+-----+---------------+--------+------------------------+--------+------------------------+--------
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1643702399740 |        | 0.00030003890460386266 |        |                        |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633046443000 |        |                        |        |     0.0462078000005004 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633047042000 |        |                        |        |    0.04628494156853029 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633047642000 |        |                        |        |    0.04466064000025056 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633048242000 |        |                        |        |     0.0435213000005004 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633048842000 |        |                        |        |    0.04634195999924722 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1633049442000 |        |                        |        |     0.0435213000005004 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638316813000 |        |                        |        |     0.1010123999989992 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638317413000 |        |                        |        |    0.09839727000025039 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638318013000 |        |                        |        |    0.09940049999999999 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638318613000 |        |                        |        |    0.10076681999974907 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638319213000 |        |                        |        |    0.10062096000100225 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638319813000 |        |                        |        |    0.10062095999974943 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638320413000 |        |                        |        |    0.10247531999925048 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638321014000 |        |                        |        |    0.10055153411006602 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638321614000 |        |                        |        |    0.10018337999975052 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1643673618000 |        | 0.048274981698011754   |        |                        |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638322814000 |        |                        |        |    0.10199196000012564 |
 b6829a40-2f25-11eb-8320-257de788cc5e | 179 | 1638323414000 |        |                        |        |    0.09925619999999999 |
.....

thingsboard=#  select count(*) from ts_kv where key=179 and str_v<>'';
 count
-------
  1220
(1 row)


```
The same table in TB 3.2.2 instance that runs in parallel on same input with the same rule chains doesn't contain "string" entries 

```
thingsboard=# select count(*) from ts_kv where key=179 and str_v<>'';
 count
-------
     0
```

**Comment by medutySMST** [comment]
I have the same issue on 3.4.3 PE , In not sure about the string values but the symptoms are the same, it only effects fields that are calculated in rule chain.

**Comment by mykhailokornieiev** [comment]
Hi. This is a known issue and there's a ticket in backlog for our product team. However, there is no set timeframe or even if it will be fixed since this is probably related to the Javascript design itself, so I highly recommend avoiding values with a large number of digits (more than 17) after the dot during aggregation. You can transform them before aggregation, so they will have fewer digits.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new information and additions to the platform in the subsequent releases.
