### ISSUE TITLE
[Bug] use Polygon Stroke Color Function not available in image map widget

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#5989]
**Describe the bug**
According to the files in the maps library the polygon part of the image-map widget settings should contain a bool usePolygonStrokeColorFunction (that is later called in the widget controller). However when the widget is used in a dashboard, the option is not shown. The polygon color function is available while the stroke color function is not. 

**Your Server Environment**
* own setup
  * installed on docker
  * ThingsBoard Version 3.3.1 PE

**Your Client Environment**
**Desktop:**

* OS: Win 10
* Browser chrome
* Version 97.0.4692.99 

**To Reproduce**
1. Create new Dashboard with Image Map widget 
2. Click on 'edit', got to advanced settings
3. Scroll down to 'polygon'
4. Toggle 'show polygon'
4. See error: use Color function available while stroke color function is not available

**Expected behavior**
Expected to see a toggle option in Widget settings: use Polygon Stroke Color Function with the possibility to write javascript code, that defines the color of the polygon stroke dynamically using typical input such as dsData and so on.

**Additional context**
At many points in the maps library in repo, it is clear that the widget should be able to use a polygon stroke color function. Searching the term usePolygonStrokeColorFunction in the repo yields a few hits where it is clear that this is an intended feature.

**Comment by kalutkaz** [comment]
Hi @medutySMST,

This functional added to map in 3.3.3 version.
![image](https://user-images.githubusercontent.com/43555187/152184390-48190f37-6b1f-48d0-8265-64473a8bd6c3.png)

**Comment by Meduty** [comment]
Sorry for the misunderstanding. 
Thank you very much.
