### ISSUE TITLE
Integrating SMS plugin for rules/actions

### ISSUE THREAD

**Issue by piousdeepakxavier** [thingsboard/thingsboard#599]
Is it possible to integrate SMS based alerts in thingsboard? Any default feature available to make use of SMS based alerts in our applications

**Comment by affoltep** [comment]
you can use a mail2sms gateway. Then you can send a mail by the mail plugin to the gateway

**Comment by mp-loki** [comment]
there is an SNS plugin available in master branch - it will be released soon. 
Twilio plugin is available in [ThingsBoard Professional Edititon](https://thingsboard.io/products/thingsboard-pe/)
