### ISSUE TITLE
[Feature Request] Change CrudRepository to JpaRepository

### ISSUE THREAD

**Issue by van-vanich** [thingsboard/thingsboard#6001]
In this issue, I suggest changing CrudRepository to JpaRepository.
JpaRepository extends PagingAndSortingRepository which in turn extends CrudRepository.
JpaRepository provides some JPA-related methods such as flushing the persistence context and deleting records in a batch.

Proposed and controlled: @smatvienko-tb

**Comment by smatvienko-tb** [comment]
This will be helpful to use repository.**saveAndFlush**() inside the Transaction. This is the only approach to catch exceptions from the database like "constraint violation exception"... A regular repository.save() is likely to postpone real saving till the end of the method.
