### ISSUE TITLE
Remove entity from Gateway list and from a Map

### ISSUE THREAD

**Issue by avipala** [thingsboard/thingsboard#6002]
I am using a Gateway that is sending list of devices that is scans periodically. Once it detects a new device it adds it to the list of devices. But once the device is no longer transmitting (for a period of 30 sec), I want to remove it from the device list (which will also remove it from the MAP). It doesn't work automatically, How can I do it?
Is it possible to write a function in "Use row style function" inside the "Entities table" which will look at the value of the last appearence time and if it is more than x sec ago, it will delete the line?
Can you please suggest how to write this function?

**Comment by ashaforost** [comment]
@avipala
Please see issue #6011; the same idea can be applied to the map widget, as well as most of the other widgets.
