### ISSUE TITLE
How to pass telemetry from TimeSeries Table row

### ISSUE THREAD

**Issue by purplehorace** [thingsboard/thingsboard#6004]
Using Thingsboard PE and CE
I have a dashboard with a Time Series Table and its rows are populated from the device telemetry.
I would like to make it so when the action of On row click occurs another widget or view can be opend to display the rows information in more detail ?

I have seen in the Thingsboard demos there is a thermostat demo that opens a new dashboard state.
This is good for selecting the device.  I already have the device selected and would like to pass a set of JSON data to a widget in the new dashbord state.

Is this possible ?

**Comment by purplehorace** [comment]
Example is I have a simple dashboard:
![image](https://user-images.githubusercontent.com/8248297/152019227-d4f0589a-65b9-46ee-b7ef-5ad0ba6a3e66.png)

I have added a new Dashboard sate pumpview:
![image](https://user-images.githubusercontent.com/8248297/152019364-ba326715-65ad-494a-bb98-924490e919ee.png)

Set the on row click action to open the new state:
![image](https://user-images.githubusercontent.com/8248297/152019479-4ae87f69-1059-4dbf-9de2-39343dbeaf0a.png)

It opens the new state nicely but I would like the data to be passed from the row to the widget in the new state.

**Comment by dhaval2017** [comment]
use this code in action 

```
openDashboardState("teststate");
function openDashboardState(stateId) {

    var params = {
        entityId: entityId,
        entityName: entityName
    };

    widgetContext.stateController.openState(stateId, {"test":"test1"}, false);
}
```
here is sample code to get state parameters in widget

![image](https://user-images.githubusercontent.com/33371842/152026386-c3874e4c-494b-49fe-b975-95f75eb23aaa.png)

here is the output

![image](https://user-images.githubusercontent.com/33371842/152026511-c914c83c-dff4-4d10-b34c-90efa4735004.png)

**Comment by purplehorace** [comment]
Thanks @dhaval2017.  Can't see how that will get me the telemetry of the line in the TimeSeries Table that has been clicked.
Can you explain how I would get that please ?

**Comment by dhaval2017** [comment]
Hi @purplehorace 
if you just need to show clicked raw data in detailed view I think better to use custom action with html

where you can open the popup and show details of clicked raw
![image](https://user-images.githubusercontent.com/33371842/152213801-09a707ec-9683-4484-b94b-9a469a5af16c.png)


let me know if this is what you needed

because I think no need to use state and navigate to another dashboard as per your requirement

thanks

**Comment by purplehorace** [comment]
Hi @dhaval2017 
Thank you again for your response. I don’t think the custom html would work because I am wanting to parse the data from the row click. The data can contain a json string of multiple attributes which needs to be parsed to extract the attributes. 

This is why I would like to pass it to a widget that has been written to perform the task and render the data.

**Comment by purplehorace** [comment]
Hi @dhaval2017 
I think I understand how the custom call could be made to work.  Once I added debug for each of the custom parameters I see the attributes from the line that was clicked in the additionalParams parameter:
![image](https://user-images.githubusercontent.com/8248297/152395048-081502ab-8921-43f8-9de9-d86549793907.png)

Now need to look at how to convert the widget to display the information.

**Comment by badril1978** [comment]
Hi @purplehorace,

I have the exact same problem of trying to access row data of timeseries data from another widget. Have been able to solve it?. Could you share your solution? Thanks.

**Comment by badril1978** [comment]
Hi @purplehorace 

I have the exact same problem of trying to access row data of timeseries data from another widget. Have been able to solve it?. Could you share your solution? Thanks.

**Comment by sindijs** [comment]
I have the same issue! Is there solution?

**Comment by badril1978** [comment]
Hi @sindijs,

I have managed to solve the issue by using the custom action with html template and a custom widget:
![image](https://github.com/thingsboard/thingsboard/assets/45901907/f966c2f1-fbc9-4c8e-a219-afa7dee53531)
 
Write the following code in JS tab of the function input space:
```
var imgUrl = additionalParams[3];

console.log(additionalParams)

let $scope = widgetContext.$scope;
widgetContext.broadcastService = $scope.$injector.get(widgetContext.servicesMap.get('broadcastService'));
widgetContext.broadcastService.broadcast('rowImg', imgUrl);
```

console.log(additionalParams) allows you to see the data that is being posted through your browser when you press F12 on your keyboard as mentioned by @purplehorace . The code below it uses the broadcastService() to broadcast the variables to other widgets.

Once you have broadcasted the variables that you want, you can call the broadcastService.on fuction in a widget to access the variable. In my case I added a custom static widget and did the following:

![image](https://github.com/thingsboard/thingsboard/assets/45901907/a5459e40-57a6-4c5b-9fc9-de7f87b8873b)

The following javascript code implemented the broadcastService() function in the onInit function of the widget:

```
(self.onInit = function() {
    let $scope = self.ctx.$scope;
    $scope.widgetText = 'Ready to get data';
    self.ctx.broadcastService = $scope.$injector.get(self.ctx.servicesMap.get('broadcastService'));
    
    
    
    self.ctx.broadcastService.on('rowImg', (evt,data) => {
        if(data)
        {
            console.log(typeof data[0]);
            //$scope.widgetText = data;
            
            
           if (typeof data[0] === 'string' && data[0].includes("https"))
            {
                var x = data[0];
                const myArray = x.split("//");
                const myArray2 = myArray[1].split("/");
                $scope.imgUrl =  "https://drive.google.com/uc?id=" + myArray2[3];
                
                console.log($scope.imgUrl);
            }
            self.ctx.detectChanges();
        }
    });
    
    $scope.click = function() {
       $scope.widgetText = "clicked";
    }
    }
        
    self.onDataUpdated = function() {
        self.ctx.detectChanges();
    }
)
```
In my case, I wanted to load a jpeg stored in google drive where the link for  different pictures are stored in the rows of the timeseries table.

The explanation of broadcast service can be found here:

[https://thingsboard.io/docs/user-guide/contribution/widgets-development/](url)

Hope this helps.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
