### ISSUE TITLE
[Feature Request] Support MQTTv5

### ISSUE THREAD

**Issue by voycey** [thingsboard/thingsboard#6005]
**Is your feature request related to a problem? Please describe.**
MQTT v3 is outdated and has been superseded by MQTTv5, the use of User Properties is a particularly large benefit of this new version

**Describe the solution you'd like**
Implement MQTTv5 in the broker

**Describe alternatives you've considered**
Other services that support MQTTv5

**Additional context**
We send a lot of additional context with the MQTT readings that would otherwise be lost via ThingsBoard

**Comment by Ultrazombie** [comment]
already implemented, closed.
