### ISSUE TITLE
New Device admin table - Is it possible to use Use row style function from Advanced for deleting one of the devices

### ISSUE THREAD

**Issue by avipala** [thingsboard/thingsboard#6011]
Hi
I have a gateway implementation that gets list of devices automatically (via messagses on MQTT). Once there is no update on certain device for X seconds, I want to deleted it from the list.
Can I use a function that will check the attributes from each of the existing devices and compare the last time that each once was recieved and if X seconds passed, to issue a command that will delete the device from the list

If it is possible, can you elaborate how to do it? (I am new in Thingsboard)
Thank you
Avi

**Comment by ashaforost** [comment]
Hi @avipala 

You can add a filter to the device admin table, that will only show the devices, which servicer attribute 'active' is true.
You will also have to configure the inactivity timeout for your devices, so after X seconds (your inactivity timeout) the server attribute 'active' will turn from true to false.

Here's an example of such a filter:
![image](https://user-images.githubusercontent.com/47900737/152312568-79373178-e265-4b8e-979b-3abe29aed211.png)

Please also see the following thingsboad articles:
[Configuration properties](https://thingsboard.io/docs/user-guide/install/config/#device-connectivity-state-parameters)
[Device Connectivity Status](https://thingsboard.io/docs/user-guide/device-connectivity-status/)
[Entity Filters](https://thingsboard.io/docs/user-guide/dashboards/#entity-filters)

**Comment by avipala** [comment]
Thank you - this direction is exactly what I was looking for
Can you elaborate how I set the inactivity timeout for devices? 
Do I do it on a global device profile?

**Comment by avipala** [comment]
Actually, I am not sure that the solution of inactivity timeout works for me.
I am using a gateway which is assoicated with a list of devices (that changes during operation).
So adding inactivity rule on the gateway rule, will not indicate inactivity of a certain device and each one of them
How can this be solved?

**Comment by avipala** [comment]
I found a way to do it in the entity list:
result = {background:"white"};
if (Date.now() - entity.lastActivityTime> 30000) {
   result.background = '#FF0000';
} else {
   result.background = '#00FF00';
}
return result;

Is is now showing the device which is not active in RED.
How can I remove this device from the map?

**Comment by avipala** [comment]
I found to way to define an attribute "Active" and use it for the map filter
Thank you!
