### ISSUE TITLE
[Bug] Problem with widget "Timeseries Bar Chart"

### ISSUE THREAD

**Issue by pinkevmladchy** [thingsboard/thingsboard#6014]
**Describe the bug**
Add a possibility to display the chart bar to correspond to the value on the horizontal axis.

For now, the bar alignment is only left, right and center. If you select "center," the bar will appear between month X and month Y. The customer wants the bar center to be on the actual center.

**To Reproduce**
1. Go to New Timeseries Bar Chart
2. Select center alignment in advances settings
3. See error

**Expected behavior**
The bar will appear between month X and month Y. The customer wants the bar center to be on the actual center.
**Screenshots**
![issues_1](https://user-images.githubusercontent.com/49400214/152366605-1cacf2d1-4234-41ee-bb36-0260b6b14262.png)

**Comment by Ibrahim-elkholy** [comment]
I have the same problem,Bar chart with time axis set wrong bar width and position

**Comment by vvlladd28** [comment]
Hi @Ibrahim-elkholy,
Can you show the widget's time window and bar alignment settings?

**Comment by Ibrahim-elkholy** [comment]
![chart](https://user-images.githubusercontent.com/73891816/174594164-8c926396-39e4-4254-9e89-0cfde6e60557.png)
![time](https://user-images.githubusercontent.com/73891816/174594170-45f49971-bf86-475d-b510-533168c4e358.png)
![sittings](https://user-images.githubusercontent.com/73891816/174594499-4099de04-1e22-4848-aba5-4856e450c69e.png)
The reading time for channel but time on the x-axis is 8:00
