### ISSUE TITLE
[Question] How do run upgrade.sh for ThingsBoard running in Docker?

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#6018]
**Component**

* Installation

**Description**
I was running ThingsBoard v3.3.2 in docker. Then I docker pulled the latest v3.3.3 from dockerhub and run it. How do I execute the upgrade.sh? 

I am getting error when modifying and saving rule chain via the UI after upgrading to v3.3.3, I suspect the database is modified in v3.3.3.

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard: 3.3.2 -> 3.3.3
 * Browser: Firefox, Chrome and Edge

**Comment by Backdraft007** [comment]
https://thingsboard.io/docs/user-guide/install/docker/#upgrading ???

**Comment by FacelookHK** [comment]
> https://thingsboard.io/docs/user-guide/install/docker/#upgrading ???

Thanks. It solved the rule chain save error!
