### ISSUE TITLE
[Bug] [Analogue gauges] Widget shows incorrect data until you click "edit" or "Fullscreen" button (occasionally)

### ISSUE THREAD

**Issue by pinkevmladchy** [thingsboard/thingsboard#6021]
**Describe the bug**
Occasionally widget shows incorrect data

**To Reproduce**
1. Go to Dashboard
2. Create analogue widget
3. Send telemetry 

**Expected behavior**
Widget must be shows correctly data

**Screenshots**
![image-2021-12-13-16-42-16-070](https://user-images.githubusercontent.com/49400214/152495298-b00f0762-552b-4498-9267-eb1c2e743229.png)
![image-2021-12-13-16-53-17-410](https://user-images.githubusercontent.com/49400214/152495305-e3d7110f-907c-4a89-aead-be745d091c78.png)

**Comment by vvlladd28** [comment]
Not reproduced
