### ISSUE TITLE
[Bug] Problem with widget "Timeseries Bar Chart"

### ISSUE THREAD

**Issue by pinkevmladchy** [thingsboard/thingsboard#6024]
**Describe the bug**
Add a possibility to display the chart bar to correspond to the value on the horizontal axis.

For now, the bar alignment is only left, right and center. If you select "center," the bar will appear between month X and month Y. The customer wants the bar center to be on the actual center.

**To Reproduce**
1. Go to Dashboard
2. Create Timeseries Bar Chart
3. In advanced settings configure alingment

**Expected behavior**
The customer wants the bar center to be on the actual center.

**Screenshots**
![image-2022-01-31-19-15-24-561](https://user-images.githubusercontent.com/49400214/152496049-f12da6ad-9320-4287-b621-2ea95102e971.png)

**Comment by vvlladd28** [comment]
Not reproduced
