### ISSUE TITLE
[Feature Request] Detect Relations changes in rule engine

### ISSUE THREAD

**Issue by van-vanich** [thingsboard/thingsboard#6031]
**Is your feature request related to a problem? Please describe.**
Implement "Relation created/altered/deleted" events in the rule engine when corresponding relation events happen.

**Describe the solution you'd like**
This PR:https://github.com/thingsboard/thingsboard/pull/5709  contains implementation for this feature

**Comment by cetsupport** [comment]
If possible this event is can be subscribed via websocket? Then will very useful to keep client side updated in real-time.

Thanks.
