### ISSUE TITLE
[Feature Request] Entities version control and synchronization between environments using Git

### ISSUE THREAD

**Issue by ViacheslavKlimov** [thingsboard/thingsboard#6033]
### General description
The feature will allow to persist the current version of chosen entities to Git and then to be able in the future to load entities of some version.
The aim of this feature is to make entities synchronization between different TB environments easier.
For example, you may save all rule chains and dashboard on dev environment and restore on the prod.
It is also useful to restore the version of the dashboard or rule chain in case you accidentally break the logic.

### Key Requirements
- must support entity types: Rule Chain, Dashboard, Device, Asset, Customer, Relation;
- should support entities: Widget Bundle, Widget, Tenant;
- storage of the attributes, the latest values and relations of the entity; 
- commit single, multiple or all entities;
- browse version history for specific entity;
- restore specific version of the entity;
- store git settings on the tenant level;
- supported multiple git based solutions: GitHub, GitLab, BitBucket, raw git;
- tenant administrator has permission to store/restore the entities;
- entities stored from one environment (dev) should be restored on another environment (prod);
- entities stored from one tenant account should be possible to restore on another tenant account on the same env.

### Implementation Steps
The implementation may be divided into following tasks:

#### Git Client
Identify and use a library to communicate with the git as a client.
The client should be able to programmatically:
- list files in the repository;
- commit the file;
- list versions of the file,
- get a specific version of the file;

We should probably make a GitClient interface and basic implementation that uses raw Git API.

#### Git Structure
Need to identify the correct folder structure to store the files.
Make a decision how to store the relations and attributes of the entity.
Most likely, we will need to introduce one or more new fields to the entities.
Something like "gitId" - but this is definitely bad naming, because it contains implementation details.
Maybe "refId", "extId" or similar.

#### Git Settings
UI and REST API to store git settings on the tenant level:
- repo URL;
- credentials; 
- branch name to use;

#### Entities Export/Import API (Service)
The Tenant API that performs store/restore operations should be stateless and should receive some form of EntityExportRequest and EntityImportRequest.
The API will be responsible for exporting entities to some simple data format, like JSON and then import them back.
This will decouple import/export logic from storage.
It will also simplify unit/integration testing and allow to support not only Git but also manual export/import to files (and other implementations of storage in the future).

#### REST API
Design of the REST API should be obvious, once we finalize previous items. Let's discuss in comments below.

**Comment by jozef-ferko-vixtechnology** [comment]
Hello. I would ask several questions.

1. Will this feature allow importing/exporting data per tenant level with all data history?
2. We use "tb-load-script" for importing new versions of rule chains / dashboards. Will this feature allow us to import/update new versions of RCs/Dashs directly via GIT, and there won't be need of using "tb-load-script"? If so, what in case RCs are parametrised (if there are variables filled in with specific values during tb-load-script execution)? 

Thank you.

**Comment by jozef-ferko-vixtechnology** [comment]
Hello @ViacheslavKlimov 

Yes, but, what in case if there is the other tenant with one configuration parameter set differently?
We don't want to end up developing RCs for each tenant separately. 

And, what about my first question? This one is currently more important to us.

**Comment by ViacheslavKlimov** [comment]
@jozef-ferko-vixtechnology 

> Yes, but, what in case if there is the other tenant with one configuration parameter set differently?

If I got correctly what you ask: when you are loading an entity from a repository, absolutely all settings will be overwritten by the ones in the repository, even the name of the entity. In case of rule chains, when you load one from repository, all rule nodes structure and settings will become as in the previously pushed entity, regardless of the current configuration.
 
 
> Will this feature allow importing/exporting data per tenant level with all data history?

The feature, for now, will not support export/import of whole tenant, but only of tenant's devices, profiles, rule chains, dashboards, customers and assets (for CE). But you will be able to push these tenant's entities all at once to the repository, as well as load all these entities together for some other tenant.

**Comment by jozef-ferko-vixtechnology** [comment]
Okay, thank you.

In short, this will allow basically capture almost the whole environment except for data itself, right?

**Comment by ViacheslavKlimov** [comment]
@jozef-ferko-vixtechnology 
Actually no, it will capture all the data: it will store the state of each entity in a certain format in the repository.
If you remove an entity that you've pushed before from the platform, you will then be able to load it back when you want.

**Comment by jozef-ferko-vixtechnology** [comment]
Sorry, I was not clear. I meant data = telemetries.

**Comment by ViacheslavKlimov** [comment]
Oh, yes, this feature, for now, will not take attributes or telemetry to attention, but we will consider implementing additional export/import of entity's telemetry/attributes, if there is a demand.

**Comment by jozef-ferko-vixtechnology** [comment]
Okay.
Thanks a lot for all clarifications.

**Comment by technorabilia** [comment]
Hello,

From the issue description:
- must support entity types: Rule Chain, Dashboard, Device, Asset, Customer, Relation;
- should support entities: Widget Bundle, Widget, Tenant;

and:
- entities stored from one environment (dev) should be restored on another environment (prod);
- entities stored from one tenant account should be possible to restore on another tenant account on the same env.

So we assume that this functionality can be used to restore a complete environment or tenant from one to another.

My question is if this ThingsBoard CE functionality will be extended for ThingsBoard PE to manage for example Integrations, Data converters and other functionality that is specific to ThingsBoard PE only.

If so, and I assume it is, will this also be in the ThingsBoard PE 3.4 release?

Thanks.

**Comment by ViacheslavKlimov** [comment]
Hi @technorabilia
Yes, for PE we're going to additionally support Entity Groups, Converters, Integrations and Roles (for now).
We plan, and I really hope we'll manage, to deliver this feature with 3.4 release :)

**Comment by cbruyndoncx** [comment]
Hi @ViacheslavKlimov this looks promising, we have just started using thingsboard and will need to migrate our setup to test and production systems over the summer.
What is the expected timeframe for this 3.4 release ? The roadmap link I found, only points to the homepage on github.

**Comment by ViacheslavKlimov** [comment]
Hello @cbruyndoncx, I think the 3.4 release will be ready in less than a month.

**Comment by ViacheslavKlimov** [comment]
@technorabilia 
All features for the release are implemented (this one as well), and we've started the final testing phase. 
Unfortunately, this release is already behind the schedule. Hopefully, we will finish in a week or two.

**Comment by Eric-Ruud** [comment]
Just wanted to say thanks for implementing this. It will save me hundreds of hours in the next year.
