### ISSUE TITLE
Upgrade from Community to Professional Edition creates a mess

### ISSUE THREAD

**Issue by zuyan9** [thingsboard/thingsboard#6036]
Similar to [issue 1932](https://github.com/thingsboard/thingsboard/issues/1932), we were trying to upgrade from Community Edition to Professional Edition, and encountered the same issue where there are errors following the upgrade guide for the professional edition. So I just did a fresh install but using the same postgres database, and now it looks like this:

![image](https://user-images.githubusercontent.com/7322443/152655575-be99718b-9ddb-4432-bb40-55b587cf0215.png)

Any idea how to fix this, other than creating a complete new database and reconfigure the settings, device profiles, rule chains, dashboards again?

Thanks,

**Comment by mde2017** [comment]
Hi @zuyan9,

try deleting the browser cache. Afterwards the names should bei displayed correctly again.

This also happened to me sometimes after perfoming upgrades.

**Comment by zuyan9** [comment]
> Hi @zuyan9,
> 
> try deleting the browser cache. Afterwards the names should bei displayed correctly again.
> 
> This also happened to me sometimes after perfoming upgrades.
> 

That solves it, thanks a lot!
