### ISSUE TITLE
[Question] I can connect tb at port 8080 but not 9090

### ISSUE THREAD

**Issue by Minephliss** [thingsboard/thingsboard#6037]
**Component**

 * Generic

**Description**
I‘m a newbie, and I'm using docker-compose to build tb on my RPi following the tutorial step by step. After I finish building, I can connect tb successfully on port 8080 but not 9090. Then I use lsof to check, and there is no process on port 9090.

**Environment**

 * OS:  raspbian arm64
 * ThingsBoard: 3.3.3-snapshot

my docker-compose.yml:

> version: '2.2'
> services:
>   mytb:
>     restart: always
>     image: "thingsboard/tb-postgres"
>     ports:
>       - "8080:9090"
>       - "1883:1883"
>       - "5683:5683/udp"
>     environment:
>       TB_QUEUE_TYPE: in-memory
>     volumes:
>       - ~/.mytb-data:/data
>       - ~/.mytb-logs:/var/log/thingsboard

my docker-compose logs
[log.txt](https://github.com/thingsboard/thingsboard/files/8009614/log.txt)

**Comment by pon0marev** [comment]
You specify the ports in the configuration. 
```
ports:
- "8080:9090"
```
Where:
* 8080 is the port on the localhost.
* 9090 is the internal port of the docker container.

You can change port 8080 to any other free port on your localhost

**Comment by Minephliss** [comment]
many thanks
