### ISSUE TITLE
Rabbitmq AlreadyClosedException

### ISSUE THREAD

**Issue by tbousiou** [thingsboard/thingsboard#6039]
I tried a thingsboard instrallation using rabbitmq for messaging service because it is supposed to be lighter according to the guides.
Everything seems to work fine but i get this repeating error in  in thingsboard.log
`com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.net.SocketException: Connection reset
`
I also have some related questions
For my use case  i need things board for 20-30 sensors max, and data sending every 10 seconds. 
Can i just use in memory messaging?
Is rabbitmq the most lightweight option?
Do i need the messaging service if i only collect data through http?

Ubuntu 20
thingsboard 3.3 CE

**Comment by Ultrazombie** [comment]
Closed due to inactivity
