### ISSUE TITLE
[Feature Request] Save and view which user achnowledged an alarm

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#6047]
**Is your feature request related to a problem? Please describe.**
With multiple users, it can be important to trace which user acknowledged an alarm. If I am responsible for managing alarms and I see an alarm that has been acknowledged, I would like to know which of my colleagues I should ask about the alarm. Is (s)he still working on the problem? How was it resolved? If I don't know who acknowledged the alarm, I don't know who to ask.
Thingsboard already saves ackTs when acknowledging.

**Describe the solution you'd like**
Whenever a user acknowledges an alarm using the alarm widget (or the REST API), Thingsboard records which user performed the acknowledgement.
When I click **Alarm details** on an acknowledged alarm in the alarm widget, I see which user performed the acknowledgement. The  timestamp when the acknowledgement was performed is already available.

**Describe alternatives you've considered**
It is possible to save the user to the alarm details using the rule engine. The alarm event metadata contains userId and userName. This is the result:
![image](https://user-images.githubusercontent.com/893502/152810294-af4ec148-79ae-4e74-8877-e1a01251a825.png)

**Additional context**
The audit log already contains information on who acknowledged what and when.

**Comment by mykhailokornieiev** [comment]
Hi. Such a feature was already implemented as a part of the alarm comments feature starting from 3.5
https://thingsboard.io/docs/user-guide/alarms/#alarm-comments
https://github.com/thingsboard/thingsboard/pull/7762
In this case, I close ticket as solved

**Comment by mfalkvidd** [comment]
Excellent, thanks!
