### ISSUE TITLE
[Question] Updating Alarm Details

### ISSUE THREAD

**Issue by Gelmi** [thingsboard/thingsboard#6062]
**Component**

 * Generic

**Description**
Hello,
I have a Alarms Table widget in my dashboard displaying alarms with details. Is there a way to update the alarm details via a custom action button. I found the alarmService service but it is not documented.

**Environment**
 * OS:  Zorin OS 16
 * ThingsBoard: 3.3.2
 * Browser: 96.0.4664.45

**Comment by volodymyr-babak** [comment]
@Gelmi 
please take a look at alarm service and alarm models source code:
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/alarm.service.ts
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/alarm.models.ts

_alarm.models.ts_ contains **alarm entity** structure and _alarm.service.ts_ contains current methods in alarm service that you can use in custom action.
