### ISSUE TITLE
Data summary view

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#607]
I need to create a display that shows, over time, the average daily value for a sensor, in order to show how its value corresponds to day of week (or day of month, or hour of day, etc.).  That is, I need to show the average of all values that fell on a Monday against all the values that fell on Tuesday, Wednesday, etc.  I believe this is not currently possible.

(To further clarify, the data for one chart I need could be generated with a query like this: `select extract(dow from to_timestamp(ts/1000)), avg(dbl_v) from ts_kv where entity_id = xxx group by extract(dow from
to_timestamp(ts/1000));`)  This is a slow query.

Since the view would be historical in nature (not necessarily being updated in real time), it is possible the necessary values could be computed by a background process and stored, and then made accessible via REST endpoint.  That would, however, require backend configuration work to specify which data gets summarized, and the bins into which data would be summarized (day of week, day of month, etc.), frequency of summary, etc., that goes beyond what could be reasonably managed by the UI.

Would you support the option of adding a REST endpoint that provided access to data in a new (optional) table that could be managed by an external data processing script?  Is there a better way to do this?

An alternate solution would be to add several columns to ds_kv to store day-of-week, day-of-month, day-of-year, etc. which might make computing summaries of the data on request feasible (though I don't have a good dataset to verify this with).  The downside is that additional storage for 5 small ints would be required for each ts_kv value, which would add to the storage requirements, and the solution is less flexible than creating a mechanism for externally computed data.

**Comment by vparomskiy** [comment]
Here are tutorials that shows how to aggregate data from multiple devices:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/
