### ISSUE TITLE
[Feature Request] Two-factor authentication

### ISSUE THREAD

**Issue by ViacheslavKlimov** [thingsboard/thingsboard#6070]
### General description
The motivation for implementing 2FA is, of course, to add an additional layer of security to the platform.
Two-factor auth solutions that might be used are, for example, Google Authenticator, Microsoft Authenticator, FreeOTP and standard 2FA with SMS message.

#### Configuration
First, we need some API on a sysadmin level for configuring what 2FA providers onboarding users will be able to use, and also for configuring the provider itself if any configuration is needed (e.g. for two-factor auth with an SMS message it might be useful to configure a separate SMS provider for this purpose, or choose to use a default one). 

Probably, a user should be able to configure two-factor access to his account during its activation. So, for that we'd also need to extend the user activation API so that a user can choose a two-factor auth method to use (or maybe he would like to be able to use different 2FA providers and choose one of them on log in?), and then configure 2FA account: in case of authentication apps - with a QR code that we will generate for each user; for SMS auth - input a mobile number to use (should we validate it with a test SMS message?). This should also be configurable in user profile settings.

In order to generate a QR code (in fact - authentication URL) if it is needed for a chosen provider, we'll need to generate and store a security key for each user (most likely in a new column in the user credentials table). Also, we'll of course need to store two-factor auth config for each specific user (maybe just in additionalInfo field).

#### Authentication process
After successfully submitting username and password, if a user has 2FA enabled, he will not be given an access token but a short-lived token with some new scope (maybe something like 'PRE_VERIFICATION_TOKEN') that will only be allowed to use for verification code check endpoint. 
This verification code is generated by the authenticator app or in case of SMS 2FA will be generated by the platform and stored in some cache with ttl. 
The attempts for verification code check are limited by the expiration time of the pre-verification token (and we might also want to add some configurable limitation for the number of submit attempts as well). Finally, after a user successfully submits the code, he is given access and refresh tokens pair to use the platform.

**Comment by Ken26M** [comment]
Can you make it that you can also get a verification code over email instead of sms. (like github)

While you are busy the username should not be the email address, usernames are not public knowledge email addresses are. (although that would still be considered valid) 
This also prevent someone from blocking your account by 'trying' since they don't have your username.

Also 2FA must be a choice for the user not mandatory to all or none.

**Comment by ViacheslavKlimov** [comment]
Hi @Ken26M,
2FA over email was already implemented and will be in 3.4 release. 
It will not be mandatory, but we plan to make such option in future release for admin to be able to force users to use 2FA.
