### ISSUE TITLE
[Bug] RPC call request rule chain node with protobuf payload doesn't publish any message on the MQTT topic `v1/devices/me/rpc/request/+`

### ISSUE THREAD

**Issue by nvandamme** [thingsboard/thingsboard#6078]
Hi,

From the doc, the RPC call request Node intent's to produce MQTT messages on topic `v1/devices/me/rpc/request/:requestId`
But it doesn't produce any, at least on TB 3.3.3 CE !
From the MQTT side, no traffic is observed on  `v1/devices/me/rpc/request/+`...

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/201825/153429470-eb3987fb-72c2-4fee-b40c-989da9b4f833.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/201825/153429991-248c73b0-4edf-40a8-97e5-8d84166d4b8f.png">

Metadata and message recieved by the RPC call request Node : 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/201825/153430760-f0d20675-90bb-4c0a-9c15-b7b99f76fa3b.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/201825/153430934-4280a556-1baf-4b9f-b6e9-394fb6d1004f.png">

And two `OUT` messages one `ACK` with a copy of the `IN` message and one `RPC_CALL_FROM_SERVER_TO_DEVICE` with an empty message...

Is there anything missing in my thingboard.yml config (default from on site local postgresql install) ?

**Your Server Environment**
* own setup
  * local infrastructure (postgresql)
  * ThingsBoard Version 3.3.3 CE
  * ubuntu groovy

**Your Device**

* Connectivity
  * MQTT (with protobuff)

**Comment by nvandamme** [comment]
A quick test involving JSON payload with MQTT transport config instead of protobuf shows that RPC call are working.

So is there a specific protobuf schema involved when producing the response ?
Or is this a silent bug, involving protobuf enconding in Thingsboard ?

**Comment by sumin-denys** [comment]
Hi @nvandamme,

1. Everything should be ok with your default thingsboard.yml config.
2. Yes, a specific protobuf schema is involved when producing the response for RPC requests. Here are all basic proto-schemas from the documentation:
![2024-11-29_20-48_1](https://github.com/user-attachments/assets/d5371dff-40ab-4de6-95b7-c54e2c79a281)
![2024-11-29_20-48](https://github.com/user-attachments/assets/a22f6232-c85e-4f84-8430-c14ea5386faa)
![2024-11-29_20-47_1](https://github.com/user-attachments/assets/33392ed8-dbf0-4396-b23d-794db90459de)
![2024-11-29_20-47](https://github.com/user-attachments/assets/4557e793-e32a-49cd-ade3-74e5e69b9b52)
3. I performed some tests, and from my side, everything worked properly 

I’m going to close this ticket. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.
