### ISSUE TITLE
How to use external link URL in OTA updates? 

### ISSUE THREAD

**Issue by KarimSamehSadek** [thingsboard/thingsboard#6079]
**Component**

 * UI

**Description**
I want to add a new OTA update using the "Using an external URL" method instead of uploading a binary file. How to use this method? What are the requirements for the URL if any? Whenever I add a URL it fails to be downloaded.

Example URL used: https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe

**Environment**

 * OS:  Ubuntu  20.04.3
 * ThingsBoard: 2,2
 * Browser: Firefox, latest

**Comment by KarimSamehSadek** [comment]
@Ultrazombie any suggestion here?

**Comment by KarimSamehSadek** [comment]
@ashvayka Appreciate your support here

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with a full description of your request.
