### ISSUE TITLE
Create device attribute from rule engine

### ISSUE THREAD

**Issue by DiegoMartinezGlez** [thingsboard/thingsboard#6084]
**Component**
 * Rule Engine

**Description**
I've been trying to create/update attribute for devices in rule engine but it always returns this error message: Unsupported msg type: POST_TELEMETRY_REQUEST

For timeseries I just add key/value pair/s to msg. So I've tried with msg and metadata for attributes but I guess that it should be done using a specific data format for attributes, but I've found no docs/examples.

I would appreciate help with this. Thanks in advance!

**Comment by nvandamme** [comment]
Hi,

Create a Transformation Script Rule node and a Save Attributes rule node: 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/201825/153580766-90667b01-e519-487b-9ca9-7924a95d60aa.png">

In the transformation script you can extract your attributes from the original message and change the message type to match an attributes POST request : 

```js
if (!msg.attributes) {
  msg.attributes = {
    attr1: "value1";
   ...
  }
}
msgType = "POST_ATTRIBUTES_REQUEST"
return { msg: msg.attributes, metadata: metadata, msgType: msgType }
```

In the save attributes node, you can choose wiche attribute register to update, either `Client Attributes`, `Shared Attributes` or `Server Attributes`

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
