### ISSUE TITLE
[Question] Assign, enable dashboard during claiming device

### ISSUE THREAD

**Issue by eRJx** [thingsboard/thingsboard#6088]
**Component**

 * Generic

**Description**

Is it possible to assign a user default dashboard or share selected dashboards during the claiming device, depending on some device feature, e.g. device attributes, device profile, device group?

**Environment**

 * ThingsBoard: Cloud

**Comment by ssakharova** [comment]
Hello @eRJx,

If the logic is not complicated, we can recommend adding an alias to the dashboard that will display all devices that the user has access to, thus also showing the devices that have been claimed. 
If your logic is more complex, use rule chains and Rest API.
