### ISSUE TITLE
RPC Knob doesn't sync in different browser screens

### ISSUE THREAD

**Issue by Jhonatan-Brandel** [thingsboard/thingsboard#609]
Hello Thingsboard team, I made a dashboard to control a device with switch, and it has a option to syncronize status of each switch widget with timeseries value, so, when i use 2 different computers accessing the dashboard at same time, and I click on switch widget, i see both screens changing the switch state simutaneously, and it works well. But with knob widget, I did't get the same result, and i think this is an important feature. If knob widget would sync with telemetry data, to display latest control value, would be great. Thanks

**Comment by fotis400** [comment]
@Jhonatan-Brandel Please see #438 .

**Comment by Ultrazombie** [comment]
@Jhonatan-Brandel Hello
We have a similar feature request on our prod team,
If you want to add more information how do you see it - please explain in more detail, and I'm adding your information to the ticket.
