### ISSUE TITLE
[Bug] edition of device type/profile not taken into account when editing device from device admin table widget

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6093]
**Describe the bug**

When I edit the device type/profile from the device admin table widget, it is not taken into account after I click on update : 
If I edit the device type again, the old type is still here and not the one I have put in the field.

**Your Server Environment**

* own setup
  * cloud
 

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser : Chrome
* Version 98.0.4758.82

**To Reproduce**
1. Create a device admin table widget showing all your devices.
2. Click on the pencil to edit a device
3. Edit the type by selecting another device profile
4. Click on Update
5. Click on the pencil of the same device again
6. See that the update of the type was not taken into account.

**Expected behavior**
I expect that when the device type is updated, the device profile changes according to that update.

**Comment by YevhenBondarenko** [comment]
Hi @lucasKapf, thanks for the issue.
This bug we will fix in the next release.

**Comment by ArtemDzhereleiko** [comment]
Hi @lucasKapf, this bug we will fix in the next release. But you can fix it right now in your environment. Step to fix:
1. Enter dashboard edit mode by clicking the pencil icon in the lower right corner of the screen and on your widget (Device Admin Table) clicking on the edit widget button then select the 'Action' tab.
![Screenshot from 2022-02-17 13-46-51](https://user-images.githubusercontent.com/83352633/154478864-5ae4f53d-386e-4de0-8cf0-69a1cc21c241.png)
2. Find action with the name 'Edit action' and click the “pencil” icon (Edit action) on the right of the row.
![Screenshot from 2022-02-17 13-48-49](https://user-images.githubusercontent.com/83352633/154478985-b02c0e6b-5fac-407f-87e7-d760e88dffd2.png)
3. Click the button 'Toggle fullscreen' for easier working with JS code.
4. After finding in the JS file the 'save' function
![Screenshot from 2022-02-17 14-12-36](https://user-images.githubusercontent.com/83352633/154479470-b957ad35-c309-473f-b373-d8b69dc28762.png)
and paste the next script after this line of script
`vm.editDeviceFormGroup.markAsPristine();`
Script to paste:
```
if (vm.editDeviceFormGroup.get('deviceType').value !== vm.device.type) {
  delete vm.device.deviceProfileId;
}
```
![Screenshot from 2022-02-17 14-15-22](https://user-images.githubusercontent.com/83352633/154479896-19772695-e451-4f83-8e43-83d4c5f40106.png)
5. Exit from fullscreen mode and click the Save button.
6. Apply changes by clicking the orange tick icon in the top right of the window and then close the details window.
7. Save applied changes by clicking the orange tick icon “Apply changes” in the bottom right of the screen.
