### ISSUE TITLE
[Question] Get error response 500 while try to delete a specific user through API or UI

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#6095]
**Component**

 * Generic

**Description**

Get error response 500 while try to delete a specific user through API or UI, can't find related error in server log, so how to troubleshoot it?

![image](https://user-images.githubusercontent.com/7221781/153658674-a10c18ee-2465-4174-a094-daa399089e4e.png)

**Environment**

 * OS:  Ubuntu Server 20.04
 * ThingsBoard: 3.3.3
 * Browser: Chrome 98.0.4758.82

**Comment by ashaforost** [comment]
Hi @maksonlee 

Please try to reproduce the issue and share the thingsboard.log file; maybe we'll get a hint of what's going on from there.
