### ISSUE TITLE
Rule chain -> Change originator not working properly!

### ISSUE THREAD

**Issue by Tpro4391** [thingsboard/thingsboard#6096]
**Describe the bug**
Thingsboard v3.3.3 update Change originator (rule chains) not working properly!
![image](https://user-images.githubusercontent.com/55780661/153708638-3fd7083c-fb8f-48cc-a3bc-77da5e795060.png)

![image](https://user-images.githubusercontent.com/55780661/153708694-4ff9b386-6ff1-41e8-9c9f-80038a52a9b9.png)

**Comment by mykhailokornieiev** [comment]
Hi. Please confirm if your issue is still relevant. If so, then please provide steps to reproduce in as much detail as possible.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
