### ISSUE TITLE
"Other Mail Properties" required in Outgoing Mail Setup for sys admin

### ISSUE THREAD

**Issue by PopoTheSapien** [thingsboard/thingsboard#61]
New to this so might be inaccurate..

Cannot add 
`"mail.smtp.starttls.enable = true"` 
as additional property, causing the following error:

`Unable to send mail: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. 17sm8107443wru.16 - gsmtp`

**Comment by ashvayka** [comment]
There is separate checkbox "enableTLS" that you can use. Are you trying to connect to gmail?

**Comment by PopoTheSapien** [comment]
Yes I am, tried using contact@datascapeindustrial.com (gmail).

**Comment by ashvayka** [comment]
@PopoTheSapien Try to switch to SMTPS and use SMTP host "smtp-relay.gmail.com" and SMTP port "465"

**Comment by PopoTheSapien** [comment]
Thanks! that worked, also had to enable less secure apps.  Also thanks for great software :)
