### ISSUE TITLE
[Question] How to set the resources loading order in custom static widget?

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#6102]
**Component**

 * UI

**Description**
I am creating a custom static widget and want to include multiple js in a specific order. For example, a.js must be loaded before b.js as b relies on a.

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.3
 * Browser: Edge, Chrome

**Comment by ChantsovaEkaterina** [comment]
Hello, @FacelookHK 
The strict widget resources loading order will be guaranteed only in the next TB version. Currently, the order can't be specified.
Please, see https://github.com/thingsboard/thingsboard/pull/5999

**Comment by FacelookHK** [comment]
As a workaround, I put all the .js into one big file.

**Comment by FacelookHK** [comment]
It is also possible to use promise to load the js one by one.

async function main() {
    await loadScript('http://127.0.0.1:3000/js/jquery-3.6.0.js')
    await loadScript('http://127.0.0.1:3000/js/jquery-ui.js')
    await loadScript('http://127.0.0.1:3000/js/jquery.dataTables.min.js')
    await loadScript('http://127.0.0.1:3000/js/chart.min.js')
    await loadScript('http://127.0.0.1:3000/js/leaflet.js')
    await loadScript('http://127.0.0.1:3000/js/index.js')
}

function loadScript(url) {
    return new Promise((resolve, reject) => {
        try {
            var script = document.createElement('script')
            script.type = 'text/javascript'
            script.src = url
            document.getElementsByTagName("head")[0].appendChild(script)
            
            script.onload = function () {
                resolve(true)
            }
        } catch (e) {
            console.log('loadScript: exception', e)
            resolve(true)
        }
    })
}

self.onInit = function() {
    main()
}
