### ISSUE TITLE
[Question] Device Admin Widget can not change deviceType with action

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#6108]
**Component**
Device Admin Widget

 * UI

**Description**
After updating to TB 3.3.2 I cannot change the deviceType of device anymore. Basically this functionality comes as a default action in the Device Admin Widget. 
Changing Attributes, DeviceLabel and DeviceName works without an error but deviceType can not be changed. 

**Environment**
 * ThingsBoard: 3.3.2
 * Browser: firefox and chrome ...

**Comment by ArtemDzhereleiko** [comment]
Hi @ThomasBaumgartner, this bug we will fix in the next release. But you can fix it right now in your environment. Step to fix:
1. Enter dashboard edit mode by clicking the pencil icon in the lower right corner of the screen and on your widget (Device Admin Table) clicking on the edit widget button then select the 'Action' tab.
![Screenshot from 2022-02-17 13-46-51](https://user-images.githubusercontent.com/83352633/154478864-5ae4f53d-386e-4de0-8cf0-69a1cc21c241.png)
2. Find action with the name 'Edit action' and click the “pencil” icon (Edit action) on the right of the row.
![Screenshot from 2022-02-17 13-48-49](https://user-images.githubusercontent.com/83352633/154478985-b02c0e6b-5fac-407f-87e7-d760e88dffd2.png)
3. Click the button 'Toggle fullscreen' for easier working with JS code.
4. After finding in the JS file the 'save' function
![Screenshot from 2022-02-17 14-12-36](https://user-images.githubusercontent.com/83352633/154479470-b957ad35-c309-473f-b373-d8b69dc28762.png)
and paste the next script after this line of script
`vm.editDeviceFormGroup.markAsPristine();`
Script to paste:
```
if (vm.editDeviceFormGroup.get('deviceType').value !== vm.device.type) {
  delete vm.device.deviceProfileId;
}
```
![Screenshot from 2022-02-17 14-15-22](https://user-images.githubusercontent.com/83352633/154479896-19772695-e451-4f83-8e43-83d4c5f40106.png)
5. Exit from fullscreen mode and click the Save button.
6. Apply changes by clicking the orange tick icon in the top right of the window and then close the details window.
7. Save applied changes by clicking the orange tick icon “Apply changes” in the bottom right of the screen.

**Comment by ThomasBaumgartner** [comment]
Thank you @ArtemDzhereleiko for your fast response and the solutions. This completely fixed the problems.
