### ISSUE TITLE
[Question] Rule Engine Statistics - Difference Permanent Timeouts & Processing Timeouts

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#6110]
**Component**

 * UI
 * Rule Engine

**Description**
In the API Usage Dashboard sometimes Timeouts are displayed. It's not clear to me what's the difference between Permanent & Processing Timeouts. Also I wasn't able to look up information from the documentation:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics

![image](https://user-images.githubusercontent.com/25298332/154100489-b4c8a168-e7ea-4aa2-bf14-57f28c107d6b.png)

Does a Permanent Timeout show that data couldn't be stored/processed even after retrying?
How Permanent & Processing Timeouts differ?

**Environment**
 * ThingsBoard: 3.3.3 PE

**Comment by mistadave** [comment]
Same questions with ThingsBoard: 3.4.1PE ?

**Comment by den1jkee** [comment]
Hello,

Processing Timeouts means that your message doesn`t have enough time to be processed and gets a timeout. Then, this message comes at the start of the queue for reprocessing from the beginning. ThingsBoard works asynchronously, so it always has a chance to get a timeout, but the queue strategy reprocesses these messages. 
Queue in ThingsBoard has several attempts for reprocessing messages which got timeout for different reasons if we are talking about default queue implementation.

After retrying, if they are not processed or stored, these messages get a Permanent Timeout, meaning ThingsBoard will not retry them.

Best regards,
Denys

**Comment by den1jkee** [comment]
Hi,
**Update for the previous message:**
For more understanding of Queue please read this article: [Queues in ThingsBoard](https://thingsboard.io/docs/user-guide/rule-engine-2-5/queues/)
This article described custom queues, parameters, settings, etc.

Best regards,
Denys

**Comment by mde2017** [comment]
Hi @den1jkee,
Thank you for the explanation!
