### ISSUE TITLE
Thingsboard application suddenly stop receiving data from sensors

### ISSUE THREAD

**Issue by fxsilva** [thingsboard/thingsboard#6111]
**Component**

 * Generic

**Description**
The thingsboard application was working fine for more than a year and suddenly yesterday the data was not showing on the dashboards, looking into the thingsboard log it appears that the data is reaching the application but is not stored on the postgresql data base so it is not displayed on the dashboard.
Any help will be appreciated

**Environment**

 * OS:  Ubuntu 20.04.3 LTS
 * ThingsBoard: version 3.3.3
![postgresql](https://user-images.githubusercontent.com/41272130/154155277-4ba7fd08-0f61-485e-84bd-7f57c6bdbf96.png)
![log](https://user-images.githubusercontent.com/41272130/154155282-44030456-9a9b-417d-a6b0-19012a4e5bb9.png)

 * Browser: chrome

**Comment by Ultrazombie** [comment]
Closed due to inactivity
