### ISSUE TITLE
[Bug] Rule node error : java.lang.RuntimeException: java.lang.NoSuchMethodException: No such function invokeInternal_XXXX

### ISSUE THREAD

**Issue by tdsimpro** [thingsboard/thingsboard#6112]
**Describe the bug**
Sometimes on some rule node we get the following error : 
java.lang.RuntimeException: java.lang.NoSuchMethodException: No such function invokeInternal_d27e35ed_7876_4739_9915_ba0fa20d3b94
So far I've only seen it in originator attribute / save timeseries / script node

**Your Server Environment**
* own setup
  * cloud 
  * ThingsBoard Version 2.4 (we'll be able to update to 3.3 in 3 months for the moment we're stuck there)
  * OS Name and Version CentOs

**To Reproduce**
1. Have a rule chain
2. Sometimes the bug happen. Can't actually reproduce constantly

**Additional context**
It looks like it happens when we reboot the service. Our solution so far have been to go into the rule chain, remove the node, recreate it, save. It looks like it fixes the issue sometimes. The errors keep happening usually for a bit after restarting the service, then stops. 
I don't know if it matters but we have about ~350 rule chains, ~3500 rule node. Server load always look okay.

**Comment by Ultrazombie** [comment]
Closed due to inactivity. Please upgrade your ThingsBoard to the latest and reproduce.
