### ISSUE TITLE
[Bug] Broken functionality:  Using the embedded HSQLDB for development purposes.

### ISSUE THREAD

**Issue by MohamedAmineOuali** [thingsboard/thingsboard#6113]
**Your Server Environment**

* own setup
  * master branch
  * Linux

**To Reproduce**
It seems that embedded HSQLDb in thingsboard is broken.  Things work fine when using PostgreSQL. The main cause of such a problem is the DB initialization. Even with `spring.jpa.hibernate.ddl-auto=update` spring-boot seems to not be able to initialize the database. The provided SQL file for init the database support only PostgreSQL, so running the setup server doesn't work. Also, there are missing beans implementation when trying to run the install server for HSQLDb.  Initializing is very important to start thingsboard server because the first thing that the server does is to load the SMTP config which should be available in the database. 

**Expected behavior**
Add default SMTP config to the HSQLDB if it is initialized by spring boot. Or add SQL script that helps populate the HSQLDB similar to PostgreSQL. 

**Additional context**
In the master branch, thingsboard is using PostgreSQL by default. However, in the documentation, it says otherwise

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
