### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6115]
**Describe the bug**

**Your Server Environment**

  * ThingsBoard 3.1.0
  * windows10

**Your Client Environment**

** Windows10

* Version 3.1.0

**Expected behavior**
sendAndFlushPacket(Object message) in MqttClientImpl failed all the time,especially when data is litte,i came into the problem when i was testing rpc.device received the rpc command .but failed in sendAndFlushPacket(Object message) in MqttClientImpl ,which means gateway didn't send the response back,that must be some problem in netty used in MqttClient

by the way,the netty version is 4.1.49 Final

**Comment by john1337** [comment]
i finally find the class file which caused this problem,which is very weird

cause the decompiled file looked alike,but the running result is quite different,any suggestions to dig deeper?

thanks anyway

**Comment by Ultrazombie** [comment]
Closed due to inactivity
