### ISSUE TITLE
[Question] How to change owner of device or asset with entity Admin widget

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#6116]
**Component**

 * UI

**Description**
Currently I cannot find a way to change the owner of a device or asset on a dashboard. On earlier versions of Thingsboard TB2.5 this was possible by using the entity admin widget by the use of a predefined action (Change Owner). 

In this predefined action it was realised the call: $q = $injector.get('$q') 

On TB 3.3.2 this call fails and therefore I cannot change owner of device or asset. 

Is there an alternative to realise this? Any help is highly appreciated.

Regards

**Environment**
 * ThingsBoard: 3.3.2

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
