### ISSUE TITLE
[Bug] Digital and analog Gauges don´t show correct data and don´t refresh

### ISSUE THREAD

**Issue by Ka-non** [thingsboard/thingsboard#6121]
I am using Digital and analog Gauges, but the Gauges Widget says a staic value. refresh page don´t show updates.
The data shows in charts are ok. this occour months ago and the problem persists.
I am working through the ESP32, DHT22, BME280 etc 
This is on Windows with Firefox and Chrome, and Mac with Safari.
server:  demo.thingsboard.io
![failgauge](https://user-images.githubusercontent.com/65251218/154422174-d1dc7272-1d0b-49da-9f16-ee4c28facb2d.png)

**Comment by ArtemDzhereleiko** [comment]
Hi @Ka-non, thanks for the issue.
This bug we will fix in the next release [#5992](https://github.com/thingsboard/thingsboard/pull/5992).

**Comment by ArtemDzhereleiko** [comment]
For the first question yes, correct.
Currently, there is no date for the future release, but if you use a demo server you will see this fix early, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by albtrentadue** [comment]
Hello 
We are experiencing this issue on TB 3.4.1 PE-1 installed in premise on Ubuntu 22.04.1 LTS
Has this been fixed on a later release?
I think this is a severe issue in TB, how can it be with no release schedule? 
Please kindly update this issue, at least with a workaround

**Comment by albtrentadue** [comment]
After further investigation, it seems that, for us, this issue affects only devices having many old data.
On device freshly created the problem does not occur.
May this be related to sql query failure on old partitions?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
