### ISSUE TITLE
[Question] View Image file uploaded by client device to other server?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#6124]
**Component**
Dashboard

 * Generic
We have some client devices that upload images of 50KB base64 string to the database.
But with like 100 devices you already have an average bandwidth of 1MB/s.
So what would be the easy secure way to show the images from a file server (on azure) from the dashboard?
And maybe only upload the filename in the Thingsboard database.?

**Environment**
 * OS:  Ubuntu LTS 20.04
 * Thingsboard PE: 3.3.3 (only PostgreSQL)
 * Browser: Edge

**Comment by mykhailokornieiev** [comment]
Hi. I'm not sure if this request is still relevant to you.
Given that Thingsboard was not designed as a file storage or image gallery in origin, then yes, using a third-party file storage (such as an S3 Bucket ) and adding a link to the image in the widgets may be appropriate.
But it is also worth considering that starting with version 3.6.2 (if I am not mistaken), the Image Gallery feature became available for saving images in Thingsboard. Maybe it will somehow change your logic.
![image](https://github.com/thingsboard/thingsboard/assets/115699895/925caae4-bcc6-418b-8d9a-1abc1813a26b)

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
