### ISSUE TITLE
Integration with mysql - Not an issue

### ISSUE THREAD

**Issue by saurabhjhamb** [thingsboard/thingsboard#613]
Folks,

I am trying to integrate mysql db with Thingsboard, tried changing .yml but of no use.
Has anyone done that? Can any of you help?

Hope not the 1st one to do this. Will really appreciate

**Comment by vparomskiy** [comment]
You will need to make changes in thingsboard.yml 'DAO Configuration' section.
Also, you will need to review schema.sql and system-data.sql scripts to support MySQL dialect.

**Comment by saurabhjhamb** [comment]
@vparomskiy following are my changes to thingsboard.yml:

# MySQL DAO Configuration
spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "validate"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQL5Dialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/thingsboard}"
    username: "${SPRING_DATASOURCE_USERNAME:mysqltb}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"

But strange error stating cannot load driver "com.mysql.jdbc.Driver", logs below:

Installing thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through
 constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defi
ned in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Tomcat.class]: Bean instantiation via factory method f
ailed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Facto
ry method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

**Comment by vparomskiy** [comment]
Mysql driver should also be added into pom.xml . In main pom and in DAO module

**Comment by caoyingde** [comment]
@saurabhjhamb I also met the same problem. Have you solved it?

**Comment by wind86** [comment]
please see https://github.com/thingsboard/thingsboard/pull/904

**Comment by Ultrazombie** [comment]
Closed due inactive

**Comment by zhangbiyun** [comment]
I have implemented the function of porting PostgreSQL to MySQL.
In addition to configuration changes, internal SQL/HQL statements also need to be adapted.

If you need customization, please contact: 314218900@qq.com
