### ISSUE TITLE
Control Widgets do not respond to {"method":"getValue"} via MQTT

### ISSUE THREAD

**Issue by mripv6** [thingsboard/thingsboard#614]
The Rocker Switch widget doesn't work. When a user invokes a dashboard with the widget, the server emits {"method":"getValue"}. However, when the remote site responds the state of the widget isn't updated. Responses such as {"value":false}, {"data":false} or {"method":"setValue","value":false} do not affect the state of the widget as per the documentation. This happens if the MQTT publish occurs over the same subscription session or a new session. 

Another post recommend an update to help manage widget state by allowing the server to poll periodically. It doesn't look like the comment was accepted. Thingsboard needs a better way of maintaining state between the control widget and the remote switch. As is, using control widgets is tenuous at best.

Thanks for all the work and I hope this bug can be addressed soon. (I'm using version 1.4.0-SNAPSHOT compiled this week.)

**Comment by vparomskiy** [comment]
I think this issue was resolved in Thingsboard v 2.0
Please upgrade to the latest version

**Comment by jabernalv** [comment]
No, it was not reolved in latest version

**Comment by Ultrazombie** [comment]
@jabernalv 
Is this problem still relevant on the latest ThingsBoard version?

**Comment by Alimousavi47** [comment]
Yes I have the same similar problem ( #10461 )
