### ISSUE TITLE
Adding Multiple image in image map widget.

### ISSUE THREAD

**Issue by Pankaj9410557422** [thingsboard/thingsboard#6142]
I am using a dashboard for multiple customers. I want the image map to change the image based on customer. And I have saved the image url in customer atrribute. Is it possible or is there a way around as i dont want to make similar dashboard for every customer.

**Comment by dhaval2017** [comment]
@Pankaj9410557422 
you can make custom widget as shown video below 
which will allow you to select customer and update image on image map based on customer selected

https://www.youtube.com/watch?v=ZGhoDAkPOCc

**Comment by ashaforost** [comment]
Hi @Pankaj9410557422 ,

You can use the 'Single entity' alias with the 'Current Customer' selected as entity. Then you can fetch the attribute with the background image by setting the image source like so:
![image](https://user-images.githubusercontent.com/47900737/155362772-f8b55aa4-3c13-43a5-ba03-4776b9e965f7.png)
![image](https://user-images.githubusercontent.com/47900737/155362880-8f82c1bf-4392-4951-b363-6157163e17e5.png)
