### ISSUE TITLE
[Question] Get device access token from widget

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#6145]
**Component**
Generic

**Description**
Is there a way to access the device access token from within a widget?

**Environment**
ThingsBoard: 3.3.3

**Comment by dhaval2017** [comment]
@MichaelRHaddad 
yes in custom widget you can have access to device access token using services/api

**Comment by MichaelRHaddad** [comment]
@dhaval2017 
Thank you for your comment. Could you please give me a code example of how something like that could be achieved? How can I access the device token via the widget js?

**Comment by dhaval2017** [comment]
https://thingsboard.io/docs/user-guide/contribution/widgets-development/

here is the thingsboard document about making custom widget

you can console the self.ctx and see different services and methods provided by thingsboard on browser console

**Comment by MichaelRHaddad** [comment]
@dhaval2017 
I actually did that already, but as far as I can tell, the access token is nowhere to be found in `self.ctx`.

**Comment by dhaval2017** [comment]
![image](https://user-images.githubusercontent.com/33371842/155184526-570e2db5-681b-44ec-846f-60220267b5a7.png)

**Comment by MichaelRHaddad** [comment]
@dhaval2017 
Thank you. I tried the following: ` console.log(self.ctx.deviceService.getDeviceCredentials(self.ctx.datasources[0].entityId));` inside `self.onInit()`, but all I get is this:
![image](https://user-images.githubusercontent.com/41021500/155188325-e211eace-8ce4-45a6-9519-a3b15610b339.png)

**Comment by dhaval2017** [comment]
use this
    self.ctx.deviceService.getDeviceCredentials(self.ctx.datasources[0].entityId).subscribe(function(data){
        console.log(data);
    })

**Comment by MichaelRHaddad** [comment]
Thank you very much.
