### ISSUE TITLE
[Question] How to update the QR code from within the widget's javascript section?

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#6148]
**Component**
 Generic

**Description**
I have a QR widget.  How can I dynamically update the QR code from within the widget's javascript section?

I have tried to manually change the `qrCodeTextFunction` but it seems to not be bound to the QR image itself:
`self.ctx.settings.qrCodeTextFunction = "return '" + dynamicallyGeneratedString + "';";`

**Environment**
ThingsBoard: 3.3.3

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
