### ISSUE TITLE
Database Installation failed 

### ISSUE THREAD

**Issue by Junaid09** [thingsboard/thingsboard#615]
Following the thingsboard contribution guide.
After building the Source code, when i use these commands to Create Database schema and populate demo data:
cd ${TB_WORK_DIR}/application/target/bin/install
chmod +x install_dev_db.sh
./install_dev_db.sh

I get this result:
No passwd entry for user 'thingsboard'
ThingsBoard DB installation failed!

it happens in both embedded HSQLDB and PostgreSQL
Kindly help me...
Thanks

**Comment by mp-loki** [comment]
Hi @Junaid09, 
are you running the script as root? The script tries  to switch user to 'thingsboard', and as soon as there is no password set, you see this Unix error.
If you run the script as root,  su should pass with no error.

**Comment by Junaid09** [comment]
Hi @mp-loki 
i have tried to run the script as root but i'm getting the same result as above. so i have to add user "thingsboard"? or there is another way??
thanks for help...

**Comment by vparomskiy** [comment]
Another way is to run ThingsboardInstallApplication java class from source code.
This tool will init DB schema with all required data

**Comment by iedwin** [comment]
I just succeed to run v1.4.1 in IDEA.
I changed the "run_user" in install_dev_db.sh from "thingsboard" to root and this script chould work to generate h2sql related file in /tmp. Then to make source code run in IDEA I continued to chown those thingsworkDB* files to my current user from root and then it worked!
BTW: My OS is Linux Manjaro.
