### ISSUE TITLE
[Question] Change Device using Converters

### ISSUE THREAD

**Issue by knityanand** [thingsboard/thingsboard#6151]
**Component**

 * Generic

**Description**
I have a poorly designed "BMS" system implemented by another company. Multiple Sensors are connected (wired) to a panel with a specific IP address. The panel then exposes the data in BACnet format. Currently we have deployed the thingsboard IOT gateway which gets the data using BACnet and transmits to the thingsboard cloud.  

Assuming that I have 2 Energy Meters connected I get the data in the following format

	"devices": [{
			"deviceName": "5F_Panel",
			"deviceType": "default",
			"address": "XX.XX.XX.XX:47808",
			"pollPeriod": 10000,
			"attributes": [{
					"key": "DG_KWH",
					"type": "float",
					"objectId": "analogValue:93",
					"propertyId": "presentValue"
				},{
					"key": "EB_KWH",
					"type": "float",
					"objectId": "analogValue:94",
					"propertyId": "presentValue"
				},{
					"key": "PF",
					"type": "float",
					"objectId": "analogValue:91",
					"propertyId": "presentValue"
				},{
					"key": "TOTAL_WATTS",
					"type": "float",
					"objectId": "analogValue:92",
					"propertyId": "presentValue"
				},{
					"key": "DG_KWH1",
					"type": "float",
					"objectId": "analogValue:93",
					"propertyId": "presentValue"
				},{
					"key": "EB_KWH1",
					"type": "float",
					"objectId": "analogValue:94",
					"propertyId": "presentValue"
				},{
					"key": "PF1",
					"type": "float",
					"objectId": "analogValue:91",
					"propertyId": "presentValue"
				},{
					"key": "TOTAL_WATTS1",
					"type": "float",
					"objectId": "analogValue:92",
					"propertyId": "presentValue"
				}
			]
		},

Instead of getting them as parameters for 2 devices I get 1 device but 8 unique params. This creates issues during dashboard generation.

How can I use a converter to convert this data as if the data was sent as below as 2 separate devices sending the same attributes.

	"devices": [{
			"deviceName": "5F_Panel_EM1",
			"deviceType": "default",
			"address": "XX.XX.XX.XX:47808",
			"pollPeriod": 10000,
			"attributes": [{
					"key": "DG_KWH",
					"type": "float",
					"objectId": "analogValue:93",
					"propertyId": "presentValue"
				},{
					"key": "EB_KWH",
					"type": "float",
					"objectId": "analogValue:94",
					"propertyId": "presentValue"
				},{
					"key": "PF",
					"type": "float",
					"objectId": "analogValue:91",
					"propertyId": "presentValue"
				},{
					"key": "TOTAL_WATTS",
					"type": "float",
					"objectId": "analogValue:92",
					"propertyId": "presentValue"
				},{
			"deviceName": "5F_Panel_EM2",
			"deviceType": "default",
			"address": "XX.XX.XX.XX:47808",
			"pollPeriod": 10000,
			"attributes": [{
					"key": "DG_KWH",
					"type": "float",
					"objectId": "analogValue:93",
					"propertyId": "presentValue"
				},{
					"key": "EB_KWH",
					"type": "float",
					"objectId": "analogValue:94",
					"propertyId": "presentValue"
				},{
					"key": "PF",
					"type": "float",
					"objectId": "analogValue:91",
					"propertyId": "presentValue"
				},{
					"key": "TOTAL_WATTS",
					"type": "float",
					"objectId": "analogValue:92",
					"propertyId": "presentValue"
				}
			]
		},

**Environment**

 * OS:  Ubuntu 20.4
 * ThingsBoard: 3.3.3
 * Browser: Firefox latest version

**Comment by qwykx** [comment]
Hey @knityanand 

Can you share your BACnet connector config file? If configured correctly the data should be split between two devices already.

You could however use the rulechain to do some conversion but this is more of a workaround than a fix.

Cheers

**Comment by knityanand** [comment]
Hi @qwykx 

I did pretty much the same. 

Please see attached two files. One config which works and the second which does not work.

[bacnet_notworking.txt](https://github.com/thingsboard/thingsboard/files/8139656/bacnet_notworking.txt)
[bacnet_working.txt](https://github.com/thingsboard/thingsboard/files/8139657/bacnet_working.txt)

I want to segregate the params as individual devices as that is where they are coming from. But because of the way the BMS vendor configured the panel, I get params from all energy meters as distinct params from 1 device only (the panel with the same IP Address).

Could you also throw some light on how to the same using the rulechain.

Rgds
Nitya

**Comment by knityanand** [comment]
Hi @qwykx 

Thanks for your note. 

I tried the above but only one device gets created in thingsboard. I guess the same IP address for both devices is preventing the same.

And yes, I do have access to the gateway. and have complete control on the config files.

What I donot have control on is the devices and the way they have been implemented.

Rgds
Nitya

**Comment by knityanand** [comment]
Hello all,
   I was able to achieve the above using the duplicate to related transformation node... 

![image](https://user-images.githubusercontent.com/55359481/165821381-220d6250-1b1c-4b6d-bad6-488dfef6c748.png)

Thanks
