### ISSUE TITLE
does thingsboard have any plans to use Time Series Database

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6152]
does thingsboard have any plans to use Time Series Database,the community version use postgresql or cassandra to save telementry data,but it's a waste of space cause there are many redundant keys.

**Comment by vparomskiy** [comment]
1. ThingsBoard support TimescaleDB
2. Cassandra - excellent time-series database.

>it's a waste of space cause there are many redundant keys
It is not true. If you do not agree - please provide your benchmarks.

**Comment by john1337** [comment]
> 1. ThingsBoard support TimescaleDB
> 2. Cassandra - excellent time-series database.
> 
> > it's a waste of space cause there are many redundant keys
> 
> It is not true. If you do not agree - please provide your benchmarks.

take ts_kv_cf for example,if there are many attrs for a device,there will be 10s or even more records,and every record will have entity_type,entity_id,ts which be will be same for one device，but if build different table for different device type,there will be another problem: to many tables

**Comment by xiddjp** [comment]
Cassandra is not a wide table, and the compression ratio and query speed are really not very good

**Comment by gaurav36** [comment]
I tried the same using timescale DB and with community edition of thingsboard, its not saving timeseries data in timescale DB based on time range. I can see following tables, 
![image](https://user-images.githubusercontent.com/6826559/220314557-07041f8c-7220-45ee-b48a-17b07218ef70.png)


and if i check ts_kv_latest i see following:
![image](https://user-images.githubusercontent.com/6826559/220314496-1bbf951a-7b6d-4a86-8843-2e233523b20a.png)

with timescale DB i suppose to see database schema based on time range for eg: like this 
![image](https://user-images.githubusercontent.com/6826559/220314739-850d1934-cdc9-47b6-aaaf-3613ed733894.png)

@vparomskiy / @ikulikov  how does DB Schema looks like while using timescale DB ? how it store timeseries data in database ?
