### ISSUE TITLE
[Question] How to filter datasource with angular service code?

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#6153]
Hello, what I'm gonna do here is showing user telemetry of a user.
Data from entity alias is users list, and use telemetry table widget so it looks like this
![image](https://user-images.githubusercontent.com/12267053/155641177-322d286d-160c-473c-9b40-da4bbbfdfa8b.png)
This widget  show all user as tabs

My question is possible to show only certain user, so not all user show as tab. 
Only show current login user, how to do filter datasource in angular code here? 
![image](https://user-images.githubusercontent.com/12267053/155641934-e4a395f3-1f48-4d8e-b1ad-d59b375793aa.png)

possible with this `<tb-timeseries-table-widget   [ctx]="ctx"></tb-timeseries-table-widget>`  ??
or need to create my own table?

**Comment by albtareng** [comment]
I have also been looking for a solution to this problem for 2 weeks. Has anyone found a solution?

**Comment by evanderbird** [comment]
still not find solution, i will close this
