### ISSUE TITLE
[Bug] Shadow overflow on navigation tiles

### ISSUE THREAD

**Issue by qwykx** [thingsboard/thingsboard#6154]
**Describe the bug**

**Your Server Environment**

* not relevant

**Your Client Environment**

* not relevant

**Your Device**

* not relevant

**To Reproduce**
1. Make white or any  brigh color as primary background color (PE editon needed or some workarounds)
2. Go to 'home'
3. Inspect either one of the navigation tiles

**Expected behavior**
Shadow should be visible.

![image](https://user-images.githubusercontent.com/38068324/155675130-087982c6-665c-48de-8348-80302db31809.png)

**Actual behavior**
Shadow is NOT visible.

![image](https://user-images.githubusercontent.com/38068324/155674853-806f0498-6912-45b5-bbd3-f8cfac835d47.png)

**Additional context**
The navigation tiles - css class _.mat-raised-button_ - has a shadow set which should be visible on the bottom of the tile. But as the parent element _.mat-grid-tile_ has ```overflow: hidden``` the shadow will be cut off.

**Possible Solutions**
* set ```.mat-grid-tile { overflow: visible; } ```
* set ```.tb-card-button { height: calc(100% - 4px); }```

**Comment by Ultrazombie** [comment]
Closed due to inactivity
