### ISSUE TITLE
[Question] Retrieve device Access Token from Rule Chain

### ISSUE THREAD

**Issue by RiccardoFelicetti** [thingsboard/thingsboard#6155]
**Component**
 
* Rule Engine

**Description**
Is it possible to retrieve device Access Token from the Rule Chain? If yes, which is the right approach?
Thank you

**Environment**

 * ThingsBoard: 3.3

**Comment by mde2017** [comment]
Hi @RiccardoFelicetti,

the only way I could think of would be using the Administration REST API for this:
https://thingsboard.io/docs/pe/reference/rest-api/

1. Call auth/login endpoint to authenticate with TB username & password. (Returns JWT Token for further requests)
2. Call api/device/{deviceId}/credentials to retrieve Access Token of specified device

![image](https://user-images.githubusercontent.com/25298332/155736802-30095258-c4ff-4202-a1d3-0aa52063cc75.png)

**Comment by RiccardoFelicetti** [comment]
Ok, thank you
