### ISSUE TITLE
[Question] How to change <mat-menu> width?

### ISSUE THREAD

**Issue by FrancescoMenga** [thingsboard/thingsboard#6157]
**Component**

 * UI

**Description**
Hi, i'm currently working on a custom widget and I'm using <mat-menu> element to create a submenu in the already working one. As you can see in the first image the width of the element is fixed and I am not able to change it, to make it bigger.

![immagine](https://user-images.githubusercontent.com/95043931/155723686-c30c3722-4e0f-423c-ad6f-e248f3cda5ea.png)

![immagine](https://user-images.githubusercontent.com/95043931/155724099-cd0a3062-5e84-4c8a-af95-e342c6ed41e3.png)

By analizing the compiled HTML page I noticed that the <mat-menu> element becomes <div> element , and it has a CSS property that sets its max-width to 280px (see the image below).

![immagine](https://user-images.githubusercontent.com/95043931/155724592-82c0f6ed-d615-410d-99ad-8ca94ed370c0.png)

I then changed the property from the browser html inspector and I managed to make the <div> element wider, by modifying the max-width property in .mat-menu-panel class:

![immagine](https://user-images.githubusercontent.com/95043931/155724693-f923c7e0-3d20-4287-85a9-40a4d7d183a2.png)
![immagine](https://user-images.githubusercontent.com/95043931/155724765-2f8f794c-bd64-44dd-a886-08f0ed00b4a9.png)

Is there a way to do this via code? I tried many methods but It didn't worked. Thanks in advance

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 2.3.3
 * Browser: Firefox Latest

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
