### ISSUE TITLE
Azure ADB2C integration issue

### ISSUE THREAD

**Issue by vimalgupta** [thingsboard/thingsboard#6160]
Hi,

We are trying to configure the oAuth with ADB2C but we are getting issue like token empty when trying login/signup with ADB2C.

in ADB2C , following is the token we are sending

{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk"
}.{
  "exp": 1645875223,
  "nbf": 1645871623,
  "ver": "1.0",
  "iss": "https://aweliv.b2clogin.com/ab0ff308-dc8d-4a0a-8491-7a043623654a/v2.0/",
  "sub": "648f61cf-d011-4c33-bfa7-12b2ae5efb7a",
  "aud": "6e1235a1-f30f-4b25-97a3-61e2953fecaf",
  "nonce": "defaultNonce",
  "iat": 1645871623,
  "auth_time": 1645871623,
  "given_name": "Gazal",
  "name": "unknown",
  "emails": [
    "gazalbindal@gmail.com"
  ],
  "tfp": "B2C_1_Signup_Signin"
}

![image](https://user-images.githubusercontent.com/10150201/155856424-bfd78385-6489-434c-812c-817c3958a390.png)

**Environment**

 * OS:  Ubunut 18.04
 * ThingsBoard: 3.3.3PE 
 * Browser: chrome , firefox
 
 Please let us know how we can overcome this.

**Comment by mykhailokornieiev** [comment]
Hi. Not sure if you request is still relevant for you. Also not sure if it is possible to connect B2C at all, but I was able to configure Azure AD as Oauth2 provider, so maybe this comment will be usefull
https://github.com/thingsboard/thingsboard/issues/10143#issuecomment-1948198924

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
