### ISSUE TITLE
[Question] Hundreds of alarms on ThingsBoard are merged and sent to MQTT？

### ISSUE THREAD

**Issue by pystudy123** [thingsboard/thingsboard#6161]
<img src = 'https://s3.bmp.ovh/imgs/2022/02/ee5b26df3df64500.jpg' />
As shown in the figure, the alarms have been generated using ThingsBoard, but there are too many alarms, and need to be merged to send real-time alarms to MQTT. How to merge? One of the alarm messages is as follows:

{
"tenantId": {
    "entityType": "TENANT",
    "id": "e0661db0-8c25-11ec-9a94-5d6fff670029"
},
"customerId": {
    "entityType": "CUSTOMER",
    "id": "13814000-1dd2-11b2-8080-808080808080"
},
"type": "alarm2",
"originator": {
    "entityType": "DEVICE",
    "id": "ea000230-8f1f-11ec-ae9d-953bf343e774"
},
"severity": "CRITICAL",
"status": "ACTIVE_UNACK",
"startTs": 1645943181958,
"endTs": 1645943181958,
"ackTs": 0,
"clearTs": 0,
"details": {},
"propagate": false,
"propagateToOwner": false,
"propagateToTenant": false,
"propagateRelationTypes": [],
"id": {
    "entityType": "ALARM",
    "id": "2edda910-9796-11ec-a719-953bf343e774"
},
"createdTime": 1645943182881,
"name": "alarm2"
}

**Comment by vparomskiy** [comment]
How do you plan to merge alarms?
 For example, 100 alarms were generated for 2 devices -> what do you need to send via MQTT, and what is the destination?

**Comment by pystudy123** [comment]
> 



> How do you plan to merge alarms? For example, 100 alarms were generated for 2 devices -> what do you need to send via MQTT, and what is the destination?

Thanks for the reply, I want 100 alarm points. For example, if there are 50 alarms created at present, I will send all alarm lists, such as the current value and creation time, to the MQTT server.
I solved it temporarily. When every alarm is created, I subscribe to the same MQTT.
