### ISSUE TITLE
[Question] MQTT over SSL | error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed Error: A TLS error occurred

### ISSUE THREAD

**Issue by xeeed-k1** [thingsboard/thingsboard#6163]
### MQTT over SSL

 * Generic

**Description**

1. We have setup [HAProxy Load Balancer](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/).
2. We currently have a letsencrypt based TLS cert on our TB site.
3. Our device profile is enabled with MQTT transport type, however, there are no data converters or integrations configured specifically for MQTT. Simple MQTT over 1883 is working.
4. We are trying to setup [MQTT over SSL](https://thingsboard.io/docs/pe/user-guide/mqtt-over-ssl/) for which we have setup [cert based authentication](https://thingsboard.io/docs/pe/user-guide/certificates/).
5. However, on testing, like this:
 `mosquitto_pub --cafile tb-server-chain.pem -d -q 1 -h "YOUR_TB_HOST" -p "8883" \
-t "v1/devices/me/telemetry" --key key.pem --cert cert.pem -m {"temperature":25}`
  we are receiving the following error:
  `Client mosq-XXXXXXXXXXXX sending CONNECT
  OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  Error: A TLS error occurred.`
6. Thingsboard log says the below:
`2022-02-27 12:58:36,319 [nioEventLoopGroup-6-2] ERROR o.t.s.t.mqtt.MqttTransportHandler - [05759a6d-cbb6-4ad2-9b91-cce438be29cc] Unexpected Exception`
7. While setting the variables in 'thingsboard.conf' file, we used the same pem file as configured for HAProxy and copied the required pem files into _/etc/thingsboard/conf_ from _/usr/share/tb-haproxy/letsencrypt/live_.
8. So, "**tb-server-chain.pem**" is same for MQTT config, HAProxy config.
9. Also, we notice that the certificate chain setup in step 1 above is **different** from the certificate chain setup in step 2 above. Is this the reason for the error in step 5 or **have we missed any important configuration**?
 

Kindly suggest the ways to resolve this issue.
Please let know if we should provide any further information.

**Environment**
 * OS:  Ubuntu 18.04.2 LTS
 * ThingsBoard: 3.3.2PE

**Comment by chfxr** [comment]
When you use LetsEncrypt, you need to provide the current Root Chain certificate:
https://letsencrypt.org/certificates/

Current one is: 
https://letsencrypt.org/certs/isrgrootx1.pem

You can also find this cert in the apt package ca-certificates (from Mozilla).
Its located in the /etc/ssl/certs folder.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by Vaibhav0216** [comment]
Hi,

I am experiencing issues connecting to thingsboard.cloud using MQTT over a secure connection on port 8883.

I have successfully connected using MQTT on port 1883, but when I try to connect using the secure port 8883, I encounter the following error:
``` mosquitto_pub --cafile ca-root.pem -d -q 1 -h "thingsboard.cloud" -p 8883 \
-t "v1/devices/me/telemetry" --key deviceKey.pem --cert chain.pem -m '{"temperature":25}'
```
**Error :-** 

`
Client (null) sending CONNECT
OpenSSL Error[0]: error:0A000086:SSL routines::certificate verify failed
Error: A TLS error occurred.
`
I have followed the documentation thoroughly but still face this issue. Could you please provide guidance on how to resolve this?

Thank you.

Best regards,
Vaibhav Kshirsagar
