### ISSUE TITLE
Login UI from Auth0 as default login UI

### ISSUE THREAD

**Issue by vimalgupta** [thingsboard/thingsboard#6165]
Hello

We have configured the Auth0 Login  and it is all OK by placing the login button in the Things-board Login Page.

We do not want to use the thingsboard login page and looking to have the Auth0 login page as default. is that possible, if so how do we do that.

**Environment**

 * OS:  ubuntu 18.04
 * ThingsBoard: PE 3.3
 * Browser: chrome , firefox

**Comment by mde2017** [comment]
Hi @vimalgupta,

if you are using PE with white-labeling, you can hide the default username & password fields via custom CSS like:

```
mat-form-field { visibility: hidden;
  height:0
}
button.tb-reset-password { visibility: hidden;
  height: 0;
}
button.mat-button-base {visibility: hidden;
height: 0;
}
div.container-divider {visibility: hidden;
height: 0;
}
```

**Comment by vimalgupta** [comment]
Hi @mde2017 

Thanks for revert.

With this i can disable the things board default login but still i will have the "Lofin with Auth 0" button which will open up the Auth0 Login screen.

i would like to know how can i avoid the "Login with Auth0" button and have Auth0 login screen shown on hitting localhost:8080.

**Comment by qwykx** [comment]
Hello @vimalgupta 

If you insepct the `Login with Auth 0 button` with developer tools you can see a link in the format `https://YOUR_FQDN/oauth2/authorization/YOUR_AUTH0_GUID`. 

By using that link you can login directly with Auth0. If you still need the `https://YOUR_FQDN/login` you could use some redirect magic on your ingress.

Cheers

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
