### ISSUE TITLE
[Question] Submitting telemetries with compression (gzip) enabled.

### ISSUE THREAD

**Issue by admiralmaggie** [thingsboard/thingsboard#6166]
**Component**

 * Generic

**Description**
I'm trying to submit a group of telemetries with gzip compression enabled in the header but I'm getting web server error 500 with no description of the issue. Is this supported at all?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.3.2
 * Browser: Chrome, submitted via python post request

**Comment by vparomskiy** [comment]
As I know, gzip compression is not supported in HTTP transport

**Comment by admiralmaggie** [comment]
> 

Thank you. I thought it might something I can activate in Spring framework but it seems like Spring doesn't support it. It is supported only with Tomcat.
