### ISSUE TITLE
[Bug] (Critical) Message is processed by more then 1 rule nodes!

### ISSUE THREAD

**Issue by ch9hn** [thingsboard/thingsboard#6171]
**Describe the bug**
We have noticed a really critical incident of a Thingsboard system.
When sending a MQTT Message to the system, every message failed to process:

`2022-02-28 10:47:36,397 [tb-rule-engine-consumer-41-thread-18 | Main-3] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [2494e520-09ae-11ec-a0ce-1bfd165d7702] Failed to process message: TbMsg(queueName=Main, id=b6548030-760f-48e6-9147-c57b7f57cd6d, ts=1646045256394, type=POST_TELEMETRY_REQUEST, originator=b4c0e1f0-0a6f-11ec-ae4a-9b4a99c2e005, customerId=8d02b440-0af6-11ec-ae4a-9b4a99c2e005, metaData=TbMsgMetaData(data={deviceType=X_Devices, deviceName=2000/2205, ts=1646045256394}), dataType=JSON, data={"timestamp":1646045003457,"ts":1646045003457,"run_state":1,"standby_state":0,"error_state":0,"machine_on_state":1,"s1run_state":1,"lossmachineid":2205,"losscat":"","lossid":""}, ruleChainId=be1c2820-0a3a-11ec-ae4a-9b4a99c2e005, ruleNodeId=null, ctx=org.thingsboard.server.common.msg.TbMsgProcessingCtx@2cad22ce, callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@6cada25d), Last Rule Node: [RuleChain: X_root_chain|RuleNode: Message Type Switch(e3320c50-0b2b-11ec-ae4a-9b4a99c2e005)]
thingsboard_1  | 2022-02-28 10:47:37,878 [TB-Scheduling-1] INFO  o.t.s.s.s.DefaultTbEntityDataSubscriptionService - Stats: regularQueryInvocationCnt = [0], regularQueryInvocationTime = [0], dynamicQueryCnt = [4] dynamicQueryInvocationCnt = [0], dynamicQueryInvocationTime = [0], alarmQueryInvocationCnt = [0], alarmQueryInvocationTime = [0]`

No error is logged in the Rulechain Debug mode, as the Rulechain can't be saved.

Rule Engine Statistics says:
`Message is processed by more then 1 rule nodes!`

**Your Server Environment**

* own setup
  * Docker on-premises system (Vanilla Setup 1:1 like in the docs)
  * ThingsBoard Version: 3.3.0 and 3.3.3
  * Ubuntu 20.04

**Your Client Environment**
Doesn't matter.

**Your Device**

* Connectivity
  * MQTT
* Device vendor and model
Siemens IoT 2040

**Expected behavior**
MQTT Messages get processed and timeseries is saved.

**Additional context**
All the things we tried before, to get it back in a working state:
- Shutdown/Restart Docker-Compose
- Delete Cache
- Reboot host system
- Install Redis Cache instead of in memory
- Removed old / orphaned volumes (as the data is written down to a folder and not a volume)
- Checked every log in the system
- Added new device and device Profile
- Changed the Custom rule chain to the Root Rulechain
- Replaced the rest of the rule chain with just debug logger node
- Updated Thingsboard from 3.3.0 to 3.3.3.
- No overcommitment of the memory seen
- No overcommitment of the CPU seen

**Comment by ViacheslavKlimov** [comment]
The error message suggests that you set `maxRuleNodeExecutionsPerMessage` as 1 in the tenant profile

**Comment by Ultrazombie** [comment]
Closed due to inactivitiy
