### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#6172]
**Component**
UI

**Description**
What is the purpose of the "Is module" checkbox inside a widget's resources?
![image](https://user-images.githubusercontent.com/41021500/155983514-9244b7f8-96c8-4ffd-9220-63515254b606.png)

**Environment**
ThingsBoard: 3.3.3

**Comment by vparomskiy** [comment]
This checkbox is used if you want to import the Angular module into a custom widget.
