### ISSUE TITLE
[Question] Create Control Widget with subscription ( similar to Switch)

### ISSUE THREAD

**Issue by RiccardoFelicetti** [thingsboard/thingsboard#6175]
**Component**

 * UI

**Description**
Is it possible to create a custom widget (CONTROL WIDGET) using the Web UI that use subscription to timeserie to retrieve data and RPC to send command? Like the Switch does.

**Environment**
 * ThingsBoard: 3.3

**Comment by dhaval2017** [comment]
@RiccardoFelicetti 
yes you can

**Comment by RiccardoFelicetti** [comment]
How can I use the subscription api ?
Doing something like this `self.ctx.subscriptionApi.createSubscriptionFromInfo (.....)`.

**Comment by dhaval2017** [comment]
yes 
or if you have alias created for same 
you can use alias in widget  and get all data directly at self.ctx.data

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
