### ISSUE TITLE
[Bug] Error: ErrImagePull

### ISSUE THREAD

**Issue by ivangarcialopez** [thingsboard/thingsboard#6176]
**Describe the bug**
Hello, this is the third time I tried to reinstall Thingsboard PE On Premise in our Azure service, using micro services. I deleted all the services in Azure 3 times and I have no luck with reinstallation.

I follow all the steps https://thingsboard.io/docs/user-guide/install/pe/cluster/azure-microservices-setup/ and in the step 9 I get an error.

I have no problems pulling docker images from the command line in local (step 7) but when I run the installation script I get the following error:

Failed to pull image "store/thingsboard/tb-pe-node:3.3.3PE": rpc error: code = FailedPrecondition desc = failed to pull and unpack image "docker.io/store/thingsboard/tb-pe-node:3.3.3PE": failed commit on ref "manifest-sha256:7852418051884f7b8eae84f46105e88b7b73950bb519e01c71b12b6980c084d4": "manifest-sha256:7852418051884f7b8eae84f46105e88b7b73950bb519e01c71b12b6980c084d4" failed size validation: 2707 != 3465: failed precondition

It seems that it could pull the image but it's having some trouble with the file validation, same sha256, but different size?

This is a screenshot from Lens setup. The pod td-db-setup with the error.
![image](https://user-images.githubusercontent.com/6485021/156068662-a42c7012-31c6-41d6-88ab-2899631d5c51.png)

**Your Server Environment**
* own setup
  * cloud with AWS microservices
  * ThingsBoard 3.3.3PE
  * Kubernetes 1.21.9

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: macOS Monterey

**Comment by Ultrazombie** [comment]
Hello @ivangarcialopez 
please use another url for pulling image's, change:
store/thingsboard/tb-pe-node:3.3.3PE
to
thingsboard/tb-pe-node:3.3.3PE
