### ISSUE TITLE
[Question] Documentation for the white labeling CSS classes

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#6181]
**Component**
Generic

**Description**
Using the suggested method in [this](https://youtu.be/V9jl-gb9g2I) video, we did an extensive redesign of our TB. However, this method is simply not sustainable. Digging through the style of each element in the browser inspector to find the relevant classes is very hacky. Is there, **anywhere**, a complete documentation of the CSS classes used by TB so we don't need to go through this detective work each and every time we want to change something?
Thank you.

**Environment**
ThingsBoard: 3.3.3

**Comment by qwykx** [comment]
Hello @MichaelRHaddad

You could find the CSS classes used in the source code (scss though). Do you maybe have a list of changes already done? We could contribute to this documentation alltogether, what do you mean :)?

Cheers

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
