### ISSUE TITLE
[Bug] Alarm in the device has been triggered, but not displayed in the alarm table widget

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#6183]
Describe the bug
Alarm in the device has been triggered(can see alarm in device detail information), but not displayed in the alarm table widget.
But other device of this type(the same device type) can display the alarm in the alarm table widget. 

Your Server Environment

Ram: 64GB
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz 
ThingsBoard Version: 3.3.2 CE
OS Name and Version: Ubuntu 20
Your Client Environment

Laptop:
Device: ThinkStation
OS: win7
Browser: Firefox
Version: latest

**Comment by xiddjp** [comment]
need help.

**Comment by xiddjp** [comment]
@ashvayka do you have some suggestions for this problem?

**Comment by xiddjp** [comment]
Does anyone else have this problem？

**Comment by ssakharova** [comment]
Hello @xiddjp,

In that case, I could recommend upgrading your instance to the most recent version to avoid encountering the described issue. 
As there has been no assistance from the community for a considerable time, I am closing this ticket due to inactivity.
