### ISSUE TITLE
[Assets] See the attributes received

### ISSUE THREAD

**Issue by Victorio1209** [thingsboard/thingsboard#6185]
* Generic

**Description**
Hello! I would like to create any assets (cows), my device is a weighting sensor and I need to send attributes for the assets, but I just see the attribute valor in the page device. How I create a relation between assets and devices?

**Comment by dhaval2017** [comment]
@Victorio1209 
you need to setup rulechain
so when device send the data it will stored into the related asset 

Thanks

**Comment by Victorio1209** [comment]
Thank you! Do you know any example of this?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
