### ISSUE TITLE
[Question] Show Button in Entities Table widget depending on attribute value of entity

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6187]
Hello,

I have an Entities table widget which displays all my Customers.
If some Customers are Service Providers, they have an boolean attribute "is_service_provider" equal to true. 
This attribute is false otherwise.
I would like to show or hide a button depending on the value of the attribute "is_service_provider".
I have tried this code in the show/hide function of button but it does not work.

```
 let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));

attributeService.getEntityAttributes(data.id, 'SERVER_SCOPE', ['is_service_provider']).subscribe(
                   function (attributes) {
				if(attributes[0]) {
					return attributes[0].value;
				}   
		  }
);
```

Is it because the return is inside the subscribe ?
Is there any other way to do what I want ?
Best Regards,

Lucas

**Comment by vparomskiy** [comment]
In your example, you return Observable instead of boolean value.
The easiest option is to add the field 'is_service_provider' in the widget datasource. And in show/hide function check it directly. Something like :

> return data && data.is_service_provider;

**Comment by lucasKapf** [comment]
Hello @vparomskiy thank you very much for your quick answer. I achieved it by doing what you said.
I have just put 
`return data && data.is_service_provider === "true"`
Otherwise it just checks if the attribute is_service_provider exists.
