### ISSUE TITLE
[Question] Thingsboard Installation on Windows Server 2016 with Restrictive Proxy

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard#6188]
**Component**

 * Installation

**Description**
I need to install Thingsboard docker version on a Windows Server 2016 which has a very restrictive proxy. Docker Desktop for Windows does not work on Windows Server but I was able to install docker with the following instructions:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker

However, it keeps timing out when I try to run: docker pull thingsboard/tb-postgres

Is there a way to do an offline installation of Thingsboard on docker? Later I will also need to install Thingsboard IoT Gateway on docker.

Thank you.

**Environment**

 * OS:  Windows Server 2016
 * ThingsBoard: 3.3.3

**Comment by vparomskiy** [comment]
maybe this article will help:
[https://4sysops.com/archives/install-docker-on-windows-server-2019/](https://4sysops.com/archives/install-docker-on-windows-server-2019/)
