### ISSUE TITLE
"Support Ukraine" on Login Page

### ISSUE THREAD

**Issue by igloodan** [thingsboard/thingsboard#6191]
**Is your feature request related to a problem? Please describe.**
If a quick modification can be made to the login page/script to show a logo and message in support of Ukraine then I will happily apply this patch to my instance. Some sort of option to include a link like the logo at the top left of the thingsboard.io webpage would be even better so that people can also donate from the link.

**Describe the solution you'd like**
Make it an option (or manual patch to a file) to include the "Stop the war, save Ukraine" from thingsboard.io on the instance login page.

**Describe alternatives you've considered**
I would modify this myself but I'm not sure where to start and would like to do this quickly.

**Additional context**
![support_ukraine](https://user-images.githubusercontent.com/50181878/156422237-c0742c0c-d2e5-4c64-8de5-455340fd9c61.png)

**Comment by igloodan** [comment]
@ashvayka 
I agree 100%, it needs to be a choice but it could either be an option or a manual file change/patch to get it made available to those that want it quite quickly.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
