### ISSUE TITLE
[Bug] Missing translations

### ISSUE THREAD

**Issue by NicoWii4** [thingsboard/thingsboard#6192]
Hello,
I'm opening this issue because I found that there are missing translations for my language which is French. (It may also be the case for other languages).

- In time windows, the "interval" checkbox shows options in English but it is not translated : 
![image](https://user-images.githubusercontent.com/80882254/156201308-03842924-3e1d-4cab-9d8e-dabd5b3b37e9.png)
It is the same problem for the timezone box.
- I also observe missing translations in several menus. For example, in a device profile details, there are missing translations for boxes (red boxes in the following image) or for input boxes descriptions :
![image](https://user-images.githubusercontent.com/80882254/156202608-0d37afff-f0ed-48d6-9579-7a67f256c327.png)

Is there any update coming soon with these missing translations? If not, is there any way to add them?

Thank you for your answer.

**Server Environment**
* Cloud docker deployment with official Thingsboard PE images
* ThingsBoard Version 3.3.3PE
* Docker host is debian buster, Docker version 20.10.12

**Client Environment**

**Desktop :**
* OS: Ubuntu 20.04 / Windows 10
* Chrome / Firefox 97.0

**Comment by xalt7x** [comment]
Greetings, @NicoWii4 

I believe these options are translatable but French locale file ([locale.constant-fr_FR.json](https://github.com/thingsboard/thingsboard/blob/hotfix/3.6.2/ui-ngx/src/assets/locale/locale.constant-fr_FR.json)) misses appropriate strings. They can be found in [locale.constant-en_US.json](https://github.com/thingsboard/thingsboard/blob/hotfix/3.6.2/ui-ngx/src/assets/locale/locale.constant-en_US.json)
```
 "timeinterval": {
...
        "predefined": {
...
          "current-day-so-far": "Current day so far",
          "current-week": "Current week (Sun - Sat)",
          "current-week-iso": "Current week (Mon - Sun)",
          "current-week-so-far": "Current week so far (Sun - Sat)",
```

Translations can be contributed by volunteers (via Pull Request, for example).

Alternatively:
- for CE version it's possible to create a [custom build](https://thingsboard.io/docs/user-guide/install/building-from-source/) with required changes.
- for PE version it's possible to use [Custom Translation feature](https://thingsboard.io/docs/pe/user-guide/custom-translation/).

![custom-translation](https://github.com/thingsboard/thingsboard/assets/44649402/843ef464-c7a2-4a4a-82c0-150286d725b2)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
