### ISSUE TITLE
how to change the font-color of text from white to other color in thingsboard ?

### ISSUE THREAD

**Issue by estelina-liao** [thingsboard/thingsboard#6194]
how to change the font-color of text from white to other color in thingsboard 3.3.2 ?

**Comment by ssakharova** [comment]
Hello @estelina-liao,

I recommend exploring the white-labeling feature to change the font color of the text from white to another color.

Here you can find more information regarding this feature - https://thingsboard.io/docs/pe/user-guide/white-labeling/
