### ISSUE TITLE
[Question] Few question about Things Board

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#6195]
ThingsBoard version: 3.3.0

I new to the things board and i currently helping my company to do the IOT platform project using Things Board. Do somebody has the knowledge to the below question? Hopefully I can get suitable resources that can help me to complete the project given by the company.

The question as followed:
1.  I only know the RAW data store at table ts_kv， ts_kv_latest， but actually I don't understand how the things board store inside the data if like that any way or link that can see/know the data inserted， do I able to query historical data from Pgadmin

2. There has time interval at the dashboard and that can set by the customer, but it not functioning, is that any setting can if I want to change and let the customer query the data?

3. Anyway to capture dashboard data or from rule chain and save as historical data in DB ? I saw it have a download option (Json) but not sure how it can save into database instead?

4. Beside Things board web site, any recommended learning platform for Things Board ?

**Comment by kastayou** [comment]
`I only know the RAW data store at table ts_kv， ts_kv_latest， but actually I don't understand how the things board store inside the data if like that any way or link that can see/know the data inserted， do I able to query historical data from Pgadmin`
Do you absolutely need to access the data inside the database?
It is better to use thingsboard API to access the historical data (called telemetry). You can check for example:
https://demo.thingsboard.io/swagger-ui/#/telemetry-controller/getTimeseriesUsingGET

`There has time interval at the dashboard and that can set by the customer, but it not functioning, is that any setting can if I want to change and let the customer query the data?`
This functionnality should work. You should try to explain what you are doing, what do you expect and what do you see.

`Anyway to capture dashboard data or from rule chain and save as historical data in DB ? I saw it have a download option (Json) but not sure how it can save into database instead?`
What kind of data? In the rule chain, there is an action node called "save timeseries" that will save the data in the database.

`Beside Things board web site, any recommended learning platform for Things Board ?`
Hi higly recommand that you check the thingsboard youtube channel. There are a lot of videos showing the different functionnalities. I found them very useful.
https://www.youtube.com/playlist?list=PLYEKB_XwLCZJ6T8RPLTjRwMw0eoabpEKO
You can follow this guide in 3 parts (you will learn a lot of things):
https://www.youtube.com/watch?v=0io1YnQjIwA
https://www.youtube.com/watch?v=mqWEGs1Z2BQ
https://www.youtube.com/watch?v=TyUKx5rNJSs
