### ISSUE TITLE
[Question] PE Mobile App Customisation: add new Menu 

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#6196]
On Thingsboard PE mobile app, is it possible to customize the menu on bottom? 
Let say I wanna put new menu "My car" and when press the menu, it will open "My Car" dashboard 
and when open a dashboard, Menu bar on bottom should keep open (menu bar not hide)

![image](https://user-images.githubusercontent.com/12267053/156497112-74de2294-617b-4024-a484-324f2f0420db.png)

if possible, how to do it? any documentation how to use thingsboard api in PE Mobile flutter?

**Comment by ssakharova** [comment]
Hello @evanderbird,

I can recommend you try to open your GitHub issue with respect to the product you are using:

[Issues · thingsboard/flutter_thingsboard_app](https://github.com/thingsboard/flutter_thingsboard_app/issues) 

[Issues · thingsboard/flutter_thingsboard_pe_app](https://github.com/thingsboard/flutter_thingsboard_pe_app/issues) 

Please describe all the details of your case there, and then you will increase the probability that the GitHub community will be able to help you.

Best regards,
Sofiia
