### ISSUE TITLE
New device type freezes the "Add device" procedure

### ISSUE THREAD

**Issue by vchryssos** [thingsboard/thingsboard#620]
When trying to add a new device, I do:
- Add new device <pop-up window appears>
- Add device Name <TAB>
- Add new device Type <...freezes! see attached gif from screencast>

![tb add new device type](https://user-images.githubusercontent.com/3367469/36846917-3af442fe-1d65-11e8-8244-d62f770728e6.gif)

**Comment by vchryssos** [comment]
Just noticed: if you 
- select <blank> from drop-down list
- press <TAB> to go to next option 
- return back to 'Device tab'

Then you can add a new device type and continue the procedure.

**Comment by Karabiy** [comment]
specify your user agent and also whether the issue persists for the ThingsBoard 3.0

**Comment by LeoMorgan113** [comment]
This issue fixed in the newest releases.
https://thingsboard.io/docs/reference/releases/
