### ISSUE TITLE
[Question] OTA update logic with rule engine

### ISSUE THREAD

**Issue by lidavid** [thingsboard/thingsboard#6206]
**Component**

 * Rule Engine

**Description**

I am trying to implement OTA update logic via the rule engine. What I would like to achieve is when a device updates a client attribute  ( firmware version ) I want to to check if there is another OTA package that meets some criteria and if so assign it to the device. Is this kind of thing possible ? Is there any nodes that can help me get the OTA updates that I have uploaded ?

**Comment by epalchenko** [comment]
Hello,
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
