### ISSUE TITLE
[Question] How to let the ThingsBoard detect current timewindow has been changed.

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#6207]
Hi if i want to make the system to refresh to 0 value in the specific time, such as recorded value and the time reach 8am, it will back to 0, i make the coding as post processing function in the widget in the dashboard, but it not functioning, any recommendation if i want to back to value 0 when meet specific time?

The following is the picture of the screenshot of my code at the dashboard widget that using post-processing function.

**Comment by mykhailokornieiev** [comment]
Hi. Idk is your question is still relevant, but you can try to use Scheduler with the type Update Attributes or with a custom type like Post Telemetry. Please note, that Scheduler available only in PE
https://thingsboard.io/docs/pe/user-guide/scheduler/#update-attributes

**Comment by Ultrazombie** [comment]
Closed due to inactive
