### ISSUE TITLE
Thingsboard Server UI failure

### ISSUE THREAD

**Issue by krzischp** [thingsboard/thingsboard#621]
I added a new tab that's called piscari (I did the analogy with the other tabs). I wrote simple html code in the new file piscari.tpl.html in order to test. It was working (when clicking on the new tab, the page was loaded). But then, I had to use a shell command line. I searched on the internet, and I found that I had to download require.js. So I did it, then I moved the file require.js to the ui/src/app/piscari/ directory. And I wrote the following html/javascript code in the file piscari.tpl.html:
<html>
<body>
<form id="myForm">
    <input id="text1" type="text" value="Write something..." />
    <input id="text2" type="text" value="Write something..." />
    <br /><br />
    <input type="submit" value="Submit !" />
    <input type="reset" value="Reset !" />
</form>
  
<script src="require.js">

//the code I saw on the website: https://nodejs.org/api/child_process.html
	const { spawn } = require('child_process');
	const ls = spawn('ls', ['-lh', '/usr']);

	ls.stdout.on('data', (data) => {
  	console.log(`stdout: ${data}`);
	});

	ls.stderr.on('data', (data) => {
  	console.log(`stderr: ${data}`);
	});

	ls.on('close', (code) => {
  	console.log(`child process exited with code ${code}`);
	});
</body>

</script>
 </html>

Then I build using maven:
mvn -T 4 clean install

and I get, in the Reactor Summary, 

[WARNING] Missing header in: /home/thingsboard/ui/src/app/piscari/require.js
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [ 10.861 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.205 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 11.734 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.634 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.743 s]
[INFO] Thingsboard Server DAO Layer ....................... SKIPPED
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  2.091 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [ 29.463 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.200 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  6.353 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  5.174 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  7.333 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  1.655 s]
[INFO] Thingsboard Server SQS Extension ................... SUCCESS [  8.080 s]
[INFO] Thingsboard Server SNS Extension ................... SUCCESS [  4.269 s]
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport ......................... SKIPPED
[INFO] Thingsboard COAP Transport ......................... SKIPPED
[INFO] Thingsboard MQTT Transport ......................... SKIPPED
[INFO] Thingsboard Server UI .............................. FAILURE [04:21 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  4.473 s]
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:33 min (Wall Clock)
[INFO] Finished at: 2018-03-02T00:21:55+00:00
[INFO] Final Memory: 91M/848M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project ui: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui

What's the problem here? I would like to know a solution to execute a shell command line in this file, please.
Thank's in advance!

**Comment by vparomskiy** [comment]
The error is 
" Some files do not have the expected license header "
During maven build, there is a goal that checks that all files have a correct license header.
To make it work, please run this command before building project
`mvn license:format`
