### ISSUE TITLE
[Question] Does Filters Support Live Table Update?

### ISSUE THREAD

**Issue by emrekardaslar** [thingsboard/thingsboard#6210]
**Component**
* EntitiesTableWidgetComponent

 * UI

**Description**
Does filters support live table update? For example, I set a filter like the value is greater than 10. I noticed that even if the filter is selected, it does not apply when new data come in. The table shows also the values under 10 (does not apply filter).

**Environment**
 * OS:  MACOS
 * ThingsBoard: v3.3.3
 * Browser: Chrome

**Comment by ashvayka** [comment]
Most of the ThingsBoard widgets use "dynamicQuery" parameter. This allows to periodically re-evaluate filter on the back end. See following parameters: https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L71

**Comment by emrekardaslar** [comment]
Thank you for your answer. Closing the issue...
