### ISSUE TITLE
Create alarm

### ISSUE THREAD

**Issue by ImNotitsami** [thingsboard/thingsboard#6216]
I'm new to the things board and i currently helping my company to do the IOT platform project using Things Board. Do somebody has the knowledge to the below question? Hopefully I can get suitable resources that can help me to complete the project given by the company.

please i'm sending  telemetry  values from the command prompt, and i wanna if the current value is greater than the previous value i have an alarm. please how i can do that ?

**Comment by ashvayka** [comment]
https://thingsboard.io/docs/user-guide/alarms/

**Comment by ashvayka** [comment]
See https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/transform-telemetry-using-previous-record/ as well to learn how to find a previous value using rule engine
