### ISSUE TITLE
Use base URL instead of IP address & port in communication emails

### ISSUE THREAD

**Issue by eeVoskos** [thingsboard/thingsboard#622]
This is a user experience issue.

In all communication emails (activation email, password reset, etc) sent by Thingsboard, the format of the link is `http(s)://IP_ADDRESS:PORT/api/noauth/activate?activateToken=XXX`. However, in a real-world scenario, the users log in using a URL (e.g. `https://thingsboard.example.com`).

It would be great if there was a base URL value, perhaps the one set in the *Base URL* field under the general system settings, that would be used in all links instead of the IP address and port (e.g. `https://thingsboard.example.com/api/noauth/activate?activateToken=XXX`).

![tb_base_url_settings](https://user-images.githubusercontent.com/505321/36897768-96a9efde-1e20-11e8-839e-c022f96c6e2b.PNG)

Is there a suggested workaround for this?

**Comment by ashvayka** [comment]
Whitelabeling, including the email templates, is part of Professional Edition functionality.

**Comment by eeVoskos** [comment]
Well, I'm not talking about whitelabeling per se. The ability to set a global URL instead of IP address that would be exposed in the communication with the world is a basic functionality in server apps.

**Comment by Javierete** [comment]
Hello @ashvayka . I think @eeVoskos is correct. I explain my observation arround this:

I have thingsboard installed listening on
`server:
  # Server bind address
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  # Server bind port
  port: "${HTTP_BIND_PORT:8080}"` 

I have HaProxy in front forwarding 443 port to machine's ip 8080 port. Under thingsboard sysadmin account, the base url is defined as https://domain.com
Now if I activate a new user under thinsgboard, the generated activation link (under email) is https://domain.com:80/api/noauth/activate?activateToken=xxxxxx

So the issue here is generating activation links (we need to remove the port). It's the intended behaviour?

**Comment by aderusha** [comment]
It seems like @ashvayka is trying to say user activation is intentionally broken unless you pay for PE.  Is this the official stance going forward?

**Comment by pablodbc** [comment]
Hello @Javierete ,

I had the same issue but using nginx as a proxy. My solution was to make thingsboard use https; this way, the activation link will be https://domain.com:443/api/noauth/activate?activateToken=xxxxxx And you won't have this problem. I hope it is not too late for you to read this. Sorry for my english.

Best regars

**Comment by garysmi2** [comment]
And for the record, after looking at the source code, correct way to deal with this if you are behind a proxy i.e.  haproxy

On the request add the headers:

x-forwarded--proto https   
x-forwarded-port 443

**Comment by andyesys** [comment]
We also use stunnel to terminate https and mqtts. And we also get a broken activation link with http:// in front, instead of https.

**Comment by Tangerino** [comment]
I still face this problem. Any other tip? Even when I added the x-forwarded headers the platform is sending HTTP request over the port 443 which yield a bad request

**Comment by eeVoskos** [comment]
We eventually overcame this problem with a minor change in code and proper nginx configuration. More specifically:

1) In `/application/src/main/java/org/thingsboard/server/controller/BaseController.java` we changed the `constructBaseUrl()` method to the following:

<pre><code>
protected String constructBaseUrl(HttpServletRequest request) {
    String scheme = request.getScheme();
    if (request.getHeader("x-forwarded-proto") != null) {
        scheme = request.getHeader("x-forwarded-proto");
    }
    int serverPort = request.getServerPort();
    if (request.getHeader("x-forwarded-port") != null) {
        try {
            serverPort = request.getIntHeader("x-forwarded-port");
        } catch (NumberFormatException e) {
        }
    }
    <b>// This hack allows us to control the base url in communication emails
    // using the 'Host' header in our reverse proxy server
    String host = request.getServerName();
    if (request.getHeader("Host") != null) {
        host = request.getHeader("Host");
    }
    if (host.contains(":")) {
        host = host.split(":")[0];
    }</b>
    return String.format("%s://%s:%d", scheme, host, serverPort);
}
</pre></code>

This basically allows controlling the host using the `Host` HTTP header.

2) On your nginx configuration, just pass the `Host` header in the appropriate `location` block:

<pre><code>
server {
    server_name my.domain.com;
    listen 80;
    listen 443 ssl;

    ssl_certificate $certificate_path;
    ssl_certificate_key $certificate_key_path;

    location / {
        proxy_pass http://$thingsboard_ip_address:8080;

        # Required for Websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        <b># Set headers for Thingsboard domain white labeling
        proxy_set_header Host $host;</b>

        # Force https redirect
        if ($scheme != "https") {
            return 301  https://$host$request_uri;
        }
    }
}
</pre></code>

I hope this helps.

**Comment by lswanderleygit** [comment]
Has anyone managed to solve this problem?

I'm also having this problem, when I try to activate a user through link I'm redirected to the domain:80 not found, and when I delete the port: 80 the uri works normally.

not found: https://www.domain:80/
![image](https://user-images.githubusercontent.com/20526353/56901552-d096c780-6a6e-11e9-8db7-ccd5f9754d68.png)

found: https://www.domain/
![image](https://user-images.githubusercontent.com/20526353/56901626-f9b75800-6a6e-11e9-8696-c23bedd1137c.png)

**Comment by eeVoskos** [comment]
@lswanderleygit the solution I posted above still works. See https://github.com/thingsboard/thingsboard/issues/622#issuecomment-446939913.

However, in the latest version (2.3, 2.3.1) I see that it is *a bit* broken, meaning that if my nginx config is for *my.domain.com*, then Thingsboard's activation url starts with https://my.domain.com:80. Which is fine in my case, as the port 80 redirect works just fine.

Keep in mind that for this solution to work you need to download the source code, make the code change manually and then build Thingsboard from source. Check out the documentation here:
https://thingsboard.io/docs/user-guide/install/building-from-source/

**Comment by thhart** [comment]
It is sufficient to activate the prohibition of hostname from client usage in the base URL setting. Then the base URL is used always.
