### ISSUE TITLE
[Question] Kafka pod: No space left on device

### ISSUE THREAD

**Issue by ivangarcialopez** [thingsboard/thingsboard#6220]
**Component**
Kafka Pod

 * Installation

**Description**
Hello, I finally was able to install the PE 3.3.2 version On Premise in our Azure  subscription. 

After 3 days working, with 18 devices sending telemetry via 1 MQTT subscription (4 variables) every 2 minutes, the TB stopped receiving MQTT messages.

I check the pods and I found an error in one of the kafka pods that no space left on device. I didn't change any of the yml files from the installation. Do I need to make any change in the configuration?

**Environment**
 * OS:  Azure Microservices
 * ThingsBoard: 3.3.2

**Comment by ivangarcialopez** [comment]
Finally by deleting the kafka logs and redeploying the system started to work.

**Comment by amarkevich** [comment]
in my case `logs` volume needs to be increased. still growing; main consumption comes from 
`1.0G    tb_rule_engine.main.0-0/`

**Comment by hsanderr** [comment]
how do i increase these logs volume?
