### ISSUE TITLE
[Bug] Table sort does not properly working on decimals

### ISSUE THREAD

**Issue by haibbi** [thingsboard/thingsboard#6225]
**Describe the bug**
Table sort numeric values alphabeticly.

**Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard Version _**3.3.3**_
  * OS Name and Version  _**Ubuntu 18.04.6 LTS**_

**Client Environment**

**Desktop:**

* OS: _**Ubuntu**_
* Browser _**Chrome**_
* Version _**99.0.4844.51 (Official Build) (64-bit)**_

**To Reproduce**
1. Create three separate devices.
2. Send telemetry to these devices. First one is like `{"temp": 200.0}`, second `{"temp": 800.0}`, third `{"temp": 1000.0}`
4. Add `Entities table` to dashboard and add devices into the data source
5. Sort by  `temp`
6. Then the result is

| entity | temp ^ |
|---|---|
| device1 | 1000.0 |
| device2 | 200.0 |
| device3 | 800.0 |

**Expected behavior**
Data should be properly sorted. Table should be like 
| entity | temp ^ |
|---|---|
| device1 | 1000.0 |
| device2 | 800.0 |
| device3 | 200.0 |

**Additional context**
If you change data to `200.1, 800.1, 1000.1` sort works.
There is a [method - convertValue](https://github.com/thingsboard/thingsboard/blob/c93309a496a5e5b6735435c1f41425feb90b0dcf/ui-ngx/src/app/core/api/entity-data-subscription.ts#L745) which decide string value is numeric or string. 
In JavaScript `Number(val).toString() === val` this clause work like `"200" === "200.0"`.

**Comment by SuminDenis** [comment]
Hi @haibbi,

I'm glad to inform you that this issue was resolved in the latest ThingsBoard version. If, after an update, this problem still occurs, please create a new issue with updated information.
