### ISSUE TITLE
[Question] Mobile browsing problems

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#6226]
**Component**
 * Generic

**Description**
There are problems with the navigability of dashboards on mobile devices. If there are charts in the dashboard for example, when I try to scroll down, the action generates a zoom on the chart and therefore it is impossible to navigate down. How can you solve this problem? Can I disable zooming on charts? Are there other solutions?

Thank you

**Comment by gednz** [comment]
I find this to be a major issue on mobile too.

A secondary consideration would be the option to disable zoom completely for all devices. 
I have cases where the Timewindow settings are relevant to the chart title and/or the post-processing calculations, therefore being able to change the timewindow makes the chart incorrect.

It seems strange that we can disable the display of the timewindow to the user but they can still over-ride it by swiping or click-dragging.


Regards
Ged

**Comment by gednz** [comment]
I have found a work around while we wait for this feature to be added.
This will disable zooming on mobile and desktop.

Create a custom Timeseries widget and add/amend the following functions:
```
function killZoom() {
    var o = self.ctx.flot.plot.getOptions();
    //o.selection.mode = null; // should have worked but dosen't
    o.selection = null;
}
self.onInit = function() {
    self.ctx.flot = new TbFlot(self.ctx); 
    killZoom();
}
self.onDataUpdated = function() {
    self.ctx.flot.update();
    killZoom();
}
self.onResize = function() {
    self.ctx.flot.resize();
    killZoom();
}
self.onEditModeChanged = function() {
    self.ctx.flot.checkMouseEvents();
    killZoom();
}
```

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
