### ISSUE TITLE
[Question] How to setup Login White Labelling for Customer

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#6234]
**Component**
 * Generic

**Description**
It is not clear to me how to setup the Login White Labeling for a Customer (non Tenant).
We are using Thingsboard in Cloud (PaaS) and we have configured the Login White Labeling for the Tenant.
Now we want to allow each Customer owned by the Tenant to customize its own login screen with color and logo.
Customers are configured with "Allow White Labeling" checkbox set.
By looking into the the Login White Labeling configuration pane, it asks for a Domain name and Base URL, but which domain name is to be used? 
We registered the domain name for the top level tenant login screen, and that's the only domain we can register in the system, and it is not accepted as domain for other Customers ("already registered").
Please let us know, thanks in advance

**Environment**
Thingsboard PaaS

**Comment by igloodan** [comment]
@albtrentadue,

As I understand it, you cannot access the White Labelling section of the user interface unless you're logged in as a user within the Customer hierarchy. You'll have to create a dummy user (maybe using "[plus addressing](https://www.msoutlook.info/question/886)") and then login with that user to get access to the Customer White Labelling section.

Thanks.

**Comment by albtrentadue** [comment]
@igloodan 
Hi Daniel, thanks for your answer.
I do log in Thingsboard as a user defined in the Customer's user group, and this is how I get access to the Customer's Login White Labelling configuration pane.
My question was: which Domain shall I specify once I get there? (see attached image) ![wl1](https://user-images.githubusercontent.com/1144682/157879892-012664a1-d5cf-48ea-b759-ae1c0c892724.png)
The Domain I used to configure Login White Labelling at Tenant level is not accepted here ("Already registered") and that's the only Domain I could register in Thingsboard so far.
Whithout such Domain, Login White Labelling at Customer level cannot complete.

**Comment by igloodan** [comment]
@albtrentadue 

You can only have one set of White Labelling options per domain, if you had two setups then the system wouldn't know which to use when a user first accessed the login page.

You **must** have a second domain or sub-domain to use the customer White Labelling so that the system knows which set to use when the domain in question is accessed.

Does that make sense?

Thanks.

**Comment by albtrentadue** [comment]
@igloodan 

Hi Daniel.
Sure it makes sense. Hence my question is: where shall I register any second domain/sub-domain?
The "Domain" section in the Tenant's System Settings only allows to register 1 domain (see 1st image, domain hidden for privacy...) 
![wl1](https://user-images.githubusercontent.com/1144682/158119104-d14684b8-881a-4032-b30f-a14f3e7adade.png)

and I haven't found any "Domain" section in the System Settings menu when I log in as the Customer Admin in the  Customer's user group (see 2nd image).
Without such possibility, the (Login) White Labelling for Customer configuration pane is pointless.
![wl2](https://user-images.githubusercontent.com/1144682/158119147-0bf01198-f683-443d-aeec-1bca49e31f51.png)

Please shed some light.

Thanks!

**Comment by igloodan** [comment]
@albtrentadue 

Have you got "Allow White Labelling" enabled for the customer?
You will find this in the customer details at the Tenant level.

If you have then you should have the below menu for their "Login White Labelling" when logged in as a customer user.
![image](https://user-images.githubusercontent.com/50181878/158176561-a51163e2-d685-4d52-aff3-d0e3d9283300.png)

Thanks,

**Comment by albtrentadue** [comment]
@igloodan 

Hi Daniel, thanks for following the issue.

I do have such "Login White Labelling" menu item in the Customer Admin user menu. Indeed, this is how I took the screenshot in my post for this issue 3 days ago. See below.
![wl1](https://user-images.githubusercontent.com/1144682/157879892-012664a1-d5cf-48ea-b759-ae1c0c892724.png)

Just to be sure, here is the Customer setting:
![wl3](https://user-images.githubusercontent.com/1144682/158188891-610ea28b-13aa-403b-9235-d76820bc53e7.png)

What I miss is not really access to White Labeling and Login White Labeling configuration, but the ability to register another domain for this Customer, either as a Tenant Admin user or as a Customer Admin user.
By looking in my post above, you may see that the Tenant can register only one Domain (which is used) and Customer Admin user misses the "Domain" menu item in the "System Settings" menu (there is only "Home Settings")

Thanks.

**Comment by igloodan** [comment]
@albtrentadue 

I think this is maybe beyond my knowledge, I don't use the cloud version, I host it myself.
It might be that you're limited on the cloud version to a single domain?

Thanks.

**Comment by albtrentadue** [comment]
@igloodan

Hi Daniel. This is a good observation.
Do you have on your on-premise version the possibility to register more domains?

**Comment by albtrentadue** [comment]
@igloodan 

Hi Daniel
Your hints are helpful. I will check them.
I think the next step will be asking directly how to register multiple domains in PaaS

Thank you!

**Comment by albtrentadue** [comment]
@igloodan 

Hi Daniel
FYI, I have created [a new issue](https://github.com/thingsboard/thingsboard/issues/6263) for this topic.
