### ISSUE TITLE
How I send e-mail?

### ISSUE THREAD

**Issue by Victorio1209** [thingsboard/thingsboard#6236]
* Rule Engine

**Description**
I created a count in sendgrid and I was configured the nodes:
![image](https://user-images.githubusercontent.com/99403075/157723271-72d70956-86fa-49c0-b719-075d8e66ddbb.png)
![image](https://user-images.githubusercontent.com/99403075/157723472-7b8316d2-112a-4556-83e7-a0b8a64206c6.png)
![image](https://user-images.githubusercontent.com/99403075/157723560-e8dbd616-cdd8-4c8b-ba93-8ff02b4a36cc.png)

What is the error?

**Environment**

 * OS:  name and version
 * ThingsBoard: Community edition
 * Browser: Google chrome

**Comment by mde2017** [comment]
Hi @Victorio1209,

maybe the connection to Sendgrid SMTP is not working correctly.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email-to-customer/

Alternatively you can configure the SMTP setting with Sysadmin user. Where you can also send test emails for verifying if everything is working:

![image](https://user-images.githubusercontent.com/25298332/157827533-f81906c1-16e2-4049-8311-3d0908ed084e.png)

**Comment by Victorio1209** [comment]
Hello @mde2017. I try with thingsboard cloud where there is the test, but the response is error.

![image](https://user-images.githubusercontent.com/99403075/157867084-7f3a713a-5a9f-42fc-974d-bdc7fc381f95.png)

**Comment by mde2017** [comment]
In the last screenshot, you haven't set the SMTP protocol.
Please try again after configuring the protocol dropdown.

**Comment by Victorio1209** [comment]
Now I tried with Google.

![image](https://user-images.githubusercontent.com/99403075/157870924-81053ca1-164a-410c-916d-5c81f21e4060.png)

**Comment by Victorio1209** [comment]
@mde2017 I have set the smtp now.

![image](https://user-images.githubusercontent.com/99403075/157871957-fb2d09cf-2d13-4d6d-adf4-473794747457.png)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
