### ISSUE TITLE
[Bug] Chrome web page break when I use thec widget on dashboard

### ISSUE THREAD

**Issue by cyt9606** [thingsboard/thingsboard#6237]
Chrome version:99.0.4844.51 
OS: windows 10;  MAC OS
If I edit the widget  [switch control] and tick the option [Show on/off labels] in Advance, the dashboard web page in Chrome will stuck and crashed.If I uncheck the option,it will work well.
When I check the option,it will work wwll on other web broswers like firefox, edge, safari.

**Comment by mde2017** [comment]
Hi @cyt9606 

I couldn't reproduce this error.
Tested with:
- OS: Windows 10
- Chrome: 99.0.4844.51
- TB PE 3.3.3

Could you provide more details, e.g. which TB version you are using?

**Comment by cyt9606** [comment]
TB 3.3.3  run on docker
widget:Control widgets-switch control
I found I need to  check  both the options [Initial value]  and [Show on/off labels] in advance ,it will happen

**Comment by cyt9606** [comment]
I run TB 3.3.3 on docker

and I tried to reproduce this error in the official demo https://thingsboard.cloud/
create a new dashboard
add widget:Control widgets-switch control
edit  widget-advance-check both  [Initial value]and [Show on/off labels] and apply changes
and the it happened

**Comment by cyt9606** [comment]
> Hi @cyt9606
> 
> I couldn't reproduce this error. Tested with:
> 
>     * OS: Windows 10
> 
>     * Chrome: 99.0.4844.51
> 
>     * TB PE 3.3.3
> 
> 
> Could you provide more details, e.g. which TB version you are using?

I run TB 3.3.3 on docker

and I tried to reproduce this error in the official demo https://thingsboard.cloud/
create a new dashboard
add widget:Control widgets-switch control
edit widget-advance-check both [Initial value]and [Show on/off labels] and apply changes
and the it happened

**Comment by mde2017** [comment]
Unfortunately, still no error with Chrome:

![image](https://user-images.githubusercontent.com/25298332/157863248-dbad0910-3014-43d3-829a-bb41eef6ec92.png)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
