### ISSUE TITLE
navigate to new dashboard state with action custom

### ISSUE THREAD

**Issue by ImNotitsami** [thingsboard/thingsboard#6239]
Hey I would really appreciate some help,
Does anyone know how a can navigate to new dashboard state with action custom :
this is the  code im using but i have no response :

var $injector = widgetContext.$scope.$injector;
$injector.get('deviceService').getDevice(entityId.id).then(function(device) {
    if(device.type == 'Energy sensor1') {
      openDashboardState('energy_state');
    } else if (device.type == 'Water sensor1') {
      openDashboardState('water_state');
    } else {
      openDashboardState('temperature_state');
    }
  });

function openDashboardState(statedId) {
  var params = {
    entityId: entityId,
    entityName: entityName
  };

  widgetContext.stateController.openState(statedId, params, false);
}

**Comment by yungwenpeng** [comment]
Hi ,
I'm not sure it's right or not. you can try to set a alert to display your params : alert(JSON.stringify(params)), and compare it to the other correct widget's params.

function openDashboardState(statedId) {
var params = {
entityId: entityId,
entityName: entityName
};
alert(JSON.stringify(params));
widgetContext.stateController.openState(statedId, params, false);
} 

I think it should be like : params:{"targetEntityParamName":{"entityId":{"id":"entityId","entityType":"entityType"},"entityName":"entityName","entityLabel":"entityName"},"targetEntityParamName":"targetEntityParamName"}

**Comment by ssakharova** [comment]
Hello @ImNotitsami,

After the ThingsBoard v.3.0, you need to use the subscribe method. Please use this code instead: 

var $injector = widgetContext.$scope.$injector;
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
if(device.type == 'Energy sensor1') {
openDashboardState('energy_state');
} else if (device.type == 'Water sensor1') {
openDashboardState('water_state');
} else {
openDashboardState('temperature_state');
}

});

function openDashboardState(stateId) {

var params = {
entityId: entityId,
entityName: entityName
};

widgetContext.stateController.openState(stateId, params, false);
}

Regards,
