### ISSUE TITLE
[Feature Request] Upgrade from monolithic to microservice architecture

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#6246]
**Is your feature request related to a problem? Please describe.**
I started off a TB production server using [monolithic setup](https://thingsboard.io/docs/user-guide/install/docker/), works perfectly. However, it is time to scale, and I'd like to upgrade to [microservice architecture](https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/) (MSA). Unfortunately, there isn't any successful attempts I have found online. 

I have had a few futile attempts.

1. The cassandra version mismatch between monolithic (4.0.1) and MSA (3.11.3). I had to bump the later.
2. After that, I copy the filesystem of the db from monolithic to MSA, without changing a thing. It did not work.
3. I removed everything and started all over again. This time, I installed and started MSA afresh. Able to login to an empty TB. Fine.
4. Now I copy again the db from monolithic and replace the folders in MSA. Restarted MSA. Still failed.

**Describe the solution you'd like**
Provide a simple guide/script to perform especially the data migration part.

TQ.

**Comment by pon0marev** [comment]
The Cassandra version has been updated to 4.1.
To migrate, you need to configure and test the new environment. Then, perform a backup of the Postgres and Cassandra database and restore it to the new environment. https://github.com/thingsboard/ThingsboardSupport/tree/main/databases
For database Cassandra, you can also add a new datacenter and perform a repair. See Cassandra's database migration.
