### ISSUE TITLE
[Question] how to deploy Rule Engine as a separate Micro service

### ISSUE THREAD

**Issue by makerlee** [thingsboard/thingsboard#6247]
**Component**
* Rule Engine

**Description**
According to Release Note: Ability to launch Rule Engine as separate microservice; but I can not find a spring-boot launch class.

**Environment**
 * ThingsBoard: 2.5+

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by NguyenTMinh** [comment]
how about now?
