### ISSUE TITLE
Sending downlink message from Thingsboard to the source.

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#6248]
**Component**

 
 * Rule Engine -> IoT Gateway
 * Generic

**Description**
I am receiving JSON data from device to the TB server by HTTP and 'statusCode:200' is sent back alright. But 'this device' needs a particular message ('81') in return to confirm that it has sent the message alright. Else it will continually try to to send the same message. 
Is it possible to sent back such downlink message by HTTP from ThingsBoard to the source (device)? 

Is Rule Chain of any help in achieving this? 

update: from the net I have gathered that TB PE have such option. But I am using CE at present. Someone suggested IoT Gateway REST connector may solve this issue. But could not found how to approach. 

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: version 3.3.2
 * Browser: Google Chrome Version 99.0.4844.51 (Official build) (64-bit)

**Comment by lincoln310** [comment]
Any answer? I have the similar question.

**Comment by debacs83** [comment]
I was suggested to look at the guide (https://thingsboard.io/docs/guides/). And I did. Also searched the net for Lambda function to POST data to EC2. 
Look at the 'Connect your device', then 'Telemetry upload API'. 
In order to publish telemetry data to ThingsBoard server node, send POST request to the following URL:
http(s)://host:port/api/v1/$ACCESS_TOKEN/telemetry

What I did:
(1) first tested with curl. You can find how to do it in that page. I did it just to pre-test if I can send payload to TB. 

(2) sending data from Lambda to ThingsBoard installed in EC2:
    1)  create policy and role to access EC2 in vpc from lambad
    (https://www.transposit.com/devops-blog/incident-management/2019.12.18-using-lambda-as-an-ssh-proxy/)
   2) write the lambda (this in node.js)  
     (https://stackoverflow.com/questions/47404325/aws-lambda-http-post-request-node-js)
     
Should work. If not please let me know. 

BTW, if you have or find any python version of Lambda function to send data from Lambda by HTTP POST could you please share it?

**Comment by debacs83** [comment]
Don't know if it is possible with Thingsboard CE. I did it by using a local server by using PHP. It receives the payload from GW (receiving data from sensors) and send that to TB and also return the desired Response to the sender (for me it was a GW). The local server was acting as a middle-man.

**Comment by lincoln310** [comment]
> Don't know if it is possible with Thingsboard CE. I did it by using a local server by using PHP. It receives the payload from GW (receiving data from sensors) and send that to TB and also return the desired Response to the sender (for me it was a GW). The local server was acting as a middle-man.

I think you can just implement it in GW? We can add custom process to specific topic. I have not use it yet. So i don't know whether it works.
