### ISSUE TITLE
[Question] Custom rule nodes - Failed to load configuration ui resources

### ISSUE THREAD

**Issue by marbrune** [thingsboard/thingsboard#6252]
**Component**

 * UI

**Description**
Created a custom RuleNode from rule-node-examples project and customized the component ui starting from rule-node-examples-ui-ngx project.
The custom RuleNode is visible, but not the structure of the form. The error says: "Failed to load configuration ui resources".

**Environment**

 * OS:  MS Windows 10 Pro
 * ThingsBoard: 3.3.3
 * Browser: Google Chrome 99.0.4844.51

**Comment by t0mZ4** [comment]
@marbrune did you find a solution to this ?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
