### ISSUE TITLE
[Question] Select multiple devices from Entities Table widget to display them in another dashboard state

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#6253]
**Component**

 * Generic / Widget

**Description**
I created a dashboard with an Entities Table widget in it. This widget has an action type `Navigate to new dashboard state` and action source `On row double click`. Everything's working fine when clicking one row in the table and jumping to the new dashboard state where the telemetry data is presented in several time charts for the selected device.

What I want to do is to click two or more rows at the same time (e.g. using `ctrl+click` or checkboxes) in order to show multiple devices in the new dashboard state instead of a single device.

Any ideas how to achieve this with the Entities Table widget?

**Environment**

 * OS:  macOS
 * ThingsBoard: Cloud
 * Browser: Firefox 98.0

**Comment by Civilduino** [comment]
I think this is a neat feature that should be implemented as it gives the possibility to quickly compare two or more devices from a long list.

I am trying to figure out this one, but it is difficult because I have very little experience with back-end programming. Looking at the Entities List widget's code and its action, I see that what needs to be updated in the action is the `entityName` that comes from `EntityData`. In this case, the `Event` needs to allow to select multiple rows, but how can I achieve that?

Code from [entities-table-widget.component.ts](https://github.com/thingsboard/thingsboard/blob/623abcd5b8be345ea20c7a8bf0ea28a34b7c7338/ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts#L698)

```javascript
public onRowClick($event: Event, entity: EntityData, isDouble?: boolean) {
  if ($event) {
    $event.stopPropagation();
  }
  this.entityDatasource.toggleCurrentEntity(entity);
  const actionSourceId = isDouble ? 'rowDoubleClick' : 'rowClick';
  const descriptors = this.ctx.actionsApi.getActionDescriptors(actionSourceId);
  if (descriptors.length) {
    let entityId;
    let entityName;
    let entityLabel;
    if (entity) {
      entityId = entity.id;
      entityName = entity.entityName;
      entityLabel = entity.entityLabel;
    }
    this.ctx.actionsApi.handleWidgetAction($event, descriptors[0], entityId, entityName, {entity}, entityLabel);
  }
}
```

Code from [table-widget.models.ts](https://github.com/thingsboard/thingsboard/blob/623abcd5b8be345ea20c7a8bf0ea28a34b7c7338/ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts#L63)
```javascript
  export interface EntityData {
  id: EntityId;
  entityName: string;
  entityLabel?: string;
  entityType?: string;
  actionCellButtons?: TableCellButtonActionDescriptor[];
  hasActions?: boolean;
  [key: string]: any;
}
```

**Comment by Civilduino** [comment]
It is not clear from the [handleWidgetAction](https://github.com/thingsboard/thingsboard/blob/da4c74287216fc6962c74f084c2eedebf06e1a64/ui-ngx/src/app/shared/models/ace/widget-completion.models.ts#L605) function description or the function code itself [handleWidgetAction code](https://github.com/thingsboard/thingsboard/blob/623abcd5b8be345ea20c7a8bf0ea28a34b7c7338/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1060) if the `entityName` can be more than one.

One idea is to dynamically generate an alias with the selected rows of the Entities Table widget so it can be used in the new dashboard state. But again, is this even possible (to generate a 'dynamic' alias)?

**Comment by JacksonBowe** [comment]
@Civilduino I'd handle this at the destination dashboard. To elaborate, the entity list widget is pretty solid with the functionality of navigating to a new dashboard. So here's how I'd handle it, 2 ways:

First way, most basic:
1. On your dashboard with the charts (the one you want to end up at) if you have the room put an entity list widget on it.
2. This entity list should show all the devices possible to compare.
3. Add a Custom Action on Row Click.
4. In the custom action you have access to loads of info; what you need is the entityName and the user id (print out `widgetContext` to grab userId, it's in there somewhere)
5. You're going to set an attribute on the USER called something descriptive like (dashboardX_devices_to_compare) ... or something like that. Just make it descriptive in case you want to reuse this functionality elsewhere.
6. Essentially you're going to add the clicked entity into an array, and store it as a SERVER attribute against the USER. <important
7. If the device is already in the list remove it, typical CRUD functionality
8. Now you should be able to create a filter and grab only specific devices where `DEVICE field 'entityName' in USER SERVER attribute 'dashboardX_devices_to_compare'`
9. If you're using current TB versions you can also change the row css of the device you click but that's just for style points.

Pretty sure that will work. Havn't tested it, but it's what I'd try first.

Second, much harder, approach.
1. Don't add a whole new entity list widget to an already cluttered dashboard.
2. Add a small button to the dashboard with an onHtmlEvent action
3. The button will make a dialog appear
4. Do all the above steps using the dialog. Be warned though, you need to be VERY competent with JS to do this. It's legitimately a nightmare.
5. Anyway here's what it would look like :D 
![chrome-capture (4)](https://user-images.githubusercontent.com/26427343/158711156-f9fbcbd5-6d02-419a-9a75-217aee729ff8.gif)


Good luck

**Comment by Civilduino** [comment]
I just can say...wow! it is like you read my mind :) you are a genius!

Thank you for the detailed explanation and I think I get the idea behind it. I will jump directly to try the first approach (although the second approach looks amazing and most suitable for my case as I already have a clustered dashboard). Any particular reason for using the `USER` entity instead of any other for assigning the attribute?

Anyway, multiple selection should be a default feature in the Entity Table widget ;)

**Comment by JacksonBowe** [comment]
By using the `USER` entity you can apply the selection only to the individual user. If you apply is globally, like on the devices for example, then when you have multiple people using the same dashboard changes they make will affect your display.

**Comment by Civilduino** [comment]
Hello again @JacksonBowe,

Hope all is good with you and thanks for the clarification. Well, if you work late at night (> 10:00pm) then we are on the same schedule hehehe!

I started trying option one with some success and failure as shown below.
- **OK** userId is found at `widgetContext.currentUser.userId`
- **OK?** user server side attribute can only be `String` or `JSON`, not array. Does it means that the array has to transformed to a string?
- **OK** save clicked entity in array with simple CRUD functionality.
- **FAIL** how do I access the user attribute in order to update it? found [this](https://stackoverflow.com/questions/49950517/how-to-access-attributes-from-thingsboard-serverside) googling but I get and error when calling `var attributeService = widgetContext.$scope.$injector.get('attributeService');` which says `NullInjectorError: No provider for attributeService!`. Do I need to use the REST API?
- **OK?**  filter based on user attribute using dynamic source type (see image below). The filter only allows me to select `String` as value type, but I guess it doesn't matter because it checks everything `in` the user attribute, right?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/27728926/159187707-aeea8f12-bc0b-4dc7-88c1-86685491674d.png">

**Comment by JacksonBowe** [comment]
Yeah you need to use the new syntax for attributeService
`let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));`

Then to get attributes it's kinda like this 
```
let attributes = {};
attributeService.getEntityAttributes(entityId, "scope")
        .subscribe(
            function(data) {
                if (data.length) {
                    for (let i = 0; i < data.length; i++) {
                        attributes[data[i].key] = data[i]
                            .value;
                    }
                }
            })
```

That will load all the attributes, just loop through for the one you want. Once you have it you can start adding to it, then save when done.

**Comment by Civilduino** [comment]
Thanks for helping me out here. I can tell you that it is not easy for me not having back-end programming skills but I don't give up that easy ;) in fact, cool to learn something new.

So, looking at the [widgetContext](https://github.com/thingsboard/thingsboard/blob/v3.3.4/ui-ngx/src/app/modules/home/models/widget-component.models.ts) API, all services are already included, so I can call them directly e.g. `widgetContext.attributeService.getEntityAttributes()`.

However, when trying to get the user attributes, nothing comes up because the `userId` doesn't have an `.entityType` or `.id` properties as required inside the `getEntityAttributes()` function, i.e. `let url = ´/api/plugins/telemetry/${entityId.entityType}/${entityId.id}/values/attributes/${attributeScope};´`

I tried the code using the entityId defined after the row click and the `SERVER_SCOPE`, it works as it should. 

Two questions:
1. Do I need to manually create a variable with `.entityId` and `.id`as required by the function?
2. How did you know that you need `.subscribe()`after the `getEntityAttributes()`function? I cannot see it in the API. It is difficult to find good documentation of these APIs or do you have some good references?

**Comment by Civilduino** [comment]
I came up with question 1 when writing the post above, so I tried the solution afterwards and it worked ;)
```javascript
const userId = {
    entityType: "USER",
    id: widgetContext.currentUser.userId
}
```
Getting closer...so question 2 left :D

**Comment by JacksonBowe** [comment]
@Civilduino to answer question #2, it's because at one point I was in your position and had no other option than to throw attempts at the wall until something stuck.

I knew that I needed to use promises but I'm not a JS programmer so I had to learn it all from scratch when developing my thingsboard dashboards.

When you use the `attributeService` you're making an api call. In JS when you make api calls you need to wait for the response in specific ways. Sometimes you can use `.then()` (which works for some thingsboard services but not all, good luck figuring out which). For most of the thingsboard services I recommend using `.subscribe()`. 

But yeah to answer your question, it's not a thingsboard specific thing, its because of Javascript magic.

**Comment by Civilduino** [comment]
Hello again @JacksonBowe!
I was away since my last reply and could not work more with this. But back on it!
I feel you, doing the same here but managed to progress a lot, specially with your help :)
Also found another post of yours on this [topic](https://github.com/thingsboard/thingsboard/issues/5298) ;)

Well `subscribe()` is for Observable objects in Angular and `promises` is in jQuery, see [here](https://stackoverflow.com/questions/42000883/what-does-the-subscribe-function-do). Furthermore, Observable objects are async, therefore the "waiting for response".

I had a problem when saving the attributes because I had the wrong order of the functions inside `subscribe` but fixed it.

Everything seems to be working except for the dashboard filter.
As you know, the user attribute can only be string and not an array. When I select many devices, I convert the array to a long string with all devices names, e.g. `"device1 device2 device3"` etc.
Then in the filter, the Entity field `name` is selected and using the operation `in` I try to check for the name "in" the user attribute string. However, this is not working.

How do you check for multiple devices names in the filter? :nerd_face:
