### ISSUE TITLE
[Question] How to integrate external API call in Thingsboard custom widget

### ISSUE THREAD

**Issue by Aviijit** [thingsboard/thingsboard#6255]
**Component**

 * Generic

**Description**

I am working on a project where I have multiple destination points and I want to calculate the optimized route between those points for a bike/ bicycle traveling mode.

we have created a custom widget and we are trying to add our own javaScript code to call google maps direction API but our request getting blocked.

we are using the community edition of Thingsboard.

**Environment**

 * OS:  GKE on GCP 
 * ThingsBoard: release-3.3.4
 * Browser: Chrome and 99.0.4844.51

**Comment by lucasKapf** [comment]
Hello, 
I also tried to do API calls from widget but I didn't achieved it.
Maybe you can use the REST API Call Rule Node inside a Rule Chain ?
Best regards,

Lucas

**Comment by bhaveshgohel** [comment]
Hi @Aviijit did you find the solution for calling external API call withing widget?

**Comment by mykhailokornieiev** [comment]
Hi. For such purpose, you will need to use `self.ctx.http.post() `service with necessary API endpoint parameteres.

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request
