### ISSUE TITLE
thingsboard gateway device not found

### ISSUE THREAD

**Issue by ghassen33560** [thingsboard/thingsboard#6256]
hello    i'm trying to send an rpc request from thingsbaord server to node mcu esp8266 via thingsbaord-gateway installed on raspberry pi 3 

i have this error and couldn't solve it , any suggests please 
|ERROR| - [tb_gateway_service.py] - tb_gateway_service - _rpc_request_handler - 753 - Connector "echo" not found"

**Comment by Andhuooo** [comment]
i also have this error

**Comment by ghassen33560** [comment]
hello sir did you find the solution?

**Comment by Andhuooo** [comment]
Now i'm connecting using modbus . rpc communication is working even though there is some errors

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket in https://github.com/thingsboard/thingsboard-gateway/issues repository with full description of your request.
