### ISSUE TITLE
[Bug] Customer User Cannot Access Assets Page

### ISSUE THREAD

**Issue by mon-dragon** [thingsboard/thingsboard#6259]
**Bug description**
Customer user gets 'Access Forbidden' popup when accessing Assets page

**Server Environment**

* Own setup
  * Docker deployment (thingsboard/tb-postgres:3.3.3)
  * OS: Ubuntu 18.04.5

**Client Environment**

* Desktop
  * OS: Windows 10
  * Browser: Firefox version 98

**To Reproduce**
1. Create a customer
2. Create a customer user
3. Create an asset
4. Assign asset to customer
5. Login customer user account
6. Access 'Assets' page

**Expected behavior**
See the list of asset(s) assigned to the customer

**Screenshots**
![image](https://user-images.githubusercontent.com/16236570/158348340-b15c15f6-b3b7-44bb-bcf7-9a147c33097d.png)

**Comment by mykhailokornieiev** [comment]
Hello mon-dragon
Please let me know if your issue is still relevant. Perhaps you have already found a solution?
Also prompt, whether the corresponding rights to the user in roles are issued?
Best regards,
Mykhailo

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
