### ISSUE TITLE
[Question] JSON payload schema, default MQTT Converter?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#6261]
**Description**
When using the Thingsboard MQTT interface and your IoT device has a not changeable json structure.
then it needs to be parsed/converted to the Thingsboard JSON format.
I assume it can be done in the rule engine.
But is there a way to do it with the Thingsboard PE Data converters?
or can this only be used when you connect to another server (integrations)

**Environment**

 * OS:  Ubuntu LTS 20.04
 * Thingsboard: 3.3.3

**Comment by JacksonBowe** [comment]
Yeah do it in the converters.

**Comment by KenSense** [comment]
> Yeah do it in the converters.

How can I link a converter to a default MQTT proflle (not an integration)?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
