### ISSUE TITLE
[Question] Login White Labeling: https possible only for one Domain in PaaS TB?

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#6263]
**Component**
 * Generic

**Description**
We are configuring a TB (PaaS) for an application where devices are assigned to several Customers and each Customer wants to access their dashboards through a customized UI. Some devices are also assigned to the Tenant, who manages TB configuration for all the Customers.
Then I configured a Domain for the Tenant (in the "System Settings"->"Domain" panel) and both White Labeling and Login White Labeling for the Tenant.  Tenant's domain has the form: "**www .thedomain.it**". So far, so good.

Now we want to configure Login White Labeling for Customers, at least to set their own logo on the login page.
The idea is to give a Customer a domain with the form: "**customer .thedomain.it**"
So we have configured Customers with "Allow White Labeling" checkbox and assigned All permission to White Labeling to Customer Admins.

What we see is that there is no way in TB PaaS to **register** the other domains for Customers. 
After configuring Customer's domain and Base URL in the Login White Labeling - and after configuring the DNS accordingly - the redirect works but **not in https**, and at first access the browser complains about certificate issues. 
This would not be acceptable for normal end users.
As I can see, Customer Admins have no way to register another domain in System Settings (see image below), beyond to the one already registered by the Tenant.
![wl2](https://user-images.githubusercontent.com/1144682/158423818-bd9da016-cf28-46c8-bebb-b66013c6f0f5.png)

Is that so? Is Domain registration limited **to only one** domain in TB Paas?

**Environment**
 * ThingsBoard: PaaS

**Comment by albtrentadue** [comment]
Hi, 
does anybody know if Domain registration limited to only one domain in Thingsboard Cloud ?

**Comment by vmlourenco** [comment]
Hello, i ask the thingsboard support team about this issue via email and the answer was we provide only 1 domain with HTTPS protection. so i think this topic can be closed
