### ISSUE TITLE
[Bug] Db upgrade from 3.3.1 to 3.3.4 failed

### ISSUE THREAD

**Issue by billr1** [thingsboard/thingsboard#6264]
I just did and rpm upgrade from Community 3.3.1 to 3.3.4 and am getting various SQL errors. I suspect this happened because of a missing case statement in xxx. As you can see from the attached image, the entry for 3.3.1 is missing. How can I easily recover from my current situation without wiping out the current installation and doing a fresh 3.3.4 install?

![image](https://user-images.githubusercontent.com/255000/158445540-3c2164b9-afeb-4d81-99fb-167fa4e19a73.png)

**Comment by billr1** [comment]
Not only is 3.3.1 missing from the above file, there's no 3.3.1 directory in the data/upgrade directory.

**Comment by mde2017** [comment]
Hi @billr1,

To be safe next time, try to follow the official upgrade documentation, that means don't skip any version and install the next version step by step:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/

In your case:
1. Upgrade 3.3.1 --> 3.3.2
2. Upgrade 3.3.2 --> 3.3.3
3. Upgrade 3.3.3 --> 3.3.4

**Comment by billr1** [comment]
Closing as operator error.
