### ISSUE TITLE
[Bug] Telemetry only storing first field

### ISSUE THREAD

**Issue by ivangarcialopez** [thingsboard/thingsboard#6266]
**Describe the bug**
Using MQTT and a data converter that previously worked in the Cloud environment and 2 weeks ago only the first field in the telemetry is being stored as data. Using debug we see that the data is being collected but not stored in the DB.

This is part of the data parser.
// Result object with device/asset attributes/telemetry data
var result = {
    deviceName: csv[2],
    deviceMessageFormatVersion: csv[1],
    deviceType: "be.Air",
    deviceLabel: csv[2],
    devicePlatformVersion: csv[0],
    timeStamp: parseFloat(csv[3]),
    attributes: {
        serialNumber: csv[2],
    },   
    telemetry: {
        co2: parseFloat(csv[5]),
        rssi_level: parseFloat(csv[4]),
        temperature: parseFloat(csv[6]),
        humidity: parseFloat(csv[7]),
    }
};

Only the CO2 is shown in the device Telemetry. As you can see only CO2 has the updated value. The other values are from 2 weeks ago.
![image](https://user-images.githubusercontent.com/6485021/158486791-df1fdcd9-099d-4ece-bfaa-50737a1397eb.png)

And this is the data we got from debugging the data parser. All telemetry data is in the JSON but is not stored.
{
    "deviceName": "89882806660000547523",
    "deviceMessageFormatVersion": "CO2V003",
    "deviceType": "be.Air",
    "deviceLabel": "89882806660000547523",
    "devicePlatformVersion": "CR0121",
    "timeStamp": 1647346832,
    "telemetry": {
        "co2": 602,
        "temperature": 21.2,
        "humidity": 52,
        "rssi_level": 24
    },
    "attributes": {
        "serialNumber": "89882806660000547523"
    }
}

**Your Server Environment**
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard 3.3.2
  * Kubernetes MIcroservices

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Mac
* Browser Chrome
* Version Version 99.0.4844.51 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**
* Connectivity
  * MQTT via one topic.

**Expected behavior**

**Screenshots**

**Comment by JacksonBowe** [comment]
Try returning it like this
```
{
    "deviceName": "name",
    "deviceType": "type",
    "attributes": {
        "attr": "val",
    },
    "telemetry": [{
        "ts": ####,
        "values": {
            "co2": ###,
            "temperature": ###,
            "rssi": ###
        }
    }]
}
```

Also, it could be a bug in your rule chain. Are you filtering specific values out? That's where I would look.

**Comment by ivangarcialopez** [comment]
I have reinstalled Thingsboard. It should be a bug in my rule chain.
