### ISSUE TITLE
[Bug] Customer users unable to view alarms

### ISSUE THREAD

**Issue by croemmich** [thingsboard/thingsboard#6267]
**Describe the bug**
When a user of a customer tries to view the alarms on a device or via a dashboard widget they receive a "Permission Denied" error.

Scenario 1:
* The device is owned directly by a Customer.

Scenario 2:
* The Device is owned by the Tenant and placed in a Device Group
* The Device Group is shared with the "Write" permission to a Customer

Other context:
* The Customer user is in Customer Administrators group.
* All roles/permissions are default/autogenerated.
* Alarms can be viewed by Tenant users.

**Your Server Environment**
* thingsboard.cloud

**Your Client Environment**
* OS: macOS Big Sur
* Browser: Chrome
* Version: 99

**To Reproduce**
1. Add a Customer
2. Add a Customer Administrator user to the Customer
3. Login with the new Customer Administrator user
4. Add a Device (details don't matter)
5. Select the new device and click the "Alarms" tab
6. See "Permission Denied" error

**Expected behavior**
Customer users should be able to see alarms.

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce this behavior on the latest version.
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
