### ISSUE TITLE
thingsboard3.3.4 ui-ngx build failed

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6268]
**Component**

 * UI

**Description**
ui-ngx build failed，output messages are as follows：
 Exit code: 1
[INFO] Command: node ./run.js
[INFO] Arguments:
[INFO] Directory: E:\work\corp\tb\thingsboard\ui-ngx\node_modules\postinstall-prepare
[INFO] Output:
[INFO] **ERROR** Failed to apply patch for package @geoman-io/leaflet-geoman-free
[INFO]
[INFO]   This happened because the patch file patches\@geoman-io+leaflet-geoman-free+2.11.4.patch could not be parsed.
[INFO]
[INFO]   If you just upgraded patch-package, you can try running:
[INFO]
[INFO]     cd patches\@geoman-io+leaflet-geoman-free+2.11.4.patc
[INFO]     patch -p1 -i h
[INFO]     npx patch-package @geoman-io/leaflet-geoman-free
[INFO]     cd ../..
[INFO]
[INFO]   Otherwise, try manually creating the patch file again.
[INFO]
[INFO]   If the problem persists, please submit a bug report:
[INFO]
[INFO]     https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

**Environment**

 * OS:  windows10
 * ThingsBoard: 3.3.4

**Comment by john1337** [comment]
i fixed it by delete geoman-io+leaflet-geoman-free+2.11.4.patch file in ui-ngx\patches,then success

**Comment by zhk0603** [comment]
work for me

**Comment by raoyh** [comment]
> i fixed it by delete geoman-io+leaflet-geoman-free+2.11.4.patch file in ui-ngx\patches,then success

thank you
