### ISSUE TITLE
thingsboard dashboard export to mobile application

### ISSUE THREAD

**Issue by ahmedjomaa1234** [thingsboard/thingsboard#6269]
* Installation

**Description**
hello i wanna ask you about community service please , 
i have iot project for school i need to know if it's possible to implement dashboard from thingsboard to my mobile application android studio please ? 
thank you !

**Comment by mykhailokornieiev** [comment]
Hello ahmedjomaa1234
Please let me know if your issue is still relevant. Perhaps you have already found a solution?
Also prompt, whether the corresponding rights to the user in roles are issued.
Best regards,
Mykhailo

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
