### ISSUE TITLE
Is it possible to get aggregation type in the data post-processing function?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6270]
Hi all,

Can you determine what type of aggregation (average, sum, etc) a plot is using in the post processing function?

**Comment by ssakharova** [comment]
Hello @OzyOzk,

In older versions, there was no option to determine what type of aggregation (average, sum, etc.) a plot was using in the post-processing function.
However, this possibility is already available in newer versions of Thingsboard.
