### ISSUE TITLE
[Question] Thingsboard PE -> Rule - How to implement average value group by a message field?

### ISSUE THREAD

**Issue by soyoeml** [thingsboard/thingsboard#6272]
**Component**

 * UI
 * Rule Engine
 * Analytics Nodes
 * Aggregate Stream Node
 * Average value

**Description**
I try to use Aggregate Stream Node to get average value grouped by a field. I can't find an option to do it.

**Environment**

 * OS:  name and version
 * ThingsBoard: 3.3.2 PE
 * Browser: Mac os Firefox 97.0.1

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
