### ISSUE TITLE
Control widget not updating on attribute value change

### ISSUE THREAD

**Issue by jerome83136** [thingsboard/thingsboard#6273]
Hello,

I'm stuck with my control widgets and I'm not sure if I did things correctly; so I need some help please.
I'm using the latest docker version of Thingsboard and TB IOT gateway, self hosted.

I want to use control switches to trigger my light switches.
My switches are running Tasmota and they are connected to my external MQTT service.
The switches are registred on Thingsboard as devices and everything is connected trought TB IOT gateway.
When a switch relay changes its status, the corresponding device immediately updates the corresponding client attribute; reflecting the "real" relay state.

**I just did a simple test:**
- Created a card widget and subscribed it to the device attribute of a switch.
- When I (manually or remotely) change the switch state; the card widget immediately displays the new state into thingsboard.
- Card widget works

- Then I created a control switch and subscribed it to the same device attribute of the same switch
- When I (manually or remotely) change the switch state, the widget doesn't updates. (even if I reload the dashboard)
- If I manually put the widget to "ON" and I (manually or remotely) change the switch state; the widget comes back to "OFF"

The device attribute of my switch can be **{"power1State":"ON"} or {"power1State":"OFF"}**
On the widget, this response is parsed with this script: **"return data ? true : false;"** (maybe needs some changes ? I'm not confortable with Javascript. Help welcome :-) )

Thank you for your help and feel free to ask for details
Best regards

**Comment by jerome83136** [comment]
UPDATE:

For others about to run out of hairs like me on this; I finaly had some luck.

It finaly worked after using this attribute control function: "return (data=="ON") ? true : false;"

I was unable to get it working with stock widgets; but it's OK with the ones coming from this repo: **https://github.com/rossmann-engineering/Collibellex-Thingsboard-Widgets#lightbulb1**

I think there is either a mistake on my side or maybe a fix on standards control widgets ?

A strange thing I noticed: when I set test attribute control function with "**return true;**" or "**return false;**"; standards widgets just ignore it. Only the widget from the "rossmann-engineering" repo are reacting correctly.

Still investigating.
Feel free to share some advice.

Best regards

**Comment by JacksonBowe** [comment]
What if you try using `"true"` and `"false"` as strings?

**Comment by jerome83136** [comment]
Hello,
Indeed it works

I modified the control function on a standard switch control widget with **"return data ? true : false;"**
Then I pushed "true" and "false" values to the target device attribute and it worked.

Thank you for your help

Best regards

**Comment by JacksonBowe** [comment]
@jerome83136 From memory data is stored as `boolean` but when you pull it into widgets it always gets converted to `string`. I think. It's been a while...
