### ISSUE TITLE
[Bug] LwM2M Bootstrap Registration (LinkParseException)

### ISSUE THREAD

**Issue by motters** [thingsboard/thingsboard#6274]
Our device connects to ThingsBoard via LwM2M (no sec, with bootstrap).
  * We created a "Device Profile" using the transport type LwM2M
  * We created a "Device" and assigned the profile. We also set the credentials to "no security".
  * Our device uses both bootstrap and server

Our device does successfully connect to the thingsboard lwm2m bootstrap server. However errors created in the transportLog:

```
error: Bootstrap session failed because of REQUEST_FAILED

error: BootstrapDiscoverRequest / failed because of org.eclipse.leshan.core.link.LinkParseException: Invalid Links [lwm2m="1.0",,;ssid=0,;ssid=1,,,,,,,] : URI-Reference [lwm2m="1.0"] should begin with "<" and ends with ">"

info: Bootstrap session started...
```

A side note is during development we have been using Leshan's demo server and had no problems. 

Is this something we're doing or is this a bug.

## Server Environment
  * AWS T2-Medium
  * Ubunu 20
  * ThingsBoard Version: 3.3.4

## Client Environment
Our device uses Zephyr along with it's built in LwM2M stack (v1.0 is set)

## Screenshots
**The error**
<img width="584" alt="image" src="https://user-images.githubusercontent.com/2155687/158716675-76226709-dcde-452b-bd56-8b94202b5ef2.png">

**Device Profile Transport Settings**
<img width="754" alt="image" src="https://user-images.githubusercontent.com/2155687/158717193-e761c218-143c-4085-bd86-630bec258011.png">

**Comment by motters** [comment]
@nickAS21 Is this something your branch fixes https://github.com/thingsboard/thingsboard/tree/lwm2m_fix_bug_bootstrap_tasks ?

**Comment by ricoheller** [comment]
Hi @motters, we are experiencing the behavior here.

However, our client uses [Anjay](https://github.com/AVSystem/Anjay) stack (LwM2M 1.0).
Did you find a workaround?

**PS:** It seems to work with [Wakaama demo](https://github.com/eclipse/wakaama) client.

**Comment by motters** [comment]
@ricoheller No, we turned off bootstrap for now. 

If i remember correctly it seemed to be something to do with the bootstrap requesting what objects are available, could be wrong though.

**Comment by nickAS21** [comment]
Yes, this is my branch.

I am the author this PR

Do you have questions for me?
