### ISSUE TITLE
[Question] How to set rule engine NOT to segragate input telemetry data in array into individual messages?

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#6279]
**Component**

 * Rule Engine

**Description**
I have a sensor that sends telemetry data in an array, but the rule engine input breaks it down into individual elements/messages. Is there a way to disable this behaviour?

For example, below telemetry data is segragated into 2 individual messages by the rule engine. The problem is that they will have the same timestamp down to millisecond, causing the save timeseries to fail to save one of them.

[{
    id: 1001,
    value: 10
}, {
    id: 1002,
    value: 20
}]
    
**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.3
 * Browser: Google Chrome

**Comment by JacksonBowe** [comment]
That payload on it's own will not make the rule engine send separate messages. If it does then it's because of a bug in your code.

Correct output:
`return { 'msg': [{'id':1001, 'value': 10}, {'id':1002, 'value':20}], 'metadata': metadata, 'msgType': msgType}`

What you're doing:
```
return [
    { "msg": {"id":1001, "value": 10}, "metadata": metadata, "msgType": msgType},  
    { "msg": {"id":1002, "value": 20}, "metadata": metadata, "msgType": msgType}
]
```

Notice where the array is

**Comment by FacelookHK** [comment]
This is the exact command that I used to send a telemetry data to ThingsBoard and I am using the default root rule-chain. You can see in the screenshot of the save timeseries node, the telemetry data is separated into 4 individual messages.

mosquitto_pub -d -q 1 -h 'localhost' -p 1883 -t 'v1/devices/me/telemetry' -u '00003' -m '[{"type":1,"id":1234,"status":0,"x":210,"y":308,"h":"1.1"},{"type":1,"id":5678,"status":0,"x":215,"y":286,"h":"1.5"},{"type":1,"id":1001,"status":0,"x":228,"y":42,"h":"1.9"},{"type":1,"id":1002,"status":0,"x":245,"y":324,"h":"3.4"}]'

![image](https://user-images.githubusercontent.com/8371565/158914768-3c2e9798-2eb4-4fd7-b710-1a0ad551bb2e.png)

**Comment by JacksonBowe** [comment]
What if you remove the quotes?
```
mosquitto_pub -d -q 1 -h 'localhost' -p 1883 -t 'v1/devices/me/telemetry' -u '00003' -m [{"type":1,"id":1234,"status":0,"x":210,"y":308,"h":"1.1"},{"type":1,"id":5678,"status":0,"x":215,"y":286,"h":"1.5"},{"type":1,"id":1001,"status":0,"x":228,"y":42,"h":"1.9"},{"type":1,"id":1002,"status":0,"x":245,"y":324,"h":"3.4"}]
```

Might work? I'm unsure.

**Comment by FacelookHK** [comment]
I am having same result with the payload sending from the actual/physical IoT device directly to ThingsBoard. I am only using mosquitto to simulate the issue on my PC, so I don't think it is a syntax issue.

**Comment by JacksonBowe** [comment]
What's the end result that you're trying to achieve? You say you're posting this as data
```json
{
    "id": 1001,
    "value": 10
}
```

But this isn't valid telemetry. What's it getting stored against? There's no `key` specified.
The docs use this as an example:
![image](https://user-images.githubusercontent.com/26427343/158916313-0f90d349-0d88-4851-b449-c191c1683550.png)

Here they clearly specify the `key` and the `value` assigned to it.

in your example what if you do this

```
mosquitto_pub -d -q 1 -h 'localhost' -p 1883 -t 'v1/devices/me/telemetry' -u '00003' -m '{"key": "ExampleKey", "value": [{"type":1,"id":1234,"status":0,"x":210,"y":308,"h":"1.1"},{"type":1,"id":5678,"status":0,"x":215,"y":286,"h":"1.5"},{"type":1,"id":1001,"status":0,"x":228,"y":42,"h":"1.9"},{"type":1,"id":1002,"status":0,"x":245,"y":324,"h":"3.4"}]}'
```

**Comment by FacelookHK** [comment]
So now I have a BLE gateway, it scans nearby BLE beacons and send the data to ThingsBoard via MQTT every 5 seconds. That is, in the payload, it contains an array containing the details of each BLE beacons. 

[{
    id: 1001,
    rssi: -50
}, {
    id: 1002,
    rssi: -60
}]

The problem is that ThingsBoard upon receiving this payload, it does not pass the whole thing to the rule engine's "INPUT", instead it separates the payload into 2 individual elements. 

What I expect is that ThingsBoard does not separate the payload into individual elements.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
