### ISSUE TITLE
SyntaxError in navigator's terminal

### ISSUE THREAD

**Issue by krzischp** [thingsboard/thingsboard#628]
I added a tab called piscari (I did the analogy with the other tabs). When I click on the tab, I get the expected html page (piscari.tpl.html). The problem is that I want to run a terminal command line in the javascript file (associated to this html script), but when doing like I do, I get:
SyntaxError: unexpected token: ':'
In the navigator terminal. I already checked many times if it was a syntax problem in my js script, but it seems not. I tried to rewrite the entire script as well, instead of copy-pasting and I still get the same error.

Here are my scripts:

piscari.tpl.html:

<body>

<form>
    <input id="text1" type="text" value="Entrez un texte" />
    <input type="submit" value="Submit !" />
    <input type="reset" value="Reset !" />
</form>
  <script src="bundle.js"></script>
</body>

piscari_main.js:

 console.log("In!!!!!!!!!");
const { spawn } = require('child_process');
const ls = spawn('ls', ['-lh', '/usr']);
console.log("Out!!!!!!!!!");

I referred to this links to write my script:
https://github.com/browserify/browserify
https://nodejs.org/api/child_process.html

I wrote the command line:
browserify main.js > bundle.js
to get bundle.js, in the same directory as piscari.tpl.html and piscari_main.js.
In the navigator's terminal, it seems it doesn't even run the piscari_main.js script because I can't see the console.log printing.

Thanks for your help in advance!

**Comment by Ultrazombie** [comment]
Hello @krzischp 
Is your problem still relevant on the latest ThingsBoard version?
