### ISSUE TITLE
[Question] filter datasource alias entities table widget

### ISSUE THREAD

**Issue by albtareng** [thingsboard/thingsboard#6280]
**Component**

 * Generic

**Description**
I have entities table widget with all device AND an asset "STREET A"
IF i create a relation query alias I can view in the widget ONLY DEVICE that have a relation with STREET A
I want other entities table widget that show ONLY DEVICE that NOT have a relation with STREET A
I thought that i can create a NEGATE relation query but isn't possible.,...
is there a way to filter datasource of widget  with an implementation on custom action OR editing on "self.onInit" OR "self.onDataUpdated" OR with filter or with other type of alias?

**Environment**
 * ThingsBoard: 3.3.3

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
