### ISSUE TITLE
[Bug] Uplink telemetry data in array format will be segragated into individual message with some messages not saved

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#6282]
**Describe the bug**
Uplink telemetry data in array format will be segragated into individual messages but having same timestamps in rule-engine causing some messages not saved (or overwritten).

Scenario:

I have a BLE gateway, it scans nearby BLE beacons and send the data to ThingsBoard via MQTT every n seconds. The uplink telemetry data is an array containing the data each BLE beacons.

[{
    deviceId: 1001,
    rssi: -50
}, {
    deviceId: 1002,
    rssi: -60
}]

Upon receipt of the telemetry data, Thingsboard does not pass the whole array as one message to the rule engine as Input, but instead it segragates the array and send 2 messages to the rule engine as Input.

{
    deviceId: 1001,
    rssi: -50
}

and

{
    deviceId: 1002,
    rssi: -60
}

Because the 2 messages come in parallel, they have the same timestamp and only 1 gets saved.

**Your Server Environment**
  * Docker deployment
  * ThingsBoard 3.3.3
  * Ubuntu 20.04

**Your Client Environment**
**Desktop (please complete the following information):**

* Ubuntu 20.04
* Google Chrome 
* Version 99

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. Upload telemetry data to ThingsBoard for a device with authorization token = 00003
mosquitto_pub -d -q 1 -h 'localhost' -p 1883 -t 'v1/devices/me/telemetry' -u '00003' -m '[{"type":1,"id":1234,"status":0,"x":210,"y":308,"h":"1.1"},{"type":1,"id":5678,"status":0,"x":215,"y":286,"h":"1.5"},{"type":1,"id":1001,"status":0,"x":228,"y":42,"h":"1.9"},{"type":1,"id":1002,"status":0,"x":245,"y":324,"h":"3.4"}]'
2. Create a dashboard with a timeseries widget to see the received data.

**Expected behavior**
1. All elements in the array should be saved successfully.

**Comment by mde2017** [comment]
Hi @FacelookHK,

I think this no bug, but correct behaviour, since both payloads have the same timestamp while arriving (it will be auto-generated by ThingsBoard if no ts field is present).

Try adding the timestamp information to each single payload like this:
`{"ts":1451649600512, "values":{"key1":"value1", "key2":"value2"}}`
https://thingsboard.io/docs/reference/mqtt-api/

In your case:

```
[{
        ts: 1647589013
        values: {
            deviceId: 1001,
            rssi: -50
        }
    }, {
        ts: 1647589014
        values: {
            deviceId: 1002,
            rssi: -60
        }
    }
]
```

**Comment by FacelookHK** [comment]
> Hi @FacelookHK,
> 
> I think this no bug, but correct behaviour, since both payloads have the same timestamp while arriving (it will be auto-generated by ThingsBoard if no ts field is present).
> 
> Try adding the timestamp information to each single payload like this: `{"ts":1451649600512, "values":{"key1":"value1", "key2":"value2"}}` https://thingsboard.io/docs/reference/mqtt-api/
> 
> In your case:
> 
> ```
> [{
>         ts: 1647589013
>         values: {
>             deviceId: 1001,
>             rssi: -50
>         }
>     }, {
>         ts: 1647589014
>         values: {
>             deviceId: 1002,
>             rssi: -60
>         }
>     }
> ]
> ```
> 
> Alternatively you could split the array into single payloads before sending to ThingsBoard. This would also lead to different timestamp values.

The problem is that the device sends the array payload to ThingsBoard and ThingsBoard fails to save the whole payload or some elements in the array of the payload. 

Splitting tha array or changing the format means I will have to set up a MQTT broker and a small application (bridge/proxy) in front of ThingsBoard.

Do you know which file in the source code should I be looking at if I want to modify this behaviour?

**Comment by FacelookHK** [comment]
Having additional MQTT broker and application sitting in front of ThingsBoard means addition HA/DR considerations. The rule engine should provide an option to disable this preprocessing of segragating the array into individual elements.

Do you know which file in the source code implements this behaviour?

**Comment by mde2017** [comment]
I don't know which source code is relevant for this behaviour.

Still I recommend the preprocessing way with additional MQTT broker, since it's probably less efffort to implemnt than changing the rulechain processing logic.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
