### ISSUE TITLE
[Question] Any API to get devices that were created by gateway MQTT API or TB IoT Gateway?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6283]
1. Is there any (HTTP) API to get a list of devices created by gateway API?
2. If no is it possible to implement? and where is a starting point in server code?

**Comment by devaskim** [comment]
I found the way by using relations API. Here is a CURL request:
```
curl -X 'POST' \
  'http://$TB_SERVER/api/relations' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Authorization: Bearer $ACCESS_TOKEN' \
  -d '{
  "filters": [
    {
      "relationType": "Created",
      "entityTypes": [
        "DEVICE"
      ]
    }
  ],
  "parameters": {
    "rootId": "$GATEWAY_ID",
    "rootType": "DEVICE",
    "direction": "FROM",
    "relationTypeGroup": "COMMON",
    "maxLevel": 0,
    "fetchLastLevelOnly": false
  }
}'
```

**Comment by mde2017** [comment]
Hi @devaskim,

you're using the right http endpoint for retrieving the related devices. In further requests you can get the device names by querying the endpoint _/api/device/{deviceId}_ 

There are also several REST clients e.g. for Python:
https://thingsboard.io/docs/reference/python-rest-client/
https://github.com/thingsboard/thingsboard-python-rest-client

**Comment by devaskim** [comment]
Thanks @mde2017 I will use that endpoint.
There is one more client in Dart, but it has been updated [slowly](https://github.com/thingsboard/dart_thingsboard_client/pull/5).
