### ISSUE TITLE
[Question] Dashboard for browsing received timeseries data - Timeline browsing

### ISSUE THREAD

**Issue by DanyHubGit** [thingsboard/thingsboard#6288]
**Component**

 * UI

**Description**
I want to create a dashboard to browse the data that I receive in realtime (so as timeseries) by one vehicle.
I have seen that in the sample use case "Fleet Tracking", there is a widget that show the trip made by the vehicle. 
But It isn't sufficient, because I haven't the possibility to see other data (not only GPS coord) in other widget (not in the map).
I would know id exist a timeline widget with with I can "scroll" in the time, and when I stop the mouse on this "timeline", the data of timeseries are loaded (in relation to this specif time ).
I hope to have explained my question.

Thanks in advance

**Environment**
 * OS: Windows 10
 * ThingsBoard: CE 3.3.3
 * Browser: Chrome last version

**Comment by mykhailokornieiev** [comment]
Hi
If this is still relevant, there is no widget in ThingsBoard that could simultaneously display the location of the device on the map for a certain period of time and all telemetry. For this, you will need to use two widgets:
new trip animation - geolocation at the required time.
New Timeseries Table - any telemetry for the required time, but there is no way to select the moment of time with the mouse.
Best regards,
Mykhailo

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
