### ISSUE TITLE
[Question] Thingsboard pages stuck on loading

### ISSUE THREAD

**Issue by FrancescoMenga** [thingsboard/thingsboard#6293]
**Component**

 * Generic

**Description**
Hi, I just upgraded my thingsboard from version 3.2.2 to 3.3.2, because I was adviced to do it instead of upgrading to the latest version. The upgrade ran smoothly and there wasn't any problems. Now that I checked the server status after weekend I noticed that both "mytbpe" and "postgres" are up and running, but i can't access any page, since it keeps loading it but never finish loading anything.
Since the service is up and running for more than 2 days i can't understand what's the problem. I also checked logs but errors are not on the service but internal errors, like RuleChain failure on executing etc.
What could I do? A solution would be awesome since I need to update TB as soon as possible.

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.3.2
 * Browser: Firefox latest

**Comment by JacksonBowe** [comment]
Can you check the web console for errors? F12 on chrome

**Comment by FrancescoMenga** [comment]
@JacksonBowe The problem seems to be this:
![immagine](https://user-images.githubusercontent.com/95043931/159675382-ed8077ed-5836-4fb7-a4dd-134be97a133b.png)

TB was installed using docker so i don't know how to access files to see if I can edit whitelabelling.json

**Comment by FrancescoMenga** [comment]
@JacksonBowe The problem seems to be this:
![Cattura](https://user-images.githubusercontent.com/95043931/159675619-14e2e8dd-5ed6-4233-b938-98d012c150d7.PNG)

**Comment by JacksonBowe** [comment]
Okay pretty destructive move here. 
Back up your database now.


In your postgress db there will be a tenant/customer attribe called white_label_params. Copy the JSON out and put into a json parser to check for errors. 

If it looks fine delete the while label params and see if it works.

**Comment by FrancescoMenga** [comment]
The problem was using a newer version of TB after updating: used docker-compose.yml with TB version 3.3.2 while there wasn't a downloaded container with that version.
