### ISSUE TITLE
Is it possible to pull telemetry data from Thingsboard Cloud?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6296]
**Component**

 * Generic

**Description**
Can I pull telemtery data down to my local PC from Thingsboard Cloud?

**Environment**

 * OS:  Windows
 * ThingsBoard: Cloud
 * Browser: Chrome

**Comment by JacksonBowe** [comment]
Yes, you will need to use the API. Search "Thingsboard Cloud Swagger"

**Comment by OzyOzk** [comment]
I found that you can do this through the dashboard itself. TB will export data as a csv, at least on pro versions.
