### ISSUE TITLE
[Feature Request] Sensors value categorization from the dashboard.

### ISSUE THREAD

**Issue by santobedi** [thingsboard/thingsboard#6297]
**Describe the solution you'd like**
Consider my sensor as a smart meter. My ML routine detects _N_ electrical appliances (I name them A_1, A_2,.............., and A_N) connected to the smart meter. I want the customer to be able to rename those appliances with their actual name (for example kettle, heater, fan, etc.) from the dashboard. Note that my ML routine detects electrical load and sends the information to the Thingsboard. I name them in the rule chain based on their values. How can the customer categorize these electrical loads from the dashboard such that the dashboard will display kettle, heater, fan, etc instead of A_1, A_2, and so on? Can the _Input widgets_ do it?

**Describe alternatives you've considered**
If there would be a kind of 'communication' between the rule chain and the dashboard, I think it could be possible.

**Comment by mde2017** [comment]
Hi @santobedi,

you could use _entityLabels_ for your customers, where Devicename stays like A_1, A_2 ... A_N, but the label can be different. Also the label doesn't have to be unique (Devicename has to be). 

In the dashboard you could use _Device Admin Table (Entity Admin Widgets)_ with default Custom Actions to change labels (Edit button):

![image](https://user-images.githubusercontent.com/25298332/159299066-bd3bb438-f40c-4058-ab51-6075b7825911.png)

To display the label in charts e.g. Line charts, just add the _${entityLabel}_ placeholder:
![image](https://user-images.githubusercontent.com/25298332/159299617-0a828d9b-9942-45a6-8ea9-b2f98742edf3.png)

![image](https://user-images.githubusercontent.com/25298332/159299748-07a1520c-d90d-4849-8ec2-c107a4530c0c.png)

**Comment by santobedi** [comment]
Hello @mde2017,

Thanks for the prompt response. In my architecture, the electrical appliances (A_1, A_2,......., and A_N) are telemetry of device 'smart meter'. I'll try to convert these telemetries into devices (editing MQTT config file) and follow your approach.
