### ISSUE TITLE
[Question] Thingboard client entity relation json parse error

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#6299]
ı have error on relation library with parsing relation model, I give required parameters as a  EntityRelation entityRelation = EntityRelation(from: entityId,to: entityIdX,type: type,typeGroup: RelationTypeGroup.COMMON,additionalInfo:{});
but ı send to saveRelation . But I saw json parse as

EntityRelation{from: DeviceId {id: 19ff54d0-992b-11ec-bc20-c1f08d3adac0}, to: DeviceId {id: 18de6990-992d-11ec-bc20-c1f08d3adac0

brackets do not exist and other types and group parameters do not exist.
this text is an error message text

` [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ThingsboardError: message: [type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast], errorCode: 2, status: null
E/flutter (11427): #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:86:18)
E/flutter (11427): #1      ThingsboardClient.post (package:thingsboard_client/src/thingsboard_client_base.dart:211:13)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #2      EntityRelationService.saveRelation (package:thingsboard_client/src/service/entity_relation_service.dart:18:20)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #3      _ScanSensorQrViewModelBase.checkPairing (package:molisens/view/modules/scan_sensor_qr/viewmodel/scan_sensor_qr_view_model.dart:67:49)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #4      _ScanSensorQRViewState.showSuccessAlertDialog.<anonymous closure> (package:molisens/view/modules/scan_sensor_qr/view/scan_sensor_qr_view.dart:260:9)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427):
E/flutter (11427): #0      ThingsboardClient.post (package:thingsboard_client/src/thingsboard_client_base.dart:211:7)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #1      EntityRelationService.saveRelation (package:thingsboard_client/src/service/entity_relation_service.dart:18:20)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #2      _ScanSensorQrViewModelBase.checkPairing (package:molisens/view/modules/scan_sensor_qr/viewmodel/scan_sensor_qr_view_model.dart:67:49)
E/flutter (11427): <asynchronous suspension>
E/flutter (11427): #3      _ScanSensorQRViewState.showSuccessAlertDialog.<anonymous closure> (package:molisens/view/modules/scan_sensor_qr/view/scan_sensor_qr_view.dart:260:9)`

**Comment by vvlladd28** [comment]
HI,
Thank you for your report. Thanks, @devaskim, for PR. Coming soon, release a new version Dart client, including this fix.
