### ISSUE TITLE
How to contribute - Developers guide

### ISSUE THREAD

**Issue by nikil511** [thingsboard/thingsboard#63]
Its good you have _building from source_ instructions, but that's not enough to help developers understand whats under the hood. Therefore a guide on setting up a recommended development environment will greatly boost contributions but more importantly help devs pick up your work/approach and also avoid asking your support for simple stuff. 

Ideally I would like instructions for: IDE setup, Building, Running and Debugging for application/core but also UI front-end. I assume the latter will have some additional steps due to the use of node.js

I believe you will attract more people/contributions this way, than just adding more features to the already very rich platform you have created! (at least that was my experience with OpenHAB)

**Comment by ashvayka** [comment]
Thank you for your feedback! We are now actively working on new release. After release we will switch to doc improvements.

**Comment by darrenaanderson** [comment]
thats great news, as i'm struggling setting up an fully working environment - i've put it down to being a little rusty, so a little more detail would be very welcome.

**Comment by nghib** [comment]
+1

**Comment by toti1212** [comment]
+1

**Comment by nmenoni** [comment]
+1

**Comment by Postgre** [comment]
+1

**Comment by victorfu** [comment]
+1

**Comment by ashvayka** [comment]
Hi Guys,
We have prepared some of the guides:
https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/
https://thingsboard.io/docs/user-guide/contribution/extensions-development/
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
I am going to close this if there is no objections. Please add comments if something is missing.
