### ISSUE TITLE
How does the “retrys” parameter of server-side RPC persistence work?

### ISSUE THREAD

**Issue by TangYuFan** [thingsboard/thingsboard#6300]
Server-side RPC structure
The body of server-side RPC request consists of multiple fields:

method - mandatory, name of the method to distinct the RPC calls. For example, “getCurrentTime” or “getWeatherForecast”. The value of the parameter is a string.
params - mandatory, parameters used for processing of the request. The value is a JSON. Leave empty JSON “{}” if no parameters needed.
timeout - optional, value of the processing timeout in milliseconds. The default value is 10000 (10 seconds). The minimum value is 5000 (5 seconds).
expirationTime - optional, value of the epoch time (in milliseconds, UTC timezone). Overrides timeout if present.
persistent - optional, see [persistent] vs [lightweight] RPC. The default value is “false”.
retries - optional, defines how many times persistent RPC will be re-sent in case of failures on the network and/or device side.
additionalInfo - optional, defines metadata for the persistent RPC that will be added to the [persistent RPC events].

**Comment by TangYuFan** [comment]
I checked the source code and couldn't find the code related to persistent RPC retry sending。
I can only find the code to determine whether the number of retries exceeds the limit。
code：
class DeviceActorMessageProcessor extends AbstractContextAwareMsgProcessor {
   private void processRpcResponseStatus(TbActorCtx context, SessionInfoProto sessionInfo, ToDeviceRpcResponseStatusMsg responseMsg) {
     //.....
    if (maxRpcRetries <= md.getRetries()) {
                    toDeviceRpcPendingMap.remove(responseMsg.getRequestId());
                    status = RpcStatus.FAILED;
                } else {
                    md.setRetries(md.getRetries() + 1);
                }
}
}

**Comment by TangYuFan** [comment]
There is no code to resend RPC in transport：
code：
public class MqttTransportHandler extends ChannelInboundHandlerAdapter implements GenericFutureListener<Future<? super Void>>, SessionMsgListener {

   public void onToDeviceRpcRequest(UUID sessionId, TransportProtos.ToDeviceRpcRequestMsg rpcRequest) {
cf.addListener(result -> {
                    if (result.cause() == null) {
                        if (!isAckExpected(payload)) {
                            transportService.process(deviceSessionCtx.getSessionInfo(), rpcRequest, RpcStatus.DELIVERED, TransportServiceCallback.EMPTY);
                        }
                        else if (rpcRequest.getPersisted()) {
                            transportService.process(deviceSessionCtx.getSessionInfo(), rpcRequest, RpcStatus.SENT, TransportServiceCallback.EMPTY);
                        }
                    } else {
                        // TODO: send error
                    }
                });
   }
}

**Comment by Ultrazombie** [comment]
Closed due to inactivity
