### ISSUE TITLE
[Bug]Build from source is Failled on folder Ui-ngx

### ISSUE THREAD

**Issue by VictorHSalvador** [thingsboard/thingsboard#6302]
When I try to build the files like the documents suggested from souces, all looks good, but when the folder ui-ngx is the target, it failed on the three lasts packaged on the Yarn Install step. I discovered that this three packages are:

"flot": "git://github.com/thingsboard/flot.git#0.9-work",
“flot.curvedlines": "git://github.com/MichaelZinsmaier/CurvedLines.git#master", 
"ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#release/1.0.0".

Looking on flot repository, I discovered that this one dont have more support to build, maybe it is the problem and the others packages are on the same situation.

I removed it from package.json on ui-ngx folde. Its worked to pass the yarn install stage, but I got stuck on next step "yarn build". Some one else has that same problem? The Yarn Build stage is showing like a lot of package (like angular packages) missing. I'm using an Oracle VM, so I'm trying a lot of ways to build, using other versions of thingsboard, other versions of npm, yarn, java and nodejs, but this problem still happening. Once appeared me that the Yarn build stage problem was the file marked.js missing, but I found this one on another folder, and I moved it to pointed directory, but not worked.

Now I'm using the lasted version of thingsboard, yarn, nodejs and npm. My virtual Machine OS is an Ubuntu 20.04.4 LTS.

**Comment by vvlladd28** [comment]
HI @VictorHSalvador,
This problem is fixed in the master branch, and we are had add [fix](https://github.com/thingsboard/thingsboard/pull/6298).

**Comment by emrekardaslar** [comment]
* In my case it is fixed by changing git:// to https://
