### ISSUE TITLE
Tenant attributes for device profile alarm

### ISSUE THREAD

**Issue by Kevinowitsch** [thingsboard/thingsboard#6303]
**Component**

 * Generic

**Description**

I am using Customer Attributes to calculate fill levels of containers and trigger alarms when surpassing a threshold. In the alarm rules you can specify a dynamic source an select "inherit from owner". 

**I was wondering where i can set those Attributes for "us" as tenant?**
So if values for customers are undefined it inherits it from "us". And also to trigger the alarm from devices that are not assigned to any customer.

And what happens if you define a default **and** a dynamic value. Does the dynamic value overwrite the default if set?

![TB1](https://user-images.githubusercontent.com/83923282/159488952-22f5519f-54a6-4eb7-a66b-02311a35dde5.PNG)
![TB2](https://user-images.githubusercontent.com/83923282/159488958-e1acea10-c676-489a-9465-05b6430b3913.PNG)

**Environment**

 * OS:  Win 10
 * ThingsBoard: PE 3.3.2
 * Browser: Firefox

**Comment by mde2017** [comment]
Hi @Kevinowitsch

this depends on the ownership of the device/asset. It can have either tenant directly as owner or the customer. 
If it belongs to the customer you can set the attributes via customer hiearchy (as seen in your screenshot).

If you would like to inherit attributes directly from the tenant itself, you can only do so via System Administrator authority. Just log in as sysadim and add the attributes to your tenant.

Unfortunately, I can't tell what's the behaviour if both default and inherited values are defined. Normally I implement alarm logic directly via rulechains, which are a lot more flexible than via device profile.

**Comment by Kevinowitsch** [comment]
Ok thanks. That solves my problem partially, but I think I'll fix the case with my own devices by checking for those in the rule chain

**Comment by JacksonBowe** [comment]
@mde2017 @Kevinowitsch I'd double check that behaviour. From memory the 'Inherit from owner' is exclusively between Tenant and Customer or Customer and sub-Customer.

What should happen here is that the filter is going to look for `default_fill_level_alarm_threshold` first on the Customer, and if it can't find it, it will try the Customers' owner (ie the Tenant in your case).

From the docs:
_Select a value: current device, current customer or current tenant. And specify the attribute from which the alarm threshold value will be taken. You may optionally check "Inherit from owner". Inheritance allows to take the threshold value from customer if it is not set on the device level. If the attribute value is not set on both device and customer levels, rule will take the value from the tenant attributes_

Source:
https://thingsboard.io/docs/user-guide/device-profiles/
ctrl+f > "Inherit"
