### ISSUE TITLE
[Bug] Marker images not showing correctly on Safari

### ISSUE THREAD

**Issue by NicoWii4** [thingsboard/thingsboard#6306]
**Describe the bug**
Marker images not showing correctly on Safari. There is a mix between my marker images and default marker.

**Your Server Environment**

* own setup
    * Cloud docker deployment with official Thingsboard PE images
    * ThingsBoard Version 3.3.3PE
    * Docker host is debian buster, Docker version 20.10.12

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: iOS
* Browser Safari
* Version 15.4

**Expected behavior**
I actually would like to see my maker images displayed the same way as on Chrome or Firefox browser.

[**Screenshots**]
![image](https://user-images.githubusercontent.com/80882254/159476545-7fd088ef-4810-46f6-8fb6-1b9e1386cf02.png)

**Additional context**
I'm afraid that I noticed the same problem on different map widget (map, imageMap, etc..).

Best regards

**Comment by vvlladd28** [comment]
Hi @NicoWii4,
Thank you for your report. But this bug [webkit](https://bugs.webkit.org/show_bug.cgi?id=238589) we cannot fix in the current version, but we can recommend a workaround which is to convert SVG icons to PNG.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
