### ISSUE TITLE
tenant log

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#631]
Is there anyway to see tenant log ?
shall we see which tenant used thingsboard in which time?

**Comment by ashvayka** [comment]
This is not available yet.

**Comment by gopirathnamt** [comment]
ashvayka i have several doubts in thingsboard and i want to contribute for thingsboards.
All i need is your support ,can u help me to solve my doubt?

**Comment by volodymyr-babak** [comment]
Greetings @gopirathnamt 
A long time passed... do you still have some doubts? If yes, please provide them, in another case I'm going to close this ticket.
Thanks.
