### ISSUE TITLE
[Bug] When using timescaledb, when the data compression policy is enabled for the "ts_kv" hypertable, thingsboard fails to write historical data

### ISSUE THREAD

**Issue by Doyle-net** [thingsboard/thingsboard#6312]
**Describe the bug**
When using timescaledb, after enabling the data compression strategy for the "ts_kv" super table, the thingsboard will appear ERROR, causing some historical data to fail to be inserted, especially the data of the thingsboard itself, such as "transportDataPointsCount"

**Your Server Environment**
* own setup
   * local infrastructure or docker deployment
   * ThingsBoard Version .3.3.4.1
   * timescaledb Version  2.6.0
* Connectivity
  * MQTT  
  * Gateway
* ERROR
`2022-03-24 07:31:47,401 [sql-queue-2-ts timescale-7-thread-1] ERROR o.s.t.i.TransactionInterceptor - Application exception overridden by rollback exception
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO ts_kv (entity_id, key, ts, bool_v, str_v, long_v, dbl_v, json_v) VALUES(?, ?, ?, ?, ?, ?, ?, cast(? AS json)) ON CONFLICT (entity_id, key, ts) DO UPDATE SET bool_v = ?, str_v = ?, long_v = ?, dbl_v = ?, json_v = cast(? AS json);]; SQL state [0A000]; error code [0]; Batch entry 1 INSERT INTO ts_kv (entity_id, key, ts, bool_v, str_v, long_v, dbl_v, json_v) VALUES('572aa7d0-ab1c-11ec-b97f-99b8716559fe'::uuid, 26, 1646092800000, NULL, NULL, 957831, NULL, cast(NULL AS json)) ON CONFLICT (entity_id, key, ts) DO UPDATE SET bool_v = NULL, str_v = NULL, long_v = 957831, dbl_v = NULL, json_v = cast(NULL AS json) was aborted: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks  Call getNextException to see other errors in the batch.; nested exception is java.sql.BatchUpdateException: Batch entry 1 INSERT INTO ts_kv (entity_id, key, ts, bool_v, str_v, long_v, dbl_v, json_v) VALUES('572aa7d0-ab1c-11ec-b97f-99b8716559fe'::uuid, 26, 1646092800000, NULL, NULL, 957831, NULL, cast(NULL AS json)) ON CONFLICT (entity_id, key, ts) DO UPDATE SET bool_v = NULL, str_v = NULL, long_v = 957831, dbl_v = NULL, json_v = cast(NULL AS json) was aborted: ERROR: insert with ON CONFLICT or RETURNING clause is not supported on compressed chunks  Call getNextException to see other errors in the batch.`
* Timescaledb About compression
[https://docs.timescale.com/api/latest/compression/#compression](url)
* Timescaledb configure
Compress data older than seven days

**Comment by fraenku** [comment]
Any progress on this?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.  If this question is still relevant to you, feel free to open a new ticket with full description of your request.
