### ISSUE TITLE
[Question] No password recived for new customer

### ISSUE THREAD

**Issue by tmsio** [thingsboard/thingsboard#6318]
* Generic

**Description**
In Cloud UI, when i create a new customer using his mail, no link was for generate new password was sent.
Mail configuration it s good also mail test.
Can You Help me?

Regards

**Environment**
 * ThingsBoard: Cloud
![mail configuration](https://user-images.githubusercontent.com/15527050/160073688-940cd8f2-1159-4ff1-ba33-5d795b39da64.PNG)
![add-customer](https://user-images.githubusercontent.com/15527050/160074063-b6728c3e-7869-48fd-b0f6-aa9d2e076b8f.PNG)

 * Browser: Chrome 99.0.4844.82 (Build ufficiale) (a 64 bit)

**Comment by lucasKapf** [comment]
Hello, I had the same problem.
Check the spam folder, the mail should be in it.

**Comment by devaskim** [comment]
If your SMTP port is 465, try switching to SMTPS instead of SMTP.

**Comment by tmsio** [comment]
Same issue on SMTPS, test mail it good, but no mail arrive to new customers.
:(

**Comment by tmsio** [comment]
Checked also in spam folder. :(

**Comment by tmsio** [comment]
Solve, the correct way is create, enter in "Customer Users" and after create new user inside this group.
Thank You
