### ISSUE TITLE
[Question] How to add external JS library in Script Rule Node

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6319]
**Component**
 * Rule Engine

**Description**
I want to use JS interpolation [library](http://borischumichev.github.io/everpolate/) to calculate value based on incoming telemetry data and calibration table that I stored in server attributes. Is it possible to include this library?

**Comment by devaskim** [comment]
Finally I copy several functions from this library and, insert into the script window of the Script Rule Node and call them before _return_ statement.

**Comment by Cmonkz** [comment]
Hope you still check this. Can you tell me how'd you do it?

**Comment by devaskim** [comment]
Hi @Cmonkz 
What library do you need?
In my case as I mentioned above I copied thirdparty code in transform function, something like this (_simplified version_):
```
// thirdparty function
function linearInterpolation(x, x0, y0, x1, y1) {
    var a = (y1 - y0) / (x1 - x0);
    var b = -a * x0 + y0;
    return a * x + b;
}

msg['MY_VAR'] = linearInterpolation(2, 0, 0, 4, 4);
return {
    msg: msg,
    metadata: metadata,
    msgType: msgType
};
```
