### ISSUE TITLE
JSON reply values from telemetry plugin are always string with double quotes

### ISSUE THREAD

**Issue by saligaris** [thingsboard/thingsboard#633]
Sending double value from telemetry plugin ex. {"temperature":12.2}
Reply is {
    "temperature": [
        {
            "ts": 1520422868210,
            "value": **"11.2"**
        }
    ]
}
![telemetry](https://user-images.githubusercontent.com/37144396/37091090-8783a930-220f-11e8-8e52-0d546d8f27f2.png)
are double quotes normal ?

**Comment by ashvayka** [comment]
yes, this is always like this. We just wanted to make this as simple as possible. This will not change in the nearest future because it will break the API.
