### ISSUE TITLE
[Question] CSS Style of MarkDown/HTML Card

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#6333]
* UI

**Description**
What is the syntax to add CSS style to the HTML Card?
It does not behave as an HTML input.
How do I link CSS '**.body**' to the 'HTML' part or what name should I use?
<img width="416" alt="Card_HTML_CSS" src="https://user-images.githubusercontent.com/49442805/160580785-4a3a20b2-7e9e-497c-8676-6528603ddd12.png">

```
.body{
  font-size: 20;
  text-align: center;
  vertical-align: middle;
}
```

**Environment**

 * OS:  Ubuntu 20.04 LTS
 * ThingsBoard: 3.3.3

**Comment by KenSense** [comment]
This also doesn't format anything:
<img width="556" alt="Card_HTML_CSS2" src="https://user-images.githubusercontent.com/49442805/161033226-ac9ee18a-be35-4948-9396-1d2f1aa6f4a5.png">

**Comment by KenSense** [comment]
I changed it to a HTML value card widget, that works.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
