### ISSUE TITLE
[Bug] Rule nodes: the "Test script function" window is not adapted to screen reduction

### ISSUE THREAD

**Issue by pinkevmladchy** [thingsboard/thingsboard#6336]
**Describe the bug**
The "Test script function" window is not adapted to screen reduction

**To Reproduce**

1. Go to the rule chain
2. Select the “script” node
3. Click on the “Test filter function” 
4. Reduce the screen

**Expected behavior**
Window must be adaptive for a screen

**Screenshots**
![image-20220316-121906](https://user-images.githubusercontent.com/49400214/160633828-7f437e81-216e-4b71-9f6f-f020a27bf8de.png)
![image-20220316-122007](https://user-images.githubusercontent.com/49400214/160633592-0677c8b6-36ae-4e09-9f1e-716934485eba.png)
![image-20220316-122328](https://user-images.githubusercontent.com/49400214/160633608-6af8f213-980e-4a02-90af-963aa0fb02f6.png)

**Comment by vvlladd28** [comment]
This problem in screen width 600-959px
