### ISSUE TITLE
How to publish telemetry data using custom widget?

### ISSUE THREAD

**Issue by akashtalole** [thingsboard/thingsboard#6337]
**Component**

 * UI
 * Generic

**Description**
I want to publish data using thingsboard custom widget. How I can achive it?

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: v3.3.3
 * Browser: Chrome

**Comment by Civilduino** [comment]
One possibility is to add a costume widget with one of [these](https://gist.github.com/Terny22) javascript in it :)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
