### ISSUE TITLE
[Question] Multiple entity on HTML Value Card

### ISSUE THREAD

**Issue by B-DAGBERT** [thingsboard/thingsboard#6338]
**Component**

 * UI

**Description**
Hi, I'm trying to print on a HTML Value Card an attribute of several entity (asset name). But I only can print the asset name of the first entity resolved by the alias. Is there a way to achieve that ? I've tried to create a new HTML Value Card i a widget bundle and modify the singleEntity to false in the typeParameters but I only can print the asset nam of the first entity resolved by my alias. I've also tried to import the HTML/Markdown card from TB 3.2.2 but i'm using TB 3.0.1 and it's not working. Thanks for yours answers !

**Environment**
 * OS:  Ubuntu 18.04.4 LTS
 * ThingsBoard: TB 3.0.1PE
 * Browser: Google Chrome 100.0.4896.60

**Comment by Civilduino** [comment]
Could you upload some pictures as example of what you are trying to achieve? Why not use an Entity Table widget instead?

**Comment by B-DAGBERT** [comment]
Hi,

First, thanks for your answer.

I'm trying to do something like this :

![Sans titre](https://user-images.githubusercontent.com/44493549/161728572-ca4bcad8-2cf6-42f9-9394-9fd92b82bfc7.png)
 
Where ASSET A and D are a certain type of asset and B, C and E, F another type of asset related to the first one.

 So I need to have two datasources who can compute several entities each, that's why i'm not using an Entity Table widget. 

I'm always trying to develop a widget based on the documentation but I can't make it work.

**Comment by Civilduino** [comment]
So you are basically trying to do the same as Entities Hierarchy widget.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/27728926/161765753-3318166a-264c-4158-bacb-4883b5f60e7c.png">

[Here](https://github.com/thingsboard/thingsboard/tree/v3.3.4/ui-ngx/src/assets/help/en_US/widget) are good examples of how you could you use the API for creating a costume widget, but not exactly as you want to do.
Under the [widgetContext](https://github.com/thingsboard/thingsboard/blob/v3.3.4/ui-ngx/src/app/modules/home/models/widget-component.models.ts) you have different services you can use to retrieve the assets and their relations, e.g. API for  assetService: [AssetService](https://github.com/thingsboard/thingsboard/blob/v3.3.4/ui-ngx/src/app/core/http/asset.service.ts). Play a bit with the API, e.g.print out the results in the web browser console to see how the work.

**Comment by B-DAGBERT** [comment]
Yes, approximatly.

But, this widget is not available in 3.0.1 .. 

Anyways, I'm gonna try again to understand how widget development is working. Thanks again

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
