### ISSUE TITLE
Thingsboard Security

### ISSUE THREAD

**Issue by gaurav20-07** [thingsboard/thingsboard#634]
Hi,

I am planning to use thingsboard for IoT as part of bigger setup. I am using keycloak to take care of the security. Is there a way I can get rid of the thingsboard security part and use the keycloak JWT to access thingsboard as a back end service. Any help is welcome.

**Comment by adityaba** [comment]
@gaurav20-07 Did you find any workaround?

Thanks,
--
Aditya Barve

**Comment by spogher** [comment]
Hi, I am also facing the same issue as i would to use Thingsboard but delegate authentication and security to keycloak. Is there any update on the subject since 2018?

Any advice or workaround is welcome.

**Comment by Karabiy** [comment]
for now the ThingsBoard does have the OAuth functionality, which allows to use different providers. 
you can refer to this link regarding those: https://thingsboard.io/docs/user-guide/oauth-2-support/ 
it seems that the keycloak does provide those functionality

**Comment by gtsere** [comment]
Has anyone find out any workaround?

**Comment by YousefAltShift** [comment]
Has anyone find out any workaround? +1

**Comment by volodymyr-babak** [comment]
ThingsBoard supports OAuth2 method of authentication.
https://thingsboard.io/docs/user-guide/oauth-2-support/
You can easily add Keycloak as OAuth2 provider to ThingsBoard platform configuration and then your users are going to be redirected to the Keycloak login webpage, once they click 'Login with Keyclock' button:
![image](https://user-images.githubusercontent.com/3466101/152804938-4a9e2e0c-c9a2-4b89-8d22-7f7c60338359.png)

Although Keycloak guide is not available at the moment on thinsgboard.io website, it should be possible to use this provider. 

But important note - you CAN NOT use Keycloak JWT token to access ThinsgBoard resources. 
Your users are going to navigate to Keycloak login websites, do authentication there, Keycloak will redirect them back to the ThingsBoard platform, and as the last step - ThingsBoard is going to create its custom JWT token and users will use ThingsBoard JWT token to access ThingsBoard resources.

**Comment by Aviijit** [comment]
can anyone please share the steps or documents to integrate Keycloak with Thingsboard

**Comment by Aviijit** [comment]
> ThingsBoard supports OAuth2 method of authentication. https://thingsboard.io/docs/user-guide/oauth-2-support/ You can easily add Keycloak as OAuth2 provider to ThingsBoard platform configuration and then your users are going to be redirected to the Keycloak login webpage, once they click 'Login with Keyclock' button: ![image](https://user-images.githubusercontent.com/3466101/152804938-4a9e2e0c-c9a2-4b89-8d22-7f7c60338359.png)
> 
> Although Keycloak guide is not available at the moment on thinsgboard.io website, it should be possible to use this provider.
> 
> But important note - you CAN NOT use Keycloak JWT token to access ThinsgBoard resources. Your users are going to navigate to Keycloak login websites, do authentication there, Keycloak will redirect them back to the ThingsBoard platform, and as the last step - ThingsBoard is going to create its custom JWT token and users will use ThingsBoard JWT token to access ThingsBoard resources.

@volodymyr-babak could you please share the steps to integrate keycloak with thingsboard.
Thanks in advance

**Comment by Aviijit** [comment]
please share the steps
