### ISSUE TITLE
[Feature Request] Enhance REST API Call Request method PATCH

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#6342]
In the rule chain I can add the REST API Call. Request methods are GET, POST, PUT, DELETE.
I need PATCH as method also. Please add this method.

**Comment by Backdraft007** [comment]
For information my workaround:
I added in the rest api call the following header:
"X-HTTP-Method-Override" = "PATCH" and use POST as method. For me it works like a charm.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
