### ISSUE TITLE
[Question] How to set timer or waiting in Rule Chain without delay node

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#6343]
![image](https://user-images.githubusercontent.com/12267053/160861497-5bdd410e-6da0-47d2-a95e-4b38cd52a68b.png)

case: 
When i send api request, that request received and status in queued on that service. 
I need to send api again **few seconds later** to capture status, it still in queue or already executed.

how to do it without delay, due delay-node being deprecated?

**Comment by mgogh** [comment]
Hi,

Any update about this question ? Did you find a solution ?

Regards,

**Comment by evanderbird** [comment]
HI there... I still dont find solution for this without _delay node_

**Comment by GabrielMarconS** [comment]
Hey,

Unfortunately still no answer.

Best regards,
<https://www.aurotecnologia.com.br/>


Em qua., 28 de set. de 2022 às 05:37, Maxime Gourlay <
***@***.***> escreveu:

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.

**Comment by evanderbird** [comment]
Hmm, seems no other choice, I will keep using delay-node :)

**Comment by sotpotatis** [comment]
I agree with @evanderbird, I see no other choice than to use delay-node. The message generator does not work for my scenario where I want TB to do things related to the *specific device that sent the original telemetry* 30 minutes after the telemetry was received,

Is it possible that someone involved with ThingsBoard can explain *why* this is deprecated and if there are any plans to remove it?
