### ISSUE TITLE
Widget Dsplay in Mobile 

### ISSUE THREAD

**Issue by vimalgupta** [thingsboard/thingsboard#6344]
**Component**
 * UI

**Description**
Is there a way to get the widget display in mobile side by side, I means to say 2 widget in single row. currently all widgets are expending to fill complete width in mobile app which is creating lot of white space and i would like to have 2 widget in one row.

**Environment**
 * OS:  ubuntu 18.04 / Android
 * ThingsBoard: 3.2

**Comment by hallard** [comment]
Agree, got the same even with 1x1 size on grid, they never get side by side, for just html card with one value should be ideal

**Comment by ssakharova** [comment]
Hello @vimalgupta, @hallard, @shayMZ,

Currently, there is no way to display two widgets side by side in a single row in mobile mode.
Therefore, I passed all the provided information to our developers and created an internal prod ticket for them to decide on its necessity and possible implementation in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
