### ISSUE TITLE
Any way to edit the bundled widgets without port/remaking?

### ISSUE THREAD

**Issue by ParisMolver** [thingsboard/thingsboard#6345]
Hi, looking at the RPC dial code on github, [available here](https://github.com/thingsboard/thingsboard/tree/da4c74287216fc6962c74f084c2eedebf06e1a64/ui-ngx/src/app/modules/home/components/widget/lib/rpc) you can see every single line of code used to create the dial. You cannot copy the CSS, JS, HTML into a new widget and get it to work though.

My largest complaint is that in TB, **you cannot edit the dial widget**. The java is simply three functions with nothing in them.

So if you as an end user want to change the color of the widget it costs about $250 USD (a recent quote) to edit 1 line of code **const levelColors = ['#19ff4b', '#ffff19', '#ff3232'];**.

As a turn key solution, this doesn't seem very turn key. There has already been so much hard work and development being poured into this project but still simple things such as editing a widget color require that same work to be re-expended to do simple edits.

I've googled and looked at all 4 pages of results on the subject. Most of the documentation is provided by thingsboard but they only cover how to create widgets from scratch not on how to edit the bundled widgets. I understand that there is a lot of power behind creating anything you want to find any need and it's a topic that needs discussion but as a sole developer, the constraint is that I simply cannot do hardware, embedded development, server deployment and now JSS, HTML, CSS ontop of learning thingsboard. It's just too many things and I am stretched too far. Any dollar I spend on paying for thingsboard widgets off fiverr are dollars that I can't use towards funding the project. There is also a big difference between building a widget from the ground up and editing a template to suit your needs. Why do we have one option and not the other?

So the question I have is, is there a JSS / CSS / HTML copy and paste code I can use to have an editable dial widget? If not, where would I post my contribution to the community? I can see it's available in most of it's glory in the github but I can't just copy and paste it into a new widget and have an exact copy of the dial widget.

**Comment by ParisMolver** [comment]
![image](https://user-images.githubusercontent.com/91441120/160958172-60dfb0f7-4250-4c91-a0d3-79fb4f55b857.png)

Here is an example of trying to copy - paste the dial javascript / html into a new widget. You can see that there is some level of modification needed and this is provided without guidance.

**Comment by devaskim** [comment]
Maybe I misunderstood, but you can export widgets bundle as json file, make changes and import modified version back.

**Comment by ParisMolver** [comment]
> Maybe I misunderstood, but you can export widgets bundle as json file, make changes and import modified version back.

This doesn't give you access to the underlying class. I'm not a web developer but I assume there is a way to edit the background color of the knob class without actually editing the knob then rebuilding thingsboard. That's the worst possible way to do it because you have to reinstall thingsboard to change the color of the knob. Very backwards.

Many of the build in widgets are locked and are called using <tb-widget> which creates the pre-defined widget class. You don't really get an opportunity to inject different values in for some of the private variables and unless the developer has made a setter for the private variable it's essentially un-editable.

**Comment by devaskim** [comment]
This is a cost for free of charge product.
You can make your contribution and hope what it will be approved.

**Comment by nikilito** [comment]
> > Maybe I misunderstood, but you can export widgets bundle as json file, make changes and import modified version back.
> 
> This doesn't give you access to the underlying class. Many of the build in widgets are locked and are called using which creates the pre-defined widget class. You don't really get an opportunity to inject different values in for some of the private variables of the class and unless the developer has made a setter for the private variable it's essentially un-editable. I'm not a web developer but I assume there is a way to edit the background color of the knob class without actually editing the knob.js then rebuilding thingsboard. I assume that on init() that you could specify tb-knob.bg-color = 'xxx' but I'm reliant on the setter I just talked about. Rebuilding the js (most straightforward but hardest to implement) is the worst possible way to do it because you have to reinstall thingsboard to change the color of the knob. Very backwards.

Have you solved it in any way?
I have the same problem: I just want to increase the font size of the label and there seems to be no way to do it.

**Comment by devaskim** [comment]
@nikilito You can override CSS styles in Settings tab of widget configuration.
![Скриншот 14-06-2022 191327](https://user-images.githubusercontent.com/86909129/173599206-ad92bbc9-c989-4224-9cab-efd6a2cf2102.jpg)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
