### ISSUE TITLE
[Bug] The telemetry data obtained by thingsboard gateway is misplaced,

### ISSUE THREAD

**Issue by bggmjxh** [thingsboard/thingsboard#6346]
I encountered a problem when using thingsboard,

Background:
I have a temperature and humidity sensor with Modbus protocol. I have collected data through thingsboard gateway. After comparison with MODBUS poll, the data collected by both are consistent under normal conditions, as shown in the figure below.
![正常](https://user-images.githubusercontent.com/15259863/161005162-17198242-3350-498e-b8b0-cc827b39fd78.gif)

However, there are two scenarios in which the data collected by the thingsboard gateway may be disordered (the positions of temperature and humidity are interchanged, or both temperature and humidity display temperature, and both temperature and humidity display humidity).
One scenario: after a long time of acquisition, this may happen in a few hours.
One scenario: I cut off the power and reconnected the temperature and humidity sensor. This will happen a few minutes ago, and it will be normal again after a period of time.
The diagram of abnormal conditions is as follows (Modbus poll normally displays the temperature and humidity of the equipment, and thingsboard is reversed):
![乱跳](https://user-images.githubusercontent.com/15259863/161005268-8f02ddd7-b2b9-4b92-a319-00719f37b53a.gif)

After persistence, it is found that the data is always wrong, sometimes misplaced for a long time, and sometimes kept correct for a long time. Modbus poll is always correct.
![730EA5D7-5CDB-4e8e-8B39-9F1F0B5EED15](https://user-images.githubusercontent.com/15259863/161005745-ef635e63-b00e-4720-bbce-3eb68e7a2010.png)

My MODBUS JSON is configured as follows:

`{
  "master": {
    "slaves": [
      {
        "host": "192.168.10.13",
        "port": 1031,
        "type": "tcp",
        "method": "socket",
        "timeout": 35,
        "byteOrder": "BIG",
        "retries": false,
        "retryOnEmpty": false,
        "retryOnInvalid": false,
        "pollPeriod": 500,
        "unitId": 1,
        "deviceName": "温度-WYB",
        "sendDataOnlyOnChange": false,
        "connectAttemptTimeMs": 5000,
        "connectAttemptCount": 5,
        "waitAfterFailedAttemptsMs": 300000,
        "attributes": [],
        "timeseries": [
          {
            "tag": "temperature",
            "type": "16uint",
            "functionCode": 4,
            "objectsCount": 1,
            "address": 1,
            "divider": 10
          },
          {
            "tag": "humidity",
            "type": "16uint",
            "functionCode": 4,
            "objectsCount": 1,
            "address": 0,
            "divider": 10
          }

        ],
        "attributeUpdates": [],
        "rpc": []
      }

    ]
  },
  "slave": null
}`

**Comment by javaMumu** [comment]
I have the same problem, looking forward to reply！

**Comment by mykhailokornieiev** [comment]
Hi. Please create a ticket in IoT Gateway repository 
https://github.com/thingsboard/thingsboard-gateway
