### ISSUE TITLE
Suggestion for BLE router to talk to Thingsboard

### ISSUE THREAD

**Issue by NKAVY** [thingsboard/thingsboard#635]
Hi,

We are working on an LTE/WIFI/Bluetooth router prototype, which is running embedded Linux on an ARM processor. We are investigating ways to make the router serve as an IoT hub, and Thingsboard seems like an interesting option for this functionality. 

We have an Ubuntu-based cross-development platform, and we have full JDK running on the router. 

We are looking for the simplest way to convert Bluetooth Low Energy data to MQTT (or cURL) so that it can be sent to thingsboard.io via a Thingsboard gateway (Not sure, if gateway is even required and the router can talk MQTT directly to thingsboard), which we plan to have on a local Ubuntu machine on the same subnet as the router. 

We are trying to understand what exactly we need: MQTT broker? Bluetooth to MQTT bridge? This will run on the ARM processor of our router, and receive data from BLE devices.

Basiclly the goal is to pair with BLE devices, receive data, and somehow get that data to the dashboard on thingsboard.io

Any insights here is very much appreciated.

Thanks in advance.

**Comment by ashvayka** [comment]
Hi,

I would recommend reviewing code of our IoT Gateway https://github.com/thingsboard/thingsboard-gateway and adding your BLE layer directly to this gateway as one of the extensions. Contributions are welcome. The alternative is to have BLE application, Mosquitto and TB IoT Gateway installed on your router.

**Comment by NKAVY** [comment]
Hi,

Thanks for the quick reply!

I am going to invest some time in getting an independent BLE application on router. If it succeeds, can I run thingsboard as a service in another Ubuntu machine and talk MQTT to it directly from the router? The interface would be,

BLE device -> BLE application in router (ARM) -> Thingsboard in ubuntu

I am not sure why thingsboard IOT gateway is required in this scenario. Looking for your comments in here.

The intention here is to port applications with lesser memory requirements on to the router. If the above doesn't work, I will have to try your first suggestion - to add a BLE layer to tb-gateway as an extension.

**Comment by ashvayka** [comment]
your scenario is valid. The router should use IoT Gateway API (MQTT) to be able to support more then one BLE device

**Comment by NKAVY** [comment]
Hi,

Thank you for your inputs. I shall close this issue.

**Comment by RayRedd** [comment]
Hi, I'd like to start with thanking for your comments and add-value in this post. I'm newbie here in IoT, I want to ask what do you mean with ble layer? A program that should relates between ble device and thingsboard service or an extension to add in thingsboard?

**Comment by zwells** [comment]
Here is the Adapter Extension for Bluetooth devices to work with Thingsboard! It's an easy Python script!
https://github.com/thingsboard/tb-ble-adapter
