### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by edosong** [thingsboard/thingsboard#6351]
**Describe the bug**
When using client side timestamp, {"ts":1648731311, "values":{"v1":3.111,"v2":3.222}}, where the ts is "Thu, 31 Mar 2022 12:55:10 GMT", the TB shows as
![image](https://user-images.githubusercontent.com/102741813/161066360-003f84e9-f693-4336-84aa-aa12d4385a44.png)
![image](https://user-images.githubusercontent.com/102741813/161073214-77561f7b-dbfc-4ec3-9361-12338e8cfec5.png)

**Your Server Environment**

* own setup
  * ThingsBoard CE Version 3.3.4.1
  * OS Ubuntu 20.4

**Your Client Environment**

**Desktop (please complete the following information):**

* OS [Windows 10]
* Browser [ chrome]
* Version [100.0.4896.60 (Official Build) (64-bit)]

* Connectivity
  * MQTT

**To Reproduce**
1. Use MQTTBox to send data as below:
![image](https://user-images.githubusercontent.com/102741813/161074236-814595d2-3eeb-45d4-8f7a-e72960c26fa2.png)

**Expected behavior**
The time should be the one indicated above.

**Screenshots**

**Additional context**

**Comment by devaskim** [comment]
According to official API documentation timestamp must have [milliseconds precision](https://devaskim.github.io/docs/reference/mqtt-api/#telemetry-upload-api).

**Comment by edosong** [comment]
Thank you very much. It's my error .  I saw it working now.
