### ISSUE TITLE
Create Widgets using locally hosted JavaScript libraries

### ISSUE THREAD

**Issue by cporter404** [thingsboard/thingsboard#6359]
**Component**
Creating Custom Widgets

I have a local installation of Thingsboard community edition running on an Ubuntu server. This server will not have access to the Internet to retrieve JavaScript libraries.  How do I host JavaScript libraries on the local Thingsboard server and how do I add that resource to my custom widget?

**Comment by Civilduino** [comment]
Maybe you can try calling the resource with `file:///` or `http://localhost`, see this [example](https://stackoverflow.com/questions/24043568/html-javascript-link-to-a-local-file) for a webpage.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
