### ISSUE TITLE
Oauth2 Authentication in thingsboard

### ISSUE THREAD

**Issue by piousdeepakxavier** [thingsboard/thingsboard#636]
Hi there,
We would like to provide "Login through Facebook" feature in our IoT platform which is developed with thingsboard 1.3.0.
Does it have any default provision/compatiblity to adopt this feature?  Or do we need to customize the existing database on our own? Thanks.

**Comment by vbalaji27** [comment]
Is this done? And is there anyways that third party authentication be used for server side?

**Comment by Karabiy** [comment]
the OAuth2 functionality is being present for the ThingsBoard 2.5+ versions. It can be configured. Soon there will be a guide regarding on how those can be established with Facebook. 
there are already prepared guides for some OAuth2  providers. You can refer to the documentation of ours regarding the OAuth2 basics with the ThingsBoard and refer to the guides for the other SSO providers: https://thingsboard.io/docs/user-guide/oauth-2-support/

**Comment by ArpithaJai** [comment]
Hey all, 

I am trying to configure Azure AD (Oauth2) for thingsboard. We are deployed in kubernetes. 
Have been following this doc https://thingsboard.io/docs/user-guide/oauth/azure/
but, I get error when the security parameters are added  to thingsboard.yml. 
Also, thingsboard works for implicit flow is there a work around.
