### ISSUE TITLE
How to remove loation icon from Map widget?

### ISSUE THREAD

**Issue by avipala** [thingsboard/thingsboard#6361]
I am using a Community version running on a raspberry and I have a Map widget that is showing the location of my devices.
I can change the color of the icon based on attributes etc
But if there is no information from that device for certain time, I want to remove the icon from the map
How can I do it?

**Comment by mde2017** [comment]
Hi @avipala

you could implement this via Marker images function:
https://thingsboard.io/docs/user-guide/ui/trip-animation-widget/#marker-options

- suscribe to attribute/telemetry you would like to use for checking activity of your devices
- add 2 images (1 marker & 1 empty/transparent image with no marker)
- implement marker function with your custom logic (if device is online show marker else show empty image)

**Comment by avipala** [comment]
Thank you very much!
