### ISSUE TITLE
MQTT integration with a communication modem

### ISSUE THREAD

**Issue by nissrine46** [thingsboard/thingsboard#6362]
please I'm trying to connect a communication modem called avior with thingsboard through MQTT protocol using mqtt://thingsboard.cloud:1883 broker but I can't I don't know if it's a problem with the credentials to log in to the broker or what because when I tried with a free broker it works great.
here are the configuration i did
![Screenshot 2022-04-04 095526](https://user-images.githubusercontent.com/102958594/161521446-c803c83d-9faa-41d1-a541-98af9fe6d38c.jpg)
![Screenshot 2022-04-04 095609](https://user-images.githubusercontent.com/102958594/161521449-c04da78e-0d6d-4d8f-b2a6-389f08f0f35e.jpg)
![Screenshot 2022-04-04 095626](https://user-images.githubusercontent.com/102958594/161521453-427c824c-1e71-4fa0-84be-bd9d9b7ec2f5.jpg)
![Screenshot 2022-04-04 095650](https://user-images.githubusercontent.com/102958594/161521456-0fdcd28e-1d26-4a23-9895-fb9e78846bd4.jpg)

**Comment by mde2017** [comment]
Hi @nissrine46,

try to use an intermediate MQTT broker between your modem & ThingsBoard. The MQTT integration connects only to external MQTT brokers as described in the documentation:
https://thingsboard.io/docs/user-guide/integrations/mqtt/
