### ISSUE TITLE
[Question] Filter entities in dashboard based on Current User attribute of type "array"

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#6363]
**Component**

 * Generic

**Description**
I want to filter the entities in a time series chart (or any other widget) using an attribute from the current user containing a list of the desired entities in an array. The image below shows the configuration of the filter. However, this is not working.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/27728926/161553010-84129728-dbd9-4a8b-8868-81e8dbb40869.png">

I cannot find proper documentation of the different filter functions. I interpreted `in` as: a function that searches a value in an array or similar. The image below shows the server side attribute of the user.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/27728926/161553796-5d458319-b0ba-44ed-866a-dee07dcd3cb2.png">

How could I filter the entities based on an array?

**Environment**

 * OS:  macOS
 * ThingsBoard: Cloud 3.3.4
 * Browser: Firefox

**Comment by Civilduino** [comment]
Figured out that the correct way to save the array in the attribute is as a comma-separated string `device1,device2,device3,etc`. So far working, but I will try it a bit more before closing this issue.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
