### ISSUE TITLE
[Question] Is alarmService working?

### ISSUE THREAD

**Issue by Gelmi** [thingsboard/thingsboard#6365]
**Component**
 * Generic

**Description**
I have a Alarms Table widget in my dashboard displaying alarms with details. I was planing to implement a custom action that would use the alarmService to Update the alarm details, but when i try to call the alarmService via widget Context ( widgetContext.servicesMap.get('alarmService') ) i doesn't work. If you take a look at https://github.com/thingsboard/thingsboard/blob/5bb6403407aa4898084832d6698aa9ea6d484889/ui-ngx/src/app/modules/home/models/widget-component.models.ts there is no alarm service being imported or defined in the widget context class. Is the feature implemented? or it's just not working?

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.4
 * Browser: Google Chrome (v96.0.4664.45)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
