### ISSUE TITLE
Thingsboard Edge PE does not start - License Error: CONNECTION_ERROR(400) Failed to Connect to Thingsboard license server!

### ISSUE THREAD

**Issue by apadEnlace** [thingsboard/thingsboard#6366]
**Component**
Thingsboard Edge

 * Installation

**Description**
I've been trying to install Thingsboard Edge PE to communicate to Thingsboard PE server. I get: "License Error: CONNECTION_ERROR(400) Failed to Connect to Thingsboard license server!"
![image](https://user-images.githubusercontent.com/99991163/161652968-f77ebb37-f42e-4e24-aa02-528494b0e66f.png)

The license server documentation (https://thingsboard.io/products/license-server/) says I only need internet access to license.thingsboard.io. I do have internet access, but it keeps not being able to connect to the license server. 

In my TB PE server, I see that the edge gateway tries to connect but disconnect immediately:

![image](https://user-images.githubusercontent.com/99991163/161653284-b366036a-0c27-44da-98da-0e6778b5d915.png)

I've tried installing TB Edge PE on a container on Linux and directly on Linux Ubuntu 20.04; on both, local VM and on the cloud VM, all these show the same error. Firewalls have been configured to allow all TCP traffic for testing.

The procedures I'm using to install are https://thingsboard.io/docs/user-guide/install/pe/edge/deb-installation/   and    
https://thingsboard.io/docs/user-guide/install/pe/edge/docker/

What am I missing?

Thanks for your help!

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: TB Edge PE (3.3.4pe) and TB Server PE 3.3.2 
 * Browser: Chrome Version 100.0.4896.60

**Comment by apadEnlace** [comment]
I looked at the "tb-edge.log" and below is what caught my attention. I also attach the log file:

![image](https://user-images.githubusercontent.com/99991163/161803649-087c2dcd-07f8-4106-9590-c47e86ff318b.png)
[tb-edge.log](https://github.com/thingsboard/thingsboard/files/8420193/tb-edge.log)


Additionally, I tested with an instance of Thingsboard Cloud Server PE, and I see the same issue

**Comment by volodymyr-babak** [comment]
@apadEnlace 
Edge PE is not accessing directly license server to validate the license - it's sending an HTTP request to ThingsBoard PE to validate it, and ThingsBoard PE sends this request to the license server. 
So ThingsBoard PE acts as a proxy between Edge PE and license portal.

You'll need to properly configure Cloud Enpoint:
![image](https://user-images.githubusercontent.com/3466101/161912473-971b44df-07d6-4235-a385-f7e5bfbc5c3d.png)
![image](https://user-images.githubusercontent.com/3466101/161912683-428e72e7-f8b0-490f-9ef4-005b46c794e4.png)

Please make sure that this IP is accessible by the Edge PE to do the license check.

**Comment by apadEnlace** [comment]
Thanks volodymyr-babak for explaining how it works

I was able to get it working. In the "CLOUD_RPC_HOST" parameter in the configuration file, I had to remove the text "https://" from the Cloud End Point Address. 

Also, it never worked when using the IP. But, this might be related to DNS configuration or other adjustment that needs to be done.

Thanks!
Abel
