### ISSUE TITLE
[Question] Unable to read input values using $scope

### ISSUE THREAD

**Issue by akashtalole** [thingsboard/thingsboard#6367]
**Component**

 * UI
 * Generic

**Description**
`    <md-input-container class="attr-input">
        <label>test</label>
        <input  type="text" name="w1" ng-model="w1" >
    </md-input-container>`
This is my sample input HTML.
I am trying to read value in javascript as below
`const w1 = $scope.w1;`

But I am getting undefined value. Is there any solution to this?

**Environment**

 * OS:  Ubuntu20.04
 * ThingsBoard: v3.3.4
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
