### ISSUE TITLE
Attribute Enrichment from device group

### ISSUE THREAD

**Issue by Kevinowitsch** [thingsboard/thingsboard#6369]
**Component**

 * Rule Engine

**Description**
Is it possible to enrich incoming telemetry with server attributes of the device group that the device is in?
I have tried the "related attributes" node in various configurations but couldn't get it to work. (Out was always failure)

**Environment**

 * OS:  Win10
 * ThingsBoard: PE 3.3.2
 * Browser: Firefox

**Comment by Backdraft007** [comment]
It is very helpful to see your configuration and the failure. All other is looking to a glass sphere.

**Comment by Kevinowitsch** [comment]
Ist not a rule chain failure, the msgType is failure so there is no error message.
Just wanna know if it is possible to enrich my 'POST_TELEMETRY' with server attributes of the device group it is in.

**Comment by Kevinowitsch** [comment]
The alternative would be to put the device into a asset and set the attributes there.

**Comment by Backdraft007** [comment]
I think the asset is the way it works. But I agree woth you with device groups.

**Comment by MJosipovi** [comment]
Hi, I am having similar problem. I have nodes that have assigned device profile called "LoRaWAN nodes". On every node I have added server attributes that I am trying to fetch in rule chain via "related device attributes" (I plan to use them as threshold values that are evaluated in filter script) and similarly I am only having failures with this.

This is screenshot of my rule chain (big picture, wait for a bit): https://drive.google.com/file/d/1VMX31jCOdTGQQCxK5Hyjp9IIj0g3pnYB/view?usp=sharing

And this are settings of my "related device attributes": https://drive.google.com/file/d/1v7jDGqCJgHsTS9033es84Hd0yH73wjR0/view?usp=sharing

Documentation of this element is very short and basically non existing, so even after like 5 hours I am without success on this. Any help is much appreciated.

OS: WIN 10
ThingsBoard: PE 3.3.4PAAS (thingsboard.cloud)
Browser: Firefox Developer Edition 100.0b3 (64-bit)

**Comment by MJosipovi** [comment]
We found the solution here: https://stackoverflow.com/questions/51484783/how-to-use-enrichment-nodes-in-thingsboard/71925964#71925964

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
