### ISSUE TITLE
Files Repository

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#637]
I would like to suggest some new functionality for Thingsboard: a files repository.

I suggest for each role (tenant, client, asset, device) a files repository to be added, ie. a space where files (of arbitrary format) may be uploaded, managed and shared with the other roles.

Some extension to the APIs has to be done to allow for downloading, and possibly checking the version of each file (timestamp? md5? other?). MQTT may publish this file on every change too.

**Comment by fotis400** [comment]
Currently Thingsboard is far from being a complete IoT platform. There is a lot of functionality missing, including:
- Firmware / Software Updates
- Remote logging
- Remote configuration of the device
- Proper device provisioning

I believe a files repository would be of great significance. Apart from the obvious use of sending and updating implementation specific files to the device, it will also aid as a work-around for all the above issues, while still be a generic and flexible solution.

For example, lets say I would like to perform an OTA firmware update to a device. The new firmware may be uploaded to Thingsboard (under the specific device), and the device will fetch the file and do the rest.

**Comment by fotis400** [comment]
Hi @LeoMorgan113,

why is this closed? Is it implemented?

**Comment by LeoMorgan113** [comment]
@fotis400,

I've added your proposal to our backlog(ticket number PROD-1031), so it will be reviewed by our developers for relevance and feasibility, but I cannot provide exact time period.
