### ISSUE TITLE
[Feature Request] Support Kafka-Multi-Tenancy / User-Spaces (Namespacing)

### ISSUE THREAD

**Issue by akei1984** [thingsboard/thingsboard#6373]
**Is your feature request related to a problem? Please describe.**
We are currently facing the problem to run multiple Thingsboard instances (e.g. Dev/Prod) on the same Kafka Cluster with Message Queue Configuration as

Consumer Groups/Consumer-IDs,Producer-IDs
and some Topic names are hardcoded.

e.g. 
monlith-consumer is always named _monlith-consumer_ in each environment
https://github.com/thingsboard/thingsboard/blob/da4c74287216fc6962c74f084c2eedebf06e1a64/common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java

This does affect currently running instances as two concurrent running instances will join into the same consumer group or subscribe to the same kafka topic.
Making it impossible to do so. 

Additionally, the current naming especially with hardcoded consumer-groups makes it very hard for the kafka admin to define fitting ACLs. 

**Describe the solution you'd like**
A very simple solution would be to introduce a new configurable parameter to CoreSettings or Kafkasettings that will be added as prefix to all topic,consumer-groups/ids,producer-ids.

This would allow to configure and seperate  by project/user/org according to 
https://kafka.apache.org/documentation/#multitenancy-topic-naming and additionally allowing a full environment separation using prefixed ACLS 

https://kafka.apache.org/documentation/#security_authz. 

At the sametime having a minimal effect on different supported queueing alternatives like rabbitMQ.

**Describe alternatives you've considered**
A viable alternative would be to allow configuration of currently all hardcoded topics,consumer-groups,consumer-ids,producer-ids...

**Additional context**

https://kafka.apache.org/documentation/#multitenancy-topic-naming
https://kafka.apache.org/documentation/#security_authz.

**Comment by Ultrazombie** [comment]
Hello @akei1984 
Do you see this feature? Try to configure the ThingsBoard env's using separate global prefix.
`  prefix: "${TB_QUEUE_PREFIX:}" # Global queue prefix. If specified, prefix is added before default topic name: 'prefix.default_topic_name'. Prefix is applied to all topics (and consumer groups for kafka>
`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
