### ISSUE TITLE
[Bug] Fail to use "MD5" as Authentication Protocol in SNMP v3 Device Registration

### ISSUE THREAD

**Issue by jcnleejohn** [thingsboard/thingsboard#6375]
When a new device with a device profile having transport type equal to SNMP is registered with Transport Configuration Authentication Protocol set to MD5, the registration process is rejected with a RED error bar attached.

**Your Server Environment**

* own setup
  * ThingsBoard PE v3.3.2
  * CentOS 7.8 (64-bit)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Firefox
* Version 98.0.2

**Your Device**

* Connectivity
  * SNMPv3

**Screenshots**
![image](https://user-images.githubusercontent.com/15992647/161780926-a486376a-7998-4cf6-8779-309b04187f79.png)

**Comment by myroslav-tb** [comment]
Hi @jcnleejohn, our prod team has confirmed that this is a bug and is planning to release a fix for it in version 3.7.1
