### ISSUE TITLE
Fail to receive telemetry over SNMP v3 protocol

### ISSUE THREAD

**Issue by jcnleejohn** [thingsboard/thingsboard#6376]
**Describe the bug**
When a SNMPv3 device is registered (transport_config.jpg), the Wireshark messages between TB and the peer device (VMware ESXi) indicate that the Engine ID sent from TB (10.166.22.50) to VMware (10.166.22.38) IS NOT CORRECT. It has been transformed from 00000063000000a100000000 to 303030303030363330303030303061313030303030303030. As a result the SNMPv3 handshaking always fails, and so no telemetry can be polled from the device.

**Your Server Environment**

* own setup
  * ThingsBoard PE v3.3.2
  * CentOS 7.8 (64-bit)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Firefox
* Version 98.0.2

* Connectivity
  * SNMPv3

**Screenshots**
![image](https://user-images.githubusercontent.com/15992647/161781950-b1284492-6a16-4ca9-b3b4-8b79dca93901.png)
![image](https://user-images.githubusercontent.com/15992647/161782002-f00c88ee-3eb7-4282-bbc7-706830a06aad.png)
![image](https://user-images.githubusercontent.com/15992647/161782070-ef4224ca-e69d-4240-8de4-2f4a0410c135.png)

**Comment by Ultrazombie** [comment]
Hello @jcnleejohn,
This issue has been resolved in [PR #11515](https://github.com/thingsboard/thingsboard/pull/11515). Please upgrade to the latest version of ThingsBoard to apply the fix, and let us know if everything works as expected.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
