### ISSUE TITLE
Bad SQL grammar exception when writing to database

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#6377]
**Component**
 * Generic

**Description**
I have updated my ThingsBoard Docker installation according to [this guide](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=inmemory#upgrading). The Update was performed without any issue, but I have figured out today that my device can not store or read data from the database. I got these errors after viewing the debug output of the `Aktion - save timeseries`.

![image](https://user-images.githubusercontent.com/3458587/161837896-18c0cc5c-a550-44ca-b995-1dc7fb6a31df.png)

What´s the reason for this issue and how can I fix it?

**Environment**
 * OS:  Ubuntu 18.04.5 LTS
 * ThingsBoard: 3.3.3 PE

**Comment by INNSOMANIA** [comment]
Bro how did you solve the problem?
