### ISSUE TITLE
Thingsboard-gateway failed to start

### ISSUE THREAD

**Issue by jessedcpc** [thingsboard/thingsboard#6378]
**Component**

 * Generic

**Description**
thingsboard-gateway.service failed to start. 

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.4.1

PS: I am a Linux and Thingsboard novice, so greatly appreciate any support :)

I have attempted a fresh install of Ubuntu and followed the (DEB) install and gateway install guide. From what I've found online, I would guess my config is incorrect, but I don't know enough about Thingsboard/Linux to investigate further.

Result of "systemctl status thingsboard-gateway":

> thingsboard-gateway.service - ThingsBoard Gateway
    Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
    Active: failed (Result: exit-code) since Wed 2022-04-06 08:42:29 AEST; 14min ago
    Process: 12388 ExecStart=/usr/bin/python3 -c from thingsboard_gateway.tb_gateway import daemon; daemon() (code=exited, status=1/FAILURE)
   Main PID: 12388 (code=exited, status=1/FAILURE)
Apr 06 08:42:29 crisp-desktop systemd[1]: thingsboard-gateway.service: Scheduled restart job, restart counter is at 5.
Apr 06 08:42:29 crisp-desktop systemd[1]: Stopped ThingsBoard Gateway.
Apr 06 08:42:29 crisp-desktop systemd[1]: thingsboard-gateway.service: Start request repeated too quickly.
Apr 06 08:42:29 crisp-desktop systemd[1]: thingsboard-gateway.service: Failed with result 'exit-code'.
Apr 06 08:42:29 crisp-desktop systemd[1]: Failed to start ThingsBoard Gateway.

Gateway config files below: (saved as .txt so I can upload)
[tb_gateway.txt](https://github.com/thingsboard/thingsboard/files/8422262/tb_gateway.txt)
modbus.json left as default for now
[modbus.txt](https://github.com/thingsboard/thingsboard/files/8422273/modbus.txt)

Gateway log files are not updating so I have not uploaded them

**Comment by Backdraft007** [comment]
Hi,
is there something in /var/los/syslog?

**Comment by jessedcpc** [comment]
Hi Backdraft,

Below is the syslog. I restarted the gateway and ran a status check just before saving the file :) 

[syslog.txt](https://github.com/thingsboard/thingsboard/files/8431172/syslog.txt)

**Comment by Backdraft007** [comment]
Hi,
is it a fresh system?

Can you please try the following:
`pip show protobuf`
`pip3 install --upgrade protobuf`
`pip show protobuf`

**Comment by jessedcpc** [comment]
Thanks for the info! Yes, it is a fresh install (as I thought I may have botched something lol)

I shall give that a go in the morning, really appreciate your help 😄

**Comment by jessedcpc** [comment]
Ok so I have updated from 3.06 to 3.20 and rebooted the machine. Restarted thingsboard-gateway service and still getting the same error.

Attached below is latest syslog if that helps
[syslog.txt](https://github.com/thingsboard/thingsboard/files/8447298/syslog.txt)

I can see that just before the gateway errors, it has the following:
`Apr  8 08:03:52 crisp-desktop python3[2936]:     create_key=_descriptor._internal_create_key,
Apr  8 08:03:52 crisp-desktop python3[2936]: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
`
Unsure how to correct this.

**Comment by Backdraft007** [comment]
Can you please uninstall protobuf.

`pip3 uninstall protobuf`

Run this command twice to be sure it is uninstalled. After that install it again.

`pip3 install --upgrade protobuf`

**Comment by jessedcpc** [comment]
I uninstalled protobuf 3.20.0, 3.6.1 was still lingering which I had to manually rm the folder. Once deleted, I re-installed protobuf 3.20.0, restarted the machine and then restarted the gateway. Still the same issue it appears :(

[syslog.txt](https://github.com/thingsboard/thingsboard/files/8459972/syslog.txt)

**Comment by Backdraft007** [comment]
Strange,
can you show the version with `pip3 show protobuf`, is it 3.20.0?
Have a look in "/usr/lib/python3/dist-packages/google/protobuf/__init__.py", which version?

**Comment by Backdraft007** [comment]
Ah,
please remove protobuf from apt.
`sudo apt remove python3-protobuf`
then rerun the installation of gateway
`sudo apt install ./python3-thingsboard-gateway.deb -y`

I can reproduce it, with a fresh install. This way worked for me.

**Comment by Backdraft007** [comment]
Hi,
no problem. Is it possible that I can have a look on your server? I think a re-install is not necessary.

**Comment by jessedcpc** [comment]
Absolutely, I have AnyDesk installed on the machine and can message you the ID (I guess GitHub doesn't have private message tho). I'll be available any time during your morning :)

**Comment by Backdraft007** [comment]
Sorry for late respond. I can support after easter. Is it okay?

**Comment by jessedcpc** [comment]
That would be awesome, thanks a heap :)

**Comment by jessedcpc** [comment]
Hey Chris, let me know if you have a chance sometime this week to assist. No worries if you're busy

**Comment by jessedcpc** [comment]
Any update mate? I've had another go last week to no success... any help is greatly appreciated!

**Comment by jessedcpc** [comment]
So I ended up re-installing a bunch of times and eventually installed v3.2 Thingsboard and v2.9 of Gateway and it worked perfectly fine together.
