### ISSUE TITLE
[Question] Gateway Widgets - IoT Gateway: How is the configuration update of an IoT Gateway implemented through the Gateway Widget?

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/thingsboard#6380]
**Gateway Widget**

 * Generic

**Description**

I'm wondering where can I find the source code of **Gateway Widgets**. I'd like to review the code about how it implements (via rpc? rest api? mqtt? mqtt gateway api?) the **configuration updates** for an IoT Gateway.

Is the new configuration sent via shared attribute in JSON format and its configuration file (
/etc/thingsboard-gateway/config/**tb_gateway.yaml**) updated in the gateway? or how is this procedure performed?

Many thanks in advance.

**Environment**

 * OS: Centos8
 * ThingsBoard: 3.3.4.1
 * Browser: Firefox 98.0.2 (64-bit)

**Comment by devaskim** [comment]
One way to review the code is to login as a tenant, open the *Widgets library* side menu. Find and open the *Gateway widgets* bundle. Then click *Edit* on one of the widgets.

**Comment by alexcorvis84** [comment]
> One way to review the code is to login as a tenant, open the _Widgets library_ side menu. Find and open the _Gateway widgets_ bundle. Then click _Edit_ on one of the widgets.

Thanks @devaskim, but that only show the widget code, while I'm more interested in the **'backend implementation'** that it performs between the platform <-> IoT Gateway. 

I mean, research how the Gateway Widget manages the remote configuration (methods, protocol used, API...) in order to **update remotely** the configuration file `tb_gateway.yml `of the IoT Gateway device.

**Comment by devaskim** [comment]
I created test gateway device via UI without running any real gateway and add configuration to it via gateway widget.
In browser DevTools I see 3 POST request after submitting configuration. The REST endpoint is the same - */api/plugins/telemetry/DEVICE/<device_id>/SHARED_SCOPE*
1. Added the *configuration* **shared attribute** with base64-encoded gateway configuration (I used OPC UA copied from gateway repo).
2. Added the *RemoteLoggingLevel* **shared attribute** with the *DEBUG* value.
3. Added the *configuration_drafts* **server attribute**  with the strange"e30=" value.

So real TB gateway once it has started it subscribes on attribute updates and then process the *configuration* attribute in specific way.

If you want to go deeper:

From [TB Swagger docs](https://demo.thingsboard.io/swagger-ui/#/telemetry-controller/saveEntityAttributesV1UsingPOST) you can find the name of the source code file and the name of the Java method - *TelemetryController.java* and *saveEntityAttributesV1* correspondingly.

Then you go to the TB repo, click on the 'Go to file' button and type the source file name and watch thousands lines of code)

**Comment by alexcorvis84** [comment]
> I created test gateway device via UI without running any real gateway and add configuration to it via gateway widget. In browser DevTools I see 3 POST request after submitting configuration. The REST endpoint is the same - _/api/plugins/telemetry/DEVICE/<device_id>/SHARED_SCOPE_
> 
>     1. Added the _configuration_ **shared attribute** with base64-encoded gateway configuration (I used OPC UA copied from gateway repo).
> 
>     2. Added the _RemoteLoggingLevel_ **shared attribute** with the _DEBUG_ value.
> 
>     3. Added the _configuration_drafts_ **server attribute**  with the strange"e30=" value.
> 
> 
> So real TB gateway once it has started it subscribes on attribute updates and then process the _configuration_ attribute in specific way.
> 
> If you want to go deeper:
> 
> From [TB Swagger docs](https://demo.thingsboard.io/swagger-ui/#/telemetry-controller/saveEntityAttributesV1UsingPOST) you can find the name of the source code file and the name of the Java method - _TelemetryController.java_ and _saveEntityAttributesV1_ correspondingly.
> 
> Then you go to the TB repo, click on the 'Go to file' button and type the source file name and watch thousands lines of code)

Hi @devaskim many thanks for your feedback and sorry for late reply!

Regarding Point 3
>     3. Added the _configuration_drafts_ **server attribute**  with the strange "e30=" value.

It's {} coded in BASE64 as well

**Comment by yohnnylim** [comment]
Can we configure custom converter class using the widget ?

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
You can refer to Github for community support and may create an issue there:

- https://github.com/thingsboard/thingsboard-gateway/issues

Please describe all the details of your case there, and then you will increase the probability that the GitHub community will be able to help you.
