### ISSUE TITLE
[Question] How to schedule (periodically send) server-side RPC in TB CE?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6382]
**Component**
 * Rule Engine
 * Generic

**Description**
How to schedule (periodically send) server-side RPC?

**Comment by Backdraft007** [comment]
In PE you can use scheduler:
https://thingsboard.io/docs/pe/user-guide/scheduler/#send-rpc-request-to-device

**Comment by devaskim** [comment]
There are a lot of Lora sensors managed by gateway (not TB IoT gateway but it uses TB mqtt gateway API). Each N seconds/minutes/hours (this is a shared or server attribute) a sensor should start self-cleaning procedure but a sensor doesn't have any clock implementation. So the idea is to send the CLEAN rpc from server side. Each sensor may have different cleaning period.

**Comment by Backdraft007** [comment]
Damn, I think it is not possible right now. I think you make a feature request for a rule node, that can send a RPC request to device.

**Comment by Backdraft007** [comment]
Maybe you can use the REST API from thingboard itself?
https://demo.thingsboard.io/swagger-ui/#/rpc-v-2-controller

**Comment by devaskim** [comment]
@Backdraft007 I found the answer to the question of this ticket but unfortunately it doesn't cover my case.
One can use the Generator node with the `RPC_CALL_FROM_SERVER_TO_DEVICE` message type.
Here is an [example from official docs](https://devaskim.github.io/docs/user-guide/rpc/#using-the-rule-engine).
