### ISSUE TITLE
[Feature] Awesome Thingsboard collection

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6384]
### Hey community,
Let's make the collection of awesome Thingsboard things!

https://github.com/devaskim/awesome-thingsboard
**Looking for your contributions)))**

**Comment by Backdraft007** [comment]
Nice idea,
but I think you have to show your contributions first and not only an empty repository. :)

Here are some widgets:
https://github.com/rossmann-engineering/Collibellex-Thingsboard-Widgets

**Comment by devaskim** [comment]
You are right. I think my contributions will be soon as we are starting new big project that already need many features missing both in CE and PE versions. Of course, I prefer the pull request to the origin repository but for some reasons TB team may ignore contributions even without any comments. I know this project almost from beginning and made contributions to gateway, server and documentation (not only from current Github account) but unfortunately I watched useful pull requests (not mine) that were abandoned. So to not to loose interesting ideas from community I decided to create this repo.

*I think TB platfrom is awesome and our community can make it even more powerful!*

P.S.: And thanks for the link. I added it to

**Comment by devaskim** [comment]
First big update is [available now](https://github.com/devaskim/awesome-thingsboard).

**Comment by janhajk** [comment]
Thanks for this awesome list.
You can add also our widget which you'll find here:
https://github.com/SchweizerischeBundesbahnen/thingsboard-advanced-attribute-widget

**Comment by devaskim** [comment]
@janhajk Thanks for your interest!!!
I added ATAW earlier (see [Widget section](https://github.com/devaskim/awesome-thingsboard#widgets))
