### ISSUE TITLE
[Bug] Thingsboard Mobile Can't Install in Android 12

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#6386]
Hello,
I try to release apk and install and it didn't work at phone with Android12

works fine at android 11 phone or below

**Comment by Backdraft007** [comment]
Hi,
you have to add `android:exported="true"` to your AndroidManifest.xml two times. In the activity line 18 and the activity line 58
see: https://cafonsomota.medium.com/android-12-dont-forget-to-set-android-exported-on-your-activities-services-and-receivers-3bee33f37beb

**Comment by evanderbird** [comment]
Thanks , i will try it.

**Comment by Backdraft007** [comment]
I made PR
https://github.com/thingsboard/flutter_thingsboard_app/pull/21
https://github.com/thingsboard/flutter_thingsboard_pe_app/pull/11 for PE
