### ISSUE TITLE
[Question] ChirpStack Integration With ThingsBoard CE

### ISSUE THREAD

**Issue by dani21almc** [thingsboard/thingsboard#6389]
**Component**

 * Generic

**Description**
I'm trying to send data from a device in ChirpStack to a ThingsBoard CE in a EC2 ubuntu server to visualize the data and my question is if is possible to do it, and maybe generate downlinks from ThingsBoard CE to chirpStack. Can someone help me with a guide for this?  

**Environment**

 * OS:  name and version
 * ThingsBoard: Community Edition
 * Browser: name and version

**Comment by Backdraft007** [comment]
Generally integrations are only available in PE version.
There is also a ready integration for chirpstack. 
https://thingsboard.io/docs/user-guide/integrations/chirpstack/

**Comment by dani21almc** [comment]
I found this information:https://thingsboard.io/docs/getting-started-guides/connectivity/ and here says that is it possible to integrate ThingsBoard Community Edition with Chirpstack, but I still can not do it.

**Comment by Backdraft007** [comment]
Ok, this guide is also linked:
https://www.chirpstack.io/application-server/integrations/thingsboard/
Did you try that?

**Comment by arifulmrislam** [comment]
You can read this repository. Maybe it will help you find the solution. 
https://github.com/arifulmrislam/Datalogging-with-ChirpStack-Node-RED-InfluxDB-Grafana-with-Docker

**Comment by danialothman** [comment]
> Ok, this guide is also linked: https://www.chirpstack.io/application-server/integrations/thingsboard/ Did you try that?

Hey all, has anyone managed to get Chirpstack to integrate with Thingsboard CE?
