### ISSUE TITLE
owntracks and thingsboard

### ISSUE THREAD

**Issue by Gastondamian** [thingsboard/thingsboard#639]
I'm trying to configure owntracks to work with thingsboard but I cant do it.

any guide or help?

**Comment by jpnmatoso** [comment]
{
  "_type": "configuration",
  "waypoints": [],
  "auth": true,
  "autostartOnBoot": true,
  "beaconBackgroundScanPeriod": 30,
  "beaconForegroundScanPeriod": 0,
  "beaconLayout": "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
  "beaconMode": 0,
  "cleanSession": false,
  "clientId": "*********", // Your Thingsboard Device Access Token
  "cmd": true,
  "cp": false,
  "deviceId": "****", // Let same Owntracks Device ID
  "host": "******.com", // Thingsboard Host. Domain or IP
  "ignoreInaccurateLocations": 0,
  "ignoreStaleLocations": 0,
  "keepalive": 3600,
  "locatorAccuracyBackground": 1,
  "locatorAccuracyForeground": 0,
  "locatorDisplacement": 500,
  "locatorInterval": 900,
  "mode": 0,
  "mqttProtocolLevel": 3,
  "notification": true,
  "notificationHigherPriority": false,
  "notificationLocation": true,
  "playOverride": false,
  "port": 1883, // Thingsboard MQTT Port
  "pub": true,
  "pubExtendedData": true,
  "pubQos": 1,
  "pubRetain": true,
  "pubTopicBase": "v1/devices/me/telemetry", // Thingsboard Telemetry Topic
  "ranging": false,
  "remoteConfiguration": true,
  "sub": true,
  "subQos": 2,
  "subTopic": "v1/devices/me/telemetry", // Thingsboard Telemetry Topic
  "tls": false,
  "username": "******", // Your Thingsboard Device Access Token
  "ws": false
}

**Comment by Gastondamian** [comment]
Thanks, but it doesnt work. It say configuration incomplete.

**Comment by jpnmatoso** [comment]
Hi Gastondamian.

I'm using Owntracks Android Version 1.2.7 and Thingsboard in a dedicated server instalation.

Maybe I send old configuration. I'll send another below.

Change *** values. Change "deviceId" in line 14, this is your owntracks deviceId.

Remove comments and spaces after coma. ***Put Your...***

Save your file UTF-8 with extension ".otrc" and import to your Owntracks.

I hope that's work.

**Comment by jpnmatoso** [comment]
{
  "_type": "configuration",
  "waypoints": [],
  "auth": true,
  "autostartOnBoot": true,
  "beaconBackgroundScanPeriod": 30,
  "beaconForegroundScanPeriod": 0,
  "beaconLayout": "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24",
  "beaconMode": 0,
  "cleanSession": false,
  "clientId": "***",***Put Your Thingsboard Device Access Token and remove this after coma***
  "cmd": true,
  "cp": false,
  "deviceId": "j7elte",
  "host": "***.com",***Put Your Thingsboard domain whitout http:// and remove this after coma***
  "ignoreInaccurateLocations": 0,
  "ignoreStaleLocations": 0,
  "keepalive": 3600,
  "locatorAccuracyBackground": 1,
  "locatorAccuracyForeground": 0,
  "locatorDisplacement": 500,
  "locatorInterval": 900,
  "mode": 0,
  "mqttProtocolLevel": 3,
  "notification": true,
  "notificationHigherPriority": false,
  "notificationLocation": true,
  "playOverride": false,
  "port": 1883,
  "pub": true,
  "pubExtendedData": true,
  "pubQos": 1,
  "pubRetain": true,
  "pubTopicBase": "v1/devices/me/telemetry",
  "ranging": false,
  "remoteConfiguration": true,
  "sub": true,
  "subQos": 2,
  "subTopic": "v1/devices/me/telemetry",
  "tls": false,
  "username": "***",***Put Your Thingsboard Device Access Token and remove this after coma***
  "ws": false
}

**Comment by Gastondamian** [comment]
Thanks! the problem was Password,  I put the device ID in password and now is working.
