### ISSUE TITLE
[Bug] Handler Dispath Failed; Nested exception is: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by PawelOstropolski** [thingsboard/thingsboard#6390]
**Describe the bug**
Saving a widget intermittently causes an OutOfMemoryError: Java heap space. A similar issue was reported with earlier versions.. is it now back?  

**Your Server Environment**

* own setup
  * local infrastructure 
  * PE 3.3.4.1
  * Linux 5.4.0-104-generic#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/11941860/162298230-5dd8dfb3-5a27-4692-b71c-1b5e6ca2e859.png)

**Comment by Backdraft007** [comment]
Can you give more information of your server? Virtual machine or bare metal? How much memory (RAM) has your server? And so on.

Do you have playes with this configuration?
https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-6-optional-memory-update-for-slow-machines-1gb-of-ram

**Comment by PawelOstropolski** [comment]
It is an ESXi 7.0 VM with 4GB of RAM and 4x vCPUs running the Ubuntu 20.04.4 LTS 64bit server. The first time this issue happened was yesterday, I was running TB on this VM for over 6 months with no issues. What has changed recently in the env: I added another tenant as a sandbox for developers and there are 2-3 developers now working simultaneously on widget libraries. One of them just experienced this problem.  per "top" - memory usage by thingsb+ java process is about 50% of total memory...  from sensor standpoint this TB instance is serving about 64 sensors liekly with far less than 1 message/second... load... 

did not play with the tweak for slow machines, since the host is > 1GB of RAM... and there were no issues so far...     

some relevant log outputs below.:  

cat /var/log/syslog | grep java
Apr  7 12:26:29 thingsboard-srv-001 thingsboard.jar[912]: java.lang.OutOfMemoryError: Java heap space
Apr  7 12:26:29 thingsboard-srv-001 thingsboard.jar[912]: Dumping heap to java_pid912.hprof ...

hprof file is about 750M... 

ls -l /./usr/share/thingsboard/bin/java_pid912.hprof
-rw------- 1 thingsboard thingsboard 753122364 Apr  7 12:26 /./usr/share/thingsboard/bin/java_pid912.hprof

**Comment by Backdraft007** [comment]
I think 4GB of RAM is not enough.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
