### ISSUE TITLE
API Usage - how to request these data thru API?

### ISSUE THREAD

**Issue by hallard** [thingsboard/thingsboard#6394]
**Component**

 * Generic

**Description**
We got lot of interesting information on API Usage screen, we would like to get these information thru API calls but we did not found the corresponding API, so the question, is it possible to request these values such as `transport hourly activity` and `rule engine hourly activity` with API calls?

**Environment**
 * N/A

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.

**Comment by GrayCygnus** [comment]
Any news on this? I would love to access API usage and those as well but i see no documentation of such in the swagger.
