### ISSUE TITLE
[Question] Deleted assets can't be re-created?

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6396]
**Component**

 * Generic

**Description**
Hi, I've deleted some Assets but it was a mistake. I want to re-create them but I've a message "Asset with such name already exists!" and it's not created. 
I can't find them anywhere in menubar but they are present in lists of assets when I have to choose an Asset.
Any idea to re-create them?
Thanks.

**Environment**

 * ThingsBoard: Thingsboard cloud
 * Browser: Microsoft Edge 100.0.1185.36

**Comment by JacksonBowe** [comment]
I've had this problem before. What you need to do is use the REST api to check for and delete the asset. 


Search Thingsboard JWT
follow the process to get a JWT token for yourself

Search Thingsboard Swagger
In the url, change the domain to yours.

Authorise the Swagger UI with your token (It will need to be in form 'Bearer #' where '#' is your token.

Now you can use the listed API calls to try and find your device.

**Comment by liotys** [comment]
Thanks a lot @JacksonBowe , I need a little time to understand that I need another url than demo.thingboard.io...
I now have delete the Assets and I have re-create them.
