### ISSUE TITLE
[Question] lwm2m sofware update

### ISSUE THREAD

**Issue by jonasfoyth** [thingsboard/thingsboard#6397]
**Component**
 * Generic

**Description**
Hello! 

I'm testing software update with a device profile configurated to lwm2m (using object 9). I've configurated my lwm2m-client with 10 instances in object 9 (9.0....9.9, one different software by instance - validated with other applications), but in thingsboard is only possible assing one software by device? It's rigth that? 

Object 9: 

![image](https://user-images.githubusercontent.com/33319582/162791203-0082bfdb-7345-47d4-8c54-b92ce379b483.png)

**Environment**
 * OS:  ubuntu 20.04
 * ThingsBoard: Version: 3.3.4.1

**Comment by epalchenko** [comment]
Hello,
Yes, that’s correct; this is the design's intention. ThingsBoard currently only supports assigning one software instance per device, so multiple instances in Object 9 will not function differently within this configuration.
