### ISSUE TITLE
[Question] How to speed up migration ?

### ISSUE THREAD

**Issue by tdsimpro** [thingsboard/thingsboard#6398]
**Component**

 * Installation

**Description**
Hi, we're migrating our thingsboard installation from 2.4 to the latest version and it's taking 24hours + (we have a lot of data).
Is there a way to speed things up by buffing the server and modifying the thingsboard conf to use more memory or something to do with postgres ? Thanks 

**Environment**
 * OS:  Centos
 * DB : Postgres

**Comment by ban2derlog** [comment]
Hi, unfortunately, migration from PostgreSQL to Hybrid takes time.
Database migration from SQL to Hybrid (SQL and NoSQL) database required refactoring for all entities and configurations.
And before making it - always create backups. With a huge amount of data any system can stuck on some moment, so check CPU\RAM\Persistant memory consumption.
