### ISSUE TITLE
[Question] How to automate migration of rule chains between tenants?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6400]
I know about [Rule Chain REST API](https://demo.thingsboard.io/swagger-ui/#/rule-chain-controller))))

At the moment I have root rule chain and another 3 chains linked with the root. It is like a test env. Once I added new feature to rule chains I need to migrate (copy) these changes to other tenants who are like a production env.

**Comment by Backdraft007** [comment]
Hi,
I'm interested, too. I have read here https://thingsboard.io/docs/reference/roadmap/ that there comes a git integration. I think this is a good way.
