### ISSUE TITLE
[Question]Change entity name and send json

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/thingsboard#6401]
Good morning,

I'm starting a bit with Thingboard and I have some doubts.
There are two things I can't do with widgets.

One is to change the name of the device or entity from a widget.

The other thing is to send two hours to my device, one I use to turn it on and the other to turn it off. Being able to send a JSON with the two values ​​would help me.
I have tried the Input widgets but it does not send it to the device.

Thank you very much for the help.

Greetings!

**Comment by mde2017** [comment]
Hi @Ataraxiall,

**1. Changing entity fields such as name or label:**
Please try to use the entity admin widgets. They include action buttons for changing entity fields & also attributes.
They can be even customized to your needs.
https://www.youtube.com/watch?v=4qSSbqXntEQ
 

**2. Sending data to device from TB:**
    Check out the RPC functionality. You can find examples in the documentation
    https://thingsboard.io/docs/user-guide/rpc/
    https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/
