### ISSUE TITLE
[Feature Request] de-duplication node 

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#6402]
We have sensors that transmit the same packet multiple times in a short period of time

for example, BLE temperature sensor is transmitting every 10secs or 2min.

we only want to save this packet once for 5 minutes in thingsboard.

ideally there was a NODE to handle this, where you define how many messages to allow per X seconds/minutes per Device ID.

otherwise it is a little complex to solve with existing nodes. Because sometimes the messages are received within milliseconds of each other, so Saving the timeseries, and then doing a lookup is too short of a time.

is there a simple way to do it today?  @ashvayka

**Comment by igloodan** [comment]
This is a node which would be useful to my use cases also, the only problem being that you will discard more recent data and only have the "last saved" value in timeseries.

Maybe a node which will "thin out" data for a given timeseries value when triggered, if you give it a value like "temperature" and a time window like "15" then it would strip out all but the first value in every 15 minute interval past the hour.

**Comment by devaskim** [comment]
Try to use the [Delta node](https://devaskim.github.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#calculate-delta) to filter the same values.

**Comment by t0mZ4** [comment]
@devaskim I don't see how delta Node will help me de-duplicate.

@ashvayka I think de-duplication should be a basic feature of the platform, and can be a great addition to Integrations/Data converter. Where a checkbox and a threshold settings will take care of it.

But, @devaskim you did give me an idea, perhaps to use Analytics - aggregate stream (thingsboard PE), as a potential solution setup as 5MIN AVG, this will maintain accuracy of multiple samples, but produce a single value every 5 min.

i will need to workout removing original temperature variable, and saving output variable instead, which is a complication I do not keen about. But might be a short-term workaround

Any thoughts guys ?

**Comment by devaskim** [comment]
@t0mZ4 What do you mean by duplicated data?
As I understand, it means that several **sequential** packets has the same data.
```
1st
{ 'param': '123'}
2nd
{ 'param': '123'}
3rd
{ 'param': '123'}
```
If yes, the *Delta* node will return `deltaParam` set to 0 for such packets and you just ignore them instead of storing into database.

**Comment by ashaforost** [comment]
The deduplication rule node is already a part of the thingsboard rule chain functionality. I am closing this issue as stale.
