### ISSUE TITLE
"Widget displays 1024 out of ... entities"

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#6403]
**Component**
Widgets

**Description**
I have a "latest values" widget. In the dashboard itself, I see the following message: "Widget displays 1024 out of 1874 entities". I want to display **all** entities, and completely remove this limitation. How can I achieve that?

Thank you.

**Environment**
ThingsBoard: 3.3.3

**Comment by mikelfo** [comment]
We are experiencing this same issue in a widget exporting a list of devices with a specific attribute value. As soon as the number goes over 1024 we get this warning, and the list is truncated to that length.

**Comment by MichaelRHaddad** [comment]
@mikelfo Have you managed to solve this issue?

**Comment by MichaelRHaddad** [comment]
This attribute is configured to 10000 entities, so it seems to not be the problem.

**Comment by ashvayka** [comment]
"1024" is a hard-coded value on the UI side for a default entity data query. It is used by all "latest values" widgets except the Map Widget which has the parameter configurable in the advanced settings of the widget. CE users may change this in the source code. We will introduce the configuration parameter in the "Data Settings" of the widget in release 3.4.

**Comment by MichaelRHaddad** [comment]
@ashvayka  Thank you for the reply. We are using PE so I assume we should also be able to change this hard-coded value in the source code. We did try to, but we did not find this attribute. Could you please guide me and show me where we can change it?

**Comment by phamhaidang112000** [comment]
@MichaelRHaddad  how to show widget data settings, please show me. I can't find it

**Comment by uhofemeier** [comment]
@phamhaidang112000 , Click on Dashboards, click edit mode (orange pencil bottom right corner), click the little pencil for the widget that has a device list or otherwise. This is where you'll find data settings.

**Comment by omkarfoodef** [comment]
@ashvayka I am facing the same issue. I am using a Markdown widget and fetching data through an entity alias.

I am displaying an asset list, but the data returned by the widget is capped at 1024 entities, whereas the actual total count is around 5000 assets.

It seems the widget binding or alias query has an implicit limit of 1024 items.

I am using **4.2.1.1PE**

**Comment by AlexDoanTB** [comment]
> It seems the widget binding or alias query has an implicit limit of 1024 items.
> 
> I am using **4.2.1.1PE**

The limit is configurable. 

<img width="725" height="609" alt="Image" src="https://github.com/user-attachments/assets/c9779be7-aaba-4d3e-998f-58bed2c9a8ab" />

**Comment by omkarfoodef** [comment]
Thanks @AlexDoanTB for your help!
