### ISSUE TITLE
[Bug] setvalue fonction not reached when uncheck a boolean

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6405]
**Describe the bug**
I use the Update Multiple Attributes widget on current user to set up filter.
I need to change an hidden field when I modifiy the value of a checkbox. 
I want to use the setvalue fonction but it's called only when I check the box. 
When I uncheck the box the fonction isn't called.

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser : firefox
* Version : 99

**To Reproduce**
1. Add a widget Update Multiple Attribute
2. Create à Field with the type Boolean (checkbox or switch)
3. add a line in setvalue fonction like console.log("set",  value, originValue);
4. Check the box and save
5.  Uncheck the box and save
6. Check again and save.

**Expected behavior**
We should see  in the console
set    true                    < empty string>
set   < empty string>  true
set    true                     < empty string>

But we don't see the second line (see the screenshot)

**Screenshots**

![image](https://user-images.githubusercontent.com/103430329/162993230-7ac4d814-f3da-49c1-beac-a65bef0efb64.png)

**Comment by vvlladd28** [comment]
Hi @liotys,
An error has occurred in the function you provided. The function needs always return a value.
```javascript
console.log("set", value, originValue);
return originValue;
```

**Comment by liotys** [comment]
Thanks a lot @vvlladd28 for your answer.
I do the correction but I still have the same behaviour.
![image](https://user-images.githubusercontent.com/103430329/163060460-45948385-d6db-40af-8806-24bd9f9246ef.png)

**Comment by JacksonBowe** [comment]
@liotys Could you try removing the comments at the bottom?

**Comment by liotys** [comment]
@JacksonBowe , you're totaly right, thanks a lot. I will never put anymore comments in my code :-). 
I note than now TB use "false" instead of "< empty string >".
![image](https://user-images.githubusercontent.com/103430329/163120848-a43474e4-8a6d-40e5-b2e2-2c701e1a1386.png)

May I ask you for a hint?
With my checkbox, I change the value of a target field with "data[index of the target].dataKey.value = '%';" in the setfonction of the checkbox.
I've found that I must use the getfunction of the target to put this value in the target field. I see this value in the form but it's not save in the current user field corresponding. 
How can I simulate a save action on the target field ?
Thanks for your answer.

**Comment by JacksonBowe** [comment]
@liotys Comments are only bad below the return statement. I don't know why, same happens in Data Converters.

Regarding your follow up question, I'm afraid I am not familiar with the widget you're using. My TB version is not up to date so I have not had a chance to use the new widgets.

**Comment by liotys** [comment]
Thank you very much for your answer, I will ask my question as a new issue.
