### ISSUE TITLE
does thingsboard project has milestone story

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6406]
does thingsboard project has milestone story, so i can see thingsboard's future plan

**Comment by qwykx** [comment]
Yes, have a look at:

- https://thingsboard.io/docs/reference/roadmap/
- https://thingsboard.io/docs/pe/reference/roadmap/

**Comment by john1337** [comment]
> Yes, have a look at:
> 
> * https://thingsboard.io/docs/reference/roadmap/
> * https://thingsboard.io/docs/pe/reference/roadmap/

thanks,it's a relative short term roadmap
