### ISSUE TITLE
does thingsboard have any plan to make all tenants use same rule chain

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6407]
**Component**

 * Rule Engine

**Description**
now all versions of thingsboard is using rule chain for one tenant(rule chain is tenant isolated),but in some cases, we want all tenant to use one rule chain,which is much convient.
so i'm wondering do you guys have any plan to develop such feature to use same rule chain for all tenants,if not why?

**Comment by john1337** [comment]
why isolate rule chain from every tenant?

**Comment by john1337** [comment]
now message flow in thingsboard is app-actor->tenant-actor->rulechain-actor->rulenode-actor,in some way which all tenants use the same rule-chain config, i think removing tenant-actor is much better,that means rule-chain config is moved to system config not tenant configuration

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
