### ISSUE TITLE
[Feature Request] Multi Select attribute based on Alias in Update Multiples Attributes widget

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6414]
**Is your feature request related to a problem? Please describe.**
When we use the Update Multiples Attributes widget on current user to use a dynamic filter, we often need to select multiples values to build a list used with a "in" clause of a filter. We usually have the possible values in an Alias.

**Describe the solution you'd like**
This solution could be a multi select list like in Excel build from an Alias (see the screenshot below).
The result is a string in interaction with the list.
It would be great if we could sort the list.

**Describe alternatives you've considered**
Now I use a simple string attribute where users have to write the list manualy..
![image](https://user-images.githubusercontent.com/103430329/163395635-5f1851f3-cc04-49da-a273-b869879e93d7.png)

**Additional context**
It could look like
![image](https://user-images.githubusercontent.com/103430329/163392889-6899ad07-117b-4bfd-a89a-764cc9891b0f.png)

**Comment by ssakharova** [comment]
Hello @liotys,

This functionality is not currently available in ThingsBoard. However, we have a similar feature request in our backlog that is awaiting developer review.

There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
