### ISSUE TITLE
[Question] Find device by scaning QR code and making relation with asset

### ISSUE THREAD

**Issue by milosilic** [thingsboard/thingsboard#6417]
**Component**
 * UI

**Description**

I have created table widget and applied QR code mobile action. 

I want to scan QR code on the device, using the provided  Thingsboard mobile app and create the relation with asset. 

How can this be done? 

I found only this example for QR code reading : 

```
showQrCodeDialog('Bar Code', code, format);

function showQrCodeDialog(title, code, format) {
  setTimeout(function() {
    widgetContext.dialogs.alert(title, 'Code: ['+code+']<br>Format: ' + format).subscribe();
  }, 100);
}

```

But I cannot figure out how to use **code** argument from **showQrCodeDialog** and make relation with asset which is already created on the Thingsboard cloud platform .

Thanks in advance,
Miloš

**Comment by devaskim** [comment]
Hi
It is not an answer to your question but you could try [my QR widget](https://github.com/devaskim/awesome-thingsboard/tree/main/widget/qr-code-scanner). It works both on phone and desktop.

**Comment by LuMagAnd** [comment]
> Hi It is not an answer to your question but you could try [my QR widget](https://github.com/devaskim/awesome-thingsboard/tree/main/widget/qr-code-scanner). It works both on phone and desktop.

Nice widget!
Is it possible to add the Aztek code standard to the widget as well?

**Comment by devaskim** [comment]
> Is it possible to add the Aztec code standard to the widget as well?

No, I think. The widget uses third party [qr-scanner](https://github.com/nimiq/qr-scanner) library which doesn't support any other than QR code,as I know

**Comment by LuMagAnd** [comment]
@devaskim Thanks for quick answer. I see. 
Next question. :)
Do you have an example how to save the scanned QR-code data info to an attribute/telemetry on an asset?
The widget has no possibility to map an entity throw entity aliases, so I suppose it must be done via javascript in box "function (qrCode, ctx)".

**Comment by devaskim** [comment]
This version of the widget lets you specify entities
[qr_code_scanner.json](https://github.com/thingsboard/thingsboard/files/13907707/qr_code_scanner.json)

> Do you have an example how to save the scanned QR-code data info to an attribute/telemetry on an asset?

No. There is `attributeService` in `ctx`. And here is its [saveEntityAttributes API](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts#L81). More information how to save data to attributes you can find in others issues.

**Comment by LuMagAnd** [comment]
@devaskim 
Thank you very much!

**Comment by Ultrazombie** [comment]
Closed due to inactivity
