### ISSUE TITLE
[Question] Can I upload a csv or xls file with data to show on Thingsboard?

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#6419]
Is it possible to upload telemetry data manually to show them in a graph? If so how can I do it?

**Comment by epalchenko** [comment]
Hello,
You can post telemetry data to the device using the following link: https://thingsboard.cloud/swagger-ui/#/telemetry-controller/saveEntityTelemetryUsingPOST
Alternatively, you can use bulk import as described here: https://thingsboard.io/docs/pe/user-guide/bulk-provisioning/
Please note that this method does not support saving timestamps.

For more specific requirements, you can also develop a custom script tailored to your needs.
