### ISSUE TITLE
[Bug] Attributes (JSON): save button is not active in "Edit JSON"

### ISSUE THREAD

**Issue by kalutkaz** [thingsboard/thingsboard#6423]
Steps to reproduce:

1)Go to the device
2)Go to the Attributes tab → Server attributes
3)Click on the plus icon and select JSON → specify the value, example: ["111","222"]
4)Click on the icon for Edit JSON and specify the value

![image](https://user-images.githubusercontent.com/43555187/163579228-28cc8953-9b57-40c2-ad92-40e152440afc.png)

![image](https://user-images.githubusercontent.com/43555187/163579265-808afe19-319a-4df2-b052-2b223f75cb39.png)

expect: can save changes

result: the button is not active

**Comment by maksonlee** [comment]
Not a valid JSON string? Try the following,

{"data": ["111", "222", "333"]}
