### ISSUE TITLE
[Question] show SnackBar in thingsboard widget

### ISSUE THREAD

**Issue by qwerty13** [thingsboard/thingsboard#6426]
**Component**
 * Generic

**Description**
How can we show a message in snackBar style? i test some examples from angular UI and did not worked, then i search "snackbar" in repository and see some constructor in toast.directive.ts; they not worked too...

what's the right object and statement for this?

**Environment**
 * ThingsBoard: 3.3.4.1

**Comment by serfreeman1337** [comment]
https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/widget-component.models.ts#L300
```javascript
self.ctx.showSuccessToast('Success?', 1000, 'bottom', 'left', self.ctx.toastTargetId);
```
