### ISSUE TITLE
Server attribute inactivityTimeout

### ISSUE THREAD

**Issue by rochakgithub** [thingsboard/thingsboard#6428]
Server attribute "inactivityTimeout" not working as the given time. I have set it to 50 seconds but still it takes 2 min or sometime even more time to get offline (active: false)

**Comment by devaskim** [comment]
Did you set up `inactivityTimeout` to 50 or 50 000 ?

**Comment by rochakgithub** [comment]
> Did you set up `inactivityTimeout` to 50 (wrong) or 50 000 (ok) ? I haven't yet tested when `active` has been changed its value, but I am using [Message Type Filter Node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#message-type-switch-node) and Activity/Inactivity events work in expected way.

Yes, I have used 50000 but it is not working properly.

**Comment by mde2017** [comment]
Hi @rochakgithub,

there is another parameter relevant for device state connectivity:

![image](https://user-images.githubusercontent.com/25298332/163941777-5ea1682a-a747-476d-92e3-a448a03389b2.png)

Each 60 seconds the checks are performed whether a device went offline or online. You may try to decrease this value in your case of 50 seconds timeout and set it to e.g. 30 seconds.

**Comment by rochakgithub** [comment]
Hi @mde2017 
Thanks for helping.
