### ISSUE TITLE
Suggestion: use a template for issues ;-)

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#643]
## Expected Behaviour

It is easy to see what the issue is about, the environment (version, database used, docker or manual install), what is expected behaviour and what is going wrong...

## Current Behaviour

Some issues are one big random guess... Something is wrong, but which version is affected etc. is in many cases not mentioned. Difficult to help & solve.

## Possible Solution

Use a template, such as this one to aid in structuring issues.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your (Docker) Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* ThingsBoard `thingsboard version` (e.g. CE 1.4 or PE 1.4):

* Database used `database used` (e.g. HSQLDB, Cassandra, Postgres):

* Docker version `docker version` (e.g. Docker 17.12 ):

* Are you using Docker Swarm or Kubernetes?

* Link to your project or a code example to reproduce issue:

## Diagnostic information

[ThingsBoard Issue Template.txt](https://github.com/thingsboard/thingsboard/files/1800542/ThingsBoard.Issue.Template.txt)

**Comment by Delapouite** [comment]
Issue templates have been added to the repo about one year ago: https://github.com/thingsboard/thingsboard/tree/master/.github/ISSUE_TEMPLATE 

@MarsWarrior do you mind closing this issue please? Thanks

**Comment by MarsWarrior** [comment]
Great!
