### ISSUE TITLE
[Bug] Generate report  rule node gives multiple output  for a  single input

### ISSUE THREAD

**Issue by Andhuooo** [thingsboard/thingsboard#6430]
![image](https://user-images.githubusercontent.com/99332219/163763057-b63a88ec-d2cf-4e6c-9422-76e0eeee350b.png)

**Comment by Ultrazombie** [comment]
Please provide your rule chain to look at your logic and investigate this case.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
