### ISSUE TITLE
[Bug] After changing 'Role' can`t save form (button 'Save' inactive)

### ISSUE THREAD

**Issue by ArtemDzhereleiko** [thingsboard/thingsboard#6435]
**Describe the bug**
1. Go to the Dashboard groups → select any Dashboard;
2. Click on the "Object group details" pencil button;
3. Choose “Permissions“;
4. Change Role data for example "Entity Group Write User" to "Entity Group Read-only User";
5. I can't save changes right away. The "save" button is not active. Although user group owner and user group are selected. All fields are filled;
6. Only after I delete and re-specify the User group owner and select the User group (same data or different if needed) I can save the changes.

Expected: The "Save" button is active immediately after changing the "Role" data and you don't need to re-fill the rest of the fields if they are not empty.

Result: After changing the "Role" data, the "save" button is not active. You need to re-fill all fields. Although they are filled in.

**Screenshots**
![image](https://user-images.githubusercontent.com/83352633/163802800-d409b3c3-026f-405a-b43d-75fafcb08b82.png)
![image](https://user-images.githubusercontent.com/83352633/163802837-7f63dc1a-f466-498d-8e3b-7959762f2b47.png)

**Comment by vvlladd28** [comment]
Hi @Backdraft007,
This bug is reproduced in TB 3.3.4
