### ISSUE TITLE
[Bug] Post processing functions not applied to Exported data.

### ISSUE THREAD

**Issue by PopoTheSapien** [thingsboard/thingsboard#6438]
The post processing function not applied to Exported data.  Instead the raw data without post processing is shown.

- Standalone server deployment using Portainer
- ThingsBoard Version: 3.2.2 PE
- OS Name and Version: Ubuntu 20.04.2 LTS

**To Reproduce**
1. Export data from Entities table to CSV
2. Open the file
3. Note.. Post processing function is not applied to data in the export.

**Expected behavior**
Post processing functions should be applied to export data.

**Comment by ashaforost** [comment]
Hi @PopoTheSapien ,

This problem was fixed in the latest versions of thingsboard. Please consider upgrading to the thingsboard v3.3.4.1
[Upgrade Instructions](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/)
