### ISSUE TITLE
Create rabbitmq quorum queues instead of classic.

### ISSUE THREAD

**Issue by arkastratuscent** [thingsboard/thingsboard#6445]
RABBITMQ queues get created by default in classic mode.
Is there a way to change this to type: streaming or quorum by default?

 * OS:  ubuntu 20.04
 * ThingsBoard: 3.3.3

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
