### ISSUE TITLE
how to publish a json payload (complexy telemetry) using thingsboard-python-client-sdk?

### ISSUE THREAD

**Issue by sebastianmenoni** [thingsboard/thingsboard#6452]
In the MQTT API documentation, it is mentioned that: "Key is always a string, while value can be either string, boolean, double, long or JSON."

ref: https://thingsboard.io/docs/reference/mqtt-api/

Regarding this point, I don't see that the Python library supports a JSON "type" value.

reference:

> `KV_SCHEMA = {
>   "type": "object",
>   "patternProperties":
>   {
>   ".": {"type": ["integer",
>   "string",
>   "boolean",
>   "number"]}
>   },
>   "minProperties": 1,
> }`

Additionally, I did some tests to validate this, and when I try to send a payload directly:

```
payload = {'someNumber':42,'someArray':[1,2,3],'someNestedObject':{'key':'value'}}
telemetry = {'newall': payload}
client.send_telemetry(telemetry,quality_of_service=1)
```

I get the following error message:

```
Failed validating 'anyOf' in schema['items']:
{'anyOf': [{'additionalProperties': False,
'properties': {'ts': {'type': 'integer'},
'values': {'minProperties': 1,
'patternProperties': {'.': {'type': ['integer',
'string',
'boolean',
'number']}},
'type': 'object'}},
'type': 'object'},
{'minProperties': 1,
'patternProperties': {'.': {'type': ['integer',
'string',
'boolean',
'number']}},
'type': 'object'}]}

On instance[0]:
{'newall': {'someArray': [1, 2, 3],
'someNestedObject': {'key': 'value'},
'someNumber': 42}}
```

Also, when I send my JSON payload as a string:

```
payload = {'someNumber':42,'someArray':[1,2,3],'someNestedObject':{'key':'value'}}
MQTT_MSG=json.dumps(payload)
telemetry = {'newall': payload}
client.send_telemetry(telemetry,quality_of_service=1)
```

The message is saved in Thingsboard as a string.

Additionally, validate the posting of a JSON payload as follows:

`mosquitto_pub -d -h "ip" -t "v1/devices/me/telemetry" -u "token" -f "telemetry-data-as-object2.json"`

My goal is to be able to publish my payload as JSON to be able to visualize it in the same way when I check the key through the REST AP (see images to visualize the difference)

python version: 3.9.1
Thingsboard version: 3.2.2PE-1
![01](https://user-images.githubusercontent.com/32903159/164333769-25eeb8ff-0da0-4a70-9771-2b94d0e81c26.png)
![02](https://user-images.githubusercontent.com/32903159/164333773-e42cfc2e-4f4f-4345-886d-7a1808ce6001.png)

**Comment by sebastianmenoni** [comment]
Apparently it is not possible to use the python SDK developed by ThingsBoard to send a "complex" payload to ThingsBoard

The only way I have found to solve the problem was to do it directly with the paho library


```
import paho.mqtt.client as paho      #mqtt library
from tb_device_mqtt import TBDeviceMqttClient, TBPublishInfo #DONT WORK FOR COMPLEX PAYLOADS AS JSON 
import json 

ACCESS_TOKEN=''                 #Token of your device
broker=""                              #host name
port=1883                              #data listening port

def on_publish(client,userdata,result):             #create function for callback
    pass
client1= paho.Client("control1")                    #create client object
client1.on_publish = on_publish                     #assign function to callback
client1.username_pw_set(ACCESS_TOKEN)               #access token from thingsboard device
client1.connect(broker,port,keepalive=60)           #establish connection

payload ={
  "newall": {
    "someNumber": 42,
    "someArray": [1,2,3],
    "someNestedObject": {"key": "value"}
  }
}
"

MQTT_MSG=json.dumps(payload)

print(payload)

ret= client1.publish("v1/devices/me/telemetry",MQTT_MSG,1) #topic-v1/devices/me/telemetry
```

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
