### ISSUE TITLE
Can you have a widget/post processing function that can retrieve the first value of the week and also the latest value?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6457]
**Component**

 * UI
 * Generic

**Description**
Hi all,

I have a data source that is acumulative. I'm trying to show the difference between the latest value and the first value of the week. Is this at all possible to do?

Ideally this would be independent of the time range selection on the gui. I'm trying to get it done in a post processing function but I'll write a widget if it's not possible there.

**Environment**
 * OS:  Linux
 * ThingsBoard: Latest
 * Browser: any

**Comment by X1folta** [comment]
When starting your widget as a time series widget and declare:

`    self.ctx.$scope.data = self.ctx.defaultSubscription.data;
    let data = self.ctx.$scope.data;
    console.log(data[0].data)`
    
you'll see in your console a lot of arrays with timestamp and value; how many it shows is limited by the dashboard timewindow. If your dashboard is already showing data for a specific week perhaps this way you can fetch the according values you need. Sorry for not being able to deliver a thorough answer, but maybe this helps.

**Comment by OzyOzk** [comment]
> When starting your widget as a time series widget and declare:
> 
> ` self.ctx.$scope.data = self.ctx.defaultSubscription.data; let data = self.ctx.$scope.data; console.log(data[0].data)`
> 
> you'll see in your console a lot of arrays with timestamp and value; how many it shows is limited by the dashboard timewindow. If your dashboard is already showing data for a specific week perhaps this way you can fetch the according values you need. Sorry for not being able to deliver a thorough answer, but maybe this helps.
> 
> (Edit: Sorry just saw that it should be indepent of time range selection, but you can still foster through the arrays searching for the specific timestamps. My personal recommendation though for your problem is to make a rulechain calculating the deltas according to your needs and displaying that value. )

I thought about using rule chains, but I don't want to add any extra telemetry data. I've looked at some custom widgets and I think it's possible. Now all I need is a logic for finding the first telemetry of the week.

**Comment by epalchenko** [comment]
Hello,
You can implement your request by developing a custom widget. Please familiarise yourself with the Widget Development Guide: https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
