### ISSUE TITLE
Problem to import SecurityContextHolder

### ISSUE THREAD

**Issue by krzischp** [thingsboard/thingsboard#646]
I want to modify the file DashboardServiceImpl.java and I need to get access to the user email.
So I first added the line
import org.springframework.security.core.context.SecurityContextHolder;
and I added, in the file /dao/pom.xml, the following dependency:
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>

But I still get, when compiling with maven, the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project dao: Compilation failure
[ERROR] /home/thingsboard/dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java:[46,48] error: package org.springframework.security.core.context does not exist
 

I'm really new to Java Spring. How can I get this error away?
Thanks in advance!

**Comment by mp-loki** [comment]
Make sure that you have added Spring Security maven dependency in pom.xml
