### ISSUE TITLE
[Feature request] Data decimation/downsampling support

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6470]
**Component**
 * Generic

**Description**
Does TB has the mechanism of data decimation? I mean decreasing the amount of stored data older than some time ago. It may be average aggregation.

**Comment by mde2017** [comment]
Hi @devaskim,

you may have a look at the TTL configuration parameters:
https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters

![image](https://user-images.githubusercontent.com/25298332/165035171-b56e029e-a616-4288-b0bd-4a369b033cbf.png)


You can define expiration intervals for automatically deletion of e.g. timeseries or debug events.

**Comment by devaskim** [comment]
Thanks @mde2017 but it is all about total data deletion.
I want to store all data points only for the last month. Then store only average value per day and etc.

**Comment by mde2017** [comment]
Now I see what you're up to.
I doubt that this mechanism is already implemented. But you could probably realize this via REST API calls and/or Database queries.

Or make a new feature request.
