### ISSUE TITLE
[Question] Device search query based on attributes or additional info

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6472]
**Component**
 * Generic

**Description**
At the [Swagger]() page I found the (Find by query)[API] but as I see it supports only relation search criteria. 
Does TB has any API to search for devices by such criterias as attributes (I am interested in ***geo coordinates*) or device's additional info? If no, could someone point me out from where I would start to develop such capability?

**Comment by qwykx** [comment]
Hello @devaskim 

You can use the _entity-query-controller_ for such.

Have a look at [Swagger Docs - entity-query-controller](https://demo.thingsboard.io/swagger-ui/#/entity-query-controller/findEntityDataByQueryUsingPOST)

Cheers

**Comment by devaskim** [comment]
Thanks @qwykx just today I succeeded in using complex dynamic filters. More details I put [here](https://github.com/thingsboard/thingsboard/issues/6429)
