### ISSUE TITLE
[Bug] thingsboard (site) shows 'string' values as 'numeric': "566e8" -> 5.66E10

### ISSUE THREAD

**Issue by rduivenvoorde** [thingsboard/thingsboard#6477]
**Describe the bug**

Having thingsboard running to monitor some sensors (via mqtt) and thingsboard gateway, one of the attributes we sent is a custom 5-character-wide 'hostname'-hash

In a dashboard we show it as a column so you can easily search for a certain device:

![gnome-shell-screenshot-dkwfy0](https://user-images.githubusercontent.com/731673/165091869-de2368f6-0ded-4a58-a138-0c7cedfe3351.png)

But then we found that certain strings looked funny:

```
3935.0
5.66E10
```

Upon searching for the real value it appeared:

```
3935.0   ->  "3935d" 
5.66E10 -> "566e8"
```

So to us it looks like that 'something' is trying to view the strings as numbers (the d is read as a double value, and having an e in it makes it a scientific notation...)...

When you use the cli to read out these attributes, they are being returned as the right *strings*.

Thinking I maybe configured the gateway wrong, and that I maybe configured is as double typed, was also NOT the case:

```  
...
          {
            "type": "string",
            "key": "system.hostname",
            "value": "${machine_id_short}"
          }
...
```
Is it possible that the site or the script of the site is trying to cast values to numeric values?

**Your Server Environment**

* own setup
  * docker deployment
  * Thingsboard 3.3.1, Gateway 3.0.1
  * Host is centos, but as said, running from containers

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Linux/Debian and Window
* Browser Firefox and Chromium
* Version latest
* 
**Your Device**

* Connectivity
  * MQTT
  * Gateway

**To Reproduce**
1. Define an attribute in the gateway 'system.hostname'
2. Create a Entities widget to show that attribute
3. Sent for a sensor the value "abcd" for system.hostname
4. See it is shown (OK) as abcd
5. now sent "566e8"
6. see it is shown as 5.66E10

See below

![gnome-shell-screenshot-887f07](https://user-images.githubusercontent.com/731673/165094092-6661f8d1-cce9-4324-88ee-6305451a3c57.png)

(Note: green background are 'active' devices, mostly a vanilla Thingsboard instance with non custom widgets or configuration)

**Additional context**

**Comment by skewty** [comment]
Would the `JSON_TYPE_CAST_ENABLED` value also affect Boolean values as provided to widgets in `dataChanged` method?  I am seeing my attributes of type Boolean come in as `"false"` or `"true"` (strings with quotes).

**Comment by ashaforost** [comment]
Yes, this setting prevents thingsboard from trying to transform any string value to another type.
