### ISSUE TITLE
How to Deploy our Customize Thingsboard to Kubenetes Engine?

### ISSUE THREAD

**Issue by Firdauzfan** [thingsboard/thingsboard#648]
After make docker image of cassandra, cassandra-setup, application and zookeeper from my custom thingsboard. I tried to deploy that to Kubernetes Engine, there's no error, but not running well.

Here is my command for yaml from my github:

curl -L https://raw.githubusercontent.com/Firdauzfan/ThingsboardGSPE/master/docker/k8s/common.yaml > common.yaml

curl -L https://raw.githubusercontent.com/Firdauzfan/ThingsboardGSPE/master/docker/k8s/cassandra.yaml > cassandra.yaml

curl -L https://raw.githubusercontent.com/Firdauzfan/ThingsboardGSPE/master/docker/k8s/zookeeper.yaml > zookeeper.yaml

curl -L https://raw.githubusercontent.com/Firdauzfan/ThingsboardGSPE/master/docker/k8s/tb.yaml > tb.yaml

curl -L https://raw.githubusercontent.com/Firdauzfan/ThingsboardGSPE/master/docker/k8s/cassandra-setup.yaml > cassandra-setup.yaml

and here is my docker image: https://hub.docker.com/u/firdauzfanani/

Example: when i run command kubectl create -f cassandra.yaml, cassandra engine just show running but not ready. ->> https://i.stack.imgur.com/MXmaB.jpg

**Comment by Karabiy** [comment]
you can refer to this link regarding on how to deploy the ThingsBoard in the Kubernetes: https://thingsboard.io/docs/user-guide/install/cluster/minikube-cluster-setup/
