### ISSUE TITLE
[Question] Rule Chain : One rule node output is success but I have no events coming in the next node

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6482]
Hello,

I'm currently using the transformation script rule node to build a Json and use it in the next rule nodes.
The thing is I have no event coming in the next rule nodes, even if I have event coming out my transformation script rule node with relation type success. Of course, my rule nodes are linked with success arrows, and each rule node has debug mode on.

Here is the part where the message is not coming from one node to another in my Rule Chain : 

![CaptureRuleChainBug1](https://user-images.githubusercontent.com/95343678/165281649-33f37b3a-84d1-4968-8287-1c0a2824c381.png)

Here is the debug of the node number 1 : 

![CaptureRuleChainBugDebug1](https://user-images.githubusercontent.com/95343678/165281668-8707679b-eb69-426d-9805-5c7dfd8a14bb.JPG)

Here is the debug of the node number 3 : it is empty. And I have the same thing in the debug of the node number 2.

![CaptureRuleChainBugDebug3](https://user-images.githubusercontent.com/95343678/165281684-9b207115-dc29-430c-9179-93566a960e9e.JPG)

Does anyone know if i'm doing something wrong, or if it is a bug ?
Best regards,

Lucas

**Comment by mykhailokornieiev** [comment]
Hi. As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
