### ISSUE TITLE
[Question] It is possible to put the Device Selection in the dashboard URL?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#6484]
* UI

**Description**
Can I make an URL of the dashboard + device selection to be put in an QR code?
The reason is that a QR code on the device itself can then easily get you to the right device on the dashboard.

I know you could make a new dashboard for each device of the customer but that's not an acceptable solution.

**Environment**
 * OS: Linux LTS
 * ThingsBoard: 3.3.3

**Comment by KenSense** [comment]
I tried to add the Base64 code like in your example but it doesn't change anything to the page:
I tried this, it's only for the default state page, any ideas?

[{"id": "default","params": {"entityId": {"id": "4b516600-6903-11ea-b5c1-6110c86f649e","entityType": "DEVICE"},"entityName": "tempsensor0001","entityLabel": ""}}]

[
	{
		"id": "default",
		"params": {
			"entityId": {
				"id": "4b516600-6903-11ea-b5c1-6110c86f649e",
				"entityType": "DEVICE"
			},
			"entityName": "tempsensor0001",
			"entityLabel": ""
		}
	}
]

**Comment by mde2017** [comment]
You have also set an Entity Alias "Entity taken from dashboard state parameters" to access the State parameter in the widgets?

In my example I used a very simple parameter. In your case it could more complex. Have you checked the structure of the state in your case? You can decode it from base64.

**Comment by epalchenko** [comment]
Hello,
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
