### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by DaXian459** [thingsboard/thingsboard#6489]
**We are connected to a PLC control cabinet composed of multiple devices. When uploading telemetry data, we can only upload it into one device. Is there any way to separate the devices in the PLC control cabinet into separate devices**

**Comment by dhaval2017** [comment]
@DaXian459 
Use gateway api here is the documentation

https://thingsboard.io/docs/reference/gateway-mqtt-api/

**Comment by DaXian459** [comment]
**Sorry,Is there any way to make them post after uploading to TB**

**Comment by devaskim** [comment]
Use the [Change originator](https://devaskim.github.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator) node of Rule chains, where new originator will be your end device not PLC.

**Comment by DaXian459** [comment]
> * Use the [Transformation node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node) to change message metadata where device id locates.
> * Try to use the [Change originator](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator) node of Rule chains.

Thank you very much。
