### ISSUE TITLE
Simple click button

### ISSUE THREAD

**Issue by AvishekHardin** [thingsboard/thingsboard#649]
Good day Everyone.. I wanted to use a simple click button (similar to the one used in HTML), is there any way to get this done in TB. Infact, i wanted to use this button to trigger messages in MQTT. Many thanks for your help.

**Comment by vparomskiy** [comment]
You can find an example in this tutorials
https://thingsboard.io/docs/samples/esp8266/gpio/
https://thingsboard.io/docs/user-guide/rpc/
https://thingsboard.io/docs/user-guide/ui/widget-library/#gpio-widgets

**Comment by AvishekHardin** [comment]
Hello Vparomskiy,

thanks for your help, I already consulted the provided link. thanks for your help.
However, what i wanted to achieve is to create a simple button using "add widgets" and wanted to use this button to trigger MQTT messages. picture like below.

![image](https://user-images.githubusercontent.com/7479253/38183279-34e7a938-3650-11e8-927c-0a3a5fcf9280.png)

Thanks for your help.

**Comment by amizer12** [comment]
Up-voting this - we need a simple button that we can assign actions to - there is no way to build a working control dashboard that is mobile and touchscreen friendly with Thingsboard without a simple configurable button ( to increase decrease specific attribute, trigger function, run root chain, whatever ).

**Comment by dhaval2017** [comment]
here is custom widget I have made for action button
you can import it in widgets and set action in dashboard to perform when button is pressed.

[actionbutton.zip](https://github.com/thingsboard/thingsboard/files/6798983/actionbutton.zip)

**Comment by rwanrooy** [comment]
> here is custom widget I have made for action button you can import it in widgets and set action in dashboard to perform when button is pressed.
> 
> [actionbutton.zip](https://github.com/thingsboard/thingsboard/files/6798983/actionbutton.zip)

This button works great. Is there a way to make 4 of these buttons next to eachother in mobile view? It seems that there can be only one column so widgets next to eachother are not accepted.
