### ISSUE TITLE
[Question] Need help to add multi json value in device to dashboard

### ISSUE THREAD

**Issue by yingkhun** [thingsboard/thingsboard#6490]
**Component**

 * UI

**Description**
* Need help to add multi json value in device to dashboard
image : https://imgur.com/3I9uNh7  << multi json look like this
image : https://imgur.com/owrY2EU  << I try to added but not work

**Environment**

 * OS:  window 10
 * ThingsBoard: 3.3.4.1
 * Browser: chrome

Thanks

**Comment by qwykx** [comment]
Hello @yingkhun add the same key multiple times to your widget and use data processing functions to return only one of the keys in your json structure.

As an alternative you could use a rule chain to split the values.

Cheers

**Comment by yingkhun** [comment]
> Hello @yingkhun add the same key multiple times to your widget and use data processing functions to return only one of the keys in your json structure.
> 
> As an alternative you could use a rule chain to split the values.
> 
> Cheers

I'm really new here sorry for ask but how to use data processing functions to return only one of the keys in your json structure.

**Comment by qwykx** [comment]
Use this snippet and change it for the value A2 accordingly.

The `parseInt()` is necessary unfortunately - you might have to change it to float if needed.

```JavaScript
let json = JSON.parse(value);

return parseInt(json.A1);
```

**Comment by yingkhun** [comment]
> Use this snippet and change it for the value A2 accordingly.
> 
> The `parseInt()` is necessary unfortunately - you might have to change it to float if needed.
> 
> ```js
> let json = JSON.parse(value);
> 
> return parseInt(json.A1);
> ```

thank you :D
