### ISSUE TITLE
[Question] Default panel in web but not in app

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/thingsboard#6491]
* UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Hello,

I have a temperature and humidity system and I want the clients to only be able to see the dashboard without any other options on the left in web mode or for the dashboard list to appear, simply put one by default.
I know what I can do with the default Panel option, the issue is that I would like that in the application that is not applied and there the dashboard could be selected since with the icons it is more organized. Can that distinction be made between web and apps?

Thank you very much

**Environment**
 * OS:  Docker
 * ThingsBoard: latest

**Comment by ssakharova** [comment]
Hello @Ataraxiall,

You could create separate dashboards for mobile mode and desktop modes.

When creating a dashboard for desktop mode, you can hide the dashboard in a mobile application, for example.
![image](https://github.com/user-attachments/assets/95c811e2-16ca-4ffe-8124-c3701e4e0f8d)

Another solution is to create one dashboard for both mobile and desktop modes. You can configure this dashboard by choosing the appropriate widgets, such as the navigation cards widgets. Then, you can choose what widgets should be displayed in desktop mode and what widgets should be displayed in mobile mode. 
![image](https://github.com/user-attachments/assets/a17f203b-10c6-41c9-b5cd-b8d1bb2c70a0)

**Comment by ssakharova** [comment]
Closed due to inactivity.
