### ISSUE TITLE
Lost Telemetry [Bug] 

### ISSUE THREAD

**Issue by freebooterish** [thingsboard/thingsboard#6492]
**Describe the bug**
I use the "monolith"deployment mode. There are 400 devices uploading messages, 90000 messages and 300000 data points per hour. I choose one of the devices to test and send 1000 messages. When the sending interval is 100ms, MQTT msgs is sent successfully, but when the sending interval is 10ms, although all messages receive mqtt ACK, but thingsboard only saves about 200 messages. I open the save telemetry “debug mode” to observe whether the messages arrived.
Thank you!

**Your Server Environment**

* own setup
  * cloud infrastructure
  * 3.3.3
  * ubuntu 20.04

**Your Device**

* Connectivity
  * MQTT

**Comment by devaskim** [comment]
Did you check logs? Maybe there are some errors?

**Comment by mde2017** [comment]
Also have a look at the troubleshooting guidelines to determine what's causing the issue:
https://thingsboard.io/docs/user-guide/troubleshooting/

**Comment by freebooterish** [comment]
> Did you check logs? Maybe there are some errors?

Thank you,Sir
[logs.txt](https://github.com/thingsboard/thingsboard/files/8572919/logs.txt)
.

**Comment by devaskim** [comment]
It isn't full log, but even there you can find what you have database issues or it is a result of something else.
```
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 42064ms.
```
Reattach logs. please

**Comment by freebooterish** [comment]
> It isn't full log, but even there you can find what you have database issues or it is a result of something else.
> 
> ```
> Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
> Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 42064ms.
> ```
> 
> Reattach logs. please
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/8579933/thingsboard.log)
Dear,sir
I reinstall Thingsboard and only one device,I send 1093 messages with  interval is 10ms, although all messages receive mqtt ACK(with waireshark monitor), but thingsboard only saves about 147 messages. I open the save telemetry “debug mode” to observe whether the messages arrived. the whole log is attached.
Thank you !

**Comment by freebooterish** [comment]
> timeoutMsgs

Thank you,sir,when I send msg with with interval is 10ms, the log report:2022-04-28 13:56:34,943 [TB-Scheduling-7] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [1
092] successfulMsgs = [137] timeoutMsgs = [955] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterat
ions = [0] failedIterations = [7]
It seems to mean that a large number of messages have timed out.
Do you have any good ideas? Thank you.

**Comment by devaskim** [comment]
I guess you need to increase one or several [SQL configuration parameters](https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters), such batch size, timeouts and delays.

**Comment by freebooterish** [comment]
> I guess you need to increase one or several [SQL configuration parameters](https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters), such batch size, timeouts and delays.

Dear,sir
I adjust some SQL configuration parameters:
export ACTORS_RULE_JS_THREAD_POOL_SIZE=900
export USE_LOCAL_JS_SANDBOX false=false
export MQTT_MSG_QUEUE_SIZE_PER_DEVICE_LIMIT=500
export SQL_TS_BATCH_SIZE=100000
export SQL_TS_BATCH_MAX_DELAY_MS=1000
#export SQL_TS_BATCH_THREADS=8
#export SQL_TS_LATEST_BATCH_SIZE=100000
export SQL_TS_LATEST_BATCH_MAX_DELAY_MS=1000
#export SQL_TS_LATEST_BATCH_THREADS=16
#export SQL_TIMESCALE_BATCH_THREADS=16

BUT But it didn't work，still lose data。
Best regards.

**Comment by pon0marev** [comment]
To investigate timeouts, processing failures, and startup failures of rule chain nodes you should inspect your log file.
To determine which rule nodes fail on startup, you can use a script to create a query in the database:
```
LOG_FILE=thingsboard.2024-05-07.4.log
FILENAME=rows.txt
export QUERY='select rule_node.name as rule_node_name, rule_chain.name as rule_chain_name, tenant.title as tenant_name from rule_node join rule_chain on rule_chain.id=rule_node.rule_chain_id join tenant on tenant.id=rule_chain.tenant_id where rule_node.id in ('
cat $LOG_FILE | grep "Failed to init actor, attempt 1" | grep -o "|.*\]"|sed 's/^.//;s/.$//' > $FILENAME

for i in $(sort -u $FILENAME) 
do
QUERY=$QUERY"'$i', "
    done
QUERY=$QUERY"'1');"

echo $QUERY
```
Where `LOG_FILE` is the path to the log file, it can be either relative or full path.

Go to the database and run this query to find all rule nodes with startup failures.

Then, investigate the failures in the rule nodes in the rule chains. Search for the message “Failed to process message:” and at the end of the line, you will see which rule node in which rule chain is causing the failure:

`Last Rule Node: [RuleChain: xxxx |RuleNode: xxxxxxxx (1b8f1b21-e5b8-11ed-8105-158dce191c94)]`
If you have many tenants, it will be difficult to determine which tenant to search in. You can use a database query:
```
select rule_node.name as rule_node_name, rule_chain.name as rule_chain_name, tenant.title as tenant_name from rule_node 
join rule_chain on rule_chain.id=rule_node.rule_chain_id
join tenant on tenant.id=rule_chain.tenant_id
where rule_node.id='1b8f1b21-e5b8-11ed-8105-158dce191c94';
```
Perform a similar search for timeouts. Timeout messages begin with Timeout to process message

You can use a script that parses the entire log file and creates a query for nodes with failures and nodes with timeouts:
```
function createQuery () {
LOG_FILE=thingsboard.2024-05-07.4.log
FILENAME=rows.txt

QUERY='select rule_node.name as rule_node_name, rule_chain.name as rule_chain_name, tenant.title as tenant_name from rule_node join rule_chain on rule_chain.id=rule_node.rule_chain_id join tenant on tenant.id=rule_chain.tenant_id where rule_node.id in ('
cat $LOG_FILE | grep "$1" | grep -o "Last Rule Node: .*" | grep -o "(.*)" |sed 's/^.//;s/.$//' > $FILENAME

for i in $(sort -u $FILENAME) 
do
QUERY=$QUERY"'$i', "
    done
QUERY=$QUERY"'1');"
echo $QUERY
}
echo Failed to process message query:
echo $(createQuery "Failed to process message:");
echo Timeout to process message query:
echo $(createQuery "Timeout to process message:");
```
This has been tested on versions 3.5+
