### ISSUE TITLE
[Question] How to navigate to other dashboard programmatically ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6494]
Hello,

I would like to know what is the function name & parameters of the stateController to navigate to other dashboard programmatically ? 
I would like to do it programmatically because I have to set multiples state entity parameters and not just one when arriving in the dashboard.
In fact, I want to reproduce the behaviour of the "Navigate to other Dashboard" type action but using custom action JS code.
Is it possible to do it ?

Best regards,

Lucas

**Comment by lucasKapf** [comment]
Hello @qwykx thank you for your answer. I'm trying to use the openState function but it seems to open only the different states inside the same dashboard. What I'm trying to do is to navigate from a dashboard to another one. Do you think I can be able to do that with the same function ?

**Comment by qwykx** [comment]
Unfortunately not.

You can however use:

```JavaScript
let dashboardId = "enter the dashboard Id here";
window.location.href = "yourthingsboardinstance.com/dashboards/" + dashboardId;
```
If you need to fetch the the dashboardId using some magic logic just use the [dashboard-controller rest api](https://demo.thingsboard.io/swagger-ui/#/dashboard-controller).

Cheers

**Comment by lucasKapf** [comment]
@qwykx oh ok, but I will not be able to pass my state entity parameters to the target dashboard if I do it this way right ?

Cheers

**Comment by qwykx** [comment]
I cannot find a solution to this by looking at the source of thingsboard :/

Why are you trying to navigate to a new dashboard instead of a state by the way?

Cheers

**Comment by lucasKapf** [comment]
Yes me neither... 
In fact I have an "old" dashboard that some of my colleagues use and I have created another dashboard to manage entities. This dashboard already has multiple states itself.
I wanted my colleagues to be able to switch from one dashboard to another in one click.
This way, I don't have to build states from scratch on the old dashboard, and my colleagues can keep using their dashboard and start using mine.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
