### ISSUE TITLE
Error:(28, 1) java: package org.thingsboard.server.extensions.core.plugin.telemetry.gen.TelemetryPluginProtos does not exist

### ISSUE THREAD

**Issue by yanleirex** [thingsboard/thingsboard#65]

**Comment by ashvayka** [comment]
@yanleirex Please execute build using maven before importing into your IDE ( I assume this is an error in IDE). Maven build generates this files automatically based on protobuf structures. That is why there is a "gen" in the package name.

**Comment by AmarLimitless** [comment]
> @yanleirex Please execute build using maven before importing into your IDE ( I assume this is an error in IDE). Maven build generates this files automatically based on protobuf structures. That is why there is a "gen" in the package name.

please tell me which command I have to run.
