### ISSUE TITLE
[Question/Feature Req?] Allen Bradley PLC Support Module

### ISSUE THREAD

**Issue by cmseaton42** [thingsboard/thingsboard#650]
## Inquiry/ Feature Req???

I have built a node based [ethernet-ip](https://github.com/cmseaton42/node-ethernet-ip) package to enable communication with newer Rockwell Automation PLCs.  I am wondering if there would be an easy way to develop a module to be integrated with thingsboard (with MQTT maybe, or HTTP), as well as what you would prefer for a project of this nature (eg should I launch it as a separate repo).

**Comment by ashvayka** [comment]
What interfaces are available to talk to this PLC at the moment?

**Comment by cmseaton42** [comment]
If you are asking about in general then some common ones are packages like [kepware](https://www.kepware.com/en-us/) or [INGEAR](https://ingeardrivers.com/).  There are others like these but these are probably the industry leaders for there individual purposes, OPC and Ethernet/IP respectively.  This said, they are both quite expensive.  I'm not sure if this anwsers your question or not though?

**Comment by Ultrazombie** [comment]
Hello, @cmseaton42 
Please provide a complete description of your issue if it still exists.

**Comment by danwale** [comment]
This is exactly what I need, shame to see this closed and no resolution, I've been told by our traditional SCADA developers that all HMI systems generally come with drivers for communicating with PLCs using Ethernet/IP CIP protocol so if we want ThingsBoard to replace such a system it would need to support that as well.
