### ISSUE TITLE
[Question] is Client-side RPC possible from a gateway on behalf of its device?

### ISSUE THREAD

**Issue by gednz** [thingsboard/thingsboard#6501]
**Component**
 * Rule Engine
 * MQTT Gateway API

**Description**
I have a custom Device acting as an MQTT gateway with lora devices connected to it. 
I have been successfully requesting attributes from Thingsboard on behalf of other devices using Request attribute values from the server as per MQTT Gateway API Reference.
However I need Thingsboard to manipulate the Attributes before sending them, hence I would like to make a Client-side RPC request against the MQTT Gateway API
The MQTT Gateway API Reference only mentions Server-side RPC.

**Environment**
 * ThingsBoard: 3.3.1PE
 * *Custom MQTT Gateway

**Comment by devaskim** [comment]
As I know there is no such functionality. But you could emulate the desired behaviour in the following way:
1. Create client-side  attributes called `state`. The values may be `DATA_PENDING`, `WORKING_STATE` end etc
2. Listen to the [ATTRIBUTES_UPDATED](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types) event in (Root) Rule Chain. This event includes the name and value of the updated attribute, so can filter the `state` attribute events.
----- 1 ------
3. Send server-side RPC to the device with pre-processed data.
----- 2 ------
3. Add shared-attribute manipulation logic to your Rule Chain.
4. Once shared attributes will be updated the device will receive them.

**Comment by gednz** [comment]
Hi @devaskim 

Thanks for the fantastic idea!
admission - I didn't actually know there was an [ATTRIBUTES_UPDATED](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types) event, sometimes you just stare at the default rule chains and forget that there is more  hiding away there.

I have been pondering this all day and I think it could be even better than Client side RPC on gateway API.

I haven't tested anything yet but I have another question about Server Side RPC on a gateway:
How does the server know what messages to send to the gateway/Does it send messages only for "connected" devices? 
-- because that would be even better than Client side RPC in that you don't have to publish a blind request for each device but rather can fashion the rule chain to cause an attribute update for devices that actually need data.

I'll update this again when I have tested more. Thanks again!

**Comment by devaskim** [comment]
To intercept *ATTRIBUTES_UPDATED* event you can add [Message Type Filter Node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#message-type-switch-node), for example, right after *Input* node of default (root) rule chain.

TB supports are 2 kinds of RPC: one-way and two-way. Each RPC has delivery timeout. If device is offline more than this timeout, RPC will be expired/cancelled. You can read more [here](https://thingsboard.io/docs/user-guide/rpc/#persistent-rpc)

**Comment by gednz** [comment]
Hi @devaskim

I have done a bit more work on this and my solution so far is to avoid RPC and use the Attribute API:

1. Gateway sends telemetry on behalf of device as normal.
2. Gateway sends attribute on behalf of device `ping=1` (we don't care about its value, its just a trigger).
3. In the Rule chain we listen for `Post attributes` and filter for `ping`. This message allows us to construct a reply JSON attribute for the device called `data`. I find I need a delay here if I want to use the latest telemetry.
4. Gateway subscribes to `v1/gateway/attributes/response` .
5. Gateway sends a request for the attribute `data` to `v1/gateway/attributes/request` on behalf of the device. A bonus here is that the Gateway sets the request ID.
6. Gateway receives response containing `data` attribute

In my testing [ATTRIBUTES_UPDATED](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types) is only triggered by dashboard activity and not by saving attributes in the rule chain.

**Comment by devaskim** [comment]
@gednz Thanks for sharing your investigation, I don't know what [ATTRIBUTES_UPDATED](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types) is triggered not in all cases. Then I looked into source code of server, and yes, mqtt gateway API uses only `POST_ATTRIBUTES` event.
