### ISSUE TITLE
[Bug] login "Authentification Failed" using autofill on chrome

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#6503]
**Describe the bug**
Using different password-manager on google chrome to login to TB leads to "Authentification failed" error. After deleting one sign on the password and adding it back again the login is successfull. 

**Your Server Environment**

  * 3.3.2 PE

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [iOS]
* Browser [chrome]

**Smartphone (please complete the following information):**
* Device: [iPhone]
* Browser [chrome]

**To Reproduce**
1. Go to Google Chrome and open the Loginpage of Thingsboard 
2. Use your password manager to autofill username and password
3. See error "Authentification failed"

**Additional context**
If you delete one sign out of your password and add it back again you can login to Thingsboard as expected.

**Comment by ltancerel** [comment]
I am seeing this issue on Qwant navigator as well on iphone ([Qwant is a french navigator respectuous of privacy](https://www.qwant.com/)  

The difference with the issue described is that I also need to do the same on login.
By the way, without touching it, it is not seen as a valid email, when erasing "m" and writing it, and doing the same for the password last letter, I am able to login ...

<img width="371" alt="Capture d’écran   2022-09-09 à 09 52 31" src="https://user-images.githubusercontent.com/26801951/189300702-2af1fe1d-4aa9-4488-bef2-36342ea57064.png">

**Comment by Ultrazombie** [comment]
The issue isn't reproducible. Closed due to inactivity
