### ISSUE TITLE
[Question] How to increase the storage space of Asset-Attributes or save Files(images, jpeg, png, pdf & Co) to the Filestorage

### ISSUE THREAD

**Issue by danielivaneza** [thingsboard/thingsboard#6507]
**Component**

 * Generic

**Description**
What I have done so far:
I take an image with a tablet in the mobileApp and save the image as a Base64Encoded String in the attributes of an asset. The problem is that the file size can only be up to 1MB, if it is larger it gives the "413 Entity Too Large" error.

Question1: Is there any way to increase the file size of the asset attributes?

Question2:
New idea:
I take an image with a tablet in the mobileApp and want to save it in the Thingsboard fileStorage. (How) can I save this image in the fileStorage?

Any recommendations on where and how to save the images?
 
**Environment**
 * ThingsBoard: PE
 * Browser: Microsoft EDGE

**Comment by pon0marev** [comment]
You can use base64 compressed images. However, it is not good practice to use images larger than 1 MB, as this can cause performance degradation. It is better to send links to images stored on AWS S3 or an FTP server to ThingsBoard.
