### ISSUE TITLE
thingboard installation failed

### ISSUE THREAD

**Issue by Divya-021** [thingsboard/thingsboard#6508]
Hi,
I am referring https://thingsboard.io/docs/user-guide/install/windows/. as mentioned in step 3. I opened pgAdmin 4 and under servers->postgresql 11->databases, i created a database named thingsboard. Also i updated the thingboard.yml in admin mode with the code provided with password set as of mine database + the code it already have. now at step 6 when i am executing install.bat --loadDemo the following problem occurs. can anyone help me with the solution?

Detecting Java version installed.
CurrentVersion 110
Java 11 found!
Installing thingsboard ...
ThingsBoard installation failed!

**Comment by Divya-021** [comment]
I got to find that there is a problem with installing thingsboard.exe. 
 
![Screenshot 2022-04-30 194904](https://user-images.githubusercontent.com/90896647/166109365-649285e3-cbff-45a6-8fee-6f56612e5a59.png)

**Comment by devaskim** [comment]
Open command line with Administrator privileges and re-run `install.bat --loadDemo`

**Comment by Divya-021** [comment]
> 

Hi,
i am executing with admin rights only. after executing this particular command i am receiving this error:
Detecting Java version installed.
CurrentVersion 110
Java 11 found!
Installing thingsboard ...   
ThingsBoard installation failed!

just after installing thingsboard without showing any error statements it directly showing installation failed

**Comment by mde2017** [comment]
Hi @Divya-021,

in the ThingsBoard installation directory you can find the logs. Do you see any errors in the **install.log** file?

Also consider to switch to Linux, if possible, since it'ts the most stable version of ThingsBoard as stated in the documentation:
https://thingsboard.io/docs/user-guide/install/windows/

**Comment by Ultrazombie** [comment]
@Divya-021 Hello!
Can you provide the install.log, please?
Also, as mentioned @mde2017 - Linux is better OS for ThingsBoard :)
