### ISSUE TITLE
[Question] display timeseries metdata on dashboard

### ISSUE THREAD

**Issue by MaxMakerMan** [thingsboard/thingsboard#6509]
hello,

I would like to display some metadata in the timeseries table widget. - However I am only able to access the entities timeseries values.

I would like to display the originatorName alongside the timeseries value, as the value can be set from dashboard aswell as from the IoT device itself. - I would like to be able to trace and display who made the change to the setting.
In the rule chain I can access the metadata using metadata.originatorName.

thank you in advance and regards from Austria :)

**Comment by devaskim** [comment]
Maybe the `Entities table` widget (Card bundle) would be better choice.
