### ISSUE TITLE
[Question] tool/library to create animated SVG flow charts from the documentation

### ISSUE THREAD

**Issue by AlbertusMagnus7** [thingsboard/thingsboard#6510]
Throughout the documentation, there are beautiful SVG-based animated and clickable flowcharts (such as https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/). Is there any particular tool or library (in python or other?) that those (including their animation) have been created with or are they each “hand-drawn”?

**Component**
 * Generic
 * Documentation

**Comment by tkqq000** [comment]
wnat know too

**Comment by majj** [comment]
+1

**Comment by Nezteb** [comment]
Ditto!

[Here's the URL directly to the SVG](https://thingsboard.io/images/gateway/python-gateway-animd-ff.svg).

I found [an SO question asking about this](https://stackoverflow.com/questions/66895537/is-there-a-library-which-can-generate-animated-svg-diagrams-like-this-example) but it has no comments/answers.

I figured it couldn't hurt to [Tweet at them and ask](https://twitter.com/Nezteb/status/1639379053206728704). 😄

**Comment by Jlrine2** [comment]
Ok, but like, how do that in Figma? is there like a guide? still seems like magic to me.

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
Please read the Figma documentation
