### ISSUE TITLE
Error when using angular way bindings to bind an array item by index or an object property

### ISSUE THREAD

**Issue by Aqaliarept** [thingsboard/thingsboard#6512]
**Server Environment**
https://thingsboard.cloud

**Client Environment**
* OS: MacOs Monterey  12.2.1
* Browser:  chrome 100.0.4896.127, safari 15.3

**To Reproduce**
1. Create a new widget bundle
2. Add a new widget type based on Latest Values
3. Set Java script to
`self.onInit = function() {
    self.ctx.$scope.data = [1, 2, 3];
}

self.onDataUpdated = function() {
    self.ctx.detectChanges();
}`

5. Set HTML code to
`<span>{{data[0]}}</span>`

6. Press *Run* button
6. See error in browser JS console:
`
[Error] ERROR – TypeError: undefined is not an object (evaluating 'ctx.data[0]')
TypeError: undefined is not an object (evaluating 'ctx.data[0]')
	Qu (vendor.4a8c3f0e21207031cc53.js:1:283052)
	handleError (vendor.4a8c3f0e21207031cc53.js:1:283216)
	dd (vendor.4a8c3f0e21207031cc53.js:1:302949)
	lu (vendor.4a8c3f0e21207031cc53.js:1:302537)
	detectChanges (vendor.4a8c3f0e21207031cc53.js:1:371820)
	configureDynamicWidgetComponent (3928.830b76b38a07b308b25e.js:1:3091169)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3090061)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3095336)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3092187)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:240761)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242516)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2772335)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2765335)
	_complete (vendor.4a8c3f0e21207031cc53.js:1:2763906)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2763709)
	_subscribe (vendor.4a8c3f0e21207031cc53.js:1:2760221)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757807)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2772225)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757691)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242504)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2772335)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2765335)
	_complete (vendor.4a8c3f0e21207031cc53.js:1:2763906)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2763709)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2813232)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2772225)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757691)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242429)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:264720)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2784604)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	notifyNext (vendor.4a8c3f0e21207031cc53.js:1:2790384)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2768133)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	gn (vendor.4a8c3f0e21207031cc53.js:1:226428)
	onInvokeTask (vendor.4a8c3f0e21207031cc53.js:1:424637)
	runTask (polyfills.bcb108b58156eefa6b2c.js:1:2572)
	invokeTask (polyfills.bcb108b58156eefa6b2c.js:1:8302)
	st (polyfills.bcb108b58156eefa6b2c.js:1:20421)
	ot (polyfills.bcb108b58156eefa6b2c.js:1:20775)
[Error] TypeError: undefined is not an object (evaluating 'ctx.data[0]')
	configureDynamicWidgetComponent (3928.830b76b38a07b308b25e.js:1:3091195)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3090061)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3095336)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:3092187)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:240761)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242516)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2772335)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2765335)
	_complete (vendor.4a8c3f0e21207031cc53.js:1:2763906)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2763709)
	_subscribe (vendor.4a8c3f0e21207031cc53.js:1:2760221)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757807)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2772225)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757691)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242504)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2772335)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2765335)
	_complete (vendor.4a8c3f0e21207031cc53.js:1:2763906)
	complete (vendor.4a8c3f0e21207031cc53.js:1:2763709)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2813232)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	(anonymous function) (vendor.4a8c3f0e21207031cc53.js:1:2772225)
	_trySubscribe (vendor.4a8c3f0e21207031cc53.js:1:2758018)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757829)
	subscribe (vendor.4a8c3f0e21207031cc53.js:1:2757691)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:242429)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	(anonymous function) (3928.830b76b38a07b308b25e.js:1:264720)
	__tryOrUnsub (vendor.4a8c3f0e21207031cc53.js:1:2765412)
	next (vendor.4a8c3f0e21207031cc53.js:1:2764649)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	next (vendor.4a8c3f0e21207031cc53.js:1:2761314)
	nextInfiniteTimeWindow (vendor.4a8c3f0e21207031cc53.js:1:2759636)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2788423)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2784604)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	notifyNext (vendor.4a8c3f0e21207031cc53.js:1:2790384)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2768133)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	_next (vendor.4a8c3f0e21207031cc53.js:1:2763810)
	next (vendor.4a8c3f0e21207031cc53.js:1:2763585)
	gn (vendor.4a8c3f0e21207031cc53.js:1:226428)
	onInvokeTask (vendor.4a8c3f0e21207031cc53.js:1:424637)
	runTask (polyfills.bcb108b58156eefa6b2c.js:1:2572)
	invokeTask (polyfills.bcb108b58156eefa6b2c.js:1:8302)
	st (polyfills.bcb108b58156eefa6b2c.js:1:20421)
	ot (polyfills.bcb108b58156eefa6b2c.js:1:20775)
`

**Expected behavior**
Possible to bind array items and object properties with Angular way syntax

**Additional context**
A similar error occurs when `self.ctx.$scope.data = {someProperty : 123};` is set to an object and in HTML I try to bind object properties like
`<span>{{data.someProperty}}</span>`

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
