### ISSUE TITLE
[Question] For what does customer entity exist? (TB CE)

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6513]
**Component**
 * Generic

**Description**
It would be great if I can log in as a customer (not customer's user), have some dashboards to review my users, their devices and etc. At the moment (v3.3.4.1) I can only create such entity type and that is all. Could someone explain how can I use it in my business purposes?

**Comment by JacksonBowe** [comment]
This functionality is added in TB PE via Role-based Access Control (RBAC). I would not expect it to become a feature of CE in the near future :L
