### ISSUE TITLE
[Bug] Edge instance detail window - Downlink overview navigation

### ISSUE THREAD

**Issue by ricktauss** [thingsboard/thingsboard#6514]
The Edge instance detail window - Downlink overview navigation is affecting the previous window.

Plattform is running on Docker on a Raspberry Pi4B. 
I am using Google Chrome as browser.

1. Go to Edge instances
2. Click on a edge instance -> detail window is opened on right side
3. Click on Downlinks
4. The latest downlinks are shown
5. Click on "items per page", use arrows for next page or click on "Event Time" column filter
6. The edge detail window is closed and the edge instances window behind is triggered
![EdgeInstance_UI](https://user-images.githubusercontent.com/57318706/166289077-de98169a-3c49-4d48-a9ae-63ce4ee19d64.JPG)

**Comment by volodymyr-babak** [comment]
@ricktauss 

thanks for creating this issue. 
Resolved in PR: 
https://github.com/thingsboard/thingsboard-pe/pull/928

Should be available in the 3.4 release.
