### ISSUE TITLE
[Question] does the converter support map type

### ISSUE THREAD

**Issue by DaXian459** [thingsboard/thingsboard#6515]
**Description**
Hello, does the converter support map type

**Environment**

 * OS:  Win10
 * ThingsBoard: 3.3.4 PE
 * Browser: Chorme

**Comment by epalchenko** [comment]
Hello,
Feel free to use TBEL in your case. TBEL allows you to create Maps. We use our own implementation of the Map to control memory usage. That is why TBEL allows only the inline creation of maps:
https://thingsboard.io/docs/pe/user-guide/tbel/#maps
