### ISSUE TITLE
[Bug] Rule Chain : One rule node output is success but I have no events coming in the next node

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6516]
**Describe the bug**
I have no event coming in the next rule nodes, even if I have event coming out my transformation script rule node with relation type success. Of course, my rule nodes are linked with success arrows, and each rule node has debug mode on.
It happens in a Rule Chain which is linked to another Rule Chain, itself linked to other Rule Chain.

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser: Chrome
* Version  100.0.4896.127

**Expected behavior**
I would expect to have some debug events in the nodes after my transformation script rule node.

**Screenshots**
Part of my Rule Chain where the bug happens : 

![CaptureRuleChainBug1](https://user-images.githubusercontent.com/95343678/166417442-ac4cf773-1d81-43e4-9956-b14583851383.png)

Debug in the transformation script rule node (number 1) : 

![CaptureRuleChainBugDebug1](https://user-images.githubusercontent.com/95343678/166417604-591d1c69-5d7d-4ad0-b951-82b01d281bb1.JPG)

Debug is empty in the script rule node (number 3) :

![CaptureRuleChainBugDebug3](https://user-images.githubusercontent.com/95343678/166417694-d77c6667-8a88-4e14-a7fc-032db3354b26.JPG)

I have the same result in the rule node number 2.
Of course, all my nodes have debug mode on.

Thank in advance for your help,

Lucas

**Comment by devaskim** [comment]
Did you look at server logs? Maybe there are errors

**Comment by lucasKapf** [comment]
Hello @devaskim, thank you for your answer. I'm using Thingsboard Cloud Professional Edition, I don't know if I can access those logs with Thingsboard Cloud ?

**Comment by devaskim** [comment]
If you use only one node after transformation script, is the same behaviour?

**Comment by lucasKapf** [comment]
I tested by inserting one script node which does "return true" between my transformation script and the two other rule nodes. 
It is the same behaviour : nothing come in my return true script

**Comment by ashaforost** [comment]
Hi @lucasKapf 

Please let me know whether you still have this issue. Also, please try the same scenario in thingsboard.cloud, and not cloud.thingsboard.io, as cloud.thingsboard.io is our PE demo instance, which is designed for our customers to get to know the thingsboard PE features only. We do not advise using cloud.thingsboard.io for business deployments, as it doesn't have the same processing capacity as thingsboard.cloud.

**Comment by lucasKapf** [comment]
Hello @ashaforost, I still have this issue. I currently use thingsboard.cloud and the problem occurs when I use the change originator rule node with related entity.
It seems that nothing comes in the rule node after the change originator rule node if too many nodes are crossed before (including node in previous rule chains).
With a total of 26 nodes before, the problem occurs.
Everything is fine with 23 nodes before.

**Comment by Lenteguppie** [comment]
I have a similar issue. I have a rule chain where I perform some transformations to a message and store it in the attributes. When that transformation is finished I give a "Success" output on the rule chain. When I look in the debug of the "Success" node the OUT message is sent correctly, but I do not receive input on the node connected to the "rule chain" rule node.

Has anyone found a fix yet?

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
