### ISSUE TITLE
How to access angular module in custom widget?

### ISSUE THREAD

**Issue by dhaval2017** [thingsboard/thingsboard#6517]
**Component**

 * Generic

**Description**
How can I access **MatTableDataSource** inside custom widget
I like to make custom table with pagination but gets error **MatTableDataSource** is not defined

**Comment by KevinPoole** [comment]
@dhaval2017 I know this is a stretch, but did you ever figure this out by chance?

**Comment by KevinPoole** [comment]
@imbeacon you helped me get my PR merged over on thingsboard-gateway so I thought maybe it'd be worth looping you in here - any thoughts?

**Comment by dhaval2017** [comment]
@KevinPoole found the alternative

https://github.com/thingsboard/thingsboard-extensions/tree/6a47d384916fcd2e5ffcee27c2cf99adea90caf0

**Comment by dhaval2017** [comment]
@KevinPoole  found the alternative

https://github.com/thingsboard/thingsboard-extensions/tree/6a47d384916fcd2e5ffcee27c2cf99adea90caf0
