### ISSUE TITLE
[Question] How to redraw manually a map widget

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6518]
**Component**

 * UI

**Description**
Hi,
I'm using interactive filter with dynamic filter that works fine.
I have an alias with this interactive filter on a map widget using openstreetmap provider (Fit map bounds to cover all markers is active).
When the new filter returns more markers, the widget is redrawn correctly with all the markers.
When the new filter return less markers, the widget is not redrawn, just the useless markers are erase from the map without changing the map bounds. It's quite good to avoid changing the map every time.
So I would like to add a header button to redraw the map focused on the markers like it's done when I refresh the current page of the browser.
What is the code to do that?
Thanks for your answers.

**Comment by devaskim** [comment]
I am interested in such option too

**Comment by devaskim** [comment]
I think [this code](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts#L784) `this.options.fitMapBounds ? !mapBounds.contains(bounds) : false` blocks redrawing.
`mapBounds` - current bounds
`bounds` - bounds of new marker set

**Comment by liotys** [comment]
Hi @devaskim , thanks for your informations.
I guess the code for the button could be like:

_let currentInstance = widgetContext.mapInstance;
  let bounds = new **L.LatLngBounds(null, null);**
      currentInstance.markers.forEach((marker) => {
        bounds.extend(marker.leafletMarker.getLatLng());
      });
    

    currentInstance.bounds = bounds;
    currentInstance.fitBounds(bounds);
    currentInstance.map.panTo(currentInstance.bounds.getCenter());_

But I don't know how to initialize bounds object...

**Comment by liotys** [comment]
Thanks to you @devaskim I've written a piece of code that works.
It's not optimized but it works.

```
let currentInstance = widgetContext.mapInstance;

if (currentInstance.markers.size>0) {
  var bounds = currentInstance.bounds;
  bounds._northEast.lat=bounds._southWest.lat=currentInstance.markersData[0].latitude;
  bounds._northEast.lng=bounds._southWest.lng=currentInstance.markersData[0].longitude;
  currentInstance.markers.forEach((marker) => {
    bounds.extend(marker.leafletMarker.getLatLng());
    });
    currentInstance.fitBounds(bounds);
    currentInstance.map.panTo(bounds.getCenter());
}


```

**Comment by devaskim** [comment]
@liotys Thanks for sharing, I will re-use your implementation too.
