### ISSUE TITLE
[Bug] Float numbers are being passed as strings from the metadata

### ISSUE THREAD

**Issue by garageeks** [thingsboard/thingsboard#6521]
**Describe the bug**
After upgrading from 3.2.1 to 3.3.4.1 we noticed some generated values by the rule chain weren't treated as float numbers but as concatenation of strings.
We have some counters to track energy usage, which are incremented by the value received in the telemetry, and then it is reset at midnight. Somehow the previous value, which is obtained from the metadata, is passed as a string and not as a float, since there it starts breaking things.
Counters with integer-only values are working fine.

![image](https://user-images.githubusercontent.com/15252836/166651923-dcf54bb7-681e-4366-bf10-d396f82df3cd.png)

Here I show how processing in the rule chain is implemented:

We obtain previous counter value from the metadata
`var previous_todaySocket1Energy = JSON.parse(metadata.todaySocket1Energy);`

Then I sum values using a function that takes care of undefined values (if they occur)

```
 msg.todaySocket1Energy = getSum([
    previous_todaySocket1Energy.value,
    msg.s1_loadWh
  ]);
```

The function itself:
```
function getSum(values) {
  return values.reduce(function (acc, current) {
    var value = current !== undefined ? current : 0;
    return acc + value;
  }, 0);
}
```

An attempted workaround is to convert strings back into float numbers with parseFloat instruction.
As the bug creates concatenations of float numbers, parseFloat will truncate at the second dot, therefore the accumulation won't be mathematically sound anymore, but the error introduced is negligible since it's decimals.
As JavaScript variables are declared without a type, the thing will keep working in a totally wrong way.

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment: AWS
  * ThingsBoard Version: 3.3.4.1
  * OS Name and Version: Ubuntu 20.04.4 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * HTTP
 

**To Reproduce**
I have no means of reproducing the error as I don't have a readily available test environment, however it could be simulated by feeding telemetry with float numbers to the routines mentioned above

**Expected behavior**
Float numbers should be passed by the metadata as floats and not as strings

**Comment by SuminDenys** [comment]
HI @garageeks,

Thank you for your report! This is a bug in our system, and our product team is already processing a product ticket PROD-1691. 
I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.
