### ISSUE TITLE
[Bug] demo.thingsboard can't login with Google with Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by ngoccatt** [thingsboard/thingsboard#6524]
**Describe the bug**
I can't login with google anymore, this seem like an issue from the server demo.thingsboard it self. Please consider fixing it.

**Your Server Environment**

* demo.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser Microsoft Edge
* Version 101.0.1210.32

**Your Device**

* Connectivity
  * MQTT
* Device vendor and model

**To Reproduce**
1. Go to demo.thingsboard.io
2. Click on login with Google
3. See error

**Expected behavior**
Successful login into thingsboard

**Screenshots**
![Screenshot 2022-05-05 122620](https://user-images.githubusercontent.com/55552595/166867988-4f347c04-5c1d-4eda-b670-e223a1ab379a.png)

**Additional context**
none

**Comment by ashaforost** [comment]
Hi @ngoccatt 

Make sure that you access the **https**://demo.thingsboard.io instead of http, the issue will be resolved then.
