### ISSUE TITLE
[Question] Detecting change in shared attribute via HTTP API

### ISSUE THREAD

**Issue by rtborg** [thingsboard/thingsboard#6528]
**Component**

 * Generic

**Description**
I'd like to know how to detect shared attributes update via the HTTP API without using timeout. The method described [here](https://thingsboard.io/docs/reference/http-api/#subscribe-to-attribute-updates-from-the-server), making a GET request with no timeout, always returns immediately with no data.  

My application fetches some configuration data via HTTP GET, and I need a way to know when that configuration has been changed on the Thingsboard server. Downloading the complete file takes some resources, therefore I am looking for a way to let the application know that it needs to download the configuration - like hash or last-date-changed field in the header. The application can then periodically check if the resource has been updated.

**Environment**

 * OS:  Using espidf and ESP32
 * ThingsBoard: version: v3.3.3
 * Browser: N/A

**Comment by devaskim** [comment]
I think there is no other way, because HTTP transport model implies that you need to periodically send request to the server.

**Comment by rtborg** [comment]
Closing as apparently polling is the only option.
