### ISSUE TITLE
[Feature Request]Replace @Scheduled annotations with Scheduled Service

### ISSUE THREAD

**Issue by irynamatveieva** [thingsboard/thingsboard#6529]
### Description
The main idea of this feature request is to replace @Scheduled annotation for methods of printing statistics with a Scheduled Service. Each using this annotation a new thread is created. To avoid this, I created a Scheduled Service, that performs the same functions without creating new threads.

**Comment by timbotetsu** [comment]
how about using [ScheduledTaskRegistrar](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/config/ScheduledTaskRegistrar.html) for scheduling all these tasks?
