### ISSUE TITLE
Retrieve assets by name

### ISSUE THREAD

**Issue by nucflash** [thingsboard/thingsboard#653]
Hi, I'm working on a automatic deployment application for IoT that needs to manage customers, assets, devices, and their relations programmatically. The application is built atop ThingsBoard. 

What I need is to retrieve customers, assets, and devices by name because I do not know their ThingsBoard ids beforehand. I can retrieve customer ids by customer name by doing:
```
/api/customers?textSearch=customerName
```
but I cannot do:
```
/api/assets?textSearch=assetName
```
I get the following:
```
{
 "timestamp":1521033025097,
 "status":400,
 "error":"Bad Request",
 "exception":"org.springframework.web.bind.UnsatisfiedServletRequestParameterException",
 "message":"Parameter conditions \\"assetIds\\" not met for actual request parameters: limit={99999}, textSearch={Hotel1}",
 "path":"/api/assets"
}
```

Is there any way that I can retrieve the id of an asset by its name?

**Comment by mfalkvidd** [comment]
@nucflash could you use findByQuery?
http://demo.thingsboard.io/swagger-ui.html#!/asset-controller/findByQueryUsingPOST

**Comment by nucflash** [comment]
Yes, this works. Thanks!

**Comment by fargiolas** [comment]
> Yes, this works. Thanks!

would you mind to share some detail? I'm trying to use the rest api to find assets and devices by name to delete them but couldn't get findbyquery to work. Thanks!

**Comment by JaMurphSmi** [comment]
I would also be interested to know how to use findByQuery.
