### ISSUE TITLE
Transform telemetry using previous record with specific data in thingsboard

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#6539]
Hi , I am new to things board, I just want ask actually my device continuously collect the data from the protocol and I want to configure with some logic in the rule chain, My telemetry data as followed:

timestamp=1652262064000 v=1
timestamp= 1652262124000 v=0
timestamp=... v=0
timestamp=... v=1

My telemetry data is live and send to my TB every few seconds... of if I want to check the time interval(by second/minutes) between the last v=1 and the lastest v =1, how can I do to calculate the time interval? I use the delta method, But unfortunally I get the error as following:

the following attributes/telemetry keys is not present in DB

I also not sure why this errors appear and what can I do to fix this error

Any recommendation ways to do this logic inside the rule chain?

**Comment by devaskim** [comment]
Firstly, check if you added or not the rule node that saves data to the database.
To implement your algorithm you need two delta nodes:
1.  First one calculates delta for the *v* key. If v-delta is negative, it means *v* has been changed from 1 to 0. On this stage add via the transformation node new key, e.g. *vChangedTs*, where set timestamp of this event. If v-delta if positive, it means *v* has been changes from 0 to 1. In that case you need pass data to the second delta node.
2. Second delta node calculates delta for the *vChangedTs* key. This value you need.

You can get timestamp either from message metadata, or create vis JS `Date.now()`

**Comment by mde2017** [comment]
Hi @ngsuityan,

you can find guides for similar usecases in the documentation:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/transform-telemetry-using-previous-record/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/telemetry-delta-validation/

**Comment by ngsuityan** [comment]
> Firstly, check if you added or not the rule node that saves data to the database. To implement your algorithm you need two delta nodes:
> 
> 1. First one calculates delta for the _v_ key. If v-delta is negative, it means _v_ has been changed from 1 to 0. On this stage add via the transformation node new key, e.g. _vChangedTs_, where set* timestamp of this event. If v-delta if positive, it means _v_ has been changes from 0 to 1. In that case you need pass data to the second delta node.
> 2. Second delta node calculates delta for the _vChangedTs_ key. The result of this node you need.
> 
> *You can get timestamp either from message metadata, or create vis JS `Date.now()`

I try using the action node "Save time-series" and save the data, but the error still happen, is that because I am using the wrong node?

**Comment by devaskim** [comment]
Each node has *Debug* option. Enable it, for example, for *Save time-series* node and for first one after *Input* node of Root rule chain. Then look at *Events* tab of each of these nodes what data come in and out.

**Comment by ngsuityan** [comment]
> Firstly, check if you added or not the rule node that saves data to the database. To implement your algorithm you need two delta nodes:
> 
> 1. First one calculates delta for the _v_ key. If v-delta is negative, it means _v_ has been changed from 1 to 0. On this stage add via the transformation node new key, e.g. _vChangedTs_, where set* timestamp of this event. If v-delta if positive, it means _v_ has been changes from 0 to 1. In that case you need pass data to the second delta node.
> 2. Second delta node calculates delta for the _vChangedTs_ key. The result of this node you need.
> 
> *You can get timestamp either from message metadata, or create vis JS `Date.now()`

is that anyways if I only save the timestamp with value 1 and calculate the different of the timestamp?

**Comment by devaskim** [comment]
I think "no", by design each telemetry packet has timestamp that is set either by client, or server. Therefore I suggested you to create another timestamp for your purpose.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
