### ISSUE TITLE
REST API Call Plugin GET method

### ISSUE THREAD

**Issue by phoenix147** [thingsboard/thingsboard#654]
I need to access an old hardware API, which only supports GET methods.

In #364 it was stated, that the REST API Call Plugin doesn't support GET (and also update). It only supports PUT and POST.

Nevertheless, the issue was closed, but why?

**Comment by vparomskiy** [comment]
It is not clear what exactly plugin do you need and what methods?
If you need to fetch data, then GET is used. For Data update/insert - post and put should be used.
If need to make CRUD operations only with GET, then you will need to create a custom plugin for make it works.

**Comment by phoenix147** [comment]
Hi!

The REST API Call Plugin, which is integrated into thingsboard, supports only PUT and POST. I did not find any possibility to use GET.

The reason: I need to set IOs of a W&T WebIO device, if an alarm is triggered. However, this device only supports GET calls to change the corresponding IOs and i cannot use PUT or POST.

It would be the simplest solution to add GET and DELETE to the possible calls of the REST API Call Plugin.

If i understand the code correctly, this should be possible by simply adding GET and DELETE to https://github.com/thingsboard/thingsboard/blob/master/extensions/extension-rest-api-call/src/main/resources/RestApiCallActionDescriptor.json

`      "items": [
        {
          "value": "POST",
          "label": "POST"
        },
        {
          "value": "PUT",
          "label": "PUT"
        },
        {
          "value": "GET",
          "label": "GET"
        },
        {
          "value": "DELETE",
          "label": "DELETE"
        }
]`

**Comment by vparomskiy** [comment]
Not actual anymore because with Rule Engine available in the Thingsboard 2.x you can make any rest api calls using 'Rest API` rule node. Closing
