### ISSUE TITLE
[Bug] Rendering state in Chart not working

### ISSUE THREAD

**Issue by thhart** [thingsboard/thingsboard#6543]
**Describe the bug**
I want to visualize a state in a chart. I can display the data in a table. The data source is delivering a true/false status. In the table it is seen as string. I could parse it and change it to numbers via the post processing function, however the data is coming in as a number type and is always 0 when I use it in a Chart as data source.
Somehow the data value is pre processed depending on the widget type which is going to be used...
The data source is the same for both widget types.

**Your Server Environment**
* own setup
  * ThingsBoard Version: 3.3.3

**Your Client Environment**
* Browser: Chrome

**Screenshots**
**This shows the chart and the table with 4 columns (time, original value, parsed,  type of), in the chart I would expect 1 as value the same as seen as in the table:**
![Screenshot_2022-05-12_12-47-29](https://user-images.githubusercontent.com/2632538/168054548-feb03581-036f-4012-9897-3633b4ce3861.png)

**This is the post processing function, this is not working obviously since value is type of number instead of string as in the table widget:**
![Screenshot_2022-05-12_12-48-47](https://user-images.githubusercontent.com/2632538/168054584-5125df59-7ecf-4c29-b010-fbd2581270ca.png)

**Comment by devaskim** [comment]
Look at *Advanced* tab in the last screenshot. Maybe some options from that section will help you

**Comment by thhart** [comment]
I checked it but could not find anything related. I used the Advanced settings to figure out the data is in number format via the tooltip already.

**Comment by devaskim** [comment]
![bool_chart](https://user-images.githubusercontent.com/86909129/168257493-cb8c39fa-4849-4f33-8c39-c2af1779b847.jpg)
Here is exported widget configuration
```
{
  "widget": {
    "isSystemType": true,
    "bundleAlias": "charts",
    "typeAlias": "basic_timeseries",
    "type": "timeseries",
    "title": "New widget",
    "image": null,
    "description": null,
    "sizeX": 8,
    "sizeY": 5,
    "config": {
      "datasources": [
        {
          "type": "function",
          "name": "randomboolean",
          "entityAliasId": "9c70ac2e-1282-7a29-041e-bd5f42198dc2",
          "filterId": null,
          "dataKeys": [
            {
              "name": "f(x)",
              "type": "function",
              "label": "StatusDoor",
              "color": "#2196f3",
              "settings": {
                "excludeFromStacking": false,
                "hideDataByDefault": false,
                "disableDataHiding": false,
                "removeFromLegend": false,
                "showLines": true,
                "fillLines": false,
                "showPoints": false,
                "showPointShape": "circle",
                "pointShapeFormatter": "var size = radius * Math.sqrt(Math.PI) / 2;\nctx.moveTo(x - size, y - size);\nctx.lineTo(x + size, y + size);\nctx.moveTo(x - size, y + size);\nctx.lineTo(x + size, y - size);",
                "showPointsLineWidth": 5,
                "showPointsRadius": 3,
                "showSeparateAxis": false,
                "axisPosition": "left",
                "thresholds": [
                  {
                    "thresholdValueSource": "predefinedValue"
                  }
                ],
                "comparisonSettings": {
                  "showValuesForComparison": true
                }
              },
              "_hash": 0.9623977238651553,
              "funcBody": "\nreturn prevValue === undefined ? true : !prevValue;",
              "units": null,
              "decimals": null,
              "usePostProcessing": null,
              "postFuncBody": null
            }
          ]
        }
      ],
      "timewindow": {
        "realtime": {
          "timewindowMs": 60000
        }
      },
      "showTitle": true,
      "backgroundColor": "#fff",
      "color": "rgba(0, 0, 0, 0.87)",
      "padding": "8px",
      "settings": {
        "shadowSize": 4,
        "fontColor": "#545454",
        "fontSize": 10,
        "xaxis": {
          "showLabels": true,
          "color": "#545454"
        },
        "yaxis": {
          "showLabels": true,
          "color": "#545454",
          "tickDecimals": 0
        },
        "grid": {
          "color": "#545454",
          "tickColor": "#DDDDDD",
          "verticalLines": true,
          "horizontalLines": true,
          "outlineWidth": 1
        },
        "stack": false,
        "tooltipIndividual": false,
        "smoothLines": false,
        "tooltipCumulative": false,
        "hideZeros": false,
        "showTooltip": true,
        "comparisonEnabled": false,
        "timeForComparison": "previousInterval",
        "xaxisSecond": {
          "axisPosition": "top",
          "showLabels": true
        },
        "customLegendEnabled": false
      },
      "title": "Bool Chart",
      "dropShadow": true,
      "enableFullscreen": true,
      "titleStyle": {
        "fontSize": "16px",
        "fontWeight": 400
      },
      "useDashboardTimewindow": true,
      "showTitleIcon": false,
      "titleTooltip": "",
      "widgetStyle": {},
      "widgetCss": "",
      "noDataDisplayMessage": "",
      "showLegend": true,
      "legendConfig": {
        "direction": "column",
        "position": "bottom",
        "sortDataKeys": false,
        "showMin": false,
        "showMax": false,
        "showAvg": true,
        "showTotal": false
      }
    },
    "row": 0,
    "col": 0,
    "id": "6481b4f3-2af8-ffbe-51cd-df37647b281b"
  },
  "aliasesInfo": {
    "datasourceAliases": {},
    "targetDeviceAliases": {}
  },
  "filtersInfo": {
    "datasourceFilters": {}
  },
  "originalSize": {
    "sizeX": 8,
    "sizeY": 5
  },
  "originalColumns": 24
}
```

**Comment by thhart** [comment]
@devaskim How does this solve my question, I don't need to display any random data! How this should be bind to the original data of my device?

**Comment by devaskim** [comment]
Did you try to import my widget and replace the random function with your data key without any pre-processing function?

**Comment by thhart** [comment]
I did this, the result remains the same, the data is type of number then and remains 0.

**Comment by devaskim** [comment]
Strange... re-check the type of data what come in to your pre-processing function - add at the begging `console.log(typeof value);` and look at *Console* of browser's DebTools

**Comment by thhart** [comment]
As stated above the type is always number in a chart context, it is string in a table context. In my screenshot you can see type in column "StatusDoor 3". The console shows number when used in the chart.
The data source is the same for both widget types. I also tested state widget but same "number" problem there.
The data  is coming in via JSON as telemetry data for a device and is only "true" or "false" however it is somehow treated/interpreted different in front of the widgets.

**Comment by thhart** [comment]
I am pretty convinced this is related to the telemetry source type being string, however I don't know how to influence this in the  JSON based transport, do you have any hints/tips how to check/change this?
How to check the data chain flow within Thingsboard itself? Which classes are involved in the data processing?

**Comment by devaskim** [comment]
> How to check the data chain flow within Thingsboard itself?
Enable debug mode for _Save timeseries_ rule chain node. In event tab of this node you will see all incoming data what will is being pushed to database.

**Comment by thhart** [comment]
I rather meant Thingsboard source code, but appreciate your feedback, will check this...

**Comment by devaskim** [comment]
The are a lot of entry points where data comes in to a server. Are you using gateway or pushing data behalf of device? What transport protocol (HTTP, MQTT and etc)?

I suggest to monitor and modify data via Rule Chain, because it is a common and next stage for steps what I described above. There is [Transformation rule node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node) what lets you check type of incoming data and modify it as you wish.
