### ISSUE TITLE
[Bug] Rule chain mqtt connection: when the ClientID is too long, you cannot connect to the mqtt server

### ISSUE THREAD

**Issue by bggmjxh** [thingsboard/thingsboard#6548]
Rule chain mqtt connection: when the ClientID is long, you cannot connect to the mqtt server.

When connecting external mqtt in the rule chain, I found that some can be connected and some cannot.

After debugging and looking for the answer, I found that the problem is the length of the clientid. A clientid that is too long cannot connect to the mqtt server in the rule engine of thingsboard.

However, you should know that the mqtt server is not necessarily built by us. The rules of some mqtt servers themselves specify the ClientID of the device, and the length of this ID may be 64 bits or even longer.
![image](https://user-images.githubusercontent.com/15259863/168238489-8587a55c-5b49-4616-ab2f-052648c6ba5a.png)
![image](https://user-images.githubusercontent.com/15259863/168238672-7fe485e5-cd50-4560-a537-1a4c04ab5a54.png)

**Comment by KenSense** [comment]
The ClientId should be unique for each device, why are you storing parameters in it.

**Comment by SuminDenys** [comment]
Hi @bggmjxh,

ThingsBoard supports ClientID which are between 1 and 23 UTF-8 encoded bytes in length. This limit covers most use cases of our users who use the MQTT Integration or MQTT Node.

Also, I want to inform you that we aren't planning to change the current limits for client ID. However, there is still some misunderstanding with the Client ID field, so I've created PROD-4236 requesting to add a character limit for the client ID field.

I am closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)

**Comment by sumin-denys** [comment]
Hi @bggmjxh,

I am pleased to announce that this issue has been resolved in version 3.8.0.

Please see the following [Pull Request](https://github.com/thingsboard/thingsboard/pull/11565)
