### ISSUE TITLE
[Question] Failed to build thingsboard 3.3.4.1,for Server UI Failure

### ISSUE THREAD

**Issue by madxuqf** [thingsboard/thingsboard#6553]
I've got the version 3.3.4.1 on Ubuntu 20.04, and blocked in built ,with the following info:

[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn install) @ ui-ngx ---
[INFO] Running 'yarn install' in /home/windy/thingsboard/ui-ngx
[INFO] yarn install v1.22.18
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.error Command failed.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.error Command failed.
[INFO] Exit code: 128
[INFO] Command: git
[INFO] Arguments: ls-remote --tags --heads git://github.com/MichaelZinsmaier/CurvedLines.git
[INFO] Directory: /home/windy/thingsboard/ui-ngx
[INFO] Output:
[INFO] fatal: Could not read from remote repository.
[INFO]
[INFO] Please make sure you have the correct access rights
[INFO] and the repository exists.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.3.4.1:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  1.404 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  2.071 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.170 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.077 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.660 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.446 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  0.671 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.254 s]
[INFO] Thingsboard Server Common Cluster API .............. SUCCESS [  6.279 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  2.223 s]
[INFO] Thingsboard Server Common Cache .................... SUCCESS [  0.527 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.099 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.960 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  0.987 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.370 s]
[INFO] Thingsboard CoAP server ............................ SUCCESS [  0.426 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.820 s]
[INFO] Thingsboard LwM2M Transport Common ................. SUCCESS [  1.668 s]
[INFO] Thingsboard SNMP Transport Common .................. SUCCESS [  0.886 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  0.673 s]
[INFO] Thingsboard Server Remote Edge wrapper ............. SUCCESS [  3.019 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.044 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.755 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  5.825 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  2.986 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.016 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 16.025 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 15.974 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 14.206 s]
[INFO] Thingsboard LwM2m Transport Service ................ SUCCESS [ 14.900 s]
[INFO] Thingsboard SNMP Transport Service ................. SUCCESS [ 14.949 s]
[INFO] ThingsBoard Server UI .............................. FAILURE [  2.556 s]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:00 min
[INFO] Finished at: 2022-05-15T15:50:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn install) on project ui-ngx: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128) -> [Help 1]

How to solve this problem? really appreciate any helps,thanks.

**Comment by spsims** [comment]
Same build error on Ubuntu 20.04 with version 3.3.4.1
Anyone have suggestions how to solve it?

**Comment by nguyenluongky** [comment]
I'm facing the same problem when build on Mac OS with version 3.3.4.1

**Comment by spsims** [comment]
OK. I found it's fixed on master branch with [d9b9d44](https://github.com/thingsboard/thingsboard/commit/d9b9d44e39a453ab54a35789fcfa8fff9ea7ef2f)

**Comment by madxuqf** [comment]
> OK. I found it's fixed on master branch with ([#6298](https://github.com/thingsboard/thingsboard/pull/6298))

It works！I got the master branch，and set a proxy, then succeed.

**Comment by yjt1216** [comment]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn
