### ISSUE TITLE
[Bug] Unable to setup Thingsboard on Kubernetes env. due to issues with postgres.

### ISSUE THREAD

**Issue by prasadfast** [thingsboard/thingsboard#6556]
Unable to create Thingsboard on kubernetes  env. due to  postgres database.

Env --> kubernetes , Docker, linux.
Single instance setup of Kubernetes.
Thingsboard version --> 3.3.4.1 version of docker images.

The environment of kubernetes contains zookeeper,kafka,postgres as well as tb-node containers.
The main issue is the kubernetes env. --> Thingsboard version is unable to create the respective schema on the database postgres.

Error --> Error admin settings doesn't exist.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Describe the bug**

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pon0marev** [comment]
Do you already have a database created? Have you done a thingsboard installation? Please attach a full log.
