### ISSUE TITLE
[rule node]How to analysis rule node exception

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#6557]
How to analysis rule node exception?
In my root rule chain, device profile rule node got NullPointException.
All error msg is only one line: "java.lang.NullPointerException".
How can i get more information to fix this error?

**Comment by devaskim** [comment]
Maybe there is stacktrace in [server's logs](https://thingsboard.io/docs/user-guide/troubleshooting/#read-logs)
