### ISSUE TITLE
[Bug] findEntityDataByQuery

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#6560]
Following the documentation for the api-endpoint "/api/entitiesQuery/find", I've tried to request both, an ENTITY_FIELD as well as a SERVER_ATTRIBUTE from my query.

The query works fine, if only request an ENTITY_FIELD. However, as soon as I include a SERVER_ATTRIBUTE I get an internal server error saying:

> {
	"status": 500,
	"message": "PreparedStatementCallback; bad SQL grammar [select count(*) from (select entities.* from (select e.id id, 'ASSET' entity_type, cast(e.name as varchar) as alias2, (coalesce(cast(alias3.bool_v as varchar), '') || coalesce(alias3.str_v, '') || coalesce(cast(alias3.long_v as varchar), '') || coalesce(cast(alias3.dbl_v as varchar), '') || coalesce(cast(alias3.json_v as varchar), '')) as alias3_value, alias3.last_update_ts as alias3_ts, 1 as attr_read, 1 as ts_read from asset e where e.tenant_id=? and (e.type = ?)) entities inner join attribute_kv alias5 ON entities.attr_read = 1 AND  alias5.entity_id=entities.id AND alias5.entity_type='ASSET' AND alias5.attribute_key=? AND alias5.attribute_type='SERVER_SCOPE'  AND (((alias5.long_v is not null and alias5.long_v > ?) or (alias5.dbl_v is not null and alias5.dbl_v > ?)) and ((alias5.long_v is not null and alias5.long_v < ?) or (alias5.dbl_v is not null and alias5.dbl_v < ?)))) result ]; nested exception is org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table \"alias3\"\n  Position: 134",
	"errorCode": 2,
	"timestamp": "2022-05-18T07:35:34.630+00:00",
	"subscriptionErrorCode": null,
	"subscriptionEntry": null,
	"subscriptionValue": null
}

This is my request-body:
```
{
  "entityFilter": {
    "type": "assetType",
    "assetType": "someType",
    "assetNameFilter": ""
  },
  "entityFields": [
    {
      "type": "ENTITY_FIELD",
      "key": "name"
    },
		{
			"type":"SERVER_ATTRIBUTE",
			"key":"someAttribute"
		}
  ],
  "keyFilters": [
    {
      "key": {
        "type": "SERVER_ATTRIBUTE",
        "key": "someAttribute"
      },
      "valueType": "NUMERIC",
      "predicate": {
        "operation": "GREATER",
        "value": {
          "defaultValue": 0,
          "dynamicValue": null
        },
        "type": "NUMERIC"
      }
    },
    {			
      "key": {
        "type": "SERVER_ATTRIBUTE",
        "key": "someAttribute"
      },
      "valueType": "NUMERIC",
      "predicate": {
        "operation": "LESS",
        "value": {
          "defaultValue":1000,
          "dynamicValue": null
        },
        "type": "NUMERIC"
      }
    }		
		
  ],	
  "pageLink": {
    "page": 0,
    "pageSize": 10,
    "sortOrder": {
      "key": {
        "key": "name",
        "type": "ENTITY_FIELD"
      },
      "direction": "ASC"
    }
  }
}
```

Any ideas on what I might be doing wrong?

By the way, the above "someAttribute" is not present for all the asssets I'm querying. Still, the key filters work. It only fails if I add the server-attribute into the entityFields-object

**Your Server Environment**
Version 3.3.1 PE

**Comment by SuminDenys** [comment]
Hi @eeitnn,

In order to fetch both SERVER ATTRIBUTE and ENTITY FIELD you need to change your query and add _**latest value object**_.

I have added the JSON file with the query, you can use it to understand what exactly you need to change in your query.

Also, here is a screenshot of an example from Swagger:
![image](https://github.com/user-attachments/assets/d97a9ef0-ef54-4fc7-9d93-a692decfdb4a)

[query_attribute_and_field.json](https://github.com/user-attachments/files/16711297/query_attribute_and_field.json)
