### ISSUE TITLE
[Question] access LegendComponent from Widget Custom Action

### ISSUE THREAD

**Issue by ThomasPrioul** [thingsboard/thingsboard#6561]
**Component**

 * UI

**Environment**
 * ThingsBoard: PE 3.3.4.1

**Description**
The line chart component allows us to select and hide series by clicking on a legend item.
![image](https://user-images.githubusercontent.com/15314924/169001828-50df20c3-16e6-4a68-a573-9adc31f82cff.png)

I would like to do the same but programmatically from a widget custom action (to clear currently hidden series for example).

I found in TB source code the LegendComponent and the following method :
https://github.com/thingsboard/thingsboard/blob/50b54a71c6e5a44df7770583263a2173b683cbca/ui-ngx/src/app/modules/home/components/widget/legend.component.ts#L54-L60

And on inspection, I can see the **tb-legend** component is created for the widget, through a HTML template.

![image](https://user-images.githubusercontent.com/15314924/169002446-e8290f38-31f9-46c3-89c2-75d3794968dc.png)

How can I access a reference to the LegendComponent from the custom action function, if it is possible ?

Thanks

**Comment by devaskim** [comment]
Maybe this code will help you. Add those lines to your custom function and explore output in DevTools Console tab
```
console.log(widgetContext.flot.subscription.legendConfig);
console.log(widgetContext.flot.subscription.legendData);
```

**Comment by ThomasPrioul** [comment]
Thanks for your help, I didn't know about the subscription object.
I have achieved 50% of my goal thanks to you. Now clicking my button toggles each series visibility, but unfortunately the legend is not updated (Angular binding does not see any change nor click event for LegendComponent). As soon as I click an element on the legend (to toggle it), the rest updates accordingly to my previous action, but also to my last action...

Before custom action click :
![image](https://user-images.githubusercontent.com/15314924/169031844-1abe44d1-dafa-4a07-adc9-9d7a68467e5f.png)

After custom action click :
![image](https://user-images.githubusercontent.com/15314924/169031957-d22fff42-32dd-4752-9a9c-52a0eba61ad9.png)

After clicking "moyenne" legend btn, following custom action click :
![image](https://user-images.githubusercontent.com/15314924/169032079-68eacd73-644a-4e57-9b0c-4d79492b3e63.png)

**Comment by devaskim** [comment]
Try to call `widgetContext.detectChanges();` after all your manipulation.

By the may, if it would be interesting for you, you can [share your widget](https://github.com/devaskim/awesome-thingsboard) with community.

**Comment by ThomasPrioul** [comment]
I tried this, but the problem is, it's not affecting the LegendComponent which is not in the scope of my component.

I'm not using a custom widget, I'm using a custom action on a Timeseries line chart widget (the one included in TB) :

`function ($event, widgetContext, entityId, entityName, additionalParams, entityLabel) {}`

```js
for (const id of Object.keys(widgetContext.subscriptions)) {
    const subscription = widgetContext.subscriptions[id];
    if (!subscription.legendData) return;
    
    for (let i = 0; i < subscription.legendData.keys.length; i++) {
        toggleHideData(i, subscription);
    }
}

// This does nothing :-(
widgetContext.detectChanges(true);
widgetContext.detectContainerChanges();

function toggleHideData(index, subscription) {
    const dataKey = subscription.legendData.keys.find(key => key.dataIndex === index).dataKey;
    if (!dataKey.settings.disableDataHiding) {
        dataKey.hidden = !dataKey.hidden;
        subscription.updateDataVisibility(index);
    }
}
```

**Comment by devaskim** [comment]
I am not a good JS developer so sorry for the following question
You are using `const`
`const subscription = widgetContext.subscriptions[id];`
but then update this object
`subscription.updateDataVisibility(index);`

**Comment by ThomasPrioul** [comment]
Yes it is ok, **const** guarantees that you don't locally reallocate the variable subscription to something else. It does not mean that you're modifying a clone of the original object. My code already works for the most part, it's just that the flot chart used underneath is not refresh by the LegendComponent, which lives outsides the WidgetComponent, if I understand correctly.
There is also the **let** keyword.
You should not use **var** keyword in modern JS, it has bad side effects.

**Comment by devaskim** [comment]
> but not the LegendComponent, which lives outsides the WidgetComponent

I didn't find in the source code that TbFlot uses LegendComponent
```
$ grep -R LegendComponent  ui-ngx/src/
ui-ngx/src/app/modules/common/modules-map.ts:import * as LegendComponent from '@home/components/widget/legend.component';
ui-ngx/src/app/modules/common/modules-map.ts:    '@home/components/widget/legend.component': LegendComponent,
ui-ngx/src/app/modules/home/components/home-components.module.ts:import { LegendComponent } from '@home/components/widget/legend.component';
ui-ngx/src/app/modules/home/components/home-components.module.ts:      LegendComponent,
ui-ngx/src/app/modules/home/components/home-components.module.ts:    LegendComponent,
ui-ngx/src/app/modules/home/components/widget/legend.component.ts:export class LegendComponent implements OnInit {
```

**Comment by ThomasPrioul** [comment]
I found the issue, what I needed was not to call detectChanges(), but to update the subscription object itself, not just its data.
The final custom action code is :

```js
for (const id of Object.keys(widgetContext.subscriptions)) {
    const subscription = widgetContext.subscriptions[id];
    if (!subscription.legendData) return;
    
    for (let i = 0; i < subscription.legendData.keys.length; i++) {
        toggleHideData(i, subscription);
    }
    
    subscription.update();
}

function toggleHideData(index, subscription) {
    const dataKey = subscription.legendData.keys
        .find(key => key.dataIndex === index)
        .dataKey;
        
    if (!dataKey.settings.disableDataHiding) {
        dataKey.hidden = !dataKey.hidden;
        subscription.updateDataVisibility(index);
    }
}
```

Thank you for telling me about subscription @devaskim
