### ISSUE TITLE
Error-Messages in wrong language

### ISSUE THREAD

**Issue by fraenku** [thingsboard/thingsboard#6565]
**Describe the bug**
Translate error-messages during login

**Your Server Environment**
cloud.thingsboard.io as well as local installation

**Your Client Environment**
Desktop, 
Windows
Chrome

**To Reproduce**
1. I've german as selected language
2. I want to login but do not remember my password
3. The error-message "Invalid username or password"  appears

**Expected behavior**
3. The error-message should appear in german or be translatable

**Additional context**
I suppose it is linked to https://github.com/thingsboard/thingsboard-edge/blob/2d986cd25ccdff7f0b3181f275edd86ceb442578/application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java

**Comment by devaskim** [comment]
It is by design. UI part of TB has translation but server uses only English

**Comment by fraenku** [comment]
This is understandable from a technical point of view, but not from a customer point of view.

Using wrong credentials is a typical use-case which is happening quite frequently and having the error-message here in another language is somehow disturbing.

**Comment by mardaisado** [comment]
+1

**Comment by mykhailokornieiev** [comment]
Hi. We have such feature request in backlog, but there is no set timeframe or even if it will be implemented at all. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new information and additions to the platform in the subsequent releases.
