### ISSUE TITLE
creating entities table with one column

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#657]
Hey all,

I want to display telemetry data from different devices in an entities table.
I would like to have one column with all the values from the devices.
Now I'm only able to make an entities table like in the printscreen. 
I would like all the blank spaces disappear.

Thanks in advance

![printscreen](https://user-images.githubusercontent.com/36699523/37475792-cdf0fb7e-2873-11e8-991c-15539f18edc6.jpg)

**Comment by vparomskiy** [comment]
You will need to create a custom widget for this. 
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
