### ISSUE TITLE
How to create custom breadcrumbs in Thingsboard ?

### ISSUE THREAD

**Issue by chhavish123** [thingsboard/thingsboard#6571]
We are trying to integrate TB and Angular app. But not able to combine default TB breadcrumbs with Angular app flow. So is there any way to combine default TB breadcrumbs with third party app like Angular with custom menus of white labeling so that Angular app flow can run with default TB breadcrumb structure?

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Comment by jrkubic** [comment]
Any news with this? Would be very interested in having the ability to customize and abuse custom breadcrumbs/navigation.
