### ISSUE TITLE
Issues with tb-web-report | Dashboard PDF export not working [Bug] 

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#6574]
**Describe the bug**
Dashboard PDF export produces : `{"status":503,"message":null,"errorCode":2,"timestamp":"2022-04-13T13:02:04.463+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}` error

**Your Server Environment**
  * docker deployment 3.3.4.1PE

**Your Client Environment**
**Desktop:**

* OS: Win 10
* Browser chrome
* Version 101.0.4951.67

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Export Dashboard'
3. Scroll down to 'Export as PDF'

Expected behavior
I expect to get a PDF file.
But I get:
 `{"status":503,"message":null,"errorCode":2,"timestamp":"2022-04-13T13:02:04.463+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}`

**Screenshots**
![image](https://user-images.githubusercontent.com/98737620/169303247-bd664307-fded-471d-a0f3-f44a9829652d.png)

**Additional context or clues**

1. I use my tb in combination with traefik. 

It is set up so that any http is forwarded to https, (80 to 443) and that 'myurl.com' is forwarded to the tb service

2. My web report log says:

```
2022-05-13 06:15:20,860 [main] INFO: Bind address: 0.0.0.0
2022-05-13 06:15:20,861 [main] INFO: Bind port: 8383
2022-05-13 06:15:20,861 [main] INFO: Starting chrome headless browser...
2022-05-13 06:15:20,862 [main] INFO: Chrome headless browser executable: /usr/share/tb-web-report/chromium/chrome
2022-05-13 06:15:21,080 [main] INFO: Started chrome headless browser.
2022-05-13 06:15:21,081 [main] INFO: Headless chrome browser version: HeadlessChrome/97.0.4691.0
2022-05-13 06:15:21,086 [main] INFO: ==> 🌎  ThingsBoard Web Reporting Service listening on http://0.0.0.0:8383/.
2022-05-13 06:17:37,958 [ReportController] INFO: Generating dashboard report: https://MY_URL:443/dashboard/5a7016f0-b571-11ec-a0e3-bd4858cf551f
2022-05-13 06:19:38,078 [ReportController] ERROR: Navigation timeout of 120000 ms exceeded:
TimeoutError: Navigation timeout of 120000 ms exceeded
    at /snapshot/web-report/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:107:111
    at async FrameManager.navigateFrame (/snapshot/web-report/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/snapshot/web-report/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/snapshot/web-report/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async generateDashboardReport (/snapshot/web-report/api/controllers/tbWebReportController.js)
```

I can open any dahsboard drom any browser via the `https://MY_URL:443/dashboard/5a7016f0-b571-11ec-a0e3-bd4858cf551f ` URL, so in my understandung, the routing should be set up correctly. (?)

3. when I go to scheduler and set the URL to `http://localhost:8080` and press `generate test report`, it weirdly enough works just fine. 

4. This issue seems very similar to: 
[[Bug] PE version PDF Export fails? #5960](https://github.com/thingsboard/thingsboard/issues/5960)

Sadly I am still stumped and dont know what to do, I cant put together the puzzle pieces. (also I admit my knowledge on traefik is limited)

**Comment by medutySMST** [comment]
2 possible solutions are as follows: 

- acc. to the solution in #5960 possibly customizing the dockerfile or entrypoint to edit /etc/hosts to include `internalserverip myurl.com`

- set up a seperate tb-web-report docker container.
   however at the moment I iam running into `hostname cant be null` and `Temporary failure in name resolution` errors.

**Comment by medutySMST** [comment]
edit solution 2 does not solve the underlying problem

**Comment by medutySMST** [comment]
update: 

- both solutions do not seem to work, however not sure if I am doing something wrong. 
- dont know how to continue

**Comment by trikimiki** [comment]
that is most definitely a hostname resolution issue, caused by traefik
Web Report service, when creating a report, tries to navigate to the same URL from which you called "Export dashboard" action in browser.
most likely, as you have deployed in docker, Web Report container cannot resolve your hostname; you need to ensure that your docker network can resolve the URL
another approach is to deploy Web Report in "host" network mode, or as a package (https://thingsboard.io/docs/user-guide/install/pe/windows/#step-9-install-thingsboard-web-report-server-component)

**Comment by medutySMST** [comment]
Hello! Thank you for commenting. 
I still havent solved this, can you suggest a few steps to make sure that my docker network can resolve the URL?

**Comment by trikimiki** [comment]
apart from the mentioned "host" network mode, I am unsure how you could do that.
overall, you only need web report to resolve this domain, so there is an option to install it elsewhere or in another way; e.g., if your OS could resolve the domain, you can [install web report as the service](https://thingsboard.io/docs/user-guide/install/pe/windows/#step-9-install-thingsboard-web-report-server-component) (but ensure that the version would match TB version)

there is [this docker parameter](https://docs.docker.com/compose/compose-file/05-services/#extra_hosts) - in theory, it does what is needed

**Comment by medutySMST** [comment]
How would you configure the extra hosts parameter in this case to make it work?

**Comment by medutySMST** [comment]
this issue seems to be resolved in newer versions, I use an instnce of TB 3.8.1 PE with traefik and web report works fine
