### ISSUE TITLE
avg execution time: 94.95

### ISSUE THREAD

**Issue by freebooterish163** [thingsboard/thingsboard#6576]
**Component**
 * Rule Engine

**Description**
When I send a messages at an interval of 100 milliseconds, everything is normal, but when the interval becomes 10 milliseconds, the  80% messages time out, I sent 2300 messages,BUT only 337 show in "Save Timeseries" Debug Mode Event windows, the thingsboard.log shows:
[tb-rule-engine-consumer-47-thread-1 | Main-8] INFO  o.t.s.s.q.TbMsgPackProcessingContext 
- [Main][8fda6ff0-d747-11ec-80d7-b5da0ea21eed] 
avg execution time: 94.95238095238095. [RuleChain: Thermostat|RuleNode: Save Timeseries(8fda6ff0-d747-11ec-80d7-b5da0ea21eed)]  

- [Main][8fda6ff0-d747-11ec-80d7-b5da0ea21eed] 
max execution time: 100. [RuleChain: Thermostat|RuleNode: Save Time
series(8fda6ff0-d747-11ec-80d7-b5da0ea21eed)]

Timeout to process message: TbMsg(queueName=Main, 
id=e4e3720c-bea8-417e-bf1a-7a527a42356d, 
ts=1652957457195, 
type=POST_TELEMETRY_REQUEST, 
originator=90774c30-d747-11ec-80d7-b5da0ea21eed, 

How can i solve the telemetry lost problem, 
thanks.

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.4.1 + Kafka + Cass
[thingsboard.log.gz](https://github.com/thingsboard/thingsboard/files/8732241/thingsboard.log.gz)
andra
<img width="665" alt="Screen Shot 2022-05-20 at 00 48 11" src="https://user-images.githubusercontent.com/94213725/169354609-63367f75-e08f-4c85-9447-6d4f64d264f1.png">

 * Browser: Chrome 101

**Comment by epalchenko** [comment]
Hello,
There is no single answer to such problems, as an option it can be a lot of JS executions, for this you need to either switch to TBEL or use microservices and add more executors, but again, there is no single solution. You need to analyze the instance - and what loads it so much with the number of messages when you have a timeouts.
New
[10:32](https://thingsboard.slack.com/archives/D04U8RH0GJ2/p1716276721372039)
Please re-create the new ticket with detailed screenshots of api usage, rule chain logic to discover your workflow.
