### ISSUE TITLE
ui-ngx:Failed to load configuration ui resources

### ISSUE THREAD

**Issue by momochaasdf** [thingsboard/thingsboard#6577]
when ui-ngx is detach from thingsboard, then use nginx to deploy it.
at rule chain page an error happend:
"ui-resources-load-error": "Failed to load configuration ui resources."

console is warning: Translation for rulenode.type-flow doesn't exist.

how do i update ? thanks.

<img width="1280" alt="微信图片_20220520180114" src="https://user-images.githubusercontent.com/18320263/169504921-cd923c02-9020-45a2-95e0-e67d3c5287d9.png">

**Comment by ssakharova** [comment]
Hello @momochaasdf,

After an upgrade (or some particular changes in the database), you can encounter this error while opening or editing any Rule Node: “Failed to load configuration UI resources".

To fix it, you need to clear your browser cache. To do so, you can try refreshing the page by forcing a cache refresh (by default Ctrl + F5) or follow the guide to clear the cache:

Chrome: [Clear cache & cookies - Computer - Google Account Help](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop) 
Firefox: [Clear cookies and site data in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox)


Best regards,
Sofiia
