### ISSUE TITLE
[Feature Request] Fix Postgres Issue with LIMIT

### ISSUE THREAD

**Issue by ganzuoni** [thingsboard/thingsboard#6578]
Defining an alarm dashboard the resulting query ends with the clause
 order by created_time DESC limit xx offset yy

when the related entity has cardinality > 100 this kind query hits the known PG issue with LIMIT clause
In my use case the generated SQL run in PSQL takes > 8 seconds when cardinality > 1000
it takes > 2 when cardinality > 100

As described in several places, adding an extra dummy column in order by clause fixes the issue, i.e.
 order by created_time, id DESC limit xx offset yy

in my use cases the query runs in few msec

**Comment by pon0marev** [comment]
Could you please let me know if this is reproducible on version 3.5.0+? Because the alarms have been significantly redesigned in version 3.5.0.

**Comment by pon0marev** [comment]
We want to inform you that we have closed your ticket as we have not received any updates on this issue. If you still have questions or encounter similar issues after upgrading to the latest version, please reopen this issue.
