### ISSUE TITLE
[Question] Rule Chain unusual behavior

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#6579]
**Component**
 * Rule Engine

**Description**

I have 4 of the same custom node instantiated in a rule chain, which are "fired" with a different generator each.  
The custom node just makes a get query to an ip camera with digest auth and listens for the camera to generate an event.  This listening is done in a separate thread and every time the camera generates an event, the node outputs an out message.  
So I get a input message, generated by the generator and then they are all outs messages. 
At the time of initializing the rule chain, this flow works fine, but after a few hours, the entire rule chain stops working, except for the custom nodes.  
That is, if i send telemetry through api, the message does not appear in the rule chain and from the custom nodes, the output they generate does not go to the script node they have connected. 
Nothing comes in the logs, does anyone know what could be happening?

**Environment**

 * ThingsBoard: 3.3.3 CE

**Comment by JacksonBowe** [comment]
When you declare variables in your custom scripts are you making sure to declare them all liek `var x = 10`? If you are in the habit of writing just `x = 10` then you will have issues. See #5270 if this is possible.

It's possible that the error is happening in your TB instance, not in the rule node. I'd have a look at the TB error logs. Can't recall exactly how to do that right now but the process is documented somewhere on the TB website.
