### ISSUE TITLE
Telemetry persistence policy

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#658]
Is there a data persistence policy where we specify the time to live for a time series?

**Comment by ashvayka** [comment]
This is available only in case you use Cassandra. See system telemetry rule. There is TTL parameter.

**Comment by darkfader** [comment]
ListenableFuture<List<Void>> save(TenantId tenantId, EntityId entityId, List<TsKvEntry> tsKvEntry, long ttl);

**Comment by Karabiy** [comment]
now the TTL is also available for PostgreSQL. It is so from the 2.5+ version. 

> Is there a data persistence policy where we specify the time to live for a time series?

**Comment by Tangerino** [comment]
Why this is closed? How do I use it for instance via HTTP API?

**Comment by Manusisko** [comment]
I've been testing the TTL on the Rule Chain for the save timeseries data, with Postgresql database and in version 2.5.2. Still TTL has no effect on the persistance of telemetries, they remain. (Tested with intervals of 1 hour and 1 second).

**Comment by bugggg90** [comment]
Thank god.

**Comment by Karabiy** [comment]
Please, refer to the link below regarding how to use the TTL. 

Save Timeseries rule node option to set TTL: https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-timeseries-node

Please, note, that those works only in case if the cassandra database is being used. 

You can also set the default global TTL for the database of yours. For those reasons you need to refer to the thingsboard.yml and set the environmental variables to the values you are looking for.
Those can be set for the telemetry and the events ( The events data is the data being generated on the debug mode being turned on for node, data converter, integration, etc. ).

Please, set those in the thingsboard.conf file and refer to the thingsboard.yml file only to get the environmental variables. It is the same logic as for the license key, so, for example, in case if you would have want to change the MQTT enabled ( the MQTT API to stop ) to the disabled, for the thingsboard.conf file you would have added the next row: 
export MQTT_ENABLED=false

After all the changes will be applied, it is required to have the thingsboard restart, to have the changes to be applied. 

The thingsboard.yml file is located in the same directory as the thingsboard.conf. The path for the directory is /etc/thingsboard/conf/

Please, let me know if you have any questions or concerns.
