### ISSUE TITLE
XML reading from REST API in RuleChain

### ISSUE THREAD

**Issue by NicolaBlasuttigh** [thingsboard/thingsboard#6580]
Hello everyone.
I'm trying to read external data with REST API as in this tutorial.

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/get-weather-using-rest-api-call/

The problem is that my server answer with xml text and not with a json payload.
For this reason, the (blue) Script node within RuleChain does not accept the input and I cannot parse the xml text.

Does anyone know how to get around the problem? Should I use some other node? Or is there no solution?

Thank you.

**Comment by santobedi** [comment]
I'm on TB Professional. TB has no node converting XML to JSON.

**Comment by santobedi** [comment]
I ended up making a middleware API to convert XML to JSON. No solutions from the Thingsboard.

**Comment by ssakharova** [comment]
Hello @NicolaBlasuttigh, @santobedi, @rjarman,

I consulted with the developers regarding this case. They do not anticipate adding improvements for parsing XML strings or support for XML strings in future releases, as XML is considered an outdated markup language.
