### ISSUE TITLE
Is there a way to login to thingsboard docker instance via Rest API ( from another container ) ?

### ISSUE THREAD

**Issue by S0UL4** [thingsboard/thingsboard#6583]
**Component**

 * UI

**Description**

I'm running Thingsboard instance, in a docker container, and added an iframe in another docker web instance to thingsboard instance, 
 What I want is when I login to my web service with the same credentials of thingsboard, I want to see that thingsboard has logged in automatically also and i can manage devices directly without login in to thingsboard again ( like the principe of SSO ), i tried to use LocalStorage of web browsers to force thingsboard to login automatically after getting logged into my web service but due to browser security reasons this was impossible.. any idea please?

**Environment**

 * ThingsBoard: latest docker image instance CE
 * Browser: google chrome

**Comment by devaskim** [comment]
Here is [login REST endpoint](https://demo.thingsboard.io/swagger-ui/#/login-endpoint). If you forward ports [in right way](https://thingsboard.io/docs/user-guide/install/docker/#choose-thingsboard-queue-service), you will have access to REST API.

**Comment by S0UL4** [comment]
> Here is [login REST endpoint](https://demo.thingsboard.io/swagger-ui/#/login-endpoint). If you forward ports [in right way](https://thingsboard.io/docs/user-guide/install/docker/#choose-thingsboard-queue-service), you will have access to REST API.

Thanks for your reply, but i have added thingsboard as an Iframe in my flask application so what i want to do is when a user login to my flask app and click on thingsboard icon he will get access automatically with the same credientials to thingsboard but according to some web browser security i couldn't force localstorage and add the jwt tokens responses of the Login requests of the thingsboard to thingsboard localstorage, so the user when clicks on thingsboard icon in my flask app will need to re-enter the credentials to login to thingsboard UI again.. i'm looking for a CAS Server to help me with this but i think this is not possible as thingsboard has a plugin for oAUTH and not for Cas servers..

**Comment by devaskim** [comment]
Got it. Did you try [postMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communication between iframe and browser page? Here is an attempt to solve localStorage/iframe challenge.

**Comment by S0UL4** [comment]
Thanks @devaskim  for your reply ! but yes i have tried a lot of tricks .. for this one i should enter to the container and add some line of codes in thingsboard so it accepts the request from my flask application to save the localStorage in it. I think the best solution is to go with oAuth2 authentification.. i'm working on this now

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
