### ISSUE TITLE
[Question] Is it supported to publish using MQTT over websockets?

### ISSUE THREAD

**Issue by javierbelenguer** [thingsboard/thingsboard#6586]
I've been testing publishing using MQTT over websockets since it would allow me to avoid firewall restrictions and it may be more efficient than HTTP requests, but I can't get it to establish connection with thingsboard, meanwhile HTTP requests and MQTT over TCP work properly. 
I'm currently using MQTT.js on the same machine to test it, but I've also tried with MQTTBox and MQTTLens using Chrome.

I haven't seen it mentioned anywhere whether it's supported or not so I thought of asking here.

Is it supported to publish using MQTT over websockets? If so, are there any examples available?

**Comment by devaskim** [comment]
This is not implemented as I know

**Comment by samkristoff** [comment]
I confirmed with ThingsBoard that MQTT over websockets is not currently supported.

You could use the [websocket or HTTP API ](https://thingsboard.io/docs/user-guide/telemetry/#websocket-api ) from the browser.

**Comment by pon0marev** [comment]
MQTT over WebSockets is not currently implemented in the thingsboard. The development team is considering implementation.

**Comment by baigod** [comment]
This function is too important. We look forward to the thingsboard team's early implementation
