### ISSUE TITLE
[Question] Walk through data array in rule engine

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6594]
**Component**
 * Rule Engine

**Description**
Is there any analog of loop in Rule Engine? So what I point out to my data array and Rule Engine processes each element of that array as it does now for a single data item.

*For example*: When a new user signs up, I want that Rule Engine automatically assigns several dashboard to that user. How to do it for a single dashboard we discuss in #6466 and here is [my implementation](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/assign-dashboard-to-new-user). But how to it for several dashboards or something other data items?

**Environment**
 * ThingsBoard: 3.3.4.1

**Comment by ashaforost** [comment]
Hi @devaskim ,

If you have to iterate through the list of dashboard Ids, you can put them in an array of JSON objects as such: `[{dashboard_id:<some id 1>}, {dashboard_id: <some id 2>}]`
This way thingsboard will fetch one JSON at a time, process it, and move to the next one, and there's no need to do a complex logic with several rule chains to create a loop.

Let me know if there are any questions left.

**Comment by devaskim** [comment]
> This way thingsboard will fetch one JSON at a time, process it, and move to the next one...

What Rule Chain node does this magic?

For example, I got list of [tenant's dashboards](https://demo.thingsboard.io/swagger-ui/#/dashboard-controller/getTenantDashboardsUsingGET), Transformation node re-formats the list to `[{dashboard_id:<some id 1>}, {dashboard_id: <some id 2>}]`. What is my next step?

**Comment by devaskim** [comment]
> This way thingsboard will fetch one JSON at a time, process it, and move to the next one...

@ashaforost  What Rule Chain node does this magic?

For example, I got list of [tenant's dashboards](https://demo.thingsboard.io/swagger-ui/#/dashboard-controller/getTenantDashboardsUsingGET), Transformation node re-formats the list to `[{dashboard_id:<some id 1>}, {dashboard_id: <some id 2>}]`. What is my next step?

**Comment by ashaforost** [comment]
Hi @devaskim 

A transformation script rule node is all you need. If the rule node returns an array, thingsboard automatically fetches each object  in the list and passes it to the next rule chain.

**Comment by devaskim** [comment]
I got Transformation rule node working after the following modification:
```
// DO NOT WORK
return [{dashboard_id: 1 }, 
        {dashboard_id: 2 }];

// WORK 
return [{ msg: {dashboard_id: 123 }}, 
        { msg: {dashboard_id: 321 }}];
```
Thanks @ashaforost  
By the way, is this feature is documented somewhere?
