### ISSUE TITLE
[Question] How to migrate a Thingsboard server data to a new one?

### ISSUE THREAD

**Issue by fabioafreitas** [thingsboard/thingsboard#6598]
**Component**
 * Installation

**Environment**
 * OS:  Debian GNU/Linux 11 (bullseye)
 * ThingsBoard: 3.3.4.1
 * Database: Only Postgres

**Description**
How to transfer the data from a Thingsboard server into a new one?

I followed the discussion of this [question](https://github.com/thingsboard/thingsboard/issues/3641), that redirected me to the [upgrade process page](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-3341pe). In there a followed the tutorial and create the backup file of my database:

```
sudo -Hiu postgres pg_dump thingsboard > thingsboard.sql.bak
```

I also created a backup of the **/etc/thingsboard/conf** folder, as suggested in the discussion.

Then, in a brand-new server, I followed the [installation](https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardDatabase=postgresql) steps until the step 6, where I executed the Thingsboard installation script without the **--loadDemo**.

```
sudo /usr/share/thingsboard/bin/install/install.sh
```
After that, I uploaded the backups of **/etc/thingsboard/conf** folder and database data using WinSCP. Replaced the current **/etc/thingsboard/conf** folder with the backup and imported the database data using the command below:

```
psql -U postgres -d thingsboard -h 127.0.0.1 -W < thingsboard.sql.bak
```

Then I started the server **sudo service thingsboard start** and waited a few minutes to see if the migration worked, but it didn't. What can I do to solve this?

**Comment by mfalkvidd** [comment]
What does the thingsboard log file say? The information there will likely be the quickest way to figure out why it isn't working.

**Comment by fabioafreitas** [comment]
I found the tutorial in another [issue](https://github.com/thingsboard/thingsboard/issues/3611). Apparently i followed the steps correctly, but it results in the logs above.

**Comment by mfalkvidd** [comment]
Nothing useful in that log unfortunately. The thingsboard log file will be the key.

**Comment by KenSense** [comment]
If it is the PE version you will need to reactivate your license key on https://license.thingsboard.io/login
(Just like you would need to do if your restore the VM)

**Comment by KenSense** [comment]
Maybe asking the obvious but you did stay with the same Thingsboard CE version for the new server right?

**Comment by fabioafreitas** [comment]
Yes, both are the same version. 3.3.4.1 CE

**Comment by fabioafreitas** [comment]
Hey guys, any news?

**Comment by fabioafreitas** [comment]
Hey guys, I finally found a way to do the migration correctly, by following the steps posted in this [discussion](https://groups.google.com/g/thingsboard/c/P7TcOnVIRqg). I'll post the steps below in case the link breaks.
--------------------------------------------------------------------------
On the first computer, backup the database using postgres dump tool:

pg_dump thingsboard --host=localhost --username postgres -W > thingsboard.dump

Then, backup the /etc/thingsboard/conf directory:

sudo tar cvfz tb.tar.gz /etc/thingsboard/conf/*

Copy thingsboard.dump and tb.tar.gz to the new computer. On the new computer, with a fresh install of Thingsboard as per the posted instructions:

Stop Thingsboard, then:

sudo su postgres
dropdb thingsboard    # this removes the database
createdb -T template0 thingsboard
psql thingsboard -U postgres -W < thingsboard.dump

Copy the /etc config files:

cd /
sudo tar xvfz /home/ubuntu/tb.tar.gz

Start Thingsboard.
