### ISSUE TITLE
https://demo.thingsboard.io/swagger-ui.html   is not working due to 'X-Authorization' header.

### ISSUE THREAD

**Issue by akashtalole** [thingsboard/thingsboard#66]
when "token":"$YOUR_JWT_TOKEN" is passed in Authorize section, but when api call is happen Bearer is not present in request headers.

follwing is the curl call generated by swagger 
curl -X GET --header 'Accept: application/json' --header 'X-Authorization: $YOUR_JWT_TOKEN' 'https://demo.thingsboard.io:443/api/tenant/devices?deviceName=30' 

When Bearer is given it works as follows
curl -X GET --header 'Accept: application/json' --header 'X-Authorization: Bearer $YOUR_JWT_TOKEN' 'https://demo.thingsboard.io:443/api/tenant/devices?deviceName=30' 

So why swagger is not appending "Bearer"  in api call.

**Comment by ashvayka** [comment]
@akashtalole This is a good questions, but probably to swagger and not thingsboard team. We will review what can be done to simplify the usage.

**Comment by akashtalole** [comment]
The pr [](https://github.com/OAI/OpenAPI-Specification/pull/807)  in swagger seems to be resolved this issue.

**Comment by akashtalole** [comment]
PR    https://github.com/OAI/OpenAPI-Specification/pull/807 seems to be resolved in swagger openapi .
