### ISSUE TITLE
[Question] Thingsboard and CAS SSO Server, is it possible?

### ISSUE THREAD

**Issue by S0UL4** [thingsboard/thingsboard#6604]
**Component**

 * UI

**Description**
I want to integrate thingsboard to work with a CAS SSO Server, is it possible ? because i only found that i could use the oAuth method but didn't find any plugin for a CAS Server.. any idea? Thanks in advance..
**Environment**

 * OS:  running thingsboard on docker container
 * ThingsBoard: latest
 * Browser: Chrome

**Comment by devaskim** [comment]
I think [this doc page](https://thingsboard.io/docs/user-guide/oauth-2-support/#custom-mapper) will help you

**Comment by pon0marev** [comment]
Did the article provided by devaskim help you solve your question?

**Comment by S0UL4** [comment]
> Did the article provided by devaskim help you solve your question?

Actually it seems that TB doesn't support CAS protocol, so i'm switching to use oAuth2 as it supports that protocol.
