### ISSUE TITLE
[Question]About get Historical data value from TB CE version

### ISSUE THREAD

**Issue by zlfkdbstj** [thingsboard/thingsboard#6605]
Hello Everyone I'm currently work on my graduation project in University. My TB version is CE and I tried to upgrade PE but University security issue occur and PE version not allowed.
Our thingsboard installed in ubuntu with Cassandra and Postgresql.And set up timestamp, rule chain, telemetry data.
I tried to use command for view data "select distinct entity_type, entity_id, key, partition from thingsboard.ts_kv_cf;"
And get csv command by "copy thingsboard.ts_kv_cf to 'database.csv';"
And i try to exact data from ts_kv_latest_cf but it won't show the data it only shows device and key.
For example, i want get csv data for a given device, key, and time period, can you write a query to extract a table of the form:

| Device | Key | Time | Value |

This is my last project for graduate University...
In case if CE can't get historical data can you guys please confirm is it possible or impossible?

Kind regards 
![Screenshot_20220527-075126_Office](https://user-images.githubusercontent.com/74388118/170589256-736dcebd-7425-4b2e-95c1-1043cf9bfc25.jpg)
![Screenshot_20220527-075118_Office](https://user-images.githubusercontent.com/74388118/170589259-9e87c11d-7514-433f-b0a1-de6495897a08.jpg)

**Comment by mde2017** [comment]
Hi @zlfkdbstj,

the _ts_kv_latest_cf_ stores no historical data, only the most recent values for Entity & Key. Therefore everything is working as it should.

Why not use the _ts_kv_cf_ table as you already mentioned?
The telemetry values can be retrieved by adding the according fields like e.g. _bool_v_ or  _long_v_ to your query.

Alternatively, you could also fetch the data via REST API (see telemetry-controller in the Swagger UI):
https://thingsboard.io/docs/reference/rest-api/
https://demo.thingsboard.io/swagger-ui/#/telemetry-controller
