### ISSUE TITLE
Hide Columns in Time series Table

### ISSUE THREAD

**Issue by hetvishah08** [thingsboard/thingsboard#6606]
**Component**

 * UI

**Description**
Hi,
I'm using Thingboard Professional edition and I'm using a time series table to show the data. I'm doing some processing in the cell-content function hence I need to access a few variables for it but I don't want to show that data as a column. How do I hide it? 

I came across this pull request :
https://github.com/thingsboard/thingsboard/pull/4235

Here it is mentioned that "Ability to hide columns" has been implemented for the time series table too but I don't see that option anywhere in the one I'm using.

**Environment**

 * ThingsBoard: 3.3.2 version

**Comment by Backdraft007** [comment]
In the advanced tab of the data key, you can hide a column. It is there where you enable the cell content function.

But I don't understand why you use the cell content function and hide this column?

**Comment by hetvishah08** [comment]
> In the advanced tab of the data key, you can hide a column. It is there where you enable the cell content function.
> 
 I don't see this option for time series table data keys. 

![timeseries table](https://user-images.githubusercontent.com/34642195/171111892-22fc5569-747c-41f8-81ee-5534a166db96.PNG)

> But I don't understand why you use the cell content function and hide this column?

I perform the cell content function on 3 data keys out of the 6. I have written a function where I need the data of the rest of the 3 data keys for the condition to be true but I don't need to show their data in the table hence I want to hide those.
Based on the true condition it will colour the cell.

`var cal_curr = 0;
cal_curr = (rowData.newCurrAvg/rowData.full_load)*100;
var max_all_temp = 0;
max_all_temp = 35 + ((cal_curr*rowData.max_all_temp_full_load)/100) + 5;
if (value < max_all_temp){
    return {"background-color" : "#2196f3"};
} else if (((26*max_all_temp)/100)+max_all_temp < value || value > ((35*max_all_temp)/100)+max_all_temp) {
    return {"background-color" : "#f86111", "color" : "#000000"};
} else if (((16*max_all_temp)/100)+max_all_temp < value || value > ((25*max_all_temp)/100)+max_all_temp) {
    return {"background-color" : "#f4f104", "color" : "#000000"};
} else if (value > ((15*max_all_temp)/100)+max_all_temp) {
    return {"background-color" : "#2bbb07", "color" : "#000000"};
}`

I want to hide 'max_all_temp_full_load', 'newCurrAvg' and 'full_load'.

Is there any other way where I can access the above data keys to perform the cell content function on another data key?

**Comment by Backdraft007** [comment]
In version 3.3.3 is the option. I don't know, when it was implemented. You can clear the cache of your browser, maybe your browser has old cached JS-files.

Can you use the cell content function to return nothing. So you have an empty cell with your color.

Or an upgrade to latest version. :)
![advanced](https://user-images.githubusercontent.com/8741669/171130556-8b48301a-737e-4c71-b338-27434f92c590.PNG)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
