### ISSUE TITLE
UI menu names not right after update

### ISSUE THREAD

**Issue by IgorMartic** [thingsboard/thingsboard#6607]
**Component**

 * UI

**Description**
After upgrading form version 3.2.2 to 3.3. saw that the names of new features were not right. Any ideas?

**Environment**

 * OS:  Ubuntu 18.04.3 LTS
 * ThingsBoard: 3.4.4.1
![Capture](https://user-images.githubusercontent.com/104068652/170695653-a80fcc26-8a30-4860-9105-33a8da59bb00.PNG)

**Comment by mde2017** [comment]
Try deleting the Browser Cache, this should solve the issue.

**Comment by IgorMartic** [comment]
Thank you, it worked.
