### ISSUE TITLE
Why can't I access the data array inside self.ctx.defaultSubscription.data[0]

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6609]
**Component**

 * Generic

**Description**
Hi all,

I'm currently trying to develop a widget that requires some some lookup functionality. I'm trying to access the "data" array in a default subscription within onInit but it's empty when I try to. I can print to the terminal and see that the data is there;

```
var temp = self.ctx.defaultSubscription.data[0];
console.log(temp);
```

This produces the following output;

```
Object { datasource: {…}, dataKey: {…}, data: [] }
  data: Array(61) [ (2) […], (2) […], (2) […], … ]
  dataKey: Object { name: "f(x)", type: "function", label: "Random", … }
  datasource: Object { type: "function", name: "function", aliasName: "function", … }
```
When I try to access the data key I get an empty array.

`console.log(temp.data);`

```
Array []
  length: 0
  <prototype>: Array []
```

I log the object again after this and can see that the array is still there. For some reason when I try to access and print it, it seems to show up as an empty array

**Environment**

 * OS:  Windows
 * ThingsBoard: Cloud
 * Browser: Firefox

**Comment by maribaubna** [comment]
I was facing the same issue. The console showed me the array data. But when I tried to access it, the array was empty.

It seems like the array might not exist yet. So I added a timeout, and it worked. Here's the StackOverflow answer that helped me. https://stackoverflow.com/a/36250890

Try 
`setTimeout(function()
{
   console.log(temp.data);

}, 100);`

**Comment by OzyOzk** [comment]
> I was facing the same issue. The console showed me the array data. But when I tried to access it, the array was empty.
> 
> It seems like the array might not exist yet. So I added a timeout, and it worked. Here's the StackOverflow answer that helped me. https://stackoverflow.com/a/36250890
> 
> Try
> 
> ```
> setTimeout(function()
> {
>    console.log(temp.data);
> 
> }, 100);
> ```

Thanks. This worked but I had to also move the assignment inside setTimeout.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
