### ISSUE TITLE
[Question] About get Historical data value from TB CE version

### ISSUE THREAD

**Issue by zlfkdbstj** [thingsboard/thingsboard#6611]
Hello Everyone I'm currently working on my graduation project at University. My TB version is CE and I tried to upgrade PE but a University security issue occurred and the PE version was not allowed.
Our things board is installed in ubuntu with Cassandra and Postgresql. And set up timestamp, rule chain, and telemetry data.
I tried to use command for view data "select distinct entity_type, entity_id, key, partition from thingsboard.ts_kv_cf;"
And get csv command by "copy thingsboard.ts_kv_cf to 'database.csv';"
And I try to exact data from ts_kv_latest_cf but it won't show the data it only shows the device and key.
For example, i want get CSV data for a given device, key, and time period, can you write a query to extract a table of the form:

| Device | Key | Time | Value |

This is my last project for graduate University...
In case of CE can't get historical data can you guys please confirm is it possible or impossible?

Kind regards

**Environment**

 * OS:  name and version
 * ThingsBoard: CE v3.1.1-1
 * Browser: Cassandra v3.11.8, postsql v12.4, mosquito v1.4.15
![1](https://user-images.githubusercontent.com/74388118/170816640-2005b011-175c-4dbe-b373-717baadd5432.jpg)
![2](https://user-images.githubusercontent.com/74388118/170816644-3ed2af16-7b9c-4aad-a3c6-de378426439d.jpg)

**Comment by mde2017** [comment]
duplicate of  #6605
