### ISSUE TITLE
[Bug] SQL configuration variables with docker deployment

### ISSUE THREAD

**Issue by paolofrs** [thingsboard/thingsboard#6612]
**Describe the bug**
Not sure this is a bug, maybe I am doing somethings wrong. I wanted to reduce the numberof logs in the output and in the `thingsboard.log` file. I notice that the message printed the most are from SQL (TS, TS Latest, Attributes). 

I edit the variables `SQL_ATTRIBUTES_BATCH_STATS_PRINT_MS`, `SQL_TS_BATCH_STATS_PRINT_MS` and `SQL_TS_LATEST_BATCH_STATS_PRINT_MS` in my thingsboard.yml file (copied from [github, tag. 3.2.1](https://github.com/thingsboard/thingsboard/blob/v3.2.1/application/src/main/resources/thingsboard.yml)). 

To load it in the container I copied the whole [resource](https://github.com/thingsboard/thingsboard/blob/v3.2.1/application/src/main/resources) folder on my server into `.tbdevel-conf`, edited the ownership (recoursively) to `799:799` and add the following line in the docker-compose file:

~~~
/path/to/local/dir/.tbdevel-conf:/usr/share/thingsboard/conf
~~~

I log into the running container and I can see that the file gets loaded properly. If I edit the variables in the `thingsboard.yml` I can see them changes if I stop and bring up the container again. I set the variables above to `60000` but logs are still printed with default value (rate of `10000` ms ).

~~~
2022-05-29 10:20:34,529 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS Latest] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2022-05-29 10:20:44,529 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS Latest] queueSize [5] totalAdded [14] totalSaved [9] totalFailed [0]
~~~

I wonder if the variables' names are't aligned with the those used by the Java thingsboard app or if it is me not able to load the configuration file properly. 

**Your Server Environment**

* own setup on docker deployment (monolithic) with image thingsboard/tb-postgres:3.2.1
  * ThingsBoard Version 3.2.1
  * OS Name and Version Ubuntu 18.04 LTS

**Your Client Environment**

not relevant

**Your Device**
not relevant

**To Reproduce**

See description above

**Expected behavior**
Log message should be printed every 60 sec.

~~~
2022-05-29 10:20:34,529 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS Latest] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2022-05-29 10:21:34,529 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS Latest] queueSize [5] totalAdded [14] totalSaved [9] totalFailed [0]
~~~

**Comment by pon0marev** [comment]
You can export the parameters you want to change to: [tb-node.env](https://github.com/thingsboard/thingsboard/blob/master/docker/tb-node.env)
Then restart the docker.

**Comment by paolofrs** [comment]
Thank you very much for your hint.

I will try it. I use the monolithic docker version. I will try to edit the variables in the `docker-compose` file and see if they get loded. 

Anyway, this seems me a workaround... The app shall read those variable from the `yml` file. Am I wrong?

**Comment by pon0marev** [comment]
The yml file uses the default variables. 
To override the variables you need to export the values to the environment (e.g. container environment)

**Comment by paolofrs** [comment]
I do not get it. 

The variables defined in the yml takes the values they are assigned to. If you do not edit them, they use the default the files's shipped with. I edited some and they works ( the behaviour of the tb app in the container changes !).

The issue is with SQL variables. They are not taken from the yml. (apparently).

**Comment by pon0marev** [comment]
All variables with specified in [configuration](https://thingsboard.io/docs/user-guide/install/config/) can be overridden from the environment. 
For example: `stats_print_interval_ms: "${SQL_ATTRIBUTES_BATCH_STATS_PRINT_MS:10000}"`
if you do not have the SQL_ATTRIBUTES_BATCH_STATS_PRINT_MS variable in the environment then the yml file uses the default value of 10000

**Comment by paolofrs** [comment]
But what if I change the default in the yml to `stats_print_interval_ms: "${SQL_ATTRIBUTES_BATCH_STATS_PRINT_MS: 60000}"` ? I assume it should initialize to `60000` but it doesn't...

**Comment by pon0marev** [comment]
These values are applied when you start the service or container. So you should recreate the container already with this value. You must create a volume for the configuration (if it doesn't exist), go into the configuration and change the value, then restart the container. 
But this is not very good, because the default values should be overridden by variables with your values. This will make it easier to support and update later.
