### ISSUE TITLE
[Question] Get related name and label in RuleChain

### ISSUE THREAD

**Issue by MatzeSch** [thingsboard/thingsboard#6613]
**Component**

 * Rule Engine

**Description**

I want to fetch the name and label of an related asset in my rule chain.
Let's say we have a device with a relation to an asset. To generate a E-Mail i want to know in which related asset the device is.
Just like Related Attributes but for the generel asset informations.

**Environment**

 * ThingsBoard: 3.3.2 PE

**Comment by MatzeSch** [comment]
Thanks @mde2017,

I thought so.
Unfortunately the workaround is not possible for me, because I need the device as originator for later.
I would have to change the Originator, get the name and label and then switch back to the original originator.

**Comment by LukaszDuss** [comment]
Are there any changes regarding this topic?

**Comment by loicgillioz** [comment]
I also have the same need, would be nice to have this implemented. For now is there any way to achieve it, maybe using a custom widget and/or the API ?

**Comment by yohnnylim** [comment]
any updates to this question? I have the same need, it would be great if we can get the asset name of the device.

**Comment by mykhailokornieiev** [comment]
Hi @MatzeSch, @mde2017 , @LukaszDuss , @loicgillioz , @yohnnylim 
Currently there is Enrichment -> "Related Entity Data" rule node, that provides ability to get related entity data without usage of "change originator" rule node, etc. It's available from 3.6 version.
![image](https://github.com/thingsboard/thingsboard/assets/115699895/5315fe4b-16ec-4694-b8f1-f2361126551c)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/59815a5c-6d81-45a4-81df-520b4cb7ff95)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/911eb942-0664-49bd-b69b-2a14250be85f)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/9ad90aaf-458f-48f1-a64d-5ad663e9a789)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/99511080-7031-4184-8c93-39f38c3ce2b2)
In this case, I close the ticket as solved. Feel free to ask new questions, and I will re-open it.
