### ISSUE TITLE
[Bug] Multiple radial gauge show wrong value as home dashboard

### ISSUE THREAD

**Issue by mistadave** [thingsboard/thingsboard#6617]
**Describe the bug**
With multiple temperature radial gauge, on of the gauge always shows a wrong value on the dashboard init(Dashboard is set as Home Dashboard). After resizing (whole window or false gauge) or new values are uploaded, the gauge shows the correct value.

**Your Server Environment**

* own setup
  * kubernetes cloud infrastructure
  * ThingsBoard PE v.3.3.4.1PE
  * Kubernetes version 1.21

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10 and 11
* Browser: Edge, Chrome, Opera
* Version Latest

**Your Device**

* Connectivity
  * MQTT
* Raspberry PI with temperature and humidity sensor.

**To Reproduce**
Precondition: Create a Dashboard with multiple Gauge to show for my example the temperature and humidity. Also 2 Line Charts and single charts.

1. Set Dashboard as Home Dashboard of user
2. Open ThingsBoard Home which shows the dashboard with the 2 riadial gauge in it.
4. See one gauge with the wrong value.

**Expected behavior**
Both gauge should show from beginning the correct values. Not after a resize or refresh of the window.

**Screenshots**
The value is supposed to be 25.00 for the temperature radial gauge. Can be seen on the simple card next to it.
![image](https://user-images.githubusercontent.com/7965357/171342931-4d042ae2-0fd0-4417-9e30-bfdfd706f77c.png)

No calculations or anything special is done on both radial gauge.
![image](https://user-images.githubusercontent.com/7965357/171343516-cf4f3f1b-db7d-410a-8c49-d0704b27145a.png)

**Additional context**
After a refresh or multiple loads of the home it usually works fine. Just right after the login it doesn't work fine.

**Comment by Backdraft007** [comment]
Hello,
I cannot reproduce it. Can you create a new widget without any settings in the Advanced tab.

**Comment by mistadave** [comment]
Hello,
I added a new "Temperature Radial Gauge" to the dashboard an it has the same bug.
The Gauge at the bottom is a new one without any advanced settings. And has the same value as the upper one.
The orange card shows the actual value, which they get when new data arrives or the canvas is rendered.
![Radial-bug-in-dashboard](https://user-images.githubusercontent.com/7965357/173537795-ba080560-f31c-4c67-a089-f92bc8bbdfb4.gif)

**Comment by Backdraft007** [comment]
That is strange. Can you display the raw data of the temperature in a card or timeseries table?
Is the temperature telemetry or an attribute?

Is it right, that the value is sorrect after you maximaize the widget? What happen, when yo do nothing and the value is changed?

**Comment by mistadave** [comment]
The temperature is **telemetry** value and is shown also in the orange box.  Where it's correct. 

And the value is correct after maximizing which calls the resize function.
It's also correct when the value changes.

**Comment by Backdraft007** [comment]
Is it now ok?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
