### ISSUE TITLE
How to use trendz thingsboard custom widget

### ISSUE THREAD

**Issue by rochakgithub** [thingsboard/thingsboard#6618]
How to use trendz thingsboard custom widget. Can anyone explain to me with an example?

https://thingsboard.io/docs/trendz/rest-api/#usage-in-custom-thingsboard-widgets

**Comment by rochakgithub** [comment]
Yes, how I can use it in different types of widgets? What widget can build ?

**Comment by vparomskiy** [comment]
You can create any widget that you want.
Here is ThingsBoard widget development guide - it explains the generic logic of how widgets are created.
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
