### ISSUE TITLE
how to assign telemetry values in the vertical bar ?

### ISSUE THREAD

**Issue by chhavish123** [thingsboard/thingsboard#6619]
Hi everyone, I want to display my entityName in the title of a vertical bar. ${entityName} it's work for me but how I can access Latest telemetry values in the vertical bar. For example, can I access something else in the title, such as the entity from Dashboard State? Any ideas?

**Comment by chhavish123** [comment]
I created a dashboard which has two widgets: HTML Value  Card and Entities
table. Then on the table there will be an action which will be navigation
to another dashboard. Show the details of that particular entity. Now
the breadcrumb or vertical line has the default name of the dashboard and
the state dashboard name. That name can be any string, or this can be taken
from the entity description, and there is only entityName, entityLabel, and
additional information as per my understanding.
But now I want that navigation between the dashboard is done by the
telemetry value name in the breadcrumb that the alias has.
Is there any way to do ssoo. please suggest to me any solution for this and
if that would be possible or not to have a telemetry value name in the
breadcrumb that the alias has as the entity has.
please reply as soon as possible
thanks

**Comment by devaskim** [comment]
[Here](https://github.com/thingsboard/thingsboard/issues/6484) is how device data is encoded in dashboard state url.

**Comment by chhavish123** [comment]
But I want this in breadcrumb not in the url

**Comment by devaskim** [comment]
[Here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts#L212-L236) is how breadcrumb item is formed.
As I understand the code above, by combining this and the approach from the issue mentioned in my previous comment you can customize the breadcrumb item. But I didn't test this.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
