### ISSUE TITLE
Same x509 certificate for multiple devices

### ISSUE THREAD

**Issue by nucflash** [thingsboard/thingsboard#662]
I have followed the instructions and generated a self-signed certificate for ThingsBoard server and for the client, the devices. I have moved the server certificates inside ThingsBoard and the client certificate (the one and only) to two devices. I'm using ThingsBoard REST API to manage my devices:

* create each device
* assign each device to the same customer
* relate each device to an asset
* update the device credentials

The last step, updating the device credentials, gives me some trouble. I'm using the following command:

```
device_credentials_data = {
    "credentialsType": "X509_CERTIFICATE",
    "credentialsValue": "blah",
    "deviceId": {"id": "a device id", "entityType": "DEVICE"},
}
tbapi.post('/api/device/credentials', device_credentials_data)
```

For the first device it works fine. However, when I try the same call for the second device, which is identical to the first call but using the second's device deviceId,  I get this error:

```
{"status":400,
 "message":"Create of existent device credentials!",
 "errorCode":31,
 "timestamp":1521410670549}
```

When I go to ThingsBoard dashboard, I have both devices, I can delete the second device, but I cannot delete the first because:

```
result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements
CLOSE
```

**Comment by mp-loki** [comment]
When you are using X509_CERTIFICATE credentials type, The public key itself is used as a device identifier, so two devices cannot use the same key. SHA3 hash of the certificate is used as a key to store those credentials in the database. I assume that the error you get is reasonable, although I would agree that there is a bug in ThingsBoard that does not allow to delete the first device and it has to be fixed.

**Comment by nucflash** [comment]
Thanks @mp-loki. I have two follow up thoughts:

1. Certificates expire after some time. When I create a new certificate for my device, does it mean that I loose its historical data because internally, its device id changes?

More broadly, I find two procedural issues issues with the current approach:

1.1. Procedure of updating the private key in a device. If I self-signed the certificates, I'd need to run `client.keygen.sh` as many times as the number of devices and burn `mqttclient.nopass.pem` into each device. Plus, when the certificate expires, I'd have to upload the new certificate to each device (I do not know how to do this as the devices probably cannot get it from ThingsBoard) and reset the device credentials on ThingsBoard. The latter step is fine, but the former can be very tricky.

2. Too economically expensive to have one certificate per device. If the public key is used as a device identifier, it means that I need a certificate for each device. If I would buy these certificates from a certificate authority and I had a fleet of thousands of devices, it would mean I'd have to pay hundreds of thousands of euros. This is not going to fly. There is a type of certificate, called star-certificate and applies to a set of sub-domains, e.g., *.domain.com. With this you buy one but you cover many sub-domains. It's economically efficient.

**Comment by mp-loki** [comment]
Hi @nucflash ,
For - no, the device id does not change. The DeviceCredentials changes, which is a separate entity, so your historical data will not be lost. For the other items -
1. You can update device credentials (upload a new certificate) using GUI or API
2. @ashvayka Please respond

**Comment by ashvayka** [comment]
Hi @nucflash 
You can create self-signed certificates and do not need to sign them at authorities. The idea is for TB server to check the signature, public part of the certificate.

**Comment by nucflash** [comment]
@mp-loki Thanks, good to know.

@ashvayka Thanks, and sure, I can generate self-signed certs, but I think it can become quite tricky to manage hunders or thousands of certificates in devices that are remotely located. 

Probably having certs is not the best way to go for my use case. I'll try to figure out something else. Thanks again.
