### ISSUE TITLE
[Question] How to specify sortOrder from custom widget

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#6622]
**Component**

 * UI

**Description**
I try to specify a sortOrder into a pageLink to get my results sorted (in this case devices sorted by name).

**Environment**
 * OS:  name and version
 * ThingsBoard: 3.1 PE
 * Browser: Firefox

When developing custom widget you can request devices assigned to a certain customer using this call:
`self.ctx.deviceService.getCustomerDevices(customerId, pageLink).subscribe(....`

This works fine with default pageLink that you obtain like this:

`self.ctx.pageLink()`; 

or even like this 

`self.ctx.pageLink(200, 0, '', null);  `

where 200 is the max page size, 0 is the current page, '' is the search string and I guess last parameter is the sortOrder.

Now I don't know how to specify sortOrder. The closest I got was with this:
```
       var pl = self.ctx.pageLink(200, 0, '', null);
       pl['sortOrder'] = {};
       pl.sortOrder['direction'] = 'ASC';
       pl.sortOrder['key'] = {};
       pl.sortOrder.key['key'] = 'name';
       pl.sortOrder.key['type'] = 'ENTITY_FIELD';
```

which succeed to inject sortOrder in the request but not the sortProperty.

/devices?pageSize=200&page=0&sortProperty=undefined&sortOrder=ASC&type=

Logically resulting in a 500 server error with that error:

`org.hibernate.QueryException: could not resolve property: undefined of: org.thingsboard.server.dao.model.sql.DeviceEntity [SELECT d FROM org.thingsboard.server.dao.model.sql.DeviceEntity d WHERE d.tenantId = :tenantId AND d.customerId = :customerId AND LOWER(d.searchText) LIKE LOWER(CONCAT(:searchText, '%')) order by d.undefined asc]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: undefined of: org.thingsboard.server.dao.model.sql.DeviceEntity [SELECT d FROM org.thingsboard.server.dao.model.sql.DeviceEntity d WHERE d.tenantId = :tenantId AND d.customerId = :customerId AND LOWER(d.searchText) LIKE LOWER(CONCAT(:searchText, '%')) order by d.undefined asc]`

So what is the proper way of performing this request with sort order on a field?

**Comment by devaskim** [comment]
Try `self.ctx.pageLink(200, 0, '', {property: 'YOUR_KEY_NAME', direction: 'ASC'});`
