### ISSUE TITLE
MQTT Connection Reset when connect to thingsboard device

### ISSUE THREAD

**Issue by Eshya** [thingsboard/thingsboard#6623]
**Component**

 * Device Thingsboard

**Description**
I have 2 devices that connect to  thingsboard device as client mqtt, but when connecting to the thingsboard device via MQTT it always resets connection. Can the mqtt device thingsboard only be used by one MQTT client?

**Comment by devaskim** [comment]
Does your MQTT client use the same Thingsboard token for each device?

**Comment by Eshya** [comment]
@devaskim yeah, I have multiple clients connect MQTT to one device in thingsboard

**Comment by devaskim** [comment]
In that case you need to increase *ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE* server [configuration parameter](https://thingsboard.io/docs/user-guide/install/config/#actor-system-parameters).

**Comment by pon0marev** [comment]
Did the answer provided by devaskim help you solve your question?

**Comment by Eshya** [comment]
@pon0marev right now I am using MQTT integration and Data Converter to replace the MQTT device because I can't access Actor system parameters and don't know how to change it

**Comment by pon0marev** [comment]
If you are installing thingsboard as a service, you need to add the following line to the configuration file (`/usr/share/thingsboard/conf/thingsboard.conf`):
`export ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE=2`
 and restart the service
