### ISSUE TITLE
Change Ip Address of the PC with the server Things Board

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#6629]
hi, can i ask if I want to change the IP address of the PC that has things board server, what i need to check before change the IP address?
because I want to change the server with things board to the server room for better protection, any recommendation?
Currently using method install locally the things board in the window. Just scare in case if changing the IP address with cause the things board unable to use.

Things Board Version: 3.3.4
Installation: Window

**Comment by pon0marev** [comment]
You want to move the service to another server. This is possible. 
You need to make backup the database, then restore it to the server. And install the same version of thingsboard that you had. 
Also, if your devices were sending requests by ip address, you will need to change the endpoint. Or use the dns name.
