### ISSUE TITLE
[Bug]  Update button not visible, Non scrollable dashboad  for 14 - 17 inch screen

### ISSUE THREAD

**Issue by hetvishah08** [thingsboard/thingsboard#6630]
Hi,
I have created a dashboard with a few graph widgets and table widgets. On clicking on the time window and under history when the time period is selected, the update button goes down. I am unable to access the update button since there is no scrolling option. I am able to access it only when I click on full-screen mode.

**Your Server Environment**

* own setup(flowlinc.io)
  * ThingsBoard Version : 3.3.2

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Chrome

**To Reproduce**
1. Go to History in Timeseries Line Chart Widget
2. Click on Time Period
3. Scroll down to update
4. See an error

**Expected behavior**
There should be a scrolling bar to scroll down and update the changes selected.

**Screenshots**
Before Selecting the Time Period you can see half Update button and there is no scroll down option:

![update button  ](https://user-images.githubusercontent.com/34642195/171852019-33f66a7d-0e1f-4c68-9ceb-06aeb94f7405.jpeg)

After selecting Time period, the Update button is not visible and there is no scroll down option:

![update button not visible](https://user-images.githubusercontent.com/34642195/171852402-778c545c-86c8-43f8-8bf1-b2cd8bc713bf.jpeg)

**Comment by devaskim** [comment]
As workaround I suggest to scale down the browser page to something less than 100%

**Comment by hetvishah08** [comment]
@devaskim I understand, I use full screen to do that but this solution is okay for me but not for the client, I cannot give this to the client. I need a scrollable option for my clients.

**Comment by devaskim** [comment]
If your team are familiar with CSS, you could fix this in [timewindow-panel.component](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/components/time/timewindow-panel.component.scss) and re-build server from code.

**Comment by hetvishah08** [comment]
I'm using a licensed version of Thingsboard. Is there any other way?

**Comment by xalt7x** [comment]
This issue is fixed since v3.5.0, nowadays "timewindow" has a scrollbar.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
