### ISSUE TITLE
[Question] Display entity label when using entity alias

### ISSUE THREAD

**Issue by stevmei** [thingsboard/thingsboard#6631]
**Component**

 * UI

**Description**
Is there a possibility of displaying a device label instead of its name when using the entity alias inside dashboards.
I'm using an entity list as entity alias for displaying its data inside all widgets. The user is able to choose the device by changing the entity alias at the top of the dashboard. The issue is, that the name of the devices are (for example) EUIs and not human readable. It is possible to give all the devices nice labels (for example with sensor names, locations, and so on...) but they are not used in that drop down / filter. Any ideas of how to combine that entityName and entityLabel?

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.3.4.1PE
 * Browser: Firefox 100.0.2

Thank you very much!

**Comment by basor-dali** [comment]
Hi, you can do it using an attribute for maps at least. For example, create sensorLabel attribute (for ex. "Temperature Sensor 1"), and then add this variable in widget's data source. Then you will be able to reference that variable when displaying device's label. 

See my map as an example.
![image](https://user-images.githubusercontent.com/97993306/172724033-2b0a333b-dcf8-4a36-9443-6399e63a5736.png)

Hope that helps

**Comment by stevmei** [comment]
Thank you for your example.

Unfortunately this is not what I mean. I understand that displaying entities / device attributes is possible using widgets. But I want to use inside the entity aliases as shown here:

![single-entity-4-ce 1](https://user-images.githubusercontent.com/13609443/172794784-77a3c134-aea0-4033-87d3-ccc06898ac3f.png)
(Image taken from the [official docs](https://thingsboard.io/docs/user-guide/ui/aliases/)

Thank you!

**Comment by ssakharova** [comment]
Hello @stevmei,

As you described, displaying a device label instead of its name when using the entity alias inside dashboards is not possible.

By the Thingsboard design, device labels are not unique and may be duplicated, while device names are unique and act as identification.
