### ISSUE TITLE
[Question] how to send custom response code for rest api request in rule chain

### ISSUE THREAD

**Issue by longGr** [thingsboard/thingsboard#6636]
**Component**
 * Rule Engine

**Description**
I want to use the REST API as a connection method for a backend server. That server handles requests originated by users and forwards them to thingsboard. The requests payload is then stored in the "shared attributes" for a MQTT connected device. For example I want to set something like `turn_on` to true but only if that `turn_on` is not already true. If it is true, I want to respond with a custom error code (e.x. 501). How would I accomplish that in a rule-chain (or somehow else if possible)?

**Environment**
 * OS:  Debain
 * ThingsBoard: 3.3.4
 * Browser: Firefox

**Comment by devaskim** [comment]
I am not sure that it is possible as of 3.3.4.1
