### ISSUE TITLE
Showing data from the future using a configurable look-ahead interval

### ISSUE THREAD

**Issue by MarsWarrior** [thingsboard/thingsboard#664]
## Expected Behaviour

If sensor data exists in the future, say for predictions, that data is displayed on the available charts.
The look-ahead time interval can be configured.

## Current Behaviour

Data with a future timestamp can be ingested into TB, but is not shown on the dashboard until that future time becomes the current or past time.

## Possible Solution

Configurable look-ahead time interval (default 0, ie use current time) makes it possible to show data in te future.

## Steps to Reproduce (for bugs)

1. Data aggregation does not work anymore when there exists data in the future. Unless set to NONE, no data is showed on the graphs.

## Context

We want to show the weather forecast for the upcoming weeks.

## Your (Docker) Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04 LTS

* ThingsBoard `1.4` (e.g. CE 1.4 or PE 1.4):

* Database used `Postgres` (e.g. HSQLDB, Cassandra, Postgres):

* Docker version `17.12` (e.g. Docker 17.12 ):

* Are you using Docker Swarm or Kubernetes?
Docker Swarm

* Link to your project or a code example to reproduce issue:

## Diagnostic information

N/A

**Comment by alebbb** [comment]
Hi, did you managed to solve this issue?

**Comment by Ultrazombie** [comment]
Hello @MarsWarrior 
Is your problem still relevant on the latest ThingsBoard version?

**Comment by apachler** [comment]
How is the state of this for TB 3.7.0?
