### ISSUE TITLE
[Question] How to use 'isModule' feature in custom widget development

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6647]
**Component**
 * UI

**Description**
How to use 'isModule' feature in custom widget development?

**Environment**
 * ThingsBoard: 3.3.4.1

**Comment by technorabilia** [comment]
The "IsModule" feature can be used in [this](https://github.com/thingsboard/thingsboard-extensions) context.

**Comment by devaskim** [comment]
@technorabilia I read and read description from link above, then run the project but got `Cannot GET /` visiting http://localhost:5000/.
So my question is [thingsboard-extensions](https://github.com/thingsboard/thingsboard-extensions) project and `isModule` option exist to incorporate compiled Angular components in custom widgets, don't they? As I understand from README CE version is supported?

**Comment by devaskim** [comment]
@technorabilia As I mentioned before when I had run [thingsboard-extensions](https://github.com/thingsboard/thingsboard-extensions) project I got `Cannot GET /`. I expected to see some widget instead. So my question is how I can see result of my developing (not custom widget but Angular component) without importing it as module in custom widget editor?

**Comment by technorabilia** [comment]
This is what I did:
```
git clone https://github.com/thingsboard/thingsboard-extensions.git
cd thingsboard-extensions/widgets/
mvn clean install -P yarn-start
```
This will result in:
```
...
[INFO] Compilation complete. Watching for file changes...
[INFO] ==> 🌎  Listening on port 5000. Open up http://localhost:5000/ in your browser.
```

Now you should be able to access http://localhost:5000/static/widgets/thingsboard-extension-widgets.js in your browser and use it as a resource with "Is module" checked.

**Comment by devaskim** [comment]
Thanks @technorabilia I did the same but got mentioned error. I will try again with my component.

**Comment by tonyngninlabbhe1** [comment]
Can custom widget only be added to Thingsboard  instance deployed as a cluster?

**Comment by devaskim** [comment]
@tonyngninlabbhe1 I think you need to create new issue and provide more details because it's not clear how your question is related to the topic.
