### ISSUE TITLE
how we can remove OTA updates ,entity view from side menu bar which present at home page on thingsboard of version 3.3.4.1[Question] your title here

### ISSUE THREAD

**Issue by patilnikii** [thingsboard/thingsboard#6648]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by ssakharova** [comment]
Hello @patilnikii,

If you mean the side menu, menu items can be hidden from there using the Custom menu feature.

Here you can find more information regarding this feature - https://thingsboard.io/docs/pe/user-guide/custom-menu/
