### ISSUE TITLE
MQTT (mqtt.MqttTransportHandler) crashing if used ESP.deepSleep()

### ISSUE THREAD

**Issue by DIYGuy01** [thingsboard/thingsboard#665]
connected to #640

**Comment by mfalkvidd** [comment]
Does Mosquitto crash directly when the esp is shut down, after a while (some timeout?), or when the esp is powered back on again?

**Comment by DIYGuy01** [comment]
Crash occurs when ESP is fully working and communicates to the TB  server (in my case it runs on Pi3). I will try to check when it happens, during PubSubClient.connect() or PubSubClient.publish()
Very strange. 
Telemetry data under device shows "nan".

**Comment by mfalkvidd** [comment]
Maybe you need to wait for all outgoing packets to be sent before shutting down the esp?
Calling yield() seems to help for udp packets: https://www.tabsoverspaces.com/233359-udp-packets-not-sent-from-esp-8266-solved/

**Comment by DIYGuy01** [comment]
Board: ESP-01
I made simple test sketch which causes the exception in TB. If i replace at the end deepsleep with delay it works ok **except first run**:
```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>

#define TOKEN "testtoken" //device token for posting data to Thingsboard server

char thingsboardServer[] = "192.168.0.101";

// Wi-Fi Settings
const char* ssid = "xxx";
const char* password = "xxx";

WiFiClient wclient;

PubSubClient mqclient(wclient);

void setup()
{
  Serial.begin(115200); //Begin serial communication;
  Serial.println();
  delay(500);
  Serial.print("Connecting to WiFi network = ");
  Serial.println(ssid);
    WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }//while
  Serial.println();
  Serial.print("WiFi connected. ");
  Serial.printf("RSSI: %d dBm\n", WiFi.RSSI());
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  mqclient.setServer( thingsboardServer, 1883 );
   
} //of setup

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println ("WiFi lost. Reconnecting...");
    ESP.deepSleep (2000000); //reboot
    //WiFi.begin(ssid, password);
  }
  else {
       // Prepare a JSON payload string
    String payload = "{";
    payload += "\"esp01-sensor0\":";
    payload += "22.55";
    payload += "}";

//    // Send payload
    char attributes[100];
    payload.toCharArray( attributes, 100 );

    //init connect to Mosquitto server
    if (!mqclient.connected()) {
      Serial.print("Sending data to ThingsBoard server ...");
      // Attempt to connect (clientId, username, password)
      if ( mqclient.connect("esp01-test", TOKEN, NULL) ) {
         mqclient.publish( "v1/devices/me/telemetry", attributes );
                          
          Serial.println( attributes );
          Serial.println( "[DONE]" );
          mqclient.disconnect();
          Serial.printf("Pause until next reading ");
          Serial.println();
          wclient.stop();
        
      }
      else {
        Serial.print( "[FAILED] [ rc = " );
        Serial.print( mqclient.state() );
        Serial.println( " : retrying in 5 seconds]" );
        // Wait 5 seconds before retrying
        delay( 5000 );
      }
    } //of if

      
    
  } //of else if wifi is ok

  
    ESP.deepSleep(5000000);
//delay (5000);
  
} //end of main loop

```

Notice that connection appears in the log at the end of exception.

> 2018-03-20 21:41:32,792 [nioEventLoopGroup-5-4] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt10816] Unexpected Exception
> java.io.IOException: Connection reset by peer
>         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
>         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
>         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
>         at sun.nio.ch.IOUtil.read(IOUtil.java:192)
>         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
>         at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
>         at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
>         at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)
> 2018-03-20 21:41:32,822 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt10817] Processing connect **msg for client: esp01-test!**

**Comment by DIYGuy01** [comment]
added unsubscribe after publish but doesn't help

**Comment by DIYGuy01** [comment]
btw, this started to happen when I rebuilt old code. Another ESP with the same code and deepsleep working well but it was compiled ~3 weeks earlier. 
Arduino libs change/versions or etc?

**Comment by mfalkvidd** [comment]
_java.io.IOException: Connection reset by peer_ indicates an unclean shutdown of the TCP connection.

I think it would be good to run wclient.flush(); before calling wclient.stop(); Could you check if that helps?

What happens if you add something like this before deepSleep, to give the network traffic time to finish?
```
unsigned long starttime = millis();
while(millis() - starttime < 5000){
  yield();
}
```

**Comment by DIYGuy01** [comment]
flush() didn't help but some delay even 1000 before ESP.deepsleep() WORKING!

**Comment by mfalkvidd** [comment]
Nice. Strange that flush isn't sufficient though. Maybe you need to check WiFiClient::status() continuously until it returns CLOSED?

**Comment by DIYGuy01** [comment]
because we had exception with mqtt I think better to check mq status instead of wifi.
well, we know workaround :)
tried this before sleep but doesn't help

```
while (!mqclient.state() == -1 ){ 
           delay (500); //wait until connection is closed
          }
          wclient.stop();

```

**Comment by mfalkvidd** [comment]
I don't think state() will ever return -1. These are the valid return values: https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/libraries/ESP8266WiFi/src/include/wl_definitions.h#L72

**Comment by DIYGuy01** [comment]
those are of wifi and I used state of MQTT

-1 : MQTT_DISCONNECTED - the client is disconnected cleanly


------------------------
Andrius
Vilnius
tel: +370 698 07555
