### ISSUE TITLE
[Bug] Kafka rebalance causes JS script timeout

### ISSUE THREAD

**Issue by chenliangrui** [thingsboard/thingsboard#6657]
When one of the tb-js-executor node restart, kafka will rebalance the js_eval.requests topic.But the rebalance duration is longer than REMOTE_JS_MAX_REQUEST_TIMEOUT, so the normal JS script will enter blacklist. In my view tb-js-executor node restart should not causes data lost. And I tried other configuration, but none of them solved the problem perfectly.

**Comment by trikimiki** [comment]
Try to edit your Kafka topics so "js_eval.requests" will have the same number of partitions as the number of js-executors. This should both increase performance and speed up rebalancing.

**Comment by chenliangrui** [comment]
emmmm...Sorry, I don't think so,Kafka rebalance time depends on the node's timeout. Kafkajs's default sessionTimeout is 30s, so the time of rebalancing is close to 30 seconds(30s - heartbeat + rebalancing). And the code will enter the blacklist...

**Comment by xiddjp** [comment]
Hi, has this problem been resolved?

**Comment by trikimiki** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the new ticket if this problem still exists.
