### ISSUE TITLE
[Feature Request] toggle enable/disable ALL data in chart widgets

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#6659]
**Is your feature request related to a problem? Please describe.**
When serving lots of different devices in a single widget eg line chart. ( see below)

![image](https://user-images.githubusercontent.com/98737620/172587180-ea458501-9b59-47ef-a9f9-ecf36e1642e0.png)

In most of my use cases it is either useful to show all data or data from a select few devices. 

currently you hace the features:

- data is hidden by default
- hide / unhide datasource by clicking it in the legend

however sometimes I may want to see all the data to get a feeling for the trend of the whole data, and then look at one specific datasource that is somehow special. then I have to options: 

- click all other devices (sometimes up to 70) 
- enter edit mode, select source, enable 'data hidden by default', and then click only the one I want to look at.

both are a horrible nuisance.

**Describe the solution you'd like**

a rather simple toggle button in the legend for hide or unhide all data sources, would make this immensly easier.

**Describe alternatives you've considered**

there is also the possibility of an option in the data settings that when all data is shown clicking on an entity in the legend does not hide it, instead it hides everything else. However I think my other solution is better for generel use.

**Additional context**

mockup of new button: 

![image](https://user-images.githubusercontent.com/98737620/172588946-33160f5c-2ccd-48de-8d44-327ad51c1538.png)

![image](https://user-images.githubusercontent.com/98737620/172589677-e516c0a6-8629-4b24-9ae1-8cc67ed51845.png)

**Comment by ThomasPrioul** [comment]
Hi @medutySMST, I have had a similar request in the past and found a solution.
Please see this issue : https://github.com/thingsboard/thingsboard/issues/6561

**Comment by ThomasPrioul** [comment]
You can set the min and max value of a timeseries chart inside the variables properties that you add in it. In the advanced settings.
If your problems are solved, please close this issue, this repo has so much open issues...

**Comment by medutySMST** [comment]
Yes I will close this, thanks for providing the solution. 

@ThomasPrioul Do you know of a way to make 'zoomin' or setting the min and max level of Y axis possible via Dashboard UI without entering settings of the widget ? 

I am thinking of a button that enables or disables variable min/max versus a set level eg.
