### ISSUE TITLE
[Bug] Trip Animation Widget ...

### ISSUE THREAD

**Issue by alkortius** [thingsboard/thingsboard#6661]
**Component**

 * Generic

**Description**
Hi everyone, I am using "https://thingsboard.io/docs/user-guide/ui/trip-animation-widget/" but when execute node timeseries-map-bus.js $ACCESSTOKEN the program doesn't respond. I don't know why, because the accesstoken exist and the mqtt package and the program are in the same folder. Someone know what could be the reason of this fail ? Thanks.

**Environment**

 * OS:  Ubuntu 20.04.4 LTS
 * ThingsBoard: v3.3.4 PE
 * Browser: Mozilla 100.0.2

**Comment by alkortius** [comment]
![mqtt_issue](https://user-images.githubusercontent.com/2829969/173031427-bb271c79-4f37-4b94-806e-e2501ca388ca.png)
We use 8883 port using TLS but I don't know how to program this part. 
Thanks.

**Comment by alkortius** [comment]
![mqtt_connecting](https://user-images.githubusercontent.com/2829969/173032012-a10633d8-6b16-4b17-b604-7a5b6eed53a5.png)
We use 8883 port using TLS but I don't know how to program this part.
Thanks.

**Comment by Backdraft007** [comment]
What says the java script? How do you start it?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
