### ISSUE TITLE
[Bug] Rest API ota-package-controller  returns error 500

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/thingsboard#6662]
**Describe the bug**
I am trying to create a new OTA package through the Rest API, as part of our CD pipeline.

I can successfully create the package with a call to `/api/otaPackage`.  
Then I try to upload the actual binary with a call to `/api/otaPackage/{otaPackageId}{?checksum,checksumAlgorithm}`, but the server always responds with an internal error:

```
{"status":500,"message":null,"errorCode":2,"timestamp":"2022-06-08T12:07:03.722+00:00"}
```

I also tried performing this call through the Swagger UI, but I get the same error. 

**Server Environment**
Thingsboard CE v3.3.4.1 on premises.
CentOS 7

**Client Environment**
*N/A*

**Your Device**
*N/A*

**To Reproduce**
Using the Rest API:
1. POST call to `/api/otaPackage` to create a new OTA package.
2. Get the package ID from the above call.
3. POST call `/api/otaPackage/{otaPackageId}`, to upload the OTA file.
4. Server always returns error 500.

**Expected behavior**
I expected to have the OTA package updated, and have it containing the firmware file.

**Screenshots**
*N/A*

**Additional context**
I am not sure if this is related, but when I open an OTA package through my browser, I cannot edit any of its fields.  
I click the "edit" button (orange pencil), and the only field that is editable is the description.

**Comment by fjpanag** [comment]
This is the part of the script that performs the above operations:

```sh
DATA="{																\
		\"tenantId\": {												\
			\"id\": \"$TENANT_ID\",									\
			\"entityType\": \"TENANT\"								\
		},															\
		\"additionalInfo\": {},										\
		\"title\":\"$TITLE\",										\
		\"version\":\"$VERSION\",									\
		\"type\":\"FIRMWARE\",										\
		\"tag\":\"$TAG\",											\
		\"checksumAlgorithm\":\"MD5\"								\
	}"

PACKAGE_ID=$(curl -s -X POST --header "Content-Type: application/json" --header "Accept: application/json" --header "X-Authorization: Bearer $TOKEN" -d "$DATA" "https://$SERVER_URL/api/otaPackage" | jq '.id.id' | xargs)

curl -s -X POST --header "Content-Type: application/octet-stream" --header "Accept: application/json" --header "X-Authorization: Bearer $TOKEN" -d @firmware.bin "https://$SERVER_URL/api/otaPackage/$PACKAGE_ID?checksumAlgorithm=MD5"
```

**Comment by fjpanag** [comment]
Just tried again after upgrading to TB v3.4.0, and the problem persists.

The call `/api/otaPackage/{otaPackageId}` always responds with:

```
{"status":500,"message":null,"errorCode":2,"timestamp":"2022-07-25T13:16:48.361+00:00"}
```

**Comment by sinweisu** [comment]
same question

**Comment by SuminDenys** [comment]
HI @fjpanag,

I am glad to inform you that this issue was resolved in the current ThingsBoard version.

I am closing this issue, if you have any questions, please feel free to open a new one.
