### ISSUE TITLE
What is default database used in thingsboard?

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#667]
can anyone tell me what is the default Database used in thingsboard?
i already used thingsboard and created some node.
now i want to use postgres,
when i run thingsboard with postgresDB,data is empty.
,thingsboard only have sysadmin,i doesnt have tenant users
when i create a tenant user also, it doesnt have any device details

**Comment by ouertani** [comment]
By default embedded HSQLDB. If you prefer to use an SQL database, PostgreSQL is recommended.

**Comment by gopirathnamt** [comment]
thanks bro
