### ISSUE TITLE
[Question] How to trigger rule engine execution on update of server attribute by the user

### ISSUE THREAD

**Issue by georgemichalis** [thingsboard/thingsboard#6670]
**Component**

 * UI
 * Rule Engine

**Description**
Hello everyone. 

I have been looking for a while about how to do something without any success, so unfortunately i have to ask.
I have a series of server attributes and corresponding controls that can update them.  Depending the values same additional constants are calculated via rule chain, to be used in subsequent calculations on telemetry data (which are not particularly important for this questions).  These constants are also saved as server attributes so they can be displayed for reference. 

My question is that if there is any way to trigger a rule engine execution when a server attribute is updated for a device from the dashboard with the provided control widgets. 
Right now i am waiting for a telemetry msg for that calculation to be triggered, which is a bit asinine. 

To give an example. Lets say that i have a server attribute called `ss_area`, and another `ss_used_area` and i am calculating a `ss_used_area_percentage = (ss_used_area / ss_area) * 100` inside the rule engine.  I want to do this calculation at the time that the values are updated by the user. 

**Environment**

 * OS:  name and version
 * ThingsBoard: CE 3.3.4.1

**Comment by basor-dali** [comment]
When you update an attribute on dashboard, it triggers "attributes updated" event in root rule chain. 
See my example root rule chain below. Hope this helps
![image](https://user-images.githubusercontent.com/97993306/172722146-b5e1ce4d-be99-4fe4-8503-6f85adc941de.png)

**Comment by georgemichalis** [comment]
hi [basor-dali](https://github.com/basor-dali) 
Thank you. That was it actually. 

You know, i figured it would be something like that, so i was testing it using the debug flags on the rule chain but it wasn't showing any events.  
For future reference in case somebody else is googling that : What i was doing wrong, is that i didn't have that rule chain set on the profile of that device that the dashboard was referring too. So the messages were going on the default root chain and not on the one that i was testing.

**Comment by basor-dali** [comment]
You're welcome! I'm glad you figured out the issue.

Cheers!
