### ISSUE TITLE
[Question] Load image from profile device uploaded image to html widget

### ISSUE THREAD

**Issue by serifis84** [thingsboard/thingsboard#6673]
**Component**

 * UI

**Description**
Device profile can upload an image file. How is it possible to access that resource and display it on the html widget (or any other widget)? Will this feature (uploading an image) be available to an asset too?

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.3.4.1
 * Browser: Chrome

**Comment by ssakharova** [comment]
Hello @serifis84,

The latest versions of Thingsboard include a new feature - the Image Gallery. The Image Gallery is a centralized repository for storing and managing images. With this feature, you can easily upload, organize, and select images to customize the interface according to your needs.

Using the image gallery, you can upload an image to the asset profile, too. Furthermore, after you’ve added an image to the Image gallery, you can embed this image into HTML card widgets, in the HTML section in the widget editor, in cell content functions, in custom actions, etc.

For further information regarding the image gallery, please refer to our documentation - https://thingsboard.io/docs/pe/user-guide/image-gallery/

Best regards,
Sofiia
