### ISSUE TITLE
[Feature Request] Add environment variables to set up CORS settings

### ISSUE THREAD

**Issue by simao-silva** [thingsboard/thingsboard#6674]
**Is your feature request related to a problem? Please describe.**
Following the question #6625, setting up **allow-credentials** is not possible with an environment variable which is very useful in a Docker environment. Since this value can be *true*, it also very useful to support the other CORS settings.

**Describe the solution you'd like**
Create the environment variables to define the CORS settings.

**Describe alternatives you've considered**
There is no viable alternative for a Docker environment. 

**Additional context**
The variables can be seen [here](https://thingsboard.io/docs/user-guide/install/config/#spring-cors-configuration).

**Comment by bbrenne** [comment]
I really need this also.

**Comment by dealnat** [comment]
Hi, we have created a product ticket for your recent feature request. The ticket number is [PROD-1514].
Our team will review your request and consider implementing it to improve our product.
This reference number will help us track the progress of your request and provide you with updates along the way.
Please refer to our release notes to find out more about new features and bug fixes: [ThingsBoard release notes](https://thingsboard.io/docs/reference/releases/)
