### ISSUE TITLE
[Question] What is the purpose of the scheduleAlarmHarvesting function in TbDeviceProfileNode

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#6679]
Hello, 
What is the purpose of the scheduleAlarmHarvesting function in TbDeviceProfileNode.java?

I found that i have set the alarm duration in the device configuration. The alarm will still be triggered if the duration is not exceeded. It 

seems that this function is working. What is the purpose of this function?I'm confused.

Thanks.

**Comment by xiddjp** [comment]
Is this project still maintained? Why is there no one to discuss the problem?

**Comment by AlexDoanTB** [comment]
Hi @xiddjp, there is no problem with the method. 
It is used for complex alarm rules (rules with duration) to schedule regular self-tics to check if the configured *Duration* period has passed or not. If passed, the alarm will be created, and if not, the rule node will wait for another self-ping.
