### ISSUE TITLE
[Question] How to fix a Dashboard that hangs, street MAP fails to load. No Edit option?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#6681]
* UI
**Description**
The map widget today failed to load some 'cloud blue map' isn't loading.
But because the map widget is hanging the edit button also doesn't come active.
So I have no way to fix the dashboard....

**Environment**
 * OS:  Ubuntu LTS 20.04
 * ThingsBoard: 3.3.3
 * Browser: Edge and Firefox

**Comment by mde2017** [comment]
Hi @KenSense,

you could export the dashboard as JSON, edit the JSON config in order to fix the problem & upload it back to ThingsBoard Server afterwards.

**Comment by KenSense** [comment]
I did try that but when I tried to remove the map widget everything else did load anymore just blank.
Maybe it would be better if there is a timeout in the widget so it is skipped if it can't load in a reachable time.

**Comment by KenSense** [comment]
The problem turns out to be a new device that had an integer type longitude instead of double.
combined with cluster setting it hangs. (because there was a very large number in the longitude field since the decimal separator was ignored.

**Comment by dhaval2017** [comment]
You can use swagger to directly fetch and update the widget

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
