### ISSUE TITLE
[Question] Provide related entities names (from relations) in custom entities table widget ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6685]
Hi,

I currently have the following relations hierarchy in Thingsboard : 

A customer contains sites, a site contains equipments, and an equipment contains devices.

Currently I have made a Rule Chain which is triggered when the relations from a device are modified (added or deleted).
This Rule Chain inspects in which equipment the device is contained, in which site this equipment is contained, and in which customer this site is contained, and it saves the owner, site and equipment names in the device attributes.
But I have a problem : if someone edit an entity name (customer, site or equipment) after that the copy of the names in the device attributes is made, the device attributes are no longer up to date with the currents related entities names...

So I think that my logic of copy is wrong.
I would like to know if it is possible to develop a custom entities table widget which could do this : 

The entities table would list all the existing devices, and we would be able to see the related owner, site and equipment names in the columns of the entities table for each device. The names in the columns would be the current names of the entities.

Best regards,

Lucas

**Comment by devaskim** [comment]
How about to listen to _Entity updated_ event and then update your relations?

**Comment by lucasKapf** [comment]
Hi @devaskim, I'm not sure if I understand what you mean : If I change the name of  an entity, the relation from and to this entity keep the right name. But the names which have been previously copied in the device attribute is not changed, it's the "old" name.

**Comment by lucasKapf** [comment]
Ok I understand, thank you @devaskim. The thing is : the entity updated can be a customer, a site or an equipment, but currently my rule chain is triggered by a device. I don't know how to change all my related devices attributes if a customer, site or equipment name has changed : I believe that you can't get all related devices from one customer, site, or equipment depending on relations. You just get the first device found...

**Comment by devaskim** [comment]
Right, there is no such rule node but you can get the list of your entities by calling TB REST API in REST rule node.

**Comment by lucasKapf** [comment]
Oh I didn't think of that thank you very much ! Do you know if I can "loop" over the result of this Rule Node ? I would need to loop because if the entity which name has changed is a customer, I would need to loop on the result of the first API call to get all the sites of the customer, then do an API call to get all the related equipments of each site, and do the same thing to get all the devices of each equipment.

**Comment by devaskim** [comment]
[Here is how to loop](https://github.com/thingsboard/thingsboard/issues/6594)
By the way, in order to call TB API you need its API token, [here is how](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/tb_api_token) I store it in metadata. Feel free to use and comment

**Comment by dhaval2017** [comment]
@lucasKapf 
Instead of rule I think good to make custom widget

**Comment by lucasKapf** [comment]
Hi @dhaval2017, thank you for your answer. I have never made a custom widget, do you have an idea of how I could start ?

**Comment by dhaval2017** [comment]
I have done many custom widgets 😅

**Comment by devaskim** [comment]
@dhaval2017 Maybe you can share your experience how to solve [such case](https://github.com/thingsboard/thingsboard/issues/6747)? :)

**Comment by lucasKapf** [comment]
Finally I have done it with a Rule Chain and it works. Thank you very much @devaskim for your Rule chain, you allowed me to understand how to use functions from the Swagger UI in a Rule Chain, it unlocks me a lot of new possibilities for the future.
