### ISSUE TITLE
[Question] Best way to log, analyze and optimize slow dashboard timeseries telemetry queries

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#6696]
**Component**

 * UI

**Description**

I'm a little new to this so please let me know if there's some additional info I need to report. Thank you in advance for the help.

Some of our dashboards load very slowly, get stuck with endless loading spinners. Sometimes they timeout with websocket errors.

I believe this is caused by slow or inefficient queries to our postgresql database and some db tuning would help, but I'm having a little bit of trouble figuring out what steps to take.

I believe I need to do something like this:
1. Identify a dashboard setting that reproduces the problem at a high frequency, then log the associated db query/queries.
2. Manually run that query in postgresql using postgresql's ANALYZE function (maybe with some other third party tools like pgMustard to help with analysis)
3. After identifying inefficient components in the query plan, make appropriate optimizations in postgres config.

However Iim getting stuck and step 1, because I'm not sure how to identify what query TB is actually performing. The logs aren't displaying any associated query activity when I access the relevant dashboards.

Does anyone have any recommendations for identifying and analyzing the queries being run? Is there a log setting I need to turn on to be able to see them? Is there some better way to approach this? Am I completely off base in my thinking about the problem? 

**Environment**
 * OS:  Any (thingsboard and postgresql on a GCP Ubuntu VM)
 * ThingsBoard: 3.3.0
 * Browser: Any

**Comment by devaskim** [comment]
Maybe official troubleshooting guide [will help you](https://thingsboard.io/docs/user-guide/troubleshooting/?scenario=growing-latency).
Also you can get some information about load time in your browser. Open DevTools, see WS (websocket) sub-tab in Network tab.
