### ISSUE TITLE
How to use server attributes and timeseries data at the same time in a widget?

### ISSUE THREAD

**Issue by megla-cschroepfer** [thingsboard/thingsboard#6697]
I am currently implementing a custom map widget based on leaflet. In order to show my thingsboard devices at the correct coordinates on the map, I need to read the longitude and latitude from the server attributes of each device.
Additionally, I need to be able to get timeseries data from different points of time inside my widget based on a date which the user selected in the dashboard.

My problem is that it seems like I can either access the server attributes by setting my widget type to "Current values" or the timeseries data by setting the type to "Time series" but I cannot get both at the same time. When I set the widget type to "Current values", I can get the server attributes and the latest values just fine but I cannot get older timeseries data in my widget. When I set the widget type to "Time series", I can get the timeseries data I need but I cannot access the server attributes.

The only working alternative I found so far is to get the `attributeService` instance in my widget and then manually call `getEntityAttributes` in order to get the server properties in a Time series widget, but this seems like an ugly workaround and it would also require me to completely change my widget code for reading the attributes of each device.

Is there no better way to get Time series data and server attributes of devices at the same time in my widget?

**Comment by epalchenko** [comment]
Hello,
In the latest ThingsBoard versions, you can add telemetry and attributes to Timeseries table widget:
![2024-05-23_16-31](https://github.com/thingsboard/thingsboard/assets/136599093/ef2fd640-5040-4a6c-b8fb-b93d6dc0b3ee)
![2024-05-23_16-30](https://github.com/thingsboard/thingsboard/assets/136599093/278221b4-f54b-4444-b040-bad27521664d)
![2024-05-23_16-37](https://github.com/thingsboard/thingsboard/assets/136599093/4b18f838-934a-48c3-83e2-3066574c589f)
And also see the answer of another user with a similar problem: https://github.com/thingsboard/thingsboard/issues/1737
