### ISSUE TITLE
[Question] Timecharts and legend font size

### ISSUE THREAD

**Issue by nikilito** [thingsboard/thingsboard#6701]
Hello everyone!
I'm looking for a "simple" way to change the font size of the time chart legend. Is this possible?
There is no default option in the widget settings... so I probably have to create a new widget with some code changes.

![Immagine 2022-06-13 140310](https://user-images.githubusercontent.com/68916828/173349508-c5009955-bcf5-439c-922e-ece29ba5af66.png)

Can anyone help me or provide any suggestions?

Thanks.

**Comment by devaskim** [comment]
@nikilito Open dashboard settings, scroll add and open Advanced Settings. Then add to Dashboard CSS
```
.tb-legend-label {
    font-size: 3em;
}
```

**Comment by nikilito** [comment]
I wasted a day trying to find a trick like that and another trying to figure out how to create a widget from the beginning.
You saved my sanity, thanks!
Sorry, one question: where is this in the documentation? I think I've been looking for it for weeks without success.

**Comment by devaskim** [comment]
I think there is no documentation for Dashboard CSS. I as you spent and spend a lot of time in developing my custom widgets and only access to source files helps me to find the right way but unfortunately not so fast as I wish.
So feel free to ask maybe we can help to each other.

**Comment by nikilito** [comment]
Hi @devaskim, do you also know some "tricks" to increase the line width of the timeseries chart?

**Comment by devaskim** [comment]
Hi @nikilito could attach some screenshot and point there out that line's width do you need? Because advanced settings of chart widget already provides width option.

**Comment by nikilito** [comment]
Hi @devaskim, thanks for your answer. I did not find any advance setting for this...Anyway, I would like to increase the thickness of the timeseries chart data. 
For example, the thickness of blue and green line of this chart.

![173349508-c5009955-bcf5-439c-922e-ece29ba5af66](https://user-images.githubusercontent.com/68916828/192561127-0794c371-668a-428d-bd87-2c61388d7149.png)

Thank you very much.

**Comment by devaskim** [comment]
![line_thickness](https://user-images.githubusercontent.com/86909129/192565407-75770c08-cc17-48df-aa00-51d02f748d7c.jpg)

**Comment by nikilito** [comment]
Why you have that option? Probably I have an older version... ? Do you know how can I check that?

![image](https://user-images.githubusercontent.com/68916828/192567833-5fe14f83-43e8-4b3f-bc43-287553187167.png)

**Comment by devaskim** [comment]
I am using version 3.4.1 and as Docker image as well. If your data is in Docker volume, it is better to make a copy of that directory.
And you should upgrade sequentially: 3.3.4.1 - 3.4  - 3.4.1 but no 3.3.4.1 - 3.4

**Comment by nikilito** [comment]
Thank you very much for these tips! I will try to upgrade..

**Comment by nikilito** [comment]
It works, thanks!
For those with the same problem:
Upgrade tb with docker following this: [https://thingsboard.io/docs/user-guide/install/docker-windows/#Upgrading](url)
If there are some errors like "Failed to load configuration ui resources" in Rule chains just clear browser cache and it should work.
