### ISSUE TITLE
[Bug] Trendz 0.9.0 issues with Thingsboard 3.3.4.1PE.

### ISSUE THREAD

**Issue by HaydenBurrows** [thingsboard/thingsboard#6715]
**Describe the bug**
Thingsboard Trendz 0.9.0 docker image isn't working with Thingsboard 3.3.4.1PE.
I get the following error:

View report build was failed: Tb Version unknown TbVersion(pe=true, version=3.3.4)

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard 3.3.4.1PE
  * Thingsboard Trendz 1.9.0-SNAPSHOT
  * OS Name and Version: Ubuntu server 22.04LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 22.04
* Browser Firefox
* Version 101.01

**Screenshots**
![image](https://user-images.githubusercontent.com/69659611/173676444-4c7eb5fb-213c-4ea3-871f-be075a9944a2.png)
![image](https://user-images.githubusercontent.com/69659611/173677211-afa8bee3-582b-4997-8dbe-bae27b88c740.png)
![image](https://user-images.githubusercontent.com/69659611/173677412-ca096924-ef13-475e-a0b1-e83dd5ba78ba.png)

**Additional context**
I have had Trendz version 0.8.2 working with Thingsboard 3.4.4.1PE, but ran into the same issue as here: thingsboard/thingsboard#5982

I have used environment variables:
TB_API_VERSION_MANUAL=3.3.4
TB_API_VERSION_MANUAL_SET=true

**Comment by vparomskiy** [comment]
Workaround for this issue is the following - update environment variables
TB_API_VERSION_MANUAL=**3.3.3**
TB_API_VERSION_MANUAL_SET=true

**Comment by HaydenBurrows** [comment]
I have tried updating the environmental variables as above, but I still get the error:
![image](https://user-images.githubusercontent.com/69659611/173941589-4132ba24-41b0-45a5-b81d-a8f88285959a.png)

**Comment by vparomskiy** [comment]
It was my mistake. It should be like this:
TB_API_VERSION_MANUAL=**3.3.3x**

**Comment by HaydenBurrows** [comment]
Legend! Works perfectly now.
