### ISSUE TITLE
[Question] Request telemetry data by particular value

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#6717]
Hello... can I make request use API to get telemetry data, filtered by particular value?
like this pic
![image](https://user-images.githubusercontent.com/12267053/173728470-a2492db2-7447-4ae7-adf9-849d2841c4ff.png)

let say i want to grab all telemetry data of that id `bf07763e` inside green area, 
is it possible to do something like `/api/..../timeseries?my_id=bf07763e` ? or other way to get that result? 

in dashboard we have filter for alias 
![image](https://user-images.githubusercontent.com/12267053/173731208-7fbfeeee-ff97-47e7-88ab-dadb1261e4ff.png)
but this is value for filtering fixed value, can we change it dynamicly using angular code from a custom widget?

**Comment by ssakharova** [comment]
Hello @evanderbird,

Due to the nature of history data, you won't be able to apply the dashboard filtering feature the way you want.
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
