### ISSUE TITLE
[Feature Request] UI: Persist user specific pagination and sorting options for tables

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6718]
**Is your feature request related to a problem? Please describe.**
Almost all sections of TB menu use tables where TB shows devices, assets and etc. There are sorting and pagination capabilities. 

**Describe the solution you'd like**
It would be convenient to persist user choice if I for example increase *items for page* from default 10 to 30 or sort items by label.

**Describe alternatives you've considered**
It doesn't exist.

**Additional context**
TB: 3.3.4.1

**Comment by Backdraft007** [comment]
I think it is on thne roadmap.
https://thingsboard.io/docs/reference/roadmap/

**Comment by devaskim** [comment]
Wait while I will implement it by myself...

**Comment by jamcinnes2** [comment]
This doesnt work for me on thingsboard 4.2.0 PE
My "Items per page" always gets reset to 10.
