### ISSUE TITLE
How to plot non-time series data in TB? 

### ISSUE THREAD

**Issue by kp372** [thingsboard/thingsboard#672]
I want to plot X vs Y plot on thingsboard dashboard. Also how do I send data from gateway to TB database? Any idea? Thanks.

**Comment by mbari** [comment]
these questions are covered in the documentation
connecting devices to thingsboard https://thingsboard.io/docs/user-guide/ui/devices/
and graphs are already explained in the videos https://thingsboard.io/docs/iot-video-tutorials/

**Comment by kp372** [comment]
Maybe I didn't explain it well. Let me try it again.
I want to plot non-time series data which has x and y values(aka X vs Y). These values are not in relation to time and don't require to be displayed in real time. I am looking for a way to load these 'X' and 'Y' datasets in postgre and later call it over the dashboard for display. 
Btw the links you posted are for either for time series or server/device attributes data.
Thank You.

**Comment by vparomskiy** [comment]
1. It would be easier if you provide some simplified reallife example.
2. Does X to Y relation change for single device?
3. Am I right that you want to make query like this - 'select Y from table where X = 12 and deviceId = 123;

**Comment by kp372** [comment]
1. The best scenario for an XY plot would be a frequency response of a time-domain signal. On this plot X-ais would be Frequency and Y-axis will be amplitude. This plot will be updated in an hour or so.

2. I don't what are you asking here. But xlim remains constant but ylim changes depending on signal amplitude.

3. No, I am trying to select last 100 Y-values from table and plot it against 100 X-values(X-values are constant). 


X | Y1 | Y2 | Y3 | … |  
-- | -- | -- | -- | -- | --
1 | 0 | 0 | 0 | … |  
2 | 5 | 8 | 0 | … |  
3 | 10 | 15 | 0 | … |  
4 | 5 | 7 | 0 | … |  
5 | 0 | 0 | 0 | … |  
6 | 0 | 0 | 2 | … |  
7 | 0 | 0 | 8 | … |  
8 | 0 | 0 | 4 | … |  
9 | 0 | 0 | 0 | … |  
10 | 0 | 0 | 0 | … |  
… | … | … | … | … |  
  |   |   |   |   |  
  |   |   |   |   |  

Every Y column is a single reading from the sensor after every hour. X remains constant for all Ys.
And the graphs have to be plotted as X vs latest column of Y.

Hope it helps.
Any suggestions are very much appreciated.

**Comment by vparomskiy** [comment]
I think you can map it on timeseries model:
Xn  is a collection of attributes. For your case it is : x1, x2, ..., x100
Yn is a timeseries data for attribute Xn
You will add widget 'Cards.latestTelemetry' and configure it to show the latest telemetry for Xn attributes of the device.

**Comment by alexsmartens** [comment]
Hey @kp372,
have you built the plot that you wanted?

I've spent bunch of time trying to build custom charts in thingsboard and ended up using [d3](https://d3js.org/). Alternatively, you can use a default TB library [flot](https://github.com/flot/flot).
You can check out more info on this in #1511 and #1531

Regarding the data, you can subscribe to latest data. Alternatively, when you get your timeseries data, you could reshape it and use it in whatever way you want

**Comment by adambforbes** [comment]
I'm also interested in whether anyone has successfully done this. I am looking to plot threshold/alarm level on a timeseries graph along with a separate timeseries with actual reading values. 
The threshold level(s) should not have a time value or key associated with it, it would display just as a line on the graph like the attached picture. 

![image](https://user-images.githubusercontent.com/10189215/58842249-6c949e00-86c1-11e9-9272-3254f6cb8def.png)

**Comment by alexsmartens** [comment]
Hi @adambforbes,
I've built a few custom widgets using mixed timeseries/latest/attribute data.
Some lessons learned are #1510, #1511, #1531, #1641,  #1737, #1743. 
Let me know if you have any specific question

**Comment by D-Hipple** [comment]
@alexsmartens I am trying todo what @adambforbes is showing. I am very new to Thingsboard widget development. Any suggestion on where to start. I have looked at your suggestion, but I am lost.

**Comment by Yuva86** [comment]
@vparomskiy, Hi, How do I set 'threshold' value in the x or y axis of the time series plot of dashboard chart widget. ?

**Comment by gglemke** [comment]
> I'm also interested in whether anyone has successfully done this. I am looking to plot threshold/alarm level on a timeseries graph along with a separate timeseries with actual reading values.
> The threshold level(s) should not have a time value or key associated with it, it would display just as a line on the graph like the attached picture.
> 
> ![image](https://user-images.githubusercontent.com/10189215/58842249-6c949e00-86c1-11e9-9272-3254f6cb8def.png)

@adambforbes I'm looking to do exactly the same! Did you manage to crack this?

**Comment by GeirFrimann** [comment]
I made this work with the rule chain by first add a originator attributes node to add the attributes to the metadata.
Then using a script node to add the attributes to the payload e.g.
msg.Radar_Threshold = Number(metadata.shared_Radar_Threshold);

**Comment by jodihonan** [comment]
> I made this work with the rule chain by first add a originator attributes node to add the attributes to the metadata.
> Then using a script node to add the attributes to the payload e.g.
> msg.Radar_Threshold = Number(metadata.shared_Radar_Threshold);

Hi @GeirFrimann , I am in the process of implementing the attributes in a timeseries chart. We have the Rule Chain created, can I please ask how you setup the Timeseries Chart Widget to display the attributes?
