### ISSUE TITLE
[Question] Disable certificate validation when using REST API Call Node in rule chain

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#6722]
**Component**

 * Rule Engine

**Description**
I want to disable certificate validation when calling one of my server from a _REST API Call Node_ in the rule engine. It is using self signed certificate. The call ends up with this failure:
`unable to find valid certification path to requested target`

How can I disable certificate verification?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.2.0 PE
 * Browser: Firefox 99

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
