### ISSUE TITLE
[Question] Failed to build source code. Maven

### ISSUE THREAD

**Issue by SebPieniazek** [thingsboard/thingsboard#6723]
**Component**

 * Installation

**Description**
Maven failed to build source code. 32/46 - Thingboards Server UI

**Environment**

 * OS:  Win 10
 * ThingsBoard: community
 * Browser: Opera

[INFO] Reactor Summary for Thingsboard 3.3.4-SNAPSHOT:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [ 17.613 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  3.647 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.826 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 10.418 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  1.853 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.963 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  1.962 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.759 s]
[INFO] Thingsboard Server Common Cluster API .............. SUCCESS [ 11.118 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  6.023 s]
[INFO] Thingsboard Server Common Cache .................... SUCCESS [  1.849 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.255 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.295 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  3.451 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.660 s]
[INFO] Thingsboard CoAP server ............................ SUCCESS [  1.607 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  3.457 s]
[INFO] Thingsboard LwM2M Transport Common ................. SUCCESS [  4.374 s]
[INFO] Thingsboard SNMP Transport Common .................. SUCCESS [  3.156 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  2.083 s]
[INFO] Thingsboard Server Remote Edge wrapper ............. SUCCESS [  6.372 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.186 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  2.873 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 12.592 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  7.660 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.070 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 24.939 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 23.298 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 22.806 s]
[INFO] Thingsboard LwM2m Transport Service ................ SUCCESS [ 23.591 s]
[INFO] Thingsboard SNMP Transport Service ................. SUCCESS [ 22.144 s]
[INFO] ThingsBoard Server UI .............................. FAILURE [ 22.888 s]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:16 min
[INFO] Finished at: 2022-06-15T12:43:59+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:yarn (yarn install) on project ui-ngx: Failed to run task: 'yarn install --network-timeout 1000000' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

MAVEN:
mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\apache-maven-3.8.6
Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18.0.1.1
Default locale: pl_PL, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

NODE:
node --version
v18.3.0

YARN:
yarn --version
1.22.15

I tried to modify .pom files and change yarn/lobock etc. to newest ones. Im also changed frontend-maven-plugin to 1.12.1 from 1.12.0.

Any tips ?

**Comment by SebPieniazek** [comment]
delete this file @geoman-io+leaflet-geoman-free+2.11.4 helps. Hope it's wont affect in the future :D

**Comment by nferry56** [comment]
Try to resume your compilation with:
mvn install -rf :ui-ngx -DskipTests

It solves the problem for me

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
