### ISSUE TITLE
[Question] Error with the Example

### ISSUE THREAD

**Issue by iyhabz** [thingsboard/thingsboard#6724]
**Component**
 * API

**Description**
Hello,

i wanna make some test with API of TB and im facing a problem with the examples from the documentation.
im trying to deploy this code
```import logging
# Importing models and REST client class from Community Edition version
from tb_rest_client.rest_client_ce import *
# Importing the API exception
from tb_rest_client.rest import ApiException


logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

# ThingsBoard REST API URL
url = "http://localhost:8080"
# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"


# Creating the REST client object with context manager to get auto token refresh
with RestClientCE(base_url=url) as rest_client:
    try:
        user = rest_client.get_user()
        devices = rest_client.get_customer_device_infos(customer_id=CustomerId('CUSTOMER', user.id), page_size=str(10),
                                                        page=str(0))
        logging.info("Devices: \n%r", devices)
    except ApiException as e:
        logging.exception(e)
```

from the example but each time i get the error "return self.auth_controller.get_user_using_get(), AttributeError: 'RestClientCE' object has no attribute 'auth_controller'" and i could not find a solution for it. 

has any one faced such a thing? and thanks in advance for the help

Best regards 

Iyhab

**Environment**

 * OS:  Win 10
 * ThingsBoard: CE

**Comment by ashaforost** [comment]
Hi @iyhabz ,

It seems you've skipped the login command. Try rest_client.login(username=username, password=password), and then run the .get_user() method.

**Comment by iyhabz** [comment]
Hi @ashaforost,

thanks for the answer now it's working
