### ISSUE TITLE
How to add or subtract two different meter readings 

### ISSUE THREAD

**Issue by rochakgithub** [thingsboard/thingsboard#6727]
How to add or subtract readings from two different meters for calculation. As If the data point comes at the same time then it is easy to do so, but if the data point gets late for a few seconds then it misses the point.

**Comment by devaskim** [comment]
[Look at this tutorial](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/function-based-on-telemetry-from-two-devices/) maybe it will help you.

**Comment by rochakgithub** [comment]
@devaskim I have implemented this in my workflow but still, I'm facing this issue because of delay in meter data telemetry is the problem.

**Comment by cowherdboy** [comment]
@rochakgithub I used [this example](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/telemetry-delta-validation/) to calculate using data arriving at different times. I used LAST in the originator telemetry. You need to also make sure the data polling period from both your meters is within the specified interval.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
