### ISSUE TITLE
what is the api for the telementry get data ??

### ISSUE THREAD

**Issue by amitghodke90** [thingsboard/thingsboard#673]
I could found the post telementry data api in swagger documents. as below.
{{url}}/api/v1/9Vf9tUFtSdMKpvKbm6dH/telemetry
However i there is not get api for telementry data , after search in code i could found some api's but  unable to get data from that apis it giving me error 
    "status": 401,
    "message": "Authentication failed",
    "errorCode": 10,
    "timestamp": 1521711162004
i am using token after user login in authorization. 
Could any body help me out for api.??
![screenshot from 2018-03-22 15-07-40](https://user-images.githubusercontent.com/25997114/37762620-d91ad3f2-2de2-11e8-93ff-27dd02cdf9a6.png)

**Comment by Tangerino** [comment]
The documentation is not accurate.

You must use
<pre>
Authorization: type token
</pre>

Example
<pre>
Authorization : Bearer cn389ncoiwuencr
</pre>

I hope it helps

**Comment by amitghodke90** [comment]
@Tangerino thanks for reply 
i am already using Authorization : Bearer {{Token}}, but unable to get reply.
also i want to confirm is this is the api for get telementry data from devices.

**Comment by vparomskiy** [comment]
https://thingsboard.io/docs/user-guide/telemetry/

You use wrong header name because Authorization is not the same as 'X-Authorization'
You need to use 'X-Authorization' header name

**Comment by amitghodke90** [comment]
Yes you are right..
After using X-Authorization its giving error
Bad request that's why I didn't used.

**Comment by vparomskiy** [comment]
Could you please post full response and thingsboard logs for this request.

**Comment by amitghodke90** [comment]
Ok.. wait ...
Thanks

On 27-Mar-2018 17:10, "vparomskiy" <notifications@github.com> wrote:

Could you please post full response and thingsboard logs for this request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thingsboard/thingsboard/issues/673#issuecomment-376493750>,
or mute the thread
