### ISSUE TITLE
Custom Validator  on FormArray-level prevents submit in custom action?

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#6738]
I've managed to include a custom validator into my form within a custom-action with html-template.
For this, I've simply defined a class and created an object from it:

```
    class customValidator {
        constructor(){
            this.isModelValid=true;
        }
        validate(c){        
            let vals = c.value.map(item=>item.field2);
            let sum = vals.reduce((previousValue, currentValue) => previousValue + currentValue,0);
            return sum != 100 ? {'adduperror':true}: {'adduperror':false};
        }
        
    }
    vm.addupValidator= new customValidator();
```

This validator was added to the fb.array-method of the instance.

```
     vm.addEntityFormGroup = vm.fb.group({
     entityName: [''],
     entityType: ['DEVICE'],
     entityLabel: [null],

     // similar to how relations-list is constructed
     myarr: vm.fb.array([     vm.fb.group({
        field1: [null, [vm.validators.required]],
        field2 [null, [vm.validators.required,
                      vm.validators.pattern(/^[0-9][0-9]?$|^100$/),
                      ]]
     })],[vm.addupValidator])
     
    });
```
Validation does indeed work as expected. However, the validator somehow doesn't allow me to submit the form (greyed out submit button)

What am I missing?
Is there another method I need to add to my validator class?

**Comment by devaskim** [comment]
Validator should return not an object but `null` in case of no error.

**Comment by eeitnn** [comment]
@devaskim : that fixed it. Thank you

**Comment by clemjrt** [comment]
Can you please provide the HTML of your custom widget ?
I am facing some issues while using FormArray in a FormControl. 
Ty by advance.
