### ISSUE TITLE
Error 401 when I upload data from API

### ISSUE THREAD

**Issue by chiavariniluca** [thingsboard/thingsboard#6739]
Hi,

I am using ThingsBoard with Trial subscription and I am trying to upload data from Post API; why the response of API is always 401?
My API is:
curl -v -X POST --data "{"temperature":42,"humidity":73}" http://demo.thingsboard.io/api/v1/O2ogacIIaAzU9Nno7ijm/telemetry --header "Content-Type:application/json"

The response is: 
```
 Mark bundle as not supporting multiuse
< HTTP/1.1 401
< content-length: 0
```

Where is the mistake?

**Comment by devaskim** [comment]
401 Unauthorized - Invalid $ACCESS_TOKEN.

**Comment by chiavariniluca** [comment]
> 401 Unauthorized - Invalid $ACCESS_TOKEN.

Yes, but I take the right access token.
![image](https://user-images.githubusercontent.com/102251679/174308933-dd854504-f060-4822-acff-d2cd49732fe7.png)
This is my credential's device.

**Comment by devaskim** [comment]
Maybe... But try to https instead of http

**Comment by chiavariniluca** [comment]
> Maybe... But try https instead of http

Same result with http or https or without both (only demo.thingsboard.io/api/v1/O2ogacIIaAzU9Nno7ijm/telemetry, as I saw in this youtube video: https://youtu.be/I2lEim_WrJ0).

**Comment by devaskim** [comment]
[Here](https://thingsboard.io/docs/api/) are supported protocols.

**Comment by chiavariniluca** [comment]
With local installation all goes well! Only in cloud not works :( 
I think that the error comes from having a test account. I have trial subscription (as ThingsBoard Cloud Maker). What do you think about it? Is it possible?

**Comment by devaskim** [comment]
I have not encountered such problems. Try to send data through MQTT protocol, for example, using `mosquitto_pub`

**Comment by chiavariniluca** [comment]
> I have not encountered such problems. Try to send data through MQTT (just for test) using, for example, `mosquitto_pub`

For solve my problem, I only changed the host service (from https://demo.thingsboard.io to thingsboard.cloud). Thank you for the help!
