### ISSUE TITLE
[Bug] A customer user can reclaim a device that not own

### ISSUE THREAD

**Issue by dev-bobsong** [thingsboard/thingsboard#6742]
**Describe the bug**
A customer user can reclaim a device that not own.

**Your Server Environment**

* own setup
  * docker
  * ThingsBoard 3.3PE
  * Ubuntu 

**Your Client Environment**

**Desktop**

* OS: Linux
* Browser：chrome

**To Reproduce**
1. Call API [DELETE /api/customer/device/{deviceName}/claim]

**Expected behavior**
A customer user reclaim a device that not own should be permission deny.

**Comment by ssakharova** [comment]
Hello @dev-bobsong,

Thank you for highlighting the problem; I’ve reproduced a bug with the device reclaiming when users of different customers can send a delete claiming request and decided to add this request to our backlog (PROD-1287) for our developers to correct this flaw.

There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

Regards,
