### ISSUE TITLE
[Question] Dynamically subscribe to a device latest values

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#6744]
**Component**

 * UI - Widget

**Description**
From a widget, how can you subscribe to a selected device (the device is selected from a list) for specific properties (attributes or timeseries)? Is that even possible?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.2.1 PE
 * Browser: Firefox 99

**Comment by Nonta-w** [comment]
I may be able to help.

I also work on custom widget. I use Entity table widget and set action on each row to go to different dashboard state on click. On the new dashboard state, I have a time-series and control widget for a specific device waiting.

**Comment by devaskim** [comment]
@bbrenne widget context has `subscriptionApi` what provides [3 methods](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L65-L70) `createSubscription() , createSubscriptionFromInfo() and removeSubscription()`. [Here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/lib/rpc/switch.component.ts#L339-L370) is code how *Switch* widget subscribes for its value, it uses `createSubscriptionFromInfo(...)`

**Comment by bbrenne** [comment]
It seems to be exactly what I'm looking for. Thanks @devaskim !
