### ISSUE TITLE
[Bug]  HTTP POST telemetry with empty json array times out

### ISSUE THREAD

**Issue by brownr16** [thingsboard/thingsboard#6746]
**Describe the bug**
ThingsBoard server does not handle well HTTP post telemetry when request body is an empty json array. Request times out after 50 seconds.

**Your Server Environment**
* cloud.thingsboard.io

* Connectivity
  * HTTP
 
* Device vendor and model
 * Postman

**To Reproduce**
1. Send a POST request to thingsboard.cloud/api/v1/<DEVICE_TOKEN>/telemetry, with body as empty json array -> []
2. Observe that request will never return a response (times out after 50 s)
3. Change body to an empty object -> {} or an array with an empty object -> [{}]
4. Observe that request will return a response

This causes a problem for some IoT gateways, e.g. the Minew G1, which send regular telemetry messages every n seconds / minutes etc., which will be an empty array if no sensor messages arrived at the gateway.

**Expected behavior**
An HTTP response should be returned by ThingsBoard server

**Screenshots**
Attached. Note that I now have rotated the device token shown in the screenshot, for security reasons, so any requests using the token shown will return 401 Unauthorised regardless of request body.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/37665987/174325195-d1dc5812-9eec-4aad-8c1a-b97d870e4cab.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/37665987/174325267-ac6a3bf8-bc8a-4f2f-9ca7-b9ca22333b42.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/37665987/174325377-22ca71f2-5d52-4e78-8a9e-4563f909b51d.png">

**Comment by den1jkee** [comment]
Greetings,
Thank you for your feedback. We are always improving our project and have already fixed this bug in the latest versions of ThingsBoard.

Best regards,
ThingsBoard Team.

**Comment by souvikrnd** [comment]
hello . i want to connect exotel and thingsboard . when i try to sent post request then show me mpty body message . but i also sent correct details in msg:data
