### ISSUE TITLE
[Bug] `repo.thingsboard.io` TLS cert expired

### ISSUE THREAD

**Issue by joe-pulse** [thingsboard/thingsboard#6752]
**Describe the bug**

The TLS cert for `repo.thingsboard.io` expired on 17th June 2022.

Just a heads-up, the cert for your maven repo expired on Friday. 

**Environments**
Any

**To Reproduce**
1. Go to `repo.thingsboard.io` in browser
2. You will observe the cert expired on Friday 17th June 2022

**Comment by Ultrazombie** [comment]
@joe-pulse 
Thank you for notifying us, fixed.

**Comment by joe-pulse** [comment]
@Ultrazombie You're welcome, cheers!
