### ISSUE TITLE
High frequency sensor

### ISSUE THREAD

**Issue by yohnniebabe** [thingsboard/thingsboard#6754]
**Component**
 * Generic

**Description**
How can we display data for high frequency sensors? I have a need to use sensors that log 2000 data per second, is there a way we can display data in 0.1 milliseconds?

**Environment**
 * OS:  Docker on windows
 * ThingsBoard: 3.3.3
 * Browser: edge or chrome

**Comment by KenSense** [comment]
Timestamp resolution is 1ms now.
You could send it as an array on 1 timestamp but then you can't view it in a graph with the current widgets....
So I think no is your answer now.

Request for micro second resolution:
https://github.com/thingsboard/thingsboard/issues/6101

**Comment by Ultrazombie** [comment]
I'll close this ticket as a duplicate open feature request. #6101
