### ISSUE TITLE
which protobuf plugin should i used?

### ISSUE THREAD

**Issue by onoeono** [thingsboard/thingsboard#6755]
i'm using idea 2021.3.3,i have already compile thingsboard,but there is two error in org/thingsboard/server/service/apiusage/TbApiUsageStateService.java and org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java.
the error said Cannot resolve symbol 'TransportProtos' on import org.thingsboard.server.gen.transport.TransportProtos.ToUsageStatsServiceMsg; and
import org.thingsboard.server.gen.transport.TransportProtos.UsageStatsKVProto;
i found that protobuf has bundled in idea 2021.1x and above. i found there is many protobuf plugins in idea plugin market. so which protobuf plugin should i use to resolve that error.

**Comment by JcBernack** [comment]
First you should make sure that the whole thing builds with maven, i.e. `mvn clean package -DskipTests` in the root folder. This will also compile the protobuf schemas and generate corresponding java sources.

Afterwards you should be able to fix the missing symbols in IDEA by properly marking the generated sources directories.
For example, there is `common/cluster-api/target/generated-sources/protobuf/java`, right click -> mark directory as -> generated sources root. There might be more of these that you need to mark.
