### ISSUE TITLE
thingsboard failed

### ISSUE THREAD

**Issue by Rujanth-c6** [thingsboard/thingsboard#6765]
****

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  windows 10 and latest
 * ThingsBoard: version
 * Browser: name and version

C:\Program Files (x86)\Thingsboard\thingsboard>install.bat -loadDemo
Detecting Java version installed.
CurrentVersion 110
Java 11 found!
Installing thingsboard ...
ThingsBoard installation failed!C:\Program Files (x86)\Thingsboard\thingsboard>install.bat -loadDemo

**Comment by onoeono** [comment]
maybe u can try to run ThingsboardInstallApplication.java with --loaddemo argument in application module.
remember to copy dao/src/main/resources/sql directory to application/src/main/data before u run
