### ISSUE TITLE
New States and Navigation between states.

### ISSUE THREAD

**Issue by AvishekHardin** [thingsboard/thingsboard#677]
Hello TB Team,

Good day,

I have the following issue: When an item in the entity list is clicked the below function is triggered to fetch the values from DEVICES and in turns create the dashboard for the selected devices.

I actually need similar things but should be pointing to ASSETS instead of DEVICES. Check the "asset.type" if matched to ("test") then open new dashboard "openDashboardState('ITS_state');"

I tried but unfortunately am not successful in doing so. can you please help me. thanks for your help and time.

var $injector = widgetContext.$scope.$injector;

$injector.get('deviceService').getDevice(entityId.id).then(function(device){
	if(device.type == 'W DHT11 Sensor'){
		openDashboardState('ITS-W_state');
	}else if(device.type == 'M DHT11 Sensor'){
		openDashboardState('ITS-M_state');
	}else{
		openDashboardState('ITS-K_state');
	}
});

function openDashboardState(stateId){
	var params = {
		entityId: entityId,
		entityName: entityName
	};
	widgetContext.stateController.openState(stateId, params, false);
}

Thanks,
Best Regards,

**Comment by ashvayka** [comment]
use assetService and getAsset?

**Comment by AvishekHardin** [comment]
Hello Andrew Shvayka,

Thanks for your help. I will try it and feedback the outcomes.

Best Regards,

**Comment by AvishekHardin** [comment]
Hello Andrew,

It worked, thanks for your help

Best Regards

**Comment by oroi1991** [comment]
Hello AvishekHardin,

I got a same problem like 'GET: /api/device/a8b95050-e0f0-11e8-9f7f-df61a781666b 404:'.
How do you resolve about it?

Best Regards

**Comment by colognebroker** [comment]
could you please send the coded source i did not get it 

something is wrong  ?

var $injector = widgetContext.$scope.$injector;

$injector.get('assetService').getAsset(entityId.id).then(
    function(asset) {
        if (asset.getName(asset) == 'Haus See') {
            openDashboardState('haus_see');
        } else if (asset.type == 'Haus Rogg) {
            openDashboardState('haus_rogg');
        } else {
            openDashboardState('ITS-K_state');
        }
    });

function openDashboardState(stateId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.stateController.openState(stateId, params,
        false);
}

**Comment by gladiiss** [comment]
try
`if (asset.getName == 'Haus See') {`
instead of 
`if (asset.getName(asset) == 'Haus See') {`
