### ISSUE TITLE
Alarm Rule Node - Use data-ts when updating

### ISSUE THREAD

**Issue by DataScienceIsCool** [thingsboard/thingsboard#6773]
**Component**

 * Rule Engine

**Description**
I want to create and update alarms in the rule chain using the timestamp from my telemetry.
When creating an alarm startTs and endTs are both nicely set to the ts of the incoming data.
However if the alarm already exists, thingsboard uses its own Timestamp to set endTs, but I
want it to be the TS from the incoming data.
The details-function of the node only lets me configure the details field, which does not help.
So why does Thingsboard use data-TS when creating an alarm, but Thingsboard-TS when updating 
and how do I work around that?

Thx

**Environment**

 * ThingsBoard: 3.3.4.1

**Comment by epalchenko** [comment]
Hello,
Perhaps, in your case, it will help you. Take the structure of the JSON message that comes out of the create alarm node. You can send a message of this structure to the create alarm node with the data-TS you need and activate "Use message alarm data" in this node: 
![image](https://github.com/thingsboard/thingsboard/assets/136599093/bf04293c-182f-4c7a-8b7f-9308517c621c)
