### ISSUE TITLE
[Question] ThingsBoard Edge CE Version is also needed License Key?

### ISSUE THREAD

**Issue by yanru0213** [thingsboard/thingsboard#6776]
**Component**

 * UI
 * Installation

**Description**
I tried to install ThingsBoard Edge and connect it with local ThingsBoard on my laptop. When I was doing the step 1 (https://thingsboard.io/docs/edge/provision-edge-on-server/), I found I still need License Key for adding Edge Instance. But according to installation guide, it's supposed to be without it. In ThingsBoard CE live demo it's not needed, either. I guess there must be something wrong.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/47958470/174993043-0e2ce21f-c12f-4870-90c4-b1e84b3a20f9.png)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/47958470/175014489-e91f7913-14e8-4460-aa14-0844e8a5429b.png)

**Environment**

 * OS:  Windows 10 Pro
 * ThingsBoard: v3.3.4.1
 * Browser: Chrome 102.0.5005.115

**Comment by volodymyr-babak** [comment]
Hello @yanru0213 

TB CE Edge doesn't require any license keys. This screenshot looks strange. 
Could you please clean the browser cache and re-open the page to create an Edge entity?
Maybe you have old UI static files cached in your browser.
