### ISSUE TITLE
[Question] Marker Image Function

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#6777]
Hello, 

I cannot figure out image marker function. I have two entity aliases: APs4, Personal Devices.
Each of them needs its own marker image and eventually I would like to set separate marker images to certain specific devices. 

var deviceType = dsData[dsIndex]['deviceType'];
if (deviceType.toUpperCase() == 'APs4'.toUpperCase())
    {
    var res = {size: 20};
    res.url = images[1];
}
if (deviceType.toUpperCase() == 'Personal Device'.toUpperCase())
    {
    var res = {size: 20};
    res.url = images[2];
}
It am trying this but it is not working. I tried to type individual devices instead of  'APs4' but it didnt helped.

Any advice? 
Thanks.

**Comment by samokomo** [comment]
Can someone help please, I am getting desperate over this trivial thing. I need to switch images based on telemetry or attributes.

**Comment by Backdraft007** [comment]
You have to post more information. What is working and what is not working? What did you configured? Post screenshots of your configurations. So it is easier to help.

**Comment by samokomo** [comment]
I am trying to change image marker on image map. 
I have two entity aliases in this widget. APs5 and Personal devices. APs5 are static and using server attributes for xPos and yPos. 
Personal devices got xPos and yPos as telemetry.
![image](https://user-images.githubusercontent.com/58517178/175033865-f10dd800-d099-4b21-84d1-6554b3fa790f.png)

What I want to achieve: I want APs5 to have image marker 1 (red dot) and personal devices to have marker 2 (blue dot).
![image](https://user-images.githubusercontent.com/58517178/175034407-73355032-9060-4aa5-895b-923b8894a237.png)
