### ISSUE TITLE
[Question] oAuth2 with Cas Server problem

### ISSUE THREAD

**Issue by S0UL4** [thingsboard/thingsboard#6778]
**Component**

 * UI
 * Generic

**Description**
Hi, i tried to do an oAuth2 with a private CAS server , i always get this error : [invalid_id_token] Missing (required) ID Token in Token Response for Client Registration: 5036b830-f16f-11ec-a1f8-bb3bf059bf30

Any idea please ?

PS: i tried an oAuth2 with Google and it worked very well ! 

this is the returned request from my private CAS server ( got it with python ) : 
{
  "attributes": {}, 
  "client_id": "client", 
  "id": "soula", 
  "service": "http://domain_here/authorized"
}
**Environment**

 * OS:  docker container
 * ThingsBoard: latest
 * Browser: Chrome

**Comment by devaskim** [comment]
Could you provide response from Google oAuth2 ?

**Comment by S0UL4** [comment]
Hi Thanks for your response @devaskim ! 

The reponse of the python code on /token (post request ) on my Private CAS server is :
{
  "access_token": "xxxx", 
  "expires_in": 28800, 
  "scope": "profile", 
  "token_type": "bearer"
}

The reponse of the python code on /token (post request ) on Google api is : 
 {
  "access_token": "xxxxxxx",
  "expires_in": 3599,
  "scope": "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
  "token_type": "Bearer",
  "id_token": "xxxxxxx"
}.

**Comment by S0UL4** [comment]
@devaskim  i got this error when i changed the mapping to custom : 
[
![image](https://user-images.githubusercontent.com/62818840/175103060-f9cbe2fb-1305-4249-b703-679dddefb38f.png)
](url)

**Comment by S0UL4** [comment]
@devaskim  there is actually some progress.. this now is my response from the CAS : 

{
  "attributes": {
    "mail": "xxxx", 
    "memberof": [
      "CN=xx,OU=xx,OU=xx,OU=xx,DC=xx,DC=xx", 
      "CN=xx,OU=xx,OU=xx,DC=xx,DC=xx"
    ], 
    "oauthClientId": "client"
  }, 
  "client_id": "client", 
  "id": "soula", 
  "service": "http://domain_here:8080/authorized"
}

any idea of how can i add to the email attribute in the basic mapper the values under "attributes"["mail"] ?

**Comment by devaskim** [comment]
Basic mapper doesn't support nested fields.

**Comment by devaskim** [comment]
Also TB expects `id_token` but CAS server didn't send it.

**Comment by S0UL4** [comment]
Thanks so much @devaskim  i will take a look on that and update you.

**Comment by S0UL4** [comment]
Hi @devaskim , if a user connected to thingsboard via oAuth2, is there a way to set a password to this user via Thingsboard UI for Rest API purpose ? I tried to set a password via the UI but i have to set first the 'current password' which i don't have..

**Comment by devaskim** [comment]
As I understand the end of [this code line](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java#L152), *current password* is empty string

**Comment by devaskim** [comment]
Here rea [API endpoints](https://demo.thingsboard.io/swagger-ui/#/auth-controller) to manage passwords and other auth things.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
