### ISSUE TITLE
Thingsboard CPU utilization greater then 100% - thingsboard not available.

### ISSUE THREAD

**Issue by mensch92** [thingsboard/thingsboard#678]
Hi,

I'm working on a IoT project with raspberry pi which sends every second a dataset via MQTT to a server which runs thingsboard with the embedded database. The **cpu** utilization (in top -n1) shows **more then 100%** (300%) and thingsboard isn't available. After a reboot nothing changes. Thingsboard has ran for a couple of hours. The server has 4 GB memory and is running a four-core processor.
The thingsboard UI isn't available. And the raspberry pi can't connect to thingsboard mqtt broker. Do someone know the problem and how can I fix it?

cheers and thankyou
Pirmin

**Comment by Tangerino** [comment]
Have you looked in the log file at /var/log/thingsboard ?
please see my issue #680
Is it related?

**Comment by vparomskiy** [comment]
1. What version of Thignsbaord are you using?
2. Could you provide Thignsboard log file
3. Is embedded database a HSQLDB ? If yes, then it is not a good option for production instances. Postgres should be a better solution.
4. What dataset size is sent over MQTT each second (in bytes)
