### ISSUE TITLE
[Question] How to assign all devices to multiple Customers?

### ISSUE THREAD

**Issue by pegah-mir** [thingsboard/thingsboard#6786]
**Component**

 * UI

**Description**
I want to assign the same device and dashboard to  multiple customers, but I can't assign the same device to more than one customer

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.31
 * Browser: Google chrome and Version 102.0.5005.61

**Comment by devaskim** [comment]
By design, one device belongs to one customer. To share data from the same device to multiple customers try [Entity Views](https://thingsboard.io/docs/user-guide/entity-views/).

**Comment by Buhaw85** [comment]
If you share data with entity view are they also able to veiw the dashborad now?

**Comment by devaskim** [comment]
yes, each customer will see all data being exported by entity views

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
