### ISSUE TITLE
UI not rendering

### ISSUE THREAD

**Issue by satyasuman** [thingsboard/thingsboard#679]
Latest code broke UI, seeing this error on the console 

javascript.js:3 Uncaught TypeError: ace.require is not a function
    at javascript.js:3
    at Object.<anonymous> (javascript.js:5)
    at e (bootstrap 119b78cb2d202ffada13:73)
    at Object.<anonymous> (widget-editor.controller.js:23)
    at e (bootstrap 119b78cb2d202ffada13:73)
    at Object.<anonymous> (index.js:34)
    at e (bootstrap 119b78cb2d202ffada13:73)
    at Object.<anonymous> (index.js:48)
    at e (bootstrap 119b78cb2d202ffada13:73)
    at Object.<anonymous> (app.js:66)

Uncaught Error: [$injector:modulerr] Failed to instantiate module thingsboard due to:
Error: [$injector:nomod] Module 'thingsboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by satyasuman** [comment]
I was able to fix this issue locally, am not sure if there has been a recent upgrade to the ace-editor npm module. The widget-editor-controller is dependent on this module and since it cannot load the ace-editor module the new build fails to render the UI. I fixed this issue by going into the ace-builds npm module and changing it from **ace.require** to **ace.acequire**

**Comment by punee995** [comment]
I'm facing same problem!
@satyasuman can you describe in detail, in which file need to make changes in ace-builds??

**Comment by BIT-masterpy** [comment]
@satyasuman

**Comment by gitsea** [comment]
when I had fix https://github.com/thingsboard/thingsboard/issues/683，another failed came out for thingsboard1.0 installing:
angular.js:15697 TypeError: Cannot read properties of undefined (reading 'length')
