### ISSUE TITLE
Prediction/Forecasting

### ISSUE THREAD

**Issue by chiavariniluca** [thingsboard/thingsboard#6791]
Hi!
I have ThingsBoard in cloud and I would like to implement prediction (forecasting) for my timeseries line chart.
![image](https://user-images.githubusercontent.com/102251679/175027950-0cfd2521-89cd-4e29-a47e-7c796c8e60ea.png)

How can I implement it?

I saw a tutorial on thingsboard website (https://thingsboard.io/docs/trendz/prediction/), but I can't do that.

Thank you in advance.
Best regards,

Luca

**Comment by chiavariniluca** [comment]
I have Trial licence with ThingsBoard. Can I install/activate Trendz for free and connect it with my free ThingsBoard licence?
Thank you in advance!

**Comment by Backdraft007** [comment]
You can install Trendz on an own server and connect it to Thingsboard CE/PE.
https://thingsboard.io/docs/trendz/connect-thingsboard/

You can try Trendz for 30 days.
https://thingsboard.io/pricing/?section=trendz

**Comment by chiavariniluca** [comment]
Ok, thank you!
