### ISSUE TITLE
Websocket not sending telemetry updates for multiple devices with different subscription cmdId values

### ISSUE THREAD

**Issue by danomatika** [thingsboard/thingsboard#6799]
**Describe the bug**

I am developing a custom tool using Python and the Thingsboard Websocket API to receive telemetry updates from multiple devices. Fetching the user access token and subscribing to a single device over a websocket works fine following the example and info laid out in the TB documentation.

For multiple devices, subscribing works but I am not able to utilize the subscription `cmdId` as expected. This key is not really explained in detail in the documentation but my understanding is that I can give each device subscription a different `cmdId` which will then be used to set the corresponding telemetry update's `subscriptionId`. This way I can tell which device is sending the update.

What I am experiencing in Python is:

* Subscribing to multiple devices using the same `cmdId` value (ie. 10):
  - Initial connection telemetry update received for all devices
  - Live updates received from all devices
  - *Cannot tell devices apart*
* Subscribing to multiple devices using a different `cmdId` values (ie, 1, 2, ...):
  - Initial connection telemetry update received for all devices
  - Live updates received *only from last subscribed device*

I also checked this in HTML+Javascript using the websocket example included in the TB documentation and see the same issue.

My subscription JSON payload looks like the following:
```python
subscription_cmd = {
    "tsSubCmds": [
        {
            "entityType": "DEVICE",
            "entityId": "e5a69b00-...",
            "scope": "LATEST_TELEMETRY",
            "cmdId": 1
        },
        {
            "entityType": "DEVICE",
            "entityId": "25b7fd90-...",
            "scope": "LATEST_TELEMETRY",
            "cmdId": 2
        }
    ]
}
```

**Your Server Environment**

* own setup:
  - local server install
  - ThingsBoard v.3.3.4.1
  - Linux, probably Ubuntu (I am not the admin)
  - probably Docker deployment
* demo.thingsboard.io (haven't tried yet, can later)

**Your Client Environment**

* OS: macOS 12.4
* Custom Python client: Python 3 with requests and websockets libs
* Browser: HTML+Javascript test in Safari and Chrome

**Comment by devaskim** [comment]
This is not an answer but you can create dashboard with several widgets. Each widget will listen to updates for different device. Then you open browser DevTools, Network tab and enable WS (websocket) filter. There you will see subscription data. Hope this will help you

**Comment by danomatika** [comment]
@devaskim Thanks for the tip. I indeed can considered why the dashboard might work while subscriptions form the external client would not. I did try this and can see the widgets are using `entityDataCmds` to subscribe to specific keys.

In any case, I think the problem lies with our server. I noticed that the live telemetry time series display when selecting a device in the device panel sometimes stops updating live. I only get a new value on a page refresh. Same with the widgets when creating a dashboard: no updates.

I went ahead and created a test account on the demo.thingsboard.io server and everything is working as expected, both on the web interface and via my custom send and receive clients. I guess I should have started with this server first. :)

Before I close this issue, is there anything I can relay to our server admin on what might be causing this issue, ie. blocked firewall ports, config options, etc? Thanks

**Comment by danomatika** [comment]
No response. Ok, closing anyway.

**Comment by skewty** [comment]
@danomatika did you figure out a solution to your problem?  Do you mind sharing the solution?

**Comment by danomatika** [comment]
No solution. Waiting to have the server moved to new hardware and reinstalled. We don't have time to deeply debug.
