### ISSUE TITLE
TB not available after reboot

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#680]
TB not available after reboot.
The log says out of memory. The first error message is listed below. If someone can help me here I can send the whole log. 
I do have a demo at April 1st for a customer and the app is not finalized yet, please help.

<pre>
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:101)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:112)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
</pre>

**--- Server ---**
CPU: 4
Memory: 8GB
Disk space available: 95% (75GB)

```bash
$free
              total        used        free      shared  buff/cache   available
Mem:        8174936     2591040     4796532        8836      787364     5321824
Swap:             0           0           0
```
```bash
$uptime
 09:38:56 up 23 min,  1 user,  load average: 0.00, 0.40, 1.07
```

**Comment by sreibs** [comment]
Hi.

Same problem here I think. I am using Thingsboard v1.4. (docker)

Everything worked fine for several weeks and suddenly got down. I have a device sending MQTT data (2 timeseries) every second. Hsqldb is 350Mo.

I attached the logs. 

I think if I clean up the hsqldb, it should work again, but I am not sure what I will loose ? (only data? user account? Relations ? Devices ?)...

Thank you for your help.
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/1923001/thingsboard.log)

**Comment by vparomskiy** [comment]
Not actual anymore since starting from Thingsboard v2.1 platform architecture was changed. Closing
