### ISSUE TITLE
[Question] How to listen to mqtt messages received

### ISSUE THREAD

**Issue by medutySMST** [thingsboard/thingsboard#6801]
**Component**

 * Generic

**Description**
setup: 

1. there is 1 gateway device connected to lots of sensors in reality.
2. there is 1 tb device that has 'is gateway' enabled and has Access Token X.
3. the gateway device sends mqtt messages to thingsboards default mqtt api in order to create tb devices for the real sensors, and publish their data. 

My questions: How can I listen to the messages that thingsboard receives this way?

**Environment**

* docker deployment
* ThingsBoard v.3.3.4.1PE
* Browser: latest Chrome

**Comment by devaskim** [comment]
Clarify your goal, please. Do you want to ensure data has been delivered to the server? 
From docs:
```
ThingsBoard server nodes act as an MQTT Broker that supports QoS levels 0 (at most once) and 1 (at least once) and a set of configurable topics.
```

**Comment by medutySMST** [comment]
I want to read the messages that thingsboard receives for troubleshootin, maybe read logs of the mqtt interaction or similar

**Comment by jeffcai** [comment]
you may check out the link: https://thingsboard.io/docs/user-guide/troubleshooting/?deploymentType=docker-compose#logs, for enabling the log trace for incoming message.

Regarding source code, MqttTransportHandler is the class handling incoming MQTT message, method channelRead is to read message, which uses log trace to print the message like log.trace("[{}] Processing msg: {}", sessionId, msg);

hope it helps.

**Comment by medutySMST** [comment]
Thank you very much, will look this up.
