### ISSUE TITLE
Customer's user is able to harm tenants relation and edit server attributes

### ISSUE THREAD

**Issue by asnik** [thingsboard/thingsboard#681]
Hello,

I suspect it is not correct situation:

1. As Tenant admin I created the device and added Relation for device to be Managed by Tenant. I need this relation to have a map and entity list of all tenant's devices (big helpdesk and service dashboard for monitoring of all devices available).
2. Assigned this device to customer, created and assigned end-user dashboard to customer. 
3. Login as customer's user, can see end-user dashboard and device. Unable to edit, it is nice.
4. Go to device, go to relations, see relation with tenant. Click edit - get access error, it is nice. Click delete - ok! Relation have been deleted and at tenant's level the device has disappeared from entities list and map widget. If I try to add new relation I unable to choose tenant as type, it is correct. 

So customer's user can do one way action to unlink tenant's relation and forget him forever. I think it is not intended by design?

Also customer's user can edit server attributes of device. It is not good for my case but may be ok in other sutuation. However, if a customer is not able to create and edit device, why he should change server side parameters created and appointed by tenant? No protection from customers, he can change Id, serial#, location...

Best regards,
Anton

**Comment by tensojka** [comment]
Is this fixed by 1d1fd7711f9189f3f2aa06e3625f351ec63bd798?

**Comment by Ultrazombie** [comment]
@asnik 
Is this problem still relevant on the latest ThingsBoard version?
