### ISSUE TITLE
[Question] How to set Storage time, let's say, to 3 years?

### ISSUE THREAD

**Issue by IrmantasKa** [thingsboard/thingsboard#6810]
**Component**
 * Rule Engine
 
**Description**
ThingsBoard Cloud Subscription plans Maker: Default storage TTL 60 days. The maximum allowed value of TTL is 5 years. Default value of the "time to live" parameter that is used to store time-series data. You may overwrite the default value in the "Save Timeseries" rule node.
Stores Timeseries data from incoming Message payload to the database and associate them to the Entity, that is identified by the Message Originator. Configured TTL seconds is used for timeseries data expiration. 0 value means that data will never expire.

In "Save Timeseries" rule node TTL seconds=0. Storage time actually is 60 days.

How to set Storage time, let's say, to 3 years?

Thanx.

**Comment by devaskim** [comment]
I think you can find answer [here](https://thingsboard.io/docs/user-guide/telemetry/#data-retention)

**Comment by IrmantasKa** [comment]
> I think you can find answer [here](https://thingsboard.io/docs/user-guide/telemetry/#data-retention)

No, I didn't... Thank you for your help.
In "Save Timeseries" rule node TTL seconds=0, but Storage time actually is 60 days.

**Comment by devaskim** [comment]
It is not clear for me why you don't override TTL in "Save timeseries" node. 0 means what server will use pre-defined system value (60 days for your plan)

**Comment by Civilduino** [comment]
According to issue #7474 you have to set the TTL value as a "long type".

@IrmantasKa How do you see the storage time assigned to the telemetry after it is stored in the database?

**Comment by ban2derlog** [comment]
if you want to save data for 3 years - you need to set in Save Tieseries node default TTL to "94608000" (3 years in seconds)
