### ISSUE TITLE
[Question] How should I understand the telemetry of the Tenant User?

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#6818]
**Component**
 * UI

**Description**
As Sysadmin user, I can view the Tenant User detail-page, where there is a card named Telemetry.

And  from https://thingsboard.io/docs/user-guide/telemetry/ I can find there is a API "http(s)://host:port/api/plugins/telemetry/{entityType}/{entityId}/keys/timeseries", in where the supported entity types are: TENANT, CUSTOMER, USER, DASHBOARD, ASSET, DEVICE, ALARM, ENTITY_VIEW.

But when I view Tenant Detail-page, indeed there is a ws call to get the telemetry, and there is no data.

So, I want to know, how should I use this API, and what can I get.

**Comment by ssakharova** [comment]
Hello @lsyer,

For any future improvements, we have retained this functionality for some entity types, including TENANT. However, please note that it does not work for the TENANT entity type, so you can ignore it in that context.
