### ISSUE TITLE
Saving entity attributes in custom widget

### ISSUE THREAD

**Issue by Pr0m3the3u5** [thingsboard/thingsboard#6820]
I'm currently using the custom actions on a time-series row click to read/write to the server attributes.

using:
     
     let attributeService = widgetContext.attributeService;
     attributeService.getEntityAttributes(entityId,'SERVER_SCOPE',["testAttribute"]).subscribe((attributes) => {console.log(attributes)});

I can read the correct value from the device server attributes.

From what I can tell to write to the attribute i need to use something like this

    let shared_attributesArray = []
    shared_attributesArray.push({key: 'testAttribute', value: '200'})
    var retVal = attributeService.saveEntityAttributes(entityId,'SERVER_SCOPE',shared_attributesArray);

but this does not update the value in the device

can anyone help?
thank you

**Comment by lucasKapf** [comment]
Hello, I think that you also have to subscribe to the saveEntityAttributes function to make it work : 
Try this : 

```
let shared_attributesArray = []
shared_attributesArray.push({key: 'testAttribute', value: '200'})
attributeService.saveEntityAttributes(entityId,'SERVER_SCOPE',shared_attributesArray).subscribe((res) =>   { widgetContext.updateAliases();})

```

**Comment by Pr0m3the3u5** [comment]
that seems to have worked thank you

**Comment by vmlourenco** [comment]
Hello, im trying to replicate this in my project, but an error was occurred, can you help me? thanks
![image](https://user-images.githubusercontent.com/25009197/175647352-defb1df4-fd0f-4e0f-86a1-9cc7c72fc841.png)

**Comment by lucasKapf** [comment]
Hi @vmlourenco 

attributeService is not defined : try to add this at the beginning of your code : 

```
let $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
```

Now you should not have error anymore
