### ISSUE TITLE
[Question] UI: Any tips and tricks to implement infinite scroll in custom widget

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6823]
I am developing widget what will show a list of asset (_Asset type_ alias). Each asset will be represented as Material card with several telemetry parameters and single SVG mini-gauge. I want to implement infinite scroll to dynamically load next "group" of assets. Maybe someone did the same and could give some advice...

**Comment by dhaval2017** [comment]
1) make static widget
2) default load first type 
3) for to load rest use this code https://stackoverflow.com/questions/5059526/infinite-scroll-jquery-plugin

**Comment by devaskim** [comment]
@dhaval2017 Ok, I will get next bunch of assets, but how I subscribe to telemetry from each of these assets? As I described above I need to display both asset's fields such name or label, and asset's telemetry.
