### ISSUE TITLE
[Question] How to use  Entity view in RPC widget 

### ISSUE THREAD

**Issue by pegah-mir** [thingsboard/thingsboard#6826]
**Component**

 * UI
 
**Description**
If I want to share the same device on multiple dashboards, I will use entity view, but entity view cannot be used in RPC widget. In multiple RPC widgets, how can I use entity view?

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.2
 * Browser: Google chrome

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
