### ISSUE TITLE
login page failed to load because of "ace.require is not a function"

### ISSUE THREAD

**Issue by 18616505009** [thingsboard/thingsboard#683]
javascript.js:3 Uncaught TypeError: ace.require is not a function
    at javascript.js:3
    at Object.<anonymous> (javascript.js:5)
    at e (bootstrap 6c7563406c877110f2a5:73)
    at Object.<anonymous> (widget-editor.controller.js:23)
    at e (bootstrap 6c7563406c877110f2a5:73)
    at Object.<anonymous> (index.js:34)
    at e (bootstrap 6c7563406c877110f2a5:73)
    at Object.<anonymous> (index.js:47)
    at e (bootstrap 6c7563406c877110f2a5:73)
    at Object.<anonymous> (app.js:66)
(anonymous) @ javascript.js:3
(anonymous) @ javascript.js:5
e @ bootstrap 6c7563406c877110f2a5:73
(anonymous) @ widget-editor.controller.js:23
e @ bootstrap 6c7563406c877110f2a5:73
(anonymous) @ index.js:34
e @ bootstrap 6c7563406c877110f2a5:73
(anonymous) @ index.js:47
e @ bootstrap 6c7563406c877110f2a5:73
(anonymous) @ app.js:66
e @ bootstrap 6c7563406c877110f2a5:73
(anonymous) @ bundle.6c7563406c877110f2a5.js:5
e @ bootstrap 6c7563406c877110f2a5:73
window.webpackJsonp @ bootstrap 6c7563406c877110f2a5:44
(anonymous) @ bundle.6c7563406c877110f2a5.js:1

I'm new to TB and i had not make any changes to the UI module but change some text words to check if npm run build will work on generating pages.This problem raised yesterday afternoon and seems like it's unrecoverable.I've reset my code to former version but did not make any sense.Seeking for help and thanks.

**Comment by punee995** [comment]
got working....
made changes in **thingsboard/ui/package.json**  change line to "ace-builds": "1.3.1",

**Comment by 18616505009** [comment]
Still not working for me after changing
    "ace-builds": "^1.3.1"
in package.json,execute "npm run build" and restart spring

**Comment by punee995** [comment]
not **"ace-builds": "^1.3.1"**
just **"ace-builds": "1.3.1"**

**Comment by 18616505009** [comment]
Yes my fault,but in my case it turned out to be other mistakes.
Finally I took the advice of my coworker:
1.go to ui directory open command line
2.mvn clean
3.mvn install
while mvn clean & mvn install does exactly the same work I've tried with npm install&npm run build,but it worked this time.
Thanks @ punee995,issue close now.
