### ISSUE TITLE
[Question] How to filter image map data based on Time? Curent data only.

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#6831]
* UI

**Description**
Hello, I would like to filter data sources on image map widget by time. My data is from Wi-Fi and it contains Timestamp. I want to display only sources with data which is not older than 5 minutes compared to current time. How to do this please? I kinda dont understant how to filter this - How the time relative values work.... Or do you know any other way how to do this easily? 

![image](https://user-images.githubusercontent.com/58517178/175919055-2bece48e-75bc-428d-b95f-0273575aef35.png)

**Environment**
 * OS: Win 10
 * ThingsBoard: Community edition
 * Browser: Edge

**Comment by devaskim** [comment]
I think it would be possible only if you create self-updated attribute for user/customer/tenant where you would store `currentTime - 5 minutes`. Then you could use this attribute in filter. By self-updated attribute I mean using rule chain and its [Generator rule node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#generator-node) to periodically trigger update.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
