### ISSUE TITLE
[Bug] Asset doesn't appear in Asset group when the owner is changed and come back to the original value

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6843]
**Describe the bug**
I changed the owner of an Asset to test the fonctionality and I changed again the owner to the original one. Now the Asset doesn't appear in the group of its type attribute. It's only in all group.
I tried to change the type but it doesn't go in the seized group .

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**
* OS:  Windows 11
* Browser All

**Expected behavior**
The Asset should appear in the group of its type.

**Comment by SuminDenis** [comment]
Hi @liotys,

The behavior mentioned above may occur when you didn't set a group for the asset in the dialog window presented in the following screenshot:
![image](https://github.com/user-attachments/assets/b6917d3c-801e-4113-b2ea-f33ff8edc2bd)

To avoid this issue, manually set a group for this asset. Please familiarize yourself with the following screenshot example:
![image](https://github.com/user-attachments/assets/ac656054-25c5-414a-898b-7e32de720e1e)

If you use Rule Chain for this purpose, to investigate this issue, we need more details such as:

1. Rule Chain Example
2. Asset's attributes
3. ThingsBoard version
