### ISSUE TITLE
[Bug] NO_ACTIVE_CONNECTION On Second RPC SNMP Request

### ISSUE THREAD

**Issue by Zac1209** [thingsboard/thingsboard#6848]
**Describe the bug**
I am trying to use RPC request to get info from a device which is configured for SNMP. When I first start up ThingsBoard, I can make the request and get an answer, but after that if I do another request I get a 409 conflict error and in my Thingsboard log I have a NO_ACTIVE_CONNECTION error.

Device profile configuration in the screenshots

Here is my RPC request:
POST http://{TB IP}:8080/api/plugins/rpc/twoway/{DEVICE ID}
{
    "method": "GET",
    "params": {
        "key": "intensity"
    }
}

**Your Server Environment**
Own setup on docker.
Tb version 3.3.3

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windoes
* Browser Postman or Chrome

* Connectivity
  * HTTP

**To Reproduce**
1. Start Thingsboard with the device profile transportation configured as bellow
2. Add a device with the appropriate profile and set the correct IP, port, protocol version and community string
3. Make a server side RPC request with either PostMan or Chrome. Request is described above.
4. Get a good result the first time
5. Make the same or another request again
6. Get the error until you reboot ThingsBoard.

**Expected behavior**
Get an answer to my SNMP request

**Screenshots**
![image](https://user-images.githubusercontent.com/13938446/176250927-e1cb41d6-d4d8-458f-8711-4a6cee211a28.png).

**Comment by ban2derlog** [comment]
Hi,
HTTP 409 error means that there is a conflict between request and response.
Do you configure properly time on your server and device?
Also, is your device have timeout or connection restriction?
E.g. - if you try to load a big amount of data and device still trying to load previous request, there can be issues.

**Comment by Zac1209** [comment]
> Hi, HTTP 409 error means that there is a conflict between request and response. Do you configure properly time on your server and device? Also, is your device have timeout or connection restriction? E.g. - if you try to load a big amount of data and device still trying to load previous request, there can be issues.

I've checked that the time server is set exactly the same on the device and the server.
By checking with wireshark, Thingsboard is not even sending the request to the device.

**Comment by ban2derlog** [comment]
З

**Comment by ban2derlog** [comment]
Hi, I think that you need use Persistent RPC.
https://thingsboard.io/docs/user-guide/rpc/#persistent-rpc
You can take reference from RestAPI - http://{TB IP}:8080/swagger-ui.html
`rpc-v-2-controller
POST /api/rpc/twoway/{deviceId}`
And use Persistent - True.

Additionally, you can read here - https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc
Under Two-way server-side RPC

**Comment by Zac1209** [comment]
Hi,

I'm already using 2 ways. I also tried persistent RPC. The request only get put in the queue, but isn't sent to the device. I'm monitoring my device using WireShark and I never see a request even being tried to be sent to it. Is my structure for a SNMP request correct? I have my oid setup in the device profile. I think that SNMP is the protocol that lacks the most of documentation on thingboard. Like it's supported, but with almost no documentation.

Thank you,

**Comment by ban2derlog** [comment]
@Zac1209 
Do you try to use TCP for SNMP?
You can change UDP\TCP by this environment:
`SNMP_UNDERLYING_PROTOCOL`

**Comment by Zac1209** [comment]
@ban2derlog 
Just tried it. Same result.
Thanks

**Comment by ban2derlog** [comment]
HI, do you try to use exactly rpc v2 controller?
it has different API endpoint, in v1 there;
http://tb_host/api/plugins/rpc/twoway/DEVICE
in rpc v2:
http://tb_host/api/rpc/twoway/DEVICE
