### ISSUE TITLE
API for posting telemetry on behalf of other devices

### ISSUE THREAD

**Issue by ralienpp** [thingsboard/thingsboard#685]
What is the recommended way of publishing telemetry on behalf of other units?

The MQTT, CoAP and HTTP documentation refers to an access token, which will link all the posted telemetry to the account associated with the token. However, my use case is different.

A gateway collects data from multiple devices provisioned in Thingsboard. They are not TCP/IP, they use their own communication technology that my gateway understands. When the gateway receives the telemetry from these proprietary devices, it should post it to Thingsboard.

If I have a thousand of such devices, I would like to avoid opening a thousand separate connectioins to Thingsboard (each with its own access token), but rather use a single connection, and substitute the information about the originating device. As a result, Thingsboard will not visualize the telemetry as it belongs to a device called "gateway", but it will associate it with the actual device that send the data.

Can this be accomplished through the existing API? If not, what is the most non-intrusive way of writing this directly to the database?

**Comment by Karabiy** [comment]
you can use the ThingsBoard Professional Edition integration functionality for those reasons. The integration doesn't require to have the access token be used, it just maps the devices based on their names. You can follow this link regarding the integration feature option: https://thingsboard.io/docs/user-guide/integrations/
