### ISSUE TITLE
when will 3.4 version be released

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6854]
when will 3.4 version be released?

**Comment by Backdraft007** [comment]
Duplicate
https://github.com/thingsboard/thingsboard/issues/6720

**Comment by john1337** [comment]
> Duplicate #6720

although it's duplicate,but it didn't say when it will be released

**Comment by KenSense** [comment]
Anyway I prefer to have it delayed than having an important fix the week after that will require an extra update procedure.

**Comment by technorabilia** [comment]
Unless, like us, you are eagerly waiting for the features in 3.4.

But of course I agree with you. Better safe than sorry.
