### ISSUE TITLE
How to change some menu names

### ISSUE THREAD

**Issue by abadfasdf** [thingsboard/thingsboard#6855]
I tried changing the menu name after watching tutorials and videos.

However, I do not know how to change the names of user, custome, device, and dashboard groups.

I wrote the code below to change the device group name, but it doesn't work.

   "device_groups": {
    "device_groups": "장치관리"
      },
![캡처](https://user-images.githubusercontent.com/108421427/176594660-60e86d7a-e185-4620-86d4-fa4bb118d3dd.JPG)

**Comment by trikimiki** [comment]
The best way to edit custom translation is to download a default locale (White Labeling -> Custom Translation -> select e.g. "English" -> Download locale file), search and add corresponding lines you want to translate into your custom translation.

Here is what you were looking for:
```
"entity-group": {
    "entity-group": "Entity group",
    "details": "Details",
    "columns": "Columns",
    "add-column": "Add column",
    "column-value": "Value",
    "column-value-required": "Column value is required.",
    "column-title": "Title",
    < . . . >
    "user-group": "User group",
   < . . . >
   }
   ```
