### ISSUE TITLE
[Question] How to applying different Data Aggregation functions on each field of a Timeseries Graph

### ISSUE THREAD

**Issue by a-haseeb7838** [thingsboard/thingsboard#6856]
**Component**

 * UI

**Description**
I have two data sources and I want apply Data aggregation functions on each of them separately e.g. I want to plot X and Y fields on a time series plot. Currently, one Data aggregation function is applied to both fields but I want to apply different Data aggregation functions on each field i.e. SUM on one field and AVG on another field. 

I'm using Timeseries Line Chart

![image](https://user-images.githubusercontent.com/92732494/176608470-493f7226-9489-475b-a99d-5b8d7d81319f.png)
![image](https://user-images.githubusercontent.com/92732494/176608483-ed5f8f9a-63a0-45a5-8db7-72b8afbaaf71.png)

Is it possible or there is another way to customize it?
Looking forward to your kind help

**Comment by mde2017** [comment]
Hi @a-haseeb7838,

this is not possible with ThingsBoard itself, but via Trendz Analytics product:
https://thingsboard.io/docs/trendz/

Example with SUM & AVG aggregation:
![image](https://user-images.githubusercontent.com/25298332/176621213-5abbc808-b0d5-47eb-8552-b0be4fddd262.png)

**Comment by a-haseeb7838** [comment]
Thanks for the quick response.
Trendz is a separate product. I think they should provide it in thingsboard as well.

**Comment by mde2017** [comment]
Yes, but there is 30 day trial version available.

There is also another way, but only possible with ThingsBoard PE. You could precompute the aggregated values using the Analytics rulenodes and then use them in the Dashboards.

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by jrkubic** [comment]
> Yes, but there is 30 day trial version available.
> 
> There is also another way, but only possible with ThingsBoard PE. You could precompute the aggregated values using the Analytics rulenodes and then use them in the Dashboards.

I know it's old but is there any chance you can elaborate on these steps a bit? We plan on going to Trendz Analytics in the future but for this quick implementation it's not worth it.

Do I just edit the rule chain so that there is an additional key that is just a counter of what sort of aggregation I am doing, attached to the datasource?
