### ISSUE TITLE
[Feature] UI: Conditional option or widget action to show/hide widget

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6866]
**Is your feature request related to a problem? Please describe.**
As of version 3.3.4.1 I couldn't find any solution to specify conditions whether to show or hide widget as it was already done for some type of widget actions.

**Describe the solution you'd like**
It may be JS function in *Settings section*  of widget configuration or widget action (not sure for the last). This function/action would have widget context parameter and return *true/false* to show or hide widget.

**Describe alternatives you've considered**
No

**Comment by devaskim** [comment]
@ssakharova Please, take a look

**Comment by ssakharova** [comment]
Hello @devaskim,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
