### ISSUE TITLE
[Question] How to programmatically close dashboard state opened as dialog

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6867]
**Component**
 * UI

**Description**
When I trigger widget's custom action with template, I have access to `dialogRef` and its method `close()` from `vm` variable. So I can programmatically close the dialog.

I want to have or do the same but with dashboard state opened as dialog. Is it possible as of 3.3.4.1? I couldn't find any `dialogRef` in widget context and `$scope` container.

**My case is the following:**
Dashboard state includes single custom widget, it's a creation form. I want to click *Save* button on this form, save what I need and then close dashboard state dialog.

**Environment**

 * ThingsBoard: 3.3.4.1

**Comment by devaskim** [comment]
@vvlladd28 Could you suggest something?

**Comment by devaskim** [comment]
need help - help yourself(

**Comment by vvlladd28** [comment]
Hi @devaskim,
As an option, I can suggest saving in the widget context in the dashboard key to minimize the number of translations linked to dialogRef. Because if you save the link in the root of widget context, it will need to be copied to all state widgets

**Comment by vvlladd28** [comment]
Perhaps the best option would be to make a link in the dashboard in stateController.

**Comment by devaskim** [comment]
Thanks @vvlladd28 for idea, but how would I pass dialog link from [EmbedDashboardDialogComponent](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/dialog/embed-dashboard-dialog.component.ts#L62) to stateController?

**Comment by devaskim** [comment]
Or do I need to set the link in (WidgetComponent [https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1434] after dialog creation?

**Comment by vvlladd28** [comment]
It is better to set the link after dialog creation

**Comment by devaskim** [comment]
> Perhaps the best option would be to make a link in the dashboard in stateController.

@vvlladd28 Unfortunately code structure is unclear for me, for example:
`widgetContext -> stateController -> dashboardCtrl -> dashboardCtx -> !!! AGAIN !!!  stateController `

I tried to add _dialogRef_ to _dashboardCtx _ and then set it after dialog creation. But for other widgets _dialogRef_ stayed _null_

So I suggest to approve this PR [#6991](https://github.com/thingsboard/thingsboard/pull/6991) :) and close this ticket.
