### ISSUE TITLE
zoom/pan for charts?!

### ISSUE THREAD

**Issue by whhsn** [thingsboard/thingsboard#687]
Hi
Does the chart has zoom/pan functionality?
Are there any user developed widgets?

R,

WH

**Comment by vparomskiy** [comment]
In Telemetry history widget you can zoom into the specific time interval that can be selected with a mouse.
Doubleclick will zoom-out to default time window.
The custom widget should be developed if need other options.

**Comment by whhsn** [comment]
Unfortunately I am not good in JAVA :(
Are there any one working to enhance the widgets?

**Comment by asnik** [comment]
afaik, widgets do not use Java but JavaScript.

**Comment by vparomskiy** [comment]
yes, Javascript
Here is starting point
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
