### ISSUE TITLE
[Question] 'onLoaded' callback method for custom map widget?

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#6870]
I've created a little custom map widget which uses         `self.ctx.dashboard.dashboardTimewindowChangedSubject.next(newDashboardtimewindow);` to change the dashboard's timewindow within the "onInit"-method. 

However, this change of the timewindow doesn't become apparent for the other widgets of the dashboard (chart widget still showing default timewindow).

Only after using `updateAliases()`  this change becomes effective. 
Yet, this needs to happen **AFTER**  the map widget has been loaded. 
If I put  `self.ctx.updateAliases()` at the end of the onInit()-Method of my custom widget, this is too early.

Is there something like an `onLoaded()`-method which triggers after the Widget has been fully loaded?
I believe this would be the proper location for updateAliases()

**Comment by mde2017** [comment]
Hi @eeitnn,

Have you tried using the following function to set the dashboard timewindow? 
I previously used this with `onInit()` for a line chart.

`self.ctx.timewindowFunctions.onUpdateTimewindow(startTimeMs, endTimeMs);`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
