### ISSUE TITLE
[Question] Rewind/player component in image map widget

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#6871]
**Component**
 * UI

**Description**
Hello thingsboard community. I would like to have rewind/player (timewindow) option in my image map widget as I would love to check historical data this way. This function is available in trip animation widget. Do I have to code and create new custom widget to be able to achieve this?
I am basically trying to get this:
![image](https://user-images.githubusercontent.com/58517178/177125082-61ceab62-e62c-46b1-ba02-35c6f7024188.png)
implemented into image map. Is it possible?

Thanks.

**Environment**
 * ThingsBoard: Community edition
 * Browser: Edge

**Comment by mykhailokornieiev** [comment]
Hi
I can say that there are definitely no standard widgets that could meet your requirements. The only option is to try to create a custom widget.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
