### ISSUE TITLE
[Question] Same dashboard for all customers

### ISSUE THREAD

**Issue by Orion4048** [thingsboard/thingsboard#6873]
**Component**
 * UI
 * Generic

**Description**

I have a project with one device profile, many devices and customers. All customers will use mobile application to access their unique devices. I've installed thingsboard server, created a device profile, a device (with the created profile), a customer, and a user for that customer. Then thanks to your ESP8266 GPIO control guide, i could realize a working platform that i can control my ESP8266 board with Android mobile application (with necessary dashboard). In device profile, Mobile Dashboard is also changed to the GPIO dashboard.

So far, everything is ok. But there is one thing i don't understand. If customers will not be assigned to the dashboard, it will not be visible for users, and i get permission error (With adb chrome debug). Tried to make dashboard public, but nothing has changed. Should i create new dashboard for every customer or assign all customers to the dashboard? Looked in to the dashboard table in database and it doesn't look possible to add too many customers, because of the structure (assigned_customers header). I want to show the same dashboard for all users.

Thanks.

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.4
 * Browser: Google Chrome 103.0.5060.66

**Comment by devaskim** [comment]
I didn't hear what there are any limits to number of assigned customers.

**Comment by Orion4048** [comment]
Technically you can, but customers are being added in one field with json format like this:

[{"customerId":{"entityType":"CUSTOMER","id":"cc8ff620-e658-11ec-8bb1-7f06850a62ef"},"title":"Adam","public":false},{"customerId":{"entityType":"CUSTOMER","id":"6ad181e0-e00b-11ec-b7b9-ef840862eb43"},"title":"Public","public":true}]

I don't know, if too many customers were added to this field, performance might be effected as well. Didn't test it though. This field's character limit is 1000000. But if this is the only way to share the same dashboard, then it is ok for me.

Thanks.

**Comment by wifff** [comment]
Hi Orion4048,
I have a quite similar problem to solve. A "one-page" dashboard for each customer accessible via browser and mobile.
I would like to switch off the navigation options and standard menus (shown in the sidebar) except the logout button.
I am using the CE of Thingsboard.

Best regards and many thanks 
Wolfgang

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
