### ISSUE TITLE
thingsboard   local installation   Pushing data using MQTT ,  Observe device none data on the Web UI （include  attributes， telemetry data）。

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#688]
thingsboard   local installation   Pushing data using MQTT in windows ,    Observe device none data on the Web UI （include  attributes， telemetry data）。

https://thingsboard.io/docs/getting-started-guides/helloworld/

mqtt-js.bat :
@echo off

REM Set ThingsBoard host to "demo.thingsboard.io" or "localhost"
set THINGSBOARD_HOST=localhost 

REM Replace YOUR_ACCESS_TOKEN with one from Device credentials window.
set ACCESS_TOKEN=FjZ7DaylgMSqCL4MSNBE

REM Read serial number and firmware version attributes
set /p ATTRIBUTES=<attributes-data.json

REM Read timeseries data as an object without timestamp (server-side timestamp will be used)
set /p TELEMETRY=<telemetry-data.json

REM publish attributes and telemetry data via mqtt client
node publish.js

**Comment by Ultrazombie** [comment]
I'm closing this ticket because you have the same - #692
