### ISSUE TITLE
Legend of flot graph widget overflows (Adds horizontal scrollbar)[Bug] 

### ISSUE THREAD

**Issue by JimmyPedersen** [thingsboard/thingsboard#6881]
**Describe the bug**
When adding one of the default flot widgets (line graph in this case) to the dashboard (size 8x6) and enabling the legend I get an ugly (overflow) scrollbar on the bottom of the legend area. See image. Tested in Chrome, Edge and Opera, all displays the same issue

** Server Environment**
* own setup
  * cloud
  * 3.3.4.1PE
  * OS Name and Version

**Client Environment**
* OS: Windows 10
* Browser: Chrome
* Version  103.0.5060.66

**To Reproduce**
1. Add Flot graph widget (line graph in this case)
2. Add datasource
3. Enable Legend
4. Save

**Expected behavior**
No overflow scrollbar, at least not until the widget is very small

**Screenshots**
![image](https://user-images.githubusercontent.com/95076607/177328041-dbe2553c-3262-441a-aae0-ef70bbc8390a.png)

**Comment by vvlladd28** [comment]
Hi @JimmyPedersen,
This issue will be fixed in TB 3.4 (Fix added to branch [develop/3.4](https://github.com/thingsboard/thingsboard/tree/develop/3.4)  https://github.com/thingsboard/thingsboard/commit/c7e75eb5b848ec7e7e90a4e5a288723c11106bdd)
