### ISSUE TITLE
[Question] multiple sensors connected by one of them.

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6884]
**Component**

 * Rule Engine

**Description**
Hi, 
I have sensors that use one of them to transmit the information of all of them. 
The message for 6 sensors looks like:
```
{
    "deviceName": "4ecf3f7f4b51",
    "deviceType": "beacon",
    "attributes": {
        "model": "beacon",
        "serialNumber": "4ecf3f7f4b51",
        "devmac": ["4ecf3f7f4b51", "5a57ff7ef16","2ecf3f7f4b51", "06a57ff7ef16", "3ecf3f7f4b51", "6a57ff7ef16"],
    },
    "telemetry": {
        "dist": [502, 120, -2, -2, 90, 140],
        "charg": [3220, 3350, -2, -2, 3600, 3280],
        "instruction": 0
    }
}
```
I have an array with the mac adresses (devmac) and two arrays with values (dist and charg).
I wonder what is the best way to transmit the telemetry to the 6 sensors concerned in thingsboard.
Thanks for your answers,

Christophe

**Environment**

 * ThingsBoard: PE Cloud

**Comment by devaskim** [comment]
We are using for this purpose [Mqtt Gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/). In this way your "master" device could send at the same time both its own telemetry and telemetry of each of "slave" devices as if these devices send data by its own.

**Comment by liotys** [comment]
Tanks @devaskim , it's not easy for me to use Mqtt while my sensors communicate with Sigfox...
I prefer to stay in thinksboard.
Finally I used the rules chain with the following elements:
- Create a relation to the slaves
- Dupplicate to related to send one telemetry by slave
It works pretty fine...
