### ISSUE TITLE
[Feature Request] We should be able to post telemetry from the scheduler

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6887]
**Is your feature request related to a problem? Please describe.**
The only way to periodically post telemetry imitating a device is by having a generator node every minute, and right after that node using a script node where you grab time of day, and if time of day is when you want to post telemetry, then you can go ahead and execute other logic in your rule

**Describe the solution you'd like**
Use a generator node in the scheduler to post telemetry

**Describe alternatives you've considered**
Using a generator node in the rule chain that runs every 5 mins, compares timestamps and when the timestamp matches the hour I want to run, I run the script.

**Additional context**

**Comment by liotys** [comment]
Hi,
may be you could use the scheduler to update an attribute of the device. Then you could use a rule chain to track this value and then use a REST API Call Node to send the telemetry to this device.
I guess you could use this attribute as a json that contains the telemetry you want to send...

**Comment by OzyOzk** [comment]
> Hi, may be you could use the scheduler to update an attribute of the device. Then you could use a rule chain to track this value and then use a REST API Call Node to send the telemetry to this device. I guess you could use this attribute as a json that contains the telemetry you want to send...

I already have a working solution, but I think allowing generator nodes in the scheduler is more intuitive.

**Comment by mykhailokornieiev** [comment]
Hi. I'm not sure for how long this is possible, but you can make custom event type for scheduler with Post Telemetry message type.
![image](https://github.com/user-attachments/assets/aaad5574-c636-4e7b-a38e-5f1fac24f8f8)

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
