### ISSUE TITLE
rpc call response changed between 3.1.0 and 3.3.4.1

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6890]
**Component**

 * Generic

**Description**
the way that deal with rpc call is different between 3.1.0 and 3.3.4.1,in 3.1.0 it won't return util device response is returned,but in 3.3.4.1,it will return immediatly without waiting for device reponse,only return rpcId,actually you can query rpc response from database,but i'am wondering why would be designed like this in 3.3.4.1?

**Comment by vvlladd28** [comment]
Hi @john1337,
To return the previous behavior of RPC commands, use the **persistent** parameter set to **false**. This was given for sending commands to active devices once every sub-hour or hour.
