### ISSUE TITLE
[Feature Request] Choose the name of the related entity of "change originator"  node

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6896]
**Is your feature request related to a problem? Please describe.**
I want to change the originator of a message and I know the name of the entity considered. The "change originator" node with related option choose the first related entity it finds and discards the other, so it's a lottery to find the one that interests me...

**Describe the solution you'd like**
I would like a field to specify the name of the entity like this:
![image](https://user-images.githubusercontent.com/103430329/177791997-1beee93b-7809-4951-bfa2-b0a3ee53de2d.png)

**Describe alternatives you've considered**
Currently I use the "duplicate to related" node and send a not empty message for the only related entity I want.

**Comment by devaskim** [comment]
Relation type `Contains` is just a word, so you can create your own relation name, for example, `RelationToDevice1` and use it.
