### ISSUE TITLE
Change default sysadmin password

### ISSUE THREAD

**Issue by PP90** [thingsboard/thingsboard#690]
As written in the description, it is possible to change the sysadmin default password?

Thanks

**Comment by mfalkvidd** [comment]
Yes. Create a bcrypt hash of the password you want (easiest way might be to change the password on an existing installation and grab the hash from the database). Replace the hash at https://github.com/thingsboard/thingsboard/blob/8a28cd703fa63f9dbd12464088e6d25593e5aa86/dao/src/main/resources/sql/system-data.sql#L24 with the new hash.
