### ISSUE TITLE
[Question] How to get device (connected, disconnected) logs.

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#6902]
**Component**
 * UI
 * Rule Engine
 * Generic

**Description**
How to get device (connected, disconnected) logs.

**Environment**
 * OS:  SentOS 8
 * ThingsBoard: 3.3.4.1 pe
 * Browser: Chrome

**Comment by devaskim** [comment]
As I know, out of the box you can get current connectivity status of device from value of server-side attribute called `active` or subscribe to its changes.

**Comment by ashaforost** [comment]
You can also try changing the state.persistToTelemetry thingsboard.yml parameter to true. This will allow you to have a record of device state changes in the device's telemetry.
