### ISSUE TITLE
Dashboard moves/shakes continuously

### ISSUE THREAD

**Issue by cerbica** [thingsboard/thingsboard#691]
Hi,
On some browsers my dashboard trembles continuously
as if it was not able to find the correct widgets dimension/position.

How can I resolve?
I have to perform a demo of my dashboard and this problem is blocking me.

Many thanks
Sarah

**Comment by MarsWarrior** [comment]
Are you running 1.4? Afaik this was solved in 1.4.

Otherwise it might be temporarely fixed by slightly resizing your browser window.

**Comment by DIYGuy01** [comment]
the same since pre 1.4 and 1.4. Firefox/Chrome shaking in case of maximized browser. Screen resolution 1920x1080.

**Comment by luPhz** [comment]
I get the same flickering dashboard with thingsboard 2.3 and firefox. It seems to work without issues in chrome.
The dashboard grid seems to get trapped in a loop:

1. Yeah there is some space available
2. Resize the dashboard grid (grow it)
3. Firefox adds scrollbars
4. Oh there is no space available
5. Resize the dashboard grid (shrink it)
6. Firefox removes the scrollbars
7. Start over at 1.

Apart from the aestetic issues the resize loop seems to force some widgets (e.g. map-widgets) to reload their content which results in unneccessary requests.

Another workaround is to zoom in or out with [CTRL]+[+/-]

**Comment by xmas3** [comment]
Same issue, very annoying ...

**Comment by corra71** [comment]
Same issue, TB 2.4.3 PE using Chrome on Mac
It seems that the problem appears only with a specific dashboard size

**Comment by Karabiy** [comment]
do those persists for the 3.0+ version on the side of yours?

**Comment by luPhz** [comment]
Hello Vladislav,

I have not tried out the 3.0 version yet, sorry.
I'll surely do in the next weeks.

However, to the best of my knowledge, I haven't this issue for the last year or so.

Greetings from Magdeburg/Germany :)
Henning
