### ISSUE TITLE
[Question] Add a new system admin account

### ISSUE THREAD

**Issue by LiamBurgess18015001** [thingsboard/thingsboard#6911]
**Component**
 * Generic

**Description**
How does one make a new system admin account for thingsboard community edition?

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: version 3.3.4.1
 * Browser: Firefox v102

**Comment by devaskim** [comment]
Try [saveUser](https://demo.thingsboard.io/swagger-ui/#/user-controller/saveUserUsingPOST) REST endpoint.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
