### ISSUE TITLE
[Bug] Cannot call function from <a> link defined in map marker popup

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#6912]
**Describe the bug**
I cannot make call working from an <a> link set as popup content of a map marker (custom widget).

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version 3.2.0 PE
  * Ubuntu

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Firefox
* Version 99

**To Reproduce**
1. Create a custom map widget (I exported open)
2. Edit onInit function:

```
    self.ctx.$scope.hello = function() {
        console.log('hello');
    }
                var myIcon = L.icon({
                    iconSize: [20, 34],
                    iconAnchor: [10, 35],
                    popupAnchor: [0, -34],
                    tooltipAnchor: [0, -24]
                });
                
                var marker = L.marker([parsed[0].lat, parsed[0].lon], {title: self.ctx.data[i].datasource.name, icon: myIcon});
                marker.addTo(self.ctx.map.map.map);
                
                marker.bindPopup("<b>test</b><br/><br/><a href=\"javascript:void(0);\" onclick=\"hello()\" class=\"tb-custom-action\" data-action-name=\"test\">test</a><br/>");
```

4. Test the new map widget with a action "test".
5. When clicking on the link the web console indicates that function hello is undefined.

**Expected behavior**
When clicking on the link in the popup the function hello should be called.

**Additional context**
Trying do make a custom map widget (with different leaflet components), this is the last blocking point. The popup content cannot call any function of the widget. I also tried ng-click and '(click)' without success.

**Comment by devaskim** [comment]
It is not an answer but how about [Tooltip action](https://thingsboard.io/docs/user-guide/ui/widget-actions/#3-tooltip-tag-action)?

**Comment by bbrenne** [comment]
That's what I use, the problem is that if the tooltip is manually generated the links will not work (I guess the links are connected in a previous "rendering" phase).

I found a work around, I connect the links myself:
```
self.ctx.map.map.map.on('popupopen', function(e) {
        var nodeList = document.querySelectorAll("a.tb-custom-action");
        
        for (var i = 0; i < nodeList.length; i++) {
            const node = nodeList[i];
            
            node.addEventListener("click", function($event) {
                    ...
                    var descriptors = self.ctx.actionsApi.getActionDescriptors('tooltipAction');
                    
                    for(var descriptor of descriptors) {
                        if(descriptor.name === ....) {
                            self.ctx.actionsApi.handleWidgetAction($event, descriptor, entityId, name);
                        }
                    }
                }
            });
        }
    });
```
