### ISSUE TITLE
The locally installed THINGSBOARD cannot get telemetry data.

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#692]
Hello!

I installed the THINGSBOARD on Windows 7 and installed the MQTT client on the PC to push data from local to my ThingsBoard instance using MQTT.

https://thingsboard.io/docs/getting-started-guides/helloworld/

I did the tutorial exactly as shown in the above link, but the THINGSBOARD was never able to get telemetry data. However pushing data from local to  Live Demo server using MQTT has been succeed by the same way。

I don't know what's wrong, or which steps are missing, I hope to get your help soon.
Some screenshots are attached.

Thanks,
Best Regards,

![2018-03-30_155020](https://user-images.githubusercontent.com/30205233/38133359-68262682-3441-11e8-8571-604ea4792a06.png)
![2018-03-30_155211](https://user-images.githubusercontent.com/30205233/38133365-7151fc18-3441-11e8-91a6-fe11a85617a4.png)
![2018-03-30_155247](https://user-images.githubusercontent.com/30205233/38133372-7d2cdb84-3441-11e8-9a57-021522f4e242.png)
![2018-03-30_155721](https://user-images.githubusercontent.com/30205233/38133379-85f04b8e-3441-11e8-9a11-b32c3714b505.png)
![2018-03-30_155350](https://user-images.githubusercontent.com/30205233/38133389-98004ed2-3441-11e8-88b6-6cd225ca0533.png)
![2018-03-30_155402](https://user-images.githubusercontent.com/30205233/38133401-a0f5fd84-3441-11e8-874e-c4d9df3decbb.png)
![2018-03-30_162226](https://user-images.githubusercontent.com/30205233/38133404-a4aceca8-3441-11e8-859e-f215fb0e22ba.png)

**Comment by Ultrazombie** [comment]
Hello @BIT-masterpy 
Is your problem still relevant on the latest ThingsBoard version?
