### ISSUE TITLE
[Feature Request] Support for i18n (language) in chart axis title

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#6944]
**Is your feature request related to a problem? Please describe.**
In charts, when defining an axis title (Datakey configuration --> Advanced --> Axis title), the {i18n:key} notation is not processed.

**Describe the solution you'd like**
Being able to use i18n in chart axis titles.

**Comment by mykhailokornieiev** [comment]
Hi. I was able to make it work on the latest version.
![image](https://github.com/user-attachments/assets/c086adb7-46d5-4bea-a09a-983efba3ef1f)
`{i18n:custom.my-widget.axis}`
![image](https://github.com/user-attachments/assets/d4592c5d-2352-454a-842e-80bfce2926e1)

**Comment by mykhailokornieiev** [comment]
So, in this case, this feature implemented at least on the latest version. I close this ticket
