### ISSUE TITLE
ERROR : unconfigured table audit_log_by_tenant_id_partitions

### ISSUE THREAD

**Issue by azrin1972** [thingsboard/thingsboard#695]
I have installed a compiled version of 1.4.0 snapshot (a month ago) and today I've updated my source to latest master - 1.4.1 snapshot with Audit.

Now I cannot do add/remove users or update the dashboard as will get this error

```unconfigured table audit_log_by_tenant_id_partitions```

**Comment by vparomskiy** [comment]
You need to update DB schema because new tables/views were added in 1.4.1

**Comment by azrin1972** [comment]
How do I update the schema? I try to use the update.sh -fromVersion 1.4.0 but it said not supported version

Sincerely 
Azrin
