### ISSUE TITLE
How to set the format of mat-date-range-picker in custom widget

### ISSUE THREAD

**Issue by zjun615** [thingsboard/thingsboard#6958]
**Component**

 * UI

**Description**
I used the mat-date-range-picker  from https://material.angular.io/components/datepicker/overview.
HTML:
```html
<mat-form-field appearance="fill" style="width: 100%;">
  <mat-label>Please input peroid</mat-label>
  <mat-date-range-input id="dateRange" 
    [rangePicker]="picker">
    <input matStartDate id="startTimeInput" #dateRangeStart placeholder="start date">
    <input matEndDate #dateRangeEnd (dateChange)="dateRangeChange(dateRangeStart, dateRangeEnd)" placeholder="end date">
  </mat-date-range-input>
  <mat-hint>DD/MM/YYYY – DD/MM/YYYY</mat-hint>
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-date-range-picker #picker ></mat-date-range-picker>
</mat-form-field>
```
When I pick the date range, the both input will display the format of "DD/MM/YYYY", eg: 01/07/2022 - 18/07/2022.
I try to format the date to "YYYY-MM-DD" with every way found by google, but I failed.
Can someone help me?
Regards.

**Environment**

 * OS:   Mac
 * ThingsBoard: v3.3.4.1
 * Browser: Safari | Chrome

**Comment by devaskim** [comment]
Try this
```javascript
self.onInit = function() {
    self.ctx.$scope.dateFormat = 'YYYY/MM/DD';
}
```
```html
<mat-hint>{{dateFormat }}</mat-hint>
```

**Comment by zjun615** [comment]
@devaskim I try it, but not work. `<mat-hint>` is a hint below the input, not the format of date

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

**Comment by icoco** [comment]
> @devaskim I try it, but not work. `<mat-hint>` is a hint below the input, not the format of date

solved ? looks it not work , the tag was used conflict seem
