### ISSUE TITLE
Unable to open thingsboard account on thingsboard PE cloud

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#6974]
I tried updating my free trail thingsboard PE cloud account. After giving card details, the process was interrupted by an error.
Now when I try to login my account it is showing the following error
GET: /api/billing/tenant/customer
404: OK
and I am unable to login.
Please help me

**Comment by ban2derlog** [comment]
Hello,
Do you can log in from Private\Incognito window or different browser?
Also do you try to login again after some time?
