### ISSUE TITLE
How do I develop access to support TCP protocol? 

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#698]
How do I develop access to support TCP protocol? I don't seem to support this protocol at the moment.

**Comment by vparomskiy** [comment]
You will need to create a custom plugin. As a starting point, you can take a look at Time Plugin - https://thingsboard.io/docs/reference/plugins/time/

Also, as a reference please take a look at MQTT plugin ->
org.thingsboard.server.extensions.mqtt.plugin.MqttPlugin

**Comment by vparomskiy** [comment]
Not actual anymore because new transport microservices where introduced in Thingsboard 2.2. specific TCP transport microservice can be implemented. Closing
