### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by qiangwanfu** [thingsboard/thingsboard#6981]
http 发送命令 增加了设备状态监测，那怎么往云端发送命令边缘接收命令呢？   往云端发命令  边缘 订阅了根本收到命令？订阅边缘mqtt  
  ,云端的设备没有连接、订阅 会提示设备不在线。发不了。

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
Please make a new ticket in English - if the problem still exist.
