### ISSUE TITLE
Resolve variables in widget titles

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#699]
When I use a variable like ${entityName} in the title of a dashboard widget, it is not resolved.  It would be very helpful if it was.  Alternatively, if there were a different way to get the name of the device into the title, that would probably solve my problem.  Observed in 1.4:

![image](https://user-images.githubusercontent.com/1133323/38188812-660ea6f8-3612-11e8-9125-4f6e1a068a6e.png)

**Comment by jondoig** [comment]
This assumes a chart displays a single entity, but it can show multiple entities.

**Comment by marianodo** [comment]
Could resolve entityName on a title from a widget? I need it too

**Comment by GrayCygnus** [comment]
Any news on this guys? I'm struggling with this too, was contemplating making a custom Widget but I believe this should be more straightforward than having to go and make a custom widget

**Comment by LeoMorgan113** [comment]
Hi,

Unfortunately, we have this feature in our backlog(PROD-176) but haven't implemented it yet. 
Hope it will be done in future releases.
Keep updated!
https://thingsboard.io/docs/reference/releases/

**Comment by mfalkvidd** [comment]
Any update on the position of PROD-176 in the backlog?

**Comment by h-takado** [comment]
I too faced this problem.
It is backlogged in 2018 but not implemented even in 2023?
