### ISSUE TITLE
[Question] version control setup issues with github / bitbucket

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#6990]
Hello

I am getting the following error trying to add bitbucket or github using SSH authentication:

`Authentication is required but no CredentialsProvider has been registered`

also having issues getting it to work with user/pass

can you please add instructions [to the guide](https://thingsboard.io/docs/user-guide/version-control/#git-settings-configuration) on how to setup access for thingsboard in github/bitbucket ?

@ashvayka

**Comment by Backdraft007** [comment]
Do you get any error messages? What says the thingsboard.log?

**Comment by zuyan9** [comment]
Are you sure you are using the SSH URL instead of the HTTPS URL? For example, we should use `git@github.com:zuyan9/zuyan9.git`, not `https://github.com/zuyan9/zuyan9.git`.

**Comment by Backdraft007** [comment]
With HTTPS URL works for me fine.

**Comment by zuyan9** [comment]
@Backdraft007 using a private key file, SSH URL is working fine for me, but with HTTPS URL I'm also getting `Authentication is required but no CredentialsProvider has been registered`.

**Comment by t0mZ4** [comment]
you guys are correct, must use the ssh url when using ssh key for auth.

but bitbucket is crap, ssh access keys are read-only, so i switched to github.
