### ISSUE TITLE
[Question] How to use Dashboard tooltip function with if statement?

### ISSUE THREAD

**Issue by peterandthejetsons** [thingsboard/thingsboard#6993]
**Component**
 * UI

**Description**
I'm using latest (3.4) version from TB Comminity Edition. I have some Devices with different Device Profile and some Dashboards to visualize Timeseries from these Devices. As Dashboard Datasource I have two Devices with different Timeseries. I'd like to use Image Map's Tooltip function with If statement. 

Example: I have Device1 with DeviceProfile1 and Device2 with DeviceProfile2. I like to visualize Device1's Timeseries if DeviceType == "DeviceProfile1".

I'm using the following Tooltip script:

```
var deviceType = dsData[dsIndex]['Type'];
if (typeof deviceType !== undefined) {
if (deviceType == "DeviceProfile1") {
return '{energy:2} kWt';
} 

else if (deviceType == "DeviceProfile2") {
return '{temperature:2} °C';
}
}

```

But the same thing happens in all cases. If its manage to display the desired key, it will be displayed on all devices, not only on those for which the condition applies. If its failed to display the desired keys, then nothing is displayed in the text bubble. I'd like to get your help in this issue. If you need more information about the error, please let me know.

Thanks in advance.

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.4
 * Browser: Mozilla 102.0.1

**Comment by devaskim** [comment]
Use _console.log()_ to debug and look at output in browser DevTools in Console tab:
```
console.log('Data: ', dsData[dsIndex])
```

**Comment by peterandthejetsons** [comment]
Dear devaskim!

Sorry for my late answer, i tried your suggestion and its working now. Thank you for your help.

Best regards,
Peter
