### ISSUE TITLE
[Question] Error "please contact system administrator" with uplink integration

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#6995]
**Component**

 * Generic

**Description**
![image](https://user-images.githubusercontent.com/103430329/181061521-1bf93197-d13e-471f-9d7b-c5f484767356.png)

Hello, I have an error with my Sigfox integration when I receive a callback. The Error message is "please contact system administrator". Nevertheless the callback message is processed correctly, but Sigfox receive an error and send me the same message 4 times...
What that this error message means? How to correct it?
Thanks a lot for your answers,

Christophe

**Environment**

 * OS:  ubuntu 20.04 LTS
 * ThingsBoard: 3.4.0 PE

**Comment by zuyan9** [comment]
I think you might be hitting the device number quota

**Comment by liotys** [comment]
> I think you might be hitting the device number quota

@zuyan9 , my licence is a perpetual unlimited 🙂.

**Comment by liotys** [comment]
the answer is in the log file of the server:
2022-07-26 12:49:02,479 [DbCallbackExecutorService-18-34] WARN  o.t.i.api.util.ExceptionUtil - [6eb0f340-0c2f-11ed-9e8b-077eec124d89] Unknown error during message processing
java.lang.RuntimeException: Incoming message should contain either 'device' or 'Device' field!

It's mandatory to avec a field device or Device in the message. I called it assetName...
