### ISSUE TITLE
[Bug] Version Control - Can't create version when the entity json is too big

### ISSUE THREAD

**Issue by zuyan9** [thingsboard/thingsboard#6996]
**Describe the bug**
I've been trying out the new version control feature with the release of ThingsBoard v3.4.0PE, and I really like it so far. However, I did encounter a bug where if I want to create a version of something, it will not succeed if the entity is too big. Instead, I get the error message:

> One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: ba41c3a5-8cb0-5ca9-ba8b-98ff56ad1259)

![image](https://user-images.githubusercontent.com/7322443/181176262-02027b26-37c4-4698-961a-c0e84cc5a60a.png)

**Server Environment**
* Setup at an Ubuntu server
  * Cloud deployment on an EC2 instance on AWS
  * ThingsBoard Version: 3.4.0PE
  * Ubuntu 20.04.4 LTS

**Client Environment**
**Desktop**
* OS: Windows 11
* Browser: Chrome
* Version: 103.0.5060.134

**To Reproduce**
1. Download this zip file which contains an example dashboard: [example_dashboard.zip](https://github.com/thingsboard/thingsboard/files/9195576/example_dashboard.zip)
2. Extract the file, get the json file
3. Import the json file to an ThingsBoard instance as a dashbaord
4. Try "Create version" in the version control menu of this dashboard
5. See error

**Expected behavior**
A version should be created.

**Screenshots**
Error message when trying to create a version in version control
![image](https://user-images.githubusercontent.com/7322443/181176009-df9cd30b-e315-4386-b856-4a7dae1fa825.png)

**Comment by ashvayka** [comment]
Hi @zuyan9 , please use the environment variable  TB_QUEUE_VC_MSG_CHUNK_SIZE to configure the size of the chunks that are used for communication between the tb-core and tb-version-control services (even if you are running in monolith, I see you are using AWS SQS as a message queue)
