### ISSUE TITLE
[Question] How to divide certain datakeys from [ctx]="ctx" into different angular tabs

### ISSUE THREAD

**Issue by X1folta** [thingsboard/thingsboard#6997]
**Widget**

Update multiple attributes

<tb-multiple-input-widget 
    [ctx]="ctx">
</tb-multiple-input-widget>

 * UI

**Description**
 
Having many attributes in one datasource to update I'd love to have them sorted in angular tabs 

```
<mat-tab-group>
        <mat-tab label=" First three attributes">
        </mat-tab>
        <mat-tab label="Next three attributes">
        </mat-tab>
        ""and so on...""
</mat-tab-group> 
```

like so, but I have not yet discovered any way how to access the datakeys present in the html/angular link 

```
<tb-multiple-input-widget 
    [ctx]="ctx">
</tb-multiple-input-widget>

```

I'd appreciate it a lot if someone has found a solution to this or a way to make this work.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
