### ISSUE TITLE
REST API Call Plugin possibility to set HTTP header values

### ISSUE THREAD

**Issue by setevik00** [thingsboard/thingsboard#70]
When I create my own REST API Call Plugin to 3rd party services, I want to set custom HTTP header values.
For instance, I faced a problem that there is no way to set "Content-Type" : "application/json" for my REST API call originating from Thingsboard to 3rd party services.
Without correct HTTP headers my REST calls fail to 3rd party services and I have to use proxies to add correct headers. That's not a major problem for me, butt would be nice to fix/improve Thingsboard UI.

**Comment by ashvayka** [comment]
@setevik00 This is fixed now!
