### ISSUE TITLE
Interactive SVG file in a Widget

### ISSUE THREAD

**Issue by adamfadil** [thingsboard/thingsboard#700]
First of all, I congratulate the team of thingsboard, the solution is very impressive by its generality.
I would like to know in a first time, how I can upload interactive SVG files (with Html object data = "example.svg"  type = "image / svg + xml"> </ object>, this gives no result) .
) and in a second time, to have the possibility to control it with the functions of the type of widget (control and latest values).

**Comment by Karabiy** [comment]
for the reasons of yours, you can proceed with the custom widget development. you can refer to this link regarding on how to develop the custom widget: https://thingsboard.io/docs/user-guide/contribution/widgets-development/
