### ISSUE TITLE
How to create a end user from  "Water Metering Tenant Dashboard"?

### ISSUE THREAD

**Issue by sebastianmenoni** [thingsboard/thingsboard#7007]
TB version 3.4 includes the template: Water metering

Which in the instructions section indicates:

....You may create more Customers and more Users via "Water Metering Tenant Dashboard".

However, the dashboard does not specify any section to create end users.

They can only be created to create customers

 * OS:  Ubuntu
 * ThingsBoard PE: 3.4
 * Browser: Chrome

**Comment by mde2017** [comment]
Hi @sebastianmenoni 

Go to Customers page and click on the '+' symbol (it's implemented via Custom Widget Action):

![image](https://user-images.githubusercontent.com/25298332/181432223-29db8258-aa71-474a-bec8-4d45c6166169.png)

![image](https://user-images.githubusercontent.com/25298332/181432317-dd814076-c978-497c-ae91-1bf88729b416.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
