### ISSUE TITLE
Markers on map should forwarding to a different dashboard 

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard#7013]
Hello,
I have added a Map-Widget with multiple markers on it. The idea was to make that markers clickable, so the dashboard of the marker opens. 
I made an action that forwards to the dashboard, but every marker is now linked with the same dashboard. 

Is there a way that every marker forwards to a different dashboard?

**Comment by devaskim** [comment]
What did you mean by different dashboards? Dashboard with different set of widgets or the same dashboard but that shows data regarding marker that a user has clicked?

**Comment by rungg12** [comment]
It wouldn´t matter for me, example: i click on marker 1, it forwards me to dashboard1, if i click on marker 2 on the same map, i want that it forwards me to dashboard2.
But the problem is, that i can only add one action for all the markers, not certain actions for certain markers

**Comment by devaskim** [comment]
It is by design thus by clicking on marker you could trigger, for example, _custom action_. In its handler you could get from somewhere dashboard's id and then open that dashboard [like this](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L1123-L1133).

**Comment by rungg12** [comment]
yeah i know that, but you can only create that custom action once, so every marker is linked with the same dashboard/dashboard-state

**Comment by devaskim** [comment]
It depends on your implementation. Custom action provides access to widget context so you could dynamically resolve dashboard or its state

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
