### ISSUE TITLE
[Question] Filtering in dashboard using dynamic values

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7018]
**Component**

 * UI
 * Generic

**Description**
Hello Thingsboard community. I have a question regarding filters in dashboards. I would like to filter values which are equal to string attribute. This atribute is obviously subject to change, most likely via input widget.
I want to select device which is going to be displayed on image map widget (via input string widget of mac).
ShowBLE is server attribute belonging to customer, where the mac value is stored. So I created filter:
![image](https://user-images.githubusercontent.com/58517178/181762711-766da951-0a8f-431b-82cd-7814e89e3cfa.png)
This filter is not working properly so my question is how to get it right. I have assigned this dashboard to Customer A (predefined) and made this customer default. I applied filter to image map widget but it is not working - it is displaying all devices. Any tips?

**Environment**

 * OS:  Win 10
 * ThingsBoard: latest community version
 * Browser: Edge

**Comment by serfreeman1337** [comment]
Does filter work under "Customer A" account ?

**Comment by devaskim** [comment]
Re-check the value of `ShowBLE` attribute, perhaps it is different from `mac` values.

**Comment by samokomo** [comment]
I will have to do some work on relations of Customer A, but I would prefer to see results of this filter as Tenant Admin. 

ShowBLE is server attribute of type string 
![image](https://user-images.githubusercontent.com/58517178/182129169-dd8c26d7-db14-40f5-ae09-757612e1c7a3.png)
This attribute is editable via input widget placed in dashboard. Input widget is working fine. Even tho, filter shloud show none of the devices or just the device with correct mac attribute, but currently it shows all the devices.

**Comment by devaskim** [comment]
_Current customer_ in filter means customer of user who is being logged in at the moment. For Tenant admin it is non-sense

**Comment by samokomo** [comment]
I understand, the question is how to configure this in Community Edition than?
![image](https://user-images.githubusercontent.com/58517178/182140188-0ab34420-1fce-48bd-8774-a8ba34b1b2ca.png)

**Comment by serfreeman1337** [comment]
You can use "Current user" to make filter work for both tenant and customer accounts.

**Comment by samokomo** [comment]
Thanks for help. I am using current user option and it works. I will tell my systen administrator to create tenant attribute for this use case and switch to that later.
