### ISSUE TITLE
[Question] How to insert timeseries data into rest call api in rulechain

### ISSUE THREAD

**Issue by Cmonkz** [thingsboard/thingsboard#7021]
So I have these data and what I want to do is insert these into post rest call api
![image](https://user-images.githubusercontent.com/110072081/182100562-c4663801-b882-4eba-8896-d780e952dd26.png)

Question How do I do it? I can insert / update it without a problem if I use the rest api
![image](https://user-images.githubusercontent.com/110072081/182100893-cee0c1d5-26ab-49de-85d5-e7a18d28ad23.png)

But in the Rule chain I always get this error
![image](https://user-images.githubusercontent.com/110072081/182101136-8eb14b9d-1125-42dd-8403-486c77bed09e.png)

Hope someone can help.

**Client Environment**
OS: Windows
Browser: Chrome
TB version 3.3.4

**Comment by ashaforost** [comment]
Hi @Cmonkz ,

Try changing the url parameter 'scope' to 'ANY', instead of 'telemetry'.
Per the thingsboard API documentation, "SCOPE Value is deprecated, reserved for backward compatibility and not used in the API call implementation. Specify any scope for compatibility"

Here's the example:
http://localhost:8081/api/plugins/telemetry/DEVICE/<DEVICE_ID>/timeseries/ANY?scope=ANY

**Comment by Cmonkz** [comment]
> Hi @Cmonkz ,
> 
> Try changing the url parameter 'scope' to 'ANY', instead of 'telemetry'. Per the thingsboard API documentation, "SCOPE Value is deprecated, reserved for backward compatibility and not used in the API call implementation. Specify any scope for compatibility"
> 
> Here's the example: http://localhost:8081/api/plugins/telemetry/DEVICE/<DEVICE_ID>/timeseries/ANY?scope=ANY

Hi @ashaforost , 
Sorry for the late reply, I was away.
Can I ask how am I supposed to add request body into rest call api (post) in rule chain? 
![image](https://user-images.githubusercontent.com/110072081/184269317-38c70260-b615-45c7-a11a-51b4b2f59ac0.png)

**Comment by ashaforost** [comment]
rest api call rule node takes a msg object from the incoming message and sends it in a post request as a request body. So, before the rest API call rule node you have to compose a msg object with the request body content using, for example, a transformation script rule node.

**Comment by Cmonkz** [comment]
Got it thanks. Figured it out after doing a auto token generator. didn't know that using script is equal to request body hehe.
