### ISSUE TITLE
[Question] How to build 'thingsboard-rule-config-ui-ngx'

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7027]
I know that to run production build one need `yarn build`. The size of resulting artifact is 
```bash
User@DESKTOP-6236L21 MINGW64 ~/code/thingsboard-rule-config-ui-ngx (master)
$ ls -lh target/generated-resources/public/static/rulenode/rulenode-core-config.js
-rw-r--r-- 1 User 197121 1,6M авг  2 22:46 target/generated-resources/public/static/rulenode/rulenode-core-config.js
```
but the size of the same file in main repo is
```bash
User@DESKTOP-6236L21 MINGW64 ~/code/thingsboard (3.4)
$ ls -lh rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
-rw-r--r-- 1 User 197121 430K авг  2 15:46 rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
```
When I replace original _rulenode-core-config.js_ with built from source and build and ran Docker image of TB server no configuration page of Rule Engine node opened and browser console display following errors:

![rule-node-ui-bug2](https://user-images.githubusercontent.com/86909129/182442399-a6d1d65f-1b67-4572-9ca1-d9914f38f9d4.jpg)
![rule-node-ui-bug](https://user-images.githubusercontent.com/86909129/182442409-d0a0f818-80ff-4224-aadd-4a0008878b5b.jpg)

**Comment by shiyuecamus** [comment]
I have the same problem as you. Have you solved it？

**Comment by devaskim** [comment]
@shiyuecamus no

**Comment by shiyuecamus** [comment]
It seems that the problem is version compatibility. Try this commit version: b138645b4af8636d446892e7c5611b62fe61a938

**Comment by devaskim** [comment]
Thanks, I will try in a couple of hours. Did you succeed with this commit?

**Comment by shiyuecamus** [comment]
Yes, the problem has been solved

**Comment by devaskim** [comment]
Greate, and the last question I hope) What TB version are you using at the moment with this commit-specific version of *thingsboard-rule-config-ui-ngx*?

**Comment by shiyuecamus** [comment]
TB version: 3.3.4
thingsboard-rule-config-ui-ngx commit version: b138645b4af8636d446892e7c5611b62fe61a938

**Comment by devaskim** [comment]
My version is 3.4.1 now. But indeed you give me the clue. Thanks
P.S.: do your bundle and original one differ greatly in size?
