### ISSUE TITLE
Upgrading to thingsboard/tb-postgres 3.4 docker image broke Material assets 

### ISSUE THREAD

**Issue by securelpb** [thingsboard/thingsboard#7028]
I just finished upgrading my local Thingsboard deployment following the upgrade section in this document https://thingsboard.io/docs/user-guide/install/docker/
The update appeared to work fine, and the system is up and collecting data from my devices. The issue is that the UI appears to be unable to load any icons or fonts. Below is a screenshot of what I'm seeing and the console errors:

`ThingsBoard Version: 3.4.0
MaterialIcons-Regular-570eb83859dc23dd0eec423a49e147fe.woff2:1          Failed to load resource: the server responded with a status of 404 ()
MaterialIcons-Regular-012cf6a10129e2275d79d6adac7f3b02.woff:1          Failed to load resource: the server responded with a status of 404 ()
MaterialIcons-Regular-a37b0c01c0baf1888ca812cc0508f6e2.ttf:1          Failed to load resource: the server responded with a status of 404 ()

The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboards/cfc197e0-f35a-11ec-9e55-3b5c0d06970f:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboards/cfc197e0-f35a-11ec-9e55-3b5c0d06970f:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboards/cfc197e0-f35a-11ec-9e55-3b5c0d06970f:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboards/cfc197e0-f35a-11ec-9e55-3b5c0d06970f:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
dashboards/cfc197e0-f35a-11ec-9e55-3b5c0d06970f:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
home:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
settings/home:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
profile:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
home:1 The resource http://###/assets/fonts/MaterialIcons-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`
![Screen Shot 2022-08-02 at 5 31 50 PM](https://user-images.githubusercontent.com/8284529/182478891-d4c29378-85ef-47d0-8430-50544304b4c3.png)

**Comment by Backdraft007** [comment]
Try to clear your browser cache.

**Comment by securelpb** [comment]
![image](https://user-images.githubusercontent.com/8284529/182604547-9d2b305c-6e1d-4835-97e2-8851f2989a7c.png)
Yup, that did it. Thanks!
