### ISSUE TITLE
Contribution issue with PostgreSQL 

### ISSUE THREAD

**Issue by jackyZhangHZ** [thingsboard/thingsboard#703]
Hi 
we are trying to do contribution on Windows with below environment:
1.OS: Windows 10 64bit
2.Hardware: CPU I7 and 16GB RAM
3.JDK: jdk-8u60-windows-x64 
4.Maven: apache-maven-3.5.2 
5.Thingsboard version : thingsboard-release-1.4
6.SQL: postgresql-10.3-1-windows-x64
7.node-v8.11.1-x64 
8.Git-2.16.1-64-bit

And the contribution steps are blow:
(https://thingsboard.io/docs/user-guide/contribution/how-to-contribute)
1.Install Java and Maven
2.Install node and git 
3.Do npm dependencies
   --npm install -g cross-env 
   --npm install -g webpack
4.Do maven build and finished successfully
  --cd ${TB_WORK_DIR}
  --mvn clean install -DskipTests
5.Install SQL Database: PostgreSQL
  --connect to the database and create thingsboard DB
6.modify the thingsboard.yml and do mvn build again:
   --cd ${TB_WORK_DIR}/application
   --mvn clean install -DskipTests
7.after step 6 successfully and Create Database schema and populate demo
   --cd %TB_WORK_DIR%\application\target\windows
   --install_dev_db.bat
8. step 7 finished successfully
9. then try to Running server-side container from command line

RESULT:
   The log shows:
     1.	Tomcat started on port(s): 8080 (http)
     2. Started ThingsboardServerApplication in 42.224 seconds (JVM running for 43.611)
![issue](https://user-images.githubusercontent.com/22521769/38283105-59844458-37b4-11e8-8913-fcd1c1a9082d.PNG)

BUT when we try to open http://localhost:8080/, it shows blank only

Any insights here is very much appreciated.
Thanks in advance.

Jakcy

**Comment by asnik** [comment]
check for errors whole huge maven building log.

**Comment by jackyZhangHZ** [comment]
thanks asnik , vparomskiy,  
after review the logs and tried to rebuild the UI, the issue is fixed.
