### ISSUE TITLE
Upgrading Thingsboard PE from v3.3.4.1 to v.3.4.0 does not work [Bug] 

### ISSUE THREAD

**Issue by noraneto** [thingsboard/thingsboard#7031]
Upgrade script upgrades to the wrong version from version 3.3.4 to 3.3.4PE instead of 3.4.0
The ~/.mytbpe-data/.upgradeversion is set to 3.3.4
When I execute docker compose run mytbpe upgrade-tb.sh the upgrade starts, but reports upgrading from version 3.3.4 to 3.3.4PE ...  ( not to version 3.4.0)

* own setup
  *  docker deployment
  * v3.3.4.1
  * Ubuntu 22.04
here are the logs:
 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.3.4.1PE)
 ===================================================

Warning: Nashorn engine is planned to be removed from a future JDK release
Starting ThingsBoard Upgrade from version 3.3.4 ...
Upgrading ThingsBoard from version 3.3.4 to 3.3.4PE ...
Updating schema ...
relation "entity_group" already exists, skipping
relation "converter" already exists, skipping
relation "integration" already exists, skipping
relation "scheduler_event" already exists, skipping
relation "blob_entity" already exists, skipping
relation "role" already exists, skipping
relation "group_permission" already exists, skipping
relation "device_group_ota_package" already exists, skipping
Schema updated.
Updating data from version 3.3.4 to 3.3.4PE ...
Updating system data...
Upgrade finished successfully!

**Comment by trikimiki** [comment]
I think you forgot to change the docker image version to 3.4.0, according to this log line:
:: ThingsBoard Professional Edition :: **_(v3.3.4.1PE)_**

It should look like this in your `docker-compose.yml` file (or similar):
`image: "thingsboard/tb-pe:3.4.0PE"`

Do not forget to change `.upgradeversion` again, as it gets reset after every script run.

**Comment by noraneto** [comment]
Thanks!
