### ISSUE TITLE
[Question] How to use java to create a self signed X.509 certificate

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#7032]
**X.509 Certificate Based Authentication**

 * Generic

**Description**
[X.509 Certificate Based Authentication.](https://thingsboard.io/docs/user-guide/certificates/)
According to the instructions in the above link, create X 509 key pair, together with the following instructions, can normally create CA certificate files through OpenSSL, and can successfully connect to thingsboard。

openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes

openssl req -new -key key.pem -out ca.csr
openssl x509 -req -days 365 -in ca.csr -signkey key.pem -out ca.crt

So, how can I create such a similar key pair and CA certificate through Java code ??? 

**Environment**

 * OS:  windows
 * jdk11
 * IDEA

**Comment by ashvayka** [comment]
I am closing this issue because the question is not related to ThingsBoard. This is a general programming question that you may ask on StackOverflow or similar sites.
