### ISSUE TITLE
[Bug] Method ".settingsSchema" removed since 3.4.0

### ISSUE THREAD

**Issue by mgogh** [thingsboard/thingsboard#7033]
**Describe the bug**
Since one year, I develop a lot of "custom widget" using the method ".settingsSchema" (of Map or Flot widget) to add custom **Advanced** parameters for my widgets.
I try to update my PE edition from 3.3.4.1 to 3.4.0 but now all my widgets are not working "

Failed to compile widget script. Error: TbFlot.settingsSchema is not a function

It seems that this method was removed... and replace in "Widget settings" by settings from selector. How can I get this settings schema now ? I try to write it directly but the display are not the same as the new one (may be the react json form has changed also...). Do you have a documentation of the new use of settingsSchema in 3.4.0 ?

Also this link in the documentation (https://thingsboard.io/docs/user-guide/contribution/widgets-development/#settings-schema-section) are not working (http://networknt.github.io/react-schema-form/) I cannot use the official documentation .

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version : PE 3.3.4.1 to 3.4.0

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**Expected behavior**
New alternative to use this method "TbFlot.settingsSchema" which was available until the 3.4.0 or new documentation on how to write React JSON Form.

**Comment by cGlybWlu** [comment]
Are there any updates, solutions or workarounds regarding this issue?

**Comment by prawitdtgo** [comment]
You can custom the widget by following [widgets development](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#static-widget) and the document can't tell you about new feature [#6544](https://github.com/thingsboard/thingsboard/issues/6544) that you can delete default value on "Settings form selector" input.

![image](https://user-images.githubusercontent.com/79242951/195244168-df9a6135-5f2d-42ee-a2d2-fab79db2cec0.png)
