### ISSUE TITLE
Time series Input Widget source code

### ISSUE THREAD

**Issue by sebastianmenoni** [thingsboard/thingsboard#7036]
* UI
 * Generic

I need to be able to enter more than one variable, as well as be able to vary the time step associated with this data point. this through a widget.

My goal is to keep the functionality of the widget
"Update integer timeseries" but with the ability to enter more than one data and be able to change the time stamp.

For which I request the source code of this widget with the intention of modifying it for my requirement.

 * OS:  Ubuntu
 * ThingsBoard: 3.4
![2022-08-03 120548](https://user-images.githubusercontent.com/32903159/182656362-fa13748b-cb7c-4671-9f61-cacb15244f03.png)

**Comment by vvlladd28** [comment]
Hi @sebastianmenoni,
You can see the source code widget in  Widget Library -> Input widgets -> Update string timeseries -> Button (edit widget)
![image](https://user-images.githubusercontent.com/18036670/182828573-2c04c258-f0b7-4eaf-8eea-bc97e930b113.png)
