### ISSUE TITLE
Mobile App - API Endpoint Issue

### ISSUE THREAD

**Issue by andrewvictor5** [thingsboard/thingsboard#7037]
I am trying to publish a copy of the Thingsboard Mobile App to the App Store so that a client can access their dashboards from their phones, but I am having trouble getting the app to reach my API Endpoint. I am currently following the instructions outlined [here](https://thingsboard.io/docs/mobile/getting-started/):

I cloned a copy of the flutter_thingsboard_app into Visual Studio Code, and when I set the API Endpoint to "http://demo.thingsboard.io" (from the documentation) and run the app in debug mode, it works just fine: 
![1618f157-ef9b-4fbc-83fa-84fc525547ab](https://user-images.githubusercontent.com/43546709/182674743-3a62f2d5-2260-47d3-8fb6-d0ef0b1ec092.jpg)

When I set the API Endpoint to my organization's url and run the app in debug mode, it tries to run but gets stuck on this loading screen, never reaching the login screen. (Note: I can access the url just fine using my browser) 
![278f5257-5c22-4933-9709-7b2503a579bf](https://user-images.githubusercontent.com/43546709/182675422-2402b3be-2d14-4e63-a106-14ba63e6449d.jpg)

Is there some sort of step that I am missing? Do I need to configure the app in my Thingsboard dashboard first? Any advice or support would be greatly appreciated.

**Comment by vvlladd28** [comment]
Hi @andrewvictor5,
Can you describe the problem in more detail? What errors are written to the console?  
It is also possible that you miswrote thingsBoardApiEndpoint. Maybe the end variable includes the symbol **/**

**Comment by andrewvictor5** [comment]
Hi @vvlladd28, 
You were right, my API Endpoint was incorrect, I had typed in http: instead of https: 

But now I am having a new issue. I can access my login screen, but when I try to sign in, the app acts like it is signing in, and then immediately reloads the login screen, never actually reaching my dashboard.

Again, when I try to access it from the web, I have no issues. 

Another note: I get an error message if I try to log in with in invalid username/password combo, there is no error message here

The debug log that I get is as follows (with potentially sensitive data ommitted): 
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 authUser: AuthUser{sub: [#################################), scopes: [CUSTOMER_USER], userId: ################################, firstName: ####### lastName: Admin, enabled: true, tenantId: #####################################, customerId: ############################, isPublic: false, authority: CUSTOMER_USER, additionalData: {iss: thingsboard.cloud, iat: ########################, isBillingService: false, privacyPolicyAccepted: true, termsOfUseAccepted: true}
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by andrewvictor5** [comment]
Here is another debug with some actual errors:
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=true
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 authUser: AuthUser{sub: [##################](mailto:#################), scopes: [CUSTOMER_USER], userId: ###################################, firstName: #####, lastName: 4D, enabled: true, tenantId: ###########################, customerId: #############################, isPublic: false, authority: CUSTOMER_USER, additionalData: {iss: thingsboard.cloud, iat: ###############, exp: ################, isBillingService: false, privacyPolicyAccepted: true, termsOfUseAccepted: true}
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   ERROR │ Null check operator used on a null value
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ #0   WlService._updateImages (package:thingsboard_app/utils/services/wl_service.dart:263:76)
flutter:   ERROR │ #1   <asynchronous suspension>
flutter:   ERROR │ #2   WlService._loadUserWhiteLabelingParams (package:thingsboard_app/utils/services/wl_service.dart:220:7)
flutter:   ERROR │ #3   <asynchronous suspension>
flutter:   ERROR │ #4   WlService.updateWhiteLabeling (package:thingsboard_app/utils/services/wl_service.dart:161:7)
flutter:   ERROR │ #5   <asynchronous suspension>
flutter:   ERROR │ #6   TbContext.onUserLoaded (package:thingsboard_app/core/context/tb_context.dart:317:7)
flutter:   ERROR │ #7   <asynchronous suspension>
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ ⛔ Error: Null check operator used on a null value
flutter:   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load started.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   DEBUG │ 🐛 On load finished.
flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by yaoyi601131548** [comment]
Hi @andrewvictor5 , did you resolve the problem?

**Comment by yaoyi601131548** [comment]
Hi @vvlladd28 , i get the same problem, could you please tell me how to fix it ? Thanks.

───────────────────────────────────────────────────────────────────────────────────────────────────I/flutter ( 5027):   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────I/flutter ( 5027):   DEBUG │ 🐛 On load started.I/flutter ( 5027):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/EGL_emulation( 5027): app_time_stats: avg=96.88ms min=2.55ms max=2058.46ms count=31
D/EGL_emulation( 5027): app_time_stats: avg=17.15ms min=2.97ms max=104.46ms count=54I/flutter ( 5027):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────I/flutter ( 5027):   ERROR │ ThingsboardError: message: [HandshakeException: Handshake error in client (OS Error:I/flutter ( 5027):   ERROR │     WRONG_VERSION_NUMBER(tls_record.cc:242))], errorCode: 2, status: nullI/flutter ( 5027):   ERROR │ #0      toThingsboardErrorI/flutter ( 5027):   ERROR │ #1      HttpInterceptor.onErrorI/flutter ( 5027):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>I/flutter ( 5027):   ERROR │ #3      DioMixin.checkIfNeedEnqueueI/flutter ( 5027):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>I/flutter ( 5027):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)I/flutter ( 5027):   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)I/flutter ( 5027):   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)I/flutter ( 5027):   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)I/flutter ( 5027):   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)I/flutter ( 5027):   ERROR │I/flutter ( 5027):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄I/flutter ( 5027):   ERROR │ #0   ThingsboardClient.postI/flutter ( 5027):   ERROR │ #1   <asynchronous suspension>I/flutter ( 5027):   ERROR │ #2   OAuth2Service.getOAuth2ClientsI/flutter ( 5027):   ERROR │ #3   <asynchronous suspension>I/flutter ( 5027):   ERROR │ #4   TbContext.onUserLoadedI/flutter ( 5027):   ERROR │ #5   <asynchronous suspension>I/flutter ( 5027):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄

**Comment by Ultrazombie** [comment]
Closed the ticket because it is obsolete functionality: try the latest version.
Please feel free to open a new ticket if there is a valid issue with the new version of the mobile app in the Flutter app repository
https://github.com/thingsboard/flutter_thingsboard_app/issues
