### ISSUE TITLE
[Question] Updating telemetry data WITH TIMESTAMP from dashboard widget 

### ISSUE THREAD

**Issue by sebastianmenoni** [thingsboard/thingsboard#7038]
Component
 * UI

Description:

my goal is to replicate the functionality of the case:

#4122

but with the option to set the time map manually.

Since when using the method:

"To update telemetry data you could use Update timeseries widgets from Input widgets bundle, also Multiple attributes widget could be used, but for the last one don't forget to select Timeseries data key type in the Advanced data key settings"

The data is recorded with the time map of admission, is there a way to manually establish the time map

Environment

 * OS:  Ubuntu
 * ThingsBoard: 3.4

**Comment by JacksonBowe** [comment]
That's fairly trivial to do through the api, but not sure I'd recommend doing it via dashboard. 

Widget could make api requests to own instance of thingsboard. Would need to do two things
1. Make new telemetry reading with new timestamp
2. Delete old one

You can get the current users access token somehow through the window or widget context. Use access token to validate api, and do a post_telemetry request with the new timestamp:value

**Comment by AxelGeist** [comment]
**Component**
*UI

**Description**
I have the same problem. I try to manually update telemetry data (including manual timestamp) with the Update JSON attribute (from Input Widget bundle). The "values" of the JSON input are saved correctly, though the timestamp will not get updated according to the given "ts" input.

That is the format of my JSON input: 
{
  "ts": 1527863043000,
  "values": {
    "annotation": "Exciter Stop"
  }
} 

Why does the "ts" input not override the default timestamp?


**Environment**
*OS: Windows 10 Enterprise
*Thingsboard: v3.4
*Browser: Google Chrome Version 104.0.5112.79 (64-Bit)

**Comment by mykhailokornieiev** [comment]
Hi. There is standard widget to save telemetry with custom timestamps. You will need to use either custom action or custom widget with URL with query parameters for custom timestamps. Please get familiar with this comment:
https://github.com/thingsboard/thingsboard/issues/11108#issuecomment-2200457412
