### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by yaodadaa** [thingsboard/thingsboard#7039]
**Component**
 * UI

**Description**
I have a problem when I use the hdmi TV to connect the computer to open the thingsboard background in this way,
When I open the page on the computer, the display is normal。When I open it on the TV, some icons on the page can't be displayed. I inspect the element and find that the one that can't be displayed is a span tag，Why is this?
![image](https://user-images.githubusercontent.com/55545124/182774878-b8b967d1-2ce1-4652-83a8-da5205571774.png)
![image](https://user-images.githubusercontent.com/55545124/182774948-80d76cb7-adcf-49ee-ba3f-8d4023f90f11.png)

**Environment**

 * OS:  hdmi connect tv and computer
 * ThingsBoard: version
 * Browser: edge

**Comment by vvlladd28** [comment]
Hi @yaodadaa,
Most likely, your TV didn't support the Unicode symbol [U+2B24](https://www.htmlsymbols.xyz/unicode/U+2B24).
