### ISSUE TITLE
what is the "Thingsboard HOST/IP address " ?

### ISSUE THREAD

**Issue by meushgram** [thingsboard/thingsboard#704]
Hey completely new to thingsboard .  I have installed the Thingsboard Cluster on my linux . While uploading the data **char thingsboardServer[] = "YOUR_THINGSBOARD_HOST_OR_IP"; ** displays . Im not sure which IP address to upload . 
Thanks in advance :)

**Comment by vparomskiy** [comment]
IP address of the instance where Thingsboard installed
