### ISSUE TITLE
[Bug] Not possible to configure Exchange/365 as SMTP Server

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#7040]
**Describe the bug**
It is not possible to configure Exchange/365 as SMTP Server for ThingsBoard 3.3.4.1.
Several settings where tested including different Ports or TLS versions.

This may also be related to the encryption method, since STARTTLS is required.

**Your Server Environment**
* own setup
  * cloud
  * ThingsBoard Version 3.3.4.1
  * Ubuntu

**Expected behavior**
Exchange/365 can be used with ThingsBoard.

**Additional context**

_Server: smtp.office365.com
Port: 587
Encryption: STARTTLS_
https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

**Comment by ban2derlog** [comment]
Hi, please try to use 
`smtp.office365.com:587`
And enable TLS 1.2 as encryption.
This should work

**Comment by mde2017** [comment]
Hi @ban2derlog,

thank for your quick response.
In fact this solved the problem.
