### ISSUE TITLE
[Question] Device Profile Node "Fetch State" and "Persist State" info

### ISSUE THREAD

**Issue by FrancescoMenga** [thingsboard/thingsboard#7043]
* Rule Engine

**Description**
Hi everyone, I am struggling to find any document online on "device profile" node component in rule engine / rule chains. I understood how it works, by automatically checking device alarms and creating/clearing them, but I didn't fully understand what "Persist State" and "Fetch State" options are used for. Recently i noticed some differences when those were applied or not on alarm creation but I don't know the exact effect.
Does anybody have some related articles / documents or info on the usage of this two parameters?
That would be useful for my next project in order to make alarms work properly.

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.2.2
 * Browser: Firefox Latest

**Comment by ashvayka** [comment]
See the doc here: https://thingsboard.io/docs/user-guide/device-profiles/#device-profile-rule-node
