### ISSUE TITLE
[Question] I can login using email/pass on demo.thingsboard.io but failed getting token via cURL

### ISSUE THREAD

**Issue by polaraditia** [thingsboard/thingsboard#7045]
**Component**

 * Generic

**Description**
I can login via UI using email and pass on demo.thingsboard.io, but when I try to get JWT token using http://demo.thingsboard.io/api/auth/login via cuRL, I always get status 401, Authentication failed.

I can get JWT token manually via UI and it works use that token to get telemetry.
But I need to get JWT token programmatically via script, not manually via UI.
![image](https://user-images.githubusercontent.com/5745134/182990000-be02740e-e751-496c-a850-a99c82be3b34.png)

**Environment**
 * OS:  Windows 10
 * ThingsBoard: demo.thingsboard.io
 * Browser: Edge 103

Thank you

**Comment by devaskim** [comment]
```
curl 'https://demo.thingsboard.io/api/auth/login' \
 -H 'content-type: application/json'  \
-d '{  "username": "username",  "password": "password"}'
```

**Comment by polaraditia** [comment]
> This works for me
> 
> ```
> curl 'https://demo.thingsboard.io/api/auth/login' \
> -H 'content-type: application/json'  \
> -d '{  "username": "username",  "password": "password"}'
> ```

it's weird, this works for me too, but if I change and write in js, it still gives me error 401. Did thingsboard really strict with certain style how we write send method?

this code doesn't work for me:
![image](https://user-images.githubusercontent.com/5745134/183238845-4de91ce2-f59d-43ea-b6d4-b0b0869937da.png)
![image](https://user-images.githubusercontent.com/5745134/183238868-1301dfdd-949f-440e-ab77-8f7a0a7351b4.png)

**Comment by devaskim** [comment]
Try _stringify_ your data
```
    data: JSON.stringify(myKeyVals),
```

**Comment by polaraditia** [comment]
> Try _stringify_ your data
> 
> ```
>     data: JSON.stringify(myKeyVals),
> ```

Thank you, finally it works!
