### ISSUE TITLE
[Bug] HTTP post telemetry wrongly convert data type

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#7046]
**Describe the bug**
I am using [HTTP Device API](https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api) to push data into Thingsboard.
One of the data points has value as a string. But somehow it is being auto converted into long.

**Your Server Environment**
Monolith thingsboard 3.3.4

**Expected behavior**
Should retain the datatype of incoming data as-is.

**Screenshots**
![image](https://user-images.githubusercontent.com/58241952/182997957-2035018d-08df-4f95-95b1-f33809e4416b.png)

**Comment by vvlladd28** [comment]
Hi @Raven888888,
You need to set an environment variable JSON_TYPE_CAST_ENABLED in false
