### ISSUE TITLE
User activation link is not working after segregating thingsboard UI module from API

### ISSUE THREAD

**Issue by sudattakumar** [thingsboard/thingsboard#705]
I have segregated thingsboard UI module from API 
I am runnig UI on my local machine on port 3000 and hosted API on remote server which is running on port 8080.
After creating user when i trying to activate newly created user , activation url redirect to index page instead of create password page.
below is the Activation link,
http://localhost:3000/api/noauth/activate?activateToken=EnKqvuFo2aqoXj3VQKw5WBc1IpKPSE

**Comment by mp-loki** [comment]
Activation link will not work when running UI in debug mode. To activate your user you run your app in normal mode.

**Comment by mariojfduarte** [comment]
Hi,

I'm running the UI the same way in Production mode, still the link redirects me to login page. 

Any tips?

**Comment by aniketfidelit** [comment]
use localhost:8080 instead of localhost:3000 for activation link API.
1)after running thingsboard hit localhost:8080 instead of localhost:3000 and then create a user
2) now you can use activation link which will be generated with localhost:8080.

**Comment by mariojfduarte** [comment]
I keep getting redirected, even when I use port 8080 or 9090

My backend is running on port: 9090

**Comment by alperensener** [comment]
Is there any solution?

**Comment by mariojfduarte** [comment]
Still waiting
