### ISSUE TITLE
Device ID no longer visible via Provisioning API ?

### ISSUE THREAD

**Issue by jianyepa** [thingsboard/thingsboard#7050]
**Component**

 * Generic

**Description**
I'm following this instruction to provision my device (With X509 certificate). https://thingsboard.io/docs/user-guide/device-provisioning/?mqttprovisioning=x509-certificate&httpprovisioning=access-token

I try both MQTT and HTTP request, and the device ID is always excluded in the respond

For example, output of using the example script from the user-guide above, only credentialsValue, credentialsType and status are returned:
_[Provisioning client] Received data from ThingsBoard: {"credentialsValue":"MIICyTCCAbGgAwIBAgIUOuwlSRziMglYUoEc6XXGDMXNizowDQYJKoZIhvcNAQELBQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIyMDgwNjEyNTA0NVoXDTMyMDgwMzEyNTA0NVowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1KFPXliNvSIm58D6SkRCsHL4FHXKJEXNICan8UU3MkOkUOd3gu39o/xozfpLg1kWrdmVqBJCipOkty1XXT+FpxuSINxglcfjg+DU4LNUBGSo/KAx4BEk9kO7UJUf4xkmpP0jCnNSalpoT0rBNKQ7B9YaN4oBIqm/gheRIyMoSWyv2aRRGiC0JWnT8P06jbI+oeNTeDD7xb1lFgAVGdV4PzoJWAWGFkG7MKle3I0n30leCZmRXjhFHjjDk1c2fpRSCckUJ1H5TRjOWMC1twsgZEE5irZE4IlrIo0jM98hvlFtp1elheRGae349sovKwSPdkL2xZ/iUmulyx/OXltwNQIDAQABoxMwETAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBj0vTR3mJYlGF6lhGFcC9gLNeUYYkE3UYkiksjTnUIPbkuftn+ZegXVwGXAkDZinAltLMJq6shodqTQY0u3SEXW0J+BmT+pUOLMSIi+6h7z27ckW5VQuPbNIA8nLbNP8Rmv1y2fqpCaO9hGaUsuenqAfzCUkRw5AxLGBDRe/00FJDfo4rr+IDin/lR24xJzsndUhj2fCLfrbbxd97sevZ3uXmnoRbkE54NyMxLyEUCmAYdADA6xqQAs17SeoT7syAZKCcvO+FeDsl8nbsv3Q8YUip77dA2UqcVblirZrGZH4sfDN+LVZLWT2YeMjLhOgAZNXnnO/3LyuGlEFyeoojb","credentialsType":"X509_CERTIFICATE","status":"SUCCESS"}_

**Environment**

 * OS:  Ubuntu + Thingsboard Docker
 * ThingsBoard: version

**Comment by epalchenko** [comment]
Hello,
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket with detailed steps to reproduce if this problem still exists.
