### ISSUE TITLE
ThingsBoard sync between CE and PE platform using version control

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7056]
We have two ThingsBoard platforms: community edition for testing purpose, and professional edition for production. After I created a version in Gitlab for PE platform, I tried to restore the version in CE platform. Then the following error happened. May I know what is wrong and how to make it work?

![image](https://user-images.githubusercontent.com/17080208/183394141-a1179ee0-4657-4788-b101-0636f2030320.png)

**Comment by ashaforost** [comment]
Hi @sunyong-mwi 

Thingsboard VC feature doesn't support sync between CE and PE versions due to a difference in the entities definition in CE and PE. Thingsboard team is aware of this detail, but currently, it's not on a roadmap.
