### ISSUE TITLE
[Bug] Firmware OTA over MQTT 

### ISSUE THREAD

**Issue by mhelektro** [thingsboard/thingsboard#7058]
**Describe the bug**
I am running into problems where TB is not sending chunks of data. The example code (mqtt_firmware_client.py) does not work either. It gets stuck after printing "Firmware is not the same". It does publish a MQTT message to topic v2/fw/request/1/chunk/0, containing the given chunk size as payload. Although I also tried without giving a chunk size. 

**Your Server Environment**

* own setup
  * local infrastructure or docker deployment
  * ThingsBoard Version : 3.4.0
  * OS Name and Version : Ubuntu 22.04 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: W10Pro 
* Browser: MS Edge 
* Version 103.0.1264.71

**Your Device**

* Connectivity
  * MQTT
* Device vendor and model
  * Python example script mqtt_firmware_client.py

**To Reproduce**
1. Create new firmware in tab "OTA updates", make sure to select the right device profile
2. Select a device in "Devices" tab, edit and change "Assigned firmware" to the just created firmware
3. Start the python script and fill in the required information

**Expected behavior**
Chunks of data coming from the server

**Screenshots**
Not applicable

**Additional context**
When repeating the steps on an actual device, we see the same behaviour. The devices have TLS enabled, but that does not change the result.

**Comment by ban2derlog** [comment]
Hi, is this install of ThingsBoard full monolith or does it have services that are separate - on another instance or in Docker?
If you use separate instance for MQTT transport and, also, Redis - there is an option that you don't set Redis configuration for MQTT transport.
Also, it will be helpful to get a log file from ThingsBoard core service and (if they persist) MQTT transport service.

**Comment by mhelektro** [comment]
Thanks for your reply. 
My colleague who setup thingsboard is currently on holiday. I'm not sure what the exact setup parameters look like. 
I'll have the requested information next week, together with the logs. 

Is there anything I can do in ThingsBoard to test this further?

Thanks!

**Comment by mhelektro** [comment]
I've managed to login into the system, found this log happening when trying out the python example script:

`2022-08-09T09:28:54.182782368Z stdout F 2022-08-09 09:28:54,182 [nioEventLoopGroup-3-9] WARN  o.t.s.t.mqtt.MqttTransportHandler - [d7ff530f-1f95-40f3-8f3f-167c6f73ed1f] Failed to subscribe to [v2/fw/response/+][AT_MOST_ONCE]
2022-08-09T09:28:55.471980523Z stdout F 2022-08-09 09:28:55,471 [kafka-producer-network-thread | transport-api-request-tb-mqtt-transport-0] WARN  o.a.k.c.producer.internals.Sender - [Producer clientId=transport-api-request-tb-mqtt-transport-0] Got error produce response with correlation id 5147 on topic-partition tb_transport.api.requests-26, retrying (0 attempts left). Error: UNKNOWN_PRODUCER_ID
2022-08-09T09:28:55.472017538Z stdout F 2022-08-09 09:28:55,471 [kafka-producer-network-thread | transport-api-request-tb-mqtt-transport-0] INFO  o.a.k.c.p.i.TransactionManager - [Producer clientId=transport-api-request-tb-mqtt-transport-0] ProducerId set to 1030 with epoch 49
2022-08-09T09:28:55.472028992Z stdout F 2022-08-09 09:28:55,471 [kafka-producer-network-thread | transport-api-request-tb-mqtt-transport-0] INFO  o.a.k.c.p.internals.ProducerBatch - Resetting sequence number of batch with current sequence 1 for partition tb_transport.api.requests-26 to 0`

This log comes from /var/log/containers/tb-mqtt-transport-0_thingsboard_server-***.log where *** is some kind of identifier of long length.

I'm not sure if there are any other logs I can check to find more information? The following logs are in the same folder:

- calico-kube-controllers-5f87dbc597-png5h_kube-system_calico-kube-controllers-
- calico-node-kbcc6_kube-system_calico-node-
- calico-node-kbcc6_kube-system_flexvol-driver-
- calico-node-kbcc6_kube-system_install-cni-
- calico-node-kbcc6_kube-system_upgrade-ipam-
- cassandra-0_thingsboard_cassandra-
- cassandra-1_thingsboard_cassandra-
- cassandra-2_thingsboard_cassandra-
- cert-manager-6dd9658548-qr9dv_cert-manager_cert-manager-
- cert-manager-cainjector-5987875fc7-jhdcx_cert-manager_cert-manager-
- cert-manager-webhook-7b4c5f579b-xflbc_cert-manager_cert-manager-
- controller-6dfbf9b9c6-8wdc4_metallb-system_controller-
- coredns-66bcf65bb8-vvtfn_kube-system_coredns-
- dashboard-metrics-scraper-6b6f796c8d-6jbfl_kube-system_dashboard-metrics-
- hostpath-provisioner-76f65f69ff-482pn_kube-system_hostpath-provisioner-
- kubernetes-dashboard-765646474b-fc867_kube-system_kubernetes-dashboard-
- metrics-server-5f8f64cb86-nfs84_kube-system_metrics-server-
- nginx-ingress-microk8s-controller-gvm77_ingress_nginx-ingress-microk8s-
- postgres-7c9944c779-ncbnf_thingsboard_postgres-
- speaker-b5bmw_metallb-system_speaker-
- tb-coap-transport-0_thingsboard_server-
- tb-http-transport-0_thingsboard_server-
- tb-js-executor-5847b578d4-77zbg_thingsboard_server-
- tb-js-executor-5847b578d4-dbnbc_thingsboard_server-
- tb-js-executor-5847b578d4-jmwfp_thingsboard_server-
- tb-js-executor-5847b578d4-rngvf_thingsboard_server-
- tb-js-executor-5847b578d4-vxq9f_thingsboard_server-
- tb-kafka-0_thingsboard_server-
- tb-mqtt-transport-0_thingsboard_server-
- tb-node-0_thingsboard_server-
- tb-redis-f5687d7d5-rdgv2_thingsboard_server-
- tb-web-ui-86b958f49c-72rgr_thingsboard_server-
- webserver-depl-677c9b487f-kx4w5_thingsboard_webserver-app-
- zookeeper-0_thingsboard_zookeeper-
- zookeeper-1_thingsboard_zookeeper-
- zookeeper-2_thingsboard_zookeeper-

**Comment by ban2derlog** [comment]
As I can see - you use k8s deployment.
Check you MQTT TRANSPORT Stateful set and add REDIS_HOST environment.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-mqtt-transport
  namespace: thingsboard
spec:
  template:
    spec:
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: tb-pe-mqtt-transport:3.3.2PE
        ports:
        - containerPort: 1883
          name: mqtt
        env:
        .......
        - name: REDIS_HOST
          value: "tb-redis"
```

**Comment by mhelektro** [comment]
Hi!

Thanks for your response. That fixed the issue. 
Might want to add that to the manual, I had no idea to add those lines to thingsboard.yml.

Thanks! 

Marcel
