### ISSUE TITLE
[Feature Request] Auto-close old Github issues

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7059]
As I know there is Github plugin to do this job.

**Comment by Ultrazombie** [comment]
Hi @devaskim, we do not want to use plugins to close old tickets, as they may still be relevant or have bugs or feature requests.
A while ago, we allocated more engineers to solve problems and manually close old tickets.

**Comment by devaskim** [comment]
@Ultrazombie sounds reasonable but there are tickets opened in 2017 and they are absolutely irrelevant at the moment

**Comment by Ultrazombie** [comment]
@devaskim, 
yes, we know. hopefully, the 1.4k figure will decrease in the coming months
We are now trying to establish work with issue, with the old issue too.

**Comment by devaskim** [comment]
Thanks @Ultrazombie for quick response.
It would be great if TB team comments in some way all incoming feature request (like 'add to backlog', 'not interested' and etc).
And good luck!
