### ISSUE TITLE
[Question] SQLite storage terribly slow for IoT-Gateway. What are my options?

### ISSUE THREAD

**Issue by MarkusCropZone** [thingsboard/thingsboard#7060]
**Component**

 * Generic

**Description**
Hi,
I have already described my problem once in another question (https://github.com/thingsboard/thingsboard/issues/6880), sadly with no response.

Now I have recreated a much simpler situation with the same problem: SQLite is a bottleneck for IoT-Gateay.
In the setup guide there are 3 storage types available: Memory, File and SQLite.
For testing I use a script, which publishes a small payload 10 times per second.
Here are the results.

Memory:
![image](https://user-images.githubusercontent.com/107556149/183580433-3cabe3a8-afdd-4da3-be85-e99e666adecc.png)

File:
![image](https://user-images.githubusercontent.com/107556149/183580211-e9378ba3-32db-4d16-8fe3-7d7e47b3ff01.png)

SQLite:
![image](https://user-images.githubusercontent.com/107556149/183580634-7ee1eec2-627c-4726-b96a-773f4ab39b48.png)

Memory and file storage consistently get the 10 datapoints. SQLite however only gets around 40%.
And this is with a very small payload 
`{'SN': 'TestMaschine', 'v': str(random.random()), 'testest': '2', 'test': '3', 'TS_MIL': t, 'daten': {'unit': []}}`

The problem I have is that I have quite large payloads in reality (around 3000 characters).
In this case Memory and File do start to lag behind (while still managing to bring all 10 datapoints/s into TB)
That's why I thought the SQLite storage is the best fit for me (espcially because it says "recommended for more speed" in the setup guide). But with this result SQLite and apparently the whole IoT-Gateway is not practical for me.

So what are my alternatives? Do I really need to look into PE and "Integrations"? Would this actually solve my problem?
Or is there even a way to make it work with Gateway?

Thanks

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.4

**Comment by devaskim** [comment]
I think it would be better to move your question to [gateway project](https://github.com/thingsboard/thingsboard-gateway)

**Comment by MarkusCropZone** [comment]
Oh right, that makes more sense, thanks!

**Comment by vvlladd28** [comment]
Duplicate https://github.com/thingsboard/thingsboard-gateway/issues/899
