### ISSUE TITLE
[Bug] deviceId is not returned in provisioning request (MQTT / https requests)

### ISSUE THREAD

**Issue by jianyepa** [thingsboard/thingsboard#7063]
**Describe the bug**
Following this documents (https://thingsboard.io/docs/user-guide/device-provisioning/?mqttprovisioning=x509-certificate) to provision devices programatically via MQTT / HTTPS request (cURL), expecting to receive deviceID as part of the response, but unable to observe it

I got everything in response like example below except the "deviceId", observed device successfully added in Thingsboard, I have to manually copy the device ID and this is blocking my automation flow

_Example of response (with deviceId)_
{
  "deviceId":"3b829220-232f-11eb-9d5c-e9ed3235dff8",
  "credentialsType":"X509_CERTIFICATE",
  "credentialsId":"f307a1f717a12b32c27203cf77728d305d29f64694a8311be921070dd1259b3a",
  "credentialsValue":"MIIB........AQAB",
  "provisionDeviceStatus":"SUCCESS"
}

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version - Not Sure (Please enlighten me how to get the version if using docker deployed Thingsboard server)
  * OS Name and Version - Ubuntu 18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Ubuntu 20.04
* Browser [e.g. chrome, safari] N/A
* Version [e.g. 22]

* Connectivity
  * MQTT
  * HTTP

**To Reproduce**
1. I sent provision request from a Ubuntu 20.04 host with cURL, example:
curl -s --noproxy "*" -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Authorization: Bearer <my_token>' -d '{"deviceName": "test-5", "provisionDeviceKey": "<mykey>", "provisionDeviceSecret": "<mysecret>", "credentialsType": "X509_CERTIFICATE", "hash": "<content_of_public>"}' http://<IP:PORT>/api/v1/provision

**Expected behavior**
Return of response like mentioned in https://thingsboard.io/docs/user-guide/device-provisioning/?mqttprovisioning=x509-certificate

**Comment by trikimiki** [comment]
> Please enlighten me how to get the version if using docker deployed Thingsboard server

You can check image version via `docker ps` or via your docker-compose file - the image version corresponds to ThingsBoard version:
```
$ docker ps | grep thingsboard
< . . . >   thingsboard/tb-node:3.4.0   < . . . >
```

---

I think that part of the documentation is outdated. As you can see from "How it works?" section, it will return only status, cred type, and the cred (either token or certificate aka public key):
Call:
```
curl -s -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Authorization: Bearer <token>' -d '{"deviceName": "test-my-provisioned-device", "provisionDeviceKey": "<provision_key>", "provisionDeviceSecret": "<provision_secret>", "credentialsType": "X509_CERTIFICATE", "hash": "<cert_cred>"}' http://localhost:8080/api/v1/provision
```
Response:
```
{"credentialsValue":"<cert_cred>","credentialsType":"X509_CERTIFICATE","status":"SUCCESS"}
```
This makes sense, as you don't need a device ID in order to work with the device - you need to use credential provided in the response.

---

If you need the ID of the created device, you can use "getTenantDevice" call:
Call:
```
curl -s -X 'GET' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Authorization: Bearer <token>' 'http://localhost:8080/api/tenant/devices?deviceName=test-my-provisioned-device'
```
Response:
```
{"id":{"entityType":"DEVICE","id":"6755e8e0-18a4-11ed-a011-6df4a303756d"},"createdTime":1660132990574,"additionalInfo":null,"tenantId":{"entityType":"TENANT","id":"b8d51b90-bec9-11eb-8d19-a948c4616cf8"},"customerId":{"entityType":"CUSTOMER","id":"13814000-1dd2-11b2-8080-808080808080"},"name":"test-my-provisioned-device","type":"test-povisioning","label":null,"deviceProfileId":{"entityType":"DEVICE_PROFILE","id":"7c2cf390-18a3-11ed-a011-6df4a303756d"},"deviceData":{"configuration":{"type":"DEFAULT"},"transportConfiguration":{"type":"MQTT"}},"firmwareId":null,"softwareId":null,"ownerId":{"entityType":"TENANT","id":"b8d51b90-bec9-11eb-8d19-a948c4616cf8"}}
```
Let me beautify the response:
```
{
  "id": {
    "entityType": "DEVICE",
    "id": "6755e8e0-18a4-11ed-a011-6df4a303756d"
  },
  "createdTime": 1660132990574,
  "additionalInfo": null,
  "tenantId": {
    "entityType": "TENANT",
    "id": "b8d51b90-bec9-11eb-8d19-a948c4616cf8"
  },
  "customerId": {
    "entityType": "CUSTOMER",
    "id": "13814000-1dd2-11b2-8080-808080808080"
  },
  "name": "test-my-provisioned-device",
  "type": "test-povisioning",
  "label": null,
  "deviceProfileId": {
    "entityType": "DEVICE_PROFILE",
    "id": "7c2cf390-18a3-11ed-a011-6df4a303756d"
  },
  "deviceData": {
    "configuration": {
      "type": "DEFAULT"
    },
    "transportConfiguration": {
      "type": "MQTT"
    }
  },
  "firmwareId": null,
  "softwareId": null,
  "ownerId": {
    "entityType": "TENANT",
    "id": "b8d51b90-bec9-11eb-8d19-a948c4616cf8"
  }
}
```

**Comment by jianyepa** [comment]
> > Please enlighten me how to get the version if using docker deployed Thingsboard server
> 
> You can check image version via `docker ps` or via your docker-compose file - the image version corresponds to ThingsBoard version:
> 
> ```
> $ docker ps | grep thingsboard
> < . . . >   thingsboard/tb-node:3.4.0   < . . . >
> ```
> 
> I think that part of the documentation is outdated. As you can see from "How it works?" section, it will return only status, cred type, and the cred (either token or certificate aka public key): Call:
> 
> ```
> curl -s -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Authorization: Bearer <token>' -d '{"deviceName": "test-my-provisioned-device", "provisionDeviceKey": "<provision_key>", "provisionDeviceSecret": "<provision_secret>", "credentialsType": "X509_CERTIFICATE", "hash": "<cert_cred>"}' http://localhost:8080/api/v1/provision
> ```
> 
> Response:
> 
> ```
> {"credentialsValue":"<cert_cred>","credentialsType":"X509_CERTIFICATE","status":"SUCCESS"}
> ```
> 
> This makes sense, as you don't need a device ID in order to work with the device - you need to use credential provided in the response.
> 
> If you need the ID of the created device, you can use "getTenantDevice" call: Call:
> 
> ```
> curl -s -X 'GET' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Authorization: Bearer <token>' 'http://localhost:8080/api/tenant/devices?deviceName=test-my-provisioned-device'
> ```
> 
> Response:
> 
> ```
> {"id":{"entityType":"DEVICE","id":"6755e8e0-18a4-11ed-a011-6df4a303756d"},"createdTime":1660132990574,"additionalInfo":null,"tenantId":{"entityType":"TENANT","id":"b8d51b90-bec9-11eb-8d19-a948c4616cf8"},"customerId":{"entityType":"CUSTOMER","id":"13814000-1dd2-11b2-8080-808080808080"},"name":"test-my-provisioned-device","type":"test-povisioning","label":null,"deviceProfileId":{"entityType":"DEVICE_PROFILE","id":"7c2cf390-18a3-11ed-a011-6df4a303756d"},"deviceData":{"configuration":{"type":"DEFAULT"},"transportConfiguration":{"type":"MQTT"}},"firmwareId":null,"softwareId":null,"ownerId":{"entityType":"TENANT","id":"b8d51b90-bec9-11eb-8d19-a948c4616cf8"}}
> ```
> 
> Let me beautify the response:
> 
> ```
> {
>   "id": {
>     "entityType": "DEVICE",
>     "id": "6755e8e0-18a4-11ed-a011-6df4a303756d"
>   },
>   "createdTime": 1660132990574,
>   "additionalInfo": null,
>   "tenantId": {
>     "entityType": "TENANT",
>     "id": "b8d51b90-bec9-11eb-8d19-a948c4616cf8"
>   },
>   "customerId": {
>     "entityType": "CUSTOMER",
>     "id": "13814000-1dd2-11b2-8080-808080808080"
>   },
>   "name": "test-my-provisioned-device",
>   "type": "test-povisioning",
>   "label": null,
>   "deviceProfileId": {
>     "entityType": "DEVICE_PROFILE",
>     "id": "7c2cf390-18a3-11ed-a011-6df4a303756d"
>   },
>   "deviceData": {
>     "configuration": {
>       "type": "DEFAULT"
>     },
>     "transportConfiguration": {
>       "type": "MQTT"
>     }
>   },
>   "firmwareId": null,
>   "softwareId": null,
>   "ownerId": {
>     "entityType": "TENANT",
>     "id": "b8d51b90-bec9-11eb-8d19-a948c4616cf8"
>   }
> }
> ```



> docker ps | grep thingsboard

I am following the REST API documentation (ie http://<tb-addr>:<port>/swagger-ui) to develop my works and most of it required device ID
Thanks for your prompt reply and this really helped me a lot in automating the device provisioning.
