### ISSUE TITLE
How to pull the dashboard id in rulechain script. 

### ISSUE THREAD

**Issue by laxmiprasannaBorigi** [thingsboard/thingsboard#7064]
* Rule Engine

I have a requirement where i am generating alarm through rule chain. When alarm created i need to map the dashboard id to that rulechain. i will use the same rule chain configuration for all my tenants so the dashboard id will be differenet for each tenant . How to pull the  dashboard id in rule chain create alarm node.

**Environment**

 * ThingsBoard: 3.3.4.1

**Comment by devaskim** [comment]
In case of single dashboard per tenant you may just hardcode dashboard's id in rule chain configuration.

Otherwise you can call [Thingsboard REST API](https://demo.thingsboard.io/swagger-ui/#/dashboard-controller) from rulechain to resolve id. [Here](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/tb_api_token) is how to get Thingsboard REST API token.

**Comment by laxmiprasannaBorigi** [comment]
Yah this dashboard id should be dynamic because same rule chain i configured for all my tenants. To call the rest api from rule chain do we have any component for that? Please let me know @devaskim

**Comment by devaskim** [comment]
Rule Engine provides [REST API node](https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/)

**Comment by laxmiprasannaBorigi** [comment]
yah i verified that facing  challanges to send the authorization details because how we can know all the tenant login details.. so is there any way to pull the authorization details.. @devaskim

**Comment by devaskim** [comment]
I think there is no such capability, only manual insertion

**Comment by laxmiprasannaBorigi** [comment]
@devaskim  i tried to inject the dashboard dynamically through code (when alarm creates it is calling TbCreateAlarmNode this class. so here i am calling dashboard service to pull the dashboard id and updating to alarm details before save). 

One issue i am facing when i do this is: Not able to get the dashboardservice object in TbCreateAlarmNode class getting null for dashboard object using Autowire here. 

Please suggest if anyone have idea here..

**Comment by devaskim** [comment]
It is not clear for me whether you are developing custom rule node (1) or using those Thinsboard are providing out of the box (2).

(1) If your goal is to custom rule node, so you need _Java_ and here is [here is API](https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java#L215) to get _DashboardService_

(2) When you are using already existing rule node only part of them let you to customize their behaviour but with _JavaScript_ And in this case there is **no access** to Thinsboard services such _DashboardService_ and etc.

**Comment by laxmiprasannaBorigi** [comment]
No i am updating existing method createNewAlarm in TbCreateAlarmNode to update the dashboard id based on the dashboard name before creating the alarm.@devaskim

**Comment by devaskim** [comment]
Ok. As I mentioned before you could access to service's objects through TbContext which is already in _createNewAlarm_

**Comment by laxmiprasannaBorigi** [comment]
@devaskim  Thank you working as expected with TbContext.
