### ISSUE TITLE
Configuring widget with different colours to negative and positive values

### ISSUE THREAD

**Issue by dbalanof1975** [thingsboard/thingsboard#7066]
* Generic

**Description**

I am having problems configuring a widget ( Arc type)  that have a range between -50 to 50 to a battery Amperage.
if battery is charging value is negative in the payload, if battery is supplying enegry value is a positive in payload.

I would like to show always a positive value and do a conditional to the color of the bars as follows :
a) red when receiving a negative value  ( to represent  charging )
b) green when receiving a positive value (. to represent supplying)

**Environment**
 * OS:  MacOS Mopnterrey 12.4
 * ThingsBoard: Cloud
 * Browser: Chrome - Versión 103.0.5060.134 (Build oficial) (x86_64)

thanks in advance for the help.
Dan

**Comment by devaskim** [comment]
It is impossible with current implementation of Arc widget.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
