### ISSUE TITLE
About syntaxerror of referencing parts through TB dashboard state

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7068]
**Component**

 * Generic

**Description**
Hello:
1. Open dashbaord
2. Add a state named "test"
3. Add a map to the state named "test" and set the data source
4. Add a markdown / HTML card part in the state named "default"
5. Add the following code to the markdown / HTML pattern in the markdown / HTML card component:
```html
<div class="market-layout" style="width: 100%; height: 100%; padding: 0;" fxLayout="column">
    <tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" stateId="test"></tb-dashboard-state>
<div>
```
7. The prompt error contents are as follows:
```json
message: "Expected \"=\", \"}\", or identifier but end of input found."
name: "SyntaxError"
```
**Environment**

 * OS:  centos 7
 * ThingsBoard: 3.3.3
 * Browser: Chrome 104.0.5112.81

**Comment by devaskim** [comment]
Try to use brackets around _stateId_
```
[stateId]="'test'"
or
[stateId]="test"
```

**Comment by Backdraft007** [comment]
Your div doesn't close.

**Comment by struggle3** [comment]
> Try to use brackets around _stateId_
> 
> ```
> [stateId]="'test'"
> ```
> 
> or
> 
> ```
> [stateId]="test"
> ```

Modify the code to [stateid] = "test" and still prompt syntax error

**Comment by struggle3** [comment]
> Try to use brackets around _stateId_
> 
> ```
> [stateId]="'test'"
> ```
> 
> or
> 
> ```
> [stateId]="test"
> ```

<tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" [stateId]="test"></tb-dashboard-state>

**Comment by struggle3** [comment]
> Try to use brackets around _stateId_
> 
> ```
> [stateId]="'test'"
> ```
> 
> or
> 
> ```
> [stateId]="test"
> ```

<tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" [stateId]="test"></tb-dashboard-state>

**Comment by struggle3** [comment]
> Try to use brackets around _stateId_
> 
> ```
> [stateId]="'test'"
> ```
> 
> or
> 
> ```
> [stateId]="test"
> ```

```html
<tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" [stateId]="test"></tb-dashboard-state>
```

**Comment by pon0marev** [comment]
Please try this:
`<div class="market-layout" style="width: 100%; height: 100%; padding: 0;" fxLayout="column">
    <tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" stateId="test"></tb-dashboard-state>
</div>`

**Comment by struggle3** [comment]
> Please try this: `
> 
> 
> <tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" stateId="test">
> `

That's not good. I originally wrote this code. I was successful in thingsboard PE, but I was not successful in thingsboard CE.

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
