### ISSUE TITLE
[Question] Route Map to show distrance travelled

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#7069]
I want to show the distance a vehicle has traveled between specified dates. Is there a function inside the route map? If not can how can I show the distance?

**Comment by ssakharova** [comment]
Hello @inanlia,

Try using the Trip animation widget. This widget can be useful for various use cases, but primarily, it can be used to track, analyze, and visualize the movement of different entities in real-time.

For more information, please refer to https://thingsboard.io/docs/pe/user-guide/ui/trip-animation-widget/
