### ISSUE TITLE
[Question] Can we change to a specific originator?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#7071]
**Component**

 * Rule Engine

**Description**
If a device belongs to two different assets, how can I change the originator to a specific one? In the documentation for the change originator node, it says that it will change to the first one. Is there a way around this?

**Environment**

 * OS: Windows
 * ThingsBoard: Cloud
 * Browser: Mozilla

**Comment by devaskim** [comment]
I think as of v3.4.0 it is possible only if device is binded with assets with different relation types, for example, CONTAINS and MANAGES and etc.

**Comment by OzyOzk** [comment]
> 

Thanks. I think this will work for me right now, but it would be good to be able to choose the asset

**Comment by OzyOzk** [comment]
> I think as of v3.4.0 it is possible only if device is binded with assets with different relation types, for example, CONTAINS and MANAGES and etc.

Thanks. I think this will work for me right now, but it would be good to be able to choose the asset

**Comment by myroslav-tb** [comment]
Hi @OzyOzk, in the latest version of Thingsboard (3.6.4), you can specify the asset name as the relation type.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
