### ISSUE TITLE
Is it possible to establish Thingsboard to Thingsboard communication?

### ISSUE THREAD

**Issue by gulzh** [thingsboard/thingsboard#7072]
I am using Meazon and Thingsboard platforms for collecting data from various sensors.
Meazon is apparently, an integrator that has branded its version of ThingsBoard.
What I need is to transfer the data from Meazon to Thingsboard.
Is it possible? Do you have any suggestions on that?

Thank you!

**Comment by ban2derlog** [comment]
Hi,
You can use RestAPI to get and post data.
In ThingsBoard you can add to your endpoint - `swagger-ui.html` , and see all RestAPI controllers.
Here is example:
https://thingsboard.cloud/swagger-ui.html
Here is official documentation:
https://thingsboard.io/docs/reference/rest-api/
