### ISSUE TITLE
Where do I create dashboards only for mobile?

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard#7074]
Hey,
is it possible to create a dashboard / dashboard-state, which is exclusivly for the app / mobile browser?

**Comment by devaskim** [comment]
As I know there is option to hide dashboard in mobile application (see dashboard's details page)

**Comment by rungg12** [comment]
yes i know that, but i need to display it ONLY in the mobile

**Comment by ChrisEvisi** [comment]
You'll need to create a separate Mobile dashboard and uncheck 'Hide Dashboard in Mobile Application' in dashboard entity Details setting.  Then set check 'Hide Dashboard....' for all the other dashboards that you dont want in the mobile app as these will auto populate into Mobile dashboards if not Hidden.
![image](https://user-images.githubusercontent.com/66198901/184517322-6016255d-7a5c-424d-bb9a-11ea51733c9f.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
