### ISSUE TITLE
[Question] event controller REST API  pageSize, page, startTime not working

### ISSUE THREAD

**Issue by gaurav36** [thingsboard/thingsboard#7081]
**Event Controller GET1 REST API **

 * Generic

**Description**
Dear Team, 
I am querying some data using ThingsBoard REST API. I am mainly Queryign event Controller data (swagger-ui.html#!/event-controller/getEventsUsingGET_1) 
REST API:  [/api/events/{entityType}/{entityId}{?tenantId,pageSize,page,textSearch,sortProperty,sortOrder,startTime,endTime}] 

I am not able to use make of startTime filed. I am giving startTime Value in mili second but its not working. for eg: If i want to get data from 09th Aug at 11:16:56 GMT then , i am giving start time value as 1660043816000

Could you please advice what value you accept in start time ? 

Could you also advice me what will be value of pageSize and page if i want to get all data from start time in milli second  1660043816000 (9th August at 11:16:56 GMT)

Sorting filter in the REST API is also not working. 

*you can file screenshot here: https://ibb.co/bJ683qT *

**Environment**

 * OS:  ubuntu 20.0
 * ThingsBoard: 3.4
 * Browser: firefox Version 103.0.2 (64-bit), Chrome Version 104.0.5112.81 (Official Build) (64-bit) [its not working in both browser]

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. Feel free to open a new ticket with full description of your request if it still relevant for you.
