### ISSUE TITLE
[Bug] Ubuntu 22.04.1 with PostgreSQL+cassandra and Kafka install fails on Step 6 of guide

### ISSUE THREAD

**Issue by dvisser** [thingsboard/thingsboard#7087]
**Describe the bug**
I have followed the install guide here
[https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardDatabase=hybrid&ubuntuThingsboardQueue=kafka](https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardDatabase=hybrid&ubuntuThingsboardQueue=kafka)
and the installation fails at Step 6. 

When I run the install script I get the following error:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ThingsBoard installation failed!

Then I look at the error log and get the following output:

cat /var/log/thingsboard/thingsboard.log | grep ERROR

2022-08-15 21:29:02,147 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
2022-08-15 21:29:02,153 [main] ERROR o.s.o.j.LocalContainerEntityManagerFactoryBean - Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
2022-08-15 21:29:02,222 [main] ERROR o.s.boot.SpringApplication - Application run failed

**Your Server Environment**
* own setup
  * local infrastructure

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] Using SSH to Ubuntu server for installation

**To Reproduce**
1. Follow the install guide using ubuntu with hybrid database (postgresql + cassandra) and Kafka queue.

**Expected behavior**
A clean install of ThingsBoard.

**Comment by trikimiki** [comment]
```
2022-08-15 21:29:02,147 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
```
This means there is something wrong with your Postgres. Can you check:
- is it up and running (`pg_lsclusters` or `service postgresql status`)
- whether "postgres" user password (try to login with `psql -U postgres -h localhost`) corresponds to the one in `/etc/thingsboard/conf/thingsboard.conf` - `SPRING_DATASOURCE_PASSWORD`

**Comment by dvisser** [comment]
> ```
> 2022-08-15 21:29:02,147 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
> ```
> 
> This means there is something wrong with your Postgres. Can you check:
> 
> * is it up and running (`pg_lsclusters` or `service postgresql status`)
> * whether "postgres" user password (try to login with `psql -U postgres -h localhost`) corresponds to the one in `/etc/thingsboard/conf/thingsboard.conf` - `SPRING_DATASOURCE_PASSWORD`

1. service postgresql status is reporting that it is up and running
2. I can log in using psqk -U postgres -h localhost with the credentials supplied in thingsboard.conf 

Any other ideas?

FYI, I get the same exact issue when I do a new deployment with just postgresql (no cassandra).

**Comment by trikimiki** [comment]
Can you share the full log of installation and service log?
`/var/log/thingsboard/install.log`
`/var/log/thingsboard/thingsboard.log`

**Comment by laurentElement** [comment]
I have the exact same error although i use postgresql only and use in-memory queue. 
I already checked postgresql service status and credentials it is OK. 
Attached are the log requested.

[install.log](https://github.com/thingsboard/thingsboard/files/9367952/install.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/9367953/thingsboard.log)

**Comment by dvisser** [comment]
> I have the exact same error although i use postgresql only and use in-memory queue. 
> I already checked postgresql service status and credentials it is OK. 
> Attached are the log requested.
> 
> [install.log](https://github.com/thingsboard/thingsboard/files/9367952/install.log)
> [thingsboard.log](https://github.com/thingsboard/thingsboard/files/9367953/thingsboard.log)
> 
> 

Yep I tried this type of install today too on ubuntu 18.04 and 20.04 LTS and had exactly the same result. 

Curious? 

I also had mine work after initial install, but as soon as the machine has been rebooted atleast once, it fails in this manner. Weird.

**Comment by trikimiki** [comment]
@laurentElement 
From your log file: `org.postgresql.util.PSQLException: FATAL: database "thingsboard" does not exist`
Did you follow these steps during installation?
```
psql -U postgres -d postgres -h 127.0.0.1 -W
CREATE DATABASE thingsboard;
\q
```
@dvisser 
I can look into your problem, if you share logs as well ;)

**Comment by dvisser** [comment]
> @laurentElement 
> From your log file: `org.postgresql.util.PSQLException: FATAL: database "thingsboard" does not exist`
> Did you follow these steps during installation?
> ```
> psql -U postgres -d postgres -h 127.0.0.1 -W
> CREATE DATABASE thingsboard;
> \q
> ```
> @dvisser 
> I can look into your problem, if you share logs as well ;)

Sure. I will reproduce the error and then grab logs for you when I am back near the hardware next week. Thankyou. 

I do however know my database exists. But my logs should tell the story. Talk next week!

**Comment by trikimiki** [comment]
@dvisser please feel free to re-open (or create a new issue) once you grab logs.
