### ISSUE TITLE
how to reboot a device from dashboard using control widget button?

### ISSUE THREAD

**Issue by Islam-Muradul** [thingsboard/thingsboard#7088]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by ban2derlog** [comment]
Hi,
you can use RPC calls to Device, but only if your device can receive RPC to proceed SHUTDOWN\REBOOT.
https://thingsboard.io/docs/user-guide/rpc/
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/
Here is our documentation.

About your device specification - you need to use Manuals for it or ask a Manufacturer.
