### ISSUE TITLE
[Question] How to add and call local library like - jquery, bootstrap (no internet needed)

### ISSUE THREAD

**Issue by Cmonkz** [thingsboard/thingsboard#7089]
I'm trying to use bootstrap, I can use it perfectly fine when using cdn but I wanna use downloaded library. Any idea how to call it locally? TIA

 * Generic

 * OS: Windows 10
 * ThingsBoard: 3.3.4
 * Browser: Chrome

**Comment by ssakharova** [comment]
Hello @Cmonkz,

The only thing I can suggest to you, in this case, is to refer to this link - https://github.com/thingsboard/thingsboard-extensions/tree/master
