### ISSUE TITLE
Thingsboard on premise

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7090]
Does hosting thingsboard PE on premise will support remote dashboard monitoring for users at any location.

**Comment by trikimiki** [comment]
Did you mean making the dashboard public?

This feature is available for both CE and PE.

For CE, there is an option in the list of dashboards.
For PE, this could be done via Dashboard Groups.

**Comment by mubashirp** [comment]
Okay, but if we install thingsboard on premise on our local server, can the
dashboard be made to view from different locations on any device.

**Comment by trikimiki** [comment]
Yes. As long as your firewall/proxy allows inbound connection to the server, your public dashboard can be accessed by anyone with the link to it.

**Comment by mubashirp** [comment]
If we create a customer account, with a full screen dashboard, can customer
be able to access the account from anywhere, if we allow firewall settings.

**Comment by trikimiki** [comment]
For the public dashboard - you get the link, and it can be accessed in read-only mode for anyone with the link, no login is required.

If you create a customer, it can access a dashboard of the respective tenant user. If you want to restrict the user only to one dashboard - you can setup it so on PE, where he could only get access to some "home page" dashboard after login, with no access to navigation to any other menus. 

What is your particular use case?

**Comment by mubashirp** [comment]
We are using our thingsboard pe cloud to create an user account for one of
our clients , with full screen dashboard in it. But as it is a cloud, the
data is backed up on thingsboard usa server. If we have a provision to host
in our own windows pc, then customer would be more satisfied.
The requirement of the customer is to monitor their facility from remote,
without directly going into the facility. That is why i started with a
cloud account.
If remote monitoring is possible in on premise thingsboard PE , that would
be better.

**Comment by trikimiki** [comment]
So, all the features in the cloud are pretty much available for ThingsBoard PE. I am sure you can make it work with the on-premises installation.

**Comment by mubashirp** [comment]
Thanks, I'll check it out.
