### ISSUE TITLE
Scheduler report is empty

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7096]
I created a scheduler to generate a daily report. The dashboard of the report is a time series chart of all the sensors under a customer. I tested with different customer user credential. If the customer has 2 or 3 sensors, the report has no issue. However, if the customer has 8 or more sensors, the report is empty with no data. From ThingsBoard API usage rule engine statistics, there is no timeout when generating the report.

ThingsBoard version 3.4.0.

Report for customer with 3 sensors
![image](https://user-images.githubusercontent.com/17080208/185016345-94c0dd17-ca1f-47b9-baba-d370ca011333.png)

Report for customer with 8 sensors:
![image](https://user-images.githubusercontent.com/17080208/185016504-85cf28db-9c3a-42b5-8552-9d7fd43c8981.png)

**Comment by trikimiki** [comment]
By default, the Web Reporter waits for 3 seconds before creating the report. If you normally open the problematic dashboard, is data loading for more than 3 seconds?

If this is the case, try increasing the load wait time. For that, add this line to `/etc/tb-web-report/conf/tb-web-report.conf`:
```
export DASHBOARD_LOAD_WAIT_TIME=6000
```
where value is the wait time in ms (6 seconds in the example).

**Comment by sunyong-mwi** [comment]
The dashboard is normally loaded in 1-2 seconds. I set the DASHBOARD_LOAD_WAIT_TIME as 20000 (20 sec), restart the Thingsboard and web report service, but the result is still the same.

**Comment by sunyong-mwi** [comment]
Instead of setting DASHBOARD_LOAD_WAIT_TIME, I set DASHBOARD_IDLE_WAIT_TIME as 2000 (2 sec), and it works. May I know what's the purpose of DASHBOARD_IDLE_WAIT_TIME?

**Comment by trikimiki** [comment]
Sorry, my fault. I was inspecting the old config, with 3.4.0 release variables changed. It changes the same parameter, but was renamed for clarity.
