### ISSUE TITLE
Bug: REST API Call Plugin "Base Path"  configuration change does not work in UI

### ISSUE THREAD

**Issue by setevik00** [thingsboard/thingsboard#71]
Steps to reproduce:

1) Log in as tenant administrator
2) Create new REST API Call plugin with valid host, port and base path settings
3) Create a rule which uses  REST API Call plugin 
4) Activate both rule and REST API Call Plugin
5) Verify that REST API Plugin successfully connects to host specified in STEP 2
6) Change Base Path to some other 
7) Suspend  both REST API Plugin and a Rule
8) Activate both REST API Plugin and a Rule
9) Plugin is still using base path created in step 2, although UI shows a new base path

- Probably same problem happens with hostname and port, not tested
- Changes apply only after Thingsboard service restart

**Comment by ashvayka** [comment]
Thanks for reporting this. It is already fixed in Thingsboard 1.2. There was an overall issue with plugin configuration update. I will close when Thingsboard 1.2 release will be announced.

**Comment by setevik00** [comment]
Great! Waiting for next version release ;)

**Comment by ashvayka** [comment]
Thingsboard 1.2 is released and I am closing this bug now.
