### ISSUE TITLE
Develop new RuleNode 'split array msg'

### ISSUE THREAD

**Issue by YuriyLytvynchuk** [thingsboard/thingsboard#7102]
Description:
Split array message into several msgs

Details:
Split the array fetched from the msg body. If the msg data is not a JSON object returns the incoming message as outbound message with <code>Failure</code> chain, otherwise returns inner objects of the extracted array as separate messages via <code>Success</code> chain.

**Comment by AldirchEugene** [comment]
Please update the official document on the use of the "split array msg" node, thank you

**Comment by William04A** [comment]
Is this documented, which @AldirchEugene asked you about last year?
Could not find it here:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/
