### ISSUE TITLE
[Question] Login/Credentials in URL supported?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7106]
* Generic

**Description**
For demo purpose at customers it would be nice if we can temporarily setup an easy link that they can use to follow what is going on. 
Going through the account setup procedure while you just want to share it (during a 30min demo) to a few people but not make it public takes too much time and you don't want to make unnecessary accounts.

If the username and password can be a added in the login screen url we can work with that, is that possible or for security reasons not supported?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard PE: 3.3.3

**Comment by KenSense** [comment]
like this?
https://thingsboard.com/login?username=myname@gmail.com&password=123456
Does not work

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by gednz** [comment]
>like this?
>https://thingsboard.com/login?username=myname@gmail.com&password=123456
>Does not work


I found that this does work. you need to remove the `/login` like this:
https://thingsboard.com?username=myname@gmail.com&password=123456

**Comment by KenSense** [comment]
> > like this?
> > https://thingsboard.com/login?username=myname@gmail.com&password=123456
> > Does not work
> 
> I found that this does work. you need to remove the `/login` like this: https://thingsboard.com?username=myname@gmail.com&password=123456

Removing 'login' does indeed work (and % encode special characters.)
Tested on CE and PE, consider it solved :)

Thanks !
