### ISSUE TITLE
[Question] TB license server and TB PE Edge

### ISSUE THREAD

**Issue by technorabilia** [thingsboard/thingsboard#7109]
**Component**

 * Generic

**Description**
Suppose we have a central location with four distributed sites.

We install TB PE on the central location and TB PE Edge on each site.

Each site does not have an internet connection but only a connection to the central location.

How does this work with the TB license server?

Does PE Edge check the TB license through TB PE installed on the central location? I.e. only TB PE needs a connection to the TB license server? No connection to the TB license server needed from PE Edge?

**Environment**

 * OS:  not applicable 
 * ThingsBoard: 3.4
 * Browser: not applicable

**Comment by volodymyr-babak** [comment]
Hello @technorabilia 

at the moment ThingsBoard PE Edge is not connecting to the ThingsBoard license server directly but over a cloud instance.
ThingsBoard Edge uses HTTP connection to the ThingsBoard PE instance to verify the license.
ThingsBoard PE instance works as a proxy:
**ThingsBoard Edge** ← HTTP → **ThingsBoard PE** ← HTTP → **ThingsBoard License Server**
![image](https://user-images.githubusercontent.com/3466101/185622200-86866c85-9eef-4c3c-b428-318adfe50ba2.png)


In the configuration of the ThingsBoard Edge you are configuring Cloud Endpoint:
![image](https://user-images.githubusercontent.com/3466101/185622145-0c3ffd4f-2cff-47b7-ae14-77219d204c27.png)

This HTTP URL is used by ThingsBoard Edge exactly to verify the license key. 
At the moment we are not planning to change this behavior.

Edge is able to work offline without connecting to the cloud for 7 days. 

But during these 7 days, Edge should not be restarted - restart requires a connection to the cloud. So please avoid restarting TB Edge if there is no connectivity to the cloud.

**Comment by technorabilia** [comment]
Thank you for the explanation!
