### ISSUE TITLE
[Question] How trigger RPC action of some devices based on telemetry of another

### ISSUE THREAD

**Issue by charlescui** [thingsboard/thingsboard#7111]
**Component**

 * Rule Engine

**Description**
How to achieve it: 
- A Device(just call DeviceA) update a telemetry in Rule Chain, 
 - the key is `scene`, and value is integer such as `1`,
- and then act RPC for other multi devices
 - e.g turn off multi lights

Now I can act one RPC for one device which has relation with DeviceA, but how do this for multi devices.

I want do like this in RuleEngine, but RuleEngine not supported do this.

![image](https://user-images.githubusercontent.com/875374/185273568-5aabac6a-0a9b-43e0-b1f4-80eee2733dd5.png)

![image](https://user-images.githubusercontent.com/875374/185273612-b621f0ab-cfef-42fa-8920-c449f7860400.png)

![image](https://user-images.githubusercontent.com/875374/185273643-e1ca8843-0015-4b2a-a82f-75125758d8f4.png)

**Environment**

 * OS:  docker on ubuntu server 20.04
 * ThingsBoard: release 3.3
 * Browser: chrome

**Comment by serfreeman1337** [comment]
You need to use "[change originator](https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator)" node and relationships.

Note that doc states: _If multiple Related Entities are found, only the first Entity is used as new originator_
So you need create different relationships types (eg Contains1, Contains2...).

1. Device A settings -> Relations -> Direction: From -> Add
    * Create different relationship types for devices you whis to send rpc to
 2. Place "change originator" node before "send rpc request" node
     * Originator source: Related
     * Direction: From
     * Relation filters type: fill in Contains1, Contains2 ...

**Comment by charlescui** [comment]
@serfreeman1337 Thanks A lot!

As you suggest, I make it work, Thanks! 
But another question, I must create each relation one by one. How can I batch send rpc for multi device of the same device-type, and no need create so many relations.

**Comment by serfreeman1337** [comment]
If you have PE edition you might try to use "[duplicate to group](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/transformation-nodes/#duplicate-to-group-node)" node, it does exactly what you want.

**Comment by charlescui** [comment]
@serfreeman1337 Thanks, you are professional of TB.
