### ISSUE TITLE
Can you split values of a device

### ISSUE THREAD

**Issue by info50** [thingsboard/thingsboard#7112]
My values are all coming from the same telemetry
values: [{'v': '1'}, {'v': '500'}, {'v': '428'}, {'v': '75'}, {'v': '805'}, {'v': '8'}, {'v': '78'}, {'v': '55'}, {'v': '326'}]. these are all different values
and my question is if you can separate these values using a new widget or also using rule chains. 
Any suggestions?
Thank you in advance.

**Comment by serfreeman1337** [comment]
It should be possible with upcoming "[split array msg](https://github.com/thingsboard/thingsboard/pull/7103/files#diff-1e3eb6ae697e607c398c8d31db8b19ab0d9863ac1ae65510f78a0935a53b14b6R42)" node.
It also possible to create such logic in the rulechain using "script" nodes.

**Comment by info50** [comment]
> It should be possible with upcoming "[split array msg](https://github.com/thingsboard/thingsboard/pull/7103/files#diff-1e3eb6ae697e607c398c8d31db8b19ab0d9863ac1ae65510f78a0935a53b14b6R42)" node. It also possible to create such logic in the rulechain using "script" nodes.

Do you have an idea how it works with rule chains?

**Comment by serfreeman1337** [comment]
```
var ts = Date.now();
var data = msg.map(function(d, id) {
    return {
        ts: ts + id, 
        values: d
    };
});

return {
    msg: data, 
    metadata: metadata, 
    msgType: msgType
};
```

**Comment by info50** [comment]
> ```js
> var ts = Date.now();
> var data = msg.map(function(d, id) {
>     return {
>         ts: ts + id, 
>         values: d
>     };
> });
> 
> return {
>     msg: data, 
>     metadata: metadata, 
>     msgType: msgType
> };
> ```

I get this error: java.util.concurrent.ExecutionException: javax.script.ScriptException: TypeError: msg.map is not a function in at line number 8

**Comment by serfreeman1337** [comment]
Can you turn on "Debug mode" for this node and then post "Data" contents from "Events" tab ?

**Comment by info50** [comment]
{
    "values": "[{\u0027v\u0027: \u002714\u0027}, {\u0027v\u0027: \u00270\u0027}, {\u0027v\u0027: \u00274E28\u0027}, {\u0027v\u0027: \u002796\u0027}, {\u0027v\u0027: \u0027A807\u0027}, {\u0027v\u0027: \u0027BA\u0027}, {\u0027v\u0027: \u0027E2F\u0027}, {\u0027v\u0027: \u00273EC\u0027}, {\u0027v\u0027: \u0027BA\u0027}]"
}
this is what i get if i debug

**Comment by info50** [comment]
java.util.concurrent.ExecutionException: javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:2 Expected , or } but found '
[{'v': '15'}, {'v': '0'}, {'v': '4E24'}, {'v': 'E'}, {'v': 'A807'}, {'v': 'BA'}, {'v': 'C92'}, {'v': '2E'}, {'v': 'BA'}]
  ^ in <eval> at line number 12
	at org.thingsboard.server.service.script.AbstractNashornJsInvokeService.lambda$doInvokeFunction$1(AbstractNashornJsInvokeService.java:163)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by serfreeman1337** [comment]
I've updated my last comment. Looks like "values" field contains invalid json string. Correct json should use double quotes. 
It will work if we replace all ' with " using `msg.values.replaceAll('\'','"')`.

**Comment by info50** [comment]
Now I have a telemetry in which is always a different value. But I would like each 'v' to have its own telemetry with a new name. is that possible?
example:
{"values":[{"v":"15"},{"v":"0"},{"v":"4E24"},{"v":"10"}]}
KDY = 15
SAL = 0
SYS = 4E24
IDC = 10

**Comment by serfreeman1337** [comment]
Yes, here is an example:

```javascript
if (!('values' in msg))
    return { msg: msg, metadata: metadata,  msgType: msgType };

var data = JSON.parse(msg.values.replaceAll('\'','"'));

data = {
    "KDY": data[0].v,
    "SAL": data[1].v,
    "SYS": data[2].v,
    "IDC": data[3].v
};

return {
    msg: data, 
    metadata: metadata, 
    msgType: msgType
};
```

**Comment by info50** [comment]
Thank you very much appreciate it

**Comment by sambhavjain98** [comment]
> Example "script" transformation node:
> 
> ```js
> var ts = Date.now();
> var data = msg.map(function(d, id) {
>     return {
>         ts: ts + id, 
>         values: d
>     };
> });
> 
> return {
>     msg: data, 
>     metadata: metadata, 
>     msgType: msgType
> };
> ```
> 
> This will add timestamps to values. Timestamps are 1ms diff, so "save timeseries" node will able to tell them apart and save all of them in one go. Example output:
> 
> ```json
> [
>   {
>       "ts": 1660811736985,
>       "values": {
>           "v": "1"
>       }
>   }, 
>   {
>       "ts": 1660811736986,
>       "values": {
>           "v": "500"
>       }
>   }, 
>   {
>       "ts": 1660811736987,
>       "values": {
>           "v": "428"
>       }
>   },
>   ...
> ]
> ```
> 
> But it seems like "Timeseries table" widget is not working well in realtime with that approach. You will only get latest value in realtime, but once you hit F5 all of them will appear on the table.
> 
> it possible to fix realtime updates by successively calling "save timeseries" node, but it not very clean (too much ctrl+c ctrl+v)

Hello @serfreeman1337 , 
We are using the Timeseries table widget, and we are pushing data to save time series in format 
`[{
    "ts": 1669044495658,
    "values": {
        "val1": 155,
        "val2": 471
    }
}, {
    "ts": 1669044497658,
    "values": {
        "val1": 43,
        "val2": 397
    }
}, {
    "ts": 1669044501658,
    "values": {
        "val1": 5,
        "val2": 197
    }
}, {
    "ts": 1669044504658,
    "values": {
        "val1": 96,
        "val2": 176
    }
}]`

though the timestamps are differentiated by seconds instead of ms, we see that it updates to the latest values. Only after refresh, it separates out. 
Please elaborate and how we could mitigate this, with the method you were suggesting. If @ashvayka  has any idea on how to make it real-time. 

Is there a way we can rather split the JSON objects and then send one by one to the Save timeseries node.
