### ISSUE TITLE
[Question] Rule Chain: Update Attribute and Delete relation 

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7114]
**Component**

 * Rule Engine

**Description**
Hello Thingsboard community. I am created my first rule chains and I would like to continue and make one which should:

1. Detect a change in server attribute active (determined by Thingsboard) - When value changes to false - returns false.
2. Deletes existing cointains relation. 

I am struggling with detecting that attribute change and sending related msg.

Thanks in advance for every tip!

**Environment**

 * OS:  Win

**Comment by serfreeman1337** [comment]
1. There is "Activity Event", "Inactivity Event" links from "message type switch" node. They both set "active" server attribute.
"Inactivty Event" link will mean that "active" is false.
2. There is "delete relation" node.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
