### ISSUE TITLE
[Question] When ThingsBoard was packaged as a TV app, the widget failed to load

### ISSUE THREAD

**Issue by yaodadaa** [thingsboard/thingsboard#7115]
**Component**

 * UI

**Description**
I packaged ThingsBoard as an app to run on the TV，Dashboards with custom widgets reported an error.(This dashboard is fine when you run it on your computer)
However, the dashboard with the widgets that come with ThingsBoard works fine.
How should I handle this error？
![image](https://user-images.githubusercontent.com/55545124/185553223-b1b8ac19-b1bc-49f7-b6a9-ecd68bf73fdb.png)

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by epalchenko** [comment]
Most likely the browser on your TV does not support some of the scripts on the widget you are talking about. please tell us in more detail how you achieved this. are you running a flutter-app or a browser?
