### ISSUE TITLE
[Question] Is it possible to set up alarms for integrations?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#7125]
**Component**

 * Rule Engine

**Description**
How can I set up an alarm for an integration? I want to know if no data has come through an integration in x minutes. I know this can be done for specific devices but I would like to do it for an entire integration.

**Environment**
 * OS:  Linux
 * ThingsBoard: cloud
 * Browser: FireFox

**Comment by Butanding** [comment]
I have the same question. Could you find a solution for this?
For example i have an integration with Attributes {INTEGRATION_NAME}_messagesCount. I want to send an alarm, whenever the message count drops below certain value.

![image](https://user-images.githubusercontent.com/23176308/208457532-b59be7ec-c8f0-4890-a90c-ba6bca3dfb54.png)

And the Integration Value XXX_messagesCount gets an update like every hour (?!). So where can i catch this update message and trigger an alarm? That I could then route to the Alarm Nodes.

But i could not find the message from any integration in root rule chain or any other rule chain. Even in thingsboard.log i could not find any log related to this attribute.

The only thing i thought is, that i could use a generator to ask for the current value of _messagesCount every hour, but that sounds kind of dirty.

Any ideas?

Thanks!

**Comment by ssakharova** [comment]
Hello @OzyOzk,

The Thingsboard does not provide the option to set up alarms for integrations. 

Best regards,
Sofiia
