### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by laxmiprasannaBorigi** [thingsboard/thingsboard#7126]
Server attributes are not working through rule chain 

 * Generic

**Description**
I have a feature where i need to create some server attributes for a device when it is created. So i created a rule chain to create those attributes. And based on the attribute value(true/false) i should generate an alarm. When i created the server attribute through rule chain that is not working(means alarm is not generating) until i update value in device server attributes. Or if i create the server attribute manually then alarm is generating. So to create server attribute through rule chain do we need to do any extra configurations to make it work? 

**Environment**
 * OS:  linux
 * ThingsBoard: 3.3.4.1

**Comment by devaskim** [comment]
By design there is no additional rule chain notification about attribute was created/update from within rule chain. So you need to restructure your chains to cover such case manually.

**Comment by laxmiprasannaBorigi** [comment]
here my problem is attributes are not working through rule chain.. if i create manually or after update the created attributes from rule chain it is working..
Do we need to do any configurations for the attributes we create from rule chain?

**Comment by devaskim** [comment]
To create or update attribute from rule chain you need at least two nodes: (1) Transformation node and (2) Save attributes node.
(1) In script windows add something like
```
return {msg: { 'YOUR_ATTR_NAME' : 12345 }, metadata: metadata, msgType: 'POST_ATTRIBUTES_REQUEST'};
```
(2) Select _Server attributes_ option

**Comment by laxmiprasannaBorigi** [comment]
Working fine with solution provided
