### ISSUE TITLE
[Question] Dashboard - How to use/update the Dashboard state widget?

### ISSUE THREAD

**Issue by raomin** [thingsboard/thingsboard#7133]
**Component**

 * UI
 (Dashboard)

**Description**
I have a list of devices associated in the current asset dashboard.
I would like that selecting one device displays the details of the selected device **in the same dashboard**, not in a new state dashboard.
I imagined that the proper way of doing it is to use the _Dashboard state widget_ for the state of SelectedDevice.

Thing is what action should I set on the Entities table widget of devices to only update the _Dashboard state widget_? 
If I put _Update current dashboard state_ I end up on the detailed view of the device. 

![image](https://user-images.githubusercontent.com/4460208/186037743-d7b3676c-7b9b-4843-b3c6-1324fde89e39.png)

Should I use a custom action?

**Comment by raomin** [comment]
Eventually, I linked the _Dashboard state widget_ to an Alias with device filter and created a custom action on the device list that updates the alias filter with the devicename selected...
I guess there is a straighter way. But in case people are interested, that's my action code:

```js
widgetContext.aliasController.entityAliases['48714e11-1d4a-a630-6d86-39e9a17e0f63'].filter.deviceNameFilter=entityName
widgetContext.updateAliases();
```

**Comment by raomin** [comment]
The issue is, it doesn't get reset when I go to another asset dashboard...

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
