### ISSUE TITLE
[Bug] thingsboard_tb_1 exited with code 0

### ISSUE THREAD

**Issue by xiaopingcs** [thingsboard/thingsboard#7136]
**Describe the bug**
Cannot reproduce this test: https://thingsboard.io/docs/reference/performance-aws-instances/#scenario-e
two issues:
1. thingsboard_tb_1 exited with code 0
2. instruction link is missing (https://thingsboard.io/docs/reference/performance/performance-test-tool/)

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment: docker deployment
  * ThingsBoard Version  3.4.3
  * OS Name and Version  Ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: MacOS Monterey 12.5
* Browser: Chrome
* Version: 3.4.3

**To Reproduce**
1. set update docker and docker-compose environment in ubuntu 20.04
2. Go to 'https://thingsboard.io/docs/reference/performance-aws-instances/#scenario-e'
3. download docker-compose.yml file
4. copy docker-compose.yml to  /data/thingsboard
5. run docker-compose up
6. see error: "Caused by: java.lang.IllegalStateException: Cannot load driver class: org.hsqldb.jdbc.JDBCDriver"

**Expected behavior**
thingsboard_tb_1 should run peacefully

**Screenshots**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/65699335/186139020-45868712-ce3b-43bf-950a-97be1c959406.png">
<img width="819" alt="image" src="https://user-images.githubusercontent.com/65699335/186139455-34945fc9-04a2-4605-9716-2974f8884c1c.png">

**Additional context**

**Comment by xiaopingcs** [comment]
Hi, @ashvayka @vvlladd28 can you help?

**Comment by ban2derlog** [comment]
Hello,
Please add here what YML you use for Performance Test.}
And also specify your setup fully, because at this moment there is no `ThingsBoard Version 3.4.3`
Last one is 3.4.1

**Comment by xiaopingcs** [comment]
> Hello, Please add here what YML you use for Performance Test. And also specify your setup fully, because at this moment there is no `ThingsBoard Version 3.4.3` Last one is 3.4.1

Here is the yml file:
`version: '3'
services:
  cassandra:
    image: bitnami/cassandra:4.0
    network_mode: "host"
    restart: "always"
    volumes:
      - cassandra:/bitnami
    environment:
      CASSANDRA_CLUSTER_NAME: "ThingsBoard Cluster"
      HEAP_NEWSIZE: "4096M"
      MAX_HEAP_SIZE: "8192M"
      JVM_EXTRA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199  -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    network_mode: "host"
    restart: "always"
    volumes:
      - zookeeper:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_ADMIN_SERVER: "no"
      JVMFLAGS: "-Xmx128m -Xms128m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9199 -Dcom.sun.management.jmxremote.rmi.port=9199  -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
  kafka:
    image: docker.io/bitnami/kafka:3
    network_mode: "host"
    restart: "always"
    volumes:
      - kafka:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "localhost:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
      JMX_PORT: "1099"
    depends_on:
      - zookeeper
  postgres:
    image: "postgres:14"
    network_mode: "host"
    restart: "always"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "thingsboard"
      POSTGRES_PASSWORD: "postgres"
  tb:
    depends_on:
      - postgres
      - kafka
      - cassandra
    image: "thingsboard/tb"
    network_mode: "host"
    restart: "always"
    volumes:
      - thingsboard-data:/data
      - thingsboard-logs:/var/log/thingsboard
    environment:
      DATABASE_TS_TYPE: "cassandra"
      DATABASE_TS_LATEST_TYPE: "sql"
      #Cassandra
      CASSANDRA_CLUSTER_NAME: "ThingsBoard Cluster"
      CASSANDRA_LOCAL_DATACENTER: "datacenter1"
      CASSANDRA_KEYSPACE_NAME: "thingsboard"
      CASSANDRA_URL: "127.0.0.1:9042"
      CASSANDRA_USE_CREDENTIALS: "true"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
      CASSANDRA_QUERY_BUFFER_SIZE: "200000"
      CASSANDRA_QUERY_CONCURRENT_LIMIT: "1000"
      CASSANDRA_QUERY_POLL_MS: "5"
      #Kafka
      TB_QUEUE_TYPE: "kafka"
      TB_KAFKA_BATCH_SIZE: "65536" # default is 16384 - it helps to produce messages much efficiently
      TB_KAFKA_LINGER_MS: "5" # default is 1
      TB_QUEUE_KAFKA_MAX_POLL_RECORDS: "2048" # default is 8192
      TB_SERVICE_ID: "tb-node-0"
      HTTP_BIND_PORT: "8080"
      TB_QUEUE_RE_MAIN_PACK_PROCESSING_TIMEOUT_MS: "30000"
      # Postgres connection
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/thingsboard"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      # Cache specs
      CACHE_SPECS_DEVICES_MAX_SIZE: "512000" # default is 10000
      CACHE_SPECS_DEVICE_CREDENTIALS_MAX_SIZE: "512000" # default is 10000 
      CACHE_SPECS_SESSIONS_MAX_SIZE: "512000" # default is 10000
      TS_KV_PARTITIONS_MAX_CACHE_SIZE: "3000000" # default is 100000
      # Device state service
      DEFAULT_INACTIVITY_TIMEOUT: "1800" # defailt is 600 (10min)
      DEFAULT_STATE_CHECK_INTERVAL: "600" # default is 60 (1min)
      PERSIST_STATE_TO_TELEMETRY: "true" # Persist device state to the Cassandra. Default is false (Postgres, as device server_scope attributes)
      # Java options for 16G instance and JMX enabled
      JAVA_OPTS: " -Xmx8192M -Xms8192M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
volumes: # to persist data between container restarts or being recreated
  cassandra:
  kafka:
  zookeeper:
  postgres:
  thingsboard-data:
  thingsboard-logs:`


the issue "Cannot load driver class: org.hsqldb.jdbc.JDBCDriver" has been fixed by adding two environment variables:
**SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/thingsboard"
SPRING_DATASOURCE_USERNAME: "postgres"**

but there is a new issue now: tb is not able to connect to cassandra 
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/65699335/187130700-362fddd4-67eb-45be-b3c3-909b009115aa.png">

**Comment by xiaopingcs** [comment]
Everything works for me now.
I did following things:

1. add two environment variables in docker-compose.yml (SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/thingsboard" SPRING_DATASOURCE_USERNAME: "postgres")
2. after docker-compose down, docker-compose rm, remove docker volume data (which can be found by using docker volume ls), docker-compose up
