### ISSUE TITLE
[Question] Widgets keeps spinning/loading and never show the data

### ISSUE THREAD

**Issue by borstenhirse** [thingsboard/thingsboard#7137]
**Component**

 * UI

**Description**
I have a dashboard with a chart widget showing last 5 minutes some sensor data. It has worked well for more than 5 months and the database time-series tables is already almost 50 GB. Recently, however, when open a dashboard with a chart widget, the widget keeps loading and never shows data, as shown in the attached screenshot. 

In the debug window of Firefox (and Chrome), I see no network traffic. I also manually query the Postgresql DB on the latest time-series table (~2GB), the results are returned immediately almost. 

So what could the reason to the infinite loading of the widget?

**Environment**

 * OS:  Ubuntu LTS 20.04
 * ThingsBoard: 3.2
 * Browser: Firefox 102, Google Chrome 103.0.5060.134.
![Screenshot_20220823_111221](https://user-images.githubusercontent.com/111867016/186156501-41a0dbd8-5046-4d71-b6eb-e9037bd49cc7.png)

**Comment by borstenhirse** [comment]
Thanks @pon0marev. We also found that changing the option 'spring.jpa.properties.hibernate.order_by.default_null_ordering' to 'none' results in a performance boost.

**Comment by pon0marev** [comment]
Yes, you can enable this option to increase performance, but I recommend to upgrade because on this version it is experimental config and it has not been tested.
