### ISSUE TITLE
How can I get a list of entities by entity group ID?

### ISSUE THREAD

**Issue by ChristopheD31** [thingsboard/thingsboard#7138]
**Component**

 * UI

**Description**
Hello community,

I'm trying to fetch all entities from a specific entity group so I can populate a custom dropdown in a widget custom action with html template.

The issue #5976 is the only thing I have found that helped me, since @ashvayka exposes a service which is in PE source code. According to this issue, I would probably need to call a method like _getEntitiesByGroupId()_ from the _entityGroupService_..? Does a method like this exists, or maybe in another service?

While being here, is there a way to have access to the documentation of other functions from PE-only services and classes? The autocomplete in the widget action editor really helped me until now, but it does not cover classes and services from PE edition. 

Thank you in advance!! :)

**Environment**

 * OS:  Windows 10
 * ThingsBoard: Thingsboard PE Cloud
 * Browser: Brave 1.42.97

**Comment by pon0marev** [comment]
The community documentation will probably help you: https://github.com/thingsboard/thingsboard/issues/9899
