### ISSUE TITLE
I can't import plugins，invalid-plugin-file-error

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#714]
When I import Kafka or other extendsion plug-in, I can't import plugins: the plug-in data structure is invalid.
As explained, I added the POM dependency of the related plug-in。

**Comment by mp-loki** [comment]
Hi @caoyingde . Can you please provide the file that you are trying to import? Are you importing it on the right page? I have just tried to import [this plugin](https://thingsboard.io/docs/samples/analytics/resources/kafka_plugin_for_spark_streaming_sample.json) and it worked just fine

**Comment by caoyingde** [comment]
It's been settled. Thank you.
