### ISSUE TITLE
[Question] Google Login via OAuth2 enabled but no google option on login screen - multi-tenant TB PE setup

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#7142]
**Component**
 * Generic

**Description**
First time submitting a question here so I hope I'm doing it right.

I've spent about 2 days now trying to configure our multi-tenant TB PE application to use OAuth2 via google identity, but no matter what I try, the option does not appear on the login screen. I've enabled OAuth2 as sysadmin and set up the redirect URI, client ID and secret, as well as other options. Nothing will make the google option appear on the login screen. 

I also checked to verify there is no custom CSS hiding the element, that there is no special code in any of the white label setups, and about a hundred other things. What am I missing? 

The following tables are empty except "client_registration_template" and "oauth2_registration," which have template info and the info I configured as sys admin, respectively.

 public | oauth2_client_registration           | table             | postgres | permanent   | 0 bytes    | 
 public | oauth2_client_registration_info      | table             | postgres | permanent   | 8192 bytes | 
 public | oauth2_client_registration_template  | table             | postgres | permanent   | 48 kB      | 
 public | oauth2_domain                        | table             | postgres | permanent   | 8192 bytes | 
 public | oauth2_mobile                        | table             | postgres | permanent   | 8192 bytes | 
 public | oauth2_params                        | table             | postgres | permanent   | 8192 bytes | 
 public | oauth2_registration                  | table             | postgres | permanent   | 16 kB      | 

I suspect this has something to do with white labeling and/or domains, but I feel like I've tried every possible combination and nothing worked. The docs are pretty sparse when it comes to explaining base URLs, URIs, and OAuth2. 

I've included port 443 in the base URL and URI, and I've tried without it. 
I've tried each of our whitelabel URLs individually, or all at once. 

Has anyone successfully dealt with this? Any pointers? 

**Environment**
 * OS:  All
 * ThingsBoard: 3.4.1, 3.3.4.1
 * Browser: All

**Comment by pon0marev** [comment]
Try enabling http+https mode and make sure that the domain name is correct. ![image](https://user-images.githubusercontent.com/44898346/186701637-55737a55-a197-455f-a03f-4157c81537b4.png) If you see a button when open login page with http://domainname:80, you have a proxy problem. If you are using CloudFront try to turn it off:
![image](https://user-images.githubusercontent.com/44898346/186702353-aa6c4d7c-fec8-47ad-966e-8b4e349d350a.png)

**Comment by Eric-Ruud** [comment]
Thanks @pon0marev 

I've definitely tried every possible setting for domains and redirect URIs. No matter what I put there, the button just doesn't appear. I've also tried setting up an Auth0 custom provider just to make sure there's nothing on the google side, also no button appearing. 

Sorry if I'm missing something basic but I don't know where to access the second window you mentioned. 

When I enter any port number, my browser automatically redirects me back to the same https connection without any port number.

I suspect that there is some issue with white labeling and domains, though. 

For one of our tenants, we use a subdomain of their domain.
We also use our own domain for other tenants. 

Is there something I need to add to white label login settings to make this work with a multitenant white labeled setup where multiple doimains are being used? I've already entered all of these domains in the Oauth2 configuration and double-checked for other possible missing settings in the config file.

**Comment by Eric-Ruud** [comment]
Is there any way to enable some debugging or logging to trace the exact issue?

**Comment by Eric-Ruud** [comment]
FYI use google's load balancer with http to https redirect, but we are not using any CDN or caching.

**Comment by pon0marev** [comment]
Try to disable http to https for a while and go to port 80. If the authorization button appears, you have a redirection problem

**Comment by Eric-Ruud** [comment]
Thank you @pon0marev I think you are probably correct. I'm working with the team and will let you know how it goes!

**Comment by aistisdev** [comment]
I had this same issue while testing this functionality locally. The problem was that I did not add a port to the ip (localhost vs localhost:8080) and would not see the login button for the custom oauth2 login. 

Inspecting the login page network calls showed no errors, so I was very confused. @pon0marev maybe it would be possible to not fail silently? The sysadmin email section has a "test" function, which let's you see if everything is ok, could maybe be good to have one for oauth2 too.

**Comment by Eric-Ruud** [comment]
That is not the same issue we experienced, @aistisdev . Even when adding the port it didn't work. I do agree that there should be some better error logging here.

**Comment by Eric-Ruud** [comment]
After further troubleshooting, it appears that the issue was that SSL over HTTP isn't working properly. 

The instructions here do not work for us. 
https://thingsboard.io/docs/pe/user-guide/ssl/http-over-ssl/

Is anyone having success with this method?

What we do now is we manually generate the SSL certs and add them per domain in our Thingsboard VM. Is there any reason we should not do this? Is there a better way?

**Comment by trikimiki** [comment]
Hi!

Another (arguably better) way to provide HTTP over SSL is by using load-balancer. Here is an example with HAProxy and ThingsBoard, which also includes Certbot to provision free certificates: https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/
