### ISSUE TITLE
Is it possible to get the thingsbaord from ubuntu to windows

### ISSUE THREAD

**Issue by info50** [thingsboard/thingsboard#7146]
I have installed Thingsboard on ubuntu and now i want to run it on windows, but I don't want to start over again

**Comment by trikimiki** [comment]
You can backup your DB on Ubuntu, and restore it to your DB on Windows.

**Comment by KenSense** [comment]
I moved from Windows to Ubuntu, same database.
But it's strongly recommended for PE to use Ubuntu instead of Windows so I would keep your setup.
