### ISSUE TITLE
[Question] Is it possible to limit which widgets / dashboard states a customer can see using permissions in TB-PE?

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#7149]
**Component**

 * UI

**Description**
I'm trying to limit how much a customer can see on the dashboard, i'd prefer not to create multiple dashboards since that becomes harder to maintain for the amount of devices & widgets per dashboard.
But some widgets have controls & views that I don't want the customer to use/see.
I did find out you can read permissions of the user in the widget, but there's seems to be no way to set a custom permission resource that I can check for.

**Environment**

 * OS:  PhotonOS
 * ThingsBoard: Thingsboard PE - 3.3.4.1PE running in a docker container
 * Browser: Chrome 104.0.5112.102

**Comment by Ultrazombie** [comment]
No way, you won't be able to differentiate widgets for different customers using RBAC or another standard ThingsBoard functionality.
