### ISSUE TITLE
how to add new field to device?

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#715]
i tried to add one more field to device 
but i cant update the sql db,
where is save device to sql file located?
 i think it has prototype in devicedao but i cant find the code

**Comment by mp-loki** [comment]
dao/src/main/resources/sql/

**Comment by gopirathnamt** [comment]
thanks bro i created

**Comment by mp-loki** [comment]
May I assume this issue resolved?

**Comment by gopirathnamt** [comment]
yes bro it is solved
