### ISSUE TITLE
[Question] How to deal with a list in JSON format coming from a REST API call (rule chain)

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#7151]
**Component**

 * Rule Engine

**Description**

I want to get data from our M2M simcards provider to create a dashboard inside TB. To do that I create a new device and build the rule chain bellow:

![rule_chain](https://user-images.githubusercontent.com/7483656/186740852-3ce24cde-9a8a-405f-b695-3c64a1d4b5bb.png)

The script node called get data returned a list of objects in JSON format.

`[{
        "iccid": "89550442000122017480",
        "phoneNumber": "5543999539958",
        "operator": "TIM",
        "device": "M1-003",
        "description": "BRK-BNU-NEMOS",
        "descriptionSec": "",
        "descriptionThi": "0.16.2",
        "descriptionFour": "",
        "ip": "10.160.2.11",
        "lastImei": "8659920373108778",
        "lastImeiVerification": "865992037310879",
        "lastApn": "datatem.tim.br",
        "lastIp": "10.160.2.11",
        "lastAuth": 1661363094000,
        "lastModified": 1659448107000,
        "connected": true,
        "monthAvailableData": 78756719,
        "monthUsedData": 25015461,
        "monthUsedDataPct": 24,
        "status": "ACTIVE"
    }, {
        "iccid": "89550442000122017498",
        "phoneNumber": "5546999715446",
        "operator": "TIM",
        "device": "M1-010",
        "description": "",
        "descriptionSec": "",
        "descriptionThi": "0.16.2",
        "descriptionFour": "",
        "ip": "10.160.31.62",
        "lastImei": "8656740387961578",
        "lastImeiVerification": "865674038796153",
        "lastApn": "datatem.tim.br",
        "lastIp": "10.160.31.62",
        "lastAuth": 1661337442000,
        "lastModified": 1659447851000,
        "connected": true,
        "monthAvailableData": 94310269,
        "monthUsedData": 10546632,
        "monthUsedDataPct": 10,
        "status": "ACTIVE"
    }, {
        "iccid": "89550442000122245347",
        "phoneNumber": "5548999045967",
        "operator": "TIM",
        "device": "M1-002",
        "description": "PERIPRO-FONTE",
        "descriptionSec": "THINGSBOARD",
        "descriptionThi": "0.16.2",
        "descriptionFour": "",
        "ip": "10.160.1.93",
        "lastImei": "8656910343692178",
        "lastImeiVerification": "865691034369215",
        "lastApn": "datatem.tim.br",
        "lastIp": "10.160.1.93",
        "lastAuth": 1661337134000,
        "lastModified": 1659447137000,
        "connected": true,
        "monthAvailableData": 85662163,
        "monthUsedData": 19034147,
        "monthUsedDataPct": 18,
        "status": "ACTIVE"
    }]`

My difficulty is how I can split the list of objects and save this values inside TB to build a dashboard ?
How I can build a structure inside TB to receive these data, save and use it inside TB in the best way.

**Environment**

 * ThingsBoard: ThingsBoard Cloud Prototype
 * Browser: Microsoft Edge version 104.0.1293.63

**Comment by Backdraft007** [comment]
It is an array of JSON objects. You can loop the array in your transormation script.

**Comment by lstarke** [comment]
Hello @Backdraft007, thank you for you reply.

Yes I can but I dont get how take each object and send to a specific device or asset. I'm thinking in how to build a dash with this data. Inside the dash I have to specify a entity and its variables.

If you check my JSON, each item from the list are data from a specific SIMCard, so, in my opinion each SIMCard must be a entity inside TB with hes data as telemetries.

Does it make sence ?

**Comment by Backdraft007** [comment]
Can you try this code in a transormation script and after the script Save timeseries node.

`var test = msg;

var msg = {};

var length = test.length,
    element = null;
for (var i = 0; i < length; i++) {
  element = test[i];
    msg.iccid = element['iccid'];
    msg.monthUsedData = element['monthUsedData'];
    metadata.deviceName = element['device'];
    return {msg: msg, metadata: metadata, msgType: msgType};
}`

**Comment by lstarke** [comment]
Hello @Backdraft007, thank you.

I think I have found a alternative similar yours.

See bellow how I did:

That's my final rule chain.

![2022-08-29 14_09_40-Window](https://user-images.githubusercontent.com/7483656/187256295-1b2d4f27-5df1-4d22-9261-991f98d47256.png)

Inside get data script  write this code:

```
var obj = {};
for (let i = 0; i < msg.length; i++) {
    var device = msg[i].device;
    obj[device] = msg[i];
}
return {msg: obj, metadata: metadata, msgType: msgType};
```
To add a key to each object so this key can be selected inside dashboard.

[{"M1-003" :{
        "iccid": "89550442000122017480",
        "phoneNumber": "5543999539958",
        "operator": "TIM",
        "device": "M1-003",
        "description": "BRK-BNU-NEMOS",
        "descriptionSec": "",
        "descriptionThi": "0.16.2",
        "descriptionFour": "",
        "ip": "10.160.2.11",
        "lastImei": "8659920373108778",
        "lastImeiVerification": "865992037310879",
        "lastApn": "datatem.tim.br",
        "lastIp": "10.160.2.11",
        "lastAuth": 1661518229000,
        "lastModified": 1659448107000,
        "connected": true,
        "monthAvailableData": 77898846,
        "monthUsedData": 26958564,
        "monthUsedDataPct": 26,
        "status": "ACTIVE"
    }},{"M1-010": {
        "iccid": "89550442000122017498",
        "phoneNumber": "5546999715446",
        "operator": "TIM",
        "device": "M1-010",
        "description": "",
        "descriptionSec": "",
        "descriptionThi": "0.16.2",
        "descriptionFour": "",
        "ip": "10.160.31.62",
        "lastImei": "8656740387961578",
        "lastImeiVerification": "865674038796153",
        "lastApn": "datatem.tim.br",
        "lastIp": "10.160.31.62",
        "lastAuth": 1661490049000,
        "lastModified": 1659447851000,
        "connected": true,
        "monthAvailableData": 67508828,
        "monthUsedData": 37083010,
        "monthUsedDataPct": 35,
        "status": "ACTIVE"
  }}]

In the image bellow you can see how it appears inside device telemetries.

![2022-08-29 14_24_33-Window](https://user-images.githubusercontent.com/7483656/187261051-f23c73a1-2aa6-4130-996a-ff90922b9f1e.png)


And finally  I can accees each item as "device" inside the dashboard builder.

![2022-08-29 14_32_19-Window](https://user-images.githubusercontent.com/7483656/187262744-66f4f7c8-a912-4c18-a543-b3bc9b164c1f.png)
![2022-08-29 14_32_41-Window](https://user-images.githubusercontent.com/7483656/187262746-85752817-03f5-47cb-bf23-e7c32cf47876.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
