### ISSUE TITLE
[Question] widget compile error 

### ISSUE THREAD

**Issue by langlichong** [thingsboard/thingsboard#7152]
**Description**
  1. when to add widget to dashboard , chrome console logs : 
     errorMessages: (2) ['Failed to load default widget types!', 'Failed to compile widget html. \n Error: JIT compiler unavailable']
     widgetInfo: {type: 'latest', widgetName: 'Error loading widget', alias: 'error', sizeX: 8, sizeY: 6

**Comment by pon0marev** [comment]
What version of thingsboard do you have? What widget do you add? Do you get this error when adding any widget or a specific one? Does it happen when adding a widget to a specific dashboard or to any dashboard?
