### ISSUE TITLE
Adding three telemetry datas together

### ISSUE THREAD

**Issue by info50** [thingsboard/thingsboard#7153]
Hello,
I want to add three telemetry data together and then save them in a new telemetry is this possible with rule nodes?
P1+P2+P3 = P_ges

**Comment by Backdraft007** [comment]
Did you get the three telemetry data in one message?
Then you can use the transformation script. https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node

**Comment by info50** [comment]
No they are seperate messages
I have already tried this but it does not work

> Did you get the three telemetry data in one message? Then you can use the transformation script. https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node

**Comment by ashaforost** [comment]
Hi @info50 

Check out our guide on telemetry calculation from two devices. [Data function based on telemetry from 2 devices](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/function-based-on-telemetry-from-two-devices/)
I believe this solution is easily scalable for more devices and different calculations.

**Comment by KenSense** [comment]
You can get the last values with originator telemetry node.
Then in the script you have all needed values
You will need to check which variable is present in the message like
var P1present = typeof msg.P1 !== 'undefined';

**Comment by info50** [comment]
> You can get the last values with originator telemetry node. Then in the script you have all needed values You will need to check which variable is present in the message like var P1present = typeof msg.P1 !== 'undefined';
> 
> Those that are not present you replace with the last value before adding it.

how do you use the orginator telemetry  node?

**Comment by KenSense** [comment]
in your case I would list keys P1 P2, P3 and set to 'Last'

If you only need the sum in a Widget you can also just add them in the widget (and not store it in the database.)

**Comment by info50** [comment]
I have already made the sum in a widget but my problem is that the widget only updates when I am in the dashboard

**Comment by info50** [comment]
how looks your script?

**Comment by KenSense** [comment]
I cannot share this code but you got all you need I think.
You have something like
if (P1Present) {
    var P1 = msg.P1;
} else {
    var P1 = metadata.cs_P1;
}

Use the debug feature to see what is going in and out.

**Comment by Civilduino** [comment]
How do you sum up several time series data keys inside the widget? I cannot find that option, could you please show a screenshot?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
