### ISSUE TITLE
[Question] Edit alarm rules without access to device profile UI

### ISSUE THREAD

**Issue by DaiNgocVu** [thingsboard/thingsboard#7154]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Can I custom an HTML form for edit condition value of alarm rule instead of access to device profiles UI? Thank you.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by Backdraft007** [comment]
You can use the dynamic thresholds.
https://thingsboard.io/docs/user-guide/device-profiles/#example-7-dynamic-thresholds-based-on-the-tenant-or-customer-attributes
So, you can add a widget where the user can change the attributes.

**Comment by DaiNgocVu** [comment]
Exactly what i needed. Thank you!
