### ISSUE TITLE
[Question]  [WiFiEsp] Cannot initialize ESP module

### ISSUE THREAD

**Issue by isochizo** [thingsboard/thingsboard#7161]
--------------- CUT HERE FOR EXCEPTION DECODER ---------------
[WiFiEsp] Initializing ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Cannot initialize ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
 WiFi shield not present
 --------------- CUT HERE FOR EXCEPTION DECODER ---------------

I am trying to send data from DHT22 to ThingsBoard using Wemos D1. Sketch was obtained from 

https://thingsboard.io/docs/samples/arduino/temperature/

Libraries were installed as per sketch

Anyone can assist me on this?

**Comment by ban2derlog** [comment]
Hi, are you sure that there isn't any blockers between ESP and ThingsBoard Instance?
Do you check ThignsBoard logs for connection\errors?
