### ISSUE TITLE
[Question] Rule Engine - Timeout to process [X] messages

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#7164]
**Component**

 * Rule Engine

**Description**
Timeout to process [X] messages show in log file, why it happens and how to fix it?

```
2022-08-29 16:46:24,552 [tb-rule-engine-consumer-46-thread-23 | Main-6] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - Timeout to process [4] messages
```
![image](https://user-images.githubusercontent.com/7221781/187168168-40b8c162-72cf-450c-b7cd-1f5ffd22bb58.png)

**Environment**

 * OS:  Ubuntu 20.04 Server Edtion
 * ThingsBoard: CE 3.3.4.1
 * Browser: N/A

**Comment by maksonlee** [comment]
Thanks for the explanation, i tried to enable the debug mode for relevant rule node but can't see any related error.

So i guess i need to increase the queue timeout setting now.

**Comment by remzisahinoglu** [comment]
did you increase the queue timeout settings? if you did, can you share how to.
