### ISSUE TITLE
Add asset and create relationship 

### ISSUE THREAD

**Issue by LucasArrillaga** [thingsboard/thingsboard#7166]
Component
   Generic

Description
   Add asset and create relationship with panel state entity - Custom action (with HTML template)
   I don't want to select the relationship but use the panel state entity and create a relationship with the created asset

The code 

JS Function

function ($event, widgetContext, entityId, entityName, htmlTemplate, additionalParams, entityLabel) {

let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let assetService = $injector.get(widgetContext.servicesMap.get('assetService'));
let deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
let entityRelationService = $injector.get(widgetContext.servicesMap.get('entityRelationService'));

openAddEntityDialog();

function openAddEntityDialog() {
  customDialog.customDialog(htmlTemplate, AddEntityDialogController).subscribe();
}

function AddEntityDialogController(instance) {
  let vm = instance;

  vm.allowedEntityTypes = ['ASSET', 'DEVICE'];
  vm.entitySearchDirection = {
    from: "FROM",
    to: "TO"
  }

  vm.addEntityFormGroup = vm.fb.group({
    entityName: ['', [vm.validators.required]],
    entityType: ['ASSET'],
    entityLabel: [null],
    type: ['Potrero', [vm.validators.required]],
    attributes: vm.fb.group({
      hectareas: [null]
    }),
    relations: vm.fb.array([])
  });

  vm.cancel = function () {
    vm.dialogRef.close(null);
  };

  vm.relations = function () {
      //console.log('usando vm.relations');
    return vm.addEntityFormGroup.get('relations');
  };

  vm.addRelation = function () {
      console.log("usando funcion addRelation");
    vm.relations().push(vm.fb.group({
      relatedEntity: [null, [vm.validators.required]],
      relationType: ['Contains', [vm.validators.required]],
      direction: ['TO', [vm.validators.required]]
    }));
  };

  vm.removeRelation = function (index) {
    vm.relations().removeAt(index);
    vm.relations().markAsDirty();
  };

  vm.save = function () {
      console.log("usando funcion save");
    vm.addEntityFormGroup.markAsPristine();
    saveEntityObservable().subscribe(
      function (entity) {
        widgetContext.rxjs.forkJoin([
          saveAttributes(entity.id),
          saveRelations(entity.id)
        ]).subscribe(
          function () {
            widgetContext.updateAliases();
            vm.dialogRef.close(null);
          }
        );
      }
    );
  };

  function saveEntityObservable() {
    const formValues = vm.addEntityFormGroup.value;
    let entity = {
      name: formValues.entityName,
      type: formValues.type,
      label: formValues.entityLabel
    };
    if (formValues.entityType == 'ASSET') {
        console.log('guardado entidad');
        console.log(assetService.saveAsset(entity));
      return assetService.saveAsset(entity);
    } else if (formValues.entityType == 'DEVICE') {
      return deviceService.saveDevice(entity);
    }
  }

  function saveAttributes(entityId) {
    let attributes = vm.addEntityFormGroup.get('attributes').value;
    let attributesArray = [];
    for (let key in attributes) {
      if (attributes[key] !== null) {
        attributesArray.push({key: key, value: attributes[key]});
      }
    }
    if (attributesArray.length > 0) {
      return attributeService.saveEntityAttributes(entityId, "SERVER_SCOPE", attributesArray);
    }
    return widgetContext.rxjs.of([]);
  }

  function saveRelations(entityId) {
      console.log("usando funcion saveRelations");
      console.log(entityId);
    let relations = vm.addEntityFormGroup.get('relations').value;
    console.log("relacion formulario");
    console.log(relations);
    let tasks = [];
    for (let i = 0; i < relations.length; i++) {
      let relation = {
        type: relations[i].relationType,
        typeGroup: 'COMMON'
      };
      if (relations[i].direction == 'FROM') {
        relation.to = relations[i].relatedEntity;
        relation.from = entityId;
      } else {
        relation.to = entityId;
        relation.from = relations[i].relatedEntity;
      }
      console.log(relation);
      tasks.push(entityRelationService.saveRelation(relation));
    }
    if (tasks.length > 0) {
      return widgetContext.rxjs.forkJoin(tasks);
    }
    return widgetContext.rxjs.of([]);
  }
}
}

HTML

<form #addEntityForm="ngForm" [formGroup]="addEntityFormGroup"
      (ngSubmit)="save()" class="add-entity-form">
  <mat-toolbar fxLayout="row" color="primary">
    <h2>Crear Potrero</h2>
    <span fxFlex></span>
    <button mat-icon-button (click)="cancel()" type="button">
      <mat-icon class="material-icons">cerrar</mat-icon>
    </button>
  </mat-toolbar>
  <mat-progress-bar color="warn" mode="indeterminate" *ngIf="isLoading$ | async">
  </mat-progress-bar>
  <div style="height: 4px;" *ngIf="!(isLoading$ | async)"></div>
  <div mat-dialog-content fxLayout="column">
    <div fxLayout="row" fxLayoutGap="8px" fxLayout.xs="column"  fxLayoutGap.xs="0">
      <mat-form-field fxFlex class="mat-block">
        <mat-label>Nombre Potrero</mat-label>
        <input matInput formControlName="entityName" required>
        <mat-error *ngIf="addEntityFormGroup.get('entityName').hasError('required')">
          El nombre es requerido.
        </mat-error>
      </mat-form-field>

    </div>

    <div formGroupName="attributes" fxLayout="column">
      <div fxLayout="row" fxLayoutGap="8px" fxLayout.xs="column"  fxLayoutGap.xs="0">
        <mat-form-field fxFlex class="mat-block">
          <mat-label>Hectareas</mat-label>
          <input type="number" step="any" matInput formControlName="hectareas">
        </mat-form-field>

      </div>

    </div>

    <div class="relations-list">
      <div class="mat-body-1" style="padding-bottom: 10px; color: rgba(0,0,0,0.57);">Seleccionar Establecimiento</div>
      <div class="body" [fxShow]="relations().length">
        <div class="row" fxLayout="row" fxLayoutAlign="start center" formArrayName="relations" *ngFor="let relation of relations().controls; let i = index;">
          <div [formGroupName]="i" class="mat-elevation-z2" fxFlex fxLayout="row" style="padding: 5px 0 5px 5px;">
            <div fxFlex fxLayout="column">

              <div fxLayout="row" fxLayout.xs="column">
                  
                <tb-entity-select
                  fxFlex class="mat-block"
                  [required]="true"
                  formControlName="relatedEntity">
                </tb-entity-select>
                
              </div>
            </div>

            <div fxLayout="column" fxLayoutAlign="center center">
              <button mat-icon-button color="primary"
                      aria-label="Remove"
                      type="button"
                      (click)="removeRelation(i)"
                      matTooltip="Remove relation"
                      matTooltipPosition="above">
                <mat-icon>cerrar</mat-icon>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div>
        <button mat-raised-button color="primary"
                type="button"
                (click)="addRelation()"
                matTooltip="Add Relation"
                matTooltipPosition="above">
          Agregar
        </button>
      </div>
    </div>
  </div>
  <div mat-dialog-actions fxLayout="row" fxLayoutAlign="end center">
    <button mat-button color="primary"
            type="button"
            [disabled]="(isLoading$ | async)"
            (click)="cancel()" cdkFocusInitial>
      Cancel
    </button>
    <button mat-button mat-raised-button color="primary"
            type="submit" [disabled]="(isLoading$ | async)">
      Crear
    </button>
  </div>
</form>

**Comment by Sylphe88** [comment]
I've been looking for doing exactly this (Adding an asset and automatically create its relationship to the dashboard state entity) and could not make it work until now

**Comment by LucasArrillaga** [comment]
Hello, I was able to solve it, I had to create my own services in angular js and call the api, there is not much information about the services and functions in ThingsBoard

**Comment by HaydenBurrows** [comment]
Hi, not sure if this is what you want to achieve.  
I have a relationship hierarchy of: 
Customer-->Asset-->Device

I have a 'Create site' button with HTML template that creates an 'site' asset with the Customer currently logged in (or if Tenant Admin, the customer is taken from dashboard state parameters.
![image](https://user-images.githubusercontent.com/69659611/196551907-7e0d7bec-1535-4965-8874-51e84a1537a8.png)
```
let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let assetService = $injector.get(widgetContext.servicesMap.get('assetService'));
let entityGroupService = $injector.get(widgetContext.servicesMap.get('entityGroupService'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
let entityRelationService = $injector.get(widgetContext.servicesMap.get('entityRelationService'));

openAddSiteDialog();

function openAddSiteDialog() {
  customDialog.customDialog(htmlTemplate, AddSiteDialogController).subscribe();
}

function AddSiteDialogController(instance) {
  let vm = instance;

  vm.addSiteFormGroup = vm.fb.group({
    name: ['', [vm.validators.required]]
  });

  vm.cancel = function () {
    vm.dialogRef.close(null);
  };
  
  vm.save = function () {
    var customerId;
    if (widgetContext.currentUser.authority === 'TENANT_ADMIN') {
        customerId = widgetContext.stateController.getStateParams().entityId;
    } else {
        customerId = { id: widgetContext.currentUser.customerId, entityType: 'CUSTOMER'};
    }
    vm.addSiteFormGroup.markAsPristine();
    saveSite(customerId).subscribe(
      function (site) {
          widgetContext.rxjs.forkJoin([
              saveCustomerToSiteRelation(customerId, site.id),
              saveAttributes(site.id)
          ]).subscribe(
              function () {
                var params = widgetContext.stateController.getStateParams();
                var selectedSite = params['selectedSite'];
                params['selectedSite'] = { entityId: site.id, entityName: site.name, entityLabel: '' };
                widgetContext.updateAliases();
                vm.dialogRef.close(null);
              }
        );
      }
    );
  };

  function saveSite(customerId) {
    return getSitesGroup(customerId).pipe(
        widgetContext.rxjs.switchMap((sitesGroup) => {
            const formValues = vm.addSiteFormGroup.value;
            let site = {
              name: formValues.name,
              type: 'site',
              customerId: customerId
            };
            return assetService.saveAsset(site, sitesGroup.id.id)
        })
    );
  }
  
  function getSitesGroup(customerId) {
      return entityGroupService.getEntityGroupsByOwnerId(customerId.entityType, customerId.id, 'ASSET').pipe(
          widgetContext.rxjs.switchMap((entityGroups) => {
              var sitesGroup = entityGroups.find(group => group.name === 'Sites');
              if (sitesGroup) {
                  return widgetContext.rxjs.of(sitesGroup);
              } else {
                  sitesGroup = {
                      type: 'ASSET',
                      name: 'Sites',
                      ownerId: customerId
                  };
                  return entityGroupService.saveEntityGroup(sitesGroup);
              }
          })
      );
  }

  function saveCustomerToSiteRelation(customerId, siteId) {
      var relation = {
          from: customerId,
          to: siteId,
          typeGroup: 'COMMON',
          type: 'Owns'
      };
      return entityRelationService.saveRelation(relation);
  }
  
  function saveAttributes(entityId) {
    let attributesArray = [
        {
            key: 'latitude',
            value: 55.5150
        },
        {
            key: 'longitude',
            value: -110.11857
        },
    ];
    return attributeService.saveEntityAttributes(entityId, "SERVER_SCOPE", attributesArray);
  }
}
```
```
<form #addEntityForm="ngForm" [formGroup]="addSiteFormGroup"
      (ngSubmit)="save()" class="add-entity-form" style="width: 350px;">
  <mat-toolbar fxLayout="row" color="primary">
    <h2>Add site</h2>
    <span fxFlex></span>
    <button mat-icon-button (click)="cancel()" type="button">
      <mat-icon class="material-icons">close</mat-icon>
    </button>
  </mat-toolbar>
  <mat-progress-bar color="warn" mode="indeterminate" *ngIf="isLoading$ | async">
  </mat-progress-bar>
  <div style="height: 4px;" *ngIf="!(isLoading$ | async)"></div>
  <div mat-dialog-content fxLayout="column">
    <div fxLayout="row" fxLayoutGap="8px" fxLayout.xs="column"  fxLayoutGap.xs="0">
      <mat-form-field fxFlex class="mat-block">
        <mat-label>Site title</mat-label>
        <input matInput formControlName="name" required>
        <mat-error *ngIf="addSiteFormGroup.get('name').hasError('required')">
          Site title is required.
        </mat-error>
      </mat-form-field>
    </div>
  </div>
  <div mat-dialog-actions fxLayout="row" fxLayoutAlign="end center">
    <button mat-button color="primary"
            type="button"
            [disabled]="(isLoading$ | async)"
            (click)="cancel()" cdkFocusInitial>
      Cancel
    </button>
    <button mat-button mat-raised-button color="primary"
            type="submit"
            [disabled]="(isLoading$ | async) || addSiteFormGroup.invalid || !addSiteFormGroup.dirty">
      Add site
    </button>
  </div>
</form>
```

**Comment by Sylphe88** [comment]
I found how to do it, pretty similar to what you've done. What stroke me with your snippet was that we can reuse the rxjs from the widget context (to access map/switchmap, forkjoin and all the other stuff)! A new world opens up to me...

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
