### ISSUE TITLE
[Question] Image map - image (disable drag - drop)

### ISSUE THREAD

**Issue by DaiNgocVu** [thingsboard/thingsboard#7167]
**Component**

 * UI

**Description**
Can I freeze image in the Image Map widget?

**Comment by rajSilikon** [comment]
Were you able to find a solution to this? I also want to freeze the image.

I'm having issues wherein user are able to drag the image.

**Comment by mykhailokornieiev** [comment]
Hi. Not sure if it is still relevant. 
There is no standard functionality to disable dragging in Image Map, but you can try to use the next CSS snippet in Widget Settings → Widget Card → Card Style → Advanced Widget Style → Widget CSS:
```
.leaflet-grab {
 cursor: default !important;
}
.leaflet-pane.leaflet-map-pane {
 transform: none !important;
}
```

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
