### ISSUE TITLE
[Bug] Script Node EMPTY

### ISSUE THREAD

**Issue by mgogh** [thingsboard/thingsboard#7168]
**Describe the bug**
I'm using the community Edition in 3.4.1. I try to create a new rule chain with a script node.

Unfortunately I cannot cause the "Script node" is empty and I cannot add javascript in the "textarea".

![image](https://user-images.githubusercontent.com/38976317/187409523-7a81f8a0-09ab-414b-9329-873dd2bab300.png)

You can see the behaviour in the picture and the error in the console.
I try to rebuild the application (I using docker), etc but I still encounter this issue...

**Your Server Environment**
* own setup
  * Docker deployment
  * ThingsBoard Version 3.4.1
  * Linux

**Comment by ashaforost** [comment]
Hi @mgogh 

Try to check and disable your ad-block software if any, and clean the browser cache. You can also try a different browser. Let me know the results.

**Comment by mgogh** [comment]
Hi @ashvayka ,

Thanks for your answer, unfortunately it still not working.
I try with Firefox (previously it was with Chrome), clear cache, I have no AdBlock but it still not working :(

**Comment by Ultrazombie** [comment]
Did not reproduce this.
Closed due to inactivity
