### ISSUE TITLE
[Bug] Wrong rule chain is deployed (the rule chain in the device profile is ignored). 

### ISSUE THREAD

**Issue by dbeulen** [thingsboard/thingsboard#7169]
Describe the bug
I set up a rule chain to create alarms specific for one device profile. Therefore i setup the device profile to use a different rule chain, but it still uses the root rule chain.

Your Server Environment

    own setup
        k8s deployment
        ThingsBoard Version : 3.4.0
        OS Name and Version : Ubuntu 22.04 LTS

Your Client Environment

Desktop (please complete the following information):

    OS: W10Pro
    Browser: MS Edge
    Version 103.0.1264.71

Your Device

    Connectivity
        MQTT
    Device vendor and model
        Custom device 

To Reproduce
Steps to reproduce the behaviour:

   1. Create new empty rule chain. 
   2. Create device profile.
   3. Set device profile to a use the new rule chain.
   4. send telemetry from a device in the device profile
   5. telemetry data is still updated, indicating that the root rule chain has been used.

Expected behaviour
Because the new rule chain is empty, telemetry data should not be updated.

Screenshots
Not applicable

**Comment by ban2derlog** [comment]
Hi, 
Why do you think that Root Chain is used when you send a telemetry to Device, that assign to Device Profile that has specified Rule Chain?
I even check that, and on 3.4 and 3.4.1 version if you set Rule Chain for Device Profile - all will go to that Rule Chain, and nothing go to Root Rule Chain till you delete custom from Device Profile.
Even if your Rule Chain for Device Profile is clean and have only Input node.
