### ISSUE TITLE
Old thingsboard data into new one (same versions) using cassandra backup (var/lib/cassandra)

### ISSUE THREAD

**Issue by Vasilis-Dim** [thingsboard/thingsboard#7170]
Hey! 
I Have an old back up file (var/lib/cassandra) into an external drive from a thingsboard that i used in past. i just setup a new thingsboard and cassandra with the same versions as then (tb 2.4.4 / cassa 3.11 / ubuntu latest)  and in the cassandra yaml file i change the data_file directories from the local hdd (var/lib/cassandra/data) into the external one(/media/external_drive/backup/cassandra/data) etc. Then i try to start cassandra and i see the followings errors 

DEBUG [main] 2022-08-30 12:20:38,273 DatabaseDescriptor.java:497 - Error checking disk space
java.nio.file.AccessDeniedException: /media/vasilis/External_Drive/OLD_M3_cassandra_backup/commitlog

ERROR [main] 2022-08-30 12:24:02,941 CassandraDaemon.java:803 - Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to /media/vasilis/External_Drive/OLD_M3_cassandra_backup/commitlog. Perhaps the Cassandra user does not have the necessary permissions

(same errors for the other directories like data, hints etc)

Any idea on how to fix it?

**Comment by pon0marev** [comment]
Perform a clean installation of the cassandra database. Then set an empty folder for the cassandra data in the configuration. Create a thingsboard keyspace and then restore the data to .../cassandra/data/thingsboard

**Comment by Vasilis-Dim** [comment]
> Perform a clean installation of the cassandra database. Then set an empty folder for the cassandra data in the configuration. Create a thingsboard keyspace and then restore the data to .../cassandra/data/thingsboard

This did not help. I solve the problem when i change the database type from sql to cassandra in thingsboard.yml!
Thanks for your time!
