### ISSUE TITLE
Can we use multiple timeseries fields to prepare the statechart

### ISSUE THREAD

**Issue by laxmiprasannaBorigi** [thingsboard/thingsboard#7172]
Here i have a requirement, i need to show the custom Y-axis names based on the id in timeseries. Means based on the id field i need to show the status in statechart. When i use the  function, f(value)  i should only use one value(1 timeseries field) at a time. 

Can anyone help how can we use 2 timeseries fields to show a single statechart.
,

 * UI
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS: Linux
 * ThingsBoard: 3.3.4.1

**Comment by Ultrazombie** [comment]
https://github.com/thingsboard/thingsboard/issues/8886#issuecomment-1785391982
