### ISSUE TITLE
[Question] Switch node (Rule Engine)

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7175]
**Component**

 * Rule Engine

**Description**
Hello Thingsboard community! I would like to know more about switch node in Rule Engine. I want to route incoming messages by certain conditions and than create relations etc. The thing is that I struggle with defining custom link/wire/connection between switch node and node afterwards. 
Of course I found docs:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/

For exmaple this is part of code in my switch node 

function Nextmsg(metadata, msg) {
    return msg.interface;
}
    if (msg.devicetype =="WIFI") {
    if (msg.interface == "2_4Hz-CAP4-4np-OaM-1"||msg.interface == "5GHz-CAP4-4np-OaM-1-1") {
     return [Nextmsg(metadata, msg),'**oam**'];   
    } else {
    return ['XXX',"XZT"];   
    }
} else {}

I created custom wire/link to next node and called it **oam**. 
![image](https://user-images.githubusercontent.com/58517178/187642739-9bdb6ad9-f1c9-4dd0-be94-ec40a06382f1.png)
Problem is that every incoming message is than send via this connection. (Even when they do not pass those conditions). How to get it right? I want to add more links/conditions.  Thanks!

**Comment by devaskim** [comment]
I think you need to add global *return* at the end of your code, for example
```
return ['none'];
```

By the way, *Switch* node has *Test function* feature where you can test your code and see that result would be.

**Comment by samokomo** [comment]
Thanks, seems like it helped! I want to create an asset tree (relations) based on telemetry and this is essential piece of my puzzle. I will come back to this soon and once I 100% sort out "Switch node" I will close this thread. 

Have a nice day. 👍
