### ISSUE TITLE
gridster: how to set the default 10px to 0px

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7177]
**Component**

 * UI

**Description**
 <gridster #gridster id="gridster-child" [options]="gridsterOpts">
      <gridster-item #gridsterItem [item]="widget" [ngClass]="{'tb-noselect': isEdit}" *ngFor="let widget of dashboardWidgets">
        <tb-widget-container
          [gridsterItem]="gridsterItem"
          [widget]="widget"
          [dashboardWidgets]="dashboardWidgets"
          [dashboardStyle]="dashboardStyle"
          [backgroundImage]="backgroundImage"
          [isEdit]="isEdit"
          [isMobile]="isMobileSize"
          [isEditActionEnabled]="isEditActionEnabled"
          [isExportActionEnabled]="isExportActionEnabled"
          [isRemoveActionEnabled]="isRemoveActionEnabled"
          [disableWidgetInteraction]="disableWidgetInteraction"
          (widgetFullscreenChanged)="onWidgetFullscreenChanged($event)"
          (widgetComponentAction)="onWidgetComponentAction($event, widget)">
        </tb-widget-container>
      </gridster-item>
    </gridster>
![1](https://user-images.githubusercontent.com/19941827/187699421-00acbf5c-4cda-467f-ae99-8f64199e5072.png)

**It will generate HTML code style = "padding: 10px" how to set it to 0px;**
**Environment**

 * OS:  name and version
 * ThingsBoard: 3.4.0
 * Browser: name and version

**Comment by devaskim** [comment]
Each widget has **Widget style** subsection in **Settings** section. There is *padding* and *margin* options. The **Widget style** subsection also has **Advanced settings** where you could manually specify CSS rules.

Finally, you could manually specify CSS rules in dashboard settings. 

**NOTE**: often CSS option `!import` is needed to override existing rules, for example
```
gridster-item {
    padding: 0px !important;
}
```

**Comment by struggle3** [comment]
> Each widget has **Widget style** subsection in **Settings** section. There is _padding_ and _margin_ options. The **Widget style** subsection also has **Advanced settings** where you could manually specify CSS rules.
> 
> Finally, you could manually specify CSS rules in dashboard settings.
> 
> **NOTE**: often CSS option `!import` is needed to override existing rules, for example
> 
> ```
> gridster-item {
>     padding: 0px !important;
> }
> ```
Sorry, I used this method to test at first. It is invalid because the generated HTML element is gridster and automatically carries a style = "padding: 10px"“
![1](https://user-images.githubusercontent.com/19941827/187848578-5b44397a-005a-47ac-888e-d31748348cbe.png)

**Comment by devaskim** [comment]
This option locates in *Layout settings* of dashboard and called *Margin between widgets*

**Comment by struggle3** [comment]
> This option locates in _Layout settings_ of dashboard and called _Margin between widgets_

Is there any way to modify it, such as in the source code.

**Comment by devaskim** [comment]
Here is how it does through UI
https://user-images.githubusercontent.com/86909129/187872445-13358b0e-71fb-46ce-8e73-201eac852652.mp4

**Comment by struggle3** [comment]
> Here is how it does through UI
> 
>  01-09-2022.134542.mp4

Thank you for your reply. It has been solved according to this method.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
