### ISSUE TITLE
[Question] Bar chart with grouping by time range?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7178]
**The case**
The TB server receives message every time when a user will press the Start button on device. I would like to have a bar chart where each bar is a count of messages received in, for example, 2 hours. Is it possible in 3.4.0 version?
 
![Скриншот 01-09-2022 105245](https://user-images.githubusercontent.com/86909129/187842107-12eb7c01-1b3f-4b8d-b7bb-f6f03a251fbf.jpg)

**Comment by Backdraft007** [comment]
I do it with aggregate stream in rule chain. I count how often a machine is started. Maybe you can use node too.
It genrates an extra telemetry, but nice to work in other widgets.

**Comment by Backdraft007** [comment]
Another way is, that you use the timewindow in the bar chart widget. There you can group an sum or count the data.

**Comment by devaskim** [comment]
Thanks @Backdraft007 For my case second option works like a charm.
