### ISSUE TITLE
AWS installation snapshot not found in region ap-southeast-2

### ISSUE THREAD

**Issue by jondoig** [thingsboard/thingsboard#718]
Following the link from [Installing ThingsBoard on AWS EC2](https://thingsboard.io/docs/user-guide/install/aws/) to choose the AMI in [Sydney (ap-southeast-2)](https://console.aws.amazon.com/ec2/v2/home?region=ap-southeast-2#LaunchInstanceWizard:ami=ami-33759851), the launch fails with "The snapshot ID '8' does not exist":

![snapshot_8_does_not_exist](https://user-images.githubusercontent.com/4666409/38786224-e40545e6-4169-11e8-853f-0df301349d3b.PNG)

**Comment by jondoig** [comment]
As a workaround others can use, I've used the [thingsboard Linux install instructions](https://thingsboard.io/docs/user-guide/install/linux/) to create an AMI with Thingsboard v1.4.0 on Ubuntu 16.04.4 LTS with Oracle JDK 8 and PostGreSQL 9.5.12.

I've shared it publicly in Sydney (ap-southeast-2):
ThingsBoard 1.4.0 on Ubuntu 16.04 - ami-c54e86a7

So you can use this link to launch an instance from it just like in the instructions:
[Sydney (ap-southeast-2)](https://console.aws.amazon.com/ec2/v2/home?region=ap-southeast-2#LaunchInstanceWizard:ami=ami-c54e86a7)

**Comment by Karabiy** [comment]
starting from 2.4 TB version there are no combined packages for the AWS. If you want to use version 2.3.1 and below those are okay. 
You can refer to this link regarding the ThingsBoard installation options: https://thingsboard.io/docs/installation/
