### ISSUE TITLE
[Question] What's the point of making an entity group public?

### ISSUE THREAD

**Issue by eeitnn** [thingsboard/thingsboard#7182]
I really don't get it.

If I (tenant admin) create an asset group with some assets and make it public, I expect all customer users to be able to access the assets within this public group.

However, they don't even have Read permissions for these entities.
So what's the point of making an entity group public in the first place?

**Comment by ashaforost** [comment]
To allow customers to see the tenant's assets, you have to provide them with the group role with Read permission. See the [RBAC](https://thingsboard.io/docs/pe/user-guide/rbac/) article.

As for your initial question, you have to make the asset group public only when you need to display the asset information in the public dashboard. See the following article: [Working with IoT dashboards](https://thingsboard.io/docs/user-guide/dashboards/#make-public)
