### ISSUE TITLE
Ability to select specific debug event for "Test transformer function".

### ISSUE THREAD

**Issue by igloodan** [thingsboard/thingsboard#7184]
I have a support ticket where I am discussing this with the team but it would be great if, when viewing debug (IN) events for a rule node, there was a button named something like "Use as Sample Data" to select this msg and metadata content for use in the "Test transformer function" window.

This would allow users to select a problem message and debug it without the current hit-miss selection of data from the most recent messages.

**Comment by devaskim** [comment]
+1

**Comment by igloodan** [comment]
Just for reference, the developers have told me that the "Test transformer function" window loads the **two most recent** events from the debug table and selects the most recent "IN" from these. If you have two "OUT" events in the two most recent, you get the default temperature and humidity sample data.

**Comment by Backdraft007** [comment]
+1

**Comment by Ultrazombie** [comment]
It has already been implemented on the fresh versions of ThingsBoard.
