### ISSUE TITLE
[Bug] Text 'Items per page' in table widgets are not translated

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7189]
**Describe the bug**
Text 'Items per page' in widget is not translated.
![image](https://user-images.githubusercontent.com/49442805/187941919-fcd411d9-0329-4678-ab43-34037dc7b01a.png)

**Your Server Environment**
  * ThingsBoard Version: PE 3.3.3  (also in 3.4.1 CE)
  * OS Ubuntu LTS 20.04

**To Reproduce**
1. Go to user profile set language to French (or other language)
2. Check bottom text in a table widget
4. See English instead of French

**Comment by luisbajr** [comment]
Hi, @ashvayka and @vvlladd28. I saw some parts not translated to Portuguese. May I help with that? I use Thingsboard for my master's degree work. I have already published an article.

**Comment by ArtemDzhereleiko** [comment]
@KenSense  Thanks for your issue, this feature will be able in the next release. After the update, you will be can set your own words for the table paginator using custom translate. 
![image](https://user-images.githubusercontent.com/83352633/188671797-3b219a15-5ffe-4362-a6c7-03572e99d37e.png)
