### ISSUE TITLE
Purge telemetry data

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#719]
Please add a button that allows a tenant administrator to purge all telemetry data of a device.

It is easy to create garbage data during for example installation of a device, or during testing. This way an administrator will be able to restore the device data to a clean state.

**Comment by fotis400** [comment]
Sorry, forgot about #647. I'll close this issue, let's keep the old one only.

**Comment by TwoRedCells** [comment]
I believe this could be considered a separate request. A simple button to purge all data for a device (#719) and a complex UI to delete some data for a device (#647) are quite different in their implementation and scope of work. I recommend re-opening it.

**Comment by rkertesz** [comment]
As I posted here, it is possible to create a separate power-users webapp that uses the REST API to do data administration (specifically deletion of data) for a device 
https://github.com/thingsboard/thingsboard/issues/647#issuecomment-728175403
