### ISSUE TITLE
[Question] Permanent API key for REST?

### ISSUE THREAD

**Issue by stopthatcow** [thingsboard/thingsboard#7191]
**Component**
 * Generic

**Description**
Is it possible to create a long-lasting API key for REST services like ITTT to use? For instance I'd like the ability to update a device attribute from a REST API using a static URL (with an embedded API key).

**Comment by devaskim** [comment]
As for 3.4.1 TB doesn't support API key

**Comment by Ultrazombie** [comment]
Closed to inactivity
