### ISSUE TITLE
How to find solution on Rule Engine Component ? 

### ISSUE THREAD

**Issue by Vackyyyy** [thingsboard/thingsboard#7194]
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.4.2-SNAPSHOT:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [ 36.177 s]
[INFO] Netty MQTT Client .................................. SUCCESS [ 19.621 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.491 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 22.417 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  3.161 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [ 32.184 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [ 24.827 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  1.060 s]
[INFO] Thingsboard Server Common Cluster API .............. SUCCESS [ 21.962 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 13.470 s]
[INFO] Thingsboard Server Common Cache .................... SUCCESS [  6.441 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.402 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  7.510 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  7.217 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.762 s]
[INFO] Thingsboard CoAP server ............................ SUCCESS [  1.403 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  2.595 s]
[INFO] Thingsboard LwM2M Transport Common ................. SUCCESS [  4.933 s]
[INFO] Thingsboard SNMP Transport Common .................. SUCCESS [  2.336 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  2.487 s]
[INFO] Thingsboard Server Remote Edge wrapper ............. SUCCESS [ 10.344 s]
[INFO] Thingsboard Server Version Control API ............. SUCCESS [  2.236 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.192 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  8.546 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [11:16 min]
[INFO] Thingsboard Rule Engine Components ................. FAILURE [ 53.532 s]
[INFO] Thingsboard Server Transport Modules ............... SKIPPED
[INFO] Thingsboard HTTP Transport Service ................. SKIPPED
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] Thingsboard LwM2m Transport Service ................ SKIPPED
[INFO] Thingsboard SNMP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard Version Control Executor ............... SKIPPED
[INFO] ThingsBoard Version Control Executor Microservice .. SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:07 min
[INFO] Finished at: 2022-09-02T13:45:50+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test (default-test) on project rule-engine-components: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ubuntu/Desktop/thingsboard/rule-engine/rule-engine-components/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rule-engine-components

**Comment by Vackyyyy** [comment]
Above error is the output of "mvn clean install"

installed java:
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

installed mvn:
Maven home: /usr/share/maven
Java version: 11.0.16, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-47-generic", arch: "amd64", family: "unix"

installed Docker:
Docker version 20.10.17, build 100c701

installed Docker-compose:
docker-compose version 1.29.2, build unknown

Before running "mvn clean install". We have installed java, mvn and, docker. we have run "mvn clean install -DskipTests" and also "mvn clean install -DskipTests -Ddockerfile.skip=false"

Where it's going wrong ?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
