### ISSUE TITLE
Unable to login to thingsboard mobile app

### ISSUE THREAD

**Issue by drscrolls** [thingsboard/thingsboard#7195]
Hi, I have installed and configured my thingsboard web. But after cloning the mobile repo, i am unable to login when i run it. I changed the endpoint to the url. Still doesnt work. Any help?

**Comment by drscrolls** [comment]
These are the errors i'm getting:

[ +982 ms] I/flutter ( 7575):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 7575):   ERROR │ ThingsboardError: message: [302: Found], errorCode: 2, status: 302
[        ] I/flutter ( 7575):   ERROR │ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
[        ] I/flutter ( 7575):   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
[        ] I/flutter ( 7575):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
[        ] I/flutter ( 7575):   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
[   +1 ms] I/flutter ( 7575):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
[        ] I/flutter ( 7575):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
[        ] I/flutter ( 7575):   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] I/flutter ( 7575):   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
[        ] I/flutter ( 7575):   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
[        ] I/flutter ( 7575):   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[        ] I/flutter ( 7575):   ERROR │ 
[        ] I/flutter ( 7575):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 7575):   ERROR │ #0   ThingsboardClient.post (package:thingsboard_client/src/thingsboard_client_base.dart:256:7)
[        ] I/flutter ( 7575):   ERROR │ #1   <asynchronous suspension>
[        ] I/flutter ( 7575):   ERROR │ #2   OAuth2Service.getOAuth2Clients (package:thingsboard_client/src/service/oauth2_service.dart:34:20)
[        ] I/flutter ( 7575):   ERROR │ #3   <asynchronous suspension>
[        ] I/flutter ( 7575):   ERROR │ #4   TbContext.onUserLoaded (package:thingsboard_app/core/context/tb_context.dart:286:29)
[        ] I/flutter ( 7575):   ERROR │ #5   <asynchronous suspension>
[   +1 ms] I/flutter ( 7575):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 7575):   ERROR │ ⛔ Error: ThingsboardError: message: [302: Found], errorCode: 2, status: 302
[        ] I/flutter ( 7575):   ERROR │ ⛔ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
[        ] I/flutter ( 7575):   ERROR │ ⛔ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[        ] I/flutter ( 7575):   ERROR │ ⛔ 
[        ] I/flutter ( 7575):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[{"id":12,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[ +144 ms] I/flutter ( 7575):   DEBUG ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +3 ms] I/flutter ( 7575):   DEBUG │ 🐛 On load finished.
[   +2 ms] I/flutter ( 7575):   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 7575):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 7575):   ERROR │ ThingsboardError: message: [302: Found], errorCode: 2, status: 302
[        ] I/flutter ( 7575):   ERROR │ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
[        ] I/flutter ( 7575):   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
[        ] I/flutter ( 7575):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
[        ] I/flutter ( 7575):   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
[        ] I/flutter ( 7575):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
[        ] I/flutter ( 7575):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
[        ] I/flutter ( 7575):   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] I/flutter ( 7575):   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
[        ] I/flutter ( 7575):   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
[        ] I/flutter ( 7575):   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[        ] I/flutter ( 7575):   ERROR │ 
[        ] I/flutter ( 7575):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 7575):   ERROR │ #0   toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
[        ] I/flutter ( 7575):   ERROR │ #1   HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
[        ] I/flutter ( 7575):   ERROR │ #2   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
[        ] I/flutter ( 7575):   ERROR │ #3   DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
[        ] I/flutter ( 7575):   ERROR │ #4   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
[   +1 ms] I/flutter ( 7575):   ERROR │ #5   new Future.<anonymous closure> (dart:async/future.dart:253:37)
[        ] I/flutter ( 7575):   ERROR │ #6   Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] I/flutter ( 7575):   ERROR │ #7   _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
[        ] I/flutter ( 7575):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 7575):   ERROR │ ⛔ onError
[   +1 ms] I/flutter ( 7575):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +7 ms] E/flutter ( 7575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/material/scaffold.dart': Failed assertion: line 269 pos 7: '_scaffolds.isNotEmpty': ScaffoldMessenger.showSnackBar was called, but there are currently no descendant Scaffolds to present to.
[        ] E/flutter ( 7575): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] E/flutter ( 7575): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] E/flutter ( 7575): #2      ScaffoldMessengerState.showSnackBar (package:flutter/src/material/scaffold.dart:269:7)
[        ] E/flutter ( 7575): #3      TbContext.showNotification (package:thingsboard_app/core/context/tb_context.dart:239:32)
[        ] E/flutter ( 7575): #4      TbContext.showErrorNotification (package:thingsboard_app/core/context/tb_context.dart:188:5)
[        ] E/flutter ( 7575): #5      TbContext.onError (package:thingsboard_app/core/context/tb_context.dart:184:5)
[        ] E/flutter ( 7575): #6      ThingsboardClient._onError.<anonymous closure> (package:thingsboard_client/src/thingsboard_client_base.dart:190:35)
[   +1 ms] E/flutter ( 7575): #7      new Future.<anonymous closure> (dart:async/future.dart:253:37)
[        ] E/flutter ( 7575): #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] E/flutter ( 7575): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
[        ] E/flutter ( 7575): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
[        ] E/flutter ( 7575): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[        ] E/flutter ( 7575):

**Comment by shaphiro** [comment]
Same problem for me. The error occours when I set thingsBoardApiEndpoint to my (correct) server url. If I set thingsBoardApiEndpoint with the thingsboard demo url the error doesn't occour.

**Comment by agorrieri** [comment]
Same problem here: 

flutter:   DEBUG │ 🐛 onUserLoaded: isAuthenticated=false

flutter:   DEBUG │ 🐛 On load started.

flutter:   ERROR 
flutter:   ERROR │ ThingsboardError: message: [Path '/home/api/noauth/oauth2Clients': Method Not Allowed], errorCode: 2, status: 405
flutter:   ERROR │ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
flutter:   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
flutter:   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
flutter:   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
flutter:   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
flutter:   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
flutter:   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
flutter:   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter:   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter:   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
flutter:   ERROR │
flutter:   ERROR 

flutter:   ERROR │ #0   ThingsboardClient.post (package:thingsboard_client/src/thingsboard_client_base.dart:256:7)
flutter:   ERROR │ #1   <asynchronous suspension>
flutter:   ERROR │ #2   OAuth2Service.getOAuth2Clients (package:thingsboard_client/src/service/oauth2_service.dart:34:20)
flutter:   ERROR │ #3   <asynchronous suspension>
flutter:   ERROR │ #4   TbContext.onUserLoaded (package:thingsboard_app/core/context/tb_context.dart:286:29)
flutter:   ERROR │ #5   <asynchronous suspension>
flutter:   ERROR 

flutter:   ERROR │ ⛔ Error: ThingsboardError: message: [Path '/home/api/noauth/oauth2Clients': Method Not Allowed], errorCode: 2, status: 405
flutter:   ERROR │ ⛔ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
flutter:   ERROR │ ⛔ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
flutter:   ERROR │ ⛔ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
flutter:   ERROR │ ⛔ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
flutter:   ERROR │ ⛔ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
flutter:   ERROR │ ⛔ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
flutter:   ERROR │ ⛔ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
flutter:   ERROR │ ⛔ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter:   ERROR │ ⛔ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter:   ERROR │ ⛔ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
flutter:   ERROR │ ⛔
flutter:   ERROR 

flutter:   DEBUG │ 🐛 On load finished.

flutter:   ERROR │ ThingsboardError: message: [Path '/home/api/noauth/oauth2Clients': Method Not Allowed], errorCode: 2, status: 405
flutter:   ERROR │ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
flutter:   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
flutter:   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
flutter:   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
flutter:   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
flutter:   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
flutter:   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
flutter:   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter:   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter:   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
flutter:   ERROR │
flutter:   ERROR 

flutter:   ERROR │ #0   toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
flutter:   ERROR │ #1   HttpInterceptor.onError (package:thingsboard_client/src/interceptor/http_interceptor.dart:104:19)
flutter:   ERROR │ #2   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
flutter:   ERROR │ #3   DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
flutter:   ERROR │ #4   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
flutter:   ERROR │ #5   new Future.<anonymous closure> (dart:async/future.dart:253:37)
flutter:   ERROR │ #6   Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
flutter:   ERROR │ #7   _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter:   ERROR 

flutter:   ERROR │ ⛔ onError
flutter:   ERROR 
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/material/scaffold.dart': Failed assertion: line 269 pos 7: '_scaffolds.isNotEmpty': ScaffoldMessenger.showSnackBar was called, but there are currently no descendant Scaffolds to present to.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ScaffoldMessengerState.showSnackBar (package:flutter/src/material/scaffold.dart:269:7)
#3      TbContext.showNotification (package:thingsboard_app/core/context/tb_context.dart:239:32)
#4      TbContext.showErrorNotification (package:thingsboard_app/core/context/tb_context.dart:188:5)
#5      TbContext.onError (package:thingsboard_app/core/context/tb_context.dart:184:5)
#6      ThingsboardClient._onError.<anonymous closure> (package:thingsboard_client/src/thingsboard_client_base.dart:190:35)
#7      new Future.<anonymous closure> (dart:async/future.dart:253:37)


Also for me all these error doesn't occur using the "https://demo.thingsboard.io" endpoint. The login page correctly show up in this case.

**Comment by Vasilis-Dim** [comment]
same problem here

I/flutter ( 8742):   ERROR │ ThingsboardError: message: [], errorCode: 32, status: 404
I/flutter ( 8742):   ERROR │ #0      toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 8742):   ERROR │ #1      HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter ( 8742):   ERROR │ #2      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter ( 8742):   ERROR │ #3      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
I/flutter ( 8742):   ERROR │ #4      DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter ( 8742):   ERROR │ #5      new Future.<anonymous closure> (dart:async/future.dart:253:37)
I/flutter ( 8742):   ERROR │ #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter ( 8742):   ERROR │ #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter ( 8742):   ERROR │ #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter ( 8742):   ERROR │ #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
I/flutter ( 8742):   ERROR │ 
I/flutter ( 8742):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 8742):   ERROR │ #0   toThingsboardError (package:thingsboard_pe_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 8742):   ERROR │ #1   HttpInterceptor.onError (package:thingsboard_pe_client/src/interceptor/http_interceptor.dart:104:19)
I/flutter ( 8742):   ERROR │ #2   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter ( 8742):   ERROR │ #3   DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:789:22)
I/flutter ( 8742):   ERROR │ #4   DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter ( 8742):   ERROR │ #5   new Future.<anonymous closure> (dart:async/future.dart:253:37)
I/flutter ( 8742):   ERROR │ #6   Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter ( 8742):   ERROR │ #7   _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter ( 8742):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 8742):   ERROR │ ⛔ onError
I/flutter ( 8742):   ERROR └──────────────────────────────────

**Comment by yaoyi601131548** [comment]
same problem, anyone resolved it ?

**Comment by Anderson-Andre-P** [comment]
Same problem, anyone resolved it ?

**Comment by shaphiro** [comment]
In my case were outdated client libraries.

**Comment by Anderson-Andre-P** [comment]
> In my case were outdated client libraries.

To solve the package versions problem I run the command `flutter pub upgrade --major-versions` and solved the problems that were generated

**Comment by ssakharova** [comment]
Closed due to inactivity.
Also, for the future, we advise you to create GitHub issue with according to the product you are using:

https://github.com/thingsboard/flutter_thingsboard_app/issues

https://github.com/thingsboard/flutter_thingsboard_pe_app/issues

Best regards,
Sofiia

**Comment by Mario0621** [comment]
> Same problem, anyone resolved it ?
> 
> edit: I managed to solve my problem, for this the company changed from thingsboard 3.3 to 3.5

> Wher can i edit the thingsboard version ?

**Comment by Mario0621** [comment]
> flutter pub upgrade --major-versions

How
 can i solve the problem i didn't understand ?
