### ISSUE TITLE
Table widget does not always update

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#720]
This is a intermittent behavior that I can't always reproduce, I got a snapshot to try to show that table widget does not always show the latest value. 

If we look at the latest telemetry it is **right there!.**

The image show the screen and the message sent to the server.

![bug2](https://user-images.githubusercontent.com/3164100/38860223-07d71bae-4230-11e8-823b-da9923af6c92.png)

**Comment by RondoRonaldo** [comment]
This is added to the backlog.

**Comment by RondoRonaldo** [comment]
It is because you use timewindow "history" that works in a way that the widget will display values from a specific period of time and won't display new values until the page is updated. To avoid this situation you need to use timewindow "realtime'.
