### ISSUE TITLE
[Bug] Hiding one datakey causes threshold Lines on another datakey in timeseries charts to disappear, and one threshold to become full background fill

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#7200]
**Describe the bug**
This bug occurs when using more than one datakey on a timeseries chart and when using the Threshold Lines feature within one dataKey 

The threshold lines here are configured for the LQ_Compressor1Pressure dataKey <img width="1138" alt="image" src="https://user-images.githubusercontent.com/88675613/188215887-e65eaa9f-4a40-4907-973d-396aa6022068.png">

When hiding Operational State, the background of the entire chart changes to the color of the highest threshold line
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/88675613/188216334-a9ee0249-c1e4-4b55-b98e-9166ba517aaa.png">

It does not seem to matter if other advanced settings selected or deselected (e.g. disable stacking, no fill, separate Y axis

**Your Server Environment**

* own setup
  * TB running on VM in GCP
  * ThingsBoard 3.4.1 (and previous versions)
  * Ubuntu 

**Your Client Environment**

* Desktop: Any
* Mobile Device: Any
* OS: Any
* Browser: Any
* Version: Any

* Connectivity
  * MQTT

**To Reproduce**
1. Set up a new timeseries chart with 2 dataKeys
2. Add threshold lines to one datakey, e.g. <img width="674" alt="image" src="https://user-images.githubusercontent.com/88675613/188216162-0529aad7-ec91-4ebb-afd2-86a175370678.png">
3. Save changes and view timeseries, then hide the datakey that does not contain threshold lines, observe the change in the background color. <img width="1135" alt="image" src="https://user-images.githubusercontent.com/88675613/188216334-a9ee0249-c1e4-4b55-b98e-9166ba517aaa.png">

**Expected behavior**
When hiding a datakey, the threshold lines on another datakey should remain visible and the background should not change color

**Comment by Eric-Ruud** [comment]
@ashvayka or @vvlladd28 Have you been able to reproduce this bug? Any updates?

**Comment by epalchenko** [comment]
The problem was in older versions of ThingsBoard; please update to the latest version to fix it
