### ISSUE TITLE
[Question] Can I add wildcard to MQTT topic subscription?

### ISSUE THREAD

**Issue by zhgchen** [thingsboard/thingsboard#7201]
**Component**

 * MQTT

**Description**

Message from my gateway always add some extra information to topic, v1/gateway/telemetry/2343445123458C/DW. From console:
[nioEventLoopGroup-4-2] WARN  o.t.s.t.mqtt.MqttTransportHandler - [b3c3ee26-ba60-4e80-8cfc-c80f56793931] Failed to subscribe to [v1/gateway/telemetry/0C3811D7598A708C/DW][AT_MOST_ONCE]

Where can change MQTT topic subscription? Change to "v1/gateway/telemetry/#".

**Environment**

 * OS:  macOS 12.5.
 * ThingsBoard: 3.3.4
 * Browser: Chrome

**Comment by pon0marev** [comment]
The warning occurs when you try to subscribe to the v1/gateway/telemetry/ topic.
You can subscribe to device attributes: [Subscribe to attribute updates from the server](https://thingsboard.io/docs/reference/gateway-mqtt-api/#subscribe-to-attribute-updates-from-the-server)
You may be better to use a broker to configure subscribtion to device telemetry: [TBMQ](https://thingsboard.io/docs/mqtt-broker/user-guide/integrations/how-to-connect-thingsboard-to-tbmq/)
