### ISSUE TITLE
Thingsboard-Gateway Failed To Start

### ISSUE THREAD

**Issue by ChrisTsall99** [thingsboard/thingsboard#7202]
- Procedure 
  I have installed Thingsboard CE following the instructions of the official site, https://thingsboard.io/docs/user-guide/install/ubuntu/ and it    works correctly. Also, I tried to install Thingsboard Gateway, https://thingsboard.io/docs/iot-gateway/install/deb-installation/ but the application can't start. Any ideas? Thank you in advance!

- Virtual Machine's Specifications:
    Distributor ID: Ubuntu
    Description: Ubuntu 20.04.5 LTS
    Release: 20.04
    Codename: focal

- Thingsboard & Thingsboard Gateway Version: 
dpkg -l | grep thingsboard (I used this command in order to find the version)
ii  python3-thingsboard-gateway                3.1-1                               all          Thingsboard Gateway for IoT devices.
ii  thingsboard                                3.4.1-1                             all          thingsboard

- When I execute the following command "systemctl status thingsboard-gateway" this message appears:
    ● thingsboard-gateway.service - ThingsBoard Gateway
         Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
         Active: failed (Result: exit-code) since Sun 2022-09-04 09:05:58 UTC; 8min ago
        Process: 1405 ExecStart=/usr/bin/python3 -c from thingsboard_gateway.tb_gateway import daemon; daemon() (code=exited, status=1/FAILURE)
       Main PID: 1405 (code=exited, status=1/FAILURE)
    
    Sep 04 09:05:58 chris systemd[1]: thingsboard-gateway.service: Main process exited, code=exited, status=1/FAILURE
    Sep 04 09:05:58 chris systemd[1]: thingsboard-gateway.service: Failed with result 'exit-code'.
    Sep 04 09:05:58 chris systemd[1]: thingsboard-gateway.service: Scheduled restart job, restart counter is at 5.
    Sep 04 09:05:58 chris systemd[1]: Stopped ThingsBoard Gateway.
    Sep 04 09:05:58 chris systemd[1]: thingsboard-gateway.service: Start request repeated too quickly.
    Sep 04 09:05:58 chris systemd[1]: thingsboard-gateway.service: Failed with result 'exit-code'.
    Sep 04 09:05:58 chris systemd[1]: Failed to start ThingsBoard Gateway.

**Comment by devaskim** [comment]
It is better to move your question to [gateway](https://github.com/thingsboard/thingsboard-gateway/issues) project.

**Comment by ChrisTsall99** [comment]
I just installed thingsboard gateway version 2.9 and now it works !

**Comment by sunanda2408** [comment]
better use ubuntu 22.04 LTS for installation
