### ISSUE TITLE
[Question] How to configure caching policy for js scripts

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7203]
From browser DevTools I see that response headers of JS resources (main, vendor, polyfill and scripts) has `expires: 0` value. It dramatically impact on load speed on mobile devices. So is there any configuration option to control cache age of such static resources?

We are running haproxy + tb-postgress docker image (built from source with our modifications) .
Here is response header for main.js
```
accept-ranges: bytes
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-length: 116710
content-type: application/javascript
date: Sun, 04 Sep 2022 15:05:18 GMT
expires: 0
last-modified: Fri, 05 Aug 2022 19:44:32 GMT
pragma: no-cache
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

**Comment by devaskim** [comment]
By adding the following header to the `backend` section of *haproxy* configuration load time is reduced:
```
http-response set-header Cache-Control public,\ max-age=31536000 if { var(txn.path) -m end .svg .ico .jpg .css .js .woff2 .ttf }
```

**Comment by tomtobback** [comment]
Hi, i'm having the same issue but editing `/etc/haproxy/haproxy.cfg` does not solve it for me. I have restarted haproxy but the response headers are still showing `Expires:0` and only thingsboard.ico is cached in my firefox browser.
This is the end of my cfg file, is this correct? (using the TB default cfg, with only last line added)
```
backend tb-backend
  balance leastconn
  option tcp-check
  option log-health-checks
  server tb1 127.0.0.1:8080 check inter 5s
  http-request set-header X-Forwarded-Port %[dst_port]
  http-response set-header Cache-Control public,\ max-age=31536000 if { var(txn.path) -m end .svg .ico .jpg .css .js .woff2 .ttf }
```
Is there something else i should do? I'm not building from source so cannot use [your PR](https://github.com/thingsboard/thingsboard/pull/7333).

**Comment by devaskim** [comment]
The problem is in `var(txn.path)`., it has no value. I forgot to mention how it should be initialize in `frontend` section and now I cannot find how I did that. 

The main idea is to compare HTTP request path `.svg .ico .jpg .css .js .woff2 .ttf` So try to google how to get request path in `backend` section

**Comment by devaskim** [comment]
```
frontend http-in
    # Put together with other http-request
    http-request set-var(txn.path) path
  
frontend https_in
    # Put together with other http-request
    http-request set-var(txn.path) path

backend tb-backend
    # Add to the end of backend section
    http-response set-header Cache-Control public,\ max-age=31536000 if { var(txn.path) -m end .svg .ico .jpg .css .js .woff2 .ttf }
```
