### ISSUE TITLE
[Question] ThingsBoardInstallation failed!

### ISSUE THREAD

**Issue by SungWoo-Byun** [thingsboard/thingsboard#7205]
**Component**

 * Installation
 
**Description**
When I install ThingsBoard v3.4.1, the installation does not complete and console display following errors:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ThingsBoard installation failed!

**Environment**

 * OS:  ubuntu 20.04.05 LTS
 * ThingsBoard: v3.4.1
 * Browser: none

**Comment by ashaforost** [comment]
Check your Postgres credentials and if thingsboard can connect to your Postgres database.

**Comment by bzb-rs** [comment]
> 

Had the same issue, mine had special char '(' in the password, i removed all special characters and it worked.

**Comment by bzb-rs** [comment]
> If you do have special characters in your postgres password, you can just add quotation marks to the thingsboard.conf postgres pass: export SPRING_DATASOURCE_PASSWORD="password:):)"

Thanks for the insight @ashaforost i managed to successfully deploy a copy on-prem.

**Comment by drcanalli** [comment]
Yes, I had the same problem installing ThingsBoard, I removed the special characters and everything worked. I didn't try to put quotes with the recommended @ashaforost.
Many thanks @ashaforost and @rsebi
