### ISSUE TITLE
Multiple polygons and polylines with independent properties in map widget

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7208]
**Describe the solution you'd like**
It should be possible to represent multiple assets with independet polygons/polylines on the map widget. Each polygon can then have their own properties and actions.

**Describe alternatives you've considered**
Maybe one could define these polygons/polylines using a geoJSON that can be copy inside the widget?

**Additional context**
Similar to #1948
Example here https://stackoverflow.com/questions/48692242/leaflet-js-fill-color-error-when-hole-overlaps-boundary-of-polygon

**Comment by ssakharova** [comment]
Hello @Civilduino,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.

There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by rpcai** [comment]
Supporting this as a feature!
being able to provide a list of polgon keys, instead of just one would satify my use case

**Comment by GregAscolab** [comment]
> Supporting this as a feature! being able to provide a list of polgon keys, instead of just one would satify my use case

+1
Me too.
Ability to provide a list of "polygons", and a list of "circles". (instead of only one...)
