### ISSUE TITLE
Connecting with MQTT-SPY

### ISSUE THREAD

**Issue by whhsn** [thingsboard/thingsboard#721]
I can't connect to thingsboard server using MQTT-SPY nor MQTT-FX

Connection is ok with the ESP8266 board & the dashboard is working fine.
Any help?

**Comment by mfalkvidd** [comment]
What do you do when you try to connect?
Which messages are printed/logged when you try to connect?

**Comment by whhsn** [comment]
I got it connected - I think I need to enter the local IP address not just 127.0.0.1
Thanks

**Comment by Karabiy** [comment]
you could have used the localhost for those also, or the global IP in case if you have those being configured, or the local network IP. It depends on in which network the server and the client are being present.
