### ISSUE TITLE
Need a dynamic values in y-axis for timeseries line chart

### ISSUE THREAD

**Issue by laxmiprasannaBorigi** [thingsboard/thingsboard#7212]
**Component**

 * UI

**Description**
HI is there any possiblity to get the y-axis data on timeseries graph dynamically. Means we have a temperature (timeseries chart) where it will send the data in negative and positive both the values.. So the y-axis data is not a static. it should be dynamic based on the timeseries data. Do we have any option to show the y-axis dynamically. Please help if anyone have any idea on this,A clear and concise details.

**Environment**

 * OS:  Linux
 * ThingsBoard: thingsboard-3.3.4.1

**Comment by Backdraft007** [comment]
I don't underastand. The y-axis is dynamic. Can you be more specific about that?

**Comment by laxmiprasannaBorigi** [comment]
@Backdraft007  while creating timeseries line chart we can mention the Minimum value on the scale and Maximum value on the scale for y-axis based on that y-axis data will come.. here in my case i gave max as 100 but my device can push the data more than 100 and less than 0 also (for example temperature) so here in my case i need to scale they y-axis based on my timeseries data.. 

![image](https://user-images.githubusercontent.com/34064846/188616621-5606b2e1-5431-41f0-bd99-0f7d442f7271.png)
please check this screenshot for reference

**Comment by Backdraft007** [comment]
Leave the fields empty and the axis scales automatic.

**Comment by laxmiprasannaBorigi** [comment]
![image](https://user-images.githubusercontent.com/34064846/188635475-80bab724-37fa-4dd8-aad0-8bb293e70c90.png)
making 0 is not working it is showing 0 and 1 only graph and data is not coming like a graph

**Comment by Backdraft007** [comment]
Do not enter a number. Clear the fields completely.

**Comment by laxmiprasannaBorigi** [comment]
it solves my issue @Backdraft007  thank you
