### ISSUE TITLE
Multiple layers in map widget

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7213]
**Describe the solution you'd like**
It is important to work with multiple layers in the map widget. For example, one layer can be an orthophoto from a drone, another have multiple polygons, another show the topography, etc.
This helps the user to visualise better the information and add another dimension to the data.

**Describe alternatives you've considered**
This probably can be done with dashboard states, but it is a repetitive task and can become difficult to manage many states. In addition, you cannot have two or more layers in one state.

**Additional context**
Example https://www.drupal.org/project/leaflet_more_maps/issues/2326869

**Comment by Ultrazombie** [comment]
This feature is in our backlog. We are still thinking about how to implement this in our functionality in the future.
