### ISSUE TITLE
[Bug] TenantProfile creation fails if  ID not specified

### ISSUE THREAD

**Issue by PhilDay-CT** [thingsboard/thingsboard#7215]
**Describe the bug**
Creating a new TenantProfile via the API fails unless the ID (with a new uuid) is included in the request.   Other objects work for creation by not specifying an ID, and the system then generates one.

The swagger documentation for the TenantProfile API says that this too should work without an ID 

_"Create or update the Tenant Profile. When creating tenant profile, platform generates Tenant Profile Id as [time-based UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)). The newly created Tenant Profile Id will be present in the response. Specify existing Tenant Profile Id id to update the Tenant Profile. Referencing non-existing Tenant Profile Id will cause 'Not Found' error."_ 

_```Remove 'id', from the request body example (below) to create new Tenant Profile entity._
 

**Your Server Environment**

* own setup
  * Docker deployment of CE version
  * ThingsBoard Version V3.4.1
  * Linux Ubuntu 22.04

**Your Client Environment**

**Desktop (please complete the following information):**
* OS: Ubuntu 22.04
* Browser Chrome
* Version 105.0.5195.52 

**To Reproduce**
1. Open the swagger API page
2. Authenticate as sysadmin
3. Scroll down to 'tenant-profile-controller'
4. Click on "try it out"
5. Set default to false
6. Remove the ID record
7. Click Execute

**Expected behavior**
Expected a new Tenant Profile to be created - instead get an error

Request
```
url -X 'POST' \
  'http://localhost:8082/api/tenantProfile' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzeXNhZG1pbkB0aGluZ3Nib2FyZC5vcmciLCJ1c2VySWQiOiIwMTk3NjhjMC0yOTE3LTExZWQtYWNiYi05MzlhZGE4MzMxNTIiLCJzY29wZXMiOlsiU1lTX0FETUlOIl0sImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNjYyNDY5MTg2LCJleHAiOjE2NjI0NzgxODYsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIn0.cd0IcX9xsUTBk7PrP3opmF1nptp_bLPfxeQWE6cq8TsaVBIQEridM6r_PHxDHgvi-C57S-e47gFhd2Z0rHAa8Q' \
  -d '{
  "default": false,
  "name": "High Priority Tenants",
  "description": "Any text",
  "isolatedTbRuleEngine": true,
  "profileData": {
    "configuration": {},
    "queueConfiguration": [
      {
        "additionalInfo": {},
        "consumerPerPartition": true,
        "name": "string",
        "packProcessingTimeout": 0,
        "partitions": 0,
        "pollInterval": 0,
        "processingStrategy": {
          "failurePercentage": 0,
          "maxPauseBetweenRetries": 0,
          "pauseBetweenRetries": 0,
          "retries": 0,
          "type": "RETRY_ALL"
        },
        "submitStrategy": {
          "batchSize": 0,
          "type": "BATCH"
        },
        "topic": "string"
      }
    ]
  }
}'
```

Response:
```{
  "status": 500,
  "message": "JSON parse error: Could not resolve subtype of [simple type, class org.thingsboard.server.common.data.tenant.profile.TenantProfileConfiguration]: missing type id property 'type' (for POJO property 'configuration'); nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.thingsboard.server.common.data.tenant.profile.TenantProfileConfiguration]: missing type id property 'type' (for POJO property 'configuration')\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 7, column: 23] (through reference chain: org.thingsboard.server.common.data.TenantProfile[\"profileData\"]->org.thingsboard.server.common.data.tenant.profile.TenantProfileData[\"configuration\"])",
  "errorCode": 2,
  "timestamp": "2022-09-06T13:00:19.122+00:00"
}

```

**Additional context**
Using tcpdump it looks as if the Admin UI generates a uuid in request it makes to create a new tenant proifile

**Comment by mykhailokornieiev** [comment]
Hi
I was unable to reproduce your issue. 
http://localhost/swagger-ui/#/tenant-profile-controller/saveTenantProfileUsingPOST
I've tried the next payload without UUID: 
```
{
  "name": "Test tenant profile",
  "description": "test",
  "isolatedTbRuleEngine": false,
  "profileData": {
    "configuration": {
      "type": "DEFAULT",
      "maxDevices": 0,
      "maxAssets": 0,
      "maxCustomers": 0,
      "maxUsers": 0,
      "maxDashboards": 0,
      "maxRuleChains": 0,
      "maxResourcesInBytes": 0,
      "maxOtaPackagesInBytes": 0,
      "maxResourceSize": 0,
      "transportTenantMsgRateLimit": "1000:1,20000:60",
      "transportTenantTelemetryMsgRateLimit": "1000:1,20000:60",
      "transportTenantTelemetryDataPointsRateLimit": "1000:1,20000:60",
      "transportDeviceMsgRateLimit": "20:1,600:60",
      "transportDeviceTelemetryMsgRateLimit": "20:1,600:60",
      "transportDeviceTelemetryDataPointsRateLimit": "20:1,600:60",
      "maxTransportMessages": 10000000,
      "maxTransportDataPoints": 10000000,
      "maxREExecutions": 4000000,
      "maxJSExecutions": 5000000,
      "maxDPStorageDays": 0,
      "maxRuleNodeExecutionsPerMessage": 50,
      "maxEmails": 0,
      "maxSms": 0,
      "maxCreatedAlarms": 1000,
      "defaultStorageTtlDays": 0,
      "alarmsTtlDays": 0,
      "rpcTtlDays": 0,
      "queueStatsTtlDays": 0,
      "ruleEngineExceptionsTtlDays": 0,
      "warnThreshold": 0
    }
  },
  "default": false
}
```
So it was saved correctly even without UUID. 
![image](https://github.com/thingsboard/thingsboard/assets/115699895/80f0689d-d142-4df3-89f9-de62add80a75)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/ff99ae8e-860e-41ea-9e81-e2b0647ffedb)

Please confirm if this problem still relevant on the latest Thingsboard version.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
