### ISSUE TITLE
When I close (X) the tooltip on the map widget the panel closes (Thingsboard 3.4.1)

### ISSUE THREAD

**Issue by aortizja** [thingsboard/thingsboard#7219]
I have installed version 3.4.1 of Thingsboard, I am testing the thermostats example panel; every time I close the tooltip on the map widget the panel automatically closes. This does not happen in version 3.1.1

Is it a bug or what configuration should be done so that this does not happen?

http://x.x.x.x:xxxx/dashboards/61bcfce0-27b6-11ed-b812-4f2e958b33f1

![Sin título](https://user-images.githubusercontent.com/101874577/188673711-235ef65a-85d3-4b08-8d11-858a4715825e.png)

Automatic change in the url:

http://x.x.x.x:xxxx/#close

http://x.x.x.x:xxxx/home#close

**Comment by ashaforost** [comment]
This is a known bug in the latest thinsboard release. It will be fixed in the upcoming v3.4.2.

**Comment by aortizja** [comment]
Thanks for the info

**Comment by stoismeister** [comment]
> This is a known bug in the latest thinsboard release. It will be fixed in the upcoming v3.4.2.

i'm still experiencing this issue with the v3.4.4, do you have any inputs?
