### ISSUE TITLE
Thingsboard to Spark Integration Error

### ISSUE THREAD

**Issue by cjkini** [thingsboard/thingsboard#722]
hi guys,
Has anyone here tried the the Thingsboard to Spark Integration as per this example :https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/
I am trying to follow this example, however have been bugged by this particular error :
"
Error:(29, 48) java: package org.thingsboard.server.common.data.asset does not exist
[TB-Spark Integration errors.pdf](https://github.com/thingsboard/thingsboard/files/1922330/TB-Spark.Integration.errors.pdf)

Error:(58, 24) java: cannot find symbol
symbol: class Asset
location: class org.thingsboard.samples.spark.RestClient
"
Furthermore, in pom.xml file, this particular parent give an errotr of not being found

<parent>
<groupId>org.thingsboard</groupId>
<artifactId>samples</artifactId>
<version>1.0.0</version>
</parent>

error :
" Project 'org.thingsboard:sample:1.0.0' not found
Inspect a Maven model for resolution problems.
"
Can anyone help me to solve this issue. Tq

**Comment by mp-loki** [comment]
You need to:
1) Check out and build [ThingsBoard source code](https://github.com/thingsboard/thingsboard) (you can skip tests to speed up)
2) update thingsboard.version in parent pom of samples project to 1.4.1-SNAPSHOT
3) build samples project from parent folder, not from samples/spark-kafka-streaming-integration

**Comment by cjkini** [comment]
Hi there. Thanks for your feedback. Will look into this.

**Comment by cjkini** [comment]
Hi @mp-loki , i tried to build from source [](https://github.com/thingsboard/thingsboard); However , I got this error :+1: 

Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:1.4.1-SNAPSHOT: The following artifacts could not be resolved: org.thingsboard:extensions-api:jar:1.4.1-SNAPSHOT, org.thingsboard:extensions-core:jar:1.4.1-SNAPSHOT, org.thingsboard.common:transport:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:http:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:coap:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:mqtt:jar:1.4.1-SNAPSHOT, org.thingsboard:dao:jar:1.4.1-SNAPSHOT, org.thingsboard:dao:jar:tests:1.4.1-SNAPSHOT, org.thingsboard:ui:jar:1.4.1-SNAPSHOT, org.thingsboard:tools:jar:1.4.1-SNAPSHOT: Failure to find org.thingsboard:extensions-api:jar:1.4.1-SNAPSHOT in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> 

Appreciate your feedback on this
TQ

**Comment by cjkini** [comment]
Hi @mp-loki , i tried to build from source ; However , I got this error :

Failed to execute goal on project application: Could not resolve dependencies for project org.thingsboard:application:jar:1.4.1-SNAPSHOT: The following artifacts could not be resolved: org.thingsboard:extensions-api:jar:1.4.1-SNAPSHOT, org.thingsboard:extensions-core:jar:1.4.1-SNAPSHOT, org.thingsboard.common:transport:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:http:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:coap:jar:1.4.1-SNAPSHOT, org.thingsboard.transport:mqtt:jar:1.4.1-SNAPSHOT, org.thingsboard:dao:jar:1.4.1-SNAPSHOT, org.thingsboard:dao:jar:tests:1.4.1-SNAPSHOT, org.thingsboard:ui:jar:1.4.1-SNAPSHOT, org.thingsboard:tools:jar:1.4.1-SNAPSHOT: Failure to find org.thingsboard:extensions-api:jar:1.4.1-SNAPSHOT in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced ->

Appreciate your feedback on this
TQ

**Comment by mp-loki** [comment]
@untilbit You don't have to put sample on the server. You run it as a standalone application.

**Comment by mp-loki** [comment]
@cjkini Have you built ThingsBoard from source? Did the build pass? which maven command did you use to build ThingsBoard (I assume **mvn clean install**)?
If so, go to your local .m2 repository and check if the org.thingsboard artifacts are there

**Comment by mp-loki** [comment]
Have you build from thingsboard/ root folder, or from thingsboard/application? Can you attach the build log?

**Comment by cjkini** [comment]
Hi @mp-loki
I did built it by following this step

https://thingsboard.io/docs/user-guide/install/building-from-source/

Please advice me the right way to build if any.

Appreciate your feedback.

Regards.

**Comment by untilbit** [comment]
After building the server and running the sample it still not working, I don't get the data in the Asset.

In the IDE it still showing this issue.

![](https://v4.phpfox.com/cdn/file/file/pic/photo/2018/04/3933aa61ecc15d830129727b8755e2bf.png?t=5ad8a3c308e68)

**Comment by untilbit** [comment]
It would be better if you could rewrite the sample in other languages supported by Spark like Python or Scala and then send result back to Asset.

**Comment by mp-loki** [comment]
@cjkini Please, attach:

1. build log 
2. contents of your ~/.m2/org/thingsboard folder

**Comment by cjkini** [comment]
hi @mp-loki ;
Please find the attached build log and m2 folder content
[m2 folder content.txt](https://github.com/thingsboard/thingsboard/files/1930611/m2.folder.content.txt)
[build log.txt](https://github.com/thingsboard/thingsboard/files/1930612/build.log.txt)

Appreciate your feedback.

Regards,
Dawood

**Comment by cjkini** [comment]
Hi @mp-loki ,
I tried to install using sudo comman line, everything work well but got one error on this : 
```
[INFO] ThingsBoard Server Application ..................... FAILURE [52:44 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 h
[INFO] Finished at: 2018-04-24T17:11:39+08:00
[INFO] Final Memory: 63M/454M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/administrator/thingsboard_source/thingsboard/application && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/administrator/thingsboard_source/thingsboard/application/target/surefire/surefirebooter6974970997045365464.jar /home/administrator/thingsboard_source/thingsboard/application/target/surefire/surefire4651453185159613470tmp /home/administrator/thingsboard_source/thingsboard/application/target/surefire/surefire_16575182179221195345tmp
[ERROR] -> [Help 1]
```
Attached is updted build log. Appreciate your feedback for me to proceed
[buildloh.txt](https://github.com/thingsboard/thingsboard/files/1942107/buildloh.txt)

**Comment by cjkini** [comment]
Hi @mp-loki ,

I manage to build this. Thanks for your support. :grinning: 

Now, can teach me, how i can build this step by step?

I try to run the built jar, but got below remarks.
```
administrator@SMADEVSVR01:~/thingsboard/application/target$ java -jar thingsboard-1.4.1-SNAPSHOT.jar 
no main manifest attribute, in thingsboard-1.4.1-SNAPSHOT.jar
```
Can guide me how to proceed end to end step to run this integration?

Appreciate your feedback.

Thanks

**Comment by cjkini** [comment]
Now can you teach me

**Comment by cjkini** [comment]
hi @mp-loki ;
 i manage to solve the above issue : 
```
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:16 ./
drwxr-xr-x 31 administrator administrator 4096 Apr  26 14:53 ../
drwxrwxr-x 39 administrator administrator 4096 Apr  26 16:29 repository/
administrator@SMADEVSVR01:~/.m2$ cd repository/
administrator@SMADEVSVR01:~/.m2/repository$ ll
total 156
drwxrwxr-x 39 administrator administrator 4096 Apr  26 16:29 ./
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:16 ../
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 antlr/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 aopalliance/
drwxrwxr-x  4 administrator administrator 4096 Apr  26 16:25 asm/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 avalon-framework/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:27 backport-util-concurrent/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:18 ch/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:26 classworlds/
drwxrwxr-x 12 administrator administrator 4096 Apr  26 16:24 com/
drwxrwxr-x  4 administrator administrator 4096 Apr  26 16:17 commons-beanutils/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 commons-chain/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-cli/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-codec/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-collections/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-configuration/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-digester/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-httpclient/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-io/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-lang/
drwxrwxr-x  4 administrator administrator 4096 Apr  26 16:25 commons-logging/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 commons-net/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 commons-validator/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 dom4j/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:29 doxia/
drwxrwxr-x  4 administrator administrator 4096 Apr  26 16:17 io/
drwxrwxr-x 11 administrator administrator 4096 Apr  26 16:25 javax/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 jline/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:25 junit/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:18 log4j/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 logkit/
drwxrwxr-x  6 administrator administrator 4096 Apr  26 16:18 net/
drwxrwxr-x 30 administrator administrator 4096 Apr  26 16:28 org/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:18 oro/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 sslext/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:25 stax/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 xerces/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:28 xml-apis/
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:17 xmlenc/
```
Can u guide me how to proceed to run this integration? Thanks

**Comment by cjkini** [comment]
However, this is my `.m2/repository/org/thingsboard` content : 
```
administrator@SMADEVSVR01:~/.m2/repository/org/thingsboard$ ll
total 12
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:16 ./
drwxrwxr-x 30 administrator administrator 4096 Apr  26 16:28 ../
drwxrwxr-x  3 administrator administrator 4096 Apr  26 16:16 common/
administrator@SMADEVSVR01:~/.m2/repository/org/thingsboard$ 
```

Am i missing something here?

**Comment by cjkini** [comment]
Hi @mp-loki ,

Can you also guide me how to proceed from this built so that i can have my thingsboard interface opened at my  browser at https://localhost:8080.

In my previous activity, I did install Thingsboard using install Thingboard cluster on any pre-existing machines running Linux example here [](https://thingsboard.io/docs/user-guide/install/linux/) and used Cassandra as my database.
Thanks.
Appreciate your feedback.

**Comment by cjkini** [comment]
Hi @mp-loki ,

This is my today update : 
![error4](https://user-images.githubusercontent.com/26279896/39355598-365f992a-4a40-11e8-9f4b-4b3e633bfce1.jpeg)

I tried to do this : 
1-2. Change the version to 1.4.0 in sample parent POM
3. Build the integration from Thingboard Sample folder
4. I got error of below : 
```

/usr/lib/jvm/java-8-oracle/bin/java -Dmaven.multiModuleProjectDirectory=/home/administrator/tb-integrate/samples-master -Dmaven.home=/home/administrator/Intelij/idea-IC-181.4445.78/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/administrator/Intelij/idea-IC-181.4445.78/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/home/administrator/Intelij/idea-IC-181.4445.78/lib/idea_rt.jar=41171:/home/administrator/Intelij/idea-IC-181.4445.78/bin -Dfile.encoding=UTF-8 -classpath /home/administrator/Intelij/idea-IC-181.4445.78/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.1.1 compile -f pom.xml
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.thingsboard.samples:thingsboard-demo-loader:jar:1.0.0
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.thingsboard.samples:facilities-monitoring:jar:1.0.0
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Thingsboard Samples
[INFO] Thingsboard Demo Data
[INFO] Thingsboard Demo Loader
[INFO] Thingsboard Facilities Monitoring Demo
[INFO] Thingsboard Spark Kafka Streaming Integration Sample
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Samples 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Demo Data 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ thingsboard-demo-data ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ thingsboard-demo-data ---
[INFO] No sources to compile
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Demo Loader 1.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.thingsboard.common:data:jar:1.4.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard Samples ................................ SUCCESS [  0.133 s]
[INFO] Thingsboard Demo Data .............................. SUCCESS [  2.820 s]
[INFO] Thingsboard Demo Loader ............................ FAILURE [  0.140 s]
[INFO] Thingsboard Facilities Monitoring Demo ............. SKIPPED
[INFO] Thingsboard Spark Kafka Streaming Integration Sample SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.576 s
[INFO] Finished at: 2018-04-27T16:59:01+08:00
[INFO] Final Memory: 9M/110M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project thingsboard-demo-loader: Could not resolve dependencies for project org.thingsboard.samples:thingsboard-demo-loader:jar:1.0.0: Failure to find org.thingsboard.common:data:jar:1.4.0 in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :thingsboard-demo-loader

Process finished with exit code 1

```
Appreciate your feedback on this. Thanks

**Comment by mp-loki** [comment]
My answer will be the same. You still need to:
1) build ThingsBoard https://github.com/thingsboard/thingsboard - build should succeed
2) Check in your local maven repository that ThingsBoard artifacts are there. Specifically you are interested in **org.thingsboard.common:data**.
3) in samples pom.xml put the **version of ThingsBoard that you build in step 1**
4) build samples from project root folder

If any of these steps fail for you, find the reason and make it pass before proceeding to the next step, otherwise it does not make any sense.

**Comment by cjkini** [comment]
Hi @mp-loki
Noted. Will do the suggested step.

Thanks ya.

Regards

**Comment by gopirathnamt** [comment]
Check in your local maven repository that ThingsBoard artifacts are there. Specifically you are interested in org.thingsboard.common:data. //
Actually i checked local repository and i dont have commom data ,how can i load common data on it ?

**Comment by mp-loki** [comment]
you need to build main project (thingsboard/thingsboard). Upon the successful build the artifact will be there

**Comment by gopirathnamt** [comment]
i build and run the thingsboard successfully ,but i cant find the artifacts in local repository ,i keep on getting the same errors

**Comment by mp-loki** [comment]
if the `mvn clean install` build is successful, then the artifacts should be in <USER_HOME>/.m2/repository. If it's not there, then the build did not pass. I suggest you examine your build log thoroughly, because when UI build fails, in maven it will show SUCCESS and no artifacts are uploaded. But if you say that you run ThingsBoard successfully, then the artifacts were created, I assume you did not run `install` maven goal but `package` or smth else. 
Anyway, I suggest you to check the items mentioned above and if you cannot find the answer - open a new issue and post a full build log for the main thingsboard project.

**Comment by m0o0** [comment]
Hi, I say.
I added the required items to the POM.EXL file for the use of Kafka as follows, but encountered an error while making it.
Be guided, please.
https://thingsboard.io/docs/samples/analytics/spark-integration-with-thingsboard/#spark-application
less application/pom.xml

`... <dependency> <groupId>org.thingsboard.extensions</groupId> <artifactId>extension-kafka</artifactId> <version>${project.version}</version> </dependency> .... `
![Screenshot from 2019-08-06 22-55-14](https://user-images.githubusercontent.com/32868670/62781389-2991e500-bacd-11e9-9aab-5dca75dc115a.png)
