### ISSUE TITLE
[MQTT Shared Attributes] how to fetch all shared attributes through MQTT at once from a device

### ISSUE THREAD

**Issue by mcavalcante** [thingsboard/thingsboard#7220]
Component

 * Generic

**Description**
We know that it is possible to request, using MQTT, one shared attribute from device to the server thorugh the path "v1/devices/me/attributes/request/", with the proper json string containing the keys we´d like to gatther. We also know that, before to send the request, it is necessary to subscribe to the topic "v1/devices/me/attributes/response/+". 

My question is: how to retrieve all the shared attributes at once also using MQTT? I haven´t found any information about that in the documentation.

**Environment**
 * OS:  Linux Ubuntu 22.04
 * ThingsBoard: 3.4.0-1
 * Browser: Chrome 105.0.5195.53
 * Device platform: ESP32-WROOM-32 (it is where the MQTT request comes from)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
