### ISSUE TITLE
[Bug] Scheduler timezone gap

### ISSUE THREAD

**Issue by NicoWii4** [thingsboard/thingsboard#7225]
**Describe the bug**
Scheduler is not triggered at the expected time.

**Your Server Environment**

* own setup
  * Cloud docker deployment with official Thingsboard PE images
  * ThingsBoard Version 3.4.1PE
  * OS Name and Version: Docker host is debian buster, Docker version 20.10.12

**Your Client Environment**

**Desktop:**

* OS: Ubuntu 20.04
* Browser: Chrome, Firefox
* Version: 103.0.5060.134 (chrome) and 103.0.5060.134 (Firefox)

**To Reproduce**

1.1. I define a scheduler to update attribute weekly like this :
![bad_scheduler](https://user-images.githubusercontent.com/80882254/188839895-1f9dd222-16f7-4184-bc98-ed90ce91a3be.png)

1.2. I see wrong hour (11:01PM) in scheduler planning view:
![bad_scheduler_planning_cropped](https://user-images.githubusercontent.com/80882254/188840364-b3992798-4ad7-4a5e-bb3d-127935acbecc.png)

1.3. When i do processing in rule chains, my UPDATE_ATTRIBUTE message is timestamped at 1:01AM:
![bad_scheduler_rc](https://user-images.githubusercontent.com/80882254/188842654-e1c0c222-8d44-4adb-a08f-1b44403e3e31.png)

2.1. I have a temporary workaroud when I define my scheduler to update attribute weekly like this:
![good_scheduler](https://user-images.githubusercontent.com/80882254/188841784-abe9f485-d855-4cc7-b561-911edb0e3a02.png)

2.2. I see 00:01AM as expected in my scheduler planning view:
![good_scheduler_planning_cropped](https://user-images.githubusercontent.com/80882254/188841937-949a48c0-2302-4672-9525-b79070558bb9.png)

2.3. And my messages had a correct timestamp:
![good_scheduler_rc](https://user-images.githubusercontent.com/80882254/188842826-f3e990b2-8d96-41c2-8407-bad8e2068a36.png)

2.4 But this workaround will not work after a time change (in the night between 30th october and 1st november in Europe/Paris timezone). I see wrong hour again (01:01AM):
![good_scheduler_planning_but_bad_cropped](https://user-images.githubusercontent.com/80882254/188851842-d3af92cc-9610-486a-9ba0-dd9c1152e5ed.png)

I think there is a problem with UTC+xx:xx scheduler processing related with scheduler start time and scheduler stop time.

**Expected behavior**

Scheduler triggered at the defined hours (00:01AM in my case) for all start/end time combinaison and with all UTC+xx:xx.

**Context**

I want to use the updated attribute to trigger periodically processing at 00:01AM

**Comment by elietaillardat** [comment]
Hi @ashvayka @vvlladd28 
Any update on this subject? The recent time change in France has just emphasized this problem.
Thank you
