### ISSUE TITLE
[Question] Rule chain - Node to retrieve all related entities

### ISSUE THREAD

**Issue by elietaillardat** [thingsboard/thingsboard#7226]
**Component**

 * Rule Engine

**Description**

We would like to know if it is possible (or planned if not) to have the ability for a node to retrieve all related entities (all devices of an asset, or all assets of a client...), not only the first one as stated in the documentation :
"If multiple Related Entities are found, only the first Entity is used as new originator, other entities are discarded."

For instance if we want to retrieve an attribute from all devices under an asset, when the rule chain originator is an asset.
Thanks

**Environment**

Cloud docker deployment with official Thingsboard PE images
ThingsBoard Version 3.4.1PE
OS Name and Version: Docker host is debian buster, Docker version 20.10.12

**Comment by ashvayka** [comment]
ThingsBoard PE has a rule node "duplicate to related" that may duplicate messages to multiple other originators. So, you may use "duplicate to related" and then "related attributes" to process the incoming messages for each related entity. But you can't get the attribute for all related devices. The reason for this is basically a performance consideration. We don't want one message to cause a fetch of the attribute for 1000 related entities. 

 Is this sufficient for your case?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
