### ISSUE TITLE
Making dashboards available for other people

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#723]
Hi all,

I've made several dashboards in my tenant administrator account on my laptop.
Now I want other people (students) to work with these dashboards in the schools computer room (other server).

What is the easiest way to get this done? Making the dashboard public?

Thanks in advance.

**Comment by jensvdh15** [comment]
Thanks for the response.

But there are a lot of students so creating customer accounts will take a lot of time.

I would like to pick the 'public' option.
I can make these dashboards public in my account, but how do I make it accessible for the students?
Do I have to give them a link? Maybe they have to sign in with a demo account? Or do I have to use the public customer ID in a certain way? 

I don't know. Hope someone can help me

**Comment by t0mmyz7** [comment]
hi @jensvdh15 this is simple, you just edit the dashboard, click on Make Dashboard Public, and you will get a link to share with your students.

![image](https://user-images.githubusercontent.com/31729091/39232473-1c5c6d4e-4876-11e8-9641-922c1251a78f.png)

**Comment by Karabiy** [comment]
for those reasons, you also need to have the entities being applied as public so that it can be used to be visualized on the dashboard.
