### ISSUE TITLE
Thingsboard PE version deployment on google kubernetes  

### ISSUE THREAD

**Issue by krshashank963** [thingsboard/thingsboard#7234]
**Component**

 * Installation

**Description**
I have deployed professional version of Thingsboard on Google kubernetes and trying to use the public ip adress as a mqtt broker but I am unable to establish the connection.
Earlier if I was using thingsboard cloud then at that time I was using mqtt broker name as **thingsboard.cloud** So like that I want to use a specific broker while deploying on Google kubernetes

**Environment**
Thingsboard  professional version

**Comment by pon0marev** [comment]
Have you deployed [MQTT transport](https://thingsboard.io/docs/user-guide/install/pe/cluster/gcp-microservices-setup/#mqtt-transport-optional)? 
That your external IP for MQTT transport will be different from the external IP for web access. To find out the endpoint for MQTT transport execute:
`kubectl get svc -n thingsboard`

**Comment by krshashank963** [comment]
Yes, We have done the same and also checked with the external ip address for MQTT transport 
But while connecting we are getting  **sock. Connect(sa)   socket. Timeout: timed out** error.

Please take  a look in attached SC
<img width="587" alt="image" src="https://user-images.githubusercontent.com/44467705/189069403-3b93db69-dc06-4b1f-ad3a-c30bdb4a6eba.png">

**Comment by krshashank963** [comment]
We have tried this already but we are getting **sock. Connect(sa)     socket. Timeout: timed out** error while trying to build MQTT connection.
Please look into attached image
<img width="635" alt="image (1)" src="https://user-images.githubusercontent.com/44467705/189122834-3ca8db6b-5a76-4706-b3cf-e720eb2e1dc7.png">

**Comment by krshashank963** [comment]
We have tried this already but we are getting sock. Connect(sa) socket. Timeout: timed out error while trying to build MQTT connection.
Please look into attached image
<img width="635" alt="image (1)" src="https://user-images.githubusercontent.com/44467705/189123342-83dbdba0-439d-4a7c-955a-ec68c75d4393.png">

**Comment by krshashank963** [comment]
@pon0marev  Please look into this  question and suggest appropriate approach.

**Comment by krshashank963** [comment]
@ashvayka Any suggestion ?

**Comment by pon0marev** [comment]
Deployment of the mqtt tranport does not require any additional customizations. You only need to apply the files [tb-mqtt-transport.yml](https://github.com/thingsboard/thingsboard-pe-k8s/blob/master/gcp/microservices/transports/tb-mqtt-transport.yml) and [mqtt-load-balancer.yml](https://github.com/thingsboard/thingsboard-pe-k8s/blob/master/gcp/microservices/receipts/mqtt-load-balancer.yml)
