### ISSUE TITLE
Acquire weather data from Thingsboard directly

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#724]
Hello there,

I want to compare the weather data from my weather station with the data from openweathermap.

Here is my idea:

I have my weather station as a device. Whenever it sends data to Thingsboard (via MQTT) a TB-rule activates a TB-plugin that queries weather data from openweathermap. This data is then saved together in the database.

Can a plugin grab data from APIs? I successfully did the weather request with a python script and then sent the data to Thingsboard but I would like to replace this part with a Thingsboard plugin.

Do you guys think that is possible?

Any ideas are much appreciated! Thanks.

**Comment by mp-loki** [comment]
Yep, I assume you develop a plugin in which you configure the weather service endpoint url. Then inside of the plugin you query the endpoint the same way you do in Python, but this time in Java :)

**Comment by arture1991** [comment]
Thanks for your answer mp-loki. 

Let's assume I developed a Plugin that queries the weather service endpoint. 

But now I am left with the data, right? What next? How can I couple another Plugin that writes the data to my database? Can I link the "Weather Plugin" with the MQTT or System Telemetry Plugin?
 
In addition to that: How difficult is Plugin development? Does it require building from source again? 

Thanks a lot!

**Comment by mp-loki** [comment]
Plugin development is not that difficult if you are familiar with Java. The plugin development guide is [here](https://thingsboard.io/docs/user-guide/contribution/extensions-development/)
What I think is that you will define a Rule which will filter MQTT messages from your weather station. Once the MQTT message arrives, a Rule will route that message to a Plugin, which will query the weather service (or take some cached value), and then populate both values as the device telemetry or do whatever you want with the data.

Just keep in mind that the Rule Engine will be changed significantly soon, so you will have to re-implement your solution then.

**Comment by arture1991** [comment]
Thank again, mp-loki. One last question.

Do I get it right that I have to rebuild thingsboard with the new extension that I created?

Cheers!

**Comment by LeoMorgan113** [comment]
Yes, you need to rebuild it every time you've changes source code or added new extensions.
