### ISSUE TITLE
[Bug] Calculation SUM of total value in cycle time is wrong

### ISSUE THREAD

**Issue by Tpro4391** [thingsboard/thingsboard#7253]
**Describe the bug**
Calculation (SUM) of total value in cycle time is wrong

**Your Server Environment**

* own setup
  * local
  * ThingsBoard Version: 3.4
  * OS Name and Version: Windows

**To Reproduce**
1. Go to Timeseries table
2. Click on pick time -> Interval -> Current day 
3. Data aggregation function: Sum
4. Grouping interval: 1 hour
6. See error

**Expected behavior**
Check the total value calculation again

**Screenshots**
![image](https://user-images.githubusercontent.com/55780661/189270473-fc8789dd-7c1a-451e-9464-040975311b40.png)
![image](https://user-images.githubusercontent.com/55780661/189270511-cd9ba11f-0407-4cb6-92b9-c574a7b841c3.png)
![image](https://user-images.githubusercontent.com/55780661/189270541-ef052ffc-259d-4c87-ad14-e5ab5d91a1df.png)
The total correct value in my calculation is 5.11 while the value seen is 0

**Additional context**
I found the problem with small data fields 0~1

**Comment by Tpro4391** [comment]
Test in 3.4.1:
1. Random data value (0~0,1)
![image](https://user-images.githubusercontent.com/55780661/189806470-3a250436-f723-4bde-a8bf-965021a583e7.png)

2. Data time
![image](https://user-images.githubusercontent.com/55780661/189807669-833a8e28-c83c-4812-929a-9fc921347283.png)
3. Data sum 2min
![image](https://user-images.githubusercontent.com/55780661/189807744-15c31fdf-a49d-449c-923d-63638c2450d0.png)
4. View error
![image](https://user-images.githubusercontent.com/55780661/189807860-0886711d-c144-4d5e-b707-78b4cb2d4ba8.png)

**Comment by miroslavpetrov** [comment]
I am experiencing the exact same issue. Did you manage to find a solution?

**Comment by Tpro4391** [comment]
> I am experiencing the exact same issue. Did you manage to find a solution?

Unfortunately not yet. I think it's in the calculation code

**Comment by miroslavpetrov** [comment]
I gave up and decided to send the energy values in wH(multiplied by 1000) and after calculating the delta in thingsboard, I divide the values by 1000. Now it works fine.
![Screenshot 2022-10-24 at 17 15 36](https://user-images.githubusercontent.com/25277610/197547605-d365967e-b220-4351-a7a7-53a82c0051ee.png)

**Comment by eAndrius** [comment]
Can confirm having the same exact issue with CE v3.4.3 -- I would personally consider errors in telemetry aggregation a pretty significant bug.

**Comment by eAndrius** [comment]
The issue still present in CE v3.4.4:
![image](https://user-images.githubusercontent.com/75345/220416768-29f78e1e-692e-435f-b6e1-2d7ee61f9b9b.png)
![image](https://user-images.githubusercontent.com/75345/220416656-021b532c-407b-4bcd-9da9-fbf469badd96.png)

**Comment by etiocb** [comment]
This affects AVG calculation as well it seems:

Thingsboard version: 3.4.4PE

![image](https://user-images.githubusercontent.com/126664214/230573407-efc23a46-69c1-4831-b39b-c74f769a3575.png)

**Comment by etiocb** [comment]
After few more REST API gets and posts, it seems that this bug (storing/loading value as string instead of float) is deterministic: certain values always end-up being wrongfully converted when some other never do... yet it appears random in the sense that I cannot predict what will be the behavior for any given value... would this have anything to do with "hashing" ?

**Comment by etiocb** [comment]
I can confirm that the wrongful conversion happens before the write into database, as per database query:

![image](https://user-images.githubusercontent.com/126664214/231085090-d6adbd59-0be0-4f0c-9dc6-c5c9a1e70d12.png)
![image](https://user-images.githubusercontent.com/126664214/231084564-36e76541-753e-4034-85f5-c54cf777bcb4.png)

HOWEVER, in my case this error only seems to happen on time-series fields that are generated by rule engine (i.e not coming from an actual device):

![image](https://user-images.githubusercontent.com/126664214/231088229-5b6e5869-181c-4b29-b718-2f18d3b09fa9.png)
![image](https://user-images.githubusercontent.com/126664214/231088298-83b15987-5f1c-46c0-a5a5-debbf37d96d3.png)

**Comment by etiocb** [comment]
> After few more REST API gets and posts, it seems that this bug (storing/loading value as string instead of float) is deterministic: certain values always end-up being wrongfully converted when some other never do... yet it appears random in the sense that we cannot predict what will be the behavior for any given value... could this have something to do with "hashing" ?

I am feeling more and more that this is a single vs. double precision float and their string representation in JSON.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by albtrentadue** [comment]
I suspect that issue ##10603 is related
