### ISSUE TITLE
[Question] Best Thingsboard-Cassandra-Postgresql implementation?

### ISSUE THREAD

**Issue by Vasilis-Dim** [thingsboard/thingsboard#7257]
Question : 
Which is the best Thingsboard-Cassandra-Postgresql implementation? 

Description :

I want to create a VM to setup a new Thingsboard and I was wondering how should I do that. 
I mean...should I create 2 seperate VMs (1 for cassandra and 1 for thingsboard-postgresql) or 1 more powerful vm with everything is better? 

The Vm specs are also a good question. Should i go for 4-8 cores and around 8gb ram for each Vm or 8-12 cores and around 16gb ram in one vm? 

Extra useful information :
* Heavy Use 
* Production Enviroment

Environment : 
 * OS:  ubuntu
 * ThingsBoard:  3.2.2 PE (maybe 3.3...)
 
 Thanks for your Time

**Comment by devaskim** [comment]
Maybe [this doc](https://thingsboard.io/docs/reference/iot-platform-deployment-scenarios/#performance-requirements) will help you.

**Comment by trikimiki** [comment]
Hi!

If this is still relevant - I would rate 2 separate VMs better than 1 "extended" VM instance.
Both Cassandra and TB are Java applications and, unless highly tuned, might have performance issues when running under a stressful load. By default, both of those are trying to use as much server resources as possible.
