### ISSUE TITLE
[Bug] Very slow dashboard data request after upgrade 3.4.0

### ISSUE THREAD

**Issue by icebob** [thingsboard/thingsboard#7260]
**Describe the bug**
I'm facing a very slow dashboard data request issue after upgrading from 3.3.4.1 to 3.4.0. (Same issue with 3.4.1 as well).
When I open the dashboard, the charts are empty and it takes 10-30 sec until the dashboard shows the chart data. 

The first WS message was received at 12:20:39
![image](https://user-images.githubusercontent.com/306521/189525804-3563f781-e1b6-4b98-8d70-99717c90b0ff.png)

And the chart data message was received at 12:21:18 (49 seconds)
![image](https://user-images.githubusercontent.com/306521/189525852-05bc685d-e12e-410d-9a7a-7f6e440273a7.png)

Moreover, I'm facing much higher CPU usages (and disk IO usages) after the upgrade:
![image](https://user-images.githubusercontent.com/306521/189525749-b6fe976f-4445-4590-ae2f-25b27165eb51.png)

**Your Server Environment**

* own setup
  * cloud on AKS as monolith
  * 3.4.0 and 3.4.1
  * Docker image

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows & MacOS
* Chrome
* Version 105

**To Reproduce**
I don't know

**Expected behavior**
Same dashboard and database CPU usages as before 3.4.0

**Additional context**
Database is PostgreSQL 13 with TimescaleDB extension

**Comment by PaulHHolmes** [comment]
Just to join in on this, I am seeing the same on a GCP instance, CPU usage of 200%, and having to log in and restart the service.

**Comment by daniq350** [comment]
I am facing the same issue. Monolithic Thingsboard hosted on AWS. Working fine before the 3.4.0 upgrade.

**Comment by YevhenBondarenko** [comment]
Hi @icebob,

definitely problem related to the db indexes, plz check for example device table \d device, if indexes are absent I can send you list of queries for re-creating all indexes.

Did you restore the dump during the upgrade?

**Comment by icebob** [comment]
@YevhenBondarenko thank. I've checked the device table and I see indexes:
![image](https://user-images.githubusercontent.com/306521/213776193-0776e723-3fe4-408d-8b88-defd1f25d4a1.png)
By the way, the device table contains only 21 rows.

I don't restore the data, just upgraded the existing db.

**Comment by AngeLinuX99** [comment]
Same problem here... any fix to solve it ?

**Comment by daniq350** [comment]
> 

Upgrade to v3.4.4 (February 7, 2023). Caching issue is resolved in new update.

**Comment by PaulHHolmes** [comment]
> > 
> 
> Upgrade to v3.4.4 (February 7, 2023). Caching issue is resolved in new update.

It seems to have helped so far!

Thank you.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
