### ISSUE TITLE
[Bug] thingsboard service start faild after a few seconds

### ISSUE THREAD

**Issue by mojtabasji** [thingsboard/thingsboard#7265]
**Describe the bug**
after install thingsboard according to documentation when run `sudo systemctl start thingsboard` faild after a few seconds
created new user for postgresql and 
i add database configuration to `/etc/thingsboard/conf/thingsboard.conf`
Run installation script work successfully 

here is `sudo systemctl status thingboard` result:
```
● thingsboard.service - thingsboard
     Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-09-12 12:48:05 UTC; 485ms ago
    Process: 5737 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
   Main PID: 5737 (code=exited, status=1/FAILURE)

Sep 12 12:47:48 hetzner thingsboard.jar[5771]:  ===================================================
Sep 12 12:47:48 hetzner thingsboard.jar[5771]:  :: ThingsBoard ::       (v3.3.1)
Sep 12 12:47:48 hetzner thingsboard.jar[5771]:  ===================================================
Sep 12 12:47:59 hetzner thingsboard.jar[5771]: WARNING: An illegal reflective access operation has occurred
Sep 12 12:47:59 hetzner thingsboard.jar[5771]: WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/li>
Sep 12 12:47:59 hetzner thingsboard.jar[5771]: WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
Sep 12 12:47:59 hetzner thingsboard.jar[5771]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Sep 12 12:47:59 hetzner thingsboard.jar[5771]: WARNING: All illegal access operations will be denied in a future release
Sep 12 12:48:05 hetzner systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 12:48:05 hetzner systemd[1]: thingsboard.service: Failed with result 'exit-code'.
```

so i cant connect to `http://localhost:8080`

**Your Server Environment**
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
database = postgresql

[gc.log](https://s24.picofile.com/file/8453076968/gc.log.html)
[thingsboard.log](https://s24.picofile.com/file/8453076984/thingsboard.log.html)

**Comment by ashaforost** [comment]
You have to bind the edge rpc port from 7070, which is already taken by some other service, to some other port, 7071 for example
```
2022-09-12 10:44:58,458 [main] ERROR o.t.s.s.edge.rpc.EdgeGrpcService - Failed to start Edge RPC server!
java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:7070
```

see the active ports with `sudo lsof -i  | grep LISTEN` command
then add the `export EDGES_RPC_PORT=<new available port>` line to the thingsboard.conf file and restart the service.
Also see that you have ports 1883 and 5683 available for mqtt and coap services respectively. If they are also taken, you can rebind them with the following lines in the thingsboard.conf file
```
export MQTT_BIND_PORT=<new port>
export COAP_BIND_PORT=<new port>
```

**Comment by mojtabasji** [comment]
yes that port was in use
but i still have the same problem.

[thingsboard.log](https://s24.picofile.com/file/8453126184/thingsboard_2.log.html)
