### ISSUE TITLE
ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt599] Unexpected Exception

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#727]
Hi, when I upload telemetry data with tb-gateway, the thingsboard log shows such errors. What should I do?There is no data on the panel, but tb-gateway is clearly connected to success.

![qq 20180420000841](https://user-images.githubusercontent.com/30205233/39004208-5c999562-442f-11e8-8759-42d8eee30b0a.png)

**Comment by guodaxia103** [comment]
How do you solve this problem?

**Comment by abhishekanne** [comment]
Any update on this?

**Comment by Ultrazombie** [comment]
@abhishekanne @guodaxia103 @BIT-masterpy 
Hello, Did your issue repeat on the latest version of ThingsBoard?
