### ISSUE TITLE
Only Time-Based UUID (Version 1) is supported!  or Device with requested id wasn't found!

### ISSUE THREAD

**Issue by zgjbatyz** [thingsboard/thingsboard#728]
tools:postman
db:postgres
select * from device_credentials
1e83bbc8e1bb0f087483b6d1cd1666b | 57pt5fSbciXq6b******    | ACCESS_TOKEN     |                   | 1e83bbc8e18077087483b6d1cd1666b

use:https://www.uuidgenerator.net/version4

Bulk Version 1 UUID Generation:

get:76eef8b8-446a-11e8-842f-0ed5f89f718b

——————————————————————————————————————————
GET:http://120.24.XXX.XXX:8080/api/plugins/telemetry/DEVICE/76eef8b8-446a-11e8-842f-0ed5f89f718b/keys/timeseries
Content-Type:application/json
X-Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW1vQDEyNi5jb20iLCJzY29wZXMiOlsiVEVOQU5UX0FETUlOIl0sInVzZXJJZCI6IjcwYjA2OTIwLTNiYmMtMTFlOC04NzQ4LTNiNmQxY2QxNjY2YiIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiI1ZmNhYjI1MC0zYmJjLTExZTgtODc0OC0zYjZkMWNkMTY2NmIiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE1MjQyMDc4ODEsImV4cCI6MTUyNDIwODc4MX0.qdAD0uHlpERkbFgSZk_9KI7ItqDB0Qx0t91MQNQytiIQUOSMb_XXXXXXXXXXXXXXXXXXXXXXXXXX

error：Device with requested id wasn't found!

——————————————————————————————————————————

thanks!!!

**Comment by zgjbatyz** [comment]
ok please close it！

**Comment by untilbit** [comment]
@zgjbatyz You can close it yourself by clicking **Close issue** button.
