### ISSUE TITLE
[Feature Request] Add multiple git repositories

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#7282]
**Is your feature request related to a problem? Please describe.**
First of all, thank you for making such an amazing feature of [version control](https://thingsboard.io/docs/user-guide/version-control/) , it makes thingsboard much more scalable and easier to maintain!

I have a use case that may require multiple git repositories.

Say I have a repo A which stores all my rule chains and dashboards. The workflow is guaranteed to be:
`staging tb -> repo A -> prod tb`
Only staging can write to repo A, production can only pull from repo A, never push (not even by accident). I can control this via access token privileges of git.

At the same time, I would like to version control *other entities* such as devices and assets of prod tb to repo B.
`prod tb <-> repo B`
Repo B is exclusive for tracking devices and assets of prod tb. This will be auto-commit so that every changes to attributes or relations can be reverted at any time.

Unfortunately, I cannot think of any way of achieving this using only 1 repository and access token privileges.

**Describe the solution you'd like**
Allow adding multiple git repositories.

I think my use case is quite legit. Please let me know what you think. 😄

**Comment by Raven888888** [comment]
I just realised that auto-commit only works for Dashboard and Rule Chain, not for entities like Asset or Device. Any reason why they are excluded?

**Comment by Raven888888** [comment]
Another question: I cannot find any API on the swagger UI that can allow me to set repository in a programmatic way. Do I always have to do it on UI?

**Comment by devaskim** [comment]
> I cannot find any API on the swagger UI that can allow me to set repository in a programmatic way
See [admin controller](https://demo.thingsboard.io/swagger-ui/#/admin-controller/saveRepositorySettingsUsingPOST)

**Comment by Raven888888** [comment]
Thanks @devaskim , I missed out that section. Appreciate it!

**Comment by Raven888888** [comment]
A side thing, I noticed this error in logs, although seems to have no impact on version control feature. Not sure if this is intended?

```
2022-09-27 13:19:37,549 [JGit-FileStoreAttributeWriter-2] ERROR org.eclipse.jgit.util.FS - Cannot save config file 'FileBasedConfig[/home/thingsboard/.config/jgit/config]'
java.io.IOException: Creating directories for /home/thingsboard/.config/jgit failed
        at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:412)
        at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
        at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:219)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:744)
        at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$4(FS.java:430)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Raven888888** [comment]
@devaskim For the above error, I see that inside container there is not directory `/home/thingsboard/`, hence create directory command failed. Do we have to mount volume to create this directory inside the container?

**Comment by devaskim** [comment]
@Raven888888 I don't know

**Comment by Raven888888** [comment]
> A side thing, I noticed this error in logs, although seems to have no impact on version control feature. Not sure if this is intended?
> 
> ```
> 2022-09-27 13:19:37,549 [JGit-FileStoreAttributeWriter-2] ERROR org.eclipse.jgit.util.FS - Cannot save config file 'FileBasedConfig[/home/thingsboard/.config/jgit/config]'
> java.io.IOException: Creating directories for /home/thingsboard/.config/jgit failed
>         at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:412)
>         at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
>         at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:219)
>         at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:744)
>         at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$4(FS.java:430)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> ```

@ashvayka @den1jkee any idea about this error?

**Comment by den1jkee** [comment]
@Raven888888 
Can you describe in more detail what you do and how you get this error? (Your setup, how and when this error does)

**Comment by Raven888888** [comment]
Sure @den1jkee 

I have 2 setups, both have the same error, although they are seemingly harmless at the moment, everything still works as expected (able to create version, sync version, etc).

Setup 1:
- Docker [setup](https://thingsboard.io/docs/user-guide/install/docker/)
- ThingsBoard Version: 3.4.1
- OS Name and Version: Ubuntu 20.04

Setup 2:
- Helm [setup](https://artifacthub.io/packages/helm/thingsboard/thingsboard/0.1.3-rc.1)
- ThingsBoard Version: 3.4.1
- OS Name and Version: Ubuntu 20.04

In both setups, setup a git repository in version control UI, and check the log for the error.
I think it only happens once in the lifecycle of the TB instance, until its next restart.

**Comment by Ultrazombie** [comment]
Unfortunately, this thread is already full of different questions.
Please create a new ticket with a detailed description if this is still recurring on a fresh version of thingsboard, as there have been VC improvements in 3.4.1-> 3.6.4
