### ISSUE TITLE
[Question] How can I update/add a server side attribute in a rule chain?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#7286]
**Component**

 * Rule Engine

**Description**
Is it possible to change/add a server attribute based on incoming telemetry? I want to add a timestamp server attribute based on a telemetry value. I understand there is a save attributes node but this expects POST_ATTRIBUTES_REQUEST message types, whereas I need to add server attributes based on POST_TELEMETRY_REQUEST messages.

**Environment**

 * OS:  Linux
 * ThingsBoard: Cloud
 * Browser: FireFox

**Comment by ashaforost** [comment]
You can save your telemetry and, after that, use the transformation script rule node to add the timestamp attribute to the message and change the message type to POST_ATTRIBUTES_REQUEST. Next, just add a save attributes rule node.

**Comment by OzyOzk** [comment]
> You can save your telemetry and, after that, use the transformation script rule node to add the timestamp attribute to the message and change the message type to POST_ATTRIBUTES_REQUEST. Next, just add a save attributes rule node.

Yes I just managed it. Before when I tried setting msgType in the transformation script it said read only. I'm just setting it in the return statement now.

**Comment by ashvayka** [comment]
@OzyOzk , please share your script/rule chain for everyone else to save time on similar tasks.

**Comment by devaskim** [comment]
> I tried setting msgType in the transformation script it said read only

Don't try to change existing `msg` object. Instead create new one, set there _POST_ATTRIBUTES_REQUEST_ type and return it.

**Comment by OzyOzk** [comment]
Here's the transformation script. 

`return {msg: {last_unique_telemetry_ts: Date.now()}, metadata: metadata, msgType: "POST_ATTRIBUTES_REQUEST"};`

**Comment by jiekechoo** [comment]
I create a new attribute to device, but I can't use the new attribute in **Device Profile's Alarm Rules**. I have to modify the attribute manully. reference #7313

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
