### ISSUE TITLE
Get users email of customer.

### ISSUE THREAD

**Issue by ANUR46** [thingsboard/thingsboard#7289]
**Is your feature request related to a problem? Please describe.**
I am using ThingsBoard Community version and trying to send alarm data through email to the each users of the customer to whom the device is assigned. I have checked the rule chain section there is node is available to get email of only customer but not any rule node to get users email of a customer.

**Describe the solution you'd like**
Provide rule node to get users email of customer.

**Comment by devaskim** [comment]
There is REST API node, so you could request info about [all customer's users](https://demo.thingsboard.io/swagger-ui/#/user-controller/getCustomerUsersUsingGET)

**Comment by ANUR46** [comment]
> There is REST API node, so you could request info about [all customer's users](https://demo.thingsboard.io/swagger-ui/#/user-controller/getCustomerUsersUsingGET)

But How can I get CustomerID ?

**Comment by devaskim** [comment]
Well, maybe I something missed, but there is no direct way to get ID. But you can get it from [device information](https://demo.thingsboard.io/swagger-ui/#/device-controller/getTenantDeviceUsingGET). Metadata of rule chain message has `deviceName` field.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
