### ISSUE TITLE
[Bug] LwM2M transport pod fails to start with java.lang.UnsupportedOperationException: Not a number: {"id":0,"value":0}

### ISSUE THREAD

**Issue by radicalrad** [thingsboard/thingsboard#7292]
**Describe the bug**
ThingsBoard micro service deployment on AWS EKS stopped accepting lwm2m registration requests after spike in load.

LwM2M transport logs indicated that it got disconnected from Kafka

`2022-09-15 12:57:11,295 [kafka-admin-client-thread | adminclient-4] INFO  o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-4] Node 1 disconnected.
2022-09-15 12:57:11,341 [kafka-admin-client-thread | adminclient-3] INFO  o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-3] Node 2 disconnected.
2022-09-15 12:57:15,241 [kafka-admin-client-thread | adminclient-7] INFO  o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-7] Node 2 disconnected.`

Problem persisted for over 24 hours without crash or restart of a pod while lwm2m client registration remained to timeout.

Attempt to restart pod with lwm2m transport failed on application start up with following message in logs:

`022-09-15 13:26:47,815 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.UnsupportedOperationException: Not a number: {"id":0,"value":0}`

Stack trace indicates that error is raised during application initialisation 
`
org.thingsboard.server.lwm2m.ThingsboardLwm2mTransportApplication.main(ThingsboardLwm2mTransportApplication.java:38)
`

I would appreciate your support in resolving this. There has been no configuration changes on EKS or application.

** Server Environment**

* own setup
  * Micro service cloud deployment on AWS EKS following https://thingsboard.io/docs/user-guide/install/cluster/aws-microservices-setup/
  * ThingsBoard Version: 3.4.1
  * ThingsBoard containers from AWS EKS guide without any changes

**Client Environment**

**Leshan Lwm2m client**

* Connectivity
  * CoAP
  * Lwm2m

**To Reproduce**
1. Deploy things board as per https://thingsboard.io/docs/user-guide/install/cluster/aws-microservices-setup/. Identical EC2 instance types are used, ElasticCache and MSK services are deployed as per guide.
2. Compile Leshan demo Lwm2m client https://github.com/eclipse/leshan/tree/master/leshan-client-demo
3. Create 100 LwM2M devices in ThingsBoard and run 100 leshan clients with registration update set to 1 second (argument -cp 1). Following command starts client in no security mode.

`-jar leshan-client-demo.jar -cp 1 -n ${endpoint-name} -u coap://${coap_load_balancer_url}:5685`

4. Observer leshan client logs for “Registration failed: Timeout” message

**Expected behavior**
After less than 10 minutes lwm2m clients are unable to correctly report registration update with server. Observe log of LwM2M transport and try to restart pod.

**Comment by ban2derlog** [comment]
Hi, do you send any telemetry from Leshan or only Registeration requests?
How many messages per minute do you use with 100 Devices?
Additionally, change in your deployment [this line](https://github.com/thingsboard/thingsboard-ce-k8s/blob/5c4a9495f890e2f042341eb54bacf825992743dc/aws/microservices/transports/tb-lwm2m-transport.yml#L45) to:
` <root level="DEBUG"> `
Apply and check POD logs after Leshan works for 10 mins. 
This will gather more information from service, but also will take more storage for logs.

**Comment by radicalrad** [comment]
Thank you @ban2derlog for quick reply.

When system crashed test devices did have active telemetry consumption but load related to this was limited to single read of 6 attributes from each devices. Major load was coming from registration requests.

I changed logs to DEBUG as advised, deleted and re-applied StatefulSet providing lwm2m transport service. Collected debug logs still indicate startup issue:
`
2022-09-19 13:34:28,690 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.UnsupportedOperationException: Not a number: {"id":0,"value”:0}
`

Deleting tb-lwm2m-transport StatefulSet should have fixed any possible corrupt state in container. I am puzzled and not sure how to progress with this issue. Any hint on rootcause and possible solution is greatly appreciated.  I am attaching gathered logs - [tb-lwm2m-transport.log](https://github.com/thingsboard/thingsboard/files/9599940/tb-lwm2m-transport.log)

**Comment by ban2derlog** [comment]
Hi,
Do you try to flush Redis cache with this error?
Here can be issue when cached value is loaded from Redis and container can't proceed it.
Also, was there issues with Kafka (Amazon MSK) during test?

**Comment by radicalrad** [comment]
Hello ban2derlog,

Thanks for asking.

In short we gave up troubleshooting Thingsboard and moved on with different platform. Shortly after raising this ticket I reached out to Thingsboard sales asking for commercial support by Thingsboard professional services but there was no interest to support us on commercial basis. I will close this issue.

**Comment by ponomarenkotema** [comment]
Hello, 
I got the same issue. Flush Redis cache is helping. But maybe you have solution or workaround for this?
