### ISSUE TITLE
[Bug] Upgrade from 3.3.3 -> 3.4.1, .upgradeversion file shows wrong version

### ISSUE THREAD

**Issue by Raven888888** [thingsboard/thingsboard#7296]
**Describe the bug**
Before upgrade, TB is 3.3.3:
```bash
$ cat mytb-data-cassandra-bak/.upgradeversion
3.3.1
```

After upgrade, TB is 3.4.1:
```bash
$ cat mytb-data-cassandra/.upgradeversion
3.3.3
```

Upgrade process was successful.

The `.upgradeversion` file is supposed to show the version *before* the upgrade, even though the upgrade was successful?

**Comment by den1jkee** [comment]
Thank you for your suggestion; 
We are accept improvement of our platform, so I've added this request to our backlog ([PROD-1659](https://thingsboard-portal.atlassian.net/browse/PROD-1659)) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by Raven888888** [comment]
Thank you @den1jkee 

Is the backlog available to public, or internal only?
Sometimes exciting new features are added, but there are no discussions or notes on why certain things are done in certain ways. Such as https://github.com/thingsboard/thingsboard/pull/6534

**Comment by den1jkee** [comment]
We have an internal backlog and when the developers complete this request, they will publish an external backlog with infrormation about fixes

**Comment by alyf80** [comment]
It seems that whatever is being used to update versions for a new release is not changing the `pkg.upgradeVersion` property [here](https://github.com/thingsboard/thingsboard/blob/6674c457f6eeee70ae7e17d6a2cd6e434b5c6361/msa/tb/pom.xml#L41)
