### ISSUE TITLE
[Bug] Incorrect display of Y axis in case of multiple devices behind datasource

### ISSUE THREAD

**Issue by kalutkaz** [thingsboard/thingsboard#7298]
The graph in case of a single device:
![image](https://user-images.githubusercontent.com/43555187/191003262-ff5b24e1-153d-41ee-ad79-2d668541988e.png)

In the case of 2 devices humidity axis becomes duplicated:
![image](https://user-images.githubusercontent.com/43555187/191003326-7c4ac885-a1c2-4ed2-a2b3-fcf3fa7d5784.png)

Looks like the UI component duplicates the axis incorrectly.

**Comment by ashaforost** [comment]
Check whether you've enabled the 'show separate axis' option in the "humidity" data key configuration tab, and if so, disable it:
![image](https://user-images.githubusercontent.com/47900737/191279809-517b3c09-a5f9-464e-aea3-960e3c98a17a.png)
