### ISSUE TITLE
Enable Data Export checkbox is missing in the dashboard widget

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7300]
Enable Data Export checkbox is missing in the dashboard widget<br>
![image](https://user-images.githubusercontent.com/17080208/191165855-af3eac79-8f38-4063-84ee-becc522f39cd.png)

ThingsBoard version 3.4.0

**Comment by Backdraft007** [comment]
It is not under settings tab. Have a look at the Data tab.

**Comment by sunyong-mwi** [comment]
I found it in the Data tab. Thanks for the help
