### ISSUE TITLE
[Question] $[messageKey] not working in Alarms?

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7302]
**Component**

 * Rule Engine

**Description**
Hello thingsboard community! I have a small problem with creating Alarms which name is based on msg. 
Situation is: When I create an alarm with Alarm type with just a classical string name it gets triggered every time it shloud.
When I type $[zone] it never gets triggered/propageted. What I am doing wrong here? In past it was working just fine. 
My alarm:
![image](https://user-images.githubusercontent.com/58517178/191194840-bdbb86bf-d2c8-40a7-81ed-d01e2ea26b0e.png)
Debug Data IN:
![image](https://user-images.githubusercontent.com/58517178/191195130-9a0bfbf2-c494-4976-85d1-bf642f3fee9c.png)
Debug out/ALARM:
![image](https://user-images.githubusercontent.com/58517178/191197982-51da6d4f-58ce-4cec-a540-ec42d51fef40.png)

I just dont see it in my alarm table.... 

Thanks for any help.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by devaskim** [comment]
Enable *Use message alarm data* option

**Comment by samokomo** [comment]
Thanks for help, I figured it out, problem was somewhere else - apparenty clearing one alarm and creating another one with $[zone] was causing it. I deleted clear alarm node and it started working as intended
