### ISSUE TITLE
[Question] Uplink Data converter : How to update the device profile if the deviceType has changed in the data converter ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#7305]
Hello, I would like to know how to update the profile of a device if its deviceType has changed in the data converter (uplink).
For example : 

I have a device that has the deviceType equal to "Version_1.0.0" in Thingsboard.

Then after a while, I change the payload sent by this device and I want that this device has now the deviceType : "Version_1.0.1".

Is it possible to automatically assign the new profile "Version_1.0.1" to this device ? 
The thing that I don't understand, is : 
In my events tab of my data converter, the device has the correct deviceType (the new one) in the output of my data converter.
But in the list of all of my devices, this device keeps having the old device Profile.
How to keep the deviceProfile up to date ?
Thanks in advance,

Lucas

**Comment by lucasKapf** [comment]
I have achieved it with a Rule Chain, but maybe an easier way exists ?

**Comment by lucasKapf** [comment]
In fact my Rule Chain doesn't work properly. Issue re opened

**Comment by Lenteguppie** [comment]
Hello @lucasKapf, 

Were you able to find a fix for this issue? I am encountering the same issue at the moment.
