### ISSUE TITLE
[Question]  Device doesn’t receive device name while provisioning

### ISSUE THREAD

**Issue by Jonnik84** [thingsboard/thingsboard#7306]
**
I want my devices to send thingsboard a provision request I sent only provision secret and provision key

I want things bought to generate device name. Now I want user to understand what name device has got. And show it on device screen.

In documentation I see, that server should respond provision request with access token and device name.

 I don’t receive device name.

Please tell me how to bypass this .. maybe it’s a bug .
maybe it is possible to receive device attributes like name, label… but I don’t found how to do this in documentation …
Maybe with some kind of rules…

**Comment by devaskim** [comment]
The docs says that [device should send its name](https://thingsboard.io/docs/pe/user-guide/device-provisioning/?mqttprovisioning=mqtt-basic#provision-device-apis).
Where did you find what server generates device name?
