### ISSUE TITLE
Using attributes as remote configuration.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#731]
I am trying to remotely configure my device using the attributes.
As it seems with the current implementation, it is not possible to do so properly. Specifically, there are many problems when the device may get offline. Let me explain.

My device has an LCD interface, with a menu that allows the end user to adjust the device settings to his/her liking. I use attributes to monitor these settings, but I would also like to be able to also adjust them remotely. The device posts its internal settings as client attributes, and gets the new configuration as shared attributes.

Unfortunately since **the device cannot control the shared attributes**, I have only two options:

- Subscribe to shared attributes. This way I can remotely change the settings. However this implies that the device MUST be online. This is not possible to guarantee, and generally a nightmare to manage at large scale installations.
**Example:**
1. The device is offline.
2. I set an attribute.
3. The attribute change event is lost by the device, and my configuration is not applied.

- During boot the device may get the shared attributes that are stored to the server. However this way the user is no longer able to configure the device. The device is not able to tell which setting came last (the one in the internal memory, or the server attribute), and will block to the server attributes. 
**Example:**
1. I set an attribute, say `foo` to `3`.
2. The user sets the attribute `foo` to `5`. (Through the LCD, not Thingboard).
3. **The device cannot set the new value to the shared attribute!** Old configuration remains in server.
4. Device turns-off.
5. Device turns-on. Its internal memory tells that the setting `foo` is `3`, but Thingsboard says it is `5`. Which is the correct? Is the server data outdated? Or was new configuration while the device was offline?

**Comment by fotis400** [comment]
## Proposed Solution 1

Allow the device to manipulate the shared attributes. In my second example it would be able to store the new setting to the server, and it would be sure that value it gets it is the last one actually set.

See also #148 .

**Comment by fotis400** [comment]
### Proposed Solution 2

Ditch the whole attributes systems. That thing with the client/shared/server attributes does not look like a good idea to me.

**Unify the attributes storage**, and implement a permissions system. Each attribute may be set as "read", "write", "read/write" for both the devices and the server. This way the all the above would be very easy to be implemented, while also the administrator would have total control on the attributes.

**Comment by caoyingde** [comment]
I also have the same problem. If the device updates the attribute problem?

**Comment by eykamp** [comment]
This is essentially how it works now, except there is no attribute group that both the client and server can write to.  Though I prefer the cleanliness of the permissions approach, adding a fourth attribute group ("common"?) might also achieve the same goal.

**Comment by fotis400** [comment]
@eykamp A new attribute group may indeed solve this issue, but I don't thing it will be an optimal solution. Most importantly I think it will over-clutter the attributes interface.

I will create a new issue where I will present my proposition more extensively.

**Comment by mcpicoli** [comment]
There is no sense at all in having a group of attributes that is called "shared", but only the server can write to. The server attributes are RW to the server, invisble to the client. The client attributes are RW to the client, but RO to the server.

The simplest solution to this problem would be making the shared attributes writable by the client, be it via separate API method, via subscription-like objects ("sharedKeys: {...}, clientKeys: {...}") or via a rule-chain-esque "hack" of having prefixes "shared_", "cs_" and "ss_" for each type of attribute.

The methods proposed elsewhere of having a unix-like filesystem/permissions for the attributes, even if being much better, IMHO would demand a lot of work.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
