### ISSUE TITLE
ui-ngx 404

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7315]
**Component**

 * UI

**Description**
After modifying the ip and port in the proxy.conf.js file in the ui-ngx project, after executing yanr build, the files in public are deployed in nginx, and after starting and running, they appear after http://ip:port/login POST: /api/noauth/oauth2Clients?platform=WEB
404: Not Found

**Environment**
 * OS:  windows 10
 * ThingsBoard: 3.4.0
 * Browser: chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
