### ISSUE TITLE
[Question] custom widget timewindow update notification

### ISSUE THREAD

**Issue by olafpeters1962** [thingsboard/thingsboard#7317]
**Component**
 * UI

**Description**
I created a custom widget that displays a Grafana panel in an Iframe. Everything works fine, but I'm unable to determine how to get a notification when the timewindow is changed by a user (so that I can redraw the panel).
I installed the onDataUpdated and onLatestDataUpdated functions, but they are only invoked when the data itself is updated (as expected), not the timewindow. Neither the onResize is invoked. Is there a way to get notified when the user edit/updates the dashboard timewindow?

**Environment**
 * OS:  Ubuntu Linux 22.04
 * ThingsBoard: 3.4.1
 * Browser: Crome

**Comment by devaskim** [comment]
Custom widget API [lets you to create](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L66-L69) (call from `self.ctx.subscriptionApi`) additional data subscriptions besides default one called `self.ctx.defaultSubscription`. Each subscription [has been notified](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L231) when time window is changed. 
But subscription API requires not one or two lines of code to init subscription object. As a reference you can look at [how this is done](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts#L965) for default data subscription, i.e. `self.ctx.defaultSubscription`

**Comment by devaskim** [comment]
@olafpeters1962 I got working example:
```
    self.ctx.dashboard.dashboardTimewindowChanged.subscribe(
        (dashboardTimewindow) => {
            console.log('Dashboard windows changed');
        }
    );
```

**Comment by olafpeters1962** [comment]
@devaskim Thx very much, this works and is exactly what I needed! I now have a smooth and fully operational Thingsboard / Grafana integration, showing Grafana panels in a Thingsboard custom widget.

**Comment by devaskim** [comment]
@olafpeters1962 Great that your idea works now!

Could you share your experience how you did that?

**Comment by devaskim** [comment]
@olafpeters1962 Thanks(
