### ISSUE TITLE
Can not create relation from device to user in rule chain

### ISSUE THREAD

**Issue by JonathanTsai1982** [thingsboard/thingsboard#7319]
**Component**
 * Rule Engine

**Description**
I try to create relation from device to user，the debug events seems every thing is fine, but the relation didn't be created. But if I create relation from device to Asset, it's work correctly.
![001](https://user-images.githubusercontent.com/104144181/191903730-e4137373-fe57-4be6-83b0-5eacc2f56340.png)
![002](https://user-images.githubusercontent.com/104144181/191903739-765351a1-77a3-4211-a460-5f7d535a82a3.png)

**Environment**
 * OS:  windows 10
 * ThingsBoard: latest
 * Browser: chrome 105.0.5195.127

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce this issue on the PE 3.7
I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant.
