### ISSUE TITLE
Deleting client attributes.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#732]
As far as I can tell there is no way to delete the client attributes. Please add this functionality.

For example, after a firmware update, where there may be changes in how the device uses the attributes. Old attributes may not be used any more, and Thingsboard will be cluttered with zombie attributes. The tenant administrator would be able to fix this, by deleting any unneeded attributes.

Or even delete everything, and let the device re-create any attribute that it needs.

**Comment by stevexm** [comment]
Hi, want to echo what fotis400 commented. While not critical would it be possible to enable deletion of device client attribute(s)? Maybe I missed something in the docs?

Anyway, what a fantastic platform. Looking forward to becoming a professional edition customer after working through various use cases on the demo server.

**Comment by vparomskiy** [comment]
in the latest Thingsboard, there is an API for telemetry\attributes removing
https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/deleteEntityAttributesUsingDELETE

**Comment by sateeshg28** [comment]
I want to remove Client Attribute of device thingsBoard. In 'Scope' and 'keys' fields what I need to pass?

**Comment by manjrekarom** [comment]
@sateeshg28 

> SERVER_SCOPE
> SHARED_SCOPE
> CLIENT_SCOPE

https://github.com/thingsboard/thingsboard/issues/2165#issue-520952575

**Comment by hayschan** [comment]
Did you solve this problem eventually?

I still don't see a way to delete the client attribute on Thingsboard Community Edition (CE) GUI.

![image](https://github.com/thingsboard/thingsboard/assets/25737801/82c89ddf-1940-4561-9ea7-21bf1b3d4557)

**Comment by rpcai** [comment]
Requesting that this be re-opened. The UI is indeed inconsitent, and using API (deleteEntityAttributes) feels like a clunky workaround.
