### ISSUE TITLE
[Question] [Issue] How to speed up loading

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#7322]
**Component**

 * UI 

**Description**
As we can see in the picture, the UI part is loading very slowly on 3G or slow networks. The size of the downloaded resources is large (14.8Mb). Download 1.2 minutes. How can I reduce the load?
![image](https://user-images.githubusercontent.com/87794982/191941745-88539862-f859-4d51-b020-b1f8842d3b9e.png)

**Environment**

 * OS:  Sentos Steam 8
 * ThingsBoard: 3.4.1 PE
 * Browser: Chrome

**Comment by devaskim** [comment]
If you are using haproxy, see [my solution](https://github.com/thingsboard/thingsboard/issues/7203#issuecomment-1236388994)

**Comment by psxbox** [comment]
I don't use a proxy

**Comment by psxbox** [comment]
resources are not being cached.

**Comment by devaskim** [comment]
Finally I [implemented this feature](https://github.com/thingsboard/thingsboard/pull/7333). Waiting for review from core team...

**Comment by psxbox** [comment]
It would be better if they released it sooner. For example, version 3.4.1.1. Because there is some problem with clients.

**Comment by devaskim** [comment]
If I were in your shoes, I'd not wait for release but install proxy on machine where Thingsboard is running. Besides there is already [official doc](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-rhel/) fro CentOS from core team.

**Comment by psxbox** [comment]
> Если бы я был на вашем месте, я бы не стал ждать релиза, а установил прокси на машине, где работает Thingsboard. Кроме того, уже есть [официальный док](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-rhel/) для CentOS от основной команды.

Thanks for the reply. I will consider.

**Comment by psxbox** [comment]
> If I were in your shoes, I'd not wait for release but install proxy on machine where Thingsboard is running. Besides there is already [official doc](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-rhel/) fro CentOS from core team.

Thanks for the reply. I will consider.

**Comment by albertorivelli** [comment]
Hi, is there any solution to this? I don't want to install HAProxy and I don't want to recompile either by adding the patch by @devaskim (pull request #7333 has not been merged in the official thignsboard release).
JS application files are quite big and the android app get stuck many times. I don't update the server side very often so it'd be much better to cache all those js files that are around 20MB.

Please help
Thanks
