### ISSUE TITLE
AuthenticationServiceException: Authorization header cannot be blank!

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#733]
**Hello, I got the following error while running the thingsboard. How should I fix it?
I haven't changed the UI**

![tb](https://user-images.githubusercontent.com/30205233/39172078-391de140-47d3-11e8-8f72-9ec3a7e2f760.png)

**Comment by mp-loki** [comment]
What did you try to do? Did you call the REST API without a token?
