### ISSUE TITLE
PE V3.4.1 downlink to Chirpstack V4 integration failed

### ISSUE THREAD

**Issue by cndingtek** [thingsboard/thingsboard#7331]
Dear all,
During we send downlink from PE 3.4.1 to Chirpstack V4, we did not get the downlink showed on the chirpstack queue page. While we check the log, the PE send out downlink like below at the Chirpstack integration. 
{
    "metadata": {
        "fPort": "8",
        "DevEUI": "7cf95720fc015fef",
        "isPending": "true",
        "confirmed": "true"
    },
    "payload": "Nzg1NA=="
}
And we capture the packet at the chirpstack hosted server and found below packet:
{"deviceQueueItem":{"confirmed":"true","data":"Nzg1NA==","fPort":"8"}}
path is /api/devices/7cf95720fc015fef/queue
It get response 200 code from the chirpstack server. 
But finally it did not showed on the queue tab of Chirpstack. We checked the document and tested the swagger UI of chirpstack, we found that the required objects as below:
"queueItem": {
    "confirmed": true,
    "data": "ODAwMQ==",    
    "fCntDown": 3,
    "fPort": 10,
    "id": "string",
    "isPending": true       
  }
if there is codec, object key is added into and will be with high priority than data key. 
For the Chirpstack V3, we tested with PE 3.3.2, it worked well. But for Chirpstack V4, we updated from 3.3.2 to 3.4.1 PE, neither work for any version. 
Please check if the update of Chirpstack V3/V4 result in the failure, and if there is any way we can make the downlink works.
Thanks for your time!

**Comment by dealnat** [comment]
Hello. I've been testing Downlink for Chirpstack V4 integration with thingsboard and messages are appeared on the latest 3.8.1 version. There is a bug that integration converts all datatypes to string, but Chirpstack can't handle it (for example "Confgirmed" : "true" ) so I guess this is the possible reason of your issue too. Please try to reproduce the issue on the latest version - if problem persist please open new issue.
