### ISSUE TITLE
MQTT QoS 2 compatibility

### ISSUE THREAD

**Issue by AdrienAdB** [thingsboard/thingsboard#7334]
Hi all,
I was wondering why MQTT QoS 2 isn't compatible with TB.
https://thingsboard.io/docs/reference/mqtt-api/#mqtt-basics

I have QoS 2 requiremement for 1 of our project.

Netty 4.1 MQTT codec seems compatible: https://netty.io/4.1/api/io/netty/handler/codec/mqtt/MqttQoS.html

I would be happy to help on testing if needed.

**Comment by Ultrazombie** [comment]
For now, ThingsBoard does not support qos2 and does not plan.
We encourage you to consider using TBMQ as an alternative solution (https://thingsboard.io/docs/mqtt-broker/user-guide/qos/)
