### ISSUE TITLE
Remove sign up from thingsboard login

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7344]
Kindly suggest how to remove sign up option on the thingsboard white labelled login page. I have explored self registration option, but i couldn't see any option to disable sign up.

**Comment by mubashirp** [comment]
I have not given any settings under self registration to delete. It Is completely blank, also the delete button is disbaled. I checked under self registration to find any option to disable sign up option on the white labelled login page, but I couldn't find any options.
Can you kindly suggest how we can remove sign up option on the login page.

**Comment by Civilduino** [comment]
I am having exactly the same problem.

**Comment by Civilduino** [comment]
Basically I want to remove this div from the login webpage.

`<div _ngcontent-hfr-c211="" fxlayout="row" class="no-account-section" style="flex-direction: row; box-sizing: border-box; display: flex;"><span _ngcontent-hfr-c211="" translate="" class="no-account-message">Do not have an account?</span><a _ngcontent-hfr-c211="" routerlink="/signup" href="/signup">Sign up</a></div>`

**Comment by dhaval2017** [comment]
Did you tried to use css?

**Comment by Civilduino** [comment]
I tried CSS and it "works". I could not hide the main `div` using the `class="no-account-section"` because I see that the display options are giving explicitly in the `div` itself, overriding the class?

I could hide the `class="no-account-message"` and the `<a>` element with this code:

```
.no-account-message{
    display: none;
}

a[href^="/signup"] {
  display: none;
}
```

**Comment by mubashirp** [comment]
Wow, that works!!!! Thank you @dhaval2017 @Civilduino @Backdraft007

**Comment by Civilduino** [comment]
Close issue if you are happy with the solution :)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
