### ISSUE TITLE
[Bug] Dragable polygon labels 

### ISSUE THREAD

**Issue by Dmuldoraf** [thingsboard/thingsboard#7346]
**Description**
The polygon labels were dragged with the mouse cursor, while hover over them. This bug occured after the latest update to v3.4.1. The polygons are linked with a custom action. 

**Server Environment**
Thingsboard v3.4.1 

**Client Environment**
Desktop
Windows 10
Chrome Version 105.0.5195.127
Firefox 105.0.1 (64-bit)

**To Reproduce**
1. Create an imagemap 
2. Create assets with polygon coordinates
3. Add them to the map
4. Use polygon label function `return  dsData[dsIndex]['Label'];`
5. Hover with the cursor over the polygon

**Screenshot**

![dragging_labels](https://user-images.githubusercontent.com/40173514/192762931-6238cdaf-8beb-44bd-8f7d-1d7cd901164c.gif)

Best regards :)

**Comment by den1jkee** [comment]
hi,
Thank you, this bug will be fixed in 3.4.2. Already in pull request
(https://github.com/thingsboard/thingsboard/pull/7174)

**Comment by shayMZ** [comment]
I don't know if it is the right place, but when I set show label, the map is stuck with the loading message
