### ISSUE TITLE
[Feature Request] Math rule node

### ISSUE THREAD

**Issue by ashvayka** [thingsboard/thingsboard#7347]
**Is your feature request related to a problem? Please describe.**
The rule node applies the math function and saves the result into the message and/or database. 

You may use 5 types of arguments:

 * Constant;
 * Value from the message body;
 * Value from the message metadata;
 * Value of the attribute that belongs to the message originator (device, asset, etc). The value should be of Numeric type or string that is convertible to float;
 * Value of the latest time series that belongs to the message originator (device, asset, etc). The value should be of Numeric type or string that is convertible to float;

Primary use case for this rule node is to take one or more values from the database and modify them based on data from the message. For example, you may increase `totalWaterConsumption` based on the `deltaWaterConsumption` reported by device.

Alternative use case is the replacement of simple JS `script` nodes with more light-weight and performant implementation. For example, you may transform Fahrenheit to Celsius (*C = (F - 32) / 1.8*) using CUSTOM operation and expression: *(x - 32) / 1.8)*.

The execution is synchronized in scope of message originator (e.g. device) and server node. If you have rule nodes in different rule chains, they will process messages from the same originator synchronously in the scope of the server node.

The result of the function may be added to the message body or metadata. You may also save the result to the database as an attribute or time-series.

**Comment by devaskim** [comment]
@ashvayka Could you explain if [this feature request](https://github.com/thingsboard/thingsboard/issues/7703) is the same?
