### ISSUE TITLE
Will the frontend have an angular4 version later?

### ISSUE THREAD

**Issue by 865077695** [thingsboard/thingsboard#735]
Will the frontend have an angular4 version late

**Comment by untilbit** [comment]
It would be great if the frontend was built using Angular 2+ (preferably version 5) or Vue.js

**Comment by guojerry** [comment]
I am not sure how much effort will be taken to porting the existing UI to angular4. If somebody wants to do it, I'll give a hand.

**Comment by snzip** [comment]
I am afraid that it's hard to migrate UI to Angular in short term :)

**Comment by untilbit** [comment]
It is, becuase angular 2+ it's very different than angular js and it will need a rewrite

**Comment by toti1212** [comment]
Will be amazing, but I think the effort will be huge 😞

**Comment by Delapouite** [comment]
Starting from version 3.0.0, released last year the frontend is now in Angular 2+ : https://thingsboard.io/docs/reference/releases/#v30-june-1-2020

So I guess this issue can now be closed.
