### ISSUE TITLE
[Feature Request] The ability to change the position of the items in the Action list

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#7352]
![image](https://user-images.githubusercontent.com/87794982/193077928-8c833b6d-3424-479f-a43f-08dfef4bec88.png)

![image](https://user-images.githubusercontent.com/87794982/193078165-dddbb6e2-ca85-49d6-a49a-3ddb458c6d18.png)

**Comment by devaskim** [comment]
I also need this feature but leave it till late. But you push me to action: #7356 waiting for review
Feel free to contact, compatriot ;)

**Comment by psxbox** [comment]
Thanks

**Comment by vvlladd28** [comment]
Resolve
