### ISSUE TITLE
[Question] Using variables in scheduler

### ISSUE THREAD

**Issue by peterandthejetsons** [thingsboard/thingsboard#7358]
**Component**
Thingsboard PE latest version
 * Scheduler

**Description**
Hello! 

I'd like to ask is there a way (with rule engine or any other) to use a variable in scheduler. I'd like to get Sunrise/Sunset dates from this site API (https://sunrise-sunset.org/api) with simple rule chain, and save the dates as telemetry to a Customer or an Asset. After that, I'd like to use saved dates as variable in scheduler like this:

![sunrise](https://user-images.githubusercontent.com/104279990/193409376-960455c6-c359-4065-9087-95ed3cb203a1.PNG)

I'd like to ask your help in this issue. Thanks in advance.

Best regards,
Peter

**Comment by ketaeishi** [comment]
Same issue here. Did you find something?

**Comment by peterandthejetsons** [comment]
Unfortunately not. I'll let you know if i'll found the solution.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
Please make a feature request issue if we need to implement this feature.
