### ISSUE TITLE
[Question] Remove "Export JSON configuration" from costumer dashboard

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7363]
**Component**

 * UI
 * Generic

**Description**
I want to remove the "Export JSON configuration" option from my costumers dashboard. They should just be allowed to export .png, .jpeg or .pdf.

I cannot find how to do this, any help?

Thanks

**Environment**

 * OS:  macOS
 * ThingsBoard: PE Cloud
 * Browser: Chrome

**Comment by Civilduino** [comment]
Solved using the Advance CSS option under the White Label menu.

I selected the button with the CSS selector in Chrome and added `{display: none;}` in the CSS.

**Comment by merrittholmes7** [comment]
Hi, What was the CSS Selector you used for this and against what element?

**Comment by merrittholmes7** [comment]
I figured it out: 
button[role="menuitem"]:nth-last-child(1) {
    display: none !important;
}
