### ISSUE TITLE
[Question] Create Asset and Asset Type

### ISSUE THREAD

**Issue by kandrianatos** [thingsboard/thingsboard#7364]
**Component**
 * Generic

**Description**
I just installed thingsboard community edition localy on my windows machine, i tried to create a new asset, in the asset type field the only asset type available was the TbServiceQueue (witch is unable to save asset with that type). After that i triyed to find where can i create an asset type, but i can't find that feature. 

**Environment**
 * OS:  Windows 11 Pro Local Installation

**Comment by Civilduino** [comment]
Just create the Asset and Write the name of the Asset type you which. It creates automatically.
![image](https://user-images.githubusercontent.com/27728926/193623436-d230d805-8fda-47bc-a6d8-156063041d15.png)

**Comment by kandrianatos** [comment]
Right! Thanks!
