### ISSUE TITLE
[Bug] Blocking the rule chain for no apparent reason

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#7368]
**Describe the bug**
In several instances of thingsboard, without any explanation, errors start to appear in the logs of timeout to process the message.
At that moment, the chain of rules is blocked and is not able to accept any incoming message, regardless of whether the node where the timeout error occurs is used or not.
Similarly, it is not capable of accepting even a simple attribute write through the API, which I understand makes use of the chain of rules.

To fix this, we need to restart the entire platform.

I don't know if it is a logical and fixed operation or a bug, but it is important that we discover what it is since there are systems in production that cannot face a problem of this caliber.

I understand that if it is a timeout or script block problem due to 3 consecutive attempts failing, the rest of the chain of rules should continue to work.

Thanks for the help.

**Your Server Environment**

Several different versions and various deployments (docker swarm, kubernetes, tb-postgres)

**Your Client Environment**

Ubuntu with Chromium based browser

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
