### ISSUE TITLE
[Question] How can I disable some left menu items?

### ISSUE THREAD

**Issue by CanSapaz** [thingsboard/thingsboard#7379]
Does anyone know, How can I hide some side menu items? For exmp. I just want available 4 menu section. How can I hide the others?

**Comment by ChrisEvisi** [comment]
This is for PE version only.  
There is a video on changing the Menu items
https://thingsboard.io/docs/pe/user-guide/white-labeling/

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
