### ISSUE TITLE
Editing backgroundcolor simple card widget

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#738]
hey all,

I want to change the backgroundcolor of my simple card, depending on my telemetry value.
I tried to edit the json file by doing this:

"backgroundColor": "if (value === 0) {rgb(0, 0, 0)} else {rgb(255,255,255)}"

But this doesn't work.
Anybody who knows how I can do this?

Thanks in advance

**Comment by IvanMihaylov** [comment]
I need the same need, Can some one help us

**Comment by ant4res** [comment]
Same need for me. Anyone could help us?

**Comment by nanomoretti** [comment]
You can edit the card or create a new one. Add in the JavaScript function: 
 
`self.onDataUpdated = function() {
    ...
            self.ctx.valueCell.html(txtValue);
            if(txtValue === 'ON'){
                self.ctx.widgetConfig.backgroundColor = "green";
                
            }else{
                self.ctx.widgetConfig.backgroundColor = "red";
            }
     ...

};`

ref: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

**Comment by rowifi** [comment]
This works for me except the colour doesn't always change in sync with the displayed value.
It can be forced to update correctly by clicking on the widget, but otherwise the colour change is not guaranteed to happen immediately, and perhaps never.
Any clues?

**Comment by BlackDuck010** [comment]
I have the same issue. Did you find a fix?

**Comment by IoTopenTech** [comment]
Same problem here... looking for a solution

**Comment by rowifi** [comment]
I have moved on from this project - but it remains unsolved for me.
May return to this project, but remains a problem.

**Comment by IoTopenTech** [comment]
Thanks @rowifi ... I am now evaluating ThingsBoard. May I ask whether you shifted from ThingsBoard to a different platform?
I have solved the background color issue with the following code:
`self.ctx.valueCell.html(txtValue);
            
            //Añadido por Juanfe
            if (txtValue === 'ABIERTA') {

                self.ctx.$containerParent[0]
                    .parentElement.parentElement.style
                    .backgroundColor = 'red';
            } else {

                self.ctx.$containerParent[0]
                    .parentElement.parentElement.style
                    .backgroundColor = 'green';
            }


            //Fin añadido

            var targetWidth;`

**Comment by BlackDuck010** [comment]
Thanks @IoTopenTech - tested as works as expected.
Where did you find the documentation to enable this feature?

**Comment by IoTopenTech** [comment]
Thanks @Backdraft007 I didn´t find documentation, just a bit of investigation on the DOM tree

**Comment by BlackDuck010** [comment]
Thanks for sharing.
