### ISSUE TITLE
How to delete bricked custom widget?

### ISSUE THREAD

**Issue by JuliusHarald** [thingsboard/thingsboard#7383]
**Component**

 * UI

**Description**

I created a static widget in my custom widget library, then I changed it to last value with the dropdown menu on rigth side of the title filed. Then I saved the widget and exited the editor. Now when I open my widget library I see the widget, but it is loading endlessly, therefore I cannot edit or delete normally. Is there a way to delete it, without deleting the whole library?

**Environment**

 * OS:  ubuntu
 * ThingsBoard: cloud 
 * Browser: firefox
![Bildschirmfoto vom 2022-10-05 11-59-57](https://user-images.githubusercontent.com/31532205/194066799-fda16cc6-aec0-4e6f-a06b-15e9df4c0b2b.png)
![Bildschirmfoto vom 2022-10-05 14-59-46](https://user-images.githubusercontent.com/31532205/194066802-8653b6b2-ffdb-4bbb-9ad9-cf312b8a027f.png)

**Comment by dhaval2017** [comment]
By using rest api

**Comment by JuliusHarald** [comment]
Worked thx.
