### ISSUE TITLE
[Feature Request] "originator telemetry" let the "limit" for aggregation function be reference to Server Attribute / metadata / msg 

### ISSUE THREAD

**Issue by BorisDaich** [thingsboard/thingsboard#7390]
we have a use case when we need to be able to change the data aggregation function limit through the dashboard 
for example default value in the rule chain is 300 but user need to be able to change it in range from 100 <-->600 
right now there is no way to do it but to go to the rule chain and edit the node configuration

in the perfect world I would tie the value to the server attribute 
great solution I can send a special message with a metadata key - value that would update the limit value 
it ok that the node will reset and start calculation of aggregation function again with new configuration

please note that the interval pattern can be changed using  message metadata but the limit is not.
By the way same goes for the "data aggregation function" and the "order by" - they can not be changed through a message metadata
see the screenshot 

Is this a known limitation with a reason behind or just a missing feature? 
 
![image](https://user-images.githubusercontent.com/406865/194420526-c9f3323f-431a-46f2-a178-9aebbeb85f95.png)

**Comment by Ultrazombie** [comment]
No one has shown further interest in this, so it has been rejected. Please create a new feature request if you still consider this valid.
