### ISSUE TITLE
[Question] Does thingsboard support another relational database?

### ISSUE THREAD

**Issue by kuen-hong** [thingsboard/thingsboard#7391]
**Question**
After some googling, I cannot find other database supported information.
As question describing, documentation is shown that supported postgreSQL, does thingsboard support MS SQL or Oracle database? Because our project has asked specific database brands.

**Version**
* v3.4

Feel free to close if issue is duplicated.

**Comment by devaskim** [comment]
Only PostgreSQL

**Comment by kuen-hong** [comment]
Got it. Thanks.
