### ISSUE TITLE
Guidance on extending an existing widget

### ISSUE THREAD

**Issue by Sylphe88** [thingsboard/thingsboard#7401]
**Component**

 * UI (Widgets)

**Description**
Disclaimer: I'm not a JS/TS developer :)
I've been trying (and failing) to extend the Image Map (and image map with marker placement) widget. To be specific, my goal is to redefine the way the image is fetched and displayed (not just a simple <img> element). I'd like to avoid rewriting the whole widget as it can become very complex, however I can't find a way to extend the ImageMap or TbMapWidgetV2 classes. 
I read the documentation https://thingsboard.io/docs/paas/user-guide/contribution/widgets-development/#using-existing-javascript-code, but that did not make much sense to me (see below).

Things I've tried:
- import TS classes in the widget editor but the editor says I can't (import declarations may only appear at the top level of a module)
- dynamically substitute the imageLoader and aspectCache function calls from map-utils (https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/modules/home/components/widget/lib/maps/maps-utils.ts), but I'm unsure whether this is possible nor found a way to achieve it

Thanks for enlightening me!

**Environment**
 * OS:  Debian 10
 * ThingsBoard: 3.4.1
 * Browser: Firefox or Chrome

**Comment by devaskim** [comment]
As I know you cannot dynamically substitute any method from pre-compiled typescript TB widgets. The second as you saw before widget editor accepts only JS code.
Here is [official project](https://github.com/thingsboard/thingsboard-extensions) to create more complex Typescript widgets. I think there you would be able to extend map widget functionality but you need to become JS/TS developer)))
Good luck!

**Comment by Ultrazombie** [comment]
Closed due to inactivity
