### ISSUE TITLE
ERROR WHEN TRYING TO LOGIN WITH THE CREATED USER IN THINGSBOARD

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7404]
When i try login to a newly created user , i am getting the following error on thingsboard and i am not able to login.
![image](https://user-images.githubusercontent.com/49026279/195055298-1f340974-daea-438b-887f-52b4ea1a4938.png)
i have a dashboard group and inside it a dashboard.
i want this dashboard only to be displayed to customer on full screen.
In the user group of above user , i have added the following roles.
![image](https://user-images.githubusercontent.com/49026279/195055851-250e6079-07ad-4a2a-97d1-1116370589d5.png)

kindly suggest a solution to resolve this error.

**Comment by Civilduino** [comment]
Make sure to create a Generic Role with these permissions
<img width="429" alt="image" src="https://user-images.githubusercontent.com/27728926/196261101-0bc49b38-2482-48b6-bf45-73c74a87613f.png">

and a Group Role with these
<img width="752" alt="image" src="https://user-images.githubusercontent.com/27728926/196261276-7fed1015-5fe7-4d1e-a89d-50aac209400f.png">

Assign the roles to your User/Costumer group. Select the Dashboard that you want to share when assigning the role.

Make the dashboard fullscreen under the User details options
<img width="523" alt="image" src="https://user-images.githubusercontent.com/27728926/196262005-ce4f6c4f-a63f-4b99-a4ee-55fc0a61a0ce.png">

**Comment by mubashirp** [comment]
thank you @Civilduino
