### ISSUE TITLE
[Question] Custom Widgets - Color Picker in Settings Schema

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#7405]
**Component**

 * UI

**Description**
In a current project we need to have colors configurable within the widget settings. It works with simple String input fields, but would be more intuitive for users if there was a Color Picker UI element.

I already searched for examples in the React Schema Builder tool, but couldn't find anything suitable:
https://networknt.github.io/react-schema-form/

Is it possible to have a Color Picker UI without high effort? Am I missing something here? 
In some default widgets (like the Timeseries Line Chart) there are Color Pickers available in the Datakey Configuration:

![image](https://user-images.githubusercontent.com/25298332/195061834-3b29ae78-6928-488a-ad47-613c64ed3895.png)
 
![image](https://user-images.githubusercontent.com/25298332/195061901-9254da79-ebb4-42a4-a3e3-3095e197befe.png)

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: 3.4.1PE
 * Browser: Brave/Chrome

**Comment by JuliusHarald** [comment]
Try this:
{
    "schema": {
        "type": "object",
        "title": "Conditional Elements in Arrays",
        "properties": {
            "defaultColor": {
                "type": "string",
                "default": "#737373",
                "title": "Default color"
            }
},
    "form": [{
            "key": "defaultColor",
            "type": "color"
        }
    ]
}

( I hope I did not miss any bracket)

**Comment by mde2017** [comment]
@JuliusHarald Thank you, for your answer. But that's what I've already implemented similarly. I asked if it's possible to have a Color picker instead of simple string input.

**Comment by devaskim** [comment]
@mde2017 Out of your topic question
What TB version does you use in this project so you are able to configure custom widgets with schema?
Maybe I did something wrong but I cannot do that on 3.4.1
