### ISSUE TITLE
[Question] Problem to compile Thingsboard Server UI 4.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by nferry56** [thingsboard/thingsboard#7406]
Hello,

**Description**
Thingsboard compilation lock and a "Killed" message is displayed before stopping.
Thingsboard Server UI 4.3.2-SNAPSHOT - compilation problem on 
:ui-ngx modules compilation locks on @angular/material/tree

Launch command:
sudo mvn clean install -DskipTests -Ddockerfile.skip=true

[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn install) @ ui-ngx ---
[INFO] Running 'yarn install' in /home/ubuntu/thingsboard/ui-ngx
[INFO] yarn install v1.22.17
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ patch-package
[INFO] patch-package 6.4.7
[INFO] Applying patches...
[INFO] canvas-gauges@2.1.7 ✔
[INFO] Done in 1.49s.
[INFO]
[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn build) @ ui-ngx ---
[INFO] Running 'yarn run build:prod' in /home/ubuntu/thingsboard/ui-ngx
[INFO] yarn run v1.22.17
[INFO] $ ng build --configuration production --vendor-chunk
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] Warning: Entry point 'ngx-daterangepicker-material' contains deep imports into '/home/ubuntu/thingsboard/ui-ngx/node_modules/dayjs/plugin/localeData', '/home/ubuntu/thingsboard/ui-ngx/node_modules/dayjs/plugin/localizedFormat', '/home/ubuntu/thingsboard/ui-ngx/node_modules/dayjs/plugin/isoWeek', '/home/ubuntu/thingsboard/ui-ngx/node_modules/dayjs/plugin/weekOfYear', '/home/ubuntu/thingsboard/ui-ngx/node_modules/dayjs/plugin/customParseFormat'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[INFO] Compiling @angular/core : es2015 as esm2015
[INFO] Compiling @angular/common : es2015 as esm2015
[INFO] Compiling @angular/platform-browser : es2015 as esm2015
[INFO] Compiling @angular/platform-browser-dynamic : es2015 as esm2015
[INFO] Compiling @angular/router : es2015 as esm2015
[INFO] Compiling @ngrx/store : es2015 as esm2015
[INFO] Compiling @ngrx/effects : es2015 as esm2015
[INFO] Compiling @ngrx/store-devtools : es2015 as esm2015
[INFO] Compiling @angular/common/http : es2015 as esm2015
[INFO] Compiling @auth0/angular-jwt : es2015 as esm2015
[INFO] Compiling @ngx-translate/core : es2015 as esm2015
[INFO] Compiling @ngx-translate/http-loader : es2015 as esm2015
[INFO] Compiling @angular/cdk/platform : es2015 as esm2015
[INFO] Compiling @angular/cdk/bidi : es2015 as esm2015
[INFO] Compiling @angular/cdk/collections : es2015 as esm2015
[INFO] Compiling @angular/cdk/scrolling : es2015 as esm2015
[INFO] Compiling @angular/cdk/portal : es2015 as esm2015
[INFO] Compiling @angular/cdk/keycodes : es2015 as esm2015
[INFO] Compiling @angular/cdk/overlay : es2015 as esm2015
[INFO] Compiling @angular/cdk/observers : es2015 as esm2015
[INFO] Compiling @angular/cdk/a11y : es2015 as esm2015
[INFO] Compiling @angular/animations : es2015 as esm2015
[INFO] Compiling @angular/animations/browser : es2015 as esm2015
[INFO] Compiling @angular/platform-browser/animations : es2015 as esm2015
[INFO] Compiling @angular/forms : es2015 as esm2015
[INFO] Compiling @angular/material/core : es2015 as esm2015
[INFO] Compiling @angular/material/button : es2015 as esm2015
[INFO] Compiling @angular/cdk/layout : es2015 as esm2015
[INFO] Compiling @angular/material/snack-bar : es2015 as esm2015
[INFO] Compiling @angular/flex-layout/core : es2015 as esm2015
[INFO] Compiling @angular/flex-layout/extended : es2015 as esm2015
[INFO] Compiling @angular/flex-layout/flex : es2015 as esm2015
[INFO] Compiling @angular/flex-layout/grid : es2015 as esm2015
[INFO] Compiling @angular/flex-layout : es2015 as esm2015
[INFO] Compiling ngx-translate-messageformat-compiler : es2015 as esm2015
[INFO] Compiling angular2-hotkeys : es2015 as esm2015
[INFO] Compiling @flowjs/ngx-flow : es2015 as esm2015
[INFO] Compiling @angular/material/form-field : es2015 as esm2015
[INFO] Compiling @angular/material/autocomplete : es2015 as esm2015
[INFO] Compiling @angular/material/button-toggle : es2015 as esm2015
[INFO] Compiling @angular/material/card : es2015 as esm2015
[INFO] Compiling @angular/material/checkbox : es2015 as esm2015
[INFO] Compiling @angular/material/chips : es2015 as esm2015
[INFO] Compiling @angular/cdk/accordion : es2015 as esm2015
[INFO] Compiling @angular/material/expansion : es2015 as esm2015
[INFO] Compiling @angular/material/grid-list : es2015 as esm2015
[INFO] Compiling @angular/material/menu : es2015 as esm2015
[INFO] Compiling @angular/material/progress-bar : es2015 as esm2015
[INFO] Compiling @angular/material/progress-spinner : es2015 as esm2015
[INFO] Compiling @angular/material/radio : es2015 as esm2015
[INFO] Compiling @angular/material/sidenav : es2015 as esm2015
[INFO] Compiling @angular/material/slide-toggle : es2015 as esm2015
[INFO] Compiling @angular/material/slider : es2015 as esm2015
[INFO] Compiling @angular/cdk/stepper : es2015 as esm2015
[INFO] Compiling @angular/material/icon : es2015 as esm2015
[INFO] Compiling @angular/material/stepper : es2015 as esm2015
[INFO] Compiling @angular/cdk/table : es2015 as esm2015
[INFO] Compiling @angular/material/select : es2015 as esm2015
[INFO] Compiling @angular/material/tooltip : es2015 as esm2015
[INFO] Compiling @angular/material/paginator : es2015 as esm2015
[INFO] Compiling @angular/material/sort : es2015 as esm2015
[INFO] Compiling @angular/material/table : es2015 as esm2015
[INFO] Compiling @angular/material/tabs : es2015 as esm2015
[INFO] Compiling @angular/material/toolbar : es2015 as esm2015
[INFO] Compiling @angular/material/divider : es2015 as esm2015
[INFO] Compiling @angular/material/list : es2015 as esm2015
[INFO] Compiling @angular/material/dialog : es2015 as esm2015
[INFO] Compiling @angular/cdk/text-field : es2015 as esm2015
[INFO] Compiling @angular/material/input : es2015 as esm2015
[INFO] Compiling @angular/material/datepicker : es2015 as esm2015
[INFO] Compiling @mat-datetimepicker/core : es2015 as esm2015
[INFO] Compiling ngx-daterangepicker-material : es2015 as esm2015
[INFO] Compiling ngx-color-picker : es2015 as esm2015
[INFO] Compiling ngx-hm-carousel : es2015 as esm2015
[INFO] Compiling ngx-window-token : es2015 as esm2015
[INFO] Compiling ngx-clipboard : es2015 as esm2015
[INFO] Compiling ngx-drag-drop : es2015 as esm2015
[INFO] Compiling @angular/cdk/clipboard : es2015 as esm2015
[INFO] Compiling @angular/cdk/drag-drop : es2015 as esm2015
[INFO] Compiling @angular/material/badge : es2015 as esm2015
[INFO] Compiling @angular/material/bottom-sheet : es2015 as esm2015
[INFO] Compiling @angular/cdk/tree : es2015 as esm2015
[INFO] Compiling @angular/material/tree : es2015 as esm2015
Killed

[INFO] error Command failed with exit code 137.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ThingsBoard Server UI 3.4.2-SNAPSHOT:
[INFO]
[INFO] ThingsBoard Server UI .............................. FAILURE [07:30 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard Version Control Executor ............... SKIPPED
[INFO] ThingsBoard Version Control Executor Microservice .. SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:32 min
[INFO] Finished at: 2022-10-11T15:57:04Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn build) on project ui-ngx: Failed to run task: 'yarn run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Environment**

 * OS:  Fresh Ubuntu 22.04.1 LTS
 * ThingsBoard: 4.3.2-SNAPSHOT
 * Browser: Firefox (Last)

Thanks in advance

**Comment by devaskim** [comment]
From time to time I am also facing with this issue. As I understand this is due to out of memory (RAM). UI build requires a lot of computing resources.

**Comment by nferry56** [comment]
You are right !
The default Ubuntu Server configuration does not install swapfile.

I follow these commands in order to temporally install a swapfile (not swap partition for me).
sudo swapoff -a
sudo dd if=/dev/zero of=/swapfile bs=1G count=8
sudo chmod 600 /swapfile
sudo mkswap /swapfile
cat /proc/swaps

[INFO] Reactor Summary for ThingsBoard Server UI 3.4.2-SNAPSHOT:
[INFO]
[INFO] ThingsBoard Server UI .............................. SUCCESS [07:55 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  9.683 s]
[INFO] Thingsboard Rest Client ............................ SUCCESS [  3.487 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [02:38 min]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  0.239 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [  8.639 s]
[INFO] ThingsBoard Version Control Executor ............... SUCCESS [ 34.661 s]
[INFO] ThingsBoard Version Control Executor Microservice .. SUCCESS [  0.302 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SUCCESS [01:46 min]
[INFO] ThingsBoard Web UI Microservice .................... SUCCESS [ 42.608 s]
[INFO] ThingsBoard Node Microservice ...................... SUCCESS [  0.323 s]
[INFO] ThingsBoard Transport Microservices ................ SUCCESS [  0.026 s]
[INFO] ThingsBoard MQTT Transport Microservice ............ SUCCESS [  3.968 s]
[INFO] ThingsBoard HTTP Transport Microservice ............ SUCCESS [  0.705 s]
[INFO] ThingsBoard COAP Transport Microservice ............ SUCCESS [  0.811 s]
[INFO] ThingsBoard LWM2M Transport Microservice ........... SUCCESS [  0.691 s]
[INFO] ThingsBoard SNMP Transport Microservice ............ SUCCESS [  0.748 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

I'm now trying the complete compilation.
Thanks

**Comment by nferry56** [comment]
[INFO] BUILD SUCCESS

OK complete compilation working !
Thanks

**Comment by nferry56** [comment]
[INFO] BUILD SUCCESS

OK complete compilation working !
Thanks

**Comment by Eddie66666666** [comment]
why I try it and still fail?

**Comment by Blacktoviche** [comment]
I do have so much memory and swap file is big as of 8GB. but still facing this problem
