### ISSUE TITLE
[Bug] Scheduler (UI)

### ISSUE THREAD

**Issue by vaxvhbe** [thingsboard/thingsboard#7410]
**Describe the bug**
In the "Scheduler events" editing interface, when you change the value manually in the "Start time*" field and lose focus on this field, the day and month values are reversed in the date.

**Your Server Environment**
* own setup
  * openshift deployment
  * ThingsBoard PE 3.4.1

**Your Client Environment**

* OS: Windows 10 Pro
* Browser Brave
* Version 1.44.108 (Chromium: 106.0.5249.103)
* Browser Microsoft Edge
* Version 104.0.1293.47

**To Reproduce**
1. Go to 'Scheduler UI'
2. Click on '+' to add new schedule
3. Click on 'Schedule' tab
4. Change the date/time manualy (without the widget)
5. Click out of the field to lost the focus
6. Values of the day/month values are switched ...

**Expected behavior**
The day and month values must not be reversed

**Comment by ssakharova** [comment]
Hi @vaxvhbe,

This is a known issue in the ThingsBoard the fix of it will most likely be in v3.4.2. However, please follow the [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

Regards,
