### ISSUE TITLE
[Question] API - GET deviceid call

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7411]
**Component**

 * Rule Engine

**Description**
Hello dear Thingsboard community! I am looking for API GET call which returns device id parameter. I am struggling to find it, is there any? I guess I shoud bearer x-auth before that request, which I already use. Any tips?

Thanks in advance.

**Comment by devaskim** [comment]
Where do you need to get ID: custom widget, rule chain and etc.? And what information do you have to find exactly this device: its name or somethings else?

**Comment by devaskim** [comment]
If NodeRed has tenant admin access (token), you could find [device info by its name](https://demo.thingsboard.io/swagger-ui/#/device-controller/getTenantDeviceUsingGET)

**Comment by samokomo** [comment]
Thanks! I am working on it... but I am recieving error 400 all the time. 
URL should be - for example - http://thingsboard:9090/api/tenant/devices
And msg.payload object with deviceName parameter?

**Comment by devaskim** [comment]
I don't know exactly but you could find out from browser's *Dev tools*
1. Open [Swagger page](https://demo.thingsboard.io/swagger-ui/#/device-controller/getTenantDeviceUsingGET)
2. Open DevTools (tab *Network*, filter *Fetch/XHR*). 
3. Send request from Swagger.
4. Explore new requests and its data in *Network* tab.

**Comment by samokomo** [comment]
Thanksfor advice, I have figured out everything as of now.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
