### ISSUE TITLE
[Bug] Script rule node not compiled with correct Javascript

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#7414]
In all message trasformation scripts, if I use 'let' to define variables, script compilation fails with exception.
If I use 'var' instead, script is OK
Please see attached images
Expectation is that using 'let' in Javscript should be legal.

Server Environment:
Thingsboard v3.4.1 PE-1
OS Linux Ubuntu 22.04 LTS

![tbscript1](https://user-images.githubusercontent.com/1144682/195390025-2d6f4287-ff4b-4256-a358-1977e50f213d.png)
![tbscript2](https://user-images.githubusercontent.com/1144682/195390088-76cc7275-0f2d-44eb-95c9-e94dbe970303.png)

**Comment by devaskim** [comment]
Current version of JS engine (Nashorn JS) doesn't support `let` keyword and some other features of ECMA standart.

**Comment by albtrentadue** [comment]
Thank you @devaskim 
Fact is that the same code runs well on Thingsboard in Cloud (SaaS), hence the confusion.
Is this documented somewhere?

**Comment by den1jkee** [comment]
Hi,
I think this is because the cloud uses an external JS executor and not the built-in Nashorn, this is due to the number of requests that Nashorn can handle.
 (https://thingsboard.io/docs/reference/msa/)
