### ISSUE TITLE
[Bug] Device groups found by name only with lowercase filters

### ISSUE THREAD

**Issue by slibutti** [thingsboard/thingsboard#7415]
# Description
Device groups are not found by name anymore, both with dashboard aliases and REST APIs, when their name is in uppercase.
Queries are successful only if startsWith field value is put in lowercase.
E.g., MYGROUP is not found when using startsWith = "MYG" **but** is found using startsWith = "myg".

Tested both with dashboard aliases (Device groups whose names start with 'XXX')
and REST APIs (/entity-query-controller/findEntityDataByQueryUsingPOST).

# Server Environment
Thingsboard v3.4.1PE, both on-premise (ubuntu/docker) and on thingsboard.cloud

# Client Environment
Tested on several browsers/OSs and with curl

# To Reproduce (dashboad alias)
1. Create a device group named, e.g., TESTGROUP;
2. Create a dashboard alias "Device groups whose names start with 'TESTG'" (won't find anything);
3. Create a dashboard alias "Device groups whose names start with 'testg'" (will work).

# To Reproduce (REST)

Endpoint: /entity-query-controller/findEntityDataByQueryUsingPOST
Query: `{"entityFilter":{"type":"entityGroupName","groupType":"DEVICE","entityGroupNameFilter":"TESTG"},"pageLink":{"page":0,"pageSize":1}}`

1. Create a device group named, e.g., TESTGROUP;
2. Search for device using entityGroupNameFilter "TESTG" (won't find anything);
3. Search for device using entityGroupNameFilter "testg" (will work).

# Notes
The same aliases and REST calls were working in v.3.3.2pe, which I was using before upgrading to latest version.

**Comment by YevhenBondarenko** [comment]
The fix will be released in v3.4.2
