### ISSUE TITLE
[Feature Request] Add rule node to delete Telemetry data

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7418]
**Is your feature request related to a problem? Please describe.**
We send big data base64 Images to Thingsboard but this need to be managed so the database doesn't explode.
I need to jump through a lot of hoops trying to get this to work, without having to write an external Python script using several API calls.

**Describe the solution you'd like**
Basically, a rule node that you specify which telemetry you want to delete for that device.
Also control of last and last data before last etc.
(PostgresSQL database)

**Describe alternatives you've considered**
Using the external API call node for internal use. (Complicated workaround that is load intensive)

**Additional context**
We should have some (smarter) cleanup management, like only keep 1 image every hour instead of keeping all of them every 5 sec.
We don't want to delete all of it since we may also need it for AI later, so it's just removing most of it.

**Comment by KenSense** [comment]
I'm stuck with with using the delete API
Getting a token works done according to this [https://github.com/thingsboard/thingsboard/issues/6135#issuecomment-1124913293](https://github.com/thingsboard/thingsboard/issues/6135#issuecomment-1124913293)

But the delete API keeps giving me this error?: (Don't know were it sees a null)
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 : "Unable to parse timeseries payload. Invalid JSON body: Can't parse value: null" at rg.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)

Rule chain attached.

[delete_image.json.txt](https://github.com/thingsboard/thingsboard/files/9831078/delete_image.json.txt)
<img width="516" alt="Delete_image" src="https://user-images.githubusercontent.com/49442805/196978856-2a31f7fa-699d-49d9-a0f8-4f246f3b3753.png">

**Comment by ashaforost** [comment]
@KenSense change the api method from POST to DELETE in 'Delete' rest api call rule node.

**Comment by KenSense** [comment]
> @KenSense change the api method from POST to DELETE in 'Delete' rest api call rule node.

That was indeed the problem, thanks, now trying with extra timing parameters.
