### ISSUE TITLE
[Bug] Wrong description in REST API (swagger)

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#7421]
**Describe the bug**
Description is wrong:
https://demo.thingsboard.io/swagger-ui/#/admin-controller/saveAdminSettingsUsingPOST
The test next to the URL should indicate 'Creates or Updates an Administration Settings entry' and not 'Get the Administration Settings object using key (getAdminSettings)' which is a copy of the next entry (I guess it's a copy paste mistake).

**Your Server Environment**
* demo.thingsboard.io

**To Reproduce**
1. Go to ['this URL'](https://demo.thingsboard.io/swagger-ui/#/admin-controller/saveAdminSettingsUsingPOST)
2. Read

**Expected behavior**
A fitting description.

**Comment by Tejas-Teju** [comment]
Can I get this bug assigned @bbrenne? It will be my good first issue.

**Comment by SuminDenis** [comment]
Hello @bbrenne, 

This issue is related to the current ThingsBoard version.I will forward this to the responsible team!

**Comment by SuminDenys** [comment]
Hi @bbrenne,

I am glad to inform you that this issue has been fixed and will be added to the next release. Here is the link to Pull Request [Swagger Fix](https://github.com/thingsboard/thingsboard/pull/11422)

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
If you have any further questions or require clarification, please let me know.
