### ISSUE TITLE
Thingsboard PE Flutter application login error

### ISSUE THREAD

**Issue by aortega1** [thingsboard/thingsboard#7427]
**Component**

 * UI

**Description**
When logging into the Thingsboard PE Flutter application (after changing the app_constants.dart thingsBoardApiEndpoint to point to my endpoint, I am getting the following error in the Chrome console:

Specifically I see a 404 on /api/system/info, which I do not see exposed in swaggers definition.

I am running TB PE 3.3.1

--begin error log from Chrome debbuger--

browser_adapter.dart:181          GET https://**REDACTED HOST NAME**/api/system/info 404
fetch @ browser_adapter.dart:181
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
fetch @ browser_adapter.dart:26
_dispatchRequest @ dio_mixin.dart:657
(anonymous) @ async_patch.dart:45
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
runBody @ async_patch.dart:108
_async @ async_patch.dart:123
[_transformData] @ dio_mixin.dart:707
_dispatchRequest @ dio_mixin.dart:656
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_dispatchRequest] @ dio_mixin.dart:652
(anonymous) @ dio_mixin.dart:607
(anonymous) @ dio_mixin.dart:517
checkIfNeedEnqueue @ dio_mixin.dart:789
(anonymous) @ dio_mixin.dart:515
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
(anonymous) @ dio_mixin.dart:514
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
(anonymous) @ dio_mixin.dart:509
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
complete @ future_impl.dart:47
onValue @ future.dart:613
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
complete @ future_impl.dart:36
next @ interceptor.dart:87
_handleRequest @ http_interceptor.dart:77
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_handleRequest] @ http_interceptor.dart:75
_jwtIntercept @ http_interceptor.dart:68
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_jwtIntercept] @ http_interceptor.dart:65
onRequest @ http_interceptor.dart:55
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
onRequest @ http_interceptor.dart:38
(anonymous) @ dio_mixin.dart:517
checkIfNeedEnqueue @ dio_mixin.dart:789
(anonymous) @ dio_mixin.dart:515
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
(anonymous) @ dio_mixin.dart:514
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
(anonymous) @ dio_mixin.dart:509
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
fetch @ dio_mixin.dart:589
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
fetch @ dio_mixin.dart:487
request @ dio_mixin.dart:483
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
request @ dio_mixin.dart:453
get @ dio_mixin.dart:61
get @ thingsboard_client_base.dart:228
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
get @ thingsboard_client_base.dart:220
_checkPlatformVersion @ thingsboard_client_base.dart:137
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_checkPlatformVersion] @ thingsboard_client_base.dart:135
_userLoaded @ thingsboard_client_base.dart:175
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_userLoaded] @ thingsboard_client_base.dart:170
_setUserFromJwtToken @ thingsboard_client_base.dart:131
(anonymous) @ async_patch.dart:45
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
complete @ future_impl.dart:36
next @ interceptor.dart:134
onResponse @ http_interceptor.dart:95
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
onResponse @ http_interceptor.dart:89
(anonymous) @ dio_mixin.dart:542
checkIfNeedEnqueue @ dio_mixin.dart:789
(anonymous) @ dio_mixin.dart:540
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
(anonymous) @ dio_mixin.dart:539
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
(anonymous) @ dio_mixin.dart:533
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
complete @ future_impl.dart:47
onValue @ future.dart:613
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
complete @ future_impl.dart:36
(anonymous) @ browser_adapter.dart:53
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
_cancelAndValue @ stream_pipe.dart:61
(anonymous) @ stream.dart:1587
_checkAndCall @ operations.dart:334
dcall @ operations.dart:339
(anonymous) @ html_dart2js.dart:37341
load (async)
[_addEventListener] @ html_dart2js.dart:15887
[dartx.addEventListener] @ html_dart2js.dart:15875
[_tryResume] @ html_dart2js.dart:37371
onData @ html_dart2js.dart:37342
get first @ stream.dart:1586
fetch @ browser_adapter.dart:51
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
fetch @ browser_adapter.dart:26
_dispatchRequest @ dio_mixin.dart:657
(anonymous) @ async_patch.dart:45
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
runBody @ async_patch.dart:108
_async @ async_patch.dart:123
transformRequest @ transformer.dart:73
_transformData @ dio_mixin.dart:735
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_transformData] @ dio_mixin.dart:707
_dispatchRequest @ dio_mixin.dart:656
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_dispatchRequest] @ dio_mixin.dart:652
(anonymous) @ dio_mixin.dart:607
(anonymous) @ dio_mixin.dart:517
checkIfNeedEnqueue @ dio_mixin.dart:789
(anonymous) @ dio_mixin.dart:515
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
(anonymous) @ dio_mixin.dart:514
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
(anonymous) @ dio_mixin.dart:509
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
complete @ future_impl.dart:47
onValue @ future.dart:613
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_completeWithValue] @ future_impl.dart:566
(anonymous) @ future_impl.dart:639
_microtaskLoop @ schedule_microtask.dart:40
_startMicrotaskLoop @ schedule_microtask.dart:49
(anonymous) @ async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:69
_rootScheduleMicrotask @ zone.dart:1458
scheduleMicrotask @ zone.dart:1673
[_asyncCompleteWithValue] @ future_impl.dart:638
[_asyncComplete] @ future_impl.dart:598
complete @ future_impl.dart:36
next @ interceptor.dart:87
_handleRequest @ http_interceptor.dart:77
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_handleRequest] @ http_interceptor.dart:75
onRequest @ http_interceptor.dart:58
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
onRequest @ http_interceptor.dart:38
(anonymous) @ dio_mixin.dart:517
checkIfNeedEnqueue @ dio_mixin.dart:789
(anonymous) @ dio_mixin.dart:515
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
(anonymous) @ dio_mixin.dart:514
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
(anonymous) @ dio_mixin.dart:509
runUnary @ zone.dart:1653
handleValue @ future_impl.dart:147
handleValueCallback @ future_impl.dart:766
_propagateToListeners @ future_impl.dart:795
[_complete] @ future_impl.dart:557
(anonymous) @ future.dart:253
internalCallback @ isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:55
_createTimer @ async_patch.dart:186
createTimer @ zone.dart:1677
new @ timer.dart:51
run @ timer.dart:110
new @ future.dart:251
fetch @ dio_mixin.dart:589
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
fetch @ dio_mixin.dart:487
request @ dio_mixin.dart:483
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
request @ dio_mixin.dart:453
post @ dio_mixin.dart:97
post @ thingsboard_client_base.dart:248
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
post @ thingsboard_client_base.dart:238
login @ thingsboard_client_base.dart:284
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
login @ thingsboard_client_base.dart:282
_login @ login_page.dart:351
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
[_login] @ login_page.dart:343
(anonymous) @ login_page.dart:193
handleTap @ ink_well.dart:1072
invokeCallback @ recognizer.dart:253
handleTapUp @ tap.dart:627
[_checkUp] @ tap.dart:306
handlePrimaryPointer @ tap.dart:239
handleEvent @ recognizer.dart:615
[_dispatch] @ pointer_router.dart:98
(anonymous) @ pointer_router.dart:143
forEach @ linked_hash_map.dart:21
[_dispatchEventToRoutes] @ pointer_router.dart:141
route @ pointer_router.dart:127
handleEvent @ binding.dart:460
dispatchEvent @ binding.dart:440
dispatchEvent @ binding.dart:337
[_handlePointerEventImmediately] @ binding.dart:395
handlePointerEvent @ binding.dart:357
[_flushPointerEventQueue] @ binding.dart:314
[_handlePointerDataPacket] @ binding.dart:295
invoke1 @ platform_dispatcher.dart:1183
invokeOnPointerDataPacket @ platform_dispatcher.dart:244
[_onPointerData] @ pointer_binding.dart:147
(anonymous) @ pointer_binding.dart:653
(anonymous) @ pointer_binding.dart:594
loggedHandler @ pointer_binding.dart:288
(anonymous) @ pointer_binding.dart:179
_checkAndCall @ operations.dart:334
dcall @ operations.dart:339
ret @ js_patch.dart:413
js_primitives.dart:30   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
js_primitives.dart:30   ERROR │ ThingsboardError: message: [], errorCode: 32, status: 404
js_primitives.dart:30   ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 963:28                get current
js_primitives.dart:30   ERROR │ packages/thingsboard_client/src/error/_thingsboard_error_handler_html.dart 90:18  toThingsboardError
js_primitives.dart:30   ERROR │ packages/thingsboard_client/src/interceptor/http_interceptor.dart 104:19          onError
js_primitives.dart:30   ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
js_primitives.dart:30   ERROR │ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
js_primitives.dart:30   ERROR │ packages/thingsboard_client/src/interceptor/http_interceptor.dart 99:17           onError
js_primitives.dart:30   ERROR │ packages/dio/src/dio_mixin.dart 574:28                                            <fn>
js_primitives.dart:30   ERROR │ packages/dio/src/dio_mixin.dart 789:22                                            checkIfNeedEnqueue
js_primitives.dart:30   ERROR │ packages/dio/src/dio_mixin.dart 572:22                                            <fn>
js_primitives.dart:30   ERROR │ dart-sdk/lib/async/future.dart 253:37                                             <fn>
js_primitives.dart:30   ERROR │ dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback
js_primitives.dart:30   ERROR │ 
js_primitives.dart:30   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
js_primitives.dart:30   ERROR │ #0   packages/thingsboard_client/src/error/_thingsboard_error_handler_html.dart 90:18  toThingsboardError
js_primitives.dart:30   ERROR │ #1   packages/thingsboard_client/src/interceptor/http_interceptor.dart 104:19          onError
js_primitives.dart:30   ERROR │ #2   packages/thingsboard_client/src/interceptor/http_interceptor.dart 99:17           onError
js_primitives.dart:30   ERROR │ #3   packages/dio/src/dio_mixin.dart 574:28                                            <fn>
js_primitives.dart:30   ERROR │ #4   packages/dio/src/dio_mixin.dart 789:22                                            checkIfNeedEnqueue
js_primitives.dart:30   ERROR │ #5   packages/dio/src/dio_mixin.dart 572:22                                            <fn>
js_primitives.dart:30   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
js_primitives.dart:30   ERROR │ ⛔ onError
js_primitives.dart:30   ERROR └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
\

** the error occurs on a correct user/password combo.  When an incorrect user/pass combo is used, the application relays that info to the user (wrong password/user message in the Toast message)
**Environment**
Chrome Version 106.0.5249.103

**Comment by aortega1** [comment]
<img width="561" alt="Screen Shot 2022-10-19 at 12 30 55 PM" src="https://user-images.githubusercontent.com/8949470/196763596-678723d5-1209-47a1-8556-96d7b69180dc.png">

Please can we have an update on this issue?  I've attached an image showing what the problem looks like in the console.

**Comment by derzhavets-emg** [comment]
Hey, is there an update on this? Or at least the way to cancel this request after login? 
I assume it is some recent change in Things Board server, but my client apparently use some older version and is not willing to change it.

**Comment by ssakharova** [comment]
Hello @aortega1,

ThingsBoard Mobile App is a free-of-charge open-source product. Therefore, I can recommend you rely on community support.
Please try to open an issue on GitHub describing all the details of your case. This will increase the probability that the GitHub community will be able to fix it.

[Issues · thingsboard/flutter_thingsboard_app](https://github.com/thingsboard/flutter_thingsboard_app/issues) 

[Issues · thingsboard/flutter_thingsboard_pe_app](https://github.com/thingsboard/flutter_thingsboard_pe_app/issues)

Best regards,
Sofiia
