### ISSUE TITLE
[Bug] Custom widget type cannot be changed using the drop list inside the editor/programming panel

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7428]
**Describe the bug**
After a widget type is selected during the creation of a custom widget, the type cannot be changed anymore even if it says so in the drop list inside the widget programming panel.

I noticed the bug because I first created a "latest values" type widget that then I changed to "time series" using the drop list, however, it was still behaving like latest values. For example, my chart kept updating even when "History" instead of "Real Time" was selected in the timeframe of the dashboard.

Select widget type during creation. Cannot be changed anymore.
![image](https://user-images.githubusercontent.com/27728926/195925963-691b6427-6f39-404c-b70b-f52d6b19849d.png)

Change type using drop list inside widget editor does not change the initial selection in the back-end.
![image](https://user-images.githubusercontent.com/27728926/195925843-064f6486-ebe7-4885-9991-1be005f1cc9b.png)

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome
* Version Version 106.0.5249.103 (Official Build) (x86_64)

**To Reproduce**
1. Go to Widget Library and create new widget.
2. Select widget type in pop up window.
3. Try to change widget type inside the widget editor.
4. Compare Timeseries vs Latest Values behaviour changing the timeframe in the dashboard from Real Time to History.

**Expected behavior**
If I change the widget type from the initial selected Latest Values to Timeseries then the widget data should not update using the History timeframe, indicating that the change was indeed applied.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
