### ISSUE TITLE
"simple" MQTT connection

### ISSUE THREAD

**Issue by davygraham** [thingsboard/thingsboard#743]
Hi, I am having no luck trying to setup a connection between ThingsBoard an a local copy of mosquitto MQTT broker despite trying to follow the documentation. Data has been published to mosquitto, and can be viewed using PC & android MQTT dashboards so I know that side is working, where I am struggling is with the amount of configuration required for the tb-gateway.

To subscribe to a point using other software I simply need the broker IP address and the topic field but the tb-gateway has many more options that need to be filled in. Is it possible to set up a connection from ThingsBoard to an MQTT broker using only these details?

**Comment by mp-loki** [comment]
You need tb-gateway to connect to ThingsBoard  mosquitto mqtt broker. 
The configuration is not that complicated. Once installed the gateway, you have to:
1) in tb-gateway.yml enable mqtt extension
2) in mqtt-config.json update the broker IP address and the mapping of attributes.
The same can be done using MQTT Extension Gui. The guide is [here](https://thingsboard.io/docs/iot-gateway/getting-started/#step-8-connect-to-external-mqtt-broker)
You can connect ThingsBoard to mosquitto directly without using the gateway in [ThingsBoard PE](https://thingsboard.io/products/thingsboard-pe/)

**Comment by davygraham** [comment]
[tb-gateway.txt](https://github.com/thingsboard/thingsboard/files/1951906/tb-gateway.txt)
Hi.
my tb-gateway file does not have a section listed for 'mqtt enable'. For the mapping of the attributes is it possible to delete nost of the sections out of the JSON file? My published data to the mosquitto broker is very basic (I don't have the facility to modify this, apart from the "topic name". A sample of the data sent manually looks like the following

mosquitto_pub -h localhost -p 1884 -t "CCNkW1" -m 20 -u UZj8WJhiuvt8SWhDOR6g

I might need to transfer to the PE edition but for testing purposes I was hoping to be able to use the standard version.

**Comment by mp-loki** [comment]
To enable MQTT edit your thingsboard.yaml file as follows:
```yaml
      remoteConfiguration: false
      extensions:
        -
          id: "mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config.json
```
So in your use case, the body of the mqtt message is just an arbitrary integer number, e.g. `-m 20` not a json value, correct?

**Comment by davygraham** [comment]
Correct

**Comment by davygraham** [comment]
tb-gateway setup seems to be working OK, I can get as far as this step

https://thingsboard.io/docs/iot-gateway/getting-started/#step-81-mqtt-broker-file-configuration

Step 6, I can see all values set to zero, and the 'Last update time' counts up OK.

I have tried importing the MQTT extension setup from the following location 
https://thingsboard.io/docs/iot-gateway/getting-started/#step-8-connect-to-external-mqtt-broker
Step 8.2, but the downloaded file does not contain all required info, see [this ](https://github.com/thingsboard/thingsboard/issues/737)for details

So far I have been unable to connect any device via MQTT, please shout out if you think you can help

**Comment by mp-loki** [comment]
I think the main issue here is that ThingsBoard expects MQTT message in JSON format, meaning you send key-value like `-m '{"value":20}`. I do not recall any use cases where the message was a raw value, but I may be wrong. Is that possible for your device to send the JSON value as described above?  Then It would be easier to come up with the mapping configuration.

Regarding GUI - yes, we know about the issue in the tutorial, and it will be fixed soon. Meanwhile, you can proceed with file configuration.

**Comment by davygraham** [comment]
Thank you for the reply, I think it will be possible for me to publish a message as per your example above, could you assist with a mapping for that?

**Comment by mp-loki** [comment]
The default mqtt-config.json is almost all you need. 

You need to change "mapping" section to the following

```json
...
mapping : [
    {
          "topicFilter": "CCNkW1",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameTopicExpression": "(.*?)",
            "timeout": 60000,
            "timeseries": [
              {
                "type": "double",
                "key": "<NAME_OF_TS_IN_TB>",
                "value": "${$.value}"
              }
            ]
          }
]
```

You probably don't need to care about the rest (except MQTT broker connection section). Replace <NAME_OF_TS_IN_TB> with the name of the timeseries value that you want to see on TB.
The mapping described above will subscribe only to topic "CCNkW1" and it will create a single device in TB named "CCNkW1".
I just made it up off top of my head. I will probably test this configuration later if I have time.

**Comment by davygraham** [comment]
Many thanks for your help so far, can I give you a quick overview of what I think I have so far and see if you can spot anything obviously wrong as I think the setup is not too far away from working.

tb-server looks as though it is installed/running OK

I was initially using a local copy of mosquitto, but in order to try and simplify my initial setup I am now publishing data to test.mosquitto.org (37.187.106.16). I am publishing 2 topics as follows (1 with 1 JSON pair, the other with 9 JSON pairs). These points are live and can currently be used by others if required.
   CCNkW1 - {"value":4.9}
   ElectricMeter - {"L1N":242,"L2N":243,"L3N":243,"L1L2":420,"L1L3":421,"L2L3":420,"Phase1Power":3.4,"Phase2Power":1.1,"Phase3Power":2}

Ideally I would like to get working with the ElectricMeter example, but I am testing with just the CCNkW1 topic initially to get things working.

thingsboard.yml has the following section setup to enable MQTT

# MQTT server parameters
mqtt:
  # Enable/disable mqtt transport protocol.
  enabled: "${MQTT_ENABLED:true}"
  bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
  bind_port: "${MQTT_BIND_PORT:1883}"
  adaptor: "${MQTT_ADAPTOR_NAME:JsonMqttAdaptor}"
  timeout: "${MQTT_TIMEOUT:10000}"
  netty:
    leak_detector_level: "${NETTY_LEASK_DETECTOR_LVL:DISABLED}"
    boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
    worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"

Is the MQTT_BIND_ADDRESS:0.0.0.0 correct?

tb-gateway.yml has the following setup

server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "9090"

# Check new version updates parameters
updates:
  # Enable/disable updates checking.
  enabled: "${UPDATES_ENABLED:true}"

gateways:
  tenants:
    -
      label: "Tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "127.0.0.1"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "Vt4XrRoEZ8c5mRJBcKsa"
      remoteConfiguration: false
      extensions:
        -
          id: mqtt"
          type: "MQTT"
          extensionConfiguration: mqtt-config.json

The accessToken is copied from my gateway device and the host IP is set to use the local PC.



mqtt-config.json is set as follows

{
  "brokers": [
    {
      "host": "37.187.106.16",
      "port": 1883,
      "ssl": false,
      "retryInterval": 3000,
      "credentials": {
        "type": "anonymous"
      },
      "mapping": [
    {
          "topicFilter": "CCNkW1",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameTopicExpression": "(.*?)",
            "timeout": 60000,
            "timeseries": [
              {
                "type": "double",
                "key": "power",
                "value": "${$.value}"
              }
            ]
          }
    }
]
}
]
}

the host IP is set to use the IP for test.mosquitto.org. I am trying to subscribe to the CCNkW1 topic, I have tried various items in the 'key' section without success. I would like the information to be displayed as 'power' in TB but I have also tried setting it to 'value' as my published data is {"value":4.9}

I am also unsure if I need to create devices in TB, or if by subscribing to the topic new devices will be created for me automatically. I have tried creating devices called CCNkW1 and ElectricMeter but still do not receive any data in TB, the gateway telemetry always shows the following

![image](https://user-images.githubusercontent.com/38755042/39531071-48f99fb4-4e22-11e8-9d1f-7bbba00ae269.png)


[tb-gateway.zip](https://github.com/thingsboard/thingsboard/files/1967785/tb-gateway.zip)
[mqtt-config.zip](https://github.com/thingsboard/thingsboard/files/1967786/mqtt-config.zip)
[thingsboard.zip](https://github.com/thingsboard/thingsboard/files/1967789/thingsboard.zip)
[thingsboard.log.zip](https://github.com/thingsboard/thingsboard/files/1967790/thingsboard.log.zip)
[tb-gateway.log.zip](https://github.com/thingsboard/thingsboard/files/1967792/tb-gateway.log.zip)

If anyone has made it this far then thank you for trying to help

**Comment by mp-loki** [comment]
If everything was ok, the CCNkW1 device should have been provisioned to ThingsBoard automatically. The telemetry should be observed on that device, not on Gateway. Was the device actually created?

**Comment by mp-loki** [comment]
I found the issue - the **deviceNameTopicExpression** regex was incorrect. change it to **"^(.*)$"**
The complete configuration that worked for me is below. do not forget to change host and port to your values:
```json
{
  "brokers": [
    {
      "host": "localhost",
      "port": 1883,
      "ssl": false,
      "retryInterval": 3000,
      "credentials": {
        "type": "anonymous"
      },
      "mapping": [
        {
          "topicFilter": "CCNkW1",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameTopicExpression": "^(.*)$",
            "timeout": 60000,
            "timeseries": [
              {
                "type": "double",
                "key": "power",
                "value": "${$.value}"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by davygraham** [comment]
Perfect, thank you for all your assistance. Device created automatically and data being displayed. Now the fun begins 👍

**Comment by miguelgm04** [comment]
> Perfect, thank you for all your assistance. Device created automatically and data being displayed. Now the fun begins 👍

Hello!!! i am having the same problem and... i was asking myself, could you pls send me what command de you use the send data to your gateway?? 

I am using this one: mosquitto_pub -d -q 1 -h "localhost" -p "1883" -t "sensor/data" -u "eNBfqgYKTJ47zcjCKoPM" -m {"temperature":"25"}

But it seems that thingsboard doesn't get this infomation, temperature is still equals 0...

Could you send me the command you use pls? thanks!
