### ISSUE TITLE
[Feature Request] ota var thingsboard gateway

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard#7431]
**Is your feature request related to a problem? Please describe.**
I want to add ota on gateway. What your play? 
If i add it by myself, what is the related work?

**Comment by Ultrazombie** [comment]
Due to this request about the ThingsBoard gateway, please re-create this issue at the correct repository.
[Github for community support](https://github.com/thingsboard/thingsboard-gateway/issues).
