### ISSUE TITLE
[Question] Can I use relations query inside an HTML Value card widget ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#7437]
Hello,

Can I use a relation query function in a <script> tag inside an HTML value card widget using javascript ?
I use this widget to see informations about an equipment. But my equipment has "contains" relations with multiple devices.
I would like to know if I can see the name of those devices inside the HTML value card widget of the equipment using relation query function ?
I have tried to use widgetcontext inside the script tag but I have failed because widgetcontext is not defined. 
Thank in advance,

Lucas

**Comment by devaskim** [comment]
*HTML Value Card* supports only RegExp replacement for data keys and device name and its label. So there is no access to widget context. By the way, TB provides powerful widget called `Entities hierarchy`

**Comment by lucasKapf** [comment]
@devaskim Thank you for your answer.
I know the existence of entities hierarchy widget : it is powerful but I can't do exactly what I want with it (use CSS, JS, etc...).
I can close this issue now

**Comment by devaskim** [comment]
Just to show off)))
![silos](https://user-images.githubusercontent.com/86909129/199471077-34a849fa-81ed-419a-9633-49cb7c1add67.jpg)

**Comment by lucasKapf** [comment]
It is very nice ! So I assume that you used JS and CSS inside the entities hierarchy widget ? Did you create a custom widget ?

**Comment by devaskim** [comment]
It's entities hierarchy widget. All magic is in advanced settings:
1. `Node relations query function: f(widgetCtx, nodeCtx) ` to get child entities.
2. `Node text function: f(widgetCtx, nodeCtx)` to create CSS/JS cards for each parent/child entity

**Comment by lucasKapf** [comment]
Ok thank you ! I just noticed that the text returned in the node text function could be HTML code, I didn't know that.
