### ISSUE TITLE
[Bug] Bulk provisioned devices showing server attribute active true even when they offline/inactive

### ISSUE THREAD

**Issue by hetvishah08** [thingsboard/thingsboard#7441]
I'm using the bulk provisioning feature to add devices on thingsboard. The devices show active status even when they are offline, not connected, or sending any data.
The devices which I add individually through "Add Device" and by not using the bulk provisioning method they show active status false when they are offline or inactive.

**Your Server Environment**
* own setup
  * ThingsBoard Version 3.4
  * OS Name and Version Windows 

**Your Device**

* Connectivity
  * MQTT

**Expected behavior**
The device should show active false as a status when the devices are offline.

**Screenshots**
![active status](https://user-images.githubusercontent.com/34642195/196380810-c3d92872-c199-44ce-bbfc-c7efcaac4f68.PNG)

As you can see from the above image, the last Activity time is of 15th October and still the device is showing active true.

**Comment by SuminDenis** [comment]
Hello @[hetvishah08](https://github.com/hetvishah08),

I’m glad to inform you that this issue has been solved in the current version of ThingsBoard!
