### ISSUE TITLE
[Bug] I'm limited to a certain amount of nodes inside rule chains.

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#7443]
**Describe the bug**
I have a big severity bug.
I have several Rulechains linked to each other.
When too many nodes are run inside my rule chains, I have node output which tells success in my "end" rule chain, but the nothing comes in the linked nodes with success arrows. Of course debug mode is activated on all the rule nodes.
It is a big problem because I can't do anything after a certain amount of nodes.
I already made a post few months ago [here](https://github.com/thingsboard/thingsboard/issues/6516) and the problem still occurs.
   
**Your Server Environment**

thingsboard.cloud

**Your Device**

* Connectivity
  * HTTP

**To Reproduce**
1. Make rule chains linked to each others with rule nodes inside them.
2. See that your nodes are run correctly
3. Add useless nodes like "return true" script nodes a certain amount of times just before the end of your ending rule chain.
4. Enable debug mode on all of your nodes.
5. See that at some point, some nodes tell success output in debug but that nothing comes in the next linked rule nodes with success arrows.

**Expected behavior**
All my rule nodes should be run and appear in the debug mode.

**Additional context**
I have debug mode activated on a big amount of nodes to see where the problem occurs.

**Comment by devaskim** [comment]
Here is similar but starting from the first node #7472

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
