### ISSUE TITLE
[Bug] 自定义部件出现控制台打印错误信息

### ISSUE THREAD

**Issue by j-tyuan** [thingsboard/thingsboard#7444]
在部件库创建新的部件，会提示：
d {message: 'Expected "=", "}", or identifier but end of input found.', expected: Array(3), found: null, location: {…}, name: 'SyntaxError', …}

此问题会导致：部件的设置无效

**Comment by Ultrazombie** [comment]
Hello,
Is the problem still relevant?
Also, please provide additional information in English.

Best regards.
