### ISSUE TITLE
Long string attribute is not wrapping inside the value field [Bug] 

### ISSUE THREAD

**Issue by AlexDoanTB** [thingsboard/thingsboard#7445]
**Describe the bug**
In previous versions of the platform, the long attribute (e.g. base64 image value) was wrapped inside the value field. The details page had a standard size. Starting v3.4.1, the details page adjusts its width to match the length of the string.    

**Your Server Environment**

The bug is reproducible on each environment — demo.thingsboard.io, thingsboard.cloud + any self-hosted platform v.3.4.1

<img width="792" alt="Screenshot 2022-10-18 at 16 02 02" src="https://user-images.githubusercontent.com/47384595/196456963-73577bbd-527f-4400-8cbb-655078496db9.png">

<img width="781" alt="Screenshot 2022-10-18 at 16 00 42" src="https://user-images.githubusercontent.com/47384595/196457003-ef77164e-b6d9-4868-a285-8d08c35ab9f7.png">

**Comment by xalt7x** [comment]
This issue has been fixed in version 3.5
