### ISSUE TITLE
[Question] Pushing IoT data from AWS Lambda to ThingsBoard (in EC2 instance)

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7447]
**Component**

 * Generic

**Description**

Is it possible to send data from AWS Lambda to ThingsBoard, installed in AWS EC2 instance for ThingsBoard Community Edition? I have read that it is possible with ThingBoard PE with the Platform Integration feature, but want to know if it can be done with CE also. And if so, how to achieve that.

Any help would be very much appreciated.

ps. I have found the following article, where implementation with ThingsBoard IoT Gateway is given. Here, another simpler method is mentioned data can be pushed to Thingsbard from AWS IoT Core as 'First Option'. Is any details available for this option?

https://www.instructables.com/Persist-and-Visualize-AWS-IoT-Data-Using-Thingsboa/

**Environment**

 * OS:  Ubuntu 20.04 LTS (in AWS EC2 instance, Instance type: t2.medium, Memory : 4GB, CPU: 2)
 * ThingsBoard: 3.4.1
 * Browser: Mozilla, Google Chrome, Edge

**Comment by arifulmrislam** [comment]
Have a look at this official guideline page from thingsboard. Hopefully, you will get your answer. 

https://thingsboard.io/docs/guides/

**Comment by trikimiki** [comment]
Hi!

Indeed, the issue is caused by self-signed cert with unconfirmed/unreliable provider.
In order to fix this, you need to either provide a "validated" cert, or add your self-signed cert to the Java truststore
