### ISSUE TITLE
[Question] UI: How to avoid dashboard toolbar duplicatation

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7468]
It appears after using widget action called *Navigate to other dashboard*
![multiple_bars](https://user-images.githubusercontent.com/86909129/197160377-a5cf62b2-0db3-4c21-9b26-bc296bde51dd.jpg)

**Comment by devaskim** [comment]
No one knows(((

**Comment by akseerali** [comment]
This issue still persists. If anyone wants to recreate this issue, following the below steps:

- Create a dashboard and assign it to a user.
- Make sure to set toolbar to "always show" setting.
- Open dashboard from the new user account.
