### ISSUE TITLE
[Bug - critical] Core: No incoming rule engine messages

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7472]
**Description**
No error in logs. No telemetry saved. No rule engine messages AT ALL. 
But new device is created via Gateway MQTT API.

Here is similar (but not the same) #7443

**Configuration**
Defaults, except CoAP, LWM2M,SNMP and Edge disabled

**Affected version**
TB CE: 3.3.4, 3.3.4.1, 3.4, 3.4.1

**Environment**
 - very low load (1-5 devices, data frequency 5-15 min)
- monolith Docker deployment (3.3.4, 3.3.4.1, 3.4), microservices Docker deployment (3.4.1)
- Postgres
- Kafka (with all TB versions), Redis (3.4.1)
- Ubuntu 22, 2 core 8 GB RAM, 84 GB free space

**Video proof**

https://user-images.githubusercontent.com/86909129/197188338-4d429d1d-6e60-4785-b603-cd997d79b5c1.mp4

**Comment by devaskim** [comment]
Well, last week was a week of failures. Sorry team, the described issue is because Redis password have to be set not only for tb-node, but for transports too (I means microservices installation).
However, on earlier version than 3.4.1 and Docker Postgres monolith installation I faced with no incoming rule messages.
Sorry again

**Comment by wujianbo00** [comment]
Has this issue been solved?

**Comment by devaskim** [comment]
Yes, on 3.4.1 and microservice deployment

**Comment by wujianbo00** [comment]
> 
But there are no any desired result with my environment. publish message {"device":"DeviceA"} to topic "v1/gateway/connect", TB did not create device, and publish attributes/telemetry also no result.
my environment:
ubuntu 20.04
TB install from docker
image: thingsboard/tb-postgres@latest  (3.4.1)
queue: in-memory

**Comment by cbruyndoncx** [comment]
I have similar issue with a new install working, and not working anymore after the docker container is restarted.
I see assets for the TB service queue created as Main_xyzgenerated and the only thing I can think of is that somehow the service queue name to use is dynamically regenerated upon restart and causing issue/mismatch
