### ISSUE TITLE
[Bug] UI: Customer assignment is cancelled after asset/device label changed

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7473]
**Proof**

https://user-images.githubusercontent.com/86909129/197190198-12b3cd57-c282-49d6-a486-16773231b84f.mp4

**Comment by AlexDoanTB** [comment]
@devaskim apparently you have a custom TB CE build, bcoz the UI palette is different and the bug is irreproducible on the latest version of the platform.

**Comment by devaskim** [comment]
Thanks @AlexDoanTB for your time. Our instance is really customed and CE. I will look at Git blame.

**Comment by devaskim** [comment]
@AlexDoanTB  Sorry, it is our bug. Next time I will re-check on original version before creating an issue.
