### ISSUE TITLE
TPE all in one gateway integration with node red

### ISSUE THREAD

**Issue by Agroses** [thingsboard/thingsboard#7476]
Hello
I'm using thingspark network server actility that comes with the gateway TPE all-in-one and using Node-Red to get the data to my server
Is there anyone who knows how to make the node red inject data to the network server?

**Comment by Ultrazombie** [comment]
Hello @Agroses, what do you mean about the network server? 
Please describe your logic in more detail.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
