### ISSUE TITLE
Setting HomeDashboard to custom dashboard using Java

### ISSUE THREAD

**Issue by tonyngninlabbhe1** [thingsboard/thingsboard#7479]
**Component**

 * UI
**Description**

I am using the ThingBoard REST API client within a java  application to programmatically to configure ThingsBoard. I would like to be able to set home dashboard to be  a custom dashboard. Looking through the documentation, it seems that I should be able to do this by calling the setTenantHomeDashboardInfo() method with the appropriate parameters. However, this method isn't available within the REST client Object.  How do I access this method or are there any other methods that can be used to accomplish this?

**Environment**

 * OS:  Ubuntu 20.04 & 22.04
 * ThingsBoard: 3.4.0
 * Browser: Chrome

**Comment by devaskim** [comment]
Maybe I am about another thing however I set home dashboard for single user by [updating its additional info](https://demo.thingsboard.io/swagger-ui/#/user-controller/saveUserUsingPOST):
```
{
...
"additionalInfo": {
    "defaultDashboardId": CUSTOM_DASHBOARD_ID,
    "homeDashboardId": CUSTOM_DASHBOARD_ID,
    "homeDashboardHideToolbar": false,
    "defaultDashboardFullscreen": true
}
...
}
```

**Comment by tonyngninlabbhe1** [comment]
ah ok, I thought about that. However, I'm not sure if I'm setting addtionalinfo properly. This is what I have:

`HomeDashboardInfo dashboardInfo = new HomeDashboardInfo(dashboard.getId(), false);
      ObjectMapper mapper = new ObjectMapper();
      ObjectNode additionalInfoNode = mapper.createObjectNode().put("homeDashboardId",
          dashboardInfo.getDashboardId().getId().toString())
          .put("homeDashboardHideToolbar", "false");
      logger.info("****************Additional Info Node: ", additionalInfoNode.toString());
      restClient.getUser().get().setAdditionalInfo(additionalInfoNode);`

I tested it and it doesn't seem to be working.

**Comment by devaskim** [comment]
I think you need to save user:
```
restClient.saveUser(userWithAdditionalInfo);
```
and secondly not `"false"` but `false`
