### ISSUE TITLE
Changing the api endpoints pointing toward my thingsboard

### ISSUE THREAD

**Issue by imananuar** [thingsboard/thingsboard#7487]
**Component**
 * Generic

**Description**
I'm still new to thingsboard app, flutter and dart. Right now I have my thingsboard which have it's own database (it is managed by someone else). I want the thingsboard app to pointed to my thingsboard instead of the demo one. I change the thingsboardApiEndpoint by replacing https://demo.thingsboard.io/ to https://gateway.myiotplatform.com/ in app_constant.dart file but the emulator would take forever to load.

Can someone help me regarding this issue? I try to find the api keyword in the source code but nothing are available. Really have no idea what to do.

Thank you in advanced.

**Comment by ssakharova** [comment]
Hello @imananuar,

ThingsBoard Mobile App is a free-of-charge open-source product. Therefore, I can recommend you rely on community support.
Please try to open an issue on the GitHub, describing all the details of your case and then you will increase the probability that the GitHub community will be able to fix it.

[Issues · thingsboard/flutter_thingsboard_app](https://github.com/thingsboard/flutter_thingsboard_app/issues) 

[Issues · thingsboard/flutter_thingsboard_pe_app](https://github.com/thingsboard/flutter_thingsboard_pe_app/issues)

Best regards,
Sofiia
