### ISSUE TITLE
Blank screen after properly build and install thingsboard

### ISSUE THREAD

**Issue by jitara** [thingsboard/thingsboard#749]
After successfully build 14.0.1 without modification on Ubuntu 16.04:

[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [  1.290 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.070 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.853 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  0.752 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.834 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [04:54 min]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  0.716 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [  8.966 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.027 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  1.873 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  0.620 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  2.061 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  0.440 s]
[INFO] Thingsboard Server SQS Extension ................... SUCCESS [  2.593 s]
[INFO] Thingsboard Server SNS Extension ................... SUCCESS [  1.897 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.025 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  0.502 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  2.872 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  0.730 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [04:37 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.572 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [15:59 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:05 min
[INFO] Finished at: 2018-04-28T02:33:08+07:00
[INFO] Final Memory: 64M/436M
[INFO] ------------------------------------------------------------------------

And properly installed, configured and run the service, I've got blank html page on localhost:8080.

**Comment by jitara** [comment]
I didn't see any error 

`
Results :
Tests run: 265, Failures: 0, Errors: 0, Skipped: 0
`

but when I try to install a precompiled package, it run just fine.

any ideas?

**Comment by mp-loki** [comment]
Please check `/var/log/thingsboard/thingsboard.log` for errors

**Comment by jitara** [comment]
no errors found. here is the log file:

[thingsboard.log.txt](https://github.com/thingsboard/thingsboard/files/1957094/thingsboard.log.txt)

**Comment by mp-loki** [comment]
Log looks fine.
```log
2018-04-28 07:10:32,855 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8080 (http)
2018-04-28 07:10:32,883 [main] INFO  o.t.s.ThingsboardServerApplication - Started ThingsboardServerApplication in 25.095 seconds (JVM running for 25.96)
```

Do you see any errors on browser console when you access [http//localhost:8080](http//localhost:8080)? Are you able to call REST API e.g. with Postman or curl, like:

```
POST /api/auth/login
Host: 127.0.0.1:8080
Content-Type: application/json
Accept: application/json

{"username":"tenant@thingsboard.org", "password":"tenant"}
```

**Comment by jitara** [comment]
ok will try it,

FYI the HTML response is equal with the original (precompiled) one, it just looks the script is not running.

**Comment by mp-loki** [comment]
Javascript disabled in browser? What's in the browser console? Did you try to connect from other laptop or phone in the same network?

**Comment by mp-loki** [comment]
There could also be issue with UI build. For UI module maven calls node.js builder, and it does not return error code (probably error in our build config), so when the UI build is actually failed, in maven it shows success. So I recommend you to re-build your project with maven but pay attention to what is actually logged when building UI module.

**Comment by jitara** [comment]
Ok, I've got it works with latest build (1.4.0-SNAPSHOT), but I don't know why it doesn't works using the release version.
