### ISSUE TITLE
[Bug] Rule chain templates: could not resolve property: assignToEdge of: org.thingsboard.server.dao.model.sql.RuleChainEntity [SELECT rc FROM org.thingsboard.server.dao.model.sql.RuleChainEntity

### ISSUE THREAD

**Issue by tjdznet** [thingsboard/thingsboard#7492]
org.hibernate.QueryException: could not resolve property: assignToEdge of: org.thingsboard.server.dao.model.sql.RuleChainEntity [SELECT rc FROM org.thingsboard.server.dao.model.sql.RuleChainEntity rc WHERE rc.tenantId = :tenantId AND rc.type = :type AND LOWER(rc.searchText) LIKE LOWER(CONCAT('%', :searchText, '%')) order by rc.assignToEdge asc]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: assignToEdge of: org.thingsboard.server.dao.model.sql.RuleChainEntity [SELECT rc FROM org.thingsboard.server.dao.model.sql.RuleChainEntity rc WHERE rc.tenantId = :tenantId AND rc.type = :type AND LOWER(rc.searchText) LIKE LOWER(CONCAT('%', :searchText, '%')) order by rc.assignToEdge asc]

![image](https://user-images.githubusercontent.com/20569692/198030445-7db0eefb-aaee-4976-a566-b7cb07baa070.png)

![image](https://user-images.githubusercontent.com/20569692/198029842-db4edbdf-1333-40b4-8fcf-4b4f9d79940a.png)

**Comment by trikimiki** [comment]
If the problem described in this issue can be reproduced in the latest version, please create a new ticket with a concise description of the problem.
