### ISSUE TITLE
[Question] Is there a way to increase the default height of a dashboard ?

### ISSUE THREAD

**Issue by arxitpln** [thingsboard/thingsboard#7493]
**Component**

 * UI

**Description**
For my client needs, I want to stack a lot of widgets one on top of another (to generate a report that fits in one column), but at some point, I reach the end of the dashboard. I can not add another widget after a certain height limit. Is there a way to increase it ?

![Dashboard](https://user-images.githubusercontent.com/68555402/198034115-a0c5cda9-f447-40d1-87bd-a64f2aa2156e.png)

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.4.1 PE
 * Browser: Firefox (64 bits) 106.0.1

**Comment by devaskim** [comment]
I guess it's [hardcoded](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts#L211)
