### ISSUE TITLE
How to migrate ThingsBoard Data to another server in window

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#7502]
OS: Window
Things Board Version: 3.4
Database: Timeseries (Postgresql)
Type: CE edition

I try to migrate the things board to another high-end PC with more storage space, Can I ask what is the suitable solutions/step to migrate the things board data including all the data, devices, rule chain, dashboard and etc? I find some solutions but it is for the ubuntu/Linux solution, and there is no solution for the Window version...Hopefully can get some help to successful migrate the things board's data to new PC.

Any suggestions is appreciated. Thank you..

**Comment by devaskim** [comment]
1. `devices, rule chain, dashboard` and other entities you could migrate via (Version Control)[https://thingsboard.io/docs/user-guide/version-control/] feature.
2. To copy Postgresql data use `pg_dump` or one of similar tools if your Postgresql instance is running as a separate application. If you use Docker deployment, read about how to copy Docker volume to another machine (there are a lot of manuals)

**Comment by ngsuityan** [comment]
> 1. `devices, rule chain, dashboard` and other entities you could migrate via [Version Control](https://thingsboard.io/docs/user-guide/version-control/) feature.
> 2. To copy Postgresql data use `pg_dump` or one of similar tools if your Postgresql instance is running as a separate application. If you use Docker deployment, read about how to copy Docker volume to another machine (there are a lot of manuals)

i try to use PgAdmin4 to backup and restore but always failed.... postgre show ignored the restore error 610....any exact ways to migrate thingsboard...?

**Comment by Raven888888** [comment]
@devaskim I tried to use Version Control to migrate, it always hit 500 timeout.

I have 15000+ devices and 15000+ assets to push to git.

**Comment by Raven888888** [comment]
For more context, I have increased `SPRING_MVC_ASYNC_REQUEST_TIMEOUT` to more than enough to get over 500 timeout.

Tried again, this time UI shows "No changes to commit", but I have 15000+ devices to commit!

Here is the POST `/api/entities/vc/version` request:
```json
{"branch":"release2","versionName":"da","syncStrategy":"MERGE","entityTypes":{"DEVICE":{"syncStrategy":null,"saveRelations":true,"saveAttributes":true,"saveCredentials":true,"allEntities":true}},"type":"COMPLEX"}
```
Response is 200 with a UUID string.

It is followed by another GET `/api/entities/vc/version/<uuid>/status`
Response is 200 with
```json
{"version":null,"added":0,"modified":0,"removed":0,"error":"java.lang.RuntimeException: Future is already done!","done":true}
```

**Comment by devaskim** [comment]
@Raven888888  I suggest to create bug, provide all of these information and hope that core team help you

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
