### ISSUE TITLE
[Question] Custom action with popover

### ISSUE THREAD

**Issue by stevmei** [thingsboard/thingsboard#7504]
**Component**

 * UI

**Description**
The new popover functionality is very helpful! I need to implement a way to trigger different popovers depending on the device type. Until now it was possible to use a custom action to extract the device type from attributes using WidgetContext and open different dashboard states. Is it also possible to trigger a popover with different target states using JS?

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.4.1PE
 * Browser: Firefox 106.0.1

Thank you very much!

**Comment by devaskim** [comment]
Hi @stevmei 
I guess you asked about this
```
widgetContext.actionsApi.openDashboardStateInPopover( ... );
```
Here is a list of [parameters](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L94) for `openDashboardStateInPopover` API

**Comment by stevmei** [comment]
Hey @devaskim 
Yes, thank you very much! Must have overseen that in the API and `openDashboardStateInPopover` was not auto-completed in the editor.

If anybody needs a minimal example, you can start here:

```javascript
var $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
    $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device.id, 'SERVER_SCOPE', ['device_type'], { ignoreLoading: true }).subscribe((attributes) => {
        if (attributes.length) {
            openDashboardStatesPopover($event, attributes[0].value);
        }
    });
});

function openDashboardStatesPopover($event, statedId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.actionsApi.openDashboardStateInPopover($event, statedId, params, true, undefined, true, "500px", "500px");
}
```

**Comment by Allen4078** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/115608081/212877108-7e69ffda-31f4-4823-aa17-7882daa40f3c.png">
Showing this error when i tried(made some slight change):
var $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
    $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device.id, 'SERVER_SCOPE', ['device_type'], { ignoreLoading: true }).subscribe((attributes) => {
            openDashboardStatesPopover($event, 'test');
    });
});

function openDashboardStatesPopover($event, statedId) {
    var params = {
        entityId: entityId,
        entityName: entityName
    };
    widgetContext.actionsApi.openDashboardStateInPopover($event, statedId, params, true, undefined, true, '25vw', '25vh');
}

**Comment by Allen4078** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/115608081/212877643-0f36ad7a-5afd-40e4-aafa-bd00115bfb36.png">
Showing this error when i tried(made some slight change): 

`var $injector = widgetContext.$scope.$injector; let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService')); $injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => { $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device.id, 'SERVER_SCOPE', ['device_type'], { ignoreLoading: true }).subscribe((attributes) => { openDashboardStatesPopover($event, 'test'); }); });
function openDashboardStatesPopover($event, statedId) {
var params = {
entityId: entityId,
entityName: entityName
};
widgetContext.actionsApi.openDashboardStateInPopover($event, statedId, params, true, undefined, true, '25vw', '25vh');
}`

**Comment by stevmei** [comment]
@Allen4078 
For me, your example code is working fine, I've tried it with an entity table view and a second dashboard state 'test'. I was able to visualize real-time data of the entity that was used to open the popover, so params should be passed to 'test' as expected.
Maybe this is rather related to a widget that is loaded inside your 'test' dashboard state?

I'm using TB 3.4.2PE.

**Comment by Allen4078** [comment]
i am using piechart and slice click as action
