### ISSUE TITLE
MQTT over SSL

### ISSUE THREAD

**Issue by Pankaj9410557422** [thingsboard/thingsboard#7508]
Can anyone help me out with MQTT over SSL.

1. I am creating server.pem and server_key.pem using openssl following the documentation.
2. I changed permissions for the certs generated according to thingsboard.conf file.
3. Configured my thingsboard.conf file accordingly.
4.Then genrerated client side certificate and key using openssl following the documentation.

Now my questions are:

1.How do i generate certificate chain like one mentioned in documentation i.e. "tb-server-chain.pem" ?
2. I did hit and trial and during that i got -
```
2022-10-28 17:24:28,832 [nioEventLoopGroup-4-1] ERROR o.t.s.t.mqtt.MqttTransportHandler - [1ba05737-8605-4147-ae1e-da38cd13ab2c] Unexpected Exception
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
```
My thingsboard.conf file:
```
export MQTT_SSL_ENABLED=true
export MQTT_SSL_CREDENTIALS_TYPE=PEM
export MQTT_SSL_PEM_CERT=server.pem
export MQTT_SSL_PEM_KEY=server_key.pem
export MQTT_SSL_PEM_KEY_PASSWORD=secret

Any suggestions what i might be doing wrong?

**Comment by ashvayka** [comment]
To generate a valid certificate you need to create a CSR and ask one of the authorized CA to sign it.

**Comment by maksonlee** [comment]
According to [1], a self-signed certificates can still be used?

https://thingsboard.io/docs/user-guide/mqtt-over-ssl/#self-signed-certificates-generation
