### ISSUE TITLE
How to delete thingsboard old data in the postgresql

### ISSUE THREAD

**Issue by ngsuityan** [thingsboard/thingsboard#7509]
Operating System: Window 10
Thingsboard version: TB CE 3.4.1
Queue Messager: RabbitMQ
Database: PostgreSQL

I want to export my PostgreSQL database and migrate to the new server, however, it taking 3 days on importing the backup file. I am using the method that backup using PgAdmin 4 and restore also at another server using PgAdmin. After 3 days importing, the importing is fail due to network... After researching, there is a lot of data that is not necessary and I am thinking to delete all the data no matter alarm, debug data and etc and only remain last 6 months data.....to fasten the speed of exporting and importing the database to ease the step migrating Things board to the new server.

The following is the schema list, all inside contain high volume of data
![image](https://user-images.githubusercontent.com/83693028/198966764-005e2190-6d3b-4540-9302-c8da1bc3105e.png)

Can someone advise me on how to delete unnecessary things board data that are store inside PostgreSQL, and how to backup and restore postgresql thingsboard database in **WINDOWS** version?

For Thingsboard part, I upgrade the version of TB CE to 3.4.1 for migrating thingsboard purpose but the version control looks weird, is that this is a bug after upgrading the Thingsboard server?

![image](https://user-images.githubusercontent.com/83693028/198968012-a830ad68-e152-4d76-8b21-c714aafd37e2.png)

**Comment by HaydenBurrows** [comment]
I had the same problem.

I managed to get my database from 20GB to 2.5GB by following the steps mentioned here: [Postgres cleanup](https://blog.thingsboard.io/2020/09/deleting-timeseries-of-deleted.html?m=1) 

Note that in version 12+, omit the * when using DELETE.

Hopefully this will applies as I see you are using timescaleDB. I have used these commands on postgres 12.10 and 14.4. I would recommend to vacuum the partitions of ts_kv table separately as it takes a bit of time. If you want to see info on how much space each takes up you can use PGadmin and use the statistics tab

You can use PGadmin to backup and restore if you like or command line via PSQL. Their website has good document regarding this. Some info here:
https:///thingsboard/thingsboard/issues/6598.

Not sure about version control issue.

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by GrayCygnus** [comment]
Perhaps a more comfortable solution is to DROP the partitions on TS_KV table that you no longer want. 

ThingsBoard has some of their tables [partitioned](https://www.postgresql.org/docs/current/ddl-partitioning.html). For example I see on my TS_KV table partitions for each month. 

This is very easily done via PGAdmin GUI. Or you can always do a query and DROP the partition you no longer want.
