### ISSUE TITLE
Bug: No decimal values for ticks on Y-axis of Timeseries - Flot widget

### ISSUE THREAD

**Issue by jevsovar** [thingsboard/thingsboard#753]
Widget Timeseries - Flot (and also Timeseries Bars -Flot) does not show any decimal values for Y-axis ticks, regardless of "The number of decimals to display" setting.

Lets say if you set Y-axis range manually:
 - minimum value on the scale: 43
 - maximum value on the scale: 45
 - step size between ticks: 0.5
 - the number of decimals to display: 2

There should be 5 ticks displayed: 43.00, 43.50, 44.00, 44.50, 45.00.
Instead, there are 5 ticks, but they are marked as 43, 44, 44, 45, 45.

![slika](https://user-images.githubusercontent.com/256564/39487745-822dda4a-4d80-11e8-9050-c01c66e23a64.png)

Thingsboard version is v.1.4.0.

Jan

**Comment by holgerbrandl** [comment]
This problem is still present in TB in v3.2.2

![image](https://user-images.githubusercontent.com/200952/120154424-2a3ec280-c1f0-11eb-8956-f1ad1b49c594.png)

**Comment by ban2derlog** [comment]
Hi, does your issue persist on latest ThingsBoard version?
