### ISSUE TITLE
[Question] Sorting a string with values via rulechain?

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard#7532]
Hello,

I have a problem with the rulechain. 
Earlier I got a string with a keya and their values in it, always in the same order.
Now the values aren´t always in the same order, so the values get extracted incorrectly.

My current rulechain looks like that:

`if (!('values' in msg))
    return { msg: msg, metadata: metadata,  msgType: msgType };

var data = JSON.parse(msg.values.replaceAll('\'','"'));

data = {
    "Tagesenergie": data[0].v = parseInt(data[0].v,16)/10,
    "Strom DC": data[1].v = parseInt(data[1].v,16)/100,
    "Energie Total": data[2].v = parseInt(data[2].v,16),
    "Monatsenergie": data[3].v = parseInt(data[3].v,16),
    "SAL": data[4].v = parseInt(data[4].v,16),
    "SYS": data[5].v = parseInt(data[5].v,16),
    "Jahresenergie": data[6].v = parseInt(data[6].v,16),
    "Spannung DC": data[7].v = parseInt(data[7].v,16)/10,
    "aktuelle Leistung": data[8].v = parseInt(data[8].v,16)/2/1000
};

return {
    msg: data, 
    metadata: metadata, 
    msgType: msgType
};`

The string looks like that:
{
   "values": "[{'id': 'PV-001.Solarmax3000S.Daten.KDY', 'v': '4B'}, {'id': 'PV-001.Solarmax3000S.Daten.IDC', 'v': '12E'},
}

Now I would need some function which search for a cretain keyword in a string and safe the value in the correct varable.

**Comment by rungg12** [comment]
Thank you!

But now the variable "data" is not defined ...

**Comment by devaskim** [comment]
Did you try to init `data` from `msg`? 
I gave your idea but not out the box solution

**Comment by rungg12** [comment]
yes i got it working, thanks
