### ISSUE TITLE
[Bug] com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: SettableFuture@XXXX[status=PENDING] error inside Rule Node

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#7533]
**Describe the bug**
I use python code to inject raw timeseries data inside thingsboard. This data is then processed by rule chains to get calculated datas and store them as time series.

I have this error in a rule node output :

com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: SettableFuture@a1b80ec[status=PENDING]

Could anyone tell me what this error means ?

**Your Server Environment**

thingsboard.cloud

**To Reproduce**
1. Inject data points with requests library in python to thingsboard.
2. See that the rule chains are not well processed : some rule nodes failed with the error written above.

**Expected behavior**
My rule chains should be well processed and have no error / failures inside the nodes.

**Comment by jasonlikelucy** [comment]
I've got the same problems!
Any idea? Thank you!

**Comment by jasonlikelucy** [comment]
![image](https://user-images.githubusercontent.com/18350922/202171923-24fcf4d0-f0d7-417c-a46e-5c9d6138c1cb.png)

the node just has the default code

**Comment by jasonlikelucy** [comment]
![image](https://user-images.githubusercontent.com/18350922/202172708-48262abd-47af-45a6-8e10-d67320e9e9c3.png)
when i remove the node , the rule chains processed and have no error / failures inside the nodes,once add the node with default code the problem appeared.

**Comment by Raven888888** [comment]
I am seeing the same error in my k8s TB setup, v3.4.1.

I have not seen this error in my previous monolithic setup

**Comment by Raven888888** [comment]
I resolved the issue, it is because my js eval queue is full.

**Comment by xiddjp** [comment]
> I resolved the issue, it is because my js eval queue is full.

Hello, do you know how to config js eval queue size?

**Comment by mykhailokornieiev** [comment]
You can get familiar with following documentation https://thingsboard.io/docs/user-guide/install/pe/http-transport-config/#queue-configuration-parameters
I close this ticket due to inactivity. In case of any questions feel free to open a new ticket with full description of your issue/questions
