### ISSUE TITLE
[Question] Display format unix timestamp as value in table (Browser TimeZone)?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7535]
* UI
How to display a unix timestamp like LastActivityTime the same like the automatic "ts" timestamp?
<img width="418" alt="DateTime" src="https://user-images.githubusercontent.com/49442805/199537633-4c7147df-6eaf-4723-aeda-5cbf94f9eed3.png">

This gives only one fixed timezone (with long text of the timezone)
'value' could be like 1666970762452
output looks like "Fri Oct 28 2022 17:32:41 GMT+0200 (Central European Summer Time)"
```
var a = new Date(value);
return a;
```

I want it like: 2022-10-28 17:27:41 and changing with the browser timezone.

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: PE 3.3.3
 * Browser: Edge

**Comment by Backdraft007** [comment]
`var newDate = new Date();
newDate.setTime(value);
var dateString = newDate.toLocaleString();
return dateString;`

**Comment by KenSense** [comment]
That gives me this format 10/28/2022, 5:26:02 PM so that is something, but that is not the right browser  timezone.

The default 'ts' in the widget is using some function to do it correctely, can't we access that and use it?

**Comment by mde2017** [comment]
You can use moment.js for this:
`return moment(time).format('YYYY-MM-DD hh:mm:ss');`

https://momentjs.com/

**Comment by KenSense** [comment]
That gives indeed some nice format options, thanks but is not following the browser time.
I assume we need access to the thingsboard UI timezone setting for that.

**Comment by mde2017** [comment]
Yes, it's a lot easier to use than Vanilla JS for formatting datetimes.

Perhaps this could help you with fetching the timezone of the browser time (returns offset in Minutes):

`const date = new Date();
const offset = date.getTimezoneOffset();
console.log(offset);    // -300`

https://attacomsian.com/blog/javascript-current-timezone#:~:text=To%20get%20the%20current%20browser%27s%20time%20zone%2C%20you,the%20local%20time%20zone%20is%20ahead%20of%20UTC.

**Comment by KenSense** [comment]
I'm trying this but it may follow the browser timezone but not the UI timezone setting that I would like.
Also, not sure about the 60min offset that I added to make it correct for my browser.

```
if (value==0) {return "" }
else{
const date = new Date();
const offset = date.getTimezoneOffset() + 60;
var dateUsertimezone = value + offset * 60;
return moment(dateUsertimezone).format('YYYY-MM-DD HH:mm:ss');
}
```
