### ISSUE TITLE
Bug: Widget Timewindow

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#754]
Hello Guys!

I think encountered bug adjusting the timewindow of my widgets. Here is what I tried:

I tried to set the timewindow to historic values with a time period of less than one day. For example from 01.04.1999 10:00 until 01.04.1999 18:00. A timewindow of 8 hours. But everytime i try to set the timewindow, the "Date To"-entry is changed to the day after (meaning the 02.04.1991 in this case).
I attached a picture of what I mean. 

![map-problem](https://user-images.githubusercontent.com/37292275/39525353-05c62614-4e1c-11e8-957c-8e31a528b5f9.png)

Any help is much appreciated! 
Cheers

**Comment by untilbit** [comment]
I found similar issue in the community edition

**Comment by RondoRonaldo** [comment]
This bug was fixed in the latest ThingsBoard versions.
