### ISSUE TITLE
[Question] Custom menu settings only for customer

### ISSUE THREAD

**Issue by Timmiegamer** [thingsboard/thingsboard#7543]
**Custom menu**

Is there a way to make the custom menu only apply for customer users? 
I am trying to set it up but I only keep hiding things for me (tennant Admin) and that won't work.

For some extra context I only want these options active for a customer but it applies to every user.

"disabledMenuItems": [
"home",
"rule_chains",
"integrations",
"converters",
"roles",
"entity_view_groups",
"customers_hierarchy",
"user_groups",
"customer_groups",
"asset_groups",
"device_groups",
"scheduler",
"audit_log",
"widget_library",
"mail_server",
"mail_templates",
"custom_translation",
"custom_menu",
"login_white_labeling"
]

**Environment**

 * OS:  Windows 10
 * ThingsBoard: PE
 * Browser: Chrome latest

**Comment by helsmore** [comment]
@Timmiegamer I was able to set custom menus on a per-customer basis based on a comment on another issue (https://github.com/thingsboard/thingsboard/issues/4098#issuecomment-779703670).

The trick is to define a server-scope attribute called '`customMenu`' on the customer you want to customise the menu for, the value of this attribute should be a JSON object containing '`disabledMenuItems`' and '`menuItems`' arrays where you tweak the menus as desired. For example:

```json
{
  "disabledMenuItems": [
    "home"
  ],
  "menuItems": [
    {
      "name": "My Custom Menu",
      "iconUrl": null,
      "materialIcon": "menu",
      "iframeUrl": "https://thingsboard.io",
      "dashboardId": "<YOUR DASHBOARD ID HERE>",
      "hideDashboardToolbar": true,
      "setAccessToken": false,
      "childMenuItems": []
    },
    {
      "name": "My Custom Menu 2",
      "iconUrl": null,
      "materialIcon": "menu",
      "iframeUrl": "https://thingsboard.io",
      "setAccessToken": false,
      "childMenuItems": [
        {
          "name": "My Child Menu 1",
          "iconUrl": null,
          "materialIcon": "menu",
          "iframeUrl": "https://thingsboard.io",
          "setAccessToken": false,
          "childMenuItems": []
        },
        {
          "name": "My Child Menu 2",
          "iconUrl": null,
          "materialIcon": "menu",
          "iframeUrl": "https://thingsboard.io",
          "setAccessToken": false,
          "childMenuItems": []
        }
      ]
    }
  ]
}
```

The customisations you make at the customer level will then flow down to that customer's users.

Hope that helps.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
