### ISSUE TITLE
Prometheus returning error code 500

### ISSUE THREAD

**Issue by Sushmitha-rao** [thingsboard/thingsboard#7558]
I have installed thingsboard on linux, I want to monitor the total messages received per second. I tried to monitor it with prometheus. I am not able to fetch any metrics from [http://localhost:8080/actuator/prometheus](http://odroid:8080/actuator/prometheus). It returns error 500.

**Comment by Sushmitha-rao** [comment]
I have set METRICS_ENABLED to true and METRICS_ENDPOINTS_EXPOSE to prometheus

**Comment by smatvienko-tb** [comment]
does it related to the rule-engine microservice only or it does work for the tb-core or monolith?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
