### ISSUE TITLE
telemetry returning {}

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#756]
after sending this request to thingsboard
```
http://localhost:8080/api/plugins/telemetry/DEVICE/f140ea10-4e9f-11e8-bb2f-c9d3176405a0/values/timeseries?keys=nodeid,nodename,type,value&startTs=1293710877&endTs=166782877&interval=60000&limit=100&agg=NONE
```

i receive empty json: {}

but if i fetch single value (as following the tutorial), it works.

**Comment by rchemali** [comment]
use timestamp beetwenn 2 days

**Comment by quirosaur** [comment]
````
http://localhost:8080/api/plugins/telemetry/DEVICE/f140ea10-4e9f-11e8-bb2f-c9d3176405a0/values/timeseries?keys=nodeid,nodename,type,value&startTs=1525881600&endTs=1526054400&interval=60000&limit=100&agg=NONE
````

still same empty {}

**Comment by micnori** [comment]
I have a similar problem: I'm not able to retrivce historical data with the telemetry API. It returns only the last value.
This is an example of call:
curl -v -X GET "http://localhost:28080/api/plugins/telemetry/DEVICE/534ab830-c0a6-11e8-8b9d-51265072593d/values/timeseries?startTs=1538085600000&endTs=1538690400000" --header "Content-Type:application/json" --header "X-Authorization: Bearer TOKEN"
I'm using CE 2.1

**Comment by vparomskiy** [comment]
your query does not contain 'key' parameter that describes what telemetry keys you want to fetch.

**Comment by micnori** [comment]
Thanks @vparomskiy with the "keys" parameter it work :)

**Comment by asaad1882** [comment]
curl -v -X GET --header "Content-Type:application/json" --header 'X-Authorization: Bearer   eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc21hYS5zYWFkQGR1LmFlIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiIzYzdlZDdkMC05NTBkLTExZTktOTgwMy1mMzgzYTNkY2Q5MWIiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMGExNDMyNDAtOTUwZC0xMWU5LTk4MDMtZjM4M2EzZGNkOTFiIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTYxOTc2ODgyLCJleHAiOjE1NjE5ODA0ODJ9.rcqnBU3FDcOzpwfwuEfzC9qPUnefJYuzx95hRB7E1YsFleHwRGmvP7A5tynQL25e2k_NZhc-du2O8SLYbESp7w' 'http://94.205.239.99:8080/api/plugins/telemetry/DEVICE/717a31b0-967e-11e9-9803-f383a3dcd91b/values/timeseries?keys=lat&startTs=1561852800000&endTs=1562025600000'
using CE2.3.1

**Comment by jnmanchado** [comment]
@asaad1882 Try to use the "limit" parameter too.

And the original issue wasn't be answered. I have the same behaviour than @quirosaur, but maybe the problem is on timestamps, that are in seconds and not in milliseconds. 

Even if I fix that, the parameters "agg" and "interval" seems not be working.
