### ISSUE TITLE
[Bug] Labels not being fetched

### ISSUE THREAD

**Issue by ljubomirsinadinovski** [thingsboard/thingsboard#7568]
**Describe the bug**
When I login inside the Dashboards Menu I do not see the proper namings, instead I see the keys of the strings as shown in the image

![image](https://user-images.githubusercontent.com/24614182/200502560-f3282f3a-5109-419e-8dd6-da065dcf6ea4.png)

**Your Server Environment**

  * ThingsBoard Version: 3.3.1PE
  * OS Name and Version: Ubuntu 18.04.5 LTS

**To Reproduce**
When installing updates (maybe it was existing before), downgrading and starting again is not an option due to the other unsolved ISSUE I have opened: https://github.com/thingsboard/thingsboard/issues/7374

**Expected behavior**
Show me the string names

**Comment by Backdraft007** [comment]
That is a local browser cache problem. Clear your cache completely.

**Comment by ljubomirsinadinovski** [comment]
> That is a local browser cache problem. Clear your cache completely.

I confirm that this was the problem, thank you.
