### ISSUE TITLE
[Feature Request] Provide rule chain option to allow cyclic links

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7577]
**Is your feature request related to a problem? Please describe.**
Our devices push data through TB gateway. Each device is bound to single asset. 
We would like to store attributes and telemetry only to asset, so each time new data comes the originator will be changed to asset.

Due to possible race conditions between device/asset creation and data pushing we need some `wait/repeat` logic if originator changing is failed. In case of failure we redirect data to `wait/repeat` rule chain which has max retries control. On the end of each `wait` iteration data should be redirected back to `Change originator` node. 

**But I can't link** output of `wait/repeat` rule chain with input of `Change originator` node due to unknown limitations of Rule Engine UI. I assume it is cyclic control mechanism

**Describe the solution you'd like**
I would like to have option for rule chain to enable cyclic links between rule nodes. It will be `false` by default for backward compatibility. Also this option should be displayed in the tables of rule chain, as it is already done for `Root` option.

I am open to contribute if some of TB core team (@ashvayka @ikulikov @vvlladd28 ) point me out from where to start.

**Describe alternatives you've considered**
Duplicate part of rule chain nodes.

**Comment by poelstra-sioux** [comment]
@devaskim I ran into a similar situation. What you _can_ actually do, is to create the cycle through another rulechain.

For example, create rulechains A and B. In rulechain B you add a To Rulechain node, and make it point to A. In rulechain A, at the place where you want it to 'look back to itself', you add a To Rulechain node to chain B, which will thus loop it back to chain A.

A remaining issue is that you can't link a chain's input directly to a To Rulechain node, so you'll need to put a 'dummy' node (e.g. a MessageTypeSwitch) in-between if you don't have any other processing you need to do there.

@ikulikov Note that the ability to (conditionally) route messages in a loop this way is very important for us, so please don't remove / prevent that possibility in a future version :)

**Comment by devdoob** [comment]
@poelstra-sioux I am stuck in this. Can you please share some screenshots of what you provided as a solution. 

I have created a rulechain A which is calling rulechain B... now I want to call rulechian B again which is not possible... so I am ending rulechain B logic to point rulechain A.... now what and where to do in rulechain A that it bypasses ebeything in it and directly provide input ot rulenode B

**Comment by poelstra-sioux** [comment]
@devdoob In my case, this piece of logic is used to emulate a real device in a development environment, such that we don't need 'real' devices connected to TB, and have some rulechains emulate them instead, generating telemetry as if it was sent by a device.

Somewhere near root rulechain, we filter out certain messages and send these to the FOTA Emulator chain. Then:
![image](https://github.com/user-attachments/assets/8fca0f5e-c77d-48ae-a279-3120a01ef7fe)

![image](https://github.com/user-attachments/assets/bb913331-2ef5-4dd9-88a4-8333c8e800a3)

In my case, the computeNextState function will detect whether the message was a device message, or a looped-back message of itself.

**Comment by devdoob** [comment]
Thank you. Got the hint

**Comment by devaskim** [comment]
@poelstra-sioux Thanks for providing detailed information. Added your solution to [awesome-thingsboard](https://github.com/devaskim/awesome-thingsboard/blob/main/README.md#rule-chains)

**Comment by devaskim** [comment]
@dealnat @SuminDenys  Please, take a look at this feature request.

**Comment by SuminDenys** [comment]
Hi @devaskim,

Our team has discussed your feature request in the meeting and we came to the following conclusion:

**At the moment, the logic proposed by the community is the most acceptable option for ThingsBoard team.
Because adding this type of feature can negatively affect the experience of new users and create additional stability issues.**
 
I am closing this issue for now. If you have any further questions or require clarification, please let me know.
