### ISSUE TITLE
[Question] How a device can retrieve its last saved data if it is from inactive to active state

### ISSUE THREAD

**Issue by pdt590** [thingsboard/thingsboard#7578]
I have a Light device. It is turning on, and its current status data (ON) is sent and saved on Thingsboard. 
I try to power off the Light. I want the Light is still ON when I power on the Light again.

My question is how the Light can retrieve its last status data (ON) when power on? 

Thank you for your support.

**Comment by myroslav-tb** [comment]
Hi @pdt590, I assume you are using a control widget to turn the device on and off. The device should return its state as an attribute or timeseries key.  You can set this key for the widget to correctly display a device state
![image](https://github.com/thingsboard/thingsboard/assets/158559147/4782b672-17d0-4df9-a914-2ac24e801da4)

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
