### ISSUE TITLE
Update locale.constant-zh_CN.json

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7582]
**Component**

Changed
Unified translation of "layout"
Unified translation of "widget-action"
Unified translation of "custom"
Unified translation of "language"
Match the line numbers of the two files, locale.constant-zh_CN.json and locale.constant-en_US.json, to ensure consistency
Added
Add translation of smpp-provider
Add translation of lwm2m-security-config
Add translation of lwm2m
Add translation of snmp
Add translation of markdown
Add translation of server-error
Add translation of widgets

**Description**
The localization resource files in Chinese and English are numbered aligned, and all the content that is not translated in version 3.4.2 is added. If there is any incorrect place, please correct me.

**Environment**

 * OS:  windows 10
 * ThingsBoard: 3.4.2
 * Browser: chrome 107.0.5304.106

**Comment by xalt7x** [comment]
@struggle3 , I assume that this issue is related to PR #7581 , and therefore it is no longer relevant.
