### ISSUE TITLE
[Question] API and Storage info

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7583]
**Component**

 * API
**Description**
Hello thingsboard community! I would like to access part of API usage info via API itself. I cannot find a way to do this. Maybe someone here will know. I am interested in data points storage days or transport daily activity for example.

Broader problem is that Thingsboard shuts down as its Postgress database fills up. I managed to do some data retention which prevents it most of the time. But the ammount of data sent to Thingsboard is going to be dynamic and can increase rapidly in certain time periods - so I would like to get notified (via Thingsboard or API call in NodeRed) that this situation is probably about to happen. 

Any tips?

Thanks in advance for any help.

**Environment**

 * ThingsBoard: Community (latest)
 * Browser: Edge

**Comment by devaskim** [comment]
Based on information from browser DevTool I guess that TB `API usage` dashboard uses [entities query API](https://demo.thingsboard.io/swagger-ui/#/entity-query-controller). Input data for this API is complex so you can copy the right structure from `WS` filter of `Network` tab in browser DevTools

![api](https://user-images.githubusercontent.com/86909129/201200479-bad41352-8d30-4670-bd4d-9b3be3db4788.jpg)

**Comment by devaskim** [comment]
What did you mean by filling up Postgres database? No disk space on machine?

**Comment by samokomo** [comment]
Thanks for this tip! I used it, with different API call but still, good result. Yah and the problem is related to running out of disk space in Postgres. 
I am wondering, how much space does one datapoint take in database. Now I can track count of datapoints, it would be a good piece of info.

**Comment by samokomo** [comment]
Thanks for this tip! I used it, with different API call but still, good result. Yah and the problem is related to running out of disk space in Postgres.
I am wondering, how much space does one datapoint take in database. Now I can track count of datapoints, it would be a good piece of info

**Comment by devaskim** [comment]
I guess the size of data point is various value, because it could be string or number.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
