### ISSUE TITLE
Identify devices connected to GW

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7597]
Hi, 

I am using ThingsBoard 3.4.1, OS is Linux 20.04. 

I had previously used ThingsBoard where the GW or RaspberryPi is connected to the ThingsBoard. One single device is connected to the GW and Temp sensor was attached to the  device. For RPi, temp-humidity sensors was attached. 
Access Token is issued for GW or RPi. When only one device is connected to the GW or RPi, then it is fine. But if more than one devices are connected to the GW (which is more common) how ThingsBoard can uniquely identify the devices attached the GW? 
Because ThingsBoard does not know which devices are behind the GW, as the GW is only got an access token to connect to the ThingsBoard.

Any hints, related URL would be very helpful.

Best regards

**Comment by Backdraft007** [comment]
Which GW is it? And which connector do you use?

**Comment by debacs83** [comment]
Thank you for responding. 

I have previously used Private LoRa-GW.  This time I am planning to use both PrivateLoRa and LoRaWAN gateways. This time Installed Thingsboard in AWS EC2 instance (Ubuntu). LoRaWAN-GW will be connected through AWS IoT Core for LoRaWAN. Then through Lambda it will send the data to Thingsboard. For Private-LoRa-GW, AWS API-GW will send the data to Lambda and then to Thingsboard in EC2. 

ps.
I was looking to the Thingsboard documents and 'relations'. Seems Thingsboard issued 'entity-id' for each of its entities (device, asset, dashboard etc.). I have created an Asset and through 'relation' and 'contains' I have added two devices (for the access token has been generated - I am testing them with pseudo generated data, pushing through AWS Lambda). Is it possible to set them? When looking at the Thingsboard PostgreSQL db, Asset and Devices it contains are there in the 'relation' table. 

Is there a way to keep track of the devices connected to the gw? Sorry, I might be quite wrong. 
Or do I need to install Thingsboard Gateway?

Regards

**Comment by devaskim** [comment]
Thingsboard Gateway is based on [Thingsboard MQTT API for gateway](https://thingsboard.io/docs/reference/gateway-mqtt-api/)
The only specificity of this API is what you need to [pass device name](https://thingsboard.io/docs/reference/gateway-mqtt-api/#telemetry-upload-api) in data packet. In this way Thingsboard  server will know to what real device data belongs to.

So it is up to you whether to use Thingsboard Gateway or use Thingsboard  Gateway directly. But Thingsboard Gateway doesn't support LoRaWAN protocol.

**Comment by gednz** [comment]
Hi

I think I have the same request. I have custom gateways that publish mqtt for devices connected by lora.
It would be handy to see what devices are connected via a particular gateway.
And vice versa what gateway a particular device is connected via.

Regards

**Comment by devaskim** [comment]
There already is information about what devices the gateway firstly connected to server. See *Relation* page of gateway device.
Also TB gateway has a set of RPCs to list devices per specific connector

**Comment by debacs83** [comment]
@devaskim Thank you for your reply. 
More than one year back I tried to use TB GW and installed it. But did not work well. I will try again. 
One more thing, if there are more than one GWs, is it possible to distinguish GWs? 

<html><body>
<pre class="highlight"><code>
Topic: v1/gateway-1/connect 
Message: {"device":"Device A"}
<br>
Topic: v1/gateway-2/connect 
Message: {"device":"Device B"}
</code></pre>
</body>
</html>

BTW, is it possible to register multiple devices at a time in csv file, instead of connecting them one each in user interface? 
When the number of devices are many it would be convenient. 

@gednz 
What I am thinking as a possible solution is, linking 'gw_type', 'gw_id', 'device_id' al-together and register it to the ThingsBoard. Such as, 'gw_type1_gw_x1_device_a1' to track which device is connected to which gateway (id) and what type of gateway it is (if there are more than one). 

@devaskim, @gednz 
Please let me know what do you think the above idea. And if you can foresee any possible problem and if there is any solution for that.

Regards

**Comment by devaskim** [comment]
Each TB device (gateway is sub type of device) has its own unique access token. To connect to server gateway/device uses this token, thus the server can distinguish gateways/devices.

You don't need to manually create devices that will be connected via gateway. Every time when gateway send device's telemetry/attributes, server checks if this device exists in database, if not the server will add it automatically. By the way, `connect` and disconnect` topic are optional and are used to more exact control of [online/offline device status](https://thingsboard.io/docs/user-guide/device-connectivity-status/). So you could only push data to `telemetry` and `attributes` topics and magic will happen)

**Comment by debacs83** [comment]
Thank you for the detail explanation. 

Would like to confirm one thing. Regarding TB IoT GW not supporting LoRaWAN GW.

In my case, the system configuration is as follows:
[device] -> [LoRaWAN-GW] -> [AWS IoT Core for LoRaWAN] -> [AWS Lambda] -> [Thingsboard (in EC2)]

In Lambda I will convert the JSON data received from gateways, including device-payload and send that to Thingsboard in TB compatible JSON format. 

In that case, is that matter if the gateway is LoRaWAN or Private LoRa? Because for TB it will look same JSON format. 

Thanks.

**Comment by devaskim** [comment]
In case of MQTT gateway API Two things that matter are JSON and [this data structure](https://thingsboard.io/docs/reference/gateway-mqtt-api/#telemetry-upload-api)

**Comment by gednz** [comment]
> There already is information about what devices the gateway firstly connected to server. See _Relation_ page of gateway device. Also TB gateway has a set of RPCs to list devices per specific connector

That doesn't seem to work for me. 
I suspect these relationship entries only get added if the gateway creates the device. Manually added relations are type `contains` and `manages`, but I see some that show type `created` when they reference a device-gateway relationship where the gateway created the device.

I manually add all my devices as I flash them, then assign them to customers.

my work around is that my gateways publish a JSON attribute of their connected device names,
and my devices publish an attribute of their gateway Name.

It worries me that if a device started spamming TB via a gateway, I would struggle to find how/where it is connecting

**Comment by debacs83** [comment]
@devaskim Thanks for all the helps. 

Regards

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by ozanerturk** [comment]
Solution is using thingsboard api to retrieve the gateway info, then same API and lastConnectedGateway field can be used to find out the gateway

GET
[/api/device/info/{deviceId}] Get Device Info (getDeviceInfoById)

![image](https://github.com/thingsboard/thingsboard/assets/15703627/763bcacb-962e-46b8-ac79-b8e4a09859a1)

![image](https://github.com/thingsboard/thingsboard/assets/15703627/eb57e99a-6cff-4cb9-81d4-06430b9705de)
