### ISSUE TITLE
Not able to change background color/image dashboard when i have multiple dahsboard states

### ISSUE THREAD

**Issue by mitchellvanrijkom** [thingsboard/thingsboard#760]
When creating a new dashboard i can change background color/image settings. 
If i create multiple dashboard states these options disappear. 
Is this a bug or desired behavior?

Any help is much appreciated!

**Comment by enviroeye** [comment]
Did you ever figure out how to change the b/g color of the other states?

**Comment by vparomskiy** [comment]
Dashboard edit -> manage layouts -> main -> "Background color" - set requred value.
You can set a different color for different dashboard states.

**Comment by Shivaratn** [comment]
@vparomskiy  inside Dashboard edit i couldn't see manage layouts option. Is this the issue with respect to community edition of thingsboard?

**Comment by volodymyr-babak** [comment]
It's available in both editions:
![image](https://user-images.githubusercontent.com/3466101/153002730-9dabe915-119a-4f74-8718-412209acfddd.png)
