### ISSUE TITLE
[Question] How can I filter telemetries by topic in a dashboard?

### ISSUE THREAD

**Issue by hsanderr** [thingsboard/thingsboard#7603]
**Component**

 * Generic

**Description**
I would like to know if there is a way to filter incoming telemetries by topic in a dashboard. We have a gateway collecting data from various sensors and I would like the gateway to send all the data to the same device on ThingsBoard with different topics for each sensor and then, in the dashboard, filter the telemetries by topic (e.g., in widget A, I want to show variables from the topic gateway/sensor1 and in widget B, I want to show variables from the topic gateway/sensor2). I tried to add a filter, but the only filter types are "Attribute", "Entity field" and "Timeseries".

**Environment**

 * ThingsBoard: 3.4.1

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
