### ISSUE TITLE
Slow Database performance when switching from local PostgresSQL to AWS RDS

### ISSUE THREAD

**Issue by sferguson-ISI** [thingsboard/thingsboard#7604]
* Database Issue

**Description**
Switched over from a windows-based thingsboard version to a linux-based server running on an EC2 instance.  Tested with a locally installed DB first, and performance is good. When switching over to RDS however it takes minutes to load a dashboard that shows a list of about 200+ devices whereas before it didn't have this issue.  I tried the same remote AWS RDS database on the Windows machine and have no issue.   Any ideas what could be causing the slow down? Bandwidth restriction maybe?

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard: 3.3.2
 * Browser: Chrome 106.0.5249.119

**Comment by YevhenBondarenko** [comment]
Hi @sferguson-ISI,
definitely problem related to the db indexes, plz check for example device table `\d device`, if indexes are absent I can send you list of queries for re-creating all indexes. 

Plz write your TB version: 3.3.2 CE or PE.

Now we are investigating this issue and for helping us, plz provide us with the postgres versions (from/to), and commands which you used for switching.

**Comment by sferguson-ISI** [comment]
H3llo @YevhenBondarenko I figured out the issue, it was related to the fact that I had my EC2 instance in a different availability zone than my RDS instance.  As long as there in the same zone then the lag isn't as bad.
