### ISSUE TITLE
Bulk device provision by API

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7608]
**Component**

 * Generic

**Description**
Bulk device provisioning through API 

**Environment**

 * OS:  Linux Ubuntu 20.04 
 * ThingsBoard: 3.4.1
 * Browser: Mozilla, Google Chrome
 
I know bulk device provisioning is possible in Thingsboard with csv file by UI. 
I also tested sending telemetry data with Thingsboard provided HTTP(S) API with 'curl'. 

I would like to know if bulk provisioning by (csv file) is possible through API.  
If not, then is there any other way to do that - some way around. 

Such as, using loop through the csv file and assigning values to the POST command (curl)?

curl -v -X POST --data "{"temperature":42,"humidity":73}" http://$THINGSBOARD_HOST_NAME/api/v1/$ACCESS_TOKEN/telemetry --header "Content-Type:application/json"

with the following:

curl -v -X POST --data "{"${attribute_1}":${val_1},"{$attribute_2}":${val_2}}" http://$THINGSBOARD_HOST_NAME/api/v1/${access_token}/telemetry --header "Content-Type:application/json"

Thanks

**Comment by ViacheslavKlimov** [comment]
Hi @debacs83,
REST API for bulk import is available.

You can make a POST request to `/api/device/bulk_import` (see `/swagger-ui/#/device-controller/processDevicesBulkImportUsingPOST`). It is actually where front-end makes request to on bulk provisioning.

Request body example:
```
{
  "file": "NAME,TYPE,ACCESS_TOKEN,SERVER_ATTRIBUTE\ndevice1,default,12341325,attr1Value\n", // actual csv payload
  "mapping": {
    "columns": [
      {
        "type": "NAME"
      },
      {
        "type": "TYPE"
      },
      {
        "type": "ACCESS_TOKEN"
      },
      {
        "type": "SERVER_ATTRIBUTE",
        "key": "attr1"
      }
    ],
    "delimiter": ",",
    "header": true, // whether the first row contains columns names
    "update": true 
  }
}
```

**Comment by debacs83** [comment]
Hi @ViacheslavKlimov 

Thank you for your reply with example. I haven't used swagger before or bulk import through API before. So after reading the related documents, I may come back to confirm a few things. 

I am actually using AWS based system with ThingsBoard (TB) installed in an EC2 instance. Would like to register the devices to the TB through csv file, with Access_Tokens. Telemetry values will be send to the registered devices as it comes from the devices with regular intervals. 

Thanks

**Comment by debacs83** [comment]
My previous purpose was solved by registering multiple devices with their corresponding Access Tokens by importing CSV file in the Thingsboard UI. It worked fine. 
Telemetry values are sent through HTTP(S) POST with Access Token (which is known at that time) included dynamically to the URL. 

https://demo.thingsboard.io/swagger-ui/#/device-controller/assignDeviceToPublicCustomerUsingPOST

In the above URL there are various examples of API POST/GET/DELETE etc. So instead of using Thingsboard browser based UI, by using these APIs I can post data including Access Token to Thingsboard? Sorry, if I am grossly misunderstanding the usage of these APIs. 

There are many 'try it out' examples. But as the server is 'https://demo.thingsboard.io.443' it is naturally not reaching Thingsboard where I am hosting my devices. Can try the APIs from Linux command line as well? Or say, 
a page build with PHP/Javascript etc. and inserting the corresponding values and POST it to the Thingsboard or say upload a CSV file with the values for multiple devices? 

Sorry if my question is unclear. If so please tell me. I will try to clarify.

**Comment by debacs83** [comment]
@ViacheslavKlimov 
I have tried like this with CURL for testing.  Seems I have to add 'X-authorization' with JWT Token to register the devices. 
Can I add the csv file as I wrote below? Can I go without Server Attribute and Key? Could not understand their purpose. 

-------
    curl -X 'POST' --insecure \      
      'https://my_awsEC2_IPaddress.us-west-2.compute.amazonaws.com:8080/api/device/bulk_import' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "file": "test.csv",  // <-- csv file containing the information to register devices to TB
      "columns": [
          {
            "type": "NAME"
          },
          {
            "type": "TYPE"
          },
         {
           "type": "ACCESS_TOKEN"
         },
       ],
       "delimiter": "string",   // also used "delimiter": ","   as you have given in the example. 
       "header": true,
       "update": true
       }
    }'
----------------------

-- test csv file. File name is 'test.csv' ---

     NAME,TYPE, ACCESS_TOKEN
     aaaa796,datatype,aaaa796

**Comment by ViacheslavKlimov** [comment]
Hi @debacs83. 
The structure of the request should be a little different.
For `file` you have to submit not the name of the file, but the CSV content.
Also, `columns`, `delimiter` and other you should place inside the `mapping` object of the request; see the structure:
![image](https://user-images.githubusercontent.com/56742475/224015082-c36b0026-dc0d-4012-b1b0-78186959319e.png)

So, for you the request would look like:
```
{
  "file": "NAME,TYPE,ACCESS_TOKEN\n aaaa796,datatype,aaaa796",
  "mapping": {
    "columns": [
      {
        "type": "NAME"
      },
      {
        "type": "TYPE"
      },
      {
        "type": "ACCESS_TOKEN"
      }
    ],
    "delimiter": ",",
    "header": true,
    "update": true
  }
}
```

**Comment by ViacheslavKlimov** [comment]
Yes, you need to provide access token when making the request.

It is possible to do it with curl, but you'd better use Swagger:
if you are running Thingsboard locally, you would find Swagger on http://localhost:8080/swagger-ui/#/device-controller/processDevicesBulkImportUsingPOST

**Comment by debacs83** [comment]
Thank you so much! Yes, I am running Thingsboard locally. So I tried with Swagger locally. 
Could register device with swagger! 

Best regards

**Comment by debacs83** [comment]
Could also register devices from AWS Lambda (python). 

Thank you.
