### ISSUE TITLE
[Question] Alias Filter Not Update Data?

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#7610]
I just try create filter for Entity Alias like this, and use this on widget data source configuration
![image](https://user-images.githubusercontent.com/12267053/201622583-6423bccd-a19b-403c-84ee-7ad39017f5d8.png)

use it here 
![image](https://user-images.githubusercontent.com/12267053/201624912-5cfbcfea-fe9d-47da-a0c5-aef153eb18dd.png)

I want entity table only show entities that _status_!=available. 
It works at first load, table show all entities that _status_ not available,
and works when entity _status_ is not available (eg 'connected') turn to 'available' then it will **disappear from table**.

But when entity key _status_ from 'available' telemetry turn to 'connected', what I expect is this entity immediately **appear on table**, but nothing new row appear. It will appear later after about 30s (not sure exactly)

Is there any way to make it show data immediately when _status_ just change to !=available ?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
