### ISSUE TITLE
Map ToolTip, X button closes the entire dashboard [Bug] 

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/thingsboard#7616]
We recently updated to latest version of dashboard (Version 3), we were using version 2 before.

This issues started with the latest version. Whenever you click the exit (x button) of the tooltip, this causes the entire dashboard to quit and page redirects to the home page of the ThingsBoard.

In version 2, this just closes the tooltip (which is the expected action).

![image](https://user-images.githubusercontent.com/108116747/201867901-b9f8ff55-f0db-4d76-8f25-8837bf699adf.png)

**Comment by vvlladd28** [comment]
Hi @rajSilikon,
This issue will be fixed in the next release TB 3.4.2.
Fixed https://github.com/thingsboard/thingsboard/pull/7181.
