### ISSUE TITLE
[Question] Putting values in the metadata with IoT gateway

### ISSUE THREAD

**Issue by Lenteguppie** [thingsboard/thingsboard#7620]
**Component**

 * IoT gateway

**Description**
Hello Thingsboard, 

At this moment I am working with a custom REST converter for the IoT gateway, but as far as I know, I am not able to send metadata values. Maybe I missed something or does the IoT gateway only support sending telemetry and attributes?

Thank you in advance.

**Environment**

 * OS:  POP_OS 22.04
 * ThingsBoard: CE version 3.4.1
 * Browser: Google chrome
 * Docker images:
    *  thingsboard/tb-postgres
    *  thingsboard/tb-gateway

**Comment by devaskim** [comment]
Both TB server API and TB gateway which is using that API as well supports only telemetry and attributes.
What did you mean by metadata?
