### ISSUE TITLE
[Question] Input widged with multiple lines of text

### ISSUE THREAD

**Issue by Micteu127** [thingsboard/thingsboard#7622]
**Update shared string attribute**

 * UI

**Description**
I use a string attribute to allow the user to define information about a device. Is it possible to display multiple lines of text here?
![grafik](https://user-images.githubusercontent.com/101638082/201949394-37993d3e-4de6-4eae-ab74-1a244a6563b6.png)

**Comment by JimmyPedersen** [comment]
Any work done on this?
I really need it for entering barcode code in TSPL/ZPL

**Comment by JimmyPedersen** [comment]
In the hopes that it helps others, here's how I solved it.
Please note I'm NOT a web developer so this solution is probably ugly, but it seems to work

Save the "Update string timeseries" widget from the "Input widgets" bundle as a new widget
Replace the HTML code with the following:
`<div tb-toast toastTarget="{{ toastTargetId }}" style="width: 100%; height: 100%;">
    <form *ngIf="attributeUpdateFormGroup"
          class="attribute-update-form"
          [formGroup]="attributeUpdateFormGroup"
          (ngSubmit)="updateAttribute()">
        <div style="padding: 0 8px; margin: auto 0;">
            <div class="attribute-update-form__grid" [fxShow]="entityDetected && isValidParameter && dataKeyDetected">
                <div class="grid__element">
                    <mat-form-field class="mat-block" style="width: 100%;"
                                    floatLabel="{{settings.showLabel ? 'auto' : 'always'}}"
                                    [hideRequiredMarker]="!settings.showLabel">
                        <mat-label>{{ settings.showLabel ? labelValue : '' }}</mat-label>
                        <input matInput
                               formControlName="currentValue"
                               required
                               (focus)="isFocused = true"
                               (blur)="changeFocus()"
                               maxlength="{{settings.maxLength}}"
                               minlength="{{settings.minLength}}"/>
                        <mat-error *ngIf="attributeUpdateFormGroup.get('currentValue').hasError('required')">
                            {{requiredErrorMessage}}
                        </mat-error>
                    </mat-form-field>    
                </div>
    
                <div class="grid__element">
                    <button mat-icon-button class="applyChanges"
                               type="submit"
                               [disabled]="originalValue === attributeUpdateFormGroup.get('currentValue').value || attributeUpdateFormGroup.invalid || !attributeUpdateFormGroup.dirty"
                               matTooltip="{{ 'widgets.input-widgets.update-timeseries' | translate }}"
                               matTooltipPosition="above">
                        <mat-icon>check</mat-icon>
                    </button>
                    <button mat-icon-button class="discardChanges"
                               type="button"
                               [disabled]="originalValue === attributeUpdateFormGroup.get('currentValue').value"
                               (click)="attributeUpdateFormGroup.get('currentValue').patchValue(originalValue); isFocused = false"
                               matTooltip="{{ 'widgets.input-widgets.discard-changes' | translate }}"
                               matTooltipPosition="above">
                        <mat-icon>close</mat-icon>
                    </button>
                </div>
            </div>
    
            <div style="text-align: center; font-size: 18px; color: #a0a0a0;" [fxHide]="entityDetected">
                {{ 'widgets.input-widgets.no-entity-selected' | translate }}
            </div>
            <div style="text-align: center; font-size: 18px; color: #a0a0a0;" [fxShow]="entityDetected && !dataKeyDetected">
                {{ 'widgets.input-widgets.no-timeseries-selected' | translate }}
            </div>
            <div style="text-align: center; font-size: 18px; color: #a0a0a0;" [fxShow]="entityDetected && !isValidParameter">
                {{ 'widgets.input-widgets.attribute-not-allowed' | translate }}
            </div>
        </div>
    </form>
</div>`

Replace the JS code with the following:
`let $scope;
let settings;
let utils;
let translate;
let http;

self.onInit = function() {
    self.ctx.ngZone.run(function() {
       init(); 
       self.ctx.detectChanges(true);
    });
};


function init() {

    $scope = self.ctx.$scope;
    utils = $scope.$injector.get(self.ctx.servicesMap.get('utils'));
    translate = $scope.$injector.get(self.ctx.servicesMap.get('translate'));
    http = $scope.$injector.get(self.ctx.servicesMap.get('http'));
    $scope.toastTargetId = 'input-widget' + utils.guid();
    settings = utils.deepClone(self.ctx.settings) || {};
    settings.showLabel = utils.defaultValue(settings.showLabel, true);
    settings.showResultMessage = utils.defaultValue(settings.showResultMessage, true);
    $scope.settings = settings;
    $scope.isValidParameter = true;
    $scope.dataKeyDetected = false;
    $scope.requiredErrorMessage = utils.customTranslation(settings.requiredErrorMessage, settings.requiredErrorMessage) || translate.instant('widgets.input-widgets.entity-timeseries-required');
    $scope.labelValue = utils.customTranslation(settings.labelValue, settings.labelValue) || translate.instant('widgets.input-widgets.value');

    $scope.attributeUpdateFormGroup = $scope.fb.group(
        {currentValue: [undefined, [$scope.validators.required,
                                    $scope.validators.minLength(settings.minLength),
                                    $scope.validators.maxLength(settings.maxLength)]]}
    );

    if (self.ctx.datasources && self.ctx.datasources.length) {
        var datasource = self.ctx.datasources[0];
        if (datasource.type === 'entity') {
            if (datasource.entityType && datasource.entityId) {
                $scope.entityName = datasource.entityName;
                if (settings.widgetTitle && settings.widgetTitle.length) {
                    $scope.titleTemplate = utils.customTranslation(settings.widgetTitle, settings.widgetTitle);
                } else {
                    $scope.titleTemplate = self.ctx.widgetConfig.title;
                }

                $scope.entityDetected = true;
            }
        }
        if (datasource.dataKeys.length) {
            if (datasource.dataKeys[0].type !== "timeseries") {
                $scope.isValidParameter = false;
            } else {
                $scope.currentKey = datasource.dataKeys[0].name;
                $scope.dataKeyType = datasource.dataKeys[0].type;
                $scope.dataKeyDetected = true;
            }
        }
    }

    self.ctx.widgetTitle = utils.createLabelFromDatasource(self.ctx.datasources[0], $scope.titleTemplate);

    $scope.updateAttribute = function () {
        $scope.isFocused = false;
        if ($scope.entityDetected) {
            var datasource = self.ctx.datasources[0];

            let observable = saveEntityTimeseries(
                datasource.entityType,
                datasource.entityId,
                [
                    {
                        key: $scope.currentKey,
                        value: $scope.attributeUpdateFormGroup.get('currentValue').value
                    }
                ]
            );
            if (observable) {
                observable.subscribe(
                    function success() {
                        $scope.originalValue = $scope.attributeUpdateFormGroup.get('currentValue').value;
                        if (settings.showResultMessage) {
                            $scope.showSuccessToast(translate.instant('widgets.input-widgets.update-successful'), 1000, 'bottom', 'left', $scope.toastTargetId);
                        }
                    },
                    function fail() {
                        if (settings.showResultMessage) {
                            $scope.showErrorToast(translate.instant('widgets.input-widgets.update-failed'), 'bottom', 'left', $scope.toastTargetId);
                        }
                    }
                );
            }
        }
    };

    $scope.changeFocus = function () {
        if ($scope.attributeUpdateFormGroup.get('currentValue').value === $scope.originalValue) {
            $scope.isFocused = false;
        }
    }

    function saveEntityTimeseries(entityType, entityId, telemetries) {
        var telemetriesData = {};
        for (var a = 0; a < telemetries.length; a++) {
            if (typeof telemetries[a].value !== 'undefined' && telemetries[a].value !== null) {
                telemetriesData[telemetries[a].key] = telemetries[a].value;
            }
        }
        if (Object.keys(telemetriesData).length) {
            var url = '/api/plugins/telemetry/' + entityType + '/' + entityId + '/timeseries/scope';
            return http.post(url, telemetriesData);
        }
        return null;
    }
}

self.onDataUpdated = function() {

    try {
        if ($scope.dataKeyDetected) {
            if (!$scope.isFocused) {
                $scope.originalValue = self.ctx.data[0].data[0][1];
                $scope.attributeUpdateFormGroup.get('currentValue').patchValue($scope.originalValue);
                self.ctx.detectChanges();
            }
        }
    } catch (e) {
        console.log(e);
    }
}

self.onResize = function() {

}

self.typeParameters = function() {
    return {
        maxDatasources: 1,
        maxDataKeys: 1,
        singleEntity: true
    }
}

self.onDestroy = function() {

}
`

Hit save.

Please note that the preview doesn't look like the end result.

If someone is willing to improve on this feel free to post it here.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
