### ISSUE TITLE
[Question] Mark and label data points

### ISSUE THREAD

**Issue by Micteu127** [thingsboard/thingsboard#7623]
**Component**

 * UI

**Description**
Is there a way to mark and label data points of a timeline chart? It would be nice if certain points could be labeled here and this would also be visible in the charts as a note. For example, when you move the mouse over them.
Is there such a feature in the PE version?
![grafik](https://user-images.githubusercontent.com/101638082/201959448-fa5ab2b3-59e2-49bb-96fe-406f15ddc9ca.png)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
