### ISSUE TITLE
[Question] Documentation or list of style attributes

### ISSUE THREAD

**Issue by Micteu127** [thingsboard/thingsboard#7624]
**Component**
Entity table widget

-  UI

**Description**

I am trying to change row properties of the entity table. Mainly I want to save space and determine the size of the lines as well as the text size and fonts. Using row style function the height can be changed. Is there a more detailed description which key/value style attributes can be modified here? 
The help only returns two simple examples.

---
I found this entry and can also use it partially. Is there more information on how and what can be changed to remain compatible for the future?

![https://github.com/thingsboard/thingsboard/issues/4721](url)

**Comment by devaskim** [comment]
To tune table styles I override (some of) them in _Widget style_ section of widget's _Settings_ tab.
For example, to reduce height of header row, color it and make letters bold
```
table {
  text-align: center !important;
  width: 100%;
}
.tb-widget-actions-absolute {
    top: -5px !important;
    margin-right: 20px !important;
}
.mat-header-row {
    height: 35px !important;
}
.mat-header-cell {
  text-align: center;
}
.mat-sort-header-container {
    display: flex !important;
    justify-content: center !important;
}
.mat-table .mat-header-cell {
    color: rgba(243, 102, 33, 1) !important;
    background-color: #FCF3EC !important;
}
.mat-sort-header-content {
    font-size: 13px;
}
```
