### ISSUE TITLE
[Bug] Custom marker image on Map Widget not always loading, console shows error

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7626]
**Describe the bug**
I am using the map widget to show the location of 18 devices.
I added a custom function for the markers to show an image instead of the default pin icon. The image is selected based on changes in the telemetry data, see function code below:

```
// FUNCTIONS
function rotateSquareImage(imageBase64, rotation) {

    let img = new Image();
    img.src = imageBase64;

    let canvas = document.createElement("canvas");
    canvas.width = img.width;
    canvas.height = img.height;

    // Translate origin to center, rotate at origin, move back origin and draw
    let canvasCtx = canvas.getContext("2d");
    canvasCtx.translate(Math.floor(img.width / 2), Math.floor(img.height / 2));
    canvasCtx.rotate(rotation * (Math.PI / 180));
    canvasCtx.drawImage(img, -Math.floor(img.width / 2), -Math.floor(img.width / 2));

    return canvas.toDataURL("image/png", 1);
}

// Default image
var res = {
    url: images[0],
    size: 40
}

// Add rotation
var rotation = dsData[dsIndex]['rotation']
var elevation = dsData[dsIndex]['deltaElevation'] * -1
var alarm = dsData[dsIndex]['alarmHigh']
var warning = dsData[dsIndex]['warningHigh']
//console.log(rotation, elevation, alarm, warning)

if (rotation && elevation && alarm && warning) {
    console.log('at rotation')

    if (elevation >= alarm) {
        res.url = rotateSquareImage(images[3], rotation);
    }
    else if (elevation >= warning && elevation < alarm) {
        res.url = rotateSquareImage(images[2], rotation);
    }
    else {
        res.url = rotateSquareImage(images[1], rotation);
    }
}

return res;
```

This work sometimes, but other times I get this error in the console `polyfills.6d09cdca7f8342e3da77.js` and the marker image is not shown, but instead the default pin icon. It seems that it get stucks loading and then throw the error.

```
Event {isTrusted: true, type: 'error', target: img, currentTarget: null, eventPhase: 0, …}
isTrusted: true
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
path: (5) [img, body.tb-default, html, document, Window]
returnValue: true
srcElement: img
target: img
timeStamp: 3714.800000011921
type: "error"
[[Prototype]]: Event
```

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: macOS
* Browser: Chrome
* Version: 107.0.5304.110 (Official Build) (x86_64)

**To Reproduce**
1. Create many devices ( > 20) and show them in the Map Widget.
2. Add a custom marker function to change the default marker icon to an image based on telemetry.
3. Refresh webpage until error appear, specially when loading is slow.
4. See error in the console as an `Uncaught Event`.

**Expected behavior**
I would expect the marker icon to be always the default image that I defined in my custom marker function.

**Screenshots**
Default pin marker in widget
![image](https://user-images.githubusercontent.com/27728926/202047315-b370d128-ec25-4b84-a2f5-7f6dcc3a36c6.png)

My image marker based on custom function
![image](https://user-images.githubusercontent.com/27728926/202047436-8bf02c38-6013-4464-b0a2-92f8641b61ad.png)

**Comment by Civilduino** [comment]
**Updated the comment above with correct marker image function!**
I was too tired when I created the post and copied the wrong function code :/ 

After doing more investigation, it seems that the rotation function is the one causing the error. If I remove the rotation feature, then I don't see the widget crashing, at least not yet.
Why would the rotation function result in this error?

**Comment by Civilduino** [comment]
@devaskim do you have any idea on this? I believe that the error is cause because other tasks are asynchronous, finishing before the rotation. How can one make this work synchronous?

**Comment by devaskim** [comment]
I guess it is canvas overhead)))
[Only debug mode](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#running-ui-container-in-hot-redeploy-mode) will help you to see real stack trace but you need to run community edition. It is not a problem to deploy locally Docker instance but require some time.

**Comment by Civilduino** [comment]
Where do you activate the debug mode for the map widget?

**Comment by devaskim** [comment]
You cannot activate debug mode neither for single widget, nor for whole ALL.
I meant to locally build and run only UI container. In such mode browser's Devtool will shot more precise information where the error occurred. Before build you need to set valid TB domain [here](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/proxy.conf.js#L16-L17)

**Comment by Civilduino** [comment]
It is some problem with the `canvas` tag, but I found a better solution that seems to work! thanks to this [post](https://stackoverflow.com/questions/27443978/how-can-i-change-color-of-an-svg-img-in-base64-format). I found [this](https://stackoverflow.com/questions/22252472/how-to-change-the-color-of-an-svg-element?page=1&tab=scoredesc#tab-top) for the color too, but I haven't been able to make the color work. I am not sure about which [attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) is the correct one for the color.

Here is the function if you want to play with rotating your markers ;)
```
// color = HEX format
//function imageColorRotate(svgBase64, color, rotation) {
function imageColorRotate(svgBase64, rotation) {

    let img = new Image()
    img.src = svgBase64

    // Strip "data:image/svg+xml;base64," to get encoded SVG
    let encoded = svgBase64.substring(26);
    // Decode Base64
    let decoded = atob(encoded);

    // Create an HTML element from decoded SVG
    let wrapper = document.createElement('div');
    wrapper.innerHTML = decoded;

    let newSvg = wrapper.childNodes[1];
    // Set up new color
    //newSvg.setAttribute("fill", color);
    // Rotate
    let rotate = "rotate(" + Math.floor(rotation) + Math.floor(img.width / 2) + Math.floor(img.height / 2) + ")"
    newSvg.setAttribute("transform", rotate);

    let newSvgBase64 = "data:image/svg+xml;base64," + btoa(wrapper.innerHTML)
    wrapper.remove()

    return newSvgBase64
}
```
