### ISSUE TITLE
Claiming using device-side key scenario

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7627]
**Component**

 * Generic
![image](https://user-images.githubusercontent.com/19941827/202077672-8baa4c3c-86a2-4603-a73b-e1da11fff352.png)

**Description**
Device expirationTime usage;
1. Do you need to save the expiration time on the server side?
2. Do you need to send the expirationTime to the server?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
