### ISSUE TITLE
[Bug] svg in widget not displayed

### ISSUE THREAD

**Issue by massamino** [thingsboard/thingsboard#7630]
**Describe the bug**
SVG in widget does not update.
SVG layout updates in devtools in chrome and firefox, but the visual representation is empty for the parts updated in the web interface.

**Your Server Environment**

* own setup
  * local
  * PE 3.3.4
  * Ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Win 10
* Browser: Firefox 107, Chrome 107, Edge 107

**To Reproduce**

(widget file included: [demo_svg_bug.txt](https://github.com/thingsboard/thingsboard/files/10020348/demo_svg_bug.txt))

1. Create new widget (latest value)
2. Copy file contents in the right window (javascript, schema, data key... in additional content)
3. Click run
4. Setup widget and add a second random element.
5. Go to advanced in each and set one to 'battery sensor' and the other to 'electrolyte sensor'
6. Save
7. Open dev tools of the browser
8. Goto inspect window and use the selector to click in the widgets container.
9. The svg element is visible in the DOM and you can see the data updating (Screenshot 1)
10. The widget stays empty
11. When I add a space in front of </svg> or something else (Screenshot 2), the svg is visible (Screenshot 3), but doesn't update anymore of course.

**Expected behavior**
Widget representing the SVG element and updates.
Same code with just html elements does work.

**Screenshots**
![TB-1](https://user-images.githubusercontent.com/52240756/202143726-551c192e-07da-47ff-9b44-91bf2b27d8ee.jpg)

![TB-2](https://user-images.githubusercontent.com/52240756/202143734-32a8ca29-60f7-4936-9418-cdcf549301f7.jpg)

![TB-3](https://user-images.githubusercontent.com/52240756/202143735-e9d9171d-6924-4112-8514-92c85a12c3bb.jpg)

**Additional context**
[TB-javascript.txt](https://github.com/thingsboard/thingsboard/files/10020106/TB-javascript.txt)
[TB-Settings-Schema.txt](https://github.com/thingsboard/thingsboard/files/10020107/TB-Settings-Schema.txt)
[TB-Data-key-settings-schema.txt](https://github.com/thingsboard/thingsboard/files/10020110/TB-Data-key-settings-schema.txt)
[demo_svg_bug.txt](https://github.com/thingsboard/thingsboard/files/10020348/demo_svg_bug.txt)

**Comment by devaskim** [comment]
Try to call `self.ctx.detectChanges()` after all data or/and DOM manipulation.

**Comment by massamino** [comment]
I tried adding the ```self.ctx.detectChanges()``` , but that doesn't change a thing for me.
I moved the svg main tag to the HTML window as well. In the beginning it was done with almost everything in the HTML part, only the updating parts were in JS.

[widget_svg_bug](https://github.com/thingsboard/thingsboard/files/10024937/demo_svg_bug.txt)

**Comment by devaskim** [comment]
In my practise of developing TB widget I try to avoid DOM manipulation from JS.
Instead I am using powerful  built-in Angular directives in HTML section such as `ngFor` for loops, `ngIf` and `ngSwitch` for branching and `ngIf` to show/hide HTML elements. With this approach I init my data container in `onInit` or `onDataUpdated` callbacks and call `self.ctx.detectChanges()` at the end. Then Angular magic happens with HTML template.

**Comment by massamino** [comment]
In TB 2.2 I did it with $scope as well, but porting that widget (adding the self.ctx.detectChanges() instead of the self.ctx.$scope.$digest() command) didn't seem to work out well. I didn't have to change anything in ondataupdated in v2.2. I guess I have to add the data in ondataupdate from V3.3 on.
I'll take a look at the angular directives.
