### ISSUE TITLE
[Bug] Mqtt Node is unavailable in thingsboard cluster environment

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#7633]
### **Describe the bug**
When MQTT rule nodes are used in thingsboard cluster environment, the following errors are reported in the debugging logs of nodes in most services:
` o.t.mqtt.ChannelClosedException: Channel is closed!
	at o.t.mqtt.MqttClientImpl.sendAndFlushPacket(MqttClientImpl.java:453)
	at o.t.mqtt.MqttClientImpl.publish(MqttClientImpl.java:381)
	at o.t.mqtt.MqttClientImpl.publish(MqttClientImpl.java:346)
	at o.t.rule.engine.mqtt.TbMqttNode.onMsg(TbMqttNode.java:87)`

As we all know, when using an MQTT node to connect to an external Borker, only one MQTT connection can be established with the same credentials. Therefore, in the thingsboard cluster environment, you cannot use the same credentials to create an MQTT connection in each node of the cluster. As a result, the MQTT rule node in all nodes except one fails to create a connection, and an error is reported on the onMsg: "Channel closed!"

I think the cluster tool class should be used to keep the MQTT rule node single in the cluster.

@ikulikov Beg you to repair

**Comment by ban2derlog** [comment]
hi,
fix for this was added in 3.5 already.
https://github.com/thingsboard/thingsboard/pull/8414
![image](https://github.com/thingsboard/thingsboard/assets/33271053/280591e6-a21b-4402-bec5-0326cec8e08a)
this will set that only one node in cluster will use this.
