### ISSUE TITLE
Use ${entityDescription} in Dashboard State[Feature Request]

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/thingsboard#7635]
We are able to use ${entityName} to customize the dashboard state name.

![image](https://user-images.githubusercontent.com/108116747/202412191-a6e11c21-2a74-42dd-8517-f65adc966dd0.png)

![image](https://user-images.githubusercontent.com/108116747/202412273-db4efba3-f159-402c-af11-a1658150b5bf.png)

Is there anyway to use ${entityDescription} instead?
![image](https://user-images.githubusercontent.com/108116747/202412496-3e8e0e18-5f48-40a4-906d-8047c780406d.png)

![image](https://user-images.githubusercontent.com/108116747/202412670-b3f06e7d-051f-4245-8cda-720219dfcfa9.png)

it seams that only {entityName} works.

**Comment by devaskim** [comment]
Only `entityName` and `entityLabel` are applicable for dashbaord states.
