### ISSUE TITLE
[Bug] Custom Dashboard CSS not applied when dashboard is full-screen

### ISSUE THREAD

**Issue by dm9de** [thingsboard/thingsboard#7642]
**Describe the bug**
When I add custom dashboard-wide CSS in via the "advanced settings" section of the dashboard 'settings' dialog (i.e. as opened via the gear icon), the CSS is applied when the dashboard is not in full screen mode, but when it is in full-screen mode, the CSS is not applied.

**Your Server Environment**
* own setup
  * 3.4.0
  * Amazon Linux

**Your Client Environment**
* OSX
* Firefox
* 106.0.5

**To Reproduce**
1. Create a new dashboard by uploading a json file with the following content:
```
{
  "title": "bug report",
  "image": null,
  "mobileHide": false,
  "mobileOrder": null,
  "configuration": {
    "description": "",
    "widgets": {
      "cfb26e30-4869-2e90-3480-f55afb51beb1": {
        "isSystemType": true,
        "bundleAlias": "cards",
        "typeAlias": "html_card",
        "type": "static",
        "title": "New widget",
        "image": null,
        "description": null,
        "sizeX": 7.5,
        "sizeY": 3,
        "config": {
          "datasources": [],
          "timewindow": {
            "realtime": {
              "timewindowMs": 60000
            }
          },
          "showTitle": false,
          "backgroundColor": "rgb(255, 255, 255)",
          "color": "rgba(0, 0, 0, 0.87)",
          "padding": "8px",
          "settings": {
            "cardHtml": "<div class='my-card'>This text should be red but isn't when dashboard is full-screen</div>",
            "cardCss": "/* None */"
          },
          "title": "New HTML Card",
          "dropShadow": true
        },
        "row": 0,
        "col": 0,
        "id": "cfb26e30-4869-2e90-3480-f55afb51beb1"
      }
    },
    "states": {
      "default": {
        "name": "bug report",
        "root": true,
        "layouts": {
          "main": {
            "widgets": {
              "cfb26e30-4869-2e90-3480-f55afb51beb1": {
                "sizeX": 7,
                "sizeY": 3,
                "row": 0,
                "col": 0
              }
            },
            "gridSettings": {
              "backgroundColor": "#eeeeee",
              "columns": 24,
              "margin": 10,
              "backgroundSizeMode": "100%",
              "autoFillHeight": false,
              "backgroundImageUrl": null,
              "mobileAutoFillHeight": false,
              "mobileRowHeight": 70
            }
          }
        }
      }
    },
    "entityAliases": {},
    "filters": {},
    "timewindow": {
      "displayValue": "",
      "hideInterval": false,
      "hideAggregation": false,
      "hideAggInterval": false,
      "hideTimezone": false,
      "selectedTab": 0,
      "realtime": {
        "realtimeType": 0,
        "interval": 1000,
        "timewindowMs": 60000,
        "quickInterval": "CURRENT_DAY"
      },
      "history": {
        "historyType": 0,
        "interval": 1000,
        "timewindowMs": 60000,
        "fixedTimewindow": {
          "startTimeMs": 1668633145785,
          "endTimeMs": 1668719545785
        },
        "quickInterval": "CURRENT_DAY"
      },
      "aggregation": {
        "type": "AVG",
        "limit": 25000
      }
    },
    "settings": {
      "stateControllerId": "entity",
      "showTitle": false,
      "showDashboardsSelect": true,
      "showEntitiesSelect": true,
      "showDashboardTimewindow": true,
      "showDashboardExport": true,
      "toolbarAlwaysOpen": true,
      "titleColor": "rgba(0,0,0,0.870588)",
      "showDashboardLogo": false,
      "dashboardLogoUrl": null,
      "hideToolbar": false,
      "showFilters": true,
      "showUpdateDashboardImage": true,
      "dashboardCss": ".my-card {\n    color: red;\n}"
    }
  },
  "externalId": null,
  "name": "bug report"
}
```

2. Open the dashboard - there should be a simple HTML card with red text saying "This text should be red but isn't when dashboard is full-screen"
3. Enter full-screen mode by clicking the "expand to full screen" button
4. The text will now be black (i.e. the `dashboardCss` style has not been applied).

**Expected behavior**
When the dashboard is in full-screen mode, the text should still be red (i.e. the styling should still be applied)

**Additional context**
I've noticed that the dashboard CSS is added as an inline style, with each selector including a class ancestor similar to:
`.tb-dashboard-page-css-d757545e-29ce-4bf9-bb3c-44c63c32c91d`

When examining the generated HTML for the dashboard in full screen mode, this class does not appear on any ancestor elements of the widget components in the dashboard. Adding this class to an ancestor element manually via my browser's developer tools applies the styling as expected.

**Comment by den1jkee** [comment]
Hi,
This looks like a bug in a platform - I had already added to our backlog a ticket for a product team (PROD-1752).
Once the product team reviews this ticket, we’ll post an update on when this fix for this bug could be delivered.
Thank you!
As a workaround, you can use a Advanced settings in Edit widget settings
Best regards,
Denys.

**Comment by Civilduino** [comment]
Spent half a day trying to figure out the problem, to realise it is a bug.
I use TB PasS 3.4.2
