### ISSUE TITLE
[Question] How to return an HTTP code different from 200 with the REST Call Reply Node

### ISSUE THREAD

**Issue by Nolat** [thingsboard/thingsboard#7647]
### **Component**
 * Rule Engine

### **Environment**
 * ThingsBoard: 3.4.1 Professional Edition

### **Description**
The documentation does not explain how to return an HTTP code different from 200, is this possible? If yes, how?
If not, is it planned?

I am using custom REST API routes to authenticate requests I make to an external API. This external API returns an HTTP code that should be returned with the REST Call Reply Node.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
