### ISSUE TITLE
Nested HTTPS POST to ThingsBoard  

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7648]
**Component**

 * Generic

**Description**
I want to send JSON data from AWS Lambda to ThingsBoard installed in AWS EC2 instance. 
I have tested it with HTTPS POST method with provided API.  I could send data without any problem. 
This is how I sent.

....
url = "https://<EC2_domain_name>:8080/api/v1/<Access_Token>/telemetry".format(access_token)
data = {
         "rssi": -98.2,
         "snr": 5.6
     }
headers = {
      'content-type': 'application/json',
 }
req = urllib.request.Request(url, json.dumps(data).encode(), headers)
.....  ....
etc.

Now, If I want to send two JSON data.  Like:
{
  header = {
         "gwId": "abcedf",
         "devId: "mnop",
         "gwLat": 38.123,
         "gwLon": 140.345
       },
  data = {
         "rssi": -98.2,
         "snr": 5.6
 }

Does ThingsBoard support nested JSON data? If yes, how to format it?

So far I only send not-nested JSON. 

Thanks

**Environment**

 * OS:  Linux Ubuntu 20.04 LTS
 * ThingsBoard: 3.4.1 (Community Edition)
 * Browser: Google Chrome, Mozilla Firefox, Edge

**Comment by devaskim** [comment]
[Use array](https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api)
```
[{
    "gwId": "abcedf",
    "devId: "mnop",
    "gwLat": 38.123,
    "gwLon": 140.345
}, {
    "rssi": -98.2,
    "snr": 5.6
}]
```

**Comment by debacs83** [comment]
@devaskim 
Thank you very much. I will try and post the result.

**Comment by debacs83** [comment]
@devaskim 
Thanks for your suggestion. I worked without problem. 

In case if any one else trying to do the same (sending from AWS Lambda python to Thingsboard), writing it here. 

..........
header = {
        "gw_id": "dfa12345",
        "dev_id": "mng234",
        "gw_lat": 38.234,
        "gw_lon": 140.123
    }
    
    data = {
        "rssi": -94.5,
        "snr": 6.9
    }
    
    send_data = [header, data]

    headers = {
        'Content-Type': 'application/json',
    }

    req = urllib.request.Request(url, json.dumps(send_data).encode(), headers)
   
   ...........

Thanks and regards
