### ISSUE TITLE
custom plugin for calculation

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#765]
i want to make plugin to calculate utilization levels.

however, documentation seems to be lacking. 

how can i do queries to internal database, and how can i customize swagger rest request url of plugin?

**Comment by mp-loki** [comment]
Plugin development guide is here:
https://thingsboard.io/docs/user-guide/contribution/extensions-development/
For database queries see the source of dao module.
For swagger not shure what is the question

**Comment by quirosaur** [comment]
https://thingsboard.io/docs/reference/rest-api/
