### ISSUE TITLE
How to fetch all attributes from a device which is related to an other device

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7650]
**Component**

 * Rule Engine

**Description**
Is there a way to fetch to a rule chain node the attribute value from all contained devices under an other device?
For example we have a deviceA that contains 2 more devices (tagA,tagB). Each of these devices has a client attribute named tagID, my goal is to fetch both tagIDs and add them to the OUT payload.

Closest i came so far is by using "related device attributes" node, but seems that it's only returns 1 of the 2 tagIDs from the contained tags under deviceA (possibly the tagID of the last contained tag into deviceA)

**Environment**

 * OS:  Windows 10
 * ThingsBoard: demo.thingsboard.org
 * Browser: Chrome

**Comment by PanGian97** [comment]
Hi, sorry for the late reply, i had some other things to test first before going back to this issue. I did what u suggested, but here is the problem, i end up with multiple messages as INPUTS (cause of duplicate to each related device).

 In my case let's say we have a car (main device)if we say this car can have multiple drivers (related devices), i want to check when a driver gets inside of the car, if there is a violation or not (if driver's tag exists as  related device to car device then no violation).
 
 So as you understand the final script decides if violation exists when a driver tag's is readed or not. The problem stand with the fact that many inputs will come to the script, so let's say we have 4 inputs and 3 are going to "no violation" and one to "violation" this creates confusion cause if violation alarm starts, the next tag that passes as "no violation" will cancel it.
 
 What i want from here is a way to combine all duplicated messages to a signle message, is there a way?  Thanks a lot!!

**Comment by liotys** [comment]
Hi,
I guess you won't be able to aggregate all duplicated messages. It's the reason that you need to maintain an array (violation array) at the level of the main device (it's the trace of the passed duplicated messages). If there is a tag in this array don't clear the alarm.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
