### ISSUE TITLE
[Question] Custom widget: set gauge value property

### ISSUE THREAD

**Issue by tecnicos-computrol** [thingsboard/thingsboard#7653]
**Component**

 * UI

**Description**
I need to edit the "Speed gauge" widget to show zero value when certain condition is met. This action should be executed in the `onDataUpdated()` function.
This widget inherits methods from the "TbAnalogueRadialGauge" class, which contains an update() method. If I'm not wrong, this would be its implementation:

```
update() {
    if (this.ctx.data.length > 0) {
      const cellData = this.ctx.data[0];
      if (cellData.data.length > 0) {
        const tvPair = cellData.data[cellData.data.length -
        1];
        const value = tvPair[1];
        if (value !== this.gauge.value) {
          this.gauge.value = value;
        }
      }
    }
  }
```

TbAnalogueRadialGauge extends TbAnalogueGauge. TbAnalogueGauge exends TbBaseGauge, where update() is implemented.

It seems to access the `this.gauge.value` property to update the gauge value. However, when I try to access this property from widget development IDE, it turns out to be undefined.

```
self.onDataUpdated = function() {
    self.ctx.gauge.update();
    console.log(self.ctx.gauge.value) // output: undefined
}
```

Does anyone have any ideas about how to access this property?

**Environment**

 * OS:  Linux Ubuntu 20.04.5 LTS
 * ThingsBoard: v3.4 (ThingsBoard Professional Edition)
 * Browser: Google Chrome, Mozilla Firefox, Edge

**Comment by devaskim** [comment]
```
    console.log(self.ctx.gauge.gauge.value)
```
