### ISSUE TITLE
[Question] Alarm auto clearing immediately

### ISSUE THREAD

**Issue by KrakenIsHere** [thingsboard/thingsboard#7654]
**Component**

Rule Engine?

**Description**
As I create an alarm within the rule engine, it gets cleared immediately, even when no node for clearing exists.

Are there other methods of clearing alarms that I'm unaware of, that might be interfering?

**Environment**
 * OS:  Win 10
 * ThingsBoard: 3.3.2PE
 * Browser: Chrome

**Comment by devaskim** [comment]
> Are there other methods of clearing alarms that I'm unaware of, that might be interfering?

Device profile

**Comment by KrakenIsHere** [comment]
> Device profile

Checked it now, and there are no "Alarm rules" on any of the "Device Profiles" on the server.
At least I know that's a thing now :D

**Comment by KrakenIsHere** [comment]
The issue still happens, but the Device Profile alarms seem to work just fine, so I'll be using those instead of the ones in the Rule chain
