### ISSUE TITLE
[Feature Request] Entities table

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#7656]
If you go to another state of the dashboard and then return it back, the parameters (sorting, search ..) of the table widget are not saved. Can it somehow be implemented so that the table widget retains its state.

![image](https://user-images.githubusercontent.com/87794982/202855844-8e4c2f8d-fe51-4083-8321-2ca2ed04f157.png)
before

![image](https://user-images.githubusercontent.com/87794982/202855893-48379c14-c345-4f56-ad22-7e557f18708e.png)
going to new state

![image](https://user-images.githubusercontent.com/87794982/202855948-10c47365-1a39-4217-a87c-ac306e04da81.png)
and back

**Comment by ssakharova** [comment]
Hello @psxbox,

If you are using the Entity table widget, you can use the Default sort order option.
Please see the screenshot below:
![image](https://github.com/thingsboard/thingsboard/assets/98035385/87432b9e-a824-4d20-b921-f82d73269bbc)
