### ISSUE TITLE
[Question] Create device with MQTT_BASIC auth via API 

### ISSUE THREAD

**Issue by rbarberop** [thingsboard/thingsboard#7657]
**Component**
 * Generic

**Description**
I'm trying to create a device with mqtt_basic auth (clientid, user, password) using the API...

However, the schema in swagger does not show anything else but 'complex object' for credentialsValue...

Anyone has an example or can point me in the right direction to a more complete API documentation?

**Environment**
 * ThingsBoard: 3.4.1

**Comment by ashvayka** [comment]
Hi @rbarberop , the DeviceCredentialsType should be set to MQTT_BASIC, and the credentials value is a JSON with the following format:

```
{
"clientId": "mqttClient1",
"userName": "user1",
"password":"secret"
}
```

Note that you may use a combination of: clientId + userName + password or just userName + password.

**Comment by Ultrazombie** [comment]
We would like to apprise you that your GitHub ticket has been inactive for an extended period, and we will proceed with its closure. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
