### ISSUE TITLE
Update Asset Attribute [Feature Request]

### ISSUE THREAD

**Issue by rajSilikon** [thingsboard/thingsboard#7660]
Is there a way to update Asset Attribute with a click of a button?

![image](https://user-images.githubusercontent.com/108116747/202975375-8cc72765-261a-45da-a0c2-0d43a9dfdeaa.png)

I was able to try Update Device Attribute button and is working but only for devices.

The goal is to update multiple asset attributes with a click of a button.

**Comment by devaskim** [comment]
You could clone this widget (see *Save As* button in corresponding widget bundles) and then a bit patched the code to process not a single device but multiple assets

**Comment by rajSilikon** [comment]
I did try to clone it and modify it to update assets attributes. Unfortunately I didn't get it to work.

**Comment by devaskim** [comment]
For single asset just replace
```
        let entityId = {
            entityType: "DEVICE",
            id: self.ctx.defaultSubscription.targetDeviceId
        };
```
with
```
        let entityId = {
            entityType: "ASSET",
            id: self.ctx.defaultSubscription.targetDeviceId
        };
```

**Comment by devaskim** [comment]
For multiple assets wrap `attributeService.saveEntityAttributes(....)` in loop
```
for (var i=0; i < self.ctx.datasources.length; i++) {
    let entityId = {
        entityType: self.ctx.datasources[i].entityType,
        id: self.ctx.datasources[i].entityId
    };
}
```

**Comment by rajSilikon** [comment]
This is what I did, but I ran into issues.

  let entityId = {
            entityType: "ASSET",
            id: self.ctx.defaultSubscription.targetDeviceId
        };
  
When I select the target asset, the widget does not show the button, instead it displays "No data to display on widget".
![image](https://user-images.githubusercontent.com/108116747/204412260-5e3d02f8-0064-487c-96a1-98a4dd024190.png)

![image](https://user-images.githubusercontent.com/108116747/204412432-1acfcf8e-2f56-4ca7-93b2-9715ee5a8bed.png)


It seems that even I replace  entityType: "ASSET", the widget button only displays when its a device and not an asset.

**Comment by devaskim** [comment]
You are right. I re-checked the widget's code and it is limited only to [DEVICE type](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget-config.component.html#L268)

Did you consider Input widgets? There are alson update attribute functionality

**Comment by rajSilikon** [comment]
yes, We are using the input widget to set / update asset attributes.

What we are trying to achieve is have a button that will allow to set multiple asset attributes with a single button.

For example,

When user clicks button 1.
Asset Attributes will be updated to 
A = 25
B = 40
C = 60

When user clicks button 2.
Asset Attributes will be updated to 
A = 30
B = 45
C = 75

Something like that. RIght now to update A, B, C. I have to go to each input widget and type the new values. 


The button will serve as a preset of values, when clicked will update the attributes with specific values set by us (admin).

**Comment by devaskim** [comment]
Did you try to patch code of `Input widget` not `Control widget`?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
