### ISSUE TITLE
[Question] Custom color of mat-progress-bar in cell content function

### ISSUE THREAD

**Issue by liotys** [thingsboard/thingsboard#7661]
**Component**

 * UI

**Description**
I would like to use custom colors in a mat-progress-bar column of an Entities table widget .
I use the following  sample code provided by TB that shows a progress bar according the load of a battery. 
`var progress = value;
if (value !== '') {
  return '<mat-progress-bar style="height: 8px; padding-right: 30px" ' + 
            'role="progressbar" aria-valuemin="0" aria-valuemax="100" ' + 
            'tabindex="-1" mode="determinate" value="${progress}" ' + 
            'class="mat-progress-bar mat-primary" aria-valuenow="${progress}">' + 
        '<div aria-hidden="true">' + 
            '<svg width="100%" height="8" focusable="false" ' + 
               'class="mat-progress-bar-background mat-progress-bar-element">' +
            '<defs>' + 
            '<pattern x="4" y="0" width="8" height="4" patternUnits="userSpaceOnUse" id="mat-progress-bar-0">' + 
            '<circle cx="2" cy="2" r="2"></circle>' + 
            '</pattern>' + 
            '</defs>' + 
            '<rect width="100%" height="100%" fill="url("/components/progress-bar/overview#mat-progress-bar-0")"></rect>' + 
            '</svg>' + 
            '<div class="mat-progress-bar-buffer mat-progress-bar-element"></div>' + 
            '<div class="mat-progress-bar-primary mat-progress-bar-fill mat-progress-bar-element" style="transform: scale3d(${progress / 100}, 1, 1);"></div>' + 
            '<div class="mat-progress-bar-secondary mat-progress-bar-fill mat-progress-bar-element"></div>' + 
        '</div>' + 
    '</mat-progress-bar>';
}
`

The colors options concern the themes colors (primary, accent and warn). 
I would like to use custom colors like red, orange, green according to the load.
Is it possible to do that with mat-progress-bar?
If not, how could I do that?
Thanks for your answers.

**Environment**

 * ThingsBoard: version 3.4PE

**Comment by devaskim** [comment]
Maybe I misunderstood your goals, but I finally ended up with `div` in `div` to get fully style-customized progress bar.
![progress-bar](https://user-images.githubusercontent.com/86909129/203311361-dff52f6f-146e-48a7-8f19-3b06ea2bbdfb.jpg)

**Comment by liotys** [comment]
Thanks @devaskim for your answer. What do you mean by `div ` in `div `? I'm not very familiar with html, I only used the html code proposed by TB....

**Comment by devaskim** [comment]
```
let value = .... ; // maximum value should be 100
let color = ....  ; // based on value
return `
<div style="border-radius: 3px;background-color: grey;">
    <div style="height: 15px;width: ${value}%;background-color:${color};"></div>
</div>`;
```

**Comment by liotys** [comment]
Here is the result:
![image](https://user-images.githubusercontent.com/103430329/203734670-09c6f470-8bf7-40bd-9c16-9c54d15931ec.png)
Thanks a lot @devaskim
