### ISSUE TITLE
[Question] Is it possible to turn off a device using Thinsboard demo?

### ISSUE THREAD

**Issue by ginestopo** [thingsboard/thingsboard#7662]
**Component**

 * UI

**Description**
I would like to have a table/chart to turn off the selected device. In other words, I currently have a python script sending data to thingsboard,
I would like to have button or something that allows me to execute a python function to power off the device. 
Is it possible to receive inputs from my panel to the python script?

Thank you very much in advance.

Ginés.

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: Thingsboard DEMO
 * Browser: Firefox 107.0

**Comment by Backdraft007** [comment]
You can send a RPC Command to the device. On the device the python script can read the request and handle like you want

**Comment by ginestopo** [comment]
Thanks a lot for replying @Backdraft007  😄 Are RPC commands available for thingsboard demo version?

**Comment by Backdraft007** [comment]
I think so. I have tested it with an offline device, because I have no device to connect to the demo.
But it looks good.

**Comment by ginestopo** [comment]
Thank you very much for the feedback! Have a nice day 😃
