### ISSUE TITLE
[Bug] CSV bulk provisioning not working unless _only_ access token is provided

### ISSUE THREAD

**Issue by rbarberop** [thingsboard/thingsboard#7663]
**Describe the bug**
Similar to [this issue](https://github.com/thingsboard/thingsboard/issues/3266)

When trying to create devices using bulk provisioning, it does not work if using MQTT client id, user and password.
Only works with access token.

**Your Server Environment**

* own setup
  * local infrastructure 
  * ThingsBoard Version 3.4.1 it also affects EDGE3.4.1
  * OS Name and Version Ubuntu 18.04 LTS

**Your Device**

* Connectivity
  * MQTT (any)

**To Reproduce**
1. Go to Devices
2. Click on '+'
3. Click on 'import devices'
4. Select csv file with 5 columns: 'name, type, clientid, username, password'

**Expected behavior**
After step 3, 'select columns type' and associating the columns, the 'continue' button should be activated to proceed.
It only works if I only have 3 columns in the CSV, for name, type and access token. Any other combination will prevent 'continue' button to activate.

**Comment by rbarberop** [comment]
Tested on Thingsboard 3.4.2 release and still able to reproduce.

**Comment by AlexDoanTB** [comment]
Hi @rbarberop 
Make sure you have configured the correct delimiter (as per your *.csv) and that neither the attribute nor telemetry value field is empty. There are 2 reasons why the button might not be enabled: the misconfiguration of the delimiter (or the import file has different delimiters for columns) or there are empty fields. 
The issue you are describing is not reproducible. 

Can you please share your test *.csv file?

**Comment by rbarberop** [comment]
Hi Alex,

Thanks for checking this...

I'm following [these instructions](https://thingsboard.io/docs/pe/user-guide/bulk-provisioning/) from the documentation.

If I use a csv file with just entity name and type (I'm de-selecting 'first line contains column names' and 'update attributes/telemetry' checkboxes), it works :

> devicetest-1,default
> devicetest-2,default


However, if I add a device id, username and password, it does not:

>devicetest-1,default,test-1,user,pass
>devicetest-2,default,test-2,user,pass

**Comment by AlexDoanTB** [comment]
I took the file from the instruction and succeed with the upload.

<img width="623" alt="Screenshot 2022-12-07 at 18 06 14" src="https://user-images.githubusercontent.com/47384595/206230210-24c13bad-5e11-4de9-8c96-84b5d2421006.png">

userName, clientID values should be unique per device.

**Comment by rbarberop** [comment]
Hi,

I don't see how the screenshot you posted relates to the example I sent... I don't have server attributes in the CSV file since they are not required... 

In the second example of CSV (the one that does not work for me), the fields are:
name, type, clientid, mqtt_user, mqtt_password

So, username and clientid are unique per device:

>devicetest-1,default,test-1,user,pass
>devicetest-2,default,test-2,user,pass

![image](https://user-images.githubusercontent.com/18034094/206241159-0075080f-b69e-4343-85f9-de8c6be8c6b9.png)

**Comment by AlexDoanTB** [comment]
Sorry, but I do not have any issues either. 
Have you modified the code for CE (a assume you are testing with TB CE)? 
Test with my *.csv, please
 
 <img width="574" alt="Screenshot 2022-12-07 at 19 00 30" src="https://user-images.githubusercontent.com/47384595/206242992-0237c19b-dd81-46dc-a3aa-72916fcdb58a.png">
[test.csv](https://github.com/thingsboard/thingsboard/files/10178263/test.csv)

**Comment by AlexDoanTB** [comment]
I see now. 
The bug is confirmed. 
The validation needs to be adjusted to fit your use case. As a workaround, you can upload the file and input any dummy value to your **name** and **type** fields before you define the column type for them (while there is a default "Server attribute" type) and proceed with basic MQTT credentials mapping. Change the column types to **Name** and **Type** for your fist two rows then: the Continue button will remain active. 

The fix is scheduled for v3.4.3
