### ISSUE TITLE
[Feature Request] Use X.509 certificate chain to auto-provision new devices over MQTT

### ISSUE THREAD

**Issue by rbarberop** [thingsboard/thingsboard#7668]
**Is your feature request related to a problem? Please describe.**

Right now, device auto-provisioning depends on the new device knowing the provision device key and provision device secret for the device profile it will be added to.

Also, the device needs to send this information using a specific MQTT user (provision), to a specific topic (/provision/request) and a [specific payload](https://thingsboard.io/docs/user-guide/device-provisioning/).

This complicates an operation that should be secure, but as straight-forward as possible.

**Describe the solution you'd like**

For devices that will use X.509 client certificate to authenticate, allow auto-provisioning using a X.509 certificate chain.

It would work as follows:

1. Create device profile, select X.509 chain as provision strategy.
2. Create X.509 certificate, upload to the device profile.
3. Using the device profile's X.509, sign a new X.509 client certificate for the device
4. Flash the X.509 client certificate in the device 
5. Device tries to open a normal MQTT connection with TB using X.509 to authenticate
6. TB won't find the device in the registry, so it checks if the X.509 client certificate has been signed by any of the device profiles
7. If affirmative, auto-provisions the device
8. Device reconnects and this time, since it's in the registry, authenticates without issues.

This approach is still secure and only needs the X.509 client certificate on the device vs a very specific auto-provisioning workflow.

**Additional context**

Hono uses [this same approach](https://www.eclipse.org/hono/docs/concepts/device-provisioning/#client-certificate-based-auto-provisioning) as one of the options for auto-provisioning.

**Comment by ShvaykaD** [comment]
Hi @rbarberop,

thanks for your feature request. We think that this is a valid feature request that we plan to add in our next release. Please refer for more details to the following issue comment: https://github.com/thingsboard/thingsboard/issues/6735#issuecomment-1361135339.

**Comment by AndriiLandiak** [comment]
The X.509 provisioning feature was implemented and included in the 3.5 release.
You can now refer to the updated [documentation](https://thingsboard.io/docs/user-guide/certificates/) for detailed information on how to manage and configure X.509 certificate chain in your ThingsBoard environment.

**Comment by rbarberop** [comment]
This is great news and will unlock a lot of use cases for us! Thank you!
