### ISSUE TITLE
How does transport rate limits work when using Community Edition? 

### ISSUE THREAD

**Issue by hsanderr** [thingsboard/thingsboard#7669]
**Component**

 * Generic

**Description**
 I'm particularly interested in MQTT and [here](https://thingsboard.io/docs/user-guide/install/config/#mqtt-server-parameters) we can see that the parameters of interest (transport.rate_limits.something) have a Professional Edition stamp and present no description.

**Comment by devaskim** [comment]
Generic transport rate limits are placed in Tenant Profile

**Comment by hsanderr** [comment]
So any value can be set for the rate limits in this case?

**Comment by ssakharova** [comment]
Hello @hsanderr,

Here you can find transport rate limits that you can configure for Community Edition - https://github.com/thingsboard/thingsboard/blob/0c25a3b3fff0fba968d833ca49b69975d80687f8/application/src/main/resources/thingsboard.yml#L919
