### ISSUE TITLE
[Question] TTL for cleared alarms?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7673]
**Component**
 * Generic

**Description**
I didn't find configuration parameters for automatic deletion of old cleared alarms as it is already supported for timeseries.
Does TB support TTL for alarms?

There is only `alarms.checking_interval`, but it seems to be for another purpose.

**Environment**
 * ThingsBoard: 3.4.1

**Comment by den1jkee** [comment]
Hi,
Login with sysadmin and go into Tenant Profile, click Edit and search this section
![image](https://user-images.githubusercontent.com/113901187/204554357-1a9c0d01-cd25-4256-883e-aefb209f18b9.png)
Best regards,
Denys.

**Comment by devaskim** [comment]
Thanks @den1jkee

**Comment by devaskim** [comment]
@den1jkee Do I need to restart server after setting/editing this parameter or some other in tenant profile?
