### ISSUE TITLE
[Feature Request] Send email node: Add person name to FROM/TO/CC/BCC addresses

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7674]
**Describe the solution you'd like**
Typical address syntax is of the form "user@host.domain" or "Personal Name <user@host.domain>".
It would be useful to support the second form.

**Describe alternatives you've considered**
Add customer name in email body.

**Comment by liotys** [comment]
I can't see the source of your Request but did you put <> around user@host.domain? I've tried this and it works.

**Comment by devaskim** [comment]
@liotys Thanks for help. I forgot for this
