### ISSUE TITLE
[Question] How can I show the attributes from a device inside a table widget.

### ISSUE THREAD

**Issue by ThisIsWhatIMean** [thingsboard/thingsboard#7682]
**Component**

 * UI
 * Generic

**Description**
I would like to show the attributes from a device inside a table widget. More specifically I would like to show attributes that start with the numbers "2040". I am a noob with coding and I am new to Thingsboard.

So I would like to get all the shared attributes from a device called "Thermostat T1" and put those attributes inside a table how could I achieve this?

Thanks for the help.

**Comment by ThisIsWhatIMean** [comment]
@devaskim @ashvayka @Backdraft007 @megla-tlanghorst @ouertani @msqr @kien-truong

**Comment by ThisIsWhatIMean** [comment]
@devaskim 
Yeah, I understand that I have to code it.
But my question is how do I code it?

I have 2 problems that come up now:
1. How do I get all the attributes? 
2. Where do I put the code?

Thanks,

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
