### ISSUE TITLE
[Bug] There is a typo in the document

### ISSUE THREAD

**Issue by HardwayLinka** [thingsboard/thingsboard#7689]
There is a typo in https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api

![image](https://user-images.githubusercontent.com/45873697/204072511-3a7e19f6-ae5f-4e99-8d0e-fb9397e195d4.png)

**Comment by Ultrazombie** [comment]
Hello @HardwayLinka 
Thank you for pointing out this problem
I've created a PR to fix it.
https://github.com/thingsboard/thingsboard.github.io/pull/912
