### ISSUE TITLE
[Question] Does integrations support cluster deployment?

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#7690]
For example, tcp udp integration

**Comment by baigod** [comment]
Sorry, I may not be clear. It should be that when the integration downlink rule node is used to downlink messages, the session corresponding to the integration cannot be found

**Comment by baigod** [comment]
Because when two or more integration container replicas are started at the same time, one of them will be started, and the `org. thingsboard.server.service.integration.rpc.TbCoreRemoteIntegrationRpcService#onIntegrationDisconnect` method will be called, which will cause the session to be emptied

**Comment by baigod** [comment]
The above problems occur in tb tcp udp integration: 3.4.1 PE

**Comment by ban2derlog** [comment]
hi,
unfortunately, Remote Integration won't work properly if there are more than 1 container that use same Routing Key + Secret.
this is true for all Remote Integration.
as another option you can use multiple containers for Integration Executor, but again it will work only with non-Remote Integration.
