### ISSUE TITLE
[Feature Request]Ignore list for git backup

### ISSUE THREAD

**Issue by herron-qorvo** [thingsboard/thingsboard#7692]
**Is your feature request related to a problem? Please describe.**
Yes, as described in #7420, using git to clone an existing tenant into a fresh tenant, results in errors:
1) the root rule chain from the existing tenant cannot be imported to the fresh tenant
2) the default device profile cannot be imported either
These problems cause the entire restore to fail.

**Describe the solution you'd like**
Implement a .gitignore-like feature that allows users to specify individual entities that they don't want placed in the git repo.  i.e., the original root rule chain and default device profile.

**Describe alternatives you've considered**
1) I have gone into my repo in gitlab and deleted the offending entities after pushing from the source tenant.   This works but has to be repeated each time a full backup of the original repo is made (which is a pain).
2) I have unchecked the "all entities" control in the create entities backup dialog and selected each device profile and rule chain individually when creating a full backup.  This too works but is more cumbersome than the first method.   And again, it has to be repeated each time a full backup is made.

**Comment by ViacheslavKlimov** [comment]
Hi @herron-qorvo,
You might select `Find existing entity by name` option when importing entities to the fresh tenant:
![image](https://user-images.githubusercontent.com/56742475/210336093-b1be4d79-111e-4a9a-aa39-4546ef0596db.png)

With this, there should be no conflicts with default device profile and root rule chain as they will be updated.

**Comment by herron-qorvo** [comment]
@ViacheslavKlimov,
Thanks for suggestion.  Sorry for slow response.  We switched to a development system of having two TB servers, a production server and a staging server for development.   The git support works seemlessly in this configuration since each entity can use the same ID on each server.

**Comment by herron-qorvo** [comment]
Thanks for the notice, Viacheslav.   My company has been using the two-server solution since the start of the year and it works well.
