### ISSUE TITLE
Installing Thingsboard IOT Gateway

### ISSUE THREAD

**Issue by mubashirp1786** [thingsboard/thingsboard#7693]
i tried installing thingsboard iot gateway software on windows docker, but when i enter the first instruction given in the documentation on the cmd, i am getting the following error
![image](https://user-images.githubusercontent.com/54025886/204266645-f0414e39-c0fa-44ad-8b82-1b9294eb82bc.png)
can somebody help me out in getting started with the installation.
I am finding it difficult to understand the below step as per the documentation.
![image](https://user-images.githubusercontent.com/54025886/204267094-9cf8c11d-007c-4c9c-b49e-ea9f1036d856.png)

**Comment by den1jkee** [comment]
Greetings,
Your question is not about ThingsBoard as a service
ThingsBoard Gateway has its own branch on GitHub, which means you can create questions on the [Github community of this app](https://github.com/thingsboard/thingsboard-gateway/issues).
Best regards,
Denys.
