### ISSUE TITLE
[Question] Account lockout

### ISSUE THREAD

**Issue by Timmiegamer** [thingsboard/thingsboard#7694]
In my Thingsboard PE environment, I saw the heading "mail templates" under white labeling. This includes account lockout.
Now I tried to see if that works already but I can enter wrong as many times as I want it doesn't do it. How can I set that as a safeguard?

**Comment by mde2017** [comment]
Login as System Administrator (sysadmin) and open System Settings --> Security Settings
![image](https://user-images.githubusercontent.com/25298332/204327219-2ec03a9a-32db-43b0-954f-791db5cf9afa.png)
