### ISSUE TITLE
[Question] How to optimize the execution efficiency of js-executor

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#7698]
**Component**
js-executor

Rule Engine

**Description**
Since there are many telemetry data, each telemetry needs to be processed by a rule node. In API usage statistics, we can see that the js function executes about 200 million times a day, so I run 50 js execute nodes in my server to process this data.
But still a lot of "Timeout to process xxx Last Rule Node: [RuleChain: Root Rule Chain|RuleNode xxx" logs.
How can I improve the performance of this part？
In addition, My JS_EVALUATOR mode is REMOTE.

A clear and concise details.
JavaScript functions daily activity 

**Environment**

 * OS:  ubuntu22
 * ThingsBoard: 3.3.4.1
 * Browser: chrome

**Comment by ban2derlog** [comment]
Hi,
you need to debug this first.
timeouts can be because of issue in workflow logic.
enable Debug mode on Rule Chain nodes that persist in log line - Last Rule Node: [RuleChain: Root Rule Chain|RuleNode xxx"
and check Debug in Events tab in node for errors.

**Comment by AndreMaz** [comment]
Hi @ashvayka @ban2derlog I'm having a similar issue. Upon investigating I noted that one `js_execute` node is receiving a lot more messages than the others. Once this specific node reaches ~95% of CPU it starts producing messages like

> 2023-06-02 10:51:42,875 [JsInvokeMessageProcessor] WARN: [] SLOW PROCESSING [6.452462196350098]ms, functionName [invokeInternal_e13991909e1a3b90088]   

and the thingsboard node (core/main service) starts producing messages like

> callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@29321c61), Last Rule Node: [RuleChain: Push To Kafka|RuleNode: Add Metadata (5d0305d0-cccc-bbbb-aaaa-3d99fd0c45ac)]

So, in my case, the source problem is that, instead of balancing the message processing across all the `js_execute` nodes, Kafka pushes (almost) everything to the same node and thus exhausting its resources.

I've checked the docs and found this sentence in the [JavaScript Executor Microservices](https://thingsboard.io/docs/reference/msa/#javascript-executor-microservices) docs: 

 > Requests for the same script are forwarded to the same JS executor using built-in Kafka partitioning by key (key is a script/rule node id)

From my understanding this means the same script runs always on the same node. Is this correct?  If so, is there a way to change the partitioning logic?

**Comment by xiddjp** [comment]
> Hi, you need to debug this first. timeouts can be because of issue in workflow logic. enable Debug mode on Rule Chain nodes that persist in log line - Last Rule Node: [RuleChain: Root Rule Chain|RuleNode xxx" and check Debug in Events tab in node for errors.
I found all the fail message is Timeout，can not get useful message.

**Comment by xiddjp** [comment]
> Hi @ashvayka @ban2derlog I'm having a similar issue. Upon investigating I noted that one `js_execute` node is receiving a lot more messages than the others. Once this specific node reaches ~95% of CPU it starts producing messages like
> 
> > 2023-06-02 10:51:42,875 [JsInvokeMessageProcessor] WARN: [] SLOW PROCESSING [6.452462196350098]ms, functionName [invokeInternal_e13991909e1a3b90088]
> 
> and the thingsboard node (core/main service) starts producing messages like
> 
> > callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@29321c61), Last Rule Node: [RuleChain: Push To Kafka|RuleNode: Add Metadata (5d0305d0-cccc-bbbb-aaaa-3d99fd0c45ac)]
> 
> So, in my case, the source problem is that instead of balancing the message processing across all the `js_execute` nodes, Kafka pushes (almost) everything to the same node and thus exhausting its resources.
> 
> I've checked the docs and found this sentence in the [JavaScript Executor Microservices](https://thingsboard.io/docs/reference/msa/#javascript-executor-microservices) docs:
> 
> > Requests for the same script are forwarded to the same JS executor using built-in Kafka partitioning by key (key is a script/rule node id)
> 
> From my understanding this means the same script runs always on the same node. Is this correct? If so, is there a way to change the partitioning logic? It seems that this partitioning strategy creates some skewness in broker usage.
> 
> More context:
> 
> * js_evaluator mode: remote
> * number of evaluator nodes: 16
> * number of kafka brokers: 3

All my js-executor node cpu load is about 30%, but rule chain alway show execption "com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: SettableFuture@174e6c00[status=PENDING]
"

**Comment by baigod** [comment]
I also encountered the same situation.
May I ask how much CPU and memory do you usually allocate to the js executor container.
My architecture is a Kafka cluster, 4-core 8G x 3, with 50 1-core 1G js executor container replicas.
My tps for each nodejs is only around 70-80

**Comment by pon0marev** [comment]
Universal resource allocation settings for js-executables may not work in each particular case. You should monitor resource usage by containers in kubernetes `kubectl top pods` . And then need to perform resource management.
Basic settings for js-executors resource management you can start with:

```yml
  replicas: 6
....
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=200"
...
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 400m
            memory: 300Mi
```
