### ISSUE TITLE
RabbitMQ Plugin: Able to manually specify 'Content-Type' and 'Routing-key' in interface

### ISSUE THREAD

**Issue by marcelmaatkamp** [thingsboard/thingsboard#77]
I would like to specify the content-type and routing-key when a rule sends its output to rabbitmq in
 Rules -> Rule Details -> Plugin Action

I would like to be able to specify that the object is 'application/json' for example and has a routing-key which should be able to include fields like id/name of the object being sent.

Attached is the screenshot of the fields which are currently editable where I would like the fields to be added:
![screen shot 2017-03-16 at 09 37 52](https://cloud.githubusercontent.com/assets/6911/23987972/7f37dfae-0a2c-11e7-93d1-c6603043dfef.png)

**Comment by ashvayka** [comment]
Hi @marcelmaatkamp ! All our team members are quite busy now. One of them is working on contribution guide with details how to add/modify plugins. I will add a link here when this is ready. Feel free to contribute the changes you require.

**Comment by marcelmaatkamp** [comment]
If time permits I certainly will!! And I see these issues as a place to store features for others to see and maybe work on, be it temmembers or others wanting to contribute.

**Comment by vparomskiy** [comment]
Not valid anymore. Since ThingsBoard v2.x. specific Rule Nodes should be used.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rabbitmq-node
