### ISSUE TITLE
[Question] HTTP über SSL ( SSL_PEM_KEY und  SSL_PEM_KEY_PASSWORD )

### ISSUE THREAD

**Issue by Rawan-Nassan** [thingsboard/thingsboard#7702]
**Component**
 * Installation

**Description**
I'm trying to insert an SSL certificate for HTTPS, I got a certificate in PEM format from my university.
I also have different formats such as:

- Certificate only, PEM encoded
- Certificate (w/ issuer after), PEM encoded
-Certificate (w/ chain), PEM encoded
- PKCS#7
- PKCS#7, PEM

And Issuing CA certificates only:
    -  as Root/Intermediate(s) only, PEM encoded
    - as Intermediate(s)/Root only, PEM encoded

I have read the documentation at: https://thingsboard.io/docs/user-guide/ssl/http-over-ssl/.
I have extended the config file (thingsboard.conf) under /usr/share/thingsboard/conf/ like this: 
(I took the first option for SSL_PEM_CERT so as Certificate only, PEM encoded = server.pem )
```
export SSL_ENABLED=true
export SSL_CREDENTIALS_TYPE=PEM
export SSL_PEM_CERT=/usr/share/thingsboard/conf/ssl/server.pem
export SSL_PEM_KEY=""
export SSL_PEM_KEY_PASSWORD=""
```

but now I get an error after new start with :
sudo service thingsboard restart
here is the log output after (tail -f /var/log/thingsboard/thingsboard.log) :

`Caused by: java.lang.RuntimeException: HTTP Server SSL Credentials: Invalid SSL credentials configuration. None of the PEM or KEYSTORE configurations can be used!
	at org.thingsboard.server.common.transport.config.ssl.SslCredentialsConfig.init(SslCredentialsConfig.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 54 common frames omitted
`
**Question**
I'm relatively new to https/ssl
so I don't understand what the two terms mean here
```
export SSL_PEM_KEY
export SSL_PEM_KEY_PASSWORD
```
Does my error have something to do with SSL_PEM_KEY and SSL_PEM_KEY_PASSWORD, if so where do I find/generate these SSL_PEM_KEY and SSL_PEM_KEY_PASSWORD

**Environment**

 * OS:   Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-53-generic x86_64)
 * ThingsBoard: 3.4.1-1

**Comment by den1jkee** [comment]
Hey,
Did you change permissions to the .pem according to the thingsboard user?
Do you have a password for your .pem? If not, comment this lines:
`export SSL_PEM_KEY_PASSWORD=""`
P.S. Does your .pem like a key and cert all in one? If yes, comment this line:
`export SSL_PEM_KEY=""`
Regards,
Denys.

**Comment by Rawan-Nassan** [comment]
Hallo @den1jkee 

Thanks for your answer, I actually forgot to give the permissions.
I have now given the permissions as follows:

`chmod 754 /usr/share/thingsboard/conf/ssl/thingsboard_informatik_hs-augsburg_de.pem`

**-> Do you have a password for your .pem? If not, comment on this line.**

No, I don't have a password for .pem, I've now commented on this line.

**-> PS Does your .pem like a key and cert all in one? If yes, comment this line:**
No, my .pem consists of 3 big sections starting with (BEGIN CERTIFICATE) and ending with (END CERTIFICATE) respectively as follows:

----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----

**Comment by den1jkee** [comment]
Hi,
Then execute this command and show me an output of your PEM. 
`openssl rsa -in YOUR_KEY_HERE.pem -text`
I`m waiting for **BEGIN RSA PRIVATE KEY** section. They should be present in your PEM, if no - SSL do not start to work

**Comment by Rawan-Nassan** [comment]
Hey @den1jkee ,

**->Then execute this command and show me an output of your PEM.**
I have executed the command
`openssl rsa -in server.pem -text`
Here is the output:
`Could not read private key from server.pem`

I changed the words ----BEGIN CERTIFICATE----- to ----- BEGIN RSA PRIVATE KEY----- 
and  ----END CERTIFICATE----- to ----- END RSA PRIVATE KEY----- 
in the server.pem file and executed the command again. 
This is the output after the change:

`Could not read private key from server.pem
40C7265D467F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
40C7265D467F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
40C7265D467F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
`

**Comment by den1jkee** [comment]
`Could not read private key from server.pem` - means that you have only 50% of cert for work. Without a private key, SSL doesn`t work. 
You can try to install HAProxy from our Docs and use it if you cant get a key.
Best regards,
Denys

**Comment by Rawan-Nassan** [comment]
Hallo @den1jkee 

thank you very much, i found the error. I needed a private key. It was sent to me today.
I have the Key in :
`export SSL_PEM_KEY`,
integrated and now everything works great

**Comment by den1jkee** [comment]
You`re welcome. Great job. Have a nice weekend:)
Best regards,
Denys.
