### ISSUE TITLE
Control device without dashboard

### ISSUE THREAD

**Issue by ehsanmqn** [thingsboard/thingsboard#771]
Hi, 
Is there anybody to help me please? I want to control a device that is connected to thingsboard without the thingsboard UI panel using some API or something. Is it possible at al?

**Comment by mp-loki** [comment]
Please see the REST API documentation: https://thingsboard.io/docs/reference/rest-api/

**Comment by ehsanmqn** [comment]
@mp-loki I just examined this link. Unfortunately doesn't found anything. Could you guide me please?

**Comment by ehsanmqn** [comment]
Dear @mp-loki I found [this](https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api) instruction to control devices. But, every time I use curl command with the given JWT token I got following error.

* Hostname was NOT found in DNS cache
*   Trying 192.168.1.102...
* Connected to 192.168.1.102 (192.168.1.102) port 8080 (#0)
> POST /api/plugins/rpc/twoway/583a5310-5395-11e8-b7f9-c5d498923028 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.1.102:8080
> Accept: */*
> Content-Type:application/json
> X-Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBjb25uZWN0LmlyIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiI2N2JjNTBhMC01Mzk0LTExZTgtYjdmOS1jNWQ0OTg5MjMwMjgiLCJmaXJzdE5hbWUiOiJFaHNhbiIsImxhc3ROYW1lIjoiTWFpcWFuaSIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiI0ZDgzODQxMC01Mzk0LTExZTgtYjdmOS1jNWQ0OTg5MjMwMjgiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE1MjU4ODgyMzksImV4cCI6MTUzNDg4ODIzOX0.5d7SdDAYrzOpFPVwtzE8S6i7iwqdOzOILsvYqh_XU2iAdHvMJoEf6b914Z-FEX5i9HWhiRrIq2zYexpFgYGIQQ
> Content-Length: 79
> 
* upload completely sent off: 79 out of 79 bytes
< HTTP/1.1 401 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 96
< Date: Wed, 09 May 2018 17:51:11 GMT
< 
* Connection #0 to host 192.168.1.102 left intact
{"status":401,"message":"Invalid username or password","errorCode":10,"timestamp":152588827

**Comment by ehsanmqn** [comment]
Dear @mp-loki , I found the solution in [this](https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api) link. Thank you very much for your goodness.
