### ISSUE TITLE
[Question] Rule Engine- Change originator to a specific asset

### ISSUE THREAD

**Issue by kandrianatos** [thingsboard/thingsboard#7710]
**Component**

 * UI
 * Rule Engine

**Description**
Am trying to change originator from the customer to a specific asset (I have already create customer’s relationships with its assets), but it change always to the first related asset, I saw in documentation that if multiple related Entities are found, only the first entity is used as new originator, other entities are discarded. I would like to ask if there is a way to change to a specific asset some how.

![image](https://user-images.githubusercontent.com/22050314/204820409-b074c201-eed5-4388-b0f8-b236dc564821.png)

**Environment**

OS: Windows 11 Pro Local Installation

**Comment by liotys** [comment]
Hi, ij you know that it's a specific asset when you create the link with it, use a specific name for the link instead of "contains". So you can put this name in the field Type of the change originator.

**Comment by kandrianatos** [comment]
Hi @liotys and thanks for the relpy, in change originator relation filters there are only two options "contains - manages". Can you please provide more details?

**Comment by liotys** [comment]
Don't use the list, just enter text...

**Comment by kandrianatos** [comment]
You mean something like that?
![image](https://user-images.githubusercontent.com/22050314/205042411-c5f5c147-8ec8-47be-9288-71e167b4655e.png)

**Comment by kandrianatos** [comment]
You mean something like that?
![image](https://user-images.githubusercontent.com/22050314/205042863-d476b6f4-4948-411f-8aa7-16262ee67495.png)

**Comment by liotys** [comment]
I guess, but Asset 01 isn't the name of the asset, it's the type of the link. When you create the link, enter Asset 01 instead of contains or manages.

**Comment by kandrianatos** [comment]
Asset 01 is the name of the asset, what do you mean with the type of the link? Is there any sample or documentation about it?

**Comment by liotys** [comment]
When you create a relation, you don't have to use only contains or manages, you can enter free text (PAV in my example):
![image](https://user-images.githubusercontent.com/103430329/205092549-a9eab53b-38bf-4a6b-b3a6-0b3d547e6386.png)

![image](https://user-images.githubusercontent.com/103430329/205091720-aa83fa24-7f40-4dc3-85d7-1fc80c3078f3.png)
then in the change originator you can use this type:
![image](https://user-images.githubusercontent.com/103430329/205092069-3e82b47f-a878-4282-86fa-ae219ae7fc38.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
