### ISSUE TITLE
[Bug] Upgrade from Thingsboard PE 3.3.4.1 to PE 3.4.0 Failed!

### ISSUE THREAD

**Issue by sjupas** [thingsboard/thingsboard#7715]
**Describe the bug**
While upgrading to PE 3.4.0 upgrade script sudo /usr/share/thingsboard/bin/install/upgarde.sh --fromVersion=3.3.4.1 fails with error: Error creating bean with name 'tenantServiceImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
ThingsBoard upgrade failed!

**Your Server Environment**

* own setup
  * local infrastructure 
  * ThingsBoard Version: 3.3.4.1
  * OS Name and Version: Ubuntu 20.04.5 LTS

**Your Client Environment**

* own setup
  * local infrastructure 
  * ThingsBoard Version: 3.3.4.1
  * OS Name and Version: Ubuntu 20.04.5 LTS

* Connectivity
  
  * Integration: TCP/UDP

**To Reproduce**

**Expected behavior**
Upgrade success

**Screenshots**
![image](https://user-images.githubusercontent.com/64548453/204921267-cc1fc65f-5604-4714-bc84-36ca2dcf3c45.png)

**Additional context**
Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRuleChainService': Unsatisfied dependency expressed through field 'ruleChainValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ruleChainDataValidator': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantServiceImpl': Unsatisfied dependency expressed through field 'customerService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customerServiceImpl': Unsatisfied dependency expressed through field 'assetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseAssetService': Unsatisfied dependency expressed through field 'entityViewService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityViewServiceImpl': Unsatisfied dependency expressed through field 'entityViewValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityViewDataValidator' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/dao-3.4.0PE.jar!/org/thingsboard/server/dao/service/validator/EntityViewDataValidator.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'tenantServiceImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
ThingsBoard upgrade failed!

**Comment by den1jkee** [comment]
Hi,
For resolving this issue, use the following:
`sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.3.4`
Not `--fromVerison=3.3.4.1`.
Best regards,
Denys.

**Comment by sjupas** [comment]
Thanks. Solved it
