### ISSUE TITLE
[Bug]  Server crash for unkown reason

### ISSUE THREAD

**Issue by herken** [thingsboard/thingsboard#7717]
**Describe the bug**
Hello,
the service thingsboard crashing for unknown reason. I searched on the log but i just found this error 👍 
 Failed to submit a listener notification task. Event loop shut down?

I don't know if it's could be the origin of the issue. I joining the log. 

**Your Server Environment**

Ubuntu 18
Virtual Machine (Vmware ) 

File : https://send.e-all.io/download/5568d888713b8af9/#69ErGGU7MVq32UffVfFe0g

Password : thingsboard
Thank you

**Comment by Backdraft007** [comment]
I think this is your problem.
ERROR o.a.coyote.http11.Http11NioProtocol - Error processing async timeouts
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

How much RAM do you give your VM?

**Comment by Backdraft007** [comment]
Yes I think taht is enough. There are many errors with a scheduled task. Do you created tasks?

**Comment by herken** [comment]
Hi @Backdraft007 ,

it's my colleague who working with thingsboard but i see only one thing in scheduled.
![image](https://user-images.githubusercontent.com/36696910/205256106-ce520ab5-4814-429c-83f0-b0a9325bfe4f.png)

**Comment by Backdraft007** [comment]
Hmm ok.
I'm not so deep in Java development. As I can see, you use PE version. I think it is better to open a support ticket and link to this issue.

**Comment by den1jkee** [comment]
Hi,
Add this line to your thingsboard.conf and restart the service:
`# Update ThingsBoard memory usage and restrict it to 8Gb in /etc/thingsboard/conf/thingsboard.conf
export JAVA_OPTS="$JAVA_OPTS -Xms8G -Xmx8G"`
After this action, please provide us feedback and a thingsboard.log file for further investigation of the problem if the problem will be still persist.
Best regards,
Denys.

**Comment by herken** [comment]
Hello sorry for the late, i will try and keep you inform thank you

**Comment by herken** [comment]
Hi again crashed after less than 1 hour :(

**Comment by den1jkee** [comment]
Hi,
Please provide thingsboard.log, gc.log and the log that this command will give about the error `journalctl -u thingsboard`
Also, is swap off?

Best regards,
Denys.

**Comment by herken** [comment]
Hi,
here the link : https://send.e-all.io/download/12226152f11a0f17/#UBJw7biX70s4_Jj_E6PG2w
Last line on journal

Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstract>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEvent>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEv>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:7>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRun>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at java.base/java.lang.Thread.run(Thread.java:829)
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: Exception in thread "DbCallbackExecutorService-60-28" java.lang.OutOfMemoryError: >
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: Exception in thread "MqttTransportContext-58-10" java.lang.OutOfMemoryError: Java >
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: Exception in thread "MqttTransportContext-59-19" java.lang.OutOfMemoryError: Java >
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: Exception in thread "DefaultTransportService-23-15" java.lang.OutOfMemoryError: Ja>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: SLF4J: Failed toString() invocation on an object of type [io.netty.handler.codec.m>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: Reported exception:
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]: io.netty.util.IllegalReferenceCountException: refCnt: 0
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.buffer.ByteBufUtil.ensureAccessible(ByteBufUtil.java:125)
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.mqtt.MqttPublishMessage.content(MqttPublishMessa>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.mqtt.MqttPublishMessage.payload(MqttPublishMessa>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.mqtt.MqttPublishMessage.payload(MqttPublishMessa>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.mqtt.MqttMessage.toString(MqttMessage.java:88)
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.ja>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatt>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:21>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:16>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:151)
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.util.internal.logging.LocationAwareSlf4JLogger.warn(LocationAw>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:11>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstract>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessa>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDe>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstract>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Default>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelP>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstract>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:>
Dec 15 14:13:57 AFDU18-p-eall-TB01.FRANCOIS.INT thingsboard.jar[1433465]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEvent>
D


Thank you !

**Comment by herken** [comment]
Hi @den1jkee  sorry for the late i was on holliday :(

Do you tell me i need to disable swap  if it's on?

**Comment by herken** [comment]
I restarted service and you can see the swap status 👍 
tbuser@AFDU18-p-eall-TB01:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16009        1066         163         250       14780       14363
Swap:          4095          43        4052

**Comment by den1jkee** [comment]
Hi,
Yes, swap always interferes with Java Applications that have their garbage collector and work in many threads.
Try it with swap off.
If this didn't help you, try to use tools to investigate the problem, such as Visualgc, VisualVM.
Thanks.
Best regards,
Denys.
