### ISSUE TITLE
[Bug] Changes are not detected in Widget editing, not able to Save

### ISSUE THREAD

**Issue by thhart** [thingsboard/thingsboard#7718]
**Describe the bug**
Save button does not get activated when I try to change a widget setting. I am not able to save any change. Tested in Chrome as well as in Firefox.

**Your Server Environment**
* own setup
  * Version: 3.4.1
  * System: Debian

**Your Client Environment**

* OS: Linux
* Browser chrome 107.0.5304.121, Firefox

**To Reproduce**
1. Go to Dashboard
2. Click on Edit Dashboard
3. Edit a widget and change a value
4. Save Button does not get activated

**Screenshots**
![image](https://user-images.githubusercontent.com/2632538/205044965-5c33427d-85cd-435b-b9df-d5ba5c2aa1e3.png)

**Comment by den1jkee** [comment]
Hi,
Please go into the advanced settings section, check all your settings and code in this section, and make sure that there all correct for saving. 
I`m sure you have an error in a widget that blocks saving settings.

Best regards,
Denys.

**Comment by thhart** [comment]
Thanks, you are right there was an error in a Javascript which looks like an incompatibility with prior versions. It was hardly visible though, but thanks again.
