### ISSUE TITLE
the way that tb deal with data from edge is not effecient

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#7719]
the way that tb deal with data from edge is not effecient,that's part of the code in TelemetryEdgeProcessor processPostTelemetry
for (TransportProtos.TsKvListProto tsKv : msg.getTsKvListList()) {
}

that means tb will send telemetry to rule engine one by one,which will reduce the speed that it will process。
if edge tb send batch of data to tb,it will not cause poor efficiency

**Comment by volodymyr-babak** [comment]
hi @john1337 

thanks for suggesting this improvement. 
I had created a new ticket in thingsboard-edge repository:
https://github.com/thingsboard/thingsboard-edge/issues/37

We'll review it in more details and target for future releases.
I'm closing this one - improvements are going to be tracked in the edge repository.
