### ISSUE TITLE
Get time series telemetry data with API Call 

### ISSUE THREAD

**Issue by belalmc** [thingsboard/thingsboard#772]
I can't get telemetry data with "Timeseries data values API" other API calls are working fine with me but this one , I have generated JWT token successfully but when I call it replies with this "{
"status": 401,
"message": "Invalid username or password",
"errorCode": 10,
"timestamp": 1525802187527
}"
Using this guide: https://thingsboard.io/docs/user-guide/telemetry/#timeseries-data-values-api , postman as a tool

**Comment by mp-loki** [comment]
Can you please show your request with HTTP headers?  (In postman when you click 'Code' in upper-right corner)

**Comment by rchemali** [comment]
i have same probleme any solution ?

**Comment by untilbit** [comment]
The HTTP API call to get time-series works for me only when I set the parameter **agg** to **NONE**. It does not work for other values like **MIN, MAX, AVG, SUM or COUNT**.

**Comment by belalmc** [comment]
@untilbit can you please where to put this parameter, header?

**Comment by ashvayka** [comment]
"X-Authorization: **Bearer** YOUR_TOKEN_HERE"

**Comment by belalmc** [comment]
@ashvayka sorry but I already did that can you please explain?

**Comment by untilbit** [comment]
@belalmc 

- Run this command in terminal to get token:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"username":"tenant@thingsboard.org", "password":"tenant"}' 'http://127.0.0.1:8080/api/auth/login'
```

- Put token, device ID, startTs, endTs in the command below:
```
curl -v -X GET http://127.0.0.1:8080/api/plugins/telemetry/DEVICE/{entityId}/values/timeseries?keys=key1&startTs=**0000000000000**&endTs=**9999999999999**&interval=60000&limit=100&agg=NONE \
--header "Content-Type:application/json" \
--header "X-Authorization: Bearer **PUT_YOUR_TOKEN_HERE**"
```

You can use https://www.epochconverter.com/ to convert date to timestamp.

**Comment by belalmc** [comment]
Many thanks for all, it works fine now, I just added "Bearer " before the token @rchemali

**Comment by rchemali** [comment]
Ok thank you :)
