### ISSUE TITLE
Why my MQTT uplink on mqtt integration doesnt recieves all messages?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7723]
**Component**

 * Generic

**Description**
As the title says, my problem is the fact that the uplink converter doesnt recieves all messages from the coresponding mqtt broker. For example, there is a client publishing every 5 seconds to an mqtt broker, i created an uplink converter recieving messages from that broker. The uplink though does not receives all messages (like 7 in 10 or even worse sometimes), also there is no time pattern of which i will recieve and which not.

I'm sure that the publishing device and broker works fine, cause i connected  an other client to the broker and it can recieves every message as expected.
The only thing i suspect is that maybe something is wrong with the Kafka queue

Also, i forgot to mention 2 things:
 1st: I noticed the same behavior (even worse to be honest) on the cloud Thingsboard PE Trial version.
 2nd: When the device subscribes to thingsboard mqtt broker (when no uplink converter needed)  rule chain can recieves every message that the device is publishing.

**Environment**

 * OS:  Ubuntu 22 
 * ThingsBoard: 3.4
 * Browser: Firefox

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
