### ISSUE TITLE
[Feature Request] Entity Alias for device list with *multivalue* filter by device type

### ISSUE THREAD

**Issue by smatvienko-tb** [thingsboard/thingsboard#7724]
## Entity Alias (edit dashboard) for a device list with *multivalue* filter by device type

At this moment, only a single device type can be shown by entity alias (see screenshot)
![image](https://user-images.githubusercontent.com/79898499/205278591-f053768c-4912-47af-8372-6310a681f0fd.png)

To override this, the user needs to use additional filters that adds overhead for the high-load databases

**Describe the solution you'd like**
The desired filter may look similar to the "Device search query" that uses a relation query with a multivalue filter by device type (see screenshot)

![image](https://user-images.githubusercontent.com/79898499/205280269-8c6d5920-304d-41b0-8965-340fe12fc425.png)

**Describe alternatives you've considered**
The alternatives already exist, but they bring too much overhead to the database for high-load projects.

**Additional context**
The performance will be skyrocketing!

**Comment by volodymyr-babak** [comment]
Related PR has been successfully merged, and the feature is included in the 3.5 Release. Closing this issue.
