### ISSUE TITLE
[Question] Automatic dashboard creation

### ISSUE THREAD

**Issue by Timmiegamer** [thingsboard/thingsboard#7727]
Hello, 
I want to automate the whole process of thingsboard. But I can create devices and assets automaticaly but is it also possible that I can for example reference to a JSON file with a dashboard in it and get the device automaticaly linked to it? 
I want this to work in the Thingsboard PE customer hierarchy.

**Comment by NistantriTech-Dhaval** [comment]
Hi @Timmiegamer 
In thingsboard PE I think better to use shared dashboard functionality 

What I used to do for my customer is.
we use the table widget for tenant to create, manage and delete customers.
On time of create customer we share the predefined dashboard to newly created customer

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by JosAndrae** [comment]
> Hi [@Timmiegamer](https://github.com/Timmiegamer) In thingsboard PE I think better to use shared dashboard functionality
> 
> What I used to do for my customer is. we use the table widget for tenant to create, manage and delete customers. On time of create customer we share the predefined dashboard to newly created customer

how do you do that?

**Comment by NistantriTech-Dhaval** [comment]
@JosAndrae 
in table actions please check custom action with html it has sample code for managing devices and asset but can modify to manage for customers 
its not straight forward but doable with it.
