### ISSUE TITLE
[Question] HTTP-Request to API out of widgets returns 401 "Unauthorized"

### ISSUE THREAD

**Issue by X1folta** [thingsboard/thingsboard#7729]
**Component**

 * UI

**Description**

I am trying to do a http-post request out of a widget, but it always returns me that I am not authorized. Even if I go into Swagger, successfully do the call and post the JWT-Token into my code to be sure its the corrent one it still tells me Im unauthorized and returns code 401. Are the headers wrongly defined or why cant it authorize me? At the end I want to trigger the download of a dashboard as a PDF, thus why Im using the curl for downloadDashboardReport. 

```
makeHTTPRequest = () => {
        
        //console.log(localStorage)
            
        let jwt_at = localStorage.getItem('jwt_token'); 
        
        let url = "https://____/api/report/_genericDashboardId_/download";
        
        let headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "X-Authorization": `Bearer ${jwt_at}`
                };
       
        
        http.post(url, headers).subscribe((resp) => {
            console.log("success", resp);
            
        }, (res) => {
            console.log("fail", resp);
            
        });
    
    }
```

**Environment**

 * OS:  Windows 11
 * ThingsBoard: 3.4 PE version
 * Browser: Mozilla

**Comment by basor-dali** [comment]
@X1folta  Not sure if this is still relevant to you, but it could help someone else as well.

401 happens probably because your request is missing {} around 'headers'.

Correct request would be 

`        http.post(url, {headers}).subscribe((resp) => {
            console.log("success", resp);
            
        }, (res) => {
            console.log("fail", resp);
            
        });`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
