### ISSUE TITLE
[Bug] Upgrade from 3.4.1 to 3.4.2 errors

### ISSUE THREAD

**Issue by HaydenBurrows** [thingsboard/thingsboard#7731]
**Describe the bug**
Errors when upgrading from 3.4.1PE to 3.4.2PE (see screenshot).
Can't log in as tenant admin - error "java.lang.nullpointerexception".  Error in logs also. "unable to decode
Can log in as system admin.
Can log in as customer.
Other errors in logs also.
Successfully downgraded to 3.4.1PE by restoring backup database.

**Your Server Environment**
* own setup
  * docker deployment with AWS RDS Postgres database
  * ThingsBoard Version 3.4.1PE
  * Ubuntu 22.04

**Your Client Environment**
* OS: Ubuntu 22.10
* Browser Firefox
* Version 107

**To Reproduce**
1. Upgrade from 3.4.1 to 3.4.2
2. Observe startup errors
3. Login as system admin and change JWT admin settings.
4. Reset browser cache
5. See errors.

**Expected behavior**
Log in as usual, no errors.

**Screenshots**
Upgrade
![image](https://user-images.githubusercontent.com/69659611/205511986-c16b3b83-7aba-4bbb-80e3-77f872303c1b.png)
Error while startup
![image](https://user-images.githubusercontent.com/69659611/205512029-36adff0a-6f52-42b4-80d7-16455cc68b3c.png)
Change JWT settings
![image](https://user-images.githubusercontent.com/69659611/205512304-c81d819b-2bdc-49ed-826c-87a14ec20771.png)
Error while login as tenant admin
![image](https://user-images.githubusercontent.com/69659611/205512333-c8de5b99-5733-4c4b-99da-d1c1e663a6d3.png)
other errors
![image](https://user-images.githubusercontent.com/69659611/205512821-488acace-ccac-4a06-9a64-f9014f93f832.png)

**Comment by den1jkee** [comment]
Hi,
Can you please provide install.log, thingsboard.log, and thingsboard.conf? 
This is necessary for a detailed investigation of the problem.
Best regards,
Denys.

**Comment by HaydenBurrows** [comment]
Apologies for the late reply as I have been on leave.  I have provided:
- install.log
[install.log](https://github.com/thingsboard/thingsboard/files/10232130/install.log)
- thingsboard.log for the 13 minutes that I had 3.4.2 running
[thingsboard.2022-12-04.0.log](https://github.com/thingsboard/thingsboard/files/10232132/thingsboard.2022-12-04.0.log)
- thingsboard.txt/conf (from docker container)
[thingsboard.txt](https://github.com/thingsboard/thingsboard/files/10232128/thingsboard.txt)

I will dump my database and have a play with 3.4.1 & 3.4.2 on my development system to see if I can pinpoint the problem.

**Comment by HaydenBurrows** [comment]
I have a created a fresh local docker-compose instance connected to a remote AWS RDS copy of my existing database (3.4.1).  I went through the upgrade steps to 3.4.2, tested and all ok, upgrade to 3.4.3 all ok.

I tried connecting the upgraded 3.4.3 to my production system, but have the same error.  I'm not sure if this is too simplistic?

What I did notice is that when using the local system the organisation colours did not appear.  Are these values not stored in the main database?  Is there a local file/database with these settings?

**Comment by den1jkee** [comment]
In 3.4.3 was fixed this issue with login, and it should work, but if you have the same, please open DevTools, take a screenshot of the error, and attach it to msg.

Also, white-labeling settings are stored in the database.

Best regards,
Denys.

**Comment by HaydenBurrows** [comment]
Hi, thanks for the mention that this was fixed in 3.4.3.  I have updated from 3.4.1 --> 3.4.2 --> 3.4.3.  I have no issues with logins now.  I look forward to the new additions in the latest version.  Thanks for your help.

**Comment by GrayCygnus** [comment]
I had the same issue as here (upgraded from 3.4.1 to 3.4.2 and was unable to login). In my case, upgrading to 3.4.3 solved this problem and was able to login correctly with all my users (currently going from 3.4 to 3.5.1 hope that I don't keep hitting issues, already hit a couple on the previous steps of upgrade)
