### ISSUE TITLE
[Feature Request] Rule Chain UI: Button to clear debug events of all nodes in chain

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7735]
**Describe the solution you'd like**
At rule chain page add button to clear debug events of all nodes in chain

**Comment by vvlladd28** [comment]
HI @devaskim,
This button is already implemented in TB.
![image](https://user-images.githubusercontent.com/18036670/205865967-9592c049-c872-4b91-bf37-d89234b6873e.png)

**Comment by devaskim** [comment]
@ashvayka First of all, please, enable for users `Reopen` button for issues.

@vvlladd28 This button disables Debug mode, but my debug events stay where they were. Each node has `Clear event` button and it works as expected, i.e. debug events are being deleted right after clicking on the button. 

I suggested to add button with the same functionality but for all nodes of the rule chain at once.
