### ISSUE TITLE
Thingsboard IOT Gateway

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7737]
![image](https://user-images.githubusercontent.com/49026279/205629002-16d4a745-a63a-4780-ad83-64ad10f48111.png)
I installed a docker in windows to set up thingsboard IOT gateway.  But when i run the above command as per the documentation, i am getting the error as shown.
Kindly provide a solution to resolve this or suggest me the right way to get started with thingsboard iot gateway installation on windows.

**Comment by devaskim** [comment]
For Windows use `\` instead of `/` in paths, e.g.:
```
-v C:\Users\User\code\tb-gateway-instance\config:/thingsboard_gateway/config
```

**Comment by mubashirp** [comment]
![image](https://user-images.githubusercontent.com/49026279/206400124-fac209aa-2e18-4d80-9541-fb01b4daef6e.png)
i used  \ for left side paths, but still the error is showing same.

**Comment by devaskim** [comment]
What output of `echo %HOMEPATH%` ?

**Comment by mubashirp** [comment]
![image](https://user-images.githubusercontent.com/49026279/207277161-448b8a49-a765-4659-b724-2885730d7923.png)
@devaskim

**Comment by devaskim** [comment]
You need to add at the beginning `C:`. i.e. `C:\Users\mubas`
