### ISSUE TITLE
[Bug] StateChart should display the timeseries instead only displays latest value in TB 3.4.2

### ISSUE THREAD

**Issue by X1folta** [thingsboard/thingsboard#7742]
**Describe the bug**
StateChart seemingly takes only the latest value instead of the timeseries. The example below adresses its timeframe during "current day" there one change of the value happens around 05:00 in the morning. This change is not mirrored in the state chart view and instead only the latest value is taken and displayed.

**Your Server Environment**

  * ThingsBoard Version 3.4.2 PE

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [Win 11]
* Browser [Mozilla Firefox]
* Version [107.0.1]

**To Reproduce**
1. Go to Asset
2. Click on Telemetry Key like "load_status"
3. Display in State Chart
4. See only latest value

**Expected behavior**
As the example key "load_status" is a timeseries and one that changed its value specifically at around 5 o'clock in the morning I expect that change to be mirrored in the state chart widget.

**Screenshots**
![multipleValuesTimeSeries](https://user-images.githubusercontent.com/69015781/205903886-60fffdd3-6e22-47bf-b5e7-8c124a849dcb.png)
![loadstatus_values](https://user-images.githubusercontent.com/69015781/205903905-37b171a0-50ab-401e-84e7-bc5429e10ffb.png)
![loadstatus_values (2)](https://user-images.githubusercontent.com/69015781/205903922-dc6fb99b-b610-4eb6-b46b-529faac43eaa.png)

![testDashboard](https://user-images.githubusercontent.com/69015781/205904111-e4fcde9f-4ac5-4101-ab44-04b901b77937.png)
![stateChartView](https://user-images.githubusercontent.com/69015781/205903940-c3ae8c8f-2be3-45de-8291-1b2ad712cafb.png)

**Additional context**
The screenshots display the assets timeseries key "load_status" in the time frame of "current day". Beginning of day the value is "0" and later at around 5 o'clock in the morning its "11". Two screenshots display the view from its intended widget and one from a test dashboard and test widget generated through the asset view itself.

**Comment by X1folta** [comment]
sorry I uploaded one time the wrong screenshot of a different asset, visible on the asset name ending with "05", which is the incorrect one. Here is the correct screenshot with the change of value in the morning.

![correctValueChange](https://user-images.githubusercontent.com/69015781/205922516-f32b11fb-de84-461d-9a0f-a1810c3dfc90.png)

**Comment by Ultrazombie** [comment]
Hello @X1folta 
thanks for pointing out this problem. fixed in 3.4.3 version.
