### ISSUE TITLE
[Question] Edit Stored Telemetry String

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7744]
* UI
**Description**
A string (name) is added to the telemetry data by the user, problem is they could make a mistake when entering it.
So the string would need to be editable in the dashboard.
I'm not asking to send a new name with a new timestamp but update an existing one.
In the 'row-action' I can create a pop-up to edit one key (string) of a row in the timeseries data table.
The idea is to read the string and save it again with the same timestamp.

Is it even possible to get and provide the timestamp to save it?
Anyone with example code?
The enter telemetry string input widget isn't really helpful.

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard: PE 3.3.3

**Comment by devaskim** [comment]
Did you try to push the same key and the same timestamp but with updated value via `attributeService.saveEntityTimeseries()`

**Comment by KenSense** [comment]
That's the plan but I don't know the syntax for saving with timestamp.

**Comment by devaskim** [comment]
[API link](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts#L93)

Github provides [file search](https://github.com/thingsboard/thingsboard/find/master). Format of each UI service name is [feature].service.ts

**Comment by KenSense** [comment]
> [API link](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts#L93)
> 
> Github provides [file search](https://github.com/thingsboard/thingsboard/find/master). Format of each UI service name is [feature].service.ts

I don't see a timestamp field?

**Comment by devaskim** [comment]
It is in [AttributeData ](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L89)

**Comment by KenSense** [comment]
> It is in [AttributeData ](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L89)

ah ok, will try that, thanks.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
