### ISSUE TITLE
[Question] Update 3.3.4.1 -> 3.4

### ISSUE THREAD

**Issue by Wifialarm** [thingsboard/thingsboard#7748]
- Installation/Update

Description
Tried/Failed update 3.3.4.1 -> 3.4 following instruction [https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-34](url)
Assume that fault came after executing sudo dpkg -i thingsboard-3.4.deb where default choice is N (keep existing thingsboard.yml). Then after executing regular script sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.3.4 came to error:
:: ThingsBoard ::       (v3.4.0)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'sqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'baseRuleChainService': Unsatisfied dependency expressed through field 'ruleChainValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'ruleChainDataValidator': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'tenantServiceImpl': Unsatisfied dependency expressed through field 'customerService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'customerServiceImpl': Unsatisfied dependency expressed through field 'assetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'baseAssetService': Unsatisfied dependency expressed through field 'assetValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
 Error creating bean with name 'assetDataValidator': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException:
 Error creating bean with name 'tenantServiceImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
ThingsBoard upgrade failed!

How it is intended to perform merge: "NOTE: Package installer may ask you to merge your thingsboard configuration. It is preferred to use merge option to make sure that all your previous parameters will not be overwritten."?

How it is possible to proceed with update?

Thanks in advance

* OS:  Ubuntu 22.04
* ThingsBoard: 3.3.4.1

**Comment by den1jkee** [comment]
Hi,
If a new version of ThingsBoard offers to update .conf, .yml, .XML, it is better to agree, as each new version adds new features and changes, and it will also allow you to avoid such errors when upgrading in the future.
It is better to backup old configurations before upgrading and, if necessary, transfer the configuration to the new one from the old one.
Best regards,
Denys.
