### ISSUE TITLE
[Bug] Modbus cannot issue rpc about continuous registers

### ISSUE THREAD

**Issue by lljy233333** [thingsboard/thingsboard#7749]
**Describe the bug**
First at all, I read and write individual registers successfully. But when I use the modbus gateway to issue the rpc command to write continuous registers, the program does not report an error, but the device registers do not change.

**Your Server Environment**

* demo.thingsboard.io
* own setup
  * docker deployment
  * ThingsBoard Version:3.4.2
  *  ThingsBoard IOT Gateway Version:3.2
  * OS Name and Version:Windows 11

**Your Client Environment**

**Your Device**

* Connectivity
  * Gateway(modbus)
* modbus slave

**To Reproduce**
1. Go to 'RPC debug terminal'
2. Input ‘setSignalStrength 20’ Then enter
4. The device registers do not change.

**Expected behavior**
The value of the device's register should be changed to the data I input.
![image](https://user-images.githubusercontent.com/53068615/206127844-b9650bf1-930e-4a4d-b4ff-4bed3d4572f6.png)

**Comment by devaskim** [comment]
Use [gateway](https://github.com/thingsboard/thingsboard-gateway/issues) bugtracker

**Comment by devaskim** [comment]
Unfortunately, no. But gateway's team answers as soon as possible.
