### ISSUE TITLE
Database manipulation using Cassandra, optimizations, cleaning routines and data persistence levels 

### ISSUE THREAD

**Issue by eduardonatan** [thingsboard/thingsboard#775]
Hello everyone! I have some questions about the subject described in the title. 

-Is there a way of store the data temporarily in the database, clean routines and etc ? (Using Cassandra). -Can I accesses and manipulate the database with the rule engine or create a plugin for it? Example: receive the temperature of a sensor, if the data is too high or too low, it won't be stored in the DB. Or receive the data and store just an average value in Cassandra, not all the data received.

-Can I use Plugin and Rule engine to: Make levels of data per relevance (one type of device stores data forever, another one just for a month). 

-Is there any way of optimize the process of create users, devices and etc? like import an excel file or something like that. Example: Using Thingsboard in a class, the teacher will have to manually create all the users for each student. 

Thanks in advance, Br

**Comment by eduardonatan** [comment]
This is what I'm doing with Cassandra right now, probably is not the best approach but is working:

The thingsboard does not allow database management through its UI, so, we need to connect directly with the thingsboard DB.

**Query a specific value from a specific device:**

The ts_kv_cf table stores all the telemetry data of all devices and sensors.

entity_id = device id (can be found in thingsboard device UI)
key = name of the data


`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' ALLOW FILTERING;`



**Creating functions to get date/time intervals in cassandra:**

Cassandra does not support arithmetics operations (version 3.11), so it is impossible to do something like “SELECT * FROM thingsboard.ts_kv_cf WHERE ts <= now() - 7d”, to be able to get for example the last 7 days, we need to create a UDF function in Cassandra, using Java. For that:

First, you have to turn on enable_user_defined_functions: true in the conf/cassandra.yaml file.

then create the function:

```
CREATE FUNCTION IF NOT EXISTS thingsboard.timeAgoMinsOrDaysOrMonths(minutes int, days int, months int) 
  CALLED ON NULL INPUT 
  RETURNS timestamp
  LANGUAGE java AS '
    long now = System.currentTimeMillis();

    if (minutes != null)
	  return new Date(now - (minutes.intValue() * 60 * 1000));
    else if (days != null)
	  return new Date(now - (days.intValue() * 86400000));
    else if (days != null)
	  return new Date(now - (months.intValue() * 2629746000L));
    else
	 return new Date(now);
    
  ';

  ';
```
[check this](https://stackoverflow.com/questions/46135576/how-to-do-arithmetics-with-datetimes-in-cql?rq=1)

Note: The function has 3 parameters, you need to decide if you want to use an interval in minutes, days or months, once you decided the other parameters should be passed as null values.  

timeAgoMinsOrDaysOrMonths(minutes,days,months)

**This query returns the last 7 days of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null) ALLOW FILTERING;`

**The same query, but it returns the last 1 month of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,null,1) ALLOW FILTERING;`

**The same query, but it returns the last 10 minutes of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(10,null,null) ALLOW FILTERING;`

**This new function allow us to execute clean routines in the database, for instance, if we want to erase the last seven days of data, we can execute:**

`DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null);`

**if we want to keep just the last 7 days of data and erase everything else:**

`DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts <= timeAgoMinsOrDaysOrMonths(null,7,null);
`
obs: the partition and the entity_type must be used to delete actions on Cassandra (because they form the primary key of the entity). To see all the partitions and be able to use them in the IN clause, you need to query the ts_kv_partitions_cf table.

Hope that helps

**Comment by ashvayka** [comment]
Hi @eduardonatan . This is a valid idea and we may use UDF to speed up some queries in the future. The only downside is that user installation instructions will be more complex.

**Comment by dixon1e** [comment]
It's a helpful pattern with Cassandra clusters to reserve read-only analytics for non-write servers that shadow the data. Here's an idea instead of UDFs. 

An analytics system could be very easy to install using containerized slaves and regularly exporting shadow data. Be open in which databases to export to, e.g. Postgres, where others may create and manage well understood analytics. Make it containerized in your favorite way.

**Comment by guodaxia103** [comment]
Thank you for sharing your experience.

**Comment by ajithkumar222** [comment]
how to get above 5k records in thingsboard cassandra using nodejs?

**Comment by arpitsaxena599** [comment]
how bout if i create a new table in cassandra db in thingsboard keyspace where the 2 tables (ts_kv_cf and ts_kv_partitioned_cf) already resides?? and i redirect telemetry data in that for uniform way, can i do that??
even i mentioned new table name and Columns and field name still all telemetry going to (ts_kv_cf) by default, i want my data in other table in uniform way, i show u my scenerio,
![image](https://user-images.githubusercontent.com/106302779/193200829-28a932f3-a38c-456f-b84b-9a86dfc81783.png)
![Uploading image (6).png…]()
data is coming in a very bad way, even columns are not according to me, so i need data to store in a  new table

**Comment by Ultrazombie** [comment]
Closed due to inactivity
