### ISSUE TITLE
[Question] How can i check if deviceName from incoming message exists in devices?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7753]
**Component**

 * Rule Engine
 * Generic

**Description**
Hi, i wouldlike to know if there is a way from the rule-chain (except api cause if i do a request, i lose the previous node's msg information) to check if incoming (from mqtt integration) deviceName already exists in the Devices section (if i already have create a device with this name)

**Environment**

 * OS:  Linux
 * ThingsBoard: Latest 3.4.2
 * Browser: Mozilla

**Comment by PanGian97** [comment]
Hmm, I hoped there was an other way, but thanks, hadn't thought to make it
a Json so it will take only one field (I already have a lot there).
Thanks for the note

**Comment by liotys** [comment]
Hi,
may be you can try combine "create relation" node using $[messageKey] to create a link with an existing device with the same name. Then try to get "related attribute" Name. If not empty then the device exists. Don't forget to "delete relation".

**Comment by LukaszDuss** [comment]
In v3.5.0 "CREATE RELATION" node has option to create entity making this solution works like a charm. Thanks :)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
