### ISSUE TITLE
Created Custom Widget its working in 4200 but not in 8080 port

### ISSUE THREAD

**Issue by akashchavda** [thingsboard/thingsboard#7754]
**Component**

 * UI

**Description**
I have created custom widget for switch
switch is one component `tb-switch` and that i am using in this custom widget
in this component i am using angular material tag `mat-slide-toggle`
When i am open localhost:4200 at that time that custom widget showing properly
![Screenshot_22](https://user-images.githubusercontent.com/50907236/206196880-f4ca0585-3eed-4783-ba34-d68baa67bf80.png)
but when i am open localhost:8080 at that time its showing
![Screenshot_21](https://user-images.githubusercontent.com/50907236/206196954-940b3e30-0fd2-4091-bab1-d3d6fed07268.png)
can you please tell me what i am missing?

**Environment**

 * OS:  Ubuntu and 20
 * ThingsBoard: 3.4.1
 * Browser: Chrome and  108.0.5359.94

**Comment by devaskim** [comment]
Could you provide an export file of your widget?

**Comment by akashchavda** [comment]
this is from localhost:8080
[localhost-8080-widget.txt](https://github.com/thingsboard/thingsboard/files/10183102/localhost-8080-widget.txt)
this is from localhost:4200
[localhost-4200-widget.txt](https://github.com/thingsboard/thingsboard/files/10183109/localhost-4200-widget.txt)
JSON is not supported in comment so i converted to text file

**Comment by akashchavda** [comment]
no any errors in console

**Comment by devaskim** [comment]
Yes. 
Try to clear browser cache for localhost:8080

**Comment by akashchavda** [comment]
I tried both
1. clear browser cache
2. in incognito mode
both page localhost:8080 is not working

**Comment by trikimiki** [comment]
Can you confirm this is fixed now?
