### ISSUE TITLE
Question: Is there a schedule for when Thingsboard cloud version is upgraded? 

### ISSUE THREAD

**Issue by merrittholmes7** [thingsboard/thingsboard#7755]
Is there a schedule to say when following a new release, thingsboard cloud will be updated?

It seems logical that you would want to give existing users some warning.

Thanks

Mike

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
