### ISSUE TITLE
[Question] How to properly call the APIs available in a widget? Use of $scope.$injector or not?

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7756]
**Component**

 * Generic

**Description**
In many examples from TB I see that they call the different APIs using `$scope.$injector;`, for example:
```
let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
```

But I can see that the same API can be used directly as this:
```
widgetContext.customDialog()
widgetContext.attributeService()
```

What is the difference and what is the correct/best away to call the API?

**Environment**

 * OS:  macOS
 * ThingsBoard: PaaS (PE in the Cloud)
 * Browser: Chrome

**Comment by devaskim** [comment]
It is the same. But [still not all services](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts#L70-L90) are accessible via short form.

**Comment by Civilduino** [comment]
Thanks for the answer.
