### ISSUE TITLE
[Question] How can i have a production enviornment and a development environment under the same Thingsboard licence?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7764]
**Component**

 * Generic

**Description**
I want to have under the same licence a production and a development instance. According to what i found out i can't own multiple instances under the same licence key, so my though is, can i have a second Postgre DB on a different container and attach each one of 2 on preference? Would this work as i imagine? 

Hope there is a simpler way around though.

**Environment**

 * OS:  Linux
 * ThingsBoard PE: 3.4.2
 * Browser: Mozilla

**Comment by den1jkee** [comment]
Hi,
You can add a new instance if your instance counts more than 1 according to your license key on the license portal.
![image](https://user-images.githubusercontent.com/113901187/206706673-cccd307f-cd71-4121-89b6-6fd5880148cb.png)
The license key is not stored in the database, so you can safely duplicate your database for a new instance.
Also, according to your license key ThingsBoard instance receives a unique instanceID and if you wish to duplicate your instance they will not start if your instance count  = 1.
Watch this video if you wish to buy a new license key with multiple instances.
[ThingsBoard Professional edition: How to purchase a subscription type license?](https://youtu.be/dK-QDFGxWek?t=108)
[How-to get pay-as-you-go subscription](https://www.youtube.com/watch?v=dK-QDFGxWek) or [How-to get perpetual license](https://www.youtube.com/watch?v=GPe0lHolWek) 
Thank you!
Best regards,
Denys.
