### ISSUE TITLE
Widget data not being displayed for some user types

### ISSUE THREAD

**Issue by michaelrfeld** [thingsboard/thingsboard#7765]
**Component**

 * UI

**Description**

I am struggling with multi-tenancy and roles. I followed the documentation and set up one of the use cases, which ends rather abruptly after setting up users.  Here is the page of documentation I followed:

https://thingsboard.io/docs/pe/user-guide/rbac/#roles

I have a dashboard that I have imported that can be seen by an administrator user (please ignore the data, it's not accurate):

<img width="1389" alt="Screenshot 2022-12-08 at 2 00 06 PM" src="https://user-images.githubusercontent.com/62682570/206544778-2235245d-e25c-4de7-bdf0-1d6a6430f780.png">

But neither of the users I have created are able to see the data. Here is a screenshot of what they are seeing:

<img width="1643" alt="Screenshot 2022-12-08 at 2 00 52 PM" src="https://user-images.githubusercontent.com/62682570/206547095-64472bde-4a3b-4bcd-a246-4f332a866e20.png">

The dashboard was set up for a particular customer.  This is obviously some sort of a permissions issue, but I am not sure where these permissions are set and what permissions to change. I have attempted to share the entity group of dashboards with specific customers in the following preference modal:

<img width="550" alt="Screenshot 2022-12-08 at 2 25 05 PM" src="https://user-images.githubusercontent.com/62682570/206548845-6cc838b9-28de-402c-b2ea-c76c6860e8e0.png">

While "All Users" is checked and one would think that everyone could see it, I am unable to make changes to this and specify customers. Any changes I make are not saved and when I go back in, it looks exactly as it does in the above screenshot.

Any guidance on how to allow this user to view the data on this dashboard would be greatly appreciated. I've been going around and around for awhile and am unable to resolve it. 

Thank you.

Michael

**Environment**

 * OS:  MacOS
 * ThingsBoard: 3.4.1PE
 * Browser: Various, including Brave, Safari, and Chrome

**Comment by OKhalkov** [comment]
Hello @michaelrfeld ,
I guess that you also need to give permission to access devices and their telemetry for customers, because customers see dashboard but without data

**Comment by michaelrfeld** [comment]
Thanks, much appreciated, but that doesn't seem to be the issue. Here are the permissions for the role assigned to this user, some of which are probably redundant (I added the device permissions in response to your comment):

<img width="783" alt="Screenshot 2022-12-09 at 12 27 55 PM" src="https://user-images.githubusercontent.com/62682570/206759181-df2d6f65-9e8f-4482-85b4-ac334dbe22be.png">

<img width="770" alt="Screenshot 2022-12-09 at 12 28 14 PM" src="https://user-images.githubusercontent.com/62682570/206759210-1ed7fbd1-a8fd-43b3-8b7a-30c359bbe83d.png">

Still not working. Any further thoughts and suggestions are appreciated.

**Comment by kastayou** [comment]
Where are the devices created? at tentant level or at customer level?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
