### ISSUE TITLE
[Question] What is the right way to pass from Prototype Subscription plan to Maker Subscription plan ? 

### ISSUE THREAD

**Issue by lartsick74** [thingsboard/thingsboard#7769]
Hello,

I would like to know if it is possible to "downgrade" my Thingsboard subscription ? 
If so, will I be able to pass from the prototype subscription plan to maker subscription if I delete all the exceeding devices, assets, rule chains and customer etc.. and then I update plan ?
Thank in advance for your answer,
Lucas

**Comment by den1jkee** [comment]
Hi,
Yes, your workflow is correct. After deleting all the exceeding devices, assets, rule chains, etc., you can update your plan to lower your subscription.
Here you can see the subscription limits.
[ThingsBoard Cloud Subscription plans definition](https://thingsboard.io/products/paas/subscription/)
Best regards,
Denys.
