### ISSUE TITLE
[Feature Request] Add the "disable zooming" setting in chart-widgets

### ISSUE THREAD

**Issue by geronimo-ua** [thingsboard/thingsboard#7771]
Currently, the chart’s widget by default has the ability to zoom in and out. But there is no way to disable this option in the advanced settings.
![image](https://user-images.githubusercontent.com/118526734/206695525-28c4b33d-da4d-4ab6-823c-93bee068d315.png)

**Describe the solution you'd like**
Add an option that allows excluding the possibility of zooming on the charts.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
