### ISSUE TITLE
[Feature Request] Originator-label field for alarm-widget

### ISSUE THREAD

**Issue by geronimo-ua** [thingsboard/thingsboard#7772]
Currently, the alarm widget has a limited list of default values of Alarm data keys. 
![image](https://user-images.githubusercontent.com/118526734/206695939-02d7b5c1-a3ad-4984-ba9c-9c31b2af7aa2.png)

**Describe the solution you'd like**
Add a new default value for the alarm field - “originatorLabel”.

**Comment by sprijk** [comment]
Also in the Notification Template for Alarms the ${originatorLabel} comes in very handy, as an end user would not have to look at the ${originatorLabel}, which could be a serial number the user would not recognize.

**Comment by sumin-denys** [comment]
Hi @geronimo-ua,

I am glad to inform you that this possibility has already been added to the current ThingsBoard version.
I am closing this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).

**Comment by sprijk** [comment]
hey @geronimo-ua  that sound terrific!
where is that info about caputring the originator label? I can not find anything in the linked release notes

**Comment by sprijk** [comment]
@sumin-denys great!

is it also possible to capture the label of the alarm's originator in an notification email template?

**Comment by sumin-denys** [comment]
Hi @sprijk,
 
This is a valid improvement that is already present in our backlog PROD-2276, but at the moment, there are no timeframes for its implementation.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
If you have any further questions or require clarification, please let me know.
