### ISSUE TITLE
 How to use DeviceProfileService object in Rule Engine

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7776]
**Component**

 * Rule Engine

**Description**
1. According to the source code, it is known that there is no Device ProfileService in the DbContext interface
2. If the CRUD operation of DeviceProfile is done through Rule Node, what is the best way

**Environment**

 * OS:  windwos
 * ThingsBoard: 3.4.0
 * Browser: chrome

**Comment by ashvayka** [comment]
@dashevchenko , please add the DeviceProfileService to TbContext in 3.4.3.
@struggle3 , please make sure you will be calling the TbContext.getClusterService() and broadcasting the following events:
```
            tbClusterService.onDeviceProfileChange(savedDeviceProfile, null);
            tbClusterService.broadcastEntityStateChangeEvent(tenantId, savedDeviceProfile.getId(),
                    actionType.equals(ActionType.ADDED) ? ComponentLifecycleEvent.CREATED : ComponentLifecycleEvent.UPDATED);
```

**Comment by struggle3** [comment]
> @dashevchenko , please add the DeviceProfileService to TbContext in 3.4.3. @struggle3 , please make sure you will be calling the TbContext.getClusterService() and broadcasting the following events:
> 
> ```
>             tbClusterService.onDeviceProfileChange(savedDeviceProfile, null);
>             tbClusterService.broadcastEntityStateChangeEvent(tenantId, savedDeviceProfile.getId(),
>                     actionType.equals(ActionType.ADDED) ? ComponentLifecycleEvent.CREATED : ComponentLifecycleEvent.UPDATED);
> ```

Thank you for your reply, I have seen the relevant code of DeviceProfileService in 3.4.3, and the next version is currently undergoing an upgrade trial

**Comment by struggle3** [comment]
Thank you for your reply, I have seen the relevant code of DeviceProfileService in 3.4.3, and the next version is currently undergoing an upgrade trial
