### ISSUE TITLE
 How to use DeviceProfileService object in Rule Engine

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7777]
**Component**

 * Rule Engine

**Description**
1. According to the source code, it is known that there is no Device ProfileService in the DbContext interface
2. If the CRUD operation of DeviceProfile is done through Rule Node, what is the best way

**Environment**

 * OS:  name and windows
 * ThingsBoard: 3.4.0
 * Browser: chrome

**Comment by vvlladd28** [comment]
Dublicate #7776
