### ISSUE TITLE
[Question] how to manage the license

### ISSUE THREAD

**Issue by BluRanger** [thingsboard/thingsboard#7796]
**Component**

 * License

**Description**
need to understand how the license will be maintained as i have single instance pe license and when ever my pod goes down ! boom its down untill i refresh the lisence active instance. this is causing a downtime ! is there any option that i am missing ?

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by AlexDoanTB** [comment]
Hi @BluRanger,

To avoid downtime, you need extra instance(s) available on your license key. The licensing is instance-based. With a regular license key, once the license activates your pod, another pod with tb-core will not be up and running after k8s' automatic eviction of an unhealthy pod unless you manually unbundle the key on the License portal.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
