### ISSUE TITLE
How can i get the value of the knob widget?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7798]
**Component**

 * UI

**Description**
I have made an action on a knob widget that basically throws a pop-up window to verify the position and send rpc command (so the user has to click on action widget after putting the knob in the right place to verify rpc command).
My question is, where exactly is the value of the knob accessible inside so i can reach from inside the custom action javascript code?
i have tried to find it inside the widgetContext.$scope object, but was too big to analyse and find the value, maybe i need to look somewhere else.

**Environment**
Thingsboard PE instance
 * OS: linux
 * ThingsBoard: 3.4.2
 * Browser: mozilla

**Comment by devaskim** [comment]
```
    el = $('.knob-value', widgetContext.$container);
    console.log('Init: ', el.text());
```

**Comment by PanGian97** [comment]
Exactly what I needed, thanks a lot!!
Btw could you explain what $() command actually is? I have no clue about
Angular

**Comment by devaskim** [comment]
It is call of API provided by [JQuery JS library](https://jquery.com/).
`$('.knob-value', widgetContext.$container)` means find HTML element with CSS class `.knob-value` in jquery-field HTML element called `$container`

**Comment by PanGian97** [comment]
Thanks again, you saved my day

**Comment by PanGian97** [comment]
Coming back to this for the reason that i'm struggling now to get the value of the switch widget, this answer you mentioned works for knob cause the value is displayed on the widget, i can't do the same on switch widget:(

**Comment by devaskim** [comment]
Use browser Dev Tools (*Elements* tab) to find HTML element where widget stores and display its value. Then re-use code from [my previous answer](https://github.com/thingsboard/thingsboard/issues/7798#issuecomment-1353108870)

**Comment by PanGian97** [comment]
the problem is that this widget has both on-label and off-label classes with each one having the coresponding value. It's only hiding them depending on the switch state, i really can't find an easy way doing it

**Comment by devaskim** [comment]
You need to [check](https://www.geeksforgeeks.org/how-to-check-an-element-has-certain-css-style-using-jquery/) whether CSS `display` property is `none` for one of this label-element: 
`$('.on-label', widgetContext.$container).css('display') === 'none'`

**Comment by PanGian97** [comment]
Thereis no "display" property in on-label css, only [fxShow]="value" on html and [fxShow]="!value" for off-label instead

**Comment by devaskim** [comment]
> Thereis no "display" property in on-label

Really?

![Скриншот 19-12-2022 201016](https://user-images.githubusercontent.com/86909129/208457357-3d24ce68-1f00-4bfb-8017-676c0ff4a568.jpg)

**Comment by devaskim** [comment]
`[fxShow]` is syntax sugar of  Angular JS that will be converter to plain CSS properties such `display` or something else. No magic)))

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
