### ISSUE TITLE
Can you upgrade angular to the latest version?

### ISSUE THREAD

**Issue by UNIQUEXJ** [thingsboard/thingsboard#780]

**Comment by mfalkvidd** [comment]
Related to https://github.com/thingsboard/thingsboard/issues/735

**Comment by untilbit** [comment]
@mfalkvidd  do you have plans for upgrading the frontend to angular 6 for next versiom?

**Comment by mfalkvidd** [comment]
@untilbit me personally? No.

**Comment by untilbit** [comment]
I meant if it's going to be upgraded by some of the members TB team?

**Comment by mfalkvidd** [comment]
@untilbit I dont know.

**Comment by untilbit** [comment]
Ok.

**Comment by mp-loki** [comment]
Angular is way too different between versions 1 and 2+. Upgrading Angular would mean we need to rewrite the whole UI. I don't think it's on the plate right now.

**Comment by preservance717** [comment]
After a year, and it's 2019.
Do you have plans for upgrading the frontend to angular 6 for next versiom?

**Comment by itea-dev** [comment]
Started a new project for this purpose: https://github.com/itea-dev/ng-thingsboard

Let's build a new Angular 2+ app for Thingsboard.
