### ISSUE TITLE
How can i get the value of an attribute from getValue rpc call from knob widget?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7805]
**Component**

 * Rule Engine

**Description**
I have a knob widget that sends getValue command to initialize (by default) i want to access an attribute and return it's value to the getValue params. Why can't it be like the switch widget where it can take the value of an attribute instead of rpc getValue method? I would like to skip the custom widget option for now (except if you have a plug and play solution:P ).
I tried so far to use the rule engine node "rpc call reply" but i get "Service id is not present in the metadata!", i guess it's cause the input doesnt come from a device.

If you have any idea of a simple way please mention, thanks!

**Environment**

 * OS:  LINUX
 * ThingsBoard: 3.4.2
 * Browser: firefox

**Comment by devaskim** [comment]
You need `RPC call request` node to get response from device

**Comment by PanGian97** [comment]
That's the thing, i dont want any "response" from any device, i just want the knob widget to take the value of an attribute on "getValue" method. With call rpc request as i understand you send a request to a device outside of thingsboard

**Comment by devaskim** [comment]
Just to re-check, you don't need RPC request to device but you need to update device or asset attribute with the help of this widget?

**Comment by PanGian97** [comment]
I need the widget to initialize its value according to an attribute of a device. if i could i would prevent it from making getValue.setValue calls completely.

The idea is, i have a knob widget that when i move irt to a position i press a custom action on the widget and it sends RPC command, then it goes to rulechain where i have put a downlink node. As for the initial value of the knob widget, i want it as i said to take as value the value of an attribute.

I tried to manipulate it through rule chain but couldnt

**Comment by devaskim** [comment]
It is impossible with current implementation of knob widget

**Comment by devaskim** [comment]
Well, I didn't test, but every `RPC Request to Device` event includes `requestUUID` and `originServiceId` in its metadata. So you could catch up the event, make some modification and return back in `RPC call reply` node.

**Comment by PanGian97** [comment]
Which fields exactly should i include inside of metadata to reply back to the widget?

**Comment by devaskim** [comment]
I don't know exactly, but you could make [small test](https://thingsboard.io/docs/reference/mqtt-api/#server-side-rpc) (see *mqtt-js-rpc-from-server.js*) with enabled debug mode in rule chain. In this way you, I will get all necessary fields, for sure.

**Comment by PanGian97** [comment]
Thanks i will try!

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by solodayi** [comment]
Hi, could you get the widget updated with the value of your attribute?
