### ISSUE TITLE
[Question] How to receive the device attributes and telemetry data and change them

### ISSUE THREAD

**Issue by e-infotech** [thingsboard/thingsboard#7808]
Hi,
I have TB on my local computer and I created some sensors whose data comes from a CSV file and I defined some attributes for the sensors. What I want to do is to use python and get the attributes from the sensor and change them if they are based on a condition. For example, if the sensor location(attribute) is X change the Xattribute to Yes.
Also, I want to check some conditions based on the measurement data. If light> X decrease the light.

Can anyone help me with these scenarios?

**Comment by devaskim** [comment]
You could do this on a server side with the help of Rule Engine. Just listen to `Post attributes` and `Attributes update` rule chain events. then compare to your threshold values and modify values (`Script` rule node) and save again to database (`Save attribute` node)

With python implementation you need to implement polling to get up-to-date attribute values. Otherwise, you could use [WebSocket API](https://thingsboard.io/docs/user-guide/telemetry/#websocket-api)

**Comment by e-infotech** [comment]
> You could do this on a server side with the help of Rule Engine. Just listen to `Post attributes` and `Attributes update` rule chain events. then compare to your threshold values and modify values (`Script` rule node) and save again to database (`Save attribute` node)
> 
> With python implementation you need to implement polling to get up-to-date attribute values. Otherwise, you could use [WebSocket API](https://thingsboard.io/docs/user-guide/telemetry/#websocket-api)

Thank you. Can you please elaborate a little more? Because I want to do it for several attributes and it should be automatic. I don't want to change every time. I just want to enter the new values and the change be done automatically

**Comment by devaskim** [comment]
Well, if you are not familiar with Rule Engine, you have to read [Getting Started](https://thingsboard.io/docs/user-guide/rule-engine-2-0/re-getting-started/). Then I would try to answer on your questions, otherwise I need to explain a lot.

**Comment by e-infotech** [comment]
No, I am familiar with rule engine.

**Comment by devaskim** [comment]
> Can you please elaborate a little more?

> No, I am familiar with rule engine.

So what in unclear for you in that part of [my previous answer](https://github.com/thingsboard/thingsboard/issues/7808#issuecomment-1356377795) what relates to Rule Engine?

**Comment by e-infotech** [comment]
Should I look for "Post Attribute" and "Attribute update" nodes in the rule engine? I am using version 2.4.3 and I don't have those nodes in my rule engine.

**Comment by devaskim** [comment]
`Post Attributes` and `Attribute update` are links of `Message Type Switch` node. The former notifies you about attributes that have been posted by device, the latter means update via dashboard and some other cases.

Usual case is to link `Post Attributes` (not node) with `Save attributes` node and then link the latter with others nodes such as `Script` (in your case) to check which exactly attributes have been updated and what server should do next.

**Comment by devaskim** [comment]
I use `Filter - switch` to provide distinct processing logic to each updated attribute

![updates](https://user-images.githubusercontent.com/86909129/208522982-06bac468-4450-4ef6-92d8-e908e1ad1b5e.jpg)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
