### ISSUE TITLE
AWS trial Account 

### ISSUE THREAD

**Issue by belalmc** [thingsboard/thingsboard#781]
Hi , I've installed PE (trial) on AWS EC2 but the default credentials on this page
 https://thingsboard.io/docs/samples/demo-account/
 are not working

**Comment by simonlim** [comment]
you need to open custom TCP 8080 port. My case.  it works.

**Comment by vparomskiy** [comment]
You can use this detailed description how to configure it from aws marketplace 
https://thingsboard.io/docs/user-guide/install/aws-marketplace-pe/
