### ISSUE TITLE
How do you auto zoom maps marker on Thingsboard?

### ISSUE THREAD

**Issue by zidniryi** [thingsboard/thingsboard#7810]
**Component**

 * UI

**Description**
So I have 2 Table widgets and a Maps Widget on the Thingsboard, when I click an item in the list table, I want the maps to auto zoom to the marker in the second Maps Widget on the Thingsboard?

How to auto zoom on Maps Thingsboard with type openstreetmaps?

I mean How to do like this in thingsboard? [Auto Zoom Openstreet Maps Exmaple](https://openlayers.org/en/latest/examples/animation.html)

**Environment**

 * OS:  MacOS Monterey 12.6.1
 * ThingsBoard: version 3.4.1
 * Browser: Chrome version Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by liotys** [comment]
Hi,
I guess you will be able to filter the map widget according to your selection. Nevertheless, it will be difficult to zoom automatically. You will probably have to click on a button in the map widget. See  #6518 for more informations.

**Comment by devaskim** [comment]
Recently I started to use `broadcastService` to pass data from one widget to another. Such approach helps me implement more flexible navigation without TB Filter feature.
So once a user clicks on a row you (@zidniryi) could send broadcast event with selected entity (means to use custom action). Then clone existing OpenStreet map widget and add to `onInit` callback a brodcast-event listener. Once map widget gets the click-event, you could re-use code (with some modifications) suggested by @liotys to auto zoom.

**Comment by zidniryi** [comment]
> Hi, I guess you will be able to filter the map widget according to your selection. Nevertheless, it will be difficult to zoom automatically. You will probably have to click on a button in the map widget. See #6518 for more informations.

I see the solution you send in another:

But how to access my object maps in thingsboard?


```
let currentInstance = widgetContext.mapInstance;

if (currentInstance.markers.size>0) {
  var bounds = currentInstance.bounds;
  bounds._northEast.lat=bounds._southWest.lat=currentInstance.markersData[0].latitude;
  bounds._northEast.lng=bounds._southWest.lng=currentInstance.markersData[0].longitude;
  currentInstance.markers.forEach((marker) => {
    bounds.extend(marker.leafletMarker.getLatLng());
    });
    currentInstance.fitBounds(bounds);
    currentInstance.map.panTo(bounds.getCenter());
}
```

I got undefined . Should I define in **wiget** or in **dashboard**?

**Comment by zidniryi** [comment]
> Auto Zoom Openstreet Maps Exmaple

Soo you mean [[Zoom](https://openlayers.org/en/latest/examples/animation.html)](https://openlayers.org/en/latest/examples/animation.html) for creating like this is not posible in Thingsboard right.

**Comment by zidniryi** [comment]
> Hi, I guess you will be able to filter the map widget according to your selection. Nevertheless, it will be difficult to zoom automatically. You will probably have to click on a button in the map widget. See #6518 for more informations.

> Auto Zoom Openstreet Maps Exmaple

Soo you mean [[Zoom](https://openlayers.org/en/latest/examples/animation.html)](https://openlayers.org/en/latest/examples/animation.html) for creating like this is not posible in Thingsboard right.

**Comment by liotys** [comment]
I've found a way to automatically resize the map...
Create a group of widget. Create a copy of the openstreetmap widget in the group created.
In the copy modify the method:
```
self.onDataUpdated = function() {
    self.ctx.map.update();
    let currentInstance = self.ctx.mapInstance;

    if (currentInstance.markers.size>0) {
      var bounds = currentInstance.bounds;
      bounds._northEast.lat=bounds._southWest.lat=currentInstance.markersData[0].latitude;
      bounds._northEast.lng=bounds._southWest.lng=currentInstance.markersData[0].longitude;
      currentInstance.markers.forEach((marker) => {
        bounds.extend(marker.leafletMarker.getLatLng());
        });
        currentInstance.fitBounds(bounds);
        currentInstance.map.panTo(bounds.getCenter());
    }
}
```
It seems to work.

**Comment by zidniryi** [comment]
> > I see the solution you send in another:
> > But how to access my object maps in thingsboard?
> > ```
> > let currentInstance = widgetContext.mapInstance;
> > 
> > if (currentInstance.markers.size>0) {
> >   var bounds = currentInstance.bounds;
> >   bounds._northEast.lat=bounds._southWest.lat=currentInstance.markersData[0].latitude;
> >   bounds._northEast.lng=bounds._southWest.lng=currentInstance.markersData[0].longitude;
> >   currentInstance.markers.forEach((marker) => {
> >     bounds.extend(marker.leafletMarker.getLatLng());
> >     });
> >     currentInstance.fitBounds(bounds);
> >     currentInstance.map.panTo(bounds.getCenter());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I got undefined . Should I define in **wiget** or in **dashboard**?
> 
> It's an action in the maps widget.

But I want do that from another widget which I have two widget. Table Widget with search and Maps widget. When I press in Table widget the second widget which is Maps with marker. When I click data on the 1st widget the 2nd widget maps data zoom.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
