### ISSUE TITLE
[Bug] ThingsBoard PE Dashboard export gives image of login screen not dashboard

### ISSUE THREAD

**Issue by koldbrandt** [thingsboard/thingsboard#7813]
**Describe the bug**
When exporting a dashboard to pdf, jpg, jpeg you just get an image of the login screen, and not the dashboard. 
The latest version that I have seen it work on was v3.3.4.1PE. 

**Server Environment**
cloud 
ThingsBoard Version: 3.4.2pe
Linux (ubuntu 20.04)

**Client Environment**
Windows 11
Chrome, edge, firefox

**To Reproduce**
1. Go to a dashboard 
2. Click export dashboard 
3. Choose pdf, png or jpeg. 
4. See that it hasn't exported the dashboard but an image of the login screen 

**Expected behavior**
Export of an image of the dashboard. 

**Additional context**
I have updated the thingsboard version. Could this probably be a problem only for when updating the version?

**Comment by liotys** [comment]
Hi, for me it works (I have the same setup as you - 3.4.2PE upgraded from 3.3.4.1) with Edge or Chrome. Is there any message in the log of the server?
