### ISSUE TITLE
dockerfile build image

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7814]
**Component**

 * Generic

**Description**

Hello: thingsboard team, I tried to build my own docker image, but failed to use docker build on centos, please give me some pointers on the relevant steps

Error response from daemon: lstat start-tb-node.sh: no such file or directory
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream
![image](https://user-images.githubusercontent.com/19941827/208415838-e1707ff2-46f8-4011-958a-991e25ca3a14.png)
![image](https://user-images.githubusercontent.com/19941827/208415910-233e3488-e52c-426f-9030-8cad2f1069cf.png)

1、How to build a docker image or Microservice from the thingsboard source code
2、Does the Microservice in the mas directory have build instructions?

**Environment**

 * OS:  centos
 * ThingsBoard: 2.4.2
 * Browser: none

**Comment by devaskim** [comment]
I am building Docker image with
```
mvn clean install -DskipTests -Dlicense.skip -Ddockerfile.skip=false
```

**Comment by struggle3** [comment]
> I am building Docker image with
> 
> ```
> mvn clean install -DskipTests -Dlicense.skip -Ddockerfile.skip=false
> ```

Compile directly in terminal? It seems that this has nothing to do with Docker?

**Comment by devaskim** [comment]
Yes, in terminal and from the root project directory.

**Comment by struggle3** [comment]
> Yes, in terminal and from the root project directory.

Okay thank you!
But my current development environment is under windows, and the docker is in the centos of VMware Workstation Pro. If you compile the project like this, you should not be able to generate the image into the docker.

**Comment by struggle3** [comment]
> > Yes, in terminal and from the root project directory.
> 
> Okay thank you! But my current development environment is under windows, and the docker is in the centos of VMware Workstation Pro. If you compile the project like this, you should not be able to generate the image into the docker.

There is an error as shown in the figure
![image](https://user-images.githubusercontent.com/19941827/208430373-4b5a58e7-cc91-4dbc-ae5c-621293e6bd39.png)

**Comment by devaskim** [comment]
> But my current development environment is under windows, and the docker is in the centos

I am building on windows and running on Ubuntu and no problems.

**Comment by devaskim** [comment]
Error from screenshot means that docker is not running on your build machine

**Comment by struggle3** [comment]
> > But my current development environment is under windows, and the docker is in the centos
> 
> I am building on windows and running on Ubuntu and no problems.
> 
> > There is an error as shown in the figure
> 
> Error from screenshot means that docker is not running on your build machine

Ok, thanks for your reply.

**Comment by hoangchuong12** [comment]
> > > Yes, in terminal and from the root project directory.
> > 
> > 
> > Okay thank you! But my current development environment is under windows, and the docker is in the centos of VMware Workstation Pro. If you compile the project like this, you should not be able to generate the image into the docker.
> 
> There is an error as shown in the figure ![image](https://user-images.githubusercontent.com/19941827/208430373-4b5a58e7-cc91-4dbc-ae5c-621293e6bd39.png)

I want to know when everything is done, what to do next to run thingsboard from the cloned source code
