### ISSUE TITLE
Using multiple widget in single widget

### ISSUE THREAD

**Issue by Vishalbuu** [thingsboard/thingsboard#7817]
Can I create control widget (such as switch) within Latest Values widget. If possible how?

**Comment by devaskim** [comment]
I use custom widget with one or several `tb-dashboard-state` elements in it.
```
<tb-dashboard-state [ctx]="ctx" [syncParentStateParams]="false" stateId="report_daily"></tb-dashboard-state>
```
Some of TB demo dashboards use the same approach but with Markdown widget

**Comment by Vishalbuu** [comment]
Yes, I used similar to demo dashboards and created switch in map widget . I am expecting ON/OFF switch but It is returning [Object Object]. How can I clear it? I have attached my json in below tar.gz file. 
[sensor.tar.gz](https://github.com/thingsboard/thingsboard/files/10268286/sensor.tar.gz)

**Comment by devaskim** [comment]
Re-check content of archive
