### ISSUE TITLE
How Build local docker images

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7818]
**Component**

 * Generic

**Description**
Build local docker images in org.thingsboard.msa: vc executor docker project has no result output in cmd
![image](https://user-images.githubusercontent.com/19941827/208670348-2dca9bb7-c9a1-46e5-b819-daf10370ab53.png)

**Environment**

 * OS:  centos
 * ThingsBoard: 3.4.2
 * Browser: none

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
