### ISSUE TITLE
How can i access the subscribed attribute (init) of a switch widget in custom widget environment?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7819]
**Component**

 * UI

**Description**
I want to make a custom switch widget (cause i need 3 states), as by now, it's pretty simple, just some html,css,js. My question is, how can i access the subscribed attribute value (i chose in the advanced settings to initialize by subscribing to an attribute). I tried to look something inside "self.ctx.defaultSubscription" but couldnt find it

**Environment**

 * OS:  linux
 * ThingsBoard: 3.4.2
 * Browser: Firefox

**Comment by devaskim** [comment]
```
    for (let i = 0; i < self.ctx.data.length; ++i) {
        if (!self.ctx.data[i].data.length) {
            continue;
        }
        
        console.log(`${self.ctx.data[i].dataKey.label} : ${self.ctx.data[i].data[0][1]}`;
    }
```

**Comment by PanGian97** [comment]
"TypeError: self.ctx.data is undefined" is what i get

**Comment by devaskim** [comment]
Well, I copied the code from my working widget from `onDataUpdated` callback, where `self`, `ctx` and `data` are accessible.

**Comment by PanGian97** [comment]
Sorry, I was putting it onInit(), true, it returns an object that I can see
device name but not the attributes :(

**Comment by devaskim** [comment]
If you run your widget from Widget Editor in Widget bundle, you should add fake data in right-bottom section of window.
If you already added widget to dashboard and still cannot see any data, I don't know. All depends on your implementation.

**Comment by PanGian97** [comment]
I will try tomorrow better and come with more details, thanks again, i really appreciate your help!
