### ISSUE TITLE
when exchanging messages between ThingsBoard nodes be changed to using kafka 

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#7821]
as noted in https://thingsboard.io/docs/reference/monolithic/
ThingsBoard authors consider moving from gRPC to Kafka in the future releases for exchanging messages between ThingsBoard nodes. The main idea is to sacrifice small performance/latency penalties in favor of persistent and reliable message delivery and automatic load balancing provided by Kafka consumer groups
so i am wondering when will this feature be released?

**Comment by pon0marev** [comment]
This documentation is outdated. The ThingsBoard has already been using the Kafka queue since version 2.5.X.
