### ISSUE TITLE
How do I clear the help question mark icon?

### ISSUE THREAD

**Issue by abadfasdf** [thingsboard/thingsboard#7825]
![image](https://user-images.githubusercontent.com/108421427/208947957-a2349441-3600-4428-8b6d-d04867400cf2.png)

How do I clear the help question mark icon?

Most of the question marks in the picture above are created in pop-ups. I hate exposing it to clients because it links to the thinsboard site

I've tried editing the CSS to delete it, but there seems to be no way.

**Comment by devaskim** [comment]
> I've tried editing the CSS to delete it

If you are using PE version of TB, there is Advanced CSS in White labeling. Did you try it?
