### ISSUE TITLE
How to modify the widget mobile action so that it could show map direction with multiple destination given with a sets of asset as the input

### ISSUE THREAD

**Issue by Dennis-1121** [thingsboard/thingsboard#7826]
![image](https://user-images.githubusercontent.com/55220981/209054740-7af697b5-3c6a-4ce6-903f-9360f37b9718.png)

Do i need to modify here also?
![image](https://user-images.githubusercontent.com/55220981/209054821-574c8abc-9fc3-4b8d-84e4-00267d36908b.png)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
