### ISSUE TITLE
Empty Response Body after API getTimeseries-Request

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7827]
Hey guys,

I'm trying to get the summed up value for the key 'Leistung'. The problem is that the response body empty after a successfull request:

![grafik](https://user-images.githubusercontent.com/114148912/209138652-f99bf8b5-4f1d-4500-8f5c-f47e840d5f66.png)

I also tried other API Calls to see if there's even any data to access to:

![grafik](https://user-images.githubusercontent.com/114148912/209140079-d8b78922-a962-43db-b3e4-3880f2fc3071.png)

Any ideas how i could solve this problem? I would very much appreciate that!

Greetings
Reno

**Environment**
 * OS: Windows 10
 * ThingsBoard: v.3.4.3 (Demoversion)
 * Browser: Firefox

**Comment by devaskim** [comment]
`startTs` and `entTs` should be in milliseconds

**Comment by callmereno** [comment]
It worked! Thank you so much @devaskim
