### ISSUE TITLE
How to store relational data in custom tables of postgres

### ISSUE THREAD

**Issue by chhn23** [thingsboard/thingsboard#7828]
**Component**
* Rule Engine

**Description**
I am trying to save some relational data into the custom tables which are present in postgres. I came across with "save to custom table" node in rule chain but it says that it is for only cassandra tables.

**Environment**
 * OS: linux
 * ThingsBoard: Professional Edition
 * Browser: chrome

**Comment by trikimiki** [comment]
There is no possibility of doing so out-of-box now. You can create a feature request for this functionality.
