### ISSUE TITLE
[Question] Python rest client, How to get a dashboard Id & how to get a rest client generated dashboard in the hiearchy? PE

### ISSUE THREAD

**Issue by Timmiegamer** [thingsboard/thingsboard#7834]
Hello,

I am trying to make a system in what I can automaticaly assign a dashboard and create a dashboard for a customer in the hiearchy.
But there's also the problem. I can't figure out how to create a dashboard in the hiearchy and how to assign it to a dashboard group.

I have the source code from the Thingsboard documentation (Code in attatchment) In there I can create a dashboard in the all folder of the normal dashboard groups section. But in line 43 it is asking the just created dashboard for a Id to assing it to a group. But it doesn't have a antribute Id...

I've done everything I know to try and fix this but sadly I couldn't find a sollution.

And if anyone knows how to do this and/or get it in the hiearchy I would be happy if you could help me.

Kind regarts,
Tim
[restAPI.txt](https://github.com/thingsboard/thingsboard/files/10293401/restAPI.txt)

**Comment by devaskim** [comment]
TB UI, [Swagger API](https://demo.thingsboard.io/swagger-ui/#/) and Python REST client use the same API. So if you know how to do that in UI, you could open browser's DevTools (*Network* tab), repeat all steps and observe what REST endpoints were called.
