### ISSUE TITLE
How to build docker directly from repository

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#785]
##### I'm trying to build docker directly from develop/1.5 branch but it's not working.

```
sudo docker build https://github.com/thingsboard/thingsboard.git#develop/1.5:docker
```

##### I'm getting the following error:

> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git933149791/docker/Dockerfile: no such file or directory

**Comment by vparomskiy** [comment]
version 1.5 is not valid anymore. Please use the latest version.
https://thingsboard.io/docs/user-guide/install/docker/
