### ISSUE TITLE
ThingsBoard installation on Mac using Docker is giving an error

### ISSUE THREAD

**Issue by suniljadhav** [thingsboard/thingsboard#786]
I am using ThingsBoard Documentation (https://thingsboard.io) to install ThingsBoard application using Docker (Linux or Mac OS) on my Macbook Pro with MacOS High Sierra `(v10.13.4).`

However when I execute the command:
docker-compose up -d tb

I get an error -
ERROR: for tb  Cannot start service tb: b'Mounts denied:
The path /home/docker/hsqldb_volume is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

I tried to update Docker preferences to include /home directory in file sharing but still am getting an error.

Does anybody know how to resolve this issue?

![screen shot 2018-05-16 at 2 17 53 pm](https://user-images.githubusercontent.com/8843970/40107181-31f9be54-5915-11e8-8670-e264585f3a58.png)

**Comment by GaneshVarahade** [comment]
You must edit the .env file (hidden) in the folder where docker is installed, that you've downloaded from the link mentioned in the thingsboard docs UI.

The lines to be edited are for the HSQL DB. 
Change the lines --
# hsqldb environment variables
HSQLDB_DATA_DIR=<path to the folder where you want the docker to create a DB folder and save all the DB related files>
