### ISSUE TITLE
msa build failed

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#7864]
**Component**

 * Installation

**Description**
when i try to build web-ui in msa，it failed：
error An unexpected error occurred: "https://registry.yarnpkg.com/accepts/-/accepts-1.3.7.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com".sometimes this module can't download sometimes that modules can't download

**Environment**

 * OS:  ubuntu20.04
 * ThingsBoard: 3.3.4.1

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
