### ISSUE TITLE
Cannot refresh auth token

### ISSUE THREAD

**Issue by glatorre** [thingsboard/thingsboard#787]
Hello
Using /api/auth/login API I get both token and refreshToken. Which is the correct way to use the refreshToken to renew the token (without use the login API) ? 
Maybe the documentation should explain better this procedure.
Thanks

**Comment by khphillips** [comment]
Same, would like to know how to use the refreshToken

**Comment by khphillips** [comment]
Found the solution here: https://groups.google.com/d/msg/thingsboard/pnMG4lKULJI/Uppx3H1rBwAJ

Endpoint is  '/api/auth/token'
pass the header with old token... 'X-Authorization', 'Bearer ' + token
data in the post request is {'refreshToken' : XXXX}
