### ISSUE TITLE
[Question] Sum Values of Nested JSON Objects

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7872]
**Component**

 * Rule Engine

**Description**
Hey guys,

this is more of a JS related question, but i was hoping to find solutions to solve that problem.
Right now i receive a response body as an JSON array with nested objects from a rest api node. 

`
{
    "Leistung": [{"ts": 1672142939587, "value": "189.63"},
    {"ts": 1672142937463, "value": "186.16"}]
}
`

I want sum the values for the key "value" for each of these objects. Any how to realize a script node which does that?
I looked up how to do that on the Internet but the solutions arent really applicable in context of TB.

Greetings,
Reno

**Environment**
 * OS: Windows 10
 * ThingsBoard: TB Demo
 * Browser: Firefox

**Comment by devaskim** [comment]
It is only JS, not TB. 
```
let sum = 0;
data["Leistung"].forEach(item => { sum += +item['value'] });
```
You could use [Playcode](https://playcode.io) to test my JS as this platform provides more powerful code completion.

**Comment by callmereno** [comment]
Thanks for the addvice. I eventually solved it like this:

![grafik](https://user-images.githubusercontent.com/114148912/210007476-209e086c-5a41-415f-b615-fd70fc17c383.png)
