### ISSUE TITLE
[Bug] Customer Admin cannot see Audit Log of department user

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7877]
We have a customer with few departments (sub-customers). The department admin can see the audit log of the department user (e.g. login, logout). However, the customer top level admin can only see the audit log of the top level customer user, he cannot see the audit log of the department user.

**Comment by den1jkee** [comment]
Hi,

Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1792) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
Best regards,
Denys.
