### ISSUE TITLE
[Question] Problem with customer attributes node (enrichment failed)

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7879]
**Component**

 * Rule Engine

**Description**
Hey guys,

i have a problem with the 'customer attributes'-node. Im trying to add server attributes from a customer into the msg. This is what the rule chain where i want to use that node looks like:

![grafik](https://user-images.githubusercontent.com/114148912/210096959-feccd2d2-3d5c-4a03-82bc-c5d509652b33.png)

I used this [guide](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/get-weather-using-rest-api-call/) as reference. As you can see in the following pictures I followed the steps correctly (as far i can tell).

Device (Telemetry Source) is assigned to customer:  _Do i have to set up relations additionally?_
![grafik](https://user-images.githubusercontent.com/114148912/210098850-1d45bb32-a668-4bb8-b042-61ef6b0945af.png)

Server attributes of customer:
![grafik](https://user-images.githubusercontent.com/114148912/210095767-ef7aa2ba-6314-4de7-934b-927bb0a7a877.png)

Configuration of the node:
![grafik](https://user-images.githubusercontent.com/114148912/210095945-59728a58-49b6-4452-ab9c-afe436e1e7c9.png)

Here you see the entries of the node output (msg & metadata): 

![grafik](https://user-images.githubusercontent.com/114148912/210097053-66bdee58-4dbe-426b-975e-364552b27b13.png)

![grafik](https://user-images.githubusercontent.com/114148912/210097561-36f478b2-1546-4dc5-a427-1b9d6c951ca4.png)

Did I miss something? Do i have to specify the customer in the rule chain or create a relations at some point?
Neither of that is mentionedin the referred guide though. Suggestions are very welcome.

Greetings and Happy new year in advance!
Reno 

**Environment**

 * OS: WIN10
 * ThingsBoard: TB v.3.4.4 (Demo)
 * Browser: Firefox 108.0.1

**Comment by liotys** [comment]
I don't see a mistake in your configuration. No need to set an additional relation with customer. You should see the result in metadata keys.
May be the fields are too longs (token and refreshToken are very long). Try with username to see il it's a problem of length.

**Comment by mde2017** [comment]
Also my guess that the attribute values for token and refreshToken are too long.

As a workaround: 
If you can access the username & pw of the customer, it should be possible to retrieve token & refreshToken via HTTP Request. Then you don't need to read the stored token attributes.

**Comment by callmereno** [comment]
Thanks, for the advice guys. The problem was that i had a generator node in the root rule chain, which had a unlimited message count was sending messages every second. I rechecked the debug log file and found out that the tokens were passed on, but only once in like a minute.

Happy new year btw :)
