### ISSUE TITLE
Using device type as entity in function

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7881]
**Component**

 * Generic

**Description**
In Thingsboard Map widget or other, mostly in Advanced setting function, 'entityName' is used to identify the device name. Is there a way to use {entityType} the same way? Such as:
       var entityName = dsData[dsIndex]['entityName']
       if ((entityName == 'device1' )
            statement;
            return result; 

But If I use 'entityType' the same way, it does not work. Like:
var entityType = dsData[dsIndex]['entityType'];
        if (entityType == 'dev-type')
               return result;

It is not working as it does for deviceName. Is there a way to use entity type? 

**Environment**

 * OS:  Linux 20.04
 * ThingsBoard: 3.4.2
 * Browser: firefox, chrome, edge

**Comment by devdoob** [comment]
Have you added "type" in data keys? Try accessing it via type instead of entityType

**Comment by debacs83** [comment]
Thank you for your feedback.
I just tried it as:

var devType = dsData[dsIndex]['type']

if (devType == 'my-dev-type-name')
return my_result;

But did not work.  If I have done it differently than you intended to suggest pl tell me.

**Comment by devaskim** [comment]
Use `data['entityType']`

By the way, to look up all data keys just add console output in your function
```
console.log('Data: ', data);
console.log('dsData: ', dsData);
```
then open browser's DevTools (_Console_ tab) and find that you need

**Comment by liotys** [comment]
As @devdoob said, you need to add the datakeys in data definition:
![image](https://user-images.githubusercontent.com/103430329/210216194-be764b1a-44b5-4aca-bcc9-d8825f0985ea.png)
By default it will add the field type with label Type.
You have to use the label to access the value:  dsData[dsIndex]['Type'].
But you can change the label.

**Comment by devaskim** [comment]
@debacs83 If you need name of device profile, @devdoob and @liotys suggested proper way.

**Comment by debacs83** [comment]
Thank you for all of your feedback and suggestion. I will try and tell the outcome.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
