### ISSUE TITLE
[Question] Missing Relation Type after Switch Node

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7883]
**Component**

 * Rule Engine

**Description**
Hey guys,

for some reason i'm missing relation types that defined in the following filter switch node:

![grafik](https://user-images.githubusercontent.com/114148912/210251205-a348d4f7-70b3-48ec-af54-dad7878108b0.png)

As you can see in the screenshoted example, the right relation type gets returned by the function. When i try to connect the output of the switch node with the input of an alarm node in my case, this happens:

![grafik](https://user-images.githubusercontent.com/114148912/210252541-8ceff779-94de-41b0-a2da-0f21559d64a6.png)

This is also the case when i drag in another switch node with the default code. Is that maybe a bug or am I missing something.

Greetings and happy new year,
Reno

**Environment**

 * OS:  Win 10
 * ThingsBoard: TB Demo
 * Browser: Firefox

**Comment by devdoob** [comment]
Try changing your relation string:

Low Power => Low_Power
High Power => High_Power

(no spaces)

**Comment by callmereno** [comment]
> (no spaces)

It sadly doesn't make a difference.

**Comment by devdoob** [comment]
Oh I got your issue,.... you have to manullay type your relation....as per your screenshot it seems you're waiting for autocomplete to show your defined relations.... it won;t work like this....

Just manually write you relation name "Low Power" and then autocomplete will say "Create one" click on that.... your entered text will become a chip in textbox

![image](https://user-images.githubusercontent.com/1464600/210254555-eef4bd80-8073-4f34-a981-5be3727bda67.png)

![image](https://user-images.githubusercontent.com/1464600/210254614-8367f0bb-5aed-4d1f-8233-562d8684e7c0.png)

**Comment by callmereno** [comment]
Wow, i didn't even try to type it in 😅
Can you explain what the purpose the function nextRelation if you can type the the relation type manually?

The routing works now.

**Comment by devdoob** [comment]
"Every new day comes with a new joy" - Thingsboard

Its a very useful node. Let me explain this with an example.

Suppose you're receiving telemetry from multiple ports. Device send temperature info on port 27 but battery health status on port 31. You have to parse these independently...then this relationNode comes handy to split incoming msg into multiple branches. Assume if you receive telemetry on 10 different ports.

**Comment by callmereno** [comment]
Thank you for the example :) But i meant what does _function nextRelation(metadata, msg)_ do?

**Comment by devdoob** [comment]
Node executes configured JS script. Script should return array of next Chain names where Message should be routed. If Array is empty - message not routed to next Node.

Whatever we return from nextRelation...thingsboard will decide on that ....as where to route msg.

**Comment by callmereno** [comment]
Thank you for your help and explanations!
