### ISSUE TITLE
[Question] Receiving Attributes doesn't work

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7891]
* Generic
 * Rule Engine(?)

**Description**
Hey guys,

i'm currently working on a server-side rpc application. I basically want to turn on an analog LED via TB. 
The later works fine (see picture), but when I also want to mirror the analog led on my dashboard, like in this [tutorial](https://www.youtube.com/watch?v=ToQaZJiATRc). Therefore I created a server-side attribute called 'ledStatus' and linked an led indicator to its changes. To send the status i use this TB-function for example:

`
client.sendAttributeBool("ledStatus", ledStatus);`

The problem is that TB doesn't seemt to receive the change of the ledStatus. Am I missing something? Do i maybe have to make a rule chain to process information coming from the device?
 
I hope my problem is kind of understandable. Suggestions are always appreciated :)

Greetings
Reno

![grafik](https://user-images.githubusercontent.com/114148912/210409610-f9ff5103-254f-43d3-b087-05046ef3682f.png)

Here is the current code. I use the Arduino IDE for coding:

```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <ThingsBoard.h>

// AP-DE
#define home "XXXXX"
#define homepw "XXXXXXXX"

// Auswahl des TB-Access Points:
#define TB_TOKEN "XXXXXX" 
#define TB_SERVER "demo.thingsboard.io"
//#define TB_PORT 1883

// Initialization:
WiFiClient wifiClient;           
ThingsBoard client(wifiClient);  

// Select AP:
const char* ssid = home;      
const char* password = homepw;

// Other Variables:
const int led = D2;
bool ledStatus = false;
bool previousState = false;

int status = WL_IDLE_STATUS;

void setup() {

  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(led, OUTPUT);
  digitalWrite(led, LOW);
  Serial.begin(9600);               
  InitWiFi();                             
  client.connect(TB_SERVER, demo_TOKEN);  // Definition des MQTT-Server
}

///////////////////// RPC-SETTINGS /////////////////////

RPC_Response processSwitchChange(const RPC_Data& data) {
  Serial.println("Received 'processSwitchChange'-method: ");
  char params[10];
  serializeJson(data, params);
  String _params = params;

  if (_params == "true") {
    Serial.println("SWITCH: ON");
    ledStatus = true;
    return RPC_Response("processSwitchChange", "true");

  } else if (_params == "false") {
    Serial.println("SWITCH: OFF");
    ledStatus = false;
    return RPC_Response("processSwitchChange", "false");
  }
}

const size_t callbacks_size = 1;
RPC_Callback callbacks[callbacks_size] = {
  { "processSwitchChange", processSwitchChange }
};

bool subscribed = false;  //RPC-Subscribe Status

///////////////////////////////////////// //Serial.printf(previousState != ledStatus ? "true" : "false");

void loop() {

  // Maintain connection
  if (!client.connected()) {
    reconnect();
  }

  checkRPC_Subscription();

  // Sends 
  if (previousState != ledStatus) {
    Serial.println();
    Serial.println("[SWITCH STATE CHANGED]");

    if (ledStatus == true) {
      digitalWrite(led, HIGH);
      Serial.println("LED: ON");
      client.sendAttributeBool("ledStatus", true);
    } else {
      digitalWrite(led, LOW);
      Serial.println("LED: OFF");
      client.sendAttributeBool("ledStatus", false);
    }

    previousState = ledStatus;
  }

  client.loop();
}

/////////////////////////////// OTHER FUNCTIONS ////////////////////////////////////

void InitWiFi() {
  Serial.print("Connecting to Access Point...");
  WiFi.begin(ssid, password);  // Eingabe der Zugangsdaten

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);  // "." bis Verbindung hergestellt ist
    Serial.print(".");
  }
  Serial.println();
  Serial.print("Connected! IP address: ");
  Serial.println(WiFi.localIP());
}

void reconnect() {
  while (!client.connected()) {

    status = WiFi.status();
    if (status != WL_CONNECTED) {
      InitWiFi();
    }

    // Reconnect
    Serial.print("Connecting to ThingsBoard Device ...");
    if (client.connect("ESP8266 Device", TB_TOKEN, NULL)) {
      Serial.println("[DONE]");
    } else {
      Serial.print("[FAILED] Retrying in 5 seconds]");
      delay(5000);
    }
  }
}


void checkRPC_Subscription() {
  if (!subscribed) {
    Serial.println("Subscribing for RPC...");

    if (!client.RPC_Subscribe(callbacks, callbacks_size)) {
      Serial.println("Failed to subscribe for RPC");
      return;
    }

    Serial.println("Subscribe done");
    subscribed = true;
  }
}

```
**Environment**

 * OS: Win10, 
 * ThingsBoard: TB Demo
 * Browser: Firefox

**Comment by callmereno** [comment]
@devaskim Thanks for the clarifcation. I guess my main isssue is that i don't know how to send attributes to Thingsboard. Can u help in this context?

**Comment by devaskim** [comment]
I didn't use TB's C/C++ client. Maybe [examples](https://github.com/thingsboard/thingsboard-arduino-sdk/blob/master/examples) will help you

**Comment by callmereno** [comment]
Yes, i went through the RPC expample with in this [issue ](https://github.com/thingsboard/thingsboard-arduino-sdk/issues/107) with @MathewHDYT. The telemetry gets sent and received and RPC subscription is active:

Only the client attributes are getting sent

![grafik](https://user-images.githubusercontent.com/114148912/211105950-0bd0350a-4138-4b5a-b2d2-5261d50681bf.png)

but don't show up in the corresponding tab:

![grafik](https://user-images.githubusercontent.com/114148912/211108427-7f6f0b15-d469-453e-b189-0844e6cb1e1f.png)

![grafik](https://user-images.githubusercontent.com/114148912/211108285-2b0d5205-cf10-4f4c-a123-9a71951ac168.png)

![grafik](https://user-images.githubusercontent.com/114148912/211108116-aa351cdb-76de-444e-98bd-ad8eb43c570f.png)

**Comment by devaskim** [comment]
Maybe your Rule Chain ignores `Post attributes` event

**Comment by MathewHDYT** [comment]
> Maybe your Rule Chain ignores `Post attributes` event

That could be a possible issue as well @callmereno. Could you open your INA210 device profile and look what Rule chain you are using is it the default Rule chain?

Additionally for the script would it be possible to Decode the Stacktrace you got, when using Version 0.8.0. You can use this [ExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder), which should directly work in the ArduinoIDE.

This might help to further debug where exactly the crash occurs when using the newer version, because in my opinion that's a fatal flaw we need to fix anyway and I am really interested to see if it fixes the other issue (Attributes not being received).

**Comment by callmereno** [comment]
I feel so dumb. Yes this solved the problem @MathewHDYT @devaskim...
Thank you very much !

> Maybe your Rule Chain ignores `Post attributes` event

**Comment by MathewHDYT** [comment]
Nice to know I would still be interested why version 0.8.0 seemed to crash on your device, if you still have some time left could we try to fix that issue as well. Would be highly appreciated :D

**Comment by callmereno** [comment]
Yes, i'm switching to 0.8.0 and keep you posted :) Thats the least i can do
