### ISSUE TITLE
[Question] Non-expiring authentication method?

### ISSUE THREAD

**Issue by DEV-ONI** [thingsboard/thingsboard#7892]
REST APIs and Clients.

 * Generic

**Description**
We're currently looking to use a custom **_ABAC authorization solution_** to validate access to Thingsboard running in a VM instance. So far, the only way to perform queries to the admin UI is through an expiring [JWT](https://jwt.io/).

Is there a way to authenticate with a simple API key or simply have a non-expiring JWT? 
We are trying to find a way to integrate a custom **_ABAC authorization solution_** with Thingsboard and would love to continue using Thingsboard.

**Comment by devaskim** [comment]
TB still doesn't support API key, but you could increase [JWT lifetime](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L111)

I am not sure that is what you need but TB [supports OAuth protocol](https://thingsboard.io/docs/user-guide/oauth-2-support/)

**Comment by DEV-ONI** [comment]
Apologies if this is a stupid question, but would it be possible to set it to never expire? 
As it will only be communicated with behind a authorization wrapper API? 

I'm just trying to find a way to do `server-thingsboard_server` communication. Im wondering if anyone has done something similar?

**Comment by DEV-ONI** [comment]
Is this applicable for server-to-server communication?

https://developers.google.com/identity/protocols/oauth2/service-account#:~:text=The%20Google%20OAuth%202.0%20system,to%20an%20individual%20end%20user.

**Comment by devaskim** [comment]
> Apologies if this is a stupid question, but would it be possible to set it to never expire?

There is no explicit option for that, only setting big number in seconds.
