### ISSUE TITLE
[Question] How to generate repeat device inactive alarm?

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7898]
We have a device profile which will generate offline alarm when the device becomes inactive. This alarm will be sent to customer via Telegram. However, this alarm is generated only once at the moment when device is inactive. If we want to periodically send the alarm to customer during the time when device is inactive, how should we do?

**Comment by devaskim** [comment]
There is no out-the-box solution. Try to use scheduler in TB PE

**Comment by Ultrazombie** [comment]
Closed due to inactivity
