### ISSUE TITLE
Set up X-axis with telemetry 'key' values, instead of 'time'

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7899]
**Component**

 * Generic

**Description**
At present in a time-series widget (e.g. Timeseries Line Chart), the X-axis is by default time and Y-axis is different 'Key' values of the telemetry data that device is receiving, such as Temp, Humidity, RSSI, SNR etc. 

Is it possible to set the X-axis value other than default value (time)? Such as, 'Device_time', 'Gateway_time' that are coming from the device as telemetry data? 

**Environment**

 * OS:  Linux 20.04 LTS
 * ThingsBoard: 3.4.2
 * Browser:  chrome, edge, firefox

**Comment by mde2017** [comment]
This would be only possible with custom widget implementation.

**Comment by debacs83** [comment]
I see. Thank you.

**Comment by devaskim** [comment]
@debacs83 Just to ensure you know about the following:

As I know you are using gateway API to push telemetry, so you could add `ts`  property (in millis) to your data packet to set proper timestamp. [Here is example](https://thingsboard.io/docs/reference/gateway-mqtt-api/#telemetry-upload-api)

**Comment by debacs83** [comment]
@devaskim 
Thank you. Last year I did try to use gateway. But this time I am not using gateway API. Just sending data using 
HTTP(S) POST from EC2 (Linux) instance. Registered the devices with their corresponding Access Token with CSV file and dynamically inserting the Access Token to the API POST URL corresponding to the data send by the devices. 

In my case, the device is sending data through LoRaWAN gateway, and while receiving at the AWS network server, it is putting together the information about the device and gateway. As for Time Series Line Chart widget, we can select which 'keys' to use in Y-axis, but the X-axis is always in time (real-time, or history etc.).  So I was thinking if the 'keys' can be used a X-axis parameters also. 

From the example you have kindly provided, we are sending device data in the similar way, more flat JSON format. We can add another key-value pair to the device data as 'ts' if that helps. But how that will solve the above problem that I could not understand well. Could you please elaborate a little?

**Comment by devaskim** [comment]
@mde2017 Gave you the right anwer. 

Consider my comment as offtopic. You mentioned about Device_time', 'Gateway_time, so I just won't to remind that one could specify custom timestamp for incoming data.

**Comment by debacs83** [comment]
Understood. Thank you for the clarification.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
