### ISSUE TITLE
[Question] Different password policy for different customer

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7900]
When login to ThingsBoard as System Admin, we can change the password policy like the length, expiration duration, etc. However, this is a global setting for all the customers. For individual customer, can we configure the password policy differently based on customer's requirement?

**Comment by epalchenko** [comment]
Hello,
No, the platform does not have such functionality to set up a Password policy for a specific tenant, customer, or user; these settings are applied to the entire platform.
Closed due to inactivity.
