### ISSUE TITLE
[Question] JWT Config does not seem to reflect for JWT tokens

### ISSUE THREAD

**Issue by DEV-ONI** [thingsboard/thingsboard#7904]
JWT Config

Installation

**Description**
I am attempting to increase the expiration of the JWT token, but it does not seem to be reflecting properly on the service.
With the following settings
```
export JWT_TOKEN_EXPIRATION_TIME=1576800000
export JWT_REFRESH_TOKEN_EXPIRATION_TIME=1676800000
```
on

`/etc/thingsboard/conf/thingsboard.conf` 

and using the endpoint `http://<thingsboard url>/api/auth/login`
yields me a token that still expires with the **_DEFAULT_** settings of 9000 seconds.

Am I missing something?

**Environment**

 * OS:  Testing ubuntu 20.04 on AWS EC2 instance
 * ThingsBoard: 3.4.3

**Comment by liotys** [comment]
Have a look at JWT security settings in TB connected as sysadmin.

**Comment by DEV-ONI** [comment]
This does not seem to work also as sysadmin. I still receive the same expiry.
Do you mean to say there is a way to config this through the UI?

**Comment by DEV-ONI** [comment]
![image](https://user-images.githubusercontent.com/52248548/211751657-cfd488b4-1f4a-4952-bc97-5510baac9974.png)

I was able to see the settings you were referring to, but is there no way to make the env variables take effect?
Or am I missing something?

**Comment by ssakharova** [comment]
Hello @DEV-ONI,

JWT Security Settings are prioritized on the settings at the System Administrator level on the web UI over variables set in the `thingsboard.conf` file. 

For more information, please refer to the following link - https://thingsboard.io/docs/pe/user-guide/ui/jwt-security-settings/
