### ISSUE TITLE
[Question] Trigger Rule Chain Event with Dashboard/Widget(s)

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7907]
* Rule Engine
 * Generic

**Description**
Hey guys,

is it possible to trigger an rule chain event via the dashboard (+ widgets)? If yes, then how?

I have rule chain which makes calculations with the help of server attributes and values from the databasa (fetched via rest api get request). It would be nice if i could use this application regardless of whether the my device which sends the data/values is running or not. Currently the application only works when the client/device is active.

Any suggestions?

Greetings
Reno

**Environment**

 * OS:  Win10
 * ThingsBoard: TB Demo
 * Browser: Firefox

**Comment by devaskim** [comment]
Consider [RPC](https://thingsboard.io/docs/user-guide/rpc/#sending-server-side-rpc) as rule chain's triggers

**Comment by Ultrazombie** [comment]
Closed due to inactivity
