### ISSUE TITLE
[Bug] Inactivity Alarm sometimes cannot be cleared

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#7909]
We create a rule in device profile to generate inactivity alarm.<br>
The critical alarm condition is as follows.<br>
![image](https://user-images.githubusercontent.com/17080208/211143991-2f57aa96-a4c8-4407-9d1c-7d75d9e8ee10.png)
The clear alarm condition is as follows.<br>
![image](https://user-images.githubusercontent.com/17080208/211144023-f2e3daa6-4b14-4209-b2b8-f3d7f357a75c.png)

Sometimes, the alarm cannot be cleared when the device is changed from inactive to active.

**Comment by sunyong-mwi** [comment]
**Alarm test for a sensor**:
1. On 04:03:10, data is received. After that, there is no data received before 04:23:10
2. On 04:23:10, data is received
3. On 04:23:11, offline alarm is generated.
4. On 04:28:10, data is received, but alarm is not cleared.

**Observation**: if at almost the same when offline alarm is generated and a data is received, the offline alarm will not be cleared after that. The possible reason could be synchronization issue in different threads:  
1. Data is not received after timeout, set “active” to false
2. Data is received immediately after step 1, set “active” to true
3. Due to the step 1, offline alarm is generated
4. Data is received after 5 minutes. However, there is no change of the “active” status, and thus it does not trigger the device profile rule to clear the alarm.

**Workaround**: In Root Rule chain, add a node to clear offline alarm after receiving the data (Post telemetry) event. The side effect is that the queue size is doubled from the API statistics.

**Comment by myroslav-tb** [comment]
Hi @sunyong-mwi, we weren't able to reproduce this issue in the latest version of the Thingsboard. Please update your instance.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
