### ISSUE TITLE
how to send data to device form server using api

### ISSUE THREAD

**Issue by lomal788** [thingsboard/thingsboard#791]
how to send data to device from server using api?
I'm making 3 party system.
I Tested in thingsboard dashboard it work I want to make like that in my system.

**Comment by untilbit** [comment]
https://thingsboard.io/docs/api/

**Comment by lomal788** [comment]
I saw api document but it's not work that's why I ask u.

**Comment by untilbit** [comment]
Sorry, I thought you mean to send data to the server using api

**Comment by lomal788** [comment]
when I call http://localhost:8080/api/plugins/rpc/twoway/$DEVICE_ID
this in java then 400 error return it.
I send 

{   "method": "setGpio",   "params": {     "pin": "23",     "value": 1   } }
--
this json and I put JWT_TOKEN I don't know why it return error.
oneway, twoway are same.

**Comment by lomal788** [comment]
it work thank you guys.
