### ISSUE TITLE
database-schema-update 3.4.1

### ISSUE THREAD

**Issue by fraenku** [thingsboard/thingsboard#7915]
**Describe the bug**
In https://github.com/thingsboard/thingsboard/blob/master/application/src/main/data/upgrade/3.4.1/schema_update.sql
a change has been made 2 weeks ago after version 3.4.2 has been released. This means that all customers which have already migrated to 3.4.2 will never apply the changes made two weeks ago.
Should the change not been moved to the next new update-script?

**Comment by trikimiki** [comment]
When upgrading TB, you need to use images/packages that are already provided here: https://thingsboard.io/docs/user-guide/install/upgrade-instructions/
