### ISSUE TITLE
How to display the Hierarchy Group Thingsboard list?

### ISSUE THREAD

**Issue by zidniryi** [thingsboard/thingsboard#7916]
**Component**

 * UI

**Description**
I'm using Thingsboards when the parent user is clicked I want to display all the child's hierarchies in the table, but now when I click on the parent only one data is displayed. Like this:

<img width="1113" alt="Screen Shot 2023-01-10 at 10 46 29" src="https://user-images.githubusercontent.com/19811857/211457499-b02a2f36-bf18-4670-85a0-ec94b3d67a2a.png">

How can all child Device data be loaded in the Entity Table Thingsboard when the parent got clicked?

**Environment**

* OS: MacOS Monterey 12.6.1
* ThingsBoard: version CE 3.4.1
* Browser: Chrome and Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by devdoob** [comment]
what is the entity alias for the table on right?

**Comment by devaskim** [comment]
@zidniryi Table widget allows only one datasource, but you need two - parent and childrens. There is no such alias that includes parent and children simultaneously.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
