### ISSUE TITLE
[Question] Settings of the RPC Switch Control 

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7924]
* Generic

**Description**
Hey guys,

can someone explain some advanced settings of the RPC switch control widget:

![grafik](https://user-images.githubusercontent.com/114148912/211784779-0d46bb9b-0cdf-445f-b4ae-d07f90defb52.png)

I understand that the RPC set value method is used to initialize the RPC callback from the device. If I'm not mistaken you can also define a json payload and as the return (to the device?), right? 

How does the 'RPC get value'-method to all of this?

Is the Also, what does the setting 'initial value' do?

Greetings
Reno

**Environment**

 * ThingsBoard: TB Demo v3.4.4.

**Comment by Juka-22** [comment]
Component

UI
Thingsboard Cloud


Hey there, I have the same doubts. Can someone explain the advanced settings of the RPC switch control widget?



Environment
OS: Win 10 64-bit
Browser: Firefox

**Comment by Alimousavi47** [comment]
Hi @callmereno 
as I know using set value you can control your device through server side and vice versa using get value you could get for example the current data of your device.

**Comment by mykhailokornieiev** [comment]
Hi @callmereno 
In general, @Alimousavi47 gave a correct answer. In this case, I close this ticket due to inactivity.
