### ISSUE TITLE
[Bug] Switch Control Widget: Changing name doesn't work

### ISSUE THREAD

**Issue by callmereno** [thingsboard/thingsboard#7930]
**Describe the bug**
Hey guys,

when i try to change the name of the switch control widget in the advanced settings, it doesn't get updated.
After saving the dashboard the previously entered name also gets deleted/reset.

Greetings,
Reno

**Your Server Environment**

* demo.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Firefox
* Version 108.0.2

**To Reproduce**
1. Go to 'Advanced' in the switch control widget
2. Change the name of the widget
3. Save the changes

**Expected behavior**
Entered name gets displayed.

**Comment by IoTThinks** [comment]
I have the same problem in TB CE 3.4.3 too. 
Previously, my TB CE 3.4.1 works fine.

Change Switch Title
![image](https://user-images.githubusercontent.com/29994971/213951116-0aa11b5a-4913-449e-9f51-661e95e55380.png)

Looks OK
![image](https://user-images.githubusercontent.com/29994971/213951155-25a9806f-6a13-45b9-acc9-48d5e39c0edf.png)

Dashboard still see old name. It should show RO2-New.
![image](https://user-images.githubusercontent.com/29994971/213951188-d5794000-9fa1-4f6a-bc9b-43f92d320038.png)

Click edit again then see old name.
It should show RO2-New.
![image](https://user-images.githubusercontent.com/29994971/213951215-f48dbc54-8fdd-4727-8cf8-54e234a333cb.png)

**Comment by IoTThinks** [comment]
Changing name of switch control doesn't work on TB CE 3.4.3 yet.

**Comment by mykhailokornieiev** [comment]
Hi
As far as I can see, this problem was solved at least in 3.5.1 and this problem is not reproducible on the latest version (3.6.4)
