### ISSUE TITLE
[Question] How to display a string value in a timeseries chart (only in tooltip)

### ISSUE THREAD

**Issue by MaxiGalaxi** [thingsboard/thingsboard#7932]
**Component**

 * UI (?)
 
**Description**
I am trying to display a string value in the tooltip of a timeseries chart. 
<img src="https://i.imgur.com/MCmGCQX.png">

That's the data entry:
<img src="https://i.imgur.com/Kii57HE.png">

So in the tooltip it should be like"weather_desc: light rain".
Is this possible?

**Environment**
 * ThingsBoard: CE 3.2.2

**Comment by ssakharova** [comment]
Hello @MaxiGalaxi,

The default functionality of the Timeseries Chart widget does not align with your requirements, as this widget is developed to work only with numeric values. Consequently, a string cannot be displayed in the tooltip of a Timeseries chart.

Therefore, the most viable solution would be to develop a custom widget according to your specific requirements. 

Best regards,
Sofiia
