### ISSUE TITLE
[Question]  Timeseries Line Chart - Weekday instead of date

### ISSUE THREAD

**Issue by MaxiGalaxi** [thingsboard/thingsboard#7933]
**Component**

 * Widget

**Description**
I wonder if it is possible to display the weekday instead of the date (+ time) on the x-axis.
For example I got a chart displaying the rain of the last 7 days on the x-axis are ticks for every day described by date + time, but I would like to display the corresponding weekday.

<img src="https://i.imgur.com/YlBUKew.png" alt="Snippet of a timeseries chart">

What I want to achieve is that instead or additional to the date on the x-axis the corresponding name of the day is displayed. As of right now there is no additional data provided, TB is abbreviating the date from the timestamp when the data was received.

**Environment**

 * ThingsBoard: CE 3.2.2

**Comment by MaxiGalaxi** [comment]
Would this only be possible with a custom widget?

Is it possible to display the weekday in the tooltip just like the key-value-pairs?

**Comment by devaskim** [comment]
Out of the box only Y tick could be custom formatted. To customize tooltip go to *Advanced Settings* of widget and implement *Tooltip value format function*

**Comment by MaxiGalaxi** [comment]
> Out of the box only Y ticks could be custom formatted. To customize tooltip go to _Advanced Settings_ of widget and implement _Tooltip value format function_

Yeah thank you for your response, sadly this is not possible for the X-Axis.

**Comment by ssakharova** [comment]
Hello @MaxiGalaxi,

The latest versions of Thingsboard introduce new widgets like the Line Chart and Timeseries Chart, which offer enhanced customization options for labels on the X-axis.

Please see the screenshots below:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/5eff0f3a-4692-4bbf-8945-53d9c919248b)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/45d28817-08f5-4765-b574-80321f047ca2)

Therefore, we recommend you consider upgrading to the latest version of the Thingsboard.

Best regards,
Sofiia
