### ISSUE TITLE
[Question] How can i make a dropdown menu in an widget's action?

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7936]
**Component**

 * UI
 * Generic

**Description**
I have a custom action in a widget where a popup is showed up, i want to show there a dropdown menu and then save the value selected as a server attribute. My knowledge in reactis restricted, so a full example would help

**Environment**

 * OS: Linux
 * ThingsBoard: 3.4.2
 * Browser: Mozilla

**Comment by devaskim** [comment]
As I understand you need custom action with HTML template. There are already several examples of HTML forms and JS controllers. TB uses Angular Material components. here are [examples of select](https://material.angular.io/components/select/examples)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
