### ISSUE TITLE
[Question] Is it possible to have 10000 attributes for user?

### ISSUE THREAD

**Issue by AnhNDd-BKAV** [thingsboard/thingsboard#7941]
**Component**
 Generic

**Description**
In our particular problem, User needs to have more than 10000 attributes. Can Thingsboard handle this? Or what is the correct solution we should use?

I have 2 options:
1. User has 10000 attributes
2. User has 1 attribute, in the attribute is json containing 10000 information

**Comment by skewty** [comment]
I would go option 2 JSON. 
Perhaps it makes sense to separate them into a few groups?

**Comment by AnhNDd-BKAV** [comment]
> I would go option 2 JSON. 
> Perhaps it makes sense to separate them into a few groups?

But limit size of value attribute is 10000. I can increase in config database, but it true ?

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
