### ISSUE TITLE
[Bug]  "Action - device profile" node incorrectly handles alarm created and cancelled

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard#7944]
**Describe the bug**
The "Action - device profile" node  incorrectly handles alarm created and cancelled.

Expected results:
1. Alarm Active to come out on Alarm Active
2. Alarm Cancelled to come out on Alarm Cancelled
3. Alarm Active to come out on Success
4. Alarm Cancelled to come out on Success

Actual results:
1. this works
2. this doesn't work
3. this doesn't work
4. this works

Version: 3.4.0 PE (nothing mentioned in .1, .2, .3 release notes that this was fixed)

**Comment by skewty** [comment]
I updated to 3.4.3 and now Alarm Active never works.

Here is what I am trying with and having no success:

![image](https://user-images.githubusercontent.com/9087223/214160591-c2ced557-df0c-4087-84c0-6f6d6507af38.png)

![image](https://user-images.githubusercontent.com/9087223/214161293-e7cece7b-0055-4853-8339-66cf11f67a35.png)

I completely deleted the database on my development server and installed a new demo database then went to "Root Rule Chain" added a node right after "device profile - Device Profile Node" (which exists by default) and although I can see my alarm is activating, it never comes through for me.

**Comment by SuminDenis** [comment]
Hi @skewty,

I cannot reproduce this behavior on the current ThingsBoard version.

Please update your instance to the latest ThingsBoard version, everything should work properly!
