### ISSUE TITLE
[Bug] Change Dashboard State in Open Dialog in 3.4.3

### ISSUE THREAD

**Issue by HaydenBurrows** [thingsboard/thingsboard#7945]
**Describe the bug**
When using a display state option "Open in seperate dialog", then try to change dashboard state again within the open dialog (state display option e.g. normal), the screen displays an overlay and you can't click anything.

In 3.4.1, when using a separate dialog, then going to another dashboard state using "normal", it would change in that dialog.

There doesn't seem to be any errors in DevTool. (Chrome).

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard 3.4.3PE
  * Ubuntu 22.10

**Your Client Environment**
* OS: Ubuntu 22.10
* Browser: Chrome and Firefox

**To Reproduce**
1. Make widget, change dashboard state using row click to open separate dialog
2. In dialog, change dashboard state using row click using normal.
3. The dashboard state should open in the separate dialog, but it displays an overlay and dismisses the dialog

**Expected behavior**
The second change to dashboard state should open in the same separate dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/69659611/212568376-c508cb9b-57c2-4a5b-9367-d6ca813757bb.png)

**Comment by SuminDenis** [comment]
Hi @HaydenBurrows ,

Thank you for informing us about this issue. It looks like a platform bug. I have already added a ticket, PROD-4054, to our backlog.

There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by SuminDenys** [comment]
Hi @HaydenBurrows,

We are closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.
