### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Coderakid01** [thingsboard/thingsboard#7946]
**Describe the bug**
Hi everyone! I'm having a problem with my Thingsboard, It appears that I have a UI Bug somehow after upgrading it. I made the upgrade from Version 2.4.0 to the Latest Version 3.4.3, After the upgrade, I notice my Thingsboard has a UI Bug in which it didn't display the text properly.

Some Detail about my Server
Platform : Digital Ocean
ThingsBoard Version : Community Edition Ver 3.4.3 (Latest)
OS : Ubuntu 18.04

**Screenshots**
https://drive.google.com/file/d/1Wj8vl02kaFO0AjA5nMcPGSxPbVTNh9qZ/view?usp=share_link
<p align="center"><img src="https://github.com/Coderakid01/Medias/blob/main/Capture.JPG" width="900"></a></p>

**Comment by JavierNR** [comment]
Hello, probably your browser needs to upgrade the cache. Try hitting Shift + F5 or clearing your browser cache and check if it works.

**Comment by Coderakid01** [comment]
Hi, I have rebooted my server and reload my browser, everything has work fine, Thanks a lot for the tips really much appreciate it!
