### ISSUE TITLE
[Question] Filter in Entities Hierarchy Widget

### ISSUE THREAD

**Issue by samokomo** [thingsboard/thingsboard#7956]
**Component**

 * UI
**Description**
Hello Thingsboard community. I have a kinda newbie question. I need a filter in entities hierarchy widget, which will allow only active entities on level 2 and all entities on level 1 (devices with active = true (server attribute)}. I guess it shlould be defined in Node relations query function, but I am a little bit confused on how to define this.
![image](https://user-images.githubusercontent.com/58517178/212850084-80550671-755b-4eb1-b8b2-a44986daa809.png)
 

Thanks for any help! Have a nice day!
**Environment**

 * OS:  Win
 * ThingsBoard: Latest
 * Browser: Edge

**Comment by devaskim** [comment]
In such cases I do the following:
Create the same entity alias and filter in some test dashboard. Then open browser's DevTools, go to Network tab, enable WS (websocket) filter and find in outgoing requests which query should be

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by fabianlefebre** [comment]
Sorry for opening here again, did you find a solution for your issue?
I am lacking the same option, I have tried to find a way to hide it when it is being found or to apply filters on the higher level. 
But so far, all leading to not the desired result.
