### ISSUE TITLE
[Feature Request] Dashboard entity selector: provide option to display name/label/name+label 

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7961]
**Is your feature request related to a problem? Please describe.**
The entity's name is unique identifier, so often it is not human "readable". But entity selector of dashboard displays entity names to distinguish one from another, it is reasonable.

It would be useful to have dashboard configuration option to switch between displaying either name, label or name+label.

**Comment by Backdraft007** [comment]
@devaskim do you know if the label field is editable from dashboard in the current version?
In the past it is not.

**Comment by devaskim** [comment]
@Backdraft007 No, as I know. Only on the entity's details page.

**Comment by devdoob** [comment]
@Backdraft007 yes it's possible to modify entity name and entity from dashboard

![image](https://user-images.githubusercontent.com/1464600/213158595-dabdf662-074c-4614-a3c5-c627bf5007b3.png)

**Comment by devaskim** [comment]
@devdoob with custom action you could do whatever you want)

**Comment by devdoob** [comment]
True... I thought he's finding a way to achieve this. 
Got it now. @Backdraft007 was referring to functionality from dashboard.

**Comment by Backdraft007** [comment]
Thanks @devdoob,
but their, the user can also change entity name. That is not good. :)
