### ISSUE TITLE
[Question] Decode base64ToHex

### ISSUE THREAD

**Issue by emurilloEcourbes** [thingsboard/thingsboard#7964]
Hi, 
I'm using a Transform payload to transform a payload in Base64 to hexadecimal. 
In ThingBoard PE I'm using atob function without problems, but in CE I can not use atob function. 
Anyone can help me to how I can decode the payload?

 * Rule Engine

**Description**
I'm trying to decode a payload from Base64 to Hex, but when I use the atob function I got the error: 
`org.thingsboard.script.api.TbScriptException: javax.script.ScriptException: ReferenceError: "atob" is not defined in at line number 14`
I tried to fix it, but I couldn't. How can I decode the payload?

**Environment**
 * OS:  name and version
 * ThingsBoard: version 3.4.3
Thanks in advance

**Comment by TomPohys** [comment]
Hi, the `base64ToHex(String input)` is working for transform a payload in [Base64 to Hex](https://thingsboard.io/docs/user-guide/tbel/#parsehextoint:~:text=Copy%20to%20clipboard-,base64ToHex,-Decodes%20the%20Base64)

e.g. `var bytesStr = base64ToHex(msg.payload);`

**Comment by emurilloEcourbes** [comment]
Thanks [TomPohys](https://github.com/TomPohys)
