### ISSUE TITLE
[Feature Request] Timeseries chart: define threshold values from entity telemetry latest value

### ISSUE THREAD

**Issue by TheBergam** [thingsboard/thingsboard#7966]
It is possible to draw horizontal lines on timeseries charts in the advanced data key configuration section by defining thresholds.

The only options to select the threshold value source are "Predefined value" and "Value taken from entity attribute".

Is it possible to add an option for "**Value taken from entity telemetry latest value**"?
(my setpoints that I want to use for the threshold values are saved as telemetry because it is important to monitor how they are changed through time)

![Screenshot 2023-01-18 152958](https://user-images.githubusercontent.com/30861996/213213687-d09d2f10-545b-475d-b4a9-02ae5f42630f.png)

**Comment by devaskim** [comment]
Chart data key configuration let you do this with *Latest values* data keys
