### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7967]
**Component**

 * UI
 * Rule Engine

**Description**
I have a custom html card widget that takes some values from server attributes. Then i have a custom action where i can edit the attributes and save them. The problem is that i dont want to only save the attribute, but also to make an rpc call (where it will be send to my device through downlink node). Unfortunatelly "sendOneWayCommand" function doens't seem to work on a card widget's custom action.
Also i tried to make a rpc call request through rulechain on "Attributes updated" case scenario, but this doesnt work too

**Environment**

 * OS:  Linux
 * ThingsBoard: 3.4.2
 * Browser: Mozilla

**Comment by mykhailokornieiev** [comment]
Hi. I'm not sure if this question is still relevant to you, but this is probably related to the fact that all non-RPC widgets have the `rpcEnabled: false` option by default. It’s impossible to just rewrite the parameter in the current subscription. Therefore, you need to create a custom subscription
https://github.com/thingsboard/thingsboard/blob/cb37450470892f82a3787a1e989f3463295f1055/ui-ngx/src/app/core/api/widget-subscription.ts#L196

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
