### ISSUE TITLE
exception is thrown when run this project 

### ISSUE THREAD

**Issue by zhangwonderful** [thingsboard/thingsboard#797]
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.3.RELEASE:run (default-cli) on project application: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in file [D:\workspace\IoT\thingsboard-1.4\application\target\classes\org\thingsboard\server\service\security\auth\rest\RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#78c60ffd' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#78c60ffd': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory: Schema-validation: missing table [admin_settings] -> [

**Comment by zhangwonderful** [comment]
When I run mvn install on application sub-project, console output the following errors:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ThingsBoard Server Application 1.4.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ application ---
[INFO] Configured Artifact: com.google.protobuf:protoc:windows-x86_64:3.0.2:exe
[INFO] Copying protoc-3.0.2-windows-x86_64.exe to D:\workspace\IoT\thingsboard-1.4\application\target\protoc-3.0.2-windows-x86_64.exe
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.0:compile (default) @ application ---
[INFO] Compiling 2 proto file(s) to D:\workspace\IoT\thingsboard-1.4\application\target\generated-sources\protobuf\java
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.0:compile-custom (default) @ application ---
[INFO] Compiling 2 proto file(s) to D:\workspace\IoT\thingsboard-1.4\application\target\generated-sources\protobuf\grpc-java
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:add-source (add-source) @ application ---
[INFO] Source directory: D:\workspace\IoT\thingsboard-1.4\application\target\generated-sources added.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO] Copying 2 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-conf) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-service-conf) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-win-conf) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-control) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-install) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-windows-control) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-windows-install) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-data) @ application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 25 resources
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ application ---
[INFO] Compiling 3 source files to D:\workspace\IoT\thingsboard-1.4\application\target\classes
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.0:test-compile (default) @ application ---
[INFO] D:\workspace\IoT\thingsboard-1.4\application\src\test\proto does not exist. Review the configuration or consider disabling the plugin.
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ application ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ application ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ application ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ application ---
[INFO] Building jar: D:\workspace\IoT\thingsboard-1.4\application\target\thingsboard-1.4.0.jar
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-extensions) @ application ---
[INFO] Configured Artifact: org.thingsboard.extensions:extension-rabbitmq:extension:?:jar
[INFO] Configured Artifact: org.thingsboard.extensions:extension-rest-api-call:extension:?:jar
[INFO] Configured Artifact: org.thingsboard.extensions:extension-kafka:extension:?:jar
[INFO] Configured Artifact: org.thingsboard.extensions:extension-mqtt:extension:?:jar
[INFO] Configured Artifact: org.thingsboard.extensions:extension-sqs:extension:?:jar
[INFO] Configured Artifact: org.thingsboard.extensions:extension-sns:extension:?:jar
[INFO] org.thingsboard.extensions:extension-rabbitmq:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] org.thingsboard.extensions:extension-rest-api-call:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] org.thingsboard.extensions:extension-kafka:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] org.thingsboard.extensions:extension-mqtt:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] org.thingsboard.extensions:extension-sqs:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] org.thingsboard.extensions:extension-sns:extension:1.4.0:jar already exists in D:\workspace\IoT\thingsboard-1.4\application\target\extensions
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-winsw-service) @ application ---
[INFO] Configured Artifact: com.sun.winsw:winsw:bin:?:exe
[INFO] com.sun.winsw:winsw:bin:2.0.1:exe already exists in D:\workspace\IoT\thingsboard-1.4\application\target\windows
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.3.RELEASE:repackage (default) @ application ---
[INFO] Layout: ZIP
[INFO] Attaching archive: D:\workspace\IoT\thingsboard-1.4\application\target\thingsboard-1.4.0-boot.jar, with classifier: boot
[INFO] 
[INFO] --- gradle-maven-plugin:1.0.8:invoke (default) @ application ---
[INFO] jvmArgs: [Ljava.lang.String;@6cf37a31
[INFO] gradleProjectDirectory: D:\workspace\IoT\thingsboard-1.4\application
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] Initialize build
[INFO] Configure settings
[INFO] Initialize build
[INFO] Configure projects
[INFO] Configure project :
[INFO] Resolve dependencies ':classpath'
[INFO] Configure project :
[INFO] Configure projects

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'application'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.netflix.nebula:gradle-ospackage-plugin:3.8.0.
     Required by:
         :application:unspecified
      > No cached version of com.netflix.nebula:gradle-ospackage-plugin:3.8.0 available for offline mode.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.497 secs
[INFO] Initialize build
[INFO] Build
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.418 s
[INFO] Finished at: 2018-05-21T11:25:10+08:00
[INFO] Final Memory: 49M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project application: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by vparomskiy** [comment]
> Schema-validation: missing table [admin_settings] 
You need to update DB schema before running application. new table 'admin_settings' should be created.

**Comment by zhangwonderful** [comment]
Thanks a lot, the issue was resolved.
