### ISSUE TITLE
[Question] Flow variables

### ISSUE THREAD

**Issue by tudro** [thingsboard/thingsboard#7979]
**Component**
 * Rule Engine

**Description**
Is there anything similar to the `flow variables` in node red? Or any workaround to do that? 

For example: we have a device that sends 2 types of messages, A and B. A every minute, B every 10 minutes. One of the As might contain something that makes the next B require a different transformation, so i would like to save this specific A for future reference.

Another example: the device sends a message of type C in 3 "flavors". One of the flavors means accumulating the next `n` type C messages to create the full message that will be saved. 

As a workaround we could probably use the device attributes, but doesn't this have an impact on the performance? 

Thank you

**Comment by ssakharova** [comment]
Hello @tudro,

This is not supported in Thingsboard. 
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
