### ISSUE TITLE
Sending data from the past to thingsboard

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#799]
Hi all,

I'm using python to send every minute realtime data from MySQL database to thingsboard. 
The problem is that it's only sending data when the python script is running.
Is it possible to send data from the past, for example yesterday, to thingsboard? 

Another question: How does thingsboard collect all the data that is send? Is it creating his own small database? 

Gr Jens

**Comment by vparomskiy** [comment]
During telemetry upload, you should use required telemetry timestamp filed.

If you use HTTP API for telemetry upload, you can find details here 
https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api

For MQTT 
https://thingsboard.io/docs/reference/mqtt-api/#telemetry-upload-api

Thingsboard can use different storages: HSQL DB, PostgreSQL, Cassandra.
https://thingsboard.io/docs/user-guide/install/linux/#optional-external-database-installation

**Comment by mbihari** [comment]
Can anybody tell how i can send every minute realtime data from MySQL database to thingsboard.
