### ISSUE TITLE
[Bug] PE: No API documentation for PE services in custom widget context

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#7992]
**Describe the bug**
For example, I need to find pre-configured asset group or create it from custom widget. Only what editor of custom widgets says is there is `entityGroupService` in `self.ctx`, no documentation for methods of this service.

Ok. I go to Swagger UI, find `getEntityGroupsByOwnerAndTypeAndPageLink` method in EntityGroupController.

Then do `console.log(self.ctx.entityGroupService)` to check on if such method exists in `entityGroupService`. There are `getEntityGroupsByIds(_,m)`, `getEntityGroupsByOwnerId(_,m,T,l)` and `getEntityGroupsByOwnerIdAndPageLink(_,m,T,l,O)`. I guess, my is last one. **But how do I know what are `_,m,T,l,O` parameters**?

I know, unfortunately TB team (@ashvayka @ikulikov @vvlladd28 and others) doesn't like discussion, but **it is PE version, it is our money for your business**.

How do you want to start Marketplace, for example, for dashboards and widgets without these, I think, [must-have capabilities](https://github.com/thingsboard/thingsboard/issues/7580) (not features)? Again unfortunately, there was no feedback from TB team.

**Solution for my case**
```
const pageLink = self.ctx.pageLink(10, 0, someSearchStr);
self.ctx.entityGroupService.getEntityGroupsByOwnerIdAndPageLink('TENANT', tenantIdStr, 'ASSET', pageLink)
```
From 3.5
```
const pageLink = self.ctx.pageLink(10, 0, someSearchStr);
self.ctx.entityGroupService.getEntityGroupsByOwnerIdAndPageLink(pageLink, 'TENANT', tenantIdStr, 'ASSET')
```

**Comment by clemjrt** [comment]
I am having many difficulties using the entityGroupService service. There are also other services whose functions are not  available with auto-completion, or even documented somewhere. I really agree with @devaskim  that a paid solution could at least be fully documented. As he said, with PE version, it's our money for your business but it's also your solution for our business...
