### ISSUE TITLE
Configuration of multiple timeserie keys as an OR statement in one alarm rule condition

### ISSUE THREAD

**Issue by taddei68** [thingsboard/thingsboard#7996]
Thingsboard 3.3

Device Profile alarm rules 

**Description**
I intend to raise an alarm if the current [A] in either phase in a 3 phase system is greater than a set threshold. The current readings (all 3 phases) is mqtt timeseries messages from an energy meter. The current threshold is an attribute on the energy meter device. The alarm condition should be something like this: 

if ((current_phase_1 > threshold OR current_phase_2 > threshold OR current_phase_2 > threshold) AND alarm_flag === "true"){
alarm = true;
}   

However, I can not figure out how to configure the OR statement between multiple keys. Whatever I try, I only end up with which is not what I want (note the AND between each check):
if (current_phase_1 > threshold AND current_phase_2 > threshold AND current_phase_2 > threshold AND alarm_flag === "true"){
alarm = true;
} 

I simply want a general "high load" warning alarm if either phase exceeds the threshold, not a separate "high load phase n" alarm per phase. 

How can I achieve this requirement with the alarm rules?

![image](https://user-images.githubusercontent.com/33156693/214849301-3ba58b93-e0b2-43bd-a573-626658261ebd.png)

**Comment by Civilduino** [comment]
Use the "Add complex" to nest the "and" operations and use "or outside.
![image](https://user-images.githubusercontent.com/27728926/219478662-51c2d1b1-283d-4ccd-8bc5-fb1938c0592f.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has not seen any activity for a considerable period, and we will close it. Please get in touch with us if you have any additional concerns or encounter similar issues.
