### ISSUE TITLE
[Bug] Originator attribute Fails in Edge

### ISSUE THREAD

**Issue by nideid** [thingsboard/thingsboard#8005]
**Describe the bug**

**Your Server Environment**

* localhost:8080
* cloud.thingsboard.io
* own setup
  *  local infrastructure
  * ThingsBoard Version: 3.4.3 (CE)
  * ThingsBoard EDGE: 3.4.3 (edge)
  * OS Name and Version : Ubuntu VM (22.10)

**Your Client Environment**

* OS: Ubuntu VM (22.10)
* Browser 109.0 Mozilla Fire Fox snap for Ubuntu canonical-002 - 1.0

**To Reproduce**
Scenario 1:
1. Go to 'Devices'
2. Click on 'Add new device'
3. Add a device name "TestAttrDevice"
4. Click on the attributes tab
5. Add server attribute name: "testAttr"    Value: "testAttr_value"
![image](https://user-images.githubusercontent.com/121759876/215267913-5f864608-e5a3-4598-87fe-2a7f270ca54a.png)

7. Go to Edge instances
8. Click on "edge devices"
9. Click on "assign new device" This will open the window "Assign device(s) to edge"
10. Click on the attributes tab in the edge device
11. Select Server attributes
12. Select the attribute name "testAttr"
13. Update the server attribute value from "testAttr_value" to "testAttr_Updated"

![image](https://user-images.githubusercontent.com/121759876/215268045-7bbc4ca9-3946-41d6-938f-4fd1b0cdb5b3.png)

15. Go to Edge instances
16. Click on Edge rule chains
17. Select Edge Root Rule Chain
18. Add node Originator attributes between "Message Type Switch" and "Save Timeseries"
19. Add script for testing Pass and Fail.
![image](https://user-images.githubusercontent.com/121759876/215268116-97ee4846-6e47-495e-af82-a126870d6fb9.png)

![image](https://user-images.githubusercontent.com/121759876/215268169-ee4b6e44-8779-4da5-af8b-4a8b3a8d21c0.png)

![image](https://user-images.githubusercontent.com/121759876/215268262-e301e3c9-d8de-47e0-a466-ff4e75290bf1.png)

![image](https://user-images.githubusercontent.com/121759876/215268286-4a40262f-d37b-48a2-9501-00512a61b69d.png)

20. send a telemetry data using curl command
 curl -v -X POST -d "{\"temperature\": 27}" http://localhost:18080/api/v1/0w9hVsGgdPgvGFN9ilv1/telemetry --header "Content-Type:application/json" 

21. See error
![image](https://user-images.githubusercontent.com/121759876/215273120-eb0b2cc1-d28d-42fc-ba2c-bd1b8ed76124.png)

The "ss_testAttr" should have the value "testAttr_value"

**Expected behavior**
The "ss_testAttr" should have the value "testAttr_Updated"

Scenario 2:
1. Go to Edge instances
2. Click on "edge devices"
3. Click on the device "TestAttrDevice"
4. Click on the attributes tab in the edge device
5. Select Server attributes
6. Add another attribute "Second_TestAttr" with a value "Second_testAttr_Value"

![image](https://user-images.githubusercontent.com/121759876/215273315-93025271-c525-404e-ada8-7c781dac2d02.png)

8. Update the Originator attribute node to have the second server attribute

9. Send a telemetry data using Curl
curl -v -X POST -d "{\"temperature\": 27}" http://localhost:18080/api/v1/0w9hVsGgdPgvGFN9ilv1/telemetry --header "Content-Type:application/json" 

10.  See Error
![image](https://user-images.githubusercontent.com/121759876/215273578-e3d764c5-b1cb-43b7-b135-72de1565d781.png)

**Expected Behavior**
1. Should not fail 
2. should pick the updated value for "ss_testAttr" as "testAttr_Updated"
3. Should get the attribute ss_Second_TestAttr with a value "Second_TestAttr_Value"

**Screenshots**
Added

**Additional context**

I have installed ThingsBoard CE and the Edge in the same computer. Everything is working fine other than the originator attribute node.

**Comment by volodymyr-babak** [comment]
hi @nideid 

thanks for these detailed description - much appreciated for these steps to reproduce! 
Is  this related to the similar issue? https://github.com/thingsboard/thingsboard/issues/7981

I'm going to investigate it locally and provide you the root cause.

**Comment by volodymyr-babak** [comment]
hi @nideid 

I had investigated it locally and I suppose the problem is not in the originator rule node itself.
The problem that you are updating device server side attributes on the cloud and these updates are not propagated to the edge.
Once the edge receives timeseries data for the device it has outdated value of server side attributes and use them instead.

First, could you please login into edge UI (localhost:18080) and test the updates of the server side attributes directly on the edge? I believe in this case you will not see this problem and rule node will work as expected.

If you would like to be update to update server side attributes on the cloud and propagate these updates to the edge, please update root rule chain of the cloud (not edge).
Go to your cloud rule chains and open root rule chain:
![image](https://user-images.githubusercontent.com/3466101/215701939-d9a45638-65bf-488c-bce9-0c53ccf1e3a8.png)

And modify root rule chain - add new rule node - 'push to edge'. And add 'Attributes Updates' connection from 'Message type switch' rule node into 'push to edge':
![image](https://user-images.githubusercontent.com/3466101/215702268-7d5711aa-70b4-4020-bc4b-bae63a76e1c8.png)

Once you'll update root rule chain please do your test one more time - this time I believe you'll not see issues with originator rule node.

**Comment by nideid** [comment]
Hi @volodymyr-babak 

Thank you very much for the reply. Yes, If I add the push to edge node in the cloud root rule chain, its working. But I need your help to clarify the scenario mentioned below.

In my case I wanted to update the server attribute from the edge side as the internet connection is not there always. So once there is internet, then only I am going to push whatever data available to the cloud. So meanwhile in my application I have allowed the user to update the server attribute at the edge through the edge side dashboard (which is working). So my concern is if I update the server attribute at the edge will I be able to get the get the updated server attribute from the Edge root rule chain if the edge is not connected to the cloud. (Say internet is down for the whole day and not able to connect to the cloud meanwhile the user has changed the server attribute two three times from the edge side.) 

Thank you.

**Comment by volodymyr-babak** [comment]
hi @nideid 

sure, that one of the main functionality of the edge - it stores all the changes, done to the system (attribute updates, time-series uploaded, device added, etc.) in the local database. 
Once the connection between the edge and cloud is established, all the events, that are stored in the cloud queue on the edge are going to be pushed to the cloud. 
You can do a small test:
1. start TB server locally
2. start TB edge locally and connect to TB server
3. stop TB server
4. make sure that TB edge is still running and you are able to open Edge UI
5. update particular attribute of one of the devices on the edge 
6. go to 'Edge' -> 'Cloud Events' menu and observe that set of cloud events are in 'pending' state
7. start TB server locally
8. go to 'Edge' -> 'Cloud Events' menu and observe that set of cloud events are were 'pending' state are now in 'deployed' state
9. validate that attribute for device was updated on the cloud as well

**Comment by nideid** [comment]
Thank you. I will try.
