### ISSUE TITLE
Disk space used by postgres DB

### ISSUE THREAD

**Issue by tlobbri** [thingsboard/thingsboard#8016]
Hi, 

In the website of Thingsboard, I've seen that 7M datapoints require roughly 1Gb of disk space using postgres db.

I found similar value in my configuration (TB PE 3.2.1)

However I don't understand why so much space is required. 

Basically, 1 datapoint requirtes 1 double (data value -> double) + 1 long (timestamp-> long). 
Thus for 7M datapoints, it should require roughly 7 * (8+8) = 112 Mb.

There is a ratio of 9 between 112Mb and 1 Gb. I could expect a factor of 2... but 9 seems to me very high.

Could you  explain this? 

Kind regards,

**Comment by den1jkee** [comment]
Hi,
Can you show me where you found this information?
You talking about 1Gb in general or only for telemetry?

Best regards,
Denys

**Comment by tlobbri** [comment]
https://thingsboard.io/docs/reference/performance-aws-instances/#postgres

**Comment by tlobbri** [comment]
> Hi, Can you show me where you found this information? You talking about 1Gb in general or only for telemetry?
> 
> Best regards, Denys

I mean in general (disk space used by the postgres db), but I guest this is mainly the telemetry

**Comment by smatvienko-tb** [comment]
> https://thingsboard.io/docs/reference/performance-aws-instances/#postgres

@tlobbri, your link has screenshots of data distributions between tables and indexes. 

As you see, the indexes, latest table, and attributes (active state, last activity time, etc.) took some space.

> Basically, 1 datapoint requirtes 1 double (data value -> double) + 1 long (timestamp-> long).

The estimation of the data size you provided is quite different from the actual data [schema](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/sql/schema-ts-psql.sql). Simply saying, the data point is always stored with the data key, ts, and data.
The data are aligned in the psql tables. So there are some empty spaces between cells in the psql.
Data and indexes are organized as pages, and pages have some free space to take new data.
The records updated in Postgres are not deleted immediately but require vacuuming. 
The table size on disk is often bigger than the actual data.

So yes, the disc's data size is bigger than expected. And the performance test is about how the real things will look like.

For a really big telemetry workload, Postgresql is not the best choice.

The big live productions are working on the Cassandra database for telemetry. It's less expensive on disk consumption and provides better performance and many other benefits.

For smaller use cases you estimate and validate the real data consumption using the performance test tool and ThingsBoard.

If you are planning something big using ThingsBoard, [please get in touch with ThingsBoard](https://thingsboard.io/docs/contact-us/) to get the best advice before you start.

**Comment by tlobbri** [comment]
Thanks for your feedback!
