### ISSUE TITLE
[Question] Multiple call to call function self.onDataUpdated

### ISSUE THREAD

**Issue by clemjrt** [thingsboard/thingsboard#8019]
**Component**

 * Generic

**Description**

I am developping a custom widget of type "Latest Values".
I am using the aggregation function available in the latest values widgets type.
![image](https://user-images.githubusercontent.com/104388936/215738380-607b6758-cca4-400a-b52e-ae5e9c7057a8.png)

I want to render a chart with some aggregated data sent by the widget in the self.ctx.data object. 
The callBack function onDataUpdated is called several times and I would like to render the chart on the latest call to self.onDataUpdated, with the "latest" content of the object self.ctx.data.

My question is : 

How to know that the call to the callBack function self.onDataUpdated is the last, and that the content of the object self.ctx.data is complete.

I noticed that there is a method "self.onLatestDataUpdated", but I my custom widget context it isn't executed.
Maybe I am missing a point, and the latest data is already in an object of the self object, but I did not find it.

**Environment**

 * OS:  Debian Ubuntu
 * ThingsBoard: 3.4.3PE-1
 * Browser: Firefox 109.0

**Comment by clemjrt** [comment]
I am still facing the same issue, any help would be appreciated, or any information about why does it work like this; Ty by advance

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
