### ISSUE TITLE
Cassandra error

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#802]
I'm running TB + Cassandra docker but after some time (30 min) the Cassandra database does not work and when I try to log in i get the following error.

> All host(s) tried for query failed (tried: cassandra/192.168.10.10:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [cassandra/192.168.10.10] Pool is busy (no available connection and timed out after 5000 MILLISECONDS)))

**Comment by vparomskiy** [comment]
1. How many resources are allocated to the Cassandra instance?
2. How many concurrent requests are sent to Cassandra?

Cassandra is a great database but it requires a lot of resources to work properly. Minimal instance for Cassandra must have  4 GB RAM and at least 1 dedicated CPU

**Comment by untilbit** [comment]
1.  Cassandra is running alongside TB in the same server. The resources are allocated by the system or docker.

    - RAM: 16 GB
    - CPU:  2 vCPU with 2 threads per core of an Intel Xeon CPU E5 v4 @ 2.30GHz
    - OS: Ubuntu 16.04

2. I have a script that sends a message every 0.6 seconds.

**Comment by vparomskiy** [comment]
It is really strange.  What version of thingsboard are you using?

Could you please upload those log files for investigation
1. Cassandra debug.log -> /var/log/cassandra/debug.log
2. Thingsboard log -> /var/log/thingsboard/thingsboard.log

**Comment by untilbit** [comment]
I'm using TB 2.0.0 compiled from last commit (Update Rule Nodes help links.) of develop/2.0 branch.

These are the logs. Are huge.

[cassandra-debug.log](https://github.com/thingsboard/thingsboard/files/2030498/cassandra-debug.log)
[thingsboard-debug.log](https://github.com/thingsboard/thingsboard/files/2030499/thingsboard-debug.log)

**Comment by vparomskiy** [comment]
I do not see any problems in the Cassandra. Also, according to Thingsboard logs, there were only 80 requests to the Cassandra for the last 30 seconds. It is a very low number. But some of those requests were timed out. Thet is the reason why Cassandra stops responding - all connections in the pool marked are marked as failed.

Could you please tell:
1. How Is Rule Chain configured and what nodes are you using. You can export your configured Rule Chains to the json and attach to this issue.
2. Do you make any read REST API calls right before Cassandra stops responding?

**Comment by untilbit** [comment]
I noticed now that Cassandra stops just after running the python script that sends messages to TB via MQTT.

The rules I have are imported from a previous compiled version.

Let me a few minutes to delete the rules and create them again to see if this issue disappears.

**Comment by vparomskiy** [comment]
Please share also python script so we can test it locally.

**Comment by untilbit** [comment]
The python script is simple, it was working before:

[pythonScript.py.txt](https://github.com/thingsboard/thingsboard/files/2030834/pythonScript.py.txt)

**Comment by vparomskiy** [comment]
The issue will be resolved soon. But right now, as a workaround, you can disable debug mode from all nodes. After this, Cassandra connection pool will work properly.
