### ISSUE TITLE
thingsboard is Unrecognized service

### ISSUE THREAD

**Issue by Corybyte** [thingsboard/thingsboard#8021]
I ran into a new problem;
Linux distribution version: ubuntu18.04;
java version: jdk11;
thingsboard version: 3.4.3-1;
I followed the textbook and successfully executed sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
Unable to execute sudo service thingsboard start;
The error is as follows
`thingsboard is Unrecognized service`

**Comment by Backdraft007** [comment]
Can you try to enable the service?
`sudo systemctl enable thingsboard`

**Comment by Corybyte** [comment]
> 您可以尝试启动该服务吗？ `sudo systemctl enable thingsboard`

我尝试在 root 用户下之下了 
systemctl enable thingsboard
结果如下
Failed to enable unit,unit thingsboard.service does not exit

**Comment by Corybyte** [comment]
> 您可以尝试启动该服务吗？ `sudo systemctl enable thingsboard`

I tried the following under the root user
systemctl enable thingsboard
The result is as follows
Failed to enable unit, unit thingsboard.service does not exit

**Comment by Backdraft007** [comment]
Can you try to remove and reinstall thingsboard
`dpkg -r thingsboard`
`dpkg -i thingsboard-3.4.3.deb`

**Comment by ban2derlog** [comment]
do you tried to change directory to script location and run it with **_sudo ./install.sh_**?
