### ISSUE TITLE
[Feature Request] PE API: add type parameter to getAssetsByEntityGroup endpoint

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8030]
It would be nice to get assets filtered by group and type in single API call. I suggest to add `type` parameter to the [getAssetsByEntityGroup ](https://cloud.thingsboard.io/swagger-ui/#/asset-controller/getAssetsByEntityGroupIdUsingGET) endpoint.

As of 3.4.3, type filtering already is [getTenantAssetsUsingGET](https://cloud.thingsboard.io/swagger-ui/#/asset-controller/getTenantAssetsUsingGET) and [getUserAssetsUsingGET](https://cloud.thingsboard.io/swagger-ui/#/asset-controller/getUserAssetsUsingGET)

**Comment by elpollo12** [comment]
Hi @devaskim , do you know if this was implemented? I can't get the list of assets by group from self.ctx.entityGroupService or self.ctx.assetService

**Comment by devaskim** [comment]
@elpollo12 I don't know exactly but seems like not. Try to `console.log(self.ctx.entityGroupService)` to list all available methods.
