### ISSUE TITLE
[Bug] Msg Payload in Rule Engine doesn't allow semicolons

### ISSUE THREAD

**Issue by fsanna23** [thingsboard/thingsboard#8049]
**Describe the bug**
I'm using a Rest API Call node to request authorization data to an external service. The payload that is returned from that service has this structure:

```
<userId>;<sessionId>
```
The node returns this string as msg payload output to the next node. Therefore I need to use a transform script node to actually split this string. I noticed that the node (and I suppose every other node) can't handle raw strings with semicolons as payloads, returning this error when I activate the debug mode:

```
java.lang.RuntimeException: SyntaxError: Unexpected token ; in JSON at position 7 in at line number 1
```

**Server Environment**
* own setup
  * Cloud Infrastructure
  * ThingsBoard CE Version 3.5
  * OS Name and Version Ubuntu

**Client Environment**
**Desktop**

* OS: Microsoft Windows 10
* Browser Google Chrome
* Version 109.0.5414.120

**To Reproduce**
1. Create a rule chain
2. Add a generator node that triggers the chain, and make it send it message whenever
3. Add a Rest API Call node that requests something to an endpoint which returns a string with the structure mentioned above
4. Add a transform script node that is linked to the previous node with a "Success" rule
5. Enable debug on the transform script node
6. Browse the debug messages of the node, filtering for the OUT messages
7. See the error like the one above

**Expected behavior**
I should be able to pass strings with ";" as payloads from one node to another.

**Screenshots**
![Immagine 2023-02-07 111124](https://user-images.githubusercontent.com/26057524/217216182-65f48088-270a-423a-adbb-22691189f1c9.png)

**Comment by devdoob** [comment]
Need some more info. Can you share form thingsboard UI what you receive from Rest API and how you are forwarding it to next node?
