### ISSUE TITLE
custom widgets

### ISSUE THREAD

**Issue by quirosaur** [thingsboard/thingsboard#805]
Hi!

Can i include external scripts to my widgets?

i.e. bootstrap or https://github.com/dc-js/dc.graph.js

as in normal html page i would use <script></script> tag?

**Comment by vparomskiy** [comment]
Yes, just add it to the resources section
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#resourceshtmlcss-section

**Comment by quirosaur** [comment]
marvelous! thank you 👍
