### ISSUE TITLE
[Bug] windget trip animation bad value get from timeserie string parameter

### ISSUE THREAD

**Issue by loicHercogener** [thingsboard/thingsboard#8052]
**Describe the bug**
On the windget trip animation, I have bad value with Entity with parameters with string time serie. I don't get the expected string value but only "0.00". 

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version PE
  

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: windows
* Browser firefox

**Expected behavior**
exected to get the string good string value of a field time series. 
**Screenshots**
![image](https://user-images.githubusercontent.com/124673070/217256284-d5e1978a-fcf2-4bcd-bb64-225241452bad.png)
in this exemple the map is configure to show for the label the field "cause". We get on the map 0.00 but on the table we get the good value "Regular"

**Comment by devdoob** [comment]
Dont know what exactly happening here, but I encountered similar problem in one of my project.

try changing this "Data aggregation" option in dashboard timewindow to **NONE**

![image](https://user-images.githubusercontent.com/1464600/217330784-dcf0c3a3-4c55-4289-8905-9eb755744fe4.png)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
