### ISSUE TITLE
[Feature Request] access attribute values in post-processing function in Timeseries Chart Widget

### ISSUE THREAD

**Issue by gednz** [thingsboard/thingsboard#8066]
I have raw data that needs to be multiplied by a scaler value (server_attribute) before being graphed.

I would like to be able to access the scaler value attribute in the post-processing function of a data key in the timeseries line chart widget.

This could be done in the rule engine, however changes to the attribute value would only affect data going forward. I want to be able to update both past and future data.

I'd also be interested to know if there is a way I could do this with a custom version of the timeseries widget?

**Comment by mykhailokornieiev** [comment]
Hi
This feature request is rejected since it will be a performance killer and goes against the design for both Thingsboard and Timeseries widgets.
