### ISSUE TITLE
How to add Polygon data to image map on things board

### ISSUE THREAD

**Issue by azeezatmusty** [thingsboard/thingsboard#8069]
I am trying to create polygon on image map using the data I have manipulated on my Javascript part. I am trying to replicate the same thing on this [Link Stackoverflow](https://stackoverflow.com/questions/55090560/adding-polygon-data-to-an-osm-map-on-thingsboard)

When I copied the code to  my custom widget , These two lines are throwing errors and I don't know how to fix it.

**self.ctx.map.configureLocationsSettings()**;   This throw undefined

**tbMap.map.createPolygon(latLangs, self.ctx.settings, location, true, null);**
![srnshot](https://user-images.githubusercontent.com/124904250/217865337-cf1c4bb8-d901-4258-bbff-0184b8f032bf.png)

How do I fix this issue, I don't want to use the custom polygon settings because I need to manipulate some of my data as I need to show the polygon for a group of devices with the same relations.

Here is a screenshot of the solution on Stackoverflow
![srnshot](https://user-images.githubusercontent.com/124904250/217859548-b8a0c63f-bec0-4579-b868-e8f89d77c81b.png)

And I will also like to get a link where I can read the documentation for these functions, there is nothing on the website that address deep topics like this.

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
