### ISSUE TITLE
unable to start Thingsboard on a raspberry Pi 3 with latest raspian  Error starting Tomcat

### ISSUE THREAD

**Issue by vongomben** [thingsboard/thingsboard#807]
Possibly relatet to [this issue](https://github.com/thingsboard/thingsboard/issues/450), even though I'm using version 1.4 

This is the error I get by

```
cat /var/log/thingsboard/thingsboard.log | grep ERROR
```

`ERROR o.s.b.c.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#28f273' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#28f273': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
`

**Comment by jacklicn** [comment]
try run thingsboard/application/target/bin/install/install_dev_db.sh

**Comment by vparomskiy** [comment]
Did you execute installation script ?
`sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo`

https://thingsboard.io/docs/user-guide/install/rpi/#run-installation-script

**Comment by SergMeleshko** [comment]
Hello @vongomben 
Is the problem still relevant?
