### ISSUE TITLE
[Question] What is the minimum value limitation of JWT_TOKEN_EXPIRATION_TIME?

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#8073]
**Component**

 * Generic

**Description**

For debug reason, i tried to set JWT_TOKEN_EXPIRATION_TIME to 60 seconds, but seems didn't work, is there a minimum value limitation of JWT_TOKEN_EXPIRATION_TIME?

**Comment by devaskim** [comment]
Here is [validation procedure](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsValidator.java#L35-L50). Maybe this helps you

**Comment by maksonlee** [comment]
Thanks for the information.
