### ISSUE TITLE
[Critical Bug] PE: Custom translations don't load

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8074]
**Describe the bug**
At the moment our custom translation file (English) includes 100 records. We would like to use translations for customer dashboards, but we can't because from time to time (lately often) we see only translation placeholders (see **Screenshots** section).

I resetted cache multiple times in the following way, but it doesn't help
![cache](https://user-images.githubusercontent.com/86909129/218056888-6b445fb6-6afb-4e5a-bdbb-5deac4312fc7.jpg)

**Your Server Environment**
* own setup
  * Azure, monolithic
  * PE 3.4.3

**Client Environment**
Different Chromium based browsers on desktop and mobile.
Browser language - only English. Browser Region - USA

**Expected behavior**
Just should work.

**Screenshots**
![translations](https://user-images.githubusercontent.com/86909129/218054107-7f3c25ec-88e8-404b-ae65-f2b8ca0c8ecf.jpg)

**Comment by ChantsovaEkaterina** [comment]
Hello, @devaskim 
The fix for custom translation loading was included in the TB 3.4.4 version that was released recently.
Here is a related issue #7921 .

**Comment by devaskim** [comment]
@ChantsovaEkaterina thanks, will upgrade asap and test
