### ISSUE TITLE
why cassandra write didn't use batch write

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#8076]
**Component**

 * Generic

**Description**
why cassandra write didn't use batch write,while postgres and other timeseries data use batch write

**Environment**

 * ThingsBoard: 3.3.4.1

**Comment by pon0marev** [comment]
Cassandra's architecture prioritizes scalability, fault tolerance, and high availability, which can make batch writes less convenient than in traditional relational databases such as PostgreSQL.
In Cassandra, each write operation is typically directed to a specific node responsible for processing data based on a partition key. This node then coordinates with other nodes to ensure data consistency.
