### ISSUE TITLE
[Bug]  Request Timing  out in Version Control to Github

### ISSUE THREAD

**Issue by tararowell** [thingsboard/thingsboard#8077]
**Describe the bug**

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Linux Mint
* Browser : Brave
* Version: [Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)](https://brave.com/latest/)

**To Reproduce**
1. Go to System Settings---> Repository Settings.'
2. Click on 'Check access'
3. See error: 'Request Timeout'

**Expected behavior**
Connection to GH is made with success or failure
**Screenshots**

![image](https://user-images.githubusercontent.com/119680978/218311979-c32a3b09-6f93-4736-8276-b30a13f0b077.png)

**Additional context**
THe site did an initial link to GH and I do have a repo there with the proper structure that the TB made.  However, it no longer connects to keep the code under version control.

**Comment by ban2derlog** [comment]
hi,
do you check browser console for errors?
also, do you set git repo for SSH or HTTPS?
![image](https://github.com/thingsboard/thingsboard/assets/33271053/bdacf5b0-38a4-495b-8a5a-9616c1cc0ce1)
