### ISSUE TITLE
Lists dont work

### ISSUE THREAD

**Issue by Maxwh21** [thingsboard/thingsboard#8083]
![2af6a9d3-9965-407b-932a-1ff057a0b9d2](https://user-images.githubusercontent.com/103750350/218775539-331e5eda-0d81-4fb5-88a6-540b3ecb00ac.jpg)
![0ff0e46e-745f-4dd1-b0a1-ee7fd5cd062a](https://user-images.githubusercontent.com/103750350/218775553-9832ec03-b325-415d-b2ef-c90307e71d24.jpg)
![cf1a0126-73af-4295-b3ec-2e4259b89f7e](https://user-images.githubusercontent.com/103750350/218775564-d7346548-53e8-4453-9386-b51535507a43.jpg)
Am I missing something here or do lists just not work

**Comment by Maxwh21** [comment]
Turns out they do work, the documentation is just wrong:
using .push instead of .add works

**Comment by trikimiki** [comment]
This works for me:
![image](https://github.com/thingsboard/thingsboard/assets/41070061/3393e8c4-4f6c-4430-ab73-611d365f4e85)
Most likely, you are using JS instead of TBEL.
