### ISSUE TITLE
Import deviceService into widget container html code

### ISSUE THREAD

**Issue by f-dalila** [thingsboard/thingsboard#8085]
Hello

I am trying to get device types using deviceService.getDeviceTypes() function. I use widget container widget on my dashboard. In html code of widget container I wrote code shown on next figure, but it doesn't work. There is problem with injector and deviceService variables.
![script](https://user-images.githubusercontent.com/93919664/218988762-c71502b8-ae41-482d-85b6-57040c71012f.jpg)

Can anyone help me?

**Comment by devaskim** [comment]
Are you using default HTML widget or custom one?
Default HTML widget doesn't provide access to context.

**Comment by f-dalila** [comment]
I am using default one. Thank you devaskim for you answer.
