### ISSUE TITLE
How to define Device Profile of device in Rule Chain

### ISSUE THREAD

**Issue by f-dalila** [thingsboard/thingsboard#8087]
**Component**

 * Rule Engine
 
Does anyone know how to define Device Profile of device in Rule Chain? So, when new device is added to Thingsboard, its Device Profile will be defined in Rule Chain.

Thanks

**Comment by devaskim** [comment]
Use REST API node and [this TB REST endpoint](https://demo.thingsboard.io/swagger-ui/#/device-controller/saveDeviceUsingPOST).
Here is how to [get API token in Rule Chain](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/tb_api_token).
