### ISSUE TITLE
Does anybody know how to send RPC command to multiple devices from rule chain? This is my situation, I have a device that defines some parameters. It can trigger LED or buzzer of some other devices, depends on the parameters value. I managed to send to a single device by using change originator. Since it only support a single entity, obviously, how can I send to the other devices.

### ISSUE THREAD

**Issue by quanghuyTiPiCi** [thingsboard/thingsboard#8091]
Does anybody know how to send RPC command to multiple devices from rule chain? This is my situation, I have a device that defines some parameters. It can trigger LED or buzzer of some other devices, depends on the parameters value. I managed to send to a single device by using change originator. Since it only support a single entity, obviously, how can I send to the other devices.

_Originally posted by @parcox in https://github.com/thingsboard/thingsboard/issues/1232#issuecomment-933274635_

**Comment by myroslav-tb** [comment]
Hello @quanghuyTiPiCi, you can use an example from our documentation to sent the request to multiple devices at once.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/rpc-request-tutorial/

If you using Professional edition, you can also try to use the “Duplicate to group” or “duplicate to related node” to copy message to multiple entities.

Best regards,
Myrosalv

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
