### ISSUE TITLE
[Bug] Action Node in Rule Chain "Create Alarm" not updating alarm when using TBEL default code for details

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#8100]
**Describe the bug**
After creating an alarm in the rule chain using the "Create Alarm" action node, the alarm is created again instead of being updated.
I observed this behaviour when having TBEL as programming language. Switching to JS fixed the problem.

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

* OS: macOS
* Browser: Chrome
* Version: 109.0.5414.119 (Official Build) (x86_64)

* Connectivity: HTTP integration

**To Reproduce**
1. Follow tutorial https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/
2. Leave TBEL default code and save
3. Generate fake date for device to trigger the generation of alarm several times
4. For each new telemetry above the set threshold a new alarm is CREATED instead of UPDATED.

**Expected behavior**
After the alarm is created, any value above the threshold should UPDATE the alarm and not CREATE a new one.

**Screenshots**
![image](https://user-images.githubusercontent.com/27728926/219484453-e0026ffd-3f71-4aeb-8a3e-dd04aa86c86f.png)

**Comment by ezeroldan24** [comment]
Good day! Did you find a solution to the problem?

**Comment by Civilduino** [comment]
I used JavaScript instead of TBEL and it works. TBEL is recommended because it is faster executing, but until the bug is fixed I will have to use JS.

**Comment by ashvayka** [comment]
I have serious doubts that TBEL is the root cause of this. Faster execution of the details script may have caused a higher probability of the race condition. Alarm Service was significantly refactored in 3.5 to eliminate the chance of race conditions. Stay tuned for the new release.
