### ISSUE TITLE
[Question] Triggering Multiple Alarms for Multiple Input Parameters in Rule Chain

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard#8103]
**Component**

 * Rule Engine
 
**Description**
I have a simultaneous input of 4 temperature parameters into the rule chain, i.e. t1, t2, t3, t4. How do I code the switch filter so that I can trigger multiple alarms if each condition is met? If I use 4 if statements, only the alarm for the first parameter that meets the condition is triggered. The rest are ignored even though they meet the alarm conditions. 

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.4.3
 * Browser: Chrome 110.0.5481.100 (64 bit)

**Comment by devaskim** [comment]
There are at least 2 ways:
1. Forward input packet to 1....N checking scripts, then to 1....N  Create/Clear Alarm nodes.
2. In single Script Transformation node check all alarm cases and [create array of alarms](https://github.com/thingsboard/thingsboard/issues/6594#issuecomment-1141037479). Then forward the array to Filter Script to split alarms that need to be created or cleared. And finally forward to single pair of Create/Clear Alarm nodes.

**Comment by cowherdboy** [comment]
Thank you @devaskim . My initial thought was method 1 but I can't go from Input to multiple "Filter - Script" nodes. The Input node can only connect to a single script node. When I drag from Input to a second script node the input to the first script node disappears. Can you share a graphical node connection? Maybe I am doing something wrong.

**Comment by devaskim** [comment]
@cowherdboy Unfortunately, Input node doesn't support multiple links. You can add Message Type Switch node after Input and before Filter

**Comment by cowherdboy** [comment]
@devaskim That did it. Thank you so much.
