### ISSUE TITLE
Is there any way to customize HTTP post request URL?

### ISSUE THREAD

**Issue by par1111** [thingsboard/thingsboard#8115]
I am using Things board Community Edition
Here I am using this URL:
 - http(s)://host:port/api/v1/$ACCESS_TOKEN/telemetry
 
But I want to use my custom string instead of telemetry:
 - http(s)://host:port/api/v1/$ACCESS_TOKEN/XYZ
 is there any way so that I can customize request URL?

**Comment by devaskim** [comment]
In CE you could patch server side code

**Comment by par1111** [comment]
> In CE you could patch server side code.
> 
> As alternative, you could try HAProxy or Nginx to redirect incoming requests

yess, but how can i patch server side code as I am using thingsboard on local server(windows+docker).

**Comment by devaskim** [comment]
[Patch and build Docker image from source code](https://thingsboard.io/docs/user-guide/install/building-from-source/)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
