### ISSUE TITLE
[Question] pg_dump not working in docker

### ISSUE THREAD

**Issue by andonoc** [thingsboard/thingsboard#8116]
**Component**

 * Installation
 * Generic

**Description**
Mi goal is to move to a new machine.
on many issues ``pg_dump`` is recommend for migrating and backup.

``docker exec <CONTAINER_NAME> pg_dumpall -c -U postgres | gzip > postgres-data.tar.gz``
throws
`` pg_dumpall: error: could not connect to database "template1": connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "postgres" does not exist``

logging in the container as root 
``docker exec -it -u 0 <CONTAINER_NAME> bash``

check service status
`` service postgresql status``
``12/main (port 5432): down``

restart postgres service
``service postgresql start``
``Starting PostgreSQL 12 database server: mainError: Port conflict: another instance is already running on /var/run/postgresql with port 5432 ... failed!
 failed!``

The postgresql LOGs are empty

But the interresting thing is that thingsboard is always working, no data loss 

What is happening here?? 

how can i migrate?

**Environment**

 * OS:  Docker on Ubuntu 22
 * ThingsBoard: v.3.4.3 in memory with postgres monolithic installed with Docker compose

**Comment by devaskim** [comment]
Did you mount directory on host machine for Postgres data? If yes, just copy it another machine

**Comment by yanngit** [comment]
Same issue for me : 
```
pg_dump: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
```

**Comment by andonoc** [comment]
Ok, i copied the mounted directory to the new host and it seems that everything is working, nice!! Thank you
Only a question,  how could it be that postgres is down but thingsboard is working????
