### ISSUE TITLE
[Question] Triggering a widget action programmatically

### ISSUE THREAD

**Issue by MichaelRHaddad** [thingsboard/thingsboard#8120]
**Component**

 * Generic

**Description**
Is there a way to trigger a widget action programmatically?

**Environment**
 * ThingsBoard 3.4.3 Professional

**Comment by devaskim** [comment]
Here is how I call header action:
```
const name = 'My action name';
let actionDescriptor = self.ctx.actionsApi.actionDescriptorsBySourceId.headerButton.find(descriptor => descriptor.name === name);
if (actionDescriptor) {
    self.ctx.actionsApi.handleWidgetAction({}, actionDescriptor, null, null, { });
}
```

**Comment by MichaelRHaddad** [comment]
I would be grateful if you could elaborate a bit because I am not sure I understand. I will explain what exactly I am trying to do:

I have a simple widget, with a `<button id="myButton">TEST</button>`:
![image](https://user-images.githubusercontent.com/41021500/220874619-630fbd50-1451-49ea-ac27-faad9abf2d99.png)

I would like a popup to show when I click on my button. I tried two approaches:

The first was to create an action and invoke it from code. The problem is that the only action source available is "Widget header button".
![image](https://user-images.githubusercontent.com/41021500/220874966-c98e3f94-3fef-468e-81df-5b4c94da106b.png)

After searching a bit in the issues in this repository, I came across the following code:

```
self.actionSources = function() {
    return {
        'elementClick': {
            name: 'widget-action.element-click',
            multiple: true
        }
    };
}
```

I added that to the widget js, and indeed, suddenly a new option appeared:
![image](https://user-images.githubusercontent.com/41021500/220875632-a3c7a780-0f96-4785-83a2-17b790bd505d.png)

However, I did not know how to wire the button to the action.

The second approach was to use this function from the widget js:
` widgetContext.actionsApi.openDashboardStateInPopover`
but I didn't know what arguments to pass.

What should I do? Is there a documentation for this anywhere? If not, could you please explain? Thanks.

**Comment by MichaelRHaddad** [comment]
@devaskim Thank you! It works. Is there documentation for these things?

Another question, if you do not mind. How can I pass data between the states? The widget in the popup generates a JSON, and I would like the root state to have access to it. How can I Achieve this?

**Comment by HaydenBurrows** [comment]
Not sure if this helps or hinders.  You don't need to create a custom latest values widget to do what you want (open a state by button).

You can use the built in latest value widget, use html ```<button id="myButton">TEST</button>``` and choose the HTML element click as above. You can choose the popover shown below.

![image](https://user-images.githubusercontent.com/69659611/221387975-2c0c44f9-fc99-4ad9-9312-03b874f053fc.png)

If you want to use custom html using popover you can try this.  You can pass in parameters from the previous state.
![image](https://user-images.githubusercontent.com/69659611/221388389-6f091308-b089-48c0-8790-bcfc97e81332.png)
Or try this for another example #7504
For more information you can click help.  This will show some examples and also point you in the direction of code.

![image](https://user-images.githubusercontent.com/69659611/221388174-131c9384-cf03-4ac6-99f3-7590e601d365.png)

**Comment by devaskim** [comment]
@HaydenBurrows As I understand, the main goal is to get result from another state.

By the way, there is no need to `stringify` and `parse` the result of `getStateParams()`

**Comment by HaydenBurrows** [comment]
@devaskim cool, just thought I would offer some suggestions which have helped me.  I have found the issues a wealth of information when the documentation is slim.  I have enjoyed your questions and answers also.

Thanks for that info about getStateParams().  I am not a programmer/coder so use a lot of copy/paste and console.log to understand what is happening.

**Comment by devaskim** [comment]
@HaydenBurrows  Agree, `console.log` is our salvation)))
And thanks for participating

**Comment by MichaelRHaddad** [comment]
[HaydenBurrows](https://github.com/HaydenBurrows) Thank you for the information. It is helpful.
[devaskim](https://github.com/devaskim) Thanks too you too. You are very helpful.
And indeed. The state shown in the popup generates a *custom* JSON object in response to some user interaction. I would like to pass it to the root state. How can I do this?

**Comment by devaskim** [comment]
@MichaelRHaddad If both widgets (in root and popop states) are custom, then try `broadcastService`
```
let broadcastService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('broadcastService'));

// Send JSON
broadcastService.broadcast('EventName', json);

// Listen to response
broadcastService.on('EventName', (event, data) => {
    console.log('Data', data);
});
```

**Comment by MichaelRHaddad** [comment]
@devaskim It works. Thank you very much.
Last question in this issue: are `$scope` and `$injector` part of Thingsboard or of Angular? Where can I read about them? There is not much documentation about them in the widget development guide.

**Comment by devaskim** [comment]
`$injector` - Angular
`$scope, ctx` - Thingsboard, here is [code link](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/widget-component.models.ts#L116)
