### ISSUE TITLE
[Bug] thingsboard not using ip to connect to remote kafka 

### ISSUE THREAD

**Issue by longGr** [thingsboard/thingsboard#8125]
**Describe the bug**
I have setup a remote kafka server that I want to use for thingsboard. It is working fine and also thingsboard is able to successfully use it, as soon as I set the server's IP and hostname in the `/etc/hosts` file. This however should not be the case when I set the 

    export TB_KAFKA_SERVERS=10.10.10.10

in the `/etc/thingsboard/conf/thingsboard.conf` file to an IP. I don't think it should resolve the IP for a hostname to resolve the hostname to a IP again. 

In my case I get the error in `/var/log/thingsboard/thingsboard.log`:

    Error connecting to node MY_SERVER_NAME.MY_DOMAIN.TLD:9092 (id: 0 rack: null)
    java.net.UnknownHostException: MY_SERVER_NAME.MY_DOMAIN.TLD: Name or service not known

**Your Server Environment**
* own setup
  * local infrastructure 
  * ThingsBoard Version: 3.4.4PE
  * OS Name and Version: debian 11

**To Reproduce**
1. Install thingsboard like explain the doku (without the kafka & zookeeper stuff
2. On a different server create the kafka and zookeeper service and configure them to allow remote connections
3. set the FQDN of the server to something in the same domain (for example SV1.DOMAIN.TLD and SV2.DOMAIN.TLD)
4. adjust the `/etc/thingsboard/conf/thingsboard.conf` file to export `export TB_KAFKA_SERVERS=IP_OF_KAFKA_SERVER`
5. start thingsboard

**Expected behavior**
Thingsboard uses the IP to connect to the remote kafka server

**Comment by thieleon** [comment]
no idea?

**Comment by pon0marev** [comment]
Most likely you need to configure advertised.listeners for your kafka. Go to config file: `sudo nano /usr/local/kafka/config/server.properties`

Uncomment the line and replace YOU_KAFKA_HOST:
```
advertised.listeners=PLAINTEXT://YOU_KAFKA_HOST_NAME:9092
```
