### ISSUE TITLE
thingsboard is Unrecognized service

### ISSUE THREAD

**Issue by smarthhl** [thingsboard/thingsboard#813]
when i installed the service , start the service ,but tell me "thingsboard is Unrecognized service",
my env : centos7+jdk1.8

**Comment by vparomskiy** [comment]
What Thingsboard version are you using?

**Comment by smarthhl** [comment]
thingsboard (v2.0.0)

**Comment by smarthhl** [comment]
@vparomskiy thingsboard (v2.0.0)

**Comment by vparomskiy** [comment]
Thingsbaord installation on the Centos was verified and works as expected. Could you please provide more details how you install Thingsboard.

1. Are you installing rpm package?
2. Please provide an output of the package installation command

Also, here are instructions how to install Thingsboard (note - use **Centos** tab for commands that should be executed on Centos)
https://thingsboard.io/docs/user-guide/install/linux/#thingsboard-service-installation

**Comment by ZTXZM** [comment]
@vparomskiy 
hello, i had meet the same problem。
my evn: centos7 jdk1.8 thingsboard (v2.0.0)
The installation process is as follows:
============
[root@VM000000812 thingsboard]# sudo rpm -Uvh thingsboard-2.0.rpm
Preparing...                ########################################### [100%]
   1:thingsboard            ########################################### [100%]
[root@VM000000812 thingsboard]# 

root@VM000000812 install]# 
[root@VM000000812 install]# sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v2.0.0)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Loading demo data...
Installation finished successfully!
ThingsBoard installed successfully!
[root@VM000000812 install]# 

[root@VM000000812 /]# 
[root@VM000000812 /]# sudo service thingsboard start
thingsboard: unrecognized service
[root@VM000000812 /]# 
=============
Could i start the service using the direct start srcipt of the thingsboard install of using the service commond?

**Comment by vparomskiy** [comment]
I have launched Centos 7 instance in the Google cloud. Here are OS version info:

[paromskiy@centos-tb-verify ~]$ **hostnamectl**

>    Static hostname: centos-tb-verify
>          Icon name: computer-vm
>            Chassis: vm
>         Machine ID: 0d3ea3339cb114c74c2d7e28a7489805
>            Boot ID: 8e96f5ede4c143a0b1a0327c293e80ce
>     Virtualization: kvm
>   Operating System: CentOS Linux 7 (Core)
>        CPE OS Name: cpe:/o:centos:centos:7
>             Kernel: Linux 3.10.0-862.3.2.el7.x86_64
>       Architecture: x86-64
> 

[paromskiy@centos-tb-verify ~]$ **rpm --query centos-release**

> centos-release-7-5.1804.el7.centos.2.x86_64

After Java instalation, I did the following:
1.
`wget https://github.com/thingsboard/thingsboard/releases/download/v2.0/thingsboard-2.0.rpm`

> 
> 100%[=====================================================================================================================================================================================================>] 99,460,550  7.55MB/s   in 12s    
> 2018-05-31 10:48:38 (7.61 MB/s) - ‘thingsboard-2.0.rpm’ saved [99460550/99460550]

2.
`sudo rpm -Uvh thingsboard-2.0.rpm`

> Preparing...                          ################################# [100%]
> Updating / installing...
>    1:thingsboard-0:2.0.0-1            ################################# [100%]


3. 
`sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo`

>  ===================================================
>  :: ThingsBoard ::       (v2.0.0)
>  ===================================================
> Starting ThingsBoard Installation...
> Installing DataBase schema...
> Installing SQL DataBase schema...
> Loading system data...
> Loading demo data...
> Installation finished successfully!
> ThingsBoard installed successfully!

4. 
`sudo service thingsboard start`

> Redirecting to /bin/systemctl start thingsboard.service

**And Thingsboard service started as expected:**

> [paromskiy@centos-tb-verify ~]$ **ps aux | grep things**
> 
> thingsb+  1790  0.0  0.0 113176  1556 ?        Ss   10:50   0:00 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
> thingsb+  1804 99.5  6.9 2943748 252212 ?      Sl   10:50   0:24 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard -jar /usr/share/thingsboard/bin/thingsboard.jar
> paromsk+  1847  0.0  0.0 112704   956 pts/0    R+   10:50   0:00 grep --color=auto things
> 
> **sudo service thingsboard status**
> Redirecting to /bin/systemctl status thingsboard.service
> ● thingsboard.service - thingsboard
>    Loaded: loaded (/usr/lib/systemd/system/thingsboard.service; enabled; vendor preset: disabled)
>    Active: inactive (dead)
> May 31 10:50:17 centos-tb-verify thingsboard.jar[1790]: ===================================================
> May 31 10:56:52 centos-tb-verify systemd[1]: Stopping thingsboard...
> May 31 10:56:53 centos-tb-verify systemd[1]: Stopped thingsboard.
> May 31 10:57:08 centos-tb-verify systemd[1]: Started thingsboard.
> May 31 10:57:08 centos-tb-verify systemd[1]: Starting thingsboard...
> May 31 10:57:12 centos-tb-verify thingsboard.jar[2322]: ===================================================
> May 31 10:57:12 centos-tb-verify thingsboard.jar[2322]: :: ThingsBoard ::       (v2.0.0)
> May 31 10:57:12 centos-tb-verify thingsboard.jar[2322]: ===================================================
> May 31 10:57:13 centos-tb-verify systemd[1]: Stopping thingsboard...
> May 31 10:57:14 centos-tb-verify systemd[1]: Stopped thingsboard.


**An alternative way for running Thingsboard is the following command:**

> paromskiy@centos-tb-verify conf]$ sudo su
> [root@centos-tb-verify conf]# export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard"
> [root@centos-tb-verify conf]# export LOG_FILENAME=thingsboard.out
> [root@centos-tb-verify conf]# export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
> [root@centos-tb-verify conf]# export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql
> 
> [root@centos-tb-verify conf]# /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard -jar /usr/share/thingsboard/bin/thingsboard.jar > out.txt &

**Comment by ZTXZM** [comment]
I tried the alternative way, and it worked. There‘s should be something wrong with the service command on my Linux system. sorry for taking too much of your time. @vparomskiy

**Comment by smarthhl** [comment]
@ZTXZM can you tell me the alternative way?

**Comment by smarthhl** [comment]
@ZTXZM what is password and username?

**Comment by carsickcars** [comment]
> @vparomskiy
> hello, i had meet the same problem。
> my evn: centos7 jdk1.8 thingsboard (v2.0.0)
> The installation process is as follows:
> [root@VM000000812 thingsboard]# sudo rpm -Uvh thingsboard-2.0.rpm
> Preparing... ########################################### [100%]
> 1:thingsboard ########################################### [100%]
> [root@VM000000812 thingsboard]#
> 
> # root@VM000000812 install]#
> [root@VM000000812 install]# sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
> # :: ThingsBoard :: (v2.0.0)
> Starting ThingsBoard Installation...
> Installing DataBase schema...
> Installing SQL DataBase schema...
> Loading system data...
> Loading demo data...
> Installation finished successfully!
> ThingsBoard installed successfully!
> [root@VM000000812 install]#
> 
> [root@VM000000812 /]#
> [root@VM000000812 /]# sudo service thingsboard start
> thingsboard: unrecognized service
> [root@VM000000812 /]#
> Could i start the service using the direct start srcipt of the thingsboard install of using the service commond?

I faced the same problem. How could you solve it ??

**Comment by vparomskiy** [comment]
Did you try to execute commands from **An alternative way for running Thingsboard is the following command:** section (higher in this thread)?

**Comment by carsickcars** [comment]
> Did you try to execute commands from **An alternative way for running Thingsboard is the following command:** section (higher in this thread)?

I executed commands from **An alternative way for running Thingsboard is the following command**,  then have thingsboard thread , but when I curl "http://localhost:8087" (I change the thingsbord.yml port, because 8080 has used by other application),  I get **could't connect to host**
![image](https://user-images.githubusercontent.com/7300422/47776131-9dc47e80-dd2c-11e8-9b1a-13ad9eb03132.png)

**Comment by carsickcars** [comment]
This is my changed thingsboard.yml 
![image](https://user-images.githubusercontent.com/7300422/47776203-cfd5e080-dd2c-11e8-8b22-82698b595115.png)

**Comment by vparomskiy** [comment]
Please share your thingsboard.log file 

From your description it is not clear for me:
1. Is thingsboard process started (ps aux | grep thingsboard)
2. Are there any errors in the log file

**Comment by carsickcars** [comment]
1, Where is  the thingsboard.log?
2, I found when I started thingsboard used "alternative way", after a while the thingsboard thread has accidented shutdown. Please tell me where could I see the log?

**Comment by vparomskiy** [comment]
https://thingsboard.io/docs/user-guide/install/linux/#troubleshooting

/var/log/thingsboard/thingsboard.log

**Comment by carsickcars** [comment]
一,  I know the cause, because the cassandra service is accidented shutdown.  I will check it later. could you tell me some possible cause?

二.  Now I curl "http://localhost:8087" and get the message **{"timestamp":1540978811039,"status":404,"error":"Not Found","message":"No message available","path":"/"}**, Please tell me if it is correct??

**Comment by vparomskiy** [comment]
It is not correct - 200 OK should be returned.
The question is why 404 is returned because if there are any errors in the thingsboard Service - 503 will be returned. Maybe you have some proxy configured (nginx, apache2, haproxy) ?

**Comment by carsickcars** [comment]
Thank you very muchhh!  
 I  must confirm why the cassandra service is accidented shutdown, because when the cassandra service is shutdown, the thingsboard is shutdown too.  
But now I donot know why .  Only the cassandra service is proper ok so I can continue study the thingsboard service.

**Comment by seahandsome** [comment]
Hey, brother, how do you solve the "thingsboard: unrecognized service"?

**Comment by seahandsome** [comment]
when i installed the service , start the service ,but tell me "thingsboard is Unrecognized service",
my env : centos6+jdk1.8

**Comment by nguyendat5307** [comment]
you can try: sudo /usr/share/thingsboard/bin/thingsboard.jar

**Comment by fanie42** [comment]
I solved this problem by changing a setting in the config file (/etc/thingsboard/conf/thingsboard.conf):
`export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard/data"`
should be:
`export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard"`
