### ISSUE TITLE
[Question] How to place sum on top of stacked bar chart?

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard#8132]
Hello, I would like to know if it is possible to place the sum on top of each of the stacked bar. The tooltip is able to show the sum as shown in the figure but would like to know if the sum can be placed as a label on top of each stacked bar. I am using TB 3.4.4 PE.

![energy](https://user-images.githubusercontent.com/6798969/221352991-166be70c-5a58-4778-84b5-1df8a1d0c080.jpg)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
