### ISSUE TITLE
[Question] Declaring "double" "float" variables in TBEL programming

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#8134]
**Component**

 * Rule Engine

**Description**
I need to declare a double variable in TBEL to modify the timestamp to account for the millisecond precision (x1000) but it is not working. It seems that variables are limited to "int" type.
I tried e.g.
var double timestamp;
double timestamp;

**Environment**

 * OS: macOS
 * ThingsBoard: Cloud PaaS
 * Browser: Chrome

**Comment by devaskim** [comment]
For timestamp you could use `Long` type:
```
Long.parseLong(metadata.ts)
```

**Comment by Civilduino** [comment]
Yes, this worked `Long.parseLong(metadata.ts)*1000`.
Thank you @devaskim
