### ISSUE TITLE
[Question] How can I remove the constraints on ts_kv and other similar tables? Cause devices could upload more than one messages in one millisecond.

### ISSUE THREAD

**Issue by leejiaming02** [thingsboard/thingsboard#8136]
ThingsBoard version: 3.4.4
I am using **PostgresSQL** to store data.
There is a constraint on table ts_kv:  **entity_id, key, ts**:
Source code of  dao\src\main\java\org\thingsboard\server\dao\sqlts\insert\sql\SqlInsertTsRepository.java
```
private static final String INSERT_ON_CONFLICT_DO_UPDATE = "INSERT INTO ts_kv (entity_id, key, ts, bool_v, str_v, long_v, dbl_v, json_v) VALUES (?, ?, ?, ?, ?, ?, ?, cast(? AS json)) " +
        "ON CONFLICT (entity_id, key, ts) DO UPDATE SET bool_v = ?, str_v = ?, long_v = ?, dbl_v = ?, json_v = cast(? AS json);";
```
But in our  application scenarios, one device may upload more than 1 message in ont exactly millisecond, and only one message will be stored.
How could I store all the messages in PG, can I remove the constraint? Or I can find the messages in other tables? How could I modify all the codes about similar  table constrains?
Thank you!

**Comment by leejiaming02** [comment]
anyone there?

**Comment by HaydenBurrows** [comment]
Are you saying that one device (**entity_id**), will send a message (**key**) with the same timestamp (**ts**)?  I can't find it now, but I remember seeing a comment similar but the answer was millisecond is the smallest time base possible.

Also this #1277 may be of help.
