### ISSUE TITLE
Query entity relations to show/hide action cell button

### ISSUE THREAD

**Issue by igloodan** [thingsboard/thingsboard#8141]
I've been trying for hours to get an action cell button to show only when an entity has one or more "from" relations.
The below seems to make sense to me but I'm almost certain that the system isn't returning anything for "data.entityId" as that evaluates to false whereas "data.entityType" evaluates to true.

Can anyone help with how to check for "from" relations and show the action button only if there are one or more?

```
let entityRelationService = widgetContext.$scope.$injector.get(widgetContext.servicesMap.get('entityRelationService'));

let deviceRelations = entityRelationService.findByFrom(data.entityId);

if (deviceRelations.length > 0) {
    return true;
} else {
    return false;
}
```

**Comment by igloodan** [comment]
I've managed to work out that the entity ID is accessed using "data.id.id" but I don't understand the returned observable object, is there a simple way to count the number of relations returned by the `entityRelationService.findByFrom()` function?

If I subscribe to this service then the console shows that the requested URL has elements listed as "undefined" rather than using the entity ID I'm putting in there as an argument with...
`let deviceRelations = entityRelationService.findByFrom(data.id.id).subscribe();`

**Comment by devaskim** [comment]
```
entityRelationService.findByFrom(data.id.id).subscribe(
    relations => {
        console.log('Relations', relations);
    },
    error => console.log('Error', error)
);
```

**Comment by igloodan** [comment]
@devaskim 
Thanks for the suggestion, I get error "No enum constant org.thingsboard.server.common.data.EntityType.undefined" as a toast message and the browser console shows that the script is trying to access https://mydomain.com/api/relations?fromId?undefined&fromType=undefined which returns a 400 error.

**Comment by devaskim** [comment]
As `id` you need to pass JS object like:
```
{
    id: "YOUR_DEVICE_UUID",
    entityType: "DEVICE"
}
```

**Comment by igloodan** [comment]
@devaskim 
Again, thanks very much for your help, I couldn't see that that argument needed to be an object anywhere!

I've got the below but it seems that the subscribe is taking longer to the relationship count before the overall function returns so it still returns 0 even when there are 21 relations.

Please can you suggest how I return true for the overall function when the relation count is greater than zero?
```
let relationsCount = 0;
let entityRelationService = widgetContext.$scope.$injector.get(widgetContext.servicesMap.get('entityRelationService'));

let myDeviceId = {
    id: data.id.id,
    entityType: "DEVICE"
};

let deviceRelations = entityRelationService.findByFrom(myDeviceId).subscribe(
    relations => {
        console.log('Relations', relations);
        console.log(relations.length);
        doReturn(relations.length);
    },
    error => {
        console.log('Error', error);
    }
);

function doReturn(relationCount) {
    if (relationCount > 0) {
        return true;
    } else {
        return false;
    }
}
```

**Comment by devaskim** [comment]
>  I couldn't see that that argument needed to be an object anywhere!

Unfortunately, not for all services but there are helpful autocomplete tooltips
![id](https://user-images.githubusercontent.com/86909129/221775194-874d50ef-8174-4db8-9e70-802e8229e8fd.jpg)

 > Please can you suggest how I return true for the overall function when the relation count is greater than zero?

The problem is show/hide function is synchronous, but TB API calls are asynchronous. In other words, the former and the latter will end up at different time point. If action button would have some unique id, you could find it with JQuery selectors, i.e. `$('your_selector', widgetContext.$container)`, but unfortunately it isn't your case, at least I didn't find any id in browser's DevTools.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
