### ISSUE TITLE
”make role chain  root“  java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#815]
![image](https://user-images.githubusercontent.com/10750404/40705014-55e156d0-641c-11e8-9810-a46b03a6f820.png)

![image](https://user-images.githubusercontent.com/10750404/40705109-98b02888-641c-11e8-8cc2-acd30f36a34b.png)

**Comment by caoyingde** [comment]
I come into 2.0 version 1.4 update, I look at the SQL database file added two tables, so I only execute the following script create an empty table, itself is not to add data records, is I now is how to solve these problems?
--------------------------create tables-------------------------------
CREATE TABLE `rule_chain` (
  `id` VARCHAR(31) COLLATE utf8_bin NOT NULL,
  `additional_info` VARCHAR(500) COLLATE utf8_bin DEFAULT NULL,
  `configuration` TEXT COLLATE utf8_bin,
    `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
   `first_rule_node_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`root` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`debug_mode` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`search_text` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
`tenant_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin



CREATE TABLE `rule_node` (
  `id` VARCHAR(31) COLLATE utf8_bin NOT NULL,
  `rule_chain_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
  `additional_info` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
    `configuration` TEXT COLLATE utf8_bin,
    `type` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
   `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
`debug_mode` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`search_text` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin

**Comment by caoyingde** [comment]
@vparomskiy I come into 2.0 version 1.4 update, I look at the SQL database file added two tables, so I only execute the following script create an empty table, itself is not to add data records, is I now is how to solve these problems?
--------------------------create tables-------------------------------
CREATE TABLE `rule_chain` (
  `id` VARCHAR(31) COLLATE utf8_bin NOT NULL,
  `additional_info` VARCHAR(500) COLLATE utf8_bin DEFAULT NULL,
  `configuration` TEXT COLLATE utf8_bin,
    `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
   `first_rule_node_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`root` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`debug_mode` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`search_text` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
`tenant_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin



CREATE TABLE `rule_node` (
  `id` VARCHAR(31) COLLATE utf8_bin NOT NULL,
  `rule_chain_id` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
  `additional_info` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
    `configuration` TEXT COLLATE utf8_bin,
    `type` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
   `name` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
`debug_mode` VARCHAR(31) COLLATE utf8_bin DEFAULT NULL,
`search_text` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin

**Comment by vparomskiy** [comment]
There is an upgrade script that performs all required operations for migrating to version 2.0

https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-200

You should run this command for running this script
`$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=1.4.0`

Or, if you work from IDE, then you can run this class:
`ThingsboardInstallService`
VM Options:
`-Dinstall.data_dir=~/TB_SRC_DIR/application/target/data -Dspring.jpa.hibernate.ddl-auto=none -Dinstall.upgrade=true -Dinstall.upgrade.from_version=1.4.0`

**Comment by vparomskiy** [comment]
Also, you've created table **rule_chain** with **root** column of type varchar, but it should be a **boolean** column

**Comment by caoyingde** [comment]
is solved，tks!
