### ISSUE TITLE
[Question] Is there any option to create one filter which can automatically insert the all data key names to the widget?

### ISSUE THREAD

**Issue by ekrutill** [thingsboard/thingsboard#8152]
**Dashboard
![filtering](https://user-images.githubusercontent.com/116651407/222088138-2ee20728-5ce7-4185-b9e8-4e4d120d5ef4.PNG)

 * UI
 * Generic

Hello, 
I would like to ask, is there any option to create one filter which can automatically insert the all dataKey names to the widget (with timeseries data, not attributes)? 
I am asking it because if there is one object/device with 100 data sources it would be good if I could insert all data sources automatically. 

Thank you in advance! 

 * ThingsBoard: 3.4.4
 * Browser: Google Chrome 109.0.5414.75

**Comment by ekrutill** [comment]
Thank you for the answer.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
