### ISSUE TITLE
[Question] What is the procedure to add packages for widget development

### ISSUE THREAD

**Issue by Shedaim** [thingsboard/thingsboard#8155]
I'm working on Thingsboard 3.4.3 PE

I'm trying to use Minio S3 service inside a widget, without success:
1. **Tried importing the library as a resource:** 
https://cdn.jsdelivr.net/npm/minio@7.0.32/dist/main/minio.min.js
The library loads, but calling Client() returns further issues.

2. **Tried importing Minio as a module in resources:**
https://cdn.jsdelivr.net/npm/minio@7.0.32/+esm
The module fails to load.

3. **Tried installing minio on JS-executor images with Dockerfile:**
```
FROM thingsboard/tb-pe-js-executor:3.4.3PE
USER root
RUN npm install --save minio
USER node
```
I don't seem to find the way to import minio into the widget development instance.

Would appreciate some help on this. 
Of course, Minio is just one feature I'd like to use, so the solution _must enable importing external modules_.

Thank you very much

**Comment by Shedaim** [comment]
Ok, so basically the import works.
What doesn't work is actually the minio.js.
I believe it is made for Node.JS, but we are not running any such capabilities on the widget Development tool. 
So I'm getting this issue:
```
Uncaught ReferenceError: exports is not defined
    <anonymous> minio.js:3
```

failing for the line:
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

Quick research shows this is an issue trying to run node.JS from the browser without tools implementing commonJS like RequireJS.
Any chance to run something like this on a widget or on a rule-chain?

**Comment by devaskim** [comment]
I afraid it is [impossible](https://github.com/paulscherrerinstitute/minio-js-browser)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
