### ISSUE TITLE
[Bug] Microservice Deployment - "Access Denied" message when moving Customer User to different Customer

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8158]
**Describe the bug**
When moving Customer Users from one customer to another it leads to display of error message "Access Denied" although the rights are sufficient for the user to have access to e.g. Device Groups.

This behaviour is only present for Microservice Deployments. On monolithic installations this is not witnessed.

**Your Server Environment**

* own setup
  * Azure Cloud
  * ThingsBoard 3.4.3 PE
  * Microservice Architecture (AKS)

**To Reproduce**
1. Create a new Customer User
2. Change owner of Customer user to different Customer in the Hierarchy
3. Login as Customer User
4. See error message "Access Denied" (although Entities are displayed correctly & rights are sufficient)
5. Stop ThingsBoard services & clear Redis cache
6. Start ThingsBoard services again and login with customer User --> Message is gone

**Expected behavior** 
This should work without having to restart the ThingsBoard services & clear Redis cache each time this happens.

![image](https://user-images.githubusercontent.com/25298332/222387072-0db74261-e21e-4455-af03-d5f2f3e5ae53.png)

**Comment by ban2derlog** [comment]
hi, do you try after changing in hierarchy log in in different browser or Private\Incognito tab?
if you reproduce this - do it always require both tb-node restart and flushing cache, or just flushing cache resolve it?

**Comment by mde2017** [comment]
Hi @ban2derlog,

we did also test it with different browsers/Incognito tab.
Also we tried with a different a client computer.

Both did not work. The error message remained.

**Comment by mde2017** [comment]
Regarding your second question:
We did only test both: tb-node restart and flushing redis cache. 

So I cannot tell if it will also work, without restarting tb-node.

**Comment by mde2017** [comment]
had you modify default values for caching in your deployment?
- no

how many tb-nodes\tb-cores?
- 2

is redis - cluster or standalone?
- cluster

do you use redis only with ThingsBoard or with other your services too?
- only with ThingsBoard

was there errors\warnings in log of tb-node\tb-core when you changed user and when you had login?
- We didn't see any error in the logs, but we will reproduce the error in the next days and investigate further

**Comment by mde2017** [comment]
After updating to 3.4.4 the error does not occur anymore
