### ISSUE TITLE
[Bug] Thingsboard docker not working after 11 months 

### ISSUE THREAD

**Issue by ikanell379** [thingsboard/thingsboard#8179]
Some months ago i deployed thingsboard using docker deployment. Until previous week thingsboard was working perfectly but last days not working at all. The containers seems running but i cannot access anything in the browser.

 docker deployment
  * version: '2.2' docker-compose tag
  * image: "zookeeper:3.5"
  * image: wurstmeister/kafka
  * image: "thingsboard/tb-postgres"

* Windows
* Chrome,Mozilla

Are there any suggestions or similar behaviours ?

**Comment by HaydenBurrows** [comment]
I have more questions than answers unfortunately.

Can you check the thingsboard container logs? 
Can you access the container?
Do you use reverse proxy?
What error do you get in browser?
Have you tried restarting thingsboard container?

Could check disk space, memory on host machine.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
