### ISSUE TITLE
Error [Unknown name value [RULE] in Thingsboard v2.0

### ISSUE THREAD

**Issue by gustavovelascoh** [thingsboard/thingsboard#818]
Hi, I am using Thingsboard v2.0 with docker. I was using v1.4 and updated docker-compose.yaml file. Web interface works ok, but after trying to send data using curl I receive this message:

```
$ curl -v -X POST -d '{"Temperature": 12.0}' http://www.colbits.com.co:8080/api/v1/Cl2HPGM8GL38d74QROnB/telemetry --header "Content-Type:application/json"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 52.205.100.186...
* Connected to www.colbits.com.co (52.205.100.186) port 8080 (#0)
> POST /api/v1/Cl2HPGM8GL38d74QROnB/telemetry HTTP/1.1
> Host: www.colbits.com.co:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 21
> 
* upload completely sent off: 21 out of 21 bytes
< HTTP/1.1 503 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 30 May 2018 22:01:30 GMT
< Connection: close
< 
* Closing connection 0
{"timestamp":1527717691407,"status":503,"error":"Service Unavailable","exception":"org.springframework.web.context.request.async.AsyncRequestTimeoutException","message":"No message available","path":"/api/v1/Cl2HPGM8GL38d74QROnB/telemetry"}
```

In the log I found this error:

2018-05-30 21:57:47,508 [http-nio-0.0.0.0-8080-exec-5] ERROR o.t.server.controller.BaseController - Error [Unknown name value [RULE] for enum class [org.thingsboard.server.common.data.EntityType]; nested exception is java.lang.IllegalArgumentException: Unknown name value [RULE] for enum class [org.thingsboard.server.common.data.EntityType]]

(full output in attached file)

[tb_error.log](https://github.com/thingsboard/thingsboard/files/2055879/tb_error.log)

What could be causing this? Bad procedure changing from v1.4 to v2.0?

**Comment by vparomskiy** [comment]
It looks like DB schema was not updated correctly during migration.
Did you run upgrade script during migration to the new version?

Here is an instruction how to perform an upgrade
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#ubuntucentos-7

**Comment by gustavovelascoh** [comment]
As I said before, I am using docker and I just stopped the container running v1.4, change docker-compose.yml file for the one using v2.0, set `ADD_SCHEMA_AND_SYSTEM_DATA=true` and started a new container using v2.0. I did not find instructions on how upgrade should be performed when using docker.

**Comment by vparomskiy** [comment]
**ADD_SCHEMA_AND_SYSTEM_DATA** flag used for creating DB schema in new installations, it is not used for the upgrade.

https://thingsboard.io/docs/user-guide/install/docker/

> If you have already installed ThingsBoard using docker and want to upgrade or clean up your installation, please cleanup HSQLDB data directory
> sudo rm -rf /home/docker/hsqldb_volume

As you see, docker images where not designed for production systems, because for upgrading to the latest version you will need to drop your database files and they will be created from scratch during container initialization.

An alternative way is to run an upgrade script from container shell.

> $ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=1.4.0

**Comment by jmartincufre** [comment]
I remember I once did an upgrade from 1.3 to 1.4 with that method. I also use docker and have put cassandra and thingsboard 1.4 to work on Rancher.
