### ISSUE TITLE
[Question] Different behavior when sending list of telemetries inside rule chains

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8184]
**Component**

 * Rule Chains

**Description**

My devices are sending lists of telemetries each 10 minute (one telemetry per minute). Inside rule chains I noticed a different behavior when sending only one telemetry and a lista of telemetries. See images bellow:

Sending only one telemtry a behavior is for each IN I have an OUT:

![msedge_NdYHdOP4dKsasasa](https://user-images.githubusercontent.com/7483656/223708736-30bd1da6-0683-4dee-9e83-07ce7cde9b68.png)

Sending a list of telemetries I get first all the INs and after that all the OUTs:

![msedge_Dp6qwjmDMCkkk](https://user-images.githubusercontent.com/7483656/223709658-475635de-c556-422e-99b9-49d6135d4768.png)

![msedge_dR3rZu6o0Wgggg](https://user-images.githubusercontent.com/7483656/223709670-e841d7c3-3ed5-4086-a669-618950dd2991.png)

Bellow is the JSON I'm using to POST my list of telemetries:

```
[
   {
      "ts":"1678189039000",
      "values":{
         "s1":52
      }
   },
   {
      "ts":"1678188979000",
      "values":{
         "s1":53
      }
   },
   {
      "ts":"1678188919000",
      "values":{
         "s1":52
      }
   },
   {
      "ts":"1678188859000",
      "values":{
         "s1":56
      }
   },
   {
      "ts":"1678188798000",
      "values":{
         "s1":49
      }
   },
   {
      "ts":"1678188738000",
      "values":{
         "s1":45
      }
   },
   {
      "ts":"1678188678000",
      "values":{
         "s1":51
      }
   },
   {
      "ts":"1678188618000",
      "values":{
         "s1":56
      }
   },
   {
      "ts":"1678188558000",
      "values":{
         "s1":50
      }
   },
   {
      "ts":"1678188497000",
      "values":{
         "s1":52
      }
   }
]
```

Is there a way to change this behavior and have for each IN one OUT when sending a list of telemetries ?

Why I'm asking that ? Currently I want to detect if a treshold will be true consecutively x times.

i.e. ss_repeatTelemetry server attribute starts with 10 and is decremented every IN, OUt event.

```
var repeatTelemetryActual = msg.ss_repeatTelemetry

if (repeatTelemetryActual > 0) {
    return {msg: {repeatTelemetry: --repeatTelemetryActual}};
}
```
With the list of telemetries behavior the script above is execute only once and not 10 times according the list of telemetries.

**Environment**

Environment
ThingsBoard: ThingsBoard Cloud Prototype
Browser: Microsoft Edge version 104.0.1293.63

**Comment by Civilduino** [comment]
In the picture I see the same timestamp for IN and OUT, it is just the way data is sorted in the Events table.

Send the list as individual telemetries one after the other?

**Comment by lstarke** [comment]
> Send the list as individual telemetries one after the other?

I can do that, but for bandwidth saving reasons I'm sending a list of 10 telemetries. According [ThingsBoard documentation](https://thingsboard.io/docs/reference/http-api/#telemetry-upload-api).

![image](https://user-images.githubusercontent.com/7483656/224012109-c0967beb-73d3-41a9-be76-7dd5adc518cf.png)
