### ISSUE TITLE
Thingsboard bulk delete

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#8189]
Hello, 

Previously I have received this information about bulk device registration through API. 
https://demo.thingsboard.io/swagger-ui/#/auth-controller

Is there any similar provision for bulk delete also? Or even deleting single device item through API? 
Similar to publish telemetry data by 
http(s)://host:port/api/v1/$ACCESS_TOKEN/telemetry

Also, to test the above demo page(swagger) , I think I need to login with the 'Authorization' login window. 
Not sure what should be the ID and Password for this. 

Is it possible to test the APIs? If so how to? 

Best regards,
Debasish

**Comment by debacs83** [comment]
Thank you for your quick reply. I understand about the single deletion. 
Can I test like the following with curl? Have to add '--insecure' option to work 

     curl -X 'DELETE' --insecure 'https://my-aws-EC2_URL.com:8080/api/device/My_Device_ID' -H 'accept: */*'

It is giving the following error:

    {"status":401,"message":"Authentication failed","errorCode":10,"timestamp":"2023-03-09T08:45:00.231+00:00"}

Regarding bulk device registration with their corresponding access token, I am testing with CURL as follows with the swagger UI example and one received from this forum kindly provide by 'ViacheslavKlimov'.

I have put the 'test.csv' file in the same directory.  The 'test.csv' file is also give bellow. 

------  Bulk import of device with csv file ------
// using 'insecure' option as I am using self-certificate'. I could POST telemetry data with the CURL

    curl -X 'POST' --insecure \      
      'https://my_awsEC2_IPaddress.us-west-2.compute.amazonaws.com:8080/api/device/bulk_import' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
      "file": "test.csv",  // csv file containing the information to register devices to TB
      "columns": [
          {
            "type": "NAME"
          },
          {
            "type": "TYPE"
          },
         {
           "type": "ACCESS_TOKEN"
         },
       ],
       "delimiter": "string",
       "header": true,
       "update": true
       }
    }'
--------------- end of file -----------

-- test csv file. File name is 'test.csv' ---

    NAME,TYPE, ACCESS_TOKEN
    aaaa796,datatype,aaaa796

But it is giving the following error:

    '{"status":401,"message":"Authentication failed","errorCode":10,"timestamp":"2023-03-09T08:32:46.121+00:00"}

-- This is the example I have received earlier from [ViacheslavKlimov] -- but not sure what is 'key' ---

    {
     "file": "NAME,TYPE,ACCESS_TOKEN,SERVER_ATTRIBUTE\ndevice1,default,12341325,attr1Value\n", // actual csv payload
     "mapping": {
        "columns": [
         {
            "type": "NAME"
         },
         {
            "type": "TYPE"
         },
         {
            "type": "ACCESS_TOKEN"
          },
         {
            "type": "SERVER_ATTRIBUTE",
            "key": "attr1"
          }
       ],
       "delimiter": ",",
       "header": true, // whether the first row contains columns names
       "update": true 
       }
    }
---------------

**Comment by devaskim** [comment]
1. Each REST request should include _X-Authorization_ HTTP header with value `Bearer YOUR_JWT_TOKEN`
2. If you send any data in request body, add another HTTP header `Content-Type: application/json`

**Comment by debacs83** [comment]
1. Do I need JWT token (tenant) for Deleting and Registering devices to TB? But so far I did not need it for publishing telemetry data to an existing device. Device 'Access Token' is sufficient. 
 
 I was using the example here for deleting:
    https://demo.thingsboard.io/swagger-ui/#/device-controller/deleteDeviceUsingDELETE

    curl -X 'DELETE' \
    'https://demo.thingsboard.io:443/api/device/784f394c-42b6-435a-983c-b7beff2784f9' \
    -H 'accept: */*'

where, '784f394c-42b6-435a-983c-b7beff2784f9' is the device ID (example in this page). 

So I thought Device ID would do. But in that case one has to get the device ID that TB generate for each registered devices. 
Which the user does not know unless it is acquired from TB prior to the execution of the command. 

Am I confusing something?

**Comment by devaskim** [comment]
You need to read more about basics of authentication and authorization strategies via tokens (it is not only TB related info).

The rule is one: every request to server need a token disregarding it makes on behalf of either a user or a device.
1. For users it is JWT token.
2. For devices it is Access token.

When you pushes device telemetry, you do this on behalf of device (2). When you create/delete device, you do this on behalf of a user (1).

**Comment by debacs83** [comment]
Thank you.  It's true. My knowledge in authentication is inadequate. 
Besides, I didn't find any relevant information about using jwt token for registering or deleting devices. 
Now I understood how in both the occasion authentication error occurs. 
For registering device with csv file where exactly should I add my jwt token? 

I have used as follows:

curl -v -X "Autherization: Bearer <my jwt token>" POST --insecure --data '{"file": "test.csv","mapping": {"columns": [{"type": "NAME"},{"type": "TYPE"},{"type": "ACCESS_TOKEN"},],"delimiter": "string","header": true,"update": true}}' https://ec2-54-214-8-53.us-west-2.compute.amazonaws.com:8080/api/device/bulk_import --header "Content-Type:application/json"

The authentication failure error is gone. It is now ended with this msg:

    * We are completely uploaded and fine
    * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
   * Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
    < HTTP/2 400
    < date: Thu, 09 Mar 2023 11:07:30 GMT
    <
    * Connection #1 to host ec2-xx-xx-xx.us-west-2.compute.amazonaws.com left intact

And it is not creating the device. Seems partially working. But there are 'could not resolve host: POST' etc. in the msg. Will look further. If you notice anything wrongly written, please put a note. 
Sorry for the troubles.

**Comment by debacs83** [comment]
Sorry, while copy-pasting the line I missed to include the JWT Token. I DID copy it from where you have shown in the above screen-shot and included that in the cURL command line.  

I could register device on Thingsboard and could delete device also using API Swagger (ViacheslavKlimov has kindly shown be how to use it). As I login as Tenant, it is automatically authenticating with tenant's jwt token. So I don't need to use it explicitly. 

Ultimately I have to use from code (Python probably). So I will use the following page as reference. 
    https://thingsboard.io/docs/reference/python-rest-client/

Thank you very much to bear with me.

**Comment by debacs83** [comment]
Hi @devaskim 

Coming back to confirm a couple of things. First of all, could register multiple devices from AWS Lambda python using JWT Token etc.  Thanks to you and ViacheslavKlimov.

For deleting devices (one by one), other than JWT Token, I also need the 'device ID' (ex. 784f394c-42b6-435a-983c-b7beff2784f9). So every time I want to delete a device, I have to get this device ID.  And to get the device's device ID, 
I have to get it by 'GET API' by it's name (as I can only have device name to search) and then use the device ID to delete it. 

Is my understanding correct? Or there are better or simpler way?

**Comment by epalchenko** [comment]
Hello @debacs83,
> Is my understanding correct? Or there are better or simpler way?

Yes, you are right.
I closed this ticket. If you have any further questions, feel free to open a new ticket with a full description of your request.
