### ISSUE TITLE
A problem with ruls_chains  on thingsboard-2.0

### ISSUE THREAD

**Issue by sampsonsxz** [thingsboard/thingsboard#819]
I log in  thingsboard with the sysadmin account ,when I try to add a new tenant, a alert shown up,which is
"/usr/share/thingsboard/json/tenant/rule_chains",as what i can see ,no tenant added.
but,I refresh it,i see the tenant i just  added.
Any ideas with this problem？

![image](https://user-images.githubusercontent.com/35054212/40755593-939e7936-64b1-11e8-8c8b-c825d047db8f.png)

**Comment by vparomskiy** [comment]
Is it a fresh install of the Thingsboard 2.0 or an upgrade from 1.4?

If it is an upgrade, you should execute run upgrade script before starting Thingsboard. Here is instruction how to do this
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#ubuntucentos-7

**Comment by sampsonsxz** [comment]
it's a fresh install of the Thingsboard 2.0.

**Comment by sampsonsxz** [comment]
So, how can i fix this problem ??

**Comment by sampsonsxz** [comment]
I change the folder "install.data_dir" to "install.data_dir=/usr/share/thingsboard/data" 
The problem has been resolved , Thks guys!!
