### ISSUE TITLE
[Question] Alarms startTs, endTs, clearTs and createdTime not computed on the timeseries timestamp

### ISSUE THREAD

**Issue by acanidio** [thingsboard/thingsboard#8191]
**Component**

 * Rule Engine

**Description**
I have a device sending a timeseries "ooc" with its timestamp to the telemetry HTTP endpoint. Message is:

`{ "ts": <ts>, "values": { "ooc": <value> }`

The device buffers timeseries data and sends them in chunks of transmission every hour.

Both in the Rule Chain Engine and in the Device Profile -> Alarm Rules I have created a simple alarm created
when ooc >= 0.5 and cleared when ooc < 0.5.

What I noted is that while the startTs field is correctly retrieved using the timeseries timestamp, the other
fields are updated based on when the processing occurs. I could've expected this behavior from
createdTime but based on your documentation of the alarm which states "Alarm may be active or cleared. 
When ThingsBoard creates an alarm it persists the start and end time of the alarm. By default, the start time
and the end time are the same. If the alarm trigger condition repeats, the platform updates the end time.
ThingsBoard can automatically clear the alarm when an event occurs that matches an alarm clearing condition"
I would've expect that the other three fields would've work using the timeseries timestamp.

Here it is an example:

- 09/03/2023 12:15:00 -> ooc: 0.49
- 09/03/2023 12:15:10 -> ooc: 0.5
- 09/03/2023 12:15:20 -> ooc: 0.5
- 09/03/2023 12:15:30 -> ooc: 0.49

The alarm generated in my opinion must have the following fields:

- startTs: 09/03/2023 12:15:10
- endTs: 09/03/2023 12:15:20
- clearTs: 09/03/2023 12:15:30

Am I missing something? Hope to hear from you soon.

**Environment**

 * OS:  Ubuntu 18.04.3 LTS + Docker 19.03.5
 * ThingsBoard: v.3.4.4PE

**Comment by myroslav-tb** [comment]
Hi @acanidio, please check the alarm timing details in our documentation: https://thingsboard.io/docs/user-guide/alarms/#alarm-timing-details
