### ISSUE TITLE
[Question] Is there a way to test ui-ngx changes without complete compile?

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard#8193]
**Component**
 * Generic

**Description**
I'm making some UI changes and would like to test them without compiling everything. I would like to know if there is a way to run the code to quickly check if the changes are correct.

**Environment**

 * ThingsBoard: latest

**Comment by devaskim** [comment]
If you are about TB UI, not widgets, user [hot redeploy mode](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#running-ui-container-in-hot-redeploy-mode)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
