### ISSUE TITLE
[Question] MQTT Data not being received like expected

### ISSUE THREAD

**Issue by Hmr-ramzi** [thingsboard/thingsboard#8195]
**Component**

 * Generic

**Description**
Hello,
 
We are currently facing an issue with one of the created tenant devices on our environment. We are using thingsboard 3.3.2
 
We created a device in one of tenants and we send data directly to that device using mqtt protocol.
 
We are facing an unexpected behavior with the data transmission.
 
We have 2 scenarios:
Sending data points with unique keys (meaning that each data point has it’s own key which never gets repeated). On such scenario we are able to send data with high throughput (around 1.5K messages per second).
Sending data points with the same key but different value each message. On such scenario we are able to send data with high throughput like scenario 1 but looking at the database, we only receive very few data points (less than 5%) of the data.
 
Our question is why this behavior is happening and how to fix it.
 
PS: We are using the tb-mqtt python package to send the data which is introduced by thingsboard. We also tried to use different mqtt clients which lead to same result.
 
LG,
Hisham Ismail

**Environment**
 * ThingsBoard: 3.3.2 PE

**Comment by devaskim** [comment]
If timestamp (in millis) might be the same for the same key scenario, value would be overwritten.

**Comment by Hmr-ramzi** [comment]
Hi @ashvayka,

Thank you for your reply. 

It is not at the millisecond no. We send data using the tb-mqtt python package in a loop( meaning we send the data, waiting until we receive acknowledgment with success and then we start sending again) similar to the first scenario also different ts

**Comment by Hmr-ramzi** [comment]
Hello @devaskim ,

Actually you are right. I was sending data with the same TS. Sorry for wasting your time with my issue.

Closing the ticket
