### ISSUE TITLE
Python REST Client : ValueError

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#8197]
**Component**

 *  REST Client

**Description**
Testing Thingsboard provided Python REST Client to create device, asset etc. following the link below:
    https://thingsboard.io/docs/reference/python-rest-client/

Using https with self-generated certificate. So had problem initially to connect. After that could connect and creates
     1. asset with its type. 
     2. get its id. 
     3. get tenant id  etc. 
 
But it is giving error while trying to create device.  

Corresponding lines in my code:
        # creating a Device  
        device = Device(name="Thermometer 1", type="thermometer")         # <- line 57 in my code(corresponding line in the error msg)
        device = rest_client.save_device(device)

The following error msg:

    Traceback (most recent call last):
     File "testTB_01.py", line 57, in <module>
    device = Device(name="Thermometer 1", type="thermometer")
    File "/home/kenkyu/.local/lib/python3.8/site-packages/tb_rest_client/models/models_pe/device.py", line 97, in __init__
    self.device_profile_id = device_profile_id
    File "/home/kenkyu/.local/lib/python3.8/site-packages/tb_rest_client/models/models_pe/device.py", line 329, in    
    device_profile_id
    raise ValueError("Invalid value for `device_profile_id`, must not be `None`")  # noqa: E501
     ValueError: Invalid value for `device_profile_id`, must not be `None`

Where am I possibly going wrong? Just using the example as it is. Also, it is creating assets etc. as expected. 
If any other details are needed please let me know.

Regards

**Environment**

 * OS:  Linux 20.04 (installed AWS EC2 instance)
 * ThingsBoard: 3.4.1
 * Browser: Chrome

**Comment by clecuona** [comment]
The issue persists with the "get_asset_by_id_using_get" function in the asset controller of tb-rest-client version 3.5. This function worked without problems in the previous version.

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create new ticket in GitHub thingsboard python rest client issues (https://github.com/thingsboard/thingsboard-python-rest-client/issues) with detailed steps to reproduce if this problem still exists.
