### ISSUE TITLE
Cannot select  UI widget, when creating a new dashboard

### ISSUE THREAD

**Issue by nikil511** [thingsboard/thingsboard#82]
When given the option to select a UI widget, I need to do multiple double fast clicks, for a widget to be selected and a configuration to pop up. 
On slow computers its impossible to select a widget. 
Maybe you have multiple onclick listeners "stealing" the click action ?

**Comment by type0lang** [comment]
I have a similar issue; dont know if it's related.

Basically I have to restart thingsboard in order to select a new widget (when creating a new dashboard) and configure it. If I want to select another one the UI doesn't respond to the click (no log information to the browser console)

**Comment by ashvayka** [comment]
@nikil511 Are you talking about use case when I want to add new widget to dashboard?

**Comment by ashvayka** [comment]
@nikil511 @type0lang are you able to reproduce this on 1.2.1? have you cleared browser cache?

**Comment by type0lang** [comment]
@ashvayka I tried on version 1.2;

You are doing a great work! I would be great to have some visibility on milestones and versioning too.

**Comment by ashvayka** [comment]
@type0lang I wish we will have time to write them down one day. To much work at the moment, sorry!

**Comment by nikil511** [comment]
Problem persists in Chrome! (TB 1.2.2)
Tried without extensions, icognito, guest etc..  Its almost impossible to select UI widget
Works fine in Firefox

**Comment by ashvayka** [comment]
The master branch should contain the fix now. Also there is a bonus: public dashboards :-)

**Comment by nikil511** [comment]
👍 1.2.3 Snapshot solves the chrome problem! 
(and public dashboards is a very useful feature for demos)

**Comment by ashvayka** [comment]
We are now going to add social icons to the public dashboard window (to allow instant share when you make dashboard public). You can also post your dashboard here. We will be happy to share it with community.
