### ISSUE TITLE
how to send exactly same data to 3rd server?(REST API PLUGIN BodyTemplate)

### ISSUE THREAD

**Issue by lomal788** [thingsboard/thingsboard#820]
how to send data that device send to thingsboard to 3rd server?

if device send {temp:32,humidity:20} to thingsboard then using api plugin to send exactly same data to 3rd server.
I saw put bodytemplate like $temp.AsValueString then it will send only temp data.

I wanna do is whatever device send text send to 3rd server exactly same what device sended
with device id or something like that.

I wanna send whole device info could send in api plugin, data

$deviceId is work but getting data is problem.

**Comment by vparomskiy** [comment]
You can use new Rule Engine from Thingsboard 2.0 for implementing this case.
There is **REST API Call** node that was designed for this case. 

https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node

**Comment by lomal788** [comment]
@vparomskiy that link doesn't help me.. I'm asking there's code liks $deviceType, $deviceId.
If I type $cs then all Client attribute is shown but there's no commend like that in data part.
only I should put a Key name then value is shown.
What I wanna do is ex) $data then all telemetry that device sended.

**Comment by vparomskiy** [comment]
> Request body - Node will send **full Message payload** to the configured REST endpoint. If required, Rule Chain can be configured to use chain of Transformation Nodes for sending correct Payload.

So when your device submit telemetry into the Thignsboard, message payload will look like
` {temp:32,humidity:20}`

The exactly same payload will be used as a body for REST request
