### ISSUE TITLE
[Bug] Cannot save config file 'FileBasedConfig[/home/thingsboard/.config/jgit/config]

### ISSUE THREAD

**Issue by ArnaudPalgen** [thingsboard/thingsboard#8202]
**Describe the bug**

When I create a new version of an entity, or when I use 'auto-commit' no commit is created in my repository.
The connection to the repository works.

**Your Server Environment**

* own setup
  * docker deployment on raspberry pi 4
  * ThingsBoard Version: 3.4.1
  * OS Name and Version: Debian GNU/Linux 11 (bullseye)

**Your Client Environment**

**Desktop :**

* OS: macOS 13.1
* Browser: chrome 
* Version: 110.0.5481.177

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
Follow this documentation: https://thingsboard.io/docs/user-guide/version-control/#usage

**Expected behavior**
The entity is not committed to my repository. The connection to the repo works and no error message appears.

**Additional context**
Logs:
```
[JGit-FileStoreAttributeWriter-2] ERROR org.eclipse.jgit.util.FS - Cannot save config file 'FileBasedConfig[/home/thingsboard/.config/jgit/config]'
java.io.IOException: Creating directories for /home/thingsboard/.config/jgit failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:412)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:219)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:744)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$4(FS.java:430)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ArnaudPalgen** [comment]
I updated to 3.4.4 and the problem still persist

**Comment by devaskim** [comment]
Just for test, try to manually create `.config/jgit` directories

**Comment by ArnaudPalgen** [comment]
The directory was created in the container with the root user (because the user `thingsboard` has not the permission) and owner and group changed to `thingsboard`
After that, no more error messages.

BUT when I export manually an entity, nothing is committed to my repo.

- I use the "Check access" button on the git config. This return "Repository access successfully verified!"
- I try to commit one entity manually to the default branch `main`
- --> everything seems to work
- BUT nothing is committed to my repo
- SOLUTION: Create an unprotected branch

### Repo information:
- Private Gitlab instance
- On the same local network that Thingsboard
- I use a project access token for the Gitlab connection with all permission scopes


We should be notified when Thingsboard can't commit to a branch

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
