### ISSUE TITLE
Custom Action to switch which dashboard to update to

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#8207]
I have an Entity Hierarchy widget with assets and devices that these assest include. This widget is in the main state of the dashboard. I have two other states for now. When I click on the devices inside the widget dashboard updates to other states. For now I can only update to one of the two other states. I want to be able to change which state to update to based on a device's label or attribute. Any help would be appreciated.

**Comment by inanlia** [comment]
I figured it out. 
I did it like this.

````
const label = entityLabel;

if(label == <label>){
    widgetContext.stateController.updateState(<stateId1>,{"entityName":entityName,"entityLabel":entityLabel,"entityId":entityId});
}else{
    widgetContext.stateController.updateState(<stateId2>,{"entityName":entityName,"entityLabel":entityLabel,"entityId":entityId});
}
```
`

**Comment by huerovo** [comment]
Hello,

is there a similar way for navigate to an other dashboard?
