### ISSUE TITLE
[Question] create alarm / action based on a prolonged state

### ISSUE THREAD

**Issue by sebsoft** [thingsboard/thingsboard#8208]
**Component**

 * Generic

**Description**

I have a use case where an asset changes state based on an input of a device.  Consider the example where the asset is an office which has several doors and the sensor sends a message when a door opens and closes.  I would like to raise an alarm or other event when the door stays  in the open state for e.g. more than 5 minutes.

As the rule chain is message driven i could not think of a way to achieve this with a rule chain.

Hints an ideas would be appreciated 

Sebastiaan

**Comment by ezeroldan24** [comment]
Good morning, you can do it with the device profile.

**Comment by sebsoft** [comment]
Thank you for the hint.  What actually did the trick was to use the generator node and use a group as originator (e.g. doors)    in the flow this message is then picked up by the duplicate to specific group node which sends the message to all doors.  With a script node you can then check the state of each door.
