### ISSUE TITLE
After creating new virtual device telemetry data is empty 

### ISSUE THREAD

**Issue by nani44** [thingsboard/thingsboard#821]
I'm creating device 1 and device 2 .both devices are using same device id, after clicking device 1 i'm getting telemetry data. if a click device 2 telemetry data is empty. whenever i delete device 1 at that time i'm getting telemetry data in device 2.

how to overcome this problem , i need both devices telemetry data.

Thank you.

**Comment by vparomskiy** [comment]
The device ID is a UUID and they should be unique, so you should not have many devices with the same ID.

If you want to copy incoming telemetry data to other devices/assets you can use new Rule Engine in the Thingsboard 2.0. You will need to use **Change originator** and change it to the second device. In this case, incoming telemetry will be populated into 2 devices
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator

**Comment by nani44** [comment]
Thank you for your response. But my requirement is like that only, so i'm allowing to create duplicate devices with same device ID . i need to override particular methods  but i can't find out that method. tell me that method  i will implement my own method .

**Comment by vparomskiy** [comment]
BaseTimeseriesService.save()
EntityId is a device identifier

**Comment by nani44** [comment]
saving time not an issue. already saved 2 devices with same device id. retrieving time only the issue, data is not come ui.

**Comment by vparomskiy** [comment]
I don't understand how you want it to make work, because ALL thingsboard services (backend\frontend) were designed to work with unique device identifiers. If you add some changes that enable saving devices with the same identifier, then only you can resolve any issues that were added with this change.

**Comment by nani44** [comment]
actually in server side i modified new device having old device id its saved in database. whenever i click first device telemetry data is reached to front-end. after that i select second device at that time telemetry data getting empty {} . so i delete device 1 after that i click device 2 now telemetry data is reached front end.

i want whenever i click any device either device 1 or device 2 telemetry data is required.
