### ISSUE TITLE
[Question] TTL not visible after a while

### ISSUE THREAD

**Issue by changmk521** [thingsboard/thingsboard#8211]
**Component**

 * Installation

**Description**
Thingsboard TTL disappears after around 1 week. And it only shows the latest TTL while the page is opened.
![image](https://user-images.githubusercontent.com/91674354/224877776-e352dd2b-b8b9-4560-a7dd-1abfd2433138.png)

TTL will only reappear when thingsboard node pod is restarted.
![image](https://user-images.githubusercontent.com/91674354/224877742-f78bb4f1-f62c-4d1e-9512-47f2bbef071f.png)

Not sure whether something is wrong with the setup or missed some configurations.

**Environment**

 * OS:  K8s setup referencing -> https://github.com/thingsboard/thingsboard-ce-k8s
 * ThingsBoard: CE 3.4.1

**Comment by ban2derlog** [comment]
Hi,

Please, describe more detailed:
By TTL you mean TimeSeries records (telemetry)? Or only Queue statistic?
Do you check logs for ThingsBoard pod and for PostgreSQL pod? If there errors or warn messages?
Had you try to tune `SPRING_DATASOURCE_MAXIMUM_POOL_SIZE` and rise total amount of connection threads to PostgreSQL?
