### ISSUE TITLE
The number of telemetry data received by the tb is inconsistent with that stored in the database

### ISSUE THREAD

**Issue by zlwjzf** [thingsboard/thingsboard#8215]
* OS:  CentOS 7
 * ThingsBoard: 3.4.3

![tb_save](https://user-images.githubusercontent.com/115340697/224989072-ed59af6a-744b-4756-b022-28c7515eecf5.png)

![pg_save](https://user-images.githubusercontent.com/115340697/224989084-9bd9b470-59eb-4627-b773-c3e3618bf6b0.png)

Hello, see the title for the description of the problem. I found this phenomenon while debugging a problem of tb-gateway. [https://github.com/thingsboard/thingsboard-gateway/issues/1051](url)

**Comment by devaskim** [comment]
Are you sure that each of 610 messages had different timestamps for the same timeseries keys? From gateway issue, you already know that server overwrites key's value with duplicated timestamps.

**Comment by zlwjzf** [comment]
Hi @devaskim 
Yes, I testing one of the devices individually, pushing telemetry data at a rate of 1 second.  From the rule node that holds the telemetry, you can see 610 successful data, but only 577 in the database.

**Comment by ban2derlog** [comment]
Hi,
As I translate - you check Debug Events, so you enable Debug mode on node.
Do you check these events for `Failure`s with error?

**Comment by zlwjzf** [comment]
Hi, @ban2derlog 
Yes, I have checked, all events are Success, no Failure.

**Comment by myroslav-tb** [comment]
Hi @zlwjzf, we were unable to reproduce the issue on our side. If the issue still persists, please open a new ticket for us with detailed step-by-step instructions on how to reproduce it.

Best regards,
Myroslav
