### ISSUE TITLE
Customize Entities Hierarchy

### ISSUE THREAD

**Issue by stanleykao00** [thingsboard/thingsboard#8219]
**Component**

 * UI

**Description**
Hi there, 

I would like to create an entities hierarchy, I add all relation to the devices, such as building name and floor. i wanna to the config the hierarchy as follow:
Top Level (1st Level): Building Name
2nd Level: Floor
3rd Level: customize Label display in the hierarchy

I tried to modify the setting in the entities hierarchy. but i can't config it as above setting. it always show the "Device Name" in the hierarchy.

does anyone can teach me how to do it? 

**Environment**
 * ThingsBoard: v3.3.4.1 CE

**Comment by NistantriTech-Dhaval** [comment]
@stanleykao00 
did you tried this setting in widget advance?
![image](https://user-images.githubusercontent.com/127075794/226086076-9a0543fa-7165-4925-93dd-b378aeca6526.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
