### ISSUE TITLE
allow to set this value from Server Attribute

### ISSUE THREAD

**Issue by codeHui** [thingsboard/thingsboard#8225]
![image](https://user-images.githubusercontent.com/17940498/225569976-54a91f6d-b418-4512-a77a-6db649d3af72.png)
do you have a plan for allowing us to set this value from Server Attribute?
because each of our device has a different height,

**Comment by ssakharova** [comment]
Hello @codeHui,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement it in future versions of the ThingsBoard.
There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
