### ISSUE TITLE
[Question] thingsboard cloud url  is not accessible.

### ISSUE THREAD

**Issue by yunamoon** [thingsboard/thingsboard#8226]
**Component**
 * Generic

**Description**

I built a service through thingsboard cloud. 
However, the url and the additional domain are not accessible. 
The error occurred about an hour ago.

**Environment**
 * Browser: chrome

**Comment by Civilduino** [comment]
I have the same problem, any news on this?

**Comment by ashaforost** [comment]
Hi @yunamoon @Civilduino 

Yesterday thingsboard.cloud had planned maintenance. Users were notified about this in an email 4 days ago.
