### ISSUE TITLE
[Question] Updating Telemetry data after Alarm is created for Inactivity Event

### ISSUE THREAD

**Issue by EyeTeeGuy** [thingsboard/thingsboard#8227]
* Rule Engine

**Description**
Hello, I currently have a simple implementation where I send MQTT Telemetry data to Thingsboard and am using the rule engine where an alarm will be created once the device is inactive. (Followed guide on Thingsboard website) (Tutorial of Inactivity Event)

Is there a way to modify the rule chain to update the telemetry data after the alarm has been created? I'm a bit confused on which nodes should be connected to the "Create Inactivity alarm" node.

**Environment**

 * OS:  Windows/Raspberry Pi
 * ThingsBoard: Demo server
 * Browser: Chrome

**Comment by NistantriTech-Dhaval** [comment]
@EyeTeeGuy 
you can use the script rule node from transformation group to add telemetery data you like
then use save timeseries rule node to save in database

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
