### ISSUE TITLE
[Question] Migration plan from ThingsBoard Cloud to PE

### ISSUE THREAD

**Issue by star7128** [thingsboard/thingsboard#8229]
**Description**
For upcoming pilots, we would like to deploy some projects to ThingsBoard Cloud first when devices less than 1000 devices. 

Once we get the first stage business success, we will have our devops team involved. So we will need to migrate up running pilots from ThingsBoard cloud to ThingsBoard PE seamlessly in order to keep running existing services and scale up on demand.

We would like to get some guidelines to ensure these requirements above can be met and solid. Thanks!

**Comment by JuliusHarald** [comment]
> But in 3.5 version, which will be released soon, there will be new feature Migrator - that allow to migrate ThingsBoard from one instance to another. And it will be on ThingsBoard.cloud too.

Is this still planed to release or what is the state of this Migrator?
