### ISSUE TITLE
ThingsBoard 2.0 Rule Engine - Support to combine telemetry messages from multiple device and aggregate it and publish to a another device / asset

### ISSUE THREAD

**Issue by nitinware** [thingsboard/thingsboard#823]
Hi Team,
I saw that Thingsboard 2.0 is release with new rule engine. I am still exploring that rule engine.
I want to combine telemetry messages from multiple devices and aggregate them and sent to another device / asset.
I remember earlier Thingsboard v1.4 did not support that and we had to write the spark jobs to aggregate messages from multiple device and aggregate result back to a Thingsboard asset.
If the new rule engine support this feature then can you please help with a example for the same.
Your help is highly appreciated.
Thanks,
Nitin Ware

**Comment by untilbit** [comment]
Is it possible to aggregate data like in TB Kafka Spark integration sample?

**Comment by vparomskiy** [comment]
The idea is to duplicate messages from devices, change originator to required asset and save telemetry again.
Here is how the chain will look like:
![duplicate telemetry](https://user-images.githubusercontent.com/4686483/40830096-1704449a-658e-11e8-9b94-eb2adb48dc63.png)

1. After original telemetry saved we rout the same message to the script filter node. In this node we decide, should this telemetry be copied into some asset?
2. If yes, them rout message to the Change originator node. In node configuration select **Originator source** - **Related** and define relation query that will be used to find required Asset.
3. After originator changed rout message to the Save telemetry node.

With this chain, telemetry requests from specific devices will be copied into related Asset. For example, if you have 1 Asset (Building) and many devices that measure energy consumption. Each device has relation to the Building asset. When device upload measurements, they are copied into related Asset.

You can create chart time series widget for the Building (Asset) and select aggregation type **sum**. As the result, you will see total energy consumption for the building.

**Comment by nitinware** [comment]
@vparomskiy - Thanks for the example, your input is highly appreciated.
However if I want to perform action based on data of 2 different devices which may not have same input data. For example if I want to publish telemetry to a Asset if the temperature of Device A and humidity of Device B is in certain range. So does TB Rule engine gives a provision to write rule which comprises input messages from multiple devices with different data structure.

**Comment by nabil-rejeb** [comment]
@nitinware - You can save temperature of "DEVICE A" as an attribute of "DEVICE B" and humidity of "DEVICE B" as an attribute of "DEVICE A" , thus : 
"DEVICE A" and "DEVICE B" will have all informations which can be used in script to send telemetry to the asset as @vparomskiy explained.

**Comment by vparomskiy** [comment]
Or you can use enrichment **Device attributes** node with relation query to fetch related device attribute (temperature or humidity)

**Comment by nitinware** [comment]
@nabil-rejeb @vparomskiy  - This alternative option suggested by you will help me in my case. Thanks for your inputs, appreciate it.

**Comment by azrin1972** [comment]
> The idea is to duplicate messages from devices, change originator to required asset and save telemetry again.
> Here is how the chain will look like:
> ![duplicate telemetry](https://user-images.githubusercontent.com/4686483/40830096-1704449a-658e-11e8-9b94-eb2adb48dc63.png)
> 
> 1. After original telemetry saved we rout the same message to the script filter node. In this node we decide, should this telemetry be copied into some asset?
> 2. If yes, them rout message to the Change originator node. In node configuration select **Originator source** - **Related** and define relation query that will be used to find required Asset.
> 3. After originator changed rout message to the Save telemetry node.
> 
> With this chain, telemetry requests from specific devices will be copied into related Asset. For example, if you have 1 Asset (Building) and many devices that measure energy consumption. Each device has relation to the Building asset. When device upload measurements, they are copied into related Asset.
> 
> You can create chart time series widget for the Building (Asset) and select aggregation type **sum**. As the result, you will see total energy consumption for the building.

Instead of using chart, how if I want to use the digital guage instead since it has no aggregation type option?

**Comment by vparomskiy** [comment]
You can use Analytics Nodes, they can aggregate data streams.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/pe/analytics-nodes/

Here are guides for this case:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/
and
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/

**Note:** Those nodes are available on ThingsBoard PE (you can test them on https://cloud.thingsboard.io/home )
