### ISSUE TITLE
the TB does not reply with SubACK when username is "provision" and subscribe provisioning topic 

### ISSUE THREAD

**Issue by chsdzczp** [thingsboard/thingsboard#8231]
I have been interfacing a EC800G 4G Cat.1 modem with thingsboard and I meet a problem. while trying to subscribe for provisioning topic "/provision/response", thingsboard does not acknowledge the packets. I did a simulation using a python script that copied from your website, it connects and is able to subscribe and receive response messages from the server. When I try it by the 4G module, i find that the module can't subscribe the topic, because the server didn't acknowledge the packets. It seems like that the module and the python packges have different mechanisms. See attached image with packets from the wireshark capture .
![image](https://user-images.githubusercontent.com/37919180/225851020-3d0e199f-3cbd-4fd0-b4b0-f1f2bdb831bc.png)
I tested it with python again, and I found that the server didn't acknowledge the packets, too. Then I changed the username from 'provision' to a device ACCESS_TOKEN and test it again,  then the server can acknowledge the packets
![image](https://user-images.githubusercontent.com/37919180/225853253-da7d9b53-7d38-43f8-8dd2-862019d0e5e6.png)

**Comment by gulis1** [comment]
Any updates on this? I'm having the same issue in version 3.6.1

**Comment by Ultrazombie** [comment]
Hello,
Username provision is mandatory. by design.

**Comment by bakadave** [comment]
Same problem here. SUBACK is never received, provision response is however received properly.
