### ISSUE TITLE
[Question] TBEL can handle only 32 bit integers?

### ISSUE THREAD

**Issue by netbc** [thingsboard/thingsboard#8240]
**Component**

 * Rule Engine
 * Generic

**Description**
TBEL cannot process integers larger than 32 bits e.g. timestamps
![image](https://user-images.githubusercontent.com/110825868/226295982-43734788-d732-4026-89c0-3f2a8d1c8d7e.png)

**Environment**
 * ThingsBoard: version 3.4.4PE

**Comment by devaskim** [comment]
See https://github.com/thingsboard/thingsboard/issues/8015
