### ISSUE TITLE
[Bug] Thingsboard PE Swagger Asset Entity Group Empty Asset Profile

### ISSUE THREAD

**Issue by Zac1209** [thingsboard/thingsboard#8248]
**Describe the bug**
When using Swagger endpoint to get each entities of an asset entity group(/api/entityGroup/{id}/entities?pageSize=50&page=0) and having asset profit set in Thingsboard group setting I get the property "asset_profile", but it is empty. On web dashboard, the asset profile has a value. See screenshots bellow.

**Your Server Environment**
* own setup
  * local docker deployment
  * ThingsBoard Version v.3.4.3PE
  * Ubuntu 21.10

**To Reproduce**
1. Create asset group named 'SPS'
2. Create Asset profile named 'TurbineSite'
3. Create asset in asset group 'SPS' named 'Turbine01' and assign asset profile 'TurbineSite'
4. Create REST Swagger request with URL 'http://{ip}:{port}/api/entityGroup/{assetGroupId}/entities?pageSize=50&page=0'
5. Observe 'asset_profile' field to be empty

**Expected behavior**
'Asset_profile' should show 'TurbineSite'

**Screenshots**
![image](https://user-images.githubusercontent.com/13938446/226753657-b71ab588-2933-44e1-a28b-af0a50ff2c84.png)
![image](https://user-images.githubusercontent.com/13938446/226753788-558c7f80-c8c3-4fea-b664-6398139dd030.png)

**Comment by devaskim** [comment]
Did you check in browser DevTools that request is the same?

**Comment by Zac1209** [comment]
Fixed v3.5.0
