### ISSUE TITLE
[Question] Maintenance POP-UP notification on open dashboard

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8252]
**Component**

 * UI

**Description**
Notification state pop-up if server attribute is True.
The idea for this is to signal that the monitored equipment is under maintenance.

![image](https://user-images.githubusercontent.com/7483656/227195090-10ce23b9-8de0-4840-b96e-4a3ef5505066.png)

**Environment**

 * OS:  Windows 10
 * ThingsBoard Cloud
 * Browser: MS Edge 111.0.1661.44

**Comment by ban2derlog** [comment]
Hi,
Please, wait for new release of ThingsBoard 3.5.
It will have new Notification Center feature that can help you to create a proper logic for your solutions.
