### ISSUE TITLE
[Bug] Upgrade script doesn't return error when upgrade fails

### ISSUE THREAD

**Issue by poelstra-sioux** [thingsboard/thingsboard#8259]
**Describe the bug**

When running `/usr/share/thingsboard/bin/install/upgrade.sh` and it fails, it always returns exit code 0.

**Your Server Environment**

ThingsBoard PE in docker.

**To Reproduce**

Run `/usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=foo`.

**Expected behavior**

Upgrade script exits with code 1 if upgrade fails.

**Additional context**

https://github.com/thingsboard/thingsboard/blob/master/packaging/java/scripts/install/upgrade.sh#L62 contains `exit $?`, but the exit code is already consumed by the `if` before it. I suggest adding an explicit `exit 1` in the failure branch instead,

It may be wise to use `set -e` at the top of the script, too.

**Comment by trikimiki** [comment]
Hi!

Please feel free to contribute and create your PR for this improvement.
