### ISSUE TITLE
[Question] Connecting to the Thingsboard-Docker database with PGadmin

### ISSUE THREAD

**Issue by jose-franco-PT** [thingsboard/thingsboard#8261]
**Component**

**Description**
Good afternoon,

I have successfully installed Thingsboard Docker version on Windows 10, I did some experiments, namely on its interaction (data exchange) with Thingsboard Edge on Raspberry Pi, and everything went fine, as expected.

I'd like to have access to the Postgres databases of the Thingsboard container running on Docker.

I followed the instructions that are listed on the following site:
[https://thingsboard.io/docs/reference/performance/tools/postgres-pgadmin-monitoring/](url)

However I am being faced with the following message:

![image](https://user-images.githubusercontent.com/83010884/227586192-b8e981a5-c11a-4990-a0cf-781900925435.png)

I even tried forcing port 5432 directly in the docker-compose.yml file, but still without success.

- What could be the main cause of the problem described?

Thanks for your attention

**Environment**

 * OS:  Windows 10 and Docker
 * ThingsBoard: V3.4.4
 * Browser: Firefox and Brave

**Comment by devaskim** [comment]
Maybe firewall on target machine blocks 5432 port?

**Comment by pg-goose** [comment]
I'm having the same problem.
Dockerized pgadmin, thingsboard-postgres container too.

pgadmin server connection conf:

- **Host name/addr** 127.0.0.1 | 172.8.0.3 | thingsboard
> Localhost, the the container IP in the default network and the host name of the container
- **port** 5432
- **Manteinance database** thingsboard
- **username** thingsboard
- **password** postgres

Now the already running Thingsboard container outputs the following enviroment variables:
```
declare -x SPRING_DATASOURCE_PASSWORD="postgres"
declare -x SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/thingsboard"
declare -x SPRING_DATASOURCE_USERNAME="thingsboard"
declare -x SPRING_DRIVER_CLASS_NAME="org.postgresql.Driver"
```
These lines are added to the thingsboard docker compose file:

```yml
  thingsboard:
    image: "thingsboard/tb-postgres"
    container_name: 'thingsboard'
    restart: unless-stopped
    ports:
      - "5432:5432"
      #more ports
```

The db is reachable within the TB container, as it should

I can't see no reason to not be able to connect to the db
