### ISSUE TITLE
[Question] Custom Node Java getUserDevice?

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#8268]
Hi, I try to get device list by user.
In angular TB service, this possible using **deviceService.getUserDevices**, so can get devices available for current user.

But how to do this in Java (custom rule node). Can you guys help me?
![image](https://user-images.githubusercontent.com/12267053/227943331-0a5f806b-45f1-49ce-924d-dc2353d3a6d0.png)
This is function I see in java, I can't find some thing like **getuserDevice**. In here, I Only know how to get device by customer. But how to do something like **deviceService.getUserDevices**?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
