### ISSUE TITLE
Server side attribute not autogenerated using gateway

### ISSUE THREAD

**Issue by marcozanghi** [thingsboard/thingsboard#827]
The following server side attributes are not autogenerated when device is connected throught the gateway. 
Any solution?
![image](https://user-images.githubusercontent.com/1820624/40840306-5d1cd984-65a6-11e8-9f95-90f0793cbd51.png)

**Comment by ashvayka** [comment]
@mp-loki This is an about the new feature. It should work automatically, disregarding gateway connection or direct connection.

**Comment by ashvayka** [comment]
@marcozanghi I have detected the root cause of the issue and it will be fixed in v2.0.1

**Comment by marcozanghi** [comment]
@ashvayka could you give me any details ? I’ll try to contribute for a solution ! Thanks

**Comment by vparomskiy** [comment]
Thingsboard 2.0.2 already released
