### ISSUE TITLE
java heap space when opening dashboards

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#828]
Hi all,

I have 10 dashboards. 8 op them open normal. 2 of them give the error 'java heap space' (see picture)
However, yesterday they all worked fine.

![image](https://user-images.githubusercontent.com/36699523/40841259-232991be-65aa-11e8-9af5-39d02d74b0b3.png)

Anybody knows what I can do about this?

**Comment by vparomskiy** [comment]
Can you share dashboard json, so we can reproduce the issue?

**Comment by jensvdh15** [comment]
This is my json-file. I think the problem is that I'm using an image in these 2 dashboards. How can I solve this?

[air_handling_unit.txt](https://github.com/thingsboard/thingsboard/files/2066259/air_handling_unit.txt)

**Comment by ashvayka** [comment]
Host the image somewhere online and add reference to the image as a link, not as a file.

**Comment by jensvdh15** [comment]
Ok, thanks. I'll try to do that. But how can I delete thes two dashboards? 
It keeps saying 'java heap space' when I'm trying to delete or adjust the dashboards in UI.

**Comment by jensvdh15** [comment]
Anybody who knows how I can delete these dashboards?

**Comment by untilbit** [comment]
![](https://user-images.githubusercontent.com/12769948/40962351-8ce2e77e-68a5-11e8-9008-55e6a32ed6a6.png)

**Comment by jensvdh15** [comment]
Yes I know, but it says 'java heap space' when trying to delete it like this. Isn't there another way?

**Comment by untilbit** [comment]
This python api has a function to delete dashboard:

https://github.com/eykamp/thingsboard_api_tools/blob/master/thingsboard_api_tools/__init__.py

**Comment by jensvdh15** [comment]
Sorry, I'm not really common with this. Can you explain me how I can use this please?

**Comment by jensvdh15** [comment]
Anybody who knows how to solve this? I've tried it in the normal way and I've tried from te rest API. But both don't work. I've increased the java heap space and tried to delete these dashboards again but none of it works. Anybody who knows what to try next?

**Comment by untilbit** [comment]
I don't hanve another solution.
i only would create another installation and then recreate everything if there are not much devices, dashboard...

**Comment by jensvdh15** [comment]
I am using SQL DB. But how can I access the thingsboard embedded database?

**Comment by vparomskiy** [comment]
HSQLDB or Postgres ?

**Comment by jensvdh15** [comment]
HSQLDB

**Comment by kumarsm** [comment]
@jensvdh15 Found helpful instructions here:
https://stackoverflow.com/questions/48792859/how-to-access-thingsboard-internal-database
