### ISSUE TITLE
[Question] MQTT Protobuf Device Payload

### ISSUE THREAD

**Issue by acanidio** [thingsboard/thingsboard#8284]
**Component**

 * Generic

**Description**
In the JSON payload version of the MQTT device API is possible to send structured data specifying a client-side timestamp for the uploaded timeseries. There is no equivalent for Protobuf payload specified in the documentation. Am I missing something or is this a limitation of the system?

In the second case I think it is a great limitation of the system. Is there any Rule Chain custom implementation to achieve this even if it is not supported in a standard way?

As an example my device profile uses the following Protobuf specification for telemetry data:

```protobuf
syntax = "proto3";

package example_device;

message TimeseriesMessage {
    int32 temperature = 1;
    uint32 indoor_humidity = 2;
}
```

**Environment**

 * ThingsBoard: 3.4.1PE

**Comment by devaskim** [comment]
Not sure that understand you problem, but you could try to add timestamp field to `TimeseriesMessage ` and then move it from message body to `metadata.ts` while processing message in Rule Engine
