### ISSUE TITLE
MqttTransportHandler:  Message decoding failed: Illegal BIT 2 or 1 in fixed header of CONNECT message, must be 0, found 3

### ISSUE THREAD

**Issue by imananuar** [thingsboard/thingsboard#8289]
**Component**

 * Installation

**Description**
I just updated my Thingsboard version from 3.4.3 to 3.4.4. I build from source. I run my thingsboard on vm in azure and pointed to my postgres db in azure. I have the same exact configuration with 3.4.3, however when I update to the latest version, this error popped up. I configure my thingsboard.yml with below configuration:

# Local MQTT transport parameters
  mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: "${MQTT_ENABLED:true}"
    bind_address: "${MQTT_BIND_ADDRESS:0.0.0.0}"
    bind_port: "${MQTT_BIND_PORT:1883}"
    # Enable proxy protocol support. Disabled by default. If enabled, supports both v1 and v2.
    # Useful to get the real IP address of the client in the logs and for rate limits.
    proxy_enabled: "${MQTT_PROXY_PROTOCOL_ENABLED:false}"
    timeout: "${MQTT_TIMEOUT:10000}"
    msg_queue_size_per_device_limit: "${MQTT_MSG_QUEUE_SIZE_PER_DEVICE_LIMIT:100}" # messages await in the queue before device connected state. This limit works on low level before TenantProfileLimits mechanism
    netty:
      leak_detector_level: "${NETTY_LEAK_DETECTOR_LVL:DISABLED}"
      boss_group_thread_count: "${NETTY_BOSS_GROUP_THREADS:1}"
      worker_group_thread_count: "${NETTY_WORKER_GROUP_THREADS:12}"
      max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"
      so_keep_alive: "${NETTY_SO_KEEPALIVE:false}"
    # MQTT SSL configuration
    ssl:
      # Enable/disable SSL support
      enabled: "${MQTT_SSL_ENABLED:true}"
      # MQTT SSL bind address
      bind_address: "${MQTT_SSL_BIND_ADDRESS:0.0.0.0}"
      # MQTT SSL bind port
      bind_port: "${MQTT_SSL_BIND_PORT:8883}"
      # SSL protocol: See https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#sslcontext-algorithms
      protocol: "${MQTT_SSL_PROTOCOL:TLSv1.2}"
      # Server SSL credentials
      credentials:
        # Server credentials type (PEM - pem certificate file; KEYSTORE - java keystore)
        type: "${MQTT_SSL_CREDENTIALS_TYPE:PEM}"
        # PEM server credentials
        pem:
          # Path to the server certificate file (holds server certificate or certificate chain, may include server private key)
          cert_file: "${MQTT_SSL_PEM_CERT:/home/user/thingsboard/application/src/main/resources/mycert.pem}"
          # Path to the server certificate private key file. Optional by default. Required if the private key is not present in server certificate file;
          key_file: "${MQTT_SSL_PEM_KEY:/home/user/thingsboard/application/src/main/resources/mycert.pem}"
          # Server certificate private key password (optional)
          key_password: "${MQTT_SSL_PEM_KEY_PASSWORD:server_key_password}"

Another note: I do "mvn clean install -DskipTests" on branch release-3.4. My pem and cert file is exactly the same as in ver 3.4.3. I also make configuration on thingsboard/application/src/main/conf/thingsboard.conf by adding these:

export MQTT_SSL_ENABLED=true
export MQTT_SSL_CREDENTIALS_TYPE=PEM
export MQTT_SSL_PEM_CERT=mycert.pem
export MQTT_SSL_PEM_KEY=mycert.key

Please help me because I have been stuck with this issue for a day :)

**Environment**

 * OS:  Ubuntu 20.04.5 
 * ThingsBoard: 3.4.4

**Comment by Rishi-NF** [comment]
Did u ever fix this?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

Please re-create the fresh ticket if this problem still exists.
