### ISSUE TITLE
Could not create new tenant for ThingsBoard CE 2.0

### ISSUE THREAD

**Issue by AugustineNg** [thingsboard/thingsboard#829]
When logged in as the default sysadmin and tried to add a new tenant by clicking on the ADD button of the Add Tenant dialogue, ThingsBoard display the following message:

'usr/share/thingsboard/json/tenant/rule_chains'

it apparently could not find the tenant rule_chains, which in closer investigation is in the location:

'usr/share/thingsboard/data/json/tenant/rule_chains/root_rule_chain.json'

**Comment by vparomskiy** [comment]
please update to the latest version, this issue already fixed

**Comment by b8rother** [comment]
I have the same issue on Thingsboard CE 2.1
I have to emphasis that I have thingsboard installed on Centos 6 and that I have overcome the issue #398 using the alternative way for running Thingsboard from https://github.com/thingsboard/thingsboard/issues/813#issuecomment-393497951
The log file returns:
java.nio.file.NoSuchFileException: /usr/share/thingsboard/json/tenant/rule_chains

**Comment by vparomskiy** [comment]
It should work on Centos. Please upgrade to the latest version

**Comment by b8rother** [comment]
I've installed the latest version of thingsboard but that didn't resolve the issue.
I had to change the path of the install.data_dir in commands that I used to start the service.
This worked for me:
```
export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard/data"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql
/usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard/data -jar /usr/share/thingsboard/bin/thingsboard.jar > out.txt &
```

**Comment by b8rother** [comment]
I created bash script **start.sh** which includes thingsboard.conf where all variables above are predefined:
```
#!/bin/bash
#

source /usr/share/thingsboard/conf/thingsboard.conf
/usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar /usr/share/thingsboard/bin/thingsboard.jar > out.txt &
```

**Comment by qwyinxiang** [comment]
@vparomskiy Because I made a customization in version 2.1, I can't use version 2.1.3 directly. Can you tell me what is the cause of this problem, and how do you solve it?
