### ISSUE TITLE
[Question] How to get all attribute keys with the Device MQTT interface?

### ISSUE THREAD

**Issue by reinhardbluelab** [thingsboard/thingsboard#8295]
**Component**
* Generic

**Description**
Is it possible to all the attribute key names (client & shared) using just the Device MQTT interface? We need to get them all when an embedded device starts up and ideally we don't want to manually specify all the attribute key names in our code. We can't just use an empty body to request all attributes since the result may be too big for the embedded device to handle in one go. Ideally we want to get the attribute key names, then request the attribute values in batches.

**Environment**
Not applicable

**Comment by devaskim** [comment]
Only HTTP transport lets device requesting [a subset of all attributes](https://thingsboard.io/docs/reference/http-api/#request-attribute-values-from-the-server).
