### ISSUE TITLE
Slow on cloud service

### ISSUE THREAD

**Issue by SycraUmer** [thingsboard/thingsboard#8296]
**Issues**

 * On AWS Cloud the TBCE page loading is versy slow
 * What is the mininum Bandwidth Required for normal TBCE setup?
 * Can we minimize the .js/css files to minimize the loading time?

**Description**
We have installed TBCE on AWS VPS (LightSail). But the loading time is very slow even for login page. As i have tested the size of .js/css file are around 5.5Mb only for login page and it takes around 9 Sec. Home page takes 17 Sec while the .js/css files size is 12.8Mb.

Please: Give some suggestions about this issue. and also let us know how much Bandwidth will be okay for normal setup. 

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.4.1
 * Browser: Google Chrom.
 * VPS: AWS LightSail

**Comment by devaskim** [comment]
Use proxy (e.g. HAProxy) to cache such resources. Try to search among previous Github issues, there is instructions how to do that.
Also TB provides official guide how to setup HAProxy for HTTP support.
