### ISSUE TITLE
[Bug] Widget CSS - Background-color not changeable

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8299]
**Describe the bug**
It is currently not possible to use Widget CSS for changing the background-color of Widget elements like Table headers.
It seems that the styles get overwritten each time by some default settings.

But it works when setting a different text color.

**Your Server Environment**
* own setup
  * cloud AWS
  * ThingsBoard Version 3.4.4 PE

**To Reproduce**
1. Go to Widget Setting & enter Widget CSS styles (background-color)
2. Apply changes
4. See that default background color is used each time

**Expected behavior**
Custom Widget CSS shouldn't be overwritten by any default settings. Otherwise it doesn't make sense to have this feature at all.

**Screenshots**
Working example with text color (red color):

![working](https://user-images.githubusercontent.com/25298332/229081427-433ae210-81f0-44ea-84bf-e104633f6508.PNG)

```
.entities-table-787541229 .mat-table .mat-header-cell {
   color: rgba(200, 000, 0, 0.54);
}

```

Not working with background color:

![not_working](https://user-images.githubusercontent.com/25298332/229081631-25c2c895-4ac4-4227-8e00-8306d26b8967.PNG)

```
.entities-table-787541229 .mat-table .mat-header-cell {
    background-color: rgba(200, 000, 0, 0.54);
}

```

**Comment by devaskim** [comment]
Use CSS `!imprort` and don't use auto generated ID in CSS classes
```
.mat-table .mat-header-cell {
    color: rgba(243, 102, 33, 1) !important;
    background-color: #FCF3EC !important;
}
```

**Comment by mde2017** [comment]
Hey @devaskim,

Thank you very much for the explanation! This works fine.

**Comment by Diyouf** [comment]
why this not working in my angular 16  project 

`.mat-table .mat-header-cell {
    color: rgba(243, 102, 33, 1) !important;
    background-color: #FCF3EC !important;
}`

could anyone please help me!
