### ISSUE TITLE
See what version of server is running

### ISSUE THREAD

**Issue by nikil511** [thingsboard/thingsboard#83]
After deploying a few times from source, we are already confused on which version we are actually running.
Is there a way to know ? maybe have a API call which returns some system info or somewhere in the admin user backend ?

**Comment by ashvayka** [comment]
Hi! The version is always present in pom.xml that you use for the source code build. However, your idea is very valid and I've created [issue](https://thingsboard.atlassian.net/browse/TB-54) for this.

**Comment by ashvayka** [comment]
This is fixed now in v1.2.3. Available in user dashboards on the bottom-right corner of the screen.
