### ISSUE TITLE
ThingsBoard 2.0 problem with relation between customer and device over REST API

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#830]
To reproduce, do the following from the UI:

- Create a device,
- Create a customer
- Assign the device to the customer.
- Delete the relationship again.

Use the REST API to check the status:

- **GET /api/devices** with device ID as parameter:
Delivers the customer ID for "not assigned" as expected:
`"customerId": {
      "entityType": "CUSTOMER",
      "id": "13814000-1dd2-11b2-8080-808080808080"},`

- **GET /api/tenant/devices** with device name as parameter:
Delivers still the "old" customer ID which is not valid any more.
`"customerId": {
    "entityType": "CUSTOMER",
    "id": "163c5750-cb8d-11e7-bd84-694df8d52d7d"
  },`

The UI is fine, no problems visible there.  But my REST API scripts get confused...

I haven't checked V 1.4.0 for that behaviour.

**Comment by ashvayka** [comment]
Hi @BatListener . Please provide API call that you use to "delete relationship again". Are you manipulating with the relations API directly?

**Comment by BatListener** [comment]
No, I was using the TB UI to delete the relation. Within the UI everthing looks fine. The REST API was just used to retrieve the information.
And within the API it was just the **GET /api/tenant/devices** still delivering the former customer ID.
