### ISSUE TITLE
[Bug]  unable to start backend application

### ISSUE THREAD

**Issue by bhargavagonugunta** [thingsboard/thingsboard#8303]
**Describe the bug**
under common package gem package is missing
unable to rum spring boot application 
![Screenshot 2023-04-01 at 7 14 42 PM](https://user-images.githubusercontent.com/118610174/229293176-dad1fca2-92b2-484c-8fa2-443da0023741.jpg)

**Comment by devaskim** [comment]
`gen` means generated class, so you need to [build project](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#verify-build) and update IDE index

**Comment by trikimiki** [comment]
@bhargavagonugunta, is your issue still relevant?
