### ISSUE TITLE
[Bug] SMTP Relay Exchange Server - Authentication unsuccessful

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8309]
**Describe the bug**
We are currently struggling with SMTP configuration on the enviroment of one of our customers.
There is no need to provide any credentials for authentication of the SMTP Relay. Also for internal communication no proxy has to be provided. SMTP Port is 25.
Test Emails were sucessfully send, if tested without ThingsBoard (on the same server)

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.4.2 PE

**Expected behavior**
Test Emails should work without authentication errors, so Email notification can be used for the customer's usecases.

**Screenshots**
Configuration Screenshot (anonymized):
![image](https://user-images.githubusercontent.com/25298332/229717649-18f03a7b-ee91-47c3-be4c-cf78fa0e8b8d.png)

Successful tests with telnet (anonymized):
![test_email_telnet](https://user-images.githubusercontent.com/25298332/231457906-dc15ded5-55a3-4cb6-85f1-5959da4c4133.png)

Error message:
![image](https://user-images.githubusercontent.com/25298332/229717399-761c8b2c-fb39-4fd5-8431-db509dd6e362.png)

**Comment by mde2017** [comment]
Any update on this? Or ideas to fix the issue?

**Comment by AlexDoanTB** [comment]
@mde2017 it is because the SMTP settings require the **username** and **password** to be filled in. If empty, the platform will intend to authenticate with empty strings. No authentication use case is not supported. You can create a feature request. But the noAuth case is naturally insecure, and the request may be rejected.
