### ISSUE TITLE
How can i get device attribute of new created device in rule chain node? 

### ISSUE THREAD

**Issue by yaron-gorillalink** [thingsboard/thingsboard#8313]
* Rule Engine
 

**Description**
Hi,
I'm trying to get a attributes of a new created device in rule chain node. I get "new Entity" messages in to my rule node. i was trying to use the 'enrichment nodes' . both 'Device attributes' and 'Related attributes' , did not work. 

please advice,
Thanks'
Yaron

**Environment**
 * OS:  ubuntu 22.04
 * ThingsBoard: 3.2.2
 * Browser: chrome

**Comment by devaskim** [comment]
After rule chain got *New Event* event, try to use *Change Originator* node to act on behalf on created device. Then use *Device Attributes* node

**Comment by yaron-gorillalink** [comment]
Hi @ashvayka ,
Thanks for  your answer. It didn't worked. 
this how my rule chain look like :
![Screen Shot 2023-04-09 at 11 34 38 AM](https://user-images.githubusercontent.com/84899414/230762834-dd279eb7-edad-4bd9-86a5-928f3807321e.png)

this is my _Change Originator node _ : 
![Screen Shot 2023-04-09 at 11 33 37 AM](https://user-images.githubusercontent.com/84899414/230762859-a14021c6-6980-43fb-8255-2c8319f55401.png)

when creating a new device i get failure:  
![Screen Shot 2023-04-09 at 11 37 16 AM](https://user-images.githubusercontent.com/84899414/230762915-2cd8b27b-c949-440d-adec-698232341606.png)

i'm expecting to get the device id in metadata but this is the metadata i get: 
![Screen Shot 2023-04-09 at 11 39 49 AM](https://user-images.githubusercontent.com/84899414/230762998-304255c6-ab16-4360-afa7-b1bf9ca2adc9.png)

so i can not get the device as origin and can not get the device attributes.

Please help,
Thanks,
Yaron

**Comment by devaskim** [comment]
I am not @ashvayka and you are using Change Originator in wrong way for your case.
![changeorinator](https://user-images.githubusercontent.com/86909129/230782768-463580aa-3e67-4019-ae0c-c390ca30c4e0.jpg)

**Comment by yaron-gorillalink** [comment]
Hi @devaskim , 
Thanks for your answer. I see no option in 'change originator' to select 'Entity' as originator source. There is only the following option: _Customer_, _Tenant_, _Related_ and _Alarm Originator_ . 
![Screen Shot 2023-04-09 at 11 39 49 AM](https://user-images.githubusercontent.com/84899414/232500877-b62b5206-b64c-40b0-943c-fd3ddca0f1eb.png)

**Comment by devaskim** [comment]
@yaron-gorillalink I am on TB 3.4.4

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
