### ISSUE TITLE
[Bug] Line chart: Number of digits after floating point is oddly long sometimes

### ISSUE THREAD

**Issue by qwerty13** [thingsboard/thingsboard#8315]
**Describe the bug**
I have a line chart that graphs 3 values from a device sending them with 4 digit after floating point:
![Screenshot 2023-04-05 121501](https://user-images.githubusercontent.com/12482779/230037669-fe95d61c-e7d4-4d59-8fa0-899caec2a7f6.png)

In past week I saw an odd thing that line chart tooltip is showing values sometimes correct and sometimes like this:
![Untitled](https://user-images.githubusercontent.com/12482779/230037387-16cf5748-a869-4f15-a9d8-462a5151d1fb.png)

Changing Static number of digits after floating point have no effect too (in data setting or per datasource)

**Your Server Environment**
* own setup
  * VPS Server
  * ThingsBoard Version 3.4.4
  * Ubuntu 20.04.5 LTS

**Your Client Environment**
* OS: Windows
* Browser: Edge
* Version: 111

* Connectivity
  * MQTT

**Additional context**
Widget used:
[LineChart.txt](https://github.com/thingsboard/thingsboard/files/11157263/LineChart.txt)

**Comment by devaskim** [comment]
Use post processing function `return value.toFixed(3);`

**Comment by qwerty13** [comment]
Yes I can patch it, but it most work itself without trick...
It's odd because [it's code](https://github.com/thingsboard/thingsboard/blob/060a54cd6dbb1234445992f0ea40daf20471ab1a/ui-ngx/src/app/core/utils.ts) looks good 🤔.

Another thing I found is that latest value in chart looks great but selfsame is incorrect when some new data adds!

**Comment by myroslav-tb** [comment]
Hi @qwerty13, this bug was fixed in the latest versions of the Thingsboard. Please update your instance to the latest version.

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
