### ISSUE TITLE
[Question]  /usr/local/bin/docker-entrypoint.sh: 11: exec: start-web-ui.sh: not found

### ISSUE THREAD

**Issue by a-jiang** [thingsboard/thingsboard#8319]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
![image](https://user-images.githubusercontent.com/9330004/230296767-4b623798-35c1-42ea-892d-b142cce88db3.png)

**Environment**

 * OS:  centos7
 * ThingsBoard: 3.4.2
 * Browser: name and version

**Comment by ban2derlog** [comment]
Hi,
Please, provide more information about this:
Which images do you use?
Which scripts do you use?
Do you try to investigate this script so this isn't issue with rights?
