### ISSUE TITLE
[Bug] The Prometheus metrics of  rule engine component is not exposed

### ISSUE THREAD

**Issue by mehranghajari** [thingsboard/thingsboard#8320]
I started thingsboard in micro-services mode via its docker-compose and enabled monitoring. After checking Prometheus targets and validating the healthiness of targets, found out that the rule-engine targets are not healthy.
Here is evidence:
1- Prometheus view
![image](https://user-images.githubusercontent.com/47135725/230321552-8a2bd3db-45b1-4ecb-a119-d2c9fc28f07e.png)
2- Requesting on "/actuator/prometheus" endpoint
![image](https://user-images.githubusercontent.com/47135725/230321979-5da6c1b3-dbbe-4cfe-9351-38dcd6c85df2.png)

**Comment by zhanggaohao** [comment]
It is because `ThingsboardSecurityConfiguration `only takes effect when `service-type=tb-core`.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by liuchenn** [comment]
It can be configured like this
```java
package org.thingsboard.server.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.thingsboard.server.queue.util.TbRuleEngineComponent;

@Configuration
@EnableWebSecurity
@TbRuleEngineComponent
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.authorizeRequests()
                .anyRequest().permitAll().and().logout().permitAll();
    }
}
```
