### ISSUE TITLE
[Bug] Scheduler is unable to create events

### ISSUE THREAD

**Issue by gnosticChemist** [thingsboard/thingsboard#8332]
**Bug Description**
Scheduler fails to create new events

**Server Environment**
* Google Marketplace ThingsBoard
  * thingsboard-pe-1-vm 
  * ThingsBoard PE v3.4.4
  * Ubuntu 20.04.4 LTS

**Client Environment**
* OS: Debian GNU/Linux 11 (bullseye)
* Browser: Mozilla Firefox
* Version: 102.8.0esr (64-bit)

**To Reproduce**
1. Go to 'Scheduler'.
2. Click on 'Add Scheduler Event'.
3. Fill the required Fields.
4. Click on 'Create'.
5. Error message appears.

**Expected behavior**
Creating a event.

**Error log**
Failure details: https://pastebin.com/PZKfnTaJ

**Comment by woodyjon** [comment]
Hello. Your pastebin seems empty.

**Comment by woodyjon** [comment]
I also have an issue with creating a scheduler for reporting. I don't know if it is the same issue as you, as I don't see your error message.
But when I try to create the scheduler, I have the following error in the UI: 
```
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```

And in the logs, I have the following:
```
2023-04-24 08:48:48,835 [http-nio-0.0.0.0-8080-exec-5] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
2023-04-24 08:48:48,835 [http-nio-0.0.0.0-8080-exec-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column schedulere0_.originator_id does not exist
  Position: 259
2023-04-24 08:48:48,836 [http-nio-0.0.0.0-8080-exec-5] INFO  o.h.e.i.DefaultLoadEventListener - HHH000327: Error performing load command
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
	at 
```

I think the scheduler table does not exist. I don't know if it is a bug or if it is me who misinstalled an upgrade in the past.

My thingsboard is on an ubuntu server and the version is V3.4.4PE.

**Comment by woodyjon** [comment]
For info, I fixed my problem by adding 2 properties (originator_id, originator_type) to the scheduler_event table with:

```
ALTER TABLE scheduler_event ADD COLUMN originator_id UUID;
ALTER TABLE scheduler_event ADD COLUMN originator_type character varying(255);
```

**Comment by Ultrazombie** [comment]
Thanks for the information,
Your comments will be very helpful if someone else has the same problem
