### ISSUE TITLE
[Question] Find source of timeouts in Rule Engine 

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#8338]
**Component**

 * Rule Engine

**Description**
I am getting several timeouts every week and I would like to find what is causing them and what data I am losing because of it.
How do you track the timeouts in the Cloud version of TB?

**Environment**

 * OS: macOS
 * ThingsBoard: Cloud (PaaS)
 * Browser: Chrome 

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/27728926/230741823-42c29349-699a-4c63-b6cb-9e682777f6c6.png">

**Comment by trikimiki** [comment]
Hi!
You should check the application logs. The timed-out messages (as well as failed ones) are shown in the following format:

... [...] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - Timeout/Failed to process [X] messages
... [...]  INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [...] Timeout/Failed to process message: <...> **_Last Rule Node: [RuleChain: RC-Name|RuleNode: RN-Name(id)]_**
