### ISSUE TITLE
[Question] How to add device id into message in rule engine?

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#8345]
**Component**

 * Rule Engine

**Description**
Can not get the id of device in rule engine, only device name can be found in metadata.

**Environment**

 * ThingsBoard: CE 3.4.4

**Comment by ashaforost** [comment]
@maksonlee you can use the originator fields rule node to get the device id in the rule chain:
![image](https://user-images.githubusercontent.com/47900737/231184079-96e514c8-ea5f-4ff5-be14-ba2e8cc83b96.png)

**Comment by maksonlee** [comment]
it works, thanks.

**Comment by nicovon24** [comment]
Iti s not working in 2024

**Comment by AndriichnekoDm** [comment]
Hi @nicovon24 
To answer properly, could you please provide more information about: 

- Platform type and version (CE, PE, or Cloud with corresponding version; DB type)
- Deployment type and hosting OS
- Steps to reproduce 
- Code/client used to achieve the result (with payload example, auth type)
- The desired behavior of the platform or, basically, the user story
- The nature of the question and end goals you have in mind
- Modifications or custom code done
