### ISSUE TITLE
entityType should not be translated.

### ISSUE THREAD

**Issue by manuel-iot** [thingsboard/thingsboard#8352]
**Describe the bug**
When using entityType in a dashboard action's show/hide function, entityType is translated. Therefore, if you want to check entityType == "Device", it only works with English language settings. If the user has set German, for example, entityType returns "Gerät". This means that the function will only work for one language. In general, system-wide, such attributes/entity fields should not be translated.

**Your Server Environment**
3.4.4 PE / Ubuntu

**To Reproduce**
1. Create Dashboard - 
2. Create simple entity Alias
3. Add Widget (Entity Table)
4. Add Action with "Show/hide action using function"
5. Output "data" to console
6. Language set to EN: 
` entityType: 'Device'`
7. Switch language to German:
`entityType: 'Gerät',`

**Expected behavior**
entityType should always be "Device" and not translated

**Comment by myroslav-tb** [comment]
Hi @manuel-iot, this bug was fixed in the latest versions of the Thingsboard. Please update your instance to the latest version.

Best regards,
Myroslav
