### ISSUE TITLE
[Question] How can I change the `JWT_TOKEN_EXPIRATION_TIME` on a k8s deployment version?

### ISSUE THREAD

**Issue by seungbaeji** [thingsboard/thingsboard#8354]
I deployed Thignsboard a five-month ago, and it's already integrated with my company system. However, we need to change the `JWT_TOKEN_EXPIRATION_TIME` from default to more than a month. 

I found the below UI from the latest Thingsboard version but I cannot find the same UI from the integrated Thingsboard.
![image](https://user-images.githubusercontent.com/24621491/231326708-3d533104-86a6-4e5e-bfbf-76059e1d2666.png)

The integrated Thingsboard shows the below UI. There are no JWT security settings.
![image](https://user-images.githubusercontent.com/24621491/231326656-75029dc6-e91b-4b73-9ad0-925ad78b39db.png)

I cannot update the deployed Thingsboard because it can affect our system. How can I change the token time?

**Environment**
 * OS:  MacOS
 * ThingsBoard: 3.4
 * Browser: chrome

**Comment by ban2derlog** [comment]
hi,
this settings can be changed through Web UI only from 3.4.2 version.
in versions <3.4.2 you can modify it by adding parameters for ThingsBoard node.
JWT_TOKEN_EXPIRATION_TIME = value in seconds
JWT_REFRESH_TOKEN_EXPIRATION_TIME = value in seconds
https://thingsboard.io/docs/user-guide/install/config/

**Comment by seungbaeji** [comment]
@ban2derlog Thanks~!! My team added the env to the YAML file and it works well!
