### ISSUE TITLE
[Question] How can I use media queries for a popover ?

### ISSUE THREAD

**Issue by TortueHardie** [thingsboard/thingsboard#8355]
Hello, I want to use a media queries to change the CSS of a popover in my entities table, but, when I want to do it, it just doesn't works. The popover action button shows a map, on mobile phone it just render very badly (see next picture).
![image](https://user-images.githubusercontent.com/116554402/231449310-daf68f01-5ea6-4691-b234-1897b4c02700.png)

I tried multiple things but it just doesn't work, it seems that the widget don't know what type of screen is used.
![image](https://user-images.githubusercontent.com/116554402/231447468-045335a4-7965-4688-9664-f8c4b61422be.png)

Have a good day and thank you for your time !

**Comment by devaskim** [comment]
Not sure that it helps but try to

- move such styles to Dashboard CSS
- use CSS `!import` for sure
