### ISSUE TITLE
Local installation of new ThingsBoard 2.0.1 on Windows 10 fails with error

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#836]
I am trying to install locally the 2.0.1 thingsboard server on a Windows 10 PC, after uninstalling the previous 2.0 version (with uninstall.bat).
During the installation of the new version, the following error occurs:

```
Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
```

What can be done ?

**Comment by vparomskiy** [comment]
If previous install use HSQLDB, then you can manually clear it before installation

**Comment by abrasat** [comment]
Thx for reply.
Could you please send me a link about can this be done on a Windows 10 machine ?

**Comment by vparomskiy** [comment]
in the Thingsboard install directory, go to ./data/sql/ and remove all files from this directory **EXCEPT of** 

- schema.sql
- system-data.sql

After this, try to install again.

**Comment by rsrini7** [comment]
uninstall  not deleting the generated db files under thingsboard\data\sql

Folder : thingsboardDb.tmp
Files : thingsboardDb.lck, thingsboardDb.log, thingsboardDb.properties, thingsboardDb.script
