### ISSUE TITLE
PDF export fails (new issue)

### ISSUE THREAD

**Issue by taddei68** [thingsboard/thingsboard#8361]
**Describe the bug**
Dashboard PDF export produces : `{"status":503,"message":null,"errorCode":2,"timestamp":"2023-04-13T14:06:42.708+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}
`
**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.3.4.1
  * Web Report 3.4.4. (installed 3.4.1 first time, when that didn't work I upgraded to 3.4.4)
  * Windows Server 2019

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows
* Chrome
* Version 109.0.5414.75

**To Reproduce**
1. Go to 'Dashboard.'
2. Click on 'Export Dashboard'
3. Scroll down to 'Export as PDF'

**Expected behavior**
I expect to get a PDF, but instead I get:
`{"status":503,"message":null,"errorCode":2,"timestamp":"2023-04-13T14:06:42.708+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}
`

**Screenshots**
![image](https://user-images.githubusercontent.com/33156693/231789564-71a9ce7d-5763-4b59-92fb-edb4cef2ae70.png)

![image](https://user-images.githubusercontent.com/33156693/231789450-2f9e7783-bbd7-4fc0-ae13-618fcc7c76d0.png)

**Additional context**
1. My web report log says:
```
2023-04-13 16:05:59,054 [main] INFO: Bind address: 0.0.0.0
2023-04-13 16:05:59,055 [main] INFO: Bind port: 8383
2023-04-13 16:05:59,055 [main] INFO: Starting ThingsBoard Web Report Microservice...
2023-04-13 16:05:59,055 [main] INFO: Chrome headless browser executable: C:\Program Files (x86)\tb-web-report\chromium\chrome.exe
2023-04-13 16:06:00,217 [main] INFO: Started chrome headless browser.
2023-04-13 16:06:00,217 [main] INFO: Headless chrome browser version: 104.0.5112.20
2023-04-13 16:06:00,217 [TbWebReportPageQueue] INFO: Initializing pages queue with size: 1
2023-04-13 16:06:01,274 [TbWebReportPageQueue] INFO: Pages queue initialized.
2023-04-13 16:06:01,278 [main] INFO: ==> 🌎  ThingsBoard Web Report Service listening on http://0.0.0.0:8383/.
2023-04-13 16:06:01,278 [main] INFO: Started ThingsBoard Web Report Microservice.
2023-04-13 16:06:12,331 [ReportController] INFO: Generating dashboard report: baseUrl http://qnflro49mp.pcg.cargill.com:8080/, dashboardId: a9e875b0-29ca-11ed-8c68-2fd4ed306eb3. Active requests count: 1
2023-04-13 16:06:12,332 [TbWebReportPage-1] INFO: Generating dashboard report
2023-04-13 16:08:20,699 [ReportController] ERROR: Operation 'init page' timed out!
```
NOTE:
 i) The error message appears approx 30sec after the first log item, i.e. (2023-04-13 16:05:59,054 [main] INFO: Bind address: 0.0.0.0) + 30sec
ii) I have done some adjustments on default timeouts in the config file, hence the delay of approx 2min before the ERROR is issued.

2. This issue seems very similar to:
https://github.com/thingsboard/thingsboard/issues/5960
https://github.com/thingsboard/thingsboard/issues/6574
But still not exactly the same as you can se from the log file. Please advice.

3. This is the first time I have been using the web report tool on this installation, hence it has never worked before.

**Comment by pon0marev** [comment]
When the dashboard loads in your browser, does it load quickly? Do all widgets and their data load quickly?
Are you using custom widgets?
What type of deployment do you use? Is it a docker deployment, Ubuntu service, or Windows service?
How many resources are allocated to the server?

The timeout occurs because the default LOAD_DASHBOARD_RESOURCES_TIMEOUT is 10 seconds. This is not enough to load all the dashboard resources. Try increasing this parameter to 30 seconds. Try to add this line to the configuration file (`sudo nano /usr/share/tb-web-report/conf/tb-web-report.conf`) if you have a deployment as a Ubuntu service:
`export  LOAD_DASHBOARD_RESOURCES_TIMEOUT=30000`
After that, restart the service:
`sudo service tb-web-report restart`
Best Regards, Andrii.

**Comment by taddei68** [comment]
> 
@pon0marev 
As a test, I have made a small dashboard with only one widget on it. The widget is a standard HTML card as depicted below. Everything loads in less than 1 second. 

![image](https://user-images.githubusercontent.com/33156693/235604286-0d6e1193-481a-40c4-8cab-2526fa109624.png)

The deployment type is a Windows service running on a virtual environment (VMware). Not sure what you mean by 'How many resources are allocated to the server?'

For additional information, there are the configured settings in production.yml:
server:
  # Server bind address
  address: "0.0.0.0"
  # Server bind port
  port: "8383"
  # port: "8080"

browser:
  # Browser launch timeout (ms)
  launchTimeout: "120000"
  # Default page navigation timeout (ms)
  defaultPageNavigationTimeout: "120000"
  # Generate report request timeout (ms)
  generateReportTimeout: "120000"
  # Load dashboard resources timeout (ms)
  loadDashboardResourcesTimeout: "120000"
  # Dashboard idle wait time (ms)
  dashboardIdleWaitTime: "60000"
  # Max browser pages
  # maxPages: "5"
  maxPages: "1"

**Comment by pon0marev** [comment]
How much CPU and RAM do you allocate to the virtual machine?
This value is unnecessarily huge:
`dashboardIdleWaitTime: "60000"`
Try to set a lower value, like 10000(10 seconds).

If you still need 60 seconds, you should also update the parameter for Thingsboard service:
`SPRING_MVC_ASYNC_REQUEST_TIMEOUT=90000`

**Comment by taddei68** [comment]
As recommended in separate Email, I replaced Web Report v3.4.4 with v3.3.4.1 Before I installed the latter version, I rermoved the former completely. After this, the Web Report works perfectly as it should.
