### ISSUE TITLE
Time period from GUI to python script

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#837]
Hi all, 

I don't want my scripts to run permanently. Instead I want to choose the time period I want to see in GUI and let the script load the past data from that period to Thingsboard. Is it possible to make connections between the time period in the GUI and the time period in my script?

**Comment by vparomskiy** [comment]
You can select any preferred time window for the dashboard by pressing **Edit timewindow** button in the top right corner.
