### ISSUE TITLE
[Bug] the value of timeserie on widgets change with page refresh 

### ISSUE THREAD

**Issue by pfernandes-dyn4** [thingsboard/thingsboard#8372]
The value in timeserie change all time i do a page refresh. Change in table and charts. See screen shots. 

![image](https://user-images.githubusercontent.com/127698139/232252385-d1fd0feb-f8cf-41ba-8653-8a94882cd5c8.png)
![image](https://user-images.githubusercontent.com/127698139/232252406-b77025b1-b881-4f16-b5cc-122f7a539397.png)
![image](https://user-images.githubusercontent.com/127698139/232252418-17b06dd7-03c2-4a4d-8db1-8ce3792f2361.png)

happen the same with realtime and history. And this is not the value i have in db.

**Your Server Environment**
* site.dyn4.cloud
* ThingsBoard Cloud Prototype 
* Browser Google Chrome last one
* Browser Firefox last one

**Comment by ban2derlog** [comment]
Good day,

Is this widget from default Widget Bundle or custom one?
Do you use Aggregation or Cell Functions in this Widget?
Or export this Widget and share it.

**Comment by pfernandes-dyn4** [comment]
Good day,
is the default Widget. (Timeseries table)
After some test, i find, this problem only happen with filter "dashboard timewindow" on.
![image](https://user-images.githubusercontent.com/127698139/235727665-5598110d-8fe1-4a0b-8513-a177afe26370.png)

if is not selected the values are ok.

**Comment by ban2derlog** [comment]
Hi,

Please, recheck and share your settings for Dashboard Timewindow in `Edit` mode.
![image](https://user-images.githubusercontent.com/33271053/235870421-a7f24cd7-738e-4b2b-ae1e-eb911f80cf73.png)

**Comment by devdoob** [comment]
set "Data Aggregation Function" to none in dashboard timewindow

![image](https://user-images.githubusercontent.com/1464600/235967182-851654b6-c6ec-46a8-a6ac-31e6451539b0.png)

**Comment by SamueleCarboni** [comment]
Hello. Has someone solved this issue somehow? 
I have the same problem using a Timeseries Table Widget with its own Timewindow (not the Dashboard one).
Thanks

![image](https://github.com/thingsboard/thingsboard/assets/39309463/26807119-a3cd-4610-9787-decec4b252a3)

**Comment by myroslav-tb** [comment]
Hello @pfernandes-dyn4, we were unable to reproduce the issue on our side. If the issue still persists, please open a new ticket for us with detailed step-by-step instructions on how to reproduce it.

Best regards,
Myroslav
