### ISSUE TITLE
[Bug] After Updated from PE 3.3.2 to 3.4.4 the translation files were not updated

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#8374]
After upgrading from PE3.3.2 to PE3.4.4 some text are not show on human readable way, the translation files were not updated (ive compared my Custom translation file with thingsboard.cloud custom translation file they are different). 

**I followed the instructions** and updated one version after other till 3.4.4. What do I need to do to fix it?

Here are some examples:

![image](https://user-images.githubusercontent.com/77509200/232373324-7ff20b51-231c-424a-9c0d-ff46f1657ed9.png)
![image](https://user-images.githubusercontent.com/77509200/232373342-6afba8c6-42ec-4e89-9000-b177d9c9e667.png)
![image](https://user-images.githubusercontent.com/77509200/232373364-f9aa8d39-e36c-456d-a1b7-c52bf438ee82.png)

there is also others where this occurred .

**Comment by Backdraft007** [comment]
Can you please clear your browser cache?

**Comment by ifelse-code** [comment]
Yes, it solved the problem. Thank you.
