### ISSUE TITLE
[Question] Domain certificate details

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8379]
**Component**

 * Generic

**Description**

Just to confirm. My Domain details is showing that my certificate will expire on 22/06.

![image](https://user-images.githubusercontent.com/7483656/232511477-5b778edf-f07c-4469-b3a3-b2725791f66d.png)

As I checked in ThingsBoard documentation there is no action required to renew this. Is this right ?

![image](https://user-images.githubusercontent.com/7483656/232511764-e21abbb1-4ec4-494f-bd1a-6203e91fc02d.png)

**Environment**

ThingsBoard: ThingsBoard Cloud Prototype
Browser: Microsoft Edge version 104.0.1293.63

**Comment by ban2derlog** [comment]
Good day,

Yes, all certificates for Domains of ThingsBoard Cloud users have autorefresh function.
ThingsBoard Cloud will automatically renew the certificate earlier than 30 days before it expires, no action is required from your part unless you change or delete the domain CNAME record.
