### ISSUE TITLE
[Question] how to show historical calculated timeseries on widget level

### ISSUE THREAD

**Issue by andonoc** [thingsboard/thingsboard#8381]
Widget

 * UI

**Description**
If i want to have a card widget that shows a calculated value from a defined time-span, how can i do this.
say you want to display the average temperature of the last 24 hours displayed on some kind of card (without saving it to the database)

 * ThingsBoard: 3.4.4

**Comment by devaskim** [comment]
Use [attributeService](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts#L121)
```
self.ctx.attributeService.getEntityTimeseries(....).subscribe(
    timeseries => {},
   error => {}
);
```
