### ISSUE TITLE
Interaction between widgets

### ISSUE THREAD

**Issue by samir-verma-s** [thingsboard/thingsboard#8382]
**Component**

 * UI
**Description**
Hi Team,
First of all i am new to Thingsboard and trying to implement the following.
I am implementing two simple custom widget of type latest value called A and B. 
I want to  send some data from A to B based on some event occur in A for that i found small code snippet that is working in older version 2.x but not working in 3.4.4. 
In widget A (send event)
$scope.$emit('my-custom-event',
            {startTime: vm.currentEntity.startedAt, endTime: vm.currentEntity.endedAt, deviceId: vm.currentEntity.deviceId}
        );

In widget B (receive event)
$scope.$on('my-custom-event', function (event, data) {
                if (data) {
                    actOnEvent(data);
                }
            });

is this future removed from 3.4.4 or please help some alternative for this.

**Environment**

 * OS:  Ubuntu 22.04.2
 * ThingsBoard: 3.4.4
 * Browser: Chrome Version 110.0.5481.177

**Comment by samir-verma-s** [comment]
Thanks it's working.
but what about $scope.$root.$on ?

**Comment by devaskim** [comment]
TB's `$scope` is [custom TypeScript class ](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts#L93), it in't Angular's API

**Comment by samir-verma-s** [comment]
i tried to access self.ctx.$scope.$root but getting undefined.

**Comment by devaskim** [comment]
> i tried to access self.ctx.$scope.$root but getting undefined.

Are you serious? I wrote before that TB's `$scope` doesn't have any `$root`, `$on` and `$emit`. Use `broadcastService` for interaction between widgets.

**Comment by samir-verma-s** [comment]
Thanks @devaskim for your help.It's working
