### ISSUE TITLE
[Question] Provisioning already exist device

### ISSUE THREAD

**Issue by qwerty13** [thingsboard/thingsboard#8385]
**Component**

 * Generic

**Description**
I have a device that it may attempt to provision itself in some situation (like after factory reset), but when device attempts to provision with it's previous "deviceName", the response is failure like following:

`{
  "errorMsg": "Failed to provision device!",
  "status": "FAILURE"
}`

Is there a way to restore my device submitted before in Thingsboard?

**Environment**
 * ThingsBoard: v3.4.4

**Comment by devaskim** [comment]
We faced with such type of issue too while upgrading firmware. Currently, there is no solution.

**Comment by devaskim** [comment]
It is by design.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
