### ISSUE TITLE
[Question] Dashboard Filters Programmatically

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#8395]
**Description**
Is that possible to create code, to change value of Dashboard filtering?
![image](https://user-images.githubusercontent.com/12267053/233103083-fd55c828-be57-4373-8480-756dde89d12b.png)

Let's say I have custom entity widget, then I want to put codes at **self.onInit = function() {...}** to change value of dashboard-filter,

let say I want a code that will change value of the filter  (on background)  to "mySite".
if another user open that widget page, code will change filter value to "differenMySite" and then it will filters the data  

is that possible to do?

**Comment by devaskim** [comment]
```
self.ctx.aliasController.updateUserFilter(yourFilter);
```

Here is [full list of](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L114) `aliasController` API

**Comment by evanderbird** [comment]
Thanks devaskim that's helpful. 
Will try it soon.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
