### ISSUE TITLE
[Bug] After Updated from PE 3.3.2 to 3.4.4 some server side params is missing

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#8397]
After upgrading from PE3.3.2 to PE3.4.4 some server side attributes were deleted. The first one was the latitude and longitude params that in some devices got deleted. I do have abour 85 devices, and latitude and longitude were deleted on about 10 of them.
 
I followed the instructions and updated one version after other till 3.4.4. Is there a way to fix it without restoring the backup of database? I noticed it just now, 3 days after the update, if I restore the backup I will lose 3 days of data.

I do use ubuntu.

**Comment by ifelse-code** [comment]
anyone?

**Comment by trikimiki** [comment]
Most likely, your upgrade failed somewhere. It would be impossible to delete data with upgrade scripts.
