### ISSUE TITLE
[Question] How can a widget add other widgets to a dashboard

### ISSUE THREAD

**Issue by DocOliv** [thingsboard/thingsboard#8399]
**Component**

 * UI

**Description**
I would like to add several widgets dynamically to a dashboard.
I can list the devices of a customer and define dedicated aliases to all of them, and I can add one widget for each in the configuration of the dashboard :

`dashboardObj.configuration.widgets[newWidget.id] = newWidget
`
with `dashboardObj ` is returned by the dashboardService

The configuration is well updated but the widgets are not displayed.
I'm quite sure I'm missing something simple.

**Environment**

 * OS:  ubuntu
 * ThingsBoard: community edition
 * Browser: google chrome

**Comment by devaskim** [comment]
Not sure if it is ever possible, that you are trying.

[not tested] As alternative, you could put your widget to separate dashboard state. Then create custom widget and use [tb-dashboard-state](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-state.component.ts) in the loop:
```
<ng-container *nfFor="let device of ctx.datasources">
    <tb-dashboard-state [ctx]="ctx" [stateId]="yourDashboardStateIdWithOneWidget" [entityId]="{ id: device.entityId, entityType: device.enitityType}"></tb-dashboard-state>
</ng-container>
```

**Comment by DocOliv** [comment]
Hi thank you for giving me a feedback 😉

I achieved my purpose by an alternative solution. Instead of dynamically creating widgets in a Dashboard, I list and display features of my customer’s devices in a single widget.

I’ll post new messages in case of other difficulties


Bye

Olivier

**Comment by devaskim** [comment]
I think it would be better to close issues after you or someone else find the solution. It saves time of community.
