### ISSUE TITLE
how to use refresh token to renew session

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#840]
What is the right way to use refreshToken, when token expires.

**Comment by AlexanderJP91** [comment]
For the first login use the endpoint /api/auth/login, using the following:
headers:
- 'Content-Type': 'application/json'
- 'Accept': 'application/json'
data:
- "username": USERNAME
- "pass

word": PASSWORD

This will return you the token and the refreshToken

Once the token is expired, use the endpoint /api/auth/token to received the new token. Use the following:
'Content-Type': 'application/json'
'X-Authorization': bearerToken
data:
"refreshToken": refreshToken
where bearerToken is the concatenation of the string "Bearer " with the token (don't forget the space!)

This will now return you a set of valid token and refreshToken

**Comment by untilbit** [comment]
Thank you very much @AlexanderJP91 
I tested and it's working. I'll implement it in my python.

**Comment by ten2net** [comment]
Thanks ,AlexanderJP91,This issue give me a large help ,I tested and it's working.

**Comment by vparomskiy** [comment]
thank you

**Comment by hgultekin** [comment]
> Once the token is expired, use the endpoint /api/auth/token to receive the new token. Use the following:
> headers:
> 
> 'Content -Type': 'application/json'
> **'X-Authorization': bearerToken**
> 
> data:
> 
> "refreshToken": refreshToken
> where bearerToken is the concatenation of the string "Bearer " with the token (don't forget the space!)
> 

You do not need to send 'X-Authorization': bearerToken
Following will be enough to get refreshed token and refresh token
```
POST /api/auth/token HTTP/1.1
Content-Type: application/json
Accept: */*
{"refreshToken":"<Your refresh token returned from login method>"}
```

**Comment by DevNico** [comment]
How do I know If my token expired? Do I get a lifetime somewhere or do I just refresh the token when a authorized request fails?

**Comment by manjrekarom** [comment]
@DevNico You can use check **exp** claim after decoding jwt token. An easy way is to use a jwt library.

Installation of PyJWT 
`pip install pyjwt`

Then use the following code to find the expiry.
```
import jwt
token = '...'
decoded_dict = jwt.decode(token, options={"verify_signature": False})
print(decoded_dict['exp'])   # returns unix epoch in seconds
```

**Comment by sudhirbits** [comment]
Could not find this token api as part of swagger. But followed this ticket's steps and the refresh JWT flow works to get new set of tokens.
