### ISSUE TITLE
TCP communication to Thingsboard platform

### ISSUE THREAD

**Issue by EzequielDesarrolloIot** [thingsboard/thingsboard#8403]
I need help to know how to link and transmit data from a device that has TCP communication to thingsboard.cloud PE, since the platform does not have that type of communication predefined. I have the domain and the port to make the connection.
I read the TCP integration documentation but couldn't manage to communicate it.
I would be very grateful if you give me your help.
Thank you

**Comment by Backdraft007** [comment]
Do you have read this document?
https://thingsboard.io/docs/paas/user-guide/integrations/tcp/

**Comment by EzequielDesarrolloIot** [comment]
Hi Backfdraft007, first of all thanks for replying, you have already helped me from other accounts of mine. I give you an idea so you know what happens to me:
1. i have the thingsboard.cloud platform without the open source, i.e. i can't visualize it.
I need to send data through a GPS device for example latitude and longitude. The two protocols that can send are TCP and UDP. That only lets me assign domain/IP and a port which in this case would be 10560 and the port would be my domain.
3.	I copy as they are the options of the data converters and Integrations (everything totally equal as this in the documentation).
4.	My doubt begins here, since it makes you download netcat (I have Windows) and makes you send data command for example temperature, humidity, etc.. I never managed to do it. But it is not what I want, I want to send the data from my gps. 
5.	I do not understand how the data would arrive, I am using HTTP and MQTT communication, all perfect with their corresponding credentials. But the TCP/UDP option is not there. How would I link to the device? 
Sorry for the complication but if you don't understand I can try to explain myself better.

**Comment by Backdraft007** [comment]
Hi,
netcat is only for testing/simulate a device to script proper converters. If your device sends data to cloud you can enable the debug in your integration and have a look if something happen.

**Comment by netbc** [comment]
We are currently using both TCP and UDP remote integrations. The problem is that messages can only be processed one by one. If the protocol expects exchange of login frames first and then sending data in a separate frame it will not work as the device answers to the downlink cannot be captured in the rule chain.
