### ISSUE TITLE
Use of API KEY authentication and HTTP request headers

### ISSUE THREAD

**Issue by DaniilSch** [thingsboard/thingsboard#8408]
**Component**
 * Rule Engine, "REST api call" node

**Description**
The rule chain node "REST API call" seems like a powerful feature that allows TB to communicate with potentially every web-service out there. 

However, a number of web-services use header data for authentication API KEY authentication and HTTP request headers. I.e. API key is sent in the header in a KEY:VALUE format.

Question is, how to send an API request to a 3rd party server that expects an API key in the header?  Since the only way of auth in TB 2.5 is Basic and PEM, is there any way to modify the header, or compose the HTTP request manually before sending?

**Environment**
 * OS:  Win10 21H2
 * ThingsBoard: 2.5
 * Browser: Firefox 103

**Comment by Backdraft007** [comment]
TB 2.5 is very old. In actual versions you can send http headers.

**Comment by DaniilSch** [comment]
> TB 2.5 is very old. In actual versions you can send http headers.

Thanks! Updating TB worked, can send headers now.

**Comment by DaniilSch** [comment]
Thanks! Updating TB worked, can send headers now.
