### ISSUE TITLE
Cannot installation thingsboard on windows!!!

### ISSUE THREAD

**Issue by heokute** [thingsboard/thingsboard#8410]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
I'm going to install thingsboard v3.4.4 on windows 10, but I get problem as log file. "Thingsboard installation failed"
Anyone can help me, thanks a lot!!!

**Environment**

 * OS:  Windows 10 x64
 * ThingsBoard: v3.4.4
 * Browser: Chrome Version 112.0.5615.122 (Official Build) (64-bit)
[install.log](https://github.com/thingsboard/thingsboard/files/11291156/install.log)

**Comment by Backdraft007** [comment]
What are your commands. From which version do you upgrade?

**Comment by evanderbird** [comment]
Yeah happen to me as well, always fail in docker windows. 
Then I gave up end instal it on Linux, successfully only first try

**Comment by Ultrazombie** [comment]
Hello @heokute 
As I can see from the log you have "thingsboard" database is installed.
Please confirm that's your database consist the same version of ThingsBoard and try to run without installation.
`2023-04-21 06:29:44,799 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.postgresql.util.PSQLException: FATAL: database "thingsboard" does not exist`
