### ISSUE TITLE
[Bug] Reflected HTML injection via outdated swagger

### ISSUE THREAD

**Issue by mathiasbosman** [thingsboard/thingsboard#8411]
**Describe the bug**

they have found that you are able to load your own content from example https://gist.githubusercontent.com/0xdln1/T his prompt is being served from an arbitrary location (authorization.site), which can be modified as needed to be as convincing as possible to any possible victim. Imagine yourdomain.authorization.site, for example. Depending on the browser being used, a message can be included along with the prompt to make it seem more trustworthy. When a victim enters their information into the prompt, it is sent to the arbitrary location being used by the attacker (authorization.site) along with their IP address, and stored in plain text for the attacker to use when desired?

**Your Server Environment**
* demo.thingsboard.io

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: All
* Browser: All
* Version: 3.4.4 (currently the latest)

**To Reproduce**
1. Go to 'http://demo.thingsboard.io/swagger-ui/index.html?configUrl=https://gist.githubusercontent.com/0xdln1/8a89b4530eb3110e678bc1982bf38921/raw/e64def6b8fa2bb1b77c64cc2af3c61bb8321d1be/ext-injection.json'
2. Click on the link on top

**Additional context**
This vulnerability was reported to us via a BugBounty program.

**Comment by ssakharova** [comment]
Hello @mathiasbosman,

The issue described is no longer relevant, as it has already been fixed. 
Thank you for highlighting the problem.
