### ISSUE TITLE
[Question] Excuse me, can we add the flags of other invaded countries like Iraq, because they are also innocent?

### ISSUE THREAD

**Issue by example-cloud** [thingsboard/thingsboard#8415]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by devaskim** [comment]
It is open source project, so you you create pull request with desired changes

**Comment by xalt7x** [comment]
I assume that this question is about the documentation website, not the app.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
