### ISSUE TITLE
Rule Chain alert with timestamp filter

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8417]
**Component**

 
 * Rule Engine

**Description**
I'm using Thingsboard to monitor the flow of water, and I want to create a rule chain that will send me a notification only if the water flow is 0 for a certain period of time. Specifically, What I want to happen is that if the water flow is at 0 for 10 mins then I receive a notification. 
How can I set up this rule chain in Thingsboard?

I currently have it alaming and sedning notifications when the water flow is less than 1 L/Min (see picture below) but id like to add a timestamp in the filter script.  Is there write this? Thanks 
![image](https://user-images.githubusercontent.com/130080104/233671914-54f3721b-ec0b-4554-a3d9-cea79a06b3ca.png)
![image](https://user-images.githubusercontent.com/130080104/233671957-b8d6a70c-8bc1-4279-809f-ed27a7dc615a.png)

Thanks

**Comment by devaskim** [comment]
You could create additional server attribute for your device called `NoFlow_StartTimestamp`. Every time rule chain gets telemetry from the device you need either reset this attribute or set it depending water flow is or not correspondingly. Then if there is no flow, you need compare `NoFlow_StartTimestamp` with current time `Date.now()` and trigger alarm if no-flow period is more than something.

**Comment by Backdraft007** [comment]
Hey,
in my opinion the device profiles are better for this scenario:
https://thingsboard.io/docs/user-guide/device-profiles/#alarm-rules

**Comment by Buhaw85** [comment]
Thanks @Backdraft007 this works. Is there a way to send the Alarm title in the email? 
![image](https://user-images.githubusercontent.com/130080104/234952432-20835139-74b2-4190-9622-d52ef16ee37f.png)
![image](https://user-images.githubusercontent.com/130080104/234952581-8fe9b8f7-b662-4b30-92a6-1cde48e33757.png)
![image](https://user-images.githubusercontent.com/130080104/234952720-19bf56b5-ff67-4b0a-81a7-c20a76442d38.png)
 
i would like the alarm type to show up in my email.

thanks

**Comment by Backdraft007** [comment]
You can use $[name] in to Mail rule node.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
