### ISSUE TITLE
Attribute update subscription doesn't appear to be functioning

### ISSUE THREAD

**Issue by DMCEngineering** [thingsboard/thingsboard#842]
I have a 2.02 Thingsboard server set up and have been trying to test the attribute subscription functionality, but it doesn't appear to be working.

Test Case
- Created device
- Added shared attribute
- Call 

`curl -v -X GET http://localhost:8080/api/v1/$ACCESS_TOKEN/attributes/updates?timeout=20000` or
`mosquitto_sub -d -h "127.0.0.1" -t "v1/devices/me/attributes" -u "$ACCESS_TOKEN"`

from example documentation with correct address and device token

- Modify shared attribute using device page in UI

I don't see any notifications come back in either the http or mqtt test.

I can confirm that the attribute exists using the request api on http and mqtt.

**Comment by rrabadia89** [comment]
@DMCEngineering I am also encountering the similar issue. Have you found any solution or further understanding on this issue ?

**Comment by ashvayka** [comment]
Fixed in v2.0.3. Will release in few days.

**Comment by DMCEngineering** [comment]
Verified it is working on 2.0.3.  Thanks!

**Comment by efeeyuboglu92** [comment]
Hello anyone still got the same issue? I dont get updates when i change attributes using command prompt. The attribute is being changed in the rule chain but i don't get notified even though I'm subscribed.

**Comment by tatuiot** [comment]
Hi team using NodeRed as a client I can publish telemetry and request shared attributes. No issues. but when I change shared attribute from devie/attribute screen, the client does not get notified. I have to pull a request to get it...  
But the link https://thingsboard.io/docs/reference/mqtt-api/ says that I should automatically get it...  I wonder why... Thanks if some tip could be shared.
