### ISSUE TITLE
[Question] Kafka timeout and api usage dashboard

### ISSUE THREAD

**Issue by tdsimpro** [thingsboard/thingsboard#8421]
**Component**

 * Rule Engine

**Description**
Hi,
I'm getting a lot of timeouts in the thingsboard logs like : 
`2023-04-24 13:17:01,426 [TB-Scheduling-4] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [964] successfulMsgs = [0] timeoutMsgs = [964] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterations = [0] failedIterations = [180] `
But I can't see any timeout or error in the api usage dashboard.
Where can I find the reason for this timeouts ? In the db or in the logs ? 
Thanks

**Environment**

 * OS:  Centos latest version
 * ThingsBoard: 3.3
 * Browser: Chrome

**Comment by ban2derlog** [comment]
Hi,
In 3.3 version it will be hard to investigate this.
You need check logs for ThingsBoard after change in `/etc/thingsboard/conf/logback.xml` Root level logger from INFO to DEBUG, so you will have much more logs output.
Keep in mind that this will provide much more logs and according to your rolling policy maybe will use more storage (by default maximum size will be 3Gb).
Additionally, you can start from Root Rule Chain and step-by-step enable `Debug Mode` on nodes to find where exactly you have errors in Rule Chain Nodes.

P.S. After debug don't forget to disable Debug mode for nodes and in logback.xml
