### ISSUE TITLE
[Question] How to use my own generate TLS certificate with ThingsBoard Cloud ?

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8426]
**Component**

 * Generic

**Description**
Is there a way to use my own paid TLS certificates file and import it to my ThingsBoard Cloud accound ?

According the [documentation](https://thingsboard.io/products/paas/domains/), the TLS certificate are generate automatically with Let's Script.

**Environment**

ThingsBoard: ThingsBoard Cloud Prototype

**Comment by ban2derlog** [comment]
Hi,

Unfortunately, you can't use your own certificates for Domain in ThingsBoard Cloud.
You can use your own certificate only with self-managed ThingsBoard service.
