### ISSUE TITLE
fail to build from source on win7 because of no response while running npm install

### ISSUE THREAD

**Issue by DuGuanhong** [thingsboard/thingsboard#843]
I tried to run the command 
mvn clean install -DskipTests -e
but failed because of no response.
it stopped here:

INFO] Installed npm locally.
INFO]
INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
INFO] Running 'npm install' in C:\Mysoftware\thingsboard-master\ui

I changed the version of npm and node to what mvn want, still no response.

Could anyone help me?

**Comment by vparomskiy** [comment]
you can use this command for debugging mvn. Maybe output will help to identify the problem.

> mvn clean install -DskipTests -X
