### ISSUE TITLE
[Bug] customer details & tenant details 

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#8431]
![image](https://user-images.githubusercontent.com/23446974/234439252-1b9d220b-06a6-4a28-ae49-21a23b11036e.png)

![image](https://user-images.githubusercontent.com/23446974/234439294-5a014ca4-c231-49f1-96f6-3805622e3ab9.png)

what is this ? id ?

**Comment by devaskim** [comment]
The empty selection option is [known bug](https://github.com/thingsboard/thingsboard-rule-config-ui-ngx/pull/107).

The main purpose of retrieving entity ID is to call TB API through REST API rule chain. Many TB API endpoints require ID as input parameter.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
