### ISSUE TITLE
[Question]Thingsboard Server Queue components install error

### ISSUE THREAD

**Issue by ssytech** [thingsboard/thingsboard#8432]
![image](https://user-images.githubusercontent.com/9995198/234472865-58229c47-6046-4d3b-9985-95b3124a35b1.png)

When I execute "mvn clean install -DskipTests", I am prompted with the following error
[ERROR] /D:/Document/workspace/thingsboard/common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusConsumerTemplate.java:[28,45] ▒▒▒▒▒org.apache.qpid.proton.amqp.messaging▒▒▒▒▒▒
[ERROR] /D:/Document/workspace/thingsboard/common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusConsumerTemplate.java:[29,45] ▒▒▒▒▒org.apache.qpid.proton.amqp.transport▒▒▒▒▒▒
[ERROR] /D:/Document/workspace/thingsboard/common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusConsumerTemplate.java:[30,45] ▒▒▒▒▒org.apache.qpid.proton.amqp.transport▒▒▒▒

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
