### ISSUE TITLE
[Feature Request] SMTP Server Configuration - Allow noAuth

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8441]
**Is your feature request related to a problem? Please describe.**
In some scenarios SMTP relay servers such as Microsoft Exchange Servers no authentication is used. This means that there are no credentials needed. 
This case is currently not supported, since each time empty strings were used:

**Describe the solution you'd like**
Add the option to allow noAuth in SMTP server configuration. 

**Describe alternatives you've considered**
Switch to authentication with credentials. Not possible in every customer environment.

**Additional context**
More details here:
#8309

**Comment by Ultrazombie** [comment]
https://github.com/thingsboard/thingsboard/issues/8309#issuecomment-1523598979 

We will not implement this functionality as it is not secure. as Alex said, this feature can be rejected.
