### ISSUE TITLE
translate platform into another language

### ISSUE THREAD

**Issue by Meisam-rashno** [thingsboard/thingsboard#8443]
**Component**

 * UI

**Description**
Hi mates!
I want to translate platform into another language, I wanted to know where to start? Where are the files related to the language?

thanks

**Environment**

 * OS:  Ubuntu 22
 * ThingsBoard: 3.4.4 
 * Browser: Firefox

**Comment by devaskim** [comment]
[Here](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
