### ISSUE TITLE
[Bug] Inefficient RabbitMQ polling

### ISSUE THREAD

**Issue by driesva** [thingsboard/thingsboard#8445]
**Describe the bug**
Inefficient RabbitMQ polling leads to messages piling up in Rule Engine queues

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard 3.4.4 PE 
  * CentOS-7
  * RabbitMQ (HA cluster)
  * Postgres database
  
**Your Device**
* Connectivity
  * MQTT
  * HTTP

**To Reproduce**
Have a device creating lots of data points and observe _tb_rule_engine.main_ queues in RabbitMQ.

**Expected behavior**
Messages not to pile up if hardware resources are properly sized and configuration settings are properly set.

**Additional context**
For a new use case, we have devices that send a lot more data. 

We noticed that messages are piling up in some of the _tb_rule_engine.main.n_  queues. We tried to play with following parameters without luck:
```
SPRING_DATASOURCE_MAXIMUM_POOL_SIZE
SQL_TS_BATCH_THREADS
SQL_TS_LATEST_BATCH_THREADS
SQL_TS_BATCH_SIZE
SQL_TS_LATEST_BATCH_SIZE
TB_QUEUE_RE_MAIN_POLL_INTERVAL_MS
TB_QUEUE_RE_MAIN_PARTITIONS
```

Hardware is not exhausted. CPU, memory consumption are all normal. Even after changing above parameters to extreme values.

Our rule chain is very simple, basically just a few “type switch” and “save timeseries” nodes. In the Message Pack Processing Log we see that the latter is the slowest, but finishes usually below 100ms.

In our RabbitMQ dashboard, we notice that the message consumption rate only achieves around 10 messages per second. 

We looked into the Github ThingsBoard source code and found in _TbRabbitMqConsumerTemplate_ following logic:

```
    @Override
    protected List<GetResponse> doPoll(long durationInMillis) {
        List<GetResponse> result = queues.stream()
                .map(queue -> {
                    try {
                        return channel.basicGet(queue, false);
                    } catch (IOException e) {
                        log.error("Failed to get messages from queue: [{}]", queue);
                        throw new RuntimeException("Failed to get messages from queue.", e);
                    }
                }).filter(Objects::nonNull).collect(Collectors.toList());
        if (result.size() > 0) {
            return result;
        } else {
            return Collections.emptyList();
        }
    }
```

So, during polling it seems that per queue, only 1 message is obtained? 

Moreover, it turns out this way of message consumption is not advised by RabbitMQ:

> It is also possible to retrieve individual messages on demand ("pull API" a.k.a. polling). This approach to consumption is highly inefficient as it is effectively polling and applications repeatedly have to ask for results even if the vast majority of the requests yield no results. Therefore using this approach **is highly discouraged**.
Source: https://www.rabbitmq.com/api-guide.html#getting

Is there are specific reason for this implementation?

Our own hackish attempt to loop inside that method and fetch more messages per queue per poll, improves the throughput. So, the conclusion is that they way how ThingsBoard consumes messages from RabbitMQ is not efficient and creates a bottleneck.

Can we expect any improvements in this area soon?

**Comment by ban2derlog** [comment]
Hi,
ThingsBoard have limits for RabbitMQ message size and message TTL for different parts of service.
Had you try to tune them?

    queue-properties:
      rule-engine: "${TB_QUEUE_RABBIT_MQ_RE_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      core: "${TB_QUEUE_RABBIT_MQ_CORE_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      transport-api: "${TB_QUEUE_RABBIT_MQ_TA_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      notifications: "${TB_QUEUE_RABBIT_MQ_NOTIFICATIONS_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      js-executor: "${TB_QUEUE_RABBIT_MQ_JE_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      version-control: "${TB_QUEUE_RABBIT_MQ_VC_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"
      integration-api: "${TB_QUEUE_RABBIT_MQ_INTEGRATION_QUEUE_PROPERTIES:x-max-length-bytes:1048576000;x-message-ttl:604800000}"

`The default behaviour for RabbitMQ when a maximum queue length or size is set and the maximum is reached is to drop or [dead-letter](https://www.rabbitmq.com/dlx.html) messages from the front of the queue (i.e. the oldest messages in the queue).`
https://www.rabbitmq.com/maxlength.html

**Comment by driesva** [comment]
Hello @ban2derlog 

I've seen those configs, but as I understand it, RabbitMQ will drop the messages from the queue if those limits are reached. I could increase those parameters in order to prevent messages from being dropped. However I would like ThingsBoard to consume messages faster from RabbitMQ, not more messages having piled up in the queues.

**Comment by driesva** [comment]
Given there's no satisfying answer, it makes our ThingsBoard setup with RabbitMQ unusable for devices that send many data points, where some kind of real time information is required.

I might provide a PR with a workaround to get more messages from each queue per poll, if there's some guarantee that someone will look into it.

Basically it comes down to modifying `doPoll` of _TbRabbitMqConsumerTemplate_ to:

```
    @Override
    protected List<GetResponse> doPoll(long durationInMillis) {
        List<GetResponse> result = queues.stream()
                .map(queue -> {
                    List<GetResponse> queueResult = new ArrayList<>();
                    for (int i = 0; i < n; i++) {
                        GetResponse response = doQueuePoll(queue);
                        if (response == null) {
                            break;
                        }
                        queueResult.add(response);
                    }
                    return queueResult;
                })
                .filter(r -> !r.isEmpty())
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
        if (result.size() > 0) {
            log.debug("Messages polled from RabbitMQ: {}", result.size());
            return result;
        } else {
            return Collections.emptyList();
        }
    }

    protected GetResponse doQueuePoll(String queue) {
        try {
            return channel.basicGet(queue, false);
        } catch (IOException e) {
            log.error("Failed to get messages from queue: [{}]", queue);
            throw new RuntimeException("Failed to get messages from queue.", e);
        }
    }
```
where `n` is a configurable parameter to indicate how many messages to obtain per queue.

**Comment by ban2derlog** [comment]
hi,
RabbitMQ in ThingsBoard deployment is recommended for small deployment without big load.
but if you will create a PR that resolve issue with limitation of queue, it can be implemented or used for improvement\solution.
in this case best approach will be to take batch(n) from configs, so it can be adjustable.
