### ISSUE TITLE
Publish mqtt data

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#845]
Is it also possible to publish mqtt data using thingsboard and tb-gateway ? Is there any configuration example available ? I would like for instance to use a switch control to send true/false values for a mqtt topic.

**Comment by mp-loki** [comment]
Do you mean publish from ThingsBoard to a device via Gateway?
I think this what you need:
https://thingsboard.io/docs/iot-gateway/mqtt/#server-side-rpc-commands
The default mqtt-config.json file has a sample documentation for it

**Comment by abrasat** [comment]
Yes, that is what I mean, mqtt publish from ThingsBoard to a device via Gateway.
Is there any concrete example available?

For instance how would this mosquitto_pub command look like if configured in mqtt-config.json ?

```
mosquitto_pub -h MQTT_BROKER_HOST -p MQTT_BROKER_PORT -t "sensor/connect" -m '{"value":true}'
```
And how can I decide the value to be published (in the above example true or false) with the help a switch control on a dashboard ?

**Comment by abrasat** [comment]
A complete example (with sample mqtt-config.json file and all other settings) for this use-case would be great.

**Comment by Karabiy** [comment]
you can use the external node "MQTT" in case you want to send telemetry to the MQTT broker
you can refer to this link regarding those: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#mqtt-node
in case if you want to send those for the  devices being connected directly/through MQTT integration, you can use RPC for the reasons of yours. 
you can refer to this link regarding the RPC: https://thingsboard.io/docs/user-guide/rpc/
