### ISSUE TITLE
[Question] How to call mobile action scan QR code in custom widget definition ?

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#8451]
**Description**
I'm creating a custom HTML widget and want to trigger a HTML button to show QR scanner on flutter mobile app.
How to call a Scan QR Code mobile action in a custom widget ?
Something like:
```

self.onInit = function () {
     ///.........
     self.ctx.$scope.scanQR = function(){
          ///..... something to trigger the mobile QR code scanner
     }
}
```

**Comment by devaskim** [comment]
Here is how I call action from custom widget
```
let actionDescriptor = self.ctx.actionsApi.actionDescriptorsBySourceId.headerButton.find(descriptor => descriptor.name === 'YOUR_ACTION_NAME');
self.ctx.actionsApi.handleWidgetAction({}, actionDescriptor, null, null, { });
```

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by liotys** [comment]
See #13091 for an answer.
