### ISSUE TITLE
Im looking for a way to say on my dashboard if a device is offline or online. Is there a widget for this or is there a way to put it on a simple card?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8452]
**Component**

Dashboard

**Description**
Hi im looking for a way to say on my dashboard if device is offline or online. I hace a simple card set up that says true or fasle but I would like for it to say decive online instead of true and device offline instead of false.
This is what i have come up so far but it doesnt seem to work. Maybe im writting it wrong.
Any suggestions?
Thanks

![image](https://user-images.githubusercontent.com/130080104/235285394-af0ffbcb-6649-4389-b105-dd63b0bc9eb8.png)
![image](https://user-images.githubusercontent.com/130080104/235285415-fd4377c7-c083-49bd-9f44-bbf5d4704b1c.png)
![image](https://user-images.githubusercontent.com/130080104/235285432-2ffa17ec-5429-4853-83de-f420029a08c5.png)

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by dhaval2017** [comment]
@Buhaw85 
if (value == 'true')
    return 'online';
else
    return 'offline';

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
