### ISSUE TITLE
[Question] DATA CONVERTER Maximum Character Setting

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#8453]
**Component**
 * Rule Engine
 * Data Converter

**Description**
org.thingsboard.script.api.TbScriptException: java.lang.IllegalArgumentException: Script input arguments exceed maximum allowed total args size of 150000 symbols.

Data Converter got error when try to process very big json data. I think there is a config to increase the size of max character.
Where is that config?

**Comment by ashaforost** [comment]
Hi @evanderbird 

Check out the following parameters in your thingsboard.yml:
JS_MAX_TOTAL_ARGS_SIZE -- the one you need to increase
JS_MAX_RESULT_SIZE 
JS_MAX_SCRIPT_BODY_SIZE

**Comment by ChrisEvisi** [comment]
Thanks very much for your information Ana.

**Comment by dzhonapp** [comment]
> Hi @evanderbird
> 
> Check out the following parameters in your thingsboard.yml: JS_MAX_TOTAL_ARGS_SIZE -- the one you need to increase JS_MAX_RESULT_SIZE JS_MAX_SCRIPT_BODY_SIZE


In a microserviced (k8s) deployment where we should make this change at?
JS_MAX_TOTAL_ARGS_SIZE <<<<<< JS_MAX_RESULT_SIZE JS_MAX_SCRIPT_BODY_SIZE
I have tried to provide env variable but it is not being respected on tb-node stateful set.
Thanks.
