### ISSUE TITLE
[Question]  Table ts_kv explanation values

### ISSUE THREAD

**Issue by georkoy** [thingsboard/thingsboard#8454]
Ηi ,
i use thingsboard with a PostgreSQL database. I have create a device which is connect with a rule change to get the data and then i visualize this data to the dashboard. I have notice that the data are stored in the table ts_kv. This table have some columns like entity_id , key , ts , etc. So , what is key? How that key is generated? Is this key has relationship with the device data? How can i find which key is represent each data?

Can i make a different table for  each different device and connect to the dashboard to visualize the data or only the ts_kv table are used?

is there an analytic documentation about this topics?

Thanks in advance!

**Comment by devaskim** [comment]
TB core uses only `ts_kv` and `tb_kv_latest`. Why you need another table?

`entity_id` - is unique device identificator
`key` - name of single telemetry parameter,e.g. `temperature`

**Comment by georkoy** [comment]
There is a table ts_kv_dictionary which contains the mapping from key ID to key name.
i think ,  thingboard need improvement in the documentation section

[stackoverflow](https://stackoverflow.com/questions/76132319/thingsboard-data-store-in-kv-ts-table/76155708)
