### ISSUE TITLE
[Question] How to sum a variable number of asset telemetry

### ISSUE THREAD

**Issue by schejbity** [thingsboard/thingsboard#8459]
I don't know how to create the sum of several telemetry that I create on Asset.

For a better idea:
![image](https://user-images.githubusercontent.com/88762302/235482284-b405bcbf-e974-44ed-bd1d-3791bbe4babf.png)

FVE_6 is an Asset
6_INV_x are devices that are part of the asset.

Each device has three values of delivered energy per phase.
E1 E2 E3. In the Rule Chain I make the sum E1+E2+E3=Ex_SUM and save it as the device telemetry.

I then transfer these sums to the telemetry of the asset. So Asset has its telemetry E1_SUM, E2_SUM, E3_SUM, E4_SUM, E5_SUM.

I need advice on how to create the sum of the sums on the asset, i.e.:
E1_SUM + E2_SUM + E3_SUM + E4_SUM + E5_SUM = E_SUM_TOTAL

I wanted to solve it in Rule Chain, but I don't know how to load all Ex_SUM from the asset? I mainly need to load Ex_SUM dynamically, because there will be more assets and each one will have a different number of devices.

Thanks for the advice.

**Comment by NistantriTech-Dhaval** [comment]
did you tried related attributes or related device attributes rule node?

**Comment by schejbity** [comment]
No, I don't. I don't know if this is correct, what I need.

This is how my asset telemetry looks like.
This is sample data only. In reality there will be many assets and each will have a different number of these telemetry and I always need to add them all up.
I load each telemetry in a separate message and not all at once.
![image](https://user-images.githubusercontent.com/88762302/235637058-5de1ee9d-5dd6-4c6f-b421-d484d508aeef.png)

Here are my rule chains:
![image](https://user-images.githubusercontent.com/88762302/235638620-d8495c60-9e18-4513-95d4-94a23460363c.png)

**Comment by NistantriTech-Dhaval** [comment]
@schejbity 

May be you can add this telemetry keys dynamically to asset server attributes?
so idea is when you store device sum to related asset add that to asset server attribute ex. device_telemetery_keys which will have array of keys name for each device sum of asset

now fetch is using originator telemetry or attributes rule node do the sum and store it back to asset as sum

**Comment by schejbity** [comment]
You mean at first step to create Asset Server Attribute like:
{device_telemetry_keys: [INV_1_ACDE_SUM, INV_2_ACDE_SUM, INV_3_ACDE_SUM, INV_4_ACDE_SUM, INV_5_ACDE_SUM]};

If yes, how?
I don't know how to create five array elemets from five device messages?

**Comment by NistantriTech-Dhaval** [comment]
yes 
I will suggest to make administrator dashboard for this so whenever you add or delete device to asset relation 
it should modify array of asset server attribute

**Comment by devdoob** [comment]
@schejbity which version of Thingsboard are you using? CE or PE?

**Comment by schejbity** [comment]
I have this:
![image](https://user-images.githubusercontent.com/88762302/236393440-0059cd7c-f53e-4f2f-8d6b-7cbe69be35b5.png)
![image](https://user-images.githubusercontent.com/88762302/236393463-4839cec8-97f0-448f-bfab-14e5089b25d6.png)
![image](https://user-images.githubusercontent.com/88762302/236393489-72664c4f-7be6-4d05-a13b-556f4a1d35f9.png)

**Comment by devdoob** [comment]
Then you should use Aggregate nodes for your workflow

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
