### ISSUE TITLE
Customize chart control timestamp

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#846]
Is it possible to customize the timestamp used in the thingsboard chart control ? For instance instead of using the "default" (?) time set by the tb-gateway when receiving the mqtt data, would be possible to use a timestamp sent by the external mqtt publisher together with the actual values in the mqtt json payload ?

**Comment by vparomskiy** [comment]
If I understand your requirement correctly, then you should set **ts** property during telemetry upload. If this field not empty, its value is used as a telemetry timestamp.

https://thingsboard.io/docs/reference/mqtt-api/#telemetry-upload-api

**Comment by abrasat** [comment]
Thx for your reply. The mqtt data to be displayed in the chart control is published from an embedded device to an external mqtt broker, and has its own topic name. The data gets to thingsboard over the tb-gateway, there is no "v1/devices/me/telemetry" topic used. Or is this topic used internally "behind the scenes" between tb-gateway and thingsboard service?

**Comment by vparomskiy** [comment]
It does not matter how mqtt data passed into the Thingsboard. If 'data' contains **ts** field, its value will be used as timestamp, otherwise, current server timestamp will be used. 

For example, you submit mqtt data to the Thingsboard. And Thingsboard current time is 144444444444.

If you will submit this JSON, then data timestamp will be 155555555555
{"ts":155555555555, "values":{"key":"value"}}

If you will submit this JSON, then data timestamp will be 144444444444
{"key":"value"}

**Comment by abrasat** [comment]
Is the thingsboard timestamp a unix timestamp (nr.seconds since 1.1.1970, UTC) ?
Is it possible to have the timestamp with milliseconds accuracy?

**Comment by vparomskiy** [comment]
Thingsboard timestamp is a unix timestamp with milliseconds.

**Comment by mp-loki** [comment]
I have just uploaded the tests which use the configuration with [timestamp](https://github.com/thingsboard/thingsboard-gateway/blob/master/src/test/resources/mqtt-config-timestamp.json). You can also use a formatter for your timestamp like described [here](https://github.com/thingsboard/thingsboard-gateway/blob/master/src/test/resources/mqtt-config-timestamp-format.json). The formatter string is actually a Java Date Fromat. Please check these out

**Comment by abrasat** [comment]
Great, thanks !
