### ISSUE TITLE
[Question] how to use css in cell content function

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8462]
how to use css in cell content function?
i need to use circle progress bar in entity table like this:
![progress-bar-type-1](https://user-images.githubusercontent.com/45573721/235633500-818ec9d5-4b4a-44c9-ae6b-c988960e3171.png)

**Comment by NistantriTech-Dhaval** [comment]
I made it static with 45% you can make it dynamic too
return '<div class="outerCircle" style="display: flex; justify-content: center; align-items: center; padding: 0; height: 50px; width: 50px; border-radius: 100%; background-image: conic-gradient(#94d3a2 0deg, #94d3a2 162deg, #D3D3D3 162deg)" ><div style="display: flex; justify-content: center; align-items: center; padding: 0; height: 40px; width: 40px; border-radius: 100%;background-color:white" >45%</div></div>'



![image](https://user-images.githubusercontent.com/127075794/235640052-1749e316-6e49-49ea-8c83-9dc174571cfe.png)

**Comment by NistantriTech-Dhaval** [comment]
@m3relec please mark it close if it worked for you

**Comment by devaskim** [comment]
@NistantriTech-Dhaval Thanks for sharing. Added your solution to [awesome-thingsboard](https://github.com/devaskim/awesome-thingsboard) collection

**Comment by GeirFrimann** [comment]
Could anyone please share how to make this function dynamic?

**Comment by devaskim** [comment]
@GeirFrimann just replate `45%` with you data key's data

**Comment by devaskim** [comment]
`conic-gradient(#94d3a2 0deg, #94d3a2 162deg, #D3D3D3 162deg)`
seems like `45% == 162 deg`

**Comment by ezeroldan24** [comment]
Good Friday, how are you? I've been trying several ideas to make it dynamic and add my telemetry so that the circle fills and changes the central value. But without success. Does anyone have the code to make it dynamic?

**Comment by ezeroldan24** [comment]
> Good Friday, how are you? I've been trying several ideas to make it dynamic and add my telemetry so that the circle fills and changes the central value. But without success. Does anyone have the code to make it dynamic?

I already managed to do it.. thanks
