### ISSUE TITLE
[Question] how to center content and title in entities table?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8471]
how to center content and title in row entities table?
![Capture](https://user-images.githubusercontent.com/45573721/235851167-051dd578-997f-491d-8b95-b12703e1bd81.PNG)

**Comment by devaskim** [comment]
Read about [CSS Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by ban2derlog** [comment]
Hi,
You can use custom Widget CSS feature to create a different view for widget.
You need to find proper `class` on Widget that you want change and add custom CSS for it.
Example:
In `Entities table` persist class `mat-sort-header-content` with can be used for customizing cells in table head row.
For cells with value you can use Widget CSS or `Cell style` function.

![image](https://user-images.githubusercontent.com/33271053/235956741-b40a6e96-78b3-4e86-b074-4d1411379446.png)
![image](https://user-images.githubusercontent.com/33271053/235957470-f8e5b674-30cd-42fb-9ecb-86f9201c94e7.png)

![image](https://user-images.githubusercontent.com/33271053/235957711-71ee71ab-ceb4-4c17-b39c-3c5e4b5e133c.png)

**Comment by m3relec** [comment]
thanks a lot
