### ISSUE TITLE
[Question] API to get Entity Groups of Added Device

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#8476]
**Component**
 * PE
 * Device Group

**Description**
This case only for TB PE since only this version has Group feature.
Let's say I have list of DEVICE Entity Groups : 
- Dev Group A
- Dev Group B
- Dev Group C
- Dev Group D

then I add my **DeviceA** to some group: **Dev Group A, B, and C**.

Here the question,
is there any API call to get list of Groups that DeviceA been added, so something like
`/api/DeviceA/addedGroup` 
and it will produce result list of object
`[{Dev group A}, {Dev group B}, {Dev group C}]` 

any API to do this?

**Comment by dhaval2017** [comment]
Are you looking for this API?

https://thingsboard.cloud/swagger-ui/#/entity-group-controller/getEntityGroupsForEntityUsingGET

**Comment by NistantriTech-Dhaval** [comment]
@evanderbird 
Are you looking for this API?

https://thingsboard.cloud/swagger-ui/#/entity-group-controller/getEntityGroupsForEntityUsingGET

**Comment by evanderbird** [comment]
hi @NistantriTech-Dhaval 
I just try this and yes this is what I'm looking for. 
Thank you.
