### ISSUE TITLE
[Question] User already present in database

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8479]
**Component**

  * Generic

**Description**
I'm trying to add a new user but ThingsBoard says that user already present in database.
I already re-check all registered user inside my Thingsboard but can't find it.

![image](https://user-images.githubusercontent.com/7483656/236194829-2b53cd2c-1361-4910-9f36-6b0963450ec7.png)

Is there anyone that can help about this problem ?

**Environment**

ThingsBoard: ThingsBoard Cloud Prototype

**Comment by NistantriTech-Dhaval** [comment]
please check if its available in another customer or tenant

**Comment by lstarke** [comment]
> or tena

I already did this but no chance to find this user.

**Comment by ashaforost** [comment]
Hi @lstarke 

Try the getUsers rest request to find a user: [Swagger UI](https://thingsboard.cloud/swagger-ui/#/user-controller/getUserUsersUsingGET)
If there's no such user in the list, consider the possibility that this user email is registered in a separate thingsboard.cloud account.

**Comment by lstarke** [comment]
> Hi @lstarke
> 
> Try the getUsers rest request to find a user: [Swagger UI](https://thingsboard.cloud/swagger-ui/#/user-controller/getUserUsersUsingGET) If there's no such user in the list, consider the possibility that this user email is registered in a separate thingsboard.cloud account.

Nothing.

{
    "data": [],
    "totalPages": 0,
    "totalElements": 0,
    "hasNext": false
}

**Comment by ashaforost** [comment]
In this case, you may try to find this user in the database.` select * from tb_user where email='<user_email>';`
If you do find it and want to delete it, make sure to create a db backup first.

**Comment by Vaibhav0216** [comment]
@ashaforost ,
how can I find user in data base?
