### ISSUE TITLE
Installing ThingsBoard using Docker(Linux or Mac OS) Error

### ISSUE THREAD

**Issue by UNIQUEXJ** [thingsboard/thingsboard#848]
On Mac Get https://registry-1.docker.io/v2/thingsboard/application/manifests/2.0.2: unauthorized: incorrect username or password

**Comment by untilbit** [comment]
After installing docker and docker-compose:
- You just need to **clone TB repository**.
- **cd thingsboard/docker/**
- **nano tb.env**  and change database to **cassandra** if you don't want to use **sql**
- **sudo docker-compose up**
