### ISSUE TITLE
[Bug] can't search alarm table for additional date keys (timeseries or attributes)

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#8480]
this is pretty anonying if you are using and working with alarms in thingsboard! @ashvayka 

method:

create an alarm table
add additional data keys
search for values of data keys

results:
search shows no results

search for alarm type or other default fields of alarm table
results:
search succeed

example:

![image](https://user-images.githubusercontent.com/31729091/236204407-6a45506a-60ff-4051-b30b-901bdaf49481.png)

search for alarm type - success:

![image](https://user-images.githubusercontent.com/31729091/236204492-f905cc7d-55a4-4017-a931-ee15e25d193c.png)

search for added data key - no results:

![image](https://user-images.githubusercontent.com/31729091/236204607-941771e4-173e-46e1-9724-3000e3d5fb17.png)

**Comment by myroslav-tb** [comment]
Hi @t0mZ4, The issue you described is not a bug but more of a feature request. After our dev team reviews it, we will let you know if it's going to be implemented.

**Comment by myroslav-tb** [comment]
Please follow up on the release notes to check if the feature is added to the Thingsboard.
