### ISSUE TITLE
[Question] Dashboard really slow after loading more than 20k telemetry points

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#8489]
**Component**

 * UI

**Description**
I am sending telemetries from one device every hour. The device has 10 different types of telemetries, e.g. pressure, temperature, humidity, light, etc.

I created a dashboard with 4 line charts in order to present the data. Each chart present the data in different ways, e.g. raw values, rate of change, average, difference from peaks, etc.

When I select 90 days in the dashboard time window (90 x 24 x 10 = 21.6k telemetries), the dashboard becomes really slow, to the point that I need to refresh the webpage because is impossible to navigate in it! In addition, I noticed that sometimes not all the data is loaded, maybe because of a timeout?

- Is this the normal behaviour of TB? or is there a way to optimise the loading of telemetries and make the dashboard run smoothly with a large dataset?
- Is the back-end or front-end making the dashboard slow? both?

I was expecting the UI to handle even larger datasets without lag problems....

**Environment**

 * OS:  macOS
 * ThingsBoard: Cloud version
 * Browser: Chrome Version 112.0.5615.49 (Official Build) (x86_64)

**Comment by Civilduino** [comment]
Is it possible to implement server-side rendering of charts in TB? e.g. this
https://apache.github.io/echarts-handbook/en/how-to/cross-platform/server/#

**Comment by trikimiki** [comment]
> Is this the normal behaviour of TB?

20k datapoints is a considerable amount of data, so it is a normal behavior.

> is there a way to optimise the loading of telemetries and make the dashboard run smoothly with a large dataset?

you can split dashboard into smaller dashboards, or create separate states for the same dashboard (https://thingsboard.io/docs/paas/user-guide/dashboards/#states)
alternatively, you could reduce timewindow, if you need all info to be displayed simultaneously.

> Is the back-end or front-end making the dashboard slow? both?

Yes, both. On backend side, you query a lot of data from the DB; on the client side, you draw charts on widgets.
You cannot really change anything server-side on Cloud, obviously.
On client side, you can use aggregation to reduce total datapoints displayed on the widget(s).
