### ISSUE TITLE
upgrading 2.0.2 when server.port is NOT 8080

### ISSUE THREAD

**Issue by marcozanghi** [thingsboard/thingsboard#849]
upgrading to 2.0.2 fails when the server.port is NOT setted to 8080

`
Connector configured to listen on port 8443 failed to start
ThingsBoard upgrade failed!
`
I have resolved by switching to 8080 during the upgrading.

**Comment by Karabiy** [comment]
make sure to merge the thingsboard.yml and thingsboard.conf with the old versions of the thingsboard.yml and the thingsboard.conf, so that you can apply the settings which you had with the previous version for the one you are upgrading to
