### ISSUE TITLE
Device credentials are stored by plaintext! This is a serious security issue.​[Bug] 

### ISSUE THREAD

**Issue by codeHui** [thingsboard/thingsboard#8490]
Please let me know will you fix this in the future versions? at lease stop using plaintext to store for new devices. 
We are going to use your PE version, only your team can change the source code.
Thanks very much.

**Comment by Ultrazombie** [comment]
Hello @codeHui 
If client_id isn't secure for you, please consider using another method of credentials, like x509.

**Comment by Ultrazombie** [comment]
Closed due to ianctivity
