### ISSUE TITLE
[Question] When can the upcoming release be released

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#8494]
Upcoming releases
Support of revocable API keys instead of JWT tokens for programmatic REST API access;
Improvements to IoT Gateway;
Ability to save dashboard parameters (time intervals, etc) per user;
JavaScript Device/Gateway SDK;
Single sign on;

**Comment by Ultrazombie** [comment]
3.5 has already been released,
Please update and enjoy with new features and design
also, you can read release notes to be familiar with the newest features:
CE - https://thingsboard.io/docs/reference/releases/
PE - https://thingsboard.io/docs/pe/reference/releases/

Best regards,
Artem.
