### ISSUE TITLE
[Question] how can sum all active deivces?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8497]
hello
how can sum all active and deactive devices?

**Comment by devaskim** [comment]
If you mean how to filter and count devices on dashboards, do 3 steps:
1. Use _Entity count_ datasource.
2. Create alias for all devices.
3. Create 2 filters: one for active and other for non-active devices.

![active](https://user-images.githubusercontent.com/86909129/236662492-126299cd-c20f-4095-abe9-b8334fdc60bd.jpg)

**Comment by m3relec** [comment]
thans @devaskim
