### ISSUE TITLE
Does anyone know how to get the entity view attributes to update?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8498]
* Rule Engine
 * Installation

I have creatred an entity view for all my device so I could share a device with mulitple customers. Everything works great except for the attributes.  Whenever the decice attributes changes the enitity view attributes does not change. For example I want to know when a device is offline.  When the device loses power the active attribute goes to flase, then I can make a widget for this on a dashboard. But the entity view attribute does not change at all.
Does anyone know how to get the entity view attributes to update?

This is how I have my root rule chain set up now
![image](https://user-images.githubusercontent.com/130080104/236734010-81450c6f-13ff-44f2-8f06-f2d94e659749.png)
![image](https://user-images.githubusercontent.com/130080104/236733281-81e0f757-2680-4741-9734-1ef39e4f64fd.png)
![image](https://user-images.githubusercontent.com/130080104/236733507-056d50d4-4ba9-4235-8c03-08a82cc76250.png)
![image](https://user-images.githubusercontent.com/130080104/236733574-6e3fe162-ba77-400f-9f04-1a5da9c54e6e.png)

**Comment by den1jkee** [comment]
Hi,
Entity View automatically copies specified attributes from Target Entity each time you save or update this entity view. For performance reasons, target entity attributes are not propagated to entity view on each attribute change. You can enable automatic propagation by configuring a “copy to view” rule node in your rule chain and linking “Post attributes” and “Attributes Updated” messages to the new rule node.

I`ve just tested it, and it works. Is that rule chain correct? Which device profile and Rule Chain this device are linked to?

Best regards,
Denys

**Comment by Buhaw85** [comment]
So when I create the entity view for the device the entity view is showing what the device is but as soon as the device attributes change the entity view attributes do not change with it.
I have everything in my root rule chain.  I followed the steps from thingsboard site but it just wont update the attributes.
