### ISSUE TITLE
Problem to issue RPC commands to devices in TB 2.0.x

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#850]
Since version 2.0.x I have problems to issue RPC commands to my devices.
Version 1.3.1 was working fine with the devices for months without problems.

In TB 2.0.x the device is successfully connected to the server via MQTT.
The subscription to "v1/devices/me/rpc/request/+" is reported as succesfully executed,
The device is successfully and continuously publishing attributes and telemetry messages to the server.
The SERVER attributes of the device are reporting an ongoing connection.
I do not do anything with the RPC capabilities within the rules engine.
I cannot find any useful hints in the Thingsboard log file about that problem.
My devices do not report any error.

Nevertheless, any RPC request from the server to the device is timing out.
It doesn't matter, if I issue the RPC command as a tenant or as a user owning the addressed device. Same problem.
I tried to use the RPC Debug Console widget without success. It reports that the device is not connectred.

Any hints, what might be the reason or where to look for more information? I am running out of ideas now...

Here is the result from a two way RPC request with the "POST /api/plugins/rpc/twoway/{deviceId}" command:
![image](https://user-images.githubusercontent.com/11454768/41097049-fd38b1a4-6a56-11e8-9467-de4602f33499.png)

**Comment by yuyihan666** [comment]
me too

**Comment by ashvayka** [comment]
Please attach your root rule chain for review. There was an update from 2.0.1 to 2.0.2 which introduce new rule processing node. It may break your install

**Comment by BatListener** [comment]
Thanks for taking care!
Here is the root rule chain as picture and JSON.
I have added a .txt extension to the json file in order to be able to upload it.
Please let me know if you need any other information.

![image](https://user-images.githubusercontent.com/11454768/41120783-df77b8c8-6a96-11e8-8436-92f0451f8fcb.png)

[root_rule_chain.json.txt](https://github.com/thingsboard/thingsboard/files/2081758/root_rule_chain.json.txt)

**Comment by ashvayka** [comment]
If this is version 2.0.2 you are missing the node that sends request to device



![missingnode](https://user-images.githubusercontent.com/5016373/41124518-e0e5cf42-6aaa-11e8-9e73-055ebecd1885.png)

**Comment by BatListener** [comment]
Yepp, that made it! Everything working again. Many thanks for the support!

I implemented the rule chains in version 2.0.0 (when the new node was not shown by default) and then upgraded to 2.0.1 and 2.0.2 according to the upgrade instructions.
A hint/warning in the upgrade instructions to extend the root rule chain for RPC could be useful for others. The sentence in the release notes of 2.0.1 was not alarming me sufficiently...

**Comment by ashvayka** [comment]
Yes, sorry for this. We will update instructions.

**Comment by ocsacesar** [comment]
I'm happy you solved your problem =) @BatListener.
At the moment I'm having the same problem that you faced out. Could you try to help me?

I have the latest version of thingsboard and it is deployed in a CentOs server at cloud. Here is my rule chains.

![screen shot 2018-07-19 at 20 17 03](https://user-images.githubusercontent.com/7918437/42975171-322f23ba-8b91-11e8-916e-96ec33412637.png)

**Comment by ravikarthi** [comment]
> If this is version 2.0.2 you are missing the node that sends request to device
> 
> ![missingnode](https://user-images.githubusercontent.com/5016373/41124518-e0e5cf42-6aaa-11e8-9e73-055ebecd1885.png)

Hello Ashvakya,
We are using TB 2.4.1.  In the single-node, the solution works well but which is not working in the cluster mode.
Please do the needful
Thanks in advance

**Comment by maghibus** [comment]
Hi all, I have the same problem (**In the single-node, the solution works well but which is not working in the cluster mode.**) with version 3.6.2 CE
