### ISSUE TITLE
[Question] Issue with Device Activity/Inactivity events

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard#8509]
**Component**

 * ThingsBoard Device
 * Rule Engine

**Description**
Hi,

On ThingsBoard cloud, we can easily create the Device inactivity/activity alarms. This alarm/event is generated on ThingsBoard cloud. In our case, we have a device that stops sending the data when there is a wire connectivity issue. This end device also points out the problem facing by the device.

Now, the issue with ThingsBoard cloud connectivity is, if we send the error information from end-device, the Cloud Inactivity is turned into Activity event. To avoid this, we can create a separate device at Cloud, but this would be the waste of resources.

Is it possible to use the same ThingsBoard Cloud Device for a same device that can fit this scenario?

Thanks

**Environment**
 * ThingsBoard Cloud

**Comment by ashvayka** [comment]
I believe you should use [gateway API](https://thingsboard.io/docs/reference/mqtt-api/) for such a case. Also, we now support [Sparkplug](https://thingsboard.io/docs/reference/mqtt-sparkplug-api/). The other option is to have your own "active" attribute.
