### ISSUE TITLE
JWT token

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#851]
Hi all, 

I am using windows 10 and want to enter the REST API, but therefore I need the JWT token.

I've followed the instructions and executed this in cmd:

curl -g -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d '{"username":"tenant@thingsboard.org", "password":"tenant"}' 'http://127.0.0.1:8080/api/auth/login'

It gives me this error:

{"status":401,"message":"Authentication failed","errorCode":10,"timestamp":1528400906101}

Anybody who knows what i'm doing wrong?

**Comment by caoyingde** [comment]
api key:Bearer xxTokenxxx

**Comment by jensvdh15** [comment]
The problem is I'm not able te get this token.

**Comment by vparomskiy** [comment]
provided code should return JWT token.
The possible reason is that you do not have a user with provided credentials.

Are you able to login to the Thingsboard UI using provided username\password?

**Comment by jensvdh15** [comment]
No, I can't login with 'tenant@thingsboard.org' and password 'tenant'. But when I use my own login and password in the code I get the same problem.

**Comment by vparomskiy** [comment]
It is a basic functionality and works as expected. You can inspect network requests in the browser console during login to find what what data is submitted to the Thingsboard server.  Authentication failed is returned when username can not be found.

**Comment by untilbit** [comment]
@jensvdh15  Here is a simple python script to get the token via API.

_**getToken.py**_
```
import sys
import requests
import json

def getToken():
    url = 'http://127.0.0.1:8080/api/auth/login'
    headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
    loginJSON = {'username': 'tenant@thingsboard.org', 'password': 'tenant'}
    tokenAuthResp = requests.post(url, headers=headers, json=loginJSON).json()
    token = tokenAuthResp['token']
    return token

print(getToken())
```

**Comment by jensvdh15** [comment]
Thank you very much! It works

**Comment by phuongnam0907** [comment]
> 
> 
> @jensvdh15 Here is a simple python script to get the token via API.
> 
> _**getToken.py**_
> 
> ```
> import sys
> import requests
> import json
> 
> def getToken():
>     url = 'http://127.0.0.1:8080/api/auth/login'
>     headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
>     loginJSON = {'username': 'tenant@thingsboard.org', 'password': 'tenant'}
>     tokenAuthResp = requests.post(url, headers=headers, json=loginJSON).json()
>     token = tokenAuthResp['token']
>     return token
> 
> print(getToken())
> ```

I use this script but it fails now

Traceback (most recent call last):
  File "<string>", line 12, in <module>
File "<string>", line 9, in getToken
KeyError: 'token'
>

**Comment by rescuehero** [comment]
If another guy runs into this problem under windows-cmd:
use " in the inner quotation marks and " in the outer quotation marks as follows:
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"username\":\"tenant@thingsboard.org\", \"password\":\"tenant\"}" "http://XXX:8080/api/auth/login"
