### ISSUE TITLE
Installation failed while using MySQL database

### ISSUE THREAD

**Issue by An-Bin** [thingsboard/thingsboard#8513]
Hello

System: ubantu,

Database: MySQL (5.7),

Version: ThingsBoard (v3.5.0),

The following error occurred during installation:
“ERROR o.t.s.ThingsboardInstallApplication - Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
”
[install.log](https://github.com/thingsboard/thingsboard/files/11437662/install.log)

**Comment by ashvayka** [comment]
MySQL is not supported and we use some functions that are specific to PostgreSQL

**Comment by An-Bin** [comment]
@ashvayka @ban2derlog 
Okay, the problem has been resolved. Thank you
