### ISSUE TITLE
Getting Bean Creation exception while installing Thingsboard

### ISSUE THREAD

**Issue by M0ulinamary** [thingsboard/thingsboard#8517]
**Component**

 * Installation
 

**Description**
When i run the thingsboard service install step, i get the below error.
Command: sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

Error:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ThingsBoard installation failed!

**Environment**

 * OS:  CentoS7
 * ThingsBoard: v3.5.0
 * Browser: Chrome

**Comment by M0ulinamary** [comment]
I am running it in a centos VM machine not in  IDEA. 

Also am using JDK 11 only.

But still am getting the below error.

Description
When i run the thingsboard service install step, i get the below error.
Command: sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

Error:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]

**Comment by YevhenBondarenko** [comment]
@M0ulinamary plz check your thingsboard and postgres configurations are correct (necessary check the password).

**Comment by ashvayka** [comment]
please attach full log of the startup for investigation

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
