### ISSUE TITLE
[Bug] Common settings on some control widgets don't work

### ISSUE THREAD

**Issue by ArtemDzhereleiko** [thingsboard/thingsboard#8538]
The issue with widgets: Switch control widget, Slide Toggle Control, Round switch

Steps to reproduce:
1. Dashboard - add the widget, for ex. Switch control widget
2. Edit widget - Advanced tab
3. Common settings section
4. change the name to any
5. enable the switch the Show on/off labels
6. save changes
7. changes don't display
8* but if enable checkbox the Initial value from the Value settings section, settings from the Common settings section start working

![image](https://github.com/thingsboard/thingsboard/assets/83352633/bffc4216-2221-4504-81d2-d66bd155513d)

**Comment by aadriii88** [comment]
a
