### ISSUE TITLE
problem about sending telemetry data

### ISSUE THREAD

**Issue by zhleicd** [thingsboard/thingsboard#854]
In order to publish telemetry data using MQTT protocol to TB server node, according to TB document guide, the supported data formats are key-value content in JSON, I tried to push a simple json file and a nested json file, but it doesn't work when sending nested json data(just like {"test":"whatever","crashPosition":{"test":"true"}}). I want to know whether nested json data can be send to a device, if so, how to do it.
Could anyone help me?

**Comment by jfmateos** [comment]
Please, could you give more details about option 2:
2. Convert telemetry upload message using Rule Engine into the correct format before it saved in the DB.

It seems that TB does not accept nested json in telemetry, so it never gets through the rule engine.

**Comment by ppoektos** [comment]
>     3. Use **Data Converters** feature from Thingsboard PE for converting incoming payload into the correct format.

Hi, can you describe what have to be done to accept such nested json?
```
{
     "app_id":"aaa",
     "dev_id":"sss",
     "hardware_serial":"aas",
     "port":2,
     "counter":1,
     "payload_raw":"zzzzz",
     "payload_fields":
     {"altitude":10,
     "latitude":11.3519,
     "longitude":11.9094}
    }
```
