### ISSUE TITLE
[Feature Request] [3.5] Alarm Page -> Filter -> Alarm type list should auto-complete / show list of alarms

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#8540]
In the new alarm page, the Filter -> Alarm type list should auto complete and offer list of existing alarms.

![image](https://github.com/thingsboard/thingsboard/assets/31729091/34e40141-62db-4dbd-b6d5-8c0f469a9d06)

**Comment by Ultrazombie** [comment]
Hello @t0mZ4,
This feature has been added.

**Comment by Ultrazombie** [comment]
https://github.com/thingsboard/thingsboard/pull/8825
