### ISSUE TITLE
[Bug][3.5] Can't edit custom widgets

### ISSUE THREAD

**Issue by JimmyPedersen** [thingsboard/thingsboard#8548]
**Describe the bug**
It's possible to open my custom widget library but when I try to edit any of them I get an empty page.
The menus to the left and top are still there but the editor textbox, settings and preview are not there, just empty space.
Worked fine in 3.4.2PE (Didn't try in 3.4.3PE or 3.4.4PE)

Also clicking the Widget Bundles breadcrumb at the top also doesn't work

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.5
  * Ubuntu server

**Your Client Environment**
**Desktop 

* OS: Windows 10
* Chrome
* Version 113.0.5672.93 (Officiell version) (64 bitar)

![image](https://github.com/thingsboard/thingsboard/assets/95076607/2ec36b98-671e-43fa-b8af-434e096e8bdc)

![image](https://github.com/thingsboard/thingsboard/assets/95076607/c81dfb00-672e-4924-ba7e-101f48f91a39)

**Comment by JimmyPedersen** [comment]
Another discovery: Creating a new widget just gives the same empty screen

**Comment by JimmyPedersen** [comment]
Seems to be related to specific widget. If I delete this everything works again.
Maybe related to update to Angular 15, will continue to investigate and close issue if reason found

**Comment by Ultrazombie** [comment]
Closed due to inactivity
