### ISSUE TITLE
Unable to build TB2.0.2 from source

### ISSUE THREAD

**Issue by zhleicd** [thingsboard/thingsboard#855]
I tried to build thingsboard-release-2.0.2 but failed when building TB Server UI, my environment is win7 and java8.
The log info is below, Could anybody give me help.

[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard Server UI 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ui ---
[INFO] Deleting C:\Users\IBM_ADMIN\git\thingsboardA\ui\target
[INFO]
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm)
 @ ui ---
[INFO] Installing node version v6.9.1
[INFO] Copying node binary from C:\Users\IBM_ADMIN\.m2\repository\com\github\eir
slett\node\6.9.1\node-6.9.1-windows-x64.exe to C:\Users\IBM_ADMIN\git\thingsboar
dA\ui\target\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 3.10.8
[INFO] Unpacking C:\Users\IBM_ADMIN\.m2\repository\com\github\eirslett\npm\3.10.
8\npm-3.10.8.tar.gz into C:\Users\IBM_ADMIN\git\thingsboardA\ui\target\node\node
_modules
[INFO] Installed npm locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
[INFO] Running 'npm install' in C:\Users\IBM_ADMIN\git\thingsboardA\ui
[WARNING] npm WARN deprecated angular-ui-router@0.3.2: This npm package 'angular
-ui-router' has been renamed to '@uirouter/angularjs'. Please update your packag
e.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/
[ERROR] npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': un
known revision or path not in the working tree.
[ERROR] npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisi
ons, like this:
[ERROR] npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<fi
le>...]'
[ERROR] npm ERR! git rev-list -n1 master:
[ERROR] npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': un
known revision or path not in the working tree.
[ERROR] npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisi
ons, like this:
[ERROR] npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<fi
le>...]'
[ERROR] npm ERR! git rev-list -n1 master:
[ERROR] npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': un
known revision or path not in the working tree.
[ERROR] npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisi
ons, like this:
[ERROR] npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<fi
le>...]'
[ERROR] npm ERR! git rev-list -n1 master:
[ERROR] npm ERR! git rev-list -n1 0.7.5: fatal: ambiguous argument '0.7.5': unkn
own revision or path not in the working tree.
[ERROR] npm ERR! git rev-list -n1 0.7.5: Use '--' to separate paths from revisio
ns, like this:
[ERROR] npm ERR! git rev-list -n1 0.7.5: 'git <command> [<revision>...] -- [<fil
e>...]'
[ERROR] npm ERR! git rev-list -n1 0.7.5:
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "C:\\Users\\IBM_ADMIN\\git\\thingsboardA\\ui\\target\\node
\\node.exe" "C:\\Users\\IBM_ADMIN\\git\\thingsboardA\\ui\\target\\node\\node_mod
ules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.1
[ERROR] npm ERR! npm  v3.10.8
[ERROR] npm ERR! code 128
[ERROR]
[ERROR] npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 master
[ERROR] npm ERR! fatal: ambiguous argument 'master': unknown revision or path no
t in the working tree.
[ERROR] npm ERR! Use '--' to separate paths from revisions, like this:
[ERROR] npm ERR! 'git <command> [<revision>...] -- [<file>...]'
[ERROR] npm ERR!
[ERROR] npm ERR!
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\Users\IBM_ADMIN\git\thingsboardA\ui\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  6.089 s]
[INFO] Netty MQTT Client .................................. SUCCESS [ 11.748 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.215 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 12.370 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  7.425 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  4.641 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 26.305 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.140 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  3.888 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 17.153 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.089 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  1.783 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  5.625 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  2.834 s]
[INFO] Thingsboard Server UI .............................. FAILURE [ 42.479 s]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:24 min
[INFO] Finished at: 2018-06-10T18:52:47+08:00
[INFO] Final Memory: 83M/808M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm
 (npm install) on project ui: Failed to run task: 'npm install' failed. (error c
ode 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui

**Comment by sunmountain** [comment]
Have you tried to clean up / remove your .m2 cache?
Both nodejs and npm are looking somewhat outdated.

**Comment by assofour** [comment]
I have some issue, any solution?

**Comment by alexsmartens** [comment]
I'm having a similar problem:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task
```
Any solution?

**Comment by CooL16** [comment]
To resolve the issue you have to install nodejs and npm on your PC.
