### ISSUE TITLE
[Question] InactivityTimeout does not switch active server-side-attribute to false

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8550]
**Component**

 * Generic

**Description**

InactivityTimeout does not switch active server-side-attribute to false in only one device.

![image](https://github.com/thingsboard/thingsboard/assets/7483656/e6868de6-b29a-45f4-b21f-b73bb28c1b30)

Any idea why this happening

**Environment**Environment

ThingsBoard: ThingsBoard Cloud Prototype

**Comment by LukaszDuss** [comment]
> Hi, Have you manually changed this attribute in past? If yes, then this can cause such behavior.

Is it isolated to the device that was changed alone or can it affect event generation of other devices as well?

**Comment by LukaszDuss** [comment]
> @LukaszDuss this can affect only particular device. ACTIVE attribute is mandatory server check that mustn't be changed by User or during Rule Chain workflow. After switching this manually, you can receive almost any behavior with it in the future - random changes between boolean states\ignoring inactive timeout\ignoring trigger to become active after receiving telemetry or responses.

Thanks, I wasn't aware of this... That explains my recent problems ALOT. 
I guess only fix for that would be adding device again?

**Comment by mykhailokornieiev** [comment]
Hi @LukaszDuss 
Yes, your guess is correct. 
I close this ticket due to inactivity
