### ISSUE TITLE
[Bug] UI - Translation issues after 3.5 update

### ISSUE THREAD

**Issue by clemjrt** [thingsboard/thingsboard#8552]
After updating Thingsboard PE to 3.5 version, we encouter a lot of translation issues. Some examples : 

![image](https://github.com/thingsboard/thingsboard/assets/104388936/b54bc6c8-12b7-4a25-9f61-678e69193ef5)

![image](https://github.com/thingsboard/thingsboard/assets/104388936/edd15218-400d-461b-8f76-ee49be3773c4)

![image](https://github.com/thingsboard/thingsboard/assets/104388936/ff803613-3b29-42b0-8f15-812d58d3efb4)

  * ThingsBoard PE Version  3.5
  * OS Debian

Is there other people having the same UI issue  ?

**Comment by clemjrt** [comment]
Problem solved by waiting end of background tasks.

**Comment by Butanding** [comment]
@clemjrt how long did it take you to finish "background tasks"
we got the same issue here and it is not reloading somehow.
