### ISSUE TITLE
[Question] How to fetch credentials to MQTT rule node?

### ISSUE THREAD

**Issue by netbc** [thingsboard/thingsboard#8553]
**Component**

 * Rule Engine

**Description**
Is there a way to fetch credentials (Username) to the MQTT node from preceding rule node?

**Environment**

 * OS:  docker
 * ThingsBoard: 3.4.4PE

**Comment by ban2derlog** [comment]
hi,
unfortunately, you can't.
you can use `data` and `metadata` only for topics formation.

as workaround you can use different MQTT nodes with different credentials, but this can be applied only if you use not much quantity of Users on your broker.

**Comment by netbc** [comment]
Thank you.
