### ISSUE TITLE
[Question] Activity event from rule chain?

### ISSUE THREAD

**Issue by netbc** [thingsboard/thingsboard#8554]
**Component**

 * Rule Engine

**Description**
Is it possible to generate an activity event for the device using a rule chain? We are using a gateway to receive device telemetry and storing telemetry data by changing originator from a gateway to device in the rule chain. With this approach activity events are not created and we are looking ways to generate activity events by the rule chain instead.

**Environment**

 * OS:  docker
 * ThingsBoard: 3.4.4PE
 * Browser: name and version

**Comment by devaskim** [comment]
Did you try to use official [MQTT gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/)? It supports what you need out of the box.

**Comment by netbc** [comment]
I did try MQTT gateway API but it will not work using Thingsboard MQTT node in the rule chain. The MQTT gateway API expects two messages: connect to the topic and publish telemetry/attribute within one session. https://github.com/thingsboard/thingsboard/issues/5632#issuecomment-981551159
It is not possible to send two messages within one session using MQTT node in the rule chain.

**Comment by devaskim** [comment]
So you are pushing data from one TB instance to another?

**Comment by devaskim** [comment]
> Did you try to use official [MQTT gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/)? It supports what you need out of the box.

I meant using gateway API to push initial telemetry, not after it is delivered to TB. Thus I have another question, how do you get telemetry?

> It is not possible to send two messages within one session using MQTT node in the rule chain.

You could push telemetry via REST API, but it is pure performance solution and you need access token for each device

**Comment by netbc** [comment]
We get telemetry through another device, change the originator in the rule chain and save the telemetry. 

Yes, now we are using REST API to push attributes to this device and to get activity event for the device.
