### ISSUE TITLE
How to backup thingsboard entire database (dashboard, devices, assets, rules etc) and how to restore

### ISSUE THREAD

**Issue by avipala** [thingsboard/thingsboard#8563]
I saw this: sudo -Hiu postgres pg_dump thingsboard > thingsboard.sql.bak
To make backup
But none of the instructions for restore work

Please describe all the procedure
--

**Comment by Backdraft007** [comment]
Well,
have a look in the manual of postgres. :)
https://www.postgresql.org/docs/current/backup-dump.html

**Comment by ashvayka** [comment]
> Well, have a look in the manual of postgres. :) https://www.postgresql.org/docs/current/backup-dump.html

This is correct if you use PostgreSQL only. You need to backup Cassandra as well if you use it. No other backups are needed (except thingsboard.conf). Evry ThingsBoard entity is stored in the database.
