### ISSUE TITLE
[Question] Thingsboard : How to access defined server attributes in rule chain to be used in script?

### ISSUE THREAD

**Issue by A10AIO** [thingsboard/thingsboard#8566]
* Rule Engine

**Description**
I would like to use a server attribute called "SO2_H_SP" already defined in the device [_Fig 1_] to be used in a rule chain script node to check a condition to compare if setpoint has been reached or no in comparison to a telemetry value called "SO2" [_Fig 2_]. The setpoint value "SO2_H_SP" is variable and can be changed by user in UI. [_Fig 3_]

I've tried originator nodes but always get NULL values.

Please help .. 

**Fig 1**
![image](https://github.com/thingsboard/thingsboard/assets/133926103/653be58e-d4d2-4d9f-a9b9-2c0636cde4c5)

**Fig 2**
![image](https://github.com/thingsboard/thingsboard/assets/133926103/8c1203d7-f4f6-402f-966d-9db53df37826)

**Fig 3**
![image](https://github.com/thingsboard/thingsboard/assets/133926103/365925f7-20e7-4c6b-b64d-d65c5603a828)

**Environment**
 * OS:  Windows 10
 * ThingsBoard: 3.4.3
 * Browser: Firefox

**Comment by devdoob** [comment]
Which originator are you using for loading that server attribute?

**Comment by A10AIO** [comment]
I tried originator attributes ..

![image](https://github.com/thingsboard/thingsboard/assets/133926103/29d57d5c-5d2c-4f3a-8574-997aec9c0a3b)

**Comment by LukaszDuss** [comment]
Hi, is this right?
-In fig1 there is only SO_H_SP and O2_H_SP but in fig4 you are trying to get SO2_H_SP 
-In last screenshot it seems like you didnt choose "fetch into:"

**Comment by Tomi05-k** [comment]
Hello, I am facing the same problem. I want to read a value from the server properties and subtract it from a telemetry. 
How can I access the attribute?

Greetings Tom
