### ISSUE TITLE
[Bug] After upgrade to v3.5.0 CE version, dashboards have websocket errors: "A server must not mask any frames that it sends to the client."

### ISSUE THREAD

**Issue by jmicans** [thingsboard/thingsboard#8579]
**Describe the bug**
I just upgraded Thingsboard CE version from v3.4.4 to v3.5.0 

After this update, my dashboards stopped working properly and I see errors in browser console: 
vendor.c140118c2462d60d.js:1 WebSocket connection to 'wss://my-thingsboard.address.co/api/ws/plugins/telemetry?token=<token>' failed: A server must not mask any frames that it sends to the client.

Widgets show loading indicator but no data. Asset names and device labels may contain UTF8 characters 

**Your Server Environment**
* own setup
  * ThingsBoard Version v3.5.0
  * Ubuntu 20.04.5 LTS 

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows 10 Enterprise
* Browser: Chrome
* Version 113.0.5672.127 (Official Build) (64-bit)
* Errors also exist on Firefox 113.0.1 (64-bit)

**Expected behavior**
Dashboards receive data and show widgets

Error notification in Firefow browser
![image](https://github.com/thingsboard/thingsboard/assets/35926239/9fd80d6e-e739-410c-aae1-3bff2e812855)

Error from Chrome console 
![image](https://github.com/thingsboard/thingsboard/assets/35926239/8cce5699-9fd6-4b92-8804-ab84e6aecb05)

**Comment by jmicans** [comment]
Update: the error happens when dashboard alias is an asset, that is expanded as multiple entities. Alias defined like this: 
![image](https://github.com/thingsboard/thingsboard/assets/35926239/b1a45071-8a25-42ed-8847-a64ddee4b75f)
After renaming asset and device type to exclude special lv language characters, there was still one error in console, but not errors in infinite loop anymore.

**Comment by jmicans** [comment]
Maybe you can advise on steps how to downgrade thingsboard version from v3.5.0 to v3.4.4?

**Comment by ashvayka** [comment]
> Maybe you can advise on steps on how to downgrade thingsboard version from v3.5.0 to v3.4.4?

Just restore the DB to the state before the backup. We will fix this ASAP and include to 3.5.1

**Comment by ashvayka** [comment]
Is this a custom code? I have never seen error messages like "support_id: *" before?

**Comment by jmicans** [comment]
No, it's pure thingsboard code, no fork, no custom stuff added. The error message differs in chrome and in firefox. The `support_id` is just seen in firefox, but chorme shows that `A server must not mask any frames that it sends to the client.` error
I don't see any errors in thingsboard logs. Probably server sends the websocket message, but each browser rejects it with different reason.

**Comment by jmicans** [comment]
Sorry, turns out the problem was not a thingsboard fault but related to load balancer and firewall settings that was changed around the same time when version was upgraded.
