### ISSUE TITLE
[Question] Two instances PE License key for  high-availability deployment?

### ISSUE THREAD

**Issue by star7128** [thingsboard/thingsboard#8582]
**Component**

 * AWS, Azure, Minikube
 * ThingsBoard: 3.5

**Comment by ban2derlog** [comment]
hi,
yes - for PE you need license for each ThingsBoard instance/pod/container for `monolith` and `node` deployment types.
but keep in mind, that if you need to split load by using MSA with `tb-core` and `tb-rule-engine` pod\containers separately - then you will need license for each `tb-core` and `tb-rule-engine`

**Comment by star7128** [comment]
@ban2derlog thanks！

My initial idea is to easy run docker-compose with 2 TB container (monolithic) instances but there are some inconsistent issues in websocket. Can anyone instruct me how to resolve this issue or it is a known limitation?

TB1 (running container) \    Kafka
                                            + PostgreSQL+ Cassandra
TB2 (running container) /

So I validated microservices with docker-compose cluster. As your saying, there are tb-core1, tb-core2, rule engine 1, rule engine 2, etc running up independently. So there are 4 instances License key at least. It is definitely not what we want.

Finally, we intend to deploy a TB cluster but high availability to reduce downtime when any TB upgrade or single node failure in TB app node.

Try to find a balance based TCO, performance and high availability.

**Comment by ban2derlog** [comment]
Hi,
During upgrade procedure - you will have some downtime, because almost every new version made changes in PostgreSQL database.
As example of Docker Compose HA cluster, you can use this doc:
https://github.com/thingsboard/thingsboard-pe-docker-compose/blob/master/advanced/docker-compose.yml
Here persist full MSA approach, but you can simplify it to 2 monolith.
Addionally, in docs there is example of haproxy configuration for load balancing.

Which exact issue do you have with websocket when you use 2 TB nodes?

**Comment by star7128** [comment]
> Hi,
> During upgrade procedure - you will have some downtime, because almost every new version made changes in PostgreSQL database.
> As example of Docker Compose HA cluster, you can use this doc:
> https://github.com/thingsboard/thingsboard-pe-docker-compose/blob/master/advanced/docker-compose.yml
> Here persist full MSA approach, but you can simplify it to 2 monolith.
> Addionally, in docs there is example of haproxy configuration for load balancing.
> 
> Which exact issue do you have with websocket when you use 2 TB nodes?

When we run up 2 TB containers with the image thingsboard/tb-pe:3.5.0PE, we see websocket update is inconsistent with queue service. However, if we run tb-pe-node (or tb-node) and simplify it to 2 monolith (service type), it works like a charm as we expected : )

**Comment by ban2derlog** [comment]
Yes, `tb-pe` was created not for MSA approach - it contains all services in it and main purpose is to use it as standalone container.
`tb-pe-node` is more lightweight version without Wer Report, Web UI and other - so you have done all absolutely right when change deployment to `tb-pe-node` image.
