### ISSUE TITLE
[Bug] row style function change font problem

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8588]
hi
after upgrade to v3.5 CE row style font change to default font and cannot be change this.
i used this code:
```
var result = {};
result.height = "100px";
result["font-family"] = "Shabnam";
result["font-weight"] = "bold";
result.padding = "100px";
result["font-size"] = '30px';

return result;
```

**Comment by den1jkee** [comment]
Greetings,
This bug was fixed in the release of ThingsBoard 3.6 in the past week.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

Best regards,
Denys
