### ISSUE TITLE
What are the factors affecting JavaScript functions in API Usage?

### ISSUE THREAD

**Issue by A10AIO** [thingsboard/thingsboard#8589]
I would like to ask regarding the factors affecting JavaScript functions.

I have a telemetry that is updating every 10 seconds, alongside 1 rule chain, 1 integration, 1 device with 18 datapoints, and 1 dashboard with 7 states.
As per below figure, is this value normal? I mean to have around 500K JavaScript functions executions in only 48 hours. 

![image](https://github.com/thingsboard/thingsboard/assets/133926103/42c1ccd5-e80a-4edf-ad74-a3a324c525b5)

Also, how can I reduce this number? Any suggestions?

**Comment by ashvayka** [comment]
Dashboards are not affecting the JS executions. JS executions are the number of executions of a converter and any rule node with JS function inside (script node, for example). We count each execution separately. But we do not care about a number of data points in the message.

**Comment by devdoob** [comment]
@ashvayka what about TBEL scripts? Are excluded from these counters?
