### ISSUE TITLE
can not be connected to a gateway device 

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#859]
2.0.2 {"device":"GateWayDevice A"} Entities connected to a gateway type are disconnected and can not be connected to a gateway device and were previously normal when using version 1.4. In practice, our gateway entity needs to collect data as ordinary device entities. How do we solve this problem?

details: https://github.com/thingsboard/thingsboard/issues/839

**Comment by ban2derlog** [comment]
Hi, does this issue persist on latest ThingsBoard version?
