### ISSUE TITLE
[Question] how to sum specific attribute of all device 

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8590]
hello.
i need to add specific attribute of all device and show on widget.
How should I do?

**Comment by devaskim** [comment]
As I know, it is only possible with custom widget. Clone (Save As button), for example, HTML Value Card or Simple Card widget from Widget Bundles -> Cards and update `onDataUpdated()` method to calculate sum.

**Comment by m3relec** [comment]
thanks @devaskim 
is there any way to sum telemetry data of all device in rule chain?

**Comment by devaskim** [comment]
I guess you will face with synchronization issues using rule chains. For example, Device 1 sent humidity telemetry twice, meanwhile Device 2 did it only once. So it is unclear which values rule chain need to sum in this case.

**Comment by m3relec** [comment]
Yes, the same problem occurs.
Is it possible that in the rule chain, the attributes of all the devices are added together in a schedule, for example, once every hour?

**Comment by devaskim** [comment]
Maybe it is possible, but I don't know how.

It you need a sum only on UI, in my opinion, it would be easier to implement custom widget.

**Comment by m3relec** [comment]
thanks a lot @devaskim
