### ISSUE TITLE
[Question] How to reset the "cache for latest value" of "Calculate Delta node"

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#8592]
**Component**

 * Rule Engine

**Description**
How to reset the "cache for latest value" of "Calculate Delta node" 
I want a way on how to reset the cache value of latest value of time series data that is used for Calculate delta node. 
Currently even if we delete the time series data from the device, the latest value cached is retained and creates errors. 

Current work around is to delete the device and recreate a new device and start re-uploading the telemetry data. 

**Environment**
 * OS:  Ubuntu 
 * ThingsBoard: 3.4

**Comment by myroslav-tb** [comment]
Hi @sudhirbits, unfortunately, there is no option to clean the cache of the "Calculate Delta node". The cache is stored in memory, and the only way to clean it would be to restart Thingsboard or recreate the node. You can build your own custom rule chain for calculating delta, which will allow you to clean the cache.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
