### ISSUE TITLE
[Question] TB PE: Login Timeout every few months, stuck?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#8593]
* Generic

**Description**
Thingsboard PE login page.
![LoginTBPE_HAPROXY](https://github.com/thingsboard/thingsboard/assets/49442805/49d9d4b9-b1bb-4f88-b8b0-dbe382203d83)

HAproxy is giving me this 504 time out problem every few months, so nobody can log in.
But the sensor data keeps being collected over MQTT, so some part is still working.

When I just restart the thingsboard service again, it's fixed.

Any idea what could be the problem here?
Logs don't really show anything special.

**Environment**

 * OS:  Ubuntu 20.04 LTS
 * ThingsBoard PE: 3.3.3   
 * HAProxy: 2.4.12

**Comment by ViacheslavKlimov** [comment]
Please provide your HAProxy configuration and describe the setup in more detail

**Comment by KenSense** [comment]
I don't think the HAProxy has something to do with it since I don't need to restart it, I only restart the Thingsboard service to make it work again.

HAproxy is configured to do the TLS part for HTTPS and is contacting thingsboard via HTTP on the same server.
Sensor MQTT communication is on port 8883 configured in thingsboard.
Since the problem only happens after a long time I don't think it will be something obvious.
So hoping that someone here had a similar problem before.

**Comment by GabrielMarconS** [comment]
Hey, any luck finding out what was the problem?

**Comment by KenSense** [comment]
We upgraded to 3.5.1 not sure if it's fixed but haven't had the problem in a while (since July).
