### ISSUE TITLE
[Question] Assigning default dashboard to user after creation

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#8599]
Is there a way (rule engine for example), to automatically assign a user (after it's creation or all user of a customer) to a default dashboard with "Always fullscreen" set ?

**Comment by devaskim** [comment]
Here is [rule chain](https://github.com/devaskim/awesome-thingsboard/tree/main/chain/assign-dashboard-to-new-user) for this purpose. The main idea is to add 4 fields to `additionalInfo` of user enitity
```
msg.additionalInfo['defaultDashboardId'] = metadata.dashboard;
msg.additionalInfo['homeDashboardId'] = metadata.dashboard;
msg.additionalInfo['homeDashboardHideToolbar'] = true;
msg.additionalInfo['defaultDashboardFullscreen'] = true;
```

Also you could do the same via TB UI. 
![dashboard](https://github.com/thingsboard/thingsboard/assets/86909129/7fe525fd-0af4-4129-84c4-927608d55960)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
