### ISSUE TITLE
Alarm to websocket

### ISSUE THREAD

**Issue by ihevcuk** [thingsboard/thingsboard#860]
Is it possible to receive alarms on websocket endpoint? Here is an example with subscribing to device telemetry https://thingsboard.io/docs/user-guide/telemetry. I assume I should change eventType to ALARM? Could you provide example of subscribing to alarm event like you provided for telemetry:

```
       var object = {
                  tsSubCmds: [
                        {
                            entityType: "DEVICE",
                            entityId: entityId,
                            scope: "LATEST_TELEMETRY",
                            cmdId: 10
                        }
                    ],
                    historyCmds: [],
                    attrSubCmds: []
                };
```

**Comment by vparomskiy** [comment]
Alarms are available only via REST API.

You can use this API for fetching alarms by type and entity Id.
https://demo.thingsboard.io/swagger-ui.html#!/alarm-controller/getAlarmsUsingGET
