### ISSUE TITLE
[Bug] CBS Token Timeouts using Azure Service Bus  

### ISSUE THREAD

**Issue by mikepetersyn** [thingsboard/thingsboard#8601]
**Describe the bug**

When using the Azure Service Bus as ThingsBoard Queue Service, it sometimes happens that the connection from the ThingsBoard server to the Azure Service Bus is interrupted and not restored, even after several hours. The only solution is to restart the ThingsBoard server.

We tracked down the time of the disconnection using Service Bus monitoring and then isolated the following error in the tb-node container logs:

"Will retry sending CBS token for amqp://[...].servicebus.windows.net/[...] after 5 seconds."

A screenshot of the logfile shows that the transmission of the token fails repeatedly, so there is a kind of error loop where the CBS token timeout error occurs. In the source code of the azure-sdk-for-java we have seen that there is also an error message for failed authentications. So this is not a case of failed authentication. Rather, for some reason the service bus can no longer be reached and the MessagingFactory gets stuck in the exception loop.

This error is already published as an issue on the GitHub page of [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/issues/12044) in connection with the IoT Hub. Here the issue has been closed, with a note that the bug has been fixed. 

However, apparently the bug still occurs when using the SDK. Is it possible that a dependency is outdated or is it possible to catch the error within ThingsBoard if it originates from the SDK?

**Your Server Environment**

* own setup
  * OpenShift Cluster Deployment
  * ThingsBoard Version 3.4.4
  * Azure Service Bus Standard Tier (public internet access and Shared Access Signatures (SAS) authentication)

**Expected behavior**
After a connection failure, it is expected to be restored automatically. 

**Screenshots**
![cbs-token-timeouts](https://github.com/thingsboard/thingsboard/assets/56337598/2acf561b-9cbd-40f0-bc1b-d1d30e6b9f8a)

**Comment by ashvayka** [comment]
@dashevchenko

**Comment by dashevchenko** [comment]
Updated version of azure-sdk-for-java to latest: https://github.com/thingsboard/thingsboard/pull/8676. Should be fixed in 3.5.2.
