### ISSUE TITLE
[Question]  Inquiry about Establishing Relations between Alarms in Thingsboard IoT Platform

### ISSUE THREAD

**Issue by ketaeishi** [thingsboard/thingsboard#8603]
**Description**
Dear Thingsboard Support Team,

I am reaching out to inquire about a specific feature within the Thingsboard IoT platform regarding the establishment of relations between alarms. I have been utilizing Thingsboard for my IoT projects and I am thoroughly impressed with its capabilities so far.

In my current implementation, I have been leveraging the alarm functionality within Thingsboard to monitor and manage various events and anomalies occurring in my IoT system. However, as my system complexity grows, I have encountered a need to establish relations between alarms.

My requirement is to consider an alarm as a ticket, where multiple alarms can be linked or associated with a particular ticket. This capability would greatly enhance my ability to manage and track related alarms as a cohesive unit, enabling me to analyze and address issues more effectively.

Could you kindly assist me by providing information on whether Thingsboard supports the establishment of relations between alarms?

Thank you very much for your attention to this inquiry. I look forward to your response and further guidance on this matter. Please feel free to reach out to me if you require any additional information or clarification.

**Environment**
 * OS:  Debian
 * ThingsBoard: PE

**Comment by devaskim** [comment]
If you meant Thingsboard's Relation feature, you could try to create relation between alarms through [REST API](https://demo.thingsboard.io/swagger-ui/#/entity-relation-controller/saveRelationUsingPOST)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
