### ISSUE TITLE
After Updating From 3.4.4 to 3.5 UI broke

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#8608]
After the update some elements of the ui are not right. 
Its probably a problem on my end.
I have added a picture below.
How can I fix this?

 
**Screenshots**
![Ekran görüntüsü 2023-05-23 134919](https://github.com/thingsboard/thingsboard/assets/82094220/8ef401e7-6303-414d-92d6-c301e13f2137)

**Comment by ban2derlog** [comment]
Hi,
Please, clear browser cache.
This will fix this.

**Comment by ban2derlog** [comment]
Hi,
Please, clear browser cache.
This will fix this.

**Comment by ashvayka** [comment]
We will improve to make sure you don't need to clear the cache in future releases.

**Comment by inanlia** [comment]
It worked thanks.
