### ISSUE TITLE
After update to 3.5 all integrations broke. [Bug] 

### ISSUE THREAD

**Issue by arnonzamir** [thingsboard/thingsboard#8609]
**Describe the bug**
After the update to v3.5 all the integrations we use (all HTTP) stopped functioning and data from all devices stopped coming in. This is a production environment with 100th of devices. 

**Your Server Environment**
* cloud.thingsboard.io

**Your Client Environment**
impacts all client environments. 

**Your Device**

* Connectivity
  * HTTP

**Comment by ashvayka** [comment]
is this about cloud.thingsboard.io or thingsboard.cloud?

**Comment by arnonzamir** [comment]
my endpoint url is on thingsboard.cloud



                    Arnon Zamir

TEDx  <https://www.youtube.com/watch?v=IrFvq5B4Dwg> | LinkedIn
<http://il.linkedin.com/in/arnonzamir>

**Comment by Civilduino** [comment]
I have the same problem! None of my integrations are working since 10:00 CET.

TB Cloud version.

**Comment by ashvayka** [comment]
Integrations are back now. We made a mistake during the deployment of the new release. The topic for data processing between the integration executor and tb-core was unsynchronized. Now it is back to normal. Very sorry about this issue. We are going to automate the check for such issues so it will not happen again.
