### ISSUE TITLE
[Bug] after CE update to 3.5, bad UI  in firefox (but ok in Edge and Chrome)

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#8612]
After update from 3.4.1 -> 3.4.2 -> 3.4.3 -> 3.4.4 -> 3.5 I got some bug in the UI (see image)
But the problem is only in firefox
<img width="439" alt="WrongUIDropdown" src="https://github.com/thingsboard/thingsboard/assets/49442805/b133d3df-51a7-4168-866e-6f04154d451c">

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard CE 3.5 /  3.4.1
  * Ubuntu server

**Your Client Environment**

**Desktop:**
* OS: Windows 10
* Firefox 113.0.1 64bit

**To Reproduce**
I have another TB CE 3.5 running and it's working fine in the same firefox browser.
So not sure what is going on:
Server 1 CE 3.5 : Edge ok, Firefox bad (update from 3.4.1)
Server 2 CE 3.5: Edge ok, Firefox ok (update from 3.4.4)

So anyone an idea what is the reason could be and how I can fix this?

**Comment by KenSense** [comment]
OK, seemed to fixed without changing anything, must have been some caching problem I guess.

**Comment by MbBures** [comment]
I had same issue, comment is for detailed informations for others.
Server own Setup:
- HW/OS: Raspi OS Bullseye on RPI 4B
- ThingsBoard CE 3.2.1/ 3.6 / 3.6.1

Client Firefox 121/ Windows 10, acces from outside side router via NAT

I seen issue after Server clean install with TB CE 3.6.1 on clean OS, keeping same IP settings. 
Worked good from another web browser or another IP to Server.
Cache and cookies erase solved problem.
