### ISSUE TITLE
[HELP] How to process each object in an array of JSON objects (each is a sensor data)?

### ISSUE THREAD

**Issue by yjfoo** [thingsboard/thingsboard#8617]
I have a LoRaWAN gateway that aggregates some sensor data and sends out to TB cloud (PE).
The data can arrive to TB in an array of JSON objects (different sensor data). Like below eg
[{
     key1: value1,
     key11: value11
}, 
{
     key2: value2,
     key22:value22
}]

How do I loop through all the JSON objects and process/save them?

ThingsBoard: Thingsboard PE Cloud
Browser: Chrome

**Comment by devaskim** [comment]
[Walk through an array](https://github.com/thingsboard/thingsboard/issues/6594#issuecomment-1141037479)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
