### ISSUE TITLE
[Question] How to align and margin widget title?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8618]
How to align and margin widget title?

**Comment by devaskim** [comment]
You can override widget CSS classes in widget's _Settings_ -> Widget Style -> Advanced Settings -> Widget CSS. 
So just find CSS class of the widget title with the help of browser's DevTools and "patched" it.

**Note**: sometimes you need to add CSS `!import` to the end of each CSS rule to apply them for your widget. For example, `font-weight: 600 !important;`

**Comment by m3relec** [comment]
It was a very good and important guide @devaskim 
thank you
