### ISSUE TITLE
[Question]  how can i create backup for the thingsboard database  but in docker 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8621]
**Component**

 * Installation
 * Generic

**Description**
i am trying to save and store my thingsboard db to secure my progress but i am not able to store/download my database , i am currently using docker image  which is => [thingsboard/tb-postgres](https://hub.docker.com/r/thingsboard/tb-postgres/)

**Environment**

 * OS:  ubuntu 
 * ThingsBoard: latest

**Comment by devaskim** [comment]
In my opinion, it is better to use Docker volume feature to map TB database folder living in container to a folder on your local filesystem.

Now you could try to enter into running container, stop TB service and [copy database](https://docs.docker.com/engine/reference/commandline/cp/) to the local filesystem.

**Comment by securitylamb** [comment]
> Hi, You can make a backup in a local dir with docker exec command: `sudo docker exec -i <container_id_or_name> pg_dump --username thingsboard -d thingsboard > /path/to/dir/backup/thingsboard_backup.sql`
> 
> Thanks.
> 
> Best regards, Denys

**Comment by den1jkee** [comment]
hi @securitylamb ,
You need to declare the correct <container_name> or <ID_container>. You can see it when you execute `docker ps` command
For example:
![image](https://github.com/thingsboard/thingsboard/assets/113901187/bcf472ed-cfb5-4988-bacc-ffeb84dd549e)

Best regards,
Denys

**Comment by devaskim** [comment]
@den1jkee does pg_dump do its work well while TB is running ?

**Comment by den1jkee** [comment]
Hi @devaskim,
It is better to stop mytb container, like in the case of docker TB PE, but in the case of tb-postgres, you can't stop mytb container. Also, it can be done while TB running. We tested it yesterday, and successfully.
![image](https://github.com/thingsboard/thingsboard/assets/113901187/b9841c47-5bb3-4be0-a7ca-f45b9cf6439e)
![image](https://github.com/thingsboard/thingsboard/assets/113901187/ff623b08-41bf-47b5-ab6f-85d1b438c77d)
Best regards,
Denys

**Comment by dip-devlopement** [comment]
hello i am facing the issue that how how can i take backup of thingsboard/tb-postgres , and run in other ubuntu machine?   

and how to restore that in such way that my previous data, assets, dashboard and devices remain same as i created in previous .

**Comment by dip-devlopement** [comment]
please help

**Comment by dip-devlopement** [comment]
> Hi, You can make a backup in a local dir with docker exec command: `sudo docker exec -i <container_id_or_name> pg_dump --username thingsboard -d thingsboard > /path/to/dir/backup/thingsboard_backup.sql`
> 
> Thanks.
> 
> Best regards, Denys

how to restore it in such way that my all backuped data , devices, dashboards remain same . my all  old data start successfully in new restoration
