### ISSUE TITLE
[Question] proxy error at runtime

### ISSUE THREAD

**Issue by Meisam-rashno** [thingsboard/thingsboard#8625]
hi mates!
I have this error when I run the project
 `Error occured while trying to proxy to: localhost:4200/api/noauth/oauth2Clients?platform=WEB`

**Comment by den1jkee** [comment]
Hi,
Please provide more details about your issue. What kind of deployment did you do?
Please provide `thingsboard.log` to investigate.

Best regards,
Denys

**Comment by Meisam-rashno** [comment]
I have this error on runtime in VS Code terminal, probably because there is no database to connect to.
[URL=https://imgurl.ir/][IMG]https://imgurl.ir/uploads/r89610_thingsboard-error.jpg[/IMG][/URL]
What should I do if I want to see the internal pages?
