### ISSUE TITLE
Has anyone setup a RUT955 or any Teltonika device to Thingsboard website so that the thingsboard website can control devices through the control widgets/RPC??

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8627]
* Rule Engine
 * Installation

Im using the RUT955 to read registers from my devices and send that info to the thingsboard website. I have this working great. I would now like to control my devices from the thingsboard website.  I would like to write registers from the thingsboard website using their control widgets and RPC. But I am having troube to get this to work. I can write registers from the RUT955 using the test function and it works great but now I woulid like to use the thingsboard website to do this using control widgets.

Has anyone figured this out? Is there a step by step guide in seting up the RUT955 and Thingsboard so I can control my devices from the the thingsboard dashboard?

Thanks

**Comment by ban2derlog** [comment]
Hi,

Have you read docs for APIs with descriptions of how to perform server-side RPCs?
https://thingsboard.io/docs/pe/reference/http-api/#server-side-rpc

Additionally, if you use Integration to connect Devices:
https://thingsboard.io/docs/user-guide/integrations/

Also, if your device can receive API calls and perform them - you can try to use another approach via Rest API node to send commands as API requests.
