### ISSUE TITLE
[Question] 401 Authentication Failure for Thingsboard 2.4.3 -> 2.5 upgrade.

### ISSUE THREAD

**Issue by jabr0ni** [thingsboard/thingsboard#8629]
**Thingsboard Upgrade 2.4.3PE --> 2.5PE**

 * Installation

**Description**
I am in the process of commissioning an upgrade of our thingsboard server from 2.4.3 to the latest 3.x version. In order to achieve this, I need to sequentially update from 2.4.3.

Our thingsboard server runs on an EC2 AWS server. I started by cloning this image, and spinning up a new instance where I have set up HTTPS and SSL authorization for the new page. I have upgraded the database to postgres 12, and have confirmed that I am able to connect to the database with correct username and password. I have accessed the database via command line and PgAdmin.

When I start the thingsboard service, the service loads fine and I am able to access the website at the new URL, however when I attempt to log in I receive an "Authentication Failure" message. Here is the response JSON :
`{"status":401,"message":"Authentication method not supported","errorCode":10,"timestamp":"2023-05-25T06:48:08.312+0000","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}`

I then tried to do a log in with the default tenant account which gave me the same error. Here is the POST request I attempted:
```
$  curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"username":tenant@thingsboard.org","password":"tenant"}' 'https://my.website.com/api/auth/login'
{"status":401,"message":"Authentication failed","errorCode":10,"timestamp":"2023-05-25T06:39:01.088+0000","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}
```

thingsboard.yml file is what came with the default 2.5. I did a merge and these are the only options I have changed:
```
    key-store-password: "${SSL_KEY_STORE_PASSWORD:password}"
    password: "${SPRING_DATASOURCE_PASSWORD:password}"
```

I am actually wondering if this has something to do with the JWT token? The default in the yml file is:
```
tokenSigningKey: "${JWT_TOKEN_SIGNING_KEY:thingsboardDefaultSigningKey}"
```

I attempted to change it to the token used on our live server, but that did not work. I tried to generate a new one (which is what that POST request above was meant to do), but just received a 401.

**Environment**

 * OS:  Ubuntu 16.04
 * ThingsBoard: version 2.5
 * Browser: Chrome 113.0.5672.127

**Comment by ban2derlog** [comment]
Hi,
`JWT_TOKEN_SIGNING_KEY` doesn't have impact on login\password and authorization.
This is only `salt` that is used for JWT generation only.

I recommend you to compare in database `user_credential` table for this Tenant in your `PROD` db and in your `TEST` db.
Compare password hash for same user, it must be same in both DB.

**Comment by jabr0ni** [comment]
Hi @ban2derlog, there is no data in the `user_credentials` table when I view via PgAdmin. This is the same case for both my `PROD` and `TEST` databases (where `TEST` is a clone of `PROD`). 

I even tried a `pg_dump --data-only --column-inserts -U postgres ...` and did a grep for user data, and the only think that was returned was inserts into the `public.audit_log` table. Is user data stored elsewhere?

**Comment by Ultrazombie** [comment]
Hello @jabr0ni 
Is still relevant?

**Comment by jabr0ni** [comment]
> Hello @jabr0ni Is still relevant?

Hi @Ultrazombie, no it is no longer relevant. I ended up starting the install again and got it working. New version has been running fine since.
