### ISSUE TITLE
Mobile PE App doesn't build apk

### ISSUE THREAD

**Issue by inanlia** [thingsboard/thingsboard#8630]
**Describe the bug**
After upgrading from 3.4.4 to 3.5 mobile app stopped working. After inputting the login information nothing happens.
When I tried to build the apk again this output is given:

> Because every version of flutter_localizations from sdk depends on intl 0.18.0 and thingsboard_app depends on intl ^0.17.0, flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed.
exit code 1

Using _flutter build apk --no-tree-shake-icons_ also gives the same error on the terminal.

I haven't been able to resolve this issue. Changing intl version doesn't work. Removing flutter_localization or adding it manually didn't work.

**Comment by den1jkee** [comment]
Greetings,
Your question is not about ThingsBoard as a service.
Also, you need to update the source-code of your app according to new API and models and re-build your app. You can take the actual API version and models from the `master` branch.

ThingsBoard mobile app has its own branch on GitHub, which means that you can create questions on the [Github community of this app.](https://github.com/thingsboard/flutter_thingsboard_app)

Best regards,
Denys

**Comment by inanlia** [comment]
I have checked the issues page on mobile pe app. Apparently current version is not compatible with TB 3.5.0. 
I'm closing this since posting on mobile pe app page is more appropriate .
