### ISSUE TITLE
[Feature Request] add ability to customize admin menu

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#8631]
It is time thingsboard will allow tenant admin to set default menu item order in an easy drag-and-drop way.  Tenant admin should be able to set sort order, show hide items, and change names.

**Comment by ashvayka** [comment]
Thank you for this request. We now have such a feature planned. It will be part of 3.6

**Comment by securitylamb** [comment]
hi @t0mZ4  are we able to move  the menu item somehow  in the version 3.5.1 PE

**Comment by t0mZ4** [comment]
@securitylamb what do you mean?

**Comment by securitylamb** [comment]
can we move the menu item somehow like now i cant wait for 3.6 version
