### ISSUE TITLE
gateway 

### ISSUE THREAD

**Issue by LYL14** [thingsboard/thingsboard#8635]
* Generic
 * IN modbus.json file, "connectAttemptTimeMs"，"connectAttemptCount"，"waitAfterFailedAttemptsMs",After setting the time, the disconnected reconnection will receive blocked data. The reconnection time and number are different from the setting.

**Comment by devaskim** [comment]
I think it is better to repost your question to[ corresponding issues tracker.](https://github.com/thingsboard/thingsboard-gateway)

**Comment by den1jkee** [comment]
Greetings,

Your question is not related to ThingsBoard as a service.
ThingsBoard Gateway has its own branch on GitHub, which means that you can create questions on the [Github community of this app](https://github.com/thingsboard/thingsboard-gateway/issues).

Best regards,
Denys
