### ISSUE TITLE
[Question] how to multiply attribute and timeseries 

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8642]
i need to multiply attribute and timeseries?
How can I do this?

**Comment by devaskim** [comment]
If you want to get help, you should provide as much details as possible.

**Comment by m3relec** [comment]
When a time series data is received from a specific device, I want to multiply it in an attribute from the same device and store it in the new time series.

**Comment by devaskim** [comment]
Sorry, but seems like you don't [read the documentation](https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#math-function-node). Just ask and wait)

**Comment by ashvayka** [comment]
You should create a separate device profile for your type of device and assign a particular rule chain for this profile. This will isolate the processing of telemetry of different kinds of devices. Then you may add the Math node that was mentioned by @devaskim
