### ISSUE TITLE
[Question] Can't hide legends on chart while the show legends settings is turned off.

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#8648]
I created a new widget, bar chart latest value.

But somehow by default it's showing the legend on the top while the option is turned off.

![image](https://github.com/thingsboard/thingsboard/assets/43811204/d3a1add9-4805-49d7-a0a1-8bb477d815e4)

I also can't trace the css class because it's ponting to <canvas> tag.

I think the problem is also for other charts that is using chartJS library.

And when display legend option is on, another legend just added on the bottom.
![image](https://github.com/thingsboard/thingsboard/assets/43811204/6df415e9-f5b4-4521-a9db-aa9dbbaa365b)

So how can i remove that legend on the top and only trigger legend visibility from the settings option ?

**Comment by ashvayka** [comment]
Will fix in 3.5.2

**Comment by jource08** [comment]
Perfect, thank you!
