### ISSUE TITLE
3D_Map in widget

### ISSUE THREAD

**Issue by Vishalbuu** [thingsboard/thingsboard#8651]
What type of map format will support 3D map in map widget, are there any constraints for formats 
 * OS:  Ubuntu 20.04
 * ThingsBoard: CE 3.4.4
 * Browser: Firefox

**Comment by mykhailokornieiev** [comment]
Hi

There is no map widget that supports 3D map. For this task you can try to use some workaround, like HTML Card + OSM Buildings "getting start" snippet  
![image](https://github.com/thingsboard/thingsboard/assets/115699895/f0822108-45b3-4981-a462-675626cfb651)
https://osmbuildings.org/documentation/viewer/
Or you can create custom widget:
https://thingsboard.io/docs/user-guide/contribution/widgets-development/
