### ISSUE TITLE
[Bug] Led Indicator widget parse function can't process the string attribute value

### ISSUE THREAD

**Issue by ArtemDzhereleiko** [thingsboard/thingsboard#8655]
The Parse value function can fetch the boolean and numeric values of the device attributes but can’t process the string ones.

Steps to reproduce:
1. create 2 device attributes: state with value 'on' and state_bool with the value true
![image](https://github.com/thingsboard/thingsboard/assets/83352633/61f39121-fb14-4aae-ac81-3bf9721d958c)

2. create the led indicator widget with the following settings:
![image](https://github.com/thingsboard/thingsboard/assets/83352633/39c0366c-d740-4851-8cd1-36017efdebd4)
![image](https://github.com/thingsboard/thingsboard/assets/83352633/51585b55-7d39-4d1b-ac8f-df293e9ad29e)

As you can see, the state_bool works fine, whereas the state string value doesn’t even show up in the console:
![image](https://github.com/thingsboard/thingsboard/assets/83352633/e485d1f6-cc26-4245-8423-f85c3053a376)
![image](https://github.com/thingsboard/thingsboard/assets/83352633/9c63f0c6-fc44-43f7-a933-1faea0d667c6)

**Comment by julvanu** [comment]
The bugfix has not yet been implemented by release 3.5.1, right? I am using it and the issue still occurs.
