### ISSUE TITLE
Telemetry API not working when using http integration services

### ISSUE THREAD

**Issue by sunmountain** [thingsboard/thingsboard#866]
To reproduce:
1. setup tb with http integration service (2.0 PE)
2. create a device and obtain access token
3. put together a http POST sender (I used Python and the requests module, but even tried curl)
4. push data to telemetry data -> tb answers 200 OK, data does not show up
5. push data to attributes data -> tb answers 200 OK, attributes does show up
6. take a already existing device connected over integration service
7. push data to telemetry data -> tb answers 200 OK, data does show up
8. push data to attributes data -> tb answers 200 OK, attributes does show up

I then installed a plain tb 2.0.3 CE without integration services and did steps 2-5 again,
this time with the desired results.

As a last step I set up a new tenant in 2.0 PE with no integration services and tried steps 2-5 again,
this time with the desired results.

My conclusion: if one is using http integration services, the telemetry api is no longer usable.
I assume this is a bug, both should work independent from each other allowing data to
show up from both sources.

Cheers

**Comment by ashvayka** [comment]
Hi @sunmountain You have described very strange behavior and I am not sure how one is related to another. Maybe something specific in your rule chain?

**Comment by sunmountain** [comment]
You' re right, in my rule chain I had a point where the data was not properly going further.
TB is working as expected, so this issue is closed then.

Thanks for the rapid response and your help!
