### ISSUE TITLE
[Question] access internal pages on localhost without install

### ISSUE THREAD

**Issue by Meisam-rashno** [thingsboard/thingsboard#8660]
hi mates!
How can I access intrnal pages on localhost without install?
[<a href="https://imgurl.ir/"><img src="https://imgurl.ir/uploads/v94007_thingsboard-error.jpg" border="0" alt="imgurl.ir" /></a>](url)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
