### ISSUE TITLE
Thingsboard Server Side MQTT-Broker

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#867]
Hello there,

since I was not able to find any information about it I ask this question.

What kind of MQTT-Broker does Thingsboard have? Does it use mosquitto or did you guys implement your own version of a MQTT-Broker? 

Any further information on this would be much appreciated! (documentation links, links to code in git)

**Comment by vparomskiy** [comment]
New MQTT broker was implemented inside the Thingsboard.

The initial point is org.thingsboard.server.transport.mqtt.MqttTransportService

**Comment by patmaclondon** [comment]
So I don't need mosquitto? I'm new to this and trying things out. I have mosquitto running and I'm missing a good front end... I'm not in the market of programming every button in PHP or Java myself everytime I start a project or have a new sensor to add. May I also add that it seems that there is a lack of centos/RHEL support with most of the IOT stuff.
