### ISSUE TITLE
[Question] Transformation script and get customer attributes node in one rule chain

### ISSUE THREAD

**Issue by bloodscript** [thingsboard/thingsboard#8678]
**Component**
 * Rule Engine

**Description**
I want to use a rule chain to alert a customer via mail when telemetric data exceeds a certain threshold. As I want to make the rule chain as generic as possible, I added a email attribute to each customer. The root rule chain starts my "alertThresholdExceed" rule chain after saving the telemetric data. I want to send a mail to the customer to which the device is assigned and the mail shall contain the value the threshold exceeding data.
I connect my Input Node to a script filter node and check if my value exceeds the threshold (currently hardcoded threshold). If it exceeds the threshold, I can either use a transformation script to get the value that exceeded the threshold or a get customer attributes node for acquiring the customer mail, and connect the output to a create alarm node, its output to send mail node and so on... But I can not succesfully connect a transformation script and a get customer attributes node in series and then have access to the outputdata of both nodes in the send mail node.
What is the correct way to acquire a customer attribute and be able to access the message and its attributes?

**Environment**

 * OS:  Debian Bullseye 11.7 // Docker 24.0.1
 * ThingsBoard: thingsboard/tb-postgres:latest
 * Browser: Firefox 102.11.0esr

**Comment by Civilduino** [comment]
Can you post a picture of the rule chain or upload its JSON as `my_rule_chain.json.txt` here?
Did you check these tutorials?
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/

**Comment by bloodscript** [comment]
Issue was solved by further investigation by myself
