### ISSUE TITLE
[Question] ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for StandardWebSocketSession -  No incoming messages to the root rule chain

### ISSUE THREAD

**Issue by mahmutsalman** [thingsboard/thingsboard#8679]
**Component :**  Root Rule Chain

**Description:**
I set up the mqtt integration and I can see incoming messages in the debug mode yet in the root rule chain there are no incoming messages. This happened after I deleted all the customers in the hierarchy. Because I was going to create a customer using **create relation node**.

 **The error I face** is that there are no incoming messages into the root rule chain although in the integration there exist incoming telemetry messages.

I suspect it is about tenant and tenant profiles because in tenant profiles there are options for rule engine executions, TTL, OTA files in bytes, and devices maximum number and such.

For queue service **Kafka** is used.
 
 * thingsboard.log
![image](https://github.com/thingsboard/thingsboard/assets/74365527/b6b73532-55f9-416c-8d21-4691d98ce1b5)

![image](https://github.com/thingsboard/thingsboard/assets/74365527/0394a459-7b1b-466a-a2ae-64ac38511858)

**Environment**

 * OS:  Ubuntu  Ubuntu 20.04.5 LTS
 * ThingsBoard: PE 3.4.1
 * Browser: firefox

**Comment by Ultrazombie** [comment]
Closed due to inactivity
