### ISSUE TITLE
Loading screen during first page load.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#868]
Please add a loading screen when the page is initially loaded.

The initial page load is very slow, due to various scripts that have to be loaded. (As I see, they are more than 7MBs). During this time, the user is prompted with a blank white screen.

If there is no other way to reduce the page loading, or making these files smaller, at least prompt the user that the application is loading.

I get many reports that the server is not working, while in fact the users are just impatient.

**Comment by Delapouite** [comment]
I think this issue can now be closed as a loading spinner has been implemented in version 3.2.1 released in January https://thingsboard.io/docs/reference/releases/#thingsboard-ce-1
