### ISSUE TITLE
[Bug] Can't update users entity fields from web UI 

### ISSUE THREAD

**Issue by clemjrt** [thingsboard/thingsboard#8680]
**Describe the bug**
Unable to update users entity fields like email, first name or last name.
I got the error "Can't update user authority!" from this API endpoint : https://tb.tecsol.fr/swagger-ui/#/user-controller/saveUserUsingPOST
![image](https://github.com/thingsboard/thingsboard/assets/104388936/9fecfabe-c679-4017-b767-55bc60122ef3)

Here is the POST request content : 
![image](https://github.com/thingsboard/thingsboard/assets/104388936/764dd760-ea1f-4664-b6cb-022eb7e5ca2e)

The property "authority" is set to "TENANT_ADMIN" :
![image](https://github.com/thingsboard/thingsboard/assets/104388936/ab6b6476-7a6c-4455-9259-2f6697c143d1)

But in tb_user table, edited user's authority is "CUSTOMER_USER" : 
![image](https://github.com/thingsboard/thingsboard/assets/104388936/088a55de-9b32-4b0b-b3ae-4726dbb5fc8e)
  
* own setup
  * ThingsBoard PE 3.5
  * OS Debian

* OS: Ubuntu  20.04
* Firefox 113.0.2 

**To Reproduce**
1. Go to "Users" menu
2. Click on any user
3. Edit any user info
4. Save

**Comment by ashvayka** [comment]
You are trying to update a user entity with authority=CUSTOMER_USER to autority=TENANT_ADMIN. This is not allowed. Just change the authority to CUSTOMER_USER in your request.

**Comment by tacensTECSOL** [comment]
> You are trying to update a user entity with authority=CUSTOMER_USER to autority=TENANT_ADMIN. This is not allowed. Just change the authority to CUSTOMER_USER in your request.

Since he mentioned using the web ui to update his user's fields, how can he change TENANT_ADMIN to CUSTOMER_USER from the web ui ?

Why is the web ui trying to set his user's autority to TENANT_ADMIN when it's already CUSTOMER_USER ?

**Comment by tacensTECSOL** [comment]
Upgrading to 3.5.1 fixed the issue on my end
