### ISSUE TITLE
[Question] Is it possible to change the default color palette in widgets?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8684]
**Component**

 * UI

**Description**
Is it possible to change the default color palette of ThingsBoard Widgets without doing it manually after adding the widgets to the dashboard?

![image](https://github.com/thingsboard/thingsboard/assets/25298332/b5a438a4-1062-42ee-a9c4-688eda476c8a)

**Environment**

 * ThingsBoard: 3.5 PE

**Comment by devaskim** [comment]
It is almost the same but you could move widget-specific CSS styles to Dashboard CSS styles.
