### ISSUE TITLE
[Question] How to use aggregation feature in the originator telemetry node?

### ISSUE THREAD

**Issue by edsml-tz422** [thingsboard/thingsboard#8687]
**Component**
 * Rule Engine

**Description**
I want to fetch last 30 minutes data and calculate the SUM in order to use this value to trigger an alarm. I used the "originator telemetry" node. And I saw these descriptions in the help: "Aggregation feature allows you to fetch aggregated telemetry as a single value by AVG, COUNT, SUM, MIN, MAX, NONE." But I did not find aggregation feature in the originator telemetry node. 

**Environment**
 * ThingsBoard: Thingsboard Cloud Maker
<img width="779" alt="image" src="https://github.com/thingsboard/thingsboard/assets/110145372/c6bb268a-8863-4cac-96a8-a1e26f9c2479">

**Comment by ashaforost** [comment]
Hi @edsml-tz422 

A Fetch mode LAST means that the output of the rule node is the last message from a list of all retrieved messages. If you want to aggregate all data for the last 30mins, set the Fetch mode to All, and then you'll be able to configure the aggregation.

**Comment by edsml-tz422** [comment]
> Hi @edsml-tz422
> 
> A Fetch mode LAST means that the output of the rule node is the last message from a list of all retrieved messages. If you want to aggregate all data for the last 30mins, set the Fetch mode to All, and then you'll be able to configure the aggregation.

Thanks so much!
