### ISSUE TITLE
Accessing Logged In User's ID in Widget

### ISSUE THREAD

**Issue by codyclay88** [thingsboard/thingsboard#869]
Hello, 
Is there a way to access the ID of the logged in User inside of a custom widget? Or any of the logged in User's information?
Thanks!

**Comment by codyclay88** [comment]
Was able to solve this by using the angular dependency injection to get the userService. 
```
var $injector = self.ctx.$scope.$injector;
var userService = $injector.get('userService');
var userId = userService.getCurrentUser().userId;
```

**Comment by adambforbes** [comment]
Hello Cody, would you be able to include any more details on how you achieved this? E.g. Where did you put this code in the custom widget and is there any other supporting code? I have a hard time understanding custom widgets, so any additional detail would be appreciated.

**Comment by kevz93** [comment]
@adambforbes you need to make this change in thingsboard/ui and recompile to make it available for use in widgets.
