### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by tcstboard** [thingsboard/thingsboard#8699]
We have an already implemented solution in which ThingsBoard is consuming record from OPC UA server on every min. We need to change the consumption frequency from min to hour.  How to implement this requirement? Is it possible by configuring the ThingBoard config file or is there other alternative way to achieve that?

**Comment by myroslav-tb** [comment]
Hello @tcstboard, you can adjust the scan interval in the advanced section of OPC-UA integration settings.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/60936f90-2db6-4873-9363-eaad9732fbde)
Best regards,
Myroslav

**Comment by Ultrazombie** [comment]
Closed due to inactivity
