### ISSUE TITLE
The web socket connection is not opened on chrome browser on an android mobile

### ISSUE THREAD

**Issue by mustafaeltaher** [thingsboard/thingsboard#87]
The web socket connection between an android mobile and the server is not opened when opening up the platform in chrome browser

**Comment by ashvayka** [comment]
This is definitely working in general case. Add more details about your environment. Maybe this is specific to some version, etc. Is the [demo dashboard](https://demo.thingsboard.io/demo?dashboardId=e8e409c0-f2b5-11e6-a6ee-bb0136cc33d0&source=realtimeIotDashboards) working on your phone?

**Comment by mustafaeltaher** [comment]
I think it only worked when I enabled the debug options on my mobile, strange !

**Comment by mustafaeltaher** [comment]
as for the demo dashboard it was working even without enabling the debug options

**Comment by ashvayka** [comment]
I believe this may be your local network problem, since demo dashboards are working fine i will close this.
