### ISSUE TITLE
[Question] What is the latency between updating a users settings and those settings taking effect?

### ISSUE THREAD

**Issue by lfjm2022** [thingsboard/thingsboard#8703]
**Component**

 * UI
 * Generic

**Description**
In thingsboard Cloud PE When I assigned my customer users permissions for the first time yesterday by moving them into customer administrator users they were getting an access denied message. Upon logging in this morning they were able to access everything I had given them access to. It seems like some time over the night their settings updated because I did not change anything. What is the latency from making a change to that change being updated in thingsboard? How many minutes or hours does it take?

**Environment**

 * OS:  Windows and Apple
 * ThingsBoard: Cloud PE
 * Browser: Chrome, Firefox, Safari

**Comment by xalt7x** [comment]
Hello @lfjm2022 ,
Settings should apply fast so it's rather an unusual behavior. Have you experienced this problem again since then?
