### ISSUE TITLE
REST Api call Node using GET Method 

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#871]
Hello there,

I want a GET Request to be triggered on specific events. For this I created the Action Node. 

<img width="328" alt="node-ex" src="https://user-images.githubusercontent.com/37292275/41415378-b398c344-6fe8-11e8-9328-ff5123d0da5a.png">

Now I want the data that I get from the request (It is in JSON Format) to be saved. 

Here comes my question:

Where can I find the data? Will it be under device telemetry of the device that triggered the request? I cannot seem to access ist. The Doc states: 

"In case of successful request, outbound message will be passed to the next nodes via Success chain, otherwise Failure chain is used."

Any help would be much appreciated!

P.S. Great work on the new rule architecture!

**Comment by vparomskiy** [comment]
Response from the Rest API call will be added into Outbound message. 

> Outbound message from this node will contain response status, statusCode, statusReason and response headers in the Message metadata. Outbound Message payload will be the same as the response body. Original Message type and originator will not be changed.

Note: save telemetry node will process only correctly formatted data. If you want to save response as a telemetry you will need to transform it to the correct format. You can find the format in this overview
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#predefined-message-types
