### ISSUE TITLE
[Question] Can we send mutiple telemetry data with different timestamp to thingsboard 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8715]
**Component**

 Rule Engine

**Description**
I want to send multiple telemetry data but the issue they different timestamp can we achieve this using thingsboard 
somethings like this => 
[{\"ts\":1686114806,\"values\":{\"temp\":20.4,\"hum\":78}},{\"ts\":1686114812,\"values\":{\"temp\":22.4,\"hum\":80}}]

**Environment**

 * OS:  ubuntu 20.4
 * ThingsBoard: latest
 * Browser: chrome

**Comment by sudhiraplhind** [comment]
Yes this works.

**Comment by securitylamb** [comment]
so the answer is yes you can do that  just follow the documentation for sending the telemetry data to the device and you will get the result
