### ISSUE TITLE
[Bug] Cannot receive shared attribute updates through MQTT Gateway API

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8719]
**Describe the bug**
[The subscription for attribute update from a server through MQTT gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/#subscribe-to-attribute-updates-from-the-server) doesn't work at all. See full reproduction video.

This is blocker for our business. Please, fix as soon as possible or maybe there is workaround?

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard 3.4.1, 3.5.1
  * Linux, Windows

* Connectivity
  * MQTT
 
**To Reproduce**
Commands from a video
```
mosquitto_pub -d -q 1 -h localhost -u SNxIiGuacSaiBaXBwPcU -t v1/gateway/connect -m '{"device":"AttrTestDevice"}'

export TS=$(date +%s)000 && \
mosquitto_pub -d -q 1 -h localhost \
-t "v1/gateway/telemetry" \
-u "SNxIiGuacSaiBaXBwPcU" \
-m "{\"AttrTestDevice\":[{\"ts\": $TS,\"values\": {\"TestTelemetry\": 5}}]}"

mosquitto_sub -h localhost -u SNxIiGuacSaiBaXBwPcU -t v1/gateway/attributes
```

https://github.com/thingsboard/thingsboard/assets/86909129/1b8759d9-ba17-4009-a375-e221eeac4e6c

**Comment by devaskim** [comment]
@ashvayka Seems like both `connect` event and subscription to attributes should be done in one session. Am I right?

**Comment by imbeacon** [comment]
Hi @devaskim,

You are right, ThingsBoard sends attribute update to the gateway session, and it cannot send to new session, because device is "attached" to first session. It works like this from the very beginning.
