### ISSUE TITLE
[Bug] MQTT over Basic SSL Client ID Format

### ISSUE THREAD

**Issue by A10AIO** [thingsboard/thingsboard#8726]
**Describe the bug**
* When trying to connect to an MQTT host address, there is a specific format for the client ID, e.g., admin/test-123.
However, Things board refuse any other characters than letters & numbers. So when trying to connect using different Client ID format, connection is unauthorized. But when checking connection with correct Client ID format, connection is successful.

Check attached screenshots for more info.

**Server Environment**
* cloud.thingsboard.io

**Client Environment**
* OS: Windows (64bit)
* Browser: Firefox
* Version: 114.0 (64-bit)

**Connectivity**
* MQTT

**Screenshots**
* MQTT Client Configuration Instructions
![MQTT_Client](https://github.com/thingsboard/thingsboard/assets/133926103/c98ef41b-1091-4b30-a615-8cfccd6c07c9)

* Wrong Client ID Format = Connection Unauthorized
![Check Connection Fault](https://github.com/thingsboard/thingsboard/assets/133926103/bb52b175-6fea-4dbf-9ee3-11e57d751845)

* Acceptable Client ID Format = Connection Successful
![Check Connection Success](https://github.com/thingsboard/thingsboard/assets/133926103/286fa010-706a-4223-bc6f-853e1b0b50ab)

**Additional context**
Please do your best to solve this issue.

**Comment by Ultrazombie** [comment]
fixed since ThingsBoard 3.6
