### ISSUE TITLE
[Bug] Unable to save alarm details with alarmService.saveAlarm

### ISSUE THREAD

**Issue by clemjrt** [thingsboard/thingsboard#8730]
Unable to save alarm details using alarmService from widgetContext.

  * ThingsBoard PE 3.5.1
  * OS Debian

** Client Environment**

* OS: Ubuntu 20.04
* Browser Firefox

**To Reproduce**
1. Get alarm object with alarmService.getAlarm(alarmId)
2. Set alarmObject details property from the result
3. Save with alarmService.saveAlarm(alarmObject)

**Expected behavior**
Details property is supposed to be saved

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/104388936/1e2c9c4a-b26a-47d3-ba60-456b6dba12e5)

![image](https://github.com/thingsboard/thingsboard/assets/104388936/7eb2297d-c516-4e74-baf8-0970e5035677)

![image](https://github.com/thingsboard/thingsboard/assets/104388936/d3fdd051-fc71-4cb1-9f54-30b400cd5c0d)

The request is sent with a defined details property, but the answer give a null details property.

**Comment by clemjrt** [comment]
I just noticed that if alarm details are not initialized (null addtional_info column in database), alarm details are not saved. However, if these have already been initialized, registering additional properties of the details object works.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
