### ISSUE TITLE
[Question] Assets Usage Best Practices

### ISSUE THREAD

**Issue by dumont02** [thingsboard/thingsboard#8734]
**Component**

 * Generic

**Description**
I am new to thingsboard and exploring capabilities of this platform.  I am pretty impressed up to now.

I am trying to figure out how assets are expected to be used. Let's say I am a tenant selling devices to customers. And let say I want my customers to manage their own assets and link somehow their device to their assets.

I am currently confused because I was expecting that customers could create their assets through their admin portal and somehow associate their devices to their assets, but running the demo it seems like only the tenant can create and manage assets.

Could you please explain the typical use case for assets usage so I can better understand how to use them?

Thanks you

**Comment by ssakharova** [comment]
Hello @dumont02,

An Asset represents a physical or logical entity that you want to monitor or manage, such as a building, vehicle, or section of an industrial plant. Assets help organize and structure the data coming from various devices. For example, you can group devices under a single asset to represent a complex system or infrastructure. Assets can have relations with other devices or assets, creating a hierarchical structure.

The tenant usually manages the overall ThingsBoard instance, including managing customers, assigning devices, and creating dashboards.
However, as a Customer Administrator, you can also create relations between devices and assets and manage them.
