### ISSUE TITLE
creating alarm for online and offline device using device profile?

### ISSUE THREAD

**Issue by omama-kitt** [thingsboard/thingsboard#8736]
When i try to create alarm for online device and offline using (active) attribute in device attribute,
**Proplem":**
 I didnt recive any alarm in (Alarm device),
but when i try to create alarm for telemetry it get alarm for any condation not for active device or not.
could you get me the corect steps to create alarm using profile and active attribute and the relation with rule chain.

**Comment by ashaforost** [comment]
Hi @omama-kitt 

One of the possible reasons for this behavior is a misplaced device profile rule node in your rule chain. If you moved the device profile rule node in such a way that the activity and inactivity event messages are not reaching it, the inactivity alarms wouldn't be created. Generally, it's advised to keep the device profile rule node right after the input rule node.
