### ISSUE TITLE
[Question] Share Trendz Analytics View to Thingsboard Cloud Dashboard

### ISSUE THREAD

**Issue by A10AIO** [thingsboard/thingsboard#8738]
**Component**
 * UI
 * Trendz + Thingsboard Cloud

**Description**
When trying to add Trendz Analytics view to Thingsboard cloud dashboard, the widget is imported successfully to Thingsboard. However, it always shows blank background with nothing.

As per Thingsboard documentation, all you need is only use (add on dashboard) and that's it. I am sure also that the view URL in the Thingsboard is matching the one in Trendz.
So what is the problem? How to work it out? 

Trendz View
![Trendz](https://github.com/thingsboard/thingsboard/assets/133926103/7f6dfa35-3e57-40a5-91f1-f8367209e65e)

Thingsboard Cloud Dashboard
![TB](https://github.com/thingsboard/thingsboard/assets/133926103/5466fe3a-ee95-4b93-934d-679b9b49aa2a)

**Environment**
 * OS:  Win 10 64-bit
 * Browser: Firefox

**Comment by A10AIO** [comment]
Hi @vparomskiy.

There is no Data tab as it is a Trendz View Static Widget (automatically generated from Trendz).
Advanced tab contains only the view URL from Trendz.

![Trendz_1](https://github.com/thingsboard/thingsboard/assets/133926103/8e929c3e-857d-4268-9197-a9df3e755fae)

**Comment by yuliaklochai** [comment]
Currently you have two modules of the Trendz library in the resources of your widget, which can potentially cause conflicts. To resolve this issue, please retain only one link to the library in the resources tab. Here's the correct link that you should use: https://kgs.kyntech.pt/trendz/bundle/trendz-tb-lib.js

**Comment by Juka-22** [comment]
Now it's working!

Thanks for the help!!  @yuliaklochai
