### ISSUE TITLE
[Question] Required Notification_Target id in Notification_Request

### ISSUE THREAD

**Issue by clemjrt** [thingsboard/thingsboard#8742]
**Description**
To create a notification request with this API endpoint : 
![image](https://github.com/thingsboard/thingsboard/assets/104388936/53165303-a461-4019-9c26-cd07a557c8d8)
It is required to specify a notification target id, and it is not possible to specify a notification target object, as it is possible for a notification template : 
![image](https://github.com/thingsboard/thingsboard/assets/104388936/11365676-3075-4d05-b45e-786623b8a5ca)

Is there any particular reason ? 
Otherwise, I think it could be a usefull feature to send one-off notifications.

Thank you by advance for any answers.

**Environment**
 * ThingsBoard: 3.5.1 PE

**Comment by Ultrazombie** [comment]
There is no such functionality; it is beyond the scope of our system design.
