### ISSUE TITLE
HTTP over SSL TLS

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#8746]
I am trying to push data from node red to thingsboard PE cloud device via access token, over http. But i want to secure this communication by enabling SSL TLS encryption. kindly suggest how can i do that.

**Comment by devaskim** [comment]
[Here are official guides](https://thingsboard.io/docs/search/?q=haproxy)

**Comment by securitylamb** [comment]
you can just follow the installation guide  no need  to search anything else 
(I am assuming you are installing on ubuntu you can follow other guides too)
[https://thingsboard.io/docs/user-guide/install/pe/ubuntu/](url)
![image](https://github.com/thingsboard/thingsboard/assets/34526029/caec7049-3043-41ef-bfed-6047bac8a631)

**Comment by ban2derlog** [comment]
Hi,
If you use self-managed service:
Use internal HTTPS features:
https://thingsboard.io/docs/pe/user-guide/ssl/http-over-ssl/
Or use haproxy load balancer:
https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

If you use ThingsBoard Cloud:
Then it's enabled by default. If you add custom Domain Name - then ThingsBoard Cloud will automatically create a SSL certificate for it.
