### ISSUE TITLE
The new ThingsBoards Cloud update is causing slowdowns when opening a new dashboard

### ISSUE THREAD

**Issue by vmlourenco** [thingsboard/thingsboard#8747]
Hello, 

After ThingsBoard's last update, some things that were working, are not anymore. 

For example, when you click on a Widget that navigate to another dashboard sometimes it doesn't  happen instantly. You need to click to actualize the page to go to the other dashboard. 

I tried changing the Click Event to execute a JS command and go to the other dashboard, but it doesn't work because this way the new page loses some information.

How can I solve this?

Thank you

I attached a video explaining the slowness in changing the dashboard

https://github.com/thingsboard/thingsboard/assets/25009197/ab717ee7-3d7f-4d1b-a619-42ba7188bc0e

**Comment by AlexDoanTB** [comment]
@vmlourenco, have you checked and reworked your JS custom code and external stylesheets to meet Angular 15? The issue is not with the action or the quality of the network.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
