### ISSUE TITLE
[Question] I can't show bar chart with array data

### ISSUE THREAD

**Issue by ornyilmaz** [thingsboard/thingsboard#8748]
**Component**
 * UI

**Description**
I learn thingsboard UI. I want to draw x-y graphic. For example historical templerature - pressure graphic. My timeseries data1=["label1" ,"label2",...] and data2=[1,4,6,0,7,90,10,...]  

I can't show this graph. It works if I don't give the data as a array. But I don't want to deal with it.

How can I make this chart with array value?

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: CE
 * Browser: chrome

**Comment by devaskim** [comment]
How about this [custom chart](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#time-series-example)?

**Comment by ornyilmaz** [comment]
I will try this manual.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
