### ISSUE TITLE
[Question] Notification Center for Customers or Tenant Users

### ISSUE THREAD

**Issue by A10AIO** [thingsboard/thingsboard#8750]
**Component**
 * Notification Center

**Description**
I would like to view notification center messages as in tenant admin user in a tenant user page.
The user has always full screen dashboard and the home side bar is hidden.
Is it possible with these properties or only when the user dashboard is not full screen?

![Group 1](https://github.com/thingsboard/thingsboard/assets/133926103/a5ebbe95-e96f-4a43-8926-b1222502b5b1)

**Environment**
 * OS:  Win 10 64-bit
 * ThingsBoard: PE 3.5.1
 * Browser: Firefox 114.0 (64-bit)

**Comment by ssakharova** [comment]
Hello @A10AIO,

The notification bell icon doesn’t appear when the ‘Always fullscreen’ checkbox is enabled. Our developers already know about this issue, but there’s no specific timeframe for when they could correct it.

However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
