### ISSUE TITLE
[Feature Request] get base64 file by rest API

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#8758]
I would like to get base64 (png, jpeg...) of blob to send this information by rest API to another application. For my example the applications needs to receive the base64 information inside a json of rest API call, I coundn`t find a way to do this with current Blob entity controller api, is there a way?

**Comment by ifelse-code** [comment]
Hi @ban2derlog, thank you! But what I really need to do is get the file that is already on blob. For example, I need to get a report file (png) and send this by Ultramsg api, to do this I need to pass the image as base64 in a specific key. So for now, can I do this in someway?


The code below is ultramsg example to how send the image.
`
var data = JSON.stringify({
    "token": "{TOKEN}",
    "to": "+9999999999999",
    "image": "**base64code**",
    "caption": "image Caption"
});

var xhr = new XMLHttpRequest();
xhr.withCredentials = false;

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://api.ultramsg.com/{INSTANCE_ID}/messages/image");
xhr.setRequestHeader("Content-Type", "application/json");

xhr.send(data);

`

**Comment by ban2derlog** [comment]
@ifelse-code in this case you can create a Rule Chain that will send Rest API calls to ThingsBoard itself and after to your app.
Workflow will be like this:
Rest API node sends request with credentials to fetch JWT for access and after use it to send GET request to blob-controller. Responses that ThingsBoard receives on requests from Rest API nodes become messages in output route from node, so after you can modify payload in Script node and send correct payload to your API.

**Comment by ifelse-code** [comment]
yes, i`ve already tried it. But after I do the GET request to blob-controller and receive the response, the file is carried on metadata response, i can`t get a way to handle this data present on metadata. Am I doing something wrong?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
