### ISSUE TITLE
Issues using widget import to clone widgets

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#876]
Hi

I'll start with a feature request: ability to duplicate/clone widgets.

After I spend time to configure a widget exactly how I want it, I'd like to clone it and use it again with a different telemetry data.

Since there is no duplicate/clone widget option, I am left with the option to export and import the widget.

bug: when importing a widget to a dashboard that already contains the widget, the widget is imported ontop of the existing widget and both widgets are pushed to the bottom of the dashboard.

Removing one of them still causes issues, and saving the dashboard will sometime cause the widget to disappear.

Attached is the json of the widget I am trying to duplicate (timeseries float) 

[temperature.txt](https://github.com/thingsboard/thingsboard/files/2108976/temperature.txt)

I am testing Professional Edition on latest release

**Comment by t0mmyz7** [comment]
Opps, I guess there is a simple an elegant way to "copy" widgets, right-click -> copy and paste.

So I guess this issue isn't relevant to duplicating/cloning widgets, 

So now the question remains, should a user be able to import a widget more than once into the dashboard?  If so there is a bug.

**Comment by giganoide** [comment]
I think it could be usefull for "copy/paste" the widget in another dashboard.

**Comment by volodymyr-babak** [comment]
copy/paste widgets in dashboard functionality are in place:
![image](https://user-images.githubusercontent.com/3466101/152999490-7a73dfcb-a869-4793-b30a-a3113803253e.png)

**Comment by t0mZ4** [comment]
right this is a very old ticket, things have improved since :) closing it as now widgets can be duplicated and pasting is now supported. also the import bug reported is fixed.

good progress
