### ISSUE TITLE
[Bug] Row style function - some styles do not change the appearance of the table row. 

### ISSUE THREAD

**Issue by ArtemDzhereleiko** [thingsboard/thingsboard#8766]
Steps to reproduce:
1. Login as a Tenant user 
2. Open the dashboard menu - create or open any dashboard
3. Enable edit mode
4. Add the Alias with entity type device and add the Entities table widget 
5. open widget settings - Advanced tab - Enable the Use row style function
and put the following code:

return {
  height: '100PX',
  color:'rgb(0, 132, 214)',
  fontWeight: 600,
  fontSize: '17px',
  backgroundColor: 'red',
  fontFamily: 'Monospace'
}

6. save 
7. most options do not change the appearance of the row

![image](https://github.com/thingsboard/thingsboard/assets/83352633/974613ce-060f-4d28-8f05-4b7038b67850)

**Comment by Ultrazombie** [comment]
https://github.com/thingsboard/thingsboard/issues/8766
