### ISSUE TITLE
how to send device information when REST API CALL in thingsboard 2.0

### ISSUE THREAD

**Issue by lomal788** [thingsboard/thingsboard#877]
how to send device information when REST API CALL in thingsboard 2.0.

there's no fucntion for sending device information in thingsboard 2.0.

under 2.0 there's body template textbox so I can put $deviceId #temputre(data),etc like this.

but 2.0 there's no body template box when call rest api with data that device sended.

where's metaKeyName list could I find in thingsboard document?

**Comment by vparomskiy** [comment]
You need to add all fields, that you want to send via Rest API call, into message metadata before entering Rest API call node. Enrichment nodes can do this job:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/

**Comment by lomal788** [comment]
@vparomskiy No ther'es no ${deviceId}.
I checked data is sended correctly but DeviceId is not sended.
what I wanna do is send DeviceId when call the rest api ( not deviceName,Type Device Unique Id)

**Comment by arthurborgesdev** [comment]
@lomal788 Have you found a workaround for that issue? I want too to pass metadata (like time, for example) to each message sent through rest api call, but don't know how to do that.

**Comment by blackprincess88** [comment]
Still having the same issue.....
