### ISSUE TITLE
[Question] [PE] Adding persistent integration buffer

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [thingsboard/thingsboard#8770]
**Component**

 * Integrations

**Description**
Right now I am facing some issues with sensors. That's okay, and not specifically a problem with thingsboard, but thinking about building a real world, large scale application with thingsboard has opened some questions. Right now, as it is, if my _Uplink_ parser fails, the messages are "gone", or well stored in the "logs".

Now the question here for me would be if there is a possibility of adding a message buffer _after_ the Integration layer, and before the _Uplink converter_, that could persistently store the messages and _resend_ them to the _Uplink converter_ once it was "fixed". 

Whilst this seems like a niche use case, it is certainly not; there are availability and consistency concerns for several real world use cases, where a requirement is to be as close to 100% data gathering as possible, and potentially having the issue that everything is lost because _something changed_ is a high risk.

**Environment**

 * OS:  Linux (ubuntu 20.04)
 * ThingsBoard: 3.5.1PE
 * Browser: Firefox

**Comment by Ultrazombie** [comment]
Your request looks like a performance killer in the case of many messages. Please consider reprocessing messages on your side in the failed scenario.
