### ISSUE TITLE
[Question] how can I edit the home screen ??

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8771]
**Component**

 * UI
 * Generic

**Description**
how can i edit the default home Page of the thingsboard  =>>>>>>>

![image](https://github.com/thingsboard/thingsboard/assets/34526029/2ded35fd-ff77-4ab8-94d3-00b0098c20f5)
**Environment**

 * OS:  ubuntu
 * ThingsBoard:3.5.1 PE
 * Browser: brave

**Comment by ban2derlog** [comment]
Hi,
This will be able to cahnge in future release.
For now you can only change Home page for Users to a custom one or Dashboard, for example.

All these widgets can be used in Dashboard.
