### ISSUE TITLE
Dashboard Time selection window Corrupt

### ISSUE THREAD

**Issue by suyutinisai** [thingsboard/thingsboard#8773]
We recently Upgraded from 3.4.4 to 3.5.0 to 3.5.1 PE, We facing the Following Issues 
<img width="625" alt="image" src="https://github.com/thingsboard/thingsboard/assets/90888637/2f413f95-1c30-4945-967b-8c1fdbb3e46f">
![image](https://github.com/thingsboard/thingsboard/assets/90888637/11b544ec-0b8d-486a-8d13-bad84b1b70f2)

**Note: Clearing the Browser cache didn't resolve this issue**

**Comment by miraj** [comment]
could be related to #8537

**Comment by den1jkee** [comment]
Hi,

If clearing the cache doesn't resolve this issue, I can assume that you use custom translations, so in this case, you need to check the lines related to the time window in localization file. 

In localization 3.5+ version was changed detection of localized values, see an example below:

In 3.5+
`"every-n-days-text": "Every { days, plural, =1 {day} other {# days} }"`

Most likely you have the next records in your localization:

`"every-n-days-text": "Every { days, plural, 1 {day} other {# days} }"`

So the difference between localizations is  **=1 {minute}**  and this **1 {minute}**. 

You need to change as shown in example from **1 {day}, 1 {week},** etc. to **=1 {day}, =1 {week},** etc.

Best regards,
Denys

**Comment by miraj** [comment]
@den1jkee 
Issue resolved by changing the custom translation.

**Comment by den1jkee** [comment]
@miraj 
I`m glad to hear that.
