### ISSUE TITLE
[Question] How do you get the last message in the rule engine

### ISSUE THREAD

**Issue by znnspace** [thingsboard/thingsboard#8774]
**Component**

 * Rule Engine

**Description**
How do you get the last message in the rule engine

**Comment by ban2derlog** [comment]
Hi,
There isn't such option in ThingsBoard.

As workaround you can enable Debug mode in first node of Root Rule Chain and then can check messages in Event - Debug tab of this Rule node.
It will show all messages (even internal), but keep in mind that Debug mode that will be enabled continuously will store many records in database, so this can rise database size.
