### ISSUE TITLE
[Question] How to Optimize Rule Engine Message Stacking Problem

### ISSUE THREAD

**Issue by baigod** [thingsboard/thingsboard#8776]
![image](https://github.com/thingsboard/thingsboard/assets/23446974/0b1e175d-c995-4234-b637-9732b4749f2d)

version: thingsboard:3.4.4
queue.type:kafka

I am using a self built open source thingsboard3.4.4
In daily business operations, each message requires 4-5 rule nodes to complete the processing of a message. I have approximately 4 4-core 8G containers running thingsboard
My rule engine has approximately 10000 messages per second. I use the tb-js executor x 20 with kafka for remote JavaScript calls. I acknowledge that this may cause some delay due to remote calls to nodejs. May I ask how I can optimize my service parameters to fully utilize system resources and reduce kafka message accumulation in the rule engine?

**Comment by pon0marev** [comment]
To optimize the performance of script nodes, switch to [TBEL](https://thingsboard.io/docs/user-guide/tbel/), since processing such scripts does not require sending messages to js-executors via kafka. Such a script is executed inside the rule engine service.

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
