### ISSUE TITLE
how can I fetch alarms in related Asset to special Device by thingsboard library in flutter?

### ISSUE THREAD

**Issue by mahshadparsa** [thingsboard/thingsboard#8777]
I set the device profile in the web UI of ThingsBoard to create alarms when some telemetries are out of the accepted range. My device is related to the special Asset. In the web UI of ThingsBoard, I can see alarms in both entities of Asset and Device, but in my Flutter app, I can't fetch alarms by asset Id. I use from tbClient.getAlarmService().getAllAlarms(alarmQuery), I set alarmQuery as follows:

`alarmQuery=AlarmQuery(TimePageLink(10,0,null,SortOrder('createdTime',Direction.DESC)),fetchOriginator:true);
alarmQuery.searchStatuse=AlarmSearchStatuse.ACTIVE;
alarmQuery.affectedEntityId=myEntityId;`
When I run the above program, all alarms of all assets and devices are fetched, While I expected only myEntityId alarms to be displayed. Please let me know, how can I fetch only alarms of special Asset.

 * ThingsBoard: thingsboard_client: ^1.0.6

**Comment by alenas** [comment]
Hi,

you need to filter alarms by device profile:
`
AlarmDataQuery(entityFilter: DeviceTypeFilter(deviceType: "yourDeviceProfileName"),....
`

full example:

`    
var alarmFields = <EntityKey>[
      EntityKey(type: EntityKeyType.ALARM_FIELD, key: "createdTime"),
      EntityKey(type: EntityKeyType.ALARM_FIELD, key: "type"),
      EntityKey(type: EntityKeyType.ALARM_FIELD, key: "secerity"),
      EntityKey(type: EntityKeyType.ALARM_FIELD, key: "status"),
    ];
    var alarmQuery = AlarmDataQuery(
        entityFilter: DeviceTypeFilter(deviceType: "yourDeviceProfileName"),
        alarmFields: alarmFields,
        pageLink: AlarmDataPageLink(
            pageSize: 100,
            searchPropagatedAlarms: true,
            timeWindow: 604800000,
            sortOrder: EntityDataSortOrder(key: EntityKey(type: EntityKeyType.ALARM_FIELD, key: "createdTime"), direction: EntityDataSortOrderDirection.DESC)));
    _subscription = TelemetrySubscriber(_client.getTelemetryService(), [AlarmDataCmd(cmdId: 100, query: alarmQuery)]);
    _subscription!.alarmDataStream.listen(onData, onError: onError, onDone: onDone, cancelOnError: true);
    _subscription!.subscribe();
`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
