### ISSUE TITLE
[Question] Add more settings to OSM widget

### ISSUE THREAD

**Issue by shayMZ** [thingsboard/thingsboard#8778]
Hi,

I'm using the OSM widget for my new custom widget.
I want to add more settings to the default settings that a map widet allready use, c
How can I keep the default setting and use my also?
My setting only become visible if I clear the setting form selector.

I'm using thingsboard.cloud system

any suggestions?

Thanks,
Shay

**Comment by devaskim** [comment]
it is impossible

**Comment by shayMZ** [comment]
Can you explain to me how? 
Because when I add my own setting I can't see them.
This is my setting:
{
    "schema": {
        "type": "object",
        "title": "Common map settings",
        "required": [],
        "properties": {
            "autofocus": {
                "title": "Auto focus to user location",
                "type": "boolean",
                "default": false
            }
        }
    },
    "form": [
        "autofocus"
    ]
}

![image](https://github.com/thingsboard/thingsboard/assets/9458859/c1ebcb87-6aaf-4574-9de6-0ab6e839abd0)

If I remove the setting form selector it works. but it's not what I want, I want to add more setting

Thank you,
Shay

**Comment by devaskim** [comment]
> Can you explain to me how?

Read again what I wrote.

**Comment by shayMZ** [comment]
Oh, I'm sorry, I read it wrong... 

I think you should think about it to make it possible :) 

Shay

**Comment by devaskim** [comment]
> I think you should think about it to make it possible :)

I am not a member of Thingsboard team, so no ;)

**Comment by devaskim** [comment]
By the way, we need this feature too, so several months ago I implemented [this feature](https://github.com/thingsboard/thingsboard/pull/8082), but it is still in review ((((

**Comment by ashaforost** [comment]
closing the issue due to inactivity. If the issue is still valid, @devaskim , please create a PR
