### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by dhaval2017** [thingsboard/thingsboard#8781]
**Component**
 * Generic

**Description**
in integrating oauth2 https://thingsboard_domain/security-settings/oauth2
if we keep JSON web key URI empty it gives error as below
[missing_signature_verifier] Failed to find a Signature Verifier for Client Registration: '6de6eac0-0e70-11ee-902f-dfbee273aabb'. Check to ensure you have configured the JwkSet URI.

I wish it should be option to check for JWKS.

**Comment by ashaforost** [comment]
Hi @dhaval2017 

Assuming you use a custom oauth2 provider, it's unwise to add validation for the JwkSet URI field, as some custom providers do not require one. 
Please let me know if I'm incorrect in my assumptions and feel free to clarify your request.

**Comment by dmaradey** [comment]
@dhaval2017 
Did you get anywhere with this?

**Comment by dhaval2017** [comment]
> Hi @dhaval2017
> 
> Assuming you use a custom oauth2 provider, it's unwise to add validation for the JwkSet URI field, as some custom providers do not require one. Please let me know if I'm incorrect in my assumptions and feel free to clarify your request.

yes right

**Comment by dhaval2017** [comment]
> @dhaval2017 Did you get anywhere with this?

nope
