### ISSUE TITLE
[Question] Custom widget communication

### ISSUE THREAD

**Issue by Prasadhinditron** [thingsboard/thingsboard#8782]
Hi,

we are working on custom widget of time series table. we added row click action in table.
But, how to get row data in backend javascript section (In red box)

![unnamed](https://github.com/thingsboard/thingsboard/assets/137045108/9f4b17dd-cb26-422d-83e6-207fc29f5b03)

Can you please share me examples to achieve this ?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
