### ISSUE TITLE
[Question] Do Thingsboard JavaScript runners support WASM?

### ISSUE THREAD

**Issue by Fremboli** [thingsboard/thingsboard#8785]
Hi,

we are using Thingsboard PE.
Is it possible to use WASM in Data Converters and/or Rule Engine Scripts?

 Thanks

   FE

**Comment by ban2derlog** [comment]
Hi,
ThingsBoard doesn't support Assembler in JS.
But you can create a custom Rule Node that will include libs to perform such operations.
https://thingsboard.io/docs/user-guide/contribution/rule-node-development/

**Comment by Fremboli** [comment]
Thanks, i will try...
