### ISSUE TITLE
[Question] How to automatically add a wedget to the dashboard?

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#8787]
Hello. 

TB PE(3.5.1) and chirpstack are integrated.
When a device is registered on the chirpstack side, it is displayed in the TB device.

I want to automatically add this device to the customer's dashboard as a gauge widget.

I think it is using rule chain, but I don't know the trigger to know when the device is added.
I have asked ChatGPT, and He say to use "onDeviceAdded", but I can't find it in the documentation.

Is there a way to have the gauge widget appear on the dashboard automatically when a device is added to the TB?

**Comment by devaskim** [comment]
As of 3.5.1 there is no feature of conditionally showing/hiding a widget.

Vote https://github.com/thingsboard/thingsboard/issues/6866

**Comment by h-takado** [comment]
Thanks for the response.
Hopefully this will be expanded in the future.

**Comment by angelldavidd** [comment]
please, some solution? i'm need it, TY.
