### ISSUE TITLE
How can you change the color of your widget background when it receives certain telemetry?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8791]
Hi everyone,

I would like to have a card widget change background color when certain vales are returned.

For example, I would like the color to change to Green when it receives the telemetry 2 and Red when it receives the telemetry 0.
I have it now so that when the telemetry is 2 it returns with the word Manual mode. I would like it to also change the background color to green as well.

So when the value 2 is received the background color changes to Green and the word Manual mode appears.

Here what the card look like now.
![image](https://github.com/thingsboard/thingsboard/assets/130080104/b787125c-9624-404a-acef-0d91c7bc9fec)
![image](https://github.com/thingsboard/thingsboard/assets/130080104/85e7a409-0669-4541-b0f0-dff813d9ee93)

Thanks

**Comment by devaskim** [comment]
I am not sure that you can do it with this widget (consider HTML Value Card).
In general you need to add one more data key for `Control_State` but with another label, for example, `Color_State_Color`. In its post processing function returns color code/name supported by CSS [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) attribute. Then use this attribute and returned value from the function in the [style](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style) attribute of HTML element.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
