### ISSUE TITLE
[Bug] Dashboard timewindow area is not well display

### ISSUE THREAD

**Issue by star7128** [thingsboard/thingsboard#8795]
**Describe the bug**
Dashboard timewindow area is not well display in iPhone handsets

**Your Server Environment**

* demo.thingsboard.io
* self-hosting ThingsBoard PE

**Your Client Environment**

**Smartphone (please complete the following information):**
* Device: iPhone12 Pro (iOS 16.5), iPhone7 (iOS15.6.1)
* OS: iOS 16.5, iOS15.6.1
* Browser chrome, safari

**To Reproduce**
1. Firstly, click one public dashboard below via your iPhone 
https://demo.thingsboard.io/dashboards/4101e010-0fa0-11ee-bc3e-11bdfd99be3f
2. Click timewindow icon

**Expected behavior**
Dashboard timewindow area is well display in iPhone env as Android handsets 

**Screenshots**
![1E4D6005-9634-4A25-AEC9-A95D85B8DCF8](https://github.com/thingsboard/thingsboard/assets/59913479/e4a809e6-0c16-484c-bd1c-66695832ff15)

**Comment by epalchenko** [comment]
Hello,
This is already a known issue. 
The ticket (PROD-3102) about this issue has already been added to our backlog for the product team.
Once the product team reviews this ticket, we’ll post an update on when this fix for this issue could be delivered.

As a workaround, you can add the following style for your white labeling to Advanced CSS
```
.tb-timewindow-panel
{
    width: min-content !important;
    position: static !important;
}
```

**Comment by epalchenko** [comment]
We will close this ticket as it is already in our backlog.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
