### ISSUE TITLE
[Bug] Create New alarm bug

### ISSUE THREAD

**Issue by bigbrainnelson** [thingsboard/thingsboard#8797]
**Describe the bug**
Create alarm node is different post upgrade to v3.5.0

**Your Server Environment**

Self hosted Thingsboard Community Edition
  * ThingsBoard Version : v3.5.0

**Your Client Environment**

**Desktop (please complete the following information):** windows 11

* Browser [e.g. chrome, safari] chrome

I am unable to create new alarms after upgrading thingsboard from v3.4.4 to 3.5.0. Also, I can't specify alarm type and severity.
See screenshot below (opened at rule chain)

![Screenshot 2023-06-21 120329](https://github.com/thingsboard/thingsboard/assets/137255432/03cdb1c0-2560-4d24-b550-96e6a8530f65)

**Expected behavior**
![Screenshot 2023-06-21 124251](https://github.com/thingsboard/thingsboard/assets/137255432/8133fc01-4c05-471d-ae23-e28de04ba4b2).

Please help...

**Comment by AlexDoanTB** [comment]
Hi @bigbrainnelson . Could you let me know how you upgraded your instance? Have you seen the SUCCESS log?  
Have you cleared the cache? It seems like either you have not appropriately upgraded, or are facing the cache issue. 
The below screen is the UI of v3.5.x Create alarm node.  
![image](https://github.com/thingsboard/thingsboard/assets/47384595/ceffc7b6-3377-45aa-9261-7ee6a64c339d)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
