### ISSUE TITLE
[Feature Request] Entity Get/Update rule node

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8799]
**Is your feature request related to a problem? Please describe.**
Our cases:
1. Automatically setting home/default dashboard to a new/existing user.
2. Adding business specific values to `additionalInfo` field of entity (basically, user and customer).

**The main problem is not an absence of such rule node, but firing `Entity Updated` event if entity will be updated through Thingsboard REST API**. In major of our cases it causes self-DDoSing of rule engine, because our rule chain listens to this event.

**Describe the solution you'd like**
1. Add a rule node that will search entity by search text provided in a preconfigured field of a message's body or metadata and return its DTO in a message body. Type of entity could be set in a rule node configuration from a dropdown list.
2. Add a rule node that will override existing entity with DTO specified in a message body or (optionally) its field.

**Describe alternatives you've considered**
Use REST API node to
1. Call Login REST API of Thingsboard
3. Call GET entity REST API of Thingsboard to retrieve entity's DTO
4. Use Transform node to update DTO.
5. Call POST entity REST API of Thingsboard to override entity's DTO.
6. Catch `Entity Updated` event and try it to filter.

**Comment by dratasich** [comment]
Hello @devaskim,
just stumbled across this issue. Is there such a rule node?
If not -> I'm voting for it (currently I use the workaround/alternative as described) :)
Thanks in advance!

**Comment by devaskim** [comment]
I implemented 2 custom rule nodes for this purpose (**using TB 3.8.0 API**). Follow the [official guide](https://thingsboard.io/docs/user-guide/contribution/rule-node-development/) to compile and deploy those nodes.

[UpdateEntityNode.java](https://github.com/user-attachments/files/22632948/UpdateEntityNode.java)
[UpdateEntityNodeConfiguration.java](https://github.com/user-attachments/files/22632947/UpdateEntityNodeConfiguration.java)
[SearchEntityNode.java](https://github.com/user-attachments/files/22632950/SearchEntityNode.java)
[SearchEntityNodeConfiguration.java](https://github.com/user-attachments/files/22632949/SearchEntityNodeConfiguration.java)
