### ISSUE TITLE
[Question] Reseting white label login settings

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#8801]
Hi,

After a looooong migration from 3.2.0PE to 3.5.1PE, I have everything in order except 1 thing. The server is now ignoring my white label login settings (so it is using the default green/blue one). Worst than than I cannot edit these settings (despite the fact that they are loaded correctly), when I modify them and then click on save, I receive an error (400 Bad Request). Nothing shows up in the log when the error happens.

How can I fix that? How can I reset to the default settings? (so I can write new values there)

I have access to the DB so I can delete/edit records if needed (I found traces of the settings in admin_settings and in attribute_kv tables).

Any help would be appreciated.

Regards,

B

**Comment by devaskim** [comment]
Not sure that this helps you but every customer has special attribute called `whiteLabelParams`. Here is default value
```
{
    "appTitle": null,
    "customCss": null,
    "enableHelpLinks": null,
    "favicon": null,
    "faviconChecksum": null,
    "helpLinkBaseUrl": null,
    "logoImageChecksum": null,
    "logoImageHeight": null,
    "logoImageUrl": "",
    "paletteSettings": null,
    "platformName": null,
    "platformVersion": null,
    "showNameVersion": null,
    "uiHelpBaseUrl": null,
    "whiteLabelingEnabled": true
}
```

**Comment by bbrenne** [comment]
Support fixed it (I don't know how exactly).
