### ISSUE TITLE
[Question] How to use Custom Translations in Custom Widgets?

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8802]
**Component**
 * UI

**Description**
What is the best way to include custom translations in Custom Widgets?

If you use a function in the data settings, the translation for the custom widget is not executed.
However, if you use the label of a data point, it works.

![image](https://github.com/thingsboard/thingsboard/assets/25298332/a92543cc-92d0-400e-97d9-5ffd9cf7c63d)

![test](https://github.com/thingsboard/thingsboard/assets/25298332/da0b8912-9c5b-41c7-aa48-67b8e60966e2)

If you do the same in the Markdown/HTML card, it works:
![image](https://github.com/thingsboard/thingsboard/assets/25298332/59f92cae-680c-4f94-9bd3-b0b28c372fef)

![image](https://github.com/thingsboard/thingsboard/assets/25298332/a6e1be4c-90d1-4feb-851d-3ef7e1b63028)

**Environment**
 * ThingsBoard: 3.5.1 PE

**Comment by devaskim** [comment]
Not sure if it will work, but try `${entityLabel}`

**Comment by mde2017** [comment]
I have found the solution:

```
// custom translations
    self.ctx.translate.get(["custom.general.info",
        "custom.technical.fill-level"
    ]).subscribe((translations) => {
        console.log(translations)
    });
```

**Comment by devdoob** [comment]
try this 

`self.ctx.translate.instant('custom.general.info')`
