### ISSUE TITLE
[Question] how can i show alarm additional info to the dashboard ???

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8804]
**Component**

 * Rule Engine
 * Generic

**Description**
Hi I want to show the alarm addition info to my dashboard I am following this  link  [https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/](url)
i want to show total number of times alarm are created and show that on my dashboard
i am able to get alarm count inside the alarm addition info tab 
![image](https://github.com/thingsboard/thingsboard/assets/34526029/9aacbf78-4e41-4014-8ba0-a0cb15479391)
but failed to show the data on the dashboard as i follow the next step of showing this data on the dashboard

**Environment**

 * OS:  name and version
 * ThingsBoard: 3.5.1 PE
 * Browser: name and version

**Comment by devaskim** [comment]
At least alarm table widget can show such data by adding data key `details.temperature`

**Comment by securitylamb** [comment]
> At least alarm table widget can show such data by adding data key `details.temperature`
![image](https://github.com/thingsboard/thingsboard/assets/34526029/67b0af13-50b5-4fa2-b4b5-a093b8e68ba3)
I did that but still not getting the data

**Comment by devaskim** [comment]
![alarmtype](https://github.com/thingsboard/thingsboard/assets/86909129/053ffbe1-2671-40db-b58b-5c1de8deb28c)

**Comment by securitylamb** [comment]
ok i think that is what i did wrong can you share those keys

**Comment by devaskim** [comment]
> did you enter those as label
No, `details.temperature` is key

**Comment by securitylamb** [comment]
i am doing this way 
![image](https://github.com/thingsboard/thingsboard/assets/34526029/f1ed00b4-1a70-4a80-9de9-612c2c386aad)

what is this >>>>>
![image](https://github.com/thingsboard/thingsboard/assets/34526029/3df09986-f894-462f-9ab3-a20331f947fe)
mine did not have this can you explain me that

**Comment by devaskim** [comment]
I didn't remember how I did that, but I could create yet another Type or Severity field, that click on Edit button of that field and replace the value in Key field with `details.temperature`

**Comment by securitylamb** [comment]
brother can you share me the data key confrigation
![image](https://github.com/thingsboard/thingsboard/assets/34526029/8e5cc49b-7e35-41ca-8e66-a3933275e792)

**Comment by devaskim** [comment]
oh, you are so newbie, sorry) it is the same as yours

**Comment by devaskim** [comment]
![keyconf](https://github.com/thingsboard/thingsboard/assets/86909129/06798f80-6f54-4aa0-bb90-3811a17025ae)

**Comment by securitylamb** [comment]
you could just share that lol!

**Comment by devaskim** [comment]
> you could just share that lol!

I already did it before

![key](https://github.com/thingsboard/thingsboard/assets/86909129/23a96609-1b10-4dfa-993e-7f253d1da129)

**Comment by devaskim** [comment]
@securitylamb  So have you succeeded in getting details data?

**Comment by securitylamb** [comment]
@devaskim thanks yes I was able to get the alarm data but I have one more question can we get the alarm data outside alarm widget like can we get our alarm data inside the New Markdown/HTML Card widget ????? I am using this

**Comment by devaskim** [comment]
I guess no, but I didn't try. Alarm feature is a special set of API. Thigsboard doesn't even let you creating Alarm alias for dashboard

**Comment by securitylamb** [comment]
is there another way of sending these alarm detail to other widgets ???

**Comment by devaskim** [comment]
It would be easier to provide some useful information, if you describe what you want to implement on dashboard.

**Comment by securitylamb** [comment]
sure i want to show the total number of alarms generated for a device and show that on my widget

**Comment by devaskim** [comment]
If you use PE version, there is [Alarm Count API](https://demo.thingsboard.io/swagger-ui/#/entity-query-controller/countAlarmsByQueryUsingPOST) which you could call in CUSTOM widget.

**Comment by devaskim** [comment]
In CE version this could be done in Rule Engine by updating, for example, server device attribute as a count every time when new alarm appears or is cleared.

**Comment by devaskim** [comment]
There is no such API in rule chain. But how it relates to the original question about widgets?
