### ISSUE TITLE
[Question] Change in alarm table filter

### ISSUE THREAD

**Issue by bbrenne** [thingsboard/thingsboard#8805]
I recently updated on of our server from 3.2.0PE to 3.5.1PE and we noticed a change in alarm table filtering.

Before when we selected in the filter active and unacknowledged it displayed active alarms and unacknowledged alarms (making a sort of OR condition).

Now when we selected in the filter active and unacknowledged it displays only alarms that are active and unacknowledged (making a sort of AND condition).

It is a bug or was the previous behavior considered as a bug and the current situation to be considered normal?

**Comment by ssakharova** [comment]
Hello @bbrenne,

The thing is that in the current situation when you select an active and unacknowledged alarm in the filter, it displays only those alarms (making a sort of AND condition). This behavior has always existed, and it is considered normal.
