### ISSUE TITLE
[Bug] Cyclic relation issue using version control

### ISSUE THREAD

**Issue by TortueHardie** [thingsboard/thingsboard#8806]
Hello !

We have an issue with the version control (inside ThingsBoard and using the API).
We want to use the version control to export the configuration of the preprod server to the prod server.
So, we want to export a Tenant configuration, then import it in a newly created one so we can test the dashboard on this new tenant.
When we try to use the version control, to import the whole conf it doesn't work, because of the relations. It says "Failed to load the asset profile with external id '...' because it references missing rule chain with id '...' ".
We can restore everything else except the asset profile, then import the asset profile and it works but that's annoying (because we need to restore the conf two times). It's like the version control try to link entities before they are created. And we can't choose the order of the component that are restorated. We also finded that if two entities are related to each other, the version control can't happen because one need the other to be created and vice versa and that's a huge problem (if A is related to B and B is related to A, the version control says that B need to be created to create A, but when we want to create B, the version control says that A need to be created to create B).

Thanks for your help !

**Comment by devaskim** [comment]
The same problem in CE with dashboards and assigned customers.

**Comment by ViacheslavKlimov** [comment]
Version control resolves cyclic relations, but there is indeed an issue with asset profiles. We will fix this in the upcoming release.
