### ISSUE TITLE
[Bug] Version Control restore creates a NullPointerException

### ISSUE THREAD

**Issue by eluu47** [thingsboard/thingsboard#8807]
**Describe the bug**
When trying to restore a version from the version control page, the restoration fails with an error: "Failed: unexpected error (NullPointerException)"

**Your Server Environment**
* own setup
  * local infrastructure
  * 3.4.1 PE
  * Kubernetes Ubuntu 2.4

**Your Client Environment**

**Desktop:**

* OS: Windows 10
* Browser: Chrome
* Version 114.0.5735.134

**Your Device**

* Connectivity
  * Integration: IoT Hub

**To Reproduce**
1. Go to Version Control
2. Try to restore previous version
3. Get Error: "Failed: unexpected error (NullPointerException)" 

**Expected behavior**
Version gets restored.

**Additional context**

found this in the logs. It was thrown an hour before anyone in the team began to work on thingsboard.

```
INFO  o.t.s.s.s.v.DefaultEntitiesVersionControlService - [622070c0-cf06-11ed-b130-f7ce6900cd6b] Failed to process request [EntityTypeVersionLoadRequest(entityTypes={ASSET=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), DEVICE=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), ENTITY_VIEW=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), DASHBOARD=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), CUSTOMER=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), USER=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), DEVICE_PROFILE=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), RULE_CHAIN=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), WIDGETS_BUNDLE=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), CONVERTER=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), INTEGRATION=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true), ROLE=EntityTypeVersionLoadConfig(removeOtherEntities=false, findExistingEntityByName=true)})] due to: 
java.lang.NullPointerException: null
	at org.thingsboard.server.dao.owner.DefaultOwnerService.fetchOwnersHierarchy(DefaultOwnerService.java:128)
	at org.thingsboard.server.dao.owner.DefaultOwnerService.fetchOwners(DefaultOwnerService.java:195)
	at org.thingsboard.server.dao.owner.DefaultOwnerService.getOwners(DefaultOwnerService.java:159)
	at org.thingsboard.server.service.security.permission.DefaultOwnersCacheService.getOwners(DefaultOwnersCacheService.java:146)
	at org.thingsboard.server.service.sync.ie.exporting.DefaultExportableEntitiesService.belongsToTenant(DefaultExportableEntitiesService.java:186)
	at org.thingsboard.server.service.sync.ie.exporting.DefaultExportableEntitiesService.findEntityByTenantIdAndId(DefaultExportableEntitiesService.java:116)
	at jdk.internal.reflect.GeneratedMethodAccessor1016.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
```

**Comment by ban2derlog** [comment]
Hi,

According to error - during restoring ThingsBoard can't find parent entity and show this exception.
I assume that you trying restore some entities without restoring it's owner\parent.

If you had Customer hierarchy with sub-customers there can be also case with broken relations during importing.

Please, try to create a full Version import with all relations and try to restore it on new tenant.

**Comment by eluu47** [comment]
Hey ban2derlog, 

The Issue was, in fact, coming from a relation from an integration to a device, that we deleted. So when we tried to restore an integration it failed, since it couldnt restore that relation. 

So when a device gets deleted, it's relations from other entities dont get deleted along with it. Maybe it's an oversight, maybe it's on purpose, I'm not sure. I'm just letting you guys know :)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
