### ISSUE TITLE
[Question] Yarn build front-end ui-ngx independent success, but the widgets not showing at all.

### ISSUE THREAD

**Issue by sky007ca** [thingsboard/thingsboard#8809]
**Component**

 * UI

**Description**
Tried building front-end ui-ngx by "yarn build" command. After build, move public folder to ngnix to hold website. Works, but widgets not showing at all.
When I run ui from "yarn start", it works perfectly, widgets show up like normal.

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.4.2
 * Browser: chrome

**Comment by devaskim** [comment]
Maybe your ngnix blocks WebSocket connections? 

`yarn start` uses [proxy.conf.js](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/proxy.conf.js), maybe this will help your

**Comment by sky007ca** [comment]
It is so wired. I can confirm my ngnix forward webstock correctly. 
And today I find something, but I cannot understand. I hope you can give me some suggestion.
First, I build front-end by "yarn build" command. The result is same, widgets cannot load.
Second, I build whole project by "mvn clean install -DskipTests", the get the front-end files from target folder for nginx. It works, widgets loading no problem.

Somehow, yarn build is differen with maven build. How wired?
