### ISSUE TITLE
[Question] Refresh Dashboard after update.

### ISSUE THREAD

**Issue by elpollo12** [thingsboard/thingsboard#8815]
**Component**

 * UI

**Description**
I am using the method `self.ctx.dashboardService.saveDashboard` to update a dashboard from a custom widget. The changes are saved correctly, however I must manually update the entire url to see the changes. Anyone any method I should use after the saveDashboard to see the changes immediately without refreshing? 

The changes I am making is to add from another widget the dataKeys to a time series chart.

I used:

```
self.ctx.updateWidgetParams();
self.ctx.detectChanges();
```

**Environment**
 * OS:  Ubuntu Server
 * ThingsBoard: 3.5.1 PE
 * Browser: Firefox

**Comment by jsalazarplv** [comment]
I am having this same problem, any updates yet?

**Comment by elpollo12** [comment]
I found a workaround using angular router; but it's not elegant

```
self.ctx.dashboardService.getDashboard(
            'dashboardId'
        ).subscribe(
            function(
                data) {
                let dashboard = data;
                let newTagsArray = [...dashboard
                    .configuration.widgets[
                        'widgetId'
                    ].config
                    .datasources[0]
                    .dataKeys, ...self.ctx
                    .$scope.vars
                ]
                dashboard
                    .configuration.widgets[
                        'widgetId'
                    ].config
                    .datasources[0].dataKeys =
                    newTagsArray;
                self.ctx.dashboardService.save;
                self.ctx.dashboardService
                    .saveDashboard(
                        dashboard).subscribe(
                        function(
                            data) {
                            if (data) {
                                self.ctx.router
                                    .routeReuseStrategy
                                    .shouldReuseRoute =
                                    function() {
                                        return false;
                                    }
                                self.ctx.router
                                    .onSameUrlNavigation =
                                    'reload';
                                self.ctx.router
                                    .navigateByUrl(
                                        '/iframeView?stateId=loading&dashboardId=dashboardId&hideDashboardToolbar=true&setAccessToken=true', {
                                            skipLocationChange: true
                                        }).then(
                                        () => {
                                            self.ctx
                                                .router
                                                .navigate(
                                                    [
                                                        'dashboards/dashBoardId'
                                                    ]
                                                );
                                        });
                            }
                            const $injector =
                                self.ctx.$scope
                                .$injector;
                            const
                                broadcastService =
                                $injector.get(
                                    self.ctx
                                    .servicesMap
                                    .get(
                                        'broadcastService'
                                    ));
                            broadcastService
                                .broadcast(
                                    'set_tag',
                                    data);
                        });
```

**Comment by elpollo12** [comment]
Hello @devaskim. You know about reload a dashboard from custom widget? I use a saveDashboard function but the changes are not availables in real time (only if refresh the page). Thanks

**Comment by devaskim** [comment]
I think there isn't any other solution. But what is a purpose of adding another data key? Does it belong to the same entity or another?

**Comment by elpollo12** [comment]
> I think there isn't any other solution. But what is a purpose of adding another data key? Does it belong to the same entity or another?

Thanks for your answer @devaskim . 

![panel](https://github.com/thingsboard/thingsboard/assets/7535800/1cd88b98-6037-4da9-9eab-84cced7e4c5c)

The dashboard I show in the image consists of 3 widgets. The 1 is a selector of telemetry variables of a device. #2 handles the date range to be displayed and I can advance within that range and #3 is a timeseries graph where I show the data and I can eliminate variables and change color. 

I add those changes to the dashboard widget array (which I get previously). For example if I add or remove a variable to the graph from widget 1, i make a saveDashboard with the new data.

After that I want find a way  to take the changes without refresh the page.

**Comment by EdikCarlos** [comment]
have you tried using widgetContext.defaultSubscription.updateDataSubscriptions() ?

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by icoco** [comment]
how to force refresh dashboard ?
