### ISSUE TITLE
[Bug] State label in device table should consider enabled PERSIST_STATE_TO_TELEMETRY server option

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8817]
![state](https://github.com/thingsboard/thingsboard/assets/86909129/2d760b54-76f4-4ab9-8530-1bf13ce2db57)

**Comment by devaskim** [comment]
I doubt

**Comment by databang-io** [comment]
Why is this closed then ? I have the same isue in 3.5.1

**Comment by devaskim** [comment]
From my discussion experience in TB forum, it almost doesn't affect on how quickly this issue will be solved. 

Once someone from TB core team stated in some other thread that they open issue in their internal bug tracker and prioritized it. But unfortunately, we don't know when a fix for some of bugs opened by community will be released.

**Comment by gzcsschen** [comment]
i get the same question，how can do it Works normally

**Comment by xiddjp** [comment]
May I ask which submission fixed this issue?
