### ISSUE TITLE
What are TB's successful business applications?

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#882]

**Comment by vparomskiy** [comment]
Could you please describe what information you want to find?

**Comment by BIT-masterpy** [comment]
Application in industrial manufacturing (aviation manufacturing is better)，We have a lot of industrial equipment and we want to improve the efficiency of production through the industrial Internet of things.But lack of relevant experience

At 2018-06-20 17:41:55, "vparomskiy" <notifications@github.com> wrote:


Could you please describe what information you want to find?

**Comment by egeong** [comment]
I think metering energy farming and fleet tracking all are successful cases.
[](https://thingsboard.io/iot-use-cases/)
