### ISSUE TITLE
[Question] how to minimize processing errors when sending bulk data ???

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8822]
**Component**

 * Rule Engine
 * Generic

**Description**
here I am trying to send bulk data from the memory which cause it to go to permanent failure what do you think is causing the issue  for the bulk data i am making the list or group of 10 timestamp data how can I minimize this  so none of my data is lost 
![image](https://github.com/thingsboard/thingsboard/assets/34526029/a10831c0-6ef7-4d21-b86d-cd5513c9b826)

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.5.1 PE
 * Browser: name and version

**Comment by devaskim** [comment]
Maybe [this guide](https://thingsboard.io/docs/user-guide/troubleshooting/?scenario=growing-latency) will help you

**Comment by ban2derlog** [comment]
Hi,
Check ThingsBoard logs for errors during this spike - /var/log/thingsboard/

Additionally, describe your deployment - resources, queue type, database type, js executors, etc
This can be caused by insufficient resources for these requests, or wrong logic in Rule Chains.

**Comment by securitylamb** [comment]
@ban2derlog 

I hosted this on linode basic server 
2 CPU Cores
80 GB Storage
4 GB RAM

i am using the default queue -> Main 
database is postgres 
this kind of issue arise when I try to send bulk data in grouping to the server

**Comment by securitylamb** [comment]
i resolve this issue by using TBLE  and test  individual  rule chain for  any timeouts
