### ISSUE TITLE
[Question] how to assign chart to a dynamic device

### ISSUE THREAD

**Issue by TiannV** [thingsboard/thingsboard#8838]
**Component**

 * UI

**Description**
 i have two dashboard state 
![image](https://github.com/thingsboard/thingsboard/assets/36880544/1a427e77-32a2-429b-80a1-0c1d18bc734c)
![image](https://github.com/thingsboard/thingsboard/assets/36880544/f2da5a46-21d3-40aa-8872-cae00a7182d5)
 how to assign chart to a dynamic device

**Comment by devaskim** [comment]
For chart user alias called [Entity from dashboard state](https://engix-ltd.github.io/docs/user-guide/ui/aliases/#entity-from-dashboard-state).

**Comment by TiannV** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/36880544/3ac8732b-b0e5-4467-9d97-8abaacab8566)
![image](https://github.com/thingsboard/thingsboard/assets/36880544/ca87e85e-f251-4cfd-88e6-ce4d8bf0a793)
![image](https://github.com/thingsboard/thingsboard/assets/36880544/dae2bdba-a3d1-4f41-b285-63d4f601d95a)

**Comment by devaskim** [comment]
Chart doesn't provide such feature out of the box

**Comment by Ultrazombie** [comment]
Closed due to inactivity
