### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by MirFei** [thingsboard/thingsboard#8840]
Import org. thingsboard. server. common. msg. gen. MsgProtos; The above dependencies are missing in version 3.5.1 code

**Comment by MirFei** [comment]
Can you upload the gen folder?

**Comment by devaskim** [comment]
`gen` means `generated`, so you should build the project to get this folder. See [this doc](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)

**Comment by MirFei** [comment]
> `情报`方法`生成的`，所以您应该构建项目来获得这个文件夹。看见[这个医生](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)
I have a new question that I would like to consult with you。Is there a solution for both the 'since' and 'forRemoval' annotations marked in red?
![111](https://github.com/thingsboard/thingsboard/assets/124227890/400d88b0-106c-4852-867c-c05ff0ad5f26)

**Comment by devaskim** [comment]
Not sure, but maybe your global IDEA or project configuration uses wrong JDK version

**Comment by Ultrazombie** [comment]
Closed due to inactivity
