### ISSUE TITLE
[Question] File loss

### ISSUE THREAD

**Issue by wqhyx** [thingsboard/thingsboard#8842]
Java: package org.thingsboard.server.com mon. MSG. Gen does not exist

**Comment by wqhyx** [comment]
The MsgProtos file is missing

**Comment by devaskim** [comment]
@wqhyx It is not a chat where you could posting each your thought in a separate message. Please, respect community and provide meaningful title.

Regarding to your problem, I think [this docs section](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/) will help you

**Comment by wqhyx** [comment]
Sorry, pay attention next time, the problem has been solved, thank you for your help.
