### ISSUE TITLE
[Question] When do I need to push the return value of the data converter?

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#8848]
HI.

Below is a sample converter as described by TB Integration.
I would like to know why the object is "result.push" here.
In the template provided by TB's Data Converter, it is simply "result" and not "result.push".
I would like to know why it is necessary to push to an object array.

// decode payload to JSON
var data = decodeToJson(payload);
var result = [];
for (var i = 0; i < data.length; i++) {
    var report = data[i];
    var deviceName = report.serialNumber;
    var deviceType = metadata.deviceType;
    var raw = report.value;
    var decoded = hexStringToByte(raw);
    // Result object with device attributes/telemetry data
    **result.push**({ 
        deviceName: deviceName,
        deviceType: deviceType,
        attributes: {
            model: metadata.model
        },
        telemetry: {
            ts: report.timestamp,
            values: {
                battery: dataConverter(decoded, 0, 2, 100),
                temperature: dataConverter(decoded, 2, 4, 100),
                rawData: JSON.stringify(report)
            }
        }
    });
}

**Comment by trikimiki** [comment]
In this example, `result` is not really an object here - it is an array:
```var result = [];```
Here is why you can (and probably should) use the [push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) method.

In other examples, `result` is actually defined as an object, e.g.:
```// Result object with device attributes/telemetry data
var result = {
    //some data here
};
```

**Comment by h-takado** [comment]
trikimiki san

Thank you!
You're absolutely right.
I am a bit tired, I think.
