### ISSUE TITLE
Widgets should push its other down when editing a dashboard

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#885]
Hi

I have a dashboard I created, with few card widgets and time-series widgets.

![image](https://user-images.githubusercontent.com/31729091/41715609-acce01f4-755c-11e8-9423-a8d26b9dcf67.png)

Now I want to add a new card widget at the top, but I am unable to do it without moving all the widgets down one by one, and even that is tricky because scrolling up or down does not work when dragging around a widget.

![image](https://user-images.githubusercontent.com/31729091/41715417-0dc40770-755c-11e8-8645-44aa99cea97c.png)

my suggestion, and how I have seen it done, is that when hovering over another widget, while dragging a widget, it will push the widget down.

Is there another solution that I am not seeing here?

**Comment by ban2derlog** [comment]
Good day, does issue persist on latest ThingsBoard version?

**Comment by t0mZ4** [comment]
@ban2derlog yea this issue still exists. When you want to add a widget, at the top of an existing dashboard, you need to manually make room for it by resizing, moving down other widgets. Where a preferred behavior will automatically make room for the widget you are dragging.

**Comment by ban2derlog** [comment]
Thank you for your suggestion; this is a valid improvement of our platform, so I've added this request to our backlog (PROD-1546) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
