### ISSUE TITLE
[Question] max pending limit reached 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8850]
**Component**

 * Generic

**Description**
I started getting this error on my dashboard what could be the cause of it  as I am not sure what is causing this error 

**Environment**

 * OS: UBUNTU 
 * ThingsBoard: 3.5.1 PE 
 * Browser: BRAVE

**Comment by trikimiki** [comment]
Could you send a screenshot or text of the error?
Most likely, you hit a rate limit (e.g. by refreshing the dashboard page in browser a lot)
https://thingsboard.io/docs/user-guide/api-limits/

**Comment by securitylamb** [comment]
as there are no new updates regarding this issue I am marking it as  completed
