### ISSUE TITLE
[Question] How to get list of connected device by gateway

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8851]
@imbeacon @ashvayka Is there any database table / server log trace or somethings what could tell what devices did gateway connected during current MQTT session?

If there is no such information, could you point me out where I can put log message in the server code? Then I will rebuild and test again. Thanks in advance

**Issue**
From the TB 3.3 till 3.5.1 we have been observing that after some uptime server stops sending shared attributes / server side RPC to the connected device via gateway topics called `v1/gateway/attributes` and `v1/gateway/rpc` correspondingly (no TCP packets in WireShark). At the same time gateway pushes telemetry of that connected devices with the fix rate (15 min). `active` attribute of each device is `true` and `inactivityTimeout` is 10800000 ms (3 hours)

**Comment by devaskim** [comment]
@ashvayka  @imbeacon If there is no such information, could you point me out where I can put log message in the server code? Then I will rebuild and test again. Thanks in advance

**Comment by devdoob** [comment]
Why you closed it? Got any solution?

**Comment by devaskim** [comment]
> Got any solution?

No

> Why you closed it?

Because the issue is useless after month of silence.
