### ISSUE TITLE
Rules engine related issues

### ISSUE THREAD

**Issue by mengGod129** [thingsboard/thingsboard#8855]
In the rule chain
purpose :only when the telemetry data changes can we proceed to the next node
How do I achieve this

**Environment**

 * OS:  macos
 * ThingsBoard: 3.5.1
 * Browser: Google Chrome

**Comment by Backdraft007** [comment]
Can you explain your problem with more details. I don't understand what you want to achieve.

**Comment by mengGod129** [comment]
> 

In the rule chain, the next node is triggered only when the device telemetry data changes

**Comment by mengGod129** [comment]
How can this be achieved? I want the next node not to be triggered when the telemetry data has not changed.

**Comment by Backdraft007** [comment]
Sorry, I misunderstood you,
I think it is not the sense and purpose of telemetry data.

Maybe you can build a workaround with an attribute. You can compare the telemetry data with the attribute data. If its equal do nothing and it its not equal, save the data in the attribute and go to the next node.

**Comment by mengGod129** [comment]
> 抱歉，我误解了你的意思， 我认为这不是遥测数据的意义和目的。
> 
> 也许您可以使用属性构建解决方法。您可以将遥测数据与属性数据进行比较。如果确定且不一致，则将数据保存在属性中并转到下一个节点。

Thank you very much. Can the device telemetry data update time be changed? Now every 5 seconds

**Comment by mengGod129** [comment]
> Sorry, I misunderstood you, I think it is not the sense and purpose of telemetry data.
> 
> Maybe you can build a workaround with an attribute. You can compare the telemetry data with the attribute data. If its equal do nothing and it its not equal, save the data in the attribute and go to the next node.

Thank you very much. Can the device telemetry data update time be changed? Now every 5 seconds

**Comment by Backdraft007** [comment]
That depends on your device. The device sends telemetry in a configured interval.
