### ISSUE TITLE
what is the javascript code for  fetching JSON data ( server attribute ) through transformation node in thingsboard rulechain

### ISSUE THREAD

**Issue by kpakhi** [thingsboard/thingsboard#8857]
These JSON data is in present in the metadata  & i have to the fetch device name 

{
  "total_devices": 3,
  "currently_Actice": 0,
  "temp_sensor1_details": {
    "device_name": "newdevice",
    "device_id": "d5ff4040-068b-11ee-8f2d-15183b8343a4",
    "temperature_status": 0
  }
}

**Comment by devaskim** [comment]
`var deviceName = JSON.parse(metadata).temp_sensor1_details.device_name;`
