### ISSUE TITLE
[Feature Request] Time Window: Month grouping interval

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8858]
**Is your feature request related to a problem? Please describe.**
As a user I want to get chart with monthy energy consumption. Now it is possible to group data by 30 days which is not a month.

**Describe the solution you'd like**
Provide a new time window option that lets show data grouped by month taking into account leap year.

**Comment by nadeda** [comment]
did make this function?

**Comment by devaskim** [comment]
@nadeda  no

**Comment by NistantriTech-Dhaval** [comment]
+1

**Comment by devaskim** [comment]
@nadeda Hopefully I am wrong. But I am not sure if ever feature requests opened in Github Issues are interesting for Thingsboard team. For the past year I provided a lot of ideas (requests), but no reaction, no implemented features....

**Comment by nadeda** [comment]
After analyzing the code, I found that monthly grouping was not easy. Internally, it is calculated by converting to seconds, but in order to actually implement the month grouping function, it seems that it will be faster to create a new function than the existing structure.
