### ISSUE TITLE
Any plans to upgrade to newer Angular Material version?

### ISSUE THREAD

**Issue by BatListener** [thingsboard/thingsboard#886]
I think, the current angular-md version used by TB is 1.1.1.
For widget development, I am faced with a minor problem with that angular-md version.
The md-datepicker does not scroll automatically to the selected date.
See [https://github.com/angular/material/issues/9952](url)

Any plans to upgrade to a newer version of angular-md in the near future?

Again: Just a minor problem so far.
It is more a general question on when we can expect an upgrade.
There might be other benefits to upgrade, too.

**Comment by mp-loki** [comment]
Answered [here](https://github.com/thingsboard/thingsboard/issues/780) There is no such plans now because it will be too much effort.
