### ISSUE TITLE
[Question] Change REST API Authorization to allow CUSTOMER_USER access to some information

### ISSUE THREAD

**Issue by yohnnylim** [thingsboard/thingsboard#8863]
**Component**

 * REST API

**Description**
Changing the authorization of REST API to allow CUSTOMER_USER to access some data.
Hi, I would like to change the authorization of a certain REST API to allow my CUSTOMER_USER to get some info from the tenant which is currently only available to SYS_ADMIN and TENANT_ADMIN only, is there a way I can change the authorization on the REST API to allow CUSTOMER_USER to access the information?

**Environment**

 * OS:  Windows 10
 * ThingsBoard: 3.4.1
 * Browser: Microsoft Edge

**Comment by devaskim** [comment]
There is no such configuration option. Only code patching, if you use CE version.

**Comment by yohnnylim** [comment]
could you please point me to the location to the codes to be patched? I tried editing this file in /application/src/main/java/org/thingsboard/server/controller/TenantController

I changed the @PreAuthorized content but the api still would not allow CUSTOMER_USER to call it

**Comment by devaskim** [comment]
1. PreAuthorize annotation in each controller what you need.
2. CustomerUserPermissions.java (get proper permissions from SysAdminPermissions.java and TenantAdminPermissions.java)

**Comment by yohnnylim** [comment]
Hi @devaskim , thanks for the info, its working! Problem solved!

1. I've added CUSTOMER_USER to the controller under @PreAuthorized
2. Added permission to the CustomerUserPermissions.java
