### ISSUE TITLE
[Question] How to restore data from github

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#8865]
hi.
in other server i create dashboard and customer ...
i need to restore data from github repository in new server.
When I click on restore, the following error is displayed.
`Failed to load the device with external id 31b2fa70-e3f1-11ed-987d-75263dc68596
because it references missing customer with id 656d1220-e3eb-11ed-987d-75263dc68596.`

**Comment by devaskim** [comment]
Unfortunately, version control feature is yet inconvenient.

The error means that your device github dump has customerId field, in other words, it was assigned to some customer on a previous server. As of 3.5.1 TB cannot ignore this field on restoring stage. So here are some alternatives:
- restore customer with this id
- edit device's github data by replacing data in customerId field with data specified in tenantId field
- create customer with such id (not sure how)

**Comment by ssakharova** [comment]
Close due to inactivity.
