### ISSUE TITLE
Time out error while posting large amount of telemetries and using REST API

### ISSUE THREAD

**Issue by jeansey** [thingsboard/thingsboard#887]
We are using thingsboard 2.0.3 with a Cassandra database

How to reproduce the error : 

- Create a device calling REST API "/api/device" with following JSON parameter : {'name': u"L'Isle-Jourdain", 'type': 'Vigicrues'}
- Post telemetries to this device using REST API "/api/v1/my_device_token/telemetry" (we post a large amount of telemetries in one single request, see attached json file to get the json document sent to this service)
[telemetries.txt](https://github.com/thingsboard/thingsboard/files/2123895/telemetries.txt)

Result : the service takes a large amount of time to respond, and end with the following time out error : 408 {"error":"Timeout during persistence of the message to the queue!"}

**Comment by vparomskiy** [comment]
1. Could you please share your log file
2. Did you make any changes in the Rule Chains? Are there any custom nodes for data transformation or enrichment?
3. What instance is used for the Thingsboard and Cassandra (CPU/RAM)?

**Comment by jeansey** [comment]
Here is our log files : 
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2124048/thingsboard.log)
[thingsboard.out.log](https://github.com/thingsboard/thingsboard/files/2124055/thingsboard.out.log)

We didn't changed the Rule Chains. We had previous rules before migration from v1.4 to v2.0.3 but they are automatically delete if we understood well the migration process.
Here are screenshots of our rule chains : 
![rulechains1](https://user-images.githubusercontent.com/39619693/41727646-1c7489de-7575-11e8-9cd6-a8de1d854136.png)
![rulechains2](https://user-images.githubusercontent.com/39619693/41727651-20254cf8-7575-11e8-8e53-04d7d5068724.png)

Thingsboard and Cassandra are running on the same instance : a Virtual Machine with 8cpu and 16Go RAM
![serverressources](https://user-images.githubusercontent.com/39619693/41727829-94132126-7575-11e8-937c-c2f2662e6a53.png)

You can check the java options we set for those processes : 
[javaOptions.txt](https://github.com/thingsboard/thingsboard/files/2124183/javaOptions.txt)

**Comment by geonux** [comment]
We are facing a similar problem. In version 1.4.x, we already had a problem of slowness which produced the freeze of the whole web service. We migrated from Postgres to Cassandra, which solved the problem.

We have just migrated to version 2.x to take advantage of the latest advances with rules chain. Unfortunately all insertion are now very slow (on the REST api - more than 10x slower), and ultimately produce a complete freeze of the web application.

Any solutions? Maybe it's just a configuration problem.

**Comment by BatListener** [comment]
Same problem here (with 2.1.0 and may be earlier), using MQTT instead of REST.

Similar problem here.
Devices are storing large amount of telemetry messages stored in client's persistent storage while in disconnected state (using PAHO MQTT C client library). When the device client re-connects to the TB MQTT, the first few hundred persistent messages are sent successfully to the server and removed from the client's persistent storage. The remaining messages will be answered by TB with

{"error":"Timeout during persistence of the message to the queue!"}

and will not be removed from the client's persistent storage (which is correct and good!).
During next re-connect, the next couple of hundreds messages can be successfully transferred...
Can be quite a lengthly process to get rid of the messages, but at least no data ist lost.

Any thoughts on how to avoid the timeout on the server side?

**Comment by vparomskiy** [comment]
**Short answer:**
Please increase **actors.rule.queue.max_size** property in the **thingsboard.yml** file to a higher value. For example, set it to 10000.

**Long answer:**
When device submit messages to the Thingsbaord (telemetry/attributes/RPC), by default, all messages are saved in the Queue. After messages are saved, they are passed to the Rule Engine for processing and response is generated for the Device. As you see, processing inside Rule Engine is asynchronous and we need to guarantee that if a device receives '200 OK' from the Thingsboard, the message will be processed.
The queue is cleared after message processing is finished.
When a batch of messages is submitted it is saved in the queue as N separate messages.
We limit the concurrent number of messages in the Queue for single Tenant. Default max value is 100.
So when 2 batches are submitted from a single tenant with the size for each batch = 60. Message queue will reject some part of those messages and the device will receive an error.

**Comment by BatListener** [comment]
Thanks for the excellent explanation!
Appreciate it!

**Comment by vparomskiy** [comment]
More details can help with investigation

**Comment by chatper** [comment]
@vparomskiy Is there any way to observe the Queue's state? Also, can we change the default max value for the concurrent messages per Tenant via configuration or is this not exposed?

**Comment by vparomskiy** [comment]
In the current version, it is not possible.

**Comment by vparomskiy** [comment]
contributions are welcome

**Comment by JPB22** [comment]
Increasing the actors.rule.queue.max_size did not help. I get the following error...

2018-11-21 05:05:52,380 [pool-23-thread-6] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -104, SQLState: 23505
2018-11-21 05:05:52,381 [pool-23-thread-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - integrity constraint violation: unique constraint or index violation; TS_KV_UNQ_KEY table: TS_KV

Attached is the thingsboard.log file.

Any suggestions?

[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2603253/thingsboard.log)

**Comment by vparomskiy** [comment]
It looks like your system is not able to handle generated load, so I have a couple of questions: 

1. First question - what version are you using (PE or community edition?)
2. I see that you are using SQL data storage. Is it HSQLDB or Postgres?
3. What instance is used (OS, CPU, RAM, system load)?

**Comment by vparomskiy** [comment]
This thread is not active anymore. Closing an issue.

**Comment by ChristineChetty** [comment]
> **Short answer:**
> Please increase **actors.rule.queue.max_size** property in the **thingsboard.yml** file to a higher value. For example, set it to 10000.
> 
> **Long answer:**
> When device submit messages to the Thingsbaord (telemetry/attributes/RPC), by default, all messages are saved in the Queue. After messages are saved, they are passed to the Rule Engine for processing and response is generated for the Device. As you see, processing inside Rule Engine is asynchronous and we need to guarantee that if a device receives '200 OK' from the Thingsboard, the message will be processed.
> The queue is cleared after message processing is finished.
> When a batch of messages is submitted it is saved in the queue as N separate messages.
> We limit the concurrent number of messages in the Queue for single Tenant. Default max value is 100.
> So when 2 batches are submitted from a single tenant with the size for each batch = 60. Message queue will reject some part of those messages and the device will receive an error.

I tried to find actors.rule.queue.max_size in thingsboard.yml, cannot find it. Please advise which parameter this has been replaced with in v3.1.1PE
