### ISSUE TITLE
[Question] Can I edit existing widgets?

### ISSUE THREAD

**Issue by VukasNikola** [thingsboard/thingsboard#8871]
Hello, I'm a student who doesn't know a lot of things about how ThingsBoard /javascript works but I need a bit of help. I have a task of developing an interface for our class dashboard and I would like to modify the existing "update shared integer attribute" widget. Is this possible? Or do i have to make a completely new widget from scratch to do this? Thank you for the help!

**Comment by Backdraft007** [comment]
Depending on what you want to do, you can modify the widget in the widgets library and save it as new widget.

**Comment by VukasNikola** [comment]
I would like to make a drop down menu with preset options that will then change the attribute. I would also like to set the options to be a string. Do you think that would be possible?  

Something like this:

![IMG_0312](https://github.com/thingsboard/thingsboard/assets/110349322/17edea72-2046-4670-914a-ab2c18c350a0)

**Comment by Backdraft007** [comment]
Have a look at the "Update multiple attributes" widget.  There you can make the input field as select.
When it is enough for you, you don't have to develop an own widget.
![grafik](https://github.com/thingsboard/thingsboard/assets/8741669/6fd8f65f-d298-4c03-b5a2-4402292f7cab)

**Comment by VukasNikola** [comment]
Thank you good sir!
