### ISSUE TITLE
[Question] How to retrieve attribute name for custom widget?

### ISSUE THREAD

**Issue by jabr0ni** [thingsboard/thingsboard#8874]
**Component**

 * UI

**Description**
I am trying to retrieve an attribute name in HTML by calling a javascript in scope function called `AttributeName` however I keep being returned ctx.AttributeName is not a function in the widget window. I thought that  this is because the html is being loaded first before the javascript, so I added `ng-if="AttributeName"` in the html however no luck. What am I doing wrong here?

My JS and Angular knowledge is limited and I come from a C/C++ background. Trying to do as much as I can until we find a good JS dev :) 

HTML where I am calling AttributeName
```
    <thead ng-if="AttributeName">
		<tr>
		    <th colspan="4">{{ AttributeName(0) }}</th>
		</tr>
	</thead>
```

Javascript
```
self.onInit = function() {

    var $scope = self.ctx.$scope;
    $scope.AttributeName = function(index) {
        return $scope.ctx.data[0].datasource.name;
    };
}
```

**Environment**

 * OS:  Win 11
 * ThingsBoard: 3.5.1
 * Browser: Chrome 114.0.5735.199

**Comment by devaskim** [comment]
```
    <thead>
		<tr *ngFor="let item of ctx.data">
		    <th colspan="4">{{ item.datasource.name }}</th>
		</tr>
	</thead>
```

**Comment by Ultrazombie** [comment]
Closed due to inactivity
