### ISSUE TITLE
[Question] Thingsboard PE any way to limit self register customer device creation 

### ISSUE THREAD

**Issue by NistantriTech-Dhaval** [thingsboard/thingsboard#8876]
**Component**
 * Generic

**Description**
Does thingsboard PE have option to configure max devices can created by the customer?
I can see for tenant there is option in tenant profile to limit number of entities for the tenant

**Comment by ssakharova** [comment]
Hello @NistantriTech-Dhaval,

In the thingsboard PE, there is an option to configure a maximum number of entities for tenants while configuring the tenant profile on the Sysadmin level. 

However, there isn't an option to limit the number of entities customers can create.

Best regards,
Sofiia
