### ISSUE TITLE
How to pop up a layer in the map, for information input

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#8877]
**Component**

 * Generic

**Description**
![image](https://github.com/thingsboard/thingsboard/assets/19941827/b94fce38-352e-462c-a286-f536bead592c)

How to locate the device on the map on the right after the left alarm is selected and pop up a layer for counting in relevant information

**Environment**

 * OS:  windows 10
 * ThingsBoard: 3.5.1
 * Browser: chrome

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
