### ISSUE TITLE
[Feature Request] Telegram Notifications

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8885]
**Describe the solution you'd like**
As a user I want to be notified via Telegram ([Bot API](https://core.telegram.org/bots/api)).

From a configuration perspective we need to things: bot token and so-called `chat_id`. The former could be set in the same way as it is already implemented for Slack. To get the latter there are [several ways](https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id), but eventually it could be user's server attribute.

**Comment by Backdraft007** [comment]
Hi,
while I searched another topic in the documenation, I found this:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/integration-with-telegram-bot/

**Comment by devaskim** [comment]
Thanks @Backdraft007 I meant the same by out of the box as much as possible.
