### ISSUE TITLE
[Bug] When selecting "This Year" with monthly aggregation, and "Calculate Delta" option, Trendz also displays December of last year.

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#8891]
**Describe the bug**
When selecting "This Year" with monthly aggregation, and "Calculate Delta" option, Trendz also displays December of last year.

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
Thingsboard 3.5.1PE, Trendz 1.10.2-RC2
  * OS Name and Version
Ubuntu 

**To Reproduce**
1. Create a new bar chart in trendz
2. Select "this year" as time frame and monthly aggregation
3. Choose any telemetry and select "calculate delta"
4. Generate report
5. Notice that december of last year is also present

**Expected behavior**
When I select "this year" I only see data from this year

**Screenshots**
<img width="993" alt="image" src="https://github.com/thingsboard/thingsboard/assets/88675613/94ca8586-ff7b-4d42-93e1-47672208a515">

**Comment by trikimiki** [comment]
Hello,

Thanks for reporting this issue! I forwarded this to the Trendz dev team, and they replied that they are already working on fixing this. Expect the fix in the nearest releases.

I will close the ticket, as it does not relate to ThingsBoard. Please feel free to email Trendz contact person (e.g. dmatvienko@thingsboard.io) in case you have any other Trendz-related questions.

**Comment by Eric-Ruud** [comment]
Thank you Mykhailo!
