### ISSUE TITLE
[Question] For calculated fields in Trendz, the delta() function doesn't seem to work. What am I doing wrong? 

### ISSUE THREAD

**Issue by Eric-Ruud** [thingsboard/thingsboard#8892]
**Component**

* Trendz calculated fields

**Description**
I am attempting to use calculated fields to determine inverter production for a solar inverter. I think I need to do the following (in either order, neither seems to work)
1. Divide WH values by 1000 convert WH to kWh
2. Calculate deltas and sum them to determine the total change per inverter. 

I can calculate deltas without using calculated fields, but I can't also divide by 1000. So I try to use the delta() function in the Javascript IDE, but it returns an error: "delta is not defined in <eval>  in line 1.

<img width="1188" alt="image" src="https://github.com/thingsboard/thingsboard/assets/88675613/8750440f-97eb-4354-b548-158198850153">

Am I doing something wrong here? According to the documentation this function should exist, but there isn't any detail about how to use it.

Is there another way to accomplish my goal? 

** own setup
cloud or local infrastructure or docker deployment
ThingsBoard Version
Thingsboard 3.5.1PE, Trendz 1.10.2-RC2
OS Name and Version
Ubuntu

**Comment by yuliaklochai** [comment]
Hi!
You can accomplish your goal using batch calculations. For example, using the next code you can calculate delta and transform your telemetry:
```
var energyList = none(EM energy meter.energyConsAbsolute);
var energyListDelta = [];

for(var i = 0; i < energyList.length; i++) {
    if(i !== 0) {
        var delta = energyList[i].value - energyList[i - 1].value;
        energyListDelta.push({ts: energyList[i].ts, value: delta / 100});
    }
}

return energyListDelta;
```
![image](https://github.com/thingsboard/thingsboard/assets/92470819/c5032151-aefc-485d-a482-e6539fed68b4)

**Comment by lddlala1** [comment]
Hi, I used this code. But it still not worked. Can you help me ?
![image](https://github.com/thingsboard/thingsboard/assets/97032347/3909b9ce-c6f9-422b-a36c-04782f956868)

**Comment by lddlala1** [comment]
> using batch calculations

I used batch calculations. But it not worked.
![image](https://github.com/thingsboard/thingsboard/assets/97032347/2c57d4c0-f3cf-4ad8-9e14-49205c779327)

**Comment by batslay** [comment]
> Hi! You can accomplish your goal using batch calculations. For example, using the following code, you can calculate delta and transform your telemetry:
> 
> ```
> var energyList = none(EM energy meter.energyConsAbsolute);
> var energyListDelta = [];
> 
> for(var i = 0; i < energyList.length; i++) {
>     if(i !== 0) {
>         var delta = energyList[i].value - energyList[i - 1].value;
>         energyListDelta.push({ts: energyList[i].ts, value: delta / 100});
>     }
> }
> 
> return energyListDelta;
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/92470819/252920887-c5032151-aefc-485d-a482-e6539fed68b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDI5NTUsIm5iZiI6MTcxMDIwMjY1NSwicGF0aCI6Ii85MjQ3MDgxOS8yNTI5MjA4ODctYzUwMzIxNTEtYWVmYy00ODVkLWE0ODItZTY1MzlmZWQ2OGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDAwMTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MWQ4ZTU1ZGQ5Zjc3NGJmNmY4MTVhYjdiMTU5YTMxOGQ5NWEyYTk3OTMwM2RhMjgxNDdlZWE3YzA4OWUxYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RB3RTzpHOHuY5Cjwv02p-UUzW2xXkeIhAFrlt_WLTqk)

Hello, can you show the whole screen of the batch calculation?
Thanks

**Comment by yuliaklochai** [comment]
Hi!
Sure, here is my calculation field for getting delta:
![image](https://github.com/thingsboard/thingsboard/assets/92470819/eca5363e-cd46-438f-b025-7e0a846f04f1)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
