### ISSUE TITLE
[Question] Power Bi report integration

### ISSUE THREAD

**Issue by zsofip** [thingsboard/thingsboard#8895]
**Component**

 * UI

**Description**
Is it possible to display a Power Bi report in a widget, eg. in an iframe or so? Has anybody tried to integrate Power Bi into a Thingsboard widget?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
