### ISSUE TITLE
Retrieving values from thingsboard devices

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#8899]
I tried to pull telemetry data from thingsboard devices via API. But i am not able to retrieve the data. The api url i used was in the format:
https://thingsboard-instance-url/api/v1/DEVICE/device id/timeseries

also i used the following headers:
Content-Type: application/json
X-Authorization: Bearer{access-token}
But thingsboard is not responding to this request. Kindly suggest where i made the mistake.

**Comment by Civilduino** [comment]
Check the Swagger UI for proper calling the API https://thingsboard.io/docs/reference/rest-api/

**Comment by mubashirp** [comment]
BUT I am using thingsboard professional cloud. There should be some links and headers that i can utilize in the api.

**Comment by mubashirp** [comment]
is there any link to the device so that i can send a get request to retrieve the values. I am using thingsboard professional cloud.

**Comment by mubashirp** [comment]
i tried with the python code too, but the device is not responding to the api.
import requests

# Set the ThingsBoard Cloud API endpoint
api_url = "https://YOUR_DOMAIN/api/v1"

# Set the access token obtained from the ThingsBoard Cloud dashboard
access_token = "YOUR_ACCESS_TOKEN"

# Set the device ID or entity ID from which you want to fetch telemetry data
device_id = "YOUR_DEVICE_ID"

# Set the number of telemetry data points to retrieve (optional)
limit = 10

# Set the telemetry keys or attributes to fetch (optional)
keys = ["temperature", "humidity"]

# Construct the API URL for fetching telemetry data
telemetry_url = f"{api_url}/{device_id}/telemetry"

# Set the request headers with the access token
headers = {
    "Content-Type": "application/json",
    "X-Authorization": f"Bearer {access_token}"
}

# Set the request parameters (optional)
params = {
    "limit": limit,
    "keys": keys
}

# Send the GET request to fetch telemetry data
response = requests.get(telemetry_url, headers=headers, params=params)

# Check the response status
if response.status_code == 200:
    # Telemetry data fetched successfully
    telemetry_data = response.json()
    print(telemetry_data)
else:
    # Error occurred while fetching telemetry data
    print(f"Failed to fetch telemetry data. Status code: {response.status_code}")

this code is giving me the output as 405 error

**Comment by Civilduino** [comment]
Before jumping to Python, try Swagger so you understand the API.

1) For the cloud version https://thingsboard.cloud/swagger-ui/ and authorise with your credentials.
2) Search the command you want and try it.
![image](https://github.com/thingsboard/thingsboard/assets/27728926/94c55a4a-60bc-4ba7-8e9a-3e09bfdd6762)
3) Execute it to get the example curl command.

`
curl -X 'GET' \
  'https://thingsboard.cloud:443/api/plugins/telemetry/DEVICE/784f394c-42b6-435a-983c-b7beff2784f9/keys/timeseries' \
  -H 'accept: application/json' \
  -H 'X-Authorization: Your Access Token Here'
`

4) Get your Access Token from your security tab in your cloud profile.
![image](https://github.com/thingsboard/thingsboard/assets/27728926/9dac64ee-06f9-4b5b-a6eb-06c5a310c754)

5) Add token to curl command and execute in the terminal.

**Comment by mubashirp** [comment]
this worked,thank you @Civilduino

**Comment by mubashirp** [comment]
can we increase the expiry time of jwt token in thingsboard cloud professional edition version, as i have to provide the token again and again due to its early expiry

**Comment by mubashirp** [comment]
any comment on how we can do that

**Comment by Civilduino** [comment]
I don't know unfortunately, this seems to work for PE edition #7892
Ask Cloud support.

**Comment by mykhailokornieiev** [comment]
There is no possibility to increase the expiry time of JWT token in thingsboard.cloud. 
In this case, I close the ticket.
