### ISSUE TITLE
Can't start thingsboard 2.0.3 on windows

### ISSUE THREAD

**Issue by pavellzubkov** [thingsboard/thingsboard#890]
Thingsboard 2.0.3 release was installed successfully, but i see "system error 1067" when i run "net start thingsboard" In log folder in file thingsboard.err.log i see :

> Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'UseCondCardMark' <

Meanwile thingsboard 1.4.0 release starting ok on same machine.

**Comment by pavellzubkov** [comment]
need to stop all java process before starting thingsboard service

**Comment by pavellzubkov** [comment]
I use java

> java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)<

**Comment by pavellzubkov** [comment]
When i try build from sorces master branch (2.0.4) i have next error

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project application: There are test failures.<

**Comment by pavellzubkov** [comment]
Failed on test

> -------------------------------------------------------------------------------
Test set: org.thingsboard.server.rules.RuleEngineSqlTestSuite
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 63.188 sec <<< FAILURE! - in org.thingsboard.server.rules.RuleEngineSqlTestSuite
testTwoRuleChainsWithTwoRules(org.thingsboard.server.rules.flow.sql.RuleEngineFlowSqlIntegrationTest)  Time elapsed: 5.554 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<0>

**Comment by IvanSemenenko** [comment]
Please, look at this solution https://github.com/thingsboard/thingsboard/issues/883
You need to delete the next line at the file thingsboard.xml (located in the Thingsboard install dir): 
<startargument>-XX:+UseCondCardMark</startargument>
or add the line:
<startargument>-XX:+IgnoreUnrecognizedVMOptions</startargument>
After that please restart your Thingsboard service.

**Comment by pavellzubkov** [comment]
Thank you! I was reading those solution, but i didn't find thingsboard.conf on windows. I must been find xml file.

**Comment by alexsmartens** [comment]
@pavellzubkov, @vparomskiy,
thank you, I had a similar problem and deleting `-XX:+UseCondCardMark` fixed the issue.
What does deleting `-XX:+UseCondCardMark` mean?

**Comment by alexsmartens** [comment]
Hey,
be careful with `-XX:+UseCondCardMark` when you upgrade to **TB 2.3.1**. You'd probably want to add the flag back if you're building from source before doing the upgrade.

I did not add the flag back, so after the upgrade I saw this message at `http://localhost:8080/`:
```
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed May 08 20:35:36 UTC 2019
There was an unexpected error (type=Not Found, status=404).
No message available 
```
Adding the flag back solved the problem.
