### ISSUE TITLE
[Question] Indoor Tracking System

### ISSUE THREAD

**Issue by knityanand** [thingsboard/thingsboard#8901]
**Thingsboard**

 * Generic

**Description**
In an indoor facility we have people wearing armbands which amongst other things share X, Y & Z location info of each person using 0 - 1 scale. I would like to map onto an floor plan the location of individuals and update the same dynamically. Can anybody please help me with an approach or the widget I should use.

**Environment**

 * OS:  Ubuntu 20.4
 * ThingsBoard: 3.5
 * Browser: Firefox

**Comment by hayschan** [comment]
I just came across Thingsboard. I saw there is an Image Map widget that displays the latest value. Its description is as follow:

>  Displays the indoor or relative location of the entities on the image map. Useful to display floor maps, smart parking, etc. Entity coordinates are expected to be in the range from 0 to 1. Highly customizable via custom markers, marker tooltips, and widget actions.  

Let's see if that widget helps.

**Comment by knityanand** [comment]
Yes I had tried that. It works.. Except that, the positioning is controlled using static attributes and not time-series values. We have to convert the data received into attributes and then display.
