### ISSUE TITLE
[Question] WARN  o.t.s.d.s.i.s.SqlPartitioningRepository - Failed to parse 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8905]
**Component**

 * Generic

**Description**
So i received  no data for a device even though it created queue and there were  just no data received  
but when i checked the issue in log file I saw this just after the queue got finished 
can someone explain is this was the cause if yes how can I resolve this . 
![image](https://github.com/thingsboard/thingsboard/assets/34526029/dbdfc601-1484-467f-90c4-746ec8701d9e)

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.5.1 PE
 * Browser: name and version

**Comment by den1jkee** [comment]
Greetings,
Could you please modify the logback.xml logger level from INFO to DEBUG and reproduce this issue again?
After successfully reproducing, roll back logback.xml to INFO and provide us with this log.
By default, ThingsBoard is configured to **INFO** level. But for testing/debugging proposes, you may change the log level to **DEBUG** at the:
```
<root level="DEBUG">
    <appender-ref ref="fileLogAppender"/>
</root>
```

Best regards,
Denys
