### ISSUE TITLE
about defaultEntity and GateWayEntity ID ,RPC twoway APi response to the 408 request timeout,

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#891]
I'm sorry to bother, weekend but now encountered a very thorny problem, when I was in call RPC twoway API call deviceId parameters into defaultDevice rather than gatewayDevice ID, response to the 408 request timeout, first, because in my call RPC interface is the default gateway and the ID of the do. My current thinking is to query against the incoming ID in TB to get the associated gateway and get the ID, and then assign it again. Or is there any other way to solve my problem? Thank you very much and look forward to your reply!

**Comment by caoyingde** [comment]
Now I solve this problem in a very stupid way, such as code:
![image](https://user-images.githubusercontent.com/10750404/41807249-78eb3160-76fe-11e8-83df-f514dce51ff6.png)

Look forward to a better way!

**Comment by mp-loki** [comment]
I can't understand what this ticket is about

**Comment by caoyingde** [comment]
gateWayID request Rpc API:

![image](https://user-images.githubusercontent.com/10750404/41815837-c6a7cc38-77a8-11e8-8b17-446eb597bffc.png)

![image](https://user-images.githubusercontent.com/10750404/41815865-8e92af10-77a9-11e8-9332-5f03eec2a393.png)
===============================
not gateWay request RPC api:

![image](https://user-images.githubusercontent.com/10750404/41815917-ad9d1174-77aa-11e8-8368-16aaa8632fca.png)

![image](https://user-images.githubusercontent.com/10750404/41815932-fae0ade2-77aa-11e8-910e-069083021156.png)

**Comment by ten2net** [comment]
![1](https://user-images.githubusercontent.com/1018417/45207334-4bca2400-b2ba-11e8-8b6e-84c1895b58e6.png)
In my case  ,Device is getway, get errorcode 408 also.

**Comment by AndreMaz** [comment]
@mp-loki I'm also facing a similar issue (or I might be misunderstanding the docs :sweat_smile: )
I'll try to explain my problem.

I have 3 devices
- `gateway` - implements MQTT  gateway API and it subscribes to `v1/gateway/rpc`
- `icy-boat-5927` - device connected to gateway
- `broken-fire-6565` - device connected to gateway
Devices list:
![image](https://user-images.githubusercontent.com/9802754/167144150-a16f099f-500f-4d29-9efa-90eb4fa3f0fc.png)

and I'm having trouble in sending server-side RCP requests to `icy-boat-5927` and `broken-fire-6565`.
When I make a RCP req, via REST API, I'm getting a `409 Conflict`. 

For example, here's a response to a  POST req. `http://localhost:9090/api/plugins/rpc/twoway/aaf37c10-cd0f-11ec-9c95-1fd873be76f8` where `aaf37c10-cd0f-11ec-9c95-1fd873be76f8` is the device ID of the `icy-boat-5927` device.

![image](https://user-images.githubusercontent.com/9802754/167145190-c8d06783-0162-4ec2-8378-80966fa1178d.png)

I would expect that after making a POST req. the `gateway` device would receive the data (at `v1/gateway/rpc`) but, for some, reason it doesn't.

Making RPC reqs. to `gateway` works properly, i.e., they arrive to `v1/devices/me/rpc/request/<reqID>` topic.

I'm using TB v3.3.3

**Comment by ban2derlog** [comment]
Hi, does this issue persist on latest ThingsBoard version?
