### ISSUE TITLE
[Question] Custom chartJS widget latest value data update issue on computer wake from sleep

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#8910]
### **Background**

- I'm building a custom bar chart widget using chartJS v4 library.
- Chart intended to display single datasource, latest value.
- In this case, my bar chart is used to show watts data from connectors.
- Connector watts data shown based on running charge sessions. This charge sessions are shown on separate dashboard state using entities table.

### **Problem**
I will have to reload the page every time the computer wake from sleep/hibernate to get the correct data.
As long as the computer idle/standby, the latest value are loaded correctly.
**On computer wake from sleep/hibernate, the chart doesn't load latest value correctly**.

### **Attempts**
- I've tried to put `myChart.update();` and `self.ctx.detectChanges();` inside `self.onDataUpdated()` function but data still not updated correctly on computer wake from sleep.
- I've tried to compare my custom chart to thingsboard bar chart latest value and entites table latest value, showing same dataKey. I put the computer to sleep for a night and check the next day. Result are the Entities table showing data correctly, Thingsboard bar chart and my bar chart not showing data correctly.

Here's the image of the charge sessions table (the correct total of data count that we're referencing to) with thingsboard barchart and my bar chart showing incorrect data count (total should be 4 per widgets) on computer wake from sleep:
![Untitleda](https://github.com/thingsboard/thingsboard/assets/43811204/914f94b9-3172-46db-8b54-34f41502b83f)

And here's the image of the correct data after browser reloaded. Showing the correct total (3) of data each widget.
![Untitledaa](https://github.com/thingsboard/thingsboard/assets/43811204/f663e9f5-a01e-48ad-83d1-5b030c8d1d96)

### **Question**

- Is there any method or function that i can use, just like  this `self.ctx.$scope.entitiesTableWidget.onDataUpdated()` on entites table widget ?
- if not, then is there anything i can do to "force update" widget to sync the latest dataKey value ?

### **Evironment**
- Thingsboard PE 3.4.4
- Browser  Microsoft Edge latest, Vivaldi

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
