### ISSUE TITLE
[Question] Enrichment "Originator attributes" node NOT working for latest telemetries in Assets

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#8915]
**Component**

 * Rule Engine
 

**Description**
I am trying to fetch the latest telemetries from an Asset using the Originator Attributes node in the Rule Chain but it is not working. I get the error "java.lang.RuntimeException: The following attribute/telemetry keys is not present in the DB".

I want to fetch multiple data keys specified in the metadata of the message. For this, I created a comma-separate string with the data key names I want, e.g. "temperature1,temperature2,humidity1", which I call using `${getKeys}` but this is not working.
I also tried calling the individual data key names "temperature1" "temperature2" "humidity1" and still is not working.

The node is not recognising the existence of the data keys in the Asset.

![image](https://github.com/thingsboard/thingsboard/assets/27728926/f18762d7-721e-44f8-8733-7c847c264559)

**Environment**

 * OS:  macOS 
 * ThingsBoard: Cloud 3.5.1
 * Browser: Chrome latest

**Comment by TrafalgarLaw-24** [comment]
@Civilduino Just use getKeys instead of the braces or dollar symbol

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by tomermurray** [comment]
@Civilduino did you manage to figure out a different way to do this since it seems like this is still not a supported feature?
