### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by 1043021051** [thingsboard/thingsboard#8927]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.
![6$BDOS8_`(P365FDFHUK_HI](https://github.com/thingsboard/thingsboard/assets/39759644/a3103b8a-3f58-4182-9755-6ef41698ddab)
Run multiple times to save the remote test abnormality after the remote test？

**Environment**

 * OS:  name and version
 * ThingsBoard:  3.5.0
 * Browser: name and version

**Comment by Ultrazombie** [comment]
Hello @1043021051 
please describe your issue in more detail.
