### ISSUE TITLE
[Question] How to get a copy of the default settings schema for widgets.

### ISSUE THREAD

**Issue by LKY0616** [thingsboard/thingsboard#8934]
**Component**

 * Generic

**Description**
Hi, I am trying to modify a line chart widget to display some data keys as step charts.

For that purpose, I need to add a checkbox to the data key settings schema. However, in the widget editor, that section is blank. Instead there is another tab "Widget settings" as shown below.

![image](https://github.com/thingsboard/thingsboard/assets/138561017/126fc825-67e6-4cf0-88a0-62a78ca5deec)

When those fields are filled, the widget ignores the schema in the other tabs. So i cleared the field under Data key settings, and entered my own code into the Data Key Settings Schema tab.

 I got it to work somehow. The problem now is that I don't have the other settings anymore.
 
![image](https://github.com/thingsboard/thingsboard/assets/138561017/824695c1-9171-4b24-8ed5-642458781543)

How can I get the json code for the default schemas? I would like to insert my settings into the default forms and not have to rebuild it. 

Thank you.

**Environment**

 * ThingsBoard: PE 3.5.1
 * Browser: Chrome Version 109.0.5414.120

**Comment by devaskim** [comment]
> I would like to insert my settings into the default forms and not have to rebuild it.

There is no such option.

**Comment by LKY0616** [comment]
Thanks @devaskim.
Is there a way to get the contents of the schema templates then?

**Comment by devaskim** [comment]
Here are [all settings sources](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/app/modules/home/components/widget/lib/settings/chart)

But even if you override settings schema, you also need to force chart implementation to apply your custom configuration keys, that is another challenge.

**Comment by LKY0616** [comment]
Tq.
