### ISSUE TITLE
MQTT Connection

### ISSUE THREAD

**Issue by Shresthj** [thingsboard/thingsboard#8937]
**Component**
![Mqtt](https://github.com/thingsboard/thingsboard/assets/45101562/e0eabb8d-007a-4aea-8efa-a014cbe65474)

 *  Rule chains

**Description**
I need help, I am tiring to create MQTT broker in (Rule Chains) but I
don't know how to create I need an instruction or steps to create MQTT.
Please find the attachment And provide some document regarding this.
i am using thing (https://demo.thingsboard.io)

**Environment**

 * OS:  name and version
 * ThingsBoard: v 3.4.4
 * Browser: name and version

**Comment by ashaforost** [comment]
Hi @Shresthj 

Please see the [MQTT Rule Node documentation](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/external-nodes/#mqtt-node).
Note that this rule node does not create a new mqtt broker but connects to an existing third-party broker of your choice. 

If you need an MQTT broker, check out Thingsboard's new project:  [TBMQ Broker](https://thingsboard.io/docs/mqtt-broker/)
