### ISSUE TITLE
Problems creating new device using rule engine

### ISSUE THREAD

**Issue by Martinnisted** [thingsboard/thingsboard#894]
Hi,

I'm trying to create new device using the rule engine. By using the rule node REST API, it is possible to get access to device types, but only by using the header X-Autorization: Bearer <JWT token>. But it is not possible to get the token without using username and password in a data field and this is not possible in the REST API node.

I'm sure that I'm missing something, but how is it possible to creating a device using the rule engine?

**Comment by ashvayka** [comment]
The REST API node is designed to execute API calls to external systems, not to TB itself. I am closing this as an invalid. The right way to do this is to create custom rule node implementation.
