### ISSUE TITLE
Provision Client Intermediate Public Key as Device Profile X509 provision strategy

### ISSUE THREAD

**Issue by BigKing992** [thingsboard/thingsboard#8944]
ThingsBoard Web UI -> Profiles -> Device profiles -> Your Device profile -> Device provisioning,In the Device provisioning step, the X.509 Certificates Chain is not found, only three options are disabled, allow the creation of new devices, and check for preconfigured devices

**Comment by ban2derlog** [comment]
Hi,
Which ThingsBoard version are you using?
This feature was released with 3.5.0.
