### ISSUE TITLE
[Feature Request] RedHat Enterprise Linux (RHEL) 9.2 Support

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard#8950]
**Is your feature request related to a problem? Please describe.**
Modern RHEL / Centos Stream (9.x series) is still not supported.

[End dates are coming in 2024 for CentOS Stream 8 and CentOS Linux 7. Check the blog post for information on upgrade and migration options.](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/)

**Describe the solution you'd like**
Support recent / modern RHEL / Centos versions.

**Comment by trikimiki** [comment]
Hi!
The latest TB versions actually completely support RHEL/CentOS/derivatives 9.x
I am currently updating all installation docs to mention that. Thanks for the suggestion!
