### ISSUE TITLE
[Bug] Azure Active Directory Connection

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#8952]
**Describe the bug**
We are currently trying to integrate ThingsBoard with Azure Active Directory via OAuth 2.0, but always end up with "Connection timed out" error. On Azure AD side successful logins are displayed.

We also tried to use the similar issue for orientation, but did also not work as expected.
https://github.com/thingsboard/thingsboard/issues/8156

Current configuration is listed below

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.5.1

**Expected behavior**
Login via Azure AD should be working.

**Screenshots**
Error message:
![error](https://github.com/thingsboard/thingsboard/assets/25298332/b03eb9b1-81fa-4596-8860-4f9703803dbb)

Configuration:
![part1](https://github.com/thingsboard/thingsboard/assets/25298332/55cd1bb7-27d3-4567-94b4-4d7db1ac32d9)

![part2](https://github.com/thingsboard/thingsboard/assets/25298332/eb16d081-7ca1-4ca3-aece-c4b8dc13384b)

**Comment by mykhailokornieiev** [comment]
Hi
I'm not sure if your request is still relevant, but you can try to make the same as in this comment:
https://github.com/thingsboard/thingsboard/issues/10143#issuecomment-1948198924

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
