### ISSUE TITLE
Thingsboard PE Improvement Suggestions

### ISSUE THREAD

**Issue by markhunt** [thingsboard/thingsboard#896]
As at Thingsboard PE customer, a couple of issues or suggestions for future updates if I can:

For customer (not tenant) login permissions, propose option to allow certain administrative options to be removed from a customer login...or at least a permission option to enable/disable:

1. Remove ability for customer login to add/amend/remove device or asset relationships
2. Remove ability for customer login to add/amend server attributes
3. Remove ability for customer login to amend whitelabelling
4. Add the ability for a customer login to see the PE asset and device groups - the table based asset and device entity groups is excellent...but only accessible if using a tenant login

These it is reasonable to consider are admin (tenant) activities - allowing user accounts access to these functions is causing issue for us operationally as the customer logins are making changes that need 'fixing'.

Also, can we add the ability to remove/hide the HELP icon on the assets/devices menu option for customer logins also?  It's great having a HELP icon link....but this directs to the public thingsboard documentation which is not of great use for PE commercial customers.  As a PE customer, it's not feasible for us a recompile PE from source (as we cannot access the source) to remove that HELP link.

Hope these suggestions are useful and could be considered for future updates.

Mark

**Comment by ban2derlog** [comment]
Hi, is issue persist on latest ThingsBoard version?
