### ISSUE TITLE
How to make the data on the Line chart not change the sorting position with the size of the telemetry value

### ISSUE THREAD

**Issue by duxiu1124** [thingsboard/thingsboard#8970]
**Component**

 * Generic

**Description**
How to fix the position of the value displayed on the tool tip so that it does not change with the size of the data, and changing the position is inconvenient for data analysis，Could you please assist me in solving this problem？
![image](https://github.com/thingsboard/thingsboard/assets/51322395/c350409e-f7d9-4e5a-8089-bbe938ca17a8)
![image](https://github.com/thingsboard/thingsboard/assets/51322395/200b3b99-5b7a-455b-881e-dfdf9a72969c)

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.4.0 PE
 * Browser: name and version

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
