### ISSUE TITLE
[Question] Issue with navigation card paths and version control

### ISSUE THREAD

**Issue by herron-qorvo** [thingsboard/thingsboard#8973]
**Component**

 * UI

**Description**

My company is using the PE version of TB.  We have two servers running production and staging versions of our code.  Recently, I started using navigation cards to link one dashboard to another in our UI.  The problem is the path to destination dashboard includes the ids of the dashboard group and dashboard.  

_Example:_
_Navigation Card > Advanced > Navigation Path:_
```
dashboardGroups/39d79430-75c5-11ed-9338-a51186c29ac9/d1bf3af0-281c-11ee-a637-5df53bcc43f4
```

When I push the staging server code to our git repository and then pull to the production server, the ids of the target dashboards are not necessarily the same.  So when I open the dashboard containing the navigation card, errors result.  I have to go back and manually update the broken navigation card paths to match the path on the new server.   Is there anyway around this?

**Environment**

 * OS:  RHEL
 * ThingsBoard: 3.4.1 PE
 * Browser: Edge 114.0.1823.82

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. However, there is no workaround except for creating custom widget that will be able to use not entityId, but its name.
