### ISSUE TITLE
[Bug] Bar Chart Does Not Stack Correctly When No Data From A Particular Source 

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard#8974]
**Describe the bug**
When plotting a bar chart with stacking mode enabled, the stacking value is incorrect when there is no data from a particular source. I am attaching below the graphs:

**Your Server Environment**

  * ThingsBoard Version 3.51PE
  * Ubuntu 20.04.3 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome
* Version 115.0.5790.102 (Official Build) (64-bit)

**Your Device**
Custom-made modbus device

* Connectivity
  * MQTT

** Steps to Reproduce **
1. Go to Dashboard and add Timeseries Bar Chart widget
2. Add multiple Datasources
3. Click on Advanced tab and tick on Enable stacking mode.

**Expected behavior**
1) Bar Chart with all the sources enabled (6 sources in this example)
![stack_error](https://github.com/thingsboard/thingsboard/assets/6798969/4bc20ab4-af2b-4133-8d41-14bf58f60c7f)
By right all the data should be hovering around a value of 800. However, from 14.00 to 20.00 and 2.00 to 9.00, we see the value is only about 600 (off by about 200 kWh). This coincides when the data source from CDA 7 is off as shown below.

2) Source (CDA 7) has intermittent data
![stack_error7](https://github.com/thingsboard/thingsboard/assets/6798969/8f5514ab-a4bd-4782-9028-f87147d3431c)
Data from CDA 7 is off between 14.00 to 20.00 and 2.00 to 9.00.

3) Bar Chart with CDA 7 disabled
![stack_error_no7](https://github.com/thingsboard/thingsboard/assets/6798969/c3aeabfe-3e43-42c1-9f27-bb8f482c3051)
This graph shows the values correctly when the offending source, CDA 7, is disabled.

**Comment by mykhailokornieiev** [comment]
Hi. There is a bug in a platform. I will inform on any updates in this ticket https://github.com/thingsboard/thingsboard/issues/7321#issuecomment-2110404306
This one I close as duplicate
