### ISSUE TITLE
[Bug] Latitude and longitude truncated

### ISSUE THREAD

**Issue by rascove** [thingsboard/thingsboard#8976]
**Describe the bug**
I have added two server attributes to a private device, which is propagated to public entity view to be displayed on Google Map in a public dashboard. Both latitude and longitude have 6 decimal points, but these values are rounded to 2 decimal points, which resulted in incorrect marker location in Google Map.

**Your Server Environment**
Virtual Machine in Oracle Cloud Infrastructure
ThingsBoard 3.5.1
Ubuntu 22.04.2 LTS

**To Reproduce**
1. Create a new device with server attributes latitude and longitude with data type Double and 6 decimal points
2. Create a new public entity view that propagate the attributes of previously created device
3. Create a new public dashboard with Google Map widget and data source entity view created earlier

**Expected behavior**
A marker located on correct coordinate

**Comment by mykhailokornieiev** [comment]
Hi. I was unable to reproduce your behavior even with your steps to reproduce. 
![image](https://github.com/thingsboard/thingsboard/assets/115699895/981974d1-ed93-4082-aada-790f4f42e771)
Please check your number of digits after floating point. Also there can be data post-processing function
![image](https://github.com/thingsboard/thingsboard/assets/115699895/d89a96fd-40cf-4d12-869c-2a256fc3303d)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/095a873c-8c27-4b4b-9347-8f290319f96d)

**Comment by rascove** [comment]
Hi @mykhailokornieiev,

Thank you very much for your reply. However, I've found the solution earlier and forgot to close the issue. The reason why the decimal point is truncated is because the entity key is simply written as `${latitude}` and `${longitude}` without specifying the decimal point, i.e., `${latitude:7}` and `${longitude:7}`.
