### ISSUE TITLE
[Question] How can i dynamically add form controls?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#8977]
**Component**

 * UI

**Description**
How can i dynamically add form controls in widget action with html template? This is not working

![image](https://github.com/thingsboard/thingsboard/assets/87794982/541feba2-f7a2-4c9f-b804-18371f9c22d2)

![image](https://github.com/thingsboard/thingsboard/assets/87794982/aedc326f-42cc-489c-86ed-622e28b2f005)

**Environment**

 * OS:  Cenos Steam 8
 * ThingsBoard: 3.4.1 PE
 * Browser: Edge Chromium

**Comment by devaskim** [comment]
```
let validators = [vm.validators.required];
let valueControl = vm.fb.control(null, {'validators': validators, 'updateOn': 'change'});
```

**Comment by devaskim** [comment]
`fb` is Angular's [Form Builder](https://angular.io/api/forms/FormBuilder)
