### ISSUE TITLE
Server-side RPC not working in v2.0.3.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#898]
I just realized that after upgrading from v1.4.0 to v2.0.3. the server-side RPC is not working.

Devices that were properly configured before, and that were tested and known to be ok are now not working.

I searched this issue a lot. As it seems the requests are never sent from the server. I tried with many widgets, including the RPC Debug widget. No matter what are my actions on the dashboard, the Thingsboard broker does not publish anything at all.

**Comment by BatListener** [comment]
May be same as here?
#850

**Comment by fotis400** [comment]
Oh, my bad. Sorry, I didn't see that issue.

Indeed my issue is solved, following the advice of #850.
