### ISSUE TITLE
[Question] TimeseriesDao  cannot find

### ISSUE THREAD

**Issue by qqhai007** [thingsboard/thingsboard#8982]
field timeseriesDao in org.thingsboard.server.dao.timeseries.BaseTimeseriesService required a bean of type 'org.thingsboard.server.dao.timeseries.TimeseriesDao' that could not be found.

I cannot find the reason.

**Comment by qqhai007** [comment]
windows platform

**Comment by Ultrazombie** [comment]
Hello @qqhai007 
Were you able to solve your problem?

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
