### ISSUE TITLE
JWT Token Extension

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#8985]
I am using thingsboard professional edition cloud. Currently my JWT Token has only life of few hours. I am using it to call an API. Can anywone suggest how we can extend the JWT Token duration in the cloud edition.

**Comment by ban2derlog** [comment]
Hi,

You can't modify JWT token and refresh token lifetime in ThingsBoard Cloud.

The only way is to migrate to Self Hosted instance where you can modify anything.
