### ISSUE TITLE
[Question] API Usage - Way to high numbers/infinite queue loop

### ISSUE THREAD

**Issue by SmartMetersAreCool** [thingsboard/thingsboard#8989]
**Component**
 * Rule Engine/Queue
 * Generic

**Description**
I'm trying to understand the nature of the values presented in the first picture, where it shows a peak of over 2.5 million processes in the queue. This number is particularly astounding, given that I only uploaded approximately 2,450 values. Even when accounting for rule nodes, this number seems excessively high, especially when compared to the yellow line (which represents about 40k processes). We had these 40k processes in place before switching the queue type from Burst to Sequential by Originator, and they managed to handle 200k data points (uploaded in individual requests).

I'm curious about what these values indicate and how they could be utilized for troubleshooting. My current understanding is that these figures represent the successful or unsuccessful executions of **rule nodes**.

![image](https://github.com/thingsboard/thingsboard/assets/122782131/c8b73921-6259-4f08-93b9-e21a388b38ff)

**Some context about our work environment:**
We typically upload a substantial amount of data via individual HTTP requests about four times per day. The aforementioned 200k data points usually occur once daily in the early hours. Our setup involved a burst Queue with the "retry on timeout" feature.

We introduced a new rule chain designed to aggregate values from a single device. Unfortunately, Thingsboard was unable to save these values quickly enough, which occasionally resulted in new values being added to older ones, thereby leading to incorrect results.

To mitigate this issue, we created a new queue using the "Sequential by Originator" setting and enabled the "retry all" feature. However, this change led to the generation of the rather unappealing chart shown below.
![image](https://github.com/thingsboard/thingsboard/assets/122782131/e281dc93-35d7-4446-bb8d-d87a7bec1ce1)

The spikes and subsequent data are irrelevant, as we reverted the queue back to the burst type upon noticing some irregularities. However, we previously had a consistent occurrence of 20,440 processing timeouts, despite dealing with only 2,450 values. Correlating with this is the green line (the one in the first screenshot) visible before the spike, which represents about 40k successful processes. Despite halting the upload after roughly 10-20 minutes, the line remained constant for the remaining period. The spikes started to appear after we switched back to burst, after which the pattern began to normalize.

Moreover, I'd appreciate insights on how to verify the queue length, as it has a cap of 15k (normally, I believe it's 10k). We fear data loss if we continue to upload beyond this point, as Thingsboard would still return a 200 status code, but the data would never be saved.

Considering all of the above:
If these values do represent rule node executions, could someone explain why it seems to create an infinite loop with Sequential by Originator and why it spikes to such high numbers when using the burst option? When does timeout occur and why? Are there settings I can change to combat this?

I appreciate your help

**Environment**
 * OS:  Ubuntu
 * 3.5.1 PE

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
