### ISSUE TITLE
Need documented migration path from Postgres to Cassandra

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#899]
We need a documented upgrade path to migrate a Postgres database to Cassandra (assuming this is possible).  If someone can outline the process, I'm willing to try it on my data and make a first pass at writing up some formal documentation.

**Comment by fotis400** [comment]
I would be interested in this too.

Maybe provide a script that performs database migrations?

**Comment by tekzoom** [comment]
I need to do the same thing.

**Comment by hamburml** [comment]
Anything?!

**Comment by GrayCygnus** [comment]
After finding this issue I continued searching for clues and found this repo: 

https://github.com/AbCthings/thingsboard-data-migration 

It was suggested in this SO [answer](https://stackoverflow.com/a/56902233/3908170), which basically suggests that you do a fresh TB + Cassandra install, and the migrate your data from your current TB instance using the REST API. Haven't tried it yet, but worth sharing. Will update when I try it...

**Comment by volodymyr-babak** [comment]
For anyone who is interested in migration from PostgreSQL to Hybrid mode with Cassandra + PostgreSQL please take a look at the database migration project - https://github.com/thingsboard/database-migrator

With a help of this project, you should be able to move timeseries data from PostgreSQL to Cassandra cluster.

**Comment by dimarudik** [comment]
There are tool https://github.com/dimarudik/bublik#postgresql-to-cassandra for this scenario
