### ISSUE TITLE
 Issue with Deleted Telemetry Data Still Appearing in the Device's Latest Telemetry Interface

### ISSUE THREAD

**Issue by jch889** [thingsboard/thingsboard#8990]
Description of the Issue:
I have utilized the Thingsboard API REST to successfully delete specific telemetry data points from my device. However, even after deletion, these data points are still visible in the latest telemetry interface of the device. This behavior is unexpected, and I would like to ensure that deleted data is no longer displayed.

Steps Taken:

Used the appropriate API REST call to delete the specific telemetry data.
Confirmed successful deletion via API response.
Expected Behavior:
Upon successful deletion of telemetry data through the API, I expect the deleted data points not to be displayed in the latest telemetry interface of the device.

Possible Causes:
I have considered that this issue may be related to caching mechanisms or delayed synchronization.

Request for Assistance:
Could you please investigate this issue and provide guidance on the following:

Is there any caching mechanism in place that might cause the deleted data to still appear in the interface?
How can I manually clear or refresh the cache to ensure the latest telemetry data is displayed correctly?
Are there any other factors that might be contributing to this behavior?
Is there a way to force an immediate update of the latest telemetry interface to reflect the deleted data?
Additional Information:

Thingsboard Professional Edition version: 3.4.3
Operating system:  Ubuntu 20.04.3 LTS (GNU/Linux 5.15.0-1040-azure x86_64)
Browser used to access the interface: Google Chrome

**Comment by ban2derlog** [comment]
Hi,

Telemetry and latest telemetry are different entities.
In `DELETE /api/plugins/telemetry/{entityType}/{entityId}/timeseries/delete{?deleteAllDataForKeys,endTs,keys,rewriteLatestIfDeleted,startTs}` API
you have parameter:
rewriteLatestIfDeleted
Do you set this false?

**Comment by ban2derlog** [comment]
If you set rewriteLatestIfDeleted to true, then any telemetry belonging to these timeframes is deleted,  and telemetry that doesn't belong to these timeframes will be rewritten as the latest telemetry and displayed in the interface. 
If you do not need to overwrite historical telemetry as the latest and show it as the latest, set this flag to false. 

In addition, startTs and endTs should be specified in milliseconds format, UTC-0 timezone. For e.x.,  Tue May 16 2023 20:00 = 1684267200 = 1684267200000
So check that you set proper timeframe when trying to delete Latest telemetry.

**Comment by jch889** [comment]
Thank you for your response and clarification regarding the DELETE API and the use of "rewriteLatestIfDeleted" parameter.

I apologize for the oversight in specifying the timeframes for telemetry data deletion. I understand now that the "startTs" and "endTs" should be provided in milliseconds format, using the UTC-0 timezone. I was using UTC-4 timezone in my previous attempts, which caused the deletion not to take effect.
