### ISSUE TITLE
 Issue with Outgoing Mail Server Settings - SMTP STARTTLS Error

### ISSUE THREAD

**Issue by jch889** [thingsboard/thingsboard#8991]
Description of the Issue:
We are using Thingsboard version 3.4.3 on Ubuntu 20.04.3 LTS (GNU/Linux 5.15.0-1040-azure x86_64). When attempting to configure the Outgoing Mail Server with our Outlook email account, we encounter the following error:

Unable to send mail: org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [BN8PR04CA0018.namprd04.prod.outlook.com 2023-07-25T15:38:53.111Z 08DB8B703C81A91E] ; message exceptions (1) are: Failed message 1: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [BN8PR04CA0018.namprd04.prod.outlook.com 2023-07-25T15:38:53.111Z 08DB8B703C81A91E]

Expected Behavior:
We expect to be able to successfully send emails through our Outlook email account using the Outgoing Mail Server configuration in Thingsboard.

Configuration Details:

Thingsboard version: 3.4.3
OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.15.0-1040-azure x86_64)
Outlook email account details:
SMTP Server: smtp.office365.com
Port: 587
Encryption Method: STARTTLS
Troubleshooting Steps Taken:

Ensured the correct version of Thingsboard (3.4.3) that supports STARTTLS is being used.
Configured Thingsboard to use "STARTTLS" as the encryption method for the Outgoing Mail Server.
Verified that port 587 is open and accessible for outgoing email traffic.
Checked the validity of SSL/TLS certificates for the Outlook SMTP server.
Request for Assistance:
Could you please help us resolve this issue with the Outgoing Mail Server configuration? Specifically, we would like to know:

Is there any known issue with the version 3.4.3 regarding STARTTLS support?
How can we ensure Thingsboard uses STARTTLS correctly to communicate with the Outlook SMTP server?
Are there any additional steps or configurations we should consider to make this work?

**Comment by ban2derlog** [comment]
Hello,

According to Office 365 documentation - there is no SMTPS option.
You can use SMTP and enable TLS 1.2.
Endpoint for Exchange will be
smtp.office365.com:587

Also, check if your Office 365 allows you to use SMTP Basic Auth.
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online
