### ISSUE TITLE
Widget Data Manipulation and the tooltip not working

### ISSUE THREAD

**Issue by merrittholmes7** [thingsboard/thingsboard#8992]
I am updating widget data and when I do this the tooltip no longer works on hover. Is there something I need to do to refresh this?

Context:

I am creating my own version of the time series widget and taking data and aggregating it into a new set of data elements. I am then updating:

.defaultSubscription.data
.data
.defaultSubscription.labelPatternsSourcesData
.datasources
.defaultSubscription.datasources
 
and also for the legend

.defaultSubscription.legendData.keys

I then update the flot widget using

self.ctx.flot.update();
 self.ctx.detectChanges();

Issue/Question:
When doing the abaove I get the chart to update correctly including legend, but for some reason the tooltip stops working when I hover over the data point. What do I also need to update to ensure the tooltip continues to work in this context (when the data points and keys have changed)

**Comment by AndreSensaway** [comment]
how did you resolve this? I'm working on a custom timeseries chart widget as well. The tooltip is working but I cannot change datakey label that is shown in the tooltip even though I've changed the labels in in the dataKeys objects.
