### ISSUE TITLE
[Question] Can we pass alarm time to chart ??

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8993]
**Component**

 * UI
 * Generic

**Description**
i wanted to show data in graph when the alarm is rasied to next 25 sec how can i get alarm creation time to a chart to display it for next 25 sec 

**Environment**

 * OS:  ubuntu 20.4
 * ThingsBoard: 4.5.1 PE
 * Browser: Chrome

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
