### ISSUE TITLE
[Question] how to show data from (CASANDRA)custom table to dashbord graph ?

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8999]
**Component**

 * Generic

**Description**
i wanted to show data from my custom table that is created using casandra USING save to custom table node in rule chain and show that data on the graph 
**Environment**

 * OS: ubuntu 20.4
 * ThingsBoard: 3.5.1PE
 * Browser: BRAVE

**Comment by ashaforost** [comment]
Hi @securitylamb 

If you want to get data from a custom table, you need to develop a custom API to work with this table. On top of it, you can develop a custom widget, that will use this API to fetch data and display it.
