### ISSUE TITLE
Document password requirements

### ISSUE THREAD

**Issue by chrowe** [thingsboard/thingsboard#90]
After a bunch of troubleshooting it looks like the "Change password" form doesn't have the same requirements as the login form. e.g. I am able to create a password with an `&` symbol in it but when I try to log in it does not work.
Sometimes I get a `Invalid username or password` message and sometimes I don't.
In all cases I get a `POST /api/auth/login 401 ()` error in the console.

I am running Chrome 57 on a Mac.

The password creation and reset forms should have password requirements documented and a warning about not meeting these requirements should be thrown when not met.
1. How long can a password be?
2. How long does a password have to be?
3. What characters are required?
4. What characters are not allowed?

**Comment by srisler** [comment]
Hi,

Do we have update on that?

**Comment by ashvayka** [comment]
This is fixed in 1.4. any chars now. The code is in master branch.
