### ISSUE TITLE
Unable to see device data on web ui

### ISSUE THREAD

**Issue by cerbica** [thingsboard/thingsboard#900]
Hi,
I installed 2.0.3 version.
I literally followed the directions at link:

https://thingsboard.io/docs/getting-started-guides/helloworld/#pushing-data-from-the-device

in order to push data from a device to web ui.

The script runs correctly:connect to the server and push data.

In /var/log/thingsboard/thingsboard.log I can see the line:

"2018-06-27 05:21:29,622 [nioEventLoopGroup-82-2] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt2] Processing connect msg for client: mqttjs_6a7581e5!"

This is the output of publish.js:

[Sarah.NB] ➤ node publish.js
Connecting to: 192.168.31.7 using access token: pzWngb9TIMDwNfoLsGkf
Client connected!
Attributes published!
Telemetry published!

But in web UI, the device "ATTRIBUTES" and "LATEST TELEMETRY" tabs do not show anythings,
they are empty.

Any idea?

thanks
Sarah

**Comment by DHDSP** [comment]
This is also my Problem, I did follow the instructions but although publishing data using the script (successful), no data is visible on the device's telemetry page. 

The progress bar keeps moving forever, but now data is showing. 

I installed 2.0.3 originally but did not try to upload data) and upgraded to 2.1.0. Then I uploaded data using the scripts from the tutorial.

I noticed somethin weird though: the only rulechain available ist the"root rule chain", subtitled "root" , but if I export the rule chain, it clearly says:

{
  "ruleChain": {
    "additionalInfo": null,
    "name": "Root Rule Chain",
    "firstRuleNodeId": null,
    **"root": false,**
    "debugMode": false,
    "configuration": null
  },
...

**Comment by DHDSP** [comment]
OK, I "solved" **my** main problem: the reason it was not working, is that I am running thingsboard behind an nginx proxy. I had to activate websockets support on my (subdomain) proxy like this (found somewhere, just can't remember where):

location / {
            proxy_pass http://localhost:8087/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # WebSocket support (nginx 1.4)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

Now the telemetry values show up. I will ignore the "dead letters encountered" for now.

**Comment by Kafongo** [comment]
@DHDSP I found the config options for websockets in the nginx documentation : https://www.nginx.com/blog/websocket-nginx/
