### ISSUE TITLE
SYSADMIN PASSWORD RESET

### ISSUE THREAD

**Issue by fxsilva** [thingsboard/thingsboard#9004]
**Component**

 * Generic

**Description**
I try to change the sysadmin password, and apparently I made a mistake and now I can not login with the old password nor with the new I tough was changed, what I can do to restore or have access to the platform

**Environment**

 * OS:  UBUNTU 20.04
 * ThingsBoard: CE
 * Browser: CHROMIUM

**Comment by fxsilva** [comment]
Please forgot the issue, I found my mistake, thanks

**Comment by ban2derlog** [comment]
Hi,
Resetting System Administrator password can be done only by using queries in database.

0. Before any changes in database perform full backup
1. Run this query:
`update user_credentials SET password = '$2a$10$YMyxoU0hMOLmd9D7tz/dQeDY3fkXRAv8C023F6hzx2gVB9dTBUpq6' WHERE user_id=(select id from tb_user where authority = 'SYS_ADMIN');`
2. Now you System Administrator account has default password - `sysadmin`

**Comment by LDS79** [comment]
Hi Could you tell me where or how I have to run this query?
Thanks
