### ISSUE TITLE
[Bug] User Profile Settings - Dropdowns for Language & Phone not disabled when no permission to change

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#9005]
**Describe the bug**
In a current project we set the profiles for users to read-only. Though they can change values for the dropdowns (language & phone). Saving the changes is not allowed, but still some users are confused that these fields are editable whereas E-Mails, & Name fields are disabled.

**Your Server Environment**

* own setup
  * cloud
  * ThingsBoard Version 3.5.1 PE

**To Reproduce**
1. Create a new User in a Group with no "Write" or "All" permission for profile
2. Login as new user
3. Switch to user profile settings
4. Dropdowns for Language & Phone Number are changeable (yet saving is not allowed afterwards)

**Expected behavior**
Dropdowns are disabled when there is no permission to change the values.

**Screenshots**
![CPT2307280957-1079x495](https://github.com/thingsboard/thingsboard/assets/25298332/c406edee-e35a-4511-9e1f-b9097ce8f28b)

**Comment by AlexDoanTB** [comment]
@mde2017 Restricting the user to edit their own information and preferences is an antipattern. The only bug I see is the ability to access the UI for users without the Profile permissions.

**Comment by ashaforost** [comment]
closing the issue due to inactivity
