### ISSUE TITLE
[Bug] Changes in "Settings schema" do not affect the "Advanced" section of the widget

### ISSUE THREAD

**Issue by sperezs95** [thingsboard/thingsboard#9007]
**Describe the bug**
I am following the instructions of the widget development guide published in the URL: https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/#rpc-control-widget, Specifically RPC (Control) widget; Changing the JSON of the Settings schema does not cause changes to the widget.

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10 Home
* Browser Chrome
* Version: 115.0.5790.110 (Build oficial) (64 bits)

**Smartphone (please complete the following information):**
* Device: None
* OS: None
* Browser [None
* Version None

**Your Device**
None

**To Reproduce**
1: Create new widget type
![image](https://github.com/thingsboard/thingsboard/assets/75050569/cc9f19f4-b4c4-42ed-8a7a-dae5087f27a2)

2: Create control widget, clear CSS, paste HTML code, schema settings JSON and JS code. 
![image](https://github.com/thingsboard/thingsboard/assets/75050569/0b4ec75b-42bb-4c9e-83ec-57549b929543)

4. Add title, click run button, click save button, enter edit mode in previw, edit widget:
![image](https://github.com/thingsboard/thingsboard/assets/75050569/992f2926-67be-44cd-ae87-189b920b0ef7)

5. Additionally, without adding the widget to a dashboard, the default configuration continues to be displayed:
![image](https://github.com/thingsboard/thingsboard/assets/75050569/8fed759a-e48a-4273-bdba-7ad391aafd1e)
![image](https://github.com/thingsboard/thingsboard/assets/75050569/c6662f4e-ddc1-4643-90b9-7eab04d7851c)

**Expected behavior**
I would expect to find the option shown in the development gui:
![image](https://github.com/thingsboard/thingsboard/assets/75050569/c370e097-e24c-424c-a0c5-2da4a6c21c35)

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/75050569/6b257102-12ec-4de4-8d4f-566d8f65065a)

**Additional context**
I'm new to this topic, I hope I'm not making an obvious mistake, thank you very much and I look forward to any response.

**Comment by ashaforost** [comment]
Hi @sperezs95 

Try removing the following parameter from the widget settings:
![image](https://github.com/thingsboard/thingsboard/assets/47900737/9fa15649-dbbc-461d-a8db-0827fc313509)

**Comment by Civilduino** [comment]
@sperezs95 could you post the "Settings schema" code as well?

**Comment by sperezs95** [comment]
> Hi @sperezs95
> 
> Try removing the following parameter from the widget settings: ![image](https://user-images.githubusercontent.com/47900737/257766966-9fa15649-dbbc-461d-a8db-0827fc313509.png)

@ashaforost Thank you very much, that seems to have worked!

**Comment by sperezs95** [comment]
> @sperezs95 could you post the "Settings schema" code as well? or you have not made any modifications to the default example?

Hello @Civilduino, I had not made any changes to the "Settings schema". Greetings

**Comment by Civilduino** [comment]
Great that you found the solution. Then you could close the issue :)
