### ISSUE TITLE
[Question] Create relation - Name Pattern

### ISSUE THREAD

**Issue by serifis84** [thingsboard/thingsboard#9011]
**Component**

* Rule Engine

**Description**
Could you provide an example of a pattern? The originator post 10 keys Water_Meter_1 through Water_Meter_10. Is there a patter that can catch Water_Meter_x and create a device (if it is not already created) ?

**Environment**

 * OS:  Ubuntu 20.04.6
 * ThingsBoard: 3.4.4
 * Browser: Chrome

**Comment by myroslav-tb** [comment]
Hi @serifis84, the solution depends on what message your originator is sending. In general, I can recommend using the script and filter nodes to separate the required keys from the message.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
