### ISSUE TITLE
[Question] problem in Rule Engine node connecting to kafka with SASL_PLANTEXT

### ISSUE THREAD

**Issue by yeehecan** [thingsboard/thingsboard#9013]
**Component**

 * Rule Engine

**Description**
we are trying to setup a thingsboard cluster with kafka brokers.
kafka are deploy as 3 nodes cluster with  SASL_PLAINTEXT auth mechanism.
the transport and core node seems working fine , no error messages were found in logs.
but the rule engine node got a lot of  persistent WARN logs.

`WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ffc09b70-ee5f-11ed-8f57-3d2956252f0e-tb-rule-engine] Bootstrap broker 192.168.1.178:9092 (id: -2 rack: null) disconnected
WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ffc09b70-ee5f-11ed-8f57-3d2956252f0e-tb-rule-engine] Bootstrap broker 192.168.1.177:9092 (id: -1 rack: null) disconnected
WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ffc09b70-ee5f-11ed-8f57-3d2956252f0e-tb-rule-engine] Bootstrap broker 192.168.1.179:9092 (id: -3 rack: null) disconnected
WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ffc09b70-ee5f-11ed-8f57-3d2956252f0e-tb-rule-engine] Bootstrap broker 192.168.1.178:9092 (id: -2 rack: null) disconnected`

in kafka logs also got lot of auth failed messages

`Failed authentication with /192.168.1.251 (channelId=192.168.1.179:9092-192.168.1.251:44246-19) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
Failed authentication with /192.168.1.251 (channelId=192.168.1.179:9092-192.168.1.251:44250-19) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
Failed authentication with /192.168.1.251 (channelId=192.168.1.179:9092-192.168.1.251:44260-20) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
Failed authentication with /192.168.1.251 (channelId=192.168.1.179:9092-192.168.1.251:45248-20) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
Failed authentication with /192.168.1.251 (channelId=192.168.1.179:9092-192.168.1.251:45258-20) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)`

Even if there is a persistent warn messages in rule engine logs , the device telemetry mesages are displays normally in thingsboard UI.

I try to downgrade kafka to 2.8.1 the problem remains the same.

My rule engine`s kafka config are:

`TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: "192.168.1.177:9092,192.168.1.178:9092,192.168.1.179:9092"
      TB_QUEUE_KAFKA_USE_CONFLUENT_CLOUD: "true"
      TB_QUEUE_KAFKA_CONFLUENT_SASL_MECHANISM: PLAIN
      TB_QUEUE_KAFKA_CONFLUENT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="testuser" password="testpass";
      TB_QUEUE_KAFKA_CONFLUENT_SECURITY_PROTOCOL: SASL_PLAINTEXT`

We tested the kafka cluster with  kafka-console-consumer.sh and kafka-console-producer.sh,Both publishing and subscribing are normal.

is there anyone runing into the same problem , please help me.
thanks.

**Environment**

 thingsboard and kafka are both deploy with docker compose.
 * ThingsBoard: 3.5.1 community editon
 * kafka : bitnami/kafka 3.2.3

**Comment by yeehecan** [comment]
we have found the culprit ，we have two envirment both have zookeeper redis and kafka .
We configure the platform service configuration to connect zk of environment 1 and kafka of environment 2 .that cause the problem.

**Comment by epneo-banuprakash** [comment]
I didn't understand what the config you changed, we are also facing similar issues and also we are  using same environment  , we didn't find the culprit , checked every where but find nothing.

**Comment by yeehecan** [comment]
> I didn't understand what the config you changed, we are also facing similar issues and also we are using same environment , we didn't find the culprit , checked every where but find nothing.

in our environment the WARN logs is not caused by thingsboard configs , Incorrect rule chain configuration is causing the WARN logs.We have configured a Kafka node in rule chain ,  and connect to the same kafka cluster that thingsboard using ,
later we changed the  auth configs of kafka , then we only changed  the configs of thingsboard and forget to change the kafka rule node , this caused the worn logs.  because the thingsboard and the rule node are connected to the same Kafka cluster , So the warning log misleads us,we've always suspected that the configuration of thingsboard is causing the warning logs
