### ISSUE TITLE
[Bug] Wrong database schema public for postgres

### ISSUE THREAD

**Issue by lgtti** [thingsboard/thingsboard#9022]
**Describe the bug**
In the SQL migration file "application/src/main/data/upgrade/3.2.2/schema_update_event.sql" there is  reference to the schema 'public'.
For example:
```
CREATE INDEX IF NOT EXISTS idx_event_ts
    ON public.event
    (ts DESC NULLS LAST)
    WITH (FILLFACTOR=95);
```

This is a problem because, for a fresh installation, the schema used is 'thingsboard'

**Your Server Environment**
* own setup
  * docker deployment
  * Version 3.4.0

**To Reproduce**
1. Create new schema in external database called 'thingsboard'
2. Create new user 'thingsboard' with all grant to the previously created schema
3. Setup the initializedb-job with the env variable SPRING_DATASOURCE_URL=jdbc:postgresql://host:5432/thingsboard
4. Run the job
5. In Job logs you will see the error:
```
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: relation "public.event" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.thingsboard.server.service.install.SqlAbstractDatabas
...
```

**Expected behavior**
DB correctly initialized

**Comment by TheSamabo** [comment]
I encountered exactly the same problem on the same TB version / upgrade. @lgtti Have you managed to solve it ?

**Comment by lgtti** [comment]
Hi, we have used the schema public....we have tried some solutions such as default user permissions but nothing succedeed.

**Comment by TheSamabo** [comment]
Hi, thank you for replying, i would have forgotten to get back.
I solved it by creating a table in public schema. Exactly like the `event` table in thingsboard schema
like so: 
`CREATE TABLE public.event (
  id UUID NOT NULL,
  created_time BIGINT NOT NULL,
  body TEXT,
  entity_id UUID,
  entity_type VARCHAR(255),
  event_type VARCHAR(255),
  event_uid VARCHAR(255),
  tenant_id UUID,
  ts BIGINT NOT NULL,
  CONSTRAINT event_pkey PRIMARY KEY (id),
  CONSTRAINT event_unq_key UNIQUE (tenant_id, entity_id, entity_type, event_type, event_uid)
);
`

**Comment by Ultrazombie** [comment]
Closed due to inactivity
