### ISSUE TITLE
[Question] Create group of settings (add group title) using the Settings Schema in custom widget

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#9028]
**Component**

 * UI

**Description**
I want to group the settings of the widget in different groups in order to improve the UX of the custom widget. For example, default widgets have their settings grouped under a title and surrounded by a thin line, e.g. see picture below.

How do you group the settings under the "Settings Schema" option of the custom widget?

![image](https://github.com/thingsboard/thingsboard/assets/27728926/b2d45a7f-860f-4cc5-a54c-e6004432d6e6)

**Environment**

 * OS:  macOS
 * ThingsBoard: Cloud 3.5.1
 * Browser: Chrome latest

**Comment by Philip2809** [comment]
Hey! Did you find out how to do this?

**Comment by Philip2809** [comment]
Figured it out by looking at the code, because there is of course no documentation...

```
{
    "schema": {
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck"
    },
    "lastName": {
      "type": "string",
      "title": "Last name"
    },
    "age": {
      "type": "integer",
      "title": "Age"
    },
    "bio": {
      "type": "string",
      "title": "Bio"
    },
    "password": {
      "type": "string",
      "title": "Password",
      "minLength": 3
    },
    "telephone": {
      "type": "string",
      "title": "Telephone",
      "minLength": 10
    }
  }
},
    "form": [
  ["firstName",
  "lastName"],
  ["age",
  "bio",
  "password",
  "telephone"]
],
"groupInfoes": [
    {
        "formIndex": 0,
        "GroupTitle": "test group 1"
    },{
        "formIndex": 1,
        "GroupTitle": "test group 2"
    }]
} 
```

![image](https://github.com/thingsboard/thingsboard/assets/51290462/5e1768c7-bf95-41b2-a454-2edd3ebc4531)


I have no idea how you style it, just wanted this to be here

**Comment by Civilduino** [comment]
I was trying several examples from here https://rjsf-team.github.io/react-jsonschema-form/ but did not work. However, I haven't tried in the latest update 3.6.1

I think there is some documentation here https://json-schema.org/ but it is not trivial what to search and where.

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
