### ISSUE TITLE
Alarm acknowledgment using device profile

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/thingsboard#9031]
I had been using the alarm nodes within the chain of rules and now my idea is to implement the alarms within the device profile, but I have a question that I am not being able to solve. Does anyone know how to recognize alarms with a device profile and show the user's email within the alarm widget? I managed to do it but when it is updated the alarm is cleared. Any ideas? I leave a picture of how I had done it.
![pic2](https://github.com/thingsboard/thingsboard/assets/91096768/54edb707-3801-400b-af24-639def0c52c6)

![pic1](https://github.com/thingsboard/thingsboard/assets/91096768/25aba29f-c594-4d16-9a08-9138ba1be4e5)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
