### ISSUE TITLE
[Bug] Too much data in the device table causes the default queue to block, and the project fails to run

### ISSUE THREAD

**Issue by horsex** [thingsboard/thingsboard#9032]
os:win7
thingsboard version：3.5.1
ARM：16G
DB：postgres 11
I found there seems to be a bug, when the device table data is 6 million, the project fails to start, which seems to mean that the default queue rotation training fails.When the device data is only 1 million, it can run normally

[1.txt](https://github.com/thingsboard/thingsboard/files/12246957/1.txt)

**Comment by ViacheslavKlimov** [comment]
Hi.

From the logs:

```
2023-08-02 23:19:35,688 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:350)
```

You may increase the value for `TB_QUEUE_TRANSPORT_MAX_REQUEST_TIMEOUT` (in millis),
or if you don't need SNMP support, you may set `SNMP_ENABLED` env variable to `false`.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
