### ISSUE TITLE
[Question] Logo size in fullscreen

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#9036]
**Component**

 * UI

**Description**
In white labeling, I can set the logo height. No problem, it works. But when switch the dashboard to fullscreen, the logo is very small. Where or how can I change the logo size in fullscreen?

**Comment by ssakharova** [comment]
Hello @Backdraft007,

If you are configuring the logo in the White Labelling settings, the logo height can be configured.

However, if you mean the logo that can be set in the dashboard settings to display it in full-screen mode, its height cannot be configured. 

Best regards,
Sofiia
