### ISSUE TITLE
[Bug] Scheduler not working properly.

### ISSUE THREAD

**Issue by ronit18** [thingsboard/thingsboard#9041]
* Own setup
  * thingsboard-3.5.1pe
  * tb-web-report-3.5.1pe
  * psql (PostgreSQL) 12.14 (Ubuntu 12.14-1.pgdg22.04+1)
  * OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1030-aws x86_64)
  * Browser : Chrome
  * MQTT
 
Scheduler is not working properly. I have set scheduler to send emails every day at 8. It works fine for 2 days, then it send mail sometimes. Last week it was not working properly so I rescheduled it and started working but after 2-3 days it was sending mail not everyday.

**Comment by Ultrazombie** [comment]
Please provide the thingsboard.log file when this happens again (stops sending), preferably logs for a couple of days to understand the situation.
