### ISSUE TITLE
[Question] Remote Integration - UDP/TCP protocols

### ISSUE THREAD

**Issue by Andmac12** [thingsboard/thingsboard#9042]
**Component**

 * Generic

**Description**

Someone can tell if with a UDP or TCP remote integration I can receive messages from a device using IEC 60870–5‑104 and HAC-NBh? I need confirmation for both protocols.

**Comment by myroslav-tb** [comment]
Hi @Andmac12, Thingsboard is able to integrate with the vast majority of protocols. You would need to develop your own custom converter script for the proper comunication.

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
