### ISSUE TITLE
[Question] Better widget DX and TailwindCSS

### ISSUE THREAD

**Issue by danisal** [thingsboard/thingsboard#9045]
**Component**

 * UI

**Description**
Hi, is there a better way to develop custom widgets? It's been tough to create a dialog widget since I need to save the template and then open the action... not productive at all.

And also, is there a way to avoid the crossorigin="anonymous"? Since I cannot use TailwindCSS CDN... Even if the Is Module is unchecked.

<img width="643" alt="Screenshot 2023-08-04 at 14 35 16" src="https://github.com/thingsboard/thingsboard/assets/9869755/5a39a790-d2cd-4c57-b698-a64429369bf2">

<img width="1019" alt="Screenshot 2023-08-04 at 14 34 59" src="https://github.com/thingsboard/thingsboard/assets/9869755/f1663b7a-b2d0-470a-b3ff-9e37b0949f74">

<img width="438" alt="Screenshot 2023-08-04 at 14 34 40" src="https://github.com/thingsboard/thingsboard/assets/9869755/be4e401a-c509-47fc-8fb4-9a11e744c005">

<img width="654" alt="Screenshot 2023-08-04 at 14 33 28" src="https://github.com/thingsboard/thingsboard/assets/9869755/d4d16919-b255-4a0d-9e8c-37dfc68a1003">

**Environment**

 * OS:  macOS
 * ThingsBoard: PE
 * Browser: any

**Comment by danisal** [comment]
@ashvayka can you provide any information on the subject?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
