### ISSUE TITLE
[Question] Hide sidebar without White Labeling? 

### ISSUE THREAD

**Issue by VukasNikola** [thingsboard/thingsboard#9046]
Hello, is it possible to hide the sidebar in the dashboard settings without having to get the pro version and doing it through White Labeling? Any help is appreciated, thank you! 

![image](https://github.com/thingsboard/thingsboard/assets/110349322/b90e704d-dbc5-47c4-8d28-52e110d28bdd)

**Comment by mykhailokornieiev** [comment]
Hi
There is no possibility to hide the sidebar using standard Thingsboard functionality. 
Only possible workarounds:
1) White Labeling
2) Using the home dashboard in full-screen mode. In this case, it would be necessary to add all needed functionality in this dashboard

**Comment by Ultrazombie** [comment]
Closed due to inactive
