### ISSUE TITLE
Values shown on dashboards not updated until first post_attributes_request

### ISSUE THREAD

**Issue by glancia** [thingsboard/thingsboard#905]
Hi,

I'm experiencing an annoying problem that seems to be related to cached values. When I first open my dashboard, the value coming from an attribute is completely outdated. I have this attribute updated every minute, so with the dashboard open, the value is correcty update after a post request. If I close and reopen the dashboard, the same wrong initial value reappears.

It means that my customer will see wrong values for 1 minute until first update, which is quite strange. I experience the same thing in different entities an entity types.

Same problem seem to have been reported on issue [181](https://github.com/thingsboard/thingsboard/issues/181), but no solution given.

Thingsboard 2.0.3 (but same issued observed on 1.4.0)
Ubuntu 16.04
Cassandra

Thanks 

![image](https://user-images.githubusercontent.com/26585392/42091229-e66a2720-7b7a-11e8-8030-d54fd4d5cb33.png)

![image](https://user-images.githubusercontent.com/26585392/42091282-2c9b6560-7b7b-11e8-9522-2436c9622228.png)

![image](https://user-images.githubusercontent.com/26585392/42091291-3a79307c-7b7b-11e8-8534-d0e46521d4b1.png)

**Comment by volodymyr-babak** [comment]
@glancia 
do you see this issue in the 3+ releases? 
The latest values were moved from Cassandra to PostgreSQL, and now consistency is much better.

**Comment by glancia** [comment]
Hello,

Just to let you know that I found a problem today:

![image](https://user-images.githubusercontent.com/26585392/154951279-4d779e62-2592-4cec-a1a9-05f1588497fa.png)


![image](https://user-images.githubusercontent.com/26585392/154951323-be0c0487-2b57-41ee-b8ab-deb34172b166.png)
