### ISSUE TITLE
[Question] hwo to use Alarm Rule  to filter the some  value if the telemetry key's  value is a json 

### ISSUE THREAD

**Issue by langlichong** [thingsboard/thingsboard#9051]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
A clear and concise details.

**Environment**

 * OS:  name and version
 * ThingsBoard: version
 * Browser: name and version

**Comment by Civilduino** [comment]
Use the Script node before and parse the JSON value.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
