### ISSUE TITLE
how to use threejs in widget?

### ISSUE THREAD

**Issue by qqhai007** [thingsboard/thingsboard#9053]
**Component**

 * UI

**Comment by epalchenko** [comment]
Hello @KashifAhmd,
To use three.js in a custom widget, you need to find the library you need on this site: https://cdnjs.com/
![image](https://github.com/thingsboard/thingsboard/assets/136599093/4b920088-7592-428b-9dd0-b88ef9c778fd)
Go to the library you need and copy the URL:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/09fbb120-33e9-45f0-b5f7-20b7d716d6d0)
You should paste this URL into Resources as follows:
![image](https://github.com/thingsboard/thingsboard/assets/136599093/6cba68f7-fdbe-49a0-8a92-76f31a776403)
