### ISSUE TITLE
[Question] Custom widget "get value at timestamp" function

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#9055]
**Component**
 * UI

**Description**
Im trying to get values at multiple specific timestamps in my widget. But I cant find any decent way to get these values without making use of the 'external' HTTP API:
`https://mydash.cluma.com/api/plugins/telemetry/${entityType}/${entityId}/values/timeseries`
then as parameters:
`{"keys": "temperature", "startTs": 0, "endTs": timestamp, "limit": 1, "agg": "NONE"}`

This gets the most recent value before the timestamp (value as if you were looking at it at that time). It's the behavior I want, but with the HTTP API and not directly within the widget. While this does work, its not ideal as for the widget i'm making as I would have to make this call +/- 24 times / instance.

**Environment**

 * ThingsBoard: 3.4.3PE

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
