### ISSUE TITLE
msa web-ui unpack failed: Negative time

### ISSUE THREAD

**Issue by alizamay** [thingsboard/thingsboard#9059]
[INFO] ---------------------< org.thingsboard.msa:web-ui >---------------------
[INFO] Building ThingsBoard Web UI Microservice 3.5.1-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ web-ui ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ web-ui ---
[INFO] Configured Artifact: com.google.protobuf:protoc:windows-x86_64:3.21.9:exe
[INFO] Copying protoc-3.21.9-windows-x86_64.exe to C:\Private\test\thingsboard-master\msa\web-ui\target\protoc-3.21.9-windows-x86_64.exe
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (extract-web-ui) @ web-ui ---
[INFO] Configured Artifact: org.thingsboard:ui-ngx:?:jar
[INFO] Unpacking C:\Users\tanat\.m2\repository\org\thingsboard\ui-ngx\3.5.1-SNAPSHOT\ui-ngx-3.5.1-SNAPSHOT.jar to C:\Private\test\thingsboard-master\msa\web-ui\target\web with includes "" and excludes ""
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.964 s
[INFO] Finished at: 2566-08-09T16:08:03+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (extract-web-ui) on project web-ui: Execution extract-web-ui of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack failed: Negative time -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by alizamay** [comment]
C:\Private\test\thingsboard-master\msa\web-ui>mvn -version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\IoTPlug\apache-maven-3.8.6
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_212\jre
Default locale: en_US, platform encoding: MS874
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Ultrazombie** [comment]
Closed due to inactivity
