### ISSUE TITLE
[Question] Is it possible to send notification to Whatsapp ?

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#9066]
**Component**
 * Rule Engine
 * Generic

**Description**
Is there a way to send notification to WhatsApp like SMS or Telegram ?

**Environment**

- ThingsBoard: ThingsBoard Cloud Prototype

**Comment by yohnnylim** [comment]
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/integration-with-telegram-bot/

**Comment by lstarke** [comment]
> https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/integration-with-telegram-bot/

Thank you for the reply but this tutorial is only about telegram right ? I found nothing about WhatsApp on ThingsBoard documentation.

**Comment by mde2017** [comment]
It is a lot harder to connect with Whatsapp than with Telegram. But there are 3rd-party providers, which support Whatsapp Integration. In a previous project I used Sinch:
https://www.sinch.com/products/apis/messaging/whatsapp/

They have an API you can call with ThingsBoard rulechains. Unfortunately, it is not free to use.
