### ISSUE TITLE
how to send DeviceId when Rest Api Call?

### ISSUE THREAD

**Issue by lomal788** [thingsboard/thingsboard#907]
how to send DeviceId when Rest Api Call?
When Rest api call I can send DeviceType via ${Device Type} on header.
but there is no DeviceId or Device Api key I can send.
I wanna send Device Unique Key Not DeviceName.
By The way I'm using ThingsBoard 2.0 Rule Engine

**Comment by lonwern** [comment]
You can use "originator fields" node to get "id" field.

![image](https://user-images.githubusercontent.com/5079364/42212000-7878f74e-7ee7-11e8-8d78-2b8b7571b45b.png)

**Comment by lomal788** [comment]
@lonwern that's not what I want.
under thingsboard 2.0 api call could send device id but can't send data dynamicly.
in thingsboard 2.0 could send data dynamicly but can't send device id.

I want to send device unique key (not name) when api is calling.
not put data on attribute.

**Comment by lonwern** [comment]
"originator fields" node put fields to metadata instead of put them to attributes, after that you can use these fields in "rest api call" node.

![image](https://user-images.githubusercontent.com/5079364/42254526-a769d50e-7f79-11e8-99fb-351cfe9c10db.png)

**Comment by lomal788** [comment]
@lonwern My rule chain look like this.
![image](https://user-images.githubusercontent.com/8577910/42266306-01fe58f0-7fb1-11e8-93d6-97fc04b4971e.png)
and I put data in originator fields and rest api call 
![image](https://user-images.githubusercontent.com/8577910/42266328-146a7442-7fb1-11e8-8f3c-adada6361ee3.png)
![image](https://user-images.githubusercontent.com/8577910/42266363-24d66278-7fb1-11e8-99d7-3fc845ddeec0.png)

result look like this.
![image](https://user-images.githubusercontent.com/8577910/42266378-30749348-7fb1-11e8-80d9-ac68d6d40f56.png)

**Comment by lonwern** [comment]
@lomal788 use ${deviceId} instead of ${metadata.deviceId}

**Comment by lomal788** [comment]
@lonwern omg it work thank you so much for helping me.
