### ISSUE TITLE
[Bug] Upgrade from 3.4.4 to 3.5.0 fails

### ISSUE THREAD

**Issue by YiannisBourkelis** [thingsboard/thingsboard#9088]
**Describe the bug**
I am trying to upgrade a thingsboard installation from 3.4.4 to 3.5.0 following the guide here https://thingsboard.io/docs/user-guide/install/upgrade-instructions/

However after executing the command **sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.4.4** , I get the error:

```
 ===================================================
 :: ThingsBoard ::       (v3.5.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.4.4 ...
Clearing cache to upgrade from version 3.4.4 to 3.5.0
Clearing cache [deviceProfiles]
Upgrading ThingsBoard from version 3.4.4 to 3.5.0 ...
Updating schema ...
column "status" of relation "alarm" already exists, skipping
index "idx_alarm_originator_alarm_type_active" does not exist, skipping
index "idx_alarm_tenant_alarm_type_active" does not exist, skipping
index "idx_entity_alarm_entity_id_alarm_type_created_time_alarm_id" does not exist, skipping
Schema updated.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: column "label" does not exist
  Position: 1873
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
	at org.thingsboard.server.service.install.SqlEntityDatabaseSchemaService.createOrUpdateViewsAndFunctions(SqlEntityDatabaseSchemaService.java:53)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:252)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```

How can I fix this issue so that I can upgrade the thingsboard installation?

**Your Server Environment**

* own setup
  * thingsboard 3.4.4 / Postgre Database
  * Debian GNU/Linux 11 (bullseye)

**Your Client Environment**

**Desktop (any OS):**

* Browser [all browsers]

**Smartphone (please complete the following information):**
* Device: [all devices]
* OS: [all]
* Browser [all]

**To Reproduce**
I started upgrading from 3.3.2 all the way up one by one version as instructed by the docs.

**Expected behavior**
Should upgrade thingsboard without issues

**Comment by Shangping1213** [comment]
> **Describe the bug** I am trying to upgrade a thingsboard installation from 3.4.4 to 3.5.0 following the guide here https://thingsboard.io/docs/user-guide/install/upgrade-instructions/
> 
> However after executing the command **sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.4.4** , I get the error:
> 
> ```
>  ===================================================
>  :: ThingsBoard ::       (v3.5.0)
>  ===================================================
> 
> Starting ThingsBoard Upgrade from version 3.4.4 ...
> Clearing cache to upgrade from version 3.4.4 to 3.5.0
> Clearing cache [deviceProfiles]
> Upgrading ThingsBoard from version 3.4.4 to 3.5.0 ...
> Updating schema ...
> column "status" of relation "alarm" already exists, skipping
> index "idx_alarm_originator_alarm_type_active" does not exist, skipping
> index "idx_alarm_tenant_alarm_type_active" does not exist, skipping
> index "idx_entity_alarm_entity_id_alarm_type_created_time_alarm_id" does not exist, skipping
> Schema updated.
> Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
> Unexpected error during ThingsBoard installation!
> org.postgresql.util.PSQLException: ERROR: column "label" does not exist
>   Position: 1873
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
> 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
> 	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
> 	at org.thingsboard.server.service.install.SqlEntityDatabaseSchemaService.createOrUpdateViewsAndFunctions(SqlEntityDatabaseSchemaService.java:53)
> 	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:252)
> 	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
> Unexpected error during ThingsBoard installation!
> ThingsBoard upgrade failed!
> ```
> 
> How can I fix this issue so that I can upgrade the thingsboard installation?
> 
> **Your Server Environment**
> 
> * own setup
>   
>   * thingsboard 3.4.4 / Postgre Database
>   * Debian GNU/Linux 11 (bullseye)
> 
> **Your Client Environment**
> 
> **Desktop (any OS):**
> 
> * Browser [all browsers]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [all devices]
> * OS: [all]
> * Browser [all]
> 
> **To Reproduce** Steps to reproduce the behavior: I started upgrading from 3.3.2 all the way up one by one version as instructed by the docs.
> 
> **Expected behavior** Should upgrade thingsboard without issues

Hello, has this problem been resolved? I am also facing a similar situation.

**Comment by trikimiki** [comment]
You need to check if your DB has the same structure as here https://github.com/thingsboard/thingsboard/blob/v3.4.4/dao/src/main/resources/sql/schema-entities.sql

(works for any similar "ERROR: column "X" does not exist" or version, in most cases DB schema missing something)
