### ISSUE TITLE
[Question] Aggregate Stream reprocess/deletion handling

### ISSUE THREAD

**Issue by merrittholmes7** [thingsboard/thingsboard#9092]
**Component**
Aggregate stream node

 * Rule Engine

**Description**
Please can someone describe the behaviour of the aggrgate Stream node for occurences where a telemetry value for a ts is updated (perhaps a correction of an incorrect value), or when a telemetry value is deleted. If the aggregate stream node doesn;t handle this, what is best practice to update the aggregations on these types of events?

**Environment**

 * ThingsBoard: PE

**Comment by mykhailokornieiev** [comment]
Hi. Since you have been answered on the support portal regarding this request, I am closing this ticket.
