### ISSUE TITLE
[Question] Need help to understand save to custom table node 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#9095]
**Component**

 * Rule Engine

**Description**
HI i want to know more about save to custom table node do i have to install cassandra before i can use that and how do i save my telemetry data with it . 
any type of infomation is helpful 
**Environment**

 * ThingsBoard:  3.5.1

**Comment by Andmac12** [comment]
@securitylamb , you have to setup a Cassandra cluster and then configure your Thingsboard instance to run in Hybrid database mode. This way thingsboard will use postgreSQL for the entities and Cassandra for the telemetries. 

[Read this](https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardDatabase=hybrid) and take particular attention on step 3.

**Comment by securitylamb** [comment]
> @securitylamb , you have to setup a Cassandra cluster and then configure your Thingsboard instance to run in Hybrid database mode. This way thingsboard will use postgreSQL for the entities and Cassandra for the telemetries.
> 
> [Read this](https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardDatabase=hybrid) and take particular attention on step 3.

thanks for the doc i followed the steps and installed it successfully can you tell how can i setup save to custom node inside rule chain

**Comment by Andmac12** [comment]
You have create the table you want inside Cassandra Thingsboard keyspace previously. Then simply do like [this](https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-to-custom-table).
