### ISSUE TITLE
[Question] The Things Stack Community Integration stopped working?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#9103]
**Component**
 * Integration Lora The Things Stack Community (API v3)

**Description**
Yesterday 4AM the integrations to eu1.cloud.thethings.network stopped working.
I get a 'failed to connect to MQTT broker' with 'check connection' button.
I tried subscribing with mosquitto_sub and that still works. So I would think our side is the problem but I didn't change anything.

Not sure which side isn't working correctly.
Hence if someone else got the same problems since yesterday (17/08/2023) let me know.

Thanks

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.5.1 PE

**Comment by Ultrazombie** [comment]
Please provide thingsboard.log when it happens again. We try to improve work with integrations with every release, and your log will help us with this.
