### ISSUE TITLE
[Bug]  After add one more tb-node pod telemetry does not update in k8s monolith mode

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#9108]
**Describe the bug**
After add one more tb-node pod telemetry does not update in k8s monolith mode.
When reducing the tb-node pod to one, telemetry can upload normally
Is monolith mode not support multi tb-node?

**Your Server Environment**
 * k8s helm deploy
 * ThingsBoard Version 3.3.4

**Your Client Environment**

* OS: windows10
* Browser chrome 
* Version 115.0.5790.98

* Connectivity
  * MQTT

**To Reproduce**
1. git clone thingsboard-ce-k8s project
2. set tb-node replicaCount to 2 or bigger number
3. start service and send telemetry to tb
4. telemetry not update in device page
5. reduce tb-node replicaCount to 1
6. telemetry update normally

**Comment by xiddjp** [comment]
Can i increase tb-node pod in monolith mode?

**Comment by pon0marev** [comment]
You can increase the number of replicas for the tb-monolith service, but you need to add kafka, zookeeper and redis for your deployment. It is better to switch to a microservice project (like [https://github.com/thingsboard/thingsboard-ce-k8s/tree/master/aws/microservices](https://github.com/thingsboard/thingsboard-ce-k8s/tree/master/aws/microservices)) and scale the tb-node service to the number of replicas you need.
