### ISSUE TITLE
[Bug] GKE microservice deployment error in load balance for http-transport and http integration 

### ISSUE THREAD

**Issue by leungwl2001** [thingsboard/thingsboard#9109]
**Describe the bug**
I am following this guideline for installing the tb in GCP using k8s.
https://thingsboard.io/docs/user-guide/install/pe/cluster/gcp-microservices-setup/

**Your Server Environment**
Google Cloud Platform

* Connectivity
   * HTTP

![螢幕截圖 2023-08-19 下午8 38 14](https://github.com/thingsboard/thingsboard/assets/12575432/d480cf3b-bdbc-4fe3-a29e-8e967af7ba63)
![螢幕截圖 2023-08-19 下午8 38 26](https://github.com/thingsboard/thingsboard/assets/12575432/e9690ac8-6be4-4a0e-9711-0af0cab371d6)
![螢幕截圖 2023-08-19 下午8 38 20](https://github.com/thingsboard/thingsboard/assets/12575432/fd525dd1-32b1-441c-91c5-a28cba0773b5)
![螢幕截圖 2023-08-19 下午8 38 48](https://github.com/thingsboard/thingsboard/assets/12575432/c32efd30-0d99-4876-bc1b-bebdf023243c)
![螢幕截圖 2023-08-19 下午8 39 06](https://github.com/thingsboard/thingsboard/assets/12575432/337015a9-f38a-4fe6-bade-a165aaa87faf)
![螢幕截圖 2023-08-19 下午8 39 29](https://github.com/thingsboard/thingsboard/assets/12575432/0fd7466e-19dd-407e-a197-82667a43202e)

And I get the 502 Server Error when I using the http integration link and using the http rest api to access tb.
I don't know it is a deployment error or bug for GKE. BTW, mqtt is ok. just can't using http.

**Comment by Ultrazombie** [comment]
Hello,
Please use the separate repo for k8s question and issue:
https://github.com/thingsboard/thingsboard-pe-k8s/issues or https://github.com/thingsboard/thingsboard-ce-k8s/issues
