### ISSUE TITLE
[Question] HELP REALLY QUICK QUESTION ABOUT ATTRIBUTES

### ISSUE THREAD

**Issue by VukasNikola** [thingsboard/thingsboard#9110]
Using a Rule Chain I want to add an Enrichment - originator attributes node. In this node I wish to select ALL the shared attributes. Is there a way to select all attributes? 
![image](https://github.com/thingsboard/thingsboard/assets/110349322/3a94bd30-3e21-43c0-8741-b2d0bfd87fb3)

**Comment by ezeroldan24** [comment]
That option is not available. You have to select one by one. Or at least I didn't discover it. Best regards

**Comment by Ultrazombie** [comment]
Closed due to inactivitiy
