### ISSUE TITLE
[Question] Use Rule Engine to set device 'Label' ?

### ISSUE THREAD

**Issue by george-edwards** [thingsboard/thingsboard#9114]
Rule Engine

 * Rule Engine

**Description**
I'd like to use the Rule Engine to set the Device property called 'Label'. Experimenting myself leads me to believe one can only manually set the Label; surely this is not true. Does anyone know how to achieve this? Below is my rule chain which allows me to get the value I want from a Client Attribute called 'Remark'. I get the value via an 'originator_attributes' node whenever a Device post an attribute update.. but now that I've got the value I don't know what to do with it / how to commit that to the db as the 'Label' value.

![image](https://github.com/thingsboard/thingsboard/assets/29008795/a5227b19-41ce-4b65-b8aa-f4ab791eddb0)

**Comment by skewty** [comment]
I don't think you currently can without using external "rest api call".
See the SwaggerUI for what / how to make the rest api call.

http://my.thingsboard.local:8080/swagger-ui/#

**Comment by george-edwards** [comment]
Thank you, I appreciate your response. Unfortunately there's no endpoint in the RESTful-like API that changes `label`.

**Comment by skewty** [comment]
I believe you are incorrect.  Use device-controller

![Screenshot from 2023-09-07 12-32-11](https://github.com/thingsboard/thingsboard/assets/9087223/518db1da-4ff1-4a30-a34d-6653045047b1)

**Comment by Ultrazombie** [comment]
closed due to inactive
