### ISSUE TITLE
[Question] using the gateway to PLC Modbus collect data, there will be problems when the device is reconnectedre

### ISSUE THREAD

**Issue by MaryLee7979** [thingsboard/thingsboard#9127]
* Generic
**Description**
Hello,

When I use the modbus function of the iot gateway to collect data from the PLC, I unplug the network cable and plug it in again. The Gateway will run the reconnection action. After the reconnection is successful, it can start to upload data to Thingsboard Cloud normally. After a while Then the following message will appear [""2023-08-24 14:08:13" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 184 - Subscribed to *|* with id 3 for device *"] , the data cannot be uploaded to the cloud, how can I solve it?

![image](https://github.com/thingsboard/thingsboard/assets/143065053/b0406f72-a69e-4ebf-9740-bd1e1e2e2860)

![image](https://github.com/thingsboard/thingsboard/assets/143065053/c6a0b3b1-5ac9-4337-9fd6-d2dec8b4a4fa)

[gateway_logs.txt](https://github.com/thingsboard/thingsboard/files/12426086/gateway_logs.txt)

**Environment**

 * OS:  win10 x64
 * ThingsBoard: Thingsboard Cloud
 * Thingsboard Iot Gateway:  version 3.3
 * Python :3.9.5
 *

**Comment by Ultrazombie** [comment]
Hello @MaryLee7979,
Please use the gateway issue page for the gateway issue.
https://github.com/thingsboard/thingsboard-gateway/issues
