### ISSUE TITLE
http issue

### ISSUE THREAD

**Issue by mokerosan** [thingsboard/thingsboard#9129]
**Expected behavior:**
**Communicate LilyGo-T-Call-SIM800  to thingsboard via http and gsm**

Actual behavior:
Keeps rebooting and won't start. 
Here is the monitor output:
`rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12776
load:0x40080400,len:3032
entry 0x400805e4`

Information about the Issue:
when using the instance `ThingsBoard tb(client);` To send data through mqtt it works fine with both gsm and wifi. the problem is when i change the instance `ThingsBoardHttp  tb(client, TOKEN, THINGSBOARD_SERVER, THINGSBOARD_PORT);`
this only happens using gsm. in wifi the "ThingsBoardHttp" works correctly

Steps to reproduce the behavior
You just have to upload this [code](https://www.online-ide.com/SAlYpUvZR9) to the board and install the following libraries using the ide platformio

- 	vshymanskyy/StreamDebugger@^1.0.1
- 	vshymanskyy/TinyGSM@^0.11.7
- 	thingsboard/ThingsBoard@^0.10.2
- 	plerup/EspSoftwareSerial@^8.1.0
- 	sparkfun/SparkFun BME280@^2.0.9

I can't understand what kind of conflict the thingsboardhttp instance has with tinygsm, I would really appreciate your help.

**Comment by jgarcia-atg** [comment]
Hi!
I used the example demo called "0005-arduino-sim900_send_telemetry_http" with updated library 0.11.1 and I got same error on Serial Monitor:

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
```

Any update or solution about this?

Thank you!

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
