### ISSUE TITLE
Bar chart have very thin bars

### ISSUE THREAD

**Issue by philesgilles** [thingsboard/thingsboard#913]
Good day,

I'm trying to get a time serie bar chart on V2.0.3 but the bars are extremely thin and we can barely see them. the width is of a second. so i can only see the bars when the time is short.
I'm sending datas every 5 minutes.
Anything im doing wrong ?
![screen shot 2018-07-05 at 08 48 21](https://user-images.githubusercontent.com/5814112/42306996-4f08f1e8-8031-11e8-9d87-785664547f01.png)
![screen shot 2018-07-05 at 08 48 07](https://user-images.githubusercontent.com/5814112/42307005-54431350-8031-11e8-812e-e253c59b40d3.png)

**Comment by glancia** [comment]
I have the same problem. I presume that the scale of the x-axis is divided into seconds. If you have only one set of data every 5 minutes, the width of your bar is 1/300. Aggregating the date might solve this issue, but in my case it's creating another one. I have my data in a monthly basis, so the bars get invisible. If I aggregate, I have no option to aggregate by calendar month, but by 30 days and this messes up the chart.

**Comment by glancia** [comment]
Changing it to a line chart also solves the problem, since the chart forces to keep a continuous line.
