### ISSUE TITLE
[Question] MQTT integrations Credentials with script

### ISSUE THREAD

**Issue by JoyceWithCat** [thingsboard/thingsboard#9130]
**Component**

 * UI

**Description**
Hi all, i am woring on the mqtt integrations in thingsboard. And our client requires us to use username+timestamp with encryption string as the username. Is there any way for us to input the username by js script in UI? Or any other way to work with? Thank you.

![image](https://github.com/thingsboard/thingsboard/assets/20220163/bb1b4c95-5864-4fc8-b5d4-296b8e427e80)

**Comment by ashaforost** [comment]
Hi @JoyceWithCat 

It sounds like a custom extension for your browser - not something thingsboard team has ever worked with. Thingsboard doesn't support this use case out of the box. 
As I can see, the thingsboard community doesn't have any suggestions either, so I'll close this issue as stale. Feel free to create a new issue if you're still looking for a solution.
