### ISSUE TITLE
[Question] About "Add to group" option in rule chain

### ISSUE THREAD

**Issue by JoyceWithCat** [thingsboard/thingsboard#9131]
**Component**

 * UI
 * Rule Engine

**Description**
Hi all, i just find that if i use "add to group" node with a device under a customer, the device will be assigned to the customer group. Can I choose to assign the device to device group rather than customer group if the device is owned by customer? Thank you.

**Comment by myroslav-tb** [comment]
Hi @JoyceWithCat, in the  "add to group" rule node you can specify to which group name device will be assigned.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/c239ce99-0178-4b71-8e33-cb8c713e62f4)
Best regards,
Myroslav

**Comment by Ultrazombie** [comment]
Closed due to inactivity
