### ISSUE TITLE
[Bug] OTA Packages Service helper incorrectly calling http API for getOtaPackage

### ISSUE THREAD

**Issue by jverduci** [thingsboard/thingsboard#9134]
Things PE 3.5.1

![Screen Shot 2023-08-28 at 4 36 50 pm](https://github.com/thingsboard/thingsboard/assets/80398379/0f688453-6d14-487b-8353-ba2604fd948a)

![Screen Shot 2023-08-28 at 4 48 37 pm](https://github.com/thingsboard/thingsboard/assets/80398379/e0112f86-7b75-4501-a9a0-964ef96dd7a4)

https://github.com/thingsboard/thingsboard/blob/release-3.5/ui-ngx/src/app/core/http/ota-package.service.ts 

OTA package service's

public getOtaPackage(otaPackageId: string, config?: RequestConfig): Observable<OtaPackage> {
    return this.http.get<OtaPackage>(`/api/otaPackages/${otaPackageId}`, defaultHttpOptionsFromConfig(config));
  }
  
  
The above function throws an error when trying to execute, it seems like there isnt a /api/otaPackages though based on the swagger doc's, that takes a singular OTA package id. This perhaps should be calling '/api/otaPackage/${otaPackageId}`, where the 's' has been omitted from Package**s**

**Comment by SuminDenis** [comment]
Hi @jverduci,

Thank you for informing us about this issue.

We confirmed this issue is a bug in our system, and our product team has already been notified via a product ticket PROD-4054.

Currently, there is no timeframe for fixing this bug. We will let you know as soon as it is fixed.

**Comment by SuminDenys** [comment]
Hi @jverduci,

We are closing this issue for now. If you need to update the status of the prod ticket or have any further questions, please feel free to reopen this issue.
