### ISSUE TITLE
[Question] How to pass msg/metadata keys as config params to custom rule nodes?

### ISSUE THREAD

**Issue by jverduci** [thingsboard/thingsboard#9135]
Currently implementing some custom rules nodes and looking to set a config item of the node based on a value of a message being passed to it. I understand theres a seperate UI element involved in styling the node, however is this also where the msg/metadata items are also enabled to be passed through?

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
