### ISSUE TITLE
[Question] trigger rule chain from related entity

### ISSUE THREAD

**Issue by qoentz** [thingsboard/thingsboard#9137]
**Component**

 * Rule Engine

**Description**
Hello! Is it possible to trigger a rule chain connected to a specific asset profile, if the asset in question has a relation to the device sending the message? Couldn't get this to work properly

**Environment**
 * OS:  Windows/Mac
 * ThingsBoard: 3.5 CE
 * Browser: Firefox (latest)

**Comment by mykhailokornieiev** [comment]
Hi
I'm not sure what actually you are trying to achieve and if it still relevant, but you can use device profile where you can define rule chain for all processing. In this case, if you want to duplicate some data from devices to related assets, it will be enough to use something like "duplicate to related" or "change originator" rule node.
