### ISSUE TITLE
[Question] Engineering best practices for Dashboards and Widgets

### ISSUE THREAD

**Issue by elgutierrez** [thingsboard/thingsboard#9139]
**Component**
 * UI

**Description**
I'm trying to understand what would be the best workflow for me and my team. I'm finding it hard to apply standard engineering best practices when working with the **Thingsboard Cloud** platform.

I have enabled the **Version Control** feature so all customizations made are kept in our own Github repository, which is great. But nevertheless, we faced issues when multiple developers were editing the same dashboard concurrently through the UI and we lost our changes. Also, I haven't found the optimal way to work as a team of developers on different dashboards and custom widgets. I'd love to be able to:

1. Create a pull request and make the changes go through a code review process.
2. Having different environments and being able to move validated changes from a staging environment to a production env
3. Being able to use my preferred IDE (VS Code) on my local environment, and also to use default Angular code and tooling (and not needing to use the online editor, which is limited) 
4. Being able to use Typescript

I can't find this subject related to developer experience in the documentation, nor in the Thingsboard github repo. Could you point me out where I can find this information?

**Comment by dm9de** [comment]
I'm also very interested in this question. If I could extend the terms of reference of the question slightly, it would also be great for guidance on good engineering practice around developing rule chains.

**Comment by danisal** [comment]
+1

**Comment by danisal** [comment]
@devaskim, sorry to tag you out of the blue, but do you have any insights on these questions? We are facing similar development issues and would be great if we have any guidance 🙏

**Comment by devaskim** [comment]
Hey guys,
Vital theme, but I haven't any ready answers. My team is only me)
As for widget editor, it is a big pain. But only what we could is just to look at its code and try to develop some kind of plugin that we will integrates with TB REST API.

**Comment by elgutierrez** [comment]
> I believe your best bet is to clone: https://github.com/thingsboard/thingsboard-extensions and work out of your own repo.
> 
> I have not yet figured out how to put ThingsBoard into debugging mode so it runs the angular code in non production mode and browser add-ons like Angular dev tools and Redux DevTools work though.
> 
> You will also want to put server logging into DEBUG mode.
> 
> Edit: `/etc/thingsboard/conf/logback.xml` and set: `<logger name="org.thingsboard.server" level="DEBUG" />`.
> 
> The docs at: https://thingsboard.io/docs/user-guide/troubleshooting/#enable-certain-logs have incorrect path.

Thanks, I finally ended up by using this solution and it works pretty well locally. I run a docker container with the TB CE, and I run the `thingsboard-extensions` dev server. Then, I copy the bundled script generated and add it to the resources tab, checking the `Is module` checkbox. For production, I deploy this bundle to S3 and update my Thingsboard Cloud instance.

But this manual step is pretty annoying and I'd love to automate it. I started experimenting with a Github Action that will listen to changes on the widgets folder. There's a `{widget}.manifest.json` file inside each widget's folder that contains the `Widget descriptor` for each widget. If there's a create/update/delete of one of those widgets, I call the TB REST API and update the Widget accordingly. Unfortunately I had to stop the experimentation because of lack of time, but I'd be willing to create an open source repo if someone else would like to contribute to it

**Comment by skewty** [comment]
You can run production build 
```shell
cd ${TB_EXTENSION_WORK_DIR}
mvn clean install -DskipTests
```
and copy the generated .jar file onto your production ThingsBoard server into `/usr/share/thingsboard/extensions` and restart that ThingsBoard service and it should be "built-in".

**Comment by elgutierrez** [comment]
Thanks for the tip, @skewty but I use the hosted Thingsboard Cloud solution, so I don't have access to the servers/configs

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
