### ISSUE TITLE
Installation of TB 2.03 on a RaspberryPi 

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#914]
Hello there,

I want to try out your latest version of thingsboard on my Raspberry Pi. But when I start the installation script  `/usr/share/thingsboard/bin/install/install.sh` I get the following error:

`Unrecognized VM option 'UseCondCardMark`
`Error: Could not create the Java Virtual Machine.`
`Error: A fatal exception has occurred. Program will exit.`
`Thingsboard installation failed!'`

This is my Java version:

`java version "1.8.0_65"`
`Java(TM) SE Runtime Environment (build 1.8.0_65-b17)`
`Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)`

I already found that `UseCondCardMark` is added to JAVA_OPTS in the thingsboard.conf file. 

I don't want to remove options and regret it later on. 

Any ideas on that ?

Thanks in advance!

**Comment by Tangerino** [comment]
Found the same issue

**Comment by vparomskiy** [comment]
Please use ignoreunknownvmoptions flag. Fix well be released in TB 2.1

**Comment by milanlacok** [comment]
Sorry for adding to this post but could you explain how ti use ignoreunknownvmoptions flag?

Thanks in advance.
