### ISSUE TITLE
How can I create/apply filter in javascript block (not from UI)

### ISSUE THREAD

**Issue by PNilwatcharaporn** [thingsboard/thingsboard#9140]
**Component**

 * UI
 * Generic

**Description**
I created my own filter it works well when I applied a filter in widget datasource settings. but how can I applied a created filter in javascript block (e.g. when I create custom action with HTML template). I've just found that  `self.widgetContext.aliasController.filter`gives all my created filter. but how can I selected one of those filter and apply to my data ?

My objectives are to add header button and then it will show dialog containing list of available devices. now I can show checkable box. The problem is I have no idea that how to integrated the checked devices with data filter 

**Environment**

 * OS:  Raspberry PI
 * ThingsBoard: 3.5.1
 * Browser: Chrome
![Screenshot 2566-08-28 at 20 05 42](https://github.com/thingsboard/thingsboard/assets/116630350/53a59669-f907-487b-bfd5-1c92ba6bbd93)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
