### ISSUE TITLE
[Question] how can i assign particular set of device to particular user group ?

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#9146]
Hi i want to show particualr device to particualr user group using rbac and not show other device to it basically if i use device group than i have to assign device to customer which means all the different user group will be able to see all the device as the are under same customer i dont want  that i want each group to have to seprate set of devices and dashboard which is not visible to other user group 
i am using thingsboard 3.5.1 PE 
i did manage to achive that using entity grouping but i dont think that is the correct way of doing things

**Comment by EGerry** [comment]
I've the same issue. When you think about giving a solution ? tks.

**Comment by ssakharova** [comment]
Hello @securitylamb, @EGerry,

First, you will need to put all devices for which you want to restrict/grant access into separate device groups.
After that, you will need to give these device groups the Group roles created earlier (Entity group Read-only, Entity Group Write, or your custom roles that would satisfy your specific needs).

**Comment by EGerry** [comment]
Thank you for you reply.
EG

**Comment by EGerry** [comment]
Thank you for you reply.
But this it does not work if the device is paired with a customer.
I paired 2 devices to a new group, one of which with customer. I only see the one without customer.

how can I do?

Thanks
Elisa

**Comment by ssakharova** [comment]
Hello @EGerry,

Please clarify what you mean by 'paired'. Assigned?

**Comment by EGerry** [comment]
Yes, assigned to a customer.

**Comment by ssakharova** [comment]
Hello @EGerry,

You need to either remove the device from the customer (which will move it to the 'All' device group under the tenant) or assign a second device to the same customer where the first device is located. This will allow you to add both devices to the device group.

**Comment by ssakharova** [comment]
Closed due to inactivity.
