### ISSUE TITLE
[Question] can we assign devicegroup and  dashbaord group to particualr user and not to other users ???

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#9149]
**Component**

 * Generic

**Description**
basically i want to assign device to be shown to particualr user  only  can anyone elobrate if that is even possible 

**Environment**

 * OS:  name and version
 * ThingsBoard: 3.5.1PE
 * Browser: name and version

**Comment by mykhailokornieiev** [comment]
Hi
There is no such possibility by design of Thingsboard. If you want to assign device/dashboard group to only one user, then you will need to create a separate user group for them.

**Comment by Ultrazombie** [comment]
Closed due to inactive
