### ISSUE TITLE
Nashorn engine in TB2.0 may have multithread-safe problem.

### ISSUE THREAD

**Issue by cityant** [thingsboard/thingsboard#915]
We have a rule chain in which four scripts rule-nodes (transform type) are connected to a message type rule-node before in parallel and a savetimeseries rule-node behind.  These scripts are used to parse different parts of a encoded message to telemetries and then be saved into db. In each script, there is a variable has the same name as the ones in three other scripts but doesn't has a 'var' keyword ahead. When executing the rule chain, the results are not correct and random. 

We did some investigation, and found it may be a MT-safe problem on nashorn. We tried to add 'var' before the four same-name variable and the problem disappeared.  And we tried to a synchronized block around execution of a script in rule engine, problem gone too. 

We think this variable is a global variable and may be accessed by multithreads on Akka actors which is the root cause. There is a blog for such problem about multithread-safe of nashorn: 
https://blogs.oracle.com/nashorn/nashorn-multithreading-and-mt-safety

We don't know if it's designed in this way, however, from developer of rule chain point of view, all variables in the script should be local and global variable should be restricted and isolated in the context of execution of the script.

**Comment by vparomskiy** [comment]
You are right. Thank you for reporting. We will address this issue in next releases.

**Comment by ashvayka** [comment]
The issue is not with the multi-threading but with the use of the "var" variable. without "var" you make a global variable and multiple JS executions may change it's state. We can't put the synchronized block for performance reasons. That is why starting 3.3.x we updated the JS editor to highlight such problems and do not allow global variables in the functions.
