### ISSUE TITLE
[Question] How to put datasource inside JS on widget without selection?

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#9152]
**Component**

 * UI

**Description**
I want to select default timeseries inside widget. Why? I need to select different timeseries based on model device, so I need to subscribe to the data and show it on Timeseries Table. Can I do this?

For example, I need to display the "myTimeseries" timeserie without the need of user selection.

with the code below I can get the data I need, but how to display it on timeseries table?

**code inside onInit()**
`
let attributeService = self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('attributeService'));

    let maxTime = self.ctx.timeWindow.maxTime;
    let minTime = self.ctx.timeWindow.minTime;
    
    let attributesDevice = attributeService.getEntityTimeseries(datasource,["myTimeseries"],minTime,maxTime,1000).subscribe((r) => {
           console.log('response', r);
    })
`

**Environment**

 * ThingsBoard: PE 3.4.4

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
