### ISSUE TITLE
[Question] How to disable column visibility on Timeseries Table?

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#9153]
**Component**

 * UI

**Description**
I need to disable column visibility based on device model. I thought about getting an attribute inside javascript and then disabling the columns that are not needed. Is this possible?

**Environment**

 * ThingsBoard: PE 3.4.4

**Comment by evanderbird** [comment]
yes you can hide the data-key you want

**Comment by Ultrazombie** [comment]
Closed due to inactivity
