### ISSUE TITLE
[Question] RPC to Modbus Device

### ISSUE THREAD

**Issue by greytideas** [thingsboard/thingsboard#9158]
**Component**
 * TB Gateway - modbus
 * RPC

**Description**
I have successfully configured and deployed a modbus connector via tb_gateway and have timeseries telemetry publishing to the tb service.

My current challenge is that my customers require RPC of their modbus devices over the TB UI.

I have been struggling to learn how to achieve this with the tb gateway and tb service. I'm trying to understand how to extend the gateway's modbus.json config to include the write registers that can be driven from RPC commands in TB.

Would anyone be able to point me in the right direction to achieve success in this regard?

**Environment**
 * OS:  Debian 11
 * ThingsBoard: 3.3
 * Browser: Chrome 116.0.5845.111

**Comment by Ultrazombie** [comment]
Hello @greytideas,
Please feel free to re-open this ticket to the gateway repository, as it's a separate product.
https://github.com/thingsboard/thingsboard-gateway/issues
