### ISSUE TITLE
CANT START SERVICE THINGSBOARD

### ISSUE THREAD

**Issue by fariz** [thingsboard/thingsboard#916]
I am uisng window10 when we want to start the service it show

![image](https://user-images.githubusercontent.com/65761/42373351-da4983a4-813e-11e8-9ea8-c0168d8a15a5.png)
 
is there any help please :)

**Comment by mp-loki** [comment]
Did you [install](https://thingsboard.io/docs/user-guide/install/windows/) the service in the first place? The command to start it on Windows is `net start thingsboard`
