### ISSUE TITLE
[Question]  hidden the top menu bar

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#9161]
Component

White Label

Description
Is there a way to hidden the top menu bar ?

![image](https://github.com/thingsboard/thingsboard/assets/7483656/2a416f0d-ad1f-47bb-a397-12a12d6dd762)

Final result can be something like this:

![image](https://github.com/thingsboard/thingsboard/assets/7483656/6ba27b12-a98a-484f-80dc-daa93048bf4d)

Environment

ThingsBoard: ThingsBoard Cloud Prototype

**Comment by mykhailokornieiev** [comment]
There is no standard solution for your purpose, but you can hide it via White Labeling -> Advanced CSS
![image](https://github.com/thingsboard/thingsboard/assets/115699895/7fa6dd92-b673-4fcb-9cb0-ac3ad49881f0)
```
.mat-toolbar.tb-primary-toolbar.mat-primary.mat-toolbar-single-row {
    display: none !important;
}
```

**Comment by h-takado** [comment]
In addition, please let me know.
If I use the above method, my account information will also be lost.
Is there any way to delete just the dashboard menu?
The reason is that we don't want users to use that menu.
![erase](https://github.com/thingsboard/thingsboard/assets/111136063/9235b971-55e6-418c-abb9-5d1f82ca3079)

**Comment by mykhailokornieiev** [comment]
@h-takado 
```
.mat-toolbar-tools {
    visibility: hidden !important;
}
```
You can use DevTools (F12) for reverse engineering, so you would be able to get the necessary elements and change their settings

**Comment by mykhailokornieiev** [comment]
@h-takado better use this one, because the previous one is related not only to this dashboard menu (it will make hidden add device button, etc)
```
.tb-breadcrumb {
    visibility: hidden !important;    
}
```

**Comment by h-takado** [comment]
Thank you!
You also showed me how to reverse engineer it so I can solve it myself in the future!

**Comment by kaichh** [comment]
I would like to follow up another one.

Is it possible to set the sidebar hidden with a toggle for wide screen? From my observation, currently the sidebar would only hidden in viewport width smaller than 960px.
