### ISSUE TITLE
creation of custom widget in thingsboard v 3.5.1

### ISSUE THREAD

**Issue by kpakhi** [thingsboard/thingsboard#9176]
i want a widget with 2 button only for navigation purpose
' button 1 ' is using for navigating to next dashboard &
' button 2' is using for previous dashboard 

*So basically this same widget will make it for all dasboard 
* i want to make navigation to Next dasboard & Previous dashboard

So how to set predefined dasbaord id &  state for button 1&2  for this widget present in all dasboard 

Please help ,
 i am a beginner in thingsboard  your support will help me a lot

**Comment by ssakharova** [comment]
Hello @kpakhi,

In that case, please consider implementing widget actions in the default widgets that allow users to navigate to the next and previous dashboards.

To learn how to use and configure widget actions, please refer to our documentation - https://thingsboard.io/docs/pe/user-guide/ui/widget-actions/

To get more examples of using custom actions, you need to click on the question mark while configuring a widget action. Please see the screenshots below:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/97888d73-5d0d-4d09-b30d-d429fdffab91)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/c0d03142-50bb-48f5-957a-17d1e0b2c08f)

Using these examples, you can easily develop more complex custom actions.

![image](https://github.com/thingsboard/thingsboard/assets/98035385/8073a2a5-8053-49ee-8172-6669ec1f52b5)

In addition, new versions of the Thingsboard include Navigation widgets, which may help you achieve the desired result. 

![image](https://github.com/thingsboard/thingsboard/assets/98035385/5bd2eb8e-7c55-47e2-9663-9d7baeeee848)

Best regards,
Sofiia
