### ISSUE TITLE
[Question] Checking the counter value on a particular day

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9178]
Hello
I have a counter that increases daily and this increase is not constant.
It may increase by 10 units one day and 500 units the next.
Is it possible that I can check to see how many units have increased in the last day or last week?

**Comment by ssakharova** [comment]
Hello @m3relec,

In most cases, this can be realized through developing rule chain logic. 
However, if this approach is not suitable for you, please provide us with more information about your desired result.
