### ISSUE TITLE
[Question] Comunication between local pc and remote rpi via mqtt

### ISSUE THREAD

**Issue by jorgrde1** [thingsboard/thingsboard#9181]
**Component**

 * Rule Engine

**Description**
Send mqtt msg from one pc to a rpi via thingsboard platform

**Environment**

 * OS:  Ubuntu 22.04.2 LTS
 * ThingsBoard: v3.5.1 

Hello there!
My question is about if it is possible to send msgs via mqtt using the thingsboard topics from my local computer to my remote Raspberry, I've seen that i can subscribe my rpi to the topic v1/devices/me/rpc/request/+ and receive the mqtt message that the Thingsboard server send when I use a GPIO controller panel on the device panel, but if I publish a message with a python script using mqtt libreries it doesnt work, it's there a way to do it?

My purpose is to send messages to the rpi to read there and execute some commands remotely.

Here's the documentation i found to subscribe topics from rpi and change gpio status with the panel on TB: **https://thingsboard.io/docs/samples/raspberry/gpio/**

Also this is the python script I use to publish msg on the same topic that seems is not working. 
```
import paho.mqtt.client as mqtt
import json

THINGSBOARD_HOST = 'ingress-radiatus.dataspace2.slap53.iti.es'
ACCESS_TOKEN = 'NodoToken6'

# Crear un cliente MQTT
client = mqtt.Client()
# Establecer el nombre de usuario y contraseña (access token)
client.username_pw_set(ACCESS_TOKEN)
# Conectar al servidor ThingsBoard
client.connect(THINGSBOARD_HOST, 9101, 60)

# Definir el mensaje que deseas enviar
request_message = {"method":"setGpioStatus","params":{"pin":29,"enabled":"true"}}


# Convertir el mensaje a JSON
json_message = json.dumps(request_message)

# Publicar el mensaje en el topic deseado
client.publish('v1/devices/me/rpc/request/1', json_message, qos=1)

# Desconectar el cliente MQTT
client.disconnect()
```

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
