### ISSUE TITLE
[Bug] Thingsboard 3.3.2 fails to start after recent OpenJDK upgrade

### ISSUE THREAD

**Issue by dmohns** [thingsboard/thingsboard#9188]
**Describe the bug**

This isn't a full bug report yet, I will provide all details later, if I got more hints that these might be related.

Our ThingsBoard instance started failing at September 1st. 

The only thing I noticed is that around the same time `openjdk` was upgraded from `11.0.20+8-1ubuntu1~20.04` to `11.0.20.1+1-0ubuntu1~20.04`.

Did anyone notice similar issues?

**Your Server Environment**

* own setup: Ubuntu 20.04, kafka on same machine + dedicated Postgres instance

**Comment by xalt7x** [comment]
Hello @dmohns .
Generally minor `openjdk` updates  don't break applications, so there might be some different issue.  
Nevertheless, if you still have an issue, please provide thingsboard.log.

**Comment by dmohns** [comment]
> Hello @dmohns . Generally minor `openjdk` updates don't break applications, so there might be some different issue. Nevertheless, if you still have an issue, please provide thingsboard.log.

Hey, thanks for the response. Ok, good to know. 

The incident is too far in the past, I won't be able to access logs anymore in a reasonable manner. Hence I'll close this issue.
