### ISSUE TITLE
[Question] Custom map widget with header

### ISSUE THREAD

**Issue by TamaraTakacs** [thingsboard/thingsboard#9190]
**Component**
 * UI
 * Widget 

**Description**
I would like to create a custom map widget with the existing functionalities of the native map - only extend with a custom header - custom title and subtitle, toggle buttons, "expand to full screen" button (similar to what already exists in 3.5 recent-dashboards-widget, in the image below).

I duplicated the native (Google) map widget and tried to make a custom widget from it, but any html I add is hidden by the map itself as that fills the root container. My question is: is it somehow possible to "embed" this native map in a new widget in a container I can control, with all existing functionalities? 

<img width="609" alt="image" src="https://github.com/thingsboard/thingsboard/assets/131176269/2d7e2520-d1ee-40f7-91ed-21e3bcbf96af">

**Environment**
 * ThingsBoard: v3.4

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
