### ISSUE TITLE
client RPC request fails

### ISSUE THREAD

**Issue by GeirFrimann** [thingsboard/thingsboard#920]
Using TB 2.0.3 I'm trying to request the servers date & time by sending the following request: 
{
    "method": "getTime",
    "params": {}
}
with the topic "v1/devices/me/rpc/request/2".

I have enabled logging on the Message type switch node in the root rule chain, and also on a log node with a RPC request relation to the Message type switch node.
The message shows up in the debug output on the Message type switch node, but not on the log node (Debug mode are enabled on both nodes). 
After one minute the device gets the following response: 
{"error":"Timeout during processing of message by the server!"}.

Question is why doesn't the message show up in the debug on the log node?
Any suggestions of how to request the server's date & time with the new rule chain would be much appreciated!

**Comment by yingzhangOK** [comment]
GeirFrimann, do you have a solution about this problem, please share if you got, thanks a lot.

**Comment by GeirFrimann** [comment]
> GeirFrimann, do you have a solution about this problem, please share if you got, thanks a lot.

I had forgot about that issue, but now I tried to solve it, and I did!
Here is what I did:
Method for sending RPC request to server:
```
void requestServerRPC(String MethodName, int RequestNo)
{
	String payload;
	StaticJsonDocument<200> doc;
	doc["method"] = MethodName;
	doc["params"] = "";
	serializeJson(doc, payload);
	String topic = "v1/devices/me/rpc/request/" + String(RequestNo);
	client.publish(topic.c_str(), payload.c_str());
}
```

Method for handling incoming response from server:
```
void on_message(char *topic, byte *payload, unsigned int length)
{
	StaticJsonDocument<200> data;
	auto error = deserializeJson(data, payload);
	if (error)
	{
		Serial.print(F("deserializeJson() failed with code "));
		Serial.println(error.c_str());
		return;
	}
	
	JsonObject object = data.as<JsonObject>();
	
	if (String(topic).startsWith("v1/devices/me/rpc/response"))
	{
		String MethodName = object["method"];
		if(MethodName == "getTime")
		{
			String dt = object["params"];
			CurrentTime = dt;  //My global time variable
		}
	}
}
```
Add following to the client connect method:
```
void client_connect()
{
	//Add code for connecting to MQTT Broker
	//...
	int counter = 1;
	client.setCallback(on_message);
	client.subscribe("v1/devices/me/rpc/response/+");
	
	requestServerRPC("getTime", counter++);
}

```
On the Rule chain, add a script node after the Message type switch with a "RPC Request from device" connection, and then a rpc call reply node:
![image](https://user-images.githubusercontent.com/17338046/62888137-f9ea1380-bd3e-11e9-8a17-c8edab5109e5.png)
Here is the script code:
```
var responseMsg = {};
var Method = msg.method;
var today = new Date();
var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
responseMsg.method = Method;
responseMsg.params = time;
msgType = 'RPC message';
return {msg: responseMsg, metadata: metadata, msgType: msgType};
```
Of course if you have several different requests to the server you filter on the method name.

Hope this helps, good luck!
