### ISSUE TITLE
is there any way to fetch Customer ID using Token / Username & password?

### ISSUE THREAD

**Issue by mohan-m-u** [thingsboard/thingsboard#921]

**Comment by vparomskiy** [comment]
Yes

**Comment by mohan-m-u** [comment]
can you tell me how ?

**Comment by eykamp** [comment]
Are you using Python?

**Comment by vparomskiy** [comment]
You can extract CustomerID from JWT token.
For example, your JWT token is
`eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwYXJvbXNraXlAZ21haWwuY29tIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiJlZjNjZWM0MC00MjM0LTExZTgtYmMzOC0wOWY2OTIzMjZmYTciLCJmaXJzdE5hbWUiOiJWaXRhbGl5IiwibGFzdE5hbWUiOiJQYXJvbXNraXkiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiYTBjOWY0NjAtMzQwOS0xMWU4LWJjMzgtMDlmNjkyMzI2ZmE3IiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTMxNDUwMDUxLCJleHAiOjE1MzE0NTA5NTF9.GylqoPiErPMgbMQbpBw6mbpyNPuiZ8ktt_YjhIrNuEjahzVSRrqUY3JBiiEeLpuh4jn54rwsfc6lqMZRpArzlQ`

Then, you can decode it as a Base64 string. Here is an online tool that can do this:
http://www.utilities-online.info/base64/#.W0gUdXYzbcF
Output:

> 
> {
>   "alg": "HS512"
> }{
>   "sub": "paromskiy@gmail.com",
>   "scopes": [
>     "TENANT_ADMIN"
>   ],
>   "userId": "ef3cec40-4234-11e8-bc38-09f692326fa7",
>   "firstName": "Vitaliy",
>   "lastName": "Paromskiy",
>   "enabled": true,
>   "isPublic": false,
>   "tenantId": "a0c9f460-3409-11e8-bc38-09f692326fa7",
>   "customerId": "13814000-1dd2-11b2-8080-808080808080",
>   "iss": "thingsboard.io",
>   "iat": 1531450051,
>   "exp": 1531450951
> })jค쳠lě䜺麲4뢧ɭ刡"㮒6ፔᮥܐb臋樸s骱䩂쥀

**Comment by mohan-m-u** [comment]
Ok Cool thanks ...  Ok one more question is there any REST API to fetch CustomerID, instead of decoding   JWT token.

**Comment by eykamp** [comment]
You can use my library (unfinished, but will accomplish this task), or you can extract the code and embed it in your own scripts.  It's an MIT license, but if you make any improvements, please consider submitting a PR.

```
# untested!
from thingsboard_api_tools import TbApi   # pip install git+git://github.com/eykamp/thingsboard_api_tools.git --upgrade

tbapi = TbApi(url_with_port, username, password)  #<== define these somewhere
cust = tbapi.get_customer(cust_name) #<== customer whose id you want
print(tbapi.get_id(cust))

**Comment by mohan-m-u** [comment]
@vparomskiy  @eykamp  Thanks for your valuable Comments .

**Comment by seikosantana** [comment]
I'm on javascript, and a simple atob doesn't work on that.

**Comment by Delapouite** [comment]
Have a look at this StackOverflow answer https://stackoverflow.com/a/38552302/232943

**Comment by seikosantana** [comment]
> Have a look at this StackOverflow answer https://stackoverflow.com/a/38552302/232943

Thanks a lot! Works like a charm.
