### ISSUE TITLE
[ERROR] COMPILATION ERROR : 

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#922]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] E:\git\thingsboard\dao\src\main\java\org\thingsboard\server\dao\nosql\RateLimitedResultSetFuture.java:[48,47] 错误: 不兼容的类型: 无法推断类型变量 I,O
[ERROR]     (参数不匹配; lambda 表达式中的返回类型错误
      ResultSetFuture无法转换为? extends O)
  其中, I,O是类型变量:
    I扩展已在方法 <I,O>transform(ListenableFuture<I>,Function<? super I,? extends O>)中声明的Object
    O扩展已在方法 <I,O>transform(ListenableFuture<I>,Function<? super I,? extends O>)中声明的Object
E:\git\thingsboard\dao\src\main\java\org\thingsboard\server\dao\nosql\RateLimitedResultSetFuture.java:[49,16] 错误: 不兼容的类型: lambda 表达式中的参数类型不兼容
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by mp-loki** [comment]
I'm sorry but no one in our team can read Chinese

**Comment by caoyingde** [comment]
@mp-loki 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project dao: Compilation failure: Compilation failure:
[ERROR] E:\git\thingsboard\dao\src\main\java\org\thingsboard\server\dao\nosql\RateLimitedResultSetFuture.java:[48,47]Error: incompatible type: inferred type variable I, O [ERROR] (parameter mismatch; return type error in lambda expression ResultSetFuture can't be converted to extends O), I, O is a type variable: I extension has been declared in method <I, O>transform Extension has been declared Object in method <I, O>transform (ListenableFuture<I>, Function<? Super I, extends O>)
E:\git\thingsboard\dao\src\main\java\org\thingsboard\server\dao\nosql\RateLimitedResultSetFuture.java:[49,16] Error: incompatible type: parameter type incompatible in lambda expression.

**Comment by SergMeleshko** [comment]
Hello @caoyingde 
Is this issue still relevant on the latest version of ThingsBoard?
