### ISSUE TITLE
[Question] how to reset sysadmin password from postgres

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9221]
Hello
I forgot the admin password and the option to forget the password does not send the email.
Is there a way to find or change the password through the Postgres database?

**Comment by trikimiki** [comment]
Hi!
This will restore the sysadmin password to default "sysadmin" (suppose default Postgre user/host/db-name are used):
```
psql -U postgres -h localhost -d thingsboard
```
```
update user_credentials SET password = '$2a$10$YMyxoU0hMOLmd9D7tz/dQeDY3fkXRAv8C023F6hzx2gVB9dTBUpq6' WHERE user_id=(select id from tb_user where authority = 'SYS_ADMIN');
```
