### ISSUE TITLE
[Bug] Error installing from source code on Ubuntu 20.04 ThingsBoard Server UI .............................. FAILURE

### ISSUE THREAD

**Issue by jeovajireh** [thingsboard/thingsboard#9222]
Following the tutorial below:
https://thingsboard.io/docs/user-guide/install/building-from-source/

**Describe the bug**

[INFO] ➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
[INFO] ➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
[INFO] ➤ YN0013: │ zone.js@npm:0.13.0 can't be found in the cache and will be fetched from the remote registry
[INFO] ➤ YN0000: └ Completed in 2s 184ms
[INFO] ➤ YN0000: ┌ Link step
[INFO] ➤ YN0007: │ core-js@npm:3.29.1 must be built because it never has been before or the last one failed
[INFO] ➤ YN0007: │ date-fns@npm:2.0.0-alpha.27 must be built because it never has been before or the last one failed
[INFO] ➤ YN0007: │ postinstall-prepare@npm:2.0.0 must be built because it never has been before or the last one failed
[INFO] ➤ YN0007: │ esbuild@npm:0.17.8 must be built because it never has been before or the last one failed
[INFO] ➤ YN0007: │ nice-napi@npm:1.0.2 must be built because it never has been before or the last one failed
[INFO] ➤ YN0000: └ Completed in 1m 1s
[INFO] ➤ YN0000: Done with warnings in 1m 54s
[INFO]
[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn build) @ ui-ngx ---
[INFO] Running 'yarn run build:prod' in /home/thingsboard-3.5.1/ui-ngx
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] An unhandled exception occurred: Cannot read properties of undefined (reading 'pluginOptions')
[INFO] See "/tmp/ng-uxxgWp/angular-errors.log" for further details.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.5.1:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.650 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  5.889 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.279 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 18.893 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  1.163 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.656 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  1.480 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.614 s]
[INFO] Thingsboard Server Common Cluster API .............. SUCCESS [ 18.188 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  5.108 s]
[INFO] Thingsboard Server Common Cache .................... SUCCESS [  1.446 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.115 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  4.813 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  6.846 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.771 s]
[INFO] Thingsboard CoAP server ............................ SUCCESS [  0.874 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.739 s]
[INFO] Thingsboard LwM2M Transport Common ................. SUCCESS [  3.646 s]
[INFO] Thingsboard SNMP Transport Common .................. SUCCESS [  1.723 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  1.894 s]
[INFO] Thingsboard Server Remote Edge wrapper ............. SUCCESS [  7.183 s]
[INFO] Thingsboard Server Version Control API ............. SUCCESS [  1.838 s]
[INFO] Thingsboard Script Invoke Commons .................. SUCCESS [  0.017 s]
[INFO] Thingsboard Server Script invoke API ............... SUCCESS [  1.798 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.073 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.723 s]
[INFO] Thingsboard Server JS Client for remote JS execution SUCCESS [  0.649 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 15.600 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  8.808 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.020 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 40.434 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 31.743 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 27.372 s]
[INFO] Thingsboard LwM2m Transport Service ................ SUCCESS [ 28.116 s]
[INFO] Thingsboard SNMP Transport Service ................. SUCCESS [ 27.577 s]
[INFO] ThingsBoard Server UI .............................. FAILURE [02:01 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Version Control Executor ............... SKIPPED
[INFO] ThingsBoard Version Control Executor Microservice .. SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard LWM2M Transport Microservice ........... SKIPPED
[INFO] ThingsBoard SNMP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Monitoring Service ..................... SKIPPED
[INFO] ThingsBoard Monitoring Microservice ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:38 min
[INFO] Finished at: 2023-09-09T15:38:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn build) on project ui-ngx: Failed to run task: 'yarn run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ui-ngx

**Your Server Environment**

* own setup
 * local infrastructure 

**CPU**
cpuid

      (simple synth)  = AMD Ryzen (Castle Peak B0) / EPYC (Rome B0) [Zen 2], 7nm
   miscellaneous (1/ebx):
      process local APIC physical ID = 0x0 (0)
      cpu count                      = 0x4 (4)

**Mem**

free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       686Mi       5.0Gi       7.0Mi       2.1Gi       6.8Gi
Swap:          31Gi        77Mi        31Gi

**Disk**

/dev/sda3       194G   77G  108G  42% /

[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 5.4
[INFO] os.detected.version.major: 5
[INFO] os.detected.version.minor: 4
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 20.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64

**To Reproduce**

1. sudo apt-get install maven
2. git clone -b release-3.5 git@github.com:thingsboard/thingsboard.git --depth 1
3. cd thingsboard
3. mvn clean install -DskipTests

**Additional context**

**/tmp/ng-uxxgWp/angular-errors.log**

[error] TypeError: Cannot read properties of undefined (reading 'pluginOptions')
    at module.exports (/home/thingsboard-3.5.1/ui-ngx/extra-webpack.config.js:71:57)
    at Function.<anonymous> (/home/thingsboard-3.5.1/ui-ngx/node_modules/@angular-builders/custom-webpack/dist/custom-webpack-builder.js>
    at Generator.next (<anonymous>)
    at fulfilled (/home/thingsboard-3.5.1/ui-ngx/node_modules/@angular-builders/custom-webpack/dist/custom-webpack-builder.js:5:58)

**Comment by candice1984** [comment]
I meet the same problem.
Have you handled this issue yet?

**Comment by jeovajireh** [comment]
> I meet the same problem. Have you handled this issue yet?

Nothing, no one answers anything, everyone pretends it doesn't exist, I already had this same error and enabling swap memory worked, but days later I compiled it again and it didn't run. I believe there is an untreated error or an unspecified requirement in the project.

**Comment by Eddie66666666** [comment]
我也遇到了，怎么解决？

**Comment by jeovajireh** [comment]
> 我也遇到了,怎么解决？

Anything! There is a bug but they are not interested in finding the solution, as this forces the use of ready-made packages.

**Comment by jeovajireh** [comment]
> 我也遇到了,怎么解决？

Anything! There is a bug but they are not interested in finding the solution, as this forces the use of ready-made packages.

**Comment by ltanme** [comment]
I meet the same problem. Have you handled this issue yet?
`[INFO] warning protractor > webdriver-manager > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[INFO] warning protractor > webdriver-manager > request > har-validator@5.1.5: this library is no longer supported
[INFO] [2/4] Fetching packages...
[INFO] [3/4] Linking dependencies...
[INFO] warning " > @flowjs/ngx-flow@0.6.0" has incorrect peer dependency "@angular/common@^14.0.0-".
[INFO] warning " > @flowjs/ngx-flow@0.6.0" has incorrect peer dependency "@angular/core@^14.0.0-".
[INFO] [4/4] Building fresh packages...
[INFO] success Saved lockfile.
[INFO] $ patch-package
[INFO] patch-package 6.5.1
[INFO] Applying patches...
[INFO] @angular/core@15.2.10 鉁?
[INFO] @mat-datetimepicker/core@11.0.3 鉁?
[INFO] canvas-gauges@2.1.7 鉁?
[INFO] echarts@5.5.0 鉁?
[INFO] Done in 116.37s.
[INFO]
[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn build) @ ui-ngx ---
[INFO] Running 'yarn run build:prod' in E:\workProject\java5\thingsboard\ui-ngx
[INFO] yarn run v1.22.17
[INFO] $ node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration production --vendor-chunk
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] - Generating browser application bundles (phase: setup)...info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] An unhandled exception occurred: Cannot read properties of undefined (reading 'pluginOptions')
[INFO] See "C:\Users\admin\AppData\Local\Temp\ng-D2i9ii\angular-errors.log" for further details.
[INFO] error Command failed with exit code 127.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:26 min
[INFO] Finished at: 2024-05-10T19:44:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn build) on project ui-ngx: Failed to run task: 'yarn run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by ltanme** [comment]
I meet the same problem.
Have you handled this issue yet?
`[INFO] warning protractor > webdriver-manager > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[INFO] warning protractor > webdriver-manager > request > har-validator@5.1.5: this library is no longer supported
[INFO] [2/4] Fetching packages...
[INFO] [3/4] Linking dependencies...
[INFO] warning " > @flowjs/ngx-flow@0.6.0" has incorrect peer dependency "@angular/common@^14.0.0-".
[INFO] warning " > @flowjs/ngx-flow@0.6.0" has incorrect peer dependency "@angular/core@^14.0.0-".
[INFO] [4/4] Building fresh packages...
[INFO] success Saved lockfile.
[INFO] $ patch-package
[INFO] patch-package 6.5.1
[INFO] Applying patches...
[INFO] @angular/core@15.2.10 鉁?
[INFO] @mat-datetimepicker/core@11.0.3 鉁?
[INFO] canvas-gauges@2.1.7 鉁?
[INFO] echarts@5.5.0 鉁?
[INFO] Done in 116.37s.
[INFO]
[INFO] --- frontend-maven-plugin:1.12.0:yarn (yarn build) @ ui-ngx ---
[INFO] Running 'yarn run build:prod' in E:\workProject\java5\thingsboard\ui-ngx
[INFO] yarn run v1.22.17
[INFO] $ node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration production --vendor-chunk
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] - Generating browser application bundles (phase: setup)...info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] An unhandled exception occurred: Cannot read properties of undefined (reading 'pluginOptions')
[INFO] See "C:\Users\admin\AppData\Local\Temp\ng-D2i9ii\angular-errors.log" for further details.
[INFO] error Command failed with exit code 127.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:26 min
[INFO] Finished at: 2024-05-10T19:44:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:yarn (yarn build) on project ui-ngx: Failed to run task: 'yarn run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by hunglmtb** [comment]
I updated this and the issue gone away.
```
-    "@angular-builders/custom-webpack": "~15.0.0",
+    "@angular-builders/custom-webpack": "17.0.2",

-    "@ngtools/webpack": "15.2.1",
+    "@ngtools/webpack": "17.3.8",
```
Hope this helps
