### ISSUE TITLE
[Bug] maven repository repo.thingsboard.io not respond

### ISSUE THREAD

**Issue by lgtti** [thingsboard/thingsboard#9235]
**Describe the bug**
Access repo.thingsboard.io to download maven artifacts fails due to connection timeout.

Tested using terminal mvn, wget and curl, browser, vpn from US (i'm from Italy). Tested using PC internet connection and 4G cellular network also.

**Comment by jacksoncurrie** [comment]
Also experiencing this issue. Blocking us from building for CI/C which downloads artifacts from `repo.thingsboard.io`.

**Comment by jacksoncurrie** [comment]
It seems like this issue is fixed. `repo.thingsboard.io` is resolving successfully now 🙌

**Comment by lgtti** [comment]
yes, confirmed. Close the issue.
