### ISSUE TITLE
change in rule node config isn't propagated to other nodes

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#924]
When running in a cluster, a change in the rule node configuration of 1 node isn't reflected in the other nodes.
Steps to reproduce:
1. connect to `node1` with your browser and add a message generator node that generates messages for `device1`. Link the successful messages to the 'save telemetry' node.
2. check to see that messages for `device1` are arriving by looking at the last telemetry of the device.
3. connect to `node2` with your browser and change the generator rule node to start sending messages to `device2`. 
4. check to see that the messages for `device2` are arriving --> OK
5. check to see that the messages for `device1` stop arriving --> NOK

**Comment by janbols** [comment]
This is because the rule chain update is not propagated to the other nodes. A PR was created to fix this. See https://github.com/thingsboard/thingsboard/pull/919

**Comment by Delapouite** [comment]
Hello @janbols As the PR #919 you provided was merged, do you think this issue can be closed? Thanks
