### ISSUE TITLE
[Question] Handling 8 byte timestamps using TBEL

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [thingsboard/thingsboard#9243]
**Component**

 * Rule Engine

**Description**
Currently writing an uplink converter for an IoT device, and I'm stuck. Said device is sending us an 8 byte timestamp, which I need to convert. Sadly it appears that using TBEL, there is no real built in functionality that supports that, or enables me to convert it.

This would be the timestamp: 
`00 00 01 6B 40 D9 AD 80`
And this the timestamp:
` June 10, 2019 10:05:36 AM`

How can I solve this?

**Environment**
   * cloud deployment
   * ThingsBoard Version
   * OS: Linux (ubuntu 20.04)

**Comment by devaskim** [comment]
Try to search for how to do it in Java with its standard library and then test it in Rule Engine

**Comment by RicardoMonteiroSimoes** [comment]
> Try to search for how to do it in Java with its standard library and then test it in Rule Engine

I tried that. According to this:

https://thingsboard.io/docs/user-guide/tbel/#using-java-classes

The usage of java is extremely limited, so I don't exactly have access to many functions. One solution I've seen is the usage of `BigInteger`, which I can't use.

**Comment by kastayou** [comment]
You can use parseInt to convert the hex to decimal value of your timestamp and then convert it to a date

```
var input = "0000016B40D9AD80"
var timestampDecimal = parseInt(input, 16);

console.log("Decimal value: " + timestampDecimal);
console.log("Date :" + new Date(timestampDecimal));

```

https://jsfiddle.net/7p92rb6s/

**Comment by RicardoMonteiroSimoes** [comment]
> You can use parseInt to convert the hex to decimal value of your timestamp and then convert it to a date
> 
> ```
> var input = "0000016B40D9AD80"
> var timestampDecimal = parseInt(input, 16);
> 
> console.log("Decimal value: " + timestampDecimal);
> console.log("Date :" + new Date(timestampDecimal));
> ```
> 
> https://jsfiddle.net/7p92rb6s/

Thanks for the reply. It works when using JS, which is good, but I was asking about TBEL, as it's the "way to go" according to the official documentation.

**Comment by kastayou** [comment]
Sorry, I missed the part about TBEL. oupps

**Comment by xalt7x** [comment]
> > You can use parseInt to convert the hex to decimal value of your timestamp and then convert it to a date
> > ```
> > var input = "0000016B40D9AD80"
> > var timestampDecimal = parseInt(input, 16);
> > 
> > console.log("Decimal value: " + timestampDecimal);
> > console.log("Date :" + new Date(timestampDecimal));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://jsfiddle.net/7p92rb6s/
> 
> Thanks for the reply. It works when using JS, which is good, but I was asking about TBEL, as it's the "way to go" according to the official documentation.

Hello @RicardoMonteiroSimoes ,

You can find conversion examples on the [documentation website](https://thingsboard.io/docs/user-guide/tbel/).

The TBEL snippet below works for me (Thingsboard v3.6+)

```
var input = "0000016B40D9AD80";
var timestampDecimal = parseLong(input, 16);
var options = {"timeZone":"UTC","dateStyle":"long"};
var optionsStr = JSON.stringify(options);
msg.timestamp = new Date(timestampDecimal).toLocaleString("en-US", optionsStr);

return {msg: msg};
```
Output: `June 10, 2019, 10:05:36 AM`

![image](https://github.com/thingsboard/thingsboard/assets/44649402/d5de7ee1-47db-41fa-a602-d521990db804)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by GilDev** [comment]
Just for anyone encountering this issue, there is now [a `parseBytesToLong()` helper function](https://thingsboard.io/docs/user-guide/tbel/#parsebytestolong).
