### ISSUE TITLE
"Please contact system administrator" error on HTTP integration

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#9246]
**Component**

 * Rule Engine

**Description**
I'm getting a "Please contact system administrator" error in my HTTP integration. everything was working fine until this morning when I started getting this error.

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: ThingsBoard: 3.3.4.1PE-1
 * Browser: Mozilla

**Comment by ChrisEvisi** [comment]
We have found that this is often a result of related DataConverter error.  have to check the dataconverter events history for this.
