### ISSUE TITLE
Is there a way that I could show 0 on my widgets when telemetry stops coming in?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#9249]
UI
Description
When telemetry data stops coming in, say the power is turn off to my device., the widget would still show the last telemetry that came in even if it was from hours ago, making it seem like the device is still receiving telemetry.
Is there a way that I could show 0 on my widgets when telemetry stops coming in?

Here is what Ive come up with so far.  It works but I dont like the delay to get information on my widgets when I first load the dashboard. It takes 30 seconds or so to get data to show up on the dashboard.

![image](https://github.com/thingsboard/thingsboard/assets/130080104/254c4c99-67ec-4c44-8f29-792252b50eea)

Maybe theres another way to write it in the post processing area or maybe a rule chain I can make?

Thanks

**Comment by dhaval2017** [comment]
@Buhaw85 may be you can rewrite values to 0 or null when device is disconnected?

**Comment by Ultrazombie** [comment]
Closed due to inactivity
