### ISSUE TITLE
Slide Toggle Control Widget[Bug] 

### ISSUE THREAD

**Issue by kpule** [thingsboard/thingsboard#9253]
**Describe the bug**
Hello I am running ThingsBoard version 3.5.1. I am trying to use the Slide Toggle Control widget on my dashboard. Whenever I slide the switch, from ON to OFF and vice versa, it takes forever to change the state of the switch. Please see picture below. Any help is appreciated

**Your Server Environment**

* own setup
  * cloud deployment
  * ThingsBoard Version: 3.5.1
  * OS Name and Version: Ubuntu 22.04.3 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser: Chrome
* Version  116.0.5845.188

**To Reproduce**
1. Add the Slide Toggle Control widget to the dashboard 
2. Toggle switch
3. It hangs without changing the state of the switch
4. See attached image

**Expected behavior**
It hangs while loading to change state

**Screenshots**
See attached image
![Toggle%20Switch](https://github.com/thingsboard/thingsboard/assets/87413880/9e63858e-6372-4355-ac0a-ccabdf0ef12b)

**Comment by Alimousavi47** [comment]
yes I also see such things on thingsboard v3.6.0
so still a bug I think

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by DanielBustillos** [comment]
**Facing the same issue as well.**
I'm running ThingsBoard version 3.6 on my server, and whenever I use the Slide Toggle Control widget, it gets stuck in the loading state when toggling between ON and OFF. I am successfully receiving the RPC request and returning a payload of {"result":"ok"}, but the widget still hangs, and the state doesn't change as expected.

I've also attempted returning the received parameters in the response, but the issue persists. Should I modify the response payload to something different, or is there another reason the widget remains in a loading state?

Any guidance would be greatly appreciated.
