### ISSUE TITLE
[Bug] Notifications pages does not translate alarm texts

### ISSUE THREAD

**Issue by tarmacx** [thingsboard/thingsboard#9255]
**Describe the bug**
When we go into the notification page, alarms that are displayed in the list are using the placeholder text instead of the translation

**Your Server Environment**

* own setup
  *  docker deployment
  * ThingsBoard Version 3.5.1
  * OS Name and Version Ubuntu 22

**Your Client Environment**

**Desktop:**

* OS: Windows 10
* Browser : Chrome
* Version:  116

**To Reproduce**
1. Click on the bell for notifications
2. Show all

**Expected behavior**
We should see the message with the proper text from the translation file.

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/13239306/1e885b84-6cc4-4aef-b3ed-deaa0f2b99c2)

**Comment by epalchenko** [comment]
Hello @tarmacx,

This is a known issue with custom translations that was fixed in version 3.6.0.
Upgrading to this version will resolve your issue.
