### ISSUE TITLE
[Bug] CoAP not support get firmware

### ISSUE THREAD

**Issue by wanglei1991** [thingsboard/thingsboard#9261]
CoAP not support get firmware with "coap get coap://x.x.x.x:5683/api/v1/TWmOF1jrwZoxeMDmSet9/firmware?title=firmware&version=2.0"
==[ CoAP Response ]============================================
MID    : 3054
Token  : B4D2FF51456CBBA0
Type   : ACK
Status : 4.00 - BAD_REQUEST
Options: {}
RTT    : 3252 ms
Payload: 0 Bytes
===============================================================

**Comment by Ultrazombie** [comment]
Please re-create the ticket with a more detailed description if your issue is still valid.
