### ISSUE TITLE
Rule chain - mqtt message that contains device name

### ISSUE THREAD

**Issue by leonmyburg** [thingsboard/thingsboard#927]
In the Rule Chain you have the option to send post telemetry data via MQTT to another MQTT broker. The topic can be configured with meta dat. Is it possible to send device attributes/meta data (like device name ex. {"device" : {"DeviceA": [{foo data}]}}) in the payload as currently it just send the telemetry?

**Comment by vparomskiy** [comment]
https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#mqtt-node

`Publish incoming **message payload** to the topic of the configured MQTT broker`

Before sending a message to the MQTT broker you can add Transformation Node that will change Message payload to the required format.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node

**Comment by leonmyburg** [comment]
Thanks
