### ISSUE TITLE
[Question] How to Prevent Tooltip From Displaying Non-existent Values?

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard#9270]
**Component**

 * Generic

**Description**
With reference to the figure below, the tooltip shows values for CDA #5 even though there is no data from the device at that particular time. I did enable Hide zero/false values from tooltip in the tooltip settings. How do I resolve this? 

![WhatsApp Image 2023-09-15 at 20 27 36](https://github.com/thingsboard/thingsboard/assets/6798969/5ef51e23-e1d7-463e-8ee2-f3a6e383959b)

**Environment**

 * ThingsBoard: 3.5.1

**Comment by ssakharova** [comment]
Hello @cowherdboy,

New versions of ThingsBoard have introduced changes to the appearance and functionality of some default widgets, including the Bar Chart widget. We recommend upgrading to the latest version to take advantage of these improvements and explore the enhanced capabilities of the modified Bar Chart widget.
![image](https://github.com/thingsboard/thingsboard/assets/98035385/6fa62cb8-48c4-4210-9c32-ecdac6bf1ca8)
