### ISSUE TITLE
[Question] A rule chain to generate api calls for every instance of an asset profile.

### ISSUE THREAD

**Issue by Wirg** [thingsboard/thingsboard#9271]
**Component**
 * Rule Engine

**Description**
I am trying to create a rule chain that generate api calls every 10min for every instance of an asset profile.
The goal would be to achieve something like this diagram.
![mermaid-diagram-2023-09-18-102032](https://github.com/thingsboard/thingsboard/assets/17848620/c16a818f-b6bf-4182-90aa-f731e0977f62)

I found this similar question with no real answer : https://github.com/thingsboard/thingsboard/issues/4019 .
I am surprised the only answer would be to create a custom node. Is that the case ?

**Environment**
 * ThingsBoard: Cloud PE Startup
 * Browser: Chrome

**Comment by ashaforost** [comment]
Hi @Wirg 

Scheduling can be done via the thingsboard's scheduler feature: basically, you can create a dummy scheduler that will trigger a rule chain and route the message to the asset broadcasting logic.
As for actually retrieving all asset profiles and all assets in said profiles, there are several solutions, and none of them are ideal, to be frank.

1. Create an asset group for each asset type and a scheduler for each asset group(this works only on one level of hierarchy, e.g., tenant, customer a, customer b...). Then, you can use duplicate to group rule node. 
2. Entities relations: create relations from one dummy asset to each one you have and use scheduler + duplicate to related rule node
3. IMHO, the easiest: custom script + server cron job, or at least rest api calls in the rule chain to retrieve a list of required assets.

As you can see, a custom rule node, in this case, is not such a bad idea after all. 

Additionally, I created a feature request in our backlog for our developers to review the suggestion and decide on the implementation. Hopefully, they will see the use of such a feature and choose to develop it.
