### ISSUE TITLE
[Question] Building from source, no DEB file

### ISSUE THREAD

**Issue by realbeeit** [thingsboard/thingsboard#9272]
**Component**

 
 * Installation

**Description**
When I build my custom Thingsboard instance with command: mvn clean install -DskipTests build is successfull but there is no deb file. What am I missing?

**Environment**

 * OS:  Ubuntu 22.04 ARM64

**Comment by Backdraft007** [comment]
is there a path application/target?

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
