### ISSUE TITLE
[Question] Thingsboard endless load screen

### ISSUE THREAD

**Issue by KnoetzeRuan** [thingsboard/thingsboard#9279]
**Component**
 * Generic

**Description**
I Installed Thingsboard community edition on a new PC that is running at a site that has no Internet access. We use Thingsboard on site to consolidate all device on the local network. We have tested this before and it was working. This new site however is giving us a strange error when trying to open Thingsboard on a browser:

![image](https://github.com/thingsboard/thingsboard/assets/145371049/cf29c7a0-5cf2-49f6-acc2-54b058da8034)

Thingsboard keeps showing the loading screen but nothing wants to load. We get the error as shown on Chrome.

Attached is the full working of the error. It look to me like a possible timezone issue? Has anyone ever seen this issue?

PS. I tested the PC in an office with internet access and everything worked fine then.

**Environment**

 * OS:  Windows 10
 * ThingsBoard: V3.4.4
 * Browser: Chrome and Firefox
[Error.txt](https://github.com/thingsboard/thingsboard/files/12650714/Error.txt)

**Comment by KnoetzeRuan** [comment]
It seems the issue was that the site installed an outdated Chrome and Firefox browser on their PC. We updated it and it is working.

**Comment by prazsmarid** [comment]
I want to run ThingsBoard on older devices with older browser. There is any support for it?
