### ISSUE TITLE
[Question] [TB] Unable to de-serialize received json data with error (NoMemory)

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9282]
**Component**

 * Generic

**Description**
I have encontered a problem today while working on my ESP32 device where I am getting this output when trying to request shared attributes, make OTA updates or processing an RPC request. I do not know why this problem is occuring because earlier this morning I was receiving this output just when trying to perform an OTA update but then I got the same problem with my RPC and Attributes systems.
I have tried to use example codes to check if I was doing something wrong but it does not seem to work and I have tried looking for an answer online but I have not been able to find a solution.

**Environment**

 * OS:  Windows 10 Pro 21H2
 * ThingsBoard: 3.5.1

**Comment by rch-goldsnaker** [comment]
Try with this video : https://www.youtube.com/watch?v=04aKK_7yCqc&t=30s

**Comment by jortega11** [comment]
Honestly, I do not remember what was causing the issue because this was a long time ago. Probably it had something to so with the size of some configuration.
