### ISSUE TITLE
[Question] Is there a way to select which buttons to display on the widget top right corner?

### ISSUE THREAD

**Issue by danisal** [thingsboard/thingsboard#9292]
**Component**

 * UI

**Description**
I want to hide a button on the widget's top right corner, the "Export widget data" button. Is there a way to accomplish this?
<img width="249" alt="image" src="https://github.com/thingsboard/thingsboard/assets/9869755/96f56513-d282-4f51-820c-365b42fe64c5">

**Environment**

 * OS:  any
 * ThingsBoard: 3.5.1 PE
 * Browser: any

**Comment by Backdraft007** [comment]
Edit your widget. At the bottom if the data tab click on "Data settings" and disable Data export.

**Comment by danisal** [comment]
thank you @Backdraft007 🙌
