### ISSUE TITLE
How to controll device

### ISSUE THREAD

**Issue by hanyou** [thingsboard/thingsboard#93]
we can collect data from device, but I want to controll device, such as turn off light, how to do?

**Comment by setevik00** [comment]
Please take a look at Thingsboard tutorial first (https://thingsboard.io/docs/iot-video-tutorials/). Best place for Howto questions is Thingsboard forum: https://groups.google.com/forum/#!forum/thingsboard

**Comment by ashvayka** [comment]
This is possible via [RPC feature](https://thingsboard.io/docs/user-guide/rpc/). You are also able to use following  [gpio widgets](https://thingsboard.io/docs/user-guide/ui/widget-library/#gpio-widgets) or develop your own.

**Comment by ikulikov** [comment]
Closing due an inactivity.

**Comment by amrithmmh** [comment]
have the same question...how to control an led via thingsboard?
