### ISSUE TITLE
REST over SSL Rule-Node

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#930]
Hello there!

I was experimenting with you rule-chains and came across a problem: 

I fail in making a request (via rest api call node) to any service that uses https for their api (for example datakick.org). After I successfully used the rest node to enrich incoming data with weather data from OpenWeatherMap I hoped that I could try out other APIs as well. 

Now I am wondering:
Is there any possibility to include REST over SSL? 
Do I have to create my own node that supports REST over SSL?
How could I do this?

Thanks in advance for any ideas on that.

P.S. The new rule-engine is great!

**Comment by volodymyr-babak** [comment]
this is already supported in 3+ versions. 
I was able to GET successfully next endpoint https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration into my rule chain:
![image](https://user-images.githubusercontent.com/3466101/153154036-6d75720a-e788-4a65-b0de-8f39146a1748.png)
