### ISSUE TITLE
[Question] Can I upload a file to configure my devices?

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9302]
**Component**

 * Generic

**Description**
I have a question regarding a project I am currently developing. I will have many devices with the same code but different configurations (i.e. Token, MQTT Broker, WiFi SSID/Password, etc) and I wanted to know if there is a way to have a configuration file with the information needed for each device and upload it to ThingsBoard (or something similar) so the device can read those values and get the configuration without the need to make an OTA update or something similar to change those parameters.

I have also thought about sending the data using RPC commands, but a system like the one mentioned above is more preferable.

**Environment**

 * ThingsBoard: 3.5.1

**Comment by ashaforost** [comment]
Hi @jortega11 

You can try bulk provisioning to upload a bunch of devices with some server side attributes, tokens, etc; See [Bulk Provisioning](https://thingsboard.io/docs/user-guide/bulk-provisioning/)

**Comment by jortega11** [comment]
I have read about bulk provisioning and it could be useful to create a bunch of devices with their own token and attributes, but I mean about having the possibility modify some parameters like the WiFi SSID, password, etc. **when the device is already created**, like the bulk provisioning does.

It would be the same system as bulk provisioning but, as I said, when the device is already created (because we are assuming that they are **already defined and configured** and the user wants to make changes in the configuration of some of them on the go).



I am pretty sure that this feature does not exist at the moment, but I wanted to make sure there is not a way to do it so I could try to think about another way.

**Comment by ashaforost** [comment]
Bulk provisioning looks up already existing devices and can update attributes/timeseries if needed. Assuming the parameters you mentioned (WiFi SSID, password, etc) are attributes or timeseries, bulk import can be of use in this case. If not, please clarify where you set those parameters.
![image](https://github.com/thingsboard/thingsboard/assets/47900737/1309c0b0-104a-4ea2-bc81-f1a7d3d88448)

**Comment by jortega11** [comment]
Okay, I will check it out. Thank you.
