### ISSUE TITLE
[Bug] thingsboard3.5 AbstractTbQueueConsumerTemplate lock release bug description

### ISSUE THREAD

**Issue by chanimagery** [thingsboard/thingsboard#9309]
**Describe the bug**
thingsboard3.5 AbstractTbQueueConsumerTemplate lock release bug description

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version 3.5
  * OS Name and Version Win10

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Win10
* Browser Chrome
* Version [e.g. 22]

**Smartphone (please complete the following information):**

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**
In the org.thingsboard.server.queue.common.AbstractTbQueueConsumerTemplate.poll()f method, there is the following code fragment consumerLock.lock();
        try {
            while (!subscribeQueue.isEmpty()) {
                subscribed = false;
                partitions = subscribeQueue.poll();
            }
            if (!subscribed) {
                List<String> topicNames = partitions.stream().map(TopicPartitionInfo::getFullTopicName).collect(Collectors.toList());
                doSubscribe(topicNames);
                subscribed = true;
            }
            records = partitions.isEmpty() ? emptyList() : doPoll(durationInMillis);
        } finally {
            consumerLock.unlock();
        }
If subscribeQueue.isEmpty() is empty, the consumerLock lock will never be released, causing log.error() to be printed continuously.
It is recommended to modify it to
  try {
            consumerLock.lock(); // Get the lock
            
            if (this.stopped) {
                return errorAndReturnEmpty();
            }
            if (!this.subscribed && this.partitions == null && this.subscribeQueue.isEmpty()) {
                return sleepAndReturnEmpty(startNanos, durationInMillis);
            }
            
           ....
            
        } finally {
            consumerLock.unlock();
        }
....

thanks

**Comment by ViacheslavKlimov** [comment]
The lock is always unlocked in the `finally` block:
```
consumerLock.lock();
try {
    while (!subscribeQueue.isEmpty()) {
        subscribed = false;
        partitions = subscribeQueue.poll();
    }
    if (!subscribed) {
        List<String> topicNames = getFullTopicNames();
        doSubscribe(topicNames);
        subscribed = true;
    }
    records = partitions.isEmpty() ? emptyList() : doPoll(durationInMillis);
} finally {
    consumerLock.unlock();
}
```
