### ISSUE TITLE
A request for rule chain 

### ISSUE THREAD

**Issue by sampsonsxz** [thingsboard/thingsboard#931]
I want to realize a request that if  I can  get the values of telemetry  from the embedded HSQLDB  at 12 o'clock,and then send them to the specified mailbox.
The telemetry  has already been post to thingsboard via MQTT.
Is it possible ? If possible ,how to do it?

**Comment by eykamp** [comment]
Do you want to do it with an external script (like a cron job, for example)?  If so, you can use the getTimeseries call from the Telemetry API to do it.

http://<YOUR URL HERE>:8080/swagger-ui.html#!/telemetry-controller/getTimeseriesUsingGET

I have an unfinished Python library that will make this easy.  If that would be compatible with your approach, I'd be happy to provide you some sample code.

**Comment by sampsonsxz** [comment]
Thanks buddy,but I consider the rule chain or the function of TB first, How to realize this by the Telemetry API  ?

**Comment by marshallr3** [comment]
This would be nice to have, using Rule Chain to execute a 'cron job' to prevent having to run externally.

**Comment by corlinski** [comment]
I confirm. Such a feature is highly recommended fro Rule Chain ;)
