### ISSUE TITLE
convert timestamp in second to milisecond

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9312]
Hello
When converting the time stamp in seconds to milliseconds, the received number is out of the variable range.
I could not define a long variable because it gives an error.
How can I convert timestamps to milliseconds?

`
//msg.sys.sunrise = 1695435081;

var time = msg.sys.sunrise * 1000;

msg.sunrise = time;

//output
// msg.sunrise => -1077000920;
`

**Comment by ashaforost** [comment]
Hi @m3relec 

Thank you for reporting this issue. I've created a bug report in our backlog; our developers will review this issue and decide on the fix.

**Comment by nickAS21** [comment]
https://github.com/thingsboard/tbel/pull/21
