### ISSUE TITLE
Creating Custom Message Types in ThingsBoard Rule Engine

### ISSUE THREAD

**Issue by ShukeshAiotel** [thingsboard/thingsboard#9315]
**Component**

 * Rule Engine

**Description**

Hi everyone,

I'm using ThingsBoard CE v3.5.1, and I'm facing a challenge in handling custom message types within the rule engine. I need to create custom message types to better organize and process my IoT data. Can anyone please help me figure out how to create custom message types in ThingsBoard?

Thanks in Advace.

**Environment**
 * OS: Ubuntu 20.04
 * ThingsBoard:CE 3.5.1

**Comment by mykhailokornieiev** [comment]
Hi. It looks like you need Filter -> Switch rule node
https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#switch-node

**Comment by ShukeshAiotel** [comment]
Hello @mykhailokornieiev 

Thanks for your response, we are trying to integrate one of our platform data with Thingsboard, for that we are trying to create a new msgType Similar to "POST_TELEMETRY_REQUEST", which will filter the incoming to thingsboard from our platform.

**Comment by mykhailokornieiev** [comment]
Hello @ShukeshAiotell. From the last message, it is not entirely clear whether there are any questions left or maybe there are problems with the proposed node.

**Comment by mykhailokornieiev** [comment]
Hello @ShukeshAiotel. It still not fully clear. Please describe it in as much detail as possible. How exactly do you want to send this data to thingsboard? Is it HTTP, MQTT, maybe via one of available integrations? What is data format of this data, is it JSON payload, or maybe HEX, plain text etc.?

**Comment by ShukeshAiotel** [comment]
Hello @mykhailokornieiev 

I have defined a custom RestController where data format is JSON payload, I need to push the incoming JSON payload to rule-engine. 

Example: 

```
endpoint : /api/device_data
JSON Payload : 

{
"temperature": 30,
"humidity":40
}

payload that need to be pushed to rule-engine: 

{
    "msg": {
        "temperature": 30,
        "humidity": 40
    },
    "metadata": {
        "ts": "1697689521547"
    },
    "msgType": "CUSTOM_MSG_TYPE"
}
``` 
I hope this makes you clear what I actually want to achieve.

**Comment by mykhailokornieiev** [comment]
Hello @ShukeshAiotel
You can try to use the rule engine controller http://localhost:8080/swagger-ui/#/rule-engine-controller, it will have REST_API_REQUEST message type, so you will change it via Switch node on the necessary message type under desired conditions.

**Comment by ShukeshAiotel** [comment]
Hello @mykhailokornieiev 

Thanks for your response, will try and revert back if I have any questions.
