### ISSUE TITLE
Rule chain wrong result type

### ISSUE THREAD

**Issue by xmas3** [thingsboard/thingsboard#932]
Hi, following the instruction for Transform telemetry using previous record.

Im getting on TB following error.
`2018-07-12 11:28:33,326 [pool-33-thread-1] WARN  o.t.s.s.s.RuleNodeJsScriptEngine - Wrong result type: NUMBER`

Any ideas what can be wrong?
I can provide complete log on DEBUG/TRACE level.

**Comment by xmas3** [comment]
Maybe this can be the cause, I can find the fetched attribute in data an metadata too. Is this correct?

```
{
    **"ActualValueIN1": 6333419,**
    "delta": 61
}
```
```
{
    "deviceType": "Watermeter",
    **"ActualValueIN1": "6333358",**
    "deviceName": "XXX",
    "ts": "1531388334369"
}
```

**Comment by ebmsh** [comment]
Made the same mistake: You used a filter scipt (expects boolean output) and not a transformation script (object output)

**Comment by AnasAbdeen** [comment]
how to change attribute value in the rule chain in thingsboard
