### ISSUE TITLE
[Bug] Can't connect device after 3.5.1->3.6.0 update

### ISSUE THREAD

**Issue by LukaszDuss** [thingsboard/thingsboard#9323]
**Describe the bug**
I can't communicate any device (HTTP nor MQTT) after update 

I had tried CURL, mosquitto-pub, MQTTX and devices won't connect, all i get is connection error.

I have noticed that after the update, variable TB_VERSION=latest in .env file, makes thingsboard run as 3.5.1 still instead of 3.6.0. Manual override this to =3.6.0 will make thingsboard run in 3.6.0 version

**Your Server Environment**
* own setup
  * ThingsBoard Version: MSA [hybrid + kafka] 3.5.1 -> 3.6.0
  * OS Name and Version - Ubuntu 22.04

**Your Device**
* Connectivity
  * MQTT
  * HTTP
  * Gateway

**Comment by trikimiki** [comment]
Hi!

Did you upgrade ThingsBoard DB? https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/#upgrading

**Comment by LukaszDuss** [comment]
I only did that

**Comment by trikimiki** [comment]
Just to be clear - did you run upgrade first, and then change the ENV variable?
It should be done other way round - ENV first, then upgrade.
Could you please share install logs (should be in your log volume -> install.log)?

**Comment by LukaszDuss** [comment]
> Just to be clear - did you run upgrade first, and then change the ENV variable? It should be done other way round - ENV first, then upgrade. Could you please share install logs (should be in your log volume -> install.log)?

yeah i fkd up 🥇 

here are logs - i have tried few times to upgrade 
[install_log3.log](https://github.com/thingsboard/thingsboard/files/12749581/install_log3.log)
[install_log1.log](https://github.com/thingsboard/thingsboard/files/12749582/install_log1.log)
[install_log2.log](https://github.com/thingsboard/thingsboard/files/12749583/install_log2.log)

**Comment by LukaszDuss** [comment]
ok, seems like rebooting all mqtt-transport containers and http-transport did the trick.

I had restarting all services and rebooting OS prior to posting this issue.
I will check if rebooting/restarting services will break TB again
