### ISSUE TITLE
CompletableFuture compliant scheduling tasks

### ISSUE THREAD

**Issue by chenggwang** [thingsboard/thingsboard#9328]
CompletableFuture should be used, not just ListenableFuture

**Comment by Ultrazombie** [comment]
hello @chenggwang 
What do you mean by that comment?

**Comment by chenggwang** [comment]
> hello @chenggwang What do you mean by that comment?

jdk1.8 after CompletableFuture has become an important task scheduling framework in JUC, solves the problem of callback hell, easy to use..
Change here to return Future and you're free to choose. Of course does not affect the previous ListenableFuture use, new development if you use CompletableFuture, remember to call the correct link method on it!

**Comment by chenggwang** [comment]
> hello @chenggwang What do you mean by that comment?

And I've already submitted a PR, which explains it in detail：Making it possible to use CompletableFuture #9327

**Comment by trikimiki** [comment]
the PR https://github.com/thingsboard/thingsboard/pull/9327 was merged
thank you for your contribution!
