### ISSUE TITLE
AI jars integration

### ISSUE THREAD

**Issue by wind86** [thingsboard/thingsboard#933]
Hi,
Any plans to integrate AI libraries like deeplearning4j into rule engine?
Thx

**Comment by volodymyr-babak** [comment]
there are no plans to add these libraries into the rule engine, but you can always add your custom rule node and use them in the rule chain, with any AI libraries that you want.
Please take a look at this guide on how to implement your custom rule nodes:
https://thingsboard.io/docs/user-guide/contribution/rule-node-development/
