### ISSUE TITLE
[Question] Get time-series data REST API return empty but can get data from Cassandra directly

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#9333]
**Component**

 * Generic

**Description**
Get time-series data REST API return empty but can get data from Cassandra directly, how to debug it?

![image](https://github.com/thingsboard/thingsboard/assets/7221781/71659d8c-2d55-4e56-8962-0875a7c819aa)

![image](https://github.com/thingsboard/thingsboard/assets/7221781/9320b215-eef7-4f62-b027-09688fef11de)

**Environment**

 * ThingsBoard: 3.5.1

**Comment by trikimiki** [comment]
Hi!

Did you have everything working previously, or was it the first time REST request did not return the data?

Do you see data when using timeseries widget?

**Comment by maksonlee** [comment]
> Hi!
> 
> Did you have everything working previously, or was it the first time REST request did not return the data?

Not sure, but seems that problem happens after i dropped thingsboard keyspace and re-created it with [1]
[1] https://github.com/thingsboard/database-migrator/blob/master/src/main/resources/schema-ts.cql

> Do you see data when using timeseries widget?

Can see data in widget in realtime mode but history.

BTW, i can't find any related error message in thingsboard.log.

**Comment by maksonlee** [comment]
and here is our current Cassandra thingsboard keyspace definition,

```
cqlsh:thingsboard> describe thingsboard;

CREATE KEYSPACE thingsboard WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE thingsboard.ts_kv_cf (
    entity_type text,
    entity_id timeuuid,
    key text,
    partition bigint,
    ts bigint,
    bool_v boolean,
    dbl_v double,
    json_v text,
    long_v bigint,
    str_v text,
    PRIMARY KEY ((entity_type, entity_id, key, partition), ts)
) WITH CLUSTERING ORDER BY (ts ASC)
    AND additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND cdc = false
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND extensions = {}
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';

CREATE TABLE thingsboard.ts_kv_partitions_cf (
    entity_type text,
    entity_id timeuuid,
    key text,
    partition bigint,
    PRIMARY KEY ((entity_type, entity_id, key), partition)
) WITH CLUSTERING ORDER BY (partition ASC)
    AND additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.1
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND cdc = false
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND extensions = {}
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';
```

**Comment by maksonlee** [comment]
I created a new device in the same tenant, no problem at all, but still have issue with old devices.

**Comment by trikimiki** [comment]
This is most likely an upgrade issue (some previous upgrade failed somewhere)
Also, it might be an issue with DB relation table; it contains some important things required for proper entities functionality
