### ISSUE TITLE
[Question] Dashboard state changes using asset

### ISSUE THREAD

**Issue by piyush-bhanushali1** [thingsboard/thingsboard#9334]
Hi All,
I have A asset in which there is a,b,c asset and in a,b,c has their devices. I have created main dashboard which shows data of A assets now i want to pass Details from one dashboard to another in which i want to show all devices of that individual assets. Can anyone help me on this? I can get details of devices from one dashboard to another but not able to do on asset level.

**Comment by ashaforost** [comment]
Hi @piyush-bhanushali1 

On the first dashboard: widget with asset A + widget action 'navigate to other dashboard' with 'set entity from widget' option enabled.
On the second dashboard: widget with alias 'relation query': 
![image](https://github.com/thingsboard/thingsboard/assets/47900737/2e34aeb8-a411-4b0d-9fdb-7f91ebf5bf3a)
This solution entails that your assets and devices have relations set up between them.
You can also play with the relation types filters based on your relation settings.
