### ISSUE TITLE
[Question] Custom action (with HTML template) development

### ISSUE THREAD

**Issue by danisal** [thingsboard/thingsboard#9340]
**Component**
 * UI

**Description**
Hi, I've been developing custom widgets and actions with HTML templates, but I still need documentation and guidelines for this department. And I have some questions regarding this.

- Besides the custom action with HTML template [documentation](https://thingsboard.io/docs/user-guide/ui/widget-actions/#custom-action-with-html-template), is there any other place where I can view some more complex examples? For example, retrieving time series data after a user action?
- Connected with the previous point, are there some best practice guidelines when implementing device-related settings? i.e., should they be implemented in a dialog in multiple tabs, or would it be better to be in a different dashboard view with different widgets?
- Where can I find documentation of the JS methods available to us, either in the widgets or in the widget actions, so we can know what we can create and what should be used? Besides [this one](https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/#introduction)
- Is there any documentation about the HTML attributes available to us, for example, the *fxFlex* for the flexbox layout? Where can I find documentation about this?
- Last but not least, is there a better/easier way for widget development other than the online editor? Because it doesn't offer the best DX, copying and pasting between the local code editor and thingsboard is a really time-consuming and error-prone solution, especially on extended custom widgets and widget actions.

I appreciate any help you can give.

**Environment**
 * OS:  Any
 * ThingsBoard: PE 3.6
 * Browser: Any

**Comment by devaskim** [comment]
> Is there any documentation about the HTML attributes available to us, for example, the fxFlex for the flexbox layout? Where can I find documentation about this?

[Docs link](https://github.com/angular/flex-layout/wiki/Declarative-API-Overview) and [Demo link](https://tburleson-layouts-demos.firebaseapp.com/#/docs)

**Comment by devaskim** [comment]
In general, I cannot find any other docs. Widget's editor autocompetion feature is also incomplete. So source code is your jedi path)
- [widget context](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/models/widget-component.models.ts#L122)
- [widget component](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/widget.component.ts)
- [HTTP API](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/app/core/http)

**Comment by devaskim** [comment]
And the last from my side. I prefer dashboard state instead of widget action template because of the latter approach requires a lot of time just for editing, saving changes and debugging.

And as I know we have only one editor(((

**Comment by Ultrazombie** [comment]
closed due to inactive
