### ISSUE TITLE
How to backup and restore telemetry data in postgre?

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9345]
Hello. 
I installed thingsboard on another server. 
Now I want to transfer the telemetry data stored in the database to another server.
How should I do this?

**Comment by devaskim** [comment]
Here is my [SO answer](https://stackoverflow.com/a/77071115/17782348) how I did it recently. 
If you don't need to keep server running as in my case, just user pg_basebackup tool. There is a lot of tutorials in the web how to use it.

**Comment by Ultrazombie** [comment]
closed due to inactive

**Comment by dip-devlopement** [comment]
> Hello. I installed thingsboard on another server. Now I want to transfer the telemetry data stored in the database to another server. How should I do this?

I have complet solution for that Contact on dharmikprajapati230@gmail.com. # tb- postgres, #thingsboard.
