### ISSUE TITLE
How can I get current user data from relations query?

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#9346]
Hello!
I am facing an issue with rendering information where the user only has access. The situation is that I have 4 asset entities, and they are dynamic. When I press location, renders the areas data and like that. The problem is that it renders the data from that location, but I want to add a filter in order for the user to see only the areas which they have access, not all the areas from that location.
<img src="https://github.com/thingsboard/thingsboard/assets/98624393/f11803bf-ed88-49cd-bf68-e5fc3b6fc6c1" width="600"/>
I have currently this relation, which gets the areas from the selected location, the issue is that I do know not how to add a relationship with the current user, we have some relations such as accessToArea with the user, but gets me all the users also instead of the areas which the user have access. 
I wanted to know if there a way to filter the data depending the user, by using rule chains or entity aliases.
Is there a way to solve this problem?

**Comment by devaskim** [comment]
How about this alias?

![areas](https://github.com/thingsboard/thingsboard/assets/86909129/4847aca6-d79f-44a4-9db8-f1bdf14bd038)

**Comment by Ultrazombie** [comment]
closed due to inactive
