### ISSUE TITLE
[Bug] could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

### ISSUE THREAD

**Issue by izi-mh** [thingsboard/thingsboard#9347]
Hello,

ich have done the upgrade from thinsgboard:tb-postgres:3.4.4 to 3.5.1 over 3.5.0

After upgrade there is an error in alarm.

<img width="963" alt="Bildschirmfoto 2023-10-03 um 13 43 59" src="https://github.com/thingsboard/thingsboard/assets/60258478/9172fc4a-6bd6-47ff-b851-a0f2f55aedb7">

This is the update log without schema upgrade 3.4.4:

 ===================================================
 :: ThingsBoard ::       (v3.5.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.4.4 ...
Clearing cache to upgrade from version 3.4.4 to 3.5.0
Clearing cache [deviceProfiles]
Upgrading ThingsBoard from version 3.4.4 to 3.5.0 ...
Updating schema ...
column "status" of relation "alarm" already exists, skipping
index "idx_alarm_originator_alarm_type_active" does not exist, skipping
index "idx_alarm_tenant_alarm_type_active" does not exist, skipping
index "idx_entity_alarm_entity_id_alarm_type_created_time_alarm_id" does not exist, skipping
Schema updated.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Creating default notification configs for system admin
Creating default notification configs for all tenants
Upgrade finished successfully!
waiting for server to shut down....2023-10-03 10:45:40.285 UTC [12] LOG:  received fast shutdown request
2023-10-03 10:45:40.287 UTC [12] LOG:  aborting any active transactions
2023-10-03 10:45:40.293 UTC [12] LOG:  background worker "logical replication launcher" (PID 19) exited with exit code 1
2023-10-03 10:45:40.293 UTC [14] LOG:  shutting down
2023-10-03 10:45:40.346 UTC [12] LOG:  database system is shut down
 done
server stopped

This is update log, after schema update 3.4.4:

===================================================
 :: ThingsBoard ::       (v3.5.1)
 ===================================================

Starting ThingsBoard Upgrade from version 3.4.4 ...
Clearing cache to upgrade from version 3.4.4 to 3.5.0
Clearing cache [relations]
Clearing cache [deviceCredentials]
Clearing cache [devices]
Clearing cache [sessions]
Clearing cache [assets]
Clearing cache [entityViews]
Clearing cache [claimDevices]
Clearing cache [securitySettings]
Clearing cache [tenantProfiles]
Clearing cache [tenants]
Clearing cache [tenantsExist]
Clearing cache [deviceProfiles]
Clearing cache [assetProfiles]
Clearing cache [notificationSettings]
Clearing cache [sentNotifications]
Clearing cache [attributes]
Clearing cache [userSessionsInvalidation]
Clearing cache [otaPackages]
Clearing cache [otaPackagesData]
Clearing cache [edges]
Clearing cache [repositorySettings]
Clearing cache [autoCommitSettings]
Clearing cache [twoFaVerificationCodes]
Clearing cache [versionControlTask]
Clearing cache [userSettings]
Clearing cache [dashboardTitles]
Clearing cache [entityCount]
Upgrading ThingsBoard from version 3.4.4 to 3.5.0 ...
Updating schema ...
Schema updated.
Creating default notification configs for system admin
Creating default notification configs for all tenants
Upgrading ThingsBoard from version 3.5.0 to 3.5.1 ...
Updating schema ...
Schema updated.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Upgrade finished successfully!
waiting for server to shut down....2023-10-03 11:34:30.092 UTC [11] LOG:  received fast shutdown request
2023-10-03 11:34:30.093 UTC [11] LOG:  aborting any active transactions
2023-10-03 11:34:30.096 UTC [11] LOG:  background worker "logical replication launcher" (PID 18) exited with exit code 1
2023-10-03 11:34:30.096 UTC [13] LOG:  shutting down
2023-10-03 11:34:30.128 UTC [11] LOG:  database system is shut down

How can i fix it?

**Comment by ViacheslavKlimov** [comment]
What do the logs say when the error occurs on UI?

**Comment by mhuelsmann** [comment]
Hello,

here the log aprt of the error.

ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:15.515 UTC [63] ERROR:  column alarminfoe0_.propagate_to_owner does not exist at character 623
ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:15.515 UTC [63] STATEMENT:  select alarminfoe0_.id as id1_3_, alarminfoe0_.created_time as created_2_3_, alarminfoe0_.ack_ts as ack_ts3_3_, alarminfoe0_.acknowledged as acknowle4_3_, alarminfoe0_.assign_ts as assign_t5_3_, alarminfoe0_.assignee_id as assignee6_3_, alarminfoe0_.clear_ts as clear_ts7_3_, alarminfoe0_.cleared as cleared8_3_, alarminfoe0_.customer_id as customer9_3_, alarminfoe0_.additional_info as additio10_3_, alarminfoe0_.end_ts as end_ts11_3_, alarminfoe0_.originator_id as origina12_3_, alarminfoe0_.originator_type as origina13_3_, alarminfoe0_.propagate as propaga14_3_, alarminfoe0_.propagate_relation_types as propaga15_3_, alarminfoe0_.propagate_to_owner as propaga16_3_, alarminfoe0_.propagate_to_tenant as propaga17_3_, alarminfoe0_.severity as severit18_3_, alarminfoe0_.start_ts as start_t19_3_, alarminfoe0_.tenant_id as tenant_20_3_, alarminfoe0_.type as type21_3_, alarminfoe0_.assignee_email as assigne22_3_, alarminfoe0_.assignee_first_name as assigne23_3_, alarminfoe0_.assignee_last_name as assigne24_3_, alarminfoe0_.originator_label as origina25_3_, alarminfoe0_.originator_name as origina26_3_, alarminfoe0_.status as status27_3_ from alarm_info alarminfoe0_ where alarminfoe0_.tenant_id=$1 and ($2 is null or alarminfoe0_.created_time>=$3) and ($4 is null or alarminfoe0_.created_time<=$5) and ($6 is null or alarminfoe0_.type in ($7)) and ($8 is null or alarminfoe0_.severity in ($9)) and ($10=false or alarminfoe0_.cleared=$11) and ($12=false or alarminfoe0_.acknowledged=$13) and ($14 is null or alarminfoe0_.assignee_id=uuid($15)) and (lower(alarminfoe0_.type) like lower(('%'||$16||'%')) or lower(alarminfoe0_.severity) like lower(('%'||$17||'%')) or lower(alarminfoe0_.status) like lower(('%'||$18||'%'))) order by alarminfoe0_.created_time desc nulls last, alarminfoe0_.id asc nulls last limit $19
ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:15,526 [http-nio-0.0.0.0-9090-exec-8] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:15,526 [http-nio-0.0.0.0-9090-exec-8] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column alarminfoe0_.propagate_to_owner does not exist
ESC[36mtb_30 |ESC[0m   Position: 623
ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:16,113 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-1 [Events] queueSize [0] totalAdded [14] totalSaved [14] totalFailed [0]
ESC[36mtb_30 |ESC[0m 2023-10-03 10:50:16,114 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-2 [Events] queueSize [0] totalAdded [56] totalSaved [56] totalFailed [0]

**Comment by mhuelsmann** [comment]
shorter:

leNode: SaveTS(c58c7e80-a815-11ea-a65d-c78be24fd3c9)]
2023-10-04 16:20:20,719 [http-nio-0.0.0.0-9090-exec-7] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
2023-10-04 16:20:20,719 [http-nio-0.0.0.0-9090-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column alarminfoe0_.propagate_to_owner does not exist
  Position: 623

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
