### ISSUE TITLE
Control widget customization

### ISSUE THREAD

**Issue by cerbica** [thingsboard/thingsboard#935]
Hi @vparomskiy ,
I'm using thingsboard V2.0.3.
I want to customize a control widget on thingsboard.
I use "Subscribe for attribute" method in order to retrieve on/off status, using as value the attribute named "control_attr".
My problem is: how to get the latest value of "control_attr" inside my customized control widget.

Any help is a appreciated.
Thanks
Sarah

**Comment by nabil-rejeb** [comment]
hi @cerbica ,
 take a look to issue #574 , you will find a widget to change attribute value from thingsboard.

I hope it can help you.
Rejeb nabil
