### ISSUE TITLE
[Question] Custom actions with HTML template

### ISSUE THREAD

**Issue by ChristianPastenR** [thingsboard/thingsboard#9365]
Greetings,

I'm working on a form (custom action with HTML template) and I need to disable a checkbox if the input above is empty or the checkbox itself is true, but the directive [disabled] ="attributes.machine == ' ' || attributes .sa_status == true " does not work for me, what am I doing wrong, ps: sometimes it does work. Thanks.

![image](https://github.com/thingsboard/thingsboard/assets/93354953/9732c157-50bd-4455-935e-6c58be9d3e96)

![image](https://github.com/thingsboard/thingsboard/assets/93354953/386bd979-e2ec-45ba-aa6b-f0236b0511a0)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
