### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mixo3891** [thingsboard/thingsboard#9367]
hi. I have update Thingsboard CE from 3.5 to 3.6.
I have one issue. I have write on 3.5 thingsboard round progress bar like this:
![image](https://github.com/thingsboard/thingsboard/assets/99183101/eb8efc1b-56a2-488d-8d3e-16ffeac2a033)

but on new version this progress bar have moved but can not find source code where it is, where must be, they is not.
they must be here: 
![image](https://github.com/thingsboard/thingsboard/assets/99183101/188ffba3-832b-4e2e-9f6f-997f9d1e7eba)
please help, where it is

**Comment by mixo3891** [comment]
Also on new version Widget library widgets is not grouped, and if you do not remember widget name you must check all page to find necessary one.

**Comment by devaskim** [comment]
Did you look at `Advanced` option of data key to find progress bar code (top right corner on your screenshot)?

**Comment by devaskim** [comment]
> Also on new version Widget library widgets is not grouped

There is `Widget Bundle` tab as was before

**Comment by mixo3891** [comment]
thank you found all.
