### ISSUE TITLE
[Question] oAuth Keycloak token to Thingsboard Token conversion

### ISSUE THREAD

**Issue by Serbinmatosh** [thingsboard/thingsboard#9368]
**Component**

 * Generic

**Description**
We are currently using Thingsboard, and use Keycloak as oAuth login IDM. 
Everything works when logging in, but it seems that Thingsboard is using the Keycloak token to authenticate the user, and then assigns them a Thingsboard token. 
We are currently having a problem authenticating the API calls to the backend from other services because the Thingsboard API does not recognize valid Keycloak tokens and seems to expect the actual Thingsboard token. 
We didn't find anywhere in the documentation about a specific API where we can convert a valid keycloak token to a valid Thingsboard token in order to access the APIs.

Is there a solution here for us? 

We want our keycloak users to be able to call any API with either their keycloak token or an API that converts the keycloak token to a Thingsboard token. If this is not possible, then the backend is inaccessible for anyone without the @thingsboard.io email.

We appreciate any help you can give.

**Environment**
 * OS:  MacOS and Windows 11
 * ThingsBoard: 3.5.1
 * Browser: name and version

**Comment by loicgillioz** [comment]
Hey, any update on this ?
