### ISSUE TITLE
[Bug] Problem loading widget configuration after upgrading from Thingsboard 3.5.1PE to 3.6PE

### ISSUE THREAD

**Issue by benjaminferrier** [thingsboard/thingsboard#9369]
**Bug description**

After upgrading Thingsboard from 3.5.1PE to 3.6PE, when connecting with non-admin users to accessible dashboards, there is an error displayed on each widgets : "Problem loading widget configuration. Probably associated widget type was removed" instead of widget expected content (graphs, tables ...) :

<img width="1269" alt="Screenshot from 2023-10-03 17-15-40" src="https://github.com/thingsboard/thingsboard/assets/88196784/20b3e312-a63d-4b5f-b78f-24245c10c483">

There is no problem with admin acounts.
I never had this problem during the previous upgrades.
I downgraded the instance to 3.5.1PE and all worked fine again.
I tried to upgrade again to 3.6PE and the problem appeared again ...

**Server Environment**
* Self-managed installation
* ThingsBoard 3.6PE
* Rocky Linux 8.8

**Client Environment**

Debian 12 with Firefox 115.3.0.esr (64-bit)

Thanks for your help !

**Comment by EinarArnason** [comment]
As a workaround, I assigned all groups on the customer user.

**Comment by benjaminferrier** [comment]
Hello EinarArnason, thank you for sharing the trick, that confirm that I am not the only one concerned. But I don't want to assign all groups to customer user, I hope there will be an update soon :-)

**Comment by xalt7x** [comment]
@benjaminferrier , @EinarArnason 
In this case, non-admin users must have read permission for a "Widget type" resource, which can be assigned for a "Generic" role type. Also, this permission is included in the standard "Customer User" role.

**Comment by philippludwig** [comment]
> As a workaround, I assigned all groups on the customer user.

And how did you do that?
