### ISSUE TITLE
[Question] How to close widgetContext.alert() programmatically?

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#9375]
How to close widgetContext.alert() programmatically?
I wonder if there's any function or method i can call to close the showing widgetContext.alert dialog. So that i can call another alert dialog without sacking them if user didn't press close button.
 * TB: PE 3.4.4

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
