### ISSUE TITLE
[Question] after fresh install on ubuntu 22.04 container there is no process listening on port 8080

### ISSUE THREAD

**Issue by redwil** [thingsboard/thingsboard#9376]
**Component**
 * Installation
    Tried a default install of community edition on standalone local server postgres+cassandra, kafka queue
 
**Description**
followed the instructions 
everything seem correct no installation errors
started thingsboard service - no errors
- log: too big to paste here - suggestions  for where to put it for examination
-- enabled TRACE for TB server in logback
-- relevant errors
2023-10-06 17:27:25,466 [main] ERROR o.t.server.queue.kafka.TbKafkaAdmin - Failed to get all topics.
2023-10-06 17:28:26,201 [main] ERROR o.s.boot.SpringApplication - Application run failed
-- warnings:
--- lots and lots from kafaka
ran grep 8080 on log with empty results
ran 'netstat -napt' | grep 8080' with empty results

It seems to me that TB does not start the service at 8080

**Environment**

 * OS:  ubuntu 22.04LTS minimal server under LXD/LXC container
 * ThingsBoard: 3.6.0 (latest from the install instructions)
 * Browser: N/A (did not get to that point to use one)
- environment details: can provide other details if needed
-- lxd/lxc container: 
--- source: images:ubuntu/jammy (22.04 LTS) this is a minimal ubuntu server
-- extra packages installed besides the ones in installation instructions
--- gpg as dependancy to apt-key
--- net-tools for 'netstat' to look at listening ports in the system

I would appreciate, obviously, some hints to where to look for the problem

**Comment by redwil** [comment]
Forgot one thing to mention:
- tried a bare install of 3.6.0 postgres only, in-memory queue and seem to work. could reach the instance at port 8080
-

**Comment by Ultrazombie** [comment]
I realize it's been a while, but if you still have this problem - please provide the thingsboard.log file to see what's causing it.

**Comment by redwil** [comment]
Sorry it has been a while i had my project on hold.

i never solved the issue anyway. will have to start from scratch again

when i get to it i will post the log

thanks
