### ISSUE TITLE
[Question] How can I create a widget to plot an array of integer 

### ISSUE THREAD

**Issue by ignadeandres** [thingsboard/thingsboard#9378]
**Component**

 * UI

**Description**
Hello. I have a device that sends every few minutes an array of integers to my thingsboard instance that will store them in a single variable and I'd like to plot them in a widget chart in an orderly manner: first goes first, second goes second, etc. This chart is meant to have different "time windows" so that I can see the last X sent values. 

Example: 

Values: [1, 2, 3 ,4 ,5]
I want a widget that using this array as source plots in the X-axis displays the element's position in the array (in this case: 1 -> 1, 2 -> 2...) and in the Y-axis the value itself.

**Environment**

 * ThingsBoard: 3.4.1
 * Browser: Chrome last version

**Comment by devaskim** [comment]
Here is [official example](https://thingsboard.io/docs/user-guide/contribution/widgets-development/#time-series-example)

**Comment by Ultrazombie** [comment]
closed due to inactive
