### ISSUE TITLE
[Feature Request] OR logic between Filter Keys

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#9379]
Hi

We can really use OR statement between FIlter keys, otherwise they are not very useful to create good user experience filtering/finding devices.

![image](https://github.com/thingsboard/thingsboard/assets/31729091/b3664e4f-56db-4065-b7cc-a992c4e95660)

Complex condition is only available for each Key and not between keys.

**Comment by t0mZ4** [comment]
for example, we'd like user to set filter, but also to remove filter, by selecting "Clear", or to only SET some of the filters. With AND statement between filter keys that's not possible 
![image](https://github.com/thingsboard/thingsboard/assets/31729091/11f9ebc4-01b9-49a5-9235-e3e6afe59e39)

**Comment by oxygen50** [comment]
Could you solve this?
We also would like a feature like this as we filtering by two keys but need a OR operation for a widget.
push...

**Comment by mykhailokornieiev** [comment]
Hi
For now, there’s no possibility of using OR logic in dashboard filters.
However, this is a valid improvement previously added to our backlog (PROD-3318). Currently, there is no estimated timeframe for this feature or whether it will be added. 
Once the product team reviews this ticket, we’ll post an update on when this feature could be delivered if they decide to add it to the product.

**Comment by oxygen50** [comment]
@mykhailokornieiev duplicate feature request: https://github.com/thingsboard/thingsboard/issues/8033

**Comment by darioludwigswk** [comment]
We really could use OR too!

**Comment by mykhailokornieiev** [comment]
Since there is already a created prod ticket, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by rpcai** [comment]
Supporting this as a feature - this limitation is an acute pain point for me currently

**Comment by ajmachin** [comment]
Supporting this as a feature as well, I can't understand how a filter functionality has been implemented without an OR logic.

**Comment by t0mZ4** [comment]
Yea its a crucial missing feature for us still.

**Comment by dpergarc-c** [comment]
I don't want to be that guy, but this functionality would also be great for our projects!

**Comment by bealopb** [comment]
This is a feature that should be a MUST. We are losing some functionality in the projects because of it.

**Comment by JakeDaSnake80** [comment]
Absolutely agree. Filters without the OR functionality and that is hasn't been solved is very surprising (and not in a good way)

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15090 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.

**Comment by mykhailokornieiev** [comment]
Hi. The feature is implemented https://github.com/thingsboard/thingsboard/pull/15286 and will be a part of 4.4 release.
Feel free to open a new ticket in case any questions or issues arise.
Have a great day.
