### ISSUE TITLE
TB 2.0.3: Error Running Rule Chain Filter Script on RPi 3

### ISSUE THREAD

**Issue by ToyotaCorollary** [thingsboard/thingsboard#938]
After upgrading to 2.0.3 on an RPi3 (and adding JVM flag as per https://github.com/thingsboard/thingsboard/issues/883) my previously-working rule chain appears to fail to execute. At least one problem seems to involve its filter script: anytime I test the filter script, or a simple dummy filter script, with the "Test Script" function I get the error

Can't compile script: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms

When I downgrade back to 2.0.2 the "Test Script" function works properly.

**Comment by nuco** [comment]
I solved that by increasing the "max_cpu_time" value in thingsboard.yml

**Comment by ToyotaCorollary** [comment]
Early indications are that this appears to have worked; thanks!
