### ISSUE TITLE
Copy some of device data in other devices

### ISSUE THREAD

**Issue by Gi0Lynx** [thingsboard/thingsboard#9380]
**Component**

 * Rule Engine
 * Generic

**Description**
Hello, 
I'm using ESP32 to send telemetry to thingsboard. I'm using multiple sensors and sending data to one device, using one token but  with different keys.
I was trying to find a way to copy part of telemetry data of that device in other devices.
for example if key is "temperature" I want to copy that in "temperature sensor"
I don't know if it's possible working with rule chain or relations

I know I probably didn't use best technical words to explain my problem, but I'm new to this stuff and trying to learn more about it :)

**Comment by devaskim** [comment]
[These guides](https://thingsboard.github.io/docs/guides/#AnchorIDDataProcessing) will help you

**Comment by avindra99** [comment]
@devaskim where can I find end to end flow of the application? Do we have documentation?

**Comment by devaskim** [comment]
> where can I find end to end flow of the application?

@avindra99 End to end solution is paid job, I think. 

> Do we have documentation?

I already provided you with the link to guides and documentation

**Comment by Gi0Lynx** [comment]
> [These guides](https://thingsboard.github.io/docs/guides/#AnchorIDDataProcessing) will help you

They were very helpful ! Thank you
