### ISSUE TITLE
There is no Add Device + option when I logined with customer account

### ISSUE THREAD

**Issue by avindra99** [thingsboard/thingsboard#9386]
Feature Request:
I would like to request the addition of the "Add Device" option for customer accounts as well. This would provide a consistent and user-friendly experience for all users, allowing them to easily add devices when needed.

Use Case:
As a customer, I often need to add new devices to my account. Having the "Add Device" option easily accessible would streamline this process and improve the overall user experience.

Expected Behavior:
When logged in with a customer account, there should be a visible "Add Device" option, similar to what is available for administrator accounts.

Additional Information:
This feature enhancement would make the platform more user-friendly and efficient for customers, reducing the need for multiple account types to access basic functionalities. It would also promote a more consistent user experience across different account types.

![Administrator level](https://github.com/thingsboard/thingsboard/assets/94655548/327c2e9a-94f7-4b59-924b-369ae53bc5fa)
![customer level](https://github.com/thingsboard/thingsboard/assets/94655548/a6a40b01-052e-47c4-9998-76254ad9c03a)

**Comment by avindra99** [comment]
The marker has misplaced in the first screenshot actually missing is + option which is beside refresh option

**Comment by mykhailokornieiev** [comment]
In this case, you need to use RBAC (Role-Based Access Control), with which you can set up the necessary permissions for each customer group, so they will be able to add new devices by themselves. But, this feature is available only in Thingsboard PE, and as I see you use CE.
Anyway, you can use the next documentation to familiarize yourself
https://thingsboard.io/docs/pe/user-guide/rbac/#thingsboard-ce-vs-pe-security-features-comparison

**Comment by Ultrazombie** [comment]
Closed due to inactive
