### ISSUE TITLE
[Question] Thingsboard Start Failure

### ISSUE THREAD

**Issue by KnoetzeRuan** [thingsboard/thingsboard#9394]
Good Day

Our servers restarted and now Thingsboard does not want to start up. The only error I can see in the log is as follows:

2023-10-11 11:05:35,007 [main] ERROR o.t.s.t.l.s.DefaultLwM2mTransportService - Failed to gracefully stop the LwM2M transport server!
2023-10-11 11:05:37,908 [main] ERROR o.s.boot.SpringApplication - Application run failed

Below is the log file in question. 
[thingsboard.zip](https://github.com/thingsboard/thingsboard/files/12868670/thingsboard.zip)

Can anyone please assist in why it does not want to start.

Thank You

**Environment**

 * ThingsBoard: 3.4.1 PE - Perpetual License

**Comment by KnoetzeRuan** [comment]
UPDATE:

I managed to get the server running on Port 8080 with SSL disabled. There is however nothing running on Port 443 as Shown below:
![image](https://github.com/thingsboard/thingsboard/assets/145371049/d17613db-f75b-4797-8e2f-9cb7f9c72cbb)

Is there a reason that ssl port would not be able to bind?

Thanks

**Comment by mykhailokornieiev** [comment]
It looks like your are trying to run the ThingsBoard instance on a low-level(443) port. For this, you need to give access directly to Java. 
Use this command to execute Java on port 443:
`sudo setcap 'cap_net_bind_service=+ep' /usr/lib/jvm/java-11-openjdk-amd64/bin/java`
However, it would be better to use 8080 for local ThingsBoard instance. If you need port 443 the best practice is to use HAProxy
https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/#prerequisites

**Comment by Ultrazombie** [comment]
Closed due to inactive
