### ISSUE TITLE
[Question] Entity table and alarms counter

### ISSUE THREAD

**Issue by elgutierrez** [thingsboard/thingsboard#9395]
**Component**
 * UI

**Description**
I'm trying to build a dashboard to display a list of assets with some column with attributes from it. I also would like to display an icon showing if it has some type of alarms (`Energy` alarm, `HVAC`, etc). Those alarms are generated by devices attached to those assets. ie: 

```
Store (Asset) ---contains --- > Energy Meter (device)
              ---contains --- > HVAC (device)
```
I know that I can propagate the alarms from the devices to the parent asset. But I can't find any way to display a column with the alarms using the `Entity table` widget.

One workaround that I'm considering is to set an alarm counter in the asset when the device creates/clears the alarm, but I don't think it's the best way to go. Is there another way for doing so?

<img width="759" alt="Screenshot 2023-10-11 at 11 53 59" src="https://github.com/thingsboard/thingsboard/assets/492679/a0b40416-a32f-4e87-849c-fae37335a0d2">

**Comment by devaskim** [comment]
In my opinion, alarm counter is the best solution for a performance perpective.

As alternative, you can use `cell content update function` in the table widget to 2 things in it:
1. Return empty empty, for example, `div` but with unique `id` html attribute (for example, asset id). 
2. Send async request to TB API to count alarms and after getting response, you should find with `jQuery` or raw [getElementById](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) appropriate `div` and update its content with the received count.

This approach works - you can find the similar discussion there but about customer name. But it (approach) requires sending a lot of alarm counting requests.

**Comment by Ultrazombie** [comment]
closed due to inactive
