### ISSUE TITLE
Historical data not being pulled.

### ISSUE THREAD

**Issue by PopoTheSapien** [thingsboard/thingsboard#94]
I did a fresh install of thingsboard 1.2.2 on ubuntu and for some reason my dashboard trends aren't getting updated with historical data (only real-time).  However, my other box, which I upgraded to 1.2.2 still works.  Not sure whats wrong ....

**Comment by setevik00** [comment]
In widget settings -> timewindow -> Historical values, what is data aggregation function? By default it is average, e.g. its calculates average values for the certain period of time.
Try to set Aggregation function to None and Grouping interval to 1 second. 
BTW, are you sure that historical data is available in DB?

**Comment by PopoTheSapien** [comment]
Thanks 👍  Was using the map widget to test data.  Didn't think averaging would be applicable...
