### ISSUE TITLE
entityDescription instead of entityName

### ISSUE THREAD

**Issue by glancia** [thingsboard/thingsboard#940]
Hi,

If we think about the naming convention for entities in a large system, it would be nice that the entity name could be structured and the fancy name string to be show in the dashboards could be the entity description.

Is it possible today? What is the variable handling the description. I tried ${entityDescription} without success.

Thanks

**Comment by ashaforost** [comment]
Hi @glancia ,

You can set your 'fancy name string' in the entity label section, which later can be easily fetched in the rule chains as well as in the widget titles in the advanced widget settings:
![image](https://user-images.githubusercontent.com/47900737/151345624-16bd7de3-d3c5-4a94-bcae-01e73a94e675.png)
![image](https://user-images.githubusercontent.com/47900737/151345746-91e56e08-dcc8-4109-8bdb-56be46bb6a8f.png)
