### ISSUE TITLE
[Bug] HTML/Markdown widget is not working with new version v3.6.0

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard#9403]
**Describe the bug**
The HTML/Markdown widget is not working with Datasources after the upgradation of cloud version to v3.6.0. The widget is going complete white when the first time we open the user interface. This issue temporarily clears when we select the Edit mode option. 

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**
* OS: Windows 11
* Browsers and version: Chrome 117.0.5938.150 and Microsoft Edge 117.0.2045.60

**To Reproduce**
1. Add a new widget of type html/markdown
2. Add the datasource of type entity
3. Save changes
4. Refresh the webpage
Also, please find attached the widget for reproducing the issue.
[markdown_html_card.json](https://github.com/thingsboard/thingsboard/files/12885466/markdown_html_card.json)

**Expected behavior**
When we open the dashboard, the widget should appear and show the required information, but its just showing white background.

**Screenshots**
Markdown/html widget at the initial loading of webpage.
![image](https://github.com/thingsboard/thingsboard/assets/35078099/9ccbe05a-4590-4c5e-87f3-10c979b50346)

Markdown/html widget after we select the Edit mode option.
![image](https://github.com/thingsboard/thingsboard/assets/35078099/d322f385-dfa8-4dbe-be29-4d978ba31e24)

**Comment by ChantsovaEkaterina** [comment]
Hello, @akseerali 
Please, add the missing closing `</span>` tag to your markup, and then the widget will work as expected.

**Comment by akseerali** [comment]
Hi @ChantsovaEkaterina 

Thanks you for the response and information. 
I have updated and tested it, but unfortunately the issue persists.

If possible, could you please share the widget? Thanks

**Comment by ChantsovaEkaterina** [comment]
Hello, @akseerali 
Try importing the following samples to your dashboard.
[markdown_html_card (1).json](https://github.com/thingsboard/thingsboard/files/12913747/markdown_html_card.1.json)
[markdown_html_card (2).json](https://github.com/thingsboard/thingsboard/files/12913751/markdown_html_card.2.json)
