### ISSUE TITLE
[Question] Meraki Sensors Support

### ISSUE THREAD

**Issue by lsenecaux** [thingsboard/thingsboard#9404]
Hi,

Does TB supports Meraki Sensors ?
If yes, how to configure TB to import these IoT ?
In fact, Meraki Sensors are BLE devices and connect to MQTT Broker through Meraki APs or Camera, so multiples IoT devices send message to the broker with same MQTT username / password.
More information here : [https://documentation.meraki.com/MT/MT_General_Articles/MT_MQTT_Setup_Guide](https://documentation.meraki.com/MT/MT_General_Articles/MT_MQTT_Setup_Guide)
Thanks in advance,

**Comment by devaskim** [comment]
As I understand, you can use [thingsboard-gateway ](https://github.com/thingsboard/thingsboard-gateway/) to [map mqtt data](https://thingsboard.io/docs/iot-gateway/config/mqtt/#section-mapping) to different devices.

**Comment by lsenecaux** [comment]
Thanks @devaskim ,

I can now get metrics from Meraki Sensors

**Comment by lsenecaux** [comment]
Have you got any tips to programmatically rename devices ?
TB IoT Gateway create devices with mac address. 
I would like to make a rest api call to meraki dashboard and retrieve sensor name.
I tried with rule chain, but without success.

regards,

**Comment by devaskim** [comment]
> TB IoT Gateway create devices with mac address.

It depends on a connector configuration that you provided. So maybe you need just tune it.
By the way, it is a risky idea to rename devices after gateway created them. For details read this [docs page](https://engix-ltd.github.io/docs/iot-gateway/how-device-removing-renaming-works/).

In general, use [this issues tracker](https://github.com/thingsboard/thingsboard-gateway/issues) for gateway related questions

**Comment by lsenecaux** [comment]
Device name (mac address) is pull from MQTT Topic :
`meraki/v1/mt/<network id>/ble/<device mac>/<metric>`
The only way to get real device name (from meraki dashboard) is to make a REST API Call...

**Comment by devaskim** [comment]
Sorry, I don't understand yet. How does TB  get real device name?

**Comment by devaskim** [comment]
Finally I got it. I thought Meraki dashboard is in TB server.
To update device info in TB you can use its REST API . [One ](https://demo.thingsboard.io/swagger-ui/#/device-controller/getTenantDeviceUsingGET) to find by mac. [two ](https://demo.thingsboard.io/swagger-ui/#/device-controller/saveDeviceUsingPOST) to update device info
