### ISSUE TITLE
How to create custom widget type on Thingsboard CE v3.5.1

### ISSUE THREAD

**Issue by ShukeshAiotel** [thingsboard/thingsboard#9408]
**Component**

Custom Widget_Type 

1. What are the process and steps to successfully create a widget type  ? [ currently used path for widget development -  /ui-ngx/src/app/modules/home/components/widget ]
2. What are /application/src/main/data/json/system/widget_bundles and json/widget_types and how are they used in creating the custom widget types?
3. Should the DB flushed and reloaded after the creation and build of custom widget? How does it work?
4. We had gone through the thingsboard widget development guide which helps to build a widget with existing widget types. But, we are looking for a guide that can help us build a widget type from scratch.
5. Can you provide us a sample layout and an example for further understanding.

**Environment**
 * ThingsBoard: v3.5.1

**Comment by devaskim** [comment]
As I know there is no such guide or doc page. But I am curios what the problem you could not solve with the existing widget type?

**Comment by AIOTEL-sanjanaa** [comment]
So, there are a few things we need to achieve in a single widget.
1. We need to get client attributes to process the client attribute data.
2. Set shared attributes based on the widget input. 
3. On checking the client attributes again, send an ACK to the device using shared attributes.
On trying to implement this logic, we used two widget types, latest values and control widget. But building a single custom widget might will be very useful to us.  
Please let us know the ways to achieve this functionality.

**Comment by devaskim** [comment]
Just use one widget of `latest` type. There use `self.ctx.attributeService` to check and update all type of attributes.

**Comment by AIOTEL-sanjanaa** [comment]
Latest value only reads the attributes, we want the same widget to set shared attributes in the same widget. Suppose I choose to view ACK in the table and have a mat-form-field on top, based on the input, i.e, in the field Node - which will give a json inputs of all the opcua nodes to be read, should be updated in the shared attribute and the gateway will send the list of nodes active in the connector - I found that only the control widgets set the shared attribute. If we could set it in the latest widget, can you give a way to go about it. Which functions to use exactly?

**Comment by devaskim** [comment]
I am talking about custom widget of type `latest`, so there you write any JavaScript you want.
Here is [attribute service code](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/http/attribute.service.ts) - it is the most up to date list of its functions, believe me.

**Comment by AIOTEL-sanjanaa** [comment]
Okay will try and revert back if I have any questions. Thank you.

**Comment by AIOTEL-sanjanaa** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/132904735/408d2994-349e-4dbd-8f9a-9bb6a8c8eb2e)
Is there a way that I can set just the entity? I don't want to select the data key as all the connectors will be sending with the same key, so I want it hard-coded.

**Comment by devaskim** [comment]
> Is there a way that I can set just the entity?

Add to JS part of your widget
```
self.typeParameters = function() {
    return {
        dataKeysOptional: true
    }
}
```

**Comment by devaskim** [comment]
> If am right, this is how I used to send shared attributes

Please, post code instead of screenshot.

In general, TB API return Angular/RxJS `Observable` object. You need to call `subscribe` method to get response or error
```
self.ctx.attributeService.someMethod(...).subscribe(
    result => {
        console.log('Gor result', result);
    },
    error => {
        console.log('Gor error', error );
     }
);
```

**Comment by AIOTEL-sanjanaa** [comment]
Thank you

**Comment by Vaibhav0216** [comment]
I want the widget which gives me attribute latest value and also control button to send command like switch in same widget. then what should type i choose. I have choosed control widget but in this case some problems comes in front of me like below issue posted on community. 

Issue with Undefined self.ctx.datasources in Custom Control Widgets #11478
