### ISSUE TITLE
is there any way i can show customer dashboard(webview) directly without login page only by using  token

### ISSUE THREAD

**Issue by mohan-m-u** [thingsboard/thingsboard#942]

**Comment by emeng** [comment]
set dashboard to public.

**Comment by mohan-m-u** [comment]
@emeng  in my case i don't think making dashboard as public and hard-coding URL is a good idea.

**Comment by robertoenr** [comment]
Hi, any way to do this in recent TB versions?

**Comment by volodymyr-babak** [comment]
You can add X-Authorization header to the request headers:

--header "X-Authorization: Bearer YOUR_JWT_TOKEN"

This should allow accessing restricted dashboards (and other entities) without entering login and password.
