### ISSUE TITLE
[Question] How to use white labeling in a script ?

### ISSUE THREAD

**Issue by TortueHardie** [thingsboard/thingsboard#9424]
Hello,
We've recently updated to ThingsBoard 3.6.0 PE and we have a problem using white labeling.
I was editing the white labeling using attributes in a script but since 3.6 it is apparently no longer possible to use attributes for white labeling.
How can I edit white labeling in a script ?

**Comment by myroslav-tb** [comment]
Hello @TortueHardie, you can use the Rest API whitelabeling controller for your script, you can check it by accessing http://YOUR_HOST/swagger-ui/#/white-labeling-controller

**Comment by Ultrazombie** [comment]
Closed due to inactivity
