### ISSUE TITLE
[Feature Request] Adding Entity Query Service in Custom rulnode TBContext (https://github.com/thingsboard/thingsboard/blob/release-3.6/rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java)

### ISSUE THREAD

**Issue by NistantriTech-Dhaval** [thingsboard/thingsboard#9426]
**Is your feature request related to a problem? Please describe.**
As of now to find the information by filtering entities using query there is no any rule nodes available neither in custom rule node we can directly have access to call Entity Query service
 
**Describe the solution you'd like**
if we have **Entity Query Service** accessible in TBContext for custom rulenode we can develop custom rule node to fetch relevant information

**Describe alternatives you've considered**
For now temporary solution we are fetching the in rule chain and calling the rest API but that is not best solution as credentials needed to be accessible in rulechain hardcoded or another way. 

**Additional context**
Please Let us know when should we expect this feature or doo you guys have any other planning 
please consider it for both Community as well for Professional Edition 

Thanks

**Comment by devaskim** [comment]
#9416

**Comment by 0xFiro** [comment]
+ 1

**Comment by tusharCF** [comment]
+1

**Comment by myroslav-tb** [comment]
Hi @NistantriTech-Dhaval, since pull request was merged in the ticket https://github.com/thingsboard/thingsboard/pull/9416 I'm closing this one.

Best regards,
Myroslav
