### ISSUE TITLE
Delete asset causes  cassandra crash(delete relation time out )

### ISSUE THREAD

**Issue by sdfantasy** [thingsboard/thingsboard#943]
If a asset has relations contains many devices, when device has new alarms,the relations between asset and device alarm is added rapidly。If i delete the asset, the TB will delete all the relations between asset and device alarm ,this cause a  time-out error for cassandra,then cassandra is crashed.
Is there a loop delete mechanism to avoid this problem?

**Comment by volodymyr-babak** [comment]
not for the time, that the ticket was created, but starting from 3+ all entities are stored in PostgreSQL and this issue was not detected for the last years. So you should not experience this type of problem anymore.
