### ISSUE TITLE
[Bug] prevValue and timePrev not working in post-processing function

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#9434]
**Describe the bug**
In attribute cards or simple HTML card the prevValue and timePrev are always 0.

**Your Server Environment**
* own setup
  * local infrastructure
  * 3.5.1 PE
  * Debian 12

**Comment by t0mZ4** [comment]
i find same behavior to be true in TimeSeries Graph

**Comment by myroslav-tb** [comment]
Hi @Backdraft007, if a previous value doesn't exist in the database by default, prevValue and timePrev will be returning a 0.

Best regards,
Myroslav
