### ISSUE TITLE
[Question] How to process data that posted to v1/gateway/telemetry?

### ISSUE THREAD

**Issue by slashjiang** [thingsboard/thingsboard#9438]
**Component**

 * Rule Engine

**Description**
I have some IoT gateway from hardware vendor, those vendors have their customized JSON format, for example *origJson*:
```
{
    "type": "change",
    "sn": "GW001",
    "time": "2023-10-16 16:09:56",
    "data": {
        "C1_D1": [
            {
                "id": "Ua",
                "desc": "æ ç¾01",
                "quality": "0",
                "value": "391.100"
            },
            {
                "id": "Uca",
                "desc": "æ ç¾02",
                "quality": "0",
                "value": "384.700"
            },
            {
                "id": "Ia",
                "desc": "æ ç¾03",
                "quality": "0",
                "value": "6.260"
            },
            {
                "id": "Pa",
                "desc": "æ ç¾05",
                "quality": "0",
                "value": "654.910"
            }
        ],
        "C1_D2": [
            {
                "id": "Ua",
                "desc": "æ ç¾01",
                "quality": "0",
                "value": "391.100"
            },
            {
                "id": "Uca",
                "desc": "æ ç¾02",
                "quality": "0",
                "value": "384.700"
            },
            {
                "id": "Ia",
                "desc": "æ ç¾03",
                "quality": "0",
                "value": "6.260"
            },
            {
                "id": "Pa",
                "desc": "æ ç¾05",
                "quality": "0",
                "value": "654.910"
            }
        ]
    }
}
```
If I post the message to v1/devices/me/telemetry, Thingsboard does not know this format, so I have to create device C1_D1, C1_D2, then I use rule chain reformat this JSON data and update both device. I can not use rule chain to make C1_D1 and C1_D2 online or active.
If I post this message to v1/gateway/telemetry, thingsboard will create device "time", "sn", "date" ect. 
So If I format this JSON to *gwTypeJson*
```
{
    "C1_D1": [{
    	"ts": 1697589243471,
    	"values": {
			"Ua": "391.100",
			"Uca": "384.700",
			"Ia": "6.260",
			"Pa": "654.910"
        }
     }],
    "C1_D2": [{
    	"ts": 1697589243471,
    	"values": {
			"Ua": "391.100",
			"Uca": "384.700",
			"Ia": "6.260",
			"Pa": "654.910"
        }
     }]
}
```
Thingsboard will create both devices and update telemetry automatically, This is most what I hope it to do.

My idea is post *origJson* to v1/gateway/telemetry and use rule chain to format *origJson* to *gwTypeJson*, but it does not work, It seems that message post to v1/gateway/telemetry does not go into the rule chain that I set to my gateway device.

Any idea to solve this?

**Environment**

 * OS:  Debian 12
 * ThingsBoard: 3.6.0
 * Browser: Chrome 111.0.5563.146

**Comment by ssakharova** [comment]
Hello @slashjiang,

Please proceed with the following documentation - https://thingsboard.io/docs/pe/reference/gateway-mqtt-api/
