### ISSUE TITLE
[Bug] After upgrading to 3.6 - GUI error

### ISSUE THREAD

**Issue by realbeeit** [thingsboard/thingsboard#9444]
**Describe the bug**
After upgrading to 3.6 GUI is not right. There are errors, buttons not showing correctly.

**Your Server Environment**

* own setup
  * Local VPS
  * ThingsBoard Version: 3.6
  * OS Name and Version:  Ubuntu 20.04 (64-bit)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows, MacOS
* Browser: All

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/99592619/732722a9-e94d-4e82-af7c-03faeccf87a3)

**Comment by trikimiki** [comment]
This is a visual-only issue - your browser contains locale from older version. You need to clear browser cache for ThingsBoard site. The easiest way is "forced page reload" (Ctrl+F5)

**Comment by realbeeit** [comment]
Thank you very much. That was the issue.
