### ISSUE TITLE
no matching function for call to 'ThingsBoardSized<>::ThingsBoardSized(WiFiClient&)

### ISSUE THREAD

**Issue by jimmy737** [thingsboard/thingsboard#9450]
**Describe the bug**
I receive this error compiling a simple sketch on Arduino IDE. No error with version 11. Only version 12

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**
Arduino IDE| version 18 and 2.2.1

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]  CHROME
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**
Compile a simple sketch that use tb.sendTelemetryData("TEMPLATE", MyValue++);

**Expected behavior**

**Screenshots**
<img width="946" alt="error" src="https://github.com/thingsboard/thingsboard/assets/148379458/a8a63e84-f254-43ba-b745-00d505c38b84">

**Additional context**
`
#include <ThingsBoard.h>
#include <WiFi.h>

#define WIFI_AP "Gladysa"
#define WIFI_PASSWORD "Gladysa26"
#define TOKEN "esp32token2023"
#define LED_BUILTIN 2

int MyValue=0;
int status = WL_IDLE_STATUS;
char thingsboardServer[] = "thingsboard.cloud";

WiFiClient wifiClient;
ThingsBoard tb(wifiClient);

void setup() {

  pinMode(LED_BUILTIN, OUTPUT);

  Serial.begin(9600);

  InitWiFi();
  
  delay(5000);
}

void loop() {

  CheckConnection();

  BlinkLedIfConnected();

  delay(2000);

  tb.sendTelemetryData("TEMPLATE", MyValue++);

}

void InitWiFi() {
  Serial.println("Connecting to AP ...");
  WiFi.begin(WIFI_AP, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("Connected to AP");

}

void reconnect() {
  // Loop until we're reconnected
  while (!tb.connected()) {
    status = WiFi.status();
    if (status != WL_CONNECTED) {
      WiFi.begin(WIFI_AP, WIFI_PASSWORD);
      while (WiFi.status() != WL_CONNECTED) {
        delay(1000);
        Serial.print(".");
      }
      Serial.println("Connected to AP");
    }
    Serial.print("Connecting to ThingsBoard node ...");
    if (tb.connect(thingsboardServer, TOKEN)) {
      Serial.println("[DONE]");
    } else {
      Serial.print("[FAILED]");
      Serial.println(" : retrying in 5 seconds]");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void CheckConnection() {

  if (!tb.connected()) {
    reconnect();
  }
}

void  BlinkLedIfConnected() {

              if (WiFi.status() == WL_CONNECTED) {
              digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
              delay(500);                      // wait for a second
              digitalWrite(LED_BUILTIN, LOW);   // turn the LED off by making the voltage LOW
              delay(500);                    
              }
}`

**Comment by jimmy737** [comment]
I just tried another example to learn how to use RPC.  Got the same error. Does anyone know how to resolve this?
Thank you.
 no matching function for call to 'ThingsBoardSized<>::RPC_Subscribe(RPC_Callback [1], const size_t&)'

**Comment by somik123** [comment]
Downgrade your thingsboard version to 0.10.2 and it'll work fine. Apparently the developers have not heard of (or care about) backwards compatibility. Then again, since the major version is still 0 (for 0.10.2) i guess it is still a work in progress...

**Comment by somik123** [comment]
I don't know if this will help you, but here is my code to send data to my server:

```
#include <Wire.h>
#include <AHT20.h>
#include <BMP280.h>

#include <WiFi.h>
#include <HTTPClient.h>
#include <ThingsBoard.h>  // ThingsBoard SDK

// ThingsBoard server instance.
#define TOKEN "TOKEN_GOES_HERE"
#define THINGSBOARD_SERVER "iot.example.com"

// Update every 60 seconds
int send_delay = 60 * 1000;

// Main application loop delay in ms
int quant = 20;

// Keep track of how long ago the data was sent
int send_passed = 0;


const char* ssid = "WIFI_SSID";
const char* password = "WIFI_PASSWORD";



// Initialize the sensors
AHT20 aht20;
BMP280 bmp280;

// Initialize ThingsBoard client
WiFiClient espClient;

// Initialize ThingsBoard instance
ThingsBoard tb(espClient);



void setup() {

  Serial.begin(115200);
  delay(1000);

  

  Wire.begin();  //Join I2C bus

  //Check if the AHT20 will acknowledge
  if (aht20.begin() == false) {
    Serial.println("AHT20 not detected. Please check wiring. Waiting.");
    while (aht20.begin() == false) {
      Serial.print(".");
      delay(1000);
    }
  }
  Serial.println("AHT20 acknowledged.");

  bmp280.begin();

  // Start WiFi connection
  WiFi.mode(WIFI_STA);  // Optional
  connectToWifi();
  Serial.print("Local ESP32 IP: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(quant);

  send_passed += quant;

  // Reconnect to WiFi, if needed
  if (WiFi.status() != WL_CONNECTED) {
    connectToWifi();
    return;
  }

  if (send_passed > send_delay) {
    send_passed = 0;
    connectToThingsBoard();
    read_sensor(); // and send data to server
  }
}



void read_sensor() {
  // put your main code here, to run repeatedly:
  //If a new measurement is available

  bool flag = false;

  while (flag == false) {
    if (aht20.available() == true) {
      //Get the new temperature and humidity value
      float temperature = aht20.getTemperature();
      float humidity = aht20.getHumidity();

      //Get pressure value
      float pressure = bmp280.getPressure() * 0.98692327 / 100000;

      sendDataToServer(temperature, humidity, pressure);

      flag = true;
      break;
    } else {
      delay(1000);
    }
  }
}





void connectToWifi() {
  Serial.println("Connecting to AP ...");
  // attempt to connect to WiFi network
  WiFi.begin(ssid, password);

  // Loop until we're reconnected
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("Connected to AP");
}





void connectToThingsBoard() {
  // Reconnect to ThingsBoard, if needed
  if (!tb.connected()) {

    // Connect to the ThingsBoard
    Serial.print("Connecting to: ");
    Serial.print(THINGSBOARD_SERVER);
    Serial.print(" with token ");
    Serial.println(TOKEN);
    if (!tb.connect(THINGSBOARD_SERVER, TOKEN)) {
      Serial.println("Failed to connect");
      return;
    }
  }
}





void sendDataToServer(float temperature, float humidity, float pressure) {

  Serial.println("Sending data...");

  tb.sendTelemetryFloat("temperature", temperature);
  tb.sendTelemetryFloat("humidity", humidity);
  tb.sendTelemetryFloat("pressure", pressure);

  //Print the results
  Serial.print("Temperature: ");
  Serial.print(temperature, 2);
  Serial.print(" C\t");

  Serial.print("Humidity: ");
  Serial.print(humidity, 2);
  Serial.print("% RH\t");

  Serial.print("Pressure: ");
  Serial.print(pressure);
  Serial.print("Pa");

  Serial.println();
}

```

**Comment by Shayantika-Dhar** [comment]
i am having same issue with thingsboard not working at arduino ide, the same code is running fine at wokwi online simulator but not at arduino ide

**Comment by Shayantika-Dhar** [comment]
tried solving but it wont work.

**Comment by jimmy737** [comment]
Here is my solution that worked for me. Move away from thingsboard to a better IoT platform like Arduino IoT. Cheap simple reliable and great support from a very active forum. Sent from my iPhoneOn Jan 3, 2024, at 1:35 AM, Shayantika Dhar ***@***.***> wrote:﻿
tried solving but it wont work.

**Comment by ashaforost** [comment]
Hi,

Please raise this issue in the [thingsboard-cliend-sdk repository ](https://github.com/thingsboard/thingsboard-client-sdk/issues). This way, the developer who worked on it may help you with your issue. 
I'm closing the current issue.

**Comment by ClaudioSeda** [comment]
Now. I had same problem. Downgraded to 14,0 worked
