### ISSUE TITLE
[Question] Storing delta value each day

### ISSUE THREAD

**Issue by realbeeit** [thingsboard/thingsboard#9451]
**Component**

 * UI

**Description**
Hello, is it possible to store delta from Value and chart card widget to telemetry? Or somehow else to store last value before midnight to other table? So I can display that delta day by day. I put screenshoot what value I want to store.

**Environment**

 * OS:  Ubuntu 20.24 64-bit
 * ThingsBoard: 3.6.0
 * Browser: Chrome
<img width="785" alt="Slika zaslona 2023-10-18 u 20 29 20" src="https://github.com/thingsboard/thingsboard/assets/99592619/d905bd10-4b0b-48d6-b447-46f86c5c31d2">
<img width="813" alt="Slika zaslona 2023-10-18 u 20 30 18" src="https://github.com/thingsboard/thingsboard/assets/99592619/652c439e-5619-48f5-a95a-df80277b9c76">

**Comment by realbeeit** [comment]
@Backdraft007 that is not it...I want from widget to telemetry or else...not rule chain.

**Comment by Backdraft007** [comment]
Sorry, then I'm out.

**Comment by devaskim** [comment]
@realbeeit you may use custom header action. But to activate it you need to click on the button in the right top corner. The button will appear after you create the action.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
