### ISSUE TITLE
[Question] Sharing a value between device and dashboard

### ISSUE THREAD

**Issue by philippludwig** [thingsboard/thingsboard#9454]
**Component**

 * Generic

**Description**
I have a value that I would like to set from a dashboard on the device. However, the value has an allowed range (0-255), and since the dashboard input controls don’t support min/max values, I will clamp the value to the allowed range from the device.

However, that does not seem to be possible. What I tried:

* Added a client attribute, because apparently these are read/write from both ends (according to the documentation)
* Pushed a value to the attribute from the device via HTTP. This works, the new value is displayed in the attribute list.
* Added an input control to the dashboard and selected the attribute as source.
* Entered a new value in the control. 

What I expected:

* The client attribute gets updated to the value I entered.

What happened:

* A new server attribute with the same name gets created. The client attribute is left alone.

**Environment**
 * OS: Debian current
 * ThingsBoard: No idea where to look for the TB version. It is not visible in the UI and I can’t find it in the logs. I installed the latest version 4 weeks ago.
 * Browser: Firefox current

**Comment by Backdraft007** [comment]
The input widgets support min/max.
You cannont update client attributes from dashboard. Not the normal way. Client attributes are sent from client. Server attributes cannote be read from client.
What do you need is the shared attribute.

**Comment by philippludwig** [comment]
I see. Based on these images from the documentation I tought it was the other way around:

![image](https://github.com/thingsboard/thingsboard/assets/3770792/89212cb1-bf77-4c76-a3d8-deed55689c1e)

![image](https://github.com/thingsboard/thingsboard/assets/3770792/8ae1b2fb-3d2b-4934-8c22-a777624b7151)

***

Also, if you could point me to the location of the min/max setting for the input widgets, I would appreciate it.

**Comment by Backdraft007** [comment]
Input widget "Update shared integer attribute" advanced.
![Screenshot 2023-10-20 085940](https://github.com/thingsboard/thingsboard/assets/8741669/b1cfa64c-e6d2-4e30-bca6-41ce8e1482de)

When you use the multiple attributes widget is in the advanced section oth the data key.
