### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by tecnicos-computrol** [thingsboard/thingsboard#9462]
**Component**
 * Generic

**Description**
Hello everyone, perhaps someone could assist me with this. I need to share a server attribute (specifically, the "active" attribute) from a device with its related asset. I want to ensure that the asset also has an attribute called "active," with its value mirroring that of the related device. It's worth noting that there's already a "Contains" type relationship established from the device to the asset.

**Environment**
* OS: Linux Ubuntu 20.04.5 LTS
* ThingsBoard: v3.4 (ThingsBoard Professional Edition)
* Browser: Google Chrome, Mozilla Firefox, Edge

**Comment by devaskim** [comment]
The solutions depends on where do you want to use the `active` attribute.
In general, the most reliable way is to use rule chains to listen to at least 4 events: Post Telemetry, Post Attributes, Activity Event, Inactivity Event. The latter means `active` became `false`, others means `active` was set to `true`.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
