### ISSUE TITLE
[Question] Create/Update alarms using ThingsBoard REST API seem to be a device creation

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#9463]
**Component**

 * Generic

**Description**
Why when a POST for create a new alarm using REST API the message type of the alarm is ENTITDY_CREATED and not ALARM_CREATED?

![image](https://github.com/thingsboard/thingsboard/assets/7483656/5684ee13-c8e7-46b1-90c7-8f8906021c32)

Tha's my post.

![image](https://github.com/thingsboard/thingsboard/assets/7483656/1e01fab0-15a6-4dcf-9d87-528a461ffa9b)

**Environment**

 * OS:  Windows
 * ThingsBoard: Cloud
 * Browser: MS Edge version 118.0.2088.57

**Comment by ttqteo** [comment]
You can follow this instruction.

1. Filling your host `POST <host>/api/alarm` 
2. Add header token, make sure this token is generated by your host:
```json
{
    "X-Authorization": "Bearer <token>"
}
```
3. Add JSON body, this is listing minimal fields that can create a new alarm in your Thingsboard.
```json
{
  name: <string>,
  type: <string>,
  originator: {
    entityId: <uuid>,
    entityType: <string>
  },
  severity: "CRITICAL",
  status: "ACTIVE_UNACK",
  details: {}
}
```

**Comment by lstarke** [comment]
Using this [endpoint](https://iot.netzsch.com.br/swagger-ui/#/alarm-controller/saveAlarmUsingPOST) ThingsBoard Platform creates an alarm inside device pra it seem that for ThingsBoard is a new device. I'm confuse. Some can explain this ?

![image](https://github.com/thingsboard/thingsboard/assets/7483656/40c0aeac-c2d6-47f3-aa39-b5ed51f2ab91)

![image](https://github.com/thingsboard/thingsboard/assets/7483656/b27e3726-3474-4e92-bb7a-2ba5212a62ec)

**Comment by ViacheslavKlimov** [comment]
Hi @lstarke,
There is indeed an issue when creating alarm using REST API: the message type should be Alarm Created.
And because it is 'Entity Created' and originator type is Device, notification rule incorrectly assumes that 'Device was created'.
We will fix this for the upcoming 3.6.1 release.

**Comment by ShvaykaD** [comment]
Hi @lstarke, a small clarification regarding confusion with types of message:

We don't have such message type as ALARM_CREATED and to send alarm entity creation message to rule engine we use ENTITY_CREATED message type as well as for other entities like device, asset, etc. 
Since we use this message type for a long time we can't change the message type for backward-compatibilty of existing rule chains that handle alarm creations based on ENTITY_CREATED message type. 

@ViacheslavKlimov, however, notification message content needs to be fixed anyway.

**Comment by ViacheslavKlimov** [comment]
You might use a filter script node on 'Entity Created' event with the following TBEL filter script that checks if incoming msg data is alarm:
```
if (msg.id != null && msg.id.entityType != null) {
    return msg.id.entityType == 'ALARM';
}
return false;
```
