### ISSUE TITLE
Error: Cannot resolve symbol 'TransportProtos' when running code for the first time

### ISSUE THREAD

**Issue by avindra99** [thingsboard/thingsboard#9464]
Description:
I encountered an issue when trying to run the code for the first time. The error message I received is as follows:

import org.thingsboard.server.gen.transport.TransportProtos.AttributeValueProto;
Cannot resolve symbol 'TransportProtos'

Steps to Reproduce:

Clone the repository.
Build the project.
Attempt to run the code.

**Comment by avindra99** [comment]
![image](https://github.com/thingsboard/thingsboard/assets/94655548/d537b989-b8d3-4ffa-bb8d-5cadbd3aabf2)

**Comment by ttqteo** [comment]
You need to run `mvn clean install -DskipTests` first. This step aims to install all required packages in project.

**Comment by ttqteo** [comment]
Read detail [Contribution Guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)

**Comment by ViacheslavKlimov** [comment]
If after full install the error persists, this is the issue with the IDE. Open 'Edit Custom Properties...' (or maybe it is called differently) and add the following line:
`idea.max.intellisense.filesize=20000`

**Comment by H0wAway** [comment]
> 如果完全安装后错误仍然存​​在，则这是 IDE 的问题。打开“编辑自定义属性...”（或者可能以不同的方式调用）并添加以下行： `idea.max.intellisense.filesize=20000`

Thanks, it really solved the headache problem

**Comment by Ultrazombie** [comment]
Closed due to inactivity
