### ISSUE TITLE
[Question] how to fetch latest message key in day ago

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9465]
Hello
How can I retrieve the last message key saved the previous day before 12:00 PM?
I used the originator telemetry node, but I don't know how to set the start interval and end interval to retrieve exactly the last message that was saved before 12:00 PM.

**Comment by evanderbird** [comment]
in this case, that 12:00pm  is END Interval
and start interval would be how many hour before that, anytime you want

for example 6am, 2023/10/20  
you just convert it to unix_timestamp ==> 1697756400000  
use unix_timestamp for START or END Interval

**Comment by Ultrazombie** [comment]
Closed due to inactivity
