### ISSUE TITLE
[Question] OpenStreetMap widget lags when tracking 1000 devices

### ISSUE THREAD

**Issue by VictorLiang-5giotlead** [thingsboard/thingsboard#9470]
**Component**

 * UI

**Description**
We would like to track about 1000 devices with attributes every 10 seconds through MQTT using a map widget. However, we have noticed that without using cluster, when all 1000 points appear on the map, it significantly impacts the client's (browser) performance, making it difficult to drag the map.
We tried to track the source code and found that if comment out `marker.updateMarkerIcon(settings);` in the method `updateMarker` [here](https://github.com/thingsboard/thingsboard/blob/4907283b6ed57702536cc938746d4dfc6f63e4a9/ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts#L978C29-L978C29), it can improve the performance.
We hide label and disable color function, our marker image function settings include only a fixed SVG image like - 
```
return {
    url: images[0],
    size: 10
}
```
here's a short demo:
* In order to make this issue more apparent, I change it to send data every second.
* before changes
https://github.com/thingsboard/thingsboard/assets/97156419/bd6530d7-e8c7-448f-a2d4-8b64cb6eb308
* after changes
https://github.com/thingsboard/thingsboard/assets/97156419/fd43d439-9062-45b0-a08f-58139700af80

I don't think this case needs to update the icon every time, so I'm not sure what the root cause is that really makes it lag.
Does anyone have any recommendations for improving the performance without removing the update icon feature for this scenario?

**Environment**

 * OS:  Linux Debian 11
 * ThingsBoard: 3.6.0 CE with Kafka
 * Browser: Microsoft Edge 118.0.2088.57

**Comment by mykhailokornieiev** [comment]
Hi. As far as see, you've been provided with an answer on support portal. In this case, I close this ticket
