### ISSUE TITLE
[Bug] Export data from timeseries widget (e.g. line chart) with an attribute as threshold does not work

### ISSUE THREAD

**Issue by JuliusHarald** [thingsboard/thingsboard#9471]
**Describe the bug**
* We have a Line Chart with an attribute as a threshold. Data Export is enabled, but it does not work. In the browsers console there is a "TypeError: J is undefinded" message. Without the threshold it is possible to export the data.

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Linux
* Browser: Firefox
* Version [e.g. 22]

**To Reproduce**
1. create a dashboard with a timeseries widget, e.g. line chart
2. add device to the widget and choose an attribute in the "Latest data keys" section
3. enable data export
4. save and try to export the data from the widget
5. See error (in browser console)

**Expected behavior**
* The data should be exported

**Screenshots**
![Screenshot_2023-10-23_13-12-25](https://github.com/thingsboard/thingsboard/assets/31532205/c5d2c46c-99da-4d8c-bb8e-338186dab321)

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
