### ISSUE TITLE
create Custom rule chain to detect same value in interval time

### ISSUE THREAD

**Issue by yusmi25** [thingsboard/thingsboard#9478]
**Component**
 * Rule Engine

**Description**
any solution to create alarm with node when the value data always same in range interval time ? in thingsboard PE I can use analytics node aggregate stream to solve this problem
thanks.

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.6.0 CE with postgres
 * Browser: firefox
![image](https://github.com/thingsboard/thingsboard/assets/60766202/dd5a0bf2-701e-40ad-be34-f5a041976b73)

**Comment by devaskim** [comment]
I think 2 nodes would be enough: Originator Telemetry + Script (of type Filter)

**Comment by yusmi25** [comment]
> I think 2 nodes would be enough: Originator Telemetry + Script (of type Filter)

what is the output of telemetry originator

**Comment by devaskim** [comment]
array of object with timestamp and value fields

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
