### ISSUE TITLE
Navigate to new dashboard state

### ISSUE THREAD

**Issue by yjfoo** [thingsboard/thingsboard#9488]
[Description]
In my entities table widget, I've setup two "Site". 
Site A and Site B have different sensors deployed.
Site A has sensor A and B deployed.
Site B has sensor A, B and C deployed.
I have setup dashboard state to transition into new state (selected site) upon "on row click".
Under the dashboard state, I've setup the respective widgets to show the visualization.
However "on row click" on site A, it continues to show the widget for sensor C but it's empty (since it's not deployed and therefore shouldn't have data). 
The dashboard state seem to require the different ${entityName} in dashboard state to have the same widgets?
I might have missed something but is it possible to have different widgets for my situation since they are different sites and possibly have different sensors deployed?

ThingsBoard: CE 3.4.4

**Comment by devaskim** [comment]
Use custom action and set there dashboard state name dynamically based on sensor type or some other criteria. So each state will have different widgets.
```
const params = {
    entityId: entityId,
    entityName: entityName,
    entityLabel: entityLabel
};
const state = 'name_of_state_based_on_something';
widgetContext.stateController.openState(state, params);
```

**Comment by yjfoo** [comment]
Hi, Thanks this is working perfectly
