### ISSUE TITLE
How to navigate to a dashboard state using an html tag id

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/thingsboard#9490]
Does anyone know? I'm creating a widget that has to navigate to different dashboards but I don't want to use href to reload the page, but to change the state

**Comment by mykhailokornieiev** [comment]
Hi
You can get familiar with the following documentation https://thingsboard.io/docs/user-guide/contribution/widgets-development/#state-controller

**Comment by Ultrazombie** [comment]
Closed due to inactive
