### ISSUE TITLE
Request method 'GET' not supported

### ISSUE THREAD

**Issue by turnede0** [thingsboard/thingsboard#9497]
I tried to self-host thingsboard by docker.then, i have post call.
```
curl -v -X POST http://XXXX.XXXX.com/api/v1/NYAubhLAhdrqqwYCB3LF/telemetry --header Content-Type:application/json --data "{temperature:25}"
```
However, i get the response
```
{
    "status": 405,
    "message": "Request method 'GET' not supported",
    "errorCode": 31,
    "timestamp": "2023-10-25T15:56:38.649+00:00"
}
```
I have no idea what happening.

**Comment by turnede0** [comment]
finally, i figure out that is port problem after checking swagger
it is using port 443
it success if i change the curl "https://xxxxx.xxxx.semproject.us:443/api/v1/qR9f4asiNzGQOL92w506/telemetry".

However, Thingsboard recommand   

```

**Comment by turnede0** [comment]
curl -v -X POST http://xxxxx.xxxxxx.com:8080/api/v1/qR9f4asiNzGQOL92w506/telemetry --header Content-Type:application/json --data "{temperature:25}"
````

Can i change the recommandation in ui? I would like to change change it from 8080 to 443

**Comment by mykhailokornieiev** [comment]
Hi
Such problem may occur due to the following factors: 
1. Settings of the Base URL (Sysadmin User -> System Settings -> General ) 
2. Settings of load balancer. ThingsBoard requires the X-Forwarded-Proto header.

**Comment by Ultrazombie** [comment]
Closed due to inactive
