### ISSUE TITLE
[Bug] Notifications button doesn't appear on Fullscreen

### ISSUE THREAD

**Issue by gnosticChemist** [thingsboard/thingsboard#9498]
**Bug Description**
Users notifications button doesn't appear when "Always Fullscreen" Dashboards are selected. Notifications can still be acessed by checking the Account Profile

**Server Environment**

* Google Cloud
  * ThingsBoard PE 3.6

**Your Client Environment**

Any environment

**To Reproduce**
1. Choose an User
2. Set a Default Dashboard with 'Always Fullscreen' marked
3. Log as the User

**Expected behavior**
Notifications button showing up on account's info left.

**Screenshots**

![missing](https://github.com/thingsboard/thingsboard/assets/31459018/1ec1311a-1488-4606-b9d8-5de56923aa3e)
![missing2](https://github.com/thingsboard/thingsboard/assets/31459018/4005095c-8a9b-4989-bb3a-dbe9a5b847a4)

**Comment by chowardcode** [comment]
I'd also like to know a solution.

**Comment by ssakharova** [comment]
Hello @gnosticChemist, @chowardcode,

The notification bell icon doesn’t appear when the ‘Always fullscreen’ checkbox is enabled. Our developers already know about this issue, but there’s no specific timeframe for when they could correct it.

However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
