### ISSUE TITLE
[Question] Access Forbidden You haven't access rights to this location!

### ISSUE THREAD

**Issue by junleus** [thingsboard/thingsboard#9518]
**Description**
when add a map widgets,got  Access Forbidden You haven't access rights to this location!
so should I use PE version with Advanced Role-Based Access Control ?

<img width="769" alt="image" src="https://github.com/thingsboard/thingsboard/assets/37057723/d7bcb9d5-b139-4c96-b4f5-6d9be1fc3a46">

**Comment by IoTThinks** [comment]
I have this issue too after upgrading ThingsBoard 3.4.1 to 3.6.2.

Hit this error when adding widgets to existing dashboarr and saving existing dashboards.

New dashboards seems no issue.

**Comment by IoTThinks** [comment]
For my case, it was the firewall wrongly blocks /api/dashboard due to Body Size restriction.
Solved for my case.

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
