### ISSUE TITLE
url for public dashboard with public device

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#952]
Is it possible to display a public dashboard getting the data from a public device, without having to login ? (the thingsboard server is started locally on my PC).  What would be the direct URL to the dashboard?

What about the combination public dashboard and private device, can the user login be avoided in this case?

**Comment by botsbuzz** [comment]
+1

**Comment by mp-loki** [comment]
On the Dashboards screen, click "Make dashboard public". You can later recover the public dashboard link by clicking edit icon.

**Comment by RondoRonaldo** [comment]
To show the data from a device on a public dashboard it is required to change the device to the public one. 
In case using ThingsBoard PE, you need to make entity group public one and then all of the dashboards in it will become public and will have the corresponding buttons to get public links to them. 
![image](https://user-images.githubusercontent.com/43723966/85863395-c5067400-b7cb-11ea-923e-b1cebb86f633.png)
![image](https://user-images.githubusercontent.com/43723966/85863347-b455fe00-b7cb-11ea-9732-e4b859a499d4.png)

**Comment by vcmorini** [comment]
Can the URL be returned via REST/HTTP?

**Comment by vcmorini** [comment]
The public dashboard URL can also be composed, instead of by clicks:

In Python3:
`dashboard_url = f"{url}/dashboard/{dashboard_id}?publicId={public_client_id}"
`
dashboard_id and public_client_id variables can be fetched by REST API. 
You can check Swagger for that: https://demo.thingsboard.io/swagger-ui.html#/
