### ISSUE TITLE
how to use restapi ?

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#953]
I installed thingsboard in my system and i need to use restapi to connect to another server . 
How can i use RestAPI to Connect to another server from thingsboard ?

**Comment by RondoRonaldo** [comment]
There is a "rest API call" node in a rule chain so it is possible to send requests to other services and get responses from them. 
You may refer to ThingsBoard documentation regarding this node: 
https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node

Also, there is documentation regarding ThingsBoard REST API: 
https://thingsboard.io/docs/reference/rest-api/
