### ISSUE TITLE
Dynamic dropdown (select) options in Multiple Attributes widget

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#9531]
In Update Multiple Attributes widget, I can set input as dropdown (select). However, the selection options are fixed and need to be pre-defined. If I want to make the options in dropdown list as dynamic values, e.g. all the device IDs, how can I do it?

**Comment by liotys** [comment]
Hi @sunyong-mwi ,
You should define a datasource with your list of values:
![image](https://github.com/thingsboard/thingsboard/assets/103430329/46a81c02-b88e-447e-8d51-109e6ac51092)
Then in the getvalue function of the field you want to customize (called ChoixFlux in my exemple) use some code like:

```
for (var i = 0; i < ctx.data.length; i++) {
    if (ctx.data[i].dataKey.name == 'ChoixFlux') {
        break;
    }
}
let source = ctx.data[i].dataKey;
let valeursFlux=[];
for (var j = 0; j < ctx.datasources.length; j++) {
    if (ctx.datasources[j].aliasName=='Liste des Flux') {
        valeursFlux.push(ctx.datasources[j].name);
            }
    
}
valeursFlux.sort();
let valeursFluxAll=['Tous sélectionner'];
valeursFluxAll.push(...valeursFlux);
let listeChoix=[];
for (var k = 0; k < valeursFluxAll.length; k++) {
        listeChoix.push({value:valeursFluxAll[k],label:valeursFluxAll[k]});
   
}
source.settings.selectOptions=listeChoix;
return value;
```

**Comment by sunyong-mwi** [comment]
Hi @liotys,
The method works. Thanks for the brilliant idea.

**Comment by Faheem-Punnasseri** [comment]
> Hi @liotys, The method works. Thanks for the brilliant idea.

Could you please share the snippet and code in detail? I'm currently attempting to make the "Select" type of Update Multiple Attribute dynamic as well.

**Comment by sunyong-mwi** [comment]
@Faheem-Punnasseri , pls see my code below.


```
// console.log(ctx);

var dataKeyName = 'selectedDev1';

// get all the sensor names
var values = [];
var labels = [];
for (var j = 0; j < ctx.datasources.length; j++) {
	// check data source with alias 'tempSensor'
	// note: the alias 'tempSensor' is defined and added as hidden data source
    if (ctx.datasources[j].aliasName == 'tempSensor') {
        values.push(ctx.datasources[j].entityName);
        labels.push(ctx.datasources[j].entityName + ' (' + ctx.datasources[j].entityLabel + ')');
    }
}

// add first item
var valuesAll = ['NA'];
valuesAll.push(...values);

var labelsAll = ['Not Selected'];
labelsAll.push(...labels);

// create selection list
var choiceList = [];
for (var k = 0; k < labelsAll.length; k++) {
    choiceList.push({
		value: valuesAll[k], 
		label: labelsAll[k]});
   
}

// find the data which is the input
for (var i = 0; i < ctx.data.length; i++) {
    if (ctx.data[i].dataKey.name == dataKeyName) {
        break;
    }
}
var source = ctx.data[i].dataKey;

// set the choice list to the input
source.settings.selectOptions = choiceList;

return value;
```

**Comment by Faheem-Punnasseri** [comment]
@sunyong-mwi

Thank you. That was really helpful. Can we generate a value in another "Select" input field based on the value selected in the current 'Select' input for updating multiple attributes? Do you have any ideas on that?

**Comment by sunyong-mwi** [comment]
@Faheem-Punnasseri , in my example, the "selectedDev1" is current user's attribute. Once you select the value, the attribute will be updated. In another Select input, you can retrieve the current user's attribute using attribute service and use it.

**Comment by Faheem-Punnasseri** [comment]
@sunyong-mwi Thanks for the clarification, and thank you for your support.

**Comment by PhilipRai** [comment]
Im trying to wrap my head around the above code...

I can only get it to select 'No Selection'
