### ISSUE TITLE
[Bug] Widget Error after  v3.6.0 (Sep 21, 2023)

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#9543]
**Describe the bug**
After last release v3.6.0 (Sep 21, 2023) I'm getting errors on widget when openning dashboard.

**Your Server Environment**

cloud.thingsboard.io

**Your Client Environment**

* OS: [Windows]
* Browser [MS Edge]
* Version [118.0.2088.69]

**Your Device**

* Connectivity
  * HTTP
   
* Internal device project

**To Reproduce**
1. Just openning any created dashboard

**Expected behavior**
All widget used in deashboard must be rendered normally

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/7483656/a1680390-87bc-442d-a8b7-dbfa8ebc8477)

**Comment by Backdraft007** [comment]
Do you cleared your browser cache?

**Comment by lstarke** [comment]
> Do you cleared your browser cache?

Worked. Thank you @Backdraft007.
