### ISSUE TITLE
Custom Menu bar development in thingsboard 

### ISSUE THREAD

**Issue by cognetagreen** [thingsboard/thingsboard#9547]
In Thingsboard, we are targeting to develop advance level dashboard designs using HTML code. Can we create a side overlay menu bar of our own ? At present we can only see Thingsboard default menu option.

**Comment by devaskim** [comment]
No - in CE version
Yes (partially) - PE version (see custom menu feature)

**Comment by cognetagreen** [comment]
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sidenav

Can we achieve this kind of menu ?

**Comment by devaskim** [comment]
With custom widgets you can implement what ever you want, but it would be better to use dashboard in fullscreen mode to hide origin TB menu.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
