### ISSUE TITLE
how to add user localhost?

### ISSUE THREAD

**Issue by amrithmmh** [thingsboard/thingsboard#955]
I need to add users in my local lan thingsboard how do i do that

**Comment by amrithmmh** [comment]
update: sorry for asking this dumb question I have found out that postgresql is required for the database however i made a new user "userone" using `sudo adduser sammy`

**Comment by Karabiy** [comment]
for the postgres? 
after sudo su - postgres
psql 
you need to go with 
\password 
so that you can go with those for the postgres user, in case of those
