### ISSUE TITLE
Thingsboard Dashboard- Display telemetry from multiple devices under same device group

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#9557]
I am trying to display telemetry data from multiple devices under same device group in a single thingsboard dashboard widget. I created  a device group alias for it as per the screenshot.
![image](https://github.com/thingsboard/thingsboard/assets/49026279/9d8cfaa1-ad57-42f8-8955-cb37f3e8574b)
But, when i am configuring the widget, I am only able to display data from a single device among the multiple devices of the device group. 
Please let me know, if this configuration is correct. I just want to club the data from multiple devices under a device group in a single widget on the thingsboard dashboard.
@ashaforost @ashvayka @devaskim

**Comment by devaskim** [comment]
Hi @mubashirp 
Honestly, I am not a TB, however what widget are you using? Alias is correct.

**Comment by mubashirp** [comment]
it is HTML value card, the issue is similar with other type of widgets too.
![image](https://github.com/thingsboard/thingsboard/assets/49026279/70d56f2d-1242-412f-83bf-f60092fc7092)
here tag a is from one device, and tag c from another device, but both under same device group. But only tag a is being displayed.
![image](https://github.com/thingsboard/thingsboard/assets/49026279/3ff9bf21-6df2-49e7-9cf7-b21d6ba1532c)

**Comment by devaskim** [comment]
HTML value card supports only single entity. 
In general, you can see its source code in Resources->Widget Library - HTML value card widget

**Comment by Ultrazombie** [comment]
Closed due to inactivity
