### ISSUE TITLE
[Question] DEVICE rate limit reached!

### ISSUE THREAD

**Issue by ohack38** [thingsboard/thingsboard#9559]
**Component**

 * Generic

**Description**
We are currently using the cloud prototype subscription. I tried to add a new integration for our raspberry pi. We are sending http requests from the rpi but getting a response with status 500 with error message "DEVICE rate limit reached". We have only used 64 of 100 allowed devices. What could be the issue?

**Environment**
 * OS:  name and version
 * ThingsBoard: Cloud prototype
 * Browser: name and version

**Comment by ashaforost** [comment]
Try searching for the missing devices in the customer entities. They are definitely somewhere, or the error wouldn't pop up.
You may get the list of all devices using the [Get Tenant Devices request](https://thingsboard.cloud/swagger-ui/#/device-controller/getTenantDevicesUsingGET)

**Comment by ViacheslavKlimov** [comment]
Rate limit is not entities limit, it's a limit for amount of messages from device within a period of time.
Probably your device is sending messages too frequently.

**Comment by ohack38** [comment]
The problem seems to have been that our devices reached the telemetry transport data point rate limit - 20/sec. Since our devices send up to 15 data points per message, two messages within a second caused the error.

**Comment by barrybingo** [comment]
Just started trying out the platform and, like ohack38, we are also sending multiple telemetry in one payload so the rate limit is easily exceeded.

**Comment by ohack38** [comment]
You'll need to split up your messages into smaller chunks and add a timeout between sending messages.

**Comment by ezeroldan24** [comment]
Hi how are you? I'm having the same problem with the message limit and my devices getting disconnected. Can this be fixed from the chain of rules? Any recommendations?
