### ISSUE TITLE
Release 2.1.0 Docker Image not available on docker-hub

### ISSUE THREAD

**Issue by nitinware** [thingsboard/thingsboard#956]
The docker images of Thingsboard latest release 2.1.0, is not available on dockerhub.
Can you please upload 2.1.0 on docker-hub, so that we can use that image.

**Comment by volodymyr-babak** [comment]
@nitinware thanks for mentioned this. Fixed

**Comment by nitinware** [comment]
@volodymyr-babak - Thanks for the quick fix, much appreciated.
