### ISSUE TITLE
[Question] Alias as Type in Relation Query

### ISSUE THREAD

**Issue by ADV-LUT** [thingsboard/thingsboard#9561]
**Component**

 * UI

**Description**
I am encountering an issue when trying to add an additional entity filter on a dashboard. Specifically, under the Filter type - Relations query in the Root entity section, I am missing the option to use a different alias.

![Screenshot 2023-11-03 140755](https://github.com/thingsboard/thingsboard/assets/43776990/ed5bf569-6b21-4fbc-98ef-8ec5af0338aa)

**Environment**

 * OS:  name and version
 * ThingsBoard: 3.5.1
 * Browser: firefox

Here's what I am dealing with: I have a dashboard where a device entity is passed when navigating to another dashboard. I was able to identify the overarching Edge device using an entity filter. Now, I aim to list all associated devices based on this ID, but unfortunately, I cannot seem to pass this ID or find an option to do so. Is there a workaround or a setting that I am missing that would allow me to use a different alias in the Relations query?

Any guidance or assistance would be greatly appreciated!

**Comment by ashaforost** [comment]
Try to enable the 'use dashboard state entity as root' option in your relation query entity alias. It will search for the entities related to the one you set when navigating to another dashboard.
