### ISSUE TITLE
[Question] I am unable to set up Trendz Analytics

### ISSUE THREAD

**Issue by AIOTEL-sanjanaa** [thingsboard/thingsboard#9562]
**Component**
Trendz Analytics

 * Installation
 I am installing the trendz analytics using docker(ubuntu).

**Description**
I had set up thingsboard on docker and trendz in docker as well. Am facing issue to set up trendz analytics in my localhost. I had attached the logs bellow. 
[trendz.log](https://github.com/thingsboard/thingsboard/files/13250541/trendz.log)

**Environment**

 * OS:  Ubuntu
 * ThingsBoard: 3.6
 * Browser: Mozilla

**Comment by vparomskiy** [comment]
Accroding to the log file Trendz service was already installed. So it is not a fresh installation.
Can you describe what was the previous version and how you run an upgrade?

**Comment by Ultrazombie** [comment]
@AIOTEL-sanjanaa 
Please reopen the issue if the problem still exists. We will close it for now, as you have not responded for a long time.

Thanks.
