### ISSUE TITLE
[Question] Docker Thingsboard Update Angular 15

### ISSUE THREAD

**Issue by Zac1209** [thingsboard/thingsboard#9563]
**Component**

 * Installation

**Description**
Hello, I am running ThingsBoard CE in a Linux Docker environment. I updated from 3.4.4 to 3.5. This is the update where ThingsBoard switched to Angular 15 and there's a note to migrate. The problem is that the instruction are for direct installation on Windows or Linux, they are not applicable to Docker.

How would I go to migrate my UI? Obviously, my script rule node UI are now broken.

Thank you

**Comment by ashaforost** [comment]
Hi @Zac1209 

The migration to Angular 15 means that if you have some custom rule nodes/widgets/etc, you need to rebuild them using Angular 15.  If the mentioned 'script rule node' is a custom one, please rebuild it and upload new .jar file to the thingsboard extensions volume. If this rule node is the default one and you're seeing a broken UI after the upgrade, try clearing your browser's cache; it should restore the UI in this case.
