### ISSUE TITLE
Need help on create widget Setting Schema

### ISSUE THREAD

**Issue by mixo3891** [thingsboard/thingsboard#9564]
I can not create Widget Setting Schema  for lattes value widget. I am trying create schema but on widget setting have not anything input.
my schema is:
{
"schema":{
        "type": "object",
        "title": "Settings",
        "properties": {
            "set_name": {
                "title": "true name",
                "type": "string",
                "default": "SET"
            },
            "reset_name": {
                "title": "false name",
                "type": "string",
                "default": "RST"
            }
        }
    },
    "form":[
        "set_name","reset_name"
            ]
}
there should be inputs "true name" and "false name" input box
![image](https://github.com/thingsboard/thingsboard/assets/99183101/7f4c6377-c3ff-43a2-b961-52d5d0d2738f)
![image](https://github.com/thingsboard/thingsboard/assets/99183101/a6bc40be-a29a-41cb-abb4-f77e8ce6e710)

**Comment by mixo3891** [comment]
can help anyone?

**Comment by devaskim** [comment]
@mixo3891 After upgrade to 3.6, I found custom settings in the `Appearance` tab.

**Comment by mixo3891** [comment]
I checked it but no settings,
can you give me some setting schema example and form?

**Comment by devaskim** [comment]
```
{
    "schema": {
        "type": "object",
        "title": "",
        "properties": {
            "sensorTypes": {
                "type": "array",
                "title": "Sensort types",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "title": "Title",
                            "type": "string"
                        },
                        "state": {
                            "title": "ID (use as dashboard state)",
                            "type": "string"
                        },
                        "icon": {
                            "title": "Material Icon name",
                            "type": "string"
                        }
                    }
                }
            }
        },
        "form": [{
            "key": "sensorTypes",
            "type": "array"
        }],
        "required": [
            "sensorTypes"
        ]
    }
}
```

**Comment by mixo3891** [comment]
still same
no changes

**Comment by mixo3891** [comment]
I think I found problem, this widget is imported from json from previous version thingsboard, I creat new widget and copy all code, and setting was appear.
