### ISSUE TITLE
[Question] Timeseries API

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#9575]
Hello! I would like to create my own report. I need to get time series with aggregation.
In RestApi `/api/plugins/telemetry/{entityType}/{entityId}/values/timeseries{?agg,endTs,interval,keys,limit,orderBy,startTs,useStrictDataTypes}` has the `interval` parameter.
If we want the aggregation interval range to be one day, we will set it to `86400000`. How to set this option to one month? The months are different.
Thanks.

**Comment by garysmi2** [comment]
... and just to jump on board - the endpoint for retrieving timeseries data as mentioned in the above post is causing me great confusion regarding the aggregation functions. For example I wish to fetch the data for a whole day starting at 00:00h to 23:59h  on the same dat using the AVG aggregation and an interval  of 3600000. I would expect this to return twelve values aligned on the hour, what I get in return though are hourly averages aligned on the half hour worse still the data returned is timestamped as starting at 23:30h on the previous day - before the start timestamp that I am using - this doesn't seem correct or else I am missing something here in regards to aggregation and intervals?

**Comment by mykhailokornieiev** [comment]
Hi. There is no such option in Thingsboard Rest API. Such functionality is only available on the UI side as a front-end feature, and it takes different interval parameters (ts) depending on which month is it (28, 30 or 31 days). For your case, it would be necessary to set up this interval for each month individually

**Comment by psxbox** [comment]
Time | Активная энергия | Рективная энергия
-- | -- | --
08/11/2023 17:30:00 | 0,000 | 0,000
08/11/2023 18:30:00 | 0,049 | 0,009
08/11/2023 19:30:00 | 0,047 | 0,009
08/11/2023 20:30:00 | 0,036 | 0,006
08/11/2023 21:30:00 | 0,032 | 0,005
08/11/2023 22:30:00 | 0,014 | 0,002
08/11/2023 23:30:00 | 0,007 | 0,000
...
09/11/2023 17:30:00 | 0,054 | 0,010

Why, when aggregating data by interval, is the time displayed in the middle of each interval?

**Comment by mykhailokornieiev** [comment]
In fact, this is simply by design of the aggregation function. For the day, it will be noon, for the hour - hh:30. etc.
But the actual calculation for the 17:30 (for example) has timeframe between 17:00 and 18:00, as you mentioned before
So, it's just by design of Thingsboard.

**Comment by Ultrazombie** [comment]
Closed due to inactive
