### ISSUE TITLE
Develop new Database Scheme

### ISSUE THREAD

**Issue by arture1991** [thingsboard/thingsboard#958]
Hello there,

I was wondering about implementing a new database option for Thingsboard. What do you guys think? How much of an expense would that be? Is it even worth the hassle? 

Best regards 

Arthur

**Comment by mp-loki** [comment]
You can try with DynamoDB if you want :)

**Comment by khuynhthanhchiluyen** [comment]
can use make databases as plugins so everyone can integrate theirs favorite databases ?
