### ISSUE TITLE
[Question] Restoring postgres backup in a new thingsboard installation

### ISSUE THREAD

**Issue by nomanuser** [thingsboard/thingsboard#9580]
Hi,
I'm trying to restore a thingsboard database  dump  in a new installation of thingsboard but when i start thingsboard i have this error:
User with email 'sysadmin@thingsboard.org'  already present in database!

**Comment by devaskim** [comment]
Just drop and create `thingsboard` database with `psql` or GUI Postgres client.

**Comment by Ultrazombie** [comment]
@nomanuser 
Please confirm that the problem is solved, if not, please post here the error that occurs.
Thanks.

**Comment by nomanuser** [comment]
> Just drop and create `thingsboard` database with `psql` or GUI Postgres client. Then restore backup again.

Thanks, solved.
