### ISSUE TITLE
[Question] Is there a way to customize the Angular Material density?

### ISSUE THREAD

**Issue by danisal** [thingsboard/thingsboard#9588]
**Component**
 * UI

**Description**
There is a place where I would like to have a smaller input, and I saw that in angular material, there is a way to accomplish that by using the [density](https://material.angular.io/guide/theming#customizing-density) property. Can we use that on the widgets?

**Environment**

 * OS:  any
 * ThingsBoard: 3.6 PE
 * Browser: any

**Comment by epalchenko** [comment]
Hello,
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket with detailed steps to reproduce if this problem still exists.

**Comment by danisal** [comment]
Just for reference, I manage to accomplish this by doing the following:

1. at the top of you `.scss` file use the `use` directive to import angular material, like:
```scss
// my-component.scss
@use '@angular/material' as mat;
...
```
3. the you can use a class to add the density you want, like:
```scss
...
.dense-minimum {
  @include mat.all-component-densities(minimum);
}

.dense-2 {
  @include mat.all-component-densities(2);
}
...
```
