### ISSUE TITLE
Help with OPC-UA Connector with IoT Gateway

### ISSUE THREAD

**Issue by insurf** [thingsboard/thingsboard#9594]
Hallo,
I am using a ThingsBoard PE instance and need assistance with the integration of an OPC-UA interface. Specifically, I would like to monitor the values from a Siemens S7 1500 with ThingsBoard.

I have successfully connected the ThingsBoard PE to the IoT Gateway and the Gateway to the S7 via OPC UA. 
Using an OPC Client, I can see the paths to the individual nodes. (See screenshot "Path")
How do I have to configure the opc.json file to obtain the nodes status? For Example node in "pic2"

This would be the config (opcua.json) I am using on the Gateway:
{
  "server": {
    "name": "OPC-UA Default Server",
    "url": "opc.tcp://192.168.0.1:4840",
    "timeoutInMillis": 5000,
    "scanPeriodInMillis": 5000,
    "disableSubscriptions": false,
    "subCheckPeriodInMillis": 100,
    "showMap": false,
    "security": "Basic128Rsa15",
    "identity": {
      "type": "anonymous"
    },
    "mapping": [
      {
        "devices": [
          {
            "deviceNodePattern": "Root\\.Objects\\.001=TMP+SS-100KF1_PLC\\.Outputs", 
            "deviceNamePattern": "001=TMP+SS-100KF1_PLC",
            "attributes": []
            "timeseries": [
              {
                "key": "Dosierung Fe3Cl", 
                "path": "$.['ns=3;s=Dosierung Fe3Cl']"
              }
            ]
          }
        ]
      }
    ]
  }
}

The log shows:
opcua_connector - __init__ - 64 - deviceNodePattern in mapping: {"devices": [{"deviceNodePattern": "Root\\.Objects\\.001=TMP+SS-100KF1_PLC", "deviceNamePattern": "001=TMP+SS-100KF1_PLC", "attributes": [], "timeseries": [{"key": "Dosierung Fe3Cl", "path": "$.['ns=3;s=Dosierung Fe3Cl']"}]}]} - not found, add property deviceNodePattern to processing this mapping"

Would kindly ask for your support here.
Thank you!

 * OS:  Ubuntu 20.04
 * ThingsBoard: ThingsBoard PE
 * 
![pic2](https://github.com/thingsboard/thingsboard/assets/144221111/f9daa6c6-99a0-406c-ab2c-63fd3139c11f)
![Path](https://github.com/thingsboard/thingsboard/assets/144221111/b9c2041b-649c-4550-b425-e293c4529169)

**Comment by devaskim** [comment]
Use [this issue tracker](https://github.com/thingsboard/thingsboard-gateway/issues) for gateway related questions.

**Comment by insurf** [comment]
Ok, will do.
Thank you!

**Comment by Ultrazombie** [comment]
@insurf 
Devaskim is right, and you need to use a different project for gateway questions. 
Thanks.
