### ISSUE TITLE
[Question] Minimal miscroservices deployment

### ISSUE THREAD

**Issue by pg-goose** [thingsboard/thingsboard#9597]
**Component**
- Installation

**Description**
I would like to know if the suggested miscroservices installation found on /docker/README.md is as minimal as it gets. I've been checking the services and I see: `tb-rule-engine2` does it means having two rule engines? Do I realy need 2? (same for the other services with multiple instances)

Or for example, I wont make HTTP calls from my devices nor RPC calls, we'll just stick to MQTT.
I can't figure out if some of these services can be removed without affecting other components but seeing the architecture:

![image](https://github.com/thingsboard/thingsboard/assets/75203757/3abec944-4b3a-4557-9ad3-0dfbaa738ed8)

I imagined that tb-http-transport can be safely removed for example.
Thanks!

**Environment**
 * ThingsBoard: Comunity - latest

**Comment by devaskim** [comment]
You could only that services what you need for your case. 
Service duplication is to show how TB can scale in microservice mode. If you don't need 2 rule engine or some other services, maybe you don't need microservice mode (deployment) at all.
