### ISSUE TITLE
autostart thingsboard on boot in raspbian (rpi 3b)

### ISSUE THREAD

**Issue by amrithmmh** [thingsboard/thingsboard#960]
i have used a bash script
```
#/bin/bash 
sudo service thingsboard start
```
and made it executable
and updated rc.d using `sudo update-rc.d superscript defaults`
but the server does not start at boot

how to make it start at boot

**Comment by cristianhumelnicu** [comment]
@amrithmmh 

sudo systemctl enabe thingsboard

That should make thingsboard start after each reboot...

**Comment by cristianhumelnicu** [comment]
@amrithmmh 

There is not solution ... is all about RPI3 hardware resources . If u need speed up deploy TB on other hardware 
H

**Comment by SergMeleshko** [comment]
Hello @amrithmmh 
Is the issue with performance is still relevant?
