### ISSUE TITLE
[Question] Custom action to update and navigate to a dashboard state when cell button action

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9602]
**Component**

 * Generic

**Description**
I wanted to update a dashboard state and then navigate to another one using a cell button action. Since I only can choose between of these two functions, I was thinking about using a custom action to implement this functionality. Which code should I use to do it? Because I have seen [this ThingsBoard video](https://www.youtube.com/watch?v=mqWEGs1Z2BQ) and some past issues but it is not working for me. How could I do it?

**Environment**

 * ThingsBoard: 3.6

**Comment by devaskim** [comment]
Call `widgetContext.stateController.openState()` in your custom action to open new dashboard state

**Comment by jortega11** [comment]
I discovered that what causing the issue was not the custom action so I managed to do it in another way without the need to use it.
Thank you!
