### ISSUE TITLE
js-executors not connecting to kafka and system disrupts for sometime after kafka recreation

### ISSUE THREAD

**Issue by aminzakizebarjad** [thingsboard/thingsboard#9614]
**Describe the bug**
Hello,
I am deploying version 3.3.4.1 on my server. We have been using community edition for about 6 months and we have confronted many issues mainly from Kafka [ as looking through the logs].
Once I committed `bash dokcer-stop-services.sh` and deployed new configurations to the kafka.env file as the logs where using lots of our  disk and it was on the info level. So I added below configs to the kafka.env file
`LOG4J_LOGGER_ORG_APACHE_ZOOKEEPER=ERROR  `

`LOG4J_LOGGER_KAFKA=ERROR  `

`LOG4J_LOGGER_ORG_APACHE_KAFKA=ERROR ` 

then I committed ` bash docker-start-services.sh`

I saw that the Kafka was being recreated via docker compose as I changed the ENV of the Kafka container. This is where the issues begin.

I saw that the js-executors where getting restarted for all a day showing below message in its logs:
`
 [kafkajs] ERROR: Response Metadata(key: 3, version: 6): {"timestamp":"2023-11-12T06:14:50.372Z","logger":"kafkajs","broker":"kafka:9092","clientId":"kafkajs","error":"There is no listener on the leader broker that matches the listener on which metadata request was processed","correlationId":1,"size":22906}
`

`
Failed to start ThingsBoard JavaScript Executor Microservice: There is no listener on the leader broker that matches the listener on which metadata request was processed
`

`
[kafkaTemplate] ERROR: KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed
`
the mqtt-transport, http-transport, tb-core and tb-rule-engine where showing some logs showing that there where no connection available to Kafka.

I got into the Kafka by `docker exec` and executed ` kafka-topic.sh --describe` as the image below shows the result:    

![msg-840300517-38624](https://github.com/thingsboard/thingsboard/assets/43999266/5087583a-e0a4-4deb-b0bb-414a1f72b350)

showing that there is no leader to any of the topics.
I found out that the reason is that the Kafka id to which the containers are connected are having id: **1001** and the new kafka image is being created has the id **1007**

so I added below configs to the kafka.env and the issue was solved:  

`
KAFKA_BROKER_ID=1001
`
`
KAFKA_RESERVED_BROKER_MAX_ID=1000000000
`

Now after one month I did some other changes for log retention in kafka.env so the container was being recreated. tb-core, mqtt-transport and  http-transport  have no issues but still js-executors are restarting with the same log which says there is no kafka to connect.  every thing is functioning now in web-ui and in our browser and telemetries and attributes and RPCs are OK, But in background js-executors are restarting. 
is there anything to do? 

### another issue :
after kafka recreation for some time the system functions well but there comes the time when the MQTT connection faces issue and the connection to our devices disrupts, showing multiple disconnections. as in the logs of kafka this happens when som mqtt-transport topics get deleted by kafka or maybe some other reasons. 
after this happens I recreate the kafka and this issue gets solved. Is there any config to add or something to do to prevent this?

**My Server Environment**
* own setup
  * cloud  docker deployment
  * ThingsBoard 3.3.4.1
  * OS Name and Version: debian 11

* Connectivity
  * MQTT
  * HTTP

**Comment by pon0marev** [comment]
You should configure a kafka cluster of 3 nodes to achieve high availability and to prevent thingsboard interruptions when one of the kafka brokers stops or restarts. For example, you can use the [Kafka cluster template from Bitnami](https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose-cluster.yml).
