### ISSUE TITLE
Error uploading to google playstore

### ISSUE THREAD

**Issue by Natz017** [thingsboard/thingsboard#9615]
Remove conflicts from the manifest before uploading. The following content provider authorities are in use by other developers: org.thingsboard.pe.app.flutter.image_provider.

I can't find the package. 

![Error upload](https://github.com/thingsboard/thingsboard/assets/90948077/de7efbb1-350a-4d8b-a54f-8a4a24ce15fa)

**Comment by nikolamaksim1** [comment]
I faced exactly the same issue.
How to fix it?

**Comment by ashvayka** [comment]
The issue here is with the package name. Same package name is used by ThingsBoard Inc to publish the sample app. One should change the "org.thingsboard.pe..." to something unique. Usually the reversed domain of the company.

**Comment by ashvayka** [comment]
We will prepare the script to change the name and update the instructions to simplify the process.

**Comment by LeoMorgan113** [comment]
@Natz017 and @nikolamaksim1, here is a documentation [how to change AppName and BundleId](https://thingsboard.io/docs/pe/mobile/release/#change-app-name).
