### ISSUE TITLE
[Bug] Alarm table widget - infinite loading

### ISSUE THREAD

**Issue by ArtemDzhereleiko** [thingsboard/thingsboard#9618]
Step to reproduce:
1. Open the dashboard or create a new one;
2. Add the Alias(Single alias - device);
3. Add Alarm table widget with Alias from step 2  as datasource;
4. On the Device page, delete device that we used in step 2;
5. Go to dashboard;
![image](https://github.com/thingsboard/thingsboard/assets/83352633/38e8fce4-36e1-46fe-93ae-970c8d6e24c2)

**Expected behavior**
"No alarms found" message

**Comment by LukaszDuss** [comment]
got same issue with admin entity table
