### ISSUE TITLE
[Question] Permission denied pop-up adding dashboard with dashboard rights in Role

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#9646]
* Generic

**Description**
When I add a dashboard with the + sign I get a pop-up with permission denied.
But the role that I use does have create rights,
When I click away the pop-up I can continue adding a new dashboard though.

It's taking away the usefulness of Role settings if they don't seem to work correctly.
The Role is defined as giving all rights except deleting rights.

**Environment**

 * OS:  Ubuntu Server 20.04LTS
 * ThingsBoard PE 3.5.1

![image](https://github.com/thingsboard/thingsboard/assets/49442805/2c606bdc-a954-4c66-990b-7ebe4243b1e1)
![image](https://github.com/thingsboard/thingsboard/assets/49442805/004cb922-00f8-4864-ba96-c82a3e7e5519)

**Comment by mykhailokornieiev** [comment]
Hi
Please confirm if this problem is still relevant.
If yes, then please provide full steps to reproduce this problem with explanation of tenant/customer level and user group location of assigned role.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
