### ISSUE TITLE
[Feature Request] Calculated Timewindows based on telemetry or attribute data

### ISSUE THREAD

**Issue by dreibelt** [thingsboard/thingsboard#9662]
I have a situation where moments in time are important for a device, thus we record a timeseries value which is a timestamp of this moment. These moments are usually service or failure occurances.

I would like to be able to show data that starts from a stored timeseries "timestamp" until now, or more specifically, using a timeseries value to "calculate" the widget or dashboard timewindow. Even a widget similar to the date-range-picker which can assiciate to specific widgets would be handy (seperate feature)

I have considered this might be possible with actions. but this would require alot of duplicate code. 

**Additional context**
Imagine we need to maintain a service log for a pump, tracking several key counters between automatically captured points in time, often these moments are unknow to the person viewing the telemtry.

**Comment by Ultrazombie** [comment]
No one has shown further interest in this, so it has been rejected. Please create a new feature request if you still consider this valid.
