### ISSUE TITLE
Is it possible to change my default database installation? 

### ISSUE THREAD

**Issue by ahakDot** [thingsboard/thingsboard#9666]
I installed the Thingsboard instance on a Digital Ocean server and set it up using the standard PostgreSQL database approach. I would like to change my setup now and use a hybrid approach where I use Cassandra for telemetry data and SQL for entities since my server receives a lot of sensor readings. Is there a way to migrate without reinstalling the instance or losing the saved data? 

I am looking forward for your support

**Comment by Backdraft007** [comment]
Yes,
I think it is possible. https://github.com/thingsboard/database-migrator 
But I don't know, if this "old" tool works with current version.
I'm also at the point to switch to hybrid, but not yet the time. I will test it in a few days with my test server.

**Comment by ahakDot** [comment]
Thanks mate @Backdraft007 for the help. I am also not pretty sure if it works and don't want to sacrifice losing the data i have. I would really appreciate it if you tell me if the test with your test server went good or not.

**Comment by Backdraft007** [comment]
Hey,
first tests are good. But I stuck on migration from dump to SSTables. My server has not enough RAM. I have to order a bigger one. But I don't have time for it until tomorrow.
I will report.

**Comment by Backdraft007** [comment]
Hi @ahakDot,
no good news. All steps working fine, but I don't see any historical data. I have to investigate it next week.

**Comment by pon0marev** [comment]
Try migration procedure again as we have fixed some bugs in the migrator code. The migrator supports all versions from 3.0.0 to latest.
