### ISSUE TITLE
[Feature Request] Display active fault codes

### ISSUE THREAD

**Issue by JakeDaSnake80** [thingsboard/thingsboard#9669]
For automotive as well as the mobile industry, the fault codes (J1939 and DM1) currently active is reslly important. A widget to show currently active fault codes is needed.

Every fault code (DM1) consists of source address (number, where 0 could be the engine), SPN (failing component, e.g. 16 is engine fuel filter), FMI (number, some details what the fault code be), occ (number - occurrence count, i.e. how many times have the fault occurred) and state (0/1 - inactive or active). A widget with columns for these values should be available.
If a fault occurs, the state is set to 1 (active) and the source address combined with the SPN is not present in the list in the widget, a line should be added to the widget. If the fault is updated but the state is set to 0 (inactive), the corresponding line (source address and SPN) should be removed. If state stays at 1 but FMI and/or occ is changed, this should be reflected in the widget.

**Comment by JakeDaSnake80** [comment]
Example of sending MQTT messages and how and what should be shown in the active fault codes widget

![image](https://github.com/thingsboard/thingsboard/assets/151576361/290e0cba-5013-48c7-8e12-0d084ed86919)

**Comment by JakeDaSnake80** [comment]
If a fault has gone from inactive to active a few times, i.e. the occurrence count has increased, implies that I will see the fault code on multiple lines. 
For example, if adding a filter (filter on State == true) and sending the data as in the screenshot - there will be two lines for SA=1 and SPN=110. The first and last sent MQTT messages will generate the two lines.

**Comment by devaskim** [comment]
So you want to display only latest data which relates to SA/SPN pair, right?

**Comment by JakeDaSnake80** [comment]
Yes, correct

**Comment by devaskim** [comment]
I think the problem is more general than absent of fault codes widget. You need some kind of SQL's `GROUP BY` and `DISTINCT` by/for several data keys (`SN` and `SPN`), but TB doesn't support such data selections.

**Comment by JakeDaSnake80** [comment]
Would it make any difference if the SA/SPN was combined into a single value instead of a pair?

**Comment by devaskim** [comment]
No, I think. 
In general, TB stores every data key (`SN`, `SPN`, `FMI`, `OCC`) separately, so there is no link between them at all

**Comment by devaskim** [comment]
As alternative, with the help of rule engine you can convert such MQTT messages to TB alarm where `SN`/`SPN` pair will be alarm's type, `State` will indicate if you need to create/update or clear alarm. Other fields you can put to alarm's addition info to display them later in Alarm Table widget.

**Comment by JakeDaSnake80** [comment]
That might be a solution. I will have a look at that. Thanks!

**Comment by JakeDaSnake80** [comment]
Yes, worked as you suggested! Perfect, thanks!

**Comment by JakeDaSnake80** [comment]
Did some more testing. In the create alarm rule node I've put SA, SPN, FMI, OCC and STATE to the alarm's addition info. Is it possible to have SA, SPN etc. shown as columns in the alarm table widget? Currently I need to go into details in the alarm widget to be able to see them.

**Comment by devaskim** [comment]
Use `additionalInfo.SA` as data key

**Comment by JakeDaSnake80** [comment]
How do I retrieve that? Tried it like this but didn't work.

![image](https://github.com/thingsboard/thingsboard/assets/151576361/b54ff48b-ba3e-4f91-b5ae-27da39b440f7)

**Comment by devaskim** [comment]
Sorry, `details.SA`

**Comment by JakeDaSnake80** [comment]
Ok, got it to work. Not obvious how to do it though. First I need to add an existing alarm data key, like severity, and then go in and modify the data key to details.SA. Is there a better way to do it?

**Comment by devaskim** [comment]
I don't know, but it would be a good feature request.

**Comment by JakeDaSnake80** [comment]
Good that it works anyway! Super happy with the support you're providing! Thanks a lot!
