### ISSUE TITLE
[Bug] PE3.6.1 API 403: You don't have permission to perform this operation!

### ISSUE THREAD

**Issue by jason-hulkman** [thingsboard/thingsboard#9670]
**Describe the bug**
API:[/api/otaPackage/info/{otaPackageId}] get error message: "You don't have permission to perform this operation!"

request like:
ht*tp://xxxxDomain:8080/api/otaPackage/info/otapackageID-otapackageID-otapackageID

response:
{
  "status": 403,
  "message": "You don't have permission to perform this operation!",
  "errorCode": 20,
  "timestamp": 1700552667986,
  "subscriptionErrorCode": null,
  "subscriptionEntry": null,
  "subscriptionValue": null
}

The APP we developed attempts to use this API interface to obtain OTA package information, Available for users with 'TENANT_ADMIN' or 'CUSTOMER_USER' authority.

We use the customer's permissions to call this interface.

In the past two months, we tested PE 3.5.1 and it worked fine. Recently we upgraded to PE 3.6.1, but we were prompted that we did not have permission to obtain it.

However, the same API interface is obtained normally in CE 3.6.1.

**Your Server Environment**
PE 3.6.1 install at Linux ubuntu 22

**Your Client Environment**
Safari browser

**Your Device**, No device!

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/133846760/a174c59f-c116-4c63-81e2-b74ea7da07de)
<img width="1106" alt="WeChatWorkScreenshot_4eacb789-09af-4bd1-ba23-73e595b2d3ff" src="https://github.com/thingsboard/thingsboard/assets/133846760/db60f812-9b59-4795-99bf-fe57d10430d3">

**Comment by jabr0ni** [comment]
This has started to happen to my API on 3.5.1. Not sure what's happened here

**Comment by xalt7x** [comment]
This bug is fixed in version 3.6.2 PE

From the [release notes](https://thingsboard.io/docs/pe/reference/releases/#v362):

> Fixed validation of Customer permissions for OTA Package entity;

Download links and upgrade instructions for Ubuntu can be found in the [documentation](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-362pe).
