### ISSUE TITLE
[Question] Can i change the filter in the widget action?

### ISSUE THREAD

**Issue by psxbox** [thingsboard/thingsboard#9674]
**Component**
 * UI

**Description**
![image](https://github.com/thingsboard/thingsboard/assets/87794982/43994b36-58fe-4baf-88ab-e0e7fd2f0542)

I have two `Entity count` and on `Entities table`.
Can i change the filter in `Entities table` widget by clicking the `Entity count` widget?

**Environment**

 * OS:  docker
 * ThingsBoard: 3.6.1 CE
 * Browser: Chromium

**Comment by devaskim** [comment]
As I know you can only update filter's input data, not replacing by another filter, because it is widget configuration and it is loaded when the dashboard starts up.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
