### ISSUE TITLE
[Question] How to generate Notification for all customer user from rule chain

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#9676]
**Component**
 * Rule Engine

**Description**
I try to generate notification based on data in message device.
This works well, and generate notification for "tenant user" recipient.
But the same rule engine notification node, with "Users of the entity owner" recipient doesn't send notification to the users of the customer at which the device is affected.
Why ?

If someone can confirm me simple step to make it running... maybe I forget something...

1. Create a customer : "MyCustomer"
2. Create a user : "MyCustomerUser", affected to "MyCustomer"
3. Create a device : "MyDevice", affected to customer "MyCustomer"

Create a rule chain that check message content and generate notification if success :  

Global view :  
![image](https://github.com/thingsboard/thingsboard/assets/151620289/68d82797-46d4-4248-8e97-33c22682c22c)

Script filter :  
![image](https://github.com/thingsboard/thingsboard/assets/151620289/cc7e69c6-b575-4413-ab76-5ac43afbbb75)  
Simple check if "statusF1 is positive in msg data  
`return msg.statusF1 > 0;`

send notification :  
![image](https://github.com/thingsboard/thingsboard/assets/151620289/9563c399-7c51-4dd3-b247-44f79d7b5c5b)
Select recipient as "Users of the entity owner"

Test it, by sending attribut "statusF1" from "MyDevice", and no notification are sent to "MyUser" ???
If I select "tenant users" as recipient in send notificaiton node : It works...

Maybe I misunderstand something ?
Could it be a bug ?
Is someone is able to use "Users of the entity owner" correctly ?

???
Thank for your help.

**Environment**
 * ThingsBoard: PE cloud version (latest 3.6.1)
 * Browser: Chrome

**Comment by ViacheslavKlimov** [comment]
As a workaround, you could generate an alarm for the device based on your filter script, and then configure Alarm notification rule (in the Notification center) to send notifications to device's owner when an alarm goes on for it.

**Comment by GregAscolab** [comment]
Thank you for this feedback.
Waiting 3.6.2 release fixing couple of bug ASAP ;-)
