### ISSUE TITLE
[Bug] Attribute value cleared when cancelling/closing edition box

### ISSUE THREAD

**Issue by arnauldf** [thingsboard/thingsboard#9679]
**Describe the bug**
I've created a dashboard with a "Update Multiple Attributes" widget, in which I have some fields coming from an asset attributes, among which some are json values. So I decided to set data keys type as JSON, in the datasource datakeys configuration panel.
[below Screen 1]
So now I can click on the edit icon to open a dialog box when I'm testing the widget
[below Screen 2]
When I click on the edit icon, a box opens to edit the json value
[below Screen 3]
But when I close or cancel the box, the initial value disappears :(
[below Screen 4]

**Your Server Environment**
* own setup
  * cloud and local docker deployment
  * ThingsBoard Version: 3.6.0PE
  * AWS for cloud, MacOS for local docker

**Your Client Environment**
**Desktop**
* OS: MacOS Sonoma
* Browser: chrome and safari
* Version: latest

* Connectivity
  * HTTP

**To Reproduce**
1. Create an asset with a json attribute
2. Create a dashboard using a "Update Multiple Attributes" widget
3. Set attribute datakey type as JSON
4. Test:
- click on json field edit icon
- cancel box => value is cleared

**Expected behavior**
Just let the initial value as it was when opening the dialog box

**Screenshots**
Screen 1
![image](https://github.com/thingsboard/thingsboard/assets/18332312/01eb4d0a-58a2-4274-9c47-8d953c4395bd)
Screen 2
![image](https://github.com/thingsboard/thingsboard/assets/18332312/dd8a65a2-4119-4546-b53d-b2f21cfe6c91)
Screen 3
![image](https://github.com/thingsboard/thingsboard/assets/18332312/37b5e2f7-0798-42ea-b93b-a40cef95306e)
Screen 4
![image](https://github.com/thingsboard/thingsboard/assets/18332312/93083b28-7c17-48c4-b1ba-9648f44c4cd7)

**Comment by xalt7x** [comment]
Fixed in 3.6.2 ( PR #9729 )
