### ISSUE TITLE
[Feature Request] Support for sort by column for the alarms table widget

### ISSUE THREAD

**Issue by JakeDaSnake80** [thingsboard/thingsboard#9680]
The alarms table widget doesn't seem to support sort by column. That would have been a good addition as well as a setting for default column to sort by.

![image](https://github.com/thingsboard/thingsboard/assets/151576361/c1aac15d-6dda-46d2-8e60-8d29008354d9)

**Comment by epalchenko** [comment]
Hello,

The tickets (PROD-5071) about your feature requests have already been added to our backlog for the product team.

We will close this ticket as it is already in our backlog.
Please follow our Release Notes (https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.
