### ISSUE TITLE
[Question] Sparkplug - using DCMD 

### ISSUE THREAD

**Issue by framista** [thingsboard/thingsboard#9681]
**Sparkplug**

**Description**
I followed this example https://thingsboard.io/docs/reference/mqtt-sparkplug-api/ to use sparkplug. I tried to add RCP button to switch on led green. I chose rcp button, target device and in rcp settings I wrote DCMD in RCP method and { "metricName": "Outputs/LEDs/Green", "value": true} in RCP method params. But when I click on button nothing is happening. 
I also tried to use a widget RCP debug terminal. But after writing: DCMD {
    "metricName": "Outputs/LEDs/Green",
    "value": true
}
I got error message: {"result":"BAD_REQUEST_PARAMS","error":" Failed send To Device Rpc Request: DCMD. This device does not have a metricName: [Outputs/LEDs/Green]”}.
Is there any way to print existing metricName or to debug what is exactly incorrect?

When I try to change value for Outputs/LEDs/Green in device/attributes/shared attributes, the led works correctly. So I assume that my device is correctly configured.

**Comment by myroslav-tb** [comment]
Hi @framista, we found an issue with the sparkplug emulator, and our team is working on resolving it.
