### ISSUE TITLE
[Feature Request]Move multiple widgets at a time

### ISSUE THREAD

**Issue by kurt-klingbeil** [thingsboard/thingsboard#9682]
Currently, it seems that Thingsboard only supports dragging one widget at a time.
On those rare occasions (/snort) when one needs to add something to TheTop, 
one must go to TheBottom, and drag everything, one by one, down by enough to create the top-end space to
insert a new widget. Then fiddle around pushing everything back up.

Box-drag is a well-established UI concept as are click-select and/or shift-select to choose a number of items
and then subject them all to some commonly supported operation - typically move.

Some other ways this could be implemented is to leave blank space at the top of a page, which would not be rendered or displayed - except when in edit mode.
Upon closing the edit, the blank upper region would be "scanned" looking for some "visible" entity.
This "blank margin" would simply be "blanked out" and the rendering of the page graphics would 
begin at the first non-blank entity.

If a new entity is dragged to the "top" area of the page, that would simply reduce the blank margin.

**Comment by epalchenko** [comment]
Hello,

The tickets (PROD-5069, PROD-5070) about your feature requests have already been added to our backlog for the product team.

We will close this ticket as it is already in our backlog.
Please follow our Release Notes (https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by Ashbajit** [comment]
Has this feature been added?
