### ISSUE TITLE
Can we use javascript libray (JS module) under resources in rule chains/ system widgets? If yes how?

### ISSUE THREAD

**Issue by adksujan** [thingsboard/thingsboard#9686]
**Component**
 * Rule Engine

**Description**
With then upgrade of thingsboard to community version 3.6.1 there's an option to upload JS module in Resources library. However, I couldn't find the documentation on its uses and purpose of this feature and how to use it. I would expect that the JS module would be reusable in widgets and rule chains to eliminate the redundant codes that are required in different parts. The help page link leads to LWM2M Device API reference and there's nothing about the usage of JS module.
I would like to reuse the JS module on rule chain in at least script node as well as on the already existing widgets. How can I achieve this?

**Environment**

 * ThingsBoard: 3.6.1

**Comment by devaskim** [comment]
There is not such capability.
