### ISSUE TITLE
[Feature Request] A more comprehensive Simplified Chinese language pack for ThingsBoard

### ISSUE THREAD

**Issue by stvliu** [thingsboard/thingsboard#9694]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devaskim** [comment]
If you are native speaker, it would be faster to do it yourself. Translation items are stored in JSON format [here](https://github.com/thingsboard/thingsboard/tree/master/ui-ngx/src/assets/locale). You can edit and save these files even in browser via Github UI. The most complete is [locale.constant-en_US.json](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/assets/locale/locale.constant-en_US.json)
