### ISSUE TITLE
Logic Unit

### ISSUE THREAD

**Issue by PeHo89** [thingsboard/thingsboard#97]
Eg.: Sending a message to a board, when sensor value of another board is over a threshold. In my case: controlling a gpio on a Raspberry Pi 2 depending on sensor value from LattePanda (another device) directly via Thingsboard. The LattePanda is streaming sensor values to the Thingsboard platform. The LED connected to a GPIO on a Raspberry Pi 2 could be controlled via the platform. Now I want to create a logic unit, where you can say, turn on LED of board A when temperature sensor is more than 20 degrees centigrade on board B. This can't be done nowadays via the platform directly. This is what I will try to implement.

**Comment by vparomskiy** [comment]
It can be implemented using ThingsBoard Rule Chains
