### ISSUE TITLE
TB stops working after query telemetry

### ISSUE THREAD

**Issue by Tangerino** [thingsboard/thingsboard#970]
When I issue the following query the server stops working or acting very weird.
The time series has only one month of data every 15 minutes.

<pre>
/api/plugins/telemetry/DEVICE/658bb0e0-83ab-11e8-8f52-958f8aa0b2ec/values/timeseries?keys=pm_wh_produced&startTs=1501313040000&endTs=1532849040000&interval=60000&limit=1&agg=SUM'
</pre>

![image](https://user-images.githubusercontent.com/3164100/43364024-efd50164-9311-11e8-84aa-0ff1d0b25696.png)

For any additional information, just ping me please.

**Comment by ashvayka** [comment]
There is a configuration parameter in thingsboard.yml to change the amount of max parallel queries. We have seen this problem in v2.0.0 but fixed it long time ago.

**Comment by ashvayka** [comment]
your request results in multiple queries on the background. One for each "interval" in the endTs - startTs range. You are producing a lot of queries that are hitting the limit and you get error.
