### ISSUE TITLE
[Bug]Is it possible to use unsigned 32bit in TBEL?

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#9701]
Hello. 

Works in javascript but error in TBEL.

var num = 0x80000000; 　// error TBEL
var num = 0x80000000; 　// OK Javascript

var num = 0x7fffffff; 　　// OK TBEL & Javascript

I think this behavior is a bug in TBEL.

**Comment by xalt7x** [comment]
TBEL is able to handle values larger than 0x7FFFFFFF (int32 max. value), however, as of now they need to be converted with [TBEL helper functions](https://thingsboard.io/docs/user-guide/tbel/#helper-functions).

For this case parseLong works:

`parseLong("0x80000000",16)`

Description from the [documentation](https://thingsboard.io/docs/user-guide/tbel/#parselong) website

> **parseLong**
> Converts input string to long.
> 
> Syntax:
> Long parseLong(String str[, String radix])
> 
> Parameters:
> - str: string - the String containing the long representation to be parsed.
> - radix: String - optional radix to be used while parsing string.

**Comment by h-takado** [comment]
Thanks for the comment.
I will give it a try.

and, Happy New Year.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
