### ISSUE TITLE
[Question] ThingsBoard Microservices Installation Update Problem

### ISSUE THREAD

**Issue by berofa** [thingsboard/thingsboard#9706]
Hello everyone

I have a ThingsBoard CE Microservices installation as described here:

https://github.com/thingsboard/thingsboard/tree/master/docker

Until recently I was still using TB v3.2.1, now I've set about updating the installation to the latest version. I proceeded as described at https://github.com/thingsboard/thingsboard/tree/master/docker:

```
$ ./docker-stop-services.sh
.evn file adapted (the desired version)
$ ./docker-upgrade-tb.sh --fromVersion=[FROM_VERSION]
$ ./docker-start-services.sh
```

I imported all versions individually (e.g. from 3.2.1 to 3.2.2, then to 3.3.0, then to 3.3.1, etc. as described here: https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-344).

Up to and including version 3.4.4 everything works without any problems. I can't make the jump from 3.4.4 to 3.5.0. Although the update is carried out successfully, I receive the following error message when I log in to ThingsBoard and go to the devices page and open a device there:

**java.lang.RuntimeException: unknown object tag -126**

The devices (as well as all other data including time series data) are there, but I can no longer connect devices via MQTT and upload new data to ThingsBoard. The error message itself doesn't tell me anything and I couldn't really find anything about it on Google.

Unfortunately, even a complete server reboot does not solve the problem. I have already tried to continue with the update to the latest version despite the error message (i.e. installing 3.5.1 and then 3.6.0) but the error message also appears with version 3.6.0.

Have any of you already had this problem and a solution? Or an approach I could try/where I could look for more details?

The operating system is Linux (Ubuntu).

**Comment by trikimiki** [comment]
Hi!
sorry for coming late to this issue
`java.lang.RuntimeException: unknown object tag -126`
That error is linked to cache. Most likely, you are using Redis, and need to flush it:
`docker exec -it <redis_id> bash`
`redis-cli flushall`
