### ISSUE TITLE
[Question] How to change Date format in Update Multiple Attributes widget for calender? 

### ISSUE THREAD

**Issue by yusufscelik** [thingsboard/thingsboard#9711]
## UI

**Description**
I want to change the date format in the 'Update Multiple Attributes Widget,' but it doesn't seem to be working. I can change the format for displaying values in a table using the JavaScript Format Framework. I did the same for the Input Widget, but the format, that i use for calendar didn't change. I want to have the both of the data format as "DD.MM.yyyy" not "DD/MM/yyyy".

![updateMultipleAttributes](https://github.com/thingsboard/thingsboard/assets/95184239/a72a0f27-5be1-4eed-ad15-dce72de974f0)

Here, you can see that the same value settings don't work for the Input widget, even though I have the same configuration for both of them. My value setting JS format seems like this;

Set value settings:
```
console.log(moment(value).format("DD.MM.yyyy"));
return moment(value).format("DD.MM.yyyy");
```

![updateMultipleAttributes2](https://github.com/thingsboard/thingsboard/assets/95184239/fe504fb9-d8b4-4449-9c1a-2afc8efbdb32)

**Environment**
 * ThingsBoard: Pressional Edition 
 * Browser: Microsoft Edge latest

**Comment by xalt7x** [comment]
Hello @yusufscelik 
Unfortunately, Angular Datepicker is currently [hardcoded to "en-GB"](https://github.com/thingsboard/thingsboard/blob/hotfix/3.6.2/ui-ngx/src/app/shared/shared.module.ts#L246). Please see related issues #6958 and #9895
