### ISSUE TITLE
[Question] Inquiry about ThingsBoard Interaction with IoT Devices and Offline Device Handling

### ISSUE THREAD

**Issue by piyush-bhanushali1** [thingsboard/thingsboard#9719]
Hi,

I'm interested in understanding how ThingsBoard interacts with IoT devices and how it manages requests when a device is offline. Could someone please provide insights into the code implementation related to this functionality?

Thank you!

**Comment by epalchenko** [comment]
Hello @piyush-bhanushali1,
ThingsBoard tracks the state of the persistent RPC. There are 7 available states that you can familiarise yourself with at the link:
https://thingsboard.io/docs/pe/user-guide/rpc/#persistent-rpc

**Comment by epalchenko** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with a full description of your request.
