### ISSUE TITLE
HTTP Transport Service" building failed

### ISSUE THREAD

**Issue by ludarod** [thingsboard/thingsboard#9732]
**Description**
Hello everyone, I need some help to resolve compilation an issues problem of TB from source, this is the error

[INFO] Thingsboard HTTP Transport Service ................. FAILURE [ 2.778 s]
[INFO] Thingsboard MQTT Transport Service ................. SKIPPED
[INFO] Thingsboard CoAP Transport Service ................. SKIPPED
[INFO] ThingsBoard Server UI .............................. SKIPPED
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.997 s
[INFO] Finished at: 2020-07-31T16:02:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.thingsboard:gradle-maven-plugin:1.0.11:invoke (default) on project http: org.gradle.tooling.BuildException: Could not execute build using connection to Gradle distribution from 'https://services.gradle.org/distributions/gradle-7.1.1-bin.zip'. -> [Help 1]

**Environment**

 * OS:  I tried in windows and ubuntu 20.04 LTS and got it the same error
 * ThingsBoard: 3.6.1
 Java: 11
Maven: 3.9.5

**Comment by myUsername-LYC** [comment]
I have the same problem. Have you solved it?

**Comment by Ultrazombie** [comment]
Closed due to inactivity

**Comment by Georgio-Khoury** [comment]
for anyone still encountering the same error, focus on the this line:
Could not execute build using connection to Gradle distribution from 'https://services.gradle.org/distributions/gradle-7.1.1-bin.zip'. -> [Help 1]

Focus on the gradle version. The issue is most probably caused by this gradle release not supporting your JDK.
For more info about gradle-jdk compatibility check this:
https://docs.gradle.org/current/userguide/compatibility.html

The simple solution here is to downgrade your JDK (or update it if it's older than 8) for it to be compatible with that gradle release.

**Comment by sduqlsc** [comment]
i solve the problem by changing the gralde download url, aka, download gralde zip and put it in a file server, then change the url to the file server url. 

see https://github.com/thingsboard/thingsboard/issues/3696#issuecomment-2235051426
