### ISSUE TITLE
[Question] Would creating a custom rule node to replace 100 rule node processings improve performance?

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#9736]
**Component**

 * Rule Engine

**Description**
We have complex logic for a single incoming message, it need about 100 rule node to process it, thus we have many processing timeout errors.

I want to know if we create a custom rule node to do all things which did by 100 rule nodes, would it improve performance?

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.1

**Comment by ezeroldan24** [comment]
Good morning.. Performance wouldn't improve in my opinion if you sent the same amount of data. What specifically do you need?

**Comment by Ultrazombie** [comment]
Closed due to inactive.
