### ISSUE TITLE
Things Board Eco System

### ISSUE THREAD

**Issue by torandneo** [thingsboard/thingsboard#974]
Hi
First of all Thanks for the Nice work.
I am looking to customize thingsboard so that the front end and back end are hosted on different servers.
I dont want to install it as a service.
Can any one suggest help with this.Any pointers.

Regards
Neo

**Comment by Karabiy** [comment]
hello
there are various options for the installation. you may refer to this link regarding those: https://thingsboard.io/docs/user-guide/install/installation-options/
