### ISSUE TITLE
[Bug] ThingsboardErrorResponse.timestamp is integer but spec says it is string

### ISSUE THREAD

**Issue by ardrabczyk** [thingsboard/thingsboard#9740]
**Describe the bug**

In Swagger spec it says that `timestamp` is string:

    "ThingsboardErrorResponse": {
      "title": "ThingsboardErrorResponse",
      "type": "object",
      "properties": {
        "status": {
          "type": "integer",
          "description": "HTTP Response Status Code",
          "format": "int32",
          "readOnly": true,
          "example": 401
        },
        "message": {
          "type": "string",
          "description": "Error message",
          "readOnly": true,
          "example": "Authentication failed"
        },
        "errorCode": {
          "type": "object",
          "description": "Platform error code:\n* `2` - General error (HTTP: 500 - Internal Server Error)\n\n* `10` - Authentication failed (HTTP: 401 - Unauthorized)\n\n* `11` - JWT token expired (HTTP: 401 - Unauthorized)\n\n* `15` - Credentials expired (HTTP: 401 - Unauthorized)\n\n* `20` - Permission denied (HTTP: 403 - Forbidden)\n\n* `30` - Invalid arguments (HTTP: 400 - Bad Request)\n\n* `31` - Bad request params (HTTP: 400 - Bad Request)\n\n* `32` - Item not found (HTTP: 404 - Not Found)\n\n* `33` - Too many requests (HTTP: 429 - Too Many Requests)\n\n* `34` - Too many updates (Too many updates over Websocket session)\n\n* `40` - Subscription violation (HTTP: 403 - Forbidden)",
          "readOnly": true,
          "example": "10"
        },
        "timestamp": {
          "type": "string",
          "description": "Timestamp",
          "format": "date-time",
          "readOnly": true
        }
      }
    }

but for some reason it's integer:

    $ curl -s --header 'Authorization: Bearer WRONG-BEARER' 'http://localhost:8080/api/deviceProfiles?pageSize=100&page=0' | jq
    {
      "status": 401,
      "message": "Invalid username or password",
      "errorCode": 10,
      "timestamp": 1701348580144
    }

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version: built from master

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Linux

**Your Device**

* Connectivity
  * HTTP

**To Reproduce**

    $ curl -s --header 'Authorization: Bearer WRONG-BEARER' 'http://localhost:8080/api/deviceProfiles?pageSize=100&page=0' | jq
    {
      "status": 401,
      "message": "Invalid username or password",
      "errorCode": 10,
      "timestamp": 1701348580144
    }

**Expected behavior**

`timestamp` should be string according to spec. Either the implementation or spec has to be changed.

**Comment by skewty** [comment]
Schema issue similar to #9769 and https://github.com/thingsboard/thingsboard-extensions/issues/37.

Given these issues exist for all aspects of ThingsBoard (TypeScript client,  Python client) perhaps some shared [JSON schema](https://json-schema.org/) should be used by both server and client to ensure problems like this don't continue to make their way into the code base in the future?
