### ISSUE TITLE
Failed to subscribe v1/gateway/rpc

### ISSUE THREAD

**Issue by niks-coder** [thingsboard/thingsboard#975]
I am trying to connect thingsboard gateway service with thingsboard server.
I am using thingsboard 2.1.0 Release and tb-gateway 2.0.4 (Pre-Release). whenever i start the gateway service i find the error in thingsboard log

2018-08-01 08:27:50,328 [nioEventLoopGroup-5-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt43] Processing connect msg for client: netty-mqtt/q6chKmTv!
2018-08-01 08:27:50,405 [nioEventLoopGroup-5-7] WARN  o.t.s.t.mqtt.MqttTransportHandler - [mqtt43] Failed to subscribe to [v1/gateway/rpc][AT_MOST_ONCE]

due to which i am unable to have RPC server call to device.

I also tried to subscribe v1/gateway/rpc using node red with user name as gateway Access Token but still i am not able to subscribe the topic.

**Comment by NikhilBijagarni** [comment]
Hi,
No the problem still exist.

**Comment by syuusikou** [comment]
can you tell me how did you solved this problem please?
I stucked at this for 1 week, so desperate...

**Comment by syuusikou** [comment]
I am now trying to use some MQTT client tool to do some test.

**Comment by NikhilBijagarni** [comment]
I have not solved this issue yet i tried to subscribe RPC topic using MQTT
client tool but was not successful.
May be if you solve this let me know.
