### ISSUE TITLE
How to see mqtt broker logs online?

### ISSUE THREAD

**Issue by vijayflashbulb** [thingsboard/thingsboard#9752]
we have a device which is running on nbiot, but sometimes data is not sent successfully. so is there any way to get a response from thingsboard whether the data was successfully transmitted.

**Comment by xalt7x** [comment]
It's possible to increase thingsboard.log message verbosity for certain parts of the Thingsboard.
Please try adding the line below to your [logback.xml](https://thingsboard.io/docs/user-guide/troubleshooting/#enable-certain-logs) .
` <logger name="org.thingsboard.server.transport.mqtt.MqttTransportHandler" level="DEBUG" />`

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
