### ISSUE TITLE
Interaction over Widgets

### ISSUE THREAD

**Issue by openedhardware** [thingsboard/thingsboard#976]
I need to do something on a widget(A) when something is changed on the other widget(B).

I used **state controller** to save the changed values of **B** to `params` and then got that values on **A**.

The problem is, how to get notified whenever the status of **B** changes.

Any idea?

e.g.

Code on Widget **B** to save `startDate` to `params`:

```javascript
var stateId = self.ctx.stateController.getStateId();
var params = self.ctx.stateController.getStateParams();
params.startDate = self.ctx.$scope.startDate;
self.ctx.stateController.updateState(stateId, params);
```

Code on Widget **A** to get `startDate` from `params`:
```javascript
var startDate = self.ctx.stateController.getStateParams().startDate;
```

How can I update `startDate` on **A** whenever `startDate` on **B** changes?

**Comment by openedhardware** [comment]
I noticed that the interaction feature was already implemented in your demo dashboard - https://thingsboard.io/smart-metering/

So if I select `District A` on the map widget, the titles of the right-bottom widget are also changed.

How did you integrate this feature?

**Comment by vparomskiy** [comment]
You can use Action API
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#actions-api

Also, take a look at this videos
https://thingsboard.io/docs/iot-video-tutorials/#dashboard-development-guide-part-2-dashboard-states-aliases-and-widget-actions

**Comment by openedhardware** [comment]
Thanks, @vparomskiy !

Closing this issue now...

**Comment by openedhardware** [comment]
@vparomskiy 

I couldn't find what I needed... :cry: 

So I just need to execute something on a widget when another widget changes.

Impossible?

**Comment by ashvayka** [comment]
Possible with custom widgets and some event bus, I am not expert in front-end development but it should be possible.

**Comment by openedhardware** [comment]
Could you share the details of the event bus?

**Comment by openedhardware** [comment]
Any details about the ActionAPI?
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#actions-api

**Comment by vparomskiy** [comment]
If you are using custom widgets, then you can implement basic messaging using events:
For example, you want to send an event from custom widget A to the custom widget B.

In widget A (send event)
```
$scope.$emit('my-custom-event',
            {startTime: vm.currentEntity.startedAt, endTime: vm.currentEntity.endedAt, deviceId: vm.currentEntity.deviceId}
        );
```

In widget B (receive event)
```
$scope.$on('my-custom-event', function (event, data) {
                if (data) {
                    actOnEvent(data);
                }
            });
```

**Comment by openedhardware** [comment]
Perfect!

Let me try right now. :)

**Comment by openedhardware** [comment]
@vparomskiy 
Hmm, it does not work...

Here are simple widgets that sends/receives events with your code:

[SimpleButtons.zip](https://github.com/thingsboard/thingsboard/files/2252891/SimpleButtons.zip)

Would you like to import these widgets and test on your end?

Pretty simple widgets.

Cheers.

**Comment by openedhardware** [comment]
- Send Event Widget:

```
{
  "alias": "send_event_button",
  "name": "Send Event Button",
  "descriptor": {
    "type": "static",
    "sizeX": 7.5,
    "sizeY": 3,
    "resources": [],
    "templateHtml": "<div>\n    <md-button ng-click=\"onBtnClick()\">Send Event</md-button>\n</div>",
    "templateCss": "",
    "controllerScript": "self.onInit = function() {\n\n    self.ctx.$scope.onBtnClick = function() {\n        console.log('Sending event.');\n        self.ctx.$scope.$emit('my-custom-event',\n            {message: \"Hello!\"}\n        );\n    }\n}\n\nself.onDestroy = function() {\n}\n",
    "settingsSchema": "{\n}",
    "dataKeySettingsSchema": "{}\n",
    "defaultConfig": "{\"datasources\":[{\"type\":\"static\",\"name\":\"function\",\"dataKeys\":[{\"name\":\"f(x)\",\"type\":\"function\",\"label\":\"Random\",\"color\":\"#2196f3\",\"settings\":{},\"_hash\":0.15479322438769105,\"funcBody\":\"var value = prevValue + Math.random() * 100 - 50;\\nvar multiplier = Math.pow(10, 2 || 0);\\nvar value = Math.round(value * multiplier) / multiplier;\\nif (value < -1000) {\\n\\tvalue = -1000;\\n} else if (value > 1000) {\\n\\tvalue = 1000;\\n}\\nreturn value;\"}]}],\"timewindow\":{\"realtime\":{\"timewindowMs\":60000}},\"showTitle\":false,\"backgroundColor\":\"rgb(255, 255, 255)\",\"color\":\"rgba(0, 0, 0, 0.87)\",\"padding\":\"8px\",\"settings\":{\"cardHtml\":\"<div class='card'>HTML code here</div>\",\"cardCss\":\".card {\\n    font-weight: bold;\\n    font-size: 32px;\\n    color: #999;\\n    width: 100%;\\n    height: 100%;\\n    display: flex;\\n    align-items: center;\\n    justify-content: center;\\n}\"},\"title\":\"Send Event Button\",\"dropShadow\":true}"
  }
}
```

- Receive Event Widget:
```
{
  "alias": "receive_event",
  "name": "Receive Event Button",
  "descriptor": {
    "type": "static",
    "sizeX": 7.5,
    "sizeY": 3,
    "resources": [],
    "templateHtml": "<div>\n    <h4>Message from other widget</h4>\n    <md-content layout-padding>\n        {{message}}\n    </md-content>\n</div>",
    "templateCss": "",
    "controllerScript": "self.onInit = function() {\n    self.ctx.$scope.$on('my-custom-event', function (event, data) {\n        if (data) {\n            console.log('Message is received!');\n            console.log(data);\n            self.ctx.$scope.message = data;\n        }\n    });\n}\n",
    "settingsSchema": "{\n}",
    "dataKeySettingsSchema": "{}\n",
    "defaultConfig": "{\"datasources\":[{\"type\":\"static\",\"name\":\"function\",\"dataKeys\":[{\"name\":\"f(x)\",\"type\":\"function\",\"label\":\"Random\",\"color\":\"#2196f3\",\"settings\":{},\"_hash\":0.15479322438769105,\"funcBody\":\"var value = prevValue + Math.random() * 100 - 50;\\nvar multiplier = Math.pow(10, 2 || 0);\\nvar value = Math.round(value * multiplier) / multiplier;\\nif (value < -1000) {\\n\\tvalue = -1000;\\n} else if (value > 1000) {\\n\\tvalue = 1000;\\n}\\nreturn value;\"}]}],\"timewindow\":{\"realtime\":{\"timewindowMs\":60000}},\"showTitle\":false,\"backgroundColor\":\"rgb(255, 255, 255)\",\"color\":\"rgba(0, 0, 0, 0.87)\",\"padding\":\"8px\",\"settings\":{\"cardHtml\":\"<div class='card'>HTML code here</div>\",\"cardCss\":\".card {\\n    font-weight: bold;\\n    font-size: 32px;\\n    color: #999;\\n    width: 100%;\\n    height: 100%;\\n    display: flex;\\n    align-items: center;\\n    justify-content: center;\\n}\"},\"title\":\"Receive Event Button\",\"dropShadow\":true}"
  }
}
```

**Comment by doranagy** [comment]
Hi there,

I have a similar problem like this. Do you have any updates or solutions?

**Comment by HaithemS** [comment]
Can't get to work. Anyone else tried this?

**Comment by doranagy** [comment]
Here is my solution:
[sendEvent.zip](https://github.com/thingsboard/thingsboard/files/2820831/sendEvent.zip)

**Comment by HaithemS** [comment]
Thank you @doranagy It works!

**Comment by vparomskiy** [comment]
I think that issue can be closed.

**Comment by anzorayubov** [comment]
> Here is my solution:
> [sendEvent.zip](https://github.com/thingsboard/thingsboard/files/2820831/sendEvent.zip)

after update to TB 3.0 it doesn't work(

**Comment by Karabiy** [comment]
there was the migration to the angular 9
you may refer to this link regarding those: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

**Comment by anzorayubov** [comment]
> there was the migration to the angular 9
> you may refer to this link regarding those: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

thanks, where i can read about all updates in TB 3? I so understand that delivered angular material also

**Comment by anzorayubov** [comment]
> there was the migration to the angular 9
> you may refer to this link regarding those: https://thingsboard.io/docs/user-guide/contribution/widgets-development/

and yet, how I can transfer event from widget to widget?

**Comment by Manusisko** [comment]
This is a new issue in TB3.0+ as $broadcast and $on have been deprecated. If anyone has found a Solution I'm also struggling with this issue.

**Comment by Manusisko** [comment]
For anyone facing this issue, I've found services are actually maintained across all widget contexts. So if you define a function in a service in one widget, it can be called in a different widget.
For example, I tested:

`//This is defined in the action of a widget or on it's Javascript with self.ctx.userService
widgetContext.userService.onThisCalled = function(message){
     console.log("MESSAGE", message);
}`

`if(widgetContext.userService.onThisCalled !== undefined){
       widgetContext.userService.onThisCalled("This works!");
}`


Hope this helps anyone

**Comment by ajithkumar222** [comment]
> For anyone facing this issue, I've found services are actually maintained across all widget contexts. So if you define a function in a service in one widget, it can be called in a different widget.
> For example, I tested:
> 
> `//This is defined in the action of a widget or on it's Javascript with self.ctx.userService widgetContext.userService.onThisCalled = function(message){ console.log("MESSAGE", message); }`
> 
> `if(widgetContext.userService.onThisCalled !== undefined){ widgetContext.userService.onThisCalled("This works!"); }`
> 
> Hope this helps anyone

i can't get widgetContext.userService.onThisCalled..how to achieve this

**Comment by Manusisko** [comment]
> 
> 
> > For anyone facing this issue, I've found services are actually maintained across all widget contexts. So if you define a function in a service in one widget, it can be called in a different widget.
> > For example, I tested:
> > `//This is defined in the action of a widget or on it's Javascript with self.ctx.userService widgetContext.userService.onThisCalled = function(message){ console.log("MESSAGE", message); }`
> > `if(widgetContext.userService.onThisCalled !== undefined){ widgetContext.userService.onThisCalled("This works!"); }`
> > Hope this helps anyone
> 
> i can't get widgetContext.userService.onThisCalled..how to achieve this

You need to define such function in a custom widget or in a widget's action (defined when action executes).

**Comment by ajithkumar222** [comment]
> > > For anyone facing this issue, I've found services are actually maintained across all widget contexts. So if you define a function in a service in one widget, it can be called in a different widget.
> > > For example, I tested:
> > > `//This is defined in the action of a widget or on it's Javascript with self.ctx.userService widgetContext.userService.onThisCalled = function(message){ console.log("MESSAGE", message); }`
> > > `if(widgetContext.userService.onThisCalled !== undefined){ widgetContext.userService.onThisCalled("This works!"); }`
> > > Hope this helps anyone
> > 
> > 
> > i can't get widgetContext.userService.onThisCalled..how to achieve this
> 
> You need to define such function in a custom widget or in a widget's action (defined when action executes).

i defined widgetContext.userService.onThisCalled on javascript window in custom widget,but it shows a error

**Comment by inanlia** [comment]
> For anyone facing this issue, I've found services are actually maintained across all widget contexts. So if you define a function in a service in one widget, it can be called in a different widget. For example, I tested:
> 
> `//This is defined in the action of a widget or on it's Javascript with self.ctx.userService widgetContext.userService.onThisCalled = function(message){ console.log("MESSAGE", message); }`
> 
> `if(widgetContext.userService.onThisCalled !== undefined){ widgetContext.userService.onThisCalled("This works!"); }`
> 
> Hope this helps anyone

Hi, how can i define this.

**Comment by claezon** [comment]
@inanlia You could do it like this:

**Widget A (transmitter)**
```javascript
const $injector = self.ctx.$scope.$injector;
const broadcastService = $injector.get(self.ctx.servicesMap.get('broadcastService'));
broadcastService.broadcast('SOME_CUSTOM_EVENT', {
    foo: 'bar',
    bax: 'baz'
});
```

**Widget B (_C, D..._) (receiver)**
```javascript
const $injector = self.ctx.$scope.$injector;
const broadcastService = $injector.get(self.ctx.servicesMap.get('broadcastService'));
broadcastService.on('SOME_CUSTOM_EVENT', (evt, msg) => {
    console.log(msg); // Handle received data as seen fit
});
```

**Comment by zidniryi** [comment]
@claezon But why is take long?

I mean I make like this on receiver :

```
let data = ""
const $injector = self.ctx.$scope.$injector;
const broadcastService = $injector.get(self.ctx.servicesMap.get('broadcastService'));
broadcastService.on('SOME_CUSTOM_EVENT', (evt, msg) => {
     data = msg
    console.log(msg); // Handle received data as seen fit
});
```


console.log(data)

But not changes the initial variable of **data**?
