### ISSUE TITLE
[Question] TBEL: Got compile error when have a switch statement inside another switch statement?

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#9760]
**Component**

 * Rule Engine
 
**Description**
It can be compiled successfully if i remove inner switch statement, so is TBEL support nested switch statement, or i missed something?

![image](https://github.com/thingsboard/thingsboard/assets/7221781/263e4a30-6b4f-443a-92c2-9c561b9e7758)

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.1

**Comment by xalt7x** [comment]
It has something to do with formatting.
A possible workaround here is to move a curly bracket that closes the "switch (b)" block to the beginning of the line (thus removing existing tab/space indentations).

Here's an example that works for me:
```
var a = 0;
switch (a) {
    case 0:
        var b = 0;
        switch (b) {
            case 0:
                break;
}
        break;
}
return {msg: msg , metadata: metadata, msgType: msgType};
```

**Comment by xalt7x** [comment]
TBEL adheres to Java code conventions, so the requirements for code review may be stricter than for Javascript. Formatting in the example above just helped to workaround the issue with the "break" statement usage.

Generally, "break" should be used for all "cases" in the "switch" except the last one. So, in the provided script example, "break" is redundant and needs to be removed.

Here's another example that works in TBEL:
```
var a = 0;
switch (a) {
    case 0:
        var b = 1;
        switch (b) {
            case 0:
                break;
            case 1:
                msg.script_works = true;
        }
}
return {msg: msg , metadata: metadata, msgType: msgType};
```

![image](https://github.com/thingsboard/thingsboard/assets/44649402/de647893-1872-49b3-923c-8bebf087f115)

**Comment by maksonlee** [comment]
> TBEL adheres to Java code conventions, so the requirements for code review may be stricter than for Javascript. Formatting in the example above just helped to workaround the issue with the "break" statement usage.
> 
> Generally, "break" should be used for all "cases" in the "switch" except the last one. So, in the provided script example, "break" is redundant and needs to be removed.
> 
> Here's another example that works in TBEL:
> 
> ```
> var a = 0;
> switch (a) {
>     case 0:
>         var b = 1;
>         switch (b) {
>             case 0:
>                 break;
>             case 1:
>                 msg.script_works = true;
>         }
> }
> return {msg: msg , metadata: metadata, msgType: msgType};
> ```
thanks for reply, but i can use "break" for all "cases" in "switch" including the last one in Java, the following code works fine.
```
public class Main {
    public static void main(String[] args) {
        var a = 0;
        switch (a) {
            case 0:
                var b = 1;
                switch (b) {
                    case 0:
                        break;
                    case 1:
                        break;
                }
        }
    }
}
```

**Comment by xalt7x** [comment]
@maksonlee 
> but i can use "break" for all "cases" in "switch" including the last one in Java

I wonder if there is a practical reason for adding "break" in the last "case".

Quoting [w3schools](https://www.w3schools.com/js/js_switch.asp):
> It is not necessary to break the last case in a switch block. The block breaks (ends) there anyway.

**Comment by maksonlee** [comment]
> Another approach is to add a "default" case statement, which is a common practice.
> 
> This code works for me:
> 
> ```
> var a = 0;
> switch (a) {
>     case 0:
>         var b = 1;
>         switch (b) {
>             case 0:
>                 break;
>             case 1:
>                 break;
>             default:
>         }
> }
> return {msg: msg , metadata: metadata, msgType: msgType};
> ```

so how can i check TBEL format error before run it? currently code editor doesn't show error until run it.

**Comment by xalt7x** [comment]
@maksonlee ,

> so how can i check TBEL format error before run it? currently code editor doesn't show error until run it.   

Thingsboard has some hints for code writing in the TBEL/JS code input fields. However, these hints do not cover all possible TBEL errors or user errors in writing or formatting code. Therefore, yes, the user needs to click the "Test" button on the "Test Script Function" page to make sure that the code really works.

---

I believe that this discussion isn't directly related to the original issue. Hope that at least some of the workarounds mentioned earlier, work for you.

**Comment by maksonlee** [comment]
> @maksonlee ,
> 
> > so how can i check TBEL format error before run it? currently code editor doesn't show error until run it.
> 
> Thingsboard has some hints for code writing in the TBEL/JS code input fields. However, these hints do not cover all possible TBEL errors or user errors in writing or formatting code. Therefore, yes, the user needs to click the "Test" button on the "Test Script Function" page to make sure that the code really works.
> 
> I believe that this discussion isn't directly related to the original issue. Hope that at least some of the workarounds mentioned earlier, work for you.

Sure, thanks for help, and it works for this issue.
