### ISSUE TITLE
[Bug] mkdir: cannot create directory ‘/data/db’: Permission denied / Error opening log file '/var/log/thingsboard/gc.log': Permission denied

### ISSUE THREAD

**Issue by SmartieTV** [thingsboard/thingsboard#9762]
**Describe the bug**
A fresh Docker installation with Kafka, closely following the guidelines from [the guide](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka), leads to some issues, preventing the container from starting properly. 

I have also used the following commands:
`sudo mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data`
`sudo mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs`

**Logs from the TB container (thingsboard-mytb-1):** 
mkdir: cannot create directory ‘/data/db’: Permission denied
The files belonging to this database system will be owned by user "thingsboard".
This user must also own the server process.
The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
initdb: error: could not create directory "/data/db": Permission denied
pg_ctl: database system initialization failed
creating directory /data/db ... Starting Postgresql...
pg_ctl: directory "/data/db" does not exist
Connecting to Postgres, 300 attempts left...
Connecting to Postgres, 299 attempts left...
Connecting to Postgres, 298 attempts left...
Connecting to Postgres, 297 attempts left...
Connecting to Postgres, 296 attempts left...
Connecting to Postgres, 295 attempts left...
...
Connecting to Postgres, 2 attempts left...
Connecting to Postgres, 1 attempts left...
Creating database...
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
Postgresql is ready
Starting ThingsBoard installation ...
Invalid -Xlog option '-Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/gc.log:time,uptime,level,tags:filecount=10,filesize=10M', see error log for details.
Error: Could not create the Java Virtual Machine.
[0.002s][error][logging] Error opening log file '/var/log/thingsboard/gc.log': Permission denied
[0.002s][error][logging] Initialization of output 'file=/var/log/thingsboard/gc.log' using options 'filecount=10,filesize=10M' failed.
Error: A fatal exception has occurred. Program will exit.
ERROR: ThingsBoard is not installed
pg_ctl: directory "/data/db" does not exist

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version 3.6.1 (CE, Postgres DB)
  * OS: Ubuntu 22.04.03 LTS, Docker 24.0.6

**Comment by xalt7x** [comment]
It's related to directory permissions. They should be owned by user 799

docker-compose.yml example from the documentation contains the relative path of the current user's home folder.
Please ensure you run "docker compose" commands from the same user that executed directory creation commands.

I can reproduce this issue if I:
- Create directories as the "root" user and run docker commands as a regular user
- Create directories as a regular user and run docker commands as the "root" user

**Comment by SmartieTV** [comment]
Hi xalt7x, thanks for your help. 

I also used some comments from [this issue](https://github.com/thingsboard/thingsboard/issues/3347) to successfully fix it.

**Comment by webber007** [comment]
centos7中安全模块selinux把权限禁掉了
挂载之前 setenforce 0
挂载之后 setenforce 1
