### ISSUE TITLE
[Question] Can we give users the ability to Create / Edit Dashboards?

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#9766]
Hello!

I have a question, we have different type of users and clients, we want to make out application more dynamic for them. 
Us as tenant administrators, are able to give them permissions to edit and add widgets to the dashboards they have access to? I do not know if there is an option to allow the Edit mode for these users. And what consequences would have for our application, would store the widgets in the scope of the user only or would be shown for all users?

Thanks!

**Comment by mykhailokornieiev** [comment]
For your purposes you need to use RBAC (Role-Based Access Control), with which you can set up the necessary permissions for each user group, so they will be able to create/edit dashboard. But please note, this feature is available only in Thingsboard PE.
Anyway, you can use the next documentation to familiarize yourself
https://thingsboard.io/docs/pe/user-guide/rbac/#thingsboard-ce-vs-pe-security-features-comparison

**Comment by Ultrazombie** [comment]
Closed due to inactive
