### ISSUE TITLE
[Question] How to use telemetry data in javascript on HTML Value Card

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#9773]
Hello
In the HTML code section, I enter the data values through ${value}, but in the JavaScript code section, I do not know how to enter.
This part is part of JavaScript code.
`<script>
var test;
hour = ${hour};
if (hour===17)
  test = 17;
};
</script>`

**Comment by Backdraft007** [comment]
You add attribute or telemetry data key in the data section. E.g. hour with description hour.
Then you can use it in JS like:
```
var hour = "${hour}";
var test;
if(hour === 17) {
  test = 17;
}

```
