### ISSUE TITLE
[Feature Request] be consistent in APIs

### ISSUE THREAD

**Issue by skewty** [thingsboard/thingsboard#9781]
![image](https://github.com/thingsboard/thingsboard/assets/9087223/68ba0a9d-0b70-43de-897b-11e13f87c2a0)

speaks for itself. sometimes all upper case, sometimes 3 letters, sometimes 4 letters, all lower case, sometimes camelCase, sometimes snake_case, sometimes 'timestamp', sometimes 'ts'.

The API has grown in complexity and functionality over years and it seems little attention was put into cleaning up / improving what is already there.

Hopefully 4.0 does a big cleanup.

**Comment by Ultrazombie** [comment]
We will take your suggestions, thank you for your attention.
Also, feel free to contribute if you notice anything like this
