### ISSUE TITLE
[Question] Thingsboard Rest Client install fail

### ISSUE THREAD

**Issue by turnede0** [thingsboard/thingsboard#9797]
**Description**
After typing `mvn clean install –DskipTests`, it always stop at failing on installing Thingsboard Rest Client

it show the error  `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project rest-client: Compilation failure
[ERROR] An unknown compilation problem occurred
`

Do you have any idea? Thank you

![image](https://github.com/thingsboard/thingsboard/assets/79206052/6b65d40f-666a-4b41-b471-edff76e736e1)

**Environment**

 * OS:  window 11
 * ThingsBoard:  release3.6
 * Browser: name and version

**Comment by devaskim** [comment]
Did you use Java 11 ?

**Comment by Clay408** [comment]
> Did you use Java 11 ?

Will there be any issues with using Java 11?

**Comment by devaskim** [comment]
No, as I know, only Java 11

**Comment by turnede0** [comment]
yes, this is java 11   openJDK 11.0.2

**Comment by turnede0** [comment]
Problem solved.I use JDK 12.0.2 to solve problem 
refer to  issue [5043](https://github.com/thingsboard/thingsboard/issues/5043)
