### ISSUE TITLE
[Bug] CE - Oauth Provider with Unsigned certificate Invalid_token_response 

### ISSUE THREAD

**Issue by zetfactor** [thingsboard/thingsboard#9799]
**Describe the bug**
Thingsboard- CE is deployed in K8s as Micro-service, once configuring Keycloak IDP (which has unsigned TLS cert) 
and try to login using Keycloak, the following Error appears:

`
[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: I/O error on POST request for "https://{xxxxx}/auth/realms/{myrealm}/protocol/openid-connect/token": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Your Server Environment**
* own setup
  * ThingsBoard Version 3.5.1 (but error occurs in all latest aswell)
  * Kubernetes Micro-service setup / error occurs also in Docker monolith setup
  * KeyCloak with Unsigned TLS Cert
  * Created a config map/volumes to inject the certificate to /etc/ssl/certs inside the pod (this solution worked with other applications)

**To Reproduce**
1. Configure Keycloak as OAuth idp
2. Make sure you inject your Keycloak Unsigned cert to /etc/ssl/certs folder inside the container/pod (tb-node & UI pods)
3. Try to login using IDP

- Other checks I did, Created an Auth0 account, created the same configurations, and it's working fine.

If anyone can support me with this, and or provide me with exact KeyCloak Client settings to make it happen, it would be great.

Thanks for your efforts

**Comment by mykhailokornieiev** [comment]
Hi
We have the next tutorials regarding Keycloak as OAuth2 configuration on the Thingsboard side.
I'm highly recommend to get familiar with both of them, since the second one just an addition to the first one

**Comment by mykhailokornieiev** [comment]
ThingsBoard allows you to provide Single Sign-On functionality for your customers and automatically create tenants, customers, or sub customers using external user management platforms, that support the OAuth 2.0 protocol.
    1. Create a client for ThingsBoard in your existing Relm or if required create a new Realm for it.
![image](https://github.com/user-attachments/assets/64729e0c-300e-4e8d-a8cd-1b2d449215f4)
    2. Go to your ThingsBoard as a System Administrator ([sysadmin@thingsboard.org](mailto:sysadmin@thingsboard.org) / sysadmin). Check the General Settings -> Base URL should not contain “/” at the end (f.e. “http://127.0.0.1:8080” instead of “https://127.0.0.1:8080/”). Then in the Home section, find the “OAuth2” icon and click on it.
![image](https://github.com/user-attachments/assets/8536276d-cb28-440d-9cf6-3dc3c120b1b0)       
    3. Check the Enable OAuth2 settings and click on + Add. Click on the window that appears, for further settings. Select the required protocol. If you decide to use the HTTP protocol, be sure to write down its port 8080 in the domain name (localhost:8080). For Keycloak we will configure the Custom provider. Click on this block.
![image](https://github.com/user-attachments/assets/af35150a-4b95-4732-8697-33b95f535502)       
    4. Copy Redirect URI template and go back to a client you created for ThingsBoard and make the next configurations:
- Paste URI to “Valid Redirect URI“
- Access type → confidential
- Implicit Flow Enabled → off
- Direct Access Grants Enabled → off
- Authorization Enabled → on
- Service Accounts Enabled → on
![image](https://github.com/user-attachments/assets/53f48340-7efc-4bdd-bdc1-d3b11076021b)       
Click “Save“
    5. Go to the “Installation” tab and chose “Format Option” and copy resource/secret to ThingsBoard Client ID/Client Secret
![image](https://github.com/user-attachments/assets/3c2d221e-b849-4f19-bb4e-d5dc7a3acdd5)
    6. To retrieve OpenID connect endpoints make an GET request to: [http://keycloakhost:keycloakport/auth/realms/](http://keycloakhost/){realm}/.well-known/openid-configuration

PowerShell:
Invoke-RestMethod -Uri "http://kk.nice.internal:8081/auth/realms/TB/.well-known/openid-configuration"

Bash:
curl http://kk.nice.internal:8081/auth/realms/TB/.well-known/openid-configuration | jq

Copy nex URIs to ThingsBoard:
- authorization_endpoint
- token_endpoint
- userinfo_endpoint
- jwks_uri
![image](https://github.com/user-attachments/assets/32e0644c-948d-48b0-ba5a-029026eb47e0)
    7. Add next scopes:
- OpenID
- profile
- email
And fill “Provider label“
![image](https://github.com/user-attachments/assets/03b8373a-1e49-4222-a45e-f8eb490c03a6)
    8. Go to the mapper and configure:
- Customer name pattern
- User groups name pattern
![image](https://github.com/user-attachments/assets/35f8ecc4-9b30-4e81-a193-3a1008105a88)
       For more information on mapper settings please refer to [Mapping of the external user into ThingBoard internal user structure](https://thingsboard.io/docs/user-guide/oauth-2-support/#mapping-of-the-external-user-into-thingboard-internal-user-structure)
    9. Click “Save”
    10. Now you should be able to login with Keycloak
![image](https://github.com/user-attachments/assets/ac7d3dfb-a460-4ed0-99cc-cdbbda9d7b60)

**Comment by mykhailokornieiev** [comment]
This article is only an addition and expansion of the previous one, I recommend using both
Testing took place on a localhost. Thingsboard PE 3.4.4 was launched as the service on port 8081. Keycloak 21.1.1 was launched in Docker on port 8080.
![image](https://github.com/user-attachments/assets/f78d971d-4c7e-4973-a791-770e172fd5ba)

1. It is necessary to create a new realm:
![image](https://github.com/user-attachments/assets/1eae77a7-3d8f-4c5b-95ae-d4b1b0298538)
![image](https://github.com/user-attachments/assets/22d943b0-4617-4bc6-bedc-710194671489)
2. Import this attached client, you can use its settings as a reference in the future:
[thingsboard.json](https://github.com/user-attachments/files/17922210/thingsboard.json)
![image](https://github.com/user-attachments/assets/3a9cca29-0b6a-4771-aca8-c0f82da073e0)
![image](https://github.com/user-attachments/assets/9feaba4a-f172-4b29-be79-a76abc28abb8)
3. Create new Realm Role:
![image](https://github.com/user-attachments/assets/273f057a-06a1-4435-ae7b-e42d50cdb6a2)
![image](https://github.com/user-attachments/assets/9073ca06-1782-4244-8896-389270911fa2)
4. Create new user:
![image](https://github.com/user-attachments/assets/e3afe078-cf7e-4440-9d0b-45ddfd32f211)
5. Go to Role Mapping and Assign role to your user:
![image](https://github.com/user-attachments/assets/c227b5ff-f006-4386-91e5-45bc98b3f451)
![image](https://github.com/user-attachments/assets/68905410-8eb8-43e9-b4a6-9e0d1beb5edb)
![image](https://github.com/user-attachments/assets/65934d38-c13d-45b9-b08d-a027b190b990)
6. Go to Credentials and setup your user’s password:
![image](https://github.com/user-attachments/assets/0d4d2d87-fa67-46f8-a7f8-b335fb81c4a4)
![image](https://github.com/user-attachments/assets/81f2647e-c467-4f03-b9ce-cc6d275df61f)
7. Fill in all the fields below (including JSON Web Key URI and User info URI):
![image](https://github.com/user-attachments/assets/c3ebee1e-7bcf-4049-a3b4-d8e7b3e2d2cf)
![image](https://github.com/user-attachments/assets/e2dec2c2-7779-4f4e-a409-0ed379044631)
You can get all this URIs using next command:
`curl http://localhost:8080/realms/master/.well-known/openid-configuration | jq`
![image](https://github.com/user-attachments/assets/d9158105-60c1-41a0-9bd2-ef0b83fa73e3)
After that, you will be able to authorize your user with Keycloak:
https://github.com/user-attachments/assets/211a82f8-fb82-4a32-a6c8-9605b2f3b16e
