### ISSUE TITLE
Chart not stacking 

### ISSUE THREAD

**Issue by PopoTheSapien** [thingsboard/thingsboard#98]
Hi.  Noticed that this graph was stacking selectively.  The yellow and green bars have similar values.  My cursor reveals the underlying green bar.

![image](https://cloud.githubusercontent.com/assets/15940445/24823252/9c9909ce-1bfc-11e7-8967-64a5ce74872e.png)

Enjoying all the features in the new 1.2.2 :)

**Comment by ashvayka** [comment]
Is this historical chart or real-time with big sliding window?

**Comment by ikulikov** [comment]
Closing due an inactivity.

**Comment by glancia** [comment]
Hi, I'm facing the same issue, both on realtime or historical chart. No matter long or short window.

**Comment by dreibelt** [comment]
When any series has a null value, the series either side of it wont stack.
![image](https://user-images.githubusercontent.com/36125043/75666503-a383f880-5cc1-11ea-98ea-2f86ec9e1a3d.png)
