### ISSUE TITLE
Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by donggangcj** [thingsboard/thingsboard#980]
Hi ! 
  I installed the thingsboard successfully through Kubernetes.Howerver,when I created a device and delete a device,maybe more operations,the thingsboard throw an Exception like this:
![image](https://user-images.githubusercontent.com/22852751/43620006-213ea90e-9703-11e8-90f1-cdb7572fc054.png)
Is that redis-service failed?

**Comment by vparomskiy** [comment]
Are you using the thingsboard cluster or change caching options in thingsboard.yml to use Redis?
Because otherwise Redis is not used inside the Thingsboard

**Comment by CooL16** [comment]
This issue has been fixed in our new releases of kubernetes https://thingsboard.io/docs/user-guide/install/cluster/minikube-cluster-setup/
