### ISSUE TITLE
[Question] Free Cloud Dashboard Device Limits?

### ISSUE THREAD

**Issue by donskytech** [thingsboard/thingsboard#9809]
**Component**

 * Generic

**Description**
I am evaluating the Thingsboard cloud and tried creating 6 devices.  I sent telemetry data for the initial 4 devices and I can see them in a card and time series chart. 
However,  for the last 2, I am not able to display it in the dashboard.
Could there be a reason or a restriction that only 4 devices are available for testing and I need to go to the PAID tier to see the telemetry data for the last two?

**Environment**

 * ThingsBoard: Cloud
 * Browser: Chrome - Ver 119

**Comment by ViacheslavKlimov** [comment]
_Maker_ subscription plan allows up to 30 devices. 
Probably you couldn't see something on dashboard due to misconfiguration. 
Check our documentation: https://thingsboard.io/docs/pe/user-guide/widgets/
