### ISSUE TITLE
[Feature Request] Allow OTA packages to be assigned to multiple profiles

### ISSUE THREAD

**Issue by stopthatcow** [thingsboard/thingsboard#9811]
I love the OTA feature of Thingsboard and I use it to distribute my firmware but I see assigning packages to a single device profile as a limitation. I use a common firmware image for devices that have several different profiles applied to them for various use cases.

I'd like to be able to assign a single OTA image to more than one device profile.

Uploading the same package multiple times (once for each profile) is a workaround, but it is not ideal.

**Comment by Ultrazombie** [comment]
This is not done by the platform's design. Use one device profile for such devices.
