### ISSUE TITLE
[Question] build fail , "'com.sun.tools.javac.tree.JCTree qualid'" error occur

### ISSUE THREAD

**Issue by turnede0** [thingsboard/thingsboard#9812]
**Description**
When I try to run the application it show the error.

![image](https://github.com/thingsboard/thingsboard/assets/79206052/2f716ed0-c8b7-4375-a140-90b5f62a68c4)

`java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'`

some people said this error relate to `lombok`  but i have no idea with error.

I tried to use JDK  11,12,14,21. Error still here.

**Environment**

 * OS:  Window 11
 * ThingsBoard: version 3.6
 * Browser: chrome

**Comment by fcemyuksel** [comment]
I have this problem too.....

**Comment by fcemyuksel** [comment]
Thank you. I tried and I did it. iPhone’umdan gönderildiokidooh ***@***.***> şunları yazdı (15 Oca 2024 17:00):﻿
Hi, did you try with JDK 17 and lombok version 1.18.30 ?

**Comment by Ruslan-Isayev** [comment]
i have the same issue, i bought new laptop and i wanted to open my project here. this project was working before i even downloaded the same jdk 20. but not working right now

**Comment by Karadkar007** [comment]
try with JDK 17 and lombok version 1.18.30

**Comment by amenehmousavi** [comment]
change version IntelliJ to 11.

**Comment by Edem003** [comment]
Change the "lombok" vervsion to 
_<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.30</version>
    <scope>provided</scope>
</dependency>_ 
on the pom.xml file.

**Comment by mohammadLogan** [comment]
the minimal Lombok version compatible with JDK 21 is 1.18.30
in pom.xml 

<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.30</version>
</dependency>
