### ISSUE TITLE
Tenant admin at highest level gets permissions denied error when logging in

### ISSUE THREAD

**Issue by lfjm2022** [thingsboard/thingsboard#9821]
**Describe the bug**
When logging in, my fellow tenant admin who is not the owner gets a permissions denied error. This error only happens when logging in and there is no additional information about the error. I checked and we have the same permissions and owner. There are no error logs that come up on their user account information

**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Firefox, Chrome
* Version 

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. Login as owner
2. Set another user as tenant admin permissions owned by your account
3. Login as other user and get permission denied error with no additional information

**Expected behavior**
If there is an error I expect an error code of some sort to help me diagnose. I expect there not to be an error because we are users with the same permissions

**Screenshots**
Error:
![Screenshot 2023-12-11  Home Page Permission Denied Error](https://github.com/thingsboard/thingsboard/assets/121903909/0845e661-124c-4e1d-b803-ad1e072c1387)

My Permissions
![Screenshot 2023-12-11 Self Owner and Permissions](https://github.com/thingsboard/thingsboard/assets/121903909/335ee9e6-49eb-4906-92a1-aec8112c0f12)

Their Permissions
![Screenshot 2023-12-11 Other owner and permissions](https://github.com/thingsboard/thingsboard/assets/121903909/4c92e393-988b-4c4b-a71b-929603dd7bcd)

Role Permissions
![Tenant Admin Permissions](https://github.com/thingsboard/thingsboard/assets/121903909/3394129a-6d01-4f20-a6df-1c60d5e965ab)

**Additional context**

**Comment by mykhailokornieiev** [comment]
Hi
Did you try to reproduce issue with DevTools (F12) -> Network. Is there more additional information about an error?
Also, did you try to use another browser or private mode?

**Comment by Ultrazombie** [comment]
Closed due to inactive
