### ISSUE TITLE
[Question] Maximum Character Setting : "Script input arguments exceed maximum allowed total args size of 100000 symbols"

### ISSUE THREAD

**Issue by GregAscolab** [thingsboard/thingsboard#9829]
**Component**
 * Converter
 * Integration

**Description**
Exactly same problem/question as #8453  !
But I'm using Thingsboard PE Cloud...

As I try to get integration from SIM Card provider (#9816), the JSON data sent by provider could exceed the limit. (Big JSON table for multiple SIM card event update at once).

Seems to be link to :  
JS_MAX_TOTAL_ARGS_SIZE <<<<<<
JS_MAX_RESULT_SIZE  
JS_MAX_SCRIPT_BODY_SIZE  

Is it possible to increase this value in TB PE Cloud ?

**Environment**
 * ThingsBoard: PE Cloud 3.6.1
 * Browser: Chrome

**Comment by ViacheslavKlimov** [comment]
What max total args size would be ok for you?
What is the average size of the payload?

**Comment by GregAscolab** [comment]
Hi,

Here is the warning from SIM card provider :  

> **Endpoint Capacity**
> Be aware that the HTTP/Webhook integration will deliver the incoming events as a list of JSON objects. Dependent on the amount of SIMs and occurred records this request can be quite large. A maximum limit of 3.000 records per request is set. 1NCE customers with a large quantity of SIMs and high number of events as such must be aware that their backend system receiving data from the stream needs to have the capacity to handle large incoming requests.

_From : [1nce HTTP/Webhook](https://help.1nce.com/dev-hub/docs/examples-data-streamer-http)_

The biggest EVENT record is approx. = 1800 characters (according examples)
Min EVENT is approx = 800 Characters

We get 3000x1800 = 5 400 000 characters  MAX

If we set an average, we always have the chance to overpass the limit and lost data...
This is the first time I work with this API, so I don't have any experience on the data volume.

**Comment by GregAscolab** [comment]
FYI :  

Last error log in my integration say :  
> end of debug message =  [truncated 680674 symbols]
> error message = "Script input arguments exceed maximum allowed total args size of 100000 symbols"

So approx. 780k symbols for the last message received...

**Comment by GregAscolab** [comment]
Hello,

Is it possible to start increase the limit to 1M character at least ? In order to start testing correctly ?
Thank you.

**Comment by ViacheslavKlimov** [comment]
Unfortunately, we can't increase the limit x10.
Consider using your own on-premise deployment

**Comment by dzhonapp** [comment]
In a microserviced (k8s) deployment where we should make this change at? 
`JS_MAX_TOTAL_ARGS_SIZE <<<<<<
JS_MAX_RESULT_SIZE
JS_MAX_SCRIPT_BODY_SIZE`
I have tried to provide env variable but it is not being respected on tb-node stateful set. 
Thanks.

**Comment by pon0marev** [comment]
```
            - name: JS_MAX_TOTAL_ARGS_SIZE
              value: "300000"
            - name: JS_MAX_RESULT_SIZE
              value: "300000"
```

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
