### ISSUE TITLE
https://demo.thingsboard.io/ service is down from yesterday

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#983]
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache/2.4.29 (Ubuntu) Server at demo.thingsboard.io Port 44

Some times I am getting below error.
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.29 (Ubuntu) Server at demo.thingsboard.io Port 443

**Comment by ashvayka** [comment]
working on this. Will have patch soon.

**Comment by wangyanyan1994** [comment]
Hi
    How are you landing https://demo.thingsboard.io/ ?
    Why did I make a mistake when I landed ?

    The wrong hints are as follows :
    Authentication failed ,

**Comment by SuneethaYamani** [comment]
@ashvayka I have installed a PE instance on AWS. It was working fine for a couple of days but now I am facing a "503 Service Unavailable" error. Can you please throw some light on why this could happen on the PE instance?

Is the PE instance on the same version as demo.thingsboard.io and therefore susceptible to the same issues?

**Comment by vparomskiy** [comment]
@SuneethaYamani demo.thingsboard.io is different from Professional Edition. Please copy your log files and create separate issue with details.

I'm closing this issue since issue with demo instance was resolved.

**Comment by mayurbaldha** [comment]
it seems to be down again ....[
![Screenshot 2019-05-15 at 2 54 40 PM](https://user-images.githubusercontent.com/10371739/57764635-77db5600-7721-11e9-9cb0-6140608c232c.png)
](url)

**Comment by TanCans** [comment]
demo.thingsboard.io is down again, could you check it?

**Comment by Ka-non** [comment]
demo.thingsboard.io is down again, could you check it?
