### ISSUE TITLE
Thingsboard on mobile phone

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#984]
Is iet possible to watch dashboards on a mobile phone? Is there maybe a specific version for that?

Thank you

**Comment by mohan-mu** [comment]
@jensvdh15 thingsboard dashboard is fully mobile responsive of course you can view it on any mobile or a tablet

**Comment by vparomskiy** [comment]
Each widget/dashboard has 'mobile' layout settings and you can configure it to customize view on mobile devices.
