### ISSUE TITLE
node external RabbitMQ

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#9843]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic
 * Configuration

**Description**
how to publish data from timeseries node to rabbitmq external node in rule chain? 
![Screenshot 2023-12-14 103151](https://github.com/thingsboard/thingsboard/assets/123174270/b5fe90e2-4f27-4b0c-9cf7-93119d1b7e1a)

Does rabbitmq configuration need to be connected to rabbitmq broker?
what should the exchange name pattern and routing key pattern contain?
![Screenshot 2023-12-14 103303](https://github.com/thingsboard/thingsboard/assets/123174270/bd9a2ceb-7d19-4a96-9895-eff3ca6a6634)

**Environment**

 * ThingsBoard: version 3.6.1 PE

**Comment by devaskim** [comment]
[This doc page](https://thingsboardb.io/docs/user-guide/rule-engine-2-0/external-nodes/#rabbitmq-node) can help

**Comment by Ultrazombie** [comment]
closed due inactivity
