### ISSUE TITLE
Feature request: default value for latest timeseries (and client, shared and server attributes)

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#985]
In my rule chain, I fetch 5 previous telemetry values. This is what my rule chain looks like:
![image](https://user-images.githubusercontent.com/893502/43648965-299dfbfc-973c-11e8-82b7-858dc951260d.png)
All the 5 scripts to the right do is to set a default value in case of failure.
Also, even though the originator attributes tool can add multiple values, it will fail if one of the values are missing, so in practice I need 1 originator attributes node for each attribute I want to fetch.

It would be great if it was possible to specify a default value for each attribute directly in the originator attribute node. If that was possible, my rule chain would be much easier to manage.

Fetching with a default value is a very common case. I would say it is required whenever the originator attribute tool is used.

**Comment by nabil-rejeb** [comment]
in the documentation you can find that:

**Outbound Message Metadata will contain configured attributes if they exist.

If attribute or telemetry was not found, it is not added into Message Metadata and still routed via Success chain.**

And i use the same "originator attributes" for diffrent kind of Devices with Different Attribute names without problem.

So you can use ONE originator with ONE script to add missing data.

**Comment by mfalkvidd** [comment]
Interesting info, thanks @nabil-rejeb 

However, it seems like the documentation is incorrect. If at least one value was missing, the rule returns _Failure_ with the following error message:
java.lang.RuntimeException: [Pulse_count_1] telemetry value is not present in the DB!
