### ISSUE TITLE
[Question] I wonder why don't update to jdk 21

### ISSUE THREAD

**Issue by nadeda** [thingsboard/thingsboard#9852]
**Component**

 * Generic

**Description**
A clear and concise details.

I wonder why don't update to jdk 21

use jdk11.

**Environment**

 * OS:  windows
 * ThingsBoard: 3.6.1
 * Browser: name and version

**Comment by xalt7x** [comment]
Thingsboard targets Long-Term Support [Java releases](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).
Port to JDK 17 is ongoing.
