### ISSUE TITLE
[Question] Send sensor data from multiple devices using LoRa to Thingsboard

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9854]
**Component**

 * Generic

**Description**
I want to send sensor data collected from multiple devices using LoRa to Thingsboard through another device acting as a gateway. These satellite devices will not have internet connection because they are intended to be in remote areas so they will not be able to connect to ThingsBoard by themselves.
The idea is to send some measurements (i.e. temperature & humidity) via LoRa from these devices to one that is connected to the Internet so it can access ThingsBoard.

Is there any way to achieve this functionality with the Community Edition?

**Environment**

 * ThingsBoard: 3.6.1

**Comment by devaskim** [comment]
For the same case we use [MQTT Gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/)

**Comment by jortega11** [comment]
Thank you! I will take a look.

**Comment by rayene01** [comment]
Hello,
I am using the MQTT gateway API to solve a similar problem. I am able to send data from LORA devices to the server without any issues. However, I am encountering difficulties when sending RPC commands from the server to the device. I need to find a way for the server to send an ID or any other key that the device gateway can use to identify the LORA device that will be controlled.
