### ISSUE TITLE
[Question] Restore deleted entity from repository

### ISSUE THREAD

**Issue by netbc** [thingsboard/thingsboard#9856]
**Component**

 * UI

**Description**
We accidently deleted a device. Can it be restored from version control repository?

**Environment**

 * OS:  Docker
 * ThingsBoard: version 3.6.1 PE
 * Browser: name and version

**Comment by ViacheslavKlimov** [comment]
Yes, of course.
https://thingsboard.io/docs/user-guide/version-control/#restore-from-git

**Comment by netbc** [comment]
This restores all devices, can I restore just one device?

**Comment by ViacheslavKlimov** [comment]
Not for now. But you could create a branch with only this particular device, and then restore the version.
