### ISSUE TITLE
is there any REST API call or Websocket call to set Client/Server Attributes ,If its available can you share it here please.

### ISSUE THREAD

**Issue by mohan-mu** [thingsboard/thingsboard#986]

**Comment by nabil-rejeb** [comment]
Take a look to thingsboard doc
https://thingsboard.io/docs/reference/rest-api/
And issue #574.

**Comment by mohan-mu** [comment]
Thanks a lot @nabil-rejeb,  so as you mentioned in  #574  i can set client Attributes using WebSocket 
Here is an example.Please correct me if i'm wrong.
{
 entityType: "DEVICE",
deviceId:deviceId,
attributeScope :"CLIENT_SCOPE ",
Attributes=[{key:"KeyName1", value:"value1"}, ... ,{key:"KeyName n", value:"value n"}]
}

**Comment by nabil-rejeb** [comment]
Hi @mohan-mu , in #574 we use the UI attribute service that do a rest api call to save new data.
You have a complete REST API Documentation at this link : [https://demo.thingsboard.io/swagger-ui.html](url)

**Comment by mohan-mu** [comment]
@nabil-rejeb  I figured out how to set Attributes(Shared and server attributes) using REST API but  I cant able to set Client Attributes
Below is my request snippet  Correct me if I had done wrong 

**Request**
http://localhost:8080/api/plugins/telemetry/DEVICE/c324a1c0-97b6-11e8-a758-1f6321ec2d39/CLIENT_SCOPE

**Request Body**
{
"key":"value"
}

**Response**
Invalid scope: CLIENT_SCOPE

So i'm getting Invalid scope: CLIENT_SCOPE as a response am i doing anything wrong

**Comment by nabil-rejeb** [comment]
That's right, only SERVER_SCOPE and SHARED_SCOPE are accepted using this REST API.
for CLIENT SCOPE you have to use the HTTP Device api to publish device attribute (may close existant device session)
[https://thingsboard.io/docs/reference/http-api/#publish-attribute-update-to-the-server](url)

**Comment by mohan-mu** [comment]
@nabil-rejeb  Thanks a lot ,I think there are lot of things to learn from you. Really its a great work thank you .
