### ISSUE TITLE
[Question] Sort function on entity table when using data post-processing function

### ISSUE THREAD

**Issue by AlexIoTBE** [thingsboard/thingsboard#9875]
When using a entity table where the latest values of entities are shown:
Is it possible to use the sort function on a data key with data post-processing function.
F.e.: Use data post-processing function: return value *10.
Sorting of this column value (value*10) seems impossible.
![Data_key_config](https://github.com/thingsboard/thingsboard/assets/99114795/0744b5c8-ce66-4f71-ad47-70479b023bee)

![Entity_table](https://github.com/thingsboard/thingsboard/assets/99114795/145f4ad2-0ccd-4234-918e-de2a7247457e)

**Comment by mykhailokornieiev** [comment]
Hi. 
The sorting was disabled for the columns to which the post-processing function is applied, as the columns are always sorted by the initial timeseries values and not by the values after the post-processing. As this feature was ambiguous to the users, many reported that the columns in the widget were out of order. Thus the decision to disable the column sorting was made.

In your case, you can use the cell content function instead, as it allows for column sorting and basically returns the same result.  The cell content function can be found in the data key configuration - Advanced tab.

**Comment by Ultrazombie** [comment]
Closed due to inactive
