### ISSUE TITLE
[Question] ThingsBoard stops after starting when using SSL for MQTT

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9879]
**Component**

 * Generic

**Description**
I wanted to implement SSL in my MQTT communications. I have generated a self-signed certificate using OpenSSL and then changed the necessary information in the configuration file to use SSL and the ceritificate I have generated. Then I restarted the services to apply the changes, but after a little time since I started the service ThingsBoard stops working. I have attached the [thingsboard.log here](https://github.com/thingsboard/thingsboard/files/13726814/thingsboard.log).

What could be causing this issue? Or which troubleshooting steps could I follow?
Thank you!

**Environment**

 * OS:  W10 Pro
 * ThingsBoard: 3.6.1

**Comment by mykhailokornieiev** [comment]
Hi. First of all, check if your certificate is located in the same as thingsboard.conf directory `/etc/thingsboard/conf/`. In this case, you need to specify in thingsboard.conf the name of the file. It must be something like
```
# export MQTT_SSL_ENABLED=true
# export MQTT_SSL_CREDENTIALS_TYPE=PEM
# export MQTT_SSL_PEM_CERT=cert.pem
# export MQTT_SSL_PEM_KEY=key.pem
```

**Comment by jortega11** [comment]
I have enabled SLL again and the service is not stopping at the moment so I will just assume that it is working now, but just to make sure, how could I check if SSL is really working or not? I'm sorry but I am a beginner in terms of security!

Thank you very much!

**Comment by mykhailokornieiev** [comment]
For such purpose, you can get familiar with the article
https://thingsboard.io/docs/user-guide/basic-mqtt/#mqtts-mqtt-over-tls

**Comment by jortega11** [comment]
Yes, apparently the issue had something to do with the certificate, but I could manage to get it working.

Thanks!
