### ISSUE TITLE
3.6 version UI Translation for 'xxx.xxx' doesn't exist

### ISSUE THREAD

**Issue by wanghuaming8** [thingsboard/thingsboard#9886]
![微信图片_20231221153404](https://github.com/thingsboard/thingsboard/assets/127464623/8b4a291b-448b-4e78-a900-7b8aa6e45f00)
![微信图片_20231221153415](https://github.com/thingsboard/thingsboard/assets/127464623/a079cef6-3860-4c33-bdda-d85b4fd45ea1)
![微信图片_20231221153419](https://github.com/thingsboard/thingsboard/assets/127464623/df97cd37-10a7-4f57-a15c-b244428faf55)

Version: 3.6
Browser selected area follows the computer, China
When I compile it, I visit the home page and find that the page component name is not displaying Chinese, but the json field name.
I tried changing browsers and found it didn't work, but when I run the ui-ngx module alone to access port 4200, the page displays correctly. What is the situation with this.

**Comment by alenas** [comment]
After upgrade - make sure you update browser cache. I was seeing the same. Had to do "CTRL+F5" on the page.

**Comment by wanghuaming8** [comment]
> 升级后 - 确保清除浏览器和代理缓存。我也看到了同样的情况。必须在页面上执行“CTRL+F5”。

I'll try

**Comment by wanghuaming8** [comment]
> After upgrade - make sure you clear browser and proxy cache. I was seeing the same. Had to do "CTRL+F5" on the page.
it work，thanks
