### ISSUE TITLE
[Question] volume mounts used in docker compose files for AWS VM tests

### ISSUE THREAD

**Issue by srihari-bg** [thingsboard/thingsboard#9888]
**ThingsBoard CE docker instance setup for AWS VM testing**

 * Installation

**Description**
Hi, I have installed the ThingsBoard CE through docker with the following instructions earlier [link](https://thingsboard.io/docs/user-guide/install/docker/?ubuntuThingsboardQueue=kafka), from which I understand that ThingsBoard needs two mounting directories (.mytb-data and .mytb-logs) to be created with required permissions.

But, as I progressed to test a VM with the instance, I came across the different configurations used in different scenarios [here](https://thingsboard.io/docs/reference/performance-aws-instances/) , From Scenario B configuration, I am unable to understand the mounting directories used, can someone please explain me the volumes and guide me through the steps to setup the scenario and be able to test the VM?

Any help will be much appreciated!
   
**Environment**

 * OS:  Ubuntu server 22.04
 * ThingsBoard: latest
 * Browser: Not Applicable

**Comment by trikimiki** [comment]
Hello!

Volumes used in this performance guide are local. They are created in Docker directories, so they are managed by Docker as well.

Volumes used in the installation guides are external and mounted on the specific user-defined path. They are not managed by Docker, so it is required to set them up and provide required permissions.

You can find more info here: https://docs.docker.com/compose/compose-file/07-volumes/

**Comment by srihari-bg** [comment]
Okay, can you please provide me some more insights on how docker manages the volumes exactly?

**Comment by trikimiki** [comment]
Hi!

Please note that this question is not related to ThingsBoad. I would recommend checking respective Docker documentation and/or relevant forums.
