### ISSUE TITLE
How to contribute language localization? 

### ISSUE THREAD

**Issue by zhw618** [thingsboard/thingsboard#99]
The newest version 1.2.2 supported Korean Localization.
I want to contribute other language localizations, for example: Chinese Localization.
The problem is, how do I do ? 

Have any documention for language contributor ?
Thanks.

**Comment by ashvayka** [comment]
Hi,
Please review following PRs to get the implementation tips https://github.com/thingsboard/thingsboard/pull/81 and https://github.com/thingsboard/thingsboard/pull/88/

**Comment by sequencer** [comment]
@zhw618 I have translated the first 400 lines...
how about you translate from the last to top?

**Comment by ashvayka** [comment]
This is now contributed.
