### ISSUE TITLE
How to manage OTA upgrades for multiple MCUs

### ISSUE THREAD

**Issue by jason-hulkman** [thingsboard/thingsboard#9905]
My IoT device has 9 MCUs, and each MCU has its own firmware. ThingsBoard's device Profile can only map one firmware OTA firmware package.
My question is: How to let one Device Profile manage multiple different OTA firmware packages?

**Comment by mykhailokornieiev** [comment]
Hi
Currently, there is no possibility to assign more than one FW and one SW per device using standard Thingsboard functionality. 
As workaround you can create something like FW pack, what will include all firmware updates for all necessary components and unpack them on the device side, or, you can use some custom solution (rule chain + dashboard's)

**Comment by jason-hulkman** [comment]
> Hi Currently, there is no possibility to assign more than one FW and one SW per device using standard Thingsboard functionality. As workaround you can create something like FW pack, what will include all firmware updates for all necessary components and unpack them on the device side, or, you can use some custom solution (rule chain + dashboard's)

I found a way to handle this multi-MCU firmware OTA upgrade scenario.

Think of the communication module in the hardware device as a gateway, and each MCU as an independent "sub-device" to report data through the gateway device.

Use the gateway to create each sub-device. The device name can use the sub-serial number of each MCU motherboard, or a special name.
Topic: v1/gateway/connect
Message:
{
   "device": "sub device mcu sn";
   "type": "sub device profile name";
}

At this point, each sub-device can independently manage its own OTA firmware or software version.

As for telemetry, attribute data grouping by MCU, reporting, rule chain, and alarm processing, the original logic may need to be split.

You can view https://thingsboard.io/docs/reference/gateway-mqtt-api/

**Comment by davidpob99** [comment]
Hi @mykhailokornieiev , are there any updates about updating several packages via OTA?

**Comment by mykhailokornieiev** [comment]
Hi @davidpob99. Such a feature request was previously added to our backlog for developers, however there is no ETA for such feature implementation. In fact, it is not clear if it will be implemented at all.

**Comment by davidpob99** [comment]
Thank you for the quick response
