### ISSUE TITLE
[Question] Setting dashboard full screen

### ISSUE THREAD

**Issue by emurilloEcourbes** [thingsboard/thingsboard#9907]
**Component**
 * UI

**Description**
I would like to set a user's dashboard to full screen by default, so that the side menu does not appear, is this possible? In tb PE I know it is possible but I have not been able to put it in the CE.

**Environment**
 * OS:  name and version
 * ThingsBoard: 3.4
 * Browser: any brower

**Comment by devaskim** [comment]
Open user details and set `Default dashboard` and `Always fullscreen`

**Comment by emurilloEcourbes** [comment]
Thanks @devaskim
