### ISSUE TITLE
[Question] How to use a filter on telemetry that is not available on every device

### ISSUE THREAD

**Issue by AlexIoTBE** [thingsboard/thingsboard#9909]
I have 46 devices, only 9 of them have a panicButton (timeseries) parameter.
8 devices with "false" and 1 device with "true".

![Filter0](https://github.com/thingsboard/thingsboard/assets/99114795/e1a19a32-214f-4ba4-87cd-6de31c216334)

When the filter panicButton is set to "false", now I only see 8 devices ==> I want to see all the 46 devices.
When the filter panicButton is set to "true", I want to see only one device.
Is this possible without adding the panicButton timeseries to all the devices?

![filter1](https://github.com/thingsboard/thingsboard/assets/99114795/ae3551ee-5581-4663-9bee-96fbef0cab4f)
![filter2](https://github.com/thingsboard/thingsboard/assets/99114795/56b93659-7ce7-4730-83f5-a8b747cfba9d)
![filter3](https://github.com/thingsboard/thingsboard/assets/99114795/5de85b23-56e7-49f9-8040-c01e560d95f0)

**Comment by ssakharova** [comment]
Hello @AlexIoTBE,

The dashboard filtering feature operates exclusively on the entities and their associated data used on the specific dashboard. 

Unfortunately, the architecture logic does not support a mechanism to apply the filter to telemetry that is not present on the entities to which the filter is applied.

Best regards,
Sofiia
