### ISSUE TITLE
MQTT Shared Attribute subscription not working

### ISSUE THREAD

**Issue by SICSoftware** [thingsboard/thingsboard#991]
I subscribed to "v1/devices/me/attributes" with my AccessKey but don't get any response when I change the shared key on the device? 
Using Thingsboard 2.1.0
Looks like the same error as in here:
https://github.com/thingsboard/thingsboard/issues/842

**Comment by vparomskiy** [comment]
I've re-verified this scenario and works as expected on latest master. 
Please, check that you update a shared attribute of the device, but not a server attribute because device will not be notified about updates of the server attributes.

**Comment by efeeyuboglu92** [comment]
Hello anyone still got the same issue? I dont get updates when i change attributes using command prompt. The attribute is being changed in the rule chain but i don't get notified even though I'm subscribed.

**Comment by ashaforost** [comment]
Hi @efeeyuboglu92 

Let me know if you still experience this issue. The latest version of thingsboard doesn't show any problems with attribute subscriptions.
