### ISSUE TITLE
How to disable notification system

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#9913]
How to disable notification system? I think this feature is not so important for me.

**Comment by mykhailokornieiev** [comment]
Hi
Currently there is no such possibility.
You can try to disable/delete templates, rules, recipients
![image](https://github.com/thingsboard/thingsboard/assets/115699895/20b2ae74-094e-41ad-8208-548e10c760fc)

**Comment by xiddjp** [comment]
I can't find this page, my thingsboard version is 3.5.1

**Comment by mykhailokornieiev** [comment]
In case of using 3.5.1, you can disable it by deleting
![image](https://github.com/thingsboard/thingsboard/assets/115699895/179247a9-cf9a-4f8b-bb1c-16d44d557d47)

**Comment by xiddjp** [comment]
ok, thanks a lot.
