### ISSUE TITLE
Know the user who performed the RPC action

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/thingsboard#9916]
Good morning, is there any way to know who is the user who performed the RPC action? The output of the button doesn't give me the username.

**Comment by mykhailokornieiev** [comment]
Hi
You can check this information in the audit logs
![image](https://github.com/thingsboard/thingsboard/assets/115699895/53ad0e4d-5c1f-420f-9550-e60ac704f1bf)

**Comment by ezeroldan24** [comment]
I understand I already knew that in that place you could see the user. But I want to use it on a dashboard for example, have it as an attribute or telemetry of the device. Do you know if this can be done from the rule chain in some way?

**Comment by mykhailokornieiev** [comment]
There is no standard solution for your purpose. 
You can try to achieve it via rule chain by listening 'RPC Call to Device' event, or the one you need. Then, you can use Rest API call rule node with audit-log-controller, to get the necessary records and then transform it to suitable form for save timeseries / attributes rule node.

**Comment by ezeroldan24** [comment]
You replied to me in Jira just :D Thank you, I keep that in mind.
