### ISSUE TITLE
[Question] Device Profiles is not working properly 

### ISSUE THREAD

**Issue by KingstonChoi** [thingsboard/thingsboard#9919]
A device profile is linked to a specific rule chain, but the device is instead pointing to the default root rule chain in ThingsBoard, not sure what is the possible reasons of causing this issue?

**Comment by devaskim** [comment]
is this profile is default?

**Comment by KingstonChoi** [comment]
Nope, link to other profile

**Comment by xalt7x** [comment]
@KingstonChoi

Please provide some details on this case:

1. Your server environment:
- OS version
- Thingsboard installation type (e.g., Ubuntu, Windows, docker, Cluster setup)

2. Your Thingsboard version and edition (CE or PE)

3. Screenshots of the:
- Default Rule Chain ("Root Rule Chain")
- Details page of the Device
- Details page of the Device Profile linked to the Device
- Rulechain linked to the device profile
