### ISSUE TITLE
[Question] delete entity through dashboard widget

### ISSUE THREAD

**Issue by asi-lhn** [thingsboard/thingsboard#9925]
**Component**
 * Generic

**Description**
hello.
is it possible to create/delete server attributes(asset) through the dashboard widget?
i want that user can add or delete a key-value-set in the dashboard. and that data could be used in other widget.

with insert widget, user can only update the value.

help me! thanks.

**Environment**
 * OS:  window
 * ThingsBoard: CE
 * Browser: Chrome

**Comment by KashifAhmd** [comment]
You can perform an API request using widget action

**Comment by evanderbird** [comment]
you can see API list here https://demo.thingsboard.io/swagger-ui/

**Comment by Ultrazombie** [comment]
closed due to inactivity
