### ISSUE TITLE
[Question] could not access property in TBEL but JS

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#9931]
**Component**

 * Rule Engine

**Description**
The following script works fine as JS but TBEL, seems that TBEL doesn't treat msg.values as a map but array list.

![image](https://github.com/thingsboard/thingsboard/assets/7221781/195c952d-598e-4aed-b82f-0d4452ab013c)

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.2

**Comment by xalt7x** [comment]
Generally, such an expression is valid for TBEL. However, just like in Javascript, some words are reserved, and it's recommended to avoid them.
The "values" name is still can be used but it must be specified as a string.
`return msg["values"].a == 0;`

**Comment by maksonlee** [comment]
> Generally, such an expression is valid for TBEL. However, just like in Javascript, some words are reserved, and it's recommended to avoid them. The "values" name is still can be used but it must be specified as a string. `return msg["values"].a == 0;`

thanks for explanation, if we push telemetry with timestamp specified, then we have "values" as key name in JSON.

![image](https://github.com/thingsboard/thingsboard/assets/7221781/47d38b6f-f40c-44f8-a356-7f2408bb154a)
