### ISSUE TITLE
About OTA ！The device memory is too small and the upgrade package is too large to verify the complete file.

### ISSUE THREAD

**Issue by wanghuaming8** [thingsboard/thingsboard#9938]
The device memory is too small and the upgrade package is too large. The complete file cannot be verified and can only be verified in segments. How to deal with this situation? Or we can only modify the source code logic and add a check code to each piece of data sent.

**Comment by jason-hulkman** [comment]
There is no need to modify the TB's OTA update logic. Just add OTA sub package update logic at device side. 

Split segment download and verification
Configure the download configuration script in the "total" firmware package
============
SubPackage, Size, Checksum, Algorithm,URL
pkg.v1.001,...
pkg.v1.002,...
...
pkg.v1.00n,...
============

all above sub package can be defined and  managed at ThingsBoard OTA. 

Assign the virtual "total" firmware on the target device, config "sub" firmware link to the "total". You can define the config at the "total" ota package description or downloaded pre-installation scrip.

About the OTA update RPC cmd, can be defined as the Server side or APP side.

**Comment by wanghuaming8** [comment]
> 无需修改TB的OTA更新逻辑。只需在设备端添加OTA分包更新逻辑即可。
> 
> 分段下载和验证 配置“总”固件包中的下载配置脚本 /////////////////////// SubPackage, Size, Checksum, Algorithm,URL pkg .v1.001,... pkg.v1.002,... ... pkg.v1.00n,... /////////////////////// //
> 
> 以上所有子包都可以在 ThingsBoard OTA 上定义和管理。
> 
> 在目标设备上分配虚拟“总”固件，将“子”固件链接配置到“总”。您可以在“总”OTA 包描述或下载的预安装脚本中定义配置。
> 
> 关于OTA更新RPC cmd，可以定义为Server端或APP端。

i will try

**Comment by Ultrazombie** [comment]
closed due to inactivity
