### ISSUE TITLE
Unable to execute intsall.sh file of thingsboard community edition on ubuntu server

### ISSUE THREAD

**Issue by subrataghosh** [thingsboard/thingsboard#9942]
I have created 1 ec2 server from the aws free tier account.Now I am trying to install thingsboard on it.I have follow the steps that mention on the official [doc ](https://thingsboard.io/docs/user-guide/install/ubuntu/).But When I execute the following cmd , 

sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo

Getting following error

$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
sudo: unable to execute /usr/share/thingsboard/bin/install/install.sh: No such file or directory

**Comment by Backdraft007** [comment]
`sudo dpkg -i thingsboard-3.6.2.deb` runs without problems?
What is the output of 
`ls -al /usr/share/thingsboard/bin/install/`
and
`cat /var/log/thingsboard/install.log`

**Comment by Ultrazombie** [comment]
Hello @subrataghosh 
Please reply to the comment above so we can help you if the problem still exists.

**Comment by tranvanchienhn** [comment]
hi, 

![Image](https://github.com/user-attachments/assets/785e631b-6f3c-4995-bc26-59e48dc35188)

> Hello [@subrataghosh](https://github.com/subrataghosh) Please reply to the comment above so we can help you if the problem still exists.
