### ISSUE TITLE
After switch rule node script from javascript to tbel, do i still need run js-executor service to run tbel script?

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#9951]
I switched rule node script from rulenode.script-lang-java-script to rulenode.script-lang-tbel, do i still need run js-executor service to run tbel script?
In offical doc(https://thingsboard.io/docs/user-guide/tbel/), it said "The Rule Engine and JS executors communicate through the queue ",
how about tbel? Is rule engine need to communicate with queue?
Hope someone to answer.

**Comment by Ultrazombie** [comment]
Hello @xiddjp,
TBEL scripts don't require js-executor service and executing on thingsboard service.
