### ISSUE TITLE
[Question] timezone in tooltip in time series widget

### ISSUE THREAD

**Issue by inakigoicolea** [thingsboard/thingsboard#9969]
We have a dashboard with a few time series widgets. We have users and devices sending information from all over the world. So, each widget can be set to a different time zone. 

The widgets change the display of the data according to the time zone correctly.

However, the time series widget tooltip, the small dark window that pops up when you hover on a data point, always shows the browser time zone, regardless of the time zone configured in that widget.

Any suggestion on how to avoid this? 

Thanks!

**Comment by mykhailokornieiev** [comment]
I see that you've already created a similar request on our support portal. I will duplicate the final solution here after we solve it on the support portal.

**Comment by mykhailokornieiev** [comment]
As promised, duplicate the conclusion here:
This behavior is related to dynamicaly changing timezone both in widget and PC settings one by one. 
To avoid it, there is a few workarounds:
1. Set up necessary timezone in widget, without changing PC timezone
2. Change PC timezone and set the widget timezone on "Browser time"
