### ISSUE TITLE
[Question] How to make dashboard visible to all users

### ISSUE THREAD

**Issue by ifelse-code** [thingsboard/thingsboard#9973]
I would like to know how to make dashboards visible to all users. Do I need to share it manually with all clients? Is there any smarter way than doing this?

**Environment**
Thingsboard PE

**Comment by trikimiki** [comment]
Hi!

You can share a dashboard group with a specific customer group: https://thingsboard.io/docs/pe/user-guide/dashboards/#share-dashboard-group. If you have multiple customers, you can share the dashboard multiple times.
You can also make a dashboard group public, this will make dashboards accessible to anyone with the link to it, including not logged in users: https://thingsboard.io/docs/pe/user-guide/dashboards/#make-dashboard-group-public

**Comment by ifelse-code** [comment]
@trikimiki thank you! Maybe I was not very clear with my question. The way you pointed is the way I already do this. I want to know if there is another way to make this visible to all customers without manually sharing every time a client is created.

**Comment by evanderbird** [comment]
I dont think it has configuration for it. 
But maybe we can create triger in rule-engine, when new Customer entity created, then create rulechain triger to add dashboard role-access to that new Customer user group

**Comment by trikimiki** [comment]
@ifelse-code you can share the dashboard with group "All"
additionally, there is a way to make dashboard public for anyone with the link: https://thingsboard.io/docs/user-guide/dashboards/#make-dashboard-public
