### ISSUE TITLE
[Bug] Change originator node returns unknown asset

### ISSUE THREAD

**Issue by netbc** [thingsboard/thingsboard#9981]
**Describe the bug**
After the upgrade to 3.6.2 the 'change originator' rule chain node changes originator to an asset that does not exist. 

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version 3.6.2PE
  * OS Name and Version docker

**Expected behavior**
Should change originator to the related asset

**Comment by netbc** [comment]
Apparently, when the related asset gets deleted the relation data still remains within device data.

**Comment by Ultrazombie** [comment]
Hello @netbc,
Fixed in the 3.6.3 version.
