### ISSUE TITLE
[Bug] `repo.thingsboard.io` certificate has expired

### ISSUE THREAD

**Issue by jacksoncurrie** [thingsboard/thingsboard#9983]
Just a heads-up, the certificate for your maven repo has expired.

The certificate for `repo.thingsboard.io` expired at around: 15:16, 11th January, 2024 (UTC).

![image](https://github.com/thingsboard/thingsboard/assets/22111473/b667a953-97a8-406c-a366-492f6272936a)

**Comment by Ultrazombie** [comment]
Thanks for pointing out.
Fixed.
