### ISSUE TITLE
[Feature Request] Entities table multiple data sources

### ISSUE THREAD

**Issue by gednz** [thingsboard/thingsboard#9985]
Situation 1:
I have different device types that I wish to show in one table. 
Currently only one data source (alias) is allowed in the Entities Table widget which means I cannot use a second alias for the second device type.

Situation 2
I have devices that support up to 4 sensors of different types. 
I would like to be able to add 4 datasources (alias/filter combinations) and use the filter to only show if a particular type of sensor is present on that sensor channel.

I would then be able to create a row click action popup to configure that sensors attributes.

**Comment by evanderbird** [comment]
I think solution for this, you can create your own custom widget by export existing Entity Table widget 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/96f758ab-2725-4b99-9d23-29dd341e2e1e)
export and put it (import) in your own Widget Bundle (just create new one)
then you can edit that widget, change parameter `maxDatasources` to more than one. 
![image](https://github.com/thingsboard/thingsboard/assets/12267053/0d0f009c-13a5-459f-a8de-068e75d5d282)

**Comment by gednz** [comment]
Hi evanderbird

Thanks for the idea. 
I tried this and while it lets you add more data sources, unfortunately only the first is displayed/used.

**Comment by evanderbird** [comment]
hmm unexpected, 
did you use filter or if dont mind you can shre what config in your dasboard?

**Comment by gednz** [comment]
My understanding of how widgets work and how to create them ends at saving an existing widget and making minor changes.

**Comment by andreasbergkvist** [comment]
I would like to +1 for this feature as well. I am building generic dashboards which are largely powered by entity aliases that are filtered by "Entities by group name". I just now had a wish to use the same table for two different aliases, and came up short.
The only working solution that I've come up with is to use two tables, which for several customers would result in one empty table.

**Comment by jource08** [comment]
It's hardcoded to the component file to read the first index of datasource. [Source Code](https://github.com/thingsboard/thingsboard/blob/c4e5ab65ee73a604cab2d374c98b232d42390517/ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts#L423)
Guess we can do nothing about it unless to create a custom widget from scratch.

![image](https://github.com/thingsboard/thingsboard/assets/43811204/e2bfd6c3-ed51-46b3-9dd5-168387bf4f84)

**Comment by mykhailokornieiev** [comment]
Hi
We already have such feature request in our backlog. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
