### ISSUE TITLE
Where is thingsboard source code directory in ubuntu?

### ISSUE THREAD

**Issue by zahidurrahman** [thingsboard/thingsboard#999]
Hi.I am new in thingsboard.I have install thingsboard on ubuntu and run it locally.It works fine for me.I want to change the logo and design of it.I don not know which directory the source code has.Could anyone help me to solve it our.thanks a lot.

**Comment by mp-loki** [comment]
Hi @zahidurrahman. Thank you for your interest in ThingsBoard!
There is no source code directory if you have installed ThingsBoard as a service. 
To make changes to the original code you need to check it out from Git. Please see [How to contribute](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/) guide for reference

**Comment by zahidurrahman** [comment]
Thanks a lot sir.I am so happy for fast reply.Love this community a lot

**Comment by yhu2019** [comment]
Hi @zahidurrahman Have you end up find the solutions yet? I have the same question too.
