### ISSUE TITLE
[Question] Error while generating token to Outgoing Mail Server

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#9993]
**Component**

 * Generic

**Description**
I'm getting the error bellow while trying generating the token. Anyone can help ?

![image](https://github.com/thingsboard/thingsboard/assets/7483656/c025f012-5951-4b1d-b428-6105019e077a)
![MicrosoftTeams-image (16)](https://github.com/thingsboard/thingsboard/assets/7483656/bed195a3-f278-47cb-8842-9112a1c190d5)

**Environment**

 * ThingsBoard: Cloud

**Comment by mykhailokornieiev** [comment]
Hi
Please make sure that you’ve repeated all steps from this documentation https://thingsboard.io/docs/pe/user-guide/ui/mail-settings/#office-365-configuration-with-oauth2-authentication-example 
If yes, then the problem must be on the Office365 side. 
As practice shows, similar problems may occur when using the Office 365 Oauth2 option as SNMP. Unfortunately, I cannot tell you which setting on the Office 365 side is responsible for that. In this case, I can recommend trying the other options for sending emails listed in the documentation.

**Comment by lstarke** [comment]
Thank you @mykhailokornieiev. I'll check internally.

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
